### ISSUE TITLE
[Native Image] Oracle SQLcl Version 24.3.0.285.0530

### ISSUE THREAD

**Issue by asgeirn** [oracle/graal#10006]
### Describe the Issue

Attempting to build a native image of Oracle SQLcl Version 24.3.0.285.0530 fails within oracle.jdbc.nativeimage.NativeImageFeature.

### Using the latest version of GraalVM can resolve many issues.

- [x] I tried with the [latest version](https://www.graalvm.org/downloads/) of GraalVM.

### GraalVM Version

java version "23.0.1" 2024-10-15
Java(TM) SE Runtime Environment Oracle GraalVM 23.0.1+11.1 (build 23.0.1+11-jvmci-b01)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 23.0.1+11.1 (build 23.0.1+11-jvmci-b01, mixed mode, sharing)

### Operating System and Version

Darwin M-KX6N12W65G 23.6.0 Darwin Kernel Version 23.6.0: Thu Sep 12 23:35:10 PDT 2024; root:xnu-10063.141.1.701.1~1/RELEASE_ARM64_T6030 arm64

### Build Command

```
$JAVA_HOME/bin/native-image --diagnostics-mode --enable-preview --add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.configure=ALL-UNNAMED -cp $(find . -name \*.jar | tr '\n' :) oracle.dbtools.raptor.scriptrunner.cmdline.SqlCli
```

### Expected Behavior

A native image of sqlcl

### Actual Behavior

Error: Feature defined by oracle.jdbc.nativeimage.NativeImageFeature unexpectedly failed with a(n) java.lang.NoSuchMethodError. Please report this problem to the authors of oracle.jdbc.nativeimage.NativeImageFeature.

### Steps to Reproduce

1. Download and extract sqlcl
2. cd into sqlcl
3. Run the build command above

### Build Log Output and Error Messages

```
Error: Feature defined by oracle.jdbc.nativeimage.NativeImageFeature unexpectedly failed with a(n) java.lang.NoSuchMethodError. Please report this problem to the authors of oracle.jdbc.nativeimage.NativeImageFeature.
Caused by: java.lang.NoSuchMethodError: 'void com.oracle.svm.core.configure.ResourcesRegistry.addResourceBundles(java.lang.String)'
	at oracle.jdbc.nativeimage.NativeImageFeature.beforeAnalysis(NativeImageFeature.java:81)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$10(NativeImageGenerator.java:822)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:93)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:822)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:592)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:554)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:528)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:711)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:139)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)
Internal exception: com.oracle.svm.core.util.UserError$UserException: Feature defined by oracle.jdbc.nativeimage.NativeImageFeature unexpectedly failed with a(n) java.lang.NoSuchMethodError. Please report this problem to the authors of oracle.jdbc.nativeimage.NativeImageFeature.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:97)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.handleFeatureError(FeatureHandler.java:299)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:95)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:822)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:592)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:554)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:528)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:711)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:139)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)
Caused by: java.lang.NoSuchMethodError: 'void com.oracle.svm.core.configure.ResourcesRegistry.addResourceBundles(java.lang.String)'
	at oracle.jdbc.nativeimage.NativeImageFeature.beforeAnalysis(NativeImageFeature.java:81)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$10(NativeImageGenerator.java:822)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:93)
	... 7 more
```

**Comment by oubidar-Abderrahim** [comment]
According to the error, `oracle.jdbc.nativeimage.NativeImageFeature` calls the following Native Image internal function, which is not an API:  `com.oracle.svm.core.configure.ResourcesRegistry.addResourceBundles(String)`. 
So, this would be an issue for the JDBC team

**Comment by asgeirn** [comment]
Could you provide me with directions on where to report this issue?

**Comment by oubidar-Abderrahim** [comment]
We contacted the JDBC team and created a internal ticket for this issue
