### ISSUE TITLE
[Native Image] Unable to build as main class is not found in multi module project

### ISSUE THREAD

**Issue by justmike1** [oracle/graal#10069]
### Describe the Issue

I am running the following:

```(shell)
./gradlew --info --stacktrace --console=plain --no-daemon clean ":services:auth:bootJar"
```

which works successfully, it is the current build command we do for a few years which is working, and we want to migrate to GraalVM

```(shell)
> native-image --no-fallback --initialize-at-build-time --verbose \
    -cp /Users/mikej/velotix/velotix-server/services/auth/build/libs/auth.jar \
    -H:Class=ai.velotix.auth.AuthApplicationKt;
```

gets me the error:

```(shell)
========================================================================================================================
GraalVM Native Image: Generating 'ai.velotix.auth.authapplicationkt' (executable)...
========================================================================================================================
[1/8] Initializing...                                                                                    (0.0s @ 0.16GB)
Error: Main entry point class 'ai.velotix.auth.AuthApplicationKt' neither found on
classpath: '/Users/mikej/velotix/velotix-server/services/auth/build/libs/auth.jar' nor
modulepath: '/Library/Java/JavaVirtualMachines/graalvm-23.jdk/Contents/Home/lib/svm/library-support.jar'.
com.oracle.svm.driver.NativeImage$NativeImageError
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.showError(NativeImage.java:2300)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.build(NativeImage.java:1888)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1847)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.main(NativeImage.java:1829)
	at java.base@23.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```

gradle.build.kts
```(shell)
import org.springframework.boot.gradle.tasks.bundling.BootJar
import org.springframework.boot.gradle.tasks.run.BootRun

plugins {
    id("ai.velotix.spring-service-conventions")
    id("org.springframework.boot") version "3.3.5"
    id("org.graalvm.buildtools.native") version "0.10.3"
}

repositories {
    mavenCentral()
    maven("https://repo.spring.io/milestone")
    maven("https://build.shibboleth.net/nexus/content/repositories/releases/") // for OpenSAML dependency
}

dependencies {
............
}

apply(plugin = "io.spring.dependency-management")

springBoot {
    mainClass.set("ai.velotix.auth.AuthApplicationKt")
    buildInfo()
}

graalvmNative {
    binaries {
        named("main") {
            mainClass.set("ai.velotix.auth.AuthApplicationKt")
            buildArgs.addAll(
                "--no-fallback",
                "--initialize-at-build-time"
            )
        }
    }
}

tasks.named<BootJar>("bootJar") {
    enabled = true
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named<Jar>("jar") {
    enabled = false
}

tasks.named<BootRun>("bootRun") {
    systemProperties = System.getProperties() as Map<String, Any>
}
```

### Using the latest version of GraalVM can resolve many issues.

- [x] I tried with the [latest version](https://www.graalvm.org/downloads/) of GraalVM.

### GraalVM Version

```(shell)
> java --version
java 23.0.1 2024-10-15
Java(TM) SE Runtime Environment Oracle GraalVM 23.0.1+11.1 (build 23.0.1+11-jvmci-b01)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 23.0.1+11.1 (build 23.0.1+11-jvmci-b01, mixed mode, sharing)
```

### Operating System and Version

Darwin Mikes-New-MacBook-Pro.local 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:25 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6030 arm64

### Build Command

```(shell)
> native-image --no-fallback --initialize-at-build-time --verbose \
    -cp /Users/mikej/velotix/velotix-server/services/auth/build/libs/auth.jar \
    -H:Class=ai.velotix.auth.AuthApplicationKt
```

### Expected Behavior

Never ran it successfully, I expect to build a native image.

### Actual Behavior

Build of bootJar successful as usual, `native-image` receives 

```(shell)
Main entry point class 'ai.velotix.auth.AuthApplicationKt' neither found on
``` 

### Steps to Reproduce

I can't share the code...

### Build Log Output and Error Messages

```(shell)
========================================================================================================================
GraalVM Native Image: Generating 'ai.velotix.auth.authapplicationkt' (executable)...
========================================================================================================================
[1/8] Initializing...                                                                                    (0.0s @ 0.16GB)
Error: Main entry point class 'ai.velotix.auth.AuthApplicationKt' neither found on
classpath: '/Users/mikej/velotix/velotix-server/services/auth/build/libs/auth.jar' nor
modulepath: '/Library/Java/JavaVirtualMachines/graalvm-23.jdk/Contents/Home/lib/svm/library-support.jar'.
com.oracle.svm.driver.NativeImage$NativeImageError
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.showError(NativeImage.java:2300)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.build(NativeImage.java:1888)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1847)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.main(NativeImage.java:1829)
	at java.base@23.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
~
```

**Comment by oubidar-Abderrahim** [comment]
For SpringBoot application, you need to follow certain recommendation to successfully build a native image. We have a guide about this [here](https://www.graalvm.org/latest/reference-manual/native-image/guides/build-spring-boot-app-into-native-executable/) and you can find more on the internet.

**Comment by ntycx** [comment]
The guide doesn't tell us how to compile springboot projects with multiple modules. When I run nativeCompile in the root module, it tells me that the main class can't be found. exe file can not find the other module configuration files.

**Comment by oubidar-Abderrahim** [comment]
Any update?
