### ISSUE TITLE
[native-image] Scala Apache HttpClient LogConfigurationException

### ISSUE THREAD

**Issue by kronolynx** [oracle/graal#1009]
I'm getting this error
```
Exception in thread "main" org.apache.commons.logging.LogConfigurationException: java.lang.ClassNotFoundException: org.
apache.commons.logging.impl.LogFactoryImpl (Caused by java.lang.ClassNotFoundException: org.apache.commons.logging.impl
.LogFactoryImpl)                                                                                                       
        at org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1158)                                   
        at org.apache.commons.logging.LogFactory$2.run(LogFactory.java:960)                                            
        at java.security.AccessController.doPrivileged(AccessController.java:62)                                       
        at org.apache.commons.logging.LogFactory.newFactory(LogFactory.java:957)                                       
        at org.apache.commons.logging.LogFactory.getFactory(LogFactory.java:624)                                       
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:655)                                           
        at org.apache.http.conn.ssl.DefaultHostnameVerifier.<init>(DefaultHostnameVerifier.java:82)                    
        at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:966)
        at org.apache.http.impl.client.HttpClients.createDefault(HttpClients.java:56)
        at example.Sample$.runSample(ScalaApacheHttpRestClient.scala:19)
        at example.ScalaApacheHttpRestClient$.main(ScalaApacheHttpRestClient.scala:51)
        at example.ScalaApacheHttpRestClient.main(ScalaApacheHttpRestClient.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.impl.LogFactoryImpl
        at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:51)
        at java.lang.ClassLoader.loadClass(Target_java_lang_ClassLoader.java:127)
        at org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1020)
        ... 11 more
```

In issue #768 someone suggest to fix this error using:
```
{
    "name" : "org.apache.commons.logging.impl.Jdk14Logger",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true
  }
```

I can't make it work on `GraalVM 1.0.0-rc12` and I haven't found any other solution.

### Steps to reproduce
https://github.com/kronolynx/scala-graal-apache-http

After cloning the project
```
$ sbt assembly
$ native-image --enable-url-protocols=http,https -H:ReflectionConfigurationFiles=reflect.json --no-server -jar target/scala-2.12/graal-http.jar 
$ ./graal-http
```

**Comment by Jurrie** [comment]
Hi @kronolynx! While not a direct answer to your question why the reflection configuration doesn't work, I do have an alternative. You could substitute the methods in LogFactory and LogFactoryImpl that do reflection. With the following code (which is based on [the work of @DmPanov](https://github.com/DmPanov/graal-vs-apache-httpclient), I get this to work:

```java
@TargetClass(LogFactory.class)
final class LogFactorySubstituted
{
	@Substitute
	protected static LogFactory newFactory(final String factoryClass, final ClassLoader classLoader, final ClassLoader contextClassLoader)
	{
		return new LogFactoryImpl();
	}
}

@TargetClass(LogFactoryImpl.class)
final class LogFactoryImplSubstituted
{
	@Substitute
	private Log discoverLogImplementation(String logCategory)
	{
		return new SimpleLog(logCategory);
	}
}
```

The used annotations are in package [com.oracle.substratevm:svm](https://mvnrepository.com/artifact/com.oracle.substratevm/svm/1.0.0-rc12).

Of course, you loose the functionality to determine the delegate logging facility at runtime.

**Comment by kronolynx** [comment]
Thanks @Jurrie 
In my case I'm not sure if it's possible to use that kind of substitution, I'm actually trying to make a project in scala with [elastic4s](https://github.com/sksamuel/elastic4s). Elastic4s uses the apache http client.

**Comment by cstancu** [comment]
@kronolynx the behavior has changed since this issue was opened. I suggest using the Native Image agent to get the complete reflection configuration.
