### ISSUE TITLE
Graal Compiler - ClassCastException while parsing

### ISSUE THREAD

**Issue by HanyzPAPU** [oracle/graal#10130]
**Describe the issue**

Compiling the `test()` method of the attached classfile causes ClassCastException.

**Steps to reproduce the issue**
Please include both build steps as well as run steps

1.  `git clone https://github.com/HanyzPAPU/graal`
2. `cd graal/compiler/src/jdk.graal.compiler.test.bytecodefuzz`
3. `mkdir src/build && cd src/build &&  cmake .. && make && cd ../..`
4. `mx build`
5. `./run-reproducer Crash_00f521f45437ed3f4c4bedf886a4e6d8c07357cf`

**Describe GraalVM and your environment:**
 - GraalVM version: **built from commit 137a94ee053b2be6ef3605404c2247f52849cf37**
 - JDK major version: **24**
 - OS: **Ubuntu 22.04 WSL2 on Win11**
 - Architecture: **Intel x86-64**

**More details**
Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
[Use -Djdk.graal.LogFile=<path> to redirect Graal log output to a file.]
[thread:3] scope: main
  [thread:3] scope: main.Parsing
  Context: HotSpotMethod<Catch_NPE_010.test()>
  Context: StructuredGraph:1{HotSpotMethod<Catch_NPE_010.test()>}
      [thread:3] scope: main.Parsing.PhaseSuite.HotSpotGraphBuilderPhase
      Exception raised in scope main.Parsing.PhaseSuite.HotSpotGraphBuilderPhase: java.lang.ClassCastException: class jdk.graal.compiler.nodes.InvokeNode cannot be cast to class jdk.graal.compiler.nodes.AbstractMergeNode (jdk.graal.compiler.nodes.InvokeNode and jdk.graal.compiler.nodes.AbstractMergeNode are in module jdk.graal.compiler of loader 'platform')
      	at jdk.graal.compiler/jdk.graal.compiler.java.BytecodeParser.createTarget(BytecodeParser.java:3498)
      	at jdk.graal.compiler/jdk.graal.compiler.java.BytecodeParser.appendGoto(BytecodeParser.java:3685)
      	at jdk.graal.compiler/jdk.graal.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3795)
      	at jdk.graal.compiler/jdk.graal.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3730)
      	at jdk.graal.compiler/jdk.graal.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3577)
      	at jdk.graal.compiler/jdk.graal.compiler.java.BytecodeParser.build(BytecodeParser.java:1163)
      	at jdk.graal.compiler/jdk.graal.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1055)
      	at jdk.graal.compiler/jdk.graal.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:103)
      	at jdk.graal.compiler/jdk.graal.compiler.java.GraphBuilderPhase.run(GraphBuilderPhase.java:68)
      	at jdk.graal.compiler/jdk.graal.compiler.java.GraphBuilderPhase.run(GraphBuilderPhase.java:43)
      	at jdk.graal.compiler/jdk.graal.compiler.phases.BasePhase.apply(BasePhase.java:468)
      	at jdk.graal.compiler/jdk.graal.compiler.phases.BasePhase.apply(BasePhase.java:335)
      	at jdk.graal.compiler/jdk.graal.compiler.phases.PhaseSuite.run(PhaseSuite.java:423)
      	at jdk.graal.compiler/jdk.graal.compiler.phases.BasePhase.apply(BasePhase.java:468)
      	at jdk.graal.compiler/jdk.graal.compiler.phases.BasePhase.apply(BasePhase.java:335)
      	at jdk.graal.compiler.core.test.GraalCompilerTest.parse(GraalCompilerTest.java:1580)
      	at jdk.graal.compiler.core.test.GraalCompilerTest.parseEager(GraalCompilerTest.java:1509)
      	at jdk.graal.compiler.core.test.GraalCompilerTest.parseForCompile(GraalCompilerTest.java:1214)
      	at jdk.graal.compiler.core.test.GraalCompilerTest.getCode(GraalCompilerTest.java:1151)
      	at jdk.graal.compiler.core.test.GraalCompilerTest.getCode(GraalCompilerTest.java:1094)
      	at jdk.graal.compiler.test.bytecodefuzz.FuzzTarget.access$400(FuzzTarget.java:10)
      	at jdk.graal.compiler.test.bytecodefuzz.FuzzTarget$TestExecution.testCompile(FuzzTarget.java:82)
      	at jdk.graal.compiler.test.bytecodefuzz.FuzzTarget.testBytecode(FuzzTarget.java:107)
      	at jdk.graal.compiler.test.bytecodefuzz.FuzzTarget.fuzzerTestOneInput(FuzzTarget.java:138)
      	at Crash_00f521f45437ed3f4c4bedf886a4e6d8c07357cf.main(Crash_00f521f45437ed3f4c4bedf886a4e6d8c07357cf.java:26)
```
A classfile containing the code which causes the crash, together with dissasembly: [Classfile.zip](https://github.com/user-attachments/files/17844285/Classfile.zip)

**Comment by davleopo** [comment]
@HanyzPAPU  thanks for your report. We will have a look.

@rmosaner  can you have a look ?

**Comment by HanyzPAPU** [comment]
I added a building step I forgot originally.

**Comment by rmosaner** [comment]
Thanks @HanyzPAPU for the detailed reproducer.

The issue is internally tracked as [GR-59966].

**Comment by rmosaner** [comment]
The problem should be fixed with this [PR](https://github.com/oracle/graal/pull/10142).
