### ISSUE TITLE
Graal Compiler - GraalError: failed guarantee

### ISSUE THREAD

**Issue by HanyzPAPU** [oracle/graal#10131]
**Describe the issue**

The compilation of the method `duffSum()` from the attached classfile crashes. 

**Steps to reproduce the issue**
Please include both build steps as well as run steps

1.  `git clone https://github.com/HanyzPAPU/graal`
2. `cd graal/compiler/src/jdk.graal.compiler.test.bytecodefuzz`
3. `mkdir src/build && cd src/build && cmake .. && make && cd ../..`
4. `mx build`
5. `./run-reproducer Crash_1305503bcc0d111f3497e0c517b573236b1bb0ad`

**Describe GraalVM and your environment:**
 - GraalVM version: **built from commit 137a94ee053b2be6ef3605404c2247f52849cf37**
 - JDK major version: **24**
 - OS: **Ubuntu 22.04 WSL2 on Win11**
 - Architecture: **Intel x86-64**

**More details**
Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
Exception in thread "main" jdk.graal.compiler.debug.GraalError: failed guarantee: Adding 1449|ValueProxy to the graph but its input -1|ValueProxy is not alive
	at jdk.graal.compiler/jdk.graal.compiler.debug.GraalError.guarantee(GraalError.java:118)
	at jdk.graal.compiler/jdk.graal.compiler.graph.NodeClass.registerAtInputsAsUsage(NodeClass.java:1428)
	at jdk.graal.compiler/jdk.graal.compiler.graph.Node.initialize(Node.java:832)
	at jdk.graal.compiler/jdk.graal.compiler.graph.Graph.addHelper(Graph.java:646)
	at jdk.graal.compiler/jdk.graal.compiler.graph.Graph.uniqueHelper(Graph.java:918)
	at jdk.graal.compiler/jdk.graal.compiler.graph.Graph.addOrUnique(Graph.java:533)
	at jdk.graal.compiler/jdk.graal.compiler.nodes.java.ArrayLengthNode.maybeAddPositivePi(ArrayLengthNode.java:190)
	at jdk.graal.compiler/jdk.graal.compiler.nodes.memory.ReadNode.simplify(ReadNode.java:182)
	at jdk.graal.compiler/jdk.graal.compiler.phases.common.CanonicalizerPhase.tryCanonicalize(CanonicalizerPhase.java:611)
	at jdk.graal.compiler/jdk.graal.compiler.phases.common.CanonicalizerPhase.processNode(CanonicalizerPhase.java:504)
	at jdk.graal.compiler/jdk.graal.compiler.phases.common.CanonicalizerPhase.processWorkSet(CanonicalizerPhase.java:349)
	at jdk.graal.compiler/jdk.graal.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:77)
	at jdk.graal.compiler/jdk.graal.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:45)
	at jdk.graal.compiler/jdk.graal.compiler.phases.BasePhase.apply(BasePhase.java:468)
	at jdk.graal.compiler/jdk.graal.compiler.phases.BasePhase.apply(BasePhase.java:335)
	at jdk.graal.compiler/jdk.graal.compiler.phases.common.CanonicalizerPhase.applyIncremental(CanonicalizerPhase.java:268)
	at jdk.graal.compiler/jdk.graal.compiler.phases.common.LoweringPhase.lower(LoweringPhase.java:306)
	at jdk.graal.compiler/jdk.graal.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:276)
	at jdk.graal.compiler/jdk.graal.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:116)
	at jdk.graal.compiler/jdk.graal.compiler.phases.BasePhase.apply(BasePhase.java:468)
	at jdk.graal.compiler/jdk.graal.compiler.phases.BasePhase.apply(BasePhase.java:335)
	at jdk.graal.compiler/jdk.graal.compiler.phases.PhaseSuite.run(PhaseSuite.java:423)
	at jdk.graal.compiler/jdk.graal.compiler.phases.BasePhase.apply(BasePhase.java:468)
	at jdk.graal.compiler/jdk.graal.compiler.phases.BasePhase.apply(BasePhase.java:335)
	at jdk.graal.compiler/jdk.graal.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:276)
	at jdk.graal.compiler/jdk.graal.compiler.core.GraalCompiler.compile(GraalCompiler.java:150)
	at jdk.graal.compiler.core.test.GraalCompilerTest.compile(GraalCompilerTest.java:1291)
	at jdk.graal.compiler.core.test.GraalCompilerTest.getCode(GraalCompilerTest.java:1156)
	at jdk.graal.compiler.core.test.GraalCompilerTest.getCode(GraalCompilerTest.java:1094)
	at jdk.graal.compiler.test.bytecodefuzz.FuzzTarget.access$400(FuzzTarget.java:10)
	at jdk.graal.compiler.test.bytecodefuzz.FuzzTarget$TestExecution.testCompile(FuzzTarget.java:82)
	at jdk.graal.compiler.test.bytecodefuzz.FuzzTarget.testBytecode(FuzzTarget.java:107)
	at jdk.graal.compiler.test.bytecodefuzz.FuzzTarget.fuzzerTestOneInput(FuzzTarget.java:138)
	at Crash_1305503bcc0d111f3497e0c517b573236b1bb0ad.main(Crash_1305503bcc0d111f3497e0c517b573236b1bb0ad.java:26)
```

File with the classfile causing the error and its disassembly: [Classfile.zip](https://github.com/user-attachments/files/17844479/Classfile.zip)

**Comment by davleopo** [comment]
Tracked internally as GR-59957.

**Comment by HanyzPAPU** [comment]
I added a building step I forgot originally.
