### ISSUE TITLE
[native-image] Building image fails with long com.oracle.svm.core.posix.PosixJavaNIOSubstitutions$Target_sun_nio_ch_FileDispatcherImpl.seek0 target method not found

### ISSUE THREAD

**Issue by oroppas** [oracle/graal#1014]
```
Building lli.image... [dependencies updated: GRAALVM_CMP_GU_GVM_INS_POLYNATIVE_PRO_PYN_RGX_SLG_STAGE1_SVM_TFL_VVM]
env MX_HOME=/home/ryutas/workspace/packages/graal/mx MX__SUITEMODEL=sibling GRAAL_PYTHONHOME=/home/ryutas/workspace/packages/graal/graalpython/graalpython MX_PRIMARY_SUITE_PATH=/home/ryutas/workspace/packages/graal/graal/vm MX_SUBPROCESS_COMMAND_FILE=/tmp/mx_subprocess_command.CXNs8g \
/home/ryutas/workspace/packages/graal/graal/vm/mxbuild/linux-amd64/GRAALVM_CMP_GU_GVM_INS_POLYNATIVE_PRO_PYN_RGX_SLG_STAGE1_SVM_TFL_VVM/graalvm-cmp-gu-gvm-ins-polynative-pro-pyn-rgx-slg-stage1-svm-tfl-vvm-1.0.0-rc14-dev/jre/lib/svm/bin/native-image -H:+EnforceMaxRuntimeCompileMethods -g BatteryHorseStapleCorrect -H:Path= -H:Name=batteryhorsestaplecorrect
Composing classpath for ['sulong:SULONG_LAUNCHER']. Entries:
- sdk:GRAAL_SDK
- sdk:LAUNCHER_COMMON
- sulong:SULONG_LAUNCHER
env MX_HOME=/home/ryutas/workspace/packages/graal/mx MX__SUITEMODEL=sibling GRAAL_PYTHONHOME=/home/ryutas/workspace/packages/graal/graalpython/graalpython MX_PRIMARY_SUITE_PATH=/home/ryutas/workspace/packages/graal/graal/vm MX_SUBPROCESS_COMMAND_FILE=/tmp/mx_subprocess_command.4d2MIu \
/home/ryutas/workspace/packages/graal/graal/vm/mxbuild/linux-amd64/GRAALVM_CMP_GU_GVM_INS_POLYNATIVE_PRO_PYN_RGX_SLG_STAGE1_SVM_TFL_VVM/graalvm-cmp-gu-gvm-ins-polynative-pro-pyn-rgx-slg-stage1-svm-tfl-vvm-1.0.0-rc14-dev/jre/lib/svm/bin/native-image -H:+EnforceMaxRuntimeCompileMethods -Dorg.graalvm.version=1.0.0-rc14-dev -Dgraalvm.version=1.0.0-rc14-dev -cp /home/ryutas/workspace/packages/graal/graal/sdk/mxbuild/dists/jdk11/graal-sdk.jar:/home/ryutas/workspace/packages/graal/graal/sdk/mxbuild/dists/jdk11/launcher-common.jar:/home/ryutas/workspace/packages/graal/graal/sulong/mxbuild/dists/jdk1.8/sulong-launcher.jar --language:llvm -H:-ParseRuntimeOptions -Dorg.graalvm.launcher.classpath=jre/lib/graalvm/launcher-common.jar:jre/lib/graalvm/sulong-launcher.jar -Dorg.graalvm.launcher.relative.language.home=bin/lli --tool:chromeinspector --tool:profiler -H:NumberOfThreads=1 com.oracle.truffle.llvm.launcher.LLVMLauncher -H:Path=/home/ryutas/workspace/packages/graal/graal/vm/mxbuild/linux-amd64/lli.image -H:Name=lli
[lli:20234]    classlist:   3,068.82 ms
[lli:20234]        setup:     360.62 ms
Error: could not find target method: private static long com.oracle.svm.core.posix.PosixJavaNIOSubstitutions$Target_sun_nio_ch_FileDispatcherImpl.seek0(java.io.FileDescriptor,long) throws java.io.IOException
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image building with exit status 1
```

This is how I build:

```
JAVA_HOME=/home/ryutas/packages/graal/graal-jvmci-8/jdk1.8.0_201/linux-amd64/product \
mx -v --max-cpus 1 --dynamicimports /substratevm,/tools,sulong,/graalpython build
```

**Comment by cstancu** [comment]
Can you please display the trace you get when running with `-H:+ReportExceptionStackTraces`?

**Comment by oroppas** [comment]
```
Error: could not find target method: private static long com.oracle.svm.core.posix.PosixJavaNIOSubstitutions$Target_sun_nio_ch_FileDispatcherImpl.seek0(java.io.FileDescriptor,long) throws java.io.IOException
com.oracle.svm.core.util.UserError$UserException: could not find target method: private static long com.oracle.svm.core.posix.PosixJavaNIOSubstitutions$Target_sun_nio_ch_FileDispatcherImpl.seek0(java.io.FileDescriptor,long) throws java.io.IOException
	at com.oracle.svm.core.util.UserError.abort(UserError.java:67)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findOriginalMethod(AnnotationSubstitutionProcessor.java:632)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleMethodInAliasClass(AnnotationSubstitutionProcessor.java:327)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:299)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:275)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:231)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:840)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:795)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:497)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:417)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by cstancu** [comment]
This error doesn't make much sense since I can see the original `sun.nio.ch.FileDispatcherImpl.seek0` that our substitutions mechanism looks for.  Can you  try an `mx clean`? Also, where do you get your jmvic enabled JDK from? Can you get the latest release `openjdk-8u202-jvmci-0.55` from https://github.com/graalvm/openjdk8-jvmci-builder/releases.

**Comment by oroppas** [comment]
I used graal-jvmci-8 built upon jdk1.8.0_201. I rebased graal-jvmci-8 re-based on jdk1.8.0_202 and the error disappeared. Does this ring any bells?

**Comment by cstancu** [comment]
I am not sure what happened there. Maybe there was some inconsistency in your development environment and rebasing/rebuilding fixed it.

**Comment by olpaw** [comment]
> I used graal-jvmci-8 built upon jdk1.8.0_201. I rebased graal-jvmci-8 re-based on jdk1.8.0_202 and the error disappeared. Does this ring any bells?

See: https://github.com/oracle/graal/commit/dcaa97b477cf48dd08d94dba544c5eb5e2a1ba82#diff-13c7b80b7342d7b12537e781d66207de

**Comment by oroppas** [comment]
Thanks!
