### ISSUE TITLE
[Native Image] error loading java.security

### ISSUE THREAD

**Issue by aamcurtis** [oracle/graal#10159]
### Describe the Issue

When attempting to start up my native image, I'm met with the following stack trace:

`Exception in thread "main" java.lang.InternalError: Error loading java.security file
        at java.base@23.0.1/java.security.Security.initialize(Security.java:105)
        at java.base@23.0.1/java.security.Security.lambda$static$0(Security.java:84)
        at java.base@23.0.1/java.security.AccessController.executePrivileged(AccessController.java:132)
        at java.base@23.0.1/java.security.AccessController.doPrivileged(AccessController.java:319)
        at java.base@23.0.1/java.security.Security.<clinit>(Security.java:83)
        at java.base@23.0.1/java.io.ObjectInputFilter$Config.lambda$static$0(ObjectInputFilter.java:637)
        at java.base@23.0.1/java.security.AccessController.executePrivileged(AccessController.java:132)
        at java.base@23.0.1/java.security.AccessController.doPrivileged(AccessController.java:319)
        at java.base@23.0.1/java.io.ObjectInputFilter$Config.<clinit>(ObjectInputFilter.java:636)
        at java.base@23.0.1/java.io.ObjectInputStream.<init>(ObjectInputStream.java:402)
        at sharebox.security.Passphrase.<init>(Passphrase.java:129)`

Whcih corresponds to the following line of code:

             ` in = new ObjectInputStream ( new FileInputStream( ShareboxConfig.getInstallDirectory() + File.separator + passphraseFile`

I've no idea how or why this would trigger the java.security file, running the agent and debugging the uncompiled code using the graal jvm doesn't throw this exception. 

### Using the latest version of GraalVM can resolve many issues.

- [x] I tried with the [latest version](https://www.graalvm.org/downloads/) of GraalVM.

### GraalVM Version

 Oracle GraalVM 23.0.1+11.1

### Operating System and Version

Windows 10 x86

### Troubleshooting Confirmation

- [x] I tried the suggestions in the [troubleshooting guide](https://www.graalvm.org/latest/reference-manual/native-image/guides/troubleshoot-run-time-errors/).

### Run Command

.\target\Sharebox "M:\cypherit-bitbucket\sharebox\config\sharebox.ini" -Djava.home="C:\Program Files\graalVM\graalvm-jdk-23.0.1+11.1"

### Expected Behavior

I'd expected the passphrase file to load

### Actual Behavior

Exception thrown trying to read the input stream

`Exception in thread "main" java.lang.InternalError: Error loading java.security file
        at java.base@23.0.1/java.security.Security.initialize(Security.java:105)
        at java.base@23.0.1/java.security.Security.lambda$static$0(Security.java:84)
        at java.base@23.0.1/java.security.AccessController.executePrivileged(AccessController.java:132)
        at java.base@23.0.1/java.security.AccessController.doPrivileged(AccessController.java:319)
        at java.base@23.0.1/java.security.Security.<clinit>(Security.java:83)
        at java.base@23.0.1/java.io.ObjectInputFilter$Config.lambda$static$0(ObjectInputFilter.java:637)
        at java.base@23.0.1/java.security.AccessController.executePrivileged(AccessController.java:132)
        at java.base@23.0.1/java.security.AccessController.doPrivileged(AccessController.java:319)
        at java.base@23.0.1/java.io.ObjectInputFilter$Config.<clinit>(ObjectInputFilter.java:636)
        at java.base@23.0.1/java.io.ObjectInputStream.<init>(ObjectInputStream.java:402)
        at sharebox.security.Passphrase.<init>(Passphrase.java:129)`

### Steps to Reproduce

1. Run the native image with the command supplied

### Additional Context

Bouncy castle is used for it's PGP functioanlity

**Comment by selhagani** [comment]
Hi @aamcurtis, 

Thank you for reaching out to us. 
Could you share with us a simple reproducer for your issue in a public github repo please?

**Comment by fmeum** [comment]
I've seen similar errors when running a JVM with a working directory whose path contains non-ASCII Unicode characters (especially those requiring a 4 byte encoding such as emojis).

**Comment by aamcurtis** [comment]
I've managed to find the root cause while builidng the reproducer, contained within the build args was the option to compile Java.Security at runtime, which would seem to be pretty self-explanatory. As for the reason this was included in the first place I can only assume it was while trying to get bouncycastle to play nicely during compile.
