### ISSUE TITLE
[native-image] failed when using js engine

### ISSUE THREAD

**Issue by wkgcass** [oracle/graal#1017]
I'm running macos 10.13.6 and I am trying to build a native image but got the error during compile time.  
I managed to build a very small piece of code which can re-produce this exception.

TestFail.java

```java
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;

public class TestFail {
    public static void main(String[] args) throws Exception {
        ScriptEngine engine = new ScriptEngineManager().getEngineByName("js");
        engine.eval("1+1");
    }
}
```

```
javac -version
javac 1.8.0_192

native-image --version
GraalVM Version 1.0.0-rc12

javac TestFail.java
native-image --language:js TestFail
Build on Server(pid: 94127, port: 53403)
[testfail:94127]    classlist:   4,148.27 ms
[testfail:94127]        (cap):   2,527.74 ms
[testfail:94127]        setup:   3,231.40 ms
[testfail:94127]     analysis:  21,431.68 ms
Fatal error: java.lang.IndexOutOfBoundsException: index -1
	at java.util.concurrent.atomic.AtomicReferenceArray.checkedByteOffset(AtomicReferenceArray.java:78)
	at java.util.concurrent.atomic.AtomicReferenceArray.get(AtomicReferenceArray.java:125)
	at com.oracle.graal.pointsto.flow.context.object.AnalysisObject.getInstanceFieldTypeStore(AnalysisObject.java:213)
	at com.oracle.graal.pointsto.flow.context.object.AnalysisObject.getInstanceFieldFlow(AnalysisObject.java:199)
	at com.oracle.graal.pointsto.flow.LoadFieldTypeFlow$LoadInstanceFieldTypeFlow.onObservedUpdate(LoadFieldTypeFlow.java:159)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:347)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:389)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:508)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Processing image build request failed
```

Then I tried to run on a linux docker container, and I get a heap OOM exception:

```
root@5db5fcac1cd5:/xxx# /graalvm/bin/native-image --language:js TestFail
Build on Server(pid: 11, port: 45527)*
[testfail:11]    classlist:   7,440.69 ms
[testfail:11]        (cap):   1,347.26 ms
[testfail:11]        setup:   3,410.00 ms
[testfail:11]     analysis:  72,933.66 ms
Error: Error encountered while parsing java.lang.invoke.CallSite.makeUninitializedCallSite(java.lang.invoke.MethodType)
Parsing context:
	parsing java.lang.invoke.CallSite.<init>(CallSite.java:105)
	parsing java.lang.invoke.MutableCallSite.<init>(MutableCallSite.java:100)
	parsing jdk.internal.dynalink.support.AbstractRelinkableCallSite.<init>(AbstractRelinkableCallSite.java:104)
	parsing jdk.internal.dynalink.ChainedCallSite.<init>(ChainedCallSite.java:135)
	parsing jdk.nashorn.internal.runtime.linker.LinkerCallSite.<init>(LinkerCallSite.java:72)
	parsing jdk.nashorn.internal.runtime.linker.LinkerCallSite.newLinkerCallSite(LinkerCallSite.java:124)
	parsing jdk.nashorn.internal.runtime.linker.Bootstrap.bootstrap(Bootstrap.java:208)
	parsing jdk.nashorn.internal.runtime.linker.Bootstrap.createDynamicInvoker(Bootstrap.java:371)
	parsing jdk.nashorn.internal.runtime.linker.Bootstrap.createDynamicInvoker(Bootstrap.java:345)
	parsing jdk.nashorn.internal.runtime.linker.InvokeByName.<init>(InvokeByName.java:98)
	parsing jdk.nashorn.internal.runtime.linker.InvokeByName.<init>(InvokeByName.java:73)
	parsing jdk.nashorn.internal.objects.Global.<init>(Global.java:97)
	parsing jdk.nashorn.internal.runtime.Context.newGlobal(Context.java:1111)
	parsing jdk.nashorn.api.scripting.NashornScriptEngine$2.run(NashornScriptEngine.java:350)
	parsing jdk.nashorn.api.scripting.NashornScriptEngine$2.run(NashornScriptEngine.java:346)
	parsing com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:72)
	parsing java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:398)
	parsing java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
	parsing javax.script.ScriptEngineManager.initEngines(ScriptEngineManager.java:120)
	parsing javax.script.ScriptEngineManager.init(ScriptEngineManager.java:84)
	parsing javax.script.ScriptEngineManager.<init>(ScriptEngineManager.java:61)
	parsing TestFail.main(TestFail.java:6)
	parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:152)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Original error: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.OutOfMemoryError: Java heap space
	at parsing java.lang.invoke.CallSite.makeUninitializedCallSite(CallSite.java:241)
	at org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2435)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:88)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3189)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:2993)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:890)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:784)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:95)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:205)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:324)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.flow.SpecialInvokeTypeFlow.onObservedUpdate(InvokeTypeFlow.java:421)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:347)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:389)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:508)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.ArrayDeque.allocateElements(ArrayDeque.java:147)
	at java.util.ArrayDeque.<init>(ArrayDeque.java:203)
	at org.graalvm.compiler.graph.NodeWorkList.<init>(NodeWorkList.java:40)
	at org.graalvm.compiler.graph.NodeWorkList.<init>(NodeWorkList.java:34)
	at org.graalvm.compiler.graph.NodeWorkList$IterativeNodeWorkList.<init>(NodeWorkList.java:87)
	at org.graalvm.compiler.graph.Graph.createIterativeNodeWorkList(Graph.java:1069)
	at org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.run(CanonicalizerPhase.java:202)
	at org.graalvm.compiler.phases.common.CanonicalizerPhase.run(CanonicalizerPhase.java:125)
	at org.graalvm.compiler.phases.common.CanonicalizerPhase.run(CanonicalizerPhase.java:66)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at com.oracle.svm.hosted.phases.IntrinsifyMethodHandlesInvocationPlugin.processInvokeWithMethodHandle(IntrinsifyMethodHandlesInvocationPlugin.java:352)
	at com.oracle.svm.hosted.phases.IntrinsifyMethodHandlesInvocationPlugin.handleInvoke(IntrinsifyMethodHandlesInvocationPlugin.java:161)
	at org.graalvm.compiler.java.BytecodeParser.tryNodePluginForInvocation(BytecodeParser.java:2198)
	at org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1703)
	at org.graalvm.compiler.java.BytecodeParser.genDynamicInvokeHelper(BytecodeParser.java:1584)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1534)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1519)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5018)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3184)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:2993)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:890)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:784)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:95)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:205)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:324)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Processing image build request failed
```

**Comment by cstancu** [comment]
@wkgcass Building a `native-image` that contains `graal.js` with the `ScriptEngineManager`/`ScripeEngine` API is currently not possible. However you can build it using the polyglot API:
```
import org.graalvm.polyglot.Context;

public class TestPolyglot {
public static void main(String[] args) {
    Context context = Context.newBuilder().allowAllAccess(true).build();
    context.eval("js", "print('Hello polyglot world JavaScript!');");
    }
}
```
We will suppport the `ScriptEngineManager`/`ScripeEngine` API on `native-image` soon too. Right now trying to build and image that calls `AbstractScriptEngine.eval()` will make `NashornScriptEngine.eval()` reachable. Unfortunately nashorn cannot be supported on `native-image` because it makes heavy use of `MethodHandle` and `native-image` `MethodHandle` support is limited to cases where the `MethodHandle` objects are compile time constants.

**Comment by wkgcass** [comment]
@cstancu Thanks for your help! I successfully compiled and verified my program using reflection to polyglot.Context while it still supports a standard jre without any bundle jars.

Something like:

```java
public static final boolean isGraal;

static {
    String isGraalStr = System.getProperty("IsGraal", "false");
    isGraal = isGraalStr.equals("true");
}

JsContext newContext() {
    if (isGraal) {
        return new PolyglotJsContext(); // reflect inside the class
    } else {
        return new JDKJsContext(); // directly access ScriptEngine in the class
    }
}
```

and

```
native-image --language:js -DIsGraal=true .......
```

This works, and I'm wondering whether the `native-image` compiler does a static check to see which line of code is reachable? Because I didn't remove the ScriptEngine reference from code but it seems `native-image` managed to skip the ScriptEngine part.

**Comment by cstancu** [comment]
@wkgcass yes, the static block (and in general all class initializers unless specified otherwise) is executed at image build time and the value of `isGraal` is determined. Then constant folding in the Graal compiler eliminates the `else` branch as unreachable code.

**Comment by cstancu** [comment]
We now [disable the nashorn engine](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_jdk_nashorn_api_scripting_NashornScriptEngineFactory.java#L36) in `native-image`. When you build an image with `native-image --language:js ...` the Graal.js engine is included and returned by `new ScriptEngineManager().getEngineByName("js")` and the example from your initial report works as expected. This fix will be available in RC14.
