### ISSUE TITLE
NoClassDefFoundError with Micronaut and Jaeger

### ISSUE THREAD

**Issue by ilopmar** [oracle/graal#1024]
I'm trying to generate a Graal native image for a Micronaut application that uses Jaeger and I've found a `java.lang.NoClassDefFoundError: io/micronaut/tracing/brave/sender/HttpClientSender`

To reproduce the issue:
- `git clone https://github.com/ilopmar/micronaut-jaeger-graal`
- `cd micronaut-jaeger-graal`
- Use GraalRC12. I've also tried with graal master branch (rc14-dev) and the error is the same.
- `./build-native-image.sh`

The native image generation fails with:

```
[mn-jaeger-graal:6087]     analysis:  53,937.38 ms
Error: Error encountered while parsing io.micronaut.tracing.brave.BraveTracerConfiguration$HttpClientSenderConfiguration.<init>() 
Parsing context:
	parsing io.micronaut.tracing.brave.$BraveTracerConfiguration$HttpClientSenderConfigurationDefinition.build(Unknown Source)
	parsing io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1385)
	parsing io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:1791)
	parsing io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1695)
	parsing io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1673)
	parsing io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:959)
	parsing io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:560)
	parsing io.micronaut.context.BeanLocator.findBean(BeanLocator.java:132)
	parsing io.micronaut.runtime.Micronaut.start(Micronaut.java:69)
	parsing io.micronaut.runtime.Micronaut.run(Micronaut.java:274)
	parsing io.micronaut.runtime.Micronaut.run(Micronaut.java:260)
	parsing micronaut.jaeger.graal.Application.main(Application.java:8)
	parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:152)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Original error: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.NoClassDefFoundError: io/micronaut/tracing/brave/sender/HttpClientSender
	at parsing io.micronaut.tracing.brave.BraveTracerConfiguration$HttpClientSenderConfiguration.<init>(BraveTracerConfiguration.java:178)
	at org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2435)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:88)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3189)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:2993)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:890)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:784)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:95)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:205)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:324)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.flow.SpecialInvokeTypeFlow.onObservedUpdate(InvokeTypeFlow.java:421)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:347)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:389)
	at com.oracle.graal.pointsto.flow.SourceTypeFlowBase.update(SourceTypeFlowBase.java:121)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:508)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NoClassDefFoundError: io/micronaut/tracing/brave/sender/HttpClientSender
	at java.lang.Class.getDeclaringClass0(Native Method)
	at java.lang.Class.getDeclaringClass(Class.java:1235)
	at java.lang.Class.getEnclosingClass(Class.java:1277)
	at jdk.vm.ci.hotspot.HotSpotJDKReflection.getEnclosingClass(HotSpotJDKReflection.java:108)
	at jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.getEnclosingType(HotSpotResolvedObjectTypeImpl.java:939)
	at jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.getEnclosingType(HotSpotResolvedObjectTypeImpl.java:62)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:291)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:202)
	at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupType(WrappedConstantPool.java:154)
	at org.graalvm.compiler.java.BytecodeParser.lookupType(BytecodeParser.java:3992)
	at org.graalvm.compiler.java.BytecodeParser.genNewInstance(BytecodeParser.java:4235)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5023)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3184)
	... 24 more

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image building with exit status 1
```

The class `io.micronaut.tracing.brave.sender.HttpClientSender` it is on the classpath but what happens is that the class extends from `zipkin2.reporter.Sender` which is not: https://github.com/micronaut-projects/micronaut-core/blob/master/tracing/src/main/java/io/micronaut/tracing/brave/sender/HttpClientSender.java#L53

I think this is a bug because that neither the class `io.micronaut.tracing.brave.BraveTracerConfiguration` nor `io.micronaut.tracing.brave.BraveTracerConfiguration$HttpClientSenderConfiguration` should be loaded. 
Both classes have an `@Requires` that is not satisfied and I'm using `--allow-incomplete-classpath`

`BraveTracerConfiguration`-> https://github.com/micronaut-projects/micronaut-core/blob/master/tracing/src/main/java/io/micronaut/tracing/brave/BraveTracerConfiguration.java#L44-L45
`BraveTracerConfiguration$HttpClientSenderConfiguration` -> https://github.com/micronaut-projects/micronaut-core/blob/master/tracing/src/main/java/io/micronaut/tracing/brave/BraveTracerConfiguration.java#L167-L168

This issue maybe is similar to this one https://github.com/oracle/graal/issues/947 (already fixed)

**Comment by cstancu** [comment]
Fixed in https://github.com/oracle/graal/commit/aa4990d586a96fd3aa5974738f19a419cd1a3a49. Thanks for the detailed report!

**Comment by ilopmar** [comment]
Thanks for your support! :100:
