### ISSUE TITLE
Exception while running Polylgot programs in GraalVM debug version.

### ISSUE THREAD

**Issue by gammaraylab** [oracle/graal#10256]
**Describe GraalVM and your environment :**
 - Commit id: **b25dea73bea0bfdce02e6fc6ddfe5d14ffdaf364**
 - CE
 - JDK version: **24**
 - OS and OS Version: **Ubuntu 22.04**
 - Architecture: **amd64**
 - mx version:  **7.36.1**
 - The output of `java -Xinternalversion`:
```
OpenJDK 64-Bit Server VM (24+26-jvmci-b01) for linux-amd64 JRE (24+26-jvmci-b01), built on 2024-11-28T18:41:32Z with gcc 13.2.0

```

**Have you verified this issue still happens when using the latest snapshot?**
Yes

**The issue**
While running a simple polyglot program, the GraalVM that I built throws the an exception. 
I have no issue with running simple java programs with it. 
Also the polyglot programs ran successfully with other ```release CE``` versions of graalVM.

**Repository that reproduces the issue**
```
https://github.com/gammaraylab/Polyglot-examples
```

**Steps to reproduce the issue**
1. `git clone https://github.com/graalvm/mx.git`
2. `export PATH=$PATH:$PWD/mx`
3. `git clone https://github.com/oracle/graal.git`
4. `$ mx fetch-jdk`
5.  or `export JAVA_HOME=<latest jvmci home>`
6. `$ cd graal/compiler`
7. `$ mx build`
8. `$ cd ../truffle`
9. `$ mx build`
10. Now create a maven project from the repo.
11. Setup the JDK to `graal/sdk/latest_graalvm_home`
12. Run the polyglot example.

**Expected behavior**
It runs a simple python loop and prints a list of numbers.

```
830
12070
13050
.
.
.
19602
19900
------------------------------
hello

Process finished with exit code 0
```

**Additional context**
I am actually trying to add some phases in compiler for polyglot program execution.

<details><summary>Details</summary>

```
org.graalvm.polyglot.PolyglotException: java.util.ServiceConfigurationError: com.oracle.truffle.api.provider.InternalResourceProvider: Provider com.oracle.truffle.runtime.LibTruffleAttachResourceProvider not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:559)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1090)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1099)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1142)
	at java.base/java.util.ServiceLoader$1.hasNext(ServiceLoader.java:1164)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1246)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:153)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:176)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:636)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.InternalResourceCache.collectOptionalResources(InternalResourceCache.java:495)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.InternalResourceCache.loadOptionalInternalResources(InternalResourceCache.java:481)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.LanguageCache.createLanguages(LanguageCache.java:270)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.LanguageCache.loadLanguages(LanguageCache.java:261)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.LanguageCache.languages(LanguageCache.java:222)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.EngineAccessor$EngineImpl.getLanguageIds(EngineAccessor.java:1445)
	at org.graalvm.truffle/com.oracle.truffle.api.TruffleLogger$LoggerCache.getKnownIds(TruffleLogger.java:1063)
	at org.graalvm.truffle/com.oracle.truffle.api.TruffleLogger$LoggerCache.getOrCreateLogger(TruffleLogger.java:1050)
	at org.graalvm.truffle/com.oracle.truffle.api.TruffleLogger.getLogger(TruffleLogger.java:161)
	at org.graalvm.truffle/com.oracle.truffle.api.LanguageAccessor$LanguageImpl.getLogger(LanguageAccessor.java:531)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLoggers$EngineLoggerProvider.apply(PolyglotLoggers.java:786)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotImpl.logTruffleRuntimeWarning(PolyglotImpl.java:396)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotImpl.buildEngine(PolyglotImpl.java:310)
	at org.graalvm.polyglot/org.graalvm.polyglot.Engine$Builder.build(Engine.java:771)
	at org.graalvm.polyglot/org.graalvm.polyglot.Context$Builder.build(Context.java:1975)
	at org.graalvm.polyglot/org.graalvm.polyglot.Context.create(Context.java:1029)
	at org.gammaraylab.TestCases.addComplexLoop(TestCases.java:79)
	at org.gammaraylab.Main.loop(Main.java:11)
	at org.gammaraylab.Main.main(Main.java:5)
	Suppressed: Attached Guest Language Frames (0)
```
</details>

**Comment by gammaraylab** [comment]
The issue was resolved after adding `module-info.java` in the project.
