### ISSUE TITLE
[Native Image] Error Report

### ISSUE THREAD

**Issue by rawoof-git** [oracle/graal#10265]
### Describe the Issue

Getting below error  while creating native-image

Error
Exception in thread "main" java.lang.NullPointerException
	at java.base@23.0.1/java.util.Objects.requireNonNull(Objects.java:220)
	at java.base@23.0.1/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:215)
	at java.base@23.0.1/java.nio.file.Path.of(Path.java:148)
	at java.base@23.0.1/java.nio.file.Paths.get(Paths.java:69)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.WindowsBuildEnvironmentUtil.findVCVarsallWithVSWhere(WindowsBuildEnvironmentUtil.java:114)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.WindowsBuildEnvironmentUtil.propagateEnv(WindowsBuildEnvironmentUtil.java:53)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.buildImage(NativeImage.java:1689)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.completeImageBuild(NativeImage.java:1329)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.build(NativeImage.java:1882)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1847)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.main(NativeImage.java:1829)
	at java.base@23.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)

GraalVM version using : 23.0.1
Command using to create image : mvn clean -Pnative native:compile
Spring-boot version : 3.2.3
native-maven-plugin version : native-maven-plugin

### Please confirm if you have tested with the latest available version.

- [X] I tried with the latest version of GraalVM. [Latest GraalVM Version](https://www.graalvm.org/downloads/)

### Share the `svm_err_b_*.md` File

native-maven-plugin

**Comment by rawoof-git** [comment]
Its working with graalVM version 17. Closing this issue

**Comment by ozkanpakdil** [comment]
@selhagani 
This error come when I run the build outside "x86_x64 Cross Tools Command Prompt for VS 2022", for example I was running the build in git bash and got this 
```
Apply jar:file:///C:/Users/ozkan/.m2/repository/io/micrometer/micrometer-core/1.14.2/micrometer-core-1.14.2.jar!/META-INF/native-image/io.micrometer/micrometer-core/proxy-config.json
Warning: The option '-H:ServiceLoaderFeatureExcludeServices=org.hibernate.bytecode.spi.BytecodeProvider' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: Please re-evaluate whether any experimental option is required, and either remove or unlock it. The build output lists all active experimental options, including where they come from and possible alternatives. If you think an experimental option should be considered as stable, please file an issue.
Apply jar:file:///C:/sdkman/candidates/java/current/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/thirdparty/native-image.properties
Apply jar:file:///C:/sdkman/candidates/java/current/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/polyglot/native-image.properties
Exception in thread "main" java.lang.NullPointerException
        at java.base@23.0.1/java.util.Objects.requireNonNull(Objects.java:220)
        at java.base@23.0.1/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:215)
        at java.base@23.0.1/java.nio.file.Path.of(Path.java:148)
        at java.base@23.0.1/java.nio.file.Paths.get(Paths.java:69)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.WindowsBuildEnvironmentUtil.findVCVarsallWithVSWhere(WindowsBuildEnvironmentUtil.java:114)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.WindowsBuildEnvironmentUtil.propagateEnv(WindowsBuildEnvironmentUtil.java:53)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.buildImage(NativeImage.java:1689)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.completeImageBuild(NativeImage.java:1329)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.build(NativeImage.java:1882)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1847)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.main(NativeImage.java:1829)
        at java.base@23.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```

then I realize I forgot to run it under the x86 vcvars, long story short I think this error should tell to user that something is not found on the env , run this under "VS x86 native build vars" I think earlier versions of graalvm was doing that. probably why rawoof closed this with "working in 17"

here is my version
```
ozkan@hp-envy-2021-i7-nvidia MINGW64 ~/tmp/jhipster-native-test
$  ./mvnw --version
MINGW support requires --add-opens java.base/java.lang=ALL-UNNAMED
MINGW support requires --add-opens java.base/java.lang=ALL-UNNAMED
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: C:\Users\ozkan\.m2\wrapper\dists\apache-maven-3.9.9\3477a4f1
Java version: 23.0.1, vendor: GraalVM Community, runtime: C:\sdkman\candidates\java\current
Default locale: en_GB, platform encoding: UTF-8
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"
```
