### ISSUE TITLE
Fatal error: com.oracle.svm.core.util.VMError$HostedError: Option name "UseLibC" has multiple definitions

### ISSUE THREAD

**Issue by rawoof-git** [oracle/graal#10266]
### Describe the Issue

Getting below error while building native-image 
Fatal error: com.oracle.svm.core.util.VMError$HostedError: Option name "UseLibC" has multiple definitions: com.oracle.svm.hosted.c.libc.HostedLibCFeature$LibCOptions.UseLibC and com.oracle.svm.core.posix.linux.libc.LibCFeature$LibCOptions.UseLibC
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:72)
	at com.oracle.svm.hosted.option.HostedOptionParser.lambda$collectOptions$0(HostedOptionParser.java:77)
	at com.oracle.svm.common.option.CommonOptionParser.collectOptions(CommonOptionParser.java:173)
	at com.oracle.svm.core.option.SubstrateOptionsParser.collectOptions(SubstrateOptionsParser.java:118)
	at com.oracle.svm.hosted.option.HostedOptionParser.collectOptions(HostedOptionParser.java:66)
	at com.oracle.svm.hosted.option.HostedOptionParser.<init>(HostedOptionParser.java:61)
	at com.oracle.svm.hosted.NativeImageClassLoaderSupport.setupHostedOptionParser(NativeImageClassLoaderSupport.java:189)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.installNativeImageClassLoader(NativeImageGeneratorRunner.java:186)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:129)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:626)

GraalVM version : 17.0.12

### Using the latest version of GraalVM can resolve many issues.

- [X] I tried with the [latest version](https://www.graalvm.org/downloads/) of GraalVM.

### GraalVM Version

GraalVM version : 17.0.12

### Operating System and Version

Windows 11

### Build Command

mvn clean -Pnative native:compile

### Expected Behavior

should create native image

### Actual Behavior

Getting exception after few steps 

### Steps to Reproduce

Add below plugin and try to create image

</plugin>
		    <plugin>
               <groupId>org.graalvm.buildtools</groupId>
               <artifactId>native-maven-plugin</artifactId>
               <version>0.10.0</version>
               <configuration>

        <mainClass>com.test.Hello</mainClass>
        <buildArgs>
            --no-fallback
            <arg>--add-exports=jdk.internal.vm.compiler/org.graalvm.compiler.options=ALL-UNNAMED</arg>
        </buildArgs>
    </configuration>
    <executions>
        <execution>
            <id>build-native</id>
            <goals>
                <goal>compile-no-fork</goal>
            </goals>
            <phase>package</phase>
        </execution>
    </executions>
            </plugin>

**Comment by fernando-valdez** [comment]
Hi @rawoof-git, thanks for reporting this issue.  The error indicates that the `UseLibC` option is defined more than once in the GraalVM native image build configuration. Can you please confirm that UseLibC is defined only once in your build configuration?
