### ISSUE TITLE
[native-image] StringUTF16 issue (unimplemented) with LLVM backend on Java 11

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#1056]
When generating an image for a HelloWorld application using the llvm backend (-H:CompilerBackend=llvm -H:-MultiThreaded -H:-SpawnIsolates) the following error is thrown:
Fatal error: org.graalvm.compiler.graph.GraalGraphError: org.graalvm.compiler.debug.GraalError: unimplemented: StringUTF16.compress substitution is not implemented on this architecture
	at node: 37|AMD64StringUTF16Compress
	at method: byte[] java.lang.StringUTF16.compress(byte[], int, int)  [Direct call from String StringUTF16.newString(byte[], int, int)]
	at jdk.internal.vm.compiler/org.graalvm.compiler.graph.GraalGraphError.transformAndAddContext(GraalGraphError.java:136)
	at org.graalvm.compiler.core.llvm.NodeLLVMBuilder.doBlock(NodeLLVMBuilder.java:220)
	at org.graalvm.compiler.core.llvm.LLVMGenerationPhase.run(LLVMGenerationPhase.java:38)
	at org.graalvm.compiler.core.llvm.LLVMCompilerBackend.emitLLVM(LLVMCompilerBackend.java:65)
	at org.graalvm.compiler.core.llvm.LLVMCompilerBackend.emitBackEnd(LLVMCompilerBackend.java:42)
	at com.oracle.svm.core.graal.llvm.SubstrateLLVMBackend.emitBackEnd(SubstrateLLVMBackend.java:107)
	at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:145)
	at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:129)
	at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:914)
	at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:877)
	at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:259)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:169)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: org.graalvm.compiler.debug.GraalError: unimplemented: StringUTF16.compress substitution is not implemented on this architecture
	at jdk.internal.vm.compiler/org.graalvm.compiler.debug.GraalError.unimplemented(GraalError.java:43)
	at jdk.internal.vm.compiler/org.graalvm.compiler.lir.gen.LIRGeneratorTool.emitStringUTF16Compress(LIRGeneratorTool.java:298)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.amd64.AMD64StringUTF16CompressNode.generate(AMD64StringUTF16CompressNode.java:94)
	at org.graalvm.compiler.core.llvm.NodeLLVMBuilder.emitNode(NodeLLVMBuilder.java:260)
	at org.graalvm.compiler.core.llvm.NodeLLVMBuilder.doRoot(NodeLLVMBuilder.java:250)
	at org.graalvm.compiler.core.llvm.NodeLLVMBuilder.doBlock(NodeLLVMBuilder.java:218)

**Comment by vjovanov** [comment]
Fixed [here](https://github.com/oracle/graal/commit/5d98913b9511eaceb8623a1b2b8960b46875a5db).

**Comment by vjovanov** [comment]
Fixed [here](https://github.com/oracle/graal/commit/b4b403e30a2f095084ac9f7f5d4f0442661b612c).
