### ISSUE TITLE
native-image fails with "Deadlock creating new types" error

### ISSUE THREAD

**Issue by vmencik** [oracle/graal#1070]
I get the following error when compiling a Scala application with native-image. Unfortunatelly I don't have a simple reproducer and the app is a proprietary code I cannot publish here.

Is there a way how to get more information about the error? For example which type(s) caused the deadlock?
It is probably caused by native-image having some issues with some Scala feature as the application is using Cake Pattern, things like `abstract override`, lazy vals and other stuff.
Also it is very strange that the error happens if I leave the `main` method of the application empty but in the original state when the `main` method instantiates the class using the cake pattern, native-image compiles without errors.

```
[error] Fatal error: jdk.vm.ci.common.JVMCIError: jdk.vm.ci.common.JVMCIError: should not reach here: Deadlock creating new types
[error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error] 	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
[error] 	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
[error] 	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:434)
[error] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:284)
[error] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:406)
[error] 	at com.oracle.svm.hosted.server.NativeImageBuildServer.executeCompilation(NativeImageBuildServer.java:390)
[error] 	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$processCommand$8(NativeImageBuildServer.java:327)
[error] 	at com.oracle.svm.hosted.server.NativeImageBuildServer.withJVMContext(NativeImageBuildServer.java:408)
[error] 	at com.oracle.svm.hosted.server.NativeImageBuildServer.processCommand(NativeImageBuildServer.java:324)
[error] 	at com.oracle.svm.hosted.server.NativeImageBuildServer.processRequest(NativeImageBuildServer.java:268)
[error] 	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$serve$7(NativeImageBuildServer.java:228)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: jdk.vm.ci.common.JVMCIError: should not reach here: Deadlock creating new types
[error] 	at jdk.vm.ci.common.JVMCIError.shouldNotReachHere(JVMCIError.java:50)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:251)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:204)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:181)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisType.convertTypes(AnalysisType.java:208)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisType.<init>(AnalysisType.java:168)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:262)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:204)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:181)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisType.getEnclosingType(AnalysisType.java:940)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:297)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:204)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:181)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisType.convertTypes(AnalysisType.java:208)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisType.<init>(AnalysisType.java:168)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:262)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:204)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:181)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisType.convertTypes(AnalysisType.java:208)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisType.<init>(AnalysisType.java:168)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:262)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:204)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:181)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisField.getDeclaredType(AnalysisField.java:133)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisField.<init>(AnalysisField.java:106)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createField(AnalysisUniverse.java:364)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:352)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:319)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:75)
[error] 	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaField(UniverseMetaAccess.java:104)
[error] 	at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaField(AnalysisMetaAccess.java:71)
[error] 	at com.oracle.svm.reflect.hosted.ReflectionDataBuilder.filterFields(ReflectionDataBuilder.java:306)
[error] 	at com.oracle.svm.reflect.hosted.ReflectionDataBuilder.duringAnalysis(ReflectionDataBuilder.java:231)
[error] 	at com.oracle.svm.reflect.hosted.ReflectionFeature.duringAnalysis(ReflectionFeature.java:81)
[error] 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:679)
[error] 	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
[error] 	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:679)
[error] 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:499)
[error] 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:417)
[error] 	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
[error] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[error] Error: Processing image build request failed
```

**Comment by cstancu** [comment]
This issue may have been related to throwing a `NoClassDefFoundError` (or other type resolution errors) during AnalysisTypeCreation. That problem has been fixed in the meantime, the error should be properly caught and reported. Please reopen if you can still reproduce with the latest release.
