### ISSUE TITLE
Failure to compile method that interprets ok

### ISSUE THREAD

**Issue by headius** [oracle/graal#1075]
I'm seeing the following error for a piece of code that interprets correct (I get no verification errors) and which seems to JIT properly on C2.

```
[Use -Dgraal.LogFile=<path> to redirect Graal log output to a file.]
Thread[JVMCI CompilerThread2,9,system]: Compilation of Users.headius.projects.jruby.lib.ruby.stdlib.monitor.RUBY$method$broadcast$0(ThreadContext, StaticScope, IRubyObject, Block, RubyModule, String) failed:
org.graalvm.compiler.graph.GraalGraphError: Invalid frame state 87|FrameState@-3[AFTER_BCI]
	at node: 2312|Read
	at org.graalvm.compiler.hotspot.HotSpotDebugInfoBuilder.raiseInvalidFrameStateError(HotSpotDebugInfoBuilder.java:122)
	at org.graalvm.compiler.hotspot.HotSpotDebugInfoBuilder.computeFrameForState(HotSpotDebugInfoBuilder.java:92)
	at org.graalvm.compiler.core.gen.DebugInfoBuilder.build(DebugInfoBuilder.java:101)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.stateForWithExceptionEdge(NodeLIRBuilder.java:748)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.stateFor(NodeLIRBuilder.java:740)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.state(NodeLIRBuilder.java:729)
	at org.graalvm.compiler.nodes.memory.ReadNode.generate(ReadNode.java:79)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.emitNode(NodeLIRBuilder.java:473)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.doRoot(NodeLIRBuilder.java:464)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.doBlock(NodeLIRBuilder.java:379)
	at org.graalvm.compiler.core.LIRGenerationPhase.emitBlock(LIRGenerationPhase.java:81)
	at org.graalvm.compiler.core.LIRGenerationPhase.run(LIRGenerationPhase.java:71)
	at org.graalvm.compiler.core.LIRGenerationPhase.run(LIRGenerationPhase.java:46)
	at org.graalvm.compiler.lir.phases.LIRPhase.apply(LIRPhase.java:117)
	at org.graalvm.compiler.lir.phases.LIRPhase.apply(LIRPhase.java:109)
	at org.graalvm.compiler.core.gen.LIRCompilerBackend.emitLIR0(LIRCompilerBackend.java:139)
	at org.graalvm.compiler.core.gen.LIRCompilerBackend.emitLIR(LIRCompilerBackend.java:102)
	at org.graalvm.compiler.core.gen.LIRCompilerBackend.emitBackEnd(LIRCompilerBackend.java:82)
	at org.graalvm.compiler.core.target.Backend.emitBackEnd(Backend.java:262)
	at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:145)
	at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:129)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileHelper(HotSpotGraalCompiler.java:185)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:198)
	at org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:182)
	at org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:99)
	at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:172)
	at org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:331)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:138)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:105)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:627)
To disable compilation failure notifications, set CompilationFailureAction to Silent (e.g., -Dgraal.CompilationFailureAction=Silent).
To print a message for a compilation failure without retrying the compilation, set CompilationFailureAction to Print (e.g., -Dgraal.CompilationFailureAction=Print).
Retrying compilation of Users.headius.projects.jruby.lib.ruby.stdlib.monitor.RUBY$method$broadcast$0(ThreadContext, StaticScope, IRubyObject, Block, RubyModule, String)
```

The bytecode for this method (Ruby code jitted to JVM bytecode) is in the following gist: https://gist.github.com/headius/33160a110d0365029bd1ec45c48b32f3

**Comment by thomaswue** [comment]
@gilles-duboscq Is this related to the bug fix you are currently working on?

**Comment by gilles-duboscq** [comment]
@thomaswue If you are thinking about #1050, i wouldn't expect an `AFTER_BCI`, the fix i'm working on for #1050 is specific to the exception handling path where we would rather see `AFTER_EXCEPTION_BCI`.

@headius, according to the log, a second compilation was attempted for diagnostics, did it produce a diagnostic zip? That would contain the IR dumps which could be helpful in identifying the issue.
Can you run this with `-esa`? That might catch the error earlier.

How reproducible is it? Can you point us to a jruby version and a command line to reproduce?

**Comment by headius** [comment]
The setup is a bit involved so I can get back to you on that if the dumps are insufficient.

I've shared three dumps that occurred while using GraalVM to run a JRuby on Rails benchmark: https://drive.google.com/drive/folders/11eTZOJvv2vL9e_wCWTaoz3ffqSJtSSvP?usp=sharing

**Comment by gilles-duboscq** [comment]
Thank you for the dumps!
After a quick look I think they should be enough to identify and fix the issue.

**Comment by gilles-duboscq** [comment]
This should be fixed in d742661.

**Comment by headius** [comment]
I can confirm I don't get the message I reported above, but I'm still trying to confirm the methods in question are jitting properly.

**Comment by headius** [comment]
I managed to get this output from PrintCompilation running under GraalVM EE 19.1:

```
...
 192299 19017   !   3       Users.headius.projects.jruby.lib.ruby.stdlib.monitor::RUBY$method$broadcast$0 (121 bytes)
...
159849 28809   !   4       Users.headius.projects.jruby.lib.ruby.stdlib.monitor::RUBY$method$broadcast$0 (121 bytes)
```

I also see the tier 3 compile advance through "not entrant" and "zombie" on its way out.

This seems to confirm all tiers are able to compile the method that failed before.

**Comment by gilles-duboscq** [comment]
Thank you for confirming
