### ISSUE TITLE
SubstrateVM: Error in MulticastSocket

### ISSUE THREAD

**Issue by jerrinot** [oracle/graal#1082]
```java
import java.io.IOException;
import java.net.MulticastSocket;

public class Main {
    public static void main(String[] args) throws IOException {
        new MulticastSocket(null);
    }
}
```
this fails with
```
Exception in thread "main" java.net.SocketException: Bad address
	at java.net.PlainDatagramSocketImpl.socketSetOption0(PlainDatagramSocketImpl.java:1236)
	at java.net.PlainDatagramSocketImpl.socketSetOption(PlainDatagramSocketImpl.java:74)
	at java.net.AbstractPlainDatagramSocketImpl.setOption(AbstractPlainDatagramSocketImpl.java:309)
	at java.net.DatagramSocket.setReuseAddress(DatagramSocket.java:1086)
	at java.net.MulticastSocket.<init>(MulticastSocket.java:168)
	at info.jerrinot.testgraalnative.Main.main(Main.java:12)
```

I am not quite sure what's the best way to debug native images. When running with strace I can see:
```
socket(AF_INET6, SOCK_DGRAM, IPPROTO_IP) = 3
setsockopt(3, SOL_IPV6, IPV6_V6ONLY, [0], 4) = 0
setsockopt(3, SOL_SOCKET, SO_BROADCAST, [1], 4) = 0
setsockopt(3, SOL_IPV6, IPV6_RECVPKTINFO, [0], 4) = 0
setsockopt(3, SOL_IPV6, IPV6_MULTICAST_HOPS, [1], 4) = 0
setsockopt(3, SOL_SOCKET, SO_REUSEADDR, 0x1, 4) = -1 EFAULT (Bad address)
```

I assume SubstrateVM calls `setsockopt()` and pass a value `1` instead of a point to value `1`
```
       int setsockopt(int sockfd, int level, int optname, const void *optval, socklen_t optlen);
```

**Comment by jerrinot** [comment]
indeed I can reproduce it with
```c
#include <stdio.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>


void exitIfFailed(int code) {
    if (code != 0) {
        printf("%s\n", strerror(errno));
        exit(code);
    }
}

int main() {
    int fd = socket(AF_INET6, SOCK_DGRAM, IPPROTO_IP);

    int optval = 0;
    exitIfFailed(setsockopt(fd, SOL_IPV6, IPV6_V6ONLY, (const void *)&optval, 4));
    optval = 1;
    exitIfFailed(setsockopt(fd, SOL_SOCKET, SO_BROADCAST, (const void *)&optval, 4));
    optval = 0;
    exitIfFailed(setsockopt(fd, SOL_IPV6, IPV6_RECVPKTINFO, (const void *)&optval, 4));
    optval = 1;
    exitIfFailed(setsockopt(fd, SOL_IPV6, IPV6_MULTICAST_HOPS, (const void *)optval, 4));
    return 0;
}
```
please see the missing ampersand in the last `setsockopt()` call.

**Comment by jerrinot** [comment]
when I change [this](https://github.com/oracle/graal/blob/a86089fc936cb1ec199a70c6b6314021425ab64b/substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixJavaNetSubstitutions.java#L1234) to:
```java
WordPointer wordPointer = StackValue.get(WordPointer.class);
((CIntPointer)wordPointer).write(optval);
if (JavaNetNetUtilMD.NET_SetSockOpt(fd, level_Pointer.read(), optname_Pointer.read(), wordPointer, optlen) < 0) {
  throw new SocketException(PosixUtils.lastErrorString("Error setting socket option"));
}
```

then it seems to work. I cannot tell I fully understand it tho. This whole `WordFactory` business and Java to C-pointer translation is still a mystery to me. 

As a side-note: This [cache](https://github.com/oracle/graal/blob/1928ecd565097a6416f3614be0e174c9e617d3b7/compiler/src/org.graalvm.compiler.word/src/org/graalvm/compiler/word/Word.java#L1227) looks suspicious given the values are [not immutable](https://github.com/oracle/graal/blob/a5be24fd6c1d8a6a26c029110d89f931dce0aa85/substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/JavaNetNetUtil.java#L1818-L1820)

**Comment by Peter-B-Kessler** [comment]
Good catch!  

Your fix is not the way I would have fixed it: I would have declared `optval` a `CIntPointer` at its declaration, and then used `optval.read` and `optval.write` to access it where I was dealing with it as an `int`, and passed plain `optval` where I needed a `WordPointer`.

I will go fix it.  Thanks for the report.

**Comment by jerrinot** [comment]
@Peter-B-Kessler: your fix looks better indeed! 

to piggy-back on this issue: Is there any quick way to try changes in the `com.oracle.svm.core.posix` package? full ` mx --env ce build` is quite time consuming.

**Comment by Peter-B-Kessler** [comment]
@cstancu: Can you answer the question about less time-consuming ways to test out changes?  I certainly do not build the whole CE distribution to test out changes.  But I do not want to hand out  confusing instructions if there is already a nice write-up on how to build just a native image for, say, a test.

**Comment by cstancu** [comment]
@jerrinot  If you are only interested in `native-image` you can build a light version of GraalVM running `mx --disable-polyglot --disable-libpolyglot --dynamicimports /substratevm build` in [`graal/vm`](https://github.com/oracle/graal/tree/master/vm). See the [VM suite documentation](https://github.com/oracle/graal/tree/master/vm#vm-suite) for more details.

**Comment by jerrinot** [comment]
Thanks to both of you!
