### ISSUE TITLE
RInternalError: not implemented: .Internal gzcon

### ISSUE THREAD

**Issue by hugsyy** [oracle/graal#1105]
Hello,
I am running Spring Boot application on oracle/graalvm-ce:1.0.0-rc11 image. I installed R language using gu tool as well. When I run an RScript this line gives error. 

`load(url("link/test.rda"))`

Error: 

```
Caused by: org.graalvm.polyglot.PolyglotException: com.oracle.truffle.r.runtime.RInternalError: not implemented: .Internal gzcon
        at com.oracle.truffle.r.runtime.RInternalError.unimplemented(RInternalError.java:108)
        at com.oracle.truffle.r.nodes.builtin.InternalNode$InternalUninitializedNode.execute(InternalNode.java:143)
        at com.oracle.truffle.r.runtime.nodes.RNode.visibleExecute(RNode.java:74)
        at com.oracle.truffle.r.nodes.function.FunctionBodyNode.visibleExecute(FunctionBodyNode.java:58)
        at com.oracle.truffle.r.nodes.function.FunctionDefinitionNode.execute(FunctionDefinitionNode.java:280)
        at <R>.gzcon(Unknown)
        at <R>.load(unknown.r:1)
        at <R>.function(x, scd, request){\n#library(dply(Unnamed:9)
        at org.graalvm.polyglot.Value.execute(Value.java:338)
```

**Comment by steve-s** [comment]
Hello Ulugbek,

thank you for the report. We are working on an implementation of the `.Internal gzcon`.

**Comment by tstupka** [comment]
hi Ulugbek,

i understand that the original url was a complete url including the scheme - e.g. http://, https:// 
and not "link/test.rda", right?

**Comment by hugsyy** [comment]
@tstupka Hi Tomas, yes it was a complete url including the scheme.

**Comment by steve-s** [comment]
in such case it should be fixed in https://github.com/oracle/fastr/commit/291d948e549c7752976b0d86cea6200b43bb4d57 and should be in the next RC build. Please reopen this issue if you experience the problem again.
