### ISSUE TITLE
Invalid json processed by native-image-configure tool

### ISSUE THREAD

**Issue by ilopmar** [oracle/graal#1114]
I'm trying to use `native-image-configure` but I got the following error:

```
$ ~/native-image-configure process-trace --output-dir=./graal-config /tmp/trace-file.json 
com.oracle.svm.core.util.json.JSONParserException: line 91 column 137 Invalid JSON: String contains control character
	at com.oracle.svm.core.util.json.JSONParser.error(JSONParser.java:371)
	at com.oracle.svm.core.util.json.JSONParser.syntaxError(JSONParser.java:451)
	at com.oracle.svm.core.util.json.JSONParser.parseString(JSONParser.java:202)
	at com.oracle.svm.core.util.json.JSONParser.parseLiteral(JSONParser.java:86)
	at com.oracle.svm.core.util.json.JSONParser.parseArray(JSONParser.java:184)
	at com.oracle.svm.core.util.json.JSONParser.parseLiteral(JSONParser.java:84)
	at com.oracle.svm.core.util.json.JSONParser.parseObject(JSONParser.java:122)
	at com.oracle.svm.core.util.json.JSONParser.parseLiteral(JSONParser.java:82)
	at com.oracle.svm.core.util.json.JSONParser.parseArray(JSONParser.java:184)
	at com.oracle.svm.core.util.json.JSONParser.parseLiteral(JSONParser.java:84)
	at com.oracle.svm.core.util.json.JSONParser.parse(JSONParser.java:65)
	at com.oracle.svm.configure.trace.TraceProcessor.process(TraceProcessor.java:70)
	at com.oracle.svm.configure.ConfigurationTool.processTrace(ConfigurationTool.java:150)
	at com.oracle.svm.configure.ConfigurationTool.main(ConfigurationTool.java:68)
```

Please find attached the `trace-file.json` file (rename to .txt because of Github restrictions): [trace-file.json.txt](https://github.com/oracle/graal/files/3007342/trace-file.json.txt)

The json file was generated using the native-image-agent. If you need more info or the sample project used to generate the file, please let me know.

**Comment by cstancu** [comment]
@ilopmar thanks for the report. This is the same as https://github.com/oracle/graal/issues/1107.

**Comment by ilopmar** [comment]
Upps, sorry about that.
