### ISSUE TITLE
Strange ClassNotFound exception

### ISSUE THREAD

**Issue by gjevardat** [oracle/graal#1115]
Here is the situation using rc14
I have a fat executable jar (using openjpa) on which I run the native-image config file generator tool. It works well and I obtain all the different config json files.
```
java -agentlib:native-image-agent=output=trace.json -jar the.jar
native-image --tool:native-image-configure
./native-image-configure process-trace --output-dir=. trace.json
```

Then I run the  native-image generation and it is also working well. 
```
native-image --allow-incomplete-classpath --enable-all-security-services --verbose --report-unsupported-elements-at-runtime -H:+ReportExceptionStackTraces  -H:ConfigurationFileDirectories=jsonFiles/ -jar  the.jar
```

Then when I execute the native image I have a ClassNotFoundException
```java
Exception in thread "main" <openjpa-3.0.0-r422266:1833209 fatal user error> org.apache.openjpa.persistence.ArgumentException: localized message key: bad-new-brokerfactory; substitutions: [<<openjpa-3.0.0-r422266:1833209 fatal user error> org.apache.openjpa.util.UserException: localized message key: bad-brokerfactory-class; substitutions: [org.apache.openjpa.jdbc.kernel.JDBCBrokerFactory]>]
	at org.apache.openjpa.kernel.Bootstrap.newBrokerFactory(Bootstrap.java:76)
	at org.apache.openjpa.persistence.PersistenceProviderImpl.getBrokerFactory(PersistenceProviderImpl.java:149)
	at org.apache.openjpa.persistence.PersistenceProviderImpl.createEntityManagerFactory(PersistenceProviderImpl.java:92)
	at org.apache.openjpa.persistence.PersistenceProviderImpl.createEntityManagerFactory(PersistenceProviderImpl.java:155)
	at org.apache.openjpa.persistence.PersistenceProviderImpl.createEntityManagerFactory(PersistenceProviderImpl.java:63)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)
	at MyMain.main(MyMain.java:30)
Caused by: <openjpa-3.0.0-r422266:1833209 fatal user error> org.apache.openjpa.persistence.ArgumentException: localized message key: bad-brokerfactory-class; substitutions: [org.apache.openjpa.jdbc.kernel.JDBCBrokerFactory]
	at org.apache.openjpa.kernel.Bootstrap.getFactoryClass(Bootstrap.java:166)
	at org.apache.openjpa.kernel.Bootstrap.invokeFactory(Bootstrap.java:118)
	at org.apache.openjpa.kernel.Bootstrap.newBrokerFactory(Bootstrap.java:66)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.openjpa.jdbc.kernel.JDBCBrokerFactory
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:51)
	at java.lang.Class.forName(DynamicHub.java:1083)
	at org.apache.openjpa.kernel.Bootstrap.getFactoryClass(Bootstrap.java:164)
	... 8 more
```

It is puzzling because I'am 100% sure the JDBCBrokerFActory is in the fat jar.

**Comment by cstancu** [comment]
@gjevardat is `org.apache.openjpa.jdbc.kernel.JDBCBrokerFactory` in the reflection config file? Do you see any warnings regarding registering elements for reflection from the `native-image` command?

**Comment by gjevardat** [comment]
Good question :) Actually it is not in the reflection config file. But if I add it manually it produces same ClassNotFound error.
In my first attempts to build native image using manually feeded config file I had to add this reflection config for JDBCBroker Factory, but for whatever reason the trace agent does not...

**Comment by gjevardat** [comment]
Can I provide a classpath to native image such that it can load bytecode if the class is not found in the native image ?

**Comment by gjevardat** [comment]
To answer your question I do not see any warnings during native image build

**Comment by cstancu** [comment]
> Can I provide a classpath to native image such that it can load bytecode if the class is not found in the native image ?

No, the `native-image` cannot currently run bytecodes loaded at run time.

**Comment by cstancu** [comment]
Can this be reproduced with the same repo from https://github.com/oracle/graal/issues/1096, https://github.com/gjevardat/graalopenjpa ?

**Comment by cstancu** [comment]
Please re-open and provide a reproducible example if this is still a problem with the latest release.
