### ISSUE TITLE
[native-image] can't compile simple Tomcat application

### ISSUE THREAD

**Issue by Denis7775** [oracle/graal#1124]
Hi!
For now I try to make a native image from simple web application with embedded Tomcat, I solved some problems connected with reflection, providing necessary classes in json file, but I faced with another problem:

```
WARNING: A context path must either be an empty string or start with a '/' and do not end with a '/'. The path [/] does not meet these criteria and has been changed to []
Mar 31, 2019 10:56:21 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8080"]
Mar 31, 2019 10:56:21 AM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
Mar 31, 2019 10:56:21 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Mar 31, 2019 10:56:21 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.0.48
Mar 31, 2019 10:56:21 AM org.apache.catalina.core.ContainerBase startInternal
SEVERE: A child container failed during start
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[/]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:943)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:871)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:481)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[/]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
	... 8 more
Caused by: org.apache.catalina.LifecycleException: Failed to initialize component [org.apache.catalina.webresources.StandardRoot@7f637320da78]
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:135)
	at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4968)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5101)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	... 8 more
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported field java.net.URL.handlers is reachable
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:102)
	at java.net.URL.setURLStreamHandlerFactory(URL.java:1118)
	at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.<init>(TomcatURLStreamHandlerFactory.java:130)
	at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.getInstanceInternal(TomcatURLStreamHandlerFactory.java:53)
	at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.register(TomcatURLStreamHandlerFactory.java:77)
	at org.apache.catalina.webresources.StandardRoot.registerURLStreamHandlerFactory(StandardRoot.java:697)
	at org.apache.catalina.webresources.StandardRoot.initInternal(StandardRoot.java:680)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
	... 12 more

Mar 31, 2019 10:56:21 AM org.apache.catalina.core.ContainerBase startInternal
SEVERE: A child container failed during start
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:943)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:441)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:789)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:370)
	at SimpleWebApp.main(SimpleWebApp.java:43)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:481)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: org.apache.catalina.LifecycleException: A child container failed during start
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:951)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:871)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	... 8 more

Exception in thread "main" org.apache.catalina.LifecycleException: Failed to start component [StandardServer[-1]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:370)
	at SimpleWebApp.main(SimpleWebApp.java:43)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardService[Tomcat]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:789)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	... 2 more
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:441)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	... 4 more
Caused by: org.apache.catalina.LifecycleException: A child container failed during start
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:951)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	... 6 more
```

the application is:

```
public class SimpleWebApp {

    public static void main(String[] args) throws LifecycleException {
        Tomcat tomcat = new Tomcat();
        tomcat.setBaseDir("temp");
        tomcat.setPort(8080);

        String contextPath = "/";
        String docBase = new File(".").getAbsolutePath();

        Context context = tomcat.addContext(contextPath, docBase);

        HttpServlet servlet = new HttpServlet() {
            @Override
            protected void doGet(HttpServletRequest req, HttpServletResponse resp)
                    throws ServletException, IOException {
                PrintWriter writer = resp.getWriter();

                writer.println("<html><title>Welcome</title><body>");
                writer.println("<h1>Have a Great Day!</h1>");
                writer.println("</body></html>");
            }
        };

        String servletName = "Servlet1";
        String urlPattern = "/go";

        tomcat.addServlet(contextPath, servletName, servlet);
        context.addServletMappingDecoded(urlPattern, servletName);

        tomcat.start();
        tomcat.getServer().await();
    }
}
```
Does anyone have some ideas how to solve this problem?
Thanks

**Comment by cstancu** [comment]
@Denis7775 did you [enable http](https://github.com/oracle/graal/blob/master/substratevm/URL-PROTOCOLS.md#url-protocols-on-substrate-vm)? Can you please provide a complete reproducible example, i.e., also the maven/gradle config, etc.?

**Comment by Denis7775** [comment]
@cstancu , the repo https://github.com/Denis7775/tomcat-native-image, I've solved some problems with reflection(tomcat-reflection-config.json)
1)I tried to construct image within the jar that now in repo(out/...) and get the next error while compiling
```
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of java.lang.Class$Atomic. Add a RecomputeFieldValue.FieldOffset manual substitution for java.lang.Class$Atomic.reflectionDataOffset. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field.
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of java.lang.Class$Atomic. Add a RecomputeFieldValue.FieldOffset manual substitution for java.lang.Class$Atomic.annotationTypeOffset. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field.
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of java.lang.Class$Atomic. Add a RecomputeFieldValue.FieldOffset manual substitution for java.lang.Class$Atomic.annotationDataOffset. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field.
```
but dispite thit mistake, image finally constructed and I get a mistake that I've already mention in this issue

2)After that I tried to recompute offset by adding the next class

```
import com.oracle.svm.core.annotate.Alias;
import com.oracle.svm.core.annotate.RecomputeFieldValue;
import com.oracle.svm.core.annotate.TargetClass;

@TargetClass(className = "java.lang.Class$Atomic")
final class Target_java_lang_Class$Atomic {
    @Alias
    @RecomputeFieldValue(kind = RecomputeFieldValue.Kind.FieldOffset, declClass = Class.class, name = "reflectionData")
    private static long reflectionDataOffset;

    @Alias
    @RecomputeFieldValue(kind = RecomputeFieldValue.Kind.FieldOffset, declClass = Class.class, name = "annotationType")
    private static long annotationTypeOffset;

    @Alias
    @RecomputeFieldValue(kind = RecomputeFieldValue.Kind.FieldOffset, declClass = Class.class, name = "annotationData")
    private static long annotationDataOffset;
}

public class TomcatSubstitutions {
}
```
but after that the application can't even compile, iscrashes with error

```
Error: Field java.lang.Class.annotationData is not present on type java.lang.Class. Error encountered while analysing com.oracle.svm.core.MonitorSupport.getOrCreateMonitor(java.lang.Object, boolean) 
Parsing context:
	parsing com.oracle.svm.core.MonitorSupport.monitorEnter(MonitorSupport.java:106)

com.oracle.graal.pointsto.util.AnalysisError$FieldNotPresentError: Field java.lang.Class.annotationData is not present on type java.lang.Class. Error encountered while analysing com.oracle.svm.core.MonitorSupport.getOrCreateMonitor(java.lang.Object, boolean) 
Parsing context:
	parsing com.oracle.svm.core.MonitorSupport.monitorEnter(MonitorSupport.java:106)

	at com.oracle.graal.pointsto.util.AnalysisError.fieldNotPresentError(AnalysisError.java:152)
	at com.oracle.graal.pointsto.flow.context.object.AnalysisObject.getInstanceFieldTypeStore(AnalysisObject.java:220)
	at com.oracle.graal.pointsto.flow.context.object.AnalysisObject.getInstanceFieldFilterFlow(AnalysisObject.java:187)
	at com.oracle.graal.pointsto.flow.OffsetStoreTypeFlow$AbstractUnsafeStoreTypeFlow.handleUnsafeAccessedFields(OffsetStoreTypeFlow.java:192)
	at com.oracle.graal.pointsto.flow.OffsetStoreTypeFlow$AbstractUnsafeStoreTypeFlow.onObservedUpdate(OffsetStoreTypeFlow.java:228)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:352)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:394)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:508)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:169)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Processing image build request failed
```
So, for now I am confused with such results, especially the last one, because we have such fields in Class

command line for construction an image:
```
 native-image -jar embedded-tomcat.jar -H:ReflectionConfigurationResources=tomcat-reflection-config.json --report-unsupported-elements-at-runtime -H:+ReportExceptionStackTraces --enable-all-security-services
```

**Comment by ninja-** [comment]
just got the same issue after switching from 20.0 to 20.0-java11...
