### ISSUE TITLE
emitPause not implemented in LLVM backend

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#1126]
The LLVMGenerator has currently no implementation for emitPause:

Caused by: org.graalvm.compiler.debug.GraalError: unimplemented
	at jdk.internal.vm.compiler/org.graalvm.compiler.debug.GraalError.unimplemented(GraalError.java:39)
	at org.graalvm.compiler.core.llvm.LLVMGenerator.emitPause(LLVMGenerator.java:951)
	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.PauseNode.generate(PauseNode.java:51)
	at org.graalvm.compiler.core.llvm.NodeLLVMBuilder.emitNode(NodeLLVMBuilder.java:265)
	at org.graalvm.compiler.core.llvm.NodeLLVMBuilder.doRoot(NodeLLVMBuilder.java:255)

**Comment by vjovanov** [comment]
@loicottet the only thing I found (besides writing our own assembly) is:
 
  https://llvm.org/docs/LangRef.html#llvm-donothing-intrinsic

WDYT?

**Comment by johanvos** [comment]
that should work imho
