### ISSUE TITLE
Truffle language installation after update from rc12 to rc14

### ISSUE THREAD

**Issue by jmaschad** [oracle/graal#1133]
After updating from graal 1.0.0-rc12 to 1.0.0-rc14 I get an `IllegalArgumentException` when trying to eval a script of my truffle language. When switching back to rc12 everything works fine again.

```
Exception in thread "main" java.lang.IllegalArgumentException: A language with id 'dc' is not installed. Installed languages are: [js, llvm].
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.requirePublicLanguage(PolyglotEngineImpl.java:687)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.requirePublicLanguage(PolyglotContextImpl.java:776)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:747)
	at org.graalvm.polyglot.Context.eval(Context.java:335)
	at org.jmal.datacalc.Main.executeSource(Main.java:33)
	at org.jmal.datacalc.Main.main(Main.java:18)
```

I searched the change log and also tried to find a relevant change in *Simple Language* but could not find anything.

**Comment by jmaschad** [comment]
`-XX:-UseJVMCIClassLoader` fixed the issue. Apparently, that option was not strictly necessary with rc12 so I missed it in the original project setup.

**Comment by chumer** [comment]
Yes, this was the case precisely for RC-12.  RC-11 had the current behavior. Sorry for the confusion.
Please check out the [documentation](https://www.graalvm.org/docs/graalvm-as-a-platform/implement-language/#running-simplelanguage-using-command-line) regarding this.
