### ISSUE TITLE
Native image blows up when it accesses Method.getDefaultValue()

### ISSUE THREAD

**Issue by dsyer** [oracle/graal#1135]
`Annotation` classes have `Methods` with default values. It is useful to access the default value reflectively, but it blows up in a native image, even if you declare the annotation type in `reflect-confg.json`. 

Here's an example error:

```
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported method java.lang.Class.getConstantPool() is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:102)
	at java.lang.Class.getConstantPool(DynamicHub.java)
	at java.lang.System$2.getConstantPool(System.java:1227)
	at java.lang.reflect.Method.getDefaultValue(Method.java:609)
	at com.sample.App.main(App.java:23)
```

Sample project: https://github.com/sdeleuze/graal-issues/pull/9

**Comment by dsyer** [comment]
Similar to #1135 (arises in a similar use case) but the error is different, so possibly not the same thing.

**Comment by cstancu** [comment]
This is fixed by https://github.com/oracle/graal/commit/ef950cc5fe3506f45403571c4c15badcdf2115d1.
