### ISSUE TITLE
NativeImage server-id-XYZ file name too long

### ISSUE THREAD

**Issue by plutext** [oracle/graal#1161]
```
Could not recursively delete path: /home/jharrop/.native-image/machine-id-d9ff46071e9b4bf799d1540eef9bf325/session-id-78e8/server-id-9a7cc9922191cd902698d719de72d817fa20648721e14bf14243f1683e6ab4b0c86aad2e747f83404ede13a28313987adf547c6fba340149566eb2551265f937
java.nio.file.FileSystemException: /home/jharrop/.native-image/machine-id-d9ff46071e9b4bf799d1540eef9bf325/session-id-78e8/server-id-9a7cc9922191cd902698d719de72d817fa20648721e14bf14243f1683e6ab4b0c86aad2e747f83404ede13a28313987adf547c6fba340149566eb2551265f937 -> /home/jharrop/.native-image/machine-id-d9ff46071e9b4bf799d1540eef9bf325/session-id-78e8/server-id-9a7cc9922191cd902698d719de72d817fa20648721e14bf14243f1683e6ab4b0c86aad2e747f83404ede13a28313987adf547c6fba340149566eb2551265f937.deleted: File name too long
        at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:457)
        at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
        at java.nio.file.Files.move(Files.java:1395)
        at com.oracle.svm.driver.NativeImage.deleteAllFiles(NativeImage.java:1394)
        at com.oracle.svm.driver.NativeImageServer$Server.shutdown(NativeImageServer.java:274)
        at com.oracle.svm.driver.NativeImageServer.lambda$cleanupServers$8(NativeImageServer.java:532)
        at com.oracle.svm.driver.NativeImageServer.withFileChannel(NativeImageServer.java:661)
        at com.oracle.svm.driver.NativeImageServer.withLockDirFileChannel(NativeImageServer.java:650)
        at com.oracle.svm.driver.NativeImageServer.cleanupServers(NativeImageServer.java:523)
        at com.oracle.svm.driver.NativeImageServer.buildImage(NativeImageServer.java:750)
        at com.oracle.svm.driver.NativeImage.completeImageBuild(NativeImage.java:951)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1030)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1008)
Error: Image build request failed with exit status -1
```
There is:
```
String serverUID = imageServerUID(javaArgs, builderPaths);
Path serverDir = sessionDir.resolve(serverDirPrefix + serverUID);
```

where

```
    private static String imageServerUID(List<String> vmArgs, List<Collection<Path>> builderPaths) {
        MessageDigest digest;
        try {
            digest = MessageDigest.getInstance("SHA-512");
        } catch (NoSuchAlgorithmException e) {
            throw showError("SHA-512 digest is not available", e);
        }
        for (Collection<Path> paths : builderPaths) {
            for (Path path : paths) {
                digest.update(path.toString().getBytes());
                updateHash(digest, path);
            }
        }
        for (String string : vmArgs) {
            digest.update(string.getBytes());
        }

        byte[] digestBytes = digest.digest();
        StringBuilder sb = new StringBuilder(digestBytes.length * 2);
        for (byte b : digestBytes) {
            sb.append(String.format("%02x", b & 0xff));
        }
        return sb.toString();
    }
```

Nothing is stopping that from getting too long?

Happens with rc15.  How to work around this please?

**Comment by olpaw** [comment]
> Nothing is stopping that from getting too long?

The digest of an SHA-512 is always the same size (512 bits). I don't know what you mean by "Nothing is stopping that from getting too long". We haven't encountered a system where that code caused any problems. Please provide detailed system specifications (Linux Version, Distribution, Filesystem used for /home/jharrop, ....) so that we have a chance to reproduce the issue.

As a workaround you can use `--no-server` for now.

**Comment by plutext** [comment]
Linux 4.19; Manjaro; 
dev/mapper/cryptroot /home btrfs rw,noatime,compress=lzo,ssd,space_cache,commit=120,subvolid=258,subvol=/@home 0 0

But the problem only just started happening.  That is, I happily ran the native-image command a number of times yesterday before it suddenly started to give that error.

I have found that I can ignore the error; "Fallback to one-shot image building ..." works for me.

```
Could not recursively delete path: /home/jharrop/.native-image/machine-id-d9ff46071e9b4bf799d1540eef9bf325/session-id-1882/server-id-ae5e4c5f0b55b075cc1c082f9faf99a7f60e28dea31c54bfc3c6067b29899ed104eb321d753b12fde44d1c938af075dbfb402d0feac369450241cff023abc00c
java.nio.file.FileSystemException: /home/jharrop/.native-image/machine-id-d9ff46071e9b4bf799d1540eef9bf325/session-id-1882/server-id-ae5e4c5f0b55b075cc1c082f9faf99a7f60e28dea31c54bfc3c6067b29899ed104eb321d753b12fde44d1c938af075dbfb402d0feac369450241cff023abc00c -> /home/jharrop/.native-image/machine-id-d9ff46071e9b4bf799d1540eef9bf325/session-id-1882/server-id-ae5e4c5f0b55b075cc1c082f9faf99a7f60e28dea31c54bfc3c6067b29899ed104eb321d753b12fde44d1c938af075dbfb402d0feac369450241cff023abc00c.deleted: File name too long
        at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:457)
        at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
        at java.nio.file.Files.move(Files.java:1395)
        at com.oracle.svm.driver.NativeImage.deleteAllFiles(NativeImage.java:1394)
        at com.oracle.svm.driver.NativeImageServer.lambda$startServer$9(NativeImageServer.java:601)
        at com.oracle.svm.driver.NativeImageServerHelper.daemonize(NativeImageServerHelper.java:59)
        at com.oracle.svm.driver.NativeImageServer.startServer(NativeImageServer.java:564)
        at com.oracle.svm.driver.NativeImageServer.lambda$getServerInstance$2(NativeImageServer.java:438)
        at com.oracle.svm.driver.NativeImageServer.withFileChannel(NativeImageServer.java:661)
        at com.oracle.svm.driver.NativeImageServer.getServerInstance(NativeImageServer.java:380)
        at com.oracle.svm.driver.NativeImageServer.buildImage(NativeImageServer.java:741)
        at com.oracle.svm.driver.NativeImage.completeImageBuild(NativeImage.java:951)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1030)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1008)
Error: Starting image-build server instance failed
Caused by: com.oracle.svm.driver.NativeImage$NativeImageError: Could not determine port for sending image-build requests.
Server stdout/stderr:
The log file already exists, or could not be created.
Warning: Creating image-build server failed. Fallback to one-shot image building ...
```

**Comment by olpaw** [comment]
> Do you think btrfs might be the culprit here? Something to do with deleting/re-using that file path too many times?

That could indeed be a problem with the filesystem. I will close this issue. Feel free to reopen if you are able to reproduce the issue on ext4.

**Comment by peter-hofer** [comment]
Could you post the output of `find /home/jharrop/.native-image/ -ls` please?

**Comment by plutext** [comment]
```
$ find /home/jharrop/.native-image/ -ls
  3089724      0 drwxr-xr-x   1  jharrop  jharrop       248 Apr 14 18:16 /home/jharrop/.native-image/
  7860878      0 drwxr-xr-x   1  jharrop  jharrop       376 Apr 14 18:16 /home/jharrop/.native-image/machine-id-d9ff46071e9b4bf799d1540eef9bf325
  7860879      8 -rw-r--r--   1  jharrop  jharrop         0 Apr 14 18:16 /home/jharrop/.native-image/machine-id-d9ff46071e9b4bf799d1540eef9bf325/create-server.lock
  7860880      0 drwxr-xr-x   1  jharrop  jharrop       672 Apr 14 18:16 /home/jharrop/.native-image/machine-id-d9ff46071e9b4bf799d1540eef9bf325/session-id-1882
  7860881      8 -rw-r--r--   1  jharrop  jharrop         0 Apr 14 18:16 /home/jharrop/.native-image/machine-id-d9ff46071e9b4bf799d1540eef9bf325/session-id-1882/.lock
  7860882      0 drwxr-xr-x   1  jharrop  jharrop       752 Apr 14 18:16 /home/jharrop/.native-image/machine-id-d9ff46071e9b4bf799d1540eef9bf325/session-id-1882/server-id-ae5e4c5f0b55b075cc1c082f9faf99a7f60e28dea31c54bfc3c6067b29899ed104eb321d753b12fde44d1c938af075dbfb402d0feac369450241cff023abc00c
  7860883     24 -rw-r--r--   1  jharrop  jharrop     14036 Apr 15 07:47 /home/jharrop/.native-image/machine-id-d9ff46071e9b4bf799d1540eef9bf325/session-id-1882/server-id-ae5e4c5f0b55b075cc1c082f9faf99a7f60e28dea31c54bfc3c6067b29899ed104eb321d753b12fde44d1c938af075dbfb402d0feac369450241cff023abc00c/server.log
  7860884     12 -rw-r--r--   1  jharrop  jharrop      1140 Apr 14 18:16 /home/jharrop/.native-image/machine-id-d9ff46071e9b4bf799d1540eef9bf325/session-id-1882/server-id-ae5e4c5f0b55b075cc1c082f9faf99a7f60e28dea31c54bfc3c6067b29899ed104eb321d753b12fde44d1c938af075dbfb402d0feac369450241cff023abc00c/server.properties
  7860885      8 -rw-r--r--   1  jharrop  jharrop         0 Apr 14 18:16 /home/jharrop/.native-image/machine-id-d9ff46071e9b4bf799d1540eef9bf325/session-id-1882/server-id-ae5e4c5f0b55b075cc1c082f9faf99a7f60e28dea31c54bfc3c6067b29899ed104eb321d753b12fde44d1c938af075dbfb402d0feac369450241cff023abc00c/.lock
  7860886     20 -rw-r--r--   1  jharrop  jharrop     11614 Apr 15 07:47 /home/jharrop/.native-image/machine-id-d9ff46071e9b4bf799d1540eef9bf325/session-id-1882/server-id-ae5e4c5f0b55b075cc1c082f9faf99a7f60e28dea31c54bfc3c6067b29899ed104eb321d753b12fde44d1c938af075dbfb402d0feac369450241cff023abc00c/build-request.log
```
