### ISSUE TITLE
Compilation failure with graalvm 1.0.0 RC16

### ISSUE THREAD

**Issue by hlolli** [oracle/graal#1182]
I am using clang 5-0, gcc 7.4.0, jvmci "0.59" built with openjdk version "1.8.0_202".

```
52686 method(s) included for runtime compilation
WARNING: suspicious method reachable for runtime compilation: com.oracle.svm.core.deopt.Deoptimizer.deoptSourceFrameOperation(CodePointer, boolean, IsolateThread)
Check the complete tree of reachable methods using the option PrintRuntimeCompileMethods
Suspicious method is called from
  com.oracle.svm.core.deopt.Deoptimizer.access$000(Deoptimizer.java:146) -> com.oracle.svm.core.deopt.Deoptimizer$DeoptSourceFrameOperation.operate(Deoptimizer.java:596)
  com.oracle.svm.core.thread.VMOperation.operateUnderIndicator(VMOperation.java:149)
  com.oracle.svm.core.thread.VMOperation.execute(VMOperation.java:134)
  com.oracle.svm.core.thread.VMOperationControl$Worklist.drain(VMOperationControl.java:316)
  com.oracle.svm.core.thread.VMOperationControl.drain(VMOperationControl.java:181)
  com.oracle.svm.core.thread.VMOperationControl.enqueue(VMOperationControl.java:163)
  com.oracle.svm.core.thread.VMOperation.enqueue(VMOperation.java:99)
  com.oracle.svm.core.thread.VMOperation.enqueueBlockingNoSafepoint(VMOperation.java:125)
  com.oracle.svm.core.thread.JavaThreads.interruptVMCondVars(JavaThreads.java:517) -> com.oracle.svm.core.thread.Target_java_lang_Thread.interrupt0(JavaThreads.java:892)
  java.lang.Thread.interrupt(Thread.java:922)
  java.io.PrintStream.newLine(PrintStream.java:556)
  java.io.PrintStream.println(PrintStream.java:808)
  com.ibm.icu.impl.Trie2Writable.freeze(Trie2Writable.java:1098)
  com.ibm.icu.impl.Trie2Writable.toTrie2_32(Trie2Writable.java:998)
  com.ibm.icu.impl.Normalizer2Impl.ensureCanonIterData(Normalizer2Impl.java:655)
  com.ibm.icu.impl.UCharacterProperty$5.contains(UCharacterProperty.java:305)
  com.ibm.icu.impl.UCharacterProperty.getIntPropertyValue(UCharacterProperty.java:621)
  com.ibm.icu.lang.UCharacter.getIntPropertyValue(UCharacter.java:5683) -> com.ibm.icu.text.RuleBasedBreakIterator.getLanguageBreakEngine(RuleBasedBreakIterator.java:682)
  com.ibm.icu.text.RuleBasedBreakIterator.access$100(RuleBasedBreakIterator.java:40) -> com.ibm.icu.text.RuleBasedBreakIterator$DictionaryCache.populateDictionary(RuleBasedBreakIterator.java:1211)
  com.ibm.icu.text.RuleBasedBreakIterator$BreakCache.populateFollowing(RuleBasedBreakIterator.java:1522)
  com.ibm.icu.text.RuleBasedBreakIterator$BreakCache.populateNear(RuleBasedBreakIterator.java:1458)
  com.ibm.icu.text.RuleBasedBreakIterator.first(RuleBasedBreakIterator.java:364)
  com.ibm.icu.text.RuleBasedBreakIterator.setText(RuleBasedBreakIterator.java:647)
  com.ibm.icu.text.BreakIterator.setText(BreakIterator.java:514)
  com.oracle.truffle.js.builtins.SegmenterPrototypeBuiltins$CreateSegmentIteratorNode.execute(SegmenterPrototypeBuiltins.java:148)
  com.oracle.truffle.js.builtins.SegmenterPrototypeBuiltins$JSSegmenterSegmentNode.doSegment(SegmenterPrototypeBuiltins.java:123)
  com.oracle.truffle.js.builtins.SegmenterPrototypeBuiltinsFactory$JSSegmenterSegmentNodeGen.execute(SegmenterPrototypeBuiltinsFactory.java:164)
  com.oracle.truffle.js.nodes.control.AsyncFunctionBodyNode$AsyncFunctionRootNode.execute(AsyncFunctionBodyNode.java:95)
  org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:325)
  org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:315)

[libpolyglot:32401]     universe:   7,732.52 ms
[libpolyglot:32401]      (parse):   7,393.96 ms
[libpolyglot:32401]      compile:   7,406.62 ms
Fatal error: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.NullPointerException
        at parsing com.oracle.svm.core.hub.DynamicHub.getMethod(DynamicHub.java:971)
        at method: Method java.lang.Class.getMethod(String, Class[])
        at org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2621)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:85)
        at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3421)
        at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3223)
        at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:944)
        at com.oracle.svm.hosted.phases.HostedBytecodeParser.build(HostedGraphBuilderPhase.java:107)
        at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:838)
        at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
        at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at com.oracle.svm.hosted.code.CompileQueue.defaultParseFunction(CompileQueue.java:713)
        at com.oracle.svm.hosted.code.CompileQueue.doParse(CompileQueue.java:679)
        at com.oracle.svm.hosted.code.CompileQueue$ParseTask.run(CompileQueue.java:302)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedMethod(SharedGraphBuilderPhase.java:190)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedInvoke(SharedGraphBuilderPhase.java:156)
        at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1534)
        at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1509)
        at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5257)
        at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3416)
        ... 18 more
Error: Image build request failed with exit status 1
```

**Comment by fniephaus** [comment]
What did you try to compile? Could you please provide steps to reproduce this?

**Comment by hlolli** [comment]
`mx -v --dynamicimports /substratevm,/tools,sulong,/graal-nodejs,graalpython build`

**Comment by eregon** [comment]
Looks like a missing `@TruffleBoundary` before calling `  com.ibm.icu.text.*` methods.
cc @woess @wirthi 

Also, SubstrateVM should probably have `java.lang.Thread.interrupt` as an implicit boundary. cc @cstancu

**Comment by hlolli** [comment]
Because I had 20 minutes to spare, I tried compiling with this patch on newest master
```patch
diff --git a/substratevm/src/com.oracle.svm.thirdparty/src/com/oracle/svm/thirdparty/ICU4JFeature.java b/substratevm/src/com.oracle.svm.thirdparty/src/com/oracle/svm/thirdparty/ICU4JFeature.java
index 3c69f0501a3..8e76656202a 100644
--- a/substratevm/src/com.oracle.svm.thirdparty/src/com/oracle/svm/thirdparty/ICU4JFeature.java
+++ b/substratevm/src/com.oracle.svm.thirdparty/src/com/oracle/svm/thirdparty/ICU4JFeature.java
@@ -34,6 +34,8 @@ import org.graalvm.nativeimage.hosted.Feature;
 import org.graalvm.nativeimage.ImageSingletons;
 import org.graalvm.nativeimage.hosted.RuntimeReflection;
 
+import com.oracle.truffle.api.CompilerDirectives.TruffleBoundary;
+
 import com.oracle.svm.core.annotate.Alias;
 import com.oracle.svm.core.annotate.AutomaticFeature;
 import com.oracle.svm.core.annotate.InjectAccessors;
@@ -69,6 +71,7 @@ public final class ICU4JFeature implements Feature {
     }
 
     @Override
+    @TruffleBoundary
     public void beforeAnalysis(BeforeAnalysisAccess access) {
         registerShimClass(access, "com.ibm.icu.text.NumberFormatServiceShim");
         registerShimClass(access, "com.ibm.icu.text.CollatorServiceShim");
```

Does the stacktrace look the same

```
[libpolyglot:32400]    classlist:   6,758.10 ms
[libpolyglot:32400]        (cap):   1,737.37 ms
[libpolyglot:32400]        setup:   3,149.94 ms
[libpolyglot:32400]   (typeflow):  64,986.65 ms
[libpolyglot:32400]    (objects): 113,330.65 ms
[libpolyglot:32400]   (features):  48,150.00 ms
[libpolyglot:32400]     analysis: 231,007.56 ms
52687 method(s) included for runtime compilation
WARNING: suspicious method reachable for runtime compilation: com.oracle.svm.core.deopt.Deoptimizer.deoptSourceFrameOperation(CodePointer, boolean, IsolateThread)
Check the complete tree of reachable methods using the option PrintRuntimeCompileMethods
Suspicious method is called from
  com.oracle.svm.core.deopt.Deoptimizer.access$000(Deoptimizer.java:146) -> com.oracle.svm.core.deopt.Deoptimizer$DeoptSourceFrameOperation.operate(Deoptimizer.java:596)
  com.oracle.svm.core.thread.VMOperation.operateUnderIndicator(VMOperation.java:149)
  com.oracle.svm.core.thread.VMOperation.execute(VMOperation.java:134)
  com.oracle.svm.core.thread.VMOperationControl$Worklist.drain(VMOperationControl.java:316)
  com.oracle.svm.core.thread.VMOperationControl.drain(VMOperationControl.java:181)
  com.oracle.svm.core.thread.VMOperationControl.enqueue(VMOperationControl.java:163)
  com.oracle.svm.core.thread.VMOperation.enqueue(VMOperation.java:99)
  com.oracle.svm.core.thread.VMOperation.enqueueBlockingNoSafepoint(VMOperation.java:125)
  com.oracle.svm.core.thread.JavaThreads.interruptVMCondVars(JavaThreads.java:517) -> com.oracle.svm.core.thread.Target_java_lang_Thread.interrupt0(JavaThreads.java:892)
  java.lang.Thread.interrupt(Thread.java:922)
  java.io.PrintStream.newLine(PrintStream.java:556)
  java.io.PrintStream.println(PrintStream.java:808)
  com.ibm.icu.impl.Trie2Writable.freeze(Trie2Writable.java:1098)
  com.ibm.icu.impl.Trie2Writable.toTrie2_32(Trie2Writable.java:998)
  com.ibm.icu.impl.Normalizer2Impl.ensureCanonIterData(Normalizer2Impl.java:655)
  com.ibm.icu.impl.UCharacterProperty$5.contains(UCharacterProperty.java:305)
  com.ibm.icu.impl.UCharacterProperty.getIntPropertyValue(UCharacterProperty.java:621)
  com.ibm.icu.lang.UCharacter.getIntPropertyValue(UCharacter.java:5683) -> com.ibm.icu.text.RuleBasedBreakIterator.getLanguageBreakEngine(RuleBasedBreakIterator.java:682)
  com.ibm.icu.text.RuleBasedBreakIterator.access$100(RuleBasedBreakIterator.java:40) -> com.ibm.icu.text.RuleBasedBreakIterator$DictionaryCache.populateDictionary(RuleBasedBreakIterator.java:1211)
  com.ibm.icu.text.RuleBasedBreakIterator$BreakCache.populateFollowing(RuleBasedBreakIterator.java:1522)
  com.ibm.icu.text.RuleBasedBreakIterator$BreakCache.populateNear(RuleBasedBreakIterator.java:1458)
  com.ibm.icu.text.RuleBasedBreakIterator.first(RuleBasedBreakIterator.java:364)
  com.ibm.icu.text.RuleBasedBreakIterator.setText(RuleBasedBreakIterator.java:647)
  com.ibm.icu.text.BreakIterator.setText(BreakIterator.java:514)
  com.oracle.truffle.js.builtins.SegmenterPrototypeBuiltins$CreateSegmentIteratorNode.execute(SegmenterPrototypeBuiltins.java:148)
  com.oracle.truffle.js.builtins.SegmenterPrototypeBuiltins$JSSegmenterSegmentNode.doSegment(SegmenterPrototypeBuiltins.java:123)
  com.oracle.truffle.js.builtins.SegmenterPrototypeBuiltinsFactory$JSSegmenterSegmentNodeGen.execute(SegmenterPrototypeBuiltinsFactory.java:164)
  com.oracle.truffle.js.nodes.control.AsyncFunctionBodyNode$AsyncFunctionRootNode.execute(AsyncFunctionBodyNode.java:95)
  org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:325)
  org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:315)

[libpolyglot:32400]     universe:   7,318.14 ms
[libpolyglot:32400]      (parse):   7,787.16 ms
[libpolyglot:32400]      compile:   7,801.58 ms
Fatal error: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.NullPointerException
        at parsing com.oracle.svm.core.hub.DynamicHub.getMethod(DynamicHub.java:971)
        at method: Method java.lang.Class.getMethod(String, Class[])
        at org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2621)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:85)
        at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3421)
        at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3223)
        at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:944)
        at com.oracle.svm.hosted.phases.HostedBytecodeParser.build(HostedGraphBuilderPhase.java:107)
        at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:838)
        at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
        at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at com.oracle.svm.hosted.code.CompileQueue.defaultParseFunction(CompileQueue.java:713)
        at com.oracle.svm.hosted.code.CompileQueue.doParse(CompileQueue.java:679)
        at com.oracle.svm.hosted.code.CompileQueue$ParseTask.run(CompileQueue.java:302)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedMethod(SharedGraphBuilderPhase.java:190)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedInvoke(SharedGraphBuilderPhase.java:156)
        at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1534)
        at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1509)
        at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5257)
        at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3416)
        ... 18 more
Error: Image build request failed with exit status 1
```

Looks the same to me, but nice experiment, took your comment most likely out of context :)

**Comment by woess** [comment]
Since you're building from source using mx, can you please check the version of graaljs (git commit or `mx sversions`)? `CreateSegmentIteratorNode.execute` has changed in RC16 (https://github.com/graalvm/graaljs/commit/71ee9723af19133f92a0f478f6660e3fcd0daffa) and it appears you don't have that change.

**Comment by hlolli** [comment]
@woess you are right, I am using graaljs revision rc15 with sha256 `0siryzvmj9h8zkyr0d3gy9fqgyxb9s5xs15rf7lnx9zh3ykq549y` but rc16 has sha256 `079ag8wjdfxd8z69i6di55q1d7a4c87a6091flwn6fd3jz0f3crf`. This seems to be totally my blunder, not to blame mx, since I patched it to prevent this check manually. Will test soon (the compilation takes a while and I'm busy with the other tasks atm).

**Comment by hlolli** [comment]
I can confirm that this was the problem, I wasn't using the right graaljs version
