### ISSUE TITLE
[native-image] SimpleDateFormatter regression

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#1195]
The following code will cause a failure during compilation:
    
```
public static void main(String[] args) throws Exception  {
        System.err.println("Hello, world");
        SimpleFormatter sf = new SimpleFormatter();
        System.err.println("SF = "+sf);
    }
```

The error is
```
Error: Error encountered while parsing java.util.logging.SimpleFormatter.<init>() 
Parsing context:
	parsing Hello2.main(Hello2.java:7)
	parsing app//com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:153)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

...
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.svm.core.util.VMError$HostedError: Error in @InjectAccessors handling of field java.util.logging.SimpleFormatter.format, accessors class com.oracle.svm.core.jdk.FormatAccessors: found no method named set or setFormat
	at parsing java.logging@11.0.2/java.util.logging.SimpleFormatter.<init>(SimpleFormatter.java:67)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2621)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:85)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3421)
...
Caused by: com.oracle.svm.core.util.VMError$HostedError: Error in @InjectAccessors handling of field java.util.logging.SimpleFormatter.format, accessors class com.oracle.svm.core.jdk.FormatAccessors: found no method named set or setFormat
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:66)
	at com.oracle.svm.hosted.phases.InjectedAccessorsPlugin.error(InjectedAccessorsPlugin.java:152)
	at com.oracle.svm.hosted.phases.InjectedAccessorsPlugin.handleField(InjectedAccessorsPlugin.java:89)
	at com.oracle.svm.hosted.phases.InjectedAccessorsPlugin.handleStoreField(InjectedAccessorsPlugin.java:57)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genPutField(BytecodeParser.java:4760)
...

```
(regression introduced by https://github.com/oracle/graal/commit/73544249ffd462d6b81ba10ac6233d914b7fb064)

This can be fixed with the following patch:

```
--- a/substratevm/src/com.oracle.svm.core.jdk9/src/com/oracle/svm/core/jdk/Target_java_util_logging_SimpleFormatter_JDK9OrLater.java
+++ b/substratevm/src/com.oracle.svm.core.jdk9/src/com/oracle/svm/core/jdk/Target_java_util_logging_SimpleFormatter_JDK9OrLater.java
@@ -54,6 +54,10 @@ class FormatAccessors {
         }
         return format;
     }
+    
+    public static void setFormat(java.util.logging.SimpleFormatter parent, String f) {
+        format = f;
+    }
 }

```

**Comment by cstancu** [comment]
This has been merged in 35a1819a37fc3df5c34072921850447010ed0581. Thanks!
