### ISSUE TITLE
ClassCastException with substitutions

### ISSUE THREAD

**Issue by gsmet** [oracle/graal#1200]
In Quarkus, we have the following substitutions:
```
    @TargetClass(ThreadLocalResettingRunnable.Resetter.class)
    @Substitute
    static final class Target_ThreadLocalResettingRunnable_Resetter {
        @Substitute
        static void run() {
            Target_java_lang_Thread thread = (Target_java_lang_Thread) (Object) Thread.currentThread();
            thread.threadLocals = null;
            thread.inheritableThreadLocals = null;
        }
    }

    @TargetClass(Thread.class)
    static final class Target_java_lang_Thread {
        @Alias
        Target_java_lang_ThreadLocal_ThreadLocalMap threadLocals;
        @Alias
        Target_java_lang_ThreadLocal_ThreadLocalMap inheritableThreadLocals;
    }
```

Starting recently (probably with rc15, it's still there in rc16), we started to see the following `ClassCastException`:
```
java.lang.ClassCastException: org.jboss.threads.JBossThread cannot be cast to java.lang.Thread
	at org.jboss.threads.ThreadLocalResettingRunnable$Resetter.run(Substitutions.java:47)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:34)
```
line 47 being `Target_java_lang_Thread thread = (Target_java_lang_Thread) (Object) Thread.currentThread();`.

Note that `JBossThread` is extending `Thread` so we suspect it has something to do with the substitutions and the aliases.

It's a rather critical issue as, in some cases, we have the error for each call to an API.

**Comment by cstancu** [comment]
Not sure what is going on here but we cast frequently between `java.lang.Thread` and `com.oracle.svm.core.thread.Target_java_lang_Thread`. We use the [`JavaThreads.toTarget(Thread)`](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/thread/JavaThreads.java#L146) utility method.

**Comment by dmlloyd** [comment]
I will try to change the cast from a "normal" cast to `Foo.class.cast()` and see if that helps.

**Comment by dmlloyd** [comment]
We tried using the `cast` method approach and it still fails.

**Comment by cstancu** [comment]
Can you provide a reproducible example so I can take a closer look?

**Comment by dmlloyd** [comment]
Got it into a minimal reproducer:

```java
package org.jboss.sample;

import com.oracle.svm.core.annotate.Alias;
import com.oracle.svm.core.annotate.TargetClass;

/**
 *
 */
public class CastingIssue {

    public static void main(String[] args) {
        System.out.println("Resetting thread locals, here we go!");
        Target_java_lang_Thread thread = Target_java_lang_Thread.class.cast(Thread.currentThread());
        thread.threadLocals = null;
        thread.inheritableThreadLocals = null;
        System.out.println("It worked!");
    }

    @TargetClass(Thread.class)
    static final class Target_java_lang_Thread {
        @Alias
        Target_java_lang_ThreadLocal_ThreadLocalMap threadLocals;
        @Alias
        Target_java_lang_ThreadLocal_ThreadLocalMap inheritableThreadLocals;
    }

    @TargetClass(className = "java.lang.ThreadLocal$ThreadLocalMap")
    static final class Target_java_lang_ThreadLocal_ThreadLocalMap {
    }

}
```

Compile into a JAR with this class as the main class, then:

```
$ native-image --no-server -jar out/artifacts/prove_casting_issue_jar/prove-casting-issue.jar 
[prove-casting-issue:16976]    classlist:   1,366.09 ms
[prove-casting-issue:16976]        (cap):     905.72 ms
[prove-casting-issue:16976]        setup:   2,043.36 ms
[prove-casting-issue:16976]   (typeflow):   2,404.49 ms
[prove-casting-issue:16976]    (objects):     852.09 ms
[prove-casting-issue:16976]   (features):     139.69 ms
[prove-casting-issue:16976]     analysis:   3,463.87 ms
[prove-casting-issue:16976]     (clinit):     100.87 ms
[prove-casting-issue:16976]     universe:     293.88 ms
[prove-casting-issue:16976]      (parse):     315.39 ms
[prove-casting-issue:16976]     (inline):   1,149.35 ms
[prove-casting-issue:16976]    (compile):   4,088.64 ms
[prove-casting-issue:16976]      compile:   5,815.75 ms
[prove-casting-issue:16976]        image:     319.29 ms
[prove-casting-issue:16976]        write:      94.53 ms
[prove-casting-issue:16976]      [total]:  13,520.39 ms
```
Finally:

```
$ ./prove-casting-issue 
Resetting thread locals, here we go!
Exception in thread "main" java.lang.ClassCastException
	at org.jboss.sample.CastingIssue.main(CastingIssue.java:31)
```

**Comment by dmlloyd** [comment]
If both `Thread.class` and `Target_java_lang_Thread.class` are printed, the output is:

```
class java.lang.Thread
class java.lang.Thread
```

**Comment by bobmcwhirter** [comment]
If you use `SubstrateUtil.cast(...)` you get the same error, but with a better/more-nonsensical message:

    Exception in thread "main" java.lang.ClassCastException: java.lang.Thread cannot be cast to java.lang.Thread

**Comment by dmlloyd** [comment]
I attempted to bisect this but couldn't find a GraalVM version that introduces the problem.  I went as far back as RC5 but I didn't have JVMCI versions for going any earlier than that.  I wonder if the problem might  be in JVMCI though?  Either that, or this *never* worked and somehow we didn't notice until now.

**Comment by dmlloyd** [comment]
Another weird thing, I tried to reverse the cast like this:

```java
        Thread foo = Thread.class.cast(new Target_java_lang_Thread());
```
and:

```java
    @TargetClass(Thread.class)
    static final class Target_java_lang_Thread {
        @Alias
        Target_java_lang_Thread() {}
    // ...
    }
```

And I got this unexpected error during `native-image` build:

```
$ native-image -H:+ReportExceptionStackTraces --no-server -jar out/artifacts/prove_casting_issue_jar/prove-casting-issue.jar 
[prove-casting-issue:84930]    classlist:   1,156.65 ms
[prove-casting-issue:84930]        (cap):     829.73 ms
[prove-casting-issue:84930]        setup:   2,057.61 ms
[prove-casting-issue:84930]     analysis:     859.68 ms
Error: Field java.lang.Thread.unsafeParkEvent is not present on type java.lang.Thread. Error encountered while analysing java.lang.Thread.init(java.lang.ThreadGroup, java.lang.Runnable, java.lang.String, long) 
Parsing context:
	parsing java.lang.Thread.<init>(Thread.java:448)
	parsing org.jboss.sample.CastingIssue.main(CastingIssue.java:33)
	parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:153)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

com.oracle.graal.pointsto.util.AnalysisError$FieldNotPresentError: Field java.lang.Thread.unsafeParkEvent is not present on type java.lang.Thread. Error encountered while analysing java.lang.Thread.init(java.lang.ThreadGroup, java.lang.Runnable, java.lang.String, long) 
Parsing context:
	parsing java.lang.Thread.<init>(Thread.java:448)
	parsing org.jboss.sample.CastingIssue.main(CastingIssue.java:33)
	parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:153)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

	at com.oracle.graal.pointsto.util.AnalysisError.fieldNotPresentError(AnalysisError.java:142)
	at com.oracle.graal.pointsto.flow.context.object.AnalysisObject.getInstanceFieldTypeStore(AnalysisObject.java:224)
	at com.oracle.graal.pointsto.flow.context.object.AnalysisObject.getInstanceFieldFlow(AnalysisObject.java:209)
	at com.oracle.graal.pointsto.flow.StoreFieldTypeFlow$StoreInstanceFieldTypeFlow.onObservedUpdate(StoreFieldTypeFlow.java:161)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:352)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:394)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:509)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
```

The thing is I didn't substitute the class, so I'm not sure what is going on here.

**Comment by dmlloyd** [comment]
Here's a more minimal reproducer:

```java
package org.jboss.sample;

import com.oracle.svm.core.annotate.TargetClass;

public class CastingIssue {

    public static void main(String[] args) {
        Replacement.class.cast(Thread.currentThread());
        System.out.println("It worked!");
    }

    @TargetClass(Thread.class)
    static final class Replacement {
    }
}
```
Constrast with this program which appears to work fine:
```java
package org.jboss.sample;

import com.oracle.svm.core.annotate.TargetClass;

public class CastingIssue {

    public static void main(String[] args) {
        Replacement.class.cast(new String(new byte[0]));
        System.out.println("It worked!");
    }

    @TargetClass(String.class)
    static final class Replacement {
    }
}
```

**Comment by cstancu** [comment]
This issue cannot be replicated anymore.
