### ISSUE TITLE
[Sulong] Compilation error for LLVMX86_Pmovmskb128

### ISSUE THREAD

**Issue by mrigger** [oracle/graal#1202]
Hi, when executing `armon-libart` from the cicro benchmarks with Sulong (RC16), I get the following error:

```
[truffle] opt fail         @find_child                                                 |Reason org.graalvm.compiler.code.SourceStackTraceBailoutException$1: too many loop explosion iterations - does the explosion not terminate for method SubstrateMethod<LLVMX86_ConversionNode$LLVMX86_Pmovmskb128.doIntrinsic>? 
org.graalvm.compiler.code.SourceStackTraceBailoutException$1: too many loop explosion iterations - does the explosion not terminate for method SubstrateMethod<LLVMX86_ConversionNode$LLVMX86_Pmovmskb128.doIntrinsic>?
Caused by: org.graalvm.compiler.core.common.PermanentBailoutException: too many loop explosion iterations - does the explosion not terminate for method SubstrateMethod<LLVMX86_ConversionNode$LLVMX86_Pmovmskb128.doIntrinsic>?
	at org.graalvm.compiler.replacements.PEGraphDecoder.tooManyLoopExplosionIterations(PEGraphDecoder.java:671)
	at org.graalvm.compiler.replacements.PEGraphDecoder.checkLoopExplosionIteration(PEGraphDecoder.java:665)
	at org.graalvm.compiler.nodes.GraphDecoder.handleLoopExplosionEnd(GraphDecoder.java:755)
	at org.graalvm.compiler.nodes.GraphDecoder.processNextNode(GraphDecoder.java:553)
	at org.graalvm.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:415)
	at org.graalvm.compiler.replacements.PEGraphDecoder.decode(PEGraphDecoder.java:619)
	at org.graalvm.compiler.truffle.compiler.PartialEvaluator.doGraphPE(PartialEvaluator.java:474)
	at com.oracle.svm.truffle.api.SubstratePartialEvaluator.doGraphPE(SubstratePartialEvaluator.java:81)
	at org.graalvm.compiler.truffle.compiler.PartialEvaluator.fastPartialEvaluation(PartialEvaluator.java:512)
	at org.graalvm.compiler.truffle.compiler.PartialEvaluator.createGraph(PartialEvaluator.java:242)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compileAST(TruffleCompilerImpl.java:438)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:621)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:568)
	at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:177)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.doCompile(TruffleCompilerImpl.java:280)
	at org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.doCompile(GraalTruffleRuntime.java:687)
	at org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.doCompile(GraalTruffleRuntime.java:711)
	at org.graalvm.compiler.truffle.runtime.BackgroundCompileQueue$Request.run(BackgroundCompileQueue.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.graalvm.compiler.truffle.runtime.BackgroundCompileQueue$TruffleCompilerThreadFactory$1.run(BackgroundCompileQueue.java:163)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)


```

**Comment by zapster** [comment]
Hi Manuel! Thanks for the report. A fixed has already been merged to master (27e7276341). Disclosure: the issue was in fact discovered by running the cicro benchmarks internally.
