### ISSUE TITLE
[native-image] despite native-image-agent JNI UnsatisfiedLinkError with javax.sound.midi

### ISSUE THREAD

**Issue by tarilabs** [oracle/graal#1205]
Hi, I am using 1.0.0-rc16

I have a simplified reproducer by means of a very simple app[1] just for listening to midi keyboard note press, I believe this is using JNI because I am using package `javax.sound.midi` so as suggested from documentation, I run first the reproducer with:
```
java -agentlib:native-image-agent=config-output-dir=conf/ -jar target/test20190427midionoff-0.0.1-SNAPSHOT.jar
```
and I can use the application normally; display midi devices, I connect to a midi device and it print out keyboard note press.

However most json files are empty[2] especially jni-config.json. 
resource-config.json gets:
```
{
  "resources":[{"pattern":"META-INF/services/javax.sound.midi.spi.MidiDeviceProvider"}]
}
```
and reflect-config.json gets:
```
[
{
  "name":"sun.misc.Unsafe",
  "fields":[{"name":"theUnsafe"}]
}
]
```

Then I compile with
```
native-image --static -H:ConfigurationFileDirectories=conf/ -jar target/test20190427midionoff-0.0.1-SNAPSHOT.jar
```

however as I run the produced binary executable, I get:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.sun.media.sound.MidiOutDeviceProvider.nGetNumDevices()I [symbol: Java_com_sun_media_sound_MidiOutDeviceProvider_nGetNumDevices or Java_com_sun_media_sound_MidiOutDeviceProvider_nGetNumDevices__]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
	at com.sun.media.sound.MidiOutDeviceProvider.nGetNumDevices(MidiOutDeviceProvider.java)
	at com.sun.media.sound.MidiOutDeviceProvider.getNumDevices(MidiOutDeviceProvider.java:85)
	at com.sun.media.sound.AbstractMidiDeviceProvider.readDeviceInfos(AbstractMidiDeviceProvider.java:69)
	at com.sun.media.sound.AbstractMidiDeviceProvider.getDeviceInfo(AbstractMidiDeviceProvider.java:122)
	at javax.sound.midi.MidiSystem.getMidiDeviceInfo(MidiSystem.java:195)
	at net.tarilabs.test20190427midionoff.App.main(App.java:16)
```

line 16 is indeed the first statement in the main method.

Am I missing something, or is there some bug?
Can you kindly advise, please?

Thanks in advance,
MM

[1] 
```
import java.util.Scanner;

import javax.sound.midi.MidiDevice;
import javax.sound.midi.MidiDevice.Info;
import javax.sound.midi.MidiMessage;
import javax.sound.midi.MidiSystem;
import javax.sound.midi.Receiver;
import javax.sound.midi.ShortMessage;
import javax.sound.midi.Transmitter;

public class App {

    public static void main(String[] args) throws Exception {
        Info[] devs = MidiSystem.getMidiDeviceInfo();
        for (int i = 0; i < devs.length; i++) {
            MidiDevice d = MidiSystem.getMidiDevice(devs[i]);
            printInfo(i, d);
        }
        System.out.print("Index? > ");
        Scanner scanner = new Scanner(System.in);
        int idx = Integer.parseInt(scanner.nextLine());
        MidiDevice device = MidiSystem.getMidiDevice(devs[idx]);
        printInfo(idx, device);
        device.open();
        Transmitter transmitter = device.getTransmitter();
        transmitter.setReceiver(new ConsoleReceiver());
        scanner.nextLine();
        device.close();
    }

    private static void printInfo(int idx, MidiDevice d) {
        Info i = d.getDeviceInfo();
        System.out.println(String.format("%2s %2s %3s %s %s %s %s", idx, d.getMaxTransmitters() != 0 ? "IN" : "", d.getMaxReceivers() != 0 ? "OUT" : "", i.getName(), i.getVendor(), i.getVersion(), i.getDescription()));
    }

    private static final class ConsoleReceiver implements Receiver {

        private static final String[] KEYS = {"Do", "Do#", "Re", "Re#", "Mi", "Fa", "Fa#", "Sol", "Sol#", "La", "La#", "Si"};

        @Override
        public void send(MidiMessage message, long timeStamp) {
            if (message instanceof ShortMessage) {
                ShortMessage s = (ShortMessage) message;
                switch (s.getCommand()) {
                    case 0x80:
                        System.out.print("Off ");
                        break;
                    case 0x90:
                        System.out.print(" On ");
                        break;
                }
                int d1 = s.getData1();
                System.out.print(d1 > 127 ? "?" : KEYS[d1 % 12] + (d1 / 12 - 1));
                System.out.println(" vel: " + s.getData2());
            } else {
                System.out.println(message);
            }
        }

        @Override
        public void close() {
            // nothing (yet).
        }
    }
}
```
[2] https://github.com/tarilabs/test20190427midionoff/tree/d71677325ad4329aad0eea480d73947969aace10/conf

**Comment by peter-hofer** [comment]
Hi Matteo, thank you for your patience. When your Java application (or a library) uses native code via JNI, that doesn't necessarily mean that the native code in turn needs access to the Java application, which is what the JNI configuration file specifies. So it can be perfectly fine if the agent doesn't record much in the files.

In your case, the problem is with the native libraries for MIDI support. Behind the scenes, the `com.sun.media.sound.Platform` class uses `System.loadLibrary()` to load required native libraries for sound and media that are part of the JDK. Unfortunately, the class does this in its static initializer, which in this case gets executed during the image build and also cannot be delayed to runtime with `native-image --initialize-at-run-time=...`. Therefore, the libraries are loaded only at build time, but not again at runtime, and you get an `UnsatisfiedLinkError`.

Since javax.sound.midi is part of the JDK, a proper solution would involve explicit support for those classes in `native-image` like we have for various other JDK classes. The fact that javax.sound.midi seemingly involves several native libraries that are entangled with the JVM (`libjvm.so`) makes that more complex, and I don't think that we currently have concrete plans to work on that. However, given that we are currently working on reusing more JDK native code via JNI in future releases, that might become a possibility.

As a less-than-pretty workaround, I was able to manually reset and reinitialize the `Platform` class by adding these lines to your `main` method.
```
        Field loadedLibs = Class.forName("com.sun.media.sound.Platform").getDeclaredField("loadedLibs");
        loadedLibs.setAccessible(true);
        loadedLibs.setInt(null, 0);
        Method loadLibraries = Class.forName("com.sun.media.sound.Platform").getDeclaredMethod("loadLibraries");
        loadLibraries.setAccessible(true);
        loadLibraries.invoke(null);
        Method readProperties = Class.forName("com.sun.media.sound.Platform").getDeclaredMethod("readProperties");
        readProperties.setAccessible(true);
        readProperties.invoke(null);
```
The required native libraries are part of the JDK, so those need to be present at runtime and you need to point your program to the directories that contain them when you run it:
```
env LD_LIBRARY_PATH=/path/to/jdk/jre/lib/amd64/server/ ./app -Djava.library.path=/path/to/jdk/jre/lib/amd64/
```
I don't have any MIDI devices to test with, so this might not actually make the program work as expected.

**Comment by tarilabs** [comment]
Thank you so much @peter-hofer for the feedback; I've made some progress but now stuck again.

I have modified the program as follows, following your feedback

<details>

```
package net.tarilabs.test20190427midionoff;

import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.Scanner;

import javax.sound.midi.MidiDevice;
import javax.sound.midi.MidiDevice.Info;
import javax.sound.midi.MidiMessage;
import javax.sound.midi.MidiSystem;
import javax.sound.midi.Receiver;
import javax.sound.midi.ShortMessage;
import javax.sound.midi.Transmitter;

public class App {

    public static void main(String[] args) throws Exception {
        graalvmniworkaround();
        Info[] devs = MidiSystem.getMidiDeviceInfo();
        for (int i = 0; i < devs.length; i++) {
            MidiDevice d = MidiSystem.getMidiDevice(devs[i]);
            printInfo(i, d);
        }
        System.out.print("Index? > ");
        Scanner scanner = new Scanner(System.in);
        int idx = Integer.parseInt(scanner.nextLine());
        MidiDevice device = MidiSystem.getMidiDevice(devs[idx]);
        printInfo(idx, device);
        device.open();
        Transmitter transmitter = device.getTransmitter();
        transmitter.setReceiver(new ConsoleReceiver());
        scanner.nextLine();
        device.close();
    }

    /**
     * https://github.com/oracle/graal/issues/1205
     */
    private static void graalvmniworkaround() throws Exception {
        Field loadedLibs = Class.forName("com.sun.media.sound.Platform").getDeclaredField("loadedLibs");
        loadedLibs.setAccessible(true);
        loadedLibs.setInt(null, 0);
        Method loadLibraries = Class.forName("com.sun.media.sound.Platform").getDeclaredMethod("loadLibraries");
        loadLibraries.setAccessible(true);
        loadLibraries.invoke(null);
        Method readProperties = Class.forName("com.sun.media.sound.Platform").getDeclaredMethod("readProperties");
        readProperties.setAccessible(true);
        readProperties.invoke(null);
    }

    private static void printInfo(int idx, MidiDevice d) {
        Info i = d.getDeviceInfo();
        System.out.println(String.format("%2s %2s %3s %s %s %s %s", idx, d.getMaxTransmitters() != 0 ? "IN" : "", d.getMaxReceivers() != 0 ? "OUT" : "", i.getName(), i.getVendor(), i.getVersion(), i.getDescription()));
    }

    private static final class ConsoleReceiver implements Receiver {

        private static final String[] KEYS = {"Do", "Do#", "Re", "Re#", "Mi", "Fa", "Fa#", "Sol", "Sol#", "La", "La#", "Si"};

        @Override
        public void send(MidiMessage message, long timeStamp) {
            if (message instanceof ShortMessage) {
                ShortMessage s = (ShortMessage) message;
                switch (s.getCommand()) {
                    case 0x80:
                        System.out.print("Off ");
                        break;
                    case 0x90:
                        System.out.print(" On ");
                        break;
                }
                int d1 = s.getData1();
                System.out.print(d1 > 127 ? "?" : KEYS[d1 % 12] + (d1 / 12 - 1));
                System.out.println(" vel: " + s.getData2());
            } else {
                System.out.println(message);
            }
        }

        @Override
        public void close() {
            // nothing (yet).
        }
    }
}
```

</details>


Also as per your feedback, I'm now doing:
```
export LD_LIBRARY_PATH=$JAVA_HOME/jre/lib/amd64/server
./test20190427midionoff-0.0.1-SNAPSHOT -Djava.library.path=$JAVA_HOME/jre/lib/amd64
```
where in my case:
```
$ echo $JAVA_HOME
/home/mmortari/.jabba/jdk/graalvm@19.0.0
```

The program now successfully lists the available MIDI devices, however:
```
Index? > 3
 3    OUT V103 [hw:1,0,1] ALSA (http://www.alsa-project.org) 5.0.7-200.fc29.x86_64 iCON iKeyboard 6X V1.03, USB MIDI, iCON iKeyboard 6X V1.03
Exception in thread "main" java.lang.NoClassDefFoundError: Ljavax/sound/midi/MidiUnavailableException;
	at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:327)
	at com.sun.media.sound.MidiOutDevice.nOpen(MidiOutDevice.java)
	at com.sun.media.sound.MidiOutDevice.implOpen(MidiOutDevice.java:54)
	at com.sun.media.sound.AbstractMidiDevice.doOpen(AbstractMidiDevice.java:154)
	at com.sun.media.sound.AbstractMidiDevice.open(AbstractMidiDevice.java:118)
	at net.tarilabs.test20190427midionoff.App.main(App.java:29)
```

To try address this NoClassDefFoundError of MidiUnavailableException, I have done some research on the documentation and somehow connected github issues and made sure of the following.

I have modified `reflect-config.json` as follows:
```
[
{
  "name":"com.sun.media.sound.Platform",
  "fields":[{"name":"loadedLibs"}],
  "methods":[
    {"name":"loadLibraries","parameterTypes":[] }, 
    {"name":"readProperties","parameterTypes":[] }
  ]
},
{ "name":"javax.sound.midi.MidiUnavailableException",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredClasses" : true,
    "allPublicClasses" : true
},
{
  "name":"sun.misc.Unsafe",
  "fields":[{"name":"theUnsafe"}]
}
]
```

I have modified `jni-config.json` as follows:
```
[
{ "name":"javax.sound.midi.MidiUnavailableException",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredClasses" : true,
    "allPublicClasses" : true
},
{
    "name" : "Ljavax/sound/midi/MidiUnavailableException;",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredClasses" : true,
    "allPublicClasses" : true
}
]
```
(as not fully sure what should be the `name` format in this latter .json file, by also looking at this comment on another question: https://github.com/oracle/graal/issues/1185#issuecomment-485914458)

However I still get the stacktrace mentioned above
```
Exception in thread "main" java.lang.NoClassDefFoundError: Ljavax/sound/midi/MidiUnavailableException;
	at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:327)
	at com.sun.media.sound.MidiOutDevice.nOpen(MidiOutDevice.java)
	at com.sun.media.sound.MidiOutDevice.implOpen(MidiOutDevice.java:54)
	at com.sun.media.sound.AbstractMidiDevice.doOpen(AbstractMidiDevice.java:154)
	at com.sun.media.sound.AbstractMidiDevice.open(AbstractMidiDevice.java:118)
	at net.tarilabs.test20190427midionoff.App.main(App.java:29)

```

What am I missing, and/or doing wrong, please?

If I can support better in providing details/code/feedback don't hesitate to let me know, I'd be glad to provide as much information impossible in order to resolve the issue -my end goal for this exercise is to be able to read midi signals of note on/off

Thanks again for your feedback so far! GraalVM is awesome!!
Looking forward hearing from you in order to resolve the problem described

**Comment by peter-hofer** [comment]
Thanks for the feedback! The entry with `"javax.sound.midi.MidiUnavailableException"` should work, but I think the syntax with slashes is not valid and should actually cause a build error. Can you please check that the configuration file is provided on the command line (also try with `-H:JNIConfigurationFiles`, `-H:ReflectionConfigurationFiles` directly) and that the build completes successfully?

**Comment by tarilabs** [comment]
@peter-hofer Thank you SO MUCH for the suggestion to try with the other options.
When I did compile it with :
```
native-image --static -H:ConfigurationFileDirectories=conf/ -jar target/test20190427midionoff-0.0.1-SNAPSHOT.jar
```

I experienced the problem as above.

Following your suggestions, I tried to re-compile it with
```
native-image --static -H:JNIConfigurationFiles=conf/jni-config.json -H:ReflectionConfigurationFiles=conf/reflect-config.json -jar target/test20190427midionoff-0.0.1-SNAPSHOT.jar
```

and the error changed!
Which as always in these situation is progress!! :)

I had since updated my files as:
jni-config.json
```
[
{ "name":"javax.sound.midi.MidiUnavailableException",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredClasses" : true,
    "allPublicClasses" : true
},
{ "name":"com.sun.media.sound.MidiInDevice",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredClasses" : true,
    "allPublicClasses" : true
}	
]
```
and reflect-config.json : 
```
[
{
  "name":"com.sun.media.sound.Platform",
  "fields":[{"name":"loadedLibs"}],
  "methods":[
    {"name":"loadLibraries","parameterTypes":[] }, 
    {"name":"readProperties","parameterTypes":[] }
  ]
},
{ "name":"javax.sound.midi.MidiUnavailableException",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredClasses" : true,
    "allPublicClasses" : true
},
{ "name":"com.sun.media.sound.MidiInDevice",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredClasses" : true,
    "allPublicClasses" : true
},
{
  "name":"sun.misc.Unsafe",
  "fields":[{"name":"theUnsafe"}]
}
]
```
and with that, I have achieved this goal to read notes on/off
![image](https://user-images.githubusercontent.com/1699252/58819848-65be4a80-8631-11e9-8664-0d7608e3bf8a.png)

I wonder why when compiling with `-H:ConfigurationFileDirectories=conf/` option did not followed the contents of the files, nor emitting any warning/error?
With the separate files options seems to be working much better now.

**Comment by peter-hofer** [comment]
That's great!
Indeed it shouldn't make a difference whether you specify `-H:ConfigurationFileDirectories=dir` or `-H:-H:JNIConfigurationFiles=dir/jni-config.json`. I'll try to reproduce this problem locally.

**Comment by tarilabs** [comment]
@peter-hofer I might be wrong, but I sometimes I was also under the impression the content from those files was "cached" between native image builds.. I don't even know if this is actually/possible or part of some internal behaviour, I just wanted to mention in case it helps reproducing it. Naturally I did make sure the conf .json files on the filesystem were saved correctly
