### ISSUE TITLE
Liberty startup issue: NumberFormatException in com.ibm.ws.kernel.service.util.JavaInfo when running on GraalVM 1.0 RC16

### ISSUE THREAD

**Issue by MaartenSmeets** [oracle/graal#1214]
I also created this issue on https://github.com/OpenLiberty/open-liberty/issues/7372. Not sure where a fix should be implemented (Open Liberty or GraalVM).

When running JAR generated with mvn clean package from https://github.com/MaartenSmeets/jvmperformance/tree/master/microservicetestcode/MicroProfile
 (using net.wasdev.wlp.maven.parent:liberty-maven-app-parent:2.6.4,
net.wasdev.wlp.maven.parent:liberty-maven-plugin:2.6.4,
io.openliberty:openliberty-runtime:19.0.0.4)

on GraalVM 1.0 RC16 using the following Dockerfile

```
FROM oracle/graalvm-ce:1.0.0-rc16
VOLUME /tmp
ARG JAR_FILE
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-XX:+UnlockExperimentalVMOptions","-Xmx2G","-Xms2G","-jar","/app.jar"]
```

with
```
docker build -t testimage -f Dockerfile --build-arg JAR_FILE=target/mp-rest-service.jar .
docker run -d -p 8080:8080 testimage
```

My application will not start and I get the following error (docker logs testimage).

```
[ERROR   ] CWWKE0701E: FrameworkEvent ERROR org.osgi.framework.BundleException: Exception in com.ibm.ws.config.internal.WSConfigActivator.start() of bundle com.ibm.ws.config.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:835)
	at [internal classes]
Caused by: java.lang.ExceptionInInitializerError
	at com.ibm.ws.config.admin.internal.UpdateQueue.<init>(UpdateQueue.java:152)
	... 1 more
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.ibm.ws.kernel.service.util.JavaInfo.<init>(JavaInfo.java:87)
	... 1 more
```

Open Liberty with the same code and same base Java version (8u202) does not cause issues on AdoptOpenJDK, OpenJ9 and Oracle JDK. I'm unsure if this is an issue in the Java version number parsing in the Open Liberty code or in GraalVM for providing a wrong Java version.

**Comment by MaartenSmeets** [comment]
The issue has been resolved on the Liberty side in release 19.0.0.5. See https://github.com/OpenLiberty/open-liberty/issues/7372#issuecomment-487969687
