### ISSUE TITLE
"No instances are allowed in the image heap" for Micronaut and Security

### ISSUE THREAD

**Issue by ilopmar** [oracle/graal#1215]
It is now not possible to build a Micronaut native image with Security after this change https://github.com/oracle/graal/commit/b20dead4f4f0527dae948767992c82d4f43837f6 was merged in master last week.

Keep in mind that the application is using the suggested options: `--initialize-at-build-time=ch.qos.logback,com.fasterxml.jackson,fresh.graal,io.micronaut,io.netty,io.reactivex,org.reactivestreams,org.slf4j,org.yaml.snakeyaml,javax` and that this works properly with RC16.

To reproduce the issue:

- `git clone https://github.com/micronaut-graal-tests/micronaut-security-jwt-graal`
- `cd micronaut-security-jwt-graal`
- Use graal from master branch (currently rc18.dev)
- `./build-native-image.sh`

The image generation fails:
```
Warning: Using a deprecated option --rerun-class-initialization-at-runtime. Currently there is no replacement for this option. Try using --initialize-at-run-time or use the non-API option -H:ClassInitialization directly.
Warning: Using a deprecated option --delay-class-initialization-to-runtime. Use --initialize-at-run-time.
Warning: Using a deprecated option --delay-class-initialization-to-runtime. Use --initialize-at-run-time.
[security-jwt-graal:24484]    classlist:   7,792.10 ms
[security-jwt-graal:24484]        (cap):   2,163.07 ms
[security-jwt-graal:24484]        setup:   5,841.61 ms
[security-jwt-graal:24484]     analysis:  92,927.24 ms
Error: Unsupported features in 2 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances are allowed in the image heap for a class that is initialized or reinitialized at image runtime: com.nimbusds.jose.jwk.KeyType
Trace: 
	at parsing io.micronaut.security.token.jwt.signature.jwks.JwksSignatureConfigurationProperties.<init>(JwksSignatureConfigurationProperties.java:43)
Call path from entry point to io.micronaut.security.token.jwt.signature.jwks.JwksSignatureConfigurationProperties.<init>(): 
	at io.micronaut.security.token.jwt.signature.jwks.JwksSignatureConfigurationProperties.<init>(JwksSignatureConfigurationProperties.java:31)
	at io.micronaut.security.token.jwt.signature.jwks.$JwksSignatureConfigurationPropertiesDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1501)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2185)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:1783)
	at io.micronaut.context.DefaultBeanContext.lambda$null$43(DefaultBeanContext.java:1634)
	at io.micronaut.context.DefaultBeanContext$$Lambda$541/1606207531.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances are allowed in the image heap for a class that is initialized or reinitialized at image runtime: net.minidev.json.JSONObject
Trace: 
	at parsing io.micronaut.security.token.jwt.endpoints.KeysController.lambda$keys$0(KeysController.java:68)
Call path from entry point to io.micronaut.security.token.jwt.endpoints.KeysController.lambda$keys$0(ObjectMapper): 
	at io.micronaut.security.token.jwt.endpoints.KeysController.lambda$keys$0(KeysController.java:68)
	at io.micronaut.security.token.jwt.endpoints.KeysController$$Lambda$1055/983443857.apply(Unknown Source)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
	at io.reactivex.internal.operators.flowable.FlowableReduceSeedSingle$ReduceSeedObserver.onComplete(FlowableReduceSeedSingle.java:110)
	at io.micronaut.http.client.filters.ClientServerRequestTracingPublisher$1$$Lambda$1723/1997286439.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

**Comment by vjovanov** [comment]
Addition of this flag fixes the issue: `--initialize-at-build-time=com.nimbusds.jose.jwk.KeyType,net.minidev.json.JSONObject`.

These got initialized through: `io.micronaut.security.token.jwt.signature.jwks.JwksSignatureConfigurationProperties` which is eagerly initialized. Again, adding a stack trace here will help in the future.
