### ISSUE TITLE
GraalError: plugin graph not found (numberOfLeadingZeros)

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#1224]
### Environment
GraalVM CE 1.0.0 RC16 on Linux

### Error message
```
Thread[System-3,5,main]: Compilation of java.util.concurrent.ConcurrentHashMap.putVal(Object, Object, boolean) failed:
org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: org.graalvm.compiler.debug.GraalError: should not reach here: plugin graph not found: MethodSubstitutionPlugin[org.graalvm.compiler.replacements.IntegerSubstitutions.numberOfLeadingZeros(int)] with INLINE_AFTER_PARSING
	at parsing java.util.concurrent.ConcurrentHashMap.resizeStamp(ConcurrentHashMap.java:2217)
	at org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2621)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3421)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3223)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:944)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:838)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at org.graalvm.compiler.java.GraphBuilderPhase.run(GraphBuilderPhase.java:55)
	at org.graalvm.compiler.java.GraphBuilderPhase.run(GraphBuilderPhase.java:40)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:212)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.phases.common.inlining.info.elem.InlineableGraph.parseBytecodes(InlineableGraph.java:201)
	at org.graalvm.compiler.phases.common.inlining.info.elem.InlineableGraph.<init>(InlineableGraph.java:74)
	at org.graalvm.compiler.phases.common.inlining.info.elem.Inlineable.getInlineableElement(Inlineable.java:38)
	at org.graalvm.compiler.phases.common.inlining.info.AbstractInlineInfo.populateInlinableElements(AbstractInlineInfo.java:69)
	at org.graalvm.compiler.phases.common.inlining.walker.InliningData.processNextInvoke(InliningData.java:506)
	at org.graalvm.compiler.phases.common.inlining.walker.InliningData.moveForward(InliningData.java:735)
	at org.graalvm.compiler.phases.common.inlining.InliningPhase.run(InliningPhase.java:100)
	at org.graalvm.compiler.phases.common.inlining.InliningPhase.run(InliningPhase.java:40)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:212)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:220)
	at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:144)
	at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:129)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileHelper(HotSpotGraalCompiler.java:212)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:226)
	at org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:186)
	at org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:96)
	at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:177)
	at org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:342)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:142)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:108)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:663)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST_Nonvirtual:Ljdk_vm_ci_hotspot_HotSpotJVMCIRuntime_2_0002ecompileMethod_00028Ljdk_vm_ci_hotspot_HotSpotResolvedJavaMethod_2IJI_00029Ljdk_vm_ci_hotspot_HotSpotCompilationRequestResult_2(JNIJavaCallWrappers.java:0)
Caused by: org.graalvm.compiler.debug.GraalError: should not reach here: plugin graph not found: MethodSubstitutionPlugin[org.graalvm.compiler.replacements.IntegerSubstitutions.numberOfLeadingZeros(int)] with INLINE_AFTER_PARSING
	at org.graalvm.compiler.hotspot.SymbolicSnippetEncoder$EncodedSnippets.getMethodSubstitutionGraph(SymbolicSnippetEncoder.java:289)
	at org.graalvm.compiler.hotspot.HotSpotReplacementsImpl.getMethodSubstitution(HotSpotReplacementsImpl.java:245)
	at org.graalvm.compiler.nodes.graphbuilderconf.MethodSubstitutionPlugin.execute(MethodSubstitutionPlugin.java:195)
	at org.graalvm.compiler.java.BytecodeParser.tryInvocationPlugin(BytecodeParser.java:2243)
	at org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1767)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1529)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1509)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5257)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3416)
	... 37 more
To disable compilation failure notifications, set CompilationFailureAction to Silent (e.g., -Dgraal.CompilationFailureAction=Silent).
To print a message for a compilation failure without retrying the compilation, set CompilationFailureAction to Print (e.g., -Dgraal.CompilationFailureAction=Print).
Retrying compilation of java.util.concurrent.ConcurrentHashMap.putVal(Object, Object, boolean)
Could not connect to the IGV on 127.0.0.1:4445. Dumping IGV graphs in ../graal_diagnostics_20264/java.util.concurrent.ConcurrentHashMap.putVal(Object,_Object,_boolean)
Thread[System-3,5,main]: Compilation of java.util.concurrent.ConcurrentHashMap.transfer(ConcurrentHashMap$Node[], ConcurrentHashMap$Node[]) failed:
org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: org.graalvm.compiler.debug.GraalError: should not reach here: plugin graph not found: MethodSubstitutionPlugin[org.graalvm.compiler.replacements.IntegerSubstitutions.numberOfLeadingZeros(int)] with INLINE_AFTER_PARSING
	at parsing java.util.concurrent.ConcurrentHashMap.resizeStamp(ConcurrentHashMap.java:2217)
	at org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2621)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3421)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3223)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:944)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:838)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at org.graalvm.compiler.java.GraphBuilderPhase.run(GraphBuilderPhase.java:55)
	at org.graalvm.compiler.java.GraphBuilderPhase.run(GraphBuilderPhase.java:40)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:212)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.phases.common.inlining.info.elem.InlineableGraph.parseBytecodes(InlineableGraph.java:201)
	at org.graalvm.compiler.phases.common.inlining.info.elem.InlineableGraph.<init>(InlineableGraph.java:74)
	at org.graalvm.compiler.phases.common.inlining.info.elem.Inlineable.getInlineableElement(Inlineable.java:38)
	at org.graalvm.compiler.phases.common.inlining.info.AbstractInlineInfo.populateInlinableElements(AbstractInlineInfo.java:69)
	at org.graalvm.compiler.phases.common.inlining.walker.InliningData.processNextInvoke(InliningData.java:506)
	at org.graalvm.compiler.phases.common.inlining.walker.InliningData.moveForward(InliningData.java:735)
	at org.graalvm.compiler.phases.common.inlining.InliningPhase.run(InliningPhase.java:100)
	at org.graalvm.compiler.phases.common.inlining.InliningPhase.run(InliningPhase.java:40)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:212)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:220)
	at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:144)
	at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:129)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileHelper(HotSpotGraalCompiler.java:212)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:226)
	at org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:186)
	at org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:96)
	at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:177)
	at org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:342)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:142)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:108)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:663)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST_Nonvirtual:Ljdk_vm_ci_hotspot_HotSpotJVMCIRuntime_2_0002ecompileMethod_00028Ljdk_vm_ci_hotspot_HotSpotResolvedJavaMethod_2IJI_00029Ljdk_vm_ci_hotspot_HotSpotCompilationRequestResult_2(JNIJavaCallWrappers.java:0)
Caused by: org.graalvm.compiler.debug.GraalError: should not reach here: plugin graph not found: MethodSubstitutionPlugin[org.graalvm.compiler.replacements.IntegerSubstitutions.numberOfLeadingZeros(int)] with INLINE_AFTER_PARSING
	at org.graalvm.compiler.hotspot.SymbolicSnippetEncoder$EncodedSnippets.getMethodSubstitutionGraph(SymbolicSnippetEncoder.java:289)
	at org.graalvm.compiler.hotspot.HotSpotReplacementsImpl.getMethodSubstitution(HotSpotReplacementsImpl.java:245)
	at org.graalvm.compiler.nodes.graphbuilderconf.MethodSubstitutionPlugin.execute(MethodSubstitutionPlugin.java:195)
	at org.graalvm.compiler.java.BytecodeParser.tryInvocationPlugin(BytecodeParser.java:2243)
	at org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1767)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1529)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1509)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5257)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3416)
	... 37 more
To disable compilation failure notifications, set CompilationFailureAction to Silent (e.g., -Dgraal.CompilationFailureAction=Silent).
To print a message for a compilation failure without retrying the compilation, set CompilationFailureAction to Print (e.g., -Dgraal.CompilationFailureAction=Print).
Retrying compilation of java.util.concurrent.ConcurrentHashMap.transfer(ConcurrentHashMap$Node[], ConcurrentHashMap$Node[])
Could not connect to the IGV on 127.0.0.1:4445. Dumping IGV graphs in ../graal_diagnostics_20264/java.util.concurrent.ConcurrentHashMap.transfer(ConcurrentHashMap$Node[],_ConcurrentHashMap$Node[])
```

### Dump
[graal_diagnostics_20264.zip](https://github.com/oracle/graal/files/3136078/graal_diagnostics_20264.zip)

**Comment by dougxc** [comment]
@tkrodriguez this looks like a case of a method substitution not being included because our build system says it's not needed (https://github.com/oracle/graal/blob/b4b403e30a2f095084ac9f7f5d4f0442661b612c/compiler/src/org.graalvm.compiler.replacements.amd64/src/org/graalvm/compiler/replacements/amd64/AMD64GraphBuilderPlugins.java#L115). I think you fixed this for a number of other conditional method substitutions such that they are always included in libgraal just in case they're needed.

**Comment by fniephaus** [comment]
Thanks for the info! Everything seems to work fine when running with `-XX:-UseJVMCINativeLibrary` as a workaround.

**Comment by tkrodriguez** [comment]
Hmm.  This is an interesting version of the problem with missing method substitutions.  Most of our method substitutions are for features which are enabled by processor features so you if you on a recent CPU you get all of them.  This particular one has a fallback for the case where the you don't have a CPU feature so it gets left out.  It's easy enough to fix in a localized way.
