### ISSUE TITLE
[native-image] native-image (in server mode) freezes when run on jar file (graalvm-ce-rc16)

### ISSUE THREAD

**Issue by neomatrix369** [oracle/graal#1252]
Environment: 
```
Darwin manis-MacBook.local 17.7.0 Darwin Kernel Version 17.7.0: Wed Feb 27 00:43:23 PST 2019; root:xnu-4570.71.35~1/RELEASE_X86_64 x86_64
```

```
➜  streams git:(master) ✗ $GRAALCE_HOME/bin/java -version
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (build 1.8.0_202-20190206132754.buildslave.jdk8u-src-tar--b08)
OpenJDK GraalVM CE 1.0.0-rc16 (build 25.202-b08-jvmci-0.59, mixed mode)
```

See https://github.com/graalvm/graalvm-demos/tree/master/native-netty-plot, when running the below:

```
 $GRAALCE_HOME/bin/native-image --verbose -jar target/netty-plot-0.1-jar-with-dependencies.jar
```
we get

```
Apply jar:file:///Users/path/to/git-repos/hands-on-workshops/devoxxuk-2019-graalvm-session/graalvm-demos/native-netty-plot/target/netty-plot-0.1-jar-with-dependencies.jar!/META-INF/native-image/com.oracle.substratevm/netty-plot/native-image.properties
<does not respond forever>
```
Why? Because process is waiting in memory!!! See below:

```
Sampling process 9501 for 3 seconds with 1 millisecond of run time between samples
Sampling completed, processing symbols...
Analysis of sampling native-image (pid 9501) every 1 millisecond
Process:         native-image [9501]
Path:            /opt/graalvm-ce-1.0.0-rc16/Contents/Home/jre/lib/svm/bin/native-image
Load Address:    0x10b494000
Identifier:      native-image
Version:         0
Code Type:       X86-64
Parent Process:  zsh [6245]

Date/Time:       2019-05-09 20:25:27.464 +0100
Launch Time:     2019-05-09 20:24:00.481 +0100
OS Version:      Mac OS X 10.13.6 (17G6030)
Report Version:  7
Analysis Tool:   /usr/bin/sample

Physical footprint:         3560K
Physical footprint (peak):  3560K
----

Call graph:
    2669 Thread_59021   DispatchQueue_1: com.apple.main-thread  (serial)
    + 2669 PosixJavaNetClose$$Lambda$ca483cb3ef31b32ec470365988c52031e45d2fd3_getAsInt_5bf829efad7fcc93ff5d4441d36991870b04238c  (in native-image) + 111  [0x10b4ea7af]
    +   2669 __recvfrom  (in libsystem_kernel.dylib) + 10  [0x7fff52a18c32]
    2669 Thread_59023: Thread-1
      2669 Util_jdk_internal_misc_Signal$DispatchThread_run_eeebea10b374a7031abb3bd32119e4d5872bb7de  (in native-image) + 104  [0x10b4f1548]
        2669 cSunMiscSignal_await  (in native-image) + 44  [0x10b9e2e0c]
          2669 sem_wait  (in libsystem_kernel.dylib) + 10  [0x7fff52a1a262]

Total number in stack (recursive counted multiple, when >=5):

Sort by top of stack, same collapsed (when >= 5):
        __recvfrom  (in libsystem_kernel.dylib)        2669
        sem_wait  (in libsystem_kernel.dylib)        2669

<snipped>
```

Better explanation: because we ran version 0.32 `native-image` server previous to running the version rc17 version. And version 0.32 is running and waiting for a response (we ran this version of the native-image first and its hanging around in memory), and the version rc17 didn't run or does not talk to the version 0.32:

```
native-netty-plot git:(master) ✗ ps aux | grep java
<user>             4144   0.1 12.0 19834740 2019544   ??  S     7:02pm   4:33.63 /opt/graalvm-0.32/Contents/Home/bin/java -Xbootclasspath/a:/opt/graalvm-0.32/Contents/Home/jre/lib/boot/graaljs-scriptengine.jar:/opt/graalvm-0.32/Contents/Home/jre/lib/boot/graal-sdk.jar -cp /opt/graalvm-0.32/Contents/Home/jre/lib/svm/builder/svm.jar:/opt/graalvm-0.32/Contents/Home/jre/lib/svm/builder/objectfile.jar:/opt/graalvm-0.32/Contents/Home/jre/lib/svm/builder/svm-enterprise.jar:/opt/graalvm-0.32/Contents/Home/jre/lib/svm/builder/pointsto.jar:/opt/graalvm-0.32/Contents/Home/jre/lib/jvmci/graal.jar:/opt/graalvm-0.32/Contents/Home/jre/lib/jvmci/enterprise-graal.jar:/opt/graalvm-0.32/Contents/Home/jre/lib/jvmci/jvmci-api.jar:/opt/graalvm-0.32/Contents/Home/jre/lib/jvmci/jvmci-hotspot.jar -server -d64 -noverify -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:-UseJVMCIClassLoader -XX:+UseJVMCICompiler -Dgraal.CompileGraalWithC1Only=false -XX:CICompilerCount=2 -Dgraal.VerifyGraalGraphs=false -Dgraal.VerifyGraalGraphEdges=false -Dgraal.VerifyGraalPhasesSize=false -Dgraal.VerifyPhases=false -Dgraal.EagerSnippets=true -Xss10m -Duser.country=US -Duser.language=en -Dsubstratevm.version=ce6d21f73b901f42d4741cb2b50a039de5298ae5:substratevm,9b231d82a9ede92d66bf13ad3c2a20bb7f13e31d:substratevm-enterprise -Dgraalvm.version=0.32 -Dorg.graalvm.version=0.32 -Dcom.oracle.graalvm.isaot=true -Djvmci.class.path.append=/opt/graalvm-0.32/Contents/Home/jre/lib/jvmci/graal.jar:/opt/graalvm-0.32/Contents/Home/jre/lib/jvmci/enterprise-graal.jar -Xms1g -Xmx13743895344 com.oracle.svm.hosted.server.NativeImageBuildServer -port=26681 -logFile=/Users/path/to/.native-image/machine-id-hostid-0/session-id-22b/server-id-6bcce634b4d8e1de73671f07a79906c7c39942363266ff1cc20964263c822b5e15af666465c90aefe72cd3d26a0f9796afece9d79f59c8f706e5113c2e7a900a/server.log
```

There could have been some message or feedback as to what is happening the execution. Checking the process via MacOS's activity monitor and `ps` shows the server is waiting to be contacted.

/cc @lukasstadler

**Comment by neomatrix369** [comment]
```
 $GRAALCE_HOME/bin/native-image --server-list --verbose
```
Does not return any list or return to the CLI.

**Comment by neomatrix369** [comment]
```
$GRAALCE_HOME/bin/native-image --no-server -jar target/netty-plot-0.1-jar-with-dependencies.jar
```

And this works!

```
[netty-plot:9929]    classlist:   5,281.56 ms
[netty-plot:9929]        (cap):   2,436.64 ms
[netty-plot:9929]        setup:   6,133.58 ms
[netty-plot:9929]   (typeflow):  16,264.21 ms
[netty-plot:9929]    (objects):  17,019.55 ms
[netty-plot:9929]   (features):     625.05 ms
[netty-plot:9929]     analysis:  34,647.21 ms
[netty-plot:9929]     universe:   1,152.44 ms
[netty-plot:9929]      (parse):   3,715.89 ms
[netty-plot:9929]     (inline):   6,823.80 ms
[netty-plot:9929]    (compile):  30,517.91 ms
[netty-plot:9929]      compile:  42,635.99 ms
[netty-plot:9929]        image:   3,444.24 ms
[netty-plot:9929]        write:     814.78 ms
[netty-plot:9929]      [total]:  94,658.30 ms
```

**Comment by cstancu** [comment]
@neomatrix369 can you replicate this with the freshly released [GraalVM 19](https://github.com/oracle/graal/releases/tag/vm-19.0.0)?

**Comment by neomatrix369** [comment]
@cstancu I re-ran using rc19 and its the same issue:

```
Sampling process 10562 for 3 seconds with 1 millisecond of run time between samples
Sampling completed, processing symbols...
Analysis of sampling native-image (pid 10562) every 1 millisecond
Process:         native-image [10562]
Path:            /opt/graalvm-ce-19.0.0/Contents/Home/jre/lib/svm/bin/native-image
Load Address:    0x10c917000
Identifier:      native-image
Version:         0
Code Type:       X86-64
Parent Process:  zsh [6245]

Date/Time:       2019-05-09 22:56:38.791 +0100
Launch Time:     2019-05-09 22:56:27.744 +0100
OS Version:      Mac OS X 10.13.6 (17G6030)
Report Version:  7
Analysis Tool:   /usr/bin/sample

Physical footprint:         3748K
Physical footprint (peak):  3748K
----

Call graph:
    2688 Thread_88948   DispatchQueue_1: com.apple.main-thread  (serial)
    + 2688 PosixJavaNetClose$$Lambda$ca483cb3ef31b32ec470365988c52031e45d2fd3_getAsInt_5bf829efad7fcc93ff5d4441d36991870b04238c  (in native-image) + 111  [0x10c96a09f]
    +   2688 __recvfrom  (in libsystem_kernel.dylib) + 10  [0x7fff52a18c32]
    2688 Thread_88951: Thread-1
      2688 Util_jdk_internal_misc_Signal$DispatchThread_run_eeebea10b374a7031abb3bd32119e4d5872bb7de  (in native-image) + 104  [0x10c970fc8]
        2688 cSunMiscSignal_await  (in native-image) + 44  [0x10ce3688c]
          2688 sem_wait  (in libsystem_kernel.dylib) + 10  [0x7fff52a1a262]

Total number in stack (recursive counted multiple, when >=5):

Sort by top of stack, same collapsed (when >= 5):
        __recvfrom  (in libsystem_kernel.dylib)        2688
        sem_wait  (in libsystem_kernel.dylib)        2688
<snipped>
```

see command:
```
➜  native-netty-plot git:(master) ✗ /opt/graalvm-ce-19.0.0/Contents/Home/bin/native-image --verbose --initialize-at-run-time  -jar target/netty-plot-0.1-jar-with-dependencies.jar
Apply jar:file:///Users/swami/git-repos/hands-on-workshops/devoxxuk-2019-graalvm-session/graalvm-demos/native-netty-plot/target/netty-plot-0.1-jar-with-dependencies.jar!/META-INF/native-image/com.oracle.substratevm/netty-plot/native-image.properties
Warning: Using a deprecated option --delay-class-initialization-to-runtime. Use --initialize-at-run-time.
```
Additiona confusion, why is it showing the above warning even though I have used `--initialize-at-run-time`, am I not passing the flag in the correct manner?

**Comment by vjovanov** [comment]
I will look into this. The native-image.properties of netty contain the deprecated flag. It will be fixed with the new version of netty.

**Comment by neomatrix369** [comment]
Is this error related? I got this error after a fresh restart of the machine:

```
  native-netty-plot git:(master) ✗ $GRAALVM_HOME/bin/native-image -jar target/netty-plot-0.1-jar-with-dependencies.jar
Warning: Using a deprecated option --delay-class-initialization-to-runtime. Use --initialize-at-run-time.
Build on Server(pid: 7910, port: 49910)
[netty-plot:7910]    classlist:   1,163.30 ms
[netty-plot:7910]        setup:       7.03 ms
Fatal error: java.lang.NoClassDefFoundError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:458)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:289)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:427)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.executeCompilation(NativeImageBuildServer.java:390)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$processCommand$8(NativeImageBuildServer.java:327)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.withJVMContext(NativeImageBuildServer.java:408)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.processCommand(NativeImageBuildServer.java:324)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.processRequest(NativeImageBuildServer.java:268)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$serve$7(NativeImageBuildServer.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/graalvm/nativeimage/Feature
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.oracle.svm.hosted.FeatureHandler.registerFeatures(FeatureHandler.java:85)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:804)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:521)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:441)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: org.graalvm.nativeimage.Feature
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 22 more
Error: Image build request failed with exit status 1
```

**Comment by vjovanov** [comment]
This class is in the Graal SDK which should be on the boot classpath. This jar must be missing somehow. You can use the verbose mode to see the exact command and why this JAR is missing.

**Comment by rbygrave** [comment]
Hmmm. Getting the same issue as @neomatrix369  ... jre/lib/boot/graal-sdk.jar does exist but does not contain org.graalvm.nativeimage.Feature.class.

This `org.graalvm.nativeimage.Feature.class` is in my IntelliJ IDE classpath via graal-sdk-1.0.0-rc8.jar.

The jre/lib/boot/graal-sdk.jar is bigger, hacking around - swapping it with 1.0.0.-rc8.jar gives me 

```
...
[netty-plot:6268]    classlist:   2,149.94 ms
[netty-plot:6268]        setup:      15.09 ms
Error: Class does not implement org.graalvm.nativeimage.hosted.Feature: com.oracle.svm.nettyplot.PlotterSingletonFeature
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

I wonder if the example is now old .. and the Feature thing has been removed.

**Comment by vjovanov** [comment]
Server mode is not supported anymore.
