### ISSUE TITLE
Unkown identifier using graalvm.js engine in non-graal JVM

### ISSUE THREAD

**Issue by gzoller** [oracle/graal#1257]
I'm migrating from Nashorn to Graal via the ScriptEngineManager (running Graal's JS engine inside a stock, non-Graal VM).  I'm running Scala code, but that's not material to the issue.
Tried running Oracle's JVM 12.0.1 and 1.8.0_152.

```scala
import javax.script._

case class Foo() {
  def hi(name: String): String = "Hi, " + name + "!"
}

object Runme extends App {
  val engine = new ScriptEngineManager().getEngineByName("nashorn")
  //  val engine = new ScriptEngineManager().getEngineByName("graal.js")
  val bindings = engine.createBindings()
  bindings.put("foo", Foo())
  engine.setBindings(bindings, ScriptContext.ENGINE_SCOPE)

  engine.eval("var myFn = function(name){return foo.hi(name);}")
  println("Say " + engine.eval("myFn('Fred')")) // "Say Hi, Fred!"
}
```

When run with nashorn I see the expected output.  With graal.js I get this error:

```
Exception in thread "main" javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: TypeError: invokeMember on JavaObject[Foo() (co.blocke.scalabars.Foo)] failed due to: Unknown identifier: hi
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:338)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:310)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
	at co.blocke.scalabars.Runme$.delayedEndpoint$co$blocke$scalabars$Runme$1(Runme.scala:36)
	at co.blocke.scalabars.Runme$delayedInit$body.apply(Runme.scala:28)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at co.blocke.scalabars.Runme$.main(Runme.scala:28)
	at co.blocke.scalabars.Runme.main(Runme.scala)
Caused by: org.graalvm.polyglot.PolyglotException: TypeError: invokeMember on JavaObject[Foo() (co.blocke.scalabars.Foo)] failed due to: Unknown identifier: hi
	at <js>.myFn(<eval>:1)
	at <js>.:program(<eval>:1)
	at org.graalvm.polyglot.Context.eval(Context.java:341)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:336)
	... 13 more
```

**Comment by djoooooe** [comment]
Hi @gzoller,
Thanks for the report. GraalVM JavaScript enforces strict sandboxing rules by default, one of them being that JavaScript code cannot access host Java objects unless it is explicitly allowed by the user. The simplest way to allow your code to access `Foo.hi()` is to pass the option `polyglot.js.allowAllAccess=true` as described here: https://github.com/graalvm/graaljs/blob/master/docs/user/ScriptEngine.md.

Working example (as a JUnit test):
```
public static class Foo {

    public String hi(String name) {
        return "Hi, " + name + "!";
    }
}

@Test
public void testPutJavaObject() throws ScriptException {
    ScriptEngine engine = new ScriptEngineManager().getEngineByName("graal.js");
    Bindings bindings = engine.createBindings();
    bindings.put("polyglot.js.allowAllAccess", true);
    bindings.put("foo", new Foo());
    engine.setBindings(bindings, ScriptContext.ENGINE_SCOPE);
    engine.eval("var myFn = function(name){return foo.hi(name);}");
    assertEquals("Say Hi, Fred!", "Say " + engine.eval("myFn('Fred')"));
}
```

**Comment by djoooooe** [comment]
Closing the issue, please re-open if the suggested solution does not work for you.

**Comment by gzoller** [comment]
Many thanks, Josef.  This worked exactly as you said!

**Comment by SalathielGenese** [comment]
Thank you @djoooooe
