### ISSUE TITLE
Unable to call NetworkInterface#isLoopback

### ISSUE THREAD

**Issue by melix** [oracle/graal#1267]
Maybe I'm missing something obvious, but it feels not. The Gradle launcher needs to find a proper interface to communicate with the daemon. To do so it iterates over network interfaces and does this: https://github.com/gradle/gradle/blob/055a689b16a2b1798e77a4d9522ba935d1c610a4/subprojects/messaging/src/main/java/org/gradle/internal/remote/internal/inet/InetAddresses.java#L62

However, when running with the native image it fails with:

```
Caused by: java.lang.UnsatisfiedLinkError: java.net.NetworkInterface.isLoopback0(Ljava/lang/String;I)Z [symbol: Java_java_net_NetworkInterface_isLoopback0 or Java_java_net_NetworkInterface_isLoopback0__Ljava_lang_String_2I]
        at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
        at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
        at java.net.NetworkInterface.isLoopback0(NetworkInterface.java)
        at java.net.NetworkInterface.isLoopback(NetworkInterface.java:411)
        at org.gradle.internal.remote.internal.inet.InetAddresses.analyzeNetworkInterface(InetAddresses.java:54)
        ... 31 more
```

I tried to add this to my JNI configuration file, without success:

```
  {
    "name": "java.net.NetworkInterface",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "methods": [{ "name" : "isLoopback0", "parameterTypes": ["java.lang.String", "int"] }],
    "allDeclaredClasses": true,
    "allPublicClasses": true
  }
```

**Comment by vjovanov** [comment]
Thanks for reporting the issue. Can you send a code sample and the command to reproduce this issue?

It is hard to tell what could be the problem without a complete example.

**Comment by melix** [comment]
Repro instructions are on: https://github.com/melix/graal-repro-1267

**Comment by bobmcwhirter** [comment]
Fix here:

https://github.com/oracle/graal/pull/1406
