### ISSUE TITLE
Structured logging output

### ISSUE THREAD

**Issue by lvh** [oracle/graal#1285]
I'm debugging a bunch of native-image problems and it would be very helpful (for automation and testing and bug reporting) if I could get error reports out as structured objects. I'd be fine with any kind of format -- XML, JSON, or even just holding on to the relevant objects and letting me run some code in the JVM.

As an example of something I would like to get a structured version of, here's an error I'm seeing with native-image:

```
Error: Unsupported features in 2 methods
Detailed message:
Error: No instances are allowed in the image heap for a class that is initialized or reinitialized at image runtime: org.apache.http.conn.ssl.SSLConnectionSocketFactory. Try marking this class for build-time initialization with --initialize-at-build-time=org.apache.http.conn.ssl.SSLConnectionSocketFactory
Trace: 	object java.util.concurrent.ConcurrentHashMap$Node
	object java.util.concurrent.ConcurrentHashMap$Node[]
	object java.util.concurrent.ConcurrentHashMap
	object org.apache.http.config.Registry
	object clojure.lang.Var
	method clj_http.conn_mgr$make_reusable_conn_manager_STAR_.invokeStatic(Object)
Call path from entry point to clj_http.conn_mgr$make_reusable_conn_manager_STAR_.invokeStatic(Object): 
	at clj_http.conn_mgr$make_reusable_conn_manager_STAR_.invokeStatic(conn_mgr.clj:298)
	at clj_http.conn_mgr$make_reusable_conn_manager_STAR_.invoke(conn_mgr.clj:298)
	at clojure.core$keep$fn__8196$fn__8197.invoke(core.clj:7245)
	at clj_http.headers.HeaderMap.applyTo(headers.clj:105)
	at cljurl_graalvm_demo.core.main(Unknown Source)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:153)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
```

Obviously I can parse this, but that seems incredibly brittle and reliant on implementation details. I assume the Graal team doesn't want to promise anything about the structure of that `Call path from entry point to ...` object never changing for example. But clearly there's a JVM running here which just has that trace object -- I'd be very interested in poking at its innards. (In this particular case I'm trying to find classes that introduce image heap instances at build time, but this is a general question I think.)

**Comment by cstancu** [comment]
@lvh in this specific error message the `Call path from entry point to ...` is actually constructed by the static analysis and is not a stack trace reported by the underlying JVM. This is the shortest call path, out of possible many other paths, that the analysis finds between the entry point and the target method.
