### ISSUE TITLE
native-image error when run one spring boot project

### ISSUE THREAD

**Issue by guanchao-yang** [oracle/graal#1297]
The errors below :

```
ethod. Finally, specify the custom feature to the native image building tool using the -H:Features=MyCustomFeature option.
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:82)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:67)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:782)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:404)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:319)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1275)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1263)
        at com.example.demo.DemoApplication.main(DemoApplication.java:16)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nettyReactiveWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/reactive/ReactiveWebServerFactoryConfiguration$EmbeddedNetty.class]: Unsatisfied dependency expressed through method 'nettyReactiveWebServerFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'reactorServerResourceFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/reactive/ReactiveWebServerFactoryConfiguration$EmbeddedNetty.class]: Invocation of init method failed; nested exception is com.oracle.svm.core.jdk.UnsupportedFeatureError: The offset of long java.nio.Buffer.address is accessed without the field being first registered as unsafe accessed. Please register the field as unsafe accessed. You can do so by using a custom Feature. First, create a class that implements the org.graalvm.nativeimage.hosted.Feature interface. Then, implement the method beforeAnalysis(org.graalvm.nativeimage.BeforeAnalysisAccess config). Next, use the config object to register the field for unsafe access by calling config.registerAsUnsafeAccessed(java.lang.reflect.Field) method. Finally, specify the custom feature to the native image building tool using the -H:Features=MyCustomFeature option.
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:780)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:521)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1325)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1164)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.getWebServerFactory(ReactiveWebServerApplicationContext.java:119)
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.createWebServer(ReactiveWebServerApplicationContext.java:91)
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:79)
        ... 8 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'reactorServerResourceFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/reactive/ReactiveWebServerFactoryConfiguration$EmbeddedNetty.class]: Invocation of init method failed; nested exception is com.oracle.svm.core.jdk.UnsupportedFeatureError: The offset of long java.nio.Buffer.address is accessed without the field being first registered as unsafe accessed. Please register the field as unsafe accessed. You can do so by using a custom Feature. First, create a class that implements the org.graalvm.nativeimage.hosted.Feature interface. Then, implement the method beforeAnalysis(org.graalvm.nativeimage.BeforeAnalysisAccess config). Next, use the config object to register the field for unsafe access by calling config.registerAsUnsafeAccessed(java.lang.reflect.Field) method. Finally, specify the custom feature to the native image building tool using the -H:Features=MyCustomFeature option.
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1264)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1184)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:868)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:771)
        ... 20 more
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: The offset of long java.nio.Buffer.address is accessed without the field being first registered as unsafe accessed. Please register the field as unsafe accessed. You can do so by using a custom Feature. First, create a class that implements the org.graalvm.nativeimage.hosted.Feature interface. Then, implement the method beforeAnalysis(org.graalvm.nativeimage.BeforeAnalysisAccess config). Next, use the config object to register the field for unsafe access by calling config.registerAsUnsafeAccessed(java.lang.reflect.Field) method. Finally, specify the custom feature to the native image building tool using the -H:Features=MyCustomFeature option.
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:102)
        at sun.misc.Unsafe.objectFieldOffset(Unsafe.java:48)
        at io.netty.util.internal.PlatformDependent0$3.run(PlatformDependent0.java:164)
        at java.security.AccessController.doPrivileged(AccessController.java:63)
        at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:157)
        at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:347)
        at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:267)
        at java.lang.Class.ensureInitialized(DynamicHub.java:437)
        at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:213)
        at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:81)
        at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:347)
        at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:267)
        at java.lang.Class.ensureInitialized(DynamicHub.java:437)
        at io.netty.util.ConstantPool.<init>(ConstantPool.java:32)
        at io.netty.util.AttributeKey$1.<init>(AttributeKey.java:27)
        at io.netty.util.AttributeKey.<clinit>(AttributeKey.java:27)
        at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:347)
        at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:267)
        at java.lang.Class.ensureInitialized(DynamicHub.java:437)
        at reactor.netty.resources.PooledConnectionProvider.<clinit>(PooledConnectionProvider.java:217)
        at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:347)
        at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:267)
        at java.lang.Class.ensureInitialized(DynamicHub.java:437)
        at reactor.netty.resources.ConnectionProvider.elastic(ConnectionProvider.java:81)
        at reactor.netty.tcp.TcpResources.create(TcpResources.java:280)
        at reactor.netty.tcp.TcpResources.getOrCreate(TcpResources.java:225)
        at reactor.netty.http.HttpResources.get(HttpResources.java:41)
        at org.springframework.http.client.reactive.ReactorResourceFactory.afterPropertiesSet(ReactorResourceFactory.java:162)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1841)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
        ... 31 more

```

**Comment by cstancu** [comment]
What GraalVM version are you using? Can you please provide a reproducible example?

**Comment by aclement** [comment]
Just chiming in, not sure what the original poster is using to build their project but my work-in-progress feature compiles some spring boot apps just fine ( https://github.com/aclement/spring-boot-graal-feature ). It does currently include the necessary call to:
 
```
access.registerAsUnsafeAccessed(Buffer.class.getDeclaredField("address"));
```

which covers the exception mentioned above. But whether I should be doing it or netty itself, haven't dug into that yet.  (my feature is for Graal 19)

**Comment by guanchao-yang** [comment]
@cstancu @aclement Thank you very much ,use  https://github.com/aclement/spring-boot-graal-feature running ok.  And @aclement this project(spring-boot-graal-feature) will contribute to Spring Boot project?

**Comment by aclement** [comment]
It is a work in progress that will hopefully manifest in spring in some form (I am on the spring team).

**Comment by guanchao-yang** [comment]
@aclement Really hope!z 👍

**Comment by cstancu** [comment]
Thanks @aclement!
@guanchao-yang if I understand correctly the Feature provided by @aclement fixes your problem. I'll close this issue, please reopen if you still have problems.
