### ISSUE TITLE
sun.security.provider.NativePRNG error with Micronaut and Freemarker

### ISSUE THREAD

**Issue by ilopmar** [oracle/graal#1315]
I'm trying to create a native image with Micronaut and Freemarker and I get the following error:

```
[views-graal:29265]     analysis:  71,434.63 ms
Error: No instances are allowed in the image heap for a class that is initialized or reinitialized at image runtime: sun.security.provider.NativePRNG. Try marking this class for build-time initialization with --initialize-at-build-time=sun.security.provider.NativePRNG
Detailed message:
Trace: 	object java.security.SecureRandom
	method java.rmi.server.ObjID.<init>()
Call path from entry point to java.rmi.server.ObjID.<init>(): 
	at java.rmi.server.ObjID.<init>(ObjID.java:111)
	at sun.rmi.transport.LiveRef.<init>(LiveRef.java:74)
	at sun.rmi.server.UnicastServerRef.<init>(UnicastServerRef.java:168)
	at java.rmi.server.UnicastRemoteObject.exportObject(UnicastRemoteObject.java:320)
	at java.rmi.server.UnicastRemoteObject.<init>(UnicastRemoteObject.java:198)
	at java.rmi.server.UnicastRemoteObject.<init>(UnicastRemoteObject.java:180)
	at freemarker.debug.impl.RmiDebugModelImpl.<init>(RmiDebugModelImpl.java:53)
	at freemarker.debug.impl.RmiDebuggedEnvironmentImpl.getCachedWrapperFor(RmiDebuggedEnvironmentImpl.java:90)
	at freemarker.debug.impl.RmiDebuggedEnvironmentImpl$DebugEnvironmentModel.get(RmiDebuggedEnvironmentImpl.java:316)
	at freemarker.ext.beans.HashAdapter.get(HashAdapter.java:73)
	at freemarker.ext.beans.HashAdapter$1$1$1.getValue(HashAdapter.java:124)
	at sun.security.ssl.SSLSocketImpl$NotifyHandshakeThread.run(SSLSocketImpl.java:2687)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
```

I've also tried the suggestion of using `--initialize-at-build-time=sun.security.provider.NativePRNG` but then the error is:

```
[views-graal:30386]        setup:   2,430.04 ms
Error: Incompatible change of initialization policy for sun.security.provider.NativePRNG: trying to change BUILD_TIME from the command line to RERUN for substitutions
com.oracle.svm.core.util.UserError$UserException: Incompatible change of initialization policy for sun.security.provider.NativePRNG: trying to change BUILD_TIME from the command line to RERUN for substitutions
	at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:89)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:100)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:100)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:100)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:100)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insert(ClassInitializationConfiguration.java:62)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.rerunInitialization(ConfigurableClassInitialization.java:216)
	at com.oracle.svm.hosted.SecurityServicesFeature.duringSetup(SecurityServicesFeature.java:101)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$12(NativeImageGenerator.java:844)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:844)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:529)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:449)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
```

To reproduce the issue:
- `git clone https://github.com/micronaut-graal-tests/micronaut-views-graal`
- `cd micronaut-views-graal`
- `git checkout freemarker`
- Use latest Graal from master branch (at this moment `20.0.0-beta.01-dev`)
- `./build-native-image.sh`

Please keep in mind that I used the java agent so I've included the file generated `reflect-config.json` file.

**Comment by guanchao-yang** [comment]
@cstancu  Do we have any other workaround temporary？ Thanks

**Comment by cstancu** [comment]
@ilopmar the reported issues are not reproducible with Micronaut 1.2.0 and GraalVM 19.2.0. Now you can successfully build an image, however processing a request fails with:
```
14:20:36.752 [nioEventLoopGroup-2-2] WARN  io.netty.channel.ChannelInitializer - Failed to initialize a channel. Closing: [id: 0x1049a9a7, L:/127.0.0.1:8080 - R:/127.0.0.1:47042]
java.lang.ExceptionInInitializerError: null
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:290)
	at java.lang.Class.ensureInitialized(DynamicHub.java:467)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:235)
	at java.lang.Class.ensureInitialized(DynamicHub.java:467)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:235)
	at java.lang.Class.ensureInitialized(DynamicHub.java:467)
	at io.netty.handler.codec.http.HttpServerCodec.<init>(HttpServerCodec.java:68)
	at io.micronaut.http.server.netty.NettyHttpServer$1.initChannel(NettyHttpServer.java:292)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:964)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:610)
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1474)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1126)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:651)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:503)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:416)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:475)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1464)
	at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:279)
	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:274)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1081)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1089)
	at io.netty.handler.codec.http.HttpObjectEncoder.<clinit>(HttpObjectEncoder.java:55)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
```
This is fixed by passing `--initialize-at-run-time=io.netty.buffer.AbstractReferenceCountedByteBuf`  to `native-image`. This has already been submited to Netty: https://github.com/netty/netty/pull/9515.
