### ISSUE TITLE
[native-image] vm\mx.vm\launcher_template_modules.cmd does not exist

### ISSUE THREAD

**Issue by oroppas** [oracle/graal#1328]
```
Building native-image.exe.image-bash... [C:\msys64\home\ryuta\packages\graal\vm\mxbuild\windows-amd64\native-image.exe.image-bash\native-image.cmd does not exist]
Traceback (most recent call last):
  File "C:\msys64\home\ryuta\packages\mx\mx.py", line 19192, in <module>
    main()
  File "C:\msys64\home\ryuta\packages\mx\mx.py", line 19173, in main
    retcode = c(command_args)
  File "C:\msys64\home\ryuta\packages\mx\mx_commands.py", line 147, in __call__
    return self.command_function(*args, **kwargs)
  File "C:\msys64\home\ryuta\packages\graal\substratevm\mx.substratevm\mx_substratevm.py", line 986, in build
    orig_command_build(args, vm)
  File "C:\msys64\home\ryuta\packages\mx\mx_commands.py", line 147, in __call__
    return self.command_function(*args, **kwargs)
  File "C:\msys64\home\ryuta\packages\mx\mx.py", line 12917, in build
    t.execute()
  File "C:\msys64\home\ryuta\packages\mx\mx.py", line 964, in execute
    self.build()
  File "C:\msys64\home\ryuta\packages\graal\vm\mx.vm\mx_vm.py", line 1285, in build
    with open(self._template_file(), 'r') as template, mx.SafeFileCreation(output_file) as sfc, open(sfc.tmpPath, 'w') as launcher:
IOError: [Errno 2] No such file or directory: 'C:\\msys64\\home\\ryuta\\packages\\graal\\vm\\mx.vm\\launcher_template_modules.cmd
```

**Comment by bobmcwhirter** [comment]
I don’t have a windows VM so was unable to do the jdk11 on Windows.

**Comment by pejovica** [comment]
@oroppas, building `native-image` with JDK 11 is not yet supported on Windows (if that's what you're trying to do).

**Comment by oroppas** [comment]
That's exactly what I was trying to do. I'll be waiting for Windows support.

**Comment by pejovica** [comment]
This issue is not relevant anymore. Windows support was added a while ago.
