### ISSUE TITLE
MitigateExceedingMaxOopMapStackOffsetTest failed on AArch64

### ISSUE THREAD

**Issue by pli-arm** [oracle/graal#1337]
```
.E
runStackObjects(org.graalvm.compiler.hotspot.lir.test.MitigateExceedingMaxOopMapStackOffsetTest)
org.graalvm.compiler.debug.GraalError: java.lang.AssertionError
        at lir instruction: B0@3698 org.graalvm.compiler.lir.aarch64.AArch64Move$Move stack:32|QWORD = MOVE r0|QWORD[.]
[B0]
        at jdk.internal.vm.compiler/org.graalvm.compiler.lir.asm.CompilationResultBuilder.emitOp(CompilationResultBuilder.java:557)
        at jdk.internal.vm.compiler/org.graalvm.compiler.lir.asm.CompilationResultBuilder.emitBlock(CompilationResultBuilder.java:537)
        at jdk.internal.vm.compiler/org.graalvm.compiler.lir.asm.CompilationResultBuilder.emit(CompilationResultBuilder.java:512)
        at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.aarch64.AArch64HotSpotBackend.emitCodeBody(AArch64HotSpotBackend.java:325)
        at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.aarch64.AArch64HotSpotBackend.emitCode(AArch64HotSpotBackend.java:268)
        at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.aarch64.AArch64HotSpotBackend.emitCode(AArch64HotSpotBackend.java:251)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.gen.LIRCompilerBackend.emitCode(LIRCompilerBackend.java:207)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.gen.LIRCompilerBackend.emitBackEnd(LIRCompilerBackend.java:87)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.target.Backend.emitBackEnd(Backend.java:280)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:145)
        at org.graalvm.compiler.core.test.GraalCompilerTest.compile(GraalCompilerTest.java:1103)
        at org.graalvm.compiler.core.test.GraalCompilerTest.getCode(GraalCompilerTest.java:996)
        at org.graalvm.compiler.core.test.GraalCompilerTest.getCode(GraalCompilerTest.java:937)
        at org.graalvm.compiler.core.test.GraalCompilerTest.executeActual(GraalCompilerTest.java:763)
        at org.graalvm.compiler.core.test.GraalCompilerTest.executeActualCheckDeopt(GraalCompilerTest.java:895)
        at org.graalvm.compiler.core.test.GraalCompilerTest.testAgainstExpected(GraalCompilerTest.java:885)
        at org.graalvm.compiler.jtt.JTTTest.runTest(JTTTest.java:111)
        at org.graalvm.compiler.jtt.JTTTest.runTest(JTTTest.java:94)
        at org.graalvm.compiler.jtt.JTTTest.runTest(JTTTest.java:90)
        at org.graalvm.compiler.hotspot.lir.test.MitigateExceedingMaxOopMapStackOffsetTest.runStackObjects(MitigateExceedingMaxOopMapStackOffsetTest.java:161)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at com.oracle.mxtool.junit.MxJUnitWrapper.runRequest(MxJUnitWrapper.java:282)
        at com.oracle.mxtool.junit.MxJUnitWrapper.main(MxJUnitWrapper.java:198)
Caused by: java.lang.AssertionError
        at jdk.internal.vm.compiler/org.graalvm.compiler.asm.aarch64.AArch64MacroAssembler.makeAddress(AArch64MacroAssembler.java:186)
        at jdk.internal.vm.compiler/org.graalvm.compiler.asm.aarch64.AArch64MacroAssembler.makeAddress(AArch64MacroAssembler.java:255)
        at jdk.internal.vm.compiler/org.graalvm.compiler.lir.aarch64.AArch64Move.loadStackSlotAddress(AArch64Move.java:583)
        at jdk.internal.vm.compiler/org.graalvm.compiler.lir.aarch64.AArch64Move.loadStackSlotAddress(AArch64Move.java:577)
        at jdk.internal.vm.compiler/org.graalvm.compiler.lir.aarch64.AArch64Move.reg2stack(AArch64Move.java:436)
        at jdk.internal.vm.compiler/org.graalvm.compiler.lir.aarch64.AArch64Move.move(AArch64Move.java:378)
        at jdk.internal.vm.compiler/org.graalvm.compiler.lir.aarch64.AArch64Move$Move.emitCode(AArch64Move.java:127)
        at jdk.internal.vm.compiler/org.graalvm.compiler.lir.aarch64.AArch64LIRInstruction.emitCode(AArch64LIRInstruction.java:39)
        at jdk.internal.vm.compiler/org.graalvm.compiler.lir.asm.CompilationResultBuilder.emitOp(CompilationResultBuilder.java:550)
        ... 49 more

```
@dougxc @sanzinger

**Comment by sanzinger** [comment]
Thank you for reporting this issue. The problem arises when the stack gets large enough so the offset cannot be stored with immediate offset. I have a fix which provides a scratch register.
