### ISSUE TITLE
java.net.UnknownHostException in native-image mode, not in JVM mode

### ISSUE THREAD

**Issue by rsvoboda** [oracle/graal#1338]
When playing with Quarkus I noticed UnknownHostException in native mode, not in JVM mode. Found with 1.0.0-rc-16, present in GraalVM CE 19.0.0.

I have my hostname set to RS, no dns around. Of course when I update my /etc/hosts this issues goes away even for native mode. But sometimes users don't have rights to edit /etc/hosts or they don't know they can do it.

GraalVM/Substrate VM simple example:

```java
import java.net.InetAddress;
import java.net.UnknownHostException;
public class AbcMain {
    public static void main(String[] args) throws UnknownHostException {
        InetAddress inetAddress = InetAddress.getLocalHost();
        System.out.println("IP of my system is: " + inetAddress.getHostAddress());
        System.out.println("Name of my system is: " + inetAddress.getHostName());
    }
}
```

```
javac AbcMain.java
```
```
java -cp . AbcMain
IP of my system is: 10.20.30.101
Name of my system is: RS
```

```
native-image --no-server AbcMain
 ...
./abcmain
Exception in thread "main" java.net.UnknownHostException: RS: RS
	at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
	at AbcMain.main(AbcMain.java:7)
Caused by: java.net.UnknownHostException: RS
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:3439)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
	... 1 more
```

**Comment by bobmcwhirter** [comment]
Experimenting locally, I've found on OSX...

JVM mode works both with my network up and down.

Network Up: IPv4 address resolution.
Network Down: IPv6 address resolution (non-null, just f'ugly).

Native-Image mode works only with network up:

Network Up: IPv4 address resolution
Network Down: Error below (granted, weird stack, I'm JDK11'ing...)

```
Exception in thread "main" java.net.UnknownHostException: melvin
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:3416)
	at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515)
	at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1505)
	at java.net.InetAddress.getAllByName(InetAddress.java:1364)
	at java.net.InetAddress.getAllByName(InetAddress.java:1298)
	at Foo.main(Foo.java:12)
```

Looking at the PosixNetJava substitutions, it *looks* right. 

Using `-Djava.net.preferIPv6Addresses=true` either while building the native image or on the command-line executive of the native image seems to make no difference, and still get IPv4 resolution when successful and the network is up.
