### ISSUE TITLE
Failed to bootstrap Netty with graal 19.0.0

### ISSUE THREAD

**Issue by aboullaite** [oracle/graal#1346]
Hello,

Following the issue #1262, I've successfully managed to build and generate my native image using graal 19.0.0!
```
StartServer [
/opt/graalvm-ce-19.0.0/bin/java \
-Xbootclasspath/a:/opt/graalvm-ce-19.0.0/jre/lib/boot/graaljs-scriptengine.jar:/opt/graalvm-ce-19.0.0/jre/lib/boot/graal-sdk.jar \
-cp \
/opt/graalvm-ce-19.0.0/jre/lib/svm/builder/pointsto.jar:/opt/graalvm-ce-19.0.0/jre/lib/svm/builder/svm.jar:/opt/graalvm-ce-19.0.0/jre/lib/svm/builder/llvm-platform-specific.jar:/opt/graalvm-ce-19.0.0/jre/lib/svm/builder/llvm-wrapper.jar:/opt/graalvm-ce-19.0.0/jre/lib/svm/builder/objectfile.jar:/opt/graalvm-ce-19.0.0/jre/lib/svm/builder/svm-llvm.jar:/opt/graalvm-ce-19.0.0/jre/lib/svm/builder/graal-llvm.jar:/opt/graalvm-ce-19.0.0/jre/lib/svm/builder/javacpp.jar:/opt/graalvm-ce-19.0.0/jre/lib/jvmci/jvmci-api.jar:/opt/graalvm-ce-19.0.0/jre/lib/jvmci/graal-management.jar:/opt/graalvm-ce-19.0.0/jre/lib/jvmci/graal.jar:/opt/graalvm-ce-19.0.0/jre/lib/jvmci/jvmci-hotspot.jar \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-XX:-UseJVMCICompiler \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-d64 \
-XX:-UseJVMCIClassLoader \
-Xss10m \
-Duser.country=US \
-Duser.language=en \
-Dorg.graalvm.version=19.0.0 \
-Dorg.graalvm.config=CE \
-Dcom.oracle.graalvm.isaot=true \
-Djvmci.class.path.append=/opt/graalvm-ce-19.0.0/jre/lib/jvmci/graal.jar \
-Xmx3344274224 \
-Xms1g \
com.oracle.svm.hosted.server.NativeImageBuildServer \
-port=0 \
-logFile=/root/.native-image/machine-id-900c9f54d99f4948aed3f701d540d791/session-id-1/server-id-f0e60dc82ca3ff54fcb83818aa7c09b80f94f534409925bcba2c7f90af25fcacea2b118075b5986455fd5d7538749b7caab1376400091f202493ce8ce985ae96/server.log
]
Build on Server(pid: 9, port: 39353)*
SendBuildRequest [
-task=com.oracle.svm.hosted.NativeImageGeneratorRunner
-imagecp
/opt/graalvm-ce-19.0.0/jre/lib/svm/builder/pointsto.jar:/opt/graalvm-ce-19.0.0/jre/lib/svm/builder/svm.jar:/opt/graalvm-ce-19.0.0/jre/lib/svm/builder/llvm-platform-specific.jar:/opt/graalvm-ce-19.0.0/jre/lib/svm/builder/llvm-wrapper.jar:/opt/graalvm-ce-19.0.0/jre/lib/svm/builder/objectfile.jar:/opt/graalvm-ce-19.0.0/jre/lib/svm/builder/svm-llvm.jar:/opt/graalvm-ce-19.0.0/jre/lib/svm/builder/graal-llvm.jar:/opt/graalvm-ce-19.0.0/jre/lib/svm/builder/javacpp.jar:/opt/graalvm-ce-19.0.0/jre/lib/jvmci/jvmci-api.jar:/opt/graalvm-ce-19.0.0/jre/lib/jvmci/graal-management.jar:/opt/graalvm-ce-19.0.0/jre/lib/jvmci/graal.jar:/opt/graalvm-ce-19.0.0/jre/lib/jvmci/jvmci-hotspot.jar:/opt/graalvm-ce-19.0.0/jre/lib/boot/graaljs-scriptengine.jar:/opt/graalvm-ce-19.0.0/jre/lib/boot/graal-sdk.jar:/opt/graalvm-ce-19.0.0/jre/lib/svm/library-support.jar:/opt/app/netty-example-1.0-SNAPSHOT.jar
-H:Path=/opt/app
-H:Class=me.aboullaite.dockercon.HelloWorld
-H:Kind=STATIC_EXECUTABLE
-H:ClassInitialization=io.netty.handler.codec.http.HttpObjectEncoder:run_time
-H:ReflectionConfigurationResources=netty_reflection_config.json
-H:+ReportUnsupportedElementsAtRuntime
-H:Optimize=1
-H:CLibraryPath=/opt/graalvm-ce-19.0.0/jre/lib/svm/clibraries/linux-amd64
-H:Name=netty-native
]
[netty-native:9]    classlist:   5,989.44 ms
[netty-native:9]        (cap):   1,107.17 ms
[netty-native:9]        setup:   3,321.85 ms
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of io.netty.buffer.AbstractReferenceCountedByteBuf. Detailed failure reason(s): Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
[netty-native:9]   (typeflow):  11,219.94 ms
[netty-native:9]    (objects):   8,217.74 ms
[netty-native:9]   (features):     554.79 ms
[netty-native:9]     analysis:  20,467.96 ms
[netty-native:9]     (clinit):     344.98 ms
[netty-native:9]     universe:     917.57 ms
[netty-native:9]      (parse):   1,706.88 ms
[netty-native:9]     (inline):   2,109.81 ms
[netty-native:9]    (compile):  15,958.53 ms
[netty-native:9]      compile:  20,457.85 ms
[netty-native:9]        image:   1,074.65 ms
[netty-native:9]        write:     326.71 ms
[netty-native:9]      [total]:  52,916.37 ms
```
However, Now the application fails to start with the following error:
```
May 30, 2019 3:38:10 AM io.netty.util.internal.PlatformDependent <clinit>
INFO: Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
May 30, 2019 3:38:10 AM io.netty.channel.DefaultChannelId defaultProcessId
WARNING: Failed to find the current process ID from ''; using a random value: -1443740830
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class io.netty.buffer.ByteBufAllocator
        at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:211)
        at java.lang.Class.ensureInitialized(DynamicHub.java:437)
        at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:58)
        at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:71)
        at io.netty.bootstrap.FailedChannel.<init>(FailedChannel.java:30)
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:330)
        at io.netty.bootstrap.AbstractBootstrap.doBind
```

You can find the sample [here](https://github.com/aboullaite/java-docker/tree/graal). It's working perfectly with graal rc16!

**Comment by aboullaite** [comment]
Updated to GraalVM 19.2.0.1 and Netty 4.1.41.Final solved the issue with some minor modification!

**Comment by cstancu** [comment]
@aboullaite thanks for reporting back!
