### ISSUE TITLE
Error found while creating native-image with micronaut 1.1.2

### ISSUE THREAD

**Issue by jlojosnegros** [oracle/graal#1360]
Procedure:
```
09:05 $ ./gradlew assemble

BUILD SUCCESSFUL in 14s
10 actionable tasks: 8 executed, 2 up-to-date
09:06 $ native-image --no-server --no-fallback  -cp build/libs/catalog-0.1.jar 
[catalog:16475]    classlist:   5,373.20 ms
[catalog:16475]        (cap):     808.07 ms
[catalog:16475]        setup:   2,180.30 ms
Warning: RecomputeFieldValue.ArrayIndexScale automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.arrayIndexScale(Class
) was detected in the static initializer of reactor.core.publisher.RingBufferFields. Detailed failure reason(s): Could not determine the field where the value produced by the call to su
n.misc.Unsafe.arrayIndexScale(Class) for the array index scale computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a 
field store. 
Warning: RecomputeFieldValue.ArrayBaseOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.arrayBaseOffset(Class
) was detected in the static initializer of reactor.core.publisher.RingBufferFields. Detailed failure reason(s): Could not determine the field where the value produced by the call to su
n.misc.Unsafe.arrayBaseOffset(Class) for the array base offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a 
field store. 
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) 
was detected in the static initializer of reactor.core.publisher.UnsafeSupport. Detailed failure reason(s): Could not determine the field where the value produced by the call to sun.mis
c.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field st
ore. 
[catalog:16475]     analysis:  67,483.71 ms
Fatal error: java.lang.NoClassDefFoundError
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:458)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:289)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:427)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:109)
Caused by: java.lang.NoClassDefFoundError: io/netty/channel/unix/DomainSocketAddress
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at com.oracle.svm.core.hub.DynamicHub.initEnumConstantsAtRuntime(DynamicHub.java:390)
        at com.oracle.svm.hosted.analysis.Inflation.checkType(Inflation.java:194)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
        at com.oracle.svm.hosted.analysis.Inflation.checkObjectGraph(Inflation.java:136)
        at com.oracle.graal.pointsto.BigBang.checkObjectGraph(BigBang.java:599)
        at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:557)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:684)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:523)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:441)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: io.netty.channel.unix.DomainSocketAddress
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 20 more
Error: Image build request failed with exit status 1
```

property file:
```
Args = -H:IncludeResources=logback.xml|application.yml|bootstrap.yml \
       -H:Name=catalog \
       -H:Class=org.jlom.master_upm.tfm.graalvm.catalog.CatalogApplication \
       -H:+ReportExceptionStackTraces \
       --allow-incomplete-classpath \
       --initialize-at-build-time=com.nimbusds.jose.jwk.KeyType \
       --initialize-at-build-time=io.micrometer.core.instrument.ImmutableTag \
       --initialize-at-build-time=net.minidev.json.JSONObject \
       --initialize-at-build-time=io.micrometer.core.instrument.logging.LoggingRegistryConfig \
       --initialize-at-run-time=io.micronaut.configuration.lettuce.session.$RedisHttpSessionConfigurationDefinition \
       --initialize-at-build-time=reactor.core.publisher.Mono \
       --initialize-at-build-time=io.micrometer.prometheus.PrometheusConfig \
       --initialize-at-build-time=io.micrometer.core.instrument.simple.SimpleConfig \
       --initialize-at-build-time=io.micrometer.core.instrument.config.NamingConvention \
       --initialize-at-build-time=io.micrometer.core.instrument.config.NamingConvention$1 \
       --initialize-at-build-time=reactor.core.publisher.Flux \
       --initialize-at-build-time=io.lettuce.core.dynamic.Batcher
```

**Comment by cstancu** [comment]
@jlojosnegros this issue should have been fixed. Please reopen if still a problem with GraalVM 19.2.0 and latest micronaut release? Please also provide the source code for `catalog-0.1.jar ` so we can reproduce.
