### ISSUE TITLE
RInternalError: java.lang.StackOverflowError when trying to load RData file

### ISSUE THREAD

**Issue by thiagohora** [oracle/graal#1372]
I'm getting a StackOverflowError when trying to load a RData file

R script:
```
library(caret)
library(tm)
library(SnowballC)
library(kernlab)
library(e1071)

load('r/fitSvm.RData')
load('r/tdm.RData')
load('r/ss.RData')
```

Stack trace:
```
Loading required package: lattice
Loading required package: ggplot2
Loading required package: NLP

Attaching package: ‘NLP’

The following object is masked from ‘package:ggplot2’:

    annotate


Attaching package: ‘kernlab’

The following object is masked from ‘package:ggplot2’:

    alpha
...
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.glovoapp.hackathon.r.RService]: Constructor threw exception; nested exception is org.graalvm.polyglot.PolyglotException: com.oracle.truffle.r.runtime.RInternalError: java.lang.StackOverflowError
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:184)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:300)
	... 39 more
Caused by: org.graalvm.polyglot.PolyglotException: com.oracle.truffle.r.runtime.RInternalError: java.lang.StackOverflowError
	at com.oracle.truffle.r.nodes.function.FunctionDefinitionNode.execute(FunctionDefinitionNode.java:330)
	at org.graalvm.polyglot.Value.execute(Value.java:338)
	at com.glovoapp.hackathon.r.FastR.execute(FastR.java:134)
	at com.glovoapp.hackathon.r.FastR.call(FastR.java:159)
	at com.glovoapp.hackathon.r.RBundle.<init>(RBundle.java:45)
	at com.glovoapp.hackathon.r.RService.<init>(RService.java:16)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172)
	... 41 more
```

**Comment by thiagohora** [comment]
Any insights here?
