### ISSUE TITLE
native-image-maven-plugin misbehaves with graalvm-19.0.0 without native-image installed

### ISSUE THREAD

**Issue by smoell** [oracle/graal#1375]
Hi all,

I started migrating my project from 1.0.0-rc16 to 19.0.0.

My Args:

```
Args =  --enable-url-protocols=http,https --enable-all-security-services \
        --static \
        --verbose \
        --report-unsupported-elements-at-runtime \
        --initialize-at-run-time=io.netty.handler.codec.http2.Http2CodecUtil,io.netty.handler.codec.http.HttpObjectEncoder,io.netty.handler.codec.http2.DefaultHttp2FrameWriter,io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder \
        -H:IncludeResources=(META-INF|vertx-default-jul-logging)/.* \
        -H:ReflectionConfigurationFiles=classes/${.}/reflection.json
```

The output:

```
-H:Path=/target \
-H:EnableURLProtocols=http,https \
-H:Kind=STATIC_EXECUTABLE \
-H:ClassInitialization=io.netty.handler.codec.http2.Http2CodecUtil:run_time,io.netty.handler.codec.http.HttpObjectEncoder:run_time,io.netty.handler.codec.http2.DefaultHttp2FrameWriter:run_time,io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder:run_time \
-H:IncludeResources=(META-INF|vertx-default-jul-logging)/.* \
-H:+EnableAllSecurityServices \
-H:+ReportUnsupportedElementsAtRuntime \
-H:+AllowIncompleteClasspath \
-H:Class=com.amazon.BootStrapVerticle \
-H:Name=reactive-vertx \
-H:CLibraryPath=/target/native-image-maven-plugin/19.0.0/linux-amd64 \
-H:ReflectionConfigurationFiles=/target/classes/META-INF/native-image/com.amazon/reactive-vertx/reflection.json
]
Fatal error: java.lang.UnsupportedOperationException: java.lang.UnsupportedOperationException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
        at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
        at com.oracle.svm.hosted.ImageClassLoader.initAllClasses(ImageClassLoader.java:158)
        at com.oracle.svm.hosted.ImageClassLoader.create(ImageClassLoader.java:114)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:197)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:427)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:109)
Caused by: java.lang.UnsupportedOperationException
        at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:123)
        at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
        at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276)
        at com.oracle.svm.hosted.ImageClassLoader.loadClassesFromPath(ImageClassLoader.java:191)
        at com.oracle.svm.hosted.ImageClassLoader.lambda$initAllClasses$0(ImageClassLoader.java:158)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:2746)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Unfortunately, I have no idea how to proceed,

**Comment by cstancu** [comment]
The major change between RC16 and 19 releases is the class initialization strategy. In RC16 all classes were eagerly initialized at build time whereas in 19 the application classes are initialized at runtime by default. You can read more about class initialization [here](https://github.com/oracle/graal/blob/master/substratevm/CLASS-INITIALIZATION.md). As a quick test you can try initializing the whole class hierarchy can be initialized at build time, i.e., the previous behavior, by adding `--initialize-at-build-time` on the command line.

**Comment by cstancu** [comment]
Actually, looking closer at the stack trace I think that the problem is not due to class initialization changes. The exception is thrown from `com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:123)`:
```
if (!var8.endsWith(".zip") && !var8.endsWith(".jar")) {
                    throw new UnsupportedOperationException();
                }
```
Can you provide the entire output of `--verbose` including the `-imagecp` section ?

**Comment by smoell** [comment]
Sure, here's the complete output:

```
[INFO] ImageClasspath: /root/.m2/repository/io/vertx/vertx-core/3.7.1/vertx-core-3.7.1.jar:/root/.m2/repository/io/netty/netty-common/4.1.34.Final/netty-common-4.1.34.Final.jar:/root/.m2/repository/io/netty/netty-buffer/4.1.34.Final/netty-buffer-4.1.34.Final.jar:/root/.m2/repository/io/netty/netty-transport/4.1.34.Final/netty-transport-4.1.34.Final.jar:/root/.m2/repository/io/netty/netty-handler/4.1.34.Final/netty-handler-4.1.34.Final.jar:/root/.m2/repository/io/netty/netty-codec/4.1.34.Final/netty-codec-4.1.34.Final.jar:/root/.m2/repository/io/netty/netty-handler-proxy/4.1.34.Final/netty-handler-proxy-4.1.34.Final.jar:/root/.m2/repository/io/netty/netty-codec-socks/4.1.34.Final/netty-codec-socks-4.1.34.Final.jar:/root/.m2/repository/io/netty/netty-codec-http/4.1.34.Final/netty-codec-http-4.1.34.Final.jar:/root/.m2/repository/io/netty/netty-codec-http2/4.1.34.Final/netty-codec-http2-4.1.34.Final.jar:/root/.m2/repository/io/netty/netty-resolver/4.1.34.Final/netty-resolver-4.1.34.Final.jar:/root/.m2/repository/io/netty/netty-resolver-dns/4.1.34.Final/netty-resolver-dns-4.1.34.Final.jar:/root/.m2/repository/io/netty/netty-codec-dns/4.1.34.Final/netty-codec-dns-4.1.34.Final.jar:/root/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.8/jackson-core-2.9.8.jar:/root/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.8/jackson-databind-2.9.8.jar:/root/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.8/jackson-annotations-2.9.8.jar:/root/.m2/repository/io/vertx/vertx-redis-client/3.7.1/vertx-redis-client-3.7.1.jar:/root/.m2/repository/io/vertx/vertx-web/3.7.1/vertx-web-3.7.1.jar:/root/.m2/repository/io/vertx/vertx-web-common/3.7.1/vertx-web-common-3.7.1.jar:/root/.m2/repository/io/vertx/vertx-auth-common/3.7.1/vertx-auth-common-3.7.1.jar:/root/.m2/repository/io/vertx/vertx-bridge-common/3.7.1/vertx-bridge-common-3.7.1.jar:/root/.m2/repository/io/vertx/vertx-web-client/3.7.1/vertx-web-client-3.7.1.jar:/root/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/2.9.5/jackson-dataformat-cbor-2.9.5.jar:/root/.m2/repository/software/amazon/awssdk/kinesis/2.5.56/kinesis-2.5.56.jar:/root/.m2/repository/software/amazon/awssdk/aws-cbor-protocol/2.5.56/aws-cbor-protocol-2.5.56.jar:/root/.m2/repository/software/amazon/awssdk/aws-json-protocol/2.5.56/aws-json-protocol-2.5.56.jar:/root/.m2/repository/software/amazon/awssdk/protocol-core/2.5.56/protocol-core-2.5.56.jar:/root/.m2/repository/software/amazon/awssdk/sdk-core/2.5.56/sdk-core-2.5.56.jar:/root/.m2/repository/software/amazon/awssdk/profiles/2.5.56/profiles-2.5.56.jar:/root/.m2/repository/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.jar:/root/.m2/repository/software/amazon/awssdk/auth/2.5.56/auth-2.5.56.jar:/root/.m2/repository/software/amazon/eventstream/eventstream/1.0.1/eventstream-1.0.1.jar:/root/.m2/repository/software/amazon/awssdk/http-client-spi/2.5.56/http-client-spi-2.5.56.jar:/root/.m2/repository/software/amazon/awssdk/regions/2.5.56/regions-2.5.56.jar:/root/.m2/repository/software/amazon/awssdk/annotations/2.5.56/annotations-2.5.56.jar:/root/.m2/repository/software/amazon/awssdk/utils/2.5.56/utils-2.5.56.jar:/root/.m2/repository/software/amazon/awssdk/aws-core/2.5.56/aws-core-2.5.56.jar:/root/.m2/repository/software/amazon/awssdk/apache-client/2.5.56/apache-client-2.5.56.jar:/root/.m2/repository/org/apache/httpcomponents/httpclient/4.5.6/httpclient-4.5.6.jar:/root/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/root/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/root/.m2/repository/org/apache/httpcomponents/httpcore/4.4.10/httpcore-4.4.10.jar:/root/.m2/repository/software/amazon/awssdk/netty-nio-client/2.5.56/netty-nio-client-2.5.56.jar:/root/.m2/repository/io/netty/netty-transport-native-epoll/4.1.34.Final/netty-transport-native-epoll-4.1.34.Final-linux-x86_64.jar:/root/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.34.Final/netty-transport-native-unix-common-4.1.34.Final.jar:/root/.m2/repository/com/typesafe/netty/netty-reactive-streams-http/2.0.0/netty-reactive-streams-http-2.0.0.jar:/root/.m2/repository/com/typesafe/netty/netty-reactive-streams/2.0.0/netty-reactive-streams-2.0.0.jar:/root/.m2/repository/software/amazon/awssdk/url-connection-client/2.5.56/url-connection-client-2.5.56.jar:/root/.m2/repository/com/google/protobuf/protobuf-java/3.7.1/protobuf-java-3.7.1.jar:/root/.m2/repository/com/google/guava/guava/27.1-jre/guava-27.1-jre.jar:/root/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/root/.m2/repository/com/google/gua a/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/root/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/root/.m2/repository/org/checkerframework/checker-qual/2.5.2/checker-qual-2.5.2.jar:/root/.m2/repository/com/google/errorprone/error_prone_annotations/2.2.0/error_prone_annotations-2.2.0.jar:/root/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar:/root/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.17/animal-sniffer-annotations-1.17.jar:/root/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/target/reactive-vertx-1.6.jar
[INFO] BuildArgs: [--enable-all-security-services, -H:+ReportUnsupportedElementsAtRuntime, --allow-incomplete-classpath, -H:Class=com.amazon.BootStrapVerticle, -H:Name=reactive-vertx]
Executing [
/opt/graalvm-ce-19.0.0/jre/bin/java \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-XX:-UseJVMCICompiler \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-d64 \
-XX:-UseJVMCIClassLoader \
-Xss10m \
-Xms1g \
-Xmx13068402688 \
-Duser.country=US \
-Duser.language=en \
-Dorg.graalvm.version=dev \
-Dorg.graalvm.config= \
-Dcom.oracle.graalvm.isaot=true \
-Djvmci.class.path.append=/root/.m2/repository/org/graalvm/compiler/compiler/19.0.0/compiler-19.0.0.jar \
-Xbootclasspath/a:/root/.m2/repository/org/graalvm/sdk/graal-sdk/19.0.0/graal-sdk-19.0.0.jar \
-cp \
/root/.m2/repository/com/oracle/substratevm/svm/19.0.0/svm-19.0.0.jar:/root/.m2/repository/com/oracle/substratevm/pointsto/19.0.0/pointsto-19.0.0.jar:/root/.m2/repository/com/oracle/substratevm/objectfile/19.0.0/objectfile-19.0.0.jar:/opt/graalvm-ce-19.0.0/jre/lib/jvmci/jvmci-api.jar:/opt/graalvm-ce-19.0.0/jre/lib/jvmci/parentClassLoader.classpath:/opt/graalvm-ce-19.0.0/jre/lib/jvmci/graal.jar:/opt/graalvm-ce-19.0.0/jre/lib/jvmci/graal-management.jar:/opt/graalvm-ce-19.0.0/jre/lib/jvmci/compiler-name:/opt/graalvm-ce-19.0.0/jre/lib/jvmci/jvmci-hotspot.jar:/opt/graalvm-ce-19.0.0/jre/lib/jvmci/jvmci-api.src.zip:/opt/graalvm-ce-19.0.0/jre/lib/jvmci/jvmci-hotspot.src.zip:/root/.m2/repository/org/graalvm/compiler/compiler/19.0.0/compiler-19.0.0.jar \
com.oracle.svm.hosted.NativeImageGeneratorRunner \
-imagecp \
/root/.m2/repository/org/graalvm/sdk/graal-sdk/19.0.0/graal-sdk-19.0.0.jar:/root/.m2/repository/com/oracle/substratevm/svm/19.0.0/svm-19.0.0.jar:/root/.m2/repository/com/oracle/substratevm/pointsto/19.0.0/pointsto-19.0.0.jar:/root/.m2/repository/com/oracle/substratevm/objectfile/19.0.0/objectfile-19.0.0.jar:/opt/graalvm-ce-19.0.0/jre/lib/jvmci/jvmci-api.jar:/opt/graalvm-ce-19.0.0/jre/lib/jvmci/parentClassLoader.classpath:/opt/graalvm-ce-19.0.0/jre/lib/jvmci/graal.jar:/opt/graalvm-ce-19.0.0/jre/lib/jvmci/graal-management.jar:/opt/graalvm-ce-19.0.0/jre/lib/jvmci/compiler-name:/opt/graalvm-ce-19.0.0/jre/lib/jvmci/jvmci-hotspot.jar:/opt/graalvm-ce-19.0.0/jre/lib/jvmci/jvmci-api.src.zip:/opt/graalvm-ce-19.0.0/jre/lib/jvmci/jvmci-hotspot.src.zip:/root/.m2/repository/org/graalvm/compiler/compiler/19.0.0/compiler-19.0.0.jar:/root/.m2/repository/com/oracle/substratevm/library-support/19.0.0/library-support-19.0.0.jar:/root/.m2/repository/io/vertx/vertx-core/3.7.1/vertx-core-3.7.1.jar:/root/.m2/repository/io/netty/netty-common/4.1.34.Final/netty-common-4.1.34.Final.jar:/root/.m2/repository/io/netty/netty-buffer/4.1.34.Final/netty-buffer-4.1.34.Final.jar:/root/.m2/repository/io/netty/netty-transport/4.1.34.Final/netty-transport-4.1.34.Final.jar:/root/.m2/repository/io/netty/netty-handler/4.1.34.Final/netty-handler-4.1.34.Final.jar:/root/.m2/repository/io/netty/netty-codec/4.1.34.Final/netty-codec-4.1.34.Final.jar:/root/.m2/repository/io/netty/netty-handler-proxy/4.1.34.Final/netty-handler-proxy-4.1.34.Final.jar:/root/.m2/repository/io/netty/netty-codec-socks/4.1.34.Final/netty-codec-socks-4.1.34.Final.jar:/root/.m2/repository/io/netty/netty-codec-http/4.1.34.Final/netty-codec-http-4.1.34.Final.jar:/root/.m2/repository/io/netty/netty-codec-http2/4.1.34.Final/netty-codec-http2-4.1.34.Final.jar:/root/.m2/repository/io/netty/netty-resolver/4.1.34.Final/netty-resolver-4.1.34.Final.jar:/root/.m2/repository/io/netty/netty-resolver-dns/4.1.34.Final/netty-resolver-dns-4.1.34.Final.jar:/root/.m2/repository/io/netty/netty-codec-dns/4.1.34.Final/netty-codec-dns-4.1.34.Final.jar:/root/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.8/jackson-core-2.9.8.jar:/root/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.8/jackson-databind-2.9.8.jar:/root/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.8/jackson-annotations-2.9.8.jar:/root/.m2/repository/io/vertx/vertx-redis-client/3.7.1/vertx-redis-client-3.7.1.jar:/root/.m2/repository/io/vertx/vertx-web/3.7.1/vertx-web-3.7.1.jar:/root/.m2/repository/io/vertx/vertx-web-common/3.7.1/vertx-web-common-3.7.1.jar:/root/.m2/repository/io/vertx/vertx-auth-common/3.7.1/vertx-auth-common-3.7.1.jar:/root/.m2/repository/io/vertx/vertx-bridge-common/3.7.1/vertx-bridge-common-3.7.1.jar:/root/.m2/repository/io/vertx/vertx-web-client/3.7.1/vertx-web-client-3.7.1.jar:/root/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/2.9.5/jackson-dataformat-cbor-2.9.5.jar:/root/.m2/repository/software/amazon/awssdk/kinesis/2.5.56/kinesis-2.5.56.jar:/root/.m2/repository/software/amazon/awssdk/aws-cbor-protocol/2.5.56/aws-cbor-protocol-2.5.56.jar:/root/.m2/repository/software/amazon/awssdk/aws-json-protocol/2.5.56/aws-json-protocol-2.5.56.jar:/root/.m2/repository/software/amazon/awssdk/protocol-core/2.5.56/protocol-core-2.5.56.jar:/root/.m2/repository/software/amazon/awssdk/sdk-core/2.5.56/sdk-core-2.5.56.jar:/root/.m2/repository/software/amazon/awssdk/profiles/2.5.56/profiles-2.5.56.jar:/root/.m2/repository/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.jar:/root/.m2/repository/software/amazon/awssdk/auth/2.5.56/auth-2.5.56.jar:/root/.m2/repository/software/amazon/eventstream/eventstream/1.0.1/eventstream-1.0.1.jar:/root/.m2/repository/software/amazon/awssdk/http-client-spi/2.5.56/http-client-spi-2.5.56.jar:/root/.m2/repository/software/amazon/awssdk/regions/2.5.56/regions-2.5.56.jar:/root/.m2/repository/software/amazon/awssdk/annotations/2.5.56/annotations-2.5.56.jar:/root/.m2/repository/software/amazon/awssdk/utils/2.5.56/utils-2.5.56.jar:/root/.m2/repository/software/amazon/awssdk/aws-core/2.5.56/aws-core-2.5.56.jar:/root/.m2/repository/software/amazon/awssdk/apache-client/2.5.56/apache-client-2.5.56.jar:/root/.m2/repository/org/apache/httpcomponents/httpclient/4.5.6/httpclient-4.5.6.jar:/root/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/root/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/root/.m2/repository/org/apache/httpcomponents/httpcore/4.4.10/httpcore-4.4.10.jar:/root/.m2/repository/software/amazon/awssdk/netty-nio-client/2.5.56/netty-nio-client-2.5.56.jar:/root/.m2/repository/io/netty/netty-transport-native-epoll/4.1.34.Final/netty-transport-native-epoll-4.1.34.Final-linux-x86_64.jar:/root/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.34.Final/netty-transport-native-unix-common-4.1.34.Final.jar:/root/.m2/repository/com/typesafe/netty/netty-reactive-streams-http/2.0.0/netty-reactive-streams-http-2.0.0.jar:/root/.m2/repository/com/typesafe/netty/netty-reactive-streams/2.0.0/netty-reactive-streams-2.0.0.jar:/root/.m2/repository/software/amazon/awssdk/url-connection-client/2.5.56/url-connection-client-2.5.56.jar:/root/.m2/repository/com/google/protobuf/protobuf-java/3.7.1/protobuf-java-3.7.1.jar:/root/.m2/repository/com/google/guava/guava/27.1-jre/guava-27.1-jre.jar:/root/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/root/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/root/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/root/.m2/repository/org/checkerframework/checker-qual/2.5.2/checker-qual-2.5.2.jar:/root/.m2/repository/com/google/errorprone/error_prone_annotations/2.2.0/error_prone_annotations-2.2.0.jar:/root/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar:/root/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.17/animal-sniffer-annotations-1.17.jar:/root/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/target/reactive-vertx-1.6.jar \
-H:Path=/target \
-H:EnableURLProtocols=http,https \
-H:Kind=STATIC_EXECUTABLE \
-H:ClassInitialization=io.netty.handler.codec.http2.Http2CodecUtil:run_time,io.netty.handler.codec.http.HttpObjectEncoder:run_time,io.netty.handler.codec.http2.DefaultHttp2FrameWriter:run_time,io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder:run_time \
-H:IncludeResources=(META-INF|vertx-default-jul-logging)/.* \
-H:+EnableAllSecurityServices \
-H:+ReportUnsupportedElementsAtRuntime \
-H:+AllowIncompleteClasspath \
-H:Class=com.amazon.BootStrapVerticle \
-H:Name=reactive-vertx \
-H:CLibraryPath=/target/native-image-maven-plugin/19.0.0/linux-amd64 \
-H:ReflectionConfigurationFiles=/target/classes/META-INF/native-image/com.amazon/reactive-vertx/reflection.json
]
Fatal error: java.lang.UnsupportedOperationException: java.lang.UnsupportedOperationException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
        at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
        at com.oracle.svm.hosted.ImageClassLoader.initAllClasses(ImageClassLoader.java:158)
        at com.oracle.svm.hosted.ImageClassLoader.create(ImageClassLoader.java:114)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:197)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:427)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:109)
Caused by: java.lang.UnsupportedOperationException
        at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:123)
        at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
        at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276)
        at com.oracle.svm.hosted.ImageClassLoader.loadClassesFromPath(ImageClassLoader.java:191)
        at com.oracle.svm.hosted.ImageClassLoader.lambda$initAllClasses$0(ImageClassLoader.java:158)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:2746)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by cstancu** [comment]
The problem is most likely the entry `/opt/graalvm-ce-19.0.0/jre/lib/jvmci/parentClassLoader.classpath` in both `-cp` and `-imagecp`. Additionally `-imagecp` contains an entry `/opt/graalvm-ce-19.0.0/jre/lib/jvmci/compiler-name` which seems wrong. Do you use Quarkus? I don't recognize the `[INFO] ImageClasspath:` and `[INFO] BuildArgs:` from our usual output.

**Comment by olpaw** [comment]
> Do you use Quarkus? I don't recognize the [INFO] ImageClasspath: and [INFO] BuildArgs: lines from our usual output.

I think he is using the `native-image-maven-plugin`. See https://github.com/oracle/graal/blob/b9beef9d00f7c4898d6fc6683f845c221d91feba/substratevm/src/native-image-maven-plugin/src/main/java/com/oracle/substratevm/NativeImageMojo.java#L235

Having `parentClassLoader.classpath` on the cp & imagecp comes from not filtering for `*.jar` only in
https://github.com/oracle/graal/blob/b9beef9d00f7c4898d6fc6683f845c221d91feba/substratevm/src/native-image-maven-plugin/src/main/java/com/oracle/substratevm/NativeImageMojo.java#L381

@smoell can you try if temporarily moving `parentClassLoader.classpath` out of `/opt/graalvm-ce-19.0.0/jre/lib/jvmci/` makes the problem go away. If that is the case then we need a fix for the `NativeImageMojo` class.

**Comment by olpaw** [comment]
Oh, I see what's going on. You have /opt/graalvm-ce-19.0.0 set as your `JAVA_HOME` but the graalvm installed there does not have native-image installed. This confuses the plugin and it takes the wrong turn. Running `gu install native-image` should fix the problem.

Nonetheless I will refine the detection for native-image availability so that this will not be an issue in future releases. In the past downloading a graalvm release always had `native-image` included (it was not optional component), and the `native-image-maven-plugin` was built with that assumption in mind.

**Comment by dougxc** [comment]
@olpaw I would also suggest making `ImageClassLoader` more resilient again class paths that include entries that are neither zip/jars nor directories.

**Comment by smoell** [comment]
Changed my Dockerfile to 

```
FROM oracle/graalvm-ce:19.0.0 AS build-aot

RUN yum clean all && yum update -y && yum install wget -y

RUN wget https://www-eu.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz -P /tmp
RUN tar xf /tmp/apache-maven-3.6.1-bin.tar.gz -C /opt
RUN ln -s /opt/apache-maven-3.6.1 /opt/maven
RUN ln -s /opt/graalvm-ce-19.0.0 /opt/graalvm

ENV GRAALVM_HOME=/opt/graalvm
ENV JAVA_HOME=/opt/graalvm
ENV M2_HOME=/opt/maven
ENV MAVEN_HOME=/opt/maven
ENV PATH=${M2_HOME}/bin:${PATH}
ENV PATH=${GRAALVM_HOME}/bin:${PATH}

COPY ./pom.xml ./pom.xml
COPY src ./src/

ENV MAVEN_OPTS='-Xmx6g'

RUN gu install native-image

RUN mvn -Dmaven.test.skip=true -Pnative-image-fargate clean package
```

now it works, thank you.

**Comment by olpaw** [comment]
I put a fix on master that ensures that even without having run `gu install native-image` before using `native-image-maven-plugin` it runs as expected. In this case the plugin downloads all missing components needed for image building from maven central.
