### ISSUE TITLE
native-image-maven-plugin UnsupportedOperationException ZipFileSystemProvider

### ISSUE THREAD

**Issue by dansiviter** [oracle/graal#1390]
Creating the simplest of hello world applications reusing `com.oracle.substratevm:native-image-maven-plugin:19.0.0` results in a `java.lang.UnsupportedOperationException`.

It doesn't appear 19.0.2 is in maven central so can't test with that.

**Version:**
```plain
$ mvn -version
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T20:00:29+01:00)
Maven home: /Users/***/maven/apache-maven-3.6.1
Java version: 1.8.0_212, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-19.0.2/Contents/Home/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.5", arch: "x86_64", family: "mac"
```

**pom.xml**
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>acme</groupId>
	<artifactId>graal-demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<properties>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

		<graalvm.version>19.0.0</graalvm.version>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>com.oracle.substratevm</groupId>
				<artifactId>native-image-maven-plugin</artifactId>
				<version>${graalvm.version}</version>
				<executions>
					<execution>
						<goals>
							<goal>native-image</goal>
						</goals>
						<phase>package</phase>
					</execution>
				</executions>
				<configuration>
					<mainClass>acme.Main</mainClass>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
```

**Class:**
```java
package acme;

public class Main {
	public static void main(String[] args) {
		System.out.println("*** Hello! ***");
	}
}
```

**Stacktrace:**
```plain
[INFO] --- native-image-maven-plugin:19.0.0:native-image (default) @ graal-demo ---
[INFO] ImageClasspath Entry: acme:graal-demo:jar:0.0.1-SNAPSHOT (file:///Users/***/graal-demo/target/graal-demo-0.0.1-SNAPSHOT.jar)
[INFO] WorkingDirectory: /Users/***/graal-demo/target
[INFO] ImageClasspath: /Users/***/graal-demo/target/graal-demo-0.0.1-SNAPSHOT.jar
[INFO] BuildArgs: [-H:Class=acme.Main]
Fatal error: java.lang.UnsupportedOperationException: java.lang.UnsupportedOperationException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at com.oracle.svm.hosted.ImageClassLoader.initAllClasses(ImageClassLoader.java:158)
	at com.oracle.svm.hosted.ImageClassLoader.create(ImageClassLoader.java:114)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:197)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:427)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:109)
Caused by: java.lang.UnsupportedOperationException
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:123)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276)
	at com.oracle.svm.hosted.ImageClassLoader.loadClassesFromPath(ImageClassLoader.java:191)
	at com.oracle.svm.hosted.ImageClassLoader.lambda$initAllClasses$0(ImageClassLoader.java:158)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:2746)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

```

**Comment by SergejIsbrecht** [comment]
If I were to follow the documentation on medium ( https://medium.com/graalvm/simplifying-native-image-generation-with-maven-plugin-and-embeddable-configuration-d5b283b92f57 ) it actually works as expected. 

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.test</groupId>
    <artifactId>maven-test</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.3</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <classpathPrefix>lib/</classpathPrefix>
                            <classpathLayoutType>repository</classpathLayoutType>
                            <mainClass>de.graalvm.Main</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>

            <plugin>
                <groupId>com.oracle.substratevm</groupId>
                <artifactId>native-image-maven-plugin</artifactId>
                <version>19.0.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>native-image</goal>
                        </goals>
                        <phase>package</phase>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

This also works:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.test</groupId>
    <artifactId>maven-test</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.3</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <classpathPrefix>lib/</classpathPrefix>
                            <classpathLayoutType>repository</classpathLayoutType>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>

            <plugin>
                <groupId>com.oracle.substratevm</groupId>
                <artifactId>native-image-maven-plugin</artifactId>
                <version>19.0.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>native-image</goal>
                        </goals>
                        <phase>package</phase>
                        <configuration>
                            <mainClass>de.graalvm.Main</mainClass>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

In order to build you need to excute:
`mvn package`

The executable will be place in the "**target**" folder

**Comment by olpaw** [comment]
Also note that I only recently I fixed a `native-image-maven-plugin` issue in regard to using a graalvm installation as JAVA_HOME that does not have `gu install native-image` run before. For 19.0.X the workaround is to ensure `gu install native-image` has been run prior to using the plugin. On master this is no more necessary. See: https://github.com/oracle/graal/issues/1375

**Comment by dansiviter** [comment]
@olpaw `gu install native-image` worked around it for me. Thanks
