### ISSUE TITLE
What is the correct way to load shared object dependencies to build native image?

### ISSUE THREAD

**Issue by adityats2020** [oracle/graal#1393]
I have a project that includes the following kinds of dependencies
* JARs
* Shared Objects (*.so)
* Files that setup shared libraries (via LD_LIBRARY_PATH)

When I try to create native-image by setting classpath to the folder containing these files, it fails with the following error
```StartServer [
/workspace/graalvm/jre/bin/java \
-Xbootclasspath/a:/workspace/graalvm/jre/lib/boot/graal-sdk.jar:/workspace/graalvm/jre/lib/boot/graaljs-scriptengine.jar \
-cp \
/workspace/graalvm/jre/lib/svm/builder/javacpp.jar:/workspace/graalvm/jre/lib/svm/builder/llvm-platform-specific.jar:/workspace/graalvm/jre/lib/svm/builder/llvm-wrapper.jar:/workspace/graalvm/jre/lib/svm/builder/pointsto.jar:/workspace/graalvm/jre/lib/svm/builder/svm-llvm.jar:/workspace/graalvm/jre/lib/svm/builder/svm.jar:/workspace/graalvm/jre/lib/svm/builder/graal-llvm.jar:/workspace/graalvm/jre/lib/svm/builder/objectfile.jar:/workspace/graalvm/jre/lib/jvmci/jvmci-hotspot.jar:/workspace/graalvm/jre/lib/jvmci/graal.jar:/workspace/graalvm/jre/lib/jvmci/graal-management.jar:/workspace/graalvm/jre/lib/jvmci/jvmci-api.jar \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-XX:-UseJVMCICompiler \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-d64 \
-XX:-UseJVMCIClassLoader \
-Xss10m \
-Duser.country=US \
-Duser.language=en \
-Dorg.graalvm.version=19.0.2 \
-Dorg.graalvm.config=CE \
-Dcom.oracle.graalvm.isaot=true \
-Djvmci.class.path.append=/workspace/graalvm/jre/lib/jvmci/graal.jar \
-Xmx1655644160 \
-Xms1g \
com.oracle.svm.hosted.server.NativeImageBuildServer \
-port=0 \
-logFile=/root/.native-image/machine-id-hostid-11ac0200/session-id-1/server-id-a5d4632cc246d89dc2cdfd67f7d80719d6cbef9d03b57e2787a0f9cc31fff52694543da2dc443e21b1b06a35337190d7c9bbf22b0244042e597eb0a58e60db71/server.log
]
Build on Server(pid: 9, port: 34851)*
SendBuildRequest [
-task=com.oracle.svm.hosted.NativeImageGeneratorRunner
-imagecp
/workspace/graalvm/jre/lib/svm/builder/javacpp.jar:/workspace/graalvm/jre/lib/svm/builder/llvm-platform-specific.jar:/workspace/graalvm/jre/lib/svm/builder/llvm-wrapper.jar:/workspace/graalvm/jre/lib/svm/builder/pointsto.jar:/workspace/graalvm/jre/lib/svm/builder/svm-llvm.jar:/workspace/graalvm/jre/lib/svm/builder/svm.jar:/workspace/graalvm/jre/lib/svm/builder/graal-llvm.jar:/workspace/graalvm/jre/lib/svm/builder/objectfile.jar:/workspace/graalvm/jre/lib/jvmci/jvmci-hotspot.jar:/workspace/graalvm/jre/lib/jvmci/graal.jar:/workspace/graalvm/jre/lib/jvmci/graal-management.jar:/workspace/graalvm/jre/lib/jvmci/jvmci-api.jar:/workspace/graalvm/jre/lib/boot/graal-sdk.jar:/workspace/graalvm/jre/lib/boot/graaljs-scriptengine.jar:/workspace/graalvm/jre/lib/svm/library-support.jar:/workspace/lib/Project-1.0.jar:/workspace/lib/*
-H:Path=/workspace
-H:+ReportExceptionStackTraces
-H:Name=project
-H:+ReportUnsupportedElementsAtRuntime
-H:Kind=SHARED_LIBRARY
-H:CLibraryPath=/workspace/graalvm/jre/lib/svm/clibraries/linux-amd64
-H:Class=com.alpha.Launcher
]
Fatal error: java.lang.UnsupportedOperationException: java.lang.UnsupportedOperationException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at com.oracle.svm.hosted.ImageClassLoader.initAllClasses(ImageClassLoader.java:158)
	at com.oracle.svm.hosted.ImageClassLoader.create(ImageClassLoader.java:114)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:200)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:430)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.executeCompilation(NativeImageBuildServer.java:390)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$processCommand$8(NativeImageBuildServer.java:327)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.withJVMContext(NativeImageBuildServer.java:408)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.processCommand(NativeImageBuildServer.java:324)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.processRequest(NativeImageBuildServer.java:268)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$serve$7(NativeImageBuildServer.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedOperationException
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:123)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276)
	at com.oracle.svm.hosted.ImageClassLoader.loadClassesFromPath(ImageClassLoader.java:191)
	at com.oracle.svm.hosted.ImageClassLoader.lambda$initAllClasses$0(ImageClassLoader.java:158)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:2746)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1259)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1077)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1043)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1002)
```

From https://github.com/oracle/graal/issues/438, I gather that the shared library path has to be set using `H:CLibraryPath`. Is that accurate? 
How can I resolve dependencies that set LD_LIBRARY_PATH?

**Comment by AdamBien** [comment]
You are right, for me H:CLibraryPath is working, but LD_LIBRARY_PATH is ignored. Checkout: https://adambien.blog/roller/abien/entry/graalvm_how_to_call_c

**Comment by fernando-valdez** [comment]
Using **-H:CLibraryPath** is the correct way to accomplish this.
