### ISSUE TITLE
SubstrateVM: MulticastSocket.joinGroup() fails

### ISSUE THREAD

**Issue by belaban** [oracle/graal#1398]

**Comment by belaban** [comment]
I'm trying to get JGroups running with IP multicast support, but the showstopper is `MulticastSocket.joinGroup()`:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: java.net.PlainDatagramSocketImpl.join(Ljava/net/InetAddress;Ljava/net/NetworkInterface;)V [symbol: Java_java_net_PlainDatagramSocketImpl_join or Java_java_net_PlainDatagramSocketImpl_join__Ljava_net_InetAddress_2Ljava_net_NetworkInterface_2]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
	at java.net.PlainDatagramSocketImpl.join(PlainDatagramSocketImpl.java)
	at java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:178)
	at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323)
	at org.jgroups.tests.MulticastTest.testMulticastSocket(MulticastTest.java:41)
	at org.jgroups.tests.MulticastTest.main(MulticastTest.java:34)
```

The issue is also present in `DatagramChannel.join()`.

To reproduce:
- Use native-compile on MulticastTest [1]
- Run with MulticastSocket: ./org.jgroups.tests.multicasttest
- Run with DatagramChannel:  ./org.jgroups.tests.multicasttest -nio

The latter issue seems to be related to [3].

[1] https://github.com/belaban/JGroups/blob/master/tests/other/org/jgroups/tests/MulticastTest.java
[2] https://issues.jboss.org/browse/JGRP-2344
[3] https://github.com/oracle/graal/issues/474

**Comment by dmlloyd** [comment]
I've been looking at this. I think I can probably produce an initial PR sometime in the next few days.

**Comment by belaban** [comment]
Thanks a bunch, David! The beers next time we meet are on me! :-)

**Comment by dmlloyd** [comment]
I've opened pull request #1404.  This fixes the old I/O case, but not the NIO case yet.

**Comment by belaban** [comment]
Thanks, David! 
This fixes the showstopper that's preventing UDP from running! The NIO case is not currently a showstopper for me.

**Comment by dmlloyd** [comment]
That's what I figured.  NIO is a bit tricky because it's very different between Java 8 and Java 11, and I'm not sure it's worth investing a large effort to get Java 8 going.  We'll see what they say about the initial PR before I try to cross that bridge.

**Comment by belaban** [comment]
I tested this with GraalVM 19.1.1, but the multicasttest still fails:

```
[belasmac] /Users/bela$ ./org.jgroups.tests.multicasttest
Exception in thread "main" java.lang.UnsatisfiedLinkError: java.net.PlainDatagramSocketImpl.join(Ljava/net/InetAddress;Ljava/net/NetworkInterface;)V [symbol: Java_java_net_PlainDatagramSocketImpl_join or Java_java_net_PlainDatagramSocketImpl_join__Ljava_net_InetAddress_2Ljava_net_NetworkInterface_2]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
	at java.net.PlainDatagramSocketImpl.join(PlainDatagramSocketImpl.java)
	at java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:178)
	at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323)
	at org.jgroups.tests.MulticastTest.testMulticastSocket(MulticastTest.java:42)
	at org.jgroups.tests.MulticastTest.main(MulticastTest.java:35)
```

**Comment by belaban** [comment]
This is on MacOS, but that shouldn't be the issue as the Java version works fine.

**Comment by bobmcwhirter** [comment]
@belaban Couldja open a new issue for `PlainDatagramSocketImpl.join(...)` so we could track it separately?

**Comment by belaban** [comment]
@bobmcwhirter What do you mean? Clone this issue and change the titel? :-)

**Comment by bobmcwhirter** [comment]
This one is closed and references a different method so.... yes?

**Comment by belaban** [comment]
Done: https://github.com/oracle/graal/issues/1584
