### ISSUE TITLE
BootstrapJVMCI is broken with EconomyCompilerConfiguration on AArch64

### ISSUE THREAD

**Issue by pli-arm** [oracle/graal#1408]
After @thomaswue's below commit of restricting application of canonicalizations, BootstrapJVMCI is broken with -Dgraal.CompilerConfiguration=economy on AArch64.
```
commit 1419ca558c45504065b09825d57acbc6be822636
Author: Thomas Wuerthinger <thomas.wuerthinger@oracle.com>
Date:   Sun Jun 9 18:18:01 2019 +0200

    Restrict application of canonicalizations for better compilation speed.
```

Command line to reproduce this failure (only on AArch64, x86 is good)
```
mx vm -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler -Djvmci.Compiler=graal \
  -Dgraal.CompilationFailureAction=ExitVM -Dgraal.CompilerConfiguration=economy -XX:+BootstrapJVMCI -version
```

Stack trace printed
```
Thread[JVMCI CompilerThread24,9,system]: Compilation of jdk.internal.org.objectweb.asm.SymbolTable.addConstantUtf8(String) failed:
org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.IllegalStateException: zip file closed
        at parsing jdk.internal.org.objectweb.asm.SymbolTable.addConstantUtf8(SymbolTable.java:800)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2470)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3272)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3074)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:976)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:870)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase.run(GraphBuilderPhase.java:55)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase.run(GraphBuilderPhase.java:40)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:209)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:213)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:144)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:129)
        at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileHelper(HotSpotGraalCompiler.java:225)
        at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:243)
        at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:159)
        at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:80)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:177)
        at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:323)
        at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:143)
        at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:109)
        at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:692)
Caused by: java.lang.IllegalStateException: zip file closed
        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:850)
        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:339)
        at java.base/java.util.zip.ZipFile$1.getEntry(ZipFile.java:1056)
        at java.base/java.util.jar.JarFile.getEntry0(JarFile.java:577)
        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:506)
        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:468)
        at java.base/jdk.internal.module.ModuleReferences$JarModuleReader.getEntry(ModuleReferences.java:243)
        at java.base/jdk.internal.module.ModuleReferences$JarModuleReader.implOpen(ModuleReferences.java:264)
        at java.base/jdk.internal.module.ModuleReferences$SafeCloseModuleReader.open(ModuleReferences.java:181)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findResourceAsStream(BuiltinClassLoader.java:275)
        at java.base/java.lang.Module.getResourceAsStream(Module.java:1574)
        at jdk.internal.vm.compiler/org.graalvm.compiler.serviceprovider.GraalServices.getClassfileAsStream(GraalServices.java:205)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.classfile.ClassfileBytecodeProvider.getClassfile(ClassfileBytecodeProvider.java:111)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.classfile.ClassfileBytecodeProvider.getBytecode(ClassfileBytecodeProvider.java:86)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.<init>(BytecodeParser.java:797)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.createBytecodeParser(GraphBuilderPhase.java:89)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.parseAndInlineCallee(BytecodeParser.java:2485)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.inline(BytecodeParser.java:2391)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.intrinsify(BytecodeParser.java:2323)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.graphbuilderconf.MethodSubstitutionPlugin.execute(MethodSubstitutionPlugin.java:207)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.tryInvocationPlugin(BytecodeParser.java:2092)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1801)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genDynamicInvokeHelper(BytecodeParser.java:1675)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1625)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1610)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5113)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3267)
        ... 23 more
```

**Comment by XiaohongGong** [comment]
@sanzinger I committed an PR to fix this issue : https://github.com/oracle/graal/pull/1465. Can you help to take a look at it? Thank you!

**Comment by pli-arm** [comment]
Close this as #1465 is merged
