### ISSUE TITLE
Graal CompileTheWorld failed with JDK 14

### ISSUE THREAD

**Issue by pli-arm** [oracle/graal#1409]
Graal unittest CompileTheWorld failed with latest JDK (14).

Stack trace printed
```
--o-o-o-o-o-o-o-o-o-o-o-o-o-o-
CompileTheWorld : Waiting for 99686 compiles
CompileTheWorld : Waiting for 93808 compiles
--o-o-o-o-o-o-o-o-o-o-o-o-o-o-
Thread[CompileTheWorld-46,10,main]: Compilation of java.net.http.HttpRequest.equals(Object) failed:
org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.AssertionError
	at parsing java.net.http.HttpRequest.equals(HttpRequest.java:395)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2470)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3272)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3074)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:976)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:870)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase.run(GraphBuilderPhase.java:55)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase.run(GraphBuilderPhase.java:40)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:209)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:213)
	at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:144)
	at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:129)
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileHelper(HotSpotGraalCompiler.java:225)
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:243)
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:159)
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:80)
	at jdk.internal.vm.compiler/org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:177)
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:323)
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:297)
	at org.graalvm.compiler.hotspot.test.CompileTheWorld.compileMethod(CompileTheWorld.java:984)
	at org.graalvm.compiler.hotspot.test.CompileTheWorld.access$400(CompileTheWorld.java:117)
	at org.graalvm.compiler.hotspot.test.CompileTheWorld$1.run(CompileTheWorld.java:919)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
	at jdk.internal.vm.compiler/org.graalvm.compiler.core.CompilerThread.run(CompilerThread.java:42)
Caused by: java.lang.AssertionError
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.isDefinitelyResolvedWithRespectTo(HotSpotResolvedObjectTypeImpl.java:840)
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotSignature.checkValidCache(HotSpotSignature.java:140)
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotSignature.getReturnType(HotSpotSignature.java:197)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1774)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genDynamicInvokeHelper(BytecodeParser.java:1675)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1625)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1610)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5113)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3267)
	... 30 more
```

**Comment by dougxc** [comment]
Is this using Graal in OpenJDK or GitHub Graal? Can you please provide the command line for reproducing.

**Comment by pli-arm** [comment]
This is using GitHub Graal built with JDK 14 and can be reproduced by `mx gate -t CTW:hosted`

**Comment by dougxc** [comment]
@pli-arm thanks for finding this.
I'm moving this to a JBS bug: https://bugs.openjdk.java.net/browse/JDK-8226566
