### ISSUE TITLE
Java 11: ReentrantLock used on heap during native-image gen

### ISSUE THREAD

**Issue by dmlloyd** [oracle/graal#1415]
I'm seeing an exception trace like this:

```
2019-06-20 14:53:31 com.oracle.svm.core.util.UserError$UserException: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option -H:ClassInitialization=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
2019-06-20 14:53:31 Detailed message:
2019-06-20 14:53:31 Trace:      object java.util.concurrent.locks.ReentrantLock$NonfairSync
2019-06-20 14:53:31     object java.util.concurrent.locks.ReentrantLock
2019-06-20 14:53:31     method sun.awt.SunToolkit.awtUnlock()
2019-06-20 14:53:31 Call path from entry point to sun.awt.SunToolkit.awtUnlock(): 
2019-06-20 14:53:31     at java.desktop@11.0.3/sun.awt.SunToolkit.awtUnlock(SunToolkit.java:203)
2019-06-20 14:53:31     at java.desktop@11.0.3/sun.java2d.xr.XRPMBlit.Blit(XRPMBlitLoops.java:183)
2019-06-20 14:53:31     at java.desktop@11.0.3/sun.java2d.pipe.DrawImage.renderImageXform(DrawImage.java:552)
2019-06-20 14:53:31     at java.desktop@11.0.3/sun.java2d.pipe.DrawImage.transformImage(DrawImage.java:264)
2019-06-20 14:53:31     at java.desktop@11.0.3/sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:76)
2019-06-20 14:53:31     at java.desktop@11.0.3/sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:1027)
2019-06-20 14:53:31     at java.desktop@11.0.3/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3415)
2019-06-20 14:53:31     at java.desktop@11.0.3/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3391)
2019-06-20 14:53:31     at com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$10.convertToBufferedImage(RuntimeBuiltinLeafInfoImpl.java:428)
2019-06-20 14:53:31     at com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$10.print(RuntimeBuiltinLeafInfoImpl.java:452)
2019-06-20 14:53:31     at com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$10.print(RuntimeBuiltinLeafInfoImpl.java:386)
2019-06-20 14:53:31     at com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$PcdataImpl.writeText(RuntimeBuiltinLeafInfoImpl.java:183)
2019-06-20 14:53:31     at com.sun.xml.bind.v2.runtime.ValueListBeanInfoImpl.serializeBody(ValueListBeanInfoImpl.java:125)
2019-06-20 14:53:31     at com.sun.xml.bind.v2.runtime.XMLSerializer.childAsSoleContent(XMLSerializer.java:593)
2019-06-20 14:53:31     at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.serializeRoot(ClassBeanInfoImpl.java:341)
2019-06-20 14:53:31     at com.sun.xml.bind.v2.runtime.XMLSerializer.childAsRoot(XMLSerializer.java:494)
2019-06-20 14:53:31     at com.sun.xml.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:328)
2019-06-20 14:53:31     at com.sun.xml.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:256)
2019-06-20 14:53:31     at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:110)
2019-06-20 14:53:31     at org.jboss.resteasy.plugins.providers.jaxb.MapProvider.writeTo(MapProvider.java:308)
2019-06-20 14:53:31     at org.jboss.resteasy.client.jaxrs.internal.AbortedResponse.<init>(AbortedResponse.java:69)
2019-06-20 14:53:31     at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterRequest(ClientInvocation.java:639)
2019-06-20 14:53:31     at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:485)
2019-06-20 14:53:31     at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:519)
2019-06-20 14:53:31     at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.method(ClientInvocationBuilder.java:326)
2019-06-20 14:53:31     at org.jboss.resteasy.client.jaxrs.internal.CompletionStageRxInvokerImpl.lambda$method$48(CompletionStageRxInvokerImpl.java:354)
2019-06-20 14:53:31     at org.jboss.resteasy.client.jaxrs.internal.CompletionStageRxInvokerImpl$$Lambda$1463/0x00000007c241c040.get(Unknown Source)
2019-06-20 14:53:31     at java.base@11.0.3/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
2019-06-20 14:53:31     at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2019-06-20 14:53:31     at app//com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
2019-06-20 14:53:31     at app//com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
2019-06-20 14:53:31     at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
```

I think what's happening is that at the time the heap snapshot is being built, the lock is held by a running AWT thread, so that thread is considered "on the heap".  I don't have a "real" stack trace of that thread, but I would assume it is the EDT, which should be "killable" simply by finding and interrupting it, which should in turn release all its locks and so forth.  I don't know how or when this should be done.

**Comment by vjovanov** [comment]
Are you using `--initialize-at-build-time`? This should not be happening with the new class initialization policies.

**Comment by dmlloyd** [comment]
Yes, Quarkus initialized everything at build time by default.

**Comment by vjovanov** [comment]
Well, that is why. You need to avoid initializing the class that puts this thread to the heap.

**Comment by dmlloyd** [comment]
Sure, that's a fair point, but before I close this issue I have one question: is there any event or phase that we can hook into wherein we can perform some action after class init is complete but before the heap is snapshotted?

**Comment by vjovanov** [comment]
Yes, you can do it in `afterAnalysis` if it does not have to interact with analysis or `duringAnalysis` if you want to influence analysis.

**Comment by dmlloyd** [comment]
OK.  Well, now I have a couple options - thanks!
