### ISSUE TITLE
Built native-image for spring-boot app failing with 'caught signal 11'

### ISSUE THREAD

**Issue by aclement** [oracle/graal#1421]
Using my spring-boot feature and running native-image against a new app that involves hibernate. Fixed quite a few things in my feature (reflect/resource lists) but now it seems to just crash and I'm not sure what to do next. See dump below.  I can probably come up with a recreation test project if useful.
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                        

Jun 21, 2019 5:05:34 PM org.springframework.boot.StartupInfoLogger logStarting
INFO: Starting SampleApplication on Andys-MacBook-Pro-2018.local with PID 95052 (started by aclement in /Users/aclement/gits3/vanilla-orm)
Jun 21, 2019 5:05:34 PM org.springframework.boot.SpringApplication logStartupProfileInfo
INFO: No active profile set, falling back to default profiles: default
2019-06-21 17:05:34.836  INFO 95052 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2019-06-21 17:05:34.839  INFO 95052 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2019-06-21 17:05:34.840  INFO 95052 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2019-06-21 17:05:34.841  INFO 95052 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate Core {[WORKING]}
[ [ SubstrateSegfaultHandler caught signal 11 ] ]

  
  General Purpose Register Set Values: 
  
    RAX 0000000000000000
    RBX 0000000000000000
    RCX 0000000000000001
    RDX 0000000115c6d5c8
    RBP 0000000000000000
    RSI 0000000000000000
    RDI 000000010f187b78
    RSP 00007ffeebbeb1c8
    R8 0000000000000026
    R9 0000000000000005
    R10 00000000026e8f58
    R11 000000000000001f
    R12 0000000009ae5878
    R13 00000000c0001002
    R14 000000010c187000
    R15 00007fa246c05380
    EFL 0000000000010206
    RIP 0000000000000000
    
  
  JavaFrameAnchor dump:
  
    No anchors
    
  TopFrame info:
  
    
  VMThreads info:
  
    VMThread 00007fa248a001d0  STATUS_IN_NATIVE  java.lang.Thread@0x1159d8228
    VMThread 00007fa246c05380  STATUS_IN_JAVA (safepoints disabled)  java.lang.Thread@0x10ef47a78
    
  VM Thread State for current thread 00007fa246c05380:
  
    0 (8 bytes): com.oracle.svm.jni.JNIThreadLocalEnvironment.jniFunctions = (bytes) 
      00007fa246c05380: 0000000000000000
    
    8 (32 bytes): com.oracle.svm.core.genscavenge.ThreadLocalAllocation.pinnedTLAB = (bytes) 
      00007fa246c05388: 0000000000000000 0000000000000000
      00007fa246c05398: 0000000000000000 0000000000000000
      
    
    40 (32 bytes): com.oracle.svm.core.genscavenge.ThreadLocalAllocation.regularTLAB = (bytes) 
      00007fa246c053a8: 0000000115c00000 0000000115d00000
      00007fa246c053b8: 0000000115c6d5f0 0000000115a00000
      
    
    72 (8 bytes): com.oracle.svm.core.genscavenge.PinnedAllocatorImpl.openPinnedAllocator = (Object) null
    80 (8 bytes): com.oracle.svm.core.heap.NoAllocationVerifier.openVerifiers = (Object) null
    88 (8 bytes): com.oracle.svm.core.jdk.IdentityHashCodeSupport.hashCodeGeneratorTL = (Object) java.util.SplittableRandom  000000010ff80168
    96 (8 bytes): com.oracle.svm.core.snippets.SnippetRuntime.currentException = (Object) null
    104 (8 bytes): com.oracle.svm.core.thread.JavaThreads.currentThread = (Object) java.lang.Thread  000000010ef47a78
    112 (8 bytes): com.oracle.svm.core.thread.ThreadingSupportImpl.activeTimer = (Object) null
    120 (8 bytes): com.oracle.svm.jni.JNIThreadLocalHandles.handles = (Object) null
    128 (8 bytes): com.oracle.svm.jni.JNIThreadLocalPendingException.pendingException = (Object) null
    136 (8 bytes): com.oracle.svm.jni.JNIThreadLocalPinnedObjects.pinnedObjectsListHead = (Object) null
    144 (8 bytes): com.oracle.svm.jni.JNIThreadOwnedMonitors.ownedMonitors = (Object) null
    152 (8 bytes): com.oracle.svm.core.genscavenge.ThreadLocalAllocation.freeList = (Word) 0  0000000000000000
    160 (8 bytes): com.oracle.svm.core.graal.snippets.StackOverflowCheckImpl.stackBoundaryTL = (Word) 140732845228032  00007ffeeb3f8000
    168 (8 bytes): com.oracle.svm.core.stack.JavaFrameAnchors.lastAnchor = (Word) 0  0000000000000000
    176 (8 bytes): com.oracle.svm.core.thread.VMThreads.IsolateTL = (Word) 4497895424  000000010c187000
    184 (8 bytes): com.oracle.svm.core.thread.VMThreads.OSThreadIdTL = (Word) 4682552768  00000001171a15c0
    192 (8 bytes): com.oracle.svm.core.thread.VMThreads.nextTL = (Word) 0  0000000000000000
    200 (4 bytes): com.oracle.svm.core.graal.snippets.StackOverflowCheckImpl.yellowZoneStateTL = (int) 1  00000001
    204 (4 bytes): com.oracle.svm.core.snippets.ImplicitExceptions.implicitExceptionsAreFatal = (int) 0  00000000
    208 (4 bytes): com.oracle.svm.core.thread.Safepoint.safepointRequested = (int) -9324253  ff71b923
    212 (4 bytes): com.oracle.svm.core.thread.Safepoint.safepointRequestedValueBeforeSafepoint = (int) 0  00000000
    216 (4 bytes): com.oracle.svm.core.thread.ThreadingSupportImpl.currentPauseDepth = (int) 0  00000000
    220 (4 bytes): com.oracle.svm.core.thread.VMOperationControl.isLockOwner = (int) 0  00000000
    224 (4 bytes): com.oracle.svm.core.thread.VMThreads$StatusSupport.safepointsDisabledTL = (int) 1  00000001
    228 (4 bytes): com.oracle.svm.core.thread.VMThreads$StatusSupport.statusTL = (int) 1  00000001
    
  VMOperation dump:
  
    No VMOperation in progress
    
  Dump Counters:
  
    
  Raw Stacktrace:
  
    00007ffeebbeb1c8: 0000000104448cf7 0000000115c645d8
    00007ffeebbeb1d8: 0000000115c64520 0000000115c645d8
    00007ffeebbeb1e8: 000000010db85dd8 000000010f187bb0
    00007ffeebbeb1f8: 0000000003000bb0 000000010db85df0
    00007ffeebbeb208: 000000010dc38900 000000010f187b78
    00007ffeebbeb218: 00000001054c3bd2 f4c9ba2e15c6d298
    00007ffeebbeb228: 0000000009ae6298 000000010dc38900
    00007ffeebbeb238: 00000001060fe16b 0000000115c64520
    00007ffeebbeb248: 0000000106371be2 000000010db98a80
    00007ffeebbeb258: 000000000ef48348 000000010dc388d0
    00007ffeebbeb268: 00000001060fe818 000000010c187000
    00007ffeebbeb278: 000000000ff01490 000000010dc388d0
    00007ffeebbeb288: 00000001060fd676 0000000115c57300
    00007ffeebbeb298: 0000000104441468 000000030f19f338
    00007ffeebbeb2a8: 000000010ef48348 000000010dc38618
    00007ffeebbeb2b8: 000000010dc38630 0000000115c64520
    00007ffeebbeb2c8: 000000010ef2b518 000000010e6d7430
    00007ffeebbeb2d8: 0000000104448cf7 0000000115c57300
    00007ffeebbeb2e8: 0000000105705004 000000010f19f338
    00007ffeebbeb2f8: 000000010db85dd8 000000010f19f980
    00007ffeebbeb308: 0000000003018980 000000010db85df0
    00007ffeebbeb318: 000000010dc2a6c8 000000010f19f948
    00007ffeebbeb328: 00000001054c3bd2 000000010f1bdc78
    00007ffeebbeb338: 0000000115c571f8 000000010dc2a6c8
    00007ffeebbeb348: 00000001060a051e 000000010f1bdc40
    00007ffeebbeb358: 00000001054c3bd2 0000000115c2fbb8
    00007ffeebbeb368: 0000000115c2bbf8 0000000115c2c288
    00007ffeebbeb378: 00000001060a0386 0000000115c12848
    00007ffeebbeb388: 0000000115c2fb48 000000010e8ef2e8
    00007ffeebbeb398: 0000000115c2bbf8 0000000115c2c288
    00007ffeebbeb3a8: 00000001063778ab 000000000000001a
    00007ffeebbeb3b8: 8000100315c054c0 000000010e462638
    00007ffeebbeb3c8: 000000010db85dd8 000000010f140b30
    00007ffeebbeb3d8: 0000000115c2c288 0000000115c2bbf8
    00007ffeebbeb3e8: 00000001159ee550 000000010c187000
    00007ffeebbeb3f8: 000000010c187000 00000001159ee550
    00007ffeebbeb408: 0000000115c0adf8 0000000115c0ada0
    00007ffeebbeb418: 0000000106c20d27 000000010dc58f70
    00007ffeebbeb428: 000000010dc25988 0000000115c0ada0
    00007ffeebbeb438: 0000000115c057b8 00000001159ee550
    00007ffeebbeb448: 0000000115c04ca8 000000011592b218
    00007ffeebbeb458: 0000000106c0e5f7 000000010dc58f70
    00007ffeebbeb468: 000000010dc25988 00000001159ec808
    00007ffeebbeb478: 0000000106bf97b4 000000010e463390
    00007ffeebbeb488: 000000010db6c6f0 000000011592b218
    00007ffeebbeb498: 000000010dc25988 00000001159ec808
    00007ffeebbeb4a8: 0000000106bfa9c4 0000000115c04ca8
    00007ffeebbeb4b8: 0000000115c05750 000000011592acf8
    00007ffeebbeb4c8: 0000000115c056c0 000000011592acf8
    00007ffeebbeb4d8: 000000010672e2c7 0000000009a7e6c0
    00007ffeebbeb4e8: 000000010ef45810 00000001159ec808
    00007ffeebbeb4f8: 0000000106bfa437 0000000115c04ca8
    00007ffeebbeb508: 00000001057a47e0 000000010ef45810
    00007ffeebbeb518: 000000010dbae710 000000010ef45810
    00007ffeebbeb528: 00000001159fdd88 00000000028114d8
    00007ffeebbeb538: 0000000009865808 00000001159ec808
    00007ffeebbeb548: 0000000106c0e1aa 00000001155a25e8
    00007ffeebbeb558: 0000000113558608 00000001159ec808
    00007ffeebbeb568: 000000010660eb35 00000001150a12e8
    00007ffeebbeb578: 00000001159ec808 00000001159ec808
    00007ffeebbeb588: 00000001066009a6 00000001159ec808
    00007ffeebbeb598: 000000010660d70d 00000001159faf08
    00007ffeebbeb5a8: 00000001155a2298 00000001159ec808
    00007ffeebbeb5b8: 00000001150a12e8 0000000113558258
    
  Stacktrace Stage0:
  
    
  Stacktrace Stage1:
  
    
  Full Stacktrace:
  
    
  [Native image heap boundaries: 
    ReadOnly Primitives: 0x10c187008 .. 0x10db5d4e0
    ReadOnly References: 0x10db5d4f8 .. 0x10eb9f940
    Writable Primitives: 0x10eba0000 .. 0x10ef2b4f8
    Writable References: 0x10ef2b518 .. 0x10fe84800]
  
  
  [Heap:
    [Young generation: 
      [youngSpace:
        aligned: 2088864/2 unaligned: 0/0
        aligned chunks:
          0x110000000 (0x110001030-0x110062508)
          0x113700000 (0x113701030-0x11370d8f0)]]
    [Old generation: 
      [fromSpace:
        aligned: 0/0 unaligned: 0/0]
      [toSpace:
        aligned: 0/0 unaligned: 0/0]
      [pinnedFromSpace:
        aligned: 0/0 unaligned: 0/0]
      [pinnedToSpace:
        aligned: 0/0 unaligned: 0/0]]
    [Unused:
      aligned: 0/0]]
  
  Use runtime option -R:-InstallSegfaultHandler if you don't want to use SubstrateSegfaultHandler.
  
  Bye bye ...
```

**Comment by cstancu** [comment]
What GraalVM version are you using? Yes, a reproducible example would help.

**Comment by aclement** [comment]
Sorry, this was "GraalVM Version 19.0.0 CE" on a mac. I'll work what I have into an example.

**Comment by cstancu** [comment]
Can you also try with [19.0.2 CE](https://github.com/oracle/graal/releases/tag/vm-19.0.2). We fixed several bugs in the meantime.

**Comment by aclement** [comment]
Seems to fail the same with 19.0.2 CE as well. Project is here: https://github.com/aclement/vanilla-orm
Should be able to clone and run `./compile.sh` to run native-image.

I will say the project isn't in perfect shape right now, I'm not even sure running the regular java version works (because what is in the unpack folder is a patched version of the originally built app to work around some other issues), but regardless it probably shouldn't crash like this once compiled, if anything I might be expecting another class not found issue. Thanks for taking a look.

**Comment by SergejIsbrecht** [comment]
On Linux it looks quite different

```
sergej@sergej-P50:~/Development/GitHub/vanilla-orm$ uname -a
Linux sergej-P50 4.18.0-22-generic #23-Ubuntu SMP Tue Jun 4 20:22:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Also Image-Generation taks a lot of time and memory (>16GiB) on my machine.

```
[orm:13581]     (clinit):   2,824.93 ms
[orm:13581]     universe:   6,576.86 ms
[orm:13581]      (parse):   7,637.23 ms
[orm:13581]     (inline):  10,800.87 ms
[orm:13581]    (compile):  44,788.15 ms
[orm:13581]      compile:  68,030.56 ms
[orm:13581]        image:   8,759.03 ms
[orm:13581]        write:   2,935.03 ms
[orm:13581]      [total]: 379,757.03 ms


Compiled app (orm)
Jun 22, 2019 10:26:04 AM com.fasterxml.jackson.databind.ext.Java7Support <clinit>
WARNING: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                        

Jun 22, 2019 10:26:04 AM org.springframework.boot.StartupInfoLogger logStarting
INFO: Starting SampleApplication on sergej-P50 with PID 13893 (started by sergej in /home/sergej/Development/GitHub/vanilla-orm)
Jun 22, 2019 10:26:04 AM org.springframework.boot.SpringApplication logStartupProfileInfo
INFO: No active profile set, falling back to default profiles: default
Jun 22, 2019 10:26:04 AM org.springframework.boot.SpringApplication reportFailure
SEVERE: Application run failed
java.lang.ExceptionInInitializerError
        at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:287)
        at java.lang.Class.ensureInitialized(DynamicHub.java:437)
        at org.springframework.context.annotation.ConfigurationClassEnhancer.newEnhancer(ConfigurationClassEnhancer.java:121)
        at org.springframework.context.annotation.ConfigurationClassEnhancer.enhance(ConfigurationClassEnhancer.java:109)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:429)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(ConfigurationClassPostProcessor.java:263)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:286)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:130)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:67)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:782)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:404)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:319)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1275)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1263)
        at app.main.SampleApplication.main(SampleApplication.java:53)
Caused by: java.lang.IllegalArgumentException: expecting exactly 1 method in interface org.springframework.cglib.proxy.Enhancer$EnhancerKey
        at org.springframework.cglib.core.ReflectUtils.findInterfaceMethod(ReflectUtils.java:473)
        at org.springframework.cglib.core.ReflectUtils.findNewInstance(ReflectUtils.java:366)
        at org.springframework.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:259)
        at org.springframework.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
        at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:358)
        at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:110)
        at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:108)
        at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
        at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
        at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:134)
        at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:319)
        at org.springframework.cglib.core.KeyFactory$Generator.create(KeyFactory.java:237)
        at org.springframework.cglib.core.KeyFactory.create(KeyFactory.java:184)
        at org.springframework.cglib.core.KeyFactory.create(KeyFactory.java:160)
        at org.springframework.cglib.proxy.Enhancer.<clinit>(Enhancer.java:104)
        at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:347)
        at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:267)
        ... 16 more

Command exited with non-zero status 1
0.06user 0.04system 0:00.23elapsed 48%CPU (0avgtext+0avgdata 93276maxresident)k
53728inputs+0outputs (185major+11071minor)pagefaults 0swaps

```

**Comment by aclement** [comment]
Let me try on linux too. The message you are getting there is something I might expect to see (as it is a work in progress) and I know how to address errors like that.

**Comment by aclement** [comment]
Blows up on linux for me too, similar error.

> takes a lot of time and memory (>16GiB) on my machine.
This is something I am interested in discussing at some point, are these times typical for an app this small, or am I likely doing something in the feature that really impacts the time/memory required. My other working sample apps using the same feature take a long time too.

**Comment by mbecca** [comment]
> 
> 
> On Linux it looks quite different
> 
> ```
> sergej@sergej-P50:~/Development/GitHub/vanilla-orm$ uname -a
> Linux sergej-P50 4.18.0-22-generic #23-Ubuntu SMP Tue Jun 4 20:22:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
> ```
> 
> Also Image-Generation taks a lot of time and memory (>16GiB) on my machine.
> 
> ```
> [orm:13581]     (clinit):   2,824.93 ms
> [orm:13581]     universe:   6,576.86 ms
> [orm:13581]      (parse):   7,637.23 ms
> [orm:13581]     (inline):  10,800.87 ms
> [orm:13581]    (compile):  44,788.15 ms
> [orm:13581]      compile:  68,030.56 ms
> [orm:13581]        image:   8,759.03 ms
> [orm:13581]        write:   2,935.03 ms
> [orm:13581]      [total]: 379,757.03 ms
> 
> 
> Compiled app (orm)
> Jun 22, 2019 10:26:04 AM com.fasterxml.jackson.databind.ext.Java7Support <clinit>
> WARNING: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
> 
>   .   ____          _            __ _ _
>  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
> ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
>  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
>   '  |____| .__|_| |_|_| |_\__, | / / / /
>  =========|_|==============|___/=/_/_/_/
>  :: Spring Boot ::                        
> 
> Jun 22, 2019 10:26:04 AM org.springframework.boot.StartupInfoLogger logStarting
> INFO: Starting SampleApplication on sergej-P50 with PID 13893 (started by sergej in /home/sergej/Development/GitHub/vanilla-orm)
> Jun 22, 2019 10:26:04 AM org.springframework.boot.SpringApplication logStartupProfileInfo
> INFO: No active profile set, falling back to default profiles: default
> Jun 22, 2019 10:26:04 AM org.springframework.boot.SpringApplication reportFailure
> SEVERE: Application run failed
> java.lang.ExceptionInInitializerError
>         at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:287)
>         at java.lang.Class.ensureInitialized(DynamicHub.java:437)
>         at org.springframework.context.annotation.ConfigurationClassEnhancer.newEnhancer(ConfigurationClassEnhancer.java:121)
>         at org.springframework.context.annotation.ConfigurationClassEnhancer.enhance(ConfigurationClassEnhancer.java:109)
>         at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:429)
>         at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(ConfigurationClassPostProcessor.java:263)
>         at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:286)
>         at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:130)
>         at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705)
>         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
>         at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:67)
>         at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:782)
>         at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:404)
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:319)
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1275)
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1263)
>         at app.main.SampleApplication.main(SampleApplication.java:53)
> Caused by: java.lang.IllegalArgumentException: expecting exactly 1 method in interface org.springframework.cglib.proxy.Enhancer$EnhancerKey
>         at org.springframework.cglib.core.ReflectUtils.findInterfaceMethod(ReflectUtils.java:473)
>         at org.springframework.cglib.core.ReflectUtils.findNewInstance(ReflectUtils.java:366)
>         at org.springframework.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:259)
>         at org.springframework.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
>         at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:358)
>         at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:110)
>         at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:108)
>         at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
>         at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
>         at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:134)
>         at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:319)
>         at org.springframework.cglib.core.KeyFactory$Generator.create(KeyFactory.java:237)
>         at org.springframework.cglib.core.KeyFactory.create(KeyFactory.java:184)
>         at org.springframework.cglib.core.KeyFactory.create(KeyFactory.java:160)
>         at org.springframework.cglib.proxy.Enhancer.<clinit>(Enhancer.java:104)
>         at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:347)
>         at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:267)
>         ... 16 more
> 
> Command exited with non-zero status 1
> 0.06user 0.04system 0:00.23elapsed 48%CPU (0avgtext+0avgdata 93276maxresident)k
> 53728inputs+0outputs (185major+11071minor)pagefaults 0swaps
> ```

Hello! I have the same error, using GraalVM Version 19.1.1 on Spring Boot application:


Aug 09, 2019 2:05:52 PM com.fasterxml.jackson.databind.ext.Java7Support <clinit>
--

**Comment by mbecca** [comment]
Hello,

Any progress on this?

Regards, M.

**Comment by thomaswue** [comment]
This is still failing with the same problem on the latest version and we can use the link to the repo to reproduce?

**Comment by aclement** [comment]
I think this has been resolved by other issues. I no longer see it. The sample that originally indicated the problem still doesn't work but I think due to configuration reasons rather than the original problem.

**Comment by cstancu** [comment]
Thank you for double checking @aclement .
