### ISSUE TITLE
[native-image][JDK11]: Class.getPackage() fails with NPE

### ISSUE THREAD

**Issue by qdeee** [oracle/graal#1428]
I'm trying to build my application using native-image on **JDK 11**, however it fails with NPE on Class.getPackage() call (jackson does this call during deserialization). 

Minimal example:
```(java)
public class PackageName {
	public static void main(String... args) {
		java.util.ArrayList.class.getPackage();
	}
}
```

```
$ javac PackageName.java
$ native-image --no-server --initialize-at-build-time --no-fallback PackageName
[packagename:660489]    classlist:   1,310.97 ms
[packagename:660489]        (cap):   1,316.51 ms
[packagename:660489]        setup:   2,740.61 ms
[packagename:660489]   (typeflow):   5,145.25 ms
[packagename:660489]    (objects):   4,782.91 ms
[packagename:660489]   (features):     426.35 ms
[packagename:660489]     analysis:  10,677.15 ms
[packagename:660489]     (clinit):     314.85 ms
[packagename:660489]     universe:     778.09 ms
[packagename:660489]      (parse):     833.35 ms
[packagename:660489]     (inline):   1,916.89 ms
[packagename:660489]    (compile):   6,485.74 ms
[packagename:660489]      compile:  10,197.46 ms
[packagename:660489]        image:   2,190.03 ms
[packagename:660489]        write:     219.86 ms
[packagename:660489]      [total]:  28,320.84 ms

$ ./packagename
Exception in thread "main" java.lang.NullPointerException
	at jdk.internal.loader.BootLoader.getDefinedPackage(BootLoader.java:178)
	at jdk.internal.loader.BootLoader.definePackage(BootLoader.java:170)
	at java.lang.Class.getPackage(DynamicHub.java:968)
	at PackageName.main(PackageName.java:3)
```

**OS**: Ubuntu 14.04
**JDK**: OpenJDK 11.0.3 (2019-04-16)
**Graal**: built from master (2019.06.24 09:28:21 commit c12f7791882bc393f7fa4446fe2e8308748bf5dd)

**Comment by cstancu** [comment]
Thank you for your report. This is a bug that seems to only happen for classes loaded via the boot class loader (e.g., all the `java.util` classes).

**Comment by dmlloyd** [comment]
https://github.com/mandrel/graal/issues/9
