### ISSUE TITLE
Spring boot WIth R integration buildEngine issue

### ISSUE THREAD

**Issue by akashchavda** [oracle/graal#1433]
I am new in R integration with Spring boot and i got below example for R integration with Spring boot,
`https://medium.com/graalvm/enhance-your-java-spring-application-with-r-data-science-b669a8c28bea`

I was follow all step from that link but at the end i got below exception
```
Caused by: java.lang.AbstractMethodError: org.graalvm.polyglot.impl.AbstractPolyglotImpl.buildEngine(Ljava/io/OutputStream;Ljava/io/OutputStream;Ljava/io/InputStream;Ljava/util/Map;JLjava/util/concurrent/TimeUnit;ZJZZLjava/util/logging/Handler;)Lorg/graalvm/polyglot/Engine;
	at org.graalvm.polyglot.Engine$Builder.build(Engine.java:413)
	at org.graalvm.polyglot.Context$Builder.build(Context.java:1014)
	at org.graalvm.demos.springr.SpringRApplication.getGraalVMContext(SpringRApplication.java:59)
	at org.graalvm.demos.springr.SpringRApplication$$EnhancerBySpringCGLIB$$692c7431.CGLIB$getGraalVMContext$1(<generated>)
	at org.graalvm.demos.springr.SpringRApplication$$EnhancerBySpringCGLIB$$692c7431$$FastClassBySpringCGLIB$$6ca16b56.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361)
	at org.graalvm.demos.springr.SpringRApplication$$EnhancerBySpringCGLIB$$692c7431.getGraalVMContext(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 52 more
```

I have just changed pom.xml 

```
<dependency>
     <groupId>org.graalvm</groupId>
     <artifactId>graal-sdk</artifactId>
     <version>1.0.0-rc6</version>
</dependency>
        
<dependency>
    <groupId>org.graalvm.js</groupId>
    <artifactId>js</artifactId>
    <version>1.0.0-rc10</version>
</dependency>
<dependency>
    <groupId>org.graalvm.js</groupId>
    <artifactId>js-scriptengine</artifactId>
    <version>1.0.0-rc10</version>
</dependency>
<dependency>
    <groupId>org.graalvm.truffle</groupId>
    <artifactId>truffle-api</artifactId>
    <version>1.0.0-rc10</version>
</dependency>
```

I have installed R also installed ggplot2 library successfully

let me know what is the solution for this issue?

**Comment by steve-s** [comment]
Hello akashchavda,

thank you for your interest in GaalVM R integration. Can you try setting the same version of all the artifacts, e.g. to rc10, like so:

```
<dependency>
     <groupId>org.graalvm</groupId>
     <artifactId>graal-sdk</artifactId>
     <version>1.0.0-rc10</version>
</dependency>

<dependency>
    <groupId>org.graalvm.js</groupId>
    <artifactId>js</artifactId>
    <version>1.0.0-rc10</version>
</dependency>
<dependency>
    <groupId>org.graalvm.js</groupId>
    <artifactId>js-scriptengine</artifactId>
    <version>1.0.0-rc10</version>
</dependency>
<dependency>
    <groupId>org.graalvm.truffle</groupId>
    <artifactId>truffle-api</artifactId>
    <version>1.0.0-rc10</version>
</dependency>
```

**Comment by akashchavda** [comment]
I have check it latest version of graal-sdk and its below
```
<dependency>
  <groupId>org.graalvm</groupId>
  <artifactId>graal-sdk</artifactId>
  <version>1.0.0-rc7</version>
</dependency>
```

`1.0.0-rc10` version is not found for `graal-sdk` .

**Comment by steve-s** [comment]
You will have to use different `groupId` because for later versions `graal-sdk` was moved to `org.graalvm.sdk`, so I think this should work:
```
<dependency>
     <groupId>org.graalvm.sdk</groupId>
     <artifactId>graal-sdk</artifactId>
     <version>1.0.0-rc10</version>
</dependency>

<dependency>
    <groupId>org.graalvm.js</groupId>
    <artifactId>js</artifactId>
    <version>1.0.0-rc10</version>
</dependency>
<dependency>
    <groupId>org.graalvm.js</groupId>
    <artifactId>js-scriptengine</artifactId>
    <version>1.0.0-rc10</version>
</dependency>
<dependency>
    <groupId>org.graalvm.truffle</groupId>
    <artifactId>truffle-api</artifactId>
    <version>1.0.0-rc10</version>
</dependency>
```
Furthermore, you can probably use the latest (`19.0.0`) version of all those components.

**Comment by akashchavda** [comment]
Yeah that `buildEngine` is not appear now but when i execute `mvn spring-boot:run` command then i got below exception

```
Caused by: org.graalvm.polyglot.PolyglotException: Error in library(ggplot2) : there is no package called ‘ggplot2’
	at <R>.stop(internal:1)
	at <R>.library:BLOCK0(unknown.r:1)
	at <R>.library(unknown.r:1)
	at <R>.<repl wrapper>(plot.R:1)
	at <R>.(plot.R:1)
	at org.graalvm.polyglot.Context.eval(Context.java:341)
	at org.graalvm.demos.springr.SpringRApplication.getPlotFunction(SpringRApplication.java:37)
	at org.graalvm.demos.springr.SpringRApplication$$EnhancerBySpringCGLIB$$7a6b2eab.CGLIB$getPlotFunction$0(<generated>)
	at org.graalvm.demos.springr.SpringRApplication$$EnhancerBySpringCGLIB$$7a6b2eab$$FastClassBySpringCGLIB$$1f3f9d31.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361)
	at org.graalvm.demos.springr.SpringRApplication$$EnhancerBySpringCGLIB$$7a6b2eab.getPlotFunction(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 38 more

```
I have check that `ggplot2` its already installed please see below

```
> library("ggplot2")
> packageVersion("ggplot2")
[1] ‘3.2.0’

```

But dont know why that `package not found` error showing.

**Comment by steve-s** [comment]
This almost looks like you installed `ggplot2` in your system `R`. You can install `ggplot2` with FastR by:
```
$GRAALVM_HOME/bin/R -e 'install.packages("ggplot2")'
```
make sure to use the `R` executable from GraalVM. When you are inside `R` REPL console, you can check which version of `R` in the welcome message or by printing the `R.version` global variable:
```
R version 3.5.1 (FastR)
Copyright (c) 2013-19, Oracle and/or its affiliates
Copyright (c) 1995-2018, The R Core Team
Copyright (c) 2018 The R Foundation for Statistical Computing
Copyright (c) 2012-4 Purdue University
Copyright (c) 1997-2002, Makoto Matsumoto and Takuji Nishimura
All rights reserved.

FastR is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information.

Type 'q()' to quit R.
> R.version
               _                               
platform       x86_64-unknown-linux-gnu        
arch           amd64                           
os             linux5.0.0-19-generic           
system         amd64, linux5.0.0-19-generic    
major          3                               
minor          5.1                             
year           2018                            
month          07                              
day            02                              
svn rev                                        
language       R                               
engine         FastR                           
version.string FastR version 3.5.1 (2018-07-02)
```

**Comment by akashchavda** [comment]
@steve-s  Thank you very much.. its now working properly..
