### ISSUE TITLE
[native-image] generated code is not position-independent

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#1443]
The generated code has text relocations, and some platforms (e.g. Android) do not allow shared libraries with text relocations.
Would it be possible to optionally generate position independent code (as if it was generated with -fpic)?

**Comment by bobmcwhirter** [comment]
There are some codepaths that check for a PIC config flag. Dunno exactly how consistently or how you actually set it.

**Comment by vjovanov** [comment]
Have you executed the image build with `--static`? We have calls to C functions that will use relocations.

**Comment by johanvos** [comment]
reproducable test:
```
mx native-image -H:TempDirectory=tmp HelloWorld
gcc -o libhello.so --shared  tmp/SVM-1564138267168/helloworld.o
scanelf -qT libhello.so 

Resulting output:

scanelf: scanelf_file_textrels(): ELF libhello.so has TEXTREL markings but doesnt appear to have any real TEXTREL's !?
  libhello.so
```

**Comment by vjovanov** [comment]
Is this fixed?

**Comment by manuel-alvarez-alvarez** [comment]
Dear all,

It seems that native-image is still generating non position independent code.

We are trying to build a shared library that can be compressed later on by UPX (https://upx.github.io/) and it requires that there are no text relocations.

When running `native-image -H:+TraceNativeToolUsage -H:NativeLinkerOption=-Wl,--warn-shared-textrel --shared` the linker complains about some relocations `warning: relocation in read-only section '.svm_heap'`.

If we try to use the flag `-H:+GeneratePIC` the native-image command fails with lots of exceptions like the following:
```
 Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.oracle.svm.core.code.IsolateEnterStub.JNIInvocationInterface_AttachCurrentThreadAsDaemon_d1dce4d04352e910ee4dbda42768c5c580f6b066
(com.oracle.svm.jni.nativeapi.JNIJavaVM, com.oracle.svm.jni.nativeapi.JNIEnvironmentPointer, com.oracle.svm.jni.nativeapi.JNIJavaVMAttachArgs)
 Parsing context: <no parsing context available>

   at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:126)
   at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:311)
   at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureTypeFlowCreated(MethodTypeFlow.java:282)
   at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
   at com.oracle.graal.pointsto.BigBang$1.run(BigBang.java:413)
   at com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:188)
   at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:172)
   at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
   at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
   at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
   at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
   at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
   at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
 Caused by: com.oracle.svm.core.util.VMError$HostedError: Unexpected control flow structure after CEntryPointLeaveNode. Disallowed node 35|Deopt in method com.oracle.svm.core.code.IsolateEnterStub.JNIInvocationInterface_AttachCurrentThre
adAsDaemon_d1dce4d04352e910ee4dbda42768c5c580f6b066(JNIJavaVM, JNIEnvironmentPointer, JNIJavaVMAttachArgs)
   at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
   at com.oracle.svm.core.graal.nodes.CEntryPointLeaveNode.collectReturns(CEntryPointLeaveNode.java:180)
   at com.oracle.svm.core.graal.nodes.CEntryPointLeaveNode.collectReturns(CEntryPointLeaveNode.java:173)
   at com.oracle.svm.core.graal.nodes.CEntryPointLeaveNode.anchorReturnValue(CEntryPointLeaveNode.java:144)
   at com.oracle.svm.core.graal.nodes.CEntryPointLeaveNode.simplify(CEntryPointLeaveNode.java:114)
   at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.tryCanonicalize(CanonicalizerPhase.java:437)
   at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.processNode(CanonicalizerPhase.java:348)
   at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.processWorkSet(CanonicalizerPhase.java:325)
   at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.run(CanonicalizerPhase.java:284)
   at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase.run(CanonicalizerPhase.java:194)
   at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase.run(CanonicalizerPhase.java:75)
   at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
   at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
   at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:182)
   at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:321)
   at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:293)
   ... 11 more
```

I've created a small project showcasing the issue [https://github.com/manuel-alvarez-alvarez/graal-shared-library](https://github.com/manuel-alvarez-alvarez/graal-shared-library) 

Is this issue still active? Any help will be greatly appreciated, thanks!

**Comment by christianwimmer** [comment]
`GeneratePIC` is an option that comes from the Graal compiler. It certainly does not do anything useful when applied to native image.

Relocations are certainly needed in the image heap. That is not really a text section, it is a data section. But parts of the image heap are known to be read only, so it is good practice to mark it as read only too in the section table.

**Comment by MicroGery** [comment]
@olpaw @christianwimmer  I cannot find `-H:±GeneratePIC ` in the latest version of native-image --expert-options-all. Does it because graalvm has decided not to support pic？
