### ISSUE TITLE
[native-image] --enable-all-security-services crashes on EE 19.0.2

### ISSUE THREAD

**Issue by JulienNevo** [oracle/graal#1444]
Compiling the simplest HelloWorld class crashes if --enable-all-security-services is used, version 19.0.2 but **only** on EE (on CE, it works fine).

`native-image HelloWorld --enable-all-security-services`

The log:
```
Build on Server(pid: 13200, port: 39293)
[helloworld:13200]    classlist:     433.57 ms
[helloworld:13200]        (cap):   1,386.83 ms
[helloworld:13200]        setup:   2,333.67 ms
Fatal error: java.lang.NullPointerException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:458)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:292)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:430)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.executeCompilation(NativeImageBuildServer.java:390)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$processCommand$8(NativeImageBuildServer.java:327)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.withJVMContext(NativeImageBuildServer.java:408)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.processCommand(NativeImageBuildServer.java:324)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.processRequest(NativeImageBuildServer.java:268)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$serve$7(NativeImageBuildServer.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
	at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38)
	at java.lang.reflect.Field.get(Field.java:393)
	at com.oracle.svm.hosted.SecurityServicesFeature.lambda$getConsParamClassAccessor$0(SecurityServicesFeature.java:241)
	at com.oracle.svm.hosted.SecurityServicesFeature.register(SecurityServicesFeature.java:281)
	at com.oracle.svm.hosted.SecurityServicesFeature.beforeAnalysis(SecurityServicesFeature.java:175)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$7(NativeImageGenerator.java:667)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:64)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:667)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:523)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:441)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1

```

**Comment by cstancu** [comment]
@JulienNevo I cannot replicate the reported issue with either 19.0.2 EE or latest master. It is also surprising that the issue is on EE but not CE since there is no difference between the two versions when it comes to the supported security services. Did you download 19.0.2 EE from https://www.oracle.com/technetwork/graalvm/downloads/index.html and installed the native-image component via `./gu install native-image`?

**Comment by cstancu** [comment]
By the way, it turns out that due to a bug in `gu` running `./gu install native-image` in a GraalVM EE distribution will bring in the CE Native Image: `Downloading: Component native-image: Native Image  from github.com`. You need to manually download the `Oracle GraalVM Enterprise Edition Native Image Early Adopter` from [OTN](https://www.oracle.com/technetwork/graalvm/downloads/index.html) and install it via `./gu install -L native-image-installable-svm-svmee-linux-amd64-19.0.2.jar`. However, I still cannot replicate the issue that you reported. What does your HelloWorld contain?

**Comment by JulienNevo** [comment]
Indeed I downloaded the "Oracle GraalVM Enterprise Edition based on JDK8 for Linux (19.0.2)" from your link, and installed Native Image via GU. I did the same from the CE version, which I downloaded [here](https://github.com/oracle/graal/releases) (graalvm-ce-linux-amd64-19.0.2.tar.gz).

My hello world is as simple as can be:
`public class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}`

**Comment by cstancu** [comment]
@JulienNevo I am going to close this issue as I still cannot reproduce it. If it still a problem please reopen and provide the updated stack trace and the output of `native-image --verbose`. Thanks!

**Comment by jaikiran** [comment]
@cstancu, just a FYI - this NPE that's reported in this issue is the same as the one we are fixing in https://github.com/oracle/graal/pull/1893. I had vaguely remembered seeing that NPE before in the issue tracker, so I just did a search today and found this one.
