### ISSUE TITLE
native-image failed on ojdbc8 jar

### ISSUE THREAD

**Issue by rosstang2565** [oracle/graal#1454]
GraalVM's limitation?
Oracle database driver don't support GraalVM?

````
----------------------------------------------------------------------------------------------------------
./graalvm/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager --allow-incomplete-classpath -H:IncludeResources=.*.properties|.*META-INF/persistence.xml|.*.xsd --report-unsupported-elements-at-runtime -H:ClassInitialization=oracle.net.nt.TimeoutInterruptHandler:run_time,oracle.jdbc.driver.BlockSource:run_time --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar om-rest-quarkus-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:-SpawnIsolates -H:+JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace
...
Error: Unsupported features in 2 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option -H:ClassInitialization=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: 
	at parsing oracle.jdbc.driver.BlockSource$ThreadedCachingBlockSource$BlockReleaser.access$100(BlockSource.java:289)
Call path from entry point to oracle.jdbc.driver.BlockSource$ThreadedCachingBlockSource$BlockReleaser.access$100(): 
	at oracle.jdbc.driver.BlockSource$ThreadedCachingBlockSource$BlockReleaser.access$100(BlockSource.java:289)
	at oracle.jdbc.driver.BlockSource$ThreadedCachingBlockSource.stopBlockReleaserThread(BlockSource.java:282)
	at oracle.jdbc.driver.OracleDriver.deregister(OracleDriver.java:520)
	at oracle.jdbc.driver.OracleDriver$$Lambda$186/1875146103.deregister(Unknown Source)
	at java.sql.DriverManager.deregisterDriver(DriverManager.java:414)
	at oracle.jdbc.driver.OracleDriver$2.run(OracleDriver.java:643)
	at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:83)
	at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:396)
	at java.util.logging.LogManager.access$800(LogManager.java:145)
	at java.util.logging.LogManager$2.run(LogManager.java:345)
	at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:63)
	at sun.nio.ch.Util.atBugLevel(Util.java:478)
	at sun.nio.ch.SelectorImpl.selectedKeys(SelectorImpl.java:73)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:567)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
--------------------------------------------------------------------------------------------
-- WARNING: The above stack trace is not a real stack trace, it is a theoretical call tree---
-- If an interface has multiple implementations SVM will just display one potential call  ---
-- path to the interface. This is often meaningless, and what you actually need to know is---
-- the path to the constructor of the object that implements this interface.              ---
-- Quarkus has attempted to generate a more meaningful call flow analysis below          ---
---------------------------------------------------------------------------------------------
```

**Comment by codecr** [comment]
I've the same issue. Is there any update?

**Comment by cstancu** [comment]
Please use [these instructions](https://github.com/oracle/graal/issues/1748#issuecomment-542353582) to build an ojdbc8 image.
