### ISSUE TITLE
FrameWithoutBoxing should not be materialized errors

### ISSUE THREAD

**Issue by smokeelow** [oracle/graal#1463]
I updated GraalVM from 19 to 19.1, and now I see the following errors during the high load test, but they only appear once

`Reason org.graalvm.compiler.code.SourceStackTraceBailoutException$1: Object of type Lorg/graalvm/compiler/truffle/runtime/FrameWithoutBoxing; should not be materialized (must not pass virtual object into an invoke that cannot be inlined): 
org.graalvm.compiler.code.SourceStackTraceBailoutException$1: Object of type Lorg/graalvm/compiler/truffle/runtime/FrameWithoutBoxing; should not be materialized (must not pass virtual object into an invoke that cannot be inlined):
	at com.oracle.truffle.js.nodes.instrumentation.DeclareTagProvider$MaterializedFunctionBodyNode.execute(DeclareTagProvider.java:142)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:48)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:147)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:93)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:328)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:318)
Caused by: org.graalvm.compiler.graph.VerificationError: Object of type Lorg/graalvm/compiler/truffle/runtime/FrameWithoutBoxing; should not be materialized (must not pass virtual object into an invoke that cannot be inlined):
	at org.graalvm.compiler.nodes.virtual.EnsureVirtualizedNode.ensureVirtualFailure(EnsureVirtualizedNode.java:98)
	at org.graalvm.compiler.nodes.virtual.CommitAllocationNode.lower(CommitAllocationNode.java:117)
	at org.graalvm.compiler.phases.common.LoweringPhase$Round.process(LoweringPhase.java:475)
	at org.graalvm.compiler.phases.common.LoweringPhase$Round.access$200(LoweringPhase.java:351)
	at org.graalvm.compiler.phases.common.LoweringPhase$Round$ProcessFrame.preprocess(LoweringPhase.java:415)
	at org.graalvm.compiler.phases.common.LoweringPhase.processBlock(LoweringPhase.java:574)
	at org.graalvm.compiler.phases.common.LoweringPhase$Round.run(LoweringPhase.java:400)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:209)
	at org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:56)
	at org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:38)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.phases.common.LoweringPhase.lower(LoweringPhase.java:271)
	at org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:264)
	at org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:94)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:209)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:220)
	at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:144)
	at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:129)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compilePEGraph(TruffleCompilerImpl.java:521)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compileAST(TruffleCompilerImpl.java:455)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:624)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:571)
	at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:178)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.doCompile(TruffleCompilerImpl.java:280)
	at org.graalvm.compiler.truffle.compiler.hotspot.libgraal.HotSpotToSVMEntryPoints.doCompile(HotSpotToSVMEntryPoints.java:251)`

log file attached [graal-19.1-errors.log](https://github.com/oracle/graal/files/3356838/graal-19.1-errors.log)

**Comment by woess** [comment]
Thanks for the report! This bug will be fixed in GraalVM 19.2.0.
