### ISSUE TITLE
Option name "DynamicProxyConfigurationFiles" has multiple definitions

### ISSUE THREAD

**Issue by javadimon** [oracle/graal#1475]
GRAAL 19.1.0 
Native image fail

$JAVA_HOME/bin/native-image -jar shop-1.0-SNAPSHOT-jar-with-dependencies.jar 
Build on Server(pid: 15366, port: 40643)
Fatal error: com.oracle.svm.core.util.VMError$HostedError: Option name "DynamicProxyConfigurationFiles" has multiple definitions: com.oracle.svm.core.configure.ConfigurationFiles$Options.DynamicProxyConfigurationFiles and com.oracle.svm.reflect.proxy.hosted.DynamicProxyFeature$Options.DynamicProxyConfigurationFiles
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:66)
	at com.oracle.svm.hosted.option.HostedOptionParser.collectOptions(HostedOptionParser.java:88)
	at com.oracle.svm.hosted.option.HostedOptionParser.<init>(HostedOptionParser.java:61)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:203)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:446)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.executeCompilation(NativeImageBuildServer.java:394)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$processCommand$8(NativeImageBuildServer.java:331)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.withJVMContext(NativeImageBuildServer.java:412)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.processCommand(NativeImageBuildServer.java:328)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.processRequest(NativeImageBuildServer.java:272)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$serve$7(NativeImageBuildServer.java:232)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Error: Image build request failed with exit status 1

**Comment by cstancu** [comment]
Do you have a compile time dependency on `svm` packages, i.e., for substitutions? Then you should make sure those dependencies are also from 19.1.0.

**Comment by javadimon** [comment]
Thanks for response!
Yes I used https://mvnrepository.com/artifact/com.oracle.substratevm/native-image-maven-plugin
But last version native-image-maven-plugin only 19.0.2

**Comment by olpaw** [comment]
native-image-maven-plugin 19.1.0 is available since 01-Jul-2019
https://search.maven.org/search?q=native-image-maven-plugin
