### ISSUE TITLE
Start Tomcat in Spring Boot use GraalVM 19.1.0 got errors : java.lang.ClassLoader.registerAsParallelCapable() Not support

### ISSUE THREAD

**Issue by guanchao-yang** [oracle/graal#1477]
Start Tomcat in Spring Boot use GraalVM 19.1.0 got errors below:

```
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:155) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[na:na]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) ~[na:na]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) ~[na:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[na:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1231) ~[na:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1220) ~[na:na]
        at com.alipay.sofa.tomcat.SOFABootWebApplication.main(SOFABootWebApplication.java:25) ~[na:na]
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:126) ~[na:na]
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:88) ~[na:na]
        at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:432) ~[na:na]
        at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:189) ~[na:na]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:179) ~[na:na]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:152) ~[na:na]
        ... 8 common frames omitted
Caused by: org.apache.catalina.LifecycleException: null
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:928) ~[na:na]
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262) ~[na:na]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[na:na]
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421) ~[na:na]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[na:na]
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:932) ~[na:na]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[na:na]
        at org.apache.catalina.startup.Tomcat.start(Tomcat.java:456) ~[na:na]
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:107) ~[na:na]
        ... 13 common frames omitted
Caused by: java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:na]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:na]
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916) ~[na:na]
        ... 21 common frames omitted
Caused by: org.apache.catalina.LifecycleException: null
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:928) ~[na:na]
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841) ~[na:na]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[na:na]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) ~[na:na]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) ~[na:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:na]
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[na:na]
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) ~[na:na]
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) ~[na:na]
        ... 21 common frames omitted
Caused by: java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:na]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:na]
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916) ~[na:na]
        ... 29 common frames omitted
Caused by: org.apache.catalina.LifecycleException: null
        at org.apache.catalina.loader.WebappLoader.startInternal(WebappLoader.java:413) ~[na:na]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[na:na]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4994) ~[na:na]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[na:na]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) ~[na:na]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) ~[na:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:na]
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[na:na]
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) ~[na:na]
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) ~[na:na]
        ... 29 common frames omitted
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported method java.lang.ClassLoader.registerAsParallelCapable() is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:102) ~[na:na]
        at java.lang.ClassLoader.registerAsParallelCapable(Target_java_lang_ClassLoader.java:1204) ~[na:na]
        at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader.<clinit>(TomcatEmbeddedWebappClassLoader.java:42) ~[na:na]
        at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350) ~[na:na]
        at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270) ~[na:na]
        at java.lang.Class.ensureInitialized(DynamicHub.java:451) ~[na:na]
        at com.oracle.svm.core.hub.ClassForNameSupport.forNameOrNull(ClassForNameSupport.java:52) ~[na:na]
        at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:58) ~[na:na]
        at java.lang.Class.forName(DynamicHub.java:1145) ~[na:na]
        at org.apache.catalina.loader.WebappLoader.createClassLoader(WebappLoader.java:503) ~[na:na]
        at org.apache.catalina.loader.WebappLoader.startInternal(WebappLoader.java:389) ~[na:na]
        ... 38 common frames omitted

```

**Comment by guanchao-yang** [comment]
```
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported method java.lang.ClassLoader.registerAsParallelCapable() is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
```

**Comment by guanchao-yang** [comment]
```
om.oracle.svm.core.jdk.UnsupportedFeatureError: Target_java_lang_ClassLoader.getClassLoadingLock(String)
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:102)
        at java.lang.ClassLoader.getClassLoadingLock(Target_java_lang_ClassLoader.java:197)
        at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader.loadClass(TomcatEmbeddedWebappClassLoader.java:64)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188)
        at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:540)
        at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:521)
        at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:150)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4604)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5143)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:932)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Tomcat.start(Tomcat.java:456)
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:107)
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:88)
        at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:432)
        at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:189)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:179)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:152)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1231)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1220)
        at com.alipay.sofa.tomcat.SOFABootWebApplication.main(SOFABootWebApplication.java:25)
```

**Comment by starkgate** [comment]
Same problem here with jetty:

```
./start
com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported method java.lang.ClassLoader.registerAsParallelCapable() is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:102)
	at java.lang.ClassLoader.registerAsParallelCapable(Target_java_lang_ClassLoader.java:1197)
	at org.eclipse.jetty.start.Classpath$Loader.<clinit>(Classpath.java:41)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	at java.lang.Class.ensureInitialized(DynamicHub.java:467)
	at org.eclipse.jetty.start.Classpath.getClassLoader(Classpath.java:159)
	at org.eclipse.jetty.start.Main.start(Main.java:485)
	at org.eclipse.jetty.start.Main.main(Main.java:77)
```

**Comment by cstancu** [comment]
The class loader support has been refactored and we don't replace the entire `java.lang.ClassLoader` class anymore. The reported stack traces are not relevant anymore.
