### ISSUE TITLE
Just faced a Unimplemented exception

### ISSUE THREAD

**Issue by pmlopes** [oracle/graal#1488]
```
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Unimplemented: sun.nio.ch.DatagramChannelImpl.send0(boolean, FileDescriptor, long, int, InetAddress, int)
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:102)
        at sun.nio.ch.DatagramChannelImpl.send0(DatagramChannelImpl.java:114)
        at sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:521)
        at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:483)
        at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:462)
        at io.netty.channel.socket.nio.NioDatagramChannel.doWriteMessage(NioDatagramChannel.java:293)
        at io.netty.channel.nio.AbstractNioMessageChannel.doWrite(AbstractNioMessageChannel.java:142)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:939)
        ... 31 more
```

Use case, trying to use a datagram channel with netty.

**Comment by dmlloyd** [comment]
This was fixed by 4c4ca8235de8a6fe4b0f434fd511a908e346bad9 in #1425.
