### ISSUE TITLE
java.lang.UnsatisfiedLinkError: sun.security.ec.ECKeyPairGenerator.generateECKeyPair

### ISSUE THREAD

**Issue by hgeraldino** [oracle/graal#1489]
```
/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/bin/java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-20190523183630.graal2.jdk8u-src-tar-gz-b03)
OpenJDK 64-Bit GraalVM CE 19.1.0 (build 25.212-b03-jvmci-20-b04, mixed mode)
```

I wrote a small java application (using micronaut) and created a native image. When running the native image it fails with:

```
21:46:20.975 [pool-2-thread-1] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: sun.security.ec.ECKeyPairGenerator.generateECKeyPair(I[B[B)[Ljava/lang/Object; [symbol: Java_sun_security_ec_ECKeyPairGenerator_generateECKeyPair or Java_sun_security_ec_ECKeyPairGenerator_generateECKeyPair__I_3B_3B]
java.lang.UnsatisfiedLinkError: sun.security.ec.ECKeyPairGenerator.generateECKeyPair(I[B[B)[Ljava/lang/Object; [symbol: Java_sun_security_ec_ECKeyPairGenerator_generateECKeyPair or Java_sun_security_ec_ECKeyPairGenerator_generateECKeyPair__I_3B_3B]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
	at sun.security.ec.ECKeyPairGenerator.generateECKeyPair(ECKeyPairGenerator.java)
	at sun.security.ec.ECKeyPairGenerator.generateKeyPair(ECKeyPairGenerator.java:128)
	at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:703)
	at java.security.KeyPairGenerator.genKeyPair(KeyPairGenerator.java:470)
	at example.micronaut.KeyGeneratorController.newKey(KeyGeneratorController.java:26)
	at example.micronaut.$KeyGeneratorControllerDefinition$$exec1.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:144)
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2711)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:236)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:122)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$17(RoutingInBoundHandler.java:1360)
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14755)
	at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:52)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52)
	at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:52)
	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
	at io.reactivex.Flowable.subscribe(Flowable.java:14805)
	at io.reactivex.Flowable.subscribe(Flowable.java:14752)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

The app is rather simple: it uses a java.security.KeyPairGenerator instance to generate a Public/Private KeyPair. The sample project can be found at: https://github.com/hgeraldino/micronaut-graalvm-keygenerator.git

I tried adding the ECKeyPairGenerator class to the [JNI configuration](https://github.com/hgeraldino/micronaut-graalvm-keygenerator/blob/master/src/main/resources/reflect.json) without success. Issue feels similar to #1267 

To build the project (using maven 3.6):
```
$ mvn clean package
...
$ native-image --no-server --verbose -cp target/complete-0.1.jar 
Apply jar:file:///Users/hgeraldino/playground/complete/target/complete-0.1.jar!/META-INF/native-image/io.micronaut.http/mime-types/native-image.properties
Apply jar:file:///Users/hgeraldino/playground/complete/target/complete-0.1.jar!/META-INF/native-image/io.micronaut/runtime-graal/native-image.properties
Apply jar:file:///Users/hgeraldino/playground/complete/target/complete-0.1.jar!/META-INF/native-image/io.micronaut/health/native-image.properties
Apply jar:file:///Users/hgeraldino/playground/complete/target/complete-0.1.jar!/META-INF/native-image/io.micronaut/http/native-image.properties
Apply jar:file:///Users/hgeraldino/playground/complete/target/complete-0.1.jar!/META-INF/native-image/io.micronaut/inject/native-image.properties
Apply jar:file:///Users/hgeraldino/playground/complete/target/complete-0.1.jar!/META-INF/native-image/io.micronaut/netty/native-image.properties
Apply jar:file:///Users/hgeraldino/playground/complete/target/complete-0.1.jar!/META-INF/native-image/io.micronaut/http-netty-channel/native-image.properties
Apply jar:file:///Users/hgeraldino/playground/complete/target/complete-0.1.jar!/META-INF/native-image/example.micronaut/complete-application/native-image.properties
Apply jar:file:///Users/hgeraldino/playground/complete/target/complete-0.1.jar!/META-INF/native-image/example/micronaut/native-image.properties
Executing [
/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/bin/java \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-d64 \
-XX:-UseJVMCIClassLoader \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx13743895344 \
-Duser.country=US \
-Duser.language=en \
-Dorg.graalvm.version=19.1.0 \
-Dorg.graalvm.config=CE \
-Dcom.oracle.graalvm.isaot=true \
-Djvmci.class.path.append=/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/jvmci/graal.jar \
-Xbootclasspath/a:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/boot/graaljs-scriptengine.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/boot/graal-sdk.jar \
-cp \
/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/svm/builder/llvm-wrapper.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/svm/builder/svm.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/svm/builder/javacpp.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/svm/builder/objectfile.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/svm/builder/graal-llvm.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/svm/builder/svm-llvm.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/svm/builder/llvm-platform-specific.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/svm/builder/pointsto.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/jvmci/graal.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/jvmci/graal-management.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/jvmci/jvmci-api.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/jvmci/jvmci-hotspot.jar \
com.oracle.svm.hosted.NativeImageGeneratorRunner \
-imagecp \
/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/boot/graaljs-scriptengine.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/boot/graal-sdk.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/svm/builder/llvm-wrapper.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/svm/builder/svm.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/svm/builder/javacpp.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/svm/builder/objectfile.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/svm/builder/graal-llvm.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/svm/builder/svm-llvm.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/svm/builder/llvm-platform-specific.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/svm/builder/pointsto.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/jvmci/graal.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/jvmci/graal-management.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/jvmci/jvmci-api.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/jvmci/jvmci-hotspot.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/svm/library-support.jar:/Users/hgeraldino/playground/complete/target/complete-0.1.jar \
-H:Path=/Users/hgeraldino/playground/complete \
-H:IncludeResources=META-INF/http/mime.types \
-H:ClassInitialization=io.micronaut.reactive.reactor.ReactorInstrumentation:run_time \
-H:ClassInitialization=ch.qos.logback:build_time,com.fasterxml.jackson:build_time,io.micronaut:build_time,io.reactivex:build_time,org.reactivestreams:build_time,org.slf4j:build_time,org.yaml.snakeyaml:build_time,javax:build_time \
-H:ReflectionConfigurationResources=META-INF/native-image/io.micronaut/health/reflection-config.json \
-H:ReflectionConfigurationResources=META-INF/native-image/io.micronaut/http/reflection-config.json \
-H:+ReportUnsupportedElementsAtRuntime \
-H:+AllowIncompleteClasspath \
-H:ClassInitialization=io.netty.handler.codec.http.HttpObjectEncoder:run_time,io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder:run_time,io.netty.handler.ssl.util.ThreadLocalInsecureRandom:run_time,com.sun.jndi.dns.DnsClient:run_time,io.netty.handler.ssl.ConscryptAlpnSslEngine:run_time,io.netty.handler.ssl.JettyNpnSslEngine:run_time,io.netty.handler.ssl.ReferenceCountedOpenSslEngine:run_time,io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator:run_time,io.netty.handler.ssl.ReferenceCountedOpenSslServerContext:run_time,io.netty.handler.ssl.ReferenceCountedOpenSslClientContext:run_time,io.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator:run_time \
-H:ClassInitialization=io.netty:build_time \
-H:EnableURLProtocols=http,https \
-H:ReflectionConfigurationResources=META-INF/native-image/io.micronaut/http-netty-channel/reflection-config.json \
-H:IncludeResources=logback.xml|application.yml|bootstrap.yml \
-H:Name=complete \
-H:Class=example.micronaut.Application \
-H:ReflectionConfigurationResources=META-INF/native-image/example/micronaut/reflection-config.json \
-H:CLibraryPath=/Library/Java/JavaVirtualMachines/graalvm-ce-19.1.0/Contents/Home/jre/lib/svm/clibraries/darwin-amd64 \
-H:ReflectionConfigurationFiles=/Users/hgeraldino/playground/complete/target/classes/reflect.json
]
[complete:2380]    classlist:   4,315.84 ms
[complete:2380]        (cap):   1,258.66 ms
[complete:2380]        setup:   2,808.05 ms
[complete:2380]   (typeflow):  21,729.66 ms
[complete:2380]    (objects):  15,752.65 ms
[complete:2380]   (features):   2,252.65 ms
[complete:2380]     analysis:  42,354.47 ms
[complete:2380]     (clinit):     900.08 ms
[complete:2380]     universe:   2,310.17 ms
[complete:2380]      (parse):   2,859.30 ms
[complete:2380]     (inline):   4,848.99 ms
[complete:2380]    (compile):  31,801.08 ms
[complete:2380]      compile:  41,970.22 ms
[complete:2380]        image:   3,718.06 ms
[complete:2380]        write:   1,274.25 ms
[complete:2380]      [total]:  99,102.55 ms
```
After launching the process (```./complete```), making an HTTP GET to the endpoint throws the exception:
```
$ curl http://localhost:8080/keygen/new
```

**Comment by cstancu** [comment]
The JCA security services need to be enabled via: [`--enable-all-security-services`](https://github.com/oracle/graal/blob/master/substratevm/JCA-SECURITY-SERVICES.md#jca-security-services-on-substrate-vml)

**Comment by hgeraldino** [comment]
Hi Codrut,

Micronaut is enabling the https URL protocol for this microservice, so security services should be enabled as per the docs. I recreated the image with the `--enable-all-security-services` arg but the result was the same.

 Thanks for looking into this.

**Comment by yschimke** [comment]
There is a similar error when trying to use the ECC ciphers, fixed with including the SunEC lib.  I don't know if this is the same.

-Djava.library.path=$JAVA_HOME/lib/

https://github.com/oracle/graal/issues/1336

**Comment by cstancu** [comment]
`sunec` is now statically included in the image when code that requires it is reachable.
