### ISSUE TITLE
Fallback image generation fails when working dir and input file are on different partitions (Windows)

### ISSUE THREAD

**Issue by GermanCoding** [oracle/graal#1514]
**Steps to reproduce:**

1. On Windows, open a terminal
2. Navigate to a directory, let's say `C:\example1`
3. Execute `native-image -jar D:\example2\input.jar` with a file that requires a fallback build. _Note that the working directory is on **C** and the input file is on **D**._

**Result:** Building fails entirely with the following exception:
```
Exception in thread "main" java.lang.IllegalArgumentException: 'other' has different root
        at sun.nio.fs.WindowsPath.relativize(WindowsPath.java:392)
        at sun.nio.fs.WindowsPath.relativize(WindowsPath.java:44)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at com.oracle.svm.driver.NativeImage.createFallbackBuildArgs(NativeImage.java:539)
        at com.oracle.svm.driver.NativeImage.access$000(NativeImage.java:89)
        at com.oracle.svm.driver.NativeImage$FallbackBuildConfiguration.<init>(NativeImage.java:558)
        at com.oracle.svm.driver.NativeImage$FallbackBuildConfiguration.create(NativeImage.java:562)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1178)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1145)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1104)
```

If working in directories which are on the same drive/partition, it works as expected.

GraalVM version: 19.1.1
OS: Windows 10

**Comment by helpermethod** [comment]
Still no progress on this issue? This is quite a blocker on Windows Server Github runners :/.

**Comment by wirthi** [comment]
Can you please help us understand why you are using the `fallback-image` feature in the first place? That does not sound like a usecase.

**Comment by lost22git** [comment]
same problem
