### ISSUE TITLE
[native-image] regression: got false error during compilation to binaries

### ISSUE THREAD

**Issue by plokhotnyuk** [oracle/graal#1515]
It worked for some earlier releases of GraalVM, see: https://gitter.im/graalvm/native-image?at=5b6765fa6d45752f98937ad9

Now with GraalVM CE 19.1.0 I got the following compilation error:
```
Caused by: com.oracle.svm.hosted.analysis.flow.SVMMethodTypeFlowBuilder$UnsafeOffsetError: Field AnalysisField<UnsafeUtils.STRING_CODER_OFFSET accessed: false reads: true written: false> is used as an offset in an unsafe operation, but no value recomputation found.
 Wrapped field: HotSpotResolvedJavaFieldImpl<com.github.plokhotnyuk.jsoniter_scala.core.UnsafeUtils.STRING_CODER_OFFSET long:112>
 Location: at com.github.plokhotnyuk.jsoniter_scala.core.UnsafeUtils.getLatin1Array(UnsafeUtils.java:34) [bci: 16]
	at com.oracle.svm.hosted.analysis.flow.SVMMethodTypeFlowBuilder$UnsafeOffsetError.report(SVMMethodTypeFlowBuilder.java:119)
	at com.oracle.svm.hosted.analysis.flow.SVMMethodTypeFlowBuilder.checkUnsafeOffset(SVMMethodTypeFlowBuilder.java:161)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder$NodeIterator.node(MethodTypeFlowBuilder.java:1029)
	at org.graalvm.compiler.phases.graph.PostOrderNodeIterator.apply(PostOrderNodeIterator.java:106)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:421)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	... 10 more
```
Sources of UnsafeUtils.java:
```
import java.lang.reflect.Field;

public class UnsafeUtils {
    private static final sun.misc.Unsafe UNSAFE;
    private static final long STRING_CODER_OFFSET;
    private static final long STRING_VALUE_OFFSET;

    static {
        sun.misc.Unsafe u = null;
        long sco = 0, svo = 0;
        try {
            Field f = sun.misc.Unsafe.class.getDeclaredField("theUnsafe");
            f.setAccessible(true);
            u = (sun.misc.Unsafe) f.get(null);
        } catch (Throwable e) {
            // ignore
        }
        if (u != null) {
            try {
                sco = u.objectFieldOffset(String.class.getDeclaredField("coder"));
                svo = u.objectFieldOffset(String.class.getDeclaredField("value"));
            } catch (Throwable e) {
                // ignore
            }
        }
        UNSAFE = u;
        STRING_CODER_OFFSET = sco;
        STRING_VALUE_OFFSET = svo;
    }

    static byte[] getLatin1Array(String s) {
        if (STRING_CODER_OFFSET == 0 || s == null || UNSAFE.getByte(s, STRING_CODER_OFFSET) != 0) {
            return null;
        }
        return (byte[]) UNSAFE.getObject(s, STRING_VALUE_OFFSET);
    }
}
```

**Comment by plokhotnyuk** [comment]
Trying to use only `STRING_VALUE_OFFSET` values in a source bellow doesn't help:
```
Caused by: com.oracle.svm.hosted.analysis.flow.SVMMethodTypeFlowBuilder$UnsafeOffsetError: Field AnalysisField<UnsafeUtils.STRING_VALUE_OFFSET accessed: false reads: true written: false> is used as an offset in an unsafe operation, but no value recomputation found.
 Wrapped field: HotSpotResolvedJavaFieldImpl<com.github.plokhotnyuk.jsoniter_scala.core.UnsafeUtils.STRING_VALUE_OFFSET long:112>
 Location: at com.github.plokhotnyuk.jsoniter_scala.core.UnsafeUtils.getLatin1Array(UnsafeUtils.java:32) [bci: 8]
	at com.oracle.svm.hosted.analysis.flow.SVMMethodTypeFlowBuilder$UnsafeOffsetError.report(SVMMethodTypeFlowBuilder.java:119)
	at com.oracle.svm.hosted.analysis.flow.SVMMethodTypeFlowBuilder.checkUnsafeOffset(SVMMethodTypeFlowBuilder.java:161)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder$NodeIterator.node(MethodTypeFlowBuilder.java:1029)
	at org.graalvm.compiler.phases.graph.PostOrderNodeIterator.apply(PostOrderNodeIterator.java:106)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:421)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	... 10 more
```
Version of `UnsafeUtils.java` used:
```
import java.lang.reflect.Field;

public class UnsafeUtils {
    private static final sun.misc.Unsafe UNSAFE;
    private static final long STRING_VALUE_OFFSET;

    static {
        sun.misc.Unsafe u = null;
        long svo = 0;
        try {
            Field f = sun.misc.Unsafe.class.getDeclaredField("theUnsafe");
            f.setAccessible(true);
            u = (sun.misc.Unsafe) f.get(null);
        } catch (Throwable e) {
            // ignore
        }
        if (u != null) {
            try {
                svo = u.objectFieldOffset(String.class.getDeclaredField("value"));
            } catch (Throwable e) {
                // ignore
            }
        }
        UNSAFE = u;
        STRING_VALUE_OFFSET = svo;
    }

    static byte[] getLatin1Array(String s) {
        if (s != null) {
            Object o = UNSAFE.getObject(s, STRING_VALUE_OFFSET);
            if (o instanceof byte[]) {
                byte[] bs = (byte[]) o;
                if (bs.length == s.length()) {
                    return bs;
                }
            }
        }
        return null;
    }
}
```

**Comment by bobmcwhirter** [comment]
Now I think that PR *does* address the issue you're seeing here.

**Comment by plokhotnyuk** [comment]
Closing as outdated... jsoniter-scala doesn't use `sun.misc.Unsafe` anymore.
