### ISSUE TITLE
Downloading LIBFFI_SOURCES failed

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#1516]
Our CI builds are currently failing because of this:
```
Error reading from ftp://sourceware.org/pub/libffi/libffi-3.2.1.tar.gz: <urlopen error ftp error: timed out>
WARNING: ** If behind a firewall without direct internet access, use the http_proxy environment variable (e.g. "env http_proxy=proxy.company.com:80 mx ...") or download manually with a web browser.
Could not download to /home/travis/.mx/cache/LIBFFI_SOURCES_280c265b789e041c02e5c97815793dfc283fb1e6/libffi-sources.tar.gz from any of the following URLs: https://lafo.ssw.uni-linz.ac.at/pub/graal-external-deps/libffi-3.2.1.tar.gz, ftp://sourceware.org/pub/libffi/libffi-3.2.1.tar.gz
Downloading LIBFFI_SOURCES failed
1 build tasks failed
gate: 21 Jul 2019 11:13:52(+00:19) END:   BuildWithEcj [0:00:15.983381] [disk (free/total): 54.1GB/68.9GB]
Traceback (most recent call last):
  File "/home/travis/build/user/mx/mx_gate.py", line 419, in gate
    _run_gate(cleanArgs, args, tasks)
  File "/home/travis/build/user/mx/mx_gate.py", line 514, in _run_gate
    mx.command_function('build')(defaultBuildArgs + args.extra_build_args)
  File "/home/travis/build/user/mx/mx_commands.py", line 147, in __call__
    return self.command_function(*args, **kwargs)
  File "/home/travis/build/user/mx/mx.py", line 14106, in build
    abort('{0} build tasks failed'.format(len(failed)))
  File "/home/travis/build/user/mx/mx.py", line 3743, in abort
    raise SystemExit(error_code)
```

I don't know what caused the `urlopen error`, but http://lafo.ssw.uni-linz.ac.at/ is down at the moment.

**Comment by davleopo** [comment]
@fniephaus can you please retry, this should be fixed in the meantime.

**Comment by fniephaus** [comment]
@davleopo yes, it's working again. Thanks!
