### ISSUE TITLE
[native-image] java.net.NetworkInterface.isUp0 not implemented

### ISSUE THREAD

**Issue by anusse** [oracle/graal#1522]
As in PR #1076 I am also getting an UnsatisfiedLinkError when I try to run my native executable. Although the required underlying methods (getFlags0 and openSocketWithFallBack()) have been implemented as part of PR #1406, it seems like isUp() is still missing. Are there plans to add isUp()?

Example stack trace:

```
Exception in thread "main" java.util.ServiceConfigurationError: liquibase.sqlgenerator.SqlGenerator: Provider liquibase.sqlgenerator.core.LockDatabaseChangeLogGenerator could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232)
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
    	...
Caused by: java.lang.UnsatisfiedLinkError: java.net.NetworkInterface.isUp0(Ljava/lang/String;I)Z [symbol: Java_java_net_NetworkInterface_isUp0 or Java_java_net_NetworkInterface_isUp0__Ljava_lang_String_2I]
        at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
        at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
        at java.net.NetworkInterface.isUp0(NetworkInterface.java)
        at java.net.NetworkInterface.isUp(NetworkInterface.java:399)
        at liquibase.util.NetUtil.getLocalHost(NetUtil.java:31)
        at liquibase.util.NetUtil.getLocalHostName(NetUtil.java:69)
        at liquibase.sqlgenerator.core.LockDatabaseChangeLogGenerator.<clinit>(LockDatabaseChangeLogGenerator.java:30)
        at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
        at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
        at java.lang.Class.ensureInitialized(DynamicHub.java:451)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(DynamicHub.java:762)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        ...
```

**Comment by bobmcwhirter** [comment]
I’ll submit a patch shortly
