### ISSUE TITLE
[sulong] missing specialization for LLVMGetElementPtrNodeGen

### ISSUE THREAD

**Issue by lewurm** [oracle/graal#1534]
`repro2.c`:
```c
#include <stdlib.h>

typedef struct _MemPool MemPool;

struct _MemPool {
        unsigned char *pos;
        unsigned char *end;
};

MemPool* mempool_new_size (void) {
        int init_size = 8192;
        MemPool *pool = (MemPool*)malloc(init_size);

        pool->pos = (unsigned char *)pool + sizeof(MemPool);
        pool->end = (unsigned char *)pool + init_size;
        return pool;
}

int main (void) {
        return mempool_new_size() != (void*)0 ? 0 : 1;
}
```

```console
$  clang -O2 repro2.c && ./a.out; echo $?
0
$ clang -O2 -c -emit-llvm -S repro2.c
$ grep -A 5 'main' repro2.ll. # make sure the LLVM IR looks something like this
define i32 @main() local_unnamed_addr #0 {
  %1 = tail call noalias i8* @malloc(i64 8192) #2
  %2 = insertelement <2 x i8*> undef, i8* %1, i32 0
  %3 = shufflevector <2 x i8*> %2, <2 x i8*> undef, <2 x i32> zeroinitializer
  %4 = getelementptr i8, <2 x i8*> %3, <2 x i64> <i64 16, i64 8192>
  %5 = bitcast i8* %1 to <2 x i8*>*
$ clang -O2 -c -emit-llvm repro2.c
$ lli repro2.bc
ERROR: com.oracle.truffle.api.dsl.UnsupportedSpecializationException: Unexpected values provided for LLVMGetElementPtrNodeGen@66d2b8de: [< 2 x void* > < void*
 0x57d3c00, void* 0x57d3c00 >, < 2 x i64 > < i64 16, i64 8192 >], [LLVMPointerVector,LLVMI64Vector]
org.graalvm.polyglot.PolyglotException: com.oracle.truffle.api.dsl.UnsupportedSpecializationException: Unexpected values provided for LLVMGetElementPtrNodeGen
@66d2b8de: [< 2 x void* > < void* 0x57d3c00, void* 0x57d3c00 >, < 2 x i64 > < i64 16, i64 8192 >], [LLVMPointerVector,LLVMI64Vector]
        at com.oracle.truffle.llvm.nodes.memory.LLVMGetElementPtrNodeGen.executeAndSpecialize(LLVMGetElementPtrNodeGen.java:111)
        at com.oracle.truffle.llvm.nodes.memory.LLVMGetElementPtrNodeGen.executeGeneric_generic2(LLVMGetElementPtrNodeGen.java:91)
        at com.oracle.truffle.llvm.nodes.memory.LLVMGetElementPtrNodeGen.executeGeneric(LLVMGetElementPtrNodeGen.java:48)
        at com.oracle.truffle.llvm.nodes.vars.LLVMWriteNodeFactory$LLVMWritePointerNodeGen.execute_generic1(LLVMWriteNodeFactory.java:755)
        at com.oracle.truffle.llvm.nodes.vars.LLVMWriteNodeFactory$LLVMWritePointerNodeGen.execute(LLVMWriteNodeFactory.java:736)
        at com.oracle.truffle.llvm.nodes.base.LLVMBasicBlockNode.execute(LLVMBasicBlockNode.java:98)
        at com.oracle.truffle.llvm.nodes.control.LLVMDispatchBasicBlockNode.executeGeneric(LLVMDispatchBasicBlockNode.java:102)
        at com.oracle.truffle.llvm.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:82)
        at <llvm> main(Unknown)
        at org.graalvm.polyglot.Value.execute(Value.java:336)
        at com.oracle.truffle.llvm.launcher.LLVMLauncher.execute(LLVMLauncher.java:208)
        at com.oracle.truffle.llvm.launcher.LLVMLauncher.launch(LLVMLauncher.java:62)
        at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:121)
        at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:70)
        at com.oracle.truffle.llvm.launcher.LLVMLauncher.main(LLVMLauncher.java:53)
```

**Comment by zapster** [comment]
Thanks for report! This has been fixed on master and will work in the upcoming releases.
