### ISSUE TITLE
[question] native-image generation error: lzma

### ISSUE THREAD

**Issue by viktorklang** [oracle/graal#1536]
Hi,

I'm encountering this issue when running native-image on macOS 10.14.5 using:

OpenJDK Runtime Environment (build 1.8.0_222-20190711112007.graal.jdk8u-src-tar-gz-b08)
OpenJDK 64-Bit GraalVM CE 19.1.1 (build 25.222-b08-jvmci-19.1-b01, mixed mode)

This error appears, which is reported as a user error, but it seems rather unlikely. Have anyone seen this, and if so, how to make it go away?

`output included error: /usr/local/include/Block.h:16:3: error: Never include this file directly. Use <lzma.h> instead.`

```
[error] Error: Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:16:3: error: Never include this file directly. Use <lzma.h> instead.
[error] Error: Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:93:2: error: unknown type name 'lzma_check'
[error] Error: Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:148:2: error: unknown type name 'lzma_vli'
[error] Error: Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:172:2: error: unknown type name 'lzma_vli'
[error] Error: Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:200:2: error: unknown type name 'lzma_filter'
[error] Error: Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:217:20: error: use of undeclared identifier 'LZMA_CHECK_SIZE_MAX'
[error] Error: Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:231:2: error: unknown type name 'lzma_vli'
[error] Error: Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:232:2: error: unknown type name 'lzma_vli'
[error] Error: Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:233:2: error: unknown type name 'lzma_vli'
[error] Error: Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:234:2: error: unknown type name 'lzma_vli'
[error] Error: Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:235:2: error: unknown type name 'lzma_vli'
[error] Error: Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:236:2: error: unknown type name 'lzma_vli'
[error] Error: Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:237:2: error: unknown type name 'lzma_reserved_enum'
[error] Error: Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:238:2: error: unknown type name 'lzma_reserved_enum'
[error] Error: Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:239:2: error: unknown type name 'lzma_reserved_enum'
[error] Error: Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:240:2: error: unknown type name 'lzma_reserved_enum'
[error] Error: Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:261:2: error: unknown type name 'lzma_bool'
[error] Error: Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:263:2: error: unknown type name 'lzma_bool'
[error] Error: Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:264:2: error: unknown type name 'lzma_bool'
[error] com.oracle.svm.core.util.UserError$UserException: Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:16:3: error: Never include this file directly. Use <lzma.h> instead.
[error] Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:93:2: error: unknown type name 'lzma_check'
[error] Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:148:2: error: unknown type name 'lzma_vli'
[error] Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:172:2: error: unknown type name 'lzma_vli'
[error] Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:200:2: error: unknown type name 'lzma_filter'
[error] Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:217:20: error: use of undeclared identifier 'LZMA_CHECK_SIZE_MAX'
[error] Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:231:2: error: unknown type name 'lzma_vli'
[error] Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:232:2: error: unknown type name 'lzma_vli'
[error] Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:233:2: error: unknown type name 'lzma_vli'
[error] Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:234:2: error: unknown type name 'lzma_vli'
[error] Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:235:2: error: unknown type name 'lzma_vli'
[error] Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:236:2: error: unknown type name 'lzma_vli'
[error] Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:237:2: error: unknown type name 'lzma_reserved_enum'
[error] Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:238:2: error: unknown type name 'lzma_reserved_enum'
[error] Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:239:2: error: unknown type name 'lzma_reserved_enum'
[error] Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:240:2: error: unknown type name 'lzma_reserved_enum'
[error] Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:261:2: error: unknown type name 'lzma_bool'
[error] Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:263:2: error: unknown type name 'lzma_bool'
[error] Error compiling query code (in /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c). Compiler command  gcc /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives.c -o /var/folders/c9/bbngnch57r32zlblnw63wkrh0000gn/T/SVM-1063859825289923708/PosixDirectives output included error: /usr/local/include/Block.h:264:2: error: unknown type name 'lzma_bool'
[error] 	at com.oracle.svm.core.util.UserError.abort(UserError.java:114)
[error] 	at com.oracle.svm.hosted.c.NativeLibraries.reportErrors(NativeLibraries.java:196)
[error] 	at com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1512)
[error] 	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:993)
[error] 	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:827)
[error] 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:520)
[error] 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:440)
[error] 	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
[error] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[error] Error: Image build request failed with exit status 1
[error] java.lang.RuntimeException: Failed to run native-image, exit status: 1
[error] 	at scala.sys.package$.error(package.scala:26)
[error] 	at com.typesafe.sbt.packager.graalvmnativeimage.GraalVMNativeImagePlugin$.$anonfun$projectSettings$3(GraalVMNativeImagePlugin.scala:52)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by viktorklang** [comment]
Possible solved by this, investigating further: https://github.com/golang/go/issues/25240#issuecomment-387969187

**Comment by peter-hofer** [comment]
Thank you for your report. The comments on the issue you linked seem to indicate that is caused by incorrect/incompatible leftover header files. Can you confirm that? Are you using _lzma_ anywhere? (we don't seem to reference it)

**Comment by viktorklang** [comment]
Yes, I can confirm that it was due to leftover header files—just in case
someone else encounters this issue.

Cheers,
V
-- 
Cheers,
√

**Comment by peter-hofer** [comment]
Thanks for your response.
