### ISSUE TITLE
When classpath no groovy dependency got errors below!

### ISSUE THREAD

**Issue by guanchao-yang** [oracle/graal#1539]
```
Error: substitution target for com.oracle.svm.polyglot.groovy.Target_org_codehaus_groovy_vmplugin_v7_IndyInterface_invalidateSwitchPoints is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
com.oracle.svm.core.util.UserError$UserException: substitution target for com.oracle.svm.polyglot.groovy.Target_org_codehaus_groovy_vmplugin_v7_IndyInterface_invalidateSwitchPoints is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
  at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
  at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findTargetClass(AnnotationSubstitutionProcessor.java:823)
  at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:252)
  at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:230)
  at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:863)
  at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:817)
  at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:520)
  at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:440)
  at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
  at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
  at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
  at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
  at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

I think maybe optimize groovy `@Substitute`.

[source code](https://github.com/oracle/graal/blob/97567ebd2a81279461bad60d422b71371ca6803a/substratevm/src/com.oracle.svm.polyglot/src/com/oracle/svm/polyglot/groovy/GroovySubstitutions.java)

**Comment by cstancu** [comment]
@guanchao-yang can you please provide steps to replicate how you reached this exception?

**Comment by guanchao-yang** [comment]
@cstancu  I added this dependency fixed

```xml
<dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.4.7</version>
        </dependency>
```
But I got the errors below when I use groovy script function:

```
[com.alipay.sofa.tomcat.demosvmapplication:62029]     analysis:  19,180.12 ms
Error: Unsupported features in 2 methods
Detailed message:
Error: type is not available in this platform: com.oracle.svm.hosted.ameta.HostedDynamicHubFeature
Trace:  object java.lang.Class[]
        object java.lang.invoke.MethodType
        object java.lang.invoke.MethodType$ConcurrentWeakInternSet$WeakEntry
        object java.util.concurrent.ConcurrentHashMap$Node
        object java.util.concurrent.ConcurrentHashMap$Node[]
        object java.util.concurrent.ConcurrentHashMap
        object java.lang.invoke.MethodType$ConcurrentWeakInternSet
        method java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean)
Call path from entry point to java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean): 
        no path found from entry point to target method

Error: type is not available in this platform: com.oracle.svm.hosted.lambda.LambdaSubstitutionType
Trace:  object java.lang.invoke.MethodType
        object java.lang.invoke.MethodType$ConcurrentWeakInternSet$WeakEntry
        object java.util.concurrent.ConcurrentHashMap$Node
        object java.util.concurrent.ConcurrentHashMap$Node[]
        object java.util.concurrent.ConcurrentHashMap
        object java.lang.invoke.MethodType$ConcurrentWeakInternSet
        method java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean)
Call path from entry point to java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean): 
        no path found from entry point to target method


com.oracle.svm.core.util.UserError$UserException: Unsupported features in 2 methods
Detailed message:
Error: type is not available in this platform: com.oracle.svm.hosted.ameta.HostedDynamicHubFeature
Trace:  object java.lang.Class[]
        object java.lang.invoke.MethodType
        object java.lang.invoke.MethodType$ConcurrentWeakInternSet$WeakEntry
        object java.util.concurrent.ConcurrentHashMap$Node
        object java.util.concurrent.ConcurrentHashMap$Node[]
        object java.util.concurrent.ConcurrentHashMap
        object java.lang.invoke.MethodType$ConcurrentWeakInternSet
        method java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean)
Call path from entry point to java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean): 
        no path found from entry point to target method

Error: type is not available in this platform: com.oracle.svm.hosted.lambda.LambdaSubstitutionType
Trace:  object java.lang.invoke.MethodType
        object java.lang.invoke.MethodType$ConcurrentWeakInternSet$WeakEntry
        object java.util.concurrent.ConcurrentHashMap$Node
        object java.util.concurrent.ConcurrentHashMap$Node[]
        object java.util.concurrent.ConcurrentHashMap
        object java.lang.invoke.MethodType$ConcurrentWeakInternSet
        method java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean)
Call path from entry point to java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean): 
        no path found from entry point to target method


        at com.oracle.svm.core.util.UserError.abort(UserError.java:75)
        at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:216)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:732)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:522)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:440)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported features in 2 methods
Detailed message:
Error: type is not available in this platform: com.oracle.svm.hosted.ameta.HostedDynamicHubFeature
Trace:  object java.lang.Class[]
        object java.lang.invoke.MethodType
        object java.lang.invoke.MethodType$ConcurrentWeakInternSet$WeakEntry
        object java.util.concurrent.ConcurrentHashMap$Node
        object java.util.concurrent.ConcurrentHashMap$Node[]
        object java.util.concurrent.ConcurrentHashMap
        object java.lang.invoke.MethodType$ConcurrentWeakInternSet
        method java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean)
Call path from entry point to java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean): 
        no path found from entry point to target method

Error: type is not available in this platform: com.oracle.svm.hosted.lambda.LambdaSubstitutionType
Trace:  object java.lang.invoke.MethodType
        object java.lang.invoke.MethodType$ConcurrentWeakInternSet$WeakEntry
        object java.util.concurrent.ConcurrentHashMap$Node
        object java.util.concurrent.ConcurrentHashMap$Node[]
        object java.util.concurrent.ConcurrentHashMap
        object java.lang.invoke.MethodType$ConcurrentWeakInternSet
        method java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean)
Call path from entry point to java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean): 
        no path found from entry point to target method


        at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:133)
        at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:565)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:683)
        ... 7 more
Error: Image build request failed with exit status 1

```
