### ISSUE TITLE
native-image success but run failed

### ISSUE THREAD

**Issue by Zhoulianchang** [oracle/graal#1540]
```
native-image -jar hello-1.0.jar
Build on Server(pid: 179, port: 39542)*
[hello-1.0:179]    classlist:   4,976.09 ms
[hello-1.0:179]        (cap):   2,211.88 ms
[hello-1.0:179]        setup:   5,833.06 ms
[hello-1.0:179]     analysis:  31,856.57 ms
Warning: Aborting stand-alone image build. com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported field java.net.URL.handlers is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
	at parsing java.net.URL.setURLStreamHandlerFactory(URL.java:1118)
Call path from entry point to java.net.URL.setURLStreamHandlerFactory(URLStreamHandlerFactory): 
	at java.net.URL.setURLStreamHandlerFactory(URL.java:1110)
	at org.springframework.boot.loader.jar.JarFile.resetCachedUrlHandlers(JarFile.java:401)
	at org.springframework.boot.loader.jar.JarFile.registerUrlProtocolHandler(JarFile.java:391)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:48)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:147)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

Warning: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Build on Server(pid: 179, port: 39542)
[hello-1.0:179]    classlist:     657.95 ms
[hello-1.0:179]        (cap):   1,834.57 ms
[hello-1.0:179]        setup:   3,007.67 ms
[hello-1.0:179]   (typeflow):   6,796.65 ms
[hello-1.0:179]    (objects):   2,474.66 ms
[hello-1.0:179]   (features):     442.03 ms
[hello-1.0:179]     analysis:   9,903.48 ms
[hello-1.0:179]     (clinit):     362.02 ms
[hello-1.0:179]     universe:   1,133.60 ms
[hello-1.0:179]      (parse):   2,842.46 ms
[hello-1.0:179]     (inline):   3,945.72 ms
[hello-1.0:179]    (compile):  30,972.46 ms
[hello-1.0:179]      compile:  38,529.56 ms
[hello-1.0:179]        image:   1,005.86 ms
[hello-1.0:179]        write:     554.28 ms
[hello-1.0:179]      [total]:  54,997.27 ms
Warning: Image 'hello-1.0' is a fallback image that requires a JDK for execution (use --no-fallback to suppress fallback image generation).
```
## Running binary
```
bash-4.2# ./hello-1.0 
Error: Could not find or load main class org.springframework.boot.loader.JarLauncher
```

**Comment by olpaw** [comment]
@Zhoulianchang are you sure running `java -jar hello-1.0.jar` works?

If so please rerun `hello-1.0` with
```
FALLBACK_EXECUTOR_VERBOSE=true ./hello-1.0
```
and post the output to the command for further inspection.

**Comment by Zhoulianchang** [comment]
@olpaw I deleted the jar file after I generated the file. It can be run before it is deleted.
```
bash-4.2# FALLBACK_EXECUTOR_VERBOSE=true ./hello-1.0
Exec: /opt/graalvm-ce-19.1.1/jre/bin/java -Dorg.graalvm.nativeimage.kind=fallback-executable -cp /home/hello-1.0.jar org.springframework.boot.loader.JarLauncher
Error: Could not find or load main class org.springframework.boot.loader.JarLauncher
```

**Comment by olpaw** [comment]
Well, that's the expected behavior when a **fallback image** gets generated. But this likely not what you wanted. I guess you want to build a **standalone image** that can run independently from JVM and the original jar file. For more info see https://medium.com/graalvm/introducing-the-tracing-agent-simplifying-graalvm-native-image-configuration-c3b56c486271

**Comment by Zhoulianchang** [comment]
alright, thank you very much
