### ISSUE TITLE
Batik (dacapo) fails on graalvm-ce-19.1.1 and graalvm-ce-19.0.2

### ISSUE THREAD

**Issue by Fithos** [oracle/graal#1541]
I noticed that batik (from dacapo-9.12-MR1-bach) fails on GraalVM CE. Please see the log below:

```
$ /Library/Java/JavaVirtualMachines/graalvm-ce-19.1.1/Contents/Home/bin/java -jar dacapo/dacapo-9.12-MR1-bach.jar batik
===== DaCapo 9.12-MR1 batik starting =====
About to transcode 3 SVG file(s)

Converting mapWaadt.svg to /Users/fithos/concprof-dacapo-analysis/./scratch/mapWaadt.png ... ... success
Converting mapSpain.svg to /Users/fithos/concprof-dacapo-analysis/./scratch/mapSpain.png ... ... success
Converting sydney.svg to /Users/fithos/concprof-dacapo-analysis/./scratch/sydney.png ... java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.dacapo.harness.Batik.iterate(Batik.java:41)
	at org.dacapo.harness.Benchmark.run(Benchmark.java:187)
	at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:199)
	at org.dacapo.harness.TestHarness.main(TestHarness.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at Harness.main(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: com/sun/image/codec/jpeg/TruncatedFileException
	at org.apache.batik.ext.awt.image.codec.jpeg.JPEGRegistryEntry.handleStream(JPEGRegistryEntry.java:87)
	at org.apache.batik.ext.awt.image.spi.ImageTagRegistry.readURL(ImageTagRegistry.java:189)
	at org.apache.batik.bridge.SVGImageElementBridge.createImageGraphicsNode(SVGImageElementBridge.java:257)
	at org.apache.batik.bridge.SVGImageElementBridge.buildImageGraphicsNode(SVGImageElementBridge.java:176)
	at org.apache.batik.bridge.SVGImageElementBridge.createGraphicsNode(SVGImageElementBridge.java:118)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:206)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:164)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:212)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:164)
	at org.apache.batik.bridge.GVTBuilder.build(GVTBuilder.java:78)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:214)
	at org.apache.batik.transcoder.image.ImageTranscoder.transcode(ImageTranscoder.java:92)
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:142)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:159)
	at org.apache.batik.apps.rasterizer.SVGConverter.transcode(SVGConverter.java:992)
	at org.apache.batik.apps.rasterizer.SVGConverter.execute(SVGConverter.java:715)
	at org.apache.batik.apps.rasterizer.Main.execute(Main.java:938)
	... 13 more
Caused by: java.lang.ClassNotFoundException: com.sun.image.codec.jpeg.TruncatedFileException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.dacapo.harness.DacapoClassLoader.loadClass(DacapoClassLoader.java:123)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 30 more
```
I tested and got this exception on
- graalvm-ce-19.0.2 MacOS
- graalvm-ce-19.0.2 Linux
- graalvm-ce-19.1.1 MacOS

On graalvm-ee, instead, the workload works fine (I tried graalvm-ee-19.0.2, both on Linux and MacOS). 

This issue should be the same one described at https://www.stichlberger.com/software/workaround-for-batiks-noclassdeffounderrorclassnotfoundexception-truncatedfileexception/ (thanks to @villazon). 

cc @gilles-duboscq

**Comment by gilles-duboscq** [comment]
Hi Andrea,
Thank you for the report.

Isn't it expected though? GraalVM CE is based on OpenJDK 8 which doesn't have the class batik is looking for. It works on GraalVM EE because that's based on Oracle JDK.

I get the same result on OpenJDK from Fedora for example.
I'm not sure we can do much on our end.

**Comment by neomatrix369** [comment]
Maybe mention somewhere in the docs or runtime (if possible) about this dependency or requirement, may result in one less repeat question. 😄

**Comment by Fithos** [comment]
@gilles-duboscq, @neomatrix369 I see. Thanks for the clarification! Then, I think the issue can be closed.
