### ISSUE TITLE
Native image build failed with error: Main entry point class 'io.micronaut.function.aws.runtime.MicronautLambdaRuntime' not found.

### ISSUE THREAD

**Issue by nehaliacharya94** [oracle/graal#1558]
I have a Micronaut application for which I am trying to build the native image (a Docker image) in my local environment (Windows) with the command:
`docker build . -t student-custom-runtime`. 
The stacktrace is:
```
Error: Main entry point class 'io.micronaut.function.aws.runtime.MicronautLambdaRuntime' not found.
com.oracle.svm.core.util.UserError$UserException: Main entry point class 'io.micronaut.function.aws.runtime.MicronautLambdaRuntime' not found.
        at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:240)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:422)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:108)
Error: Image build request failed with exit status 1
```
With reference to the above error, I have checked that the Project and External Dependencies in my project has the micronaut-function-aws-custom-runtime jar file. The build-native-image.sh file is:
```
#!/bin/sh
GRAALVM_HOME=${GRAALVM_HOME:-/usr/lib/graalvm}
${GRAALVM_HOME}/bin/native-image --no-server \
             --class-path student-custom-runtime-*.jar \
             -H:ReflectionConfigurationFiles=src/main/resources/reflect.json \
             -H:EnableURLProtocols=http \
             -H:IncludeResources="logback.xml|application.properties|.*/endpoints.json$" \
	     -H:Log=registerResource \
	     -H:DynamicProxyConfigurationFiles="dynamic-proxies.json" \
             -H:Name=server \
             -H:Class=io.micronaut.function.aws.runtime.MicronautLambdaRuntime \
             -H:+ReportUnsupportedElementsAtRuntime \
             -H:+ReportExceptionStackTraces \
             -H:-AllowVMInspection \
	     --enable-https \
             --allow-incomplete-classpath \
             --rerun-class-initialization-at-runtime='sun.security.jca.JCAUtil$CachedSecureRandomHolder,javax.net.ssl.SSLContext' \
             --delay-class-initialization-to-runtime=io.netty.handler.codec.http.HttpObjectEncoder,io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder,io.netty.handler.ssl.util.ThreadLocalInsecureRandom,com.sun.jndi.dns.DnsClient,io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler,com.amazonaws.serverless.proxy.internal.LambdaContainerHandler,io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator,io.netty.handler.ssl.ReferenceCountedOpenSslEngine
```
I'm not sure what I am missing. Any help is appreciated.

**Comment by cstancu** [comment]
The `micronaut-function-aws-custom-runtime.jar` needs to be on your classpath. I see that your `--class-path` only specifies `student-custom-runtime-*.jar`. Or is that an uber jar that is supposed to contain all classes? If you can share your code I can take a closer look.

**Comment by nehaliacharya94** [comment]
It is an uber jar having all the classes but when I viewed the contents of the jar, it didn't have `micronaut-function-aws-custom-runtime.jar`. Unfortunately I can't share the code due to workplace policies. I did try to add it in the classpath like you suggested but it still says not found. I might have not added it correctly. Should it be like this:
```
#!/bin/sh
GRAALVM_HOME=${GRAALVM_HOME:-/usr/lib/graalvm}
${GRAALVM_HOME}/bin/native-image --no-server \
             --class-path student-custom-runtime-*.jar \
             --class-path micronaut-function-aws-custom-runtime.jar \
             -H:ReflectionConfigurationFiles=src/main/resources/reflect.json \
             -H:EnableURLProtocols=http \
             -H:IncludeResources="logback.xml|application.properties|.*/endpoints.json$" \
	     -H:Log=registerResource \
	     -H:DynamicProxyConfigurationFiles="dynamic-proxies.json" \
             -H:Name=server \
             -H:Class=io.micronaut.function.aws.runtime.MicronautLambdaRuntime \
             -H:+ReportUnsupportedElementsAtRuntime \
             -H:+ReportExceptionStackTraces \
             -H:-AllowVMInspection \
	     --enable-https \
             --allow-incomplete-classpath \
             --rerun-class-initialization-at-runtime='sun.security.jca.JCAUtil$CachedSecureRandomHolder,javax.net.ssl.SSLContext' \
             --delay-class-initialization-to-runtime=io.netty.handler.codec.http.HttpObjectEncoder,io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder,io.netty.handler.ssl.util.ThreadLocalInsecureRandom,com.sun.jndi.dns.DnsClient,io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler,com.amazonaws.serverless.proxy.internal.LambdaContainerHandler,io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator,io.netty.handler.ssl.ReferenceCountedOpenSslEngine
```

**Comment by bobmcwhirter** [comment]
Try a single `-cp` for the classpath, using the appropriate path separator (`:` on unix-like systems).

`-cp student-custom-runtime-*.jar:micronaut-function-aws-custom-runtime.jar`

I'm also unsure if `-cp` supports wildcards in that way, or if they will get expanded by the shell. Worth experimenting, but that might also be part of the issue.

To determine, place an `echo` immediately in front of your command and you'll see what fully, expanded command-line is being executed.

**Comment by nehaliacharya94** [comment]
`-cp student-custom-runtime-*.jar:micronaut-function-aws-custom-runtime.jar` showed `cp` as an error in the build-native-image.sh file so I removed it and added `--class-path student-custom-runtime-*.jar:micronaut-function-aws-custom-runtime.jar` but it still gives the same error.
