### ISSUE TITLE
On Windows, if users have "long" username, the build is not working

### ISSUE THREAD

**Issue by apupier** [oracle/graal#1562]
for instance, for "Aurelien Pupier", the tmp dir by default is returned in the form: `C:\Users\AURELI~1\AppData\Local\Temp\`

the error is:
```
Error: Error compiling query code (in C:\Users\AURELI~1\AppData\Local\Temp\SVM-4151949191562174986\JNIHeaderDirectives.cpp). Compiler command  CL -IC:\install\graalvm-ce-windows-amd64-19.1.1\graalvm-ce-19.1.1\include\win32 C:\Users\AURELI~1\AppData\Local\Temp\SVM-4151949191562174986\JNIHeaderDirectives.cpp /FeC:\Users\AURELI~1\AppData\Local\Temp\SVM-4151949191562174986\JNIHeaderDirectives.exe output included error: [Microsoft (R) C/C++ Optimizing Compiler Version 19.22.27905 for x86, Copyright (C) Microsoft Corporation.  All rights reserved., ]
com.oracle.svm.core.util.UserError$UserException: Error compiling query code (in C:\Users\AURELI~1\AppData\Local\Temp\SVM-4151949191562174986\JNIHeaderDirectives.cpp). Compiler command  CL -IC:\install\graalvm-ce-windows-amd64-19.1.1\graalvm-ce-19.1.1\include\win32 C:\Users\AURELI~1\AppData\Local\Temp\SVM-4151949191562174986\JNIHeaderDirectives.cpp /FeC:\Users\AURELI~1\AppData\Local\Temp\SVM-4151949191562174986\JNIHeaderDirectives.exe output included error: [Microsoft (R) C/C++ Optimizing Compiler Version 19.22.27905 for x86, Copyright (C) Microsoft Corporation.  All rights reserved., ]
        at com.oracle.svm.core.util.UserError.abort(UserError.java:114)
        at com.oracle.svm.hosted.c.NativeLibraries.reportErrors(NativeLibraries.java:196)
        at com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1512)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:993)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:827)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:520)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:440)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

if using the CL command directly, we have access to full error:

```
C:\git\camel-language-server>CL -IC:\install\graalvm-ce-windows-amd64-19.1.1\graalvm-ce-19.1.1\include\win32 C:\Users\AURELI~1\AppData\Local\Temp\SVM-4151949191562174986\JNIHeaderDirectives.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.22.27905 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

JNIHeaderDirectives.cpp
c1xx: fatal error C1083: Cannot open source file: 'C:\Users\AURELI~1\AppData\Local\Temp\SVM-4151949191562174986\JNIHeaderDirectives.cpp': No such file or directory
```
there is effectively no such file or directories
There is  no folder namds SVM-XXXX in the temp folder

workaround: specify another repository using `-H:TempDirectory`

**Comment by pejovica** [comment]
It looks like you are using a 32-bit compiler, which is not supported. Could you try from the 64-bit Developer Command Prompt? Also, we only test the MSVC 2010 compiler, so there may be other issues with newer versions.

**Comment by apupier** [comment]
you're right. using a a 64 bits Developer Command prompt, there is not this issue.
