### ISSUE TITLE
Error: Unsupported features in 3 methods when using in GraalVM 19.1.1

### ISSUE THREAD

**Issue by guanchao-yang** [oracle/graal#1563]
Got errors below : 

```
Error: Unsupported features in 3 methods
Detailed message:
Error: Non-reducible loop
Call path from entry point to oracle.net.aso.r.a(byte[], int, char[], int):
        at oracle.net.aso.r.a(Unknown Source)
        at oracle.net.aso.l.b(Unknown Source)
        at oracle.net.aso.l.a(Unknown Source)
        at oracle.net.ano.DataIntegrityService.a(Unknown Source)
        at oracle.net.ano.Service.c(Unknown Source)
        at oracle.net.ano.Ano.negotiation(Unknown Source)
        at oracle.net.ns.NSProtocol.connect(NSProtocol.java:439)
        at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1102)
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:320)
        at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:546)
        at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:236)
        at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:32)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:521)
        at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:120)

```

```
Error: only four jsr nesting levels are supported
Call path from entry point to com.mysql.jdbc.PreparedStatement.executeBatchSerially(int):
        at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1890)
        at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1393)
        at com.oracle.svm.reflect.Statement_executeBatch_ad5c04e8bff028e2eba4fdc81e56a0fabddc3502_2923.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at javax.xml.transform.TransformerException.printStackTrace(TransformerException.java:348)
        at javax.xml.transform.TransformerException.printStackTrace(TransformerException.java:282)
        at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:761)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
Original exception that caused the problem: org.graalvm.compiler.java.JsrNotSupportedBailout: only four jsr nesting levels are supported
        at org.graalvm.compiler.java.JsrScope.push(JsrScope.java:47)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:799)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
```

```
Error: only four jsr nesting levels are supported
Call path from entry point to com.mysql.jdbc.ServerPreparedStatement.executeBatchSerially(int):
        at com.mysql.jdbc.ServerPreparedStatement.executeBatchSerially(ServerPreparedStatement.java:664)
        at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1393)
        at com.oracle.svm.reflect.Statement_executeBatch_ad5c04e8bff028e2eba4fdc81e56a0fabddc3502_2923.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at javax.xml.transform.TransformerException.printStackTrace(TransformerException.java:348)
        at javax.xml.transform.TransformerException.printStackTrace(TransformerException.java:282)
        at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:761)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
Original exception that caused the problem: org.graalvm.compiler.java.JsrNotSupportedBailout: only four jsr nesting levels are supported
        at org.graalvm.compiler.java.JsrScope.push(JsrScope.java:47)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:799)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
        at org.graalvm.compiler.java.BciBlockMapping.createJsrAlternatives(BciBlockMapping.java:830)
```

**Comment by dougxc** [comment]
Hi @guanchao-yang , is it possible for you to provide a small reproducer for this?

**Comment by dougxc** [comment]
I've managed to reproduce and will create a fix.

**Comment by guanchao-yang** [comment]
@dougxc Using the oracle jdbc 

```xml
<dependency>
                <groupId>com.oracle</groupId>
                <artifactId>ojdbc6</artifactId>
                <version>11.2.0.3.0</version>
            </dependency>
```
@dougxc Looking forward to your fix.

**Comment by dougxc** [comment]
This should be fixed by https://github.com/oracle/graal/commit/17b272f9e2bb634c4544ffacfced6d4fcc6654bb.
