### ISSUE TITLE
SubstrateVM: PlainDatagramSocketImpl.join() fails

### ISSUE THREAD

**Issue by belaban** [oracle/graal#1584]
I'm trying to get JGroups running with IP multicast support, but the showstopper is PlainDatagramSocketImpl.join():

```
[belasmac] /Users/bela$ ./org.jgroups.tests.multicasttest 
Exception in thread "main" java.lang.UnsatisfiedLinkError: java.net.PlainDatagramSocketImpl.join(Ljava/net/InetAddress;Ljava/net/NetworkInterface;)V [symbol: Java_java_net_PlainDatagramSocketImpl_join or Java_java_net_PlainDatagramSocketImpl_join__Ljava_net_InetAddress_2Ljava_net_NetworkInterface_2]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
	at java.net.PlainDatagramSocketImpl.join(PlainDatagramSocketImpl.java)
	at java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:178)
	at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323)
	at org.jgroups.tests.MulticastTest.testMulticastSocket(MulticastTest.java:42)
	at org.jgroups.tests.MulticastTest.main(MulticastTest.java:35)

```

To reproduce:

    Use native-compile on MulticastTest [1]
    Run with MulticastSocket: ./org.jgroups.tests.multicasttest
    Run with DatagramChannel: ./org.jgroups.tests.multicasttest -nio

[1] https://github.com/belaban/JGroups/blob/master/tests/other/org/jgroups/tests/MulticastTest.java
[2] https://issues.jboss.org/browse/JGRP-2344

**Comment by galderz** [comment]
@belaban I think @dmlloyd already fixed this issue. The problem IMO is that the fix that David added was integrated with master and probably not the 19.1.x or 19.2.x branches (didn't check this in detail), hence why it might still fail 19.1.1. I tried myself with 19.2.2 and it failed too. 

However, I built GraalVM from master and then it started fine (I didn't test further):

```
./org.jgroups.tests.multicasttest
MulticastSocket: local=0.0.0.0/0.0.0.0:6789, remote=null
```

**Comment by galderz** [comment]
Actually, I had tried with 19.1.1 and it didn't work. I've just checked 19.2 branch and the commits are there, so most likely 19.2.0 should work...

**Comment by belaban** [comment]
I don't know the commit policy of SubstrateVM, but I would expect any fix to be in the next release _after_ the fix! I'll try this out with 19.2.2.
@galderz Thanks for trying this out, but I want a release and not something I build off of master myself. I can wait, I moved the issue to the next JGroups release.
Cheers

**Comment by galderz** [comment]
@belaban Tried with 19.2.0 (released) and it worked fine:

```
$ CLASSPATH=./target/jgroups-4.1.4-SNAPSHOT.jar ./bin/compile.sh org.jgroups.tests.MulticastTest
...
$ ./org.jgroups.tests.multicasttest
MulticastSocket: local=0.0.0.0/0.0.0.0:6789, remote=null
$ native-image --version
GraalVM Version 19.2.0 CE
```

**Comment by belaban** [comment]
@cstancu OK, thanks for the clarification! I'll try out the 19.2.2 release then.
Cheers,

**Comment by galderz** [comment]
@belaban It's 19.2.0. I got confused with version numbers 🤪

**Comment by belaban** [comment]
@galderz whatever the latest version is by the time I try this out then... :-)
