### ISSUE TITLE
[jvisualvm] "Too deep inlining" when running with memory profiler

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#1590]
It looks like `ProfilerRuntimeObjLiveness.traceObjAlloc` should be marked as a boundary somehow:

```
[truffle] opt fail         methodName             |Reason org.graalvm.compiler.core.common.PermanentBailoutException: Too deep inlining, probably caused by recursive inlining.
== Inlined methods ordered by inlining frequency:
java.lang.Object.<init>() [167]
org.graalvm.visualvm.lib.jfluid.server.ThreadInfo.<init>(Thread) [166]
org.graalvm.visualvm.lib.jfluid.server.ProfilerRuntimeObjLiveness.traceObjAlloc(Object, char) [166]
org.graalvm.visualvm.lib.jfluid.server.ThreadInfo.newThreadInfo(Thread) [166]
org.graalvm.visualvm.lib.jfluid.server.ThreadInfo.getThreadInfo(Thread) [166]
org.graalvm.visualvm.lib.jfluid.server.ThreadInfo.getThreadInfo() [166]
de.hpi.swa.graal.squeak.nodes.ExecuteContextNode.executeFresh(VirtualFrame) [1]
de.hpi.swa.graal.squeak.util.FrameAccess.initializeMarker(Frame, CompiledCodeObject) [1]
org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(VirtualFrame) [1]
org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(Object[]) [1]
de.hpi.swa.graal.squeak.nodes.EnterCodeNode.execute(VirtualFrame) [1]
== Complete stack trace of inlined methods:
java.lang.Object.<init>(Object.java:37)
org.graalvm.visualvm.lib.jfluid.server.ThreadInfo.<init>(ThreadInfo.java:104)
org.graalvm.visualvm.lib.jfluid.server.ThreadInfo.newThreadInfo(ThreadInfo.java:429)
org.graalvm.visualvm.lib.jfluid.server.ThreadInfo.getThreadInfo(ThreadInfo.java:304)
org.graalvm.visualvm.lib.jfluid.server.ThreadInfo.getThreadInfo(ThreadInfo.java:297)
org.graalvm.visualvm.lib.jfluid.server.ProfilerRuntimeObjLiveness.traceObjAlloc(ProfilerRuntimeObjLiveness.java:246)
...
java.lang.Object.<init>(Object.java:37)
org.graalvm.visualvm.lib.jfluid.server.ThreadInfo.<init>(ThreadInfo.java:104)
org.graalvm.visualvm.lib.jfluid.server.ThreadInfo.newThreadInfo(ThreadInfo.java:429)
org.graalvm.visualvm.lib.jfluid.server.ThreadInfo.getThreadInfo(ThreadInfo.java:304)
org.graalvm.visualvm.lib.jfluid.server.ThreadInfo.getThreadInfo(ThreadInfo.java:297)
org.graalvm.visualvm.lib.jfluid.server.ProfilerRuntimeObjLiveness.traceObjAlloc(ProfilerRuntimeObjLiveness.java:246)
java.lang.Object.<init>(Object.java:37)
de.hpi.swa.graal.squeak.util.FrameAccess.initializeMarker(FrameAccess.java:160)
de.hpi.swa.graal.squeak.nodes.ExecuteContextNode.executeFresh(ExecuteContextNode.java:91)
de.hpi.swa.graal.squeak.nodes.EnterCodeNode.execute(EnterCodeNode.java:34)
org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:328)
org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:318)
	at org.graalvm.compiler.replacements.PEGraphDecoder.tooDeepInlining(PEGraphDecoder.java:1103)
	at org.graalvm.compiler.replacements.PEGraphDecoder.doInline(PEGraphDecoder.java:869)
	at org.graalvm.compiler.replacements.PEGraphDecoder.tryInline(PEGraphDecoder.java:848)
	at org.graalvm.compiler.replacements.PEGraphDecoder.trySimplifyInvoke(PEGraphDecoder.java:722)
	at org.graalvm.compiler.replacements.PEGraphDecoder.handleInvoke(PEGraphDecoder.java:696)
	at org.graalvm.compiler.nodes.GraphDecoder.processNextNode(GraphDecoder.java:584)
	at org.graalvm.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:415)
	at org.graalvm.compiler.replacements.PEGraphDecoder.decode(PEGraphDecoder.java:619)
	at org.graalvm.compiler.truffle.compiler.PartialEvaluator.doGraphPE(PartialEvaluator.java:482)
	at org.graalvm.compiler.truffle.compiler.PartialEvaluator.fastPartialEvaluation(PartialEvaluator.java:520)
	at org.graalvm.compiler.truffle.compiler.PartialEvaluator.createGraph(PartialEvaluator.java:247)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compileAST(TruffleCompilerImpl.java:441)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:624)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:571)
	at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:178)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.doCompile(TruffleCompilerImpl.java:280)
	at org.graalvm.compiler.truffle.compiler.hotspot.libgraal.HotSpotToSVMEntryPoints.doCompile(HotSpotToSVMEntryPoints.java:251)
```

**Comment by fniephaus** [comment]
This still seems to be a problem. Even worse, this causes unusual object allocations, for example lots of `toString()` calls to print the error warnings. And this in turn makes it really hard to use the memory profile in VisualVM. Please advice how this can be fixed.
