### ISSUE TITLE
[native-image] Alternative to using the advice 'Register the class by using org.graalvm.nativeimage.hosted.RuntimeReflection'?

### ISSUE THREAD

**Issue by neomatrix369** [oracle/graal#1601]
After using the native-image of an app that uses the GSon library, at some point I get the below error:

```java
10 Aug 2019 14:40:08.601 WARN Main:generateJSONReportFile Unable to generate JSON report file
java.lang.RuntimeException: Unable to invoke no-args constructor for class org.neomatrix369.common.SomeProject. Registering an InstanceCreator with Gson for this type may fix this problem.
	at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:228)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:212)
	at org.neomatrix369.common.functions.GsonFunctions$PostProcessingEnabler$1.read(GsonFunctions.java:57)
[snipped]
	at org.neomatrix369.cli.Main.run(Main.java:328)
	at org.neomatrix369.cli.Main.main(Main.java:171)
Caused by: java.lang.IllegalArgumentException: Class org.neomatrix369.common.SomeProject is instantiated reflectively but was never registered. Register the class by using org.graalvm.nativeimage.hosted.RuntimeReflection
	at com.oracle.svm.core.genscavenge.graal.AllocationSnippets.checkDynamicHub(AllocationSnippets.java:163)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gson.internal.UnsafeAllocator$1.newInstance(UnsafeAllocator.java:50)
	at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:225)
	... 20 common frames omitted
```

The advice prompted here is to use the `RuntimeReflection` class and register is via my app, I'm guessing using code like this:

```java
@AutomaticFeature
class RuntimeReflectionRegistrationFeature implements Feature {
  public void beforeAnalysis(BeforeAnalysisAccess access) {
    try {
      RuntimeReflection.register(String.class);
      RuntimeReflection.register(/* finalIsWritable: */ true, String.class.getDeclaredField("value"));
      RuntimeReflection.register(String.class.getDeclaredField("hash"));
      RuntimeReflection.register(String.class.getDeclaredConstructor(char[].class));
      RuntimeReflection.register(String.class.getDeclaredMethod("charAt", int.class));
      RuntimeReflection.register(String.class.getDeclaredMethod("format", String.class, Object[].class));
      RuntimeReflection.register(String.CaseInsensitiveComparator.class);
      RuntimeReflection.register(String.CaseInsensitiveComparator.class.getDeclaredMethod("compare", String.class, String.class));
    } catch (NoSuchMethodException | NoSuchFieldException e) { ... }
  }
}
```

Although then I would have to use GraalVM JDK libraries and that creates a dependency between the two, similarly the same is mentioned on [1](https://github.com/oracle/graal/blob/master/substratevm/LIMITATIONS.md#reflection) and [2: the bottom half of the section](https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md#manual-configuration).

Currently, I already have a configuration mentioned in `reflect-config.json`:

```json
{
  "name":"org.neomatrix369.SomeProject",
  "allDeclaredFields":true
},
```

Would this work if I extended the above configuration:

```json
{
  "name":"org.neomatrix369.SomeProject",
  "allDeclaredFields":true
},
```

```json
{
  "name":"org.neomatrix369.SomeProject",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredClasses" : true,
    "allPublicClasses" : true

    <--- and field definitions as shown in the docs? -->
}
```

It's not super clear hence I'm asking.

**Comment by neomatrix369** [comment]
So following my hunch, I did as above:

```
{
  "name":"org.neomatrix369.SomeProject",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredClasses" : true,
    "allPublicClasses" : true

    [ <-- here -->]
}
```

and added field definitions as shown in the docs in the `[ <-- here -->]` section and the advice related to `org.graalvm.nativeimage.hosted.RuntimeReflection` disappeared. And was followed by advice for the `reflect-config.json` file.

**Comment by neomatrix369** [comment]
The above action resolved the issue.
