### ISSUE TITLE
When running On GraalVM 19.2.0 got errors below:

### ISSUE THREAD

**Issue by guanchao-yang** [oracle/graal#1635]
```
Error: Error encountered while parsing java.io.File$TempDirectory.<clinit>()
Parsing context: <no parsing context available>

com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing java.io.File$TempDirectory.<clinit>()
Parsing context: <no parsing context available>

	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:323)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.BigBang$1.run(BigBang.java:384)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.svm.core.util.VMError$HostedError: Error in @InjectAccessors handling of field java.io.File$TempDirectory.random, accessors class com.oracle.svm.core.jdk.Target_java_io_File_TempDirectory$FileTempDirectoryRandomAccessors: found no method named set or setRandom
	at parsing java.io.File$TempDirectory.<clinit>(File.java:1901)
	at org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2499)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:92)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3301)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3103)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:977)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:871)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:221)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:340)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	... 9 more
Caused by: com.oracle.svm.core.util.VMError$HostedError: Error in @InjectAccessors handling of field java.io.File$TempDirectory.random, accessors class com.oracle.svm.core.jdk.Target_java_io_File_TempDirectory$FileTempDirectoryRandomAccessors: found no method named set or setRandom
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:66)
	at com.oracle.svm.hosted.phases.InjectedAccessorsPlugin.error(InjectedAccessorsPlugin.java:152)
	at com.oracle.svm.hosted.phases.InjectedAccessorsPlugin.handleField(InjectedAccessorsPlugin.java:89)
	at com.oracle.svm.hosted.phases.InjectedAccessorsPlugin.handleStoreStaticField(InjectedAccessorsPlugin.java:62)
	at org.graalvm.compiler.java.BytecodeParser.genPutStatic(BytecodeParser.java:4806)
	at org.graalvm.compiler.java.BytecodeParser.genPutStatic(BytecodeParser.java:4777)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5171)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3296)
	... 20 more
Error: Image build request failed with exit status 1
```

**Comment by guanchao-yang** [comment]
No Set method :

![image](https://user-images.githubusercontent.com/32863418/63575400-8fe23180-c5bc-11e9-9134-2fce4436165d.png)

**Comment by cstancu** [comment]
@guanchao-yang can you share more about your use case? Do you delay the initialization of `java.io.File$TempDirectory` at run time? Can you share simple code to replicate this? I think we could simply remove the `Target_java_io_File_TempDirectory` substitution and always run the initializer of `java.io.File$TempDirectory` at run time.

**Comment by guanchao-yang** [comment]
@cansukaynak Yes, I delay the initialization of `java.io.File$TempDirectory` at run time  and config like this `--initialize-at-run-time=java.io.File\$TempDirectory` .  


As user can I simply remove the Target_java_io_File_TempDirectory substitution and always run the initializer of java.io.File$TempDirectory at run time? @cstancu

**Comment by cstancu** [comment]
This issue is not relevant anymore. We removed the `Target_java_io_File_TempDirectory` substitution in the meantime.
