### ISSUE TITLE
[native-image] Kotlin project fails to include JAXP provided by JDK

### ISSUE THREAD

**Issue by boonyasukd** [oracle/graal#1648]
I'm creating [a Quarkus project](https://github.com/boonyasukd/buggy-kotlin-native) (in Kotlin) that generates an Excel file via Apache POI, which requires the use of `JAXP` included as part of Java 8. However, when I created an executable, ran it, and made a REST call to `http://localhost:8080/hello`, I got an error saying that it cannot find resource bundle class `com.sun.org.apache.xml.internal.serializer.utils.SerializerMessages`:

```
...
Caused by: java.util.MissingResourceException: Could not load any resource bundle by com.sun.org.apache.xml.internal.serializer.utils.SerializerMessages
	at com.sun.org.apache.xalan.internal.utils.SecuritySupport$8.run(SecuritySupport.java:182)
	at com.sun.org.apache.xalan.internal.utils.SecuritySupport$8.run(SecuritySupport.java:174)
	at java.security.AccessController.doPrivileged(AccessController.java:69)
	at com.sun.org.apache.xalan.internal.utils.SecuritySupport.getResourceBundle(SecuritySupport.java:174)
	at com.sun.org.apache.xalan.internal.utils.SecuritySupport.getResourceBundle(SecuritySupport.java:164)
	at com.sun.org.apache.xml.internal.serializer.utils.Messages.createMessage(Messages.java:153)
	at com.sun.org.apache.xml.internal.serializer.OutputPropertiesFactory.getDefaultMethodProperties(OutputPropertiesFactory.java:346)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.setDefaults(TransformerImpl.java:1132)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.createOutputProperties(TransformerImpl.java:1092)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.<init>(TransformerImpl.java:254)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.<init>(TransformerImpl.java:245)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:735)
	at org.apache.poi.openxml4j.opc.StreamHelper.getIdentityTransformer(StreamHelper.java:45)
	at org.apache.poi.openxml4j.opc.StreamHelper.saveXmlInStream(StreamHelper.java:61)
	at org.apache.poi.openxml4j.opc.internal.ZipContentTypeManager.saveImpl(ZipContentTypeManager.java:69)
	at org.apache.poi.openxml4j.opc.internal.ContentTypeManager.save(ContentTypeManager.java:452)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:524)
	... 74 more
```
### Notes
- Attempting to fix this by including `com.sun.org.apache.xml.internal.serializer.utils.SerializerMessages` and `com.sun.org.apache.xml.internal.serializer.utils.SerializerMessages_en` into `reflect-config.json` doesn't work. The executable still couldn't find the classes.

- However, if I include a separate dependency [`jaxp-ri` in `pom.xml`](https://github.com/boonyasukd/buggy-kotlin-native/blob/master/pom.xml#L83-L87), the problem goes away. But this is undesirable since the JAXP used is a bit dated (version 1.4 vs 1.6 provided in JDK 8).

- I tried to create another Quarkus Java project, but this time the native executable from Java project actually works without crashing. So I believe the Java counterpart properly includes JAXP from JDK into an executable.

### Environment
```
$ mvn -version
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-05T02:00:29+07:00)
Maven home: /usr/local/Cellar/maven/3.6.1/libexec
Java version: 1.8.0_222, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-19.2.0/Contents/Home/jre
Default locale: en_TH, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"
```

### Command
`jre/bin/native-image` invoked as part of a call `mvn clean package -Pnative`:

```
[INFO] --- quarkus-maven-plugin:0.20.0:native-image (default) @ invoice-generator ---
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] Running Quarkus native-image plugin on OpenJDK 64-Bit GraalVM CE 19.2.0
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] /Library/Java/JavaVirtualMachines/graalvm-ce-19.2.0/Contents/Home/jre/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar invoice-generator-1.0-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http -H:-SpawnIsolates -H:-JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace
```

**Comment by cstancu** [comment]
@boonyasukd you may need to explicitly include the missing resources in the image. Here are the [resources docs](https://github.com/oracle/graal/blob/master/substratevm/RESOURCES.md#accessing-resources-in-substrate-vm-images).

**Comment by boonyasukd** [comment]
@cstancu Thank you for replying. A couple of days after reporting this bug, I added a resource bundle as suggested in the link you provided:

```json
  "bundles":[
    {"name":"com.sun.org.apache.xml.internal.serializer.utils.SerializerMessages"}
  ],
```
Then I arrived at this Exception, where it asked for "output_xml.properties" (snipped for brevity):
```
...
Caused by: com.sun.org.apache.xml.internal.serializer.utils.WrappedRuntimeException: Could not load the propery file 'output_xml.properties' for output method 'xml' (check CLASSPATH)
	at com.sun.org.apache.xml.internal.serializer.OutputPropertiesFactory.getDefaultMethodProperties(OutputPropertiesFactory.java:346)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.setDefaults(TransformerImpl.java:1132)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.createOutputProperties(TransformerImpl.java:1092)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.<init>(TransformerImpl.java:254)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.<init>(TransformerImpl.java:245)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:735)
	at org.apache.poi.openxml4j.opc.StreamHelper.getIdentityTransformer(StreamHelper.java:45)
	at org.apache.poi.openxml4j.opc.StreamHelper.saveXmlInStream(StreamHelper.java:61)
	at org.apache.poi.openxml4j.opc.internal.ZipContentTypeManager.saveImpl(ZipContentTypeManager.java:69)
	at org.apache.poi.openxml4j.opc.internal.ContentTypeManager.save(ContentTypeManager.java:452)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:524)
	... 70 more
```
The problem is, previously, I already ran this app with `-agentlib:native-image-agent`. And inside `META-INF/native-image/resource-config.json`, the agent already added [this line](https://github.com/boonyasukd/buggy-kotlin-native/blob/master/src/main/resources/META-INF/native-image/resource-config.json#L16) to it:

```
    {"pattern":"com/sun/org/apache/xml/internal/serializer/output_xml.properties"}, 
```
But yet, the `native-image` cmd was still unable to include this file into my executable.

In the end, I solved this by recreating this `output_xml.properties` within my own project (under `/resources` folder). And now the executable works without crashing.

**Comment by cstancu** [comment]
@peter-hofer `com/sun/org/apache/xml/internal/serializer/output_xml.properties` is a JDK resource, so it is on the classpath, shouldn't it be included in the image based on the entry in `resource-config.json` above?

**Comment by boonyasukd** [comment]
FYI, last week I spent some time creating/testing a Micronaut project (also kotlin-flavored) with the same functionality. It also ran into the very same problem: recreating `output_xml.properties` in the project is still required.

**Comment by eginez** [comment]
This should now be fixed with https://github.com/oracle/graal/commit/563408ea34f8593f488e1b8cd6d7101effb91f2d

**Comment by Paradox98** [comment]
graalvm 21.0.0.2 
I encountered this problem again
```
Caused by: com.sun.org.apache.xml.internal.serializer.utils.WrappedRuntimeException: Could not load the propery file 'output_xml.properties' for output method 'xml' (check CLASSPATH)
        at com.sun.org.apache.xml.internal.serializer.OutputPropertiesFactory.getDefaultMethodProperties(OutputPropertiesFactory.java:346)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.setDefaults(TransformerImpl.java:1132)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.createOutputProperties(TransformerImpl.java:1092)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.<init>(TransformerImpl.java:254)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.<init>(TransformerImpl.java:245)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:735)
```
