### ISSUE TITLE
[native-image] Building lli.image failed on JDK11

### ISSUE THREAD

**Issue by oroppas** [oracle/graal#1649]
Hi,

Build fails on the master branch

```
Building lli.image... [dependency GRAALVM_UNKNOWN_STAGE1 updated]
[lli:4053]    classlist:   3,836.88 ms
[lli:4053]        (cap):  10,977.66 ms
[lli:4053]        setup:  13,032.49 ms
Warning: RecomputeFieldValue.ArrayBaseOffset automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) was detected in the static initializer of java.util.concurrent.atomic.AtomicReferenceArray. Detailed failure reason(s): Could not determine the field where the value produced by the call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) for the array base offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
Warning: RecomputeFieldValue.ArrayIndexShift automatic substitution failed. The automatic substitution registration was attempted because an ArrayIndexScale computation followed by a call to java.lang.Integer.numberOfLeadingZeros(int) was detected in the static initializer of java.util.concurrent.atomic.AtomicReferenceArray. Detailed failure reason(s): Could not determine the field where the value produced by the subtraction operation 140|- for the array index shift computation is stored. The subtraction is not directly followed by a field store or by a sign extend node followed directly by a field store. 
Warning: RecomputeFieldValue.ArrayIndexScale automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.arrayIndexScale(Class) was detected in the static initializer of java.util.concurrent.atomic.AtomicReferenceArray. Detailed failure reason(s): Could not determine the field where the value produced by the call to jdk.internal.misc.Unsafe.arrayIndexScale(Class) for the array index scale computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
[lli:4053]     analysis:  20,372.52 ms
Error: Error encountered while parsing jdk.internal.vm.annotation.Contended$$ProxyImpl.<init>(java.lang.reflect.InvocationHandler) 
Parsing context:
	parsing com.oracle.svm.reflect.$Proxy138_constructor_886cb99c531e14a26756b354624ad6467a543767_19.newInstance(Unknown Source)
	parsing java.base@11.0.4/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinPool.newInstanceFromSystemProperty(ForkJoinPool.java:2329)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinPool.<init>(ForkJoinPool.java:2345)
	parsing app//com.oracle.svm.core.jdk.ForkJoinPoolCommonAccessor.initializeCommonPool(RecomputedFields.java:435)
	parsing app//com.oracle.svm.core.jdk.ForkJoinPoolCommonAccessor.get(RecomputedFields.java:424)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinTask.tryExternalHelp(ForkJoinTask.java:378)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:323)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:412)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	parsing java.base@11.0.4/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)
	parsing java.base@11.0.4/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	parsing java.base@11.0.4/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	parsing com.oracle.truffle.llvm.launcher.LLVMLauncher.preprocessArguments(LLVMLauncher.java:142)
	parsing org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:95)
	parsing org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:70)
	parsing com.oracle.truffle.llvm.launcher.LLVMLauncher.main(LLVMLauncher.java:53)
	parsing app//com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:151)
	parsing app//com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Error encountered while parsing jdk.internal.vm.annotation.Contended$$ProxyImpl.<init>(java.lang.reflect.InvocationHandler) 
Parsing context:
	parsing com.oracle.svm.reflect.$Proxy138_constructor_886cb99c531e14a26756b354624ad6467a543767_19.newInstance(Unknown Source)
	parsing java.base@11.0.4/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinPool.newInstanceFromSystemProperty(ForkJoinPool.java:2329)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinPool.<init>(ForkJoinPool.java:2345)
	parsing app//com.oracle.svm.core.jdk.ForkJoinPoolCommonAccessor.initializeCommonPool(RecomputedFields.java:435)
	parsing app//com.oracle.svm.core.jdk.ForkJoinPoolCommonAccessor.get(RecomputedFields.java:424)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinTask.tryExternalHelp(ForkJoinTask.java:378)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:323)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:412)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	parsing java.base@11.0.4/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)
	parsing java.base@11.0.4/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	parsing java.base@11.0.4/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	parsing com.oracle.truffle.llvm.launcher.LLVMLauncher.preprocessArguments(LLVMLauncher.java:142)
	parsing org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:95)
	parsing org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:70)
	parsing com.oracle.truffle.llvm.launcher.LLVMLauncher.main(LLVMLauncher.java:53)
	parsing app//com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:151)
	parsing app//com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

Here's how I build

```
JAVA_HOME=/usr/lib/jvm/java-11-openjdk \
PATH=$PATH:$HOME/packages/graal/mx \
mx --max-cpus 1 --dynamicimports /substratevm,/tools,/sulong,/graalpython build
```

**Comment by oroppas** [comment]
```
JAVA_HOME=/usr/lib/jvm/java-11-openjdk \
PATH=$PATH:$HOME/packages/graal/mx \
mx -v --max-cpus 1 --extra-image-builder-argument=-H:+ReportExceptionStackTraces --dynamicimports /substratevm,/tools,/sulong,/graalpython build
```

and the messages with "-H:+ReportExceptionStackTraces"

```
Building lli.image... [dependencies updated: GRAALVM_UNKNOWN_STAGE1]
env MX_HOME=/home/ryuta/packages/graal/mx MX__SUITEMODEL=sibling GRAAL_PYTHONHOME=/home/ryuta/packages/graal/graalpython/graalpython MX_PRIMARY_SUITE_PATH=/home/ryuta/packages/graal/graal/vm MX_SUBPROCESS_COMMAND_FILE=/tmp/mx_subprocess_command.rsepo2f9 \
/home/ryuta/packages/graal/graal/vm/mxbuild/linux-amd64/GRAALVM_UNKNOWN_STAGE1/graalvm-unknown-19.3.0-dev/lib/svm/bin/native-image --macro:lli-launcher -H:NumberOfThreads=1 -H:Path=/home/ryuta/packages/graal/graal/vm/mxbuild/linux-amd64/lli.image
[lli:20904]    classlist:   4,232.62 ms
[lli:20904]        (cap):   3,059.52 ms
[lli:20904]        setup:   5,085.53 ms
Warning: RecomputeFieldValue.ArrayBaseOffset automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) was detected in the static initializer of java.util.concurrent.atomic.AtomicReferenceArray. Detailed failure reason(s): Could not determine the field where the value produced by the call to jdk.internal.misc.Unsafe.arrayBaseOffset(Class) for the array base offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
Warning: RecomputeFieldValue.ArrayIndexShift automatic substitution failed. The automatic substitution registration was attempted because an ArrayIndexScale computation followed by a call to java.lang.Integer.numberOfLeadingZeros(int) was detected in the static initializer of java.util.concurrent.atomic.AtomicReferenceArray. Detailed failure reason(s): Could not determine the field where the value produced by the subtraction operation 140|- for the array index shift computation is stored. The subtraction is not directly followed by a field store or by a sign extend node followed directly by a field store. 
Warning: RecomputeFieldValue.ArrayIndexScale automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.arrayIndexScale(Class) was detected in the static initializer of java.util.concurrent.atomic.AtomicReferenceArray. Detailed failure reason(s): Could not determine the field where the value produced by the call to jdk.internal.misc.Unsafe.arrayIndexScale(Class) for the array index scale computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
[lli:20904]     analysis:  19,608.70 ms
Error: Error encountered while parsing jdk.internal.vm.annotation.Contended$$ProxyImpl.<init>(java.lang.reflect.InvocationHandler) 
Parsing context:
	parsing com.oracle.svm.reflect.$Proxy138_constructor_886cb99c531e14a26756b354624ad6467a543767_19.newInstance(Unknown Source)
	parsing java.base@11.0.4/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinPool.newInstanceFromSystemProperty(ForkJoinPool.java:2329)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinPool.<init>(ForkJoinPool.java:2345)
	parsing app//com.oracle.svm.core.jdk.ForkJoinPoolCommonAccessor.initializeCommonPool(RecomputedFields.java:435)
	parsing app//com.oracle.svm.core.jdk.ForkJoinPoolCommonAccessor.get(RecomputedFields.java:424)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinTask.tryExternalHelp(ForkJoinTask.java:378)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:323)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:412)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	parsing java.base@11.0.4/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)
	parsing java.base@11.0.4/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	parsing java.base@11.0.4/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	parsing com.oracle.truffle.llvm.launcher.LLVMLauncher.preprocessArguments(LLVMLauncher.java:145)
	parsing org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:95)
	parsing org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:70)
	parsing com.oracle.truffle.llvm.launcher.LLVMLauncher.main(LLVMLauncher.java:53)
	parsing app//com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:151)
	parsing app//com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing jdk.internal.vm.annotation.Contended$$ProxyImpl.<init>(java.lang.reflect.InvocationHandler) 
Parsing context:
	parsing com.oracle.svm.reflect.$Proxy138_constructor_886cb99c531e14a26756b354624ad6467a543767_19.newInstance(Unknown Source)
	parsing java.base@11.0.4/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinPool.newInstanceFromSystemProperty(ForkJoinPool.java:2329)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinPool.<init>(ForkJoinPool.java:2345)
	parsing app//com.oracle.svm.core.jdk.ForkJoinPoolCommonAccessor.initializeCommonPool(RecomputedFields.java:435)
	parsing app//com.oracle.svm.core.jdk.ForkJoinPoolCommonAccessor.get(RecomputedFields.java:424)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinTask.tryExternalHelp(ForkJoinTask.java:378)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:323)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:412)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	parsing java.base@11.0.4/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)
	parsing java.base@11.0.4/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	parsing java.base@11.0.4/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	parsing com.oracle.truffle.llvm.launcher.LLVMLauncher.preprocessArguments(LLVMLauncher.java:145)
	parsing org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:95)
	parsing org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:70)
	parsing com.oracle.truffle.llvm.launcher.LLVMLauncher.main(LLVMLauncher.java:53)
	parsing app//com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:151)
	parsing app//com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:327)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.flow.SpecialInvokeTypeFlow.onObservedUpdate(InvokeTypeFlow.java:421)
	at com.oracle.graal.pointsto.flow.TypeFlow.addObserver(TypeFlow.java:314)
	at com.oracle.graal.pointsto.flow.TypeFlow.addObserver(TypeFlow.java:304)
	at com.oracle.graal.pointsto.flow.MethodFlowsGraph.linkClones(MethodFlowsGraph.java:281)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:120)
	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:191)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:343)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:385)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:511)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.oracle.svm.core.util.VMError$HostedError: Manually constructed graph does not terminate control flow properly. lastFixedNode: 0|StartNode
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:66)
	at com.oracle.svm.core.graal.replacements.SubstrateGraphKit.finalizeGraph(SubstrateGraphKit.java:254)
	at com.oracle.svm.hosted.annotation.AnnotationSupport$AnnotationConstructorMethod.buildGraph(AnnotationSupport.java:241)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.buildGraph(AnalysisMethod.java:319)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:185)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:340)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	... 18 more
Error: Error encountered while parsing jdk.internal.vm.annotation.Contended$$ProxyImpl.<init>(java.lang.reflect.InvocationHandler) 
Parsing context:
	parsing com.oracle.svm.reflect.$Proxy138_constructor_886cb99c531e14a26756b354624ad6467a543767_19.newInstance(Unknown Source)
	parsing java.base@11.0.4/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinPool.newInstanceFromSystemProperty(ForkJoinPool.java:2329)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinPool.<init>(ForkJoinPool.java:2345)
	parsing app//com.oracle.svm.core.jdk.ForkJoinPoolCommonAccessor.initializeCommonPool(RecomputedFields.java:435)
	parsing app//com.oracle.svm.core.jdk.ForkJoinPoolCommonAccessor.get(RecomputedFields.java:424)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinTask.tryExternalHelp(ForkJoinTask.java:378)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:323)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:412)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	parsing java.base@11.0.4/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)
	parsing java.base@11.0.4/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	parsing java.base@11.0.4/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	parsing com.oracle.truffle.llvm.launcher.LLVMLauncher.preprocessArguments(LLVMLauncher.java:145)
	parsing org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:95)
	parsing org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:70)
	parsing com.oracle.truffle.llvm.launcher.LLVMLauncher.main(LLVMLauncher.java:53)
	parsing app//com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:151)
	parsing app//com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing jdk.internal.vm.annotation.Contended$$ProxyImpl.<init>(java.lang.reflect.InvocationHandler) 
Parsing context:
	parsing com.oracle.svm.reflect.$Proxy138_constructor_886cb99c531e14a26756b354624ad6467a543767_19.newInstance(Unknown Source)
	parsing java.base@11.0.4/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinPool.newInstanceFromSystemProperty(ForkJoinPool.java:2329)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinPool.<init>(ForkJoinPool.java:2345)
	parsing app//com.oracle.svm.core.jdk.ForkJoinPoolCommonAccessor.initializeCommonPool(RecomputedFields.java:435)
	parsing app//com.oracle.svm.core.jdk.ForkJoinPoolCommonAccessor.get(RecomputedFields.java:424)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinTask.tryExternalHelp(ForkJoinTask.java:378)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:323)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:412)
	parsing java.base@11.0.4/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	parsing java.base@11.0.4/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)
	parsing java.base@11.0.4/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	parsing java.base@11.0.4/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	parsing com.oracle.truffle.llvm.launcher.LLVMLauncher.preprocessArguments(LLVMLauncher.java:145)
	parsing org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:95)
	parsing org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:70)
	parsing com.oracle.truffle.llvm.launcher.LLVMLauncher.main(LLVMLauncher.java:53)
	parsing app//com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:151)
	parsing app//com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:327)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.flow.SpecialInvokeTypeFlow.onObservedUpdate(InvokeTypeFlow.java:421)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:343)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:385)
	at com.oracle.graal.pointsto.flow.SourceTypeFlowBase.update(SourceTypeFlowBase.java:121)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:511)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.oracle.svm.core.util.VMError$HostedError: Manually constructed graph does not terminate control flow properly. lastFixedNode: 0|StartNode
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:66)
	at com.oracle.svm.core.graal.replacements.SubstrateGraphKit.finalizeGraph(SubstrateGraphKit.java:254)
	at com.oracle.svm.hosted.annotation.AnnotationSupport$AnnotationConstructorMethod.buildGraph(AnnotationSupport.java:241)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.buildGraph(AnalysisMethod.java:319)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:185)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:340)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	... 14 more
Error: Image build request failed with exit status 1
[exit code: 1]
  File "/home/ryuta/packages/graal/mx/mx.py", line 19803, in <module>
    main()
  File "/home/ryuta/packages/graal/mx/mx.py", line 19784, in main
    retcode = c(command_args)
  File "/home/ryuta/packages/graal/mx/mx_commands.py", line 147, in __call__
    return self.command_function(*args, **kwargs)
  File "/home/ryuta/packages/graal/graal/substratevm/mx.substratevm/mx_substratevm.py", line 1101, in build
    orig_command_build(args, vm)
  File "/home/ryuta/packages/graal/mx/mx_commands.py", line 147, in __call__
    return self.command_function(*args, **kwargs)
  File "/home/ryuta/packages/graal/mx/mx.py", line 14129, in build
    task.proc.start()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 74, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ryuta/packages/graal/mx/mx.py", line 14112, in executeTask
    task.execute()
  File "/home/ryuta/packages/graal/mx/mx.py", line 4559, in execute
    _built = self.build()
  File "/home/ryuta/packages/graal/graal/vm/mx.vm/mx_vm.py", line 1646, in build
    self.svm_support.native_image(build_args, output_file)
  File "/home/ryuta/packages/graal/graal/vm/mx.vm/mx_vm.py", line 875, in native_image
    return mx.run(native_image_command, nonZeroIsFatal=nonZeroIsFatal, out=out, err=err)
  File "/home/ryuta/packages/graal/mx/mx.py", line 13078, in run
    abort(retcode)
  File "/home/ryuta/packages/graal/mx/mx.py", line 3735, in abort
    traceback.print_stack()

Building lli.image failed
[Stopped javac-daemon on port 46123 for Java 11.0.4 (11) from /usr/lib/jvm/java-11-openjdk]
[Stopped javac-daemon on port 43299 for Java 11.0.4 (11) from /usr/lib/jvm/java-11-openjdk]
Shutting down
Shutting down
Traceback (most recent call last):
  File "/home/ryuta/packages/graal/mx/mx.py", line 19803, in <module>
    main()
  File "/home/ryuta/packages/graal/mx/mx.py", line 19784, in main
    retcode = c(command_args)
  File "/home/ryuta/packages/graal/mx/mx_commands.py", line 147, in __call__
    return self.command_function(*args, **kwargs)
  File "/home/ryuta/packages/graal/graal/substratevm/mx.substratevm/mx_substratevm.py", line 1101, in build
    orig_command_build(args, vm)
  File "/home/ryuta/packages/graal/mx/mx_commands.py", line 147, in __call__
    return self.command_function(*args, **kwargs)
  File "/home/ryuta/packages/graal/mx/mx.py", line 14148, in build
    abort('{0} build tasks failed'.format(len(failed)))
  File "/home/ryuta/packages/graal/mx/mx.py", line 3717, in abort
    if _is_process_alive(p):
  File "/home/ryuta/packages/graal/mx/mx.py", line 3677, in _is_process_alive
    return p.is_alive()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 148, in is_alive
    self._check_closed()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 92, in _check_closed
    raise ValueError("process object is closed")
ValueError: process object is closed
```
