### ISSUE TITLE
--enable-all-security-services fails on Windows

### ISSUE THREAD

**Issue by Runemoro** [oracle/graal#1663]
```
error LNK2001: unresolved external symbol Java_sun_security_mscapi_KeyStore_loadKeysOrCertificateChains
error LNK2001: unresolved external symbol Java_sun_security_mscapi_PRNG_generateSeed
error LNK2001: unresolved external symbol Java_sun_security_smartcardio_PCSC_SCardEstablishContext
```

**Comment by lilili87222** [comment]
The same error when I compile with native image on windows.

**Comment by kangzq0530** [comment]
The same error I found both on windows10 and windows7 with Graalvm-ee-19.2.0. HelloWorld is OK. Output:

Setting SDK environment relative to C:\Program Files\Microsoft SDKs\Windows\v7.1\.
Targeting Windows 7 x64 Debug

[authserver:10568]    classlist:  11,558.60 ms
[authserver:10568]        (cap):   3,754.60 ms
[authserver:10568]        setup:   6,095.66 ms
[authserver:10568]   (typeflow):  48,039.85 ms
[authserver:10568]    (objects):  34,804.77 ms
[authserver:10568]   (features):   5,183.28 ms
[authserver:10568]     analysis:  94,787.97 ms
[authserver:10568]     (clinit):   2,471.14 ms
[authserver:10568]     universe:   5,253.58 ms
[authserver:10568]      (parse):   8,744.73 ms
[authserver:10568]     (inline):   5,084.14 ms
[authserver:10568]    (compile):  85,082.10 ms
[authserver:10568]      compile: 104,440.12 ms
[authserver:10568]        image:   8,004.66 ms
[authserver:10568]        write:     879.60 ms
Fatal error: java.lang.RuntimeException: java.lang.RuntimeException: host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 2

Running command: CL /MD /Zi /PDBSTRIPPED /FeD:\programming\workspace\java\ethanms-authserver\authserver.exe C:\Users\HP\AppData\Local\Temp\SVM-5060476321446349851\authserver.obj C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\ffi.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\java.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\net.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\nio.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\libchelper.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\strictmath.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\jvm.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\zip.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\ffi.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\java.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\net.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\nio.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\libchelper.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\strictmath.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\jvm.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\zip.lib /link /INCREMENTAL:NO /NODEFAULTLIB:LIBCMT /NODEFAULTLIB:OLDNAMES /LIBPATH:C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib /LIBPATH:C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64 jitdebug.lib advapi32.lib ws2_32.lib secur32.lib iphlpapi.lib

Microsoft (R) C/C++ Optimizing Compiler Version 16.00.30319.01 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '/PDBSTRIPPED'
Microsoft (R) Incremental Linker Version 10.00.30319.01
Copyright (C) Microsoft Corporation.  All rights reserved.

/debug
/out:D:\programming\workspace\java\ethanms-authserver\authserver.exe
/INCREMENTAL:NO /NODEFAULTLIB:LIBCMT /NODEFAULTLIB:OLDNAMES
"/LIBPATH:C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib"
"/LIBPATH:C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64"
jitdebug.lib
advapi32.lib
ws2_32.lib
secur32.lib
iphlpapi.lib
C:\Users\HP\AppData\Local\Temp\SVM-5060476321446349851\authserver.obj
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\ffi.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\java.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\net.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\nio.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\libchelper.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\strictmath.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\jvm.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\zip.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\ffi.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\java.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\net.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\nio.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\libchelper.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\strictmath.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\jvm.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\zip.lib"
   Creating library D:\programming\workspace\java\ethanms-authserver\authserver.lib and object D:\programming\workspace\java\ethanms-authserver\authserver.exp
authserver.obj : error LNK2001: unresolved external symbol Java_java_lang_Thread_resume0
authserver.obj : error LNK2001: unresolved external symbol Java_java_lang_Thread_stop0
authserver.obj : error LNK2001: unresolved external symbol Java_java_lang_Thread_suspend0
authserver.obj : error LNK2001: unresolved external symbol Java_sun_reflect_Reflection_getCallerClass
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_ec_ECDHKeyAgreement_deriveKey
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_ec_ECDSASignature_signDigest
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_ec_ECDSASignature_verifySignedDigest
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_ec_ECKeyPairGenerator_generateECKeyPair
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_krb5_Config_getWindowsDirectory
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_krb5_SCDynamicStoreConfig_getKerberosConfig
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_KeyStore_generatePrivateKeyBlob
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_KeyStore_loadKeysOrCertificateChains
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_KeyStore_storeCertificate
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_KeyStore_storePrivateKey
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_PRNG_generateSeed
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_RSAKeyPairGenerator_generateRSAKeyPair
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_RSASignature_generatePublicKeyBlob
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_RSASignature_importPublicKey
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_smartcardio_PCSC_SCardEstablishContext
D:\programming\workspace\java\ethanms-authserver\authserver.exe : fatal error LNK1120: 19 unresolved externals

        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:461)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:310)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:448)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:113)
Caused by: java.lang.RuntimeException: host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 2

Running command: CL /MD /Zi /PDBSTRIPPED /FeD:\programming\workspace\java\ethanms-authserver\authserver.exe C:\Users\HP\AppData\Local\Temp\SVM-5060476321446349851\authserver.obj C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\ffi.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\java.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\net.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\nio.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\libchelper.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\strictmath.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\jvm.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\zip.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\ffi.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\java.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\net.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\nio.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\libchelper.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\strictmath.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\jvm.lib C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\zip.lib /link /INCREMENTAL:NO /NODEFAULTLIB:LIBCMT /NODEFAULTLIB:OLDNAMES /LIBPATH:C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib /LIBPATH:C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64 jitdebug.lib advapi32.lib ws2_32.lib secur32.lib iphlpapi.lib

Microsoft (R) C/C++ Optimizing Compiler Version 16.00.30319.01 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '/PDBSTRIPPED'
Microsoft (R) Incremental Linker Version 10.00.30319.01
Copyright (C) Microsoft Corporation.  All rights reserved.

/debug
/out:D:\programming\workspace\java\ethanms-authserver\authserver.exe
/INCREMENTAL:NO /NODEFAULTLIB:LIBCMT /NODEFAULTLIB:OLDNAMES
"/LIBPATH:C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib"
"/LIBPATH:C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64"
jitdebug.lib
advapi32.lib
ws2_32.lib
secur32.lib
iphlpapi.lib
C:\Users\HP\AppData\Local\Temp\SVM-5060476321446349851\authserver.obj
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\ffi.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\java.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\net.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\nio.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\libchelper.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\strictmath.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\jvm.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\zip.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\ffi.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\java.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\net.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\nio.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\libchelper.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\strictmath.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\svm\clibraries\windows-amd64\jvm.lib"
"C:\Program Files\Java\graalvm-ee-19.2.0\jre\lib\zip.lib"
   Creating library D:\programming\workspace\java\ethanms-authserver\authserver.lib and object D:\programming\workspace\java\ethanms-authserver\authserver.exp
authserver.obj : error LNK2001: unresolved external symbol Java_java_lang_Thread_resume0
authserver.obj : error LNK2001: unresolved external symbol Java_java_lang_Thread_stop0
authserver.obj : error LNK2001: unresolved external symbol Java_java_lang_Thread_suspend0
authserver.obj : error LNK2001: unresolved external symbol Java_sun_reflect_Reflection_getCallerClass
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_ec_ECDHKeyAgreement_deriveKey
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_ec_ECDSASignature_signDigest
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_ec_ECDSASignature_verifySignedDigest
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_ec_ECKeyPairGenerator_generateECKeyPair
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_krb5_Config_getWindowsDirectory
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_krb5_SCDynamicStoreConfig_getKerberosConfig
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_KeyStore_generatePrivateKeyBlob
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_KeyStore_loadKeysOrCertificateChains
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_KeyStore_storeCertificate
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_KeyStore_storePrivateKey
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_PRNG_generateSeed
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_RSAKeyPairGenerator_generateRSAKeyPair
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_RSASignature_generatePublicKeyBlob
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_mscapi_RSASignature_importPublicKey
authserver.obj : error LNK2001: unresolved external symbol Java_sun_security_smartcardio_PCSC_SCardEstablishContext
D:\programming\workspace\java\ethanms-authserver\authserver.exe : fatal error LNK1120: 19 unresolved externals

        at com.oracle.svm.hosted.image.NativeBootImageViaCC.write(NativeBootImageViaCC.java:350)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:657)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1

**Comment by lilili87222** [comment]
It may caused by not load .lib file
I add

getNativeLibraries().addLibrary("sunec", true);

it stop ec problem ,but mscapi.lib file not found .

tested windows 7 amd64, graalvm 19.2.1

can you  add those .lib files ? @thomaswue

**Comment by thomaswue** [comment]
@pejovica Can you check this? CC @cstancu
