### ISSUE TITLE
[jvmci] Unresolved compilation problems

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#1670]
Reproducible on `openjdk1.8.0_222-jvmci-19.2-b02` and `openjdk1.8.0_222-jvmci-19.3-b02` for macOS.

```
Thread[JVMCI CompilerThread2,9,system]: Compilation of java.lang.String.toUpperCase(Locale) @ 157 failed:
org.graalvm.compiler.graph.GraalGraphError: java.lang.Error: Unresolved compilation problem:
	The method get(ResolvedJavaType, int) in the type VirtualObject is not applicable for the arguments (ResolvedJavaType, int, boolean)

	at node: 265|Deopt
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.doBlock(NodeLIRBuilder.java:380)
	at org.graalvm.compiler.core.LIRGenerationPhase.emitBlock(LIRGenerationPhase.java:85)
	at org.graalvm.compiler.core.LIRGenerationPhase.run(LIRGenerationPhase.java:75)
	at org.graalvm.compiler.core.LIRGenerationPhase.run(LIRGenerationPhase.java:46)
	at org.graalvm.compiler.lir.phases.LIRPhase.apply(LIRPhase.java:117)
	at org.graalvm.compiler.lir.phases.LIRPhase.apply(LIRPhase.java:109)
	at org.graalvm.compiler.core.gen.LIRCompilerBackend.emitLIR0(LIRCompilerBackend.java:154)
	at org.graalvm.compiler.core.gen.LIRCompilerBackend.emitLIR(LIRCompilerBackend.java:113)
	at org.graalvm.compiler.core.gen.LIRCompilerBackend.emitBackEnd(LIRCompilerBackend.java:83)
	at org.graalvm.compiler.core.target.Backend.emitBackEnd(Backend.java:279)
	at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:145)
	at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:129)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileHelper(HotSpotGraalCompiler.java:227)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:245)
	at org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:170)
	at org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:84)
	at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:178)
	at org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:334)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:144)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:109)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:667)
Caused by: java.lang.Error: Unresolved compilation problem:
	The method get(ResolvedJavaType, int) in the type VirtualObject is not applicable for the arguments (ResolvedJavaType, int, boolean)

	at org.graalvm.compiler.serviceprovider.GraalServices.createVirtualObject(GraalServices.java:504)
	at org.graalvm.compiler.core.gen.DebugInfoBuilder.toJavaValue(DebugInfoBuilder.java:323)
	at org.graalvm.compiler.core.gen.DebugInfoBuilder.computeStack(DebugInfoBuilder.java:279)
	at org.graalvm.compiler.core.gen.DebugInfoBuilder.computeFrameForState(DebugInfoBuilder.java:247)
	at org.graalvm.compiler.hotspot.HotSpotDebugInfoBuilder.computeFrameForState(HotSpotDebugInfoBuilder.java:94)
	at org.graalvm.compiler.core.gen.DebugInfoBuilder.computeFrameForState(DebugInfoBuilder.java:252)
	at org.graalvm.compiler.hotspot.HotSpotDebugInfoBuilder.computeFrameForState(HotSpotDebugInfoBuilder.java:94)
	at org.graalvm.compiler.core.gen.DebugInfoBuilder.build(DebugInfoBuilder.java:103)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.stateForWithExceptionEdge(NodeLIRBuilder.java:757)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.stateFor(NodeLIRBuilder.java:749)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.state(NodeLIRBuilder.java:738)
	at org.graalvm.compiler.nodes.DeoptimizeNode.generate(DeoptimizeNode.java:119)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.emitNode(NodeLIRBuilder.java:482)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.doRoot(NodeLIRBuilder.java:473)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.doBlock(NodeLIRBuilder.java:376)
	... 20 more
```

/cc @dougxc

**Comment by dougxc** [comment]
This looks like an Eclipse compiler problem (based on the deferred Java compiler error).
Can you please provide steps to reproduce.

**Comment by fniephaus** [comment]
Closing this issue as I can no longer reproduce the problem on `19.2.0.1`...
