### ISSUE TITLE
Failed to run native image that uses  org.jline.terminal.TerminalBuilder

### ISSUE THREAD

**Issue by ahelmbr** [oracle/graal#1694]
I wrote a simple HelloWorld Terminal App zu extract the problems from my Application

with jline.terminal 

this is my main class
```
package main;

import org.jline.terminal.Terminal;
import org.jline.terminal.TerminalBuilder;
import java.io.IOException;
import java.io.PrintWriter;

public class HelloTerminal {
    public static void main(String[] args) {
        try {
            Terminal terminal = TerminalBuilder.builder().dumb(true).build();
            final PrintWriter terminalWriter = terminal.writer();
            terminalWriter.println("Hello Terminal");
            terminalWriter.flush();
        } catch (IOException ignored) {
            // :(
        }
    }
}
```

Here is my gradle build file
```
buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "gradle.plugin.com.palantir.graal:gradle-graal:0.2.0"
    }
}
repositories {
    jcenter()
}

apply plugin: 'java'
apply plugin: "com.palantir.graal"

group 'com.test'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

graal {
    mainClass 'main.HelloTerminal'
    outputName 'hello'
    graalVersion '19.2.0'
    option '--verbose'
    option '--allow-incomplete-classpath'
    option '--report-unsupported-elements-at-runtime'
    option '-H:IncludeResources="org/jline/utils/*.*'
    option '-H:IncludeResources="org/jline/terminal/*.*'
}

ext {
    jline3Version = '3.12.1'
    jline3JansiVersion = '3.12.1'
}

dependencies {
    compile group: 'org.jline', name: 'jline', version: jline3Version
    compile group: 'org.jline', name: 'jline-terminal-jansi', version: jline3JansiVersion
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
}

```

I can build the native image without any errors or warnings
But running my image - i have the following error.

```
Anjas-MBP:graalvm-terminal ahelmbre$ ./build/graal/hello 
Exception in thread "main" java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at org.jline.utils.InputStreamReader.<init>(InputStreamReader.java:135)
        at org.jline.utils.InfoCmp.loadDefaultInfoCmp(InfoCmp.java:610)
        at org.jline.utils.InfoCmp.lambda$static$3(InfoCmp.java:621)
        at org.jline.utils.InfoCmp.getLoadedInfoCmp(InfoCmp.java:557)
        at org.jline.terminal.impl.AbstractTerminal.parseInfoCmp(AbstractTerminal.java:193)
        at org.jline.terminal.impl.DumbTerminal.<init>(DumbTerminal.java:88)
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:401)
        at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:259)
        at main.HelloTerminal.main(HelloTerminal.java:13)
```

Has somebody an idea what i should change?

**Comment by ahelmbr** [comment]
we added further resources 
```
{
  "resources": [
    {"pattern": ".*.caps"},
    {"pattern": ".*.txt"}
  ]
}
```
and used them in the build.gradle graal task
`option "-H:ResourceConfigurationFiles=${rootProject.rootDir}/graal/resources.json"
`

Now the native image  works!

**Comment by cstancu** [comment]
@ahelmbr good to hear that you got it working! Thanks for reporting back!
