### ISSUE TITLE
AArch64 gate test BootstrapWithSystemAssertionsNoCoop failed

### ISSUE THREAD

**Issue by pli-arm** [oracle/graal#1704]
HotSpot crashes because of segmentation fault when running mx gate test with JDK13 or JDK master (14). This issue can be reproduced by below test command.
`mx gate -t BootstrapWithSystemAssertionsNoCoop`

Output
```
Bootstrapping JVMCI.......................#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000ffffae7806f4, pid=183338, tid=183371
#
# JRE version: OpenJDK Runtime Environment (13.0) (build 13-internal+0-adhoc.penli01.jdksrc)
# Java VM: OpenJDK 64-Bit Server VM (13-internal+0-adhoc.penli01.jdksrc, mixed mode, jvmci, jvmci compiler, g1 gc, linux-aarch64)
# Problematic frame:
# V  [libjvm.so+0xc976f4]  StackValue::create_stack_value(frame const*, RegisterMap const*, ScopeValue*)+0x32c
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P" (or dumping to /home/penli01/graal/compiler/core.183338)
#
# An error report file with more information is saved as:
# /home/penli01/graal/compiler/hs_err_pid183338.log
Compiled method (JVMCI)   47336 1136             org.graalvm.compiler.nodes.cfg.ControlFlowGraph::visitDominatorTreeDefault (279 bytes)
 total in heap  [0x0000ffff9b4a5090,0x0000ffff9b4aab18] = 23176
 relocation     [0x0000ffff9b4a51f0,0x0000ffff9b4a5588] = 920
 main code      [0x0000ffff9b4a55c0,0x0000ffff9b4a9a80] = 17600
 stub code      [0x0000ffff9b4a9a80,0x0000ffff9b4a9b40] = 192
 oops           [0x0000ffff9b4a9b40,0x0000ffff9b4a9b48] = 8
 metadata       [0x0000ffff9b4a9b48,0x0000ffff9b4a9c68] = 288
 scopes data    [0x0000ffff9b4a9c68,0x0000ffff9b4aa4d8] = 2160
 scopes pcs     [0x0000ffff9b4aa4d8,0x0000ffff9b4aaa48] = 1392
 dependencies   [0x0000ffff9b4aaa48,0x0000ffff9b4aaa60] = 24
 nul chk table  [0x0000ffff9b4aaa60,0x0000ffff9b4aab08] = 168
 JVMCI data     [0x0000ffff9b4aab08,0x0000ffff9b4aab18] = 16
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

GDB backtrace message
```
#8  <signal handler called>
#9  oop::obj (this=0x0) at /home/penli01/jdk_src/src/hotspot/share/oops/oopsHierarchy.hpp:99
#10 oop::oop (o=..., this=0xfff62dfe9bc8) at /home/penli01/jdk_src/src/hotspot/share/oops/oopsHierarchy.hpp:92
#11 StackValue::create_stack_value (fr=fr@entry=0xfff5b4084e38, reg_map=reg_map@entry=0x0, sv=<optimized out>)
    at /home/penli01/jdk_src/src/hotspot/share/runtime/stackValue.cpp:125
#12 0x0000ffffbefb6f74 in compiledVFrame::create_stack_value (sv=<optimized out>, this=0xfff5b4084e20) at /home/penli01/jdk_src/src/hotspot/share/runtime/vframe_hp.cpp:167
#13 compiledVFrame::locals (this=0xfff5b4084e20) at /home/penli01/jdk_src/src/hotspot/share/runtime/vframe_hp.cpp:62
#14 0x0000ffffbefb0f8c in vframeArrayElement::fill_in (this=this@entry=0xfff5ec096558, vf=0xfff5b4084e20, realloc_failures=realloc_failures@entry=false)
    at /home/penli01/jdk_src/src/hotspot/share/runtime/vframeArray.cpp:114
#15 0x0000ffffbefb3e5c in vframeArray::fill_in (this=0xfff5ec095d10, thread=<optimized out>, frame_size=<optimized out>, chunk=0xfff7486d8af0, reg_map=0xfff62dfea190,
    realloc_failures=<optimized out>) at /home/penli01/jdk_src/src/hotspot/share/runtime/vframeArray.cpp:524
#16 0x0000ffffbefb3f5c in vframeArray::allocate (thread=thread@entry=0xfff7486d8000, frame_size=22, chunk=chunk@entry=0xfff7486d8af0, reg_map=reg_map@entry=0xfff62dfea190,
    sender=..., caller=..., self=..., realloc_failures=false, realloc_failures@entry=255) at /home/penli01/jdk_src/src/hotspot/share/runtime/vframeArray.cpp:511
#17 0x0000ffffbe261aa8 in Deoptimization::create_vframeArray (thread=thread@entry=0xfff7486d8000, fr=..., reg_map=reg_map@entry=0xfff62dfea190, chunk=chunk@entry=0xfff7486d8af0,
    realloc_failures=255, realloc_failures@entry=false) at /home/penli01/jdk_src/src/hotspot/share/runtime/deoptimization.cpp:1388
#18 0x0000ffffbe267084 in Deoptimization::fetch_unroll_info_helper (thread=0xfff7486d8000, exec_mode=65535)
    at /home/penli01/jdk_src/src/hotspot/share/runtime/deoptimization.cpp:332
```

**Comment by pli-arm** [comment]
@mur47x111 I found this failure firstly appears after your "unaligned bulk zeroing on AArch64" patch and the bootstrap test passes with jdk11u (where dczid is not available in that JVMCI).

**Comment by mur47x111** [comment]
I will take a look, thanks for the report!

**Comment by mur47x111** [comment]
@pli-arm Could you please verify if https://github.com/oracle/graal/commit/e4d9c5f09a3c9be9f3c66ff0feff787519875a12 address the issue? We are also preparing a patch like https://github.com/graalvm/labs-openjdk-11/commit/ba6a33ceb41fffdb0da22f5536fa2c760853bf7d towards JDK14

**Comment by pli-arm** [comment]
@mur47x111  Sorry for my late reply. I'm just back from the Chinese national holiday. I see this fix is already merged.

I can't rerun the gate test now since current graal compiler master cannot build with JDK 13/14 (I've created another issue #1723). But I've verified that the bootstrap can pass if I cherry-pick this fix to a previous code base. Thanks for your quick fix. I will close this.
