### ISSUE TITLE
[native-image] NPE at CompileQueue.defaultCompileFunction

### ISSUE THREAD

**Issue by lburgazzoli** [oracle/graal#1707]
I've been facing the following issue while building a native image with support for graal js:

```
Fatal error: java.lang.NullPointerException
	at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:931)
	at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:917)
	at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:259)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
For a reproducer:

- checkout https://github.com/lburgazzoli/apache-camel-k-runtime/tree/github-57
- mvn clean install -DskipTests=true
- mvn install -Dnative -rf :camel-k-quarkus-loader-js-it

May be related to https://github.com/graalvm/graaljs/issues/209

**Comment by cstancu** [comment]
@lburgazzoli it looks like your code is using `<graalvm.version>19.1.1</graalvm.version>`. Can you please try with the latest GraalVM version and let me know if you run in the same issue?

**Comment by lburgazzoli** [comment]
@cstancu it does not happen anymore in 19.2.0.1
