### ISSUE TITLE
NoClassDefFoundError: Ljava/net/SocketTimeoutException

### ISSUE THREAD

**Issue by mcred** [oracle/graal#1710]
We have an application that works on linux and osx, but the binary fails on windows in a weird way. The error for `java.lang.NoClassDefFoundError: Ljava/net/SocketTimeoutException;` confuses me because the application can call `throw SocketTimeoutException()` without any issues. It looks like there is an issue somewhere in `socketRead0` in the native code. Any suggestion on how we can get past this?

Things we've tried to get past this issue:
*   Include `java.net.SocketTimeoutException` in the code for the application hoping the compiler will include it in the binary
*   Add `java.net.SocketTimeoutException` to the `resource-config.json`
*   Add `--initialize-at-run-time` and `--initialize-at-build-time` for `java.net.SocketTimeoutException` during the `native-image` command

Full Stack Trace:
```
java.lang.NoClassDefFoundError: Ljava/net/SocketTimeoutException;
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:328)
        at java.net.SocketInputStream.socketRead0(SocketInputStream.java)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.exhausted(RealBufferedSource.java:61)
        at okhttp3.internal.connection.RealConnection.isHealthy(RealConnection.java:591)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:120)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:221)
        at okhttp3.RealCall.execute(RealCall.java:81)
        at io.titandata.client.apis.RepositoriesApi.updateRepository(RepositoriesApi.kt:955)
        at io.titandata.titan.providers.local.Run.run(Run.kt:70)
        at io.titandata.titan.providers.local.Run.run$default(Run.kt:20)
        at io.titandata.titan.providers.Local.run(Local.kt:129)
        at io.titandata.titan.commands.Run.run(Run.kt:27)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:112)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:19)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:166)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:164)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:181)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:200)
        at io.titandata.titan.Cli.main(Cli.kt:60)
```

**Comment by kangzq0530** [comment]
Have you tried add the class into jni-config.json?

**Comment by cstancu** [comment]
@mcred, as @kangzq0530 suggested, it looks like you need to register `Ljava/net/SocketTimeoutException;` as thrown from native code. As detailed in the [docs](https://github.com/oracle/graal/blob/master/substratevm/JNI.md) " Individual classes, methods, and fields that should be accessible via JNI must be specified during native image generation in a configuration file". You should also give the [`native-image-agent`](https://github.com/oracle/graal/blob/master/substratevm/CONFIGURE.md) a try as it automates the discovery of dynamically accessed elements and it can assist you in generating the config files. If you provide reproducible code we can take a closer look.

**Comment by mcred** [comment]
JNI config was the issue!

The weird thing is that the native-image-agent doesn't pick up this particular class. Once it was manually added it worked.

**Comment by thomaswue** [comment]
CC @peter-hofer regarding the question whether the agent should pick up this class.
