### ISSUE TITLE
[native-image] VMError.shouldNotReachHere: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by chrisseaton** [oracle/graal#1713]
I get this error while building a native image.

```
Fatal error: com.oracle.svm.core.util.VMError$HostedError: java.lang.reflect.InvocationTargetException
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:70)
	at com.oracle.svm.hosted.annotation.AnnotationSubstitutionField.readValue(AnnotationSubstitutionField.java:131)
	at com.oracle.svm.core.meta.ReadableJavaField.readFieldValue(ReadableJavaField.java:35)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:100)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:75)
	at com.oracle.graal.pointsto.ObjectScanner.scanField(ObjectScanner.java:175)
	at com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:344)
	at com.oracle.graal.pointsto.ObjectScanner.access$400(ObjectScanner.java:62)
	at com.oracle.graal.pointsto.ObjectScanner$3$1.run(ObjectScanner.java:414)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.oracle.svm.hosted.annotation.AnnotationSubstitutionField.readValue(AnnotationSubstitutionField.java:114)
	... 13 more
Caused by: java.lang.annotation.IncompleteAnnotationException: com.xruby.runtime.lang.annotation.RubyLevelClass missing element dummy
	at sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:81)
	at com.sun.proxy.$Proxy133.dummy(Unknown Source)
	... 18 more
```

The program runs as a normal Java application, and`IncompleteAnnotationException` doesn't make any sense to me - `dummy` has a default value.

```java
...
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface RubyLevelClass {
	String name();
	String superclass() default "Object";
	String[] modules() default {};
	UndefMethod[] undef() default {};
	DummyMethod[] dummy() default {};
}
...
```

```
$ javap -classpath xruby-0.3.3.jar -v com.xruby.runtime.lang.annotation.RubyLevelClass
...
  public abstract com.xruby.runtime.lang.annotation.DummyMethod[] dummy();
    descriptor: ()[Lcom/xruby/runtime/lang/annotation/DummyMethod;
    flags: ACC_PUBLIC, ACC_ABSTRACT
Error: java.lang.reflect.InvocationTargetException
      AnnotationDefault: length = 0x0
...
```

```bash
$ export JAVA_HOME=$PWD/graalvm-ce-19.2.0.1
$ PATH=$JAVA_HOME/bin:$PATH
$ git clone https://github.com/chrisseaton/xruby-archive.git xruby
$ pushd xruby
$ sh build.sh
$ popd
$ cp xruby/*.jar .
$ java -noverify -jar xruby-0.3.3.jar -c fib.rb
$ native-image -J-noverify -jar fib.jar
```

This is very dusty code, hence, the `-noverify` to get around the lack of a stackmap.

**Comment by fernando-valdez** [comment]
issue not longer present
