### ISSUE TITLE
Could not find any source file for 'file:/usr/lib/jvm/java-11-openjdk/lib/*.a'

### ISSUE THREAD

**Issue by oroppas** [oracle/graal#1718]
Hi,

Building fails on Arch Linux as the error message on the title.

Here's how I build:

```
JAVA_HOME=/usr/lib/jvm/java-11-openjdk \
PATH=$PATH:$HOME/packages/graal/mx \
mx -v --max-cpus 1 --dynamicimports /substratevm,/tools,/sulong,/graalpython build
```

Here's the full error log:

```
Archiving GRAALVM_UNKNOWN_JAVA11_STAGE1... [dependencies updated: graalpython-launcher_native-image.properties, graalvm-jimage, graalvm-native-clang++-launcher_native-image.properties, graalvm-native-clang-launcher_native-image.properties, native-image-agent-library_native-image.properties, native-image-configure-launcher_native-image.properties, native-image-launcher_native-image.properties, polyglot-library_native-image.properties]
Directory: /home/ryuta/packages/graal/graal
env MX_HOME=/home/ryuta/packages/graal/mx MX__SUITEMODEL=sibling MX_PRIMARY_SUITE_PATH=/home/ryuta/packages/graal/graal/vm MX_SUBPROCESS_COMMAND_FILE=/tmp/mx_subprocess_command.z1oth76b \
git ls-files '/usr/lib/jvm/java-11-openjdk/lib/*.a'
WARNING:   GRAALVM_UNKNOWN_JAVA11_STAGE1:
Adding file which is not in the repository: '/usr/lib/jvm/java-11-openjdk/lib/*.a' in 'graalvm-unknown-java11-19.3.0-dev/lib/'
  File "/home/ryuta/packages/graal/mx/mx.py", line 19146, in <module>
    main()
  File "/home/ryuta/packages/graal/mx/mx.py", line 19127, in main
    retcode = c(command_args)
  File "/home/ryuta/packages/graal/mx/mx_commands.py", line 147, in __call__
    return self.command_function(*args, **kwargs)
  File "/home/ryuta/packages/graal/graal/substratevm/mx.substratevm/mx_substratevm.py", line 1109, in build
    orig_command_build(args, vm)
  File "/home/ryuta/packages/graal/mx/mx_commands.py", line 147, in __call__
    return self.command_function(*args, **kwargs)
  File "/home/ryuta/packages/graal/mx/mx.py", line 13442, in build
    task.proc.start()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 74, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ryuta/packages/graal/mx/mx.py", line 13425, in executeTask
    task.execute()
  File "/home/ryuta/packages/graal/mx/mx.py", line 4654, in execute
    _built = self.build()
  File "/home/ryuta/packages/graal/graal/vm/mx.vm/mx_vm.py", line 786, in build
    super(GraalVmLayoutDistributionTask, self).build()
  File "/home/ryuta/packages/graal/mx/mx.py", line 4972, in build
    self.subject.make_archive()
  File "/home/ryuta/packages/graal/mx/mx.py", line 5739, in make_archive
    self._install_source(source, output, destination, arc)
  File "/home/ryuta/packages/graal/mx/mx.py", line 5683, in _install_source
    _install_source_files(((source_file, _arcname_f(source_file)) for source_file in glob.iglob(file_path)), include=source_path, excludes=source.get('exclude'))
  File "/home/ryuta/packages/graal/mx/mx.py", line 5520, in _install_source_files
    abort("Could not find any source file for '{}'".format(source['_str_']), context=self)
  File "/home/ryuta/packages/graal/mx/mx.py", line 3749, in abort
    traceback.print_stack()
  GRAALVM_UNKNOWN_JAVA11_STAGE1:
Could not find any source file for 'file:/usr/lib/jvm/java-11-openjdk/lib/*.a'
Archiving GRAALVM_UNKNOWN_JAVA11_STAGE1 failed
[Stopped javac-daemon on port 36795 for Java 11.0.4 (11) from /usr/lib/jvm/java-11-openjdk]
[Stopped javac-daemon on port 37777 for Java 11.0.4 (11) from /usr/lib/jvm/java-11-openjdk]
Shutting down
Shutting down
Traceback (most recent call last):
  File "/home/ryuta/packages/graal/mx/mx.py", line 19146, in <module>
    main()
  File "/home/ryuta/packages/graal/mx/mx.py", line 19127, in main
    retcode = c(command_args)
  File "/home/ryuta/packages/graal/mx/mx_commands.py", line 147, in __call__
    return self.command_function(*args, **kwargs)
  File "/home/ryuta/packages/graal/graal/substratevm/mx.substratevm/mx_substratevm.py", line 1109, in build
    orig_command_build(args, vm)
  File "/home/ryuta/packages/graal/mx/mx_commands.py", line 147, in __call__
    return self.command_function(*args, **kwargs)
  File "/home/ryuta/packages/graal/mx/mx.py", line 13461, in build
    abort('{0} build tasks failed'.format(len(failed)))
  File "/home/ryuta/packages/graal/mx/mx.py", line 3731, in abort
    if _is_process_alive(p):
  File "/home/ryuta/packages/graal/mx/mx.py", line 3691, in _is_process_alive
    return p.is_alive()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 148, in is_alive
    self._check_closed()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 92, in _check_closed
    raise ValueError("process object is closed")
ValueError: process object is closed
```

**Comment by bobmcwhirter** [comment]
I’ve seen the same. Sometime after 18 September is seems we can no longer build against standard JDK11. Which is a shame.

**Comment by bobvandette** [comment]
We are transitioning substratevm from using an internal Java based implementation of the JDK native libraries to using the real OpenJDK libraries built as static libraries.  The "*.a" files that can not be found are these static libraries.  We are working to make these libraries available and resolve other JDK11 specific issues.   Stay tuned!

**Comment by bobvandette** [comment]
As a temporary work-around, just create these empty files in your JDK's lib directory.

touch libfdlibm.a  libjava.a	libnet.a  libnio.a  libzip.a

This will get you back to the support you previously had which may still have some issues with JDK11 but at least the build should complete.

**Comment by bobmcwhirter** [comment]
Do intend on making the static libs available for all platforms, including aarch64?

**Comment by olpaw** [comment]
> Do you intend on making the static libs available for all platforms, including aarch64?

Have a look in `labsjdk-ce-11.0.5+9-jvmci-19.3-b03-linux-aarch64.tar.gz` from https://github.com/graalvm/labs-openjdk-11/releases/tag/jvmci-19.3-b03 and search for `*.a`.

**Comment by olpaw** [comment]
@bobmcwhirter any more related questions or can we close this one?

**Comment by oroppas** [comment]
So, my understanding is that OpenJDK under Arch Linux will ship with static libraries. Correct?
