### ISSUE TITLE
[GR-18843] Error with H2 database and Micronaut

### ISSUE THREAD

**Issue by ilopmar** [oracle/graal#1743]
As discussed in #1726, after we have removed the flag `--report-unsupported-elements-at-runtime` our test application with Micronaut Data JDBC and H2 doesn't work anymore.

Steps to reproduce the issue:
- `git clone https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal`
- `cd micronaut-data-jdbc-graal`
- Use Graal from master branch (19.3-dev)
- `./build-native-image.sh`

The creation of the native image fails with:
```
[mn-data-jdbc-graal:134]    classlist:  15,599.34 ms
[mn-data-jdbc-graal:134]        (cap):   5,374.95 ms
[mn-data-jdbc-graal:134]        setup:  10,399.24 ms
[mn-data-jdbc-graal:134]   (typeflow): 202,372.99 ms
[mn-data-jdbc-graal:134]    (objects):  79,867.79 ms
[mn-data-jdbc-graal:134]   (features):   7,973.58 ms
[mn-data-jdbc-graal:134]     analysis: 296,614.63 ms
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method sun.util.locale.provider.LocaleServiceProviderPool.getAvailableLocales() is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
	at parsing java.text.Collator.getAvailableLocales(Collator.java:432)
Call path from entry point to java.text.Collator.getAvailableLocales(): 
	at java.text.Collator.getAvailableLocales(Collator.java:430)
	at org.h2.table.MetaTable.generateRows(MetaTable.java:1579)
	at org.h2.index.MetaIndex.find(MetaIndex.java:51)
	at org.h2.store.PageStore.compact(PageStore.java:555)
	at org.h2.engine.Database.closeOpenFilesAndUnlock(Database.java:1572)
	at org.h2.engine.Database.closeImpl(Database.java:1440)
	at org.h2.engine.Database.close(Database.java:1417)
	at org.h2.engine.DelayedDatabaseCloser.run(DelayedDatabaseCloser.java:59)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:478)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
```

Adding the flag `--report-unsupported-elements-at-runtime` makes possible to create the native image again, but this was discouraged in #1726.

**Comment by wirthi** [comment]
The internal ticket GR-18843 has been closed as fixed in 2019 after a PR was merged so I assume this should have been closed long time ago.
