### ISSUE TITLE
[native-image] [Runtime] java.lang.NoSuchMethodException: io.micronaut.http.client.DefaultHttpClient$HttpClientInitializer.channelRegistered(io.netty.channel.ChannelHandlerContext)

### ISSUE THREAD

**Issue by ustari28** [oracle/graal#1758]
Project with micronaut 1.2.2 works fine when execute with java -jar.
Compile with graalvm 19.2.1 CE
`native-image --no-server --initialize-at-run-time=io.micronaut.discovery.aws.parameterstore.AWSParameterStoreConfigClient -cp target/mn-first-rest-*.jar`
And when I execute the application that use eureka-discovery informs the following error:
`13:45:11.415 [main] DEBUG i.m.context.DefaultBeanContext - Resolved existing bean [io.micronaut.http.bind.DefaultRequestBinderRegistry@7fdee4ce7d30] for type [interface io.micronaut.http.bind.RequestBinderRegistry] and qualifier [null]
13:45:11.415 [main] DEBUG io.micronaut.context.lifecycle - Created bean [io.micronaut.http.client.DefaultHttpClient@7fded6e8fd18] from definition [Definition: io.micronaut.http.client.DefaultHttpClient] with qualifier [null]
13:45:11.415 [main] DEBUG i.m.context.DefaultBeanContext - Resolved existing bean [io.micronaut.runtime.ApplicationConfiguration@7fdee4e17298] for type [class io.micronaut.runtime.ApplicationConfiguration] and qualifier [null]
13:45:11.415 [main] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: class io.micronaut.http.codec.CodecConfiguration
13:45:11.416 [main] DEBUG i.m.context.DefaultBeanContext - Resolved bean candidates [Definition: io.micronaut.http.codec.CodecConfiguration] for type: class io.micronaut.http.codec.CodecConfiguration
13:45:11.417 [main] DEBUG i.m.context.DefaultBeanContext - Finalized bean definitions candidates: []
13:45:11.419 [main] DEBUG io.netty.channel.ChannelHandlerMask - Class class io.micronaut.http.client.DefaultHttpClient$HttpClientInitializer missing method channelRegistered, assume we can not skip execution
java.lang.NoSuchMethodException: io.micronaut.http.client.DefaultHttpClient$HttpClientInitializer.channelRegistered(io.netty.channel.ChannelHandlerContext)
        at java.lang.Class.getMethod(DynamicHub.java:1003)
        at io.netty.channel.ChannelHandlerMask$2.run(ChannelHandlerMask.java:172)
        at io.netty.channel.ChannelHandlerMask$2.run(ChannelHandlerMask.java:167)
        at java.security.AccessController.doPrivileged(AccessController.java:89)
        at io.netty.channel.ChannelHandlerMask.isSkippable(ChannelHandlerMask.java:167)
        at io.netty.channel.ChannelHandlerMask.mask0(ChannelHandlerMask.java:95)
        at io.netty.channel.ChannelHandlerMask.mask(ChannelHandlerMask.java:80)
        at io.netty.channel.AbstractChannelHandlerContext.<init>(AbstractChannelHandlerContext.java:104)
        at io.netty.channel.DefaultChannelHandlerContext.<init>(DefaultChannelHandlerContext.java:26)
        at io.netty.channel.DefaultChannelPipeline.newContext(DefaultChannelPipeline.java:120)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:204)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:385)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:372)
        at io.netty.bootstrap.Bootstrap.init(Bootstrap.java:261)
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:310)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:159)
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:143)
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:127)
        at io.micronaut.http.client.DefaultHttpClient.doConnect(DefaultHttpClient.java:1253)
        at io.micronaut.http.client.DefaultHttpClient.doConnect(DefaultHttpClient.java:1208)
        at io.micronaut.http.client.DefaultHttpClient.doConnect(DefaultHttpClient.java:1181)
        at io.micronaut.http.client.DefaultHttpClient.lambda$null$27(DefaultHttpClient.java:1026)`
You can see the source in [github](https://github.com/ustari28/mn-first-rest/tree/feature/discovery)

**Comment by graemerocher** [comment]
This is debug output from Netty and the error can be ignored.

**Comment by ustari28** [comment]
I think It's part of the error. I give the error that I forgot in my last comment
`[36m12:13:10.048[0;39m [1;30m[nioEventLoopGroup-2-3][0;39m [39mDEBUG[0;39m [35mi.m.http.client.DefaultHttpClient[0;39m - Sending HTTP Request: PUT /eureka/apps/mn-first-rest-1/mn-first-rest-1%3A8080
[36m12:13:10.048[0;39m [1;30m[nioEventLoopGroup-2-3][0;39m [39mDEBUG[0;39m [35mi.m.http.client.DefaultHttpClient[0;39m - Chosen Server: eureka-server(8761)
[36m12:13:10.048[0;39m [1;30m[nioEventLoopGroup-2-3][0;39m [39mDEBUG[0;39m [35mio.netty.channel.ChannelHandlerMask[0;39m - Class class io.micronaut.http.client.DefaultHttpClient$10 missing method channelRegistered, assume we can not skip execution
java.lang.NoSuchMethodException: io.micronaut.http.client.DefaultHttpClient$10.channelRegistered(io.netty.channel.ChannelHandlerContext)
	at java.lang.Class.getMethod(DynamicHub.java:1003)
	at io.netty.channel.ChannelHandlerMask$2.run(ChannelHandlerMask.java:172)
	at io.netty.channel.ChannelHandlerMask$2.run(ChannelHandlerMask.java:167)
	at java.security.AccessController.doPrivileged(AccessController.java:89)
	at io.netty.channel.ChannelHandlerMask.isSkippable(ChannelHandlerMask.java:167)
	at io.netty.channel.ChannelHandlerMask.mask0(ChannelHandlerMask.java:95)
	at io.netty.channel.ChannelHandlerMask.mask(ChannelHandlerMask.java:80)
	at io.netty.channel.AbstractChannelHandlerContext.<init>(AbstractChannelHandlerContext.java:104)
	at io.netty.channel.DefaultChannelHandlerContext.<init>(DefaultChannelHandlerContext.java:26)
	at io.netty.channel.DefaultChannelPipeline.newContext(DefaultChannelPipeline.java:120)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:204)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:195)
	at io.micronaut.http.client.DefaultHttpClient.addFullHttpResponseHandler(DefaultHttpClient.java:1944)
	at io.micronaut.http.client.DefaultHttpClient.sendRequestThroughChannel(DefaultHttpClient.java:1591)
	at io.micronaut.http.client.DefaultHttpClient.lambda$null$26(DefaultHttpClient.java:1031)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:493)`

**Comment by graemerocher** [comment]
Again that is debug output. What problem are you facing? Whatever it is unrelated to the given trace

**Comment by ustari28** [comment]
The problem is when I compile the micronaut application with native-image the service of registering to eureka server doesn't work

**Comment by graemerocher** [comment]
That appears to be a different issue. Could you report the issues and attach an example that reproduces the issue. https://github.com/micronaut-projects/micronaut-core/issues
