### ISSUE TITLE
JDBC application with Teradata JDBC driver: native-image build fails with com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: unstructured control flow  ( [, 539]  [, 1359, 539, 539, 539])

### ISSUE THREAD

**Issue by gg-npn** [oracle/graal#1764]
The issue might be related to https://github.com/oracle/graal/issues/1699
Build fails with the following error:
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: unstructured control flow  ( [, 539]  [, 1359, 539, 539, 539])
Detailed message:
Call path from entry point to com.teradata.jdbc.jdbc_4.io.TDNetworkIOIF.read(BufferContainer, int, TDStatement, boolean): 
	at com.teradata.jdbc.jdbc_4.io.TDNetworkIOIF.read(TDNetworkIOIF.java:719)
	at com.teradata.jdbc.jdbc_4.io.TDPacketStream.readStream(TDPacketStream.java:800)
	at com.teradata.jdbc.jdbc_4.statemachine.StatementReceiveState.action(StatementReceiveState.java:141)
	at com.teradata.jdbc.jdbc_4.statemachine.StatementController.runBody(StatementController.java:137)
	at com.teradata.jdbc.jdbc_4.ifsupport.Results.moreResults(Results.java:184)
	at com.teradata.jdbc.jdbc_4.TDStatement.doNonPrepExecute(TDStatement.java:297)
	at com.teradata.jdbc.jdbc_4.TDStatement.execute(TDStatement.java:1136)

Full log, code and build script attached
[jdbc-test.zip](https://github.com/oracle/graal/files/3752403/jdbc-test.zip)

**Comment by ggorshtein** [comment]
Forgot to mention: using graalvm-ee-19.2.1

**Comment by thomaswue** [comment]
What version of javac was the JAR file generated from? Use of JSR bytecode is largely deprecated by now.

**Comment by gg-npn** [comment]
The class that fails: com.teradata.jdbc.jdbc_4.io.TDNetworkIOIF was generated by JDK 1.2(byte offset 7 is 0x2E)
