### ISSUE TITLE
native-image: DatagramDispatcher not implemented

### ISSUE THREAD

**Issue by mziccard** [oracle/graal#1787]
Attempting to read/write on a DatagramChannel from an application built with native-image results in:
```
com.oracle.svm.core.jdk.UnsupportedFeatureError: Unimplemented: sun.nio.ch.DatagramChannelImpl.receive0(FileDescriptor, long, int)
    at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:102)
    at sun.nio.ch.DatagramDispatcher.write0(DatagramDispatcher.java:108)
    at sun.nio.ch.DatagramDispatcher.write(DatagramDispatcher.java:51)
    at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
    at sun.nio.ch.IOUtil.write(IOUtil.java:65)
```

This is caused by DatagramDispatcher substitutions throwing an exception (don't be misled by the wrong error message).

**Comment by christianwimmer** [comment]
Fixed in https://github.com/oracle/graal/commit/fb3caa5ace0b247e2fe8c1a4ef4ef425f4eabaa8
