### ISSUE TITLE
During native image build ZipException: invalid stored block lengths

### ISSUE THREAD

**Issue by tjwatson** [oracle/graal#1792]
Reproduced on Mac with `OpenJDK 64-Bit GraalVM CE 19.2.1 (build 25.232-b07-jvmci-19.2-b03, mixed mode)`

This happens if a JAR containing META-INF/services file changes on disk and you have a native image build server running that previously used the JAR file.  The native image server must be stopped and restarted to get past it.

```
Build on Server(pid: 3427, port: 54188)
[atomos:3427]    classlist:   1,203.53 ms
[atomos:3427]        (cap):   3,401.75 ms
[atomos:3427]        setup:   3,818.98 ms
[atomos:3427]     analysis:   4,047.31 ms
Error: Error loading service implementations for service `org.osgi.framework.connect.FrameworkUtilHelper` from URL `jar:file:/Users/tjwatson/.m2/repository/org/atomos/atomos.framework/0.0.1-SNAPSHOT/atomos.framework-0.0.1-SNAPSHOT.jar!/META-INF/services/org.osgi.framework.connect.FrameworkUtilHelper`
com.oracle.svm.core.util.UserError$UserException: Error loading service implementations for service `org.osgi.framework.connect.FrameworkUtilHelper` from URL `jar:file:/Users/tjwatson/.m2/repository/org/atomos/atomos.framework/0.0.1-SNAPSHOT/atomos.framework-0.0.1-SNAPSHOT.jar!/META-INF/services/org.osgi.framework.connect.FrameworkUtilHelper`
	at com.oracle.svm.core.util.UserError.abort(UserError.java:75)
	at com.oracle.svm.hosted.ServiceLoaderFeature.handleType(ServiceLoaderFeature.java:165)
	at com.oracle.svm.hosted.ServiceLoaderFeature.duringAnalysis(ServiceLoaderFeature.java:112)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:711)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:711)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:526)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.util.zip.ZipException: invalid stored block lengths
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at com.oracle.svm.hosted.ServiceLoaderFeature.parseServiceResource(ServiceLoaderFeature.java:248)
	at com.oracle.svm.hosted.ServiceLoaderFeature.handleType(ServiceLoaderFeature.java:163)
	... 11 more
Error: Image build request failed with exit status 1
```

**Comment by christianwimmer** [comment]
The image build server is disabled by default now, so I'm closing this issue.
