### ISSUE TITLE
[native-image] No parsing context available

### ISSUE THREAD

**Issue by ldeclevanano** [oracle/graal#1810]
Hi!

When trying to build a native image with 

`    native-image -jar project.jar \
        -H:Name=project-exec \
        --allow-incomplete-classpath \
       --initialize-at-build-time=org.jooq \
        --initialize-at-build-time=org.postgresql.Driver \
        --initialize-at-build-time=org.postgresql.util.SharedTimer \
        --initialize-at-build-time=org.slf4j \
        -H:-UseServiceLoaderFeature \
        -H:+TraceClassInitialization --auto-fallback \
        -H:+ReportExceptionStackTraces`

I get this error
```
Error: Error encountered while parsing io.grpc.netty.shaded.io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator.<clinit>() 
Parsing context: <no parsing context available> 

com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing io.grpc.netty.shaded.io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator.<clinit>() 
Parsing context: <no parsing context available> 

        at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:323)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
        at com.oracle.graal.pointsto.BigBang$1.run(BigBang.java:384)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.IllegalAccessError: class sun.security.ssl.ALPNExtension cannot access its superclass sun.security.ssl.HelloExtension
        at parsing io.grpc.netty.shaded.io.netty.handler.ssl.JettyAlpnSslEngine.initAvailable(JettyAlpnSslEngine.java:44)
        at parsing io.grpc.netty.shaded.io.netty.handler.ssl.JettyAlpnSslEngine.<clinit>(JettyAlpnSslEngine.java:34)
        at org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2470)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:92)
        at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3272)
        at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3074)
        at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:976)
        at org.graalvm.compiler.java.BytecodeParser.parseAndInlineCallee(BytecodeParser.java:2491)
        at org.graalvm.compiler.java.BytecodeParser.inline(BytecodeParser.java:2391)
        at org.graalvm.compiler.java.BytecodeParser.tryInline(BytecodeParser.java:2137)
        at org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1809)
        at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1566)
        at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1546)
        at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5125)
        at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3267)
        at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3074)
        at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:976)
        at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:870)
        at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
        at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
        at com.oracle.svm.hosted.substitute.UnsafeAutomaticSubstitutionProcessor.getStaticInitializerGraph(UnsafeAutomaticSubstitutionProcessor.java:905)
        at com.oracle.svm.hosted.substitute.UnsafeAutomaticSubstitutionProcessor.computeSubstitutions(UnsafeAutomaticSubstitutionProcessor.java:321)
        at com.oracle.svm.hosted.SVMHost.registerType(SVMHost.java:199)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:262)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:203)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:180)
        at com.oracle.graal.pointsto.meta.AnalysisMethod.getDeclaringClass(AnalysisMethod.java:342)
        at com.oracle.graal.pointsto.meta.AnalysisMethod.getSignature(AnalysisMethod.java:311)
        at com.oracle.graal.pointsto.flow.MethodFlowsGraph.<init>(MethodFlowsGraph.java:98)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.<init>(MethodTypeFlow.java:75)
        at com.oracle.graal.pointsto.meta.AnalysisMethod.<init>(AnalysisMethod.java:132)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.createMethod(AnalysisUniverse.java:410)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:398)
        at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupMethod(WrappedConstantPool.java:116)
        at org.graalvm.compiler.java.BytecodeParser.lookupMethod(BytecodeParser.java:4123)
        at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1543)
        at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5125)
        at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3267)
        at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3074)
        at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:976)
        at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:870)
        at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
        at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:221)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:340)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
        ... 9 more
Caused by: java.lang.IllegalAccessError: class sun.security.ssl.ALPNExtension cannot access its superclass sun.security.ssl.HelloExtension
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at com.oracle.svm.hosted.ImageClassLoader.forName(ImageClassLoader.java:404)
        at com.oracle.svm.hosted.ImageClassLoader.findClassByName(ImageClassLoader.java:394)
        at com.oracle.svm.hosted.snippets.ReflectionPlugins.processForName(ReflectionPlugins.java:210)
        at com.oracle.svm.hosted.snippets.ReflectionPlugins.access$100(ReflectionPlugins.java:65)
        at com.oracle.svm.hosted.snippets.ReflectionPlugins$2.apply(ReflectionPlugins.java:159)
        at org.graalvm.compiler.nodes.graphbuilderconf.InvocationPlugin.execute(InvocationPlugin.java:217)
        at org.graalvm.compiler.java.BytecodeParser.tryInvocationPlugin(BytecodeParser.java:2092)
        at org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1801)
        at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1566)
        at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1546)
        at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5125)
        at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3267)
        ... 55 more
```

I'm using graalvm 19.2.0.1
Should I add a reflect-config.json file with some grpc definitions? 
Any help is welcome

**Comment by cstancu** [comment]
@ldeclevanano that looks like some incompatible class change in one of the dependencies. Please reopen if you can still replicate with the latest GraalVM and provide reproducible code. Thank you!
