### ISSUE TITLE
[native-image] ConcurrentModificationException in org.graalvm.launcher.Launcher

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#1811]
For some reason, an `ConcurrentModificationException` is thrown in `org.graalvm.launcher.Launcher` when I provide `--vm*` arguments:

```
bin/graalsqueak-svm --vm.XX:+PrintGC images/trunk64-wip.image
org.graalvm.launcher.Launcher$AbortException
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$SubList.checkForComodification(ArrayList.java:1239)
	at java.util.ArrayList$SubList.listIterator(ArrayList.java:1099)
	at java.util.AbstractList.listIterator(AbstractList.java:299)
	at java.util.ArrayList$SubList.iterator(ArrayList.java:1095)
	at org.graalvm.launcher.Launcher.parsePolyglotOptions(Launcher.java:686)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:102)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:70)
	at de.hpi.swa.graal.squeak.launcher.GraalSqueakLauncher.main(GraalSqueakLauncher.java:55)
[1]    39832 exit 255   bin/graalsqueak-svm --vm.XX:+PrintGC
```

`polyglot --vm.XX:+PrintGC --shell`, on the other hand, seems to work fine.
I'm not aware of any concurrent list access in our code.

*Tested with GraalVM CE 19.2.1 on macOS Catalina.*

**Comment by tzezula** [comment]
The problem is in https://github.com/hpi-swa/graalsqueak/blob/master/src/de.hpi.swa.graal.squeak.launcher/src/de/hpi/swa/graal/squeak/launcher/GraalSqueakLauncher.java#L64 which returns the `unrecognizedArgs` as an `args` sublist.
The `SubList.iterator()` throws an `ConcurrentModificationException` when a change happened in underlaying `List`.

**Comment by fniephaus** [comment]
Wow, good catch! Thanks @tzezula! So the bug is indeed in our code...closing this issue.
