### ISSUE TITLE
Sulong loads and searches all native libraries for a symbol it should already know the location of

### ISSUE THREAD

**Issue by chrisseaton** [oracle/graal#1815]
```
    public AllocateReadOnlyGlobalsBlockNode(LLVMContext context, StructureType type, DataLayout dataLayout) {
        this.size = type.getSize(dataLayout);
        this.toNative = LLVMToNativeNode.createToNativeWithTarget();

        NFIContextExtension nfiContextExtension = context.getLanguage().getContextExtensionOrNull(NFIContextExtension.class);
        this.allocateGlobalsBlock = nfiContextExtension.getNativeFunction(context, "__sulong_allocate_globals_block", "(UINT64):POINTER");
        this.interop = InteropLibrary.getFactory().create(allocateGlobalsBlock);
    }
```

This symbol `__sulong_allocate_globals_block` is only going to be coming from one place - `libsulong`, but Sulong uses `getNativeFunction`, then `getNativeFunctionOrNull`, which loops through all possible native libraries, loading them all in `loadLibrary`.

```
	at com.oracle.truffle.llvm.runtime.NFIContextExtension.loadLibrary(NFIContextExtension.java:224)
	at com.oracle.truffle.llvm.runtime.NFIContextExtension.loadLibrary(NFIContextExtension.java:202)
	at com.oracle.truffle.llvm.runtime.NFIContextExtension.addLibrary(NFIContextExtension.java:152)
	at com.oracle.truffle.llvm.runtime.NFIContextExtension.addLibraries(NFIContextExtension.java:144)
	at com.oracle.truffle.llvm.runtime.NFIContextExtension.getNativeFunctionOrNull(NFIContextExtension.java:300)
	at com.oracle.truffle.llvm.runtime.NFIContextExtension.getNativeFunction(NFIContextExtension.java:366)
	at com.oracle.truffle.llvm.runtime.nodes.memory.AllocateReadOnlyGlobalsBlockNode.<init>(AllocateReadOnlyGlobalsBlockNode.java:58)
```

**Comment by chrisseaton** [comment]
Could be assigned to @rschatz.

**Comment by fernando-valdez** [comment]
@rschatz do you think this issue still applies?
