### ISSUE TITLE
Invoking suspendable Kotlin functions from guest language

### ISSUE THREAD

**Issue by maurocchi** [oracle/graal#1821]
Hi guys,
a newbie question: is there a way to invoke suspendable Kotlin functions from exported methods without to expose to the guest language details about the coroutine machinery?

Example:
```kotlin
package org.example

import kotlinx.coroutines.*
import org.graalvm.polyglot.*

class HttpClient {
    @HostAccess.Export
    suspend fun get(path: String): Any {
        delay(1000L)
        return "result of $path"
    }
}

suspend fun main() {
    val job = GlobalScope.launch {
        Context.create().use { context ->
            context.getBindings("js").putMember("http", HttpClient())
            context.eval("js", "console.log(http.get('/hello'))")
        }
    }
    job.join()
}
```

The invocation fails probably due to the lack of the coroutine context:
```
Exception in thread "DefaultDispatcher-worker-1" TypeError: invokeMember (get) on
JavaObject[org.example.HttpClient@4166fbbc (org.example.HttpClient)] failed due to:
Arity error - expected: 2 actual: 1
```

**Comment by shelajev** [comment]
You are correct. If you look at the bytecode for this snippet, the `get` method actually has 2 arguments: `String, kotlin.coroutines.Continuation<java.lang.Object>`: 

```
❯ javap HttpClient
Warning: File ./HttpClient.class does not contain class HttpClient
Compiled from "Main.kt"
public final class org.example.HttpClient {
  public final java.lang.Object get(java.lang.String, kotlin.coroutines.Continuation<java.lang.Object>);
  public org.example.HttpClient();
}
``` 

You can get further with it by executing: 
```
            context.eval("js", "console.log(http.get('/hello', null))")
```

Which would result in an expected:
```
Exception in thread "DefaultDispatcher-worker-1" org.graalvm.polyglot.PolyglotException
	at kotlin.coroutines.jvm.internal.ContinuationImpl.getContext(ContinuationImpl.kt:105)
	at kotlin.coroutines.jvm.internal.ContinuationImpl.intercepted(ContinuationImpl.kt:112)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt.intercepted(IntrinsicsJvm.kt:137)
	at kotlinx.coroutines.DelayKt.delay(Delay.kt:82)
	at org.example.HttpClient.get(Main.kt:9)
	at <js> :program(Unnamed:1:12-35)
	at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:370)
	at org.example.MainKt$main$job$1.invokeSuspend(Main.kt:18)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
Caused by host exception: kotlin.KotlinNullPointerException

Process finished with exit code 0
``` 

And of course you can add some sort of a coroutine to the bindings (or expose some sort of a coroutine creating mechanics). For example this passes and exits without errors (but doesn't do what you want I think. 

```
package org.example

import kotlinx.coroutines.*
import org.graalvm.polyglot.*

class HttpClient {
    @HostAccess.Export
    suspend fun get(path: String): Any {
        delay(1000L)
        return "result of $path"
    }
}

suspend fun main() {
    val job = GlobalScope.launch {
        Context.create().use { context ->
            context.getBindings("js").putMember("http", HttpClient())
            context.getBindings("js").putMember("cont", kotlin.coroutines.Continuation<java.lang.Object>(this.coroutineContext, {}))
            context.eval("js", "console.log(http.get('/hello', cont))")
        }
    }
    job.join()
}
```
