### ISSUE TITLE
[native-image] Very simple JNI test code fails with java.lang.UnsatisfiedLinkError when executed

### ISSUE THREAD

**Issue by retrogradeorbit** [oracle/graal#1828]
I have created the simplest possible JNI example project here:

https://github.com/retrogradeorbit/graal-native-image-jni

I have followed the documentation on JNI support to the best of my ability. I have setup the jni-config.json file as best as I can fathom. Running the resultant jar with `java -jar` works. But compiling with native-image and then running the resultant binary fails with:

```
$ make run-native 
javac src/HelloWorld.java
cd src && jar cfm ../HelloWorld.jar manifest.txt HelloWorld.class
cd src && javah -jni HelloWorld
gcc -shared -Wall -Werror -I/usr/lib/jvm/java-8-oracle/include -I/usr/lib/jvm/java-8-oracle/include/linux -o libHelloWorld.so -fPIC src/HelloWorld.c
/home/crispin/graalvm-ce-19.2.1/bin/native-image \
	-jar HelloWorld.jar \
	-H:Name=helloworld \
	-H:+ReportExceptionStackTraces \
	-H:ConfigurationFileDirectories=config-dir \
	--initialize-at-build-time \
	--verbose \
	--no-fallback \
	--no-server \
	--static \
	"-J-Xmx1g" \
	-H:+TraceClassInitialization -H:+PrintClassInitialization
Executing [
/home/crispin/graalvm-ce-19.2.1/jre/bin/java \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-d64 \
-XX:-UseJVMCIClassLoader \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx14g \
-Duser.country=US \
-Duser.language=en \
-Dorg.graalvm.version=19.2.1 \
-Dorg.graalvm.config=CE \
-Dcom.oracle.graalvm.isaot=true \
-Djvmci.class.path.append=/home/crispin/graalvm-ce-19.2.1/jre/lib/jvmci/graal.jar \
-javaagent:/home/crispin/graalvm-ce-19.2.1/jre/lib/svm/builder/svm.jar \
-Xmx1g \
-Xbootclasspath/a:/home/crispin/graalvm-ce-19.2.1/jre/lib/boot/graaljs-scriptengine.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/boot/graal-sdk.jar \
-cp \
/home/crispin/graalvm-ce-19.2.1/jre/lib/svm/builder/svm.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/svm/builder/javacpp.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/svm/builder/svm-llvm.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/svm/builder/graal-llvm.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/svm/builder/llvm-platform-specific.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/svm/builder/llvm-wrapper.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/svm/builder/objectfile.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/svm/builder/pointsto.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/jvmci/jvmci-hotspot.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/jvmci/graal-management.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/jvmci/jvmci-api.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/jvmci/graal.jar \
com.oracle.svm.hosted.NativeImageGeneratorRunner \
-watchpid \
14878 \
-imagecp \
/home/crispin/graalvm-ce-19.2.1/jre/lib/boot/graaljs-scriptengine.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/boot/graal-sdk.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/svm/builder/svm.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/svm/builder/javacpp.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/svm/builder/svm-llvm.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/svm/builder/graal-llvm.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/svm/builder/llvm-platform-specific.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/svm/builder/llvm-wrapper.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/svm/builder/objectfile.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/svm/builder/pointsto.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/jvmci/jvmci-hotspot.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/jvmci/graal-management.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/jvmci/jvmci-api.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/jvmci/graal.jar:/home/crispin/graalvm-ce-19.2.1/jre/lib/svm/library-support.jar:/home/crispin/dev/epiccastle/graal-native-image-jni/HelloWorld.jar \
-H:Path=/home/crispin/dev/epiccastle/graal-native-image-jni \
-H:Class=HelloWorld \
-H:+ReportExceptionStackTraces \
-H:ConfigurationFileDirectories=config-dir \
-H:ClassInitialization=:build_time \
-H:FallbackThreshold=0 \
-H:+StaticExecutable \
-H:+TraceClassInitialization \
-H:+PrintClassInitialization \
-H:CLibraryPath=/home/crispin/graalvm-ce-19.2.1/jre/lib/svm/clibraries/linux-amd64 \
-H:Name=helloworld
]
[helloworld:14900]    classlist:   2,120.39 ms
[helloworld:14900]        (cap):   2,076.86 ms
[helloworld:14900]        setup:   3,709.06 ms
[helloworld:14900]   (typeflow):   3,177.48 ms
[helloworld:14900]    (objects):   2,370.85 ms
[helloworld:14900]   (features):     384.07 ms
[helloworld:14900]     analysis:   6,058.98 ms
Printing initializer configuration to /home/crispin/dev/epiccastle/graal-native-image-jni/reports/initializer_configuration_20191114_001931.txt
Printing initializer dependencies to /home/crispin/dev/epiccastle/graal-native-image-jni/reports/initializer_dependencies_20191114_001931.dot
Printing 0 classes that are considered as safe for build-time initialization to /home/crispin/dev/epiccastle/graal-native-image-jni/reports/safe_classes_20191114_001931.txt
Printing 1710 classes of type BUILD_TIME to /home/crispin/dev/epiccastle/graal-native-image-jni/reports/build_time_classes_20191114_001931.txt
Printing 13 classes of type RERUN to /home/crispin/dev/epiccastle/graal-native-image-jni/reports/rerun_classes_20191114_001931.txt
Printing 0 classes of type RUN_TIME to /home/crispin/dev/epiccastle/graal-native-image-jni/reports/run_time_classes_20191114_001931.txt
[helloworld:14900]     (clinit):     211.51 ms
[helloworld:14900]     universe:     551.77 ms
[helloworld:14900]      (parse):     633.83 ms
[helloworld:14900]     (inline):   1,160.06 ms
[helloworld:14900]    (compile):   5,877.57 ms
[helloworld:14900]      compile:   8,064.44 ms
[helloworld:14900]        image:     593.28 ms
[helloworld:14900]        write:     154.77 ms
[helloworld:14900]      [total]:  21,467.13 ms
LD_LIBRARY_PATH=./ ./helloworld
Exception in thread "main" java.lang.UnsatisfiedLinkError: HelloWorld.print()V [symbol: Java_HelloWorld_print or Java_HelloWorld_print__]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
	at HelloWorld.print(HelloWorld.java)
	at HelloWorld.main(HelloWorld.java:10)
Makefile:40: recipe for target 'run-native' failed
make: *** [run-native] Error 1
```

Could you please help me with what I am missing? If I can get this simple example working it will serve as a good reference for others trying to get JNI working with native-image.

**Comment by peter-hofer** [comment]
The trouble is that `System.loadLibrary` is called from the static initializer of `Main`, but you pass `--initialize-at-build-time` as flag, so the initializer will already be executed during the image build and the library will not be loaded at runtime. You can also tell from the files generated by `+PrintClassInitialization` (the output `Printing 0 classes of type RUN_TIME` also indicates this). Moreover, I would advise against using `--static` because it needs static versions of various libraries on your system and increases image sizes.

**Comment by retrogradeorbit** [comment]
@peter-hofer thankyou very much for your insight. That is clear now you say this but I found the documentation quite confusing. I have updated my repository to clearly explain this. I will issue a PR and improve the graalvm documentation to make this more explicit. I'll flag you as a reviewer of the PR so you can check.
