### ISSUE TITLE
[native-image] [windows] 19.3.0 - trivial .jar can't be made into an exe

### ISSUE THREAD

**Issue by Skhmt** [oracle/graal#1850]
Code is literally just a class with `System.out.println("hello world");` and it runs correctly as a .jar with the system's JDK.

```
C:\Users\user1\Desktop\GraalVM test>C:\graalvm-ce-java11-19.3.0\bin\native-image -jar JavaHelloWorld.jar --no-fallback --verbose
Executing [
C:\graalvm-ce-java11-19.3.0\bin\java.exe \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
-Djava.lang.invoke.stringConcat=BC_SB \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.runtime=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.code=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.aarch64=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.amd64=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.hotspot=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.services=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.common=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.code.site=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.code.stack=ALL-UNNAMED \
--add-opens \
jdk.internal.vm.compiler/org.graalvm.compiler.debug=ALL-UNNAMED \
--add-opens \
jdk.internal.vm.compiler/org.graalvm.compiler.nodes=ALL-UNNAMED \
--add-opens \
jdk.unsupported/sun.reflect=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.module=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.ref=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.reflect=ALL-UNNAMED \
--add-opens \
java.base/java.io=ALL-UNNAMED \
--add-opens \
java.base/java.lang=ALL-UNNAMED \
--add-opens \
java.base/java.lang.reflect=ALL-UNNAMED \
--add-opens \
java.base/java.lang.invoke=ALL-UNNAMED \
--add-opens \
java.base/java.lang.ref=ALL-UNNAMED \
--add-opens \
java.base/java.net=ALL-UNNAMED \
--add-opens \
java.base/java.nio=ALL-UNNAMED \
--add-opens \
java.base/java.nio.file=ALL-UNNAMED \
--add-opens \
java.base/java.security=ALL-UNNAMED \
--add-opens \
java.base/javax.crypto=ALL-UNNAMED \
--add-opens \
java.base/java.util=ALL-UNNAMED \
--add-opens \
java.base/java.util.concurrent.atomic=ALL-UNNAMED \
--add-opens \
java.base/sun.security.x509=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.logger=ALL-UNNAMED \
--add-opens \
org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED \
--add-opens \
org.graalvm.sdk/org.graalvm.polyglot=ALL-UNNAMED \
--add-opens \
org.graalvm.truffle/com.oracle.truffle.polyglot=ALL-UNNAMED \
--add-opens \
org.graalvm.truffle/com.oracle.truffle.api.impl=ALL-UNNAMED \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx14g \
-Duser.country=US \
-Duser.language=en \
-Dorg.graalvm.version=dev \
-Dorg.graalvm.config= \
-Dcom.oracle.graalvm.isaot=true \
--module-path \
C:\graalvm-ce-java11-19.3.0\lib\truffle\truffle-api.jar \
-javaagent:C:\graalvm-ce-java11-19.3.0\lib\svm\builder\svm.jar \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-cp \
C:\graalvm-ce-java11-19.3.0\lib\svm\builder\objectfile.jar;C:\graalvm-ce-java11-19.3.0\lib\svm\builder\pointsto.jar;C:\graalvm-ce-java11-19.3.0\lib\svm\builder\svm.jar \
com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus \
-imagecp \
C:\graalvm-ce-java11-19.3.0\lib\svm\builder\objectfile.jar;C:\graalvm-ce-java11-19.3.0\lib\svm\builder\pointsto.jar;C:\graalvm-ce-java11-19.3.0\lib\svm\builder\svm.jar;C:\graalvm-ce-java11-19.3.0\lib\svm\library-support.jar;C:\Users\user1\Desktop\GraalVM test\JavaHelloWorld.jar \
-H:Path=C:\Users\user1\Desktop\GraalVM test \
-H:Class=HelloWorld \
-H:Name=JavaHelloWorld \
-H:FallbackThreshold=0 \
-H:CLibraryPath=C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64
]
[JavaHelloWorld:13184]    classlist:     851.86 ms
[JavaHelloWorld:13184]        (cap):     845.01 ms
[JavaHelloWorld:13184]        setup:   1,620.79 ms
[JavaHelloWorld:13184]   (typeflow):   3,635.23 ms
[JavaHelloWorld:13184]    (objects):   3,391.36 ms
[JavaHelloWorld:13184]   (features):     123.24 ms
[JavaHelloWorld:13184]     analysis:   7,268.08 ms
[JavaHelloWorld:13184]     (clinit):     111.25 ms
[JavaHelloWorld:13184]     universe:     317.46 ms
[JavaHelloWorld:13184]      (parse):     422.25 ms
[JavaHelloWorld:13184]     (inline):     993.86 ms
[JavaHelloWorld:13184]    (compile):   3,510.14 ms
[JavaHelloWorld:13184]      compile:   5,242.46 ms
[JavaHelloWorld:13184]        image:     559.39 ms
[JavaHelloWorld:13184]        write:     330.19 ms
Fatal error: java.lang.RuntimeException: java.lang.RuntimeException: host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 2

Running command: CL /MD /Zi /PDBSTRIPPED /FeC:\Users\user1\Desktop\GraalVM test\JavaHelloWorld.exe C:\Users\user1\AppData\Local\Temp\SVM-7248843675299935506\JavaHelloWorld.obj C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\ffi.lib C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\strictmath.lib C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\jvm.lib C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\libchelper.lib C:\graalvm-ce-java11-19.3.0\lib\net.lib C:\graalvm-ce-java11-19.3.0\lib\java.lib C:\graalvm-ce-java11-19.3.0\lib\zip.lib C:\graalvm-ce-java11-19.3.0\lib\nio.lib C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\ffi.lib C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\strictmath.lib C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\jvm.lib C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\libchelper.lib C:\graalvm-ce-java11-19.3.0\lib\net.lib C:\graalvm-ce-java11-19.3.0\lib\java.lib C:\graalvm-ce-java11-19.3.0\lib\zip.lib C:\graalvm-ce-java11-19.3.0\lib\nio.lib /link /INCREMENTAL:NO /NODEFAULTLIB:LIBCMT /NODEFAULTLIB:OLDNAMES /LIBPATH:C:\graalvm-ce-java11-19.3.0\lib /LIBPATH:C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64 advapi32.lib ws2_32.lib secur32.lib iphlpapi.lib

Microsoft (R) C/C++ Optimizing Compiler Version 16.00.30319.01 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '/PDBSTRIPPED'
Microsoft (R) Incremental Linker Version 10.00.30319.01
Copyright (C) Microsoft Corporation.  All rights reserved.

/debug
"/out:C:\Users\user1\Desktop\GraalVM test\JavaHelloWorld.exe"
/INCREMENTAL:NO /NODEFAULTLIB:LIBCMT /NODEFAULTLIB:OLDNAMES
/LIBPATH:C:\graalvm-ce-java11-19.3.0\lib
/LIBPATH:C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64
advapi32.lib
ws2_32.lib
secur32.lib
iphlpapi.lib
C:\Users\user1\AppData\Local\Temp\SVM-7248843675299935506\JavaHelloWorld.obj
C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\ffi.lib
C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\strictmath.lib
C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\jvm.lib
C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\libchelper.lib
C:\graalvm-ce-java11-19.3.0\lib\net.lib
C:\graalvm-ce-java11-19.3.0\lib\java.lib
C:\graalvm-ce-java11-19.3.0\lib\zip.lib
C:\graalvm-ce-java11-19.3.0\lib\nio.lib
C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\ffi.lib
C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\strictmath.lib
C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\jvm.lib
C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\libchelper.lib
C:\graalvm-ce-java11-19.3.0\lib\net.lib
C:\graalvm-ce-java11-19.3.0\lib\java.lib
C:\graalvm-ce-java11-19.3.0\lib\zip.lib
C:\graalvm-ce-java11-19.3.0\lib\nio.lib
   Creating library C:\Users\user1\Desktop\GraalVM test\JavaHelloWorld.lib and object C:\Users\user1\Desktop\GraalVM test\JavaHelloWorld.exp
jvm.lib(JvmFuncs.obj) : error LNK2019: unresolved external symbol __imp___acrt_iob_func referenced in function JVM_AddModuleExports
java.lib(jni_util.obj) : error LNK2001: unresolved external symbol __imp___acrt_iob_func
jvm.lib(JvmFuncs.obj) : error LNK2019: unresolved external symbol __imp___stdio_common_vfprintf referenced in function _vfprintf_l
java.lib(jni_util.obj) : error LNK2001: unresolved external symbol __imp___stdio_common_vfprintf
jvm.lib(JvmFuncs.obj) : error LNK2019: unresolved external symbol __imp___stdio_common_vsprintf referenced in function jio_snprintf
C:\Users\user1\Desktop\GraalVM test\JavaHelloWorld.exe : fatal error LNK1120: 3 unresolved externals

        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
        at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:462)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:315)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:454)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:115)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:479)
Caused by: java.lang.RuntimeException: host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 2

Running command: CL /MD /Zi /PDBSTRIPPED /FeC:\Users\user1\Desktop\GraalVM test\JavaHelloWorld.exe C:\Users\user1\AppData\Local\Temp\SVM-7248843675299935506\JavaHelloWorld.obj C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\ffi.lib C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\strictmath.lib C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\jvm.lib C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\libchelper.lib C:\graalvm-ce-java11-19.3.0\lib\net.lib C:\graalvm-ce-java11-19.3.0\lib\java.lib C:\graalvm-ce-java11-19.3.0\lib\zip.lib C:\graalvm-ce-java11-19.3.0\lib\nio.lib C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\ffi.lib C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\strictmath.lib C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\jvm.lib C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\libchelper.lib C:\graalvm-ce-java11-19.3.0\lib\net.lib C:\graalvm-ce-java11-19.3.0\lib\java.lib C:\graalvm-ce-java11-19.3.0\lib\zip.lib C:\graalvm-ce-java11-19.3.0\lib\nio.lib /link /INCREMENTAL:NO /NODEFAULTLIB:LIBCMT /NODEFAULTLIB:OLDNAMES /LIBPATH:C:\graalvm-ce-java11-19.3.0\lib /LIBPATH:C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64 advapi32.lib ws2_32.lib secur32.lib iphlpapi.lib

Microsoft (R) C/C++ Optimizing Compiler Version 16.00.30319.01 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '/PDBSTRIPPED'
Microsoft (R) Incremental Linker Version 10.00.30319.01
Copyright (C) Microsoft Corporation.  All rights reserved.

/debug
"/out:C:\Users\user1\Desktop\GraalVM test\JavaHelloWorld.exe"
/INCREMENTAL:NO /NODEFAULTLIB:LIBCMT /NODEFAULTLIB:OLDNAMES
/LIBPATH:C:\graalvm-ce-java11-19.3.0\lib
/LIBPATH:C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64
advapi32.lib
ws2_32.lib
secur32.lib
iphlpapi.lib
C:\Users\user1\AppData\Local\Temp\SVM-7248843675299935506\JavaHelloWorld.obj
C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\ffi.lib
C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\strictmath.lib
C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\jvm.lib
C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\libchelper.lib
C:\graalvm-ce-java11-19.3.0\lib\net.lib
C:\graalvm-ce-java11-19.3.0\lib\java.lib
C:\graalvm-ce-java11-19.3.0\lib\zip.lib
C:\graalvm-ce-java11-19.3.0\lib\nio.lib
C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\ffi.lib
C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\strictmath.lib
C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\jvm.lib
C:\graalvm-ce-java11-19.3.0\lib\svm\clibraries\windows-amd64\libchelper.lib
C:\graalvm-ce-java11-19.3.0\lib\net.lib
C:\graalvm-ce-java11-19.3.0\lib\java.lib
C:\graalvm-ce-java11-19.3.0\lib\zip.lib
C:\graalvm-ce-java11-19.3.0\lib\nio.lib
   Creating library C:\Users\user1\Desktop\GraalVM test\JavaHelloWorld.lib and object C:\Users\user1\Desktop\GraalVM test\JavaHelloWorld.exp
jvm.lib(JvmFuncs.obj) : error LNK2019: unresolved external symbol __imp___acrt_iob_func referenced in function JVM_AddModuleExports
java.lib(jni_util.obj) : error LNK2001: unresolved external symbol __imp___acrt_iob_func
jvm.lib(JvmFuncs.obj) : error LNK2019: unresolved external symbol __imp___stdio_common_vfprintf referenced in function _vfprintf_l
java.lib(jni_util.obj) : error LNK2001: unresolved external symbol __imp___stdio_common_vfprintf
jvm.lib(JvmFuncs.obj) : error LNK2019: unresolved external symbol __imp___stdio_common_vsprintf referenced in function jio_snprintf
C:\Users\user1\Desktop\GraalVM test\JavaHelloWorld.exe : fatal error LNK1120: 3 unresolved externals

        at com.oracle.svm.hosted.image.NativeBootImageViaCC.write(NativeBootImageViaCC.java:382)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:652)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1482)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1260)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1222)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1181)
        at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1665)
```

I'm running from the Windows 7 x64 Debug Build Environment console as with previous versions of GraalVM for Windows.

**Comment by bobvandette** [comment]
This looks like a Visual Studio tools version mismatch.  I'm not sure which version of Visual Studio was used to build GraalVM but it looks like you may be using an old version of Visual Studio to link your JavaHelloWorld.exe file.  The interface to the Visual Studio C Runtime library changed in VS2015.  What version of Visual Studio do you have?

**Comment by Skhmt** [comment]
I'm using the one that was recommended for GraalVM 19.0.0, and building .exe files in 19.0.0, 19.1.0, and 19.2.0 (if I recall correctly, but definitely 19.0.0 and 19.1.0) worked. It's Windows SDK 7.1. I think it came with the 2010 Visual C++ Compilers. Does it say anywhere what specific version of the Windows SDK we now have to use?

**Comment by bobvandette** [comment]
You are build with the JDK 11 version of GraalVM which is most likely built with a newer Visual Studio.  Earlier GraalVM versions, were JDK 8 based.  The JDK 8 versions used Visual Studio 10.  The Java team builds JDK 11 with Visual Studio 2017.  There is a Windows implementation of GraalVM 19.3 that uses JDK 8.  You can try this as a work-around until you get a newer VS version.

**Comment by Skhmt** [comment]
Would newer versions work, or does it specifically have to be 2017?

**Comment by bobvandette** [comment]
I'd recommend using 2017 since that's the version that will be used for the Java binaries included for the Java 11 version of GraalVM but I don't know for sure which version the current 19.3 is using.  Aleksandar Pejovik who is assigned to this issue will know for sure.

**Comment by Skhmt** [comment]
That fixed it, thanks @bobvandette

**Comment by dougxc** [comment]
@pejovica it would be good if we could have Native Image check for compatibility with known Visual Studio versions and at least issue a warning when an untested version is present.

**Comment by remkop** [comment]
The documentation should be updated to clarify the prerequisites for building Windows native images for GraalVM 19.3: https://www.graalvm.org/docs/reference-manual/native-image/#prerequisites

Are the prerequisites different for Java 8 and Java 11?

**Comment by remkop** [comment]
I added https://github.com/oracle/graal/issues/1852 to improve the docs for the Windows native image prerequisites.

**Comment by tsatatwer** [comment]
I have exactly the same issue .

**Comment by Skhmt** [comment]
> 
> 
> I have exactly the same issue .

Install VS2017 community edition from https://my.visualstudio.com/Downloads?q=visual%20studio%202017&wt.mc_id=o~msft~vscom~older-downloads

**Comment by tsatatwer** [comment]
Done.

**Comment by Skhmt** [comment]
That completely fixed the issue for me - you have to use the `x64 Native Tools Command Prompt for VS 2017` command prompt in the Visual Studio 2017 start menu area.

**Comment by tsatatwer** [comment]
YES.

**Comment by Skhmt** [comment]
OK.

**Comment by remkop** [comment]
To activate the VS 2017 environment from the cmd prompt on a CI server: 

```
call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat"
```

**Comment by pejovica** [comment]
@remkop, that will set up a x86 toolchain, which we don't support. You need to set up a x64 toolchain, e.g., using `vcvars64.bat`.

**Comment by bobvandette** [comment]
I use this command to prepare to use Visual Studio 2017 for building GraalVM.

cd "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build"
call vcvarsall x64

**Comment by remkop** [comment]
@pejovica @bobvandette The full command to activate the VS 2017 environment was exactly what I was looking for. This is very helpful, thank you! I will try this and add a note to https://github.com/oracle/graal/issues/1852
