### ISSUE TITLE
ForkJoinTest is failing

### ISSUE THREAD

**Issue by jaikiran** [oracle/graal#1855]
I'm trying to get used to the substratevm test infrastructure and just incidentally happened to try out `com.oracle.svm.test.ForkJoinTest`. Running this test (both in IDE and `mx build unittest com.oracle.svm.test.ForkJoinTest`) fails consistently with:

```
mx unittest com.oracle.svm.test.ForkJoinTest
MxJUnitCore
JUnit version 4.12
.E
testForkJoinTaskGetWithException(com.oracle.svm.test.ForkJoinTest)
java.lang.ClassCastException: java.lang.RuntimeException cannot be cast to java.io.FileNotFoundException
	at com.oracle.svm.test.ForkJoinTest.testForkJoinTaskGetWithException(ForkJoinTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.oracle.mxtool.junit.MxJUnitWrapper.runRequest(MxJUnitWrapper.java:310)
	at com.oracle.mxtool.junit.MxJUnitWrapper.main(MxJUnitWrapper.java:226)

Time: 0.067
There was 1 failure:
1) com.oracle.svm.test.ForkJoinTest#testForkJoinTaskGetWithException
java.lang.ClassCastException: java.lang.RuntimeException cannot be cast to java.io.FileNotFoundException
	at com.oracle.svm.test.ForkJoinTest.testForkJoinTaskGetWithException(ForkJoinTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.oracle.mxtool.junit.MxJUnitWrapper.runRequest(MxJUnitWrapper.java:310)
	at com.oracle.mxtool.junit.MxJUnitWrapper.main(MxJUnitWrapper.java:226)

FAILURES!!!
Tests run: 1,  Failures: 1
```
The issue seems to be in the test case, since the real exception does indeed get wrapped a couple of times by the `RuntimeException`.

Am I running this test wrong? Or are these tests not part of the regular (CI and local) builds?

I'm on Java 8:
```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-20191009173705.graal.jdk8u-src-tar-gz-b07)
OpenJDK 64-Bit Server VM (build 25.232-b07-jvmci-19.3-b04, mixed mode)
```

**Comment by jaikiran** [comment]
PR with the fix https://github.com/oracle/graal/pull/1856

**Comment by dougxc** [comment]
@christianwimmer @cstancu do you know why this is not failing on our gates?

**Comment by christianwimmer** [comment]
@dougxc  In the gate we only run these test as a Native Image and not also on the HotSpot VM.

There is a slight difference in the exception behavior because `ForkJoinTask.getThrowableException()` uses reflection to create a new exception instance to wrap the exception thrown by the failing task. Since constructors are not available on Native Image unless explicitly registered using a reflection configuration file, the constructor lookup fails and `ForkJoinTask.getThrowableException()` throws the original exception. Which according to the comment on `getThrowableException()` is correct.
