### ISSUE TITLE
[native-image] cannot build an image with the 19.3.0 version of GraalVM CE for java8 and java11

### ISSUE THREAD

**Issue by plokhotnyuk** [oracle/graal#1863]
## graalvm-ce-java11-19.3.0
```
$ /usr/lib/jvm/graalvm-ce-java11/bin/native-image --no-server --no-fallback --allow-incomplete-classpath --report-unsupported-elements-at-runtime -jar target/scala-2.13/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.jar
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:341]    classlist:   2,283.88 ms
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:341]        (cap):     661.84 ms
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:341]        setup:   1,656.77 ms
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:341]   (typeflow):   9,919.53 ms
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:341]    (objects):   8,332.85 ms
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:341]   (features):     348.16 ms
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:341]     analysis:  18,896.28 ms
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:341]     (clinit):     371.34 ms
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:341]     universe:     736.70 ms
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:341]      (parse):   1,128.52 ms
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:341]     (inline):   2,112.65 ms
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:341]    (compile):   9,963.96 ms
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f26f47d6216, pid=341, tid=378
#
# JRE version: OpenJDK Runtime Environment (11.0.5+10) (build 11.0.5+10-jvmci-19.3-b05-LTS)
# Java VM: OpenJDK 64-Bit GraalVM CE 19.3.0 (11.0.5+10-jvmci-19.3-b05-LTS, mixed mode, sharing, tiered, jvmci, jvmci compiler, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xd5b216]  Symbol::as_unicode(int&) const+0x16
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P" (or dumping to /home/andriy/Projects/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-examples/core.341)
#
# An error report file with more information is saved as:
# /home/andriy/Projects/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-examples/hs_err_pid341.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

## graalvm-ce-java8-19.3.0
```
$ /usr/lib/jvm/graalvm-ce-java8/bin/native-image --no-server --no-fallback --allow-incomplete-classpath --report-unsupported-elements-at-runtime -jar target/scala-2.13/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.jar
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:489]    classlist:   3,007.30 ms
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:489]        (cap):     612.34 ms
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:489]        setup:   1,562.82 ms
warning: unknown anonymous info of class scala.collection.immutable.LazyList$State$Empty$, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by scala.collection.immutable.LazyList$State$Empty$ which is not following the naming convention.
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:489]   (typeflow):  39,573.50 ms
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:489]    (objects):   8,895.65 ms
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:489]   (features):     203.08 ms
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:489]     analysis:  48,841.41 ms
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:489]     (clinit):     398.47 ms
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:489]     universe:     873.56 ms
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:489]      (parse):  31,137.68 ms
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:489]     (inline):   1,066.95 ms
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:489]    (compile):   7,588.35 ms
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:489]      compile:  40,151.22 ms
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:489]        image:     531.41 ms
[jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT:489]        write:     125.15 ms
Fatal error: java.lang.RuntimeException: java.lang.RuntimeException: host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 1

Running command: cc -v -o /home/andriy/Projects/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-examples/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-5501497825700285691/exported_symbols.list -Wl,-x -L/tmp/SVM-5501497825700285691 -L/usr/lib/jvm/graalvm-ce-java8/jre/lib -L/usr/lib/jvm/graalvm-ce-java8/jre/lib/svm/clibraries/linux-amd64 /tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o /usr/lib/jvm/graalvm-ce-java8/jre/lib/svm/clibraries/linux-amd64/libffi.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/svm/clibraries/linux-amd64/libjvm.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/svm/clibraries/linux-amd64/libstrictmath.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/libnet.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/libzip.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/libjava.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/libnio.a -lm -lpthread -ldl -lpthread -lz -lrt

Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.4.0-1ubuntu1~18.04.1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) 
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-o' '/home/andriy/Projects/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-examples/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT' '-z' 'noexecstack' '-L/tmp/SVM-5501497825700285691' '-L/usr/lib/jvm/graalvm-ce-java8/jre/lib' '-L/usr/lib/jvm/graalvm-ce-java8/jre/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/7/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/7/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper -plugin-opt=-fresolution=/tmp/ccLPrf9e.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --sysroot=/ --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -z now -z relro -o /home/andriy/Projects/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-examples/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT -z noexecstack /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/7/crtbeginS.o -L/tmp/SVM-5501497825700285691 -L/usr/lib/jvm/graalvm-ce-java8/jre/lib -L/usr/lib/jvm/graalvm-ce-java8/jre/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/7/../../.. --gc-sections --dynamic-list /tmp/SVM-5501497825700285691/exported_symbols.list -x /tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o /usr/lib/jvm/graalvm-ce-java8/jre/lib/svm/clibraries/linux-amd64/libffi.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/svm/clibraries/linux-amd64/libjvm.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/svm/clibraries/linux-amd64/libstrictmath.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/libnet.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/libzip.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/libjava.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/libnio.a -lm -lpthread -ldl -lpthread -lz -lrt -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-linux-gnu/7/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crtn.o
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0x40): undefined reference to `Java_java_lang_invoke_MethodHandle_invokeBasic'
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0xd0): undefined reference to `Java_java_lang_invoke_MethodHandle_invokeBasic'
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0x138): undefined reference to `Java_java_lang_invoke_MethodHandle_invokeBasic'
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0x188): undefined reference to `Java_java_lang_invoke_MethodHandle_invokeBasic'
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0x1c0): undefined reference to `Java_java_lang_invoke_MethodHandle_invokeBasic'
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0x2b0): undefined reference to `Java_sun_misc_Unsafe_defineAnonymousClass'
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0x330): undefined reference to `Java_java_lang_invoke_MethodHandle_invokeBasic'
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0x368): undefined reference to `Java_sun_misc_Unsafe_defineClass'
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0x490): undefined reference to `Java_java_lang_invoke_MethodHandle_invokeBasic'
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0x4f8): undefined reference to `Java_java_lang_invoke_MethodHandle_invokeBasic'
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0x670): undefined reference to `Java_java_lang_invoke_MethodHandle_invokeBasic'
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0xa30): undefined reference to `Java_java_lang_invoke_MethodHandle_invokeBasic'
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0xbb8): undefined reference to `Java_java_lang_invoke_MethodHandle_invokeBasic'
collect2: error: ld returned 1 exit status

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:462)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:315)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:454)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:115)
Caused by: java.lang.RuntimeException: host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 1

Running command: cc -v -o /home/andriy/Projects/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-examples/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-5501497825700285691/exported_symbols.list -Wl,-x -L/tmp/SVM-5501497825700285691 -L/usr/lib/jvm/graalvm-ce-java8/jre/lib -L/usr/lib/jvm/graalvm-ce-java8/jre/lib/svm/clibraries/linux-amd64 /tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o /usr/lib/jvm/graalvm-ce-java8/jre/lib/svm/clibraries/linux-amd64/libffi.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/svm/clibraries/linux-amd64/libjvm.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/svm/clibraries/linux-amd64/libstrictmath.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/libnet.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/libzip.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/libjava.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/libnio.a -lm -lpthread -ldl -lpthread -lz -lrt

Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.4.0-1ubuntu1~18.04.1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) 
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-o' '/home/andriy/Projects/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-examples/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT' '-z' 'noexecstack' '-L/tmp/SVM-5501497825700285691' '-L/usr/lib/jvm/graalvm-ce-java8/jre/lib' '-L/usr/lib/jvm/graalvm-ce-java8/jre/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/7/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/7/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper -plugin-opt=-fresolution=/tmp/ccLPrf9e.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --sysroot=/ --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -z now -z relro -o /home/andriy/Projects/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-examples/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT -z noexecstack /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/7/crtbeginS.o -L/tmp/SVM-5501497825700285691 -L/usr/lib/jvm/graalvm-ce-java8/jre/lib -L/usr/lib/jvm/graalvm-ce-java8/jre/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/7/../../.. --gc-sections --dynamic-list /tmp/SVM-5501497825700285691/exported_symbols.list -x /tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o /usr/lib/jvm/graalvm-ce-java8/jre/lib/svm/clibraries/linux-amd64/libffi.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/svm/clibraries/linux-amd64/libjvm.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/svm/clibraries/linux-amd64/libstrictmath.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/libnet.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/libzip.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/libjava.a /usr/lib/jvm/graalvm-ce-java8/jre/lib/libnio.a -lm -lpthread -ldl -lpthread -lz -lrt -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-linux-gnu/7/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crtn.o
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0x40): undefined reference to `Java_java_lang_invoke_MethodHandle_invokeBasic'
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0xd0): undefined reference to `Java_java_lang_invoke_MethodHandle_invokeBasic'
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0x138): undefined reference to `Java_java_lang_invoke_MethodHandle_invokeBasic'
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0x188): undefined reference to `Java_java_lang_invoke_MethodHandle_invokeBasic'
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0x1c0): undefined reference to `Java_java_lang_invoke_MethodHandle_invokeBasic'
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0x2b0): undefined reference to `Java_sun_misc_Unsafe_defineAnonymousClass'
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0x330): undefined reference to `Java_java_lang_invoke_MethodHandle_invokeBasic'
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0x368): undefined reference to `Java_sun_misc_Unsafe_defineClass'
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0x490): undefined reference to `Java_java_lang_invoke_MethodHandle_invokeBasic'
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0x4f8): undefined reference to `Java_java_lang_invoke_MethodHandle_invokeBasic'
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0x670): undefined reference to `Java_java_lang_invoke_MethodHandle_invokeBasic'
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0xa30): undefined reference to `Java_java_lang_invoke_MethodHandle_invokeBasic'
/tmp/SVM-5501497825700285691/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.o:(.data+0xbb8): undefined reference to `Java_java_lang_invoke_MethodHandle_invokeBasic'
collect2: error: ld returned 1 exit status

	at com.oracle.svm.hosted.image.NativeBootImageViaCC.write(NativeBootImageViaCC.java:382)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:652)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
```

Steps to reproduce:
1. Clone `jsoniter-scala` repo: 
```
$ git clone https://github.com/plokhotnyuk/jsoniter-scala.git
```

2. Enter to the cloned directory and checkout for the specific branch:
```
$ cd jsoniter-scala\jsoniter-scala-examples
$ git checkout native-image-build-failure
```
3. [Install latest version of `sbt`](https://www.scala-sbt.org/1.0/docs/Setup.html) and/or ensure that it already installed properly: 
```
$ sbt about
```
4. Build an uber jar and test that it works fine:
```
$ sbt clean assembly
$ java -jar target/scala-2.13/jsoniter-scala-examples-assembly-0.1.0-SNAPSHOT.jar
```
It should print the following output to the console:
```
User(John,List(Device(1,HTC One X)))
{"name":"John","devices":[{"id":2,"model":"iPhone X"}]}
```
5. Ensure that the compiler is installed
```
$ /usr/lib/jvm/graalvm-ce-java11/bin/native-image --version
GraalVM Version 19.3.0 CE
```
and optionally:
```
$ sudo /usr/lib/jvm/graalvm-ce-19/bin/gu install native-image
```
6. Start building the image using commands provided with errors.

**Comment by olpaw** [comment]
Atm, we can only handle simple method handles that can be reduced to a single call target at image build time. @plokhotnyuk does the example work with `GraalVM 19.2.1`?

**Comment by plokhotnyuk** [comment]
@plokhotnyuk yes, it works, but to test it you need reset branch to previous commit or just checkout the master branch with [the substitution required for 19.2.1](https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-examples/src/main/scala-2.13/com/github/plokhotnyuk/jsoniter_scala/examples/Target_scala_runtime_Statics.java).

**Comment by olpaw** [comment]
Thanks for checking. That means that we are now seeing code path that we cannot handle that we previously substituted away. I classify this is a bug. Thanks for the report!

**Comment by aclement** [comment]
I've also just observed this with a Spring application (vanilla-jpa sample). I was running on my own built graal, commit #c2ee5c253e6 (Dec 16) on Java11 base. I could create repro instructions if you really need them, but they might a little painful.

**Comment by christianwimmer** [comment]
Fixed in https://github.com/oracle/graal/commit/3a96706037695a41e025c3d3b873f16632c00820
