### ISSUE TITLE
[native-image] Building image for "svmjunit" crash on AArch64.

### ISSUE THREAD

**Issue by XiaohongGong** [oracle/graal#1872]
Building image for "svmjunit" on AArch64 fail by with the following error:

    Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.AssertionError: HotSpot object in image org.graalvm.compiler.hotspot.meta.HotSpotObjdumpDisassemblerProvider
        at parsing org.graalvm.compiler.printer.CFGPrinterObserver$DisassemblerHolder.access$000(CFGPrinterObserver.java:257)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2475)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:94)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3291)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3093)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:977)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:871)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:221)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:340)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)

It's caused due to a hotspot object being included to the image file. And the problem codes in `CFGPrinterObserver$DiassemblerHolder` :

    if (arch.equals("aarch64")) {
        if (name.contains("hsdis-objdump")) {
             selected = d;
             break;
        }
    }

This loads the HotSpotObjdumpDisassemblerProvider as the disassembler. Basically it's invalid for svm. So is there any reason that it does not use `HexCodeFileDisassemblerProvider`  on AArch64 like x86?

**Comment by tshull226** [comment]
Hi @sanzinger do you have any input on this? It looks like `HexCodeFileDisassemblerProvider` uses an old maxine library which shouldn't be able to disassemble AArch64. Should there be a check added to use the "nop" disassembler provider if truffle on svm is being used?

**Comment by sanzinger** [comment]
I came across this issue as well. We should move this Assembler type away from the hotspot package, since it is unrelated to hotspot and well usable for SVM.

**Comment by XiaohongGong** [comment]
Hi @sanzinger , thanks for your additional comment. Then I will create a PR to fix it. Thank you!

**Comment by sanzinger** [comment]
Not necessary I have one already in progress.

**Comment by sanzinger** [comment]
Here is the change: https://github.com/sanzinger/graal/tree/sa/GR-20544 Unfortunately, it is not complete atm. When using it with truffle and disabling `ProcessBuilder`, the image cannot be compiled.  https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.truffle/src/com/oracle/svm/truffle/TruffleFeature.java#L876

**Comment by XiaohongGong** [comment]
So is there any reason that we need to change the original `Runtime.getRuntime().exec(cmdline)` to `ProcessBuilder.start` ? I'm not familiar with this part, just curious about it. Thank you!

**Comment by XiaohongGong** [comment]
Hi @sanzinger , how is this issue going on? Is there any update? Thanks!

**Comment by XiaohongGong** [comment]
@sanzinger is there any update for this issue?

**Comment by XiaohongGong** [comment]
Hi @sanzinger any update?

**Comment by sanzinger** [comment]
Hi @XiaohongGong 

> So is there any reason that we need to change the original Runtime.getRuntime().exec(cmdline) to ProcessBuilder.start ? I'm not familiar with this part, just curious about it. Thank you!

I don't remember exactly, why I did this, I think it was because `Runtime.exec` is/was not well supported on SVM.

I am reviewing this change and will try to merge it asap.

**Comment by sanzinger** [comment]
Ok, I just ran the tests again and found the problem I had in January with this change.

We can also build images which have certain restrictions such as not allow to run external commands for security reasons. This call from the compiler violates this rule and aborts the compilation. [see TruffleFeature.java](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.truffle/src/com/oracle/svm/truffle/TruffleFeature.java#L947)

Unfortunately in the compiler project we cannot probe whether this feature is disabled or enabled. 
One way is to reflectively try to read field `com.oracle.truffle.polyglot.PolyglotEngineImpl.ALLOW_CREATE_PROCESS` and do not use this disassembler then.  This is an ugly solution.

I am looking for an option to test whether the process builder will be allowed in the target image - and if not we must choose another disassembler or even an empty disassembler implementation.

**Comment by XiaohongGong** [comment]
Hi @sanzinger , that make sense! Thanks for your external explanation! So is there any possible influence if we choose an empty disassembler implementation? Any influence to the printed CFG? Thanks!

**Comment by teshull** [comment]
Hi @XiaohongGong. A fix for this was merged yesterday.
