### ISSUE TITLE
GraalVM 19.3.0 native image: java.lang.SecurityException: Invalid signature file digest for Manifest main attributes

### ISSUE THREAD

**Issue by bmhm** [oracle/graal#1873]
Dear GraalVM team,

I am trying to package a native image of an openJFX application using graalvm-java11-linux-amd64 and openjfx-11.0.2 and micronauts 1.2.6.

I get this error upon invocation:

```java
[my.app:7414]    classlist:   6,512.17 ms
Fatal error: java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
        at java.base/sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:336)
        at java.base/sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:269)
        at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:316)
        at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:230)
        at java.base/java.util.jar.JarFile.initializeVerifier(JarFile.java:757)
        at java.base/java.util.jar.JarFile.ensureInitialization(JarFile.java:1034)
        at java.base/java.util.jar.JavaUtilJarAccessImpl.ensureInitialization(JavaUtilJarAccessImpl.java:69)
        at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:870)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:517)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:260)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:454)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:115)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:479)
Error: Image build request failed with exit status 1
```

There is no further clue.

Building using maven:

```xml
<plugin>
            <groupId>com.oracle.substratevm</groupId>
            <artifactId>native-image-maven-plugin</artifactId>
            <version>19.2.1</version>
            <executions>
              <execution>
                <goals>
                  <goal>native-image</goal>
                </goals>
                <phase>package</phase>
                <configuration>
                  <mainClass>${exec.mainClass}</mainClass>
                  <buildArgs>
                    --no-server
                    --no-fallback
                  </buildArgs>
                </configuration>
              </execution>
            </executions>
          </plugin>
```

I get a warning of a version mismatch between the plugin and the actual GraalVM JDK. However, I am using the latest version of both and I suppose oracle would not unintentionally forget to release a new plugin if there was a known error.

Also, the same error occurs when not using the maven plugin, but applying the `native-image` command to a fat shaded jar. Thus, the error is not in the plugin, but the native image tool.

I did some digging, maybe this issue is related:
https://github.com/quarkusio/quarkus/issues/2686

HTH and thanks for GraalVM.
Ben

**Comment by bmhm** [comment]
Hi, I already found a workaround.

In the shade plugin:
```xml
            <configuration>
              <transformers>
                <transformer
                    implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                  <mainClass>${exec.mainClass}</mainClass>
                </transformer>
                <transformer
                    implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
                <transformer implementation="org.apache.maven.plugins.shade.resource.DontIncludeResourceTransformer">
                  <resource>.SF</resource>
                </transformer>
                <transformer implementation="org.apache.maven.plugins.shade.resource.DontIncludeResourceTransformer">
                  <resource>.DSA</resource>
                </transformer>
                <transformer implementation="org.apache.maven.plugins.shade.resource.DontIncludeResourceTransformer">
                  <resource>.RSA</resource>
                </transformer>
              </transformers>
```

The last three entries are the important ones. They will exclude signatures from existing JARs.
So (just maybe) this is not a problem to be solved in GraalVM.

**Comment by olpaw** [comment]
This is not something that needs fixing on our side.
