### ISSUE TITLE
[native-image] -H:IncludeResourceBundles does not include XML resource bundles

### ISSUE THREAD

**Issue by fhoeben** [oracle/graal#1878]
I'm trying to create a native image using Liquibase. It has an XML based resource bundle (`liquibase/i18n/liquibase-commandline-helptext`). By default (of course) this is not included in the image, but when I add `-H:IncludeResourceBundles=liquibase/i18n/liquibase-core,liquibase/i18n/liquibase-commandline-helptext` the liquibase-core is added just fine, but I get an exception during image generation:

```
Fatal error: java.util.MissingResourceException: Can't find bundle for base name liquibase/i18n/liquibase-commandline-helptext, locale en_US
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:1091)
        at com.oracle.svm.core.jdk.LocalizationSupport.getBundleInDefaultLocale(LocalizationSupport.java:73)
        at com.oracle.svm.core.jdk.LocalizationSupport.addBundleToCache(LocalizationSupport.java:67)
        at com.oracle.svm.core.jdk.LocalizationSupport.includeResourceBundles(LocalizationSupport.java:87)
        at com.oracle.svm.core.jdk.LocalizationSupport.<init>(LocalizationSupport.java:59)
        at com.oracle.svm.core.jdk.LocalizationFeature.afterRegistration(LocalizationFeature.java:108)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$11(NativeImageGenerator.java:809)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:809)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:524)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
```

When I add a .properties version of the specified bundle I'm able to generate a native image, but my application fails to start as it expects and XMLResourceBundle, and doesn't get one...
```
java.lang.ClassCastException: java.util.PropertyResourceBundle cannot be cast to liquibase.util.xml.XMLResourceBundle
    at liquibase.integration.commandline.Main.<clinit>(Main.java:65)
```

How do I enable usage of XML resource bundles by a native image?

**Comment by fhoeben** [comment]
The bundle is accessed using:
```
    private static XMLResourceBundle commandLineHelpBundle = ((XMLResourceBundle) getBundle
            ("liquibase/i18n/liquibase-commandline-helptext", new XmlResourceBundleControl()));
```

Although I have to admit I don't believe there is any need in this particular case to cast the bundle to an `XMLResourceBundle` this is existing code, in a library, which I would like to be able to use as-is in my native image.

**Comment by peter-hofer** [comment]
Thank you for your report @fhoeben . We currently don't support `ResourceBundle.Control` with `IncludeResourceBundles` and therefore also not `XmlResourceBundleControl`, and we treat it the same as regular `.properties` resources, which is why the file can't be found in the first place.
Implementing this is tricky because a concrete `Control` object must be available during the image build to locate and load the `ResourceBundle`. In your case, since this is a statically initialized variable, you can try running the static initializer of the enclosing class using `--initalize-at-build-time=com.acme.MyClass` (see also CLASS-INITIALIZATION.md).
