### ISSUE TITLE
GraalVM-java11-19.3.0 on Win 10 native-image hello world still fails.

### ISSUE THREAD

**Issue by jgranduel** [oracle/graal#1886]
Hi, 

testing again `native-image.cmd` against a Hello World Class from command line (PowerShell-7), but still fails.
`
A.java : 
public class A {
    public static void main(String[] args){
        System.out.println("Hello Graalvm!");
    }
}
`
- $env:GRAALVM_HOME = ".../graalvm-java11-19.3.0"
- cl.exe defined: `"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.20.27508\bin\Hostx64\x64\cl.exe"`
- vcvars64.bat run with success (`"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"`)
```
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.0
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
```
- javac -version
javac 11.0.5

```
>javac A.java
>native-image.cmd "-H:+ReportExceptionStackTraces" A
[a:12804]    classlist:   1,608.55 ms
[a:12804]        (cap):     696.01 ms
[a:12804]        setup:     968.76 ms
Error: 
  Error compiling query code (in <APPDATA FOLDER>\Local\Temp\SVM-11282833246357143750\WindowsDirectives.cpp). 
  Compiler command  CL <APPDATA FOLDER>\Local\Temp\SVM-11282833246357143750\WindowsDirectives.cpp /Fe<APPDATA FOLDER>\Local\Temp\SVM-11282833246357143750\WindowsDirectives.exe 
  output included error: [Compilateur d'optimisation Microsoft (R) C/C++ version 19.20.27508.1 pour x64, Copyright (C) Microsoft Corporation. Tous droits réservés., ]
  
com.oracle.svm.core.util.UserError$UserException: Error compiling query code (in <APPDATA FOLDER>\Local\Temp\SVM-11282833246357143750\WindowsDirectives.cpp). 

Compiler command  CL <APPDATA FOLDER>\Local\Temp\SVM-11282833246357143750\WindowsDirectives.cpp /Fe<APPDATA FOLDER>\Local\Temp\SVM-11282833246357143750\WindowsDirectives.exe output included error: [Compilateur d'optimisation Microsoft (R) C/C++ version 19.20.27508.1 pour x64, Copyright (C) Microsoft Corporation. Tous droits réservés., ]
        at com.oracle.svm.core.util.UserError.abort(UserError.java:114)
        at com.oracle.svm.hosted.c.NativeLibraries.reportErrors(NativeLibraries.java:214)
        at com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1518)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1006)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:835)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:528)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1
```

HTH, if only for documentation... Best regards

**Comment by gdoenlen** [comment]
Not sure if related, but I also get silent failures from `native-image.cmd`  when trying to compile quarkus apps on windows with both 19.3 and 19.2.1: https://github.com/quarkusio/quarkus/issues/5675

**Comment by pejovica** [comment]
@jgranduel, could you try from the Command Prompt instead of PowerShell to see if it makes any difference.

**Comment by jgranduel** [comment]
Success!
```
>set GRAALVM_HOME=path\to\graalvm-java11-19.3.0
>set PATH=path\to\graalvm-ce-java11-19.3.0\bin;%PATH%

>cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build"
>.\vcvars64.bat

>javac --version
javac 11.0.5
>native-image.cmd A
[a:16264]    classlist:   1,212.47 ms
[a:16264]        (cap):   2,914.51 ms
[a:16264]        setup:   3,947.91 ms
[a:16264]   (typeflow):   4,936.89 ms
[a:16264]    (objects):   3,841.67 ms
[a:16264]   (features):     230.56 ms
[a:16264]     analysis:   9,207.42 ms
[a:16264]     (clinit):     144.46 ms
[a:16264]     universe:     413.72 ms
[a:16264]      (parse):     716.47 ms
[a:16264]     (inline):   1,416.76 ms
[a:16264]    (compile):   6,269.48 ms
[a:16264]      compile:   8,951.05 ms
[a:16264]        image:     744.44 ms
[a:16264]        write:     588.48 ms
[a:16264]      [total]:  25,254.90 ms

.\a.exe
Hello GraalVM!
```
Thanks, I should have tried indeed! (Please, support PowerShell ;-) !)

**Comment by jbreathe** [comment]
It seems like it is not an issue with Graal, but with PowerShell itself.
See [this](https://stackoverflow.com/q/2124753) SO question for details and workarounds.

**Comment by pejovica** [comment]
Closing as resolved.
