### ISSUE TITLE
[native-image] UserException thrown when Version is used from a substitution class 

### ISSUE THREAD

**Issue by gwenneg** [oracle/graal#1889]
Hi GraalVM team!

I tried to replace `System.getProperty("org.graalvm.version").startsWith("19.2.")` with `Version.getCurrent().compareTo(19, 3) < 0` in a class similar to this one:

```
@TargetClass(value = Field.class, onlyWith = GraalVersion19_2.class)
final class FieldReplacement {
    // Content omitted
}

final class GraalVersion19_2 implements BooleanSupplier {
    public boolean getAsBoolean() {
        return Version.getCurrent().compareTo(19, 3) < 0;
    }
}
```

The following exception was then thrown during the native image generation:

```
Error: ImageSingletons do not contain key org.graalvm.home.HomeFinder
com.oracle.svm.core.util.UserError$UserException: ImageSingletons do not contain key org.graalvm.home.HomeFinder
	at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
	at com.oracle.svm.hosted.ImageSingletonsSupportImpl$HostedManagement.doLookup(ImageSingletonsSupportImpl.java:119)
	at com.oracle.svm.hosted.ImageSingletonsSupportImpl.lookup(ImageSingletonsSupportImpl.java:44)
	at org.graalvm.nativeimage.ImageSingletons.lookup(ImageSingletons.java:86)
	at org.graalvm.home.HomeFinder.getInstance(HomeFinder.java:99)
	at org.graalvm.home.Version.getCurrent(Version.java:293)
	at io.quarkus.runtime.graal.GraalVersion19_2.getAsBoolean(FieldReplacement.java:62)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findTargetClass(AnnotationSubstitutionProcessor.java:806)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:252)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:230)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:876)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:825)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:528)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
```

Is that an expected behavior?

**Comment by jaikiran** [comment]
Hello @gwenneg, I think this might help https://github.com/oracle/graal/pull/1890

**Comment by gwenneg** [comment]
Great, thanks @jaikiran!

**Comment by eregon** [comment]
A workaround for 19.3.0 only (#1890 will change it) would be to include that feature explicitly with:
```
--features=org.graalvm.home.HomeFinderFeature
```

**Comment by gwenneg** [comment]
That's good to know, thanks @eregon!

**Comment by gwenneg** [comment]
Was this issue fixed in `19.3.1` as suggested by the current milestone? I don't see the fix in the `19.3.1` commits and the issue is not mentioned in the [release note](https://www.graalvm.org/docs/release-notes/19_3/).

**Comment by gwenneg** [comment]
@thomaswue Do you have the answer to my question above?

**Comment by dougxc** [comment]
@cstancu maybe you can answer this question?
