### ISSUE TITLE
InvokeMember on JavaObject - Unknown identifier

### ISSUE THREAD

**Issue by Mogztter** [oracle/graal#1910]
```java
import org.graalvm.polyglot.*;

import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

public class Polyglot {
  public static void main(String[] args) {
    Context context = Context.newBuilder("js")
      .allowIO(true)
      .allowPolyglotAccess(PolyglotAccess.ALL)
      .build();
    context.getPolyglotBindings().putMember("IncludeResolver", new IncludeResolver());
    context.eval("js", "var IncludeResolver = Polyglot.import('IncludeResolver');");
    context.eval("js", "console.log(IncludeResolver.pwd())");
  }

  public static class IncludeResolver {
    public String pwd() {
      return Paths.get("").toAbsolutePath().toString();
    }
  }
}
```
```console
$ /path/to/graalvm/bin/java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-20191008104205.buildslave.jdk8u-src-tar--b07)
OpenJDK 64-Bit GraalVM CE 19.3.0 (build 25.232-b07-jvmci-19.3-b05, mixed mode)

$ /path/to/graalvm/bin/javac ./Polyglot.java -d build/
$ /path/to/graalvm/bin/java -classpath build Polyglot
Exception in thread "main" TypeError: invokeMember (pwd) on JavaObject[Polyglot$IncludeResolver@2ed2d9cb (Polyglot$IncludeResolver)] failed due to: Unknown identifier: pwd
	at <js> :program(Unnamed:1:12-32)
	at org.graalvm.polyglot.Context.eval(Context.java:370)
	at Polyglot.main(Polyglot.java:18)
```

The above code was working with GraalVM 1.0.0-rc12.

**Comment by Mogztter** [comment]
Sorry it was a restriction introduced 1.0.0-rc15 I guess. Using `allowAllAccess(true)` solved this issue.

**Comment by max-datagamma** [comment]
If you're using Java modules, this can also be caused by trying to access a class in a module that Graal does not have access to. Just add the package for the class in question to your module-info.java, e.g.:
opens com.acme.server.utils;

**Comment by pml-lang** [comment]
@max-datagamma: Thanks a lot. That solved it for me.
