### ISSUE TITLE
[native-image] Native image generation in docker container crashes with `--enable-https`

### ISSUE THREAD

**Issue by fhoeben** [oracle/graal#1918]
I'm trying to build a native version of wiremock. I got an image created, but when I tried to run it, it failed with message `Exception in thread "main" java.security.NoSuchAlgorithmException: PKIX TrustManagerFactory not available`.

So I added the `--enable-https` option to my native-image command. Then I got a whole stack trace:
```
Fatal error: java.lang.RuntimeException: java.lang.RuntimeException: host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 1

Running command: cc -v -o /wiremock/wiremock -z noexecstack -Wl,--gc-sections -Wl,-x -static -L/tmp/SVM-9064945281140919797 -L/opt/graalvm-ce-java8-19.3.0/jre/lib -L/opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64 /tmp/SVM-9064945281140919797/wiremock.o /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libffi.a /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libjvm.a /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libstrictmath.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libnet.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libzip.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libjava.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libnio.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libsunec.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libsunec.a -lm -lpthread -ldl -lpthread -lz -lrt -lstdc++

Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39.0.3) (GCC) 
COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/:/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/:/usr/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/
LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-o' '/wiremock/wiremock' '-z' 'noexecstack' '-static' '-L/tmp/SVM-9064945281140919797' '-L/opt/graalvm-ce-java8-19.3.0/jre/lib' '-L/opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/libexec/gcc/x86_64-redhat-linux/4.8.5/collect2 --build-id --no-add-needed --hash-style=gnu -m elf_x86_64 -static -o /wiremock/wiremock -z noexecstack /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtbeginT.o -L/tmp/SVM-9064945281140919797 -L/opt/graalvm-ce-java8-19.3.0/jre/lib -L/opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../.. --gc-sections -x /tmp/SVM-9064945281140919797/wiremock.o /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libffi.a /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libjvm.a /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libstrictmath.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libnet.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libzip.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libjava.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libnio.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libsunec.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libsunec.a -lm -lpthread -ldl -lpthread -lz -lrt -lstdc++ --start-group -lgcc -lgcc_eh -lc --end-group /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtend.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crtn.o
/tmp/SVM-9064945281140919797/wiremock.o:(.data+0xca0): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/graalvm-ce-java8-19.3.0/jre/lib/libnio.a(UnixNativeDispatcher.o): In function `Java_sun_nio_fs_UnixNativeDispatcher_getgrgid':
/opt/jprt/T/P1/225159.buildslave/s/jdk/src/solaris/native/sun/nio/fs/UnixNativeDispatcher.c:1037: warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/graalvm-ce-java8-19.3.0/jre/lib/libnio.a(UnixNativeDispatcher.o): In function `prepAttributes':
/opt/jprt/T/P1/225159.buildslave/s/jdk/src/solaris/native/sun/nio/fs/UnixNativeDispatcher.c:444: warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/SVM-9064945281140919797/wiremock.o:(.data+0x328): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/graalvm-ce-java8-19.3.0/jre/lib/libnio.a(UnixNativeDispatcher.o): In function `prepAttributes':
/opt/jprt/T/P1/225159.buildslave/s/jdk/src/solaris/native/sun/nio/fs/UnixNativeDispatcher.c:443: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/jprt/T/P1/225159.buildslave/s/jdk/src/solaris/native/sun/nio/fs/UnixNativeDispatcher.c:443: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/graalvm-ce-java8-19.3.0/jre/lib/libnet.a(Inet4AddressImpl.o): In function `Java_java_net_Inet4AddressImpl_lookupAllHostAddr':
/opt/jprt/T/P1/225159.buildslave/s/jdk/src/solaris/native/java/net/Inet4AddressImpl.c:418: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/SVM-9064945281140919797/wiremock.o:(.data+0x478): undefined reference to `Java_sun_misc_Unsafe_defineClass'
/opt/graalvm-ce-java8-19.3.0/jre/lib/libjava.a(URLClassPath.o): In function `Java_sun_misc_URLClassPath_getLookupCacheURLs':
/opt/jprt/T/P1/225159.buildslave/s/jdk/src/share/native/sun/misc/URLClassPath.c:77: undefined reference to `JVM_GetResourceLookupCacheURLs'
/opt/graalvm-ce-java8-19.3.0/jre/lib/libjava.a(VM.o): In function `Java_sun_misc_VM_latestUserDefinedLoader0':
/opt/jprt/T/P1/225159.buildslave/s/jdk/src/share/native/sun/misc/VM.c:116: undefined reference to `JVM_LatestUserDefinedLoader'
collect2: error: ld returned 1 exit status

        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:462)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:315)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:454)
        at com.oracle.svm.hosted.server.NativeImageBuildServer.executeCompilation(NativeImageBuildServer.java:402)
        at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$processCommand$8(NativeImageBuildServer.java:339)
        at com.oracle.svm.hosted.server.NativeImageBuildServer.withJVMContext(NativeImageBuildServer.java:420)
        at com.oracle.svm.hosted.server.NativeImageBuildServer.processCommand(NativeImageBuildServer.java:336)
        at com.oracle.svm.hosted.server.NativeImageBuildServer.processRequest(NativeImageBuildServer.java:280)
        at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$serve$7(NativeImageBuildServer.java:240)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 1

Running command: cc -v -o /wiremock/wiremock -z noexecstack -Wl,--gc-sections -Wl,-x -static -L/tmp/SVM-9064945281140919797 -L/opt/graalvm-ce-java8-19.3.0/jre/lib -L/opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64 /tmp/SVM-9064945281140919797/wiremock.o /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libffi.a /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libjvm.a /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libstrictmath.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libnet.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libzip.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libjava.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libnio.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libsunec.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libsunec.a -lm -lpthread -ldl -lpthread -lz -lrt -lstdc++

Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39.0.3) (GCC) 
COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/:/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/:/usr/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/
LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-o' '/wiremock/wiremock' '-z' 'noexecstack' '-static' '-L/tmp/SVM-9064945281140919797' '-L/opt/graalvm-ce-java8-19.3.0/jre/lib' '-L/opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/libexec/gcc/x86_64-redhat-linux/4.8.5/collect2 --build-id --no-add-needed --hash-style=gnu -m elf_x86_64 -static -o /wiremock/wiremock -z noexecstack /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtbeginT.o -L/tmp/SVM-9064945281140919797 -L/opt/graalvm-ce-java8-19.3.0/jre/lib -L/opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../.. --gc-sections -x /tmp/SVM-9064945281140919797/wiremock.o /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libffi.a /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libjvm.a /opt/graalvm-ce-java8-19.3.0/jre/lib/svm/clibraries/linux-amd64/libstrictmath.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libnet.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libzip.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libjava.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libnio.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libsunec.a /opt/graalvm-ce-java8-19.3.0/jre/lib/libsunec.a -lm -lpthread -ldl -lpthread -lz -lrt -lstdc++ --start-group -lgcc -lgcc_eh -lc --end-group /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtend.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crtn.o
/tmp/SVM-9064945281140919797/wiremock.o:(.data+0xca0): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/graalvm-ce-java8-19.3.0/jre/lib/libnio.a(UnixNativeDispatcher.o): In function `Java_sun_nio_fs_UnixNativeDispatcher_getgrgid':
/opt/jprt/T/P1/225159.buildslave/s/jdk/src/solaris/native/sun/nio/fs/UnixNativeDispatcher.c:1037: warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/graalvm-ce-java8-19.3.0/jre/lib/libnio.a(UnixNativeDispatcher.o): In function `prepAttributes':
/opt/jprt/T/P1/225159.buildslave/s/jdk/src/solaris/native/sun/nio/fs/UnixNativeDispatcher.c:444: warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/SVM-9064945281140919797/wiremock.o:(.data+0x328): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/graalvm-ce-java8-19.3.0/jre/lib/libnio.a(UnixNativeDispatcher.o): In function `prepAttributes':
/opt/jprt/T/P1/225159.buildslave/s/jdk/src/solaris/native/sun/nio/fs/UnixNativeDispatcher.c:443: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/jprt/T/P1/225159.buildslave/s/jdk/src/solaris/native/sun/nio/fs/UnixNativeDispatcher.c:443: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/graalvm-ce-java8-19.3.0/jre/lib/libnet.a(Inet4AddressImpl.o): In function `Java_java_net_Inet4AddressImpl_lookupAllHostAddr':
/opt/jprt/T/P1/225159.buildslave/s/jdk/src/solaris/native/java/net/Inet4AddressImpl.c:418: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/SVM-9064945281140919797/wiremock.o:(.data+0x478): undefined reference to `Java_sun_misc_Unsafe_defineClass'
/opt/graalvm-ce-java8-19.3.0/jre/lib/libjava.a(URLClassPath.o): In function `Java_sun_misc_URLClassPath_getLookupCacheURLs':
/opt/jprt/T/P1/225159.buildslave/s/jdk/src/share/native/sun/misc/URLClassPath.c:77: undefined reference to `JVM_GetResourceLookupCacheURLs'
/opt/graalvm-ce-java8-19.3.0/jre/lib/libjava.a(VM.o): In function `Java_sun_misc_VM_latestUserDefinedLoader0':
/opt/jprt/T/P1/225159.buildslave/s/jdk/src/share/native/sun/misc/VM.c:116: undefined reference to `JVM_LatestUserDefinedLoader'
collect2: error: ld returned 1 exit status

        at com.oracle.svm.hosted.image.NativeBootImageViaCC.write(NativeBootImageViaCC.java:382)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:652)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
The command '/bin/sh -c native-image   -cp .:wiremock-standalone.jar:slf4j-simple.jar   -H:Name=wiremock --static  --no-fallback   --report-unsupported-elements-at-runtime --allow-incomplete-classpath   --enable-https   com.github.tomakehurst.wiremock.standalone.WireMockServerRunner' returned a non-zero code: 1
``` 

I'm using the following docker file  (full project at https://github.com/fhoeben/wiremock-docker/tree/graal)
```
 ARG GRAALVM_VERSION=latest
ARG BUSYBOX_VERSION=latest

FROM oracle/graalvm-ce:${GRAALVM_VERSION} as graal
ARG WIREMOCK_VERSION=2.25.1

RUN gu install native-image

WORKDIR /wiremock

ADD https://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-jre8-standalone/${WIREMOCK_VERSION}/wiremock-jre8-standalone-${WIREMOCK_VERSION}.jar \
    /wiremock/wiremock-standalone.jar
ADD https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.29/slf4j-simple-1.7.29.jar \
    /wiremock/slf4j-simple.jar

RUN mkdir -p META-INF
COPY native-image META-INF/native-image

#CMD java -agentlib:native-image-agent=config-output-dir=META-INF/native-image \
#  -cp wiremock-standalone.jar:slf4j-simple.jar \
#  com.github.tomakehurst.wiremock.standalone.WireMockServerRunner

RUN native-image \
  -cp .:wiremock-standalone.jar:slf4j-simple.jar \
  -H:Name=wiremock --static  --no-fallback \
  --report-unsupported-elements-at-runtime --allow-incomplete-classpath \
  --enable-https \
  com.github.tomakehurst.wiremock.standalone.WireMockServerRunner

FROM scratch
WORKDIR /wiremock
COPY --from=graal /wiremock/wiremock /wiremock/

ENTRYPOINT ["/wiremock/wiremock"]
EXPOSE 8080
```

**Comment by cstancu** [comment]
@fhoeben can you still replicate this issue with latest GraalVM release?

**Comment by fhoeben** [comment]
I no longer get the stack trace. A quick retry gave me another error on starting the created image, but build seems to work now...

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:291)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(DynamicHub.java:855)
        at com.github.tomakehurst.wiremock.standalone.CommandLineOptions.httpServerFactory(CommandLineOptions.java:207)
        at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:75)
        at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.run(WireMockServerRunner.java:65)
        at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.main(WireMockServerRunner.java:125)
Caused by: java.lang.NoSuchMethodException: com.github.tomakehurst.wiremock.jetty94.Jetty94HttpServer.<init>(com.github.tomakehurst.wiremock.core.Options, com.github.tomakehurst.wiremock.http.AdminRequestHandler, com.github.tomakehurst.wiremock.http.StubRequestHandler)
        at java.lang.Class.getConstructor0(DynamicHub.java:3082)
        at java.lang.Class.getConstructor(DynamicHub.java:1825)
        at com.github.tomakehurst.wiremock.jetty9.JettyHttpServerFactory.safelyGetConstructor(JettyHttpServerFactory.java:50)
        at com.github.tomakehurst.wiremock.jetty9.JettyHttpServerFactory.getServerConstructor(JettyHttpServerFactory.java:36)
        at com.github.tomakehurst.wiremock.jetty9.JettyHttpServerFactory.<clinit>(JettyHttpServerFactory.java:30)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:351)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:271)
        ... 6 more
```

**Comment by cstancu** [comment]
That looks like you are missing a reflection configuration.

**Comment by rafaeldff** [comment]
I'm seeing a similar error in a container with 22.1.0. I opened an issue about it in the _container_ repository: https://github.com/graalvm/container/issues/59
