### ISSUE TITLE
Getting following error while generating excel file using native image.

### ISSUE THREAD

**Issue by mohitochani** [oracle/graal#1929]
Code generates an excel file using apache poi.
Code getting executed as required in eclipse.

Exception in thread "main" java.lang.ClassCastException: org.apache.xmlbeans.impl.values.XmlComplexContentImpl cannot be cast to org.openxmlformats.schemas.spreadsheetml.x2006.main.CTWorkbook
        at org.openxmlformats.schemas.spreadsheetml.x2006.main.CTWorkbook$Factory.newInstance(Unknown Source)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.onWorkbookCreate(XSSFWorkbook.java:460)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:263)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:257)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:245)
        at POITest.test.ApachePOIExcelWrite.main(ApachePOIExcelWrite.java:21)

**Comment by jramirez-isc** [comment]
@mohitochani, the error message seems very general and unrelated to `native-image`. Can you please share the code/steps to replicate the error? How are you generating the native image?

**Comment by yrostov** [comment]
Hi,

I am getting the same exception naively compiling Excel generation POI code. Below is relevant source code. Exception starts in constructor and ends in static newInstance method, which by looks of it, does run - time loading.

Code
`import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

Workbook workbook = new XSSFWorkbook();
`

POM
`		<dependency>
		  <groupId>org.apache.poi</groupId>
		  <artifactId>poi-ooxml</artifactId>
		  <version>4.1.2</version>
		</dependency>
`

**Comment by jramirez-isc** [comment]
@yrostov Can you explain what the `mvn package -Pnative` command does? 
I've seen it when using Quarkus, but I want to confirm.
