### ISSUE TITLE
NPE when running async code in parallel in contexts sharing engine

### ISSUE THREAD

**Issue by zolstein** [oracle/graal#1942]
I can't tell if I've run into a bug or I've used Graal inappropriately.

I work with a system that creates many contexts for running pieces of javascript and python, sometimes concurrently. We found that creating contexts for python took too long, but that we could make this much faster by sharing a single Engine between all contexts. (Probably this will help in other ways, too.) However, this causes problems when executing multiple pieces of code in parallel. In particular, when we run multiple async javascript functions in parallel we get an NPE executing the AsyncFunctionRootNode. I constructed a minimal test that exercises this issue.

```java
@Test
public void testMultiThreadedExecution() throws InterruptedException {
  // Test passes if using non-async function, e.g (() => { return 1 })
  Source code = Source.create("js", "(async () => { return 1 })");
  Engine engine = Engine.create();
  List<Thread> threads = new ArrayList<>();
  for (int i = 0; i < 10; i++) {
    // Test passes if contexts do not share the same engine.
    Context context = Context.newBuilder().engine(engine).build();
    Runnable runCode = () -> System.out.println(context.eval(code).execute());
    threads.add(new Thread(runCode));
  }
  AtomicBoolean failure = new AtomicBoolean(false);
  for (Thread thread : threads) {
    thread.setUncaughtExceptionHandler(
        (t, e) -> {
          e.printStackTrace();
          failure.set(true);
        });
    // Test passes if threads run in series, rather than in parallel.
    thread.start();
  }
  for (Thread thread : threads) {
    thread.join();
  }
  assert !failure.get();
}
```
This test produces (10 of) the following stack trace:
```
org.graalvm.polyglot.PolyglotException: java.lang.NullPointerException
	at com.oracle.truffle.js.nodes.control.AsyncFunctionBodyNode$AsyncFunctionRootNode.execute(AsyncFunctionBodyNode.java:93)
	at <js> null(Unknown)
	at <js> :=>(Unnamed:1:1-24)
	at org.graalvm.polyglot.Value.execute(Value.java:364)
	at execution.table.MultiThreadedTest.lambda$testMultiThreadedExecution$0(MultiThreadedTest.java:24)
	at java.lang.Thread.run(Thread.java:748)
Original Internal Error: 
java.lang.NullPointerException
	at com.oracle.truffle.js.nodes.control.AsyncFunctionBodyNode$AsyncFunctionRootNode.execute(AsyncFunctionBodyNode.java:93)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:327)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:317)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:304)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:286)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:241)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:63)
	at com.oracle.truffle.js.nodes.control.AsyncFunctionBodyNode.asyncFunctionStart(AsyncFunctionBodyNode.java:173)
	at com.oracle.truffle.js.nodes.control.AsyncFunctionBodyNode.execute(AsyncFunctionBodyNode.java:181)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:147)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:93)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:327)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:317)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:304)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:286)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:241)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:63)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$UnboundJSFunctionCacheNode.executeCall(JSFunctionCallNode.java:1250)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:291)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:237)
	at com.oracle.truffle.js.nodes.interop.JSInteropExecuteNode.doDefault(JSInteropExecuteNode.java:72)
	at com.oracle.truffle.js.nodes.interop.JSInteropExecuteNodeGen.executeAndSpecialize(JSInteropExecuteNodeGen.java:63)
	at com.oracle.truffle.js.nodes.interop.JSInteropExecuteNodeGen.execute(JSInteropExecuteNodeGen.java:46)
	at com.oracle.truffle.js.runtime.builtins.JSClass.execute(JSClass.java:690)
	at com.oracle.truffle.js.runtime.builtins.JSClassGen$InteropLibraryExports$Cached.executeNode_AndSpecialize(JSClassGen.java:762)
	at com.oracle.truffle.js.runtime.builtins.JSClassGen$InteropLibraryExports$Cached.execute(JSClassGen.java:738)
	at com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.execute(InteropLibraryGen.java:3045)
	at com.oracle.truffle.polyglot.PolyglotValue$InteropCodeCache$AbstractExecuteNode.executeShared(PolyglotValue.java:1679)
	at com.oracle.truffle.polyglot.PolyglotValue$InteropCodeCache$ExecuteNoArgsNode.executeImpl(PolyglotValue.java:1786)
	at com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:94)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:327)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:317)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:304)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:286)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget$OptimizedCallProfiled.call(OptimizedCallTarget.java:873)
	at com.oracle.truffle.polyglot.PolyglotValue$InteropValue.execute(PolyglotValue.java:2392)
	at org.graalvm.polyglot.Value.execute(Value.java:364)
	at execution.table.MultiThreadedTest.lambda$testMultiThreadedExecution$0(MultiThreadedTest.java:24)
	at java.lang.Thread.run(Thread.java:748)
Caused by: Attached Guest Language Frames (3)
```

I've tested this using GraalVM 19.2.0 and 19.3.0; I believe some older versions exhibit the same behavior, but I haven't personally tested them. From reading the docs, it seems like both sharing engines between contexts and running multiple contexts concurrently should work fine. 

If this _shouldn't_ work, can you help me understand why, and hopefully provide some other suggestions for how to create python contexts more quickly?

In any case, I'll provide any more information you need.

**Comment by eleinadani** [comment]
Hi @zolstein, thanks for the report. This looks like a bug in the Graal JavaScript runtime. We will investigate. 

ps. other JavaScript-related issues for GraalVM can be reported here: https://github.com/graalvm/graaljs/issues

**Comment by zolstein** [comment]
Ah. I didn't realize you tracked graaljs separately from graalvm. Should I re-report the issue over there?

How would I determine that a bug like this exists specifically in the JS runtime rather than somewhere that would affect other languages. (I ask partly because since filing this I've found a very similar-looking problem when executing python code in this way. Should I file that separately with graalpython, or add it to this report? Maybe both?)
