### ISSUE TITLE
[native-image] crashes "Undefined symbols for architecture x86_64" _JVM_GetSystemPackage(s)

### ISSUE THREAD

**Issue by aclement** [oracle/graal#1946]
Self built graal on #5a9edeb3ef07c (Java8 base).  Trying to build my springmvc-tomcat sample. This seems a vague follow on from #1920 perhaps, as in more symbols not accessible.
```
[tc:36957]        write:   1,468.42 ms
Fatal error: java.lang.RuntimeException: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1

Linker command executed:
cc -v -o /Users/aclement/gits/spring-graal-native/spring-graal-native-samples/springmvc-tomcat/unpack/BOOT-INF/classes/tc -Wl,-no_compact_unwind -Wl,-exported_symbols_list -Wl,/var/folders/tg/klfmdszs2z129xkyrpyzlfyc0000gn/T/SVM-1765668139593105917/exported_symbols.list -Wl,-x -arch x86_64 -L/var/folders/tg/klfmdszs2z129xkyrpyzlfyc0000gn/T/SVM-1765668139593105917 -L/Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib -L/Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/svm/clibraries/darwin-amd64 /var/folders/tg/klfmdszs2z129xkyrpyzlfyc0000gn/T/SVM-1765668139593105917/tc.o /Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libffi.a /Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/liblibchelper.a /Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/liblibchelper.a /Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/liblibchelper.a /Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libjvm.a /Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libstrictmath.a /Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/libnet.a /Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/libjava.a /Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/libzip.a /Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/libnio.a /Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/libsunec.a /Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/libsunec.a -Wl,-framework,CoreFoundation -lpthread -lpthread -ldl -lz -lstdc++

Linker command ouput:
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
 "/Library/Developer/CommandLineTools/usr/bin/ld" -demangle -lto_library /Library/Developer/CommandLineTools/usr/lib/libLTO.dylib -dynamic -arch x86_64 -macosx_version_min 10.14.0 -o /Users/aclement/gits/spring-graal-native/spring-graal-native-samples/springmvc-tomcat/unpack/BOOT-INF/classes/tc -L/var/folders/tg/klfmdszs2z129xkyrpyzlfyc0000gn/T/SVM-1765668139593105917 -L/Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib -L/Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/svm/clibraries/darwin-amd64 -no_compact_unwind -exported_symbols_list /var/folders/tg/klfmdszs2z129xkyrpyzlfyc0000gn/T/SVM-1765668139593105917/exported_symbols.list -x /var/folders/tg/klfmdszs2z129xkyrpyzlfyc0000gn/T/SVM-1765668139593105917/tc.o /Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libffi.a /Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/liblibchelper.a /Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/liblibchelper.a /Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/liblibchelper.a /Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libjvm.a /Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libstrictmath.a /Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/libnet.a /Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/libjava.a /Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/libzip.a /Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/libnio.a /Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/libsunec.a /Users/aclement/gits/8/graal/sdk/mxbuild/darwin-amd64/GRAALVM_UNKNOWN_JAVA8/graalvm-unknown-java8-20.0.0-dev/Contents/Home/jre/lib/libsunec.a -framework CoreFoundation -lpthread -lpthread -ldl -lz -lc++ -lSystem /Library/Developer/CommandLineTools/usr/lib/clang/10.0.1/lib/darwin/libclang_rt.osx.a
Undefined symbols for architecture x86_64:
  "_JVM_GetSystemPackage", referenced from:
      _Java_java_lang_Package_getSystemPackage0 in libjava.a(Package.o)
  "_JVM_GetSystemPackages", referenced from:
      _Java_java_lang_Package_getSystemPackages0 in libjava.a(Package.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
```

**Comment by eginez** [comment]
This is issue is now fixed in head of master by commit https://github.com/oracle/graal/commit/cfef71c13cab78d5fafeaed20ef0828e83503bc1
