### ISSUE TITLE
[native-image] intermittent failure which compiling app, internal static field changed during image gen

### ISSUE THREAD

**Issue by aclement** [oracle/graal#1953]
```

Fatal error: com.oracle.svm.core.util.VMError$HostedError: com.oracle.svm.core.util.UserError$UserException: Static field or an object referenced from a static field changed during native image generation?
  object:sun.security.provider.DigestBase=java.lang.Object@5cfe32fe  of class: java.util.concurrent.ConcurrentHashMap$Node
  reachable through:
    object: com.oracle.svm.core.deopt.DeoptimizedFrame$ConstantEntry=java.lang.Object@30d4a40c  of class: java.util.concurrent.ConcurrentHashMap$Node
    object: [Ljava.util.concurrent.ConcurrentHashMap$Node;@6ab36bbe  of class: java.util.concurrent.ConcurrentHashMap$Node[]
object: {com.oracle.svm.core.graal.code.SubstrateCallingConvention=java.lang.Object@672e9895, org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroupMember=java.lang.Object@42e07b35, com.oracle.svm.hosted.classinitialization.InitializationNode=java.lang.Object@74730763, com.oracle.svm.hosted.FeatureImpl$AfterCompilationAccessImpl=java.lang.Object@6a8ea8ac, com.sun.org.apache.xml.internal.security.transforms.implementations.TransformC14N11=java.lang.Object@5c8bc521, com.oracle.svm.core.configure.ResourcesRegistry=java.lang.Object@15550fc1, org.springframework.scripting.config.LangNamespaceHandler=java.lang.Object@5febf111, ch.qos.logback.classic.db.names.ColumnName=java.lang.Object@1d45b6e2, org.graalvm.compiler.replacements.StandardGraphBuilderPlugins$StringIndexOfConstantPlugin=TRIMMED THE REST OF THIS LINE>
   object: jdk.internal.loader.ClassLoaders$PlatformClassLoader@2492a5f9  of class: jdk.internal.loader.ClassLoaders$PlatformClassLoader
    root: java.util.ResourceBundle.loadBundle(ResourceBundle$CacheKey, List, ResourceBundle$Control, boolean)

        at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:70)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:648)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:452)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

This isn't happening every time. Repro instructions:
```
git clone https://github.com/spring-projects-experimental/spring-graal-native
cd spring-graal-native/spring-graal-native-feature
git checkout upgrade_19_3
mvn clean package
cd ../spring-graal-native-samples/commandlinerunner
Run compile.sh a few times
```
this is mac (pre catalina) with dev build of graal (commit #5a9edeb3ef) on Java 11 base.

**Comment by eginez** [comment]
I believe this has been address and the above repro case does not show the problem anymore.
