### ISSUE TITLE
[native-image] com.oracle.svm.core.jdk.UnsupportedFeatureError for sun.text.spi.JavaTimeDateTimePatternProvider

### ISSUE THREAD

**Issue by maxum2610** [oracle/graal#1955]
LocalDate.format gives UnsupportedFeatureError for sun.text.spi.JavaTimeDateTimePatternProvider.

 LocaleServiceProviderAdapter.getAdapter:  providerClass: sun.text.spi.JavaTimeDateTimePatternProvider
[Fri Dec 06 19:16:23 CET 2019][INFO] [SUB] com.oracle.svm.core.jdk.UnsupportedFeatureError: LocaleServiceProviderAdapter.getAdapter:  providerClass: sun.text.spi.JavaTimeDateTimePatternProvider
[Fri Dec 06 19:16:23 CET 2019][INFO] [SUB] 	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:102)
[Fri Dec 06 19:16:23 CET 2019][INFO] [SUB] 	at sun.util.locale.provider.LocaleProviderAdapter.getAdapter(LocaleProviderAdapter.java:51)
[Fri Dec 06 19:16:23 CET 2019][INFO] [SUB] 	at java.time.format.DateTimeFormatterBuilder.getLocalizedDateTimePattern(DateTimeFormatterBuilder.java:221)
[Fri Dec 06 19:16:23 CET 2019][INFO] [SUB] 	at java.time.format.DateTimeFormatterBuilder$LocalizedPrinterParser.formatter(DateTimeFormatterBuilder.java:4769)
[Fri Dec 06 19:16:23 CET 2019][INFO] [SUB] 	at java.time.format.DateTimeFormatterBuilder$LocalizedPrinterParser.format(DateTimeFormatterBuilder.java:4745)
[Fri Dec 06 19:16:23 CET 2019][INFO] [SUB] 	at java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2335)
[Fri Dec 06 19:16:23 CET 2019][INFO] [SUB] 	at java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1843)
[Fri Dec 06 19:16:23 CET 2019][INFO] [SUB] 	at java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1817)
[Fri Dec 06 19:16:23 CET 2019][INFO] [SUB] 	at java.time.LocalDate.format(LocalDate.java:1816)

Possible cause:  sun.text.spi.JavaTimeDateTimePatternProvider is not included in the spiClasses() list in LocalSubstitutions.java

**Comment by eginez** [comment]
Hi @maxum2610 would you be able to provide a way to reproduce this failure?

**Comment by maxum2610** [comment]
Hi @eginez see attached zip with test program.

I ran the test directly for DateTimeFormatterBuilder.getLocalizedDateTimePattern using a Locale other than the default one (not sure if this is important).

[Sat Dec 14 14:42:02 CET 2019][FINE] ==================== RUN TASK ====================
Hello, JAVA main, argc = 1, argv = 0x7ffeec67e0b8
2019-12-14 14:42:03.041 hellofxml[14400:397137] Starting Gluon VM...
TESTING BUG #1955 START
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:479)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: LocaleProviderAdapter.getAdapter:  providerClass: sun.text.spi.JavaTimeDateTimePatternProvider
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:101)
	at sun.util.locale.provider.LocaleProviderAdapter.getAdapter(LocaleProviderAdapter.java:99)
	at java.time.format.DateTimeFormatterBuilder.getLocalizedDateTimePattern(DateTimeFormatterBuilder.java:221)
	at hellofx.HelloFXML.start(HelloFXML.java:58)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.security.AccessController.doPrivileged(AccessController.java:98)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_lang_Runnable_2_0002erun_00028_00029V(JNIJavaCallWrappers.java:0)

From what I can ascertain, the probable cause is that  sun.text.spi.JavaTimeDateTimePatternProvider is not included in the spiClasses() list in LocalSubstitutions.java

use: "mvn clean client:build -X"  to build and "mvn client:run -X" to run.
  
[HelloFXML.zip](https://github.com/oracle/graal/files/3963885/HelloFXML.zip)

**Comment by eginez** [comment]
fixed by https://github.com/oracle/graal/commit/a19c060f457b6bdf95fcca1f1ed512e41a22d447
