### ISSUE TITLE
Accessing deleted fields via reflection causes an incomprehensible error

### ISSUE THREAD

**Issue by vjovanov** [oracle/graal#1980]
Accessing deleted fields via reflection causes an incomprehensible error message. For the code snippet:
```
lass Holder {
    public String getName() {
        return "Holder@" + System.identityHashCode(this);
    }
}
@TargetClass(Holder.class)
final class Target_com_oracle_svm_enterprise_test_core_Holder {
    @Delete
    public native String getName();
}
class HolderReflectionAccess {
    private static final Method getNameMethod;
    static {
        Method nameMethod = null;
        try {
            nameMethod = Holder.class.getMethod("getName");
        } catch (ReflectiveOperationException | IllegalArgumentException e) {
            // Should never happen
            throw VMError.shouldNotReachHere(e);
        }
        getNameMethod = nameMethod;
    }
    @SuppressWarnings("static-method")
    public String getName(Holder type) {
        try {
            Object name = getNameMethod.invoke(type);
            return (String) name;
        } catch (ReflectiveOperationException e) {
            return "no-name";
        }
    }
}
public class ReflectionOnDeltedMethodTest {
    @SVMTest
    public void test01() {
        HolderReflectionAccess access = new HolderReflectionAccess();
        Holder holder = new Holder();
        String className = access.getName(holder);
        Assert.assertTrue("Holder name should be with `no-name`.", className.startsWith("no-name"));
    }
}```

We get the following error:
```
com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.oracle.svm.reflect.Holder_getName_68b5e270d66184b786a0b29915e2c66b80a29984.invoke(java.lang.Object, java.lang.Object[]) 
Parsing context:
	parsing java.lang.reflect.Method.invoke(Method.java:498)
	parsing com.oracle.svm.enterprise.test.core.HolderReflectionAccess.getName(ReflectionOnDeltedMethodTest.java:55)
	parsing com.oracle.svm.enterprise.test.core.ReflectionOnDeltedMethodTest.test01(ReflectionOnDeltedMethodTest.java:81)
	parsing com.oracle.svm.core.code.IsolateEnterStub.ReflectionOnDeltedMethodTest_test01_8f61ff128f8fd9701c06798157a71d4ae5a4f148(generated:0)
	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:327)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:191)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:344)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:386)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:511)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$0(CompletionExecutor.java:171)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method com.oracle.svm.enterprise.test.core.Holder.getName() is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.lookup(AnnotationSubstitutionProcessor.java:183)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:397)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:377)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:1)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaMethod(UniverseMetaAccess.java:93)
	at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaMethod(AnalysisMetaAccess.java:66)
	at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaMethod(AnalysisMetaAccess.java:1)
	at com.oracle.svm.reflect.hosted.ReflectionSubstitutionType$ReflectiveInvokeMethod.buildGraph(ReflectionSubstitutionType.java:511)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.buildGraph(AnalysisMethod.java:319)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:185)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:340)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	... 12 more
```

**Comment by cstancu** [comment]
If you follow the suggestion in the error message and you run with `--report-unsupported-elements-at-runtime` then the behavior is the expected one: the call to `getNameMethod.invoke(type)` will throw an `java.lang.reflect.InvocationTargetException` whose cause is an `com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported method com.oracle.svm.enterprise.test.core.Holder.getName()` is reachable. The `InvocationTargetException` is caught and the test passes. So I think that the **reflection intrinsification mechanism is behaving as expected in the presence of deleted methods**.
