### ISSUE TITLE
Mongonaut does not work on macOS

### ISSUE THREAD

**Issue by vjovanov** [oracle/graal#1983]
The native-image from 

 https://github.com/dekstroza/mongonaut

builds fine but at execution there is an exception during socket creation:
```
$ ./mongonaut
13:24:01.429 [main] DEBUG io.jaegertracing.Configuration - Found a Metrics Factory service: class io.jaegertracing.micrometer.MicrometerMetricsFactory
13:24:01.430 [main] DEBUG i.j.t.i.senders.ThriftSenderFactory - Using the UDP Sender to send spans to the agent.
13:24:01.432 [main] DEBUG i.j.internal.senders.SenderResolver - Using sender UdpSender()
13:24:01.459 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 80ms. Server Running: http://localhost:8080
13:24:11.424 [nioEventLoopGroup-2-2] INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
13:24:11.433 [cluster-ClusterId{value='5df2316bb02edf0fa0184e76', description='null'}-localhost:27017] INFO  org.mongodb.driver.cluster - Exception in monitor thread while connecting to server localhost:27017
com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$OpenCompletionHandler.failed(AsynchronousSocketChannelStream.java:117)
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:128)
	at sun.nio.ch.Invoker$2.run(Invoker.java:218)
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: java.net.ConnectException: Connection refused
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_net_ConnectException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(UnixAsynchronousSocketChannelImpl.java)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:252)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:198)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
	at sun.nio.ch.KQueuePort$EventHandlerTask.run(KQueuePort.java:301)
	... 3 common frames omitted
```

This is caused by the move to JNI.

**Comment by vjovanov** [comment]
This was a configuration issue.
