### ISSUE TITLE
Problem with OkHttp & Charsets

### ISSUE THREAD

**Issue by nfrankel** [oracle/graal#1997]
I'm trying to use GraalVM native-image to make a native executable out of a JAR.

The JAR depends on `io.fabric8:kubernetes-client` which depends on `com.squareup.okhttp3:okhttp`. This is a sample of the `okhttp3.internal.Util`:

```
public final class Util {
  public static final Charset UTF_8 = Charset.forName("UTF-8");
  public static final Charset ISO_8859_1 = Charset.forName("ISO-8859-1");
  private static final Charset UTF_16_BE = Charset.forName("UTF-16BE");
  private static final Charset UTF_16_LE = Charset.forName("UTF-16LE");
  private static final Charset UTF_32_BE = Charset.forName("UTF-32BE");
  private static final Charset UTF_32_LE = Charset.forName("UTF-32LE");
  ...
}
```

This is my `Dockerfile`:

```
FROM oracle/graalvm-ce:19.2.1 as build
COPY target/jvm-operator-1.9.jar /var/jvm-operator-1.9.jar
COPY config /var/config
WORKDIR /opt/graalvm
RUN gu install native-image \
 && native-image -jar /var/jvm-operator-1.9.jar \
   -H:ConfigurationFileDirectories=/var/config \
   -H:+AddAllCharsets \
   -H:+ReportExceptionStackTraces \
 && mv jvm-operator-1.9 /var/jvm-operator-1.9

FROM bitnami:minideb/buster
COPY --from=build /var/jvm-operator-1.9 operator
CMD ./operator
```

At runtime, I still have this stack when scheduling:

```
Caused by: java.nio.charset.UnsupportedCharsetException: UTF-32BE
	at java.nio.charset.Charset.forName(Charset.java:531)
	at okhttp3.internal.Util.<clinit>(Util.java:75)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
```

Notice the `H:+AddAllCharsets` flag. I don't understand why it doesn't work.

**Comment by eginez** [comment]
@nfrankel Is there a place I can download the code you have and reproduce your bug

**Comment by nfrankel** [comment]
Hello @eginez 

> Is there a place I can download the code you have and reproduce your bug.

Yes, there is. Please check https://github.com/nfrankel/jvm-controller/
The issue happens just before [this commit](https://github.com/nfrankel/jvm-controller/commit/0dc0cc6469a16d42234b3739df964d354d54b893). In this commit, I'm using a patched version of OkHttp.

> Have you by any chance had a look at running your code on the latest version of graal?

Nope, I didn't. But I waited 3 months to get an answer 😅

**Comment by nfrankel** [comment]
Just noticed Graal VM 20.0 got released. Will try when I have time.

**Comment by eginez** [comment]
Sounds good for the record I was just able to build the project above with the tip of master
```
native-image -H:+AddAllCharsets -jar target/jvm-operator-1.10.jar
OpenJDK 64-Bit Server VM warning: -XX:ThreadPriorityPolicy=1 may require system level permission, e.g., being the root user. If the necessary permission is not possessed, changes to priority will be silently ignored.
Warning: Ignoring server-mode native-image argument --no-server.
OpenJDK 64-Bit Server VM warning: -XX:ThreadPriorityPolicy=1 may require system level permission, e.g., being the root user. If the necessary permission is not possessed, changes to priority will be silently ignored.
[jvm-operator-1.10:3385]    classlist:   3,414.09 ms,  1.00 GB
[jvm-operator-1.10:3385]        (cap):   1,542.44 ms,  1.00 GB
[jvm-operator-1.10:3385]        setup:   2,769.25 ms,  1.00 GB
[jvm-operator-1.10:3385]   (typeflow):  23,181.76 ms,  3.00 GB
[jvm-operator-1.10:3385]    (objects):  25,203.18 ms,  3.00 GB
[jvm-operator-1.10:3385]   (features):   2,378.31 ms,  3.00 GB
[jvm-operator-1.10:3385]     analysis:  53,454.65 ms,  3.00 GB
[jvm-operator-1.10:3385]     (clinit):   1,156.06 ms,  3.00 GB
[jvm-operator-1.10:3385]     universe:   3,322.35 ms,  3.00 GB
[jvm-operator-1.10:3385]      (parse):   7,433.76 ms,  3.00 GB
[jvm-operator-1.10:3385]     (inline):   4,096.04 ms,  3.00 GB
[jvm-operator-1.10:3385]    (compile):  24,465.56 ms,  3.00 GB
[jvm-operator-1.10:3385]      compile:  39,067.75 ms,  3.00 GB
[jvm-operator-1.10:3385]        image:   7,120.01 ms,  3.00 GB
[jvm-operator-1.10:3385]        write:   1,134.61 ms,  3.00 GB
[jvm-operator-1.10:3385]      [total]: 110,597.45 ms,  3.00 GB
```

This built with  vanila okhttp: `org.squareup.okhttp3:okhttp:3.12.6`

**Comment by nfrankel** [comment]
Can you try without the `-H:+AddAllCharsets` and show it fails please?

**Comment by eginez** [comment]
Gladly
With `-H:+AddAllCharsets`
```
[main] INFO ch.frankel.kubernetes.extend.Sidecar - *** JVM Operator v1.10 ***
[main] WARN io.fabric8.kubernetes.client.Config - Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[OkHttp https://kubernetes.default.svc/...] WARN io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager - Exec Failure
java.net.UnknownHostException: kubernetes.default.svc: nodename nor servname provided, or not known
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_net_UnknownHostException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java)
	at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515)
	at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1505)
	at java.net.InetAddress.getAllByName(InetAddress.java:1364)
	at java.net.InetAddress.getAllByName(InetAddress.java:1298)
	at okhttp3.Dns$1.lookup(Dns.java:40)
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:215)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:119)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createHttpClient$3(HttpClientUtils.java:113)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failed to start websocket
```

Without charsets flag
```
[main] INFO ch.frankel.kubernetes.extend.Sidecar - *** JVM Operator v1.10 ***
[main] WARN io.fabric8.kubernetes.client.Config - Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:290)
	at java.lang.Class.ensureInitialized(DynamicHub.java:496)
	at okhttp3.OkHttpClient.<clinit>(OkHttpClient.java:127)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	at java.lang.Class.ensureInitialized(DynamicHub.java:496)
	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:475)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:73)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:64)
	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:51)
	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:43)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:89)
	at ch.frankel.kubernetes.extend.Sidecar.main(Sidecar.java:13)
Caused by: java.nio.charset.UnsupportedCharsetException: UTF-32BE
	at java.nio.charset.Charset.forName(Charset.java:529)
	at okhttp3.internal.Util.<clinit>(Util.java:75)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	... 12 more
```

**Comment by nfrankel** [comment]
Thanks!
