### ISSUE TITLE
[native-image] Should sun.security.util.Resources be auto-included in the native image?

### ISSUE THREAD

**Issue by gwenneg** [oracle/graal#2005]
Hi GraalVM team!

The following exception it thrown in Quarkus during one of our integration tests execution with JDK 11 only (the test ends successfully with JDK 8):

```
r_ed18b755467e1c5fdc8a90c62127a21080a24841_Bean.get(InfinispanEmbeddedProducer_ProducerMethod_manager_ed18b755467e1c5fdc8a90c62127a21080a24841_Bean.zig:43)
	at io.quarkus.infinispan.embedded.runtime.InfinispanEmbeddedProducer_ProducerMethod_manager_ed18b755467e1c5fdc8a90c62127a21080a24841_Bean.get(InfinispanEmbeddedProducer_ProducerMethod_manager_ed18b755467e1c5fdc8a90c62127a21080a24841_Bean.zig:343)
	at io.quarkus.it.infinispan.embedded.TestServlet_Bean.create(TestServlet_Bean.zig:263)
	... 19 more
Caused by: org.infinispan.commons.CacheConfigurationException: Error starting component org.infinispan.xsite.BackupReceiverRepository
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:555)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:770)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:605)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:569)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:547)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:770)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:605)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:569)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:547)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:770)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:605)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:569)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:547)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:770)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:605)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:569)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:547)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:770)
	at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:344)
	at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:240)
	at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:741)
	... 32 more
Caused by: java.util.MissingResourceException: Resource bundle not found sun.security.util.Resources. Register the resource bundle using the option -H:IncludeResourceBundles=sun.security.util.Resources.
	at com.oracle.svm.core.jdk.LocalizationSupport.getCached(LocalizationSupport.java:66)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:53)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at sun.security.util.ResourcesMgr.getBundle(ResourcesMgr.java:54)
	at sun.security.util.ResourcesMgr.getString(ResourcesMgr.java:40)
	at javax.security.auth.Subject.getSubject(Subject.java:292)
	at org.infinispan.security.Security.getSubject(Security.java:147)
	at org.infinispan.notifications.impl.AbstractListenerImpl.validateAndAddListenerInvocations(AbstractListenerImpl.java:215)
	at org.infinispan.notifications.cachemanagerlistener.CacheManagerNotifierImpl.addListenerAsync(CacheManagerNotifierImpl.java:172)
	at org.infinispan.notifications.Listenable.addListener(Listenable.java:26)
	at org.infinispan.xsite.BackupReceiverRepositoryImpl.start(BackupReceiverRepositoryImpl.java:41)
	at org.infinispan.xsite.CorePackageImpl$1.start(CorePackageImpl.java:39)
	at org.infinispan.xsite.CorePackageImpl$1.start(CorePackageImpl.java:31)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:587)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:578)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:547)
	... 57 more
```

It's an easy one to fix using `-H:IncludeResourceBundles` or `com.oracle.svm.core.jdk.LocalizationFeature`. But when I submitted the Quarkus PR, @jaikiran asked an interesting question:

> Looking at the stacktrace in the linked issue, it's coming from within a JRE internal class ('sun.security.util.ResourceMgr') so I think the resource bundle for such usages should be auto included by substratevm itself (ofcourse if that class is considered reachable).

What do you think about it? Should `sun.security.util.Resources` be auto-included in the native image?

**Comment by vjovanov** [comment]
I would say that if we can determine in analysis when this resource will be needed we should include it automatically. Otherwise, it would bloat the image necessary if this feature is not used. 

I believe we can find this out by checking if method `sun.security.util.ResourcesMgr#getString` can be ever invoked. We should then do the same thing for `sun.security.util.ResourcesMgr#getAuthResourceString`. @cstancu what is your take on this?
