### ISSUE TITLE
Unexpected exception during JVMCI compiler initialization

### ISSUE THREAD

**Issue by plokhotnyuk** [oracle/graal#2013]
It happened 3 times during run of the set about 1K JMH benchmarks with forking each as a separated process:
```
[info] Exception during JVMCI compiler initialization:
[info] Exception in thread "JVMCI-native CompilerThread0": java.lang.ExceptionInInitializerError
[info] java.lang.ExceptionInInitializerError
[info] 	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:290)
[info] 	at java.lang.Class.ensureInitialized(DynamicHub.java:475)
[info] 	at java.lang.System.getenv(System.java:897)
[info] 	at org.graalvm.libgraal.jni.JNIUtil.traceLevel(JNIUtil.java:268)
[info] 	at org.graalvm.libgraal.jni.JNIUtil.trace(JNIUtil.java:292)
[info] 	at org.graalvm.libgraal.jni.HotSpotToSVMScope.<init>(HotSpotToSVMScope.java:114)
[info] 	at org.graalvm.compiler.hotspot.management.libgraal.HotSpotGraalManagement.defineClassesInHotSpot(HotSpotGraalManagement.java:170)
[info] 	at org.graalvm.compiler.hotspot.management.libgraal.HotSpotGraalManagement.initialize(HotSpotGraalManagement.java:115)
[info] 	at org.graalvm.compiler.hotspot.HotSpotGraalRuntime.<init>(HotSpotGraalRuntime.java:178)
[info] 	at org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:156)
[info] 	at org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:134)
[info] 	at org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:52)
[info] 	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.getCompiler(HotSpotJVMCIRuntime.java:599)
[info] 	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:667)
[info] 	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST_Nonvirtual:Ljdk_vm_ci_hotspot_HotSpotJVMCIRuntime_2_0002ecompileMethod_00028Ljdk_vm_ci_hotspot_HotSpotResolvedJavaMethod_2IJI_00029Ljdk_vm_ci_hotspot_HotSpotCompilationRequestResult_2(JNIJavaCallWrappers.java:0)
[info] Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 51 out of bounds for length 50
[info] 	at com.oracle.svm.jni.functions.JNIFunctions.SetObjectArrayElement(JNIFunctions.java:671)
[info] 	at java.lang.ProcessEnvironment.environ(ProcessEnvironment.java)
[info] 	at java.lang.ProcessEnvironment.<clinit>(ProcessEnvironment.java:70)
[info] 	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
[info] 	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
[info] 	... 14 more
```
On the following environment:  Intel® Core™ i9-9880H CPU @ 2.3GHz (max 4.8GHz), RAM 16Gb DDR4-2400, macOS Mojave 10.14.6, and the latest version of GraalVM EE for Java8.
```
[info] # VM version: JDK 1.8.0_231, Java HotSpot(TM) 64-Bit GraalVM EE 19.3.0, 25.231-b11-jvmci-19.3-b05
[info] # VM invoker: /Library/Java/JavaVirtualMachines/graalvm-ee-java8-19.3.0/Contents/Home/jre/bin/java
[info] # VM options: -server -Xms2g -Xmx2g -XX:NewSize=1g -XX:MaxNewSize=1g -XX:InitialCodeCacheSize=512m -XX:ReservedCodeCacheSize=512m -XX:+UseParallelGC -XX:-UseAdaptiveSizePolicy -XX:MaxInlineLevel=18 -XX:-UseBiasedLocking -XX:+AlwaysPreTouch -XX:+UseNUMA -XX:-UseAdaptiveNUMAChunkSizing
```

**Comment by dougxc** [comment]
Are these JMH benchmarks running any code that modifies the environment? Seems like the `environ` variable is [not thread safe](http://www.club.cc.cmu.edu/~cmccabe/blog_the_setenv_fiasco.html). [Googling shows](https://www.google.com/search?q=ProcessEnvironment.%3Cclinit%3E+ArrayIndexOutOfBoundsException) that this sporadically happens to other Java programs.

**Comment by cstancu** [comment]
@plokhotnyuk as @dougxc investigation suggests this doesn't seem to be a GraalVM specific issue. Were you able to replicate this in a different environment as well?

**Comment by plokhotnyuk** [comment]
@cstancu @dougxc thank you for your investigation and support!

I'm closing it as not related to GraalVM
