### ISSUE TITLE
Cannot set JVMCIPermission via policy file in graalvm-ce-java11-19.3.0

### ISSUE THREAD

**Issue by tporeba** [oracle/graal#2053]
Application that run just file on GraalVM 19.2.1, java8 release now fails on Graal 19.3.0, java11 because it cannot set necessary permission `jdk.vm.ci.services.JVMCIPermission` via policy file.

It looks like it is caused by the module system. 

I get this on stderr while policy file is being parsed:
> java.security.policy: error adding Permission, jdk.vm.ci.services.JVMCIPermission:
	java.lang.IllegalAccessException: class sun.security.provider.PolicyFile (in module java.base) cannot access class jdk.vm.ci.services.JVMCIPermission (in module jdk.internal.vm.ci) because module jdk.internal.vm.ci does not export jdk.vm.ci.services to module java.base

And then application fails because of missing JVMCIPermission - access denied error:

> Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.graalvm.truffle/com.oracle.truffle.api.TruffleOptions.<clinit>(TruffleOptions.java:130)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory$ResolvedDispatch.register(LibraryFactory.java:559)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryExport.register(LibraryExport.java:117)
	at org.graalvm.truffle/com.oracle.truffle.api.library.DynamicDispatchLibraryGen.<clinit>(DynamicDispatchLibrary.java:183)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.loadGeneratedClass(LibraryFactory.java:437)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.resolveImpl(LibraryFactory.java:418)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.resolve(LibraryFactory.java:411)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.<init>(LibraryFactory.java:162)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen.<init>(InteropLibraryGen.java:228)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen.<clinit>(InteropLibraryGen.java:212)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.loadGeneratedClass(LibraryFactory.java:437)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.resolveImpl(LibraryFactory.java:418)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.resolve(LibraryFactory.java:411)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibrary.<clinit>(InteropLibrary.java:1204)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValue.<clinit>(PolyglotValue.java:120)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotImpl.initialize(PolyglotImpl.java:114)
	at org.graalvm.sdk/org.graalvm.polyglot.impl.AbstractPolyglotImpl.setConstructors(AbstractPolyglotImpl.java:209)
	at org.graalvm.sdk/org.graalvm.polyglot.Engine$1.run(Engine.java:700)
	at org.graalvm.sdk/org.graalvm.polyglot.Engine$1.run(Engine.java:668)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.graalvm.sdk/org.graalvm.polyglot.Engine.initEngineImpl(Engine.java:668)
	at org.graalvm.sdk/org.graalvm.polyglot.Engine.access$000(Engine.java:103)
	at org.graalvm.sdk/org.graalvm.polyglot.Engine$ImplHolder.<clinit>(Engine.java:112)
	at org.graalvm.sdk/org.graalvm.polyglot.Engine.getImpl(Engine.java:264)
	at org.graalvm.sdk/org.graalvm.polyglot.Engine$Builder.build(Engine.java:502)
	at org.graalvm.sdk/org.graalvm.polyglot.Context$Builder.build(Context.java:1444)
	at com.example.App.main(App.java:26)
Caused by: java.security.AccessControlException: access denied ("jdk.vm.ci.services.JVMCIPermission" "jvmci")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:897)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
	at jdk.internal.vm.ci/jdk.vm.ci.services.JVMCIServiceLocator.getProviders(JVMCIServiceLocator.java:104)
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCICompilerConfig.getJVMCICompilerFactories(HotSpotJVMCICompilerConfig.java:145)
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCICompilerConfig.getCompilerFactory(HotSpotJVMCICompilerConfig.java:93)
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.<init>(HotSpotJVMCIRuntime.java:468)
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.runtime(HotSpotJVMCIRuntime.java:172)
	at jdk.internal.vm.ci/jdk.vm.ci.runtime.JVMCI.initializeRuntime(Native Method)
	at jdk.internal.vm.ci/jdk.vm.ci.runtime.JVMCI.getRuntime(JVMCI.java:65)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.AbstractHotSpotTruffleRuntimeAccess.getRuntime(AbstractHotSpotTruffleRuntimeAccess.java:42)
	at org.graalvm.truffle/com.oracle.truffle.api.Truffle$1.run(Truffle.java:126)
	at org.graalvm.truffle/com.oracle.truffle.api.Truffle$1.run(Truffle.java:107)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.graalvm.truffle/com.oracle.truffle.api.Truffle.initRuntime(Truffle.java:107)
	at org.graalvm.truffle/com.oracle.truffle.api.Truffle.<clinit>(Truffle.java:62)
	... 31 more

My cmd line: 
> C:\Java\graalvm-ce-java11-19.3.0\bin\java.exe -Dpolyglot.js.nashorn-compat=true -Djava.security.debug=denied -Djava.security.manager -Djava.security.policy=test.policy com.example.App

test.policy file:

    grant  {
      //lots of permissions skipped for clarity
      ...
      permission jdk.vm.ci.services.JVMCIPermission;
    };

**Comment by dougxc** [comment]
@chumer what's the status of Polyglot applications and the SecurityManager?

**Comment by chumer** [comment]
Unfortunately enabling the security manager is currently not supported if you want to use the polyglot API for the Graal SDK. 

It is planned to be fixed, but I don't have an ETA.

**Comment by tporeba** [comment]
@chumer Is it unsupported for both JDK11 and JDK8? Should I expect any blocking issues down the road when if I use SecurityManager with graalvm-ce-java8-19.3.x ? 

I planned to migrate my production JSR223 application from Rhino/Nashorn to Graal.js, but removing SecurityManager is not an option. I must somehow restrict the permissions as the executed scripts are not considered safe.

**Comment by tporeba** [comment]
I had an idea for a workaround - writing my own subclass of `BasicPermission` that would override `implies`:

```Java
    @Override
    public boolean implies(Permission p) {
        if ("jdk.vm.ci.services.JVMCIPermission".equals(p.getClass().getCanonicalName())) {
            return true;
        }

        return super.implies(p);
    }
```

If this worked, then I could just replace all `JVMCIPermission` grants in policy file with my custom permission class and get the same fine-grained control as in JDK8.

Unfortunately this `JVMCIPermission` is needed very early on, when my custom permission is not yet loaded - it is visible as `java.security.UnresolvedPermission` at that time. I don't know how to force loading it that early.

Another idea would be using custom SecurityManager class and overriding `checkPermission` to do the same as above. But this have a downside that it grants `JVMCIPermission` globally.

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-20945.

**Comment by tporeba** [comment]
My previous workaround idea from comment above did not work, but it lead me to another one, that actually works:

1. Create a permission class:
```Java
package com.example;
public class ReplacementJVMCIPermission extends BasicPermission {

    public ReplacementJVMCIPermission() {
        super("jvmci");
    }
}
```
2. You need to use a custom SecurityManager, class via `-Djava.security.manager=com.example.YourSecurityManager`, then in that `YourSecurityManager` override checkPermission methods:
```Java
    @Override
    public void checkPermission(Permission perm) {
        perm = workaround(perm);
        super.checkPermission(perm);
    }

    @Override
    public void checkPermission(Permission perm, Object context) {
        perm = workaround(perm);
        super.checkPermission(perm, context);
    }

    private Permission workaround(Permission perm) {
        if ("jdk.vm.ci.services.JVMCIPermission".equals(perm.getClass().getCanonicalName())) {
            perm = new ReplacementJVMCIPermission();
        }
        return perm;
    }
```

3. Now you can just use `com.example.ReplacementJVMCIPermission` instead of `jdk.vm.ci.services.JVMCIPermission` in your policy file:
```Java
grant  {
  //lots of permissions skipped for clarity
  ...
  permission com.example.ReplacementJVMCIPermission;
};
```

You keep the fine-grained control, while avoiding the problem with Java11 module system.
Regards
Tomasz
