### ISSUE TITLE
[native-image] Crash with undefined symbol _Java_java_lang_Class_getEnclosingMethod0

### ISSUE THREAD

**Issue by aclement** [oracle/graal#2054]
Found this morning, graal built from commit 82874a531e2ac0d (today) with Java 11 base. Running the spring commandlinerunner sample - can provide full repro instructions if necessary:
```
Undefined symbols for architecture x86_64:
  "_Java_java_lang_Class_getEnclosingMethod0", referenced from:
      ___svm_version_info in commandlinerunner.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

	at com.oracle.svm.hosted.image.NativeBootImageViaCC.handleLinkerFailure(NativeBootImageViaCC.java:433)
	at com.oracle.svm.hosted.image.NativeBootImageViaCC.write(NativeBootImageViaCC.java:408)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:662)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:450)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by eginez** [comment]
fixed with https://github.com/oracle/graal/commit/2e38fa87b4842051ef532c926dad4c4cc8d539b7
