### ISSUE TITLE
Unsupported java.lang.Class.getConstantPool() is reachable from parseParameterAnnotations

### ISSUE THREAD

**Issue by ziyilin** [oracle/graal#2062]
I got the following complains:
```
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.Class.getConstantPool() is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Trace:
        at parsing java.lang.System$2.getConstantPool(System.java:1275)
Call path from entry point to java.lang.System$2.getConstantPool(Class):
        at java.lang.System$2.getConstantPool(System.java:1275)
        at java.lang.reflect.Executable.parseParameterAnnotations(Executable.java:83)
        at com.oracle.svm.reflect.Executable_parseParameterAnnotations_e04e8678cbe5147ec3ca5f53b872cc8ea631d03c_12307.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.xml.dtm.DTMException.printStackTrace(DTMException.java:350)
        at org.apache.xml.dtm.DTMException.printStackTrace(DTMException.java:286)
        at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:749)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
```
What is  this class?
> com.oracle.svm.reflect.Executable_parseParameterAnnotations_e04e8678cbe5147ec3ca5f53b872cc8ea631d03c_12307

How it is generated? If it is generated by Substrate VM, it should not call the unimplemented method.

**Comment by cstancu** [comment]
That's a method stub generated as a result of `Executable.parseParameterAnnotations()` being registered for reflection. Do you (or a framework you use) explicitly register this method for reflection? In normal execution `Executable.parseParameterAnnotations()` is never used in SVM, the only method that uses is `Executable.sharedGetParameterAnnotations()` is substituted with a custom implementation.

**Comment by ziyilin** [comment]
I see. We have configured all methods in Executable for reflection:
```
{
  "name":"java.lang.reflect.Executable",
  "allDeclaredMethods":true,
  "allPublicMethods":true
}
```

This could be the reason.

**Comment by cstancu** [comment]
Fixed by https://github.com/oracle/graal/commit/e922ede476ba5d99c826779ef5931648fd6150df.
