### ISSUE TITLE
substitution with this keyword

### ISSUE THREAD

**Issue by dufoli** [oracle/graal#2071]
I try to create an extention for cxf on quarkus project and I have an issue with substitution with this keyword.
I found no doc about such a case and it seems odd that "this" is treated as a field because I cannot substitute it.

dispatch function have the following signature
`public HttpServerExchange dispatch(HttpHandler handler)`

class UndertowHTTPHandler implements HttpHandler and I want to use this keyword in substitution.
but I get:

```
com.oracle.svm.core.util.UserError$UserException: One of @Delete, @Alias, or @Inject must be used: final io.quarkus.cxf.runtime.graal.Substitutions io.quarkus.cxf.runtime.graal.Substitutions$Substitute_UndertowHTTPDestination.this$0
	at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
	at com.oracle.svm.core.util.UserError.guarantee(UserError.java:86)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleFieldInAliasClass(AnnotationSubstitutionProcessor.java:356)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:304)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:274)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:230)
```

In order that this respect the interface, I have add implements HttpHandler. So this can be used.

Here is the substitution I use:

```
@TargetClass(className = "org.apache.cxf.transport.http_undertow.UndertowHTTPHandler")
    public final class Substitute_UndertowHTTPHandler implements HttpHandler {
        @Substitute
        public void handleRequest(HttpServerExchange undertowExchange) throws Exception {
            try {
                // perform blocking operation on exchange
                if (undertowExchange.isInIoThread()) {
                    undertowExchange.dispatch(this);
                    return;
                }
            }
        }
    }
}
```

**Comment by cstancu** [comment]
Using `this` is supported. HOwver, the error message seems to refer to another substitution class than the one in  the snippet that you pasted: `io.quarkus.cxf.runtime.graal.Substitutions$Substitute_UndertowHTTPDestination.this$0`.

**Comment by dufoli** [comment]
@TargetClass(className = "org.apache.cxf.transport.http_undertow.UndertowHTTPDestination")
    public final class Substitute_UndertowHTTPDestination {
        @Alias
        protected void doService(ServletContext context, HttpServletRequest req, HttpServletResponse resp) throws IOException {
        }
    }

**Comment by dufoli** [comment]
here is the full code of the substitution error I report:
https://github.com/quarkusio/quarkus/pull/5538/commits/9eea797a7da713beef33a867d0b2c41d2a955350

**Comment by cstancu** [comment]
`@Alias` methods should not have a body, just declare it `native` to make javac happy:
```
@TargetClass(className = "org.apache.cxf.transport.http_undertow.UndertowHTTPDestination")
public final class Substitute_UndertowHTTPDestination {
    @Alias
    protected native void doService(ServletContext context, HttpServletRequest req, HttpServletResponse resp);
}```

**Comment by dufoli** [comment]
OK thanks but how to solve the this issue of this.
making the substitution class inherite will work for interface but if I have an abstract class it is not possible.

example with 2 classes:
```
public class foo extend abstractFoo {
public void func() {
}
}
public class bar {
public void method(abstractFoo a) {
}
}
```

If I want to substitute foo.func to call bar.method(this).
How Do I proceed?
```
@TargetClass(className="foo")
public final class substitute_foo {
@substitute
public void func() {
bar b = new bar();
bar.method(this);
}
}
```

this can not compile because this is not abstractFoo.
I cannot extend substitution with AbstractFoo because it is not allowed.

**Comment by dufoli** [comment]
I have rerty with native but do not work:

```
    @TargetClass(className = "org.apache.cxf.transport.http_undertow.UndertowHTTPDestination")
    public final class Substitute_UndertowHTTPDestination {

        @Alias
        protected native void doService(ServletContext context, HttpServletRequest req, HttpServletResponse resp);

    }

    @TargetClass(className = "org.apache.cxf.transport.http_undertow.UndertowHTTPHandler")
    public final class Substitute_UndertowHTTPHandler implements HttpHandler {

        @Substitute
        public void handleRequest(HttpServerExchange undertowExchange) throws Exception {
            undertowExchange.dispatch(this);
        }
    }
```
this keyword seems not supported:
```
Error: One of @Delete, @Alias, or @Inject must be used: final io.quarkus.cxf.runtime.graal.Substitutions io.quarkus.cxf.runtime.graal.Substitutions$Substitute_UndertowHTTPDestination.this$0
com.oracle.svm.core.util.UserError$UserException: One of @Delete, @Alias, or @Inject must be used: final io.quarkus.cxf.runtime.graal.Substitutions io.quarkus.cxf.runtime.graal.Substitutions$Substitute_UndertowHTTPDestination.this$0
	at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
	at com.oracle.svm.core.util.UserError.guarantee(UserError.java:86)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleFieldInAliasClass(AnnotationSubstitutionProcessor.java:356)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:304)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:274)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:230)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:876)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:825)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:528)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)

```

**Comment by cstancu** [comment]
You can use [`com.oracle.svm.core.SubstrateUtil.cast(Object obj, Class<T> toType)`](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/SubstrateUtil.java#L211). For your example above:
```
abstract class AbstractFoo {
}

class Foo extends AbstractFoo {
    public void func() {
    }
}

class Bar {
    public void method(AbstractFoo a) {
    }
}

@TargetClass(className = "Foo")
final class Target_Foo {
    @Substitute
    public void func() {
        Bar bar = new Bar();
        bar.method(SubstrateUtil.cast(this, AbstractFoo.class));
    }
}
```
However, be warned that the substitution mechanism is not API and it can change without notice. It is meant for internal use in SubstrateVM only. Although you may use it as a temporary solution, in the long run you should aim to update the code that requires the modifications.
