### ISSUE TITLE
Cannot build a bundle jar with Jersey+Jetty+CDI

### ISSUE THREAD

**Issue by nhenneaux** [oracle/graal#2075]
I tried to build the bundle jar built in the project [jersey-http2-jetty-connector](https://github.com/nhenneaux/jersey-http2-jetty-connector/tree/master/jersey-http2-jetty-bundle) using `mvn clean verify  -DskipTests -DskipDepCheck` command.
## First I tried without any option.
`native-image -jar jersey-http2-jetty-connector/jersey-http2-jetty-bundle/target/jersey-http2-jetty-bundle-*-bundle.jar`
It failed and I got the following error.
```
Caused by: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass(String, byte[], int, int, ProtectionDomain) is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
```
## So I tried with `--report-unsupported-elements-at-runtime`
I got the following warnings.
`Warning: Image 'jersey-http2-jetty-bundle-1.0.0-bundle' is a fallback image that requires a JDK for execution (use --no-fallback to suppress fallback image generation).`
`Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: org.slf4j.impl.StaticMarkerBinder.getSingleton(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
`
## Then with `--allow-incomplete-classpath`
The build succeed, however when I try to run the native bundle it fails with the following error.
```
$ ./jersey-http2-jetty-bundle-1.0.0-bundle
Exception in thread "main" java.lang.AssertionError: Spi class not found
	at java.security.Security.getSpiClass(Security.java:684)
	at java.security.Security.getImpl(Security.java:700)
	at java.security.KeyStore.getInstance(KeyStore.java:875)
	at com.github.nhenneaux.jersey.http2.jetty.bundle.JettyServer$TlsSecurityConfiguration.getKeyStore(JettyServer.java:150)
	at com.github.nhenneaux.jersey.http2.jetty.bundle.Bootstrap.main(Bootstrap.java:11)
Caused by: java.lang.ClassNotFoundException: java.security.KeyStoreSpi
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
	at java.lang.Class.forName(DynamicHub.java:1184)
	at java.security.Security.getSpiClass(Security.java:680)
	... 4 more
```

Do you have any idea why I got the error `java.lang.ClassNotFoundException: java.security.KeyStoreSpi`?

Thanks for your help

**Comment by cstancu** [comment]
You should enable security services with `--enable-all-security-services`. You can read more [here](https://github.com/oracle/graal/blob/master/substratevm/JCA-SECURITY-SERVICES.md) (although the `libsunec.so` info in that doc is out of date; it is now linked in via JNI when needed).

**Comment by nhenneaux** [comment]
Thanks, it's progressing :-)
I now get the following error on startup of the native image
`Caused by: java.lang.InstantiationException: Type `org.apache.logging.log4j.message.DefaultFlowMessageFactory` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.`

I also get the warning `Image-build server limit exceeded. Use options --server{-list,-shutdown[-all]} to fix the problem.` construction of the native image but it's not clear to what server it's about?

**Comment by cstancu** [comment]
> org.apache.logging.log4j.message.DefaultFlowMessageFactory can not be instantiated reflectively as it does not have a no-parameter constructor

That type's no-parameter constructor needs to be registered for reflection. You can also use the[ `native-image-agent`](https://github.com/oracle/graal/blob/master/substratevm/CONFIGURE.md#assisted-configuration-of-native-image-builds) to automatically discover such cases.

>  it's not clear to what server it's about

It's the native image build server, i.e., a compilation server that speeds up builds by keeping a warmed up JVM running the Graal compiler around. You can bypass it by adding the `--no-serrver` option to `native-image`.

**Comment by nhenneaux** [comment]
Thanks for your help !
I'm still getting the same error even with native image agent. Perhaps I missed something.
I firstly run the application with the agent.
`$HOME/Downloads/graalvm-ce-java11-19.3.1/Contents/Home/bin/native-image -H:ConfigurationFileDirectories=graal/config-dir/ --report-unsupported-elements-at-runtime  --allow-incomplete-classpath --enable-all-security-services -jar /Users/nicolas/IdeaProjects/jersey-http2-jetty-connector/jersey-http2-jetty-bundle/target/jersey-http2-jetty-bundle-*-bundle.jar`
Then I build the native image with this config.
`$HOME/Downloads/graalvm-ce-java11-19.3.1/Contents/Home/bin/native-image -H:ConfigurationFileDirectories=graal/config-dir/ --report-unsupported-elements-at-runtime  --allow-incomplete-classpath --enable-all-security-services -jar /Users/nicolas/IdeaProjects/jersey-http2-jetty-connector/jersey-http2-jetty-bundle/target/jersey-http2-jetty-bundle-*-bundle.jar`
And finally I ran the native bundle.
`./jersey-http2-jetty-bundle-1.0.0-bundle`
I still get the error
`Caused by: java.lang.InstantiationException: Type `org.apache.logging.log4j.message.DefaultFlowMessageFactory` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
`
Have I missed something ?

**Comment by cstancu** [comment]
Does your reflection config contains `org.apache.logging.log4j.message.DefaultFlowMessageFactory`'s no-parameter constructor?

**Comment by nhenneaux** [comment]
Yes it's inside it
```
$ grep 'DefaultFlowMessageFactory' graal/config-dir/*
graal/config-dir/reflect-config.json:  "name":"org.apache.logging.log4j.message.DefaultFlowMessageFactory",
```

**Comment by nhenneaux** [comment]
Hi @cstancu ,

Were you able to dig further on this issue?

Thanks for your help,

Nicolas

**Comment by jramirez-isc** [comment]
Hi @nhenneaux I'm currently working on this issue, I'm trying to reproduce it and not seeing the `no-parameter constructor `message, but I'm getting a different error message, even when running with `java -jar`:
```
2020-03-18 15:55:37.391:INFO::main: Logging initialized @1808ms to org.eclipse.jetty.util.log.StdErrLog
Exception in thread "main" java.lang.IllegalStateException: No Server ALPNProcessors!
	at org.eclipse.jetty.alpn.server.ALPNServerConnectionFactory.<init>(ALPNServerConnectionFactory.java:52)
	at com.github.nhenneaux.jersey.http2.jetty.bundle.JettyServer.getConnectionFactories(JettyServer.java:95)
	at com.github.nhenneaux.jersey.http2.jetty.bundle.JettyServer.<init>(JettyServer.java:58)
	at com.github.nhenneaux.jersey.http2.jetty.bundle.Bootstrap.main(Bootstrap.java:16)
	Suppressed: java.lang.IllegalStateException: org.eclipse.jetty.alpn.ALPN must be on JVM boot classpath
		at org.eclipse.jetty.alpn.openjdk8.server.OpenJDK8ServerALPNProcessor.init(OpenJDK8ServerALPNProcessor.java:44)
		at org.eclipse.jetty.alpn.server.ALPNServerConnectionFactory.<init>(ALPNServerConnectionFactory.java:72)
		... 3 more

```
Did you encounter this error?

This is the `native-image` command I ran:
```
native-image -H:ReflectionConfigurationFiles=config-dir/reflect-config.json -H:ResourceConfigurationFiles=config-dir/resource-config.json --enable-all-security-services --allow-incomplete-classpath --report-unsupported-elements-at-runtime --no-fallback -jar target/jersey-http2-jetty-bundle-*-bundle.jar
```

**Comment by nhenneaux** [comment]
Hi,

Are you running it using Java 11? It needs an alpn processor which is not
available in Java 8.

Thanks for your support,

Best regards,

Nicolas Henneaux

**Comment by jramirez-isc** [comment]
@nhenneaux Yes, that was it, thank you.
I could go further the `org.apache.logging.log4j.message.DefaultFlowMessageFactory` error by using:
```
-H:ReflectionConfigurationFiles=config-dir/reflect-config.json -H:DynamicProxyConfigurationFiles=config-dir/proxy-config.json -H:ResourceConfigurationFiles=config-dir/resource-config.json
```
Instead of `-H:ConfigurationFileDirectories` option. @cstancu do you think there is an issue with this option? Apparently, it's not recognizing the reflection config from the `config-dir`.

**Comment by nhenneaux** [comment]
I just tested it now and it works with latest version. Fallback is still needed.
```
nicolas@enix-002:~/ahub/jersey-http2-jetty-connector$ /home/nicolas/Downloads/graalvm-ce-java11-linux-amd64-20.1.0/graalvm-ce-java11-20.1.0/bin/native-image -jar jersey-http2-jetty-bundle/target/jersey-http2-jetty-bundle-*-bundle.jar
Build on Server(pid: 137555, port: 34589)
[jersey-http2-jetty-bundle-1.0.1-bundle:137555]    classlist:   1,381.91 ms,  4.46 GB
[jersey-http2-jetty-bundle-1.0.1-bundle:137555]        (cap):     364.34 ms,  4.46 GB
[jersey-http2-jetty-bundle-1.0.1-bundle:137555]        setup:     612.74 ms,  4.46 GB
WARNING GR-10238: VarHandle for static field is currently not fully supported. Static field private static volatile java.lang.System$Logger jdk.internal.event.EventHelper.securityLogger is not properly marked for Unsafe access!
^L[jersey-http2-jetty-bundle-1.0.1-bundle:137555]     (clinit):     392.24 ms,  4.56 GB
[jersey-http2-jetty-bundle-1.0.1-bundle:137555]     analysis:  26,827.04 ms,  4.56 GB
Warning: Aborting stand-alone image build due to unsupported features
Warning: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Build on Server(pid: 137555, port: 34589)
[jersey-http2-jetty-bundle-1.0.1-bundle:137555]    classlist:      65.18 ms,  4.63 GB
[jersey-http2-jetty-bundle-1.0.1-bundle:137555]        (cap):     384.80 ms,  4.63 GB
[jersey-http2-jetty-bundle-1.0.1-bundle:137555]        setup:     544.32 ms,  4.63 GB
[jersey-http2-jetty-bundle-1.0.1-bundle:137555]     (clinit):      86.81 ms,  4.63 GB
[jersey-http2-jetty-bundle-1.0.1-bundle:137555]   (typeflow):   2,906.23 ms,  4.63 GB
[jersey-http2-jetty-bundle-1.0.1-bundle:137555]    (objects):   3,944.56 ms,  4.63 GB
[jersey-http2-jetty-bundle-1.0.1-bundle:137555]   (features):      69.80 ms,  4.63 GB
[jersey-http2-jetty-bundle-1.0.1-bundle:137555]     analysis:   7,182.01 ms,  4.63 GB
[jersey-http2-jetty-bundle-1.0.1-bundle:137555]     universe:     143.67 ms,  4.63 GB
[jersey-http2-jetty-bundle-1.0.1-bundle:137555]      (parse):     312.12 ms,  4.63 GB
[jersey-http2-jetty-bundle-1.0.1-bundle:137555]     (inline):     440.39 ms,  4.63 GB
[jersey-http2-jetty-bundle-1.0.1-bundle:137555]    (compile):   1,910.43 ms,  4.59 GB
[jersey-http2-jetty-bundle-1.0.1-bundle:137555]      compile:   2,939.08 ms,  4.59 GB
[jersey-http2-jetty-bundle-1.0.1-bundle:137555]        image:     488.24 ms,  4.59 GB
[jersey-http2-jetty-bundle-1.0.1-bundle:137555]        write:     108.43 ms,  4.59 GB
[jersey-http2-jetty-bundle-1.0.1-bundle:137555]      [total]:  11,508.27 ms,  4.59 GB
Warning: Image 'jersey-http2-jetty-bundle-1.0.1-bundle' is a fallback image that requires a JDK for execution (use --no-fallback to suppress fallback image generation and to print more detailed information why a fallback image was necessary).

```

**Comment by jramirez-isc** [comment]
@nhenneaux you still need to use `--enable-all-security-services` option. And also use the [native-image-agent](https://github.com/oracle/graal/blob/master/substratevm/CONFIGURE.md#assisted-configuration-of-native-image-builds) to generate the reflection config and specify that configuration at image building, using these options:
```
-H:ReflectionConfigurationFiles= 
-H:DynamicProxyConfigurationFiles=
-H:ResourceConfigurationFiles=
-H:JNIConfigurationFiles=
```

**Comment by nhenneaux** [comment]
Thanks for the help, it seems fine with all the options !
```
nicolas@enix-002:~/ahub/jersey-http2-jetty-connector$ $GRAAL_HOME/bin/native-image \
> --enable-all-security-services \
> -H:ReflectionConfigurationFiles=graal/config-dir/reflect-config.json \
> -H:DynamicProxyConfigurationFiles=graal/config-dir/proxy-config.json \
> -H:ResourceConfigurationFiles=graal/config-dir/resource-config.json \
> -H:JNIConfigurationFiles=graal/config-dir/jni-config.json  \
> -jar jersey-http2-jetty-bundle/target/jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle.jar
Build on Server(pid: 85947, port: 42307)*
[jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle:85947]    classlist:   2,253.53 ms,  0.96 GB
[jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle:85947]        (cap):     776.62 ms,  0.96 GB
[jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle:85947]        setup:   1,860.26 ms,  0.96 GB
WARNING GR-10238: VarHandle for static field is currently not fully supported. Static field private static volatile java.lang.System$Logger jdk.internal.event.EventHelper.securityLogger is not properly marked for Unsafe access!
[jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle:85947]     (clinit):     676.47 ms,  5.06 GB
[jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle:85947]     analysis:  38,287.47 ms,  5.06 GB
Warning: Aborting stand-alone image build due to unsupported features
Warning: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Build on Server(pid: 85947, port: 42307)
[jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle:85947]    classlist:      83.86 ms,  5.09 GB
[jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle:85947]        (cap):     387.65 ms,  5.09 GB
[jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle:85947]        setup:     596.96 ms,  5.09 GB
[jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle:85947]     (clinit):      83.70 ms,  5.09 GB
[jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle:85947]   (typeflow):   3,008.22 ms,  5.09 GB
[jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle:85947]    (objects):   3,578.13 ms,  5.09 GB
[jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle:85947]   (features):      84.07 ms,  5.09 GB
[jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle:85947]     analysis:   6,928.69 ms,  5.09 GB
[jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle:85947]     universe:     198.82 ms,  5.09 GB
[jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle:85947]      (parse):     620.60 ms,  5.09 GB
[jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle:85947]     (inline):     642.15 ms,  5.09 GB
[jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle:85947]    (compile):   4,016.66 ms,  5.09 GB
[jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle:85947]      compile:   5,659.70 ms,  5.09 GB
[jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle:85947]        image:     593.33 ms,  5.09 GB
[jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle:85947]        write:     210.54 ms,  5.09 GB
[jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle:85947]      [total]:  14,325.98 ms,  5.09 GB
Warning: Image 'jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle' is a fallback image that requires a JDK for execution (use --no-fallback to suppress fallback image generation and to print more detailed information why a fallback image was necessary).
nicolas@enix-002:~/ahub/jersey-http2-jetty-connector$ ./jersey-http2-jetty-
jersey-http2-jetty-bundle/                       jersey-http2-jetty-bundle-1.0.1-bundle           jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle  jersey-http2-jetty-connector/
nicolas@enix-002:~/ahub/jersey-http2-jetty-connector$ ./jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle 
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2020-08-12 09:30:05.914:INFO::main: Logging initialized @496ms to org.eclipse.jetty.util.log.StdErrLog
2020-08-12 09:30:05.972:INFO:oejs.Server:main: jetty-9.4.30.v20200611; built: 2020-06-11T12:34:51.929Z; git: 271836e4c1f4612f12b7bb13ef5a92a927634b0d; jvm 11.0.7+10-jvmci-20.1-b02
WELD-000900: 3.0.0 (Final)
WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jboss.classfilewriter.ClassFile$1 (file:/home/nicolas/ahub/jersey-http2-jetty-connector/jersey-http2-jetty-bundle/target/jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of org.jboss.classfilewriter.ClassFile$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WELD-ENV-002003: Weld SE container 2f644140-6e6b-4ec2-a343-f9ca712ea424 initialized
2020-08-12 09:30:06.623:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@7ff19c33{/,null,AVAILABLE}
2020-08-12 09:30:06.629:INFO:oejus.SslContextFactory:main: x509=X509@766a49c7(server,h=[e25e7ec8c936, localhost, server.dc1.consul.ingenico.tech, server.dc2.consul.ingenico.tech],w=[]) for Server@6bccd036[provider=null,keyStore=null,trustStore=null]
2020-08-12 09:30:06.715:INFO:oejs.AbstractConnector:main: Started ServerConnector@258d79be{SSL, (ssl, alpn, h2, http/1.1)}{0.0.0.0:8080}
2020-08-12 09:30:06.716:INFO:oejs.Server:main: Started @1298ms
Server Server@6ed3f258{STARTED}[9.4.30.v20200611] has been started and listening on port 8080

^CWELD-ENV-002001: Weld SE container 2f644140-6e6b-4ec2-a343-f9ca712ea424 shut down
Weld SE container 2f644140-6e6b-4ec2-a343-f9ca712ea424 shut down by shutdown hook

**Comment by nhenneaux** [comment]
I made some progress but still blocked on the following error.
```
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported method java.lang.ClassLoader.defineClass1(ClassLoader, String, byte[], int, int, ProtectionDomain, String) is reachable
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:86)
```
I used the following parameters to build native image. I added resources bundles that were missing.
```
$GRAAL_HOME/bin/native-image \
--enable-all-security-services \
-H:ReflectionConfigurationFiles=graal/config-dir/reflect-config.json \
-H:DynamicProxyConfigurationFiles=graal/config-dir/proxy-config.json \
-H:ResourceConfigurationFiles=graal/config-dir/resource-config.json \
-H:JNIConfigurationFiles=graal/config-dir/jni-config.json \
-H:IncludeResourceBundles=javax.servlet.LocalStrings,javax.servlet.http.LocalStrings,javax.xml.bind.Messages,com.sun.org.apache.xerces.internal.impl.msg.SAXMessages \
--no-fallback \
--allow-incomplete-classpath \
--report-unsupported-elements-at-runtime \
-jar jersey-http2-jetty-bundle/target/jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle.jar
```
I built configuration files using Graal agent.
```
$GRAAL_HOME/bin/java -agentlib:native-image-agent=config-output-dir=graal/config-dir/ -jar jersey-http2-jetty-bundle/target/jersey-http2-jetty-bundle-1.0.3-SNAPSHOT-bundle.jar
```

**Comment by nhenneaux** [comment]
Issue in log4j2, rest is now ok. [LOG4J2-2649](https://issues.apache.org/jira/browse/LOG4J2-2649), see also https://github.com/oracle/graal/issues/1209
