### ISSUE TITLE
[native-image] Error instantiating class caused by UnsatisfiedLinkError

### ISSUE THREAD

**Issue by phact** [oracle/graal#2077]
My native image fails at run-time with the following:
```
2020-01-17 02:40:08,941 INFO  [com.dat.pow.LanderResource] (vert.x-worker-thread-5) Could not 
connect to cassandra
java.lang.IllegalArgumentException: Error instantiating class AtomicTimestampGenerator (specified by advanced.timestamp-generator.class): com.kenai.jffi.Foreign.invokeN2O1(JJJJLjava/lang/Object;III)J [symbol: Java_com_kenai_jffi_Foreign_invokeN2O1 or Java_com_kenai_jffi_Foreign_invokeN2O1__JJJJLjava_lang_Object_2III]
	at com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:236)
	at com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:94)
	at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.buildTimestampGenerator(DefaultDriverContext.java:363)
	at com.datastax.oss.driver.internal.core.util.concurrent.LazyReference.get(LazyReference.java:55)
	at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.getTimestampGenerator(DefaultDriverContext.java:732)
	at com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.init(DefaultSession.java:327)
	at com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.access$1000(DefaultSession.java:280)
	at com.datastax.oss.driver.internal.core.session.DefaultSession.lambda$init$0(DefaultSession.java:126)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:497)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: java.lang.UnsatisfiedLinkError: com.kenai.jffi.Foreign.invokeN2O1(JJJJLjava/lang/Object;III)J [symbol: Java_com_kenai_jffi_Foreign_invokeN2O1 or Java_com_kenai_jffi_Foreign_invokeN2O1__JJJJLjava_lang_Object_2III]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
	at com.kenai.jffi.Foreign.invokeN2O1(Foreign.java)
	at com.kenai.jffi.Invoker.invokeN2(Invoker.java:1038)
	at com.datastax.oss.driver.internal.core.os.Native$LibCLoader$LibC$jnr$ffi$2.gettimeofday(Unknown Source)
	at com.datastax.oss.driver.internal.core.os.Native.currentTimeMicros(Native.java:57)
	at com.datastax.oss.driver.internal.core.time.NativeClock.fetchTimeMicros(NativeClock.java:74)
	at com.datastax.oss.driver.internal.core.time.NativeClock.<init>(NativeClock.java:57)
	at com.datastax.oss.driver.internal.core.time.Clock.getInstance(Clock.java:41)
	at com.datastax.oss.driver.internal.core.time.MonotonicTimestampGenerator.buildClock(MonotonicTimestampGenerator.java:109)
	at com.datastax.oss.driver.internal.core.time.MonotonicTimestampGenerator.<init>(MonotonicTimestampGenerator.java:43)
	at com.datastax.oss.driver.internal.core.time.AtomicTimestampGenerator.<init>(AtomicTimestampGenerator.java:52)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:229)
	... 16 more
```

I'm running:
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07)
OpenJDK 64-Bit Server VM GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07, mixed mode, sharing)
```

Given that JNI is in the stacktrace:
> 	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
 

and because I was hitting some other issues with reflection, I did run the dynamic analysis agent using `-agentlib:native-image-agent=config-output-dir=` and pointed to the files in my image build:

    -H:ReflectionConfigurationFiles=../../reflection-config/reflect-config.json
    -H:+JNI
    -H:JNIConfigurationFiles=../../reflection-config/jni-config.json -

But I'm still hitting the error, any ideas would be appreciated!

**Comment by phact** [comment]
I've been digging around and I haven't been able to find anyone that's gotten an app that uses jffi to work with `native-image` yet. If anyone knows of one I'd love to poke around.

In the meantime here's a minimum reproducible example of the error I'm hitting now:

https://github.com/phact/cassandra-quarkus-starter

You do need a cassandra instance running on localhost to point this at. You can get this quickly via docker:

    $ docker run --name some-cassandra --network some-network -d cassandra:tag

**Comment by peter-hofer** [comment]
In this case, the call is from Java to C function `Java_com_kenai_jffi_Foreign_invokeN2O1`, and so an explicit configuration might not be necessary. However, the function cannot be found, so perhaps the jffi native library containing the function implementation has not been (properly) loaded. In some cases that often involve static class initializers, libraries happen to be loaded during the native image build instead of at runtime, in which case you need a way to postpone that library load (for example by delaying class initialization) or to re-load the library at runtime. Can you find out where the jffi library is loaded in Cassandra or your application?

**Comment by phact** [comment]
Thanks @peter-hofer, I think the jffi library gets loaded by the java driver here: https://github.com/datastax/java-driver/blob/2863100b736f01b77f7347d17536da6f151b4583/core/src/main/java/com/datastax/oss/driver/internal/core/os/Native.java

**Comment by phact** [comment]
By the way, I was also able to get around this by asking the java driver to use the java clock instead of the native jffi clock https://datastax-oss.atlassian.net/browse/JAVA-2616

**Comment by peter-hofer** [comment]
Apologies for the late reply. You could try to defer class initialization of those `*Loader` classes until runtime with the `--initialize-at-runtime` parameter to `native-image`.
