### ISSUE TITLE
[native-image] Unsupported feature error JDK11OrLater: Target_java_lang_ClassLoader.loadClass

### ISSUE THREAD

**Issue by aclement** [oracle/graal#2093]
I am compiling our vanilla-jpa sample in the spring feature repo (https://github.com/spring-projects-experimental/spring-graal-native) and running it against a recent 20.0.0 Java11 weekly dev build.

When running the image, I get this error. It isnt' spring directly doing something unsupported but that `Package.getPackageInfo()` - does that need a substitution on it?

```
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: JDK11OrLater: Target_java_lang_ClassLoader.loadClass(Target_java_lang_Module, String)
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Package.getPackageInfo(Package.java:420)
	at java.lang.Package.getAnnotations(Package.java:467)
	at org.springframework.data.util.NullableUtils.isNonNull(NullableUtils.java:138)
	at org.springframework.data.util.NullableUtils.isNonNull(NullableUtils.java:124)
	at org.springframework.data.repository.core.support.MethodInvocationValidator.supports(MethodInvocationValidator.java:63)
```

Here is a small test program that fails in the same way:
```
public class Code {
  public static void main(String []argv) {
    Code.class.getPackage().getAnnotations();
  }
}
```

```
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: JDK11OrLater: Target_java_lang_ClassLoader.loadClass(Target_java_lang_Module, String)
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Package.getPackageInfo(Package.java:420)
	at java.lang.Package.getAnnotations(Package.java:467)
	at Code.main(Code.java:3)
```

**Comment by eginez** [comment]
@aclement Building the example from the latest commit in the master branch succeeds. However the problem mention in this issue is still present

**Comment by eginez** [comment]
I was able to replicate the issue at runtime with the example after changes to the configurations

**Comment by eginez** [comment]
closed with https://github.com/oracle/graal/commit/871f9784f3d7df3556f9388187cdabcdb53751d0
