### ISSUE TITLE
Building substrate vm using mx build fails with an exception

### ISSUE THREAD

**Issue by XanderAtBackboneSystems** [oracle/graal#2095]
I tried to compile a fresh copy of substrate vm using mx. I did this by checking out the lastest release tag (vm-19.3.1) from (git@github.com:oracle/graal.git) and master from  git@github.com:graalvm/mx.git. 

The steps to reproduce are:
1. export PATH="${PATH}:&lt;path-to&gt;/mx"
2. export JAVA_HOME to be either:
    - /Library/Java/JavaVirtualMachines/openjdk1.8.0_242-jvmci-20.0-b02/Contents/Home
    - /Library/Java/JavaVirtualMachines/graalvm-ce-java11-19.3.1/Contents/Home
3. (Optionally) set EXTRA_JAVA_HOMES
4. cd &lt;path-to&gt;/graal/substratevm
5. mx build

The following output is logged:
```
$ mx build
build: Checking SubstrateVM requirements for building ...
no symbols
Updated <path-to>/graal/substratevm/src/com.oracle.svm.native.jvm.posix/src/src_gen/JvmFuncsFallbacks.c
JAVA_HOME: /Library/Java/JavaVirtualMachines/openjdk1.8.0_242-jvmci-20.0-b02/Contents/Home
EXTRA_JAVA_HOMES: /Library/Java/JavaVirtualMachines/graalvm-ce-java11-19.3.1/Contents/Home
Dependencies removed from build:
 project org.graalvm.libgraal.jdk13 was removed as JDK 13 is not available
 project org.graalvm.compiler.serviceprovider.jdk13 was removed as JDK 13 is not available
 project org.graalvm.compiler.hotspot.jdk12 was removed as JDK 12 is not available
 project org.graalvm.compiler.hotspot.jdk13 was removed as JDK 13 is not available
 project org.graalvm.compiler.hotspot.jdk14 was removed as JDK 14 is not available
 com.oracle.svm.native.jvm.windows removed: only windows is supported
 project org.graalvm.compiler.replacements.jdk12.test was removed as JDK 12 is not available
Compiling com.oracle.truffle.api.jdk8 with javac-daemon(JDK 1.8)... [<path-to>/graal/truffle/mxbuild/src/com.oracle.truffle.api.jdk8/bin/com/oracle/truffle/api/impl/TruffleJDKServices.class does not exist]
Creating 'parentClassLoader.classpath' file... [<path-to>/graal/sdk/mxbuild/parentClassLoader.classpath/jvmci-parent-classpath/parentClassLoader.classpath does not exist]
Creating native-image.properties for native-image-agent-library... [content not up to date]
Creating native-image.properties for polyglot-launcher... [content not up to date]
Creating native-image.properties for polyglot-library... [content not up to date]
Creating native-image.properties for native-image-launcher... [content not up to date]
Creating native-image.properties for jvmcicompiler-library... [content not up to date]
Creating native-image.properties for native-image-configure-launcher... [content not up to date]
Compiling com.oracle.graalvm.locator.jdk8 with javac-daemon(JDK 1.8)... [<path-to>/graal/truffle/mxbuild/src/com.oracle.graalvm.locator.jdk8/bin/com/oracle/graalvm/locator/JDKServices.class does not exist]
Compiling org.graalvm.compiler.truffle.runtime.serviceprovider.jdk8 with javac-daemon(JDK 1.8)... [<path-to>/graal/compiler/mxbuild/src/org.graalvm.compiler.truffle.runtime.serviceprovider.jdk8/bin/org/graalvm/compiler/truffle/runtime/serviceprovider/TruffleRuntimeServices.class does not exist]
Compiling org.graalvm.compiler.truffle.common.hotspot with javac-daemon(JDK 1.8)... [<path-to>/graal/compiler/mxbuild/src/org.graalvm.compiler.truffle.common.hotspot/bin/org/graalvm/compiler/truffle/common/hotspot/HotSpotTruffleCompilerRuntime.class[2020-01-23 12:18:57] is older than <path-to>/graal/compiler/mxbuild/src/org.graalvm.compiler.truffle.common/bin/org/graalvm/compiler/truffle/common/VoidGraphStructure.class[2020-01-23 12:27:34]]
Compiling org.graalvm.home.test with javac-daemon(JDK 1.8)... [<path-to>/graal/sdk/mxbuild/src/org.graalvm.home.test/bin/org/graalvm/home/test/VersionTest.class[2020-01-23 12:26:01] is older than <path-to>/graal/sdk/mxbuild/src/org.graalvm.home/bin/org/graalvm/home/impl/VmLocatorSymbol.class[2020-01-23 12:27:34]]
Compiling org.graalvm.launcher.test with javac-daemon(JDK 1.8)... [<path-to>/graal/sdk/mxbuild/src/org.graalvm.launcher.test/bin/org/graalvm/launcher/test/LauncherTest.class[2020-01-23 12:25:53] is older than <path-to>/graal/sdk/mxbuild/src/org.graalvm.launcher/bin/org/graalvm/launcher/PolyglotLauncherFeature.class[2020-01-23 12:27:35]]
Traceback (most recent call last):
  File "<path-to>/mx/mx.py", line 19369, in <module>
    main()
  File "<path-to>/mx/mx.py", line 19350, in main
    retcode = c(command_args)
  File "<path-to>/mx/mx_commands.py", line 147, in __call__
    return self.command_function(*args, **kwargs)
  File "<path-to>/graal/substratevm/mx.substratevm/mx_substratevm.py", line 1268, in build
    orig_command_build(args, vm)
  File "<path-to>/mx/mx_commands.py", line 147, in __call__
    return self.command_function(*args, **kwargs)
  File "<path-to>/mx/mx.py", line 13587, in build
    task.prepare(daemons)
  File "<path-to>/mx/mx.py", line 6964, in prepare
    self.compiler.prepare_daemon(daemons, self.compileArgs)
  File "<path-to>/mx/mx.py", line 7307, in prepare_daemon
    self.daemon = JavacDaemon(self.jdk, jvmArgs)
  File "<path-to>/mx/mx.py", line 7420, in __init__
    CompilerDaemon.__init__(self, jdk, jvmArgs, 'com.oracle.mxtool.compilerserver.JavacDaemon', jdk.toolsjar, ['--force-javac'])
  File "<path-to>/mx/mx.py", line 7356, in __init__
    raise RuntimeError('Error starting ' + self.name() + ': returncode=' + str(returncode) + '\n' + ''.join(pout))
RuntimeError: Error starting javac-daemon: returncode=255
Exception during JVMCI compiler initialization:
Exception in thread "main": jdk.vm.ci.common.JVMCIError
jdk.vm.ci.common.JVMCIError: java.lang.ClassNotFoundException: org.graalvm.word.WordBase
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.createClass(HotSpotJVMCIRuntime.java:503)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime$1.computeValue(HotSpotJVMCIRuntime.java:516)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime$1.computeValue(HotSpotJVMCIRuntime.java:513)
	at java.lang.ClassValue.get(JavaLangSubstitutions.java:510)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.fromClass0(HotSpotJVMCIRuntime.java:523)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.fromClass(HotSpotJVMCIRuntime.java:544)
	at jdk.vm.ci.hotspot.HotSpotMetaAccessProvider.lookupJavaType(HotSpotMetaAccessProvider.java:63)
	at org.graalvm.compiler.word.WordTypes.<init>(WordTypes.java:77)
	at org.graalvm.compiler.hotspot.word.HotSpotWordTypes.<init>(HotSpotWordTypes.java:64)
	at org.graalvm.compiler.hotspot.HotSpotBackendFactory.createWordTypes(HotSpotBackendFactory.java:50)
	at org.graalvm.compiler.hotspot.amd64.AMD64HotSpotBackendFactory.createBackend(AMD64HotSpotBackendFactory.java:124)
	at org.graalvm.compiler.hotspot.HotSpotGraalRuntime.<init>(HotSpotGraalRuntime.java:190)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:156)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:134)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:52)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.getCompiler(HotSpotJVMCIRuntime.java:630)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:697)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST_Nonvirtual:Ljdk_vm_ci_hotspot_HotSpotJVMCIRuntime_2_0002ecompileMethod_00028Ljdk_vm_ci_hotspot_HotSpotResolvedJavaMethod_2IJI_00029Ljdk_vm_ci_hotspot_HotSpotCompilationRequestResult_2(JNIJavaCallWrappers.java:0)
Caused by: java.lang.ClassNotFoundException: org.graalvm.word.WordBase
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at jdk.vm.ci.hotspot.CompilerToVM.lookupType(CompilerToVM.java)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.createClass(HotSpotJVMCIRuntime.java:501)
	... 17 more
```

This also happends when using other mx commands like `mx ideinint` and it also happends on other parts of the graal repo (like compiler) not in sulong.

**Comment by dougxc** [comment]
The problem is caused by using a GraalVM in EXTRA_JAVA_HOMES. Currently, GraalVM cannot be used to bootstrap itself. The workaround is to avoid putting GraalVM in JAVA_HOME or EXTRA_JAVA_HOMES.

**Comment by dougxc** [comment]
This particular failure will be resolved once we fix libgraal such that it does not require the Graal classes to be available on the module path (/cc @tkrodriguez).

**Comment by XanderAtBackboneSystems** [comment]
You are right it works when i only expose: `openjdk1.8.0_242-jvmci-20.0-b02` Using the JAVA_HOME.... is this sufficient to create native-images that are based on jdk11 or do i need a JVMCI enabled jdk 11?

**Comment by dougxc** [comment]
To create native-images based on jdk11, you need to use a JDK downloaded from https://github.com/graalvm/labs-openjdk-11/releases.

**Comment by XanderAtBackboneSystems** [comment]
@dougxc thanx... it was not enough to just use the native image binary... unfortunately.
I try to understand some of the decisions native image makes during execution... but thats an entire other discussion...

Thanks again...
This issue can be closed.

**Comment by crowlogic** [comment]
It would be nice to add a message during build to check and inform the person compiling the thing that graal can't bootstrap itself, just checking the JAVA_HOME can do this
