### ISSUE TITLE
[native-image] helidon quickstart-se build failed on Oracle Linux 7

### ISSUE THREAD

**Issue by dyangcht** [oracle/graal#2105]
I tried to use maven and native-image to build it but got the same error as below.
Anyone got this?

Command:
$ native-image -H:+ReportExceptionStackTraces -jar helidon-quickstart.jar helidon-quickstart

Error message as following:
Warning: Using a deprecated option --delay-class-initialization-to-runtime. Use --initialize-at-run-time.
Build on Server(pid: 17540, port: 41167)
[helidon-quickstart:17540]    classlist:   1,350.28 ms
[helidon-quickstart:17540]        (cap):   1,364.49 ms
[helidon-quickstart:17540]        setup:   1,565.02 ms
Error: Type SignedWord is signed, but accessed C value is unsigned
    method com.oracle.svm.core.posix.headers.Fcntl$flock.l_len()
Error: Type SignedWord is signed, but accessed C value is unsigned
    method com.oracle.svm.core.posix.headers.Fcntl$flock.set_l_len(SignedWord)
Error: Type SignedWord is signed, but accessed C value is unsigned
    method com.oracle.svm.core.posix.headers.Fcntl$flock.l_start()
Error: Type SignedWord is signed, but accessed C value is unsigned
    method com.oracle.svm.core.posix.headers.Fcntl$flock.set_l_start(SignedWord)
com.oracle.svm.core.util.UserError$UserException: Type SignedWord is signed, but accessed C value is unsigned
    method com.oracle.svm.core.posix.headers.Fcntl$flock.l_len()
Type SignedWord is signed, but accessed C value is unsigned
    method com.oracle.svm.core.posix.headers.Fcntl$flock.set_l_len(SignedWord)
Type SignedWord is signed, but accessed C value is unsigned
    method com.oracle.svm.core.posix.headers.Fcntl$flock.l_start()
Type SignedWord is signed, but accessed C value is unsigned
    method com.oracle.svm.core.posix.headers.Fcntl$flock.set_l_start(SignedWord)
	at com.oracle.svm.core.util.UserError.abort(UserError.java:114)
	at com.oracle.svm.hosted.c.NativeLibraries.reportErrors(NativeLibraries.java:196)
	at com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1524)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:834)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:524)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1

**Comment by eginez** [comment]
@dyangcht it appears as if you are using a older version of graalvm? Can you re-run the build with the latest version of both helidon and graalvm?

**Comment by dyangcht** [comment]
> @dyangcht it appears as if you are using a older version of graalvm? Can you re-run the build with the latest version of both helidon and graalvm?

My environment is as following. Are they the newest version?
1. OL7 4.14.35-1902.9.2.el7uek.x86_64
2. GraalVM Community Edition 19.3.1
3. Helidon v1.4.1 SE

**Comment by eginez** [comment]
I am not sure what the latest version of Helidon is, but the graalvm version looks correct, I would suggest opening an issue with the Helidon team as a first step, as they might have already fix this issue

**Comment by dyangcht** [comment]
Ok, Thanks
