### ISSUE TITLE
ClassNotFound when running Native image - although the class is present in the fat jar

### ISSUE THREAD

**Issue by jeevanjoseph** [oracle/graal#2106]
## Background and Description
I am building an application that uses [nats.io](https://nats.io), and [micronaut](http://micronaut.io). I am new to GraalVM and I'm not sure If I've overlooked something, looking at past issues on github that looked similar has not really helped yet.  I'd much appreacite it if someone could point me the right way.

The app builds fine, and generates an executable fat jar (build uses `gradle` and the gradle `shadow` plugin). The app runs fine when the jar is executed, and the `native-image` build does not show any warnings either. At runtime however, the native binary throws a 
```
java.lang.ClassNotFoundException: io.nats.client.impl.SocketDataPort
```
The weird thing is that the `SocketDataPort.class`  is definitely in the fat jar.

### Version Info
```
$ native-image --version
GraalVM Version 19.3.1 CE
```

### Fat jar execution
```
$ java -jar build/libs/fulfillment-0.1-all.jar
23:39:12.183 [pool-1-thread-1] INFO  mushop.FulfillmentService - Connecting to NATS nats://localhost:4222 and subscribing to subject mushop-orders
23:39:12.341 [pool-1-thread-1] INFO  mushop.FulfillmentService - Sending update {"orderId":"ORD-123","shipment":{"id":"SHP-123","name":"Processing"}}
23:39:12.378 [nats:3] INFO  mushop.FulfillmentService - got message OrderUpdate{orderId='ORD-123', Shipment=Shipment{id='SHP-123', name='Processing'}} on the mushop orders subject
23:39:12.686 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 2099ms. Server Running: http://localhost:8099
23:39:22.345 [pool-1-thread-2] INFO  mushop.FulfillmentService - Sending update {"orderId":"ORD-123","shipment":{"id":"SHP-123","name":"Processing"}}
23:39:22.352 [nats:3] INFO  mushop.FulfillmentService - got message OrderUpdate{orderId='ORD-123', Shipment=Shipment{id='SHP-123', name='Processing'}} on the mushop orders subject
^C23:39:24.934 [Thread-4] INFO  io.micronaut.runtime.Micronaut - Embedded Application shutting down
```

### Native image build 
The output here is when building on MacOS. I get the same result when I build using within a linux based docker container with the `--static` flag on  
```
$ native-image -jar build/libs/fulfillment-0.1-all.jar

Build on Server(pid: 10360, port: 59292)
[fulfillment:10360]    classlist:   7,474.21 ms
[fulfillment:10360]        (cap):   1,959.97 ms
[fulfillment:10360]        setup:   2,737.56 ms
[fulfillment:10360]   (typeflow):  43,626.50 ms
[fulfillment:10360]    (objects):  23,463.05 ms
[fulfillment:10360]   (features):   4,461.95 ms
[fulfillment:10360]     analysis:  74,910.60 ms
[fulfillment:10360]     (clinit):   1,391.21 ms
[fulfillment:10360]     universe:   4,050.35 ms
[fulfillment:10360]      (parse):   5,195.78 ms
[fulfillment:10360]     (inline):  16,609.58 ms
[fulfillment:10360]    (compile):  41,587.40 ms
[fulfillment:10360]      compile:  66,348.05 ms
[fulfillment:10360]        image:   4,988.31 ms
[fulfillment:10360]        write:   1,859.60 ms
[fulfillment:10360]      [total]: 162,675.87 ms
```

### Stacktrace
```
$ ./fulfillment
23:25:20.731 [pool-4-thread-1] INFO  mushop.FulfillmentService - Connecting to NATS nats://localhost:4222 and subscribing to subject mushop-orders
23:25:20.734 [pool-4-thread-1] ERROR i.m.s.DefaultTaskExceptionHandler - Error invoking scheduled task Error instantiating bean of type [mushop.FulfillmentService]: java.lang.ClassNotFoundException: io.nats.client.impl.SocketDataPort
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [mushop.FulfillmentService]: java.lang.ClassNotFoundException: io.nats.client.impl.SocketDataPort
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1626)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2307)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1989)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1963)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:605)
	at io.micronaut.scheduling.processor.ScheduledMethodProcessor.lambda$process$5(ScheduledMethodProcessor.java:118)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:497)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

### A closer look at the jar file
`io.nats.client.impl.SocketDataPort` is the 7th on the list
```
$  jar -tvf build/libs/fulfillment-0.1-all.jar |grep io.nats.client.impl
     0 Mon Jan 27 21:37:52 PST 2020 io/nats/client/impl/
   382 Fri Oct 25 16:26:48 PDT 2019 io/nats/client/impl/DataPort.class
 49911 Fri Oct 25 16:26:48 PDT 2019 io/nats/client/impl/NatsConnection.class
  1286 Fri Oct 25 16:26:48 PDT 2019 io/nats/client/impl/StringAuthHandler.class
  6770 Fri Oct 25 16:26:48 PDT 2019 io/nats/client/impl/NatsConsumer.class
  4796 Fri Oct 25 16:26:48 PDT 2019 io/nats/client/impl/NatsMessage.class
  4257 Fri Oct 25 16:26:48 PDT 2019 io/nats/client/impl/FileAuthHandler.class
  4936 Fri Oct 25 16:26:48 PDT 2019 io/nats/client/impl/SocketDataPort.class
   690 Fri Oct 25 16:26:48 PDT 2019 io/nats/client/impl/NatsConnection$3.class
  6708 Fri Oct 25 16:26:48 PDT 2019 io/nats/client/impl/NatsConnectionWriter.class
  6540 Fri Oct 25 16:26:48 PDT 2019 io/nats/client/impl/NatsServerInfo.class
  1372 Fri Oct 25 16:26:48 PDT 2019 io/nats/client/impl/NatsConnectionReader$Mode.class
  4133 Fri Oct 25 16:26:48 PDT 2019 io/nats/client/impl/NatsSubscription.class
   791 Fri Oct 25 16:26:48 PDT 2019 io/nats/client/impl/NatsConnection$2.class
  1133 Fri Oct 25 16:26:48 PDT 2019 io/nats/client/impl/SSLUtils.class
 10103 Fri Oct 25 16:26:48 PDT 2019 io/nats/client/impl/NatsDispatcher.class
  6925 Fri Oct 25 16:26:48 PDT 2019 io/nats/client/impl/NatsStatistics.class
   882 Fri Oct 25 16:26:48 PDT 2019 io/nats/client/impl/SSLUtils$1.class
 11477 Fri Oct 25 16:26:48 PDT 2019 io/nats/client/impl/NatsConnectionReader.class
  1584 Fri Oct 25 16:26:48 PDT 2019 io/nats/client/impl/NatsImpl.class
  6002 Fri Oct 25 16:26:48 PDT 2019 io/nats/client/impl/MessageQueue.class
   977 Fri Oct 25 16:26:48 PDT 2019 io/nats/client/impl/NatsConnection$1.class
```

**Comment by eginez** [comment]
@jeevanjoseph it seems like the class was never made it to the native image. could be because the classes is being access through reflection?  I would check the callers of that class and make sure you have the right [configurations](https://github.com/oracle/graal/blob/master/substratevm/LIMITATIONS.md#reflection) for the libraries you are using

**Comment by jeevanjoseph** [comment]
Yes. Just skimmed through the Nats.io source, and sure enough the `DataPort` is created via reflection -  [buildDataPort](https://github.com/nats-io/nats.java/blob/7f7fe824422b6966c8147bc5f028f228be4ed6ad/src/main/java/io/nats/client/Options.java#L1268) and [createInstanceOf](https://github.com/nats-io/nats.java/blob/7f7fe824422b6966c8147bc5f028f228be4ed6ad/src/main/java/io/nats/client/Options.java#L681).

**Comment by eginez** [comment]
perfect it should be a matter of creating/amending the configuration to include such file. I am closing this issue for now. Feel free to re-open it if need be
