### ISSUE TITLE
mx native-image broken

### ISSUE THREAD

**Issue by galderz** [oracle/graal#2107]
`mx native-image` in Master (3e83a17e36a056322788acedd1b256b84286acc0) seems to be broken:

```
mx native-image HelloWorld
WARNING: No platform-specific definition is available for distribution JDK11_NATIVE_IMAGE_MUSL_SUPPORT for your OS (darwin)
[helloworld:27912]    classlist:   1,869.33 ms,  1.36 GB
[helloworld:27912]        setup:      72.63 ms,  1.36 GB
Fatal error: java.lang.NoClassDefFoundError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:462)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:357)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:501)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:115)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:528)
Caused by: java.lang.NoClassDefFoundError: org/graalvm/compiler/nodes/spi/PlatformConfigurationProvider
	at com.oracle.svm.core.genscavenge.graal.HeapFeature.afterRegistration(HeapFeature.java:68)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$11(NativeImageGenerator.java:817)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:817)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:528)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.ClassNotFoundException: org.graalvm.compiler.nodes.spi.PlatformConfigurationProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 12 more
```

And there might be more issues with it. 10 days before I tried and this was happening (I don't know if latest error is hiding it):

```
$ mx native-image HelloWorld
WARNING: No platform-specific definition is available for distribution JDK11_NATIVE_IMAGE_MUSL_SUPPORT for your OS (darwin)
[helloworld:12209]    classlist:   1,780.14 ms,  1.20 GB
[helloworld:12209]        setup:     104.12 ms,  1.20 GB
Fatal error: java.lang.NoSuchMethodError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:462)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:357)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:501)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:115)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:528)
Caused by: java.lang.NoSuchMethodError: 'void org.graalvm.compiler.core.amd64.AMD64SuitesCreator.<init>(org.graalvm.compiler.phases.tiers.CompilerConfiguration)'
	at com.oracle.svm.core.graal.amd64.SubstrateAMD64SuitesCreatorProvider.<init>(SubstrateAMD64SuitesCreatorProvider.java:35)
	at com.oracle.svm.core.graal.amd64.SubstrateAMD64Feature.afterRegistration(SubstrateAMD64Feature.java:83)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$11(NativeImageGenerator.java:817)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:817)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:528)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1
```

This last one seemed to be happening because I was using JDK11 which has an outdated `AMD64SuitesCreator` class that hasn't got the constructor that Graal expects. This new constructor is only in the version that's in the graal source tree.

**Comment by olpaw** [comment]
@galderz are you using a standard JDK or the ones from
* https://github.com/graalvm/openjdk8-jvmci-builder/releases (for Java 8)
* https://github.com/graalvm/labs-openjdk-11/releases (for Java 11)
?

**Comment by galderz** [comment]
Using `labsjdk-ce-11.0.6+9-jvmci-20.0-b02-darwin-amd64.tar.gz`

**Comment by olpaw** [comment]
Not sure what your problem is. Cannot reproduce locally:
```
🍎 [master=] ~/OLabs/graal/substratevm> mx native-image -jar svmbuild/vm/lib/graalvm/svm-driver.jar 
WARNING: No platform-specific definition is available for distribution JDK11_NATIVE_IMAGE_MUSL_SUPPORT for your OS (darwin)
[native-image:5108]    classlist:   1,773.32 ms,  1.00 GB
[native-image:5108]        (cap):   1,147.20 ms,  1.24 GB
[native-image:5108]        setup:   2,360.94 ms,  1.24 GB
[native-image:5108]   (typeflow):   6,854.61 ms,  2.35 GB
[native-image:5108]    (objects):   7,230.99 ms,  2.35 GB
[native-image:5108]   (features):     338.50 ms,  2.35 GB
[native-image:5108]     analysis:  14,910.73 ms,  2.35 GB
[native-image:5108]     (clinit):     235.07 ms,  2.35 GB
[native-image:5108]     universe:     596.33 ms,  2.35 GB
[native-image:5108]      (parse):     969.89 ms,  2.35 GB
[native-image:5108]     (inline):   4,827.28 ms,  3.22 GB
[native-image:5108]    (compile):   7,600.24 ms,  3.22 GB
[native-image:5108]      compile:  14,092.56 ms,  3.22 GB
[native-image:5108]        image:   1,833.59 ms,  3.22 GB
[native-image:5108]        write:     421.54 ms,  3.22 GB
[native-image:5108]      [total]:  36,228.76 ms,  3.22 GB
🍎 [master %=] ~/OLabs/graal/substratevm> echo $JAVA_HOME 
/Users/paul/OLabs/jdk-11
🍎 [master %=] ~/OLabs/graal/substratevm> readlink /Users/paul/OLabs/jdk-11
labsjdk-ce-11.0.6-jvmci-20.0-b02/Contents/Home
🍎 [master %=] ~/OLabs/graal/substratevm> git log -1
commit 44fa6d297f106c60566f6faa3b50d4cea401cd51 (HEAD -> master, origin/master, origin/HEAD)
```

**Comment by galderz** [comment]
@olpaw Thanks for double checking this. I did a fresh clone of the repo and it works. Apologies for the inconvenience.

However, I fail to see how I can completely clean the graal repo to fix this?  There's no way to do `mx clean` from the root of the repo. Doing an `mx clean` in substratevm directory name is not enough in this case. Doing an `mx clean` in all directories neither works (see [example](https://gist.github.com/galderz/cb65a6a39d4bbbd7fd79aa986fd8e96b)). What else is required to fully clean things?

**Comment by olpaw** [comment]
I usually use `git clean -dfx` on repo top level for that.

**Comment by galderz** [comment]
@olpaw That worked, thank you 😀
