### ISSUE TITLE
[native-image][19.3.1][java8] mac os native image build fails

### ISSUE THREAD

**Issue by dieu** [oracle/graal#2117]
I try to build a native image and got an error:

```
Fatal error: java.lang.RuntimeException: java.lang.RuntimeException: host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 1

Running command: cc -v -o /Users/apanasenko/workspace/source3/strato-check-tool -Wl,-no_compact_unwind -Wl,-exported_symbols_list -Wl,/var/folders/ck/4611r0hx4nv5fpj5r2sff1nc0000gp/T/SVM-4580101948668973565/exported_symbols.list -Wl,-x -arch x86_64 -L/var/folders/ck/4611r0hx4nv5fpj5r2sff1nc0000gp/T/SVM-4580101948668973565 -L/Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib -L/Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64 /var/folders/ck/4611r0hx4nv5fpj5r2sff1nc0000gp/T/SVM-4580101948668973565/strato-check-tool.o /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libjava.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libnet.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libzip.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libnio.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libffi.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/liblibchelper.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libjvm.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libstrictmath.a -lm -Wl,-framework,CoreFoundation -lpthread -ldl -lz

Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -lto_library /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib -dynamic -arch x86_64 -macosx_version_min 10.14.0 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -o /Users/apanasenko/workspace/source3/strato-check-tool -L/var/folders/ck/4611r0hx4nv5fpj5r2sff1nc0000gp/T/SVM-4580101948668973565 -L/Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib -L/Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64 -no_compact_unwind -exported_symbols_list /var/folders/ck/4611r0hx4nv5fpj5r2sff1nc0000gp/T/SVM-4580101948668973565/exported_symbols.list -x /var/folders/ck/4611r0hx4nv5fpj5r2sff1nc0000gp/T/SVM-4580101948668973565/strato-check-tool.o /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libjava.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libnet.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libzip.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libnio.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libffi.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/liblibchelper.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libjvm.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libstrictmath.a -lm -framework CoreFoundation -lpthread -ldl -lz -L/usr/local/lib -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/lib/darwin/libclang_rt.osx.a
Undefined symbols for architecture x86_64:
  "_VerifyClassname", referenced from:
      _Java_sun_misc_URLClassPath_knownToNotExist0 in libjava.a(URLClassPath.o)
      _Java_java_lang_ClassLoader_findBootstrapClass in libjava.a(ClassLoader.o)
  "_VerifyFixClassname", referenced from:
      _Java_sun_misc_URLClassPath_knownToNotExist0 in libjava.a(URLClassPath.o)
      _Java_java_lang_ClassLoader_findBootstrapClass in libjava.a(ClassLoader.o)
      _Java_java_lang_ClassLoader_defineClass2 in libjava.a(ClassLoader.o)
      _Java_java_lang_ClassLoader_defineClass1 in libjava.a(ClassLoader.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:462)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:315)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:454)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:115)
Caused by: java.lang.RuntimeException: host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 1

Running command: cc -v -o /Users/apanasenko/workspace/source3/strato-check-tool -Wl,-no_compact_unwind -Wl,-exported_symbols_list -Wl,/var/folders/ck/4611r0hx4nv5fpj5r2sff1nc0000gp/T/SVM-4580101948668973565/exported_symbols.list -Wl,-x -arch x86_64 -L/var/folders/ck/4611r0hx4nv5fpj5r2sff1nc0000gp/T/SVM-4580101948668973565 -L/Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib -L/Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64 /var/folders/ck/4611r0hx4nv5fpj5r2sff1nc0000gp/T/SVM-4580101948668973565/strato-check-tool.o /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libjava.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libnet.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libzip.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libnio.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libffi.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/liblibchelper.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libjvm.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libstrictmath.a -lm -Wl,-framework,CoreFoundation -lpthread -ldl -lz

Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -lto_library /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib -dynamic -arch x86_64 -macosx_version_min 10.14.0 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -o /Users/apanasenko/workspace/source3/strato-check-tool -L/var/folders/ck/4611r0hx4nv5fpj5r2sff1nc0000gp/T/SVM-4580101948668973565 -L/Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib -L/Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64 -no_compact_unwind -exported_symbols_list /var/folders/ck/4611r0hx4nv5fpj5r2sff1nc0000gp/T/SVM-4580101948668973565/exported_symbols.list -x /var/folders/ck/4611r0hx4nv5fpj5r2sff1nc0000gp/T/SVM-4580101948668973565/strato-check-tool.o /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libjava.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libnet.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libzip.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/libnio.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libffi.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/liblibchelper.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libjvm.a /Users/apanasenko/Downloads/graalvm-ce-java8-19.3.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libstrictmath.a -lm -framework CoreFoundation -lpthread -ldl -lz -L/usr/local/lib -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/lib/darwin/libclang_rt.osx.a
Undefined symbols for architecture x86_64:
  "_VerifyClassname", referenced from:
      _Java_sun_misc_URLClassPath_knownToNotExist0 in libjava.a(URLClassPath.o)
      _Java_java_lang_ClassLoader_findBootstrapClass in libjava.a(ClassLoader.o)
  "_VerifyFixClassname", referenced from:
      _Java_sun_misc_URLClassPath_knownToNotExist0 in libjava.a(URLClassPath.o)
      _Java_java_lang_ClassLoader_findBootstrapClass in libjava.a(ClassLoader.o)
      _Java_java_lang_ClassLoader_defineClass2 in libjava.a(ClassLoader.o)
      _Java_java_lang_ClassLoader_defineClass1 in libjava.a(ClassLoader.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

	at com.oracle.svm.hosted.image.NativeBootImageViaCC.write(NativeBootImageViaCC.java:388)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:652)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
```

**Comment by eginez** [comment]
@dieu Can you provide us with a code snippet that reproduces this error?

**Comment by olpaw** [comment]
See https://github.com/oracle/graal/issues/2144#issuecomment-584617332
