### ISSUE TITLE
[native-image] Increase maximum Java heap size

### ISSUE THREAD

**Issue by lazar-mitrovic** [oracle/graal#2130]
Building workloads that consume more than 14g of memory causes following exception:
```
Error: Image build request failed with exit status 137 (
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 137
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1504)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1266)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1227)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1186)
	at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1683)
Compilation failed with result = 137
```
Since this status code represents out of memory exception, I bumped value at: 
https://github.com/oracle/graal/blob/c6537b12d96d383aa904a55621cafe7ec05d72eb/substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java#L1582
to `55g` after which build completed successfully. 

I suppose that valid fix for this issue would be removing check altogether, like:
```java
protected String getXmxValue(int maxInstances) {
        Long memMax = Long.divideUnsigned(Long.divideUnsigned(getPhysicalMemorySize(), 10) * 8, maxInstances);
        return Long.toUnsignedString(memMax);
    }
``` 
if there are no known use cases where this could cause regressions.

**Comment by olpaw** [comment]
> Building workloads that consume more than 14g of memory causes following exception

If you want to perform image builds that require more than 14g you have to use e.g.
```
native-image --no-server -J-Xmx24G ...
```
The `--no-server` will ensure that no native-image build server will be created that keeps running to wait for further image build requests after your image build completed. If you use `--no-server` you are allowed to use as much heap as you like for a single image build.

**Comment by vjovanov** [comment]
@olpaw what was the reason for this difference in behavior? I don't see a reason to put a limitation on what the user wants.

**Comment by olpaw** [comment]
The reason we have it is to prevent a native-image build server to be too greedy by default. We have gate builders with e.g. 128GB of RAM and lots of cores (48 and more) and we run multiple buildbot requests simultaneously on those machines. If each native-image build server would claim 80% of that RAM per default that would be a bad idea. If a user needs more than that upper limit he can dot that by building with a custom Xmx setting using --no-server:
```
bin/native-image --no-server -J-Xmx24G ....
```
If users (i.e. more than one random person) really want native-image build servers that take make than 14g we could add a specific native-image option for that (e.g. --server-Xmx).

**Comment by vjovanov** [comment]
Makes sense. Why don't we just use the `-J-Xmx` and if it is set we change the 14G for the value that the user passed?

**Comment by olpaw** [comment]
Because then you have no image build-server reuse unless you use the exact same `-J-Xmx` argument in all you image build requests.

**Comment by vjovanov** [comment]
Wouldn't most of them be 14G, and then for the special cases it would be a separate server. I find this a better trade-off than to have something working only with `--no-server` or adding a separate flag. I think this is an exceptional usecase.

**Comment by olpaw** [comment]
Keep in mind that truffle languages can also specify custom `-Xmx` values in their `native-image.properties` files. Thus preventing image build server reuse is even more likely if there is not fixed `-Xmx` for server mode.

To really fix this for once and all we could modify the scheme that we use to calculate `NativeImageServer.imageServerUID` to not take `-Xm*` arguments into account. Then we would have image build server reuse even if the `-Xm*` arguments of the request do not match with the ones the build server got started with. But it would hurt if we output a warning in case of of reuse with non-matching `-Xm*` args.

**Comment by vjovanov** [comment]
Yes, we could do that. We run all images smaller than 14g on the main server, and then if the value is larger we can create a separate server. A warning is maybe needed only if someone puts a value that is smaller than 14g on the command line (not in the property files). Nobody complained until now, so maybe we should not be overly aggressive with the warnings.

WDYT?

**Comment by olpaw** [comment]
> WDYT?

Sounds like a good idea.

**Comment by simonDeHero** [comment]
hi, i wanted to "bump" this topic, as i am currently getting this "status 137" error too.

i am using graalvm CE 20.1.0 with java 11. my app is based on Spring Boot 2.3.0. the app has the according Spring dependencies for web mvc (REST layer), feign (auto-generated http client) jpa (postgres) and integration with AWS SQS (putting messages to queue and listening for new messages). 

my build machine has 16GB RAM and a 16GB swap file and i specified `--no-server -J-Xmx30G` for the `native-image` command. after the `analysis` step, i get this "status 137" error.

thx for looking into this issue!
