### ISSUE TITLE
Does reading a file, then closing it (its e.g. InputStream), really have to be delayed in static initialization?

### ISSUE THREAD

**Issue by doctorpangloss** [oracle/graal#2133]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **oracle/graalvm-ce:19.3.1-java11**
 - CE or EE: **CE**
 - Build Time or run time failure: **build-time**
 - JDK version: **JDK11**

It appears I cannot read and close a file during static build time initialization.

This is extremely valuable for deserialization of resources. It would, on the face of it, be side-effect free, in all ways that actually matter.

**Code snippet or code repository that reproduces the issue**

Graal is being evaluated for a game server to distribute opponent AI move calculations to a lambda / serverless function.

This snippet is an example of something in a static initializer that will fail:

```
Files.newInputStream(filename);
```

This command is used to build the entire application. It static initializes the minimum number of classes to load the contents of the `CardCatalogue` (this is a digital card game), which is JSON resources that get deserialized into objects living in static fields.

**native-image command**:
```
native-image \
    --no-server \
    --no-fallback \
    --initialize-at-build-time=com.hiddenswitch.spellsource.micro.BotsController,com.hiddenswitch.spellsource.core.JsonConfiguration,io.vertx.core.json,net.demilich,com.google.common.base.Preconditions,com.google.common.base.Ascii,com.google.common.base.CharMatcher,com.google.common.base.CharMatcher\$InRange,com.google.common.base.CharMatcher\$Is,com.google.common.base.CharMatcher\$FastMatcher,com.google.common.base.CaseFormat,com.google.common.base.CaseFormat\$3,com.google.common.base.CaseFormat\$1,com.google.common.base.CaseFormat\$4,com.google.common.base.CaseFormat\$2,com.google.common.base.CaseFormat\$5 \
    --static \
    -H:+TraceClassInitialization \
    -H:ReflectionConfigurationFiles=src/main/resources/META-INF/native-image/com.hiddenswitch.spellsource/micro/reflect-config.json \
    -H:DynamicProxyConfigurationFiles=src/main/resources/META-INF/native-image/com.hiddenswitch.spellsource/micro/proxy-config.json \
    -H:ResourceConfigurationFiles=src/main/resources/META-INF/native-image/com.hiddenswitch.spellsource/micro/resource-config.json \
    -H:IncludeResources=src/main/resources/logback.xml,src/main/resources/application.yml \
    -H:Name=micro \
    -H:Class=com.hiddenswitch.spellsource.micro.Application \
    -cp build/libs/micro-*-all.jar
[micro:24]    classlist:  15,815.97 ms
[micro:24]        (cap):     933.89 ms
[micro:24]        setup:   2,595.66 ms
[micro:24]   (typeflow):  48,959.93 ms
[micro:24]    (objects):  40,088.24 ms
[micro:24]   (features):  11,194.89 ms
[micro:24]     analysis: 104,896.55 ms
Error: Unsupported features in 5 methods
Detailed message:
Error: Detected a direct Buffer in the image heap. A direct Buffer has a pointer to unmanaged C memory, and C memory from the image generator is not available at image run time.  Object has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-build-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: 	object jdk.internal.jimage.ImageReader$SharedImageReader
	object jdk.internal.jimage.ImageReader
	method jdk.internal.module.SystemModuleFinders$SystemImage.reader()
Call path from entry point to jdk.internal.module.SystemModuleFinders$SystemImage.reader(): 
	at jdk.internal.module.SystemModuleFinders$SystemImage.reader(SystemModuleFinders.java:385)
	at jdk.internal.module.SystemModuleFinders$ModuleContentSpliterator.next(SystemModuleFinders.java:526)
	at jdk.internal.module.SystemModuleFinders$ModuleContentSpliterator.tryAdvance(SystemModuleFinders.java:549)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
	at com.oracle.svm.jni.access.JNIReflectionDictionary.unsetEntryPoints(JNIReflectionDictionary.java:149)
	at com.oracle.svm.jni.functions.JNIFunctions.UnregisterNatives(JNIFunctions.java:362)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_UnregisterNatives_07af9442aa98f893dd700b47b363fa08a3f7e240(generated:0)
Error: Detected a direct Buffer in the image heap. A direct Buffer has a pointer to unmanaged C memory, and C memory from the image generator is not available at image run time.  Object has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-build-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: 	object jdk.internal.jimage.ImageReader$SharedImageReader
	object jdk.internal.jimage.ImageReader
	method jdk.internal.module.SystemModuleFinders$SystemImage.reader()
Call path from entry point to jdk.internal.module.SystemModuleFinders$SystemImage.reader(): 
	at jdk.internal.module.SystemModuleFinders$SystemImage.reader(SystemModuleFinders.java:385)
	at jdk.internal.module.SystemModuleFinders$ModuleContentSpliterator.next(SystemModuleFinders.java:526)
	at jdk.internal.module.SystemModuleFinders$ModuleContentSpliterator.tryAdvance(SystemModuleFinders.java:549)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
	at com.oracle.svm.jni.access.JNIReflectionDictionary.unsetEntryPoints(JNIReflectionDictionary.java:149)
	at com.oracle.svm.jni.functions.JNIFunctions.UnregisterNatives(JNIFunctions.java:362)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_UnregisterNatives_07af9442aa98f893dd700b47b363fa08a3f7e240(generated:0)
Error: Detected a direct/mapped ByteBuffer in the image heap. A direct ByteBuffer has a pointer to unmanaged C memory, and C memory from the image generator is not available at image run time. A mapped ByteBuffer references a file descriptor, which is no longer open and mapped at run time.  Object has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-build-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: 	object jdk.internal.jimage.ImageReader$SharedImageReader
	object jdk.internal.jimage.ImageReader
	method jdk.internal.module.SystemModuleFinders$SystemImage.reader()
Call path from entry point to jdk.internal.module.SystemModuleFinders$SystemImage.reader(): 
	at jdk.internal.module.SystemModuleFinders$SystemImage.reader(SystemModuleFinders.java:385)
	at jdk.internal.module.SystemModuleFinders$ModuleContentSpliterator.next(SystemModuleFinders.java:526)
	at jdk.internal.module.SystemModuleFinders$ModuleContentSpliterator.tryAdvance(SystemModuleFinders.java:549)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
	at com.oracle.svm.jni.access.JNIReflectionDictionary.unsetEntryPoints(JNIReflectionDictionary.java:149)
	at com.oracle.svm.jni.functions.JNIFunctions.UnregisterNatives(JNIFunctions.java:362)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_UnregisterNatives_07af9442aa98f893dd700b47b363fa08a3f7e240(generated:0)
Error: Detected a direct/mapped ByteBuffer in the image heap. A direct ByteBuffer has a pointer to unmanaged C memory, and C memory from the image generator is not available at image run time. A mapped ByteBuffer references a file descriptor, which is no longer open and mapped at run time.  Object has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-build-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: 	object jdk.internal.jimage.ImageReader$SharedImageReader
	object jdk.internal.jimage.ImageReader
	method jdk.internal.module.SystemModuleFinders$SystemImage.reader()
Call path from entry point to jdk.internal.module.SystemModuleFinders$SystemImage.reader(): 
	at jdk.internal.module.SystemModuleFinders$SystemImage.reader(SystemModuleFinders.java:385)
	at jdk.internal.module.SystemModuleFinders$ModuleContentSpliterator.next(SystemModuleFinders.java:526)
	at jdk.internal.module.SystemModuleFinders$ModuleContentSpliterator.tryAdvance(SystemModuleFinders.java:549)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
	at com.oracle.svm.jni.access.JNIReflectionDictionary.unsetEntryPoints(JNIReflectionDictionary.java:149)
	at com.oracle.svm.jni.functions.JNIFunctions.UnregisterNatives(JNIFunctions.java:362)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_UnregisterNatives_07af9442aa98f893dd700b47b363fa08a3f7e240(generated:0)
Error: Detected a direct/mapped ByteBuffer in the image heap. A direct ByteBuffer has a pointer to unmanaged C memory, and C memory from the image generator is not available at image run time. A mapped ByteBuffer references a file descriptor, which is no longer open and mapped at run time.  Object has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-build-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: 	object jdk.internal.jimage.ImageReader$SharedImageReader
	object jdk.internal.jimage.ImageReader
	method jdk.internal.module.SystemModuleFinders$SystemImage.reader()
Call path from entry point to jdk.internal.module.SystemModuleFinders$SystemImage.reader(): 
	at jdk.internal.module.SystemModuleFinders$SystemImage.reader(SystemModuleFinders.java:385)
	at jdk.internal.module.SystemModuleFinders$ModuleContentSpliterator.next(SystemModuleFinders.java:526)
	at jdk.internal.module.SystemModuleFinders$ModuleContentSpliterator.tryAdvance(SystemModuleFinders.java:549)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
	at com.oracle.svm.jni.access.JNIReflectionDictionary.unsetEntryPoints(JNIReflectionDictionary.java:149)
	at com.oracle.svm.jni.functions.JNIFunctions.UnregisterNatives(JNIFunctions.java:362)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_UnregisterNatives_07af9442aa98f893dd700b47b363fa08a3f7e240(generated:0)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
 1. `git clone https://github.com/hiddenswitch/Spellsource-Server.git && cd Spellsource-Server && git checkout micro-improvements`
 2. With JDK11: `./gradlew micro:shadowJar && docker build -t micro -f micro/Dockerfile .`

**Expected behavior**
Reading files in a static initializer should work.

**Comment by doctorpangloss** [comment]
You can read a file and close it in static initialization.
