### ISSUE TITLE
[native image]BufferOverFlowException when build

### ISSUE THREAD

**Issue by kangzq0530** [oracle/graal#2134]
OS: Windows 10 64bit
GraalVM : ee-java8-19.3.1
output:
[server:20488]    classlist:   9,735.83 ms
[server:20488]        (cap):   3,488.14 ms
[server:20488]        setup:   6,038.86 ms
[server:20488]   (typeflow):  71,208.39 ms
[server:20488]    (objects):  37,012.61 ms
[server:20488]   (features):   8,344.66 ms
[server:20488]     analysis: 121,588.52 ms
[server:20488]     (clinit):   1,825.38 ms
8954 method(s) included for runtime compilation
[server:20488]     universe:   5,660.79 ms
[server:20488]      (parse):   7,115.10 ms
[server:20488]     (inline):  19,638.45 ms
[server:20488]    (compile):  63,902.86 ms
[server:20488]      compile:  96,801.57 ms
[server:20488]        image:  10,511.17 ms
[server:20488]        write:     124.31 ms
Fatal error: com.oracle.svm.core.util.VMError$HostedError: java.nio.BufferOverflowException
        at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:70)
        at com.oracle.svm.hosted.image.NativeBootImage.write(NativeBootImage.java:141)
        at com.oracle.svm.hosted.image.NativeBootImageViaCC.write(NativeBootImageViaCC.java:329)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:652)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.nio.BufferOverflowException
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:363)
        at java.nio.ByteBuffer.put(ByteBuffer.java:859)
        at com.oracle.objectfile.ObjectFile.writeBuffer(ObjectFile.java:1611)
        at com.oracle.objectfile.ObjectFile.write(ObjectFile.java:1207)
        at com.oracle.svm.hosted.image.NativeBootImage.write(NativeBootImage.java:139)
        ... 8 more
Error: Image build request failed with exit status 1

By the way, the recently build snapshot is not usable for windows which the system default code page is not 437, because native-image try to detected the msvc version by exec cl.exe but the output is different in different code page.

**Comment by kangzq0530** [comment]
I added a Feature class:
```
@AutomaticFeature
final class BeforeImageWriteFeature implements Feature {

    @SneakyThrows
    @Override
    public void beforeImageWrite(BeforeImageWriteAccess access) {
        ObjectFile file = ((BeforeImageWriteAccessImpl) access).getImage().getOrCreateDebugObjectFile();
        ArrayList<Element> elements = new ArrayList<>();
        int bake = file.bake(elements);
        for (Element element : elements) {
            System.out.println(element.toString());
            int off = (int) file.getDecisionsByElement().get(element).getDecision(LayoutDecision.Kind.OFFSET).getValue();
            System.out.println(off);
            int expectedSize = (int) file.getDecisionsByElement().get(element).getDecidedValue(LayoutDecision.Kind.SIZE);
            byte[] content = (byte[]) file.getDecisionsByElement().get(element).getDecidedValue(LayoutDecision.Kind.CONTENT);
            System.out.println(expectedSize);
            System.out.println(content.length);
        }
        System.out.println(bake);
    }
}
```
And the output:
```
PECoffHeader(PECoffHeader)
0
20
20
SectionHeaderTable(.secthdrtab)
20
200
200
PECoffDirectiveSection(.drectve)
220
2552
2552
PECoffProgbitsSection(.text)
4096
67179920
67179920
PECoffProgbitsSection(.rodata)
67186688
31064
31064
PECoffProgbitsSection(.data)
67219456
4024
4024
PECoffProgbitsSection(.svm_heap)
67223552
78911864
78911864
PECoffRelocationTable(.reloctab)
146135416
1269180
1269180
PECoffSymtab(.symtab)
147404596
8256171
8256604
155660767
```
So `PECoffSymtab` content.length doesn't match it allocate, and cause the BufferOverFlowException.
But I don't know why this happend, hope for help.
