### ISSUE TITLE
Lambda expression in classes marked for initialization at build time

### ISSUE THREAD

**Issue by crowlogic** [oracle/graal#2135]
Error: Classes that should be initialized at run time got initialized during image building:
 com.crowlogic.b2tf.Configuration$$Lambda$1374/0x00000008455aa840 was unintentionally initialized at build time. com.crowlogic.b2tf.Configuration$$Lambda$1374/0x00000008455aa840 has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.crowlogic.b2tf.Configuration$$Lambda$1374/0x00000008455aa840

com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 com.crowlogic.b2tf.Configuration$$Lambda$1374/0x00000008455aa840 was unintentionally initialized at build time. com.crowlogic.b2tf.Configuration$$Lambda$1374/0x00000008455aa840 has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=com.crowlogic.b2tf.Configuration$$Lambda$1374/0x00000008455aa840

	at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:510)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:187)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:710)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:710)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

I think it would make sense, to automatically assume all the lambda expressions are initialized.. instead of having to identify them by hex values which can change arbitrarily

Maybe related to
https://github.com/oracle/graal/issues/1218

**Comment by vjovanov** [comment]
Could you please provide a command that will allow me to reproduce the issue?

**Comment by crowlogic** [comment]
@vjovanov Hi Vojan, was the project I shared sufficient to reproduce the problem? Thanks!!

**Comment by sdeleuze** [comment]
Hi, we are blocked by this issue while trying to optimize Spring Boot application image size. Please let me know if I should share a repro project or not. Also could you tag it with `spring`?

**Comment by sdeleuze** [comment]
Thanks. Is there a workaround for that? If I specify `org.springframework.util.MimeType$$Lambda$3` it is not taken in account, and `org.springframework.util.MimeType$$Lambda$3/1638737677` changes at each compilation. For now I try to use package config but if there is a better way I would be interested to know.

**Comment by vjovanov** [comment]
Here is a reproducer:
```
class SideEffect {
  static {
    System.console();
  }
  static int v = 1; 
}
interface TestSAM {
  static int v = SideEffect.v;
 
  int apply(int v);

  default void hi() {}
}
class LambdaHolder {

  public static TestSAM f = (x) -> {
    return 1;
  };

}

public class HelloWorld {
	public static void main(String[] args) throws Exception {
           System.out.println(LambdaHolder.f.apply(1));
	}
}```

`native-image --initialize-at-build-time=LambdaHolder --debug-attach HelloWorld`


Have you tried with latest master, it should improve things? This issue is quite hard to hit.

**Comment by sdeleuze** [comment]
@vjovanov I have just tried the latest [20.2.0-dev-20200423_0149](https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/20.2.0-dev-20200423_0149) build and indeed it compiles fine my `org.springframework.util.MimeType` class and its lambda.

But latest [20.1.0-dev-20200419_0207 build](https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/20.1.0-dev-20200419_0207) still has the issue.

Could you check if the next `20.1.0-dev` build will contain the fix?

**Comment by vjovanov** [comment]
It will eventually, as I am fixing this issue now and will do a backport of it.

**Comment by vjovanov** [comment]
This issue has been fixed. Now one will have to specify `--initialize-at-build-time=LambdaHolder,TestSam` and the system will prove the lambda as safe.
