### ISSUE TITLE
[native image] crash with SIGSEGV when trying to migrate aws-java-sdk version to 2.10.56

### ISSUE THREAD

**Issue by nikitakakra** [oracle/graal#2138]
Trying to  building the native image in codeBuild on AWS. I had upgraded aws-java-sdk version from 1.x.x to 2.10.56. The native image builds with the 1.x.x version however, an error occurs when building the native image with 2.10.56 version. I have used GraalVM version 19.0.0 and micronaut-bom: 1.1.1.

The CloudWatch logs are as below:

`Warning: class initialization of class io.netty.channel.epoll.Native failed with exception java.lang.NoClassDefFoundError: Could not initialize class io.netty.channel.epoll.Native. This class will be initialized at run time because either option --report-unsupported-elements-at-runtime or option --allow-incomplete-classpath is used for image building. Use the option --delay-class-initialization-to-runtime=io.netty.channel.epoll.Native to explicitly request delayed initialization of this class.`

```
#  A fatal error has been detected by the Java Runtime Environment:
# SIGSEGV (0xb) at pc=0x00007f8a435218e0, pid=71, tid=0x00007f89f79c0700
# JRE version: OpenJDK Runtime Environment (8.0_202-b08) (build 1.8.0_202-20190206132807.buildslave.jdk8u-src-tar--b08)
# Java VM: OpenJDK GraalVM CE 1.0.0-rc15 (25.202-b08-jvmci-0.58 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C 0x00007f8a435218e0
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
# An error report file with more information is saved as:
# /codebuild/output/src666903570/src/hs_err_pid71.log
# If you would like to submit a bug report, please visit:
# http://bugreport.java.com/bugreport/crash.jsp
Error: Image build request failed with exit status 134
[Container] 2020/02/07 06:45:52 Command did not exit successfully ./build-native-image.sh exit status 1
[Container] 2020/02/07 06:45:52 Phase complete: BUILD State: FAILED
[Container] 2020/02/07 06:45:52 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: ./build-native-image.sh. Reason: exit status 1
[Container] 2020/02/07 06:45:52 Entering phase POST_BUILD
[Container] 2020/02/07 06:45:52 Phase complete: POST_BUILD State: SUCCEEDED
[Container] 2020/02/07 06:45:52 Phase context status code: Message:
[Container] 2020/02/07 06:45:53 Expanding base directory path: .
[Container] 2020/02/07 06:45:53 Assembling file list
[Container] 2020/02/07 06:45:53 Expanding .
[Container] 2020/02/07 06:45:53 Expanding file paths for base directory .
[Container] 2020/02/07 06:45:53 Assembling file list
[Container] 2020/02/07 06:45:53 Expanding ./test-function-*.zip
[Container] 2020/02/07 06:45:53 Phase complete: UPLOAD_ARTIFACTS State: FAILED
[Container] 2020/02/07 06:45:53 Phase context status code: CLIENT_ERROR Message: no matching artifact paths found
```
build-native-image.sh

```
#!/bin/sh
GRAALVM_HOME=${GRAALVM_HOME:-/usr/lib/graalvm}
${GRAALVM_HOME}/bin/native-image --no-server \
             --class-path test-function-custom-runtime-*.jar \
             -H:ReflectionConfigurationFiles=src/main/resources/reflect.json \
             -H:EnableURLProtocols=http \
             -H:IncludeResources="logback.xml|application.properties|git.properties|.*/endpoints.json$" \
	     -H:Log=registerResource \
	     -H:DynamicProxyConfigurationFiles="dynamic-proxies.json" \
             -H:Name=server \
             -H:Class=io.micronaut.function.aws.runtime.MicronautLambdaRuntime \
             -H:+ReportUnsupportedElementsAtRuntime \
             -H:-AllowVMInspection \
	     --enable-https \
             --allow-incomplete-classpath \
             --rerun-class-initialization-at-runtime='sun.security.jca.JCAUtil$CachedSecureRandomHolder,javax.net.ssl.SSLContext' \
             --delay-class-initialization-to-runtime=io.netty.handler.codec.http.HttpObjectEncoder,io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder,io.netty.handler.ssl.util.ThreadLocalInsecureRandom,com.sun.jndi.dns.DnsClient,io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler,com.amazonaws.serverless.proxy.internal.LambdaContainerHandler,io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator,io.netty.handler.ssl.ReferenceCountedOpenSslEngine
```

P.S. If I upgrade graal and micronaut-bom version to 1.2.10 and graal verison 19.2.1, the native image is successfully created but when I try to access an application endpoint, it fails for below exception: `error failed: org.apache.commons.logging.LogFactoryjava.lang.NoClassDefFoundError: org.apache.commons.logging.LogFactory and series of exceptions with specifically while creating S3 client and  lambda client.`

The exception also had failure at below point:
`failed: Could not initialize class software.amazon.awssdk.http.apache.internal.conn.SdkTlsSocketFactoryjava.lang.NoClassDefFoundError: Could not initialize class software.amazon.awssdk.http.apache.internal.conn.SdkTlsSocketFactory`

Any help is appreciated!

**Comment by eginez** [comment]
it seems like you are missing classes in your native image. Perhaps you need to register some of the missing classes for reflection.
See https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md

**Comment by nikitakakra** [comment]
Sorry for the delay in response .
This is my [reflect.json](https://github.com/oracle/graal/files/4265747/reflect.txt) file 
While building the native image I m getting the below error 
`
Error: Error parsing reflection configuration in /codebuild/output/src123456/src/src/main/resources/reflect.json:
Class org.apache.commons.logging.impl.Jdk14Logger not found
Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option ReflectionConfigurationFiles.
com.oracle.svm.core.util.UserError$UserException: Error parsing reflection configuration in /codebuild/output/src123456/src/src/main/resources/reflect.json:
Class org.apache.commons.logging.impl.Jdk14Logger not found
Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option ReflectionConfigurationFiles.
at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
at com.oracle.svm.hosted.config.ConfigurationParserUtils.doParseAndRegister(ConfigurationParserUtils.java:137)
at com.oracle.svm.hosted.config.ConfigurationParserUtils.lambda$parseAndRegisterConfigurations$1(ConfigurationParserUtils.java:84)
at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:210)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:313)
at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.IntPipeline.reduce(IntPipeline.java:479)
at java.util.stream.IntPipeline.sum(IntPipeline.java:437)
at com.oracle.svm.hosted.config.ConfigurationParserUtils.parseAndRegisterConfigurations(ConfigurationParserUtils.java:89)
at com.oracle.svm.reflect.hosted.ReflectionFeature.duringSetup(ReflectionFeature.java:69)
at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$12(NativeImageGenerator.java:842)
at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:842)
at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:524)
at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1`

I have added the `org.apache.commons.logging.impl.Jdk14Logger`  in reflect.json

**Comment by nikitakakra** [comment]
> it seems like you are missing classes in your native image. Perhaps you need to register some of the missing classes for reflection.
> See https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md

I have added the reflect.json but still facing the issue
