### ISSUE TITLE
[LLVM] UnsupportedSpecializationException when running "chicken"

### ISSUE THREAD

**Issue by zilti** [oracle/graal#2184]
**GraalVM and my environment :**
 - GraalVM version or commit id if built from source: 20.0.0
 - CE or EE: CE
 - JDK version: JDK11
 - OS and OS Version: OpenSUSE Linux with Kernel 5.5.4-1-default
 - Architecture: amd64
 - The output of `java -Xinternalversion`:
```
OpenJDK 64-Bit Server VM (11.0.6+9-jvmci-20.0-b02) for linux-amd64 JRE (11.0.6+9-jvmci-20.0-b02), built on Jan 20 2020 20:06:41 by "buildslave" with gcc 7.3.0
```

**Have you verified this issue still happens when using the latest snapshot?**
The snapshot is older than the release.

**Describe the issue**
When trying to run the compiled program, I get `ERROR: com.oracle.truffle.api.dsl.UnsupportedSpecializationException: Unexpected values provided for LLVMAMD64WriteAddressRegisterNodeGen#1: [StackPointer 0x7f9210bff010 (Bounds: 0x7f920bbff010 - 0x7f9210bff010)], [StackPointer]`. I added the full stack trace at the bottom of the ticket for readability reasons.

**How to compile the LLVM bitcode that causes the problem**
 - Did you use the bundled [llvm toolchain](https://www.graalvm.org/docs/reference-manual/languages/llvm/#compiling-to-llvm-bitcode) for compiling to LLVM bicode (see `lli --print-toolchain-path`)? *yes*
 - If not, does problem still occur when using the toolchain? *does not apply*
 - If the toolchain cannot be used, which compilers/tools were use and what versions (e.g., `clang --version`)? *does not apply*

**Code snippet or code repository that reproduces the problem**

**Steps to reproduce the problem**
Please include both build steps as well as run steps
1. `gu install llvm-toolchain`
2. Download "chicken-5.1.0.tar.gz" from [code.call-cc.org](http://code.call-cc.org/) and extract it
3. Make sure `${GRAALVM_HOME}/languages/llvm/native/bin` is on the PATH and `which gcc` returns the GraalVM symlink to GraalVM's clang.
4. Run `make PLATFORM=linux`
5. Run `${GRAALVM_HOME}/languages/llvm/bin/lli csi`
6. Admire the exception

**Expected behavior**
A REPL is supposed to show up.

**Additional context**
Here is the full stack trace of running `lli csi`:
```
ERROR: com.oracle.truffle.api.dsl.UnsupportedSpecializationException: Unexpected values provided for LLVMAMD64WriteAddressRegisterNodeGen#1: [StackPointer 0x7f9210bff010 (Bounds: 0x7f920bbff010 - 0x7f9210bff010)], [StackPointer]
org.graalvm.polyglot.PolyglotException: com.oracle.truffle.api.dsl.UnsupportedSpecializationException: Unexpected values provided for LLVMAMD64WriteAddressRegisterNodeGen#1: [StackPointer 0x7f9210bff010 (Bounds: 0x7f920bbff010 - 0x7f9210bff010)], [StackPointer]
        at com.oracle.truffle.llvm.runtime.nodes.asm.support.LLVMAMD64WriteAddressRegisterNodeGen.executeAndSpecialize(LLVMAMD64WriteAddressRegisterNodeGen.java:172)
        at com.oracle.truffle.llvm.runtime.nodes.asm.support.LLVMAMD64WriteAddressRegisterNodeGen.execute_generic4(LLVMAMD64WriteAddressRegisterNodeGen.java:136)
        at com.oracle.truffle.llvm.runtime.nodes.asm.support.LLVMAMD64WriteAddressRegisterNodeGen.execute(LLVMAMD64WriteAddressRegisterNodeGen.java:51)
        at com.oracle.truffle.llvm.runtime.nodes.asm.base.LLVMInlineAssemblyBlockNode.execute(LLVMInlineAssemblyBlockNode.java:48)
        at com.oracle.truffle.llvm.runtime.nodes.func.LLVMInlineAssemblyRootNode.execute(LLVMInlineAssemblyRootNode.java:74)
        at <llvm> CHICKEN_run(runtime.c:1551:43333)
        at <llvm> CHICKEN_main(runtime.c:635:19970)
        at <llvm> main(csi.c:15476:504107)
        at org.graalvm.polyglot.Value.execute(Value.java:367)
        at com.oracle.truffle.llvm.launcher.LLVMLauncher.execute(LLVMLauncher.java:219)
        at com.oracle.truffle.llvm.launcher.LLVMLauncher.launch(LLVMLauncher.java:63)
        at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:121)
        at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:70)
        at com.oracle.truffle.llvm.launcher.LLVMLauncher.main(LLVMLauncher.java:53)
Original Internal Error: 
com.oracle.truffle.api.dsl.UnsupportedSpecializationException: Unexpected values provided for LLVMAMD64WriteAddressRegisterNodeGen#1: [StackPointer 0x0 (Bounds: 0x0 - 0x0 not allocated)], [StackPointer]
        at com.oracle.truffle.llvm.runtime.nodes.asm.support.LLVMAMD64WriteAddressRegisterNodeGen.executeAndSpecialize(LLVMAMD64WriteAddressRegisterNodeGen.java:172)
        at com.oracle.truffle.llvm.runtime.nodes.asm.support.LLVMAMD64WriteAddressRegisterNodeGen.execute_generic4(LLVMAMD64WriteAddressRegisterNodeGen.java:136)
        at com.oracle.truffle.llvm.runtime.nodes.asm.support.LLVMAMD64WriteAddressRegisterNodeGen.execute(LLVMAMD64WriteAddressRegisterNodeGen.java:51)
        at com.oracle.truffle.llvm.runtime.nodes.asm.base.LLVMInlineAssemblyBlockNode.execute(LLVMInlineAssemblyBlockNode.java:48)
        at com.oracle.truffle.llvm.runtime.nodes.func.LLVMInlineAssemblyRootNode.execute(LLVMInlineAssemblyRootNode.java:74)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:474)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:449)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:419)
        at com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:146)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:349)
        at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:67)
        at com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNode.doDirect(LLVMDispatchNode.java:117)
        at com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNodeGen.executeAndSpecialize(LLVMDispatchNodeGen.java:174)
        at com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNodeGen.executeDispatch(LLVMDispatchNodeGen.java:133)
        at com.oracle.truffle.llvm.runtime.nodes.func.LLVMCallNode.executeGeneric(LLVMCallNode.java:70)
        at com.oracle.truffle.llvm.runtime.nodes.cast.LLVMToAddressNodeGen.executeGeneric_generic5(LLVMToAddressNodeGen.java:141)
        at com.oracle.truffle.llvm.runtime.nodes.cast.LLVMToAddressNodeGen.executeGeneric(LLVMToAddressNodeGen.java:81)
        at com.oracle.truffle.llvm.runtime.nodes.memory.LLVMGetElementPtrNodeGen.executeGeneric_generic2(LLVMGetElementPtrNodeGen.java:80)
        at com.oracle.truffle.llvm.runtime.nodes.memory.LLVMGetElementPtrNodeGen.executeGeneric(LLVMGetElementPtrNodeGen.java:41)
        at com.oracle.truffle.llvm.runtime.nodes.vars.LLVMWriteNodeFactory$LLVMWritePointerNodeGen.execute(LLVMWriteNodeFactory.java:714)
        at com.oracle.truffle.llvm.runtime.nodes.base.LLVMBasicBlockNode$InitializedBlock.execute(LLVMBasicBlockNode.java:154)
        at com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNode.executeGeneric(LLVMDispatchBasicBlockNode.java:81)
        at com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNode.executeGeneric(LLVMFunctionRootNode.java:75)
        at com.oracle.truffle.llvm.runtime.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:87)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:474)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:449)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:419)
        at com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:146)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:349)
        at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:67)
        at com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNode.doDirect(LLVMDispatchNode.java:117)
        at com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNodeGen.executeAndSpecialize(LLVMDispatchNodeGen.java:174)
        at com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNodeGen.executeDispatch(LLVMDispatchNodeGen.java:133)
        at com.oracle.truffle.llvm.runtime.nodes.func.LLVMCallNode.executeGeneric(LLVMCallNode.java:70)
        at com.oracle.truffle.llvm.runtime.nodes.others.LLVMValueProfilingNodeFactory$LLVMI64ProfiledValueNodeGen.executeGeneric_generic1(LLVMValueProfilingNodeFactory.java:392)
        at com.oracle.truffle.llvm.runtime.nodes.others.LLVMValueProfilingNodeFactory$LLVMI64ProfiledValueNodeGen.executeGeneric(LLVMValueProfilingNodeFactory.java:376)
        at com.oracle.truffle.llvm.runtime.nodes.api.LLVMFrameNullerExpression.executeGeneric(LLVMFrameNullerExpression.java:75)
        at com.oracle.truffle.llvm.runtime.nodes.vars.LLVMWriteNodeFactory$LLVMWriteI64NodeGen.execute_generic1(LLVMWriteNodeFactory.java:366)
        at com.oracle.truffle.llvm.runtime.nodes.vars.LLVMWriteNodeFactory$LLVMWriteI64NodeGen.execute(LLVMWriteNodeFactory.java:347)
        at com.oracle.truffle.llvm.runtime.nodes.base.LLVMBasicBlockNode$InitializedBlock.execute(LLVMBasicBlockNode.java:154)
        at com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNode.executeGeneric(LLVMDispatchBasicBlockNode.java:81)
        at com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNode.executeGeneric(LLVMFunctionRootNode.java:75)
        at com.oracle.truffle.llvm.runtime.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:87)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:474)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:449)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:419)
        at com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:146)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:349)
        at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:67)
        at com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNode.doDirect(LLVMDispatchNode.java:117)
        at com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNodeGen.executeAndSpecialize(LLVMDispatchNodeGen.java:174)
        at com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNodeGen.executeDispatch(LLVMDispatchNodeGen.java:133)
        at com.oracle.truffle.llvm.runtime.nodes.func.LLVMCallNode.executeGeneric(LLVMCallNode.java:70)
        at com.oracle.truffle.llvm.runtime.nodes.api.LLVMExpressionNode.executeI32(LLVMExpressionNode.java:87)
        at com.oracle.truffle.llvm.runtime.nodes.others.LLVMValueProfilingNodeFactory$LLVMI32ProfiledValueNodeGen.executeI32(LLVMValueProfilingNodeFactory.java:304)
        at com.oracle.truffle.llvm.runtime.nodes.api.LLVMFrameNullerExpression.executeI32(LLVMFrameNullerExpression.java:120)
        at com.oracle.truffle.llvm.runtime.nodes.vars.LLVMWriteNodeFactory$LLVMWriteI32NodeGen.execute(LLVMWriteNodeFactory.java:271)
        at com.oracle.truffle.llvm.runtime.nodes.base.LLVMBasicBlockNode$InitializedBlock.execute(LLVMBasicBlockNode.java:154)
        at com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNode.executeGeneric(LLVMDispatchBasicBlockNode.java:81)
        at com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNode.executeGeneric(LLVMFunctionRootNode.java:75)
        at com.oracle.truffle.llvm.runtime.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:87)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:474)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:449)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:419)
        at com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:146)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:349)
        at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:67)
        at com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNode.doDirect(LLVMDispatchNode.java:117)
        at com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNodeGen.executeAndSpecialize(LLVMDispatchNodeGen.java:174)
        at com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNodeGen.executeDispatch(LLVMDispatchNodeGen.java:133)
        at com.oracle.truffle.llvm.runtime.nodes.func.LLVMCallNode.executeGeneric(LLVMCallNode.java:70)
        at com.oracle.truffle.llvm.runtime.nodes.api.LLVMExpressionNode.executeI32(LLVMExpressionNode.java:87)
        at com.oracle.truffle.llvm.runtime.nodes.others.LLVMValueProfilingNodeFactory$LLVMI32ProfiledValueNodeGen.executeGeneric(LLVMValueProfilingNodeFactory.java:288)
        at com.oracle.truffle.llvm.runtime.nodes.api.LLVMFrameNullerExpression.executeGeneric(LLVMFrameNullerExpression.java:75)
        at com.oracle.truffle.llvm.runtime.nodes.func.LLVMCallNode.executeGeneric(LLVMCallNode.java:67)
        at com.oracle.truffle.llvm.runtime.nodes.api.LLVMVoidStatementNodeGen.execute(LLVMVoidStatementNodeGen.java:20)
        at com.oracle.truffle.llvm.runtime.nodes.base.LLVMBasicBlockNode$InitializedBlock.execute(LLVMBasicBlockNode.java:154)
        at com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNode.executeGeneric(LLVMDispatchBasicBlockNode.java:81)
        at com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNode.executeGeneric(LLVMFunctionRootNode.java:75)
        at com.oracle.truffle.llvm.runtime.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:87)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:474)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:449)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:419)
        at com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:146)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:349)
        at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:67)
        at com.oracle.truffle.llvm.runtime.nodes.func.LLVMGlobalRootNode.executeWithoutFrame(LLVMGlobalRootNode.java:85)
        at com.oracle.truffle.llvm.runtime.nodes.func.LLVMGlobalRootNode.execute(LLVMGlobalRootNode.java:75)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:474)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:449)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:419)
        at com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:146)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:349)
        at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:67)
        at com.oracle.truffle.llvm.runtime.SulongLibrary$Execute.doCached(SulongLibrary.java:160)
        at com.oracle.truffle.llvm.runtime.SulongLibraryGen$InteropLibraryExports$Cached.executeAndSpecialize(SulongLibraryGen.java:136)
        at com.oracle.truffle.llvm.runtime.SulongLibraryGen$InteropLibraryExports$Cached.execute(SulongLibraryGen.java:101)
        at com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.execute(InteropLibraryGen.java:3778)
        at com.oracle.truffle.polyglot.PolyglotValue$InteropCodeCache$AbstractExecuteNode.executeShared(PolyglotValue.java:1699)
        at com.oracle.truffle.polyglot.PolyglotValue$InteropCodeCache$ExecuteNoArgsNode.executeImpl(PolyglotValue.java:1806)
        at com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:98)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:474)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:449)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:419)
        at com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:146)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget$OptimizedCallProfiled.call(OptimizedCallTarget.java:1292)
        at com.oracle.truffle.polyglot.PolyglotValue$InteropValue.execute(PolyglotValue.java:2464)
        at org.graalvm.polyglot.Value.execute(Value.java:367)
        at com.oracle.truffle.llvm.launcher.LLVMLauncher.execute(LLVMLauncher.java:219)
        at com.oracle.truffle.llvm.launcher.LLVMLauncher.launch(LLVMLauncher.java:63)
        at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:121)
        at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:70)
        at com.oracle.truffle.llvm.launcher.LLVMLauncher.main(LLVMLauncher.java:53)
Caused by: Attached Guest Language Frames (7)
```

**Comment by zapster** [comment]
closing stale issue. reopen if appropriate
