### ISSUE TITLE
[truffle] IndexOutOfBoundsException in PolymorphicSpecializeDump

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#2191]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **20.0.0**
 - CE or EE: **[CE]**
 - JDK version: **[JDK8]**
 - OS and OS Version: **[macOS Catalina]**
 - Architecture: **[amd64]**
 - The output of `java -Xinternalversion`:
```
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (25.242-b06-jvmci-20.0-b02) for bsd-amd64 JRE (8u242), built on Jan 20 2020 12:54:03 by "graal" with gcc 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)
```

**Steps to reproduce**
Run GraalSqueak with `--experimental-options --engine.SplittingDumpDecisions`.

**Line of interest**
https://github.com/oracle/graal/blob/bd6b9c8113340af26cbb1f228958498d10d74b4e/compiler/src/org.graalvm.compiler.truffle.runtime/src/org/graalvm/compiler/truffle/runtime/PolymorphicSpecializeDump.java#L51

**Stack trace**
```
ERROR: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
org.graalvm.polyglot.PolyglotException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.graalvm.compiler.truffle.runtime.PolymorphicSpecializeDump.dumpPolymorphicSpecialize(PolymorphicSpecializeDump.java:51)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.maybeDump(OptimizedCallTarget.java:1269)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.maybeSetNeedsSplit(OptimizedCallTarget.java:1237)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.polymorphicSpecialize(OptimizedCallTarget.java:1212)
	at org.graalvm.compiler.truffle.runtime.GraalTVMCI.reportPolymorphicSpecialize(GraalTVMCI.java:153)
	at com.oracle.truffle.api.impl.Accessor$NodeSupport.reportPolymorphicSpecialize(Accessor.java:168)
	at com.oracle.truffle.api.nodes.Node.reportPolymorphicSpecialize(Node.java:536)
	at de.hpi.swa.graal.squeak.nodes.DispatchEagerlyNodeGen.checkForPolymorphicSpecialize(DispatchEagerlyNodeGen.java:308)
	at de.hpi.swa.graal.squeak.nodes.DispatchEagerlyNodeGen.executeAndSpecialize(DispatchEagerlyNodeGen.java:296)
	at de.hpi.swa.graal.squeak.nodes.DispatchEagerlyNodeGen.executeDispatch(DispatchEagerlyNodeGen.java:82)
	at de.hpi.swa.graal.squeak.nodes.DispatchSendNode.doDispatch(DispatchSendNode.java:46)
	at de.hpi.swa.graal.squeak.nodes.DispatchSendNodeGen.executeSend(DispatchSendNodeGen.java:44)
	at de.hpi.swa.graal.squeak.nodes.bytecodes.SendBytecodes$AbstractSendNode.executeVoid(SendBytecodes.java:74)
	at de.hpi.swa.graal.squeak.nodes.ExecuteContextNode.startBytecode(ExecuteContextNode.java:192)
	at de.hpi.swa.graal.squeak.nodes.ExecuteContextNode.executeFresh(ExecuteContextNode.java:105)
	at de.hpi.swa.graal.squeak.nodes.EnterCodeNode.execute(EnterCodeNode.java:39)
	at <smalltalk> OrderedCollection>>reset(Unknown)
	at <smalltalk> ExternalObjectTable>>externalObjectsArray:(ExternalObjectTable>>externalObjectsArray::4:60-78)
	at <smalltalk> ExternalObjectTable>>synchronizeExternalObjectsArrayAndForceUpdate:(ExternalObjectTable>>synchronizeExternalObjectsArrayAndForceUpdate::18:389-424)
	at <smalltalk> [] in ExternalObjectTable>>clearExternalObjects([] in ExternalObjectTable>>clearExternalObjects:13:296-356)
	at <smalltalk> BlockClosure>>ensure:(BlockClosure>>ensure::3:44-77)
	at <smalltalk> Semaphore>>critical:(Semaphore>>critical::9:177-197)
	at <smalltalk> ExternalObjectTable>>clearExternalObjects(ExternalObjectTable>>clearExternalObjects:17:474-497)
	at <smalltalk> SmalltalkImage>>clearExternalObjects(SmalltalkImage>>clearExternalObjects:3:85-118)
	at <smalltalk> CTX SmalltalkImage>>snapshot:andQuit:withExitCode:embedded: @6057aebb(SmalltalkImage>>snapshot:andQuit:withExitCode:embedded::142:3486-3524)
	at org.graalvm.polyglot.Value.execute(Value.java:367)
	at de.hpi.swa.graal.squeak.launcher.GraalSqueakLauncher.execute(GraalSqueakLauncher.java:114)
	at de.hpi.swa.graal.squeak.launcher.GraalSqueakLauncher.launch(GraalSqueakLauncher.java:75)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:121)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:70)
	at de.hpi.swa.graal.squeak.launcher.GraalSqueakLauncher.main(GraalSqueakLauncher.java:42)
```

/cc @boris-spas

**Comment by boris-spas** [comment]
Tracking internally as GR-21525.

**Comment by boris-spas** [comment]
Fixed in https://github.com/oracle/graal/commit/e5226bc46702ef707cb2484bdc81f8e0a75bf6db
