### ISSUE TITLE
Newest pgjdbc crashes when creating a connection

### ISSUE THREAD

**Issue by snoble** [oracle/graal#2195]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: 19.3.1
 - CE or EE: CE
 - Build Time or run time failure: run-time
 - JDK version: JDK8
 - Native compiler information:<details><summary>Run the following to capture compiler version</summary>
   - In windows: `cl.exe`
   - In macOS : `cc -v`
   - In Linux: `gcc --version`
</details>

```
gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
```
 - Native linker information:<details><summary>Run the following to capture linker version</summary>
   - In windows: `cl.exe`
   - In macOS : `cc -Wl,-v`
   - In Linux: `gcc -Wl,--version`
</details>

```
collect2 version 9.2.1 20191008
/usr/bin/ld -plugin /usr/lib/gcc/x86_64-linux-gnu/9/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper -plugin-opt=-fresolution=/tmp/cckS2Npu.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /l
ib64/ld-linux-x86-64.so.2 -pie -z now -z relro /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/9/crtbeginS.o -L/usr/lib/gcc/x86_64-linux-gnu/9 -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x8
6_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/9/../../.. --version -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-linux-gnu/9/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crtn.o
GNU ld (GNU Binutils for Ubuntu) 2.33
```
 - OS and OS Version: **Ubuntu 19.10**
 - Architecture: **AMD64**
 - The output of `java -Xinternalversion`: 
```
OpenJDK 64-Bit Server VM (25.242-b08) for linux-amd64 JRE (1.8.0_242-8u242-b08-0ubuntu3~19.10-b08), built on Jan 17 2020 23:41:21 by "buildd" with gcc 8.3.0
```

**Have you verified this issue still happens when using the latest snapshot?**
You can find snapshot builds here: https://github.com/graalvm/graalvm-ce-dev-builds/releases

**Describe the issue**
The newest version of pgjdbc (42.2.10) now crashes when creating a connection. 

I made a minimal reproduction `https://github.com/snoble/pgjdbc-bug`. You can `git clone git@github.com:snoble/pgjdbc-bug.git` then `bazel run //src/main/scala/dev/snoble/pgjdbcbug:pgjdbc-bug-10-graal`.

But if you just have a scala program that's just

```scala
  def main(args: Array[String]): Unit = {
    val url = "jdbc:postgresql:db"
    val conn = DriverManager.getConnection(url, "postgres", "")
  }
```

depending on 42.2.10 and run it in graal it will crash with the stack trace

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:290)
        at java.lang.Class.ensureInitialized(DynamicHub.java:475)
        at org.postgresql.Driver.loadDefaultProperties(Driver.java:107)
        at org.postgresql.Driver.access$000(Driver.java:58)
        at org.postgresql.Driver$1.run(Driver.java:93)
        at org.postgresql.Driver$1.run(Driver.java:91)
        at java.security.AccessController.doPrivileged(AccessController.java:117)
        at org.postgresql.Driver.getDefaultProperties(Driver.java:91)
        at org.postgresql.Driver.connect(Driver.java:220)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at dev.snoble.pgjdbcbug.Bug$.main(Bug.scala:9)
        at dev.snoble.pgjdbcbug.Bug.main(Bug.scala)
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: ALLOW_ENCODING_CHANGES
        at org.postgresql.PGProperty.<init>(PGProperty.java:690)
        at org.postgresql.PGProperty.<init>(PGProperty.java:678)
        at org.postgresql.PGProperty.<init>(PGProperty.java:674)
        at org.postgresql.PGProperty.<clinit>(PGProperty.java:31)
        at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
        at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
        ... 12 more
Caused by: java.lang.NoSuchFieldException: ALLOW_ENCODING_CHANGES
        at java.lang.Class.getField(DynamicHub.java:1015)
        at org.postgresql.PGProperty.<init>(PGProperty.java:688)
        ... 17 more
```

**Describe the full native-image command**
<details><summary>Capture full native-image command by running with the `--verbose` flag e.g.:</summary>

```
 native-image --verbose --enable-http --enable-https --initialize-at-build-time=org.postgresql.Driver --initialize-at-build-time=org.postgresql.util.SharedTimer -H:+TraceClassInitialization --no-server --no-fallback -H:Class=dev.snoble.pgjdbcbug.Bug -H:CCompilerPath=/usr/bin/gcc -H:+ReportExceptionStackTraces
```
</details>

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. `git clone git@github.com:snoble/pgjdbc-bug.git`
2. `bazel run //src/main/scala/dev/snoble/pgjdbcbug:pgjdbc-bug-10-graal`
3. (optional) `bazel run //src/main/scala/dev/snoble/pgjdbcbug:pgjdbc-bug-9-graal` to see the code run normally with the previous 42.2.9 version

**Expected behavior**
No exception, or possibly an authentication exception.

**Additional context**
Add any other context about the problem here. Specially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary
<details><summary>Details</summary>

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:290)
        at java.lang.Class.ensureInitialized(DynamicHub.java:475)
        at org.postgresql.Driver.loadDefaultProperties(Driver.java:107)
        at org.postgresql.Driver.access$000(Driver.java:58)
        at org.postgresql.Driver$1.run(Driver.java:93)
        at org.postgresql.Driver$1.run(Driver.java:91)
        at java.security.AccessController.doPrivileged(AccessController.java:117)
        at org.postgresql.Driver.getDefaultProperties(Driver.java:91)
        at org.postgresql.Driver.connect(Driver.java:220)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at dev.snoble.pgjdbcbug.Bug$.main(Bug.scala:9)
        at dev.snoble.pgjdbcbug.Bug.main(Bug.scala)
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: ALLOW_ENCODING_CHANGES
        at org.postgresql.PGProperty.<init>(PGProperty.java:690)
        at org.postgresql.PGProperty.<init>(PGProperty.java:678)
        at org.postgresql.PGProperty.<init>(PGProperty.java:674)
        at org.postgresql.PGProperty.<clinit>(PGProperty.java:31)
        at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
        at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
        ... 12 more
Caused by: java.lang.NoSuchFieldException: ALLOW_ENCODING_CHANGES
        at java.lang.Class.getField(DynamicHub.java:1015)
        at org.postgresql.PGProperty.<init>(PGProperty.java:688)
        ... 17 more
```

Just by looking in the stack trace it looks like the error was introduced with the new code at https://github.com/pgjdbc/pgjdbc/blame/master/pgjdbc/src/main/java/org/postgresql/PGProperty.java#L31

Looking at where the exception occurs it is possible this is related to how graal handles reflections. But I'm not sure. https://github.com/pgjdbc/pgjdbc/blame/master/pgjdbc/src/main/java/org/postgresql/PGProperty.java#L689
</details>
Also submitted at https://github.com/pgjdbc/pgjdbc/issues/1722

**Comment by snoble** [comment]
In response to the conversation in the pgjdbc issue I tried adding a `reflectconfig` to see if that would resolve the issue but it didn't. It is curious to me that the graal analyzer does not detect the `getField` call and report it as an unsupported feature at build time.

https://github.com/snoble/pgjdbc-bug/compare/try-reflectconfig-solution

**Comment by snoble** [comment]
Found that we could solve this with a reflectconfig containing
```json
[
  {
    "name" : "org.postgresql.PGProperty",
    "allDeclaredFields" : true
  }
]
```
It would be nice if this were caught as an unsupported feature. But that seems minor.

**Comment by thomaswue** [comment]
@christianwimmer Should we detect this call as an unsupported feature at build time?
