### ISSUE TITLE
native-image NPE in BytecodeStream.setBCI()

### ISSUE THREAD

**Issue by aclement** [oracle/graal#2200]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: 20.0
 - CE or EE: CE
 - Build Time or run time failure: build-time
 - JDK version: 8
 - Native compiler information:<details><summary>Run the following to capture compiler version</summary>
   - In windows: `cl.exe`
   - In macOS : `cc -v`
   - In Linux: `gcc --version`
</details>

```
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
 - Native linker information:<details><summary>Run the following to capture linker version</summary>
   - In windows: `cl.exe`
   - In macOS : `cc -Wl,-v`
   - In Linux: `gcc -Wl,--version`
</details>

```
@(#)PROGRAM:ld  PROJECT:ld64-450.3
BUILD 18:16:53 Apr  5 2019
configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
Library search paths:
	/usr/local/lib
	/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib
Framework search paths:
	/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
 - OS and OS Version: **[e.g. macOS Catalina]**
 - Architecture: **[e.g.: AMD64]**
 - The output of `java -Xinternalversion`: 
```
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (25.242-b06-jvmci-20.0-b02) for bsd-amd64 JRE (8u242), built on Jan 20 2020 12:54:03 by "graal" with gcc 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)
```

**Have you verified this issue still happens when using the latest snapshot?**
You can find snapshot builds here: https://github.com/graalvm/graalvm-ce-dev-builds/releases

I tried with master today, behaves the same.

**Describe the issue**
Building a new spring-batch sample, used the agent to collect config. The config may be insufficient but the crash doesn't let me know that.

**Describe the full native-image command**
<details><summary>Capture full native-image command by running with the `--verbose` flag e.g.:</summary>

```
 native-image --verbose [... other args]
```
</details>

```
/Users/aclement/installs/graalvm-ce-java8-20.0.0/Contents/Home/jre/bin/native-image -cp /Users/aclement/.m2/repository/org/springframework/experimental/spring-graal-native-feature/0.6.0.BUILD-SNAPSHOT/spring-graal-native-feature-0.6.0.BUILD-SNAPSHOT.jar:/Users/aclement/.m2/repository/org/springframework/boot/spring-boot-starter-batch/2.3.0.M2/spring-boot-starter-batch-2.3.0.M2.jar:/Users/aclement/.m2/repository/org/springframework/boot/spring-boot-starter/2.3.0.M2/spring-boot-starter-2.3.0.M2.jar:/Users/aclement/.m2/repository/org/springframework/boot/spring-boot/2.3.0.M2/spring-boot-2.3.0.M2.jar:/Users/aclement/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.3.0.M2/spring-boot-autoconfigure-2.3.0.M2.jar:/Users/aclement/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.3.0.M2/spring-boot-starter-logging-2.3.0.M2.jar:/Users/aclement/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar:/Users/aclement/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar:/Users/aclement/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.13.0/log4j-to-slf4j-2.13.0.jar:/Users/aclement/.m2/repository/org/apache/logging/log4j/log4j-api/2.13.0/log4j-api-2.13.0.jar:/Users/aclement/.m2/repository/org/slf4j/jul-to-slf4j/1.7.30/jul-to-slf4j-1.7.30.jar:/Users/aclement/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.jar:/Users/aclement/.m2/repository/org/yaml/snakeyaml/1.25/snakeyaml-1.25.jar:/Users/aclement/.m2/repository/org/springframework/batch/spring-batch-core/4.2.1.RELEASE/spring-batch-core-4.2.1.RELEASE.jar:/Users/aclement/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.10.1/jackson-databind-2.10.1.jar:/Users/aclement/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.10.1/jackson-annotations-2.10.1.jar:/Users/aclement/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.10.1/jackson-core-2.10.1.jar:/Users/aclement/.m2/repository/io/micrometer/micrometer-core/1.3.5/micrometer-core-1.3.5.jar:/Users/aclement/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.11/HdrHistogram-2.1.11.jar:/Users/aclement/.m2/repository/org/latencyutils/LatencyUtils/2.0.3/LatencyUtils-2.0.3.jar:/Users/aclement/.m2/repository/javax/batch/javax.batch-api/1.0/javax.batch-api-1.0.jar:/Users/aclement/.m2/repository/org/codehaus/jettison/jettison/1.2/jettison-1.2.jar:/Users/aclement/.m2/repository/org/springframework/batch/spring-batch-infrastructure/4.2.1.RELEASE/spring-batch-infrastructure-4.2.1.RELEASE.jar:/Users/aclement/.m2/repository/org/springframework/retry/spring-retry/1.2.5.RELEASE/spring-retry-1.2.5.RELEASE.jar:/Users/aclement/.m2/repository/org/springframework/spring-aop/5.2.3.RELEASE/spring-aop-5.2.3.RELEASE.jar:/Users/aclement/.m2/repository/org/springframework/spring-beans/5.2.3.RELEASE/spring-beans-5.2.3.RELEASE.jar:/Users/aclement/.m2/repository/org/springframework/spring-context/5.2.3.RELEASE/spring-context-5.2.3.RELEASE.jar:/Users/aclement/.m2/repository/org/springframework/spring-expression/5.2.3.RELEASE/spring-expression-5.2.3.RELEASE.jar:/Users/aclement/.m2/repository/org/springframework/spring-tx/5.2.3.RELEASE/spring-tx-5.2.3.RELEASE.jar:/Users/aclement/.m2/repository/org/springframework/boot/spring-boot-starter-jdbc/2.3.0.M2/spring-boot-starter-jdbc-2.3.0.M2.jar:/Users/aclement/.m2/repository/com/zaxxer/HikariCP/3.4.2/HikariCP-3.4.2.jar:/Users/aclement/.m2/repository/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar:/Users/aclement/.m2/repository/org/springframework/spring-jdbc/5.2.3.RELEASE/spring-jdbc-5.2.3.RELEASE.jar:/Users/aclement/.m2/repository/org/springframework/spring-context-indexer/5.2.3.RELEASE/spring-context-indexer-5.2.3.RELEASE.jar:/Users/aclement/.m2/repository/com/h2database/h2/1.4.200/h2-1.4.200.jar:/Users/aclement/.m2/repository/mysql/mysql-connector-java/8.0.19/mysql-connector-java-8.0.19.jar:/Users/aclement/.m2/repository/org/springframework/spring-core/5.2.3.RELEASE/spring-core-5.2.3.RELEASE.jar:/Users/aclement/.m2/repository/org/springframework/spring-jcl/5.2.3.RELEASE/spring-jcl-5.2.3.RELEASE.jar:/Users/aclement/gits5/spring-graal-native/spring-graal-native-samples/spring-batch-native/target/spring-batch-native-0.0.1-BUILD-SNAPSHOT.jar -Dmode=light --initialize-at-build-time --allow-incomplete-classpath --report-unsupported-elements-at-runtime --enable-all-security-services -H:+ReportExceptionStackTraces -H:Class=org.springframework.samples.springbatchnative.SpringBatchNativeApplication
```

**Code snippet or code repository that reproduces the issue**
```
git clone git@github.com:spring-projects-experimental/spring-graal-native.git
git checkout extensible-configuration
cd spring-graal-native
./build-feature.sh
cd *samples/spring-batch-native
mvn package
./ni.sh
```

```
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.springframework.transaction.reactive.TransactionalOperator.create(org.springframework.transaction.ReactiveTransactionManager)
Parsing context:
	parsing org.springframework.boot.autoconfigure.transaction.TransactionAutoConfiguration.transactionalOperator(TransactionAutoConfiguration.java:69)
	parsing com.oracle.svm.reflect.TransactionAutoConfiguration_transactionalOperator_a964289f6b3e47bee01b407a7368b35f9592c637_38771.invoke(Unknown Source)
	parsing java.lang.reflect.Method.invoke(Method.java:498)
	parsing ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:66)
	parsing ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:119)
	parsing ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:419)
	parsing ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	parsing ch.qos.logback.classic.Logger.log(Logger.java:765)
	parsing org.apache.commons.logging.LogAdapter$Slf4jLocationAwareLog.error(LogAdapter.java:428)
	parsing org.springframework.boot.SpringApplication.reportFailure(SpringApplication.java:837)
	parsing org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:812)
	parsing org.springframework.boot.SpringApplication.run(SpringApplication.java:325)
	parsing org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	parsing org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	parsing org.springframework.samples.springbatchnative.SpringBatchNativeApplication.main(SpringBatchNativeApplication.java:10)
	parsing com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:151)
	parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:327)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:346)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:511)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at org.graalvm.compiler.bytecode.BytecodeStream.setBCI(BytecodeStream.java:209)
	at org.graalvm.compiler.bytecode.BytecodeStream.<init>(BytecodeStream.java:47)
	at org.graalvm.compiler.java.BytecodeParser.<init>(BytecodeParser.java:914)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.<init>(SharedGraphBuilderPhase.java:84)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.<init>(SharedGraphBuilderPhase.java:79)
	at com.oracle.svm.hosted.phases.AnalysisGraphBuilderPhase$AnalysisBytecodeParser.<init>(AnalysisGraphBuilderPhase.java:62)
	at com.oracle.svm.hosted.phases.AnalysisGraphBuilderPhase.createBytecodeParser(AnalysisGraphBuilderPhase.java:56)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:221)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:340)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	... 10 more
Error: Image build request failed with exit status 1
```
</details>

**Comment by thomaswue** [comment]
Thanks for the report! Can you quickly run this with "-ea -esa"? Looking at the relevant code, this should trigger some assertions earlier.

**Comment by aclement** [comment]
Hey Thomas - how should I pass these through? I tried the base app running a 20.0 (8) with those, no difference. I tried supplying them to native-image and it only allowed `-ea` (made no difference), it complained about not recognizing `-esa`. Do I have to get into running the java command behind the native-image command?

**Comment by eginez** [comment]
Andy, I pulled your latest changes and I am no longer seeing this issue. Though other miss-configurations still remain in the example. For the record to pass compiler flags to native-image use the `-J` prefix, e.g.: `-J-esa`

**Comment by eginez** [comment]
Are you seeing the same Andy?

**Comment by aclement** [comment]
Fails the same for me as it does above. I did have to regenerate the `ni.sh` script because dependencies must have shifted (to get the ni.sh script I just run `mvn -Pgraal clean package` then copy out the line from the maven failure. Feels like there might be another bug lurking that the mvn direct run of native-image doesn't print the error out. 

Passing that option through with `-J-esa` did give me new output:
```
Caused by: java.lang.AssertionError
	at org.graalvm.compiler.bytecode.BytecodeStream.<init>(BytecodeStream.java:45)
	at org.graalvm.compiler.java.BytecodeParser.<init>(BytecodeParser.java:914)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.<init>(SharedGraphBuilderPhase.java:84)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.<init>(SharedGraphBuilderPhase.java:79)
	at com.oracle.svm.hosted.phases.AnalysisGraphBuilderPhase$AnalysisBytecodeParser.<init>(AnalysisGraphBuilderPhase.java:62)
	at com.oracle.svm.hosted.phases.AnalysisGraphBuilderPhase.createBytecodeParser(AnalysisGraphBuilderPhase.java:56)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
```

**Comment by eginez** [comment]
@aclement there seems to be a missing dependency in the project as shown here:https://github.com/spring-projects-experimental/spring-graal-native/pull/53.

With such dependency in the classpath, the error is no longer present. Granted I am still verifying for errors in our bytecode parsing. At least the above should let you continue building the application.

FYI that application is initializing a lot of things at build-time, is that expected?

**Comment by eginez** [comment]
If you are wondering where that dependency is coming from:
https://github.com/spring-projects/spring-framework/blob/master/spring-tx/src/main/java/org/springframework/transaction/reactive/TransactionalOperator.java  brings in 
https://github.com/reactor/reactor-core/blob/59aa6a402d94dc9effed3931a028de1492ca88c9/reactor-core/src/main/java/reactor/core/publisher/Flux.java which brings the missing dependency

**Comment by aclement** [comment]
I have seen a situation or two where I've needed to add stuff to the classpath to make it native-image buildable when the app runs just fine regularly. Doing that felt wrong/odd, as if native-image was making a wrong decision (or at least non optimal decision). For now I'll try adding it and see how far I can get.

**Comment by eginez** [comment]
You are initializing a lot of classes at runtime in that example

**Comment by aclement** [comment]
I guess I was interpreting it as a build-time init setting would mean 'the bits of this class you determine we need should be initialized at build-time' but sounds like it is more subtle than that, interesting.

**Comment by aclement** [comment]
This looks like the project that keeps on giving, adding that dependency causes the next issue which I'm not quite sure how to deal with:
```

Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.mysql.cj.jdbc.ha.ReplicationConnectionProxy.createProxyInstance(com.mysql.cj.conf.ConnectionUrl)
Parsing context:
	parsing com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:209)
	parsing com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	parsing com.oracle.svm.reflect.DataSource_getConnection_accf695da61b46411dfdf4d0aa10229d00c8abe2_2708.invoke(Unknown Source)
	parsing java.lang.reflect.Method.invoke(Method.java:498)
...
Caused by: java.lang.IllegalArgumentException: interface com.mysql.cj.jdbc.ha.ReplicationConnection is not visible from class loader
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:581)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
	at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
	at java.lang.reflect.WeakCache.get(WeakCache.java:127)
	at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
	at java.lang.reflect.Proxy.getProxyClass(Proxy.java:371)
	at com.oracle.svm.core.jdk.proxy.DynamicProxyRegistry.getProxyClass(DynamicProxyRegistry.java:44)
	at com.oracle.svm.reflect.proxy.DynamicProxySupport.lambda$addProxyClass$0(DynamicProxySupport.java:94)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1688)
	at com.oracle.svm.reflect.proxy.DynamicProxySupport.addProxyClass(DynamicProxySupport.java:94)
	at com.oracle.svm.hosted.snippets.SubstrateGraphBuilderPlugins.interceptProxyInterfaces(SubstrateGraphBuilderPlugins.java:247)
```
Maybe it needs a separate tracker item? Again, the app is running perfectly fine with java -jar, it just seems native-image can't build it.

**Comment by eginez** [comment]
Hey @aclement I am trying to fix a patch for this issue but I am getting the following error
```
Fatal error:java.lang.IllegalStateException: java.lang.IllegalStateException: No @CompilationHint found for import selector: org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration$CacheConfigurationImportSelector
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:463)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:358)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:517)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:116)
Caused by: java.lang.IllegalStateException: No @CompilationHint found for import selector: org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration$CacheConfigurationImportSelector```

I pull your latest changes from the `extensible-configuration` branch

**Comment by sdeleuze** [comment]
I think you should use `master` since `extensible-configuration` has been merged in it and active development is on `master`. Also the artifact is now just `spring-native-graal` see updated documentation in https://github.com/spring-projects-experimental/spring-graal-native.

**Comment by eginez** [comment]
perfect I will try from master thanks @sdeleuze

**Comment by eginez** [comment]
https://github.com/oracle/graal/commit/69794db183e49551cc31b7c5aa122cd332c863f0 merges a fix for the above. The spring project no longer fails with the NullPointerException. Further for unlinked methods an error will be returned
