### ISSUE TITLE
allow reflection metadata for classes that reference undefined classes

### ISSUE THREAD

**Issue by pczmr8v5n454iycf** [oracle/graal#2207]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **[e.g. 19.3]** 20.0
 - CE or EE: **[e.g.: CE]** CE
 - Build Time or run time failure: **[eg run-time]** Build Time
 - JDK version: **[e.g.: JDK8]** JDK11
 
**Have you verified this issue still happens when using the latest snapshot?**
You can find snapshot builds here: https://github.com/graalvm/graalvm-ce-dev-builds/releases
no
**Describe the issue**
allow reflection metadata for classes that reference undefined classes

**Describe the full native-image command**

**Code snippet or code repository that reproduces the issue**

**Steps to reproduce the issue**

**Expected behavior**

**Additional context**
Add any other context about the problem here. Specially important are stack traces or log output. Feel free to link to gists or to screenshots if necesary

```
WARNING: Could not register reflection metadata for org.apache.logging.log4j.core.layout.JsonLayout. Reason: java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonGenerationException.
WARNING: Could not register reflection metadata for org.apache.logging.log4j.core.layout.CsvLogEventLayout. Reason: java.lang.NoClassDefFoundError: org/apache/commons/csv/CSVFormat.
WARNING: Could not register reflection metadata for org.apache.logging.log4j.core.layout.CsvParameterLayout. Reason: java.lang.NoClassDefFoundError: org/apache/commons/csv/CSVFormat.
WARNING: Could not register reflection metadata for org.apache.logging.log4j.core.layout.YamlLayout. Reason: java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonGenerationException.
WARNING: Could not register reflection metadata for org.apache.logging.log4j.core.async.JCToolsBlockingQueueFactory. Reason: java.lang.NoClassDefFoundError: org/jctools/queues/MpscArrayQueue.
WARNING: Could not register reflection metadata for org.apache.logging.log4j.core.layout.XmlLayout. Reason: java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonGenerationException.
...
```

**Comment by peter-hofer** [comment]
Thanks for your report @pczmr8v5n454iycf, can you provide a code example where this is a problem?

**Comment by pczmr8v5n454iycf** [comment]
@peter-hofer 
a example:

https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/c1fe16b0e9cb429260bf497fd6b9287157495fd4/worldedit-bukkit/src/main/java/com/sk89q/wepif/PermissionsResolverManager.java#L110
This line uses reflection to access a method of a class that may import a class that does not exist.
https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/c1fe16b0e9cb429260bf497fd6b9287157495fd4/worldedit-bukkit/src/main/java/com/sk89q/wepif/PermissionsExResolver.java#L42
If the imported class does not exist, it returns null in JVM. But in the native image, an error will be thrown on the previous line.

**Comment by peter-hofer** [comment]
@pczmr8v5n454iycf which are the "imported" classes in your example?

**Comment by pczmr8v5n454iycf** [comment]
@peter-hofer `ru.tehkode.permissions.PermissionManager`

**Comment by kristofdho** [comment]
I am running into the same issue, any update on this?

**Comment by peter-hofer** [comment]
Hi @kristofdho , can you please give more details on how this "crashes the image building" in https://github.com/gluonhq/client-maven-plugin/issues/200 and possibly provide a reproducing example? I have already revised the code you suspect to be at fault a while ago to be resilient against missing classes.

**Comment by peter-hofer** [comment]
@pczmr8v5n454iycf , I don't understand your example. So the `factory` method exists, but `PermissionManager` is not on the class path? And when this method is called in the JVM, it will return `null`? So what happens in a native-image build, or if the build fails, what is the output?

**Comment by pczmr8v5n454iycf** [comment]
an error will be thrown on this line since it's not registered: https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/c1fe16b0e9cb429260bf497fd6b9287157495fd4/worldedit-bukkit/src/main/java/com/sk89q/wepif/PermissionsResolverManager.java#L110

**Comment by kristofdho** [comment]
I am trying to figure out a small example for my issue (with the Object jni registration).
But as already mentioned, I am also running into the orriginal issue, and for that I do have a reproducible example:

file: `UndefinedReferencePoc.java`
```java
class UndefinedReferencePoc {
    public static void main(String[] args) throws Exception {
		Library lib = (Library)Class.forName(args[0]).getDeclaredConstructor().newInstance();
		lib.doStuff();
    }
}

interface Library {
	public void doStuff();
	public DeleteMe unused();
	public void unused2(DeleteMe d);
}

class LibraryImpl implements Library {
	public void doStuff() {
		System.out.println("Hello from LibraryImpl");
	}
	
	public DeleteMe unused() { return null; }
	public void unused2(DeleteMe d) {}
}

class DeleteMe {
}
```

file: `reflect-config.json`
```json
[
  {
    "name" : "LibraryImpl",
    "methods" : [
      {"name":"<init>","parameterTypes":[] }
    ]
  }
]
```

Steps to reproduce:
1. `javac UndefinedReferencePoc.java`
2. delete the `DeleteMe.class` file
3. run native-image: `native-image -H:Name=UndefinedReferencePoc -H:Class=UndefinedReferencePoc --verbose --no-fallback --allow-incomplete-classpath -H:ReflectionConfigurationResources=reflect-config.json`
4. Build contains a single warning: 
```
[UndefinedReferencePoc:37576]    classlist:   1,082.90 ms,  0.96 GB
[UndefinedReferencePoc:37576]        (cap):   1,901.77 ms,  0.96 GB
[UndefinedReferencePoc:37576]        setup:   3,716.32 ms,  0.96 GB
WARNING: Could not register reflection metadata for LibraryImpl. Reason: java.lang.NoClassDefFoundError: DeleteMe.
[UndefinedReferencePoc:37576]     (clinit):     184.87 ms,  1.20 GB
[UndefinedReferencePoc:37576]   (typeflow):   3,905.18 ms,  1.20 GB
[UndefinedReferencePoc:37576]    (objects):   3,465.75 ms,  1.20 GB
[UndefinedReferencePoc:37576]   (features):     229.58 ms,  1.20 GB
[UndefinedReferencePoc:37576]     analysis:   7,952.53 ms,  1.20 GB
[UndefinedReferencePoc:37576]     universe:     378.90 ms,  1.22 GB
[UndefinedReferencePoc:37576]      (parse):     745.56 ms,  1.22 GB
[UndefinedReferencePoc:37576]     (inline):     977.44 ms,  1.67 GB
[UndefinedReferencePoc:37576]    (compile):   4,777.54 ms,  2.25 GB
[UndefinedReferencePoc:37576]      compile:   6,914.18 ms,  2.25 GB
[UndefinedReferencePoc:37576]        image:     929.00 ms,  2.25 GB
[UndefinedReferencePoc:37576]        write:     323.54 ms,  2.25 GB
[UndefinedReferencePoc:37576]      [total]:  21,482.00 ms,  2.25 GB
```

- running from java:
```
 > java UndefinedReferencePoc LibraryImpl
Hello from LibraryImpl
```
- running the native image:
```
 > UndefinedReferencePoc.exe LibraryImpl
Exception in thread "main" java.lang.NoSuchMethodException: LibraryImpl.<init>()
        at java.lang.Class.getConstructor0(DynamicHub.java:3349)
        at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2553)
        at UndefinedReferencePoc.main(UndefinedReferencePoc.java:3)
```

From my observations it looks like running `getDeclaredMethod` on the class referencing the deleted class fails both on java & native-image as it looks like all references are resolved during that call, so it fails on the deleted class reference (which is presumably the whole reason native-image refuses to register the reflection metadata anyway).

But it looks like this is not applicable on reflective constructor lookups, so I would expect native-image to allow you to register constructors anyway to be conform with the expected result from java. If any other reflective lookup is performed, it's fine to crash at runtime (and show the warning) because that's also what the regular JVM does.

**Comment by kristofdho** [comment]
Upon further inspection, constructors can fail too if they contain references to non existing classes, and the warning is shown if one of these fail:
https://github.com/oracle/graal/blob/26431bf1b00dc23da5fbd8b89f02060f8cfd4811/substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/hosted/ReflectionDataBuilder.java#L256-L263

I think the correct way to handle this would be to check these individually, only if there is reflection config requires it, so calls that wouldn't fail at runtime, can be registered correctly.

**Comment by kristofdho** [comment]
I made a PR which implements this suggestion on my other account. #3037

**Comment by kristofdho** [comment]
As explained on #3058, that sort-of fixes my issue with the `Object#<init>` JNI registration. It is caused by a class being reachable through service-loading that can't be loaded due to missing classes on the classpath. I don't know the exact reason why it's not loadable as I don't have access to the source code.

The unloadable class is included as it's a subtype of Object, and the `getDeclaredMethods` call fails. I have already worked around the issue with the ServiceLoaderFeature exclusions.
But I'm guessing there are niche scenarios where this can still occur, and won't be fixed by #3058 either, for example if you register `Object#getClass` for JNI. So maybe it could be desirable to have some extra error handling around that part, for example not crashing on missing classes if --allow-incomplete-classpath is specified? In the end it's probably too niche and better to crash.

FYI, the problematic class is `com.sun.media.imageioimpl.plugins.tiff.TIFFCodecLibFaxDecompressor` from `javax.media:jai_imageio:1.1` crashing on missing class `com.sun.medialib.codec.g3fax.Decoder`. Any source code version I can find shouldn't pose any issues, but the compiled version does have issues so I don't know what is going on.
