### ISSUE TITLE
image-native build error

### ISSUE THREAD

**Issue by mjablecnik** [oracle/graal#2222]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: 19.3.1
 - CE or EE: CE
 - JDK version: jdk-11.0.2
 - OS and OS Version: Linux Mint 19.3 Tricia
 - Architecture: amd64
 - The output of `java -Xinternalversion`: 
```
OpenJDK 64-Bit Server VM (11.0.5+10-post-Ubuntu-0ubuntu1.118.04) for linux-amd64 JRE (11.0.5+10-post-Ubuntu-0ubuntu1.118.04), built on Oct 16 2019 22:01:07 by "buildd" with gcc 7.4.0
```

**Have you verified this issue still happens when using the latest snapshot?**
no

**Describe the issue**
cannot build native image

**Code snippet or code repository that reproduces the issue**
```
https://github.com/Applemann/Templates/tree/master/MicronautTemplate
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. git clone git@github.com:Applemann/Templates.git
2. cd Templates/MicronautTemplate
3. ./gradlew assemble
4. ./docker-build.sh

**Expected behavior**
Successfuly build GraalVM native-image and run it in docker container

**Additional context**
Here are output and stacktraces of my attempts:
<details><summary>RUN native-image --no-server --no-fallback -H:+ReportExceptionStackTraces --initialize-at-build-time=com.mysql.cj.jdbc.Driver -cp build/libs/micronaut-jdbi-*.jar</summary>

```
Step 5/10 : RUN native-image --no-server --no-fallback -H:+ReportExceptionStackTraces --initialize-at-build-time=com.mysql.cj.jdbc.Driver -cp build/libs/micronaut-jdbi-*.jar
 ---> Running in 11c17abd063b
Warning: Using a deprecated option --rerun-class-initialization-at-runtime. Currently there is no replacement for this option. Try using --initialize-at-run-time or use the non-API option -H:ClassInitialization directly.
Warning: Using a deprecated option --delay-class-initialization-to-runtime. Use --initialize-at-run-time.
Warning: Using a deprecated option --delay-class-initialization-to-runtime. Use --initialize-at-run-time.
Warning: Using a deprecated option --delay-class-initialization-to-runtime. Use --initialize-at-run-time.
[micronaut-graal-app:25]    classlist:   9,790.14 ms,  1.86 GB
[micronaut-graal-app:25]        (cap):   1,189.57 ms,  1.86 GB
[micronaut-graal-app:25]        setup:   3,924.78 ms,  1.86 GB
[micronaut-graal-app:25]     analysis:  65,273.50 ms,  9.00 GB
Error: Classes that should be initialized at run time got initialized during image building:
 com.mysql.cj.jdbc.AbandonedConnectionCleanupThread was unintentionally initialized at build time. To see why com.mysql.cj.jdbc.AbandonedConnectionCleanupThread got initialized use -H:+TraceClassInitialization

com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 com.mysql.cj.jdbc.AbandonedConnectionCleanupThread was unintentionally initialized at build time. To see why com.mysql.cj.jdbc.AbandonedConnectionCleanupThread got initialized use -H:+TraceClassInitialization

        at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
        at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:510)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:187)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:715)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:715)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1
The command '/bin/sh -c native-image --no-server --no-fallback -H:+ReportExceptionStackTraces --initialize-at-build-time=com.mysql.cj.jdbc.Driver -cp build/libs/micronaut-jdbi-*.jar' returned a non-zero code: 1

```
</details>
<details><summary>RUN native-image --no-server --no-fallback -H:+ReportExceptionStackTraces --initialize-at-build-time=com.mysql.cj.jdbc.Driver,com.mysql.cj.jdbc.AbandonedConnectionCleanupThread -cp build/libs/micronaut-jdbi-*.jar</summary>

```
Step 5/10 : RUN native-image --no-server --no-fallback -H:+ReportExceptionStackTraces --initialize-at-build-time=com.mysql.cj.jdbc.Driver,com.mysql.cj.jdbc.AbandonedConnectionCleanupThread -cp build/libs/micronaut-jdbi-*.jar
 ---> Running in cfff2a70e7c2
Warning: Using a deprecated option --rerun-class-initialization-at-runtime. Currently there is no replacement for this option. Try using --initialize-at-run-time or use the non-API option -H:ClassInitialization directly.
Warning: Using a deprecated option --delay-class-initialization-to-runtime. Use --initialize-at-run-time.
Warning: Using a deprecated option --delay-class-initialization-to-runtime. Use --initialize-at-run-time.
Warning: Using a deprecated option --delay-class-initialization-to-runtime. Use --initialize-at-run-time.
[micronaut-graal-app:24]    classlist:  11,174.86 ms,  1.84 GB
[micronaut-graal-app:24]        (cap):   1,144.54 ms,  1.84 GB
[micronaut-graal-app:24]        setup:   3,920.65 ms,  1.84 GB
[micronaut-graal-app:24]   (typeflow): 110,216.78 ms, 13.38 GB
[micronaut-graal-app:24]    (objects): 102,925.77 ms, 13.38 GB
[micronaut-graal-app:24]   (features):   5,527.76 ms, 13.38 GB
[micronaut-graal-app:24]     analysis: 227,191.42 ms, 13.38 GB
Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image run time.  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
        reading field com.mysql.cj.jdbc.AbandonedConnectionCleanupThread.threadRef

com.oracle.svm.core.util.UserError$UserException: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image run time.  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
        reading field com.mysql.cj.jdbc.AbandonedConnectionCleanupThread.threadRef

        at com.oracle.svm.core.util.UserError.abort(UserError.java:79)
        at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:221)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:741)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image run time.  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
        reading field com.mysql.cj.jdbc.AbandonedConnectionCleanupThread.threadRef

        at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:738)
        ... 8 more
Error: Image build request failed with exit status 1
The command '/bin/sh -c native-image --no-server --no-fallback -H:+ReportExceptionStackTraces --initialize-at-build-time=com.mysql.cj.jdbc.Driver,com.mysql.cj.jdbc.AbandonedConnectionCleanupThread -cp build/libs/micronaut-jdbi-*.jar' returned a non-zero code: 1

```
</details>

<details><summary>RUN native-image --no-server --no-fallback -H:+ReportExceptionStackTraces --initialize-at-build-time=com.mysql.cj.jdbc.Driver,com.mysql.cj.jdbc.AbandonedConnectionCleanupThread --initialize-at-run-time=com.mysql.cj.jdbc.AbandonedConnectionCleanupThread.threadRef -cp build/libs/micronaut-jdbi-*.jar</summary>

```
Step 5/10 : RUN native-image --no-server --no-fallback -H:+ReportExceptionStackTraces --initialize-at-build-time=com.mysql.cj.jdbc.Driver,com.mysql.cj.jdbc.AbandonedConnectionCleanupThread --initialize-at-run-time=com.mysql.cj.jdbc.AbandonedConnectionCleanupThread.threadRef -cp build/libs/micronaut-jdbi-*.jar
 ---> Running in 390fccb3df95
Warning: Using a deprecated option --rerun-class-initialization-at-runtime. Currently there is no replacement for this option. Try using --initialize-at-run-time or use the non-API option -H:ClassInitialization directly.
Warning: Using a deprecated option --delay-class-initialization-to-runtime. Use --initialize-at-run-time.
Warning: Using a deprecated option --delay-class-initialization-to-runtime. Use --initialize-at-run-time.
Warning: Using a deprecated option --delay-class-initialization-to-runtime. Use --initialize-at-run-time.
[micronaut-graal-app:25]    classlist:   9,925.67 ms,  1.59 GB
[micronaut-graal-app:25]        (cap):   1,267.16 ms,  1.59 GB
[micronaut-graal-app:25]        setup:   3,819.12 ms,  1.59 GB
[micronaut-graal-app:25]   (typeflow): 110,588.89 ms, 13.33 GB
[micronaut-graal-app:25]    (objects): 109,086.67 ms, 13.33 GB
[micronaut-graal-app:25]   (features):   5,356.90 ms, 13.33 GB
[micronaut-graal-app:25]     analysis: 235,766.38 ms, 13.33 GB
Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image run time.  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
        reading field com.mysql.cj.jdbc.AbandonedConnectionCleanupThread.threadRef

com.oracle.svm.core.util.UserError$UserException: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image run time.  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
        reading field com.mysql.cj.jdbc.AbandonedConnectionCleanupThread.threadRef

        at com.oracle.svm.core.util.UserError.abort(UserError.java:79)
        at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:221)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:741)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image run time.  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
        reading field com.mysql.cj.jdbc.AbandonedConnectionCleanupThread.threadRef

        at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:738)
        ... 8 more
Error: Image build request failed with exit status 1
The command '/bin/sh -c native-image --no-server --no-fallback -H:+ReportExceptionStackTraces --initialize-at-build-time=com.mysql.cj.jdbc.Driver,com.mysql.cj.jdbc.AbandonedConnectionCleanupThread --initialize-at-run-time=com.mysql.cj.jdbc.AbandonedConnectionCleanupThread.threadRef -cp build/libs/micronaut-jdbi-*.jar' returned a non-zero code: 1

```
</details>
<details><summary>RUN native-image --no-server --no-fallback -H:+ReportExceptionStackTraces --initialize-at-build-time=com.mysql.cj.jdbc.Driver--initialize-at-run-time=com.mysql.cj.jdbc.AbandonedConnectionCleanupThread -cp build/libs/micronaut-jdbi-*.jar</summary>

```
Step 5/10 : RUN native-image --no-server --no-fallback -H:+ReportExceptionStackTraces --initialize-at-build-time=com.mysql.cj.jdbc.Driver--initialize-at-run-time=com.mysql.cj.jdbc.AbandonedConnectionCleanupThread -cp build/libs/micronaut-jdbi-*.jar
 ---> Running in 7e1e4bf19bca
Warning: Using a deprecated option --rerun-class-initialization-at-runtime. Currently there is no replacement for this option. Try using --initialize-at-run-time or use the non-API option -H:ClassInitialization directly.
Warning: Using a deprecated option --delay-class-initialization-to-runtime. Use --initialize-at-run-time.
Warning: Using a deprecated option --delay-class-initialization-to-runtime. Use --initialize-at-run-time.
Warning: Using a deprecated option --delay-class-initialization-to-runtime. Use --initialize-at-run-time.
[micronaut-graal-app:24]    classlist:   9,658.25 ms,  1.62 GB
[micronaut-graal-app:24]        (cap):   1,172.53 ms,  1.62 GB
[micronaut-graal-app:24]        setup:   3,821.65 ms,  1.62 GB
[micronaut-graal-app:24]   (typeflow): 112,739.80 ms, 13.19 GB
[micronaut-graal-app:24]    (objects): 103,320.87 ms, 13.19 GB
[micronaut-graal-app:24]   (features):   5,150.69 ms, 13.19 GB
[micronaut-graal-app:24]     analysis: 230,961.15 ms, 13.19 GB
[micronaut-graal-app:24]     (clinit):   3,693.62 ms, 13.19 GB
[micronaut-graal-app:24]     universe:  10,866.79 ms, 13.19 GB
[micronaut-graal-app:24]      (parse):  17,384.31 ms, 13.38 GB
[micronaut-graal-app:24]     (inline):   9,772.06 ms, 13.46 GB
[micronaut-graal-app:24]    (compile): 107,442.95 ms, 13.46 GB
[micronaut-graal-app:24]      compile: 142,148.80 ms, 13.46 GB
[micronaut-graal-app:24]        image:  15,216.99 ms, 13.46 GB
Fatal error: com.oracle.svm.core.util.VMError$HostedError: java.lang.NoClassDefFoundError: Lorg/codehaus/janino/ScriptEvaluator;
        at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:70)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:641)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NoClassDefFoundError: Lorg/codehaus/janino/ScriptEvaluator;
        at java.base/java.lang.Class.getDeclaredFields0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3061)
        at java.base/java.lang.Class.getDeclaredField(Class.java:2409)
        at com.oracle.graal.pointsto.infrastructure.OriginalFieldProvider.getJavaField(OriginalFieldProvider.java:43)
        at com.oracle.graal.pointsto.meta.AnalysisField.getJavaField(AnalysisField.java:420)
        at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readUninitializedStaticValue(AnalysisConstantReflectionProvider.java:136)
        at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:87)
        at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:77)
        at com.oracle.svm.hosted.meta.HostedField.readValue(HostedField.java:156)
        at com.oracle.svm.hosted.image.NativeImageHeapWriter.writeField(NativeImageHeapWriter.java:136)
        at com.oracle.svm.hosted.image.NativeImageHeapWriter.writeStaticFields(NativeImageHeapWriter.java:110)
        at com.oracle.svm.hosted.image.NativeImageHeapWriter.writeHeap(NativeImageHeapWriter.java:92)
        at com.oracle.svm.hosted.image.NativeBootImage.build(NativeBootImage.java:472)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:630)
        ... 7 more
Caused by: java.lang.ClassNotFoundException: org.codehaus.janino.ScriptEvaluator
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 21 more
Error: Image build request failed with exit status 1
The command '/bin/sh -c native-image --no-server --no-fallback -H:+ReportExceptionStackTraces --initialize-at-build-time=com.mysql.cj.jdbc.Driver--initialize-at-run-time=com.mysql.cj.jdbc.AbandonedConnectionCleanupThread -cp build/libs/micronaut-jdbi-*.jar' returned a non-zero code: 1
```
</details>

**Comment by Applemann** [comment]
I resolved it by: https://github.com/oracle/graal/issues/1943#issuecomment-580681513
But now when I want run it I have:
```
martin at probook-pc MicronautTemplate >>> docker run -p 8080:8080 micronaut-graal-app
/micronaut-graal-app/micronaut-graal-app: /usr/lib/libstdc++.so.6: no version information available (required by /micronaut-graal-app/micronaut-graal-app)
15:22:35,407 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
15:22:35,407 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
15:22:35,407 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [resource:logback.xml]
15:22:35,407 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@7f9a8f703fa0 - URL [resource:logback.xml] is not of type file
15:22:35,409 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
15:22:35,410 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
15:22:35,410 |-ERROR in ch.qos.logback.core.joran.action.AppenderAction - Could not create an Appender of type [ch.qos.logback.core.ConsoleAppender]. ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.core.ConsoleAppender
        at ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.core.ConsoleAppender
        at      at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:69)
        at      at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:45)
        at      at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:34)
        at      at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:52)
        at      at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:269)
        at      at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:145)
        at      at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:128)
        at      at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
        at      at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
        at      at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
        at      at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
        at      at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
        at      at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
        at      at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
        at      at java.lang.Class.ensureInitialized(DynamicHub.java:496)
        at      at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
        at      at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at      at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
        at      at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
        at      at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
        at      at io.micronaut.runtime.Micronaut.<clinit>(Micronaut.java:46)
        at      at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
        at      at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
        at      at java.lang.Class.ensureInitialized(DynamicHub.java:496)
        at      at micronaut.jdbi.Application.main(Application.kt:9)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.core.ConsoleAppender
        at      at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
        at      at java.lang.ClassLoader.loadClass(ClassLoader.java:229)
        at      at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:56)
        at      ... 28 common frames omitted
15:22:35,410 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@3:73 - ActionException in Action for tag [appender] ch.qos.logback.core.joran.spi.ActionException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.core.ConsoleAppender
        at ch.qos.logback.core.joran.spi.ActionException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.core.ConsoleAppender
        at      at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:76)
        at      at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:269)
        at      at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:145)
        at      at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:128)
        at      at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
        at      at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
        at      at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
        at      at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
        at      at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
        at      at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
        at      at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
        at      at java.lang.Class.ensureInitialized(DynamicHub.java:496)
        at      at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
        at      at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at      at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
        at      at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
        at      at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
        at      at io.micronaut.runtime.Micronaut.<clinit>(Micronaut.java:46)
        at      at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
        at      at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
        at      at java.lang.Class.ensureInitialized(DynamicHub.java:496)
        at      at micronaut.jdbi.Application.main(Application.kt:9)
Caused by: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.core.ConsoleAppender
        at      at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:69)
        at      at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:45)
        at      at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:34)
        at      at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:52)
        at      ... 25 common frames omitted
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.core.ConsoleAppender
        at      at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
        at      at java.lang.ClassLoader.loadClass(ClassLoader.java:229)
        at      at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:56)
        at      ... 28 common frames omitted
15:22:35,410 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
15:22:35,410 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - Could not find an appender named [STDOUT]. Did you define it below instead of above in the configuration file?
15:22:35,410 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - See http://logback.qos.ch/codes.html#appender_order for more details.
15:22:35,410 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [io.micronaut.http.server.netty.NettyHttpServer] to DEBUG
15:22:35,410 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
15:22:35,410 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@7f9a8f703f60 - Registering current configuration as safe fallback point

Mar 05, 2020 3:22:35 PM com.fasterxml.jackson.databind.ext.Java7Support <clinit>
WARNING: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added

```

**Comment by daddykotex** [comment]
I'm writing here as a way to bump this issue and maybe check with the authors if they found a solution workaround. Logging frameworks are a pain to work with in Graal and I've managed to finally compile a somewhat complex application.

But upon execution, I have the same error as described in https://github.com/oracle/graal/issues/2222#issuecomment-595288448 (above).

**Comment by daddykotex** [comment]
I have found a solution. Graal comes with a tracing agrnt that you can use to generate configuration file to specify what classes to include at runtime because they're used via reflection (reflect-config.json).

I did that and the ConsoleAppender was in the list. In the following build, the error described above did not happen.

**Comment by cstancu** [comment]
@daddykotex thanks for sharing your solution.
