### ISSUE TITLE
java.awt.event.KeyEvent.getKeyText() throws UnsupportedFeatureError

### ISSUE THREAD

**Issue by pczmr8v5n454iycf** [oracle/graal#2223]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **[e.g. 19.3]** 20.0
 - CE or EE: **[e.g.: CE]** CE
 - Build Time or run time failure: **[eg run-time]** run-time
 - JDK version: **[e.g.: JDK8]** JDK11
 - Native compiler information:<details><summary>Run the following to capture compiler version</summary>
   - In windows: `cl.exe`
   - In macOS : `cc -v`
   - In Linux: `gcc --version`
</details>

```
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6) 
```
 - Native linker information:<details><summary>Run the following to capture linker version</summary>
   - In windows: `cl.exe`
   - In macOS : `cc -Wl,-v`
   - In Linux: `gcc -Wl,--version`
</details>

```
collect2 version 8.3.0
/usr/bin/ld -plugin /usr/lib/gcc/x86_64-linux-gnu/8/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper -plugin-opt=-fresolution=/tmp/ccsLIPxX.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/8/crtbeginS.o -L/usr/lib/gcc/x86_64-linux-gnu/8 -L/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/8/../../.. --version -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-linux-gnu/8/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/crtn.o
GNU ld (GNU Binutils for Debian) 2.31.1
Copyright (C) 2018 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```
 - OS and OS Version: **[e.g. macOS Catalina]** Debian 10
 - Architecture: **[e.g.: AMD64]** AMD64
 - The output of `java -Xinternalversion`: 
```
OpenJDK 64-Bit Server VM (11.0.6+9-jvmci-20.0-b02) for linux-amd64 JRE (11.0.6+9-jvmci-20.0-b02), built on Jan 20 2020 20:06:41 by "buildslave" with gcc 7.3.0
```

**Have you verified this issue still happens when using the latest snapshot?**
You can find snapshot builds here: https://github.com/graalvm/graalvm-ce-dev-builds/releases
no

**Describe the issue**
java.awt.event.KeyEvent.getKeyText() throws UnsupportedFeatureError

**Describe the full native-image command**

**Code snippet or code repository that reproduces the issue**
```
java.awt.event.KeyEvent.getKeyText(...)
```

**Steps to reproduce the issue**

**Expected behavior**
no UnsupportedFeatureError

**Additional context**
logs:
<details><summary>Details</summary>

```
com.oracle.svm.core.jdk.UnsupportedFeatureError: Resource bundle lookup must be loaded during native image generation: sun.awt.resources.awt
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:101) ~[?:?]
	at java.util.ListResourceBundle.loadLookup(ListResourceBundle.java:105) ~[?:?]
	at java.util.ListResourceBundle.handleGetObject(ListResourceBundle.java:130) ~[?:?]
	at java.util.ResourceBundle.getObject(ResourceBundle.java:555) ~[?:?]
	at java.util.ResourceBundle.getString(ResourceBundle.java:521) ~[?:?]
	at java.awt.Toolkit.getProperty(Toolkit.java:1451) ~[?:?]
	at java.awt.event.KeyEvent.getKeyText(KeyEvent.java:1403) ~[?:?]

```
</details>

**Comment by fjwbarnard** [comment]
From your code snippet I notice Java AWT. Anything based on AWT such as Swing apps do not work with GraalVM native-image currently - see https://github.com/oracle/graal/issues/1327#issuecomment-548087243  

They do plan to support it, but it certainly is not high on the priority list: https://github.com/oracle/graal/issues/1327#issuecomment-587087553

**Comment by pczmr8v5n454iycf** [comment]
It is a CLI application that uses a AWT API.
