### ISSUE TITLE
OutOfMemoryError is sometimes reported as PolyglotException.isInternalError()

### ISSUE THREAD

**Issue by tporeba** [oracle/graal#2307]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **19.3.1**
 - CE or EE: **CE**
 - JDK version: **JDK11**
 - OS and OS Version: **Windows / Linux**
 - Architecture: **x64**
 - The output of `java -Xinternalversion`:
```
OpenJDK 64-Bit Server VM (11.0.6+9-jvmci-19.3-b07) for linux-amd64 JRE (11.0.6+9-jvmci-19.3-b07), built on Jan 13 2020 20:43:28 by "buildslave" with gcc 7.3.0
```

**Have you verified this issue still happens when using the latest snapshot?**
Yes, reproducible

**Describe the issue**
I was investigating how my app behaves in case of errors thrown from polyglot graal.js scripts with particular interest in `OutOfMemory` errors. OOM is wrapped in `PolyglotException`, which is fine. I expected it to be an instance where `isHostException` is true, but sometimes I get an instance where `isHostException` is false, but instead `isInternalError` is true. 

This is a bit confusing, especially that `PolyglotException` javadoc says that `isInternalError` is reserved for programming errors.

**Code snippet or code repository that reproduces the issue**
From https://github.com/graalvm/graaljs/blob/master/docs/user/JavaInterop.md
```
//Rhino pattern
var JArray = Java.type('java.lang.reflect.Array');
var JString = Java.type('java.lang.String');
var sarr = JArray.newInstance(JString, 2147483647);
```

<details><summary>Rhino style OOM is reported as host exception</summary>

```
Requested array size exceeds VM limit
	at java.base/java.lang.reflect.Array.newArray(Native Method)
	at java.base/java.lang.reflect.Array.newInstance(Array.java:78)
	at java.base/java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(DirectMethodHandle$Holder)
	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000840266440.invoke(LambdaForm$MH)
	at java.base/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
	at <js> :program(Unnamed:22:636-674)
Caused by host exception: java.lang.OutOfMemoryError: Requested array size exceeds VM limit
```

</details>

```
//Nashorn pattern
var IntArray = Java.type("int[]");
var iarr = new IntArray(2147483647);
```

<details><summary>Nashorn style OOM is reported as internal error</summary>

```
Exception in thread "main" org.graalvm.polyglot.PolyglotException: java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at java.base/java.lang.reflect.Array.newArray(Native Method)
	at java.base/java.lang.reflect.Array.newInstance(Array.java:78)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObject$Instantiate.doArrayCached(HostObject.java:685)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObjectGen$InteropLibraryExports$Cached.instantiateAndSpecialize(HostObjectGen.java:2278)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObjectGen$InteropLibraryExports$Cached.instantiate(HostObjectGen.java:2239)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibrary$Asserts.instantiate(InteropLibrary.java:1325)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.instantiate(InteropLibraryGen.java:5986)
	at com.oracle.truffle.js.nodes.function.JSNewNode.doNewForeignObject(JSNewNode.java:239)
	at com.oracle.truffle.js.nodes.function.JSNewNodeGen.executeAndSpecialize(JSNewNodeGen.java:273)
	at com.oracle.truffle.js.nodes.function.JSNewNodeGen.execute(JSNewNodeGen.java:163)
	at com.oracle.truffle.js.nodes.access.WritePropertyNode.executeAndSpecialize(WritePropertyNode.java:251)
	at com.oracle.truffle.js.nodes.access.WritePropertyNode.executeVoid(WritePropertyNode.java:221)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:91)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:74)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:91)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:84)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:147)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:93)
Original Internal Error: 
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at java.base/java.lang.reflect.Array.newArray(Native Method)
	at java.base/java.lang.reflect.Array.newInstance(Array.java:78)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObject$Instantiate.doArrayCached(HostObject.java:685)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObjectGen$InteropLibraryExports$Cached.instantiateAndSpecialize(HostObjectGen.java:2278)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObjectGen$InteropLibraryExports$Cached.instantiate(HostObjectGen.java:2239)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibrary$Asserts.instantiate(InteropLibrary.java:1325)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.instantiate(InteropLibraryGen.java:5986)
	at com.oracle.truffle.js.nodes.function.JSNewNode.doNewForeignObject(JSNewNode.java:239)
	at com.oracle.truffle.js.nodes.function.JSNewNodeGen.executeAndSpecialize(JSNewNodeGen.java:273)
	at com.oracle.truffle.js.nodes.function.JSNewNodeGen.execute(JSNewNodeGen.java:163)
	at com.oracle.truffle.js.nodes.access.WritePropertyNode.executeAndSpecialize(WritePropertyNode.java:251)
	at com.oracle.truffle.js.nodes.access.WritePropertyNode.executeVoid(WritePropertyNode.java:221)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:91)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:74)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:91)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:84)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:147)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:93)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:348)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:338)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:325)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:307)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:256)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:64)
	at com.oracle.truffle.js.lang.JavaScriptLanguage$1.execute(JavaScriptLanguage.java:227)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:348)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:338)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:325)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:307)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:244)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:231)
```

</details>

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Run an app that executes one of graal.js snippets from above

**Expected behavior**
I would expect that `java.lang.Error`s like OOM to be reported consistently as host exceptions, or at least in a consistent way that allows to identify them and rethrow the original error. Now I need to treat every PolyglotException with `isInternalError` flag as potentially fatal for my app, which looks like an overkill.

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-23075.

**Comment by chumer** [comment]
Errors that happen as part of guest code execution are guest errors. Errors that happen as part of host code execution are host errors. So OOM errors are not necessarily host errors.

OOM should never be an internal error. As internal errors are always bugs on our side, but in this case it is a problem in the script.

I suggest we add a new category of errors in PolyglotException. First thing I can think of is:
```
public boolean isLimitExceeded();
```
It would be true if any of the host limits would be triggered. You could find out whether they triggered on the host or guest side by using PolyglotException#isGuestException ans isHostException.

What do you think?

**Comment by tporeba** [comment]
> What do you think?

Looks fine for me.

**Comment by chumer** [comment]
In 20.2 there will be `PolyglotException.isResourceExhausted()`.
Javadoc: https://www.graalvm.org/sdk/javadoc/org/graalvm/polyglot/PolyglotException.html#isResourceExhausted--
