### ISSUE TITLE
CFGPrinter: ArrayIndexOutOfBoundsException for trivial Java program

### ISSUE THREAD

**Issue by sighingnow** [oracle/graal#2315]
**Describe the issue**

CFGPrinter doesn't work as expected for trivial Java program.

HelloWorld.java

```java
public class HelloWorld {
  public static void main(String[] args) {
    System.out.println("Hello, World!");

    int x = 1;
    for (int i = 1; i < 100000000; ++i) {
        x *= 2 * i;
    }

  }
}
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. `javac HelloWorld.java`
2. `java -Dgraal.Dump -Dgraal.PrintCFG=true -XX:+UseJVMCICompiler HelloWorld`

**Describe GraalVM and your environment:**
 - GraalVM version: GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
 - JDK major version: 11
 - OS: macOS Catalina
 - Architecture: AMD64]

The stack trace:

```
Hello, World!
[Use -Dgraal.LogFile=<path> to redirect Graal log output to a file.]
Dumping IGV graphs in ~/graal-expr/graal_dumps/2020.04.02.01.35.46.210
CFGPrinter: Exception during output of After high tier: java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 7
java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 7
	at org.graalvm.compiler.graph.NodeMap.get(NodeMap.java:54)
	at org.graalvm.compiler.printer.CFGPrinter.inFixedSchedule(CFGPrinter.java:157)
	at org.graalvm.compiler.printer.CFGPrinter.schedule(CFGPrinter.java:221)
	at org.graalvm.compiler.printer.CFGPrinter.scheduleInputs(CFGPrinter.java:215)
	at org.graalvm.compiler.printer.CFGPrinter.printCFG(CFGPrinter.java:177)
	at org.graalvm.compiler.printer.CFGPrinterObserver.dumpSandboxed(CFGPrinterObserver.java:220)
	at org.graalvm.compiler.printer.CFGPrinterObserver.dump(CFGPrinterObserver.java:85)
	at org.graalvm.compiler.debug.ScopeImpl.dump(ScopeImpl.java:223)
	at org.graalvm.compiler.debug.DebugContext.dump(DebugContext.java:1200)
	at org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:222)
	at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:144)
	at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:129)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileHelper(HotSpotGraalCompiler.java:227)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:245)
	at org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:170)
	at org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:84)
	at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:179)
	at org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:334)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:144)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:109)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:697)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST_Nonvirtual:Ljdk_vm_ci_hotspot_HotSpotJVMCIRuntime_2_0002ecompileMethod_00028Ljdk_vm_ci_hotspot_HotSpotResolvedJavaMethod_2IJI_00029Ljdk_vm_ci_hotspot_HotSpotCompilationRequestResult_2(JNIJavaCallWrappers.java:0)
```

**Comment by wirthi** [comment]
That was likely some bug the team has already fixed. I tried with two different recent version (22.2 EE and 22.1 CE), it worked with both without any issues.

I am closing this issue. If you can reproduce on a recent version, please reopen and let us know.
