### ISSUE TITLE
Code installation failed: code is too large

### ISSUE THREAD

**Issue by rbotafogo** [oracle/graal#2329]
**Describe GraalVM and your environment :**
 - GraalVM-ce-java11-20.0.0
 - CE
 - JDK version: 11
 - OS Ubuntu 18.04
 - amd64
 - The output of `java -Xinternalversion`: OpenJDK 64-Bit Server VM (11.0.6+9-jvmci-20.0-b02) for linux-amd64 JRE (11.0.6+9-jvmci-20.0-b02), built on Jan 20 2020 20:06:41 by "buildslave" with gcc 7.3.0

[truffle] opt fail         calc_element                                                |ASTSize           961 |Reason jdk.vm.ci.code.BailoutException: Code installation failed: code is too large 
jdk.vm.ci.code.BailoutException: Code installation failed: code is too large
	at jdk.vm.ci.hotspot.HotSpotCodeCacheProvider.installCode(HotSpotCodeCacheProvider.java:150)
	at org.graalvm.compiler.core.target.Backend.createInstalledCode(Backend.java:194)
	at org.graalvm.compiler.core.target.Backend.createInstalledCode(Backend.java:147)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compilePEGraph(TruffleCompilerImpl.java:552)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compileAST(TruffleCompilerImpl.java:481)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:660)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:598)
	at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:179)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.actuallyCompile(TruffleCompilerImpl.java:308)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.doCompile(TruffleCompilerImpl.java:259)
	at org.graalvm.compiler.truffle.compiler.hotspot.libgraal.HotSpotToSVMEntryPoints.doCompile(HotSpotToSVMEntryPoints.java:269)

**Comment by fniephaus** [comment]
Steps to reproduce would be helpful, as well as the language(s) you're using. Where does "calc_element" come from?

**Comment by boris-spas** [comment]
As @fniephaus pointed out, more information is needed to make this report actionable. 
I'm closing the issue but will gladly reopen if more information is provided.
