### ISSUE TITLE
Agent missed reflections in clinit 

### ISSUE THREAD

**Issue by ziyilin** [oracle/graal#2335]
**Describe the issue**
Agent intercepts java.lang.Class.forName method and executes _forName(className, **true**, classloader)_ inside Agent. If there are other reflection, resource, proxy or jni calls in the target class' static initializer, Agent will miss them and lead to native-image runtime failure.
This issue can be fixed by this proposed PR https://github.com/oracle/graal/pull/2334
**Steps to reproduce the issue**
This test can easily reproduce the issue:
```
/*
 * Copyright (c) 2020 Alibaba Group Holding Limited. All Rights Reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation. Alibaba designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 */
package test.reflect;

import java.lang.reflect.InvocationTargetException;

/**
 * $GRAALVM_HOME/bin/java -cp bin -agentlib:native-image-agent=config-output-dir=config-complexCL/META-INF/native-image test.reflect.TestComplexClassInitializer
 * $GRAALVM_HOME/bin/native-image -cp out/production/staticmodel:config-complexCL test.reflect.TestComplexClassInitializer
 * ./test.reflect.testcomplexclassinitializer
 */
public class TestComplexClassInitializer {

    static String name = "test.reflect.ComplexCL";

    public static void main(String[] args) throws NoSuchMethodException, ClassNotFoundException {
        Class<?> cl = Class.forName(name);
        System.out.println(ComplexCL.obj.toString());
    }

    public static String getRefName(){
        return "test.reflect.TestA";
    }
}

class ComplexCL{
    static Object obj;
    static {
        try {
            Class clazz = Class.forName(TestComplexClassInitializer.getRefName());
            obj=clazz.getConstructor().newInstance();
        } catch (ClassNotFoundException | NoSuchMethodException | InstantiationException | IllegalAccessException | InvocationTargetException e) {
            e.printStackTrace();
        }
    }
}

class TestA{

    public  TestA(){}

    @Override
    public String toString(){
        return "This is TestA";
    }
}

```
A more realistic example is from SPECjvm2008's derby benchmark, the above test is simplified from this case:
```
XBM01.D :
ERROR XBM01: XBM01.D :
        at org.apache.derby.iapi.services.monitor.Monitor.exceptionStartingModule(Monitor.java:669)
        at org.apache.derby.impl.services.monitor.ProtocolKey.create(ProtocolKey.java:70)
        at org.apache.derby.impl.services.monitor.BaseMonitor.startModule(BaseMonitor.java:542)
        at org.apache.derby.iapi.services.monitor.Monitor.startSystemModule(Monitor.java:366)
        at org.apache.derby.impl.services.monitor.BaseMonitor.runWithState(BaseMonitor.java:364)
        at org.apache.derby.impl.services.monitor.FileMonitor.<init>(FileMonitor.java:60)
        at org.apache.derby.iapi.services.monitor.Monitor.startMonitor(Monitor.java:289)
        at org.apache.derby.iapi.jdbc.JDBCBoot.boot(JDBCBoot.java:69)
        at org.apache.derby.jdbc.EmbeddedDriver.boot(EmbeddedDriver.java:201)
        at org.apache.derby.jdbc.EmbeddedDriver.<clinit>(EmbeddedDriver.java:96)
        at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
        at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
        at java.lang.Class.ensureInitialized(DynamicHub.java:504)
        at spec.benchmarks.derby.DerbyHarness.initDatabases(DerbyHarness.java:232)
        at spec.benchmarks.derby.Main.setupBenchmark(Main.java:99)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at spec.harness.SpecJVMBenchmarkBase.runSimple(SpecJVMBenchmarkBase.java:124)
        at spec.benchmarks.derby.Main.main(Main.java:134)
Caused by: java.lang.ClassNotFoundException: org.apache.derby.iapi.services.stream.InfoStreams
        at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
        at java.lang.Class.forName(DynamicHub.java:1237)
        at org.apache.derby.impl.services.monitor.ProtocolKey.create(ProtocolKey.java:64)
        ... 16 more
============= begin nested exception, level (1) ===========
java.lang.ClassNotFoundException: org.apache.derby.iapi.services.stream.InfoStreams
        at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
        at java.lang.Class.forName(DynamicHub.java:1237)
        at org.apache.derby.impl.services.monitor.ProtocolKey.create(ProtocolKey.java:64)
        at org.apache.derby.impl.services.monitor.BaseMonitor.startModule(BaseMonitor.java:542)
        at org.apache.derby.iapi.services.monitor.Monitor.startSystemModule(Monitor.java:366)
        at org.apache.derby.impl.services.monitor.BaseMonitor.runWithState(BaseMonitor.java:364)
        at org.apache.derby.impl.services.monitor.FileMonitor.<init>(FileMonitor.java:60)
        at org.apache.derby.iapi.services.monitor.Monitor.startMonitor(Monitor.java:289)
        at org.apache.derby.iapi.jdbc.JDBCBoot.boot(JDBCBoot.java:69)
        at org.apache.derby.jdbc.EmbeddedDriver.boot(EmbeddedDriver.java:201)
        at org.apache.derby.jdbc.EmbeddedDriver.<clinit>(EmbeddedDriver.java:96)
        at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
        at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
        at java.lang.Class.ensureInitialized(DynamicHub.java:504)
        at spec.benchmarks.derby.DerbyHarness.initDatabases(DerbyHarness.java:232)
        at spec.benchmarks.derby.Main.setupBenchmark(Main.java:99)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at spec.harness.SpecJVMBenchmarkBase.runSimple(SpecJVMBenchmarkBase.java:124)
        at spec.benchmarks.derby.Main.main(Main.java:134)
============= end nested exception, level (1) ===========

```
**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **[e.g. EE 19.3, CE 20.0, CE 20.1.0-dev-20200304_0848]**
 - JDK major version: **[e.g.:8]**
 - OS: **[e.g. macOS Catalina]**
 - Architecture: **[e.g.: AMD64]**

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
    PASTE YOUR LOG/STACK TRACE HERE
```

**Comment by peter-hofer** [comment]
Merged your fix in 9abecf764253a023c69882ca543848e3b4c9125e, thanks again!
