### ISSUE TITLE
Compilation fails on native-image java11 with java.lang.Class.annotationData problem

### ISSUE THREAD

**Issue by ninja-** [oracle/graal#2339]
**Describe the issue**

When switching build from java8 to java11, it fails with this error.
I needed to enable assertions to get this stacktrace.

```
Info:RecomputeFieldValue.FieldOffset substitution automatically registered for java.lang.Class$Atomic.reflectionDataOffset, target element java.lang.Class.reflectionData.
Info:RecomputeFieldValue.FieldOffset substitution automatically registered for java.lang.Class$Atomic.annotationTypeOffset, target element java.lang.Class.annotationType.
Info:RecomputeFieldValue.FieldOffset substitution automatically registered for java.lang.Class$Atomic.annotationDataOffset, target element java.lang.Class.annotationData.
2 fatal errors detected:
Fatal error: java.lang.AssertionError: AnalysisField<Class.annotationData accessed: true reads: false written: true>
	at com.oracle.graal.pointsto.meta.AnalysisField.getPosition(AnalysisField.java:351)
	at com.oracle.graal.pointsto.flow.context.object.AnalysisObject.getInstanceFieldTypeStore(AnalysisObject.java:223)
	at com.oracle.graal.pointsto.flow.context.object.AnalysisObject.getInstanceFieldFlow(AnalysisObject.java:209)
	at com.oracle.graal.pointsto.flow.OffsetLoadTypeFlow$AbstractUnsafeLoadTypeFlow.onObservedUpdate(OffsetLoadTypeFlow.java:191)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:344)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:386)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:511)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Fatal error: java.lang.AssertionError: AnalysisField<Class.annotationData accessed: true reads: false written: true>
	at com.oracle.graal.pointsto.meta.AnalysisField.getPosition(AnalysisField.java:351)
	at com.oracle.graal.pointsto.flow.context.object.AnalysisObject.getInstanceFieldTypeStore(AnalysisObject.java:223)
	at com.oracle.graal.pointsto.flow.context.object.AnalysisObject.getInstanceFieldFilterFlow(AnalysisObject.java:191)
	at com.oracle.graal.pointsto.flow.OffsetStoreTypeFlow$AbstractUnsafeStoreTypeFlow.handleUnsafeAccessedFields(OffsetStoreTypeFlow.java:192)
	at com.oracle.graal.pointsto.flow.OffsetStoreTypeFlow$AbstractUnsafeStoreTypeFlow.onObservedUpdate(OffsetStoreTypeFlow.java:228)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:344)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:386)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:511)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1527)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1289)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1250)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1209)
	at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1707)
```

**Steps to reproduce the issue**
Not sure yet. I am trying to get a minimal reproducer, as my classpath is super large.

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here]
20.0.0-java11 from dockerhub
 - JDK major version: **[e.g.:8]** 11
 - OS: **[e.g. macOS Catalina]** Linux
 - Architecture: **[e.g.: AMD64]** AMD64

**More details**

I've been digging deeply thinking it's issue in some missing substituions in DynamicHub and related classes.
Looks like that's not the case, and everything that could use methods that use Class.Atomic.* have been plugged.
Maybe we could substite the Atomic class with stubs so compiler wouldn't try to check these offsets with no need as they won't be used.

```
    PASTE YOUR LOG/STACK TRACE HERE
```

**Comment by ninja-** [comment]
I think that's an edge case for java.lang.Class, which unlike all other classess does not have a superclass?
https://github.com/oracle/graal/blob/a6fefe14fb58e5f78b2d5d12467a9510d0722a2d/substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/meta/AnalysisType.java#L877
^ following 2 methods are suspicious

**Comment by cstancu** [comment]
@ninja- is this issue still reproducible?

**Comment by ninja-** [comment]
@cstancu I gave up moving my project to Graal due to crucial features and optimizations being hidden behind Enterprise Edition..
If no one fixed the issue, I guess it would still be reproducible, but as my classpath was super large and the build scripts quite hacky and volatile, it was hard for me to provide a good reproducer.

**Comment by cstancu** [comment]
Thanks for your reply. I'll close this issue for now. I'll reopen if I have a reproducible.
