### ISSUE TITLE
native-image failing with unexpected CNFE when analyzing default methods

### ISSUE THREAD

**Issue by aclement** [oracle/graal#2355]
**Describe the issue**
We are compiling our app with `--allow-incomplete-classpath --report-unsupported-elements-at-runtime`. However it still reports CNFE at image build time like this:
```
Caused by: java.lang.NoClassDefFoundError: org/reactivestreams/Publisher
	at jdk.vm.ci.hotspot.CompilerToVM.getDeclaredMethods(Native Method)
	at jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.getDeclaredMethods(HotSpotResolvedObjectTypeImpl.java:952)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.declaresDefaultMethods(ClassInitializationFeature.java:375)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.hasDefaultMethods(ClassInitializationFeature.java:363)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.buildClassInitializationInfo(ClassInitializationFeature.java:351)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:193)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:715)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:715)
```

The default method can be found in https://github.com/spring-projects/spring-framework/blob/master/spring-tx/src/main/java/org/springframework/transaction/reactive/TransactionalOperator.java - it is the one involving Mono, since that extends CorePublisher which extends org.reactivestreams.Publisher.

Looking at the code in https://github.com/oracle/graal/blob/69794db183e49551cc31b7c5aa122cd332c863f0/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/classinitialization/ClassInitializationFeature.java. 

I see within the buildClassInitializationInfo method that we catch problems accessing getDeclaredMethods() (line 330) and record what went wrong and continue. However the call to hasDefaultMethods() from the stack trace is made outside of the try catch  (line 358) that would cope with this problem, and so the CNFE flies out of the method. Should the default method  call happen inside that try catch in some way so we cope with this type not being around? 

I have tried Graal 20.0 and master branch built today (16-Apr). 

**Steps to reproduce the issue**
Please include both build steps as well as run steps
Clone the spring-graal-native project, https://github.com/spring-projects-experimental/spring-graal-native - run `build.sh` at the root, then go into the samples/vanilla-tx folder in the pom there is the reactive-streams dependency. As cloned build.sh will run OK, remove the dependency and you will see the error above (compile.sh output is kept in target/native-image/output.txt)

**Describe GraalVM and your environment:**
 GraalVM 20 (or master) on Java8 base, catalina.

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
    PASTE YOUR LOG/STACK TRACE HERE
```

**Comment by eginez** [comment]
This is happening in the `vanilla-tx` example

**Comment by aclement** [comment]
my mistake - i didn't use a rebuild of todays graals master. Instead I built a fresh version of the 20.0 tag (so I could include some debugging). sorry!
