### ISSUE TITLE
ClassInitalizerHasSideEffectsException: Non-inlined invoke of method: java.lang.invoke.MethodHandle.invokeBasic()

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#2374]
**Excessive exception reporting**

Using native-image with the latest master, since dfab304406916b239935b9b70179e57ff3d1eadf (https://github.com/oracle/graal/commit/dfab304406916b239935b9b70179e57ff3d1eadf)   there is a huge amount of exceptions being thrown while compiling e.g. HelloFX (https://github.com/gluonhq/client-samples/tree/master/Maven/HelloFX)

Compilation succeeds and the resulting image is fine, but the exceptions probably worry the developer (and I don't see anything wrong with the code). 

The format of those exceptions is as follows:
```[Tue Apr 21 15:06:56 CEST 2020][INFO] [SUB]     Context obj com.oracle.svm.hosted.classinitialization.ClassInitializerGraphBuilderPhase@1f96de6f
[Tue Apr 21 15:06:56 CEST 2020][INFO] [SUB]     Context obj HotSpotMethod<CollinearSimplifier$1.<clinit>()>
[Tue Apr 21 15:06:56 CEST 2020][INFO] [SUB] [thread:32] scope: ForkJoinPool-2-worker-5
[Tue Apr 21 15:06:56 CEST 2020][INFO] [SUB]   [thread:32] scope: ForkJoinPool-2-worker-5.EarlyClassInitializerAnalysis
[Tue Apr 21 15:06:56 CEST 2020][INFO] [SUB]   Context: HotSpotMethod<DCollinearSimplifier$1.<clinit>()>
[Tue Apr 21 15:06:56 CEST 2020][INFO] [SUB]     [thread:32] scope: ForkJoinPool-2-worker-5.EarlyClassInitializerAnalysis.ClassInitializerGraphBuilderPhase
[Tue Apr 21 15:06:56 CEST 2020][INFO] [SUB]     Exception raised in scope ForkJoinPool-2-worker-5.EarlyClassInitializerAnalysis.ClassInitializerGraphBuilderPhase: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.svm.hosted.classinitialization.ClassInitalizerHasSideEffectsException: Access of static field from a different class: com.sun.marlin.DCollinearSimplifier$SimplifierState.$VALUES
[Tue Apr 21 15:06:56 CEST 2020][INFO] [SUB]     	at parsing com.sun.marlin.DCollinearSimplifier$SimplifierState.values(DCollinearSimplifier.java:32)
[Tue Apr 21 15:06:56 CEST 2020][INFO] [SUB]     	at parsing com.sun.marlin.DCollinearSimplifier$1.<clinit>(DCollinearSimplifier.java:100)
[Tue Apr 21 15:06:56 CEST 2020][INFO] [SUB]     	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2590)
[Tue Apr 21 15:06:56 CEST 2020][INFO] [SUB]     	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:94)
[Tue Apr 21 15:06:56 CEST 2020][INFO] [SUB]     	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3428)
[Tue Apr 21 15:06:56 CEST 2020][INFO] [SUB]     	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3230)```

**Comment by mipastgt** [comment]
I am getting swamped by these exception messages. Is there still no solution? Not even a comment?

**Comment by vjovanov** [comment]
I will look into this. It seems that we are leaking our internal exceptions to the log files.

**Comment by mipastgt** [comment]
I'd be more than happy if this could be fixed. It is just driving me nuts again right at this moment :-)

**Comment by vjovanov** [comment]
Well, the image build works, right?

**Comment by mipastgt** [comment]
Yes, it does. But when you get hundreds of such error messages it is difficult to spot the real ones in between.

**Comment by bodiam** [comment]
I'm getting the same, or a similar issue, except that my conversion to a native image is not working. I'm not sure why, since I'm not sure what internal errors are, and what "real" errors are.

I get errors like:

```
Caused by: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.Class.isNestmateOf(Class) is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
```

and 

```
org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.svm.hosted.classinitialization.ClassInitalizerHasSideEffectsException: Access of static field from a different class: java.lang.Boolean.FALSE
```

and

```
Caused by: com.oracle.svm.hosted.classinitialization.ClassInitalizerHasSideEffectsException: Access of static field from a different class: java.lang.String.COMPACT_STRINGS
```

and 

```
    Exception raised in scope ForkJoinPool-2-worker-17.EarlyClassInitializerAnalysis.ClassInitializerGraphBuilderPhase: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.svm.hosted.classinitialization.ClassInitalizerHasSideEffectsException: Reference of class that is not initialized: kotlin.reflect.jvm.internal.impl.name.FqName
```

I'm not sure how to resolve these errors, since I have 10 MB of errors in my output, and I'm not sure what real errors are and what not. I actually just assumed all of them were real.

**Comment by mipastgt** [comment]
According to my experience the first one in your list is a real error for which a possible fix is suggested. All the other ones are just internal messages which slipped through.
Just my 2€ent

**Comment by mfunaro** [comment]
` Caused by: com.oracle.svm.hosted.classinitialization.ClassInitalizerHasSideEffectsException: Non-inlined invoke of method: java.lang.Class.getName0()`

Does this error also fall under the "internal messages that slipped through"?

**Comment by vjovanov** [comment]
Yes.

**Comment by mipastgt** [comment]
Do you have any news on this issue to share?

**Comment by vjovanov** [comment]
Not really. This is not blocking anyone so it does not have priority. Why is the fix so important?

**Comment by mipastgt** [comment]
If you get swamped with hundreds of such messages in a single build this is a real PITA. And then try to spot some real problem between all that nonsense. Using native-image has become a real pain when you try to use it on real applications and not just hello world examples. Does that somehow explain the importants of this fix?

**Comment by vjovanov** [comment]
Yes, I think we can prioritize this.

**Comment by christianwimmer** [comment]
The exception stack trace is only printed when the Graal debug handler is enabled, which is for example `-H:Log=xxx` or `-H:Dump=xxx`. I'll fix that the exception is not printed in such cases.

**Comment by mipastgt** [comment]
@christianwimmer You made my day :-)

**Comment by bodiam** [comment]
Thanks, that is much appreciated!

**Comment by christianwimmer** [comment]
Should be fixed by https://github.com/oracle/graal/commit/84ef869a16dd3e7a9ee4302d16e0ef98cd141cf5
