### ISSUE TITLE
When i used jasper 6.12.2 show this problem how to fixed 

### ISSUE THREAD

**Issue by mohammed860** [oracle/graal#2376]
Apr 22, 2020 12:53:01 AM erp.Newtest86 jButton1ActionPerformed
SEVERE: null
net.sf.jasperreports.engine.JRException: Errors were encountered when compiling report expressions class file:
1. The operator % is undefined for the argument type(s) Integer, int
                value = ((java.lang.Integer)variable_colum32cunt.getValue()) % 2 == 0; //$JR_EXPR_ID=14$
                        <------------------------------------------------------>
2. The operator % is undefined for the argument type(s) Integer, int
                value = ((java.lang.Integer)variable_colum32cunt.getOldValue()) % 2 == 0; //$JR_EXPR_ID=14$
                        <--------------------------------------------------------->
3. The operator % is undefined for the argument type(s) Integer, int
                value = ((java.lang.Integer)variable_colum32cunt.getEstimatedValue()) % 2 == 0; //$JR_EXPR_ID=14$
                        <--------------------------------------------------------------->
3 errors
.
	at net.sf.jasperreports.engine.design.JRAbstractCompiler.compileReport(JRAbstractCompiler.java:206)
	at net.sf.jasperreports.engine.JasperCompileManager.compile(JasperCompileManager.java:358)
	at net.sf.jasperreports.engine.JasperCompileManager.compileReport(JasperCompileManager.java:618)
	at erp.Newtest86.jButton1ActionPerformed(Newtest86.java:163)
	at erp.Newtest86.access$000(Newtest86.java:47)
	at erp.Newtest86$1.actionPerformed(Newtest86.java:74)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)****

**Comment by fernando-valdez** [comment]
Hello @mohammed860, please check if this problem persists in the latest GraalVM snapshot

**Comment by fernando-valdez** [comment]
Closing this ticket due to the lack of response.
