### ISSUE TITLE
[native-image] Quarkus NI build failures when using Debuginfo

### ISSUE THREAD

**Issue by a74nh** [oracle/graal#2379]
*Using Quarkus github checkout of a0d8e9bf5 2020-04-22.
*Edit the deployment code to always build native images using debug info.
*Build Quarkus using the native flag.
*Almost all integration tests will fail to build as native images.

```
$ cd quarkus
$ git diff
diff --git a/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java b/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java
index 83a02c48a..e1f2a039b 100644
--- a/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java
+++ b/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java
@@ -319,6 +319,7 @@ public class NativeImageBuildStep {
} else {
command.add("-H:-StackTrace");
}
+ command.add("-H:GenerateDebugInfo=1");
String executableName = outputTargetBuildItem.getBaseName() + packageConfig.runnerSuffix;
command.add(executableName);

$ ./mvnw clean install -Dnative -fae

<snip>
[quarkus-integration-test-bootstrap-config-application-999-SNAPSHOT-runner:8570]      compile:  25,423.95 ms,  6.10 GB
[quarkus-integration-test-bootstrap-config-application-999-SNAPSHOT-runner:8570]        image:  33,409.54 ms,  6.03 GB
Fatal error:com.oracle.svm.core.util.VMError$HostedError: com.oracle.svm.core.util.UserError$UserException: Static field or an object referenced from a static field changed during native image generation?
  object:jdk.internal.ref.Cleaner@167bc07e  of class: jdk.internal.ref.Cleaner
  reachable through:
    object: jdk.internal.ref.Cleaner@521e0eb9  of class: jdk.internal.ref.Cleaner
    object: jdk.internal.ref.Cleaner@1995fd11  of class: jdk.internal.ref.Cleaner
    object: java.nio.DirectByteBuffer[pos=0 lim=0 cap=0]  of class: java.nio.DirectByteBuffer
    root: io.netty.buffer.CompositeByteBuf.<clinit>()

        at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:72)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:647)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.oracle.svm.core.util.UserError$UserException: Static field or an object referenced from a static field changed during native image generation?
  object:jdk.internal.ref.Cleaner@167bc07e  of class: jdk.internal.ref.Cleaner
  reachable through:
    object: jdk.internal.ref.Cleaner@521e0eb9  of class: jdk.internal.ref.Cleaner
    object: jdk.internal.ref.Cleaner@1995fd11  of class: jdk.internal.ref.Cleaner
    object: java.nio.DirectByteBuffer[pos=0 lim=0 cap=0]  of class: java.nio.DirectByteBuffer

```

Tested on both X86 and AArch64.
Graal built from git head b47aaf4 2020-04-14
Using labsjdk-ce-11.0.6-jvmci-20.0-b02.

Everything works fine if I undo the patch with the GenerateDebugInfo flag

**Comment by adinn** [comment]
Hmm, that's 'interesting' :-). I'll see if I can reproduce this and identify where this is coming from. I may well refer it on to our Quarkus team though. Thanks for the report!

**Comment by jaikiran** [comment]
Hello @a74nh, just a FYI - you don't have to patch the Quarkus code to pass in additional native build arguments. Quarkus lets you pass those right from the command line. You can use the following to achieve what you are after:

```
mvn clean install -Dnative   -Dquarkus.native.additional-build-args=-H:GenerateDebugInfo=1
```
Notice the `quarkus.native.additional-build-args` which can be used to pass the additional build arguments for native image build. 

Furthermore, I tried this with latest upstream master quarkus and latest graal VM repo (commit f7ecc7ecc9a51e1db50a35244b9d85f2eaac3063) and couldn't reproduce this issue. The native image build completed successfully. I did verify that the `GenerateDebugInfo` param is indeed being passed.

**Comment by a74nh** [comment]
> you don't have to patch the Quarkus code to pass in additional native build arguments

Aha! thanks for that.

Just updated both Quarkus and Graal and I can still repeat the issue.

However.... **I've been using JDK11 to build Graal on both X86 and AArch64.**

I switched to JDK8 for X86, and almost everything passes (except Kafka)

_So, looks like the build failures are JDK11 specific issues._



Note, The Kafka failure the following (maybe worth splitting this to a new defect):

```
[quarkus-integration-test-kafka-999-SNAPSHOT-runner:35543]   (features):   1,337.32 ms,  4.20 GB
[quarkus-integration-test-kafka-999-SNAPSHOT-runner:35543]     analysis:  50,361.47 ms,  4.20 GB
Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image run time.  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
        reading field org.apache.avro.generic.GenericDatumReader.creator of
                constant org.apache.avro.specific.SpecificDatumReader@299e79d3 reached by
        reading field io.quarkus.it.kafka.avro.Pet.READER$

com.oracle.svm.core.util.UserError$UserException: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image run time.  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by
        reading field org.apache.avro.generic.GenericDatumReader.creator of
                constant org.apache.avro.specific.SpecificDatumReader@299e79d3 reached by
        reading field io.quarkus.it.kafka.avro.Pet.READER$

        at com.oracle.svm.core.util.UserError.abort(UserError.java:79)
        at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:217)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:753)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:538)
```

**Comment by jaikiran** [comment]
Hello @a74nh, for the Kafka issue, I think it's better to open an issue in the quarkus repo and have it tracked and investigated there.

**Comment by a74nh** [comment]
Kafka issue raised here: https://github.com/quarkusio/quarkus/issues/8914

**Comment by a74nh** [comment]
That just leaves the JDK11 issues for this bug

**Comment by jvican** [comment]
Hi folks. Just chiming in to say that I've also run into this bug when compiling a closed source application with GraalVM 21.1.0 and `-H:GenerateDebugInfo=1` enabled. I have tried to trace the symbol but no meaningful output was produced. My stack trace shares a lot of the information in this ticket, but the origin of all the problems seems to be Netty's `EmptyByteBuf.nioBuffers`:

```
Caused by: com.oracle.svm.core.util.UserError$UserException: Image heap writing found a class not seen during static analysis. Did a static field or an object referenced from a static field change during native image generation? For example, a lazily initialized cache could have been initialized during image generation, in which case you need to force eager initialization of the cache before static analysis or reset the cache using a field value recomputation.
    object: jdk.internal.ref.Cleaner@70a25500  of class: jdk.internal.ref.Cleaner
  reachable through:
    object: jdk.internal.ref.Cleaner@19dfb5e1  of class: jdk.internal.ref.Cleaner
    object: jdk.internal.ref.Cleaner@14fa4a6a  of class: jdk.internal.ref.Cleaner
    object: java.nio.DirectByteBuffer[pos=0 lim=0 cap=0]  of class: java.nio.DirectByteBuffer
    root: io.netty.buffer.EmptyByteBuf.nioBuffers(int, int)

        at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
        at com.oracle.svm.hosted.image.NativeImageHeap.reportIllegalType(NativeImageHeap.java:514)
        at com.oracle.svm.hosted.image.NativeImageHeapWriter.verifyTargetDidNotChange(NativeImageHeapWriter.java:132)
        at com.oracle.svm.hosted.image.NativeImageHeapWriter.writeReference(NativeImageHeapWriter.java:165)
        at com.oracle.svm.hosted.image.NativeImageHeapWriter.write(NativeImageHeapWriter.java:154)
        at com.oracle.svm.hosted.image.NativeImageHeapWriter.writeField(NativeImageHeapWriter.java:148)
        at com.oracle.svm.hosted.image.NativeImageHeapWriter.writeObject(NativeImageHeapWriter.java:343)
        at com.oracle.svm.hosted.image.NativeImageHeapWriter.writeHeap(NativeImageHeapWriter.java:88)
        at com.oracle.svm.hosted.image.NativeImage.build(NativeImage.java:468)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:683)
        ... 7 more
Error: Image build request failed with exit status 1
```
