### ISSUE TITLE
[OpenJDK15] The addition of Hidden Classes breaks native-image

### ISSUE THREAD

**Issue by bobvandette** [oracle/graal#2382]
**Describe the issue**

The addition of Hidden Classes in JDK15 is causing native-image to fail with several UnsupportedFeatureExceptions.

https://bugs.openjdk.java.net/browse/JDK-8238358
https://hg.openjdk.java.net/jdk/jdk/rev/30ec85283758

**Steps to reproduce the issue**

Build GraalVM with binaries built from the latest JDK15 and run native-image on Hello World.

**More details**

Here is one example of the error:

Fatal error: FallbackImageRequest while building fallback image.com.oracle.svm.hosted.FallbackFeature$FallbackImageRequest: Aborting stand-alone image build. Unsupported features in 58 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Invoke with MethodHandle argument could not be reduced to at most a single call or single field access. The method handle must be a compile time constant, e.g., be loaded from a `static final` field. Method that contains the method handle invocation: java.lang.invoke.Invokers$Holder.linkToTargetMethod(Object)

A build of JDK15 before and after the Hidden Classes changeset proves that this change is the cause of the UnsupportedFeatureException.

The failure occurs when native-image is trying to process an
Invoke with a Method Handle but the invocation plugin doesn’t handle DynamicNewInstanceNode.

The methodHandleMethod is ...

AnalysisMethod<java.lang.invoke.Invokers$Holder.linkToTargetMethod -> HotSpotMethod<Invokers$Holder.linkToTargetMethod(Object)>>

In IntrinsifyMethodHandlesInvocationPlugin.java

node is 12|DynamicNewInstance

```
Node singleFunctionality = null;
ReturnNode singleReturn = null;
for (Node node : graph.getNodes()) {
    if (node == graph.start() || node instanceof ParameterNode || node instanceof ConstantNode || node instanceof FrameState) {
        /* Ignore the allowed framework around the nodes we care about. */
    } else if (node instanceof MethodCallTargetNode) {
        /* We check the Invoke, so we can ignore the call target. */
    } else if ((node instanceof Invoke || node instanceof LoadFieldNode || node instanceof StoreFieldNode) && singleFunctionality == null) {
        singleFunctionality = node;
    } else if (node instanceof ReturnNode && singleReturn == null) {
        singleReturn = (ReturnNode) node;
    } else {
        reportUnsupportedFeature(b, methodHandleMethod);  <<<---------
        return;
    }
}
```

**Comment by bobvandette** [comment]
// @jerboaa

**Comment by jerboaa** [comment]
Thanks for the heads-up. Only saw this now.

**Comment by bobvandette** [comment]
The problem is caused by a change in the LambdaMetaFactory.

For lambda proxies, it might be related to the constructor:
   http://cr.openjdk.java.net/~mchung/valhalla/webrevs/hidden-classes/webrev.07/src/java.base/share/classes/java/lang/invoke/InnerClassLambdaMetafactory.java.sdiff.html

Previously, it created a static factory method that calls the constructor and the callsite returned is the static factory method.

With hidden class and nestmate, the static factory method is no longer needed.  The callsite returned is the direct method handle of the constructor of the hidden class. 

As a result, the pattern of Nodes that native-image needs to process now includes a DynamicNewInance node.  A constructor needs to be called before the MethodCallTarget is invoked.

Here are the Nodes that are processed in IntrinsifyMethodHandlesInvocationPlugin.java

Processing Node: 0|StartNode for graph: StructuredGraph:784{HotSpotMethod<Invokers$Holder.linkToTargetMethod(Object)>}
Processing Node: 1|Constant(BoundMethodHandle.Species_L@768642314, a -)
Processing Node: 2|FrameState@0 
Processing Node: 5|Constant(DirectMethodHandle.Constructor@73971057, a -)
Processing Node: 6|FrameState@4 
Processing Node: 8|FrameState@12 
Processing Node: 11|Constant(Class:com.oracle.svm.jni.functions.JNIInvocationInterface$Support$$Lambda$413/0x00000007c0b47970, a -)
Processing Node: 12|DynamicNewInstance 
Processing Node: 15|InstanceOf 
Processing Node: 16|FixedGuard 
Processing Node: 18|MethodCallTarget 
Processing Node: 19|Invoke#0x00000007c0b47970.<init>
Processing Node: 20|FrameState@18 
Processing Node: 21|Return 

I attempted to avoid the Inlining of this specific MethodHandle invoke type but it appears that Graal can't handle this pattern either.

Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.oracle.svm.jni.JNIThreadLocalPinnedObjects.unpinArrayByAddress(org.graalvm.word.PointerBase) 
Parsing context:
        parsing com.oracle.svm.jni.functions.JNIFunctions$Support.unpinString(JNIFunctions.java:1133)
        parsing com.oracle.svm.jni.functions.JNIFunctions.ReleaseStringChars(JNIFunctions.java:500)
        parsing com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ReleaseStringChars_aba9a9705a410f995f6fc1f6e850b359dd83f50c(generated:0)

        at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:340)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:311)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:112)
        at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:437)
        at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:530)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1429)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.oracle.svm.core.util.UserError$UserException: Expected Object but got Word for call argument in com.oracle.svm.jni.JNIThreadLocalPinnedObjects.unpinArrayByAddress(JNIThreadLocalPinnedObjects.java:81)
        at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.checkWordType(SharedGraphBuilderPhase.java:327)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.createMethodCallTarget(SharedGraphBuilderPhase.java:306)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.createNonInlinedInvoke(BytecodeParser.java:2065)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1972)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genDynamicInvokeHelper(BytecodeParser.java:1793)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeDynamic(BytecodeParser.java:1718)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeDynamic(BytecodeParser.java:1714)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5342)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3423)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3230)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1088)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:982)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:214)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:224)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:351)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:322)
        ... 11 more

**Comment by ftomassetti** [comment]
With graalvm-ce-java11-21.1.0 I am seeing a failure due to a similar message:

```
Caused by: com.oracle.svm.core.util.UserError$UserException: Expected Object but got Word for call argument in com.strumenta.polyparser.rpgparser.ParserKt.parseCode(Parser.kt)
        at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.checkWordType(SharedGraphBuilderPhase.java:358)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.createMethodCallTarget(SharedGraphBuilderPhase.java:337)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.createNonInlinedInvoke(BytecodeParser.java:2058)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1966)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1671)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1651)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5448)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3451)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3258)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1125)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1019)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:76)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:113)
        at com.oracle.svm.hosted.SVMHost.parseBytecode(SVMHost.java:647)
        at com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:592)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:163)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:304)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:313)
        ... 11 more
```
