### ISSUE TITLE
[native-image] sun.security.provider.X509Factory - Static field or an object referenced from a static field changed during native image generation

### ISSUE THREAD

**Issue by dimasukr** [oracle/graal#2389]
**Describe issue**
Error during native image build.
Very simple vertx-pg-client project - https://github.com/dimasukr/graalvm-vertx-repro/blob/master/src/main/java/App.java

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. `git clone --depth 1 https://github.com/dimasukr/graalvm-vertx-repro.git`
2. `sh docker_build.sh`
Or if no docker then:  
```
mvn package
mkdir build
cp ./target/bootstrap.jar ./build/
cp ./docker/native-config/*.json ./build/
cp ./docker/build_native.sh ./build/
cd ./build
sh ./build_native.sh
```

**Describe GraalVM and your environment:**
 - GraalVM version CE 20.1.0 and 20.0.0
 - JDK major version: 11
 - OS: Ubuntu 18.04
 - Docker:  19.03.8
 - Architecture: AMD64

**More details**
```
Fatal error: com.oracle.svm.core.util.VMError$HostedError: com.oracle.svm.core.util.UserError$UserException: Image heap writing found an object whose class was not seen as instantiated during static analysis. Did a static field or an object referenced from a static field change during native image generation? For example, a lazily initialized cache could have been initialized during image generation, in which case you need to force eager initialization of the cache before static analysis or reset the cache using a field value recomputation.
   object: sun.security.provider.X509Factory@2ad0dba6 of class: sun.security.provider.X509Factory
   reachable through:
     object: java.security.cert.CertificateFactory@6074f49f  of class: java.security.cert.CertificateFactory
     root: HostedField<SslContext.X509_CERT_FACTORY location: 4152   AnalysisField<SslContext.X509_CERT_FACTORY accessed: false reads: false written: true>>
       at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:70)
       at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:641)
       at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
       at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
       at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
       at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
       at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
       at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
       at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.oracle.svm.core.util.UserError$UserException: Image heap writing found an object whose class was not seen as instantiated during static analysis. Did a static field or an object referenced from a static field change during native image generation? For example, a lazily initialized cache could have been initialized during image generation, in which case you need to force eager initialization of the cache before static analysis or reset the cache using a field value recomputation.
   object: sun.security.provider.X509Factory@2ad0dba6 of class: sun.security.provider.X509Factory
   reachable through:
     object: java.security.cert.CertificateFactory@6074f49f  of class: java.security.cert.CertificateFactory
     root: HostedField<SslContext.X509_CERT_FACTORY location: 4152   AnalysisField<SslContext.X509_CERT_FACTORY accessed: false reads: false written: true>>
       at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
       at com.oracle.svm.hosted.image.NativeImageHeap.requireType(NativeImageHeap.java:473)
       at com.oracle.svm.hosted.image.NativeImageHeap.addObjectToBootImageHeap(NativeImageHeap.java:363)
       at com.oracle.svm.hosted.image.NativeImageHeap.addObject(NativeImageHeap.java:312)
       at com.oracle.svm.hosted.image.NativeImageHeap.processAddObjectWorklist(NativeImageHeap.java:565)
       at com.oracle.svm.hosted.image.NativeImageHeap.addTrailingObjects(NativeImageHeap.java:200)
       at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:620)
       ... 7 more
```

**Comment by dimasukr** [comment]
Any ideas on workaround?

**Comment by dimasukr** [comment]
Same issue in 20.1.0

**Comment by BornToRain** [comment]
add --enable-all-security-services can fix this bug in 20.1.0.

**Comment by dimasukr** [comment]
Yes this helps but it doubles size of the image which is not ideal

**Comment by cdrtz** [comment]
Yes, the security services API brings in quite a bit of code. You may be able to reduce that if you know exact security services that your app needs: https://github.com/oracle/graal/blob/master/substratevm/JCA-SECURITY-SERVICES.md#alternative-to---enable-all-security-services. We are also working on a solution to automate the discovery of needed security services based on code reachability.

**Comment by cstancu** [comment]
Yes, the security services API brings in quite a bit of code. You may be able to reduce that if you know exact security services that your app needs: https://github.com/oracle/graal/blob/master/substratevm/JCA-SECURITY-SERVICES.md#alternative-to---enable-all-security-services. We are also working on a solution to automate the discovery of needed security services based on code reachability.

**Comment by dimasukr** [comment]
I'm actually not using any security services and don't want to enable them at all.
It is possible that vertx is using those somehow
