### ISSUE TITLE
CNFE failure during native-image build for type not necessary to run the app

### ISSUE THREAD

**Issue by aclement** [oracle/graal#2391]
**Describe the issue**
This is a bit like issue #2355  in that native-image fails with a CNFE for a type that the app doesn't need when running - it is being compiled with `--allow-incomplete-classpath` and `--report-unsupported-elements-at-runtime`. However it seems to be a different codepath leading to the problem related to method handles and possibly invokedynamic. It may be a real issue that needs addressing with a substitution on our side perhaps but if so I'm finding the error message not super helpful. When run in the mode below the feature is definiitely adding more types for reflection/etc than an agent would but I'm surprised if adding one of those should cause native-image to fail in quite such a cryptic way.

**Steps to reproduce the issue**
1. git clone git@github.com:spring-projects-experimental/spring-graal-native.git
2. with GRAAL on your classpath run `./build.sh` in the project root
3. cd spring-graal-native-samples/commandlinerunner
4. if you run `./build.sh` as is, it will work.
5. Edit compile.sh and in the native-image call delete the line `-Dspring.graal.remove-unused-autoconfig=true \`
6. This causes the feature to do less trimming of spring config. It is still a valid way to run - it will add more targets for reflection to satisfy these extra configs.
7. Run `./build.sh` again. Get the errors below.

**Describe GraalVM and your environment:**
- I've tried Graal 20.0 release,  20.1 released dev builds, and my own master build from graal this morning (commit  268c16f23cd52)
- These are Java8
- On MAC

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/bin/java \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-d64 \
-XX:-UseJVMCIClassLoader \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx14g \
-Duser.country=US \
-Duser.language=en \
-Djava.awt.headless=true \
-Dorg.graalvm.version=20.1.0-dev \
-Dorg.graalvm.config= \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
-Djvmci.class.path.append=/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/jvmci/graal.jar \
-javaagent:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/svm/builder/svm.jar \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-Xbootclasspath/a:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/boot/graaljs-scriptengine.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/boot/graal-sdk.jar \
-cp \
/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/svm/builder/llvm-wrapper-shadowed.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/svm/builder/svm.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/svm/builder/objectfile.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/svm/builder/llvm-platform-specific-shadowed.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/svm/builder/javacpp-shadowed.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/svm/builder/svm-llvm.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/svm/builder/pointsto.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/jvmci/graal.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/jvmci/graal-management.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/jvmci/jvmci-api.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/jvmci/graal-truffle-jfr-impl.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/jvmci/jvmci-hotspot.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/resources.jar \
com.oracle.svm.hosted.NativeImageGeneratorRunner \
-imagecp \
/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/boot/graaljs-scriptengine.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/boot/graal-sdk.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/svm/builder/llvm-wrapper-shadowed.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/svm/builder/svm.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/svm/builder/objectfile.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/svm/builder/llvm-platform-specific-shadowed.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/svm/builder/javacpp-shadowed.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/svm/builder/svm-llvm.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/svm/builder/pointsto.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/jvmci/graal.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/jvmci/graal-management.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/jvmci/jvmci-api.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/jvmci/graal-truffle-jfr-impl.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/jvmci/jvmci-hotspot.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/resources.jar:/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/svm/library-support.jar:/Users/aclement/gits6/spring-graal-native/spring-graal-native-samples/commandlinerunner/target/native-image/BOOT-INF/classes:/Users/aclement/gits6/spring-graal-native/spring-graal-native-samples/commandlinerunner/target/native-image/BOOT-INF/lib:/Users/aclement/gits6/spring-graal-native/spring-graal-native-samples/commandlinerunner/target/native-image/BOOT-INF/lib/spring-boot-autoconfigure-2.3.0.M4.jar:/Users/aclement/gits6/spring-graal-native/spring-graal-native-samples/commandlinerunner/target/native-image/BOOT-INF/lib/spring-aop-5.2.6.BUILD-SNAPSHOT.jar:/Users/aclement/gits6/spring-graal-native/spring-graal-native-samples/commandlinerunner/target/native-image/BOOT-INF/lib/log4j-api-2.13.1.jar:/Users/aclement/gits6/spring-graal-native/spring-graal-native-samples/commandlinerunner/target/native-image/BOOT-INF/lib/spring-context-5.2.6.BUILD-SNAPSHOT.jar:/Users/aclement/gits6/spring-graal-native/spring-graal-native-samples/commandlinerunner/target/native-image/BOOT-INF/lib/spring-beans-5.2.6.BUILD-SNAPSHOT.jar:/Users/aclement/gits6/spring-graal-native/spring-graal-native-samples/commandlinerunner/target/native-image/BOOT-INF/lib/slf4j-api-1.7.30.jar:/Users/aclement/gits6/spring-graal-native/spring-graal-native-samples/commandlinerunner/target/native-image/BOOT-INF/lib/spring-boot-2.3.0.M4.jar:/Users/aclement/gits6/spring-graal-native/spring-graal-native-samples/commandlinerunner/target/native-image/BOOT-INF/lib/logback-classic-1.2.3.jar:/Users/aclement/gits6/spring-graal-native/spring-graal-native-samples/commandlinerunner/target/native-image/BOOT-INF/lib/log4j-to-slf4j-2.13.1.jar:/Users/aclement/gits6/spring-graal-native/spring-graal-native-samples/commandlinerunner/target/native-image/BOOT-INF/lib/snakeyaml-1.26.jar:/Users/aclement/gits6/spring-graal-native/spring-graal-native-samples/commandlinerunner/target/native-image/BOOT-INF/lib/spring-boot-starter-2.3.0.M4.jar:/Users/aclement/gits6/spring-graal-native/spring-graal-native-samples/commandlinerunner/target/native-image/BOOT-INF/lib/jul-to-slf4j-1.7.30.jar:/Users/aclement/gits6/spring-graal-native/spring-graal-native-samples/commandlinerunner/target/native-image/BOOT-INF/lib/spring-jcl-5.2.6.BUILD-SNAPSHOT.jar:/Users/aclement/gits6/spring-graal-native/spring-graal-native-samples/commandlinerunner/target/native-image/BOOT-INF/lib/logback-core-1.2.3.jar:/Users/aclement/gits6/spring-graal-native/spring-graal-native-samples/commandlinerunner/target/native-image/BOOT-INF/lib/jakarta.annotation-api-1.3.5.jar:/Users/aclement/gits6/spring-graal-native/spring-graal-native-samples/commandlinerunner/target/native-image/BOOT-INF/lib/spring-boot-starter-logging-2.3.0.M4.jar:/Users/aclement/gits6/spring-graal-native/spring-graal-native-samples/commandlinerunner/target/native-image/BOOT-INF/lib/spring-core-5.2.6.BUILD-SNAPSHOT.jar:/Users/aclement/gits6/spring-graal-native/spring-graal-native-samples/commandlinerunner/target/native-image/BOOT-INF/lib/spring-context-indexer-5.2.6.BUILD-SNAPSHOT.jar:/Users/aclement/gits6/spring-graal-native/spring-graal-native-samples/commandlinerunner/target/native-image/BOOT-INF/lib/spring-expression-5.2.6.BUILD-SNAPSHOT.jar:/Users/aclement/gits6/spring-graal-native/spring-graal-native-samples/commandlinerunner/target/native-image:/Users/aclement/gits6/spring-graal-native/spring-graal-native/target/spring-graal-native-0.7.0.BUILD-SNAPSHOT.jar \
-H:Path=/Users/aclement/gits6/spring-graal-native/spring-graal-native-samples/commandlinerunner/target/native-image \
-H:+DumpTargetInfo \
-H:FallbackThreshold=0 \
-H:Name=commandlinerunner \
-H:+ReportExceptionStackTraces \
-H:+AllowIncompleteClasspath \
-H:+ReportUnsupportedElementsAtRuntime \
-H:CLibraryPath=/Users/aclement/installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/svm/clibraries/darwin-amd64 \
-H:Class=com.example.commandlinerunner.CommandlinerunnerApplication \

]
[commandlinerunner:18130]    classlist:   3,928.93 ms,  1.38 GB
 ____             _               _____          _                  
/ ___| _ __  _ __(_)_ __   __ _  |  ___|__  __ _| |_ _   _ _ __ ___ 
\___ \| '_ \| '__| | '_ \ / _` | | |_ / _ \/ _` | __| | | | '__/ _ \
 ___) | |_) | |  | | | | | (_| | |  _|  __/ (_| | |_| |_| | | |  __/
|____/| .__/|_|  |_|_| |_|\__, | |_|  \___|\__,_|\__|\__,_|_|  \___|
      |_|                 |___/                                     

Use -Dspring.graal.verbose=true on native-image call to see more detailed information from the feature
[commandlinerunner:18130]        (cap):   1,208.06 ms,  1.38 GB
Found #5 types in static reflection list to register
Skipping #5 types not on the classpath
Attempting proxy registration of #19 proxies
Skipped registration of #16 proxies - relevant types not on classpath
[commandlinerunner:18130]        setup:   2,524.81 ms,  1.38 GB
Registering resources - #34 patterns
Registering resources - #2 bundles
Processing META-INF/spring.factories files...
spring.factories processing, problem adding access for key org.springframework.boot.autoconfigure.jdbc.HikariDriverConfigurationFailureAnalyzer: org/springframework/jdbc/CannotGetJdbcConnectionException
Processing spring.factories - EnableAutoConfiguration lists #126 configurations
annotation extractTypesFromAttributes=[value, type](class java.util.ArrayList)
annotation extractTypesFromAttributes=[value, name](class java.util.ArrayList)
annotation extractTypesFromAttributes=[value, name](class java.util.ArrayList)
annotation extractTypesFromAttributes=[value](class java.util.ArrayList)
spring.factories processing, problem adding access for key org.springframework.boot.diagnostics.analyzer.ValidationExceptionFailureAnalyzer: javax/validation/ValidationException
Processing spring.factories - PropertySourceLoader lists #2 property source loaders
Processing META-INF/spring.components files...
Registered 2 entries
Registered 2 entries
Configuring initialization time for specific types and packages:
#68 buildtime-init-classes   #23 buildtime-init-packages   #33 runtime-init-classes    #0 runtime-init-packages

Warning: class initialization of class org.springframework.boot.validation.MessageInterpolatorFactory failed with exception java.lang.NoClassDefFoundError: javax/validation/ValidationException. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=org.springframework.boot.validation.MessageInterpolatorFactory to explicitly request delayed initialization of this class.
Number of types dynamically registered for reflective access: #4248
# Building image for target platform: org.graalvm.nativeimage.Platform$DARWIN_AMD64
# Using native toolchain:
#   Name: LLVM (clang)
#   Vendor: apple
#   Version: 11.0.0
#   Target architecture: x86_64
#   Path: /usr/bin/cc
# Using CLibrary: com.oracle.svm.core.c.libc.GLibc
[commandlinerunner:18130]     (clinit):     789.16 ms,  4.11 GB
# Static libraries:
#   ../../../../../../../installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/liblibchelper.a
#   ../../../../../../../installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/libnet.a
#   ../../../../../../../installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libstrictmath.a
#   ../../../../../../../installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libffi.a
#   ../../../../../../../installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libdarwin.a
#   ../../../../../../../installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/libnio.a
#   ../../../../../../../installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/libjava.a
#   ../../../../../../../installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/svm/clibraries/darwin-amd64/libjvm.a
#   ../../../../../../../installs/graalvm-ce-java8-20.1.0-dev/Contents/Home/jre/lib/libzip.a
# Other libraries: -framework Foundation,pthread,dl,z
[commandlinerunner:18130]   (typeflow):  12,094.77 ms,  4.11 GB
[commandlinerunner:18130]    (objects):  17,446.32 ms,  4.11 GB
[commandlinerunner:18130]   (features):   8,660.13 ms,  4.11 GB
[commandlinerunner:18130]     analysis:  40,558.58 ms,  4.11 GB
Error: Error loading a referenced type: java.lang.IllegalAccessError: no such method: org.springframework.core.io.buffer.DataBufferUtils.release(DataBuffer)boolean/invokeStatic
Detailed message:
Trace: 
	at parsing org.springframework.core.io.buffer.DefaultDataBufferFactory.join(DefaultDataBufferFactory.java:114)
Call path from entry point to org.springframework.core.io.buffer.DefaultDataBufferFactory.join(List): 
	at org.springframework.core.io.buffer.DefaultDataBufferFactory.join(DefaultDataBufferFactory.java:110)
	at com.oracle.svm.reflect.DefaultDataBufferFactory_join_ecee51af1a1cc88e99d26bc1d893f116c08a0408_1290.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder$BeanProperty.lambda$getValue$0(JavaBeanBinder.java:333)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder$BeanProperty$$Lambda$402/1306916650.get(Unknown Source)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:345)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)

com.oracle.svm.core.util.UserError$UserException: Error loading a referenced type: java.lang.IllegalAccessError: no such method: org.springframework.core.io.buffer.DataBufferUtils.release(DataBuffer)boolean/invokeStatic
Detailed message:
Trace: 
	at parsing org.springframework.core.io.buffer.DefaultDataBufferFactory.join(DefaultDataBufferFactory.java:114)
Call path from entry point to org.springframework.core.io.buffer.DefaultDataBufferFactory.join(List): 
	at org.springframework.core.io.buffer.DefaultDataBufferFactory.join(DefaultDataBufferFactory.java:110)
	at com.oracle.svm.reflect.DefaultDataBufferFactory_join_ecee51af1a1cc88e99d26bc1d893f116c08a0408_1290.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder$BeanProperty.lambda$getValue$0(JavaBeanBinder.java:333)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder$BeanProperty$$Lambda$402/1306916650.get(Unknown Source)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:345)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)

	at com.oracle.svm.core.util.UserError.abort(UserError.java:79)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:217)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:753)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:538)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Error loading a referenced type: java.lang.IllegalAccessError: no such method: org.springframework.core.io.buffer.DataBufferUtils.release(DataBuffer)boolean/invokeStatic
Detailed message:
Trace: 
	at parsing org.springframework.core.io.buffer.DefaultDataBufferFactory.join(DefaultDataBufferFactory.java:114)
Call path from entry point to org.springframework.core.io.buffer.DefaultDataBufferFactory.join(List): 
	at org.springframework.core.io.buffer.DefaultDataBufferFactory.join(DefaultDataBufferFactory.java:110)
	at com.oracle.svm.reflect.DefaultDataBufferFactory_join_ecee51af1a1cc88e99d26bc1d893f116c08a0408_1290.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder$BeanProperty.lambda$getValue$0(JavaBeanBinder.java:333)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder$BeanProperty$$Lambda$402/1306916650.get(Unknown Source)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:345)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:750)
	... 7 more
Caused by: java.lang.IllegalAccessError: no such method: org.springframework.core.io.buffer.DataBufferUtils.release(DataBuffer)boolean/invokeStatic
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:483)
	at jdk.vm.ci.hotspot.CompilerToVM.resolveInvokeDynamicInPool(Native Method)
	at jdk.vm.ci.hotspot.HotSpotConstantPool.loadReferencedType(HotSpotConstantPool.java:743)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.loadReferencedType(WrappedConstantPool.java:88)
	at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.loadReferencedType(WrappedConstantPool.java:105)
	at com.oracle.svm.hosted.phases.SubstrateClassInitializationPlugin.loadReferencedType(SubstrateClassInitializationPlugin.java:71)
	at org.graalvm.compiler.java.BytecodeParser.loadReferenceType(BytecodeParser.java:4384)
	at org.graalvm.compiler.java.BytecodeParser.maybeEagerlyResolve(BytecodeParser.java:4366)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.maybeEagerlyResolve(SharedGraphBuilderPhase.java:127)
	at org.graalvm.compiler.java.BytecodeParser.lookupMethod(BytecodeParser.java:4316)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeDynamic(BytecodeParser.java:1713)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5342)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3423)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3230)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1088)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:982)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:214)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:224)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:351)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:322)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:311)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:112)
	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:228)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:470)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:542)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:530)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	... 4 more
Caused by: java.lang.NoClassDefFoundError: org/reactivestreams/Publisher
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394)
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750)
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477)
	... 38 more
Caused by: java.lang.ClassNotFoundException: org.reactivestreams.Publisher
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 44 more
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1541)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1299)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1260)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1219)
```

**Comment by eginez** [comment]
Hey @aclement, at first sight this looks like an unsupported use of reflection via `MethodHandles`. I'll take a deeper look at it

**Comment by eginez** [comment]
I notice https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/io/buffer/DataBufferUtils.java#L42 pulls from a jar that is not in the classpath. This is happening during analysis time.

**Comment by eginez** [comment]
The problems is due to analysis not handling all exceptions for unresolved types. Specifically when the analysis bumps into a type that can not be loaded/found in the classpath. Typically we push those exceptions to the run-time, thus we'll do the same here

**Comment by eginez** [comment]
fixed with https://github.com/oracle/graal/commit/97bffe682455f68ac272205997eff3d482f3a013
