### ISSUE TITLE
[OpenJDK 11u] HelloWorld native-image generation fails with enabled assertions

### ISSUE THREAD

**Issue by jerboaa** [oracle/graal#2402]
A graal VM built from OpenJDK 11u (upcoming 11.0.8) will hit an assertion on generating native images. A simple `HelloWorld` will do. I'm setting `java.vm.version` to a version which looks like a released version of OpenJDK so as to actually enable assertions at runtime. Developer builds won't show this issue.

Reproducer:
```
$ ./substratevm/svmbuild/vm/bin/native-image -J-Djava.vm.version=11.0.8+1 -J-ea -cp substratevm HelloWorld foo-bar
Exception in thread "main" jdk.vm.ci.common.JVMCIError: VM config values not expected to be present in JDK 11 linux-amd64 (java.home=/disk/graal/upstream-sources/graal/sdk/mxbuild/linux-amd64/GRAALVM_E6EC3842EE_JAVA11/graalvm-e6ec3842ee-java11-20.2.0-dev, java.vm.name=OpenJDK 64-Bit Server VM, java.vm.version=11.0.8+1):
    AVX3Threshold at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.GraalHotSpotVMConfig.<init>(GraalHotSpotVMConfig.java:157) [value: 4096]
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.GraalHotSpotVMConfigAccess.reportErrors(GraalHotSpotVMConfigAccess.java:224)
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.GraalHotSpotVMConfig.<init>(GraalHotSpotVMConfig.java:67)
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalRuntime.<init>(HotSpotGraalRuntime.java:161)
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:156)
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:134)
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:52)
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.getCompiler(HotSpotJVMCIRuntime.java:425)
	at com.oracle.svm.hosted.c.GraalAccess.getGraalCapability(GraalAccess.java:50)
	at com.oracle.svm.hosted.c.GraalAccess.getOriginalTarget(GraalAccess.java:38)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.isValidArchitecture(NativeImageGeneratorRunner.java:221)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.verifyValidJavaVersionAndPlatform(NativeImageGeneratorRunner.java:426)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:232)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:518)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:117)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:546)
Error: Image build request failed with exit status 1
```

Note that [JDK-8221092](https://bugs.openjdk.java.net/browse/JDK-8221092) got backported to OpenJDK 11.0.6 which introduced this flag.

**Comment by dougxc** [comment]
This is going to require enhancing the `expectPresent` guard for `AVX3Threshold` at https://github.com/oracle/graal/blob/6fe68785c8a20ebd905e922d42e6ed22a431702b/compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/GraalHotSpotVMConfig.java#L157
Do you think you can come up with a PR for that @jerboaa ?

**Comment by jerboaa** [comment]
@dougxc Yes. See #2403
