### ISSUE TITLE
Formatting of PolyglotException for internal errors is redundant in some cases

### ISSUE THREAD

**Issue by chrisseaton** [oracle/graal#2404]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **`268c16f23cd527949a340aa1917956638583f455`**
 - CE or EE: **CE**
 - JDK version: **JDK8**
 - OS and OS Version: **macOS Catalina**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
OpenJDK 64-Bit Server VM (25.242-b06-jvmci-20.1-b01) for bsd-amd64 JRE (1.8.0), built on Mar 29 2020 08:11:18 by "graal" with gcc 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)
```

**Have you verified this issue still happens when using the latest snapshot?**
Not latest snapshot, but recent TruffleRuby and Graal.

**Describe the issue**
The formatting of `PolyglotException` is redundant.

**Code snippet or code repository that reproduces the issue**
```
% ruby --coverage -e 14
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. `git clone git@github.com:oracle/truffleruby.git`
2. `cd truffleruby`
3. `git checkout d1230ebe1257d85dd1e7de7fd12ab5a482230ebb`
4. `tool/jt.rb build --env native`
5. `tool/jt.rb --use native ruby --coverage -e 14`

**Expected behavior**
I would expect `PolyglotException` to not print the stacktrace twice, and to not mention guest frames if there aren't any.

Actual:

```
truffleruby: an exception escaped out of the interpreter - this is an implementation bug
org.graalvm.polyglot.PolyglotException: java.lang.NullPointerException
	at com.oracle.truffle.polyglot.EngineAccessor$EngineImpl.getCurrentContext(EngineAccessor.java:347)
	at com.oracle.truffle.api.TruffleLanguage.getCurrentContext(TruffleLanguage.java:1485)
	at org.truffleruby.RubyLanguage.getCurrentContext(RubyLanguage.java:149)
	at org.truffleruby.language.RubyContextSourceNode.getContext(RubyContextSourceNode.java:69)
	at org.truffleruby.language.LazyRubyNode.getOrCreateMasterResolution(LazyRubyNode.java:93)
	at org.truffleruby.language.LazyRubyNode.lambda$resolve$0(LazyRubyNode.java:76)
	at com.oracle.truffle.api.nodes.Node.atomic(Node.java:577)
	at org.truffleruby.language.LazyRubyNode.resolve(LazyRubyNode.java:71)
	at org.truffleruby.language.LazyRubyNode.materializeInstrumentableNodes(LazyRubyNode.java:57)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$AbstractNodeVisitor.materializeSyntaxNodes(InstrumentationHandler.java:1668)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$AbstractNodeVisitor.materialize(InstrumentationHandler.java:1573)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$AbstractNodeVisitor.visit(InstrumentationHandler.java:1534)
	at com.oracle.truffle.api.nodes.NodeUtil.forEachChild(NodeUtil.java:468)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$AbstractNodeVisitor.visit(InstrumentationHandler.java:1561)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoot(InstrumentationHandler.java:1204)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoots(InstrumentationHandler.java:747)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.addSourceSectionBinding(InstrumentationHandler.java:486)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.attachSourceSectionListener(InstrumentationHandler.java:1043)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.access$2700(InstrumentationHandler.java:93)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$AbstractInstrumenter.attachLoadSourceSectionListener(InstrumentationHandler.java:2170)
	at com.oracle.truffle.tools.coverage.CoverageTracker.instrumentLoadedStatements(CoverageTracker.java:279)
	at com.oracle.truffle.tools.coverage.CoverageTracker.instrument(CoverageTracker.java:256)
	at com.oracle.truffle.tools.coverage.CoverageTracker.start(CoverageTracker.java:143)
	at com.oracle.truffle.tools.coverage.impl.CoverageInstrument.onCreate(CoverageInstrument.java:167)
	at com.oracle.truffle.api.instrumentation.TruffleInstrument$Env.onCreate(TruffleInstrument.java:408)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$InstrumentClientInstrumenter.create(InstrumentationHandler.java:1856)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.createInstrument(InstrumentationHandler.java:396)
	at com.oracle.truffle.api.instrumentation.InstrumentAccessor$InstrumentImpl.createInstrument(InstrumentAccessor.java:103)
	at com.oracle.truffle.polyglot.PolyglotInstrument.ensureCreated(PolyglotInstrument.java:128)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.ensureInstrumentsCreated(PolyglotEngineImpl.java:425)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.loadPreinitializedContext(PolyglotEngineImpl.java:1498)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.createContext(PolyglotEngineImpl.java:1442)
	at org.graalvm.polyglot.Context$Builder.build(Context.java:1490)
	at org.truffleruby.launcher.RubyLauncher.createContext(RubyLauncher.java:265)
	at org.truffleruby.launcher.RubyLauncher.runRubyMain(RubyLauncher.java:204)
	at org.truffleruby.launcher.RubyLauncher.launch(RubyLauncher.java:123)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:121)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:70)
	at org.truffleruby.launcher.RubyLauncher.main(RubyLauncher.java:38)
Original Internal Error: 
java.lang.NullPointerException
	at com.oracle.truffle.polyglot.EngineAccessor$EngineImpl.getCurrentContext(EngineAccessor.java:347)
	at com.oracle.truffle.api.TruffleLanguage.getCurrentContext(TruffleLanguage.java:1485)
	at org.truffleruby.RubyLanguage.getCurrentContext(RubyLanguage.java:149)
	at org.truffleruby.language.RubyContextSourceNode.getContext(RubyContextSourceNode.java:69)
	at org.truffleruby.language.LazyRubyNode.getOrCreateMasterResolution(LazyRubyNode.java:93)
	at org.truffleruby.language.LazyRubyNode.lambda$resolve$0(LazyRubyNode.java:76)
	at com.oracle.truffle.api.nodes.Node.atomic(Node.java:577)
	at org.truffleruby.language.LazyRubyNode.resolve(LazyRubyNode.java:71)
	at org.truffleruby.language.LazyRubyNode.materializeInstrumentableNodes(LazyRubyNode.java:57)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$AbstractNodeVisitor.materializeSyntaxNodes(InstrumentationHandler.java:1668)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$AbstractNodeVisitor.materialize(InstrumentationHandler.java:1573)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$AbstractNodeVisitor.visit(InstrumentationHandler.java:1534)
	at com.oracle.truffle.api.nodes.NodeUtil.forEachChild(NodeUtil.java:468)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$AbstractNodeVisitor.visit(InstrumentationHandler.java:1561)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoot(InstrumentationHandler.java:1204)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoots(InstrumentationHandler.java:747)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.addSourceSectionBinding(InstrumentationHandler.java:486)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.attachSourceSectionListener(InstrumentationHandler.java:1043)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.access$2700(InstrumentationHandler.java:93)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$AbstractInstrumenter.attachLoadSourceSectionListener(InstrumentationHandler.java:2170)
	at com.oracle.truffle.tools.coverage.CoverageTracker.instrumentLoadedStatements(CoverageTracker.java:279)
	at com.oracle.truffle.tools.coverage.CoverageTracker.instrument(CoverageTracker.java:256)
	at com.oracle.truffle.tools.coverage.CoverageTracker.start(CoverageTracker.java:143)
	at com.oracle.truffle.tools.coverage.impl.CoverageInstrument.onCreate(CoverageInstrument.java:167)
	at com.oracle.truffle.api.instrumentation.TruffleInstrument$Env.onCreate(TruffleInstrument.java:408)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$InstrumentClientInstrumenter.create(InstrumentationHandler.java:1856)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.createInstrument(InstrumentationHandler.java:396)
	at com.oracle.truffle.api.instrumentation.InstrumentAccessor$InstrumentImpl.createInstrument(InstrumentAccessor.java:103)
	at com.oracle.truffle.polyglot.PolyglotInstrument.ensureCreated(PolyglotInstrument.java:128)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.ensureInstrumentsCreated(PolyglotEngineImpl.java:425)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.loadPreinitializedContext(PolyglotEngineImpl.java:1498)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.createContext(PolyglotEngineImpl.java:1442)
	at org.graalvm.polyglot.Context$Builder.build(Context.java:1490)
	at org.truffleruby.launcher.RubyLauncher.createContext(RubyLauncher.java:265)
	at org.truffleruby.launcher.RubyLauncher.runRubyMain(RubyLauncher.java:204)
	at org.truffleruby.launcher.RubyLauncher.launch(RubyLauncher.java:123)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:121)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:70)
	at org.truffleruby.launcher.RubyLauncher.main(RubyLauncher.java:38)
Caused by: Attached Guest Language Frames (0)
```

Expected:

```truffleruby: an exception escaped out of the interpreter - this is an implementation bug
org.graalvm.polyglot.PolyglotException: java.lang.NullPointerException
	at com.oracle.truffle.polyglot.EngineAccessor$EngineImpl.getCurrentContext(EngineAccessor.java:347)
	at com.oracle.truffle.api.TruffleLanguage.getCurrentContext(TruffleLanguage.java:1485)
	at org.truffleruby.RubyLanguage.getCurrentContext(RubyLanguage.java:149)
	at org.truffleruby.language.RubyContextSourceNode.getContext(RubyContextSourceNode.java:69)
	at org.truffleruby.language.LazyRubyNode.getOrCreateMasterResolution(LazyRubyNode.java:93)
	at org.truffleruby.language.LazyRubyNode.lambda$resolve$0(LazyRubyNode.java:76)
	at com.oracle.truffle.api.nodes.Node.atomic(Node.java:577)
	at org.truffleruby.language.LazyRubyNode.resolve(LazyRubyNode.java:71)
	at org.truffleruby.language.LazyRubyNode.materializeInstrumentableNodes(LazyRubyNode.java:57)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$AbstractNodeVisitor.materializeSyntaxNodes(InstrumentationHandler.java:1668)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$AbstractNodeVisitor.materialize(InstrumentationHandler.java:1573)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$AbstractNodeVisitor.visit(InstrumentationHandler.java:1534)
	at com.oracle.truffle.api.nodes.NodeUtil.forEachChild(NodeUtil.java:468)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$AbstractNodeVisitor.visit(InstrumentationHandler.java:1561)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoot(InstrumentationHandler.java:1204)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoots(InstrumentationHandler.java:747)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.addSourceSectionBinding(InstrumentationHandler.java:486)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.attachSourceSectionListener(InstrumentationHandler.java:1043)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.access$2700(InstrumentationHandler.java:93)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$AbstractInstrumenter.attachLoadSourceSectionListener(InstrumentationHandler.java:2170)
	at com.oracle.truffle.tools.coverage.CoverageTracker.instrumentLoadedStatements(CoverageTracker.java:279)
	at com.oracle.truffle.tools.coverage.CoverageTracker.instrument(CoverageTracker.java:256)
	at com.oracle.truffle.tools.coverage.CoverageTracker.start(CoverageTracker.java:143)
	at com.oracle.truffle.tools.coverage.impl.CoverageInstrument.onCreate(CoverageInstrument.java:167)
	at com.oracle.truffle.api.instrumentation.TruffleInstrument$Env.onCreate(TruffleInstrument.java:408)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$InstrumentClientInstrumenter.create(InstrumentationHandler.java:1856)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.createInstrument(InstrumentationHandler.java:396)
	at com.oracle.truffle.api.instrumentation.InstrumentAccessor$InstrumentImpl.createInstrument(InstrumentAccessor.java:103)
	at com.oracle.truffle.polyglot.PolyglotInstrument.ensureCreated(PolyglotInstrument.java:128)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.ensureInstrumentsCreated(PolyglotEngineImpl.java:425)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.loadPreinitializedContext(PolyglotEngineImpl.java:1498)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.createContext(PolyglotEngineImpl.java:1442)
	at org.graalvm.polyglot.Context$Builder.build(Context.java:1490)
	at org.truffleruby.launcher.RubyLauncher.createContext(RubyLauncher.java:265)
	at org.truffleruby.launcher.RubyLauncher.runRubyMain(RubyLauncher.java:204)
	at org.truffleruby.launcher.RubyLauncher.launch(RubyLauncher.java:123)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:121)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:70)
	at org.truffleruby.launcher.RubyLauncher.main(RubyLauncher.java:38)
```

(The actual exception is https://github.com/oracle/truffleruby/issues/1994, but I'm talking about the exception formatting.)

**Additional context**
Add any other context about the problem here. Specially important are stack traces or log output. Feel free to link to gists or to screenshots if necesary
<details><summary>Details</summary>

```
    PASTE YOUR LOG/STACK TRACE HERE
```
</details>

**Comment by eregon** [comment]
BTW, that `NullPointerException` should really be a more explicit error, without requiring `assert` to be on.

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-23071.

**Comment by chumer** [comment]
We will print internal errors if they have no guest frames.
Not sure we can actually remove the guest frames (0) notice in the end. But that can be fixed with the new TruffleException base class that we plan to do.

We will provide a better error for the NPE here.

**Comment by tzezula** [comment]
https://github.com/oracle/graal/commit/f85f90ea02afa5cdd2ead6890e93d15befcce6a4
