### ISSUE TITLE
agent is missing resource bundles for spring sample (e.g. javax.servlet.http.LocalStrings)

### ISSUE THREAD

**Issue by aclement** [oracle/graal#2417]
**Describe the issue**
In trying to use pure agent generated configuration to build some of the Spring samples, the agent is missing two resource bundles and they have to be added via command line flags:
```
  -H:IncludeResourceBundles=javax.servlet.LocalStrings \
  -H:IncludeResourceBundles=javax.servlet.http.LocalStrings \
```

These places are found in `javax.http.servlet.HttpServlet`:
```
    private static final String LSTRING_FILE =
        "javax.servlet.http.LocalStrings";
    private static final ResourceBundle lStrings =
        ResourceBundle.getBundle(LSTRING_FILE);
```

and I think `javax.servlet.GenericServlet`:
```
    private static final String LSTRING_FILE = "javax.servlet.LocalStrings";
    private static ResourceBundle lStrings =
        ResourceBundle.getBundle(LSTRING_FILE);
```

**Steps to reproduce the issue**
```
1. git clone git@github.com:spring-projects-experimental/spring-graal-native.git
2. cd spring-graal-native
3. ./build.sh (this builds the feature for configuring initialization)
4. cd spring-graal-native-samples/springmvc-tomcat/agent
5. ./build.sh (this will work)
6. ./build.sh (remove the bundle including lines in the native-image call in build.sh and re-run - this will fail)
```

**Describe GraalVM and your environment:**
Graal 20.0 (JDK8) or master (commit 732e2a707c 28-Apr-2020 ) (JDK8)
- MacOS Catalina

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
Caused by: java.util.MissingResourceException: Resource bundle not found javax.servlet.http.LocalStrings. Register the resource bundle using the option -H:IncludeResourceBundles=javax.servlet.http.LocalStrings.
	at com.oracle.svm.core.jdk.LocalizationSupport.getCached(LocalizationSupport.java:66) ~[na:na]
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:53) ~[na:na]
	at javax.servlet.http.HttpServlet.<clinit>(HttpServlet.java:93) ~[springmvc-tomcat-agent:na]
```

**Comment by christianwimmer** [comment]
It's on the list of issues for @vjovanov to fix in 20.2. Non-core parts of the JDK will be treated like the application (like no initialization at build time of these classes). Then @peter-hofer will use the same package/class list for the agent to filter what the agent is tracing.

**Comment by d-kozak** [comment]
I've experimented with this issue and noticed that the resource bundles are no longer being added via command line flags in the sample project. The flags were removed in the commit 
https://github.com/spring-projects-experimental/spring-graalvm-native/commit/b1efa9f70682b6e386a07897c0fd7ad872dd34f7 
(Also, the project was renamed from springmvc-tomcat to webmvc-tomcat). I've run the build script and it worked without the flags. The agent seems to pick up the resource bundles correctly. Therefore I'd like to ask whether you still experience this issue?

**Comment by d-kozak** [comment]
As mentioned previously, bundles are no longer explicitly included in the `build.sh` file and the build succeeded when I tried in September. However, when I tried local build today, I got a Maven failure.
 ```
[INFO] Scanning for projects...
[WARNING] Could not transfer metadata org.springframework.boot:spring-boot-starter-parent:2.5.0-SNAPSHOT/maven-metadata.xml from/to spring-snapshot (https://repo.spring.io/snapshot): Transfer failed for https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-starter-parent/2.5.0-SNAPSHOT/maven-metadata.xml
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.springframework.experimental:spring-native-sample-parent:0.10.0-SNAPSHOT: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:2.5.0-SNAPSHOT from/to spring-snapshot (https://repo.spring.io/snapshot): Transfer failed for https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-starter-parent/2.5.0-SNAPSHOT/spring-boot-starter-parent-2.5.0-SNAPSHOT.pom and 'parent.relativePath' points at no local POM @ org.springframework.experimental:spring-native-sample-parent:0.10.0-SNAPSHOT, /Users/dkozak/tmp/spring-graal-native/samples/maven-parent/pom.xml, line 7, column 10
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.example:webmvc-tomcat:0.0.1-SNAPSHOT (/Users/dkozak/tmp/spring-graal-native/samples/webmvc-tomcat/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.springframework.experimental:spring-native-sample-parent:0.10.0-SNAPSHOT: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:2.5.0-SNAPSHOT from/to spring-snapshot (https://repo.spring.io/snapshot): Transfer failed for https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-starter-parent/2.5.0-SNAPSHOT/spring-boot-starter-parent-2.5.0-SNAPSHOT.pom and 'parent.relativePath' points at no local POM @ org.springframework.experimental:spring-native-sample-parent:0.10.0-SNAPSHOT, /Users/dkozak/tmp/spring-graal-native/samples/maven-parent/pom.xml, line 7, column 10: Connect to repo.spring.io:443 [repo.spring.io/35.241.58.96] failed: Operation timed out (Connection timed out) -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
FAILURE: an error occurred when compiling the native-image.
```
I assume the problem no longer manifests because it was already fixed by last September, but I can't double check locally. Please let me know whether I should proceed somehow about it, otherwise I'll close this issue in the upcoming days.

**Comment by d-kozak** [comment]
Since I received no reaction, I assume it is resolved.
