### ISSUE TITLE
IllegalAccessException when accessing HostObject

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#2424]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **20.0.0**
 - CE or EE: **CE**
 - JDK version: **JDK11**
 - OS and OS Version: **macOS Catalina**
 - Architecture: **amd64**

**Have you verified this issue still happens when using the latest snapshot?**
You can find snapshot builds here: https://github.com/graalvm/graalvm-ce-dev-builds/releases

Nope.

**Describe the issue**
While trying to inspect a Java host object, GraalSqueak crashed because of an `IllegalStateException`. Below is the stack trace.

**Stack trace**
```
ERROR: java.lang.IllegalStateException: java.lang.IllegalAccessException: access to public member failed: sun.java2d.SunGraphics2D.alphafill/sun.java2d.loops.MaskFill/getField, from public Lookup
org.graalvm.polyglot.PolyglotException: java.lang.IllegalStateException: java.lang.IllegalAccessException: access to public member failed: sun.java2d.SunGraphics2D.alphafill/sun.java2d.loops.MaskFill/getField, from public Lookup
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostFieldDesc$MHImpl.makeGetMethodHandle(HostFieldDesc.java:207)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostFieldDesc$MHImpl.get(HostFieldDesc.java:163)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObject$ReadFieldNode.doCached(HostObject.java:1272)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObjectFactory$ReadFieldNodeGen.executeAndSpecialize(HostObjectFactory.java:1271)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObjectFactory$ReadFieldNodeGen.execute(HostObjectFactory.java:1236)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObject.readMember(HostObject.java:254)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObjectGen$InteropLibraryExports$Cached.readMember(HostObjectGen.java:1201)
	at de.hpi.swa.graal.squeak.nodes.plugins.PolyglotPlugin$PrimReadMemberNode.doReadMember(PolyglotPlugin.java:1090)
...
```

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-23072

**Comment by woess** [comment]
Thanks for the report! The bug was that we exposed inaccessible public fields in JDK 11. Should be fixed as of https://github.com/oracle/graal/commit/8a6eea3f1eeb436d1f44bd4501e49a80c61c6722 in master.

**Comment by fniephaus** [comment]
Thanks a lot, @woess!
