### ISSUE TITLE
Static field changed error that wasn't there before in earlier 20.1 builds

### ISSUE THREAD

**Issue by aclement** [oracle/graal#2438]
**Describe the issue**
We have a Spring webflux-r2dbc sample. It was working fine with Graal 20.1 dev release 20200419 but it fails with 20200506. The failure looks like this:
```
[webflux-r2dbc:36675]        image:   3,045.46 ms,  7.54 GB
Fatal error:com.oracle.svm.core.util.VMError$HostedError: com.oracle.svm.core.util.UserError$UserException: Static field or an object referenced from a static field changed during native image generation?
  object:[Ljava.lang.reflect.TypeVariable;@59ca0b26  of class: java.lang.reflect.TypeVariable[]
  reachable through:
    object: sun.reflect.generics.repository.MethodRepository@76d3e68c  of class: sun.reflect.generics.repository.MethodRepository
    object: public abstract reactor.core.publisher.Mono org.springframework.data.repository.reactive.ReactiveCrudRepository.deleteAll(org.reactivestreams.Publisher)  of class: java.lang.reflect.Method
    root: HostedField<$Proxy221.m6 location: 3632   AnalysisField<$Proxy221.m6 accessed: false reads: true written: true>>

	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:72)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:647)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.svm.core.util.UserError$UserException: Static field or an object referenced from a static field changed during native image generation?
  object:[Ljava.lang.reflect.TypeVariable;@59ca0b26  of class: java.lang.reflect.TypeVariable[]
  reachable through:
    object: sun.reflect.generics.repository.MethodRepository@76d3e68c  of class: sun.reflect.generics.repository.MethodRepository
    object: public abstract reactor.core.publisher.Mono org.springframework.data.repository.reactive.ReactiveCrudRepository.deleteAll(org.reactivestreams.Publisher)  of class: java.lang.reflect.Method
    root: HostedField<$Proxy221.m6 location: 3632   AnalysisField<$Proxy221.m6 accessed: false reads: true written: true>>

	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.image.NativeImageHeapWriter.verifyTargetDidNotChange(NativeImageHeapWriter.java:130)
	at com.oracle.svm.hosted.image.NativeImageHeapWriter.writeReference(NativeImageHeapWriter.java:158)
	at com.oracle.svm.hosted.image.NativeImageHeapWriter.write(NativeImageHeapWriter.java:147)
	at com.oracle.svm.hosted.image.NativeImageHeapWriter.writeField(NativeImageHeapWriter.java:141)
	at com.oracle.svm.hosted.image.NativeImageHeapWriter.writeObject(NativeImageHeapWriter.java:344)
	at com.oracle.svm.hosted.image.NativeImageHeapWriter.writeHeap(NativeImageHeapWriter.java:89)
	at com.oracle.svm.hosted.image.NativeBootImage.build(NativeBootImage.java:483)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:636)
	... 6 more
```
I can't tell if it is an app problem or a graalvm problem.  The `shouldNotReachHere` in the stack trace perhaps suggests something graalvm really didn't think it would encounter? I half wondered if related to the changes that have gone in around proxy interfaces and initialization?  Can it just be an app issue about specifying the right run/build time initialization? (If so, can the message be a bit clearer?)

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. git clone https://github.com/spring-projects-experimental/spring-graal-native
2. cd spring-graal-native
3. ./build.sh
4. cd spring-graal-native-samples/webflux-r2dbc
5. mvn -Pgraal clean package

**Describe GraalVM and your environment:**
 - Works on 20.1 (Java8):  20200419. Fails on 20.1 (Java8) 20200506
 - JDK major version: 8
 - OS: MacOS Catalina (and seen on Linux)

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```

[webflux-r2dbc:36675]        image:   3,045.46 ms,  7.54 GB
Fatal error:com.oracle.svm.core.util.VMError$HostedError: com.oracle.svm.core.util.UserError$UserException: Static field or an object referenced from a static field changed during native image generation?
  object:[Ljava.lang.reflect.TypeVariable;@59ca0b26  of class: java.lang.reflect.TypeVariable[]
  reachable through:
    object: sun.reflect.generics.repository.MethodRepository@76d3e68c  of class: sun.reflect.generics.repository.MethodRepository
    object: public abstract reactor.core.publisher.Mono org.springframework.data.repository.reactive.ReactiveCrudRepository.deleteAll(org.reactivestreams.Publisher)  of class: java.lang.reflect.Method
    root: HostedField<$Proxy221.m6 location: 3632   AnalysisField<$Proxy221.m6 accessed: false reads: true written: true>>

	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:72)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:647)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.svm.core.util.UserError$UserException: Static field or an object referenced from a static field changed during native image generation?
  object:[Ljava.lang.reflect.TypeVariable;@59ca0b26  of class: java.lang.reflect.TypeVariable[]
  reachable through:
    object: sun.reflect.generics.repository.MethodRepository@76d3e68c  of class: sun.reflect.generics.repository.MethodRepository
    object: public abstract reactor.core.publisher.Mono org.springframework.data.repository.reactive.ReactiveCrudRepository.deleteAll(org.reactivestreams.Publisher)  of class: java.lang.reflect.Method
    root: HostedField<$Proxy221.m6 location: 3632   AnalysisField<$Proxy221.m6 accessed: false reads: true written: true>>

	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.image.NativeImageHeapWriter.verifyTargetDidNotChange(NativeImageHeapWriter.java:130)
	at com.oracle.svm.hosted.image.NativeImageHeapWriter.writeReference(NativeImageHeapWriter.java:158)
	at com.oracle.svm.hosted.image.NativeImageHeapWriter.write(NativeImageHeapWriter.java:147)
	at com.oracle.svm.hosted.image.NativeImageHeapWriter.writeField(NativeImageHeapWriter.java:141)
	at com.oracle.svm.hosted.image.NativeImageHeapWriter.writeObject(NativeImageHeapWriter.java:344)
	at com.oracle.svm.hosted.image.NativeImageHeapWriter.writeHeap(NativeImageHeapWriter.java:89)
	at com.oracle.svm.hosted.image.NativeBootImage.build(NativeBootImage.java:483)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:636)
	... 6 more
```

**Comment by eginez** [comment]
@aclement is this only happening on docker? or on mac os well?

**Comment by aclement** [comment]
@eginez Those instructions are for Mac too. I managed to sort out the versions that truly did/didnt show the problem for me.

**Comment by sdeleuze** [comment]
I can reproduce it on regular Linux as well, so I think this is not platform specific.

**Comment by eginez** [comment]
fixed with https://github.com/oracle/graal/commit/7965307ff13d759f0e529a339b52a28760dc4d79
