### ISSUE TITLE
Possible classloader problem with GraalVM when used in IntelliJ Plugin

### ISSUE THREAD

**Issue by joaobispo** [oracle/graal#2462]
- GraalVM version or commit id if built from source: 20.0.0
 - CE or EE: CE
 - JDK version: JDK11
 - OS and OS Version: Windows 10
 - Architecture: amd64
 - The output of `java -Xinternalversion`: 
```
OpenJDK 64-Bit Server VM (11+28) for windows-amd64 JRE (11+28), built on Aug 23 2018 03:04:58 by "mach5one" with MS VC++ 15.5 (VS2017)

```

**Have you verified this issue still happens when using the latest snapshot?**
No

**Describe the issue**
I'm trying to use the JavaScript engine of GraalVM inside an IntelliJ plugin, but I'm having the following error:

(triggered when clicking "Tools" in the toolbar of the test IntelliJ IDE)
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider com.oracle.truffle.js.scriptengine.GraalJSEngineFactory could not be instantiated
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider de.lab4inf.math.scripting.javacc.JavaCCScriptEngineFactory could not be instantiated

(triggered when calling the plugin with "Tools->Action" in the toolbar of the test IntelliJ IDE)
2020-05-13 23:15:13,343 [ 13291] ERROR - llij.ide.plugins.PluginManager - No language and polyglot implementation was found on the classpath. Make sure the truffle-api.jar is on the classpath.
java.lang.IllegalStateException: No language and polyglot implementation was found on the classpath. Make sure the truffle-api.jar is on the classpath.

I'm adding the necessary dependencies in the build.gradle file:

compile group: 'org.graalvm.js', name: 'js', version: '20.0.0'
compile group: 'org.graalvm.js', name: 'js-scriptengine', version: '20.0.0'

And in External Libraries, truffle-api.jar appears.

**Code snippet or code repository that reproduces the issue**
```
GraalJSScriptEngine.create();
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. git clone --single-branch --branch graalvm-issue https://github.com/wacfwaef/plugintest.git
2. cd plugintest
3. wget "http://specs.fe.up.pt/tools/lara_libs.zip" -O ./libs/lara_libs.zip
4. unzip -d ./libs ./libs/lara_libs.zip
5. gradle runIde
6. This will launch an IntelliJ IDE. Create a new project, and in the top toolbar, wait until Tools->Action becomes enabled. When it becomes enabled, click it, and it will trigger the problem.

**Expected behavior**

For the JavaScript engine to be found and instantiated.

**Additional context**
Add any other context about the problem here. Specially important are stack traces or log output. Feel free to link to gists or to screenshots if necesary
<details><summary>Details</summary>

```
21:23:22: Executing task 'runIde'...


> Task :compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :patchPluginXml UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes
> Task :instrumentCode
> Task :postInstrumentCode
> Task :jar UP-TO-DATE
> Task :prepareSandbox

> Task :runIde
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.util.ReflectionUtil to method sun.java2d.SunGraphicsEnvironment.isUIScaleEnabled()
WARNING: Please consider reporting this to the maintainers of com.intellij.util.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2020-05-14 21:23:31,063 [   1279]   WARN - j.internal.DebugAttachDetector - Unable to start DebugAttachDetector, please add `--add-exports=java.base/jdk.internal.vm=ALL-UNNAMED` to VM options 
2020-05-14 21:23:34,280 [   4496]   WARN - com.intellij.util.xmlb.Binding - no accessors for class org.jetbrains.kotlin.idea.highlighter.KotlinDefaultHighlightingSettingsProvider 
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider com.oracle.truffle.js.scriptengine.GraalJSEngineFactory could not be instantiated
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider de.lab4inf.math.scripting.javacc.JavaCCScriptEngineFactory could not be instantiated
2020-05-14 21:23:39,142 [   9358]  ERROR - llij.ide.plugins.PluginManager - No language and polyglot implementation was found on the classpath. Make sure the truffle-api.jar is on the classpath. 
java.lang.IllegalStateException: No language and polyglot implementation was found on the classpath. Make sure the truffle-api.jar is on the classpath.
	at org.graalvm.polyglot.Engine$PolyglotInvalid.noPolyglotImplementationFound(Engine.java:840)
	at org.graalvm.polyglot.Engine$PolyglotInvalid.buildEngine(Engine.java:761)
	at org.graalvm.polyglot.Engine$Builder.build(Engine.java:515)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.<init>(GraalJSScriptEngine.java:246)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.create(GraalJSScriptEngine.java:615)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.create(GraalJSScriptEngine.java:597)
	at myplugin.AnAction.actionPerformed(AnAction.java:35)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:266)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:283)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:294)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:263)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:284)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:112)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:83)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:107)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:116)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:121)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:517)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:36)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:539)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:776)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2020-05-14 21:23:39,147 [   9363]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2019.3  Build #IC-193.5233.102 
2020-05-14 21:23:39,147 [   9363]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.4; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-05-14 21:23:39,147 [   9363]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 10 
2020-05-14 21:23:39,151 [   9367]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: plugintest version: 1.0-SNAPSHOT 
2020-05-14 21:23:39,151 [   9367]  ERROR - llij.ide.plugins.PluginManager - Last Action: actiona 

```
</details>

**Comment by boris-spas** [comment]
Tracking internally as Issue GR-24941.

**Comment by valbendan** [comment]
If there is any work aournd for now ?

**Comment by wirthi** [comment]
I am closing this ticket, a lot has changed in our internal implementation in the meantime. If the problem persists with a recent version of GraalVM, please open a new ticket.
