### ISSUE TITLE
Substituted method with lambda fails while the one with anonymous class succeeds

### ISSUE THREAD

**Issue by sdeleuze** [oracle/graal#2479]
In a substitution, we have a method that is using a lambda (it is the original code):
```
@Substitute
public void processConfigBeanDefinitions(BeanDefinitionRegistry registry) {
	configCandidates.sort((bd1, bd2) -> {
			int i1 = ConfigurationClassUtils.getOrder(bd1.getBeanDefinition());
			int i2 = ConfigurationClassUtils.getOrder(bd2.getBeanDefinition());
			return Integer.compare(i1, i2);
		});
}
```

It produces this error:
```
Error: One of @Delete, @Substitute, @AnnotateOriginal, or @Alias must be used: private static int org.springframework.context.annotation.Target_ConfigurationClassPostProcessor.lambda$processConfigBeanDefinitions$0(org.springframework.beans.factory.config.BeanDefinitionHolder,org.springframework.beans.factory.config.BeanDefinitionHolder)
com.oracle.svm.core.util.UserError$UserException: One of @Delete, @Substitute, @AnnotateOriginal, or @Alias must be used: private static int org.springframework.context.annotation.Target_ConfigurationClassPostProcessor.lambda$processConfigBeanDefinitions$0(org.springframework.beans.factory.config.BeanDefinitionHolder,org.springframework.beans.factory.config.BeanDefinitionHolder)
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.core.util.UserError.guarantee(UserError.java:92)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleMethodInAliasClass(AnnotationSubstitutionProcessor.java:324)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:302)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:274)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:230)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:908)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:838)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:536)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
```

If I change it to use an anonymous class like that, it compiles and works fine:
```
@Substitute
public void processConfigBeanDefinitions(BeanDefinitionRegistry registry) {
	configCandidates.sort(new Comparator<BeanDefinitionHolder>() {
			@Override
			public int compare(BeanDefinitionHolder bd1, BeanDefinitionHolder bd2) {
				int i1 = ConfigurationClassUtils.getOrder(bd1.getBeanDefinition());
				int i2 = ConfigurationClassUtils.getOrder(bd2.getBeanDefinition());
				return Integer.compare(i1, i2);
			}
		});
}
```

I would expect the lambda based version working like the anonymous class one.
Tested with GraalVM 20.1.
Please tag this issue with the `spring` label.

**Comment by vjovanov** [comment]
Substitutions should not be used so this ticket is not the highest priority. Moving to 22.1.

**Comment by christianwimmer** [comment]
This is a side-effect of how javac emits bytecode for lambdas: it creates synthetic methods in the class that defines the lambda. These synthetic methods are obviously not annotated and do not have a matching method in the target class, so you get the error.
Unfortunately, there is no good solution for this problem: We do not allow new methods in target classes because method linking can go very wrong for such methods (virtual method dispatch is derived via JVMCI where no substitutions are known).

**Comment by vjovanov** [comment]
We could reduce the confusion by printing an error that explains that no lambdas are allowed in `@Substitute` methods.
