### ISSUE TITLE
cross-compilation on Darwin from AMD64 to AARCH64 fails

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#2482]
**Describe the issue**

When cross-compiling on Darwin to AARCH64 and using the LLVM backend, compilation works fine.

Withouth the LLVM backend, compilation fails with the exception below.
The following parameters are passed to native-image:
```
-Dsvm.targetArch=arm64
-Dsvm.targetName=ios

```

```
Caused by: java.lang.IllegalArgumentException: can only truncate to powers-of-two <= 8
        at com.oracle.objectfile.io.AssemblyBuffer.readTruncatedLong(AssemblyBuffer.java:400)
        at com.oracle.objectfile.macho.MachOUserDefinedSection.markRelocationSite(MachOUserDefinedSection.java:173)
        at com.oracle.objectfile.BasicProgbitsSectionImpl.markRelocationSite(BasicProgbitsSectionImpl.java:118)
        at com.oracle.svm.hosted.image.NativeBootImage.markDataRelocationSiteFromText(NativeBootImage.java:652)
        at com.oracle.svm.hosted.image.NativeBootImage.markRelocationSitesFromMaps(NativeBootImage.java:588)
        at com.oracle.svm.hosted.image.NativeBootImage.build(NativeBootImage.java:513)
```

**Comment by loicottet** [comment]
Fixed by [fe1e2b19](https://github.com/oracle/graal/commit/fe1e2b19fe4ca115da1931a24787b53981fbc3d2)
