### ISSUE TITLE
Twitter finagle native image compiling issue java.lang.invoke.SerializedLambda error

### ISSUE THREAD

**Issue by realradical** [oracle/graal#2487]
**Describe the issue**
I have a project using twitter finagle framework. First I use `Tracing agent` to generate native image configurations. When I try to compile the native image, it gives me the following error. The finagle framework is written in Scala, but according to the error, it seems like it uses java lambda somewhere. Does graal support lambda atm?

`Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.twitter.finagle.toggle.JsonToggleMap$JsonToggles.$deserializeLambda$(java.lang.invoke.SerializedLambda)`

**Steps to reproduce the issue**
https://github.com/twitter/finagle

**Describe GraalVM and your environment:**
 - GraalVM version: 20.0.0.r11-grl
 - JDK major version: 11
 - OS: macOS Catalina
 - Architecture: Intel64

**More details**
```
    native-image --verbose -jar target/scala-2.13/big-brother-hosted.jar big-brother -H:+TraceClassInitialization --initialize-at-build-time=ch.qos.logback
Apply jar:file:///Users/jacob.shao/Dev/big-brother-hosted/target/scala-2.13/big-brother-hosted.jar!/META-INF/native-image/org.scala-lang/scala-lang/native-image.properties
Apply jar:file:///Users/jacob.shao/Dev/big-brother-hosted/target/scala-2.13/big-brother-hosted.jar!/META-INF/native-image/io.netty/transport/native-image.properties
Apply jar:file:///Users/jacob.shao/Dev/big-brother-hosted/target/scala-2.13/big-brother-hosted.jar!/META-INF/native-image/io.netty/handler/native-image.properties
Apply jar:file:///Users/jacob.shao/Dev/big-brother-hosted/target/scala-2.13/big-brother-hosted.jar!/META-INF/native-image/io.netty/common/native-image.properties
Apply jar:file:///Users/jacob.shao/Dev/big-brother-hosted/target/scala-2.13/big-brother-hosted.jar!/META-INF/native-image/io.netty/codec-http2/native-image.properties
Apply jar:file:///Users/jacob.shao/Dev/big-brother-hosted/target/scala-2.13/big-brother-hosted.jar!/META-INF/native-image/io.netty/codec-http/native-image.properties
Apply jar:file:///Users/jacob.shao/Dev/big-brother-hosted/target/scala-2.13/big-brother-hosted.jar!/META-INF/native-image/io.netty/buffer/native-image.properties
Apply jar:file:///Users/jacob.shao/Dev/big-brother-hosted/target/scala-2.13/big-brother-hosted.jar!/META-INF/native-image/com.flipp.dat/native-image.properties
Apply jar:file:///Users/jacob.shao/Dev/big-brother-hosted/target/scala-2.13/big-brother-hosted.jar!/META-INF/native-image/com.flipp.dat/jni-config.json
Apply jar:file:///Users/jacob.shao/Dev/big-brother-hosted/target/scala-2.13/big-brother-hosted.jar!/META-INF/native-image/com.flipp.dat/reflect-config.json
Apply jar:file:///Users/jacob.shao/Dev/big-brother-hosted/target/scala-2.13/big-brother-hosted.jar!/META-INF/native-image/com.flipp.dat/resource-config.json
Apply jar:file:///Users/jacob.shao/Dev/big-brother-hosted/target/scala-2.13/big-brother-hosted.jar!/META-INF/native-image/com.flipp.dat/proxy-config.json
StartServer [
/Users/jacob.shao/.sdkman/candidates/java/20.0.0.r11-grl/bin/java \
-cp \
/Users/jacob.shao/.sdkman/candidates/java/20.0.0.r11-grl/lib/svm/builder/llvm-wrapper-shadowed.jar:/Users/jacob.shao/.sdkman/candidates/java/20.0.0.r11-grl/lib/svm/builder/svm.jar:/Users/jacob.shao/.sdkman/candidates/java/20.0.0.r11-grl/lib/svm/builder/objectfile.jar:/Users/jacob.shao/.sdkman/candidates/java/20.0.0.r11-grl/lib/svm/builder/graal-llvm.jar:/Users/jacob.shao/.sdkman/candidates/java/20.0.0.r11-grl/lib/svm/builder/llvm-platform-specific-shadowed.jar:/Users/jacob.shao/.sdkman/candidates/java/20.0.0.r11-grl/lib/svm/builder/javacpp-shadowed.jar:/Users/jacob.shao/.sdkman/candidates/java/20.0.0.r11-grl/lib/svm/builder/svm-llvm.jar:/Users/jacob.shao/.sdkman/candidates/java/20.0.0.r11-grl/lib/svm/builder/pointsto.jar \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
-Djava.lang.invoke.stringConcat=BC_SB \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.runtime=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.code=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.aarch64=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.amd64=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.hotspot=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.services=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.common=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.code.site=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.code.stack=ALL-UNNAMED \
--add-opens \
jdk.internal.vm.compiler/org.graalvm.compiler.debug=ALL-UNNAMED \
--add-opens \
jdk.internal.vm.compiler/org.graalvm.compiler.nodes=ALL-UNNAMED \
--add-opens \
jdk.unsupported/sun.reflect=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.module=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.ref=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.reflect=ALL-UNNAMED \
--add-opens \
java.base/java.io=ALL-UNNAMED \
--add-opens \
java.base/java.lang=ALL-UNNAMED \
--add-opens \
java.base/java.lang.reflect=ALL-UNNAMED \
--add-opens \
java.base/java.lang.invoke=ALL-UNNAMED \
--add-opens \
java.base/java.lang.ref=ALL-UNNAMED \
--add-opens \
java.base/java.net=ALL-UNNAMED \
--add-opens \
java.base/java.nio=ALL-UNNAMED \
--add-opens \
java.base/java.nio.file=ALL-UNNAMED \
--add-opens \
java.base/java.security=ALL-UNNAMED \
--add-opens \
java.base/javax.crypto=ALL-UNNAMED \
--add-opens \
java.base/java.util=ALL-UNNAMED \
--add-opens \
java.base/java.util.concurrent.atomic=ALL-UNNAMED \
--add-opens \
java.base/sun.security.x509=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.logger=ALL-UNNAMED \
--add-opens \
org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED \
--add-opens \
org.graalvm.sdk/org.graalvm.polyglot=ALL-UNNAMED \
--add-opens \
org.graalvm.truffle/com.oracle.truffle.polyglot=ALL-UNNAMED \
--add-opens \
org.graalvm.truffle/com.oracle.truffle.api.impl=ALL-UNNAMED \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Duser.country=US \
-Duser.language=en \
-Djava.awt.headless=true \
-Dorg.graalvm.version=20.0.0 \
-Dorg.graalvm.config=CE \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
--module-path \
/Users/jacob.shao/.sdkman/candidates/java/20.0.0.r11-grl/lib/truffle/truffle-api.jar \
-javaagent:/Users/jacob.shao/.sdkman/candidates/java/20.0.0.r11-grl/lib/svm/builder/svm.jar=traceInitialization \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-Xmx6871947672 \
-Xms1g \
-Dgraal.LogFile=%e \
com.oracle.svm.hosted.server.NativeImageBuildServer \
-port=0 \
-logFile=/Users/jacob.shao/.native-image/machine-id-hostid-0/session-id-f74/server-id-e8c50d5bbb4a8ee3733e57533e011da1629f89847f0f0b53ec97d26a0741cd0b013a48c70fae234cbfcc92e14afbe5501144578b629187a4081b99c33943b8a7/server.log
]
Build on Server(pid: 4011, port: 63810)*
SendBuildRequest [
-task=com.oracle.svm.hosted.NativeImageGeneratorRunner
-imagecp
/Users/jacob.shao/.sdkman/candidates/java/20.0.0.r11-grl/lib/svm/builder/llvm-wrapper-shadowed.jar:/Users/jacob.shao/.sdkman/candidates/java/20.0.0.r11-grl/lib/svm/builder/svm.jar:/Users/jacob.shao/.sdkman/candidates/java/20.0.0.r11-grl/lib/svm/builder/objectfile.jar:/Users/jacob.shao/.sdkman/candidates/java/20.0.0.r11-grl/lib/svm/builder/graal-llvm.jar:/Users/jacob.shao/.sdkman/candidates/java/20.0.0.r11-grl/lib/svm/builder/llvm-platform-specific-shadowed.jar:/Users/jacob.shao/.sdkman/candidates/java/20.0.0.r11-grl/lib/svm/builder/javacpp-shadowed.jar:/Users/jacob.shao/.sdkman/candidates/java/20.0.0.r11-grl/lib/svm/builder/svm-llvm.jar:/Users/jacob.shao/.sdkman/candidates/java/20.0.0.r11-grl/lib/svm/builder/pointsto.jar:/Users/jacob.shao/.sdkman/candidates/java/20.0.0.r11-grl/lib/svm/library-support.jar:/Users/jacob.shao/Dev/big-brother-hosted/target/scala-2.13/big-brother-hosted.jar
-H:Path=/Users/jacob.shao/Dev/big-brother-hosted
-H:Class=com.flipp.dat.BigBrotherHostedServer
-H:ClassInitialization=scala.runtime.Statics$VM:build_time
-H:ReflectionConfigurationResources=META-INF/native-image/io.netty/transport/reflection-config.json
-H:ClassInitialization=io.netty.handler.ssl.util.ThreadLocalInsecureRandom:run_time
-H:ClassInitialization=io.netty.util.AbstractReferenceCounted:run_time,io.netty.util.concurrent.GlobalEventExecutor:run_time,io.netty.util.concurrent.ImmediateEventExecutor:run_time,io.netty.util.concurrent.ScheduledFutureTask:run_time,io.netty.util.internal.ThreadLocalRandom:run_time
-H:ClassInitialization=io.netty.handler.codec.http2.Http2CodecUtil:run_time,io.netty.handler.codec.http2.Http2ClientUpgradeCodec:run_time,io.netty.handler.codec.http2.Http2ConnectionHandler:run_time,io.netty.handler.codec.http2.DefaultHttp2FrameWriter:run_time
-H:ClassInitialization=io.netty:build_time
-H:ClassInitialization=io.netty.handler.codec.http.HttpObjectEncoder:run_time,io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder:run_time,io.netty.handler.codec.http.websocketx.extensions.compression.DeflateDecoder:run_time
-H:ClassInitialization=io.netty.buffer.PooledByteBufAllocator:run_time,io.netty.buffer.ByteBufAllocator:run_time,io.netty.buffer.ByteBufUtil:run_time,io.netty.buffer.AbstractReferenceCountedByteBuf:run_time
-H:+ReportExceptionStackTraces
-H:+AllowIncompleteClasspath
-H:FallbackThreshold=0
-H:JNIConfigurationResources=META-INF/native-image/com.flipp.dat/jni-config.json
-H:ReflectionConfigurationResources=META-INF/native-image/com.flipp.dat/reflect-config.json
-H:ResourceConfigurationResources=META-INF/native-image/com.flipp.dat/resource-config.json
-H:DynamicProxyConfigurationResources=META-INF/native-image/com.flipp.dat/proxy-config.json
-H:+TraceClassInitialization
-H:ClassInitialization=ch.qos.logback:build_time
-H:CLibraryPath=/Users/jacob.shao/.sdkman/candidates/java/20.0.0.r11-grl/lib/svm/clibraries/darwin-amd64
-H:Name=big-brother
]
[big-brother:4011]    classlist:  13,151.14 ms,  1.60 GB
[big-brother:4011]        (cap):   2,489.25 ms,  1.60 GB
[big-brother:4011]        setup:   4,312.14 ms,  1.60 GB
[big-brother:4011]     analysis:  17,271.83 ms,  1.60 GB
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.twitter.finagle.toggle.JsonToggleMap$JsonToggles.$deserializeLambda$(java.lang.invoke.SerializedLambda)
Parsing context:
	parsing com.oracle.svm.reflect.JsonToggleMap$JsonToggles_$deserializeLambda$_bb8a412c8a9871c0e2c8b340b9bf729d80fe599f_96.invoke(Unknown Source)
	parsing java.lang.reflect.Method.invoke(Method.java:566)
	parsing ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:66)
	parsing ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:119)
	parsing ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:419)
	parsing ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	parsing ch.qos.logback.classic.Logger.log(Logger.java:765)
	parsing io.netty.util.internal.logging.LocationAwareSlf4JLogger.log(LocationAwareSlf4JLogger.java:46)
	parsing io.netty.util.internal.logging.LocationAwareSlf4JLogger.warn(LocationAwareSlf4JLogger.java:209)
	parsing io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:89)
	parsing io.netty.channel.nio.AbstractNioMessageChannel.<init>(AbstractNioMessageChannel.java:42)
	parsing io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:89)
	parsing io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:75)
	parsing com.oracle.svm.reflect.NioServerSocketChannel_constructor_cd19a285246874e5b0af2e941d291a26dc1e5b40_5.newInstance(Unknown Source)
	parsing java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	parsing java.util.concurrent.ForkJoinPool.newInstanceFromSystemProperty(ForkJoinPool.java:2329)
	parsing java.util.concurrent.ForkJoinPool.<init>(ForkJoinPool.java:2345)
	parsing com.oracle.svm.core.jdk.ForkJoinPoolCommonAccessor.initializeCommonPool(RecomputedFields.java:402)
	parsing com.oracle.svm.core.jdk.ForkJoinPoolCommonAccessor.get(RecomputedFields.java:391)
	parsing java.util.concurrent.ForkJoinTask.tryExternalHelp(ForkJoinTask.java:380)
	parsing java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:323)
	parsing java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:412)
	parsing java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	parsing java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	parsing java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	parsing java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	parsing java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	parsing sun.util.locale.provider.LocaleResources.getZoneStrings(LocaleResources.java:331)
	parsing sun.util.locale.provider.TimeZoneNameProviderImpl.getZoneStrings(TimeZoneNameProviderImpl.java:138)
	parsing sun.util.cldr.CLDRTimeZoneNameProviderImpl.getZoneStrings(CLDRTimeZoneNameProviderImpl.java:129)
	parsing sun.util.locale.provider.TimeZoneNameUtility.loadZoneStrings(TimeZoneNameUtility.java:86)
	parsing sun.util.locale.provider.TimeZoneNameUtility.getZoneStrings(TimeZoneNameUtility.java:72)
	parsing java.text.DateFormatSymbols.getZoneStringsImpl(DateFormatSymbols.java:844)
	parsing java.text.DateFormatSymbols.getZoneStringsWrapper(DateFormatSymbols.java:838)
	parsing java.text.DateFormatSymbols.hashCode(DateFormatSymbols.java:666)
	parsing java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	parsing java.util.concurrent.ConcurrentHashMap.equals(ConcurrentHashMap.java:1360)
	parsing org.graalvm.collections.EconomicMapImpl.compareKeys(EconomicMapImpl.java:276)
	parsing org.graalvm.collections.EconomicMapImpl.findLinear(EconomicMapImpl.java:263)
	parsing org.graalvm.collections.EconomicMapImpl.find(EconomicMapImpl.java:256)
	parsing org.graalvm.collections.EconomicMapImpl.get(EconomicMapImpl.java:245)
	parsing com.oracle.svm.core.option.SubstrateOptionsParser.parseOption(SubstrateOptionsParser.java:201)
	parsing com.oracle.svm.core.option.RuntimeOptionParser.parseOptionAtRuntime(RuntimeOptionParser.java:196)
	parsing com.oracle.svm.core.option.RuntimeOptionParser.parse(RuntimeOptionParser.java:166)
	parsing com.oracle.svm.core.option.RuntimeOptionParser.parseAndConsumeAllOptions(RuntimeOptionParser.java:77)
	parsing com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:132)
	parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:327)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:346)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:511)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of scala.runtime.LambdaDeserialize are allowed in the image heap as this class should be initialized at image runtime. Object has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked.
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.checkImageHeapInstance(ClassInitializationFeature.java:173)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:534)
	at com.oracle.svm.hosted.analysis.flow.SVMMethodTypeFlowBuilder.registerUsedElements(SVMMethodTypeFlowBuilder.java:82)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:229)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:340)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	... 11 more
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1527)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1289)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1250)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1209)
	at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1707)
```

**Comment by vjovanov** [comment]
This should be fixed. We run finagle in benchmarks now. If not, please reopen.
