### ISSUE TITLE
The crash happens when compile a Netty project

### ISSUE THREAD

**Issue by floating-cat** [oracle/graal#2495]
**Describe the issue**
Native-image fails to compile a Netty & Scala project. It crashes and creates an error report file.

**Steps to reproduce the issue**
1. git clone --single-branch --branch graalvm-test https://github.com/floating-cat/star-link.git
2. Install SBT (https://www.scala-sbt.org/).
3. If your native-image path is not `/usr/lib/jvm/java-11-graalvm/bin/native-image`, open the build.sbt file in this project's root directory. And edit line 17 to change the path.
4. Run `sbt "link / graalvm-native-image:packageBin"` in this project root directory from the terminal.

**Describe GraalVM and your environment:**
 - GraalVM version: CE 20.1.0 (can also be reproduced in the CE 20.0.0)
 - JDK major version: 11
 - OS: Arch Linux
 - Kernel: 5.6.13-arch1-1
 - Architecture: AMD64

**More details**
When I use `-agentlib:native-image-agent=` to run my project, I can see a warning message `WARNING: Error processing trace entry: java.lang.IndexOutOfBoundsException: start 3, end 2, length 3: {caller_class=io.netty.internal.tcnative.SSL, result=true, args=[], function=NewObjectArray, tracer=jni, class=[[B}` when using this flag.
I use the generated tracing agent files for running the native image command. These files are placed in `link/src/graal`

```
[info] Executing [
[info] /usr/lib/jvm/java-11-graalvm/bin/java \
[info] -XX:+UseParallelGC \
[info] -XX:+UnlockExperimentalVMOptions \
[info] -XX:+EnableJVMCI \
[info] -Dtruffle.TrustAllTruffleRuntimeProviders=true \
[info] -Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
[info] -Dgraalvm.ForcePolyglotInvalid=true \
[info] -Dgraalvm.locatorDisabled=true \
[info] -Dsubstratevm.IgnoreGraalVersionCheck=true \
[info] -Djava.lang.invoke.stringConcat=BC_SB \
[info] --add-exports \
[info] jdk.internal.vm.ci/jdk.vm.ci.runtime=ALL-UNNAMED \
[info] --add-exports \
[info] jdk.internal.vm.ci/jdk.vm.ci.code=ALL-UNNAMED \
[info] --add-exports \
[info] jdk.internal.vm.ci/jdk.vm.ci.aarch64=ALL-UNNAMED \
[info] --add-exports \
[info] jdk.internal.vm.ci/jdk.vm.ci.amd64=ALL-UNNAMED \
[info] --add-exports \
[info] jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED \
[info] --add-exports \
[info] jdk.internal.vm.ci/jdk.vm.ci.hotspot=ALL-UNNAMED \
[info] --add-exports \
[info] jdk.internal.vm.ci/jdk.vm.ci.services=ALL-UNNAMED \
[info] --add-exports \
[info] jdk.internal.vm.ci/jdk.vm.ci.common=ALL-UNNAMED \
[info] --add-exports \
[info] jdk.internal.vm.ci/jdk.vm.ci.code.site=ALL-UNNAMED \
[info] --add-exports \
[info] jdk.internal.vm.ci/jdk.vm.ci.code.stack=ALL-UNNAMED \
[info] --add-opens \
[info] jdk.internal.vm.compiler/org.graalvm.compiler.debug=ALL-UNNAMED \
[info] --add-opens \
[info] jdk.internal.vm.compiler/org.graalvm.compiler.nodes=ALL-UNNAMED \
[info] --add-opens \
[info] jdk.unsupported/sun.reflect=ALL-UNNAMED \
[info] --add-opens \
[info] java.base/jdk.internal.module=ALL-UNNAMED \
[info] --add-opens \
[info] java.base/jdk.internal.ref=ALL-UNNAMED \
[info] --add-opens \
[info] java.base/jdk.internal.reflect=ALL-UNNAMED \
[info] --add-opens \
[info] java.base/java.io=ALL-UNNAMED \
[info] --add-opens \
[info] java.base/java.lang=ALL-UNNAMED \
[info] --add-opens \
[info] java.base/java.lang.reflect=ALL-UNNAMED \
[info] --add-opens \
[info] java.base/java.lang.invoke=ALL-UNNAMED \
[info] --add-opens \
[info] java.base/java.lang.ref=ALL-UNNAMED \
[info] --add-opens \
[info] java.base/java.net=ALL-UNNAMED \
[info] --add-opens \
[info] java.base/java.nio=ALL-UNNAMED \
[info] --add-opens \
[info] java.base/java.nio.file=ALL-UNNAMED \
[info] --add-opens \
[info] java.base/java.security=ALL-UNNAMED \
[info] --add-opens \
[info] java.base/javax.crypto=ALL-UNNAMED \
[info] --add-opens \
[info] java.base/java.util=ALL-UNNAMED \
[info] --add-opens \
[info] java.base/java.util.concurrent.atomic=ALL-UNNAMED \
[info] --add-opens \
[info] java.base/sun.security.x509=ALL-UNNAMED \
[info] --add-opens \
[info] java.base/jdk.internal.logger=ALL-UNNAMED \
[info] --add-opens \
[info] org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED \
[info] --add-opens \
[info] org.graalvm.sdk/org.graalvm.polyglot=ALL-UNNAMED \
[info] --add-opens \
[info] org.graalvm.truffle/com.oracle.truffle.polyglot=ALL-UNNAMED \
[info] --add-opens \
[info] org.graalvm.truffle/com.oracle.truffle.api.impl=ALL-UNNAMED \
[info] -XX:+UseJVMCINativeLibrary \
[info] -Xss10m \
[info] -Xms1g \
[info] -Xmx6612130200 \
[info] -Duser.country=US \
[info] -Duser.language=en \
[info] -Djava.awt.headless=true \
[info] -Dorg.graalvm.version=20.1.0 \
[info] -Dorg.graalvm.config= \
[info] -Dcom.oracle.graalvm.isaot=true \
[info] -Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
[info] -Xshare:off \
[info] --module-path \
[info] /usr/lib/jvm/java-11-graalvm/lib/truffle/truffle-api.jar \
[info] -javaagent:/usr/lib/jvm/java-11-graalvm/lib/svm/builder/svm.jar=traceInitialization \
[info] -Djdk.internal.lambda.disableEagerInitialization=true \
[info] -Djdk.internal.lambda.eagerlyInitialize=false \
[info] -Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
[info] -cp \
[info] /usr/lib/jvm/java-11-graalvm/lib/svm/builder/javacpp-shadowed.jar:/usr/lib/jvm/java-11-graalvm/lib/svm/builder/llvm-platform-specific-shadowed.jar:/usr/lib/jvm/java-11-graalvm/lib/svm/builder/llvm-wrapper-shadowed.jar:/usr/lib/jvm/java-11-graalvm/lib/svm/builder/objectfile.jar:/usr/lib/jvm/java-11-graalvm/lib/svm/builder/pointsto.jar:/usr/lib/jvm/java-11-graalvm/lib/svm/builder/svm-llvm.jar:/usr/lib/jvm/java-11-graalvm/lib/svm/builder/svm.jar \
[info] 'com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus' \
[info] -watchpid \
[info] 70182 \
[info] -imagecp \
[info] /usr/lib/jvm/java-11-graalvm/lib/svm/builder/javacpp-shadowed.jar:/usr/lib/jvm/java-11-graalvm/lib/svm/builder/llvm-platform-specific-shadowed.jar:/usr/lib/jvm/java-11-graalvm/lib/svm/builder/llvm-wrapper-shadowed.jar:/usr/lib/jvm/java-11-graalvm/lib/svm/builder/objectfile.jar:/usr/lib/jvm/java-11-graalvm/lib/svm/builder/pointsto.jar:/usr/lib/jvm/java-11-graalvm/lib/svm/builder/svm-llvm.jar:/usr/lib/jvm/java-11-graalvm/lib/svm/builder/svm.jar:/usr/lib/jvm/java-11-graalvm/lib/svm/library-support.jar:/home/xxx/Projects/star-link/link/target/scala-2.13/link_2.13-0.1.jar:/home/xxx/Projects/star-link/client/target/scala-2.13/client_2.13-0.1.jar:/home/xxx/Projects/star-link/common/target/scala-2.13/common_2.13-0.1.jar:/home/xxx/Projects/star-link/server/target/scala-2.13/server_2.13-0.1.jar:/home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.2/scala-library-2.13.2.jar:/home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/com/monovore/decline_2.13/1.2.0/decline_2.13-1.2.0.jar:/home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/org/typelevel/cats-core_2.13/2.0.0/cats-core_2.13-2.0.0.jar:/home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-all/4.1.50.Final/netty-all-4.1.50.Final.jar:/home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-transport-native-epoll/4.1.50.Final/netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar:/home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-transport-native-kqueue/4.1.50.Final/netty-transport-native-kqueue-4.1.50.Final-osx-x86_64.jar:/home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-tcnative-boringssl-static/2.0.30.Final/netty-tcnative-boringssl-static-2.0.30.Final.jar:/home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/commons-codec/commons-codec/1.14/commons-codec-1.14.jar:/home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/com/github/pureconfig/pureconfig_2.13/0.12.3/pureconfig_2.13-0.12.3.jar:/home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/com/github/seancfoley/ipaddress/5.3.1/ipaddress-5.3.1.jar:/home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.13.3/log4j-api-2.13.3.jar:/home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.13.3/log4j-core-2.13.3.jar:/home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/org/typelevel/cats-macros_2.13/2.0.0/cats-macros_2.13-2.0.0.jar:/home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/org/typelevel/cats-kernel_2.13/2.0.0/cats-kernel_2.13-2.0.0.jar:/home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-common/4.1.50.Final/netty-common-4.1.50.Final.jar:/home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-buffer/4.1.50.Final/netty-buffer-4.1.50.Final.jar:/home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-transport/4.1.50.Final/netty-transport-4.1.50.Final.jar:/home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-transport-native-unix-common/4.1.50.Final/netty-transport-native-unix-common-4.1.50.Final.jar:/home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/com/github/pureconfig/pureconfig-core_2.13/0.12.3/pureconfig-core_2.13-0.12.3.jar:/home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/com/github/pureconfig/pureconfig-generic_2.13/0.12.3/pureconfig-generic_2.13-0.12.3.jar:/home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-resolver/4.1.50.Final/netty-resolver-4.1.50.Final.jar:/home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/com/github/pureconfig/pureconfig-macros_2.13/0.12.3/pureconfig-macros_2.13-0.12.3.jar:/home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/com/typesafe/config/1.4.0/config-1.4.0.jar:/home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/com/github/pureconfig/pureconfig-generic-base_2.13/0.12.3/pureconfig-generic-base_2.13-0.12.3.jar:/home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/com/chuusai/shapeless_2.13/2.3.3/shapeless_2.13-2.3.3.jar \
[info] -H:Path=/home/xxx/Projects/star-link/link/target/graalvm-native-image \
[info] -H:ClassInitialization=io.netty.handler.codec.http2.Http2CodecUtil:run_time,io.netty.handler.codec.http2.Http2ClientUpgradeCodec:run_time,io.netty.handler.codec.http2.Http2ConnectionHandler:run_time,io.netty.handler.codec.http2.DefaultHttp2FrameWriter:run_time \
[info] -H:ClassInitialization=io.netty:build_time \
[info] -H:ClassInitialization=io.netty.handler.codec.http.HttpObjectEncoder:run_time,io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder:run_time,io.netty.handler.codec.http.websocketx.extensions.compression.DeflateDecoder:run_time \
[info] -H:ClassInitialization=io.netty.handler.ssl.util.ThreadLocalInsecureRandom:run_time \
[info] -H:ClassInitialization=io.netty.util.AbstractReferenceCounted:run_time,io.netty.util.concurrent.GlobalEventExecutor:run_time,io.netty.util.concurrent.ImmediateEventExecutor:run_time,io.netty.util.concurrent.ScheduledFutureTask:run_time,io.netty.util.internal.ThreadLocalRandom:run_time \
[info] -H:ClassInitialization=io.netty.buffer.PooledByteBufAllocator:run_time,io.netty.buffer.ByteBufAllocator:run_time,io.netty.buffer.ByteBufUtil:run_time,io.netty.buffer.AbstractReferenceCountedByteBuf:run_time \
[info] -H:ReflectionConfigurationResources=META-INF/native-image/io.netty/transport/reflection-config.json \
[info] -H:Name=link \
[info] -H:+TraceClassInitialization \
[info] -H:+ReportExceptionStackTraces \
[info] -H:+RemoveSaturatedTypeFlows \
[info] -H:+DumpTargetInfo \
[info] -H:CLibraryPath=/usr/lib/jvm/java-11-graalvm/lib/svm/clibraries/linux-amd64 \
[info] -H:ReflectionConfigurationFiles=/home/xxx/Projects/star-link/link/src/graal/reflect-config.json \
[info] -H:DynamicProxyConfigurationFiles=/home/xxx/Projects/star-link/link/src/graal/proxy-config.json \
[info] -H:ResourceConfigurationFiles=/home/xxx/Projects/star-link/link/src/graal/resource-config.json \
[info] -H:JNIConfigurationFiles=/home/xxx/Projects/star-link/link/src/graal/jni-config.json \
[info] -H:Class=cl.monsoon.star.link.Star \
[info] ]
[info] [link:70204]    classlist:   7,655.33 ms,  1.17 GB
[info] [link:70204]        (cap):     785.30 ms,  1.17 GB
[info] [link:70204]        setup:   2,484.00 ms,  1.18 GB
[info] # Building image for target platform: org.graalvm.nativeimage.Platform$LINUX_AMD64
[info] # Using native toolchain:
[info] #   Name: GNU project C and C++ compiler (gcc)
[info] #   Vendor: pc
[info] #   Version: 10.1.0
[info] #   Target architecture: x86_64
[info] #   Path: /usr/bin/gcc
[info] # Using CLibrary: com.oracle.svm.core.c.libc.GLibc
[error] ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider com.oracle.truffle.js.scriptengine.GraalJSEngineFactory could not be instantiated
[info] #
[info] # A fatal error has been detected by the Java Runtime Environment:
[info] #
[info] #  SIGSEGV (0xb) at pc=0x00007f93e45f7160, pid=70204, tid=70276
[info] #
[info] # JRE version: OpenJDK Runtime Environment GraalVM CE 20.1.0 (11.0.7+10) (build 11.0.7+10-jvmci-20.1-b02)
[info] # Java VM: OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (11.0.7+10-jvmci-20.1-b02, mixed mode, tiered, jvmci, jvmci compiler, compressed oops, parallel gc, linux-amd64)
[info] # Problematic frame:
[info] # C  0x00007f93e45f7160
[info] #
[info] # Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/xxx/Projects/star-link/link/target/graalvm-native-image/core.70204)
[info] #
[info] # An error report file with more information is saved as:
[info] # /home/xxx/Projects/star-link/link/target/graalvm-native-image/hs_err_pid70204.log
[info] #
[info] # If you would like to submit a bug report, please visit:
[info] #   https://github.com/oracle/graal/issues
[info] # The crash happened outside the Java Virtual Machine in native code.
[info] # See problematic frame for where to report the bug.
[info] #
[error] Error: Image build request failed with exit status 134
[error] com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 134
[error]         at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1541)
[error]         at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1299)
[error]         at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1260)
[error]         at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1219)
[error]         at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1722)
```

Error messages from the created error file (Please refer the attached error file for details [hs_err_pid72375.log](https://github.com/oracle/graal/files/4671728/hs_err_pid72375.log):

```
Stack: [0x00007f9614df5000,0x00007f96157f6000],  sp=0x00007f96157f2de8,  free space=10231k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x00007f9606ff7160
j  io.netty.channel.unix.Errors.<clinit>()V+0
v  ~StubRoutines::call_stub
V  [libjvm.so+0x87fd39]
V  [libjvm.so+0x850dde]
V  [libjvm.so+0x851493]
V  [libjvm.so+0xe2bd20]
J 3246  jdk.internal.misc.Unsafe.ensureClassInitialized0(Ljava/lang/Class;)V java.base@11.0.7 (0 bytes) @ 0x00007f96bff447ff [0x00007f96bff44740+0x00000000000000bf]
J 3427 c1 com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.ensureClassInitialized(Ljava/lang/Class;Z)Lcom/oracle/svm/hosted/classinitialization/InitKind; (160 bytes) @ 0x00007f96b8f55584 [0x00007f96b8f55420+0x0000000000000164]
J 7999 jvmci com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(Ljava/lang/Class;Z)Lcom/oracle/svm/hosted/classinitialization/InitKind; (279 bytes) @ 0x00007f96c00fe0fc [0x00007f96c00fdb20+0x00000000000005dc]
J 5743 c1 com.oracle.svm.hosted.SVMHost.registerType(Lcom/oracle/graal/pointsto/meta/AnalysisType;)V (100 bytes) @ 0x00007f96b976a9ec [0x00007f96b976a020+0x00000000000009cc]
J 9940 jvmci com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(Ljdk/vm/ci/meta/ResolvedJavaType;)Lcom/oracle/graal/pointsto/meta/AnalysisType; (427 bytes) @ 0x00007f96c021d75c [0x00007f96c021d380+0x00000000000003dc]
J 9938 jvmci com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(Ljdk/vm/ci/meta/JavaType;)Lcom/oracle/graal/pointsto/meta/AnalysisType; (57 bytes) @ 0x00007f96c02205dc [0x00007f96c0220320+0x00000000000002bc]
J 4312 c1 com.oracle.graal.pointsto.meta.AnalysisMethod.<init>(Lcom/oracle/graal/pointsto/meta/AnalysisUniverse;Ljdk/vm/ci/meta/ResolvedJavaMethod;)V (462 bytes) @ 0x00007f96b91c79f4 [0x00007f96b91c75a0+0x0000000000000454]
J 4310 c1 com.oracle.graal.pointsto.meta.AnalysisUniverse.createMethod(Ljdk/vm/ci/meta/ResolvedJavaMethod;)Lcom/oracle/graal/pointsto/meta/AnalysisMethod; (86 bytes) @ 0x00007f96b91c246c [0x00007f96b91c1bc0+0x00000000000008ac]
J 9171 jvmci com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(Ljdk/vm/ci/meta/JavaMethod;)Ljdk/vm/ci/meta/JavaMethod; (76 bytes) @ 0x00007f96bfd77bdc [0x00007f96bfd77700+0x00000000000004dc]
J 5456 c1 com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupMethod(II)Ljdk/vm/ci/meta/JavaMethod; (21 bytes) @ 0x00007f96b965715c [0x00007f96b9656ce0+0x000000000000047c]
J 4599 c1 com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.lookupMethodInPool(II)Ljdk/vm/ci/meta/JavaMethod; (53 bytes) @ 0x00007f96b92cbb0c [0x00007f96b92cb860+0x00000000000002ac]
J 4170 c1 org.graalvm.compiler.java.BytecodeParser.lookupMethod(II)Ljdk/vm/ci/meta/JavaMethod; jdk.internal.vm.compiler (51 bytes) @ 0x00007f96b916c0e4 [0x00007f96b916bc60+0x0000000000000484]
J 5092 c1 org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(II)V jdk.internal.vm.compiler (59 bytes) @ 0x00007f96b94806bc [0x00007f96b9480640+0x000000000000007c]
j  org.graalvm.compiler.java.BytecodeParser.processBytecode(II)V+2396 jdk.internal.vm.compiler
J 9823 c1 org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(Lorg/graalvm/compiler/java/BciBlockMapping$BciBlock;)V jdk.internal.vm.compiler (701 bytes) @ 0x00007f96ba4448e4 [0x00007f96ba43fea0+0x0000000000004a44]
J 10141 jvmci org.graalvm.compiler.java.BytecodeParser.build(Lorg/graalvm/compiler/nodes/FixedWithNextNode;Lorg/graalvm/compiler/java/FrameStateBuilder;)V jdk.internal.vm.compiler (922 bytes) @ 0x00007f96c02574ec [0x00007f96c0256340+0x00000000000011ac]
J 6413 c1 org.graalvm.compiler.java.BytecodeParser.buildRootMethod()V jdk.internal.vm.compiler (141 bytes) @ 0x00007f96b9a24c04 [0x00007f96b9a24620+0x00000000000005e4]
J 6718 c1 org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(Lorg/graalvm/compiler/nodes/StructuredGraph;)V jdk.internal.vm.compiler (22 bytes) @ 0x00007f96b9b4eafc [0x00007f96b9b4e660+0x000000000000049c]
J 5644 c1 org.graalvm.compiler.phases.Phase.run(Lorg/graalvm/compiler/nodes/StructuredGraph;Ljava/lang/Object;)V jdk.internal.vm.compiler (6 bytes) @ 0x00007f96b9720314 [0x00007f96b97200c0+0x0000000000000254]
J 5282 c1 org.graalvm.compiler.phases.BasePhase.apply(Lorg/graalvm/compiler/nodes/StructuredGraph;Ljava/lang/Object;Z)V jdk.internal.vm.compiler (504 bytes) @ 0x00007f96b9569544 [0x00007f96b9565500+0x0000000000004044]
J 7063 c1 com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse()Z (672 bytes) @ 0x00007f96b9c5951c [0x00007f96b9c54d20+0x00000000000047fc]
J 9788 jvmci com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply()V (714 bytes) @ 0x00007f96c020bbb4 [0x00007f96c020bb20+0x0000000000000094]
J 7204 c1 com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(Lcom/oracle/graal/pointsto/BigBang;Lcom/oracle/graal/pointsto/flow/InvokeTypeFlow;)V (167 bytes) @ 0x00007f96b9cf4874 [0x00007f96b9cf42e0+0x0000000000000594]
J 6495 c1 com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(Lcom/oracle/graal/pointsto/BigBang;Lcom/oracle/graal/pointsto/flow/context/AnalysisContext;Lcom/oracle/graal/pointsto/flow/InvokeTypeFlow;)Lcom/oracle/graal/pointsto/flow/MethodFlowsGraph; (108 bytes) @ 0x00007f96b9a5bb24 [0x00007f96b9a5ba00+0x0000000000000124]
J 6691 c1 com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(Lcom/oracle/graal/pointsto/BigBang;)V (134 bytes) @ 0x00007f96b9b3f6d4 [0x00007f96b9b3e4c0+0x0000000000001214]
J 9075 jvmci com.oracle.graal.pointsto.BigBang$2.run(Lorg/graalvm/compiler/debug/DebugContext;)V (31 bytes) @ 0x00007f96bfda762e [0x00007f96bfda75a0+0x000000000000008e]
J 7692 jvmci com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(Lcom/oracle/graal/pointsto/util/CompletionExecutor$DebugContextRunnable;)V (409 bytes) @ 0x00007f96c00be38c [0x00007f96c00bdd80+0x000000000000060c]
J 7690 jvmci com.oracle.graal.pointsto.util.CompletionExecutor$$Lambda$353.run()V (12 bytes) @ 0x00007f96c00bd1f4 [0x00007f96c00bd1a0+0x0000000000000054]
J 2459 jvmci java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec()Z java.base@11.0.7 (11 bytes) @ 0x00007f96bfe2e7f4 [0x00007f96bfe2e7a0+0x0000000000000054]
J 10234 c1 java.util.concurrent.ForkJoinTask.doExec()I java.base@11.0.7 (37 bytes) @ 0x00007f96ba654a1c [0x00007f96ba654780+0x000000000000029c]
J 8757 jvmci java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Ljava/util/concurrent/ForkJoinTask;Ljava/util/concurrent/ForkJoinPool$WorkQueue;I)V java.base@11.0.7 (86 bytes) @ 0x00007f96c0123a5c [0x00007f96c01238e0+0x000000000000017c]
J 9142 jvmci java.util.concurrent.ForkJoinPool.scan(Ljava/util/concurrent/ForkJoinPool$WorkQueue;I)Z java.base@11.0.7 (209 bytes) @ 0x00007f96c01cad94 [0x00007f96c01cab40+0x0000000000000254]
j  java.util.concurrent.ForkJoinPool.runWorker(Ljava/util/concurrent/ForkJoinPool$WorkQueue;)V+25 java.base@11.0.7
j  java.util.concurrent.ForkJoinWorkerThread.run()V+24 java.base@11.0.7
v  ~StubRoutines::call_stub
V  [libjvm.so+0x87fd39]
V  [libjvm.so+0x87dcdd]
V  [libjvm.so+0x92a88c]
V  [libjvm.so+0xdffeda]
V  [libjvm.so+0xdfc94f]
V  [libjvm.so+0xc4aa6e]
```

**Comment by dougxc** [comment]
This is a crash in a netty native method called via JNI: https://github.com/netty/netty/blob/00afb19d7a37de21b35ce4f6cb3fa7f74809f2ab/transport-native-unix-common/src/main/java/io/netty/channel/unix/Errors.java#L37
As far as I can see, the initialization of these JNI methods in *only* done via [`OnLoad`](https://github.com/netty/netty/blob/f58223982ce8d9ed056c3d127972222966d0ebd1/transport-native-unix-common/src/main/c/netty_unix_errors.c#L212) and this is not triggered in the context of Native Image.
I'm not sure how to resolve this so would suggest [reaching out](https://github.com/netty/netty/issues) to the netty team to request their input.

**Comment by dougxc** [comment]
Or maybe try a more recent netty version as suggested [here](https://github.com/oracle/graal/issues/2643#issuecomment-698038550).

**Comment by floating-cat** [comment]
I tried to use the most recent netty version, but it doesn't help.
I switched to use dockered version of my app before because I still haven't found out how to compile it by using the Graal Native.

Will dig this problem or reach out to the netty team if I have time later.
Thanks for the information.
