### ISSUE TITLE
Support Truffle-based languages such as JS when using -H:+UseLowLatencyGC

### ISSUE THREAD

**Issue by nhoughto** [oracle/graal#2497]
**Describe the issue**
I have an existing project that successfully compiles a native image on 20.0.1 CE, I wanted to test out some of the EE features, specifically the new low latency GC in 20.x EE, but that native image build fails with a seemingly low latency specific error:

```
Unannotated callee: org.graalvm.compiler.replacements.ReplacementsUtil.runtimeAssert(boolean, String) called by annotated caller com.oracle.svm.enterprise.gc.lowlatency.i.a(Pointer, Word)
com.oracle.svm.core.util.UserError$UserException: Found 1 violations of @Uninterruptible usage:
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. `git clone https://github.com/nhoughto/graal-repro`
2. `cd graal-repro; ./cmd.sh`

**Describe GraalVM and your environment:**
 - GraalVM version 20.1.0-ee
 - JDK major version: 8
 - OS: Debian
 - Architecture: AMD64

**More details**
```
graalvm-ee-20.1.0-ee/jre/bin/java \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-d64 \
-XX:-UseJVMCIClassLoader \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Duser.country=US \
-Duser.language=en \
-Djava.awt.headless=true \
-Dorg.graalvm.version=20.1.0 \
-Dorg.graalvm.config= \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
-Djvmci.class.path.append=/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/jvmci/graal.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/jvmci/enterprise-graal.jar \
-Dtruffle.TruffleRuntime=com.oracle.svm.truffle.api.SubstrateTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=false \
-Dpolyglot.image-build-time.PreinitializeContexts=js \
-Xmx6442450944 \
-javaagent:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/svm/builder/svm.jar \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-Xbootclasspath/a:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/boot/graal-sdk.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/boot/graaljs-scriptengine.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/truffle/truffle-api.jar \
-cp \
/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/svm/builder/llvm-platform-specific-shadowed.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/svm/builder/javacpp-shadowed.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/svm/builder/svm.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/svm/builder/pointsto.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/svm/builder/objectfile.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/svm/builder/svm-llvm.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/svm/builder/svm-enterprise-llvm.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/svm/builder/llvm-wrapper-shadowed.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/svm/builder/svm-enterprise.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/jvmci/graal.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/jvmci/jvmci-api.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/jvmci/enterprise-graal.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/jvmci/graal-management.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/jvmci/graal-truffle-jfr-impl.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/jvmci/jvmci-hotspot.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/resources.jar \
com.oracle.svm.hosted.NativeImageGeneratorRunner \
-watchpid \
4554 \
-imagecp \
/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/boot/graal-sdk.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/boot/graaljs-scriptengine.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/truffle/truffle-api.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/svm/builder/llvm-platform-specific-shadowed.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/svm/builder/javacpp-shadowed.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/svm/builder/svm.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/svm/builder/pointsto.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/svm/builder/objectfile.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/svm/builder/svm-llvm.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/svm/builder/svm-enterprise-llvm.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/svm/builder/llvm-wrapper-shadowed.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/svm/builder/svm-enterprise.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/jvmci/graal.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/jvmci/jvmci-api.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/jvmci/enterprise-graal.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/jvmci/graal-management.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/jvmci/graal-truffle-jfr-impl.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/jvmci/jvmci-hotspot.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/resources.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/svm/library-support.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/svm/library-support-enterprise.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/languages/regex/tregex.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/languages/js/trufflenode.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/languages/js/asm-7.1.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/languages/js/asm-util-7.1.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/languages/js/asm-commons-7.1.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/languages/js/asm-analysis-7.1.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/languages/js/asm-tree-7.1.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/languages/js/icu4j.jar:/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/languages/js/graaljs.jar:/data/worker/repro/build/libs/repro.jar \
-H:+UseLowLatencyGC \
-R:MinHeapSize=64m \
-R:MaxNewSize=32m \
-R:MaxHeapSize=128m \
-H:+AllowIncompleteClasspath \
-H:+ReportUnsupportedElementsAtRuntime \
-H:+ReportExceptionStackTraces \
-H:Name=output \
-H:Features=com.oracle.svm.truffle.TruffleFeature,org.graalvm.home.HomeFinderFeature \
-H:MaxRuntimeCompileMethods=1400 \
-H:ClassInitialization=org.graalvm.launcher:build_time,com.oracle.truffle:build_time \
-H:MaxRuntimeCompileMethods=9000 \
-H:ClassInitialization=com.oracle.truffle.js:build_time,com.oracle.js.parser:build_time,com.oracle.truffle.trufflenode:build_time,com.oracle.truffle.regex:build_time \
-H:ClassInitialization=com.ibm.icu:run_time \
-H:ReflectionConfigurationResources=com/oracle/truffle/js/runtime/resources/reflect-config.json \
-H:ResourceConfigurationResources=com/oracle/truffle/js/runtime/resources/resource-config.json \
-H:Class=Test \
-H:FallbackThreshold=0 \
-H:CLibraryPath=/root/.gradle/caches/com.palantir.graal/20.1.0-ee/graalvm-ee-20.1.0-ee/jre/lib/svm/clibraries/linux-amd64 \
-H:Path=/data/worker/repro/build \

[output:4407]    classlist:   7,484.59 ms,  1.65 GB
[output:4407]        (cap):   1,410.26 ms,  2.29 GB
[output:4407]        setup:   4,443.58 ms,  2.29 GB
[output:4407]     (clinit):   1,492.55 ms,  3.45 GB
[output:4407]   (typeflow):  45,656.55 ms,  3.45 GB
[output:4407]    (objects):  30,603.25 ms,  3.45 GB
[output:4407]   (features):   8,132.70 ms,  3.45 GB
[output:4407]     analysis:  89,653.82 ms,  3.45 GB
[output:4407]     universe:   2,984.39 ms,  3.42 GB
9490 method(s) included for runtime compilation
[output:4407]      (parse):  11,243.81 ms,  3.44 GB
[output:4407]      compile:  11,703.31 ms,  3.44 GB
Error: Found 1 violations of @Uninterruptible usage:
Unannotated callee: org.graalvm.compiler.replacements.ReplacementsUtil.runtimeAssert(boolean, String) called by annotated caller com.oracle.svm.enterprise.gc.lowlatency.i.a(Pointer, Word)
com.oracle.svm.core.util.UserError$UserException: Found 1 violations of @Uninterruptible usage:
Unannotated callee: org.graalvm.compiler.replacements.ReplacementsUtil.runtimeAssert(boolean, String) called by annotated caller com.oracle.svm.enterprise.gc.lowlatency.i.a(Pointer, Word)
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.code.UninterruptibleAnnotationChecker.check(UninterruptibleAnnotationChecker.java:72)
	at com.oracle.svm.hosted.code.CompileQueue.finish(CompileQueue.java:347)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:604)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
```

**Comment by nhoughto** [comment]
Repro here: https://github.com/nhoughto/graal-repro

**Comment by nhoughto** [comment]
bump?

**Comment by dougxc** [comment]
@christianhaeubl is on vacation and should reply once back next week.

**Comment by christianhaeubl** [comment]
Thanks for reporting that issue. This is a known limitation as the low-latency GC does not yet support any Truffle-based languages such as JavaScript. This restriction will be lifted later this year. I will try to improve the error message though as it isn't particularly helpful at the moment.

**Comment by nhoughto** [comment]
Ok thanks for the update, is this the best issue to track that progress? or close this and subscribe to another?

**Comment by christianhaeubl** [comment]
It is fine to track this issue (I changed it to a feature request).

**Comment by christianhaeubl** [comment]
This feature will be part of GraalVM 20.3.

**Comment by nhoughto** [comment]
Great! there are no early access builds of EE are there? I can see there are 20.3 CE dev builds but no EE? 🤞

**Comment by christianhaeubl** [comment]
Currently, we don't provide any EE early access builds.
