### ISSUE TITLE
jdk/internal/jimage/JImageOpenTest.java fails: java.lang.IllegalAccessError: superinterface check failed: class org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime$FrameVisitor (in module jdk.internal.vm.compiler) cannot access class jdk.vm.ci.code.stack.InspectedFrameVisitor (in module jdk.internal.vm.ci) because module jdk.internal.vm.ci does not export jdk.vm.ci.code.stack to module jdk.internal.vm.compiler

### ISSUE THREAD

**Issue by christhalinger** [oracle/graal#2506]
e0ab2b6e2 added a dependency to `jdk.vm.ci.code.stack` which is not exported to `jdk.internal.vm.compiler` in `module-info.java`. The `jdk/internal/jimage/JImageOpenTest.java` JDK regression test fails because of this:

```
java.lang.IllegalAccessError: superinterface check failed: class org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime$FrameVisitor (in module jdk.internal.vm.compiler) cannot access class jdk.vm.ci.code.stack.InspectedFrameVisitor (in module jdk.internal.vm.ci) because module jdk.internal.vm.ci does not export jdk.vm.ci.code.stack to module jdk.internal.vm.compiler
	at java.base/java.lang.ClassLoader.defineClass2(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1109)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:206)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:759)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:680)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:605)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:640)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:609)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at JImageOpenTest$1.lambda$run$0(JImageOpenTest.java:60)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at JImageOpenTest$1.run(JImageOpenTest.java:57)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I don't see that export in `labs-openjdk-11` either so I have no idea how this works for you:

https://github.com/graalvm/labs-openjdk-11/blob/master/src/jdk.internal.vm.ci/share/classes/module-info.java

Here is the missing export:

```
diff --git a/src/jdk.internal.vm.ci/share/classes/module-info.java b/src/jdk.internal.vm.ci/share/classes/module-info.java
index fed310d..2ee7ec9 100644
--- a/src/jdk.internal.vm.ci/share/classes/module-info.java
+++ b/src/jdk.internal.vm.ci/share/classes/module-info.java
@@ -30,6 +30,7 @@ module jdk.internal.vm.ci {
         jdk.internal.vm.compiler.management;
     exports jdk.vm.ci.meta to jdk.internal.vm.compiler;
     exports jdk.vm.ci.code to jdk.internal.vm.compiler;
+    exports jdk.vm.ci.code.stack to jdk.internal.vm.compiler;
     exports jdk.vm.ci.hotspot to jdk.internal.vm.compiler;
 
     uses jdk.vm.ci.services.JVMCIServiceLocator;
```

After adding the missing export `jdk/modules/etc/JdkQualifiedExportTest.java` will start failing but that can be fixed by adding a known-exception:

```
diff --git a/test/jdk/jdk/modules/etc/JdkQualifiedExportTest.java b/test/jdk/jdk/modules/etc/JdkQualifiedExportTest.java
index e9bb664..6b2fdb5 100644
--- a/test/jdk/jdk/modules/etc/JdkQualifiedExportTest.java
+++ b/test/jdk/jdk/modules/etc/JdkQualifiedExportTest.java
@@ -74,6 +74,7 @@ public class JdkQualifiedExportTest {
                "jdk.internal.vm.ci/jdk.vm.ci.hotspot",
                "jdk.internal.vm.ci/jdk.vm.ci.meta",
                "jdk.internal.vm.ci/jdk.vm.ci.code",
+               "jdk.internal.vm.ci/jdk.vm.ci.code.stack",
                "jdk.jsobject/jdk.internal.netscape.javascript.spi");
 
     static void checkExports(ModuleDescriptor md) {
```

**Comment by christhalinger** [comment]
@dougxc pinging you as you've added e0ab2b6

**Comment by dougxc** [comment]
It works for Graal due to https://github.com/openjdk/jdk/blob/8119f836bf73f11440c5ff6a6343ec11b8c80600/src/jdk.internal.vm.ci/share/classes/jdk.vm.ci.hotspot/src/jdk/vm/ci/hotspot/HotSpotJVMCICompilerConfig.java#L113

**Comment by dougxc** [comment]
This needs to be addressed in the JDK so please open an OpenJDK bug instead.

**Comment by christhalinger** [comment]
I'm not sure I understand. Are you saying this is a test bug?

**Comment by dougxc** [comment]
Yes.
