### ISSUE TITLE
ObjectInputStream / ObjectOutputStream are not supported

### ISSUE THREAD

**Issue by phamvanthanh** [oracle/graal#2507]
Hi 
ObjectInputStream / ObjectOutputStream are not supported thus it is not able to do serialize/deserialize.

**environment:**
 [ GRAALVM CE 20.2.0-dev]**
 - JDK major version: **[e.g.:11]**
 - OS: **[Windows]**
 - Architecture: **[e.g.: AMD64]**

Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: ObjectInputStream.readObject()
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:86)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:53)

**Comment by phamvanthanh** [comment]
Anyone can give comments on plans to support this feature?
