### ISSUE TITLE
[native-image] crashes with -H:+TraceInlining

### ISSUE THREAD

**Issue by tianxiaogu** [oracle/graal#2512]
**Describe the issue**
A clear and concise description of the issue. We recommend using the [latest snapshot builds](https://github.com/graalvm/graalvm-ce-dev-builds/releases) to replicate the issue as  bugs are constantly being fixed in the master branch

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Download <https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.1.0/graalvm-ce-java8-linux-amd64-20.1.0.tar.gz>
2. Pick a Java program, e.g., HelloWorld

```
class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}
```

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: <https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.1.0/graalvm-ce-java8-linux-amd64-20.1.0.tar.gz>
 - JDK major version: 8
 - OS: Ubuntu 18.04
 - Architecture: AMD64

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

1. Build the HelloWorld using native-image.
```
javac HelloWorld.java
native-image -H:+TraceInlining HelloWorld
```

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
Build on Server(pid: 32347, port: 35043)
[helloworld:32347]    classlist:     109.49 ms,  1.24 GB
[helloworld:32347]        (cap):     355.14 ms,  1.24 GB
[helloworld:32347]        setup:     432.93 ms,  1.24 GB
Fatal error:org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.NullPointerException
	at parsing java.lang.ref.Reference.<clinit>(Reference.java:222)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:463)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:359)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:518)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.executeCompilation(NativeImageBuildServer.java:406)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$processCommand$8(NativeImageBuildServer.java:343)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.withJVMContext(NativeImageBuildServer.java:424)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.processCommand(NativeImageBuildServer.java:340)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.processRequest(NativeImageBuildServer.java:284)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$serve$7(NativeImageBuildServer.java:244)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.NullPointerException
	at parsing java.lang.ref.Reference.<clinit>(Reference.java:222)
	at org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2590)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:94)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3428)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3230)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1088)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:982)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:214)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
	at com.oracle.svm.hosted.substitute.UnsafeAutomaticSubstitutionProcessor.getStaticInitializerGraph(UnsafeAutomaticSubstitutionProcessor.java:929)
	at com.oracle.svm.hosted.substitute.UnsafeAutomaticSubstitutionProcessor.computeSubstitutions(UnsafeAutomaticSubstitutionProcessor.java:345)
	at com.oracle.svm.hosted.SVMHost.registerType(SVMHost.java:232)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:264)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:205)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:182)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:352)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:325)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:75)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaField(UniverseMetaAccess.java:98)
	at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaField(AnalysisMetaAccess.java:71)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.processComputedValueFields(AnnotationSubstitutionProcessor.java:214)
	at com.oracle.svm.hosted.NativeImageGenerator.initializeBigBang(NativeImageGenerator.java:938)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:867)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:536)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at org.graalvm.compiler.nodes.InliningLog.addDecision(InliningLog.java:178)
	at org.graalvm.compiler.java.BytecodeParser.tryFastInlineAccessor(BytecodeParser.java:2295)
	at org.graalvm.compiler.java.BytecodeParser.inline(BytecodeParser.java:2451)
	at org.graalvm.compiler.java.BytecodeParser.tryInline(BytecodeParser.java:2248)
	at org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1925)
	at org.graalvm.compiler.java.BytecodeParser.genDynamicInvokeHelper(BytecodeParser.java:1791)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1741)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1726)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5338)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3423)
	... 28 more
Error: Image build request failed with exit status 1

```

**Comment by christianwimmer** [comment]
No one has ever tried enabling that option, so even if it worked you would not get any output from it.

**Comment by oubidar-Abderrahim** [comment]
I am closing this issue. If you think this is still relevant please reopen it.
