### ISSUE TITLE
Native image builds fail with latest Graal and OpenJDK11u sources

### ISSUE THREAD

**Issue by stooke** [oracle/graal#2515]
A graal VM built from OpenJDK 11u (upcoming 11.0.8) will hit an assertion on generating native images. A simple HelloWorld will do.  A test in Graal assumes features which are not yet in OpenJDK 11u.

The JDK commit adding these functions was https://hg.openjdk.java.net/jdk/jdk/rev/d6aa9ea2405d
This has not been backported to OpenJDK11 (at a minimum).
The Graal version check was added 3 days ago: https://github.com/oracle/graal/commit/ecf0290e6f984be9a8dff836bf7b0e1a90a376d9

Here is the stack trace:
...
Exception in thread "main" jdk.vm.ci.common.JVMCIError: VM config values missing that should be present in JDK 11 windows-amd64 (java.home=C:\tmp\graal-11\graal\sdk\mxbuild\windows-amd64\GRAALVM_132C5E3B79_JAVA11\graalvm-132c5e3b79-java11-20.2.0-dev, java.vm.name=OpenJDK 64-Bit Server VM, java.vm.version=11.0.8-ea+4):
    JVMCIRuntime::dynamic_new_instance_or_null at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.GraalHotSpotVMConfig.<init>(GraalHotSpotVMConfig.java:797)
    JVMCIRuntime::new_array_or_null at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.GraalHotSpotVMConfig.<init>(GraalHotSpotVMConfig.java:795)
    JVMCIRuntime::new_instance_or_null at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.GraalHotSpotVMConfig.<init>(GraalHotSpotVMConfig.java:794)
    JVMCIRuntime::new_multi_array_or_null at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.GraalHotSpotVMConfig.<init>(GraalHotSpotVMConfig.java:796)
        at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.GraalHotSpotVMConfigAccess.reportErrors(GraalHotSpotVMConfigAccess.java:226)
        at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.GraalHotSpotVMConfig.<init>(GraalHotSpotVMConfig.java:67)
        at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalRuntime.<init>(HotSpotGraalRuntime.java:163)
        at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:156)
        at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:134)
        at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:52)
        at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.getCompiler(HotSpotJVMCIRuntime.java:425)
        at com.oracle.svm.hosted.c.GraalAccess.getGraalCapability(GraalAccess.java:50)
        at com.oracle.svm.hosted.c.GraalAccess.getOriginalTarget(GraalAccess.java:38)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.isValidArchitecture(NativeImageGeneratorRunner.java:208)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.verifyValidJavaVersionAndPlatform(NativeImageGeneratorRunner.java:413)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:219)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:505)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:114)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:533)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1558)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1308)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1269)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1228)
        at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1739)
...

**Comment by dougxc** [comment]
This should just be a matter of modifying the `expectPresent` argument value when initializing `newInstanceOrNullAddress` and friends using `org.graalvm.compiler.hotspot.GraalHotSpotVMConfigAccess.IS_OPENJDK` (see `useAESCTRIntrinsics` for an example).

**Comment by dougxc** [comment]
Can you please see if this patch fixes the build:
```
diff --git a/compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/GraalHotSpotVMConfig.java b/compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/GraalHotSpotVMConfig.java
index 871766d6b73..bf1a422aad7 100644
--- a/compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/GraalHotSpotVMConfig.java
+++ b/compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/GraalHotSpotVMConfig.java
@@ -791,10 +791,10 @@ public class GraalHotSpotVMConfig extends GraalHotSpotVMConfigAccess {
     public final long dynamicNewInstanceAddress = getAddress("JVMCIRuntime::dynamic_new_instance");

     // Allocation stubs that return null when allocation fails
-    public final long newInstanceOrNullAddress = getAddress("JVMCIRuntime::new_instance_or_null", 0L, JVMCI || JDK >= 12 || (JDK == 11 && JDK_UPDATE >= 7));
-    public final long newArrayOrNullAddress = getAddress("JVMCIRuntime::new_array_or_null", 0L, JVMCI || JDK >= 12 || (JDK == 11 && JDK_UPDATE >= 7));
-    public final long newMultiArrayOrNullAddress = getAddress("JVMCIRuntime::new_multi_array_or_null", 0L, JVMCI || JDK >= 12 || (JDK == 11 && JDK_UPDATE >= 7));
-    public final long dynamicNewInstanceOrNullAddress = getAddress("JVMCIRuntime::dynamic_new_instance_or_null", 0L, JVMCI || JDK >= 12 || (JDK == 11 && JDK_UPDATE >= 7));
+    public final long newInstanceOrNullAddress = getAddress("JVMCIRuntime::new_instance_or_null", 0L, JVMCI || JDK >= 12 || (!IS_OPENJDK && JDK == 11 && JDK_UPDATE >= 7));
+    public final long newArrayOrNullAddress = getAddress("JVMCIRuntime::new_array_or_null", 0L, JVMCI || JDK >= 12 || (!IS_OPENJDK && JDK == 11 && JDK_UPDATE >= 7));
+    public final long newMultiArrayOrNullAddress = getAddress("JVMCIRuntime::new_multi_array_or_null", 0L, JVMCI || JDK >= 12 || (!IS_OPENJDK && JDK == 11 && JDK_UPDATE >= 7));
+    public final long dynamicNewInstanceOrNullAddress = getAddress("JVMCIRuntime::dynamic_new_instance_or_null", 0L, JVMCI || JDK >= 12 || (!IS_OPENJDK && JDK == 11 && JDK_UPDATE >= 7));

     public boolean areNullAllocationStubsAvailable() {
         return newInstanceOrNullAddress != 0L;
```

**Comment by dougxc** [comment]
The reason for making it a hard failure is that we discovered a performance issue in Graal a while ago that was (in part) due to certain VM symbols [not being exported from C++ to Java](https://github.com/graalvm/labs-openjdk-11/commit/6ecf980849defb4137799774d67aaae27d3bc056). It took quite a while to find this cause and we want to avoid that happening again. A reliable to ensure this is a gate failure. That said, we add support for a GRAAL_CONFIG_ERROR_AS_WARNING environment variable if you think that would be useful.

**Comment by dougxc** [comment]
The config errors should now be resolved by https://github.com/oracle/graal/commit/c183ad7fd2e9c322132d0ce21accea60e0c26393. Please open a new issue if there are further config problems.

**Comment by robilad** [comment]
Hi Doug,

I ran into a similar sounding issue trying to run the tests in the graal-js-jdk11-maven-demo on JDK 15 EA b26:

[INFO] Running com.mycompany.app.AppTest
=== Nashorn via javax.script.ScriptEngine ===
*** Nashorn not found ***
=== Graal.js via org.graalvm.polyglot.Context === 
=== Graal.js via javax.script.ScriptEngine ===
org.graalvm.polyglot.PolyglotException: jdk.vm.ci.common.JVMCIError: VM config values missing that should be present in JDK 15 linux-amd64 (java.home=/home/dtopic-de/Downloads/jdk-15, java.vm.name=OpenJDK 64-Bit Server VM, java.vm.version=15-ea+26-1287):
    STACK_BIAS at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.GraalHotSpotVMConfig.<init>(GraalHotSpotVMConfig.java:256)
VM config values not expected to be present in JDK 15 linux-amd64 (java.home=/home/dtopic-de/Downloads/jdk-15, java.vm.name=OpenJDK 64-Bit Server VM, java.vm.version=15-ea+26-1287):
    Deoptimization::_support_large_access_byte_array_virtualization at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.GraalHotSpotVMConfig.<init>(GraalHotSpotVMConfig.java:878) [value: 1]
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.392 s <<< FAILURE! - in com.mycompany.app.AppTest
[ERROR] testGraalPolyglotSpeed(com.mycompany.app.AppTest)  Time elapsed: 0.539 s  <<< ERROR!
org.graalvm.polyglot.PolyglotException: 
jdk.vm.ci.common.JVMCIError: VM config values missing that should be present in JDK 15 linux-amd64 (java.home=/home/dtopic-de/Downloads/jdk-15, java.vm.name=OpenJDK 64-Bit Server VM, java.vm.version=15-ea+26-1287):
    STACK_BIAS at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.GraalHotSpotVMConfig.<init>(GraalHotSpotVMConfig.java:256)
VM config values not expected to be present in JDK 15 linux-amd64 (java.home=/home/dtopic-de/Downloads/jdk-15, java.vm.name=OpenJDK 64-Bit Server VM, java.vm.version=15-ea+26-1287):
    Deoptimization::_support_large_access_byte_array_virtualization at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.GraalHotSpotVMConfig.<init>(GraalHotSpotVMConfig.java:878) [value: 1]

Would these changes potentially address this issue as well?

**Comment by dougxc** [comment]
The fix for that is already in master: https://github.com/oracle/graal/commit/24a764e4a9afe8b6a867ac11ed44da98c890931b#diff-99a8fd7ee6b70f2a26738ac86a114ffbL255
I'm not so familiar with when/how graal-js-jdk11-maven-demo is kept up to date with graal master. @wirthi might be able to help out there.
