### ISSUE TITLE
Spring app build failing when a type isn't on the classpath (with --allow-incomplete-classpath)

### ISSUE THREAD

**Issue by aclement** [oracle/graal#2529]
**Describe the issue**
Within the spring-graalvm-native project is an app using tomcat and spring.  If I add a specific spring cloud dependency to that app, it starts failing at image build time with:
```
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.NoClassDefFoundError: org/springframework/retry/backoff/BackOffPolicy
	at parsing org.springframework.cloud.client.loadbalancer.LoadBalancerAutoConfiguration$RetryAutoConfiguration.loadBalancedRetryFactory(LoadBalancerAutoConfiguration.java:112)
	at org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2578)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:100)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3416)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3218)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1088)
```
It appear to be looking for `BackOffPolicy` because the code in question `org.springframework.cloud.client.loadbalancer.LoadBalancerAutoConfiguration$RetryAutoConfiguration.loadBalancedRetryFactory(LoadBalancerAutoConfiguration.java:112)` does:
```
return new LoadBalancedRetryFactory() { };
```
and `LoadBalancedRetryFactory` has default methods that mention `BackOffPolicy`:

```
default BackOffPolicy createBackOffPolicy(String service) {
```
I'm not sure the type analysis is gracefully handling the missing BackOffPolicy in this default method (when `--allow-incomplete-classpath` is specified).  This app runs perfectly fine as a built java app on a JVM without the types around. I feel like we've seen something around default method handling before (maybe that wasn't in a return type though?)

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. git clone git@github.com:spring-projects-experimental/spring-graalvm-native.git
2. cd spring-graalvm-native
3. git checkout fd9c420a8979 (just to make sure you have the exact same as I have, probably not critical)
4. ./build.sh
5. cd spring-graalvm-native-samples/springmvc-tomcat
6. open pom.xml and add this in the 'dependencies' section (~line23):
```
               <dependency>
                       <groupId>org.springframework.cloud</groupId>
                       <artifactId>spring-cloud-starter-sleuth</artifactId>
               </dependency>
```
Also add this at the end (just before the closing /project tag on the last line) to get spring cloud dependency management:
```
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>Hoxton.SR4</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```
7. ./build.sh (the error text will come up and is stored in `target/native-image/output.txt`)

**Describe GraalVM and your environment:**
- GraalVM 20.1 release (also tried built master today 1-Jun-2020 #cddb248f0eb25f0).
 - JDK 8
- Catalina macOS

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.

This trace log was from the Graal 20.1 release version:
```
$ native-image --version
GraalVM Version 20.1.0 (Java Version 1.8.0_252)

...
Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.springframework.cloud.client.loadbalancer.LoadBalancerAutoConfiguration$RetryAutoConfiguration.loadBalancedRetryFactory() 
Parsing context:
	parsing com.oracle.svm.reflect.LoadBalancerAutoConfiguration$RetryAutoConfiguration_loadBalancedRetryFactory_20ffcb05673e3db00f876818eb5d5933cfabf046_5177.invoke(Unknown Source)
	parsing java.lang.reflect.Method.invoke(Method.java:498)
	parsing com.sun.naming.internal.ResourceManager$AppletParameter.get(ResourceManager.java:167)
	parsing com.sun.naming.internal.ResourceManager.getInitialEnvironment(ResourceManager.java:221)
	parsing javax.naming.InitialContext.init(InitialContext.java:240)
	parsing javax.naming.InitialContext.<init>(InitialContext.java:192)
	parsing org.springframework.jndi.JndiLocatorDelegate.isDefaultJndiEnvironmentAvailable(JndiLocatorDelegate.java:90)
	parsing org.springframework.web.context.support.StandardServletEnvironment.customizePropertySources(StandardServletEnvironment.java:87)
	parsing org.springframework.core.env.AbstractEnvironment.<init>(AbstractEnvironment.java:124)
	parsing org.springframework.core.env.StandardEnvironment.<init>(StandardEnvironment.java:54)
	parsing org.springframework.web.context.support.StandardServletEnvironment.<init>(StandardServletEnvironment.java:45)
	parsing org.springframework.boot.SpringApplication.getOrCreateEnvironment(SpringApplication.java:457)
	parsing org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:342)
	parsing org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	parsing org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	parsing org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	parsing com.example.tomcat.TomcatApplication.main(TomcatApplication.java:10)
	parsing com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:149)
	parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:184)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:336)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:311)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:112)
	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:228)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:470)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:542)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:530)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.NoClassDefFoundError: org/springframework/retry/backoff/BackOffPolicy
	at parsing org.springframework.cloud.client.loadbalancer.LoadBalancerAutoConfiguration$RetryAutoConfiguration.loadBalancedRetryFactory(LoadBalancerAutoConfiguration.java:112)
	at org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2590)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:94)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3428)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3230)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1088)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:982)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:214)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:225)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:352)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:322)
	... 12 more
Caused by: java.lang.NoClassDefFoundError: org/springframework/retry/backoff/BackOffPolicy
	at jdk.vm.ci.hotspot.CompilerToVM.getDeclaredMethods(Native Method)
	at jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.getDeclaredMethods(HotSpotResolvedObjectTypeImpl.java:952)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.declaresDefaultMethods(ClassInitializationFeature.java:385)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.processInterfaces(ConfigurableClassInitialization.java:606)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:565)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:132)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.maybeInitializeHosted(ConfigurableClassInitialization.java:160)
	at com.oracle.svm.hosted.SVMHost.registerType(SVMHost.java:223)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:264)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:205)
	at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupType(WrappedConstantPool.java:155)
	at org.graalvm.compiler.java.BytecodeParser.lookupType(BytecodeParser.java:4274)
	at org.graalvm.compiler.java.BytecodeParser.genNewInstance(BytecodeParser.java:4545)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5343)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3423)
	... 23 more
Caused by: java.lang.ClassNotFoundException: org.springframework.retry.backoff.BackOffPolicy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 38 more
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1541)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1299)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1260)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1219)

```

**Comment by cstancu** [comment]
@aclement thanks for the reproducer! I was able to replicate the issue, a solution will take a bit more work.

**Comment by eginez** [comment]
Hey all a fix for this has been committed in jvmci. See: https://github.com/graalvm/graal-jvmci-8/commit/7f40b4b9dd216e83f6ff8a4d0911142f34771fe2 and  https://github.com/graalvm/graal-jvmci-8/commit/d933af3b445baa085e1bd4592d1cf28f431b3f66.
@aclement if you could test this workload with the newest jvmci, that would be great.
