### ISSUE TITLE
Graal compiler uses too much CPU and never ends

### ISSUE THREAD

**Issue by Cat7373** [oracle/graal#2548]
**Describe the issue**
`org.springframework.security.crypto.bcrypt.BCrypt` can never be compiled

**Steps to reproduce the issue**
1. environment:

    ```
    cat73@test:~$ lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 20.04 LTS
    Release:	20.04
    Codename:	focal
    cat73@test:~$ uname -a
    Linux saas-test 5.4.0-1010-azure #10-Ubuntu SMP Fri Apr 10 17:51:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
    cat73@test:~$ java -version
    java version "11.0.7" 2020-04-14 LTS
    Java(TM) SE Runtime Environment GraalVM EE 20.1.0 (build 11.0.7+8-LTS-jvmci-20.1-b02)
    Java HotSpot(TM) 64-Bit Server VM GraalVM EE 20.1.0 (build 11.0.7+8-LTS-jvmci-20.1-b02, mixed mode, sharing)
    ```
2. download the code: https://github.com/Cat7373/demo-code
3. Compile and run:

    ```sh
    ./gradlew clean bootJar
    mv build/libs/graal-demo-1.0.0-SNAPSHOT.jar ./graal-demo.jar
    java -jar graal-demo.jar
    ```
4. View the Graal compilation thread (i.e. `JVMCI-native CompilerThread0`) in the new shell:

    ```
    cat73@test:~$ jps
    1234 graal-demo.jar
    cat73@test:~$ jstack 1234
    2020-06-08 15:03:13
    Full thread dump Java HotSpot(TM) 64-Bit Server VM (11.0.7+8-LTS-jvmci-20.1-b02 mixed mode, sharing):

    Threads class SMR info:
    _java_thread_list=0x00007f1240001f00, length=11, elements={
    0x00007f128c023800, 0x00007f128c1f2800, 0x00007f128c1f4800, 0x00007f128c1fd000,
    0x00007f128c1ff800, 0x00007f128c201800, 0x00007f128c203800, 0x00007f128c235800,
    0x00007f128c28c800, 0x00007f12440cb000, 0x00007f1240001000
    }

    "main" #1 prio=5 os_prio=0 cpu=49007.11ms elapsed=550.99s tid=0x00007f128c023800 nid=0x14da2a waiting on condition  [0x00007f1293bf8000]
    java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(java.base@11.0.7/Native Method)
        at org.cat73.demo.Main.main(Main.java:26)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.7/Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.7/NativeMethodAccessorImpl.java:62)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.7/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@11.0.7/Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)

    "Reference Handler" #2 daemon prio=10 os_prio=0 cpu=0.35ms elapsed=550.97s tid=0x00007f128c1f2800 nid=0x14da31 waiting on condition  [0x00007f12904ae000]
    java.lang.Thread.State: RUNNABLE
        at java.lang.ref.Reference.waitForReferencePendingList(java.base@11.0.7/Native Method)
        at java.lang.ref.Reference.processPendingReferences(java.base@11.0.7/Reference.java:241)
        at java.lang.ref.Reference$ReferenceHandler.run(java.base@11.0.7/Reference.java:213)

    "Finalizer" #3 daemon prio=8 os_prio=0 cpu=0.37ms elapsed=550.97s tid=0x00007f128c1f4800 nid=0x14da32 in Object.wait()  [0x00007f12903ad000]
    java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.7/Native Method)
        - waiting on <0x000000072b132f50> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@11.0.7/ReferenceQueue.java:155)
        - waiting to re-lock in wait() <0x000000072b132f50> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@11.0.7/ReferenceQueue.java:176)
        at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11.0.7/Finalizer.java:170)

    "Signal Dispatcher" #4 daemon prio=9 os_prio=0 cpu=0.28ms elapsed=550.97s tid=0x00007f128c1fd000 nid=0x14da33 runnable  [0x0000000000000000]
    java.lang.Thread.State: RUNNABLE

    "JVMCI-native CompilerThread0" #5 daemon prio=9 os_prio=0 cpu=550758.06ms elapsed=550.97s tid=0x00007f128c1ff800 nid=0x14da34 runnable  [0x0000000000000000]
    java.lang.Thread.State: RUNNABLE
    Compiling:  551 %     4       org.springframework.security.crypto.bcrypt.BCrypt::key @ 151 (196 bytes)

    "C1 CompilerThread0" #6 daemon prio=9 os_prio=0 cpu=178.05ms elapsed=550.97s tid=0x00007f128c201800 nid=0x14da35 waiting on condition  [0x0000000000000000]
    java.lang.Thread.State: RUNNABLE
    No compile task

    "Sweeper thread" #7 daemon prio=9 os_prio=0 cpu=5.73ms elapsed=550.97s tid=0x00007f128c203800 nid=0x14da36 runnable  [0x0000000000000000]
    java.lang.Thread.State: RUNNABLE

    "Common-Cleaner" #8 daemon prio=8 os_prio=0 cpu=0.83ms elapsed=550.95s tid=0x00007f128c235800 nid=0x14da37 in Object.wait()  [0x00007f1268dcb000]
    java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.7/Native Method)
        - waiting on <0x000000072b133a60> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@11.0.7/ReferenceQueue.java:155)
        - waiting to re-lock in wait() <0x000000072b133a60> (a java.lang.ref.ReferenceQueue$Lock)
        at jdk.internal.ref.CleanerImpl.run(java.base@11.0.7/CleanerImpl.java:148)
        at java.lang.Thread.run(java.base@11.0.7/Thread.java:834)
        at jdk.internal.misc.InnocuousThread.run(java.base@11.0.7/InnocuousThread.java:134)

    "Service Thread" #9 daemon prio=9 os_prio=0 cpu=0.08ms elapsed=550.92s tid=0x00007f128c28c800 nid=0x14da38 runnable  [0x0000000000000000]
    java.lang.Thread.State: RUNNABLE

    "Libgraal MBean Registration" #10 daemon prio=1 os_prio=4 cpu=15.05ms elapsed=550.86s tid=0x00007f12440cb000 nid=0x14da3a waiting on condition  [0x00007f126869e000]
    java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(java.base@11.0.7/Native Method)
        at org.graalvm.compiler.hotspot.management.SVMMBean$Factory.run(jdk.internal.vm.compiler.management/SVMMBean.java:569)

    "Attach Listener" #12 daemon prio=9 os_prio=0 cpu=0.76ms elapsed=539.52s tid=0x00007f1240001000 nid=0x14da87 waiting on condition  [0x0000000000000000]
    java.lang.Thread.State: RUNNABLE

    "VM Thread" os_prio=0 cpu=55.67ms elapsed=550.98s tid=0x00007f128c1ef800 nid=0x14da30 runnable  

    "GC Thread#0" os_prio=0 cpu=32.85ms elapsed=550.99s tid=0x00007f128c038000 nid=0x14da2b runnable  

    "GC Thread#1" os_prio=0 cpu=28.65ms elapsed=547.40s tid=0x00007f1254001000 nid=0x14da47 runnable  

    "GC Thread#2" os_prio=0 cpu=36.18ms elapsed=547.40s tid=0x00007f1254002800 nid=0x14da48 runnable  

    "GC Thread#3" os_prio=0 cpu=23.12ms elapsed=547.40s tid=0x00007f1254004000 nid=0x14da49 runnable  

    "G1 Main Marker" os_prio=0 cpu=0.51ms elapsed=550.99s tid=0x00007f128c08b000 nid=0x14da2c runnable  

    "G1 Conc#0" os_prio=0 cpu=0.07ms elapsed=550.99s tid=0x00007f128c08d000 nid=0x14da2d runnable  

    "G1 Refine#0" os_prio=0 cpu=0.36ms elapsed=550.99s tid=0x00007f128c15e000 nid=0x14da2e runnable  

    "G1 Young RemSet Sampling" os_prio=0 cpu=115.23ms elapsed=550.99s tid=0x00007f128c160000 nid=0x14da2f runnable  
    "VM Periodic Task Thread" os_prio=0 cpu=267.68ms elapsed=550.92s tid=0x00007f128c28f800 nid=0x14da39 waiting on condition  

    JNI global refs: 12, weak refs: 0
    ```

    Part of the Graal compiler:

    ```
    "JVMCI-native CompilerThread0" #5 daemon prio=9 os_prio=0 cpu=550758.06ms elapsed=550.97s tid=0x00007f128c1ff800 nid=0x14da34 runnable  [0x0000000000000000]
    java.lang.Thread.State: RUNNABLE
    Compiling:  551 %     4       org.springframework.security.crypto.bcrypt.BCrypt::key @ 151 (196 bytes)
    ```

    It will always get stuck on this class.

    And the CPU usage of this thread is always 100%.

**Describe GraalVM and your environment:**
 - GraalVM version: GraalVM EE 20.1.0 (build 11.0.7+8-LTS-jvmci-20.1-b02)
 - JDK major version: 11
 - OS: Ubuntu 20.04 LTS
 - Architecture: AMD64

**Comment by gergo-** [comment]
@Cat7373 thanks for this report and the clear instructions for reproducting it. I have a fix that should land in GraalVM 20.2.0. For now the best way to work around this is to pass `-Dgraal.GraalCompileOnly=~BCrypt.key` on the command line to exclude this method from compilation with the GraalVM compiler.
