### ISSUE TITLE
Running IGV on Windows results in `dead jar` message

### ISSUE THREAD

**Issue by MartinBalin** [oracle/graal#2549]
Issue reported by **David Justo** on public GraalVM slack channel https://graalvm.slack.com/archives/CNBFR78F9/p1591569643020300
Missing information on IGV version and what JDK is being used to run IGV on.
Exception seen in log according to user is:
```
-------------------------------------------------------------------------------
java.lang.AssertionError: Already had dead JAR: C:\Users\david\AppData\Local\Temp\org-netbeans-libs-javacapi4868099851300684857.jar
        at org.netbeans.JarClassLoader$JarSource.destroy(JarClassLoader.java:675)
        at org.netbeans.JarClassLoader.destroy(JarClassLoader.java:316)
        at org.netbeans.StandardModule.classLoaderDown(StandardModule.java:556)
        at org.netbeans.ModuleManager.enable(ModuleManager.java:1398)
        at org.netbeans.ModuleManager.enable(ModuleManager.java:1254)
        at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:315)
        at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:251)
        at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:298)
        at org.netbeans.core.startup.Main.getModuleSystem(Main.java:156)
        at org.netbeans.core.startup.Main.getModuleSystem(Main.java:125)
        at org.netbeans.core.startup.Main.start(Main.java:282)
        at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:98)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by davidmrdavid** [comment]
Hi folks, this is David Justo.

Doing a `java - version` yields:

```
C:\Users\david>java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)

C:\Users\david>
```

Before trying this out, I installed java 8, then downloaded the GraalVM zip and set my `JAVA_HOME` and `PATH` as per the instructions. Commands like `gu` appear to work at a surface level. This is Windows 10.

@MartinBalin , let me know if there's any more information I can provide.

**Comment by davidmrdavid** [comment]
Just giving this a friendly bump @MartinBalin  :)

**Comment by sdedic** [comment]
@davidmrdavid I guess more information is needed. I've successfuly run IGV today:
```
Product Version: IdealGraphVisualizer 20.1.0
Updates: NetBeans IDE is updated to version NetBeans 8.2 Patch 2
Java: 11.0.7; OpenJDK 64-Bit Server VM 11.0.7+10-jvmci-20.1-b02
Runtime: OpenJDK Runtime Environment 11.0.7+10-jvmci-20.1-b02
System: Windows 10 version 10.0 running on amd64; Cp1250; cs_CZ (idealgraphvisualizer)
```
The start of the log file reads:
```
>Log Session: Thursday, June 11, 2020 at 10:25:12 AM Central European Summer Time
>System Info: 
  Product Version         = IdealGraphVisualizer ol-netbeans-11-223-on-20200213
  Operating System        = Windows 10 version 10.0 running on amd64
  Java; VM; Vendor        = 11.0.7; OpenJDK 64-Bit Server VM 11.0.7+10-jvmci-20.1-b02; GraalVM Community
  Runtime                 = OpenJDK Runtime Environment 11.0.7+10-jvmci-20.1-b02
```
Maybe IGV does not pick the correct JDK on your system ?

Please paste the startup information from the log file.

**Comment by davidmrdavid** [comment]
So this is what I get when running `idealgraphvisualizer` in the `\bin` directory where its located:

```
C:\Users\david\Downloads\idealgraphvisualizer-19.3.2-all\idealgraphvisualizer\bin>

The launcher has determined that the parent process has a console and will reuse it for its own console output.
Closing the console will result in termination of the running program.
Use '--console suppress' to suppress console output.
Use '--console new' to create a separate console window.
-------------------------------------------------------------------------------
>Log Session: Sunday, June 14, 2020 6:06:38 PM PDT
>System Info:
  Product Version         = IdealGraphVisualizer ol-netbeans-11-125-on-20191015
  Operating System        = Windows 10 version 10.0 running on x86
  Java; VM; Vendor        = 1.8.0_251; Java HotSpot(TM) Client VM 25.251-b08; Oracle Corporation
  Runtime                 = Java(TM) SE Runtime Environment 1.8.0_251-b08
  Java Home               = C:\Program Files (x86)\Java\jre1.8.0_251
  System Locale; Encoding = en_US (idealgraphvisualizer); Cp1252
  Home Directory          = C:\Users\david
  Current Directory       = C:\Users\david\Downloads\idealgraphvisualizer-19.3.2-all\idealgraphvisualizer
  User Directory          = C:\Users\david\AppData\Roaming\idealgraphvisualizer\0.29
  Cache Directory         = C:\Users\david\AppData\Local\idealgraphvisualizer\Cache\0.29
  Installation            = C:\Users\david\Downloads\idealgraphvisualizer-19.3.2-all\idealgraphvisualizer\idealgraphvisualizer
                            C:\Users\david\Downloads\idealgraphvisualizer-19.3.2-all\idealgraphvisualizer\extide
                            C:\Users\david\Downloads\idealgraphvisualizer-19.3.2-all\idealgraphvisualizer\harness
                            C:\Users\david\Downloads\idealgraphvisualizer-19.3.2-all\idealgraphvisualizer\ide
                            C:\Users\david\Downloads\idealgraphvisualizer-19.3.2-all\idealgraphvisualizer\java
                            C:\Users\david\Downloads\idealgraphvisualizer-19.3.2-all\idealgraphvisualizer\nb
                            C:\Users\david\Downloads\idealgraphvisualizer-19.3.2-all\idealgraphvisualizer\webcommon
                            C:\Users\david\Downloads\idealgraphvisualizer-19.3.2-all\idealgraphvisualizer\platform
                            C:\Users\david\Downloads\idealgraphvisualizer-19.3.2-all\idealgraphvisualizer\platform
  Boot & Ext. Classpath   = C:\Program Files (x86)\Java\jre1.8.0_251\lib\resources.jar;C:\Program Files (x86)\Java\jre1.8.0_251\lib\rt.jar;C:\Program Files (x86)\Java\jre1.8.0_251\lib\sunrsasign.jar;C:\Program Files (x86)\Java\jre1.8.0_251\lib\jsse.jar;C:\Program Files (x86)\Java\jre1.8.0_251\lib\jce.jar;C:\Program Files (x86)\Java\jre1.8.0_251\lib\charsets.jar;C:\Program Files (x86)\Java\jre1.8.0_251\lib\jfr.jar;C:\Program Files (x86)\Java\jre1.8.0_251\classes;C:\Program Files (x86)\Java\jre1.8.0_251\lib\ext\access-bridge-32.jar;C:\Program Files (x86)\Java\jre1.8.0_251\lib\ext\cldrdata.jar;C:\Program Files (x86)\Java\jre1.8.0_251\lib\ext\dnsns.jar;C:\Program Files (x86)\Java\jre1.8.0_251\lib\ext\jaccess.jar;C:\Program Files (x86)\Java\jre1.8.0_251\lib\ext\jfxrt.jar;C:\Program Files (x86)\Java\jre1.8.0_251\lib\ext\localedata.jar;C:\Program Files (x86)\Java\jre1.8.0_251\lib\ext\nashorn.jar;C:\Program Files (x86)\Java\jre1.8.0_251\lib\ext\sunec.jar;C:\Program Files (x86)\Java\jre1.8.0_251\lib\ext\sunjce_provider.jar;C:\Program Files (x86)\Java\jre1.8.0_251\lib\ext\sunmscapi.jar;C:\Program Files (x86)\Java\jre1.8.0_251\lib\ext\sunpkcs11.jar;C:\Program Files (x86)\Java\jre1.8.0_251\lib\ext\zipfs.jar
  Application Classpath   = C:\Users\david\Downloads\idealgraphvisualizer-19.3.2-all\idealgraphvisualizer\platform\lib\boot.jar;C:\Users\david\Downloads\idealgraphvisualizer-19.3.2-all\idealgraphvisualizer\platform\lib\org-openide-modules.jar;C:\Users\david\Downloads\idealgraphvisualizer-19.3.2-all\idealgraphvisualizer\platform\lib\org-openide-util-lookup.jar;C:\Users\david\Downloads\idealgraphvisualizer-19.3.2-all\idealgraphvisualizer\platform\lib\org-openide-util-ui.jar;C:\Users\david\Downloads\idealgraphvisualizer-19.3.2-all\idealgraphvisualizer\platform\lib\org-openide-util.jar
  Startup Classpath       = C:\Users\david\Downloads\idealgraphvisualizer-19.3.2-all\idealgraphvisualizer\platform\core\asm-all-5.0.1.jar;C:\Users\david\Downloads\idealgraphvisualizer-19.3.2-all\idealgraphvisualizer\platform\core\core-base.jar;C:\Users\david\Downloads\idealgraphvisualizer-19.3.2-all\idealgraphvisualizer\platform\core\core.jar;C:\Users\david\Downloads\idealgraphvisualizer-19.3.2-all\idealgraphvisualizer\platform\core\org-netbeans-libs-asm.jar;C:\Users\david\Downloads\idealgraphvisualizer-19.3.2-all\idealgraphvisualizer\platform\core\org-openide-filesystems.jar;C:\Users\david\Downloads\idealgraphvisualizer-19.3.2-all\idealgraphvisualizer\idealgraphvisualizer\core\org-graalvm-visualizer-upgrader.jar;C:\Users\david\Downloads\idealgraphvisualizer-19.3.2-all\idealgraphvisualizer\idealgraphvisualizer\core\locale\core_idealgraphvisualizer.jar
-------------------------------------------------------------------------------
java.lang.AssertionError: Already had dead JAR: C:\Users\david\AppData\Local\Temp\org-netbeans-libs-javacapi2045456551376205221.jar
        at org.netbeans.JarClassLoader$JarSource.destroy(JarClassLoader.java:675)
        at org.netbeans.JarClassLoader.destroy(JarClassLoader.java:316)
        at org.netbeans.StandardModule.classLoaderDown(StandardModule.java:556)
        at org.netbeans.ModuleManager.enable(ModuleManager.java:1398)
        at org.netbeans.ModuleManager.enable(ModuleManager.java:1254)
        at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:315)
        at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:251)
        at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:298)
        at org.netbeans.core.startup.Main.getModuleSystem(Main.java:156)
        at org.netbeans.core.startup.Main.getModuleSystem(Main.java:125)
        at org.netbeans.core.startup.Main.start(Main.java:282)
        at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:98)
        at java.lang.Thread.run(Unknown Source)
```

Is this what you mean by "the log file" ?

**Comment by sdedic** [comment]
Not exactly; look in your `C:\Users\david\AppData\Roaming\idealgraphvisualizer\0.29\var\log` for `messages.log` file - but the initial messages are (should be) the same.
I am not able to reproduce the exact error you have, maybe because I am using 64bit Win10; but according to the printed `classpath` it seems that you use **JRE** to launch IGV, not **JDK**: that won't work, IGV needs full JDK runtime (`dt.jar` and `tools.jar`).

Please either install JDK as the default Java runtime, or you can use GraalVM itself (or any other JDK installation) as a runtime: edit `C:\Users\david\Downloads\idealgraphvisualizer-19.3.2-all\idealgraphvisualizer\conf\idealgraphvisualizer.conf` and near the end, **uncomment** line starting with
```
#jdkhome="...."
```
and provide the full path to the preferred JDK.

I wonder how `C:\Users\david\AppData\Local\Temp\org-netbeans-libs-javacapi2045456551376205221.jar` was located: did you have IGV installed previously (= some garbage left by previous installation ?)

**Comment by davidmrdavid** [comment]
Your suggestion, changing the `jdkhome="..."` line, worked!
Thanks!
