### ISSUE TITLE
UnsatisfiedLinkError when using PKCS11 in native image generated executable

### ISSUE THREAD

**Issue by mttcr** [oracle/graal#2552]
**Describe the issue**
I have a java program that read smart cards under linux. It uses sun.security.pkcs11.SunPKCS11.
I have the following error when using PKCS11:
```
java.lang.UnsatisfiedLinkError: sun.security.pkcs11.wrapper.PKCS11.connect(Ljava/lang/String;Ljava/lang/String;)V [symbol: Java_sun_security_pkcs11_wrapper_PKCS11_connect or Java_sun_security_pkcs11_wrapper_PKCS11_connect__Ljava_lang_String_2Ljava_lang_String_2]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
	at sun.security.pkcs11.wrapper.PKCS11.connect(PKCS11.java)
	at sun.security.pkcs11.wrapper.PKCS11.<init>(PKCS11.java:147)
	at sun.security.pkcs11.wrapper.PKCS11.getInstance(PKCS11.java:160)
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:318)
	at sun.security.pkcs11.SunPKCS11$1.run(SunPKCS11.java:112)
	at sun.security.pkcs11.SunPKCS11$1.run(SunPKCS11.java:109)
	at java.security.AccessController.doPrivileged(AccessController.java:119)
	at sun.security.pkcs11.SunPKCS11.configure(SunPKCS11.java:109)
...
```

**Steps to reproduce the issue**

compile and run this snippet with graal vm
```
    public static void main(String[] args)
    {
        String config = "name=opensc\n" //
            + "library=/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so\n" //
            + "slot=0\n";
        sun.security.pkcs11.SunPKCS11 p11 = (SunPKCS11) new sun.security.pkcs11.SunPKCS11().configure("--" + config);
    }
```

**Describe GraalVM and your environment:**
 - GraalVM version: graalvm-ce-java11-linux-20.1.0
 - JDK major version: 11
 - OS: Ubuntu 18.04.4 LTS
 - Architecture: 64

**More details**
I actually did some things to make it works.
1. Use the javaagent to capture reflection and jni: nothing added even though the SunPKCS11 provider worked great.
```
GRAALVMPATH=/root/test/graalvm-ce-java11-linux-20.1.0
PATH=$PATH:$GRAALVMPATH/bin
LINUX_CONFIG_DIR=config-dir-linux
cd /root/test
gu install native-image
$GRAALVMPATH/bin/java -agentlib:native-image-agent=config-merge-dir=$LINUX_CONFIG_DIR -jar test.jar -f ../testv3/v3.conf
```
2. Manually added the whole `sun.security.pkcs11.wrapper` package in both reflect-config.json and jni-config.json
```
{ "name":"sun.security.pkcs11.wrapper.CK_AES_CTR_PARAMS", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_ATTRIBUTE", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_C_INITIALIZE_ARGS", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_CREATEMUTEX", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_DATE", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_DESTROYMUTEX", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_ECDH1_DERIVE_PARAMS", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_ECDH2_DERIVE_PARAMS", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_INFO", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_LOCKMUTEX", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_MECHANISM_INFO", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_MECHANISM", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_NOTIFY", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_PBE_PARAMS", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_PKCS5_PBKD2_PARAMS", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_RSA_PKCS_OAEP_PARAMS", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_RSA_PKCS_PSS_PARAMS", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_SESSION_INFO", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_SLOT_INFO", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_SSL3_KEY_MAT_OUT", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_SSL3_KEY_MAT_PARAMS", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_SSL3_MASTER_KEY_DERIVE_PARAMS", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_SSL3_RANDOM_DATA", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_TLS_MAC_PARAMS", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_TLS_PRF_PARAMS", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_TLS12_KEY_MAT_PARAMS", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_TLS12_MASTER_KEY_DERIVE_PARAMS", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_TOKEN_INFO", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_UNLOCKMUTEX", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_VERSION", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_X9_42_DH1_DERIVE_PARAMS", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.CK_X9_42_DH2_DERIVE_PARAMS", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.Constants", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.Functions", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.PKCS11", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.PKCS11Constants", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.PKCS11Exception", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"sun.security.pkcs11.wrapper.PKCS11RuntimeException", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"java.lang.Long", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"java.lang.Object", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true},
{ "name":"java.lang.Boolean", "allDeclaredConstructors" : true,"allPublicConstructors" : true,"allDeclaredMethods" : true,"allPublicMethods" : true,"allDeclaredClasses" : true,"allPublicClasses" : true,"allPublicFields" : true,"allDeclaredFields" : true}

```

3. As the PKCS11 class was initialized at build time, added this block of code in my program:
```
if (!nativeLoaded)
{
	nativeLoaded = true;
	try
	{
		Method m = Class.forName("sun.security.pkcs11.wrapper.PKCS11").getDeclaredMethod("initializeLibrary", new Class[] { boolean.class });
		System.loadLibrary("j2pkcs11");
		m.setAccessible(true);
		m.invoke(null, Boolean.FALSE);
	}
	catch (Throwable t)
	{
		t.printStackTrace();
	}
}
```
4. build the image with 
```
native-image \
--verbose \
--enable-all-security-services \
--enable-https \
--enable-http \
--no-fallback \
-H:Name=test \
-H:+JNI \
-H:Path=graalbin \
-H:JNIConfigurationFiles=$LINUX_CONFIG_DIR/jni-config.json \
-H:ResourceConfigurationFiles=$LINUX_CONFIG_DIR/resource-config.json \
-H:ReflectionConfigurationFiles=$LINUX_CONFIG_DIR/reflect-config.json \
-H:DynamicProxyConfigurationFiles=$LINUX_CONFIG_DIR/proxy-config.json \
-H:IncludeResourceBundles=sun.security.util.Resources \
-cp test.jar \
fr.test.Test
```
5. Launch the binary with the following command line:
`LD_LIBRARY_PATH=/root/test/graalvm-ce-java11-linux-20.1.0/lib/server/ ./graalbin/test -Djava.library.path=/root/test/graalvm-ce-java11-linux-20.1.0/lib/ -f ../testv3/v3.conf `

6. next step, maybe: 
- embed libj2pkcs11.so as a resource in the executable, and at startup, move it somewhere and relaunch itself with the -Djava.library.path command line argument.

Did I miss something, or is there any plan to make this work "out of the box"?
FYI, I have a simlar issue under windows with the sunmscapi not embedded (#1410)

**Comment by cstancu** [comment]
@mttcr thank you for the report and for the in-depth investigation. It sounds like you succeeded in getting your program working with the method that you describe. I will look into statically linking this library in when needed, as we do with others.

**Comment by mttcr** [comment]
Hello,
Thanks for your answer. Is there an approximate target version where j2pkcs11 and sunmscapi will be linked?

**Comment by kenpb** [comment]
Hello,

Sorry to jump in @cstancu just found this issue as I reached the same point as @mttcr any updates?

    GraalVM version: GraalVM Version 21.0.0 (Java Version 1.8.0_282-b07)
    JDK major version: 1.8.0
    OS: Mint 19.04 LTS
    Architecture: x64

**Comment by kkriske** [comment]
@mttcr to answer your question here, to keep the relevant information in the right place:

> could something similar be done to statically link j2pkcs11 under linux?

Yes normally that should be possible. PKCS11 does seem a bit bigger than SunMSCAPI, so it may be a bit more work.
All relevant code of PKCS11 can be found here: https://github.com/graalvm/labs-openjdk-11/tree/b988ca25875850ccb19218f52b12b38956c264e4/src/jdk.crypto.cryptoki

If you feel comfortable doing so, you could give it a shot yourself and open a PR?
It seems like there is both a windows and linux variant so it's probably best to add support for both platforms at once.
