### ISSUE TITLE
Regression: javax/management/query/CustomQueryTest.java fails with graal-0.27

### ISSUE THREAD

**Issue by christhalinger** [oracle/graal#256]
Here is the other regression (as mentioned in #255):

```
--------------------------------------------------
TEST: javax/management/query/CustomQueryTest.java
TEST JDK: /data/jenkins/workspace/jdk8-centos7-release/usr/lib/jvm/java-1.8.0-twitter

ACTION: build -- Passed. Build successful
REASON: Named class compiled on demand
TIME:   1.015 seconds
messages:
command: build CustomQueryTest
reason: Named class compiled on demand
Test directory:
  compile: CustomQueryTest
elapsed time (seconds): 1.015

ACTION: compile -- Passed. Compilation successful
REASON: .class file out of date or does not exist
TIME:   1.015 seconds
messages:
command: compile -XDignore.symbol.file=true /data/jenkins/workspace/jdk8-centos7-release/jdk/test/javax/management/query/CustomQueryTest.java
reason: .class file out of date or does not exist
Mode: othervm
elapsed time (seconds): 1.015
configuration:
javac compilation environment
  source path: /data/jenkins/workspace/jdk8-centos7-release/jdk/test/javax/management/query
  class path:  /data/jenkins/workspace/jdk8-centos7-release/jdk/test/javax/management/query
               /data/jenkins/workspace/jdk8-centos7-release/jdk/testoutput/jdk_svc/JTwork/classes/0/javax/management/query
               /data/jenkins/workspace/jdk8-centos7-release/usr/lib/jvm/java-1.8.0-twitter/lib/tools.jar

rerun:
HOME=/var/lib/jenkins \
LANG=en_US.UTF-8 \
PATH=/bin:/usr/bin \
    /data/jenkins/workspace/jdk8-centos7-release/usr/lib/jvm/java-1.8.0-twitter/bin/javac \
        -J-ea \
        -J-esa \
        -J-XX:+UnlockExperimentalVMOptions \
        -J-XX:+EnableJVMCI \
        -J-XX:+UseJVMCICompiler \
        -J-XX:+UseConcMarkSweepGC \
        -J-Xmx512m \
        -J-Dtest.src=/data/jenkins/workspace/jdk8-centos7-release/jdk/test/javax/management/query \
        -J-Dtest.src.path=/data/jenkins/workspace/jdk8-centos7-release/jdk/test/javax/management/query \
        -J-Dtest.classes=/data/jenkins/workspace/jdk8-centos7-release/jdk/testoutput/jdk_svc/JTwork/classes/0/javax/management/query \
        -J-Dtest.class.path=/data/jenkins/workspace/jdk8-centos7-release/jdk/testoutput/jdk_svc/JTwork/classes/0/javax/management/query \
        -J-Dtest.vm.opts='-ea -esa -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+UseConcMarkSweepGC -Xmx512m' \
        -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-XX:+UnlockExperimentalVMOptions -J-XX:+EnableJVMCI -J-XX:+UseJVMCICompiler -J-XX:+UseConcMarkSweepGC -J-Xmx512m' \
        -J-Dtest.compiler.opts= \
        -J-Dtest.java.opts='-XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+UseConcMarkSweepGC' \
        -J-Dtest.jdk=/data/jenkins/workspace/jdk8-centos7-release/usr/lib/jvm/java-1.8.0-twitter \
        -J-Dcompile.jdk=/data/jenkins/workspace/jdk8-centos7-release/usr/lib/jvm/java-1.8.0-twitter \
        -J-Dtest.timeout.factor=4.0 \
        -d /data/jenkins/workspace/jdk8-centos7-release/jdk/testoutput/jdk_svc/JTwork/classes/0/javax/management/query \
        -sourcepath /data/jenkins/workspace/jdk8-centos7-release/jdk/test/javax/management/query \
        -classpath /data/jenkins/workspace/jdk8-centos7-release/jdk/test/javax/management/query:/data/jenkins/workspace/jdk8-centos7-release/jdk/testoutput/jdk_svc/JTwork/classes/0/javax/management/query:/data/jenkins/workspace/jdk8-centos7-release/usr/lib/jvm/java-1.8.0-twitter/lib/tools.jar \
        -XDignore.symbol.file=true /data/jenkins/workspace/jdk8-centos7-release/jdk/test/javax/management/query/CustomQueryTest.java
STDOUT:
STDERR:

ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.Exception: FAILED: expected 48, got 49
REASON: Assumed action based on file name: run main CustomQueryTest 
TIME:   0.393 seconds
messages:
command: main CustomQueryTest
reason: Assumed action based on file name: run main CustomQueryTest 
Mode: othervm
elapsed time (seconds): 0.393
configuration:
STDOUT:
STDERR:
java.lang.Exception: FAILED: expected 48, got 49
	at CustomQueryTest.assertEquals(CustomQueryTest.java:113)
	at CustomQueryTest.main(CustomQueryTest.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.lang.Thread.run(Thread.java:748)

JavaTest Message: Test threw exception: java.lang.Exception: FAILED: expected 48, got 49
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.Exception: FAILED: expected 48, got 49
rerun:
HOME=/var/lib/jenkins \
LANG=en_US.UTF-8 \
PATH=/bin:/usr/bin \
CLASSPATH=/data/jenkins/workspace/jdk8-centos7-release/jdk/testoutput/jdk_svc/JTwork/classes/0/javax/management/query:/data/jenkins/workspace/jdk8-centos7-release/jdk/test/javax/management/query:/data/jenkins/workspace/jdk8-centos7-release/usr/lib/jvm/java-1.8.0-twitter/lib/tools.jar:/data/jenkins/workspace/jdk8-centos7-release/jtreg/lib/javatest.jar:/data/jenkins/workspace/jdk8-centos7-release/jtreg/lib/jtreg.jar \
    /data/jenkins/workspace/jdk8-centos7-release/usr/lib/jvm/java-1.8.0-twitter/bin/java \
        -Dtest.src=/data/jenkins/workspace/jdk8-centos7-release/jdk/test/javax/management/query \
        -Dtest.src.path=/data/jenkins/workspace/jdk8-centos7-release/jdk/test/javax/management/query \
        -Dtest.classes=/data/jenkins/workspace/jdk8-centos7-release/jdk/testoutput/jdk_svc/JTwork/classes/0/javax/management/query \
        -Dtest.class.path=/data/jenkins/workspace/jdk8-centos7-release/jdk/testoutput/jdk_svc/JTwork/classes/0/javax/management/query \
        -Dtest.vm.opts='-ea -esa -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+UseConcMarkSweepGC -Xmx512m' \
        -Dtest.tool.vm.opts='-J-ea -J-esa -J-XX:+UnlockExperimentalVMOptions -J-XX:+EnableJVMCI -J-XX:+UseJVMCICompiler -J-XX:+UseConcMarkSweepGC -J-Xmx512m' \
        -Dtest.compiler.opts= \
        -Dtest.java.opts='-XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+UseConcMarkSweepGC' \
        -Dtest.jdk=/data/jenkins/workspace/jdk8-centos7-release/usr/lib/jvm/java-1.8.0-twitter \
        -Dcompile.jdk=/data/jenkins/workspace/jdk8-centos7-release/usr/lib/jvm/java-1.8.0-twitter \
        -Dtest.timeout.factor=4.0 \
        -ea \
        -esa \
        -XX:+UnlockExperimentalVMOptions \
        -XX:+EnableJVMCI \
        -XX:+UseJVMCICompiler \
        -XX:+UseConcMarkSweepGC \
        -Xmx512m \
        -XX:+UnlockExperimentalVMOptions \
        -XX:+EnableJVMCI \
        -XX:+UseJVMCICompiler \
        -XX:+UseConcMarkSweepGC \
        com.sun.javatest.regtest.agent.MainWrapper /data/jenkins/workspace/jdk8-centos7-release/jdk/testoutput/jdk_svc/JTwork/javax/management/query/CustomQueryTest.d/main.0.jta

TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: FAILED: expected 48, got 49
--------------------------------------------------
```

**Comment by dougxc** [comment]
@JaroslavTulach , this looks like it might have something to do with the Graal MBean. Can you please investigate it.

**Comment by dougxc** [comment]
@jtulach , can you please look into this

**Comment by JaroslavTulach** [comment]
I've found some version of the `CustomQueryTest.java` (where is yours coming from, Chris?) and I was able to:
```bash
open/test/jdk/javax/management/query$ javac CustomQueryTest.java 
open/test/jdk/javax/management/query$ /graalvm-0.32/bin/java CustomQueryTest 
open/test/jdk/javax/management/query$ md5sum CustomQueryTest.java
cc7d8e2784ad38c572b9ea90c91a7d17  CustomQueryTest.java
```
As far as I can say the GraalVM `0.32` can run the `CustomQueryTest` without a problem.

**Comment by JaroslavTulach** [comment]
Unless there is some new evidence, let's close this as "works for me".
