### ISSUE TITLE
java.lang.UnsatisfiedLinkError: sun.java2d.cmm.lcms.LCMS.getProfileID

### ISSUE THREAD

**Issue by phamvanthanh** [oracle/graal#2566]
Hi,
I go this error at run time.
java.lang.UnsatisfiedLinkError: sun.java2d.cmm.lcms.LCMS.getProfileID(Ljava/awt/color/ICC_Profile;)Lsun/java2d/cmm/lcms/LCMSProfile; [symbol: Java_sun_java2d_cmm_lcms_LCMS_getProfileID or Java_sun_java2d_cmm_lcms_LCMS_getProfileID__Ljava_awt_color_ICC_1Profile_2]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:153)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
	at sun.java2d.cmm.lcms.LCMS.getProfileID(LCMS.java)
	at sun.java2d.cmm.lcms.LCMSTransform.<init>(LCMSTransform.java:83)
	at sun.java2d.cmm.lcms.LCMS.createTransform(LCMS.java:173)
	at java.awt.color.ICC_ColorSpace.toRGB(ICC_ColorSpace.java:178)

Env:
 - GraalVM version GraalVM CE 20.2.0-dev-20200613_0203
 - JDK major version: 11
 - OS: Windows
 - Architecture: **[e.g.: AMD64]**

**Comment by vjovanov** [comment]
This should be fixed by now. @pejovica please verify.
