### ISSUE TITLE
Error running native image from groovy code

### ISSUE THREAD

**Issue by davecramer** [oracle/graal#2586]
**Describe the issue**
Main throws an exception. I didn't notice this at first but it still runs:

hello world

**Steps to reproduce the issue**
Please include both build steps as well as run steps
 
1. **git clone https://github.com/davecramer/graalvmtest.git**
2. **./gradlew jar**
3. **native-image --native-image-info --verbose -cp ./build/libs/graalvmtest-1.0-SNAPSHOT.jar:$GROOVY_HOME/lib/groovy-2.5.12.jar --initialize-at-run-time=org.codehaus.groovy.control.XStreamUtils,groovy.grape.GrapeIvy --no-fallback --no-server -H:Name=testpostgres -H:Class=TestPostgres -H:+ReportUnsupportedElementsAtRuntime --allow-incomplete-classpath**

**Describe GraalVM and your environment:**
 - GraalVM Version 20.1.0 (Java Version 11.0.7)
 - JDK openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)*
 - OS: **macos mojave**
 - Architecture: **intel **

**More details**
```
native-image -cp ./build/libs/graalvmtest-1.0-SNAPSHOT.jar:$GROOVY_HOME/lib/groovy-2.5.12.jar --initialize-at-run-time=org.codehaus.groovy.control.XStreamUtils,groovy.grape.GrapeIvy --no-fallback --no-server -H:Name=testpostgres -H:Class=TestPostgres -H:+ReportUnsupportedElementsAtRuntime --allow-incomplete-classpath
[testpostgres:9341]    classlist:   2,167.42 ms,  0.96 GB
[testpostgres:9341]        (cap):   3,594.08 ms,  0.96 GB
[testpostgres:9341]        setup:   5,083.84 ms,  0.96 GB
[testpostgres:9341]     (clinit):     367.52 ms,  2.29 GB
[testpostgres:9341]   (typeflow):  13,474.93 ms,  2.29 GB
[testpostgres:9341]    (objects):  11,637.01 ms,  2.29 GB
[testpostgres:9341]   (features):     529.19 ms,  2.29 GB
[testpostgres:9341]     analysis:  26,539.96 ms,  2.29 GB
[testpostgres:9341]     universe:     710.64 ms,  2.29 GB
[testpostgres:9341]      (parse):   4,224.49 ms,  2.29 GB
[testpostgres:9341]     (inline):   4,340.10 ms,  3.62 GB
[testpostgres:9341]    (compile):  17,026.83 ms,  4.33 GB
[testpostgres:9341]      compile:  27,027.73 ms,  4.33 GB
[testpostgres:9341]        image:   2,536.02 ms,  4.33 GB
[testpostgres:9341]        write:     730.64 ms,  4.33 GB
[testpostgres:9341]      [total]:  65,038.76 ms,  4.33 GB
Daves-MacBook-Pro:graalvmtest davec$ native-image --native-image-info --verbose -cp ./build/libs/graalvmtest-1.0-SNAPSHOT.jar:$GROOVY_HOME/lib/groovy-2.5.12.jar --initialize-at-run-time=org.codehaus.groovy.control.XStreamUtils,groovy.grape.GrapeIvy --no-fallback --no-server -H:Name=testpostgres -H:Class=TestPostgres -H:+ReportUnsupportedElementsAtRuntime --allow-incomplete-classpath
Executing [
/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/bin/java \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
-Djava.lang.invoke.stringConcat=BC_SB \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.runtime=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.code=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.aarch64=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.amd64=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.hotspot=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.services=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.common=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.code.site=ALL-UNNAMED \
--add-exports \
jdk.internal.vm.ci/jdk.vm.ci.code.stack=ALL-UNNAMED \
--add-opens \
jdk.internal.vm.compiler/org.graalvm.compiler.debug=ALL-UNNAMED \
--add-opens \
jdk.internal.vm.compiler/org.graalvm.compiler.nodes=ALL-UNNAMED \
--add-opens \
jdk.unsupported/sun.reflect=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.module=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.ref=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.reflect=ALL-UNNAMED \
--add-opens \
java.base/java.io=ALL-UNNAMED \
--add-opens \
java.base/java.lang=ALL-UNNAMED \
--add-opens \
java.base/java.lang.reflect=ALL-UNNAMED \
--add-opens \
java.base/java.lang.invoke=ALL-UNNAMED \
--add-opens \
java.base/java.lang.ref=ALL-UNNAMED \
--add-opens \
java.base/java.net=ALL-UNNAMED \
--add-opens \
java.base/java.nio=ALL-UNNAMED \
--add-opens \
java.base/java.nio.file=ALL-UNNAMED \
--add-opens \
java.base/java.security=ALL-UNNAMED \
--add-opens \
java.base/javax.crypto=ALL-UNNAMED \
--add-opens \
java.base/java.util=ALL-UNNAMED \
--add-opens \
java.base/java.util.concurrent.atomic=ALL-UNNAMED \
--add-opens \
java.base/sun.security.x509=ALL-UNNAMED \
--add-opens \
java.base/jdk.internal.logger=ALL-UNNAMED \
--add-opens \
org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED \
--add-opens \
org.graalvm.sdk/org.graalvm.polyglot=ALL-UNNAMED \
--add-opens \
org.graalvm.truffle/com.oracle.truffle.polyglot=ALL-UNNAMED \
--add-opens \
org.graalvm.truffle/com.oracle.truffle.api.impl=ALL-UNNAMED \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx14g \
-Duser.country=US \
-Duser.language=en \
-Djava.awt.headless=true \
-Dorg.graalvm.version=20.1.0 \
-Dorg.graalvm.config= \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
--module-path \
/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/truffle/truffle-api.jar \
-javaagent:/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/svm/builder/svm.jar \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-cp \
/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/svm/builder/llvm-wrapper-shadowed.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/svm/builder/svm.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/svm/builder/objectfile.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/svm/builder/llvm-platform-specific-shadowed.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/svm/builder/javacpp-shadowed.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/svm/builder/svm-llvm.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/svm/builder/pointsto.jar \
'com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus' \
-imagecp \
/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/svm/builder/llvm-wrapper-shadowed.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/svm/builder/svm.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/svm/builder/objectfile.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/svm/builder/llvm-platform-specific-shadowed.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/svm/builder/javacpp-shadowed.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/svm/builder/svm-llvm.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/svm/builder/pointsto.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/svm/library-support.jar:/Users/davec/projects/graalvmtest/build/libs/graalvmtest-1.0-SNAPSHOT.jar:/Users/davec/.sdkman/candidates/groovy/current/lib/groovy-2.5.12.jar \
-H:Path=/Users/davec/projects/graalvmtest \
-H:+DumpTargetInfo \
-H:ClassInitialization=org.codehaus.groovy.control.XStreamUtils:run_time,groovy.grape.GrapeIvy:run_time \
-H:FallbackThreshold=0 \
-H:Name=testpostgres \
-H:Class=TestPostgres \
-H:+ReportUnsupportedElementsAtRuntime \
-H:+AllowIncompleteClasspath \
-H:CLibraryPath=/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/svm/clibraries/darwin-amd64 \

]
[testpostgres:9392]    classlist:   2,139.70 ms,  0.96 GB
[testpostgres:9392]        (cap):   1,335.50 ms,  0.96 GB
[testpostgres:9392]        setup:   2,665.62 ms,  0.96 GB
# Building image for target platform: org.graalvm.nativeimage.Platform$DARWIN_AMD64
# Using native toolchain:
#   Name: LLVM (clang)
#   Vendor: apple
#   Version: 10.0.1
#   Target architecture: x86_64
#   Path: /usr/bin/cc
# Using CLibrary: com.oracle.svm.core.c.libc.GLibc
[testpostgres:9392]     (clinit):     341.85 ms,  2.29 GB
# Static libraries:
#   ../../../../Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/svm/clibraries/darwin-amd64/liblibchelper.a
#   ../../../../Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/libnet.a
#   ../../../../Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/svm/clibraries/darwin-amd64/libstrictmath.a
#   ../../../../Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/svm/clibraries/darwin-amd64/libffi.a
#   ../../../../Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/svm/clibraries/darwin-amd64/libdarwin.a
#   ../../../../Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/libnio.a
#   ../../../../Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/libjava.a
#   ../../../../Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/svm/clibraries/darwin-amd64/libjvm.a
#   ../../../../Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/lib/libzip.a
# Other libraries: -framework Foundation,pthread,dl,z
[testpostgres:9392]   (typeflow):  11,998.93 ms,  2.29 GB
[testpostgres:9392]    (objects):  11,417.96 ms,  2.29 GB
[testpostgres:9392]   (features):     504.28 ms,  2.29 GB
[testpostgres:9392]     analysis:  24,781.51 ms,  2.29 GB
[testpostgres:9392]     universe:     556.62 ms,  2.29 GB
[testpostgres:9392]      (parse):   3,093.46 ms,  2.30 GB
[testpostgres:9392]     (inline):   2,426.11 ms,  3.64 GB
[testpostgres:9392]    (compile):  13,472.71 ms,  4.43 GB
[testpostgres:9392]      compile:  20,177.99 ms,  4.43 GB
[testpostgres:9392]        image:   2,109.70 ms,  4.43 GB
[testpostgres:9392]        write:     650.51 ms,  4.43 GB
[testpostgres:9392]      [total]:  53,316.12 ms,  4.43 GB
```

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
    ```
java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:165)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:271)
	at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:342)
	at java.io.DataInputStream.readUTF(DataInputStream.java:594)
	at java.io.DataInputStream.readUTF(DataInputStream.java:569)
	at org.codehaus.groovy.reflection.GeneratedMetaMethod$DgmMethodRecord.loadDgmInfo(GeneratedMetaMethod.java:194)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:201)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:108)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:86)
	at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:37)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	at java.lang.Class.ensureInitialized(DynamicHub.java:499)
	at org.codehaus.groovy.reflection.ClassInfo.isValidWeakMetaClass(ClassInfo.java:298)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassForClass(ClassInfo.java:268)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:324)
	at TestPostgres.$getStaticMetaClass(TestPostgres.groovy)
	at TestPostgres.<init>(TestPostgres.groovy)
	at TestPostgres.main(TestPostgres.groovy:5)
```
```

**Comment by fernando-valdez** [comment]
Hello @davecramer, Thanks for reporting this. 
I will take a look at this issue. If I have a question, I will let you know.

**Comment by fernando-valdez** [comment]
Hello @davecramer, I was able to reproduce this issue locally. Fortunately, there is a fix. 

Please be sure to generate the config files, then add them to the native image generations. Here are the steps:

1. Generate the config file like this:
``` 
java -agentlib:native-image-agent=config-output-dir=conf/ \
-cp ./build/libs/graalvmtest-1.0-SNAPSHOT.jar:$GROOVY_HOME/lib/groovy-2.5.12.jar TestPostgres 
```

2. Once you create the files on the `conf` folder, add them to your native image generation:
```
native-image --native-image-info \
--verbose \
-cp ./build/libs/graalvmtest-1.0-SNAPSHOT.jar:$GROOVY_HOME/lib/groovy-2.5.12.jar \
--initialize-at-run-time=org.codehaus.groovy.control.XStreamUtils,groovy.grape.GrapeIvy \
--no-fallback \
--no-server \
-H:ConfigurationFileDirectories=conf/ \
-H:Name=testpostgres \
-H:Class=TestPostgres \
-H:+ReportUnsupportedElementsAtRuntime \
--allow-incomplete-classpath
```

Please let me know if you have any questions

**Comment by davecramer** [comment]
thx!
Dave Cramer
