### ISSUE TITLE
Issue with execute native image for Spring-boot app

### ISSUE THREAD

**Issue by openbeck** [oracle/graal#2613]
When I send request to my Spring-boot application then I get stacktrace shown below

My steps to build an image 
1. mkdir -p src/main/resources/META-INF/native-image
2. mvn clean package
3. java -agentlib:native-image-agent=config-output-dir=src/main/resources/META-INF/native-image \
  -jar target/rest-service.jar
4. mvn -Pgraal clean package

**Environment:**
-  Spring boot 2.3.1
- openjdk version "1.8.0_252"
- OpenJDK Runtime Environment (build 1.8.0_252-b09)
- OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 25.252-b09-jvmci-20.1-b02, mixed mode)
 - Windows 10
 - AMD64

Also I disable CGLIB in my app
@SpringBootApplication(proxyBeanMethods = false)
```
    ERROR 8688 --- [nio-8080-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: java.lang.IllegalStateException: org.springframework.cglib.core.CodeGenerationException: com.oracle.svm.core.jdk.UnsupportedFeatureError-->Unsupported method java.lang.ClassLoader.defineClass1(String, byte[], int, int, ProtectionDomain, String) is reachable] with root cause

com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported method java.lang.ClassLoader.defineClass1(String, byte[], int, int, ProtectionDomain, String) is reachable
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:86) ~[na:na]
        at java.lang.ClassLoader.defineClass1(ClassLoader.java) ~[blockingapp.demo.demoapplication.exe:na]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[blockingapp.demo.demoapplication.exe:na]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:na]
        at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:535) ~[na:na]
        at org.springframework.data.mapping.model.ClassGeneratingPropertyAccessorFactory$PropertyAccessorClassGenerator.generateCustomAccessorClass(ClassGeneratingPropertyAccessorFactory.java:337) ~[na:na]
        at org.springframework.data.mapping.model.ClassGeneratingPropertyAccessorFactory.createAccessorClass(ClassGeneratingPropertyAccessorFactory.java:199) ~[na:na]
        at org.springframework.data.mapping.model.ClassGeneratingPropertyAccessorFactory.potentiallyCreateAndRegisterPersistentPropertyAccessorClass(ClassGeneratingPropertyAccessorFactory.java:185) ~[na:na]
        at org.springframework.data.mapping.model.ClassGeneratingPropertyAccessorFactory.getPropertyAccessor(ClassGeneratingPropertyAccessorFactory.java:93) ~[na:na]
        at org.springframework.data.mapping.model.InstantiationAwarePropertyAccessorFactory.getPropertyAccessor(InstantiationAwarePropertyAccessorFactory.java:42) ~[na:na]
        at org.springframework.data.mapping.model.BasicPersistentEntity.getPropertyAccessor(BasicPersistentEntity.java:453) ~[na:na]
        at org.springframework.data.mongodb.core.convert.MappingMongoConverter.populateProperties(MappingMongoConverter.java:356) ~[blockingapp.demo.demoapplication.exe:na]
        at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:347) ~[blockingapp.demo.demoapplication.exe:na]
        at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:317) ~[blockingapp.demo.demoapplication.exe:na]
        at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:250) ~[blockingapp.demo.demoapplication.exe:na]
        at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:246) ~[blockingapp.demo.demoapplication.exe:na]
        at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:98) ~[blockingapp.demo.demoapplication.exe:na]
        at org.springframework.data.mongodb.core.MongoTemplate$ReadDocumentCallback.doWith(MongoTemplate.java:3130) ~[na:na]
        at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:2777) ~[blockingapp.demo.demoapplication.exe:na]
        at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:2507) ~[blockingapp.demo.demoapplication.exe:na]
        at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:2489) ~[blockingapp.demo.demoapplication.exe:na]
        at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:856) ~[blockingapp.demo.demoapplication.exe:na]
        at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.findAll(SimpleMongoRepository.java:380) ~[blockingapp.demo.demoapplication.exe:na]
        at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.findAll(SimpleMongoRepository.java:204) ~[blockingapp.demo.demoapplication.exe:na]
        at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.findAll(SimpleMongoRepository.java:54) ~[blockingapp.demo.demoapplication.exe:na]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:na]
        at org.springframework.data.repository.core.support.ImplementationInvocationMetadata.invoke(ImplementationInvocationMetadata.java:72) ~[na:na]
        at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:382) ~[blockingapp.demo.demoapplication.exe:na]
        at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:205) ~[na:na]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:549) ~[na:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[na:na]
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:155) ~[na:na]
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:130) ~[na:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[na:na]
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:37) ~[na:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[na:na]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95) ~[na:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[na:na]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[na:na]
        at com.sun.proxy.$Proxy216.findAll(Unknown Source) ~[na:na]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:na]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[na:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[na:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[na:na]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139) ~[na:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[na:na]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[na:na]
        at com.sun.proxy.$Proxy216.findAll(Unknown Source) ~[na:na]
        at blockingapp.demo.controllers.TraineeController.findAll(TraineeController.java:25) ~[blockingapp.demo.demoapplication.exe:na]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[na:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[na:na]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[na:na]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879) ~[blockingapp.demo.demoapplication.exe:na]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[blockingapp.demo.demoapplication.exe:na]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[blockingapp.demo.demoapplication.exe:na]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[blockingapp.demo.demoapplication.exe:na]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[blockingapp.demo.demoapplication.exe:na]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[blockingapp.demo.demoapplication.exe:na]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[blockingapp.demo.demoapplication.exe:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[blockingapp.demo.demoapplication.exe:na]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[blockingapp.demo.demoapplication.exe:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[blockingapp.demo.demoapplication.exe:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[na:na]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[blockingapp.demo.demoapplication.exe:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[na:na]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[blockingapp.demo.demoapplication.exe:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[blockingapp.demo.demoapplication.exe:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[na:na]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[blockingapp.demo.demoapplication.exe:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[blockingapp.demo.demoapplication.exe:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[na:na]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[blockingapp.demo.demoapplication.exe:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[blockingapp.demo.demoapplication.exe:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[na:na]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[na:na]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[na:na]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[na:na]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [blockingapp.demo.demoapplication.exe:na]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [blockingapp.demo.demoapplication.exe:na]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [blockingapp.demo.demoapplication.exe:na]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [blockingapp.demo.demoapplication.exe:na]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [blockingapp.demo.demoapplication.exe:na]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [blockingapp.demo.demoapplication.exe:na]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [blockingapp.demo.demoapplication.exe:na]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [blockingapp.demo.demoapplication.exe:na]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [blockingapp.demo.demoapplication.exe:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [blockingapp.demo.demoapplication.exe:na]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [blockingapp.demo.demoapplication.exe:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [blockingapp.demo.demoapplication.exe:na]
        at java.lang.Thread.run(Thread.java:748) [blockingapp.demo.demoapplication.exe:na]
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517) [blockingapp.demo.demoapplication.exe:na]
        at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138) [blockingapp.demo.demoapplication.exe:na]
```

**Comment by eginez** [comment]
@openbeck This issue is probably better suited for https://github.com/spring/spring-graal-native.
