### ISSUE TITLE
java.lang.UnsatisfiedLinkError: com.sun.imageio.plugins.jpeg.JPEGImageReader.initJPEGImageReader [aarch64]

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#2620]
When compiling TruffleSqueak for aarch64, I get the following `UnsatisfiedLinkError` when the JPEG plugin is used:

```
ERROR: java.lang.UnsatisfiedLinkError: com.sun.imageio.plugins.jpeg.JPEGImageReader.initJPEGImageReader()J [symbol: Java_com_sun_imageio_plugins_jpeg_JPEGImageReader_initJPEGImageReader or Java_com_sun_imageio_plugins_jpeg_JPEGImageReader_initJPEGImageReader__]
org.graalvm.polyglot.PolyglotException: java.lang.UnsatisfiedLinkError: com.sun.imageio.plugins.jpeg.JPEGImageReader.initJPEGImageReader()J [symbol: Java_com_sun_imageio_plugins_jpeg_JPEGImageReader_initJPEGImageReader or Java_com_sun_imageio_plugins_jpeg_JPEGImageReader_initJPEGImageReader__]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:153)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.initJPEGImageReader(JPEGImageReader.java)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.<init>(JPEGImageReader.java:232)
	at com.sun.imageio.plugins.jpeg.JPEGImageReaderSpi.createReaderInstance(JPEGImageReaderSpi.java:85)
	at javax.imageio.spi.ImageReaderSpi.createReaderInstance(ImageReaderSpi.java:320)
	at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:532)
	at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:516)
	at javax.imageio.ImageIO.read(ImageIO.java:1463)
	at javax.imageio.ImageIO.read(ImageIO.java:1363)
	at de.hpi.swa.trufflesqueak.nodes.plugins.JPEGReadWriter2Plugin$PrimJPEGReadHeaderfromByteArrayerrorMgrNode.doReadHeader(JPEGReadWriter2Plugin.java:113)
	...
```

*Tested with GraalVM CE 20.1.0 on Raspberry Pi OS (aarch64).*

**Comment by ebremer** [comment]
I'm getting this similar error on Centos 7.x but at runtime:
java.lang.UnsatisfiedLinkError: com.sun.imageio.plugins.jpeg.JPEGImageReader.initJPEGImageReader()J [symbol: Java_com_sun_imageio_plugins_jpeg_JPEGImageReader_initJPEGImageReader or Java_com_sun_imageio_plugins_jpeg_JPEGImageReader_initJPEGImageReader__]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.initJPEGImageReader(JPEGImageReader.java)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.<init>(JPEGImageReader.java:232)
	at com.sun.imageio.plugins.jpeg.JPEGImageReaderSpi.createReaderInstance(JPEGImageReaderSpi.java:85)
	at javax.imageio.spi.ImageReaderSpi.createReaderInstance(ImageReaderSpi.java:320)
	at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:532)
	at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:516)
	at javax.imageio.ImageIO.read(ImageIO.java:1463)
	at javax.imageio.ImageIO.read(ImageIO.java:1363)

**Comment by ebremer** [comment]
see also: https://stackoverflow.com/questions/60527663/is-javax-imageio-supported-by-graalvm-native-image

**Comment by christianwimmer** [comment]
With the change in GraalVM 20.2 that many JDK classes are no longer initialized at build time, this might work now already.

**Comment by fniephaus** [comment]
It's unfortunately still an issue on 20.2:

```
$ ./graalvm-ce-java11-20.2.0/bin/trufflesqueak
[trufflesqueak] Running Squeak/Smalltalk on GraalVM CE...
[trufflesqueak] Image loaded in 808ms.
ERROR: java.lang.UnsatisfiedLinkError: com.sun.imageio.plugins.jpeg.JPEGImageReader.initJPEGImageReader()J [symbol: Java_com_sun_imageio_plugins_jpeg_JPEGImageReader_initJPEGImageReader or Java_com_sun_imageio_plugins_jpeg_JPEGImageReader_initJPEGImageReader__]
org.graalvm.polyglot.PolyglotException: java.lang.UnsatisfiedLinkError: com.sun.imageio.plugins.jpeg.JPEGImageReader.initJPEGImageReader()J [symbol: Java_com_sun_imageio_plugins_jpeg_JPEGImageReader_initJPEGImageReader or Java_com_sun_imageio_plugins_jpeg_JPEGImageReader_initJPEGImageReader__]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:153)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.initJPEGImageReader(JPEGImageReader.java)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.<init>(JPEGImageReader.java:232)
	at com.sun.imageio.plugins.jpeg.JPEGImageReaderSpi.createReaderInstance(JPEGImageReaderSpi.java:85)
	at javax.imageio.spi.ImageReaderSpi.createReaderInstance(ImageReaderSpi.java:320)
	at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:532)
	at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:516)
	at javax.imageio.ImageIO.read(ImageIO.java:1463)
	at javax.imageio.ImageIO.read(ImageIO.java:1363)
	at de.hpi.swa.trufflesqueak.nodes.plugins.JPEGReadWriter2Plugin$PrimJPEGReadHeaderfromByteArrayerrorMgrNode.readImageOrPrimFail(JPEGReadWriter2Plugin.java:119)
	at de.hpi.swa.trufflesqueak.nodes.plugins.JPEGReadWriter2Plugin$PrimJPEGReadHeaderfromByteArrayerrorMgrNode.doReadHeader(JPEGReadWriter2Plugin.java:110)
	at de.hpi.swa.trufflesqueak.nodes.plugins.JPEGReadWriter2PluginFactory$PrimJPEGReadHeaderfromByteArrayerrorMgrNodeFactory$PrimJPEGReadHeaderfromByteArrayerrorMgrNodeGen.executeAndSpecialize(JPEGReadWriter2PluginFactory.java:852)
	at de.hpi.swa.trufflesqueak.nodes.plugins.JPEGReadWriter2PluginFactory$PrimJPEGReadHeaderfromByteArrayerrorMgrNodeFactory$PrimJPEGReadHeaderfromByteArrayerrorMgrNodeGen.executePrimitive(JPEGReadWriter2PluginFactory.java:839)
	at de.hpi.swa.trufflesqueak.nodes.dispatch.CachedDispatchNode$CachedDispatchPrimitiveNode.execute(CachedDispatchNode.java:108)
...
```

**Comment by vjovanov** [comment]
We have a fix for this in the pipeline. It should be in by 20.3.

**Comment by giova333** [comment]
@vjovanov has this issue already been fixed?

**Comment by vjovanov** [comment]
I think JPEG had issues and this PR ought to address them: 

https://github.com/oracle/graal/pull/3032#issuecomment-736515615

**Comment by jerboaa** [comment]
> I think JPEG had issues and this PR ought to address them:
> 
> [#3032 (comment)](https://github.com/oracle/graal/pull/3032#issuecomment-736515615)

I concur. It should be fixed with that PR.

**Comment by jerboaa** [comment]
This should be fixed with latest graal master.

**Comment by vjovanov** [comment]
Thaks @jerboaa!

**Comment by Rohit-nagbhidkar** [comment]
Still having error while calling ImageIO.read on jpeg files
using quarkus native image 20.3.1-java11
Exception in thread "Lambda Thread" java.lang.UnsatisfiedLinkError: com.sun.imageio.plugins.jpeg.JPEGImageReader.initJPEGImageReader()J [symbol: Java_com_sun_imageio_plugins_jpeg_JPEGImageReader_initJPEGImageReader or Java_com_sun_imageio_plugins_jpeg_JPEGImageReader_initJPEGImageReader__]
at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:153)
at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
at com.sun.imageio.plugins.jpeg.JPEGImageReader.initJPEGImageReader(JPEGImageReader.java)
at com.sun.imageio.plugins.jpeg.JPEGImageReader.<init>(JPEGImageReader.java:232)
at com.sun.imageio.plugins.jpeg.JPEGImageReaderSpi.createReaderInstance(JPEGImageReaderSpi.java:85)
at javax.imageio.spi.ImageReaderSpi.createReaderInstance(ImageReaderSpi.java:320)
at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:532)
at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:516)
at javax.imageio.ImageIO.read(ImageIO.java:1463)
at javax.imageio.ImageIO.read(ImageIO.java:1363)

**Comment by jerboaa** [comment]
> quarkus native image 20.3.1-java11

What is that exactly? Is that a container image? If so, which fully qualified name of the image is that?

**Comment by Rohit-nagbhidkar** [comment]
> > quarkus native image 20.3.1-java11
> 
> What is that exactly? Is that a container image? If so, which fully qualified name of the image is that?
its quay.io/quarkus/ubi-quarkus-native-image:20.3.1-java11

**Comment by jerboaa** [comment]
> > > quarkus native image 20.3.1-java11
> > 
> > 
> > What is that exactly? Is that a container image? If so, which fully qualified name of the image is that?
> 
> its quay.io/quarkus/ubi-quarkus-native-image:20.3.1-java11

AFAIK, that image doesn't support AWT yet as Graal VM 20.3.1 itself doesn't. You'd have to try 21.0 for that to have a chance of working.

Alternatively you can give `ubi-quarkus-mandrel`[1] a spin which has some relevant AWT backports for this to work.

[1] quay.io/quarkus/ubi-quarkus-mandrel:20.3-java11

**Comment by Rohit-nagbhidkar** [comment]
> > > > quarkus native image 20.3.1-java11
> > > 
> > > 
> > > What is that exactly? Is that a container image? If so, which fully qualified name of the image is that?
> > 
> > 
> > its quay.io/quarkus/ubi-quarkus-native-image:20.3.1-java11
> 
> AFAIK, that image doesn't support AWT yet as Graal VM 20.3.1 itself doesn't. You'd have to try 21.0 for that to have a chance of working.
> 
> Alternatively you can give `ubi-quarkus-mandrel`[1] a spin which has some relevant AWT backports for this to work.
> 
> [1] quay.io/quarkus/ubi-quarkus-mandrel:20.3-java11

i have also tried quay.io/quarkus/ubi-quarkus-native-image:21.0-java11
its giving following error
Error: Runtime exited with error: signal: segmentation fault (core dumped) Runtime.ExitError
