### ISSUE TITLE
Native Build Error, report 'Error encountered while parsing io.netty.util.internal.UnsafeAtomicLongFieldUpdater'

### ISSUE THREAD

**Issue by LilithBristol** [oracle/graal#2643]
When i use native-image build my java project ,it report a error

Enviroment
 - GraalVM CE 20.2.0-dev-20200701_0158
 - JDK 8
 - Windows 10 1903
 - AMD64

build command
```powershell
 native-image.cmd -H:+TraceClassInitialization -H:+ReportExceptionStackTraces --allow-incomplete-classpath --initialize-at-build-time=org.slf4j,ch.qos.logback --initialize-at-run-time=io.netty.handler.ssl.util.ThreadLocalInsecureRandom,io.netty.util.internal.UnsafeAtomicReferenceFieldUpdater --no-fallback -jar .\debug-tool-0.1.0.jar
```

error
```java
Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing io.netty.util.internal.UnsafeAtomicLongFieldUpdater.get(java.lang.Object)
Parsing context:
        parsing java.util.concurrent.atomic.AtomicLongFieldUpdater.addAndGet(AtomicLongFieldUpdater.java:275)
        parsing io.netty.channel.ChannelOutboundBuffer.decrementPendingOutboundBytes(ChannelOutboundBuffer.java:196)
        parsing io.netty.channel.ChannelOutboundBuffer.remove0(ChannelOutboundBuffer.java:300)
        parsing io.netty.channel.ChannelOutboundBuffer.failFlushed(ChannelOutboundBuffer.java:622)
        parsing io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:610)
        parsing io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:551)
        parsing io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1289)
        parsing io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:524)
        parsing io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:509)
        parsing io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:378)
        parsing io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:1003)
        parsing io.netty.channel.AbstractChannel.close(AbstractChannel.java:182)
        parsing com.taobao.tair.comm.TairClientFactory.createClient(TairClientFactory.java:280)
        parsing com.taobao.tair.comm.TairClientFactory.access$000(TairClientFactory.java:48)
        parsing com.taobao.tair.comm.TairClientFactory$2.call(TairClientFactory.java:186)
        parsing com.taobao.tair.comm.TairClientFactory$2.call(TairClientFactory.java:183)
        parsing picocli.CommandLine.executeUserObject(CommandLine.java:1853)
        parsing picocli.CommandLine.access$1100(CommandLine.java:145)
        parsing picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2255)
        parsing picocli.CommandLine$RunLast.handle(CommandLine.java:2249)
        parsing picocli.CommandLine$RunLast.handle(CommandLine.java:2213)
        parsing picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2080)
        parsing picocli.CommandLine.execute(CommandLine.java:1978)
        parsing com.aliyun.pop.debug.tool.PopDebugTool.main(PopDebugTool.kt:23)
        parsing com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:149)
        parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:184)
        parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

        at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:331)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:302)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
        at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:227)
        at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:470)
        at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:542)
        at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:542)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.oracle.svm.hosted.analysis.flow.SVMMethodTypeFlowBuilder$UnsafeOffsetError: Field AnalysisField<UnsafeAtomicLongFieldUpdater.offset accessed: false reads: true written: true> is used as an offset in an unsafe operation, but no value recomputation found.
 Wrapped field: HotSpotResolvedJavaFieldImpl<io.netty.util.internal.UnsafeAtomicLongFieldUpdater.offset long:16>
 Location: at io.netty.util.internal.UnsafeAtomicLongFieldUpdater.get(UnsafeAtomicLongFieldUpdater.java:60) [bci: 6]
        at com.oracle.svm.hosted.analysis.flow.SVMMethodTypeFlowBuilder$UnsafeOffsetError.report(SVMMethodTypeFlowBuilder.java:100)
        at com.oracle.svm.hosted.analysis.flow.SVMMethodTypeFlowBuilder.checkUnsafeOffset(SVMMethodTypeFlowBuilder.java:143)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder$NodeIterator.node(MethodTypeFlowBuilder.java:1060)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.graph.PostOrderNodeIterator.apply(PostOrderNodeIterator.java:106)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:438)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:313)
        ... 13 more
Error: Image build request failed with exit status 1
```

I.m not use unsafe method in the source,but poject include netty depndency that use a unsafe method.

```groovy
 io.netty:netty-all:4.0.35.Final
```

The Unsafe Method in netty

```java
final class UnsafeAtomicReferenceFieldUpdater<U, M> extends AtomicReferenceFieldUpdater<U, M> {
    private final long offset;
    private final Unsafe unsafe;

    UnsafeAtomicReferenceFieldUpdater(Unsafe unsafe, Class<? super U> tClass, String fieldName)
            throws NoSuchFieldException {
        Field field = tClass.getDeclaredField(fieldName);
        if (!Modifier.isVolatile(field.getModifiers())) {
            throw new IllegalArgumentException("Must be volatile");
        }
        this.unsafe = unsafe;
        offset = unsafe.objectFieldOffset(field);
    }

    @Override
    public boolean compareAndSet(U obj, M expect, M update) {
        return unsafe.compareAndSwapObject(obj, offset, expect, update);
    }

    @Override
    public boolean weakCompareAndSet(U obj, M expect, M update) {
        return unsafe.compareAndSwapObject(obj, offset, expect, update);
    }

    @Override
    public void set(U obj, M newValue) {
        unsafe.putObjectVolatile(obj, offset, newValue);
    }

    @Override
    public void lazySet(U obj, M newValue) {
        unsafe.putOrderedObject(obj, offset, newValue);
    }

    @SuppressWarnings("unchecked")
    @Override
    public M get(U obj) {
        return (M) unsafe.getObjectVolatile(obj, offset);
    }
}
```

i see the netty [demo](https://github.com/cstancu/netty-native-demo)
and add this in the reflect-config.json

```json
{
    "name": "io.netty.channel.socket.nio.NioServerSocketChannel",
    "methods": [
      { "name": "<init>", "parameterTypes": [] }
    ]
  }
```

it seems not work for this question

**Comment by cstancu** [comment]
Please a more recent version of Netty, the latest release is recommended. It should contain all the necessary support code for building Native Image.

**Comment by zipper01** [comment]
It's Jan 2023 now and I still got [a similar problem](https://stackoverflow.com/questions/75013326/graalvm-native-image-image-build-error-report-error-encountered-while-parsing). Also see [here (no progress)](https://github.com/netty/netty/issues/10895).
