### ISSUE TITLE
Unable to call a default interface method on a JDK proxy

### ISSUE THREAD

**Issue by sdeleuze** [oracle/graal#2658]
We are looking for a way to call a default interface method on a JDK proxy. Currently with https://github.com/lettuce-io/lettuce-core/blob/main/src/main/java/io/lettuce/core/dynamic/intercept/DefaultMethodInvokingInterceptor.java and https://github.com/lettuce-io/lettuce-core/blob/main/src/main/java/io/lettuce/core/internal/DefaultMethods.java we get:
```
[4:29 PM] Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported constructor java.lang.invoke.MemberName.<init>(Method, boolean) is reachable: All methods from java.lang.invoke should have been replaced during image building.
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:86)
	at java.lang.invoke.MemberName.<init>(MemberName.java:521)
	at java.lang.invoke.MethodHandles$Lookup.unreflectSpecial(MethodHandles.java:1233)
	at io.lettuce.core.internal.DefaultMethods$MethodHandleLookup$1.lookup(DefaultMethods.java:71)
	at io.lettuce.core.internal.DefaultMethods.lookupMethodHandle(DefaultMethods.java:49)
	at io.lettuce.core.cluster.ClusterFutureSyncInvocationHandler.lookupDefaultMethod(ClusterFutureSyncInvocationHandler.java:202)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at io.lettuce.core.cluster.ClusterFutureSyncInvocationHandler.handleInvocation(ClusterFutureSyncInvocationHandler.java:85)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy131.masters(Unknown Source)
	at example.App.main(App.java:19)
```

**Comment by peter-hofer** [comment]
Thank you for your report @sdeleuze. The target method of a method handle call must be known at image build time, which is not possible with how `io.lettuce.core.internal.DefaultMethods` utilities are used here.

**Comment by cstancu** [comment]
`MethodHandle` support is under development and is being tracked by https://github.com/oracle/graal/issues/2761.

**Comment by peter-hofer** [comment]
I believe this should be resolved by the recent method handle enhancements. @sdeleuze @loicottet  , please reopen if it is not.

**Comment by sdeleuze** [comment]
@peter-hofer Thanks, could you please set the related milestone (21.1 I guess) ?
