### ISSUE TITLE
NPE when running native image: Java + LLVM

### ISSUE THREAD

**Issue by vodka2** [oracle/graal#2662]
I can't run even a minimal native image that calls C code from Java. Could not find any examples, and the error is not clear at all. When running the program with `java`, without building the native image, no error happens.

**Steps to reproduce**
t.cpp:
```c
#include <stdio.h>

int test() {
    puts("Hello world!");
    return 0;
}
```
Polyglot.java
```java
import java.io.*;
import org.graalvm.polyglot.*;

class Polyglot {
    public static void main(String[] args) throws IOException {
        Context polyglot = Context.newBuilder().
        		               allowAllAccess(true).build();
        File file = new File("/absolute-path/polyglot0");
        Source source = Source.newBuilder("llvm", file).build();
        Value cpart = polyglot.eval(source);
        System.out.println(cpart);
    }
}
```
```
$LLVM_TOOLCHAIN/clang t.cpp -lpolyglot-mock -o polyglot0
javac Polyglot.java
native-image --no-fallback --no-server --language:llvm --initialize-at-build-time -cp . Polyglot
./polyglot
```
**Environment:**
 - GraalVM version: **GraalVM CE 20.2.0-dev-20200709_0208**
 - JDK major version: **11**
 - OS: **Arch Linux**
 - Architecture: **AMD64**

**More details**
```
Exception in thread "main" org.graalvm.polyglot.PolyglotException: java.lang.IllegalStateException: java.lang.NullPointerException
	at com.oracle.truffle.llvm.runtime.LLVMContext.initialize(LLVMContext.java:302)
	at com.oracle.truffle.llvm.runtime.LLVMLanguage.initializeContext(LLVMLanguage.java:125)
	at com.oracle.truffle.llvm.runtime.LLVMLanguage.initializeContext(LLVMLanguage.java:68)
	at com.oracle.truffle.api.TruffleLanguage$Env.postInit(TruffleLanguage.java:2966)
	at com.oracle.truffle.api.LanguageAccessor$LanguageImpl.postInitEnv(LanguageAccessor.java:230)
	at com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureInitialized(PolyglotLanguageContext.java:570)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:875)
	at org.graalvm.polyglot.Context.eval(Context.java:345)
	at Polyglot.main(Polyglot.java:10)
Caused by: java.lang.NullPointerException
	at com.oracle.truffle.llvm.runtime.LLVMContext.initialize(LLVMContext.java:299)
	... 8 more
Caused by: Attached Guest Language Frames (0)
Internal GraalVM error, please report at https://github.com/oracle/graal/issues/.
```

**Comment by rschatz** [comment]
Hi @vodka2 !

The problem here is that it doesn't find the LLVM language home. It needs to load a few libraries from there.
If you run it with `./polyglot -Dllvm.home=$GRAALVM_HOME/languages/llvm` it works.

I'm actually not sure whether that's a bug or by design. @chumer do you know how the home finder interacts with custom native images? Is `-Dllvm.home` the recommended solution, or do we have something better?

**Comment by vodka2** [comment]
@rschatz Thank you, this is a really secret command line option, only one match on Google.

**Comment by rschatz** [comment]
I just got reminded by @eregon that `-Dllvm.home=...` is deprecated, it should be `-Dorg.graalvm.language.llvm.home=...` ;)

**Comment by rschatz** [comment]
The problem original problem seems fixed, but I'll leave this open until we have some documentation on this problem.

**Comment by eregon** [comment]
I'll work on documenting the various ways to set the home.
Until then, `-Dorg.graalvm.home=$GRAALVM_HOME` or `-Dorg.graalvm.language.llvm.home=$GRAALVM_HOME/languages/llvm` are two ways to set the home at runtime (the first one has the advantage that other languages will find their home too).

**Comment by eregon** [comment]
This is now documented in https://www.graalvm.org/latest/reference-manual/embed-languages/#build-native-executables-from-polyglot-applications + language homes are copied automatically.
