### ISSUE TITLE
Java SecurityManager enabled requires access to java.home

### ISSUE THREAD

**Issue by vloo** [oracle/graal#2678]
**Environment**
windows10, java 11

kotlin server side application using graalvm.js as library
`implementation(group = "org.graalvm.js", name = "js", version = "20.1.0")`
`implementation(group = "org.graalvm.js", name = "js-scriptengine", version = "20.1.0")`

**Java Security Manager enabled** without read rights to filesystem
```
    val context: Context = Context.newBuilder()
            .allowHostAccess(HostAccess.ALL)
            .allowIO(true)
            .allowCreateThread(true)
            .allowCreateProcess(true)
            .allowExperimentalOptions(true).option("js.nashorn-compat", "true")
            .allowHostClassLookup(ScriptClassFilterPredicate())
            .build()
        context.getBindings("js")
        context.eval("js", "var a = 1;")
```
**throws exception:**
```
org.graalvm.polyglot.PolyglotException: java.lang.ExceptionInInitializerError
	at com.oracle.truffle.js.runtime.JSContext.createRealm(JSContext.java:593) ~[js-20.1.0.jar!/:?]
	at com.oracle.truffle.js.lang.JavaScriptLanguage.createContext(JavaScriptLanguage.java:349) ~[js-20.1.0.jar!/:?]
	at com.oracle.truffle.js.lang.JavaScriptLanguage.createContext(JavaScriptLanguage.java:117) ~[js-20.1.0.jar!/:?]
	at com.oracle.truffle.api.LanguageAccessor$LanguageImpl.createEnvContext(LanguageAccessor.java:212) ~[truffle-api-20.1.0.jar!/:?]
	at com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureCreated(PolyglotLanguageContext.java:465) ~[truffle-api-20.1.0.jar!/:?]
	at com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureInitialized(PolyglotLanguageContext.java:540) ~[truffle-api-20.1.0.jar!/:?]
	at com.oracle.truffle.polyglot.PolyglotContextImpl.getBindings(PolyglotContextImpl.java:686) ~[truffle-api-20.1.0.jar!/:?]
	at org.graalvm.polyglot.Context.getBindings(Context.java:408) ~[graal-sdk-20.1.0.jar!/:?]
```

**real cause:**
```
access denied ("java.io.FilePermission" "C:\Program Files\Java\jdk-11.0.7" "read")
java.security.AccessControlException: access denied ("java.io.FilePermission" "C:\Program Files\Java\jdk-11.0.7" "read")
```

throw from **DefaultHomeFinder**
`line 198: if (!Files.exists(javaHome)) {

**workeround:**
set any value to "org.graalvm.launcher.home" before script execution
`System.setProperty("org.graalvm.launcher.home", "graal-vm-home-placeholder-value")`

there is no need to have java.home enabled in the security manager

**Comment by EdenYoung1** [comment]
I found that there is a similar problem in [openj9](https://github.com/eclipse/openj9). Maybe we can refer to this issue https://github.com/eclipse/openj9/issues/6119  to learn more context about the bug ?
Or maybe we can locate the faulty lines and this fix https://github.com/eclipse/openj9/pull/6288 can probably help repair the bug ?

**Comment by fernando-valdez** [comment]
Closing this ticket due to the lack of response. Please feel free to reopen it if the problem persists
