### ISSUE TITLE
Caused by: com.sleepycat.je.EnvironmentFailureException: (JE 18.3.12) Class does not exist: com.sleepycat.persist.impl.CollectionProxy$ArrayListProxy UNEXPECTED_STATE: Unexpected internal state, may have side effects.

### ISSUE THREAD

**Issue by dhanendras** [oracle/graal#2685]
I tried with both grallvm 19.x and 20.x but giving error in berkleydb .. I am using quarkus 1.6.0.Final .

Please help us out here or let us know if any more information is needed.

**Comment by shelajev** [comment]
Hi, @dhanendras, yes, more information needed. Can you please provide more information, preferably following the [template for native image related issues](https://github.com/oracle/graal/issues/new?assignees=&labels=bug%2C+native-image&template=1_issues_native_image.md&title=). 

thanks a lot. Otherwise it's really impossible to help based on the insufficient info provided.

**Comment by dhanendras** [comment]
@shelajev Thanks for the reply and apologies for the delay. Please find the detail in next comment as per the template. I have created a sample code in GitHub for the understanding.

**Comment by dhanendras** [comment]
**Describe the issue**
A clear and concise description of the issue. We recommend using the [latest snapshot builds](https://github.com/graalvm/graalvm-ce-dev-builds/releases) to replicate the issue as  bugs are constantly being fixed in the master branch

We are using berkelydb in our application and the maven dependency is

 <dependency>
      <groupId>com.sleepycat</groupId>
      <artifactId>je</artifactId>
      <version>18.3.12</version>
    </dependency>

The error we are getting is in run time, when we try to run the native image.



2020-07-22 07:44:10,557 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /test/sleepy failed, error id: d2a67f33-9604-4c69-a4d2-9974962e8027-1: org.jboss.resteasy.spi.UnhandledException: com.sleepycat.je.EnvironmentFailureException: (JE 18.3.12) Class does not exist: com.sleepycat.persist.impl.CollectionProxy$ArrayListProxy UNEXPECTED_STATE: Unexpected internal state, may have side effects.
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:216)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:515)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:259)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:163)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:245)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:132)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:37)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:94)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: com.sleepycat.je.EnvironmentFailureException: (JE 18.3.12) Class does not exist: com.sleepycat.persist.impl.CollectionProxy$ArrayListProxy UNEXPECTED_STATE: Unexpected internal state, may have side effects.
	at com.sleepycat.compat.DbCompat.unexpectedState(DbCompat.java:591)
	at com.sleepycat.persist.impl.PersistCatalog.createFormat(PersistCatalog.java:749)
	at com.sleepycat.persist.impl.PersistCatalog.init(PersistCatalog.java:494)
	at com.sleepycat.persist.impl.PersistCatalog.initAndRetry(PersistCatalog.java:274)
	at com.sleepycat.persist.impl.PersistCatalog.<init>(PersistCatalog.java:234)
	at com.sleepycat.persist.impl.Store.<init>(Store.java:210)
	at com.sleepycat.persist.EntityStore.<init>(EntityStore.java:204)
	at com.sample.sleepycat.Test.testSleepy(Test.java:43)
	at com.sample.sleepycat.Test_ClientProxy.testSleepy(Test_ClientProxy.zig:184)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:638)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:504)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:454)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:456)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:417)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:391)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:488)
	... 19 more


**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. git clone https://github.com/dhanendras/graalsleepy.git
2. cd sleepycat
3. Mvn clean package -Pnative
4. Cd target
5. ./sleepycat-0.0.1-SNAPSHOT-runner
6. Paste the following link in browser :’
http://localhost:8080/test/sleepy

After pressing enter we’ll get 501 and the above error stack in console.



**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **[e.g. EE 19.3, CE 20.0, CE 20.1.0-dev-20200304_0848]**
 - JDK major version: **11**
 - OS: ** macOS Catalina**
 - Architecture: **AMD64**


**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
    

2020-07-22 07:44:10,557 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /test/sleepy failed, error id: d2a67f33-9604-4c69-a4d2-9974962e8027-1: org.jboss.resteasy.spi.UnhandledException: com.sleepycat.je.EnvironmentFailureException: (JE 18.3.12) Class does not exist: com.sleepycat.persist.impl.CollectionProxy$ArrayListProxy UNEXPECTED_STATE: Unexpected internal state, may have side effects.
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:216)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:515)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:259)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:163)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:245)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:132)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:37)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:94)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: com.sleepycat.je.EnvironmentFailureException: (JE 18.3.12) Class does not exist: com.sleepycat.persist.impl.CollectionProxy$ArrayListProxy UNEXPECTED_STATE: Unexpected internal state, may have side effects.
	at com.sleepycat.compat.DbCompat.unexpectedState(DbCompat.java:591)
	at com.sleepycat.persist.impl.PersistCatalog.createFormat(PersistCatalog.java:749)
	at com.sleepycat.persist.impl.PersistCatalog.init(PersistCatalog.java:494)
	at com.sleepycat.persist.impl.PersistCatalog.initAndRetry(PersistCatalog.java:274)
	at com.sleepycat.persist.impl.PersistCatalog.<init>(PersistCatalog.java:234)
	at com.sleepycat.persist.impl.Store.<init>(Store.java:210)
	at com.sleepycat.persist.EntityStore.<init>(EntityStore.java:204)
	at com.sample.sleepycat.Test.testSleepy(Test.java:43)
	at com.sample.sleepycat.Test_ClientProxy.testSleepy(Test_ClientProxy.zig:184)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:638)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:504)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:454)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:456)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:417)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:391)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:488)
	... 19 more

```

**Comment by oubidar-Abderrahim** [comment]
A bug was raised to the Dev team regarding this issue.

**Comment by vjovanov** [comment]
@oubidar-Abderrahim have you tried reproducing this example and tried to run it with an agent to make sure there is no missing config here?

**Comment by oubidar-Abderrahim** [comment]
@vjovanov yes, I tried the agent but still got the same behavior. I created GR-25639 with the provided reproducer, I also created a mush smaller reproducer that you can find attached to the GR ticket.

**Comment by vjovanov** [comment]
Thanks, @gradinac is probably the best person to handle this.

**Comment by gradinac** [comment]
Hey @dhanendras, thank you for reporting the issue!
It appears that some native-image configuration was missing. However, after tweaking the configuration, we hit the following exception at runtime:
```
Caused by: java.lang.UnsupportedOperationException: Serialization of class definitions not supported
	at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:14)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1135)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)
	at com.sleepycat.persist.impl.PersistCatalog.writeData(PersistCatalog.java:1356)
	at com.sleepycat.persist.impl.PersistCatalog.init(PersistCatalog.java:574)
	at com.sleepycat.persist.impl.PersistCatalog.initAndRetry(PersistCatalog.java:274)
	at com.sleepycat.persist.impl.PersistCatalog.<init>(PersistCatalog.java:234)
	at com.sleepycat.persist.impl.Store.<init>(Store.java:210)
```
Serialization support is a new feature available from GraalVM 21.0 (available currently in [dev builds](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), however, after attempting to build a native-image with the newer GraalVM version, we hit the exact same exception.

The following config was used for the image build: [native-image-config.tar.gz](https://github.com/oracle/graal/files/5665668/native-image-config.tar.gz)
However, there appears to be a substitution added to Quarkus that terminates the image if it reaches serialization-related classes: https://github.com/quarkusio/quarkus/pull/9686/commits/214e05cf396c8dca18bd6a7b99062fe42d9749bc

You can create an issue there for the above problem and follow up with them on how to best resolve this. If any native-image issues come up in the process, let us know.

**Comment by vjovanov** [comment]
@gradinac how come @oubidar-Abderrahim didn't see that the configuration is missing?

**Comment by gradinac** [comment]
The most likely reason is because of the way the underlying projects wrapped the exception:
```
2020-07-22 07:44:10,557 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /test/sleepy failed, error id: d2a67f33-9604-4c69-a4d2-9974962e8027-1: org.jboss.resteasy.spi.UnhandledException: com.sleepycat.je.EnvironmentFailureException: (JE 18.3.12) Class does not exist: com.sleepycat.persist.impl.CollectionProxy$ArrayListProxy UNEXPECTED_STATE: Unexpected internal state, may have side effects.
```
The configuration generated by the agent also requires a bit of manual tweaking to get the image build working (I've also probably provided a superset of the necessary config in the previous comment)
