### ISSUE TITLE
Exception in thread "main" java.time.DateTimeException: Unable to initialize HijrahCalendar: Hijrah-umalqura

### ISSUE THREAD

**Issue by jnorthrup** [oracle/graal#2702]
I am having problems porting openjdk standard jdk libs to graalvm.  Kotlin does not appear to be the issue.  this looks like a bug that was in openjdk9 that was fixed for openjdk10

repeatable git project repos:

support library:
`git@github.com:jnorthrup/columnar.git
`
executable:
` git@gitlab.com:fjLWN2z5O1/random-verb-generated-project-name.git
`
both are public repos with tag  graaldatesissue

maven effective pom  
```

<!-- ====================================================================== -->
<!--                                                                        -->
<!-- Generated on 2020-07-23T01:22:18                                       -->
<!--                                                                        -->
<!-- ====================================================================== -->

<!-- ====================================================================== -->
<!--                                                                        -->
<!-- Effective POM for project 'columnar:kaggle-m5:jar:1.0.1-SNAPSHOT'      -->
<!--                                                                        -->
<!-- ====================================================================== -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>columnar</groupId>
    <artifactId>columnar-parent</artifactId>
    <version>1.0.1-SNAPSHOT</version>
  </parent>

  <groupId>columnar</groupId>
  <artifactId>kaggle-m5</artifactId>
  <version>1.0.1-SNAPSHOT</version>

  <properties>
    <graalvm.version>20.1.0</graalvm.version>
    <kotlin.version>1.3.72</kotlin.version>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.graalvm.sdk</groupId>
      <artifactId>graal-sdk</artifactId>
      <version>20.1.0</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>columnar</groupId>
      <artifactId>lillypads</artifactId>
      <version>1.0.1-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <version>5.6.0</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlinx</groupId>
      <artifactId>kotlinx-coroutines-core</artifactId>
      <version>1.3.7</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <artifactId>kotlin-stdlib</artifactId>
          <groupId>org.jetbrains.kotlin</groupId>
        </exclusion>
        <exclusion>
          <artifactId>kotlin-stdlib-common</artifactId>
          <groupId>org.jetbrains.kotlin</groupId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib-jdk8</artifactId>
      <version>1.3.72</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-test-junit</artifactId>
      <version>1.3.72</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <repositories>
    <repository>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>bintray.kotlin.eap</id>
      <name>Bintray Kotlin EAP Repository</name>
      <url>https://dl.bintray.com/kotlin/kotlin-eap</url>
    </repository>
    <repository>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>central</id>
      <name>Central Repository</name>
      <url>https://repo.maven.apache.org/maven2</url>
    </repository>
  </repositories>

  <pluginRepositories>
    <pluginRepository>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>bintray.kotlin.eap</id>
      <name>Bintray Kotlin EAP Repository</name>
      <url>https://dl.bintray.com/kotlin/kotlin-eap</url>
    </pluginRepository>
    <pluginRepository>
      <releases>
        <updatePolicy>never</updatePolicy>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>central</id>
      <name>Central Repository</name>
      <url>https://repo.maven.apache.org/maven2</url>
    </pluginRepository>
  </pluginRepositories>

  <build>
    <sourceDirectory>/home/jim/work/wm/src/main/kotlin</sourceDirectory>
    <scriptSourceDirectory>/home/jim/work/wm/src/main/scripts</scriptSourceDirectory>
    <testSourceDirectory>/home/jim/work/wm/src/test/kotlin</testSourceDirectory>
    <outputDirectory>/home/jim/work/wm/target/classes</outputDirectory>
    <testOutputDirectory>/home/jim/work/wm/target/test-classes</testOutputDirectory>

    <resources>
      <resource>
        <directory>/home/jim/work/wm/src/main/resources</directory>
      </resource>
    </resources>

    <testResources>
      <testResource>
        <directory>/home/jim/work/wm/src/test/resources</directory>
      </testResource>
    </testResources>

    <directory>/home/jim/work/wm/target</directory>
    <finalName>kaggle-m5-1.0.1-SNAPSHOT</finalName>

    <pluginManagement>
      <plugins>
        <plugin>
          <artifactId>maven-antrun-plugin</artifactId>
          <version>1.3</version>
        </plugin>
        <plugin>
          <artifactId>maven-assembly-plugin</artifactId>
          <version>2.2-beta-5</version>
        </plugin>
        <plugin>
          <artifactId>maven-dependency-plugin</artifactId>
          <version>2.8</version>
        </plugin>
        <plugin>
          <artifactId>maven-release-plugin</artifactId>
          <version>2.5.3</version>
        </plugin>
      </plugins>
    </pluginManagement>

    <plugins>
      <plugin>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>2.8</version>
        <executions>
          <execution>
            <phase>install</phase>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <configuration>
              <outputDirectory>/home/jim/work/wm/target/lib</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.jetbrains.kotlin</groupId>
        <artifactId>kotlin-maven-plugin</artifactId>
        <version>1.3.72</version>
        <executions>
          <execution>
            <id>compile</id>
            <phase>compile</phase>
            <goals>
              <goal>compile</goal>
            </goals>
            <configuration>
              <jvmTarget>11</jvmTarget>
              <args>
                <arg>-Xopt-in=kotlin.RequiresOptIn</arg>
                <arg>-Xnew-inference</arg>
                <arg>-Xinline-classes</arg>
              </args>
            </configuration>
          </execution>
          <execution>
            <id>test-compile</id>
            <phase>test-compile</phase>
            <goals>
              <goal>test-compile</goal>
            </goals>
            <configuration>
              <jvmTarget>11</jvmTarget>
              <args>
                <arg>-Xopt-in=kotlin.RequiresOptIn</arg>
                <arg>-Xnew-inference</arg>
                <arg>-Xinline-classes</arg>
              </args>
            </configuration>
          </execution>
        </executions>
        <configuration>
          <jvmTarget>11</jvmTarget>
          <args>
            <arg>-Xopt-in=kotlin.RequiresOptIn</arg>
            <arg>-Xnew-inference</arg>
            <arg>-Xinline-classes</arg>
          </args>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.0.0-M4</version>
        <executions>
          <execution>
            <id>default-test</id>
            <phase>test</phase>
            <goals>
              <goal>test</goal>
            </goals>
            <configuration>
              <properties>
                <configurationParameters>junit.jupiter.conditions.deactivate = *
                            junit.jupiter.extensions.autodetection.enabled = true
                            junit.jupiter.testinstance.lifecycle.default = per_class
                            junit.jupiter.execution.parallel.enabled = true</configurationParameters>
              </properties>
            </configuration>
          </execution>
        </executions>
        <configuration>
          <properties>
            <configurationParameters>junit.jupiter.conditions.deactivate = *
                            junit.jupiter.extensions.autodetection.enabled = true
                            junit.jupiter.testinstance.lifecycle.default = per_class
                            junit.jupiter.execution.parallel.enabled = true</configurationParameters>
          </properties>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-source-plugin</artifactId>
        <executions>
          <execution>
            <id>attach-sources</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.1</version>
        <executions>
          <execution>
            <id>default-compile</id>
            <phase>compile</phase>
            <goals>
              <goal>compile</goal>
            </goals>
          </execution>
          <execution>
            <id>default-testCompile</id>
            <phase>test-compile</phase>
            <goals>
              <goal>testCompile</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.graalvm.nativeimage</groupId>
        <artifactId>native-image-maven-plugin</artifactId>
        <version>20.1.0</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>native-image</goal>
            </goals>
            <configuration>
              <skip>false</skip>
              <imageName>example</imageName>
              <buildArgs>-H:+ReportExceptionStackTraces
                        --no-fallback
                        --allow-incomplete-classpath
                        --verbose</buildArgs>
              <mainClass>kaggle.challenge.App</mainClass>
              <imageName>kaggle-m5</imageName>
            </configuration>
          </execution>
        </executions>
        <configuration>
          <skip>false</skip>
          <imageName>example</imageName>
          <buildArgs>-H:+ReportExceptionStackTraces
                        --no-fallback
                        --allow-incomplete-classpath
                        --verbose</buildArgs>
          <mainClass>kaggle.challenge.App</mainClass>
          <imageName>kaggle-m5</imageName>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-clean-plugin</artifactId>
        <version>2.5</version>
        <executions>
          <execution>
            <id>default-clean</id>
            <phase>clean</phase>
            <goals>
              <goal>clean</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-resources-plugin</artifactId>
        <version>2.6</version>
        <executions>
          <execution>
            <id>default-testResources</id>
            <phase>process-test-resources</phase>
            <goals>
              <goal>testResources</goal>
            </goals>
          </execution>
          <execution>
            <id>default-resources</id>
            <phase>process-resources</phase>
            <goals>
              <goal>resources</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-jar-plugin</artifactId>
        <version>2.4</version>
        <executions>
          <execution>
            <id>default-jar</id>
            <phase>package</phase>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-install-plugin</artifactId>
        <version>2.4</version>
        <executions>
          <execution>
            <id>default-install</id>
            <phase>install</phase>
            <goals>
              <goal>install</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-deploy-plugin</artifactId>
        <version>2.7</version>
        <executions>
          <execution>
            <id>default-deploy</id>
            <phase>deploy</phase>
            <goals>
              <goal>deploy</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-site-plugin</artifactId>
        <version>3.3</version>
        <executions>
          <execution>
            <id>default-site</id>
            <phase>site</phase>
            <goals>
              <goal>site</goal>
            </goals>
            <configuration>
              <outputDirectory>/home/jim/work/wm/target/site</outputDirectory>
              <reportPlugins>
                <reportPlugin>
                  <groupId>org.apache.maven.plugins</groupId>
                  <artifactId>maven-project-info-reports-plugin</artifactId>
                </reportPlugin>
              </reportPlugins>
            </configuration>
          </execution>
          <execution>
            <id>default-deploy</id>
            <phase>site-deploy</phase>
            <goals>
              <goal>deploy</goal>
            </goals>
            <configuration>
              <outputDirectory>/home/jim/work/wm/target/site</outputDirectory>
              <reportPlugins>
                <reportPlugin>
                  <groupId>org.apache.maven.plugins</groupId>
                  <artifactId>maven-project-info-reports-plugin</artifactId>
                </reportPlugin>
              </reportPlugins>
            </configuration>
          </execution>
        </executions>
        <configuration>
          <outputDirectory>/home/jim/work/wm/target/site</outputDirectory>
          <reportPlugins>
            <reportPlugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-project-info-reports-plugin</artifactId>
            </reportPlugin>
          </reportPlugins>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <reporting>
    <outputDirectory>/home/jim/work/wm/target/site</outputDirectory>
  </reporting>

  <profiles>
    <profile>
      <id>native-graalvm</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.graalvm.nativeimage</groupId>
            <artifactId>native-image-maven-plugin</artifactId>
            <version>20.1.0</version>
            <executions>
              <execution>
                <phase>package</phase>
                <goals>
                  <goal>native-image</goal>
                </goals>
              </execution>
            </executions>
            <configuration>
              <skip>false</skip>
              <imageName>example</imageName>
              <buildArgs>-H:+ReportExceptionStackTraces
                        --no-fallback
                        --allow-incomplete-classpath
                        --verbose</buildArgs>
              <mainClass>kaggle.challenge.App</mainClass>
              <imageName>kaggle-m5</imageName>
            </configuration>
          </plugin>
        </plugins>
      </build>
      <properties>
        <graalvm.version>20.1.0</graalvm.version>
      </properties>
      <dependencies>
        <dependency>
          <groupId>org.graalvm.sdk</groupId>
          <artifactId>graal-sdk</artifactId>
          <version>20.1.0</version>
          <scope>provided</scope>
        </dependency>
        <dependency>
          <groupId>columnar</groupId>
          <artifactId>lillypads</artifactId>
          <version>1.0.1-SNAPSHOT</version>
        </dependency>
      </dependencies>
    </profile>
  </profiles>
</project>
```

runtime native stacktrace

```

Exception in thread "main" java.time.DateTimeException: Unable to initialize HijrahCalendar: Hijrah-umalqura
       at java.time.chrono.HijrahChronology.loadCalendarData(HijrahChronology.java:912)
       at java.time.chrono.HijrahChronology.checkCalendarInit(HijrahChronology.java:315)
       at java.time.chrono.HijrahChronology.getHijrahDateInfo(HijrahChronology.java:581)
       at java.time.chrono.HijrahDate.<init>(HijrahDate.java:284)
       at java.time.chrono.HijrahDate.ofEpochDay(HijrahDate.java:166)
       at java.time.chrono.HijrahChronology.date(HijrahChronology.java:451)
       at java.time.chrono.HijrahChronology.date(HijrahChronology.java:195)
       at cursors.calendar.JvmCal.date(JvmCal.kt:47)
       at cursors.calendar.JvmCal.dateWiseCategories(JvmCal.kt:74)
       at cursors.calendar.JvmCal.inflate$default(JvmCal.kt:91)
       at kaggle.challenge.App$notebook$1.invoke(App.kt:115)
       at kaggle.challenge.App$notebook$1.invoke(App.kt:42)
       at kaggle.challenge.App$Companion.bootData(App.kt:204)
       at kaggle.challenge.App.notebook(App.kt:112)
       at kaggle.challenge.App$Companion.main(App.kt:210)
       at kaggle.challenge.App.main(App.kt)
Caused by: java.lang.RuntimeException: Hijrah calendar resource not found: /java/time/chrono/hijrah-config-islamic-umalqura.properties
       at java.time.chrono.HijrahChronology.readConfigProperties(HijrahChronology.java:822)
       at java.time.chrono.HijrahChronology.loadCalendarData(HijrahChronology.java:843)
 

```

**Comment by jnorthrup** [comment]
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8178823
