### ISSUE TITLE
[libgraal] NPE in compiler when using `--vm.Dgraal.Dump=Truffle:1`

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#2705]
All Graal compilation requests fail in [`20.2.0-dev-20200718_0205`](https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/20.2.0-dev-20200718_0205) when `--vm.Dgraal.Dump=Truffle:1` is passed in (see below). This is probably due to the new flag naming convention, but I'm not sure what the new name of the `Dump` flag is.

```
[engine] opt fail         String>>hash <split-17bd1c4d>                               |ASTSize            28
java.lang.RuntimeException:java.lang.Exception:
java.lang.RuntimeException: java.lang.IllegalStateException: Feature unsupported in version 6.1
	at org.graalvm.graphio.GraphOutput$Builder.requireVersion(GraphOutput.java:216)
	at org.graalvm.graphio.GraphOutput$Builder.attr(GraphOutput.java:303)
	at org.graalvm.compiler.debug.DebugContext.buildOutput(DebugContext.java:136)
	at org.graalvm.compiler.truffle.compiler.TruffleDebugContextImpl.buildOutput(TruffleDebugContextImpl.java:46)
	at org.graalvm.compiler.truffle.compiler.hotspot.libgraal.TruffleToLibGraalEntryPoints.getDumpChannel(TruffleToLibGraalEntryPoints.java:651)
	at org.graalvm.compiler.truffle.runtime.hotspot.libgraal.TruffleToLibGraalCalls.getDumpChannel(Native Method)
	at org.graalvm.compiler.truffle.runtime.hotspot.libgraal.IgvSupport.buildOutput(IgvSupport.java:71)
	at org.graalvm.compiler.truffle.runtime.TruffleTreeDumper.dumpASTAndCallTrees(TruffleTreeDumper.java:80)
	at org.graalvm.compiler.truffle.runtime.TruffleTreeDumper.dump(TruffleTreeDumper.java:70)
	at org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.maybeDumpTruffleTree(GraalTruffleRuntime.java:711)
	at org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.compileImpl(GraalTruffleRuntime.java:662)
	at org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.doCompile(GraalTruffleRuntime.java:643)
	at org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime$1.execute(GraalTruffleRuntime.java:741)
	at org.graalvm.compiler.truffle.runtime.BackgroundCompileQueue$RequestImpl.call(BackgroundCompileQueue.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
	at org.graalvm.compiler.truffle.runtime.BackgroundCompileQueue$TruffleCompilerThreadFactory$1.run(BackgroundCompileQueue.java:282)
	Suppressed: java.lang.NullPointerException
		at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.common.TruffleOutputGroup.close(TruffleOutputGroup.java:73)
		at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.compileImpl(GraalTruffleRuntime.java:659)
		at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.doCompile(GraalTruffleRuntime.java:643)
		at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime$1.execute(GraalTruffleRuntime.java:741)
		at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.BackgroundCompileQueue$RequestImpl.call(BackgroundCompileQueue.java:236)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base/java.lang.Thread.run(Thread.java:834)
		at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.BackgroundCompileQueue$TruffleCompilerThreadFactory$1.run(BackgroundCompileQueue.java:282)
```

**Comment by fniephaus** [comment]
https://github.com/oracle/graal/commit/65d14c56e793bfc0f6ea9349a9d6cf13c073c72a seems related. /cc @sdedic

**Comment by fniephaus** [comment]
The stack-trace shows that libgraal is involved, and when turning it off via `--vm.XX:-UseJVMCINativeLibrary`, things are working again.

**Comment by tzezula** [comment]
The exception is unrelated to the new engine options. The `vm.Dgraal.Dump` is a correct option.
Seems to be related to https://github.com/oracle/graal/commit/669886903114a0e809f8f94d73ca3719536f1ec3.

**Comment by tzezula** [comment]
Fixed by: https://github.com/oracle/graal/commit/c9b3900f4a21a882ba8e708240453eb4956410a1

**Comment by fniephaus** [comment]
Thanks for the fix, @tzezula!
