### ISSUE TITLE
java.xml resource refuses to be included in native-image

### ISSUE THREAD

**Issue by kristofdho** [oracle/graal#2719]
**Describe the issue**
Writing an xslx file, using the apache poi library fails at runtime. It worked in 20.1 when initializing almost all of the poi library at build time. Due to the recent switch to initialize jdk internals at runtime, I had to switch the poi library to also be initialized at runtime.
Now when I run the resulting executable, it complains about a missing `com.sun.org.apache.xml.internal.serializer.XMLEntities` resource which should be added by this snippet:

https://github.com/oracle/graal/blob/64a9c2444563eb63290ded6d14118d445db15427/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/xml/XMLParsersRegistration.java#L105-L126

which is run in the `JavaxXmlClassAndResourcesLoaderFeature`

https://github.com/oracle/graal/blob/64a9c2444563eb63290ded6d14118d445db15427/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/xml/JavaxXmlClassAndResourcesLoaderFeature.java#L53-L54

I have confirmed that the method is reachable so the resource registration should be executed.
I have also manually added the `com.sun.*.properties` pattern in a `resource-config.json` file to no avail.

Somehow the `XMLEntities.properties` file is not included in the native-image no matter what, and the reason it worked on 20.1 would be because the file was already read at build-time so no longer required at run-time.

**Describe GraalVM and your environment:**
 - GraalVM version: **CE 20.2.0-dev-20200718_0205**
 - JDK major version: **11**
 - OS: **Windows**
 - Architecture: **amd64**

**More details**

Stacktrace at runtime:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:291)
	at com.sun.org.apache.xml.internal.serializer.ToUnknownStream.<init>(ToUnknownStream.java:119)
	at com.sun.org.apache.xalan.internal.xsltc.runtime.output.TransletOutputHandlerFactory.getSerializationHandler(TransletOutputHandlerFactory.java:159)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.getOutputHandler(TransformerImpl.java:472)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:354)
	at org.apache.poi.openxml4j.opc.StreamHelper.saveXmlInStream(StreamHelper.java:82)
	at org.apache.poi.openxml4j.opc.internal.ZipContentTypeManager.saveImpl(ZipContentTypeManager.java:69)
	at org.apache.poi.openxml4j.opc.internal.ContentTypeManager.save(ContentTypeManager.java:452)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:524)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1505)
	at org.apache.poi.ooxml.POIXMLDocument.write(POIXMLDocument.java:242)
	at ...
Caused by: java.lang.RuntimeException: The resource [ com.sun.org.apache.xml.internal.serializer.XMLEntities ] could not load: java.lang.RuntimeException: The resource [ com.sun.org.apache.xml.internal.serializer.XMLEntities ] could not be found.
  
 com.sun.org.apache.xml.internal.serializer.XMLEntities 	 java.lang.RuntimeException: The resource [ com.sun.org.apache.xml.internal.serializer.XMLEntities ] could not be found.
 
	at com.sun.org.apache.xml.internal.serializer.CharInfo.<init>(CharInfo.java:304)
	at com.sun.org.apache.xml.internal.serializer.CharInfo.getCharInfoInternal(CharInfo.java:486)
	at com.sun.org.apache.xml.internal.serializer.ToXMLStream.<clinit>(ToXMLStream.java:59)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:351)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:271)
	... 23 more
```

**Comment by kristofdho** [comment]
I managed to work around this by adding `--initialize-at-build-time=com.sun.org.apache.xml.internal.serializer.ToXMLStream` which again loads in the file at build-time and avoid the need to include it in the image.
