### ISSUE TITLE
Method called from static initializer not @Substitute'd

### ISSUE THREAD

**Issue by gustavonalle** [oracle/graal#2721]
**Describe the issue**

The class [MMapDirectory.java](https://github.com/apache/lucene-solr/blob/d7beb0f1479d2a9c4f37d780aa31edcd1012ac69/lucene/core/src/java/org/apache/lucene/store/MMapDirectory.java#L325) from Apache Lucene has the following static initializer:

```java

static {
    final Object hack = AccessController.doPrivileged((PrivilegedAction<Object>) MMapDirectory::unmapHackImpl);
    // More stuff here ...
  }
```

A substitution was provided as:

```java
@TargetClass(MMapDirectory.class)
final class MMapDirectoryReplacementJDK {

    @Substitute
    private static Object unmapHackImpl() {
        // Just for testing purposes, return a simple obj
        return new Object();
    }

}
```

But the original method was still called during the native image generation:

```
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Invoke with MethodHandle argument could not be reduced to at most a single call or single field access. The method handle must be a compile time constant, e.g., be loaded from a `static final` field. Method that contains the method handle invocation: java.lang.invoke.MethodHandle.invokeBasic(Object)
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The error is then reported at run time when the invoke is executed.
Trace: 
        at parsing java.lang.invoke.LambdaForm$MH/0x00000007c1254840.invokeExact_MT(LambdaForm$MH)
Call path from entry point to java.lang.invoke.LambdaForm$MH/185227349.invokeExact_MT(Object, Object, Object): 
        at java.lang.invoke.LambdaForm$MH/0x00000007c1254840.invokeExact_MT(LambdaForm$MH)
        at org.apache.lucene.store.MMapDirectory.lambda$null$0(MMapDirectory.java:404)
        at org.apache.lucene.store.MMapDirectory$$Lambda$1164/0x00000007c1459840.run(Unknown Source)
        at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:83)
        at java.security.ProtectionDomain.mergePermissions(ProtectionDomain.java:488)
        at java.security.ProtectionDomain.toString(ProtectionDomain.java:425)
        at java.lang.String.valueOf(String.java:2951)
        at java.io.PrintStream.print(PrintStream.java:745)
        at java.io.PrintStream.println(PrintStream.java:882)
        at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:759)
```

The line ```MMapDirectory.java:404``` is only reached if the original method was called, not the replacement.

**Steps to reproduce the issue**

todo

**Describe GraalVM and your environment:**
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)
```
```Linux host 5.6.16-200.fc31.x86_64 #1 SMP Thu Jun 4 18:07:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by cstancu** [comment]
That doesn't seem to be a problem with the substitution but rather with the lamda form, i.e., the analysis doesn't even reach the substitution, it gets stuck in the method handle.

**Comment by gustavonalle** [comment]
Is there any workaround to have that method replaced?

**Comment by cstancu** [comment]
The underlying issue here is incomplete `MethodHandle` support. That is under development and is being tracked by https://github.com/oracle/graal/issues/2761.
