### ISSUE TITLE
Getting java.lang.UnsatisfiedLinkError: jdk.internal.loader.BootLoader.getSystemPackageNames()

### ISSUE THREAD

**Issue by zcaudate** [oracle/graal#2724]
I'm looking to get [Jep](https://github.com/ninia/jep/issues/271) working with GraalVm and got quite far before getting this error. I've attached the reflect-config and jni-config with this issue. 

[reflect-config.txt](https://github.com/oracle/graal/files/5003722/reflect-config.txt)
[jni-config.txt](https://github.com/oracle/graal/files/5003721/jni-config.txt)

All the classes dependencies are there but I'm now stuck on a really cryptic error. Any help would be great.

```
java.lang.UnsatisfiedLinkError: jdk.internal.loader.BootLoader.getSystemPackageNames()[Ljava/lang/String; [symbol: Java_jdk_internal_loader_BootLoader_getSystemPackageNames or Java_jdk_internal_loader_BootLoader_getSystemPackageNames__]
        at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
        at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
        at jdk.internal.loader.BootLoader.getSystemPackageNames(BootLoader.java)
        at jdk.internal.loader.BootLoader.packages(BootLoader.java:192)
        at java.lang.ClassLoader.getPackages(ClassLoader.java:2354)
        at java.lang.Package.getPackages(Package.java:377)
        at jep.ClassList.loadPackages(ClassList.java:170)
        at jep.ClassList.<init>(ClassList.java:68)
        at jep.ClassList.getInstance(ClassList.java:366)
        at jep.Jep.setupJavaImportHook(Jep.java:320)
        at jep.Jep.configureInterpreter(Jep.java:310)
        at jep.SharedInterpreter.configureInterpreter(SharedInterpreter.java:64)
        at jep.Jep.<init>(Jep.java:282)
        at jep.SharedInterpreter.<init>(SharedInterpreter.java:56)
```

**Comment by zcaudate** [comment]
It compiles fine, but when I run the compiled program, it gives me the error. I'm using 

```
OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)
```

**Comment by zcaudate** [comment]
I've put together a sample repo demonstrating the issue:

https://github.com/zcaudate/sample-jep-graal

**Comment by zapster** [comment]
The issue has been fixed in b0bce9e.

**Comment by zcaudate** [comment]
@zapster thanks! Can you briefly explain (if possible) what the issue was and which version of graal I should use to run the sample project?

**Comment by zapster** [comment]
@zcaudate sure!

> Can you briefly explain (if possible) what the issue was

JDK 9 introduced `jdk.internal.loader.BootLoader.packages()` to retrieve all packages loaded by the boot class loader. Internally, that function calls the native function `jdk.internal.loader.BootLoader.getSystemPackageNames()` which does not exist in native images. Thus, the error message you reported. The change adds support for `BootLoader.packages()` (see https://github.com/oracle/graal/commit/b0bce9e6c866302e662ba243beca87ea9e76db9e#diff-422e3fa386126a69506423650c878a251e18cc6e6cfdb39d87923a88a97628a3).

> which version of graal I should use to run the sample project?

The fix will be included in the next mainline release which will be 21.2.

**Comment by zcaudate** [comment]
oh awesome. thanks!
