### ISSUE TITLE
Using Java AWT Fonts gives unsatisfiedlinkerror while running native image

### ISSUE THREAD

**Issue by Mahaswami** [oracle/graal#2729]
**Describe the issue**

Trying to get AWT fonts working in native mode.  Below is the code. It uses java.awt and simply prints the available font family names.

```
public class MainClass {
    public static void main(String[] args) {
        String fonts[] = GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();
         for ( int i = 0; i < fonts.length; i++ ) {
             System.out.println(fonts[i]);
         }
    }
}
```
Running the native image gives the following error.

```
Exception in thread "main" java.lang.InternalError: java.lang.reflect.InvocationTargetException
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:86)
	at java.security.AccessController.doPrivileged(AccessController.java:83)
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at sun.java2d.SunGraphicsEnvironment.getFontManagerForSGE(SunGraphicsEnvironment.java:189)
	at sun.java2d.SunGraphicsEnvironment.getAvailableFontFamilyNames(SunGraphicsEnvironment.java:223)
	at sun.java2d.SunGraphicsEnvironment.getAvailableFontFamilyNames(SunGraphicsEnvironment.java:251)
	at sun.java2d.HeadlessGraphicsEnvironment.getAvailableFontFamilyNames(HeadlessGraphicsEnvironment.java:75)
	at com.mahaswami.nativeimage.MainClass.main(MainClass.java:8)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:84)
	... 7 more
Caused by: java.lang.UnsatisfiedLinkError: sun.font.FontConfigManager.getFontConfigVersion()I [symbol: Java_sun_font_FontConfigManager_getFontConfigVersion or Java_sun_font_FontConfigManager_getFontConfigVersion__]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
	at sun.font.FontConfigManager.getFontConfigVersion(FontConfigManager.java)
	at sun.font.FcFontConfiguration.readFcInfo(FcFontConfiguration.java:455)
	at sun.font.FcFontConfiguration.init(FcFontConfiguration.java:94)
	at sun.font.FcFontConfiguration.<init>(FcFontConfiguration.java:76)
	at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:713)
	at sun.font.SunFontManager$2.run(SunFontManager.java:367)
	at java.security.AccessController.doPrivileged(AccessController.java:83)
	at sun.font.SunFontManager.<init>(SunFontManager.java:312)
	at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at sun.awt.X11FontManager.<init>(X11FontManager.java:56)
	... 9 more
```

Since FontConfigManager.getFontConfigVersion() uses libfontconfig, tried to load the libfontconfig.so at runtime but it did not help.

**Steps to reproduce the issue**

The reproducer project is available at 
https://github.com/MahaswamiSoftware/awtfont-native-image

**Describe GraalVM and your environment:**
 - GraalVM version : **[CE 20.1.0]**
 - JDK major version: **[11]**
 - OS: **[linux mint]**
 - Architecture: **[AMD64]**

**More details**
Contents of jni config file 

```
[
{
  "name":"java.lang.ClassLoader",
  "methods":[
    {"name":"getPlatformClassLoader","parameterTypes":[] }, 
    {"name":"loadClass","parameterTypes":["java.lang.String"] }
  ]
},
{
  "name":"java.lang.ClassNotFoundException"
},
{
  "name":"java.lang.NoSuchMethodError"
},
  {
    "name": "sun.font.FontConfigManager",
    "methods": [
      {"name": "getFontConfigVersion","parameterTypes":[]}
    ]
  }
]
```
Contents of reflection config file
```
[
  {
    "name": "sun.awt.X11FontManager",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredFields" : true,
    "allPublicFields" : true
  },
  {
    "name": "sun.font.FontConfigManager",
    "methods": [
      {"name": "getFontConfigVersion","parameterTypes":[]}
    ]
  }
]
```

**Comment by peter-hofer** [comment]
Thank you for your report @Mahaswami . We currently do not support AWT or Swing code, but some improvements have recently been made. It might be possible to get it to work, but you will have to load the AWT library (and possibly others) in your code. Perhaps the comments in this issue are of use: https://github.com/oracle/graal/issues/1327

**Comment by Mahaswami** [comment]
@peter-hofer thank you for reverting. We are not trying to use native image for typical AWT or Swing purposes of running a GUI client. A very important use case for web server applications is report generation. In our case we are trying to use JasperReport ( a very popular open source reporting engine) to generate reports inside the native image. We have for the moment isolated the problem down to the code inside JasperReport which is using Fonts for report generation. 

The #1327 seems connected some thread issues in AWT desktop GUI and may not be directly relevant to this issue. At the outset, it appears that we may need some pointers connected to the JNI library loading (which doesn't seem to carry some of the files related to fonts config/loading etc).

Given the importance of this report generation use case, appreciate if you can give a bit more concrete points for us to try to take this forward even if this is a tedious configuration process involved. You may also see our separate report with a full reproducer using jasperreports in #2696

**Comment by peter-hofer** [comment]
Indeed issue #1327 itself is not directly related to your troubles, but some of the comments there discuss important steps such as loading `libawt.so` or `libawt_headless.so` which are relevant for your use case. In particular, @vektory79 managed to get PlantUML running on native-image: https://github.com/vektory79/plantuml-native-image

**Comment by Mahaswami** [comment]
@peter-hofer Thank you. Will checkout the planetUML stuff and revert.

**Comment by pquiring** [comment]
You need to copy ``${java.home}\lib\*font*`` to ``.\lib`` in app folder which is where Java looks for font config files.

**Comment by chirontt** [comment]
Seems significant improvements in AWT/Swing support have occurred since the OP reported this issue in the 20.1 version. In GraalVM 22.0.0.2 version, the sample code above works fine for me.

To test it, I've forked the OP's reproducer project, and updated extensively its pom.xml so that Maven alone can be used to build the native image. The fork is [here](https://github.com/chirontt/awtfont-native-image).

To produce the native image:
```
mvn compile exec:exec package
```
(the `exec:exec` goal is important, as it generates the native image config files using the agent)

Then to run the generated native image, e.g. in Linux:
```
./target/native-image/awtfont-native-image
```
or in Windows:
```
target\native-image\awtfont-native-image.exe -Djava.home="%JAVA_HOME%"
```

**Comment by ctoabidmaqbool** [comment]
> Seems significant improvements in AWT/Swing support have occurred since the OP reported this issue in the 20.1 version. In GraalVM 22.0.0.2 version, the sample code above works fine for me.
> 
> To test it, I've forked the OP's reproducer project, and updated extensively its pom.xml so that Maven alone can be used to build the native image. The fork is [here](https://github.com/chirontt/awtfont-native-image).
> 
> To produce the native image:
> 
> ```
> mvn compile exec:exec package
> ```
> 
> (the `exec:exec` goal is important, as it generates the native image config files using the agent)
> 
> Then to run the generated native image, e.g. in Linux:
> 
> ```
> ./target/native-image/awtfont-native-image
> ```
> 
> or in Windows:
> 
> ```
> target\native-image\awtfont-native-image.exe -Djava.home="%JAVA_HOME%"
> ```

 I have tried v. latest graalvm dev build, but sill there are issue!
 

![image](https://github.com/user-attachments/assets/cc40fc4b-4755-4592-bce8-4df4c60bb206)

```
D:\GraalVM-Projects\awtfont-native-image-fork>target\native-image\awtfont-native-image.exe -Djava.home="%JAVA_HOME%"
Exception in thread "main" java.lang.UnsatisfiedLinkError: sun.awt.PlatformGraphicsInfo.hasDisplays0()Z [symbol: Java_sun_awt_PlatformGraphicsInfo_hasDisplays0 or Java_sun_awt_PlatformGraphicsInfo_hasDisplays0__]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:152)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:41)
        at java.desktop@24/sun.awt.PlatformGraphicsInfo.hasDisplays0(Native Method)
        at java.desktop@24/sun.awt.PlatformGraphicsInfo.<clinit>(PlatformGraphicsInfo.java:39)
        at java.desktop@24/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:91)
        at java.desktop@24/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:82)
        at java.desktop@24/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:104)
        at com.mahaswami.nativeimage.MainClass.main(MainClass.java:8)
        at java.base@24/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```

**Comment by chirontt** [comment]
I've tried my [fork](https://github.com/chirontt/awtfont-native-image) using the following GraalVM CE release versions: [graalvm-community-openjdk-17.0.9](https://github.com/graalvm/graalvm-ce-builds/releases/tag/jdk-17.0.9), [graalvm-community-openjdk-21.0.2](https://github.com/graalvm/graalvm-ce-builds/releases/tag/jdk-21.0.2) and [graalvm-community-openjdk-22.0.2](https://github.com/graalvm/graalvm-ce-builds/releases/tag/jdk-22.0.2) - they all work fine for me. I don't bother with the dev builds.
