### ISSUE TITLE
Occasional deadlock in native-image

### ISSUE THREAD

**Issue by zfernandez88** [oracle/graal#2732]
Occasionally when running native-image, we encounter a deadlock. Unfortunately, we do not have a reproducible case. However, we have captured a thread dump (included at the bottom of this report). 

- GraalVM version: 20.1.0
- JDK Major Version: 8
- OS: RHEL
- Architecture: AMD64

```
2020-06-02 10:08:35
Full thread dump OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (25.252-b09-jvmci-20.1-b02 mixed mode):

"Attach Listener" #19 daemon prio=9 os_prio=0 tid=0x00002acdf8001000 nid=0x15aa waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"native-image pid watcher" #18 prio=5 os_prio=0 tid=0x00002acd6443f800 nid=0x1402 waiting for monitor entry [0x00002acdb67fa000]
   java.lang.Thread.State: BLOCKED (on object monitor)
                at sun.misc.URLClassPath.getLookupCache(URLClassPath.java:406)
                - waiting to lock <0x00000006955e39a8> (a sun.misc.URLClassPath)
                at sun.misc.URLClassPath.getResource(URLClassPath.java:247)
                at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
                at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
                at java.security.AccessController.doPrivileged(Native Method)
                at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
                - locked <0x0000000697eb5868> (a java.lang.Object)
                at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
                at org.objectweb.asm.MethodWriter.visitFrame(MethodWriter.java:844)
                at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1834)
                at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1283)
                at org.objectweb.asm.ClassReader.accept(ClassReader.java:688)
                at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
                at com.oracle.svm.hosted.agent.NativeImageBytecodeInstrumentationAgent.applyRewriteLambdasTransformation(NativeImageBytecodeInstrumentationAgent.java:69)
                at com.oracle.svm.hosted.agent.NativeImageBytecodeInstrumentationAgent$$Lambda$1/1078694789.apply(Unknown Source)
                at com.oracle.svm.util.AgentSupport$1.transform(AgentSupport.java:36)
                at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
                at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
                at java.lang.ClassLoader.findBootstrapClass(Native Method)
                at java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1008)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:407)
                - locked <0x0000000697e897b0> (a java.lang.Object)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:405)
                - locked <0x0000000697e89730> (a java.lang.Object)
                at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
                at com.oracle.svm.hosted.NativeImageGeneratorRunner$1.run(NativeImageGeneratorRunner.java:100)
                at java.util.TimerThread.mainLoop(Timer.java:555)
                at java.util.TimerThread.run(Timer.java:505)

"Service Thread" #17 daemon prio=9 os_prio=0 tid=0x00002acd643b8000 nid=0x13d1 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread11" #16 daemon prio=9 os_prio=0 tid=0x00002acd643b5800 nid=0x13d0 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread10" #15 daemon prio=9 os_prio=0 tid=0x00002acd643b3800 nid=0x13cf waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread9" #14 daemon prio=9 os_prio=0 tid=0x00002acd643b1800 nid=0x13ce waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread8" #13 daemon prio=9 os_prio=0 tid=0x00002acd643af800 nid=0x13cd waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"JVMCI-native CompilerThread7" #12 daemon prio=9 os_prio=0 tid=0x00002acd643ad800 nid=0x13cc runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"JVMCI-native CompilerThread6" #11 daemon prio=9 os_prio=0 tid=0x00002acd643ab800 nid=0x13cb runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"JVMCI-native CompilerThread5" #10 daemon prio=9 os_prio=0 tid=0x00002acd643a9800 nid=0x13ca runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"JVMCI-native CompilerThread4" #9 daemon prio=9 os_prio=0 tid=0x00002acd643a7800 nid=0x13c9 waiting for monitor entry [0x00002acdc53ff000]
   java.lang.Thread.State: BLOCKED (on object monitor)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:398)
                - waiting to lock <0x0000000697eb5868> (a java.lang.Object)
                at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
                at org.objectweb.asm.ClassReader.computeImplicitFrame(ClassReader.java:2985)
                at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1760)
                at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1283)
                at org.objectweb.asm.ClassReader.accept(ClassReader.java:688)
                at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
                at com.oracle.svm.hosted.agent.NativeImageBytecodeInstrumentationAgent.applyRewriteLambdasTransformation(NativeImageBytecodeInstrumentationAgent.java:69)
                at com.oracle.svm.hosted.agent.NativeImageBytecodeInstrumentationAgent$$Lambda$1/1078694789.apply(Unknown Source)
                at com.oracle.svm.util.AgentSupport$1.transform(AgentSupport.java:36)
                at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
                at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
                at java.util.jar.JarFile.getManifestFromReference(JarFile.java:195)
                at java.util.jar.JarFile.getManifest(JarFile.java:180)
                at sun.misc.URLClassPath$JarLoader.getClassPath(URLClassPath.java:1199)
                at sun.misc.URLClassPath.getLoader(URLClassPath.java:532)
                - locked <0x00000006955e39a8> (a sun.misc.URLClassPath)
                at sun.misc.URLClassPath.getNextLoader(URLClassPath.java:494)
                - locked <0x00000006955e39a8> (a sun.misc.URLClassPath)
                at sun.misc.URLClassPath.getResource(URLClassPath.java:248)
                at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
                at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
                at java.security.AccessController.doPrivileged(Native Method)
                at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
                - locked <0x0000000696cae240> (a java.lang.Object)
                at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
                at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at com.oracle.svm.hosted.NativeImageSystemClassLoader.loadClass(NativeImageSystemClassLoader.java:87)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:351)

"JVMCI-native CompilerThread3" #8 daemon prio=9 os_prio=0 tid=0x00002acd643a5800 nid=0x13c5 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"JVMCI-native CompilerThread2" #7 daemon prio=9 os_prio=0 tid=0x00002acd643a3000 nid=0x13be runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"JVMCI-native CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00002acd643a1000 nid=0x13bc runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"JVMCI-native CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00002acd6439f000 nid=0x13bb runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00002acd64353000 nid=0x13ad runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00002acd64289000 nid=0x13a0 in Object.wait() [0x00002acde9400000]
   java.lang.Thread.State: WAITING (on object monitor)
                at java.lang.Object.wait(Native Method)
                - waiting on <0x0000000695588f80> (a java.lang.ref.ReferenceQueue$Lock)
                at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
                - locked <0x0000000695588f80> (a java.lang.ref.ReferenceQueue$Lock)
                at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
                at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00002acd64284800 nid=0x139e in Object.wait() [0x00002acde89ff000]
   java.lang.Thread.State: WAITING (on object monitor)
                at java.lang.Object.wait(Native Method)
                - waiting on <0x0000000695586ca0> (a java.lang.ref.Reference$Lock)
                at java.lang.Object.wait(Object.java:502)
                at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
                - locked <0x0000000695586ca0> (a java.lang.ref.Reference$Lock)
                at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" #1 prio=5 os_prio=0 tid=0x00002acd64010000 nid=0x138a waiting for monitor entry [0x00002acd63b33000]
   java.lang.Thread.State: BLOCKED (on object monitor)
                at sun.misc.URLClassPath.knownToNotExist(URLClassPath.java:378)
                - waiting to lock <0x00000006955e39a8> (a sun.misc.URLClassPath)
                at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:336)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
                at com.oracle.svm.hosted.NativeImageGeneratorRunner.verifyClassPathAndConvertToURLs(NativeImageGeneratorRunner.java:202)
                at com.oracle.svm.hosted.NativeImageGeneratorRunner.installNativeImageClassLoader(NativeImageGeneratorRunner.java:159)
                at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:116)

"VM Thread" os_prio=0 tid=0x00002acd6427d000 nid=0x139c runnable 

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00002acd64027800 nid=0x138c runnable 

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00002acd64029800 nid=0x138d runnable 

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x00002acd6402b800 nid=0x138f runnable 

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x00002acd6402d000 nid=0x1390 runnable 

"GC task thread#4 (ParallelGC)" os_prio=0 tid=0x00002acd6402f000 nid=0x1391 runnable 

"GC task thread#5 (ParallelGC)" os_prio=0 tid=0x00002acd64030800 nid=0x1392 runnable 

"GC task thread#6 (ParallelGC)" os_prio=0 tid=0x00002acd64032800 nid=0x1393 runnable 

"GC task thread#7 (ParallelGC)" os_prio=0 tid=0x00002acd64034800 nid=0x1394 runnable 

"GC task thread#8 (ParallelGC)" os_prio=0 tid=0x00002acd64036000 nid=0x1395 runnable 

"GC task thread#9 (ParallelGC)" os_prio=0 tid=0x00002acd64038000 nid=0x1396 runnable 

"GC task thread#10 (ParallelGC)" os_prio=0 tid=0x00002acd6403a000 nid=0x1397 runnable 

"GC task thread#11 (ParallelGC)" os_prio=0 tid=0x00002acd6403b800 nid=0x1398 runnable 

"GC task thread#12 (ParallelGC)" os_prio=0 tid=0x00002acd6403d800 nid=0x1399 runnable 

"VM Periodic Task Thread" os_prio=0 tid=0x00002acd643ba800 nid=0x13d2 waiting on condition 

JNI global references: 325


Found one Java-level deadlock:
=============================
"native-image pid watcher":
  waiting to lock monitor 0x00002acdcc005138 (object 0x00000006955e39a8, a sun.misc.URLClassPath),
  which is held by "JVMCI-native CompilerThread4"
"JVMCI-native CompilerThread4":
  waiting to lock monitor 0x00002acdf40062c8 (object 0x0000000697eb5868, a java.lang.Object),
  which is held by "native-image pid watcher"

Java stack information for the threads listed above:
===================================================
"native-image pid watcher":
                at sun.misc.URLClassPath.getLookupCache(URLClassPath.java:406)
                - waiting to lock <0x00000006955e39a8> (a sun.misc.URLClassPath)
                at sun.misc.URLClassPath.getResource(URLClassPath.java:247)
                at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
                at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
                at java.security.AccessController.doPrivileged(Native Method)
                at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
                - locked <0x0000000697eb5868> (a java.lang.Object)
                at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
                at org.objectweb.asm.MethodWriter.visitFrame(MethodWriter.java:844)
                at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1834)
                at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1283)
                at org.objectweb.asm.ClassReader.accept(ClassReader.java:688)
                at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
                at com.oracle.svm.hosted.agent.NativeImageBytecodeInstrumentationAgent.applyRewriteLambdasTransformation(NativeImageBytecodeInstrumentationAgent.java:69)
                at com.oracle.svm.hosted.agent.NativeImageBytecodeInstrumentationAgent$$Lambda$1/1078694789.apply(Unknown Source)
                at com.oracle.svm.util.AgentSupport$1.transform(AgentSupport.java:36)
                at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
                at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
                at java.lang.ClassLoader.findBootstrapClass(Native Method)
                at java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1008)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:407)
                - locked <0x0000000697e897b0> (a java.lang.Object)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:405)
                - locked <0x0000000697e89730> (a java.lang.Object)
                at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
                at com.oracle.svm.hosted.NativeImageGeneratorRunner$1.run(NativeImageGeneratorRunner.java:100)
                at java.util.TimerThread.mainLoop(Timer.java:555)
                at java.util.TimerThread.run(Timer.java:505)
"JVMCI-native CompilerThread4":
                at java.lang.ClassLoader.loadClass(ClassLoader.java:398)
                - waiting to lock <0x0000000697eb5868> (a java.lang.Object)
                at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
                at org.objectweb.asm.ClassReader.computeImplicitFrame(ClassReader.java:2985)
                at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1760)
                at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1283)
                at org.objectweb.asm.ClassReader.accept(ClassReader.java:688)
                at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
                at com.oracle.svm.hosted.agent.NativeImageBytecodeInstrumentationAgent.applyRewriteLambdasTransformation(NativeImageBytecodeInstrumentationAgent.java:69)
                at com.oracle.svm.hosted.agent.NativeImageBytecodeInstrumentationAgent$$Lambda$1/1078694789.apply(Unknown Source)
                at com.oracle.svm.util.AgentSupport$1.transform(AgentSupport.java:36)
                at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
                at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
                at java.util.jar.JarFile.getManifestFromReference(JarFile.java:195)
                at java.util.jar.JarFile.getManifest(JarFile.java:180)
                at sun.misc.URLClassPath$JarLoader.getClassPath(URLClassPath.java:1199)
                at sun.misc.URLClassPath.getLoader(URLClassPath.java:532)
                - locked <0x00000006955e39a8> (a sun.misc.URLClassPath)
                at sun.misc.URLClassPath.getNextLoader(URLClassPath.java:494)
                - locked <0x00000006955e39a8> (a sun.misc.URLClassPath)
                at sun.misc.URLClassPath.getResource(URLClassPath.java:248)
                at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
                at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
                at java.security.AccessController.doPrivileged(Native Method)
                at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
                - locked <0x0000000696cae240> (a java.lang.Object)
                at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
                at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at com.oracle.svm.hosted.NativeImageSystemClassLoader.loadClass(NativeImageSystemClassLoader.java:87)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:351)

Found 1 deadlock.
```

**Comment by dougxc** [comment]
This is a symptom of libgraal doing class loading which it really should not need to. This issue will be resolved by work @tkrodriguez is currently undertaking.

**Comment by vjovanov** [comment]
This issue has been fixed.
