### ISSUE TITLE
Unable to create native image NullPointerException

### ISSUE THREAD

**Issue by sendev1** [oracle/graal#2734]
**Describe the issue**
Hello,

I upgraded app to spring boot 2.3.1 and I am using spring-graalvm-native 0.7.1. The project has so many dependencies. When I tried to create native image I got this error.

```
analysis: 2,106,404.76 ms, 14.22 GB
Fatal error:java.lang.NullPointerException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:463)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:359)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:518)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:117)
Caused by: java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
        at com.oracle.svm.hosted.ClassValueFeature.duringAnalysis(ClassValueFeature.java:74)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:720)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:720)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:538)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1

```
**Steps to reproduce the issue**
Please include both build steps as well as run steps
native-image -J-Xmx16G -J-Xms12G^
        --no-server ^
        --no-fallback ^
        --initialize-at-run-time=ch.qos.logback.classic.util.ContextInitializer.autoConfig ^
        --initialize-at-run-time=org.springframework.boot.logging.logback.ColorConverter ^
        -H:Name=%ARTIFACT%-agent ^
        -H:+TraceClassInitialization ^
        -H:+ReportExceptionStackTraces ^
        -H:+PrintAnalysisCallTree ^
        -H:+RemoveSaturatedTypeFlows ^
        -Dspring.native.verbose=true ^
        -Dspring.native.remove-yaml-support=true ^
        -Dspring.xml.ignore=true ^
        -Dspring.spel.ignore=true ^
        -Dspring.native.remove-jmx-support=true ^
        -Dspring.native.verify=true ^
        -cp %CP% %MAINCLASS%

**Describe GraalVM and your environment:**
 - GraalVM version 20.1.0
 - JDK major version:  8
 - OS:  Windows 10
 - Architecture: Intel

**More details**
Look like there was similar error happened in the past GraalVM `19.3.0` but I am not using security services. Just trying to create native image. How can I enable tracing in GraalVM to get more information because the given error is not sufficient to find the cause. In the issue 1883 it was mentioned that` "I added traces to the GraalVM source code and recompiled it."` but i am not sure now to do that. Any help would be appreciated.
https://github.com/oracle/graal/issues/1883

**Comment by sendev1** [comment]
@gwenneg looks like you would able to help me. Kindly take a look at this issue

**Comment by sendev1** [comment]
@jaikiran I hope you can help me here.

**Comment by sendev1** [comment]
I am not sure how to get debug log for graal vm so I connected my intellij to debug the running graal vm and I see that this is causing the NullPointerException. Any help would be appreciated


![image](https://user-images.githubusercontent.com/68568448/89467809-e5ffa480-d73b-11ea-9a7e-73f7fa1f3fcf.png)

**Comment by jaikiran** [comment]
Hello @sendev1, I think this should be fixed by this PR https://github.com/oracle/graal/pull/2728 that has been raised recently.

**Comment by sendev1** [comment]
@jaikiran Thank you. Could you please advise me which release this fix would be added? This is blocking my work. So, can I do any workaround to move forward?

**Comment by jaikiran** [comment]
Hello @sendev1, I am just a contributor to this project. I don't know which version of Graal VM this fix will be included in. You will probably have to keep a watch on that PR and see when it gets merged.

**Comment by thomaswue** [comment]
The PR with the fix is still open. I will let @christianwimmer comment when it is planned to be merged.

**Comment by sendev1** [comment]
@christianwimmer Thanks for the reply. This issue is blocking native image build process that we are trying to do for one of the spring boot project. The project management team wants to know when this fix will be available for us to move forward. Could you please advise when this fix will be available? Approximate time frame would be helpful.

 Also please advise if there is anyway for us to move forward instead of waiting for 20.3? Right now we are using 20.1.0

**Comment by christianwimmer** [comment]
Fixed in https://github.com/oracle/graal/commit/8f460607824ec13d05c9a15b9259565b36a4ff30
