### ISSUE TITLE
Dumping IGV graphs on EE fails with a ClassCastException

### ISSUE THREAD

**Issue by zfernandez88** [oracle/graal#2739]
**Describe the issue**

When running under SubstrateVM with the VM option -Dgraal.Dump=Truffle:1, compilation fails with a class cast exception. Potentially related to compilation in isolates; if I disable that (via -H:-SupportCompileInIsolates), I can dump compilation graphs again.

**Describe GraalVM and your environment:**
 - GraalVM version: EE 20.1.0
 - JDK major version: 8
 - OS: RHEL
 - Architecture: AMD64]

```
[thread:1] scope: main
  [thread:1] scope: main.Truffle
  Context: Truffle<Isolated:_BufferRetClosureRootNode@11593cb3()>
    [thread:1] scope: main.Truffle.CreateGraph
    Context: StructuredGraph:598830{Isolated: BufferRetClosureRootNode@11593cb3, TypedEntryMethod<BufferRetClosureRootNode@11593cb3_unspecialized>}
      [thread:1] scope: main.Truffle.CreateGraph.PEGraphDecode
      Context: StructuredGraph:598830{Isolated: BufferRetClosureRootNode@11593cb3, TypedEntryMethod<BufferRetClosureRootNode@11593cb3_unspecialized>}
      Exception raised in scope main.Truffle.CreateGraph.PEGraphDecode: java.lang.ClassCastException: com.oracle.svm.core.meta.DirectSubstrateObjectCons
tant cannot be cast to com.oracle.svm.enterprise.graal.isolated.z
        at com.oracle.svm.enterprise.truffle.isolated.l.getPosition(stripped:49)
        at org.graalvm.compiler.truffle.compiler.PartialEvaluator$TruffleSourceLanguagePositionProvider.getPosition(PartialEvaluator.java:452)
        at org.graalvm.compiler.replacements.PEGraphDecoder$PEMethodScope.resolveSourceLanguagePosition(PEGraphDecoder.java:247)
        at org.graalvm.compiler.replacements.PEGraphDecoder$PEMethodScope.getCallerBytecodePosition(PEGraphDecoder.java:234)
        at org.graalvm.compiler.nodes.GraphDecoder$MethodScope.getCallerBytecodePosition(GraphDecoder.java:154)
        at org.graalvm.compiler.replacements.PEGraphDecoder$PEAppendGraphBuilderContext.withNodeSoucePosition(PEGraphDecoder.java:514)
        at org.graalvm.compiler.replacements.PEGraphDecoder$PEAppendGraphBuilderContext.append(PEGraphDecoder.java:503)
        at org.graalvm.compiler.nodes.graphbuilderconf.GraphBuilderContext.nullCheckedValue(GraphBuilderContext.java:297)
        at org.graalvm.compiler.nodes.graphbuilderconf.GraphBuilderContext.nullCheckedValue(GraphBuilderContext.java:279)
        at org.graalvm.compiler.replacements.PEGraphDecoder.doInline(PEGraphDecoder.java:963)
        at org.graalvm.compiler.replacements.PEGraphDecoder.tryInline(PEGraphDecoder.java:912)
        at org.graalvm.compiler.replacements.PEGraphDecoder.trySimplifyInvoke(PEGraphDecoder.java:782)
        at org.graalvm.compiler.replacements.PEGraphDecoder.handleInvoke(PEGraphDecoder.java:756)
        at org.graalvm.compiler.nodes.GraphDecoder.processNextNode(GraphDecoder.java:758)
        at org.graalvm.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:509)
        at org.graalvm.compiler.replacements.PEGraphDecoder.decode(PEGraphDecoder.java:661)
        at org.graalvm.compiler.truffle.compiler.PartialEvaluator.doGraphPE(PartialEvaluator.java:528)
        at com.oracle.svm.truffle.api.SubstratePartialEvaluator.doGraphPE(SubstratePartialEvaluator.java:80)
        at org.graalvm.compiler.truffle.compiler.PartialEvaluator.inliningGraphPE(PartialEvaluator.java:571)
        at org.graalvm.compiler.truffle.compiler.PartialEvaluator.evaluate(PartialEvaluator.java:319)
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compileAST(TruffleCompilerImpl.java:458)
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:652)
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:589)
        at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:179)
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.actuallyCompile(TruffleCompilerImpl.java:297)
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.doCompile(TruffleCompilerImpl.java:263)
        at com.oracle.svm.enterprise.truffle.isolated.b.doCompile0(stripped:199)

      Context obj StructuredGraph:598830{Isolated: BufferRetClosureRootNode@11593cb3, TypedEntryMethod<BufferRetClosureRootNode@11593cb3_unspecialized>}
      Context obj Truffle<Isolated:_BufferRetClosureRootNode@11593cb3()>
```

**Comment by peter-hofer** [comment]
Thank you for your report @zfernandez88 , I'm looking into this issue.

**Comment by peter-hofer** [comment]
As a workaround, you can specify `-R:-CompileInIsolates`.

**Comment by peter-hofer** [comment]
Resolved, thanks again for the report.
