### ISSUE TITLE
20.2-dev and 20.3-dev is throwing Error: Already registered: java.lang.management.ManagementFactory.getPlatformMBeanServer()

### ISSUE THREAD

**Issue by sendev1** [oracle/graal#2750]
**Describe the issue**
I tried all dev release build (20.3 and 20.2) and for all of them I am seeing same error

```
Error: Already registered: java.lang.management.ManagementFactory.getPlatformMBeanServer()
com.oracle.svm.core.util.UserError$UserException: Already registered: java.lang.management.ManagementFactory.getPlatformMBeanServer()
        at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
        at com.oracle.svm.core.util.UserError.guarantee(UserError.java:92)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.register(AnnotationSubstitutionProcessor.java:724)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleMethodInAliasClass(AnnotationSubstitutionProcessor.java:338)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:302)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:274)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:230)
        at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:915)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:852)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:553)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:163)
Error: Image build request failed with exit status 1
```
**Steps to reproduce the issue**
Downloaded the artifacts from Graal release gthub page and all the 20.2-dev and 20.3-dev windows builds are causing this error when i try native-image command.

**Describe GraalVM and your environment:**
 - GraalVM version 20.2-dev, 20.3-dev
 - JDK major version: 8
 - OS: Windows 10
 - Architecture: Intel

**Comment by peter-hofer** [comment]
Thank you for your report @sendev1 . Just to make sure, do you have the JAR files of GraalVM (and specifically, native-image) specified on the class path more than once?

**Comment by sendev1** [comment]
@peter-hofer Thank you for your reply and sorry for the delayed response. Looks like I had another graalvm reference in my build.gradle file and you comment helped me to fix it. I removed the dependency from build.gradle and that  help me to resolved the above reported issue. So this can be closed

**Comment by peter-hofer** [comment]
Glad to hear it, thanks for reporting back.
