### ISSUE TITLE
Jersey HK2 giving dynamic proxy error while running native image

### ISSUE THREAD

**Issue by bajajyog** [oracle/graal#2754]
**Describe the issue**

     

 Spring boot(2.4.0.Snapshot) , Jersey(2.3x), Hibernate  micro Service  app. I am able to build the native image for my microservice successfully. While running the native image, it is giving error for jersey.I have added below entries in proxy-config.json but jersey proxy error not  resolving. Dynamic proxies are not allowed at run time, only should be done at image creation time. Please advise, why native image creation proxies are not created for jersey by Graal VM. Any issues in proxy config json file.
proxy config entries
[
   ["javax.ws.rs.core.UriInfo","org.glassfish.jersey.server.ExtendedUriInfo","javax.ws.rs.container.ResourceInfo"],
    ["javax.ws.rs.container.ResourceInfo","org.glassfish.jersey.server.ExtendedUriInfo","javax.ws.rs.core.UriInfo"],
     ["javax.ws.rs.container.ResourceInfo","javax.ws.rs.core.UriInfo","org.glassfish.jersey.server.ExtendedUriInfo"],
     ["javax.servlet.http.HttpServletRequest"],
      ["org.glassfish.jersey.server.ExtendedUriInfo","javax.ws.rs.container.ResourceInfo","javax.ws.rs.core.UriInfo"]
]

**Steps to reproduce the issue**
if required, I can set up a small demo code for this issue in github.

**Describe GraalVM and your environment:**
 
Java 8 HotSpot(TM) 64-Bit Server VM GraalVM EE 20.1.1 (build 25.261-b33-jvmci-20.1-b04, mixed mode) mac os

**More details**

-H:+InstallExitHandlers \
-H:ReflectionConfigurationResources=META-INF/native-image/org.apache.tomcat.embed/tomcat-embed-websocket/tomcat-reflection.json \
-H:ResourceConfigurationResources=META-INF/native-image/org.apache.tomcat.embed/tomcat-embed-websocket/tomcat-resource.json \
-H:ReflectionConfigurationResources=META-INF/native-image/org.apache.tomcat.embed/tomcat-embed-core/tomcat-reflection.json \
-H:ResourceConfigurationResources=META-INF/native-image/org.apache.tomcat.embed/tomcat-embed-core/tomcat-resource.json \
-H:Name=abc \
-H:+RemoveSaturatedTypeFlows \
-H:FallbackThreshold=0 \
-H:EnableURLProtocols=http \
-H:EnableURLProtocols=https \
-H:EnableURLProtocols=http,https \
-H:+ReportUnsupportedElementsAtRuntime \
-H:+ReportExceptionStackTraces \
-H:+EnableAllSecurityServices \
-H:+AllowIncompleteClasspath \
-H:+TraceClassInitialization \
-H:IncludeResourceBundles=oracle.net.jdbc.nl.mesg.NLSR,oracle.net.mesg.Message \
-H:ClassInitialization=org.jboss.logging:build_time,org.hibernate.internal:build_time \
-H:ClassInitialization=org.hibernate.query:build_time \
-H:ClassInitialization=org.hibernate.internal.StatelessSessionImpl:run_time \
-H:ClassInitialization=javax.el.ListELResolver:build_time,javax.el.BeanELResolver:build_time,javax.el.MapELResolver:build_time,javax.el.CompositeELResolver:build_time \

-H:ClassInitialization=org.apache.logging.log4j.core.net.MulticastDnsAdvertiser:run_time \

'-H:ClassInitialization=org.apache.commons.logging.LogAdapter$Log4jLog:build_time' \
-H:ClassInitialization=org.springframework.boot.logging.log4j2.Log4J2LoggingSystem:build_time \
-H:+DumpTargetInfo \
-H:ClassInitialization=net.bytebuddy:build_time \
-H:ClassInitialization=java.sql.DriverManager:run_time \
-H:ClassInitialization=oracle.net.jdbc.nl.mesg.NLSR_en:build_time \
-H:+TraceServiceLoaderFeature \
-H:JNIConfigurationResources=META-INF/native-image/com/birt-service-graal/jni-config.json \
-H:ReflectionConfigurationResources=META-INF/native-image/com/birt-core-graal/reflect-config.json \
-H:ReflectionConfigurationResources=META-INF/native-image/com/birt-service-graal/reflect-config.json \
-H:ReflectionConfigurationResources=META-INF/native-image/com/core-graal/reflect-config.json \
-H:ResourceConfigurationResources=META-INF/native-image/com/birt-core-graal/resource-config.json \
-H:ResourceConfigurationResources=META-INF/native-image/com/birt-service-graal/resource-config.json \
-H:ResourceConfigurationResources=META-INF/native-image/com/core-graal/resource-config.json \
-H:DynamicProxyConfigurationResources=META-INF/native-image/com/birt-core-graal/proxy-config.json \
-H:DynamicProxyConfigurationResources=META-INF/native-image/com/birt-service-graal/proxy-config.json \
-H:DynamicProxyConfigurationResources=META-INF/native-image/com/core-graal/proxy-config.json \
-H:CLibraryPath=/Library/Java/JavaVirtualMachines/graalvm-ee-java8-20.1.1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64 \

-H:Class=com.ABC \
```
 
```

***           **Error Stack** *********
: java.lang.IllegalStateException: A descriptor SystemDescriptor(
	implementation=org.glassfish.jersey.inject.hk2.SupplierFactoryBridge
	contracts={javax.ws.rs.core.UriInfo,org.glassfish.jersey.server.ExtendedUriInfo,javax.ws.rs.container.ResourceInfo}
	scope=org.glassfish.jersey.process.internal.RequestScoped
	qualifiers={}
	descriptorType=PROVIDE_METHOD
	descriptorVisibility=NORMAL
	metadata=
	rank=0
	loader=org.glassfish.hk2.utilities.binding.AbstractBinder$2@132c379f8
	proxiable=true
	proxyForSameScope=false
	analysisName=null
	id=54
	locatorId=0
	identityHashCode=305159356
	reified=true) requires a proxy, but the proxyable library is not on the classpath
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2071) ~[?:?]
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93) ~[?:?]
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67) ~[?:?]
	at org.glassfish.jersey.inject.hk2.ContextInjectionResolverImpl.resolve(ContextInjectionResolverImpl.java:103) ~[omsai:?]
	at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:188) ~[?:?]
	at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:211) ~[?:?]
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:334) ~[?:?]
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463) ~[?:?]
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59) ~[?:?]
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47) ~[?:?]
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131) ~[?:?]
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176) ~[?:?]
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98) ~[?:?]
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102) ~[?:?]
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93) ~[?:?]
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67) ~[?:?]
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.lambda$getAllServiceHolders$0(AbstractHk2InjectionManager.java:136) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:?]
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:?]
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getAllServiceHolders(AbstractHk2InjectionManager.java:140) ~[?:?]
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getAllServiceHolders(ImmediateHk2InjectionManager.java:30) ~[?:?]
	at org.glassfish.jersey.internal.inject.Providers.getServiceHolders(Providers.java:307) ~[?:?]
	at org.glassfish.jersey.internal.inject.Providers.getCustomProviders(Providers.java:151) ~[?:?]
	at org.glassfish.jersey.message.internal.MessageBodyFactory.initialize(MessageBodyFactory.java:219) ~[?:?]
	at org.glassfish.jersey.message.internal.MessageBodyFactory$MessageBodyWorkersConfigurator.postInit(MessageBodyFactory.java:114) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$2(ApplicationHandler.java:349) ~[?:?]
	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:349) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:293) ~[?:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[?:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[?:?]
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:292) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:259) ~[?:?]
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311) ~[?:?]
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154) ~[?:?]
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:347) ~[?:?]
	at javax.servlet.GenericServlet.init(GenericServlet.java:158) ~[omsai:?]
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1134) ~[?:?]
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:986) ~[?:?]
	at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedContext.load(TomcatEmbeddedContext.java:82) ~[omsai:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) ~[?:?]
	at java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2897) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:?]
	at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedContext.lambda$deferredLoadOnStartup$0(TomcatEmbeddedContext.java:65) ~[omsai:?]
	at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedContext.doWithThreadContextClassLoader(TomcatEmbeddedContext.java:106) ~[omsai:?]
	at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedContext.deferredLoadOnStartup(TomcatEmbeddedContext.java:64) ~[omsai:?]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.performDeferredLoadOnStartup(TomcatWebServer.java:305) ~[omsai:?]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:216) ~[omsai:?]
	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43) ~[?:?]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[omsai:?]
	... 14 more

**Comment by peter-hofer** [comment]
Thank you for your report @bajajyog . Did you use the agent to generate your configuration?
Looking at the source code of `org.jvnet.hk2.internal.Utilities.createService()`, it calls `Utilities.proxiesAvailable()`, which tries to load class `javassist.util.proxy.MethodHandler` unless it has already done so before. native-image does not support runtime class loading, so this would fail at runtime, with the exact message you are getting. You might be able to get this to work by ensuring that `proxiesAvailable` is called at least once during the image build.

**Comment by bajajyog** [comment]
Yes, I used agent to generate the configs. That helped to resolve apache log4j issues. let me set up graalvm feature for jersey proxy creation at image build time. thanks for quick response and oracle to have this amazing technology.

**Comment by bajajyog** [comment]
Your recommendation worked. Now proxy error resolved.

**Comment by bajajyog** [comment]
Now this error coming. Please advise if any recommendation.


Caused by: javax.validation.ValidationException: HV000183: Unable to initialize 'javax.el.ExpressionFactory'. Check that you have the EL dependencies on the classpath, or use ParameterMessageInterpolator instead
	at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.buildExpressionFactory(ResourceBundleMessageInterpolator.java:206) ~[?:?]
	at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.<init>(ResourceBundleMessageInterpolator.java:94) ~[?:?]
	at org.hibernate.validator.internal.engine.AbstractConfigurationImpl.getDefaultMessageInterpolator(AbstractConfigurationImpl.java:570) ~[omsai:?]
	at org.hibernate.validator.internal.engine.AbstractConfigurationImpl.getDefaultMessageInterpolatorConfiguredWithClassLoader(AbstractConfigurationImpl.java:790) ~[omsai:?]
	at org.hibernate.validator.internal.engine.AbstractConfigurationImpl.getMessageInterpolator(AbstractConfigurationImpl.java:480) ~[omsai:?]
	at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.<init>(ValidatorFactoryImpl.java:151) ~[?:?]
	at org.hibernate.validator.HibernateValidator.buildValidatorFactory(HibernateValidator.java:38) ~[omsai:?]
	at org.hibernate.validator.internal.engine.AbstractConfigurationImpl.buildValidatorFactory(AbstractConfigurationImpl.java:448) ~[omsai:?]
	at org.glassfish.jersey.server.validation.internal.ValidationBinder$DefaultValidatorFactoryProvider.get(ValidationBinder.java:136) ~[omsai:?]
	at org.glassfish.jersey.server.validation.internal.ValidationBinder$DefaultValidatorFactoryProvider.get(ValidationBinder.java:129) ~[omsai:?]
	at org.glassfish.jersey.inject.hk2.SupplierFactoryBridge.provide(SupplierFactoryBridge.java:76) ~[omsai:?]
	at org.jvnet.hk2.internal.FactoryCreator.create(FactoryCreator.java:129) ~[?:?]
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463) ~[?:?]
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59) ~[?:?]
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47) ~[?:?]
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131) ~[?:?]
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176) ~[?:?]
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98) ~[?:?]
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102) ~[?:?]
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:666) ~[?:?]
	at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:54) ~[?:?]
	at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:188) ~[?:?]
	at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:211) ~[?:?]
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:334) ~[?:?]
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463) ~[?:?]
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59) ~[?:?]
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47) ~[?:?]
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131) ~[?:?]
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176) ~[?:?]
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98) ~[?:?]
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102) ~[?:?]
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:758) ~[?:?]
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:721) ~[?:?]
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:717) ~[?:?]
	at org.glassfish.jersey.inject.hk2.SupplierFactoryBridge.provide(SupplierFactoryBridge.java:75) ~[omsai:?]
	at org.jvnet.hk2.internal.FactoryCreator.create(FactoryCreator.java:129) ~[?:?]
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463) ~[?:?]
	at org.jvnet.hk2.internal.PerLookupContext.findOrCreate(PerLookupContext.java:46) ~[?:?]
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102) ~[?:?]
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:758) ~[?:?]
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:721) ~[?:?]
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:691) ~[?:?]
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getInstance(AbstractHk2InjectionManager.java:160) ~[?:?]
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getInstance(ImmediateHk2InjectionManager.java:30) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvokerConfigurator.lambda$postInit$0(ResourceMethodInvokerConfigurator.java:54) ~[?:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker$Builder.build(ResourceMethodInvoker.java:194) ~[?:?]
	at org.glassfish.jersey.server.internal.routing.RuntimeModelBuilder.createInflector(RuntimeModelBuilder.java:106) ~[?:?]
	at org.glassfish.jersey.server.internal.routing.RuntimeModelBuilder.createMethodRouter(RuntimeModelBuilder.java:93) ~[?:?]
	at org.glassfish.jersey.server.internal.routing.RuntimeModelBuilder.createResourceMethodRouters(RuntimeModelBuilder.java:287) ~[?:?]
	at org.glassfish.jersey.server.internal.routing.RuntimeModelBuilder.buildModel(RuntimeModelBuilder.java:151) ~[?:?]
	at org.glassfish.jersey.server.internal.routing.Routing$Builder.buildStage(Routing.java:223) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:399) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:293) ~[?:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[?:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[?:?]
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:292) ~[?:?]
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:259) ~[?:?]
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311) ~[?:?]
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154) ~[?:?]
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:347) ~[?:?]
	at javax.servlet.GenericServlet.init(GenericServlet.java:158) ~[omsai:?]
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1134) ~[?:?]
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:986) ~[?:?]
	at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedContext.load(TomcatEmbeddedContext.java:82) ~[omsai:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) ~[?:?]
	at java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2897) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:?]
	at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedContext.lambda$deferredLoadOnStartup$0(TomcatEmbeddedContext.java:65) ~[omsai:?]
	at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedContext.doWithThreadContextClassLoader(TomcatEmbeddedContext.java:106) ~[omsai:?]
	at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedContext.deferredLoadOnStartup(TomcatEmbeddedContext.java:64) ~[omsai:?]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.performDeferredLoadOnStartup(TomcatWebServer.java:305) ~[omsai:?]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:216) ~[omsai:?]
	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43) ~[?:?]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[omsai:?]

**Comment by bajajyog** [comment]
I finally able to resolve javax.el.ExpressionFactory error by Graalvm substitution.
