### ISSUE TITLE
Native image fails due to "/usr/bin/ld: cannot find -l-L/usr/lib/x86_64-linux-gnu -lSDL2"

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#2768]
**Describe the issue**
Native image compilation fails due to "/usr/bin/ld: cannot find -l-L/usr/lib/x86_64-linux-gnu -lSDL2" on Ubuntu when using 20.2. Everything worked fine with 20.1 and still works fine on macOS. `libc6-dev` should be preinstalled on the system and we manually install `libsdl2-dev`.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. `git clone https://github.com/hpi-swa/trufflesqueak/`
2. `git checkout wip/20.2`
3. `mx --env trufflesqueak-svm build`

**Describe GraalVM and your environment:**
 - GraalVM version: **20.2.0 CE**
 - JDK major version: **8 and 11**
 - OS: **Ubuntu**
 - Architecture: **AMD64**

**More details**
```
2020-08-19T09:08:42.2514399Z [trufflesqueak:11299]    classlist:   7,208.41 ms,  1.52 GB
2020-08-19T09:08:45.3611489Z [trufflesqueak:11299]        (cap):   2,374.46 ms,  1.52 GB
2020-08-19T09:08:46.4433112Z [trufflesqueak:11299]        setup:   4,173.74 ms,  1.52 GB
2020-08-19T09:10:15.5920406Z [trufflesqueak:11299]     (clinit):     535.75 ms,  3.48 GB
2020-08-19T09:10:16.1667341Z [trufflesqueak:11299]   (typeflow):  45,719.91 ms,  3.48 GB
2020-08-19T09:10:16.1668142Z [trufflesqueak:11299]    (objects):  36,972.03 ms,  3.48 GB
2020-08-19T09:10:16.1668677Z [trufflesqueak:11299]   (features):   3,873.25 ms,  3.48 GB
2020-08-19T09:10:16.1672137Z [trufflesqueak:11299]     analysis:  88,701.41 ms,  3.48 GB
2020-08-19T09:10:18.1707834Z [trufflesqueak:11299]     universe:   2,002.55 ms,  3.72 GB
2020-08-19T09:10:18.2156417Z 4914 method(s) included for runtime compilation
2020-08-19T09:10:31.2802401Z [trufflesqueak:11299]      (parse):  12,146.48 ms,  3.70 GB
2020-08-19T09:10:43.6179266Z [trufflesqueak:11299]     (inline):  11,945.39 ms,  3.44 GB
2020-08-19T09:11:52.0410689Z [trufflesqueak:11299]    (compile):  68,344.21 ms,  3.52 GB
2020-08-19T09:11:54.6835586Z [trufflesqueak:11299]      compile:  95,649.44 ms,  3.52 GB
2020-08-19T09:12:01.3162201Z [trufflesqueak:11299]        image:   6,631.50 ms,  3.56 GB
2020-08-19T09:12:01.8638525Z [trufflesqueak:11299]        write:     544.57 ms,  3.56 GB
2020-08-19T09:12:01.8778619Z Fatal error:java.lang.RuntimeException: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1
2020-08-19T09:12:01.8779153Z 
2020-08-19T09:12:01.8779495Z Based on the linker command output, possible reasons for this include:
2020-08-19T09:12:01.8780696Z 1. It appears as though lib-L/usr/lib/x86_64-linux-gnu.a is missing. Please install it.
2020-08-19T09:12:01.8781671Z 
2020-08-19T09:12:01.8782567Z Linker command executed:
2020-08-19T09:12:01.8786094Z /usr/bin/gcc -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-2717626522138480107/exported_symbols.list -Wl,--exclude-libs,ALL -Wl,-x -o /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/trufflesqueak.image/trufflesqueak /tmp/SVM-2717626522138480107/trufflesqueak.o /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/libnet.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/svm/clibraries/linux-amd64/libffi.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/libnio.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/libjava.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/libfdlibm.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/libzip.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/svm/clibraries/linux-amd64/libjvm.a -v -L/tmp/SVM-2717626522138480107 -L/home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib -L/home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/svm/clibraries/linux-amd64 -L/home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/include '-l-L/usr/lib/x86_64-linux-gnu -lSDL2' -lpthread -ldl -lz -lrt 
2020-08-19T09:12:01.8786946Z 
2020-08-19T09:12:01.8787334Z Linker command output:
2020-08-19T09:12:01.8787784Z Using built-in specs.
2020-08-19T09:12:01.8788280Z COLLECT_GCC=/usr/bin/gcc
2020-08-19T09:12:01.8789054Z COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
2020-08-19T09:12:01.8789380Z OFFLOAD_TARGET_NAMES=nvptx-none
2020-08-19T09:12:01.8789605Z OFFLOAD_TARGET_DEFAULT=1
2020-08-19T09:12:01.8789890Z Target: x86_64-linux-gnu
2020-08-19T09:12:01.8791422Z Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
2020-08-19T09:12:01.8791834Z Thread model: posix
2020-08-19T09:12:01.8792156Z gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
2020-08-19T09:12:01.8792635Z COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/
2020-08-19T09:12:01.8793268Z LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../:/lib/:/usr/lib/
2020-08-19T09:12:01.8794389Z COLLECT_GCC_OPTIONS='-z' 'noexecstack' '-o' '/home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/trufflesqueak.image/trufflesqueak' '-v' '-L/tmp/SVM-2717626522138480107' '-L/home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib' '-L/home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/svm/clibraries/linux-amd64' '-L/home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/include' '-mtune=generic' '-march=x86-64'
2020-08-19T09:12:01.8799098Z  /usr/lib/gcc/x86_64-linux-gnu/7/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/7/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper -plugin-opt=-fresolution=/tmp/ccP1o6at.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -z now -z relro -o /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/trufflesqueak.image/trufflesqueak -z noexecstack /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/7/crtbeginS.o -L/tmp/SVM-2717626522138480107 -L/home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib -L/home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/svm/clibraries/linux-amd64 -L/home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/include -L/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/7/../../.. --gc-sections --dynamic-list /tmp/SVM-2717626522138480107/exported_symbols.list --exclude-libs ALL -x /tmp/SVM-2717626522138480107/trufflesqueak.o /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/libnet.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/svm/clibraries/linux-amd64/libffi.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/libnio.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/libjava.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/libfdlibm.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/libzip.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/svm/clibraries/linux-amd64/libjvm.a -l-L/usr/lib/x86_64-linux-gnu -lSDL2 -lpthread -ldl -lz -lrt -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-linux-gnu/7/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crtn.o
2020-08-19T09:12:01.8800305Z /usr/bin/ld: cannot find -l-L/usr/lib/x86_64-linux-gnu -lSDL2
2020-08-19T09:12:01.8800473Z collect2: error: ld returned 1 exit status
2020-08-19T09:12:01.8800551Z 
2020-08-19T09:12:01.8800702Z 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2020-08-19T09:12:01.8800892Z 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2020-08-19T09:12:01.8801085Z 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2020-08-19T09:12:01.8801262Z 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
2020-08-19T09:12:01.8801438Z 	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
2020-08-19T09:12:01.8801611Z 	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
2020-08-19T09:12:01.8801777Z 	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:480)
2020-08-19T09:12:01.8801960Z 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:349)
2020-08-19T09:12:01.8802211Z 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:508)
2020-08-19T09:12:01.8802397Z 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:114)
2020-08-19T09:12:01.8802700Z Caused by: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1
2020-08-19T09:12:01.8802797Z 
2020-08-19T09:12:01.8802943Z Based on the linker command output, possible reasons for this include:
2020-08-19T09:12:01.8803344Z 1. It appears as though lib-L/usr/lib/x86_64-linux-gnu.a is missing. Please install it.
2020-08-19T09:12:01.8803455Z 
2020-08-19T09:12:01.8803586Z Linker command executed:
2020-08-19T09:12:01.8806510Z /usr/bin/gcc -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-2717626522138480107/exported_symbols.list -Wl,--exclude-libs,ALL -Wl,-x -o /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/trufflesqueak.image/trufflesqueak /tmp/SVM-2717626522138480107/trufflesqueak.o /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/libnet.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/svm/clibraries/linux-amd64/libffi.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/libnio.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/libjava.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/libfdlibm.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/libzip.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/svm/clibraries/linux-amd64/libjvm.a -v -L/tmp/SVM-2717626522138480107 -L/home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib -L/home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/svm/clibraries/linux-amd64 -L/home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/include '-l-L/usr/lib/x86_64-linux-gnu -lSDL2' -lpthread -ldl -lz -lrt 
2020-08-19T09:12:01.8806985Z 
2020-08-19T09:12:01.8807119Z Linker command output:
2020-08-19T09:12:01.8807405Z Using built-in specs.
2020-08-19T09:12:01.8807552Z COLLECT_GCC=/usr/bin/gcc
2020-08-19T09:12:01.8807887Z COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
2020-08-19T09:12:01.8808185Z OFFLOAD_TARGET_NAMES=nvptx-none
2020-08-19T09:12:01.8808328Z OFFLOAD_TARGET_DEFAULT=1
2020-08-19T09:12:01.8808604Z Target: x86_64-linux-gnu
2020-08-19T09:12:01.8810137Z Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
2020-08-19T09:12:01.8810619Z Thread model: posix
2020-08-19T09:12:01.8810949Z gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
2020-08-19T09:12:01.8811430Z COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/
2020-08-19T09:12:01.8812056Z LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../:/lib/:/usr/lib/
2020-08-19T09:12:01.8813195Z COLLECT_GCC_OPTIONS='-z' 'noexecstack' '-o' '/home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/trufflesqueak.image/trufflesqueak' '-v' '-L/tmp/SVM-2717626522138480107' '-L/home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib' '-L/home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/svm/clibraries/linux-amd64' '-L/home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/include' '-mtune=generic' '-march=x86-64'
2020-08-19T09:12:01.8817514Z  /usr/lib/gcc/x86_64-linux-gnu/7/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/7/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper -plugin-opt=-fresolution=/tmp/ccP1o6at.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -z now -z relro -o /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/trufflesqueak.image/trufflesqueak -z noexecstack /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/7/crtbeginS.o -L/tmp/SVM-2717626522138480107 -L/home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib -L/home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/svm/clibraries/linux-amd64 -L/home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/include -L/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/7/../../.. --gc-sections --dynamic-list /tmp/SVM-2717626522138480107/exported_symbols.list --exclude-libs ALL -x /tmp/SVM-2717626522138480107/trufflesqueak.o /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/libnet.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/svm/clibraries/linux-amd64/libffi.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/libnio.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/libjava.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/libfdlibm.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/libzip.a /home/runner/work/trufflesqueak/graal/sdk/mxbuild/linux-amd64/GRAALVM_1E8FD16873_JAVA8_STAGE1/graalvm-1e8fd16873-java8-20.2.0/jre/lib/svm/clibraries/linux-amd64/libjvm.a -l-L/usr/lib/x86_64-linux-gnu -lSDL2 -lpthread -ldl -lz -lrt -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-linux-gnu/7/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crtn.o
2020-08-19T09:12:01.8818699Z /usr/bin/ld: cannot find -l-L/usr/lib/x86_64-linux-gnu -lSDL2
2020-08-19T09:12:01.8818851Z collect2: error: ld returned 1 exit status
2020-08-19T09:12:01.8818939Z 
2020-08-19T09:12:01.8819089Z 	at com.oracle.svm.hosted.image.NativeBootImageViaCC.handleLinkerFailure(NativeBootImageViaCC.java:459)
2020-08-19T09:12:01.8819259Z 	at com.oracle.svm.hosted.image.NativeBootImageViaCC.write(NativeBootImageViaCC.java:434)
2020-08-19T09:12:01.8819427Z 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:677)
2020-08-19T09:12:01.8819605Z 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
2020-08-19T09:12:01.8819775Z 	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
2020-08-19T09:12:01.8819938Z 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
2020-08-19T09:12:01.8820098Z 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
2020-08-19T09:12:01.8820256Z 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
2020-08-19T09:12:01.8820394Z 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:163)
2020-08-19T09:12:02.0414664Z Error: Image build request failed with exit status 1
2020-08-19T09:12:02.0526871Z 
2020-08-19T09:12:02.1408408Z Building trufflesqueak.image failed
2020-08-19T09:12:02.2419709Z 1 build tasks failed
```

Link to build: https://github.com/hpi-swa/trufflesqueak/runs/1002207920?check_suite_focus=true#step:4:333

**Comment by olpaw** [comment]
@fniephaus can you try if moving `-L/usr/lib/x86_64-linux-gnu` and `-L/usr/local/lib` out of https://github.com/hpi-swa/trufflesqueak/blob/715dd01fb5091d62c099716cecb28dad21e7d1fa/src/de.hpi.swa.trufflesqueak/src/de/hpi/swa/trufflesqueak/aot/SDLCContext.java#L22..L31 into https://github.com/hpi-swa/trufflesqueak/blob/715dd01fb5091d62c099716cecb28dad21e7d1fa/src/de.hpi.swa.trufflesqueak/src/de/hpi/swa/trufflesqueak/aot/SDLCContext.java#L34..L43 does the trick?

**Comment by olpaw** [comment]
Also https://github.com/hpi-swa/trufflesqueak/blob/715dd01fb5091d62c099716cecb28dad21e7d1fa/src/de.hpi.swa.trufflesqueak/src/de/hpi/swa/trufflesqueak/aot/SDLCContext.java#L22 should actually return "SDL2" instead of "-lSDL2".

**Comment by olpaw** [comment]
https://github.com/oracle/graal/issues/2768#issuecomment-677518381 wont work because `getOptions()` only affects query code compilation but not linking. Therefore you have to use `-H:NativeLinkerOption=-L/usr/lib/x86_64-linux-gnu` instead.

**Comment by olpaw** [comment]
@fniephaus let me know if the changes have the desired effect so that I can close this issue.

**Comment by fniephaus** [comment]
Thanks a lot for looking into this and suggesting the right fix! As of https://github.com/hpi-swa/trufflesqueak/commit/1b1ac6822b36781246d06c4e65795228fdb3519c, this no longer happens. Thanks again, Fabio
