### ISSUE TITLE
Error loading JVMCI in JDK8?

### ISSUE THREAD

**Issue by PRIESt512** [oracle/graal#278]
I wanted to run an example - [Truffle Tutorial: Embedding Truffle Languages in Java](http://oracle.github.io/graal/truffle/javadoc/com/oracle/truffle/tutorial/embedding/package-summary.html)
However, the line: 
`PolyglotEngine engine = PolyglotEngine.newBuilder().build();`
Generates an exception:
`Exception in thread "main" java.util.ServiceConfigurationError: com.oracle.truffle.api.TruffleRuntimeAccess: Provider org.graalvm.compiler.truffle.hotspot.HotSpotTruffleRuntimeAccess not a subtype`
If you run an example with the JVM option: _-original_, exceptions are not generated.
I looked at the sources, found the most interesting in the class: _com.oracle.truffle.api.Truffle_
Method: _com.oracle.truffle.api.Truffle#initRuntime_:
```
...
boolean jdk8OrEarlier = System.getProperty("java.specification.version").compareTo("1.9") < 0;
                if (!jdk8OrEarlier) {
                    // As of JDK9, the JVMCI Services class should only be used for service types
                    // defined by JVMCI. Other services types should use ServiceLoader directly.
                    access = selectTruffleRuntimeAccess(ServiceLoader.load(TruffleRuntimeAccess.class));
                } else {
                    String[] serviceClassNames = {"jdk.vm.ci.services.Services", "jdk.vm.ci.service.Services",
                                    "jdk.internal.jvmci.service.Services", "com.oracle.jvmci.service.Services"};
                    for (String serviceClassName : serviceClassNames) {
                        try {
                            servicesClass = Class.forName(serviceClassName);
                            if (servicesClass != null) {
                                access = selectTruffleRuntimeAccess(reflectiveServiceLoaderLoad(servicesClass));
                                if (access != null) {
                                    break;
                                }
                            }
                        } catch (ClassNotFoundException e) {
                            continue;
                        }
                    }
                }
                // TODO: try standard ServiceLoader?

                if (access != null) {
                    return access.getRuntime();
                }
                return new DefaultTruffleRuntime();
            }
```
We're seeing a crawl on the _serviceClassNames_. Each element of the array is tested for presence in the classpath and if all is well, try to get a reflex method _load_(method _reflectiveServiceLoaderLoad_):
```
Method m = servicesClass.getDeclaredMethod("load", Class.class);
return (Iterable<TruffleRuntimeAccess>) m.invoke(null, TruffleRuntimeAccess.class);
```
Let's consider more in detail load:
```
public static <S> Iterable<S> load(Class<S> service) {
        SecurityManager sm = System.getSecurityManager();
        if (sm != null) {
            sm.checkPermission(new JVMCIPermission());
        }
        return load0(service);
    }
private static <S> Iterable<S> load0(Class<S> service) {
        if (jvmciEnabled) {
            ClassLoader cl = null;
            try {
                cl = getJVMCIClassLoader();
                return ServiceLoader.load(service, cl);
            } catch (UnsatisfiedLinkError e) {
                jvmciEnabled = false;
            } catch (InternalError e) {
                if (e.getMessage().equals("JVMCI is not enabled")) {
                    jvmciEnabled = false;
                } else {
                    throw e;
                }
            }
        }
        return Collections.emptyList();
    }
```
Next, obtaining the ServiceLoader iterator calls the _nextService()_:
```
private S nextService() {
            if (!hasNextService())
                throw new NoSuchElementException();
            String cn = nextName;
            nextName = null;
            Class<?> c = null;
            try {
                c = Class.forName(cn, false, loader);
            } catch (ClassNotFoundException x) {
                fail(service,
                     "Provider " + cn + " not found");
            }
            if (!service.isAssignableFrom(c)) {
                fail(service,
                     "Provider " + cn  + " not a subtype");
            }
```
But at the same time in META-INF the necessary information is present. Why _service.isAssignableFrom(c)_ returns false?
I correctly understood all and here an error or so it is necessary?
Thank you in advance! :)

**Comment by dougxc** [comment]
Hi @PRIESt512 , how exactly are you launching the VM? A simple example for reproducing your issue along with a command line would be very helpful. Based on what you've reported, it sounds like `com.oracle.truffle.api.TruffleRuntimeAccess` and `org.graalvm.compiler.truffle.hotspot.HotSpotTruffleRuntimeAccess` are being loaded by different class loaders.

**Comment by dougxc** [comment]
I think this should fix your use case: https://github.com/oracle/graal/issues/275#issuecomment-355658059

**Comment by PRIESt512** [comment]
Yes, there was a thought that because of the different loaders class _service.isAssignableFrom(c)_ always returns false. But still was not completely sure of this... 
Using _labsjdk_ did not help unfortunately. Use _labsjdk_ - then the code in the method _com.oracle.truffle.api.Truffle#initRuntime_  returns DefaultTruffleRuntime. Passage through an array _serviceClassNames_ throws an exception _ClassNotFoundException_ at each iteration.
Code to run:
```
public static void main(String[] args) throws IOException {

    PolyglotEngine engine = PolyglotEngine.newBuilder().build();
    Source src =
        Source.newBuilder("(function (a, b) {\n" + "  return a * b;" + "})").mimeType("text/javascript").name("mul.js")
              .build();

    PolyglotEngine.Value jsFunction = engine.eval(src);
    Multiplier mul = jsFunction.as(Multiplier.class);
    System.out.println(mul.multiply(2, 4));
}
```
Command line:
```
MacBook-Air-Aleksej:libs aleksej$ /Users/aleksej/graalvm-0.30.2/Contents/Home/bin/java -jar Graal-1.0-Test.jar 
Exception in thread "main" java.util.ServiceConfigurationError: com.oracle.truffle.api.TruffleRuntimeAccess: Provider org.graalvm.compiler.truffle.hotspot.HotSpotTruffleRuntimeAccess not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at com.oracle.truffle.api.Truffle.selectTruffleRuntimeAccess(Truffle.java:61)
	at com.oracle.truffle.api.Truffle.access$000(Truffle.java:39)
	at com.oracle.truffle.api.Truffle$1.run(Truffle.java:119)
	at com.oracle.truffle.api.Truffle$1.run(Truffle.java:90)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.oracle.truffle.api.Truffle.initRuntime(Truffle.java:90)
	at com.oracle.truffle.api.Truffle.<clinit>(Truffle.java:48)
	at com.oracle.truffle.api.TruffleOptions.<clinit>(TruffleOptions.java:126)
	at com.oracle.truffle.api.nodes.Node.<init>(Node.java:89)
	at com.oracle.truffle.api.impl.Accessor$2.<init>(Accessor.java:396)
	at com.oracle.truffle.api.impl.Accessor.<clinit>(Accessor.java:396)
	at com.oracle.truffle.api.vm.PolyglotEngine.ensureInitialized(PolyglotEngine.java:219)
	at com.oracle.truffle.api.vm.PolyglotEngine.<init>(PolyglotEngine.java:263)
	at com.oracle.truffle.api.vm.PolyglotEngine.<clinit>(PolyglotEngine.java:212)
	at com.sample.Start.main(Start.java:32)
```
Running with the JVM argument _original_:
```
MacBook-Air-Aleksej:libs aleksej$ /Users/aleksej/graalvm-0.30.2/Contents/Home/bin/java -original  -jar Graal-1.0-Test.jar 
Exception in thread "main" java.lang.IllegalStateException: No language for MIME type text/javascript found. Supported types: []
	at com.oracle.truffle.api.vm.PolyglotEngine.findLanguage(PolyglotEngine.java:913)
	at com.oracle.truffle.api.vm.PolyglotEngine.eval(PolyglotEngine.java:654)
	at com.sample.Start.main(Start.java:38)
```
Running with labsjdk:
```
MacBook-Air-Aleksej:libs aleksej$ /Users/aleksej/graal/sulong/labsjdk1.8.0_151-jvmci-0.39/Contents/Home/bin/java -jar Graal-1.0-Test.jar
Exception in thread "main" java.lang.IllegalStateException: No language for MIME type text/javascript found. Supported types: []
	at com.oracle.truffle.api.vm.PolyglotEngine.findLanguage(PolyglotEngine.java:913)
	at com.oracle.truffle.api.vm.PolyglotEngine.eval(PolyglotEngine.java:654)
	at ru.rtec.Start.main(Start.java:38)
```
```
MacBook-Air-Aleksej:libs aleksej$ /Users/aleksej/graalvm-0.30.2/Contents/Home/bin/java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b01-internal-jvmci-0.38, mixed mode)
```
MacBook: OS 10.13.2

**Comment by dougxc** [comment]
@chumer , shouldn't @PRIESt512 be using `org.graalvm.polyglot.Engine` instead of `com.oracle.truffle.api.vm.PolyglotEngine`? Is there some updated version of the tutorial in terms of Graal SDK?

**Comment by defsprite** [comment]
I was running into the same problem getting `SimpleLanguage` to work. Here is what I found:

- The issue is a result of two different class loaders at play
- **Using Labs JDK as `JAVA_HOME` resolves the issue**

As far as I know, the Labs JDK does not contain the language implementations (`<jdk_root>/jre/languages`) of the original Graal VM download. 

If you like to run `text/javascript` you would need to add `graal-js.jar` manually to the classpath. A quick but not very thorough check showed that adding it will register `JavaScript@ 0.9 for [application/javascript, text/javascript]` and `application/js-regex=[REGEX@ 0.1 for [application/js-regex]` 

`engine.getLanguages()` will show you the supported languages.

**Comment by chumer** [comment]
The embedding tutorial in the javadoc are outdated and the examples are not functional anymore in GraalVM.
You need to use org.graalvm.polyglot package instead. Its time update the javadoc to reflect this ASAP.
