### ISSUE TITLE
org.xml.sax.SAXException

### ISSUE THREAD

**Issue by wangzhongshan** [oracle/graal#2802]
**Describe the issue**

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. **git clone https://github.com/wangzhongshan/zeebe-bpmn-demo.git**
2. **mvn clean package**
3. **native-image --verbose --initialize-at-build-time --no-fallback --allow-incomplete-classpath --report-unsupported-elements-at-runtime -cp ./target/zeebe-bpmn-demo-1.0-SNAPSHOT.jar App ./target/app**
4. **./target/app**

**Describe GraalVM and your environment:**
 - GraalVM version:
    openjdk 11.0.7 2020-04-14
   OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
   OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)

 - JDK major version: **11**
 - OS: **[macOS Catalina]**
 - Architecture: **[AMD64]**

**More details**

```
    Exception in thread "main" org.camunda.bpm.model.xml.ModelParseException: SAXException while parsing input stream
        at org.camunda.bpm.model.xml.impl.util.DomUtil.parseInputStream(DomUtil.java:244)
        at org.camunda.bpm.model.xml.impl.parser.AbstractModelParser.parseModelFromStream(AbstractModelParser.java:97)
        at io.zeebe.model.bpmn.impl.BpmnParser.parseModelFromStream(BpmnParser.java:62)
        at io.zeebe.model.bpmn.Bpmn.doReadModelFromInputStream(Bpmn.java:387)
        at io.zeebe.model.bpmn.Bpmn.readModelFromStream(Bpmn.java:281)
        at com.jd.jddlink.App.main(App.java:14)
Caused by: org.xml.sax.SAXException: Error: URI=null Line=2: schema_reference.4: Failed to read schema document 'jar:file:/Users/wangzhongshan9/wzs_workspace/code/graalvm-demos/zeebe-bpmn-demo/target/lib/zeebe-bpmn-model-0.21.1.jar!/BPMN20.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
        at org.camunda.bpm.model.xml.impl.util.DomUtil$DomErrorHandler.error(DomUtil.java:201)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:138)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:306)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:4257)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaError(XSDHandler.java:4240)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument1(XSDHandler.java:2531)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(XSDHandler.java:2238)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:588)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:617)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.processJAXPSchemaSource(XMLSchemaLoader.java:789)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:606)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.findSchemaGrammar(XMLSchemaValidator.java:2710)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:2069)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:829)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:613)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3063)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:836)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:246)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:122)
        at org.camunda.bpm.model.xml.impl.util.DomUtil.parseInputStream(DomUtil.java:239)
        ... 5 more
```

**Comment by oubidar-Abderrahim** [comment]
@wangzhongshan I think the correct command is: `native-image -jar target/zeebe-bpmn-demo-1.0-SNAPSHOT.jar`
the -cp is used to indicate jar added to the classpath, not the actual App you want to create native-image for.

**Comment by oubidar-Abderrahim** [comment]
I tested it and it works, I can generate and execute the native-image. please confirm that this solved your issue.

**Comment by wangzhongshan** [comment]
It works ok with your command,but it not work when use `native-image --initialize-at-build-time -jar target/zeebe-bpmn-demo-1.0-SNAPSHOT.jar`,I  have to use `--initialize-at-build-time ` for some reason(eg. use polyglot api).
Is there any other solution?

**Comment by oubidar-Abderrahim** [comment]
the command `--initialize-at-build-time` is used to specify what classes or packages should be initialized at build time (as the name suggests) for static access. the correct way to use this flag is `--initialize-at-build-time=full.name.of.the.ClassOrPackage` (ex: `--initialize-at-build-time=com.sun.org.apache.xerces` `--initialize-at-build-time=java.awt.event.ActionEvent`).
 
Note that you can declare all classes and packages you want to initialize at build time at once separated by a comma. (ex: `--initialize-at-build-time=com.sun.org.apache.xerces,java.awt.event.ActionEvent`).

This flag shouldn't be used unless there is a need to initialize a class or package at build time. (usually, the build would fail with a message this class should be initialized at build time).

**Comment by wangzhongshan** [comment]
Ok,tks,I don't use `--initialize-at-build-time` command now.
