### ISSUE TITLE
reachability of http not triggered

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#2810]
**Describe the issue**
Using the latest GraalVM code, a HelloWorld program that contains a URL with a http resource requires 
`--enable-url-protocols=http` or otherwise will fail at runtime.
While this make sense, there might be a reachability handler that would check for this, and that is currently failing

**Steps to reproduce the issue**
Please include both build steps as well as run steps
```
import java.net.URL;

public class Hello { 

    public static void main(String[] args) throws Exception {
        System.err.println("Hello, world");
        URL url = new URL ("http://gluonhq.com");
        System.err.println("url = "+url);
    }

}

```
```
java -cp . Hello
14:57	$GRAALVM_HOME/bin/native-image -cp . Hello
14:58	./hello
```

**Describe GraalVM and your environment:**
- Head (c69eded9bb9613cbbc412559fe02c0a19c7f5ffa)
 - JDK major version: **11**
 - OS: ** Linux **
 - Architecture: **AMD64**

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
Hello, world
Exception in thread "main" java.net.MalformedURLException: Accessing an URL protocol that was not enabled. The URL protocol http is supported but not enabled by default. It must be enabled by adding the --enable-url-protocols=http option to the native-image command.
	at com.oracle.svm.core.jdk.JavaNetSubstitutions.unsupported(JavaNetSubstitutions.java:208)
	at com.oracle.svm.core.jdk.JavaNetSubstitutions.getURLStreamHandler(JavaNetSubstitutions.java:165)
	at java.net.URL.getURLStreamHandler(URL.java:70)
	at java.net.URL.<init>(URL.java:651)
	at java.net.URL.<init>(URL.java:541)
	at java.net.URL.<init>(URL.java:488)
	at Hello.main(Hello.java:7)

```

**Comment by fernando-valdez** [comment]
Hi @johanvos, thank you for reporting this.

Can you please share the version of GraalVM you used?

**Comment by johanvos** [comment]
The head version (https://github.com/oracle/graal/commit/c69eded9bb9613cbbc412559fe02c0a19c7f5ffa being the latest commit at the moment)
