### ISSUE TITLE
getdtablesize not supported on Android

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#2812]
**Describe the issue**
Applications using JMX fail at runtime on Android, due to a missing symbol:
`cannot locate symbol "getdtablesize"`

This is because `com/oracle/svm/core/posix/PosixSubstrateOperatingSystemMXBean.java` is using getdtablesize, which is not supported since Android 21. Using sysconf(_SC_OPEN_MAX) works on Android.

Also, the man page for getdtablesize recommends using sysconf(_SC_OPEN_MAX) -- see https://man7.org/linux/man-pages/man2/getdtablesize.2.html

**Steps to reproduce the issue**
```
package hello;

import com.sun.management.UnixOperatingSystemMXBean;

import java.lang.management.ManagementFactory;
import java.lang.management.OperatingSystemMXBean;

public class HelloWorld {

    private static final OperatingSystemMXBean osMxBean = ManagementFactory.getOperatingSystemMXBean();


    public static void main(String[] args) {
        System.out.println("Hello World!! " + osMxBean + ", Unix: " + (osMxBean instanceof UnixOperatingSystemMXBean));
        UnixOperatingSystemMXBean unixOsBean = (UnixOperatingSystemMXBean) osMxBean;;
        unixOsBean.getOpenFileDescriptorCount();
        System.exit(0);
    }

}
```

**Describe GraalVM and your environment:**
 - GraalVM latest master c69eded9bb9613cbbc412559fe02c0a19c7f5ffa
 - JDK major version: **11**
 - OS: **[e.g. Android]**
 - Architecture: **[e.g.: AArch64]**

```
==================== RUN TASK ====================
[SUB] --------- beginning of main
[SUB] --------- beginning of system
[SUB] V/GraalActivity( 4413): onCreate start, using Android Logging v1
[SUB] V/GraalActivity( 4413): onCreate done
[SUB] V/GraalActivity( 4413): onStart
[SUB] V/GraalActivity( 4413): onStart done
[SUB] V/GraalActivity( 4413): onResume
[SUB] V/GraalActivity( 4413): onResume done
[SUB] V/GraalActivity( 4413): surfaceCreated for com.gluonhq.helloandroid.MainActivity@2baa7b5
[SUB] V/GraalActivity( 4413): loading substrate library
[SUB] --------- beginning of crash
[SUB] E/AndroidRuntime( 4413): FATAL EXCEPTION: main
[SUB] E/AndroidRuntime( 4413): Process: hello.helloworld, PID: 4413
[SUB] E/AndroidRuntime( 4413): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "getdtablesize" referenced by "/data/app/hello.helloworld-Db4RLY2UlsTroZ5k5pqaLg==/lib/arm64/libsubstrate.so"...
[SUB] E/AndroidRuntime( 4413):  at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
[SUB] E/AndroidRuntime( 4413):  at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
[SUB] E/AndroidRuntime( 4413):  at java.lang.System.loadLibrary(System.java:1667)
[SUB] E/AndroidRuntime( 4413):  at com.gluonhq.helloandroid.MainActivity.surfaceCreated(MainActivity.java:104)
[SUB] E/AndroidRuntime( 4413):  at android.view.SurfaceView.updateSurface(SurfaceView.java:758)```

**Comment by johanvos** [comment]
See https://github.com/gluonhq/substrate/issues/761 for the original issue

**Comment by cstancu** [comment]
Fixed in https://github.com/oracle/graal/pull/2813
