### ISSUE TITLE
Static using muslc

### ISSUE THREAD

**Issue by emrul** [oracle/graal#2824]
My native images are building well so now I am experimenting with other areas - specifically building a static image.

Per instructions on the internet I've added ```--static -H:UseMuslC=bundle/``` arguments to my native image build but I get the following error:

```
Error: Could not find option 'UseMuslC'. Use -H:PrintFlags= to list all available options.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1558)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1308)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1269)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1228)
	at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1740)
```

For reference my Dockerfile looks like:
```
FROM oracle/graalvm-ce:20.2.0-java11 as build
RUN gu install native-image

RUN curl -L -o musl.tar.gz https://github.com/gradinac/musl-bundle-example/releases/download/v1.0/musl.tar.gz && \
    tar -xvzf musl.tar.gz

COPY target/myjar.jar .
COPY graal ./graal

RUN native-image \
    --no-server \
    --static \
    -H:UseMuslC=bundle/ \
    -J-Xmx10G \
    --no-fallback \
    --verbose \
    --enable-all-security-services \
    --enable-url-protocols=http,https \
    -H:ReflectionConfigurationFiles=graal/reflect-config.json \
    -H:ResourceConfigurationFiles=graal/resource-config.json \
    -H:DynamicProxyConfigurationFiles=graal/proxy-config.json \
    -H:+ReportExceptionStackTraces \
    --report-unsupported-elements-at-runtime \
    --allow-incomplete-classpath \
    -H:IncludeResources=".*" \
    -H:+TraceClassInitialization \
    -H:+PrintClassInitialization \
    --install-exit-handlers \
    -H:+AddAllCharsets \
    -H:+RemoveSaturatedTypeFlows \
    -H:IncludeResourceBundles=org.apache.xmlbeans.impl.regex.message,com.sun.org.apache.xml.internal.serializer.utils.SerializerMessages \
    -jar myjar.jar

```

**Comment by fernando-valdez** [comment]
Hello @emrul, 
On GraalVM 20.1 you were able to use the flag `-H:UseMuslC`. But GraalVM 20.2 uses a different approach. Please see this document that explains the process:
https://github.com/oracle/graal/blob/master/substratevm/StaticImages.md

**Comment by emrul** [comment]
Ah, @fernando-valdez thank you for pointing me to that!

Ok, so I've managed to get it to work without much hassle in Docker (no kidding this has been the smoothest part of my Native Image exeperience so far!).

For anyone else who wants a copy + paste for building static images, here is my Dockerfile:

```
# Note: Without JAR prefix (e.g. If given 'myjar', will append '.jar')
ARG SOURCE_FILE="myjar"

FROM oracle/graalvm-ce:20.2.0-java11 as build
RUN gu install native-image

# BEGIN PRE-REQUISITES FOR STATIC NATIVE IMAGES FOR GRAAL 20.2.0
# SEE: https://github.com/oracle/graal/blob/master/substratevm/StaticImages.md
ARG RESULT_LIB="/staticlibs"

RUN mkdir ${RESULT_LIB} && \
    curl -L -o musl.tar.gz https://musl.libc.org/releases/musl-1.2.1.tar.gz && \
    mkdir musl && tar -xvzf musl.tar.gz -C musl --strip-components 1 && cd musl && \
    ./configure --disable-shared --prefix=${RESULT_LIB} && \
    make && make install && \
    cd / && rm -rf /muscl && rm -f /musl.tar.gz \ && \
    cp /usr/lib/gcc/x86_64-redhat-linux/4.8.2/libstdc++.a ${RESULT_LIB}/lib/

ENV PATH="$PATH:${RESULT_LIB}/bin"
ENV CC="musl-gcc"

RUN curl -L -o zlib.tar.gz https://zlib.net/zlib-1.2.11.tar.gz && \
   mkdir zlib && tar -xvzf zlib.tar.gz -C zlib --strip-components 1 && cd zlib && \
   ./configure --static --prefix=${RESULT_LIB} && \
    make && make install && \
    cd / && rm -rf /zlib && rm -f /zlib.tar.gz
#END PRE-REQUISITES FOR STATIC NATIVE IMAGES FOR GRAAL 20.2.0

ARG SOURCE_JAR_DIR="target/"
ARG SOURCE_FILE
ARG GRAAL_CONFIG_DIR="graal"

COPY ${SOURCE_JAR_DIR}${SOURCE_JAR} .
COPY ${GRAAL_CONFIG_DIR} ./graal

RUN native-image \
    --no-server \
    --static \
    --libc=musl \
    -J-Xmx10G \
    --no-fallback \
    --verbose \
    --enable-all-security-services \
    --enable-url-protocols=http,https \
    -H:ReflectionConfigurationFiles=graal/reflect-config.json \
    -H:ResourceConfigurationFiles=graal/resource-config.json \
    -H:DynamicProxyConfigurationFiles=graal/proxy-config.json \
    -H:+ReportExceptionStackTraces \
    --report-unsupported-elements-at-runtime \
    --allow-incomplete-classpath \
    -H:IncludeResources=".*" \
    -H:+TraceClassInitialization \
    -H:+PrintClassInitialization \
    --install-exit-handlers \
    -H:+AddAllCharsets \
    -H:IncludeResourceBundles=org.apache.xmlbeans.impl.regex.message,com.sun.org.apache.xml.internal.serializer.utils.SerializerMessages \
    -jar ${SOURCE_FILE}.jar

```

**Comment by jamesward** [comment]
Thanks @emrul!  Note that for `ghcr.io/graalvm/graalvm-ce:21.0.0` change:
```
cp /usr/lib/gcc/x86_64-redhat-linux/4.8.2/libstdc++.a ${RESULT_LIB}/lib/
```
to:
```
cp /usr/lib/gcc/x86_64-redhat-linux/8/libstdc++.a ${RESULT_LIB}/lib/
```

**Comment by sergey-morenets** [comment]
Hi @emrul 

Thank you for the provided Dockerfile but it doesn't work for me if I use the latest GraalVM version:

`FROM ghcr.io/graalvm/graalvm-ce:java17-21.3.0 as graalvm`

I get the following error message:

```

#13 1.864 Error: Default native-compiler executable 'x86_64-linux-musl-gcc' not found via environment variable PATH
#13 1.864 Error: To prevent native-toolchain checking provide command-line option -H:-CheckToolchain
```

This executable (x86_64-linux-musl-gcc) is actually absent in my Docker image and musl-gcc is available in ${RESULT_LIB}/bin.

**Comment by sergey-morenets** [comment]
I've investigated how different GraalVM versions work with musl library.
The latest 20.x release (20.3.2) and 21.2.0 work without any issues. However 21.3.0 fails to generate native image. My assumption is that because it's  JDK 17-based. Previous versions were JDK 11-based.

**Comment by sergey-morenets** [comment]
So I finally made it working by changing the musl implementations:

```
ARG RESULT_LIB="/musl"

RUN mkdir ${RESULT_LIB} && \
    curl -L -o musl.tar.gz https://more.musl.cc/10.2.1/x86_64-linux-musl/x86_64-linux-musl-native.tgz && \
    tar -xvzf musl.tar.gz -C musl --strip-components 1 && \
    cp /usr/lib/gcc/x86_64-redhat-linux/8/libstdc++.a ${RESULT_LIB}/lib/

ENV CC=/musl/bin/gcc

RUN curl -L -o zlib.tar.gz https://zlib.net/zlib-1.2.11.tar.gz && \
    mkdir zlib && tar -xvzf zlib.tar.gz -C zlib --strip-components 1 && \
    cd zlib && ./configure --static --prefix=/musl && \
    make && make install && \
    cd / && rm -rf /zlib && rm -f /zlib.tar.gz

ENV PATH="$PATH:/musl/bin"
```

Please note, that the latest musl version (12.2.1) doesn't work correctly with GraalVM.

**Comment by schnatterer** [comment]
Thank you all for this issue and the solutions! It helped me to overcome non-functional DNS (resulting in `UnknownHostException`s) in my static image using GraalVM 22, JDK17 and Groovy.
If you're looking for a working example, a simple app that is wrapped into a static image using musl inside a Docker image, see cloudogu/groovy-cli-graal-nativeimage-micronaut-example@54a3ebd25f3b6abb7e53e2f35ed956114ef4b1d5.
