### ISSUE TITLE
[native image] drools throw error during compilation, Error: Classes that should be initialized at run time got initialized during image building

### ISSUE THREAD

**Issue by samyc1201** [oracle/graal#2827]
**Describe the issue**
I am trying to run a simple drools example and compile it into native image, but it fails at compilation time.

**Steps to reproduce the issue**
I am using Gluon plugin to build it, the extra arguments I pass in:

```
--allow-incomplete-classpath
-H:+TraceClassInitialization
--initialize-at-run-time=org.eclipse.sisu.space.SpaceModule,org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.parser.Parser,org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.ast.NullAnnotationMatching,org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.util.Util,org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.ast.NullAnnotationMatching$CheckMode
```

**Describe GraalVM and your environment:**
 - GraalVM version: graalvm-ce-java11-20.2.0-dev
 - JDK major version: 11 (use the one come with Graalvm)
 - OS: macOS Mojave 10.14.6
 - Architecture: ARM64 

**More details**

```
  [Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] Error: Classes that should be initialized at run time got initialized during image building:
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB]  org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.ast.NullAnnotationMatching$CheckMode the class was requested to be initialized at run time (from the command line). org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.ast.NullAnnotationMatching$CheckMode has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try avoiding to initialize the class that caused initialization of org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.ast.NullAnnotationMatching$CheckMode
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.ast.NullAnnotationMatching the class was requested to be initialized at run time (from the command line). org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.ast.NullAnnotationMatching has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try avoiding to initialize the class that caused initialization of org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.ast.NullAnnotationMatching
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] org.eclipse.sisu.space.SpaceModule the class was requested to be initialized at run time (from the command line). org.eclipse.sisu.space.SpaceModule has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try avoiding to initialize the class that caused initialization of org.eclipse.sisu.space.SpaceModule
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.parser.Parser the class was requested to be initialized at run time (from the command line). org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.parser.Parser has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try avoiding to initialize the class that caused initialization of org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.parser.Parser
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.util.Util the class was requested to be initialized at run time (from the command line). org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.util.Util has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try avoiding to initialize the class that caused initialization of org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.util.Util
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] 
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB]  org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.ast.NullAnnotationMatching$CheckMode the class was requested to be initialized at run time (from the command line). org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.ast.NullAnnotationMatching$CheckMode has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try avoiding to initialize the class that caused initialization of org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.ast.NullAnnotationMatching$CheckMode
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.ast.NullAnnotationMatching the class was requested to be initialized at run time (from the command line). org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.ast.NullAnnotationMatching has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try avoiding to initialize the class that caused initialization of org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.ast.NullAnnotationMatching
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] org.eclipse.sisu.space.SpaceModule the class was requested to be initialized at run time (from the command line). org.eclipse.sisu.space.SpaceModule has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try avoiding to initialize the class that caused initialization of org.eclipse.sisu.space.SpaceModule
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.parser.Parser the class was requested to be initialized at run time (from the command line). org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.parser.Parser has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try avoiding to initialize the class that caused initialization of org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.parser.Parser
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.util.Util the class was requested to be initialized at run time (from the command line). org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.util.Util has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try avoiding to initialize the class that caused initialization of org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.util.Util
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] 
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] 	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:526)
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:227)
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:732)
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:732)
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:555)
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[Wed Sep 02 15:28:10 SGT 2020][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[Wed Sep 02 15:28:11 SGT 2020][INFO] [SUB] Error: Image build request failed with exit status 1
[Wed Sep 02 15:28:11 SGT 2020][FINE] Result for compile: 1
[Wed Sep 02 15:28:11 SGT 2020][SEVERE] Process compile failed with result: 1

```

The command to compile (extracted from log):

```
/Users/incomemac/Downloads/graalvm-ce-java11-20.2.0-dev/Contents/Home/bin/native-image --report-unsupported-elements-at-runtime -Djdk.internal.lambda.eagerlyInitialize=false --no-server -H:+ExitAfterRelocatableImageWrite -H:+SharedLibrary -H:+AddAllCharsets -H:+ReportExceptionStackTraces -H:-DeadlockWatchdogExitOnTimeout -H:DeadlockWatchdogInterval=0 -H:+RemoveSaturatedTypeFlows --features=org.graalvm.home.HomeFinderFeature -H:TempDirectory=/Users/incomemac/Desktop/income-workplace/HelloFX-Webview/target/client/arm64-ios/gvm/tmp -H:EnableURLProtocols=http,https -H:+PrintAnalysisCallTree -H:Log=registerResource: -H:ReflectionConfigurationFiles=/Users/incomemac/Desktop/income-workplace/HelloFX-Webview/target/client/arm64-ios/gvm/reflectionconfig-arm64-ios.json -H:JNIConfigurationFiles=/Users/incomemac/Desktop/income-workplace/HelloFX-Webview/target/client/arm64-ios/gvm/jniconfig-arm64-ios.json -H:ResourceConfigurationFiles=/Users/incomemac/Desktop/income-workplace/HelloFX-Webview/target/client/arm64-ios/gvm/resourceconfig-arm64-ios.json -H:CompilerBackend=llvm -H:-SpawnIsolates -H:PageSize=16384 -Dsvm.targetName=iOS -Dsvm.targetArch=arm64 -H:+UseCAPCache -H:CAPCacheDir=/Users/incomemac/Desktop/income-workplace/HelloFX-Webview/target/client/arm64-ios/gvm/capcache -H:IncludeResourceBundles=org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.problem.messages,com/sun/javafx/scene/control/skin/resources/controls,com/sun/javafx/scene/control/skin/resources/controls-nt,com.sun.javafx.tk.quantum.QuantumMessagesBundle,com.sun.media.jfxmedia.MediaErrors,com.sun.webkit.graphics.Images,com.sun.webkit.LocalizedStrings,javafx.scene.web.HTMLEditorSkin -Dsvm.platform=org.graalvm.nativeimage.Platform$DARWIN_AARCH64 -cp /Users/incomemac/Desktop/income-workplace/HelloFX-Webview/target/classes:/Users/incomemac/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/Users/incomemac/.m2/repository/com/gluonhq/attach/device/4.0.7/device-4.0.7-ios.jar:/Users/incomemac/.m2/repository/com/gluonhq/attach/device/4.0.7/device-4.0.7.jar:/Users/incomemac/.m2/repository/com/gluonhq/attach/storage/4.0.7/storage-4.0.7-ios.jar:/Users/incomemac/.m2/repository/com/gluonhq/attach/storage/4.0.7/storage-4.0.7.jar:/Users/incomemac/.m2/repository/com/gluonhq/attach/util/4.0.7/util-4.0.7.jar:/Users/incomemac/.m2/repository/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar:/Users/incomemac/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar:/Users/incomemac/.m2/repository/com/google/inject/guice/4.0/guice-4.0-no_aop.jar:/Users/incomemac/.m2/repository/com/google/protobuf/protobuf-java/3.6.1/protobuf-java-3.6.1.jar:/Users/incomemac/.m2/repository/com/thoughtworks/xstream/xstream/1.4.11.1/xstream-1.4.11.1.jar:/Users/incomemac/.m2/repository/commons-codec/commons-codec/1.11/commons-codec-1.11.jar:/Users/incomemac/.m2/repository/commons-io/commons-io/2.3/commons-io-2.3.jar:/Users/incomemac/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar:/Users/incomemac/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar:/Users/incomemac/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/Users/incomemac/.m2/repository/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar:/Users/incomemac/.m2/repository/org/apache/ant/ant/1.8.4/ant-1.8.4.jar:/Users/incomemac/.m2/repository/org/apache/ant/ant-launcher/1.8.4/ant-launcher-1.8.4.jar:/Users/incomemac/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar:/Users/incomemac/.m2/repository/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.jar:/Users/incomemac/.m2/repository/org/apache/httpcomponents/httpcore/4.4.6/httpcore-4.4.6.jar:/Users/incomemac/.m2/repository/org/apache/maven/maven-aether-provider/3.3.9/maven-aether-provider-3.3.9.jar:/Users/incomemac/.m2/repository/org/apache/maven/maven-artifact/3.3.9/maven-artifact-3.3.9.jar:/Users/incomemac/.m2/repository/org/apache/maven/maven-builder-support/3.3.9/maven-builder-support-3.3.9.jar:/Users/incomemac/.m2/repository/org/apache/maven/maven-compat/3.3.9/maven-compat-3.3.9.jar:/Users/incomemac/.m2/repository/org/apache/maven/maven-core/3.3.9/maven-core-3.3.9.jar:/Users/incomemac/.m2/repository/org/apache/maven/maven-model/3.3.9/maven-model-3.3.9.jar:/Users/incomemac/.m2/repository/org/apache/maven/maven-model-builder/3.3.9/maven-model-builder-3.3.9.jar:/Users/incomemac/.m2/repository/org/apache/maven/maven-plugin-api/3.3.9/maven-plugin-api-3.3.9.jar:/Users/incomemac/.m2/repository/org/apache/maven/maven-repository-metadata/3.3.9/maven-repository-metadata-3.3.9.jar:/Users/incomemac/.m2/repository/org/apache/maven/maven-settings/3.3.9/maven-settings-3.3.9.jar:/Users/incomemac/.m2/repository/org/apache/maven/maven-settings-builder/3.3.9/maven-settings-builder-3.3.9.jar:/Users/incomemac/.m2/repository/org/apache/maven/wagon/wagon-http/3.0.0/wagon-http-3.0.0.jar:/Users/incomemac/.m2/repository/org/apache/maven/wagon/wagon-http-shared/3.0.0/wagon-http-shared-3.0.0.jar:/Users/incomemac/.m2/repository/org/apache/maven/wagon/wagon-provider-api/3.0.0/wagon-provider-api-3.0.0.jar:/Users/incomemac/.m2/repository/org/codehaus/plexus/plexus-classworlds/2.5.2/plexus-classworlds-2.5.2.jar:/Users/incomemac/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.6/plexus-component-annotations-1.6.jar:/Users/incomemac/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.21/plexus-interpolation-1.21.jar:/Users/incomemac/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.22/plexus-utils-3.0.22.jar:/Users/incomemac/.m2/repository/org/drools/drools-compiler/7.42.0.Final/drools-compiler-7.42.0.Final.jar:/Users/incomemac/.m2/repository/org/drools/drools-core/7.42.0.Final/drools-core-7.42.0.Final.jar:/Users/incomemac/.m2/repository/org/drools/drools-core-dynamic/7.42.0.Final/drools-core-dynamic-7.42.0.Final.jar:/Users/incomemac/.m2/repository/org/drools/drools-core-reflective/7.42.0.Final/drools-core-reflective-7.42.0.Final.jar:/Users/incomemac/.m2/repository/org/eclipse/aether/aether-api/1.1.0/aether-api-1.1.0.jar:/Users/incomemac/.m2/repository/org/eclipse/aether/aether-connector-basic/1.1.0/aether-connector-basic-1.1.0.jar:/Users/incomemac/.m2/repository/org/eclipse/aether/aether-impl/1.1.0/aether-impl-1.1.0.jar:/Users/incomemac/.m2/repository/org/eclipse/aether/aether-spi/1.1.0/aether-spi-1.1.0.jar:/Users/incomemac/.m2/repository/org/eclipse/aether/aether-transport-file/1.1.0/aether-transport-file-1.1.0.jar:/Users/incomemac/.m2/repository/org/eclipse/aether/aether-transport-http/1.1.0/aether-transport-http-1.1.0.jar:/Users/incomemac/.m2/repository/org/eclipse/aether/aether-transport-wagon/1.1.0/aether-transport-wagon-1.1.0.jar:/Users/incomemac/.m2/repository/org/eclipse/aether/aether-util/1.1.0/aether-util-1.1.0.jar:/Users/incomemac/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.2/org.eclipse.sisu.inject-0.3.2.jar:/Users/incomemac/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.plexus/0.3.2/org.eclipse.sisu.plexus-0.3.2.jar:/Users/incomemac/.m2/repository/org/jsoup/jsoup/1.7.2/jsoup-1.7.2.jar:/Users/incomemac/.m2/repository/org/kie/kie-api/7.42.0.Final/kie-api-7.42.0.Final.jar:/Users/incomemac/.m2/repository/org/kie/kie-ci/7.42.0.Final/kie-ci-7.42.0.Final.jar:/Users/incomemac/.m2/repository/org/kie/kie-internal/7.42.0.Final/kie-internal-7.42.0.Final.jar:/Users/incomemac/.m2/repository/org/kie/soup/kie-soup-commons/7.42.0.Final/kie-soup-commons-7.42.0.Final.jar:/Users/incomemac/.m2/repository/org/kie/soup/kie-soup-maven-integration/7.42.0.Final/kie-soup-maven-integration-7.42.0.Final.jar:/Users/incomemac/.m2/repository/org/kie/soup/kie-soup-maven-support/7.42.0.Final/kie-soup-maven-support-7.42.0.Final.jar:/Users/incomemac/.m2/repository/org/kie/soup/kie-soup-project-datamodel-api/7.42.0.Final/kie-soup-project-datamodel-api-7.42.0.Final.jar:/Users/incomemac/.m2/repository/org/kie/soup/kie-soup-project-datamodel-commons/7.42.0.Final/kie-soup-project-datamodel-commons-7.42.0.Final.jar:/Users/incomemac/.m2/repository/org/kie/soup/kie-soup-xstream/7.42.0.Final/kie-soup-xstream-7.42.0.Final.jar:/Users/incomemac/.m2/repository/org/mvel/mvel2/2.4.8.Final/mvel2-2.4.8.Final.jar:/Users/incomemac/.gluon/substrate/javafxStaticSdk/15-ea+gvm22/ios-arm64/sdk/lib/javafx-base.jar:/Users/incomemac/.gluon/substrate/javafxStaticSdk/15-ea+gvm22/ios-arm64/sdk/lib/javafx-base.jar:/Users/incomemac/.gluon/substrate/javafxStaticSdk/15-ea+gvm22/ios-arm64/sdk/lib/javafx-controls.jar:/Users/incomemac/.gluon/substrate/javafxStaticSdk/15-ea+gvm22/ios-arm64/sdk/lib/javafx-controls.jar:/Users/incomemac/.gluon/substrate/javafxStaticSdk/15-ea+gvm22/ios-arm64/sdk/lib/javafx-graphics.jar:/Users/incomemac/.gluon/substrate/javafxStaticSdk/15-ea+gvm22/ios-arm64/sdk/lib/javafx-graphics.jar:/Users/incomemac/.gluon/substrate/javafxStaticSdk/15-ea+gvm22/ios-arm64/sdk/lib/javafx-media.jar:/Users/incomemac/.gluon/substrate/javafxStaticSdk/15-ea+gvm22/ios-arm64/sdk/lib/javafx-media.jar:/Users/incomemac/.gluon/substrate/javafxStaticSdk/15-ea+gvm22/ios-arm64/sdk/lib/javafx-web.jar:/Users/incomemac/.gluon/substrate/javafxStaticSdk/15-ea+gvm22/ios-arm64/sdk/lib/javafx-web.jar:/Users/incomemac/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.26/jcl-over-slf4j-1.7.26.jar:/Users/incomemac/.m2/repository/org/slf4j/slf4j-api/1.7.26/slf4j-api-1.7.26.jar:/Users/incomemac/.m2/repository/org/sonatype/plexus/plexus-cipher/1.7/plexus-cipher-1.7.jar:/Users/incomemac/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar:/Users/incomemac/.m2/repository/xmlpull/xmlpull/1.1.3.1/xmlpull-1.1.3.1.jar:/Users/incomemac/.m2/repository/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.jar --allow-incomplete-classpath -H:+TraceClassInitialization --initialize-at-run-time=org.eclipse.sisu.space.SpaceModule,org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.parser.Parser,org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.ast.NullAnnotationMatching,org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.util.Util,org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.ast.NullAnnotationMatching$CheckMode hellofx.HelloFX
[Wed Sep 02 15:27:11 SGT 2020][FINE] Start process compile...
```

**Comment by oubidar-Abderrahim** [comment]
Can you provide a reproducer, please?

**Comment by samyc1201** [comment]
I am actually using Gluon maven plugin to build it, it abstracts away those manual command complexity. I try to copy the content below:

In the pom.xml, include:

```
<dependency>
    <groupId>org.kie</groupId>
    <artifactId>kie-ci</artifactId>
    <version>7.42.0.Final</version>
</dependency>
```

In the main method entry point, it calls:

`RuleUtil.setupDrools();`

`RuleUtil` file content:

```
package hellofx;

import org.kie.api.KieServices;
import org.kie.api.builder.KieBuilder;
import org.kie.api.builder.KieFileSystem;
import org.kie.api.builder.Message;
import org.kie.api.runtime.KieContainer;
import org.kie.api.runtime.KieSession;

public class RuleUtil {

	public static void setupDrools() {

		KieServices kieServices = KieServices.Factory.get();
		KieFileSystem kfs = kieServices.newKieFileSystem();

		kfs.write(kieServices.getResources()
				.newUrlResource(Thread.currentThread().getContextClassLoader().getResource("droolsTest.drl")));

		KieBuilder kieBuilder = kieServices.newKieBuilder(kfs).buildAll();

		if (kieBuilder.getResults().hasMessages(Message.Level.ERROR)) {
			System.out.println(kieBuilder.getResults().getMessages());
		}

		KieContainer kieContainer = kieServices.newKieContainer(kieServices.getRepository().getDefaultReleaseId());
		KieSession kieSession = kieContainer.newKieSession();

		Applicant applicant = new Applicant("David", 37, 1600000.0, 11);

		kieSession.insert(applicant);

		kieSession.fireAllRules();

		System.out.println("test rule result = " + applicant.getName());
	}

}
```

Simple drools fact:

```
package hellofx;

public class Applicant {

	private String name;
	private int age;
	private double currentSalary;
	private int experienceInYears;

	public Applicant(String name, int age, Double currentSalary, int experienceInYears) {
		this.name = name;
		this.age = age;
		this.currentSalary = currentSalary;
		this.experienceInYears = experienceInYears;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getAge() {
		return age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public Double getCurrentSalary() {
		return currentSalary;
	}

	public void setCurrentSalary(Double currentSalary) {
		this.currentSalary = currentSalary;
	}

	public int getExperienceInYears() {
		return experienceInYears;
	}

	public void setExperienceInYears(int experienceInYears) {
		this.experienceInYears = experienceInYears;
	}
}

```

`droolsTest.drl` localed at `src/main/resources`

```
import hellofx.Applicant;

rule "Suggest Manager Role"
    when
        $a : Applicant(experienceInYears > 10)
    then
        $a.setName("sam");
end
```

I run in desktop JVM, it is running without issue, so I capture metadata from tracing agent and configure in the project.

For the resource list:

```
<list>.*\\.drl$</list>
<list>.*\\.conf$</list>
<list>.*\\.mvel$</list>
<list>.*\\.rsc$</list>
<list>.*\\.props$</list>
```

For reflection list, there are a lot, attached the whole file here (I rename to txt so I can upload here), the error message doesn't look like coming from reflection, so I guess reflection config is fine:

[reflectionconfig.txt](https://github.com/oracle/graal/files/5161168/reflectionconfig.txt)

For JNI, I didn't configure any, it takes the default one.

For bundle list, there is only one:

`org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.problem.messages`

For the extra arguments I use:

```
--allow-incomplete-classpath
-H:+TraceClassInitialization
--initialize-at-run-time=org.eclipse.sisu.space.SpaceModule,org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.parser.Parser,org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.ast.NullAnnotationMatching,org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.util.Util,org.drools.compiler.shade.org.eclipse.jdt.internal.compiler.ast.NullAnnotationMatching$CheckMode
```

Below is the Gluon project zip file:

[HelloFX-Webview.zip](https://github.com/oracle/graal/files/5161215/HelloFX-Webview.zip)

I use this command to build `mvn clean client:build`.

**Comment by oubidar-Abderrahim** [comment]
I am sorry for this super late response, I could not run the project due to some issue with my mac that I couldn't fix. 
Could you please verify if this issue is still reproducible using GraalVM CE java11 21.0.0?

**Comment by solaanan** [comment]
Hello @samyc1201 , are you able to face the issue using the latest [GraalVM Community Edition](https://github.com/graalvm/graalvm-ce-builds/releases/tag/jdk-21.0.2)?

**Comment by solaanan** [comment]
Closing due to inactivity, please feel free to reopen or create a new issue if you still have issues, thank you
