### ISSUE TITLE
Quarkus native tests fail after 1b7b2c8c72dd6e3c3601f9e20705cd8b92c46f06

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#2841]
**Describe the issue**
After 1b7b2c8c72dd6e3c3601f9e20705cd8b92c46f06 quarkus is failing with:
```
Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing java.util.concurrent.ThreadLocalRandom.<clinit>() 
Parsing context: <no parsing context available> 

        at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:327)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:302)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
        at com.oracle.graal.pointsto.BigBang$1.run(BigBang.java:421)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.svm.core.util.VMError$HostedError: Error in @InjectAccessors handling of field java.util.concurrent.ThreadLocalRandom.seeder, accessors class com.oracle.svm.core.jdk.ThreadLocalRandomAccessors: found no method named set or setSeeder
        at parsing java.base@11.0.9-ea/java.util.concurrent.ThreadLocalRandom.<clinit>(ThreadLocalRandom.java:1084)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2575)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:96)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3413)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3215)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1091)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:985)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:70)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:223)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:357)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:313)
        ... 10 more
Caused by: com.oracle.svm.core.util.VMError$HostedError: Error in @InjectAccessors handling of field java.util.concurrent.ThreadLocalRandom.seeder, accessors class com.oracle.svm.core.jdk.ThreadLocalRandomAccessors: found no method named set or setSeeder
        at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
        at com.oracle.svm.hosted.phases.InjectedAccessorsPlugin.error(InjectedAccessorsPlugin.java:152)
        at com.oracle.svm.hosted.phases.InjectedAccessorsPlugin.handleField(InjectedAccessorsPlugin.java:89)
        at com.oracle.svm.hosted.phases.InjectedAccessorsPlugin.handleStoreStaticField(InjectedAccessorsPlugin.java:62)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genPutStatic(BytecodeParser.java:4965)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genPutStatic(BytecodeParser.java:4936)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5330)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3408)
        ... 22 more
Error: Image build request failed with exit status 1
```

See https://github.com/oracle/graal/pull/2840/checks?check_run_id=1102052270#step:17:122

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Build latest graal with `mx --primary-suite-path substratevm --components='Native Image' build`
2. `export JAVA_HOME=$(mx --primary-suite-path substratevm --components='Native Image' graalvm-home)`
2. `curl -L -O https://github.com/quarkusio/quarkus/archive/1.7.3.Final.tar.gz`
3. `tar xf 1.7.3.Final.tar.gz`
4. `cd quarkus-1.7.3.Final`
5. `./mvnw -e -Dquickly`
6. `./mvnw --settings .github/mvn-settings.xml -Dnative -Dnative.skip.surefire -pl integration-tests/main verify`

**Describe GraalVM and your environment:**
 - GraalVM version: **master**
 - JDK major version: **11**
 - OS: **Fedora 32**
 - Architecture: **AMD64**

**Comment by zakkak** [comment]
\cc @cstancu

**Comment by jaikiran** [comment]
I've opened https://github.com/oracle/graal/pull/2844 with a potential fix.

**Comment by cstancu** [comment]
This likely happens because `java.util.concurrent.ThreadLocalRandom` is initialized at run time, then its `<clinit>` is analyzed and the write to the  `ThreadLocalRandom.seeder` static field becomes reachable. Is there a reason why  `java.util.concurrent.ThreadLocalRandom` is (re)initialized at run time, or is there some leftover config in Quarkus? We could support a proper implementation for `setSeeder()`, i.e., store the provided value, but if `ThreadLocalRandom` is initialized at run time then it means that `ThreadLocalRandom.initialSeed()` becomes reachable at run time which brings in all the `java.security.SecureRandom` code for even the simplest images.

**Comment by zakkak** [comment]
> This likely happens because `java.util.concurrent.ThreadLocalRandom` is initialized at run time, then its `<clinit>` is analyzed and the write to the `ThreadLocalRandom.seeder` static field becomes reachable. Is there a reason why `java.util.concurrent.ThreadLocalRandom` is (re)initialized at run time, or is there some leftover config in Quarkus? 

It looks like the re-init was done to work-around the issue that 1b7b2c8c72dd6e3c3601f9e20705cd8b92c46f06 fixes (see https://github.com/quarkusio/quarkus/issues/11573) so I guess it could be removed in future releases (or applied only on GraalVM <=20.2)

\cc @stuartwdouglas @gsmet

> We could support a proper implementation for `setSeeder()`, i.e., store the provided value, but if `ThreadLocalRandom` is initialized at run time then it means that `ThreadLocalRandom.initialSeed()` becomes reachable at run time which brings in all the `java.security.SecureRandom` code for even the simplest images.

I see. Not sure what's the standard here, nor do I have a strong opinion on this. Are there any other similar cases, i.e., where image build breaks if you try to re-init a class?

**Comment by cstancu** [comment]
No, the image build should definitely not break.

**Comment by stuartwdouglas** [comment]
It sounds like the solution here is to just make this fix in Quarkus only apply to GraalVM <= 20.2?

**Comment by zakkak** [comment]
> It sounds like the solution here is to just make this fix in Quarkus only apply to GraalVM <= 20.2?

Yes that sounds like the right thing to do on the Quarkus side, but it looks like there needs to be something done on the GraalVM side as well, to avoid the build failure in similar cases.

**Comment by cstancu** [comment]
Yes, as an immediate solution you can modify Quarkus, but we'll provide a solution in GraalVM to avoid the image build crash.

**Comment by cstancu** [comment]
Fixed via https://github.com/oracle/graal/commit/665fa481c01076d86592f46f405923c824daac45. Now we have a setter for `ThreadLocalRandom.seeder` so the class can be initialized at run time. As I mentioned above, we don't initialize that class at run time by default to avoid bringing `java.security.SecureRandom` code for even the simplest images.

**Comment by zakkak** [comment]
Thank you @cstancu
