### ISSUE TITLE
Graalvm 20.2.0 Deadlock in chromeinspector.server.CommandProcessThread when debugging

### ISSUE THREAD

**Issue by Caffeine-01** [oracle/graal#2865]
Found one Java-level deadlock:
=============================
"ajp-nio-0.0.0.0-8009-exec-21":
  waiting for ownable synchronizer 0x0000000572418480, (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync),
  which is held by "chromeinspector.server.CommandProcessThread"
"chromeinspector.server.CommandProcessThread":
  waiting for ownable synchronizer 0x00000001c5e235f8, (a java.util.concurrent.locks.ReentrantLock$NonfairSync),
  which is held by "ajp-nio-0.0.0.0-8009-exec-106"
"ajp-nio-0.0.0.0-8009-exec-106":
  waiting for ownable synchronizer 0x0000000572418480, (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync),
  which is held by "chromeinspector.server.CommandProcessThread"

Java stack information for the threads listed above:
===================================================
"ajp-nio-0.0.0.0-8009-exec-21":
	at jdk.internal.misc.Unsafe.park(java.base@11.0.8/Native Method)
	- parking to wait for  <0x0000000572418480> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.8/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.8/AbstractQueuedSynchronizer.java:885)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(java.base@11.0.8/AbstractQueuedSynchronizer.java:1009)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(java.base@11.0.8/AbstractQueuedSynchronizer.java:1324)
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(java.base@11.0.8/ReentrantReadWriteLock.java:738)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$FindSourcesOperation.postVisitNotifications(org.graalvm.truffle/InstrumentationHandler.java:1419)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$Visitor.postVisit(org.graalvm.truffle/InstrumentationHandler.java:1913)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoot(org.graalvm.truffle/InstrumentationHandler.java:1080)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoots(org.graalvm.truffle/InstrumentationHandler.java:579)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.addExecutionBinding(org.graalvm.truffle/InstrumentationHandler.java:342)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.attachListener(org.graalvm.truffle/InstrumentationHandler.java:910)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.access$3300(org.graalvm.truffle/InstrumentationHandler.java:93)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$AbstractInstrumenter.attachExecutionEventListener(org.graalvm.truffle/InstrumentationHandler.java:2311)
	at com.oracle.truffle.api.instrumentation.Instrumenter.attachExecutionEventListener(org.graalvm.truffle/Instrumenter.java:88)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl$CancelHandler.enableCancel(org.graalvm.truffle/PolyglotEngineImpl.java:1239)
	- locked <0x0000000471afd9c8> (a com.oracle.truffle.polyglot.PolyglotEngineImpl$CancelHandler)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl$CancelHandler.cancel(org.graalvm.truffle/PolyglotEngineImpl.java:1223)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.ensureClosed(org.graalvm.truffle/PolyglotEngineImpl.java:975)
	- locked <0x0000000572418578> (a com.oracle.truffle.polyglot.PolyglotEngineImpl)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.ensureClosed(org.graalvm.truffle/PolyglotEngineImpl.java:942)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.close(org.graalvm.truffle/PolyglotEngineImpl.java:910)
	at org.graalvm.polyglot.Engine.close(org.graalvm.sdk/Engine.java:224)

"chromeinspector.server.CommandProcessThread":
	at jdk.internal.misc.Unsafe.park(java.base@11.0.8/Native Method)
	- parking to wait for  <0x00000001c5e235f8> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.8/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.8/AbstractQueuedSynchronizer.java:885)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(java.base@11.0.8/AbstractQueuedSynchronizer.java:917)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@11.0.8/AbstractQueuedSynchronizer.java:1240)
	at java.util.concurrent.locks.ReentrantLock.lock(java.base@11.0.8/ReentrantLock.java:267)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoot(org.graalvm.truffle/InstrumentationHandler.java:1046)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoots(org.graalvm.truffle/InstrumentationHandler.java:579)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.addExecutionBinding(org.graalvm.truffle/InstrumentationHandler.java:342)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.attachFactory(org.graalvm.truffle/InstrumentationHandler.java:906)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.access$3200(org.graalvm.truffle/InstrumentationHandler.java:93)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$AbstractInstrumenter.attachExecutionEventFactory(org.graalvm.truffle/InstrumentationHandler.java:2304)
	at com.oracle.truffle.api.instrumentation.Instrumenter.attachExecutionEventFactory(org.graalvm.truffle/Instrumenter.java:117)
	at com.oracle.truffle.api.debug.Breakpoint.assignBinding(org.graalvm.truffle/Breakpoint.java:598)
	- locked <0x00000004bffcd238> (a com.oracle.truffle.api.debug.Breakpoint)
	at com.oracle.truffle.api.debug.Breakpoint.access$500(org.graalvm.truffle/Breakpoint.java:129)
	at com.oracle.truffle.api.debug.Breakpoint$1.onExecute(org.graalvm.truffle/Breakpoint.java:565)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.notifySourceExecutedBinding(org.graalvm.truffle/InstrumentationHandler.java:795)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.addSourceExecutionBinding(org.graalvm.truffle/InstrumentationHandler.java:441)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.attachExecuteSourceListener(org.graalvm.truffle/InstrumentationHandler.java:926)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.access$3700(org.graalvm.truffle/InstrumentationHandler.java:93)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$AbstractInstrumenter.attachExecuteSourceListener(org.graalvm.truffle/InstrumentationHandler.java:2343)
	at com.oracle.truffle.api.debug.Breakpoint.install(org.graalvm.truffle/Breakpoint.java:548)
	at com.oracle.truffle.api.debug.Breakpoint.install(org.graalvm.truffle/Breakpoint.java:537)
	at com.oracle.truffle.api.debug.DebuggerSession.install(org.graalvm.truffle/DebuggerSession.java:765)
	- locked <0x00000004bffcd290> (a com.oracle.truffle.api.debug.DebuggerSession)
	at com.oracle.truffle.api.debug.DebuggerSession.install(org.graalvm.truffle/DebuggerSession.java:747)
	- locked <0x00000004bffcd290> (a com.oracle.truffle.api.debug.DebuggerSession)
	at com.oracle.truffle.tools.chromeinspector.BreakpointsHandler.lambda$createURLBreakpoint$0(BreakpointsHandler.java:95)
	at com.oracle.truffle.tools.chromeinspector.BreakpointsHandler$$Lambda$5699/0x00000007c2067040.loadedScript(Unknown Source)
	at com.oracle.truffle.tools.chromeinspector.ScriptsHandler.addLoadScriptListener(ScriptsHandler.java:92)
	at com.oracle.truffle.tools.chromeinspector.BreakpointsHandler.createURLBreakpoint(BreakpointsHandler.java:108)
	at com.oracle.truffle.tools.chromeinspector.InspectorDebugger.setBreakpointByUrl(InspectorDebugger.java:595)
	at com.oracle.truffle.tools.chromeinspector.server.InspectServerSession.doProcessCommand(InspectServerSession.java:422)
	at com.oracle.truffle.tools.chromeinspector.server.InspectServerSession.processCommand(InspectServerSession.java:263)
	at com.oracle.truffle.tools.chromeinspector.server.InspectServerSession.access$300(InspectServerSession.java:61)
	at com.oracle.truffle.tools.chromeinspector.server.InspectServerSession$CommandProcessThread.run(InspectServerSession.java:614)
...

"ajp-nio-0.0.0.0-8009-exec-106":
	at jdk.internal.misc.Unsafe.park(java.base@11.0.8/Native Method)
	- parking to wait for  <0x0000000572418480> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.8/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.8/AbstractQueuedSynchronizer.java:885)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(java.base@11.0.8/AbstractQueuedSynchronizer.java:1009)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(java.base@11.0.8/AbstractQueuedSynchronizer.java:1324)
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(java.base@11.0.8/ReentrantReadWriteLock.java:738)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$FindSourcesOperation.postVisitNotifications(org.graalvm.truffle/InstrumentationHandler.java:1419)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$Visitor.postVisit(org.graalvm.truffle/InstrumentationHandler.java:1913)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoot(org.graalvm.truffle/InstrumentationHandler.java:1080)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoot(org.graalvm.truffle/InstrumentationHandler.java:1035)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoots(org.graalvm.truffle/InstrumentationHandler.java:573)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitLoadedSourceSections(org.graalvm.truffle/InstrumentationHandler.java:391)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitLoadedSourceSections(org.graalvm.truffle/InstrumentationHandler.java:922)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.access$3600(org.graalvm.truffle/InstrumentationHandler.java:93)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$AbstractInstrumenter.visitLoadedSourceSections(org.graalvm.truffle/InstrumentationHandler.java:2337)
	at com.oracle.truffle.api.debug.SuspendableLocationFinder.findNearestBound(org.graalvm.truffle/SuspendableLocationFinder.java:114)
	at com.oracle.truffle.api.debug.SuspendableLocationFinder.findNearest(org.graalvm.truffle/SuspendableLocationFinder.java:92)
	at com.oracle.truffle.api.debug.BreakpointLocation$BreakpointSourceLocation.adjustLocation(org.graalvm.truffle/BreakpointLocation.java:241)
	at com.oracle.truffle.api.debug.Breakpoint.doResolve(org.graalvm.truffle/Breakpoint.java:583)
	at com.oracle.truffle.api.debug.DebuggerSession.resolveUnresolvedBreakpoints(org.graalvm.truffle/DebuggerSession.java:787)
	at com.oracle.truffle.api.debug.DebuggerSession.access$100(org.graalvm.truffle/DebuggerSession.java:182)
	at com.oracle.truffle.api.debug.DebuggerSession$2.create(org.graalvm.truffle/DebuggerSession.java:536)
	at com.oracle.truffle.api.instrumentation.ProbeNode.createEventNode(org.graalvm.truffle/ProbeNode.java:625)
	at com.oracle.truffle.api.instrumentation.ProbeNode.createEventChainCallback(org.graalvm.truffle/ProbeNode.java:545)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.createBindings(org.graalvm.truffle/InstrumentationHandler.java:721)
	at com.oracle.truffle.api.instrumentation.ProbeNode.lazyUpdatedImpl(org.graalvm.truffle/ProbeNode.java:377)
	at com.oracle.truffle.api.instrumentation.ProbeNode.lazyUpdate(org.graalvm.truffle/ProbeNode.java:359)
	at com.oracle.truffle.api.instrumentation.ProbeNode.onEnter(org.graalvm.truffle/ProbeNode.java:214)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:46)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:147)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:93)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(jdk.internal.vm.compiler/OptimizedCallTarget.java:503)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(jdk.internal.vm.compiler/OptimizedCallTarget.java:480)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(jdk.internal.vm.compiler/OptimizedCallTarget.java:446)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(jdk.internal.vm.compiler/OptimizedCallTarget.java:430)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(jdk.internal.vm.compiler/OptimizedCallTarget.java:393)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(jdk.internal.vm.compiler/OptimizedDirectCallNode.java:68)
....

**Comment by oubidar-Abderrahim** [comment]
Hi, could you provide a small reproducer for this deadlock?

**Comment by Caffeine-01** [comment]
It's a race condition and the initial deadlock stacktracess were user triggered. It took me a while to reproduce it easily.  Eventually the code below deadlocked, but I'm not sure if it's the same deadlock.

package graalvmDeadlock;

import com.oracle.truffle.api.debug.Breakpoint;
import com.oracle.truffle.api.debug.Debugger;
import java.io.IOException;
import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.Engine;
import org.graalvm.polyglot.Source;

public class Main {

   /**
    * @param args the command line arguments
    */
   public static void main(String[] args) throws Exception {
      for (;;) {
         var engine = Engine.newBuilder().build();
         var code = "let i = 0;\n"
                + "for(;;){\n"
                + "  i++;\n"
                + "}";
         
         new Thread(
            () -> {
               try {
                  var source = Source.newBuilder("js", code, "LoopTest").build();
                  Context.newBuilder("js").engine(engine).build().eval(source);
               } catch (IOException ex) {
                  throw new RuntimeException(ex);
               }
            },
            "JsLoop"
         ).start();
         
         
         var breakPointThread = new Thread(
               () -> {
                  try (
                     var session = Debugger.find(engine).startSession(event -> {
                     event.prepareStepInto(1);
                  })) {
                     var source = com.oracle.truffle.api.source.Source.newBuilder("js", code, "LoopTest").build();                  
                     for(;;) {
                        var breakPoint = Breakpoint.newBuilder(source)
                              .lineIs(3)
                              .resolveListener((breakpoint, section) -> {
                                 System.out.println(breakpoint + " " + section);
                              })
                              .build();
                        try {
                           Thread.sleep(9);
                        } catch (InterruptedException ex) {
                           return;
                        }
                        System.out.println("Install breakpoint");
                        session.install(breakPoint);
                        breakPoint.dispose();
                     }
                  }
               },
               "Debugger"
         );
         
         breakPointThread.start();         
         Thread.sleep(10);
         System.out.println("Engine close");
         engine.close(true);
         breakPointThread.interrupt();
      }
      
   }
   
}


Found one Java-level deadlock:
=============================
"main":
  waiting for ownable synchronizer 0x00000005e89983d8, (a java.util.concurrent.locks.ReentrantLock$NonfairSync),
  which is held by "JsLoop"
"JsLoop":
  waiting to lock monitor 0x00007fb20c007380 (object 0x00000005e88f7248, a com.oracle.truffle.api.debug.Breakpoint),
  which is held by "Debugger"
"Debugger":
  waiting for ownable synchronizer 0x00000005e89983d8, (a java.util.concurrent.locks.ReentrantLock$NonfairSync),
  which is held by "JsLoop"

Java stack information for the threads listed above:
===================================================
"main":
	at jdk.internal.misc.Unsafe.park(java.base@11.0.8/Native Method)
	- parking to wait for  <0x00000005e89983d8> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.8/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.8/AbstractQueuedSynchronizer.java:885)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(java.base@11.0.8/AbstractQueuedSynchronizer.java:917)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@11.0.8/AbstractQueuedSynchronizer.java:1240)
	at java.util.concurrent.locks.ReentrantLock.lock(java.base@11.0.8/ReentrantLock.java:267)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoot(InstrumentationHandler.java:1046)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoots(InstrumentationHandler.java:579)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.addExecutionBinding(InstrumentationHandler.java:342)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.attachListener(InstrumentationHandler.java:910)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.access$3300(InstrumentationHandler.java:93)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$AbstractInstrumenter.attachExecutionEventListener(InstrumentationHandler.java:2311)
	at com.oracle.truffle.api.instrumentation.Instrumenter.attachExecutionEventListener(Instrumenter.java:88)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl$CancelHandler.enableCancel(PolyglotEngineImpl.java:1239)
	- locked <0x00000005e95a8cb8> (a com.oracle.truffle.polyglot.PolyglotEngineImpl$CancelHandler)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl$CancelHandler.cancel(PolyglotEngineImpl.java:1223)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.ensureClosed(PolyglotEngineImpl.java:975)
	- locked <0x00000005e95a2d20> (a com.oracle.truffle.polyglot.PolyglotEngineImpl)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.ensureClosed(PolyglotEngineImpl.java:942)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.close(PolyglotEngineImpl.java:910)
	at org.graalvm.polyglot.Engine.close(Engine.java:224)
	at graalvmDeadlock.Main.main(Main.java:78)
"JsLoop":
	at com.oracle.truffle.api.debug.Breakpoint.getConditionExistsUnchanged(Breakpoint.java:488)
	- waiting to lock <0x00000005e88f7248> (a com.oracle.truffle.api.debug.Breakpoint)
	at com.oracle.truffle.api.debug.Breakpoint.access$1200(Breakpoint.java:129)
	at com.oracle.truffle.api.debug.Breakpoint$AbstractBreakpointNode.<init>(Breakpoint.java:1279)
	at com.oracle.truffle.api.debug.Breakpoint$BreakpointBeforeNode.<init>(Breakpoint.java:1145)
	at com.oracle.truffle.api.debug.Breakpoint$BreakpointNodeFactory.create(Breakpoint.java:1132)
	at com.oracle.truffle.api.instrumentation.ProbeNode.createEventNode(ProbeNode.java:625)
	at com.oracle.truffle.api.instrumentation.ProbeNode.createEventChainCallback(ProbeNode.java:545)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.createBindings(InstrumentationHandler.java:721)
	at com.oracle.truffle.api.instrumentation.ProbeNode.lazyUpdatedImpl(ProbeNode.java:377)
	at com.oracle.truffle.api.instrumentation.ProbeNode.lazyUpdate(ProbeNode.java:359)
	at com.oracle.truffle.api.instrumentation.ProbeNode.onEnter(ProbeNode.java:214)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:46)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute_generic4(JSWriteCurrentFrameSlotNodeGen.java:177)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute(JSWriteCurrentFrameSlotNodeGen.java:93)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.executeVoid(JSWriteCurrentFrameSlotNodeGen.java:343)
	at com.oracle.truffle.js.nodes.binary.DualNode.executeVoid(DualNode.java:149)
	at com.oracle.truffle.js.nodes.control.AbstractRepeatingNode.executeBody(AbstractRepeatingNode.java:73)
	at com.oracle.truffle.js.nodes.control.WhileNode$WhileDoRepeatingNode.executeRepeating(WhileNode.java:231)
	at com.oracle.truffle.api.nodes.RepeatingNode.executeRepeatingWithValue(RepeatingNode.java:106)
	at com.oracle.truffle.api.impl.DefaultLoopNode.execute(DefaultLoopNode.java:71)
	at com.oracle.truffle.js.nodes.control.WhileNode.executeVoid(WhileNode.java:178)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:91)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:84)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute_generic4(JSWriteCurrentFrameSlotNodeGen.java:177)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute(JSWriteCurrentFrameSlotNodeGen.java:93)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.executeVoid(JSWriteCurrentFrameSlotNodeGen.java:343)
	at com.oracle.truffle.js.nodes.binary.DualNode.executeVoid(DualNode.java:149)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:91)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:84)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:47)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:147)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:93)
	at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:82)
	at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:59)
	at com.oracle.truffle.js.lang.JavaScriptLanguage$1.execute(JavaScriptLanguage.java:216)
	at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:99)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:877)
	at org.graalvm.polyglot.Context.eval(Context.java:345)
	at graalvmDeadlock.Main.lambda$main$0(Main.java:38)
	at graalvmDeadlock.Main$$Lambda$27/0x00000007c008b440.run(Unknown Source)
	at java.lang.Thread.run(java.base@11.0.8/Thread.java:834)
"Debugger":
	at jdk.internal.misc.Unsafe.park(java.base@11.0.8/Native Method)
	- parking to wait for  <0x00000005e89983d8> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.8/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.8/AbstractQueuedSynchronizer.java:885)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(java.base@11.0.8/AbstractQueuedSynchronizer.java:917)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@11.0.8/AbstractQueuedSynchronizer.java:1240)
	at java.util.concurrent.locks.ReentrantLock.lock(java.base@11.0.8/ReentrantLock.java:267)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoot(InstrumentationHandler.java:1046)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoot(InstrumentationHandler.java:1035)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoots(InstrumentationHandler.java:573)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler.disposeBinding(InstrumentationHandler.java:593)
	at com.oracle.truffle.api.instrumentation.InstrumentationHandler$AbstractInstrumenter.disposeBinding(InstrumentationHandler.java:2252)
	at com.oracle.truffle.api.instrumentation.EventBinding.dispose(EventBinding.java:116)
	- locked <0x00000005e88fe118> (a com.oracle.truffle.api.instrumentation.EventBinding$Source)
	at com.oracle.truffle.api.debug.Breakpoint.uninstall(Breakpoint.java:666)
	at com.oracle.truffle.api.debug.Breakpoint.setEnabled(Breakpoint.java:279)
	- locked <0x00000005e88f7248> (a com.oracle.truffle.api.debug.Breakpoint)
	at com.oracle.truffle.api.debug.Breakpoint.dispose(Breakpoint.java:361)
	- locked <0x00000005e88f7248> (a com.oracle.truffle.api.debug.Breakpoint)
	at graalvmDeadlock.Main.lambda$main$3(Main.java:68)
	at graalvmDeadlock.Main$$Lambda$28/0x00000007c008a840.run(Unknown Source)
	at java.lang.Thread.run(java.base@11.0.8/Thread.java:834)

Found 1 deadlock.

**Comment by gilles-duboscq** [comment]
@entlicher, it this one of the instrumentation deadlock that was fixed recently? Is this resolved by d37946aec3112a015b3f205545cf993c3d0c31c2?
If that is the case then this is fixed in 20.3.0

**Comment by fernando-valdez** [comment]
@Caffeine-01 can you please test this issue using the latest GraalVM version, and share your results?

**Comment by oubidar-Abderrahim** [comment]
Closed as resolved
