### ISSUE TITLE
java.lang.ClassNotFoundException: com.sun.xml.ws.db.DatabindingFactoryImpl

### ISSUE THREAD

**Issue by sendev1** [oracle/graal#2877]
**Describe the issue**
I am using soap webservices in spring boot 2.3.1 app. I am using agent to prepare the configuration files. I executed the soap webservice when agent was running to make sure that agent collects all the information for the soap service. The image generation went fine but while running the native image I got the following error.

```
java.lang.ClassNotFoundException: com.sun.xml.ws.db.DatabindingFactoryImpl
        at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
        at java.lang.Class.forName(DynamicHub.java:1214)
        at com.sun.xml.ws.api.databinding.DatabindingFactory.newInstance(DatabindingFactory.java:131)
        at com.sun.xml.ws.client.WSServiceDelegate.buildRuntimeModel(WSServiceDelegate.java:870)
        at com.sun.xml.ws.client.WSServiceDelegate.createSEIPortInfo(WSServiceDelegate.java:899)
        at com.sun.xml.ws.client.WSServiceDelegate.addSEI(WSServiceDelegate.java:862)
        at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:451)
        at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:420)
        at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:475)
        at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:479)
        at javax.xml.ws.Service.getPort(Service.java:188)
        at com.myconfig.CxfConfig.getPublishingClient(CxfConfig.java:85)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:635)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1304)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1224)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:884)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:227)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:893)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at com.myapp.App.main(App.java:23)
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Agent to create config files
java -cp %CP% ^
  -agentlib:native-image-agent=config-merge-dir=%GRAAL_AGENT_PATH%\META-INF\native-image ^
  %MAINCLASS%

2. native image command
native-image ^
        --enable-all-security-services ^
        --enable-url-protocols=http ^
        --no-server ^
        --no-fallback ^
        --initialize-at-build-time=com.sun.jmx.remote,org.apache.xerces.util.XMLChar,org.apache.xerces.xni.NamespaceContext ^
        --initialize-at-build-time=javax.xml.datatype.DatatypeFactory,org.bouncycastle ^
        -H:Name=%ARTIFACT%-agent ^
        -H:TraceClassInitialization=true ^
        -H:+RemoveSaturatedTypeFlows ^
        -H:+ReportExceptionStackTraces ^
        -H:DeadlockWatchdogInterval=10 ^
        -H:+DeadlockWatchdogExitOnTimeout ^
        -Dspring.native.remove-yaml-support=true ^
        -Dspring.xml.ignore=true ^
        -Dspring.spel.ignore=true ^
        -Dspring.native.remove-jmx-support=true ^
        -Dspring.native.verify=true ^
        -cp %CP% %MAINCLASS%

**Describe GraalVM and your environment:**
 - GraalVM version 20.0.3 09/22 build
 - JDK major version: 8
 - OS: windows
 - Architecture: intel

**Comment by sendev1** [comment]
some more info.

I am not sure why agent did not pickup. I manually added this entry into reflect-config.json


```
{
  "name":"com.sun.xml.ws.db.DatabindingFactoryImpl",
  "allDeclaredConstructors" : true,
  "allPublicConstructors" : true,
  "allDeclaredMethods" : true,
  "allPublicMethods" : true,
  "allDeclaredClasses" : true,
  "allPublicClasses" : true
}
```

and I am seeing following error while running native image

```
java.security.PrivilegedActionException: null
        at java.security.AccessController.doPrivileged(AccessController.java:121)
        at com.sun.xml.ws.model.Injector.<clinit>(Injector.java:105)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:351)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:271)
        at com.sun.xml.ws.model.WrapperBeanGenerator.createRequestWrapperBean(WrapperBeanGenerator.java:295)
        at com.sun.xml.ws.model.RuntimeModeler.getRequestWrapperClass(RuntimeModeler.java:375)
        at com.sun.xml.ws.model.RuntimeModeler.processDocWrappedMethod(RuntimeModeler.java:801)
        at com.sun.xml.ws.model.RuntimeModeler.processMethod(RuntimeModeler.java:731)
        at com.sun.xml.ws.model.RuntimeModeler.processClass(RuntimeModeler.java:491)
        at com.sun.xml.ws.model.RuntimeModeler.buildRuntimeModel(RuntimeModeler.java:320)
        at com.sun.xml.ws.db.DatabindingImpl.<init>(DatabindingImpl.java:100)
        at com.sun.xml.ws.db.DatabindingProviderImpl.create(DatabindingProviderImpl.java:74)
        at com.sun.xml.ws.db.DatabindingProviderImpl.create(DatabindingProviderImpl.java:58)
        at com.sun.xml.ws.db.DatabindingFactoryImpl.createRuntime(DatabindingFactoryImpl.java:120)
        at com.sun.xml.ws.client.WSServiceDelegate.buildRuntimeModel(WSServiceDelegate.java:882)
        at com.sun.xml.ws.client.WSServiceDelegate.createSEIPortInfo(WSServiceDelegate.java:899)
        at com.sun.xml.ws.client.WSServiceDelegate.addSEI(WSServiceDelegate.java:862)
        at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:451)
        at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:420)
        at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:475)
        at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:479)
        at javax.xml.ws.Service.getPort(Service.java:188)
        at at com.myconfig.CxfConfig.getPublishingClient(CxfConfig.java:85)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:635)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1304)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1224)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:884)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:227)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:893)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at com.myapp.App.main(App.java:23)
Caused by: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String, [B, int, int, java.lang.ClassLoader, java.security.ProtectionDomain)
        at java.lang.Class.getMethod(DynamicHub.java:1056)
        at com.sun.xml.ws.model.Injector$3.run(Injector.java:109)
        at com.sun.xml.ws.model.Injector$3.run(Injector.java:105)
        at java.security.AccessController.doPrivileged(AccessController.java:119)
        ... 59 common frames omitted
```

**Comment by mcraj017** [comment]
@sendev1 please try --enable-all-security-services option while building native image

**Comment by cstancu** [comment]
@peter-hofer does the agent collect reflective calls from `com.sun.xml` packages?

**Comment by peter-hofer** [comment]
@cstancu it does with the more recent caller filter by @vjovanov , but did not with the old filter. It's likely that the _20.0.3 09/22 build_ is still using that old filter, but it can be overridden.

**Comment by mcraj017** [comment]
@sendev1 please provide the reproducer for this issue

**Comment by sendev1** [comment]
@mcraj017 Here is the code
**SOAP Server**
https://github.com/sendev1/cxf-server
Just download the spring boot app and start the app
This should be up and running http://localhost:8080/cxf/ws/helloworld?wsdl

**SOAP Client** - Here is where I am facing issues
https://github.com/sendev1/cxf-client
Download app
If you would like to try it as spring boot app then just start it as spring boot app and hit http://localhost:8081/hello
To create windows native image run compile.bat

There are 4 approaches I tried.

1. Apache document says use `JaxWsProxyFactoryBean` 
So when I create client in spring config as below

```
@Bean
public HelloWorldPortType helloWorldClient(Bus bus){
        final JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean();
        factory.setBus(bus);
        factory.setServiceClass(HelloWorldPortType.class);
        factory.setAddress("http://localhost:8080/cxf/ws/helloworld");
        return (HelloWorldPortType) factory.create();
    }
```

I am getting similar to following error
`nested exception is java.lang.RuntimeException: java.lang.InternalError: java.lang.NoSuchMethodError: org.apache.cxf.binding.soap.wsdl.extensions.SoapBinding.setElementType(javax.xml.namespace.QName)`

2. I thought may be @Bean is causing problem here so thought of defining public method with out @Bean in spring config as below

ApplicationConfig.java
```
public HelloWorldPortType helloWorldClient(Bus bus){
        final JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean();
        factory.setBus(bus);
        factory.setServiceClass(HelloWorldPortType.class);
        factory.setAddress("http://localhost:8080/cxf/ws/helloworld");
        return (HelloWorldPortType) factory.create();
    }

```
HelloworldController

```
private final HelloWorldPortType helloWorldClient;
public HelloController(ApplicationConfig applicationConfig, Bus bus){
        helloWorldClient = applicationConfig.helloWorldClient(bus);
    }
```

This is also causing same above exception. 

I have attached the generated image for apporach 2 here ->` src/main/resources/native-image/client-agent-without @bean but with JaxWsProxyFactoryBean.exe`

3. Ok, so `JaxWsProxyFactoryBean` did nor work and I tried the following way to create client

ApplicationConfig.java
```
@Bean
    public HelloWorldPortType helloWorldClient() throws MalformedURLException {
        final QName SERVICE = new QName("http://server.cxf.com/", "HelloWorldImplService");
        final Service service = Service.create(new URL("http://localhost:8080/cxf/ws/helloworld?wsdl"),
                SERVICE);
       return service.getPort(HelloWorldPortType.class);
    }
```

HomeController.java
public HelloController(HelloWorldPortType helloWorldClient) {
        this.helloWorldClient = helloWorldClient;
    }

The drawback for this approach is that server should be up and running otherwise client spring boot app wont even start and tracing agent wont able to collect the native-image config file

This apporach was throwing following error
`nested exception is java.lang.RuntimeException: java.lang.InternalError: java.lang.NoSuchMethodError: org.apache.cxf.binding.soap.wsdl.extensions.SoapBinding.setElementType(javax.xml.namespace.QName)`

I have attached the generated image for apporach 3 here ->` src/main/resources/native-image/client-agent-@bean with out JaxWsProxyFactoryBean.exe`

4. So may be @Bean in the above example is causing problem. So I removed @Bean from ApplicationConfig.java for the apporach 3 and created client directly inside HelloworldController

HellowordController.java
```
@RequestMapping("/hello")
    public String hello() {

        final Service service = Service.create(new URL("http://localhost:8080/cxf/ws/helloworld?wsdl"),
                SERVICE);

        final HelloWorldPortType port = service.getPort(HelloWorldPortType.class);
        port.greetings("hi");
        return "hi";
}
```
This time the native image starts and runs and it stops abruptly with out throwing any error. It does not available to serve the incoming request.

I have attached the generated image for apporach 3 here ->` src/main/resources/native-image/client-agent-client calling inside controller.exe`

**Comment by mcraj017** [comment]
@sendev1 I cannot find https://github.com/sendev1/cxf-client

**Comment by sendev1** [comment]
I had to take down the repo because looks like my work email id is used for one of commit. I am having hartime to use 2 different git account to check in code. I will attach cxf-client as zip file
[cxf-client.zip](https://github.com/oracle/graal/files/5411406/cxf-client.zip)

**Comment by mcraj017** [comment]
@sendev1 ok thanks

**Comment by mcraj017** [comment]
@sendev1 I tried to reproduce this issue, but there are no steps provided and also compile.bat is not working.
Please check the reproducer and provide clear steps and repo to reproduce this issue
thanks

**Comment by mcraj017** [comment]
closing the issue as there is no response from the user
