### ISSUE TITLE
Native image problem in Jenkins pipeline

### ISSUE THREAD

**Issue by alexh2o17** [oracle/graal#2883]
Hi, I've a problem with my native image. I want to create native images of my microservices written in scala with http4s. 

On my macbook pro everything works. I tried also in a windows pc and in other docker image, but if I try to create native image on Jenkins I've an error on last stage. I can't give a reproducible test. I used last Graalvm 20.2.0 and also last dev 20.3.0 with the same error.

I use: 

```
native-image -J-Xmx24G \
                        --allow-incomplete-classpath \
                        --no-fallback \
                        --initialize-at-build-time \
                        --enable-http \
                        --verbose \
                        -H:ConfigurationFileDirectories=src/graal \
                        -H:+ReportExceptionStackTraces \
                        -H:+ReportUnsupportedElementsAtRuntime \
                        -H:+StackTrace \
                        -H:+JNI \
                        -H:-SpawnIsolates \
                        -H:-UseServiceLoaderFeature \
                        -jar test.jar test
```

This is my error:

```
Fatal error:com.oracle.svm.core.util.VMError$HostedError: com.oracle.svm.core.util.UserError$UserException: Image heap writing found a class not seen during static analysis. Did a static field or an object referenced from a static field change during native image generation? For example, a lazily initialized cache could have been initialized during image generation, in which case you need to force eager initialization of the cache before static analysis or reset the cache using a field value recomputation.
    object: com.oracle.svm.reflect.ThreadImpl_getThreadAllocatedBytes_5fae1c01d629826c21ab7d94ef2df2ac98ffda29_220@1760102b  of class: com.oracle.svm.reflect.ThreadImpl_getThreadAllocatedBytes_5fae1c01d629826c21ab7d94ef2df2ac98ffda29_220
  reachable through:
    object: public long[] sun.management.ThreadImpl.getThreadAllocatedBytes(long[])  of class: java.lang.reflect.Method
    object: public long[] sun.management.ThreadImpl.getThreadAllocatedBytes(long[])  of class: java.lang.reflect.Method
    root: HostedField<ThreadAllocatedMemory.getThreadAllocatedBytes location: 96   AnalysisField<ThreadAllocatedMemory.getThreadAllocatedBytes accessed: false reads: false written: true>>

	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:72)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:676)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:473)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:163)
Caused by: com.oracle.svm.core.util.UserError$UserException: Image heap writing found a class not seen during static analysis. Did a static field or an object referenced from a static field change during native image generation? For example, a lazily initialized cache could have been initialized during image generation, in which case you need to force eager initialization of the cache before static analysis or reset the cache using a field value recomputation.
    object: com.oracle.svm.reflect.ThreadImpl_getThreadAllocatedBytes_5fae1c01d629826c21ab7d94ef2df2ac98ffda29_220@1760102b  of class: com.oracle.svm.reflect.ThreadImpl_getThreadAllocatedBytes_5fae1c01d629826c21ab7d94ef2df2ac98ffda29_220
  reachable through:
    object: public long[] sun.management.ThreadImpl.getThreadAllocatedBytes(long[])  of class: java.lang.reflect.Method
    object: public long[] sun.management.ThreadImpl.getThreadAllocatedBytes(long[])  of class: java.lang.reflect.Method
    root: HostedField<ThreadAllocatedMemory.getThreadAllocatedBytes location: 96   AnalysisField<ThreadAllocatedMemory.getThreadAllocatedBytes accessed: false reads: false written: true>>

	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.image.NativeImageHeap.reportIllegalType(NativeImageHeap.java:508)
	at com.oracle.svm.hosted.image.NativeImageHeap.requireType(NativeImageHeap.java:487)
	at com.oracle.svm.hosted.image.NativeImageHeap.addObjectToBootImageHeap(NativeImageHeap.java:367)
	at com.oracle.svm.hosted.image.NativeImageHeap.addObject(NativeImageHeap.java:305)
	at com.oracle.svm.hosted.image.NativeImageHeap.processAddObjectWorklist(NativeImageHeap.java:592)
	at com.oracle.svm.hosted.image.NativeImageHeap.addTrailingObjects(NativeImageHeap.java:198)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:659)
	... 6 more
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1632)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1382)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1343)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1302)
```

**Comment by fernando-valdez** [comment]
Hello @alexh2o17, thank you for reporting this.
Can you please tell me the version of Java you used on Jenkins?

**Comment by alexh2o17** [comment]
@fernando-valdez  Jenkins agent start with: 
```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
```

but during pipeline I change with graalvm java 8 version. I tried both using native image and mvn native image plugin with same error.

**Comment by fernando-valdez** [comment]
Did you use the native image agent?
You can use the native image agent to generate the necessary config files using 
`java -agentlib:native-image-agent=config-output-dir=ConfigFolderName -jar YourApp.jar` 
and try to cover most use cases in your application to make sure the agent scans most of the code.

Finally, specify the config folder when generating the native image by adding the flag: 
`-H:ConfigurationFileDirectories=ConfigFolderName`

**Comment by alexh2o17** [comment]
Yes i just used native image agent to populate config file.

**Comment by fernando-valdez** [comment]
@alexh2o17 is this a trasient issue? or happens 100% of the time on Jenkins?

**Comment by alexh2o17** [comment]
@fernando-valdez 100% only in jenkins.

**Comment by fernando-valdez** [comment]
It will be difficult to create a diagnostic without a reproducer. Is it possible to test another (sharable) project on the same environment that throws this error?

**Comment by alexh2o17** [comment]
I don't think that is possibile cause is not private project on private environment :( Other logs or informations can help??

**Comment by fernando-valdez** [comment]
These kinds of errors usually occur when application code runs already during image generation and changes static fields (or state reachable from static fields) while the image build process is running. 

So the static analysis still sees an uninitialized field, but then when the image heap is written the field contains an instance of a type that was not seen as ever been instantiated.

Can you please modify the jenkins job to only build the native image?

**Comment by alexh2o17** [comment]
HI @fernando-valdez I've little updates. I created image with last dev graalvm 2.3.0 with java11. Now image starts but have the same problems of classic jar: cold start. First call is ever really slow!

**Comment by fernando-valdez** [comment]
Hello @alexh2o17,
Can you please test the latest version of GraalVM and check if you still have a problem with the cold start?
I am glad the original issue was fixed. For that, I am closing this issue.
