### ISSUE TITLE
Regression with Micronaut gRPC: "org.graalvm.compiler.debug.GraalError: should not reach here: Intrinsic graph can only have one node with an exception edge"

### ISSUE THREAD

**Issue by ilopmar** [oracle/graal#2896]
**Describe the issue**

Our CI has detected a regression introduced by this commit https://github.com/oracle/graal/commit/9d21964f7afa35d4d4f3bece233a293b2682637e with our Micronaut gRPC test application.

**Steps to reproduce the issue**

- `git clone https://github.com/micronaut-graal-tests/micronaut-grpc-graal`
- `cd micronaut-grpc-graal`
- `git checkout graalvm-issue`
- Use GraalVM compiled from master branch
- `./build-native-image.sh`

**Describe GraalVM and your environment:**
 - GraalVM version: **Compiled from master branch. commit 9d21964f7afa35d4d4f3bece233a293b2682637e**
 - JDK major version: **8 and 11**
 - OS: **Linux Mint**
 - Architecture: **AMD64**

**More details**

```
[grpc-server:37379]    classlist:   5,873.36 ms,  2.05 GB
[grpc-server:37379]        (cap):     678.43 ms,  2.05 GB
[grpc-server:37379]        setup:   2,132.64 ms,  2.05 GB
[grpc-server:37379]     analysis:  15,630.02 ms,  2.43 GB
Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing sun.misc.Unsafe.allocateInstance(java.lang.Class) 
Parsing context:
	parsing com.oracle.svm.reflect.Unsafe_allocateInstance_5f173986d81e2cfe0b998ca594d6f585d1e638d5_899.invoke(Unknown Source)
	parsing java.lang.reflect.Method.invoke(Method.java:498)
	parsing ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:66)
	parsing ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:119)
	parsing ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:419)
	parsing ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	parsing ch.qos.logback.classic.Logger.info(Logger.java:579)
	parsing io.micronaut.runtime.Micronaut.start(Micronaut.java:150)
	parsing io.micronaut.runtime.Micronaut.run(Micronaut.java:299)
	parsing io.micronaut.runtime.Micronaut.run(Micronaut.java:285)
	parsing micronaut.example.Application.main(Application.java:8)
	parsing com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:146)
	parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:331)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:302)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultSpecialInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:368)
	at com.oracle.graal.pointsto.flow.TypeFlow$1.run(TypeFlow.java:433)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: org.graalvm.compiler.debug.GraalError: should not reach here: Intrinsic graph can only have one node with an exception edge
	at org.graalvm.compiler.debug.GraalError.shouldNotReachHere(GraalError.java:51)
	at org.graalvm.compiler.replacements.IntrinsicGraphBuilder.updateLastInstruction(IntrinsicGraphBuilder.java:182)
	at org.graalvm.compiler.replacements.IntrinsicGraphBuilder.append(IntrinsicGraphBuilder.java:212)
	at org.graalvm.compiler.nodes.graphbuilderconf.GraphBuilderContext.add(GraphBuilderContext.java:112)
	at com.oracle.svm.hosted.snippets.SubstrateGraphBuilderPlugins$15.apply(SubstrateGraphBuilderPlugins.java:581)
	at org.graalvm.compiler.nodes.graphbuilderconf.InvocationPlugin.execute(InvocationPlugin.java:169)
	at org.graalvm.compiler.replacements.IntrinsicGraphBuilder.buildGraph(IntrinsicGraphBuilder.java:339)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:192)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:357)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:313)
	... 10 more
Error: Image build request failed with exit status 1
```

Full CI log: https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/774292619

**Comment by jramirez-isc** [comment]
@ilopmar Thanks for reporting this.
I can confirm this issue in the latest snapshot. It's working fine in GraalVM 20.2.0.

**Comment by ilopmar** [comment]
Yes, with the previous commit (8a96bec03e19a666ae749cce35f8e895a6561844) it also works, no need to go back to 20.2.0 :-P

**Comment by teshull** [comment]
I pushed something to master yesterday (67bf1674bf639d165bdc8010b73881ef6e823b3f) which I believe resolves this issue. @ilopmar can you confirm things work now?

**Comment by ilopmar** [comment]
Yes, I can confirm it works now! https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/780683984

Thank you for fixing this so fast :rocket:
