### ISSUE TITLE
Native image for google-java-format fails unexpectedly after compilation

### ISSUE THREAD

**Issue by perezd** [oracle/graal#2903]
**Describe the issue**

Using graalVM-jdk11 + native image, I am unable to create a runnable native image of google-java-format.jar. Some say it has worked in environments like MacOS but I cannot get it to work in Linux/Ubuntu.

**Steps to reproduce the issue**
Steps are outlined here:
https://github.com/google/google-java-format/issues/358#issuecomment-699926534

**Describe GraalVM and your environment:**
 - GraalVM version: graalvm-ce-java11-20.2.0 (w/ native image installed)
 - JDK major version: 11
 - OS: Linux/Ubuntu
 - Architecture: AMD64

**More details**

The build works just fine but when you actually attempt to run the binary I get the following:
```
java.lang.IllegalStateException: Unknown Java version: 11
	at com.google.googlejavaformat.java.Formatter.getMajor(Formatter.java:193)
	at com.google.googlejavaformat.java.Formatter.format(Formatter.java:157)
	at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:291)
	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:267)
	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:45)
	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
```

This does not happen if I run the jar it originated from, it works as intended.

**Comment by fernando-valdez** [comment]
Hello @perezd, 

Can you please share the args you used to create the native image?

Also, did you use the `native-image-agent` to create the configuration files? if not,  you can get more information here:
https://www.graalvm.org/reference-manual/native-image/Configuration/#assisted-configuration-of-native-image-builds

**Comment by perezd** [comment]
Hi @fernando-valdez, the detailed flags and commands are outlined in a walkthrough:
https://github.com/google/google-java-format/issues/358#issuecomment-699926534

The agent was used as well.

**Comment by zapster** [comment]
Hi @perezd!

This issue is no longer present when using the latest `native-image` and `google-java-format`. I'm closing it for now, but do not hesitate to reopen it if you run into other issues.

**Comment by limbic-derek** [comment]
Appears to not be working in a new way,

Command I ran:
```
/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.3.0/Contents/Home/bin/native-image \
	-H:Class=com.google.googlejavaformat.java.Main  \
	-H:Name="google-java-format" \
	-H:IncludeResourceBundles=com.sun.tools.javac.resources.javac \
	-cp google-java-format-1.13.0-all-deps.jar \
        --allow-incomplete-classpath \
	--no-fallback 
```

Binary builds successfully, but crashes at runtime:

```
java.lang.ExceptionInInitializerError
	at com.sun.tools.javac.file.BaseFileManager.createLocations(BaseFileManager.java:115)
	at com.sun.tools.javac.file.BaseFileManager.<init>(BaseFileManager.java:76)
	at com.sun.tools.javac.file.JavacFileManager.<init>(JavacFileManager.java:144)
	at com.google.googlejavaformat.java.JavaInput.buildToks(JavaInput.java:352)
	at com.google.googlejavaformat.java.JavaInput.buildToks(JavaInput.java:334)
	at com.google.googlejavaformat.java.JavaInput.<init>(JavaInput.java:276)
	at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:280)
	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:267)
	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:45)
	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.lang.NullPointerException
	at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:75)
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
	at com.sun.tools.javac.file.Locations.<clinit>(Locations.java:139)
	... 16 more
```

**Comment by perezd** [comment]
Appears to not be working in a new way,

Command I ran:
```
/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.3.0/Contents/Home/bin/native-image \
	-H:Class=com.google.googlejavaformat.java.Main  \
	-H:Name="google-java-format" \
	-H:IncludeResourceBundles=com.sun.tools.javac.resources.javac \
	-cp google-java-format-1.13.0-all-deps.jar \
        --allow-incomplete-classpath \
	--no-fallback 
```

Binary builds successfully, but crashes at runtime:

```
java.lang.ExceptionInInitializerError
	at com.sun.tools.javac.file.BaseFileManager.createLocations(BaseFileManager.java:115)
	at com.sun.tools.javac.file.BaseFileManager.<init>(BaseFileManager.java:76)
	at com.sun.tools.javac.file.JavacFileManager.<init>(JavacFileManager.java:144)
	at com.google.googlejavaformat.java.JavaInput.buildToks(JavaInput.java:352)
	at com.google.googlejavaformat.java.JavaInput.buildToks(JavaInput.java:334)
	at com.google.googlejavaformat.java.JavaInput.<init>(JavaInput.java:276)
	at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:280)
	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:267)
	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:45)
	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.lang.NullPointerException
	at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:75)
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
	at com.sun.tools.javac.file.Locations.<clinit>(Locations.java:139)
	... 16 more
```

**Comment by zapster** [comment]
hi @perezd and thanks for getting back on this!

This is a valid `NullPointerException` (although I agree it is not obvious)! See the code at [`com.sun.tools.javac.file.Locations.<clinit>(Locations.java:139)`](https://github.com/openjdk/jdk/blob/jdk-17-ga/src/jdk.compiler/share/classes/com/sun/tools/javac/file/Locations.java#L137):

```java
static final Path javaHome = FileSystems.getDefault().getPath(System.getProperty("java.home"));
 ```

Since the `java.home` property is not set by default in native executables, the result is an NPE.

Explicitly setting the property fixes the issue:

```
./google-java-format-1.11.0-all-deps -Djava.home=$GRAALVM_HOME --fix-imports-only Hello.java
```

Another option is to build the native executable with `--initialize-at-build-time=com.sun.tools.javac.file.Locations`. That way, the property available at image generation time (i.e., the java home that is driving your native-image tool) will be baked into to native executable.

Which solution is the right one depends very much on your use-case.

Hope that helps.
