### ISSUE TITLE
Compilation fails with llvm backend: `ImageSingletons do not contain key org.graalvm.home.HomeFinder`

### ISSUE THREAD

**Issue by pkesseli** [oracle/graal#2919]
**Describe the issue**
Compiling a simple hello world program using the LLVM back-end issues the following error: `ImageSingletons do not contain key org.graalvm.home.HomeFinder`

**Steps to reproduce the issue**
In Docker `ubuntu:latest`:
1. `wget https://github.com/graalvm/graalvm-ce-dev-builds/releases/download/20.3.0-dev-20201013_0215/graalvm-ce-java11-linux-amd64-dev.tar.gz`
2. `export PATH=$PATH:~/graalvm-ce-java11-20.3.0-dev/bin`
3. `gu install llvm-toolchain native-image`
4. `apt-get install -y openjdk-8-jdk openjdk-11-jdk git gradle maven build-essential clang libz-dev llvm zlib1g-dev`
5. `native-image -H:CompilerBackend=llvm -cp classes ch.kesseli.helloworld.HelloWorld`

**Describe GraalVM and your environment:**
 - GraalVM version: 20.3.0-dev-20201013_0215
 - JDK: openjdk version "11.0.8" 2020-07-14
 - OS: Docker `ubuntu:latest`
 - Architecture: AMD64

**More details**
The same build passes fine if `-H:CompilerBackend=llvm` is omitted.
```
# native-image -H:CompilerBackend=llvm -cp classes ch.kesseli.helloworld.HelloWorld
[ch.kesseli.helloworld.helloworld:2139]    classlist:   3,493.37 ms,  0.96 GB
[ch.kesseli.helloworld.helloworld:2139]        (cap):     994.69 ms,  0.96 GB
[ch.kesseli.helloworld.helloworld:2139]        setup:   3,175.62 ms,  0.96 GB
[ch.kesseli.helloworld.helloworld:2139]     (clinit):     432.40 ms,  1.12 GB
[ch.kesseli.helloworld.helloworld:2139]   (typeflow):  20,129.87 ms,  1.12 GB
[ch.kesseli.helloworld.helloworld:2139]    (objects):  20,074.14 ms,  1.12 GB
[ch.kesseli.helloworld.helloworld:2139]   (features):   1,917.48 ms,  1.12 GB
[ch.kesseli.helloworld.helloworld:2139]     analysis:  43,096.42 ms,  1.12 GB
[ch.kesseli.helloworld.helloworld:2139]     universe:     879.89 ms,  1.12 GB
[ch.kesseli.helloworld.helloworld:2139]      (parse):   5,551.83 ms,  1.03 GB
[ch.kesseli.helloworld.helloworld:2139]     (inline):   6,642.44 ms,  1.24 GB
[ch.kesseli.helloworld.helloworld:2139]    (compile):   2,021.13 ms,  1.23 GB
[ch.kesseli.helloworld.helloworld:2139]      compile:  14,432.44 ms,  1.23 GB
4 fatal errors detected:
Fatal error:org.graalvm.compiler.graph.GraalGraphError: com.oracle.svm.core.util.UserError$UserException: ImageSingletons do not contain key org.graalvm.home.HomeFinder
        at node: 6|Conditional { stamp=i32 [0 - 1] ?0000000000000001,  }
        at method: void com.oracle.svm.core.graal.snippets.StackOverflowCheckSnippets.throwCachedStackOverflowError()  [Direct call from void FunctionPointerLogHandler.fatalError()]
        at com.oracle.svm.core.graal.llvm.NodeLLVMBuilder.doBlock(NodeLLVMBuilder.java:291)
        at com.oracle.svm.core.graal.llvm.SubstrateLLVMBackend.generate(SubstrateLLVMBackend.java:146)
        at com.oracle.svm.core.graal.llvm.SubstrateLLVMBackend.emitLLVM(SubstrateLLVMBackend.java:122)
        at com.oracle.svm.core.graal.llvm.SubstrateLLVMBackend.emitBackEnd(SubstrateLLVMBackend.java:102)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:146)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:130)
        at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:986)
        at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:948)
        at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:263)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.oracle.svm.core.util.UserError$UserException: ImageSingletons do not contain key org.graalvm.home.HomeFinder
        at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
        at com.oracle.svm.hosted.ImageSingletonsSupportImpl$HostedManagement.doLookup(ImageSingletonsSupportImpl.java:119)
        at com.oracle.svm.hosted.ImageSingletonsSupportImpl.lookup(ImageSingletonsSupportImpl.java:44)
        at org.graalvm.sdk/org.graalvm.nativeimage.ImageSingletons.lookup(ImageSingletons.java:86)
        at org.graalvm.sdk/org.graalvm.home.HomeFinder.getInstance(HomeFinder.java:99)
        at com.oracle.svm.core.graal.llvm.util.LLVMToolchain.getLLVMBinDir(LLVMToolchain.java:101)
        at com.oracle.svm.core.graal.llvm.util.LLVMToolchain.runLLVMCommand(LLVMToolchain.java:44)
        at com.oracle.svm.core.graal.llvm.LLVMFeature$LLVMVersionChecker.getLLVMVersion(LLVMFeature.java:147)
        at com.oracle.svm.core.graal.llvm.LLVMFeature$LLVMVersionChecker.<clinit>(LLVMFeature.java:135)
        at com.oracle.svm.core.graal.llvm.LLVMGenerator.emitConditionalMove(LLVMGenerator.java:641)
        at com.oracle.svm.core.graal.llvm.NodeLLVMBuilder.emitConditional(NodeLLVMBuilder.java:395)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.calc.ConditionalNode.generate(ConditionalNode.java:269)
        at com.oracle.svm.core.graal.llvm.NodeLLVMBuilder.emitNode(NodeLLVMBuilder.java:327)
        at com.oracle.svm.core.graal.llvm.NodeLLVMBuilder.doBlock(NodeLLVMBuilder.java:287)
        ... 15 more
Fatal error:org.graalvm.compiler.graph.GraalGraphError: java.lang.NoClassDefFoundError: Could not initialize class com.oracle.svm.core.graal.llvm.LLVMFeature$LLVMVersionChecker
        at node: 31|Conditional { stamp=i32 [0 - 1] ?0000000000000001,  }
        at method: void com.oracle.svm.core.thread.Safepoint.enterSlowPathSafepointCheck()  [Direct call from void FunctionPointerLogHandler.fatalError()]
        at com.oracle.svm.core.graal.llvm.NodeLLVMBuilder.doBlock(NodeLLVMBuilder.java:291)
        at com.oracle.svm.core.graal.llvm.SubstrateLLVMBackend.generate(SubstrateLLVMBackend.java:146)
        at com.oracle.svm.core.graal.llvm.SubstrateLLVMBackend.emitLLVM(SubstrateLLVMBackend.java:122)
        at com.oracle.svm.core.graal.llvm.SubstrateLLVMBackend.emitBackEnd(SubstrateLLVMBackend.java:102)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:146)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:130)
        at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:986)
        at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:948)
        at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:263)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.oracle.svm.core.graal.llvm.LLVMFeature$LLVMVersionChecker
        at com.oracle.svm.core.graal.llvm.LLVMGenerator.emitConditionalMove(LLVMGenerator.java:641)
        at com.oracle.svm.core.graal.llvm.NodeLLVMBuilder.emitConditional(NodeLLVMBuilder.java:395)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.calc.ConditionalNode.generate(ConditionalNode.java:269)
        at com.oracle.svm.core.graal.llvm.NodeLLVMBuilder.emitNode(NodeLLVMBuilder.java:327)
        at com.oracle.svm.core.graal.llvm.NodeLLVMBuilder.doBlock(NodeLLVMBuilder.java:287)
        ... 15 more
Fatal error:org.graalvm.compiler.graph.GraalGraphError: java.lang.NoClassDefFoundError: Could not initialize class com.oracle.svm.core.graal.llvm.LLVMFeature$LLVMVersionChecker
        at node: 119|Conditional { stamp=i32 [-1 - 2] ?0000000000000002,  }
        at method: int com.oracle.svm.core.graal.snippets.CEntryPointSnippets.initializeIsolate(CEntryPointCreateIsolateParameters)  [Direct call from IsolateThread CEntryPointBuiltins.createIsolate()]
        at com.oracle.svm.core.graal.llvm.NodeLLVMBuilder.doBlock(NodeLLVMBuilder.java:291)
        at com.oracle.svm.core.graal.llvm.SubstrateLLVMBackend.generate(SubstrateLLVMBackend.java:146)
        at com.oracle.svm.core.graal.llvm.SubstrateLLVMBackend.emitLLVM(SubstrateLLVMBackend.java:122)
        at com.oracle.svm.core.graal.llvm.SubstrateLLVMBackend.emitBackEnd(SubstrateLLVMBackend.java:102)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:146)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:130)
        at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:986)
        at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:948)
        at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:263)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.oracle.svm.core.graal.llvm.LLVMFeature$LLVMVersionChecker
        at com.oracle.svm.core.graal.llvm.LLVMGenerator.emitConditionalMove(LLVMGenerator.java:641)
        at com.oracle.svm.core.graal.llvm.NodeLLVMBuilder.emitConditional(NodeLLVMBuilder.java:395)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.calc.ConditionalNode.generate(ConditionalNode.java:269)
        at com.oracle.svm.core.graal.llvm.NodeLLVMBuilder.emitNode(NodeLLVMBuilder.java:327)
        at com.oracle.svm.core.graal.llvm.NodeLLVMBuilder.doBlock(NodeLLVMBuilder.java:287)
        ... 15 more
Fatal error:org.graalvm.compiler.graph.GraalGraphError: java.lang.NoClassDefFoundError: Could not initialize class com.oracle.svm.core.graal.llvm.LLVMFeature$LLVMVersionChecker
        at node: 42|Conditional { stamp=i32 [0 - 1] ?0000000000000001,  }
        at method: void com.oracle.svm.core.thread.Safepoint.enterSlowPathTransitionFromNativeToNewStatus(int)  [Direct call from IsolateThread IsolateEnterStub.CEntryPointBuiltins_attachThread_5e4ff7ed3f8f48e5e8436a4175371632ade676a8(Isolate)]
        at com.oracle.svm.core.graal.llvm.NodeLLVMBuilder.doBlock(NodeLLVMBuilder.java:291)
        at com.oracle.svm.core.graal.llvm.SubstrateLLVMBackend.generate(SubstrateLLVMBackend.java:146)
        at com.oracle.svm.core.graal.llvm.SubstrateLLVMBackend.emitLLVM(SubstrateLLVMBackend.java:122)
        at com.oracle.svm.core.graal.llvm.SubstrateLLVMBackend.emitBackEnd(SubstrateLLVMBackend.java:102)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:146)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:130)
        at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:986)
        at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:948)
        at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:263)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.oracle.svm.core.graal.llvm.LLVMFeature$LLVMVersionChecker
        at com.oracle.svm.core.graal.llvm.LLVMGenerator.emitConditionalMove(LLVMGenerator.java:641)
        at com.oracle.svm.core.graal.llvm.NodeLLVMBuilder.emitConditional(NodeLLVMBuilder.java:395)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.calc.ConditionalNode.generate(ConditionalNode.java:269)
        at com.oracle.svm.core.graal.llvm.NodeLLVMBuilder.emitNode(NodeLLVMBuilder.java:327)
        at com.oracle.svm.core.graal.llvm.NodeLLVMBuilder.doBlock(NodeLLVMBuilder.java:287)
        ... 15 more
Error: Image build request failed with exit status 1
```

**Comment by fernando-valdez** [comment]
Hello @pkesseli,
Thanks for reporting this issue. I will take a look at it and will let you know if I have any questions

**Comment by jespertheend** [comment]
Did anyone find a workaround for this?

**Comment by fernando-valdez** [comment]
Hello @pkesseli and @jespertheend. There is a fix [available](https://github.com/oracle/graal/commit/1b92af41014cabe0ddfc646cc7394e51ea64476d). Please try the latest version of GraalVM. 
Please feel free to reopen this ticket if you find the same issue again
