### ISSUE TITLE
Native Image fails if /tmp is mounted with noexec

### ISSUE THREAD

**Issue by ddimtirov** [oracle/graal#2921]
**Describe the issue**

Graal Native Image fails with exception on RHEL7 when the `/tmp` directory is mounted as `noexec`.
This is our new company standard, and it's a royal pain to get an exception.
Please consider adding an option to put the executable files in user-specified location.

**Steps to reproduce the issue**
1. Start with stock RHEL7
1. Edit `/etc/fstab` 
1. Update as follows: 
```
< tmpfs /tmp    tmpfs   defaults,nodev,nosuid,exec,rootcontext=system_u:object_r:tmp_t:s0       0       0
< /dev/mapper/vg_root-lv_var_tmp        /var/tmp        xfs     defaults,nodev,exec,nosuid      0       0
---
> tmpfs /tmp    tmpfs   defaults,nodev,nosuid,noexec,rootcontext=system_u:object_r:tmp_t:s0     0       0 
> /dev/mapper/vg_root-lv_var_tmp        /var/tmp        xfs     defaults,nodev,noexec,nosuid    0       0 
```

Run ni - it will fail with:
```
[fixer:3435640]    classlist:   6,118.45 ms,  0.96 GB
[fixer:3435640]        (cap):     771.85 ms,  0.96 GB
[fixer:3435640]        setup:   2,500.13 ms,  0.96 GB
Fatal error:com.oracle.svm.core.util.VMError$HostedError: java.io.IOException: Cannot run program "/tmp/SVM-977745275151305999/AArch64LibCHelperDirectives" (in directory "/tmp/SVM-977745275151305999"): error=13, Permission denied
        at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:72)
        at com.oracle.svm.hosted.c.CAnnotationProcessor.makeQuery(CAnnotationProcessor.java:126)
        at com.oracle.svm.hosted.c.CAnnotationProcessor.process(CAnnotationProcessor.java:102)
        at com.oracle.svm.hosted.c.NativeLibraries.finish(NativeLibraries.java:526)
        at com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1539)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1036)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:868)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:553)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.io.IOException: Cannot run program "/tmp/SVM-977745275151305999/AArch64LibCHelperDirectives" (in directory "/tmp/SVM-977745275151305999"): error=13, Permission denied
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at com.oracle.svm.hosted.c.CAnnotationProcessor.makeQuery(CAnnotationProcessor.java:117)
        ... 13 more
Caused by: java.io.IOException: error=13, Permission denied
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 15 more
Error: Image build request failed with exit status 1
```

**Comment by ddimtirov** [comment]
Fixed by passing `-H:TempDirectory=<path>`, but the compilation slowed to a crawl - 8min vs ~2min.

Nevertheless, the setting exists, and smart enough build tool should be able to take advantage of `/tmp` when mapped as executable, while using a fallback when it is not.

Ideally though, I hope it is possible to eliminate the need for executable `/tmp`, or provide a setting for only executable files (right now the new `tmp` dir contains a few minuscule executables, and one hige `.o` file).

**Comment by christf** [comment]
the workaround does not work for me. For now I remount /tmp with exec. Obviously this is a problem.
