### ISSUE TITLE
GraalVM native image runtime issue for Hadoop APIs: No LoginModule found for com.sun.security.auth.module.UnixLoginModule / NTLoginModule

### ISSUE THREAD

**Issue by zcui001** [oracle/graal#2937]
GraalVM and environment:

OS: Red Hat Enterprise Linux Server release 6.4 (Santiago)
OS: Windows 10
GraalVM version 20.1.0  CE JDK 11 

Issue: 
GraalVM native image runtime failed for Hadoop APIs:
Linux error: No LoginModule found for com.sun.security.auth.module.UnixLoginModule
Windows error: No LoginModule found for com.sun.security.auth.module.NTLoginModule

Steps to reproduce the issue
1. Create a GraalVM native image maven project to build an executable.

2. Add Hadoopdependencies:
   ```
     <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-common</artifactId>
            <version>2.7.3</version>
            <exclusions>
                <exclusion>
                    <groupId>jdk.tools</groupId>
                    <artifactId>jdk.tools</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
  

3. Add below java code:


```
import org.apache.hadoop.security.UserGroupInformation;

    public static void main(String[] args) {

        try {
            UserGroupInformation.loginUserFromSubject(null);
        } catch (IOException e) {
            e.printStackTrace();
        }
}

```

4. Run the code in GraalVM with JVM arguments: "-agentlib:native-image-agent=config-output-dir=native.conf". It would work fine and generated a few .json files in native.conf dir. Then use those .jsons and the below native-image.properties to build the native image:
Args = --no-fallback \
  --enable-http --enable-https --enable-all-security-services \
  -H:GenerateDebugInfo=1 -H:-DeleteLocalSymbols \
  -H:IncludeResourceBundles=sun.security.util.Resources \
  -H:+ReportExceptionStackTraces

5. On Linux, the build succeeds but runtime fails with below error:
java.io.IOException: failure to login
        at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:824)
Caused by: javax.security.auth.login.LoginException: No LoginModule found for com.sun.security.auth.module.UnixLoginModule
        at javax.security.auth.login.LoginContext.invoke(LoginContext.java:710)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:665)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:663)
        at java.security.AccessController.doPrivileged(AccessController.java:146)
        at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:663)
        at javax.security.auth.login.LoginContext.login(LoginContext.java:574)
        at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:799)
        ... 1 more

6. On Windows, the build succeeds but runtime fails with similar error: 
java.io.IOException: failure to login
        at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:824)
Caused by: javax.security.auth.login.LoginException: No LoginModule found for com.sun.security.auth.module.NTLoginModule
        at javax.security.auth.login.LoginContext.invoke(LoginContext.java:710)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:665)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:663)
        at java.security.AccessController.doPrivileged(AccessController.java:146)
        at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:663)
        at javax.security.auth.login.LoginContext.login(LoginContext.java:574)
        at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:799)
        ... 1 more

**Comment by zcui001** [comment]
The above one line java code will reproduce the issue. This issue was observed in a real scenario where we try to call Apache Parquet API (based on Hadoop Core API) to write parquet files. Below is how to reproduce in this real example issue besides the same steps above.
1) Add Apache Parquet maven dependencies:
```
        <dependency>
            <groupId>org.apache.parquet</groupId>
            <artifactId>parquet-column</artifactId>
            <version>${apache.parquet.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.parquet</groupId>
            <artifactId>parquet-avro</artifactId>
            <version>${apache.parquet.version}</version>
        </dependency>

```

2) Add below java code:
    
```
import org.apache.parquet.column.ParquetProperties;
import org.apache.parquet.example.data.Group;
import org.apache.parquet.hadoop.ParquetFileWriter;
import org.apache.parquet.hadoop.ParquetWriter;
import org.apache.parquet.hadoop.example.GroupWriteSupport;
import org.apache.parquet.schema.MessageType;
import java.io.IOException;
import static org.apache.parquet.hadoop.metadata.CompressionCodecName.UNCOMPRESSED;
import static org.apache.parquet.schema.MessageTypeParser.parseMessageType;

        Configuration conf = new Configuration();
        Path parquetFile = new Path("c:\\temp\\test.parquet");

        MessageType schema = parseMessageType(
                "message test { "
                        + "optional int32 int32_field; "
                        + "} ");
        GroupWriteSupport.setSchema(schema, conf);

        try {
            ParquetWriter<Group> zecwriter = new ParquetWriter<Group>(
                    parquetFile,
                    ParquetFileWriter.Mode.OVERWRITE,
                    new GroupWriteSupport(),
                    UNCOMPRESSED, 1024, 1024, 512, true, false, ParquetProperties.WriterVersion.PARQUET_1_0, conf);
        } catch (IOException e) {
            e.printStackTrace();
        }

```

**Comment by zcui001** [comment]
To reproduce the issue on Windows, you need Hadoop winutils.exe 
1) Download winutils.exe from https://github.com/steveloughran/winutils/tree/master/hadoop-2.7.1/bin and save to local drive: C:\hadoop-2.7.1\bin
2) set env var: set HADOOP_HOME=c:\hadoop-2.7.1
3) Run/Build the above code on Windows

**Comment by oubidar-Abderrahim** [comment]
I see that you're using the agent to generate the config files, but where do you specify those files to the native image?

**Comment by oubidar-Abderrahim** [comment]
I created a maven project with the Hadoop dependency and the main method you suggested and was able to run it, generate the native image and execute it without issues

I used ` java -agentlib:native-image-agent=config-merge-dir=src/main/resources/META-INF/native-image/com/oracle/example -jar target/Example-1.0-SNAPSHOT-jar-with-dependencies.jar` to generate the config files and `native-image --no-fallback --enable-http --enable-https --enable-all-security-services -H:GenerateDebugInfo=1 -H:-DeleteLocalSymbols -H:IncludeResourceBundles=sun.security.util.Resources -H:+ReportExceptionStackTraces --no-server -H:IncludeResourceBundles=sun.security.util.AuthResources -H:ConfigurationFileDirectories=src/main/resources/META-INF/native-image/com/oracle/example -jar target/Example-1.0-SNAPSHOT-jar-with-dependencies.jar` to generate the native image

please try with this command and let me know if it does fix the issue

**Comment by zcui001** [comment]
@oubidar-Abderrahim Abderrahim
Thanks so much your quick response! I tried with your command and still got the same error. Just wanted to confirm: which GraalVM version do you use? (I am using CE  20.1.0 for Java 11).

**Comment by oubidar-Abderrahim** [comment]
@zcui001 yes I am using GraalVM CE 20.1.0 for Java 11 and I am testing on Ubuntu 18.04
I am assuming if it was reproducible in RedHat it should be on Ubuntu. before thinking about OS let make sure we're using the same reproducer:

My Main.java is : 
```
package com.oracle.example;

import org.apache.hadoop.security.UserGroupInformation;
import java.io.IOException;

public class Main {
    public static void main(String[] args) {

        try {
            UserGroupInformation.loginUserFromSubject(null);
            System.out.println("No Exception");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```
my pom.xml: 
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.oracle</groupId>
    <artifactId>Example</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
        	<groupId>org.apache.hadoop</groupId>
         	<artifactId>hadoop-common</artifactId>
         	<version>2.7.3</version>
         	<exclusions>
             		<exclusion>
                 		<groupId>jdk.tools</groupId>
                 		<artifactId>jdk.tools</artifactId>
             		</exclusion>
         	</exclusions>
     	</dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.1.1</version>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>com.oracle.example.Main</mainClass>
                        </manifest>
                    </archive>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```
This looks similar to what you provided, right?

**Comment by zcui001** [comment]
@oubidar-Abderrahim yes, it looks similar, except for using 11 as maven compiler version as I'm using GraalVM JDK 11. I'm going to give a try on Ubuntu. 

```
<maven.compiler.source>11</maven.compiler.source>
<maven.compiler.target>11</maven.compiler.target>
```

**Comment by oubidar-Abderrahim** [comment]
Okay, I was able to get the exception when specifying 
```
<maven.compiler.source>11</maven.compiler.source>
<maven.compiler.target>11</maven.compiler.target> 
```
instead of 
```
<maven.compiler.source>1.8</maven.compiler.source>
<maven.compiler.target>1.8</maven.compiler.target>
```

**Comment by zcui001** [comment]
I also tried with 1.8 as maven compiler version, but got the same runtime error. I'm going to try the same on Ubuntu.

**Comment by oubidar-Abderrahim** [comment]
@zcui001 I think the issue is in `UnixLoginModule` (or `NTLoginModule` if you're on Windows) not being picked up by the agent.

Could you add 
```
{
  "name":"com.sun.security.auth.module.UnixLoginModule",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
```
to the `reflect-config.json` file and generate the native-image again? let me know if it worked

**Comment by zcui001** [comment]
@oubidar-Abderrahim yes, it works now! Thanks so much for your help!!

**Comment by smurugu** [comment]
> Okay, I was able to get the exception when specifying
> 
> ```
> <maven.compiler.source>11</maven.compiler.source>
> <maven.compiler.target>11</maven.compiler.target> 
> ```
> 
> instead of
> 
> ```
> <maven.compiler.source>1.8</maven.compiler.source>
> <maven.compiler.target>1.8</maven.compiler.target>
> ```

I believe Hadoop including version 3.x supports only JDK 8 although you can run the compiled jar file in JDK 11. Is it possible to run NamedNode, DataNode applications in GraalVM
