### ISSUE TITLE
"Code that was considered unreachable by closed-world analysis was reached" when using --initialize-at-build-time

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#2938]
**Describe the issue**
Native image throws exception about unreachable code when using `--initialize-at-build-time`.

**Steps to reproduce the issue**
```
git clone git@github.com:oracle/graal.git --depth 1
cd graal
mx --primary-suite-path substratevm --components='Native Image' build
mkdir test
cd test

cat <<EOF > Main.java
import java.security.SecureRandom;

public class Main {
    public static void main(String[] args) {
        System.out.println("Hello " + Random.rnd.nextInt());
    }
}

class Random {
    public static final SecureRandom rnd = new SecureRandom();
}
EOF

cat <<EOF > SubstMain.java
import java.security.SecureRandom;

import com.oracle.svm.core.annotate.Alias;
import com.oracle.svm.core.annotate.RecomputeFieldValue;
import com.oracle.svm.core.annotate.TargetClass;

@TargetClass(className = "Random")
final class SubstMain {
    @Alias
    @RecomputeFieldValue(kind = RecomputeFieldValue.Kind.NewInstance)
    public static SecureRandom rnd;
}
EOF

javac -cp ./:../sdk/latest_graalvm_home/lib/svm/builder/svm.jar *.java
../sdk/latest_graalvm_home/bin/native-image --initialize-at-build-time Main
./main
Fatal error: unhandled exception in isolate 0x7f4c20e00000: com.oracle.svm.core.jdk.UnsupportedFeatureError: Code that was considered unreachable by closed-world analysis was reached. The call to java.util.Random.nextInt() is not reachable.
    at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:87)
    at com.oracle.svm.core.snippets.SnippetRuntime.unsupportedFeature(SnippetRuntime.java:153)
    at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:76)
```

**Describe GraalVM and your environment:**
 - GraalVM version: **master (aa323f54c9abd583af86c1f876925e38366c900a)**
 - JDK major version: **11**
 - OS: **Linux Fedora 32**
 - Architecture: **AMD64**

**More details**
The failure appears when using `--initialize-at-build-time=Random` as well.

If `--initialize-at-build-time` is ommited `Random` gets initialiazed at runtime while `Main`, `SubstMain`, `java.util.Random` and `sun.security.provider.SecureRandom` remain build-time initialized and the test works as expected:
```
./main
Hello 2089683574
```

**Comment by jramirez-isc** [comment]
Hi @zakkak,
Thanks for reporting this. 
I was able to reproduce the issue following the steps you provided.
We'll let know any progress.

**Comment by zakkak** [comment]
Last checked on 796c0692039c462e10a04755d8736c2b2a50b0d6 (still reproducible)

**Comment by zakkak** [comment]
@cstancu FWIW I can no longer reproduce this with 21.2.0-dev-20210605_0329 I am now getting a segmentation fault instead though.
Note however that adding `-H:-ParseOnce` makes it reproduce even with 21.2.0-dev-20210605_0329.

```
$ ./main

[ [ SubstrateSegfaultHandler caught a segfault. ] ]

General Purpose Register Set values:

  RAX 0000000000000003
  RBX 0000000000844030
  RCX 0000000000000002
  RDX 0000000000431030
  RBP 0000000000000000
  RSI 00007ffccabed920
  RDI 0000000000000000
  RSP 00007ffccabedb90
  R8  0000000000000000
  R9  0000000000000000
  R10 0000000000000008
  R11 0000000000000246
  R12 0000000000405200
  R13 0000000000000000
  R14 0000000000000000
  R15 0000000000000000
  EFL 0000000000010206
  RIP 000000000041d7d3
  
JavaFrameAnchor dump:

  No anchors
  
TopFrame info:

  TotalFrameSize in CodeInfoTable 112
  
VMThreads info:

  VMThread 000000000231d300  STATUS_IN_JAVA (safepoints disabled)  java.lang.Thread@0x7f6492eeec08
  
VM Thread State for current thread 000000000231d300:

  0 (8 bytes): com.oracle.svm.jni.JNIThreadLocalEnvironment.jniFunctions = (bytes) 
    000000000231d300: 00007f6492dcb010
  
  8 (8 bytes): com.oracle.svm.core.graal.snippets.StackOverflowCheckImpl.stackBoundaryTL = (Word) 1  0000000000000001
  16 (4 bytes): com.oracle.svm.core.thread.Safepoint.safepointRequested = (int) 2147477705  7fffe8c9
  20 (4 bytes): com.oracle.svm.core.thread.VMThreads$StatusSupport.statusTL = (int) 1  00000001
  24 (32 bytes): com.oracle.svm.core.genscavenge.ThreadLocalAllocation.regularTLAB = (bytes) 
    000000000231d318: 00007f6492a00000 00007f6492b00000
    000000000231d328: 00007f6492a02940 0000000000000000
    
  
  56 (8 bytes): com.oracle.svm.core.thread.JavaThreads.currentThread = (Object) java.lang.Thread  00007f6492eeec08
  64 (8 bytes): com.oracle.svm.core.stack.JavaFrameAnchors.lastAnchor = (Word) 0  0000000000000000
  72 (8 bytes): com.oracle.svm.core.heap.NoAllocationVerifier.openVerifiers = (Object) null
  80 (8 bytes): com.oracle.svm.core.identityhashcode.IdentityHashCodeSupport.hashCodeGeneratorTL = (Object) null
  88 (8 bytes): com.oracle.svm.core.snippets.ExceptionUnwind.currentException = (Object) null
  96 (8 bytes): com.oracle.svm.core.thread.ThreadingSupportImpl.activeTimer = (Object) null
  104 (8 bytes): com.oracle.svm.graal.isolated.IsolatedCompileClient.currentClient = (Object) null
  112 (8 bytes): com.oracle.svm.graal.isolated.IsolatedCompileContext.currentContext = (Object) null
  120 (8 bytes): com.oracle.svm.jni.JNIObjectHandles.handles = (Object) com.oracle.svm.core.handles.ThreadLocalHandles  00007f6492a01120
  128 (8 bytes): com.oracle.svm.jni.JNIThreadLocalPendingException.pendingException = (Object) null
  136 (8 bytes): com.oracle.svm.jni.JNIThreadLocalPinnedObjects.pinnedObjectsListHead = (Object) null
  144 (8 bytes): com.oracle.svm.jni.JNIThreadOwnedMonitors.ownedMonitors = (Object) null
  152 (8 bytes): com.oracle.svm.core.SubstrateDiagnostics.threadOnlyAttachedForCrashHandler = (bytes) 
    000000000231d398: 0000000000000000
  
  160 (8 bytes): com.oracle.svm.core.thread.VMThreads.IsolateTL = (Word) 140069935513600  00007f6492c00000
  168 (8 bytes): com.oracle.svm.core.thread.VMThreads.OSThreadHandleTL = (Word) 140069942850240  00007f64932ff2c0
  176 (8 bytes): com.oracle.svm.core.thread.VMThreads.OSThreadIdTL = (Word) 140069942850240  00007f64932ff2c0
  184 (8 bytes): com.oracle.svm.core.thread.VMThreads.nextTL = (Word) 0  0000000000000000
  192 (8 bytes): com.oracle.svm.core.thread.VMThreads.unalignedIsolateThreadMemoryTL = (Word) 36819696  000000000231d2f0
  200 (4 bytes): com.oracle.svm.core.graal.snippets.StackOverflowCheckImpl.yellowZoneStateTL = (int) -16843010  fefefefe
  204 (4 bytes): com.oracle.svm.core.snippets.ImplicitExceptions.implicitExceptionsAreFatal = (int) 0  00000000
  208 (4 bytes): com.oracle.svm.core.thread.ThreadingSupportImpl.currentPauseDepth = (int) 0  00000000
  212 (4 bytes): com.oracle.svm.core.thread.VMThreads$ActionOnExitSafepointSupport.actionTL = (int) 0  00000000
  216 (4 bytes): com.oracle.svm.core.thread.VMThreads$ActionOnTransitionToJavaSupport.actionTL = (int) 0  00000000
  220 (4 bytes): com.oracle.svm.core.thread.VMThreads$StatusSupport.safepointsDisabledTL = (int) 1  00000001
  
VMOperation dump:

  No VMOperation in progress
  
  The 10 most recent VM operation status changes (oldest first):
    
  
Dump Counters:

  
Raw Stacktrace:

  00007ffccabedb90: 0000000000800000 ffffffffffffffff
  00007ffccabedba0: 0000000000000001 0000000000000001
  00007ffccabedbb0: 0000000000e8b7b8 0000000000844030
  00007ffccabedbc0: 0000000000000000 0000000000405200
  00007ffccabedbd0: 0000000000000000 0000000000000000
  00007ffccabedbe0: 0000000000000000 00007ffccabedce8
  00007ffccabedbf0: 0000000100844030 00007f6493327b75
  00007ffccabedc00: 00007ffccabedce8 0000000100000064
  
Stacktrace Stage 0:

  SP 00007ffccabedb90 IP 000000000041d7d3  FrameSize 112
  
Stacktrace Stage 1:

  SP 00007ffccabedb90 IP 000000000041d7d3  com.oracle.svm.core.code.CodeInfo@0x7f6492ea14f0 name = image code
  
Stacktrace Stage 2:

  SP 00007ffccabedb90 IP 000000000041d7d3  com.oracle.svm.core.code.CodeInfo@0x7f6492ea14f0 name = image code
  
[Heap settings and statistics: 
  Supports isolates: true
  Object reference size: 8
  Incremental collections: 0
  Complete collections: 0]

[Native image heap boundaries: 
  ReadOnly Primitives: 0x7f6492c01028 .. 0x7f6492ce5690
  ReadOnly References: 0x7f6492ce56a0 .. 0x7f6492dcae68
  ReadOnly Relocatables: 0x7f6492dcb000 .. 0x7f6492e36278
  Writable Primitives: 0x7f6492e37000 .. 0x7f6492eb4848
  Writable References: 0x7f6492eb4858 .. 0x7f649303ed68
  Writable Huge: 0x0 .. 0x0
  ReadOnly Huge: 0x7f6493100030 .. 0x7f64931b0b98]


[Heap:
  [Young generation: 
    [Eden: 
      [edenSpace:
        aligned: 0/0 unaligned: 0/0]]
    [Survivors: 
      ]]
  [Old generation: 
    [oldFromSpace:
      aligned: 0/0 unaligned: 0/0]
    [oldToSpace:
      aligned: 0/0 unaligned: 0/0]
    ]
  [Unused:
    aligned: 0/0]]

Segfault detected, aborting process. Use runtime option -R:-InstallSegfaultHandler if you don't want to use SubstrateSegfaultHandler.
```

**Comment by zakkak** [comment]
The issue with this turned out to be a missing `declClass = SecureRandom.class` in the `RecomputeFieldValue` annotation. Fixing this resolves the issue.

With the latest graal `master` the following error is printed in such cases:

```
Caused by: com.oracle.svm.core.util.UserError$UserException: Field value transformer returned value of type `Random` that is not assignable to declared type `java.security.SecureRandom` of Random.rnd
```

which is not perfect but should be enough for the users of the `RecomputeFieldValue` annotation. 

Unfortunately a segmentation fault still happens after printing the above error. Ideally the process should exit with an error code with a segmentation fault.
