### ISSUE TITLE
sun.util.resources.TimeZoneNames is included by deafult on Linux, but it is not on Windows

### ISSUE THREAD

**Issue by Karm** [oracle/graal#2944]
Hello,

The following snippet builds and runs without warnings on Centos8 and contemporary Fedora systems:
**TimeZoneTest.java**
```java
import java.time.ZoneId;
import java.util.Date;
import java.util.TimeZone;

/**
 * @author Severin Gehwolf <sgehwolf@redhat.com>
 * @author Michal Karm Babacek <karm@redhat.com>
 */
public class TimeZoneTest {
    public static void main(String[] args) {
        System.out.println(String.format("%tc", new Date()));
        final TimeZone tz = TimeZone.getTimeZone(ZoneId.of("Europe/Paris"));
        System.out.println(tz.getDisplayName());
    }
}
```
# Linux :heavy_check_mark: 

```
$  export JAVA_HOME=/var/X/JDKs/graalvm-ce-java11-20.2.0/;export GRAALVM_HOME=${JAVA_HOME};export PATH=${JAVA_HOME}/bin:${PATH}
$ javac TimeZoneTest.java 
$ native-image -J-Duser.country=CA -J-Duser.language=fr TimeZoneTest
$ ./timezonetest 
mar. oct. 27 16:35:34 CET 2020
heure normale d’Europe centrale
```

# Windows :x: 

On Windows, it seems it is necessary to include ```-H:IncludeResourceBundles=sun.util.resources.TimeZoneNames``` explicitly (the same with 20.2.0 and 20.1.0):

```batch
λ set JAVA_HOME=C:\projects\graalvm-ce-java11-20.1.0
λ set PATH=%JAVA_HOME%\bin;%PATH%
λ javac TimeZoneTest.java
λ native-image -J-Duser.country=CA -J-Duser.language=fr TimeZoneTest
C:\tmp
λ timezonetest.exe
mar. oct. 27 04:29:30 HAP 2020
Exception in thread "main" java.util.MissingResourceException: Resource bundle not found sun.util.resources.TimeZoneNames. Register the resource bundle using the option -H:IncludeResourceBundles=sun.util.resources.TimeZoneNames.
        at com.oracle.svm.core.jdk.LocalizationSupport.getCached(LocalizationSupport.java:66)
        at sun.util.resources.Bundles.loadBundleOf(Bundles.java:52)
        at sun.util.resources.Bundles.of(Bundles.java:106)
        at sun.util.resources.LocaleData$1.run(LocaleData.java:185)
        at sun.util.resources.LocaleData$1.run(LocaleData.java:182)
        at java.security.AccessController.doPrivileged(AccessController.java:83)
        at sun.util.resources.LocaleData.getBundle(LocaleData.java:182)
        at sun.util.resources.LocaleData.getTimeZoneNames(LocaleData.java:114)
        at sun.util.locale.provider.LocaleResources.getTimeZoneNames(LocaleResources.java:271)
        at sun.util.cldr.CLDRTimeZoneNameProviderImpl.deriveFallbackName(CLDRTimeZoneNameProviderImpl.java:164)
        at sun.util.cldr.CLDRTimeZoneNameProviderImpl.getDisplayNameArray(CLDRTimeZoneNameProviderImpl.java:99)
        at sun.util.locale.provider.TimeZoneNameProviderImpl.getDisplayName(TimeZoneNameProviderImpl.java:99)
        at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getName(TimeZoneNameUtility.java:271)
        at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getObject(TimeZoneNameUtility.java:229)
        at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getObject(TimeZoneNameUtility.java:215)
        at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObjectImpl(LocaleSubstitutions.java:150)
        at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObject(LocaleSubstitutions.java:242)
        at sun.util.locale.provider.TimeZoneNameUtility.retrieveDisplayNamesImpl(TimeZoneNameUtility.java:197)
        at sun.util.locale.provider.TimeZoneNameUtility.retrieveDisplayName(TimeZoneNameUtility.java:150)
        at java.util.TimeZone.getDisplayName(TimeZone.java:401)
        at java.util.TimeZone.getDisplayName(TimeZone.java:316)
        at TimeZoneTest.main(TimeZoneTest.java:13)
```

When I include it, it goes better...although still weird. The Windows box has English US locale.

```batch
λ native-image -J-Duser.country=CA -J-Duser.language=fr -H:IncludeResourceBundles=sun.util.resources.TimeZoneNames TimeZoneTest
λ timezonetest.exe
mar. oct. 27 04:31:10 HAP 2020
heure normale dÆEurope centrale
```
# Question

Is this the expected behavior?

ping @jerboaa @zakkak 

**Describe GraalVM and your environment:**
 - GraalVM version: **CE 20.1, CE 20.2**
 - JDK major version: **11**
 - OS: **Windows 10**
 - Architecture: **AMD64**

**Comment by jerboaa** [comment]
@Karm Seems expected. It got fixed with:
https://github.com/oracle/graal/pull/2777 which is in 20.3+ CE apparently.

**Comment by jerboaa** [comment]
I don't recall which versions of OpenJDK 20.1 and 20.2 use, but if they're on 11.0.8 the difference between Linux and Windows may just be that it's easier to reproduce there. Please check a build from master.

**Comment by Karm** [comment]
@jerboaa O.K. built made of master on my Windows workstation works...    I used  labsjdk-ce-11.0.8-jvmci-20.3-b01.

```batch
λ set JAVA_HOME=C:\projects\graal\graal\sdk\mxbuild\windows-amd64\GRAALVM_6A37976327_JAVA11\graalvm-6a37976327-java11-21.0.0-dev/
λ set PATH=%JAVA_HOME%\bin;%PATH%
λ javac TimeZoneTest.java
λ native-image -J-Duser.country=CA -J-Duser.language=fr TimeZoneTest
[timezonetest:7932]    classlist:   2 406,82 ms,  0,96 GB
[timezonetest:7932]        (cap):   2 057,97 ms,  0,96 GB
[timezonetest:7932]        setup:   3 317,22 ms,  0,96 GB
[timezonetest:7932]     (clinit):     145,76 ms,  1,21 GB
[timezonetest:7932]   (typeflow):   5 950,98 ms,  1,21 GB
[timezonetest:7932]    (objects):   4 983,91 ms,  1,21 GB
[timezonetest:7932]   (features):     266,61 ms,  1,21 GB
[timezonetest:7932]     analysis:  11 518,31 ms,  1,21 GB
[timezonetest:7932]     universe:     479,77 ms,  1,70 GB
[timezonetest:7932]      (parse):   1 539,67 ms,  1,70 GB
[timezonetest:7932]     (inline):   1 864,00 ms,  1,70 GB
[timezonetest:7932]    (compile):   9 056,00 ms,  2,32 GB
[timezonetest:7932]      compile:  12 967,26 ms,  2,32 GB
[timezonetest:7932]        image:   1 184,21 ms,  2,32 GB
[timezonetest:7932]        write:     372,06 ms,  2,32 GB
[timezonetest:7932]      [total]:  32 438,79 ms,  2,32 GB

λ timezonetest.exe
mar. oct. 27 17:35:11 HAP 2020
heure normale dÆEurope centrale
```
