### ISSUE TITLE
graalvm 21.0.0 fails to build on labsjdk15-jvmci-20.3-b03

### ISSUE THREAD

**Issue by frank-dspeed** [oracle/graal#2948]
**Describe the issue**
graalvm 21.0.0 fails to build on labsjdk15-jvmci-20.3-b03

**Steps to reproduce the issue**
https://github.com/direktspeed/graalvm-stack/blob/main/.github/workflows/release-ce-dev.yml

**Describe GraalVM and your environment:**
https://github.com/direktspeed/graalvm-stack/blob/main/.github/workflows/release-ce-dev.yml

**More details**
my builds worked befor since 23 days problems did come i now did upgrade to the newst labsjdk-jvmci-20.3.b03 but still does not build anymore the failures about unsupported features where there also with jvmci 20.3-b01 

last working graal + graaljs commits
https://github.com/direktspeed/graalvm-stack/releases/tag/vm-20.3.0-GRAALVM-d31e1e5-GRAALJS-0c3bdea-jdk15-jvmci-20.3-b01

```
Building gu.image... [dependency GRAALVM_18ADCA24E2_JAVA15_STAGE1 updated]
[gu:12478]    classlist:   3,326.09 ms,  0.96 GB
[gu:12478]        (cap):   1,049.83 ms,  0.96 GB
[gu:12478]        setup:   3,108.50 ms,  0.96 GB
[gu:12478]     (clinit):     420.15 ms,  2.41 GB
[gu:12478]   (typeflow):  21,285.71 ms,  2.41 GB
[gu:12478]    (objects):  37,526.65 ms,  2.41 GB
[gu:12478]   (features):     784.98 ms,  2.41 GB
[gu:12478]     analysis:  60,827.10 ms,  2.41 GB
Error: Unsupported features in 2 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace: 
	at parsing sun.nio.ch.DatagramChannelImpl.socket(DatagramChannelImpl.java:275)
Call path from entry point to sun.nio.ch.DatagramChannelImpl.socket(): 
	at sun.nio.ch.DatagramChannelImpl.socket(DatagramChannelImpl.java:272)
	at com.sun.jndi.dns.DNSDatagramSocketFactory.openRandom(DNSDatagramSocketFactory.java:230)
	at com.sun.jndi.dns.DNSDatagramSocketFactory.open(DNSDatagramSocketFactory.java:177)
	at com.sun.jndi.dns.DnsClient.getDatagramSocket(DnsClient.java:143)
	at com.sun.jndi.dns.DnsClient.doUdpQuery(DnsClient.java:403)
	at com.sun.jndi.dns.DnsClient.query(DnsClient.java:214)
	at com.sun.jndi.dns.Resolver.query(Resolver.java:81)
	at com.sun.jndi.dns.DnsContext.c_getAttributes(DnsContext.java:434)
	at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_getAttributes(ComponentDirContext.java:235)
	at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.getAttributes(PartialCompositeDirContext.java:141)
	at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.getAttributes(PartialCompositeDirContext.java:129)
	at sun.security.krb5.KrbServiceLocator.lambda$getKerberosService$0(KrbServiceLocator.java:93)
	at sun.security.krb5.KrbServiceLocator$$Lambda$838/0x00000007c0d40710.run(Unknown Source)
	at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:147)
	at java.util.ServiceLoader$ProviderImpl.invokeFactoryMethod(ServiceLoader.java:752)
	at java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:337)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type java.lang.invoke.MemberName is reachable: All methods from java.lang.invoke should have been replaced during image building.
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Trace: 
	at parsing java.lang.invoke.MethodHandles$Lookup.findVarHandle(MethodHandles.java:2899)
Call path from entry point to java.lang.invoke.MethodHandles$Lookup.findVarHandle(Class, String, Class): 
	no path found from entry point to target method


Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1

Building gu.image failed
1 build tasks failed
Error: Process completed with exit code 1.

```

**Comment by dougxc** [comment]
There are a number of issues in addition to this one in terms of being able to build GraalVM on JDK 15. We are working through them but have no concrete time line at this point.

**Comment by dougxc** [comment]
Tracked internally with GR-23899.

**Comment by frank-dspeed** [comment]
@dougxc could you maybe add that also to graalvm-ce-dev builds? i mean you probally already buld and test that some where then i would not need to have my own build stack for that. i need it because i use always java edge version features.

**Comment by dougxc** [comment]
Yes, once we have GraalVM on JDK 15 (or JDK 16 depending on time line) working, we will include it in the graalvm-ce-dev builds (cc @gilles-duboscq ).

**Comment by frank-dspeed** [comment]
@dougxc graalvm 20.3 worked perfect 20 days befrore

**Comment by dougxc** [comment]
I'm surprised to hear that - you got lucky ;-)

In any case, I cannot offer any guarantees of it working (again) until we've resolved all known issues.

**Comment by dougxc** [comment]
With GraalVM released on JDK 16, this issue should no longer be a  problem.
