### ISSUE TITLE
Issue with WebView reflection

### ISSUE THREAD

**Issue by Zachpocalypse** [oracle/graal#2968]
The last time I tried building on my Windows device, I experienced a similar issue. But I'm getting an issue accessing what I'm guessing is a component in the native libraries for JavaFX?

Environments I've reproduced on:
macOS Catalina/Big Sur RC/Windows 10 (2004)
AdoptOpenJDK11/14
Latest GraalVM from the website (20.2)

```
Thu Oct 29 23:38:16 CDT 2020][INFO] [SUB] [com.graalonline.gui.launcher:11497]        (cap):   2,728.11 ms,  0.96 GB
[Thu Oct 29 23:38:18 CDT 2020][INFO] [SUB] [com.graalonline.gui.launcher:11497]        setup:   5,942.30 ms,  0.96 GB
[Thu Oct 29 23:40:11 CDT 2020][INFO] [SUB] [com.graalonline.gui.launcher:11497]     (clinit):   1,279.82 ms,  3.09 GB
[Thu Oct 29 23:40:12 CDT 2020][INFO] [SUB] [com.graalonline.gui.launcher:11497]   (typeflow):  46,647.02 ms,  3.09 GB
[Thu Oct 29 23:40:12 CDT 2020][INFO] [SUB] [com.graalonline.gui.launcher:11497]    (objects):  55,909.44 ms,  3.09 GB
[Thu Oct 29 23:40:12 CDT 2020][INFO] [SUB] [com.graalonline.gui.launcher:11497]   (features):   7,327.48 ms,  3.09 GB
[Thu Oct 29 23:40:12 CDT 2020][INFO] [SUB] [com.graalonline.gui.launcher:11497]     analysis: 113,429.87 ms,  3.09 GB
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB] [com.graalonline.gui.launcher:11497]     universe:   3,101.49 ms,  3.09 GB
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB] Fatal error:java.lang.NoClassDefFoundError
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:480)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:349)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:508)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:114)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:537)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB] Caused by: java.lang.NoClassDefFoundError: com/sun/media/jfxmedia/events/PlayerStateListener
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at java.base/java.security.AccessController.doPrivileged(Native Method)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at jdk.internal.vm.ci/jdk.vm.ci.hotspot.CompilerToVM.getDeclaredMethods(Native Method)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.getDeclaredMethods(HotSpotResolvedObjectTypeImpl.java:979)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at com.oracle.svm.jni.access.JNIAccessibleMethod.anyMatchIgnoreReturnType(JNIAccessibleMethod.java:139)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at com.oracle.svm.jni.access.JNIAccessibleMember.findHidingSubclasses(JNIAccessibleMember.java:103)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at com.oracle.svm.jni.access.JNIAccessibleMember.findHidingSubclasses(JNIAccessibleMember.java:110)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at com.oracle.svm.jni.access.JNIAccessibleMember.setHidingSubclasses(JNIAccessibleMember.java:83)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at com.oracle.svm.jni.access.JNIAccessibleMethod.finishBeforeCompilation(JNIAccessibleMethod.java:135)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at com.oracle.svm.jni.access.JNIAccessFeature.beforeCompilation(JNIAccessFeature.java:348)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGenerator.lambda$doRun$2(NativeImageGenerator.java:611)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:611)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB] Caused by: java.lang.ClassNotFoundException: com.sun.media.jfxmedia.events.PlayerStateListener
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB]      ... 28 more
[Thu Oct 29 23:40:15 CDT 2020][INFO] [SUB] Error: Image build request failed with exit status 1
```

My build.gradle:

```
plugins {
    id("application")
    id("org.openjfx.javafxplugin") version "0.0.9"
    id "com.gluonhq.client-gradle-plugin" version "0.1.32"
}

application {
    mainClassName = "com.graalonline.gui.Launcher"
    applicationDefaultJvmArgs = [
        '-Dgreeting.language=en',
        '-XX:+FlightRecorder',
        '-XX:StartFlightRecording=disk=true,maxsize=5G',
    ]
}

java {
    group = "com.graalonline.rcfx"
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
    archivesBaseName = "gui"
}

repositories {
    jcenter()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    mavenLocal()
    mavenCentral()
}

javafx {
    version = "14"
    modules = ["javafx.web", "javafx.fxml", "javafx.media"]
}

jar {
    manifest {
        attributes 'Main-Class': 'com.graalonline.gui.Launcher'
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}

dependencies {
    implementation(project(":rc-core"))

    implementation("com.github.varra4u:utils4j:1.0")
    implementation("com.googlecode.soundlibs:tritonus-all:0.3.7.2")
    implementation("com.google.code.gson:gson:2.8.6")
    implementation("com.google.flogger:flogger:0.5.1")
    implementation("org.jsoup:jsoup:1.13.1")
    implementation("org.json:json:20190722")
    implementation("commons-codec:commons-codec:1.13")
    implementation("commons-io:commons-io:2.6")
    implementation("org.apache.commons:commons-compress:1.20")
    implementation("io.reactivex:rxjava:1.0.9")
    implementation("org.jetbrains:annotations:19.0.0")

    runtimeOnly("com.google.flogger:flogger-system-backend:0.5.1")
    implementation("org.openjfx:javafx-web:$javafx.version:win")
    implementation("org.openjfx:javafx-web:$javafx.version:linux")
    implementation("org.openjfx:javafx-web:$javafx.version:mac")

    implementation("org.openjfx:javafx-media:$javafx.version:win")
    implementation("org.openjfx:javafx-media:$javafx.version:linux")
    implementation("org.openjfx:javafx-media:$javafx.version:mac")

    implementation("org.openjfx:javafx-graphics:$javafx.version:win")
    implementation("org.openjfx:javafx-graphics:$javafx.version:linux")
    implementation("org.openjfx:javafx-graphics:$javafx.version:mac")

    implementation("org.openjfx:javafx-controls:$javafx.version:win")
    implementation("org.openjfx:javafx-controls:$javafx.version:linux")
    implementation("org.openjfx:javafx-controls:$javafx.version:mac")

    implementation("org.openjfx:javafx-base:$javafx.version:win")
    implementation("org.openjfx:javafx-base:$javafx.version:linux")
    implementation("org.openjfx:javafx-base:$javafx.version:mac")

    implementation("org.openjfx:javafx-fxml:$javafx.version:win")
    implementation("org.openjfx:javafx-fxml:$javafx.version:linux")
    implementation("org.openjfx:javafx-fxml:$javafx.version:mac")
}

gluonClient {
    enableSwRendering = true
    graalvmHome = "/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.2.0/Contents/Home"

    mainClassName = "com.graalonline.gui.Launcher"
    compilerArgs = [
        "-H:+ReportUnsupportedElementsAtRuntime",
        "--no-fallback",
        "--enable-all-security-services",
        "-Dpolyglot.js.nashorn-compat=true GraalSuite",
        "-H:+AllowIncompleteClasspath",
H:ClassInitialization=com.sun.javafx.scene.web.WebEngine:build_time,com.sun.javafx.scene.web.WebView:build_time,com.sun.javafx.fxml.builder.web.WebViewBuilder:build_time,com.graalonline.gui.remotecontrol.ServerController:run_time,com.graalonline.gui.login.LoginController:run_time,com.graalonline.gui.editor.EditorController:run_time,com.graalonline.gui.serverlister.ServerListerController:run_time,"
    ]
    reflectionList = [
        "javafx.scene.web.WebView",
        "javafx.fxml.FXMLLoader",
        "com.graalonline.gui.Main",
        "com.graalonline.gui.login.LoginController",
        "com.graalonline.gui.remotecontrol.RemoteControlFlow",
        "com.graalonline.gui.remotecontrol.ServerController",
        "com.graalonline.gui.serverlister.ServerListerController",
        "javafx.scene.control.SplitPane",
        "com.graalonline.gui.login.connection.ConnectionController",
        "javafx.scene.control.TableColumn",
        "javafx.scene.control.TableColumnBase",
        "javafx.scene.control.TableView",
        "javafx.scene.control.CheckBox",
        ]
    resourcesList = [".*\\\\.config\$", ".*/META-INF/services/.*", ".*\\\\.xml\$", ".*\\\\.psd\$", ".*\\\\.css\$", ".*\\\\.fxml\$", ".*\\\\.js\$"]
}

tasks.compileJava {
    doFirst {
        options.compilerArgs = [
                '--module-path', classpath.asPath,
                '--add-modules', 'javafx.base',
                '--add-modules', 'javafx.fxml',
                '--add-modules', 'javafx.controls',
                '--add-modules', 'javafx.web',
                '--add-modules', 'javafx.graphics',
                '-Xlint:unchecked',
                '-Xlint:deprecation',
        ]
    }
    classpath += files(sourceSets.main.output.resourcesDir) //adds build/resources/main to javac's classpath
    dependsOn processResources
}

tasks.compileTestJava {
    classpath += files(sourceSets.test.output.resourcesDir) //adds build/resources/test to test javac's classpath
    dependsOn processTestResources
}

tasks.clean {
    delete "out"
}
```

Any insight would be greatly appreciated.

So far, I have tried:
* Adding the mentioned classes to both the reflection and JNI lists. Can't be found in either.
* Different versions of JavaFX
* Adding/Removing WebEngine from reflection
* Building with/without dependencies and with/without the JavaFX plugin in all permutations.
* Building with/without the add-module lines in all permutations with the JavaFX plugin and dependencies.

[client-debug0.log](https://github.com/gluonhq/substrate/files/5464395/client-debug0.log)

[process-compile-1604033734317.log](https://github.com/gluonhq/substrate/files/5464392/process-compile-1604033734317.log)

**Comment by fernando-valdez** [comment]
Thanks for reporting this issue @Zachpocalypse, 
I will take a look at it. 
If I have any questions, I will let you know.

**Comment by fernando-valdez** [comment]
@Zachpocalypse can you please share the entire content of your build.gradle file?
 Seems like the top of the file is missing.

**Comment by Zachpocalypse** [comment]
The only missing line was the opening portion of the plugins codeblock. I've fixed that.

**Comment by Zachpocalypse** [comment]
> @Zachpocalypse can you please share the entire content of your build.gradle file?
> 
>  Seems like the top of the file is missing.

Any update on the issue or suggestions as to what the problem may be?

**Comment by petermz** [comment]
From the error, it seems missing is either javafx-media.jar or some classloader configuration that makes it available to the native image.

I'd also try removing the `AllowIncompleteClasspath` option and see what it complains about at image build time
