### ISSUE TITLE
(.data+0xf50): undefined reference to `Java_java_awt_Component_initIDs'

### ISSUE THREAD

**Issue by yyanglike** [oracle/graal#2971]
**Describe the issue**
/usr/bin/ld: demo.o: warning: relocation in read-only section `.svm_heap'
/usr/bin/ld: demo.o:(.data+0xf50): undefined reference to `Java_java_awt_Component_initIDs'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
	at com.oracle.svm.hosted.image.NativeBootImageViaCC.handleLinkerFailure(NativeBootImageViaCC.java:463)
	at com.oracle.svm.hosted.image.NativeBootImageViaCC.write(NativeBootImageViaCC.java:430)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:679)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:470)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

when using native-image to build a native image ,report an error.what 's should I do next?

**Comment by jramirez-isc** [comment]
Hi @yyanglike do you have a reproducer for this error?

**Comment by yyanglike** [comment]
This is just a spring boot project,I think the error should not appear.i recompile the project ,but the same error re-emerged
/usr/bin/ld: demo.o: warning: relocation in read-only section `.svm_heap'
/usr/bin/ld: demo.o:(.data+0x1060): undefined reference to `Java_java_awt_Component_initIDs'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
	at com.oracle.svm.hosted.image.NativeBootImageViaCC.handleLinkerFailure(NativeBootImageViaCC.java:463)
	at com.oracle.svm.hosted.image.NativeBootImageViaCC.write(NativeBootImageViaCC.java:430)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:679)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:470)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1651)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1401)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1362)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1321)
	at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1833)

**Comment by yyanglike** [comment]
I changed the new version and some parentments ,this error disappered.

**Comment by Jaakkonen** [comment]
I had same kind of issue with a statically compiled groovy script pulling in `org.jenkins-ci.plugins:job-dsl-core:1.77` with GraalVM JDK 11. With GraalVM JDK 8 the linking passed.
