### ISSUE TITLE
Win10 graal native stacktrace ms SDK 7.1

### ISSUE THREAD

**Issue by dufoli** [oracle/graal#2975]
**Describe the issue**
Under win10, with microsoft SDK, when I build any quarkus extension, I get a stack trace.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. git clone --depth 1 https://github.com/quarkiverse/quarkiverse-cxf.git
2. CALL "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
3. mvn clean install -Dnative

**Describe GraalVM and your environment:**
 - graalvm-ce-java8-20.2.0
 - jdk1.8.0_221
- Microsoft SDK 7.1
 - OS: win 10 familly
 - Architecture: x64

**More details**
The same stack trace happend on other extension build. So I guess it is related to environment.
The error do not happend on github build action which use a linux image.

```
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of sun.nio.ch.Iocp are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
        at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.checkImageHeapInstance(ClassInitializationFeature.java:193)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:560)
        at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.replaceObject(AnalysisConstantReflectionProvider.java:217)
        at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.interceptValue(AnalysisConstantReflectionProvider.java:188)
        at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:102)
        at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:78)
        at org.graalvm.compiler.nodes.util.ConstantFoldUtil$1.readValue(ConstantFoldUtil.java:51)
        at org.graalvm.compiler.core.common.spi.JavaConstantFieldProvider.readConstantField(JavaConstantFieldProvider.java:84)
        at com.oracle.svm.hosted.ameta.AnalysisConstantFieldProvider.readConstantField(AnalysisConstantFieldProvider.java:72)
        at org.graalvm.compiler.nodes.util.ConstantFoldUtil.tryConstantFold(ConstantFoldUtil.java:47)
        at com.oracle.svm.hosted.phases.ConstantFoldLoadFieldPlugin.tryConstantFold(ConstantFoldLoadFieldPlugin.java:64)
        at com.oracle.svm.hosted.phases.ConstantFoldLoadFieldPlugin.handleLoadStaticField(ConstantFoldLoadFieldPlugin.java:60)
        at org.graalvm.compiler.java.BytecodeParser.genGetStatic(BytecodeParser.java:4882)
        at org.graalvm.compiler.java.BytecodeParser.genGetStatic(BytecodeParser.java:4849)
        at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5334)
        at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3413)
        at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3220)
        at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1090)
        at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:984)
        at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:74)
        at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:214)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:223)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:357)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:313)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:302)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
        at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:434)
        at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:552)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
```

**Comment by fernando-valdez** [comment]
Hi @dufoli,
Thanks for reporting this. I will take a look at the issue. If I have any questions I will let you know

**Comment by fernando-valdez** [comment]
Hi @dufoli. This issue was tested using the latest version of GraalVM and the problem was fixed. 
If you find this problem again, please re-open this ticket.
