### ISSUE TITLE
Assertion / NPE on removeMember()

### ISSUE THREAD

**Issue by pmlopes** [oracle/graal#2977]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **GraalVM CE 21.0.0-dev-20201111_0522**
 - CE or EE: **CE]**
 - JDK version: **JDK11**
 - OS and OS Version: **Linux Ubuntu 20.04 LTS**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
OpenJDK 64-Bit Server VM (11.0.9+10-jvmci-20.3-b05) for linux-amd64 JRE (11.0.9+10-jvmci-20.3-b05), built on Nov  7 2020 16:14:18 by "buildslave" with gcc 7.3.0
```

**Describe the issue**
With the current stable release 20.2.0, removing elements from the bindings doesn't raise any assertion of crashes.

The use case is: Under the "js" polyglot engine (graaljs) I want to exclude from the bindings several well known properties:

* "exit"
* "quit"
* "Packages"
* "java"
* "javafx"
* "javax"
* "com"
* "org"
* "edu"

Even though the issue also happens for custom values added to the bindings, for example, during a setup step, I want to expose a few fields to the bindings and remove them before the user script runs. A simple reproducer for this short case is here in JUnit style:

**Code snippet or code repository that reproduces the issue**

```java
  @Test
  public void test21_0_0_DEV() {

    try (Context context = Context.newBuilder("js")
      .allowHostClassLookup(fqcn -> true)
      .allowHostAccess(HostAccess.ALL)
      .build()) {

      Value bindings = context.getBindings("js");

      bindings.putMember("mybinding", new ConcurrentHashMap<>());

      context.eval(
        Source.newBuilder(
          "js",
          "print(mybinding);",
          "script.js").buildLiteral());

      // failure
      bindings.removeMember("mybinding");
    }
  }
```

**Expected behavior**

This isn't expected:

```
org.graalvm.polyglot.PolyglotException: java.lang.NullPointerException: Pre-condition contract violation for receiver null.

	at org.graalvm.truffle/com.oracle.truffle.api.interop.AssertUtils.preCondition(AssertUtils.java:202)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibrary$Asserts.accepts(InteropLibrary.java:2198)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.isMemberRemovable(InteropLibraryGen.java:5936)
	at com.oracle.truffle.js.runtime.interop.TopScopeObject.removeMember(TopScopeObject.java:271)
	at com.oracle.truffle.js.runtime.interop.TopScopeObjectGen$InteropLibraryExports$Cached.removeMemberNode_AndSpecialize(TopScopeObjectGen.java:453)
	at com.oracle.truffle.js.runtime.interop.TopScopeObjectGen$InteropLibraryExports$Cached.removeMember(TopScopeObjectGen.java:437)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibrary$Asserts.removeMember(InteropLibrary.java:2647)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValue$InteropCodeCache$RemoveMemberNode.doCached(PolyglotValue.java:1716)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueFactory$InteropCodeCacheFactory$RemoveMemberNodeGen.executeAndSpecialize(PolyglotValueFactory.java:3023)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueFactory$InteropCodeCacheFactory$RemoveMemberNodeGen.executeImpl(PolyglotValueFactory.java:2972)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:113)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.removeMember(Value.java:421)
	at io.reactiverse.es4x.test.GraalJSReproducer.test21_0_0_DEV(GraalJSReproducer.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Original Internal Error: 
java.lang.NullPointerException: Pre-condition contract violation for receiver null.
	at org.graalvm.truffle/com.oracle.truffle.api.interop.AssertUtils.preCondition(AssertUtils.java:202)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibrary$Asserts.accepts(InteropLibrary.java:2198)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.isMemberRemovable(InteropLibraryGen.java:5936)
	at com.oracle.truffle.js.runtime.interop.TopScopeObject.removeMember(TopScopeObject.java:271)
	at com.oracle.truffle.js.runtime.interop.TopScopeObjectGen$InteropLibraryExports$Cached.removeMemberNode_AndSpecialize(TopScopeObjectGen.java:453)
	at com.oracle.truffle.js.runtime.interop.TopScopeObjectGen$InteropLibraryExports$Cached.removeMember(TopScopeObjectGen.java:437)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibrary$Asserts.removeMember(InteropLibrary.java:2647)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValue$InteropCodeCache$RemoveMemberNode.doCached(PolyglotValue.java:1716)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueFactory$InteropCodeCacheFactory$RemoveMemberNodeGen.executeAndSpecialize(PolyglotValueFactory.java:3023)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueFactory$InteropCodeCacheFactory$RemoveMemberNodeGen.executeImpl(PolyglotValueFactory.java:2972)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:113)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:556)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:527)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:481)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:465)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalRuntimeSupport.callProfiled(GraalRuntimeSupport.java:136)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValue$InteropValue.removeMember(PolyglotValue.java:2674)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.removeMember(Value.java:421)
	at io.reactiverse.es4x.test.GraalJSReproducer.test21_0_0_DEV(GraalJSReproducer.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: Attached Guest Language Frames (1)
```

**Comment by pmlopes** [comment]
Also happens with: `GraalVM CE 20.3.0-dev-20201109_0912`

**Comment by chumer** [comment]
That is a known issue internally tracked as GR-27300. Was fixed today on master. Currently being backported to 20.3.
By @wirthi .

**Comment by wirthi** [comment]
HI @pmlopes 

as @chumer mentioned, this was already fixed (last week, and already backported; we just happen to have the same issue in Ruby as well, which is currently in the CI).

It should be in the next public preview build of GraalVM 20.3.0 (it already in the internal one).

-- Christian

**Comment by wirthi** [comment]
Just confirmed it is actually working: your code is printing `{}` and the `removeMember` line returns `true`.

-- Christian
