### ISSUE TITLE
revive support for HotSpot Truffle trampoline in AArch64 under CompressedOops

### ISSUE THREAD

**Issue by dougxc** [oracle/graal#298]
In https://github.com/oracle/graal/commit/6afc8f0ba83c7c73fa5b455d2bfa9bf86efe7d11, the instrumentation added to methods annotated by `@TruffleCallBoundary` had to be updated to account for the [extra load](https://github.com/oracle/graal/commit/6afc8f0ba83c7c73fa5b455d2bfa9bf86efe7d11#diff-c75a35e6f1e812d8592951c060d634c8L38) required after making `OptimizedCallTarget` contain an `InstalledCode` instead of directly subclassing it.

This has already been for [AMD64](https://github.com/oracle/graal/blob/9eac6585eb4aa211c030362eceda5edcbee7b4a6/compiler/src/org.graalvm.compiler.truffle.compiler.hotspot.amd64/src/org/graalvm/compiler/truffle/compiler/hotspot/amd64/AMD64TruffleCallBoundaryInstrumentationFactory.java#L68-L73) and [SPARC](https://github.com/oracle/graal/blob/9eac6585eb4aa211c030362eceda5edcbee7b4a6/compiler/src/org.graalvm.compiler.truffle.compiler.hotspot.sparc/src/org/graalvm/compiler/truffle/compiler/hotspot/sparc/SPARCTruffleCallBoundaryInstumentationFactory.java#L69-L72). However, I wasn't sure of the necessary changes for [AArch64](https://github.com/oracle/graal/blob/9eac6585eb4aa211c030362eceda5edcbee7b4a6/compiler/src/org.graalvm.compiler.truffle.compiler.hotspot.aarch64/src/org/graalvm/compiler/truffle/compiler/hotspot/aarch64/AArch64TruffleCallBoundaryInstumentationFactory.java#L64).

**Comment by dougxc** [comment]
On a side node, the spelling of `AArch64TruffleCallBoundaryInstumentationFactory` should be fixed to `AArch64TruffleCallBoundaryInstrumentationFactory` (add the missing "r").

**Comment by dougxc** [comment]
@adinn , would you be able to look into this issue?

**Comment by adinn** [comment]
sure I will take a look and see what I can do

n.b. expect possible slight delay and maybe some noob questions as this will be a cold start -- I have not built or debugged Graal for a few months :-)

**Comment by dougxc** [comment]
No problem. Once you have something that compiles, this is a simple way to test it:
```
compiler> mx unittest -XX:+UseCompressedOops CompilationOfProfilerNodesTest
MxJUnitCore
JUnit version 4.12
.
Time: 1.289

OK (1 test)

```
If that unit test passes, then the trampoline was successfully executed. The `-XX:+UseCompressedOops` is probably not necessary since that should be default.
Next you can try:
```
compiler> mx unittest -XX:+UseCompressedOops truffle
```
which will run all Truffle unit tests.
Just ensure you are in the `compiler` directory when running these commands.

**Comment by sanzinger** [comment]
@adinn  I have a fix for this issue on the way.

**Comment by adinn** [comment]
Hi Stefan,

Sorry, this is going to be a rather long story . . .

1: I checked your the source code for your patch and it looks fine -- it does essentially he same as the equivalent x86 code. Assuming that is all the change that is needed (an assumption I am not yet clear is valid but let's take that on trust for now) then it passes the eyeball test.

2: I ran the one-off test recommended by Doug

`  $ mx unittest -XX:+UseCompressedOops CompilationOfProfilerNodesTest`

and it completed successfully. So, your patch is working as expected to uncompress the relevant pointer.

3: I ran the full truffle tests using command

`  $ mx unittest -XX:+UseCompressedOops truffle`

This led to a couple of exceptions in two separate tests. However, only one test failed (which in itself is a bit odd and suggests that the other test is succeeding spuriously). Here is the failure report:

```
There was 1 failure:
1) assertThisIsSame(com.oracle.truffle.api.interop.java.test.JavaInteropTest)
java.lang.NullPointerException
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.vm.PolyglotImpl.wrapGuestException(PolyglotImpl.java:250)
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.vm.PolyglotBoundaryRootNode.execute(PolyglotBoundaryRootNode.java:82)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:245)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:234)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:224)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:209)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:185)
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.interop.java.ObjectProxyHandler.invoke(JavaInteropReflect.java:669)
	at com.sun.proxy.$Proxy67.equals(Unknown Source)
	at org.junit.Assert.isEquals(Assert.java:131)
	at org.junit.Assert.equalsRegardingNull(Assert.java:127)
	at org.junit.Assert.assertEquals(Assert.java:111)
	at com.oracle.truffle.api.interop.java.test.JavaInteropTest.assertThisIsSame(JavaInteropTest.java:171)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       . . .
	at com.oracle.mxtool.junit.MxJUnitWrapper.runRequest(MxJUnitWrapper.java:280)
	at com.oracle.mxtool.junit.MxJUnitWrapper.main(MxJUnitWrapper.java:196)
Caused by: com.oracle.truffle.api.TruffleStackTrace$LazyStackTrace
Caused by: com.oracle.truffle.api.TruffleStackTrace
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.TruffleStackTrace.fillIn(TruffleStackTrace.java:170)
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.TruffleStackTrace.addStackFrameInfo(TruffleStackTrace.java:233)
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.TruffleLanguage$LanguageImpl.onThrowable(TruffleLanguage.java:1865)
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.impl.TVMCI.onThrowable(TVMCI.java:177)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalTVMCI.onThrowable(GraalTVMCI.java:112)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:250)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:234)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:224)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:209)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:185)
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.interop.java.ObjectProxyHandler.invoke(JavaInteropReflect.java:669)
	at com.sun.proxy.$Proxy67.equals(Unknown Source)
	at org.junit.Assert.isEquals(Assert.java:131)
	at org.junit.Assert.equalsRegardingNull(Assert.java:127)
	at org.junit.Assert.assertEquals(Assert.java:111)
	at com.oracle.truffle.api.interop.java.test.JavaInteropTest.assertThisIsSame(JavaInteropTest.java:171)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        . . .
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.oracle.mxtool.junit.MxJUnitWrapper.runRequest(MxJUnitWrapper.java:280)
	at com.oracle.mxtool.junit.MxJUnitWrapper.main(MxJUnitWrapper.java:196)
```
The fact that the original throw happens below

`  jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary`

suggests it may be related to the patch (or may just be something else that has not been patched). 

4: The other exception backtrace that got printed during the full truffle unit tests was under com.oracle.truffle.api.instrumentation.test.ThreadsEventsTest$1.run and was an org.graalvm.polyglot.PolyglotException which wrapped an internal java.lang.AssertionError:

```
Exception in thread "Thread-25008" org.graalvm.polyglot.PolyglotException: java.lang.AssertionError
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.vm.PolyglotLanguage$ContextProfile.get(PolyglotLanguage.java:205)
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.vm.PolyglotImpl$EngineImpl.getCurrentContext(PolyglotImpl.java:306)
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.TruffleLanguage$ContextReference.get(TruffleLanguage.java:1738)
	at com.oracle.truffle.api.instrumentation.test.InstrumentationTestLanguage.parse(InstrumentationTestLanguage.java:211)
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.TruffleLanguage$ParsingRequest.parse(TruffleLanguage.java:607)
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.TruffleLanguage.parse(TruffleLanguage.java:1051)
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.TruffleLanguage$LanguageImpl.parse(TruffleLanguage.java:1850)
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.vm.PolyglotLanguageContext.parseCached(PolyglotLanguageContext.java:110)
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.vm.PolyglotContextImpl.eval(PolyglotContextImpl.java:763)
	at org.graalvm.graal_sdk/org.graalvm.polyglot.Context.eval(Context.java:162)
	at com.oracle.truffle.api.instrumentation.test.ThreadsEventsTest$1.run(ThreadsEventsTest.java:151)
Original Internal Error: 
java.lang.AssertionError
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.vm.PolyglotLanguage$ContextProfile.get(PolyglotLanguage.java:205)
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.vm.PolyglotImpl$EngineImpl.getCurrentContext(PolyglotImpl.java:306)
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.TruffleLanguage$ContextReference.get(TruffleLanguage.java:1738)
	at com.oracle.truffle.api.instrumentation.test.InstrumentationTestLanguage.parse(InstrumentationTestLanguage.java:211)
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.TruffleLanguage$ParsingRequest.parse(TruffleLanguage.java:607)
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.TruffleLanguage.parse(TruffleLanguage.java:1051)
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.TruffleLanguage$LanguageImpl.parse(TruffleLanguage.java:1850)
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.vm.PolyglotLanguageContext.parseCached(PolyglotLanguageContext.java:110)
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.vm.PolyglotContextImpl.eval(PolyglotContextImpl.java:763)
	at org.graalvm.graal_sdk/org.graalvm.polyglot.Context.eval(Context.java:162)
	at com.oracle.truffle.api.instrumentation.test.ThreadsEventsTest$1.run(ThreadsEventsTest.java:151)
Caused by: com.oracle.truffle.api.TruffleStackTrace$LazyStackTrace
Caused by: com.oracle.truffle.api.TruffleStackTrace
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.TruffleStackTrace.fillIn(TruffleStackTrace.java:170)
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.TruffleStackTrace.find(TruffleStackTrace.java:73)
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.TruffleStackTraceElement.getStackTrace(TruffleStackTraceElement.java:94)
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.vm.PolyglotExceptionImpl.<init>(PolyglotExceptionImpl.java:81)
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.vm.PolyglotImpl.wrapGuestException(PolyglotImpl.java:251)
	at com.oracle.truffle.truffle_api/com.oracle.truffle.api.vm.PolyglotContextImpl.eval(PolyglotContextImpl.java:772)
	at org.graalvm.graal_sdk/org.graalvm.polyglot.Context.eval(Context.java:162)
	at com.oracle.truffle.api.instrumentation.test.ThreadsEventsTest$1.run(ThreadsEventsTest.java:151)
```
It seems the test just swallowed this error without failing which may well be a problem with the tests.

5: I rebuilt without your patch and reran the failing test. It still failed but I would guess this is because the function your patch implements is missing. There were actually two failures -- both of which appear to indicate an unexpected exception:

```
There were 2 failures:
1) testException(com.oracle.truffle.api.interop.java.test.JavaInteropTest)
java.lang.AssertionError: expected HostException but was: class java.util.NoSuchElementException
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.oracle.truffle.api.interop.java.test.JavaInteropTest.testException(JavaInteropTest.java:923)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        . . .
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.oracle.mxtool.junit.MxJUnitWrapper.runRequest(MxJUnitWrapper.java:280)
	at com.oracle.mxtool.junit.MxJUnitWrapper.main(MxJUnitWrapper.java:196)
2) testException2(com.oracle.truffle.api.interop.java.test.JavaInteropTest)
java.lang.AssertionError: expected HostException but was: class java.lang.IllegalArgumentException
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.oracle.truffle.api.interop.java.test.JavaInteropTest.testException2(JavaInteropTest.java:937)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        . . .
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.oracle.mxtool.junit.MxJUnitWrapper.runRequest(MxJUnitWrapper.java:280)
	at com.oracle.mxtool.junit.MxJUnitWrapper.main(MxJUnitWrapper.java:196)
```
6: I also reran the ThreadEventsTest using the unpatched Graal and this time it worked fine with no exception backtrace.

7: I will attempt to debug this to see what is going on. It would help if someone could point me at the full change set for the x86 code to see if there is some other change to arch-specific code other than the the HotspotMove instruction that might be missing.

**Comment by adinn** [comment]
Ah, re that last request . . . I just saw the checkin mentioned in Doug's original comment. I will take a look at that.

**Comment by dougxc** [comment]
@adinn I think you can ignore the failing `JavaInteropTest` as I saw that @sanzinger filed an issue for this failing in our internal bug tracker. I don't believe it has anything to do with AArch64. @sanzinger can confirm this - don't waste any time on this until he does.

**Comment by adinn** [comment]
Ok, thanks for the heads up.

**Comment by sanzinger** [comment]
1. Thank you.
2. Ok
3. This issue is known and unrelated to AArch64, it occurs on AMD64 as well and will be fixed soon.
4. Same as 3.
6., 7. as I am writing, Doug has replied already.

**Comment by sanzinger** [comment]
Fix is merged.
