### ISSUE TITLE
JVM Crash while Building Quarkus Project

### ISSUE THREAD

**Issue by mrbahr2021** [oracle/graal#2985]
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fac4a6fb5ff, pid=27, tid=101
#
# JRE version: OpenJDK Runtime Environment GraalVM CE 20.2.0 (11.0.8+10) (build 11.0.8+10-jvmci-20.2-b03)
# Java VM: OpenJDK 64-Bit Server VM GraalVM CE 20.2.0 (11.0.8+10-jvmci-20.2-b03, mixed mode, tiered, jvmci, jvmci compiler, compressed oops, parallel gc, linux-amd64)
# Problematic frame:
# v  ~BufferBlob::vtable chunks
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /project/core.27)
#
# An error report file with more information is saved as:
# /project/hs_err_pid27.log
Compiled method (JVMCI)   22938 10755       4       jdk.vm.ci.meta.ResolvedJavaType::resolveConcreteMethod (26 bytes)
 total in heap  [0x00007fac52157790,0x00007fac52158068] = 2264
 relocation     [0x00007fac521578f8,0x00007fac52157960] = 104
 constants      [0x00007fac52157960,0x00007fac52157980] = 32
 main code      [0x00007fac52157980,0x00007fac52157ca0] = 800
 stub code      [0x00007fac52157ca0,0x00007fac52157cb0] = 16
 oops           [0x00007fac52157cb0,0x00007fac52157cc0] = 16
 metadata       [0x00007fac52157cc0,0x00007fac52157d48] = 136
 scopes data    [0x00007fac52157d48,0x00007fac52157e80] = 312
 scopes pcs     [0x00007fac52157e80,0x00007fac52157fe0] = 352
 dependencies   [0x00007fac52157fe0,0x00007fac52157fe8] = 8
 nul chk table  [0x00007fac52157fe8,0x00007fac52158058] = 112
 JVMCI data     [0x00007fac52158058,0x00007fac52158068] = 16
Compiled method (JVMCI)   22938 12125       4       com.oracle.graal.pointsto.meta.AnalysisUniverse::collectMethodImplementations (98 bytes)
 total in heap  [0x00007fac52687510,0x00007fac52688858] = 4936
 relocation     [0x00007fac52687678,0x00007fac52687730] = 184
 constants      [0x00007fac52687740,0x00007fac52687760] = 32
 main code      [0x00007fac52687760,0x00007fac52687fe0] = 2176
 stub code      [0x00007fac52687fe0,0x00007fac52688040] = 96
 oops           [0x00007fac52688040,0x00007fac52688050] = 16
 metadata       [0x00007fac52688050,0x00007fac526880e0] = 144
 scopes data    [0x00007fac526880e0,0x00007fac52688588] = 1192
 scopes pcs     [0x00007fac52688588,0x00007fac526887b8] = 560
 dependencies   [0x00007fac526887b8,0x00007fac526887c8] = 16
 nul chk table  [0x00007fac526887c8,0x00007fac52688848] = 128
 JVMCI data     [0x00007fac52688848,0x00007fac52688858] = 16
Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled
#
# If you would like to submit a bug report, please visit:
#   https://github.com/oracle/graal/issues
#
Error: Image build request failed with exit status 134
```

Unfortunately, I cannot constantly reproduce.  If I reboot my system, it will work for a while and then start eliciting the same error.

GraalVM 20.2.0
Quarkus 1.9.2
OS Ubuntu: 5.8.17-050817-generic
Architecture: AMD64 

```
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03)
OpenJDK 64-Bit Server VM GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03, mixed mode, sharing)
```

Stack Trace:

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.9.2.Final:native-image (default) on project codigo-provider-sendback-lda: Failed to generate native image: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:307)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:936)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] Caused by: java.lang.RuntimeException: Image generation failed. Exit code: 134
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:520)
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:276)
[ERROR]         ... 12 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
```

**Comment by dougxc** [comment]
Please attach hs_err_pid27.log to this issue.

**Comment by mrbahr2021** [comment]
[hs_err_pid27.log](https://github.com/oracle/graal/files/5547452/hs_err_pid27.log)

Here is the log.

Thanks,
Tom

**Comment by fernando-valdez** [comment]
Hello @mrbahr2021,
I will take a look at this issue. If I have any question I will let you know

**Comment by mrbahr2021** [comment]
Hi All - Any thoughts on this issue?  I appreciate your help.  Tom

**Comment by dougxc** [comment]
Have you opened a Quarkus issue? Maybe someone from that project has an idea.

**Comment by mrbahr2021** [comment]
I can do that.  And if they have any ideas, I'll update you all.

Thanks,
Tom

**Comment by fernando-valdez** [comment]
Hello @mrbahr2021,
There are multiple fixes on GraalVM regarding SIGSEGV crashes. But it is impossible to validate that your issue was fixed without a reproducer. 
Please use the latest version of GraalVM and test it again. If you find a similar problem, open a new ticket and attach any relevant information.
