### ISSUE TITLE
Native Image Agent fails to generate correct reflection configuration

### ISSUE THREAD

**Issue by chanseokoh** [oracle/graal#2994]
**Describe the issue**
The Native Image Agent misses to generate necessary `fields` access reflection configuration. To resolve the issue, I have to add them manually, which is impractical in our case.

Our app makes heavy use of Jackson to serialize and deserialize a lot of JSON contents. Many of our JSON Java template classes declare some fields as `final` so that no matter what the actual content to deserialize is, we always pick up the value declared in Java code. However, the Native Image Agent fails to add "allowWrite" reflection configuration, and running the native image results in the following error:

```
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Cannot set final field: com.example.JacksonIssueDemo$JsonTemplate.finalValue. Enable by specifying "allowWrite" for this field in the reflection configuration.
 at [Source: (String)"{"foo": 1234}"; line: 1, column: 16] (through reference chain: com.example.JacksonIssueDemo$JsonTemplate["foo"])
```

Sample Java deserialization code (from my reproducible sample repo below):
```java
public class JacksonIssueDemo {

  private static class JsonTemplate {
    public final int finalValue = 1234;
  }

  public static void main(String[] args) throws IOException {
    ObjectMapper mapper = new ObjectMapper();
    JsonTemplate parsed1 = mapper.readValue("{\"finalValue\": 1234}", JsonTemplate.class);
    JsonTemplate parsed2 = mapper.readValue("{\"finalValue\": 5678}", JsonTemplate.class);
    // Note both of these return 1234 (even if the second JSON input has 5678).
    System.out.println(parsed1.finalValue);
    System.out.println(parsed2.finalValue);
  }
}
```

**Steps to reproduce the issue**
```
$ which java
/home/chanseok/graalvm/bin/java
$ java -version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06)
OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06, mixed mode, sharing)
$ echo $JAVA_HOME
/home/chanseok/graalvm
$
$ git clone https://github.com/chanseokoh/GraalVmNativeImageAgentIssue.git
$ cd GraalVmNativeImageAgentIssue
$ mvn clean package dependency:copy-dependencies
$ java -agentlib:native-image-agent=config-output-dir=/tmp/native-image-config \
    -cp target/dependency/*:target/native-image-agent-issue-1.jar \
    com.example.JacksonIssueDemo
1234
1234
$ native-image --static --no-fallback --no-server \
    -H:ConfigurationFileDirectories=/tmp/native-image-config \
    -cp target/dependency/*:target/native-image-agent-issue-1.jar \
    com.example.JacksonIssueDemo
$ ./com.example.jacksonissuedemo
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Cannot set final field: com.example.JacksonIssueDemo$JsonTemplate.finalValue. Enable by specifying "allowWrite" for this field in the reflection configuration.
 at [Source: (String)"{"finalValue": 1234}"; line: 1, column: 16] (through reference chain: com.example.JacksonIssueDemo$JsonTemplate["finalValue"])
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:623)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:611)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:152)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4526)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3468)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3436)
        at com.example.JacksonIssueDemo.main(JacksonIssueDemo.java:14)
Caused by: java.lang.IllegalAccessException: Cannot set final field: com.example.JacksonIssueDemo$JsonTemplate.finalValue. Enable by specifying "allowWrite" for this field in the reflection configuration.
        at java.lang.reflect.Field.set(Field.java:780)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:150)
        ... 6 more
$
$ # Now manually add "allowWrite" reflection configuration to fix this issue.
$ cat fix.patch
--- a/reflect-config.json       2020-11-18 15:49:44.605510971 -0500
+++ b/reflect-config.json       2020-11-18 15:39:38.432507858 -0500
@@ -3,7 +3,10 @@
   "name":"com.example.JacksonIssueDemo$JsonTemplate",
   "allDeclaredFields":true,
   "allDeclaredMethods":true,
-  "allDeclaredConstructors":true
+  "allDeclaredConstructors":true,
+  "fields":[
+    {"name":"finalValue", "allowWrite": true}
+  ]
 },
 {
   "name":"com.fasterxml.jackson.databind.ext.Java7HandlersImpl",
$ patch -p1 /tmp/native-image-config/reflect-config.json < fix.patch
patching file /tmp/native-image-config/reflect-config.json
$ native-image --static --no-fallback --no-server \
    -H:ConfigurationFileDirectories=/tmp/native-image-config \
    -cp target/dependency/*:target/native-image-agent-issue-1.jar \
    com.example.JacksonIssueDemo
$ # Works fine.
$ ./com.example.jacksonissuedemo
1234
1234
$
```

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06, mixed mode, sharing)**
 - JDK major version: **11**
 - OS: **Ubuntu-based Linux**
 - Architecture: **AMD64**

**Comment by mcraj017** [comment]
@chanseokoh Thanks for reporting the issue
We will look into it

**Comment by mcraj017** [comment]
@chanseokoh you can add the allowWrite manually in /tmp/native-image-config/reflect-config.json
and your application will work
`[
{
  "name":"com.example.JacksonIssueDemo$JsonTemplate",
  "allDeclaredFields":true,
  "allDeclaredMethods":true,
  "allDeclaredConstructors":true,
"fields" : [
      { "name" : "finalValue", "allowWrite" : true }
    ]
},
{
  "name":"com.fasterxml.jackson.databind.ext.Java7HandlersImpl",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
{
  "name":"com.fasterxml.jackson.databind.ext.Java7SupportImpl",
  "methods":[{"name":"<init>","parameterTypes":[] }]
}]`

**Comment by chanseokoh** [comment]
That's what I did as I said in the issue description, which is not really feasible in our case.

**Comment by mcraj017** [comment]
@chanseokoh Native-image is early adopter technology, so with every update we are making it better and better, for now The agent only observes lookups of fields via JNI or reflection, not each individual write of a field. Doing so would significantly slow down accesses. We can detect illegal accesses at image runtime however.
for now, I will check with the dev team, if there is any backgroud

**Comment by mcraj017** [comment]
@chanseokoh for now, the only way to resolve this is only changing the config files manually, as it is early adopter technology, please always use the latest version

**Comment by chanseokoh** [comment]
I get that for now I must change the generate config files manually. However, could you reopen this issue for tracking a feature request so that eventually the agent has a chance to generate correct config files?
