### ISSUE TITLE
JetBrains Skija Unsupported JNI version native-image

### ISSUE THREAD

**Issue by davidbruce** [oracle/graal#3005]
**Describe the issue**
I'm trying to run Jetbrain's "Rendering the first image" example from https://github.com/JetBrains/skija/blob/master/docs/Getting%20Started.md.  It seems to compile fine, but once I attempt to run it, it fails.  The application runs fine as a jar, but it extracts the libskija.so to `/tmp/skija_(nanosecondtime)/libskija.so` and I think that is where the issue stems from.   Here is the code that is loading the shared library: https://github.com/JetBrains/skija/blob/master/shared/src/main/java/org/jetbrains/skija/impl/Library.java

I did run the jar once with `-agentlib:native-image-agent=config-output-dir=lib/META-INF/native-image` to create the config files. 

**Steps to reproduce the issue**
native-image.properties:
```
ImageName=Main
Args=-H:+ReportExceptionStackTraces -H:TraceClassInitialization=true -H:+AllowVMInspection \
-H:+JNI \
--allow-incomplete-classpath --verbose --no-server --no-fallback --report-unsupported-elements-at-runtime -DremoveUnusedAutoconfig=true
```
Java Code:
```java
import org.jetbrains.skija.*;

public class Main  {
    public static void main(String[] args) {
        var surface = Surface.makeRasterN32Premul(200, 200);
        var skcanvas = surface.getCanvas();
        var background = new Paint();
        background.setColor(0xFFFFFFFF);
        var paint = new Paint();
        paint.setColor(0xFF0000FF);
        skcanvas.drawRect(Rect.makeXYWH(0, 0, 200, 200), background);
        var radius = 0.0;

        skcanvas.drawCircle(100, 100, 100, paint);
        var image = surface.makeImageSnapshot();
        var pngData = image.encodeToData(EncodedImageFormat.JPEG);
        var pngBytes = pngData.getBytes();        

        try{
            var path = java.nio.file.Path.of("output.png");
            java.nio.file.Files.write(path, pngBytes);
        } catch(Exception e) {

        }

    }
}
```

**Describe GraalVM and your environment:**
```
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment GraalVM CE 21.0.0-dev (build 11.0.9+10-jvmci-20.3-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0-dev (build 11.0.9+10-jvmci-20.3-b06, mixed mode, sharing)
```

**More details**
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unsupported JNI version 0xffffffff, required by /tmp/skija_75783271105621/libskija.so
        at com.oracle.svm.jni.JNILibraryInitializer.checkSupportedJNIVersion(JNILibraryInitializer.java:80)
        at com.oracle.svm.jni.JNILibraryInitializer.callOnLoadFunction(JNILibraryInitializer.java:73)
        at com.oracle.svm.jni.JNILibraryInitializer.initialize(JNILibraryInitializer.java:127)
        at com.oracle.svm.core.jdk.NativeLibrarySupport.addLibrary(NativeLibrarySupport.java:185)
        at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibrary0(NativeLibrarySupport.java:141)
        at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibrary(NativeLibrarySupport.java:102)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:270)
        at java.lang.Runtime.load0(Runtime.java:768)
        at java.lang.Runtime.load(Runtime.java:238)
        at java.lang.System.load(System.java:357)
        at org.jetbrains.skija.impl.Library.load(Library.java:33)
        at org.jetbrains.skija.impl.Library.staticLoad(Library.java:15)
        at org.jetbrains.skija.Surface.<clinit>(Surface.java:7)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:351)
```

If I add 
--initialize-at-build-time=org.jetbrains.skija 
I get the following instead:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.jetbrains.skija.Surface._nMakeRasterN32Premul(II)J [symbol: Java_org_jetbrains_skija_Surface__1nMakeRasterN32Premul or Java_org_jetbrains_skija_Surface__1nMakeRasterN32Premul__II]
        at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:153)
        at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
        at org.jetbrains.skija.Surface._nMakeRasterN32Premul(Surface.java)
        at org.jetbrains.skija.Surface.makeRasterN32Premul(Surface.java:17)
        at Main.main(Main.java:5)
```

**Comment by dmlloyd** [comment]
I've seen this in other JNI libraries with GraalVM.  It happens when the JNI_OnLoad method returns `-1` (aka `JNI_ERR`) - which occurs in more than one JNI library "in the wild" when there is an error, even though the JNI spec doesn't actually document that error return and the runtime generally recognizes it as `Unsupported JNI version 0xffffffff` (where `0xffffffff` is the twos-complement unsigned representation of `-1`).

Most often this is going to be due to a class or field not being registered for JNI access.

**Comment by fernando-valdez** [comment]
Hi @davidbruce, 
Thanks for reporting this issue, I will take a look at this and will go back to you with any new feedback

**Comment by davidbruce** [comment]
Thanks for looking into this!

**Comment by spket** [comment]
It's Skija's bug, it does not need module feature in JNI, so it return a wrong JNI Version.

Change it to JNI_VERSION_1_8 I'm able to build native image with GraalVM, take a look [Native GUI application with SWT and Skija on Raspberry Pi](https://www.spket.com/blog/native-gui-app-with-swt-and-skija-on-raspberry-pi/)
