### ISSUE TITLE
UnsupportedFeatureException: VarHandle object must be a compile time constant with Java 11

### ISSUE THREAD

**Issue by ilopmar** [oracle/graal#3028]
**Describe the issue**

We've added support to create Micronaut GraalVM native images with Liquibase, and the native-image build fails when using H2 and JDK11. It works properly with JDK8.

**Steps to reproduce the issue**

- `git clone https://github.com/micronaut-graal-tests/micronaut-liquibase-graal`
- `cd micronaut-liquibase-graal`
- `git checkout 2.2.x_h2`
- Use GraalVM 20.3.0-JDK11 or GraalVM compiled from master.
- `./build-native-image.sh`
- The application fails to build. See the stacktrace bellow.

**Describe GraalVM and your environment:**
 - GraalVM version: **20.3.0-JDK11 and 66df1ab28dccffad1cd3bc5d1527120b48a4e3b2**
 - JDK major version: **11**
 - OS: **Linux Mint 20**
 - Architecture: **AMD64**

**More details**

```
[liquibase-h2:87065]    classlist:   1,678.88 ms,  0.96 GB
[liquibase-h2:87065]        (cap):     429.61 ms,  1.18 GB
[liquibase-h2:87065]        setup:   1,681.62 ms,  1.18 GB
[liquibase-h2:87065]     (clinit):   1,420.24 ms,  5.47 GB
[liquibase-h2:87065]   (typeflow):  19,386.43 ms,  5.47 GB
[liquibase-h2:87065]    (objects):  30,233.49 ms,  5.47 GB
[liquibase-h2:87065]   (features):   3,293.05 ms,  5.47 GB
[liquibase-h2:87065]     analysis:  60,302.58 ms,  6.35 GB
Error: Unsupported features in 9 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace: 
        at parsing org.h2.util.Bits.readDouble(Bits.java:184)
Call path from entry point to org.h2.util.Bits.readDouble(byte[], int): 
        at org.h2.util.Bits.readDouble(Bits.java:184)
        at org.h2.util.geometry.EWKBUtils$EWKBSource.readCoordinate(EWKBUtils.java:217)
        at org.h2.util.geometry.EWKBUtils.addCoordinate(EWKBUtils.java:475)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:376)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:292)
        at org.h2.value.ValueGeometry.getEnvelopeNoCopy(ValueGeometry.java:238)
        at org.h2.mvstore.db.MVSpatialIndex$FindBoundsCursor.check(MVSpatialIndex.java:474)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.fetchNext(MVRTreeMap.java:527)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.hasNext(MVRTreeMap.java:484)
        at java.util.AbstractMap.hashCode(AbstractMap.java:526)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getFieldNameByID(JNIReflectionDictionary.java:307)
        at com.oracle.svm.jni.functions.JNIFunctions.ToReflectedField(JNIFunctions.java:855)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ToReflectedField_80d8233579d5215df0227b770e5c01228a0de9b9(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace: 
        at parsing org.h2.util.Bits.readDoubleLE(Bits.java:198)
Call path from entry point to org.h2.util.Bits.readDoubleLE(byte[], int): 
        at org.h2.util.Bits.readDoubleLE(Bits.java:198)
        at org.h2.util.geometry.EWKBUtils$EWKBSource.readCoordinate(EWKBUtils.java:217)
        at org.h2.util.geometry.EWKBUtils.addCoordinate(EWKBUtils.java:475)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:376)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:292)
        at org.h2.value.ValueGeometry.getEnvelopeNoCopy(ValueGeometry.java:238)
        at org.h2.mvstore.db.MVSpatialIndex$FindBoundsCursor.check(MVSpatialIndex.java:474)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.fetchNext(MVRTreeMap.java:527)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.hasNext(MVRTreeMap.java:484)
        at java.util.AbstractMap.hashCode(AbstractMap.java:526)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getFieldNameByID(JNIReflectionDictionary.java:307)
        at com.oracle.svm.jni.functions.JNIFunctions.ToReflectedField(JNIFunctions.java:855)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ToReflectedField_80d8233579d5215df0227b770e5c01228a0de9b9(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace: 
        at parsing org.h2.util.Bits.readInt(Bits.java:128)
Call path from entry point to org.h2.util.Bits.readInt(byte[], int): 
        at org.h2.util.Bits.readInt(Bits.java:128)
        at org.h2.security.XTEA.encryptBlock(XTEA.java:68)
        at org.h2.security.XTEA.encrypt(XTEA.java:53)
        at org.h2.security.SecureFileStore.write(SecureFileStore.java:68)
        at org.h2.store.FileStoreOutputStream.write(FileStoreOutputStream.java:70)
        at sun.security.ssl.SSLSocketOutputRecord.flush(SSLSocketOutputRecord.java:251)
        at java.io.PrintStream.flush(PrintStream.java:417)
        at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:763)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace: 
        at parsing org.h2.util.Bits.readIntLE(Bits.java:142)
Call path from entry point to org.h2.util.Bits.readIntLE(byte[], int): 
        at org.h2.util.Bits.readIntLE(Bits.java:142)
        at org.h2.util.geometry.EWKBUtils$EWKBSource.readInt(EWKBUtils.java:206)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:396)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:292)
        at org.h2.value.ValueGeometry.getEnvelopeNoCopy(ValueGeometry.java:238)
        at org.h2.mvstore.db.MVSpatialIndex$FindBoundsCursor.check(MVSpatialIndex.java:474)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.fetchNext(MVRTreeMap.java:527)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.hasNext(MVRTreeMap.java:484)
        at java.util.AbstractMap.hashCode(AbstractMap.java:526)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getFieldNameByID(JNIReflectionDictionary.java:307)
        at com.oracle.svm.jni.functions.JNIFunctions.ToReflectedField(JNIFunctions.java:855)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ToReflectedField_80d8233579d5215df0227b770e5c01228a0de9b9(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace: 
        at parsing org.h2.util.Bits.readLong(Bits.java:156)
Call path from entry point to org.h2.util.Bits.readLong(byte[], int): 
        at org.h2.util.Bits.readLong(Bits.java:156)
        at org.h2.value.Value.convertToLong(Value.java:958)
        at org.h2.value.Value.convertTo(Value.java:766)
        at org.h2.value.Value.convertTo(Value.java:723)
        at org.h2.jdbc.JdbcPreparedStatement.setObject(JdbcPreparedStatement.java:565)
        at com.oracle.svm.reflect.PreparedStatement_setObject_5b494a5a8f7fcd76e8cd88a6cab852968d728fd3_2959.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at javax.xml.transform.TransformerException.printStackTrace(TransformerException.java:345)
        at javax.xml.transform.TransformerException.printStackTrace(TransformerException.java:285)
        at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:759)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace: 
        at parsing org.h2.util.Bits.uuidToBytes(Bits.java:212)
Call path from entry point to org.h2.util.Bits.uuidToBytes(long, long): 
        at org.h2.util.Bits.uuidToBytes(Bits.java:211)
        at org.h2.value.ValueUuid.getBytes(ValueUuid.java:201)
        at org.h2.jdbc.JdbcResultSet.getBytes(JdbcResultSet.java:1072)
        at org.h2.store.LobStorageBackend.readBlock(LobStorageBackend.java:232)
        at org.h2.store.LobStorageBackend$LobInputStream.fillBuffer(LobStorageBackend.java:770)
        at org.h2.store.LobStorageBackend$LobInputStream.skip(LobStorageBackend.java:706)
        at sun.net.www.MeteredStream.skip(MeteredStream.java:147)
        at sun.net.www.http.KeepAliveStreamCleaner.run(KeepAliveStreamCleaner.java:133)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
        at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace: 
        at parsing org.h2.util.Bits.writeDouble(Bits.java:300)
Call path from entry point to org.h2.util.Bits.writeDouble(byte[], int, double): 
        at org.h2.util.Bits.writeDouble(Bits.java:300)
        at org.h2.util.geometry.EWKBUtils$EWKBTarget.writeDouble(EWKBUtils.java:162)
        at org.h2.util.geometry.EWKBUtils$EWKBTarget.addCoordinate(EWKBUtils.java:146)
        at org.h2.util.geometry.EWKTUtils.parseEWKT(EWKTUtils.java:718)
        at org.h2.util.geometry.EWKTUtils.parseEWKT(EWKTUtils.java:608)
        at org.h2.value.ValueGeometry.get(ValueGeometry.java:117)
        at org.h2.value.Transfer.readValue(Transfer.java:771)
        at org.h2.server.TcpServerThread.setParameters(TcpServerThread.java:257)
        at org.h2.server.TcpServerThread.process(TcpServerThread.java:331)
        at org.h2.server.TcpServerThread.run(TcpServerThread.java:175)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
        at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace: 
        at parsing org.h2.util.Bits.writeInt(Bits.java:240)
Call path from entry point to org.h2.util.Bits.writeInt(byte[], int, int): 
        at org.h2.util.Bits.writeInt(Bits.java:240)
        at org.h2.store.Data.writeInt(Data.java:166)
        at org.h2.store.FileStoreOutputStream.write(FileStoreOutputStream.java:61)
        at sun.security.ssl.SSLSocketOutputRecord.flush(SSLSocketOutputRecord.java:251)
        at java.io.PrintStream.flush(PrintStream.java:417)
        at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:763)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace: 
        at parsing org.h2.util.Bits.writeLong(Bits.java:270)
Call path from entry point to org.h2.util.Bits.writeLong(byte[], int, long): 
        at org.h2.util.Bits.writeLong(Bits.java:270)
        at org.h2.security.SecureFileStore.xorInitVector(SecureFileStore.java:102)
        at org.h2.security.SecureFileStore.write(SecureFileStore.java:67)
        at org.h2.store.FileStoreOutputStream.write(FileStoreOutputStream.java:70)
        at sun.security.ssl.SSLSocketOutputRecord.flush(SSLSocketOutputRecord.java:251)
        at java.io.PrintStream.flush(PrintStream.java:417)
        at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:763)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1

```

**Comment by richvim** [comment]
This also appears to be a blocker for Graal-porting projects which use the popular [Caffeine](https://github.com/ben-manes/caffeine) library.

**Comment by chrisvest** [comment]
Having better support for VarHandles in Graal would be very helpful for Netty, as we seek to reduce our reliance on `sun.misc.Unsafe`. Netty is also very widely used, so we need to support Graal native-image build configurations. It would be a lot of trouble to configure every class that makes use of VarHandles, for runtime initialisation.

**Comment by plokhotnyuk** [comment]
@ilopmar It looks that GraalVM CE Java11 22.0.0.2 supports `VarHandle` values initialized in Java classes.

**Comment by linghengqian** [comment]
> @ilopmar It looks that GraalVM CE Java11 22.0.0.2 supports `VarHandle` values initialized in Java classes.

It seems that the use of Varhandle is still very limited？
