### ISSUE TITLE
Imported javascript File is read twice by Truffle virtual file system.

### ISSUE THREAD

**Issue by sir-ion** [oracle/graal#3030]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **20.3.0**
 - CE or EE: **CE**
 - JDK version: **graalvm-ce-java11-20.0.0**
 - OS and OS Version: **Ubuntu 19.10**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
 **OpenJDK 64-Bit Server VM (11.0.6+9-jvmci-20.0-b02) for linux-amd64 JRE (11.0.6+9-jvmci-20.0-b02), built on Jan 20 2020 20:06:41 by "buildslave" with gcc 7.3.0**
```

**Have you verified this issue still happens when using the latest snapshot?** No

**Describe the issue**
I am using the polyglot api to execute some javascript code from Java and I provide a Truffle virtual file system.
When I simply import a javascript es6 module at runtime its file is read twice (i.e., the method `newByteChannel(...)` in the snippet below is called twice).
I think this is not the expected behaviour (as retrieving such file could be expensive).

```java
package com.example;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URI;
import java.nio.ByteBuffer;
import java.nio.channels.SeekableByteChannel;
import java.nio.file.AccessMode;
import java.nio.file.attribute.FileAttribute;
import java.nio.file.DirectoryStream;
import java.nio.file.DirectoryStream.Filter;
import java.nio.file.LinkOption;
import java.nio.file.OpenOption;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.Collections;
import java.util.Map;
import java.util.Set;

import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.HostAccess;
import org.graalvm.polyglot.io.FileSystem;
import org.graalvm.polyglot.ResourceLimits;
import org.graalvm.polyglot.Source;

public class MyTestClass {
  public static void main(final String[] args) throws IOException {
    final Context ctx = Context.newBuilder("js")
    .resourceLimits(ResourceLimits.newBuilder().statementLimit(100_000_000, null).build())
    .allowIO(true)
    .fileSystem(new MyVirtualFileSystem())
    .allowHostClassLoading(false)
    .allowHostAccess(HostAccess.newBuilder(HostAccess.EXPLICIT).allowArrayAccess(true).build())
    .allowExperimentalOptions(true)
    .option("js.strict", "true")
    .option("js.console", "false")
    .option("js.print", "false")
    .option("js.load", "false")
    .option("js.load-from-url", "false")
    .option("js.polyglot-builtin", "false")
    .option("js.ecmascript-version", "2020")
    .build();

    // The content of 'someDep.js' is hard coded inside the newByteChannel(...) method below
    final Source consumerSource = Source.newBuilder("js", "import 'someDep';", "main.js")
        .mimeType("application/javascript+module")
        .build();

    ctx.eval(consumerSource);
  }


  private static class MyVirtualFileSystem implements FileSystem {
    @Override
    public Path parsePath(final URI uri) {
      return Paths.get(uri);
    }

    @Override
    public Path parsePath(final String path) {
      return Paths.get(path);
    }

    @Override
    public void checkAccess(final Path path, final Set<? extends AccessMode> modes, final LinkOption... linkOptions)
        throws IOException {
      // no-op
    }

    @Override
    public void createDirectory(final Path dir, final FileAttribute<?>... attrs) throws IOException {
      // no-op
    }

    @Override
    public void delete(final Path path) throws IOException {
      // no-op
    }

    @Override
    public SeekableByteChannel newByteChannel(final Path path, final Set<? extends OpenOption> options,
        final FileAttribute<?>... attrs) throws IOException {
      (new Exception()).printStackTrace();
      System.out.println("options: " + options);
      System.out.println("attrs: " + Arrays.toString(attrs));
      System.out.println("path: " + path);
      System.out.println("");

      switch (path.toFile().getName()) {
        case "someDep":
          return new MyVirtualFile("export const foo = 1234");
      }
      throw new FileNotFoundException(path.toString());
    }

    @Override
    public DirectoryStream<Path> newDirectoryStream(final Path dir, final Filter<? super Path> filter) throws IOException {
      System.out.println("dir " + dir);
      throw new UnsupportedOperationException();
    }

    @Override
    public Path toAbsolutePath(final Path path) {
      return path;
    }

    @Override
    public Path toRealPath(final Path path, final LinkOption... linkOptions) throws IOException {
      return path;
    }

    @Override
    public Map<String, Object> readAttributes(final Path path, final String attributes, final LinkOption... options)
        throws IOException {
      return Collections.emptyMap();
    }
  }

  public static class MyVirtualFile implements SeekableByteChannel {
    private final ByteBuffer buf;
    private final int length;

    public MyVirtualFile(final String data) {
      final byte[] d = data.getBytes();
      buf = ByteBuffer.wrap(d);
      length = d.length;
    }

    @Override
    public boolean isOpen() {
      return true;
    }

    @Override
    public void close() throws IOException {
      // TODO Auto-generated method stub

    }

    @Override
    public int read(final ByteBuffer dst) throws IOException {
      final int avail = Math.min(dst.remaining(), buf.remaining());
      final ByteBuffer tmp = buf.duplicate ();
      tmp.limit (tmp.position() + avail);
      dst.put(tmp);
      buf.position(buf.position() + avail);
      return avail;
    }

    @Override
    public int write(final ByteBuffer src) throws IOException {
      // TODO Auto-generated method stub
      return 0;
    }

    @Override
    public long position() throws IOException {
      return length - buf.remaining();
    }

    @Override
    public SeekableByteChannel position(final long newPosition) throws IOException {
      buf.position(Math.toIntExact(newPosition));
      return this;
    }

    @Override
    public long size() throws IOException {
      return length;
    }

    @Override
    public SeekableByteChannel truncate(final long size) throws IOException {
      // TODO Auto-generated method stub
      return null;
    }
  }
}

```

**Steps to reproduce the issue**
1. Run the snippet above with the following options
```bash
  --add-opens org.graalvm.truffle/com.oracle.truffle.api=ALL-UNNAMED
  --add-opens org.graalvm.truffle/com.oracle.truffle.api.frame=ALL-UNNAMED    
  --add-opens org.graalvm.truffle/com.oracle.truffle.api.nodes=ALL-UNNAMED 
  --add-opens org.graalvm.truffle/com.oracle.truffle.api.source=ALL-UNNAMED
```

2. The output is the following
```java
java.lang.Exception
        at com.gullivernet.goal.tasks.scripting.MyTestClass$MyVirtualFileSystem.newByteChannel(MyTestClass.java:83)
        at org.graalvm.truffle/com.oracle.truffle.api.TruffleFile.newByteChannel(TruffleFile.java:786)
        at org.graalvm.truffle/com.oracle.truffle.api.TruffleFile.newInputStream(TruffleFile.java:815)
        at com.oracle.truffle.llvm.runtime.LLVMFileDetector.readMagicWord(LLVMFileDetector.java:67)
        at com.oracle.truffle.llvm.runtime.LLVMFileDetector.findMimeType(LLVMFileDetector.java:52)
        at org.graalvm.truffle/com.oracle.truffle.api.TruffleFile.getMimeType(TruffleFile.java:1566)
        at org.graalvm.truffle/com.oracle.truffle.api.TruffleFile.getMimeType(TruffleFile.java:1555)
        at org.graalvm.truffle/com.oracle.truffle.api.LanguageAccessor$LanguageImpl.getEncoding(LanguageAccessor.java:393)
        at org.graalvm.truffle/com.oracle.truffle.api.source.SourceAccessor.getEncoding(SourceAccessor.java:69)
        at org.graalvm.truffle/com.oracle.truffle.api.source.Source.getEncoding(Source.java:1342)
        at org.graalvm.truffle/com.oracle.truffle.api.source.Source.buildSource(Source.java:1057)
        at org.graalvm.truffle/com.oracle.truffle.api.source.Source$SourceBuilder.build(Source.java:1574)
        at org.graalvm.truffle/com.oracle.truffle.api.source.Source$LiteralBuilder.build(Source.java:1734)
        at com.oracle.truffle.js.runtime.JSRealm$2.resolveImportedModule(JSRealm.java:1960)
        at com.oracle.truffle.js.parser.GraalJSEvaluator.hostResolveImportedModule(GraalJSEvaluator.java:339)
        at com.oracle.truffle.js.parser.GraalJSEvaluator.innerModuleInstantiation(GraalJSEvaluator.java:507)
        at com.oracle.truffle.js.parser.GraalJSEvaluator.moduleInstantiation(GraalJSEvaluator.java:479)
        at com.oracle.truffle.js.parser.GraalJSEvaluator$2.evalModule(GraalJSEvaluator.java:279)
        at com.oracle.truffle.js.parser.GraalJSEvaluator$2.execute(GraalJSEvaluator.java:273)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:474)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:449)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:419)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:403)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:349)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:67)
        at com.oracle.truffle.js.lang.JavaScriptLanguage$1.execute(JavaScriptLanguage.java:228)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:474)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:449)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:419)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:403)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:330)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:320)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:822)
        at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:345)
        at com.gullivernet.goal.tasks.scripting.MyTestClass.main(MyTestClass.java:49)
options: [READ]
attrs: []
path: someDep

java.lang.Exception
        at com.gullivernet.goal.tasks.scripting.MyTestClass$MyVirtualFileSystem.newByteChannel(MyTestClass.java:83)
        at org.graalvm.truffle/com.oracle.truffle.api.TruffleFile.newByteChannel(TruffleFile.java:786)
        at org.graalvm.truffle/com.oracle.truffle.api.TruffleFile.readAllBytes(TruffleFile.java:856)
        at org.graalvm.truffle/com.oracle.truffle.api.source.Source.read(Source.java:1200)
        at org.graalvm.truffle/com.oracle.truffle.api.source.Source.buildSource(Source.java:1058)
        at org.graalvm.truffle/com.oracle.truffle.api.source.Source$SourceBuilder.build(Source.java:1574)
        at org.graalvm.truffle/com.oracle.truffle.api.source.Source$LiteralBuilder.build(Source.java:1734)
        at com.oracle.truffle.js.runtime.JSRealm$2.resolveImportedModule(JSRealm.java:1960)
        at com.oracle.truffle.js.parser.GraalJSEvaluator.hostResolveImportedModule(GraalJSEvaluator.java:339)
        at com.oracle.truffle.js.parser.GraalJSEvaluator.innerModuleInstantiation(GraalJSEvaluator.java:507)
        at com.oracle.truffle.js.parser.GraalJSEvaluator.moduleInstantiation(GraalJSEvaluator.java:479)
        at com.oracle.truffle.js.parser.GraalJSEvaluator$2.evalModule(GraalJSEvaluator.java:279)
        at com.oracle.truffle.js.parser.GraalJSEvaluator$2.execute(GraalJSEvaluator.java:273)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:474)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:449)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:419)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:403)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:349)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:67)
        at com.oracle.truffle.js.lang.JavaScriptLanguage$1.execute(JavaScriptLanguage.java:228)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:474)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:449)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:419)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:403)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:330)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:320)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:822)
        at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:345)
        at com.gullivernet.goal.tasks.scripting.MyTestClass.main(MyTestClass.java:49)
options: []
attrs: []
path: someDep
```

**Expected behavior**
The `newByteChannel(...)` method should be called only once.

**Additional context**
See the output above for the stack traces

**Comment by mcraj017** [comment]
@sir-ion Thanks for reporting the bug
We will check it and let you know the findings

**Comment by mcraj017** [comment]
@sir-ion bug has been raised with our dev team, will update you once its fixed

**Comment by mcraj017** [comment]
@sir-ion The bug will e fixed in future releases 
please test the latest one from the below repo
https://github.com/graalvm/graalvm-ce-dev-builds/releases
