### ISSUE TITLE
Duplicate key error in GraalVM dashboard

### ISSUE THREAD

**Issue by sdeleuze** [oracle/graal#3054]
When we try to use GraalVM dashboard in one of the [Spring Native samples ](https://github.com/spring-projects-experimental/spring-graalvm-native/tree/master/spring-graalvm-native-samples) (let say the `rsocket` one), we got this error:

```
Printing Dashboard Code-Breakdown BGV dump to /home/seb/workspace/spring-graalvm-native/spring-graalvm-native-samples/rsocket/target/native-image/dump.bgv
[rsocket:75568]      compile:  34,002.41 ms,  6.77 GB
Print of Dashboard dump output ended.
Fatal error:java.lang.IllegalStateException: java.lang.IllegalStateException: Duplicate key io.netty.util.concurrent.AbstractScheduledEventExecutor.schedule(Callable, long, TimeUnit) ScheduledFuture (attempted merging values 53 and 1803)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:483)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:350)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:509)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:115)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:541)
Caused by: java.lang.IllegalStateException: Duplicate key io.netty.util.concurrent.AbstractScheduledEventExecutor.schedule(Callable, long, TimeUnit) ScheduledFuture (attempted merging values 53 and 1803)
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3605)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.oracle.svm.hosted.dashboard.CodeBreakdownJsonObject.getData(CodeBreakdownJsonObject.java:55)
	at com.oracle.svm.hosted.dashboard.DashboardDumpFeature.lambda$afterCompilation$5(DashboardDumpFeature.java:170)
	at com.oracle.graal.pointsto.reports.ReportUtils.reportImpl(ReportUtils.java:153)
	at com.oracle.graal.pointsto.reports.ReportUtils.report(ReportUtils.java:144)
	at com.oracle.svm.hosted.dashboard.DashboardDumpFeature.afterCompilation(DashboardDumpFeature.java:163)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$doRun$3(NativeImageGenerator.java:634)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:634)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:471)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

It may be related to optional types not in the classpath and/or generics based on some observation we did.

**Comment by mcraj017** [comment]
@sdeleuze it has been added for future natiuve-image releases (21.1), please follow https://www.graalvm.org/ to get updated with the new releses

**Comment by sdeleuze** [comment]
@mcraj017 Just to be sure, will it be available as of 21.0 or will we have to wait for 21.1?

**Comment by Ondrej-Douda** [comment]
The fix should be present in 21 version and also backported to 20.3.1...

**Comment by sdeleuze** [comment]
Nice, please update the target version accordingly.
