### ISSUE TITLE
Wrapping with custom JVMCI compiler config breaks something in JIT

### ISSUE THREAD

**Issue by headius** [oracle/graal#306]
I'm not sure how exactly to describe this...

I have been working on a wrapper for Graal that can plug into JVMCI but allow us to tweak compilation specific to JRuby's workloads. The code for this is at https://github.com/jruby/jruby-graal.

Originally, the code simply wrapped and delegated all the Graal JVMCI endpoints, and this worked correctly to decorate Graal's high tier with a special pass for JRuby.

However, now it appears this method of wrapping Graal breaks compilation in some way. I now get these errors:

```
Thread[JVMCI CompilerThread0,9,system]: Compilation of java.util.zip.ZipFile$Source.hashN(byte[], int, int) failed: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: org.graalvm.compiler.debug.GraalError: org.graalvm.compiler.nodes.extended.BranchProbabilityNode.probability(double, boolean) should have been handled by a GeneratedInvocationPlugin
```

Even worse, if I remove all my customizations except for returning my own subclass of CoreCompilerConfiguration, it *still* fails, even though the code is identical to Graal's JVMCI plugin (other than the subclass):

```java
    public static class JRubyCompilerConfigurationFactory extends CoreCompilerConfigurationFactory {
        @Override
        public CompilerConfiguration createCompilerConfiguration() {
//            return new CoreCompilerConfiguration();
            return new JRubyGraalCompilerConfiguration();
        }
    }

    public static class JRubyGraalCompilerConfiguration extends CoreCompilerConfiguration {
    }
```

If I change the code above to return CoreCompilerConfiguration, I get no errors. If I use mine, it errors.

Doesn't it seem as though something about compilation is changing solely based on whether the configuration class came from Graal?

**Comment by headius** [comment]
Note that the errors do appear to affect performance; with a real CoreCompilerConfiguration, JRuby performs 800s better than with JRubyGraalCompilerConfiguration.

**Comment by dougxc** [comment]
Are you building Graal or using existing jars?

**Comment by headius** [comment]
I am building Graal from master.

**Comment by headius** [comment]
Other environment details:

```
$ java -version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

$ java -Djruby.jit.logging -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI \
-XX:+UseJVMCICompiler -Djvmci.Compiler=graal \
--module-path ../jruby-graal/target/jruby-graal-0.1-SNAPSHOT.jar:../jruby-graal/graal/compiler/mxbuild/modules/jdk.internal.vm.compiler.jar:../jruby-graal/graal/sdk/mxbuild/modules/org.graalvm.graal_sdk.jar:../jruby-graal/graal/truffle/mxbuild/modules/com.oracle.truffle.truffle_api.jar \
--add-exports jdk.internal.vm.ci/jdk.vm.ci.services=jruby.graal \
-Djruby.home=/Users/headius/projects/jruby -Djruby.fixnum.cache=false \
-Djruby.compile.invokedynamic -Dgraal.CompilationFailureAction=Diagnose \
-jar ../jruby/lib/jruby.jar ../jruby-graal/blah.rb
```

**Comment by dougxc** [comment]
Are you relying on Eclipse to do the building? That's the only time I've seen these `should have been handled by a GeneratedInvocationPlugin` errors (due to Eclipse's somewhat broken annotation processing).

**Comment by headius** [comment]
No, I am cloning the repository into a git submodule and using mx to build it. Then I incorporate the results into my plugin.

I run it exactly the same way whether I use CoreCompilerConfiguration or JRubyGraalCompilerConfiguration and it works fine in the former case.

**Comment by headius** [comment]
Sorry, I don't incorporate Graal itself into my plugin; I use the Graal jars as shown on the command line above, plus my plugin jar. In both cases (working and not) I ask for the "jruby-graal" compiler, and I can see it's using my code.

**Comment by headius** [comment]
FWIW changing my code here only rebuilds my plugin; Graal itself remains exactly the same in both cases, but doesn't work if I use my own compiler config class.

**Comment by dougxc** [comment]
Can you please paste the complete stack trace.

**Comment by headius** [comment]
First trace I see:

```
Thread[JVMCI CompilerThread0,9,system]: Compilation of java.util.zip.ZipFile$Source.hashN(byte[], int, int) failed: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: org.graalvm.compiler.debug.GraalError: org.graalvm.compiler.nodes.extended.BranchProbabilityNode.probability(double, boolean) should have been handled by a GeneratedInvocationPlugin
	at parsing org.graalvm.compiler.hotspot.replacements.InstanceOfSnippets.instanceofExact(InstanceOfSnippets.java:137)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2284)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3014)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:2831)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:848)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:742)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:93)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:47)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:195)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:40)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:36)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.ReplacementsImpl$GraphMaker.buildInitialGraph(ReplacementsImpl.java:456)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.ReplacementsImpl$GraphMaker.makeGraph(ReplacementsImpl.java:362)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.ReplacementsImpl.makeGraph(ReplacementsImpl.java:322)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.ReplacementsImpl.getSnippet(ReplacementsImpl.java:228)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.SnippetTemplate.<init>(SnippetTemplate.java:709)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.SnippetTemplate$AbstractTemplates.template(SnippetTemplate.java:654)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.InstanceOfSnippetsTemplates.lower(InstanceOfSnippetsTemplates.java:99)
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.meta.DefaultHotSpotLoweringProvider.lower(DefaultHotSpotLoweringProvider.java:243)
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.amd64.AMD64HotSpotLoweringProvider.lower(AMD64HotSpotLoweringProvider.java:82)
	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.java.InstanceOfNode.lower(InstanceOfNode.java:106)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase$Round.process(LoweringPhase.java:460)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase$Round.access$200(LoweringPhase.java:336)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase$Round$ProcessFrame.preprocess(LoweringPhase.java:400)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.processBlock(LoweringPhase.java:559)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase$Round.run(LoweringPhase.java:385)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:47)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:195)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:137)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:203)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:54)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:36)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:195)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:137)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.lower(LoweringPhase.java:256)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:249)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:89)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:195)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:137)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:203)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:195)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:137)
	at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:234)
	at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:172)
	at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:158)
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileHelper(HotSpotGraalCompiler.java:189)
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:202)
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:169)
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:94)
	at jdk.internal.vm.compiler/org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:165)
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:317)
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:142)
	at jdk.internal.vm.compiler/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:108)
	at jruby.graal@0.1-SNAPSHOT/org.jruby.jvmci.JRubyJVMCI$Compiler.compileMethod(JRubyJVMCI.java:125)
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:433)
Caused by: org.graalvm.compiler.debug.GraalError: org.graalvm.compiler.nodes.extended.BranchProbabilityNode.probability(double, boolean) should have been handled by a GeneratedInvocationPlugin
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.ReplacementsImpl.notifyNotInlined(ReplacementsImpl.java:173)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.createNonInlinedInvoke(BytecodeParser.java:1743)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1666)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1367)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1349)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:4611)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3009)
	... 52 more
```

**Comment by headius** [comment]
I've included full output with max fails set much higher. Perhaps something in there will be helpful (temporary gist): https://gist.githubusercontent.com/headius/a0d07e9483bfdba666e01b43814bdcd4/raw/b8c559e4530870f423b9351bc695b0398254a4c7/gistfile1.txt

**Comment by dougxc** [comment]
It's hard to say what's going wrong. It seems as though the `HotSpotBackendFactory` being created by `JRubyGraalCompilerConfigurationFactory` is missing or not registering some GraphBuilder plugins (e.g. like [this](https://github.com/oracle/graal/blob/480b839bb3cf5863a2c2458e3071059b2586c239/compiler/src/org.graalvm.compiler.hotspot.amd64/src/org/graalvm/compiler/hotspot/amd64/AMD64HotSpotBackendFactory.java#L157)).

**Comment by headius** [comment]
JRubyCompilerConfigurationFactory extends CoreConfigurationFactory, and does not override the backend creation.

**Comment by tkrodriguez** [comment]
Maybe it something about running with 9?  How does it behave with JDK8?

**Comment by dougxc** [comment]
Can you verify that your `graal.jar` has the classes generated for these plugins. For example:
```
> jar tf mxbuild/dists/graal.jar | grep probability
org/graalvm/compiler/nodes/extended/PluginFactory_BranchProbabilityNode$BranchProbabilityNode_probability.class
```

**Comment by dougxc** [comment]
I would try this on JDK8 to see if it is a module thing.

**Comment by headius** [comment]
Wouldn't it fail with CoreCompilerConfiguration if something were wrong with my Graal jar?

In any case, they're there.

```
$ jar tf mxbuild/dists/graal.jar | grep probability
org/graalvm/compiler/nodes/extended/PluginFactory_BranchProbabilityNode$BranchProbabilityNode_probability.class
```

I should reiterate that this plugin works fine if I return a new CoreCompilerConfiguration, and fails if I return my subclass of CoreCompilerConfiguration.

**Comment by headius** [comment]
I will try to get this to run on 8. The build and command line are set up for Java 9, so it will take me a bit.

**Comment by headius** [comment]
I'm having trouble finding the right docs to use my own build of Graal with labs's JDK8+JVMCI. It only seems to be able to locate the built-in Graal.

**Comment by headius** [comment]
Ok, nevermind, it seems to be picking it up now.

**Comment by headius** [comment]
I can confirm that running under JDK8+JVMCI does not appear to have the same problem.

```
java -Djruby.jit.logging -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI \
-XX:+UseJVMCICompiler -Djvmci.Compiler=jruby-graal \
-Xbootclasspath/a:../jruby-graal/target/jruby-graal-0.1-SNAPSHOT.jar:../jruby-graal/graal/compiler/mxbuild/modules/jdk.internal.vm.compiler.jar:../jruby-graal/graal/sdk/mxbuild/modules/org.graalvm.graal_sdk.jar:../jruby-graal/graal/truffle/mxbuild/modules/com.oracle.truffle.truffle_api.jar:/Library/Java/JavaVirtualMachines/jdk8-jvmci/Contents/Home/jre/lib/jvmci/jvmci-api.jar:/Library/Java/JavaVirtualMachines/jdk8-jvmci/Contents/Home/jre/lib/jvmci/jvmci-hotspot.jar \
-Djruby.home=/Users/headius/projects/jruby -Djruby.fixnum.cache=false \
-Djruby.compile.invokedynamic -Dgraal.CompilationFailureAction=Print \
-jar ../jruby/lib/jruby.jar ../jruby-graal/blah.rb
```

**Comment by tkrodriguez** [comment]
Maybe you need to add some module commands to make stuff visible to your custom compiler?

**Comment by headius** [comment]
I don't get any errors about things being unavailable, but perhaps Graal is swallowing something. However this is literally *just* extending one class and returning an instance of that subclass instead of an instance of the superclass. The logic it inherits should all still live within the graal module.

I'm not sure what I'd expose since it doesn't give a very good indication why it failed.

**Comment by dougxc** [comment]
@headius , if you send me the relevant jar files, I can try reproduce locally and figure out what's going on.

**Comment by tkrodriguez** [comment]
If you had a fastdebug build you could try -XX:+TraceExceptions to see if any errors are being hidden from you.

**Comment by chrisseaton** [comment]
@headius off topic, but is my understanding right that your plugin makes _all_ objects in the JRuby package virtualisable?

https://github.com/jruby/jruby-graal/blob/f590927edf26c376f4ec939a37a359cf7121bbd3/src/main/java/org/jruby/jvmci/JRubyJVMCI.java#L195

Do you not have any internal implementation objects that need identity?

**Comment by headius** [comment]
@chrisseaton That's just an experiment. It won't virtualize everything.

**Comment by headius** [comment]
@dougxc I've pushed a snapshot of the wrapper to https://oss.sonatype.org/content/repositories/snapshots/org/jruby/jruby-graal/0.1-SNAPSHOT/

The rest of the jars (graal, truffle, jvmci, etc) are just built from graal master today and are not included with my wrapper.

**Comment by dougxc** [comment]
Sorry for the delay in getting back to this but I've figured out where things are going wrong:
https://github.com/oracle/graal/blob/440d89a72cdeb7bc7951e37462cd30bf12fa3ae6/compiler/src/org.graalvm.compiler.hotspot/src/org/graalvm/compiler/hotspot/meta/HotSpotInvocationPlugins.java#L134
I'm working on a fix now.

**Comment by dougxc** [comment]
The problem here is that on JDK 9+, Graal uses module membership to determine if a method is trusted in terms of whether an intrinsic available for the method can be applied. The set of trusted modules is built from the transitive set of modules required by the module defining the instance of `CompilerConfiguration` in use. In your case, this is `org.jruby.jvmci.JRubyJVMCI.JRubyGraalCompilerConfiguration` which is loaded from an automatic module. An automatic module [only requires](https://docs.oracle.com/javase/9/docs/api/java/lang/module/ModuleDescriptor.html#requires--) the `java.base` module. The preferred solution is to make your `jruby.graal` module an non-automatic module.
