### ISSUE TITLE
com.oracle.svm.hosted.substitute.DeletedElementException

### ISSUE THREAD

**Issue by goeh** [oracle/graal#3067]
**Describe the issue**
I'm trying to build a native image from a Micronaut+Picocli+MinIO project that I developed but I get an exception `com.oracle.svm.hosted.substitute.DeletedElementException` and if I add `--report-unsupported-elements-at-runtime` I get `java.lang.RuntimeException: class io.minio.ListObjectsArgs must have no argument constructor` at runtime.

This offending class is in a 3:rd party library [minio-java](https://github.com/minio/minio-java/blob/master/api/src/main/java/io/minio/ListObjectsArgs.java) and it does not have any constructors defined. But it does use a non-trivial **builder** and **reflection** to create instances. I forked minio-java and added a no-argument constructor to ListObjectsArgs but did not help.

**Steps to reproduce the issue**
1. **git clone --depth 1 https://github.com/technipelago/minio-util**
2. **./build-native-image.sh** (there are two variants inside this script, one commented out)
3. **docker run -d -p 9000:9000 \\
  -e "MINIO_ACCESS_KEY=1234567890EXAMPLE" \\
  -e "MINIO_SECRET_KEY=EXAMPLEKEYEXAMPLEKEYEXAMPLEKEY" \\
  minio/minio server /data**
4. ./mu alias add test http://localhost:9000 1234567890EXAMPLE EXAMPLEKEYEXAMPLEKEYEXAMPLEKEY
5. ./mu bucket create test/my-bucket

The command works ok when using the normal JVM
```
java -jar build/libs/minio-util-1.0.0.BUILD-SNAPSHOT-all.jar bucket create test/my-bucket
```

**Describe GraalVM and your environment:**
 - GraalVM version: **20.3.0.r11-grl** and **20.3.0.r8-grl** installed with **sdkman**
 - JDK major version: **11** and **8**
 - OS: **MacOS Catalina**
 - Architecture: **x86_64 / DARWIN_AMD64**

**More details**

This is the error when building the image:
```
[mu:91323]     analysis:  56,655.10 ms,  5.28 GB
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type jdk.internal.reflect.MethodAccessorGenerator is reachable

Detailed message:
Trace: 
	at parsing jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:513)
Call path from entry point to jdk.internal.reflect.ReflectionFactory.generateConstructor(Class, Constructor): 
	at jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:513)
	at jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:506)
	at java.io.ObjectStreamClass.getSerializableConstructor(ObjectStreamClass.java:1531)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:509)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:484)
	at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:84)
	at sun.security.pkcs11.SunPKCS11.initToken(SunPKCS11.java:1028)
	at sun.security.pkcs11.SunPKCS11$TokenPoller.run(SunPKCS11.java:852)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
```

If I add `--report-unsupported-elements-at-runtime` I get this error at runtime:
```
Caused by: java.lang.RuntimeException: class io.minio.ListObjectsArgs must have no argument constructor
	at io.minio.BaseArgs$Builder.newInstance(BaseArgs.java:135)
	at io.minio.BaseArgs$Builder.build(BaseArgs.java:148)
	at se.technipelago.minio.cmd.AbstractBucketCommand.getObjects(AbstractBucketCommand.java:49)
```

I've created an issue in my repository https://github.com/technipelago/minio-util/issues/1 that gives more information and stack-traces, etc.

**Comment by Arc-2023** [comment]
Now, I'm still getting errors with minio when running binary file compiled with GraalVM: io.minio.DownloadObjectArgs must have no argument constructor.
adding --initialize-at-build-time= io.minio.GetObjectArgs does not help a litte.
And the weired thing is that there is one args constructor in GetObjectArgs class.
Nothing found in Minio document and other places.
