### ISSUE TITLE
Error when having java.lang.Object<init> in JNI configuration

### ISSUE THREAD

**Issue by johanvos** [oracle/graal#3107]
**Describe the issue**
When java.lang.Object<init> is passed in the JNI configuration file, a crash will occur

**Steps to reproduce the issue**
With the following jni-config file in /tmp/jni-config.json:

```
[
  {
    "name" : "java.lang.Object",
    "methods" : [
      {"name":"<init>","parameterTypes":[] }
    ]
  }
]
```

and a simple HelloWorld class in target/classes,

the command 
native-image -J-ea -H:JNIConfigurationFiles=/tmp/jniconfig.json -cp target/classes hello.HelloWorld

will fail with an assertion error similar to the one below:

**Describe GraalVM and your environment:**
- GraalVM: head version 
 - JDK major version: 11
 - OS: macOS Catalina
 - Architecture: AMD64

**More details**

This started with https://github.com/oracle/graal/commit/55022d06126d9d5878591f0057bcbfd84e7212b9
The problem is that an `InstanceOf` node is used in JNIJavaCallWrapperMethod.java:

        LogicNode instanceOf = kit.unique(InstanceOfNode.create(expectedTypeRef, receiver, null, null));

In case expectedTypeRef is `AnalsysType<java.lang.Object>` and the receiver is something like `9|Invoke#JNIGeneratedMethodSupport.unboxHandle`, the return value of `InstanceOfNode.create` is a synonym `LogicNode` with a value of `-1|NULL` (returned by `InstanceOfNode.findSynonym`) , which causes the assert to be triggered (and a crash to occur later)

```
	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:331)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:302)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
	at com.oracle.graal.pointsto.BigBang$1.run(BigBang.java:422)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.AssertionError: Input -1|IsNull of node 58|LogicNegation is not alive
	at jdk.internal.vm.compiler/org.graalvm.compiler.graph.NodeClass.registerAtInputsAsUsage(NodeClass.java:1396)
	at jdk.internal.vm.compiler/org.graalvm.compiler.graph.Node.initialize(Node.java:657)
	at jdk.internal.vm.compiler/org.graalvm.compiler.graph.Graph.addHelper(Graph.java:507)
	at jdk.internal.vm.compiler/org.graalvm.compiler.graph.Graph.uniqueHelper(Graph.java:684)
	at jdk.internal.vm.compiler/org.graalvm.compiler.graph.Graph.unique(Graph.java:672)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.GraphKit.unique(GraphKit.java:178)
	at com.oracle.svm.jni.hosted.JNIJavaCallWrapperMethod.typeCheckReceiverAndCreateCallTypeMethod(JNIJavaCallWrapperMethod.java:435)
	at com.oracle.svm.jni.hosted.JNIJavaCallWrapperMethod.buildGraph(JNIJavaCallWrapperMethod.java:264)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.buildGraph(AnalysisMethod.java:333)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:187)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:357)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:313)

```

**Comment by mcraj017** [comment]
@johanvos Thanks for reporting the issue
we will check it out and update the issue

**Comment by mcraj017** [comment]
@johanvos please use 21.0.02
https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.0.0.2
I have tried and successfully build the image, if you still face the error, please reopen
