### ISSUE TITLE
Multi threaded access requested is not allowed for language(s) js

### ISSUE THREAD

**Issue by liangjin0414** [oracle/graal#3112]
<dependency>
        <groupId>org.graalvm.js</groupId>
        <artifactId>js</artifactId>
        <version>20.3.0</version>
</dependency>

**just run this:**

public static void main(String[] args) {
        Context context = Context.newBuilder().build();
        for (int i = 0; i < 5; i++) {
            new Thread(() -> {
                while (true) {
                    context.eval("js", "var a = 400; a");
                }
            }).start();
        }
    }

Exception in thread "Thread-2" java.lang.IllegalStateException: Multi threaded access requested by thread Thread[Thread-6,5,main] but is not allowed for language(s) js.
	at com.oracle.truffle.polyglot.PolyglotEngineException.illegalState(PolyglotEngineException.java:132)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.throwDeniedThreadAccess(PolyglotContextImpl.java:724)
	at com.oracle.truffle.polyglot.PolyglotLanguageContext.checkThreadAccess(PolyglotLanguageContext.java:306)
	at com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureCreated(PolyglotLanguageContext.java:498)
	at com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureInitialized(PolyglotLanguageContext.java:585)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:939)
	at org.graalvm.polyglot.Context.eval(Context.java:347)
	at org.graalvm.polyglot.Context.eval(Context.java:373)

**Comment by liangjin0414** [comment]
while **nashorn** work fine in this case:

final private static ScriptEngineManager SCRIPT_ENGINE_MANAGER = new ScriptEngineManager();
    final private static NashornScriptEngine ENGINE = (NashornScriptEngine)SCRIPT_ENGINE_MANAGER
        .getEngineByName("nashorn");

    public static void main(String[] args) {
        for (int i = 0; i < 5; i++) {
            new Thread(() -> {
                while (true) {
                    try {
                        ENGINE.eval("var a = 400; a");
                    } catch (ScriptException e) {
                        throw new RuntimeException(e);
                    }
                }
            }).start();
        }
    }

**Comment by mcraj017** [comment]
@liangjin0414 thanks for reporting the issue, we will take a look into this
for the time being please check out this guide
https://github.com/oracle/graaljs/blob/master/docs/user/NashornMigrationGuide.md

**Comment by mcraj017** [comment]
@liangjin0414 please check the below link about how to implement multithreading in graalvm javascript
https://github.com/oracle/graaljs/blob/master/docs/user/NashornMigrationGuide.md#multithreading
if you still have questions, please feel free to open the ticket
