### ISSUE TITLE
Compiling a shared library with -H:-MultiThreaded failed

### ISSUE THREAD

**Issue by ziyilin** [oracle/graal#3113]
**Describe the issue**
Compiling a Java program into shared library is failed when `-H:-MultiThreaded` is set. The complete error messages are:
```
[libmathapi:96557]    classlist:     820.33 ms,  0.96 GB
[libmathapi:96557]        (cap):     470.44 ms,  0.96 GB
[libmathapi:96557]        setup:  18,292.70 ms,  0.96 GB
[libmathapi:96557]     (clinit):     165.97 ms,  1.22 GB
[libmathapi:96557]   (typeflow):   3,706.00 ms,  1.22 GB
[libmathapi:96557]    (objects):   3,669.27 ms,  1.22 GB
[libmathapi:96557]   (features):     229.63 ms,  1.22 GB
[libmathapi:96557]     analysis:   7,966.39 ms,  1.22 GB
[libmathapi:96557]     universe:     379.62 ms,  1.22 GB
[libmathapi:96557]      (parse):     661.57 ms,  1.68 GB
[libmathapi:96557]     (inline):     780.45 ms,  1.68 GB
[libmathapi:96557]    (compile):     109.05 ms,  1.68 GB
[libmathapi:96557]      compile:   1,660.04 ms,  1.68 GB
3 fatal errors detected:
Fatal error:org.graalvm.compiler.debug.GraalError: java.lang.NullPointerException
        at method: void com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionClear_f8f1b5cbd6fa215c2f96b35e6dbc342caf9c6571(JNIEnvironment)  [entry point]
        at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:1027)
        at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:958)
        at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:263)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.SnippetTemplate$MemoryOutputMap.getLastLocationAccess(SnippetTemplate.java:1459)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.SnippetTemplate.replaceMemoryUsages(SnippetTemplate.java:1529)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.SnippetTemplate.rewireMemoryGraph(SnippetTemplate.java:1477)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.SnippetTemplate.instantiate(SnippetTemplate.java:1607)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.SnippetTemplate.instantiate(SnippetTemplate.java:1555)
        at com.oracle.svm.core.graal.snippets.CEntryPointSnippets$EnterLowering.lower(CEntryPointSnippets.java:639)
        at com.oracle.svm.core.graal.snippets.CEntryPointSnippets$EnterLowering.lower(CEntryPointSnippets.java:593)
        at com.oracle.svm.core.graal.amd64.SubstrateAMD64LoweringProvider.lower(SubstrateAMD64LoweringProvider.java:59)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.spi.Lowerable.lower(Lowerable.java:40)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase$Round.process(LoweringPhase.java:448)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase$Round.access$300(LoweringPhase.java:324)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase$Round$ProcessFrame.preprocess(LoweringPhase.java:388)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.processBlock(LoweringPhase.java:547)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase$Round.run(LoweringPhase.java:373)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:209)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:56)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:38)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.lower(LoweringPhase.java:242)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:235)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:91)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:209)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:242)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:145)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:130)
        at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:996)
        ... 9 more
Fatal error:org.graalvm.compiler.debug.GraalError: java.lang.NullPointerException
        at method: boolean com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionCheck_c3880ec5388acdaaf0a33f93c718f75d394cf800(JNIEnvironment)  [entry point]
        at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:1027)
        at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:958)
        at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:263)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.SnippetTemplate$MemoryOutputMap.getLastLocationAccess(SnippetTemplate.java:1459)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.SnippetTemplate.replaceMemoryUsages(SnippetTemplate.java:1529)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.SnippetTemplate.rewireMemoryGraph(SnippetTemplate.java:1477)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.SnippetTemplate.instantiate(SnippetTemplate.java:1607)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.SnippetTemplate.instantiate(SnippetTemplate.java:1555)
        at com.oracle.svm.core.graal.snippets.CEntryPointSnippets$EnterLowering.lower(CEntryPointSnippets.java:639)
        at com.oracle.svm.core.graal.snippets.CEntryPointSnippets$EnterLowering.lower(CEntryPointSnippets.java:593)
        at com.oracle.svm.core.graal.amd64.SubstrateAMD64LoweringProvider.lower(SubstrateAMD64LoweringProvider.java:59)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.spi.Lowerable.lower(Lowerable.java:40)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase$Round.process(LoweringPhase.java:448)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase$Round.access$300(LoweringPhase.java:324)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase$Round$ProcessFrame.preprocess(LoweringPhase.java:388)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.processBlock(LoweringPhase.java:547)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase$Round.run(LoweringPhase.java:373)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:209)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:56)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:38)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.lower(LoweringPhase.java:242)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:235)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:91)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:209)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:242)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:145)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:130)
        at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:996)
        ... 9 more
Fatal error:org.graalvm.compiler.debug.GraalError: java.lang.NullPointerException
        at method: JNIObjectHandle com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionOccurred_000e777c909ddebba179d4b74e02a774f08bc4b8(JNIEnvironment)  [entry point]
        at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:1027)
        at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:958)
        at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:263)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.SnippetTemplate$MemoryOutputMap.getLastLocationAccess(SnippetTemplate.java:1459)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.SnippetTemplate.replaceMemoryUsages(SnippetTemplate.java:1529)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.SnippetTemplate.rewireMemoryGraph(SnippetTemplate.java:1477)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.SnippetTemplate.instantiate(SnippetTemplate.java:1607)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.SnippetTemplate.instantiate(SnippetTemplate.java:1555)
        at com.oracle.svm.core.graal.snippets.CEntryPointSnippets$EnterLowering.lower(CEntryPointSnippets.java:639)
        at com.oracle.svm.core.graal.snippets.CEntryPointSnippets$EnterLowering.lower(CEntryPointSnippets.java:593)
        at com.oracle.svm.core.graal.amd64.SubstrateAMD64LoweringProvider.lower(SubstrateAMD64LoweringProvider.java:59)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.spi.Lowerable.lower(Lowerable.java:40)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase$Round.process(LoweringPhase.java:448)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase$Round.access$300(LoweringPhase.java:324)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase$Round$ProcessFrame.preprocess(LoweringPhase.java:388)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.processBlock(LoweringPhase.java:547)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase$Round.run(LoweringPhase.java:373)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:209)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:56)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:38)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.lower(LoweringPhase.java:242)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:235)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:91)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:209)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:242)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:145)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:130)
        at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:996)
        ... 9 more
Error: Image build request failed with exit status 1

```

**Steps to reproduce the issue**
1. Unzip [testcase.zip](https://github.com/oracle/graal/files/5780589/testcase.zip)
2. Set GRAALVM_HOME to your based GraalVM home.
3. Run `./compileAndRun.sh 11  -H:-MultiThreaded` for JDK11 based GraalVM to see the error.
4. Run `./compileAndRun.sh 11` will succeed.

**Comment by mcraj017** [comment]
@ziyilin please provide the reproducer

**Comment by ziyilin** [comment]
> @ziyilin please provide the reproducer

Please see the `**Steps to reproduce the issue**` section. I've attached a test case.

**Comment by mcraj017** [comment]
@ziyilin thanks of the reproducer, I am able to reproduce it, 
we will get back to you soon

**Comment by christianwimmer** [comment]
The option `-H:-MultiThreaded` is not supported. It can be useful for some embedding scenarios, so we don't want to remove the code from the code base for now.
In particular, JNI does not work at all with `-H:-MultiThreaded`, so this error is not surprising.

We are happy to accept community fixes for such problems, but are not able to work on that ourselfs. So I leave this issue open, but remove the assignees so that it is clear that no one is working on it.

**Comment by fernando-valdez** [comment]
Hello @christianwimmer, this feature request was created in June 2021, please let me know if the feature request makes sense or if it applicable by today's state of the project

**Comment by christianwimmer** [comment]
`-H:-MultiThreaded` is deprecated by now, and will be removed in GraalVM for JDK 23.
