### ISSUE TITLE
UnsupportedFeatureException: No instances of sun.nio.ch.Iocp are allowed

### ISSUE THREAD

**Issue by MarioMO98** [oracle/graal#3114]
**Describe the issue**
Greetings,

we are getting problems compiling one of the graalvm samples in Windows 10 (https://github.com/spring-projects-experimental/spring-graalvm-native/tree/master/spring-graalvm-native-samples/cloud-function-netty).

We have followed the instructions detailed in the official documentation for GraalVM on Windows and we are using GraalVM v 20.3 for Java 8 (11 as well), and Spring GraalVM Native 0.9.0.

Besides, we have tested with both JDK 8 (in a Windows SDK 7.1 command shell) and JDK 11 (in a x64 native tools command prompt for VS 2019) , with their respective GraalVM Version and we get the same exception:
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of sun.nio.ch.Iocp are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=sun.nio.ch.Iocp.

In first instance, we had to add the native profile to the sample's pom.xml (#233 (comment)) but, in our case, we changed the main class to the sample main class (com.example.demo.DemoApplication), and execute the mvn -pNative clean package.

**Steps to reproduce the issue**
1.  mvn -Pnative clean package

**Describe GraalVM and your environment:**
 - GraalVM version: graalvm-ce-java11-20.3.0
 - JDK major version: 11
 - OS: Windows 10
 - Architecture: AMD64

**More details**
Could this error be originated by AsynchronousFileChannel.open (file.toPath (), StandardOpenOption.READ) method?
Here is the trace of the exception:

_Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of sun.nio.ch.Iocp are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=sun.nio.ch.Iocp.
Detailed message:
Trace:
at parsing sun.nio.ch.WindowsAsynchronousFileChannelImpl.open(WindowsAsynchronousFileChannelImpl.java:105)
Call path from entry point to sun.nio.ch.WindowsAsynchronousFileChannelImpl.open(FileDescriptor, boolean, boolean, ThreadPool):
at sun.nio.ch.WindowsAsynchronousFileChannelImpl.open(WindowsAsynchronousFileChannelImpl.java:104)
at sun.nio.fs.WindowsChannelFactory.newAsynchronousFileChannel(WindowsChannelFactory.java:208)
at sun.nio.fs.WindowsFileSystemProvider.newAsynchronousFileChannel(WindowsFileSystemProvider.java:140)
at java.nio.channels.AsynchronousFileChannel.open(AsynchronousFileChannel.java:248)
at java.nio.channels.AsynchronousFileChannel.open(AsynchronousFileChannel.java:301)
at org.springframework.core.io.buffer.DataBufferUtils.lambda$read$6(DataBufferUtils.java:224)
at org.springframework.core.io.buffer.DataBufferUtils$$Lambda$1113/1779033696.call(Unknown Source)
at reactor.core.publisher.MonoCallable.block(MonoCallable.java:81)
at reactor.core.publisher.MonoCallable.block(MonoCallable.java:74)
at org.springframework.boot.web.embedded.netty.NettyWebServer$1.run(NettyWebServer.java:160)
at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
at com.oracle.svm.core.code.IsolateEnterStub.WindowsJavaThreads_osThreadStartRoutine_4bc03aa26f8cdfc97ebd54050e8ae4bce1023851(generated:0)_

Thanks in advance.

**Comment by fernando-valdez** [comment]
Hello @MarioMO98, 
Thanks for reporting this issue. 
I will take a look at this issue. If I have any question, I will let you know

**Comment by MarioMO98** [comment]
I added the --trace-object-instantiation=sun.nio.ch.Iocp to see how this object got instantiated and I get the following output:

_Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of sun.nio.ch.Iocp are allowed in the image heap as this class should be initialized at image runtime. Object has been initialized by the sun.nio.ch.WindowsAsynchronousFileChannelImpl$DefaultIocpHolder class initializer with a trace:
        at sun.nio.ch.Iocp.<init>(Iocp.java:68)
        at sun.nio.ch.WindowsAsynchronousFileChannelImpl$DefaultIocpHolder.defaultIocp(WindowsAsynchronousFileChannelImpl.java:56)
        at sun.nio.ch.WindowsAsynchronousFileChannelImpl$DefaultIocpHolder.<clinit>(WindowsAsynchronousFileChannelImpl.java:53)
.  **To fix the issue mark sun.nio.ch.Iocp for build-time initialization with --initialize-at-build-time=sun.nio.ch.Iocp or use the the information from the trace to find the culprit and --initialize-at-run-time=<culprit> to prevent its instantiation**._

Then, I added the --initialize-at-build-time=sun.nio.ch.Iocp option as it says in the log, but I get another error:

_Error: Incompatible change of initialization policy for sun.nio.ch.Iocp: trying to change BUILD_TIME from the command line to RERUN for JDK native code support via JNI
com.oracle.svm.core.util.UserError$UserException: Incompatible change of initialization policy for sun.nio.ch.Iocp: trying to change BUILD_TIME from the command line to RERUN for JDK native code support via JNI
        at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:99)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insert(ClassInitializationConfiguration.java:64)
        at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.rerunInitialization(ConfigurableClassInitialization.java:379)
        at com.oracle.svm.core.jdk.JNIRegistrationUtil.rerunClassInit(JNIRegistrationUtil.java:73)
        at com.oracle.svm.hosted.jdk.JNIRegistrationJavaNio.duringSetup(JNIRegistrationJavaNio.java:63)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$12(NativeImageGenerator.java:882)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:882)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:556)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:471)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)_

Any solution?

**Comment by dragosroban** [comment]
Anyone here with a solution? I am having the exact same issue. :(
