### ISSUE TITLE
Error when calling java.awt.Color.getColorSpace() (works on 20.2 and 21.1-dev)

### ISSUE THREAD

**Issue by JiriOndrusek** [oracle/graal#3115]
**Describe the issue**
I'm fixing an issue in camel-quarkus extension for FOP (https://github.com/apache/camel-quarkus/issues/2113).

I'm facing an error `Not implemented yet for GraalVM native images`. Although message comes from quarkus, I think that it is caused by some changes between graalvm 20.2 and 20.3
Let me explain:

- If you execute integration tests of camel-quarkus FOP extension with graalvm 20.2. Test is successful.
- If you execute integration tests of camel-quarkus FOP extension with graalvm 20.3. Test fails.
- If you execute integration tests of camel-quarkus FOP extension with graalvm 21.1-dev. (https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/21.1.0-dev-20210106_0315) Test is successful.

IMHO it is linked to AWT support, which didn't make it into 20.3.

**Steps to reproduce the issue**
Take camel-quarkus (tested with revision `30111eacf22f00c8a1934ce3ec0ab2be7586b83e`). Execute native integration test for fop extension (`mvn clean verify -Pnative -f integration-tests/fop/`)
On linux with java 11 with graalvm graalvm-ce-java11-linux-amd64-20.2.0 test suceeds, with graalvm graalvm-ce-java11-linux-amd64-20.3.0 fails.

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **[CE 20.3]**
 - JDK major version: **11**
 - OS: **linux**
 - Architecture: **AMD64**

```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 20.3.0 (Java Version 11.0.9+7-LTS-jvmci-20.3-b06)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] /home/jondruse/dev/graal/graalvm-ce-java11-20.3.0/bin/native-image -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Duser.language=en -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -jar camel-quarkus-integration-test-fop-1.6.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http -H:NativeLinkerOption=-no-pie --no-server -H:-UseServiceLoaderFeature -H:+StackTrace camel-quarkus-integration-test-fop-1.6.0-SNAPSHOT-runner
[camel-quarkus-integration-test-fop-1.6.0-SNAPSHOT-runner:112519]    classlist:   4,048.90 ms,  1.19 GB
[camel-quarkus-integration-test-fop-1.6.0-SNAPSHOT-runner:112519]        (cap):     584.16 ms,  1.19 GB
[camel-quarkus-integration-test-fop-1.6.0-SNAPSHOT-runner:112519]        setup:   2,105.58 ms,  1.19 GB
14:16:24,904 INFO  [org.jbo.threads] JBoss Threads version 3.1.1.Final
[camel-quarkus-integration-test-fop-1.6.0-SNAPSHOT-runner:112519]     (clinit):   1,278.56 ms,  4.57 GB
[camel-quarkus-integration-test-fop-1.6.0-SNAPSHOT-runner:112519]   (typeflow):  25,857.64 ms,  4.57 GB
[camel-quarkus-integration-test-fop-1.6.0-SNAPSHOT-runner:112519]    (objects):  29,877.24 ms,  4.57 GB
[camel-quarkus-integration-test-fop-1.6.0-SNAPSHOT-runner:112519]   (features):   1,131.16 ms,  4.57 GB
[camel-quarkus-integration-test-fop-1.6.0-SNAPSHOT-runner:112519]     analysis:  60,685.49 ms,  4.57 GB
[camel-quarkus-integration-test-fop-1.6.0-SNAPSHOT-runner:112519]     universe:   2,437.94 ms,  4.57 GB
[camel-quarkus-integration-test-fop-1.6.0-SNAPSHOT-runner:112519]      (parse):   6,758.80 ms,  5.05 GB
[camel-quarkus-integration-test-fop-1.6.0-SNAPSHOT-runner:112519]     (inline):  11,623.06 ms,  6.43 GB
[camel-quarkus-integration-test-fop-1.6.0-SNAPSHOT-runner:112519]    (compile):  44,662.89 ms,  6.62 GB
[camel-quarkus-integration-test-fop-1.6.0-SNAPSHOT-runner:112519]      compile:  66,312.24 ms,  6.62 GB
[camel-quarkus-integration-test-fop-1.6.0-SNAPSHOT-runner:112519]        image:   5,983.55 ms,  6.33 GB
[camel-quarkus-integration-test-fop-1.6.0-SNAPSHOT-runner:112519]        write:     781.77 ms,  6.33 GB
[camel-quarkus-integration-test-fop-1.6.0-SNAPSHOT-runner:112519]      [total]: 143,087.15 ms,  6.33 GB
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 145973ms
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.2:integration-test (default) @ camel-quarkus-integration-test-fop ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.camel.quarkus.component.fop.it.FopIT
Executing [/home/jondruse/git/tmp/tmp/camel-quarkus/integration-tests/fop/target/camel-quarkus-integration-test-fop-1.6.0-SNAPSHOT-runner, -Dquarkus.http.port=39821, -Dquarkus.http.ssl-port=35259, -Dtest.url=http://localhost:39821, -Dquarkus.log.file.path=target/target/quarkus.log]
2021-01-08 14:18:09,555 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) bootstrap runtime: org.apache.camel.quarkus.core.CamelContextRuntime
2021-01-08 14:18:09,556 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.7.0 (camel-1) is starting
2021-01-08 14:18:09,556 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) StreamCaching is not in use. If using streams then it's recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
2021-01-08 14:18:09,556 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Total 0 routes, of which 0 are started
2021-01-08 14:18:09,556 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.7.0 (camel-1) started in 0ms
2021-01-08 14:18:09,558 INFO  [io.quarkus] (main) camel-quarkus-integration-test-fop 1.6.0-SNAPSHOT native (powered by Quarkus 1.11.0.Beta1) started in 0.014s. Listening on: http://0.0.0.0:39821
2021-01-08 14:18:09,559 INFO  [io.quarkus] (main) Profile prod activated. 
2021-01-08 14:18:09,559 INFO  [io.quarkus] (main) Installed features: [camel-core, camel-fop, camel-support-common, camel-support-commons-logging, camel-xml-jaxp, cdi, resteasy]
2021-01-08 14:18:11,180 INFO  [org.apa.cam.qua.com.fop.it.FopResource] (executor-thread-1) Sending to fop: <fo:root xmlns:fo="http://www.w3.org/1999/XSL/Format">
  <fo:layout-master-set>
    <fo:simple-page-master master-name="only">
      <fo:region-body region-name="xsl-region-body" margin="0.7in"  padding="0" />
      <fo:region-before region-name="xsl-region-before" extent="0.7in" />
        <fo:region-after region-name="xsl-region-after" extent="0.7in" />
      </fo:simple-page-master>
    </fo:layout-master-set>
    <fo:page-sequence master-reference="only">
      <fo:flow flow-name="xsl-region-body">
      <fo:block font-family="Freedom">hello</fo:block>
    </fo:flow>
  </fo:page-sequence>
</fo:root>
2021-01-08 14:18:11,184 WARN  [org.apa.fop.fo.pro.CommonHyphenation] (executor-thread-1) Substituted specified hyphenation character (0x2d) with 0x20 because the font doesn't have the specified hyphenation character: Freedom,normal,400
2021-01-08 14:18:11,185 ERROR [org.apa.fop.are.AreaTreeModel] (executor-thread-1) Error while rendering page 1: java.lang.UnsupportedOperationException: Not implemented yet for GraalVM native images
	at sun.java2d.cmm.lcms.LCMS.loadProfileNative(LCMS.java:13)
	at sun.java2d.cmm.lcms.LCMS.loadProfile(LCMS.java:42)
	at java.awt.color.ICC_Profile.getInstance(ICC_Profile.java:790)
	at java.awt.color.ICC_Profile.getInstance(ICC_Profile.java:1026)
	at java.awt.color.ICC_Profile.getInstance(ICC_Profile.java:991)
	at java.awt.color.ICC_Profile$2.run(ICC_Profile.java:940)
	at java.awt.color.ICC_Profile$2.run(ICC_Profile.java:936)
	at java.security.AccessController.doPrivileged(AccessController.java:84)
	at java.awt.color.ICC_Profile.getStandardProfile(ICC_Profile.java:935)
	at java.awt.color.ICC_Profile.getDeferredInstance(ICC_Profile.java:1067)
	at java.awt.color.ICC_Profile.getInstance(ICC_Profile.java:854)
	at java.awt.color.ColorSpace.getInstance(ColorSpace.java:298)
	at java.awt.Color.getColorSpace(Color.java:1183)
	at org.apache.fop.pdf.PDFColorHandler.establishColorFromColor(PDFColorHandler.java:95)
	at org.apache.fop.pdf.PDFColorHandler.establishColor(PDFColorHandler.java:88)
	at org.apache.fop.render.pdf.PDFContentGenerator.setColor(PDFContentGenerator.java:458)
	at org.apache.fop.render.pdf.PDFContentGenerator.setColor(PDFContentGenerator.java:435)
	at org.apache.fop.render.pdf.PDFContentGenerator.setColor(PDFContentGenerator.java:460)
	at org.apache.fop.render.pdf.PDFContentGenerator.updateColor(PDFContentGenerator.java:483)
	at org.apache.fop.render.pdf.PDFPainter.drawText(PDFPainter.java:428)
	at org.apache.fop.render.pdf.PDFPainter.drawText(PDFPainter.java:449)
	at org.apache.fop.render.intermediate.IFRenderer$TextUtil.flush(IFRenderer.java:1238)
	at org.apache.fop.render.intermediate.IFRenderer.renderText(IFRenderer.java:1064)
	at org.apache.fop.render.AbstractRenderer.renderInlineArea(AbstractRenderer.java:861)
	at org.apache.fop.render.intermediate.IFRenderer.renderInlineArea(IFRenderer.java:927)
	at org.apache.fop.render.AbstractRenderer.renderLineArea(AbstractRenderer.java:845)
	at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:704)
	at org.apache.fop.render.AbstractRenderer.renderBlock(AbstractRenderer.java:758)
	at org.apache.fop.render.intermediate.IFRenderer.renderBlock(IFRenderer.java:999)
	at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:689)
	at org.apache.fop.render.AbstractRenderer.renderFlow(AbstractRenderer.java:591)
	at org.apache.fop.render.AbstractPathOrientedRenderer.renderFlow(AbstractPathOrientedRenderer.java:789)
	at org.apache.fop.render.AbstractRenderer.renderMainReference(AbstractRenderer.java:568)
	at org.apache.fop.render.AbstractRenderer.renderBodyRegion(AbstractRenderer.java:433)
	at org.apache.fop.render.AbstractRenderer.renderRegionViewport(AbstractRenderer.java:380)
	at org.apache.fop.render.intermediate.IFRenderer.renderRegionViewport(IFRenderer.java:738)
	at org.apache.fop.render.AbstractRenderer.renderPageAreas(AbstractRenderer.java:345)
	at org.apache.fop.render.AbstractRenderer.renderPage(AbstractRenderer.java:318)
	at org.apache.fop.render.intermediate.IFRenderer.renderPage(IFRenderer.java:587)
	at org.apache.fop.area.RenderPagesModel.addPage(RenderPagesModel.java:123)
	at org.apache.fop.layoutmgr.AbstractPageSequenceLayoutManager.finishPage(AbstractPageSequenceLayoutManager.java:316)
	at org.apache.fop.layoutmgr.PageSequenceLayoutManager.finishPage(PageSequenceLayoutManager.java:243)
	at org.apache.fop.layoutmgr.PageSequenceLayoutManager.activateLayout(PageSequenceLayoutManager.java:147)
	at org.apache.fop.area.AreaTreeHandler.endPageSequence(AreaTreeHandler.java:267)
	at org.apache.fop.fo.pagination.PageSequence.endOfNode(PageSequence.java:139)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:362)
	at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:190)
	at com.sun.org.apache.xml.internal.serializer.ToXMLSAXHandler.endElement(ToXMLSAXHandler.java:263)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:610)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1718)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2883)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(TransformerImpl.java:660)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:774)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:370)
	at org.apache.camel.component.fop.FopProducer.transform(FopProducer.java:98)
	at org.apache.camel.component.fop.FopProducer.process(FopProducer.java:66)
	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
	at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:218)
	at org.apache.camel.impl.engine.SharedCamelInternalProcessor$1.process(SharedCamelInternalProcessor.java:112)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:109)
	at org.apache.camel.support.cache.DefaultProducerCache.send(DefaultProducerCache.java:189)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:176)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:172)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.requestBody(DefaultProducerTemplate.java:413)
	at org.apache.camel.quarkus.component.fop.it.FopResource.post(FopResource.java:55)
	at org.apache.camel.quarkus.component.fop.it.FopResource_ClientProxy.post(FopResource_ClientProxy.zig:161)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:41)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)

2021-01-08 14:18:11,186 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /fop/post?userConfigURL=file%3A%2F%2F%2Fhome%2Fjondruse%2Fgit%2Ftmp%2Ftmp%2Fcamel-quarkus%2Fintegration-tests%2Ffop%2Ftarget%2Ftmp%2Fmycfg.xml failed, error id: 4b45909f-bec3-44da-892d-1cebb21b3930-1: org.jboss.resteasy.spi.UnhandledException: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:41)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
	at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:425)
	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:69)
	at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:218)
	at org.apache.camel.impl.engine.SharedCamelInternalProcessor$1.process(SharedCamelInternalProcessor.java:112)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:109)
	at org.apache.camel.support.cache.DefaultProducerCache.send(DefaultProducerCache.java:189)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:176)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:172)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.requestBody(DefaultProducerTemplate.java:413)
	at org.apache.camel.quarkus.component.fop.it.FopResource.post(FopResource.java:55)
	at org.apache.camel.quarkus.component.fop.it.FopResource_ClientProxy.post(FopResource_ClientProxy.zig:161)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	... 19 more
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Resource bundle lookup must be loaded during native image generation: com.sun.org.apache.xalan.internal.xsltc.compiler.util.ErrorMessages
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:87)
	at java.util.ListResourceBundle.loadLookup(ListResourceBundle.java:108)
	at java.util.ListResourceBundle.handleGetObject(ListResourceBundle.java:130)
	at java.util.ResourceBundle.getObject(ResourceBundle.java:555)
	at java.util.ResourceBundle.getString(ResourceBundle.java:521)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.util.ErrorMsg.getErrorMessage(ErrorMsg.java:311)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.util.ErrorMsg.toString(ErrorMsg.java:284)
	at java.lang.String.valueOf(String.java:2951)
	at java.io.PrintStream.println(PrintStream.java:897)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.error(TransformerImpl.java:1376)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.postErrorToListener(TransformerImpl.java:841)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:782)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:370)
	at org.apache.camel.component.fop.FopProducer.transform(FopProducer.java:98)
	at org.apache.camel.component.fop.FopProducer.process(FopProducer.java:66)
	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
	... 41 more



```

**Comment by ppalaga** [comment]
This is related or even a duplicate of https://github.com/oracle/graal/issues/3077

**Comment by gradinac** [comment]
Hey @JiriOndrusek! I think @ppalaga is correct, the root cause of this issue seems to be the same one as #3077. Could you try running your example with [GraalVM 20.3.1](https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-20.3.1)? That would give us insight on whether the problem still occurs with the new release.

**Comment by JiriOndrusek** [comment]
@gradinac I'll try to verify it during the next week, thanks

**Comment by JiriOndrusek** [comment]
@gradinac I've verified the issue with graalvm-ce-java11-20.3.1. Problem is fixed, thanks!

**Comment by gradinac** [comment]
@JiriOndrusek I'm glad to hear that, thank you for letting us now! :)
