### ISSUE TITLE
Regression with H2 and Java 11 in Micronaut: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant

### ISSUE THREAD

**Issue by ilopmar** [oracle/graal#3130]
**Describe the issue**

All our test applications that use H2 with Java 11 have started to fail on CI (they work with Java 8) when using GraalVM 21.0 from the release branch. This was working last Thursday so it has to be something committed really soon.

The error is the same in all of them: `com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant`.

Please note that even adding `--report-unsupported-elements-at-runtime` makes no difference and it is not possible to create the native-image.

At this moment this is kind of blocking because it does't allow to build a Micronaut JDK11 native-image with H2 as database.

**Steps to reproduce the issue**

- `git clone https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal`
- `cd micronaut-data-jdbc-graal`
- `git checkout h2-issue-jdk11`
- Use GraalVM compiled from release 21.0 branch
- `./build-native-image.sh`
- The application fail to build the native-image. See error bellow.

**Describe GraalVM and your environment:**
 - GraalVM version: **21.0 compiled from release branch. Commit ef37eb9a6697c3d600db2d89f1d2b755454adedd**
 - JDK major version: **11**
 - OS: **Linux Mint 20**
 - Architecture: **AMD64**

**More details**

```
[data-jdbc-h2:144087]    classlist:   1,660.22 ms,  0.96 GB
[data-jdbc-h2:144087]        (cap):     425.92 ms,  0.96 GB
[data-jdbc-h2:144087]        setup:   1,544.66 ms,  0.96 GB
[data-jdbc-h2:144087]     (clinit):   1,237.13 ms,  5.67 GB
[data-jdbc-h2:144087]   (typeflow):  20,279.13 ms,  5.67 GB
[data-jdbc-h2:144087]    (objects):  24,526.20 ms,  5.67 GB
[data-jdbc-h2:144087]   (features):   2,721.63 ms,  5.67 GB
[data-jdbc-h2:144087]     analysis:  52,558.44 ms,  5.67 GB
Error: Unsupported features in 9 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace: 
        at parsing org.h2.util.Bits.readDouble(Bits.java:184)
Call path from entry point to org.h2.util.Bits.readDouble(byte[], int): 
        at org.h2.util.Bits.readDouble(Bits.java:184)
        at org.h2.util.geometry.EWKBUtils$EWKBSource.readCoordinate(EWKBUtils.java:217)
        at org.h2.util.geometry.EWKBUtils.addCoordinate(EWKBUtils.java:475)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:376)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:292)
        at org.h2.value.ValueGeometry.getEnvelopeNoCopy(ValueGeometry.java:238)
        at org.h2.mvstore.db.MVSpatialIndex$FindBoundsCursor.check(MVSpatialIndex.java:474)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.fetchNext(MVRTreeMap.java:527)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.hasNext(MVRTreeMap.java:484)
        at java.util.AbstractMap.hashCode(AbstractMap.java:526)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getLinkage(JNIReflectionDictionary.java:146)
        at com.oracle.svm.jni.functions.JNIFunctions.RegisterNatives(JNIFunctions.java:349)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_RegisterNatives_7728ce15b57af339792ad95c60f247990e0df65e(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace: 
        at parsing org.h2.util.Bits.readDoubleLE(Bits.java:198)
Call path from entry point to org.h2.util.Bits.readDoubleLE(byte[], int): 
        at org.h2.util.Bits.readDoubleLE(Bits.java:198)
        at org.h2.util.geometry.EWKBUtils$EWKBSource.readCoordinate(EWKBUtils.java:217)
        at org.h2.util.geometry.EWKBUtils.addCoordinate(EWKBUtils.java:475)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:376)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:292)
        at org.h2.value.ValueGeometry.getEnvelopeNoCopy(ValueGeometry.java:238)
        at org.h2.mvstore.db.MVSpatialIndex$FindBoundsCursor.check(MVSpatialIndex.java:474)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.fetchNext(MVRTreeMap.java:527)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.hasNext(MVRTreeMap.java:484)
        at java.util.AbstractMap.hashCode(AbstractMap.java:526)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getLinkage(JNIReflectionDictionary.java:146)
        at com.oracle.svm.jni.functions.JNIFunctions.RegisterNatives(JNIFunctions.java:349)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_RegisterNatives_7728ce15b57af339792ad95c60f247990e0df65e(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace: 
        at parsing org.h2.util.Bits.readInt(Bits.java:128)
Call path from entry point to org.h2.util.Bits.readInt(byte[], int): 
        at org.h2.util.Bits.readInt(Bits.java:128)
        at org.h2.security.Fog.encryptBlock(Fog.java:34)
        at org.h2.security.Fog.encrypt(Fog.java:22)
        at org.h2.security.SecureFileStore.write(SecureFileStore.java:68)
        at org.h2.store.FileStoreOutputStream.write(FileStoreOutputStream.java:70)
        at java.util.zip.DeflaterOutputStream.flush(DeflaterOutputStream.java:277)
        at java.io.PrintStream.flush(PrintStream.java:417)
        at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:763)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace: 
        at parsing org.h2.util.Bits.readIntLE(Bits.java:142)
Call path from entry point to org.h2.util.Bits.readIntLE(byte[], int): 
        at org.h2.util.Bits.readIntLE(Bits.java:142)
        at org.h2.util.geometry.EWKBUtils$EWKBSource.readInt(EWKBUtils.java:206)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:396)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:292)
        at org.h2.value.ValueGeometry.getEnvelopeNoCopy(ValueGeometry.java:238)
        at org.h2.mvstore.db.MVSpatialIndex$FindBoundsCursor.check(MVSpatialIndex.java:474)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.fetchNext(MVRTreeMap.java:527)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.hasNext(MVRTreeMap.java:484)
        at java.util.AbstractMap.hashCode(AbstractMap.java:526)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getLinkage(JNIReflectionDictionary.java:146)
        at com.oracle.svm.jni.functions.JNIFunctions.RegisterNatives(JNIFunctions.java:349)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_RegisterNatives_7728ce15b57af339792ad95c60f247990e0df65e(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace: 
        at parsing org.h2.util.Bits.readLong(Bits.java:156)
Call path from entry point to org.h2.util.Bits.readLong(byte[], int): 
        at org.h2.util.Bits.readLong(Bits.java:156)
        at org.h2.value.Value.convertToLong(Value.java:958)
        at org.h2.value.Value.convertTo(Value.java:766)
        at org.h2.value.Value.convertTo(Value.java:723)
        at org.h2.jdbc.JdbcPreparedStatement.setObject(JdbcPreparedStatement.java:565)
        at com.oracle.svm.reflect.PreparedStatement_setObject_5b494a5a8f7fcd76e8cd88a6cab852968d728fd3_1715.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at javax.xml.transform.TransformerException.printStackTrace(TransformerException.java:345)
        at javax.xml.transform.TransformerException.printStackTrace(TransformerException.java:285)
        at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:759)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace: 
        at parsing org.h2.util.Bits.uuidToBytes(Bits.java:212)
Call path from entry point to org.h2.util.Bits.uuidToBytes(long, long): 
        at org.h2.util.Bits.uuidToBytes(Bits.java:211)
        at org.h2.value.ValueUuid.getBytes(ValueUuid.java:201)
        at org.h2.jdbc.JdbcResultSet.getBytes(JdbcResultSet.java:1072)
        at org.h2.store.LobStorageBackend.readBlock(LobStorageBackend.java:232)
        at org.h2.store.LobStorageBackend$LobInputStream.fillBuffer(LobStorageBackend.java:770)
        at org.h2.store.LobStorageBackend$LobInputStream.skip(LobStorageBackend.java:706)
        at sun.net.www.MeteredStream.skip(MeteredStream.java:147)
        at sun.net.www.http.KeepAliveStreamCleaner.run(KeepAliveStreamCleaner.java:133)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
        at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace: 
        at parsing org.h2.util.Bits.writeDouble(Bits.java:300)
Call path from entry point to org.h2.util.Bits.writeDouble(byte[], int, double): 
        at org.h2.util.Bits.writeDouble(Bits.java:300)
        at org.h2.util.geometry.EWKBUtils$EWKBTarget.writeDouble(EWKBUtils.java:162)
        at org.h2.util.geometry.EWKBUtils$EWKBTarget.addCoordinate(EWKBUtils.java:146)
        at org.h2.util.geometry.EWKTUtils.parseEWKT(EWKTUtils.java:718)
        at org.h2.util.geometry.EWKTUtils.parseEWKT(EWKTUtils.java:608)
        at org.h2.value.ValueGeometry.get(ValueGeometry.java:117)
        at org.h2.value.Transfer.readValue(Transfer.java:771)
        at org.h2.server.TcpServerThread.setParameters(TcpServerThread.java:257)
        at org.h2.server.TcpServerThread.process(TcpServerThread.java:331)
        at org.h2.server.TcpServerThread.run(TcpServerThread.java:175)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
        at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace: 
        at parsing org.h2.util.Bits.writeInt(Bits.java:240)
Call path from entry point to org.h2.util.Bits.writeInt(byte[], int, int): 
        at org.h2.util.Bits.writeInt(Bits.java:240)
        at org.h2.store.Data.writeInt(Data.java:166)
        at org.h2.store.FileStoreOutputStream.write(FileStoreOutputStream.java:61)
        at java.util.zip.DeflaterOutputStream.flush(DeflaterOutputStream.java:277)
        at java.io.PrintStream.flush(PrintStream.java:417)
        at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:763)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace: 
        at parsing org.h2.util.Bits.writeLong(Bits.java:270)
Call path from entry point to org.h2.util.Bits.writeLong(byte[], int, long): 
        at org.h2.util.Bits.writeLong(Bits.java:270)
        at org.h2.security.SecureFileStore.xorInitVector(SecureFileStore.java:102)
        at org.h2.security.SecureFileStore.write(SecureFileStore.java:67)
        at org.h2.store.FileStoreOutputStream.write(FileStoreOutputStream.java:70)
        at java.util.zip.DeflaterOutputStream.flush(DeflaterOutputStream.java:277)
        at java.io.PrintStream.flush(PrintStream.java:417)
        at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:763)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1

```

**Comment by oubidar-Abderrahim** [comment]
I tried running you're example using GraalVM 21.0.0-dev, 20.3.0, and even 20.2.0. Yet still, I get the same error with each version. Are you sure this was working for Java 11 flavored GraalVM before? could you please confirm that this issue wasn't happening with the previous Java 11 GraalVM version (20.3.0)?

**Comment by ilopmar** [comment]
I've checked again and you are absolutelly right. I deeply apologize for this :worried: 

The issue is on our side (I'll check what is really going on tomorrow morning). We haven't been able to run our CI automatically lately, and we haven't been able to catch this when it happened so I though the issue was on GraalVM side.

Again, apologizes for the noise.
