### ISSUE TITLE
After installing WASM, you can no longer rebuild some configurations of native images

### ISSUE THREAD

**Issue by chrisseaton** [oracle/graal#3135]
After installing WASM, you can no longer rebuild some configurations of native images.

Ok:

```
% tar -zxf graalvm-ce-java8-darwin-amd64-21.0.0.tar.gz
% graalvm-ce-java8-21.0.0/Contents/Home/bin/gu install -L native-image-installable-svm-java8-darwin-amd64-21.0.0.jar 
Processing Component archive: native-image-installable-svm-java8-darwin-amd64-21.0.0.jar
Installing new component: Native Image (org.graalvm.native-image, version 21.0.0)
% graalvm-ce-java8-21.0.0/Contents/Home/bin/gu install -L llvm-toolchain-installable-java8-darwin-amd64-21.0.0.jar   
Processing Component archive: llvm-toolchain-installable-java8-darwin-amd64-21.0.0.jar
Installing new component: LLVM.org toolchain (org.graalvm.llvm-toolchain, version 21.0.0)
% graalvm-ce-java8-21.0.0/Contents/Home/bin/gu install -L espresso-installable-java8-darwin-amd64-21.0.0.jar      
Processing Component archive: espresso-installable-java8-darwin-amd64-21.0.0.jar
Installing new component: Java on Truffle (org.graalvm.espresso, version 21.0.0)

This version of Java on Truffle is experimental. We do not recommended it for production use.

Usage: java -truffle [-options] class [args...]
           (to execute a class)
    or java -truffle [-options] -jar jarfile [args...]
           (to execute a jar file)

To rebuild the polyglot library:
    gu rebuild-images libpolyglot -cp ${GRAALVM_HOME}/jre/lib/graalvm/lib-espresso.jar


IMPORTANT NOTE:
---------------
Set of GraalVM components that provide language implementations have changed. The Polyglot native image and polyglot native C library may be out of sync: 
- new languages may not be accessible
- removed languages may cause the native binary to fail on missing resources or libraries.
To rebuild and refresh the native binaries, use the following command:
        /Users/chrisseaton/Desktop/graalvm-ce-java8-darwin-amd64-21.0.0/graalvm-ce-java8-21.0.0/Contents/Home/bin/gu rebuild-images

% graalvm-ce-java8-21.0.0/Contents/Home/bin/gu install -L python-installable-svm-java8-darwin-amd64-21.0.0.jar 
Processing Component archive: python-installable-svm-java8-darwin-amd64-21.0.0.jar
Installing new component: Graal.Python (org.graalvm.python, version 21.0.0)

IMPORTANT NOTE:
---------------
Set of GraalVM components that provide language implementations have changed. The Polyglot native image and polyglot native C library may be out of sync: 
- new languages may not be accessible
- removed languages may cause the native binary to fail on missing resources or libraries.
To rebuild and refresh the native binaries, use the following command:
        /Users/chrisseaton/Desktop/graalvm-ce-java8-darwin-amd64-21.0.0/graalvm-ce-java8-21.0.0/Contents/Home/bin/gu rebuild-images

% graalvm-ce-java8-21.0.0/Contents/Home/bin/gu install -L ruby-installable-svm-java8-darwin-amd64-21.0.0.jar  
Processing Component archive: ruby-installable-svm-java8-darwin-amd64-21.0.0.jar
Installing new component: TruffleRuby (org.graalvm.ruby, version 21.0.0)

IMPORTANT NOTE:
---------------
The Ruby openssl C extension needs to be recompiled on your system to work with the installed libssl.
First, make sure TruffleRuby's dependencies are installed, which are described at:
  https://github.com/oracle/truffleruby/blob/master/README.md#dependencies
Then run the following command:
        /Users/chrisseaton/Desktop/graalvm-ce-java8-darwin-amd64-21.0.0/graalvm-ce-java8-21.0.0/Contents/Home/jre/languages/ruby/lib/truffle/post_install_hook.sh


IMPORTANT NOTE:
---------------
Set of GraalVM components that provide language implementations have changed. The Polyglot native image and polyglot native C library may be out of sync: 
- new languages may not be accessible
- removed languages may cause the native binary to fail on missing resources or libraries.
To rebuild and refresh the native binaries, use the following command:
        /Users/chrisseaton/Desktop/graalvm-ce-java8-darwin-amd64-21.0.0/graalvm-ce-java8-21.0.0/Contents/Home/bin/gu rebuild-images

% graalvm-ce-java8-21.0.0/Contents/Home/bin/gu rebuild-images libpolyglot
Building libpolyglot...
-H:IncludeAllTimeZones and -H:IncludeTimeZones are now deprecated. Native-image includes all timezones by default.
[libpolyglot:58883]    classlist:   6,894.50 ms,  2.32 GB
[libpolyglot:58883]        (cap):   5,747.15 ms,  2.32 GB
[libpolyglot:58883]        setup:   8,564.33 ms,  2.32 GB
[libpolyglot:58883]     (clinit):   5,043.79 ms, 12.44 GB
[libpolyglot:58883]   (typeflow): 334,397.55 ms, 12.44 GB
[libpolyglot:58883]    (objects): 451,386.79 ms, 12.44 GB
[libpolyglot:58883]   (features):  91,295.68 ms, 12.44 GB
[libpolyglot:58883]     analysis: 907,139.05 ms, 12.44 GB
[libpolyglot:58883]     universe:   7,132.32 ms, 12.44 GB
38811 method(s) included for runtime compilation
[libpolyglot:58883]      (parse):  25,070.81 ms, 12.27 GB
[libpolyglot:58883]     (inline):  24,842.37 ms, 12.44 GB
[libpolyglot:58883]    (compile):  82,025.66 ms, 13.00 GB
[libpolyglot:58883]      compile: 149,366.84 ms, 13.00 GB
[libpolyglot:58883]        image: 114,789.41 ms, 12.44 GB
[libpolyglot:58883]        write:  10,605.73 ms, 12.44 GB
[libpolyglot:58883]      [total]: 1,209,622.68 ms, 12.44 GB
```

Not ok:

```
% tar -zxf graalvm-ce-java8-darwin-amd64-21.0.0.tar.gz
% graalvm-ce-java8-21.0.0/Contents/Home/bin/gu install -L native-image-installable-svm-java8-darwin-amd64-21.0.0.jar 
Processing Component archive: native-image-installable-svm-java8-darwin-amd64-21.0.0.jar
Installing new component: Native Image (org.graalvm.native-image, version 21.0.0)
% graalvm-ce-java8-21.0.0/Contents/Home/bin/gu install -L llvm-toolchain-installable-java8-darwin-amd64-21.0.0.jar   
Processing Component archive: llvm-toolchain-installable-java8-darwin-amd64-21.0.0.jar
Installing new component: LLVM.org toolchain (org.graalvm.llvm-toolchain, version 21.0.0)
% graalvm-ce-java8-21.0.0/Contents/Home/bin/gu install -L espresso-installable-java8-darwin-amd64-21.0.0.jar      
Processing Component archive: espresso-installable-java8-darwin-amd64-21.0.0.jar
Installing new component: Java on Truffle (org.graalvm.espresso, version 21.0.0)

This version of Java on Truffle is experimental. We do not recommended it for production use.

Usage: java -truffle [-options] class [args...]
           (to execute a class)
    or java -truffle [-options] -jar jarfile [args...]
           (to execute a jar file)

To rebuild the polyglot library:
    gu rebuild-images libpolyglot -cp ${GRAALVM_HOME}/jre/lib/graalvm/lib-espresso.jar


IMPORTANT NOTE:
---------------
Set of GraalVM components that provide language implementations have changed. The Polyglot native image and polyglot native C library may be out of sync: 
- new languages may not be accessible
- removed languages may cause the native binary to fail on missing resources or libraries.
To rebuild and refresh the native binaries, use the following command:
        /Users/chrisseaton/Desktop/graalvm-ce-java8-darwin-amd64-21.0.0/graalvm-ce-java8-21.0.0/Contents/Home/bin/gu rebuild-images

% graalvm-ce-java8-21.0.0/Contents/Home/bin/gu install -L python-installable-svm-java8-darwin-amd64-21.0.0.jar 
Processing Component archive: python-installable-svm-java8-darwin-amd64-21.0.0.jar
Installing new component: Graal.Python (org.graalvm.python, version 21.0.0)

IMPORTANT NOTE:
---------------
Set of GraalVM components that provide language implementations have changed. The Polyglot native image and polyglot native C library may be out of sync: 
- new languages may not be accessible
- removed languages may cause the native binary to fail on missing resources or libraries.
To rebuild and refresh the native binaries, use the following command:
        /Users/chrisseaton/Desktop/graalvm-ce-java8-darwin-amd64-21.0.0/graalvm-ce-java8-21.0.0/Contents/Home/bin/gu rebuild-images

% graalvm-ce-java8-21.0.0/Contents/Home/bin/gu install -L ruby-installable-svm-java8-darwin-amd64-21.0.0.jar  
Processing Component archive: ruby-installable-svm-java8-darwin-amd64-21.0.0.jar
Installing new component: TruffleRuby (org.graalvm.ruby, version 21.0.0)

IMPORTANT NOTE:
---------------
The Ruby openssl C extension needs to be recompiled on your system to work with the installed libssl.
First, make sure TruffleRuby's dependencies are installed, which are described at:
  https://github.com/oracle/truffleruby/blob/master/README.md#dependencies
Then run the following command:
        /Users/chrisseaton/Desktop/graalvm-ce-java8-darwin-amd64-21.0.0/graalvm-ce-java8-21.0.0/Contents/Home/jre/languages/ruby/lib/truffle/post_install_hook.sh


IMPORTANT NOTE:
---------------
Set of GraalVM components that provide language implementations have changed. The Polyglot native image and polyglot native C library may be out of sync: 
- new languages may not be accessible
- removed languages may cause the native binary to fail on missing resources or libraries.
To rebuild and refresh the native binaries, use the following command:
        /Users/chrisseaton/Desktop/graalvm-ce-java8-darwin-amd64-21.0.0/graalvm-ce-java8-21.0.0/Contents/Home/bin/gu rebuild-images

% graalvm-ce-java8-21.0.0/Contents/Home/bin/gu install -L wasm-installable-svm-java8-darwin-amd64-21.0.0.jar 
Processing Component archive: wasm-installable-svm-java8-darwin-amd64-21.0.0.jar
Installing new component: GraalWasm (org.graalvm.wasm, version 21.0.0)

IMPORTANT NOTE:
---------------
Set of GraalVM components that provide language implementations have changed. The Polyglot native image and polyglot native C library may be out of sync: 
- new languages may not be accessible
- removed languages may cause the native binary to fail on missing resources or libraries.
To rebuild and refresh the native binaries, use the following command:
        /Users/chrisseaton/Desktop/graalvm-ce-java8-darwin-amd64-21.0.0/graalvm-ce-java8-21.0.0/Contents/Home/bin/gu rebuild-images

% graalvm-ce-java8-21.0.0/Contents/Home/bin/gu rebuild-images libpolyglot
Building libpolyglot...
-H:IncludeAllTimeZones and -H:IncludeTimeZones are now deprecated. Native-image includes all timezones by default.
[libpolyglot:56427]    classlist:   8,066.06 ms,  2.96 GB
[libpolyglot:56427]        (cap):   7,025.27 ms,  2.96 GB
[libpolyglot:56427]        setup:  11,176.97 ms,  2.96 GB
[To redirect Truffle log output to a file use one of the following options:
* '--log.file=<path>' if the option is passed using a guest language launcher.
* '-Dpolyglot.log.file=<path>' if the option is passed using the host Java launcher.
* Configure logging using the polyglot embedding API.]
[engine::PolyglotContextImpl] WARNING: Language wasm cannot be pre-initialized as it does not override TruffleLanguage.patchContext method.
[libpolyglot:56427]     (clinit):   4,897.94 ms, 12.44 GB
[libpolyglot:56427]   (typeflow): 1,112,920.98 ms, 12.44 GB
[libpolyglot:56427]    (objects): 701,031.51 ms, 12.44 GB
[libpolyglot:56427]   (features): 201,744.88 ms, 12.44 GB
[libpolyglot:56427]     analysis: 2,049,724.64 ms, 12.44 GB
[libpolyglot:56427]     universe:   6,630.80 ms, 12.44 GB
39279 method(s) included for runtime compilation

=== Found 8 compilation blacklist violations ===

Blacklisted method
  java.lang.StringBuffer.append(String)
called from
  java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:668)
  java.lang.StringBuilder.append(StringBuilder.java:208) -> org.graalvm.wasm.nodes.WasmRootNode.executeWithContext(WasmRootNode.java:155)
  org.graalvm.wasm.nodes.WasmRootNode.execute(WasmRootNode.java:103)
  org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:591)
  org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:562)
  
Blacklisted method
  java.lang.String.valueOf(Object)
called from
  java.lang.StringBuilder.append(StringBuilder.java:131)
  org.graalvm.wasm.api.Dictionary.toDisplayString(Dictionary.java:119)
  org.graalvm.wasm.api.DictionaryGen$InteropLibraryExports$Cached.toDisplayString(DictionaryGen.java:90)
  org.truffleruby.interop.InteropNodes$ToDisplayStringNode.toDisplayString(InteropNodes.java:897)
  org.truffleruby.interop.InteropNodesFactory$ToDisplayStringNodeFactory$ToDisplayStringNodeGen.execute(InteropNodesFactory.java:9422)
  org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:61)
  org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:591)
  org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:562)
  
Blacklisted method
  java.util.HashMap.containsKey(Object)
called from
  org.graalvm.wasm.api.Dictionary.isMemberReadable(Dictionary.java:107)
  org.graalvm.wasm.api.DictionaryGen$InteropLibraryExports$Cached.isMemberReadable(DictionaryGen.java:84)
  com.oracle.truffle.js.builtins.ObjectFunctionBuiltins$ObjectGetOwnPropertyDescriptorNode.getForeignObject(ObjectFunctionBuiltins.java:355)
  com.oracle.truffle.js.builtins.ObjectFunctionBuiltinsFactory$ObjectGetOwnPropertyDescriptorNodeGen.execute(ObjectFunctionBuiltinsFactory.java:232)
  com.oracle.truffle.js.nodes.control.AsyncFunctionBodyNode$AsyncFunctionRootNode.execute(AsyncFunctionBodyNode.java:142)
  org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:591)
  org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:562)
  
Blacklisted method
  java.util.HashMap.containsKey(Object)
called from
  org.graalvm.wasm.api.Dictionary.isMemberReadable(Dictionary.java:107) -> org.graalvm.wasm.api.Global.isMemberReadable(Global.java:116)
  org.graalvm.wasm.api.DictionaryGen$InteropLibraryExports$Cached.isMemberReadable(DictionaryGen.java:84)
  com.oracle.truffle.js.builtins.ObjectFunctionBuiltins$ObjectGetOwnPropertyDescriptorNode.getForeignObject(ObjectFunctionBuiltins.java:355)
  com.oracle.truffle.js.builtins.ObjectFunctionBuiltinsFactory$ObjectGetOwnPropertyDescriptorNodeGen.execute(ObjectFunctionBuiltinsFactory.java:232)
  com.oracle.truffle.js.nodes.control.AsyncFunctionBodyNode$AsyncFunctionRootNode.execute(AsyncFunctionBodyNode.java:142)
  org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:591)
  org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:562)
  
Blacklisted method
  java.util.HashMap.containsKey(Object)
called from
  org.graalvm.wasm.api.Dictionary.isMemberReadable(Dictionary.java:107) -> org.graalvm.wasm.api.ProxyGlobal.isMemberReadable(ProxyGlobal.java:80)
  org.graalvm.wasm.api.DictionaryGen$InteropLibraryExports$Cached.isMemberReadable(DictionaryGen.java:84)
  com.oracle.truffle.js.builtins.ObjectFunctionBuiltins$ObjectGetOwnPropertyDescriptorNode.getForeignObject(ObjectFunctionBuiltins.java:355)
  com.oracle.truffle.js.builtins.ObjectFunctionBuiltinsFactory$ObjectGetOwnPropertyDescriptorNodeGen.execute(ObjectFunctionBuiltinsFactory.java:232)
  com.oracle.truffle.js.nodes.control.AsyncFunctionBodyNode$AsyncFunctionRootNode.execute(AsyncFunctionBodyNode.java:142)
  org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:591)
  org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:562)
  
Blacklisted method
  java.util.HashMap.containsKey(Object)
called from
  org.graalvm.wasm.api.Dictionary.isMemberReadable(Dictionary.java:107) -> org.graalvm.wasm.api.Table.isMemberReadable(Table.java:85)
  org.graalvm.wasm.api.DictionaryGen$InteropLibraryExports$Cached.isMemberReadable(DictionaryGen.java:84)
  com.oracle.truffle.js.builtins.ObjectFunctionBuiltins$ObjectGetOwnPropertyDescriptorNode.getForeignObject(ObjectFunctionBuiltins.java:355)
  com.oracle.truffle.js.builtins.ObjectFunctionBuiltinsFactory$ObjectGetOwnPropertyDescriptorNodeGen.execute(ObjectFunctionBuiltinsFactory.java:232)
  com.oracle.truffle.js.nodes.control.AsyncFunctionBodyNode$AsyncFunctionRootNode.execute(AsyncFunctionBodyNode.java:142)
  org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:591)
  org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:562)
  
Blacklisted method
  java.util.HashMap.getNode(int, Object)
called from
  java.util.LinkedHashMap.get(LinkedHashMap.java:440)
  org.graalvm.wasm.api.Dictionary.readMember(Dictionary.java:76)
  org.graalvm.wasm.api.DictionaryGen$InteropLibraryExports$Cached.readMember(DictionaryGen.java:72)
  com.oracle.truffle.js.builtins.ObjectFunctionBuiltins$ObjectGetOwnPropertyDescriptorNode.getForeignObject(ObjectFunctionBuiltins.java:357)
  com.oracle.truffle.js.builtins.ObjectFunctionBuiltinsFactory$ObjectGetOwnPropertyDescriptorNodeGen.execute(ObjectFunctionBuiltinsFactory.java:232)
  com.oracle.truffle.js.nodes.control.AsyncFunctionBodyNode$AsyncFunctionRootNode.execute(AsyncFunctionBodyNode.java:142)
  org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:591)
  org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:562)
  
Blacklisted method
  java.util.HashMap.hash(Object)
called from
  java.util.LinkedHashMap.get(LinkedHashMap.java:440)
  org.graalvm.wasm.api.Dictionary.readMember(Dictionary.java:76)
  org.graalvm.wasm.api.DictionaryGen$InteropLibraryExports$Cached.readMember(DictionaryGen.java:72)
  com.oracle.truffle.js.builtins.ObjectFunctionBuiltins$ObjectGetOwnPropertyDescriptorNode.getForeignObject(ObjectFunctionBuiltins.java:357)
  com.oracle.truffle.js.builtins.ObjectFunctionBuiltinsFactory$ObjectGetOwnPropertyDescriptorNodeGen.execute(ObjectFunctionBuiltinsFactory.java:232)
  com.oracle.truffle.js.nodes.control.AsyncFunctionBodyNode$AsyncFunctionRootNode.execute(AsyncFunctionBodyNode.java:142)
  org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:591)
  org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:562)
  
Fatal error:com.oracle.svm.core.util.VMError$HostedError: Blacklisted methods are reachable for runtime compilation
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
	at com.oracle.svm.truffle.TruffleFeature.beforeCompilation(TruffleFeature.java:920)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$doRun$2(NativeImageGenerator.java:619)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:619)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Error: Image build request failed with exit status 1
```

**Comment by chrisseaton** [comment]
I see the warning, `WARNING: Language wasm cannot be pre-initialized as it does not override TruffleLanguage.patchContext method.`, but if that's what causes the hard error should it be an error not a warning, and should it be excluded from Native Images when installed so we don't need the warning or error?

**Comment by mcraj017** [comment]
@chrisseaton thanks for reporting the issue
this error has been fixed in the latest dev release
https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/21.1.0-dev-20210126_1929

**Comment by abvijaykumar** [comment]
Even I had the same issue, when I tried to compile the espresso. I remove WASM and I was able rebuild espresso
