### ISSUE TITLE
[gu] `gu upgrade --edition ee` fails with "Internal error occurred: null"

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#3137]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **21.0.0*
 - CE or EE: **CE**
 - JDK version: **JDK11**
 - OS and OS Version: **macOS Catalina**
 - Architecture: **amd64**

According to [this](https://www.graalvm.org/reference-manual/graalvm-updater/#upgrade-graalvm), `gu upgrade --edition ee` should "install the newest version of GraalVM Enterprise Edition, next to the current installation". Instead, the command fails with "Internal error occurred: null" (at least currently).

#### Repro
```
$ gu --verbose upgrade --edition ee
Downloading: Release index file (source: https://oca.opensource.oracle.com/gds/meta-data.json)
Receiving 16 kB: Done.
Downloading: Component catalog for GraalVM Enterprise Edition 21.0.0 on jdk11 (source: https://oca.opensource.oracle.com/gds/GRAALVM_EE_JAVA11_21_0_0/21_0_0_EE_Java11_component-catalog.properties)
Receiving 24 kB: Done.
Internal error occurred: null
```

**Comment by oubidar-Abderrahim** [comment]
I just tried locally from my macOS Mojave 10.14.6 and it worked as expected (see the logs below). Can you please re-check that you're using the correct version? 

```
~ gu upgrade --edition ee
Downloading: Release index file from oca.opensource.oracle.com
Downloading: Component catalog for GraalVM Enterprise Edition 21.0.0 on jdk11 from oca.opensource.oracle.com
=========================================================================
	Preparing to install GraalVM Core version 21.0.0.
	Destination directory: /Users/aoubidar/Desktop/CE/graalvm-ee-java11-21.0.0
=========================================================================
The component(s) GraalVM Core requires to accept the following license: GraalVM Enterprise Edition License
Enter "Y" to confirm and accept all the license(s). Enter "R" to the see license text.
Any other input will abort installation: Y
Downloading: Contents of "GraalVM Enterprise Edition License" from oca.opensource.oracle.com
Please provide an e-mail address to not show the license check again (optional). You may want to check Oracle Privacy Policy (https://www.oracle.com/legal/privacy/privacy-policy.html).
Enter a valid e-mail address:      
Please provide an e-mail address to not show the license check again (optional). You may want to check Oracle Privacy Policy (https://www.oracle.com/legal/privacy/privacy-policy.html).
Enter a valid e-mail address: Downloading: Component core: GraalVM Core from oca.opensource.oracle.com
Please provide an e-mail address to not show the license check again (optional). You may want to check Oracle Privacy Policy (https://www.oracle.com/legal/privacy/privacy-policy.html).
Enter a valid e-mail address: Downloading: Component org.graalvm: GraalVM Core from oca.opensource.oracle.com
Installing GraalVM Core version 21.0.0 to /Users/aoubidar/Desktop/CE/graalvm-ee-java11-21.0.0...
Copying license info from 21.0.0 to 21.0.0.
```

Also, it is worth mentioning that there is currently an issue with using `gu` from another GraalVM installation beside the one you are declaring in your `GRAALVM_HOME` variable. so if you type `/graalvm-ce-java11-21.0.0/bin/gu --version` while you are declaring (for example) 20.3.0 in your PATH, it will print `GraalVM Updater 20.3.0` and not 21.0.0. this issue is tracked internally on `GR-28873`, and the workaround for this is to set the `GRAALVM_HOME` to the desired installation and add it to your `PATH` variable.

Please let's know if the issue was resolved for you.

**Comment by fniephaus** [comment]
Mh... no matter what I do, I always end up with the same error. Is there anyway to print the stack trace of this internal error?

**Comment by oubidar-Abderrahim** [comment]
You can use `-e` or `--debug` to print stacktraces

**Comment by fniephaus** [comment]
Thanks! Here's the stack trace:
```
$ gu upgrade --debug --edition ee
Downloading: Release index file from oca.opensource.oracle.com
Downloading: Component catalog for GraalVM Enterprise Edition 21.0.0 on jdk11 from oca.opensource.oracle.com
Internal error occurred: null
java.lang.NullPointerException
	at org.graalvm.component.installer.model.ComponentRegistry.shortenComponentId(ComponentRegistry.java:452)
	at org.graalvm.component.installer.commands.UpgradeProcess.findGraalVersion(UpgradeProcess.java:515)
	at org.graalvm.component.installer.commands.UpgradeCommand.configureProcess(UpgradeCommand.java:153)
	at org.graalvm.component.installer.commands.UpgradeCommand.execute(UpgradeCommand.java:166)
	at org.graalvm.component.installer.ComponentInstaller.doProcessCommand(ComponentInstaller.java:431)
	at org.graalvm.component.installer.ComponentInstaller.processCommand(ComponentInstaller.java:445)
	at org.graalvm.component.installer.ComponentInstaller.run(ComponentInstaller.java:569)
	at org.graalvm.component.installer.ComponentInstaller.main(ComponentInstaller.java:622)
```

And this seems to be the line:
https://github.com/oracle/graal/blob/ef37eb9a6697c3d600db2d89f1d2b755454adedd/vm/src/org.graalvm.component.installer/src/org/graalvm/component/installer/model/ComponentRegistry.java#L452

**Comment by oubidar-Abderrahim** [comment]
Would you mind also sharing the content of the release file? you'll find it in `graalvm-ce-java11-21.0.0/Content/Home/release`

**Comment by fniephaus** [comment]
Sure, my `graalvm-ce-java11-21.0.0/Contents/Home/release` looks like this:

```
IMPLEMENTOR="GraalVM Community"
JAVA_VERSION="11.0.10"
JAVA_VERSION_DATE="2021-01-19"
LIBC="default"
MODULES="java.base java.logging jdk.internal.vm.ci jdk.unsupported org.graalvm.sdk java.datatransfer java.xml java.prefs java.desktop java.management org.graalvm.truffle jdk.internal.vm.compiler com.oracle.graal.graal_enterprise java.compiler java.instrument java.security.sasl java.naming java.rmi java.management.rmi java.net.http java.scripting java.security.jgss java.transaction.xa java.sql java.sql.rowset java.xml.crypto java.se java.smartcardio jdk.accessibility jdk.aot jdk.internal.jvmstat jdk.attach jdk.charsets jdk.compiler jdk.crypto.ec jdk.crypto.cryptoki jdk.dynalink jdk.internal.ed jdk.editpad jdk.hotspot.agent jdk.httpserver jdk.internal.le jdk.internal.opt jdk.management jdk.internal.vm.compiler.management jdk.jfr jdk.internal.vm.compiler.truffle.jfr jdk.jartool jdk.javadoc jdk.jcmd jdk.management.agent jdk.jconsole jdk.jdeps jdk.jdwp.agent jdk.jdi jdk.jlink jdk.jshell jdk.jsobject jdk.jstatd jdk.localedata jdk.management.jfr jdk.naming.dns jdk.naming.ldap jdk.naming.rmi jdk.net jdk.pack jdk.rmic jdk.scripting.nashorn jdk.scripting.nashorn.shell jdk.sctp jdk.security.auth jdk.security.jgss jdk.unsupported.desktop jdk.xml.dom jdk.zipfs org.graalvm.js.scriptengine org.graalvm.locator"
OS_ARCH="x86_64"
OS_NAME="Darwin"
SOURCE=".:git:1cd24cbef646+ compiler:ec048fd719531a06ed10a3dc79503506b75cb091 graal-js:556f438b715b03fee5942d60d0db9c0f5e914422 graal-nodejs:556f438b715b03fee5942d60d0db9c0f5e914422 java-benchmarks:ec048fd719531a06ed10a3dc79503506b75cb091 regex:ec048fd719531a06ed10a3dc79503506b75cb091 sdk:ec048fd719531a06ed10a3dc79503506b75cb091 substratevm:ec048fd719531a06ed10a3dc79503506b75cb091 sulong:ec048fd719531a06ed10a3dc79503506b75cb091 tools:ec048fd719531a06ed10a3dc79503506b75cb091 truffle:ec048fd719531a06ed10a3dc79503506b75cb091 vm:ec048fd719531a06ed10a3dc79503506b75cb091"
GRAALVM_VERSION="21.0.0"
COMMIT_INFO={"compiler": {"commit.committer": "Gilles Duboscq <gilles.m.duboscq@oracle.com>", "commit.committer-ts": 1610736025, "commit.rev": "ec048fd719531a06ed10a3dc79503506b75cb091"}, "graal-js": {"commit.committer": "Gilles Duboscq <gilles.m.duboscq@oracle.com>", "commit.committer-ts": 1610735918, "commit.rev": "556f438b715b03fee5942d60d0db9c0f5e914422"}, "graal-nodejs": {"commit.committer": "Gilles Duboscq <gilles.m.duboscq@oracle.com>", "commit.committer-ts": 1610735918, "commit.rev": "556f438b715b03fee5942d60d0db9c0f5e914422"}, "java-benchmarks": {"commit.committer": "Gilles Duboscq <gilles.m.duboscq@oracle.com>", "commit.committer-ts": 1610736025, "commit.rev": "ec048fd719531a06ed10a3dc79503506b75cb091"}, "regex": {"commit.committer": "Gilles Duboscq <gilles.m.duboscq@oracle.com>", "commit.committer-ts": 1610736025, "commit.rev": "ec048fd719531a06ed10a3dc79503506b75cb091"}, "sdk": {"commit.committer": "Gilles Duboscq <gilles.m.duboscq@oracle.com>", "commit.committer-ts": 1610736025, "commit.rev": "ec048fd719531a06ed10a3dc79503506b75cb091"}, "substratevm": {"commit.committer": "Gilles Duboscq <gilles.m.duboscq@oracle.com>", "commit.committer-ts": 1610736025, "commit.rev": "ec048fd719531a06ed10a3dc79503506b75cb091"}, "sulong": {"commit.committer": "Gilles Duboscq <gilles.m.duboscq@oracle.com>", "commit.committer-ts": 1610736025, "commit.rev": "ec048fd719531a06ed10a3dc79503506b75cb091"}, "tools": {"commit.committer": "Gilles Duboscq <gilles.m.duboscq@oracle.com>", "commit.committer-ts": 1610736025, "commit.rev": "ec048fd719531a06ed10a3dc79503506b75cb091"}, "truffle": {"commit.committer": "Gilles Duboscq <gilles.m.duboscq@oracle.com>", "commit.committer-ts": 1610736025, "commit.rev": "ec048fd719531a06ed10a3dc79503506b75cb091"}, "vm": {"commit.committer": "Gilles Duboscq <gilles.m.duboscq@oracle.com>", "commit.committer-ts": 1610736025, "commit.rev": "ec048fd719531a06ed10a3dc79503506b75cb091"}}
component_catalog="https://www.graalvm.org/component-catalog/v2/graal-updater-component-catalog-java11.properties|{ee=GraalVM Enterprise Edition}gds://oca.opensource.oracle.com/gds/meta-data.json"
```

**Comment by oubidar-Abderrahim** [comment]
The version looks the same as mine, yet I cannot reproduce this issue on my machine. 

First of all, could you please redownload `graalvm-ce-java11-darwin-amd64-21.0.0.tar.gz` from https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.0.0 and try again, just to eliminate the possibility of something went wrong during the first download.

Also kindly provide the System version and Kernel version you're using. You can find such information using the command `system_profiler SPSoftwareDataType` on a terminal.

**Comment by fniephaus** [comment]
After downloading the bundle again, `gu upgrade --edition ee` seems to work fine. Not sure how I "broke" my initial installation (I have installed some languages, rebuilt images, etc). I'll keep an eye on it and will re-open if this happens again.

Thanks for your help!
