### ISSUE TITLE
GraalSDK doesn't recognize -XX:+EnableJVMCI flag.

### ISSUE THREAD

**Issue by rahmanusta** [oracle/graal#3145]
GraalSDK doesn't recognize -XX:+EnableJVMCI flag.

I tried to run Java code with espresso in graal-sdk. I'm getting the following error:

```
java.lang.Error: The EnableJVMCI VM option must be true (i.e., -XX:+EnableJVMCI) to use JVMCI
	at jdk.internal.vm.ci/jdk.vm.ci.services.Services.checkJVMCIEnabled(Services.java:83) ~[na:na]
	at jdk.internal.vm.ci/jdk.vm.ci.services.Services.initializeJVMCI(Services.java:130) ~[na:na]

```
I set the JVM parameters to `-XX:+IgnoreUnrecognizedVMOptions -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:-UseJVMCICompiler -truffle` surprisingly it continue asking same error. Is flag name changed ?

**I'm using:**
- graal-sdk(21.0.0)
- graalvm ce 21.0.0 (jdk 11)
- macOS big sur
- AMD 64

**Comment by gilles-duboscq** [comment]
Java on Truffle doesn't support JVMCI at the moment. In particular, `-XX:+EnableJVMCI` is not supported.

**Comment by mukel** [comment]
When you run with `java -truffle`, the Java bytecodes run as a guest Truffle language. Using the graal-sdk inside Espresso may work (because is just Java code), but it will be very slow (interpreter-mode only). The graal-sdk is meant to be used from host Java, where you can e.g. spawn a guest Java (Espresso) context.

**Comment by rahmanusta** [comment]
I understand, maybe the problem is different. I just wanted to run java code with graal-sdk. I have Graalvm and espresso installed. I'm running the code below without any JVM arguments.

```
import org.graalvm.polyglot.Context;

public class ContextRun {

    public static void main(String[] args) throws ReflectiveOperationException {
        Context context = Context.newBuilder()
                .build();
        context.eval("java", "System.out.println(\"Hello world\")");

    }
}
```

This is giving me an error:

```
Exception in thread "main" org.graalvm.polyglot.PolyglotException: com.oracle.truffle.espresso.meta.EspressoError: failed guarantee: Native access is not allowed by the host environment but it's required to load Espresso/Java native libraries. Allow native access on context creation e.g. contextBuilder.allowNativeAccess(true)
	at com.oracle.truffle.espresso.meta.EspressoError.guarantee(EspressoError.java:96)
	at com.oracle.truffle.espresso.runtime.EspressoContext.initializeContext(EspressoContext.java:326)
	at com.oracle.truffle.espresso.EspressoLanguage.initializeContext(EspressoLanguage.java:205)
	at com.oracle.truffle.espresso.EspressoLanguage.initializeContext(EspressoLanguage.java:65)
	at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$Env.postInit(TruffleLanguage.java:3397)
	at org.graalvm.truffle/com.oracle.truffle.api.LanguageAccessor$LanguageImpl.postInitEnv(LanguageAccessor.java:300)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureInitialized(PolyglotLanguageContext.java:597)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:939)
	at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:347)
```

Okay, then I'm giving native access with allowNativeAccess(true), then I start getting another error:

```
[java] SEVERE: TruffleNFI native library isolation is not supported.
java.lang.IllegalArgumentException: isolated namespace not supported
	at com.oracle.truffle.nfi.impl.NFIBackendImpl.parse(NFIBackendImpl.java:103)
	at com.oracle.truffle.nfi.NFIRootNode$LoadLibraryNode.parseLibrary(NFIRootNode.java:105)
```

Then, I tried to enable JVMCI, but it also didn't help. How can I run a Java code with graal-sdk ? What is wrong with my code/configuration ?

Thank you.

**Comment by gilles-duboscq** [comment]
You should not use the `-truffle` flag when you start your program.
The `-truffle` flag will run your program in Java on truffle mode (aka "espresso"). However, your program seems to be made to run in HotSpot or native-image: it starts a Java on Truffle context (guest VM) inside a HotSpot or native-image (host VM).

Also note that Java on Truffle is an implementation of the Java Virtual Machine, not of the Java language. As a result you can't just pass it a piece of Java source code, it only understands bytecodes.
This page in the documentation will give some more details: [Embedding in Host Java](https://www.graalvm.org/reference-manual/java-on-truffle/interoperability/#embedding-in-host-java)

**Comment by mukel** [comment]
Running Espresso on HotSpot is only supported on Linux ATM with some limitations. We need to be able to isolate Espresso native libraries from the HotSpot natives libraries. For such purpose we use glibc's `dlmopen` to create isolated linking namespaces within the same process; we couldn't find similar functionality on Mac or Windows; suggestions are very welcome.
There's a prototype that run all native code (all OpenJDK native libraries compiled to LLVM bitcode) via Sulong, providing such isolation, until that lands, MacOS and Windows are limited to use Espresso in native mode, single context.

**Comment by mukel** [comment]
[Support for Sulong landed on master](https://github.com/oracle/graal/commit/4c151903220030781bea05a09c704c304cd16678), but it cannot be used out-of-the-box yet since it requires a special build of the OpenJDK native libraries (compiled to LLVM bitcode).
