### ISSUE TITLE
SerializationSupport.getSerializationConstructorAccessor throws misleading Exception. when called with abstract class

### ISSUE THREAD

**Issue by warrenc5** [oracle/graal#3156]
OpenJDK Runtime Environment GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06)
5.9.0-5-amd64

Jboss has it's own ideas about serialization and reflection and may be calling SerializationSupport incorrectly with an abstract class.  SerializationSupport could be tolerant and check and return null or throw ??

Adding ... does not help.
```
[
  {
  "name":"java.util.AbstractMap"
  }
]
```

```
Exception in thread "remoting-jmx client-thread-1" com.oracle.svm.core.jdk.UnsupportedFeatureError: SerializationConstructorAccessor class not found for declaringClass: java.util.AbstractMap (targetConstructorClass: java.lang.Object). Usually adding java.util.AbstractMap to serialization-config.json fixes the problem.
  at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:87)
        at com.oracle.svm.reflect.serialize.SerializationSupport.getSerializationConstructorAccessor(SerializationSupport.java:132)
        at jdk.internal.reflect.MethodAccessorGenerator.generateSerializationConstructor(MethodAccessorGenerator.java:48)
        at jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:514)
        at jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:427)
        at sun.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:103)
        at org.jboss.marshalling.reflect.JDKSpecific.newConstructorForSerialization(JDKSpecific.java:48)
        at org.jboss.marshalling.reflect.SerializableClass.<init>(SerializableClass.java:79)
        at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:62)
        at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:59)
        at java.lang.ClassValue.get(JavaLangSubstitutions.java:602)
        at org.jboss.marshalling.reflect.SerializableClassRegistry.lookup(SerializableClassRegistry.java:83)
        at org.jboss.marshalling.reflect.SerializableClass.<init>(SerializableClass.java:76)
        at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:62)
        at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:59)
        at java.lang.ClassValue.get(JavaLangSubstitutions.java:602)
        at org.jboss.marshalling.reflect.SerializableClassRegistry.lookup(SerializableClassRegistry.java:83)
        at org.jboss.marshalling.river.ClassDescriptors.getSerializableClassDescriptor(ClassDescriptors.java:152)
        at org.jboss.marshalling.river.ClassDescriptors.getSerializableClassDescriptor(ClassDescriptors.java:146)
        at org.jboss.marshalling.river.ClassDescriptors.<clinit>(ClassDescriptors.java:101)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
        at org.jboss.marshalling.river.RiverUnmarshaller.doReadClassDescriptor(RiverUnmarshaller.java:1253)
        at org.jboss.marshalling.river.RiverUnmarshaller.doReadClassDescriptor(RiverUnmarshaller.java:1049)
        at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1366)
        at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:283)
        at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:216)
        at org.jboss.marshalling.AbstractObjectInput.readObject(AbstractObjectInput.java:41)
        at org.jboss.remotingjmx.protocol.v2.ClientCommon$MarshalledResponseHandler.readValue(ClientCommon.java:224)
        at org.jboss.remotingjmx.protocol.v2.ClientCommon$BaseResponseHandler.handle(ClientCommon.java:176)
        at org.jboss.remotingjmx.protocol.v2.ClientCommon$MessageReceiver$1.run(ClientCommon.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)

```

The call is comming from https://github.com/jboss-remoting/jboss-marshalling/blob/2.0.9.Final

**Comment by warrenc5** [comment]
Ok - it looks like I can resolve the abstract classes constructor with Object<init>() - Which is what jboss/river actually does. 

```
package org.jboss.marshalling.reflect;

import com.oracle.svm.core.annotate.Substitute;
import com.oracle.svm.core.annotate.TargetClass;
import java.lang.reflect.Constructor;
import java.lang.reflect.Modifier;

@TargetClass(value = org.jboss.marshalling.reflect.JDKSpecific.class)
final class Target_org_jboss_marshalling_reflect_JDKSpecific {

    @Substitute(polymorphicSignature = false)
    static Constructor<?> newConstructorForSerialization(Class<?> classToInstantiate, Constructor<?> constructorToCall) {

        if (constructorToCall != null) {
            return constructorToCall;
        } else if (Modifier.isAbstract(classToInstantiate.getModifiers())) {
            return null;
        } else {
            try {
                return classToInstantiate.getDeclaredConstructor(new Class[0]);
            } catch (NoSuchMethodException ex) {
                ex.printStackTrace();
            } catch (SecurityException ex) {
                ex.printStackTrace();
            }
        }
        return null;
    }

}
```

Then I end up with an exception from Outputstream.write. 



```
java.util.EnumSet public java.lang.Object()
Exception in thread "remoting-jmx client-thread-1" com.oracle.svm.core.jdk.UnsupportedFeatureError: SerializationConstructorAccessor class not found for declaringClass: java.util.EnumSet (targetConstructorClass: java.util.AbstractSet). Usually adding java.util.EnumSet to serialization-config.json fixes the problem.
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:87)
        at com.oracle.svm.reflect.serialize.SerializationSupport.getSerializationConstructorAccessor(SerializationSupport.java:132)
        at jdk.internal.reflect.MethodAccessorGenerator.generateSerializationConstructor(MethodAccessorGenerator.java:48)
        at jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:514)
        at jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:506)
        at java.io.ObjectStreamClass.getSerializableConstructor(ObjectStreamClass.java:1531)
        at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:509)
        at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:484)
        at java.security.AccessController.doPrivileged(AccessController.java:84)
        at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:484)
        at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:381)
        at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:225)
        at org.jboss.marshalling.reflect.SerializableClass.<init>(SerializableClass.java:85)
        at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:62)
        at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:59)
        at java.lang.ClassValue.get(JavaLangSubstitutions.java:602)
        at org.jboss.marshalling.reflect.SerializableClassRegistry.lookup(SerializableClassRegistry.java:83)
        at org.jboss.marshalling.river.ClassDescriptors.getSerializableClassDescriptor(ClassDescriptors.java:152)
        at org.jboss.marshalling.river.ClassDescriptors.<clinit>(ClassDescriptors.java:119)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
        at org.jboss.marshalling.river.RiverUnmarshaller.doReadClassDescriptor(RiverUnmarshaller.java:1253)
        at org.jboss.marshalling.river.RiverUnmarshaller.doReadClassDescriptor(RiverUnmarshaller.java:1049)
        at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1366)
        at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:283)
        at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:216)
        at org.jboss.marshalling.AbstractObjectInput.readObject(AbstractObjectInput.java:41)
        at org.jboss.remotingjmx.protocol.v2.ClientCommon$MarshalledResponseHandler.readValue(ClientCommon.java:224)
        at org.jboss.remotingjmx.protocol.v2.ClientCommon$BaseResponseHandler.handle(ClientCommon.java:176)
        at org.jboss.remotingjmx.protocol.v2.ClientCommon$MessageReceiver$1.run(ClientCommon.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)


```
```
 grep -Ri enumset src/main/resources/META-INF/
src/main/resources/META-INF/native-image_1/reflect-config.json:  "name":"java.util.EnumSet",
src/main/resources/META-INF/native-image_1/reflect-config.json:  "name":"java.util.EnumSet$SerializationProxy",
src/main/resources/META-INF/native-image/reflect-config.json:  "name":"java.util.EnumSet",
src/main/resources/META-INF/native-image/reflect-config.json:  "name":"java.util.EnumSet$SerializationProxy",
src/main/resources/META-INF/native-image/serialization-config.json:  "name":"java.util.EnumSet"
src/main/resources/META-INF/native-image/serialization-config.json:  "name":"java.util.EnumSet"
```

**Comment by olpaw** [comment]
Hi @warrenc5, have you also tried with:
```
[
  {
    "name":"java.util.AbstractMap",
    "customTargetConstructorClass":"java.lang.Object"
  }
]
```
for more info see `native-image --expert-options-detail SerializationConfigurationFiles`

**Comment by warrenc5** [comment]
@olpaw  Thanks for that - Just waiting for a _stable nightly_ dev build to test.

**Comment by olpaw** [comment]
> @olpaw Thanks for that - Just waiting for a _stable nightly_ dev build to test.

You can try with https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/21.1.0-dev-20210126_1929

**Comment by warrenc5** [comment]
I did a complete tear down rebuild of my project. Isolated the test case to the following.  

> openjdk 11.0.10 2021-01-19
> OpenJDK Runtime Environment GraalVM CE 21.1.0-dev (build 11.0.10+8-jvmci-21.0-b06)
> OpenJDK 64-Bit Server VM GraalVM CE 21.1.0-dev (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)

I generated the native-image with the mvn  -Prun-native profile.

https://github.com/warrenc5/jain-slee-js/blob/master/src/main/java/org/jboss/marshalling/reflect/TestThis.java

The InstanceNotFoundException I don't understand because the Super class is Throwable which implements serializable. Although I can see jboss marshaller going through all the super classes (maybe unnecessarily) and it finally confuses the svm core SerializationSupport.

Enum is also a suprise to me because it's super class is AbstractSet and stack trace is from java.io and jdk.internal.reflect up.

I'm still experimenting with the Substitutes. Learning about jdk internals. Any advice is really appreciated.

```
INF WORKS
com.oracle.svm.core.jdk.UnsupportedFeatureError: SerializationConstructorAccessor class not found for declaringClass: java.lang.Exception (targetConstructorClass: java.lang.Throwable). Usually adding java.lang.Exception to serialization-config.json fixes the problem.
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:87)
        at com.oracle.svm.reflect.serialize.SerializationSupport.getSerializationConstructorAccessor(SerializationSupport.java:132)
        at jdk.internal.reflect.MethodAccessorGenerator.generateSerializationConstructor(MethodAccessorGenerator.java:48)
        at jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:514)
        at jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:427)
        at sun.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:103)
        at org.jboss.marshalling.reflect.JDKSpecific.newConstructorForSerialization(JDKSpecific.java:48)
        at org.jboss.marshalling.reflect.SerializableClass.<init>(SerializableClass.java:79)
        at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:62)
        at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:59)
        at java.lang.ClassValue.get(JavaLangSubstitutions.java:602)
        at org.jboss.marshalling.reflect.SerializableClassRegistry.lookup(SerializableClassRegistry.java:83)
        at org.jboss.marshalling.reflect.SerializableClass.<init>(SerializableClass.java:76)
        at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:62)
        at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:59)
        at java.lang.ClassValue.get(JavaLangSubstitutions.java:602)
        at org.jboss.marshalling.reflect.SerializableClassRegistry.lookup(SerializableClassRegistry.java:83)
        at org.jboss.marshalling.reflect.SerializableClass.<init>(SerializableClass.java:76)
        at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:62)
        at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:59)
        at java.lang.ClassValue.get(JavaLangSubstitutions.java:602)
        at org.jboss.marshalling.reflect.SerializableClassRegistry.lookup(SerializableClassRegistry.java:83)
        at org.jboss.marshalling.reflect.SerializableClass.<init>(SerializableClass.java:76)
        at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:62)
        at org.jboss.marshalling.reflect.SerializableClassRegistry$1.computeValue(SerializableClassRegistry.java:59)
        at java.lang.ClassValue.get(JavaLangSubstitutions.java:602)
        at org.jboss.marshalling.reflect.SerializableClassRegistry.lookup(SerializableClassRegistry.java:83)
        at org.jboss.marshalling.reflect.TestThis.main(TestThis.java:24)
        at RunScript.main(RunScript.java:74)
AbstractSet WORKS
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: SerializationConstructorAccessor class not found for declaringClass: java.util.EnumSet (targetConstructorClass: java.util.AbstractSet). Usually adding java.util.EnumSet to serialization-config.json fixes the problem.
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:87)
        at com.oracle.svm.reflect.serialize.SerializationSupport.getSerializationConstructorAccessor(SerializationSupport.java:132)
        at jdk.internal.reflect.MethodAccessorGenerator.generateSerializationConstructor(MethodAccessorGenerator.java:48)
        at jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:514)
        at jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:506)
        at java.io.ObjectStreamClass.getSerializableConstructor(ObjectStreamClass.java:1531)
        at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:509)
        at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:484)
        at java.security.AccessController.doPrivileged(AccessController.java:84)
        at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:484)
        at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:381)
        at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:225)
        at org.jboss.marshalling.reflect.TestThis.main(TestThis.java:38)
        at RunScript.main(RunScript.java:74)
[ERROR] Command execution failed.

```

**Comment by warrenc5** [comment]
Ok - so serialization-config.json is just a allow/deny access list?
I was able to fix INF
with... (even though it's asking for declared class Throwable - which I also had customTargetConstructorClass
serialization-config.json 
```{
  "name":"java.lang.Exception"
  ,"customTargetConstructorClass":"java.lang.Object"
},```

**Comment by olpaw** [comment]
> I'm still experimenting with the Substitutes. Learning about jdk internals. Any advice is really appreciated.

You should not need any substitutions. Adding the right `serialization-config.json` should be enough to get it working. Note that the native-image-agent only supports `serialization-config.json` for regular serialization uses-cases (where ObjectOutputStream/ObjectInputStream are used to writeObject/readObject). Special cases that require `"customTargetConstructorClass"` are not detected by the agent. You have to manually provide configuration for those.
The error message emitted at image runtime helps you with finding what you need to add. E.g
```
com.oracle.svm.core.jdk.UnsupportedFeatureError: SerializationConstructorAccessor class not found for declaringClass: java.lang.Exception (targetConstructorClass: java.lang.Throwable). Usually adding java.lang.Exception to serialization-config.json fixes the problem.
```
tells you that you need to add
```
[
  {
    "name":"java.lang.Exception",
    "customTargetConstructorClass":"java.lang.Throwable"
  }
]
```

**Comment by olpaw** [comment]
> I generated the native-image META-INF with the mvn -Prun profile and build the graal with -Pgraal and then test with -Prun-native
> 
> https://github.com/warrenc5/jain-slee-js/blob/master/src/main/java/org/jboss/marshalling/reflect/TestThis.java

What's the best way to get the required jboss jar files for your test?

**Comment by warrenc5** [comment]
Thanks @oplaw

I've pushed a new pom with the jboss repos and tested

`mvn -s settings.xml -U compile`

I think the JBOSS libraries are kind of causing this because 

`ObjectStreamClass.lookup(javax.management.InstanceNotFoundException.class); `
Works

Where  as 
 `SerializableClass lookup = org.jboss.marshalling.reflect.SerializableClassRegistry.getInstance().lookup(javax.management.InstanceNotFoundException.class);`
Fails.

But EnumSet still fails on 

` ObjectStreamClass.lookup(EnumSet.class);`

So here are my findings. I think Jboss is hunting through jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization for every Superclass recursively up the hierarchy.

But I only worked that out from the constant errors from the native-image
Leading to the serialization-config below.

So maybe there is some sort of heuristic about what's allowed based on subclass


Actually I think I should just have to add 

```{
        "name": "javax.management.InstanceNotFoundException"
        ,  "customTargetConstructorClass": "java.lang.Object"
    }
```

To imply the following config - which works and I have commited.

```
   {
        "name": "javax.management.InstanceNotFoundException"
        ,
        "customTargetConstructorClass": "javax.management.OperationsException"
    }, 
    {
        "name": "javax.management.InstanceNotFoundException"
        ,
        "customTargetConstructorClass": "javax.management.JMException"
    }, 
    {
        "name": "javax.management.InstanceNotFoundException"
        ,
        "customTargetConstructorClass": "java.lang.Exception"
    }, {
        "name": "javax.management.InstanceNotFoundException"
        ,
        "customTargetConstructorClass": "java.lang.Throwable"
    }, {
        "name": "javax.management.InstanceNotFoundException"
        ,
        "customTargetConstructorClass": "java.lang.Object"
    },
 {
        "name": "javax.management.OperationsException"
        ,
        "customTargetConstructorClass": "java.lang.Throwable"
    },

{
        "name": "javax.management.OperationsException"
        ,
        "customTargetConstructorClass": "java.lang.Object"
    },

{
        "name": "javax.management.OperationsException"
        ,
        "customTargetConstructorClass": "java.lang.Exception"
    },

    {
        "name": "javax.management.OperationsException"
        ,
        "customTargetConstructorClass": "javax.management.JMException"
    },
    {
        "name": "javax.management.JMException"
        ,
        "customTargetConstructorClass": "java.lang.Object"
    },
    {
        "name": "javax.management.JMException"
        ,
        "customTargetConstructorClass": "java.lang.Throwable"
    },
    {
        "name": "javax.management.JMException"
        ,
        "customTargetConstructorClass": "java.lang.Exception"
    },
    {
        "name": "java.lang.Throwable"
        ,
        "customTargetConstructorClass": "java.lang.Object"
    },
```

**Comment by warrenc5** [comment]
I've also branched the project for easier change management :)

https://github.com/warrenc5/jain-slee-js/tree/feature/native

**Comment by warrenc5** [comment]
I guess I'm being presumptuous, but... If I can serialize a javax.management.InstanceNotFoundException then it follows that I can serialize a javax.management.JMException - so why do I need to explicitly declare it?

**Comment by olpaw** [comment]
> I guess I'm being presumptuous, but... If I can serialize a javax.management.InstanceNotFoundException then it follows that I can serialize a javax.management.JMException - so why do I need to explicitly declare it?

Serialization relies on runtime code-generation of a `ConstructorAccessor` for  a given pair of `Class<?> and Constructor<?>`. If your application makes direct use of the jdk-internal method
```
jdk.internal.reflect.ReflectionFactory#newConstructorForSerialization(Class<?>, Constructor<?>)
```
(like `org.jboss.marshalling.reflect` apparently does) then for native-image you must ensure that the possible `Class<?> Constructor<?>` pairs that might be used at runtime are known at image buildtime - hence the need to provide `"name"` **and** `"customTargetConstructorClass"` for such special cases.

Again, if serialization is used as intended (via ObjectOutputStream.writeObject/ObjectInputStream.readObject ) the additional `"customTargetConstructorClass"` is not needed (because then the `Constructor<?>` in the pair can be inferred) and the agent can be used to create a working `serialization-config.json`.

**Comment by warrenc5** [comment]
Thanks a lot, @oplaw your guidance has pointed me in the right direction. 

I have a working baseline serialization-config.json file as illustrated above, and pushed. 

Now I will follow your advice to see how I can best get the native agent to assist with generation. 

The first things I will try is to move jboss.reflect code to runtime and to put some calls into the Main java class.  

Because the entire point of this project is to move JMX operations into Javascript-land (For the jain-slee JMX library)  - I see how JS late/runtime binding is kinda conflicting with native early/compile time binding at a technical design level.  

Happy for you to close this. Thanks again.
