### ISSUE TITLE
Regression with Micronaut, security providers and X509

### ISSUE THREAD

**Issue by ilopmar** [oracle/graal#3157]
**Describe the issue**

The Micronaut test applications that use SSL/HTTPS are failing at runtime because something has changed in `master` branch related to security providers and algorithms. It seems that some `sun.security` and related classes were included before but not they are not now. 

Other applications that use Micronaut Security fail with errors like `No installed provider supports this key: javax.crypto.spec.SecretKeySpec`.

I don't know if this is a regression or we need to make some adjustment in our configuration to include them.

**Steps to reproduce the issue**

- `git clone https://github.com/micronaut-graal-tests/micronaut-basic-app`
- `cd micronaut-basic-app`
- `git checkout issue-security-providers`
- Use GraalVM compiled from master branch (currently 21.1.0-dev)
- `./build-native-image.sh`
- `./basic-app`
- `curl localhost:8080/bintray/packages-lowlevel`

That curl requests triggers a call using Micronaut HTTP client to Bintray API. The issue happens during initial SSL handshake. See error below.

**Describe GraalVM and your environment:**
 - GraalVM version: **Commit 3d12e199361a981b5c0a40ba613940dc3a44b188**
 - JDK major version: **8 and 11**
 - OS: **Linux Mint**
 - Architecture: **AMD64**

**More details**

```
12:12:34.903 [default-nioEventLoopGroup-1-3] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Failed to parse server certificates
javax.net.ssl.SSLHandshakeException: Failed to parse server certificates
	at sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:349)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:439)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1074)
	at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1061)
	at java.security.AccessController.doPrivileged(AccessController.java:147)
	at sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1008)
	at io.netty.handler.ssl.SslHandler.runAllDelegatedTasks(SslHandler.java:1557)
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1571)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1455)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1282)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1329)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.security.cert.CertificateException: X.509 not found
	at java.security.cert.CertificateFactory.getInstance(CertificateFactory.java:198)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:432)
	... 33 common frames omitted
Caused by: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: X.509, provider: SUN, class: sun.security.provider.X509Factory)
	at java.security.Provider$Service.newInstance(Provider.java:1905)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at java.security.cert.CertificateFactory.getInstance(CertificateFactory.java:193)
	... 34 common frames omitted
Caused by: java.lang.NoSuchMethodException: sun.security.provider.X509Factory.<init>()
	at java.lang.Class.getConstructor0(DynamicHub.java:3349)
	at java.lang.Class.getConstructor(DynamicHub.java:2151)
	at java.security.Provider.newInstanceUtil(Provider.java:153)
	at java.security.Provider$Service.newInstance(Provider.java:1894)
	... 37 common frames omitted
```

I've used the native agent to generate the reflect configuration and I've manually adjust it to include some missing classes after getting different errors in different tries/runs. Probably there are some classes that are not necessary (and others that are needed and I'm missing), but I'm not sure.

This is what I've tried: [reflect-config.json.txt](https://github.com/oracle/graal/files/5873007/reflect-config.json.txt)

With that configuration the error is:

```
javax.net.ssl.SSLException: Unsupported signature algorithm: rsa_pkcs1_sha256
	at sun.security.ssl.Alert.createSSLException(Alert.java:133)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
	at sun.security.ssl.ECDHServerKeyExchange$ECDHServerKeyExchangeMessage.<init>(ECDHServerKeyExchange.java:298)
	at sun.security.ssl.ECDHServerKeyExchange$ECDHServerKeyExchangeConsumer.consume(ECDHServerKeyExchange.java:527)
	at sun.security.ssl.ServerKeyExchange$ServerKeyExchangeConsumer.consume(ServerKeyExchange.java:111)
	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:377)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
	at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:968)
	at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:955)
	at java.security.AccessController.doPrivileged(AccessController.java:147)
	at sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:902)
	at io.netty.handler.ssl.SslHandler.runAllDelegatedTasks(SslHandler.java:1557)
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1571)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1455)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1282)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1329)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.security.InvalidKeyException: No installed provider supports this key: sun.security.rsa.RSAPublicKeyImpl
	at java.security.Signature$Delegate.chooseProvider(Signature.java:1261)
	at java.security.Signature$Delegate.engineInitVerify(Signature.java:1322)
	at java.security.Signature.initVerify(Signature.java:514)
	at java.security.Signature$1.initVerify(Signature.java:130)
	at sun.security.util.SignatureUtil.initVerifyWithParam(SignatureUtil.java:150)
	at sun.security.ssl.SignatureScheme.getVerifier(SignatureScheme.java:535)
	at sun.security.ssl.ECDHServerKeyExchange$ECDHServerKeyExchangeMessage.<init>(ECDHServerKeyExchange.java:294)
	... 34 common frames omitted
```

And I'm stuck in that.

**Comment by kkriske** [comment]
Ran into the same thing, adding `-H:+EnableAllSecurityServices` manually worked around the issue for me.

**Comment by ilopmar** [comment]
I've tried the solution proposed by @kkriske and it works for me in a few apps I've tried.

@oubidar-Abderrahim can you please confirm if that's the right fix to this issue or if it's a temporary workaround and you guys are going to fix something on GraalVM?

**Comment by oubidar-Abderrahim** [comment]
Sorry for the late response @ilopmar. Yes indeed, adding the `--enable-all-security-services` flag is the way to fix this issue.

By default, a native image is built with support for the `SecureRandom` and `MessageDigest` engines from the SUN provider. These are core security services needed by the VM itself. All the other Java security services (**`Signature`**, `Cipher`, `Mac`, `KeyPair`, `KeyGenerator`, `KeyFactory`, `KeyStore`, etc.,) must be enabled by adding the `--enable-all-security-services` option to the native-image command. The reason behind enabling only core security services by default is that you can start with a basic image and add more security services as you need them. This helps keep the overall image size small.

Note: the `--enable-all-security-services` option is enabled by default when `HTTPS` support is enabled.

**Comment by ilopmar** [comment]
@oubidar-Abderrahim We already have enabled `HTTPS`: https://github.com/micronaut-projects/micronaut-core/blob/4e35cd2e5eff534c8d6c9d82c115a97ee366a9e1/inject/src/main/resources/META-INF/native-image/io.micronaut/micronaut-inject/native-image.properties#L18 and that option has been there for 2 years now.
So, maybe the issue is that `--enable-all-security-services` is not not enabled automatically when using https. Can you please reopen the issue/confirm this?
Should we switch to `--enable-http` and `--enable-https` instead of using `-H:EnableURLProtocols=http,https`?

**Comment by oubidar-Abderrahim** [comment]
I guess the issue here is a deprecated

**Comment by oubidar-Abderrahim** [comment]
Let me check and get back to you

**Comment by olpaw** [comment]
> So, maybe the issue is that --enable-all-security-services is not not enabled automatically when using https.

@ilopmar I'm afraid I' to blame for this regression. I already have a fix. Should be on master by end of this week.
Sorry for the inconvenience.

**Comment by ilopmar** [comment]
Thanks @olpaw I'll test it once it's merged and I'll close this issue.

**Comment by olpaw** [comment]
@ilopmar the fix is on master.

**Comment by ilopmar** [comment]
Yeah, build back to green: https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/pipelines/251875019

Thank you!
