### ISSUE TITLE
iodine issue: External LLVMFunction pthread_atfork cannot be found

### ISSUE THREAD

**Issue by AlexeyMatskevich** [oracle/graal#3188]
```
RuntimeError: External LLVMFunction pthread_atfork cannot be found.
  <internal:core> core/kernel.rb:293:in `require_relative'
  /home/aleksei/.asdf/installs/ruby/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/iodine-0.7.43/lib/iodine.rb:6:in `<top (required)>'
  <internal:core> core/kernel.rb:234:in `gem_original_require'
  /home/aleksei/.asdf/installs/ruby/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/iodine-0.7.43/exe/iodine:4:in `<top (required)>'
  <internal:core> core/kernel.rb:401:in `load'
  <internal:core> core/kernel.rb:401:in `load'
  /home/aleksei/.asdf/installs/ruby/truffleruby+graalvm-20.3.0/bin/iodine:23:in `<top (required)>'
  <internal:core> core/kernel.rb:401:in `load'
  <internal:core> core/kernel.rb:401:in `load'

[ [ SubstrateSegfaultHandler caught a segfault. ] ]
```
To reproduce:
```
gem install iodine
iodine
```

**Comment by oubidar-Abderrahim** [comment]
Could you please provide more detailed steps to reproduce this issue? that would be helpful

**Comment by AlexeyMatskevich** [comment]
1. Install `rbenv`
2. Install `truffleruby+graalvm-20.3.0` from [ruby-build](https://github.com/rbenv/ruby-build/tree/master/) with `rbenv install truffleruby+graalvm-20.3.0`
3. Switch to `truffleruby` with `rbenv shell truffleruby+graalvm-20.3.0`
4. Check ruby version
```
ruby -v
truffleruby 20.3.0, like ruby 2.6.6, GraalVM CE Native [x86_64-linux]
```
5. Install iodine with `gem install iodine`
6. Run iodine with `iodine` or try to check iodine version with `iodine -v`
```
iodine -v
<internal:core> core/kernel.rb:293:in `require_relative': External LLVMFunction pthread_atfork cannot be found. (RuntimeError)
        from /home/alex/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/iodine-0.7.43/lib/iodine.rb:6:in `<top (required)>'
        from <internal:core> core/kernel.rb:234:in `gem_original_require'
        from /home/alex/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/alex/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/iodine-0.7.43/exe/iodine:4:in `<top (required)>'
        from <internal:core> core/kernel.rb:401:in `load'
        from <internal:core> core/kernel.rb:401:in `load'
        from /home/alex/.rbenv/versions/truffleruby+graalvm-20.3.0/bin/iodine:23:in `<main>'
```
[Get full backtrace](https://gist.github.com/AlexeyMatskevich/c28b67a1d88516515cb3b9159be5a335)

**Comment by oubidar-Abderrahim** [comment]
The issue is tracked internally on GR-29336

**Comment by oubidar-Abderrahim** [comment]
This is not planned

**Comment by oubidar-Abderrahim** [comment]
This is not planned
