### ISSUE TITLE
Incompatible change of initialization policy for java.net.NetworkInterface: trying to change RUN_TIME from the command line to RERUN for JDK native code support via JNI

### ISSUE THREAD

**Issue by StefanOltmann** [oracle/graal#3216]
**Describe the issue**

I try to build a native image a project that uses an `Inet4Address` class.

Using the `--initialize-at-run-time` option I included all traces to this class. Only one remains:

```
Error: Classes that should be initialized at run time got initialized during image building:
 java.net.Inet4Address the class was requested to be initialized at run time (from the command line). java.net.NetworkInterface caused initialization of this class with the following trace: 
	at java.net.Inet4Address.<clinit>(Inet4Address.java:98)
	at java.net.NetworkInterface.init(Unknown Source)
	at java.net.NetworkInterface.<clinit>(NetworkInterface.java:68)
```

But when I add `java.net.NetworkInterface` to the list I get this error:

```
Error: Incompatible change of initialization policy for java.net.NetworkInterface: trying to change RUN_TIME from the command line to RERUN for JDK native code support via JNI
com.oracle.svm.core.util.UserError$UserException: Incompatible change of initialization policy for java.net.NetworkInterface: trying to change RUN_TIME from the command line to RERUN for JDK native code support via JNI
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
```

I found similar reportings in https://github.com/oracle/graal/issues/2723 and https://github.com/oracle/graal/issues/1462 .
So I assume this may be a bug.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. **git clone --depth 1 https://github.com/StefanOltmann/smart-home-server**
2. **./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true**

**Describe GraalVM and your environment:**
 - GraalVM version: **20.3.1 (coming with a container bundled with Quarkus), but also tried 21.0.0.2**
 - JDK major version: **11** (11.0.10+8-jvmci-20.3-b09, Github Action)
 - OS: **Linux (GitHub Action)**
 - Architecture: **x64 I guess (GitHub Action)**

**Stack traces:**
```
Running Quarkus native-image plugin on GraalVM Version 20.3.1 (Java Version 11.0.10+8-jvmci-20.3-b09)
docker run -v /home/runner/work/smart-home-server/smart-home-server/build/smart-home-server-0.1-native-image-source-jar:/project:z --env LANG=C --user 1001:116 --rm quay.io/quarkus/ubi-quarkus-native-image:20.3.1-java11 -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Duser.language=en -J-Dfile.encoding=UTF-8 --initialize-at-run-time=java.net.Inet4Address,li.pitschmann.knx.core.utils.Networker,li.pitschmann.knx.core.net.HPAI,li.pitschmann.knx.core.config.CoreConfigs,li.pitschmann.knx.core.body.SearchRequestBody,li.pitschmann.knx.core.body.DescriptionRequestBody --trace-class-initialization=java.net.Inet4Address --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -jar smart-home-server-0.1-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services --no-server -H:-UseServiceLoaderFeature -H:+StackTrace smart-home-server-0.1-runner
[smart-home-server-0.1-runner:27]    classlist:   6,295.29 ms,  1.20 GB
[smart-home-server-0.1-runner:27]        (cap):     766.19 ms,  1.20 GB
[smart-home-server-0.1-runner:27]        setup:   2,735.83 ms,  1.20 GB
[smart-home-server-0.1-runner:27]     analysis:  22,742.13 ms,  1.69 GB
Error: Classes that should be initialized at run time got initialized during image building:
 java.net.Inet4Address the class was requested to be initialized at run time (from the command line). java.net.NetworkInterface caused initialization of this class with the following trace: 
	at java.net.Inet4Address.<clinit>(Inet4Address.java:98)
	at java.net.NetworkInterface.init(Unknown Source)
	at java.net.NetworkInterface.<clinit>(NetworkInterface.java:68)
```

```
Running Quarkus native-image plugin on GraalVM Version 20.3.1 (Java Version 11.0.10+8-jvmci-20.3-b09)
docker run -v /home/runner/work/smart-home-server/smart-home-server/build/smart-home-server-0.1-native-image-source-jar:/project:z --env LANG=C --user 1001:116 --rm quay.io/quarkus/ubi-quarkus-native-image:20.3.1-java11 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Duser.language=en -J-Dfile.encoding=UTF-8 --initialize-at-run-time=java.net.Inet4Address,li.pitschmann.knx.core.utils.Networker,li.pitschmann.knx.core.net.HPAI,li.pitschmann.knx.core.config.CoreConfigs,li.pitschmann.knx.core.body.SearchRequestBody,li.pitschmann.knx.core.body.DescriptionRequestBody,java.net.NetworkInterface --trace-class-initialization=java.net.Inet4Address --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -jar smart-home-server-0.1-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services --no-server -H:-UseServiceLoaderFeature -H:+StackTrace smart-home-server-0.1-runner
[smart-home-server-0.1-runner:25]    classlist:   6,794.00 ms,  0.96 GB
[smart-home-server-0.1-runner:25]        (cap):     794.09 ms,  0.96 GB
[smart-home-server-0.1-runner:25]        setup:   1,590.04 ms,  0.96 GB
Error: Incompatible change of initialization policy for java.net.NetworkInterface: trying to change RUN_TIME from the command line to RERUN for JDK native code support via JNI
com.oracle.svm.core.util.UserError$UserException: Incompatible change of initialization policy for java.net.NetworkInterface: trying to change RUN_TIME from the command line to RERUN for JDK native code support via JNI
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:99)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insert(ClassInitializationConfiguration.java:64)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.rerunInitialization(ConfigurableClassInitialization.java:379)
	at com.oracle.svm.core.jdk.JNIRegistrationUtil.rerunClassInit(JNIRegistrationUtil.java:73)
	at com.oracle.svm.hosted.jdk.JNIRegistrationJavaNet.duringSetup(JNIRegistrationJavaNet.java:56)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$12(NativeImageGenerator.java:880)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:880)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:554)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:469)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
```

**Comment by mcraj017** [comment]
@StefanOltmann Thanks for reporting the issue
We will check it out and get back to you

**Comment by mcraj017** [comment]
@StefanOltmann I tried the reproducer and got another exception:
```
Task :quarkusBuild FAILED
:quarkusBuild (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 2.269 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image
        at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:303)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
  Caused by: java.lang.RuntimeException: Image generation failed. Exit code: 125
        at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:570)
        at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:269)
        ... 10 more
```

**Comment by StefanOltmann** [comment]
@mcraj017 That exception is the result of the root exception I quoted above.

You should get the same exception somewhere in your stack trace.

Please see here the full stack trace:
https://github.com/StefanOltmann/smart-home-server/runs/1906383194?check_suite_focus=true

**Comment by StefanOltmann** [comment]
@mcraj017 Is there anything you need from me to reproduce the issue?

**Comment by mcraj017** [comment]
@StefanOltmann I am able to build the image successfully by removing the java.net classes from native-image arguments in application.properties
`quarkus.native.additional-build-args=--initialize-at-run-time=li.pitschmann.knx.core.utils.Networker\\,li.pitschmann.knx.core.net.HPAI\\,li.pitschmann.knx.core.config.CoreConfigs\\,li.pitschmann.knx.core.body.SearchRequestBody\\,li.pitschmann.knx.core.body.DescriptionRequestBody`

**log**

```

]
[smart-home-server-0.1-runner:27]    classlist:  15,388.70 ms,  0.94 GB
[smart-home-server-0.1-runner:27]        (cap):     617.63 ms,  0.94 GB
[smart-home-server-0.1-runner:27]        setup:   2,859.24 ms,  0.94 GB
14:21:55,436 INFO  [org.jbo.threads] JBoss Threads version 3.2.0.Final
[smart-home-server-0.1-runner:27]     (clinit):     927.77 ms,  2.63 GB
[smart-home-server-0.1-runner:27]   (typeflow):  38,141.99 ms,  2.63 GB
[smart-home-server-0.1-runner:27]    (objects):  30,649.72 ms,  2.63 GB
[smart-home-server-0.1-runner:27]   (features):   1,063.18 ms,  2.63 GB
[smart-home-server-0.1-runner:27]     analysis:  72,921.27 ms,  2.63 GB
[smart-home-server-0.1-runner:27]     universe:   4,055.18 ms,  3.17 GB
[smart-home-server-0.1-runner:27]      (parse):  16,391.63 ms,  4.03 GB
[smart-home-server-0.1-runner:27]     (inline):   7,566.04 ms,  3.83 GB
[smart-home-server-0.1-runner:27]    (compile):  60,213.91 ms,  3.86 GB
[smart-home-server-0.1-runner:27]      compile:  87,152.33 ms,  3.85 GB
[smart-home-server-0.1-runner:27]        image:   5,414.15 ms,  3.82 GB
[smart-home-server-0.1-runner:27]        write:   7,763.65 ms,  3.82 GB
[smart-home-server-0.1-runner:27]      [total]: 196,031.81 ms,  3.82 GB
objcopy executable not found in PATH. Debug symbols will not be separated from executable.
That will result in a larger native image with debug symbols embedded in it.

> Task :quarkusBuild
Quarkus augmentation completed in 209352ms
:quarkusBuild (Thread[Execution worker for ':',5,main]) completed. Took 3 mins 30.312 secs.
:assemble (Thread[Execution worker for ':',5,main]) started.

> Task :assemble
Skipping task ':assemble' as it has no actions.
:assemble (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:check (Thread[Execution worker for ':',5,main]) started.

> Task :check UP-TO-DATE
Skipping task ':check' as it has no actions.
:check (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:build (Thread[Execution worker for ':',5,main]) started.

> Task :build
Skipping task ':build' as it has no actions.
:build (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.

BUILD SUCCESSFUL in 3m 44s
7 actionable tasks: 7 executed
```

**Comment by StefanOltmann** [comment]
Ok, for some reason, now it works. Thank you.

**Comment by mcraj017** [comment]
great
