### ISSUE TITLE
native-image error building Kotlin code

### ISSUE THREAD

**Issue by kirillp** [oracle/graal#3243]
**Describe the issue**

GraalVM failed to compile some Kotlin generated code
Rendering the following errors:

Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing delightex.api.uibuilder.example.TodoKt$todoList$$inlined$vflow$lambda$3.invoke(delightex.api.uibuilder.builders.ChooseBuilder) 
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.NoClassDefFoundError: delightex/api/uibuilder/example/TodoKt$todoList$2$2

Full error log
https://gist.githubusercontent.com/kirillp/01d78f079c3253bffe872edd45baae73/raw/5b84a663a0bf0dd8aa03f5d7ef46690557b01f21/error.txt

The class file that cause the issue:
[TodoKt$todoList$inlined$vflow$lambda$3.zip](https://github.com/oracle/graal/files/6042332/TodoKt.todoList.inlined.vflow.lambda.3.zip)

Class file disassembly:
[TodoKt$todoList$inlined$vflow$lambda$3.dump.txt](https://github.com/oracle/graal/files/6042333/TodoKt.todoList.inlined.vflow.lambda.3.dump.txt)

All classes
[classes.zip](https://github.com/oracle/graal/files/6042477/classes.zip)

**Steps to reproduce the issue**

Currently we are looking into a simple way to reproduce. 
It seems that Kotlin functions defined in another function causing the problem.

**Describe GraalVM and your environment:**
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)

**Comment by kirillp** [comment]
If I enable Dashboard file like this
```
-H:DashboardDump=dashboard
-H:+DashboardAll
-H:+DashboardJson

```

then error is different

Fatal error:java.lang.NullPointerException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:370)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:529)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:561)
Caused by: java.lang.NullPointerException
	at com.oracle.svm.hosted.dashboard.PointsToJsonObject.connectFlowToEnclosingMethod(PointsToJsonObject.java:742)
	at com.oracle.svm.hosted.dashboard.PointsToJsonObject.connectFlowsToEnclosingMethods(PointsToJsonObject.java:713)
	at com.oracle.svm.hosted.dashboard.PointsToJsonObject.build(PointsToJsonObject.java:495)
	at com.oracle.svm.hosted.dashboard.ToJson$JsonObject.dump(ToJson.java:332)
	at com.oracle.svm.hosted.dashboard.ToJson.putProperty(ToJson.java:133)
	at com.oracle.svm.hosted.dashboard.ToJson.put(ToJson.java:124)
	at com.oracle.svm.hosted.dashboard.DashboardDumpFeature.lambda$onAnalysisExit$2(DashboardDumpFeature.java:125)
	at com.oracle.graal.pointsto.reports.ReportUtils.reportImpl(ReportUtils.java:153)
	at com.oracle.graal.pointsto.reports.ReportUtils.report(ReportUtils.java:144)
	at com.oracle.svm.hosted.dashboard.DashboardDumpFeature.onAnalysisExit(DashboardDumpFeature.java:119)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$10(NativeImageGenerator.java:779)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:779)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:563)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by kirillp** [comment]
JVM executes the code just fine.
Also TeaVM compiles it as well.

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this issue. Please if you do find a simpler way to reproduce this, it would be much appreciated to share it. If not, Could we have the reproducing code, with the steps to reproduce, in a Github repo that we can just clone? this should be easier to test for everyone and also will go accordingly to security standards. Thanks.

**Comment by zvozin** [comment]
It appears to be the naming conventions that Kotlin plays loose with. E.g.:
```
warning: unknown locality of class Lorg/http4k/lens/LensInjector$of$1;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lorg/http4k/lens/LensInjector$of$1; which is not following the naming convention.
warning: unknown locality of class Lkotlin/coroutines/CoroutineContext$plus$1;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lkotlin/coroutines/CoroutineContext$plus$1; which is not following the naming convention.
warning: unknown locality of class Larrow/typeclasses/MonadFx$monad$wrapReturn$1;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Larrow/typeclasses/MonadFx$monad$wrapReturn$1; which is not following the naming convention.
warning: unknown locality of class Larrow/typeclasses/MonadThrowFx$monadThrow$wrapReturn$1;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Larrow/typeclasses/MonadThrowFx$monadThrow$wrapReturn$1; which is not following the naming convention.
```

To reproduce, simply add `org.jetbrains.kotlinx:kotlinx-coroutines-core:{{your-kotlin-version}}` to a project and instantiate a CoroutineContext.

`native-images` appears to not be friendly to multi-$ class names. My builds are failing with errors like:
```
java.lang.NoClassDefFoundError: com/medsbyme/public/pricesearch/ByIPAndPartialNameKt$ByIpAndPartialName$1$1
```
Each time it's a different class name, seemingly random, but always ending on `$1$1` (`$____[$_____][...]` is how Kotlin encodes nested lambdas).

**Comment by kirillp** [comment]
Try new kotlin release with -ir compiler flag, it might help.
https://blog.jetbrains.com/kotlin/2021/02/the-jvm-backend-is-in-beta-let-s-make-it-stable-together/

**Comment by zvozin** [comment]
@kirillp it does, actually. `native-image` still craps out in a million different ways and requires a fantastically long list of exclusions, but the new JVM IR appears to solve the lambda naming problem.

**Comment by shelajev** [comment]
@zvozin can you please create an example to reproduce this?

**Comment by zvozin** [comment]
My comment 2 above has instructions. Note that the problem appears to go away with the Kotlin 1.5 IR, which compiles lambdas to dynamic invocations rather than anonymous inner classes.

**Comment by kirillp** [comment]
@zvozin 
Hi Alex, I have Kotlin project setup for GraalVM maven build
Can you suggest code that I can put there to reproduce ?
Our project is very big, I can not over-simplify it to send a simple reproducer

**Comment by kirillp** [comment]
reproducer https://github.com/oracle/graal/issues/3276

**Comment by cstancu** [comment]
Kotlin 1.5 IR seems to have fixed the issue.
