### ISSUE TITLE
Native image compilation sometimes stalls: deadlock?

### ISSUE THREAD

**Issue by borkdude** [oracle/graal#3251]
**Describe the issue**

Native image compilation sometimes stalls during the build of this project:

https://github.com/borkdude/tools-deps-native-experiment

Maybe a deadlock issue?

**Steps to reproduce the issue**
Please include both build steps as well as run steps

Check out [the repo](https://github.com/borkdude/tools-deps-native-experiment) at commit `9b13099542d1fd682b96138b8e7baadc20eeea92`:

Follow instructions here: https://github.com/borkdude/tools-deps-native-experiment/tree/9b13099542d1fd682b96138b8e7baadc20eeea92#build

Let me know if something is not clear.

**Describe GraalVM and your environment:**
 - GraalVM version 21.0.0 CE
 - JDK major version: 11
 - OS: macOS Mojave (also happens on Linux on CI)
 - Architecture: amd64
```

**Comment by borkdude** [comment]
Today at the GraalVM workshop someone pointed out issue #2869: not sure if that's related, but could be?

**Comment by thomaswue** [comment]
Thanks for the report! I don't think this can be related to #2869, because the way we use the compiler for creating the image is so different. During which part of the build process does it deadlock / can you maybe paste a console output?

**Comment by dougxc** [comment]
Also, a dump of all stacks (by sending SIGQUIT to the Native Image process) would be helpful.

**Comment by borkdude** [comment]
This happens after the setup phase:

```
[tools-deps-native:20554] setup: 2,391.24 ms, 0.93 GB
``` 

Here is the thread dump.

[thread_dump.txt](https://github.com/oracle/graal/files/6076317/thread_dump.txt)

**Comment by dougxc** [comment]
This looks related to https://github.com/oracle/graal/issues/673 (/cc @peter-hofer).
Also, I noticed that a couple of threads are blocked in JNA class initializers:
```
"ForkJoinPool-4-worker-27" #48 daemon prio=5 os_prio=31 cpu=136.45ms elapsed=99.95s tid=0x00007fdbc6a70000 nid=0x6d07 in Object.wait()  [0x0000700012625000]
   java.lang.Thread.State: RUNNABLE
	at com.sun.jna.Native.initIDs(Native Method)
	at com.sun.jna.Native.<clinit>(Native.java:139)
	at com.sun.jna.NativeLong.<clinit>(NativeLong.java:23)
	at com.sun.jna.platform.win32.WinError.<clinit>(WinError.java:24247)
	at jdk.internal.misc.Unsafe.ensureClassInitialized0(java.base@11.0.10/Native Method)
	at jdk.internal.misc.Unsafe.ensureClassInitialized(java.base@11.0.10/Unsafe.java:1042)
	at sun.misc.Unsafe.ensureClassInitialized(jdk.unsupported@11.0.10/Unsafe.java:698)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.ensureClassInitialized(ConfigurableClassInitialization.java:174)
```
and:
```
"ForkJoinPool-4-worker-31" #50 daemon prio=5 os_prio=31 cpu=128.72ms elapsed=99.94s tid=0x00007fdb6601b000 nid=0x6107 in Object.wait()  [0x0000700013a2b000]
   java.lang.Thread.State: RUNNABLE
	at com.sun.jna.Pointer.<clinit>(Pointer.java:41)
	at com.sun.jna.platform.win32.WinBase.<clinit>(WinBase.java:35)
	at jdk.internal.misc.Unsafe.ensureClassInitialized0(java.base@11.0.10/Native Method)
	at jdk.internal.misc.Unsafe.ensureClassInitialized(java.base@11.0.10/Unsafe.java:1042)
	at sun.misc.Unsafe.ensureClassInitialized(jdk.unsupported@11.0.10/Unsafe.java:698)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.ensureClassInitialized(ConfigurableClassInitialization.java:174)
```
It could be that there's racy logic in this class initializers that causes deadlock when class initialization is triggered by Native Image.

**Comment by borkdude** [comment]
One library I'm using in this project was using JSch but is now just shelling out to git, which is easier on GraalVM.

To reproduce the problem reported above:

Check out [the repo](https://github.com/borkdude/tools-deps-native-experiment) at commit `9b13099542d1fd682b96138b8e7baadc20eeea92`:

Follow instructions here: https://github.com/borkdude/tools-deps-native-experiment/tree/9b13099542d1fd682b96138b8e7baadc20eeea92#build.

**Comment by christianwimmer** [comment]
Looks like a bug in JNA. When class initializer have cyclic dependencies, then the multi-threaded class initialization that native image is doing is exposing such bugs (which can occur of course in a "normal" Java run on the Java HotSpot VM too).

Not initializing JNA classes at image build time (which is the default anyway) sounds like the easiest solution. Initializing all classes at image build time when you do not know what these class initializers are doing is a bad idea.

**Comment by borkdude** [comment]
@christianwimmer Thanks for looking into it. Note that in a Clojure-based GraalVM-native CLI we usually do not have the choice of initializing everything at runtime and when a Clojure library uses JNA classes, these will also be initialized at build time, unless some patching is applied.

**Comment by thomaswue** [comment]
Is that because all Clojure runtime libraries are initialized at build time and therefore also all their dependencies?

**Comment by borkdude** [comment]
@thomaswue In short yes. 

Smallest repro possible, a program which prints CLI args. This requires Java and the Clojure CLI (https://clojure.org/guides/getting_started).

```
mkdir -p src
```

src/mymain.clj
``` clojure
(ns mymain
  (:gen-class))

(defn -main [& args]
  (println :args args))
```

Compile to bytecode:
```
mkdir -p classes
clojure -M -e "(compile 'mymain)"
```

Test:
```
$ java -cp classes:$(clojure -Spath) mymain 1 2 3
:args (1 2 3)
```

Compile with native-image:
```
$GRAALVM_HOME/bin/native-image --no-server --no-fallback -cp classes:$(clojure -Spath) mymain
```

Running it gives:
```
$ ./mymain 1 2 3
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:315)
	at clojure.lang.Namespace.<init>(Namespace.java:34)
	at clojure.lang.Namespace.findOrCreate(Namespace.java:176)
	at clojure.lang.Var.internPrivate(Var.java:156)
	at mymain.<clinit>(Unknown Source)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
Caused by: java.io.FileNotFoundException: Could not locate clojure/core__init.class, clojure/core.clj or clojure/core.cljc on classpath.
	at clojure.lang.RT.load(RT.java:462)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.lang.RT.<clinit>(RT.java:338)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
	... 6 more
```

With ` --initialize-at-build-time` it works like expected.

Trying to initialize `clojure.core__init` at runtime:

```
$ $GRAALVM_HOME/bin/native-image --no-server --no-fallback --initialize-at-build-time=clojure.core__init -cp classes:$(clojure -Spath) mymain
[mymain:70423]    classlist:     940.29 ms,  0.96 GB
[mymain:70423]        (cap):     819.60 ms,  0.96 GB
[mymain:70423]        setup:   2,121.37 ms,  0.96 GB
To see how the classes got initialized, use --trace-class-initialization=clojure.lang.Var,clojure.lang.RT,clojure.lang.PersistentList$EmptyList,clojure.lang.Compiler,clojure.lang.Reflector
[mymain:70423]     analysis:   4,746.25 ms,  1.20 GB
Error: Classes that should be initialized at run time got initialized during image building:
 clojure.lang.Var was unintentionally initialized at build time. To see why clojure.lang.Var got initialized use --trace-class-initialization=clojure.lang.Var
clojure.lang.RT was unintentionally initialized at build time. To see why clojure.lang.RT got initialized use --trace-class-initialization=clojure.lang.RT
clojure.lang.PersistentList$EmptyList was unintentionally initialized at build time. To see why clojure.lang.PersistentList$EmptyList got initialized use --trace-class-initialization=clojure.lang.PersistentList$EmptyList
clojure.lang.Compiler was unintentionally initialized at build time. To see why clojure.lang.Compiler got initialized use --trace-class-initialization=clojure.lang.Compiler
clojure.lang.Reflector was unintentionally initialized at build time. To see why clojure.lang.Reflector got initialized use --trace-class-initialization=clojure.lang.Reflector
```

Initializing  the entire `clojure` package:
```
$ GRAALVM_HOME/bin/native-image --no-server --no-fallback --initialize-at-build-time=clojure -cp classes:$(clojure -Spath) mymain
```

```
$ ./mymain 1 2 3
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:315)
Caused by: java.io.FileNotFoundException: Could not locate clojure/core/server__init.class, clojure/core/server.clj or clojure/core/server.cljc on classpath.
	at clojure.lang.RT.load(RT.java:462)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6839.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6780.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at clojure.core$require.doInvoke(core.clj:6007)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:384)
	at clojure.lang.RT.doInit(RT.java:491)
	at clojure.lang.RT.init(RT.java:467)
	at clojure.lang.Util.loadWithClass(Util.java:248)
	at mymain.<clinit>(Unknown Source)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
```

```
$ $GRAALVM_HOME/bin/native-image --no-server --no-fallback --initialize-at-build-time=clojure --initialize-at-build-time=clojure.core.server__init -H:+ReportExceptionStackTraces -cp classes:$(clojure -Spath) mymain
[mymain:80135]    classlist:     884.11 ms,  0.96 GB
[mymain:80135]        setup:     188.39 ms,  0.96 GB
Error: Class initialization of clojure.core.server__init failed. Use the option --initialize-at-run-time=clojure.core.server__init to explicitly request delayed initialization of this class.
com.oracle.svm.core.util.UserError$UserException: Class initialization of clojure.core.server__init failed. Use the option --initialize-at-run-time=clojure.core.server__init to explicitly request delayed initialization of this class.
	at com.oracle.svm.core.util.UserError.abort(UserError.java:82)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.reportInitializationError(ConfigurableClassInitialization.java:211)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.ensureClassInitialized(ConfigurableClassInitialization.java:192)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.forceInitializeHosted(ConfigurableClassInitialization.java:487)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.initializeAtBuildTime(ConfigurableClassInitialization.java:418)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.initializeAtBuildTime(ConfigurableClassInitialization.java:244)
	at com.oracle.svm.hosted.classinitialization.InitKind.lambda$stringConsumer$2(InitKind.java:71)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.lambda$processClassInitializationOptions$1(ClassInitializationFeature.java:152)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.processClassInitializationOptions(ClassInitializationFeature.java:142)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:867)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:580)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:495)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
	at jdk.unsupported/sun.misc.Unsafe.ensureClassInitialized(Unsafe.java:698)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.ensureClassInitialized(ConfigurableClassInitialization.java:176)
	... 17 more
Caused by: java.lang.IllegalStateException: Can't change/establish root binding of: *warn-on-reflection* with set
	at clojure.lang.Var.set(Var.java:226)
	at clojure.core.server__init.load(Unknown Source)
	at clojure.core.server__init.<clinit>(Unknown Source)
	... 21 more
Error: Image build request failed with exit status 1
``` 

I think I may actually have discovered a new issue why this isn't possible.

**Comment by christianwimmer** [comment]
One workaround you can do for class initialization deadlocks when you are already relying on the native image `Feature` API: in the `Feature.beforeAnalysis` method, you can manually trigger the class initialization of one of the affected classes. At this point, you are still single threaded. I used this for example recently to work around a JDK class initialization deadlock: https://github.com/oracle/graal/commit/2c6bf3c4fe290c8ab37e903377576618829d1ee3
