### ISSUE TITLE
Compilation fails with NoSuchFieldError: InliningCutoffCountPenalty

### ISSUE THREAD

**Issue by rpofuk** [oracle/graal#3265]
**Compilation broken**
```
ERROR! Fatal error:java.lang.NoSuchFieldError: InliningCutoffCountPenalty
 	at org.graalvm.compiler.truffle.compiler.TruffleCompilerOptions.<clinit>(TruffleCompilerOptions.java:255)
  	at org.graalvm.compiler.truffle.compiler.TruffleCompilerOptions_OptionDescriptors.get(TruffleCompilerOptions_OptionDescriptors.java:17)
  	at org.graalvm.compiler.truffle.compiler.TruffleCompilerOptions_OptionDescriptors$1.next(TruffleCompilerOptions_OptionDescriptors.java:282)
 	at org.graalvm.compiler.truffle.compiler.TruffleCompilerOptions_OptionDescriptors$1.next(TruffleCompilerOptions_OptionDescriptors.java:273)
 	at com.oracle.svm.hosted.option.HostedOptionParser.collectOptions(HostedOptionParser.java:78)
 	at com.oracle.svm.hosted.option.HostedOptionParser.<init>(HostedOptionParser.java:62)
 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:258)
 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:529)
 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
 	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:561)

```

I dont even know where to start checking. Where is source code for this classes? TruffleCompilerOptions, InliningCutoffCountPenalty

I'm compiling on Ubuntu 20.04 using GraalVM 20.0.3.

**Comment by SergejIsbrecht** [comment]
Which version of native-image are you using? It seems that there are some dependencies in your runtime-classpath, which are incompatible. It seems that the current master does not contain a class named `TruffleCompilerOptions`, but your native-image thinks it does. 

I would try using a native-image, which matches GraalVM 20.0.3

**Comment by rpofuk** [comment]
Thank you!

**Comment by dieu** [comment]
Hello, 

What's a solution for this issue actually? 

```
Fatal error:java.lang.NoSuchFieldError: InliningCutoffCountPenalty
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerOptions.<clinit>(TruffleCompilerOptions.java:255)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerOptions_OptionDescriptors.get(TruffleCompilerOptions_OptionDescriptors.java:17)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerOptions_OptionDescriptors$1.next(TruffleCompilerOptions_OptionDescriptors.java:282)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerOptions_OptionDescriptors$1.next(TruffleCompilerOptions_OptionDescriptors.java:273)
	at com.oracle.svm.hosted.option.HostedOptionParser.collectOptions(HostedOptionParser.java:78)
	at com.oracle.svm.hosted.option.HostedOptionParser.<init>(HostedOptionParser.java:62)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:258)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:529)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:561)
```

```
native-image --version
GraalVM Version 21.0.0.2 (Java Version 11.0.10+8-jvmci-21.0-b06)
```
