### ISSUE TITLE
-H:+PrintPointsToStatistics fails

### ISSUE THREAD

**Issue by ziyilin** [oracle/graal#3267]
**Describe the issue**
`-H:+PrintPointsToStatistics` option fails the build with NullPointerException and multi-threading issues. A PR is proposed to fix this issue: https://github.com/oracle/graal/pull/3266

**Steps to reproduce the issue**
1.  Simply run `$GRAALVM_HOME/bin/native-image -H:+PrintPointsToStatistics HelloWorld` and fails with message:
```
Fatal error:java.lang.NullPointerException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
        at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:499)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:370)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:531)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:568)
Caused by: java.lang.NullPointerException
        at com.oracle.graal.pointsto.typestate.PointsToStats.asString(PointsToStats.java:589)
        at com.oracle.graal.pointsto.typestate.PointsToStats.lambda$reportTypeFlowStats$4(PointsToStats.java:325)
        at java.base/java.util.concurrent.ConcurrentHashMap$EntrySpliterator.forEachRemaining(ConcurrentHashMap.java:3645)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at com.oracle.graal.pointsto.typestate.PointsToStats.reportTypeFlowStats(PointsToStats.java:320)
        at com.oracle.graal.pointsto.typestate.PointsToStats.doReport(PointsToStats.java:133)
        at com.oracle.graal.pointsto.typestate.PointsToStats.report(PointsToStats.java:118)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:818)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:575)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:495)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
After fix this problem, run `$GRAALVM_HOME/bin/native-image -H:+PrintPointsToStatistics HelloWorld` again will see the thread safety issue:
```
Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing sun.util.locale.provider.BreakIteratorProviderImpl.isSupportedLocale(java.util.Locale)
Parsing context:
        parsing sun.util.locale.provider.LocaleProviderAdapter.findAdapter(LocaleProviderAdapter.java:283)
        parsing sun.util.locale.provider.LocaleProviderAdapter.getAdapter(LocaleProviderAdapter.java:264)
        parsing java.text.BreakIterator.createBreakInstance(BreakIterator.java:553)
        parsing java.text.BreakIterator.getBreakInstance(BreakIterator.java:545)
        parsing java.text.BreakIterator.getWordInstance(BreakIterator.java:460)
        parsing java.lang.ConditionalSpecialCasing.isFinalCased(ConditionalSpecialCasing.java:205)
        parsing java.lang.ConditionalSpecialCasing.isConditionMet(ConditionalSpecialCasing.java:175)
        parsing java.lang.ConditionalSpecialCasing.lookUpTable(ConditionalSpecialCasing.java:160)
        parsing java.lang.ConditionalSpecialCasing.toLowerCaseCharArray(ConditionalSpecialCasing.java:137)
        parsing java.lang.StringUTF16.toLowerCaseEx(StringUTF16.java:721)
        parsing java.lang.StringUTF16.toLowerCase(StringUTF16.java:677)
        parsing java.lang.String.toLowerCase(String.java:2504)
        parsing java.lang.String.toLowerCase(String.java:2527)
        parsing com.oracle.svm.core.option.SubstrateOptionsParser.parseLong(SubstrateOptionsParser.java:490)
        parsing com.oracle.svm.core.option.XOptions.parseFromValueString(XOptions.java:183)
        parsing com.oracle.svm.core.option.XOptions.parseWithNameAndPrefix(XOptions.java:175)
        parsing com.oracle.svm.core.option.XOptions.parse(XOptions.java:149)
        parsing com.oracle.svm.core.option.RuntimeOptionParser.parseAndConsumeAllOptions(RuntimeOptionParser.java:80)
        parsing com.oracle.svm.core.graal.snippets.CEntryPointSnippets.initializeIsolate(CEntryPointSnippets.java:279)

        at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:331)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureTypeFlowCreated(MethodTypeFlow.java:302)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
        at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:227)
        at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:470)
        at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:542)
        at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:560)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 71141 out of bounds for length 71140
        at java.base/java.util.ArrayList.add(ArrayList.java:487)
        at java.base/java.util.ArrayList.add(ArrayList.java:499)
        at com.oracle.graal.pointsto.typestate.PointsToStats.registerTypeFlowBuilder(PointsToStats.java:149)
        at com.oracle.graal.pointsto.flow.builder.TypeFlowBuilder.create(TypeFlowBuilder.java:50)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:317)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:313)
```

**Describe GraalVM and your environment:**
 - 097b75d8ab8fca80470b1b6169c1a0143b65366f
 - JDK major version: **11**
 - OS: **[e.g. macOS Catalina]**
 - Architecture: **[e.g.: AMD64]**

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
    PASTE YOUR LOG/STACK TRACE HERE
```

**Comment by mcraj017** [comment]
@ziyilin Thanks for reporting the issue
we will take a look and get back to you
