### ISSUE TITLE
NoClassDefFoundError on synchronized(Class) block when class is compiled with 1.3 target

### ISSUE THREAD

**Issue by nemecec** [oracle/graal#3274]
**Describe the issue**
Given a simple test class:
```java
public class Test {

  public static void main(String[] args) {
    synchronized (Test.class) {
      System.out.println("Test");
    }
  }

}
```
Compiled with JDK 1.8: `javac -target 1.3 -source 1.3 Test.java`
Converted to native image with GraalVM 21.0.0.2 (JDK 11): `native-image --install-exit-handlers --no-fallback Test`
When ran: `./test`
It fails with:
```
Exception in thread "main" java.lang.NoClassDefFoundError: Test
	at Test.class$(Test.java:4)
	at Test.main(Test.java:4)
```

**Describe GraalVM and your environment:**
 - GraalVM version: **21.0.0.2 (Java Version 11.0.10+8-jvmci-21.0-b06)**
 - JDK major version: **11**
 - OS: **macOS Big Sur 11.1**
 - Architecture: **x86**

**More details**
Output when building the image without `--no-fallback` flag:
```
$ native-image --install-exit-handlers Test
[test:52303]    classlist:   3,931.20 ms,  0.96 GB
[test:52303]        (cap):   4,249.00 ms,  0.96 GB
[test:52303]        setup:   9,199.76 ms,  0.96 GB
[test:52303]     (clinit):     392.57 ms,  1.19 GB
[test:52303]   (typeflow):  19,524.42 ms,  1.19 GB
[test:52303]    (objects):   8,628.62 ms,  1.19 GB
[test:52303]   (features):     872.15 ms,  1.19 GB
[test:52303]     analysis:  29,911.54 ms,  1.19 GB
[test:52303]     universe:     874.37 ms,  1.68 GB
Warning: Reflection method java.lang.Class.forName invoked at Test.class$(Test.java:22)
Warning: Aborting stand-alone image build due to reflection use without configuration.
Warning: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
[test:52334]    classlist:   2,604.07 ms,  0.96 GB
[test:52334]        (cap):   3,027.71 ms,  0.96 GB
[test:52334]        setup:   6,572.10 ms,  0.96 GB
[test:52334]     (clinit):     406.74 ms,  1.71 GB
[test:52334]   (typeflow):  19,681.57 ms,  1.71 GB
[test:52334]    (objects):   9,914.65 ms,  1.71 GB
[test:52334]   (features):     462.96 ms,  1.71 GB
[test:52334]     analysis:  30,898.53 ms,  1.71 GB
[test:52334]     universe:     927.15 ms,  1.71 GB
[test:52334]      (parse):   6,698.35 ms,  1.71 GB
[test:52334]     (inline):   3,657.74 ms,  1.71 GB
[test:52334]    (compile):  37,931.47 ms,  2.34 GB
[test:52334]      compile:  49,404.58 ms,  2.34 GB
[test:52334]        image:   2,321.45 ms,  2.34 GB
[test:52334]        write:   1,891.04 ms,  2.34 GB
[test:52334]      [total]:  95,003.34 ms,  2.34 GB
Warning: Image 'test' is a fallback image that requires a JDK for execution (use --no-fallback to suppress fallback image generation and to print more detailed information why a fallback image was necessary).
```

Output when building the image with `--native-image-info` and  `--verbose` flags:
```
$ native-image --install-exit-handlers --no-fallback --native-image-info --verbose Test
Executing [
/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0.2/Contents/Home/bin/java \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.site=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.stack=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.common=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.sparc=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.runtime=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.services=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.sparc=ALL-UNNAMED \
--add-exports=org.graalvm.truffle/com.oracle.truffle.api=ALL-UNNAMED \
--add-opens=jdk.internal.vm.compiler/org.graalvm.compiler.debug=ALL-UNNAMED \
--add-opens=jdk.internal.vm.compiler/org.graalvm.compiler.nodes=ALL-UNNAMED \
--add-opens=jdk.unsupported/sun.reflect=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.module=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.ref=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.reflect=ALL-UNNAMED \
--add-opens=java.base/java.io=ALL-UNNAMED \
--add-opens=java.base/java.lang=ALL-UNNAMED \
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED \
--add-opens=java.base/java.lang.invoke=ALL-UNNAMED \
--add-opens=java.base/java.lang.ref=ALL-UNNAMED \
--add-opens=java.base/java.net=ALL-UNNAMED \
--add-opens=java.base/java.nio=ALL-UNNAMED \
--add-opens=java.base/java.nio.file=ALL-UNNAMED \
--add-opens=java.base/java.security=ALL-UNNAMED \
--add-opens=java.base/javax.crypto=ALL-UNNAMED \
--add-opens=java.base/java.util=ALL-UNNAMED \
--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED \
--add-opens=java.base/sun.security.x509=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.logger=ALL-UNNAMED \
--add-opens=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED \
--add-opens=org.graalvm.sdk/org.graalvm.polyglot=ALL-UNNAMED \
--add-opens=org.graalvm.truffle/com.oracle.truffle.polyglot=ALL-UNNAMED \
--add-opens=org.graalvm.truffle/com.oracle.truffle.api.impl=ALL-UNNAMED \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx13743895344 \
-Duser.country=US \
-Duser.language=en \
-Djava.awt.headless=true \
-Dorg.graalvm.version=21.0.0.2 \
-Dorg.graalvm.config= \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
--module-path \
/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0.2/Contents/Home/lib/truffle/truffle-api.jar \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-javaagent:/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0.2/Contents/Home/lib/svm/builder/svm.jar \
-cp \
/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0.2/Contents/Home/lib/svm/builder/llvm-wrapper-shadowed.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0.2/Contents/Home/lib/svm/builder/svm.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0.2/Contents/Home/lib/svm/builder/objectfile.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0.2/Contents/Home/lib/svm/builder/llvm-platform-specific-shadowed.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0.2/Contents/Home/lib/svm/builder/javacpp-shadowed.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0.2/Contents/Home/lib/svm/builder/svm-llvm.jar:/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0.2/Contents/Home/lib/svm/builder/pointsto.jar \
'com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus' \
-imagecp \
/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0.2/Contents/Home/lib/svm/library-support.jar:/Users/neeme/Workspaces/sympower/sympower-controller/raspi \
-H:Path=/Users/neeme/Workspaces/sympower/sympower-controller/raspi \
-H:+InstallExitHandlers \
-H:FallbackThreshold=0 \
-H:+DumpTargetInfo \
-H:CLibraryPath=/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0.2/Contents/Home/lib/svm/clibraries/darwin-amd64 \
-H:Class=Test \
-H:Name=test \

]
[test:52702]    classlist:   3,431.34 ms,  0.96 GB
[test:52702]        (cap):   3,736.88 ms,  0.96 GB
[test:52702]        setup:   6,739.61 ms,  0.96 GB
# Building image for target platform: org.graalvm.nativeimage.Platform$DARWIN_AMD64
# Using native toolchain:
#   Name: LLVM (clang)
#   Vendor: apple
#   Version: 11.0.0
#   Target architecture: x86_64
#   Path: /usr/bin/cc
# Using CLibrary: com.oracle.svm.core.c.libc.NoLibC
[test:52702]     (clinit):     456.32 ms,  1.22 GB
# Static libraries:
#   ../../../../../../Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0.2/Contents/Home/lib/svm/clibraries/darwin-amd64/liblibchelper.a
#   ../../../../../../Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0.2/Contents/Home/lib/static/darwin-amd64/libnet.a
#   ../../../../../../Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0.2/Contents/Home/lib/svm/clibraries/darwin-amd64/libdarwin.a
#   ../../../../../../Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0.2/Contents/Home/lib/static/darwin-amd64/libnio.a
#   ../../../../../../Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0.2/Contents/Home/lib/static/darwin-amd64/libjava.a
#   ../../../../../../Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0.2/Contents/Home/lib/static/darwin-amd64/libfdlibm.a
#   ../../../../../../Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0.2/Contents/Home/lib/static/darwin-amd64/libzip.a
#   ../../../../../../Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.0.0.2/Contents/Home/lib/svm/clibraries/darwin-amd64/libjvm.a
# Other libraries: pthread,-framework Foundation,dl,z
[test:52702]   (typeflow):  10,228.81 ms,  1.22 GB
[test:52702]    (objects):   5,741.21 ms,  1.22 GB
[test:52702]   (features):     427.06 ms,  1.22 GB
[test:52702]     analysis:  17,226.71 ms,  1.22 GB
[test:52702]     universe:     796.29 ms,  1.22 GB
[test:52702]      (parse):   3,883.32 ms,  1.70 GB
[test:52702]     (inline):   2,203.53 ms,  1.70 GB
[test:52702]    (compile):  18,905.36 ms,  2.32 GB
[test:52702]      compile:  25,727.56 ms,  2.32 GB
[test:52702]        image:   1,962.79 ms,  2.32 GB
[test:52702]        write:     570.77 ms,  2.32 GB
[test:52702]      [total]:  56,786.07 ms,  2.32 GB
```

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this, this is tracked internally in GR-30022

**Comment by nemecec** [comment]
Thank you! Any idea when I can expect a fix? Next release?

**Comment by vjovanov** [comment]
This bug has been fixed with inlining before analysis and it is available in GraalVM 21.
