### ISSUE TITLE
I can't get a native image to compile an application using Kotlin 

### ISSUE THREAD

**Issue by joshlong** [oracle/graal#3276]
I'm getting an error when trying to compile a Kotlin + Spring application with `native-image`. 

Here's the stack trace: 

```
 Parsing context:
[INFO]     [creator]     	parsing org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795)
[INFO]     [creator]     	parsing org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:785)
[INFO]     [creator]     	parsing org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
[INFO]     [creator]     	parsing com.example.rx.RxApplicationKt.main(RxApplication.kt:86)
[INFO]     [creator]     	parsing com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:146)
[INFO]     [creator]     	parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
[INFO]     [creator]     	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
[INFO]     [creator]     
[INFO]     [creator]     	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
[INFO]     [creator]     	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:327)
[INFO]     [creator]     	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:302)
[INFO]     [creator]     	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
[INFO]     [creator]     	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:227)
[INFO]     [creator]     	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:470)
[INFO]     [creator]     	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:542)
[INFO]     [creator]     	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:547)
[INFO]     [creator]     	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
[INFO]     [creator]     	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
[INFO]     [creator]     	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[INFO]     [creator]     	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[INFO]     [creator]     	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[INFO]     [creator]     	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[INFO]     [creator]     	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[INFO]     [creator]     Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.NoClassDefFoundError: com/example/rx/RxApplicationKt$main$1$context$1$1$1
[INFO]     [creator]     	at parsing com.example.rx.RxApplicationKt$main$1$context$1$$special$$inlined$bean$2$lambda$1.run(RxApplication.kt:41)
[INFO]     [creator]     	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2586)
[INFO]     [creator]     	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:106)
[INFO]     [creator]     	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3441)
[INFO]     [creator]     	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3243)
[INFO]     [creator]     	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1109)
[INFO]     [creator]     	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1003)
[INFO]     [creator]     	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
[INFO]     [creator]     	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:76)
[INFO]     [creator]     	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
[INFO]     [creator]     	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
[INFO]     [creator]     	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
[INFO]     [creator]     	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
[INFO]     [creator]     	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:223)
[INFO]     [creator]     	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:357)
[INFO]     [creator]     	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:313)
[INFO]     [creator]     	... 13 more
[INFO]     [creator]     Caused by: java.lang.NoClassDefFoundError: com/example/rx/RxApplicationKt$main$1$context$1$1$1
[INFO]     [creator]     	at java.base/java.lang.Class.getEnclosingMethod0(Native Method)
[INFO]     [creator]     	at java.base/java.lang.Class.hasEnclosingMethodInfo(Class.java:1708)
[INFO]     [creator]     	at java.base/java.lang.Class.isLocalOrAnonymousClass(Class.java:1704)
[INFO]     [creator]     	at java.base/java.lang.Class.isLocalClass(Class.java:1656)
[INFO]     [creator]     	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJDKReflection.isLocalClass(HotSpotJDKReflection.java:94)
[INFO]     [creator]     	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.isLocal(HotSpotResolvedObjectTypeImpl.java:967)
[INFO]     [creator]     	at com.oracle.graal.pointsto.meta.AnalysisType.isLocal(AnalysisType.java:1023)
[INFO]     [creator]     	at com.oracle.svm.hosted.SVMHost.createHub(SVMHost.java:379)
[INFO]     [creator]     	at com.oracle.svm.hosted.SVMHost.registerType(SVMHost.java:249)
[INFO]     [creator]     	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:272)
[INFO]     [creator]     	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:210)
[INFO]     [creator]     	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:187)
[INFO]     [creator]     	at com.oracle.graal.pointsto.infrastructure.AnalysisConstantPool.lookupField(AnalysisConstantPool.java:48)
[INFO]     [creator]     	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.lookupField(BytecodeParser.java:4360)
[INFO]     [creator]     	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genGetStatic(BytecodeParser.java:4914)
[INFO]     [creator]     	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5400)
[INFO]     [creator]     	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3436)
[INFO]     [creator]     	... 25 more
[INFO]     [creator]     Error: Image build request failed with exit status 1
[INFO]     [creator]     unable to invoke layer creator
[INFO]     [creator]     unable to contribute native-image layer
[INFO]     [creator]     error running build
[INFO]     [creator]     exit status 1
[INFO]     [creator]     ERROR: failed to build: exit status 1

```

You can reproduce it using `mvn spring-boot:build-image` with the `pom.xml` at the root of the [this Github repository](https://github.com/joshlong/rx-kotlin-native).

**Comment by mcraj017** [comment]
@joshlong thanks for reporting the issue
we will check it and get back to you

**Comment by mcraj017** [comment]
@joshlong I tried the reproducer and got the below error:
```
ERROR] org.apache.maven.plugin.MojoExecutionException: Fatal error compiling
[ERROR] [org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1145), org.apache.maven.plugin.compiler.TestCompilerMojo.execute(TestCompilerMojo.java:180), org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137), org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo(MojoExecutor.java:120), org.springframework.aot.maven.AbstractBootstrapMojo.compileGeneratedTestSources(AbstractBootstrapMojo.java:151), org.springframework.aot.maven.TestGenerateMojo.execute(TestGenerateMojo.java:65), org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137), org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210), org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156), org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148), org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:355), org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200), org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156), org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148), org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117), org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81), org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56), org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128), org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305), org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192), org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105), org.apache.maven.cli.MavenCli.execute(MavenCli.java:956), org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288), org.apache.maven.cli.MavenCli.main(MavenCli.java:192), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282), org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225), org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406), org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)]
```

**Comment by mcraj017** [comment]
Closing the issue because there is no response form the user
