### ISSUE TITLE
Using date in version 21.0.0

### ISSUE THREAD

**Issue by himanshusharma30** [oracle/graal#3278]
On printing date in js using `console.log(dateObject)`,  prints the instant of the object. In my case, I am using java.sql.Date which has no time component, hence throws UnsupportedOperationException. Such problem was not in the previous versions and the date got printed as the toString() returned the string but after the v21.0.0 release the same code is throwing exception.

**Comment by oubidar-Abderrahim** [comment]
Could you please provide a reproducer for this issue? thanks

**Comment by himanshusharma30** [comment]
`org.graalvm.polyglot.Context.Builder builder = Context.newBuilder();
		builder.allowAllAccess(true);
		try (Context context = builder.build()) {
		context.eval("js", "console.log(new java.util.Date()); console.log(new java.sql.Date(new java.util.Date().getTime()))");
		}`

In version previous to 21.0.0, this code gives output as 

Fri Mar 19 10:50:07 IST 2021
2021-03-19

but in versions on and after 21.0.0, the same code prints

1616130965157
Exception in thread "main" org.graalvm.polyglot.PolyglotException: java.lang.UnsupportedOperationException
	at java.sql/java.sql.Date.toInstant(Date.java:316)
	at com.oracle.truffle.polyglot.HostObject.asInstant(HostObject.java:995)
	at com.oracle.truffle.polyglot.HostObjectGen$InteropLibraryExports$Cached.asInstant(HostObjectGen.java:2138)
	at com.oracle.truffle.js.runtime.builtins.JSDate.getDateValueFromInstant(JSDate.java:707)
	at com.oracle.truffle.js.nodes.cast.JSToPrimitiveNode.doTruffleJavaObject(JSToPrimitiveNode.java:229)
	at com.oracle.truffle.js.nodes.cast.JSToPrimitiveNodeGen.execute(JSToPrimitiveNodeGen.java:117)
	at com.oracle.truffle.js.nodes.cast.JSToStringNode.doTruffleObject(JSToStringNode.java:167)
	at com.oracle.truffle.js.nodes.cast.JSToStringNodeGen.executeString(JSToStringNodeGen.java:95)
	at com.oracle.truffle.js.builtins.GlobalBuiltins$JSGlobalOperation.toString1(GlobalBuiltins.java:507)
	at com.oracle.truffle.js.builtins.GlobalBuiltins$JSGlobalPrintNode.print(GlobalBuiltins.java:1330)
	at com.oracle.truffle.js.builtins.GlobalBuiltinsFactory$JSGlobalPrintNodeGen.execute(GlobalBuiltinsFactory.java:2384)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:147)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:93)
	at <js> :program(Unnamed:1:35-96)
	at org.graalvm.polyglot.Context.eval(Context.java:373)


Instant of the date is being extracted and then printed, rather than toString().

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting the issue. It is tracked now internally by GR-30325

**Comment by chumer** [comment]
Fixed in 21.1
