### ISSUE TITLE
Run time NPE in Kotlin code

### ISSUE THREAD

**Issue by kirillp** [oracle/graal#3279]
**Describe the issue**

When I compile Kotlin simple, the result executable crashes with NPE
```
now kotlin ...
Unconfined            : I'm working in thread main
java.lang.ExceptionInInitializerError: null
    at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:315)
    at kotlin.random.Random.<clinit>(Random.kt:272)

```
**Steps to reproduce the issue**
use my repo: https://github.com/kirillp/graalSamples/tree/kotlin
branch kotlin
mvn clean package

**Describe GraalVM and your environment:**
 - GraalVM version graalvm-ce-java11-21.0.0
 - JDK major version:  11
 - OS: Windows
 - Architecture: AMD64

**Comment by mcraj017** [comment]
@kirillp thanks for reporting the issue
we will look into it and get back to you

**Comment by mcraj017** [comment]
@kirillp please try with GraalVM 21.0.0.2 https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.0.0.2
It worked for me
```
C:\graalvm-ce-java11-21.0.0.2\lib\svm\bin\native-image.exe -cp C:\Users\mchouhan\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib-jdk8\1.4.31\kotlin-stdlib-jdk8-1.4.31.jar;C:\Users\mchouhan\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib\1.4.31\kotlin-stdlib-1.4.31.jar;C:\Users\mchouhan\.m2\repository\org\jetbrains\annotations\13.0\annotations-13.0.jar;C:\Users\mchouhan\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib-jdk7\1.4.31\kotlin-stdlib-jdk7-1.4.31.jar;C:\Users\mchouhan\.m2\repository\org\jetbrains\kotlinx\kotlinx-coroutines-core-jvm\1.4.1\kotlinx-coroutines-core-jvm-1.4.1.jar;C:\Users\mchouhan\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib-common\1.4.0\kotlin-stdlib-common-1.4.0.jar;C:\Users\mchouhan\Desktop\github\3279\graalSamples\simpleApp\target\add-1.0-SNAPSHOT.jar --no-fallback --shared -H:Optimize=2 -H:Name=GraalSample
[GraalSample:15804]    classlist:   1,011.65 ms,  0.96 GB
[GraalSample:15804]        (cap):  21,070.78 ms,  0.96 GB
[GraalSample:15804]        setup:  25,217.11 ms,  0.96 GB
[GraalSample:15804]     (clinit):     235.68 ms,  1.72 GB
[GraalSample:15804]   (typeflow):   6,410.56 ms,  1.72 GB
[GraalSample:15804]    (objects):   5,659.82 ms,  1.72 GB
[GraalSample:15804]   (features):     305.12 ms,  1.72 GB
[GraalSample:15804]     analysis:  12,957.01 ms,  1.72 GB
[GraalSample:15804]     universe:     513.91 ms,  1.72 GB
[GraalSample:15804]      (parse):     879.97 ms,  1.72 GB
[GraalSample:15804]     (inline):   1,230.17 ms,  1.72 GB
[GraalSample:15804]    (compile):   7,637.30 ms,  2.37 GB
[GraalSample:15804]      compile:  10,314.95 ms,  2.37 GB
[GraalSample:15804]        image:   1,072.77 ms,  2.37 GB
[GraalSample:15804]        write:   1,077.59 ms,  2.37 GB
[GraalSample:15804]      [total]:  52,712.24 ms,  2.37 GB
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:exec (windows-app) @ add ---
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-exec/1.3/commons-exec-1.3.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-exec/1.3/commons-exec-1.3.pom (11 kB at 6.3 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/35/commons-parent-35.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/35/commons-parent-35.pom (58 kB at 85 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar (54 kB at 82 kB/s)

C:\Users\mchouhan\Desktop\github\3279\graalSamples\simpleApp>cl app.cpp GraalSample.lib /Itarget /Fotarget\ /Fetarget\ /MD /link /libpath:target\ 
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29913 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

app.cpp
Microsoft (R) Incremental Linker Version 14.28.29913.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:target\app.exe
/libpath:target\
target\app.obj
GraalSample.lib
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:07 min
[INFO] Finished at: 2021-04-07T16:23:24+08:00
[INFO] ------------------------------------------------------------------------
```

**Comment by kirillp** [comment]
the problem with resulting executable does not work
> the result executable crashes with NPE

**Comment by mcraj017** [comment]
@kirillp thanks for the clarification, I have raised the bug with our dev team.
I will be resolved in future releases

**Comment by wirthi** [comment]
@kirillp sorry for the quite delayed response. The use of AI makes it easier to tackle such tickets now, and I have managed to reproduce and fix your problem. This is what the agent did to fix it (based on the current master branch, but should also work on 25.0 in similar fashion):

1. Add reachability metadata for Kotlin stdlib reflection
   Native Image needs reflective constructor metadata for:
```
     {
       "reflection": [
         {
           "type": "kotlin.internal.jdk8.JDK8PlatformImplementations",
           "methods": [
             { "name": "<init>", "parameterTypes": [] }
           ]
         }
       ]
     }
```
2. Close the explicitly created coroutine thread.  The sample uses: `newSingleThreadContext("MyOwnThread")`- that dispatcher needs to be closed after the launched job completes. Otherwise the sample prints output but isolate teardown can hang.
3. Shut down the old coroutines default scheduler. With kotlinx-coroutines-core-jvm:1.4.1, Dispatchers.Default leaves worker threads around. For this embedded/shared-library sample, I added cleanup after the Kotlin. Entry point: `     DefaultScheduler.INSTANCE.shutdown$kotlinx_coroutines_core(1_000L);`
4. Use the right isolate teardown API in the C launcher. Since Java-created threads were involved, the Linux launcher should use: `graal_detach_all_threads_and_tear_down_isolate(graalThread)` instead of plain: `graal_tear_down_isolate(graalThread)`
5. Build-tool compatibility only. The original Kotlin Maven plugin 1.4.31 is too old for current JDKs. To compile the old sample locally, I used GraalVM 17 plus: `MAVEN_OPTS='--add-opens java.base/java.util=ALL-UNNAMED'`. The actual native image was then built with current masterGraalVM.


This resulted in a 15MB GraalSample.so and a 16k app-current. Starting the `./app-current` results in:

```
$ ./app-current
graal results: add(4) = 5, sub(7) = -6
now kotlin ...
Unconfined            : I'm working in thread main
Default               : I'm working in thread DefaultDispatcher-worker-1
main runBlocking      : I'm working in thread main
newSingleThreadContext: I'm working in thread MyOwnThread
```
