### ISSUE TITLE
Bean definition [freemarker.template.Configuration] could not be loaded: Error instantiating bean of type [freemarker.template.Configuration]: null

### ISSUE THREAD

**Issue by hminukuri-chwy** [oracle/graal#3281]
**Describe the issue**
Native image throws Error instantiating bean of type [freemarker.template.Configuration]: null , while java jar works fine

**Steps to reproduce the issue**
https://github.com/hminukuri-chwy/graalfreemarkerConfiguration

**Describe GraalVM and your environment:**
Steps to reproduce 
./deploy.sh
Invoke lambda function with sample test event
  "body": "{\"name\":\"Testing GraalVM\"}",
Java jar deployment works fine  , native image throws this error

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [freemarker.template.Configuration] could not be loaded: Error instantiating bean of type [freemarker.template.Configuration]: null
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1549)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:220)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2780)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:233)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:166)
	at io.micronaut.function.executor.AbstractExecutor.startEnvironment(AbstractExecutor.java:125)
	at io.micronaut.function.aws.MicronautRequestHandler.buildApplicationContext(MicronautRequestHandler.java:85)
	at io.micronaut.function.aws.MicronautRequestHandler.<init>(MicronautRequestHandler.java:48)
	at example.micronaut.BookRequestHandler.<init>(BookRequestHandler.java:17)
	at example.micronaut.BookLambdaRuntime.createRequestHandler(BookLambdaRuntime.java:23)
	at io.micronaut.function.aws.runtime.AbstractMicronautLambdaRuntime.createHandler(AbstractMicronautLambdaRuntime.java:192)
	at io.micronaut.function.aws.runtime.AbstractMicronautLambdaRuntime.startRuntimeApiEventLoop(AbstractMicronautLambdaRuntime.java:313)
	at io.micronaut.function.aws.runtime.AbstractMicronautLambdaRuntime.run(AbstractMicronautLambdaRuntime.java:129)
	at example.micronaut.BookLambdaRuntime.main(BookLambdaRuntime.java:13)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [freemarker.template.Configuration]: null
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1927)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2647)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2183)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1543)
	... 13 more
Caused by: java.lang.ExceptionInInitializerError
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:290)
	at java.lang.Class.ensureInitialized(DynamicHub.java:499)
	at example.micronaut.FreeMarkerMessageComposerFactory.freemarkerConfiguration(FreeMarkerMessageComposerFactory.java:26)
	at example.micronaut.$FreeMarkerMessageComposerFactory$FreemarkerConfiguration0Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1898)
	... 16 more
Caused by: java.lang.RuntimeException: Failed to load and parse /freemarker/version.properties
	at freemarker.template.Configuration.<clinit>(Configuration.java:515)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	... 20 more
Caused by: java.io.IOException: Class-loader resource not found (shown quoted): "/freemarker/version.properties". The base class was freemarker.template.Configuration.
	at freemarker.template.utility.ClassUtil.checkInputStreamNotNull(ClassUtil.java:534)
	at freemarker.template.utility.ClassUtil.loadProperties(ClassUtil.java:498)
	at freemarker.template.Configuration.<clinit>(Configuration.java:494)
	... 22 more
Request loop failed with: Bean definition [freemarker.template.Configuration] could not be loaded: Error instantiating bean of type [freemarker.template.Configuration]: null
END RequestId: 5eb919d1-f0f7-4598-94ba-abee54badf6f
REPORT RequestId: 5eb919d1-f0f7-4598-94ba-abee54badf6f	Duration: 1187.13 ms	Billed Duration: 1188 ms	Memory Size: 128 MB	Max Memory Used: 31 MB	
Unknown application error occurred

```

**Comment by hminukuri-chwy** [comment]
Closing this adding this dependency fixed issue

  **implementation("io.micronaut.views:micronaut-views-freemarker")**
