### ISSUE TITLE
native-image on applications using com.sun.jndi.ldap.ServiceLocator fail

### ISSUE THREAD

**Issue by jerboaa** [oracle/graal#3297]
**Describe the issue**
https://github.com/oracle/graal/commit/11b9817fb341f9447c300304fe461933bf79c2aa#diff-8ea159555f76609d835155ca3b7f534b8a5adbb932fa6366c4db09a5b2ec2275R62 banned Random/SplittableRandom from the image heap. As it turns out there is still some usage of `java.util.Random` in `com.sun.jndi.ldap.ServiceLocator` (part of OpenJDK 11), which isn't properly configured to get runtime-reinitialized. That's unlike other usages within OpenJDK.

**Steps to reproduce the issue**
Run the quarkus elytron-security-ldap integration tests with `-Dnative`

**Describe GraalVM and your environment:**
 - GraalVM version: master, revision e1eb501fe3106ddddbe6a5dbc08db866663b1976
 - JDK major version: **11**
 - OS: **Linux**
 - Architecture: **AMD64**

**More details**
Stack trace looks like this:
```
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.  Object has been initialized by the com.sun.jndi.ldap.ServiceLocator class initializer with a trace: 
 	at java.util.Random.<init>(Random.java:105)
	at com.sun.jndi.ldap.ServiceLocator.<clinit>(ServiceLocator.java:47)
. Try avoiding to initialize the class that caused initialization of the object. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: 
	at parsing java.naming@11.0.11-ea/com.sun.jndi.ldap.ServiceLocator.selectHostport(ServiceLocator.java:248)
Call path from entry point to com.sun.jndi.ldap.ServiceLocator.selectHostport(ServiceLocator$SrvRecord[], int, int): 
	at java.naming@11.0.11-ea/com.sun.jndi.ldap.ServiceLocator.selectHostport(ServiceLocator.java:232)
	at java.naming@11.0.11-ea/com.sun.jndi.ldap.ServiceLocator.extractHostports(ServiceLocator.java:220)
	at java.naming@11.0.11-ea/com.sun.jndi.ldap.ServiceLocator.getLdapService(ServiceLocator.java:185)
	at java.naming@11.0.11-ea/com.sun.jndi.ldap.ServiceLocator.getLdapService(ServiceLocator.java:114)
	at java.naming@11.0.11-ea/com.sun.jndi.ldap.DefaultLdapDnsProvider.lookupEndpoints(DefaultLdapDnsProvider.java:59)
	at java.naming@11.0.11-ea/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:200)
	at com.oracle.svm.reflect.LdapCtxFactory_getUsingURL_3f8afafe7f27d6a3ad324737dd5b4a503b392567_210.invoke(Unknown Source)
	at java.base@11.0.11-ea/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base@11.0.11-ea/java.util.ServiceLoader$ProviderImpl.invokeFactoryMethod(ServiceLoader.java:737)
	at java.base@11.0.11-ea/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:720)
	at app//com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:217)
	at app//com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:170)
	at app//com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:291)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)
```

**Comment by jerboaa** [comment]
I should have a PR which fixes this issue available shortly.

**Comment by mcraj017** [comment]
@vjovanov please close this issue, once you merge the related PR

**Comment by jerboaa** [comment]
@vjovanov Any update on this one? You've mentioned in #3298 that the fix will be part of another change. Has that been integrated?
