### ISSUE TITLE
Source.CONTENT_NONE breaks IGV and graal.Dump

### ISSUE THREAD

**Issue by acertain** [oracle/graal#3301]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: 21.0.0.2
 - CE or EE: I think both? but this stack trace iirc is from EE
 - JDK version: graalvm-ee-java11-21.0.0.2
 - OS and OS Version: linux nixos
 - Architecture: amd64
 - The output of `java -Xinternalversion`: Java HotSpot(TM) 64-Bit Server VM (11.0.10+8-LTS-jvmci-21.0-b06) for linux-amd64 JRE (11.0.10+8-LTS-jvmci-21.0-b06), built on Jan 15 2021 11:30:21 by "buildslave" with gcc 7.3.0

**Have you verified this issue still happens when using the latest snapshot?**

No

**Describe the issue**

IGV yells at me and doesn't load the graph, and truffle/graal prints a TruffleCompilerThread exception

**Code snippet or code repository that reproduces the issue**
```
    Source.newBuilder("cadenza", "", sp.file)
          .content(Source.CONTENT_NONE).build()
          .createSection(sp.sline, sp.scol, sp.eline, sp.ecol)
```
then return the section from RootNode.getSourceSection, and trigger compilation

**Additional context**

Stack trace/TruffleCompilerThread log 

<details><summary>Details</summary>

```

[thread:562] scope: TruffleCompilerThread-23
  [thread:562] scope: TruffleCompilerThread-23.Truffle
  Context: Truffle<ClosureRootNode@5918c260()>
    [thread:562] scope: TruffleCompilerThread-23.Truffle.CreateGraph
    Context: StructuredGraph:211844{ClosureRootNode@5918c260, HotSpotMethod<OptimizedCallTarget.profiledPERoot(Object[])>}
      [thread:562] scope: TruffleCompilerThread-23.Truffle.CreateGraph.AgnosticInliningPhase
      Exception raised in scope TruffleCompilerThread-23.Truffle.CreateGraph.AgnosticInliningPhase: org.graalvm.libgraal.jni.JNIExceptionWrapper: java.lang.UnsupportedOperationException
      	at com.oracle.truffle.api.source.SourceImpl.getCharacters(SourceImpl.java:86)
      	at com.oracle.truffle.api.source.Source.getURI(Source.java:391)
      	at org.graalvm.compiler.truffle.runtime.TruffleInlining$TruffleSourceLanguagePosition.getURI(TruffleInlining.java:161)
      	at org.graalvm.compiler.truffle.runtime.hotspot.libgraal.TruffleFromLibGraalEntryPoints.getURI(TruffleFromLibGraalEntryPoints.java:290)
      	at org.graalvm.libgraal.jni.FromLibGraalCalls.callJObject(FromLibGraalCalls.java:154)
      	at org.graalvm.compiler.truffle.compiler.hotspot.libgraal.HSTruffleInliningPlanGen.callGetURI(HSTruffleInliningPlanGen.java:66)
      	at org.graalvm.compiler.truffle.compiler.hotspot.libgraal.HSTruffleInliningPlan$HSTruffleSourceLanguagePosition.getURI(HSTruffleInliningPlan.java:181)
      	at org.graalvm.compiler.truffle.compiler.PartialEvaluator$SourceLanguagePositionImpl.getURI(PartialEvaluator.java:665)
      	at org.graalvm.compiler.printer.BinaryGraphPrinter.locationURI(BinaryGraphPrinter.java:571)
      	at org.graalvm.compiler.printer.BinaryGraphPrinter.locationURI(BinaryGraphPrinter.java:80)
      	at org.graalvm.graphio.ProtocolImpl.findLocationURI(ProtocolImpl.java:337)
      	at org.graalvm.graphio.GraphProtocol.addPoolEntry(GraphProtocol.java:692)
      	at org.graalvm.graphio.GraphProtocol.writePoolObject(GraphProtocol.java:479)
      	at org.graalvm.graphio.GraphProtocol.writePropertyObject(GraphProtocol.java:837)
      	at org.graalvm.graphio.GraphProtocol.writeProperties(GraphProtocol.java:866)
      	at org.graalvm.graphio.GraphProtocol.writeNodes(GraphProtocol.java:554)
      	at org.graalvm.graphio.GraphProtocol.writeGraph(GraphProtocol.java:537)
      	at org.graalvm.graphio.GraphProtocol.writePropertyObject(GraphProtocol.java:840)
      	at org.graalvm.graphio.GraphProtocol.writeProperties(GraphProtocol.java:866)
      	at org.graalvm.graphio.GraphProtocol.writeNodes(GraphProtocol.java:554)
      	at org.graalvm.graphio.GraphProtocol.writeGraph(GraphProtocol.java:537)
      	at org.graalvm.graphio.GraphProtocol.print(GraphProtocol.java:138)
      	at org.graalvm.graphio.GraphOutput.print(GraphOutput.java:100)
      	at org.graalvm.compiler.printer.BinaryGraphPrinter.print(BinaryGraphPrinter.java:318)
      	at org.graalvm.compiler.printer.GraphPrinterDumpHandler.dump(GraphPrinterDumpHandler.java:200)
      	at org.graalvm.compiler.debug.ScopeImpl.dump(ScopeImpl.java:223)
      	at org.graalvm.compiler.debug.DebugContext.dump(DebugContext.java:1363)
      	at org.graalvm.compiler.truffle.compiler.phases.inlining.CallTree.dumpBasic(CallTree.java:105)
      	at org.graalvm.compiler.truffle.compiler.phases.inlining.AgnosticInliningPhase.run(AgnosticInliningPhase.java:82)
      	at org.graalvm.compiler.truffle.compiler.phases.inlining.AgnosticInliningPhase.run(AgnosticInliningPhase.java:38)
      	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
      	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
      	at org.graalvm.compiler.truffle.compiler.PartialEvaluator.inliningGraphPE(PartialEvaluator.java:614)
      	at org.graalvm.compiler.truffle.compiler.PartialEvaluator.evaluate(PartialEvaluator.java:344)
      	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compileAST(TruffleCompilerImpl.java:514)
      	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:733)
      	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:668)
      	at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:222)
      	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.actuallyCompile(TruffleCompilerImpl.java:336)
      	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.doCompile(TruffleCompilerImpl.java:289)
      	at org.graalvm.compiler.truffle.compiler.hotspot.libgraal.TruffleToLibGraalEntryPoints.doCompile(TruffleToLibGraalEntryPoints.java:261)
      	at org.graalvm.compiler.truffle.runtime.hotspot.libgraal.TruffleToLibGraalCalls.doCompile(Native Method)
      	at org.graalvm.compiler.truffle.runtime.hotspot.libgraal.LibGraalHotSpotTruffleCompiler.doCompile(LibGraalHotSpotTruffleCompiler.java:123)
      	at org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.compileImpl(GraalTruffleRuntime.java:695)
      	at org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.doCompile(GraalTruffleRuntime.java:662)
      	at org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.doCompile(GraalTruffleRuntime.java:643)
      	at org.graalvm.compiler.truffle.runtime.CompilationTask$1.accept(CompilationTask.java:58)
      	at org.graalvm.compiler.truffle.runtime.CompilationTask$1.accept(CompilationTask.java:52)
      	at org.graalvm.compiler.truffle.runtime.CompilationTask.call(CompilationTask.java:180)
      	at org.graalvm.compiler.truffle.runtime.CompilationTask.call(CompilationTask.java:41)
      	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
      	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
      	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
      	at java.lang.Thread.run(Thread.java:834)
      	at org.graalvm.compiler.truffle.runtime.BackgroundCompileQueue$TruffleCompilerThreadFactory$1.run(BackgroundCompileQueue.java:279)
```
</details>

**Comment by tzezula** [comment]
Fixed in graalvm-21.1.
https://github.com/oracle/graal/commit/35a07adf4249afbf19aec5db02b291da2d8a3749
