### ISSUE TITLE
[dap] SEVERE: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by echoinacup** [oracle/graal#3309]
**Described GraalVM and your environment :**
 - GraalVM version **[graal-sdk-20.3.0]**
 - **[CE]**
 - JDK version: **[e.g.: JDK11]**
 - OS and OS Version: **[macOS BigSur 11.2.1]**
 - Architecture: **[x64]**
 - The output of `java -Xinternalversion`:
```
 **OpenJDK 64-Bit Server VM (11.0.10+8-jvmci-21.0-b06) for bsd-amd64 JRE (11.0.10+8-jvmci-21.0-b06), built on Jan 15 2021 00:28:57 by "graal1" with gcc 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)**
```

**Have you verified this issue still happens when using the latest snapshot?** YES
You can find snapshot builds here: https://github.com/graalvm/graalvm-ce-dev-builds/releases

**Describe the issue**
I've created DAP connection and run debug of client javascript which was executed in java with the HELP of VScode.

**Code snippet or code repository that reproduces the issue**
```
    public static void main(String[] args) {
        Context context = Context.newBuilder(JavaScriptLanguage.ID)
                .option("dap", "4747")
                .build();
        var evaluated = context.eval(JavaScriptLanguage.ID, "function check() {\n" +
                "  console.log(\"start\");\n" +
                "\n" +
                "  for (let index = 0; index < 10; index++) {\n" +
                "    console.log(index);\n" +
                "  }\n" +
                "\n" +
                "  console.log(\"stop\");\n" +
                "  return \"done\"\n" +
                "}");
        Value function = context.getBindings(JavaScriptLanguage.ID).getMember("check");

        System.out.println(function.execute());
    }

//VS code launch 
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "graalvm",
            "request": "attach",
            "name": "Attach to Remote",
            "debugServer": 4747
        }
    ]
}
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Step one run main method 
2. Step two run debug from vs code f5 with the launch file 

**Expected behavior**
the console output should be without errors, just the debug result. In my case, only console output from the javascript

**Additional context**
Add any other context about the problem here. Specially important are stack traces or log output. Feel free to link to gists or to screenshots if necesary
<details><summary>Details</summary>

```
   Graal DAP] Starting server and listening on localhost/127.0.0.1:4747
[Graal DAP] Client connected on /127.0.0.1:52571
[To redirect Truffle log output to a file use one of the following options:
* '--log.file=<path>' if the option is passed using a guest language launcher.
* '-Dpolyglot.log.file=<path>' if the option is passed using the host Java launcher.
* Configure logging using the polyglot embedding API.]
[dap] SEVERE: Index 0 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.oracle.truffle.tools.dap.server.LoadedSourcesHandler.getSource(LoadedSourcesHandler.java:76)
	at com.oracle.truffle.tools.dap.server.BreakpointsHandler.setBreakpoints(BreakpointsHandler.java:88)
	at com.oracle.truffle.tools.dap.server.DebugProtocolServerImpl.setBreakpoints(DebugProtocolServerImpl.java:249)
	at com.oracle.truffle.tools.dap.types.DebugProtocolServer$Session.processRequest(DebugProtocolServer.java:477)
	at com.oracle.truffle.tools.dap.types.DebugProtocolServer$Session.processMessage(DebugProtocolServer.java:404)
	at com.oracle.truffle.tools.dap.types.DebugProtocolServer$Session.run(DebugProtocolServer.java:341)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

[dap] SEVERE: Index 0 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.oracle.truffle.tools.dap.server.LoadedSourcesHandler.getSource(LoadedSourcesHandler.java:76)
	at com.oracle.truffle.tools.dap.server.BreakpointsHandler.setBreakpoints(BreakpointsHandler.java:88)
	at com.oracle.truffle.tools.dap.server.DebugProtocolServerImpl.setBreakpoints(DebugProtocolServerImpl.java:249)
	at com.oracle.truffle.tools.dap.types.DebugProtocolServer$Session.processRequest(DebugProtocolServer.java:477)
	at com.oracle.truffle.tools.dap.types.DebugProtocolServer$Session.processMessage(DebugProtocolServer.java:404)
	at com.oracle.truffle.tools.dap.types.DebugProtocolServer$Session.run(DebugProtocolServer.java:341)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

[dap] SEVERE: Index 0 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.oracle.truffle.tools.dap.server.LoadedSourcesHandler.getSource(LoadedSourcesHandler.java:76)
	at com.oracle.truffle.tools.dap.server.BreakpointsHandler.setBreakpoints(BreakpointsHandler.java:88)
	at com.oracle.truffle.tools.dap.server.DebugProtocolServerImpl.setBreakpoints(DebugProtocolServerImpl.java:249)
	at com.oracle.truffle.tools.dap.types.DebugProtocolServer$Session.processRequest(DebugProtocolServer.java:477)
	at com.oracle.truffle.tools.dap.types.DebugProtocolServer$Session.processMessage(DebugProtocolServer.java:404)
	at com.oracle.truffle.tools.dap.types.DebugProtocolServer$Session.run(DebugProtocolServer.java:341)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

[dap] SEVERE: Index 0 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.oracle.truffle.tools.dap.server.LoadedSourcesHandler.getSource(LoadedSourcesHandler.java:76)
	at com.oracle.truffle.tools.dap.server.BreakpointsHandler.setBreakpoints(BreakpointsHandler.java:88)
	at com.oracle.truffle.tools.dap.server.DebugProtocolServerImpl.setBreakpoints(DebugProtocolServerImpl.java:249)
	at com.oracle.truffle.tools.dap.types.DebugProtocolServer$Session.processRequest(DebugProtocolServer.java:477)
	at com.oracle.truffle.tools.dap.types.DebugProtocolServer$Session.processMessage(DebugProtocolServer.java:404)
	at com.oracle.truffle.tools.dap.types.DebugProtocolServer$Session.run(DebugProtocolServer.java:341)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

[dap] SEVERE: Index 0 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.oracle.truffle.tools.dap.server.LoadedSourcesHandler.getSource(LoadedSourcesHandler.java:76)
	at com.oracle.truffle.tools.dap.server.BreakpointsHandler.setBreakpoints(BreakpointsHandler.java:88)
	at com.oracle.truffle.tools.dap.server.DebugProtocolServerImpl.setBreakpoints(DebugProtocolServerImpl.java:249)
	at com.oracle.truffle.tools.dap.types.DebugProtocolServer$Session.processRequest(DebugProtocolServer.java:477)
	at com.oracle.truffle.tools.dap.types.DebugProtocolServer$Session.processMessage(DebugProtocolServer.java:404)
	at com.oracle.truffle.tools.dap.types.DebugProtocolServer$Session.run(DebugProtocolServer.java:341)
```
</details>

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this, Could you please try with either 21.0.0.2 or 20.3.1.2 and see if the issue persists?

**Comment by echoinacup** [comment]
@oubidar-Abderrahim thank you for such a quick response!
Could you please take a look on the screenshot below:
<img width="1028" alt="Screenshot 2021-03-29 at 15 04 34" src="https://user-images.githubusercontent.com/12871695/112841484-d05f3680-90a0-11eb-83dd-c681dc07eaae.png">

**Comment by oubidar-Abderrahim** [comment]
I couldn't reproduce this issue on my macOS Catalina, maybe it is specific to Big Sur. I will try to find a suitable machine to test.
Also, if it possible for you to test in another macOS version or in Linux, this would be very helpful.

**Comment by echoinacup** [comment]
I will ask my colleague and I will let you know as soon as possible :)

**Comment by echoinacup** [comment]
I've tried on my colleague's  machine with the same MacOs and it works fine. I've reinstalled the latest version of Graalvm and reconfigured my local setting for the debug etc. The issue is gone. Thank you a lot again!
