### ISSUE TITLE
RuntimeException while using `-H:+PrintUniverse` option

### ISSUE THREAD

**Issue by ivan-ristovic** [oracle/graal#3316]
**Describe the issue**
Invoking native-image with `-H:+PrintUniverse` diagnostic option throws a RuntimeException. This happens regardless of the source code, the issue can be reproduced even with a simple "Hello world" program.

**Steps to reproduce the issue**
1. Create a simple HelloWorld program
2. Invoke `native-image` with `-H:+PrintUniverse` option
3. Observe the error

**Describe GraalVM and your environment:**
 - The master branch, as of commit 3abd476366622eb75fac1fbd88a1cbc64812e769 at the time of writing
 - JDK major version: **[11]**
 - OS: **[Ubuntu 20.04 LTS]**
 - Architecture: **[AMD64]**

**More details**
The `com.oracle.svm.hosted.NativeImageGenerator#printTypes` method has a "switch" on the LayoutEncoding of a type: https://github.com/oracle/graal/blob/a97353a9116a67c67ede205a35e0e0bfc85ea36b/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGenerator.java#L1656

`com.oracle.svm.core.heap.StoredContinuation` does not fall into any of these categories, and the method throws. There is no apparent reason why it should be in the universe for the simple HelloWorld program. @olpaw suggested that this might be related with the Java 16 changes, and in any case it seems like this type (and possibly others, I haven't checked if any other types are included which would also throw) should be excluded from the resulting image. 

This method is used in only one place, and it is this option, so other features are not affected.

Full stack trace:
```
Fatal error:com.oracle.svm.core.util.VMError$HostedError: should not reach here
        at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:64)
        at com.oracle.svm.hosted.NativeImageGenerator.printTypes(NativeImageGenerator.java:1673)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:610)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:495)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
```

**Comment by peter-hofer** [comment]
Fixed in 15e550d9b5247c20e389fb96ebd2a5c26be1134f.
