### ISSUE TITLE
Quarkus integration-tests/jgit fails to parse bytecode

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#3317]
**Describe the issue**

As reported in https://github.com/graalvm/mandrel/issues/226 there seems to be a bug which doesn't reproduce 100% of the time.
When using a graal vm 21.1-dev build from https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/21.1.0-dev-20210323_2140 and trying to generate a native-image from `integration-tests/jgit` will sometimes fail with a bytecode parsing error. Caused by a `NullPointerException`.

**Steps to reproduce the issue**

1. Get GraalVM 21.1-dev build from https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/21.1.0-dev-20210323_2140
2. `git clone --depth 1 https://github.com/quarkusio/quarkus.git`
3. `cd quarkus`
4. `./mvnw -Dquickly`
5. `export GRAALVM_HOME=<path/to/graalvm-21.1-dev>` make sure to change with the correct path
5. `./mvnw clean verify -Dnative -pl integration-tests/jgit/` (repeat until failure)

**Describe GraalVM and your environment:**
 - GraalVM version : **21.1.0-dev-20210323_2140**
 - JDK major version: **11**
 - OS: **Fedora 33**
 - Architecture: **AMD64**

**More details**

On failure the output is:
```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /home/sgehwolf/Documents/openjdk/quarkus/quarkus-source/integration-tests/jgit/target/quarkus-integration-test-jgit-999-SNAPSHOT-native-image-source-jar/quarkus-integration-test-jgit-999-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 21.1.0-dev (Java Version 11.0.11+5-jvmci-21.1-b02)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] /disk/graal/builds/graalvm-ce-java11-21.1.0-dev/bin/native-image -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Duser.language=en -J-Duser.country=US -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -jar quarkus-integration-test-jgit-999-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:NativeLinkerOption=-no-pie --no-server -H:-UseServiceLoaderFeature -H:+StackTrace quarkus-integration-test-jgit-999-SNAPSHOT-runner
[quarkus-integration-test-jgit-999-SNAPSHOT-runner:42704]    classlist:   2,909.19 ms,  0.96 GB
[quarkus-integration-test-jgit-999-SNAPSHOT-runner:42704]        (cap):     503.96 ms,  0.96 GB
[quarkus-integration-test-jgit-999-SNAPSHOT-runner:42704]        setup:   2,296.04 ms,  0.96 GB
[quarkus-integration-test-jgit-999-SNAPSHOT-runner:42704]     analysis:  16,346.52 ms,  2.29 GB
Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.eclipse.jgit.api.MergeCommand$FastForwardMode.valueOf(org.eclipse.jgit.api.MergeCommand$FastForwardMode$Merge) 
Parsing context:
	parsing com.oracle.svm.reflect.MergeCommand$FastForwardMode_valueOf_766eec92b57c0121d3830fbad8aa9f5c56f6ef35_1190.invoke(Unknown Source)
	parsing java.lang.reflect.Method.invoke(Method.java:566)
	parsing javax.enterprise.util.AnnotationLiteral.invoke(AnnotationLiteral.java:288)
	parsing javax.enterprise.util.AnnotationLiteral.getMemberValue(AnnotationLiteral.java:276)
	parsing javax.enterprise.util.AnnotationLiteral.toString(AnnotationLiteral.java:135)
	parsing java.lang.String.valueOf(String.java:2951)
	parsing java.lang.StringBuilder.append(StringBuilder.java:168)
	parsing java.lang.Throwable.printStackTrace(Throwable.java:662)
	parsing java.lang.Throwable.printStackTrace(Throwable.java:648)
	parsing java.lang.Throwable.printStackTrace(Throwable.java:639)
	parsing com.oracle.svm.core.thread.JavaThreads.dispatchUncaughtException(JavaThreads.java:647)
	parsing com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:152)
	parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:327)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureTypeFlowCreated(MethodTypeFlow.java:302)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
	at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:420)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:547)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.NullPointerException
	at parsing org.eclipse.jgit.api.MergeCommand$FastForwardMode.valueOf(MergeCommand.java:169)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2601)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:106)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3456)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3258)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1125)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1019)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:76)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:113)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:592)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:163)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:304)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:313)
	... 11 more
Caused by: java.lang.NullPointerException
	at com.oracle.svm.hosted.phases.EnumSwitchPlugin.handleInvoke(EnumSwitchPlugin.java:99)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.tryNodePluginForInvocation(BytecodeParser.java:2232)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1899)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1671)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1651)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5448)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3451)
	... 25 more
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  40.896 s
[INFO] Finished at: 2021-03-25T17:16:31+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project quarkus-integration-test-jgit: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:209)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.lang.RuntimeException: Image generation failed. Exit code: 1
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:350)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:181)
[ERROR] 	... 10 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Might be related to the introduction of EnumSwitchPlugin in oracle@9d785ed (cc @christianwimmer @cstancu )

In https://github.com/oracle/graal/blob/93ec5943ded2b22baa58529853ffc7cc5069204e/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/phases/EnumSwitchPlugin.java#L99 ensureGraphParsed may return null (see https://github.com/oracle/graal/blob/93ec5943ded2b22baa58529853ffc7cc5069204e/substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/meta/AnalysisMethod.java#L563) but it's not checked.

**Comment by christianwimmer** [comment]
Thanks for the report, I'm working on a fix to make that code more robust

**Comment by christianwimmer** [comment]
https://github.com/oracle/graal/pull/3318/files should fix the problem.
I was not able to immediately build Quarkus from source and run the tests, so can you please veriy if my PR fixes the problem?

**Comment by zakkak** [comment]
Thanks for the quick fix Christian, I tried it about 10 times and I was not able to reproduce (it used to appear about 1 out of 3 times).
