### ISSUE TITLE
Error: Incompatible change of initialization policy for org.slf4j.impl.StaticLoggerBinder: trying to change BUILD_TIME from the command line to RUN_TIME from the command line

### ISSUE THREAD

**Issue by eric-moritz** [oracle/graal#3330]
**Describe the issue**
Adding `--initialize-at-run-time=org.slf4j.impl.StaticLoggerBinder` to build args causes: `Error: Incompatible change of initialization policy for org.slf4j.impl.StaticLoggerBinder: trying to change BUILD_TIME from the command line to RUN_TIME from the command line` 

**Steps to reproduce the issue**

1. mvn -Pnative-image package

**Describe GraalVM and your environment:**
 - OpenJDK 64-Bit Server VM GraalVM CE 21.0.0.2 (build 25.282-b07-jvmci-21.0-b06, mixed mode)

 - native-image-maven-plugin, 21.0.0.2

 - spring-aot-maven-plugin, 0.9.1

**More details**
Original build args were:
```
--verbose
--no-fallback
--enable-https
--report-unsupported-elements-at-runtime
--allow-incomplete-classpath
--trace-class-initialization=javax.xml.parsers.FactoryFinder
-H:+ReportExceptionStackTraces
```

 This reported the following error:

```
com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
javax.xml.parsers.FactoryFinder was unintentionally initialized at build time. org.slf4j.impl.StaticLoggerBinder caused initialization of this class with the following trace:
                at javax.xml.parsers.FactoryFinder.<clinit>(FactoryFinder.java:45)
                at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:127)
                at ch.qos.logback.core.joran.event.SaxEventRecorder.buildSaxParser(SaxEventRecorder.java:79)
                at ch.qos.logback.core.joran.event.SaxEventRecorder.recordEvents(SaxEventRecorder.java:57)
                at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:151)
                at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
                at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
                at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
                at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
                at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
                at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
                at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
                at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:539)
                at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:226)
                at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:740)
                at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
                at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:740)
                at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:563)
                at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
                at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
                at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
                at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
                at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
                at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)

Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
                at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1676)
                at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1426)
                at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1387)
                at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1374)
```

With that, I changed build args to:
```
--verbose
--no-fallback
--enable-https
--report-unsupported-elements-at-runtime
--allow-incomplete-classpath
--trace-class-initialization=javax.xml.parsers.FactoryFinder
--initialize-at-run-time=org.slf4j.impl.StaticLoggerBinder
-H:+ReportExceptionStackTraces
```

This reported the following error:
```
Error: Incompatible change of initialization policy for org.slf4j.impl.StaticLoggerBinder: trying to change BUILD_TIME from the command line to RUN_TIME from the command line

com.oracle.svm.core.util.UserError$UserException: Incompatible change of initialization policy for org.slf4j.impl.StaticLoggerBinder: trying to change BUILD_TIME from the command line to RUN_TIME from the command line
                at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
                at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:99)
                at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
                at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
                at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
                at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
                at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insert(ClassInitializationConfiguration.java:64)
                at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.initializeAtRunTime(ConfigurableClassInitialization.java:228)
                at com.oracle.svm.hosted.classinitialization.InitKind.lambda$stringConsumer$0(InitKind.java:61)
                at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.processClassInitializationOptions(ClassInitializationFeature.java:150)
                at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:842)
                at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:561)
                at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
                at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
                at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
                at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
                at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
                at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)

Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
                at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1676)
                at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1426)
                at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1387)
                at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1374)
```

How do I resolve this error?

**Comment by mcraj017** [comment]
@eric-moritz please share a reproducer

**Comment by eric-moritz** [comment]
@mcraj017 I am not able to share current project details due to corp policies, however, I will try to create duplicate error in new project which I can share.  I then interim is there anything else I can do?

**Comment by mcraj017** [comment]
@eric-moritz check out https://github.com/oracle/graal/issues/2222

**Comment by mcraj017** [comment]
Closing this issue because there is no activity for last 30 days
