### ISSUE TITLE
BytecodeParserError: NPE when parsing sun.nio.ch.Util$3.run(Util.java:414)

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#3338]
**Steps to reproduce the issue**
Please include both build steps as well as run steps
```bash
git clone --depth 1 https://github.com/hpi-swa/trufflesqueak
cd trufflesqueak
mx --env trufflesqueak-svm build
```

**Describe GraalVM and your environment:**
 - GraalVM version, commit id: **14b6790d744d1cca484482bc09f545eee7ed93dc**
 - JDK major version: **11**
 - OS: **macOS Catalina**
 - Architecture: **AMD64**

**More details**
```
Building trufflesqueak.image... [dependency GRAALVM_594AAB0086_JAVA11_STAGE1 updated]
[trufflesqueak:40773]    classlist:   2,407.98 ms,  0.96 GB
[trufflesqueak:40773]        (cap):   2,723.33 ms,  0.96 GB
[trufflesqueak:40773]        setup:   4,601.46 ms,  0.96 GB
[trufflesqueak:40773]     analysis:  51,784.11 ms,  5.15 GB
Fatal error:org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.NullPointerException
	at parsing sun.nio.ch.Util$3.run(Util.java:414)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2601)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:106)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3456)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3258)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1125)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1019)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:76)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.svm.graal.hosted.GraalFeature.processMethod(GraalFeature.java:539)
	at com.oracle.svm.graal.hosted.GraalFeature.duringAnalysis(GraalFeature.java:484)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$14(NativeImageGenerator.java:765)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:71)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:765)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:582)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:495)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.getTargetClass(AnnotationSubstitutionProcessor.java:867)
	at com.oracle.svm.hosted.snippets.SubstrateGraphBuilderPlugins.extractClassArray(SubstrateGraphBuilderPlugins.java:383)
	at com.oracle.svm.hosted.snippets.ReflectionPlugins.unbox(ReflectionPlugins.java:395)
	at com.oracle.svm.hosted.snippets.ReflectionPlugins.foldInvocationUsingReflection(ReflectionPlugins.java:354)
	at com.oracle.svm.hosted.snippets.ReflectionPlugins.access$200(ReflectionPlugins.java:92)
	at com.oracle.svm.hosted.snippets.ReflectionPlugins$5.defaultHandler(ReflectionPlugins.java:327)
	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.graphbuilderconf.InvocationPlugin.apply(InvocationPlugin.java:99)
	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.graphbuilderconf.InvocationPlugin.execute(InvocationPlugin.java:169)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.applyInvocationPlugin(BytecodeParser.java:2220)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.tryInvocationPlugin(BytecodeParser.java:2206)
	at com.oracle.svm.graal.hosted.GraalFeature$RuntimeBytecodeParser.tryInvocationPlugin(GraalFeature.java:269)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1912)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genDynamicInvokeHelper(BytecodeParser.java:1784)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1734)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1719)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5446)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3451)
	... 22 more
Error: Image build request failed with exit status 1
```

![image](https://user-images.githubusercontent.com/2368856/114375296-cea76f80-9b84-11eb-8b3c-9e3e28febb52.png)

![image](https://user-images.githubusercontent.com/2368856/114375324-d36c2380-9b84-11eb-8c7a-e5d7eb0476ef.png)

Here's the line that is not being processed correctly:
https://github.com/graalvm/labs-openjdk-11/blob/a2cebf5e08f0afd07508f47123b94700ce914c37/src/java.base/share/classes/sun/nio/ch/Util.java#L414

**Comment by fniephaus** [comment]
@cstancu any way you could have a look at this before the 21.1 release? It seems we will no longer be able to build TruffleSqueak with Native Image until this is fixed.

**Comment by fniephaus** [comment]
Using git bisect, I found out that https://github.com/oracle/graal/commit/a0ea2cdee4a5569b686660e9c681a3454e4c02e7 caused issues with out SqueakSSL plugin because [some boundaries were missing](https://github.com/hpi-swa/trufflesqueak/commit/2a267daf9d292e25d69094cff03fd2b465a21a8c). With those boundaries in place, compilation succeeds again. So this is no longer a blocker for us. Nonetheless, I'll keep this open because we should make sure that the usual "blacklisted method reached" errors should not be masked with some obscure BytecodeParserError.
