### ISSUE TITLE
Error: Frame states being merged are incompatible

### ISSUE THREAD

**Issue by smallshen** [oracle/graal#3342]
```
Error: Frame states being merged are incompatible: unbalanced monitors - locked objects do not match
 This frame state: [locals: [1,2,67,57,80,82,83,83,83,83,5] stack: [108] locks: [93 / 84] rethrowException]
Other frame state: [locals: [1,2,183,184,317,318,319,319,319,319,5] stack: [320] locks: [321 / 294] rethrowException]
Parser context: androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invokeSuspend(Recomposer.kt:402) [bci: 167, intrinsic: false]
 167: invokestatic  #11         // androidx.compose.runtime.Recomposer.access$getHasFrameWorkLocked:(androidx.compose.runtime.Recomposer)boolean
 170: ifne          194
 173: aload         5
 175: invokestatic  #12         // androidx.compose.runtime.Recomposer.access$recordComposerModificationsLocked:(androidx.compose.runtime.Recomposer)void

Detailed message:
Call path from entry point to androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invokeSuspend(Object):
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invokeSuspend(Recomposer.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:137)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1676)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1426)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1387)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1374)
        at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1858)
```
In compatible with coroutines in Jetpack Compose Desktop when adding "--no-fallback" option for generating native image

Version: graalvm-ce-java11-21.0.0.2

**Comment by smallshen** [comment]
Full Log
```
[EridaniLauncher-windows-x64-1.0.0:90212]    classlist:   1,339.20 ms,  0.96 GB
[EridaniLauncher-windows-x64-1.0.0:90212]        (cap):   1,580.64 ms,  0.96 GB
[EridaniLauncher-windows-x64-1.0.0:90212]        setup:   3,381.44 ms,  0.96 GB
[EridaniLauncher-windows-x64-1.0.0:90212]     (clinit):     530.17 ms,  3.25 GB
[EridaniLauncher-windows-x64-1.0.0:90212]   (typeflow):  12,187.71 ms,  3.25 GB
[EridaniLauncher-windows-x64-1.0.0:90212]    (objects):  11,364.92 ms,  3.25 GB
[EridaniLauncher-windows-x64-1.0.0:90212]   (features):     659.83 ms,  3.25 GB
[EridaniLauncher-windows-x64-1.0.0:90212]     analysis:  25,441.32 ms,  3.25 GB
Error: Frame states being merged are incompatible: unbalanced monitors - locked objects do not match
 This frame state: [locals: [1,2,67,57,80,82,83,83,83,83,5] stack: [108] locks: [93 / 84] rethrowException]
Other frame state: [locals: [1,2,183,184,317,318,319,319,319,319,5] stack: [320] locks: [321 / 294] rethrowException]
Parser context: androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invokeSuspend(Recomposer.kt:402) [bci: 167, intrinsic: false]
 167: invokestatic  #11         // androidx.compose.runtime.Recomposer.access$getHasFrameWorkLocked:(androidx.compose.runtime.Recomposer)boolean
 170: ifne          194
 173: aload         5
 175: invokestatic  #12         // androidx.compose.runtime.Recomposer.access$recordComposerModificationsLocked:(androidx.compose.runtime.Recomposer)void

Detailed message:
Call path from entry point to androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invokeSuspend(Object):
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invokeSuspend(Recomposer.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:137)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1

```

**Comment by smallshen** [comment]
```
[EridaniLauncher-windows-x64-1.0.0:121600]    classlist:   1,466.17 ms,  0.96 GB
[EridaniLauncher-windows-x64-1.0.0:121600]        (cap):   1,514.25 ms,  0.96 GB
[EridaniLauncher-windows-x64-1.0.0:121600]        setup:   3,272.85 ms,  0.96 GB
[EridaniLauncher-windows-x64-1.0.0:121600]     (clinit):     452.96 ms,  3.25 GB
[EridaniLauncher-windows-x64-1.0.0:121600]   (typeflow):  11,234.08 ms,  3.25 GB
[EridaniLauncher-windows-x64-1.0.0:121600]    (objects):  10,943.67 ms,  3.25 GB
[EridaniLauncher-windows-x64-1.0.0:121600]   (features):     615.83 ms,  3.25 GB
[EridaniLauncher-windows-x64-1.0.0:121600]     analysis:  23,957.98 ms,  3.25 GB
Error: Frame states being merged are incompatible: unbalanced monitors - locked objects do not match
 This frame state: [locals: [1,2,67,57,80,82,83,83,83,83,5] stack: [108] locks: [93 / 84] rethrowException]
Other frame state: [locals: [1,2,183,184,317,318,319,319,319,319,5] stack: [320] locks: [321 / 294] rethrowException]
Parser context: androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invokeSuspend(Recomposer.kt:402) [bci: 167, intrinsic: false]
 167: invokestatic  #11         // androidx.compose.runtime.Recomposer.access$getHasFrameWorkLocked:(androidx.compose.runtime.Recomposer)boolean
 170: ifne          194
 173: aload         5
 175: invokestatic  #12         // androidx.compose.runtime.Recomposer.access$recordComposerModificationsLocked:(androidx.compose.runtime.Recomposer)void

Detailed message:
Call path from entry point to androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invokeSuspend(Object):
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invokeSuspend(Recomposer.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:137)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

com.oracle.svm.core.util.UserError$UserException: Frame states being merged are incompatible: unbalanced monitors - locked objects do not match
 This frame state: [locals: [1,2,67,57,80,82,83,83,83,83,5] stack: [108] locks: [93 / 84] rethrowException]
Other frame state: [locals: [1,2,183,184,317,318,319,319,319,319,5] stack: [320] locks: [321 / 294] rethrowException]
Parser context: androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invokeSuspend(Recomposer.kt:402) [bci: 167, intrinsic: false]
 167: invokestatic  #11         // androidx.compose.runtime.Recomposer.access$getHasFrameWorkLocked:(androidx.compose.runtime.Recomposer)boolean
 170: ifne          194
 173: aload         5
 175: invokestatic  #12         // androidx.compose.runtime.Recomposer.access$recordComposerModificationsLocked:(androidx.compose.runtime.Recomposer)void

Detailed message:
Call path from entry point to androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invokeSuspend(Object):
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invokeSuspend(Recomposer.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:137)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

        at com.oracle.svm.core.util.UserError.abort(UserError.java:82)
        at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:233)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:773)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:563)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Frame states being merged are incompatible: unbalanced monitors - locked objects do not match
 This frame state: [locals: [1,2,67,57,80,82,83,83,83,83,5] stack: [108] locks: [93 / 84] rethrowException]
Other frame state: [locals: [1,2,183,184,317,318,319,319,319,319,5] stack: [320] locks: [321 / 294] rethrowException]
Parser context: androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invokeSuspend(Recomposer.kt:402) [bci: 167, intrinsic: false]
 167: invokestatic  #11         // androidx.compose.runtime.Recomposer.access$getHasFrameWorkLocked:(androidx.compose.runtime.Recomposer)boolean
 170: ifne          194
 173: aload         5
 175: invokestatic  #12         // androidx.compose.runtime.Recomposer.access$recordComposerModificationsLocked:(androidx.compose.runtime.Recomposer)void

Detailed message:
Call path from entry point to androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invokeSuspend(Object):
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invokeSuspend(Recomposer.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:137)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

        at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:770)
        ... 8 more
Caused by: org.graalvm.compiler.core.common.PermanentBailoutException: Frame states being merged are incompatible: unbalanced monitors - locked objects do not match
 This frame state: [locals: [1,2,67,57,80,82,83,83,83,83,5] stack: [108] locks: [93 / 84] rethrowException]
Other frame state: [locals: [1,2,183,184,317,318,319,319,319,319,5] stack: [320] locks: [321 / 294] rethrowException]
Parser context: androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invokeSuspend(Recomposer.kt:402) [bci: 167, intrinsic: false]
 167: invokestatic  #11         // androidx.compose.runtime.Recomposer.access$getHasFrameWorkLocked:(androidx.compose.runtime.Recomposer)boolean
 170: ifne          194
 173: aload         5
 175: invokestatic  #12         // androidx.compose.runtime.Recomposer.access$recordComposerModificationsLocked:(androidx.compose.runtime.Recomposer)void

        at jdk.internal.vm.compiler/org.graalvm.compiler.java.FrameStateBuilder.checkCompatibleWith(FrameStateBuilder.java:419)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.FrameStateBuilder.merge(FrameStateBuilder.java:428)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.createTarget(BytecodeParser.java:3185)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.createTarget(BytecodeParser.java:3093)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.createHandleExceptionTarget(BytecodeParser.java:1360)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.handleException(BytecodeParser.java:1337)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.updateWithExceptionNode(BytecodeParser.java:2944)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.updateLastInstruction(BytecodeParser.java:2935)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.append(BytecodeParser.java:2919)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.graphbuilderconf.GraphBuilderContext.add(GraphBuilderContext.java:116)
        at com.oracle.svm.hosted.phases.SubstrateClassInitializationPlugin.emitEnsureClassInitialized(SubstrateClassInitializationPlugin.java:79)
        at com.oracle.svm.hosted.phases.SubstrateClassInitializationPlugin.apply(SubstrateClassInitializationPlugin.java:64)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1650)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1634)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5406)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3436)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3243)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1109)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1003)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:76)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:223)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:357)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:313)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:302)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
        at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultSpecialInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:368)
        at com.oracle.graal.pointsto.flow.TypeFlow$1.run(TypeFlow.java:433)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        ... 5 more
Error: Image build request failed with exit status 1
```

**Comment by mcraj017** [comment]
@smallshen please provide reproducer

**Comment by smallshen** [comment]
[EridaniLauncher-windows-x64-1.0.0.jar.zip](https://github.com/oracle/graal/files/6328826/EridaniLauncher-windows-x64-1.0.0.jar.zip)
It is built with kotlin 1.4.32, compose desktop version is v0.4.0-build183

**Comment by smallshen** [comment]
I think the problem is the native compiler can not recognize the loop in kotlin coroutines. I tested with another jar made with jetpack compose it throws error of 
```
Error: Non-reducible loop requires too much duplication
Call path from entry point to androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapGestures$2$1.invokeSuspend(Object):
```

**Comment by ScottPierce** [comment]
Seeing this also.

**Comment by smallshen** [comment]
any progress?

**Comment by mcraj017** [comment]
@smallshen I have raised this issue with our dev team, please wait for their response

**Comment by smallshen** [comment]
https://github.com/oracle/graal/issues/3358
I think this issue has same problem.

**Comment by davleopo** [comment]
Hi @smallshen , thanks for the report. Do you know if the problem reproduces on linux as well ? Having a linux reproducer would simplify the investigations.

**Comment by smallshen** [comment]
@davleopo
[JetpackComposeMinimumExample.zip](https://github.com/oracle/graal/files/6462384/JetpackComposeMinimumExample.zip)
This is a small example with Jetpack Compose
use task "packageUberJarForCurrentOS" to create a fat jar.
The final jar file should be in build/compose/jars

**Comment by smallshen** [comment]
> Hi @smallshen , thanks for the report. Do you know if the problem reproduces on linux as well ? Having a linux reproducer would simplify the investigations.

Also it requires java 11+ to run

**Comment by davleopo** [comment]
@smallshen thanks for the minimum example, I can reproduce the error locally, Ill dig in and get back to you once I have a fix/workaround.

**Comment by smallshen** [comment]
I will do my best to provide you with the information if you need more

**Comment by smallshen** [comment]
It should be the problem of kotlin coroutines, not only in jetpack compose, could be anywhere

**Comment by davleopo** [comment]
@smallshen  a fix for this went in some time ago. Can you still reproduce the issue?

**Comment by smallshen** [comment]
It is solved, which leads to another problem in awt library loading
```
Cannot open (null)\bin\jawt.dll
```

**Comment by smallshen** [comment]
Should I open a new issue?

**Comment by ScottPierce** [comment]
Yes, please open another issue and link it here so I can follow that as
well :)

**Comment by smallshen** [comment]
Ok, new Issue link
https://github.com/oracle/graal/issues/3807
