### ISSUE TITLE
Illegal char <:> with generated native-image configuration

### ISSUE THREAD

**Issue by smallshen** [oracle/graal#3343]
Generating configuration for jar with agentlib  ```-agentlib:native-image-agent=config-output-dir=./config/```
```
Fatal error:java.nio.file.InvalidPathException: Illegal char <:> at index 2: –H:ConfigurationFileDirectories=./config/.obj
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.resolve(Path.java:515)
        at com.oracle.svm.hosted.image.NativeBootImageViaCC.write(NativeBootImageViaCC.java:404)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:685)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
```

Version: graalvm-ce-java11-21.0.0.2

**Comment by mcraj017** [comment]
@smallshen try this
java -agentlib:native-image-agent=config-output-dir=META-INF/native-image

**Comment by smallshen** [comment]
![image](https://user-images.githubusercontent.com/39912494/115020877-d31fa100-9e80-11eb-9436-9020fafd444b.png)

**Comment by mcraj017** [comment]
@smallshen As error states create META-INF\native-image directory
`mkdir -p META-INF\native-image`

**Comment by smallshen** [comment]
this is more like a parse error instead of directory error

**Comment by mcraj017** [comment]
@smallshen please follow the doc in the below link
https://docs.oracle.com/en/graalvm/enterprise/19/guide/reference/native-image/tracing-agent.html

**Comment by mcraj017** [comment]
if you still face some error
Please provide reproducer

**Comment by smallshen** [comment]
https://github.com/oracle/graal/issues/3342#issuecomment-821786690
The same one

**Comment by mcraj017** [comment]
ok so closing this issue
We will follow there

**Comment by smallshen** [comment]
this is solved in new version of release

**Comment by liudonghua123** [comment]
I tried with the latest graalvm (GraalVM CE 21+35.1) and native.maven.plugin (0.9.26). But it's the same.

<details><summary>Details</summary>

```
D:\code\java\fun_player>java -version
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
openjdk version "21" 2023-09-19
OpenJDK Runtime Environment GraalVM CE 21+35.1 (build 21+35-jvmci-23.1-b15)
OpenJDK 64-Bit Server VM GraalVM CE 21+35.1 (build 21+35-jvmci-23.1-b15, mixed mode, sharing)

D:\code\java\fun_player>native-image.cmd --version
native-image 21 2023-09-19
GraalVM Runtime Environment GraalVM CE 21+35.1 (build 21+35-jvmci-23.1-b15)
Substrate VM GraalVM CE 21+35.1 (build 21+35, serial gc)

D:\code\java\fun_player>
D:\code\java\fun_player>mvn -Pnative -Dagent package -e
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] Found GraalVM installation from GRAALVM_HOME variable.
[INFO]
[INFO] ----------------< com.liudonghua.examples:midi_player >-----------------
[INFO] Building midi_player 0.1.0
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- resources:3.3.0:resources (default-resources) @ midi_player ---
[INFO] skip non existing resourceDirectory D:\code\java\fun_player\src\main\resources
[INFO]
[INFO] --- compiler:3.8.1:compile (default-compile) @ midi_player ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- resources:3.3.0:testResources (default-testResources) @ midi_player ---
[INFO] skip non existing resourceDirectory D:\code\java\fun_player\src\test\resources
[INFO]
[INFO] --- compiler:3.8.1:testCompile (default-testCompile) @ midi_player ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- surefire:3.0.0-M8:test (default-test) @ midi_player ---
[WARNING] Parameter 'systemProperties' is deprecated: Use systemPropertyVariables instead.
[INFO] Surefire report directory: D:\code\java\fun_player\target\surefire-reports
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
[INFO] Running com.liudonghua.examples.AppTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.09 s - in com.liudonghua.examples.AppTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- native:0.9.26:merge-agent-files (test-native) @ midi_player ---
[INFO] Merging agent 2 files into D:\code\java\fun_player\target\native\agent-output\test
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
[INFO]
[INFO] --- native:0.9.26:test (test-native) @ midi_player ---
[INFO] ====================
[INFO] Initializing project: midi_player
[INFO] ====================
[INFO] Executing: D:\apps\graalvm-community-openjdk-21+35.1\bin\native-image.cmd @target\tmp\native-image-3104926618333443292.args org.graalvm.junit.platform.NativeImageJUnitLauncher
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <
> at index 10: D:codejava
un_player       argetclasses
        at java.base@21/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:204)
        at java.base@21/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
        at java.base@21/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base@21/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base@21/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
        at java.base@21/java.nio.file.Path.of(Path.java:148)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.expandAsteriskClassPathElement(NativeImage.java:2156)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.addCustomImageClasspath(NativeImage.java:2135)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.DefaultOptionHandler.processClasspathArgs(DefaultOptionHandler.java:231)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.DefaultOptionHandler.consume(DefaultOptionHandler.java:68)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage$NativeImageArgsProcessor.apply(NativeImage.java:2061)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.processNativeImageArgs(NativeImage.java:2368)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.completeImageBuild(NativeImage.java:1054)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.build(NativeImage.java:1913)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1878)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.main(NativeImage.java:1852)
        at java.base@21/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.847 s
[INFO] Finished at: 2023-09-20T10:19:11+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.26:test (test-native) on project midi_player: Execution of D:\apps\graalvm-community-openjdk-21+35.1\bin\native-image.cmd @target\tmp\native-image-3104926618333443292.args org.graalvm.junit.platform.NativeImageJUnitLauncher returned non-zero result -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.26:test (test-native) on project midi_player: Execution of D:\apps\graalvm-community-openjdk-21+35.1\bin\native-image.cmd @target\tmp\native-image-3104926618333443292.args org.graalvm.junit.platform.NativeImageJUnitLauncher returned non-zero result
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:347)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:330)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:175)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:76)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:163)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:160)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:260)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:172)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:100)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:821)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:270)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: Execution of D:\apps\graalvm-community-openjdk-21+35.1\bin\native-image.cmd @target\tmp\native-image-3104926618333443292.args org.graalvm.junit.platform.NativeImageJUnitLauncher returned non-zero result
    at org.graalvm.buildtools.maven.AbstractNativeImageMojo.buildImage (AbstractNativeImageMojo.java:418)
    at org.graalvm.buildtools.maven.NativeTestMojo.execute (NativeTestMojo.java:150)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:342)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:330)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:175)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:76)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:163)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:160)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:260)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:172)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:100)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:821)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:270)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

D:\code\java\fun_player>
```

</details>

**Comment by liudonghua123** [comment]
I updated native.maven.plugin (0.9.27). The path separator changed from `\` to `\\` in `@target\tmp\native-image-xxx.args`, and this error disappeared.

<details><summary>Details</summary>

```
D:\code\java\fun_player>mvn -Pnative -Dagent package -e
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
Downloading from nexus-aliyun: http://maven.aliyun.com/nexus/content/groups/public/org/graalvm/buildtools/native-maven-plugin/0.9.27/native-maven-plugin-0.9.27.pom
Downloaded from nexus-aliyun: http://maven.aliyun.com/nexus/content/groups/public/org/graalvm/buildtools/native-maven-plugin/0.9.27/native-maven-plugin-0.9.27.pom (3.1 kB at 1.9 kB/s)
Downloading from nexus-aliyun: http://maven.aliyun.com/nexus/content/groups/public/org/graalvm/buildtools/junit-platform-native/0.9.27/junit-platform-native-0.9.27.pom
Downloaded from nexus-aliyun: http://maven.aliyun.com/nexus/content/groups/public/org/graalvm/buildtools/junit-platform-native/0.9.27/junit-platform-native-0.9.27.pom (2.5 kB at 5.4 kB/s)
Downloading from nexus-aliyun: http://maven.aliyun.com/nexus/content/groups/public/org/graalvm/buildtools/utils/0.9.27/utils-0.9.27.pom
Downloaded from nexus-aliyun: http://maven.aliyun.com/nexus/content/groups/public/org/graalvm/buildtools/utils/0.9.27/utils-0.9.27.pom (1.9 kB at 4.0 kB/s)
Downloading from nexus-aliyun: http://maven.aliyun.com/nexus/content/groups/public/org/graalvm/buildtools/graalvm-reachability-metadata/0.9.27/graalvm-reachability-metadata-0.9.27.pom
Downloaded from nexus-aliyun: http://maven.aliyun.com/nexus/content/groups/public/org/graalvm/buildtools/graalvm-reachability-metadata/0.9.27/graalvm-reachability-metadata-0.9.27.pom (2.0 kB at 4.2 kB/s)
Downloading from nexus-aliyun: http://maven.aliyun.com/nexus/content/groups/public/org/graalvm/buildtools/native-maven-plugin/0.9.27/native-maven-plugin-0.9.27.jar
Downloading from nexus-aliyun: http://maven.aliyun.com/nexus/content/groups/public/org/graalvm/buildtools/junit-platform-native/0.9.27/junit-platform-native-0.9.27.jar
Downloading from nexus-aliyun: http://maven.aliyun.com/nexus/content/groups/public/org/graalvm/buildtools/utils/0.9.27/utils-0.9.27.jar
Downloading from nexus-aliyun: http://maven.aliyun.com/nexus/content/groups/public/org/graalvm/buildtools/graalvm-reachability-metadata/0.9.27/graalvm-reachability-metadata-0.9.27.jar
Downloaded from nexus-aliyun: http://maven.aliyun.com/nexus/content/groups/public/org/graalvm/buildtools/native-maven-plugin/0.9.27/native-maven-plugin-0.9.27.jar (82 kB at 112 kB/s)
Downloaded from nexus-aliyun: http://maven.aliyun.com/nexus/content/groups/public/org/graalvm/buildtools/utils/0.9.27/utils-0.9.27.jar (30 kB at 39 kB/s)
Downloaded from nexus-aliyun: http://maven.aliyun.com/nexus/content/groups/public/org/graalvm/buildtools/junit-platform-native/0.9.27/junit-platform-native-0.9.27.jar (26 kB at 29 kB/s)
Downloaded from nexus-aliyun: http://maven.aliyun.com/nexus/content/groups/public/org/graalvm/buildtools/graalvm-reachability-metadata/0.9.27/graalvm-reachability-metadata-0.9.27.jar (26 kB at 29 kB/s)
[INFO] Found GraalVM installation from GRAALVM_HOME variable.
[INFO]
[INFO] ----------------< com.liudonghua.examples:midi_player >-----------------
[INFO] Building midi_player 0.1.0
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- resources:3.3.0:resources (default-resources) @ midi_player ---
[INFO] skip non existing resourceDirectory D:\code\java\fun_player\src\main\resources
[INFO]
[INFO] --- compiler:3.8.1:compile (default-compile) @ midi_player ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- resources:3.3.0:testResources (default-testResources) @ midi_player ---
[INFO] skip non existing resourceDirectory D:\code\java\fun_player\src\test\resources
[INFO]
[INFO] --- compiler:3.8.1:testCompile (default-testCompile) @ midi_player ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- surefire:3.0.0-M8:test (default-test) @ midi_player ---
[WARNING] Parameter 'systemProperties' is deprecated: Use systemPropertyVariables instead.
[INFO] Surefire report directory: D:\code\java\fun_player\target\surefire-reports
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
[INFO] Running com.liudonghua.examples.AppTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.088 s - in com.liudonghua.examples.AppTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- native:0.9.27:merge-agent-files (test-native) @ midi_player ---
[INFO] Merging agent 1 files into D:\code\java\fun_player\target\native\agent-output\test
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
[INFO]
[INFO] --- native:0.9.27:test (test-native) @ midi_player ---
[INFO] ====================
[INFO] Initializing project: midi_player
[INFO] ====================
[INFO] Executing: D:\apps\graalvm-community-openjdk-21+35.1\bin\native-image.cmd @target\tmp\native-image-1341272611514530189.args org.graalvm.junit.platform.NativeImageJUnitLauncher
Warning: The option '-H:DashboardDump=fortune' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: The option '-H:+DashboardAll' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: Please re-evaluate whether any experimental option is required, and either remove or unlock it. The build output lists all active experimental options, including where they come from and possible alternatives. If you think an experimental option should be considered as stable, please file an issue.
========================================================================================================================
GraalVM Native Image: Generating 'native-tests.exe' (executable)...
========================================================================================================================
For detailed information and explanations on the build output, visit:
https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/BuildOutput.md
------------------------------------------------------------------------------------------------------------------------
# Printing Dashboard BGV dump header to: D:\code\java\fun_player\fortune.bgv
[1/8] Initializing...                                                                                    (7.3s @ 0.07GB)
 Java version: 21+35, vendor version: GraalVM CE 21+35.1
 Graal compiler: optimization level: 2, target machine: x86-64-v3
 C compiler: cl.exe (microsoft, x64, 19.37.32822)
 Garbage collector: Serial GC (max heap size: 80% of RAM)
 2 user-specific feature(s):
 - com.oracle.svm.thirdparty.gson.GsonFeature
 - org.graalvm.junit.platform.JUnitPlatformFeature
------------------------------------------------------------------------------------------------------------------------
 2 experimental option(s) unlocked:
 - '-H:+DashboardAll' (origin(s): command line)
 - '-H:DashboardDump' (origin(s): command line)
------------------------------------------------------------------------------------------------------------------------
Build resources:
 - 12.03GB of memory (75.6% of 15.92GB system memory, determined at start)
 - 8 thread(s) (100.0% of 8 available processor(s), determined at start)
[junit-platform-native] Running in 'test listener' mode using files matching pattern [junit-platform-unique-ids*] found in folder [D:\code\java\fun_player\target\test-ids] and its subfolders.
[2/8] Performing analysis...  []                                                                        (24.9s @ 0.48GB)
    6,573 reachable types   (81.4% of    8,072 total)
    9,191 reachable fields  (58.7% of   15,647 total)
   30,370 reachable methods (53.3% of   56,992 total)
    2,117 types,   214 fields, and 1,180 methods registered for reflection
        2 native libraries: crypt32, ncrypt
# Printing Dashboard PointsTo analysis BGV dump to: D:\code\java\fun_player\fortune.bgv
Print of Dashboard dump output ended.

Error: Classes that should be initialized at run time got initialized during image building:
 org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry was unintentionally initialized at build time. To see why org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry got initialized use --trace-class-initialization=org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry
org.junit.platform.launcher.core.ServiceLoaderRegistry was unintentionally initialized at build time. To see why org.junit.platform.launcher.core.ServiceLoaderRegistry got initialized use --trace-class-initialization=org.junit.platform.launcher.core.ServiceLoaderRegistry
org.junit.platform.launcher.core.EngineIdValidator was unintentionally initialized at build time. To see why org.junit.platform.launcher.core.EngineIdValidator got initialized use --trace-class-initialization=org.junit.platform.launcher.core.EngineIdValidator
To see how the classes got initialized, use --trace-class-initialization=org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry,org.junit.platform.launcher.core.ServiceLoaderRegistry,org.junit.platform.launcher.core.EngineIdValidator
------------------------------------------------------------------------------------------------------------------------
                       4.7s (11.9% of total time) in 180 GCs | Peak RSS: 1.47GB | CPU load: 4.41
========================================================================================================================
Finished generating 'native-tests.exe' in 38.2s.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  51.593 s
[INFO] Finished at: 2023-09-20T10:29:09+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.27:test (test-native) on project midi_player: Execution of D:\apps\graalvm-community-openjdk-21+35.1\bin\native-image.cmd @target\tmp\native-image-1341272611514530189.args org.graalvm.junit.platform.NativeImageJUnitLauncher returned non-zero result -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.27:test (test-native) on project midi_player: Execution of D:\apps\graalvm-community-openjdk-21+35.1\bin\native-image.cmd @target\tmp\native-image-1341272611514530189.args org.graalvm.junit.platform.NativeImageJUnitLauncher returned non-zero result
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:347)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:330)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:175)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:76)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:163)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:160)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:260)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:172)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:100)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:821)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:270)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: Execution of D:\apps\graalvm-community-openjdk-21+35.1\bin\native-image.cmd @target\tmp\native-image-1341272611514530189.args org.graalvm.junit.platform.NativeImageJUnitLauncher returned non-zero result
    at org.graalvm.buildtools.maven.AbstractNativeImageMojo.buildImage (AbstractNativeImageMojo.java:418)
    at org.graalvm.buildtools.maven.NativeTestMojo.execute (NativeTestMojo.java:150)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:342)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:330)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:175)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:76)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:163)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:160)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:260)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:172)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:100)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:821)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:270)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

D:\code\java\fun_player>
```
</details>
