### ISSUE TITLE
Regression with Micronaut when using POJOs from other modules

### ISSUE THREAD

**Issue by ilopmar** [oracle/graal#3347]
**Describe the issue**

We've detected in Micronaut a regression with a test application we have. It is a multi-project build. There is a `core` module that only has a POJO and then, then POJO is used in a Micronaut application in a controller.
Some time ago the application started to fail with a `java.lang.NoClassDefFoundError: example.micronaut.pojo.Book` when the Micronaut app starts.

It seems that GraalVM is doing something different or some reflective loading. More context in https://github.com/micronaut-projects/micronaut-core/issues/5164

**Steps to reproduce the issue**

- `git clone https://github.com/micronaut-graal-tests/micronaut-introspected-graal`
- `cd micronaut-introspected-graal`
- `git checkout issue-graalvm`
- Use GraalVM SDK
- `./build-native-image.sh`
- `./app/build/native-image/introspected`
- The application starts to fail. See error below.

**Describe GraalVM and your environment:**

 - GraalVM version: **21.0.0.2** and daily in our CI with `master` and `release/graal-vm/21.1` branches
 - JDK major version: **8** and **11**
 - OS: **Linux Mint 20.1**
 - Architecture: **AMD64**

**More details**

Error when starting the application:

```
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v2.4.3-SNAPSHOT)

15:20:56.259 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error instantiating bean of type  [io.micronaut.http.server.netty.NettyHttpServer]

Message: example.micronaut.pojo.Book
Path Taken: new NettyHttpServer(NettyHttpServerConfiguration serverConfiguration,ApplicationContext applicationContext,[Router router],RequestArgumentSatisfier requestArgumentSatisfier,MediaTypeCodecRegistry mediaTypeCodecRegistry,NettyCustomizableResponseTypeHandlerRegistry customizableResponseTypeHandlerRegistry,StaticResourceResolver resourceResolver,BeanProvider ioExecutor,ThreadFactory threadFactory,ExecutorSelector executorSelector,ServerSslBuilder serverSslBuilder,List outboundHandlers,EventLoopGroupFactory eventLoopGroupFactory,EventLoopGroupRegistry eventLoopGroupRegistry,HttpCompressionStrategy httpCompressionStrategy,HttpContentProcessorResolver httpContentProcessorResolver,ChannelOptionFactory channelOptionFactory,ErrorResponseProcessor errorResponseProcessor)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.http.server.netty.NettyHttpServer]

Message: example.micronaut.pojo.Book
Path Taken: new NettyHttpServer(NettyHttpServerConfiguration serverConfiguration,ApplicationContext applicationContext,[Router router],RequestArgumentSatisfier requestArgumentSatisfier,MediaTypeCodecRegistry mediaTypeCodecRegistry,NettyCustomizableResponseTypeHandlerRegistry customizableResponseTypeHandlerRegistry,StaticResourceResolver resourceResolver,BeanProvider ioExecutor,ThreadFactory threadFactory,ExecutorSelector executorSelector,ServerSslBuilder serverSslBuilder,List outboundHandlers,EventLoopGroupFactory eventLoopGroupFactory,EventLoopGroupRegistry eventLoopGroupRegistry,HttpCompressionStrategy httpCompressionStrategy,HttpContentProcessorResolver httpContentProcessorResolver,ChannelOptionFactory channelOptionFactory,ErrorResponseProcessor errorResponseProcessor)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1970)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2724)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2710)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2382)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2356)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1261)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1012)
	at io.micronaut.http.server.netty.$NettyHttpServerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1943)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2724)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2710)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2382)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2356)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1282)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:752)
	at io.micronaut.context.BeanLocator.findBean(BeanLocator.java:149)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:73)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:311)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:297)
	at micronaut.example.Application.main(Application.java:8)
Caused by: java.lang.NoClassDefFoundError: example.micronaut.pojo.Book
	at micronaut.example.$BookControllerDefinition$$exec1.<init>(Unknown Source)
	at micronaut.example.$BookControllerDefinition.<init>(Unknown Source)
	at micronaut.example.$BookControllerDefinition.<init>(Unknown Source)
	at micronaut.example.$BookControllerDefinitionClass.load(Unknown Source)
	at io.micronaut.context.AbstractBeanDefinitionReference.load(AbstractBeanDefinitionReference.java:62)
	at io.micronaut.context.DefaultBeanContext.lambda$getBeanDefinitions$13(DefaultBeanContext.java:1162)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.concurrent.ConcurrentLinkedQueue$CLQSpliterator.forEachRemaining(ConcurrentLinkedQueue.java:857)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at io.micronaut.context.DefaultBeanContext.getBeanDefinitions(DefaultBeanContext.java:1165)
	at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:64)
	at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:44)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2000)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3091)
	at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:2994)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:1059)
	at io.micronaut.context.AbstractBeanDefinition.doGetBeansOfType(AbstractBeanDefinition.java:1225)
	at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractBeanDefinition.java:1172)
	at io.micronaut.web.router.$DefaultRouterDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1943)
	... 19 common frames omitted
```

**Comment by mcraj017** [comment]
@ilopmar bug has been raised to dev team.

**Comment by christianwimmer** [comment]
I think the `Book` class is just not on the class path provided to the native image generator. Adding `--verbose` to the `native-image` command gives me the following class path (external dependencies omitted):
```
/home/cwimmer/Downloads/micronaut/micronaut-introspected-graal/core/build/libs/core.jar
/home/cwimmer/Downloads/micronaut/micronaut-introspected-graal/app/build/classes/java/main
/home/cwimmer/Downloads/micronaut/micronaut-introspected-graal/app/build/resources/main
```

But the file `core.jar` and the directory it is supposed to be in just don't exist.

**Comment by ilopmar** [comment]
Thank you so much for digging into this. I've tried building `core.jar` manually before trying to create the native image and it works as expected. I didn't think about this approach to try to figure it out.

This is some bug in our Gradle plugin.

Apologies for the noise.
