### ISSUE TITLE
ArrayIndexOutOfBoundsException in PolyglotContextImpl when parsing Python code in inner context

### ISSUE THREAD

**Issue by lucaswerkmeister** [oracle/graal#3372]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **21.1.0**
 - CE or EE: **CE**
 - JDK version: **JDK11**
 - OS and OS Version: **Arch Linux** (but also happens in [GitHub Actions](https://github.com/lucaswerkmeister/graaleneyj/runs/2409293428), Ubuntu 20.04.2)
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
OpenJDK 64-Bit Server VM (11.0.11+8-jvmci-21.1-b05) for linux-amd64 JRE (11.0.11+8-jvmci-21.1-b05), built on Apr 12 2021 15:17:53 by "buildslave" with gcc 7.3.0
```

**Have you verified this issue still happens when using the latest snapshot?**
No, but 21.1.0 was only released a few days ago and I saw nothing relevant in the recent GitHub issues, at least.

You can find snapshot builds here: https://github.com/graalvm/graalvm-ce-dev-builds/releases

**Describe the issue**
When my language tries to create an inner context and then parse and run some Python code in it, it gets an error.
```
org.graalvm.polyglot.PolyglotException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.invokeContextThreadFactory(PolyglotContextImpl.java:1982)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.invokeContextThreadLocalFactory(PolyglotContextImpl.java:1963)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureCreated(PolyglotLanguageContext.java:519)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureInitialized(PolyglotLanguageContext.java:586)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.getContextInitialized(PolyglotContextImpl.java:456)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.EngineAccessor$EngineImpl.parseForLanguage(EngineAccessor.java:243)
	at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$Env.parsePublic(TruffleLanguage.java:2520)
	at de.lucaswerkmeister.graaleneyj.runtime.ZContext.parse(ZContext.java:48)
	at de.lucaswerkmeister.graaleneyj.nodes.ZInnerContextNode.doGeneric(ZInnerContextNode.java:46)
	at de.lucaswerkmeister.graaleneyj.nodes.ZInnerContextNodeGen.executeAndSpecialize(ZInnerContextNodeGen.java:63)
	at de.lucaswerkmeister.graaleneyj.nodes.ZInnerContextNodeGen.execute(ZInnerContextNodeGen.java:43)
	at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:379)
	at de.lucaswerkmeister.graaleneyj.test.ZTest.eval(ZTest.java:33)
	at de.lucaswerkmeister.graaleneyj.test.CodePythonTest.testNandFalseFalse(CodePythonTest.java:28)
...
```

I have not yet tried to narrow this down.

Curiously enough, the same thing doesn’t happen when parsing JS code: that works just fine. However, there are no GraalPython classes in the stack trace, so I’m still reporting the issue here.

**Steps to reproduce the issue**
1. Clone https://github.com/lucaswerkmeister/graaleneyj/, including submodules
2. check out commit `a61f591a0cccdc158ede2ae5ade11d1e3bdf8c54` (current head, but I’ll probably revert it in a moment)
3. with `$JAVA_HOME` pointing to GraalVM 21.1.0 (with GraalPython installed), run `mvn test`

**Expected behavior**
The all tests pass.

**Additional context**

<details>
<summary>Code throwing the exception</summary>

The error happens in this method:

```java
    private void invokeContextThreadFactory(Object[] threadLocals, LocalLocation[] locations, Thread thread) {
        assert Thread.holdsLock(this);
        if (locations == null) {
            return;
        }
        try {
            for (int i = 0; i < locations.length; i++) {
                LocalLocation location = locations[i];
                if (threadLocals[location.index] == null) {
                    threadLocals[location.index] = location.invokeFactory(this, thread);
                }
            }
        } catch (Throwable t) {
            // reset values again the language failed to initialize                                                                                                                                                                           
            for (int i = 0; i < locations.length; i++) {
                threadLocals[locations[i].index] = null;
            }
            throw t;
        }
    }
```

It seems to be called with `threadLocals` and `locations` of different length.

</details>

**Comment by lucaswerkmeister** [comment]
<details>
<summary>Short reproducer</summary>

```java
import com.oracle.truffle.api.CallTarget;
import com.oracle.truffle.api.Truffle;
import com.oracle.truffle.api.TruffleContext;
import com.oracle.truffle.api.TruffleFile.FileTypeDetector;
import com.oracle.truffle.api.TruffleLanguage;
import com.oracle.truffle.api.TruffleLanguage.ContextPolicy;
import com.oracle.truffle.api.TruffleLanguage.ContextReference;
import com.oracle.truffle.api.TruffleLanguage.Env;
import com.oracle.truffle.api.TruffleLanguage.Provider;
import com.oracle.truffle.api.TruffleLanguage.Registration;
import com.oracle.truffle.api.dsl.Cached;
import com.oracle.truffle.api.dsl.CachedContext;
import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.frame.VirtualFrame;
import com.oracle.truffle.api.nodes.IndirectCallNode;
import com.oracle.truffle.api.nodes.Node;
import com.oracle.truffle.api.nodes.RootNode;
import com.oracle.truffle.api.source.Source;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.PolyglotAccess;

public class GraalIssue3372 {

    public static void main(String[] args) {
        Context context = Context.newBuilder()
            .allowPolyglotAccess(PolyglotAccess.ALL)
            .build();
        System.out.println(context.eval("my", "").toString());
    }

    @Registration(id = "my", name = "my language", contextPolicy = ContextPolicy.SHARED)
    public static class MyLanguageProvider implements Provider {

        @Override
        public String getLanguageClassName() {
            return "GraalIssue3372.MyLanguage";
        }

        @Override
        public TruffleLanguage<?> create() {
            return new MyLanguage();
        }

        @Override
        public List<FileTypeDetector> createFileTypeDetectors() {
            return Collections.emptyList();
        }

        @Override
        public Collection<String> getServicesClassNames() {
            return Collections.emptySet();
        }

    }

    public static class MyLanguage extends TruffleLanguage<MyContext> {

        @Override
        protected MyContext createContext(Env env) {
            return new MyContext(env);
        }

        @Override
        protected CallTarget parse(ParsingRequest request) throws Exception {
            return Truffle.getRuntime().createCallTarget(new MyRootNode(this));
        }
        
    }

    public static class MyContext {

        private final Env env;

        public MyContext(Env env) {
            this.env = env;
        }

        public TruffleContext makeInnerContext() {
            return env.newContextBuilder().build();
        }

        public CallTarget parse(Source source, String... argumentNames) {
            return env.parsePublic(source, argumentNames);
        }

    }

    public static class MyRootNode extends RootNode {

        @Child
        private MyNode node = new MyNode();

        public MyRootNode(MyLanguage language) {
            super(language);
        }

        @Override
        public Object execute(VirtualFrame virtualFrame) {
            return node.execute(virtualFrame);
        }

    }

    public static class MyNode extends Node {

        private final Source source = Source.newBuilder("python", "1", "").build();

        private final IndirectCallNode callNode = IndirectCallNode.create();

        public Object execute(VirtualFrame virtualFrame) {
            ContextReference<MyContext> contextReference = lookupContextReference(MyLanguage.class);
            MyContext outerMyContext = contextReference.get();
            TruffleContext innerTruffleContext = outerMyContext.makeInnerContext();
            Object outerTruffleContext = innerTruffleContext.enter(this);
            try {
                MyContext innerMyContext = contextReference.get();
                CallTarget callTarget = innerMyContext.parse(source);
                return callNode.call(callTarget, new Object[0]);
            } finally {
                innerTruffleContext.leave(this, outerTruffleContext);
                innerTruffleContext.close();
            }
        }

    }

}
```

</details>

Tarball (Makefile assumes GraalVM 11 is installed in `/usr/lib/jvm/java-11-graalvm`, as it would be using [jdk11-graalvm-bin](https://aur.archlinux.org/packages/jdk11-graalvm-bin/) + [graalpython-jdk11-bin](https://aur.archlinux.org/packages/graalpython-jdk11-bin); not sure if other distributions use the same directory structure): 
[graal-issue-3372.tar.gz](https://github.com/oracle/graal/files/6372784/graal-issue-3372.tar.gz)

**Comment by lucaswerkmeister** [comment]
On second thought, here’s an alternative tarball with a Makefile that should work on any system as long as `$JAVA_HOME` is set properly. (The `$JAVA_HOME` must not contain spaces or other shell special character, because Makefile.) The Java code is the same :)

[graal-issue-3372.tar.gz](https://github.com/oracle/graal/files/6372794/graal-issue-3372.tar.gz)

**Comment by lucaswerkmeister** [comment]
Still happens in [GraalVM CE 21.2.0-dev-20210430_1928](https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/21.2.0-dev-20210430_1928):

```console
$ cd /tmp
$ curl -L https://github.com/graalvm/graalvm-ce-dev-builds/releases/download/21.2.0-dev-20210430_1928/graalvm-ce-java11-linux-amd64-dev.tar.gz | tar xz                                                                                                                            
$ curl -L https://github.com/oracle/graal/files/6372794/graal-issue-3372.tar.gz | tar x
$ export JAVA_HOME=/tmp/graalvm-ce-java11-21.2.0-dev/
$ export PATH=$JAVA_HOME/bin:$PATH
$ gu install python
Downloading: Component catalog from raw.githubusercontent.com
Processing Component: Graal.Python
Processing Component: LLVM.org toolchain
Additional Components are required:
    LLVM.org toolchain (org.graalvm.llvm-toolchain, version 21.2.0-dev), required by: Graal.Python (org.graalvm.python)
Downloading: Component python: Graal.Python  from github.com
Downloading: Component org.graalvm.llvm-toolchain: LLVM.org toolchain  from github.com
Installing new component: LLVM.org toolchain (org.graalvm.llvm-toolchain, version 21.2.0-dev)
Installing new component: Graal.Python (org.graalvm.python, version 21.2.0-dev)

IMPORTANT NOTE:
---------------
Set of GraalVM components that provide language implementations have changed. The Polyglot native image and polyglot native C library may be out of sync: 
- new languages may not be accessible
- removed languages may cause the native binary to fail on missing resources or libraries.
To rebuild and refresh the native binaries, use the following command:
        /tmp/graalvm-ce-java11-21.2.0-dev/bin/gu rebuild-images

You may need to install "native-image" component which provide the rebuild tools.


$ make -C graal-issue-3372/
make: Entering directory '/tmp/graal-issue-3372'
/tmp/graalvm-ce-java11-21.2.0-dev//bin/javac -cp /tmp/graalvm-ce-java11-21.2.0-dev//lib/truffle/truffle-api.jar GraalIssue3372.java
/tmp/graalvm-ce-java11-21.2.0-dev//bin/jar cf my.jar META-INF/services/ META-INF/services/com.oracle.truffle.api.TruffleLanguage\$Provider GraalIssue3372.class GraalIssue3372\$MyLanguageProvider.class GraalIssue3372\$MyLanguage.class GraalIssue3372\$MyContext.class GraalIssue3372\$MyRootNode.class GraalIssue3372\$MyNode.class
/tmp/graalvm-ce-java11-21.2.0-dev//bin/java -Dtruffle.class.path.append=my.jar GraalIssue3372
Exception in thread "main" org.graalvm.polyglot.PolyglotException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.invokeContextThreadFactory(PolyglotContextImpl.java:1996)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.invokeContextThreadLocalFactory(PolyglotContextImpl.java:1977)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureCreated(PolyglotLanguageContext.java:519)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureInitialized(PolyglotLanguageContext.java:586)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.getContextInitialized(PolyglotContextImpl.java:459)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.EngineAccessor$EngineImpl.parseForLanguage(EngineAccessor.java:244)
        at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$Env.parsePublic(TruffleLanguage.java:2523)
        at GraalIssue3372$MyContext.parse(GraalIssue3372.java:86)
        at GraalIssue3372$MyNode.execute(GraalIssue3372.java:120)
        at GraalIssue3372$MyRootNode.execute(GraalIssue3372.java:102)
        at <my> null(Unknown)
        at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:379)
        at GraalIssue3372.main(GraalIssue3372.java:31)
Original Internal Error: 
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.invokeContextThreadFactory(PolyglotContextImpl.java:1996)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.invokeContextThreadLocalFactory(PolyglotContextImpl.java:1977)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureCreated(PolyglotLanguageContext.java:519)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureInitialized(PolyglotLanguageContext.java:586)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.getContextInitialized(PolyglotContextImpl.java:459)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.EngineAccessor$EngineImpl.parseForLanguage(EngineAccessor.java:244)
        at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$Env.parsePublic(TruffleLanguage.java:2523)
        at GraalIssue3372$MyContext.parse(GraalIssue3372.java:86)
        at GraalIssue3372$MyNode.execute(GraalIssue3372.java:120)
        at GraalIssue3372$MyRootNode.execute(GraalIssue3372.java:102)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:613)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:584)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:534)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:518)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:463)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:444)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:1053)
        at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:353)
        at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:379)
        at GraalIssue3372.main(GraalIssue3372.java:31)
Caused by: Attached Guest Language Frames (1)
make: *** [Makefile:4: all] Error 1
make: Leaving directory '/tmp/graal-issue-3372'
```

**Comment by mcraj017** [comment]
@lucaswerkmeister thanks for reporting the issue
I have raised the bug to our Dev team, they will respond to this shortly

**Comment by iamrecursion** [comment]
I've just encountered this one as well!

**Comment by lucaswerkmeister** [comment]
Still happens in GraalVM CE 21.2.0.

**Comment by jchalou** [comment]
I am looking into this
