### ISSUE TITLE
java.lang.NoClassDefFoundError: Ljava/lang/Object; when running native compiled binary

### ISSUE THREAD

**Issue by ehsmeng-graalvm** [oracle/graal#3374]
**Describe the issue**
Trying to compile Cassandra. Compilation works, but when running I get:
```
JNA: Problems loading core IDs: java.lang.Object
Exception (java.lang.NoClassDefFoundError) encountered during startup: Ljava/lang/Object;
java.lang.NoClassDefFoundError: Ljava/lang/Object;
	at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:345)
```
...

**Steps to reproduce the issue**
1. **https://github.com/ehsmeng-graalvm/odd/tree/master/3**
2. **./graal_compilation.sh**
3. **. run_binary.sh**

**Describe GraalVM and your environment:**
 - GraalVM version: **CE 21.2.0-dev (build 11.0.11+5-jvmci-21.1-b03)**
 - JDK major version: **11**
 - OS: **Ubuntu 20**
 - Architecture: **AMD64**

**More details**
```
JNA: Problems loading core IDs: java.lang.Object
Exception (java.lang.NoClassDefFoundError) encountered during startup: Ljava/lang/Object;
java.lang.NoClassDefFoundError: Ljava/lang/Object;
	at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:345)
	at com.oracle.svm.jni.JNIOnLoadFunctionPointer.invoke(JNILibraryInitializer.java)
	at com.oracle.svm.jni.JNILibraryInitializer.callOnLoadFunction(JNILibraryInitializer.java:72)
	at com.oracle.svm.jni.JNILibraryInitializer.initialize(JNILibraryInitializer.java:129)
	at com.oracle.svm.core.jdk.NativeLibrarySupport.addLibrary(NativeLibrarySupport.java:186)
	at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibrary0(NativeLibrarySupport.java:142)
	at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryAbsolute(NativeLibrarySupport.java:101)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:273)
	at java.lang.Runtime.load0(Runtime.java:768)
	at java.lang.System.load(System.java:1835)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
	at com.sun.jna.NativeLibrary.<clinit>(NativeLibrary.java:87)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
	at org.apache.cassandra.utils.NativeLibraryLinux.<clinit>(NativeLibraryLinux.java:55)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
	at org.apache.cassandra.utils.NativeLibrary.<clinit>(NativeLibrary.java:103)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:260)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:763)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:887)
```

**Comment by SergejIsbrecht** [comment]
@ehsmeng-graalvm ,

to me it seems, that Object is not registered with the JNI-Class-store, if I look in your JNI configuration at given repo:

https://github.com/ehsmeng-graalvm/odd/blob/master/3/magicator-native-image-conf/jni-config.json

```plain
[
  {
    "methods": [
      {
        "parameterTypes": [],
        "name": "getPlatformClassLoader"
      },
      {
        "parameterTypes": ["java.lang.String"],
        "name": "loadClass"
      }
    ],
    "name": "java.lang.ClassLoader"
  },
  {"name": "java.lang.ClassNotFoundException"},
  {"name": "java.lang.NoSuchMethodError"}
]
```

(JNI - Java Native Interface). It seems that a native library is loaded and it tries to to access the class Object, which is not in the JNI-Class-Store. Did you try running the Agent, which collects all classes accessed via reflection?

**Comment by ehsmeng-graalvm** [comment]
Hi, The directory run-native-image-conf/ is the output from tracing-agent, and the magicator-native-image-conf/ is generated by a tool.

Tracing agent didn't create many of the entries I need in the jni-conf.
```
{
  "name":"java.lang.Object"
},
{
  "name":"java.lang.Class"
},
{
  "name":"java.lang.reflect.Method"
},
{
  "name":"java.nio.Buffer"
},
{
  "name":"java.nio.ByteBuffer"
},
{
  "name":"java.nio.CharBuffer"
},
{
  "name":"java.nio.ShortBuffer"
},
{
  "name":"java.nio.IntBuffer"
},
{
  "name":"java.nio.LongBuffer"
},
...
```

I don't know if it was supposed to, or if I'm doing something wrong.
I added "run_old_trace.sh" to show how the tracing agent was run.

**Comment by ehsmeng-graalvm** [comment]
I updated jni-config and reflect-config (checked in) as far as possible and it ended up here:

```
16:44:00.921 [main] ERROR org.apache.cassandra.service.CassandraDaemon - Exception encountered during startup
java.lang.NoSuchMethodError: java.lang.Long.<init>(J)V
	at com.oracle.svm.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1104)
	at com.oracle.svm.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1089)
	at com.oracle.svm.jni.functions.JNIFunctions.GetMethodID(JNIFunctions.java:410)
	at com.oracle.svm.jni.JNIOnLoadFunctionPointer.invoke(JNILibraryInitializer.java)
	at com.oracle.svm.jni.JNILibraryInitializer.callOnLoadFunction(JNILibraryInitializer.java:72)
	at com.oracle.svm.jni.JNILibraryInitializer.initialize(JNILibraryInitializer.java:129)
	at com.oracle.svm.core.jdk.NativeLibrarySupport.addLibrary(NativeLibrarySupport.java:186)
	at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibrary0(NativeLibrarySupport.java:142)
	at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryAbsolute(NativeLibrarySupport.java:101)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:273)
	at java.lang.Runtime.load0(Runtime.java:768)
	at java.lang.System.load(System.java:1835)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
	at com.sun.jna.NativeLibrary.<clinit>(NativeLibrary.java:87)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
	at org.apache.cassandra.utils.NativeLibraryLinux.<clinit>(NativeLibraryLinux.java:55)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
	at org.apache.cassandra.utils.NativeLibrary.<clinit>(NativeLibrary.java:103)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:260)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:763)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:887)
```

**Comment by SergejIsbrecht** [comment]
native-image:

```plain
GraalVM 21.1.0 Java 11 CE (Java Version 11.0.11+8-jvmci-21.1-b05)
```

I get following error when running:

`   38;2;228;228;228m 38;2;228;228;228m~/Development/GitHub/odd/3  master ?15     ./a.exe -Dcassandra.config=file:///home/sergej/Development/GitHub/odd/3/cassandra/conf/cassandra.yaml ✔  ✔  22:21:23 `

```
22:21:25.262 [main] INFO org.apache.cassandra.config.YamlConfigurationLoader - Configuration location: file:/home/sergej/Development/GitHub/odd/3/cassandra/conf/cassandra.yaml
22:21:25.262 [main] DEBUG org.apache.cassandra.config.YamlConfigurationLoader - Loading settings from file:/home/sergej/Development/GitHub/odd/3/cassandra/conf/cassandra.yaml
22:21:25.267 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - Unable to load the library 'netty_tcnative_linux_x86_64', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_64 in java.library.path
	at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryRelative(NativeLibrarySupport.java:132)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:275)
	at java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.lang.System.loadLibrary(System.java:1871)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at java.lang.reflect.Method.invoke(Method.java:566)

```

on `uname -a`

```plain
Linux sergej-ThinkPad-P50 5.8.0-49-generic #55~20.04.1-Ubuntu SMP Fri Mar 26 01:01:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by tenwx** [comment]
> I updated jni-config and reflect-config (checked in) as far as possible and it ended up here:
> 
> ```
> 16:44:00.921 [main] ERROR org.apache.cassandra.service.CassandraDaemon - Exception encountered during startup
> java.lang.NoSuchMethodError: java.lang.Long.<init>(J)V
> 	at com.oracle.svm.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1104)
> 	at com.oracle.svm.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1089)
> 	at com.oracle.svm.jni.functions.JNIFunctions.GetMethodID(JNIFunctions.java:410)
> 	at com.oracle.svm.jni.JNIOnLoadFunctionPointer.invoke(JNILibraryInitializer.java)
> 	at com.oracle.svm.jni.JNILibraryInitializer.callOnLoadFunction(JNILibraryInitializer.java:72)
> 	at com.oracle.svm.jni.JNILibraryInitializer.initialize(JNILibraryInitializer.java:129)
> 	at com.oracle.svm.core.jdk.NativeLibrarySupport.addLibrary(NativeLibrarySupport.java:186)
> 	at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibrary0(NativeLibrarySupport.java:142)
> 	at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryAbsolute(NativeLibrarySupport.java:101)
> 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:273)
> 	at java.lang.Runtime.load0(Runtime.java:768)
> 	at java.lang.System.load(System.java:1835)
> 	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
> 	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
> 	at com.sun.jna.Native.<clinit>(Native.java:195)
> 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
> 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
> 	at com.sun.jna.NativeLibrary.<clinit>(NativeLibrary.java:87)
> 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
> 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
> 	at org.apache.cassandra.utils.NativeLibraryLinux.<clinit>(NativeLibraryLinux.java:55)
> 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
> 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
> 	at org.apache.cassandra.utils.NativeLibrary.<clinit>(NativeLibrary.java:103)
> 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
> 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
> 	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:260)
> 	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:763)
> 	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:887)
> ```

Adding the following json string to the jni-conf file will work:
`
{
  "name":"java.lang.Object",
  "methods": [
    { "name": "toString" }
  ]
},
{
  "name":"java.lang.Class",
  "methods": [
    { "name": "getComponentType" }
  ]
},
{
  "name":"java.lang.String",
  "methods": [
    { "name": "getBytes" },
    { "name": "toCharArray" },
    { "name": "<init>" }
  ]
},
{
  "name":"java.lang.reflect.Method",
  "methods": [
    { "name": "getParameterTypes" },
    { "name": "getReturnType" }
  ]
},
{
  "name":"java.nio.Buffer",
  "methods": [
    { "name": "position" }
  ]
},
{
  "name":"java.nio.ByteBuffer",
  "methods": [
    { "name": "array" },
    { "name": "arrayOffset" }
  ]
},
{
  "name":"java.nio.CharBuffer",
  "methods": [
    { "name": "array" },
    { "name": "arrayOffset" }
  ]
},
{
  "name":"java.nio.ShortBuffer",
  "methods": [
    { "name": "array" },
    { "name": "arrayOffset" }
  ]
},
{
  "name":"java.nio.IntBuffer",
  "methods": [
    { "name": "array" },
    { "name": "arrayOffset" }
  ]
},
{
  "name":"java.nio.LongBuffer",
  "methods": [
    { "name": "array" },
    { "name": "arrayOffset" }
  ]
},
{
  "name":"java.nio.FloatBuffer",
  "methods": [
    { "name": "array" },
    { "name": "arrayOffset" }
  ]
},
{
  "name":"java.nio.DoubleBuffer",
  "methods": [
    { "name": "array" },
    { "name": "arrayOffset" }
  ]
},
{
  "name":"java.lang.Void",
  "fields":[
    { "name": "TYPE" }
  ]
},
{
  "name":"java.lang.Boolean",
  "methods": [
    { "name": "<init>" }
  ],
  "fields":[
    { "name": "value" },
    { "name": "TYPE" }
  ]
},
{
  "name":"java.lang.Byte",
  "methods": [
    { "name": "<init>" }
  ],
  "fields":[
    { "name": "value" },
    { "name": "TYPE" }
  ]
},
{
  "name":"java.lang.Character",
  "methods": [
    { "name": "<init>" }
  ],
  "fields":[
    { "name": "value" },
    { "name": "TYPE" }
  ]
},
{
  "name":"java.lang.Short",
  "methods": [
    { "name": "<init>" }
  ],
  "fields":[
    { "name": "value" },
    { "name": "TYPE" }
  ]
},
{
  "name":"java.lang.Integer",
  "methods": [
    { "name": "<init>" }
  ],
  "fields":[
    { "name": "value" },
    { "name": "TYPE" }
  ]
},
{
  "name":"java.lang.Long",
  "methods": [
    { "name": "<init>" }
  ],
  "fields":[
    { "name": "value" },
    { "name": "TYPE" }
  ]
},
{
  "name":"java.lang.Float",
  "methods": [
    { "name": "<init>" }
  ],
  "fields":[
    { "name": "value" },
    { "name": "TYPE" }
  ]
},
{
  "name":"java.lang.Double",
  "methods": [
    { "name": "<init>" }
  ],
  "fields":[
    { "name": "value" },
    { "name": "TYPE" }
  ]
}
`

**Comment by mcraj017** [comment]
@ehsmeng-graalvm please add the JSON provided by @tenwx and let us know if its works.

**Comment by ehsmeng-graalvm** [comment]
Hi, Sorry for the delay

The jni configuration advanced the compilation but it's now stuck at a later stage. 

`
[a.exe:1902026]   (typeflow):  29,119.73 ms,  4.98 GB
[a.exe:1902026]    (objects):  42,110.24 ms,  4.98 GB
[a.exe:1902026]   (features):   6,834.14 ms,  4.98 GB
[a.exe:1902026]     analysis:  82,153.41 ms,  4.98 GB
Error: Illegal: Unsafe loading from UnknownTypeState. Load: at sun.misc.Unsafe.getObject(Object, long) [bci: -1]
at net.openhft.chronicle.core.UnsafeMemory.unsafeGetObject(UnsafeMemory.java:219) [bci: 5]
Detailed message:
Trace: Location: sun.misc.Unsafe.getObject(Unsafe.java)
Call path:
Call path from entry point to net.openhft.chronicle.core.UnsafeMemory.unsafeGetObject(Object, long): 
	at net.openhft.chronicle.core.UnsafeMemory.unsafeGetObject(UnsafeMemory.java:219)
	at net.openhft.chronicle.wire.WireMarshaller$StringBuilderFieldAccess.getValue(WireMarshaller.java:732)
	at net.openhft.chronicle.wire.WireMarshaller$FieldAccess.write(WireMarshaller.java:516)
	at net.openhft.chronicle.wire.WireMarshaller.writeMarshallable(WireMarshaller.java:197)
	at net.openhft.chronicle.wire.Wires.writeMarshallable(Wires.java:329)
	at net.openhft.chronicle.wire.BinaryWire$FixedBinaryValueOut.marshallable(BinaryWire.java:1879)
	at net.openhft.chronicle.wire.ValueOut.typedMarshallable(ValueOut.java:451)
	at net.openhft.chronicle.wire.WireType.asBytes(WireType.java:478)
	at net.openhft.chronicle.wire.WireType.asString(WireType.java:461)
	at net.openhft.chronicle.wire.AbstractFieldInfo.toString(AbstractFieldInfo.java:61)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_Object_2_0002etoString_00028_00029Ljava_lang_String_2(generated:0)
`
I just wanted to see how far I could get in Cassandra. We can close this if you want.

Best,
Marcus

**Comment by mcraj017** [comment]
@christianwimmer please advice

**Comment by fbuetler** [comment]
Im experiencing currently the same issue. Compilation works but it fails at runtime with the same stack trace:
```
java.lang.NoClassDefFoundError: Ljava/lang/Object;
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:346)
        at com.oracle.svm.jni.JNIOnLoadFunctionPointer.invoke(JNILibraryInitializer.java)
        at com.oracle.svm.jni.JNILibraryInitializer.callOnLoadFunction(JNILibraryInitializer.java:72)
        at com.oracle.svm.jni.JNILibraryInitializer.initialize(JNILibraryInitializer.java:129)
...
```
I used the `native-image-agent` to build the reflection configuration.

GraalVM version: 21.1.0
Javaj version: 11

Would be nice to know what config one should add to make it work.
