### ISSUE TITLE
"GraalVM Gate" and "Nightly quarkus tests" workflows failing due to missing JDK

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#3377]
**Describe the issue**
The github workflows ["GraalVM Gate"](https://github.com/oracle/graal/actions/workflows/main.yml) and ["Nightly quarkus tests"](https://github.com/oracle/graal/actions/workflows/quarkus.yml) are failing with:

```
WARNING: Selected `/home/runner/work/graal/graal/common.json` as configuration location, since no location is provided
Fetching labsjdk-ce-11-jvmci-21.1-b05 archive from https://github.com/graalvm/labs-openjdk-11/releases/download/jvmci-21.1-b05/labsjdk-ce-11.0.11+8-jvmci-21.1-b05-linux-amd64.tar.gz...
Traceback (most recent call last):
  File "/home/runner/work/graal/graal/mx/mx.py", line 17428, in <module>
    main()
  File "/home/runner/work/graal/graal/mx/mx.py", line 17409, in main
    retcode = c(command_args)
  File "/home/runner/work/graal/graal/mx/mx_commands.py", line 147, in __call__
    return self.command_function(*args, **kwargs)
  File "/home/runner/work/graal/graal/mx/mx_fetchjdk.py", line 69, in fetch_jdk
    sha1_hash = mx._hashFromUrl(sha_url).decode('utf-8')
  File "/home/runner/work/graal/graal/mx/mx.py", line 116, in _hashFromUrl
    hashFile = _urllib_request.urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

**Comment by dougxc** [comment]
I have uploaded the artifacts now.
We will try ensure they are published more promptly for future CPU releases (/cc @marwan-hallaoui ).
