### ISSUE TITLE
reflection problem in spring boot code

### ISSUE THREAD

**Issue by xcorrnner** [oracle/graal#3379]
**Describe the issue**
Trying to compile a spring boot demo project that only print "hello" using the native image.  have tried to add the configuration JSON but still provide the same error. 
```
[root ~/AOT]# native-image -jar old-0.0.1-SNAPSHOT.jar -H:+ReportExceptionStackTraces
[old-0.0.1-SNAPSHOT:16652]    classlist:     955.22 ms,  1.16 GB
[old-0.0.1-SNAPSHOT:16652]        (cap):     433.22 ms,  1.16 GB
[old-0.0.1-SNAPSHOT:16652]        setup:  15,404.78 ms,  1.63 GB
[old-0.0.1-SNAPSHOT:16652]     (clinit):     172.81 ms,  1.70 GB
[old-0.0.1-SNAPSHOT:16652]   (typeflow):   5,314.20 ms,  1.70 GB
[old-0.0.1-SNAPSHOT:16652]    (objects):   4,588.35 ms,  1.70 GB
[old-0.0.1-SNAPSHOT:16652]   (features):     171.78 ms,  1.70 GB
[old-0.0.1-SNAPSHOT:16652]     analysis:  10,413.89 ms,  1.70 GB
[old-0.0.1-SNAPSHOT:16652]     universe:     395.70 ms,  1.70 GB
Warning: Reflection method java.lang.Class.forName invoked at org.springframework.boot.loader.jar.Handler.getFallbackHandler(Handler.java:158)
Warning: Reflection method java.lang.Class.forName invoked at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
Warning: Reflection method java.lang.Class.getDeclaredMethod invoked at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47)
Warning: Reflection method java.lang.Class.getDeclaredConstructor invoked at org.springframework.boot.loader.jar.Handler.getFallbackHandler(Handler.java:159)
Warning: Aborting stand-alone image build due to reflection use without configuration.
com.oracle.svm.hosted.FallbackFeature$FallbackImageRequest: Reflection method java.lang.Class.forName invoked at org.springframework.boot.loader.jar.Handler.getFallbackHandler(Handler.java:158)
Reflection method java.lang.Class.forName invoked at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
Reflection method java.lang.Class.getDeclaredMethod invoked at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47)
Reflection method java.lang.Class.getDeclaredConstructor invoked at org.springframework.boot.loader.jar.Handler.getFallbackHandler(Handler.java:159)
Aborting stand-alone image build due to reflection use without configuration.
        at com.oracle.svm.hosted.FallbackFeature.afterAnalysis(FallbackFeature.java:302)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$15(NativeImageGenerator.java:786)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:71)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:786)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:582)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:495)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[old-0.0.1-SNAPSHOT:16841]    classlist:     925.33 ms,  1.16 GB
[old-0.0.1-SNAPSHOT:16841]        (cap):     394.68 ms,  1.16 GB
[old-0.0.1-SNAPSHOT:16841]        setup:  13,737.51 ms,  1.64 GB
[old-0.0.1-SNAPSHOT:16841]     (clinit):     124.29 ms,  1.75 GB
[old-0.0.1-SNAPSHOT:16841]   (typeflow):   3,706.38 ms,  1.75 GB
[old-0.0.1-SNAPSHOT:16841]    (objects):   3,189.65 ms,  1.75 GB
[old-0.0.1-SNAPSHOT:16841]   (features):     135.34 ms,  1.75 GB
[old-0.0.1-SNAPSHOT:16841]     analysis:   7,285.65 ms,  1.75 GB
[old-0.0.1-SNAPSHOT:16841]     universe:     322.38 ms,  1.75 GB
[old-0.0.1-SNAPSHOT:16841]      (parse):     726.06 ms,  1.75 GB
[old-0.0.1-SNAPSHOT:16841]     (inline):   1,098.59 ms,  1.78 GB
[old-0.0.1-SNAPSHOT:16841]    (compile):   4,761.96 ms,  2.11 GB
[old-0.0.1-SNAPSHOT:16841]      compile:   7,098.61 ms,  2.11 GB
[old-0.0.1-SNAPSHOT:16841]        image:   1,027.73 ms,  2.11 GB
[old-0.0.1-SNAPSHOT:16841]        write:     129.22 ms,  2.11 GB
# Printing build artifacts to: old-0.0.1-SNAPSHOT.build_artifacts.txt
[old-0.0.1-SNAPSHOT:16841]      [total]:  30,688.18 ms,  2.11 GB
Warning: Image 'old-0.0.1-SNAPSHOT' is a fallback image that requires a JDK for execution (use --no-fallback to suppress fallback image generation and to print more detailed information why a fallback image was necessary).
```

**Steps to reproduce the issue**
1. **git clone https://github.com/xcorrnner/graalvm-springboot-aot**
2. **native-image -jar old-0.0.1-SNAPSHOT.jar**

**Describe GraalVM and your environment:**
 - GraalVM version **GraalVM CE 21.2.0-dev-20210423_1956**
 - JDK major version: **8**
 - OS: **CentOS Linux release 7.2**
 - Architecture: **AMD64**

**More details**

adding the `--native-image-info` and  `--verbose` flags when building your native image and output below.
```
[root ~/AOT]# native-image -jar old-0.0.1-SNAPSHOT.jar -H:+ReportExceptionStackTraces --native-image-info --verbose
Executing [
/root/graalvm-ce-java8-21.1.0/jre/bin/java \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-d64 \
-XX:-UseJVMCIClassLoader \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx13243174088 \
-Duser.country=US \
-Duser.language=en \
-Djava.awt.headless=true \
-Dorg.graalvm.version=21.1.0 \
-Dorg.graalvm.config=CE \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
-Djvmci.class.path.append=/root/graalvm-ce-java8-21.1.0/jre/lib/jvmci/graal.jar \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-javaagent:/root/graalvm-ce-java8-21.1.0/jre/lib/svm/builder/svm.jar \
-Xbootclasspath/a:/root/graalvm-ce-java8-21.1.0/jre/lib/boot/graal-sdk.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/boot/graaljs-scriptengine.jar \
-cp \
/root/graalvm-ce-java8-21.1.0/jre/lib/svm/builder/javacpp-shadowed.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/svm/builder/objectfile.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/svm/builder/svm-llvm.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/svm/builder/llvm-wrapper-shadowed.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/svm/builder/svm.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/svm/builder/llvm-platform-specific-shadowed.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/svm/builder/pointsto.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/jvmci/graal-management.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/jvmci/jvmci-hotspot.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/jvmci/jvmci-api.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/jvmci/graal.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/jvmci/graal-truffle-jfr-impl.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/resources.jar \
com.oracle.svm.hosted.NativeImageGeneratorRunner \
-watchpid \
22450 \
-imagecp \
/root/graalvm-ce-java8-21.1.0/jre/lib/boot/graal-sdk.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/boot/graaljs-scriptengine.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/svm/library-support.jar:/root/AOT/old-0.0.1-SNAPSHOT.jar \
-H:Path=/root/AOT \
'-H:Class@manifest from file:///root/AOT/old-0.0.1-SNAPSHOT.jar=org.springframework.boot.loader.JarLauncher' \
'-H:Name@manifest from file:///root/AOT/old-0.0.1-SNAPSHOT.jar=old-0.0.1-SNAPSHOT' \
-H:+ReportExceptionStackTraces \
-H:+DumpTargetInfo \
-H:CLibraryPath=/root/graalvm-ce-java8-21.1.0/jre/lib/svm/clibraries/linux-amd64 \
]
[old-0.0.1-SNAPSHOT:22472]    classlist:     961.68 ms,  1.16 GB
[old-0.0.1-SNAPSHOT:22472]        (cap):     428.28 ms,  1.16 GB
[old-0.0.1-SNAPSHOT:22472]        setup:   2,076.08 ms,  1.66 GB
# Building image for target platform: org.graalvm.nativeimage.Platform$LINUX_AMD64
# Using native toolchain:
#   Name: GNU project C and C++ compiler (gcc)
#   Vendor: redhat
#   Version: 4.8.5
#   Target architecture: x86_64
#   Path: /usr/bin/gcc
# Using CLibrary: com.oracle.svm.core.posix.linux.libc.GLibC
[old-0.0.1-SNAPSHOT:22472]     (clinit):     178.19 ms,  1.72 GB
# Static libraries:
#   ../graalvm-ce-java8-21.1.0/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a
#   ../graalvm-ce-java8-21.1.0/jre/lib/libnet.a
#   ../graalvm-ce-java8-21.1.0/jre/lib/libnio.a
#   ../graalvm-ce-java8-21.1.0/jre/lib/libjava.a
#   ../graalvm-ce-java8-21.1.0/jre/lib/libfdlibm.a
#   ../graalvm-ce-java8-21.1.0/jre/lib/libzip.a
#   ../graalvm-ce-java8-21.1.0/jre/lib/svm/clibraries/linux-amd64/libjvm.a
# Other libraries: pthread,dl,z,rt
[old-0.0.1-SNAPSHOT:22472]   (typeflow):   5,509.17 ms,  1.72 GB
[old-0.0.1-SNAPSHOT:22472]    (objects):   4,500.62 ms,  1.72 GB
[old-0.0.1-SNAPSHOT:22472]   (features):     219.54 ms,  1.72 GB
[old-0.0.1-SNAPSHOT:22472]     analysis:  10,599.59 ms,  1.72 GB
[old-0.0.1-SNAPSHOT:22472]     universe:     495.25 ms,  1.72 GB
Warning: Reflection method java.lang.Class.forName invoked at org.springframework.boot.loader.jar.Handler.getFallbackHandler(Handler.java:158)
Warning: Reflection method java.lang.Class.forName invoked at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
Warning: Reflection method java.lang.Class.getDeclaredMethod invoked at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47)
Warning: Reflection method java.lang.Class.getDeclaredConstructor invoked at org.springframework.boot.loader.jar.Handler.getFallbackHandler(Handler.java:159)
Warning: Aborting stand-alone image build due to reflection use without configuration.
com.oracle.svm.hosted.FallbackFeature$FallbackImageRequest: Reflection method java.lang.Class.forName invoked at org.springframework.boot.loader.jar.Handler.getFallbackHandler(Handler.java:158)
Reflection method java.lang.Class.forName invoked at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
Reflection method java.lang.Class.getDeclaredMethod invoked at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47)
Reflection method java.lang.Class.getDeclaredConstructor invoked at org.springframework.boot.loader.jar.Handler.getFallbackHandler(Handler.java:159)
Aborting stand-alone image build due to reflection use without configuration.
        at com.oracle.svm.hosted.FallbackFeature.afterAnalysis(FallbackFeature.java:302)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$15(NativeImageGenerator.java:786)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:71)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:786)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:582)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:495)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Executing [
/root/graalvm-ce-java8-21.1.0/jre/bin/java \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-d64 \
-XX:-UseJVMCIClassLoader \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx13243174088 \
-Duser.country=US \
-Duser.language=en \
-Djava.awt.headless=true \
-Dorg.graalvm.version=21.1.0 \
-Dorg.graalvm.config=CE \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
-Djvmci.class.path.append=/root/graalvm-ce-java8-21.1.0/jre/lib/jvmci/graal.jar \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-javaagent:/root/graalvm-ce-java8-21.1.0/jre/lib/svm/builder/svm.jar \
-Xbootclasspath/a:/root/graalvm-ce-java8-21.1.0/jre/lib/boot/graal-sdk.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/boot/graaljs-scriptengine.jar \
-cp \
/root/graalvm-ce-java8-21.1.0/jre/lib/svm/builder/javacpp-shadowed.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/svm/builder/objectfile.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/svm/builder/svm-llvm.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/svm/builder/llvm-wrapper-shadowed.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/svm/builder/svm.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/svm/builder/llvm-platform-specific-shadowed.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/svm/builder/pointsto.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/jvmci/graal-management.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/jvmci/jvmci-hotspot.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/jvmci/jvmci-api.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/jvmci/graal.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/jvmci/graal-truffle-jfr-impl.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/resources.jar \
com.oracle.svm.hosted.NativeImageGeneratorRunner \
-watchpid \
22450 \
-imagecp \
/root/graalvm-ce-java8-21.1.0/jre/lib/boot/graal-sdk.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/boot/graaljs-scriptengine.jar:/root/graalvm-ce-java8-21.1.0/jre/lib/svm/library-support.jar \
-H:Path=/root/AOT \
-H:+ParseRuntimeOptions \
-H:Path=/root/AOT \
-H:FallbackExecutorClasspath=old-0.0.1-SNAPSHOT.jar \
-H:FallbackExecutorMainClass=org.springframework.boot.loader.JarLauncher \
-H:-DetectUserDirectoriesInImageHeap \
-H:CLibraryPath=/root/graalvm-ce-java8-21.1.0/jre/lib/svm/clibraries/linux-amd64 \
'-H:Class@explicit main-class=com.oracle.svm.core.FallbackExecutor' \
'-H:Name@explicit image name=old-0.0.1-SNAPSHOT' \
]
[old-0.0.1-SNAPSHOT:22595]    classlist:     920.08 ms,  0.96 GB
[old-0.0.1-SNAPSHOT:22595]        (cap):     431.57 ms,  1.05 GB
[old-0.0.1-SNAPSHOT:22595]        setup:  16,493.41 ms,  1.14 GB
[old-0.0.1-SNAPSHOT:22595]     (clinit):     127.47 ms,  1.19 GB
[old-0.0.1-SNAPSHOT:22595]   (typeflow):   3,706.46 ms,  1.19 GB
[old-0.0.1-SNAPSHOT:22595]    (objects):   3,209.06 ms,  1.19 GB
[old-0.0.1-SNAPSHOT:22595]   (features):     140.21 ms,  1.19 GB
[old-0.0.1-SNAPSHOT:22595]     analysis:   7,317.59 ms,  1.19 GB
[old-0.0.1-SNAPSHOT:22595]     universe:     381.32 ms,  1.20 GB
[old-0.0.1-SNAPSHOT:22595]      (parse):     733.05 ms,  1.20 GB
[old-0.0.1-SNAPSHOT:22595]     (inline):   1,062.02 ms,  1.35 GB
[old-0.0.1-SNAPSHOT:22595]    (compile):   4,913.60 ms,  1.63 GB
[old-0.0.1-SNAPSHOT:22595]      compile:   7,187.76 ms,  1.63 GB
[old-0.0.1-SNAPSHOT:22595]        image:   1,061.44 ms,  1.63 GB
[old-0.0.1-SNAPSHOT:22595]        write:     137.80 ms,  1.63 GB
# Printing build artifacts to: old-0.0.1-SNAPSHOT.build_artifacts.txt
[old-0.0.1-SNAPSHOT:22595]      [total]:  33,661.84 ms,  1.63 GB
Warning: Image 'old-0.0.1-SNAPSHOT' is a fallback image that requires a JDK for execution (use --no-fallback to suppress fallback image generation and to print more detailed information why a fallback image was necessary).
```
try to add configuration by `$JAVA_HOME/bin/java -agentlib:native-image-agent=config-merge-dir=META-INF/native-image -jar old-0.0.1-SNAPSHOT.jar`, the output stays same as pervious one.
```
      .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.4.5)

2021-04-26 17:04:32.385  INFO 14506 --- [           main] com.example.old.OldApplication           : Starting OldApplication v0.0.1-SNAPSHOT using Java 1.8.0_292 on VM-186-126-centos with PID 14506 (/root/AOT/old-0.0.1-SNAPSHOT.jar started by root in /root/AOT)
2021-04-26 17:04:32.389  INFO 14506 --- [           main] com.example.old.OldApplication           : No active profile set, falling back to default profiles: default
2021-04-26 17:04:33.309  INFO 14506 --- [           main] com.example.old.OldApplication           : Started OldApplication in 1.456 seconds (JVM running for 1.904)
hello
```
compile with `--no-fallback` 
```
[root ~/AOT]# ./old-0.0.1-SNAPSHOT 
Exception in thread "main" java.lang.IllegalStateException: java.util.zip.ZipException: zip END header not found
        at org.springframework.boot.loader.ExecutableArchiveLauncher.<init>(ExecutableArchiveLauncher.java:52)
        at org.springframework.boot.loader.JarLauncher.<init>(JarLauncher.java:48)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.util.zip.ZipException: zip END header not found
        at com.oracle.svm.core.jdk8.zipfile.ZipFile$Source.zerror(ZipFile.java:1317)
        at com.oracle.svm.core.jdk8.zipfile.ZipFile$Source.findEND(ZipFile.java:1218)
        at com.oracle.svm.core.jdk8.zipfile.ZipFile$Source.initCEN(ZipFile.java:1225)
        at com.oracle.svm.core.jdk8.zipfile.ZipFile$Source.<init>(ZipFile.java:1062)
        at com.oracle.svm.core.jdk8.zipfile.ZipFile$Source.get(ZipFile.java:1022)
        at java.util.zip.ZipFile.<init>(ZipFile.java:261)
        at java.util.zip.ZipFile.<init>(ZipFile.java:191)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:130)
        at org.springframework.boot.loader.jar.AbstractJarFile.<init>(AbstractJarFile.java:39)
        at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:128)
        at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:123)
        at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:109)
        at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:100)
        at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:73)
        at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:69)
        at org.springframework.boot.loader.Launcher.createArchive(Launcher.java:163)
        at org.springframework.boot.loader.ExecutableArchiveLauncher.<init>(ExecutableArchiveLauncher.java:48)
        ... 2 more
```

**Comment by mcraj017** [comment]
@xcorrnner thanks for reporting the issue 
we will check it out and come back to you

**Comment by petermz** [comment]
Hi @xcorrnner -- do you use spring-native for compilation? It's definitely capable of compiling (at least) simple spring-boot apps. See [their docs](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/) for an example

**Comment by xcorrnner** [comment]
spring native works fine with just a spring boot demo.

**Comment by mcraj017** [comment]
@xcorrnner closing it as your issue is resolved using spring native project.
feel free to open new issue if you got any other problem
