### ISSUE TITLE
Unexpected assert failure org.graalvm.polyglot.Context should not be reachable

### ISSUE THREAD

**Issue by stanislavcc** [oracle/graal#3384]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **21.1.0**
 - CE or EE: **CE**
 - JDK version: **JDK11**
 - OS and OS Version: **Windows**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
OpenJDK 64-Bit Server VM (11.0.11+8-jvmci-21.1-b05) for windows-amd64 JRE (11.0.11+8-jvmci-21.1-b05), built on Apr 12 2021 17:01:18 by "" with MS VC++ 15.9 (VS2017)
```

**Have you verified this issue still happens when using the latest snapshot?**
no

**Describe the issue**
We implemented an TruffleInstrument tool that periodically executes TruffleInstrument.Env#calculateContextHeapSize from ExecutionEventListener#onReturnValue to calculate the heap size and optionally cancel the execution.

The calculation often fails on assert in https://github.com/oracle/graal/blob/89e4cfc7aeea69970b60c64cd075ceb2a104e864/truffle/src/com.oracle.truffle.polyglot/src/com/oracle/truffle/polyglot/ObjectSizeCalculator.java#L258

The reason is that our typical js script looks something like this:
```
(client) => { ... }
```
where the client parameter is a proxy object with Context property which is necessary for some operations:
```
class ScriptFetchApiClient extends ProxyObject {
   private Context context;
   ...
}
```
So from this point of view, it seems to me that Context is very easily reachable by the calculation algorithm and the assert is invalid.

Note that if the asserts are disabled the calculation finishes and it appears to be working correctly.

I also saw the same error for PolyglotContextImpl but I didn't track the traversing path to it in that case.

**Expected behavior**
Either don't assert fail when reaching Context object or have some tool (annotation) to prevent the calculation algorithm to reach specific objects.

**Additional context**
```
Caused by: org.graalvm.polyglot.PolyglotException: java.lang.AssertionError: org.graalvm.polyglot.Context should not be reachable
	at com.oracle.truffle.polyglot.ObjectSizeCalculator.isContextHeapBoundary(ObjectSizeCalculator.java:271) ~[org.graalvm.truffle:?]
	at com.oracle.truffle.polyglot.ObjectSizeCalculator.canProceed(ObjectSizeCalculator.java:317) ~[org.graalvm.truffle:?]
	at com.oracle.truffle.polyglot.ObjectSizeCalculator.access$500(ObjectSizeCalculator.java:86) ~[org.graalvm.truffle:?]
	at com.oracle.truffle.polyglot.ObjectSizeCalculator$ObjectClassInfo.visit(ObjectSizeCalculator.java:463) ~[org.graalvm.truffle:?]
	at com.oracle.truffle.polyglot.ObjectSizeCalculator.visit(ObjectSizeCalculator.java:245) ~[org.graalvm.truffle:?]
	at com.oracle.truffle.polyglot.ObjectSizeCalculator.calculateObjectSize(ObjectSizeCalculator.java:206) ~[org.graalvm.truffle:?]
	at com.oracle.truffle.polyglot.PolyglotContextImpl.calculateHeapSize(PolyglotContextImpl.java:1401) ~[org.graalvm.truffle:?]
	at com.oracle.truffle.polyglot.EngineAccessor$EngineImpl.calculateContextHeapSize(EngineAccessor.java:1394) ~[org.graalvm.truffle:?]
	at com.oracle.truffle.api.instrumentation.TruffleInstrument$Env.calculateContextHeapSize(TruffleInstrument.java:1347) ~[org.graalvm.truffle:?]
	at com.citrix.microapps.script.instrument.HeapGuard.poll(HeapGuard.java:61) ~[?:?]
	at com.citrix.microapps.script.instrument.HeapGuardInstrument$2.onReturnValue(HeapGuardInstrument.java:114) ~[?:?]
	at com.oracle.truffle.api.instrumentation.ProbeNode$EventFilterChainNode.innerOnReturnValue(ProbeNode.java:1187) ~[org.graalvm.truffle:?]
	at com.oracle.truffle.api.instrumentation.ProbeNode$EventChainNode.onReturnValue(ProbeNode.java:1016) ~[org.graalvm.truffle:?]
	at com.oracle.truffle.api.instrumentation.ProbeNode.onReturnValue(ProbeNode.java:232) ~[org.graalvm.truffle:?]
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:47) ~[?:?]
	at com.oracle.truffle.js.nodes.instrumentation.DeclareTagProvider$MaterializedFunctionBodyNode.execute(DeclareTagProvider.java:153) ~[?:?]
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:45) ~[?:?]
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:147) ~[?:?]
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:93) ~[?:?]
	at <js>.testFunction(Unknown) ~[?:?]
	at org.graalvm.polyglot.Value.execute(Value.java:834) ~[org.graalvm.sdk:?]
```
</details>

**Comment by chumer** [comment]
This assert is a safeguard from invalid references from inside a polyglot language or tool. Since you have your own instrument active It is hard for me to say where the problem is. We haven't seen this in our internal tests with our EE sandbox features.

Is it possible that your instrument stores references to org.graalvm.polyglot instances? Maybe from in `HeapGuardInstrument$2´? That is generally not expected, hence the assert.

I think we should improve the error message here and print a reference path. 

Until then in order for diagnosing this we would need a heap dump, or full reference path to the Context instance.
In addition the source code of the instrument would be helpful.

**Comment by stanislavcc** [comment]
HeapGuardInstrument$2 is instance of ExecutionEventListener which is executing calculateContextHeapSize using an object I store in ContextLocal. This object indeed has reference to TruffleContext and TruffleInstrument.Env. Could that be a problem?

**Comment by jchalou** [comment]
TruffleContext and TruffleInstrument.Env are not a problem. These are both expected to be reachable and the exploration stops on them. It would help us if you could find where PolyglotContextImpl is reachble from. Context seems to be clearly reachable from the ProxyObject, but there the explorations stops (due to the assertion failure) so PolyglotContextImpl is not reachable through it. So to fix this problem, we need further information about you use case. Thanks.

**Comment by stanislavcc** [comment]
It happens rarely in the PolyglotContextImpl case, but today I managed to take a dump and tried to get the reference path by using logging breakpoints at ObjectSizeCalculator.java:338 and ObjectSizeCalculator.java:463. 
It's pretty direct in this case:
`
[Ljava.lang.Object;@3ecaa932 -> org.graalvm.compiler.truffle.runtime.FrameWithoutBoxing@605bb273

org.graalvm.compiler.truffle.runtime.FrameWithoutBoxing@605bb273 -> [Ljava.lang.Object;@4a072e45

[Ljava.lang.Object;@4a072e45 -> PolyglotContextImpl[state=cancelling languages=[host, regex, js]]
`
Heapdump: https://citrix.sharefile.com/d-s6ecc1cb6b3394b698b05f84204804d78
[paths.txt](https://github.com/oracle/graal/files/6440688/paths.txt)

**Comment by chumer** [comment]
@stanislavcc Thanks a lot. That trace is useful! I think we found the problem. It is on our side. It happens when you have an active call to the guest context using Value (using HostToGuestRootNode), there is a remaining instance of PolyglotContextImpl in the arguments array.

**Comment by jchalou** [comment]
@stanislavcc Fix has already been submitted. It will shortly be included in a dev build available here: https://github.com/graalvm/graalvm-ce-dev-builds/releases/ The current build does not contain it yet, but the next one most likely will. Please let us know if it works for you. Thanks.

**Comment by stanislavcc** [comment]
I let it run for about an hour and got no assert error. Looks good to me.
