### ISSUE TITLE
Truffle NFI is not installed and nof installable as Graal component

### ISSUE THREAD

**Issue by OlegPliss** [oracle/graal#3394]
**Describe GraalVM and your environment :**
 GraalVM version 21.1.0
 CE
 JDK8
 Linux Ubuntu 20
 amd64
 - The output of `java -Xinternalversion`:
```
 OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (25.292-b09-jvmci-21.1-b05) for linux-amd64 JRE (1.8.0), built on Apr 12 2021 16:25:38 by "buildslave" with gcc 7.3.0
```

**Have you verified this issue still happens when using the latest snapshot?**
No.

You can find snapshot builds here: https://github.com/graalvm/graalvm-ce-dev-builds/releases

**Describe the issue**
A clear and concise description of the issue.

**Code snippet or code repository that reproduces the issue**
This is just a snippet from here: https://www.graalvm.org/graalvm-as-a-platform/language-implementation-framework/NFI/#combined-loading-and-binding
```
        Context polyglot = Context.create();
        Value library = polyglot.eval("nfi", "load \"natives.so\"");
```

```
Exception in thread "main" java.lang.IllegalArgumentException: A language with id 'nfi' is not installed. Installed languages are: [js, llvm].
	at com.oracle.truffle.polyglot.PolyglotEngineException.illegalArgument(PolyglotEngineException.java:130)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.requirePublicLanguage(PolyglotEngineImpl.java:989)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.requirePublicLanguage(PolyglotContextImpl.java:1071)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:1041)
	at org.graalvm.polyglot.Context.eval(Context.java:353)
	at org.graalvm.polyglot.Context.eval(Context.java:379)

$ gu list
ComponentId              Version             Component name                Stability                     Origin 
---------------------------------------------------------------------------------------------------------------------------------
graalvm                  21.1.0              GraalVM Core                  -                             
js                       21.1.0              Graal.js                      Supported                     
native-image             21.1.0              Native Image                  Early adopter                 github.com

$ gu available
Downloading: Component catalog from www.graalvm.org
ComponentId              Version             Component name                Stability                     Origin 
---------------------------------------------------------------------------------------------------------------------------------
espresso                 21.1.0              Java on Truffle               Experimental                  github.com
llvm-toolchain           21.1.0              LLVM.org toolchain            Supported                     github.com
native-image             21.1.0              Native Image                  Early adopter                 github.com
nodejs                   21.1.0              Graal.nodejs                  Supported                     github.com
python                   21.1.0              Graal.Python                  Experimental                  github.com
R                        21.1.0              FastR                         Experimental                  github.com
ruby                     21.1.0              TruffleRuby                   Experimental                  github.com
wasm                     21.1.0              GraalWasm                     Experimental                  github.com
```
</details>

**Comment by mcraj017** [comment]
@OlegPliss thanks for reporting the issue
Please provide a reproducer

**Comment by mcraj017** [comment]
@OlegPliss any update on reproducer

**Comment by mcraj017** [comment]
Closing as there is new issue has been created for this issue
https://github.com/oracle/graal/issues/3425
