### ISSUE TITLE
Linkage error whie trying to build any native image on Ubuntu 20.10

### ISSUE THREAD

**Issue by OlegPliss** [oracle/graal#3400]
**Describe the issue**
Linkage error while building any native image on Ubuntu 20.10

**Steps to reproduce the issue**
Just try to build any native image, i.e. HelloWorld or SimpleLanguage

**Describe GraalVM and your environment:**
 - GraalVM version: **CE 21.1.0 (build 25.292-b09-jvmci-21.1-b05, mixed mode)**
 - JDK major version: **8**
 - OS: **Ubuntu 20.10**
 - Architecture: **AMD64**

**More details**
```
opliss@oleg-ThinkPad:~/Work/temp$ native-image --verbose HelloWorld
Executing [
/home/opliss/graalvm-ce-java8-21.1.0/jre/bin/java \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-d64 \
-XX:-UseJVMCIClassLoader \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx14g \
-Duser.country=US \
-Duser.language=en \
-Djava.awt.headless=true \
-Dorg.graalvm.version=21.1.0 \
-Dorg.graalvm.config=CE \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
-Djvmci.class.path.append=/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/jvmci/graal.jar \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-javaagent:/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/svm/builder/svm.jar \
-Xbootclasspath/a:/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/boot/graal-sdk.jar:/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/boot/graaljs-scriptengine.jar \
-cp \
/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/svm/builder/llvm-wrapper-shadowed.jar:/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/svm/builder/llvm-platform-specific-shadowed.jar:/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/svm/builder/objectfile.jar:/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/svm/builder/javacpp-shadowed.jar:/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/svm/builder/svm-llvm.jar:/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/svm/builder/svm.jar:/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/svm/builder/pointsto.jar:/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/jvmci/graal-management.jar:/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/jvmci/graal.jar:/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/jvmci/jvmci-hotspot.jar:/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/jvmci/graal-truffle-jfr-impl.jar:/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/jvmci/jvmci-api.jar:/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/resources.jar \
com.oracle.svm.hosted.NativeImageGeneratorRunner \
-watchpid \
551802 \
-imagecp \
/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/boot/graal-sdk.jar:/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/boot/graaljs-scriptengine.jar:/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/svm/library-support.jar:/home/opliss/Work/temp \
-H:Path=/home/opliss/Work/temp \
-H:CLibraryPath=/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/svm/clibraries/linux-amd64 \
'-H:Class@explicit main-class=HelloWorld' \
'-H:Name@main-class lower case as image name=helloworld' \
]
[helloworld:551837]    classlist:   5,145.82 ms,  1.21 GB
[helloworld:551837]        (cap):   2,059.88 ms,  1.21 GB
[helloworld:551837]        setup:   9,574.72 ms,  1.55 GB
[helloworld:551837]     (clinit):     477.82 ms,  1.55 GB
[helloworld:551837]   (typeflow):   7,602.91 ms,  1.55 GB
[helloworld:551837]    (objects):   5,025.54 ms,  1.55 GB
[helloworld:551837]   (features):     538.18 ms,  1.55 GB
[helloworld:551837]     analysis:  14,080.32 ms,  1.55 GB
[helloworld:551837]     universe:   1,635.07 ms,  1.69 GB
[helloworld:551837]      (parse):   1,741.50 ms,  1.69 GB
[helloworld:551837]     (inline):   1,527.42 ms,  1.69 GB
[helloworld:551837]    (compile):  11,191.84 ms,  1.72 GB
[helloworld:551837]      compile:  15,535.46 ms,  1.72 GB
[helloworld:551837]        image:   1,952.14 ms,  1.90 GB
[helloworld:551837]        write:     324.10 ms,  1.90 GB
Fatal error:java.lang.RuntimeException: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1

Linker command executed:
/usr/bin/gcc -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-8241139332401546274/exported_symbols.list -Wl,--exclude-libs,ALL -Wl,-x -o /home/opliss/Work/temp/helloworld helloworld.o /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/libnet.a /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/libnio.a /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/libjava.a /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/libfdlibm.a /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/libzip.a /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/svm/clibraries/linux-amd64/libjvm.a -v -L/tmp/SVM-8241139332401546274 -L/home/opliss/graalvm-ce-java8-21.1.0/jre/lib -L/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/svm/clibraries/linux-amd64 -lpthread -ldl -lz -lrt

Linker command output:
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 10.2.0-13ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-10-JvwpWM/gcc-10-10.2.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-10-JvwpWM/gcc-10-10.2.0/debian/tmp-gcn/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (Ubuntu 10.2.0-13ubuntu1) 
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/10/:/usr/lib/gcc/x86_64-linux-gnu/10/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/10/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/10/:/usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/10/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/10/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-z' 'noexecstack' '-o' '/home/opliss/Work/temp/helloworld' '-v' '-L/tmp/SVM-8241139332401546274' '-L/home/opliss/graalvm-ce-java8-21.1.0/jre/lib' '-L/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/10/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/10/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper -plugin-opt=-fresolution=/tmp/cc38uPpG.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -z now -z relro -o /home/opliss/Work/temp/helloworld -z noexecstack /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/10/crtbeginS.o -L/tmp/SVM-8241139332401546274 -L/home/opliss/graalvm-ce-java8-21.1.0/jre/lib -L/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-linux-gnu/10 -L/usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/10/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/10/../../.. --gc-sections --dynamic-list /tmp/SVM-8241139332401546274/exported_symbols.list --exclude-libs ALL -x helloworld.o /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/libnet.a /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/libnio.a /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/libjava.a /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/libfdlibm.a /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/libzip.a /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/svm/clibraries/linux-amd64/libjvm.a -lpthread -ldl -lz -lrt -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-linux-gnu/10/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/crtn.o
ld.lld: error: unable to find library -lz
collect2: error: ld returned 1 exit status
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:499)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:370)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:531)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
Caused by: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1

Linker command executed:
/usr/bin/gcc -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-8241139332401546274/exported_symbols.list -Wl,--exclude-libs,ALL -Wl,-x -o /home/opliss/Work/temp/helloworld helloworld.o /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/libnet.a /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/libnio.a /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/libjava.a /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/libfdlibm.a /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/libzip.a /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/svm/clibraries/linux-amd64/libjvm.a -v -L/tmp/SVM-8241139332401546274 -L/home/opliss/graalvm-ce-java8-21.1.0/jre/lib -L/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/svm/clibraries/linux-amd64 -lpthread -ldl -lz -lrt

Linker command output:
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 10.2.0-13ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-10-JvwpWM/gcc-10-10.2.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-10-JvwpWM/gcc-10-10.2.0/debian/tmp-gcn/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (Ubuntu 10.2.0-13ubuntu1) 
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/10/:/usr/lib/gcc/x86_64-linux-gnu/10/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/10/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/10/:/usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/10/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/10/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-z' 'noexecstack' '-o' '/home/opliss/Work/temp/helloworld' '-v' '-L/tmp/SVM-8241139332401546274' '-L/home/opliss/graalvm-ce-java8-21.1.0/jre/lib' '-L/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/10/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/10/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper -plugin-opt=-fresolution=/tmp/cc38uPpG.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -z now -z relro -o /home/opliss/Work/temp/helloworld -z noexecstack /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/10/crtbeginS.o -L/tmp/SVM-8241139332401546274 -L/home/opliss/graalvm-ce-java8-21.1.0/jre/lib -L/home/opliss/graalvm-ce-java8-21.1.0/jre/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-linux-gnu/10 -L/usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/10/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/10/../../.. --gc-sections --dynamic-list /tmp/SVM-8241139332401546274/exported_symbols.list --exclude-libs ALL -x helloworld.o /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/libnet.a /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/libnio.a /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/libjava.a /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/libfdlibm.a /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/libzip.a /home/opliss/graalvm-ce-java8-21.1.0/jre/lib/svm/clibraries/linux-amd64/libjvm.a -lpthread -ldl -lz -lrt -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-linux-gnu/10/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/crtn.o
ld.lld: error: unable to find library -lz
collect2: error: ld returned 1 exit status
	at com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:513)
	at com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:460)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:710)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:495)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1772)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1519)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1480)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1467)
```

**Comment by OlegPliss** [comment]
Apparently zlib development package must be installed.
