### ISSUE TITLE
NoSuchFieldError: sun.java2d.cmm.lcms.LCMSTransform.renderType

### ISSUE THREAD

**Issue by khorvat1** [oracle/graal#3401]
I have a problem with ImageIO and reading of tiff and gif images.
It breaks on line `val bufferedImage = ImageIO.read(imageInputStream)`

native-image.properties
```
Args = -H:ReflectionConfigurationResources=${.}/reflect-config.json \
  -H:ResourceConfigurationResources=${.}/resource-config.json \
  -H:+ReportExceptionStackTraces \
  --initialize-at-build-time=org.slf4j \
  --initialize-at-build-time=kotlin.ULong \
  --initialize-at-build-time=sun.java2d.Disposer,java.awt.image.ColorModel,java.awt.image.Raster,java.awt.image.SampleModel,java.awt.image.PixelInterleavedSampleModel,java.awt.image.ComponentSampleModel \
  --initialize-at-build-time=java.awt.image.IndexColorModel \
  --initialize-at-build-time=sun.java2d.cmm.lcms.LCMSTransform,sun.java2d.cmm.ColorTransform,java.awt.color.ICC_Profile,sun.java2d.cmm.lcms.LCMSProfile,sun.java2d.cmm.Profile
```
and reflect-config.json
```
{
    "name": "java.awt.image.ColorModel",
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true,
    "allDeclaredFields": true
  },
  {
    "name": "java.awt.image.Raster",
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true,
    "allDeclaredFields": true
  },
  {
    "name": "java.awt.Transparency",
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true,
    "allDeclaredFields": true
  },
  {
    "name": "java.awt.image.SampleModel",
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true,
    "allDeclaredFields": true
  },
  {
    "name": "java.awt.image.PixelInterleavedSampleModel",
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true,
    "allDeclaredFields": true
  },
  {
    "name": "java.awt.image.ComponentSampleModel",
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true,
    "allDeclaredFields": true
  },
  {
    "name": "sun.java2d.cmm.lcms.LCMSTransform",
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true,
    "allDeclaredFields": true
  },
  {
    "name": "sun.java2d.cmm.ColorTransform",
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true,
    "allDeclaredFields": true
  },
  {
    "name": "java.awt.color.ICC_Profile",
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true,
    "allDeclaredFields": true
  },
  {
    "name": "sun.java2d.cmm.lcms.LCMSProfile",
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true,
    "allDeclaredFields": true
  },
  {
    "name": "sun.java2d.cmm.Profile",
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true,
    "allDeclaredFields": true
  }
```

All other problems starting from `sun.java2d.Disposer` were fixed with this configuration. Only thing that is ignored is `sun.java2d.cmm.lcms.LCMSTransform` config.

**Describe GraalVM and your environment:**
 - everything is built in docker `FROM ghcr.io/graalvm/graalvm-ce:java11-21.1.0 AS graalvm`
 - gradle-6.8.3 for gradle assemble
 - Architecture: **AMD64**

**More details**

```
    api_1  | 15:37:52.571 [default-nioEventLoopGroup-1-2] ERROR i.m.h.s.netty.RoutingInBoundHandler - traceId=asd executionId=58de4e3a-d2f8-4c33-964d-f63f1d036feb Unexpected error occurred: sun.java2d.cmm.lcms.LCMSTransform.renderType 
api_1  | java.lang.NoSuchFieldError: sun.java2d.cmm.lcms.LCMSTransform.renderType
api_1  | 	at com.oracle.svm.jni.functions.JNIFunctions$Support.getFieldID(JNIFunctions.java:1125)
api_1  | 	at com.oracle.svm.jni.functions.JNIFunctions.GetFieldID(JNIFunctions.java:429)
api_1  | 	at sun.java2d.cmm.lcms.LCMS.initLCMS(LCMS.java)
api_1  | 	at sun.java2d.cmm.lcms.LCMS.getModule(LCMS.java:214)
api_1  | 	at sun.java2d.cmm.lcms.LcmsServiceProvider.getModule(LcmsServiceProvider.java:34)
api_1  | 	at sun.java2d.cmm.CMMServiceProvider.getColorManagementModule(CMMServiceProvider.java:31)
api_1  | 	at sun.java2d.cmm.CMSManager.getModule(CMSManager.java:68)
api_1  | 	at java.awt.color.ICC_Profile.activateDeferredProfile(ICC_Profile.java:1104)
api_1  | 	at java.awt.color.ICC_Profile$1.activate(ICC_Profile.java:746)
api_1  | 	at sun.java2d.cmm.ProfileDeferralMgr.activateProfiles(ProfileDeferralMgr.java:95)
api_1  | 	at java.awt.color.ICC_Profile.getInstance(ICC_Profile.java:784)
api_1  | 	at com.sun.imageio.plugins.tiff.TIFFImageReader.getImageTypes(TIFFImageReader.java:743)
api_1  | 	at com.sun.imageio.plugins.tiff.TIFFImageReader.prepareRead(TIFFImageReader.java:979)
api_1  | 	at com.sun.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1140)
api_1  | 	at javax.imageio.ImageIO.read(ImageIO.java:1468)
api_1  | 	at javax.imageio.ImageIO.read(ImageIO.java:1363)
```

**Comment by mcraj017** [comment]
@khorvat1 Please provide a reproducer

**Comment by khorvat1** [comment]
@mcraj017 its here on branch graal-image https://github.com/khorvat1/micronaut-test/tree/graal-image
I have added 2 endpoints, /gif and /tiff, you can make http get call after you build docker image.

**Comment by khorvat1** [comment]
I found a [solution](https://github.com/vektory79/plantuml-native-image/blob/master/src/main/java/me/vektory79/plantuml/Main.java) with workaround for reported issue.
I tried to apply something like this in new [branch](https://github.com/khorvat1/micronaut-test/tree/graal-image-draw), it passes reported issue, but it throws a new exception
```
api_1  | java.lang.NoClassDefFoundError: Could not initialize class java.awt.GraphicsEnvironment$LocalGE
api_1  | 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:239)
api_1  | 	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
api_1  | 	at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
```

**Comment by pquiring** [comment]
Have you tried to use the graal agent to generate the jni-config.json files for you?  Much better than trying to do it by hand.

**Comment by khorvat1** [comment]
Agentlib helped, generated jni-config and reflect-config files solved the issue. I just had to replace CGraphicsEnvironment with X11GraphicsEnvironment to make it work in a container.
Thanks @pquiring

**Comment by ggrossetie** [comment]
@khorvat1 Hey! I have the same issue and I'm already using agentlib. Here's my stacktrace:

```
java.lang.reflect.InvocationTargetException
	at java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568)
	at net.sourceforge.plantuml.pdf.PdfConverter.convert(PdfConverter.java:77)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramInternalPdf(UmlDiagram.java:289)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:138)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:198)
	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:165)
	at net.sourceforge.plantuml.Pipe.generateDiagram(Pipe.java:103)
	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:94)
	at net.sourceforge.plantuml.Run.managePipe(Run.java:357)
	at net.sourceforge.plantuml.Run.main(Run.java:184)
Caused by: java.lang.NoSuchFieldError: sun.java2d.cmm.lcms.LCMSTransform.renderType
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$Support.getFieldID(JNIFunctions.java:1271)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.GetFieldID(JNIFunctions.java:425)
	at java.desktop@17.0.7/sun.java2d.cmm.lcms.LCMS.initLCMS(LCMS.java)
	at java.desktop@17.0.7/sun.java2d.cmm.lcms.LCMS.getModule(LCMS.java:179)
	at java.desktop@17.0.7/sun.java2d.cmm.lcms.LcmsServiceProvider.getModule(LcmsServiceProvider.java:34)
	at java.desktop@17.0.7/sun.java2d.cmm.CMMServiceProvider.getColorManagementModule(CMMServiceProvider.java:31)
	at java.desktop@17.0.7/sun.java2d.cmm.CMSManager.createModule(CMSManager.java:63)
	at java.desktop@17.0.7/sun.java2d.cmm.CMSManager.getModule(CMSManager.java:40)
	at java.desktop@17.0.7/java.awt.color.ICC_Profile.cmmProfile(ICC_Profile.java:955)
	at java.desktop@17.0.7/java.awt.color.ICC_Profile.getData(ICC_Profile.java:1102)
	at java.desktop@17.0.7/java.awt.color.ICC_Profile.getMajorVersion(ICC_Profile.java:971)
	at org.apache.xmlgraphics.java2d.color.profile.ColorProfileUtil.isDefaultsRGB(ColorProfileUtil.java:76)
	at org.apache.fop.render.pdf.AbstractImageAdapter.setupColorProfile(AbstractImageAdapter.java:157)
	at org.apache.fop.render.pdf.AbstractImageAdapter.setup(AbstractImageAdapter.java:101)
	at org.apache.fop.render.pdf.ImageRenderedAdapter.setup(ImageRenderedAdapter.java:119)
	at org.apache.fop.pdf.PDFDocument.addImage(PDFDocument.java:902)
	at org.apache.fop.svg.PDFGraphics2D.addRenderedImage(PDFGraphics2D.java:1214)
	at org.apache.fop.svg.PDFGraphics2D.drawImage(PDFGraphics2D.java:572)
	at org.apache.fop.svg.PDFGraphics2D.drawImage(PDFGraphics2D.java:530)
	at org.apache.batik.ext.awt.image.GraphicsUtil.drawImage(GraphicsUtil.java:158)
	at org.apache.batik.ext.awt.image.GraphicsUtil.drawImage(GraphicsUtil.java:455)
	at org.apache.batik.gvt.RasterImageNode.primitivePaint(RasterImageNode.java:104)
	at org.apache.batik.gvt.AbstractGraphicsNode.paint(AbstractGraphicsNode.java:509)
	at org.apache.batik.gvt.CompositeGraphicsNode.primitivePaint(CompositeGraphicsNode.java:165)
	at org.apache.batik.gvt.AbstractGraphicsNode.paint(AbstractGraphicsNode.java:509)
	at org.apache.batik.gvt.ImageNode.paint(ImageNode.java:71)
	at org.apache.batik.gvt.CompositeGraphicsNode.primitivePaint(CompositeGraphicsNode.java:165)
	at org.apache.batik.gvt.AbstractGraphicsNode.paint(AbstractGraphicsNode.java:509)
	at org.apache.batik.gvt.CompositeGraphicsNode.primitivePaint(CompositeGraphicsNode.java:165)
	at org.apache.batik.gvt.AbstractGraphicsNode.paint(AbstractGraphicsNode.java:509)
	at org.apache.batik.gvt.CompositeGraphicsNode.primitivePaint(CompositeGraphicsNode.java:165)
	at org.apache.batik.gvt.CanvasGraphicsNode.primitivePaint(CanvasGraphicsNode.java:159)
	at org.apache.batik.gvt.AbstractGraphicsNode.paint(AbstractGraphicsNode.java:509)
	at org.apache.batik.gvt.CompositeGraphicsNode.primitivePaint(CompositeGraphicsNode.java:165)
	at org.apache.batik.gvt.AbstractGraphicsNode.paint(AbstractGraphicsNode.java:509)
	at org.apache.fop.svg.PDFTranscoder.transcode(PDFTranscoder.java:184)
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:142)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:158)
	at org.apache.batik.apps.rasterizer.SVGConverter.transcode(SVGConverter.java:1008)
	at org.apache.batik.apps.rasterizer.SVGConverter.execute(SVGConverter.java:719)
	... 10 more
Exception in thread "main" java.lang.UnsupportedOperationException
	at net.sourceforge.plantuml.pdf.PdfConverter.convert(PdfConverter.java:80)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramInternalPdf(UmlDiagram.java:289)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:138)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:198)
	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:165)
	at net.sourceforge.plantuml.Pipe.generateDiagram(Pipe.java:103)
	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:94)
	at net.sourceforge.plantuml.Run.managePipe(Run.java:357)
	at net.sourceforge.plantuml.Run.main(Run.java:184)
```

I can only reproduce it on a container (without X). On my desktop machine, it's working fine.

> I just had to replace CGraphicsEnvironment with X11GraphicsEnvironment to make it work in a container.

Could you please explain how did you do it? Thanks!

**Comment by khorvat1** [comment]
@ggrossetie in reflection-config where agent generated CGraphicsEnvironment I replaced it with X11GraphicsEnvironment, like this
`  {
    "name": "sun.awt.X11GraphicsEnvironment",
    "methods": [
      {
        "name": "<init>",
        "parameterTypes": []
      }
    ]
  }`
