### ISSUE TITLE
Upgrade to 21.1.0, native image linker unable to find static libraries in CLibraryPath

### ISSUE THREAD

**Issue by huahaiy** [oracle/graal#3413]
**Describe the issue**
When option `CLibraryPath` is set correctly, the native image build used to be able to find static libraries in that path, and link to them correctly, under 21.0.0.2. 

After upgrading to 21.1.0, this breaks. The linker reports that the libraries are missing:  "It appears as though libdtlv.a is missing. Please install it.", but the libdtlv.a file is right there in the path `CLibraryPath` points to.

**Steps to reproduce the issue**
Please include both build steps as well as run steps:

0. Install Leiningen built tool https://leiningen.org/
1. git clone https://github.com/juji-io/datalevin
2. cd datalevin/native
3. script/compile

**Describe GraalVM and your environment:**
 - GraalVM version 21.1.0
 - JDK major version: 11
 - OS: Ubuntu 20.20
 - Architecture: AMD64

**More details**

```
Executing [
/opt/graalvm-ce-java11-21.1.0/bin/java \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
--add-exports=java.base/jdk.internal.module=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.site=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.stack=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.common=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.sparc=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.runtime=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.services=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.sparc=ALL-UNNAMED \
--add-opens=jdk.internal.vm.compiler/org.graalvm.compiler.debug=ALL-UNNAMED \
--add-opens=jdk.internal.vm.compiler/org.graalvm.compiler.nodes=ALL-UNNAMED \
--add-opens=jdk.unsupported/sun.reflect=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.module=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.ref=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.reflect=ALL-UNNAMED \
--add-opens=java.base/java.io=ALL-UNNAMED \
--add-opens=java.base/java.lang=ALL-UNNAMED \
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED \
--add-opens=java.base/java.lang.invoke=ALL-UNNAMED \
--add-opens=java.base/java.lang.ref=ALL-UNNAMED \
--add-opens=java.base/java.net=ALL-UNNAMED \
--add-opens=java.base/java.nio=ALL-UNNAMED \
--add-opens=java.base/java.nio.file=ALL-UNNAMED \
--add-opens=java.base/java.security=ALL-UNNAMED \
--add-opens=java.base/javax.crypto=ALL-UNNAMED \
--add-opens=java.base/java.util=ALL-UNNAMED \
--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED \
--add-opens=java.base/sun.security.x509=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.logger=ALL-UNNAMED \
--add-opens=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED \
--add-opens=org.graalvm.sdk/org.graalvm.polyglot=ALL-UNNAMED \
--add-opens=org.graalvm.truffle/com.oracle.truffle.polyglot=ALL-UNNAMED \
--add-opens=org.graalvm.truffle/com.oracle.truffle.api.impl=ALL-UNNAMED \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx14g \
-Duser.country=US \
-Duser.language=en \
-Djava.awt.headless=true \
-Dorg.graalvm.version=21.1.0 \
-Dorg.graalvm.config=CE \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Dawt.toolkit=sun.awt.X11.XToolkit \
-Djava.awt.graphicsenv=sun.awt.X11GraphicsEnvironment \
-Djava.awt.printerjob=sun.print.PSPrinterJob \
-Xshare:off \
--module-path \
/opt/graalvm-ce-java11-21.1.0/lib/truffle/truffle-api.jar \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-Dclojure.spec.skip-macros=true \
-Dclojure.compiler.direct-linking=true \
-Xmx4g \
-javaagent:/opt/graalvm-ce-java11-21.1.0/lib/svm/builder/svm.jar \
-cp \
/opt/graalvm-ce-java11-21.1.0/lib/svm/builder/svm.jar:/opt/graalvm-ce-java11-21.1.0/lib/svm/builder/llvm-platform-specific-shadowed.jar:/opt/graalvm-ce-java11-21.1.0/lib/svm/builder/objectfile.jar:/opt/graalvm-ce-java11-21.1.0/lib/svm/builder/javacpp-shadowed.jar:/opt/graalvm-ce-java11-21.1.0/lib/svm/builder/llvm-wrapper-shadowed.jar:/opt/graalvm-ce-java11-21.1.0/lib/svm/builder/svm-llvm.jar:/opt/graalvm-ce-java11-21.1.0/lib/svm/builder/pointsto.jar \
'com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus' \
-watchpid \
1185870 \
-imagecp \
/opt/graalvm-ce-java11-21.1.0/lib/svm/library-support.jar:/home/hyang/workspace/datalevin/native/target/main.uberjar.jar \
-H:Path=/home/hyang/workspace/datalevin/native \
-H:Name=dtlv \
-H:+ReportExceptionStackTraces \
-H:ConfigurationFileDirectories=config \
-H:Log=registerResource:verbose \
-H:+PrintClassInitialization \
-H:CLibraryPath=src/c \
-H:ClassInitialization=:build_time \
-H:+ReportUnsupportedElementsAtRuntime \
-H:+AllowIncompleteClasspath \
-H:FallbackThreshold=0 \
-H:+DumpTargetInfo \
'-H:Class@manifest from file:///home/hyang/workspace/datalevin/native/target/main.uberjar.jar=datalevin.main' \
'-H:Name@manifest from file:///home/hyang/workspace/datalevin/native/target/main.uberjar.jar=main.uberjar' \
'-H:ClassInitialization@jar:file:///home/hyang/workspace/datalevin/native/target/main.uberjar.jar!/META-INF/native-image/org.graalvm.polyglot/native-image.properties=org.graalvm.polyglot:build_time' \
'-H:Features@jar:file:///home/hyang/workspace/datalevin/native/target/main.uberjar.jar!/META-INF/native-image/org.graalvm.home/native-image.properties=org.graalvm.home.HomeFinderFeature' \
-H:CLibraryPath=/opt/graalvm-ce-java11-21.1.0/lib/svm/clibraries/linux-amd64 \
'-H:Name@explicit image name=dtlv' \
]
[dtlv:1185893]    classlist:   1,512.85 ms,  0.96 GB
[dtlv:1185893]        (cap):     741.57 ms,  0.96 GB
WARNING: Method java.lang.reflect.Method.canAccess(Object) not found.
[dtlv:1185893]        setup:   2,096.49 ms,  0.96 GB
# Building image for target platform: org.graalvm.nativeimage.Platform$LINUX_AMD64
# Using native toolchain:
#   Name: GNU project C and C++ compiler (gcc)
#   Vendor: linux
#   Version: 9.3.0
#   Target architecture: x86_64
#   Path: /usr/bin/gcc
# Using CLibrary: com.oracle.svm.core.posix.linux.libc.GLibC
# Printing initializer configuration to: reports/initializer_configuration_20210514_111523.txt
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of org.lmdbjava.ByteBufferProxy$UnsafeProxy. Add a RecomputeFieldValue.FieldOffset manual substitution for org.lmdbjava.ByteBufferProxy$UnsafeProxy.ADDRESS_OFFSET. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field.
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of org.lmdbjava.ByteBufferProxy$UnsafeProxy. Add a RecomputeFieldValue.FieldOffset manual substitution for org.lmdbjava.ByteBufferProxy$UnsafeProxy.CAPACITY_OFFSET. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field.
[Use -Dgraal.LogFile=<path> to redirect Graal log output to a file.]
[thread:31] scope: ForkJoinPool-4-worker-19
  [thread:31] scope: ForkJoinPool-4-worker-19.registerResource
  ServiceLoaderFeature: registerResource: META-INF/services/java.nio.file.spi.FileSystemProvider
  [thread:31] scope: ForkJoinPool-4-worker-19.registerResource
  ServiceLoaderFeature: registerResource: META-INF/services/com.fasterxml.jackson.core.JsonFactory
  [thread:31] scope: ForkJoinPool-4-worker-19.registerResource
  ServiceLoaderFeature: registerResource: META-INF/services/javax.naming.spi.InitialContextFactory
  [thread:31] scope: ForkJoinPool-4-worker-19.registerResource
  ServiceLoaderFeature: registerResource: META-INF/services/jdk.internal.logger.DefaultLoggerFinder
  [thread:31] scope: ForkJoinPool-4-worker-19.registerResource
  Resources have been added by ServiceLoaderFeature. Automatic registration can be disabled with -H:-UseServiceLoaderFeature
  [thread:31] scope: ForkJoinPool-4-worker-19.registerResource
  ResourcesFeature: registerResource: java/lang/uniName.dat
# Printing initializer dependencies to: reports/initializer_dependencies_20210514_111603.dot
# Printing 0 classes that are considered as safe for build-time initialization to: reports/safe_classes_20210514_111603.txt
# Printing 12545 classes of type BUILD_TIME to: reports/build_time_classes_20210514_111603.txt
# Printing 81 classes of type RERUN to: reports/rerun_classes_20210514_111603.txt
# Printing 2 classes of type RUN_TIME to: reports/run_time_classes_20210514_111603.txt
[dtlv:1185893]     (clinit):     593.01 ms,  1.99 GB
# Static libraries:
#   ../../../../../opt/graalvm-ce-java11-21.1.0/lib/svm/clibraries/linux-amd64/liblibchelper.a
#   ../../../../../opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libnet.a
#   ../../../../../opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libextnet.a
#   ../../../../../opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libnio.a
#   ../../../../../opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libjava.a
#   ../../../../../opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libfdlibm.a
#   ../../../../../opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libzip.a
#   ../../../../../opt/graalvm-ce-java11-21.1.0/lib/svm/clibraries/linux-amd64/libjvm.a
# Other libraries: lmdb,dtlv,pthread,dl,z,rt
[dtlv:1185893]   (typeflow):  10,662.43 ms,  1.99 GB
[dtlv:1185893]    (objects):  25,967.10 ms,  1.99 GB
[dtlv:1185893]   (features):   1,051.69 ms,  1.99 GB
[dtlv:1185893]     analysis:  40,180.82 ms,  1.99 GB
[dtlv:1185893]     universe:   1,369.88 ms,  1.99 GB
[dtlv:1185893]      (parse):   3,869.75 ms,  2.28 GB
[dtlv:1185893]     (inline):   5,961.62 ms,  2.97 GB
[dtlv:1185893]    (compile):  19,318.51 ms,  3.18 GB
[dtlv:1185893]      compile:  31,043.12 ms,  3.19 GB
[dtlv:1185893]        image:   5,704.58 ms,  3.09 GB
[dtlv:1185893]        write:     346.73 ms,  3.09 GB
Fatal error:java.lang.RuntimeException: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1

Based on the linker command output, possible reasons for this include:
1. It appears as though libdtlv.a is missing. Please install it.

Linker command executed:
/usr/bin/gcc -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-4599275693962377642/exported_symbols.list -Wl,--exclude-libs,ALL -Wl,-x -o /home/hyang/workspace/datalevin/native/dtlv dtlv.o /opt/graalvm-ce-java11-21.1.0/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libnet.a /opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libextnet.a /opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libnio.a /opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libjava.a /opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libfdlibm.a /opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libzip.a /opt/graalvm-ce-java11-21.1.0/lib/svm/clibraries/linux-amd64/libjvm.a -v -L/tmp/SVM-4599275693962377642 -L/opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc -Lsrc/c -L/opt/graalvm-ce-java11-21.1.0/lib/svm/clibraries/linux-amd64 -llmdb -ldtlv -lpthread -ldl -lz -lrt

Linker command output:
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-HskZEa/gcc-9-9.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-z' 'noexecstack' '-o' '/home/hyang/workspace/datalevin/native/dtlv' '-v' '-L/tmp/SVM-4599275693962377642' '-L/opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc' '-Lsrc/c' '-L/opt/graalvm-ce-java11-21.1.0/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/9/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/9/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper -plugin-opt=-fresolution=/tmp/ccIUlClz.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -z now -z relro -o /home/hyang/workspace/datalevin/native/dtlv -z noexecstack /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/9/crtbeginS.o -L/tmp/SVM-4599275693962377642 -L/opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc -Lsrc/c -L/opt/graalvm-ce-java11-21.1.0/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-linux-gnu/9 -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/9/../../.. --gc-sections --dynamic-list /tmp/SVM-4599275693962377642/exported_symbols.list --exclude-libs ALL -x dtlv.o /opt/graalvm-ce-java11-21.1.0/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libnet.a /opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libextnet.a /opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libnio.a /opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libjava.a /opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libfdlibm.a /opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libzip.a /opt/graalvm-ce-java11-21.1.0/lib/svm/clibraries/linux-amd64/libjvm.a -llmdb -ldtlv -lpthread -ldl -lz -lrt -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-linux-gnu/9/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crtn.o
/usr/bin/ld: cannot find -llmdb
/usr/bin/ld: cannot find -ldtlv
collect2: error: ld returned 1 exit status
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:499)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:370)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:531)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:568)
Caused by: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1

Based on the linker command output, possible reasons for this include:
1. It appears as though libdtlv.a is missing. Please install it.

Linker command executed:
/usr/bin/gcc -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-4599275693962377642/exported_symbols.list -Wl,--exclude-libs,ALL -Wl,-x -o /home/hyang/workspace/datalevin/native/dtlv dtlv.o /opt/graalvm-ce-java11-21.1.0/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libnet.a /opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libextnet.a /opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libnio.a /opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libjava.a /opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libfdlibm.a /opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libzip.a /opt/graalvm-ce-java11-21.1.0/lib/svm/clibraries/linux-amd64/libjvm.a -v -L/tmp/SVM-4599275693962377642 -L/opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc -Lsrc/c -L/opt/graalvm-ce-java11-21.1.0/lib/svm/clibraries/linux-amd64 -llmdb -ldtlv -lpthread -ldl -lz -lrt

Linker command output:
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdc
xx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-HskZEa/gcc-9-9.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-z' 'noexecstack' '-o' '/home/hyang/workspace/datalevin/native/dtlv' '-v' '-L/tmp/SVM-4599275693962377642' '-L/opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc' '-Lsrc/c' '-L/opt/graalvm-ce-java11-21.1.0/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/9/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/9/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper -plugin-opt=-fresolution=/tmp/ccIUlClz.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -z now -z relro -o /home/hyang/workspace/datalevin/native/dtlv -z noexecstack /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/9/crtbeginS.o -L/tmp/SVM-4599275693962377642 -L/opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc -Lsrc/c -L/opt/graalvm-ce-java11-21.1.0/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-linux-gnu/9 -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/9/../../.. --gc-sections --dynamic-list /tmp/SVM-4599275693962377642/exported_symbols.list --exclude-libs ALL -x dtlv.o /opt/graalvm-ce-java11-21.1.0/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libnet.a /opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libextnet.a /opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libnio.a /opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libjava.a /opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libfdlibm.a /opt/graalvm-ce-java11-21.1.0/lib/static/linux-amd64/glibc/libzip.a /opt/graalvm-ce-java11-21.1.0/lib/svm/clibraries/linux-amd64/libjvm.a -llmdb -ldtlv -lpthread -ldl -lz -lrt -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-linux-gnu/9/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crtn.o
/usr/bin/ld: cannot find -llmdb
/usr/bin/ld: cannot find -ldtlv
collect2: error: ld returned 1 exit status
	at com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:513)
	at com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:460)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:710)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:495)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1772)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1519)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1480)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1467)
	at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1959)
```

**Comment by huahaiy** [comment]
More information: Absolute path seems to work, but 21.1.0 fails to resolve relative path.

**Comment by GoodforGod** [comment]
Bumped into the same problems but while building under _amazonlinux:2018.03.0.20210408.0_ have to downgrade to GraalVM 21.0.0.2

**Comment by oubidar-Abderrahim** [comment]
If this issue is still relevant in the latest GraalVM versions, please create a new issue for it and follow the template provided. Thank you

**Comment by oubidar-Abderrahim** [comment]
If this issue is still relevant in the latest GraalVM versions, please create a new issue for it and follow the template provided. Thank you
