### ISSUE TITLE
GraalVM gate CI workflow failing due to a pylint check in mx_sulong_suite_constituents.py

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#3423]
**Describe the issue**
GraalVM gate CI workflow is failing with:

```
************* Module mx_sulong_suite_constituents
I: 49, 0: Locally disabling E0602 (locally-disabled)
I:191, 0: Locally disabling R0901 (locally-disabled)
E:133,15: Access to member 'results' before its definition line 134 (access-member-before-definition)

Traceback (most recent call last):
  File "/home/runner/work/graal/graal/mx/mx_gate.py", line 422, in gate
gate: 20 May 2021 01:16:37(+00:16) END:   Pylint [0:00:16.217429] [disk (free/total): 18.7GB/83.2GB]
    _run_gate(cleanArgs, args, tasks)
  File "/home/runner/work/graal/graal/mx/mx_gate.py", line 569, in _run_gate
    if mx.command_function('pylint')(['--primary']) != 0:
  File "/home/runner/work/graal/graal/mx/mx_commands.py", line 147, in __call__
    return self.command_function(*args, **kwargs)
  File "/home/runner/work/graal/graal/mx/mx.py", line 14469, in pylint
    run([pylint_exe, '--reports=n', '--rcfile=' + rcfile, pyfile] + additional_options, env=env)
  File "/home/runner/work/graal/graal/mx/mx.py", line 13035, in run
gate: 20 May 2021 01:16:37(+00:16) ABORT: Gate [0:00:16.954330] [disk (free/total): 18.7GB/83.2GB]
    abort(retcode)
  File "/home/runner/work/graal/graal/mx/mx.py", line 4085, in abort
    raise SystemExit(error_code)
SystemExit: 2

The sequence of mx commands that were executed until the failure follows:

mx --primary-suite-path sulong --J @-Xmx2g --java-home=/home/runner/work/graal/graal/jdk version --oneline
mx --primary-suite-path sulong --J @-Xmx2g --java-home=/home/runner/work/graal/graal/jdk sversions
mx --primary-suite-path sulong --J @-Xmx2g --java-home=/home/runner/work/graal/graal/jdk verifymultireleaseprojects
mx --primary-suite-path sulong --J @-Xmx2g --java-home=/home/runner/work/graal/graal/jdk pylint --primary

If the previous sequence is incomplete or some commands were executed programmatically use:

mx --primary-suite-path sulong --J @-Xmx2g --java-home=/home/runner/work/graal/graal/jdk gate --strict-mode --tags style,fullbuild,sulongBasic
```

**Describe GraalVM and your environment:**
GitHub actions runner 

 - GraalVM version: `master`
 - JDK major version: **8**
 - OS: **ubuntu**
 - Architecture: **AMD64**

**Comment by rschatz** [comment]
I'm guessing this is because we are using different versions of `pylint` in the internal gate and in the github actions workflow. I'm currently trying to update the version in github actions to be the same, to check whether that's the problem.

Ideally we should run exactly the same thing in our internal gate and in the github actions, so this can't happen again in the future. It's tricky in detail, because the specification language is different (jsonnet vs yaml), but I'm sure at least version synchronization of the dependency versions should be possible.
