### ISSUE TITLE
Errors in Native Image (Void Linux)

### ISSUE THREAD

**Issue by Zelakolase** [oracle/graal#3426]
**Description**
The command `native-image --static --enable-all-security services main` gives me the following error : 
```
Fatal error:java.lang.RuntimeException: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1
Based on the linker command output, possible reasons for this include:
It appears as though libz.a is missing. Please install it.
```

**My personal analysis**
1. `zlib.so` doesn't exist in `/lib/`
2. `zlib.so` doesn't exist in `./lib`
3. This command
```
[morad@zelakolase src]$ sudo ld -lz
ld: cannot find -lz
```
**My environment**
- Void Linux 5.11.22_1
- GraalVM CE Java 11 AMD64 21.1.0

LOG :
```
    Fatal error:java.lang.RuntimeException: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1

Based on the linker command output, possible reasons for this include:
1. It appears as though libz.a is missing. Please install it.

Linker command executed:
/bin/gcc -z noexecstack -Wl,--gc-sections -Wl,-x -o /home/morad/eclipse-workspace/Sandbox/src/spy spy.o /home/morad/graal/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/morad/graal/lib/static/linux-amd64/glibc/libnet.a /home/morad/graal/lib/static/linux-amd64/glibc/libextnet.a /home/morad/graal/lib/static/linux-amd64/glibc/libnio.a /home/morad/graal/lib/static/linux-amd64/glibc/libjava.a /home/morad/graal/lib/static/linux-amd64/glibc/libfdlibm.a /home/morad/graal/lib/static/linux-amd64/glibc/libzip.a /home/morad/graal/lib/svm/clibraries/linux-amd64/libjvm.a -static -v -L/tmp/SVM-9742347668187858563 -L/home/morad/graal/lib/static/linux-amd64/glibc -L/home/morad/graal/lib/svm/clibraries/linux-amd64 -lpthread -ldl -lz -lrt

Linker command output:
Using built-in specs.
COLLECT_GCC=/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: /builddir/gcc-10.2.1_pre1/configure --build=x86_64-unknown-linux-gnu --enable-gnu-unique-object --enable-vtable-verify --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --libexecdir=/usr/lib64 --libdir=/usr/lib64 --enable-threads=posix --enable-__cxa_atexit --disable-multilib --with-system-zlib --enable-shared --enable-lto --enable-plugins --enable-linker-build-id --disable-werror --disable-nls --enable-default-pie --enable-default-ssp --enable-checking=release --disable-libstdcxx-pch --with-isl --with-linker-hash-style=gnu --disable-sjlj-exceptions --disable-target-libiberty --enable-languages=c,c++,objc,obj-c++,fortran,lto,go,ada
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.2.1 20201203 (GCC) 
COMPILER_PATH=/usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/:/usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/:/usr/lib64/gcc/x86_64-unknown-linux-gnu/:/usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/:/usr/lib64/gcc/x86_64-unknown-linux-gnu/
LIBRARY_PATH=/usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/:/usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-z' 'noexecstack' '-o' '/home/morad/eclipse-workspace/Sandbox/src/spy' '-static' '-v' '-L/tmp/SVM-9742347668187858563' '-L/home/morad/graal/lib/static/linux-amd64/glibc' '-L/home/morad/graal/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/collect2 -plugin /usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/liblto_plugin.so -plugin-opt=/usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/lto-wrapper -plugin-opt=-fresolution=/tmp/ccwgHkJW.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_eh -plugin-opt=-pass-through=-lc --build-id --hash-style=gnu -m elf_x86_64 -static -o /home/morad/eclipse-workspace/Sandbox/src/spy -z noexecstack /usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/../../../../lib64/crt1.o /usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/../../../../lib64/crti.o /usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/crtbeginT.o -L/tmp/SVM-9742347668187858563 -L/home/morad/graal/lib/static/linux-amd64/glibc -L/home/morad/graal/lib/svm/clibraries/linux-amd64 -L/usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1 -L/usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/../../.. --gc-sections -x spy.o /home/morad/graal/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/morad/graal/lib/static/linux-amd64/glibc/libnet.a /home/morad/graal/lib/static/linux-amd64/glibc/libextnet.a /home/morad/graal/lib/static/linux-amd64/glibc/libnio.a /home/morad/graal/lib/static/linux-amd64/glibc/libjava.a /home/morad/graal/lib/static/linux-amd64/glibc/libfdlibm.a /home/morad/graal/lib/static/linux-amd64/glibc/libzip.a /home/morad/graal/lib/svm/clibraries/linux-amd64/libjvm.a -lpthread -ldl -lz -lrt --start-group -lgcc -lgcc_eh -lc --end-group /usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/crtend.o /usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/../../../../lib64/crtn.o
/bin/ld: spy.o:(.data+0x4c0): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/bin/ld: cannot find -lz
/bin/ld: /home/morad/graal/lib/static/linux-amd64/glibc/libnio.a(UnixNativeDispatcher.o): in function `Java_sun_nio_fs_UnixNativeDispatcher_getgrgid':
UnixNativeDispatcher.c:(.text.Java_sun_nio_fs_UnixNativeDispatcher_getgrgid+0x8a): warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/bin/ld: /home/morad/graal/lib/static/linux-amd64/glibc/libnio.a(UnixNativeDispatcher.o): in function `Java_sun_nio_fs_UnixNativeDispatcher_getgrnam0':
UnixNativeDispatcher.c:(.text.Java_sun_nio_fs_UnixNativeDispatcher_getgrnam0+0x8a): warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/bin/ld: spy.o:(.data+0x3f8): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/bin/ld: /home/morad/graal/lib/static/linux-amd64/glibc/libnio.a(UnixNativeDispatcher.o): in function `Java_sun_nio_fs_UnixNativeDispatcher_getpwnam0':
UnixNativeDispatcher.c:(.text.Java_sun_nio_fs_UnixNativeDispatcher_getpwnam0+0x8a): warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/bin/ld: /home/morad/graal/lib/static/linux-amd64/glibc/libnio.a(UnixNativeDispatcher.o): in function `Java_sun_nio_fs_UnixNativeDispatcher_getpwuid':
UnixNativeDispatcher.c:(.text.Java_sun_nio_fs_UnixNativeDispatcher_getpwuid+0x8a): warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/bin/ld: /home/morad/graal/lib/static/linux-amd64/glibc/libnet.a(Inet4AddressImpl.o): in function `Java_java_net_Inet4AddressImpl_lookupAllHostAddr':
Inet4AddressImpl.c:(.text.Java_java_net_Inet4AddressImpl_lookupAllHostAddr+0x92): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:499)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:370)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:531)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:568)
Caused by: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1

Based on the linker command output, possible reasons for this include:
1. It appears as though libz.a is missing. Please install it.

Linker command executed:
/bin/gcc -z noexecstack -Wl,--gc-sections -Wl,-x -o /home/morad/eclipse-workspace/Sandbox/src/spy spy.o /home/morad/graal/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/morad/graal/lib/static/linux-amd64/glibc/libnet.a /home/morad/graal/lib/static/linux-amd64/glibc/libextnet.a /home/morad/graal/lib/static/linux-amd64/glibc/libnio.a /home/morad/graal/lib/static/linux-amd64/glibc/libjava.a /home/morad/graal/lib/static/linux-amd64/glibc/libfdlibm.a /home/morad/graal/lib/static/linux-amd64/glibc/libzip.a /home/morad/graal/lib/svm/clibraries/linux-amd64/libjvm.a -static -v -L/tmp/SVM-9742347668187858563 -L/home/morad/graal/lib/static/linux-amd64/glibc -L/home/morad/graal/lib/svm/clibraries/linux-amd64 -lpthread -ldl -lz -lrt

Linker command output:
Using built-in specs.
COLLECT_GCC=/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: /builddir/gcc-10.2.1_pre1/configure --build=x86_64-unknown-linux-gnu --enable-gnu-unique-object --enable-vtable-verify --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --libexecdir=/usr/lib64 --libdir=/usr/lib64 --enable-threads=posix --enable-__cxa_atexit --disable-multilib --with-system-zlib --enable-shared --enable-lto --enable-plugins --enable-linker-build-id --disable-werror --disable-nls --enable-default-pie --enable-default-ssp --enable-checking=release --disable-libstdcxx-pch --with-isl --with-linker-hash-style=gnu --disable-sjlj-exceptions --disable-target-libiberty --enable-languages=c,c++,objc,obj-c++,fortran,lto,go,ada
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.2.1 20201203 (GCC) 
COMPILER_PATH=/usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/:/usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/:/usr/lib64/gcc/x86_64-unknown-linux-gnu/:/usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/:/usr/lib64/gcc/x86_64-unknown-linux-gnu/
LIBRARY_PATH=/usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/:/usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-z' 'noexecstack' '-o' '/home/morad/eclipse-workspace/Sandbox/src/spy' '-static' '-v' '-L/tmp/SVM-9742347668187858563' '-L/home/morad/graal/lib/static/linux-amd64/glibc' '-L/home/morad/graal/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/collect2 -plugin /usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/liblto_plugin.so -plugin-opt=/usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/lto-wrapper -plugin-opt=-fresolution=/tmp/ccwgHkJW.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_eh -plugin-opt=-pass-through=-lc --build-id --hash-style=gnu -m elf_x86_64 -static -o /home/morad/eclipse-workspace/Sandbox/src/spy -z noexecstack /usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/../../../../lib64/crt1.o /usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/../../../../lib64/crti.o /usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/crtbeginT.o -L/tmp/SVM-9742347668187858563 -L/home/morad/graal/lib/static/linux-amd64/glibc -L/home/morad/graal/lib/svm/clibraries/linux-amd64 -L/usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1 -L/usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/../../.. --gc-sections -x spy.o /home/morad/graal/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/morad/graal/lib/static/linux-amd64/glibc/libnet.a /home/morad/graal/lib/static/linux-amd64/glibc/libextnet.a /home/morad/graal/lib/static/linux-amd64/glibc/libnio.a /home/morad/graal/lib/static/linux-amd64/glibc/libjava.a /home/morad/graal/lib/static/linux-amd64/glibc/libfdlibm.a /home/morad/graal/lib/static/linux-amd64/glibc/libzip.a /home/morad/graal/lib/svm/clibraries/linux-amd64/libjvm.a -lpthread -ldl -lz -lrt --start-group -lgcc -lgcc_eh -lc --end-group /usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/crtend.o /usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/../../../../lib64/crtn.o
/bin/ld: spy.o:(.data+0x4c0): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/bin/ld: cannot find -lz
/bin/ld: /home/morad/graal/lib/static/linux-amd64/glibc/libnio.a(UnixNativeDispatcher.o): in function `Java_sun_nio_fs_UnixNativeDispatcher_getgrgid':
UnixNativeDispatcher.c:(.text.Java_sun_nio_fs_UnixNativeDispatcher_getgrgid+0x8a): warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/bin/ld: /home/morad/graal/lib/static/linux-amd64/glibc/libnio.a(UnixNativeDispatcher.o): in function `Java_sun_nio_fs_UnixNativeDispatcher_getgrnam0':
UnixNativeDispatcher.c:(.text.Java_sun_nio_fs_UnixNativeDispatcher_getgrnam0+0x8a): warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/bin/ld: spy.o:(.data+0x3f8): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/bin/ld: /home/morad/graal/lib/static/linux-amd64/glibc/libnio.a(UnixNativeDispatcher.o): in function `Java_sun_nio_fs_UnixNativeDispatcher_getpwnam0':
UnixNativeDispatcher.c:(.text.Java_sun_nio_fs_UnixNativeDispatcher_getpwnam0+0x8a): warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/bin/ld: /home/morad/graal/lib/static/linux-amd64/glibc/libnio.a(UnixNativeDispatcher.o): in function `Java_sun_nio_fs_UnixNativeDispatcher_getpwuid':
UnixNativeDispatcher.c:(.text.Java_sun_nio_fs_UnixNativeDispatcher_getpwuid+0x8a): warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/bin/ld: /home/morad/graal/lib/static/linux-amd64/glibc/libnet.a(Inet4AddressImpl.o): in function `Java_java_net_Inet4AddressImpl_lookupAllHostAddr':
Inet4AddressImpl.c:(.text.Java_java_net_Inet4AddressImpl_lookupAllHostAddr+0x92): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status
	at com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:513)
	at com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:460)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:710)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:495)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
```

**Comment by pquiring** [comment]
Building a --static executable requires static (*.a) not shared (*.so) library files.  You need to find (most likely build) libz.a which is not available by default in any linux repo that I know of.

**Comment by mcraj017** [comment]
@Zelakolase does the solution provided by @pquiring works for you?

**Comment by Zelakolase** [comment]
Yes, It does!
I just needed to install a package through xbps-install
