### ISSUE TITLE
Error: Undefined symbols for architecture x86_64: "_Java_java_util_prefs_MacOSXPreferencesFile_anyHost"

### ISSUE THREAD

**Issue by mmews-n4** [oracle/graal#3432]
**Description**

Native image compiler crashes after `write` stage. Command was:

`${JAVA_HOME}/bin/native-image -jar _n4jsc.jar --no-fallback --initialize-at-build-time=org.eclipse.n4js.packagejson.PackageJsonUtils,sun.instrument.InstrumentationImpl --report-unsupported-elements-at-runtime`

This issues seems similar to https://github.com/oracle/graal/issues/2063

**Steps to reproduce the issue**

0. setup graal and native tool (see version below)
1. download file `_n4jsc.zip` from https://www.dropbox.com/s/15ncs4w2vq1iriz
2. extract to `_n4jsc.jar`
3. run command above

**Describe GraalVM and your environment:**
 - GraalVM version: **graalvm-ce-java11-21.2.0-dev**
 - JDK major version: **11**
 - OS: **macOS 11.2.1 (20D74)**
 - Architecture: **AMD64**

**Output**
```
${JAVA_HOME}/bin/native-image -jar _n4jsc.jar --no-fallback --initialize-at-build-time=org.eclipse.n4js.packagejson.PackageJsonUtils,sun.instrument.InstrumentationImpl --report-unsupported-elements-at-runtime
[_n4jsc:48058]    classlist:   1,554.70 ms,  0.96 GB
[_n4jsc:48058]        (cap):   1,079.93 ms,  0.96 GB
[_n4jsc:48058]        setup:   2,375.80 ms,  0.96 GB
[_n4jsc:48058]     (clinit):   1,684.52 ms,  6.23 GB
[_n4jsc:48058]   (typeflow):  30,522.80 ms,  6.23 GB
[_n4jsc:48058]    (objects):  40,041.02 ms,  6.23 GB
[_n4jsc:48058]   (features):  11,155.47 ms,  6.23 GB
[_n4jsc:48058]     analysis:  86,242.91 ms,  6.23 GB
[_n4jsc:48058]     universe:   2,997.28 ms,  6.23 GB
[_n4jsc:48058]      (parse):   9,948.77 ms,  6.93 GB
[_n4jsc:48058]     (inline):   7,992.05 ms,  8.09 GB
[_n4jsc:48058]    (compile):  33,911.43 ms,  8.56 GB
[_n4jsc:48058]      compile:  56,919.27 ms,  8.56 GB
[_n4jsc:48058]        image:  15,750.69 ms,  8.30 GB
[_n4jsc:48058]        write:   1,584.53 ms,  8.30 GB
Fatal error:java.lang.RuntimeException: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1

Linker command executed:
/usr/bin/cc -Wl,-no_compact_unwind -Wl,-exported_symbols_list -Wl,/var/folders/sk/pbyf6nzj197c0xtx_gl_dtyc0000gn/T/SVM-7109791393636377228/exported_symbols.list -Wl,-x -arch x86_64 -o /Users/marcusmews/Eclipses/ECL3/git/n4js/target/_n4jsc _n4jsc.o /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/svm/clibraries/darwin-amd64/liblibchelper.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libnet.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/svm/clibraries/darwin-amd64/libdarwin.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libextnet.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libnio.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libjava.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libfdlibm.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libsunec.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libzip.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/svm/clibraries/darwin-amd64/libjvm.a -v -L/var/folders/sk/pbyf6nzj197c0xtx_gl_dtyc0000gn/T/SVM-7109791393636377228 -L/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64 -L/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/svm/clibraries/darwin-amd64 -lstdc++ -lpthread -Wl,-framework,Foundation -ldl -lz

Linker command output:
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
 "/Library/Developer/CommandLineTools/usr/bin/ld" -demangle -lto_library /Library/Developer/CommandLineTools/usr/lib/libLTO.dylib -dynamic -arch x86_64 -platform_version macos 11.0.0 11.1 -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -o /Users/marcusmews/Eclipses/ECL3/git/n4js/target/_n4jsc -L/var/folders/sk/pbyf6nzj197c0xtx_gl_dtyc0000gn/T/SVM-7109791393636377228 -L/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64 -L/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/svm/clibraries/darwin-amd64 -L/usr/local/lib -no_compact_unwind -exported_symbols_list /var/folders/sk/pbyf6nzj197c0xtx_gl_dtyc0000gn/T/SVM-7109791393636377228/exported_symbols.list -x _n4jsc.o /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/svm/clibraries/darwin-amd64/liblibchelper.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libnet.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/svm/clibraries/darwin-amd64/libdarwin.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libextnet.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libnio.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libjava.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libfdlibm.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libsunec.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libzip.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/svm/clibraries/darwin-amd64/libjvm.a -lc++ -lpthread -framework Foundation -ldl -lz -lSystem /Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/lib/darwin/libclang_rt.osx.a
Undefined symbols for architecture x86_64:
  "_Java_java_util_prefs_MacOSXPreferencesFile_anyHost", referenced from:
      ___svm_vm_is_static_binary in _n4jsc.o
  "_Java_java_util_prefs_MacOSXPreferencesFile_anyUser", referenced from:
      ___svm_vm_target_libc in _n4jsc.o
  "_Java_java_util_prefs_MacOSXPreferencesFile_currentHost", referenced from:
      ___data in _n4jsc.o
  "_Java_java_util_prefs_MacOSXPreferencesFile_currentUser", referenced from:
      ___svm_vm_is_static_binary in _n4jsc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:498)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:379)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:540)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:120)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:578)
Caused by: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1

Linker command executed:
/usr/bin/cc -Wl,-no_compact_unwind -Wl,-exported_symbols_list -Wl,/var/folders/sk/pbyf6nzj197c0xtx_gl_dtyc0000gn/T/SVM-7109791393636377228/exported_symbols.list -Wl,-x -arch x86_64 -o /Users/marcusmews/Eclipses/ECL3/git/n4js/target/_n4jsc _n4jsc.o /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/svm/clibraries/darwin-amd64/liblibchelper.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libnet.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/svm/clibraries/darwin-amd64/libdarwin.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libextnet.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libnio.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libjava.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libfdlibm.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libsunec.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libzip.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/svm/clibraries/darwin-amd64/libjvm.a -v -L/var/folders/sk/pbyf6nzj197c0xtx_gl_dtyc0000gn/T/SVM-7109791393636377228 -L/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64 -L/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/svm/clibraries/darwin-amd64 -lstdc++ -lpthread -Wl,-framework,Foundation -ldl -lz

Linker command output:
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
 "/Library/Developer/CommandLineTools/usr/bin/ld" -demangle -lto_library /Library/Developer/CommandLineTools/usr/lib/libLTO.dylib -dynamic -arch x86_64 -platform_version macos 11.0.0 11.1 -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -o /Users/marcusmews/Eclipses/ECL3/git/n4js/target/_n4jsc -L/var/folders/sk/pbyf6nzj197c0xtx_gl_dtyc0000gn/T/SVM-7109791393636377228 -L/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64 -L/Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/svm/clibraries/darwin-amd64 -L/usr/local/lib -no_compact_unwind -exported_symbols_list /var/folders/sk/pbyf6nzj197c0xtx_gl_dtyc0000gn/T/SVM-7109791393636377228/exported_symbols.list -x _n4jsc.o /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/svm/clibraries/darwin-amd64/liblibchelper.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libnet.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/svm/clibraries/darwin-amd64/libdarwin.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libextnet.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libnio.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libjava.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libfdlibm.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libsunec.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/static/darwin-amd64/libzip.a /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.2.0-dev/Contents/Home/lib/svm/clibraries/darwin-amd64/libjvm.a -lc++ -lpthread -framework Foundation -ldl -lz -lSystem /Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/lib/darwin/libclang_rt.osx.a
Undefined symbols for architecture x86_64:
  "_Java_java_util_prefs_MacOSXPreferencesFile_anyHost", referenced from:
      ___svm_vm_is_static_binary in _n4jsc.o
  "_Java_java_util_prefs_MacOSXPreferencesFile_anyUser", referenced from:
      ___svm_vm_target_libc in _n4jsc.o
  "_Java_java_util_prefs_MacOSXPreferencesFile_currentHost", referenced from:
      ___data in _n4jsc.o
  "_Java_java_util_prefs_MacOSXPreferencesFile_currentUser", referenced from:
      ___svm_vm_is_static_binary in _n4jsc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
	at com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:499)
	at com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:446)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:709)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:494)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
```

**Comment by mcraj017** [comment]
@mmews-n4 thanks for reporting 
please use tracing agent and try again
https://docs.oracle.com/en/graalvm/enterprise/19/guide/reference/native-image/tracing-agent.html

**Comment by mmews-n4** [comment]
@mcraj017 thanks for your reply.
If I am not mistaken, I did that already. I followed the guide ["Assisted Configuration of Native Image Builds"](https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/#assisted-configuration-of-native-image-builds): I created the files `jni-config.json`, `reflect-config.json`, `proxy-config.json`, `serialization-config.json` and `resource-config.json` (using argument `-agentlib:native-image-agent=config-merge-dir=...`) and included them in the `_n4jsc.jar` (inside download stated above) in directory `META-INF/native-image`. Without these files, creating a native image reports errors much earlier. Or maybe I missed something?

**Comment by mcraj017** [comment]
@mmews-n4 bug has been raised internally

**Comment by olpaw** [comment]
@mmews-n4 while I am able to reproduce the issue with `GraalVM 21.2.0.1 Java 11 CE`, I'm not able to reproduce it on master. 

Please verify that the issue is no more reproducible on your side with a nightly build.
https://github.com/graalvm/graalvm-ce-dev-builds/releases

Thanks, Paul

**Comment by mmews-n4** [comment]
I can confirm that the problem is not occurring in the release `GraalVM CE 21.3.0-dev-20210831_2241`. Thank you!
