### ISSUE TITLE
Could not find resource configuration resource "proxy.json"

### ISSUE THREAD

**Issue by hok021** [oracle/graal#3434]
**pom.xml:**

> <properties>
				<quarkus.package.type>native</quarkus.package.type>
				 <quarkus.native.additional-build-args>
		            --report-unsupported-elements-at-runtime,
		            -H:DynamicProxyConfigurationResources=proxy.json
		        </quarkus.native.additional-build-args>
			</properties>

**proxy.json:**

> src/main/resources/proxy.jsoon

**mvn clean package -DskipTests -Pnative**

> com.oracle.svm.core.util.UserError$UserException: Could not find resource configuration resource "proxy.json
		            -H:DynamicProxyConfigurationResources=proxy.json".
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.config.ConfigurationParserUtils.lambda$parseAndRegisterConfigurations$2(ConfigurationParserUtils.java:101)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	
Error: Image build request failed with exit status 1

**How to solve it**
**Thanks!**

**Comment by mcraj017** [comment]
@hok021 please read how to access in native-image to solve this issue
https://www.graalvm.org/reference-manual/native-image/Resources/

**Comment by mcraj017** [comment]
Closing the issue, if the proposed solution doesn't work, please reopen
