### ISSUE TITLE
`org.apache.logging.log4j.message.ParameterizedMessageFactory` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.

### ISSUE THREAD

**Issue by mgltech** [oracle/graal#3449]
n is java.lang.IllegalStateException: java.lang.InstantiationException: Type `org.apache.logging.log4j.message.ParameterizedMessageFactory` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:315) ~[na:na]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:181) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[na:na]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[na:na]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[na:na]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[app:2.5.0]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:438) ~[app:2.5.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:337) ~[app:2.5.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1336) ~[app:2.5.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1325) ~[app:2.5.0]
        at cloud.mgl.MglM3u8DlApplicationKt.main(MglM3u8DlApplication.kt:13) ~[na:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [cloud.mgl.app.M3U8MainController]: Constructor threw exception; nested exception is java.lang.IllegalStateException: java.lang.InstantiationException: Type `org.apache.logging.log4j.message.ParameterizedMessageFactory` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:225) ~[na:na]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[na:na]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311) ~[na:na]
        ... 19 common frames omitted
Caused by: java.lang.IllegalStateException: java.lang.InstantiationException: Type `org.apache.logging.log4j.message.ParameterizedMessageFactory` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
        at org.apache.logging.log4j.spi.AbstractLogger.createDefaultMessageFactory(AbstractLogger.java:231) ~[na:na]
        at org.apache.logging.log4j.spi.AbstractLogger.<init>(AbstractLogger.java:132) ~[na:na]
        at org.apache.logging.slf4j.SLF4JLogger.<init>(SLF4JLogger.java:44) ~[na:na]
        at org.apache.logging.slf4j.SLF4JLoggerContext.getLogger(SLF4JLoggerContext.java:39) ~[na:na]
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:666) ~[na:na]
        at cloud.mgl.app.M3U8MainController.<init>(M3U8MainController.kt:16) ~[app:0.0.1-SNAPSHOT]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[na:na]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[na:na]
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Constructor.call(CallerImpl.kt:41) ~[na:na]
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108) ~[na:na]
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159) ~[na:na]
        at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:112) ~[na:na]
        at org.springframework.beans.BeanUtils$KotlinDelegate.instantiateClass(BeanUtils.java:866) ~[na:na]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:197) ~[na:na]
        ... 21 common frames omitted
Caused by: java.lang.InstantiationException: Type `org.apache.logging.log4j.message.ParameterizedMessageFactory` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
        at java.lang.Class.newInstance(DynamicHub.java:912) ~[na:na]
        at org.apache.logging.log4j.spi.AbstractLogger.createDefaultMessageFactory(AbstractLogger.java:228) ~[na:na]
        ... 34 common frames omitted

**Comment by oubidar-Abderrahim** [comment]
@mgltech, please follow the standard template for filing a native-image related issue.

I will be closing this issue for now. When you open a new issue following the template, please assign it directly to me.

Thank you for your understanding.
