### ISSUE TITLE
experimental-class-define-support  vm not reach here error

### ISSUE THREAD

**Issue by ningpengtao-coder** [oracle/graal#3520]
I have experienced the experimental-class-define-support feature of the 21.2 development version, and found that the generated configuration has problems, and I need to manually adjust the loading order of the entries in the classes attribute in the predefined-classes-config.json to solve it.

1.Anonymous inner classes and lambda expressions and inner subclasses
2.Kotlin-generated classes (or languages based on JVM)

**Comment by peter-hofer** [comment]
Hi @ningpengtao-coder, nice to see you trying out this new feature. I have introduced some improvements to `master` to address this. This code has not been integrated into 21.2 yet, so please try a newer build that includes them and let me know if that helps: https://github.com/oracle/graal/commit/f4d05a0ddbd4cab13c0ef46c7e5d41bf360cad94

**Comment by ningpengtao-coder** [comment]
@peter-hofer It seems there is a problem with jdk dynamic proxy.

Stacktrace:

Error: More than one pre-defined class with the same name provided: com.sun.proxy.$Proxy131
com.oracle.svm.core.util.UserError$UserException: More than one pre-defined class with the same name provided: com.sun.proxy.$Proxy131
        at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
        at com.oracle.svm.hosted.ClassPredefinitionFeature$PredefinedClassesRegistryImpl.add(ClassPredefinitionFeature.java:127)
        at com.oracle.svm.core.configure.PredefinedClassesConfigurationParser.parseClass(PredefinedClassesConfigurationParser.java:90)
        at com.oracle.svm.core.configure.PredefinedClassesConfigurationParser.parseOrigin(PredefinedClassesConfigurationParser.java:81)
        at com.oracle.svm.core.configure.PredefinedClassesConfigurationParser.parseAndRegister(PredefinedClassesConfigurationParser.java:68)
        at com.oracle.svm.core.configure.PredefinedClassesConfigurationParser.parseAndRegister(PredefinedClassesConfigurationParser.java:59)
        at com.oracle.svm.hosted.config.ConfigurationParserUtils.doParseAndRegister(ConfigurationParserUtils.java:120)
        at com.oracle.svm.hosted.config.ConfigurationParserUtils.lambda$parseAndRegisterConfigurations$1(ConfigurationParserUtils.java:84)
        at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:212)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:491)
        at java.base/java.util.stream.IntPipeline.sum(IntPipeline.java:449)
        at com.oracle.svm.hosted.config.ConfigurationParserUtils.parseAndRegisterConfigurations(ConfigurationParserUtils.java:86)
        at com.oracle.svm.hosted.ClassPredefinitionFeature.afterRegistration(ClassPredefinitionFeature.java:67)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$15(NativeImageGenerator.java:854)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:71)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:854)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:491)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:380)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)

**Comment by ningpengtao-coder** [comment]
@peter-hofer  The problem of the jdk dynamic proxy with the same name is caused by using the config-merge-dir configuration. It seems that there is a problem with the merge logic of the predefined-classes-config.json, and the dynamically loaded class is modified and recompiled without being processed. There will be two versions in the predefined-classes-config.json.

**Comment by peter-hofer** [comment]
Thank you for your response @ningpengtao-coder. The agent shouldn't capture dynamic proxy classes in the first place, they need to be defined via `proxy-config.json`. I'll look into a fix, but it won't make it into 21.2.
As for merging `predefined-classes-config.json`, the issue is _which_ of the classes should be used. I'm not sure if simply replacing the existing entry with the more recently seen class is a good solution. Because it's undesirable to have the agent fail, and any warnings that the agent prints are easily missed, it seems better to fail during the image build and let the user address the issue.

**Comment by peter-hofer** [comment]
@ningpengtao-coder , please have a look at the changes in #3550.
