### ISSUE TITLE
Classes that should be initialized at run time got initialized during image building

### ISSUE THREAD

**Issue by SujayHub** [oracle/graal#3526]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **GraalVM EE 21.1.0**
 - CE or EE: **[EE]**
 - JDK version: **[JDK11]**
 - OS and OS Version: **[macOS BigSur]**
 - Architecture: **[Darwin x86_64]**
 - The output of `java -Xinternalversion`:
```
 **Java HotSpot(TM) 64-Bit Server VM (11.0.11+9-LTS-jvmci-21.1-b05) for bsd-amd64 JRE (11.0.11+9-LTS-jvmci-21.1-b05), built on Apr 13 2021 09:11:08 by "graal" with gcc 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)**
```

**Have you verified this issue still happens when using the latest snapshot?**
No

**Describe the issue**
A clear and concise description of the issue.

**Unable to build native image when running the command mvn -Pnative -DskipTests package in the mentioned repo**
```
**https://github.com/SujayHub/spring-native-learn.git**
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Step one [e.g.: git clone https://github.com/SujayHub/spring-native-learn.git ]
2. Step two [e.g.: mvn -Pnative -DskipTests package]

**Expected behavior**
native Image build request failed with exit status 1

**Additional context**
 Classes that should be initialized at run time got initialized during image building:
<details><summary>Details</summary>

```
    Error: Classes that should be initialized at run time got initialized during image building:
 com.oracle.truffle.api.Truffle the class was requested to be initialized at run time (from the command line). org.graalvm.compiler.truffle.common.TruffleCompilerRuntimeInstance caused initialization of this class with the following trace: 
	at com.oracle.truffle.api.Truffle.<clinit>(Truffle.java:62)
	at java.lang.Class.forName0(Unknown Source)
	at java.lang.Class.forName(Class.java:315)
	at org.graalvm.compiler.truffle.common.TruffleCompilerRuntimeInstance.init(TruffleCompilerRuntimeInstance.java:56)
	at org.graalvm.compiler.truffle.common.TruffleCompilerRuntimeInstance.<clinit>(TruffleCompilerRuntimeInstance.java:38)


com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 com.oracle.truffle.api.Truffle the class was requested to be initialized at run time (from the command line). org.graalvm.compiler.truffle.common.TruffleCompilerRuntimeInstance caused initialization of this class with the following trace: 
	at com.oracle.truffle.api.Truffle.<clinit>(Truffle.java:62)
	at java.lang.Class.forName0(Unknown Source)
	at java.lang.Class.forName(Class.java:315)
	at org.graalvm.compiler.truffle.common.TruffleCompilerRuntimeInstance.init(TruffleCompilerRuntimeInstance.java:56)
	at org.graalvm.compiler.truffle.common.TruffleCompilerRuntimeInstance.<clinit>(TruffleCompilerRuntimeInstance.java:38)


	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:545)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.afterImageWrite(ClassInitializationFeature.java:362)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$doRun$12(NativeImageGenerator.java:716)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:71)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:716)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:495)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:00 min
[INFO] Finished at: 2021-06-29T14:15:57+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.0:build (build-native) on project spring-native-learn: Execution of /Library/Java/JavaVirtualMachines/graalvm-ee-java11-21.1.0/Contents/Home/bin/native-image -cp /Users/sujaysamanta/.m2/repository/org/springframework/boot/spring-boot-starter-actuator/2.5.2/spring-boot-starter-actuator-2.5.2.jar:/Users/sujaysamanta/.m2/repository/org/springframework/boot/spring-boot-starter/2.5.2/spring-boot-starter-2.5.2.jar:/Users/sujaysamanta/.m2/repository/org/springframework/boot/spring-boot/2.5.2/spring-boot-2.5.2.jar:/Users/sujaysamanta/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.5.2/spring-boot-autoconfigure-2.5.2.jar:/Users/sujaysamanta/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.5.2/spring-boot-starter-logging-2.5.2.jar:/Users/sujaysamanta/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar:/Users/sujaysamanta/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar:/Users/sujaysamanta/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.14.1/log4j-to-slf4j-2.14.1.jar:/Users/sujaysamanta/.m2/repository/org/apache/logging/log4j/log4j-api/2.14.1/log4j-api-2.14.1.jar:/Users/sujaysamanta/.m2/repository/org/slf4j/jul-to-slf4j/1.7.31/jul-to-slf4j-1.7.31.jar:/Users/sujaysamanta/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.jar:/Users/sujaysamanta/.m2/repository/org/yaml/snakeyaml/1.28/snakeyaml-1.28.jar:/Users/sujaysamanta/.m2/repository/org/springframework/boot/spring-boot-actuator-autoconfigure/2.5.2/spring-boot-actuator-autoconfigure-2.5.2.jar:/Users/sujaysamanta/.m2/repository/org/springframework/boot/spring-boot-actuator/2.5.2/spring-boot-actuator-2.5.2.jar:/Users/sujaysamanta/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.12.3/jackson-databind-2.12.3.jar:/Users/sujaysamanta/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.12.3/jackson-annotations-2.12.3.jar:/Users/sujaysamanta/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.12.3/jackson-core-2.12.3.jar:/Users/sujaysamanta/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.3/jackson-datatype-jsr310-2.12.3.jar:/Users/sujaysamanta/.m2/repository/io/micrometer/micrometer-core/1.7.1/micrometer-core-1.7.1.jar:/Users/sujaysamanta/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.12/HdrHistogram-2.1.12.jar:/Users/sujaysamanta/.m2/repository/org/latencyutils/LatencyUtils/2.0.3/LatencyUtils-2.0.3.jar:/Users/sujaysamanta/.m2/repository/org/springframework/boot/spring-boot-starter-data-jpa/2.5.2/spring-boot-starter-data-jpa-2.5.2.jar:/Users/sujaysamanta/.m2/repository/org/springframework/boot/spring-boot-starter-aop/2.5.2/spring-boot-starter-aop-2.5.2.jar:/Users/sujaysamanta/.m2/repository/org/springframework/spring-aop/5.3.8/spring-aop-5.3.8.jar:/Users/sujaysamanta/.m2/repository/org/aspectj/aspectjweaver/1.9.6/aspectjweaver-1.9.6.jar:/Users/sujaysamanta/.m2/repository/org/springframework/boot/spring-boot-starter-jdbc/2.5.2/spring-boot-starter-jdbc-2.5.2.jar:/Users/sujaysamanta/.m2/repository/com/zaxxer/HikariCP/4.0.3/HikariCP-4.0.3.jar:/Users/sujaysamanta/.m2/repository/org/springframework/spring-jdbc/5.3.8/spring-jdbc-5.3.8.jar:/Users/sujaysamanta/.m2/repository/jakarta/transaction/jakarta.transaction-api/1.3.3/jakarta.transaction-api-1.3.3.jar:/Users/sujaysamanta/.m2/repository/jakarta/persistence/jakarta.persistence-api/2.2.3/jakarta.persistence-api-2.2.3.jar:/Users/sujaysamanta/.m2/repository/org/hibernate/hibernate-core/5.4.32.Final/hibernate-core-5.4.32.Final.jar:/Users/sujaysamanta/.m2/repository/org/jboss/logging/jboss-logging/3.4.2.Final/jboss-logging-3.4.2.Final.jar:/Users/sujaysamanta/.m2/repository/org/javassist/javassist/3.27.0-GA/javassist-3.27.0-GA.jar:/Users/sujaysamanta/.m2/repository/net/bytebuddy/byte-buddy/1.10.22/byte-buddy-1.10.22.jar:/Users/sujaysamanta/.m2/repository/antlr/antlr/2.7.7/antlr-2.7.7.jar:/Users/sujaysamanta/.m2/repository/org/jboss/jandex/2.2.3.Final/jandex-2.2.3.Final.jar:/Users/sujaysamanta/.m2/repository/com/fasterxml/classmate/1.5.1/classmate-1.5.1.jar:/Users/sujaysamanta/.m2/repository/org/dom4j/dom4j/2.1.3/dom4j-2.1.3.jar:/Users/sujaysamanta/.m2/repository/org/hibernate/common/hibernate-commons-annotations/5.1.2.Final/hibernate-commons-annotations-5.1.2.Final.jar:/Users/sujaysamanta/.m2/repository/org/glassfish/jaxb/jaxb-runtime/2.3.4/jaxb-runtime-2.3.4.jar:/Users/sujaysamanta/.m2/repository/org/glassfish/jaxb/txw2/2.3.4/txw2-2.3.4.jar:/Users/sujaysamanta/.m2/repository/com/sun/istack/istack-commons-runtime/3.0.12/istack-commons-runtime-3.0.12.jar:/Users/sujaysamanta/.m2/repository/com/sun/activation/jakarta.activation/1.2.2/jakarta.activation-1.2.2.jar:/Users/sujaysamanta/.m2/repository/org/springframework/data/spring-data-jpa/2.5.2/spring-data-jpa-2.5.2.jar:/Users/sujaysamanta/.m2/repository/org/springframework/data/spring-data-commons/2.5.2/spring-data-commons-2.5.2.jar:/Users/sujaysamanta/.m2/repository/org/springframework/spring-orm/5.3.8/spring-orm-5.3.8.jar:/Users/sujaysamanta/.m2/repository/org/springframework/spring-context/5.3.8/spring-context-5.3.8.jar:/Users/sujaysamanta/.m2/repository/org/springframework/spring-tx/5.3.8/spring-tx-5.3.8.jar:/Users/sujaysamanta/.m2/repository/org/springframework/spring-beans/5.3.8/spring-beans-5.3.8.jar:/Users/sujaysamanta/.m2/repository/org/slf4j/slf4j-api/1.7.31/slf4j-api-1.7.31.jar:/Users/sujaysamanta/.m2/repository/org/springframework/spring-aspects/5.3.8/spring-aspects-5.3.8.jar:/Users/sujaysamanta/.m2/repository/org/springframework/boot/spring-boot-starter-web/2.5.2/spring-boot-starter-web-2.5.2.jar:/Users/sujaysamanta/.m2/repository/org/springframework/boot/spring-boot-starter-json/2.5.2/spring-boot-starter-json-2.5.2.jar:/Users/sujaysamanta/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.12.3/jackson-datatype-jdk8-2.12.3.jar:/Users/sujaysamanta/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.12.3/jackson-module-parameter-names-2.12.3.jar:/Users/sujaysamanta/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/2.5.2/spring-boot-starter-tomcat-2.5.2.jar:/Users/sujaysamanta/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/9.0.48/tomcat-embed-core-9.0.48.jar:/Users/sujaysamanta/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/9.0.48/tomcat-embed-websocket-9.0.48.jar:/Users/sujaysamanta/.m2/repository/org/springframework/spring-web/5.3.8/spring-web-5.3.8.jar:/Users/sujaysamanta/.m2/repository/org/springframework/spring-webmvc/5.3.8/spring-webmvc-5.3.8.jar:/Users/sujaysamanta/.m2/repository/org/springframework/spring-expression/5.3.8/spring-expression-5.3.8.jar:/Users/sujaysamanta/.m2/repository/org/springframework/experimental/spring-native/0.10.1/spring-native-0.10.1.jar:/Users/sujaysamanta/.m2/repository/org/springframework/boot/spring-boot-starter-validation/2.5.2/spring-boot-starter-validation-2.5.2.jar:/Users/sujaysamanta/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/9.0.48/tomcat-embed-el-9.0.48.jar:/Users/sujaysamanta/.m2/repository/org/hibernate/validator/hibernate-validator/6.2.0.Final/hibernate-validator-6.2.0.Final.jar:/Users/sujaysamanta/.m2/repository/jakarta/validation/jakarta.validation-api/2.0.2/jakarta.validation-api-2.0.2.jar:/Users/sujaysamanta/.m2/repository/com/h2database/h2/1.4.200/h2-1.4.200.jar:/Users/sujaysamanta/.m2/repository/org/projectlombok/lombok/1.18.20/lombok-1.18.20.jar:/Users/sujaysamanta/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/2.3.3/jakarta.xml.bind-api-2.3.3.jar:/Users/sujaysamanta/.m2/repository/jakarta/activation/jakarta.activation-api/1.2.2/jakarta.activation-api-1.2.2.jar:/Users/sujaysamanta/.m2/repository/org/springframework/spring-core/5.3.8/spring-core-5.3.8.jar:/Users/sujaysamanta/.m2/repository/org/springframework/spring-jcl/5.3.8/spring-jcl-5.3.8.jar:/Users/sujaysamanta/Workspace/CodeCentral/SpringBook/spring-native-learn/target/spring-native-learn-0.0.1-SNAPSHOT.jar --no-fallback -H:+ReportExceptionStackTraces --trace-class-initialization=com.oracle.truffle.api.Truffle --initialize-at-run-time=com.oracle.truffle.api.Truffle -H:Class=com.img.learn.app.SpringNativeApplication -H:Name=spring-native-learn returned non-zero result -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
</details>

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this, I'll look into it and get back to you.

**Comment by SujayHub** [comment]
@oubidar-Abderrahim thank you for choosing to have a look at it, please let me know of any update

**Comment by oubidar-Abderrahim** [comment]
I did a quick check to your code and it doesn't seem to be using Truffle. I can only assume that it was called by Spring and most probably to execute some JavaScript code. For this, I removed the `<buildArg>--initialize-at-run-time=com.oracle.truffle.api.Truffle</buildArg>` and added `<buildArg>--language:js</buildArg>` this made it build and run successfully on my Linux machine.

Please give it a try and let me know if it solves your issue.

If this solves your issue, I would suggest opening a Github issue to Spring-native to include '--language:js' in their 'native-image.properties' this way others can avoid facing the same issue.

**Comment by SujayHub** [comment]
@oubidar-Abderrahim thanks for the update, the problem is resolved. I wiil do as suggested
