### ISSUE TITLE
experimental-class-define-support feature configuration parse error

### ISSUE THREAD

**Issue by ningpengtao-coder** [oracle/graal#3530]
**Describe the issue**

By default, native-image loads the configuration from META-INF/native-image of the classpath. When the experimental-class-define-support configuration is enabled, it will automatically configure -H:PredefinedClassesConfigurationResources. PredefinedClassesRegistryImpl implements the registration of dynamic class loading, but it is not compatible with the -H:PredefinedClassesConfigurationResources configuration. It can only pass -H:PredefinedClassesConfigurationFiles.

The current situation is that -H:PredefinedClassesConfigurationFiles can only be manually configured for processing.

Hope to fix the problem of -H:PredefinedClassesConfigurationResources configuration.

Stacktrace:
Fatal error:java.lang.NullPointerException
        at com.oracle.svm.hosted.ClassPredefinitionFeature$PredefinedClassesRegistryImpl.add(ClassPredefinitionFeature.java:107)
        at com.oracle.svm.core.configure.PredefinedClassesConfigurationParser.parseClass(PredefinedClassesConfigurationParser.java:90)
        at com.oracle.svm.core.configure.PredefinedClassesConfigurationParser.parseOrigin(PredefinedClassesConfigurationParser.java:81)
        at com.oracle.svm.core.configure.PredefinedClassesConfigurationParser.parseAndRegister(PredefinedClassesConfigurationParser.java:68)
        at com.oracle.svm.core.configure.PredefinedClassesConfigurationParser.parseAndRegister(PredefinedClassesConfigurationParser.java:51)
        at com.oracle.svm.hosted.config.ConfigurationParserUtils.doParseAndRegister(ConfigurationParserUtils.java:125)
        at com.oracle.svm.hosted.config.ConfigurationParserUtils.lambda$parseAndRegisterConfigurations$3(ConfigurationParserUtils.java:111)
        at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:212)
        at com.oracle.svm.hosted.config.ConfigurationParserUtils$1.tryAdvance(ConfigurationParserUtils.java:104)
        at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:491)
        at java.base/java.util.stream.IntPipeline.sum(IntPipeline.java:449)
        at com.oracle.svm.hosted.config.ConfigurationParserUtils.parseAndRegisterConfigurations(ConfigurationParserUtils.java:113)
        at com.oracle.svm.hosted.ClassPredefinitionFeature.afterRegistration(ClassPredefinitionFeature.java:67)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$15(NativeImageGenerator.java:854)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:71)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:854)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:491)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:380)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)

**Steps to reproduce the issue**

1. It can be reproduced without any settings

**Comment by mcraj017** [comment]
@ningpengtao-coder thanks for reporting the issue, please provide a reproducer

**Comment by mcraj017** [comment]
@ningpengtao-coder closing this issue because of the inactivity for past 30 days
