### ISSUE TITLE
Can Clojure projects be natively compiled without the --initialize-at-run-build-time option?

### ISSUE THREAD

**Issue by borkdude** [oracle/graal#3532]
As discussed with @vjovanov, it would be interesting to see if Clojure projects can work without the `--initialize-at-build-time` option, which is currently not possible.

**Describe the solution you'd like.**

We could create a list of reachable classes (perhaps using `"-H:+PrintClassInitialization"` + `--initialize-at-build-time` or some other way) and then mark them as reachable in the native image analyzer. Next, we should patch (using a substitution for now, perhaps later via a PR to Clojure?) RT.load 
(https://github.com/clojure/clojure/blob/a29f9b911b569b0a4890f320ec8f946329bbe0fd/src/jvm/clojure/lang/RT.java#L427)
to do nothing if the class was already marked reachable.

We would still like to initialize clojure.lang.RT itself at build time because of start up time (it loads `clojure.core` itself which is quite big and safe to initialize during the build).
There are several other namespaces that are known to be safe that could be loaded at build time as well (like `clojure.set`, `clojure.string`, etc.). But in general one should not assume that user defined namespaces are safe to initialize at build time (although in practice I find that most Clojure libraries are and if not they are pretty easily patchable).

**Describe who do you think will benefit the most.**
Clojure users using `native-image`

**Describe alternatives you've considered.**
Use `--initialize-at-build-time` with a comma separated string of all Clojure-defined packages.

**Express whether you'd like to help contributing this feature**
I would like to help where I can, in coordination with the GraalVM team.

@vjovanov Please add any information I may have missed or correct anything I may have gotten wrong.

**Repro**
How to make a "hello world" Clojure app that can be compiled with native image:

This requires Java and the [Clojure CLI](https://clojure.org/guides/getting_started).

```
mkdir -p src
```

src/mymain.clj
``` clojure
(ns mymain
  (:gen-class))

(defn -main [& args]
  (println "args:" args))
```

Compile to bytecode:
```
mkdir -p classes
clojure -M -e "(compile 'mymain)"
```

All necessary classes have now been emitted to the `classes` directory, without Clojure itself. The full classpath necessary for `java` to run this: `classes:$(clojure -Spath)`.

Test:
```
$ java -cp classes:$(clojure -Spath) mymain 1 2 3
args: (1 2 3)
```

Compile with native-image:
```
$GRAALVM_HOME/bin/native-image --no-server --no-fallback -cp classes:$(clojure -Spath) mymain
```

Running it gives:
```
$ ./mymain 1 2 3
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:315)
	at clojure.lang.Namespace.<init>(Namespace.java:34)
	at clojure.lang.Namespace.findOrCreate(Namespace.java:176)
	at clojure.lang.Var.internPrivate(Var.java:156)
	at mymain.<clinit>(Unknown Source)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
Caused by: java.io.FileNotFoundException: Could not locate clojure/core__init.class, clojure/core.clj or clojure/core.cljc on classpath.
	at clojure.lang.RT.load(RT.java:462)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.lang.RT.<clinit>(RT.java:338)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
	... 6 more
```

With ` --initialize-at-build-time` it works like expected. Starting from GraalVM 22.0 one would have to provide this option as
` --initialize-at-build-time=clojure,mymain`

Inspect `mymain.main.class` and `mymain.main__init.class` to see what happens in the static initializers.

/cc @gradinac

**Comment by borkdude** [comment]
I will make a small reproduction using `clojure` (the official Clojure CLI tool) and bash scripts later tonight.

**Comment by borkdude** [comment]
After looking into this a bit more, I remain a bit skeptical about the effect on startup time, because if you inspect the contents of static initializer blocks of Clojure-generated bytecode (especially the `__init.class` classes), it's non-trivial and not sure if it's worth the endeavor of working around this.  In the meanwhile I think we've found a reasonable workaround by listing Clojure packages explicitly and leaving Java classes untouched.

A reasonable workaround for Clojure classes that should not capture top-level values (or instances) at build time is to use `delay`, like in this commit: https://github.com/clojure/tools.deps.alpha/commit/5f0fb4f23a5e38aaaa1b13165540a63e791aaaf4.

<img width="957" alt="Screenshot 2021-06-30 at 21 00 55" src="https://user-images.githubusercontent.com/284934/124016821-53689380-d9e6-11eb-915d-5f4dfa612cec.png">

**Comment by borkdude** [comment]
I'm pretty sure that it's not a good idea to move Clojure static initialiser blocks to runtime and it will slow down native images significantly, since the work done in those blocks isn't very idiomatic "Java": https://blog.ndk.io/solving-clojure-boot-time.html

I'm satisfied with the comma separated Clojure package name for now.
