### ISSUE TITLE
org.graalvm.compiler.nodes.ValueProxyNode cannot be cast to org.graalvm.compiler.replacements.nodes.ObjectClone

### ISSUE THREAD

**Issue by FieryCod** [oracle/graal#3572]
**Describe the issue**
I'm developing a library for Clojure which extensively uses native-image to compile Clojure code that then can be uploaded to AWS Lambda. I got some of the examples which are useful to test the project tested on CI with different GraalVM versions:

- GraalVM CE - 21.1.0
- GraalVM EE - 21.1.0
- GraalVM Dev - 21.3.0-dev-20210706_1943

Tests ran in CE based images works fine, but EE native compilation fails with error:
```
Fatal error:org.graalvm.compiler.debug.GraalError: java.lang.ClassCastException: org.graalvm.compiler.nodes.ValueProxyNode cannot be cast to org.graalvm.compiler.replacements.nodes.ObjectClone
	at method: Compiler$Expr clojure.lang.Compiler$StaticInvokeExpr.parse(Var, ISeq, Object, boolean)  [Direct call from Compiler$Expr Compiler$InvokeExpr.parse(Compiler$C, ISeq)]
	at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:1029)
	at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:960)
	at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:265)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
Caused by: java.lang.ClassCastException: org.graalvm.compiler.nodes.ValueProxyNode cannot be cast to org.graalvm.compiler.replacements.nodes.ObjectClone
	at com.oracle.graal.enterprise.ax.c$a.a(stripped:167)
	at com.oracle.graal.enterprise.ax.c$a.processNode(stripped:183)
	at com.oracle.graal.enterprise.ax.c$a.processNode(stripped:120)
	at org.graalvm.compiler.virtual.phases.ea.EffectsClosure.processBlock(EffectsClosure.java:262)
	at org.graalvm.compiler.virtual.phases.ea.EffectsClosure.processBlock(EffectsClosure.java:71)
	at org.graalvm.compiler.phases.graph.ReentrantBlockIterator.apply(ReentrantBlockIterator.java:125)
	at org.graalvm.compiler.phases.graph.ReentrantBlockIterator.apply(ReentrantBlockIterator.java:97)
	at org.graalvm.compiler.virtual.phases.ea.EffectsPhase.runAnalysis(EffectsPhase.java:104)
	at org.graalvm.compiler.virtual.phases.ea.ReadEliminationPhase.run(ReadEliminationPhase.java:79)
	at com.oracle.graal.enterprise.ax.c.run(stripped:109)
	at com.oracle.graal.enterprise.ax.c.run(stripped:99)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
	at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:209)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
	at org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:232)
	at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:145)
	at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:130)
	at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:998)
	... 8 more
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1772)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1519)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1480)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1467)

```

For completeness I'm attaching the link to the CI: 
https://dev.azure.com/vetcard/holy-lambda/_build/results?buildId=110&view=logs&j=b6c59b58-6344-5d14-32db-b65ddabae5f6&t=75f4324b-3038-5ada-8c96-eba87df80633
 
**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Make sure that you have `~/.aws/credentials` `~/.aws/config` files. You can fake them! Make sure that you have docker running and at least 6gb of RAM.
2. Install babashka: https://github.com/babashka/babashka
3. `git clone https://github.com/FieryCod/holy-lambda && cd holy-lambda`
4. Build GraalVM EE image: 
   1. Download official GraalVM EE build from Oracle website:
      - graalvm-ee-java8-linux-amd64-21.1.0.tar.gz
      - native-image-installable-svm-svmee-java8-linux-amd64-21.1.0.jar
    2. Place both in holy-lambda/docker/ folder
    3. Run
    ```
    make USE_EE=true build-docker
    ```
5. Go to examples/bb/native/hl.aws-bucket
6. Run 
    ```
    bb stack:sync && bb stack:compile && bb native:conf && bb native:executable
    ```

**Describe GraalVM and your environment:**
 - GraalVM version: 21.1.0 EE
 - JDK major version: 8
 - OS: Not relevant. GraalVM used in Docker
 - Architecture: AMD 64

**More details**
GraalVM EE native-image --verbose:

```
2021-07-11T13:24:09.5709668Z Executing [
2021-07-11T13:24:09.5710738Z /opt/graalvm-ee-java8-21.1.0/jre/bin/java \
2021-07-11T13:24:09.5711138Z -XX:+UseParallelGC \
2021-07-11T13:24:09.5711481Z -XX:+UnlockExperimentalVMOptions \
2021-07-11T13:24:09.5711791Z -XX:+EnableJVMCI \
2021-07-11T13:24:09.5712380Z -Dtruffle.TrustAllTruffleRuntimeProviders=true \
2021-07-11T13:24:09.5716073Z -Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
2021-07-11T13:24:09.5716832Z -Dgraalvm.ForcePolyglotInvalid=true \
2021-07-11T13:24:09.5717188Z -Dgraalvm.locatorDisabled=true \
2021-07-11T13:24:09.5717484Z -d64 \
2021-07-11T13:24:09.5717778Z -XX:-UseJVMCIClassLoader \
2021-07-11T13:24:09.5718092Z -XX:+UseJVMCINativeLibrary \
2021-07-11T13:24:09.5718506Z -Xss10m \
2021-07-11T13:24:09.5718785Z -Xms1g \
2021-07-11T13:24:09.5719066Z -Xmx13107150848 \
2021-07-11T13:24:09.5719353Z -Duser.country=US \
2021-07-11T13:24:09.5719644Z -Duser.language=en \
2021-07-11T13:24:09.5719939Z -Djava.awt.headless=true \
2021-07-11T13:24:09.5720255Z -Dorg.graalvm.version=21.1.0 \
2021-07-11T13:24:09.5720564Z -Dorg.graalvm.config=CE \
2021-07-11T13:24:09.5720873Z -Dcom.oracle.graalvm.isaot=true \
2021-07-11T13:24:09.5721282Z -Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
2021-07-11T13:24:09.5721635Z -Xshare:off \
2021-07-11T13:24:09.5722153Z -Djvmci.class.path.append=/opt/graalvm-ee-java8-21.1.0/jre/lib/jvmci/enterprise-graal.jar:/opt/graalvm-ee-java8-21.1.0/jre/lib/jvmci/graal.jar \
2021-07-11T13:24:09.5722807Z -Djdk.internal.lambda.disableEagerInitialization=true \
2021-07-11T13:24:09.5723286Z -Djdk.internal.lambda.eagerlyInitialize=false \
2021-07-11T13:24:09.5723695Z -Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
2021-07-11T13:24:09.5724128Z -javaagent:/opt/graalvm-ee-java8-21.1.0/jre/lib/svm/builder/svm.jar \
2021-07-11T13:24:09.5724692Z -Xbootclasspath/a:/opt/graalvm-ee-java8-21.1.0/jre/lib/boot/graaljs-scriptengine.jar:/opt/graalvm-ee-java8-21.1.0/jre/lib/boot/graal-sdk.jar \
2021-07-11T13:24:09.5725092Z -cp \
2021-07-11T13:24:09.5727150Z /opt/graalvm-ee-java8-21.1.0/jre/lib/svm/builder/objectfile.jar:/opt/graalvm-ee-java8-21.1.0/jre/lib/svm/builder/svm-enterprise.jar:/opt/graalvm-ee-java8-21.1.0/jre/lib/svm/builder/llvm-platform-specific-shadowed.jar:/opt/graalvm-ee-java8-21.1.0/jre/lib/svm/builder/svm-enterprise-llvm.jar:/opt/graalvm-ee-java8-21.1.0/jre/lib/svm/builder/svm.jar:/opt/graalvm-ee-java8-21.1.0/jre/lib/svm/builder/pointsto.jar:/opt/graalvm-ee-java8-21.1.0/jre/lib/svm/builder/svm-llvm.jar:/opt/graalvm-ee-java8-21.1.0/jre/lib/svm/builder/javacpp-shadowed.jar:/opt/graalvm-ee-java8-21.1.0/jre/lib/svm/builder/llvm-wrapper-shadowed.jar:/opt/graalvm-ee-java8-21.1.0/jre/lib/jvmci/enterprise-graal.jar:/opt/graalvm-ee-java8-21.1.0/jre/lib/jvmci/jvmci-hotspot.jar:/opt/graalvm-ee-java8-21.1.0/jre/lib/jvmci/graal-truffle-jfr-impl.jar:/opt/graalvm-ee-java8-21.1.0/jre/lib/jvmci/graal.jar:/opt/graalvm-ee-java8-21.1.0/jre/lib/jvmci/jvmci-api.jar:/opt/graalvm-ee-java8-21.1.0/jre/lib/jvmci/graal-management.jar:/opt/graalvm-ee-java8-21.1.0/jre/lib/resources.jar \
2021-07-11T13:24:09.5728499Z com.oracle.svm.hosted.NativeImageGeneratorRunner \
2021-07-11T13:24:09.5728817Z -watchpid \
2021-07-11T13:24:09.5728984Z 1 \
2021-07-11T13:24:09.5729240Z -imagecp \
2021-07-11T13:24:09.5729890Z /opt/graalvm-ee-java8-21.1.0/jre/lib/boot/graaljs-scriptengine.jar:/opt/graalvm-ee-java8-21.1.0/jre/lib/boot/graal-sdk.jar:/opt/graalvm-ee-java8-21.1.0/jre/lib/svm/library-support.jar:/project/.holy-lambda/build/output.jar \
2021-07-11T13:24:09.5730449Z -H:Path=/project/.holy-lambda/build \
2021-07-11T13:24:09.5730892Z '-H:Class@manifest from file:///project/.holy-lambda/build/output.jar=hl.aws_bucket.core' \
2021-07-11T13:24:09.5731374Z '-H:Name@manifest from file:///project/.holy-lambda/build/output.jar=output' \
2021-07-11T13:24:09.5731793Z -H:ConfigurationFileDirectories=native-configuration \
2021-07-11T13:24:09.5732132Z -H:+AllowIncompleteClasspath \
2021-07-11T13:24:09.5732446Z -H:FallbackThreshold=0 \
2021-07-11T13:24:09.5732765Z -H:EnableURLProtocols=http,https \
2021-07-11T13:24:09.5733102Z -H:+ReportUnsupportedElementsAtRuntime \
2021-07-11T13:24:09.5733432Z -H:+AllowIncompleteClasspath \
2021-07-11T13:24:09.5733767Z -H:ClassInitialization=:build_time \
2021-07-11T13:24:09.5734184Z -H:CLibraryPath=/opt/graalvm-ee-java8-21.1.0/jre/lib/svm/clibraries/linux-amd64 \
2021-07-11T13:24:09.5734429Z ]
```

**Comment by fernando-valdez** [comment]
Hi @FieryCod, I will take care of this issue.
 
I will let you know if I have any questions.

**Comment by FieryCod** [comment]
Hi @fernando-valdez! Thank you! If you find any troubles with reproducing I can provide some simpler repro case :)

**Comment by fernando-valdez** [comment]
@FieryCod. 
Yes, please.  I was having issues following the instructions you provided. A simpler reproducer will be really appreciated

**Comment by fernando-valdez** [comment]
Hello @FieryCod,
The GraalVM development team took care of this issue. 
Here is the fix: https://github.com/oracle/graal/commit/41863b14cc310205a16bf5c41a2416a8da8c45a9
