### ISSUE TITLE
Cryptic error when outputting to non-existant directory

### ISSUE THREAD

**Issue by helins** [oracle/graal#3576]
**Describe the issue**

Outputting the native binary to an non-existant directory leads to a cryptic error at the end of the build process as seen below.

**Steps to reproduce the issue**

Either:
- Use the `-H:Name` to a non existing dir like `-H:Name=does/not/exist`
- Or in `native-image.properties` do the same with `ImageName`

**Describe GraalVM and your environment:**

Ubuntu 16.01 x86

```
$ java -version

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05, mixed mode, sharing)

$ native-image --version

GraalVM 21.1.0 Java 11 CE (Java Version 11.0.11+8-jvmci-21.1-b05)
```

Example of failure at write step because output directory does not exist. What is happening is very cryptic in regard of such a simple error:

```
[fdsf/Fqdfdf/qdfqsdf/Fdqfsd:5434]    classlist:   6,500.08 ms,  0.96 GB
[fdsf/Fqdfdf/qdfqsdf/Fdqfsd:5434]        (cap):   1,080.05 ms,  0.96 GB
[fdsf/Fqdfdf/qdfqsdf/Fdqfsd:5434]        setup:   4,506.56 ms,  0.96 GB
[fdsf/Fqdfdf/qdfqsdf/Fdqfsd:5434]     (clinit):     403.63 ms,  2.62 GB
[fdsf/Fqdfdf/qdfqsdf/Fdqfsd:5434]   (typeflow):  22,238.17 ms,  2.62 GB
[fdsf/Fqdfdf/qdfqsdf/Fdqfsd:5434]    (objects):  32,935.53 ms,  2.62 GB
[fdsf/Fqdfdf/qdfqsdf/Fdqfsd:5434]   (features):   1,605.57 ms,  2.62 GB
[fdsf/Fqdfdf/qdfqsdf/Fdqfsd:5434]     analysis:  58,374.71 ms,  2.62 GB
[fdsf/Fqdfdf/qdfqsdf/Fdqfsd:5434]     universe:   1,245.50 ms,  2.62 GB
[fdsf/Fqdfdf/qdfqsdf/Fdqfsd:5434]      (parse):   5,337.97 ms,  2.62 GB
[fdsf/Fqdfdf/qdfqsdf/Fdqfsd:5434]     (inline):   8,187.39 ms,  2.92 GB
[fdsf/Fqdfdf/qdfqsdf/Fdqfsd:5434]    (compile):  36,440.17 ms,  2.93 GB
[fdsf/Fqdfdf/qdfqsdf/Fdqfsd:5434]      compile:  51,431.87 ms,  2.94 GB
[fdsf/Fqdfdf/qdfqsdf/Fdqfsd:5434]        image:   4,746.86 ms,  2.94 GB
[fdsf/Fqdfdf/qdfqsdf/Fdqfsd:5434]        write:     579.63 ms,  2.94 GB
Fatal error:java.lang.RuntimeException: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1

Linker command executed:
/usr/bin/gcc -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-8375165265331956762/exported_symbols.list -Wl,--exclude-libs,ALL -Wl,-x -o /home/adam/projects/convex/clj/tool/fdsf/Fqdfdf/qdfqsdf/Fdqfsd fdsf/Fqdfdf/qdfqsdf/Fdqfsd.o /home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/adam/.sdkman/candidates/java/21.$
.0.r11-grl/lib/static/linux-amd64/glibc/libnet.a /home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/static/linux-amd64/glibc/libnio.a /home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/static/linux-amd64/glibc/libjava.a /home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/static/linux-amd64/glibc/libfdlibm.a /home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/static/li$
ux-amd64/glibc/libzip.a /home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/svm/clibraries/linux-amd64/libjvm.a -v -L/tmp/SVM-8375165265331956762 -L/home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/static/linux-amd64/glibc -L/home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/svm/clibraries/linux-amd64 -lpthread -ldl -lz -lrt

Linker command output:
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.12' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls $
-with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-ro$
t-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64$
linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-z' 'noexecstack' '-o' '/home/adam/projects/convex/clj/tool/fdsf/Fqdfdf/qdfqsdf/Fdqfsd' '-v' '-L/tmp/SVM-8375165265331956762' '-L/home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/static/linux-amd64/glibc' '-L/home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/5/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/5/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper -plugin-opt=-fresolution=/tmp/ccOkJwWi.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --sysroot=/ --build-$
d --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -z relro -o /home/adam/projects/convex/clj/tool/fdsf/Fqdfdf/qdfqsdf/Fdqfsd -z noexecstack /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/5/crtbegin.o -L/tmp/SVM-83$
5165265331956762 -L/home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/static/linux-amd64/glibc -L/home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-linux-gnu/5 -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64$
linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/5/../../.. --gc-sections --dynamic-list /tmp/SVM-8375165265331956762/exported_symbols.list --exclude-libs ALL -x fdsf/Fqdfdf/qdfqsdf/Fdqfsd.o /home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/static/linux-amd64/glibc/li$
net.a /home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/static/linux-amd64/glibc/libnio.a /home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/static/linux-amd64/glibc/libjava.a /home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/static/linux-amd64/glibc/libfdlibm.a /home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/static/linux-amd64/glibc/libzip.a /home/adam/.sdkman$
candidates/java/21.1.0.r11-grl/lib/svm/clibraries/linux-amd64/libjvm.a -lpthread -ldl -lz -lrt -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-linux-gnu/5/crtend.o /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crtn.o
/usr/bin/ld: cannot open output file /home/adam/projects/convex/clj/tool/fdsf/Fqdfdf/qdfqsdf/Fdqfsd: No such file or directory
collect2: error: ld returned 1 exit status
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
        at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:499)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:370)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:531)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:568)
Caused by: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1

Linker command executed:
/usr/bin/gcc -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-8375165265331956762/exported_symbols.list -Wl,--exclude-libs,ALL -Wl,-x -o /home/adam/projects/convex/clj/tool/fdsf/Fqdfdf/qdfqsdf/Fdqfsd fdsf/Fqdfdf/qdfqsdf/Fdqfsd.o /home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/adam/.sdkman/candidates/java/21.$
.0.r11-grl/lib/static/linux-amd64/glibc/libnet.a /home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/static/linux-amd64/glibc/libnio.a /home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/static/linux-amd64/glibc/libjava.a /home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/static/linux-amd64/glibc/libfdlibm.a /home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/static/li$
ux-amd64/glibc/libzip.a /home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/svm/clibraries/linux-amd64/libjvm.a -v -L/tmp/SVM-8375165265331956762 -L/home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/static/linux-amd64/glibc -L/home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/svm/clibraries/linux-amd64 -lpthread -ldl -lz -lrt

Linker command output:
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.12' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls $
-with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-ro$
t-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64$
linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-z' 'noexecstack' '-o' '/home/adam/projects/convex/clj/tool/fdsf/Fqdfdf/qdfqsdf/Fdqfsd' '-v' '-L/tmp/SVM-8375165265331956762' '-L/home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/static/linux-amd64/glibc' '-L/home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/5/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/5/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper -plugin-opt=-fresolution=/tmp/ccOkJwWi.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --sysroot=/ --build-$
d --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -z relro -o /home/adam/projects/convex/clj/tool/fdsf/Fqdfdf/qdfqsdf/Fdqfsd -z noexecstack /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/5/crtbegin.o -L/tmp/SVM-83$
5165265331956762 -L/home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/static/linux-amd64/glibc -L/home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-linux-gnu/5 -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64$
linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/5/../../.. --gc-sections --dynamic-list /tmp/SVM-8375165265331956762/exported_symbols.list --exclude-libs ALL -x fdsf/Fqdfdf/qdfqsdf/Fdqfsd.o /home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/static/linux-amd64/glibc/li$
net.a /home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/static/linux-amd64/glibc/libnio.a /home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/static/linux-amd64/glibc/libjava.a /home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/static/linux-amd64/glibc/libfdlibm.a /home/adam/.sdkman/candidates/java/21.1.0.r11-grl/lib/static/linux-amd64/glibc/libzip.a /home/adam/.sdkman$
candidates/java/21.1.0.r11-grl/lib/svm/clibraries/linux-amd64/libjvm.a -lpthread -ldl -lz -lrt -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-linux-gnu/5/crtend.o /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crtn.o
/usr/bin/ld: cannot open output file /home/adam/projects/convex/clj/tool/fdsf/Fqdfdf/qdfqsdf/Fdqfsd: No such file or directory
collect2: error: ld returned 1 exit status
        at com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:513)
        at com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:460)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:710)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:495)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
Error while executing task: native-image

```

**Comment by wirthi** [comment]
I believe this issue has been fixed in the meantime:

`$ native-image Example -H:Name=does/not/exist
Error: Writing image to non-existent directory /home/christian/oracle/examples/playground/does/not is not allowed. Create the missing directory if you want the image to be written to that location.
`
