### ISSUE TITLE
Resource Bundles do not work properly for jars placed on the host class path.

### ISSUE THREAD

**Issue by kustosz** [oracle/graal#3585]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **21.1.0**
 - CE or EE: **CE**
 - JDK version: **JDK11**
 - OS and OS Version: **macOS Big Sur 11.1**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
OpenJDK 64-Bit Server VM (11.0.11+8-jvmci-21.1-b05) for bsd-amd64 JRE (11.0.11+8-jvmci-21.1-b05), built on Apr 12 2021 09:12:59 by "graal1" with gcc 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)
```

**Have you verified this issue still happens when using the latest snapshot?**
You can find snapshot builds here: https://github.com/graalvm/graalvm-ce-dev-builds/releases
No.

**Describe the issue**
When using an apache xmlbeans JAR through host interop, the library cannot properly initialize itself, due to errors in loading resource bundles.

**Code snippet or code repository that reproduces the issue**
xmlbeans JAR to reproduce the issue can be downloaded here: https://mvnrepository.com/artifact/org.apache.xmlbeans/xmlbeans/5.0.1
Simple JS file reproducing the issue:
```js
Java.addToClasspath('xmlbeans-5.0.1')
x = Java.type('org.apache.xmlbeans.XmlBeans')
console.log(x.NO_TYPE)
```

**Steps to reproduce the issue**
1. Download the linked xmlbeans JAR file.
2. Keep the jar, but also create a directory called `xmlbeans`. Enter the directory and run `jar xf PATH_TO_XMLBEANS_JAR`, to extract the contents.
3. Run the JS snippet posted above. Note that it fails with an exception, the root cause of which is:
```
Caused by: java.io.FileNotFoundException: /Users/marcinkostrzewa/code/repro/xmlbeans.jar/org/apache/xmlbeans/impl/regex/message.properties (Not a directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
        at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
        at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:184)
        at java.base/java.util.ResourceBundle$Control$1.run(ResourceBundle.java:3227)
        at java.base/java.util.ResourceBundle$Control$1.run(ResourceBundle.java:3216)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:3215)
        at java.base/java.util.ResourceBundle.loadBundle(ResourceBundle.java:1994)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1776)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1728)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1728)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1662)
```
It looks like the resource bundle loader tries to access the `xmlbeans.jar` as a normal directory.
4. Now change the snippet above to `addToClasspath` the directory with extracted jar contents. Note that it works properly, printing something sensical. 

**Expected behavior**
Both a JAR dependency and an unzipped dependency should allow access to resource bundles.

**Comment by tzezula** [comment]
It's JDK specific, on the JDK 8 seems to work fine:
```
> Java.addToClasspath('xmlbeans-5.0.1.jar')
> x = Java.type('org.apache.xmlbeans.XmlBeans')
JavaClass[org.apache.xmlbeans.XmlBeans]
> console.log(x.NO_TYPE)
N=
```

**Comment by tzezula** [comment]
Fixed in dev build by https://github.com/oracle/graal/commit/588fab655c2f2483ba7f47ff01f67487175eab25.
