### ISSUE TITLE
Thread interrupts permanently break the HostClassLoader (Round 2)

### ISSUE THREAD

**Issue by iamrecursion** [oracle/graal#3590]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: 21.1 stable
 - CE or EE: **[e.g.: CE]** CE and EE
 - JDK version: **[e.g.: JDK8]** 11
 - OS and OS Version: **[e.g.: macOS Catalina]** macOS 11.4
 - Architecture: **[e.g.: amd64]** amd64
 - The output of `java -Xinternalversion`:
```
Java HotSpot(TM) 64-Bit Server VM (11.0.11+9-LTS-jvmci-21.1-b05) for bsd-amd64 JRE (11.0.11+9-LTS-jvmci-21.1-b05), built on Apr 13 2021 09:11:08 by "graal" with gcc 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)
```

**Have you verified this issue still happens when using the latest snapshot?**
Not yet, but will update the issue when I do.

**Describe the issue**
Using host interop in the presence of thread interrupts may break host interop forever. The HostClassLoader seems to enter an unrecoverably broken state when a thread interrupt happens. This is very concerning, as it suggests that it is unsafe to use thread interrupts with Truffle, as we have no guarantee as to when the classloader is running.

This was originally reported as #3273, and appeared to be fixed during the 21.1 series nightlies. We have, however, just observed what appears to be the same issue on 21.1 stable and can reproduce it using the same reproducer as before. Either I messed up the testing with the dev builds, or it has regressed.

**Code snippet or code repository that reproduces the issue**
```
import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.PolyglotException;

public class ClassLoaderBug {
    public static void main(String[] args) {
        var ctx = Context.newBuilder().allowAllAccess(true).build();
        ctx.eval("js", "Java.addToClasspath('icu4j-67.1.jar')");
        var cls = ctx.eval("js", "Java.type('com.ibm.icu.text.BreakIterator')");
        var fn = ctx.eval("js", "(cls) => { cls.getCharacterInstance(); }");

        Thread.currentThread().interrupt();

        try {
            System.out.println("Original execution");
            fn.execute(cls);
        } catch (PolyglotException e) {
            System.out.println(e);
            e.printStackTrace();
        }

        Thread.interrupted(); // make sure interrupt is cleared

        try {
            fn.execute(cls);
        } catch (PolyglotException e) {
            System.out.println(e);
            e.printStackTrace();
        }

    }
}
```

You will need the `icu4j-67.1.jar` in the same folder as the reproducer.

**Steps to reproduce the issue**
1. Paste the above code into a basic java file.
2. Run it on GraalVM.

**Expected behavior**
The `HostClassLoader` should not get broken.

**Additional context**
The first call to fn.execute(cls) fails with NoClassDefFoundError, with the root cause being:

```
Caused by: java.nio.channels.ClosedByInterruptException
        at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
        at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:162)
        at java.base/sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:366)
        at java.base/sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:52)
        at org.graalvm.truffle/com.oracle.truffle.api.TruffleFile$ByteChannelDecorator.position(TruffleFile.java:2219)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassLoader$JarLoader$ZipUtils.getInputStream(HostClassLoader.java:537)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassLoader$JarLoader$1.getInputStream(HostClassLoader.java:388)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassLoader$Resource.getContent(HostClassLoader.java:247)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassLoader.findClass(HostClassLoader.java:157)
        ... 58 more
```

However, the second (and any further) call to fn.execute(cls) fails with a NoClassDefFoundError, with the root cause:

```
Caused by: java.nio.channels.ClosedChannelException
        at java.base/sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:150)
        at java.base/sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:349)
        at java.base/sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:52)
        at org.graalvm.truffle/com.oracle.truffle.api.TruffleFile$ByteChannelDecorator.position(TruffleFile.java:2219)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassLoader$JarLoader$ZipUtils.getInputStream(HostClassLoader.java:537)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassLoader$JarLoader$1.getInputStream(HostClassLoader.java:388)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassLoader$Resource.getContent(HostClassLoader.java:247)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassLoader.findClass(HostClassLoader.java:157)
        ... 53 more
```

This suggests that the class loader is in a broken state, as seen before.

**Comment by mcraj017** [comment]
@iamrecursion thanks for reporting the issue, we will check it out and get back to you

**Comment by iamrecursion** [comment]
Thanks for the update!

**Comment by chumer** [comment]
We are investigating. Thanks for the report!

**Comment by iamrecursion** [comment]
Any updates on this one?

**Comment by tzezula** [comment]
It works fine for me.
Tested graalvm:
```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05, mixed mode, sharing)
```

I've used the above test case. I've just added `System.out.println("Second execution");` before second call to `fn.execute(cls);`.

There is no exception thrown from the second execution as seen from the output:
```
../graalvm-ce-java11-21.1.0/Contents/Home/bin/java ClassLoaderBug
Original execution
org.graalvm.polyglot.PolyglotException: java.lang.NoClassDefFoundError: com/ibm/icu/util/ICUCloneNotSupportedException
org.graalvm.polyglot.PolyglotException: java.lang.NoClassDefFoundError: com/ibm/icu/util/ICUCloneNotSupportedException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructors(Class.java:1943)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassDesc.hasDefaultConstructor(HostClassDesc.java:109)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassDesc.<init>(HostClassDesc.java:89)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassCache$1.computeValue(HostClassCache.java:183)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassCache$1.computeValue(HostClassCache.java:180)
	at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
	at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
	at java.base/java.lang.ClassValue.get(ClassValue.java:116)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassCache.forClass(HostClassCache.java:194)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassDesc.forClass(HostClassDesc.java:73)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostInteropReflect.findMethod(HostInteropReflect.java:112)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObject$LookupMethodNode.doUncached(HostObject.java:2441)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObjectFactory$LookupMethodNodeGen.executeAndSpecialize(HostObjectFactory.java:1136)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObjectFactory$LookupMethodNodeGen.execute(HostObjectFactory.java:1105)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObject.invokeMember(HostObject.java:428)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObjectGen$InteropLibraryExports$Cached.invokeMemberNode_AndSpecialize(HostObjectGen.java:2556)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObjectGen$InteropLibraryExports$Cached.invokeMember(HostObjectGen.java:2528)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.invokeMember(InteropLibraryGen.java:8138)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$ForeignInvokeNode.executeCall(JSFunctionCallNode.java:1478)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:305)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:251)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$InvokeNode.execute(JSFunctionCallNode.java:724)
	at com.oracle.truffle.js.nodes.control.DiscardResultNode.execute(DiscardResultNode.java:88)
	at com.oracle.truffle.js.nodes.binary.DualNode.execute(DualNode.java:125)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:147)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:93)
	at <js> :=>(Unknown)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.execute(Value.java:834)
	at ClassLoaderBug.main(ClassLoaderBug.java:15)
Original Internal Error:
java.lang.NoClassDefFoundError: com/ibm/icu/util/ICUCloneNotSupportedException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructors(Class.java:1943)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassDesc.hasDefaultConstructor(HostClassDesc.java:109)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassDesc.<init>(HostClassDesc.java:89)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassCache$1.computeValue(HostClassCache.java:183)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassCache$1.computeValue(HostClassCache.java:180)
	at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
	at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
	at java.base/java.lang.ClassValue.get(ClassValue.java:116)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassCache.forClass(HostClassCache.java:194)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassDesc.forClass(HostClassDesc.java:73)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostInteropReflect.findMethod(HostInteropReflect.java:112)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObject$LookupMethodNode.doUncached(HostObject.java:2441)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObjectFactory$LookupMethodNodeGen.executeAndSpecialize(HostObjectFactory.java:1136)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObjectFactory$LookupMethodNodeGen.execute(HostObjectFactory.java:1105)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObject.invokeMember(HostObject.java:428)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObjectGen$InteropLibraryExports$Cached.invokeMemberNode_AndSpecialize(HostObjectGen.java:2556)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObjectGen$InteropLibraryExports$Cached.invokeMember(HostObjectGen.java:2528)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.invokeMember(InteropLibraryGen.java:8138)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$ForeignInvokeNode.executeCall(JSFunctionCallNode.java:1478)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:305)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:251)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$InvokeNode.execute(JSFunctionCallNode.java:724)
	at com.oracle.truffle.js.nodes.control.DiscardResultNode.execute(DiscardResultNode.java:88)
	at com.oracle.truffle.js.nodes.binary.DualNode.execute(DualNode.java:125)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:147)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:93)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:613)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:584)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:534)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:518)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:481)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:71)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$UnboundJSFunctionCacheNode.executeCall(JSFunctionCallNode.java:1258)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:305)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:251)
	at com.oracle.truffle.js.nodes.interop.JSInteropExecuteNode.doDefault(JSInteropExecuteNode.java:68)
	at com.oracle.truffle.js.nodes.interop.JSInteropExecuteNodeGen.executeAndSpecialize(JSInteropExecuteNodeGen.java:59)
	at com.oracle.truffle.js.nodes.interop.JSInteropExecuteNodeGen.execute(JSInteropExecuteNodeGen.java:42)
	at com.oracle.truffle.js.runtime.builtins.JSFunctionObject.execute(JSFunctionObject.java:140)
	at com.oracle.truffle.js.runtime.builtins.JSFunctionObjectGen$InteropLibraryExports$Cached.executeNode_AndSpecialize(JSFunctionObjectGen.java:153)
	at com.oracle.truffle.js.runtime.builtins.JSFunctionObjectGen$InteropLibraryExports$Cached.execute(JSFunctionObjectGen.java:130)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.execute(InteropLibraryGen.java:7592)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValue$InteropCodeCache$AbstractExecuteNode.executeShared(PolyglotValue.java:3097)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValue$InteropCodeCache$ExecuteNode.executeImpl(PolyglotValue.java:3178)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:134)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:613)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:584)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:534)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:518)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalRuntimeSupport.callProfiled(GraalRuntimeSupport.java:143)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValue$InteropValue.execute(PolyglotValue.java:4537)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.execute(Value.java:834)
	at ClassLoaderBug.main(ClassLoaderBug.java:15)
Caused by: java.lang.ClassNotFoundException: Cannot load class: com.ibm.icu.util.ICUCloneNotSupportedException
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassLoader.findClass(HostClassLoader.java:161)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 56 more
Caused by: java.nio.channels.ClosedByInterruptException
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
	at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:162)
	at java.base/sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:366)
	at java.base/sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:52)
	at org.graalvm.truffle/com.oracle.truffle.api.TruffleFile$ByteChannelDecorator.position(TruffleFile.java:2219)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassLoader$JarLoader$ZipUtils.getInputStream(HostClassLoader.java:530)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassLoader$JarLoader$1.getInputStream(HostClassLoader.java:387)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassLoader$Resource.getContent(HostClassLoader.java:247)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassLoader.findClass(HostClassLoader.java:157)
	... 58 more
Second execution
```

**Comment by iamrecursion** [comment]
This is very odd. I can reproduce it on EE, but not on CE. 

```
java 11.0.11 2021-04-20 LTS
Java(TM) SE Runtime Environment GraalVM EE 21.1.0 (build 11.0.11+9-LTS-jvmci-21.1-b05)
Java HotSpot(TM) 64-Bit Server VM GraalVM EE 21.1.0 (build 11.0.11+9-LTS-jvmci-21.1-b05, mixed mode, sharing)
```

EE gives:

```
Original execution
org.graalvm.polyglot.PolyglotException: java.lang.NoClassDefFoundError: com/ibm/icu/util/ICUCloneNotSupportedException
Second execution
org.graalvm.polyglot.PolyglotException: java.lang.NoClassDefFoundError: com/ibm/icu/util/ICUCloneNotSupportedException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructors(Class.java:1943)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassDesc.hasDefaultConstructor(HostClassDesc.java:109)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassDesc.<init>(HostClassDesc.java:89)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassCache$1.computeValue(HostClassCache.java:183)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassCache$1.computeValue(HostClassCache.java:180)
	at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
	at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
	at java.base/java.lang.ClassValue.get(ClassValue.java:116)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassCache.forClass(HostClassCache.java:194)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassDesc.forClass(HostClassDesc.java:73)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostInteropReflect.findMethod(HostInteropReflect.java:112)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObject$LookupMethodNode.doUncached(HostObject.java:2441)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObjectFactory$LookupMethodNodeGen.executeAndSpecialize(HostObjectFactory.java:1136)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObjectFactory$LookupMethodNodeGen.execute(HostObjectFactory.java:1105)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObject.invokeMember(HostObject.java:428)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObjectGen$InteropLibraryExports$Cached.invokeMemberNode_AndSpecialize(HostObjectGen.java:2556)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObjectGen$InteropLibraryExports$Cached.invokeMember(HostObjectGen.java:2528)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.invokeMember(InteropLibraryGen.java:8138)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$ForeignInvokeNode.executeCall(JSFunctionCallNode.java:1478)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:305)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:251)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$InvokeNode.execute(JSFunctionCallNode.java:724)
	at com.oracle.truffle.js.nodes.control.DiscardResultNode.execute(DiscardResultNode.java:88)
	at com.oracle.truffle.js.nodes.binary.DualNode.execute(DualNode.java:125)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:147)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:93)
	at <js> :=>(Unknown)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.execute(Value.java:834)
	at ClassLoaderBug.main(ClassLoaderBug.java:15)
Original Internal Error: 
java.lang.NoClassDefFoundError: com/ibm/icu/util/ICUCloneNotSupportedException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructors(Class.java:1943)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassDesc.hasDefaultConstructor(HostClassDesc.java:109)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassDesc.<init>(HostClassDesc.java:89)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassCache$1.computeValue(HostClassCache.java:183)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassCache$1.computeValue(HostClassCache.java:180)
	at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
	at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
	at java.base/java.lang.ClassValue.get(ClassValue.java:116)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassCache.forClass(HostClassCache.java:194)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassDesc.forClass(HostClassDesc.java:73)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostInteropReflect.findMethod(HostInteropReflect.java:112)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObject$LookupMethodNode.doUncached(HostObject.java:2441)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObjectFactory$LookupMethodNodeGen.executeAndSpecialize(HostObjectFactory.java:1136)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObjectFactory$LookupMethodNodeGen.execute(HostObjectFactory.java:1105)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObject.invokeMember(HostObject.java:428)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObjectGen$InteropLibraryExports$Cached.invokeMemberNode_AndSpecialize(HostObjectGen.java:2556)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostObjectGen$InteropLibraryExports$Cached.invokeMember(HostObjectGen.java:2528)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.invokeMember(InteropLibraryGen.java:8138)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$ForeignInvokeNode.executeCall(JSFunctionCallNode.java:1478)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:305)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:251)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$InvokeNode.execute(JSFunctionCallNode.java:724)
	at com.oracle.truffle.js.nodes.control.DiscardResultNode.execute(DiscardResultNode.java:88)
	at com.oracle.truffle.js.nodes.binary.DualNode.execute(DualNode.java:125)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:147)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:93)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:613)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:584)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:534)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:518)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:481)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:71)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$UnboundJSFunctionCacheNode.executeCall(JSFunctionCallNode.java:1258)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:305)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:251)
	at com.oracle.truffle.js.nodes.interop.JSInteropExecuteNode.doDefault(JSInteropExecuteNode.java:68)
	at com.oracle.truffle.js.nodes.interop.JSInteropExecuteNodeGen.executeAndSpecialize(JSInteropExecuteNodeGen.java:59)
	at com.oracle.truffle.js.nodes.interop.JSInteropExecuteNodeGen.execute(JSInteropExecuteNodeGen.java:42)
	at com.oracle.truffle.js.runtime.builtins.JSFunctionObject.execute(JSFunctionObject.java:140)
	at com.oracle.truffle.js.runtime.builtins.JSFunctionObjectGen$InteropLibraryExports$Cached.executeNode_AndSpecialize(JSFunctionObjectGen.java:153)
	at com.oracle.truffle.js.runtime.builtins.JSFunctionObjectGen$InteropLibraryExports$Cached.execute(JSFunctionObjectGen.java:130)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.execute(InteropLibraryGen.java:7592)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValue$InteropCodeCache$AbstractExecuteNode.executeShared(PolyglotValue.java:3097)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValue$InteropCodeCache$ExecuteNode.executeImpl(PolyglotValue.java:3178)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:134)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:613)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:584)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:534)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:518)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalRuntimeSupport.callProfiled(GraalRuntimeSupport.java:143)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValue$InteropValue.execute(PolyglotValue.java:4537)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.execute(Value.java:834)
	at ClassLoaderBug.main(ClassLoaderBug.java:15)
Caused by: java.lang.ClassNotFoundException: Cannot load class: com.ibm.icu.util.ICUCloneNotSupportedException
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassLoader.findClass(HostClassLoader.java:161)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 56 more
Caused by: java.nio.channels.ClosedByInterruptException
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
	at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:162)
	at java.base/sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:366)
	at java.base/sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:52)
	at org.graalvm.truffle/com.oracle.truffle.api.TruffleFile$ByteChannelDecorator.position(TruffleFile.java:2219)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassLoader$JarLoader$ZipUtils.getInputStream(HostClassLoader.java:530)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassLoader$JarLoader$1.getInputStream(HostClassLoader.java:387)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassLoader$Resource.getContent(HostClassLoader.java:247)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostClassLoader.findClass(HostClassLoader.java:157)
	... 58 more

Process finished with exit code 0
```

**Comment by iamrecursion** [comment]
Interrupting still shouldn't leave the class loader in a broken sate.

**Comment by hubertp** [comment]
Still reproducible on `GraalVM CE 17.0.7+7.1`
