### ISSUE TITLE
Exception when running a Quarkus native image with JFR enabled

### ISSUE THREAD

**Issue by vic-ma** [oracle/graal#3608]
**Describe the issue**

I am trying to build and run a native image of a [simple Quarkus program](https://github.com/vic-ma/getting-started/blob/master/src/main/java/org/acme/getting/started/GreetingResource.java), which has some JFR code in it. The program is essentially just the Quarkus getting-started program with [a few bits of JFR code added](https://github.com/vic-ma/getting-started/commit/eb4864a84d593fd3e425be913136a0c976238b1a).

The native image builds without any issues, and when I run it without enabling JFR, the program runs as expected. However, when I enable JFR (regardless of starting a recording or not), [it will cause an exception](https://gist.github.com/vic-ma/4cd255df57293151f0e9a3d3bfa118fb).

This exception is a little unpredictable though, because I've had a case where I rebuilt the native image, without making any changes to the source code, and the resulting native image did not give an exception when running it with JFR enabled. And when I started a recording on this native image, the resulting recording had the expected events in it.

Another interesting thing is that the likelihood of a build working seems to be proportional to the amount of JFR code. When I removed all of the code I added, the build seems to always work; when I changed it to have only one event instead of three, it seems to work about 50% of the time; and with the original code, a working native image is more rare.

**Steps to reproduce the issue**

1. Download GraalVM and install native image.

Download: https://github.com/graalvm/graalvm-ce-dev-builds/releases/download/21.3.0-dev-20210716_2001/graalvm-ce-java11-linux-amd64-dev.tar.gz

```
$ tar xzf graalvm-ce-java11-linux-amd64-dev.tar.gz
$ cd graalvm-ce-java11-21.3.0-dev/
$ export GRAALVM_HOME=$(pwd)
$ ./bin/gu install native-image
```

2. Clone Quarkus project.

```
$ cd ..
$ git clone https://github.com/vic-ma/getting-started.git
```

3. Build the native image.

```
$ cd getting-started
$ ./mvnw clean && ./mvnw package -Pnative -Dquarkus.native.additional-build-args="-H:+AllowVMInspection"
```

4. Run the native image with JFR enabled.

```
$ ./target/getting-started-1.0.0-SNAPSHOT-runner -XX:+FlightRecorder
```

**Describe GraalVM and your environment:**
 - GraalVM version: **CE 21.3.0-dev-20210716_2001**
 - JDK major version: **11**
 - OS: **Fedora 32**
 - Architecture: **AMD64**

**More details**

The exception: https://gist.github.com/vic-ma/4cd255df57293151f0e9a3d3bfa118fb

Build log of a native image that gave the exception: https://gist.github.com/vic-ma/ac95b99a370a550f68dd6c6dfc92b46d

Build log of a native image that worked: https://gist.github.com/vic-ma/0639b30cbbe39b7f86bf393c5305fd1f

**Comment by vic-ma** [comment]
Here are some logs from an initial debugging attempt I did:

[Original program, Broken (1)](https://gist.github.com/vic-ma/78ead6538e5cca817554d1b74b5d3c2c)
[Original program, Broken (2)](https://gist.github.com/vic-ma/8b2646ce4a8147695e833e122b7e4af1)
[Only Alpha event/method, Broken](https://gist.github.com/vic-ma/da39f6d9ccbea4694588af11b2e4a0c5)
[Only Alpha event/method, Working](https://gist.github.com/vic-ma/def0b14ce036e3c0db115bbe9f42f358)

[Here is the diff](https://gist.github.com/vic-ma/e06bfd08505140678b12de962d27e2cb) for LabsJDK. I just added some print statements in the last two methods of the stack trace.

With the original program, the first log shows that the problematic event is `Alpha`, whereas the second log—a different native image build—shows that it is `Beta`. So I think this implies that the reason why the original program is much more likely to fail is because each custom event has some chance of failing, and obviously having three events increases the overall chance of having a broken build a lot.

The exception is `java.lang.NoSuchFieldException: eventHandler`, so somehow the broken event sometimes doesn't have the `eventHandler` field, and other times it does, and this is determiend at image build time, since the behaviour doesn't change after an image is built.

**Comment by jiekang** [comment]
Users can workaround this temporarily by supplying another flag to the native image builder: `-J-XX:FlightRecorderOptions=retransform=false`. For example

`native-image -J-XX:FlightRecorderOptions=retransform=false ... `

This flag causes the JVM to immediately transform all event classes on class creation.

**Comment by jiekang** [comment]
Normally the event classes are transformed via the SubstitutionProcessor: [JfrEventSubstitution](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.jfr/src/com/oracle/svm/jfr/JfrEventSubstitution.java)

Given the report, I suspect a race condition where the resulting class that is transformed via this processor is overriden by another class instance that is not transformed. A fix would likely move the transformation to be earlier in the process, similar to the `retransform=false` flag, but on the SubstrateVM side so as not to rely on HotSpot internals, if that's even a possibility.

My current expertise in SubstrateVM is not high enough yet to do more than speculate though. It would also be nice to figure out what exactly is causing the resulting image to have classes that aren't transformed by this processor.

My investigation continues!

**Comment by jiekang** [comment]
The custom events in the Quarkus app are initialized through this codepath:
```
initEventClass: class org.acme.getting.started.Alpha
java.lang.Exception
	at com.oracle.svm.jfr.JfrEventSubstitution.initEventClass(JfrEventSubstitution.java:85)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
	at com.oracle.svm.jfr.JfrEventSubstitution.lookup(JfrEventSubstitution.java:70)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:207)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:187)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.<init>(AnalysisMethod.java:142)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createMethod(AnalysisUniverse.java:431)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:419)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:396)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:77)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaMethod(UniverseMetaAccess.java:93)
	at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaMethod(AnalysisMetaAccess.java:66)
	at com.oracle.svm.hosted.substitute.SubstitutionReflectivityFilter.shouldExclude(SubstitutionReflectivityFilter.java:62)
	at com.oracle.svm.reflect.hosted.ReflectionDataBuilder.filterMethods(ReflectionDataBuilder.java:421)
	at com.oracle.svm.reflect.hosted.ReflectionDataBuilder.filterMethods(ReflectionDataBuilder.java:411)
	at com.oracle.svm.reflect.hosted.ReflectionDataBuilder.processClass(ReflectionDataBuilder.java:259)
	at com.oracle.svm.reflect.hosted.ReflectionDataBuilder.processRegisteredElements(ReflectionDataBuilder.java:202)
	at com.oracle.svm.reflect.hosted.ReflectionDataBuilder.duringAnalysis(ReflectionDataBuilder.java:150)
	at com.oracle.svm.reflect.hosted.ReflectionFeature.duringAnalysis(ReflectionFeature.java:96)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$12(NativeImageGenerator.java:728)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:73)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:728)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:489)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:399)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:562)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:121)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:592)
```

While non-Quarkus custom events, as well as internal events generally look like:

```
initEventClass: class com.redhat.jfr.events.IntegerEvent
java.lang.Exception
	at com.oracle.svm.jfr.JfrEventSubstitution.initEventClass(JfrEventSubstitution.java:85)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.oracle.svm.jfr.JfrEventSubstitution.lookup(JfrEventSubstitution.java:70)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:207)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:187)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.<init>(AnalysisMethod.java:142)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createMethod(AnalysisUniverse.java:431)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:419)
	at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupMethod(WrappedConstantPool.java:125)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.lookupMethodInPool(BytecodeParser.java:4308)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.lookupMethodInPool(SharedGraphBuilderPhase.java:140)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.lookupMethod(BytecodeParser.java:4302)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1626)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5377)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3435)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3395)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3240)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1122)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1007)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:81)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:132)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:615)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:163)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:321)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:293)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureTypeFlowCreated(MethodTypeFlow.java:282)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:222)
	at com.oracle.graal.pointsto.flow.TypeFlow$1.run(TypeFlow.java:434)
	at com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:188)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:172)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by vic-ma** [comment]
@jiekang

>Users can workaround this temporarily by supplying another flag to the native image builder: -J-XX:FlightRecorderOptions=retransform=false. 

Should building the native image with `./mvnw package -Pnative -Dquarkus.native.additional-build-args="-H:+AllowVMInspection,-J-XX:FlightRecorderOptions=retransform=false"` work around the issue? I still see the exception when I do this.

**Comment by jiekang** [comment]
> @jiekang
> 
> > Users can workaround this temporarily by supplying another flag to the native image builder: -J-XX:FlightRecorderOptions=retransform=false.
> 
> Should building the native image with `./mvnw package -Pnative -Dquarkus.native.additional-build-args="-H:+AllowVMInspection,-J-XX:FlightRecorderOptions=retransform=false"` work around the issue? I still see the exception when I do this.

@vic-ma 

I wasn't able to add multiple args to `-Dquarkus.native.additional-build-args=` for some reason. My test was building the native image manually by running something like:


```
path/to/native-image "-J-XX:FlightRecorderOptions=retransform=false" -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Duser.country=US -J-Dfile.encoding=UTF-8 -H:+AllowVMInspection --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -jar getting-started-1.0.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http -H:NativeLinkerOption=-no-pie -H:-UseServiceLoaderFeature -H:+StackTrace getting-started-1.0.0-SNAPSHOT-runner
```


in the `getting-started/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar` directory.


Maybe I got insanely lucky with the run though. I should have ran it 10 times or something lol...

**Comment by jiekang** [comment]
> @jiekang
> 
> > Users can workaround this temporarily by supplying another flag to the native image builder: -J-XX:FlightRecorderOptions=retransform=false.
> 
> Should building the native image with `./mvnw package -Pnative -Dquarkus.native.additional-build-args="-H:+AllowVMInspection,-J-XX:FlightRecorderOptions=retransform=false"` work around the issue? I still see the exception when I do this.

Okay, it seems I got the lucky run and it can still fail even with the flag passed to the JVM. Sorry about that then.

**Comment by jiekang** [comment]
After looking through the call chain and order on a few runs as well as the reports from `-H:+PrintAnalysisCallTree -H:+PrintImageObjectTree`, I'm suspecting a race condition with the Reflection feature where the `eventHandler` field is not always registered for these custom events. Currently collecting more logs of successful vs unsuccessful runs, but do have some fixes in mind if this is the case.

**Comment by jiekang** [comment]
Log difference: successful run contains

```
processClass: class com.redhat.jfr.Zeta
java.lang.Exception
        at com.oracle.svm.reflect.hosted.ReflectionDataBuilder.processClass(ReflectionDataBuilder.java:218)
        at com.oracle.svm.reflect.hosted.ReflectionDataBuilder.processRegisteredElements(ReflectionDataBuilder.java:210)
        at com.oracle.svm.reflect.hosted.ReflectionDataBuilder.duringAnalysis(ReflectionDataBuilder.java:158)
        at com.oracle.svm.reflect.hosted.ReflectionFeature.duringAnalysis(ReflectionFeature.java:96)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$12(NativeImageGenerator.java:728)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:73)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:728)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:489)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:399)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:562)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:121)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:592)
```

while unsuccessful run does not. Both runs do `initEventClass` for the custom event, (successful run does `initEventClass` before this `processClasses` log, and in both runs, the object tree does contain an eventHandler which is referenced in the call tree too.

So I'm guessing there's a race of some sort between the `ReflectionFeature` and the `JfrEventSubstitution.initEventClass` which calls:
```
Field field = ReflectionUtil.lookupField(newEventClass, "eventHandler");   // EventInstrumentation.FIELD_EVENT_HANDLER
            RuntimeReflection.register(field);
```

I'm also supposing that these custom events exhibit the issue because they're in a http request method that isn't directly called by anything so the lookup to resolve the event class is a bit different, but that's unrelated to the fix.

**Comment by jiekang** [comment]
@vic-ma 

I have a fix here: https://github.com/jiekang/graal/tree/3608 Would appreciate if you can try it out on your end too!

**Comment by vic-ma** [comment]
@jiekang It seems to fix the issue for me. I built three native images, and they all worked, and the resulting recording has the expected events in it.

**Comment by adinn** [comment]
@jiekang That definitely looks like a point at which a retransform race might occur. It would be good to add a comment next to the retransform call explaining that the reflection registration for the event handler field needs to be delayed to the feature duringAnalysis callback so that Field lookup it requires will not race/interfere with other required retransforms.
