### ISSUE TITLE
`DeletedElementException` regression with Micronaut and Cassandra

### ISSUE THREAD

**Issue by ilopmar** [oracle/graal#3609]
**Describe the issue**

Our CI has detected a regression with a Micronaut Cassandra GraalVM application. When building the native image with latest code from `master` branch, it fails with a `DeletedElementException`.

**Steps to reproduce the issue**

- `git clone https://github.com/micronaut-graal-tests/micronaut-cassandra-graal`
- `cd micronaut-cassandra-graal`
- `git checkout deleted-element-exception`
- Use GraalVM compiled from `master` branch.
- `./gradlew nativeImage`

**Describe GraalVM and your environment:**
 - GraalVM version: Commit **e0282924f3d752b49facf10cfbd766c9be2a4e32** from `master`. It worked last Friday when we run it compiling GraalVM from `master` branch commit cbf1f397fc6d0e0e4fc9919af46b7b349702fcfa.
 - 
 - JDK major version: **11**
 - OS: **Linux Mint 20.1**
 - Architecture: **AMD64**

**More details**

```
[cassandra:39162]    classlist:   3,285.26 ms,  1.18 GB
[cassandra:39162]        (cap):     591.34 ms,  1.18 GB
[cassandra:39162]        setup:   2,683.84 ms,  1.18 GB
[cassandra:39162]     (clinit):   1,244.58 ms,  5.14 GB
[cassandra:39162]   (typeflow):  33,739.41 ms,  5.14 GB
[cassandra:39162]    (objects):  30,490.17 ms,  5.14 GB
[cassandra:39162]   (features):   3,388.19 ms,  5.14 GB
[cassandra:39162]     analysis:  72,279.57 ms,  5.14 GB
Error: Unsupported features in 3 methods
[cassandra:39162]    Detailed message:
  [total]:  78,516.39 ms,  5.14 GB
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.Class.getConstantPool() is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Trace: 
        at parsing java.lang.System$2.getConstantPool(System.java:2088)
Call path from entry point to java.lang.System$2.getConstantPool(Class): 
        at java.lang.System$2.getConstantPool(System.java:2088)
        at sun.reflect.annotation.TypeAnnotationParser.parseAllTypeAnnotations(TypeAnnotationParser.java:342)
        at sun.reflect.annotation.TypeAnnotationParser.fetchBounds(TypeAnnotationParser.java:318)
        at sun.reflect.annotation.TypeAnnotationParser.parseAnnotatedBounds(TypeAnnotationParser.java:263)
        at sun.reflect.annotation.TypeAnnotationParser.parseAnnotatedBounds(TypeAnnotationParser.java:256)
        at sun.reflect.generics.reflectiveObjects.TypeVariableImpl.getAnnotatedBounds(TypeVariableImpl.java:218)
        at com.oracle.svm.reflect.TypeVariable_getAnnotatedBounds_88ea462da2b17ea45028db307519aaeeec9a4036_349.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at java.util.ServiceLoader$ProviderImpl.invokeFactoryMethod(ServiceLoader.java:737)
        at java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:720)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:216)
# Printing build artifacts to: /tmp/micronaut-cassandra-graal/build/native-image/cassandra.build_artifacts.txt
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:169)
        at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:290)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.Class.getExecutableTypeAnnotationBytes(Executable) is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Trace: 
        at parsing java.lang.System$2.getRawExecutableTypeAnnotations(System.java:2106)
Call path from entry point to java.lang.System$2.getRawExecutableTypeAnnotations(Executable): 
        at java.lang.System$2.getRawExecutableTypeAnnotations(System.java:2106)
        at sun.reflect.annotation.TypeAnnotationParser.parseAllTypeAnnotations(TypeAnnotationParser.java:337)
        at sun.reflect.annotation.TypeAnnotationParser.fetchBounds(TypeAnnotationParser.java:318)
        at sun.reflect.annotation.TypeAnnotationParser.parseAnnotatedBounds(TypeAnnotationParser.java:263)
        at sun.reflect.annotation.TypeAnnotationParser.parseAnnotatedBounds(TypeAnnotationParser.java:256)
        at sun.reflect.generics.reflectiveObjects.TypeVariableImpl.getAnnotatedBounds(TypeVariableImpl.java:218)
        at com.oracle.svm.reflect.TypeVariable_getAnnotatedBounds_88ea462da2b17ea45028db307519aaeeec9a4036_349.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at java.util.ServiceLoader$ProviderImpl.invokeFactoryMethod(ServiceLoader.java:737)
        at java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:720)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:216)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:169)
        at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:290)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.Class.getRawTypeAnnotations() is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Trace: 
        at parsing java.lang.System$2.getRawClassTypeAnnotations(System.java:2103)
Call path from entry point to java.lang.System$2.getRawClassTypeAnnotations(Class): 
        at java.lang.System$2.getRawClassTypeAnnotations(System.java:2103)
        at sun.reflect.annotation.TypeAnnotationParser.parseAllTypeAnnotations(TypeAnnotationParser.java:334)
        at sun.reflect.annotation.TypeAnnotationParser.fetchBounds(TypeAnnotationParser.java:318)
        at sun.reflect.annotation.TypeAnnotationParser.parseAnnotatedBounds(TypeAnnotationParser.java:263)
        at sun.reflect.annotation.TypeAnnotationParser.parseAnnotatedBounds(TypeAnnotationParser.java:256)
        at sun.reflect.generics.reflectiveObjects.TypeVariableImpl.getAnnotatedBounds(TypeVariableImpl.java:218)
        at com.oracle.svm.reflect.TypeVariable_getAnnotatedBounds_88ea462da2b17ea45028db307519aaeeec9a4036_349.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at java.util.ServiceLoader$ProviderImpl.invokeFactoryMethod(ServiceLoader.java:737)
        at java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:720)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:216)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:169)
        at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:290)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

Using `--report-unsupported-elements-at-runtime` as suggested in the error messages leads to the following error:

```
[cassandra:40208]    classlist:   3,395.91 ms,  1.18 GB
[cassandra:40208]        setup:     555.61 ms,  1.18 GB
Fatal error:java.lang.NoClassDefFoundError: Lnet/jpountz/lz4/LZ4Compressor;
        at java.base/java.lang.Class.getDeclaredFields0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3061)
        at java.base/java.lang.Class.getDeclaredFields(Class.java:2248)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleDeletedClass(AnnotationSubstitutionProcessor.java:533)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:306)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:266)
        at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:934)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:866)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:528)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:489)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:399)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:562)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:121)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:592)
[cassandra:40208]      Caused by: java.lang.ClassNotFoundException: net.jpountz.lz4.LZ4Compressor
[total]:   4,020.31 ms,         at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
 1.18 GB
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 14 more
Error: Image build request failed with exit status 1
```

**Comment by mcraj017** [comment]
@ilopmar thanks for reporting the issue, I have raised the issue with Dev team

**Comment by ilopmar** [comment]
Awesome. Our build is passing again :-)
