### ISSUE TITLE
PolyglotException: TypeError: Access to host class java.lang.String is not allowed or does not exist

### ISSUE THREAD

**Issue by PhilippSalvisberg** [oracle/graal#3624]
**Describe the issue**
Building a native image using `--no-fallback --language:js` leads to a `javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: TypeError: Access to host class java.lang.String is not allowed or does not exist.` error. 

When I build the native image using `--force-fallback`, then everything is fine. Configuration of script engine should be OK, see [here](https://github.com/Trivadis/plsql-formatter-settings/blob/58914adcdc7bbd4122a791eb9e95a5f187ec14ff/standalone/src/main/java/com/trivadis/plsql/formatter/TvdFormat.java#L17-L26)

I'm not sure if this is a bug or if I'm doing something wrong. 

Any help is appreciated.

Thank you.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Build the project according  [How to build](https://github.com/Trivadis/plsql-formatter-settings/blob/58914adcdc7bbd4122a791eb9e95a5f187ec14ff/standalone/README.md#how-to-build)
2. `cd target`
3. Run native image `./tvdformat` without parameters (works, usage is shown, image size 12M)
4. Build native image with `$JAVA_HOME/bin/native-image -H:IncludeResources=.\* --no-fallback --language:js -jar tvdformat.jar`
5. Run native image `./tvdformat` without parameters (does not work, PolyglotException thrown, image size 370M)

**Describe GraalVM and your environment:**
 - GraalVM version:  **CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08)**
 - JDK major version: **8** (target)
 - OS: **macOS Bis Sur 11.3.1**
 - Architecture: **darwin-amd64**

**More details**
Here's the output of the step 4 above with `--native-image-info` and  `--verbose` flags;

```
Apply jar:file:///Users/phs/github/trivadis/plsql-formatter-settings/standalone/target/lib/graal-sdk-21.2.0.jar!/META-INF/native-image/org.graalvm.home/native-image.properties
Apply jar:file:///Users/phs/github/trivadis/plsql-formatter-settings/standalone/target/lib/graal-sdk-21.2.0.jar!/META-INF/native-image/org.graalvm.polyglot/native-image.properties
Executing [
/Users/phs/graalvm/graalvm-ce-java11-21.2.0/Contents/Home/bin/java \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
--add-exports=java.base/com.sun.crypto.provider=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.event=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.loader=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.logger=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.misc=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.module=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.org.xml.sax.helpers=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.perf=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.ref=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.util.xml.impl=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.util.xml=ALL-UNNAMED \
--add-exports=java.base/sun.invoke.util=ALL-UNNAMED \
--add-exports=java.base/sun.nio.ch=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.annotation=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.reflectiveObjects=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.repository=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.tree=ALL-UNNAMED \
--add-exports=java.base/sun.security.jca=ALL-UNNAMED \
--add-exports=java.base/sun.security.provider=ALL-UNNAMED \
--add-exports=java.base/sun.security.util=ALL-UNNAMED \
--add-exports=java.base/sun.text.spi=ALL-UNNAMED \
--add-exports=java.base/sun.util.calendar=ALL-UNNAMED \
--add-exports=java.base/sun.util.locale.provider=ALL-UNNAMED \
--add-exports=java.base/sun.util.resources=ALL-UNNAMED \
--add-exports=java.xml.crypto/org.jcp.xml.dsig.internal.dom=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.site=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.stack=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.common=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.sparc=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.runtime=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.services=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.sparc=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.events=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal.consumer=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal.handlers=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal.jfc=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal=ALL-UNNAMED \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Duser.country=US \
-Duser.language=en \
-Djava.awt.headless=true \
-Dorg.graalvm.version=21.2.0 \
-Dorg.graalvm.config=CE \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
--module-path \
/Users/phs/graalvm/graalvm-ce-java11-21.2.0/Contents/Home/lib/truffle/truffle-api.jar \
-Dtruffle.TruffleRuntime=com.oracle.svm.truffle.api.SubstrateTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=false \
-Dpolyglot.image-build-time.PreinitializeContexts=js \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-Dsubstratevm.ImageIncludeBuiltinModules=org.graalvm.truffle \
-Xmx13743895344 \
-javaagent:/Users/phs/graalvm/graalvm-ce-java11-21.2.0/Contents/Home/lib/svm/builder/svm.jar \
-cp \
/Users/phs/graalvm/graalvm-ce-java11-21.2.0/Contents/Home/lib/svm/builder/llvm-wrapper-shadowed.jar:/Users/phs/graalvm/graalvm-ce-java11-21.2.0/Contents/Home/lib/svm/builder/svm.jar:/Users/phs/graalvm/graalvm-ce-java11-21.2.0/Contents/Home/lib/svm/builder/objectfile.jar:/Users/phs/graalvm/graalvm-ce-java11-21.2.0/Contents/Home/lib/svm/builder/llvm-platform-specific-shadowed.jar:/Users/phs/graalvm/graalvm-ce-java11-21.2.0/Contents/Home/lib/svm/builder/javacpp-shadowed.jar:/Users/phs/graalvm/graalvm-ce-java11-21.2.0/Contents/Home/lib/svm/builder/svm-llvm.jar:/Users/phs/graalvm/graalvm-ce-java11-21.2.0/Contents/Home/lib/svm/builder/pointsto.jar \
'com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus' \
-imagecp \
/Users/phs/graalvm/graalvm-ce-java11-21.2.0/Contents/Home/languages/regex/tregex.jar:/Users/phs/graalvm/graalvm-ce-java11-21.2.0/Contents/Home/languages/js/icu4j.jar:/Users/phs/graalvm/graalvm-ce-java11-21.2.0/Contents/Home/languages/js/graaljs.jar:/Users/phs/github/trivadis/plsql-formatter-settings/standalone/target/lib/dbtools-common-21.2.0.jar:/Users/phs/github/trivadis/plsql-formatter-settings/standalone/target/lib/js-21.2.0.jar:/Users/phs/github/trivadis/plsql-formatter-settings/standalone/target/lib/regex-21.2.0.jar:/Users/phs/github/trivadis/plsql-formatter-settings/standalone/target/lib/truffle-api-21.2.0.jar:/Users/phs/github/trivadis/plsql-formatter-settings/standalone/target/lib/icu4j-69.1.jar:/Users/phs/github/trivadis/plsql-formatter-settings/standalone/target/lib/js-scriptengine-21.2.0.jar:/Users/phs/github/trivadis/plsql-formatter-settings/standalone/target/lib/graal-sdk-21.2.0.jar:/Users/phs/github/trivadis/plsql-formatter-settings/standalone/target/tvdformat.jar:/Users/phs/graalvm/graalvm-ce-java11-21.2.0/Contents/Home/lib/svm/library-support.jar \
-H:Path=/Users/phs/github/trivadis/plsql-formatter-settings/standalone/target \
'-H:IncludeResources=.*' \
-H:FallbackThreshold=0 \
-H:Features@--macro:truffle=com.oracle.svm.truffle.TruffleFeature,org.graalvm.home.HomeFinderFeature \
-H:MaxRuntimeCompileMethods@--macro:truffle=2000 \
-H:ClassInitialization@--macro:truffle=org.graalvm.launcher:build_time,com.oracle.truffle:build_time \
-H:MaxRuntimeCompileMethods@--language:regex=900 \
-H:MaxRuntimeCompileMethods@--language:js=9200 \
-H:ClassInitialization@--language:js=com.oracle.truffle.js:build_time,com.oracle.js.parser:build_time,com.oracle.truffle.regex:build_time \
-H:ClassInitialization@--language:js=com.ibm.icu:run_time \
-H:ReflectionConfigurationResources@--language:js=com/oracle/truffle/js/runtime/resources/reflect-config.json \
-H:ResourceConfigurationResources@--language:js=com/oracle/truffle/js/runtime/resources/resource-config.json \
-H:+DumpTargetInfo \
'-H:Class@manifest from file:///Users/phs/github/trivadis/plsql-formatter-settings/standalone/target/tvdformat.jar=com.trivadis.plsql.formatter.TvdFormat' \
'-H:Name@manifest from file:///Users/phs/github/trivadis/plsql-formatter-settings/standalone/target/tvdformat.jar=tvdformat' \
'-H:Features@jar:file:///Users/phs/github/trivadis/plsql-formatter-settings/standalone/target/lib/graal-sdk-21.2.0.jar!/META-INF/native-image/org.graalvm.home/native-image.properties=org.graalvm.home.HomeFinderFeature' \
'-H:ClassInitialization@jar:file:///Users/phs/github/trivadis/plsql-formatter-settings/standalone/target/lib/graal-sdk-21.2.0.jar!/META-INF/native-image/org.graalvm.polyglot/native-image.properties=org.graalvm.polyglot:build_time' \
-H:FallbackThreshold=0 \
-H:CLibraryPath=/Users/phs/graalvm/graalvm-ce-java11-21.2.0/Contents/Home/lib/svm/clibraries/darwin-amd64
]
[tvdformat:43649]    classlist:   2,859.09 ms,  0.96 GB
[tvdformat:43649]        (cap):   3,634.37 ms,  0.96 GB
[tvdformat:43649]        setup:   5,640.33 ms,  0.96 GB
# Building image for target platform: org.graalvm.nativeimage.Platform$DARWIN_AMD64
# Using native toolchain:
#   Name: LLVM (clang)
#   Vendor: apple
#   Version: 12.0.5
#   Target architecture: x86_64
#   Path: /usr/bin/cc
# Using CLibrary: com.oracle.svm.core.c.libc.NoLibC
[tvdformat:43649]     (clinit):   1,393.59 ms,  5.93 GB
# Static libraries:
#   ../../../../../graalvm/graalvm-ce-java11-21.2.0/Contents/Home/lib/svm/clibraries/darwin-amd64/liblibchelper.a
#   ../../../../../graalvm/graalvm-ce-java11-21.2.0/Contents/Home/lib/static/darwin-amd64/libnet.a
#   ../../../../../graalvm/graalvm-ce-java11-21.2.0/Contents/Home/lib/svm/clibraries/darwin-amd64/libdarwin.a
#   ../../../../../graalvm/graalvm-ce-java11-21.2.0/Contents/Home/lib/static/darwin-amd64/libextnet.a
#   ../../../../../graalvm/graalvm-ce-java11-21.2.0/Contents/Home/lib/static/darwin-amd64/libnio.a
#   ../../../../../graalvm/graalvm-ce-java11-21.2.0/Contents/Home/lib/static/darwin-amd64/libjava.a
#   ../../../../../graalvm/graalvm-ce-java11-21.2.0/Contents/Home/lib/static/darwin-amd64/libfdlibm.a
#   ../../../../../graalvm/graalvm-ce-java11-21.2.0/Contents/Home/lib/static/darwin-amd64/libzip.a
#   ../../../../../graalvm/graalvm-ce-java11-21.2.0/Contents/Home/lib/svm/clibraries/darwin-amd64/libjvm.a
# Other libraries: z,-framework Foundation,pthread,dl
[tvdformat:43649]   (typeflow):  38,160.59 ms,  5.93 GB
[tvdformat:43649]    (objects):  35,159.06 ms,  5.93 GB
[tvdformat:43649]   (features):  11,782.33 ms,  5.93 GB
[tvdformat:43649]     analysis:  89,741.68 ms,  5.93 GB
[tvdformat:43649]     universe:   2,187.71 ms,  5.93 GB
11121 method(s) included for runtime compilation
[tvdformat:43649]      (parse):   9,879.23 ms,  5.94 GB
[tvdformat:43649]     (inline):  15,509.49 ms,  6.32 GB
[tvdformat:43649]    (compile):  63,293.02 ms,  7.27 GB
[tvdformat:43649]      compile:  95,159.01 ms,  7.27 GB
[tvdformat:43649]        image:  66,868.80 ms,  6.42 GB
[tvdformat:43649]        write:   4,296.27 ms,  6.42 GB
[tvdformat:43649]      [total]: 269,384.45 ms,  6.42 GB
# Printing build artifacts to: /Users/phs/github/trivadis/plsql-formatter-settings/standalone/target/tvdformat.build_artifacts.txt
```

And here's the output when running the created native image `./tvdformat`:

```
Exception in thread "main" javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: TypeError: Access to host class java.lang.String is not allowed or does not exist.
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.toScriptException(GraalJSScriptEngine.java:483)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:460)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:400)
	at com.trivadis.plsql.formatter.TvdFormat.run(TvdFormat.java:40)
	at com.trivadis.plsql.formatter.TvdFormat.main(TvdFormat.java:48)
Caused by: org.graalvm.polyglot.PolyglotException: TypeError: Access to host class java.lang.String is not allowed or does not exist.
	at <js>.:program(<eval>:19)
	at org.graalvm.polyglot.Context.eval(Context.java:375)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:458)
	... 3 more
```

**Comment by rodrigar-mx** [comment]
Hi @PhilippSalvisberg. I will help you solving this issue. Let me take a closer look to it and reproduce it. Any updates or questions I will let you know.

**Comment by rodrigar-mx** [comment]
Hi @PhilippSalvisberg the configuation of the script engine is correct. Indeed, only the lines
` .option("js.nashorn-compat", "true")
  .allowAllAccess(true)`
should be enough because _allowAllAccess_ permits everything else.

The real problem is that when you build a native image and you want to access Java code from a guest language you require java reflection (see [here](https://www.graalvm.org/reference-manual/embed-languages/#configuring-native-host-reflection)). You can configure it manually via a json file (see [here](https://www.graalvm.org/reference-manual/native-image/Reflection/#manual-configuration)), and link it with the `-H:ReflectionConfigurationFiles=/path/to/reflectconfig` option.

Your .json file would start like this
`[
{ "name": "java.lang.String", "allPublicMethods": true},
{ "name": "java.util.Arrays", "allPublicMethods": true},
...
]`

Please try it out, and let me know if any problem presented.

**Comment by PhilippSalvisberg** [comment]
Thank you @rodrigar-mx. 

This solved this issue regarding not accessible Java classes. Calling the native image without parameters produces the expected output.

Now I have other errors when running the native image with some parameters (works with `--force-fallback`). Here's an example error stack:

```
Exception in thread "main" javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: TypeError: path.startsWith is not a function
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.toScriptException(GraalJSScriptEngine.java:483)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:460)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:400)
	at com.trivadis.plsql.formatter.TvdFormat.run(TvdFormat.java:34)
	at com.trivadis.plsql.formatter.TvdFormat.main(TvdFormat.java:42)
Caused by: org.graalvm.polyglot.PolyglotException: TypeError: path.startsWith is not a function
	at <js>.getCdPath(<eval>:178)
	at <js>.processAndValidateArgs(<eval>:221)
	at <js>.run(<eval>:442)
	at <js>.:program(<eval>:520)
	at org.graalvm.polyglot.Context.eval(Context.java:375)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:458)
	... 3 more
```

`path` is a Java String and in the reflection configuration file I've defined

```
...
  {
    "name" : "java.lang.String",
    "allDeclaredConstructors" : true,
    "allDeclaredMethods" : true,
    "allDeclaredClasses" : true
  },
...
```

So the method `startWith` should be accessible. I guess I have to study the documentation a bit more...

However, the original issues is solved and therefore I close this issue. Thanks again.

**Comment by rodrigar-mx** [comment]
If you have any trouble with the configuration files you can assist yourself by using the tracing agent (see [here](https://medium.com/graalvm/introducing-the-tracing-agent-simplifying-graalvm-native-image-configuration-c3b56c486271) and [here](https://www.graalvm.org/reference-manual/native-image/Agent/)). Nevertheless, `startsWith` should be accessible. I will look at it. Try using meanwhile `substring` and the equal operator. If required, feel free to either reopen this issue or open a new one.

**Comment by PhilippSalvisberg** [comment]
Thanks. I changed the the JavaScript code and got rid of `startsWith`, `endWith` and similar. I understand that it is necessary to provide the information which classes are used dynamically. However, I'm surprised that it is necessary to change the code to make to produce to avoid runtime errors in the native image.

I've opened another issue #3642 where I'm stuck.
