### ISSUE TITLE
[native-image] NullPointerException in compiler when compiling app in 21.2.0

### ISSUE THREAD

**Issue by dzou** [oracle/graal#3629]
**Describe the issue**

When compiling native-image for the provided [sample app](https://github.com/dzou/graalvm-null-repro) (see reproduction instructions below), I get the error below.
**Note:** This error only occurs for GraalVM native image 21.2.0 and 21.1.0, **but this works successfully on 21.0.0**.

```
Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.eclipse.jetty.util.TypeUtil.<clinit>() 
Parsing context: <no parsing context available> 

	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:331)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureTypeFlowCreated(MethodTypeFlow.java:302)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
	at com.oracle.graal.pointsto.BigBang$1.run(BigBang.java:421)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.graalvm.compiler.graph.GraalGraphError: java.lang.NullPointerException
	at node: 1281|+ { nodeSourcePosition=at org.eclipse.jetty.util.TypeUtil.<clinit>(TypeUtil.java:192) [bci: 996], stamp=i32,  }
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.tryCanonicalize(CanonicalizerPhase.java:413)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.processNode(CanonicalizerPhase.java:346)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.processWorkSet(CanonicalizerPhase.java:323)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.run(CanonicalizerPhase.java:282)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase.run(CanonicalizerPhase.java:192)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase.run(CanonicalizerPhase.java:73)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:184)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:304)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:313)
	... 10 more
Caused by: java.lang.NullPointerException
	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.calc.AddNode.canonical(AddNode.java:98)
	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.calc.AddNode.canonical(AddNode.java:189)
	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.calc.AddNode.canonical(AddNode.java:47)
	at jdk.internal.vm.compiler/org.graalvm.compiler.graph.spi.Canonicalizable$Binary.canonical(Canonicalizable.java:137)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.tryCanonicalize(CanonicalizerPhase.java:408)
	... 20 more
```

**Steps to reproduce the issue**
1. `git clone https://github.com/dzou/graalvm-null-repro.git`
2. `cd graalvm-null-repro`
3. `mvn package -Pnative`

You'll see error in version 21.1.0 or 21.2.0. The sample works for version `21.0.0` or `21.0.0.2`.

**Describe GraalVM and your environment:**
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)

Linux OS

**Comment by mcraj017** [comment]
@dzou thanks for reporting the issue, we will check it out and get back to you

**Comment by mcraj017** [comment]
@dzou while trying reproducer, I got below error:
```
google-cloud-graalvm-samples/graalvm-samples-client-library/cloud-functions-sample$ /home/munish/github/3629/apache-maven-3.8.1/bin/mvn package -Pnative
[INFO] Scanning for projects...
[INFO]
[INFO] --------------< com.google.cloud:cloud-functions-sample >---------------
[INFO] Building cloud-functions-sample 0.5.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.google.cloud:google-cloud-graalvm-support:jar:0.5.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.922 s
[INFO] Finished at: 2021-07-30T14:35:10+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project cloud-functions-sample: Could not resolve dependencies for project com.google.cloud:cloud-functions-sample:jar:0.5.0-SNAPSHOT: Could not find artifact com.google.cloud:google-cloud-graalvm-support:jar:0.5.0-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

```

**Comment by dzou** [comment]
@mcraj017 -- Sorry about that. I created a new reproducer which should be simpler: https://github.com/dzou/graalvm-null-repro

You just need to run `mvn package -Pnative` to start the graalvm compile; no complex dependencies in the project anymore.

**Comment by mcraj017** [comment]
@dzou thank you, I will check it out

**Comment by mcraj017** [comment]
@dzou I have raised this issue with the Dev team

**Comment by dzou** [comment]
Thanks!
