### ISSUE TITLE
native-image, UX, JFR, -XX:StartFlightRecording flags/arguments units are not aligned with HotSpot convention

### ISSUE THREAD

**Issue by Karm** [oracle/graal#3638]
e.g. maxsize is parsed as a plain Long, see: [JfrManager.java](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.jfr/src/com/oracle/svm/jfr/JfrManager.java#L107) whereas in HotSpot, one can use units, see [jfrOptionSet.cpp](https://github.com/openjdk/jdk11u-dev/blob/f700d37d2b3d8c23d50defc19853c68bb60027ab/src/hotspot/share/jfr/recorder/service/jfrOptionSet.cpp#L380).

## How to reproduce:
1. Build
```
$ export JAVA_HOME=/home/karm/X/JDKs/graalvm-ce-java11-21.2.0/;export PATH=${JAVA_HOME}/bin:${PATH}
$ native-image --version
GraalVM 21.2.0 Java 11 CE (Java Version 11.0.12+6-jvmci-21.2-b08)
$ cat Main.java
public class Main {
    public static void main(String... args) {
        System.out.println("Meh.");
    }
}
$ javac Main.java
$ native-image -H:+AllowVMInspection Main
```
2. Run setting `maxsize` with plain number of bytes. Works fine. :heavy_check_mark: 
```
$ java -XX:+FlightRecorder -XX:StartFlightRecording=maxsize=10485760,filename=flight-java.jfr Main
Started recording 1.

Use jcmd 273484 JFR.dump name=1 to copy recording data to file.
Meh.

$ ./main -XX:+FlightRecorder -XX:StartFlightRecording=maxsize=10485760,filename=flight-native.jfr
Meh.
```
2. Try to use units with `maxsize` attribute. Crashes with native image run :x: 
```
$ java -XX:+FlightRecorder -XX:StartFlightRecording=maxsize=10M,filename=flight-java.jfr Main
Started recording 1.

Use jcmd 273654 JFR.dump name=1 to copy recording data to file.
Meh.

$ ./main -XX:+FlightRecorder -XX:StartFlightRecording=maxsize=10M,filename=flight-native.jfr
Exception in thread "main" com.oracle.svm.core.util.UserError$UserException: Could not parse JFR argument 'maxsize=10M'. Expected a number.
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.jfr.JfrManager.parseLong(JfrManager.java:171)
	at com.oracle.svm.jfr.JfrManager.initRecording(JfrManager.java:107)
	at com.oracle.svm.jfr.JfrManager.setup(JfrManager.java:72)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
```

TODO: Align options parsing flows so as users can use the same with both setups.

## OS
```
Linux  4.18.0-240.22.1.el8_3.x86_64 (Centos 8 Stream)
```

**Comment by mcraj017** [comment]
@Karm thanks for the contribution, we will check it out and get back to you
