### ISSUE TITLE
PolyglotException: TypeError: invokeMember (collect) on java.util.stream.ReferencePipeline$Head@4c320659 failed due to: Unknown identifier: collect

### ISSUE THREAD

**Issue by PhilippSalvisberg** [oracle/graal#3642]
**Describe the issue**
I have configured the Java class `java.util.stream.ReferencePipeline$Head` in the `reflection-config.json` as follows:

```json
   {
    "name" : "java.util.stream.ReferencePipeline$Head",
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true,
    "allDeclaredFields": true,
    "allDeclaredClasses": true,
    "allPublicConstructors": true,
    "allPublicMethods": true,
    "allPublicFields": true,
    "allPublicClasses": true
  }
```

but still get a `PolyglotException` when running the native image. Here's the full error stack:

```
Exception in thread "main" javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: TypeError: invokeMember (collect) on java.util.stream.ReferencePipeline$Head@13fb6311 failed due to: Unknown identifier: collect
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.toScriptException(GraalJSScriptEngine.java:483)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:460)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:426)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at Demo.main(Demo.java:22)
Caused by: org.graalvm.polyglot.PolyglotException: TypeError: invokeMember (collect) on java.util.stream.ReferencePipeline$Head@13fb6311 failed due to: Unknown identifier: collect
	at <js>.:program(<eval>:2)
	at org.graalvm.polyglot.Context.eval(Context.java:375)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:458)
	... 3 more
```

Any idea what I have to configure to get rid of this exception?

To replicate the issue I created a small demo program in a [Gist](https://gist.github.com/PhilippSalvisberg/282d0b88f2cd907f90d28ff5e25cb5a0),

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. `git clone https://gist.github.com/PhilippSalvisberg/282d0b88f2cd907f90d28ff5e25cb5a0`
2. `cd 282d0b88f2cd907f90d28ff5e25cb5a0`
3. `javac Demo.java`
4. `java Demo` to produce the demo output without runtime exception
5. `$JAVA_HOME/bin/native-image -H:ReflectionConfigurationFiles=reflection-config.json --language:js --no-fallback Demo`
6. `./demo` to produce the runtime exception

**Describe GraalVM and your environment:**
 - GraalVM version: **GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08)**
 - JDK major version: **11**
 - OS: **macOS Bis Sur 11.3.1**
 - Architecture: **darwin-amd64**

**More details**
I tried to run `java -agentlib:native-image-agent=config-output-dir=config Demo` but the resulting `config/reflect-config.json` contains only an empty array.

**Comment by rodrigar-mx** [comment]
Hi @PhilippSalvisberg. Thanks for reporting the issue. I will take a closer look to it and get back to you.

**Comment by rodrigar-mx** [comment]
@PhilippSalvisberg please try adding the following lines to your `reflection-config.json` file
```
{
    "name" : "java.util.stream.Stream",
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true,
    "allDeclaredFields": true,
    "allDeclaredClasses": true,
    "allPublicConstructors": true,
    "allPublicMethods": true,
    "allPublicFields": true,
    "allPublicClasses": true
}
```

**Comment by PhilippSalvisberg** [comment]
Thanks @rodrigar-mx. This did the trick. 

I still do not understand the `Unknown identifier: collect` part of the error message. `collect` is implemented in `java.util.stream.ReferencePipeline`. So, I do not understand why the interface `java.util.stream.Stream` is required in this case.

Anyway, problem solved. Thank you for your fast help.
