### ISSUE TITLE
Native Image can't find some symbols

### ISSUE THREAD

**Issue by qingyiwebt** [oracle/graal#3675]
**Describe the issue**
I heard about this tool last night and saw the improvement in execution speed. So today I'm going to use native-image to compile Minecraft.
But ran into an error that I couldn't fix. It's just for fun, but I still hope it will eventually compile a binary.
When linking using Microsoft's toolchain, the linker could not find several symbols.

**Steps to reproduce the issue**
I didn't compile native-image or GraalVM myself, I used the binaries on Github Release.
I downloaded GraalVM from https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.2.0
1. Get Minecraft startup parameters from a software called HMCL.
2. Take the -cp parameter out of the startup parameters and put it in the native-image parameter separately
3. Add the main Minecraft class (net.minecraft.launchwrapper.Launch) after the native-image
4. Execute native-image
5. Get "several unresolved symbols" error when calling msvc toolchain in native-image

**Describe GraalVM and your environment:**
 - GraalVM version: **GraalVM Community Edition 21.2.0**
 - JDK major version: **OpenJDK version "16.0.2" 2021-07-20**
 - OS: **Windows 11**
 - Architecture: **AMD64**

**More details**
```
Executing [
'H:\Softwares\GraalVM\bin\java.exe' \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
--add-exports=java.base/com.sun.crypto.provider=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.access.foreign=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.event=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.loader=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.logger=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.misc=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.module=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.org.xml.sax.helpers=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.perf=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.ref=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.util.xml.impl=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.util.xml=ALL-UNNAMED \
--add-exports=java.base/sun.invoke.util=ALL-UNNAMED \
--add-exports=java.base/sun.nio.ch=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.annotation=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.reflectiveObjects=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.repository=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.tree=ALL-UNNAMED \
--add-exports=java.base/sun.security.jca=ALL-UNNAMED \
--add-exports=java.base/sun.security.provider=ALL-UNNAMED \
--add-exports=java.base/sun.security.util=ALL-UNNAMED \
--add-exports=java.base/sun.text.spi=ALL-UNNAMED \
--add-exports=java.base/sun.util.calendar=ALL-UNNAMED \
--add-exports=java.base/sun.util.locale.provider=ALL-UNNAMED \
--add-exports=java.base/sun.util.resources=ALL-UNNAMED \
--add-exports=java.xml.crypto/org.jcp.xml.dsig.internal.dom=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.site=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.stack=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.common=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.runtime=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.services=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.events=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal.consumer=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal.handlers=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal.jfc=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal=ALL-UNNAMED \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx6834415200 \
-Duser.country=US \
-Duser.language=en \
-Djava.awt.headless=true \
-Dorg.graalvm.version=21.2.0 \
-Dorg.graalvm.config=CE \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
--module-path \
'H:\Softwares\GraalVM\lib\truffle\truffle-api.jar' \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
'-javaagent:H:\Softwares\GraalVM\lib\svm\builder\svm.jar' \
-cp \
'H:\Softwares\GraalVM\lib\svm\builder\objectfile.jar;H:\Softwares\GraalVM\lib\svm\builder\pointsto.jar;H:\Softwares\GraalVM\lib\svm\builder\svm.jar' \
'com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus' \
-imagecp \
'D:\.su_packour\.minecraft\libraries\optifine\OptiFine\1.11.2_HD_U_G5\OptiFine-1.11.2_HD_U_G5.jar;D:\.su_packour\.minecraft\libraries\optifine\launchwrapper-of\2.2\launchwrapper-of-2.2.jar;D:\.su_packour\.minecraft\libraries\com\mojang\netty\1.7.7\netty-1.7.7.jar;D:\.su_packour\.minecraft\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar;D:\.su_packour\.minecraft\libraries\net\java\dev\jna\jna\3.4.0\jna-3.4.0.jar;D:\.su_packour\.minecraft\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar;D:\.su_packour\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;D:\.su_packour\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar;D:\.su_packour\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar;D:\.su_packour\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar;D:\.su_packour\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar;D:\.su_packour\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar;D:\.su_packour\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar;D:\.su_packour\.minecraft\libraries\io\netty\netty-all\4.0.23.Final\netty-all-4.0.23.Final.jar;D:\.su_packour\.minecraft\libraries\com\google\guava\guava\17.0\guava-17.0.jar;D:\.su_packour\.minecraft\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar;D:\.su_packour\.minecraft\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar;D:\.su_packour\.minecraft\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar;D:\.su_packour\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;D:\.su_packour\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;D:\.su_packour\.minecraft\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar;D:\.su_packour\.minecraft\libraries\com\mojang\authlib\1.5.24\authlib-1.5.24.jar;D:\.su_packour\.minecraft\libraries\com\mojang\realms\1.10.16\realms-1.10.16.jar;D:\.su_packour\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;D:\.su_packour\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;D:\.su_packour\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;D:\.su_packour\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;D:\.su_packour\.minecraft\libraries\it\unimi\dsi\fastutil\7.0.12_mojang\fastutil-7.0.12_mojang.jar;D:\.su_packour\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar;D:\.su_packour\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar;D:\.su_packour\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.4-nightly-20150209\lwjgl-2.9.4-nightly-20150209.jar;D:\.su_packour\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.4-nightly-20150209\lwjgl_util-2.9.4-nightly-20150209.jar;D:\.su_packour\.minecraft\versions\1.11.2.114514\1.11.2.114514.jar;H:\Softwares\GraalVM\lib\svm\library-support.jar' \
'-H:Path=D:\.su_packour\.minecraft\versions\1.11.2.114514' \
-H:+DumpTargetInfo \
'-H:CLibraryPath=H:\Softwares\GraalVM\lib\svm\clibraries\windows-amd64' \
'-H:Class@explicit main-class=net.minecraft.launchwrapper.Launch' \
'-H:Name@main-class lower case as image name=net.minecraft.launchwrapper.launch'
]
[net.minecraft.launchwrapper.launch:18508]    classlist:   9,870.27 ms,  0.96 GB
[net.minecraft.launchwrapper.launch:18508]        (cap):     746.18 ms,  0.96 GB
[net.minecraft.launchwrapper.launch:18508]        setup:   1,808.66 ms,  0.96 GB
Error: Error compiling query code (in C:\Users\qingy\AppData\Local\Temp\SVM-3228809842000344739\AMD64LibCHelperDirectives.c). Compiler command ''C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30401\bin\Hostx86\x64\cl.exe' /WX /W4 /wd4244 /wd4245 /wd4800 /wd4804 /wd4214 '/FeC:\Users\qingy\AppData\Local\Temp\SVM-3228809842000344739\AMD64LibCHelperDirectives.exe' 'C:\Users\qingy\AppData\Local\Temp\SVM-3228809842000344739\AMD64LibCHelperDirectives.c'' output included error: [AMD64LibCHelperDirectives.c, Microsoft (R) Incremental Linker Version 14.30.30401.0, Copyright (C) Microsoft Corporation.  All rights reserved., , /out:C:\Users\qingy\AppData\Local\Temp\SVM-3228809842000344739\AMD64LibCHelperDirectives.exe , AMD64LibCHelperDirectives.obj , AMD64LibCHelperDirectives.obj : error LNK2019: unresolved external symbol __acrt_iob_func referenced in function printf, AMD64LibCHelperDirectives.obj : error LNK2019: unresolved external symbol __stdio_common_vfprintf referenced in function _vfprintf_l, AMD64LibCHelperDirectives.obj : error LNK2019: unresolved external symbol memset referenced in function AMD64LibCHelperDirectives, AMD64LibCHelperDirectives.obj : error LNK2001: unresolved external symbol __GSHandlerCheck, AMD64LibCHelperDirectives.obj : error LNK2019: unresolved external symbol __security_check_cookie referenced in function AMD64LibCHelperDirectives, AMD64LibCHelperDirectives.obj : error LNK2019: unresolved external symbol __security_cookie referenced in function AMD64LibCHelperDirectives, LINK : error LNK2001: unresolved external symbol mainCRTStartup, C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30401\lib\x86\LIBCMT.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64', C:\Users\qingy\AppData\Local\Temp\SVM-3228809842000344739\AMD64LibCHelperDirectives.exe : fatal error LNK1120: 7 unresolved externals]
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
[net.minecraft.launchwrapper.launch:18508]      [total]:  11,850.51 ms,  0.96 GB
# Printing build artifacts to: D:\.su_packour\.minecraft\versions\1.11.2.114514\net.minecraft.launchwrapper.launch.build_artifacts.txt
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1916)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1584)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1545)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1532)
```

**Comment by kkriske** [comment]
One thing that stood out to me in the error:
```
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30401\lib\x86\LIBCMT.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
```
Are you running in a 64 bit Native Tools Command Prompt? 32 bit won't do.

It would probably also help if you add `-H:+TraceNativeToolUsage` to the native-image command, and update the log output. That'll give more information about the native stuff that's going on.

**Comment by mcraj017** [comment]
@qingyiwebt does suggestion from @kkriske solves your issue?

**Comment by qingyiwebt** [comment]
Finally I found the "x86_x64 Cross Tools Command Prompt for VS 2022 Preview" and successfully used the "Native Image" tool
