### ISSUE TITLE
Netbeans Debug Test File: Cannot step through the fast thread local with the debugger without JVMCI API fallback methods

### ISSUE THREAD

**Issue by kokhoor** [oracle/graal#3676]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: 21.3-dev
 - CE or EE: CE
 - JDK version: 11
 - OS and OS Version: Windows 10
 - Architecture: amd64
 - The output of `java -Xinternalversion`: OpenJDK 64-Bit Server VM (11.0.12+5-jvmci-21.3-b01) for windows-amd64 JRE (11.0.12+5-jvmci-21.3-b01), built on Jul 16 2021 08:05:46 by "" with unknown MS VC++:1916
```
### Cause: java.lang.UnsupportedOperationException: Cannot step through the fast thread local with the debugger without JVMCI API fallback methods. Make sure the JVMCI version is up-to-date or switch to a runtime without Truffle compilation for debugging to resolve this. Use -Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime to switch to a runtime without compilation. Remember to remove this option again after debugging.
```
**Describe the issue**
When I am debugging with Netbeans, I received this error when clicking on Step Over, therefore I added: -Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime
However, the error still happens

**Code snippet or code repository that reproduces the issue**
It happens anywhere as long as you Step Over on any lines during debug

</details>

**Comment by rodrigar-mx** [comment]
Thank you for reporting this issue. We will take a closer look into it and get back to you. I would suggest you using VSCode where you can install the GraalVM extension (click [here](https://marketplace.visualstudio.com/items?itemName=oracle-labs-graalvm.graalvm)).

**Comment by rodrigar-mx** [comment]
@kokhoor I tried debugging with NetBeans12 and graalvm-21.3-dev on Windows 10 and had no issues. Which kind of application are you trying to debug? A simple java app or one with polyglot features? Have you tried other IDEs and see if the problem persists? Could you try adding `-XX:-UseJVMCICompiler` to deactivate the JVMCI and share the results.

**Comment by kokhoor** [comment]
@rodrigar-mx I am debugging a simple application (Using Netbeans 'Debug Test File' feature) that basically instantiate GraalVM javascript engine, run js code which in turn calls Java functions (which can potentially further call javascript). Netbeans IDE version 12.3, Runtime: OpenJDK Runtime Environment 12.0.1+12. Do I have to switch to Graal-dev as the Netbeans Runtime too?

I have added -XX:-UseJVMCICompiler but the result is still the same. If I don't step over / step into, just place another breakpoint and continue running, then it works, but if I click on any of the Step Over, etc. buttons, the error will appear.

org.graalvm.polyglot.PolyglotException: java.lang.UnsupportedOperationException: Cannot step through the fast thread local with the debugger without JVMCI API fallback methods. Make sure the JVMCI version is up-to-date or switch to a runtime without Truffle compilation for debugging to resolve this. Use -Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime to switch to a runtime without compilation. Remember to remove this option again after debugging.

**Comment by rodrigar-mx** [comment]
Could you please share a reproducer of the piece of code you are unable to debug.

**Comment by kokhoor** [comment]
It is actually a public project in Github:
https://github.com/kokhoor/SimplyScript-playground

Hope you can load the project in NetBeans. I am in the midst of cleaning it up to open-source it, but at the moment is just fragment of codes.

then use the 'Debug Test File' feature in netbeans to debug the my.com.solutionx.simplyscript.ScriptServiceTest file in the test (not the main src), breakpoint at line 52.

When I click Step Over, I end up in:
jdk.internal.reflect.NativeMethodAccessorImpl at the line as per attached image
<img width="746" alt="DebugStepOverFailed" src="https://user-images.githubusercontent.com/2721145/130717835-3225b062-b33e-4da8-99a3-7a09fec41668.png">

The output:
testScriptEngine(my.com.solutionx.simplyscript.ScriptServiceTest)  Time elapsed: 29.293 sec  <<< ERROR!
java.lang.UnsupportedOperationException: Cannot step through the fast thread local with the debugger without JVMCI API fallback methods. Make sure the JVMCI version is up-to-date or switch to a runtime without Truffle compilation for debugging to resolve this. Use -Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime to switch to a runtime without compilation. Remember to remove this option again after debugging.
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.failDebugStepping(HotSpotFastThreadLocal.java:184)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReferenceNoFallback(HotSpotFastThreadLocal.java:118)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReference(HotSpotFastThreadLocal.java:92)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.get(HotSpotFastThreadLocal.java:71)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReferenceNoFallback(HotSpotFastThreadLocal.java:122)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReference(HotSpotFastThreadLocal.java:92)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.get(HotSpotFastThreadLocal.java:71)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReferenceNoFallback(HotSpotFastThreadLocal.java:122)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReference(HotSpotFastThreadLocal.java:92)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.get(HotSpotFastThreadLocal.java:71)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReferenceNoFallback(HotSpotFastThreadLocal.java:122)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReference(HotSpotFastThreadLocal.java:92)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.get(HotSpotFastThreadLocal.java:71)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReferenceNoFallback(HotSpotFastThreadLocal.java:122)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReference(HotSpotFastThreadLocal.java:92)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.get(HotSpotFastThreadLocal.java:71)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReferenceNoFallback(HotSpotFastThreadLocal.java:122)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReference(HotSpotFastThreadLocal.java:92)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.get(HotSpotFastThreadLocal.java:71)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReferenceNoFallback(HotSpotFastThreadLocal.java:122)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReference(HotSpotFastThreadLocal.java:92)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.get(HotSpotFastThreadLocal.java:71)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReferenceNoFallback(HotSpotFastThreadLocal.java:122)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReference(HotSpotFastThreadLocal.java:92)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.get(HotSpotFastThreadLocal.java:71)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReferenceNoFallback(HotSpotFastThreadLocal.java:122)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReference(HotSpotFastThreadLocal.java:92)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.get(HotSpotFastThreadLocal.java:71)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReferenceNoFallback(HotSpotFastThreadLocal.java:122)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReference(HotSpotFastThreadLocal.java:92)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.get(HotSpotFastThreadLocal.java:71)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReferenceNoFallback(HotSpotFastThreadLocal.java:122)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReference(HotSpotFastThreadLocal.java:92)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.get(HotSpotFastThreadLocal.java:71)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReferenceNoFallback(HotSpotFastThreadLocal.java:122)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReference(HotSpotFastThreadLocal.java:92)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.get(HotSpotFastThreadLocal.java:71)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalFastThreadLocal.fastGet(GraalFastThreadLocal.java:64)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotFastThreadLocals.getContext(PolyglotFastThreadLocals.java:168)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.EngineAccessor$EngineImpl.getCurrentPolyglotEngine(EngineAccessor.java:462)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentAccessor$InstrumentImpl.validEngine(InstrumentAccessor.java:350)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentAccessor$InstrumentImpl.onFirstExecution(InstrumentAccessor.java:194)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.initialize(OptimizedCallTarget.java:694)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.ensureInitialized(OptimizedCallTarget.java:680)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.interpreterCall(OptimizedCallTarget.java:564)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:551)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:538)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalRuntimeSupport.callProfiled(GraalRuntimeSupport.java:144)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue.newInstance(PolyglotValueDispatch.java:2360)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.newInstance(Value.java:882)
	at my.com.solutionx.simplyscript.graal.ScriptEngine.action(ScriptEngine.java:128)
	at my.com.solutionx.simplyscript.ScriptService.action(ScriptService.java:226)
	at my.com.solutionx.simplyscript.ScriptServiceTest.testScriptEngine(ScriptServiceTest.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by kokhoor** [comment]
I have tested Graal 21.2 and the step over and step into works perfectly, and it even steps into js files.
Hopefully this issue will be resolved when Graal 21.3 is released. Thanks!

**Comment by chumer** [comment]
On Stock JDK this issue will unfortunately persist until JDK 11 Update 13 comes out.
You can also remove Graal from the upgrade module path to resolve this.
But best experience you will get with using a GraalVM JDK.

**Comment by kokhoor** [comment]
I was under the impression that I am using the GraalVM JDK. Will check further. Thanks.

**Comment by chumer** [comment]
@kokhoor yes. you actually discovered a problem where some changes did not arrive where they should in our backporting process, exactly and only in the version you report. We will fix this asap.

**Comment by kokhoor** [comment]
Thanks @chumer 
I just checked the java environment, it is indeed graalvm JDK. The output from my echo statement:  D:\dev\java\test\graalvm-ce-java11-21.3.0-dev\bin\java.exe

By the way, really thanks for prompt response. Thanks.
