### ISSUE TITLE
[native-image] JavaFX compiled application throws a fatal exception on startup

### ISSUE THREAD

**Issue by BullyWiiPlaza** [oracle/graal#3677]
**Describe the issue**
After compiling a simple JavaFX application, the EXE crashes upon starting.

**Steps to reproduce the issue**
1. Build an executable JAR file including native image tracing configs in the META-INF
2. Compile it to native code with native-image -jar "Hello World.jar" --no-fallback --verbose
3. Run the resulting EXE from the command line
4. A startup exception occurs

**Describe GraalVM and your environment:**
 - GraalVM version: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.2.0/graalvm-ce-java11-windows-amd64-21.2.0.zip
 - JDK major version: **11**
 - OS: **Windows 10 64-bit**
 - Architecture: **AMD64**

**More details**
```
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.lang.Thread.run(Thread.java:829)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:567)
        at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
Caused by: java.lang.AssertionError: java.lang.ClassNotFoundException: javafx.scene.transform.Transform
        at com.sun.javafx.util.Utils.forceInit(Utils.java:858)
        at com.sun.javafx.scene.transform.TransformHelper.<clinit>(TransformHelper.java:42)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
        at javafx.scene.transform.Transform.<clinit>(Transform.java:77)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
        at java.lang.Class.ensureInitialized(DynamicHub.java:548)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:260)
        at javafx.scene.Node.<clinit>(Node.java:5855)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
        at java.lang.Class.ensureInitialized(DynamicHub.java:548)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:260)
        at java.lang.Class.ensureInitialized(DynamicHub.java:548)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:260)
        at java.lang.Class.ensureInitialized(DynamicHub.java:548)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:260)
        at java.lang.Class.ensureInitialized(DynamicHub.java:548)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:260)
        at java.lang.Class.ensureInitialized(DynamicHub.java:548)
        at java.lang.Class.newInstance(DynamicHub.java:904)
        at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1019)
        at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:754)
        at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2722)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2552)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3237)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3194)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3163)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3136)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3113)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3106)
        at PrimeNumberCalculator.start(PrimeNumberCalculator.java:22)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.security.AccessController.doPrivileged(AccessController.java:105)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_Runnable_2_0002erun_00028_00029V(JNIJavaCallWrappers.java:0)
        at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
        ... 3 more
Caused by: java.lang.ClassNotFoundException: javafx.scene.transform.Transform
        at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:71)
        at java.lang.Class.forName(DynamicHub.java:1319)
        at com.sun.javafx.util.Utils.forceInit(Utils.java:855)
        ... 45 more
```
Possibly related issue: https://github.com/oracle/graal/issues/3659

**Comment by mcraj017** [comment]
@BullyWiiPlaza please try GraalVM 21.3-dev
https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/21.3.0-dev-20210813_0049
and let us know the output

**Comment by chirontt** [comment]
@BullyWiiPlaza, JavaFX is a different animal from Swing. GraalVM native-image has supported JavaFX apps since version 20.3 at least, while Swing support was only added recently (21.0+ version).

JavaFX native image compilation requires some special handling in order for the resultant native image to work. Simply using the `native-image -jar ...` command usually produces non-working native image for JavaFX app, as you have reported. You need some extra tool to help in the compile.

Gluon team has developed some [Maven](https://github.com/gluonhq/gluonfx-maven-plugin) and [Gradle](https://github.com/gluonhq/gluonfx-gradle-plugin) plugins to assist in native compiling of JavaFX apps that you can try. I have used them to produce native images for JavaFX apps successfully in my projects. They have some [samples](https://github.com/gluonhq/gluon-samples) how to use their Maven plugin.

**Comment by mcraj017** [comment]
@BullyWiiPlaza can you please confirm, if the above solution worked for you or you still need assistance from us?

**Comment by mcraj017** [comment]
Closing this ticket as there is no activity in last one month
