### ISSUE TITLE
native image generation fails with unrecognized relocation (0x2a) in section `.text.JVM_FindLibraryEntry'

### ISSUE THREAD

**Issue by jaikiran** [oracle/graal#3678]
Using GraalVM community edition of both `21.1.0` and `21.2.0` to generate a native image fails with the following error:

> /usr/bin/ld: /home/me/tmp/graalvm-ce-java11-21.2.0/lib/svm/clibraries/linux-amd64/libjvm.a(JvmFuncs.o): unrecognized relocation (0x2a) in section `.text.JVM_FindLibraryEntry'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status

The complete log along with the native-image command which was used (through Quarkus application is as follows):

```
/home/me/tmp/graalvm-ce-java11-21.2.0/bin/native-image -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=cs -J-Duser.country=CZ -J-Dfile.encoding=UTF-8 -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -jar getting-started-1.0.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http -H:-UseServiceLoaderFeature -H:+StackTrace -H:-ParseOnce getting-started-1.0.0-SNAPSHOT-runner
[getting-started-1.0.0-SNAPSHOT-runner:27056]    classlist:   9 135,14 ms,  0,94 GB
[getting-started-1.0.0-SNAPSHOT-runner:27056]        (cap):   3 835,56 ms,  0,94 GB
[getting-started-1.0.0-SNAPSHOT-runner:27056]        setup:  56 434,35 ms,  0,94 GB
The bundle named: messages, has not been found. If the bundle is part of a module, verify the bundle name is a fully qualified class name. Otherwise verify the bundle path is accessible in the classpath.
23:49:42,973 INFO  [org.jbo.threads] JBoss Threads version 3.4.2.Final
[getting-started-1.0.0-SNAPSHOT-runner:27056]     (clinit):   1 473,91 ms,  3,81 GB
[getting-started-1.0.0-SNAPSHOT-runner:27056]   (typeflow):  33 183,17 ms,  3,81 GB
[getting-started-1.0.0-SNAPSHOT-runner:27056]    (objects):  48 779,03 ms,  3,81 GB
[getting-started-1.0.0-SNAPSHOT-runner:27056]   (features):   2 280,32 ms,  3,81 GB
[getting-started-1.0.0-SNAPSHOT-runner:27056]     analysis:  89 117,36 ms,  3,81 GB
[getting-started-1.0.0-SNAPSHOT-runner:27056]     universe:   4 184,06 ms,  3,81 GB
[getting-started-1.0.0-SNAPSHOT-runner:27056]      (parse):  15 621,18 ms,  4,97 GB
[getting-started-1.0.0-SNAPSHOT-runner:27056]     (inline):   8 414,03 ms,  5,21 GB
[getting-started-1.0.0-SNAPSHOT-runner:27056]    (compile):  34 001,71 ms,  5,37 GB
[getting-started-1.0.0-SNAPSHOT-runner:27056]      compile:  64 225,78 ms,  5,37 GB
[getting-started-1.0.0-SNAPSHOT-runner:27056]        image:  13 496,78 ms,  5,37 GB
[getting-started-1.0.0-SNAPSHOT-runner:27056]        write:   1 991,57 ms,  5,37 GB
Fatal error:java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1

Linker command executed:
/usr/bin/gcc -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-4800557360418190176/exported_symbols.list -Wl,--exclude-libs,ALL -Wl,-x -o /home/me/tmp/quarkus-quickstarts/getting-started/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/getting-started-1.0.0-SNAPSHOT-runner getting-started-1.0.0-SNAPSHOT-runner.o /home/me/tmp/graalvm-ce-java11-21.2.0/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/me/tmp/graalvm-ce-java11-21.2.0/lib/static/linux-amd64/glibc/libnet.a /home/me/tmp/graalvm-ce-java11-21.2.0/lib/static/linux-amd64/glibc/libextnet.a /home/me/tmp/graalvm-ce-java11-21.2.0/lib/static/linux-amd64/glibc/libnio.a /home/me/tmp/graalvm-ce-java11-21.2.0/lib/static/linux-amd64/glibc/libjava.a /home/me/tmp/graalvm-ce-java11-21.2.0/lib/static/linux-amd64/glibc/libfdlibm.a /home/me/tmp/graalvm-ce-java11-21.2.0/lib/static/linux-amd64/glibc/libsunec.a /home/me/tmp/graalvm-ce-java11-21.2.0/lib/static/linux-amd64/glibc/libzip.a /home/me/tmp/graalvm-ce-java11-21.2.0/lib/svm/clibraries/linux-amd64/libjvm.a -v -L/tmp/SVM-4800557360418190176 -L/home/me/tmp/graalvm-ce-java11-21.2.0/lib/static/linux-amd64/glibc -L/home/me/tmp/graalvm-ce-java11-21.2.0/lib/svm/clibraries/linux-amd64 -lstdc++ -lz -lpthread -ldl -lrt

Linker command output:
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) 
COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/:/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/:/usr/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/
LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-z' 'noexecstack' '-o' '/home/me/tmp/quarkus-quickstarts/getting-started/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/getting-started-1.0.0-SNAPSHOT-runner' '-v' '-L/tmp/SVM-4800557360418190176' '-L/home/me/tmp/graalvm-ce-java11-21.2.0/lib/static/linux-amd64/glibc' '-L/home/me/tmp/graalvm-ce-java11-21.2.0/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/libexec/gcc/x86_64-redhat-linux/4.8.5/collect2 --build-id --no-add-needed --eh-frame-hdr --hash-style=gnu -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o /home/me/tmp/quarkus-quickstarts/getting-started/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/getting-started-1.0.0-SNAPSHOT-runner -z noexecstack /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtbegin.o -L/tmp/SVM-4800557360418190176 -L/home/me/tmp/graalvm-ce-java11-21.2.0/lib/static/linux-amd64/glibc -L/home/me/tmp/graalvm-ce-java11-21.2.0/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../.. --gc-sections --dynamic-list /tmp/SVM-4800557360418190176/exported_symbols.list --exclude-libs ALL -x getting-started-1.0.0-SNAPSHOT-runner.o /home/me/tmp/graalvm-ce-java11-21.2.0/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/me/tmp/graalvm-ce-java11-21.2.0/lib/static/linux-amd64/glibc/libnet.a /home/me/tmp/graalvm-ce-java11-21.2.0/lib/static/linux-amd64/glibc/libextnet.a /home/me/tmp/graalvm-ce-java11-21.2.0/lib/static/linux-amd64/glibc/libnio.a /home/me/tmp/graalvm-ce-java11-21.2.0/lib/static/linux-amd64/glibc/libjava.a /home/me/tmp/graalvm-ce-java11-21.2.0/lib/static/linux-amd64/glibc/libfdlibm.a /home/me/tmp/graalvm-ce-java11-21.2.0/lib/static/linux-amd64/glibc/libsunec.a /home/me/tmp/graalvm-ce-java11-21.2.0/lib/static/linux-amd64/glibc/libzip.a /home/me/tmp/graalvm-ce-java11-21.2.0/lib/svm/clibraries/linux-amd64/libjvm.a -lstdc++ -lz -lpthread -ldl -lrt -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtend.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crtn.o
/usr/bin/ld: /home/me/tmp/graalvm-ce-java11-21.2.0/lib/svm/clibraries/linux-amd64/libjvm.a(JvmFuncs.o): unrecognized relocation (0x2a) in section `.text.JVM_FindLibraryEntry'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
	at com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:499)
	at com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:446)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:660)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:491)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:380)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)
[getting-started-1.0.0-SNAPSHOT-runner:27056]      [total]: 239 573,68 ms,  5,37 GB
# Printing build artifacts to: /home/me/tmp/quarkus-quickstarts/getting-started/target/getting-started-1.0.0-SNAPSHOT-native-image-source-jar/getting-started-1.0.0-SNAPSHOT-runner.build_artifacts.txt
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:32 min
[INFO] Finished at: 2021-08-15T23:52:13-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.1.2.Final:build (default) on project getting-started: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:235)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.lang.RuntimeException: Image generation failed. Exit code: 1
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:377)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:205)
[ERROR] 	... 11 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

I don't remember having had to do anything specific in terms of native image generation on this setup previously.

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this, could you please provide a reproducer for this issue?

**Comment by jaikiran** [comment]
> could you please provide a reproducer for this issue?

The steps are as follows:
- Clone https://github.com/quarkusio/quarkus-quickstarts
- cd `getting-started`
- Set `GRAALVM_HOME` environment variable to point to the Graal VM installation which has `native-image` installed
- Using Apache Maven 3.8.x, run:

```
mvn clean install -Pnative
```

That generates the above error.

**Comment by oubidar-Abderrahim** [comment]
I tested with `mvn clean package -Pnative` and managed to build the app without issues. make sure you have native-image dependencies installed on your machine `sudo apt-get installbuild-essential libz-dev zlib1g-dev`

**Comment by jaikiran** [comment]
Closing this, since I no longer have access to this setup and I haven't been able to reproduce this on other setups. Thank you for taking time to investigate this @oubidar-Abderrahim.
