### ISSUE TITLE
Java 16 records do not work with native-image

### ISSUE THREAD

**Issue by andrewluotechnologies** [oracle/graal#3687]
**Describe the issue**
Java 16 records do not work with native-image.  The image gets generated but `equals` and `toString` do not work out of the box.  With additional reflection configuration, `toString` can work, but `equals` does not work at all.

**Steps to reproduce the issue**
Example.java
```
public class Example {
    public record Record(String value) {
    }

    public static void main(String[] args) {
        System.out.println(new Record("a").equals(new Record("b")));
    }
}
```

Run the following commands:
```
javac Example.java
native-image -cp . Example
./example
```

Error:
```
Exception in thread "main" java.lang.NoSuchMethodError: java.lang.runtime.ObjectMethods.eq(java.lang.Object, java.lang.Object)
	at com.oracle.svm.methodhandles.Util_java_lang_invoke_MethodHandleNatives.resolve(Target_java_lang_invoke_MethodHandleNatives.java:342)
	at java.lang.invoke.MethodHandleNatives.resolve(MethodHandleNatives.java:214)
	at com.oracle.svm.methodhandles.Util_java_lang_invoke_MethodHandle.invokeInternal(Target_java_lang_invoke_MethodHandle.java:139)
	at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:79)
	at com.oracle.svm.methodhandles.MethodHandleIntrinsicImpl.execute(MethodHandleIntrinsicImpl.java:180)
	at com.oracle.svm.methodhandles.Util_java_lang_invoke_MethodHandle.invokeInternal(Target_java_lang_invoke_MethodHandle.java:144)
	at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:79)
	at java.lang.invoke.LambdaForm$NamedFunction.invokeWithArguments(LambdaForm.java:76)
	at java.lang.invoke.LambdaForm.interpretName(LambdaForm.java:985)
	at java.lang.invoke.LambdaForm.interpretWithArguments(LambdaForm.java:962)
	at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:85)
	at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:0)
	at java.lang.invoke.LambdaForm$MH.0x00000007c0cbc000.linkToTargetMethod(LambdaForm$MH)
	at Example$Record.equals(Example.java:2)
	at Example.main(Example.java:6)
```

If you add the following reflection configuration (`reflection-configuration.json`):
```
[
  {
    "name": "java.lang.runtime.ObjectMethods",
    "allPublicMethods": true
  }
]
```
then, this fixes `toString` when compiled with:
```
native-image -cp . -H:ReflectionConfigurationFiles=reflection-configuration.json Example 
```
however, `equals` still fails with
```
Exception in thread "main" java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
	at com.oracle.svm.core.invoke.MethodHandleUtils.intUnbox(MethodHandleUtils.java:86)
	at com.oracle.svm.core.invoke.MethodHandleUtils.intUnbox(MethodHandleUtils.java:74)
	at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:0)
	at java.lang.invoke.LambdaForm$MH.0x00000007c0cbdc00.linkToTargetMethod(LambdaForm$MH)
	at Example$Record.equals(Example.java:2)
	at Example.main(Example.java:6)
```

Note, I also tried adding `Example$Record` to the reflection configuration but it doesn't change anything.

**Describe GraalVM and your environment:**
GraalVM CE Java 16 21.3.0-dev and 21.2.0 (both behave the same) on MacOS and Linux.

**Comment by rodrigar-mx** [comment]
Thank you for reporting this issue. We will take a closer look into it and get back to you.

**Comment by rodrigar-mx** [comment]
Hi @andrewluotechnologies. I tested your sample app with the latest dev release and the error has gone. No `reflection-configuration.json` is required. Download it from [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/21.3.0-dev-20210817_2030).

**Comment by andrewluotechnologies** [comment]
Thanks! Confirmed that this works in the latest dev version as well.  Do we know what the issue was/what fixed it?
