### ISSUE TITLE
Native image from Kawa Scheme fails to start due to ClassNotFoundException: java.lang.Number

### ISSUE THREAD

**Issue by duncanmak** [oracle/graal#3689]
I'm running `graalvm-ce-java11-21.2.0` and unlike the `20.3.0` release (see #3024), I can now successfully generate a native image, hurray! 

```
[Tue Aug 17 16:29:07 EDT 2021][INFO] We will now compile your code for x86_64-apple-darwin. This may take some time.
[Tue Aug 17 16:29:09 EDT 2021][INFO] [SUB] Warning: Ignoring server-mode native-image argument --no-server.
[Tue Aug 17 16:29:12 EDT 2021][INFO] [SUB] [javafx-from-kawa:57892]    classlist:   2,443.89 ms,  0.96 GB
[Tue Aug 17 16:29:16 EDT 2021][INFO] [SUB] [javafx-from-kawa:57892]        (cap):   2,653.66 ms,  0.96 GB
[Tue Aug 17 16:29:17 EDT 2021][INFO] [SUB] [javafx-from-kawa:57892]        setup:   4,750.65 ms,  0.96 GB
[Tue Aug 17 16:30:39 EDT 2021][INFO] [SUB] [javafx-from-kawa:57892]     (clinit):     886.80 ms,  5.61 GB
[Tue Aug 17 16:30:39 EDT 2021][INFO] [SUB] [javafx-from-kawa:57892]   (typeflow):  35,288.94 ms,  5.61 GB
[Tue Aug 17 16:30:39 EDT 2021][INFO] [SUB] [javafx-from-kawa:57892]    (objects):  41,258.70 ms,  5.61 GB
[Tue Aug 17 16:30:39 EDT 2021][INFO] [SUB] [javafx-from-kawa:57892]   (features):   2,536.29 ms,  5.61 GB
[Tue Aug 17 16:30:39 EDT 2021][INFO] [SUB] [javafx-from-kawa:57892]     analysis:  81,994.81 ms,  5.61 GB
[Tue Aug 17 16:30:43 EDT 2021][INFO] [SUB] [javafx-from-kawa:57892]     universe:   3,690.54 ms,  5.66 GB
[Tue Aug 17 16:30:47 EDT 2021][INFO] [SUB] [javafx-from-kawa:57892]      (parse):   3,622.62 ms,  5.66 GB
[Tue Aug 17 16:30:57 EDT 2021][INFO] [SUB] [javafx-from-kawa:57892]     (inline):  10,023.29 ms,  6.17 GB
[Tue Aug 17 16:31:45 EDT 2021][INFO] [SUB] [javafx-from-kawa:57892]    (compile):  48,038.29 ms,  6.56 GB
[Tue Aug 17 16:31:47 EDT 2021][INFO] [SUB] [javafx-from-kawa:57892]      compile:  64,481.52 ms,  6.56 GB
[Tue Aug 17 16:31:55 EDT 2021][INFO] [SUB] [javafx-from-kawa:57892]        image:   7,694.81 ms,  6.45 GB
[Tue Aug 17 16:31:56 EDT 2021][INFO] [SUB] [javafx-from-kawa:57892]        write:   1,016.39 ms,  6.45 GB
[Tue Aug 17 16:31:56 EDT 2021][INFO] [SUB] [javafx-from-kawa:57892]      [total]: 166,750.49 ms,  6.45 GB
[Tue Aug 17 16:31:56 EDT 2021][INFO] [SUB] # Printing build artifacts to: /Users/duncan/git/duncanmak/kawa-javafx-graalvm/target/client/x86_64-darwin/gvm/HelloFXFromKawa/javafx-from-kawa.build_artifacts.txt
[INFO] 
[INFO] --- client-maven-plugin:0.1.34:link (default-cli) @ kawa-javafx-graalvm ---
[Tue Aug 17 16:31:58 EDT 2021][INFO] ==================== LINK TASK ====================
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:03 min
[INFO] Finished at: 2021-08-17T16:32:03-04:00
[INFO] ------------------------------------------------------------------------
```

When I try to run the resulting binary, I get this error:

```
yomigana:kawa-javafx-graalvm (main) % ./target/client/x86_64-darwin/HelloFXFromKawa    
2021-08-17 16:32:30.756 HelloFXFromKawa[58145:3515805] Starting Gluon VM...
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:315)
	at java.lang.Class.ensureInitialized(DynamicHub.java:548)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:260)
	at java.lang.Class.ensureInitialized(DynamicHub.java:548)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:260)
	at gnu.kawa.reflect.ClassMemberLocation.<clinit>(ClassMemberLocation.java:188)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
	at java.lang.Class.ensureInitialized(DynamicHub.java:548)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:260)
	at java.lang.Class.ensureInitialized(DynamicHub.java:548)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:260)
	at gnu.kawa.lispexpr.LispLanguage.<clinit>(LispLanguage.java:44)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
	at java.lang.Class.ensureInitialized(DynamicHub.java:548)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:260)
	at javafx-from-kawa.<clinit>(main.scm)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
Caused by: java.lang.RuntimeException: no such class: java.lang.Number
	at gnu.bytecode.ObjectType.getReflectClass(ObjectType.java:122)
	at gnu.bytecode.ClassType.getDeclaredMethods(ClassType.java:808)
	at gnu.bytecode.ClassType.getDeclaredMethod(ClassType.java:958)
	at gnu.bytecode.ClassType.addMethod(ClassType.java:745)
	at gnu.bytecode.ClassType.addMethod(ClassType.java:735)
	at gnu.bytecode.Type.<clinit>(Type.java:691)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
	... 19 more
Caused by: java.lang.ClassNotFoundException: java.lang.Number
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:71)
	at java.lang.Class.forName(DynamicHub.java:1319)
	at gnu.bytecode.ObjectType.getContextClass(ObjectType.java:88)
	at gnu.bytecode.ObjectType.getReflectClass(ObjectType.java:115)
	... 26 more
2021-08-17 16:32:30.759 HelloFXFromKawa[58145:3515805] Started Gluon VM...
```

**Comment by chirontt** [comment]
From my experience, it's imperative that any JavaFX (or Swing) application must be run first with the native-image-agent to generate the configuration files, for the native-image command to use later to produce the native image. That would take care of those missing classes such as java.lang.Number, etc., in the resultant native image, as you have found out.

BTW, your repo as of now can't be compiled to native image in my Windows 10 platform. I have to downgrade the javafx version to 16, and upgrade the client-maven-plugin to its latest version (1.0.4, with its new artifactId `gluonfx-maven-plugin`) in order to generate the Windows native image successfully. Then I can see the missing java.lang.Number error... which is then fixed with the above-mentioned config files generated by the native-image-agent.

**Comment by johanvos** [comment]
The GraalVM analysis is able to see which classes are used directly, and via reflection if that can be determined at build-time. All classes that are referenced from the main entry point will be included.
If you use reflection, you might have to run the agent to include classes that are not directly referred.
Since JavaFX internally uses reflection too, we bundle jars with json files that contain lists for JNI/reflection. 
But it seems this class (java.lang.Number) is referenced via reflection (gnu.bytecode.ObjectType.getReflectClass)?

**Comment by duncanmak** [comment]
@chirontt Thanks for looking into my repo: https://github.com/duncanmak/kawa-javafx-graalvm

I updated the `pom.xml` per your comment, can you see if that matches what you did?

Also, what's the command you used for running `native-image-agent`?

@johanvos Thanks for your note, I found the code in Kawa that's dependent on Reflection, it's in gnu.bytecode.Type.

https://gitlab.com/kashell/Kawa/-/blob/master/gnu/bytecode/Type.java#L650

![image](https://user-images.githubusercontent.com/4791/130000003-8aaf4570-aedd-4702-8766-23243043a769.png)

**Comment by chirontt** [comment]
@duncanmak, in the `javafx-maven-plugin` block add the following configuration options to enable the agent:

	    <options>
	        <option>-agentlib:native-image-agent=config-merge-dir=src/main/resources/META-INF/native-image</option>
	    </options>

i.e. the configuration block becomes:

	<configuration>
	    <mainClass>${main.class}</mainClass>
	    <options>
	        <option>-agentlib:native-image-agent=config-merge-dir=src/main/resources/META-INF/native-image</option>
	    </options>
	</configuration>

Run the app like normal: `mvn javafx:run`, go through its functions then quit, and the agent will generate the config files in the specified directory.

Then generate the native image with: `mvn gluonfx:build`

Kudos to @johanvos and his team for maintaining/enhancing the JavaFX framework, and for developing the Maven/Gradle plugins to help in the native image generation for JavaFX apps.

**Comment by duncanmak** [comment]
@chirontt I gave it a go but it doesn't seem to be generating the files: https://github.com/duncanmak/kawa-javafx-graalvm/commit/3c3da4cbe1868f14014f35ef1007405a29445020

**Comment by chirontt** [comment]
Your \<option\> is incomplete; it should be enclosed within \<options\>, i.e.

	<options>
	    <option>-agentlib:native-image-agent=config-merge-dir=src/main/resources/META-INF/native-image</option>
	</options>

I'm surprised that the `javafx-maven-plugin` doesn't complain about the invalid \<option\> setting... Looks like it just ignores it...

Also, your `JAVA_HOME` should be pointing to the GraalVM installation, not the OpenJDK one, as the `native-image-agent` only exists in GraalVM, so that `mvn javafx:run` would work properly.
