### ISSUE TITLE
CI fails intermittently

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#3693]
**Describe the issue**

Ci fails intermittently (about 1 out of 10 times)  on `com.oracle.truffle.api.test.polyglot.PolyglotCachingTest#testSourceFreeContextStrong` test.
See https://github.com/oracle/graal/runs/3354825179?check_suite_focus=true for a failure and https://github.com/oracle/graal/actions/workflows/main.yml?query=branch%3Amaster for the general picture.

**More details**
The failed test gives the following output
```
There was 1 failure:
1) com.oracle.truffle.api.test.polyglot.PolyglotCachingTest#testSourceFreeContextStrong
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.oracle.truffle.api.test.GCUtils.assertObjectsCollectible(GCUtils.java:88)
	at com.oracle.truffle.api.test.polyglot.PolyglotCachingTest.testSourceFreeContextStrong(PolyglotCachingTest.java:165)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at com.oracle.mxtool.junit.MxJUnitWrapper$1.schedule(MxJUnitWrapper.java:324)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.oracle.mxtool.junit.MxJUnitWrapper.runRequest(MxJUnitWrapper.java:357)
	at com.oracle.mxtool.junit.MxJUnitWrapper.main(MxJUnitWrapper.java:222)
```

**Comment by zakkak** [comment]
Hi @mcraj017, I noticed that you linked #2880 to this issue.
#2880, however, does not fix this issue, it's just a PR whose CI checks happened to fail due to this issue, could you please unlink it?

**Comment by zakkak** [comment]
The issue does no longer appear on CI runs.
