### ISSUE TITLE
ibatis logger nullpointerexception 

### ISSUE THREAD

**Issue by necipakca** [oracle/graal#3694]
After build image when I run application I get following exception,

Please include both build steps as well as run steps
time native-image \
  -J-Xmx16G \
  -H:IncludeResources=".*.xml|.*.conf|.*.properties" \
  --no-server \
  -H:Name=$ARTIFACT \
  -H:+ReportUnsupportedElementsAtRuntime \
  -H:+ReportExceptionStackTraces \
  -Dspring.native.remove-unused-autoconfig=true \
  -Dspring.native.remove-yaml-support=true \
  --allow-incomplete-classpath \
  --report-unsupported-elements-at-runtime \
  --initialize-at-run-time=io.netty.handler.codec.compression.BrotliDecoder \
  --initialize-at-build-time=io.netty.util.internal.logging.Log4JLogger,org.apache.commons.logging.impl.SLF4JLocationAwareLog,org.slf4j.MDC,ch.qos.logback.classic.spi.ThrowableProxy,org.springframework.util.unit.DataSize,org.slf4j.impl.StaticLoggerBinder,org.slf4j.LoggerFactory,ch.qos.logback.classic.Logger,ch.qos.logback.core.spi.AppenderAttachableImpl,ch.qos.logback.core.status.StatusBase,ch.qos.logback.classic.Level,ch.qos.logback.core.status.InfoStatus,ch.qos.logback.classic.PatternLayout,ch.qos.logback.core.CoreConstants \
  -cp $CP $MAINCLASS --verbose;

**Describe GraalVM and your environment:**
 -  GraalVM 21.2.0 Java 11 CE
 -  Big Sur - MacOS
 -  AMD64

2021-08-18 17:24:02 - Application run failed
java.lang.ExceptionInInitializerError: null
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:315)
        at org.mybatis.spring.mapper.MapperScannerConfigurer.postProcessBeanDefinitionRegistry(MapperScannerConfigurer.java:341)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:142)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
        at tr.com.turksat.sorgu.SorguApplication.main(SorguApplication.java:18)
Caused by: org.apache.ibatis.logging.LogException: Error creating logger for logger org.mybatis.spring.mapper.ClassPathMapperScanner.  Cause: java.lang.NullPointerException
        at org.apache.ibatis.logging.LogFactory.getLog(LogFactory.java:54)
        at org.apache.ibatis.logging.LogFactory.getLog(LogFactory.java:47)
        at org.mybatis.logging.LoggerFactory.getLogger(LoggerFactory.java:32)
        at org.mybatis.spring.mapper.ClassPathMapperScanner.<clinit>(ClassPathMapperScanner.java:54)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
        ... 12 common frames omitted
Caused by: java.lang.NullPointerException: null
        at org.apache.ibatis.logging.LogFactory.getLog(LogFactory.java:52)
        ... 17 common frames omitted

**Comment by mcraj017** [comment]
@necipakca Thanks for reporting the issue,please use a native-image tracing agent
https://docs.oracle.com/en/graalvm/enterprise/21/docs/reference-manual/native-image/Agent/

**Comment by necipakca** [comment]
I added org.apache.ibatis.logging.slf4j.Slf4jLocationAwareLoggerImpl to initialize-at-build-time parameter it fixed.
