### ISSUE TITLE
Method Handles ends up with java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by dainiusjocas** [oracle/graal#3695]
When compiled with the `native-image` the concurrent invocation of the [Lovins stemmer](https://github.com/apache/lucene/blob/0b1d8ccba6cf394f707a09217813a25ec1504e50/lucene/analysis/common/src/java/org/tartarus/snowball/ext/LovinsStemmer.java) sometimes fails with an exception (see below). 
It seems that the GraalVM method handles implementation causes the exception.
When running in the JVM the same code never fails.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. git clone https://github.com/dainiusjocas/lucene-grep.git
2. cd lucene-grep 
3. git checkout bug/lovins-stemmer-concurrent-modification-exception
4. make build
5. ./lmgrep test/resources/test.txt --only-analyze --analysis="$(cat test/resources/binary/tokenfilters/lovinssnowballstem.json)" > /dev/null;

An alternative for the last step to invoke the same code in JVM would be:
```
clojure -M -m lmgrep.core test/resources/test.txt --only-analyze --analysis="$(cat test/resources/binary/tokenfilters/lovinssnowballstem.json)"
```

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: graalvm-ce-java11-21.2.0
 - JDK major version: 11
 - OS: Ubuntu 21.04, Fedora 34
 - Architecture: AMD64
- Clojure version: 1.10.3.814

Installing Clojure as described here https://clojure.org/guides/getting_started

```java.util.ConcurrentModificationException
        at java.util.HashMap.computeIfAbsent(HashMap.java:1134)
        at com.oracle.svm.methodhandles.MethodHandleIntrinsicImpl.intrinsic(MethodHandleIntrinsicImpl.java:143)
        at com.oracle.svm.methodhandles.MethodHandleIntrinsicImpl.intrinsic(MethodHandleIntrinsicImpl.java:147)
        at com.oracle.svm.methodhandles.MethodHandleIntrinsicImpl.resolve(MethodHandleIntrinsicImpl.java:430)
        at com.oracle.svm.methodhandles.Util_java_lang_invoke_MethodHandleNatives.resolve(Target_java_lang_invoke_MethodHandleNatives.java:307)
        at java.lang.invoke.MethodHandleNatives.resolve(MethodHandleNatives.java:214)
        at com.oracle.svm.methodhandles.Util_java_lang_invoke_MethodHandle.invokeInternal(Target_java_lang_invoke_MethodHandle.java:139)
        at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:79)
        at java.lang.invoke.LambdaForm$NamedFunction.invokeWithArguments(LambdaForm.java:76)
        at java.lang.invoke.LambdaForm.interpretName(LambdaForm.java:981)
        at java.lang.invoke.LambdaForm.interpretWithArguments(LambdaForm.java:958)
        at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:85)
        at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:0)
        at java.lang.invoke.LambdaForm$MH/1713965096.invokeExact_MT(LambdaForm$MH)
        at org.tartarus.snowball.SnowballProgram.find_among_b(SnowballProgram.java:382)
        at org.tartarus.snowball.ext.LovinsStemmer.r_endings(LovinsStemmer.java:1526)
        at org.tartarus.snowball.ext.LovinsStemmer.stem(LovinsStemmer.java:1886)
        at org.apache.lucene.analysis.snowball.SnowballFilter.incrementToken(SnowballFilter.java:95)
        at lmgrep.lucene.text_analysis$text__GT_token_strings.invokeStatic(text_analysis.clj:16)
        at lmgrep.lucene.text_analysis$text__GT_token_strings.invoke(text_analysis.clj:9)
        at lmgrep.only_analyze$ordered_analysis$analyze_fn__9504.invoke(only_analyze.clj:99)
        at clojure.core$map$fn__5880$fn__5881.invoke(core.clj:2746)
        at clojure.core.async.impl.channels$chan$fn__1031.invoke(channels.clj:300)
        at clojure.core.async.impl.channels.ManyToManyChannel.put_BANG_(channels.clj:143)
        at clojure.core.async$fn__6243.invokeStatic(async.clj:172)
        at clojure.core.async$fn__6243.invoke(async.clj:164)
        at clojure.core.async$pipeline_STAR_$process__6427.invoke(async.clj:534)
        at clojure.core.async$pipeline_STAR_$fn__6556.invoke(async.clj:549)
        at clojure.core.async$thread_call$fn__6350.invoke(async.clj:484)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:829)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:567)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
```

**Comment by mcraj017** [comment]
@dainiusjocas Thanks for reporting the issue, we will check it out and get back to you

**Comment by mcraj017** [comment]
Closing this issue as there is no activity in last 30 daysa
