### ISSUE TITLE
substratvm compilation failed NoneType is not iterable

### ISSUE THREAD

**Issue by dufoli** [oracle/graal#3700]
**Describe GraalVM and your environment :**
 - GraalVM master
 - CE or EE: CE
 - JDK version: 11
 - OS and OS Version: windows but with ubuntu WSL2
 - Architecture: amd64
 - The output of `java -Xinternalversion`:
```
 OpenJDK 64-Bit Server VM (11.0.12+6-jvmci-21.2-b08) for linux-amd64 JRE (11.0.12+6-jvmci-21.2-b08), built on Jul 19 2021 23:31:59 by "buildslave" with gcc 7.3.0
```

 java --version:
```
openjdk 11.0.12 2021-07-20
OpenJDK Runtime Environment GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08)
OpenJDK 64-Bit Server VM GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08, mixed mode, sharing)

```

**Describe the issue**
compilation of substratevm failed with error.

**Code snippet or code repository that reproduces the issue**
```
   sudo apt install openjdk-11-jre-headless
   sudo apt-get install openjdk-11-jdk
  sudo apt-get install libc6-dev
  sudo apt-get install zlib1g-dev
  sudo apt-get install gcc
  sudo apt-get install python3.8
  sudo apt-get install build-essential
  sudo apt-get install python-is-python3
  sudo apt-get install libstdc++6
wget https://github.com/graalvm/mx/archive/refs/tags/5.309.1.tar.gz
cd mx-5.309.1/
export PATH=$HOME/mx-5.309.1:$PATH
export PATH=$HOME/graalvm-ce-java11-21.2.0/bin:$PATH
export JAVA_HOME=$HOME/graalvm-ce-java11-21.2.0
cd substratevm
mx build
```

```
   JAVA_HOME: /home/dufoli/graalvm-ce-java11-21.2.0
25 unsatisfied dependencies were removed from build (use -v to list them)
1 non-default dependencies were removed from build (use -v to list them, mx build --all to build them)
Building com.oracle.svm.native.libchelper_amd64 with Ninja...
Building com.oracle.jvmtiasmagent_amd64 with Ninja...
Building com.oracle.jvmtiasmagent_amd64 with Ninja: Failed due to error: argument of type 'NoneType' is not iterable
Process Process-67:
Building com.oracle.truffle.nfi.test.native.isolation_amd64 with Ninja...
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dufoli/mx-5.309.1/mx.py", line 14358, in executeTask
    task.execute()
  File "/home/dufoli/mx-5.309.1/mx.py", line 5135, in execute
    _built = self.build()
  File "/home/dufoli/mx-5.309.1/mx_native.py", line 426, in build
    self.subject.generate_manifest(sfc.tmpPath)
  File "/home/dufoli/mx-5.309.1/mx_native.py", line 736, in generate_manifest
    cflags=[mx_subst.path_substitutions.substitute(cflag) for cflag in self.cflags],
  File "/home/dufoli/mx-5.309.1/mx_native.py", line 681, in cflags
    default_cflags += [add_debug_prefix(self.suite.vc_dir)]
  File "/home/dufoli/mx-5.309.1/mx_native.py", line 679, in add_debug_prefix
    return '-fdebug-prefix-map={}={}'.format(quote(prefix_dir), quote(mx.basename(prefix_dir)))
  File "/home/dufoli/mx-5.309.1/mx_native.py", line 677, in quote
    return '"{}"'.format(path) if ' ' in path else path
TypeError: argument of type 'NoneType' is not iterable
Compiling org.graalvm.nativeimage with javac-daemon(JDK 11)... [/home/dufoli/graal/sdk/mxbuild/src/org.graalvm.nativeimage/bin/org/graalvm/nativeimage/StackValue.class does not exist]
```

**Comment by rodrigar-mx** [comment]
Thanks for reporting the issue. Could you please try cloning the code directly from the repo https://github.com/graalvm/mx.git instead of downloading the tar file.
