### ISSUE TITLE
Module `com.oracle.truffle.regex` does not read module `java.logging`

### ISSUE THREAD

**Issue by boris-petrov** [oracle/graal#3707]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **21.2.0**
 - CE or EE: **CE**
 - JDK version: **JDK 16**
 - OS and OS Version: **Arch Linux 5.13.12-arch1-1**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
OpenJDK 64-Bit Server VM (16.0.2+7) for linux-amd64 JRE (16.0.2+7), built on Jul 22 2021 03:33:00 by "builduser" with gcc 11.1.0
```

**Have you verified this issue still happens when using the latest snapshot?**
No.

**Describe the issue**
Putting Graal's JARs on the module-path and running a JS app that uses regexes blows up with:

```
Exception in thread "main" org.graalvm.polyglot.PolyglotException: java.lang.IllegalAccessError: class com.oracle.truffle.regex.tregex.TRegexCompiler (in module com.oracle.truffle.regex) cannot access class java.util.logging.Level (in module java.logging) because module com.oracle.truffle.regex does not read module java.logging
        at com.oracle.truffle.regex/com.oracle.truffle.regex.tregex.TRegexCompiler.shouldLogCompilationTime(TRegexCompiler.java:121)
        at com.oracle.truffle.regex/com.oracle.truffle.regex.tregex.TRegexCompiler.compile(TRegexCompiler.java:72)
        at com.oracle.truffle.regex/com.oracle.truffle.regex.RegexLanguage.createRegexObject(RegexLanguage.java:186)
        at com.oracle.truffle.regex/com.oracle.truffle.regex.RegexLanguage.parse(RegexLanguage.java:149)
        at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$ParsingRequest.parse(TruffleLanguage.java:863)
        at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage.parse(TruffleLanguage.java:1517)
        at org.graalvm.truffle/com.oracle.truffle.api.LanguageAccessor$LanguageImpl.parse(LanguageAccessor.java:311)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotSourceCache.parseImpl(PolyglotSourceCache.java:94)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotSourceCache.access$300(PolyglotSourceCache.java:56)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotSourceCache$WeakCache.lookup(PolyglotSourceCache.java:223)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotSourceCache.parseCached(PolyglotSourceCache.java:80)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext.parseCached(PolyglotLanguageContext.java:360)
        ...
```

**Code snippet or code repository that reproduces the issue**

`build.gradle`:
```gradle
plugins {
	id 'application'
}

repositories {
	mavenCentral()
}

configurations {
	graal
}

ext.graalVmVersion = '21.2.0'

dependencies {
	compileOnly "org.graalvm.sdk:graal-sdk:$graalVmVersion"

	graal "org.graalvm.compiler:compiler:$graalVmVersion"
	graal "org.graalvm.compiler:compiler-management:$graalVmVersion"
	graal "org.graalvm.sdk:graal-sdk:$graalVmVersion"
	graal "org.graalvm.truffle:truffle-api:$graalVmVersion"
	graal "org.graalvm.js:js:$graalVmVersion"
}

def graalCompilerDir = "$buildDir/graal-compiler"

application {
	mainClass = 'graal.test.App'
	applicationDefaultJvmArgs = [
		'-XX:+UnlockExperimentalVMOptions',
		'-XX:+EnableJVMCI',
		'-XX:-UseJVMCICompiler',
		"--module-path=$graalCompilerDir",
		"--upgrade-module-path=$graalCompilerDir",
	]
}

tasks.register('prepareGraalCompiler', Copy) {
	doFirst {
		delete graalCompilerDir
	}

	into graalCompilerDir
	from configurations.graal
}

tasks.named('run').configure {
	dependsOn prepareGraalCompiler
}
```

`src/main/java/graal/test/App.java`:

```java
package graal.test;

import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.Source;

public class App {
    public static final String SOURCE = "console.log(/asd/.test('qwe'));";

    public static void main(String[] args) throws Exception {
        try (Context context = Context.create()) {
            context.eval(Source.newBuilder("js", SOURCE, "src.js").build());
        }
    }
}
```

**Steps to reproduce the issue**
```sh
gradle run
```

**Expected behavior**
No error.

**Comment by boris-petrov** [comment]
Another case is [TRegexExecutorEntryNode](https://github.com/oracle/graal/blob/vm-21.2.0/regex/src/com.oracle.truffle.regex/src/com/oracle/truffle/regex/tregex/nodes/TRegexExecutorEntryNode.java#L51) which accesses `sun.misc.Unsafe`. This requires access to `jdk.unsupported`. I've updated the PR.

**Comment by chumer** [comment]
Looks good. Will get this through the internal gate.
