### ISSUE TITLE
When trying to close all context and reload sources, received error: The Context is already closed.

### ISSUE THREAD

**Issue by kokhoor** [oracle/graal#3716]
**Describe the issue**
In my framework, I am trying to implement a reload feature where all existing contexts are closed and then reloaded from scratch. However, upon reload, and executing the same sources (all are new variables, but the actual source file isn't changed), I received this: Caused by host exception: java.lang.IllegalStateException: The Context is already closed.

**Describe GraalVM and your environment:**
 - GraalVM version 21.3-dev CE
 - OS: Windows 10
 - Architecture: x64

**More details**
The source was init using following:
        initScript = Source.newBuilder("js", new File(scripts_path + "init.js")).build();
        engine = Engine.create();
        
        HostAccess.Builder builder = HostAccess.newBuilder();
        builder.targetTypeMapping(Value.class, Object.class, (v) -> {
                    return v.hasArrayElements();
                }, (v) -> {
                    return v.as(List.class);
                })
                .allowAllClassImplementations(true)
                .allowAllImplementations(true)
                .allowArrayAccess(true)
                .allowBufferAccess(true)
                .allowIterableAccess(true)
                .allowIteratorAccess(true)
                .allowListAccess(true)
                .allowMapAccess(true)
                .allowPublicAccess(true);
        hostAccess = builder.build();
        ctx = Context.newBuilder("js").hostClassLoader(classLoader)
                .engine(global.engine)
                .allowAllAccess(true)
                .allowValueSharing(true)
                .allowHostAccess(hostAccess)
                .allowIO(true).build();
        ctx.eval(initScript);
        Source setupEnvScript = Source.newBuilder("js", new File(scripts_path + "system/setup_env.js")).build();
        Value value = ctx.ctx.eval(setupEnvScript);
        ctxConstructor = value.execute();

Running was roughly done using this (in actual a bit more complicated because the scripts are called via Java from an outer class)
            Value ctx = (Value)ctxConstructor.newInstance(scriptContext.getScriptContext());
            Value callable = ctx.getMember("call");
            return callable.execute(action, args);

Stack:
The Context is already closed.
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineException.illegalState(PolyglotEngineException.java:129)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.checkClosed(PolyglotContextImpl.java:1025)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.enterThreadChanged(PolyglotContextImpl.java:608)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineImpl.enterCached(PolyglotEngineImpl.java:1884)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineImpl.enter(PolyglotEngineImpl.java:1831)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.OtherContextGuestObject.sendImpl(OtherContextGuestObject.java:137)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.OtherContextGuestObject$Send.doSlowPath(OtherContextGuestObject.java:119)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.OtherContextGuestObjectGen$ReflectionLibraryExports$Cached.executeAndSpecialize(OtherContextGuestObjectGen.java:145)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.OtherContextGuestObjectGen$ReflectionLibraryExports$Cached.send(OtherContextGuestObjectGen.java:92)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$Proxy.isNull(InteropLibraryGen.java:2365)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibrary$Asserts.isNull(InteropLibrary.java:2963)
	at com.oracle.truffle.js.nodes.unary.JSIsNullOrUndefinedNode.doJSValueOrForeign(JSIsNullOrUndefinedNode.java:158)
	at com.oracle.truffle.js.nodes.unary.JSIsNullOrUndefinedNodeGen.executeAndSpecialize(JSIsNullOrUndefinedNodeGen.java:469)
	at com.oracle.truffle.js.nodes.unary.JSIsNullOrUndefinedNodeGen.executeBoolean(JSIsNullOrUndefinedNodeGen.java:341)
	at com.oracle.truffle.js.nodes.control.IfNode.executeCondition(IfNode.java:236)
	at com.oracle.truffle.js.nodes.control.IfNode.executeVoid(IfNode.java:176)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:80)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:55)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedBlockNode.executeGeneric(OptimizedBlockNode.java:79)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:75)
	at com.oracle.truffle.js.nodes.control.ReturnTargetNode$FrameReturnTargetNode.execute(ReturnTargetNode.java:124)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:85)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeGeneric(AbstractBlockNode.java:55)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedBlockNode.executeGeneric(OptimizedBlockNode.java:81)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:75)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:150)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:93)
	at <js> call(Unknown)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.execute(Value.java:830)
	at my.com.solutionx.simplyscript.graal.ScriptEngine.action(ScriptEngine.java:130)

**Comment by oubidar-Abderrahim** [comment]
Sorry for the late response, could you please share the complete class used for reproducing this? thank you

**Comment by oubidar-Abderrahim** [comment]
Thank you that would be very helpful
