### ISSUE TITLE
[native-image] NullPointerException in ObjectScanner.scanField

### ISSUE THREAD

**Issue by kleinj** [oracle/graal#372]
I've been experimenting with the `native-image` compiler, trying to see how far I'd get with compilation of the PRISM modelchecker (details at the bottom for steps to reproduce). This resulted consistently in a `NullPointerException` in `ObjectScanner.scanField`:

```
$ native-image --version
SubstrateVM Version Info
68c7c1073a86a3d541ffb82434acc664f3096079:substratevm
GraalVM Version 1.0.0-rc1

$ native-image -Djava.awt.headless=true -Djava.library.path=$L \
-classpath $D/classes:$L/pepa.zip:$L/colt.jar:$L/epsgraphics.jar:$L/jas.jar:$L/jcommon.jar:$L/jfreechart.jar:$L/jhoafparser.jar:$L/log4j.jar:$L/nailgun-server.jar \
prism.PrismCL

Build on Server(pid: 15000, port: 26681)*
   classlist:   2,726.54 ms
       (cap):   1,482.02 ms
       setup:   2,686.01 ms
    analysis:  15,490.69 ms
fatal error: java.lang.NullPointerException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:398)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:240)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:337)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.executeCompilation(NativeImageBuildServer.java:378)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$processCommand$8(NativeImageBuildServer.java:315)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.withJVMContext(NativeImageBuildServer.java:396)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.processCommand(NativeImageBuildServer.java:312)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.processRequest(NativeImageBuildServer.java:256)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$serve$7(NativeImageBuildServer.java:216)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.oracle.graal.pointsto.ObjectScanner.scanField(ObjectScanner.java:113)
	at com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:263)
	at com.oracle.graal.pointsto.ObjectScanner.finish(ObjectScanner.java:307)
	at com.oracle.graal.pointsto.ObjectScanner.scanBootImageHeapRoots(ObjectScanner.java:78)
	at com.oracle.graal.pointsto.ObjectScanner.scanBootImageHeapRoots(ObjectScanner.java:60)
	at com.oracle.graal.pointsto.BigBang.checkObjectGraph(BigBang.java:581)
	at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:552)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:653)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:381)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Processing image build request failed
```

I'm aware that there a probably some further issues regarding the PRISM code base to solve to make it work with native-image (I haven't yet configured the JNI calls from the C/C++ side to Java), but I guess the NPE above should not occur anyways.
 

Reproduction: I've run the following commands on a fresh Amazon EC2 Ubuntu 16.04 LTS image (in addition to installing the binary GraalVM 1.0.0-rc1 release from github):

```
sudo apt update
sudo apt install build-essential git zlib1g-dev

# expects Graal installation in ~/graalvm-1.0.0-rc1
export PATH=$HOME/graalvm-1.0.0-rc1/bin:"$PATH"

git clone https://github.com/prismmodelchecker/prism
cd prism
# checkout specific commit for reproducibility
git checkout 382aa51de3153c3a329401f2d92f1708d89bad4a

# build PRISM (including shared C/C++ libraries)
cd prism
make

# to run PRISM: use the startup script in bin/
#  bin/prism

# setup paths
D=`pwd`
L="$D/lib"

# setup LD_LIBRARY_PATH (so that the shared libraries can find dependencies)
export LD_LIBRARY_PATH=$L:"$LD_LIBRARY_PATH"

native-image -Djava.awt.headless=true -Djava.library.path=$L \
-classpath $D/classes:$L/pepa.zip:$L/colt.jar:$L/epsgraphics.jar:$L/jas.jar:$L/jcommon.jar:$L/jfreechart.jar:$L/jhoafparser.jar:$L/log4j.jar:$L/nailgun-server.jar \
prism.PrismCL
```

(cc @davexparker)

**Comment by kleinj** [comment]
Thank you very much. Yes, static initializers are probably the cause. We'll try and work around that.

**Comment by cstancu** [comment]
The NPE is fixed in https://github.com/oracle/graal/commit/6fac95ab2434fc697ce975bb815d724b98e5f41f.
