### ISSUE TITLE
load build in shared library failure at runtime

### ISSUE THREAD

**Issue by Consulting4J** [oracle/graal#3721]
**Describe the issue**

can not load build-in native shared library (libattach.so) via loadLibrary in native-image mode while code works well in Java mode.

**Steps to reproduce the issue**

source code to trigger this issue

		try {
			System.loadLibrary("attach");
			System.out.println("loadLibrary attach successful ...");
		} catch (Error e) {
			System.out.println("loadLibrary attach failure: " + e.getMessage());
		}

command line to build native-image 

/home/runner/jdks/graalvm-ce-java11-21.3.0-dev/lib/svm/bin/native-image -cp /home/runner/jdks/JMS11/target/nativeagent-0.0.1-SNAPSHOT.jar:/home/runner/jdks/JMS11/tools.jar --initialize-at-build-time=sun.tools.jinfo.JInfo --no-fallback --verbose -H:+ReportExceptionStackTraces  -H:+StaticExecutableWithDynamicLibC   -H:CLibraryPath=. -H:Class=com.myapp.Main -H:Name=myapp

**Describe GraalVM and your environment:**
 - GraalVM version 
https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/21.3.0-dev-20210824_2253
commit id  https://github.com/oracle/graal/commit/524cc5f615112566fde87924800a10c1f8ac138f

 - JDK major version:  11
 - OS: ubuntu 18.04
 - Architecture: AMD64

**More details**
native image build successfully while got error while run app

java out put trace

loadLibrary attach failure: no attach in java.library.path
Exception in thread "main" java.lang.UnsatisfiedLinkError: no attach in java.library.path
	at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryRelative(NativeLibrarySupport.java:132)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:201)
	at java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.lang.System.loadLibrary(System.java:1871)
	at sun.tools.attach.VirtualMachineImpl.<clinit>(VirtualMachineImpl.java:374)
	at sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:58)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
	at sun.tools.jinfo.JInfo.attach(JInfo.java:191)
	at sun.tools.jinfo.JInfo.sysprops(JInfo.java:182)
	at sun.tools.jinfo.JInfo.main(JInfo.java:116)

**Comment by rodrigar-mx** [comment]
Hi @Consulting4J. Thanks for reporting the issue. Could you please share a reproducer.

**Comment by Consulting4J** [comment]
@rodrigar-mx 
the following code could be used to reproduce the error.

	try {
		System.loadLibrary("attach");
		System.out.println("loadLibrary attach successful ...");
	} catch (Error e) {
		System.out.println("loadLibrary attach failure: " + e.getMessage());
	}

when try to convert this application to native image, you would get error like this

loadLibrary attach failure: no attach in java.library.path
Exception in thread "main" java.lang.UnsatisfiedLinkError: no attach in java.library.path
at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryRelative(NativeLibrarySupport.java:132)
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:201)
at java.lang.Runtime.loadLibrary0(Runtime.java:830)
at java.lang.System.loadLibrary(System.java:1871)

**Comment by rodrigar-mx** [comment]
Thanks for sharing @Consulting4J. I misread the first time and did not notice you were trying to load a build-in library. Anyway, I have reported this issue internally with the native image team. You will receive a response accordingly.

**Comment by Consulting4J** [comment]
still pending ?

**Comment by rodrigar-mx** [comment]
Yes, still in queue.

**Comment by teshull** [comment]
Hi @Consulting4J So the immediate cause of this error is that SVM doesn't link with the JNI native libattach library. By default we normally link against the libraries here: https://github.com/oracle/graal/blob/9f923dd4c87bd458b5c6ffed32b15494d17ea0d4/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/PlatformNativeLibrarySupport.java#L43 

However, libattach is used to attached to the underlying JVM, but when using native-image there is not an underlying JVM.

So how exactly are you trying to use native-image. Are you trying to make a native-image out of JInfo, or something else?

**Comment by wirthi** [comment]
Closing this older ticket with unanswered question. Feel free to reopen if this issue is still relevant to you. Ideally, you can provide an executable reproducer for a recent GraalVM version so we can directly investigate.
