### ISSUE TITLE
[native-image] NPE in ObjectScanner.scanField

### ISSUE THREAD

**Issue by nanodeath** [oracle/graal#375]
Disclaimer: I think you already fixed this (kind of), but the `fieldValue` at the top of `scanField` can be null, and we're hitting that...apparently on one of Graal's own classes (?):

```
   classlist:  23,270.81 ms
       (cap):   1,268.92 ms
       setup:   1,959.10 ms
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
RecomputeFieldValue.ArrayIndexScale automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.arrayIndexScale(Class) was detected in the static initializer of com.lmax.disruptor.RingBufferFields. Add a RecomputeFieldValue.ArrayIndexScale manual substitution for com.lmax.disruptor.RingBufferFields.
RecomputeFieldValue.ArrayBaseOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.arrayBaseOffset(Class) was detected in the static initializer of com.lmax.disruptor.RingBufferFields. Add a RecomputeFieldValue.ArrayBaseOffset manual substitution for com.lmax.disruptor.RingBufferFields.
    analysis: 179,822.70 ms
fatal error: java.lang.NullPointerException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:398)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:240)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:337)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:78)
Caused by: java.lang.NullPointerException
        at com.oracle.graal.pointsto.ObjectScanner.scanField(ObjectScanner.java:113)
        at com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:263)
        at com.oracle.graal.pointsto.ObjectScanner.finish(ObjectScanner.java:307)
        at com.oracle.graal.pointsto.ObjectScanner.scanBootImageHeapRoots(ObjectScanner.java:78)
        at com.oracle.graal.pointsto.ObjectScanner.scanBootImageHeapRoots(ObjectScanner.java:60)
        at com.oracle.graal.pointsto.BigBang.checkObjectGraph(BigBang.java:581)
        at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:552)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:653)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:381)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image building with exit status 1
```

I've managed to set a break point just before the NPE is thrown:
![image](https://user-images.githubusercontent.com/10625/39160431-2347cc90-4720-11e8-87b1-23ff15897ef2.png)

Using Graal 1.0.0 RC.

**Comment by cstancu** [comment]
This is most likely the same issue as https://github.com/oracle/graal/issues/372 which was just fixed in https://github.com/oracle/graal/commit/6fac95ab2434fc697ce975bb815d724b98e5f41f. That NPE was hiding the actual issue: we don't support ZipFile objects in the boot image heap for reasons described [here](https://github.com/oracle/graal/blob/master/substratevm/LIMITATIONS.md#static-initializers). Try with the latest sources.

**Comment by nanodeath** [comment]
*Fixed an hour ago*. Nice. Guess it's time to build from source.

**Comment by nanodeath** [comment]
Building substratevm from source also succeeded without a hitch.

I got past the original error and am now seeing a couple other `This is not supported.`-type errors, which I guess I need to figure out how to solve! The "stack"trace isn't 100% clear, but I think it'll be enough.
