### ISSUE TITLE
JfrNativeEventWriter.putUtf8() does not work

### ISSUE THREAD

**Issue by zhengyu123** [oracle/graal#3752]
The method is annotated as Uninterruptible. However, it calls standard String class methods that are not annotated with Uninterruptible, that results errors while creating native image. e.g.

Unannotated callee: java.lang.String.charAt(int) called by annotated caller com.oracle.svm.core.jdk.UninterruptibleUtils$String.modifiedUtf8Length(String, boolean)
at com.oracle.svm.core.jdk.UninterruptibleUtils$String.modifiedUtf8Length(UninterruptibleUtils.java:467) [bci: 17]
Unannotated callee: java.lang.String.charAt(int) called by annotated caller com.oracle.svm.core.jdk.UninterruptibleUtils$String.toModifiedUtf8(String, Pointer, Pointer, boolean)
at com.oracle.svm.core.jdk.UninterruptibleUtils$String.toModifiedUtf8(UninterruptibleUtils.java:488) [bci: 21]
Unannotated callee: java.lang.String.length() called by annotated caller com.oracle.svm.core.jdk.UninterruptibleUtils$String.modifiedUtf8Length(String, boolean)
at com.oracle.svm.core.jdk.UninterruptibleUtils$String.modifiedUtf8Length(UninterruptibleUtils.java:466) [bci: 9]
Unannotated callee: java.lang.String.length() called by annotated caller com.oracle.svm.core.jdk.UninterruptibleUtils$String.toModifiedUtf8(String, Pointer, Pointer, boolean)
at com.oracle.svm.core.jdk.UninterruptibleUtils$String.toModifiedUtf8(UninterruptibleUtils.java:487) [bci: 12]

**Comment by mcraj017** [comment]
@zhengyu123 Thanks for reporting the issue, please try the following steps:
1. Use the Latest GraalVM Dev release : https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/21.3.0-dev-20210831_2241
2. Use the native-image tracing agent https://www.graalvm.org/reference-manual/native-image/Agent/ 
3. Please provide reproducer

**Comment by mcraj017** [comment]
@zhengyu123 I am closing this ticket because there is no activity for last one month
