### ISSUE TITLE
WindowsVirtualMachine ClassNotFoundException

### ISSUE THREAD

**Issue by Richard-Tang** [oracle/graal#3758]
**Describe the issue**

`sun.tools.attach.WindowsVirtualMachine` Cannot be used in `NativeImage` 

But it is normal under Java commands

```java
import java.lang.reflect.Method;

public class Main {
    public static void main(String[] args) throws Exception {
        System.loadLibrary("attach");
        Class cls = Class.forName("sun.tools.attach.WindowsVirtualMachine");
        Thread.sleep(4000);
    }
}
```

```json
[
  {
    "name": "sun.tools.attach.WindowsVirtualMachine",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
  }
]
````

```powershell
C:\Users\admin\Desktop>native-image Main -H:ReflectionConfigurationFiles=C:\User
s\admin\Desktop\config.json
[main:1756]    classlist:   3,677.13 ms,  1.16 GB
[main:1756]        (cap):   1,909.24 ms,  1.16 GB
[main:1756]        setup:   2,736.24 ms,  1.16 GB
Error: Error parsing reflection configuration in C:\Users\admin\Desktop\config.j
son:
Could not resolve sun.tools.attach.WindowsVirtualMachine for reflection configur
ation. Reason: java.lang.ClassNotFoundException: sun.tools.attach.WindowsVirtual
Machine. To allow unresolvable reflection configuration, use option -H:+AllowInc
ompleteClasspath
Verify that the configuration matches the schema described in the -H:PrintFlags=
+ output for option ReflectionConfigurationFiles.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exce
ption
[main:1756]      [total]:   6,536.86 ms,  1.16 GB
# Printing build artifacts to: C:\Users\admin\Desktop\main.build_artifacts.txt
Error: Image build request failed with exit status 1
```

**Steps to reproduce the issue**
1. **javac Main.java**
2. **native-image Main -H:ReflectionConfigurationFiles=C:\Users\admin\Desktop\config.json**

**Describe GraalVM and your environment:**
 - GraalVM version: **GraalVM CE 21.2.0 (build 25.302-b07-jvmci-21.2-b08**
 - JDK major version: **openjdk 1.8.0_302**
 - OS: **Microsoft Windows 7 6.1.7601 Service Pack 1 Build 7601**
 - Architecture: **x86**

**More details**
```
  C:\Users\admin\Desktop>native-image Main -H:ReflectionConfigurationFiles=C:\User
s\admin\Desktop\config.json --native-image-info --verbose
Executing [
'C:\Users\admin\Desktop\graalvm-ce-java8-21.2.0\jre\bin\java.exe' \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-d64 \
-XX:-UseJVMCIClassLoader \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx6871521688 \
-Duser.country=US \
-Duser.language=en \
-Dorg.graalvm.version=21.2.0 \
-Dorg.graalvm.config=CE \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
'-Djvmci.class.path.append=C:\Users\admin\Desktop\graalvm-ce-java8-21.2.0\jre\li
b\jvmci\graal.jar' \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
'-javaagent:C:\Users\admin\Desktop\graalvm-ce-java8-21.2.0\jre\lib\svm\builder\s
vm.jar' \
'-Xbootclasspath/a:C:\Users\admin\Desktop\graalvm-ce-java8-21.2.0\jre\lib\boot\g
raal-sdk.jar;C:\Users\admin\Desktop\graalvm-ce-java8-21.2.0\jre\lib\boot\graaljs
-scriptengine.jar' \
-cp \
'C:\Users\admin\Desktop\graalvm-ce-java8-21.2.0\jre\lib\svm\builder\objectfile.j
ar;C:\Users\admin\Desktop\graalvm-ce-java8-21.2.0\jre\lib\svm\builder\pointsto.j
ar;C:\Users\admin\Desktop\graalvm-ce-java8-21.2.0\jre\lib\svm\builder\svm.jar;C:
\Users\admin\Desktop\graalvm-ce-java8-21.2.0\jre\lib\jvmci\graal-management.jar;
C:\Users\admin\Desktop\graalvm-ce-java8-21.2.0\jre\lib\jvmci\graal-truffle-jfr-i
mpl.jar;C:\Users\admin\Desktop\graalvm-ce-java8-21.2.0\jre\lib\jvmci\graal.jar;C
:\Users\admin\Desktop\graalvm-ce-java8-21.2.0\jre\lib\jvmci\jvmci-api.jar;C:\Use
rs\admin\Desktop\graalvm-ce-java8-21.2.0\jre\lib\jvmci\jvmci-hotspot.jar;C:\User
s\admin\Desktop\graalvm-ce-java8-21.2.0\jre\lib\resources.jar' \
com.oracle.svm.hosted.NativeImageGeneratorRunner \
-imagecp \
'C:\Users\admin\Desktop\graalvm-ce-java8-21.2.0\jre\lib\boot\graal-sdk.jar;C:\Us
ers\admin\Desktop\graalvm-ce-java8-21.2.0\jre\lib\boot\graaljs-scriptengine.jar;
C:\Users\admin\Desktop;C:\Users\admin\Desktop\graalvm-ce-java8-21.2.0\jre\lib\sv
m\library-support.jar' \
'-H:Path=C:\Users\admin\Desktop' \
'-H:ReflectionConfigurationFiles=C:\Users\admin\Desktop\config.json' \
-H:+DumpTargetInfo \
'-H:CLibraryPath=C:\Users\admin\Desktop\graalvm-ce-java8-21.2.0\jre\lib\svm\clib
raries\windows-amd64' \
'-H:Class@explicit main-class=Main' \
'-H:Name@main-class lower case as image name=main'
]
[main:920]    classlist:   2,802.61 ms,  1.13 GB
[main:920]        (cap):   1,456.20 ms,  1.13 GB
[main:920]        setup:   2,177.08 ms,  1.13 GB
Error: Error parsing reflection configuration in C:\Users\admin\Desktop\config.j
son:
Could not resolve sun.tools.attach.WindowsVirtualMachine for reflection configur
ation. Reason: java.lang.ClassNotFoundException: sun.tools.attach.WindowsVirtual
Machine. To allow unresolvable reflection configuration, use option -H:+AllowInc
ompleteClasspath
Verify that the configuration matches the schema described in the -H:PrintFlags=
+ output for option ReflectionConfigurationFiles.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exce
ption
[main:920]      [total]:   5,040.42 ms,  1.13 GB
# Printing build artifacts to: C:\Users\admin\Desktop\main.build_artifacts.txt
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed w
ith exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1916)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1584)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1545)

        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1532)

```

**Comment by mcraj017** [comment]
@Richard-Tang Thanks for reporting the issue, please use the following:
1. Use GraalVM 21.2-java 11 or GraalVM 21.3-dev-Java 11
2. Use native-image tracing agent: https://docs.oracle.com/en/graalvm/enterprise/21/docs/reference-manual/native-image/Agent/

**Comment by jerboaa** [comment]
For JDK 8, jvmstat classes are in the `tools.jar` and needs to be added to the classpath.

**Comment by mcraj017** [comment]
@Richard-Tang does solution offered by @jerboaa solves your problem?

**Comment by mcraj017** [comment]
Closing this issue because there is no activity in last one month
