### ISSUE TITLE
Unsupported bytecode for native image for fibers-instrumented code (includes reproduction)

### ISSUE THREAD

**Issue by doctorpangloss** [oracle/graal#3759]
**Describe the issue**
The bytecode emitted by `puniverse/quasar` fiber and coroutines instrumentation cannot be compiled by `native-image`.  Includes reproduction with a carefully embedded quasar-core and instrumentation script to make it very easy for you to investigate a fix.

Fixing this issue would fix #477 and could give you a path to support fibers in dynamic languages today without Loom.

This is also related to #955 because `quasar-core` uses `VarHandle` / `MethodHandle`.

A useful fibers implementation would not need to be able to instrument at runtime so maybe some changes to `quasar-core` would be possible to Just Work on GraalVM.

**Steps to reproduce the issue**

https://github.com/hiddenswitch/quasar-fibers-bytecodes-graal

```
git clone git@github.com:hiddenswitch/quasar-fibers-bytecodes-graal.git
cd quasar-fibers-bytecodes-graal
gu install native-image
./gradlew testapp:shadowJar
native-image -jar testapp/build/libs/testapp-all.jar -H:+ReportExceptionStackTraces --no-fallback --native-image-info --verbose &>output.log
```

[output.log](https://github.com/oracle/graal/files/4738894/output.log)

These errors are related to the implementation of `quasar-core` rather than the instrumentation:

```
./gradlew uninstrumentedtestapp:shadowJar
native-image -jar uninstrumentedtestapp/build/libs/uninstrumentedtestapp-all.jar -H:+ReportExceptionStackTraces --no-fallback --native-image-info --verbose &>output2.log
```

[output2.log](https://github.com/oracle/graal/files/4738908/output2.log)

# Environment

***GraalVM version:***

```
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08)
OpenJDK 64-Bit Server VM GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08, mixed mode, sharing)
```

 - JDK major version: **11**
 - OS: **macOS Catalina** and **Windows 10**
 - Architecture: **AMD64**

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for taking the time to report this, the GraalVM version you're using is obsolete, could you please try with the latest snapshot build of 21.3.0, please let us know if the issue is still reproducible with the latest build

**Comment by doctorpangloss** [comment]
I tested it with 21.2.0 and it's substantively all the same errors. I fixed the Gradle wrapper issue and the reproduction is updated. You should be able to test. This error exists on 21.3.0.

**Comment by doctorpangloss** [comment]
Substantively the issue is:

```
Call path from entry point to co.paralleluniverse.strands.dataflow.Val$1.run(): 
	at co.paralleluniverse.strands.dataflow.Val$1.run(Val.java)
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:42)
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:30)
	at co.paralleluniverse.fibers.Fiber.run(Fiber.java:1089)
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1084)
	at co.paralleluniverse.fibers.Fiber.execStackTrace1(Fiber.java:902)
	at co.paralleluniverse.fibers.Fiber.execStackTrace(Fiber.java:1282)
	at co.paralleluniverse.fibers.Fiber.getStackTrace(Fiber.java:1522)
	at co.paralleluniverse.fibers.FiberTimedScheduler.reportProblemFibers(FiberTimedScheduler.java:446)
	at co.paralleluniverse.fibers.FiberTimedScheduler.work(FiberTimedScheduler.java:140)
	at co.paralleluniverse.fibers.FiberTimedScheduler$1.run(FiberTimedScheduler.java:81)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Original exception that caused the problem: org.graalvm.compiler.core.common.PermanentBailoutException: Exception handler can be reached by both normal and exceptional control flow
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BciBlockMapping.addSuccessor(BciBlockMapping.java:1122)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BciBlockMapping.iterateOverBytecodes(BciBlockMapping.java:827)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BciBlockMapping.build(BciBlockMapping.java:721)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BciBlockMapping.create(BciBlockMapping.java:1561)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1004)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:982)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:214)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:225)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:352)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:322)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:311)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:112)
	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:228)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:470)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:542)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:530)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

on all versions of GraalVM.

**Comment by doctorpangloss** [comment]
> Hi, thank you for taking the time to report this, the GraalVM version you're using is obsolete, could you please try with the latest snapshot build of 21.3.0? please let us know if the issue is still reproducible with the latest build

@oubidar-Abderrahim any update on this? It's the same in 21.3.0 snapshot build.

**Comment by oubidar-Abderrahim** [comment]
The issue is tracked internally on GR-33715, we reach the freeze for 21.3.0 so most probably this issue will be fixed in later versions

**Comment by doctorpangloss** [comment]
Because Java 19 supports virtual threads, I am closing this issue. Quasar is obsolete.
