### ISSUE TITLE
[native-image] NPE on HelloWorld jar if "Class-Path: ." is specified in the jar's MANIFEST.MF

### ISSUE THREAD

**Issue by churlinpr** [oracle/graal#376]
native-image crashes with the NPE below when launched on an HelloWorld program whose jar has been generated by Eclipse's _Export > Runnable Jar_ because the generated MANIFEST.MF contains "Class-Path: ." (i.e. removing this entry from MANIFEST.MF **solves the problem**).

* Here's the concerned jar: http://schplaf.org/hgames/substratevm_jaxb.jar
* Here's the corresponding project's source as an Eclipse project: http://schplaf.org/hgames/substratevm_jaxb.tgz 

Here's the NPE (on linux 64, graal repo at 00bc04ebac9ef2be0a4917dc09ab3b522c5acc87 (the tip at the moment I'm writing)):

```
> native-image --no-server -jar substratevm_jaxb.jar 
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.lang.Throwable.<init>(Throwable.java:310)
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:89)
	at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)
	at com.oracle.svm.reflect.proxies.Proxy_1_NativeImage_main.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:199)
	at Lcom/oracle/svm/core/code/CEntryPointCallStubs;.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Caused by: java.lang.NullPointerException
	at java.lang.Throwable.<init>(Throwable.java:250)
	at java.lang.Exception.<init>(Exception.java:54)
	at java.lang.RuntimeException.<init>(RuntimeException.java:51)
	at java.lang.NullPointerException.<init>(NullPointerException.java:60)
	at com.oracle.svm.core.snippets.SnippetRuntime.throwNullPointerException(SnippetRuntime.java:206)
	at sun.nio.fs.UnixPath.getParent(UnixPath.java:43)
	at com.oracle.svm.driver.DefaultOptionHandler.handleJarFileArg(DefaultOptionHandler.java:214)
	at com.oracle.svm.driver.DefaultOptionHandler.consume(DefaultOptionHandler.java:100)
	at com.oracle.svm.driver.NativeImage.processNativeImageArgs(NativeImage.java:729)
	at com.oracle.svm.driver.NativeImage.completeImageBuildArgs(NativeImage.java:424)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:565)
	... 4 more
```

**Comment by olpaw** [comment]
Thanks for your report. This will be fixed on master.

**Comment by olpaw** [comment]
This is already fixed on master (by commit https://github.com/oracle/graal/commit/9df2b6a25bebf015d95859f4c555f58f431653d0)

**Comment by churlinpr** [comment]
Indeed, checkouting https://github.com/oracle/graal/releases/tag/JDK-8199755 circumvents the bug.
