### ISSUE TITLE
Build break with OpenJDK 11/17

### ISSUE THREAD

**Issue by jerboaa** [oracle/graal#3778]
A graal vm master build from source fails with OpenJDK 16 or (via mandrel) for OpenJDK 11. The offending commit seems to be cc11ae1d1fad550424b1fdc0a6cf7e9d6815874a which a) removed some flags configs for older JDKs which breaks the JDK 16 build. I suppose that's OK since JDK 17 GAs this week b) re-ordered `builderJavaArgs` so that `-XX-UseJVMCICompiler` comes first in the native image generator invocation.  That latter parts needs to have `-XX:+UnlockExperimentalVMOptions` as a preceeding arg. Using that, gets us further, but not quite done.

Failure for JDK 16 is:
```
[...]
berOfThreads=8 -H:Path=/disk/graal/upstream-sources/graalvm/sdk/mxbuild/linux-amd64/native-image.image
Apply jar:file:///disk/graal/upstream-sources/graalvm/sdk/mxbuild/linux-amd64/GRAALVM_76BF0784AB_JAVA16_STAGE1/graalvm-76bf0784ab-java16-21.3.0-dev/lib/graalvm/svm-driver.jar!/META-INF/native-image/com.oracle.substratevm/svm-driver/native-image.properties
Error: Image building not supported for Java version 16.0.2 in /disk/graal/upstream-sources/graalvm/sdk/mxbuild/linux-amd64/GRAALVM_76BF0784AB_JAVA16_STAGE1/graalvm-76bf0784ab-java16-21.3.0-dev with VM configuration "OpenJDK 64-Bit Server VM". Update SubstrateCompilerFlagsBuilder.compute_graal_compiler_flags_map() in mx_substratevm.py to add a configuration for a new Java version.

Building native-image.image: Failed due to error: 1
Building native-image.image failed
1 build tasks failed
```

Failure for JDK 17/11 is:

```
[...]
DEBUG [OperatingSystem] Execute [.\mandrel-java17-21.3.0-devc4f6af1e281\lib\svm\bin\native-image.cmd, --macro:native-image-agent-library] in C:\workspace\workspace\mandrel-maste---c3557c9d
Error: VM option 'UseJVMCICompiler' is experimental and must be enabled via -XX:+UnlockExperimentalVMOptions.
Error: The unlock option must precede 'UseJVMCICompiler'.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Error: Image build request failed with exit status 1
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 1
    at OperatingSystem.exec(build.java:1733)
    at build.buildAgents(build.java:188)
    at build.main(build.java:170)
Caused by: java.lang.RuntimeException: Failed, exit code: 1
    at OperatingSystem.exec(build.java:1718)
    at build.buildAgents(build.java:188)
    at build.main(build.java:170)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:419)
    at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:192)
    at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:132)
```

**Comment by jerboaa** [comment]
This diff gets me further, but than fails as well (on building the native diagnostic agent):

```
diff --git a/substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java b/substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
index cb7bb51e26a..7eebef1c561 100644
--- a/substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
+++ b/substratevm/src/com.oracle.svm.driver/src/com/oracle/svm/driver/NativeImage.java
@@ -485,6 +485,7 @@ public class NativeImage {
             if (useJVMCINativeLibrary) {
                 builderJavaArgs.add("-XX:+UseJVMCINativeLibrary");
             } else {
+                builderJavaArgs.add("-XX:+UnlockExperimentalVMOptions");
                 builderJavaArgs.add("-XX:-UseJVMCICompiler");
             }
 
@@ -538,7 +539,11 @@ public class NativeImage {
          * @return entries for the --upgrade-module-path of the image builder
          */
         public List<Path> getBuilderUpgradeModulePath() {
-            return getJars(rootDir.resolve(Paths.get("lib", "jvmci")), "graal", "graal-management");
+            List<Path> result = new ArrayList<>();
+            result.addAll(getJars(rootDir.resolve(Paths.get("lib", "jvmci")), "graal", "graal-management"));
+            result.addAll(getJars(rootDir.resolve(Paths.get("lib", "jvmci")), "graal-sdk", "enterprise-graal"));
+            result.addAll(getJars(rootDir.resolve(Paths.get("lib", "truffle")), "truffle-api"));
+            return result;
         }
 
         /**
```

**Comment by jerboaa** [comment]
Build failure with the above patch is:

```
Executing [
/disk/graal/upstream-sources/graalvm/mandrel-build/bin/java \
-XX:+UnlockExperimentalVMOptions \
-XX:-UseJVMCICompiler \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
--add-exports=java.base/com.sun.crypto.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.event=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.loader=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.logger=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.misc=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.module=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=java.base/jdk.internal.org.objectweb.asm=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.org.xml.sax.helpers=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.perf=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.ref=org.graalvm.nativeimage.objectfile \
--add-exports=java.base/jdk.internal.util.xml.impl=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.util.xml=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.invoke.util=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.nio.ch=org.graalvm.nativeimage.objectfile \
--add-exports=java.base/sun.reflect.annotation=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.reflectiveObjects=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.repository=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.tree=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.jca=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.util=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.text.spi=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.calendar=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.locale.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.resources=org.graalvm.nativeimage.builder \
--add-exports=java.xml.crypto/org.jcp.xml.dsig.internal.dom=org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.aarch64=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.amd64=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.site=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.stack=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.common=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.aarch64=jdk.internal.vm.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.amd64=jdk.internal.vm.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.sparc=jdk.internal.vm.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.meta=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.runtime=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.services.internal=jdk.internal.vm.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.services=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.sparc=jdk.internal.vm.compiler \
--add-exports=jdk.jfr/jdk.jfr.events=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal.consumer=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal.handlers=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal.jfc=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal=org.graalvm.nativeimage.builder \
-Xss10m \
-Xms1g \
-Xmx14g \
-Duser.country=US \
-Duser.language=en \
-Djava.awt.headless=true \
-Dorg.graalvm.version=21.3.0-dev \
'-Dorg.graalvm.config=Mandrel Distribution' \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
--upgrade-module-path \
/disk/graal/upstream-sources/graalvm/mandrel-build/lib/jvmci/graal.jar:/disk/graal/upstream-sources/graalvm/mandrel-build/lib/jvmci/graal-sdk.jar:/disk/graal/upstream-sources/graalvm/mandrel-build/lib/truffle/truffle-api.jar \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=jdk.internal.vm.compiler \
-Dorg.graalvm.version=21.3.0-dev \
-javaagent:/disk/graal/upstream-sources/graalvm/mandrel-build/lib/svm/builder/svm.jar \
--module-path \
/disk/graal/upstream-sources/graalvm/mandrel-build/lib/svm/builder/pointsto.jar:/disk/graal/upstream-sources/graalvm/mandrel-build/lib/svm/builder/objectfile.jar:/disk/graal/upstream-sources/graalvm/mandrel-build/lib/svm/builder/svm.jar \
--module \
org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner \
-imagemp \
/disk/graal/upstream-sources/graalvm/mandrel-build/lib/graalvm/jvmti-agent-base.jar:/disk/graal/upstream-sources/graalvm/mandrel-build/lib/graalvm/svm-agent.jar:/disk/graal/upstream-sources/graalvm/mandrel-build/lib/graalvm/svm-configure.jar:/disk/graal/upstream-sources/graalvm/mandrel-build/lib/graalvm/svm-driver.jar:/disk/graal/upstream-sources/graalvm/mandrel-build/lib/svm/library-support.jar \
-H:Path=/disk/graal/upstream-sources/mandrel-packaging \
'-H:Name@jar:file:///disk/graal/upstream-sources/graalvm/mandrel-build/lib/graalvm/svm-driver.jar!/META-INF/native-image/com.oracle.substratevm/svm-driver/native-image.properties=native-image' \
'-H:-ParseRuntimeOptions@jar:file:///disk/graal/upstream-sources/graalvm/mandrel-build/lib/graalvm/svm-driver.jar!/META-INF/native-image/com.oracle.substratevm/svm-driver/native-image.properties' \
'-H:ClassInitialization@jar:file:///disk/graal/upstream-sources/graalvm/mandrel-build/lib/graalvm/svm-driver.jar!/META-INF/native-image/com.oracle.substratevm/svm-driver/native-image.properties=com.oracle.svm.driver:build_time' \
-H:Name=libnative-image-agent \
-H:Path=/disk/graal/upstream-sources/graalvm/mandrel-build/lib/svm/macros/native-image-agent-library/../../.. \
-H:FallbackThreshold@--macro:native-image-agent-library=0 \
-H:ClassInitialization@--macro:native-image-agent-library=org:build_time,com:build_time,net:build_time,jdk:build_time,javax:build_time,java:build_time,sun:build_time,apple:build_time \
-H:+AssertInitializationSpecifiedForAllClasses@--macro:native-image-agent-library \
-H:+EnforceMaxRuntimeCompileMethods@--macro:native-image-agent-library \
-H:+SharedLibrary@--macro:native-image-agent-library \
'-H:Features@--macro:native-image-agent-library=com.oracle.svm.agent.NativeImageAgent$RegistrationFeature' \
-H:EnableURLProtocols@--macro:native-image-agent-library=jar \
-H:AddExports@--macro:native-image-agent-library=jdk.internal.vm.ci/jdk.vm.ci.aarch64=org.graalvm.nativeimage.driver \
-H:AddExports@--macro:native-image-agent-library=jdk.internal.vm.ci/jdk.vm.ci.amd64=org.graalvm.nativeimage.driver \
-H:AddExports@--macro:native-image-agent-library=jdk.internal.vm.ci/jdk.vm.ci.code=org.graalvm.nativeimage.driver \
-H:AddExports@--macro:native-image-agent-library=jdk.internal.vm.ci/jdk.vm.ci.meta=org.graalvm.nativeimage.agent.tracing,org.graalvm.nativeimage.configure \
-H:FallbackThreshold=0 \
-H:CLibraryPath=/disk/graal/upstream-sources/graalvm/mandrel-build/lib/svm/clibraries/linux-amd64
]
[libnative-image-agent:159316]    classlist:   1,316.04 ms,  0.96 GB
[libnative-image-agent:159316]        setup:     385.94 ms,  0.96 GB
Error: Substitution target for com.oracle.svm.core.jdk.Target_jdk_nashorn_api_scripting_ClassFilter is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
[libnative-image-agent:159316]      [total]:   1,756.02 ms,  0.96 GB
# Printing build artifacts to: /disk/graal/upstream-sources/graalvm/mandrel-build/lib/svm/macros/native-image-agent-library/../../../libnative-image-agent.build_artifacts.txt
```

**Comment by jerboaa** [comment]
PR #3793 fixes this. Please review when you get a chance!

**Comment by olpaw** [comment]
Hi @jerboaa ,

sorry for responding late. I just saw this issue. Feel free to ping me on public slack if you need my attention on issues like this.

Re:
> a) removed some flags configs for older JDKs which breaks the JDK 16 build. I suppose that's OK since JDK 17 GAs this week

Exactly as you anticipated. Since since JDK 17 gets released today and since it's an LTS release all versions between 11 and 17 are obsolete now. Thus I removed the obsolete configs.

> that -XX-UseJVMCICompiler comes first in the native image generator invocation. That latter parts needs to have -XX:+UnlockExperimentalVMOptions as a preceeding arg.

I agree this needs to be changed. `-XX:+UnlockExperimentalVMOptions` should be first.

I will look into https://github.com/oracle/graal/pull/3793 for the remaining feedback.

**Comment by jerboaa** [comment]
> sorry for responding late.

No worries.

> I just saw this issue. Feel free to ping me on public slack if you need my attention on issues like this.

@olpaw OK, thanks. Will keep that in mind. It's good to know.

> Re:
> 
> > a) removed some flags configs for older JDKs which breaks the JDK 16 build. I suppose that's OK since JDK 17 GAs this week
> 
> Exactly as you anticipated. Since since JDK 17 gets released today and since it's an LTS release all versions between 11 and 17 are obsolete now. Thus I removed the obsolete configs.
> 
> > that -XX-UseJVMCICompiler comes first in the native image generator invocation. That latter parts needs to have -XX:+UnlockExperimentalVMOptions as a preceeding arg.
> 
> I agree this needs to be changed. `-XX:+UnlockExperimentalVMOptions` should be first.
> 
> I will look into #3793 for the remaining feedback.

Thanks very much!
