### ISSUE TITLE
binary obtained with native-image crashes with ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory

### ISSUE THREAD

**Issue by churlinpr** [oracle/graal#379]
Compiling this code with native-image (with `native-image  --no-server -jar substratevm_jaxb.jar`):

```java
public class Main {

	@XmlRootElement
	public static class Data {
		@XmlAttribute
		private int x;
	}

	public static void main(String[] args) {
		JAXB.marshal(new Data(), System.out);
	}

}
```

yields a binary that crashes as follows (whereas it works fine with `java -jar` on java 8):

```
./substratevm_jaxb 
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.lang.Throwable.<init>(Throwable.java:310)
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:89)
	at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)
	at com.oracle.svm.reflect.proxies.Proxy_1_Main_main.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:199)
	at Lcom/oracle/svm/core/code/CEntryPointCallStubs;.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Caused by: javax.xml.bind.DataBindingException: javax.xml.bind.JAXBException
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
	at java.lang.Throwable.<init>(Throwable.java:310)
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.RuntimeException.<init>(RuntimeException.java:96)
	at javax.xml.bind.DataBindingException.<init>(DataBindingException.java:45)
	at javax.xml.bind.JAXB._marshal(JAXB.java:574)
	at javax.xml.bind.JAXB.marshal(JAXB.java:432)
	at substratevm_jaxb.Main.main(Main.java:25)
	... 4 more
Caused by: javax.xml.bind.JAXBException
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Exception.<init>(Exception.java:66)
	at javax.xml.bind.JAXBException.<init>(JAXBException.java:106)
	at javax.xml.bind.JAXBException.<init>(JAXBException.java:83)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:226)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:462)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:641)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:584)
	at javax.xml.bind.JAXB$Cache.<init>(JAXB.java:112)
	at javax.xml.bind.JAXB.getContext(JAXB.java:139)
	at javax.xml.bind.JAXB._marshal(JAXB.java:563)
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
	at java.lang.Throwable.<init>(Throwable.java:287)
	at java.lang.Exception.<init>(Exception.java:84)
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:75)
	at java.lang.ClassNotFoundException.<init>(ClassNotFoundException.java:82)
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:49)
	at com.oracle.svm.core.hub.DynamicHub.forName(DynamicHub.java:904)
	at javax.xml.bind.ContextFinder.safeLoadClass(ContextFinder.java:577)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:224)
	... 12 more
```

I suppose that part of JAXB's implementation is not supported out of the box, but there's no warning whatsoever. Is there a way to circumvent this issue ? (by adding something to the classpath ?)

For convenience, here's this class' source as an Eclipse project: https://www.schplaf.org/hgames/graal/substravevm_jaxb.tgz

**Comment by plutext** [comment]
I can report that using the JAXB reference implementation (v2.3.2) works for me.  I'm using rc15.  I didn't try com.sun.xml.internal.bind

**Comment by wirdman** [comment]
@plutext how exactly have you set this up to work for you? what do your dependencies look like (pom.xml?) ? cause for me it's the same error as @churlinpr . Have you managed to work around this issue?

**Comment by fernando-valdez** [comment]
This issue can be fixed by compiling native-image with the following command:
`native-image -H:ReflectionConfigurationFiles=reflect.json -H:-UseServiceLoaderFeature --no-server --no-fallback --report-unsupported-elements-at-runtime -jar YourFile.jar`

Also, include this config file (reflect.json):
`[
  {
    "name" : "com.sun.xml.internal.bind.v2.ContextFactory",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredClasses" : true,
    "allPublicClasses" : true
  },
  {
    "name" : "classes.Main$Data",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredClasses" : true,
    "allPublicClasses" : true
  }
 ]`

**Comment by jramirez-isc** [comment]
@churlinpr Here you can find a working example using your code: https://github.com/jramirez-isc/demo-jaxb-native-image

**Comment by churlinpr** [comment]
Thank you @fernando-valdez and @jramirez-isc, fix very much appreciated!

**Comment by vjovanov** [comment]
Thanks, but I would not close this issue yet: We need to include the fix to the next GraalVM release so when `com.sun.xml` is used these configs are added automatically. Also, we need to add tests so changes to this package don't break our support.

**Comment by crowlogic** [comment]
Has there been any progress with this? I am still having problems getting jaxb and native-image to work and reported an issue at https://github.com/oracle/graal/issues/2132 

What needs to be done to implement this feature? I've checked out the graal source but would need some instructions on how to go about getting mx to work since thats new to me

**Comment by vjovanov** [comment]
Yes, we have tried supporting the whole library and doing that is not possible without using the agent. Since full support was not possible we have extended the agent with the JDK support and decided to go with the agent-only support. 

To make it work with the agent you need to pass the special filter file: 
```
{
  "rules": [
    {"includeClasses": "javax.xml.**"},
    {"includeClasses": "com.sun.xml.**"},
    {"excludeClasses": "com.sun.xml.internal.bind.v2.runtime.reflect.opt.Injector"}
  ]
}
```
Then you can include that file with the following command: 
```
-agentlib:native-image-agent=config-output-dir=$CONFIG_DIR,caller-filter-file=$FILTER_FILE_PATH
```

Let us know how it goes.
\CC @gradinac @arodionov

**Comment by crowlogic** [comment]
@vjovanov native-image-agent: ```
unsupported option: 'caller-filter-file=/home/stephen/b2tf/filter.json'. Please read CONFIGURE.md.
Error occurred during initialization of VM
agent library failed to init: native-image-agent
```

**Comment by vjovanov** [comment]
This flag will be available from the 20.0 release: 

https://github.com/graalvm/graalvm-ce-builds/releases

**Comment by mipastgt** [comment]
I do not understand how this is ever going to work. If you use the agent in this way, you tune your code to read/write one (or more) particular XML file(s) but who tells you that you have covered all possibilities? As soon as a user tries to read/write another file, this may fail.

**Comment by crowlogic** [comment]
Even if it does work it does not fix the static initializer problem

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Mailaender** [comment]
I can confirm that this is still an issue:

```
~/Downloads/graalvm-ce-java11-22.0.0.2/lib/svm/bin/native-image -cp ~/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:~/.m2/repository/org/apache/commons/commons-csv/1.4/commons-csv-1.4.jar:~/.m2/repository/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar:~/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/3.0.0/jakarta.xml.bind-api-3.0.0.jar:~/.m2/repository/com/sun/activation/jakarta.activation/2.0.0/jakarta.activation-2.0.0.jar:~/.m2/repository/com/sun/xml/bind/jaxb-impl/3.0.0/jaxb-impl-3.0.0.jar:~/.m2/repository/com/sun/xml/bind/jaxb-core/3.0.0/jaxb-core-3.0.0.jar:~/Entwicklung/Eclipse/Lablicate/converter-standalone/lablicate/standalone/target/standalone-0.0.1-SNAPSHOT.jar -H:ReflectionConfigurationFiles=reflect.json -H:-UseServiceLoaderFeature --no-server --no-fallback --report-unsupported-elements-at-runtime -H:IncludeResourceBundles=jakarta.xml.bind.Messages -H:Class=my.project.Main
Warning: Ignoring server-mode native-image argument --no-server.
========================================================================================================================
GraalVM Native Image: Generating 'my.project'...
========================================================================================================================
[1/7] Initializing...
                                                                                    (2,9s @ 0,18GB)
Error: Error parsing reflection configuration in ~/Project/standalone/reflect.json:
Could not resolve com.sun.xml.bind.v2.ContextFactory for reflection configuration. Reason: java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory. To allow unresolvable reflection configuration, use option --allow-incomplete-classpath
```

pom.xml

```xml
<dependency>
	<groupId>jakarta.xml.bind</groupId>
	<artifactId>jakarta.xml.bind-api</artifactId>
	<version>3.0.0</version>
</dependency>
<dependency>
	<groupId>com.sun.xml.bind</groupId>
	<artifactId>jaxb-impl</artifactId>
	<version>3.0.0</version>
	<scope>runtime</scope>
</dependency>

[...]

<buildArgs>
	<buildArg>-H:ReflectionConfigurationFiles=reflect.json</buildArg>
	<buildArg>-H:-UseServiceLoaderFeature</buildArg>
	<buildArg>--no-server</buildArg>
	<buildArg>--no-fallback</buildArg>
	<buildArg>--report-unsupported-elements-at-runtime</buildArg>
	<buildArg>-H:IncludeResourceBundles=jakarta.xml.bind.Messages</buildArg>
</buildArgs>
```

reflect.json

```json
[
  {
    "name" : "com.sun.xml.bind.v2.ContextFactory",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredClasses" : true,
    "allPublicClasses" : true
  }
]
```

I tried other configurations with older JAXB implementation, but it will always crash runtime or in this case, during the build. The same project runs fine when built with Maven and executed through the Eclipse IDE.

**Comment by Mailaender** [comment]
Note: downgrading to 19.3.0 as suggested in https://github.com/jramirez-isc/demo-jaxb-native-image fixes it.

**Comment by rodrigar-mx** [comment]
Hi @Mailaender. Could you please update the sample project you shared (https://github.com/jramirez-isc/demo-jaxb-native-image) so it compiles with java11 or java17.  We are currently removing the support for java8.

**Comment by Mailaender** [comment]
I assume https://github.com/jramirez-isc/demo-jaxb-native-image is already made for Java 11. On Java 8 all those JAXB runtime dependency problems wouldn't occur in the first place.

**Comment by rodrigar-mx** [comment]
If I use Java 11, I cannot build the fat jar.
```
rodrigo@rodrigo-mac demo-jaxb-native-image % ./gradlew clean build fatJar

> Task :compileJava FAILED
/Users/rodrigo/Documents/OracleCloud/Oracle Content/issues/gs-338/demo-jaxb-native-image/src/main/java/classes/Main.java:3: error: package javax.xml.bind does not exist
import javax.xml.bind.JAXB;
                     ^
/Users/rodrigo/Documents/OracleCloud/Oracle Content/issues/gs-338/demo-jaxb-native-image/src/main/java/classes/Main.java:4: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlAttribute;
                                ^
/Users/rodrigo/Documents/OracleCloud/Oracle Content/issues/gs-338/demo-jaxb-native-image/src/main/java/classes/Main.java:5: error: package javax.xml.bind.annotation does not exist
import javax.xml.bind.annotation.XmlRootElement;
                                ^
/Users/rodrigo/Documents/OracleCloud/Oracle Content/issues/gs-338/demo-jaxb-native-image/src/main/java/classes/Main.java:9: error: cannot find symbol
        @XmlRootElement
         ^
  symbol:   class XmlRootElement
  location: class Main
/Users/rodrigo/Documents/OracleCloud/Oracle Content/issues/gs-338/demo-jaxb-native-image/src/main/java/classes/Main.java:11: error: cannot find symbol
                @XmlAttribute
                 ^
  symbol:   class XmlAttribute
  location: class Data
/Users/rodrigo/Documents/OracleCloud/Oracle Content/issues/gs-338/demo-jaxb-native-image/src/main/java/classes/Main.java:16: error: cannot find symbol
                JAXB.marshal(new Data(), System.out);
                ^
  symbol:   variable JAXB
  location: class Main
6 errors

FAILURE: Build failed with an exception.
```

**Comment by Mailaender** [comment]
I created a broken example at https://github.com/Mailaender/jaxb-native-image-bug and provided a workaround to showcase that this used to work in earlier versions.

**Comment by mipastgt** [comment]
@rodrigar-mx How is that supposed to work if you don't use the jar-with-dependencies?

**Comment by rodrigar-mx** [comment]
Ok. I did not know I needed to run the mvn build with the native image profile to get the executable jar for the application. Anyway, I was able build the native image and run it successfully by following these steps:
1. run the agent, after building `example-0.0.1-SNAPSHOT-jar-with-dependencies.jar` : `java -agentlib:native-image-agent=config-output-dir=META-INF/native-image -jar  target/example-0.0.1-SNAPSHOT-jar-with-dependencies.jar `
2. build the native image using the files generated by the agent:  `native-image -H:ConfigurationFileDirectories=META-INF/native-image --no-fallback -jar target/example-0.0.1-SNAPSHOT-jar-with-dependencies.jar main` (run in terminal)
3.  run the native image: 
```
rodrigo@rodrigo-mac jaxb-native-image-bug % ./main
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<data x="0"/>
```
java version:
```
openjdk version "11.0.14" 2022-01-18
OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 11.0.14+9-jvmci-22.0-b05)
OpenJDK 64-Bit Server VM GraalVM CE 22.0.0.2 (build 11.0.14+9-jvmci-22.0-b05, mixed mode, sharing)

```
Could you please try this out.

**Comment by Mailaender** [comment]
Can you send a patch for the https://github.com/Mailaender/jaxb-native-image-bug/blob/master/pom.xml for a reproducible way to solve this?

**Comment by rodrigar-mx** [comment]
@Mailaender in my previous comment I shared the steps I took to build and run the native image without errors. Please try that, and then incorporate it to your pom file. Before that, change your native image plugin. The new supported plugin is 
```
  <groupId>org.graalvm.buildtools</groupId>
  <artifactId>native-maven-plugin</artifactId>
```
More info [here](https://graalvm.github.io/native-build-tools/latest/maven-plugin.html).

**Comment by Mailaender** [comment]
I can verify that using the command line options do just work.

The Maven build after https://github.com/Mailaender/jaxb-native-image-bug/commit/e95b2ed039f41a25d520c211f29b5ab30cf78025 stills fails at runtime:

```
Exception in thread "main" jakarta.xml.bind.DataBindingException: jakarta.xml.bind.JAXBException: Implementation of Jakarta XML Binding-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory]
        at jakarta.xml.bind.JAXB._marshal(JAXB.java:558)
        at jakarta.xml.bind.JAXB.marshal(JAXB.java:416)
        at classes.Main.main(Main.java:16)
Caused by: jakarta.xml.bind.JAXBException: Implementation of Jakarta XML Binding-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory]
        at jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:232)
        at jakarta.xml.bind.ContextFinder.find(ContextFinder.java:375)
        at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
        at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
        at jakarta.xml.bind.JAXB$Cache.<init>(JAXB.java:96)
        at jakarta.xml.bind.JAXB.getContext(JAXB.java:123)
        at jakarta.xml.bind.JAXB._marshal(JAXB.java:547)
        ... 2 more
Caused by: java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:54)
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:141)
        at jakarta.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:92)
        at jakarta.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:125)
        at jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:230)
        ... 8 more
```

**Comment by Mailaender** [comment]
I just noticed that https://github.com/Mailaender/jaxb-native-image-bug/pull/1 only "worked" because it created fallback images as I deleted the reflection configuration.

**Comment by Mailaender** [comment]
Using https://github.com/Mailaender/jaxb-native-image-bug/tree/master/META-INF/native-image also does not seem to help.

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.<init>(RuntimeModelBuilder.java:55)
        at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:403)
        at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:251)
        at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:77)
        at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1111)
        at org.glassfish.jaxb.runtime.v2.ContextFactory.createContext(ContextFactory.java:140)
        at org.glassfish.jaxb.runtime.v2.JAXBContextFactory.createContext(JAXBContextFactory.java:36)
        at jakarta.xml.bind.ContextFinder.find(ContextFinder.java:358)
        at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
        at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
        at jakarta.xml.bind.JAXB$Cache.<init>(JAXB.java:96)
        at jakarta.xml.bind.JAXB.getContext(JAXB.java:123)
        at jakarta.xml.bind.JAXB._marshal(JAXB.java:547)
        at jakarta.xml.bind.JAXB.marshal(JAXB.java:416)
        at classes.Main.main(Main.java:16)
Caused by: java.lang.IllegalStateException: ReflectionNavigator.getInstance can't be found
        at org.glassfish.jaxb.runtime.v2.model.impl.Utils$1.run(Utils.java:54)
        at org.glassfish.jaxb.runtime.v2.model.impl.Utils$1.run(Utils.java:46)
        at java.security.AccessController.doPrivileged(AccessController.java:89)
        at org.glassfish.jaxb.runtime.v2.model.impl.Utils.<clinit>(Utils.java:45)
        ... 15 more
```

**Comment by lisandrod** [comment]
Add `ReflectionNavigator` to your `reflect.json` file. I've ranned through a gamut of issues trying to get jaxb to work with graalvm. Most are fixed if you add the jaxb files to the reflect.json file. However, i am running into a marshal issue where the JaxbContext either complains that it cant find the `jakarta.xml.bind.JAXBException: class <insert-some-class> nor any of its super class is known to this context` when i only add the objectfactory class or if i add the package name it just saids it doesnt find any classes. If i add the classes explicitly it just complains on XmlType.factoryClass(). A bit frustrating but i hope this helps some poor soul that has to experience this.

**Comment by damnms** [comment]
@lisandrod can you give a bit more information about that?
i tried to create a reflect json with 
/home/$USER/Downloads/graalvm-jdk-20.0.1+9.1/bin/java -agentlib:native-image-agent=config-output-dir=META-INF/native-image src/main/java/org/gitlab/myproject/adapters/Console ReflectionNavigator getInstance

but it failed with a ClassNotFoundException.

**Comment by crowlogic** [comment]
More trouble than it's worth
