### ISSUE TITLE
Error parsing JNI configuration - Field java.net.Inet6Address.cached_scope_id not found

### ISSUE THREAD

**Issue by makingthematrix** [oracle/graal#3796]
**Describe the issue**

With GraalVM CE 21.3.0-dev-20210913_2001 building a native image of a JavaFX app fails in an early stage of compilation with the following error:
```
[INFO] [SUB] Field java.net.Inet6Address.cached_scope_id not found. To allow unresolvable reflection configuration, use option --allow-incomplete-classpath
``` 
The failure might be also on the Gluon side, but I wanted to let you know first. When I used GraalVM CE 21.2.0 all worked fine with exactly the same version of the gluonfx maven plugin.
Source code used to reproduce this is available on my GitHub repo.

**Steps to reproduce the issue**
set GraalVM CE 21.3.0-dev-20210913_2001 as your JDK
```
git clone git@github.com:makingthematrix/scalaonandroid.git
git checkout java17_update
cd scalaonandroid/HelloFXML
mvn gluonfx:build
```
**Describe GraalVM and your environment:**
 - GraalVM version " GraalVM CE 21.3.0-dev-20210913_2001
 - JDK major version: 17
 - OS: Linux Mint 20.1 Cinnamon
 - Architecture: AMD64

**More details**
```
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< scalaonandroid:hellofxml >----------------------
[INFO] Building HelloFXML 0.0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- gluonfx-maven-plugin:1.0.5:build (default-cli) @ hellofxml ---
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< scalaonandroid:hellofxml >----------------------
[INFO] Building HelloFXML 0.0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] >>> gluonfx-maven-plugin:1.0.5:compile (default-cli) > process-classes @ hellofxml >>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hellofxml ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- scala-maven-plugin:4.5.3:add-source (scala-compile) @ hellofxml ---
[INFO] Add Source directory: /home/makingthematrix/workspace/scalaonandroid/HelloFXML/src/main/scala
[INFO] Add Test Source directory: /home/makingthematrix/workspace/scalaonandroid/HelloFXML/src/test/scala
[INFO] 
[INFO] --- scala-maven-plugin:4.5.3:compile (scala-compile) @ hellofxml ---
[INFO] Using incremental compilation using Mixed compile order
[INFO] Compiler bridge file: /home/makingthematrix/.sbt/1.0/zinc/org.scala-sbt/org.scala-sbt-compiler-bridge_2.13-1.5.5-bin_2.13.6__61.0-1.5.5_20210607T021730.jar
[INFO] compiling 2 Scala sources to /home/makingthematrix/workspace/scalaonandroid/HelloFXML/target/classes ...
[INFO] done compiling
[INFO] compile in 3.5 s
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ hellofxml ---
[INFO] Changes detected - recompiling the module!
[INFO] 
[INFO] <<< gluonfx-maven-plugin:1.0.5:compile (default-cli) < process-classes @ hellofxml <<<
[INFO] 
[INFO] 
[INFO] --- gluonfx-maven-plugin:1.0.5:compile (default-cli) @ hellofxml ---
[Tue Sep 14 19:10:25 CEST 2021][INFO] ==================== COMPILE TASK ====================
             _______  ___      __   __  _______  __    _
            |       ||   |    |  | |  ||       ||  |  | |
            |    ___||   |    |  | |  ||   _   ||   |_| |
            |   | __ |   |    |  |_|  ||  | |  ||       |
            |   ||  ||   |___ |       ||  |_|  ||  _    |
            |   |_| ||       ||       ||       || | |   |
            |_______||_______||_______||_______||_|  |__|

    Access to the latest docs, tips and tricks and more info on
    how to get support? Register your usage of Gluon Substrate now at

    https://gluonhq.com/activate



[Tue Sep 14 19:10:26 CEST 2021][INFO] We will now compile your code for x86_64-linux-linux. This may take some time.
[Tue Sep 14 19:10:27 CEST 2021][INFO] [SUB] Warning: Ignoring server-mode native-image argument --no-server.
[Tue Sep 14 19:10:29 CEST 2021][INFO] [SUB] [hellofxml.hellofxml:31211]    classlist:   1,840.23 ms,  0.94 GB
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] [GluonFeature] enabled for config com.oracle.svm.hosted.FeatureImpl$IsInConfigurationAccessImpl@423e4cbb
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] [hellofxml.hellofxml:31211]        setup:     361.22 ms,  0.94 GB
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] Error: Error parsing JNI configuration in /home/makingthematrix/workspace/scalaonandroid/HelloFXML/target/gluonfx/x86_64-linux/gvm/jniconfig-x86_64-linux.json:
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] Field java.net.Inet6Address.cached_scope_id not found. To allow unresolvable reflection configuration, use option --allow-incomplete-classpath
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option JNIConfigurationFiles.
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] com.oracle.svm.core.util.UserError$UserException: Error parsing JNI configuration in /home/makingthematrix/workspace/scalaonandroid/HelloFXML/target/gluonfx/x86_64-linux/gvm/jniconfig-x86_64-linux.json:
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] Field java.net.Inet6Address.cached_scope_id not found. To allow unresolvable reflection configuration, use option --allow-incomplete-classpath
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option JNIConfigurationFiles.
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at com.oracle.svm.core.util.UserError.abort(UserError.java:73)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at com.oracle.svm.hosted.config.ConfigurationParserUtils.doParseAndRegister(ConfigurationParserUtils.java:135)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at com.oracle.svm.hosted.config.ConfigurationParserUtils.lambda$parseAndRegisterConfigurations$1(ConfigurationParserUtils.java:86)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:515)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.IntPipeline.sum(IntPipeline.java:473)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at com.oracle.svm.hosted.config.ConfigurationParserUtils.parseAndRegisterConfigurations(ConfigurationParserUtils.java:88)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at com.oracle.svm.jni.access.JNIAccessFeature.afterRegistration(JNIAccessFeature.java:128)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$15(NativeImageGenerator.java:825)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:73)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:825)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:527)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] [hellofxml.hellofxml:31211]      [total]:   2,254.35 ms,  0.94 GB
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] # Printing build artifacts to: /home/makingthematrix/workspace/scalaonandroid/HelloFXML/target/gluonfx/x86_64-linux/gvm/HelloFXML/hellofxml.hellofxml.build_artifacts.txt
[Tue Sep 14 19:10:30 CEST 2021][INFO] [SUB] Error: Image build request failed with exit status 1
[Tue Sep 14 19:10:30 CEST 2021][SEVERE] Process compile failed with result: 1
Check the log files under /home/makingthematrix/workspace/scalaonandroid/HelloFXML/target/gluonfx/x86_64-linux/gvm/log
And please check https://docs.gluonhq.com/ for more information.
[Tue Sep 14 19:10:30 CEST 2021][INFO] Logging process [compile] to file: /home/makingthematrix/workspace/scalaonandroid/HelloFXML/target/gluonfx/log/process-compile-1631639430412.log
[Tue Sep 14 19:10:30 CEST 2021][SEVERE] Compiling failed.
Check the log files under /home/makingthematrix/workspace/scalaonandroid/HelloFXML/target/gluonfx/x86_64-linux/gvm/log
And please check https://docs.gluonhq.com/ for more information.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.189 s
[INFO] Finished at: 2021-09-14T19:10:30+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:gluonfx-maven-plugin:1.0.5:compile (default-cli) on project hellofxml: Compiling failed -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.818 s
[INFO] Finished at: 2021-09-14T19:10:30+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:gluonfx-maven-plugin:1.0.5:build (default-cli) on project hellofxml: Error, gluonfx:build failed -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this, we will take a look into in and get back to you

**Comment by oubidar-Abderrahim** [comment]
Hi, This looks more like an issue for Gluon, please report the issue on the Glueon repo.
I'll close this issue for the time being. If you need more assistance please reopen.
