### ISSUE TITLE
Investigate Assertion failure in DwarfInfoSectionImpl.java 

### ISSUE THREAD

**Issue by christianwimmer** [oracle/graal#3797]
**Describe the issue**

The GitHub gate fails with
```
2021-09-11T06:34:30.8320954Z [hello.hello:7416]    classlist:   4,212.63 ms,  1.62 GB
2021-09-11T06:34:31.9245092Z [hello.hello:7416]        (cap):     599.88 ms,  1.62 GB
2021-09-11T06:34:33.7146481Z [hello.hello:7416]        setup:   2,871.17 ms,  1.62 GB
2021-09-11T06:34:33.8433104Z # Printing compilation-target information to: /home/runner/work/graal/graal/substratevm/svmbuild/reports/target_info_20210911_063433.txt
2021-09-11T06:35:00.6001880Z [hello.hello:7416]     (clinit):     201.53 ms,  2.04 GB
2021-09-11T06:35:00.6140785Z # Printing native-library information to: /home/runner/work/graal/graal/substratevm/svmbuild/reports/native_library_info_20210911_063500.txt
2021-09-11T06:35:00.7272116Z [hello.hello:7416]   (typeflow):   6,473.35 ms,  2.04 GB
2021-09-11T06:35:00.7273654Z [hello.hello:7416]    (objects):  19,499.57 ms,  2.04 GB
2021-09-11T06:35:00.7276122Z [hello.hello:7416]   (features):     373.73 ms,  2.04 GB
2021-09-11T06:35:00.7279166Z [hello.hello:7416]     analysis:  26,882.91 ms,  2.04 GB
2021-09-11T06:35:02.6713471Z [hello.hello:7416]     universe:   1,942.33 ms,  2.04 GB
2021-09-11T06:35:06.0194835Z [hello.hello:7416]      (parse):   3,294.96 ms,  2.15 GB
2021-09-11T06:35:09.9964828Z [hello.hello:7416]     (inline):   3,929.19 ms,  2.18 GB
2021-09-11T06:35:41.3548027Z [hello.hello:7416]    (compile):  31,353.22 ms,  2.69 GB
2021-09-11T06:35:44.0068446Z [hello.hello:7416]      compile:  41,321.46 ms,  2.71 GB
2021-09-11T06:35:52.3072965Z [hello.hello:7416]      dbginfo:   7,744.87 ms,  2.76 GB
2021-09-11T06:35:52.7925737Z [hello.hello:7416]        image:   8,785.19 ms,  2.76 GB
2021-09-11T06:35:52.9617710Z [hello.hello:7416]        write:     168.25 ms,  2.76 GB
2021-09-11T06:35:52.9643955Z Fatal error:java.lang.AssertionError
2021-09-11T06:35:52.9648202Z 	at com.oracle.objectfile.elf.dwarf.DwarfInfoSectionImpl.writeInlineSubroutine(DwarfInfoSectionImpl.java:1372)
2021-09-11T06:35:52.9653585Z 	at com.oracle.objectfile.elf.dwarf.DwarfInfoSectionImpl.generateConcreteInlinedMethods(DwarfInfoSectionImpl.java:991)
2021-09-11T06:35:52.9658761Z 	at com.oracle.objectfile.elf.dwarf.DwarfInfoSectionImpl.writeMethodLocation(DwarfInfoSectionImpl.java:1322)
2021-09-11T06:35:52.9662799Z 	at com.oracle.objectfile.elf.dwarf.DwarfInfoSectionImpl.writeMethodLocations(DwarfInfoSectionImpl.java:939)
2021-09-11T06:35:52.9666754Z 	at com.oracle.objectfile.elf.dwarf.DwarfInfoSectionImpl.writePrimaryClassUnit(DwarfInfoSectionImpl.java:476)
2021-09-11T06:35:52.9670466Z 	at com.oracle.objectfile.elf.dwarf.DwarfInfoSectionImpl.lambda$writePrimaryClasses$8(DwarfInfoSectionImpl.java:414)
2021-09-11T06:35:52.9673755Z 	at java.util.stream.ReduceOps$1ReducingSink.accept(ReduceOps.java:80)
2021-09-11T06:35:52.9676556Z 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
2021-09-11T06:35:52.9679574Z 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
2021-09-11T06:35:52.9682572Z 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
2021-09-11T06:35:52.9685811Z 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
2021-09-11T06:35:52.9688685Z 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
2021-09-11T06:35:52.9691406Z 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2021-09-11T06:35:52.9694213Z 	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:551)
2021-09-11T06:35:52.9697852Z 	at com.oracle.objectfile.elf.dwarf.DwarfInfoSectionImpl.writePrimaryClasses(DwarfInfoSectionImpl.java:411)
2021-09-11T06:35:52.9701610Z 	at com.oracle.objectfile.elf.dwarf.DwarfInfoSectionImpl.generateContent(DwarfInfoSectionImpl.java:164)
2021-09-11T06:35:52.9705128Z 	at com.oracle.objectfile.elf.dwarf.DwarfInfoSectionImpl.createContent(DwarfInfoSectionImpl.java:99)
2021-09-11T06:35:52.9708339Z 	at com.oracle.objectfile.elf.dwarf.DwarfSectionImpl.getOrDecideSize(DwarfSectionImpl.java:407)
2021-09-11T06:35:52.9711709Z 	at com.oracle.objectfile.elf.ELFUserDefinedSection.getOrDecideSize(ELFUserDefinedSection.java:105)
2021-09-11T06:35:52.9714562Z 	at com.oracle.objectfile.ObjectFile.bake(ObjectFile.java:1659)
2021-09-11T06:35:52.9716834Z 	at com.oracle.objectfile.ObjectFile.write(ObjectFile.java:1271)
2021-09-11T06:35:52.9719091Z 	at com.oracle.svm.hosted.image.NativeImage.lambda$write$0(NativeImage.java:168)
2021-09-11T06:35:52.9722466Z 	at com.oracle.objectfile.ObjectFile.withDebugContext(ObjectFile.java:1842)
2021-09-11T06:35:52.9725817Z 	at com.oracle.svm.hosted.image.NativeImage.write(NativeImage.java:167)
2021-09-11T06:35:52.9729746Z 	at com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:412)
2021-09-11T06:35:52.9736346Z 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:657)
2021-09-11T06:35:52.9737907Z 	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
2021-09-11T06:35:52.9749043Z 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
2021-09-11T06:35:52.9751180Z 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
2021-09-11T06:35:52.9754584Z 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
2021-09-11T06:35:52.9756359Z [hello.hello:7416]      [total]:  86,366.39 ms,  2.76 GB
2021-09-11T06:35:52.9767359Z # Printing build artifacts to: /home/runner/work/graal/graal/substratevm/svmbuild/hello.hello.build_artifacts.txt
2021-09-11T06:35:53.0471934Z Error: Image build request failed with exit status 1
```

This happens since the merge of https://github.com/oracle/graal/commit/d87f6a5ced705f27fa46ed50258615a4dc1c1c1c that I did. I looked into the issue, and don't see anything wrong in the reflection changes. So I think this was a pre-existing bug that just got exposed by the changes.

The method that is compiled is a reflection invocation stub (because the declaring class of the method is `ReflectionAccessorHolder`. The stub is to create a new instance of a automatically generated `java.lang.reflect.Proxy` class (named `Proxy152` in my debug session). Such a proxy class does not have source file information. It seems to me as if `writeInlineSubroutine` does not handle the case correctly when a method with source file information inlines another method that does not have source file information.

**Steps to reproduce the issue**
`mx debuginfotest` is enough to reproduce the problem.

**Describe GraalVM and your environment:**
GitHub gate

**Comment by christianwimmer** [comment]
@adinn somehow I can not assign you to the issue, so I'm just mentioning you here so that you are aware of it.

**Comment by adinn** [comment]
@christianwimmer Yes, this was a latent bug waiting to pounce. Thanks for pushing it my way. Foivos' proposed patch removes the problem with the assert and should really be committed as quick as possible to remedy the gate problem (@olpaw a review from you would be useful).

There is still a question about the change to the inline info. I'm not clear why your compiler change means that it now includes a call in the call hierarchy with no associated file and line info. I'll take a look at what tripped the assert to see if a source position is no longer being propagated through during substitution. If so then I'll also see if we can correct that or if it is simply unavoidable.

**Comment by christianwimmer** [comment]
I did not see evidence of a a missing source position or something like this. It is certainly allowed to have inlining chains where some inlined methods do not have source information.

One change that my PR did: previously, the reflection stubs were in classes that also came to life as a `Proxy` (even though then the methods had manually generated graphs). So the declaring class (and therefore the method root of the inlining) did not have any source information. Now the stubs are all in `ReflectionAccessorHolder`, which itself has source file information. If for some reason you already bail out of debug info generation when the root method has no source file, this would have hidden the problem in the old implementation.

**Comment by fniephaus** [comment]
Thanks to @zakkak's fix, the builds are green again. Re-naming and re-opening the issue until @adinn and @christianwimmer have found out why https://github.com/oracle/graal/commit/d87f6a5ced705f27fa46ed50258615a4dc1c1c1c changed the inline info in the first place.

**Comment by adinn** [comment]
@fniephaus Thanks Fabio. I'll report back here with a fix if any is needed.

@christianwimmer I take your point that inlining chains may legitimately include caller info for code that does not have an associated file or line number. However, in cases which this one appears to represent, where the caller info refer to generated graph structures, we may want to elide the info from the call hierarchy. I'll see if that makes sense here or anywhere else.

**Comment by adinn** [comment]
@christianwimmer I cannot currently see any way of fixing this to provide a meaningful file and line number for the ReflectionInvokeMethod/ReflectionNewInstanceMethod stub frame. As currently implemented stepping down through a java.lang.reflect.Method.invoke call in gdb is going to initially jump to line 0 of file ReflectionAccessorHolder.java (at the transition step where SubstrateMethodAccessor calls functionPointer.invoke). It's not totally clear why one is seeing this file but it's also not especially opaque since the new frame at that point identifies a synthetic stub method name attached to class ReflectionAccessorHolder and we do eventually start stepping through the target method code.

Unfortunately, we cannot simply elide the ReflectionAccessorHolder call frame from the debug info as it is a top level method compiled and so it has to be be present in the call stack (it is only possible to elide a frame from the inline tree when it exists as an intermediate call between the top level caller and the leaf 

So, I'm closing this issue for now on the grounds that nothing is strictly broken even if perhaps it might still be desirable to find some more elegant way to direct the source file display.

**Comment by adinn** [comment]
@christianwimmer Actually I cannot close this issue -- perhaps you could do so?
