### ISSUE TITLE
GraalVM --target paramaters

### ISSUE THREAD

**Issue by tolginho** [oracle/graal#3810]
Hello,

i just build a native image with GraalVM on a docker container (native-image -jar rcpstick-ui.jar --no-fallback).
The build itself worked, but i think my project doesnt work because the target platform is not right. It says that " Defaults to host's OS-architecture pair."

So i tried to use the --target option: 

native-image -jar rcpstick-ui.jar --target="arm-unknown-linux-gnueabi" --no-fallback

The error was:

Exception in thread "main" com.oracle.svm.core.util.UserError$UserException: --target argument must be in format <OS>-<architecture>
        at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
        at com.oracle.svm.driver.NativeImage.addTargetArguments(NativeImage.java:1278)
        at com.oracle.svm.driver.NativeImage.completeImageBuild(NativeImage.java:1047)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1417)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1387)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1374)
        at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1858)

Soooo i googled it but couldnt get any solution. Is there a list of --target parameters anywhere? Or what does the error exactly mean?

Thank you in advance
Tolga

**Comment by rodrigar-mx** [comment]
Hi @tolginho. The format for the target flag is <OS>-<architecture>. As OS you can have "linux", "android", "darwin", "ios", or "windows", and as architecture you can have "amd64", or "aarch64". Not all combinations are supported. Take a look [here](https://docs.oracle.com/en/graalvm/enterprise/21/sdk/org/graalvm/nativeimage/Platform.html).

**Comment by tolginho** [comment]
Thank you very much.

Rodrigo Garcia ***@***.***> schrieb am Mo. 20. Sept. 2021 um
16:37:
