### ISSUE TITLE
java.lang.IllegalStateException: Multi threaded access requested by thread [] but is not allowed for language(s) js.

### ISSUE THREAD

**Issue by yang-uamng** [oracle/graal#3814]
i run a nodejs project on graavm, i want make jsfunction extends a java interface and  take the java-jar can run js-implements, but is not work

how can i visit --jvm mode  PolyglotLanguageContext and set accessAllowed

Exception in thread "OkHttp Dispatcher" java.lang.IllegalStateException: Multi threaded access requested by thread Th
d[OkHttp http:///...,5,main] but is not allowed for language(s) js.
        at com.oracle.truffle.polyglot.PolyglotEngineException.illegalState(PolyglotEngineException.java:129)
        at com.oracle.truffle.polyglot.PolyglotContextImpl.throwDeniedThreadAccess(PolyglotContextImpl.java:1075)
        at com.oracle.truffle.polyglot.PolyglotContextImpl.checkAllThreadAccesses(PolyglotContextImpl.java:933)
        at com.oracle.truffle.polyglot.PolyglotContextImpl.enterThreadChanged(PolyglotContextImpl.java:789)
        at com.oracle.truffle.polyglot.PolyglotEngineImpl.enter(PolyglotEngineImpl.java:1815)
        at com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:110)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:632)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:603)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:535)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:519)
        at org.graalvm.compiler.truffle.runtime.GraalRuntimeSupport.callProfiled(GraalRuntimeSupport.java:143)
        at com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue.canInvoke(PolyglotValueDispatch.java:2365)
        at org.graalvm.polyglot.Value.canInvokeMember(Value.java:899)
        at com.oracle.truffle.host.adapters.HostAdapterServices.hasMethod(HostAdapterServices.java:115)
        at com.oracle.truffle.host.adapters.FaasCallback$$Adapter.ok(Unknown Source)
        at com.yy.faas.sdk.http.HttpSdk$1.onResponse(HttpSdk.java:110)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: Attached Guest Language Frames (1)

**Comment by rodrigar-mx** [comment]
Hi @yang-uamng. Thanks for sharing the issue. You may want to take a look [here](https://www.graalvm.org/reference-manual/embed-languages/#access-java-from-guest-languages). If you cannot find an answer, please share i) the graalvm version you are using, ii) the OS you are using, iii) a reproducer, if possible, or the steps required to reproduce the issue.

**Comment by yang-uamng** [comment]
the graalvm version :graalvm-ce-java8-linux-amd64-21.2.0.tar.gz
the OS  : ubantu

jscode:
```
var faasCb = Java.extend(Java.type('com.yy.faas.sdk.FaasCallback'));
var impl = new faasCb({
  			fail: function(msg) {console.log(msg + ":js312ok")},
			ok: function(msg) {console.log(msg +":js123ok")}
});
var f =  HttpClientUtil.asyncRequest("http://test/api/serverexp",map , 'GET', impl);

```
javacode:

```
   public static HttpFutureReq asyncRequest(String srvUrl, Map<String, String> formMap, String type, FaasCallback callback) throws Exception {
        p = Thread.currentThread();

        HttpFutureReq httpFutureReqFuture = new HttpFutureReq();

        HttpFutureContext httpFutureContext = HttpFutureContext.builder().faasCallback(callback).build();

        RequestType requestType = RequestType.valueOf(type);
        OkHttpClient client = HttpClient.getClient();
        Request.Builder reqBuilder = buildRequestData(srvUrl, formMap, requestType);

        Call call = client.newCall(reqBuilder.build());
        call.enqueue(new Callback() {
            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                httpFutureContext.setResp("failed!!done");
                httpFutureReqFuture.done(httpFutureContext);
            }

            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                String string = response.body().string();
                System.out.println("onResponse ok " + string);
                callback.ok();
            }
        });

        return httpFutureReqFuture;
    }



```

**Comment by yang-uamng** [comment]
> Hi @yang-uamng. Thanks for sharing the issue. You may want to take a look [here](https://www.graalvm.org/reference-manual/embed-languages/#access-java-from-guest-languages). If you cannot find an answer, please share i) the graalvm version you are using, ii) the OS you are using, iii) a reproducer, if possible, or the steps required to reproduce the issue.

the graalvm version :graalvm-ce-java8-linux-amd64-21.2.0.tar.gz
the OS : ubuntu

**Comment by rodrigar-mx** [comment]
Hi @yang-uamng. The problem is not extending the java interface in js, and then call it from java. You can test this by adding at the beginning of  `asyncRequest` method the following calls: `callback.fail("")` or `callback.ok("")`; and you should see the methods been called without errors. The problem is raised because a new thread, created by the HttpRequest, is the one trying to execute this methods, and that is not allowed. Something similar to [this](https://github.com/oracle/graaljs/blob/master/graal-js/src/com.oracle.truffle.js.test.threading/src/com/oracle/truffle/js/test/threading/ConcurrentAccess.java#L88) is happening. I strongly suggest to take a deep look here https://www.graalvm.org/reference-manual/js/Multithreading/ to look for alternatives.

**Comment by yang-uamng** [comment]
> Hi @yang-uamng. The problem is not extending the java interface in js, and then call it from java. You can test this by adding at the beginning of `asyncRequest` method the following calls: `callback.fail("")` or `callback.ok("")`; and you should see the methods been called without errors. The problem is raised because a new thread, created by the HttpRequest, is the one trying to execute this methods, and that is not allowed. Something similar to [this](https://github.com/oracle/graaljs/blob/master/graal-js/src/com.oracle.truffle.js.test.threading/src/com/oracle/truffle/js/test/threading/ConcurrentAccess.java#L88) is happening. I strongly suggest to take a deep look here https://www.graalvm.org/reference-manual/js/Multithreading/ to look for alternatives.
it is asynccall, so it will take new  thread to callback inevitable, can i take same context to new thread avoid Multithreading ？

**Comment by rodrigar-mx** [comment]
Current context can be obtain by calling  _Context c = Context.getCurrent()_, but this will not work inside the new thread. Take a look at this blog post https://medium.com/graalvm/multi-threaded-java-javascript-language-interoperability-in-graalvm-2f19c1f9c37b, specially the very last example. There they achieved an async call sharing objects between nodejs and java by using workers.

**Comment by yang-uamng** [comment]
> Current context can be obtain by calling _Context c = Context.getCurrent()_, but this will not work inside the new thread. Take a look at this blog post https://medium.com/graalvm/multi-threaded-java-javascript-language-interoperability-in-graalvm-2f19c1f9c37b, specially the very last example. There they achieved an async call sharing objects between nodejs and java by using workers.

I've solved the problem by sharing queue, but it's not rigorous。i want use synchronized but it donest work

```
  Context currentContext = Context.getCurrent();

        synchronized (currentContext) {
            HttpFutureReq httpFutureReqFuture = new HttpFutureReq();
            HttpFutureContext httpFutureContext = HttpFutureContext.builder().faasCallback(callback).build();

            option.setRequestType(RequestType.valueOf(option.getMethod()));
           
            OkHttpClient client = OkHttpPoolMgr.getInstance().select(option);
            Request.Builder reqBuilder = buildRequestData(srvUrl, option, formMap);

            Call call = client.newCall(reqBuilder.build());
            call.enqueue(new Callback() {
                @Override
                public void onFailure(@NotNull Call call, @NotNull IOException e) {
                    HttpResponse httpResponse = HttpResponse.builder().code(400).message(e.getMessage()).build();
                    httpFutureContext.setResp(httpResponse);
                    httpFutureContext.setFlag(false);
                    httpFutureReqFuture.done(httpFutureContext);
                    synchronized (currentContext) {
                        System.out.println("callback~~!!");
                        callback.fail(httpResponse);
                    }
                }

                @Override
                public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                    HttpResponse resp = getResponse(response);
                    httpFutureContext.setResp(resp);
                    httpFutureContext.setFlag(true);
                    httpFutureReqFuture.done(httpFutureContext);
                    synchronized (currentContext) {
                        System.out.println("callback~~!!");
                        callback.ok(resp);
                    }

                }
            });

```

**Comment by rodrigar-mx** [comment]
It does not work, because the problem is that you are accessing the same context with a different thread. **synchronized** is not doing any difference because the whole java program  is run in currentContext and the context has not been left. As you saw in the [example](https://medium.com/graalvm/multi-threaded-java-javascript-language-interoperability-in-graalvm-2f19c1f9c37b,), there is no js code accessed directly. There is just a shared sync object that functions as an intermediary between java and js for passing async messages.

**Comment by rodrigar-mx** [comment]
Closing this issue because there is no activity in last one month.
