### ISSUE TITLE
NPE dumping CFG

### ISSUE THREAD

**Issue by chrisseaton** [oracle/graal#3816]
```
% ./truffleruby-21.2.0.1-macos-amd64/bin/ruby --experimental-options --vm.Dgraal.Dump=:3 --engine.TraceCompilation --engine.CompileOnly=foo --vm.Dgraal.PrintBackendCFG=true test.rb
...
[engine] opt done     Object#foo                                                  |AST   18|Tier 1|Time  308(  59+249 )ms|Inlined   0Y   0N|IR   105/  206|CodeSize    754|Addr 0x1195d8000|Src test.rb:1
Dumping IGV graphs in /Users/chrisseaton/Documents/ruby-compiler-explorer/graal_dumps/2021.09.20.00.22.40.922
CFGPrinter: Exception during output of After code generation: java.lang.NullPointerException
java.lang.NullPointerException
        at org.graalvm.compiler.code.HexCodeFileDisassemblerProvider.disassemble(HexCodeFileDisassemblerProvider.java:71)
        at org.graalvm.compiler.code.HexCodeFileDisassemblerProvider.disassembleCompiledCode(HexCodeFileDisassemblerProvider.java:56)
        at org.graalvm.compiler.printer.CFGPrinterObserver.disassemble(CFGPrinterObserver.java:301)
        at org.graalvm.compiler.printer.CFGPrinterObserver.dumpSandboxed(CFGPrinterObserver.java:238)
        at org.graalvm.compiler.printer.CFGPrinterObserver.dumpSandboxed(CFGPrinterObserver.java:161)
        at org.graalvm.compiler.printer.CFGPrinterObserver.dump(CFGPrinterObserver.java:86)
```

@eregon

**Comment by mcraj017** [comment]
@chrisseaton thanks for reporting the issue
@chumer please advise

**Comment by mcraj017** [comment]
@eregon please check and advise

**Comment by eregon** [comment]
It looks very much like a compiler issue, reassigning to Doug.

**Comment by dougxc** [comment]
Hi @chrisseaton is there any chance you could try reproduce this on a 21.3 snapshot? There have been some changes in that area so it would be interesting to know if the problem still exists.
Also, looking at [the code](https://github.com/oracle/graal/blob/912dc699239176ba953cf85cb10309ce03f646cf/compiler/src/org.graalvm.compiler.printer/src/org/graalvm/compiler/printer/CFGPrinterObserver.java#L83-L88) I don't think this exception should actually cause a compilation to fail. Is that the case for you?

**Comment by chrisseaton** [comment]
I don't think it causes compilation failure - it just means I don't get the graphs I want.

I will check on the snapshot today.

**Comment by dougxc** [comment]
Ok, thanks.

Of course, any help you can provide in terms of debugging the cause would be greatly appreciated.

**Comment by chrisseaton** [comment]
Still fails.

Talks about 'disassembler' but in my experience the CFG files just include raw binary as Base 64 or something like that, which is fine because I disassemble offline.

```
% ./graalvm-ce-java11-21.3.0-dev/Contents/Home/bin/ruby --experimental-options --vm.Dgraal.Dump=:3 --engine.TraceCompilation --engine.CompileOnly=foo --vm.Dgraal.PrintBackendCFG=true test.rb
Dumping IGV graphs in /Users/chrisseaton/Documents/dump/graal_dumps/2021.09.23.14.08.21.207
CFGPrinter: Exception during output of After code generation: java.util.ServiceConfigurationError: org.graalvm.compiler.code.DisassemblerProvider: Provider org.graalvm.compiler.hotspot.meta.HotSpotDisassemblerProvider not found
java.util.ServiceConfigurationError: org.graalvm.compiler.code.DisassemblerProvider: Provider org.graalvm.compiler.hotspot.meta.HotSpotDisassemblerProvider not found
        at java.util.ServiceLoader.fail(ServiceLoader.java:589)
        at java.util.ServiceLoader.loadProvider(ServiceLoader.java:868)
        at java.util.ServiceLoader$LayerLookupIterator.hasNext(ServiceLoader.java:952)
        at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
        at org.graalvm.compiler.serviceprovider.GraalServices$1$1.hasNext(GraalServices.java:150)
        at org.graalvm.compiler.printer.CFGPrinterObserver.selectDisassemblerProvider(CFGPrinterObserver.java:272)
        at org.graalvm.compiler.printer.CFGPrinterObserver.disassemble(CFGPrinterObserver.java:295)
        at org.graalvm.compiler.printer.CFGPrinterObserver.dumpSandboxed(CFGPrinterObserver.java:236)
        at org.graalvm.compiler.printer.CFGPrinterObserver.dumpSandboxed(CFGPrinterObserver.java:159)
        at org.graalvm.compiler.printer.CFGPrinterObserver.dump(CFGPrinterObserver.java:84)
        at org.graalvm.compiler.debug.ScopeImpl.dump(ScopeImpl.java:223)
        at org.graalvm.compiler.debug.DebugContext.dump(DebugContext.java:1356)
        at org.graalvm.compiler.core.gen.LIRCompilerBackend.emitCode(LIRCompilerBackend.java:254)
        at org.graalvm.compiler.core.gen.LIRCompilerBackend.emitBackEnd(LIRCompilerBackend.java:90)
        at org.graalvm.compiler.core.target.Backend.emitBackEnd(Backend.java:279)
        at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:146)
        at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:130)
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compilePEGraph(TruffleCompilerImpl.java:597)
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compileAST(TruffleCompilerImpl.java:526)
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:718)
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:656)
        at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:223)
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.actuallyCompile(TruffleCompilerImpl.java:331)
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.doCompile(TruffleCompilerImpl.java:293)
        at com.oracle.svm.truffle.isolated.IsolateAwareTruffleCompiler.doCompile0(IsolateAwareTruffleCompiler.java:213)
[To redirect Truffle log output to a file use one of the following options:
* '--log.file=<path>' if the option is passed using a guest language launcher.
* '-Dpolyglot.log.file=<path>' if the option is passed using the host Java launcher.
* Configure logging using the polyglot embedding API.]
[engine] opt done     Object#foo                                                  |AST   18|Tier 1|Time  219(  33+186 )ms|Inlined   0Y   0N|IR   105/  207|CodeSize    754|Addr 0x1148e8000|Src test.rb:1
Dumping IGV graphs in /Users/chrisseaton/Documents/dump/graal_dumps/2021.09.23.14.08.21.207
CFGPrinter: Exception during output of After code generation: java.util.ServiceConfigurationError: org.graalvm.compiler.code.DisassemblerProvider: Provider org.graalvm.compiler.hotspot.meta.HotSpotDisassemblerProvider not found
java.util.ServiceConfigurationError: org.graalvm.compiler.code.DisassemblerProvider: Provider org.graalvm.compiler.hotspot.meta.HotSpotDisassemblerProvider not found
        at java.util.ServiceLoader.fail(ServiceLoader.java:589)
        at java.util.ServiceLoader.loadProvider(ServiceLoader.java:868)
        at java.util.ServiceLoader$LayerLookupIterator.hasNext(ServiceLoader.java:952)
        at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
        at org.graalvm.compiler.serviceprovider.GraalServices$1$1.hasNext(GraalServices.java:150)
        at org.graalvm.compiler.printer.CFGPrinterObserver.selectDisassemblerProvider(CFGPrinterObserver.java:272)
        at org.graalvm.compiler.printer.CFGPrinterObserver.disassemble(CFGPrinterObserver.java:295)
        at org.graalvm.compiler.printer.CFGPrinterObserver.dumpSandboxed(CFGPrinterObserver.java:236)
        at org.graalvm.compiler.printer.CFGPrinterObserver.dumpSandboxed(CFGPrinterObserver.java:159)
        at org.graalvm.compiler.printer.CFGPrinterObserver.dump(CFGPrinterObserver.java:84)
        at org.graalvm.compiler.debug.ScopeImpl.dump(ScopeImpl.java:223)
        at org.graalvm.compiler.debug.DebugContext.dump(DebugContext.java:1356)
        at org.graalvm.compiler.core.gen.LIRCompilerBackend.emitCode(LIRCompilerBackend.java:254)
        at org.graalvm.compiler.core.gen.LIRCompilerBackend.emitBackEnd(LIRCompilerBackend.java:90)
        at org.graalvm.compiler.core.target.Backend.emitBackEnd(Backend.java:279)
        at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:146)
        at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:130)
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compilePEGraph(TruffleCompilerImpl.java:597)
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compileAST(TruffleCompilerImpl.java:526)
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:718)
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:656)
        at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:223)
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.actuallyCompile(TruffleCompilerImpl.java:331)
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.doCompile(TruffleCompilerImpl.java:293)
        at com.oracle.svm.truffle.isolated.IsolateAwareTruffleCompiler.doCompile0(IsolateAwareTruffleCompiler.java:213)
[engine] opt done     Object#foo                                                  |AST   18|Tier 2|Time  147(  11+136 )ms|Inlined   0Y   0N|IR    34/  111|CodeSize    427|Addr 0x1148ea000|Src test.rb:1
```

**Comment by dougxc** [comment]
@tzezula could you please look into this. I'm not familiar with how the IsolateAwareTruffleCompiler is configured.

**Comment by chrisseaton** [comment]
This still seems to be present in some form in 22.2.

```
CFGPrinter: Exception during output of After code generation: java.util.ServiceConfigurationError: org.graalvm.compiler.code.DisassemblerProvider: Provider org.graalvm.compiler.hotspot.meta.HotSpotDisassemblerProvider not found
java.util.ServiceConfigurationError: org.graalvm.compiler.code.DisassemblerProvider: Provider org.graalvm.compiler.hotspot.meta.HotSpotDisassemblerProvider not found
        at java.util.ServiceLoader.fail(ServiceLoader.java:593)
        at java.util.ServiceLoader.loadProvider(ServiceLoader.java:875)
        at java.util.ServiceLoader$LayerLookupIterator.hasNext(ServiceLoader.java:958)
        at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
        at org.graalvm.compiler.serviceprovider.GraalServices$1$1.hasNext(GraalServices.java:174)
        at org.graalvm.compiler.printer.CFGPrinterObserver.selectDisassemblerProvider(CFGPrinterObserver.java:222)
        at org.graalvm.compiler.printer.CFGPrinterObserver.disassemble(CFGPrinterObserver.java:248)
        at org.graalvm.compiler.printer.CFGPrinterObserver.dumpSandboxed(CFGPrinterObserver.java:191)
        at org.graalvm.compiler.printer.CFGPrinterObserver.dumpSandboxed(CFGPrinterObserver.java:143)
        at org.graalvm.compiler.printer.CFGPrinterObserver.dump(CFGPrinterObserver.java:78)
        at org.graalvm.compiler.debug.ScopeImpl.dump(ScopeImpl.java:223)
        at org.graalvm.compiler.debug.DebugContext.dump(DebugContext.java:1380)
        at org.graalvm.compiler.core.gen.LIRCompilerBackend.emitCode(LIRCompilerBackend.java:255)
        at org.graalvm.compiler.core.gen.LIRCompilerBackend.emitBackEnd(LIRCompilerBackend.java:91)
        at org.graalvm.compiler.core.target.Backend.emitBackEnd(Backend.java:289)
        at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:146)
        at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:130)
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compilePEGraph(TruffleCompilerImpl.java:635)
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compileAST(TruffleCompilerImpl.java:524)
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:763)
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:699)
        at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:223)
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.actuallyCompile(TruffleCompilerImpl.java:353)
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.doCompile(TruffleCompilerImpl.java:307)
        at com.oracle.svm.truffle.isolated.IsolateAwareTruffleCompiler.doCompile0(IsolateAwareTruffleCompiler.java:218)
```

How are other people getting assembly out?

**Comment by eregon** [comment]
> How are other people getting assembly out?

mx proftool is a convenient way to get the hot parts of the assembly (but Linux-only I guess since it depends on prof)
