### ISSUE TITLE
[GR-34132] Missing resource bundle 'sun.util.resources.CurrencyNames'

### ISSUE THREAD

**Issue by kkriske** [oracle/graal#3835]
**Describe the issue**
Missing resource bundle `sun.util.resources.CurrencyNames` when resolving currency symbols.

**Steps to reproduce the issue**

1. `AvailableCurrencies.java` file:
```java
import java.util.Currency;
import java.util.Locale;

public class AvailableCurrencies {
    public static void main(String[] args) {
        for (Currency currency : Currency.getAvailableCurrencies()) {
            System.out.println(currency.getSymbol());
        }
    }
}
```
2. compile: `javac AvailableCurrencies.java`
3. build native-image: `native-image --no-server --no-fallback AvailableCurrencies -H:DefaultLocale=en-US`
4. run `availablecurrencies.exe`:
```java
> availablecurrencies.exe
Exception in thread "main" java.util.MissingResourceException: Can't find bundle for base name sun.util.resources.CurrencyNames, locale en_US
        at sun.util.resources.Bundles.throwMissingResourceException(Bundles.java:290)
        at sun.util.resources.Bundles.loadBundleOf(Bundles.java:147)
        at sun.util.resources.Bundles.of(Bundles.java:106)
        at sun.util.resources.LocaleData$1.run(LocaleData.java:185)
        at sun.util.resources.LocaleData$1.run(LocaleData.java:182)
        at java.security.AccessController.doPrivileged(AccessController.java:87)
        at sun.util.resources.LocaleData.getBundle(LocaleData.java:182)
        at sun.util.resources.LocaleData.getCurrencyNames(LocaleData.java:98)
        at sun.util.locale.provider.LocaleResources.getCurrencyName(LocaleResources.java:225)
        at sun.util.locale.provider.CurrencyNameProviderImpl.getString(CurrencyNameProviderImpl.java:122)
        at sun.util.locale.provider.CurrencyNameProviderImpl.getSymbol(CurrencyNameProviderImpl.java:90)
        at java.util.Currency$CurrencyNameGetter.getObject(Currency.java:709)
        at java.util.Currency$CurrencyNameGetter.getObject(Currency.java:694)
        at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObjectImpl(LocaleServiceProviderPool.java:281)
        at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObject(LocaleServiceProviderPool.java:242)
        at java.util.Currency.getSymbol(Currency.java:545)
        at java.util.Currency.getSymbol(Currency.java:522)
        at AvailableCurrencies.main(AvailableCurrencies.java:7)
```

**Describe GraalVM and your environment:**
 - GraalVM version: `CE 21.2.0` `CE 21.3.0` `CE 22.0.0` `CE 22.1.0`
 - JDK major version: **11**
 - OS: **Windows 10**
 - Architecture: **AMD64**

**More details**
The issue is fixed by adding `-H:IncludeResourceBundles=sun.util.resources.CurrencyNames` to the `native-image` command, but since it's a jdk resource bundle, it should work out of the box.
The `CurrencyNames` should supposedly already be handled by this line:
https://github.com/oracle/graal/blob/4adaa2de9ba5ba085b882b6ce469d438f0305057/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/localization/LocalizationFeature.java#L400
But that doesn't seem to do the trick.

**Comment by mcraj017** [comment]
@kkriske thanks for reporting the issue, we will check it out and get back to you

**Comment by mcraj017** [comment]
@kkriske I have raised this issue with native-image team

**Comment by kkriske** [comment]
Quick update, this is still an issue in `22.1.0`.

**Comment by wirthi** [comment]
This seems to work fine on recent GraalVM versions (tested on Linux and Windows). If you still experience this problem, please reopen and share some details on your setup.
