### ISSUE TITLE
Deserialization in native-image doesn't work for certain types

### ISSUE THREAD

**Issue by jaikiran** [oracle/graal#3839]
Consider this simple Java code which serializes and then deserializes a `java.math.BigInteger`:

```
import java.io.*;
import java.math.*;

public class SerDeser {
	public static void main(final String[] args) throws Exception {
		final BigInteger b = BigInteger.ONE;
        byte[] bytes = null;
        // serialize
        try (ByteArrayOutputStream baos = new ByteArrayOutputStream();
             ObjectOutputStream oos = new ObjectOutputStream(baos)) {
            oos.writeObject(b);
            oos.flush();
            bytes = baos.toByteArray();
        }
        BigInteger d = null;
        // deserialize
        try (ByteArrayInputStream bais = new ByteArrayInputStream(bytes);
                ObjectInputStream ois = new ObjectInputStream(bais)) {
            d = (BigInteger) ois.readObject();
        }
        System.out.println("Serialized " + b + " and deserialized back to " + d);
    }
}
```
Include the following serialization config file (`ser-conf.json`):
```
[
  {
    "name": "java.math.BigInteger"
  },
  {
    "name": "java.lang.Number"
  }
]
```

Compile the java code into .class and then create a native image out of it as follows:

```
javac SerDeser.java
native-image -cp . -H:SerializationConfigurationResources=ser-conf.json SerDeser serdeser-native --no-fallback
```
After the image is generated, launch it:
```
./serdeser-native
```
This throws an exception during the deserialization part:

```
Exception in thread "main" java.io.StreamCorruptedException: invalid type code: 01
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1710)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2077)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
	at java.io.ObjectInputStream$GetFieldImpl.readFields(ObjectInputStream.java:2643)
	at java.io.ObjectInputStream.readFields(ObjectInputStream.java:673)
	at java.math.BigInteger.readObject(BigInteger.java:4646)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1175)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2325)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2196)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:493)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:451)
	at SerDeser.main(SerDeser.java:19)
```

The issue is reproducible against `21.2.0` as well as a fresh built from source, latest upstream version:

```
GraalVM 22.0.0-dev Java 11 CE (Java Version 11.0.11+8-jvmci-21.2-b02)
```

This issue was first reported in Quarkus here https://github.com/quarkusio/quarkus/issues/20397. As noted there, it looks to me that the deserialization fails if the object being deserialized has some array type field https://github.com/quarkusio/quarkus/issues/20397#issuecomment-927571946. I haven't investigated it though, so I might be wrong.

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this, we will take a look into it and get back to you

**Comment by oubidar-Abderrahim** [comment]
The following `ser-conf.json` should work
```
[
  {
  "name":"[B"
  },
  {
  "name":"java.math.BigInteger"
  },
  {
  "name":"java.lang.Number"
  }
]
```
The `native-image-agent` should be able to generate the correct serialization-config file

**Comment by jaikiran** [comment]
Hello @oubidar-Abderrahim, thank you for that detail. I'll give that a try soon.

It's interesting that it requires/adds a byte[] representation as the allowed serialization types. Do you happen to know why it is expecting the byte[] class to be specified. A quick look at the `BigInteger` class shows me that it has a `int[]` field but I don't see any `byte[]` field in it.

**Comment by oubidar-Abderrahim** [comment]
Hi @jaikiran 
if you look at the `java.math.BigInteger.readObject(BigInteger.java:4646)` mentioned in the stacktrace, you'll find
```
private void readObject(java.io.ObjectInputStream s)
    throws java.io.IOException, ClassNotFoundException {
    // prepare to read the alternate persistent fields
    ObjectInputStream.GetField fields = s.readFields();

    // Read the alternate persistent fields that we care about
    int sign = fields.get("signum", -2);
    byte[] magnitude = (byte[])fields.get("magnitude", null);
...
```
As you can see, The magnitude field is a byte array.

It is also explained in the JavaDoc of BigInteger.writeObject:
```
   /**
     * Save the {@code BigInteger} instance to a stream.  The magnitude of a
     * {@code BigInteger} is serialized as a byte array for historical reasons.
     * To maintain compatibility with older implementations, the integers
     * -1, -1, -2, and -2 are written as the values of the obsolete fields
     * {@code bitCount}, {@code bitLength}, {@code lowestSetBit}, and
     * {@code firstNonzeroByteNum}, respectively.  These values are compatible
     * with older implementations, but will be ignored by current
     * implementations.
     */
```

Hope this clarifies things for you, I will close this issue for now, if you still need assistance you can reopen it.
Thank you

**Comment by jaikiran** [comment]
Thank you @oubidar-Abderrahim for those details. I tested your suggested change to the serialization configuration and it did help and the application started passing.
