### ISSUE TITLE
How do I use native-image for axis2 / inner jars from classpath

### ISSUE THREAD

**Issue by StefanLobbenmeier** [oracle/graal#3842]
I have a project that uses Axis2 to run a Soap Server

My module has this layout:
![image](https://user-images.githubusercontent.com/36509607/134954646-2d59a32a-dbb2-4b06-bef3-a1fdc955d12e.png)

and I start my server like this

```java
import org.apache.axis2.context.*;
import org.apache.axis2.transport.http.SimpleHTTPServer;

public class MockServer {
    public static void main(String[] args) throws Exception {
        final int port = 8080;
        final ConfigurationContext configuration = ConfigurationContextFactory
                .createConfigurationContextFromURIs(
                        MockServer.class.getResource("/axis2/axis2.xml"),
                        MockServer.class.getResource("/axis2/")
                );

        SimpleHTTPServer receiver = new SimpleHTTPServer(configuration, port);
        receiver.start();
    }
}
```

I was able to generate the graalvm .json configuration files using the agent. But when I now compile this while providing the .json files in my build.gradle.kts like this
```
graalvmNative {
    binaries {
        configure<org.graalvm.buildtools.gradle.dsl.NativeImageOptions> {
            configurationFileDirectories.from(file("src/main/resources/META-INF"))

        }
    }
}
```

The build reports an issue with reflection-config.json:

```
> Task :server:nativeCompile
[server:6675]    classlist:   8,145.94 ms,  0.96 GB
[server:6675]        (cap):   1,337.12 ms,  0.96 GB
[server:6675]        setup:   3,460.81 ms,  0.96 GB
Error: Error parsing reflection configuration in server/src/main/resources/META-INF/reflect-config.json:
Could not resolve package.ClassThatLiesInTheAxisArchive for reflection configuration. Reason: java.lang.ClassNotFoundException: package.ClassThatLiesInTheAxisArchive. To allow unresolvable reflection configuration, use option -H:+AllowIncompleteClasspath
Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option ReflectionConfigurationFiles.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
[server:6675]      [total]:  11,871.31 ms,  0.96 GB
# Printing build artifacts to: server/build/native/nativeCompile/server.build_artifacts.txt
Error: Image build request failed with exit status 1
```

This is the relevant entry from reflect-config.json (I did censor the classname for now):
```json
{
  "name":"package.ClassThatLiesInTheAxisArchive",
  "methods":[{"name":"<init>","parameterTypes":[] }]
}
```

Is there any hope for this approach even working or is there maybe a sample axis2 server that sucessfully builds a native image?

**Comment by StefanLobbenmeier** [comment]
Just in case this is relevant to the issue:
```
java --version
openjdk 11.0.12 2021-07-20
OpenJDK Runtime Environment GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08)
OpenJDK 64-Bit Server VM GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08, mixed mode, sharing)
```

I used this gradle plugin:
`
    id("org.graalvm.buildtools.native") version "0.9.5"
`

**Comment by rodrigar-mx** [comment]
Hi @StefanLobbenmeier. I will take a closer look into it and get back to you.

**Comment by rodrigar-mx** [comment]
Hi @StefanLobbenmeier. I built this short demo https://github.com/rodrigar-mx/demo-axis2-graalvm-native-image. Please try it, and let me know if it does help you. Steps are indicated in README file.

**Comment by StefanLobbenmeier** [comment]
Thank you for creating this! It really helps out a lot.

I noticed that in the repository you created no axis2 service is loaded, right? Should I try adding one of the samples from the axis2 documentation to this? Then also the MockServer class would exactly match the producer I am having this me issue with. (I won’t be able to add the actual service due to licensing)

**Comment by rodrigar-mx** [comment]
I did not create any service because I do not have experience with axis2. Would be great if you add one of the samples in order to reproduce your issue.

**Comment by StefanLobbenmeier** [comment]
Ok I pushed the sample here: https://github.com/StefanLobbenmeier/demo-axis2-graalvm-native-image/tree/add-sample-aar

Compiling this to nativeImage shows the original warning of 
`WARNING: Could not resolve userguide.example1.MyService for reflection configuration. Reason: java.lang.ClassNotFoundException: userguide.example1.MyService.`

I guess it is now only a warning because the `AllowIncompleteClasspath` option?

At the end the build fails anyway, not sure if its because of the second warning or something else

```
[server:8290]    classlist:   6,027.46 ms,  0.96 GB
[server:8290]        (cap):   1,149.32 ms,  0.96 GB
WARNING: Could not resolve userguide.example1.MyService for reflection configuration. Reason: java.lang.ClassNotFoundException: userguide.example1.MyService.
[server:8290]        setup:   5,846.04 ms,  0.96 GB
WARNING: Could not register reflection metadata for org.apache.commons.logging.impl.Log4JLogger. Reason: java.lang.NoClassDefFoundError: org/apache/log4j/Priority.
[server:8290]     analysis:  27,528.23 ms,  2.30 GB
Fatal error:java.lang.InternalError: Enclosing method not found
        at java.base/java.lang.Class.getEnclosingMethod(Class.java:1296)
        at java.base/sun.reflect.generics.scope.ClassScope.computeEnclosingScope(ClassScope.java:50)
        at java.base/sun.reflect.generics.scope.AbstractScope.getEnclosingScope(AbstractScope.java:77)
        at java.base/sun.reflect.generics.scope.AbstractScope.lookup(AbstractScope.java:95)
        at java.base/sun.reflect.generics.factory.CoreReflectionFactory.findTypeVariable(CoreReflectionFactory.java:110)
        at java.base/sun.reflect.generics.visitor.Reifier.visitTypeVariableSignature(Reifier.java:165)
        at java.base/sun.reflect.generics.tree.TypeVariableSignature.accept(TypeVariableSignature.java:43)
        at java.base/sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
        at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
        at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
        at java.base/sun.reflect.generics.repository.ClassRepository.computeSuperclass(ClassRepository.java:104)
        at java.base/sun.reflect.generics.repository.ClassRepository.getSuperclass(ClassRepository.java:86)
        at java.base/java.lang.Class.getGenericSuperclass(Class.java:949)
        at com.oracle.svm.hosted.analysis.Inflation.fillGenericInfo(Inflation.java:365)
        at com.oracle.svm.hosted.analysis.Inflation.checkType(Inflation.java:139)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[server:8290]      [total]:     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at com.oracle.svm.hosted.analysis.Inflation.checkObjectGraph(Inflation.java:124)
        at com.oracle.graal.pointsto.BigBang.checkObjectGraph(BigBang.java:619)
        at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:587)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:707)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:532)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:491)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:380)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
 39,924.03 ms,  2.30 GB
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)
# Printing build artifacts to: /home/stefan/Documents/demo-axis2-graalvm-native-image/build/native/nativeCompile/server.build_artifacts.txt
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1916)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1584)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1545)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1532)

> Task :nativeCompile FAILED

```

**Comment by StefanLobbenmeier** [comment]
Actually that scary error has been solved before: https://github.com/oracle/graal/issues/1438
Fixed in Axiom: https://issues.apache.org/jira/browse/AXIOM-502

So all I had to do to get rid of this error is upgrade to axis 1.8.0, which uses axiom 1.3.0 instead of axiom 1.2.2:
```
+--- org.apache.axis2:axis2-adb:1.8.0
|    \--- org.apache.axis2:axis2-kernel:1.8.0
|         +--- org.apache.ws.commons.axiom:axiom-api:1.3.0
```

```
New output:
[server:10031]    classlist:   6,328.76 ms,  0.96 GB
[server:10031]        (cap):   1,395.72 ms,  0.96 GB
WARNING: Could not resolve userguide.example1.MyService for reflection configuration. Reason: java.lang.ClassNotFoundException: userguide.example1.MyService.
[server:10031]        setup:   5,774.18 ms,  0.96 GB
WARNING: Could not register reflection metadata for org.apache.commons.logging.impl.Log4JLogger. Reason: java.lang.NoClassDefFoundError: org/apache/log4j/Priority.
[server:10031]     (clinit):   1,048.85 ms,  5.54 GB
[server:10031]   (typeflow):  47,993.62 ms,  5.54 GB
[server:10031]    (objects):  29,673.31 ms,  5.54 GB
[server:10031]   (features):   3,041.20 ms,  5.54 GB
[server:10031]     analysis:  84,596.05 ms,  5.54 GB
[server:10031]     universe:   4,979.82 ms,  5.54 GB
[server:10031]      (parse):   4,909.79 ms,  5.54 GB
[server:10031]     (inline):   9,435.42 ms,  5.61 GB
[server:10031]    (compile):  79,391.52 ms,  5.91 GB
[server:10031]      compile:  98,611.01 ms,  5.91 GB
[server:10031]        image:  10,919.30 ms,  5.99 GB
[server:10031]        write:   1,701.37 ms,  5.99 GB
[server:10031]      [total]: 213,534.86 ms,  5.99 GB
# Printing build artifacts to: /home/stefan/Documents/demo-axis2-graalvm-native-image/build/native/nativeCompile/server.build_artifacts.txt
[native-image-plugin] Native Image written to: /home/stefan/Documents/demo-axis2-graalvm-native-image/build/native/nativeCompile
```

Output of running the native application:
```
build/native/nativeCompile/server 
Oct 05, 2021 2:10:54 PM org.apache.axiom.util.stax.dialect.StAXDialectDetector detectDialectFromJarManifest
WARNING: Unable to load manifest for StAX implementation at resource:
Oct 05, 2021 2:10:54 PM org.apache.axis2.deployment.AxisConfigBuilder processDeployers
WARNING: Unable to instantiate deployer org.apache.axis2.deployment.ServiceDeployer; see debug logs for more details
Oct 05, 2021 2:10:54 PM org.apache.axis2.deployment.URLBasedAxisConfigurator getAxisConfiguration
INFO: No repository found , module will be loaded from classpath
Oct 05, 2021 2:10:54 PM org.apache.axis2.transport.http.server.DefaultConnectionListener run
INFO: Listening on port 8080
SERVER IS RUNNING
[SimpleHTTPServer] Stop called
Oct 05, 2021 2:10:56 PM org.apache.axis2.transport.http.server.SimpleHttpServer destroy
INFO: Shut down connection listener
Oct 05, 2021 2:10:56 PM org.apache.axis2.transport.http.server.SimpleHttpServer destroy
INFO: Shut down HTTP processors
Oct 05, 2021 2:10:56 PM org.apache.axis2.transport.http.server.SimpleHttpServer destroy
INFO: HTTP protocol handler shut down
```
Checking the server now / if it is able to find it from the classpath

**Comment by StefanLobbenmeier** [comment]
Unfortunately the service is not loaded in the native version:
![image](https://user-images.githubusercontent.com/36509607/136020688-95d2a058-2e66-432e-93b4-d17ec811f916.png)
