### ISSUE TITLE
Native image build crashes 

### ISSUE THREAD

**Issue by sergey-morenets** [oracle/graal#3869]
**Describe the issue**

I have very simple Java class that I could build previously using earlier versions on GraalVM. However on the latest version I got the crash after rather long build (600 seconds).

**Steps to reproduce the issue**

Here's Dockerfile I used:

```
FROM openjdk:11-slim as jdk

COPY HelloWorld.java /sources/
WORKDIR /sources
RUN javac HelloWorld.java

FROM ghcr.io/graalvm/graalvm-ce:java11-21.2.0 as graalvm

RUN gu install native-image

COPY --from=jdk /sources/HelloWorld.class /

RUN native-image HelloWorld
```

Java class:

```
public class HelloWorld {
	public static void main(String[] args) {
		System.out.println("Hello, world");
	}
}
```

```
=== Image generator watchdog detected no activity. This can be a sign of a deadlock during image building. Dumping all stack traces. 
"main" Id=1 in RUNNABLE
    at java.base@11.0.12/java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
    at java.base@11.0.12/java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:248)
    at java.base@11.0.12/java.io.File.isDirectory(File.java:861)
    at app//com.oracle.svm.hosted.ResourcesFeature.scanDirectory(ResourcesFeature.java:268)
    at app//com.oracle.svm.hosted.ResourcesFeature.duringAnalysis(ResourcesFeature.java:215)
    at app//com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$12(NativeImageGenerator.java:730)
    at app//com.oracle.svm.hosted.NativeImageGenerator$$Lambda$844/0x00000007c0e92c40.accept(Unknown Source)
    at app//com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:71)
    at app//com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:730)
    at app//com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:532)
    at app//com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:491)
    at app//com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:380)
    at app//com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
    at app//com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
    at app//com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)

"Reference Handler" Id=2 in RUNNABLE
    at java.base@11.0.12/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
    at java.base@11.0.12/java.lang.ref.Reference.processPendingReferences(Reference.java:241)
    at java.base@11.0.12/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:213)

"Finalizer" Id=3 in WAITING on lock=java.lang.ref.ReferenceQueue$Lock@b03a37b
    at java.base@11.0.12/java.lang.Object.wait(Native Method)
    at java.base@11.0.12/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
    at java.base@11.0.12/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
    at java.base@11.0.12/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:170)

"Signal Dispatcher" Id=4 in RUNNABLE

"JVMCI-native CompilerThread0" Id=6 in RUNNABLE

"Common-Cleaner" Id=12 in TIMED_WAITING on lock=java.lang.ref.ReferenceQueue$Lock@7d441a4c
    at java.base@11.0.12/java.lang.Object.wait(Native Method)
    at java.base@11.0.12/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
    at java.base@11.0.12/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148)
    at java.base@11.0.12/java.lang.Thread.run(Thread.java:829)
    at java.base@11.0.12/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:134)

"native-image pid watcher" Id=14 in TIMED_WAITING on lock=java.util.TaskQueue@736f9479
    at java.base@11.0.12/java.lang.Object.wait(Native Method)
    at java.base@11.0.12/java.util.TimerThread.mainLoop(Timer.java:553)
    at java.base@11.0.12/java.util.TimerThread.run(Timer.java:506)

"ForkJoinPool.commonPool-worker-13" Id=35 in WAITING on lock=java.util.concurrent.ForkJoinPool@1cf6beae
    at java.base@11.0.12/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.12/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.12/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
    at java.base@11.0.12/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"Libgraal MBean Registration" Id=37 in TIMED_WAITING
    at java.base@11.0.12/java.lang.Thread.sleep(Native Method)
    at platform/jdk.internal.vm.compiler.management/org.graalvm.compiler.hotspot.management.Factory.run(Factory.java:104)

"Thread-1" Id=38 in RUNNABLE
    at java.management@11.0.12/sun.management.ThreadImpl.dumpThreads0(Native Method)
    at java.management@11.0.12/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:521)
    at java.management@11.0.12/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:509)
    at app//com.oracle.svm.hosted.DeadlockWatchdog.threadDump(DeadlockWatchdog.java:113)
    at app//com.oracle.svm.hosted.DeadlockWatchdog.watchdogThread(DeadlockWatchdog.java:80)
    at app//com.oracle.svm.hosted.DeadlockWatchdog$$Lambda$124/0x00000007c0972c40.run(Unknown Source)
    at java.base@11.0.12/java.lang.Thread.run(Thread.java:829)

"ForkJoinPool-2-worker-27" Id=45 in WAITING on lock=java.util.concurrent.ForkJoinPool@2ced8caa
    at java.base@11.0.12/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.12/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.12/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
    at java.base@11.0.12/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"ForkJoinPool-2-worker-9" Id=43 in WAITING on lock=java.util.concurrent.ForkJoinPool@2ced8caa
    at java.base@11.0.12/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.12/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.12/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
    at java.base@11.0.12/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"ForkJoinPool-2-worker-31" Id=47 in WAITING on lock=java.util.concurrent.ForkJoinPool@2ced8caa
    at java.base@11.0.12/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.12/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.12/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
    at java.base@11.0.12/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"ForkJoinPool-2-worker-17" Id=48 in WAITING on lock=java.util.concurrent.ForkJoinPool@2ced8caa
    at java.base@11.0.12/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.12/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.12/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
    at java.base@11.0.12/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"ForkJoinPool-2-worker-29" Id=54 in WAITING on lock=java.util.concurrent.ForkJoinPool@2ced8caa
    at java.base@11.0.12/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.12/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.12/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
    at java.base@11.0.12/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"ForkJoinPool-2-worker-7" Id=51 in TIMED_WAITING on lock=java.util.concurrent.ForkJoinPool@2ced8caa
    at java.base@11.0.12/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.12/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:275)
    at java.base@11.0.12/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1619)
    at java.base@11.0.12/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"ForkJoinPool-4-worker-3" Id=64 in WAITING on lock=java.util.concurrent.ForkJoinPool@3ae3ea37
    at java.base@11.0.12/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.12/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.12/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
    at java.base@11.0.12/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"Timer-0" Id=65 in TIMED_WAITING on lock=java.util.TaskQueue@6728015d
    at java.base@11.0.12/java.lang.Object.wait(Native Method)
    at java.base@11.0.12/java.util.TimerThread.mainLoop(Timer.java:553)
    at java.base@11.0.12/java.util.TimerThread.run(Timer.java:506)

"ForkJoinPool-2-worker-1" Id=68 in WAITING on lock=java.util.concurrent.ForkJoinPool@2ced8caa
    at java.base@11.0.12/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.12/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.12/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
    at java.base@11.0.12/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

=== Memory statistics (in MB):
=== Used heap size: 3056
=== Free heap size: 1218
=== Maximum heap size: 12743
=== Image generator watchdog is aborting image generation. To configure the watchdog, use the options -H:DeadlockWatchdogInterval=10 and -H:+DeadlockWatchdogExitOnTimeout
Error: Image build request failed with exit status 1
The command '/bin/sh -c native-image HelloWorld' returned a non-zero code: 1

```

**Comment by rodrigar-mx** [comment]
@sergey-morenets please change your Dockerfile to look like this
```
FROM ghcr.io/graalvm/graalvm-ce:java11-21.2.0 as graalvm

COPY HelloWorld.java /sources/
WORKDIR /sources
RUN javac HelloWorld.java

RUN gu install native-image

RUN native-image HelloWorld
a
```
GraalVM CE is based on openjdk so there is no need for pulling openjdk:11-slim. With GraalVM you can call directly `javac` for compiling your code. The error you reported was pretty rare but its cause might be some confligct between both jdk that were installed.

**Comment by rodrigar-mx** [comment]
Closing this issue because there has been no activity in last month.
