### ISSUE TITLE
java.lang.NoClassDefFoundError: sun.management.Util in runtime on JDK 17

### ISSUE THREAD

**Issue by phejl** [oracle/graal#3875]
**Describe the issue**
`ManagementFactory.getPlatformMBeanServer` in native-image (JDK 17) throws NoClassDefFoundError.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1.
```
public class Test {
    public static void main(String[] args) {
        System.out.println(java.lang.management.ManagementFactory.getPlatformMBeanServer());
    }
}
```
2. `javac Test.java`
3. `native-image --no-fallback --allow-incomplete-classpath Test`
4. `./test`
5. NoClassDefFoundError

**Describe GraalVM and your environment:**
```
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment GraalVM CE 21.3.0-dev (build 17+35-jvmci-21.3-b03)
OpenJDK 64-Bit Server VM GraalVM CE 21.3.0-dev (build 17+35-jvmci-21.3-b03, mixed mode, sharing)
```
 - JDK major version: **17**
 - OS: **Linux**
 - Architecture: **AMD64**

**More details**
```
Exception in thread "main" java.lang.NoClassDefFoundError: sun.management.Util
	at com.oracle.svm.core.jdk.management.SubstrateCompilationMXBean.getObjectName(SubstrateCompilationMXBean.java:47)
	at com.oracle.svm.core.jdk.management.ManagementSupport.addMXBean(ManagementSupport.java:267)
	at com.oracle.svm.core.jdk.management.ManagementSupport.getPlatformMBeanServer(ManagementSupport.java:259)
	at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:45)
	at Test.main(Test.java:4)
```

**Comment by phejl** [comment]
It seems this can be workarounded by adding `-J--add-exports=java.management/sun.management=ALL-UNNAMED` as an argument to `native-image`
