### ISSUE TITLE
native-image fails only on Windows when using --initialize-at-build-time with args

### ISSUE THREAD

**Issue by lread** [oracle/graal#3882]
**Thanks!**
First and foremost: thanks to the Graal team for native-image, it is truly an awesome work!

**Describe the issue**
The Clojure community is adapting to the fact that `--initialize-at-build-time` without arguments has been deprecated and will be removed in GraalVM v22.0.  (Clojure-created classes typically need to be initialized at build time and, for this reason, many Clojure projects that use Graal native-image currently use a global `--initialize-at-build-time` with no args).

While testing my project with `--initialize-at-build-time` with specific arguments, I have found that `native-image` works fine on macOS and Linux but fails with a `should not reach here` error under Windows.  
(Please note that native-image works without error on this same project across all OSes with an `--initialize-at-build-time` with no args)

I fully expect that I've missed some nuance, but also assume that a `should not reach here` under Windows is an internal error and one that the Graal team would be interested to hear about.

An oddity worth mentioning is that even though `native-image` fails with a `should not reach here` error on Windows, it still produces an image that runs and produces the expected output.

I have created [a reproduction of the issue in a GitHub repo](https://github.com/lread/repro-graal-build-time-windows).
You can see evidence of the behaviour [in output from GitHub Actions for GraalVM v21.2.0](https://github.com/lread/repro-graal-build-time-windows/runs/3842594144?check_suite_focus=true#step:9:348) and [GraalVM nightly](https://github.com/lread/repro-graal-build-time-windows/runs/3842594371?check_suite_focus=true#step:9:349) (output for v21.2.0 run from my Windows dev box also pasted below under "More details").

**Steps to reproduce the issue**
From a Windows computer, witness the failure via a PowerShell terminal session with native-image setup appropriatly:
1. `git clone https://github.com/lread/repro-graal-build-time-windows.git`
2. `cd repro-graal-build-time-windows`
3. From here you have options:
    1. To reproduce from pre-built jar: `.\repro1-jar.ps1`
    2. For other options see [notes for Graal team in repo](https://github.com/lread/repro-graal-build-time-windows#graal-team).

To witness success on maOS and Linux, repeat above in bash and run `./repro1-jar.sh`.    
 
On all OSes the resulting image can be run and will output:
```
Hello, running tests in sample namespace.

Testing hello-world.sample-test

Ran 1 tests containing 1 assertions.
0 failures, 0 errors.
All done.
```

**Describe GraalVM and your environment:**
 - GraalVM version 21.2.0 (also tried nightly 21.3.0-dev-20211008_1804-java11-amd64 via GitHub Actions)
 - JDK major version: 11
 - OS: Windows 10 (failing) macOS 10.15 (passing), Linux (passing)

**More details**
Output from `native-image` on Windows:
```
Executing [
'C:\Users\lee\scoop\apps\graalvm\current\bin\java.exe' \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
--add-exports=java.base/com.sun.crypto.provider=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.event=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.loader=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.logger=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.misc=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.module=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.org.xml.sax.helpers=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.perf=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.ref=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.util.xml.impl=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.util.xml=ALL-UNNAMED \
--add-exports=java.base/sun.invoke.util=ALL-UNNAMED \
--add-exports=java.base/sun.nio.ch=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.annotation=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.reflectiveObjects=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.repository=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.tree=ALL-UNNAMED \
--add-exports=java.base/sun.security.jca=ALL-UNNAMED \
--add-exports=java.base/sun.security.provider=ALL-UNNAMED \
--add-exports=java.base/sun.security.util=ALL-UNNAMED \
--add-exports=java.base/sun.text.spi=ALL-UNNAMED \
--add-exports=java.base/sun.util.calendar=ALL-UNNAMED \
--add-exports=java.base/sun.util.locale.provider=ALL-UNNAMED \
--add-exports=java.base/sun.util.resources=ALL-UNNAMED \
--add-exports=java.xml.crypto/org.jcp.xml.dsig.internal.dom=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.site=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.stack=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.common=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.sparc=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.runtime=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.services=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.sparc=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.events=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal.consumer=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal.handlers=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal.jfc=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal=ALL-UNNAMED \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx5987224776 \
-Duser.country=US \
-Duser.language=en \
-Djava.awt.headless=true \
-Dorg.graalvm.version=21.2.0 \
-Dorg.graalvm.config=CE \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
--module-path \
'C:\Users\lee\scoop\apps\graalvm\current\lib\truffle\truffle-api.jar' \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
'-javaagent:C:\Users\lee\scoop\apps\graalvm\current\lib\svm\builder\svm.jar' \
-cp \
'C:\Users\lee\scoop\apps\graalvm\current\lib\svm\builder\objectfile.jar;C:\Users\lee\scoop\apps\graalvm\current\lib\svm\builder\pointsto.jar;C:\Users\lee\scoop\apps\graalvm\current\lib\svm\builder\svm.jar' \
'com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus' \
-imagecp \
'Z:\proj\oss\-verify\wintmp\repro-graal-build-time-windows\exhibit\uber.jar;C:\Users\lee\scoop\apps\graalvm\current\lib\svm\library-support.jar' \
'-H:Path=Z:\proj\oss\-verify\wintmp\repro-graal-build-time-windows' \
-H:FallbackThreshold=0 \
-H:ClassInitialization=clojure:build_time,hello_world:build_time \
'-H:Class@manifest from file:///Z:/proj/oss/-verify/wintmp/repro-graal-build-time-windows/exhibit/uber.jar=hello_world.main' \
'-H:Name@manifest from file:///Z:/proj/oss/-verify/wintmp/repro-graal-build-time-windows/exhibit/uber.jar=uber' \
-H:Name=target/hello-world \
'-H:CLibraryPath=C:\Users\lee\scoop\apps\graalvm\current\lib\svm\clibraries\windows-amd64'
]
[target/hello-world:5964]    classlist:   2,448.66 ms,  0.96 GB
[target/hello-world:5964]        (cap):   2,025.90 ms,  0.96 GB
[target/hello-world:5964]        setup:   4,019.58 ms,  0.96 GB
[target/hello-world:5964]     (clinit):     421.76 ms,  2.80 GB
[target/hello-world:5964]   (typeflow):  14,845.19 ms,  2.80 GB
[target/hello-world:5964]    (objects):  14,304.87 ms,  2.80 GB
[target/hello-world:5964]   (features):     946.48 ms,  2.80 GB
[target/hello-world:5964]     analysis:  31,979.68 ms,  2.80 GB
[target/hello-world:5964]     universe:   1,801.26 ms,  2.80 GB
[target/hello-world:5964]      (parse):   1,608.98 ms,  2.80 GB
[target/hello-world:5964]     (inline):   3,179.87 ms,  2.62 GB
[target/hello-world:5964]    (compile):  25,275.50 ms,  2.56 GB
[target/hello-world:5964]      compile:  31,445.28 ms,  2.56 GB
[target/hello-world:5964]        image:   4,008.25 ms,  2.31 GB
[target/hello-world:5964]        write:     620.20 ms,  2.31 GB
Fatal error:com.oracle.svm.core.util.VMError$HostedError: should not reach here
        at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:64)
        at com.oracle.svm.hosted.jdk.JNIRegistrationSupport.makeShimDLL(JNIRegistrationSupport.java:256)
        at com.oracle.svm.hosted.jdk.JNIRegistrationSupport.makeShimDLLs(JNIRegistrationSupport.java:230)
        at com.oracle.svm.hosted.jdk.JNIRegistrationSupport.afterImageWrite(JNIRegistrationSupport.java:175)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$doRun$8(NativeImageGenerator.java:666)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:71)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:666)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:491)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:380)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)
[target/hello-world:5964]      [total]:  76,599.23 ms,  2.31 GB
# Printing build artifacts to: Z:\proj\oss\-verify\wintmp\repro-graal-build-time-windows\target\hello-world.build_artifacts.txt
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1916)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1584)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1545)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1532)
```

**Comment by lread** [comment]
Thanks so much @fernando-valdez, I look forward to learning more!

**Comment by lread** [comment]
@fernando-valdez, I have some good news: I have found the cause of the failure.

I use the `native-image` `-H:Name` option to specify my target executable.

My usage included a target dir: `-H:Name=target/hello-world`.

When running under Windows it seems that some `native-image` components recognize that `-H:Name` can include a directory and others do not. And/or some components recognize the forward slash as a path separator on Windows and others do not.

When I employed `--initialize-at-build-time` with args, I evidently evoked some different `native-image` components, hence the triggering of the failure on Windows.

My solution is to not specify any directory component in `-H:Name`. 
I instead specify the directory with `-H:Path`.
So instead of `-H:Name=target/hello-world`, I now have `-H:Path=target -H:Name=hello-world`.

I tested the changes to my [repro repo in this branch](https://github.com/lread/repro-graal-build-time-windows/commits/lread-separate-name-and-path) which has the [following differences from the main branch](https://github.com/lread/repro-graal-build-time-windows/compare/main...lread-separate-name-and-path). The ephemeral evidence of this passing can be found in [GitHub Actions results](https://github.com/lread/repro-graal-build-time-windows/actions/runs/1451616321).

I do see some [current docs that describe `-H:Name` and `-H:Path`](https://www.graalvm.org/reference-manual/native-image/HostedvsRuntimeOptions/#control-the-main-entry-points). 
I wonder if something more could be done to avoid this misuse (if that's what it was), of `-H:Name`. Ideas:
- Stress proper usage in docs
- Stress proper usage in `native-image --expert-options` help.
- Fail fast on improper usage
- Or... Allow and support directory within `-H:Name`
