### ISSUE TITLE
native image generation fails with unrecognized relocation (0x2a) in section `.text.JVM_FindLibraryEntry'

### ISSUE THREAD

**Issue by weitingyuk** [oracle/graal#3884]
Using GraalVM community edition of 21.2.0 to generate a native image fails with the following error:

/usr/bin/ld: /home/me/tmp/graalvm-ce-java11-21.2.0/lib/svm/clibraries/linux-amd64/libjvm.a(JvmFuncs.o): unrecognized relocation (0x2a) in section `.text.JVM_FindLibraryEntry'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status

**Steps to reproduce the issue**
Clone https://github.com/spring-guides/gs-rest-service
cd complete
Set GRAALVM_HOME environment variable to point to the Graal VM installation which has native-image installed
Using Apache Maven 3.6.3, run:
mvn -Pnative -DskipTests package

**Describe GraalVM and your environment:**
 - GraalVM version: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.2.0/graalvm-ce-java11-linux-amd64-21.2.0.tar.gz
 - JDK major version:  java 11
 - OS:  Debian GNU/Linux 8.9 (jessie)
 - Architecture: AMD64
 - gcc: gcc (Debian 4.9.2-10+deb8u2) 4.9.2
 - ld: GNU ld (GNU Binutils for Debian) 2.25

**More details**
The issue is similar to https://github.com/oracle/graal/issues/3678， but my started command is`mvn clean package -Pnative` and I have installed tools on my machine `sudo apt-get install build-essential libz-dev zlib1g-dev`

The complete log along with the native-image command which was used (through **Springboot** application is as follows):
```
2021/10/08 22:57:12 [rest-service-complete:814]      compile:  14,807.57 ms,  6.49 GB
2021/10/08 22:57:19 [rest-service-complete:814]        image:   7,638.36 ms,  6.49 GB
2021/10/08 22:57:20 [rest-service-complete:814]        write:     743.89 ms,  6.49 GB
2021/10/08 22:57:20 Fatal error:java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1
2021/10/08 22:57:20 
2021/10/08 22:57:20 Linker command executed:
2021/10/08 22:57:20 /usr/bin/gcc -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-15335437643850783627/exported_symbols.list -Wl,--exclude-libs,ALL -Wl,-x -o /opt/tiger/compile_path/src/code.byted.org/weitingyu/SpringBoot-GraalVM/target/rest-service-complete rest-service-complete.o /graalvm/lib/svm/clibraries/linux-amd64/liblibchelper.a /graalvm/lib/static/linux-amd64/glibc/libnet.a /graalvm/lib/static/linux-amd64/glibc/libextnet.a /graalvm/lib/static/linux-amd64/glibc/libnio.a /graalvm/lib/static/linux-amd64/glibc/libjava.a /graalvm/lib/static/linux-amd64/glibc/libfdlibm.a /graalvm/lib/static/linux-amd64/glibc/libsunec.a /graalvm/lib/static/linux-amd64/glibc/libzip.a /graalvm/lib/svm/clibraries/linux-amd64/libjvm.a -v -L/tmp/SVM-15335437643850783627 -L/graalvm/lib/static/linux-amd64/glibc -L/graalvm/lib/svm/clibraries/linux-amd64 -lstdc++ -lz -lpthread -ldl -lrt
2021/10/08 22:57:20 
2021/10/08 22:57:20 Linker command output:
2021/10/08 22:57:20 Using built-in specs.
2021/10/08 22:57:20 COLLECT_GCC=/usr/bin/gcc
2021/10/08 22:57:20 COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
2021/10/08 22:57:20 Target: x86_64-linux-gnu
2021/10/08 22:57:20 Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10+deb8u2' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --with-arch-32=i586 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
2021/10/08 22:57:20 Thread model: posix
2021/10/08 22:57:20 gcc version 4.9.2 (Debian 4.9.2-10+deb8u2) 
2021/10/08 22:57:20 COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/4.9/:/usr/lib/gcc/x86_64-linux-gnu/4.9/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/4.9/:/usr/lib/gcc/x86_64-linux-gnu/
2021/10/08 22:57:20 LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/4.9/:/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../:/lib/:/usr/lib/
2021/10/08 22:57:20 COLLECT_GCC_OPTIONS='-z' 'noexecstack' '-o' '/opt/tiger/compile_path/src/code.byted.org/weitingyu/SpringBoot-GraalVM/target/rest-service-complete' '-v' '-L/tmp/SVM-15335437643850783627' '-L/graalvm/lib/static/linux-amd64/glibc' '-L/graalvm/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
2021/10/08 22:57:20  /usr/lib/gcc/x86_64-linux-gnu/4.9/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/4.9/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper -plugin-opt=-fresolution=/tmp/ccGoC0BD.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --sysroot=/ --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o /opt/tiger/compile_path/src/code.byted.org/weitingyu/SpringBoot-GraalVM/target/rest-service-complete -z noexecstack /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/crt1.o /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/4.9/crtbegin.o -L/tmp/SVM-15335437643850783627 -L/graalvm/lib/static/linux-amd64/glibc -L/graalvm/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-linux-gnu/4.9 -L/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.9/../../.. --gc-sections --dynamic-list /tmp/SVM-15335437643850783627/exported_symbols.list --exclude-libs ALL -x rest-service-complete.o /graalvm/lib/svm/clibraries/linux-amd64/liblibchelper.a /graalvm/lib/static/linux-amd64/glibc/libnet.a /graalvm/lib/static/linux-amd64/glibc/libextnet.a /graalvm/lib/static/linux-amd64/glibc/libnio.a /graalvm/lib/static/linux-amd64/glibc/libjava.a /graalvm/lib/static/linux-amd64/glibc/libfdlibm.a /graalvm/lib/static/linux-amd64/glibc/libsunec.a /graalvm/lib/static/linux-amd64/glibc/libzip.a /graalvm/lib/svm/clibraries/linux-amd64/libjvm.a -lstdc++ -lz -lpthread -ldl -lrt -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-linux-gnu/4.9/crtend.o /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/crtn.o
2021/10/08 22:57:20 /usr/bin/ld: /graalvm/lib/svm/clibraries/linux-amd64/libjvm.a(JvmFuncs.o): unrecognized relocation (0x2a) in section `.text.JVM_FindLibraryEntry'
2021/10/08 22:57:20 /usr/bin/ld: final link failed: Bad value
2021/10/08 22:57:20 collect2: error: ld returned 1 exit status
2021/10/08 22:57:20 	at com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:499)
2021/10/08 22:57:20 	at com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:446)
2021/10/08 22:57:20 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:660)
2021/10/08 22:57:20 	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:491)
2021/10/08 22:57:20 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:380)
2021/10/08 22:57:20 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
2021/10/08 22:57:20 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
2021/10/08 22:57:20 	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)
2021/10/08 22:57:20 [rest-service-complete:814]      [total]:  67,635.75 ms,  6.49 GB
2021/10/08 22:57:20 # Printing build artifacts to: /opt/tiger/compile_path/src/code.byted.org/weitingyu/SpringBoot-GraalVM/target/rest-service-complete.build_artifacts.txt
2021/10/08 22:57:21 Error: Image build request failed with exit status 1
```

**Comment by rodrigar-mx** [comment]
Hi @weitingyuk . Thanks for reporting the issue. I will take a closer look into it and get back to you.

**Comment by rodrigar-mx** [comment]
Hi @weitingyuk. The problem seems to be caused by the old version of binutils. I managed to reproduce the same error with a simple HelloWorld native image program using Debian Jessie in a Dockerfile. The error does not present any more in Debian 9 onwards. If it is not possible for you to migrate to Debian 9, then try upgrading binutils tool, which I tried and also fixed the issue. I updated binutils to the 2.27 version. Please try it out and let me know any updates or questions.

**Comment by rodrigar-mx** [comment]
Closing this issue because there has been no activity in last month.
