### ISSUE TITLE
Static build fails with missing libraries

### ISSUE THREAD

**Issue by ebremer** [oracle/graal#3917]
**Describe the issue**
Project builds fine when NOT using --static.  It throws the following errors when using --static:
/usr/bin/ld: cannot find -lstdc++
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -ldl
/usr/bin/ld: cannot find -lz
/usr/bin/ld: cannot find -lrt
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
        at com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:502)
        at com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:449)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:657)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
[hatch:34407]      [total]:  39,835.00 ms,  5.99 GB

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. git clone https://github.com/ebremer/hatch.git
2. mvn clean package
3. native-image --static -H:ConfigurationFileDirectories=config -jar temp/hatch/target/hatch-1.1.1.jar --no-fallback --allow-incomplete-classpath --report-unsupported-elements-at-runtime hatch

**Describe GraalVM and your environment:**
https://github.com/graalvm/graalvm-ce-dev-builds/releases/download/21.3.0-dev-20211011_0738/llvm-toolchain-installable-java17-linux-amd64-dev.jar
 - JDK major version: 17
 - OS: CentosOS7
 - Architecture: AMD64

**Comment by mcraj017** [comment]
@ebremer thanks for the issue, please install glibc-devel, zlib-devel, libstdc++-static
for more information, please check the below link
https://www.graalvm.org/reference-manual/native-image/#prerequisites

**Comment by ebremer** [comment]
libstdc++-static was missing, however, the same error message occurs.

**Comment by mcraj017** [comment]
@ebremer thanks for the response, I will check further and update you

**Comment by mcraj017** [comment]
@ebremer please install g++ and try again

**Comment by ebremer** [comment]
> 
> 
> @ebremer please install g++ and try again

It was already installed.
