### ISSUE TITLE
[native-image] Https/Http2 protocol support.

### ISSUE THREAD

**Issue by sureshg** [oracle/graal#392]
Using the following kotlin code to make basic `HttpsURLConnection`
```kotlin
val url = URL("https://google.com").openConnection() as HttpsURLConnection
```
and used this command to generate the native-image.
```
$native-image -jar build/libs/graal-kotlin-aot-0.0.1.jar -H:EnableURLProtocols=https
```
Eventhough the error says it can be enabled using `-H:EnableURLProtocols=https`, it's not working.

```
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Accessing an URL protocol that was not enabled. The URL protocol https is not currently supported. It can still be enabled using -H:EnableURLProtocols=https. Supported URL protocols enabled by default: file. Additional supported URL protocols: http.
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Error.<init>(Error.java:70)
	at com.oracle.svm.core.jdk.UnsupportedFeatureError.<init>(UnsupportedFeatureError.java:29)
	at com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.unsupportedFeature(VMErrorSubstitutions.java:103)
	at com.oracle.svm.core.jdk.JavaNetSubstitutions.getURLStreamHandler(JavaNetSubstitutions.java:139)
	at com.oracle.svm.core.jdk.Target_java_net_URL.getURLStreamHandler(JavaNetSubstitutions.java:55)
```
IMHO, protocols  like `http`, `https` and `http2` should be enabled by default to make graal native-image genartion attractive for developers making cli tools.

**Comment by cstancu** [comment]
@sureshg the rationale behind enabling the `http` protocol on demand, i.e., using `-H:EnableURLProtocols=http`, is that you can start with a minimal image and can enable features as you need them to keep the overall size small.
As for `https`, that is currently under development. I agree that the error message is misleading. It will be improved soon.

**Comment by rtfpessoa** [comment]
@cstancu any news regarding this? or workaround?

**Comment by andreassimon** [comment]
> As for `https`, that is currently under development. I agree that the error message is misleading. It will be improved soon.

@cstancu Is there any place (besides this issue) to track progress on HTTPS support?

**Comment by cstancu** [comment]
@andreassimon this is the best place to track the progress. HTTPS support should be part of the next release, rc7.

**Comment by cstancu** [comment]
This should be fixed in https://github.com/oracle/graal/commit/76d043560571c3f6c4c0d76f89cb876451062251 which adds support for HTTPS and JCA security services. You need to run `native-image` with `--enable-https` or `--enable-url-protocols=https`. These features will be available in the rc7 realease. See [URL-PROTOCOLS.md](https://github.com/oracle/graal/blob/master/substratevm/URL-PROTOCOLS.md) and [JCA-SECURITY-SERVICES.md](https://github.com/oracle/graal/blob/master/substratevm/JCA-SECURITY-SERVICES.md) for details.
