### ISSUE TITLE
ArrayIndexOutOfBounds in java.lang.reflect.Executable.getAllGenericParameterTypes

### ISSUE THREAD

**Issue by spockz** [oracle/graal#3943]
**Describe the issue**
I am generating a native image for my internal application using the Spring Boot native build packs. The Spring Boot AOT misses a few things so I add my own config using the assisted configuration of the tracing agent. Regardless of whether I add that configuration to `META-INF/native-image` directly or to `META-INF/native-image/$group/$artifact` I get the `ArrayIndexOutOfBounds` below.

**Steps to reproduce the issue**
Sadly I cannot provide these as it is an internal project and the problem doesn't occur on our small example app.

**Describe GraalVM and your environment:**
 - GraalVM version: CE 21.2.0 && CE 21.3.0
 - JDK major version: **11**
 - OS: **Fedora**
 - Architecture: **AMD64**

**More details**
There is a bunch of warnings about missing classes from my application that should definitely be there. But maybe the spring-boot way of putting things in `BOOT-INF` is messing something up. The example spring boot app does compile to a native image though.

```
[sidecar:132348]     analysis:  17,034.06 ms,  6.46 GB
Fatal error:java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
 at java.base/java.lang.reflect.Executable.getAllGenericParameterTypes(Executable.java:314)
 at java.base/java.lang.reflect.Executable.getAnnotatedParameterTypes(Executable.java:705)
 at com.oracle.svm.reflect.target.Target_java_lang_reflect_Executable$AnnotatedTypeEncoder.encodeAnnotationTypes(Target_java_lang_reflect_Executable.java:293)
 at com.oracle.svm.reflect.target.Target_java_lang_reflect_Executable$AnnotatedParameterTypesComputer.compute(Target_java_lang_reflect_Executable.java:268)
 at com.oracle.svm.hosted.substitute.ComputedValueField.readValue(ComputedValueField.java:277)
 at com.oracle.svm.core.meta.ReadableJavaField.readFieldValue(ReadableJavaField.java:36)
 at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:99)
 at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:81)
 at com.oracle.graal.pointsto.ObjectScanner.scanField(ObjectScanner.java:160)
 at com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:333)
 at com.oracle.graal.pointsto.ObjectScanner.lambda$scanConstant$6(ObjectScanner.java:259)
 at com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:188)
 at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:172)
 at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
 at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
 at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
 at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
 at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
 at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by christianwimmer** [comment]
Without a reproducer, I was not able to diagnose the problem.

The exception occurs in the JDK, in `Executable.getAnnotatedParameterTypes`. So my suggestion is that you debug the native image generator yourself (by adding `--debug-attach` to the native-image command line and then attaching a Java debugger). When you are stopped at the exception breakpoint, you see the `Executable` object that causes the failure. Now you can check if a small reproducer where you just look up that method in a `main()` method and call `getAnnotatedParameterTypes` on it also fails. If yes, then you actually found a JDK bug.
