### ISSUE TITLE
Load and cpu share increase when moving from graal 21.1.0 to 21.3.0

### ISSUE THREAD

**Issue by hejcz** [oracle/graal#3959]
**Describe the issue**
When we try to update graal from 21.1.0 to 21.3.0 we consistently observe:
- load increase (+50% - from 20 to 30 on Intel(R) Xeon(R) Gold 6130 CPU) 
- cpu share increase. 21.1.0 has ~8% cpu share on startup and disappears from flamegraph eventually (or sometimes oscillates around 0.9%). 21.3.0 has **33.5%** cpu share and it doesn't get lower even after considerable amount of time (we had it for an hour on production).

Do you have any idea what might be wrong? We can add more details / do more tests if required.

**Steps to reproduce the issue**
We can't share our app but above happens every time consistently.

**Describe GraalVM and your environment:**

Our current setup is:
 - Graal version: **21.1.0**
 - JDK major version: **16.0.1+9-24**
 - OS: **Ubuntu 20.04.2 LTS (Focal Fossa)**
 - Docker image: **openjdk:16.0.1-buster**
 - Architecture: **AMD64**

Our target setup is:
 - Graal version: **21.3.0**
 - JDK major version: **17.0.1+12-39**
 - OS: **Ubuntu 20.04.2 LTS (Focal Fossa)**
 - Docker image: **openjdk:17.0.1-buster**
 - Architecture: **AMD64**

**More details**
**We use openjdk** (moving to graalvm even though it's suggested is not an option for us atm) and enable graal compiler as below.
```
-XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI 
--module-path=$APP_HOME/graal-compiler \
--upgrade-module-path=$APP_HOME/graal-compiler/compiler.jar:$APP_HOME/graal-compiler/compiler-management.jar
```
On each request we run 1 out of 25 scripts then 1 out of 12000 scripts and then optionally 1 out of 100 so there are many scripts to optimize.

Flamegraphs of TruffleCompiler look very similar but their cpu share differs vastly for 21.1.0 and 21.3.0. My colleague suggested that maybe for some reason graal fails to install optimized bytecode.

I attach graal compiler parts of flamegraphs for:
- 21.1.0 (after startup): https://raw.githubusercontent.com/hejcz/graal-bug/master/21_1_0_on_startup.trimmed.svg
- 21.3.0 (after running for some time): https://raw.githubusercontent.com/hejcz/graal-bug/master/21_3_0_all_time.trimmed.svg

**Comment by rodrigar-mx** [comment]
HI @hejcz. Thanks for reporting this issue. To have a deeper understanding of the issue it will be useful to perform some JFR recordings. Could you please run JFR in both graalvm versions and then share the produced files. To run JFR add the following flags to the command line when running your java application: 
 ```
-XX:+UnlockDiagnosticVMOptions
-XX:+DebugNonSafepoints
-XX:+FlightRecorder
-XX:+UnlockCommercialFeatures
-XX:StartFlightRecording=delay=<delay_before_start_recording_in_seconds>,duration=<duration_of_the_recording_in_seconds>,filename=<the_name_of_your_jfr_file.jfr>
```
Choose the duration of the recording appropriately so it can be appreciated the difference.

**Comment by jaroslawr** [comment]
@rodrigar-mx I work in one company with @hejcz , we identified the problem to be increased usage of the "non-profiled nmethods" CodeHeap - with Graal 21.1.0 and OpenJDK 16 we can run our app with the default setting of 128MB, it very rarely gets full and when it does, it logs something like this:

```
[1875.812s][warning][codecache] CodeHeap 'non-profiled nmethods' is full. Compiler has been disabled.
[1875.812s][warning][codecache] Try increasing the code heap size using -XX:NonProfiledCodeHeapSize=
CodeHeap 'non-profiled nmethods': size=118592Kb used=116331Kb max_used=118591Kb free=2261Kb
 bounds [0x00007fbbf93e4000, 0x00007fbc007b4000, 0x00007fbc007b4000]
CodeHeap 'profiled nmethods': size=118588Kb used=90351Kb max_used=100963Kb free=28236Kb
 bounds [0x00007fbbf2015000, 0x00007fbbf93e4000, 0x00007fbbf93e4000]
CodeHeap 'non-nmethods': size=8580Kb used=2350Kb max_used=5511Kb free=6229Kb
 bounds [0x00007fbbf17b4000, 0x00007fbbf1d44000, 0x00007fbbf2015000]
 total_blobs=21543 nmethods=20207 adapters=1206
 compilation: disabled (not enough contiguous free space left)
              stopped_count=1, restarted_count=0
 full_count=0
OpenJDK 64-Bit Server VM warning: CodeHeap 'non-profiled nmethods' is full. Compiler has been disabled.
OpenJDK 64-Bit Server VM warning: Try increasing the code heap size using -XX:NonProfiledCodeHeapSize=
```

With Graal 21.3.0 and OpenJDK 17.0.1 the message above does not seem to be printed, but when enabling `-XX:+PrintCodeCacheOnCompilation` the logs show that the 128MB gets filled in two minutes after the app starts and then it gets cleared very aggressively until it is nearly empty again and everything starts compiling again, hence the big CPU usage. We had to increase this part of the code heap to over 300MB for everything to fit. We now have a workaround and are fine with just closing the ticket, but it is a bit strange and maybe there is really some problem underneath this change of behaviour.

**Comment by rodrigar-mx** [comment]
Hi @jaroslawr. Could you please also perform some JFR recordings and share them with us, so we can get a picture of the performance between both versions. Try also with 22.0.0-dev latest [build](https://github.com/graalvm/graalvm-ce-dev-builds/releases).

**Comment by jaroslawr** [comment]
@rodrigar-mx I think we possibly have found the source of this, it seems something got broken when sharing an Engine instance between threads, have a look at this test:

```
package com.mycompany.app;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.atomic.AtomicInteger;

import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.Engine;
import org.graalvm.polyglot.HostAccess;
import org.graalvm.polyglot.Source;
import org.graalvm.polyglot.Value;
import org.junit.Test;

public class GraalTest {
    public static class Counter {
        private final AtomicInteger counter;

        public Counter() {
            this.counter = new AtomicInteger(0);
        }

        @HostAccess.Export
        public void increment() {
            counter.incrementAndGet();
        }
    }

    @Test
    public void testGraalPolyglotSpeed() {
        Counter counter = new Counter();

        ExecutorService executorService = Executors.newFixedThreadPool(10);
        Engine engine = Engine.newBuilder().build();
        List<Future> futures = new ArrayList<>();

        for (int i = 0; i < 10; i++) {
            final String script = "(function(counter) { for (var i = 0; i < 1000000; i++) { counter.increment(); }; return " + i + "; });";
            futures.add(executorService.submit(new Callable<String>() {
                public String call() {
                    try {
                        System.out.println("START");

                        Context context = Context.newBuilder("js")
                                .engine(engine)
                                .build();

                        Source source = Source.create("js", script);

                        Value fn = context.eval(source);
                        fn.execute(counter);

                    } catch (Exception e) {
                        System.out.println(e);
                        e.printStackTrace();
                    }

                    return "x";
                }
            }));
        }

        for (Future<String> future : futures) {
            try {
                future.get();
            } catch(Exception e) {
                System.out.println("Exception during get");
                System.out.println(e);
                e.printStackTrace();
            }
        }
    }
}
```

It executes just fine with Graal 21.1.0+Java16, but with Graal 21.3.0+Java17 it results in failed assertions inside Graal:

```
org.graalvm.polyglot.PolyglotException: java.lang.AssertionError
        at org.graalvm.truffle/com.oracle.truffle.host.HostExecuteNode.doInvoke(HostExecuteNode.java:871)
        at org.graalvm.truffle/com.oracle.truffle.host.HostExecuteNode.doFixed(HostExecuteNode.java:137)
        at org.graalvm.truffle/com.oracle.truffle.host.HostExecuteNodeGen.executeAndSpecialize(HostExecuteNodeGen.java:143)
        at org.graalvm.truffle/com.oracle.truffle.host.HostExecuteNodeGen.execute(HostExecuteNodeGen.java:96)
        at org.graalvm.truffle/com.oracle.truffle.host.HostObject.invokeMember(HostObject.java:451)
        at org.graalvm.truffle/com.oracle.truffle.host.HostObjectGen$InteropLibraryExports$Cached.invokeMemberNode_AndSpecialize(HostObjectGen.java:2695)
        at org.graalvm.truffle/com.oracle.truffle.host.HostObjectGen$InteropLibraryExports$Cached.invokeMember(HostObjectGen.java:2677)
        at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibrary$Asserts.invokeMember(InteropLibrary.java:3450)
        at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.invokeMember(InteropLibraryGen.java:8138)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$ForeignInvokeNode.executeCall(JSFunctionCallNode.java:1475)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:303)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:249)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$InvokeNode.execute(JSFunctionCallNode.java:722)
        at com.oracle.truffle.js.nodes.JavaScriptNode.executeVoid(JavaScriptNode.java:191)
        at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:80)
        at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:55)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedBlockNode.executeVoid(OptimizedBlockNode.java:120)
        at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:70)
        at com.oracle.truffle.js.nodes.control.AbstractRepeatingNode.executeBody(AbstractRepeatingNode.java:67)
        at com.oracle.truffle.js.nodes.control.WhileNode$WhileDoRepeatingNode.executeRepeating(WhileNode.java:231)
        at org.graalvm.truffle/com.oracle.truffle.api.nodes.RepeatingNode.executeRepeatingWithValue(RepeatingNode.java:112)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedOSRLoopNode.profilingLoop(OptimizedOSRLoopNode.java:158)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedOSRLoopNode.execute(OptimizedOSRLoopNode.java:109)
        at com.oracle.truffle.js.nodes.control.WhileNode.executeVoid(WhileNode.java:178)
        at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:80)
        at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:55)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedBlockNode.executeGeneric(OptimizedBlockNode.java:79)
        at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:75)
        at com.oracle.truffle.js.nodes.binary.DualNode.execute(DualNode.java:125)
        at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73)
        at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:150)
        at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:93)
        at <js> :anonymous(Unknown)
        at org.graalvm.sdk/org.graalvm.polyglot.Value.execute(Value.java:841)
        at com.mycompany.app.AppTest$1.call(AppTest.java:54)
        at com.mycompany.app.AppTest$1.call(AppTest.java:42)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by rodrigar-mx** [comment]
Hi @jaroslawr. I have run the test and verified this is an error. However, could you elaborate more why do you think this error is related to your performance issue.

**Comment by jaroslawr** [comment]
@rodrigar-mx  I am guessing, I might be wrong and it might be a separate issue, but the assertion that fails is this:

```
assert cache == hostContext.getGuestToHostCache();
```

It looks like there is some kind of race condition or bug that causes multiple different GuestToHostCodeCache instances to come into existence (at least this is how it looks like when I set a breakpoint on the assertion with a debugger). Now, the cause of the increased load turned out to be exhaustion of the JVM code cache which caused constant recompilations, the load mostly went back to normal when we increased the size of the code cache. Couldn't having multiple GuestToHostCodeCache instances cause additional compilations and ultimately increased JVM code cache usage?

**Comment by rodrigar-mx** [comment]
@jaroslawr I think the JFR recordings will provide more insights to this issue, so we can better understand the possible(s) cause(s).

**Comment by jaroslawr** [comment]
@rodrigar-mx I can send you the JFRs via email, I do not want to share them in public (you can find my email address on my GH profile if you on the other hand do not want to share yours publicly). Any chances for a fix for the issue that the test I provided illustrates, regardless whether it is related to the load or not? Should I report it as a separate Github issue?

**Comment by rodrigar-mx** [comment]
Hi @jaroslawr. Please report in a separate issue the new error found. After that issue is fixed, lets see if this is related to the original performance problem. Before that, perform the tests with [graalvm 22.0.0 pre-release](https://github.com/graalvm/graalvm-ce-dev-builds/releases).
