### ISSUE TITLE
Unsupported method in UnixAsynchronousSocketChannelImpl

### ISSUE THREAD

**Issue by lbialy** [oracle/graal#396]
Hi again :)

While trying to use `http4s-blaze-client` package during request handling following exception gets thrown:
```
java.util.concurrent.ExecutionException: Boxed Error
        at java.lang.Throwable.<init>(Throwable.java:287)
        at java.lang.Exception.<init>(Exception.java:84)
        at java.util.concurrent.ExecutionException.<init>(ExecutionException.java:77)
        at scala.concurrent.impl.Promise$.resolver(Promise.scala:83)
        at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:75)
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:280)
        at scala.concurrent.Promise.complete(Promise.scala:49)
        at scala.concurrent.Promise.complete$(Promise.scala:48)
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:183)
        at scala.concurrent.Promise.failure(Promise.scala:100)
        at scala.concurrent.Promise.failure$(Promise.scala:100)
        at scala.concurrent.impl.Promise$DefaultPromise.failure(Promise.scala:183)
        at org.http4s.blaze.channel.nio2.ClientChannelFactory$$anon$1.failed(ClientChannelFactory.scala:29)
        at org.http4s.blaze.channel.nio2.ClientChannelFactory$$anon$1.failed(ClientChannelFactory.scala:27)
        at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:128)
        at sun.nio.ch.Invoker$2.run(Invoker.java:218)
        at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:222)
        at Lcom/oracle/svm/core/code/CEntryPointCallStubs;.com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_002epthreadStartRoutine_0028com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_0024ThreadStartData_0029(generated:0)
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported method sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(int) is reachable: Native method. If you intend to use the Java Native Interface (JNI), specify -H:+JNI and see also -H:JNIConfigurationFiles=<path> (use -H:+PrintFlags for details)
        at java.lang.Throwable.<init>(Throwable.java:265)
        at java.lang.Error.<init>(Error.java:70)
        at com.oracle.svm.core.jdk.UnsupportedFeatureError.<init>(UnsupportedFeatureError.java:29)
        at com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.unsupportedFeature(VMErrorSubstitutions.java:103)
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(UnixAsynchronousSocketChannelImpl.java)
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:252)
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:198)
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
        at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:293)
        ... 3 common frames omitted
```

Recompilation with `-H:+JNI` transforms it into:
```
java.util.concurrent.ExecutionException: Boxed Error
        at java.lang.Throwable.<init>(Throwable.java:287)
        at java.lang.Exception.<init>(Exception.java:84)
        at java.util.concurrent.ExecutionException.<init>(ExecutionException.java:77)
        at scala.concurrent.impl.Promise$.resolver(Promise.scala:83)
        at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:75)
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:280)
        at scala.concurrent.Promise.complete(Promise.scala:49)
        at scala.concurrent.Promise.complete$(Promise.scala:48)
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:183)
        at scala.concurrent.Promise.failure(Promise.scala:100)
        at scala.concurrent.Promise.failure$(Promise.scala:100)
        at scala.concurrent.impl.Promise$DefaultPromise.failure(Promise.scala:183)
        at org.http4s.blaze.channel.nio2.ClientChannelFactory$$anon$1.failed(ClientChannelFactory.scala:29)
        at org.http4s.blaze.channel.nio2.ClientChannelFactory$$anon$1.failed(ClientChannelFactory.scala:27)
        at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:128)
        at sun.nio.ch.Invoker$2.run(Invoker.java:218)
        at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:222)
        at Lcom/oracle/svm/core/code/CEntryPointCallStubs;.com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_002epthreadStartRoutine_0028com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_0024ThreadStartData_0029(generated:0)
Caused by: java.lang.UnsatisfiedLinkError: sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(I)V [symbol: Java_sun_nio_ch_UnixAsynchronousSocketChannelImpl_checkConnect or Java_sun_nio_ch_UnixAsynchronousSocketChannelImpl_checkConnect__I]
        at java.lang.Throwable.<init>(Throwable.java:265)
        at java.lang.Error.<init>(Error.java:70)
        at java.lang.LinkageError.<init>(LinkageError.java:55)
        at java.lang.UnsatisfiedLinkError.<init>(UnsatisfiedLinkError.java:54)
        at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:123)
        at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:52)
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(UnixAsynchronousSocketChannelImpl.java)
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:252)
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:198)
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
        at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:293)
        ... 3 common frames omitted
```

**Comment by lbialy** [comment]
Any update on this? :smile:

**Comment by Peter-B-Kessler** [comment]
I wrote an implementation of `sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(I)V` but did not have a test for it.  So I wrote a test for it and got some of the dreaded "RecomputeFieldValue.FieldOffset automatic substitution failed." errors during image building.  I handed the repo to @cstancu.  I will make him an assignee.

**Comment by lbialy** [comment]
Still present in rc2 :cry:

**Comment by cstancu** [comment]
Fixed in https://github.com/oracle/graal/commit/69c31b4338ced46b3a3b7ba09d639f6267aa00ff.
