### ISSUE TITLE
NativeImage InvalidPathException

### ISSUE THREAD

**Issue by Leonardo-DGS** [oracle/graal#3960]
**Describe the issue**
When compiling anything with native-image, it gives an InvalidPathException

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. **native-image -jar [any jar file]**

**Describe GraalVM and your environment:**
 - GraalVM version: **CE 22.0.0-dev-20211028_1927**
 - JDK major version: **1.17**
 - OS: **Windows 10**
 - Architecture: **AMD64**

**More details**
```
Fatal error:java.nio.file.InvalidPathException: Illegal char <"> at index 42: C:\WINDOWS\System32\WindowsPowerShell\v1.0"\cl.exe
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.lambda$lookupSearchPath$1(CCompilerInvoker.java:497)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.lookupSearchPath(CCompilerInvoker.java:499)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.getCCompilerPath(CCompilerInvoker.java:509)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.getCCompilerInfo(CCompilerInvoker.java:356)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.<init>(CCompilerInvoker.java:70)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker$WindowsCCompilerInvoker.<init>(CCompilerInvoker.java:110)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.create(CCompilerInvoker.java:84)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:864)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:527)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
[BuildTools:7628]      [total]:   2,434.00 ms,  0.96 GB
```

**Comment by Leonardo-DGS** [comment]
> Path to cl.exe looks wrong to me. I believe cl.exe should come from Visual Studio rather than from PowerShell. Did you run vcvars64?

I just followed step-by-step the installation instructions, and simply doesn't work.

**Comment by fernando-valdez** [comment]
Hello @Leonardo-DGS, can you please share the instructions you followed?

**Comment by fernando-valdez** [comment]
Part 3 of this [page ](https://medium.com/graalvm/using-graalvm-and-native-image-on-windows-10-9954dc071311) describes how to use the x64 Native Tools Command Prompt. Please follow those steps and share your results

**Comment by Leonardo-DGS** [comment]
Sorry, I didn't initialized it with vcvars64.bat, I understood that it was sufficient to use the x64 Native Tools Command Prompt.
Thank you.
