### ISSUE TITLE
Assisted Configuration agent does not consider META-INF/native-image files

### ISSUE THREAD

**Issue by raphw** [oracle/graal#3968]
I have added a *native-image.properties* file to my library to specify that its static initializers are to be run at build-time, not at runtime. This is both to improve efficiency, as they are safe to run, and since the initializers trigger code that require code generation, so they would fail at runtime.

When running the assisted configuration agent, this agent still detects all code that is run from these static initialization blocks and adds code to *reflect-config.json* which is not really necessary when triggering the static blocks during build time. To make things worse, as there are classes generated in the static blocks, these classes cannot be found during the *native-image* phase what fails the build. If I manually remove my classes from the generated *reflect-config.json*, it works as expected. During *native-image* execution, the *native-image.properties*file is respected, and I would expect that the agent makes the same consideration

I would therefore suggest that the assisted support agent scans for *native-image.properties* files available and scans the stack trace to check if a discovery is triggered from a static initializer block that is executed during build time, to then exclude such discoveries.

Does this sound like a sensible extension?

**Comment by raphw** [comment]
To simplify the replication of the problem, I added a reproduction in [sample.zip](https://github.com/oracle/graal/files/7456681/sample.zip).

Running *native-image -cp bb.jar:. Sample* yields

> Error: Error parsing reflection configuration in file:/home/rafael/foo/META-INF/native-image/reflect-config.json:
> Could not resolve net.bytebuddy.utility.Invoker$Dispatcher for reflection configuration. Reason: java.lang.ClassNotFoundException: net.bytebuddy.utility.Invoker$Dispatcher. To allow unresolvable reflection configuration, use option --allow-incomplete-classpath

what can be avoided by deleting all entires in the *net.bytebuddy* namespace.

Note that there's a related issue to be solved to actually run the program where dynamic classes need to be stored. For now, this can be circumvent by adding the contents of [dynamic.zip](https://github.com/oracle/graal/files/7456758/dynamic.zip).

**Comment by raphw** [comment]
I realized now that you have an experimental option to extract class files which seems to work. I can however not build the image which yields the following null pointer exception:

Fatal error:java.lang.NullPointerException
	at com.oracle.svm.hosted.ClassPredefinitionFeature$PredefinedClassesRegistryImpl.add(ClassPredefinitionFeature.java:132)
	at com.oracle.svm.core.configure.PredefinedClassesConfigurationParser.parseClass(PredefinedClassesConfigurationParser.java:91)
	at com.oracle.svm.core.configure.PredefinedClassesConfigurationParser.parseOrigin(PredefinedClassesConfigurationParser.java:82)
	at com.oracle.svm.core.configure.PredefinedClassesConfigurationParser.parseAndRegister(PredefinedClassesConfigurationParser.java:69)
	at com.oracle.svm.core.configure.PredefinedClassesConfigurationParser.parseAndRegister(PredefinedClassesConfigurationParser.java:52)
	at com.oracle.svm.hosted.config.ConfigurationParserUtils.doParseAndRegister(ConfigurationParserUtils.java:127)
	at com.oracle.svm.hosted.config.ConfigurationParserUtils.lambda$parseAndRegisterConfigurations$3(ConfigurationParserUtils.java:113)
	at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:212)
	at com.oracle.svm.hosted.config.ConfigurationParserUtils$1.tryAdvance(ConfigurationParserUtils.java:106)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:491)
	at java.base/java.util.stream.IntPipeline.sum(IntPipeline.java:449)
	at com.oracle.svm.hosted.config.ConfigurationParserUtils.parseAndRegisterConfigurations(ConfigurationParserUtils.java:115)
	at com.oracle.svm.hosted.ClassPredefinitionFeature.afterRegistration(ClassPredefinitionFeature.java:73)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$15(NativeImageGenerator.java:825)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:73)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:825)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:527)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this, we will take a look into it and get back to you

**Comment by vjovanov** [comment]
I find this to be a great proposal; it will also reduce the image size. 
I would still keep a flag that disables this functionality in the agent as we have a flag to ignore what is in the jar config as well.
