### ISSUE TITLE
Calling `Record::equals` from multiple threads results in an `IllegalAccessException`

### ISSUE THREAD

**Issue by sickert** [oracle/graal#3973]
**Describe the issue**

Calling the `equals` method on a record from multiple threads results in a `IllegalAccessException` when run on a binary produced by native-image. Note that the attached snippet runs fine when using the included JVM of GraalVM.

**Steps to reproduce the issue**

Compile and run the following snippet:

```
import java.util.List;
import java.util.stream.IntStream;

public class Reproducer {

  record IntHolder(int x) {}

  private static final List<IntHolder> LIST = IntStream
    .range(0, 10000)
    .mapToObj(IntHolder::new)
    .toList();

  public static void callEquals() {
    for (var element1 : LIST) {
      for (var element2 : LIST) {
        element1.equals(element2);
      }
    }
  }

  public static void main(String[] args) throws InterruptedException {
    Thread t1 = new Thread(Reproducer::callEquals);
    Thread t2 = new Thread(Reproducer::callEquals);
    Thread t3 = new Thread(Reproducer::callEquals);
    Thread t4 = new Thread(Reproducer::callEquals);
    t1.start();
    t2.start();
    t3.start();
    t4.start();
    t1.join();
    t2.join();
    t3.join();
    t4.join();
  }
}
```

**Describe GraalVM and your environment:**
 - GraalVM version: 21.3.0
 - JDK major version: 17
 - OS: Ubuntu 20.04
 - Architecture: amd64
 - native-image --version: GraalVM 21.3.0 Java 17 CE (Java Version 17.0.1+12-jvmci-21.3-b05)

**More details**
The snippet above reports variations of the following stacktrace: 

```
Exception in thread "Thread-3" java.lang.IllegalAccessException: class com.oracle.svm.methodhandles.Util_java_lang_invoke_MethodHandle cannot access a member of class java.lang.invoke.DelegatingMethodHandle (in module java.base) with modifiers "protected abstract"
	at jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
	at java.lang.reflect.Method.invoke(Method.java:560)
	at com.oracle.svm.methodhandles.Util_java_lang_invoke_MethodHandle.invokeInternal(Target_java_lang_invoke_MethodHandle.java:222)
	at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:81)
	at java.lang.invoke.LambdaForm$NamedFunction.invokeWithArguments(LambdaForm.java:76)
	at java.lang.invoke.LambdaForm.interpretName(LambdaForm.java:964)
	at java.lang.invoke.LambdaForm.interpretWithArguments(LambdaForm.java:941)
	at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:87)
	at com.oracle.svm.methodhandles.MethodHandleIntrinsicImpl.execute(MethodHandleIntrinsicImpl.java:180)
	at com.oracle.svm.methodhandles.Util_java_lang_invoke_MethodHandle.invokeInternal(Target_java_lang_invoke_MethodHandle.java:147)
	at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:81)
	at java.lang.invoke.LambdaForm$NamedFunction.invokeWithArguments(LambdaForm.java:76)
	at java.lang.invoke.LambdaForm.interpretName(LambdaForm.java:964)
	at java.lang.invoke.LambdaForm.interpretWithArguments(LambdaForm.java:941)
	at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:87)
	at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:0)
	at java.lang.invoke.LambdaForm$MH.0x00000007c10a0800.linkToTargetMethod(LambdaForm$MH)
	at Reproducer$IntHolder.equals(Reproducer.java:27)
	at Reproducer.callEquals(Reproducer.java:37)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
```

**Comment by loicottet** [comment]
Fixed on master
