### ISSUE TITLE
How do I scan resource files in a directory

### ISSUE THREAD

**Issue by hanxiao34** [oracle/graal#3978]
We have specified a directory as the directory for storing configuration files. When starting, we need to scan this directory and load all configuration files in it. How can I do it?

the directory structure like this:
 
     META-INF
           --configs
               --my.a.properties
               --my.b.properties
               --my.c.properties
               .....................
- if I load the file  : 
```
 Utils.getResource("META-INF/configs/a.properties") 
```
it running ok!

But, I need to load all configuration files in this directory META-INF/configs .
and  the configuration file loader didn't know  which config file is here!

If I treat it as a file or dir,
```
File f=new  File("META-INF/configs");
Sysout.out.print(dir.exists);
```
it shows :   false 

help me !

**Comment by rodrigar-mx** [comment]
Hi @hanxiao34 . Maybe you can try   
`Path p = Path.of(Main.class.getResource("META-INF/configs/").toURI().getPath());` 
_*change Main to your current class_
then you can walk through it
```
System.out.println(Files.isDirectory(p));
Files.walk(p).forEach(System.out::println);
```
Otherwise, I will need you to provide more information about your execution environment:
i) graalvm version you are using, share the output of `java -version`
ii) OS you are using
iii) are you building a native image? if so, then share the build command you are using

**Comment by hanxiao34** [comment]
Wow,thxbro!!!!
My env：
GraalVM Community 21.3.0   Based on OpenJDK 11.0.13
OS :ubuntu 16.04
command : native-image  -jar solondemo.jar --allow-incomplete-classpath -H:+ReportExceptionStackTraces --enable-http
solondemo.jar  is a Java HTTP service demo,base on  solon,h2,jlhttp and other libraries。Build by jdk 1.8.0_171
The configurationfiles has been packaged into META-INF/native-image

**Comment by hanxiao34** [comment]
Hi @rodrigar-mx 
I tried what you said. But it still doesn't work。
my  code:
```
 String testprop="META-INF/solon/solon.extend.aspect.properties";
                    URL resource = Utils.getResource(classLoader, testprop);
                    PrintUtil.info(resource);
                    Properties tmp = new Properties();
                    tmp.load(new InputStreamReader(resource.openStream()));
                    Iterator<Object> iterator = tmp.keySet().iterator();
                    PrintUtil.blueln("keys in "+testprop);
                    while (iterator.hasNext()){
                       PrintUtil.blueln( String.valueOf(iterator.next()));
                    }
                    //Prove that this document exists
                    URL path4 = classLoader.getResource(testprop);
                    Path p4=Paths.get(path4.toString());
                    PrintUtil.blueln(testprop +"  isdir: "     +Files.isDirectory(p4) + "  exists:" +Files.exists(p4));

                    try {
                        PrintUtil.greenln("url1 :"+ url);
                        Path pa = Paths.get(url.toString());
                        PrintUtil.blueln(path +"  isdir: "     +Files.isDirectory(pa) + "  exists:" +Files.exists(pa));
                    }catch (Exception e){
                        e.printStackTrace();
                    }
                    try
                    {
                        PrintUtil.greenln("url2 :"+ url);
                        Path pa = Paths.get(url.getFile());
                        PrintUtil.blueln(path +"  isdir: "     +Files.isDirectory(pa) + "  exists:" +Files.exists(pa));
                    }catch (Exception e){
                        e.printStackTrace();
                    }

                    try{
                        PrintUtil.greenln("url3 :"+ url);
                        URI uri = url.toURI();
                        String path3 = uri.getPath();
                        PrintUtil.greenln("path3  :"+ path3);
                        Path p3 = Paths.get(path3);
                        PrintUtil.greenln("p3 exists :"+  Files.exists(p3));
                    }catch (Exception e){
                        e.printStackTrace();
                    }

```

and the  output:
```
[Solon] resource:META-INF/solon/solon.extend.aspect.properties
keys in META-INF/solon/solon.extend.aspect.properties
solon.plugin.priority
solon.plugin
META-INF/solon/solon.extend.aspect.properties  isdir: false  exists:false
url1 :resource:META-INF/solon
META-INF/solon  isdir: false  exists:false
url2 :resource:META-INF/solon
META-INF/solon  isdir: false  exists:false
url3 :resource:META-INF/solon
path3  :null
java.lang.NullPointerException
        at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:75)
        at sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
        at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
        at java.nio.file.Path.of(Path.java:147)
        at java.nio.file.Paths.get(Paths.java:69)
        at org.noear.solon.core.util.ResourceScaner.scan(ResourceScaner.java:106)
        at org.noear.solon.SolonProps.plugsScan(SolonProps.java:288)
        at org.noear.solon.SolonApp.init(SolonApp.java:86)
        at org.noear.solon.Solon.start(Solon.java:95)
        at org.noear.solon.Solon.start(Solon.java:66)
        at org.noear.solon.Solon.start(Solon.java:53)
        at com.hx.App.main(App.java:12)
```

**Comment by rodrigar-mx** [comment]
Hi @hanxiao34. Could you please try now change
```
 URL path4 = classLoader.getResource(testprop);
 Path p4=Paths.get(path4.toString());
 PrintUtil.blueln(testprop +"  isdir: "     +Files.isDirectory(p4) + "  exists:" +Files.exists(p4));
```
to
```
URL path4 =  Main.class.getResource(testprop);
Path p4 = Path.of(path4.getPath());
System.out.println(testprop +"  isdir: " +Files.isDirectory(p4) + "  exists:" +Files.exists(p4));
```
I tried it and get  isdir: false  and exists:true in the native image output.

**Comment by rodrigar-mx** [comment]
Closing this issue because there has been no activity during last month.
