### ISSUE TITLE
how to use  --target

### ISSUE THREAD

**Issue by hanxiao34** [oracle/graal#3986]
I saw the parameter -- target. I thought it could compile software packages on different platforms on a set of environment. But when I execute -- target = windows-amd64 on Linux, it prompts
```
Caused by: java.nio.file.NoSuchFileException: /home/hx/graalvm/graalvm-ce-java11-21.3.0/lib/svm/clibraries/windows-amd64
```

and then,  i copy windows-amd64 into there from window sdk and try again ,it prompts:

Error: Substitution target for com.oracle.svm.core.jdk.Target_java_io_WinNTFileSystem is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
com.oracle.svm.core.util.UserError$UserException: Substitution target for com.oracle.svm.core.jdk.Target_java_io_WinNTFileSystem is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
        at com.oracle.svm.core.util.UserError.abort(UserError.java:73)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findTargetClass(AnnotationSubstitutionProcessor.java:945)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:288)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:266)
        at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:912)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:839)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:527)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)

**Comment by rodrigar-mx** [comment]
Hi @hanxiao34. Cross compilation between different OS is not possible for the moment. There is already an open issue about that https://github.com/oracle/graal/issues/407. Possible alternatives are using VMs or docker images. 
--target option is used, for example, for building native images for mobile apps in gluon project https://github.com/gluonhq/gluon-samples.

**Comment by hanxiao34** [comment]
OK，tkx！
