### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method ensureClassInitialized on android

### ISSUE THREAD

**Issue by ghost** [oracle/graal#3994]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **21.3.0**
 - CE or EE: **CE**
 - JDK version: **Android Runtime**
 - OS and OS Version: **android 11RKQ1.200826.002**
 - Architecture: **aarch64**
 - The output of `java -Xinternalversion`:

**Have you verified this issue still happens when using the latest snapshot?**
You can find snapshot builds here: https://github.com/graalvm/graalvm-ce-dev-builds/releases

**Describe the issue**
A clear and concise description of the issue.
On Android, `void sun.misc.Unsafe.ensureClassInitialized(Class c)` does not exist, which causes NoSuchMethodError.
What should I do to use GraalJs on android?

**Code snippet or code repository that reproduces the issue**
```
Context context = Context.newBuilder("js").build();
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Add dependencies in build.gradle like this:
```
    implementation 'org.graalvm.js:js:21.3.0'
    implementation 'org.graalvm.js:js-scriptengine:21.3.0'
```
2. ```
        Context context = Context.newBuilder("js").build();
        Log.d("test", context.eval("js", "'aaa' + 'bbb'").asString());
   ```
3. Shift+F9 to debug app

**Expected behavior**
`D/test: aaabbb`


**Additional context**
Add any other context about the problem here. Specially important are stack traces or log output. Feel free to link to gists or to screenshots if necesary
<details><summary>Details</summary>

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hui1601.test, PID: 21945
    java.lang.NoSuchMethodError: No virtual method ensureClassInitialized(Ljava/lang/Class;)V in class Lsun/misc/Unsafe; or its super classes (declaration of 'sun.misc.Unsafe' appears in /apex/com.android.art/javalib/core-oj.jar)
        at com.oracle.truffle.api.library.LibraryFactory.ensureLibraryInitialized(LibraryFactory.java:384)
        at com.oracle.truffle.api.library.LibraryFactory.getUncached(LibraryFactory.java:364)
        at com.oracle.truffle.api.library.LibraryFactory.<init>(LibraryFactory.java:210)
        at com.oracle.truffle.api.interop.InteropLibraryGen.<init>(InteropLibraryGen.java:170)
        at com.oracle.truffle.api.interop.InteropLibraryGen.<clinit>(InteropLibraryGen.java:161)
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at com.oracle.truffle.api.library.LibraryFactory.loadGeneratedClass(LibraryFactory.java:771)
        at com.oracle.truffle.api.library.LibraryFactory.resolveImpl(LibraryFactory.java:734)
        at com.oracle.truffle.api.library.LibraryFactory.resolve(LibraryFactory.java:727)
        at com.oracle.truffle.api.interop.InteropLibrary.<clinit>(InteropLibrary.java:2878)
        at com.oracle.truffle.api.interop.InteropLibrary.getFactory(InteropLibrary.java:2842)
        at com.oracle.truffle.polyglot.PolyglotValueDispatch.<clinit>(PolyglotValueDispatch.java:156)
        at com.oracle.truffle.polyglot.PolyglotValueDispatch.createHostNull(PolyglotValueDispatch.java:1617)
        at com.oracle.truffle.polyglot.PolyglotImpl.initialize(PolyglotImpl.java:147)
        at org.graalvm.polyglot.impl.AbstractPolyglotImpl.setConstructors(AbstractPolyglotImpl.java:238)
        at org.graalvm.polyglot.Engine$1.loadAndValidateProviders(Engine.java:845)
        at org.graalvm.polyglot.Engine$1.run(Engine.java:818)
        at org.graalvm.polyglot.Engine$1.run(Engine.java:792)
        at java.security.AccessController.doPrivileged(AccessController.java:43)
        at org.graalvm.polyglot.Engine.initEngineImpl(Engine.java:792)
        at org.graalvm.polyglot.Engine.access$000(Engine.java:110)
        at org.graalvm.polyglot.Engine$ImplHolder.<clinit>(Engine.java:136)
        at org.graalvm.polyglot.Engine$ImplHolder.access$100(Engine.java:135)
        at org.graalvm.polyglot.Engine.getImpl(Engine.java:324)
        at org.graalvm.polyglot.HostAccess$Builder.targetTypeMapping(HostAccess.java:1071)
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.createNashornHostAccess(GraalJSScriptEngine.java:104)
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.<clinit>(GraalJSScriptEngine.java:99)
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.create(GraalJSScriptEngine.java:716)
        at com.hui1601.test.MainActivity.onCreate(MainActivity.java:21)
        at android.app.Activity.performCreate(Activity.java:8093)
        at android.app.Activity.performCreate(Activity.java:8067)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3452)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3651)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2104)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7861)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```
</details>

**Comment by oubidar-Abderrahim** [comment]
Currently, Android is not a supported platform for GraalVM. There is some work done by https://github.com/gluonhq for Android, not sure if it could help but you may want to check it.
