### ISSUE TITLE
Simple HTTP(S) request yields NoClassDefFoundError: sun.net.NetProperties on native image 21.3.0 CE/EE

### ISSUE THREAD

**Issue by sheltonwilson** [oracle/graal#4017]
Hi all,

We have a urgent bugfix request, our development has stopped because the bug has broken http/https functionality and downgrading is not an option because, Java Module System support which is introduced in version 21.3.0.

A simple program doing a HTTP/HTTPS get request is producing the bellow exception, the code was working on previous versions of Graalvm native image. We have tried using java 8 URLConnection, java 11 HttpClient, and Apache HttpClient, all give the same exception:  java.lang.NoClassDefFoundError: sun.net.NetProperties.

Exception:
```
Exception in thread "main" java.lang.NoClassDefFoundError: sun.net.NetProperties
        at com.oracle.svm.core.jdk.DefaultProxySelectorSystemProxiesAccessor.ensureInitialized(JavaNetSubstitutions.java:116)
        at com.oracle.svm.core.jdk.DefaultProxySelectorSystemProxiesAccessor.get(JavaNetSubstitutions.java:104)
        at sun.net.spi.DefaultProxySelector$4.run(DefaultProxySelector.java:250)
        at sun.net.spi.DefaultProxySelector$4.run(DefaultProxySelector.java:223)
        at java.security.AccessController.doPrivileged(AccessController.java:87)
        at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:222)
        at jdk.internal.net.http.HttpRequestImpl.retrieveProxy(HttpRequestImpl.java:287)
        at jdk.internal.net.http.HttpRequestImpl.<init>(HttpRequestImpl.java:133)
        at jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:603)
        at jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:540)
        at jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
        at com.mypackage.App.main(App.java:14)
```

Reproducer:
`package com.mypackge;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.net.http.HttpResponse.BodyHandlers;

public class App {

	public static void main(String[] args) throws Exception {
		HttpRequest request = HttpRequest.newBuilder().uri(new URI("https://postman-echo.com/get")).GET().build();
		HttpClient client = HttpClient.newHttpClient();
		HttpResponse<String> response = client.send(request, BodyHandlers.ofString());
		System.out.println(response.body());
	}
}
`
pom.xml:

`<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.securerandom.sandbox</groupId>
	<artifactId>nativetest</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>testnative</name>
	<url>http://maven.apache.org</url>

	<properties>
		<maven.compiler.source>11</maven.compiler.source>
		<maven.compiler.target>11</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>3.8.1</version>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>org.graalvm.nativeimage</groupId>
			<artifactId>svm</artifactId>
			<version>21.3.0</version>
		</dependency>

	</dependencies>
	<build>
		<sourceDirectory>src</sourceDirectory>
		<resources>
			<resource>
				<directory>src</directory>
				<excludes>
					<exclude>**/*.java</exclude>
				</excludes>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.0</version>
				<configuration>
					<source>11</source>
					<target>11</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.graalvm.buildtools</groupId>
				<artifactId>native-maven-plugin</artifactId>
				<version>0.9.7.1</version>
				<extensions>true</extensions>
				<configuration>
					<buildArgs>
						<buildArg>--report-unsupported-elements-at-runtime</buildArg>
						<buildArg>--no-fallback</buildArg>
						<buildArg>--allow-incomplete-classpath</buildArg>
						<buildArg>--enable-https</buildArg>
						<buildArg>--enable-http</buildArg>
						<buildArg>-H:+EnableAllSecurityServices</buildArg>
						<buildArg>-H:Name=NativeTest</buildArg>
						<buildArg>-H:NativeLinkerOption=/FORCE:UNRESOLVED</buildArg>
						<buildArg>com.mypackage.App</buildArg>
					</buildArgs>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>build</goal>
						</goals>
						<phase>package</phase>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>
</project>
`
 - GraalVM version: CE/EE 21.3.0
 - JDK major version: 11
 - OS: Windows 10
 - Architecture: AMD64

Note: 
removing option -H:NativeLinkerOption=/FORCE:UNRESOLVED
gives the following link errors which did not occur on previous versions:

`
net.lib(DefaultProxySelector.obj) : error LNK2019: unresolved external symbol __imp_WinHttpOpen referenced in function Java_sun_net_spi_DefaultProxySelector_init
net.lib(DefaultProxySelector.obj) : error LNK2019: unresolved external symbol __imp_WinHttpGetProxyForUrl referenced in function Java_sun_net_spi_DefaultProxySelector_getSystemProxies
net.lib(DefaultProxySelector.obj) : error LNK2019: unresolved external symbol __imp_WinHttpGetIEProxyConfigForCurrentUser referenced in function Java_sun_net_spi_DefaultProxySelector_getSystemProxies`

Our company would greatly appreciate it if if this could be fixed in a timely manner.

**Comment by mcraj017** [comment]
@sheltonwilson thanks for reporting the issue, we will check it out and get back to you

**Comment by mcraj017** [comment]
@sheltonwilson I did not encounter any error the provided reproducer.
please provide the steps to get this error:
```
mvn package
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< com.securerandom.sandbox:nativetest >-----------------
[INFO] Building testnative 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ nativetest ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ nativetest ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to C:\Users\mchouhan\Desktop\Issues\github\4017\nativetest\target\classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ nativetest ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\mchouhan\Desktop\Issues\github\4017\nativetest\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ nativetest ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ nativetest ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ nativetest ---
[INFO] Building jar: C:\Users\mchouhan\Desktop\Issues\github\4017\nativetest\target\nativetest-0.0.1-SNAPSHOT.jar
[INFO] 
[INFO] --- native-maven-plugin:0.9.7.1:build (default) @ nativetest ---
[INFO] ImageClasspath Entry: org.graalvm.nativeimage:svm:jar:21.3.0:compile (file:///C:/Users/mchouhan/.m2/repository/org/graalvm/nativeimage/svm/21.3.0/svm-21.3.0.jar)
[INFO] ImageClasspath Entry: org.graalvm.sdk:graal-sdk:jar:21.3.0:compile (file:///C:/Users/mchouhan/.m2/repository/org/graalvm/sdk/graal-sdk/21.3.0/graal-sdk-21.3.0.jar)
[WARNING] jar:file:///C:/Users/mchouhan/.m2/repository/org/graalvm/sdk/graal-sdk/21.3.0/graal-sdk-21.3.0.jar!/META-INF/native-image/org.graalvm.polyglot/native-image.properties does not match recommended META-INF/native-image/${groupId}/${artifactId}/native-image.properties layout.
[WARNING] jar:file:///C:/Users/mchouhan/.m2/repository/org/graalvm/sdk/graal-sdk/21.3.0/graal-sdk-21.3.0.jar!/META-INF/native-image/org.graalvm.home/native-image.properties does not match recommended META-INF/native-image/${groupId}/${artifactId}/native-image.properties layout.
[INFO] ImageClasspath Entry: org.graalvm.nativeimage:objectfile:jar:21.3.0:compile (file:///C:/Users/mchouhan/.m2/repository/org/graalvm/nativeimage/objectfile/21.3.0/objectfile-21.3.0.jar)
[INFO] ImageClasspath Entry: org.graalvm.nativeimage:pointsto:jar:21.3.0:compile (file:///C:/Users/mchouhan/.m2/repository/org/graalvm/nativeimage/pointsto/21.3.0/pointsto-21.3.0.jar)
[INFO] ImageClasspath Entry: org.graalvm.compiler:compiler:jar:21.3.0:compile (file:///C:/Users/mchouhan/.m2/repository/org/graalvm/compiler/compiler/21.3.0/compiler-21.3.0.jar)
[INFO] ImageClasspath Entry: org.graalvm.truffle:truffle-api:jar:21.3.0:compile (file:///C:/Users/mchouhan/.m2/repository/org/graalvm/truffle/truffle-api/21.3.0/truffle-api-21.3.0.jar)
[INFO] ImageClasspath Entry: com.securerandom.sandbox:nativetest:jar:0.0.1-SNAPSHOT (file:///C:/Users/mchouhan/Desktop/Issues/github/4017/nativetest/target/nativetest-0.0.1-SNAPSHOT.jar)
[INFO] Executing: c:\Users\mchouhan\Downloads\graalvm-ee-java11-21.3.0\bin\native-image.cmd -cp C:\Users\mchouhan\.m2\repository\org\graalvm\nativeimage\svm\21.3.0\svm-21.3.0.jar;C:\Users\mchouhan\.m2\repository\org\graalvm\sdk\graal-sdk\21.3.0\graal-sdk-21.3.0.jar;C:\Users\mchouhan\.m2\repository\org\graalvm\nativeimage\objectfile\21.3.0\objectfile-21.3.0.jar;C:\Users\mchouhan\.m2\repository\org\graalvm\nativeimage\pointsto\21.3.0\pointsto-21.3.0.jar;C:\Users\mchouhan\.m2\repository\org\graalvm\compiler\compiler\21.3.0\compiler-21.3.0.jar;C:\Users\mchouhan\.m2\repository\org\graalvm\truffle\truffle-api\21.3.0\truffle-api-21.3.0.jar;C:\Users\mchouhan\Desktop\Issues\github\4017\nativetest\target\nativetest-0.0.1-SNAPSHOT.jar --report-unsupported-elements-at-runtime --no-fallback --allow-incomplete-classpath --enable-https --enable-http -H:+EnableAllSecurityServices -H:Name=NativeTest -H:NativeLinkerOption=/FORCE:UNRESOLVED com.securerandom.sandbox.App -H:Name=nativetest
Warning: Option 'EnableAllSecurityServices' is deprecated and might be removed from future versions
[nativetest:19192]    classlist:     987.76 ms,  0.96 GB
[nativetest:19192]        (cap):   6,828.99 ms,  0.96 GB
[nativetest:19192]        setup:   9,838.80 ms,  0.96 GB
[nativetest:19192]     (clinit):     236.15 ms,  5.04 GB
[nativetest:19192]   (typeflow):   3,956.62 ms,  5.04 GB
[nativetest:19192]    (objects):   9,279.34 ms,  5.04 GB
[nativetest:19192]   (features):   2,237.37 ms,  5.04 GB
[nativetest:19192]     analysis:  16,512.06 ms,  5.04 GB
[nativetest:19192]     universe:     944.11 ms,  5.04 GB
[nativetest:19192]      (parse):     884.45 ms,  5.04 GB
[nativetest:19192]     (inline):   1,674.15 ms,  5.05 GB
[nativetest:19192]    (compile):  31,586.41 ms,  5.43 GB
[nativetest:19192]      compile:  35,647.43 ms,  5.43 GB
[nativetest:19192]        image:   1,521.89 ms,  5.43 GB
[nativetest:19192]        write:   6,327.43 ms,  5.43 GB
[nativetest:19192]      [total]:  72,029.63 ms,  5.43 GB
# Printing build artifacts to: C:\Users\mchouhan\Desktop\Issues\github\4017\nativetest\target\nativetest.build_artifacts.txt
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:16 min
[INFO] Finished at: 2021-11-18T17:08:02+08:00
[INFO] ------------------------------------------------------------------------

C:\Users\mchouhan\Desktop\Issues\github\4017\nativetest>target\nativetest.exe
{"args":{},"headers":{"x-forwarded-proto":"https","x-forwarded-port":"443","host":"postman-echo.com","x-amzn-trace-id":"Root=1-61961882-09b7794072a17550448f6915","user-agent":"Java-http-client/11.0.13"},"url":"https://postman-echo.com/get"}
```

**Comment by mcraj017** [comment]
Closing this issue as there is no activity in last 30 days
