### ISSUE TITLE
"There was an error linking the native image" when building the native image for a maven project

### ISSUE THREAD

**Issue by Instein98** [oracle/graal#4025]
**Describe the issue**
I was trying to build a native image to run the tests of a maven project. I write a scripts to include the loaded classes during `mvn test` in the reflection configuration file and use that configuration file to build the native image.

After excluding many loaded classes from the reflection configuration files, the native image failed: "Fatal error:java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1"

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. download [reproduce.zip](https://github.com/oracle/graal/files/7550025/reproduce.zip).
2. run `reproduce.sh` inside reproduce directory.

**Describe GraalVM and your environment:**
 - GraalVM version: **graalvm-ce-java8-linux-amd64-21.2.0** Downloaded from [here](https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.2.0/graalvm-ce-java8-linux-amd64-21.2.0.tar.gz)
 - JDK major version: **8**
 - OS: **Ubuntu 18.04**
 - Architecture: **AMD64**

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.
```
Executing [
/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/bin/java \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-d64 \
-XX:-UseJVMCIClassLoader \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx14g \
-Duser.country=US \
-Duser.language=en \
-Djava.awt.headless=true \
-Dorg.graalvm.version=21.2.0 \
-Dorg.graalvm.config=CE \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
-Djvmci.class.path.append=/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/jvmci/graal.jar \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-javaagent:/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/svm/builder/svm.jar \
-Xbootclasspath/a:/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/boot/graaljs-scriptengine.jar:/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/boot/graal-sdk.jar \
-cp \
/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/svm/builder/llvm-platform-specific-shadowed.jar:/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/svm/builder/pointsto.jar:/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/svm/builder/svm-llvm.jar:/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/svm/builder/svm.jar:/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/svm/builder/objectfile.jar:/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/svm/builder/llvm-wrapper-shadowed.jar:/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/svm/builder/javacpp-shadowed.jar:/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/jvmci/jvmci-api.jar:/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/jvmci/graal-management.jar:/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/jvmci/jvmci-hotspot.jar:/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/jvmci/graal-truffle-jfr-impl.jar:/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/jvmci/graal.jar:/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/resources.jar \
com.oracle.svm.hosted.NativeImageGeneratorRunner \
-watchpid \
1479512 \
-imagecp \
/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/boot/graaljs-scriptengine.jar:/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/boot/graal-sdk.jar:/home/ouyang/GraalBench/d4j-for-capgen/reproduce/target/test-classes:/home/ouyang/GraalBench/d4j-for-capgen/reproduce/target/classes:/home/ouyang/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/ouyang/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/ouyang/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/home/ouyang/.m2/repository/org/easymock/easymock/3.1/easymock-3.1.jar:/home/ouyang/.m2/repository/cglib/cglib-nodep/2.2.2/cglib-nodep-2.2.2.jar:/home/ouyang/.m2/repository/org/objenesis/objenesis/1.2/objenesis-1.2.jar:/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/svm/library-support.jar \
-H:Path=/home/ouyang/GraalBench/d4j-for-capgen/reproduce \
-H:+ReportExceptionStackTraces \
-H:+ReportUnsupportedElementsAtRuntime \
-H:ReflectionConfigurationFiles=ref.conf \
-H:FallbackThreshold=0 \
-H:+AllowIncompleteClasspath \
-H:+DumpTargetInfo \
-H:CLibraryPath=/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/svm/clibraries/linux-amd64 \
'-H:Class@explicit main-class=org.junit.runner.JUnitCore' \
'-H:Name@main-class lower case as image name=org.junit.runner.junitcore'
]
[org.junit.runner.junitcore:1479594]    classlist:     802.67 ms,  1.21 GB
[org.junit.runner.junitcore:1479594]        (cap):     474.02 ms,  1.58 GB
[org.junit.runner.junitcore:1479594]        setup:   1,986.72 ms,  1.58 GB
# Building image for target platform: org.graalvm.nativeimage.Platform$LINUX_AMD64
# Using native toolchain:
#   Name: GNU project C and C++ compiler (gcc)
#   Vendor: linux
#   Version: 7.5.0
#   Target architecture: x86_64
#   Path: /usr/bin/gcc
# Using CLibrary: com.oracle.svm.core.posix.linux.libc.GLibC
[org.junit.runner.junitcore:1479594]     (clinit):   1,289.01 ms,  5.17 GB
# Static libraries:
#   graalvm-ce-java8-21.2.0/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a
#   graalvm-ce-java8-21.2.0/jre/lib/libnet.a
#   graalvm-ce-java8-21.2.0/jre/lib/libnio.a
#   graalvm-ce-java8-21.2.0/jre/lib/libjava.a
#   graalvm-ce-java8-21.2.0/jre/lib/libfdlibm.a
#   graalvm-ce-java8-21.2.0/jre/lib/libsunec.a
#   graalvm-ce-java8-21.2.0/jre/lib/libzip.a
#   graalvm-ce-java8-21.2.0/jre/lib/svm/clibraries/linux-amd64/libjvm.a
# Other libraries: stdc++,z,pthread,dl,rt
[org.junit.runner.junitcore:1479594]   (typeflow):   9,321.88 ms,  5.17 GB
[org.junit.runner.junitcore:1479594]    (objects):  34,144.57 ms,  5.17 GB
[org.junit.runner.junitcore:1479594]   (features):   2,477.13 ms,  5.17 GB
[org.junit.runner.junitcore:1479594]     analysis:  48,875.27 ms,  5.17 GB
[org.junit.runner.junitcore:1479594]     universe:   4,004.42 ms,  5.17 GB
[org.junit.runner.junitcore:1479594]      (parse):   1,280.52 ms,  5.29 GB
[org.junit.runner.junitcore:1479594]     (inline):   2,210.34 ms,  5.41 GB
[org.junit.runner.junitcore:1479594]    (compile):  11,013.46 ms,  6.19 GB
[org.junit.runner.junitcore:1479594]      compile:  17,206.32 ms,  6.19 GB
[org.junit.runner.junitcore:1479594]        image:   7,794.05 ms,  6.18 GB
[org.junit.runner.junitcore:1479594]        write:     796.16 ms,  6.18 GB
Fatal error:java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1

Linker command executed:
/usr/bin/gcc -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-7186100394974649446/exported_symbols.list -Wl,--exclude-libs,ALL -Wl,-x -o /home/ouyang/GraalBench/d4j-for-capgen/reproduce/org.junit.runner.junitcore org.junit.runner.junitcore.o /home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/libnet.a /home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/libnio.a /home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/libjava.a /home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/libfdlibm.a /home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/libsunec.a /home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/libzip.a /home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/svm/clibraries/linux-amd64/libjvm.a -v -L/tmp/SVM-7186100394974649446 -L/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib -L/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/svm/clibraries/linux-amd64 -lstdc++ -lz -lpthread -ldl -lrt

Linker command output:
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-z' 'noexecstack' '-o' '/home/ouyang/GraalBench/d4j-for-capgen/reproduce/org.junit.runner.junitcore' '-v' '-L/tmp/SVM-7186100394974649446' '-L/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib' '-L/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/7/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/7/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper -plugin-opt=-fresolution=/tmp/ccjwmdjc.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -z now -z relro -o /home/ouyang/GraalBench/d4j-for-capgen/reproduce/org.junit.runner.junitcore -z noexecstack /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/7/crtbeginS.o -L/tmp/SVM-7186100394974649446 -L/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib -L/home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/7/../../.. --gc-sections --dynamic-list /tmp/SVM-7186100394974649446/exported_symbols.list --exclude-libs ALL -x org.junit.runner.junitcore.o /home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/libnet.a /home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/libnio.a /home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/libjava.a /home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/libfdlibm.a /home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/libsunec.a /home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/libzip.a /home/ouyang/GraalBench/d4j-for-capgen/reproduce/graalvm-ce-java8-21.2.0/jre/lib/svm/clibraries/linux-amd64/libjvm.a -lstdc++ -lz -lpthread -ldl -lrt -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-linux-gnu/7/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crtn.o
org.junit.runner.junitcore.o:(.data+0x570): undefined reference to `Java_java_lang_Compiler_initialize'
collect2: error: ld returned 1 exit status
	at com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:499)
	at com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:446)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:660)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:491)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:380)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
[org.junit.runner.junitcore:1479594]      [total]:  81,686.73 ms,  6.18 GB
# Printing build artifacts to: /home/ouyang/GraalBench/d4j-for-capgen/reproduce/org.junit.runner.junitcore.build_artifacts.txt
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1916)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1584)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1545)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1532)```

**Comment by rodrigar-mx** [comment]
Hi @Instein98. Could you please try using the latest graalvm version: 21.3.0. You can use either jdk 11 or jdk 17 based versions. jdk 8 is no longer supported.

**Comment by rodrigar-mx** [comment]
Closing this issue because no response has been given during the last months.
