### ISSUE TITLE
Issues with AtomicReferenceFieldUpdater

### ISSUE THREAD

**Issue by OlegIlyenko** [oracle/graal#406]
I tried to use GraalVM CE 1.0.0-rc1 in a scala project but faced an issue with `AtomicReferenceFieldUpdater` which is used in scala's `TrieMap`. 

I prepared a very minimal repository that reproduces the issue and contains more info (including the compiled image and verbose output from native-image):

https://github.com/OlegIlyenko/graalvm-sangria-test

The native-image is compiled successfully, but when the executable is run, it throws following exception:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.lang.Throwable.<init>(Throwable.java:310)
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:89)
	at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)
	at com.oracle.svm.reflect.proxies.Proxy_1_Main_main.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:199)
	at Lcom/oracle/svm/core/code/CEntryPointCallStubs;.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Caused by: java.lang.InternalError
	at java.lang.Throwable.<init>(Throwable.java:250)
	at java.lang.Error.<init>(Error.java:58)
	at java.lang.VirtualMachineError.<init>(VirtualMachineError.java:43)
	at java.lang.InternalError.<init>(InternalError.java:42)
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:94)
	at sun.reflect.misc.ReflectUtil.ensureMemberAccess(ReflectUtil.java:103)
	at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.<init>(AtomicReferenceFieldUpdater.java:327)
	at java.util.concurrent.atomic.AtomicReferenceFieldUpdater.newUpdater(AtomicReferenceFieldUpdater.java:110)
	at scala.collection.concurrent.TrieMap.<init>(TrieMap.scala:647)
	at scala.collection.concurrent.TrieMap.<init>(TrieMap.scala:652)
	at scala.collection.concurrent.TrieMap$.empty(TrieMap.scala:981)
	at scala.collection.concurrent.TrieMap$.empty(TrieMap.scala:976)
	at scala.collection.generic.MutableMapFactory.newBuilder(MutableMapFactory.scala:30)
	at scala.collection.generic.GenMapFactory.apply(GenMapFactory.scala:48)
	at sangria.validation.SchemaBasedDocumentAnalyzer.<init>(SchemaBasedDocumentAnalyzer.scala:17)
	at sangria.validation.ValidationContext.<init>(QueryValidator.scala:136)
	at sangria.validation.RuleBasedQueryValidator.validateQuery(QueryValidator.scala:61)
	at sangria.execution.Executor.$anonfun$execute$1(Executor.scala:79)
	at sangria.execution.Executor$$Lambda$461/1872166244.apply(Unknown Source)
	at sangria.execution.TimeMeasurement$.measure(TimeMeasurement.scala:8)
	at sangria.execution.Executor.execute(Executor.scala:79)
	at sangria.execution.Executor$.execute(Executor.scala:199)
	at Main$.main(Main.scala:17)
	at Main.main(Main.scala)
	... 4 more
```

**Comment by cstancu** [comment]
@OlegIlyenko the `AtomicReferenceFieldUpdater` issue should be fixed in https://github.com/oracle/graal/commit/3a120f4e2ba530d18a3e6c46e5b9141becd37d90. You can [build from source](https://github.com/oracle/graal/tree/master/substratevm#quick-start) to get the fix.

**Comment by OlegIlyenko** [comment]
Awesome, thanks a lot! :+1:
