### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: no pkcs11wrapper in java.library.path

### ISSUE THREAD

**Issue by aproust33** [oracle/graal#4064]
I am trying to migrate an application to native, using graalVM. This app needs a dependance for crpyto purpose. It is currently using this lib (https://jce.iaik.tugraz.at/products/core-crypto-toolkits/pkcs11-wrapper/). This app is a windows one.

This lib use a DLL (pkcs11wrapper.dll) included in the jar. I am currently building the jar, then building the native image using this command :
```
native-image -cp target\single-proxy-native-0.0.1-SNAPSHOT.jar;C:\dev\tools\m2\iaik\pkcs\pkcs11-wrapper\1.4\pkcs11-wrapper-1.4.jar fr.devboxsante.cps.nativ.NativeCpsApplication -Djava.library.path=C:\dev\
```
(C:\dev\ contains the right dll)

It make the exe file, but when i try to execute it, it fails :
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no pkcs11wrapper in java.library.path at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryRelative(NativeLibrarySupport.java:132) at java.lang.ClassLoader.loadLibrary(ClassLoader.java:197) at java.lang.Runtime.loadLibrary0(Runtime.java:830) at java.lang.System.loadLibrary(System.java:1871) at fr.devboxsante.cps.nativ.NativeCpsApplication.main(NativeCpsApplication.java:15)
```
I have tryied a lot of things, putting the dll in the bin folder of the native jvm, adding it to the system32 folder, ... You can find the project here

**Steps to reproduce the issue**

1. Clone https://github.com/aproust33/pkcs-native/tree/main
2. Donwload the pkcs11-wrapper jar and add it to your mvn repo
3. Run mvn package
4. Then native-image -cp target\single-proxy-native-0.0.1-SNAPSHOT.jar;C:\dev\tools\m2\iaik\pkcs\pkcs11-wrapper\1.4\pkcs11-wrapper-1.4.jar fr.devboxsante.cps.nativ.NativeCpsApplication -Djava.library.path=C:\dev\

**Describe GraalVM and your environment:**
 - openjdk 11.0.12 2021-07-20
 - OpenJDK Runtime Environment GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08)
 - OpenJDK 64-Bit Server VM GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08, mixed mode, sharing)*
 - OS: Windows 10
 - Architecture: **[e.g.: AMD64]**

**Comment by mcraj017** [comment]
@aproust33 thanks for reporting the issue, we will check it out and get back to you

**Comment by swaechter** [comment]
I want to use the same IAIK PKCS11 JNI wrapper to digitally sign PDFs. I wasn't aware that a stranger from the internet ran into the *exact* same issue like me - but a few weeks earlier (Mandatory XKCD reference https://xkcd.com/979/.

I forked your repository (https://github.com/swaechter/pkcs-native) and documented all my commands, so you @mcraj017 can reproduce the problem. In addition I made a few changes:

* Switch from Maven to Gradle
* Use the shade plugin to create a fat JAR that includes all third party dependencies
* Include the PKCS11 JAR and DLL files, so it's easier to share them

I found the issue https://github.com/oracle/graal/issues/3359 that recommends installing a `Feature` which I did:

````java
package fr.devboxsante.cps.nativ;

import com.oracle.svm.core.annotate.AutomaticFeature;
import com.oracle.svm.core.jdk.NativeLibrarySupport;
import com.oracle.svm.core.jdk.PlatformNativeLibrarySupport;
import com.oracle.svm.hosted.FeatureImpl;
import com.oracle.svm.hosted.c.NativeLibraries;
import org.graalvm.nativeimage.hosted.Feature;

@AutomaticFeature
public class LibraryFeature implements Feature {

    @Override
    public void beforeAnalysis(BeforeAnalysisAccess access) {
        NativeLibrarySupport.singleton().preregisterUninitializedBuiltinLibrary("pkcs11wrapper");
        PlatformNativeLibrarySupport.singleton().addBuiltinPkgNativePrefix("iaik.pkcs.pkcs11.wrapper.PKCS11Implementation"); // TODO: Not sure if this is correct
        NativeLibraries nativeLibraries = ((FeatureImpl.BeforeAnalysisAccessImpl) access).getNativeLibraries();
        nativeLibraries.addStaticJniLibrary("pkcs11wrapper");
    }
}
````

Rebuild and run the native-image:

````powershell
.\gradlew.bat clean build

native-image.cmd --allow-incomplete-classpath --no-fallback -H:CLibraryPath=C:/Windows/System32/drivers/ --static -jar build\libs\native.jar

C:\Users\swaechter\Downloads\pkcs-native>native.exe
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Method.java:568)
        at fr.devboxsante.cps.nativ.NativeCpsApplication.main(NativeCpsApplication.java:18)
Caused by: java.lang.UnsatisfiedLinkError: iaik.pkcs.pkcs11.wrapper.PKCS11Implementation.initializeLibrary()V [symbol: Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_initializeLibrary or Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_initializeLibrary__]
        at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:153)
        at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
        at iaik.pkcs.pkcs11.wrapper.PKCS11Implementation.initializeLibrary(PKCS11Implementation.java)
        ... 2 more
````

So it looks like the system can find the library and tries to load it - but fails. Any ideas? Maybe my package prefix is wrong?

Best,
Simon

**Comment by swaechter** [comment]
I upgraded my example: I included the Java JNI glue code into the project to prevent javac compiler issues from older Java installations + also rebuilt the DLL with MSVC 2019. Still the same problem.

The JNI header looks like this and the signature looks ok, so I guess it's a GraalVM issue or me using the wrong commands (E.g. library is not linked/integrated and missing at runtime).

![Problem](https://user-images.githubusercontent.com/5626755/146929951-400a0124-38e3-4525-8a0e-49a676a29fb7.png)

```powershell
Dump of file C:\Windows\System32\drivers\pkcs11wrapper.dll

File Type: DLL

  Section contains the following exports for pkcs11wrapper.dll

    00000000 characteristics
    FFFFFFFF time date stamp
        0.00 version
           1 ordinal base
          71 number of functions
          71 number of names

    ordinal hint RVA      name

          1    0 00001000 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1CancelFunction = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1CancelFunction
          2    1 00001060 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1CloseAllSessions = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1CloseAllSessions
          3    2 00001120 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1CloseSession = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1CloseSession
          4    3 000011C0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1CopyObject = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1CopyObject
          5    4 00001330 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1CreateObject = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1CreateObject
          6    5 00001480 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1Decrypt = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1Decrypt
          7    6 000016A0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1DecryptDigestUpdate = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1DecryptDigestUpdate
          8    7 000017F0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1DecryptFinal = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1DecryptFinal
          9    8 00001980 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1DecryptInit = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1DecryptInit
         10    9 00001A40 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1DecryptUpdate = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1DecryptUpdate
         11    A 00001C60 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1DecryptVerifyUpdate = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1DecryptVerifyUpdate
         12    B 00001DB0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1DeriveKey = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1DeriveKey
         13    C 00001FA0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1DestroyObject = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1DestroyObject
         14    D 00002020 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1Digest = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1Digest
         15    E 00002170 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1DigestEncryptUpdate = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1DigestEncryptUpdate
         16    F 000022C0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1DigestFinal = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1DigestFinal
         17   10 000023D0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1DigestInit = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1DigestInit
         18   11 00002490 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1DigestKey = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1DigestKey
         19   12 00002510 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1DigestUpdate = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1DigestUpdate
         20   13 000025C0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1Encrypt = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1Encrypt
         21   14 00002710 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1EncryptFinal = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1EncryptFinal
         22   15 00002820 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1EncryptInit = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1EncryptInit
         23   16 000028E0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1EncryptUpdate = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1EncryptUpdate
         24   17 00002A30 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1Finalize = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1Finalize
         25   18 00002A90 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1FindObjects = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1FindObjects
         26   19 00002B80 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1FindObjectsFinal = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1FindObjectsFinal
         27   1A 00002BE0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1FindObjectsInit = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1FindObjectsInit
         28   1B 00002D10 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GenerateKey = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GenerateKey
         29   1C 00002F10 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GenerateKeyPair = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GenerateKeyPair
         30   1D 000031D0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GenerateRandom = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GenerateRandom
         31   1E 000032A0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GetAttributeValue = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GetAttributeValue
         32   1F 00003630 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GetFunctionStatus = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GetFunctionStatus
         33   20 00003690 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GetInfo = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GetInfo
         34   21 00003710 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GetMechanismInfo = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GetMechanismInfo
         35   22 000037A0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GetMechanismList = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GetMechanismList
         36   23 000038B0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GetObjectSize = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GetObjectSize
         37   24 00003940 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GetOperationState = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GetOperationState
         38   25 00003A60 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GetSessionInfo = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GetSessionInfo
         39   26 00003AF0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GetSlotInfo = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GetSlotInfo
         40   27 00003B90 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GetSlotList = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GetSlotList
         41   28 00003CB0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GetTokenInfo = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1GetTokenInfo
         42   29 00003D50 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1InitPIN = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1InitPIN
         43   2A 00003E10 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1InitToken = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1InitToken
         44   2B 00003F20 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1Initialize = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1Initialize
         45   2C 00003FF0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1Login = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1Login
         46   2D 000040C0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1Logout = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1Logout
         47   2E 00004120 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1OpenSession = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1OpenSession
         48   2F 00004240 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1SeedRandom = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1SeedRandom
         49   30 00004300 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1SetAttributeValue = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1SetAttributeValue
         50   31 00004430 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1SetOperationState = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1SetOperationState
         51   32 000044F0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1SetPIN = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1SetPIN
         52   33 00004620 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1Sign = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1Sign
         53   34 00004780 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1SignEncryptUpdate = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1SignEncryptUpdate
         54   35 000048D0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1SignFinal = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1SignFinal
         55   36 000049E0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1SignInit = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1SignInit
         56   37 00004AA0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1SignRecover = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1SignRecover
         57   38 00004BF0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1SignRecoverInit = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1SignRecoverInit
         58   39 00004CB0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1SignUpdate = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1SignUpdate
         59   3A 00004D70 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1UnwrapKey = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1UnwrapKey
         60   3B 00004F90 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1Verify = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1Verify
         61   3C 00005080 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1VerifyFinal = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1VerifyFinal
         62   3D 00005140 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1VerifyInit = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1VerifyInit
         63   3E 00005200 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1VerifyRecover = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1VerifyRecover
         64   3F 00005350 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1VerifyRecoverInit = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1VerifyRecoverInit
         65   40 00005410 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1VerifyUpdate = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1VerifyUpdate
         66   41 000054D0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1WaitForSlotEvent = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1WaitForSlotEvent
         67   42 00005550 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1WrapKey = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_C_1WrapKey
         68   43 000056D0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_connect = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_connect
         69   44 000058B0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_disconnect = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_disconnect
         70   45 000058E0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_finalizeLibrary = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_finalizeLibrary
         71   46 000059A0 Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_initializeLibrary = Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_initializeLibrary

  Summary

        3000 .data
        6000 .pdata
       17000 .rdata
        1000 .reloc
        1000 .rsrc
       5A000 .text
        1000 _RDATA
```

Another interesting thread I need to check out: https://github.com/oracle/graal/issues/3359

**Comment by mcraj017** [comment]
@swaechter Please try the latest build
https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/22.0.0-dev-20220103_1601

**Comment by laurentforet** [comment]
Today I have tried the @aproust33 and @swaechter with the  "22.0.0.2 Java 11 CE" version without success : 

```

C:\Users\lfo\scm\github\swaechter\pkcs-native>native-image.cmd --allow-incomplete-classpath --no-fallback -H:CLibraryPath=C:/Windows/System32/drivers/ --static -jar build\libs\native.jar
========================================================================================================================
GraalVM Native Image: Generating 'native'...
========================================================================================================================
[1/7] Initializing...                                                                                    (5,8s @ 0,19GB)
 Version info: 'GraalVM 22.0.0.2 Java 11 CE'
 1 user-provided feature(s)
  - fr.devboxsante.cps.nativ.LibraryFeature
[2/7] Performing analysis...  [*******]                                                                  (3,9s @ 1,16GB)
   2 543 (84,15%) of  3 022 classes reachable
   3 199 (60,43%) of  5 294 fields reachable
  11 663 (72,84%) of 16 012 methods reachable
      26 classes,     0 fields, and   134 methods registered for reflection
      61 classes,    53 fields, and    51 methods registered for JNI access
[3/7] Building universe...                                                                               (0,5s @ 0,45GB)
[4/7] Parsing methods...      [*]                                                                        (0,4s @ 0,66GB)
[5/7] Inlining methods...     [****]                                                                     (0,4s @ 0,49GB)
[6/7] Compiling methods...    [**]                                                                       (2,7s @ 0,46GB)
[7/7] Creating image...                                                                                  (0,8s @ 0,72GB)
   3,96MB (37,33%) for code area:    7 006 compilation units
   5,87MB (55,25%) for image heap:   1 541 classes and 80 304 objects
 807,64KB ( 7,43%) for other data
  10,62MB in total
------------------------------------------------------------------------------------------------------------------------
Top 10 packages in code area:                               Top 10 object types in image heap:
 611,56KB java.util                                            1,66MB byte[] for general heap data
 345,11KB com.oracle.svm.jni                                 713,44KB java.lang.String
 287,72KB java.lang                                          546,55KB java.lang.Class
 225,05KB java.util.regex                                    449,92KB byte[] for java.lang.String
 221,64KB java.text                                          364,45KB java.util.HashMap$Node
 151,08KB java.util.concurrent                               192,92KB java.util.HashMap$Node[]
 115,15KB java.math                                          146,13KB char[]
 111,34KB com.oracle.svm.core.code                           139,63KB java.lang.String[]
 103,26KB com.oracle.svm.core.reflect                        130,55KB java.util.concurrent.ConcurrentHashMap$Node
  99,55KB sun.text.normalizer                                103,92KB sun.util.locale.LocaleObjectCache$CacheEntry
      ... 106 additional packages                                 ... 719 additional object types
                                           (use GraalVM Dashboard to see all)
------------------------------------------------------------------------------------------------------------------------
                        0,8s (4,9% of total time) in 17 GCs | Peak RSS: 2,45GB | CPU load: 7,89
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 C:\Users\lfo\scm\github\swaechter\pkcs-native\native.exe (executable)
 C:\Users\lfo\scm\github\swaechter\pkcs-native\native.build_artifacts.txt
========================================================================================================================
Finished generating 'native' in 15,2s.
```

The result was the same 
```
C:\Users\lfo\scm\github\swaechter\pkcs-native>.\native.exe
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Method.java:566)
        at fr.devboxsante.cps.nativ.NativeCpsApplication.main(NativeCpsApplication.java:18)
Caused by: java.lang.UnsatisfiedLinkError: iaik.pkcs.pkcs11.wrapper.PKCS11Implementation.initializeLibrary()V [symbol: Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_initializeLibrary or Java_iaik_pkcs_pkcs11_wrapper_PKCS11Implementation_initializeLibrary__]
        at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:153)
        at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
        at iaik.pkcs.pkcs11.wrapper.PKCS11Implementation.initializeLibrary(PKCS11Implementation.java)
        ... 2 more
```

**Comment by laurentforet** [comment]
I have tried to simplify the way to reproduce it with no maven/gradle just Graalvm javac and native-image tool. 
The problem can be resumed with that simple code `Pkcs11WrapperLoader.java` for windows :  

```
import java.io.File;

public class Pkcs11WrapperLoader {

 public static void main(String[] args) {
       System.load(new File("pkcs11wrapper.dll").getAbsolutePath());
    }
}
```

Then compile it , make it native and execute it : 
```
javac Pkcs11WrapperLoader.java
native-image -cp . Pkcs11WrapperLoader
pkcswrapperloader.exe
```
You will just need to put https://github.com/laurentforet/pkcs11wrapper-graalvm-issue/blob/main/pkcs11wrapper.dll in the current directory for a x64 windows test.

The mini project is here : https://github.com/laurentforet/pkcs11wrapper-graalvm-issue

**Comment by fy0** [comment]
> I have tried to simplify the way to reproduce it with no maven/gradle just Graalvm javac and native-image tool. The problem can be resumed with that simple code `Pkcs11WrapperLoader.java` for windows :
> 
> ```
> import java.io.File;
> 
> public class Pkcs11WrapperLoader {
> 
>  public static void main(String[] args) {
>        System.load(new File("pkcs11wrapper.dll").getAbsolutePath());
>     }
> }
> ```
> 
> Then compile it , make it native and execute it :
> 
> ```
> javac Pkcs11WrapperLoader.java
> native-image -cp . Pkcs11WrapperLoader
> pkcswrapperloader.exe
> ```
> 
> You will just need to put https://github.com/laurentforet/pkcs11wrapper-graalvm-issue/blob/main/pkcs11wrapper.dll in the current directory for a x64 windows test.
> 
> The mini project is here : https://github.com/laurentforet/pkcs11wrapper-graalvm-issue

same situation

**Comment by swaechter** [comment]
@munishchouhan @laurentforet @fy0 I retried with the latest version `21+35-jvmci-23.1-b15` and made some progress. The following code:

```java
package fr.devboxsante.cps.nativ;

import iaik.pkcs.pkcs11.DefaultInitializeArgs;
import iaik.pkcs.pkcs11.Module;

import java.io.File;

public class Launcher {

    public static void main(String[] args) throws Throwable {
        // Load the PKCS11 middleware
        System.out.println("Going to load the PKCS11 library");
        System.load(new File("pkcs11wrapper.dll").getAbsolutePath());
        System.out.println("Done");

        // Initialize the middleware
        System.out.println("Going to initialize the PKCS11 middleware instance");
        Module module = Module.getInstance("cryptoki");
        module.initialize(new DefaultInitializeArgs());
        System.out.println("Done");

        // Finalize the middleware
        System.out.println("Going to finalize the PKCS11 middlware");
        module.finalize();
        System.out.println("Done");
    }
}
```

works in Java, but outputs the following as native exe (Running it on a regular JVM works):

```powershell
c:\Users\swaechter\Downloads\pkcs-native>native.exe
Going to load the PKCS11 library
Done
Going to initialize the PKCS11 middleware instance
Assertion failed: jObjectClass != 0, file ../../common/src/modules.c, line 347
```

Bellow the mentioned code:

```c
/*
 * Create a new object for locking.
 */
jobject createLockObject(JNIEnv* env) {
  TRACE(tag_call, __FUNCTION__, "entering ");

  jclass jObjectClass;
  jobject jLockObject;
  jmethodID jConstructor;
  jObjectClass = (*env)->FindClass(env, "java/lang/Object");
  assert(jObjectClass != 0); // <-------------------------------------------- This is line 347
  jConstructor = (*env)->GetMethodID(env, jObjectClass, "<init>", "()V");
  assert(jConstructor != 0);
  jLockObject = (*env)->NewObject(env, jObjectClass, jConstructor);
  assert(jLockObject != 0);
  jLockObject = (*env)->NewGlobalRef(env, jLockObject);
  TRACE(tag_call, __FUNCTION__, "exiting ");

  return jLockObject;
}
```

The line to build the binary: `"c:\Program Files\Oracle\GraalVM-21+35.1\bin\native-image.cmd" -H:+UnlockExperimentalVMOptions -H:+CreateJvmShim --no-fallback -jar build\libs\native.jar`.

@munishchouhan Any idea? Is FindClass not allowed anymore, because the lookup is executed?

**Comment by swaechter** [comment]
After digging deeper into the GraalVM JNI documentation and refreshing the JNI metadata, I was able to get a working example:

```powershell
c:\Users\swaechter\Downloads\pkcs-native>.\build\native\nativeCompile\native.exe
Going to load the PKCS11 library
Done

Going to initialize the PKCS11 middleware instance
Done

Going to list all available slots and their information
Found 1 slots

=== Slot 0 ===
Slot information: Slot Description: SafeNet Token JC 0
Manufacturer ID: SafeNet, Inc.
Hardware Version: 2.00
Firmware Version: 0.00
Token present: true
Removable Device: true
Hardware Slot: true

Going to finalize the PKCS11 middlware
Done
```

The code is here: https://github.com/swaechter/pkcs-native

After you made a change, build the project and re-run the tracing agent to update all metadata:

```powershell
.\gradlew.bat build
c:\Program Files\Oracle\GraalVM-21+35.1\bin\java.exe"  -agentlib:native-image-agent=config-output-dir=src/main/resources/META-INF/native-image  -jar build\libs\native.jar
```

Afterwards you can rebuild the native-image build:

```powershell
.\gradlew.bat --info nativeCompile
```

The only thing I can't figure out at the moment: How can the GraalVM native-image plugin reuse the FAT JAR file? At the moment I specify the main-entry point in the plugin.
