### ISSUE TITLE
use G1 with native build,throw error

### ISSUE THREAD

**Issue by naah69** [oracle/graal#4070]
when i build the quarkus application native-image  with `--gc=G1`,it will be error.
in  #1875 ,it need `libstdc++-static`,but it had be installed in my machine.

log:
```
Fatal error:java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1
Linker command executed:
/usr/bin/gcc -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-2480045785311226311/exported_symbols.list -Wl,--exclude-libs,ALL -Wl,-x -o /home/gitlab-runner/data/builds/2o84uZS_/0/service/service_auth/target/auth-1.0.0-native-image-source-jar/auth-1.0.0-runner auth-1.0.0-runner.o /opt/java/graalvm/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/java/graalvm/lib/static/linux-amd64/glibc/libawt_headless.a /opt/java/graalvm/lib/static/linux-amd64/glibc/libawt.a /opt/java/graalvm/lib/static/linux-amd64/glibc/libnet.a /opt/java/graalvm/lib/static/linux-amd64/glibc/libextnet.a /opt/java/graalvm/lib/static/linux-amd64/glibc/libnio.a /opt/java/graalvm/lib/static/linux-amd64/glibc/libjava.a /opt/java/graalvm/lib/static/linux-amd64/glibc/libfdlibm.a /opt/java/graalvm/lib/static/linux-amd64/glibc/libsunec.a /opt/java/graalvm/lib/static/linux-amd64/glibc/libzip.a /opt/java/graalvm/lib/svm/clibraries/linux-amd64/libjvm.a -v -L/tmp/SVM-2480045785311226311 -L/opt/java/graalvm/lib/static/linux-amd64/glibc -L/opt/java/graalvm/lib/svm/clibraries/linux-amd64 -lg1gc-cr -ldl -lm -lpthread -lstdc++ -lstdc++ -lm -lstdc++ -lpthread -ldl -lz -lrt
Linker command output:
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) 
COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/:/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/:/usr/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/
LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-z' 'noexecstack' '-o' '/home/gitlab-runner/data/builds/2o84uZS_/0/service/service_auth/target/auth-1.0.0-native-image-source-jar/auth-1.0.0-runner' '-v' '-L/tmp/SVM-2480045785311226311' '-L/opt/java/graalvm/lib/static/linux-amd64/glibc' '-L/opt/java/graalvm/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/libexec/gcc/x86_64-redhat-linux/4.8.5/collect2 --build-id --no-add-needed --eh-frame-hdr --hash-style=gnu -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o /home/gitlab-runner/data/builds/2o84uZS_/0/service/service_auth/target/auth-1.0.0-native-image-source-jar/auth-1.0.0-runner -z noexecstack /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtbegin.o -L/tmp/SVM-2480045785311226311 -L/opt/java/graalvm/lib/static/linux-amd64/glibc -L/opt/java/graalvm/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../.. --gc-sections --dynamic-list /tmp/SVM-2480045785311226311/exported_symbols.list --exclude-libs ALL -x auth-1.0.0-runner.o /opt/java/graalvm/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/java/graalvm/lib/static/linux-amd64/glibc/libawt_headless.a /opt/java/graalvm/lib/static/linux-amd64/glibc/libawt.a /opt/java/graalvm/lib/static/linux-amd64/glibc/libnet.a /opt/java/graalvm/lib/static/linux-amd64/glibc/libextnet.a /opt/java/graalvm/lib/static/linux-amd64/glibc/libnio.a /opt/java/graalvm/lib/static/linux-amd64/glibc/libjava.a /opt/java/graalvm/lib/static/linux-amd64/glibc/libfdlibm.a /opt/java/graalvm/lib/static/linux-amd64/glibc/libsunec.a /opt/java/graalvm/lib/static/linux-amd64/glibc/libzip.a /opt/java/graalvm/lib/svm/clibraries/linux-amd64/libjvm.a -lg1gc-cr -ldl -lm -lpthread -lstdc++ -lstdc++ -lm -lstdc++ -lpthread -ldl -lz -lrt -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtend.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crtn.o
/opt/java/graalvm/lib/svm/clibraries/linux-amd64/libg1gc-cr.a(g1ParScanThreadState.o): In function `G1ParScanThreadState::G1ParScanThreadState(G1CollectedHeap*, G1RedirtyCardsQueueSet*, unsigned int, unsigned int, unsigned long, unsigned long)':
g1ParScanThreadState.cpp:(.text+0x723): undefined reference to `__cxa_throw_bad_array_new_length'
collect2: error: ld returned 1 exit status
	at com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:502)
	at com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:449)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:657)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
```

**Comment by zakkak** [comment]
@naah69 which GraalVM version are you using?

The G1 GC is only available in GraalVM Enterprise Edition

See: https://www.graalvm.org/reference-manual/native-image/MemoryManagement/

**Comment by naah69** [comment]
yes ,i am graalvm ee

java -version
```
java version "11.0.13" 2021-10-19 LTS
Java(TM) SE Runtime Environment GraalVM EE 21.3.0 (build 11.0.13+10-LTS-jvmci-21.3-b05)
Java HotSpot(TM) 64-Bit Server VM GraalVM EE 21.3.0 (build 11.0.13+10-LTS-jvmci-21.3-b05, mixed mode, sharing)
```

**Comment by mcraj017** [comment]
@naah69 thanks for reporting the issue, please update the gcc in your machine and try again

**Comment by naah69** [comment]
> @naah69 thanks for reporting the issue, please update the gcc in your machine and try again

ok,which version will work?

**Comment by mcraj017** [comment]
@naah69 gcc version 7.5.0 or later

**Comment by mcraj017** [comment]
closing this issue as there is no activity in last one month
