### ISSUE TITLE
Espresso Verifier allows not calling the super initializer

### ISSUE THREAD

**Issue by Thihup** [oracle/graal#4088]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: 21.3.0 and latest snapshot
 - CE or EE: CE
 - JDK version: JDK17
 - OS and OS Version: Ubuntu 20.04
 - Architecture: am,d
 - The output of `java -Xinternalversion`:
```
OpenJDK 64-Bit Server VM (17.0.2+5-jvmci-22.0-b02) for linux-amd64 JRE (17.0.2+5-jvmci-22.0-b02), built on Nov 22 2021 21:29:52 by "buildslave" with gcc 10.3.0
```

**Describe the issue**
It should report and error while verifying the "BClass", as it doesn't call the super constructor. Running without `-truffle` flag, it fails, but running with `-truffle` it doesnt.

**Code snippet or code repository that reproduces the issue**

```jasm
super public class dev/thihup/AClass
        version 61:0 {
  public Method "<init>":"()V"
        stack 1 locals 1  {
                aload_0;
                invokespecial   Method java/lang/Object."<init>":"()V";
                return;
  }
}
```

```jasm
super public class dev/thihup/BClass
        extends dev/thihup/AClass
        version 61:0 {
  public Method "<init>":"()V"
        stack 1 locals 1 {
                aload_0;
                invokespecial   Method java/lang/Object."<init>":"()V"; // <-- It should report an error here
                return;
  }
} 
```

The error reported without the `-truffle` flag is the following:
```
Exception in thread "main" java.lang.VerifyError: Bad <init> method call
Exception Details:
  Location:
    dev/thihup/BClass.<init>()V @1: invokespecial
  Reason:
    Type 'java/lang/Object' is not assignable to 'dev/thihup/BClass'
  Bytecode:
    0000000: 2ab7 0002 b1                           

        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:375)
        at dev.thihup.Main.main(Main.java:31)
```

**Comment by rodrigar-mx** [comment]
Hi @Thihup. Thanks for reporting the issue. Could you please provide a bit more detail on how to reproduce the error.

**Comment by Thihup** [comment]
@rodrigar-mx Sure.
The following format is the JASM from Codetools: https://wiki.openjdk.java.net/display/CodeTools/Appendix+A
You can download it here: https://repo1.maven.org/maven2/org/openjdk/asmtools/asmtools-core/7.0.b10-ea/asmtools-core-7.0.b10-ea.jar

To compile:
```
java -jar asmtools-core-7.0.b10-ea.jar jasm -d out AClass.jasm BClass.jasm
```
To execute:
```
java -truffle -cp out dev.thihup.BClass
```
