### ISSUE TITLE
[LLVM] NullPointerException on simple LLVM bitcode

### ISSUE THREAD

**Issue by zhendongsu** [oracle/graal#4105]
GraalVM version or commit id if built from source: GraalVM CE 22.1.0-dev-20211208_2010 (the latest snapshot build from https://github.com/graalvm/graalvm-ce-dev-builds/releases)
CE or EE: CE
JDK version: openjdk 11.0.13
OS and OS Version: Ubuntu 18.04
Architecture: amd64
The output of `java -Xinternalversion`:
OpenJDK 64-Bit Server VM (11.0.13+8-jvmci-22.0-b02) for linux-amd64 JRE (11.0.13+8-jvmci-22.0-b02), built on Nov 22 2021 22:03:35 by "buildslave" with gcc 7.3.0

```
[532] % lli22dev --version
LLVM 12.0.1 (GraalVM CE Native 22.1.0-dev)
[533] % 
[533] % llvm-as small.ll -o small.bc
[534] % 
[534] % lli22dev small.bc
ERROR: java.lang.NullPointerException
org.graalvm.polyglot.PolyglotException: java.lang.NullPointerException
	at com.oracle.truffle.llvm.ParserDriver.parseBinary(ParserDriver.java:324)
	at com.oracle.truffle.llvm.ParserDriver.parseLibraryWithSource(ParserDriver.java:413)
	at com.oracle.truffle.llvm.ParserDriver.parseWithDependencies(ParserDriver.java:142)
	at com.oracle.truffle.llvm.ParserDriver.parseWithDependencies(ParserDriver.java:128)
	at com.oracle.truffle.llvm.ParserDriver.parse(ParserDriver.java:101)
	at com.oracle.truffle.llvm.DefaultLoader.load(DefaultLoader.java:44)
	at com.oracle.truffle.llvm.runtime.LLVMLanguage.parse(LLVMLanguage.java:540)
	at com.oracle.truffle.api.TruffleLanguage$ParsingRequest.parse(TruffleLanguage.java:933)
	at com.oracle.truffle.api.TruffleLanguage.parse(TruffleLanguage.java:1290)
	at com.oracle.truffle.api.LanguageAccessor$LanguageImpl.parse(LanguageAccessor.java:300)
	at com.oracle.truffle.polyglot.PolyglotSourceCache.parseImpl(PolyglotSourceCache.java:94)
	at com.oracle.truffle.polyglot.PolyglotSourceCache.access$300(PolyglotSourceCache.java:56)
	at com.oracle.truffle.polyglot.PolyglotSourceCache$WeakCache.lookup(PolyglotSourceCache.java:222)
	at com.oracle.truffle.polyglot.PolyglotSourceCache.parseCached(PolyglotSourceCache.java:80)
	at com.oracle.truffle.polyglot.PolyglotLanguageContext.parseCached(PolyglotLanguageContext.java:369)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:1295)
	at com.oracle.truffle.polyglot.PolyglotContextDispatch.eval(PolyglotContextDispatch.java:63)
	at org.graalvm.polyglot.Context.eval(Context.java:399)
	at com.oracle.truffle.llvm.launcher.LLVMLauncher.execute(LLVMLauncher.java:250)
	at com.oracle.truffle.llvm.launcher.LLVMLauncher.launch(LLVMLauncher.java:75)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:295)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:121)
	at com.oracle.truffle.llvm.launcher.LLVMLauncher.main(LLVMLauncher.java:53)
Caused by: Attached Guest Language Frames (0)
Internal GraalVM error, please report at https://github.com/oracle/graal/issues/.
[535] % 
[535] % cat small.ll
define dso_local i32 @main() #0 {
  ret i32 0
}
```

The NPE also reproduces with GraalVM 19.3.6 CE.

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, we will take a look into it and get back to you
