### ISSUE TITLE
An obscure build error message

### ISSUE THREAD

**Issue by schadin** [oracle/graal#4108]
**Describe the issue**
Hello! 
I'm trying to compile a service written in java + spring boot 2.5.6 into a native application using spring native with buildpacks.
I get an error when I run the native-image. How can I figure out what's causing it?

**Steps to reproduce the issue**
No possibility, using internal dependencies. Using mvn spring-boot:build-image.

**Describe GraalVM and your environment:**
 - GraalVM version: **GraalVM CE 21.2.0 (build 25.302-b07-jvmci-21.2-b08)**
 - JDK major version: **8**
 - OS: **Linux Mint 20.2**
 - Architecture: **x86_64**

**More details**
[build.log](https://gist.github.com/schadin/21a4168e94f60f137ad23d232eca1408).

Thank you!

**Comment by mcraj017** [comment]
@schadin thanks for reporting the issue.
Please add this flag and try again --allow-incomplete-classpath

**Comment by schadin** [comment]
@mcraj017 thanks for answer. 

Compiling continues, but failed with message:  [log](https://gist.github.com/schadin/21a4168e94f60f137ad23d232eca1408#file-runtime-init-needed-log)
I added class to runtime initialization: --initialize-at-run-time= sun.instrument.InstrumentationImpl .
In compilation happend error: class already exists runtime initialization: [log](https://gist.github.com/schadin/21a4168e94f60f137ad23d232eca1408#file-already-been-initialized-log)

**Comment by mcraj017** [comment]
@schadin thanks for the response 
I will raise this to native-image team for further checking

**Comment by christianwimmer** [comment]
Without knowing your application, i.e., what code you intentionally run at image build time and which `initialize-at-build-time` options you have specified in `native-image.properties` files, it is impossible to diagnose the problem.

What probably happens: You have some code marked as `initialize-at-build-time`, but not all code that these classes transitively depend on. Have you tried the `--trace-class-initialization=sun.instrument.InstrumentationImpl` option that the error message is suggesting? It should give you a stack trace how initialization happens. 

A manual way to debug such problems is to run the image generator with `--debug-attach`, then connect a Java debugger to the image generator, set a breakpoint in the class initializer of the classes that are wrongly initialized. Then you also get the stack trace of how these classes are initialized, and since the debugger is stopped in the class initializer you can also gather more information compared to what `--trace-class-initialization` gives you.

**Comment by schadin** [comment]
Guys thank you for answers!
I'm compiled and run application after removing log4j-core.

I encountered a strange error. For testing, I added a file application-graalvm.yml with specified values. Service runs only with this profile! If you run the service without specifying a profile or with specifying another profile, an error appears:

`ERROR SpringApplication Application run failed
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: 'entityManagerFactory' depends on missing bean 'cacheManager'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'cacheManager' available
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:325)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
        at ru.diasoft.micro.Application.main(Application.java:21)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'cacheManager' available
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:863)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1344)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:309)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
        ... 11 more
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: 'entityManagerFactory' depends on missing bean 'cacheManager'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'cacheManager' available
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:325)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
        at ru.diasoft.micro.Application.main(Application.java:21)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'cacheManager' available
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:863)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1344)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:309)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
        ... 11 more`

I'm wrote two files applicaiton-full.yml and application-graalvm.yml with same content. Profile "graalvm" worked, but profile "full" doesn't.
May be you known why is it?

**Comment by wirthi** [comment]
Closing this older ticket, Spring Native is outdated (integrated now); if something like this appears on Spring Boot 3 or later, please report in a new ticket.
