### ISSUE TITLE
Error:no awt in java.library.path in compose multiplatform program

### ISSUE THREAD

**Issue by Anivie** [oracle/graal#4113]
Graalvm with native-image can't run a compose multiplatform desktop program with jdk17,it had no problems compiling, but have an error when running:`no awt in java.library.path` ,and when windows show me a messagebox thar about "0xc0000020"error

**Steps to reproduce the issue**
 - Complete compose multiplatform desktop program with gradle option "packageUberJarForCurrentOS"
 - use `native-image -jar dsk.jar` to complete it.
 - run

**Describe GraalVM and your environment:**
 - JDK major version:JDK17.0.1
 - OS: Windows 10
 - Architecture: AMD64

It can complete with Jdk11,but it will have `Cannot open (null)\bin\jawt.dll`error,and it can use `app.exe -Djava.home=$GRAALVM_HOME` to fix it

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no awt in java.library.path
        at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryRelative(NativeLibrarySupport.java:132)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:47)
        at java.lang.Runtime.loadLibrary0(Runtime.java:808)
        at java.lang.System.loadLibrary(System.java:1893)
        at java.awt.Toolkit$2.run(Toolkit.java:1385)
        at java.awt.Toolkit$2.run(Toolkit.java:1383)
        at java.security.AccessController.doPrivileged(AccessController.java:87)
        at java.awt.Toolkit.loadLibraries(Toolkit.java:1382)
        at java.awt.Toolkit.<clinit>(Toolkit.java:1415)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
        at java.awt.EventQueue.invokeLater(EventQueue.java:1313)
        at javax.swing.SwingUtilities.invokeLater(SwingUtilities.java:1420)
        at kotlinx.coroutines.swing.SwingDispatcher.dispatch(SwingDispatcher.kt:28)
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:322)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:170)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at androidx.compose.ui.window.Application_desktopKt.awaitApplication(Application.desktop.kt:199)
        at androidx.compose.ui.window.Application_desktopKt$application$1.invokeSuspend(Application.desktop.kt:115)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at androidx.compose.ui.window.Application_desktopKt.application(Application.desktop.kt:114)
        at androidx.compose.ui.window.Application_desktopKt.application$default(Application.desktop.kt:105)
        at MainKt.main(Main.kt:28)
        at MainKt.main(Main.kt)
```

**Comment by fniephaus** [comment]
As far as I know, AWT and Swing aren't fully supported yet by Native Image on Windows (see https://github.com/oracle/graal/issues/3084).

**Comment by kkriske** [comment]
@fniephaus but native-image does produce shim dlls for awt, and `no awt in java.library.path` implies that it is not there. So while there is indeed no full support, the `UnsatisfiedLinkError` shouldn't occur.

**Comment by chirontt** [comment]
The statement about the `JDK17` version of GraalVM "had no problems compiling" is just plain wrong:
```
Graalvm with native-image can't run a compose multiplatform desktop program with jdk17,it had no problems compiling...
```
To my knowledge, the `JDK17` version simple can't successfully compile *any* Swing program (compose or no compose) to native image; it suffers the "should not reach here" error during the link stage, as described in the issue #4072. Yes, it does produce an .exe file, but that .exe file is broken. When you try to run that broken .exe file, you'd get the `no awt in java.library.path` error as described by the original poster, with tons of Windows errors popped up as well. This happens to plain Swing program as well as compose one.

On the other hand, the `JDK11` version works fine, as mentioned by the original poster.

**Comment by Anivie** [comment]
> The statement about the `JDK17` version of GraalVM "had no problems compiling" is just plain wrong:
> 
> ```
> Graalvm with native-image can't run a compose multiplatform desktop program with jdk17,it had no problems compiling...
> ```
> 
> To my knowledge, the `JDK17` version simple can't successfully compile _any_ Swing program (compose or no compose) to native image; it suffers the "should not reach here" error during the link stage, as described in the issue #4072. Yes, it does produce an .exe file, but that .exe file is broken. When you try to run that broken .exe file, you'd get the `no awt in java.library.path` error as described by the original poster, with tons of Windows errors popped up as well. This happens to plain Swing program as well as compose one.
> 
> On the other hand, the `JDK11` version works fine, as mentioned by the original poster.

I can complete JavaFx program with native-image on jdk17 and run,so i thik it can complete this program too,but I seem to have a wrong view?Dose it have any solution?

**Comment by chirontt** [comment]
@Anivie Swing and JavaFX are two different animals. Both JDK versions of GraalVM can successfully compile JavaFX programs to native image, and that precisely shows that JavaFX has nothing to do with Swing :)

**Comment by fgroupindonesia** [comment]
so for swing app using GraalVM CE 20.3.5 is that possible to do the native-image command?
