### ISSUE TITLE
[LLVM] ArrayIndexOutOfBoundsException from running lli with --engine.CompileAOTOnCreate on trivial code

### ISSUE THREAD

**Issue by zhendongsu** [oracle/graal#4117]
GraalVM version or commit id if built from source: GraalVM CE 22.1.0-dev-20211209_2306 (the latest snapshot build from https://github.com/graalvm/graalvm-ce-dev-builds/releases)
CE or EE: CE
JDK version: openjdk 11.0.13
OS and OS Version: Ubuntu 18.04
Architecture: amd64
The output of `java -Xinternalversion`:
OpenJDK 64-Bit Server VM (11.0.13+8-jvmci-22.0-b02) for linux-amd64 JRE (11.0.13+8-jvmci-22.0-b02), built on Nov 22 2021 22:03:35 by "buildslave" with gcc 7.3.0

```
[521] % clangg22dev -v
GraalVM wrapper script for clang
GraalVM version: Development Build
running: /local/suz-local/software/graalvm-ce-java11-22.1.0-dev/lib/llvm/bin/clang -v
clang version 12.0.1 (GraalVM.org llvmorg-12.0.1-3-g6e0a5672bc-bgf11ed69a5a 6e0a5672bc058d882dce3d56f90b72b64a6870d7)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/suz-local/software/graalvm-ce-java11-22.1.0-dev/lib/llvm/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
Found CUDA installation: /usr/local/cuda, version 11.0
[522] % 
[522] % lli22dev --version
LLVM 12.0.1 (GraalVM CE Native 22.1.0-dev)
[523] % 
[523] % clangg22dev -c -emit-llvm -o small.bc small.c
[524] % 
[524] % lli22dev --experimental-options --engine.CompileAOTOnCreate small.bc
ERROR: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 1
org.graalvm.polyglot.PolyglotException: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 1
	at com.oracle.truffle.api.impl.FrameWithoutBoxing.verifyIndexedSet(FrameWithoutBoxing.java:753)
	at com.oracle.truffle.api.impl.FrameWithoutBoxing.setLong(FrameWithoutBoxing.java:697)
	at com.oracle.truffle.llvm.runtime.memory.LLVMStack$LLVMNativeStackAccess.executeEnter(LLVMStack.java:258)
	at com.oracle.truffle.llvm.initialization.LoadModulesNode.loadModule(LoadModulesNode.java:208)
	at com.oracle.truffle.llvm.initialization.LoadModulesNode.execute(LoadModulesNode.java:189)
	at org.graalvm.polyglot.Context.eval(Context.java:399)
	at com.oracle.truffle.llvm.launcher.LLVMLauncher.execute(LLVMLauncher.java:250)
	at com.oracle.truffle.llvm.launcher.LLVMLauncher.launch(LLVMLauncher.java:75)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:295)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:121)
	at com.oracle.truffle.llvm.launcher.LLVMLauncher.main(LLVMLauncher.java:53)
Original Internal Error: 
java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 1
	at com.oracle.truffle.api.impl.FrameWithoutBoxing.verifyIndexedSet(FrameWithoutBoxing.java:753)
	at com.oracle.truffle.api.impl.FrameWithoutBoxing.setLong(FrameWithoutBoxing.java:697)
	at com.oracle.truffle.llvm.runtime.memory.LLVMStack$LLVMNativeStackAccess.executeEnter(LLVMStack.java:258)
	at com.oracle.truffle.llvm.initialization.LoadModulesNode.loadModule(LoadModulesNode.java:208)
	at com.oracle.truffle.llvm.initialization.LoadModulesNode.execute(LoadModulesNode.java:189)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:655)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:627)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:560)
	at com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.invokeCallBoundary(SubstrateOptimizedCallTarget.java:121)
	at com.oracle.svm.truffle.api.SubstrateOptimizedCallTargetInstalledCode.doInvoke(SubstrateOptimizedCallTargetInstalledCode.java:176)
	at com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:104)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:468)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:449)
	at com.oracle.truffle.llvm.runtime.LLVMContext.initialize(LLVMContext.java:307)
	at com.oracle.truffle.llvm.runtime.LLVMLanguage.initializeContext(LLVMLanguage.java:201)
	at com.oracle.truffle.llvm.runtime.LLVMLanguage.initializeContext(LLVMLanguage.java:84)
	at com.oracle.truffle.api.TruffleLanguage$Env.postInit(TruffleLanguage.java:3317)
	at com.oracle.truffle.api.LanguageAccessor$LanguageImpl.postInitEnv(LanguageAccessor.java:289)
	at com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureInitialized(PolyglotLanguageContext.java:689)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:1294)
	at com.oracle.truffle.polyglot.PolyglotContextDispatch.eval(PolyglotContextDispatch.java:63)
	at org.graalvm.polyglot.Context.eval(Context.java:399)
	at com.oracle.truffle.llvm.launcher.LLVMLauncher.execute(LLVMLauncher.java:250)
	at com.oracle.truffle.llvm.launcher.LLVMLauncher.launch(LLVMLauncher.java:75)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:295)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:121)
	at com.oracle.truffle.llvm.launcher.LLVMLauncher.main(LLVMLauncher.java:53)
Caused by: Attached Guest Language Frames (1)
[525] % 
[525] % cat small.c
int main() { return 0; }
```

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, we will take a look into it and get back to you

**Comment by rschatz** [comment]
Should be fixed by https://github.com/oracle/graal/commit/ab89a130039dd2697505aacb59dc59b524976d0d
