### ISSUE TITLE
Number of elements in a node list too high: 65537

### ISSUE THREAD

**Issue by naah69** [oracle/graal#4122]
there is the below log when i build native images.
i don't know where is the error and how to fix it.

```log
Fatal error:org.graalvm.compiler.debug.GraalError: org.graalvm.compiler.core.common.PermanentBailoutException: Number of elements in a node list too high: 65537
        at com.oracle.graal.pointsto.util.AnalysisFuture.setException(AnalysisFuture.java:49)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:269)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool.awaitQuiescence(ForkJoinPool.java:2984)
        at com.oracle.graal.pointsto.util.CompletionExecutor.complete(CompletionExecutor.java:238)
        at com.oracle.graal.pointsto.PointsToAnalysis.checkObjectGraph(PointsToAnalysis.java:680)
        at com.oracle.graal.pointsto.PointsToAnalysis.finish(PointsToAnalysis.java:644)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:704)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:529)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
Caused by: org.graalvm.compiler.core.common.PermanentBailoutException: Number of elements in a node list too high: 65537
        at jdk.internal.vm.compiler/org.graalvm.compiler.graph.NodeList.checkMaxSize(NodeList.java:109)
        at jdk.internal.vm.compiler/org.graalvm.compiler.graph.NodeList.add(NodeList.java:184)
        at jdk.internal.vm.compiler/org.graalvm.compiler.graph.NodeList.add(NodeList.java:38)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.AbstractMergeNode.addForwardEnd(AbstractMergeNode.java:71)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.AbstractMergeNode.simplify(AbstractMergeNode.java:203)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.tryCanonicalize(CanonicalizerPhase.java:438)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.processNode(CanonicalizerPhase.java:349)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.processWorkSet(CanonicalizerPhase.java:326)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.run(CanonicalizerPhase.java:285)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase.run(CanonicalizerPhase.java:195)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase.run(CanonicalizerPhase.java:76)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
        at com.oracle.svm.hosted.substitute.UnsafeAutomaticSubstitutionProcessor.getStaticInitializerGraph(UnsafeAutomaticSubstitutionProcessor.java:1098)
        at com.oracle.svm.hosted.substitute.UnsafeAutomaticSubstitutionProcessor.computeSubstitutions(UnsafeAutomaticSubstitutionProcessor.java:374)
        at com.oracle.svm.hosted.SVMHost.initializeType(SVMHost.java:303)
        at com.oracle.graal.pointsto.meta.AnalysisType.lambda$new$0(AnalysisType.java:234)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        ... 13 more
```

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reporting the issue, Could you please clarify a few things

1. What version of GraalVM you're using? (ex: GraalVM CE 21.3.0 java11). have you tried with the latest snapshot build? if not please do so.
2. What OS you're using?
3. Did you try generating the configuration files using the native-image-agent for your application? if not please do so.
4. Could you share a reproducible example to verify and diagnose this issue.

**Comment by oubidar-Abderrahim** [comment]
I'll be closing this issue for now. If you still face this issue with our latest build, please reopen the issue and provide a reproducer that we can use to debug the issue further.
Thank you

**Comment by ekoontz** [comment]
I have hit this exception also and can provide more details as requested by @oubidar-Abderrahim . 

Using a docker file with:

```
ghcr.io/graalvm/graalvm-ce:latest
```
(note: at the time I am writing this, latest is version [22.2.0](https://www.graalvm.org/release-notes/22_2/#2220))  I get the following when trying to run `native-image`:

```
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 Fatal error: org.graalvm.compiler.debug.GraalError: org.graalvm.compiler.debug.GraalError: org.graalvm.compiler.core.common.PermanentBailoutException: Number of elements in a node list too high: 65537
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.setException(AnalysisFuture.java:49)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:269)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:63)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$postTask$9(ImageHeapScanner.java:611)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at java.base/java.util.concurrent.ForkJoinPool.externalHelpQuiescePool(ForkJoinPool.java:2104)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at java.base/java.util.concurrent.ForkJoinPool.awaitQuiescence(ForkJoinPool.java:3321)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.complete(CompletionExecutor.java:243)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis.doTypeflow(PointsToAnalysis.java:692)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis.finish(PointsToAnalysis.java:680)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis.runAnalysis(PointsToAnalysis.java:736)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:731)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:564)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 Caused by: org.graalvm.compiler.debug.GraalError: org.graalvm.compiler.core.common.PermanentBailoutException: Number of elements in a node list too high: 65537
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.setException(AnalysisFuture.java:49)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:269)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:63)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.ensureInitialized(AnalysisType.java:628)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.onReachable(AnalysisType.java:552)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AtomicUtils.atomicMarkAndRun(AtomicUtils.java:52)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.lambda$registerAsReachable$8(AnalysisType.java:530)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.forAllSuperTypes(AnalysisType.java:608)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.forAllSuperTypes(AnalysisType.java:594)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.forAllSuperTypes(AnalysisType.java:590)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.registerAsReachable(AnalysisType.java:530)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.registerAsReachable(AnalysisConstantReflectionProvider.java:334)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.HostedDynamicHubFeature.replace(HostedDynamicHubFeature.java:53)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:583)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.replaceObject(AnalysisConstantReflectionProvider.java:257)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.interceptValue(AnalysisConstantReflectionProvider.java:228)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.heap.SVMImageHeapScanner.transformFieldValue(SVMImageHeapScanner.java:126)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.onFieldValueReachable(ImageHeapScanner.java:331)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$createImageHeapObject$3(ImageHeapScanner.java:272)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	... 18 more
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 Caused by: org.graalvm.compiler.core.common.PermanentBailoutException: Number of elements in a node list too high: 65537
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at jdk.internal.vm.compiler/org.graalvm.compiler.graph.NodeList.checkMaxSize(NodeList.java:123)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at jdk.internal.vm.compiler/org.graalvm.compiler.graph.NodeList.add(NodeList.java:179)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at jdk.internal.vm.compiler/org.graalvm.compiler.graph.NodeList.add(NodeList.java:39)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.AbstractMergeNode.addForwardEnd(AbstractMergeNode.java:71)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.AbstractMergeNode.simplify(AbstractMergeNode.java:203)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase.tryCanonicalize(CanonicalizerPhase.java:417)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase.processNode(CanonicalizerPhase.java:325)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase.processWorkSet(CanonicalizerPhase.java:299)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase.run(CanonicalizerPhase.java:201)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase.run(CanonicalizerPhase.java:77)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:261)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:170)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.UnsafeAutomaticSubstitutionProcessor.getStaticInitializerGraph(UnsafeAutomaticSubstitutionProcessor.java:1112)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.UnsafeAutomaticSubstitutionProcessor.computeSubstitutions(UnsafeAutomaticSubstitutionProcessor.java:364)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.SVMHost.initializeType(SVMHost.java:284)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.initializeType(AnalysisUniverse.java:670)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.lambda$new$0(AnalysisType.java:279)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-09-25T16:04:06.103000+00:00 d6dd7b2e-79b2-4a63-8ce2-54d2e3982f46 	... 36 more
```

but on an older release, [21.0.02](https://www.graalvm.org/release-notes/21_0/#21002)
my `native_image` build succeeds. It *does* show the same "Number of elements in a node list too high" exception, but it is not fatal, in contrast to the one seen above:

```
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f Exception in thread "ForkJoinPool-4-worker-1" org.graalvm.compiler.debug.GraalError: org.graalvm.compiler.core.common.PermanentBailoutException: Number of elements in a node list too high: 65537
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at com.oracle.graal.pointsto.util.AnalysisFuture.setException(AnalysisFuture.java:49)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:269)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f Caused by: org.graalvm.compiler.core.common.PermanentBailoutException: Number of elements in a node list too high: 65537
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at jdk.internal.vm.compiler/org.graalvm.compiler.graph.NodeList.checkMaxSize(NodeList.java:108)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at jdk.internal.vm.compiler/org.graalvm.compiler.graph.NodeList.add(NodeList.java:183)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at jdk.internal.vm.compiler/org.graalvm.compiler.graph.NodeList.add(NodeList.java:37)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.AbstractMergeNode.addForwardEnd(AbstractMergeNode.java:71)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.AbstractMergeNode.simplify(AbstractMergeNode.java:203)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.tryCanonicalize(CanonicalizerPhase.java:426)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.processNode(CanonicalizerPhase.java:345)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.processWorkSet(CanonicalizerPhase.java:322)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.run(CanonicalizerPhase.java:281)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase.run(CanonicalizerPhase.java:191)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.CanonicalizerPhase.run(CanonicalizerPhase.java:73)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at com.oracle.svm.hosted.substitute.UnsafeAutomaticSubstitutionProcessor.getStaticInitializerGraph(UnsafeAutomaticSubstitutionProcessor.java:1057)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at com.oracle.svm.hosted.substitute.UnsafeAutomaticSubstitutionProcessor.computeSubstitutions(UnsafeAutomaticSubstitutionProcessor.java:352)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at com.oracle.svm.hosted.SVMHost.initializeType(SVMHost.java:286)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at com.oracle.graal.pointsto.meta.AnalysisType.lambda$new$0(AnalysisType.java:227)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-09-25T17:25:47.862000+00:00 86756e70-5a52-4124-b681-e0d0aca7136f 	... 6 more
```

but again this error is *NOT* fatal - `native_image` successfully completes despite it.

**Comment by ekoontz** [comment]
In order to reproduce this problem, 
1. `git clone` the following repository:  https://github.com/ekoontz/menard.git
2. `git checkout c7ecf0154f7c26ef4afe9e7a9a2a0dc9cd0d28f2`
3. Follow these instructions: https://github.com/ekoontz/menard/blob/main/lambda/README.md#manually-building-menard_lambda
