### ISSUE TITLE
My Java application uses --patch-module to bootstrap some JDK classes. Is it possible to integrate my patch-module bootstrap shared library with my main application image, in the same way that the JVM does it?

### ISSUE THREAD

**Issue by saoj** [oracle/graal#4129]
I'm using Java11. Below how I launch my Java application:

   `java --patch-module=java.base=./lib/bootstrap-jdk11.jar -cp my-app-1.23.34.jar com.myapp.Start`

I'm able to successfully native-compile the jars: `my-app-1.23.34.jar` and `bootstrap-jdk11.jar`. **Great!**

**Note:** bootstrap-jdk11.jar is native-compiled as a shared library.

Now I want to link my shared library with my main application, **in a way that my application understands that I'm bootstrapping some of the JDK classes**. Is that something that can be done?

Any ideas on how I would accomplish that would be appreciated!

Thanks!

**Comment by saoj** [comment]
I've tried everything again, this time with Graal 17, and I get a different error:

**NOTE:** I'm able to run this successfully with the JVM, passing the same arguments:

```
$ java -version
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05, mixed mode, sharing)

$ /usr/java/default/bin/native-image --version
GraalVM 21.3.0 Java 17 CE (Java Version 17.0.1+12-jvmci-21.3-b05)

$ /usr/java/default/bin/native-image -J--add-exports=java.base/sun.nio.ch=ALL-UNNAMED -J--enable-preview \
-J--patch-module=java.base=./lib/boot-jdk11.jar -J--add-opens=java.base/java.nio=ALL-UNNAMED -jar \
lib/myapp.jar MyAppBootstrapped

Error occurred during initialization of VM
java.lang.ExceptionInInitializerError
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(java.base@17.0.1/Native Method)
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(java.base@17.0.1/NativeConstructorAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(java.base@17.0.1/DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstanceWithCaller(java.base@17.0.1/Constructor.java:499)
	at java.lang.reflect.Constructor.newInstance(java.base@17.0.1/Constructor.java:480)
	at java.lang.ClassLoader.initSystemClassLoader(java.base@17.0.1/ClassLoader.java:1983)
	at java.lang.System.initPhase3(java.base@17.0.1/System.java:2246)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected java.lang.Class java.lang.ClassLoader.loadClass)java.lang.String,boolean)java.lang.ClassNotFoundException accessible: module java.base does not "opens java.lang" to unnamed module @4e04a765
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(java.base@17.0.1/AccessibleObject.java:354)
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(java.base@17.0.1/AccessibleObject.java:297)
	at java.lang.reflect.Method.checkCanSetAccessible(java.base@17.0.1/Method.java:199)
	at java.lang.reflect.Method.setAccessible(java.base@17.0.1/Method.java:193)
	at com.oracle.svm.util.ReflectionUtil.lookupMethod(ReflectionUtil.java:64)
	at com.oracle.svm.util.ReflectionUtil.lookupMethod(ReflectionUtil.java:57)
	at com.oracle.svm.hosted.NativeImageSystemClassLoader.<clinit>(NativeImageSystemClassLoader.java:124)
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(java.base@17.0.1/Native Method)
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(java.base@17.0.1/NativeConstructorAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(java.base@17.0.1/DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstanceWithCaller(java.base@17.0.1/Constructor.java:499)
	at java.lang.reflect.Constructor.newInstance(java.base@17.0.1/Constructor.java:480)
	at java.lang.ClassLoader.initSystemClassLoader(java.base@17.0.1/ClassLoader.java:1983)
	at java.lang.System.initPhase3(java.base@17.0.1/System.java:2246)

Error: Image build request failed with exit status 1
```

**Comment by saoj** [comment]
Can the links below help?

https://bugs.openjdk.java.net/browse/JDK-8177845

https://jigsaw-dev.openjdk.java.narkive.com/OL6JEVzX/running-jaotc-with-an-external-graal

**Comment by Thihup** [comment]
Try adding `-J--add-opens=java.base/java.lang=ALL-UNNAMED`

**Comment by saoj** [comment]
@Thihup Hey Thiago,

So for Graal 11, I had:

`/usr/java/default/bin/native-image -J--patch-module=java.base=./lib/boot-jdk11.jar -jar lib/myapp.jar MyAppBootstrapped`

and I added like you said:

`/usr/java/default/bin/native-image -J--add-opens=java.base/java.lang=ALL-UNNAMED -J--patch-module=java.base=./lib/boot-jdk11.jar -jar lib/myapp.jar MyAppBootstrapped`

and I get:

```
$ ./compileNativeWithBootstrap.sh
Unexpected error (113) returned by AddToSystemClassLoaderSearch
Unable to add /usr/java/graalvm-ce-java11-21.3.0/lib/svm/builder/svm.jar to system class path - the system class loader does not define the appendToClassPathForInstrumentation method or the method failed
FATAL ERROR in native method: processing of -javaagent failed, appending to system class path failed
Error: Image build request failed with exit status 134
```

Without your change I get:

```
$ ./compileNativeWithBootstrap.sh
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.oracle.svm.util.ReflectionUtil (file:/usr/java/graalvm-ce-java11-21.3.0/lib/svm/builder/pointsto.jar) to method java.lang.ClassLoader.loadClass(java.lang.String,boolean)
WARNING: Please consider reporting this to the maintainers of com.oracle.svm.util.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Unexpected error (113) returned by AddToSystemClassLoaderSearch
Unable to add /usr/java/graalvm-ce-java11-21.3.0/lib/svm/builder/svm.jar to system class path - the system class loader does not define the appendToClassPathForInstrumentation method or the method failed
FATAL ERROR in native method: processing of -javaagent failed, appending to system class path failed
Error: Image build request failed with exit status 134
```

Adding also `-J--add-exports=java.base/java.lang=ALL-UNNAMED`

```
$ ./compileNativeWithBootstrap.sh
Unexpected error (113) returned by AddToSystemClassLoaderSearch
Unable to add /usr/java/graalvm-ce-java11-21.3.0/lib/svm/builder/svm.jar to system class path - the system class loader does not define the appendToClassPathForInstrumentation method or the method failed
FATAL ERROR in native method: processing of -javaagent failed, appending to system class path failed
Error: Image build request failed with exit status 134
```

Now trying for Graal 17:

Before I had, which was clearly wrong... I was opening java.nio and sun.nio.ch packets:

`/usr/java/default/bin/native-image -J--add-exports=java.base/sun.nio.ch=ALL-UNNAMED -J--enable-preview \
-J--patch-module=java.base=./lib/boot-jdk11.jar -J--add-opens=java.base/java.nio=ALL-UNNAMED -jar \
lib/myapp.jar MyAppBootstrapped`

I changed to:

`/usr/java/default/bin/native-image -J--add-exports=java.base/java.lang=ALL-UNNAMED -J--enable-preview \
-J--patch-module=java.base=./lib/boot-jdk11.jar -J--add-opens=java.base/java.lang=ALL-UNNAMED -jar \
lib/myapp.jar MyAppBootstrapped`

But no luck either :( :( :(

```
$ ./compileNativeWithBootstrap.sh
Unexpected error (113) returned by AddToSystemClassLoaderSearch
Unable to add /usr/java/graalvm-ce-java17-21.3.0/lib/svm/builder/svm.jar to system class path - the system class loader does not define the appendToClassPathForInstrumentation method or the method failed
FATAL ERROR in native method: processing of -javaagent failed, appending to system class path failed
Error: Image build request failed with exit status 134
```

**Comment by rodrigar-mx** [comment]
Hi @saoj. I will take a closer look into it. Any updates or questions, I will let you know.

**Comment by sgammon** [comment]
@rodrigar-mx Any update on this issue? We just an into it on the latest version of GraalVM.
