### ISSUE TITLE
Unable to run graavl native image with BouncyCastleFIPSProvider (BCFIPS)

### ISSUE THREAD

**Issue by shashanka981** [oracle/graal#4135]
We are building a graalvm based native image for our application that is using bcfips library. Native image generation goes through fine, But at runtime, appication complains that BCFIPS provider is not registered . Stack trace of the exception :

Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Trying to verify a provider that was not registered at build time: BCFIPS version 1.000201. All providers must be registered and verified in the Native Image builder. 
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:87)
	at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:367)
	at javax.crypto.JceSecurity.getInstance(JceSecurity.java:129)
	at javax.crypto.KeyGenerator.getInstance(KeyGenerator.java:287)
	at com.pega.fnx.encryptionengine.impl.bouncycastle.EncryptionKeyGeneratorImpl.<init>(EncryptionKeyGeneratorImpl.java:54)
	at com.pega.fnx.encryptionengine.impl.bouncycastle.$EncryptionKeyGeneratorImplDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1898)
	... 114 common frames omitted

**Steps to reproduce the issue**
1. Version of graalvm - 21.3.0
2.  I have created the following entry in java.security policy file located in java_home/lib/security
**security.provider.3=org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider**
3. Version of BCFIPS library:  **org.bouncycastle:bc-fips:1.0.2.1**
4. Graalvm native options:
`Args= -H:IncludeResources=logback.xml|application.yml \
  -H:Name=service \
  -H:Class=com.pega.fnx.servicecommons.Application \
  -H:+ReportExceptionStackTraces \
  -H:+ReportUnsupportedElementsAtRuntime \
  -H:+StaticExecutableWithDynamicLibC \
  --no-fallback \
  -H:ReflectionConfigurationResources=reflectconfig \
  --initialize-at-run-time=io.micronaut.tracing.brave.instrument.http.BraveTracingServerFilter,io.micronaut.tracing.brave.instrument.http.HttpClientTracingPublisher \
  -H:AdditionalSecurityProviders=org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider

`

**Describe GraalVM and your environment:**
 - GraalVM version - ghcr.io/graalvm/graalvm-ce:java11-21.3.0
 - JDK major version: java 11
 - OS:  Linux 
 - Architecture: AMD64

More details :  From the graalvm documentation, configuring java.security policy file is sufficient to register the security provider. However, it doesnt seem to be the case. Though i see some related issues in github, not clear what is the correct solution . Please clarify

What i have already tried:

Tried with adding the following feature file, however it doesnt help 

`package com.pega.fnx.servicecommons;

import com.oracle.svm.core.annotate.AutomaticFeature;
import org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider;
import org.graalvm.nativeimage.hosted.Feature;
import org.graalvm.nativeimage.hosted.RuntimeClassInitialization;

import java.security.Security;

@AutomaticFeature
public class BouncyCastleFIPSFeature implements Feature {

    @Override
    public void afterRegistration(AfterRegistrationAccess access) {
        RuntimeClassInitialization.initializeAtBuildTime("org.bouncycastle");
        Security.addProvider(new BouncyCastleFipsProvider());
    }

}
`

**Comment by rodrigar-mx** [comment]
Hi @shashanka981. Could you please try using `-H:+TraceSecurityServices` and share the report, to see if the security provider is being registered.

**Comment by shashanka981** [comment]
It appears that security provider seems to be now registered. however, i see following errors while building the native image. Attached the file that has error messages.


[error messages.zip](https://github.com/oracle/graal/files/7750895/error.messages.zip)

**Comment by rodrigar-mx** [comment]
Try with the suggested flag --initialize-at-run-time=java.security.SecureRandom. Otherwise, please share a reproducer.

**Comment by shashanka981** [comment]
[example.zip](https://github.com/oracle/graal/files/7762320/example.zip)

Attached the zip that serves as a sample reproducer:

- Extract the zip
- Import it as a project
- Build the project
- Project also has sample docker that has instructions to run the native image - run the docker command - "docker build -t sample:1.0 .". You can notice the errors

**Comment by shashanka981** [comment]
@rodrigar-mx  any help here ?

**Comment by chirontt** [comment]
@shashanka981 how do you build and run your app (with Gradle) contained in the attached example.zip?

I'd like to run your app first in standard JVM, to see what it looks like, before even attempting to compile it to native image.

**Comment by shashanka981** [comment]
@chirontt  App works fine on standard jvm.. Building and running the app means running the commands - ./gradlew build and ./gradlew run.  If you are looking for specific details, let me know

**Comment by rodrigar-mx** [comment]
Hi @shashanka981. Sorry for the late response. I reviewed the code and do not think you need BouncyCastleFIPSFeature class. Please comment it because the providers can only be added statically and not through addProvider method. Also I noticed you are creating the file $JAVA_HOME/lib/security/java.security and appending the line  "security.provider.3=org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider". Instead of that, modify the file $JAVA_HOME/conf/security/java.security. If you view that file you can see a list of other providers almost at the beginning. Implement these changes, and please share your results.

**Comment by shashanka981** [comment]
@rodrigar-mx  I tried your suggestion and it didn't help. I have also added -H:+TraceSecurityServices option to identify if the service provider is registered and I do not see **BouncyCastleFipsProvider** in the generated security report

**Comment by rodrigar-mx** [comment]
Could you share the security report? After the previous changes, what error do you get?

**Comment by chirontt** [comment]
@shashanka981 yes, the app works fine in standard JVM, but how do you determine that it uses the FIPS provider at runtime?

The way I see it, it doesn't use that provider at all at runtime, but I could miss something...
