### ISSUE TITLE
Image build request failed with exit status 1

### ISSUE THREAD

**Issue by kamel2005** [oracle/graal#4144]
[libalssarimamana:6792]    classlist:  11,170.85 ms,  0.96 GB
[libalssarimamana:6792]        (cap):   1,950.93 ms,  0.96 GB
[libalssarimamana:6792]        setup:   3,910.62 ms,  0.96 GB
Error: Error compiling query code (in C:\Users\user\AppData\Local\Temp\SVM-2991951995775198052\WindowsDirectives.c). Compiler command ''C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\bin\HostX64\x64\cl.exe' /WX /W4 /wd4244 /wd4245 /wd4800 /wd4804 /wd4214 '/FeC:\Users\user\AppData\Local\Temp\SVM-2991951995775198052\WindowsDirectives.exe' 'C:\Users\user\AppData\Local\Temp\SVM-2991951995775198052\WindowsDirectives.c'' output included error: [WindowsDirectives.c, C:\Users\user\AppData\Local\Temp\SVM-2991951995775198052\WindowsDirectives.c(5): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory]
com.oracle.svm.core.util.UserError$UserException: Error compiling query code (in C:\Users\user\AppData\Local\Temp\SVM-2991951995775198052\WindowsDirectives.c). Compiler command ''C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\bin\HostX64\x64\cl.exe' /WX /W4 /wd4244 /wd4245 /wd4800 /wd4804 /wd4214 '/FeC:\Users\user\AppData\Local\Temp\SVM-2991951995775198052\WindowsDirectives.exe' 'C:\Users\user\AppData\Local\Temp\SVM-2991951995775198052\WindowsDirectives.c'' output included error: [WindowsDirectives.c, C:\Users\user\AppData\Local\Temp\SVM-2991951995775198052\WindowsDirectives.c(5): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory]
        at com.oracle.svm.core.util.UserError.abort(UserError.java:144)
        at com.oracle.svm.hosted.c.NativeLibraries.reportErrors(NativeLibraries.java:370)
        at com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1571)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1046)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:869)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:527)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
[libalssarimamana:6792]      [total]:  15,276.04 ms,  0.96 GB
# Printing build artifacts to: D:\amana\target\libalssarimamana.build_artifacts.txt
Error: Image build request failed with exit status 1

**Comment by kamel2005** [comment]
Windows 10 

openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05, mixed mode, sharing)

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, is it possible to share a small reproducer to illustrate the issue?

**Comment by kamel2005** [comment]
native-image --shared -H:Name=libalssarimamana -cp bcpg-jdk15to18-1.69.jar;bcprov-jdk15to18-1.69.jar;amana-1.0.jar

**Comment by kamel2005** [comment]
finally i run the cmd as admnistrator and it worked just fine.
