### ISSUE TITLE
java.beans.IntrospectionException: Method not found: isName

### ISSUE THREAD

**Issue by phial3** [oracle/graal#4167]
**Describe GraalVM and your environment :**
```
GraalVM CE 21.3.0 (build 17.0.1+12-jvmci-21.3-b05)
OS and OS Version: macOS Big sur
```

**Describe the issue**

code:
```
 PropertyDescriptor pd = new PropertyDescriptor(field, xxx.getClass());
```

result:
```
Caused by: java.beans.IntrospectionException: Method not found: isName
        at java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:110) ~[na:na]
        at java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:74) ~[na:na]

```

**Comment by rodrigar-mx** [comment]
Hi @phial3. Please review that you have correctly define the getters and setters. Otherwise, please share the full example, including the class from with the properties you are retrieving.

**Comment by rodrigar-mx** [comment]
Closing this issue because there has been no activity during last months.
