### ISSUE TITLE
URL::openStream fails when running on module path

### ISSUE THREAD

**Issue by jperedadnr** [oracle/graal#4169]
**Describe the issue**

Running native-image with latest dev build available (GraalVM CE 22.0.0-dev-20211222_1041) over a modular project:

- Running on the classpath: calling `Class::getResourceAsStream` or `Class::getResource` and then `URL::openStream` work as expected.
- Running on the modulepath: calling `Class::getResourceAsStream` works but calling `Class::getResource` and then `URL::openStream` fails.

**Steps to reproduce the issue**
HelloWorld.java
```
package hello;

import java.io.IOException;
import java.io.InputStream;
import java.net.URL;

public class HelloWorld {
    public static void main(String[] args) throws IOException {
        InputStream resourceAsStream = HelloWorld.class.getResourceAsStream("openduke.png");
        System.out.println("resourceAsStream: " + resourceAsStream);
        URL resource = HelloWorld.class.getResource("openduke.png");
        System.out.println("resource openStream: " + resource.openStream());
        System.exit(0);
    }
}
```

module-info.java
```
module helloworld {
    exports hello;
}
```
Include resource `hello/openduke.png`.

Running on class path:

`native-image -cp target/classes helloworld/hello.HelloWorld`

produces:
```
resourceAsStream: java.io.ByteArrayInputStream@5405fb3c
resource openStream: java.io.ByteArrayInputStream@3ae438bd
``` 

Running on module path:

`native-image --module-path target/classes --module helloworld/hello.HelloWorld`

produces:
```
resourceAsStream: java.io.ByteArrayInputStream@68e8ce0e
Exception in thread "main" java.io.FileNotFoundException: resource:hello/openduke.png
      at com.oracle.svm.core.jdk.resources.ResourceURLConnection.getInputStream(ResourceURLConnection.java:87)
      at java.net.URL.openStream(URL.java:1161)
      at hello.HelloWorld.main(HelloWorld.java:39)
```

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **GraalVM CE 22.0.0-dev-20211222_1041**
 - JDK major version: **17**
 - OS: **macOS Monterey**
 - Architecture: **AMD64**

**More details**

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, we will take a look into it and get back to you

**Comment by oubidar-Abderrahim** [comment]
Hi, could you please share the reproducer in a Github repo? Thank you

**Comment by jperedadnr** [comment]
I'm adding a zip with the HelloWorld project, after copying all the required files to a data folder (src has the java code but it is not needed). You need to run on a Mac.

The readme contains the instructions to run on class path or module path. Let me know if that works for you.


[HelloWorld.zip](https://github.com/oracle/graal/files/7840582/HelloWorld.zip)

**Comment by enderwsp** [comment]
any process?
as graal doc,resource is supported,
or any other suggestion about read file (project-resorces\jar-resources\externalpath\url)
