### ISSUE TITLE
JavaFx can't build with native-image

### ISSUE THREAD

**Issue by Anivie** [oracle/graal#4172]
I can build JavaFx application on jdk11 with graalvm,but then i build it with jdk17,i get an error at "complete" process:Fatal error:com.oracle.svm.core.util.VMError$HostedError: should not reach here
After reporting this error, he still output an exe file, it can be used normally on my local computer, but when others try to open this file, they will encounter various problems: white screen, fonts are not displayed.

This error will not appear on Jdk11 with graalvm.

Step to to reappear:

1. install visual studio 2022(2019 will have this error too) and choose c++ desktop to install
2. make jar file with gradle shadow plugins
3. call D:\VisualStudio\VC\Auxiliary\Build\vcvars64.bat
4. java -agentlib:native-image-agent=config-output-dir=.\native-image\ -jar my.jar
5. copy "native-image" into the jar
6. native-image --no-fallback -jar my.jar

My environment:
 - JDK major version: Jdk17.0.1
 - OS: Windows 7,10,11(all of them will have this error on jdk 17)
 - Architecture: AMD64

This is build error then it running on "complete" process 
```
Fatal error:com.oracle.svm.core.util.VMError$HostedError: should not reach here
        at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:64)
        at com.oracle.svm.hosted.jdk.JNIRegistrationSupport.makeShimDLL(JNIRegistrationSupport.java:256)
        at com.oracle.svm.hosted.jdk.JNIRegistrationSupport.makeShimDLLs(JNIRegistrationSupport.java:230)
        at com.oracle.svm.hosted.jdk.JNIRegistrationSupport.afterImageWrite(JNIRegistrationSupport.java:175)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$doRun$8(NativeImageGenerator.java:663)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:73)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:663)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
[maker:3544]      [total]: 117,305.90 ms,  5.53 GB

Printing build artifacts to: C:\Users\Administrator\Desktop\maker.build_artifacts.txt
Error: Image build request failed with exit status 1
```

It will have a exe file can work on my pc,but then it run on another pc:
`cacheDWRITE_MATRIXFields error: JNI exception or tmpClass == NULLcacheDWRITE_MATRIXFields error: JNI exception or tmpClass == NULLcacheDWRITE_MATRIXFields error: JNI exception or tmpClass == NULLcacheDWRITE_MATRIXFields error: JNI exception or tmpClass == NULLcacheDWRITE_MATRIXFields error: JNI exception or tmpClass == NULLcacheDWRITE_MATRIXFields error: JNI exception or tmpClass == NULLcacheDWRITE_MATRIXFields error: JNI exception or tmpClass == NULLcacheDWRITE_MATRIXFields error: JNI exception or tmpClass == NULLcacheDWRITE_MATRIXFields error: JNI exception or tmpClass == NULLcacheDWRITE_MATRIXFields error: JNI exception or tmpClass == NULLcacheDWRITE_MATRIXFields error: JNI exception or tmpClass == NULLcacheDWRITE_MATRIXFields error: JNI exception or tmpClass == NULLcacheDWRITE_MATRIXFields error: JNI exception or tmpClass == NULLcacheDWRITE_MATRIXFields error: JNI exception or tmpClass == NULLcacheDWRITE_MATRIXFields error: JNI exception or tmpClass == NULLcacheDWRITE_MATRIXFields error: JNI exception or tmpClass == NULLcacheDWRITE_MATRIXFields error: JNI exception or tmpClass == NULLcacheDWRITE_MATRIXFields error: JNI exception or tmpClass == NULLcacheDWRITE_MATRIXFields error: JNI exception or tmpClass == NULL`

**Comment by kkriske** [comment]
native-image does not support JavaFX out of the box.
JavaFX support is provided by Gluon, through the [GluonFX maven plugin](https://docs.gluonhq.com/#_gluonfx_plugin_for_maven).

**Comment by Anivie** [comment]
> native-image does not support JavaFX out of the box. JavaFX support is provided by Gluon, through the [GluonFX maven plugin](https://docs.gluonhq.com/#_gluonfx_plugin_for_maven).

I am using TornadoFx,so I can’t compile with gluon.Do you have another way?

**Comment by kkriske** [comment]
TornadoFX works with GluonFX: https://github.com/gluonhq/substrate/issues/572
