### ISSUE TITLE
[native-image] build crashes when trying to use mysql JDBC driver

### ISSUE THREAD

**Issue by rlewczuk** [oracle/graal#418]
I tried to compile following code:

```java
package dbtest;

import com.mysql.jdbc.Driver;
import java.sql.Connection;
import java.sql.DriverManager;

public class DbTest {

    public static void main(String[] args) {
        try {
            System.out.println(Driver.class);
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "test", "test");
            conn.close();
            System.out.println("OK");
        } catch (Exception e) {
            System.out.println("ERROR" + e);
        }
    }
}
```

Got following error:

```
$ ./build.sh
Build on Server(pid: 8493, port: 26682)
   classlist:     128.26 ms
       (cap):     526.57 ms
       setup:     683.54 ms
    analysis:   1,460.66 ms
7 fatal errors detected:
fatal error: java.lang.ArrayIndexOutOfBoundsException: -1
	at com.oracle.graal.pointsto.flow.MethodFlowsGraph.linkClones(MethodFlowsGraph.java:259)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:118)
	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:184)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:345)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:387)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:498)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:172)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
(above exception repeated several times)
Error: Processing image build request failed
```

Used following command:

```
native-image -cp mysql-connector-java-5.0.8.jar:target/classes dbtest.DbTest
```

Tested with several mysql-connector versions: 5.0.8, 5.1.6, 5.1.46, GraalVM CE 1.0-rc1. 

Not sure that it is but looks like some kind of internal error. If something inside JDBC/driver is not supported (yet), some more readable message would be useful.

Thanks and regards, 
rle

**Comment by cstancu** [comment]
@rlewczuk this looks like an internal error. Thank you for reporting.

**Comment by cstancu** [comment]
The `ArrayIndexOutOfBoundsException` is fixed in https://github.com/oracle/graal/commit/c066358c0cd8e792b82d5d81ed0963b9e950f613. Now the image builds (you can try [building from source](https://github.com/oracle/graal/tree/master/substratevm#quick-start)) however it looks like mysql-connector is using unsupported features like `java.lang.reflect.Proxy` and `java.lang.ClassLoader`. We will have limited support for these features soon. You can run `native-image` with the `-H:+ReportUnsupportedElementsAtRuntime` option to push those errors at runtime if those code paths are actually ever executed. However if you do that you will hit another limitation:
```
Error: Detected a started Thread in the image heap. This is not supported. The object was reached from a static initializer. All static class initialization is done during native image construction, thus a static initializer cannot contain code that captures state dependent on the build machine. Write your own initialization methods and call them explicitly from your main entry point.
Trace: 	object java.util.Timer
	field com.mysql.jdbc.Connection.cancelTimer
```
That's because the `com.mysql.jdbc.Connection.cancelTimer` field is initialized in a static initializer and `java.lang.Timer` starts a thread in its constructor. That could be easily avoided if you build from source and move the initialization of `com.mysql.jdbc.Connection.cancelTimer` at run time.
