### ISSUE TITLE
Accessing RandomAccessInputStream fails in native image

### ISSUE THREAD

**Issue by ebremer** [oracle/graal#4182]
**Describe the issue**
I have a project which converts VSI Whole Slide Images to TIFF.  It works.  It worked when using JDK11 of Graalvm https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.3.0.  When I converted it to the JDK17 version, the native-image version would fail, but the jar version still works.  The failure error message is as follows:

(base) erich@Corsair:/mnt/d/vsi$ ./hatch -v PC380089.vsi PC380089.tif
initializing...
Image Size : 36877x33920
Tile size  : 512x512
# of scales to be generated : 7
transferring image data...
0.0%
786432 FindFirstEOI : 6039 false 270454771
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 786432 out of bounds for length 786432
        at edu.stonybrook.bmi.hatch.JPEGTools.FindFirstEOI(JPEGTools.java:46)
        at edu.stonybrook.bmi.hatch.CellSensReader.getRaw(CellSensReader.java:1034)
        at edu.stonybrook.bmi.hatch.VSI2TIF.readWriteTiles(VSI2TIF.java:219)
        at edu.stonybrook.bmi.hatch.VSI2TIF.Execute(VSI2TIF.java:280)
        at edu.stonybrook.bmi.hatch.VSI2TIF.main(VSI2TIF.java:296)

In playing around with it, I added some System.out.println in the problem spot:
https://github.com/ebremer/hatch/blob/develop/src/main/java/edu/stonybrook/bmi/hatch/JPEGTools.java#L47-L50

Now, the weirdness starts, it works with the println added!  If I comment out the line:
              System.out.println(c+" DUMP : "+Integer.toHexString(r[c-1])+" "+Integer.toHexString(r[c]));
It fails again with native-image.  Mind you, the native-image builds, but during the run will throw the above error.
It seems when the println is not there, the comparison lines:
https://github.com/ebremer/hatch/blob/develop/src/main/java/edu/stonybrook/bmi/hatch/JPEGTools.java#L51-L52
Never see the FFD8 pattern I am looking for which is the end of the embedded JPEG stream in the VSI file.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. git clone https://github.com/ebremer/hatch.git
2. checkout develop
3. build with maven
4. use the above run line to execute.
5. I don't have a vsi (due to PHI) file I can share at the moment.  I will try to track down a non-PHI VSI to reproduce.

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **[e.g. EE 19.3, CE 20.0, CE 20.1.0-dev-20200304_0848]**
 - JDK17
 - Ubuntu 20
 - AMD64
 - https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.3.0

**More details**
Problem occurs using latest nightly build of 
https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/22.0.0-dev-20220103_1601

**Comment by ebremer** [comment]
System.out.println after the comparisons:
https://github.com/ebremer/hatch/blob/develop/src/main/java/edu/stonybrook/bmi/hatch/JPEGTools.java#L51-L52
will print but does not "fix" the problem.  Only a System.out.println BEFORE the comparisons will make it work under native-image.  I added System.out.println in the else portion of the comparisons to see what data it thought it was seeing and it is seeing the correct data.  It appears the Byte.compare just fails but will work if there is a System.out.println as specified above.  Weird.

**Comment by ebremer** [comment]
It does appear to how Byte.compare handles things in native-image.  

Byte.compare is:
    public static int compare(byte x, byte y) {
        return x - y;
    }

I wrote my own comparison method which works now in native-image

    public static int Compare(byte a, byte b) {
        return 0xff&(a-b);
    }

Why the System.out.println BEFORE the Byte.compare makes it work is completely weird.

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, we will take a look into it and get back to you

**Comment by oubidar-Abderrahim** [comment]
Hi, Could you also share the native-image command you use to build the image? thank you

**Comment by christianwimmer** [comment]
I can reproduce the problem with GraalVM 21.3, but no longer with the latest 22.0 or 21.3.1 snapshots that are coming out tomorrow. I will double-check, but so far it is looking promising that we already found and fixed the problem.

**Comment by ebremer** [comment]
@oubidar-Abderrahim

native-image -H:ConfigurationFileDirectories=/mnt/d/projects/hatch/config -jar /mnt/d/projects/hatch/target/hatch-1.1.2.jar --no-fallback --allow-incomplete-classpath --report-unsupported-elements-at-runtime /mnt/d/vsi/hatch

**Comment by mur47x111** [comment]
Could be fixed by https://github.com/oracle/graal/commit/868d594df1f925072b007cb5d3297bba4dd04306

**Comment by christianwimmer** [comment]
@ebremer GraalVM 22.0 and 21.3.1 are released (also the CE versions now), can you please check if the problem is fixed?
