### ISSUE TITLE
LINK : fatal error LNK1171: unable to load mspdbcore.dll (error code: 1455)

### ISSUE THREAD

**Issue by aalmiray** [oracle/graal#4189]
**Describe the issue**
Stumbled upon this issue when building a native image using https://github.com/marketplace/actions/github-action-for-graalvm on `windows-latest`

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Fork `https://github.com/aalmiray/test`
2. Run the Graal workflow using workflow dispatch

**Describe GraalVM and your environment:**
 - GraalVM version: **CE 21.3.0**
 - JDK major version: **17**
 - OS: **Windows 2019**
 - Architecture: **AMD64**

**More details**

```
[INFO]  Assembling all distributions with native-image
[INFO]    [native-image] assembling jreleaser-native distribution
[INFO]    [native-image] - jreleaser-early-access-windows-x86_64
[INFO]    [native-image] [jreleaser:3708]    classlist:   8,633.87 ms,  0.96 GB
[INFO]    [native-image] [jreleaser:3708]        (cap):  12,622.02 ms,  0.96 GB
[INFO]    [native-image] [jreleaser:3708]        setup:  16,003.95 ms,  0.96 GB
[INFO]    [native-image] [jreleaser:3708]     (clinit):   2,183.77 ms,  4.23 GB
[INFO]    [native-image] [jreleaser:3708]   (typeflow):  35,662.86 ms,  4.23 GB
[INFO]    [native-image] [jreleaser:3708]    (objects): 126,875.47 ms,  4.23 GB
[INFO]    [native-image] [jreleaser:3708]   (features):  23,662.69 ms,  4.23 GB
[INFO]    [native-image] [jreleaser:3708]     analysis: 192,297.47 ms,  4.23 GB
[INFO]    [native-image] [jreleaser:3708]     universe:  13,768.51 ms,  4.24 GB
[INFO]    [native-image] [jreleaser:3708]      (parse):  71,106.91 ms,  4.09 GB
[INFO]    [native-image] [jreleaser:3708]     (inline):  27,057.65 ms,  4.27 GB
[INFO]    [native-image] [jreleaser:3708]    (compile): 104,271.24 ms,  4.51 GB
[INFO]    [native-image] [jreleaser:3708]      compile: 209,376.02 ms,  4.51 GB
[INFO]    [native-image] [jreleaser:3708]        image:  12,647.92 ms,  4.32 GB
[INFO]    [native-image] [jreleaser:3708]        write:   1,736.58 ms,  4.32 GB
[INFO]    [native-image] [jreleaser:3708]      [total]: 455,568.31 ms,  4.32 GB
[INFO]    [native-image] # Printing build artifacts to: D:\a\test\test\out\jreleaser\assemble\jreleaser-native\native-image\jreleaser.build_artifacts.txt
[ERROR]   [native-image] Warning: Could not resolve apple.security.AppleProvider for reflection configuration. Reason: java.lang.ClassNotFoundException: apple.security.AppleProvider.
[ERROR]   [native-image] Fatal error:java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 2
[ERROR]   [native-image] 
[ERROR]   [native-image] Linker command executed:
[ERROR]   [native-image] 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe' '/FeD:\a\test\test\out\jreleaser\assemble\jreleaser-native\native-image\jreleaser.exe' jreleaser.obj 'C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\svm\clibraries\windows-amd64\libchelper.lib' 'C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64\net.lib' 'C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64\nio.lib' 'C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64\java.lib' 'C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64\fdlibm.lib' 'C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64\sunmscapi.lib' 'C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64\zip.lib' 'C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\svm\clibraries\windows-amd64\jvm.lib' /MD 'C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\svm\clibraries\windows-amd64\libchelper.lib' 'C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64\net.lib' 'C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64\nio.lib' 'C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64\java.lib' 'C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64\fdlibm.lib' 'C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64\sunmscapi.lib' 'C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64\zip.lib' 'C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\svm\clibraries\windows-amd64\jvm.lib' /link /INCREMENTAL:NO /NODEFAULTLIB:LIBCMT '/IMPLIB:C:\Users\RUNNER~1\AppData\Local\Temp\SVM-10808899318650343417\jreleaser.lib' '/LIBPATH:C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64' '/LIBPATH:C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\svm\clibraries\windows-amd64' winhttp.lib ncrypt.lib crypt32.lib version.lib advapi32.lib ws2_32.lib secur32.lib iphlpapi.lib userenv.lib setargv.obj /include:JDK_LoadSystemLibrary /include:getEncodingFromLangID /include:getJavaIDFromLangID shell32.lib
[ERROR]   [native-image] 
[ERROR]   [native-image] Linker command output:
[ERROR]   [native-image] Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30138 for x64
[ERROR]   [native-image] Copyright (C) Microsoft Corporation.  All rights reserved.
[ERROR]   [native-image] 
[ERROR]   [native-image] Microsoft (R) Incremental Linker Version 14.29.30138.0
[ERROR]   [native-image] Copyright (C) Microsoft Corporation.  All rights reserved.
[ERROR]   [native-image] 
[ERROR]   [native-image] /out:D:\a\test\test\out\jreleaser\assemble\jreleaser-native\native-image\jreleaser.exe 
[ERROR]   [native-image] /INCREMENTAL:NO 
[ERROR]   [native-image] /NODEFAULTLIB:LIBCMT 
[ERROR]   [native-image] /IMPLIB:C:\Users\RUNNER~1\AppData\Local\Temp\SVM-10808899318650343417\jreleaser.lib 
[ERROR]   [native-image] /LIBPATH:C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64 
[ERROR]   [native-image] /LIBPATH:C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\svm\clibraries\windows-amd64 
[ERROR]   [native-image] winhttp.lib 
[ERROR]   [native-image] ncrypt.lib 
[ERROR]   [native-image] crypt32.lib 
[ERROR]   [native-image] version.lib 
[ERROR]   [native-image] advapi32.lib 
[ERROR]   [native-image] ws2_32.lib 
[ERROR]   [native-image] secur32.lib 
[ERROR]   [native-image] iphlpapi.lib 
[ERROR]   [native-image] userenv.lib 
[ERROR]   [native-image] setargv.obj 
[ERROR]   [native-image] /include:JDK_LoadSystemLibrary 
[ERROR]   [native-image] /include:getEncodingFromLangID 
[ERROR]   [native-image] /include:getJavaIDFromLangID 
[ERROR]   [native-image] shell32.lib 
[ERROR]   [native-image] jreleaser.obj 
[ERROR]   [native-image] C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\svm\clibraries\windows-amd64\libchelper.lib 
[ERROR]   [native-image] C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64\net.lib 
[ERROR]   [native-image] C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64\nio.lib 
[ERROR]   [native-image] C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64\java.lib 
[ERROR]   [native-image] C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64\fdlibm.lib 
[ERROR]   [native-image] C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64\sunmscapi.lib 
[ERROR]   [native-image] C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64\zip.lib 
[ERROR]   [native-image] C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\svm\clibraries\windows-amd64\jvm.lib 
[ERROR]   [native-image] C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\svm\clibraries\windows-amd64\libchelper.lib 
[ERROR]   [native-image] C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64\net.lib 
[ERROR]   [native-image] C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64\nio.lib 
[ERROR]   [native-image] C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64\java.lib 
[ERROR]   [native-image] C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64\fdlibm.lib 
[ERROR]   [native-image] C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64\sunmscapi.lib 
[ERROR]   [native-image] C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\static\windows-amd64\zip.lib 
[ERROR]   [native-image] C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\lib\svm\clibraries\windows-amd64\jvm.lib 
[ERROR]   [native-image] LINK : fatal error LNK1171: unable to load mspdbcore.dll (error code: 1455)
[ERROR]   [native-image] 	at com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:502)
[ERROR]   [native-image] 	at com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:449)
[ERROR]   [native-image] 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:657)
[ERROR]   [native-image] 	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
[ERROR]   [native-image] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
[ERROR]   [native-image] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
[ERROR]   [native-image] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
[ERROR]   [native-image] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
[ERROR]   [native-image] Error: Image build request failed with exit status 1
```

Command line used to build the image

```
[DEBUG]   [native-image] C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\bin\native-image.cmd -Duser.language=en -H:IncludeLocales=en,ca,de,es,fr,hi,it,ja,nl,pt_BR,zh_TW,ru -H:Optimize=2 -H:+RemoveUnusedSymbols -H:TraceClassInitialization=apple.security.AppleProvider --report-unsupported-elements-at-runtime -jar D:\a\test\test\apps\jreleaser\build\libs\jreleaser-1.0.0-SNAPSHOT.jar -cp D:\a\test\test\apps\jreleaser\build\libs\jreleaser-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\artifactory-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\aws-java-sdk-core-1.12.131.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\aws-java-sdk-kms-1.12.131.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\aws-java-sdk-s3-1.12.131.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\bcpg-jdk15on-1.68.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\bcprov-jdk15on-1.68.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\classmate-1.5.1.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\codeberg-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\commons-codec-1.15.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\commons-compress-1.21.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\commons-io-2.11.0.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\commons-lang3-3.12.0.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\compiler-0.9.10.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\discord-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\feign-core-11.8.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\feign-form-3.8.0.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\feign-httpclient-11.8.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\feign-jackson-11.8.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\genericgit-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\git-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\gitea-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\github-api-1.129.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\github-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\gitlab-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\gitter-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\google-chat-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\http-upload-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\httpclient-4.5.13.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\httpcore-4.4.13.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\ion-java-1.0.2.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jackson-annotations-2.13.1.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jackson-core-2.13.1.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jackson-databind-2.13.1.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jackson-dataformat-cbor-2.13.1.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jackson-dataformat-toml-2.13.1.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jackson-dataformat-yaml-2.13.1.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jakarta.activation-2.0.1.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jakarta.mail-2.0.1.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\java-sdk-commons-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\JavaEWAH-1.1.12.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jcl-over-slf4j-1.7.32.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jmespath-java-1.12.131.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\joda-time-2.8.1.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jreleaser-assemblers-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jreleaser-config-json-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jreleaser-config-toml-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jreleaser-config-yaml-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jreleaser-engine-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jreleaser-model-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jreleaser-templates-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jreleaser-tools-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jreleaser-utils-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jreleaser-workflow-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jsonschema-generator-4.21.0.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jsonschema-module-jackson-4.21.0.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\mail-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\mastodon-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\mattermost-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\org.eclipse.jgit-5.13.0.202109080827-r.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\org.tukaani.xz-0.3.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\os-maven-plugin-1.7.0.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\picocli-4.6.2.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\s3-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\sdkman-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\slack-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\slf4j-api-1.7.32.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\slf4j-simple-1.7.32.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\snakeyaml-1.30.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\teams-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\telegram-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\tika-core-2.2.1.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\tool-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\twitter-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\twitter4j-core-4.0.7.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\webhooks-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\yamllint-1.5.0.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\zt-exec-1.12.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\zulip-java-sdk-1.0.0-SNAPSHOT.jar -H:Name=jreleaser
[DEBUG]   [native-image] C:\Users\RUNNER~1\AppData\Local\Temp\jreleaser-command6109196677148892391args: C:\Users\runneradmin\.graalvm\graalvm-ce-java17-21.3.0\bin\native-image.cmd -Duser.language=en -H:IncludeLocales=en,ca,de,es,fr,hi,it,ja,nl,pt_BR,zh_TW,ru -H:Optimize=2 -H:+RemoveUnusedSymbols -H:TraceClassInitialization=apple.security.AppleProvider --report-unsupported-elements-at-runtime -jar D:\a\test\test\apps\jreleaser\build\libs\jreleaser-1.0.0-SNAPSHOT.jar -cp D:\a\test\test\apps\jreleaser\build\libs\jreleaser-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\artifactory-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\aws-java-sdk-core-1.12.131.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\aws-java-sdk-kms-1.12.131.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\aws-java-sdk-s3-1.12.131.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\bcpg-jdk15on-1.68.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\bcprov-jdk15on-1.68.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\classmate-1.5.1.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\codeberg-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\commons-codec-1.15.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\commons-compress-1.21.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\commons-io-2.11.0.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\commons-lang3-3.12.0.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\compiler-0.9.10.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\discord-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\feign-core-11.8.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\feign-form-3.8.0.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\feign-httpclient-11.8.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\feign-jackson-11.8.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\genericgit-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\git-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\gitea-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\github-api-1.129.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\github-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\gitlab-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\gitter-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\google-chat-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\http-upload-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\httpclient-4.5.13.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\httpcore-4.4.13.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\ion-java-1.0.2.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jackson-annotations-2.13.1.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jackson-core-2.13.1.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jackson-databind-2.13.1.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jackson-dataformat-cbor-2.13.1.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jackson-dataformat-toml-2.13.1.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jackson-dataformat-yaml-2.13.1.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jakarta.activation-2.0.1.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jakarta.mail-2.0.1.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\java-sdk-commons-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\JavaEWAH-1.1.12.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jcl-over-slf4j-1.7.32.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jmespath-java-1.12.131.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\joda-time-2.8.1.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jreleaser-assemblers-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jreleaser-config-json-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jreleaser-config-toml-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jreleaser-config-yaml-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jreleaser-engine-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jreleaser-model-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jreleaser-templates-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jreleaser-tools-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jreleaser-utils-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jreleaser-workflow-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jsonschema-generator-4.21.0.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\jsonschema-module-jackson-4.21.0.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\mail-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\mastodon-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\mattermost-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\org.eclipse.jgit-5.13.0.202109080827-r.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\org.tukaani.xz-0.3.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\os-maven-plugin-1.7.0.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\picocli-4.6.2.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\s3-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\sdkman-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\slack-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\slf4j-api-1.7.32.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\slf4j-simple-1.7.32.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\snakeyaml-1.30.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\teams-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\telegram-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\tika-core-2.2.1.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\tool-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\twitter-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\twitter4j-core-4.0.7.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\webhooks-java-sdk-1.0.0-SNAPSHOT.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\yamllint-1.5.0.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\zt-exec-1.12.jar;D:\a\test\test\apps\jreleaser\build\dependencies\flat\zulip-java-sdk-1.0.0-SNAPSHOT.jar -H:Name=jreleaser
```

Build job defined as https://github.com/aalmiray/test/blob/cc26b57df7413d7c3b8201c10a68e681d3e324b7/.github/workflows/native-image.yml#L6-L78

**Comment by aalmiray** [comment]
Related https://github.com/oracle/graal/issues/3171

**Comment by aalmiray** [comment]
This issue has surfaced again https://github.com/jreleaser/jreleaser/actions/runs/4546403129/jobs/8017802452

I believe this commit is the one that causes the build to break https://github.com/jreleaser/jreleaser/commit/0a5c4baa51414d1b7b391a341ac270380e713c64 It has nothing to do with GraalVM Native Image settings. Rather I think it's the code size. Linux and MacOS are working as expected, only Windows fails.

**Comment by fniephaus** [comment]
As mentioned in https://github.com/oracle/graal/issues/3171#issuecomment-860643090, this appears to be an OutOfmemory error within the VS linker. This also explains why you got the error without touching anything GraalVM-related. The Windows runners have limited memory (7GB) and if GitHub decides to update the VS installation in their runner, a newer version of the VS linker may require more memory. If that is just too much for the 7GB, the linker will fail. We are hitting this issue ourselves in some places and are looking for a way to mitigate this problem.
