### ISSUE TITLE
Failed to load Graal compiler on non-GraalVM 

### ISSUE THREAD

**Issue by guygoldwasser** [oracle/graal#4201]
- GraalVM version 21.3.0
 - CE or EE: both
 - JDK version: 17
 - OS and OS Version: WIN10

Migration from Rhino. SpringBoot App with heavy JS.
While trying use the GraalVM found out Rhino with compilation runs much faster.
Wondering if it is vm issue or graal compiler, tried to load the compiler to non graal vm.

in order to do so, added dependencies:
```
    <dependency>
         <groupId>org.graalvm.compiler</groupId>
         <artifactId>compiler</artifactId>
         <version>21.3.0</version>
    </dependency>
    <dependency>
	<groupId>org.graalvm.compiler</groupId>
        <artifactId>compiler-management</artifactId>
	<version>21.3.0</version>
   </dependency>
```

and set those VMs arguments:
--add-exports jdk.internal.vm.ci/jdk.vm.ci.code=ALL-UNNAMED
--add-exports jdk.internal.vm.ci/jdk.vm.ci.services=ALL-UNNAMED
--add-exports jdk.internal.vm.ci/jdk.vm.ci.hotspot=ALL-UNNAMED
-XX:+UnlockExperimentalVMOptions
-XX:+EnableJVMCI

the conclusion is this failure:
```
Caused by: org.graalvm.polyglot.PolyglotException: java.lang.AssertionError: Compiler initialization failed cannot continue.
	at org.graalvm.compiler.truffle.runtime.hotspot.AbstractHotSpotTruffleRuntime.bypassedReservedOop(AbstractHotSpotTruffleRuntime.java:497) ~[compiler-21.3.0.jar:?]
	at org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReference(HotSpotFastThreadLocal.java:86) ~[compiler-21.3.0.jar:?]
	at org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.get(HotSpotFastThreadLocal.java:71) ~[compiler-21.3.0.jar:?]
	at org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReferenceNoFallback(HotSpotFastThreadLocal.java:122) ~[compiler-21.3.0.jar:?]
	at org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.getJVMCIReservedReference(HotSpotFastThreadLocal.java:92) ~[compiler-21.3.0.jar:?]
	at org.graalvm.compiler.truffle.runtime.hotspot.HotSpotFastThreadLocal.get(HotSpotFastThreadLocal.java:71) ~[compiler-21.3.0.jar:?]
	at org.graalvm.compiler.truffle.runtime.GraalFastThreadLocal.fastGet(GraalFastThreadLocal.java:64) ~[compiler-21.3.0.jar:?]
	at com.oracle.truffle.polyglot.PolyglotFastThreadLocals.needsEnter(PolyglotFastThreadLocals.java:145) ~[truffle-api-21.3.0.jar:?]
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.needsEnter(PolyglotEngineImpl.java:1807) ~[truffle-api-21.3.0.jar:?]
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.enterIfNeeded(PolyglotEngineImpl.java:1812) ~[truffle-api-21.3.0.jar:?]
	at com.oracle.truffle.polyglot.PolyglotLanguageInstance.lookupValueCache(PolyglotLanguageInstance.java:159) ~[truffle-api-21.3.0.jar:?]
	at com.oracle.truffle.polyglot.PolyglotLanguageContext.asValue(PolyglotLanguageContext.java:787) ~[truffle-api-21.3.0.jar:?]
	at com.oracle.truffle.polyglot.PolyglotBindingsValue.<init>(PolyglotBindingsValue.java:61) ~[truffle-api-21.3.0.jar:?]
	at com.oracle.truffle.polyglot.PolyglotContextImpl.initPolyglotBindings(PolyglotContextImpl.java:1008) ~[truffle-api-21.3.0.jar:?]
	at com.oracle.truffle.polyglot.PolyglotContextImpl.getPolyglotBindings(PolyglotContextImpl.java:984) ~[truffle-api-21.3.0.jar:?]
	at com.oracle.truffle.polyglot.PolyglotContextDispatch.getPolyglotBindings(PolyglotContextDispatch.java:102) ~[truffle-api-21.3.0.jar:?]
	at org.graalvm.polyglot.Context.getPolyglotBindings(Context.java:523) ~[graal-sdk-21.3.0.jar:?]
```

**Comment by rodrigar-mx** [comment]
Hi @guygoldwasser. Could you please share a reproducer or the piece of code that is causing this exception.

**Comment by guygoldwasser** [comment]
> Hi @guygoldwasser. Could you please share a reproducer or the piece of code that is causing this exception.

sure:
```
GraalJSScriptEngine engine = GraalJSScriptEngine.create(null, Context.newBuilder("js").
				allowValueSharing(true).option("js.foreign-object-prototype", "true").
				allowPolyglotAccess(PolyglotAccess.ALL).
				allowIO(true).allowNativeAccess(true).
				allowHostAccess(HostAccess.ALL).
				allowHostClassLoading(true).
				allowHostClassLookup(s->true)
				);
		Bindings bindings = engine.createBindings();
		engine.setBindings(bindings, ScriptContext.ENGINE_SCOPE);
                bindings .put("x","y");// this will finally will trigger context creation that continue with the above exception

```

if removing compiler dependency it work well just with interpreter.

**Comment by rodrigar-mx** [comment]
Hi again @guygoldwasser. Please  follow the instructions [here](https://www.graalvm.org/reference-manual/js/RunOnJDK/#graalvm-javascript-on-jdk-11) to run graaljs on jdk 11+. I tested your program and did not get any errors. I used
```
java version "11.0.11" 2021-04-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.11+9-LTS-194)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.11+9-LTS-194, mixed mode)
```
dowloaded the required jars, and then run the command:
`/Library/Java/JavaVirtualMachines/jdk-11.0.11.jdk/Contents/Home/bin/java -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler --module-path=$JARS/graal-sdk-21.3.1.jar:$JARS/truffle-api-21.3.1.jar --upgrade-module-path=$JARS/compiler-21.3.1.jar:$JARS/compiler-management-21.3.1.jar -cp $JARS/launcher-common-21.3.1.jar:$JARS/js-launcher-21.3.1.jar:$JARS/js-21.3.1.jar:$JARS/truffle-api-21.3.1.jar:$JARS/graal-sdk-21.3.1.jar:$JARS/js-scriptengine-21.3.1.jar:$JARS/regex-21.3.1.jar:$JARS/icu4j-70.1.jar:target/classes/ Main`

**Comment by guygoldwasser** [comment]
Thanks @rodrigar-mx . this solved my issue.
Thanks
