### ISSUE TITLE
TRegex lazy matchers ignore flavor processors

### ISSUE THREAD

**Issue by nirvdrum** [oracle/graal#4242]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **1bc9a8623c9e9e3444e53d183f03a5bf535f2b48**
 - CE or EE: **CE**
 - JDK version: **JDK11**
 - OS and OS Version: **macOS 12.1**
 - Architecture: **amd64 (Rosetta)**
 - The output of `java -Xinternalversion`:
```
OpenJDK 64-Bit Server VM (11.0.13+8-jvmci-22.0-b02) for bsd-amd64 JRE (11.0.13+8-jvmci-22.0-b02), built on Nov 22 2021 14:39:18 by "graal" with clang 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)
```

**Have you verified this issue still happens when using the latest snapshot?**
Yes.

**Describe the issue**
When adopting TRegex's new `execBoolean` functionality in TruffleRuby, we encountered an issue where a regex would work fine with `exec`, but not `execBoolean`. When adding the `BooleanMatch=true` flag to the regex compilation, we saw the inverse behavior.

**Code snippet or code repository that reproduces the issue**

In order to reproduce the issue in TruffleRuby, you'll need to build from source from the [tregex-optimized-boolean-match branch](https://github.com/Shopify/truffleruby/tree/tregex-optimized-boolean-match) in our fork.

```ruby
"abc".match(/./x)  # => Okay
"abc".match?(/./x) # => interop exception: Unsupported regex flag (com.oracle.truffle.regex.RegexSyntaxException) (RuntimeError)
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Clone the repo at https://github.com/Shopify/truffleruby
2. Build the branch _tregex-optimized-boolean-match_
3. Use `Regexp#match?` or `String#match?` with a regular expression with a flag handled by TRegex's Ruby processor, but which otherwise would be invalid in vanilla TRegex, such as the`/x` flag.

**Expected behavior**
I'd expect `exec` and `execBoolean` to admit the same inputs. I'd expect both cases to apply the Ruby flavor processor.

**Additional context**

<details><summary>Parsing trace when using the Ruby flavor processor</summary>

```
	  at com.oracle.truffle.regex.tregex.TRegexCompilationRequest.createParser(TRegexCompilationRequest.java:318)
	  at com.oracle.truffle.regex.tregex.TRegexCompilationRequest.compileInternal(TRegexCompilationRequest.java:148)
	  at com.oracle.truffle.regex.tregex.TRegexCompilationRequest.compile(TRegexCompilationRequest.java:134)
	  at com.oracle.truffle.regex.tregex.TRegexCompiler.doCompile(TRegexCompiler.java:96)
	  at com.oracle.truffle.regex.tregex.TRegexCompiler.compile(TRegexCompiler.java:77)
	  at com.oracle.truffle.regex.RegexLanguage.createRegexObject(RegexLanguage.java:186)
	  at com.oracle.truffle.regex.RegexLanguage.parse(RegexLanguage.java:149)
	  at com.oracle.truffle.api.TruffleLanguage$ParsingRequest.parse(TruffleLanguage.java:949)
	  at com.oracle.truffle.api.TruffleLanguage.parse(TruffleLanguage.java:1306)
	  at com.oracle.truffle.api.LanguageAccessor$LanguageImpl.parse(LanguageAccessor.java:300)
	  at com.oracle.truffle.polyglot.PolyglotSourceCache.parseImpl(PolyglotSourceCache.java:94)
	  at com.oracle.truffle.polyglot.PolyglotSourceCache.access$300(PolyglotSourceCache.java:56)
	  at com.oracle.truffle.polyglot.PolyglotSourceCache$WeakCache.lookup(PolyglotSourceCache.java:222)
	  at com.oracle.truffle.polyglot.PolyglotSourceCache.parseCached(PolyglotSourceCache.java:80)
	  at com.oracle.truffle.polyglot.PolyglotLanguageContext.parseCached(PolyglotLanguageContext.java:369)
	  at com.oracle.truffle.polyglot.EngineAccessor$EngineImpl.parseForLanguage(EngineAccessor.java:247)
	  at com.oracle.truffle.api.TruffleLanguage$Env.parseInternal(TruffleLanguage.java:2231)
	  at org.truffleruby.core.regexp.TRegexCache.compileTRegex(TRegexCache.java:183)
	  at org.truffleruby.core.regexp.TRegexCache.compile(TRegexCache.java:69)
```
</details>

<details><summary>Parsing trace when constructing the lazy `execBoolean` matcher</summary>

```
	  at com.oracle.truffle.regex.tregex.TRegexCompilationRequest.createParser(TRegexCompilationRequest.java:318)
	  at com.oracle.truffle.regex.tregex.TRegexCompilationRequest.compileInternal(TRegexCompilationRequest.java:148)
	  at com.oracle.truffle.regex.tregex.TRegexCompilationRequest.compile(TRegexCompilationRequest.java:134)
	  at com.oracle.truffle.regex.RegexObject.getExecCallTarget(RegexObject.java:182)
	  at com.oracle.truffle.regex.RegexObject$InvokeCacheNode.execBytesIdentity(RegexObject.java:339)
	  at com.oracle.truffle.regex.RegexObjectFactory$InvokeCacheNodeGen.executeAndSpecialize(RegexObjectFactory.java:307)
	  at com.oracle.truffle.regex.RegexObjectFactory$InvokeCacheNodeGen.execute(RegexObjectFactory.java:122)
	  at com.oracle.truffle.regex.RegexObject.invokeMember(RegexObject.java:286)
	  at com.oracle.truffle.regex.RegexObjectGen$InteropLibraryExports$Cached.invokeMemberNode_AndSpecialize(RegexObjectGen.java:238)
	  at com.oracle.truffle.regex.RegexObjectGen$InteropLibraryExports$Cached.invokeMember(RegexObjectGen.java:224)
	  at com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.invokeMember(InteropLibraryGen.java:8211)
	  at org.truffleruby.core.regexp.TruffleRegexpNodes$MatchInRegionTRegexNode.invoke(TruffleRegexpNodes.java:1052)
	  at org.truffleruby.core.regexp.TruffleRegexpNodes$MatchInRegionTRegexNode.matchInRegionTRegex(TruffleRegexpNodes.java:968)
	  at org.truffleruby.core.regexp.TruffleRegexpNodesFactory$MatchInRegionTRegexNodeFactory$MatchInRegionTRegexNodeGen.executeAndSpecialize(TruffleRegexpNodesFactory.java:1384)
	  at org.truffleruby.core.regexp.TruffleRegexpNodesFactory$MatchInRegionTRegexNodeFactory$MatchInRegionTRegexNodeGen.execute(TruffleRegexpNodesFactory.java:1341)
```
</details>

**Comment by nirvdrum** [comment]
cc @djoooooe

**Comment by djoooooe** [comment]
Should be fixed by https://github.com/oracle/graal/commit/280594dd6381fb9f74a33b76378b57e6eee50daa
