### ISSUE TITLE
Graal.nodejs fails if experimental WebAssembly turned on

### ISSUE THREAD

**Issue by CommanderTvis** [oracle/graal#4263]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **22.0**
 - CE or EE: **CE**
 - JDK version: **JDK11**
 - OS and OS Version: **Kubuntu 21.10 Impish Indri**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
OpenJDK 64-Bit Server VM (11.0.14+9-jvmci-22.0-b05) for linux-amd64 JRE (11.0.14+9-jvmci-22.0-b05), built on Jan 20 2022 10:48:34 by "buildslave" with gcc 7.3.0
```

**Describe the issue**

A clear and concise description of the issue.

**Steps to reproduce the issue**
Please include both build steps as well as run steps

1. `gu install nodejs`
1. `gu install wasm`
1. `node --experimental-options --js.webassembly`

**Expected behavior**
`node` runs successfully.

**Additional context**

<details><summary>Details</summary>

```
org.graalvm.polyglot.PolyglotException: java.lang.IllegalStateException: WebAssembly API enabled but wasm language cannot be accessed!
        at com.oracle.truffle.js.runtime.JSRealm.<init>(JSRealm.java:788)
        at com.oracle.truffle.js.runtime.JSContext.createRealm(JSContext.java:664)
        at com.oracle.truffle.js.runtime.JSContext.createRealm(JSContext.java:654)
        at com.oracle.truffle.js.lang.JavaScriptLanguage.createContext(JavaScriptLanguage.java:335)
        at com.oracle.truffle.js.lang.JavaScriptLanguage.createContext(JavaScriptLanguage.java:114)
        at com.oracle.truffle.api.LanguageAccessor$LanguageImpl.createEnvContext(LanguageAccessor.java:271)
        at com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureCreated(PolyglotLanguageContext.java:591)
        at com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureInitialized(PolyglotLanguageContext.java:670)
        at com.oracle.truffle.polyglot.PolyglotContextImpl.initializeLanguage(PolyglotContextImpl.java:1242)
        at com.oracle.truffle.polyglot.PolyglotContextImpl.initializeLanguage(PolyglotContextImpl.java:1251)
        at com.oracle.truffle.polyglot.PolyglotContextDispatch.initializeLanguage(PolyglotContextDispatch.java:58)
        at org.graalvm.polyglot.Context.initialize(Context.java:576)
        at com.oracle.truffle.js.lang.JavaScriptLanguage.getJSRealm(JavaScriptLanguage.java:503)
        at com.oracle.truffle.trufflenode.GraalJSAccess.<init>(GraalJSAccess.java:379)
        at com.oracle.truffle.trufflenode.GraalJSAccess.create(GraalJSAccess.java:427)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS_GraalJSAccess_create_fdcfec72ba862dacb59a72e9bf4128132c73e8cc(JNIJavaCallWrappers.java:0)
Caused by: Attached Guest Language Frames (0)
```
</details>

**Comment by CommanderTvis** [comment]
Wrong repo.
