### ISSUE TITLE
[LLVM] Exception in thread "main" Allocation of native memory is not possible in managed mode when using C++ exceptions

### ISSUE THREAD

**Issue by roxanan-adyen** [oracle/graal#4291]
**Describe GraalVM and your environment :**
 - GraalVM version: **22.0.0**
 - **EE**
 - JDK version: **JDK11**
 - OS and OS Version: **macOS bigSur**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
 **Java HotSpot(TM) 64-Bit Server VM (11.0.14+8-LTS-jvmci-22.0-b03) for bsd-amd64 JRE (11.0.14+8-LTS-jvmci-22.0-b03), built on Jan  2 2022 15:02:19 by "graal1" with gcc 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)**
```

**Have you verified this issue still happens when using the latest snapshot?**
Only tried it with 22.0.0

**Describe the issue**
I have a small C++ program where I throw an exception. This is built as a library that is loaded by a java app. In the java app, I get this error when I try to execute the C++ function:
```
Exception in thread "main" Allocation of native memory is not possible in managed mode.
```

**How to compile the LLVM bitcode that causes the problem**
 Compile C++ lib:
 ```
 $GRAALVM_MANAGED_LLVM_TOOLCHAIN/clang++ -fPIC -shared exception.cpp -lgraalvm-llvm -o exception.so
 ```
Where 
```
export GRAALVM_MANAGED_LLVM_TOOLCHAIN=$($GRAALVM_HOME/bin/lli --print-toolchain-path --llvm.managed)
```

**Code snippet or code repository that reproduces the problem**
C code: exception.cpp:
```
#include <iostream>
#include <exception>

extern "C" {
int my_function() {
    std::cout << "[C++] My function" << "\n";
    throw 20;

    return 0;
}
}
```
Java:
```
import java.io.*;
import org.graalvm.polyglot.*;

class Tester {
    public static void main(String[] args) throws Exception {
        Context polyglot = Context.newBuilder().allowAllAccess(true).allowIO(true).option("llvm.managed", "true").build();
        File file = new File("exception.so");
        Source source = Source.newBuilder("llvm", file).build();
        Value cpart = polyglot.eval(source);
        cpart.invokeMember("my_function");

    }
}
```

**Steps to reproduce the problem**
Please include both build steps as well as run steps
1. $GRAALVM_MANAGED_LLVM_TOOLCHAIN/clang++ -fPIC -shared exception.cpp -lgraalvm-llvm -o exception.so
2. javac Tester.java && java Tester
 Output:
 ```
 [C++] My function
Exception in thread "main" Allocation of native memory is not possible in managed mode.
        at <llvm> my_function(exception.cpp:7:125)
        at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:932)
        at Tester.main(Tester.java:10)
```
        
**Expected behavior**

**Additional context**

**Comment by rschatz** [comment]
Fixed by @zslajchrt on the master branch.
