### ISSUE TITLE
Java 11 GraalVM 22.0.0.2 EE on Windows 10 pro 21H2 64bit fails the test "reactors (concurrency)" with NPE on renaissance suite

### ISSUE THREAD

**Issue by Ulibaer** [oracle/graal#4297]
On Windows 10 21H2 64bit with Java 11 GraalVM 22.0.0.2 **EE** the test "reactors (concurrency)" fails with NullPointerException on the **second** repetition:

(...snip...)
GC before operation: completed in 333.103 ms, heap usage 131.266 MB -> 111.873 MB.
====== finagle-http (web) [default], iteration 11 completed (4599.485 ms) ======
====== reactors (concurrency) [default], iteration 0 started ======
GC before operation: completed in 353.625 ms, heap usage 148.876 MB -> 113.411 MB.
Baseline workload: Reactor scheduling events
BigBench workload: Many-to-many message ping pong
CountingActor workload: Single reactor event processing
Fibonacci workload: Dynamic reactor mix with varying lifetimes
ForkJoinCreation workload: Reactor creation performance
ForkJoinThroughput workload: Reactor processing performance
PingPong workload: Reactor pair sequential ping pong performance
StreamingPingPong workload: Reactor pair overlapping ping pong performance
Roundabout workload: Many channels reactor performance
ThreadRing workload: Reactor ring forwarding performance
====== reactors (concurrency) [default], iteration 0 completed (36330.411 ms) ======
====== reactors (concurrency) [default], iteration 1 started ======
GC before operation: completed in 577.252 ms, heap usage 1.144 GB -> 116.293 MB.
Baseline workload: Reactor scheduling events
BigBench workload: Many-to-many message ping pong
CountingActor workload: Single reactor event processing
Fibonacci workload: Dynamic reactor mix with varying lifetimes
ForkJoinCreation workload: Reactor creation performance
ForkJoinThroughput workload: Reactor processing performance
PingPong workload: Reactor pair sequential ping pong performance
java.lang.NullPointerException
at io.reactors.package$LowPriorityChannelOps$.$bang$extension(package.scala:171)
at org.renaissance.actors.PingPong$PingPongInner$1.$anonfun$ping$3(Reactors.scala:413)
at org.renaissance.actors.PingPong$PingPongInner$1.$anonfun$ping$3$adapted(Reactors.scala:412)
at io.reactors.Events$OnEventOrDone.react(Events.scala:1665)
at io.reactors.Events$Push.reactAll(Events.scala:1275)
at io.reactors.Events$Push.reactAll$(Events.scala:1267)
at io.reactors.Events$Emitter.reactAll(Events.scala:1489)
at io.reactors.Events$Emitter.react(Events.scala:1494)
at io.reactors.EventQueue$UnrolledRing.dequeue(EventQueue.scala:116)
at io.reactors.Connector.dequeue(Connector.scala:61)
at io.reactors.concurrent.Frame.drain$1(Frame.scala:322)
at io.reactors.concurrent.Frame.processEvents(Frame.scala:345)
at io.reactors.concurrent.Frame.processBatch(Frame.scala:494)
at io.reactors.concurrent.Frame.isolateAndProcessBatch(Frame.scala:210)
at io.reactors.concurrent.Frame.executeBatch(Frame.scala:183)
at io.reactors.JvmScheduler$ReactorForkJoinWorkerThread.executeNow(JvmScheduler.scala:126)
at io.reactors.JvmScheduler$ReactorForkJoinWorkerThread.postschedule(JvmScheduler.scala:151)
at io.reactors.JvmScheduler$Executed.postschedule(JvmScheduler.scala:273)
at io.reactors.concurrent.Frame.executeBatch(Frame.scala:202)
at io.reactors.JvmScheduler$Executed$$anon$5.run(JvmScheduler.scala:255)
at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

This happens on two machines, one with Core2quad Q9550s with 8GB RAM and the second with i7-7500u and 20GB RAM. Both benchmarks were started with the following command line:
`java -XX:ActiveProcessorCount=2 -jar renaissance-gpl-0.14.0.jar --csv test.csv all`

On the same machines Java11 from Oracle, GraalVM 22.0.0.2 **CE**, OpenJDK SAPmachine11 and IBM Semeru Java 11 OpenJ9VM runs the complete testsuite just fine.

**Comment by fernando-valdez** [comment]
Hello @Ulibaer, thanks for reporting this issue. I will take care of it. 
If I have any questions I will let you know.

**Comment by Ulibaer** [comment]
Update:
**After installation of latest Windows updates**, i repeated the whole testsuite again and this time it ran through completely without NPE! So i think, it was a problem with Windows itself rather than a problem of GraalVM. Sorry for the confusion, but now the suite completes on both systems.

**Comment by fernando-valdez** [comment]
Thanks for sharing this update. 
I am glad that the problem got fixed. In case you find any other problem, please feel free to open a new issue. 
I am closing this one
