### ISSUE TITLE
[GR-36973] Improved diagnostic reporting on C exports not having an IsolateThread param.

### ISSUE THREAD

**Issue by gimbles** [oracle/graal#4319]
**Describe the issue**
I just did a clean GraalVM 17 Community edition install and tried to test run the GraalVM C exports API.

**Steps to reproduce the issue**
1. Make a basic Java app exporting a C function
2. Try to use native-image
3. Failure

**Describe GraalVM and your environment:**
![image](https://user-images.githubusercontent.com/93856041/153883663-749484d3-d1cd-49ec-89ac-61a050191cc3.png)
![image](https://user-images.githubusercontent.com/93856041/153883717-b175e67e-4b82-4577-8185-277c1c1723ef.png)

```
Executing [
/home/cookies/GraalVM/bin/java \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
--add-exports=java.base/com.sun.crypto.provider=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.access.foreign=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.event=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.loader=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.logger=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.misc=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.module=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.org.xml.sax.helpers=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.perf=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.platform=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.ref=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.reflect=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.util.xml.impl=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.util.xml=ALL-UNNAMED \
--add-exports=java.base/sun.invoke.util=ALL-UNNAMED \
--add-exports=java.base/sun.net=ALL-UNNAMED \
--add-exports=java.base/sun.nio.ch=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.annotation=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.reflectiveObjects=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.repository=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.tree=ALL-UNNAMED \
--add-exports=java.base/sun.security.jca=ALL-UNNAMED \
--add-exports=java.base/sun.security.provider=ALL-UNNAMED \
--add-exports=java.base/sun.security.ssl=ALL-UNNAMED \
--add-exports=java.base/sun.security.util=ALL-UNNAMED \
--add-exports=java.base/sun.text.spi=ALL-UNNAMED \
--add-exports=java.base/sun.util.calendar=ALL-UNNAMED \
--add-exports=java.base/sun.util.locale.provider=ALL-UNNAMED \
--add-exports=java.base/sun.util.resources=ALL-UNNAMED \
--add-exports=java.management/sun.management=ALL-UNNAMED \
--add-exports=java.xml.crypto/org.jcp.xml.dsig.internal.dom=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.site=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.stack=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.common=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.runtime=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.services=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.events=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal.consumer=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal.handlers=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal.jfc=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal=ALL-UNNAMED \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx6155862016 \
-Djava.awt.headless=true \
-Dorg.graalvm.version=22.0.0.2 \
-Dorg.graalvm.config=CE \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-javaagent:/home/cookies/GraalVM/lib/svm/builder/svm.jar \
-cp \
/home/cookies/GraalVM/lib/svm/builder/native-image-base.jar:/home/cookies/GraalVM/lib/svm/builder/pointsto.jar:/home/cookies/GraalVM/lib/svm/builder/svm.jar:/home/cookies/GraalVM/lib/svm/builder/objectfile.jar:/home/cookies/GraalVM/lib/svm/builder/llvm-wrapper-shadowed.jar:/home/cookies/GraalVM/lib/svm/builder/javacpp-shadowed.jar:/home/cookies/GraalVM/lib/svm/builder/svm-llvm.jar:/home/cookies/GraalVM/lib/svm/builder/llvm-platform-specific-shadowed.jar \
--module-path \
/home/cookies/GraalVM/lib/truffle/truffle-api.jar \
'com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus' \
-watchpid \
928414 \
-imagecp \
/home/cookies/Tmp:/home/cookies/GraalVM/lib/svm/library-support.jar \
-H:Path=/home/cookies/Tmp \
-H:+SharedLibrary \
-H:+DumpTargetInfo \
-H:CLibraryPath=/home/cookies/GraalVM/lib/svm/clibraries/linux-amd64 \
'-H:Class@explicit main-class=testing' \
'-H:Name@main-class lower case as image name=testing'
]
========================================================================================================================
GraalVM Native Image: Generating 'testing'...
========================================================================================================================
[1/7] Initializing...                                                                                    (3.6s @ 0.18GB)
 Version info: 'GraalVM 22.0.0.2 Java 17 CE'
# Printing compilation-target information to: /home/cookies/Tmp/reports/target_info_20220214_200545.txt
[2/7] Performing analysis...  []                                                                         (0.6s @ 0.10GB)
     525 (43.21%) of  1,215 classes reachable
     191 (27.76%) of    688 fields reachable
   1,217 (33.65%) of  3,617 methods reachable
      19 classes,     0 fields, and    19 methods registered for reflection

Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.oracle.svm.core.code.IsolateEnterStub.testing_x_3d8cf84778bed28002abd108d7a4f0493701ed9e()
Parsing context: <no parsing context available>

        at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:141)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:315)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureTypeFlowCreated(MethodTypeFlow.java:286)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
        at com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:461)
        at com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:195)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:179)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: com.oracle.svm.core.util.UserError$UserException: @CEntryPoint requires exactly one execution context parameter of type IsolateThread: testing.x()
        at com.oracle.svm.core.util.UserError.abort(UserError.java:73)
        at com.oracle.svm.hosted.code.CEntryPointCallStubMethod.generatePrologue(CEntryPointCallStubMethod.java:383)
        at com.oracle.svm.hosted.code.CEntryPointCallStubMethod.buildGraph(CEntryPointCallStubMethod.java:154)
        at com.oracle.graal.pointsto.meta.AnalysisMethod.buildGraph(AnalysisMethod.java:317)
        at com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:99)
        at com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:556)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:167)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:358)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:297)
        ... 11 more
------------------------------------------------------------------------------------------------------------------------
                         0.1s (2.4% of total time) in 7 GCs | Peak RSS: 0.68GB | CPU load: 5.27
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /home/cookies/Tmp/testing.build_artifacts.txt
========================================================================================================================
Failed generating 'testing' after 4.3s.
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1770)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1477)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1438)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1425)
```

## Steps tried to fix the issue
I have tried reinstalling GraalVM, even tried using the dev snapshot. Same issue.

**Comment by Yush08** [comment]
> Could you please share the Java sources you used? This seems to be the interesting line in the stack trace:
> 
> ```
> Caused by: com.oracle.svm.core.util.UserError$UserException: @CEntryPoint requires exactly one execution context parameter of type IsolateThread: testing.x()
> ```

@fniephaus 
```java
import org.graalvm.polyglot.*;
import org.graalvm.nativeimage.c.function.CEntryPoint;
import org.graalvm.nativeimage.IsolateThread;

class testing {
	@CEntryPoint(name = "x")
	public static void x() { System.out.println("Sup!"); }
	
	public static void main(String[] args) {}
}
```

**Comment by Yush08** [comment]
Oh! I noticed something -- I accidently forgot to add the IsolateThread parameter to the function

Isn't there a dedicated error message for this?

**Comment by Yush08** [comment]
(Btw, adding the parameter and compiling works OK. Just realized :P)

**Comment by christianwimmer** [comment]
As the error message says:

> @CEntryPoint requires exactly one execution context parameter of type IsolateThread: testing.x()

See the JavaDoc of `CEntryPoint`: https://github.com/oracle/graal/blob/master/sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/c/function/CEntryPoint.java#L84
