### ISSUE TITLE
Unable to build native image if using polyglot API and linking in GraalWasm

### ISSUE THREAD

**Issue by nirvdrum** [oracle/graal#4324]
**Describe the issue**

I was looking to embed GraalWasm in a native application. The application also uses the polyglot API in Java to expose a `@CEntryPoint` using TruffleRuby to implement the logic of the method. Before I even called into the `"wasm"` language I ran into issues building the native image.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. **git clone --depth 1 https://github.com/nirvdrum/native-image-wasm-issue**
2. **cd native-image-wasm-issue**
3. **mvn -P native-image -D skipTests=true package**

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **CE 22.0.02 & EE 22.0.0**
 - JDK major version: **17**
 - OS: **macOS 12.2.1**
 - Architecture: **AMD64 via Rosetta on Apple M1**

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
nirvdrum@Kevins-MacBook-Pro-2 ~/d/w/native-image-wasm-issue (main)> mvn -P native-image -D skipTests=true package
[INFO] Scanning for projects...
[INFO]
[INFO] ----------< com.shopify.truffleruby:native-image-playground >-----------
[INFO] Building native-image-playground 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ native-image-playground ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/nirvdrum/dev/workspaces/native-image-wasm-issue/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ native-image-playground ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ native-image-playground ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/nirvdrum/dev/workspaces/native-image-wasm-issue/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ native-image-playground ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ native-image-playground ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- native-maven-plugin:0.9.9:test (test-native) @ native-image-playground ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ native-image-playground ---
[INFO] Building jar: /Users/nirvdrum/dev/workspaces/native-image-wasm-issue/target/native-image-playground-1.0-SNAPSHOT.jar
[INFO]
[INFO] --- native-maven-plugin:0.9.9:build (build-native) @ native-image-playground ---
[WARNING] Ignoring non-jar type ImageClasspath Entry org.graalvm.nativeimage:library-support:maven-plugin:22.0.0:compile
[INFO] ImageClasspath Entry: org.graalvm.sdk:graal-sdk:jar:22.0.0:compile (file:///Users/nirvdrum/.m2/repository/org/graalvm/sdk/graal-sdk/22.0.0/graal-sdk-22.0.0.jar)
[WARNING] jar:file:///Users/nirvdrum/.m2/repository/org/graalvm/sdk/graal-sdk/22.0.0/graal-sdk-22.0.0.jar!/META-INF/native-image/org.graalvm.polyglot/native-image.properties does not match recommended META-INF/native-image/${groupId}/${artifactId}/native-image.properties layout.
[WARNING] jar:file:///Users/nirvdrum/.m2/repository/org/graalvm/sdk/graal-sdk/22.0.0/graal-sdk-22.0.0.jar!/META-INF/native-image/org.graalvm.home/native-image.properties does not match recommended META-INF/native-image/${groupId}/${artifactId}/native-image.properties layout.
[INFO] ImageClasspath Entry: org.graalvm.nativeimage:svm:jar:22.0.0:compile (file:///Users/nirvdrum/.m2/repository/org/graalvm/nativeimage/svm/22.0.0/svm-22.0.0.jar)
[INFO] ImageClasspath Entry: org.graalvm.nativeimage:objectfile:jar:22.0.0:compile (file:///Users/nirvdrum/.m2/repository/org/graalvm/nativeimage/objectfile/22.0.0/objectfile-22.0.0.jar)
[INFO] ImageClasspath Entry: org.graalvm.nativeimage:pointsto:jar:22.0.0:compile (file:///Users/nirvdrum/.m2/repository/org/graalvm/nativeimage/pointsto/22.0.0/pointsto-22.0.0.jar)
[INFO] ImageClasspath Entry: org.graalvm.compiler:compiler:jar:22.0.0:compile (file:///Users/nirvdrum/.m2/repository/org/graalvm/compiler/compiler/22.0.0/compiler-22.0.0.jar)
[INFO] ImageClasspath Entry: org.graalvm.truffle:truffle-api:jar:22.0.0:compile (file:///Users/nirvdrum/.m2/repository/org/graalvm/truffle/truffle-api/22.0.0/truffle-api-22.0.0.jar)
[INFO] ImageClasspath Entry: org.graalvm.nativeimage:native-image-base:jar:22.0.0:compile (file:///Users/nirvdrum/.m2/repository/org/graalvm/nativeimage/native-image-base/22.0.0/native-image-base-22.0.0.jar)
[INFO] ImageClasspath Entry: org.apache.sis.core:sis-referencing:jar:1.0:compile (file:///Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-referencing/1.0/sis-referencing-1.0.jar)
[INFO] ImageClasspath Entry: org.apache.sis.core:sis-utility:jar:1.0:compile (file:///Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-utility/1.0/sis-utility-1.0.jar)
[INFO] ImageClasspath Entry: org.apache.sis.core:sis-metadata:jar:1.0:compile (file:///Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-metadata/1.0/sis-metadata-1.0.jar)
[INFO] ImageClasspath Entry: javax.measure:unit-api:jar:1.0:compile (file:///Users/nirvdrum/.m2/repository/javax/measure/unit-api/1.0/unit-api-1.0.jar)
[INFO] ImageClasspath Entry: org.opengis:geoapi:jar:3.0.1:compile (file:///Users/nirvdrum/.m2/repository/org/opengis/geoapi/3.0.1/geoapi-3.0.1.jar)
[INFO] ImageClasspath Entry: com.shopify.truffleruby:native-image-playground:jar:1.0-SNAPSHOT (file:///Users/nirvdrum/dev/workspaces/native-image-wasm-issue/target/native-image-playground-1.0-SNAPSHOT.jar)
[INFO] Executing: /Users/nirvdrum/.sdkman/candidates/java/current/bin/native-image -cp /Users/nirvdrum/.m2/repository/org/graalvm/sdk/graal-sdk/22.0.0/graal-sdk-22.0.0.jar:/Users/nirvdrum/.m2/repository/org/graalvm/nativeimage/svm/22.0.0/svm-22.0.0.jar:/Users/nirvdrum/.m2/repository/org/graalvm/nativeimage/objectfile/22.0.0/objectfile-22.0.0.jar:/Users/nirvdrum/.m2/repository/org/graalvm/nativeimage/pointsto/22.0.0/pointsto-22.0.0.jar:/Users/nirvdrum/.m2/repository/org/graalvm/compiler/compiler/22.0.0/compiler-22.0.0.jar:/Users/nirvdrum/.m2/repository/org/graalvm/truffle/truffle-api/22.0.0/truffle-api-22.0.0.jar:/Users/nirvdrum/.m2/repository/org/graalvm/nativeimage/native-image-base/22.0.0/native-image-base-22.0.0.jar:/Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-referencing/1.0/sis-referencing-1.0.jar:/Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-utility/1.0/sis-utility-1.0.jar:/Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-metadata/1.0/sis-metadata-1.0.jar:/Users/nirvdrum/.m2/repository/javax/measure/unit-api/1.0/unit-api-1.0.jar:/Users/nirvdrum/.m2/repository/org/opengis/geoapi/3.0.1/geoapi-3.0.1.jar:/Users/nirvdrum/dev/workspaces/native-image-wasm-issue/target/native-image-playground-1.0-SNAPSHOT.jar --language:js --language:wasm --native-image-info --verbose -H:Class=com.shopify.truffleruby.NativeImage -H:Name=native-image-playground
Executing [
/Users/nirvdrum/.sdkman/candidates/java/22.0.0.2.r17-grl/bin/java \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
--add-exports=java.base/com.sun.crypto.provider=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.access.foreign=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.event=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.loader=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.logger=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.misc=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.module=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.org.xml.sax.helpers=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.perf=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.platform=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.ref=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.reflect=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.util.xml.impl=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.util.xml=ALL-UNNAMED \
--add-exports=java.base/sun.invoke.util=ALL-UNNAMED \
--add-exports=java.base/sun.net=ALL-UNNAMED \
--add-exports=java.base/sun.nio.ch=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.annotation=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.reflectiveObjects=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.repository=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.tree=ALL-UNNAMED \
--add-exports=java.base/sun.security.jca=ALL-UNNAMED \
--add-exports=java.base/sun.security.provider=ALL-UNNAMED \
--add-exports=java.base/sun.security.ssl=ALL-UNNAMED \
--add-exports=java.base/sun.security.util=ALL-UNNAMED \
--add-exports=java.base/sun.text.spi=ALL-UNNAMED \
--add-exports=java.base/sun.util.calendar=ALL-UNNAMED \
--add-exports=java.base/sun.util.locale.provider=ALL-UNNAMED \
--add-exports=java.base/sun.util.resources=ALL-UNNAMED \
--add-exports=java.management/sun.management=ALL-UNNAMED \
--add-exports=java.xml.crypto/org.jcp.xml.dsig.internal.dom=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.site=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.stack=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.common=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.runtime=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.services=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.events=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal.consumer=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal.handlers=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal.jfc=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal=ALL-UNNAMED \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Djava.awt.headless=true \
-Dorg.graalvm.version=22.0.0.2 \
-Dorg.graalvm.config=CE \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
-Dtruffle.TruffleRuntime=com.oracle.svm.truffle.api.SubstrateTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=false \
-Dpolyglot.image-build-time.PreinitializeContexts=js \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-Xmx13743895344 \
-javaagent:/Users/nirvdrum/.sdkman/candidates/java/22.0.0.2.r17-grl/lib/svm/builder/svm.jar \
-cp \
/Users/nirvdrum/.sdkman/candidates/java/22.0.0.2.r17-grl/lib/svm/builder/llvm-wrapper-shadowed.jar:/Users/nirvdrum/.sdkman/candidates/java/22.0.0.2.r17-grl/lib/svm/builder/svm.jar:/Users/nirvdrum/.sdkman/candidates/java/22.0.0.2.r17-grl/lib/svm/builder/native-image-base.jar:/Users/nirvdrum/.sdkman/candidates/java/22.0.0.2.r17-grl/lib/svm/builder/objectfile.jar:/Users/nirvdrum/.sdkman/candidates/java/22.0.0.2.r17-grl/lib/svm/builder/llvm-platform-specific-shadowed.jar:/Users/nirvdrum/.sdkman/candidates/java/22.0.0.2.r17-grl/lib/svm/builder/javacpp-shadowed.jar:/Users/nirvdrum/.sdkman/candidates/java/22.0.0.2.r17-grl/lib/svm/builder/svm-llvm.jar:/Users/nirvdrum/.sdkman/candidates/java/22.0.0.2.r17-grl/lib/svm/builder/pointsto.jar \
--module-path \
/Users/nirvdrum/.sdkman/candidates/java/22.0.0.2.r17-grl/lib/truffle/truffle-api.jar \
'com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus' \
-imagecp \
/Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-referencing/1.0/sis-utility-1.0.jar:/Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-referencing/1.0/sis-metadata-1.0.jar:/Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-referencing/1.0/unit-api-1.0.jar:/Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-referencing/1.0/geoapi-3.0.1.jar:/Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-utility/1.0/unit-api-1.0.jar:/Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-utility/1.0/geoapi-3.0.1.jar:/Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-metadata/1.0/sis-utility-1.0.jar:/Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-metadata/1.0/unit-api-1.0.jar:/Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-metadata/1.0/geoapi-3.0.1.jar:/Users/nirvdrum/.m2/repository/org/opengis/geoapi/3.0.1/unit-api-1.0.jar:/Users/nirvdrum/.sdkman/candidates/java/22.0.0.2.r17-grl/languages/regex/tregex.jar:/Users/nirvdrum/.sdkman/candidates/java/22.0.0.2.r17-grl/languages/js/graaljs.jar:/Users/nirvdrum/.sdkman/candidates/java/22.0.0.2.r17-grl/languages/wasm/wasm.jar:/Users/nirvdrum/.m2/repository/org/graalvm/sdk/graal-sdk/22.0.0/graal-sdk-22.0.0.jar:/Users/nirvdrum/.m2/repository/org/graalvm/nativeimage/svm/22.0.0/svm-22.0.0.jar:/Users/nirvdrum/.m2/repository/org/graalvm/nativeimage/objectfile/22.0.0/objectfile-22.0.0.jar:/Users/nirvdrum/.m2/repository/org/graalvm/nativeimage/pointsto/22.0.0/pointsto-22.0.0.jar:/Users/nirvdrum/.m2/repository/org/graalvm/compiler/compiler/22.0.0/compiler-22.0.0.jar:/Users/nirvdrum/.m2/repository/org/graalvm/truffle/truffle-api/22.0.0/truffle-api-22.0.0.jar:/Users/nirvdrum/.m2/repository/org/graalvm/nativeimage/native-image-base/22.0.0/native-image-base-22.0.0.jar:/Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-referencing/1.0/sis-referencing-1.0.jar:/Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-utility/1.0/sis-utility-1.0.jar:/Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-metadata/1.0/sis-metadata-1.0.jar:/Users/nirvdrum/.m2/repository/javax/measure/unit-api/1.0/unit-api-1.0.jar:/Users/nirvdrum/.m2/repository/org/opengis/geoapi/3.0.1/geoapi-3.0.1.jar:/Users/nirvdrum/dev/workspaces/native-image-wasm-issue/target/native-image-playground-1.0-SNAPSHOT.jar:/Users/nirvdrum/.sdkman/candidates/java/22.0.0.2.r17-grl/lib/svm/library-support.jar \
-H:Path=/Users/nirvdrum/dev/workspaces/native-image-wasm-issue/target \
'-H:ClassInitialization@jar:file:///Users/nirvdrum/.m2/repository/org/graalvm/sdk/graal-sdk/22.0.0/graal-sdk-22.0.0.jar!/META-INF/native-image/org.graalvm.polyglot/native-image.properties=org.graalvm.polyglot:build_time' \
'-H:Features@jar:file:///Users/nirvdrum/.m2/repository/org/graalvm/sdk/graal-sdk/22.0.0/graal-sdk-22.0.0.jar!/META-INF/native-image/org.graalvm.home/native-image.properties=org.graalvm.home.HomeFinderFeature' \
-H:Features@--macro:truffle=com.oracle.svm.truffle.TruffleFeature,com.oracle.svm.truffle.TruffleBaseFeature,org.graalvm.home.HomeFinderFeature \
-H:MaxRuntimeCompileMethods@--macro:truffle=2000 \
-H:ClassInitialization@--macro:truffle=org.graalvm.launcher:build_time,com.oracle.truffle:build_time,org.graalvm.nativebridge:build_time \
-H:MaxRuntimeCompileMethods@--language:regex=900 \
-H:MaxRuntimeCompileMethods@--language:js=9200 \
-H:ClassInitialization@--language:js=com.oracle.truffle.js:build_time,com.oracle.js.parser:build_time,com.oracle.truffle.regex:build_time \
-H:ClassInitialization@--language:js=com.ibm.icu:run_time \
-H:ReflectionConfigurationResources@--language:js=com/oracle/truffle/js/runtime/resources/reflect-config.json \
-H:ResourceConfigurationResources@--language:js=com/oracle/truffle/js/runtime/resources/resource-config.json \
-H:MaxRuntimeCompileMethods@--language:wasm=2000 \
-H:+DumpTargetInfo \
-H:Class=com.shopify.truffleruby.NativeImage \
-H:Name=native-image-playground \
-H:FallbackThreshold=0 \
-H:CLibraryPath=/Users/nirvdrum/.sdkman/candidates/java/22.0.0.2.r17-grl/lib/svm/clibraries/darwin-amd64
]
========================================================================================================================
GraalVM Native Image: Generating 'native-image-playground'...
========================================================================================================================
[1/7] Initializing...                                                                                   (10.0s @ 0.20GB)
 Version info: 'GraalVM 22.0.0.2 Java 17 CE'
# Printing compilation-target information to: /Users/nirvdrum/dev/workspaces/native-image-wasm-issue/target/reports/target_info_20220214_182434.txt
[2/7] Performing analysis...  []                                                                         (3.5s @ 0.15GB)
     995 (58.91%) of  1,689 classes reachable
     263 (19.06%) of  1,380 fields reachable
   1,199 (24.12%) of  4,970 methods reachable
      41 classes,     5 fields, and    30 methods registered for reflection

Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.oracle.svm.core.code.IsolateEnterStub.NativeImage_getNumber_89ede0744493a9536dd51fe59beb33ef9974aadc()
Parsing context: <no parsing context available>

	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:141)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:315)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureTypeFlowCreated(MethodTypeFlow.java:286)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:461)
	at com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:195)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:179)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: com.oracle.svm.core.util.UserError$UserException: @CEntryPoint requires exactly one execution context parameter of type IsolateThread: com.shopify.truffleruby.NativeImage.getNumber()
	at com.oracle.svm.core.util.UserError.abort(UserError.java:73)
	at com.oracle.svm.hosted.code.CEntryPointCallStubMethod.generatePrologue(CEntryPointCallStubMethod.java:383)
	at com.oracle.svm.hosted.code.CEntryPointCallStubMethod.buildGraph(CEntryPointCallStubMethod.java:154)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.buildGraph(AnalysisMethod.java:317)
	at com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:99)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:556)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:167)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:358)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:297)
	... 11 more
------------------------------------------------------------------------------------------------------------------------
                         0.3s (1.5% of total time) in 9 GCs | Peak RSS: 0.79GB | CPU load: 2.10
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /Users/nirvdrum/dev/workspaces/native-image-wasm-issue/target/native-image-playground.build_artifacts.txt
========================================================================================================================
Failed generating 'native-image-playground' after 15.4s.
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1770)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1477)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1438)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1425)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  20.094 s
[INFO] Finished at: 2022-02-14T18:24:39-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.9:build (build-native) on project native-image-playground: Execution of /Users/nirvdrum/.sdkman/candidates/java/current/bin/native-image -cp /Users/nirvdrum/.m2/repository/org/graalvm/sdk/graal-sdk/22.0.0/graal-sdk-22.0.0.jar:/Users/nirvdrum/.m2/repository/org/graalvm/nativeimage/svm/22.0.0/svm-22.0.0.jar:/Users/nirvdrum/.m2/repository/org/graalvm/nativeimage/objectfile/22.0.0/objectfile-22.0.0.jar:/Users/nirvdrum/.m2/repository/org/graalvm/nativeimage/pointsto/22.0.0/pointsto-22.0.0.jar:/Users/nirvdrum/.m2/repository/org/graalvm/compiler/compiler/22.0.0/compiler-22.0.0.jar:/Users/nirvdrum/.m2/repository/org/graalvm/truffle/truffle-api/22.0.0/truffle-api-22.0.0.jar:/Users/nirvdrum/.m2/repository/org/graalvm/nativeimage/native-image-base/22.0.0/native-image-base-22.0.0.jar:/Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-referencing/1.0/sis-referencing-1.0.jar:/Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-utility/1.0/sis-utility-1.0.jar:/Users/nirvdrum/.m2/repository/org/apache/sis/core/sis-metadata/1.0/sis-metadata-1.0.jar:/Users/nirvdrum/.m2/repository/javax/measure/unit-api/1.0/unit-api-1.0.jar:/Users/nirvdrum/.m2/repository/org/opengis/geoapi/3.0.1/geoapi-3.0.1.jar:/Users/nirvdrum/dev/workspaces/native-image-wasm-issue/target/native-image-playground-1.0-SNAPSHOT.jar --language:js --language:wasm --native-image-info --verbose -H:Class=com.shopify.truffleruby.NativeImage -H:Name=native-image-playground returned non-zero result -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by Yush08** [comment]
Take a look at #4319 

Did you add an IsolateThread parameter to functions you're exporting through CEntryPoint?
Eg. 
```java
import org.graalvm.polyglot.*;
import org.graalvm.nativeimage.c.function.CEntryPoint;
import org.graalvm.nativeimage.IsolateThread;

class testing {
	@CEntryPoint(name = "x")
	public static void x(IsolateThread thread) { System.out.println("Hello, World!"); }
	
	public static void main(String[] args) {}
}
```

**Comment by Yush08** [comment]
![image](https://user-images.githubusercontent.com/93856041/153990504-dd26de3a-bd3a-469a-b984-1da5b42dbc87.png)
Yes by the code -- it does look like that the lack of the IsolateThread parameter is causing the error.

There should be a dedicated error message added (again?) to Native image with #4322

**Comment by nirvdrum** [comment]
@Yush08 Thanks for catching that. I indeed forgot the `IsolateThread` in this reproduction. But, I'm seeing the issue with a larger project that works just fine before adding the `--language:wasm`. I've fixed the missing parameter issue and updated the log message in the issue description.
