### ISSUE TITLE
[GR-36974] LLVM back-end failing with image builder on module path

### ISSUE THREAD

**Issue by koutheir** [oracle/graal#4336]
Running the following command:

```bash
$ mx native-image -H:CompilerBackend=llvm --macro:native-image-launcher
```

produces the following error:
```
Fatal error: java.lang.IllegalAccessError: class com.oracle.svm.core.graal.llvm.LLVMFeature (in module org.graalvm.nativeimage.llvm) cannot access class jdk.vm.ci.meta.MetaAccessProvider (in module jdk.internal.vm.ci) because module jdk.internal.vm.ci does not export jdk.vm.ci.meta to module org.graalvm.nativeimage.llvm
	at org.graalvm.nativeimage.llvm/com.oracle.svm.core.graal.llvm.LLVMFeature.afterRegistration(LLVMFeature.java:99)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$14(NativeImageGenerator.java:828)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:74)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:828)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:552)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:512)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:423)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:598)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
```

This issue also happens on the enterprise edition, and it is a blocker for us.

**Comment by olpaw** [comment]
Currently whenever you use `-H:CompilerBackend=llvm` and you build an image on the module path (like the native-image-launcher image above) the image-builder itself will run on the module path. This causes strict checking of module accessibility rules and will fail since the llvm related modules haven't beep properly modularized yet.

The workaround for now is to always build your images on the classpath. To force building GraalVM components like
* native-image-diagnostics-agent-library
* native-image-agent-library
* native-image-configure-launcher
* native-image-launcher

on the classpath you have to adjust `graal/substratevm/mx.substratevm/mx_substratevm.py` and set all place where you see `use_modules='image' if not svm_java8() else None` to `use_modules=None`.

**Comment by olpaw** [comment]
Fixed by https://github.com/oracle/graal/pull/4422

This will also be backported to the 22.1 branch
