### ISSUE TITLE
[bug report] multiple errors in scala/sbt/js project

### ISSUE THREAD

**Issue by jstriebel** [oracle/graal#435]
I am trying to move the build process of the `scala/sbt/js` based project webknossos to GraalVM (scalableminds/webknossos#2647).

The compilation of the project works fine, but `sbt stage` (which involves js (e.g. webpack builds)) takes very long (> 50min, with OpenJDK/NodeJS ~3min) and has several errors, which can be seen in the [CI output](https://circleci.com/gh/scalableminds/webknossos/3737). A reduced version is appended below.

The CI uses a docker image which is built within this PR: scalableminds/dockerfiles#3
The GraalVM version is `ce-1.0.0-rc1`.

I am not sure if I am missing something or those are bugs within graalvm/truffle. Are these issues known already? Any help in resolving those errors would be highly appreciated.

Thanks a lot!

```
[error] [truffle] opt fail         SortableSet <split-74ed4678>                                |Reason org.graalvm.compiler.code.SourceStackTraceBailoutException$1: Partial evaluation did not reduce value to a constant, is a regular compiler node: 2170|Pi 
[error] org.graalvm.compiler.code.SourceStackTraceBailoutException$1: Partial evaluation did not reduce value to a constant, is a regular compiler node: 2170|Pi
[error] Caused by: org.graalvm.compiler.core.common.PermanentBailoutException: Partial evaluation did not reduce value to a constant, is a regular compiler node: 2170|Pi
[error] 	at java.lang.Throwable.<init>(Throwable.java:265)
[error] 	at java.lang.Exception.<init>(Exception.java:66)
[error] 	at java.lang.RuntimeException.<init>(RuntimeException.java:62)
[error] 	at jdk.vm.ci.code.BailoutException.<init>(BailoutException.java:66)
[error] 	at org.graalvm.compiler.core.common.PermanentBailoutException.<init>(PermanentBailoutException.java:36)
[error] 	at org.graalvm.compiler.replacements.PEGraphDecoder$PENonAppendGraphBuilderContext.bailout(PEGraphDecoder.java:242)
[error] 	at org.graalvm.compiler.truffle.compiler.substitutions.TruffleGraphBuilderPlugins$19.apply(TruffleGraphBuilderPlugins.java:366)
[error] 	at org.graalvm.compiler.nodes.graphbuilderconf.InvocationPlugin.execute(InvocationPlugin.java:196)
…
[error] 	at org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime$1.run(GraalTruffleRuntime.java:745)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] 	at org.graalvm.compiler.core.CompilerThread.run(CompilerThread.java:40)
[error] 	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:222)
[error] 	at Lcom/oracle/svm/core/code/CEntryPointCallStubs;.com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_002epthreadStartRoutine_0028com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_0024ThreadStartData_0029(generated:0)
```

```
[error] [truffle] opt fail         :anonymous                                                  |Reason java.lang.ArrayIndexOutOfBoundsException 
[error] Dumping debug output in /home/circleci/webknossos/dumps/1527524793177
[error] Thread[TruffleCompilerThread-198,10,main]: Compilation of :anonymous failed: java.lang.ArrayIndexOutOfBoundsException
[error] 	at java.lang.Throwable.<init>(Throwable.java:250)
[error] 	at java.lang.Exception.<init>(Exception.java:54)
[error] 	at java.lang.RuntimeException.<init>(RuntimeException.java:51)
[error] 	at java.lang.IndexOutOfBoundsException.<init>(IndexOutOfBoundsException.java:46)
[error] 	at java.lang.ArrayIndexOutOfBoundsException.<init>(ArrayIndexOutOfBoundsException.java:45)
[error] 	at com.oracle.svm.core.snippets.SnippetRuntime.throwArrayIndexOutOfBoundsException(SnippetRuntime.java:230)
[error] 	at org.graalvm.compiler.graph.NodeClass$RawEdgesIterator.next(NodeClass.java:966)
[error] 	at org.graalvm.compiler.phases.schedule.SchedulePhase$Instance.processInputs(SchedulePhase.java:1128)
…
[error] 	at org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime$1.run(GraalTruffleRuntime.java:745)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] 	at org.graalvm.compiler.core.CompilerThread.run(CompilerThread.java:40)
[error] 	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:222)
[error] 	at Lcom/oracle/svm/core/code/CEntryPointCallStubs;.com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_002epthreadStartRoutine_0028com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_0024ThreadStartData_0029(generated:0)
```

```
[error] VMError.shouldNotReachHere: VMError.shouldNotReachHere: com.oracle.svm.core.genscavenge.HeapChunkProvider$AllocatorOutOfMemoryError: null
[error] 
[error] JavaFrameAnchor dump:
[error] 
[error]   Anchor 00007f78b4840b38 LastJavaSP 00007f78b4840ad0
[error]   
[error] DeoptStubPointer address: 00007f78a8bd55d0
[error] 
[error] TopFrame info:
[error] 
[error]   Lookup TotalFrameSize in CodeInfoTable:
[error]   SourceTotalFrameSize 48
[error]   
[error] VMThreads info:
…
```

```
…
[error]   RSP 00007f78b4841a40 RIP 00007f78a8e1f1c4  com.oracle.svm.core.code.ImageCodeInfo@0x7f78ac4c3d70 name = image code
[error]   RSP 00007fa9c69f3120 RIP 00007fa9bb355ae9  [image code] com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:217)RSP 00007f78b4841a80 RIP 00007f78a8e212eb  com.oracle.svm.core.code.ImageCodeInfo@0x7f78ac4c3d70 name = image code
[error]   
[error]   RSP 00007f78b4841ab0 RIP 00007f78a8e2e4d7  com.oracle.svm.core.code.ImageCodeInfo@0x7f78ac4c3d70 name = image code
[error]   RSP 00007f78b4841b10 RIP 00007f78aa32b0e7  RSP 
java.lang.Error: Running webpack failed with exit code: 99
	at AssetCompilation$$anonfun$assetsGenerationTask$1.apply(AssetCompilation.scala:80)
	at AssetCompilation$$anonfun$assetsGenerationTask$1.apply(AssetCompilation.scala:67)
	at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:35)
	at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dougxc** [comment]
Thanks for the report @jstriebel. Two things that may help diagnosing this:
* Set `-Dgraal.TruffleCompilationExceptionsAreFatal=true`
* Make the dump files (i.e. those mention in [messages](https://circleci.com/gh/scalableminds/webknossos/3737?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) like `Dumping debug output in /home/circleci/webknossos/dumps/1527524793177`) available for download somehow.

**Comment by dougxc** [comment]
@wirthi can you please assign someone from the GraalJS team to investigate this.

**Comment by jstriebel** [comment]
PS: Please feel free to correct the title to something more useful for you.

**Comment by jstriebel** [comment]
Hi Christian,

our current quick fix is to simply use nodejs and give it precedence in the PATH.

To reproduce the problem, checkout commit [`1df1d00a9a88c996ff12c3c034ed646f5fb4c2bf` of `scalableminds/webknossos`](https://github.com/scalableminds/webknossos/pull/2647/commits/1df1d00a9a88c996ff12c3c034ed646f5fb4c2bf) and simply follow the [steps of the CI](https://circleci.com/gh/scalableminds/webknossos/3777). This should be enough:
* `docker-compose run base yarn install --frozen-lockfile`
* `docker-compose run base yarn run docs`
* `docker-compose run compile bash -c 'SBT_OPTS="$SBT_OPTS -Dgraal.TruffleCompilationExceptionsAreFatal=true" sbt -v compile stage'`
* `docker-compose run base yarn test-verbose`
