### ISSUE TITLE
[LLVM] exception when std::call_once is used 

### ISSUE THREAD

**Issue by roxanan-adyen** [oracle/graal#4353]
**Describe GraalVM and your environment :**
 - GraalVM version: **22.0.0**
 - **EE**
 - JDK version: **JDK11**
 - OS and OS Version: **macOS bigSur**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
 **Java HotSpot(TM) 64-Bit Server VM (11.0.14+8-LTS-jvmci-22.0-b03) for bsd-amd64 JRE (11.0.14+8-LTS-jvmci-22.0-b03), built on Jan  2 2022 15:02:19 by "graal1" with gcc 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)**
```

**Have you verified this issue still happens when using the latest snapshot?**
Only tried it with 22.0.0

**Describe the issue**
I have a small C++ program where I try to use std::call_once. This is built as a library that is loaded by a java app. In the java app, I create two threads that will execute the C++ function. This is the error I get:
```
Java tid 21
Java tid 20
Happens once
Exception 20
org.graalvm.polyglot.PolyglotException: java.lang.IllegalMonitorStateException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.signalAll(AbstractQueuedSynchronizer.java:1996)
	at com.oracle.truffle.llvm.managed.nodes.intrinsics.multithreading.LLVMManagedPThreadCondIntrinsics$Cond.broadcast(LLVMManagedPThreadCondIntrinsics.java:60)
	at com.oracle.truffle.llvm.managed.nodes.intrinsics.multithreading.LLVMManagedPThreadCondIntrinsics$LLVMPThreadCondBroadcast.doIntrinsic(LLVMManagedPThreadCondIntrinsics.java:112)
	at com.oracle.truffle.llvm.managed.nodes.intrinsics.multithreading.LLVMManagedPThreadCondIntrinsicsFactory$LLVMPThreadCondBroadcastNodeGen.executeI32(LLVMManagedPThreadCondIntrinsicsFactory.java:278)
	at com.oracle.truffle.llvm.runtime.nodes.api.LLVMFrameNullerExpression.executeI32(LLVMFrameNullerExpression.java:116)
	at com.oracle.truffle.llvm.runtime.nodes.vars.LLVMWriteNodeFactory$LLVMWriteI32NodeGen.execute(LLVMWriteNodeFactory.java:364)
	at com.oracle.truffle.llvm.runtime.nodes.base.LLVMBasicBlockNode$InitializedBlockNode.execute(LLVMBasicBlockNode.java:172)
	at com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNode.doDispatch(LLVMDispatchBasicBlockNode.java:99)
	at com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNodeGen.executeGeneric(LLVMDispatchBasicBlockNodeGen.java:23)
	at com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNode.doRun(LLVMFunctionRootNode.java:81)
	at com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNodeGen.executeGeneric(LLVMFunctionRootNodeGen.java:25)
	at com.oracle.truffle.llvm.runtime.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:93)
	at <llvm> call_once<(lambda at call_once.cpp:26:23)>(../graalvm-ee-java11-22.0.0/Contents/Home/languages/llvm/managed/include/c++/v1/mutex:675:16788)
	at <llvm> call_once(<unavailable>:1:0)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:932)
	at Java2Threads.thread_function(Java2Threads.java:11)
	at Java2Threads.lambda$main$0(Java2Threads.java:33)
	at java.base/java.lang.Thread.run(Thread.java:834)
Original Internal Error: 
java.lang.IllegalMonitorStateException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.signalAll(AbstractQueuedSynchronizer.java:1996)
	at com.oracle.truffle.llvm.managed.nodes.intrinsics.multithreading.LLVMManagedPThreadCondIntrinsics$Cond.broadcast(LLVMManagedPThreadCondIntrinsics.java:60)
	at com.oracle.truffle.llvm.managed.nodes.intrinsics.multithreading.LLVMManagedPThreadCondIntrinsics$LLVMPThreadCondBroadcast.doIntrinsic(LLVMManagedPThreadCondIntrinsics.java:112)
	at com.oracle.truffle.llvm.managed.nodes.intrinsics.multithreading.LLVMManagedPThreadCondIntrinsicsFactory$LLVMPThreadCondBroadcastNodeGen.executeI32(LLVMManagedPThreadCondIntrinsicsFactory.java:278)
	at com.oracle.truffle.llvm.runtime.nodes.api.LLVMFrameNullerExpression.executeI32(LLVMFrameNullerExpression.java:116)
	at com.oracle.truffle.llvm.runtime.nodes.vars.LLVMWriteNodeFactory$LLVMWriteI32NodeGen.execute(LLVMWriteNodeFactory.java:364)
	at com.oracle.truffle.llvm.runtime.nodes.base.LLVMBasicBlockNode$InitializedBlockNode.execute(LLVMBasicBlockNode.java:172)
	at com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNode.doDispatch(LLVMDispatchBasicBlockNode.java:99)
	at com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNodeGen.executeGeneric(LLVMDispatchBasicBlockNodeGen.java:23)
	at com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNode.doRun(LLVMFunctionRootNode.java:81)
	at com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNodeGen.executeGeneric(LLVMFunctionRootNodeGen.java:25)
	at com.oracle.truffle.llvm.runtime.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:93)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:655)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:627)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:560)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:544)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:486)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:71)
	at com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNode.doDirectCodeFast(LLVMDispatchNode.java:165)
	at com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNodeGen.executeDispatch(LLVMDispatchNodeGen.java:87)
	at com.oracle.truffle.llvm.runtime.nodes.func.LLVMInvokeNode$LLVMInvokeNodeImpl.doInvoke(LLVMInvokeNode.java:109)
	at com.oracle.truffle.llvm.runtime.nodes.func.LLVMInvokeNodeFactory$LLVMInvokeNodeImplNodeGen.execute(LLVMInvokeNodeFactory.java:33)
	at com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNode.doDispatch(LLVMDispatchBasicBlockNode.java:223)
	at com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNodeGen.executeGeneric(LLVMDispatchBasicBlockNodeGen.java:23)
	at com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNode.doRun(LLVMFunctionRootNode.java:81)
	at com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNodeGen.executeGeneric(LLVMFunctionRootNodeGen.java:25)
	at com.oracle.truffle.llvm.runtime.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:93)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:655)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:627)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:560)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:544)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:486)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:71)
	at com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNode.doDirectCodeFast(LLVMDispatchNode.java:165)
	at com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNodeGen.executeAndSpecialize(LLVMDispatchNodeGen.java:255)
	at com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNodeGen.executeDispatch(LLVMDispatchNodeGen.java:214)
	at com.oracle.truffle.llvm.runtime.nodes.func.LLVMCallNode.doCall(LLVMCallNode.java:82)
	at com.oracle.truffle.llvm.runtime.nodes.func.LLVMCallNodeGen.executeGeneric(LLVMCallNodeGen.java:28)
	at com.oracle.truffle.llvm.runtime.nodes.api.LLVMVoidStatementNodeGen.execute(LLVMVoidStatementNodeGen.java:22)
	at com.oracle.truffle.llvm.runtime.nodes.base.LLVMBasicBlockNode$InitializedBlockNode.execute(LLVMBasicBlockNode.java:172)
	at com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNode.doDispatch(LLVMDispatchBasicBlockNode.java:99)
	at com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNodeGen.executeGeneric(LLVMDispatchBasicBlockNodeGen.java:23)
	at com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNode.doRun(LLVMFunctionRootNode.java:81)
	at com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNodeGen.executeGeneric(LLVMFunctionRootNodeGen.java:25)
	at com.oracle.truffle.llvm.runtime.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:93)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:655)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:627)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:560)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:544)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:486)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:71)
	at com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNode.doDirectCodeFast(LLVMDispatchNode.java:165)
	at com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNodeGen.executeAndSpecialize(LLVMDispatchNodeGen.java:255)
	at com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNodeGen.executeDispatch(LLVMDispatchNodeGen.java:214)
	at com.oracle.truffle.llvm.runtime.nodes.func.LLVMCallNode.doCall(LLVMCallNode.java:82)
	at com.oracle.truffle.llvm.runtime.nodes.func.LLVMCallNodeGen.executeGeneric(LLVMCallNodeGen.java:28)
	at com.oracle.truffle.llvm.runtime.nodes.api.LLVMVoidStatementNodeGen.execute(LLVMVoidStatementNodeGen.java:22)
	at com.oracle.truffle.llvm.runtime.nodes.api.LLVMFrameNuller.doExecute(LLVMFrameNuller.java:64)
	at com.oracle.truffle.llvm.runtime.nodes.api.LLVMFrameNullerNodeGen.execute(LLVMFrameNullerNodeGen.java:20)
	at com.oracle.truffle.llvm.runtime.nodes.base.LLVMBasicBlockNode$InitializedBlockNode.execute(LLVMBasicBlockNode.java:172)
	at com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNode.doDispatch(LLVMDispatchBasicBlockNode.java:99)
	at com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNodeGen.executeGeneric(LLVMDispatchBasicBlockNodeGen.java:23)
	at com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNode.doRun(LLVMFunctionRootNode.java:81)
	at com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNodeGen.executeGeneric(LLVMFunctionRootNodeGen.java:25)
	at com.oracle.truffle.llvm.runtime.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:93)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:655)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:627)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:560)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:544)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:486)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:71)
	at com.oracle.truffle.llvm.runtime.interop.LLVMForeignFunctionCallNode.doCall(LLVMForeignFunctionCallNode.java:53)
	at com.oracle.truffle.llvm.runtime.interop.LLVMForeignCallNode.execute(LLVMForeignCallNode.java:221)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:655)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:627)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:560)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:544)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:486)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:71)
	at com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptor$Execute.doDescriptor(LLVMFunctionDescriptor.java:180)
	at com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptorGen$InteropLibraryExports$Cached.executeAndSpecialize(LLVMFunctionDescriptorGen.java:166)
	at com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptorGen$InteropLibraryExports$Cached.execute(LLVMFunctionDescriptorGen.java:124)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.execute(InteropLibraryGen.java:7588)
	at com.oracle.truffle.llvm.runtime.SulongLibrary.invokeMember(SulongLibrary.java:197)
	at com.oracle.truffle.llvm.runtime.SulongLibraryGen$InteropLibraryExports$Cached.invokeMember(SulongLibraryGen.java:236)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.invokeMember(InteropLibraryGen.java:8134)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$AbstractInvokeNode.executeShared(PolyglotValueDispatch.java:4412)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$InvokeNoArgsNode.executeImpl(PolyglotValueDispatch.java:4476)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:125)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:655)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:627)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:560)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:544)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalRuntimeSupport.callProfiled(GraalRuntimeSupport.java:235)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue.invoke(PolyglotValueDispatch.java:2402)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:932)
	at Java2Threads.thread_function(Java2Threads.java:11)
	at Java2Threads.lambda$main$0(Java2Threads.java:33)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: Attached Guest Language Frames (6)

```

**How to compile the LLVM bitcode that causes the problem**
 Compile C++ lib:
 ```
 $GRAALVM_MANAGED_LLVM_TOOLCHAIN/clang++ -fPIC -shared -O1 -g call_once.cpp -lgraalvm-llvm -o call_once.so
 ```
Where 
```
export GRAALVM_MANAGED_LLVM_TOOLCHAIN=$($GRAALVM_HOME/bin/lli --print-toolchain-path --llvm.managed)
```

**Code snippet or code repository that reproduces the problem**
C++ code: call_once.cpp:
```
#include <iostream>
#include <mutex>
#include <graalvm/llvm/polyglot.h>

#ifdef __cplusplus
extern "C" {
#endif

std::once_flag flag;

void called_once() {
        std::cout << "called_once" << "\n";
}

void call_once() {
        std::call_once(flag, [](){std::cout << "Happens once" << std::endl;});

        std::cout << "Happens every time" << std::endl;
}
#ifdef __cplusplus
}
#endif
```
Java:
```
import java.io.*;
import org.graalvm.polyglot.*;

class Java2Threads {
       private static void thread_function() {
       try {
                       System.out.println("Java tid " + Thread.currentThread().getId());                   
                       cpart.invokeMember("call_once");
               } catch (Exception e) {
                       System.out.println("Exception " + Thread.currentThread().getId());
                       e.printStackTrace();
                       System.exit(-1);
               }
       }

       public static void main(String[] args) throws Exception {
               Context polyglot = Context.newBuilder().allowAllAccess(true).allowIO(true).option("llvm.managed", "true").build();
                       //option("inspect", "true").option("llvm.lazyParsing", "false").option("inspect.Suspend", "false").option("inspect.WaitAttached","true").build();
               File file = new File("call_once.so");
               Source source = Source.newBuilder("llvm", file).build();
               cpart = polyglot.eval(source);

               Thread myThread = new Thread(() -> { // Lambda Expression
                       thread_function();
               });

               Thread myThread2 = new Thread(() -> { // Lambda Expression
                       thread_function();
               });

               myThread.start();
               myThread2.start();
               myThread.join();
               myThread2.join();
        }
}
```

**Steps to reproduce the problem**
Please include both build steps as well as run steps
1. $GRAALVM_MANAGED_LLVM_TOOLCHAIN/clang++ -std=c++17 -fPIC -shared -O1 -g call_once.cpp -lgraalvm-llvm -o call_once.so
2. javac Java2Threads.java && java Java2Threads
     
**Expected behavior**
no crash and "called_once" printed only one.

**Additional context**
Note: I tried calling pthread_create before creating the threads, but it didn't solve the issue.

**Comment by rschatz** [comment]
I have found the issue and fixed it on the master branch. It was a small mismatch between the semantics of pthread synchronization primitives and the corresponding Java APIs.
