### ISSUE TITLE
Error when use native-image --language:js

### ISSUE THREAD

**Issue by SolomonSun2010** [oracle/graal#4371]
**Describe the issue**
Error when use below :
native-image --language:js  PolyglotJavaJS

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. javac PolyglotJavaJS.java
2. Java PolyglotJavaJS  // runs OK
3. native-image --language:js  PolyglotJavaJS // Error !

**Describe GraalVM and your environment:**
 - GraalVM version: **[[CE 22.1.0-dev-20220302_0015](https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/22.1.0-dev-20220302_0015)]**
 - JDK major version: **[11]**
 - OS: **[Ubuntu 18.04]**
 - Architecture: **[AMD64]**

**More details**
```java
import org.graalvm.polyglot.*;

public class PolyglotJavaJS {
    public static void main(String[] args) {
        Context polyglot = Context.create();
        Value array = polyglot.eval("js", "eval('1+1')");
        int result = array.asInt();
        System.out.println(result);
    }
}
```

```
(my_new_venv) root@peks:/opt/graalpython-22.1.0-dev-linux-amd64# native-image --language:js PolyglotJavaJS
========================================================================================================================
GraalVM Native Image: Generating 'polyglotjavajs' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                    (3.7s @ 0.21GB)
 Version info: 'GraalVM 22.1.0-dev Java 11 CE'
 C compiler: gcc (linux, x86_64, 7.5.0)
 Garbage collector: Serial GC
[2/7] Performing analysis...  [************]                                                            (39.8s @ 3.66GB)
  15,531 (96.53%) of 16,089 classes reachable
  26,953 (65.37%) of 41,234 fields reachable
  83,540 (84.90%) of 98,401 methods reachable
  12,294 (12.49%) of 98,401 methods included for runtime compilation
     191 classes,   652 fields, and   723 methods registered for reflection
      57 classes,    58 fields, and    51 methods registered for JNI access
[3/7] Building universe...                                                                               (2.4s @ 4.26GB)
[4/7] Parsing methods...      [**]                                                                       (4.7s @ 4.98GB)
[5/7] Inlining methods...     [*****]                                                                    (9.5s @ 1.89GB)
[6/7] Compiling methods...    [*****]                                                                   (26.3s @ 4.52GB)
[7/7] Creating image...
                                                                                  (0.0s @ 3.90GB)
Fatal error: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1

Linker command executed:
/usr/bin/gcc -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-16072569891138210425/exported_symbols.list -Wl,--exclude-libs,ALL -Wl,-x -o /opt/graalpython-22.1.0-dev-linux-amd64/polyglotjavajs polyglotjavajs.o /opt/graalvm-ce-java11-22.1.0-dev/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/graalvm-ce-java11-22.1.0-dev/lib/static/linux-amd64/glibc/libnet.a /opt/graalvm-ce-java11-22.1.0-dev/lib/static/linux-amd64/glibc/libextnet.a /opt/graalvm-ce-java11-22.1.0-dev/lib/static/linux-amd64/glibc/libnio.a /opt/graalvm-ce-java11-22.1.0-dev/lib/static/linux-amd64/glibc/libjava.a /opt/graalvm-ce-java11-22.1.0-dev/lib/static/linux-amd64/glibc/libfdlibm.a /opt/graalvm-ce-java11-22.1.0-dev/lib/static/linux-amd64/glibc/libzip.a /opt/graalvm-ce-java11-22.1.0-dev/lib/svm/clibraries/linux-amd64/libjvm.a -v -L/tmp/SVM-16072569891138210425 -L/opt/graalvm-ce-java11-22.1.0-dev/lib/static/linux-amd64/glibc -L/opt/graalvm-ce-java11-22.1.0-dev/lib/svm/clibraries/linux-amd64 -lpthread -ldl -lz -lrt

Linker command output:
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/7/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/7/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-z' 'noexecstack' '-o' '/opt/graalpython-22.1.0-dev-linux-amd64/polyglotjavajs' '-v' '-L/tmp/SVM-16072569891138210425' '-L/opt/graalvm-ce-java11-22.1.0-dev/lib/static/linux-amd64/glibc' '-L/opt/graalvm-ce-java11-22.1.0-dev/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/7/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/7/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper -plugin-opt=-fresolution=/tmp/ccryovR5.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -z now -z relro -o /opt/graalpython-22.1.0-dev-linux-amd64/polyglotjavajs -z noexecstack /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/7/crtbeginS.o -L/tmp/SVM-16072569891138210425 -L/opt/graalvm-ce-java11-22.1.0-dev/lib/static/linux-amd64/glibc -L/opt/graalvm-ce-java11-22.1.0-dev/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/7/../../.. --gc-sections --dynamic-list /tmp/SVM-16072569891138210425/exported_symbols.list --exclude-libs ALL -x polyglotjavajs.o /opt/graalvm-ce-java11-22.1.0-dev/lib/svm/clibraries/linux-amd64/liblibchelper.a /opt/graalvm-ce-java11-22.1.0-dev/lib/static/linux-amd64/glibc/libnet.a /opt/graalvm-ce-java11-22.1.0-dev/lib/static/linux-amd64/glibc/libextnet.a /opt/graalvm-ce-java11-22.1.0-dev/lib/static/linux-amd64/glibc/libnio.a /opt/graalvm-ce-java11-22.1.0-dev/lib/static/linux-amd64/glibc/libjava.a /opt/graalvm-ce-java11-22.1.0-dev/lib/static/linux-amd64/glibc/libfdlibm.a /opt/graalvm-ce-java11-22.1.0-dev/lib/static/linux-amd64/glibc/libzip.a /opt/graalvm-ce-java11-22.1.0-dev/lib/svm/clibraries/linux-amd64/libjvm.a -lpthread -ldl -lz -lrt -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-linux-gnu/7/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crtn.o
ld.lld: error: cannot preempt symbol: IsolateEnterStub_JNIFunctions$UnimplementedWithJNIEnvArgument_unimplemented_2fa2c0d0385cd47a3be4cef638670da72372ef42_66478a56f4c14151ddbd103c451951fba502daf8
>>> defined in polyglotjavajs.o
>>> referenced by polyglotjavajs.o:(.svm_heap+0x1F2A010)

ld.lld: error: cannot preempt symbol: IsolateEnterStub_JNIFunctions$UnimplementedWithJNIEnvArgument_unimplemented_2fa2c0d0385cd47a3be4cef638670da72372ef42_66478a56f4c14151ddbd103c451951fba502daf8
>>> defined in polyglotjavajs.o
>>> referenced by polyglotjavajs.o:(.svm_heap+0x1F2A018)

ld.lld: error: cannot preempt symbol: IsolateEnterStub_JNIFunctions$UnimplementedWithJNIEnvArgument_unimplemented_2fa2c0d0385cd47a3be4cef638670da72372ef42_66478a56f4c14151ddbd103c451951fba502daf8
>>> defined in polyglotjavajs.o
>>> referenced by polyglotjavajs.o:(.svm_heap+0x1F2A020)

ld.lld: error: cannot preempt symbol: IsolateEnterStub_JNIFunctions$UnimplementedWithJNIEnvArgument_unimplemented_2fa2c0d0385cd47a3be4cef638670da72372ef42_66478a56f4c14151ddbd103c451951fba502daf8
>>> defined in polyglotjavajs.o
>>> referenced by polyglotjavajs.o:(.svm_heap+0x1F2A028)

ld.lld: error: cannot preempt symbol: IsolateEnterStub_JNIFunctions_GetVersion_8be85797b5e03fe9b5b1db29aa2f2dda4efb4d77_4dce7c804083a392f748189a8743b4913c778bc4
>>> defined in polyglotjavajs.o
>>> referenced by polyglotjavajs.o:(.svm_heap+0x1F2A030)

ld.lld: error: cannot preempt symbol: IsolateEnterStub_JNIFunctions$UnimplementedWithJNIEnvArgument_unimplemented_2fa2c0d0385cd47a3be4cef638670da72372ef42_66478a56f4c14151ddbd103c451951fba502daf8
>>> defined in polyglotjavajs.o
>>> referenced by polyglotjavajs.o:(.svm_heap+0x1F2A038)

ld.lld: error: cannot preempt symbol: IsolateEnterStub_JNIFunctions_FindClass_3ec1032c6cb9443725d1e68194130533bfb04076_2938eed9222a9caade9eb2298992c73700cca5df
>>> defined in polyglotjavajs.o
>>> referenced by polyglotjavajs.o:(.svm_heap+0x1F2A040)

ld.lld: error: cannot preempt symbol: IsolateEnterStub_JNIFunctions_FromReflectedMethod_791b4c77bb79b0d1401efe502ff31396c61397fc_5b06caa0c39bf05d80879d50907e20f8c82c4be6
>>> defined in polyglotjavajs.o
>>> referenced by polyglotjavajs.o:(.svm_heap+0x1F2A048)

ld.lld: error: cannot preempt symbol: IsolateEnterStub_JNIFunctions_FromReflectedField_8e85c2ae62b34b8094cc2b79fa072a63cc8e30af_5de23cdc0cb33b450ad71ca1273cef510a649bb6
>>> defined in polyglotjavajs.o
>>> referenced by polyglotjavajs.o:(.svm_heap+0x1F2A050)

ld.lld: error: cannot preempt symbol: IsolateEnterStub_JNIFunctions_ToReflectedMethod_3ef80262e240189b0898b79e9794fb182c032350_451f0cccef73a72b12b6ee55af31af3bbd0be781
>>> defined in polyglotjavajs.o
>>> referenced by polyglotjavajs.o:(.svm_heap+0x1F2A058)

ld.lld: error: cannot preempt symbol: IsolateEnterStub_JNIFunctions_GetSuperclass_8ef5352c417f52b83ec1051baab7b66c4aa02b94_717974a3efd477ba62bb92506257385449156f9c
>>> defined in polyglotjavajs.o
>>> referenced by polyglotjavajs.o:(.svm_heap+0x1F2A060)

ld.lld: error: cannot preempt symbol: IsolateEnterStub_JNIFunctions_IsAssignableFrom_9f9eb7bd76ac3be141b39cbfab0846b857db8a4a_7075610e1d70b6fb45b46c63d5a9264ecc9af7da
>>> defined in polyglotjavajs.o
>>> referenced by polyglotjavajs.o:(.svm_heap+0x1F2A068)

ld.lld: error: cannot preempt symbol: IsolateEnterStub_JNIFunctions_ToReflectedField_80d8233579d5215df0227b770e5c01228a0de9b9_91f606182fe1f9ea5e5cb0e5e6a95a162c7596d0
>>> defined in polyglotjavajs.o
>>> referenced by polyglotjavajs.o:(.svm_heap+0x1F2A070)

ld.lld: error: cannot preempt symbol: IsolateEnterStub_JNIFunctions_Throw_45c8da67e730e69ddc51802d2295c52b34aee085_8c2b470d1eae7219c39d21d31784d3936280cb3f
>>> defined in polyglotjavajs.o
>>> referenced by polyglotjavajs.o:(.svm_heap+0x1F2A078)

ld.lld: error: cannot preempt symbol: IsolateEnterStub_JNIFunctions_ThrowNew_e3b570e292e0e1e8941b25ee1e9e7535b9f59fb3_b4cb2d209ecba3b903ca8321377ad396600f0fc0
>>> defined in polyglotjavajs.o
>>> referenced by polyglotjavajs.o:(.svm_heap+0x1F2A080)

ld.lld: error: cannot preempt symbol: IsolateEnterStub_JNIFunctions_ExceptionOccurred_000e777c909ddebba179d4b74e02a774f08bc4b8_fe5fb75597e7c53a64bd53ecab52c5e70e9b82b2
>>> defined in polyglotjavajs.o
>>> referenced by polyglotjavajs.o:(.svm_heap+0x1F2A088)

ld.lld: error: cannot preempt symbol: IsolateEnterStub_JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73_2e31b435c724b0160af5d1000dbdbc5b68999154
>>> defined in polyglotjavajs.o
>>> referenced by polyglotjavajs.o:(.svm_heap+0x1F2A090)

ld.lld: error: cannot preempt symbol: IsolateEnterStub_JNIFunctions_ExceptionClear_f8f1b5cbd6fa215c2f96b35e6dbc342caf9c6571_6f58f5b8d6b8badca48b76e24507ad55779f34c2
>>> defined in polyglotjavajs.o
>>> referenced by polyglotjavajs.o:(.svm_heap+0x1F2A098)

ld.lld: error: cannot preempt symbol: IsolateEnterStub_JNIFunctions_FatalError_dea4272cf8e20ff701a0a73f7a6d5d75e3401653_e37931ab8580e10b79aefa2557aa44e4c917b1ab
>>> defined in polyglotjavajs.o
>>> referenced by polyglotjavajs.o:(.svm_heap+0x1F2A0A0)

ld.lld: error: cannot preempt symbol: IsolateEnterStub_JNIFunctions_PushLocalFrame_e76a811b6c351901d35d27d64df8e2a3b62a62f2_856fd1e9c226152ddf0ba73e03c01d8f53958b8d
>>> defined in polyglotjavajs.o
>>> referenced by polyglotjavajs.o:(.svm_heap+0x1F2A0A8)

ld.lld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
collect2: error: ld returned 1 exit status
        at com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:505)
        at com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:452)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:693)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:514)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:413)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:588)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:129)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:618)
------------------------------------------------------------------------------------------------------------------------
                       12.9s (12.5% of total time) in 46 GCs | Peak RSS: 7.59GB | CPU load: 5.47
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /opt/graalpython-22.1.0-dev-linux-amd64/polyglotjavajs.build_artifacts.txt
========================================================================================================================
Failed generating 'polyglotjavajs' after 1m 42s.
Error: Image build request failed with exit status 1
    
```

**Comment by rodrigar-mx** [comment]
Hi @SolomonSun2010. I tested the same code with the same built in Ubunto20.04 amd64 and did not run into any issues. Therefore, this could be related to your environment. Please answer the following questions. i) Have you installed all the [required libraries](https://www.graalvm.org/22.0/reference-manual/native-image/#prerequisites) for native image generation? ii) Are you able to generate a native image for a simple program without polyglot features? iii) which is the output of `ld --version`?
