### ISSUE TITLE
Fail to use Kryo & Fastjson due to "No classes have been predefined" error

### ISSUE THREAD

**Issue by jessefjxm** [oracle/graal#4382]
**Describe the issue**
I create a simple demo that use Kryo to write/read some object, and use Fastjson to r/w some json file. But they both failed one same error:
```
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: No classes have been predefined during the image build to load from bytecodes at runtime.
```
Seems like they failed on reflection.
I searched around for quite a long day but can't find much discussion about this error.
Btw, reflections used by swing & awt works fine on my other program.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. download the demo `git clone https://github.com/jessefjxm/Test ]**](https://github.com/jessefjxm/Test.git`
2 build the demo `mvn clean install`
3. goto the /target directory
4. run with agent to create config 
`java -agentlib:native-image-agent=config-merge-dir=graal-config,config-write-period-secs=10 -jar Test-1.0-SNAPSHOT.jar `
5. build native image
```
native-image -J-Xmx8g --no-fallback --no-server --verbose -Djava.awt.headless=false -jar Test-1.0-SNAPSHOT.jar 
-H:Name="Test" 
-H:ConfigurationFileDirectories=graal-config 
-H:+ReportExceptionStackTraces 
-H:EnableURLProtocols=http,https 
-H:+AddAllCharsets 
-H:IncludeResources=".*xml$" -H:IncludeResources=".*/.*xml$" -H:IncludeResources=".*/.*png$" -H:Log=registerResource 
--allow-incomplete-classpath 
--report-unsupported-elements-at-runtime 
--initialize-at-run-time=io.netty.channel.epoll.Epoll,io.netty.channel.epoll.Native,io.netty.channel.epoll.EpollEventLoop,io.netty.channel.epoll.EpollEventArray,io.netty.channel.DefaultFileRegion,io.netty.channel.kqueue.KQueueEventArray,io.netty.channel.kqueue.KQueueEventLoop,io.netty.channel.kqueue.Native,io.netty.channel.unix.Errors,io.netty.channel.unix.IovArray,io.netty.channel.unix.Limits,io.netty.util.internal.logging.Log4JLogger,io.netty.channel.kqueue.KQueue 
--initialize-at-run-time=java.rmi.server.ObjID,sun.rmi.transport.ObjectTable,sun.rmi.transport.Transport,sun.rmi.transport.tcp.TCPEndpoint,sun.rmi.registry.RegistryImpl,sun.rmi.transport.DGCImpl,sun.rmi.transport.DGCClient 
--initialize-at-run-time=java.sql.DriverManager 
```

**Describe GraalVM and your environment:**
 - GraalVM version 21.3.1
 - JDK major version: 8
 - OS: Windows10
 - Architecture: 64
 - Detail:
```
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (build 1.8.0_302-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.3.1 (build 25.302-b06-jvmci-21.3-b05, mixed mode)
```

**More details**
Here's the running result:
```

C:\Users\jesse\Games\Test\target>test
Exception in thread "main" com.alibaba.fastjson.JSONException: create asm serializer error, verson 1.2.73, class class test.CustomBuffDataDTO
        at com.alibaba.fastjson.serializer.SerializeConfig.createJavaBeanSerializer(SerializeConfig.java:270)
        at com.alibaba.fastjson.serializer.SerializeConfig.createJavaBeanSerializer(SerializeConfig.java:120)
        at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:833)
        at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:442)
        at com.alibaba.fastjson.serializer.JSONSerializer.getObjectWriter(JSONSerializer.java:448)
        at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:309)
        at com.alibaba.fastjson.JSON.toJSONString(JSON.java:769)
        at com.alibaba.fastjson.JSON.toJSONString(JSON.java:707)
        at com.alibaba.fastjson.JSON.toJSONString(JSON.java:672)
        at test.Test.json(Test.java:25)
        at test.Test.main(Test.java:14)
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: No classes have been predefined during the image build to load from bytecodes at runtime.
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:87)
        at com.oracle.svm.core.hub.PredefinedClassesSupport.throwNoBytecodeClasses(PredefinedClassesSupport.java:76)
        at com.oracle.svm.core.hub.PredefinedClassesSupport.loadClass(PredefinedClassesSupport.java:130)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:269)
        at com.alibaba.fastjson.util.ASMClassLoader.defineClassPublic(ASMClassLoader.java:174)
        at com.alibaba.fastjson.serializer.ASMSerializerFactory.createJavaBeanSerializer(ASMSerializerFactory.java:409)
        at com.alibaba.fastjson.serializer.SerializeConfig.createASMSerializer(SerializeConfig.java:92)
        at com.alibaba.fastjson.serializer.SerializeConfig.createJavaBeanSerializer(SerializeConfig.java:254)
        ... 10 more
```
```
:\Users\jesse\Games\Test\target>test
com.oracle.svm.core.jdk.UnsupportedFeatureError: No classes have been predefined during the image build to load from bytecodes at runtime.
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:87)
        at com.oracle.svm.core.hub.PredefinedClassesSupport.throwNoBytecodeClasses(PredefinedClassesSupport.java:76)
        at com.oracle.svm.core.hub.PredefinedClassesSupport.loadClass(PredefinedClassesSupport.java:130)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:269)
        at com.esotericsoftware.reflectasm.AccessClassLoader.defineClass(AccessClassLoader.java:78)
        at com.esotericsoftware.reflectasm.AccessClassLoader.defineAccessClass(AccessClassLoader.java:57)
        at com.esotericsoftware.reflectasm.ConstructorAccess.get(ConstructorAccess.java:99)
        at com.esotericsoftware.kryo.util.DefaultInstantiatorStrategy.newInstantiatorOf(DefaultInstantiatorStrategy.java:60)
        at com.esotericsoftware.kryo.Kryo.newInstantiator(Kryo.java:1117)
        at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1126)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.create(FieldSerializer.java:151)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:118)
        at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:748)
        at test.KryoUtil.readFromFile(KryoUtil.java:72)
        at test.Test.main(Test.java:14)
Exception in thread "main" java.lang.NullPointerException
        at test.Test.main(Test.java:15)
```

Great thanks!

**Comment by rodrigar-mx** [comment]
Hi @jessefjxm. We are currently removing support for jdk8. Is it possible for you to move to jdk11 or jdk17 based version and try it again with latest 22.0.0 version?

**Comment by wirthi** [comment]
Closing stale ticket. If you can provide new information, based on a recent GraalVM release (22.2) and JDK11 or JDK17 (or newer), please reopen!
