### ISSUE TITLE
[GR-37423] "Use reflection metadata for all objects" has broken debuginfotest

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#4388]
[Use reflection metadata for all objects](https://github.com/oracle/graal/commit/8a42ff96c5bee396affbeeab8251e7dd195b6554) has unfortunately broken debuginfotest:
https://github.com/oracle/graal/actions/runs/1975278940

```
(gdb) ptype 'java.lang.Object'
Checker ptype Object: insufficient matching lines 13 for regular expressions 15
Checker ptype Object {
  re.compile('type = class java\\.lang\\.Object : public _objhdr {')
  re.compile('[ \t]+public:')
  re.compile('[ \t]+void Object\\(void\\);')
  re.compile('[ \t]+protected:')
  re.compile('[ \t]+java\\.lang\\.Object \\* clone\\(void\\);')
  re.compile('[ \t]+public:')
  re.compile('[ \t]+boolean equals\\(java\\.lang\\.Object \\*\\);')
  re.compile('[ \t]+int hashCode\\(void\\);')
  re.compile('[ \t]+void notify\\(void\\);')
  re.compile('[ \t]+void notifyAll\\(void\\);')
  re.compile('[ \t]+java\\.lang\\.String \\* toString\\(void\\);')
  re.compile('[ \t]+void wait\\(void\\);')
  re.compile('[ \t]+void wait\\(long\\);')
  re.compile('[ \t]+void wait\\(long, int\\);')
  re.compile('}')
}

type = class java.lang.Object : public _objhdr {
  public:
    void Object(void);
  protected:
    java.lang.Object * clone(void);
  public:
    boolean equals(java.lang.Object *);
    java.lang.Class * getClass(void);
    int hashCode(void);
    void notify(void);
    void notifyAll(void);
    java.lang.String * toString(void);
    void wait(void);
    void wait(long);
}


gate: 13 Mar 2022 03:54:05(+05:19) END:   image debuginfotest [0:02:26.758170] [disk (free/total): 25.6GB/83.2GB]
Traceback (most recent call last):
  File "/home/runner/work/graal/graal/mx/mx_gate.py", line 422, in gate
    _run_gate(cleanArgs, args, tasks)
  File "/home/runner/work/graal/graal/mx/mx_gate.py", line 651, in _run_gate
    runner(args, tasks)
  File "/home/runner/work/graal/graal/substratevm/mx.substratevm/mx_substratevm.py", line 384, in svm_gate_body
gate: 13 Mar 2022 03:54:05(+05:19) ABORT: Gate [0:05:19.616314] [disk (free/total): 25.6GB/83.2GB]
    debuginfotest(['--output-path', svmbuild_dir()])
  File "/home/runner/work/graal/graal/mx/mx_commands.py", line 147, in __call__
    return self.command_function(*args, **kwargs)
  File "/home/runner/work/graal/graal/substratevm/mx.substratevm/mx_substratevm.py", line 1162, in debuginfotest
    config=config
  File "/home/runner/work/graal/graal/substratevm/mx.substratevm/mx_substratevm.py", line 847, in native_image_context_run
    func(native_image, func_args)
  File "/home/runner/work/graal/graal/substratevm/mx.substratevm/mx_substratevm.py", line 1161, in <lambda>
    _debuginfotest(native_image, output_path, build_only, a), unmask(parsed.image_args),
  File "/home/runner/work/graal/graal/substratevm/mx.substratevm/mx_substratevm.py", line 812, in _debuginfotest
    mx.run([os.environ.get('GDB_BIN', 'gdb'), '-ex', 'python "ISOLATES=True"', '-x', join(parent, 'mx.substratevm/testhello.py'), join(path, 'hello.hello')])
  File "/home/runner/work/graal/graal/mx/mx.py", line 13309, in run
    abort(retcode)
  File "/home/runner/work/graal/graal/mx/mx.py", line 4160, in abort
    raise SystemExit(error_code)
SystemExit: 1
```

FYI @zakkak

**Comment by zakkak** [comment]
Thanks for the heads up @fniephaus.
It also results in NPE in Quarkus, see https://github.com/oracle/graal/runs/5531903059?check_suite_focus=true#step:8:342

**Comment by gastaldi** [comment]
Here is the full stack trace for the record: 

```java
Fatal error: java.lang.NullPointerException: Cannot invoke "java.lang.annotation.Annotation.annotationType()" because "annotation" is null
    at com.oracle.svm.reflect.hosted.ReflectionMetadataEncoderImpl.registerAnnotation(ReflectionMetadataEncoderImpl.java:511)
    at com.oracle.svm.reflect.hosted.ReflectionMetadataEncoderImpl.registerTypeAnnotationValues(ReflectionMetadataEncoderImpl.java:500)
    at com.oracle.svm.reflect.hosted.ReflectionMetadataEncoderImpl.addClassMetadata(ReflectionMetadataEncoderImpl.java:264)
    at com.oracle.svm.hosted.image.NativeImageCodeCache.buildRuntimeMetadata(NativeImageCodeCache.java:252)
    at com.oracle.svm.hosted.image.LIRNativeImageCodeCache.layoutMethods(LIRNativeImageCodeCache.java:106)
    at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:640)
    at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:514)
    at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
    at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
    at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
    at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:615)
```

**Comment by fniephaus** [comment]
Thanks, @gastaldi! We are already working on a fix, which should ship with 22.1.

**Comment by zakkak** [comment]
FTR the WIP PR fixing the NPE and the rest of the issues is https://github.com/oracle/graal/pull/4414

**Comment by loicottet** [comment]
Fixed by https://github.com/oracle/graal/commit/f0ed0edb1ced7531ee04e667ff0f07d0ad9fdad6
