### ISSUE TITLE
native-image Bridging Go with Java fails with Graal

### ISSUE THREAD

**Issue by mustafaakin** [oracle/graal#439]
Go can build shared libraries as well. Fetched an example code from somewhere and come up with the following:

```go
package main
//#cgo CFLAGS: -I/usr/lib/jvm/java-8-openjdk-amd64/include
//#cgo CFLAGS: -I/usr/lib/jvm/java-8-openjdk-amd64/include/linux
//#include <jni.h>
import "C"
import "fmt"

//export Java_Hello_add
func Java_Hello_add(env *C.JNIEnv, clazz C.jclass, x C.jlong, y C.jlong) C.jlong {
        fmt.Println("Hello from Go");
        return x + y
}

func main(){}
```

The corresponding Java class:

```java
public class Hello{
        static{
                System.loadLibrary("Hello");
        }
        public static native long add(long x ,long y);

        public static void main(String args[]){
                System.out.println("Hello");
                System.out.println(add(123,321));
        }
}
```

Script to build and run with normal Java:

```sh
$ go build -buildmode=c-shared -o libHello.so main.go
$ javac Hello.java
$ java -Djava.library.path=. Hello
Hello
Hello from Go
444
```

It compiles succesfully but in the runtime it fails:

```
$GRAALVM_HOME/bin/native-image Hello -H:+JNI -H:+ReflectionEnabled -H:+ReportUnsupportedElementsAtRuntime -Djava.library.path=$(pwd)
Build on Server(pid: 1234, port: 26682)*
   classlist:   2,113.06 ms
       (cap):   1,175.76 ms
       setup:   2,307.56 ms
  (typeflow):   6,556.06 ms
   (objects):   2,584.48 ms
  (features):     145.52 ms
    analysis:   9,422.01 ms
    universe:     466.76 ms
     (parse):   1,870.12 ms
    (inline):   1,377.15 ms
   (compile):   9,613.53 ms
     compile:  13,372.68 ms
       image:   1,165.99 ms
       write:     296.56 ms
     [total]:  29,235.62 ms
```

In the runtime:
```bash
./hello
Hello
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.lang.Throwable.<init>(Throwable.java:310)
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:89)
	at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)
	at com.oracle.svm.reflect.proxies.Proxy_1_Hello_main.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:199)
[
	at Lcom/oracle/svm/core/code/CEntryPointCallStubs;.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Caused by: java.lang.UnsatisfiedLinkError: Hello.add(JJ)J [symbol: Java_Hello_add or Java_Hello_add__JJ]
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Error.<init>(Error.java:70)
	at java.lang.LinkageError.<init>(LinkageError.java:55)
	at java.lang.UnsatisfiedLinkError.<init>(UnsatisfiedLinkError.java:54)
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:123)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:52)
[
	at Hello.add(Hello.java)
	at Hello.main(Hello.java:9)
	... 4 more
```

I also checked whether I should link the generated shared library .so 

``` 
$ ldd hello
	linux-vdso.so.1 (0x00007ffdc87d2000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f04acd6e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f04acb51000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f04ac936000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f04ac72e000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f04ac4f7000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f04ac14c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f04acf72000)
```

What am I doing wrong?

**Comment by peter-hofer** [comment]
The problem is that the library is loaded in the static constructor `static { ... }`. Static constructors are already executed when the class is loaded during the build, but are no longer executed at runtime. If you move the `System.loadLibrary()` call to the first line of `main`, it will work.

**Comment by mustafaakin** [comment]
Yes, I confirm it works when the shared library is loaded in the main:

```
public class Hello{
        public static native long add(long x ,long y);

        public static void main(String args[]){
                System.out.println("Hello");
                System.loadLibrary("Hello");
                System.out.println(add(123,321));
        }
}
```
