### ISSUE TITLE
graalpython don't works in arch linux with libcrypt.so.1 not found

### ISSUE THREAD

**Issue by ilyapashuk** [oracle/graal#4415]
graal version 22.0.0.2 community
jdk 17
os archlinux amd64 with all latest updates
output of java --xinternalversion
OpenJDK 64-Bit Server VM (17.0.2+8-jvmci-22.0-b05) for linux-amd64 JRE (17.0.2+8-jvmci-22.0-b05), built on Jan 20 2022 22:54:40 by "buildslave" with gcc 10.3.0

**Describe the issue**
when I try to run graalpython, installed by gu, I get the following error:
ERROR: com.oracle.truffle.api.CompilerDirectives$ShouldNotReachHere: Unable to load native posix support library
org.graalvm.polyglot.PolyglotException: com.oracle.truffle.api.CompilerDirectives$ShouldNotReachHere: Unable to load native posix support library
	at com.oracle.truffle.api.CompilerDirectives.shouldNotReachHere(CompilerDirectives.java:570)
	at com.oracle.graal.python.runtime.NFIPosixSupport$InvokeNativeFunction.loadLibrary(NFIPosixSupport.java:367)
	at com.oracle.graal.python.runtime.NFIPosixSupport$InvokeNativeFunction.call(NFIPosixSupport.java:291)
	at com.oracle.graal.python.runtime.NFIPosixSupport$InvokeNativeFunction.callLong(NFIPosixSupport.java:306)
	at com.oracle.graal.python.runtime.NFIPosixSupport.lseek(NFIPosixSupport.java:612)
	at com.oracle.graal.python.runtime.NFIPosixSupportGen$PosixSupportLibraryExports$Uncached.lseek(NFIPosixSupportGen.java:3389)
	at com.oracle.graal.python.runtime.ImageBuildtimePosixSupport.lseek(ImageBuildtimePosixSupport.java:256)
	at com.oracle.graal.python.runtime.ImageBuildtimePosixSupportGen$PosixSupportLibraryExports$Uncached.lseek(ImageBuildtimePosixSupportGen.java:1325)
	at com.oracle.graal.python.runtime.PosixSupportLibraryGen$UncachedDispatch.lseek(PosixSupportLibraryGen.java:5993)
	at com.oracle.graal.python.builtins.modules.io.FileIOBuiltins$SeekNode.internalSeek(FileIOBuiltins.java:789)
	at com.oracle.graal.python.builtins.modules.io.FileIOBuiltins$TellNode.internalTell(FileIOBuiltins.java:814)
	at com.oracle.graal.python.builtins.modules.io.AbstractBufferedIOBuiltins$BufferedInitNode.internalInit(AbstractBufferedIOBuiltins.java:116)
	at com.oracle.graal.python.builtins.modules.io.BufferedReaderBuiltins$BufferedReaderInit.internalInit(BufferedReaderBuiltins.java:95)
	at com.oracle.graal.python.builtins.modules.SysModuleBuiltins.initStd(SysModuleBuiltins.java:595)
	at com.oracle.graal.python.builtins.modules.SysModuleBuiltins.postInitialize(SysModuleBuiltins.java:578)
	at com.oracle.graal.python.builtins.Python3Core.postInitialize(Python3Core.java:766)
	at com.oracle.graal.python.runtime.PythonContext.patch(PythonContext.java:1168)
	at com.oracle.graal.python.PythonLanguage.patchContext(PythonLanguage.java:311)
	at com.oracle.graal.python.PythonLanguage.patchContext(PythonLanguage.java:103)
	at com.oracle.truffle.api.LanguageAccessor$LanguageImpl.patchEnvContext(LanguageAccessor.java:427)
	at com.oracle.truffle.polyglot.PolyglotLanguageContext.patch(PolyglotLanguageContext.java:766)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.patch(PolyglotContextImpl.java:2788)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.loadPreinitializedContext(PolyglotEngineImpl.java:1819)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.createContext(PolyglotEngineImpl.java:1712)
	at com.oracle.truffle.polyglot.PolyglotEngineDispatch.createContext(PolyglotEngineDispatch.java:160)
	at org.graalvm.polyglot.Context$Builder.build(Context.java:1832)
	at com.oracle.graal.python.shell.GraalPythonMain.launch(GraalPythonMain.java:609)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:295)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:121)
	at com.oracle.graal.python.shell.GraalPythonMain.main(GraalPythonMain.java:71)
Caused by: java.lang.UnsatisfiedLinkError: libcrypt.so.1: cannot open shared object file: No such file or directory
Internal GraalVM error, please report at https://github.com/oracle/graal/issues/.

**Steps to reproduce the issue**

download this release of the graalvm
add it's bin directory to $PATH
run 'gu install python' to add python support
run 'graalpython --version' to test it

**Expected behavior**
graal python interpreter should run

**Comment by timfel** [comment]
I think you have to install `libxcrypt-compat`.

**Comment by ilyapashuk** [comment]
thank you, it works, so I closing this issue.

may be note about this should be added to the installation guides or error message itself?

**Comment by cristatus** [comment]
IntelliJ IDEA from Flathub uses `org.freedesktop.Sdk/x86_64/23.08` runtime and doesn't include legacy xcrypt. I think graal should upgrade the xcrypt requirements.
