### ISSUE TITLE
[GR-37638] LinkAtBuildTimeSupport ImageSingleton is accessed before it gets set up correctly

### ISSUE THREAD

**Issue by olpaw** [oracle/graal#4424]
With spring native image building we can see the following stack traces
```
========================================================================================================================
GraalVM Native Image: Generating 'commandlinerunner-gradle' (executable)...
========================================================================================================================
[1/7] Initializing...
                                                                                    (0.0s @ 0.18GB)
Error: ImageSingletons do not contain key com.oracle.svm.hosted.LinkAtBuildTimeSupport
com.oracle.svm.core.util.UserError$UserException: ImageSingletons do not contain key com.oracle.svm.hosted.LinkAtBuildTimeSupport
	at com.oracle.svm.core.util.UserError.abort(UserError.java:72)
	at com.oracle.svm.hosted.ImageSingletonsSupportImpl$HostedManagement.doLookup(ImageSingletonsSupportImpl.java:117)
	at com.oracle.svm.hosted.ImageSingletonsSupportImpl.lookup(ImageSingletonsSupportImpl.java:44)
	at org.graalvm.sdk/org.graalvm.nativeimage.ImageSingletons.lookup(ImageSingletons.java:86)
	at com.oracle.svm.hosted.LinkAtBuildTimeSupport.singleton(LinkAtBuildTimeSupport.java:43)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.ensureClassInitialized(ConfigurableClassInitialization.java:182)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.forceInitializeHosted(ConfigurableClassInitialization.java:496)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.initializeAtBuildTime(ConfigurableClassInitialization.java:427)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.initializeAtBuildTime(ConfigurableClassInitialization.java:245)
	at com.oracle.svm.hosted.classinitialization.InitKind.lambda$stringConsumer$2(InitKind.java:81)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.lambda$processClassInitializationOptions$1(ClassInitializationFeature.java:92)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.processClassInitializationOptions(ClassInitializationFeature.java:82)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:812)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:554)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:514)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:615)
```
This shows that we setting up LinkAtBuildTimeSupport ImageSingleton too late.

This was first observed here: https://github.com/oracle/graal/issues/2666#issuecomment-1076101856

The reproducer is found here: https://github.com/oracle/graal/issues/2666#issuecomment-1076290540

**Comment by davecramer** [comment]
I just ran into this on a very simple project with a recent download of 22.1.0

/lib/jvm/graalvm-ce-java11-22.1.0/
