### ISSUE TITLE
espresso-jshell throws exception

### ISSUE THREAD

**Issue by davecramer** [oracle/graal#4442]
macos

```echo $GRAALVM_HOME
/Users/davecra/graalvm-ce-java11-22.0.0.2/Contents/Home/
```

```
./espresso-jshell
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.sun.tools.javac.file.BaseFileManager.createLocations(BaseFileManager.java:115)
	at com.sun.tools.javac.file.BaseFileManager.<init>(BaseFileManager.java:76)
	at com.sun.tools.javac.file.JavacFileManager.<init>(JavacFileManager.java:144)
	at com.sun.tools.javac.api.JavacTool.getStandardFileManager(JavacTool.java:108)
	at com.sun.tools.javac.api.JavacTool.getStandardFileManager(JavacTool.java:68)
	at jdk.jshell.TaskFactory.<init>(TaskFactory.java:121)
	at jdk.jshell.JShell.<init>(JShell.java:145)
	at jdk.jshell.JShell$Builder.build(JShell.java:405)
	at jdk.internal.jshell.tool.JShellTool.resetState(JShellTool.java:1085)
	at jdk.internal.jshell.tool.JShellTool.start(JShellTool.java:938)
	at jdk.internal.jshell.tool.JShellToolBuilder.start(JShellToolBuilder.java:261)
	at com.oracle.truffle.espresso.jshell.JavaShellLauncher.main(JavaShellLauncher.java:37)
Caused by: java.lang.NullPointerException
	at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:75)
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
	at com.sun.tools.javac.file.Locations.<clinit>(Locations.java:139)
	... 12 more
```

**Comment by rodrigar-mx** [comment]
Hi @davecramer. Thanks for reporting this issue. Which were the steps you took to build the native espresso-jshell?

**Comment by davecramer** [comment]
@rodrigar-mx as per the README I built it by executing ` sh build-espresso-jshell.sh`

**Comment by mukel** [comment]
The `espresso-jshell` native image doesn't have the "java.home" property defined since in native images there's no Java home nor JDK, everything is bundled in the executable, **BUT** `javac` requires a JDK with all the modules/jars ... in order to compile Java code.
Can you try running with `./espresso-jshell -Djava.home=$GRAALVM_HOME` and report if it fixes the issue for you?

**Comment by davecramer** [comment]
Yes, thanks, that does work.
