### ISSUE TITLE
[native-image] NPE in NativeImageHeap.addObjectToBootImageHeap -> Proxy_15_Iterables_iterators.toString

### ISSUE THREAD

**Issue by vlsi** [oracle/graal#445]
Testcase:

    git clone --depth=1 https://github.com/yandex-qatools/juseppe.git
    cd juseppe
    mvn -DskipTests package
    # Get juseppe-cli/target/juseppe.jar
    native-image --verbose --class-path juseppe.jar -H:Name=juseppe -H:Class=ru.lanwen.jenkins.juseppe.JuseppeCli

Output

```
-Dsubstratevm.version=68c7c1073a86a3d541ffb82434acc664f3096079:substratevm,a642b10d9d3c8ca79be66d5694311e769e1526a9:substratevm-enterprise \
-Dgraalvm.version=1.0.0-rc1 \
-Dorg.graalvm.version=1.0.0-rc1
...
-imagecp \
/Users/vladimirsitnikov/Documents/work/graalvm/graalvm-1.0.0-rc1/Contents/Home/jre/lib/boot/graaljs-scriptengine.jar:/Users/vladimirsitnikov/Documents/work/graalvm/graalvm-1.0.0-rc1/Contents/Home/jre/lib/boot/graal-sdk.jar:/Users/vladimirsitnikov/Documents/work/graalvm/graalvm-1.0.0-rc1/Contents/Home/jre/lib/svm/builder/svm.jar:/Users/vladimirsitnikov/Documents/work/graalvm/graalvm-1.0.0-rc1/Contents/Home/jre/lib/svm/builder/objectfile.jar:/Users/vladimirsitnikov/Documents/work/graalvm/graalvm-1.0.0-rc1/Contents/Home/jre/lib/svm/builder/svm-enterprise.jar:/Users/vladimirsitnikov/Documents/work/graalvm/graalvm-1.0.0-rc1/Contents/Home/jre/lib/svm/builder/pointsto.jar:/Users/vladimirsitnikov/Documents/work/graalvm/graalvm-1.0.0-rc1/Contents/Home/jre/lib/jvmci/graal.jar:/Users/vladimirsitnikov/Documents/work/graalvm/graalvm-1.0.0-rc1/Contents/Home/jre/lib/jvmci/enterprise-graal.jar:/Users/vladimirsitnikov/Documents/work/graalvm/graalvm-1.0.0-rc1/Contents/Home/jre/lib/jvmci/jvmci-api.jar:/Users/vladimirsitnikov/Documents/work/graalvm/graalvm-1.0.0-rc1/Contents/Home/jre/lib/jvmci/jvmci-hotspot.jar:/Users/vladimirsitnikov/Documents/work/graalvm/graalvm-1.0.0-rc1/Contents/Home/jre/lib/svm/library-support-enterprise.jar:/Users/vladimirsitnikov/Documents/work/graalvm/graalvm-1.0.0-rc1/Contents/Home/jre/lib/svm/library-support.jar:/Users/vladimirsitnikov/Documents/work/graalvm/juseppe.jar \
-H:Path=/Users/vladimirsitnikov/Documents/work/graalvm \
-H:Name=juseppe \
-H:Class=ru.lanwen.jenkins.juseppe.JuseppeCli \
-H:CLibraryPath=/Users/vladimirsitnikov/Documents/work/graalvm/graalvm-1.0.0-rc1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64
]
   classlist:   2,584.50 ms
       (cap):   1,359.79 ms
       setup:   2,496.95 ms
  (typeflow):   4,610.68 ms
   (objects):   3,733.29 ms
  (features):      80.36 ms
    analysis:   8,594.76 ms
    universe:     354.80 ms
     (parse):   1,496.98 ms
    (inline):   1,385.62 ms
   (compile):  10,188.11 ms
     compile:  13,771.14 ms
       image:     381.16 ms
fatal error: java.lang.NullPointerException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:398)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:240)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:337)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:78)
Caused by: java.lang.NullPointerException
	at com.oracle.svm.reflect.proxies.Proxy_15_Iterables_iterators.toString(Unknown Source)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at com.oracle.svm.hosted.image.NativeImageHeap.addObjectToBootImageHeap(NativeImageHeap.java:376)
	at com.oracle.svm.hosted.image.NativeImageHeap.addObject(NativeImageHeap.java:248)
	at com.oracle.svm.hosted.image.NativeImageHeap.processAddObjectWorklist(NativeImageHeap.java:549)
	at com.oracle.svm.hosted.image.NativeImageHeap.addTrailingObjects(NativeImageHeap.java:114)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:850)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:381)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image building with exit status 1
```

**Comment by cstancu** [comment]
@vlsi thank you for your report. This issue was [recently fixed](https://github.com/oracle/graal/commit/bade450af5e9e08935a5b6df7ba69a4dd9ed6026). Please [build from source](https://github.com/oracle/graal/tree/master/substratevm#quick-start) to get the latest fixes.
