### ISSUE TITLE
[native-image] PGO Instrument build failing

### ISSUE THREAD

**Issue by Jotschi** [oracle/graal#447]
I'm seeing a `ClassCastException` error when building a native image using  the `--pgo-instrument` flag. Same build passes without the flag.

## Version

* graalvm-ee-1.0.0-rc1-linux-amd64.tar.gz

```
SubstrateVM Version Info
68c7c1073a86a3d541ffb82434acc664f3096079:substratevm
a642b10d9d3c8ca79be66d5694311e769e1526a9:substratevm-enterprise
GraalVM Version 1.0.0-rc1
```

## Error

```
fatal error: org.graalvm.compiler.debug.GraalError: java.lang.ClassCastException: com.oracle.svm.enterprise.a.a.a$b cannot be cast to com.oracle.svm.enterprise.a.a.a$c
        at method: Object com.oracle.svm.reflect.proxies.Proxy_11_NetworkChannel_getOption.invoke(Object, Object[])  [Virtual call from int JavaMainWrapper.run(int, CCharPointerPointer), callTarget Object MethodAccessor.invoke(Object, Object[])]
        at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:966)
        at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:892)
        at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:254)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:172)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassCastException: com.oracle.svm.enterprise.a.a.a$b cannot be cast to com.oracle.svm.enterprise.a.a.a$c
        at com.oracle.svm.enterprise.a.a.a.a(stripped:50)
        at com.oracle.svm.enterprise.a.a.i.index(stripped:27)
        at com.oracle.svm.enterprise.a.a.c.lower(stripped:64)
        at com.oracle.svm.enterprise.a.a.i.lower(stripped:12)
        at com.oracle.svm.enterprise.a.a.j.lower(stripped:86)
        at org.graalvm.compiler.phases.common.LoweringPhase$Round.process(LoweringPhase.java:460)
        at org.graalvm.compiler.phases.common.LoweringPhase$Round.access$200(LoweringPhase.java:336)
        at org.graalvm.compiler.phases.common.LoweringPhase$Round$ProcessFrame.preprocess(LoweringPhase.java:400)
        at org.graalvm.compiler.phases.common.LoweringPhase.processBlock(LoweringPhase.java:559)
        at org.graalvm.compiler.phases.common.LoweringPhase$Round.run(LoweringPhase.java:385)
        at org.graalvm.compiler.phases.Phase.run(Phase.java:47)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:195)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:137)
        at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:210)
        at org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:54)
        at org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:36)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:195)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:137)
        at org.graalvm.compiler.phases.common.LoweringPhase.lower(LoweringPhase.java:256)
        at org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:249)
        at org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:89)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:195)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:137)
        at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:210)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:195)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:137)
        at org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:247)
        at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:174)
        at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:160)
        at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:935)
        ... 8 more
Error: Image building with exit status 1
```

## Reproducer

https://github.com/Jotschi/vertx-graalvm-native-image-test/tree/dev-pgo (__dev-pgo__ branch)

1. Run maven build
`mvn clean package`

2. Run native image build
```
native-image \
 --verbose \
 --no-server \
 --pgo-instrument \
 -Dio.netty.noUnsafe=true  \
 -H:ReflectionConfigurationFiles=./reflectconfigs/netty.json \
 -H:+ReportUnsupportedElementsAtRuntime \
 -jar target/vertx-graalvm-native-image-test-0.0.1-SNAPSHOT.jar
```

**Comment by Jotschi** [comment]
Also happens using graalvm-ee-1.0.0-rc2-linux-amd64.tar.gz

**Comment by panga** [comment]
PGO feature is enterprise only?

**Comment by Jotschi** [comment]
@panga Yes

**Comment by vjovanov** [comment]
Fixed. Thank you very much for the clean bug report!
