### ISSUE TITLE
--language:js seems to disable inlining in native images

### ISSUE THREAD

**Issue by sdeleuze** [oracle/graal#4473]
Based on what we discussed [in this Spring Native issue](https://github.com/spring-projects-experimental/spring-native/issues/1510#issuecomment-1084265919), using `--language:js` seems to disable inlining like if `-H:-InlineBeforeAnalysis` was applied, breaking Spring Boot applications compiled with Spring Native.

Please tag this issue with the `spring` label.

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this, we will take a look and get back to you, in the meantime could you share the steps to reproduce the issue

**Comment by LilPoppy** [comment]
> Thank you for reporting this, we will take a look and get back to you, in the meantime could you share the steps to reproduce the issue

Hi @oubidar-Abderrahim 

Pull newest from repository first:
git clone https://github.com/StorebeansDev/cobnet.git

Check if you have any Redis port opening:
sudo lsof -i :6379

Kill the redis if you have any exists:
kill -9 [pid]

Then run the following:
mvn -Dredis-host=redis -Ddb-host=db clean install -Pdocker -Ddocker-target=native

After done container run:
docker start -a cobnet

**Comment by sdeleuze** [comment]
Can be reproduced without that with just a simple Spring webapp.

**Comment by oubidar-Abderrahim** [comment]
Thank you @sdeleuze, could you please share the simple Spring webapp for clarity?

**Comment by sdeleuze** [comment]
Sure:
 - Clone https://github.com/spring-projects-experimental/spring-native
 -  In `samples/webflux-netty`, add `@NativeHint(options = "--language:js")` to `WebfluxApplication`
 - Build the project with `./build.sh`

**Comment by michelu89** [comment]
Hi @oubidar-Abderrahim,

The problem when testing my Spring application comes to a similar problem as @sdeleuze mentioned. 

What are my steps:

1. MacOs Monterey
2. set GraalVM EE java11 22.1.0 as default java
3. Cloned https://github.com/spring-projects-experimental/spring-native
4. cd samples/webmvc-tomcat **(Important, since Netty works for me too)**
5. added @NativeHint(options = "--language:js") to WebmvcApplication like this:

```
package com.example.webmvc;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.nativex.hint.NativeHint;

@NativeHint( options = "--language:js" )
@SpringBootApplication
public class WebmvcApplication {

   public static void main( final String[] args ) {
      SpringApplication.run( WebmvcApplication.class, args );
   }
}

```

6. ./build.sh

the i output i get: 

````
=== Building webmvc-tomcat sample ===
Packaging webmvc-tomcat with Maven (native)
SUCCESS
Testing webmvc-tomcat
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< com.example:webmvc-tomcat >----------------------
[INFO] Building webmvc-tomcat 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] Could not transfer metadata org.springframework.experimental:spring-native:0.12.0-SNAPSHOT/maven-metadata.xml from/to snapshots (https://repo.spring.io/plugins-release/): authentication failed for https://repo.spring.io/plugins-release/org/springframework/experimental/spring-native/0.12.0-SNAPSHOT/maven-metadata.xml, status: 401 Unauthorized
[WARNING] org.springframework.experimental:spring-native:0.12.0-SNAPSHOT/maven-metadata.xmlfailed to transfer from https://repo.spring.io/plugins-release/ during a previous attempt. This failure was cached in the local repository and resolution will not be reattempted until the update interval of snapshots has elapsed or updates are forced. Original error: Could not transfer metadata org.springframework.experimental:spring-native:0.12.0-SNAPSHOT/maven-metadata.xml from/to snapshots (https://repo.spring.io/plugins-release/): authentication failed for https://repo.spring.io/plugins-release/org/springframework/experimental/spring-native/0.12.0-SNAPSHOT/maven-metadata.xml, status: 401 Unauthorized
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ webmvc-tomcat ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 1 resource
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ webmvc-tomcat ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 6 source files to /Users/smi4abt/Downloads/spring-native-main/samples/webmvc-tomcat/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:testResources (default-testResources) @ webmvc-tomcat ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] skip non existing resourceDirectory /Users/smi4abt/Downloads/spring-native-main/samples/webmvc-tomcat/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ webmvc-tomcat ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to /Users/smi4abt/Downloads/spring-native-main/samples/webmvc-tomcat/target/test-classes
[INFO] 
[INFO] --- spring-aot-maven-plugin:0.12.0-SNAPSHOT:test-generate (test-generate) @ webmvc-tomcat ---
[INFO] Skip Spring AOT test generation since tests are skipped
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ webmvc-tomcat ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- native-maven-plugin:0.9.11:test (test-native) @ webmvc-tomcat ---
[INFO] Skipping native-image tests (parameter 'skipTests' or 'skipNativeTests' is true).
[INFO] 
[INFO] --- spring-aot-maven-plugin:0.12.0-SNAPSHOT:generate (generate) @ webmvc-tomcat ---
2022-05-03 12:30:08.713  INFO 4006 --- [           main] o.s.a.build.ContextBootstrapContributor  : Detected application class: com.example.webmvc.WebmvcApplication
2022-05-03 12:30:08.716  INFO 4006 --- [           main] o.s.a.build.ContextBootstrapContributor  : Processing application context
2022-05-03 12:30:10.791  INFO 4006 --- [           main] o.s.a.build.ContextBootstrapContributor  : Processed 124 bean definitions in 2073ms
2022-05-03 12:30:11.060  INFO 4006 --- [           main] o.s.nativex.support.SpringAnalyzer       : Spring Native operating mode: native
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 33 source files to /Users/smi4abt/Downloads/spring-native-main/samples/webmvc-tomcat/target/classes
[INFO] /Users/smi4abt/Downloads/spring-native-main/samples/webmvc-tomcat/target/generated-runtime-sources/spring-aot/src/main/java/org/springframework/boot/autoconfigure/flyway/_FactoryProvider.java: Some input files use or override a deprecated API.
[INFO] /Users/smi4abt/Downloads/spring-native-main/samples/webmvc-tomcat/target/generated-runtime-sources/spring-aot/src/main/java/org/springframework/boot/autoconfigure/flyway/_FactoryProvider.java: Recompile with -Xlint:deprecation for details.
[INFO] /Users/smi4abt/Downloads/spring-native-main/samples/webmvc-tomcat/target/generated-runtime-sources/spring-aot/src/main/java/org/springframework/aot/StaticSpringFactories.java: /Users/smi4abt/Downloads/spring-native-main/samples/webmvc-tomcat/target/generated-runtime-sources/spring-aot/src/main/java/org/springframework/aot/StaticSpringFactories.java uses unchecked or unsafe operations.
[INFO] /Users/smi4abt/Downloads/spring-native-main/samples/webmvc-tomcat/target/generated-runtime-sources/spring-aot/src/main/java/org/springframework/aot/StaticSpringFactories.java: Recompile with -Xlint:unchecked for details.
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 6 resources
[INFO] 
[INFO] --- maven-jar-plugin:3.2.2:jar (default-jar) @ webmvc-tomcat ---
[INFO] Building jar: /Users/smi4abt/Downloads/spring-native-main/samples/webmvc-tomcat/target/webmvc-tomcat-0.0.1-SNAPSHOT.jar
[INFO] 
[INFO] --- native-maven-plugin:0.9.11:build (build-native) @ webmvc-tomcat ---
[INFO] ImageClasspath Entry: org.springframework.experimental:spring-native:jar:0.12.0-SNAPSHOT:compile (file:///Users/smi4abt/.m2/repository/org/springframework/experimental/spring-native/0.12.0-SNAPSHOT/spring-native-0.12.0-SNAPSHOT.jar)
[INFO] ImageClasspath Entry: org.springframework.boot:spring-boot-starter-web:jar:2.6.6:compile (file:///Users/smi4abt/.m2/repository/org/springframework/boot/spring-boot-starter-web/2.6.6/spring-boot-starter-web-2.6.6.jar)
[INFO] ImageClasspath Entry: org.springframework.boot:spring-boot-starter:jar:2.6.6:compile (file:///Users/smi4abt/.m2/repository/org/springframework/boot/spring-boot-starter/2.6.6/spring-boot-starter-2.6.6.jar)
[INFO] ImageClasspath Entry: org.springframework.boot:spring-boot:jar:2.6.6:compile (file:///Users/smi4abt/.m2/repository/org/springframework/boot/spring-boot/2.6.6/spring-boot-2.6.6.jar)
[INFO] ImageClasspath Entry: org.springframework.boot:spring-boot-autoconfigure:jar:2.6.6:compile (file:///Users/smi4abt/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.6.6/spring-boot-autoconfigure-2.6.6.jar)
[INFO] ImageClasspath Entry: org.springframework.boot:spring-boot-starter-logging:jar:2.6.6:compile (file:///Users/smi4abt/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.6.6/spring-boot-starter-logging-2.6.6.jar)
[INFO] ImageClasspath Entry: ch.qos.logback:logback-classic:jar:1.2.11:compile (file:///Users/smi4abt/.m2/repository/ch/qos/logback/logback-classic/1.2.11/logback-classic-1.2.11.jar)
[INFO] ImageClasspath Entry: ch.qos.logback:logback-core:jar:1.2.11:compile (file:///Users/smi4abt/.m2/repository/ch/qos/logback/logback-core/1.2.11/logback-core-1.2.11.jar)
[INFO] ImageClasspath Entry: org.apache.logging.log4j:log4j-to-slf4j:jar:2.17.2:compile (file:///Users/smi4abt/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.17.2/log4j-to-slf4j-2.17.2.jar)
[INFO] ImageClasspath Entry: org.apache.logging.log4j:log4j-api:jar:2.17.2:compile (file:///Users/smi4abt/.m2/repository/org/apache/logging/log4j/log4j-api/2.17.2/log4j-api-2.17.2.jar)
[INFO] ImageClasspath Entry: org.slf4j:jul-to-slf4j:jar:1.7.36:compile (file:///Users/smi4abt/.m2/repository/org/slf4j/jul-to-slf4j/1.7.36/jul-to-slf4j-1.7.36.jar)
[INFO] ImageClasspath Entry: jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile (file:///Users/smi4abt/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.jar)
[INFO] ImageClasspath Entry: org.yaml:snakeyaml:jar:1.29:compile (file:///Users/smi4abt/.m2/repository/org/yaml/snakeyaml/1.29/snakeyaml-1.29.jar)
[INFO] ImageClasspath Entry: org.springframework.boot:spring-boot-starter-json:jar:2.6.6:compile (file:///Users/smi4abt/.m2/repository/org/springframework/boot/spring-boot-starter-json/2.6.6/spring-boot-starter-json-2.6.6.jar)
[INFO] ImageClasspath Entry: com.fasterxml.jackson.core:jackson-databind:jar:2.13.2.2:compile (file:///Users/smi4abt/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.13.2.2/jackson-databind-2.13.2.2.jar)
[INFO] ImageClasspath Entry: com.fasterxml.jackson.core:jackson-annotations:jar:2.13.2:compile (file:///Users/smi4abt/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.13.2/jackson-annotations-2.13.2.jar)
[INFO] ImageClasspath Entry: com.fasterxml.jackson.core:jackson-core:jar:2.13.2:compile (file:///Users/smi4abt/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.13.2/jackson-core-2.13.2.jar)
[INFO] ImageClasspath Entry: com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.13.2:compile (file:///Users/smi4abt/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.13.2/jackson-datatype-jdk8-2.13.2.jar)
[INFO] ImageClasspath Entry: com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.2:compile (file:///Users/smi4abt/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.13.2/jackson-datatype-jsr310-2.13.2.jar)
[INFO] ImageClasspath Entry: com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.13.2:compile (file:///Users/smi4abt/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.13.2/jackson-module-parameter-names-2.13.2.jar)
[INFO] ImageClasspath Entry: org.springframework.boot:spring-boot-starter-tomcat:jar:2.6.6:compile (file:///Users/smi4abt/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/2.6.6/spring-boot-starter-tomcat-2.6.6.jar)
[INFO] ImageClasspath Entry: org.apache.tomcat.embed:tomcat-embed-el:jar:9.0.60:compile (file:///Users/smi4abt/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/9.0.60/tomcat-embed-el-9.0.60.jar)
[INFO] ImageClasspath Entry: org.springframework:spring-web:jar:5.3.18:compile (file:///Users/smi4abt/.m2/repository/org/springframework/spring-web/5.3.18/spring-web-5.3.18.jar)
[INFO] ImageClasspath Entry: org.springframework:spring-beans:jar:5.3.18:compile (file:///Users/smi4abt/.m2/repository/org/springframework/spring-beans/5.3.18/spring-beans-5.3.18.jar)
[INFO] ImageClasspath Entry: org.springframework:spring-webmvc:jar:5.3.18:compile (file:///Users/smi4abt/.m2/repository/org/springframework/spring-webmvc/5.3.18/spring-webmvc-5.3.18.jar)
[INFO] ImageClasspath Entry: org.springframework:spring-aop:jar:5.3.18:compile (file:///Users/smi4abt/.m2/repository/org/springframework/spring-aop/5.3.18/spring-aop-5.3.18.jar)
[INFO] ImageClasspath Entry: org.springframework:spring-context:jar:5.3.18:compile (file:///Users/smi4abt/.m2/repository/org/springframework/spring-context/5.3.18/spring-context-5.3.18.jar)
[INFO] ImageClasspath Entry: org.springframework:spring-expression:jar:5.3.18:compile (file:///Users/smi4abt/.m2/repository/org/springframework/spring-expression/5.3.18/spring-expression-5.3.18.jar)
[INFO] ImageClasspath Entry: org.apache.tomcat.experimental:tomcat-embed-programmatic:jar:9.0.60:compile (file:///Users/smi4abt/.m2/repository/org/apache/tomcat/experimental/tomcat-embed-programmatic/9.0.60/tomcat-embed-programmatic-9.0.60.jar)
[WARNING] jar:file:///Users/smi4abt/.m2/repository/org/apache/tomcat/experimental/tomcat-embed-programmatic/9.0.60/tomcat-embed-programmatic-9.0.60.jar!/META-INF/native-image/org.apache.tomcat.embed/tomcat-embed-programmatic/native-image.properties does not match recommended META-INF/native-image/${groupId}/${artifactId}/native-image.properties layout.
[INFO] ImageClasspath Entry: org.slf4j:slf4j-api:jar:1.7.36:compile (file:///Users/smi4abt/.m2/repository/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar)
[INFO] ImageClasspath Entry: org.springframework:spring-core:jar:5.3.18:compile (file:///Users/smi4abt/.m2/repository/org/springframework/spring-core/5.3.18/spring-core-5.3.18.jar)
[INFO] ImageClasspath Entry: org.springframework:spring-jcl:jar:5.3.18:compile (file:///Users/smi4abt/.m2/repository/org/springframework/spring-jcl/5.3.18/spring-jcl-5.3.18.jar)
[INFO] ImageClasspath Entry: com.example:webmvc-tomcat:jar:0.0.1-SNAPSHOT (file:///Users/smi4abt/Downloads/spring-native-main/samples/webmvc-tomcat/target/webmvc-tomcat-0.0.1-SNAPSHOT.jar)
[WARNING] jar:file:///Users/smi4abt/Downloads/spring-native-main/samples/webmvc-tomcat/target/webmvc-tomcat-0.0.1-SNAPSHOT.jar!/META-INF/native-image/org.springframework.aot/spring-aot/native-image.properties does not match recommended META-INF/native-image/${groupId}/${artifactId}/native-image.properties layout.
[INFO] Executing: /Library/Java/JavaVirtualMachines/graalvm-ce-java11-22.0.0.2/Contents/Home/bin/native-image @/var/folders/4v/5mz8kr_n78g42mx5km22l59h0000gp/T/native-image11268357241830380239args
========================================================================================================================
GraalVM Native Image: Generating 'webmvc-tomcat'...
========================================================================================================================
[1/7] Initializing...                                                                                    (5,6s @ 0,34GB)
Warning: Could not register org.springframework.boot.autoconfigure.jdbc.HikariDriverConfigurationFailureAnalyzer: allDeclaredConstructors for reflection. Reason: java.lang.NoClassDefFoundError: org/springframework/jdbc/CannotGetJdbcConnectionException.
Warning: Could not register org.springframework.boot.diagnostics.analyzer.ValidationExceptionFailureAnalyzer: allDeclaredConstructors for reflection. Reason: java.lang.NoClassDefFoundError: javax/validation/ValidationException.
Warning: Could not register org.springframework.boot.liquibase.LiquibaseChangelogMissingFailureAnalyzer: allDeclaredConstructors for reflection. Reason: java.lang.NoClassDefFoundError: liquibase/exception/ChangeLogParseException.
 Version info: 'GraalVM 22.0.0.2 Java 11 CE'
The bundle named: org.apache.tomcat.util.threads.res.LocalStrings, has not been found. If the bundle is part of a module, verify the bundle name is a fully qualified class name. Otherwise verify the bundle path is accessible in the classpath.
[2/7] Performing analysis...  [**********]                                                              (36,3s @ 3,14GB)
Warning: Could not register complete reflection metadata for org.springframework.boot.liquibase.LiquibaseChangelogMissingFailureAnalyzer. Reason(s): java.lang.NoClassDefFoundError: liquibase/exception/ChangeLogParseException
Warning: Could not register complete reflection metadata for org.springframework.boot.autoconfigure.jdbc.HikariDriverConfigurationFailureAnalyzer. Reason(s): java.lang.NoClassDefFoundError: org/springframework/jdbc/CannotGetJdbcConnectionException
Warning: Could not register complete reflection metadata for org.springframework.boot.diagnostics.analyzer.ValidationExceptionFailureAnalyzer. Reason(s): java.lang.NoClassDefFoundError: javax/validation/ValidationException
Warning: Could not register complete reflection metadata for org.springframework.validation.beanvalidation.SpringValidatorAdapter$ViolationFieldError. Reason(s): java.lang.NoClassDefFoundError: javax/validation/Validator, java.lang.NoClassDefFoundError: javax/validation/ConstraintViolation
Warning: Could not register complete reflection metadata for org.springframework.aop.aspectj.autoproxy.AspectJAwareAdvisorAutoProxyCreator. Reason(s): java.lang.NoClassDefFoundError: org/aspectj/util/PartialOrder$PartialComparable
Warning: Could not register complete reflection metadata for org.springframework.aop.aspectj.annotation.AnnotationAwareAspectJAutoProxyCreator. Reason(s): java.lang.NoClassDefFoundError: org/aspectj/util/PartialOrder$PartialComparable
  14.202 (90,55%) of 15.685 classes reachable
  23.052 (76,75%) of 30.036 fields reachable
  67.923 (60,68%) of 111.928 methods reachable
       9 ( 0,01%) of 111.928 methods included for runtime compilation
     637 classes,   158 fields, and 2.283 methods registered for reflection
      68 classes,    89 fields, and    55 methods registered for JNI access
[3/7] Building universe...                                                                               (2,3s @ 3,77GB)
[4/7] Parsing methods...      [**]                                                                       (4,5s @ 1,84GB)
[5/7] Inlining methods...     [*****]                                                                    (4,1s @ 4,56GB)
[6/7] Compiling methods...    [*****]                                                                   (23,9s @ 3,92GB)
[7/7] Creating image...                                                                                  (6,0s @ 2,35GB)
  28,90MB (32,52%) for code area:   44.687 compilation units
  54,95MB (61,83%) for image heap:   9.741 classes and 411.790 objects
   5,02MB ( 5,65%) for other data
  88,87MB in total
------------------------------------------------------------------------------------------------------------------------
Top 10 packages in code area:                               Top 10 object types in image heap:
   1,50MB sun.security.ssl                                    34,00MB byte[] for general heap data
   1,05MB java.util                                            3,39MB java.lang.Class
 728,02KB com.oracle.svm.core.reflect                          2,90MB java.lang.String
 669,80KB com.sun.crypto.provider                              2,64MB byte[] for java.lang.String
 628,40KB com.ibm.icu.impl                                     1,05MB java.util.LinkedHashMap
 507,12KB com.ibm.icu.text                                   718,24KB java.lang.reflect.Method
 493,77KB sun.security.x509                                  698,47KB java.lang.Object[]
 484,39KB org.apache.catalina.core                           584,48KB java.util.HashMap$Node
 473,07KB org.apache.coyote.http2                            557,38KB java.lang.String[]
 472,49KB org.apache.tomcat.util                             530,51KB com.oracle.svm.core.util.LazyFinalReference
      ... 560 additional packages                                 ... 2937 additional object types
                                           (use GraalVM Dashboard to see all)
------------------------------------------------------------------------------------------------------------------------
                        7,3s (8,2% of total time) in 40 GCs | Peak RSS: 6,91GB | CPU load: 7,65
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /Users/smi4abt/Downloads/spring-native-main/samples/webmvc-tomcat/target/webmvc-tomcat (executable)
 /Users/smi4abt/Downloads/spring-native-main/samples/webmvc-tomcat/target/webmvc-tomcat.build_artifacts.txt
========================================================================================================================
Finished generating 'webmvc-tomcat' in 1m 28s.
[INFO] 
[INFO] --- spring-boot-maven-plugin:2.6.6:repackage (repackage) @ webmvc-tomcat ---
[INFO] Attaching repackaged archive /Users/smi4abt/Downloads/spring-native-main/samples/webmvc-tomcat/target/webmvc-tomcat-0.0.1-SNAPSHOT-exec.jar with classifier exec
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:40 min
[INFO] Finished at: 2022-05-03T12:31:46+02:00
[INFO] ------------------------------------------------------------------------
2022-05-03 12:31:46.898  INFO 4069 --- [           main] o.s.nativex.NativeListener               : AOT mode enabled

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.6)

2022-05-03 12:31:46.900  INFO 4069 --- [           main] com.example.webmvc.WebmvcApplication     : Starting WebmvcApplication v0.0.1-SNAPSHOT using Java 11.0.14 on FE-C-005QM with PID 4069 (/Users/smi4abt/Downloads/spring-native-main/samples/webmvc-tomcat/target/webmvc-tomcat started by smi4abt in /Users/smi4abt/Downloads/spring-native-main/samples/webmvc-tomcat)
2022-05-03 12:31:46.900  INFO 4069 --- [           main] com.example.webmvc.WebmvcApplication     : No active profile set, falling back to 1 default profile: "default"
2022-05-03 12:31:46.910  INFO 4069 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2022-05-03 12:31:46.910  INFO 4069 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-05-03 12:31:46.910  INFO 4069 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.60]
2022-05-03 12:31:46.917  INFO 4069 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-05-03 12:31:46.917  INFO 4069 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 17 ms
2022-05-03 12:31:46.925  WARN 4069 --- [           main] w.s.c.ServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping': Unexpected exception during bean creation; nested exception is java.lang.ExceptionInInitializerError
2022-05-03 12:31:46.925  INFO 4069 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2022-05-03 12:31:46.926 ERROR 4069 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping': Unexpected exception during bean creation; nested exception is java.lang.ExceptionInInitializerError
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:555) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[na:na]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[na:na]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[na:na]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) ~[webmvc-tomcat:2.6.6]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) ~[webmvc-tomcat:2.6.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[webmvc-tomcat:2.6.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[webmvc-tomcat:2.6.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[webmvc-tomcat:2.6.6]
        at com.example.webmvc.WebmvcApplication.main(WebmvcApplication.java:12) ~[webmvc-tomcat:0.0.1-SNAPSHOT]
Caused by: java.lang.ExceptionInInitializerError: null
        at java.lang.Class.ensureInitialized(DynamicHub.java:510) ~[webmvc-tomcat:na]
        at java.lang.Class.ensureInitialized(DynamicHub.java:510) ~[webmvc-tomcat:na]
        at org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.createRequestMappingHandlerMapping(WebMvcConfigurationSupport.java:351) ~[webmvc-tomcat:5.3.18]
        at org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration.createRequestMappingHandlerMapping(WebMvcAutoConfiguration.java:543) ~[webmvc-tomcat:2.6.6]
        at org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.requestMappingHandlerMapping(WebMvcConfigurationSupport.java:311) ~[webmvc-tomcat:5.3.18]
        at org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration.requestMappingHandlerMapping(WebMvcAutoConfiguration.java:445) ~[webmvc-tomcat:2.6.6]
        at org.springframework.aot.ContextBootstrapInitializer.lambda$initialize$23(ContextBootstrapInitializer.java:174) ~[na:na]
        at org.springframework.aot.beans.factory.BeanDefinitionRegistrar$ThrowableFunction.apply(BeanDefinitionRegistrar.java:294) ~[na:na]
        at org.springframework.aot.beans.factory.InjectedElementResolver.create(InjectedElementResolver.java:67) ~[na:na]
        at org.springframework.aot.beans.factory.BeanDefinitionRegistrar$BeanInstanceContext.create(BeanDefinitionRegistrar.java:211) ~[na:na]
        at org.springframework.aot.ContextBootstrapInitializer.lambda$initialize$24(ContextBootstrapInitializer.java:174) ~[na:na]
        at org.springframework.aot.beans.factory.BeanDefinitionRegistrar$ThrowableFunction.apply(BeanDefinitionRegistrar.java:294) ~[na:na]
        at org.springframework.aot.beans.factory.BeanDefinitionRegistrar.lambda$instanceSupplier$0(BeanDefinitionRegistrar.java:115) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1249) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1191) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[na:na]
        ... 14 common frames omitted
Caused by: java.lang.IllegalStateException: Expected method not found: java.lang.NoSuchMethodException: org.springframework.web.servlet.handler.AbstractHandlerMethodMapping$EmptyHandler.handle()
        at org.springframework.util.ClassUtils.getMethod(ClassUtils.java:1141) ~[na:na]
        at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.<clinit>(AbstractHandlerMethodMapping.java:84) ~[na:na]
        ... 31 common frames omitted

FAILURE: the output of the application does not contain the expected output
Timeout of 30 seconds reached. Unable to find 'Hello from Spring MVC and Tomcat' in 'localhost:8080/'
Timeout of 30 seconds reached. Unable to find 'Foo' in 'localhost:8080/foo.html'
Timeout of 30 seconds reached. Unable to find 'Bar' in 'localhost:8080/bar.html'
Timeout of 30 seconds reached. Unable to find 'Native' in POST 'localhost:8080/echo'
Did not kill process, it ended on it's own

```

**Comment by oubidar-Abderrahim** [comment]
Tracked internally on GR--38563

**Comment by christianwimmer** [comment]
@sdeleuze Yes, currently method inlining before analysis is not supported when a Truffle language is in the image. This requires a pretty big rewrite of how we compile the deoptimization entry points. We know how to do it, but just did not have the time yet to get it implemented.

So the main question is: how important is that for you? Do you have use cases where you want to integrate JavaScript into Spring applications?

**Comment by michelu89** [comment]
@christianwimmer There is a Java library GraphViz that creates diagrams using a Javascript engine and this could live in a Spring project. 

There could be several use-cases to generate a graph in your application. Imagine all the applications that want to have a pie chart from tables or similar things.

**Comment by sdeleuze** [comment]
@christianwimmer I guess there are some use cases like the one mentioned by @michelu89. Concretly, the impact is that Spring Boot 3 will document that `--language:js` is not supported due to this issue.

**Comment by christianwimmer** [comment]
I have this issue on the list to be addressed over the next months, I hope we get it done for the 22.3 release in fall.

**Comment by sdeleuze** [comment]
This issue is still pending and prevents any Spring Boot 3 application to enable the language support, see https://github.com/eregon/truffleruby-embed-spring. Any chance you could remove this limitation?

**Comment by teshull** [comment]
We are actively working on removing this limitation, but it requires many changes. I'll post an update here when InlineBeforeAnalysis is compatible with Truffle languages

**Comment by samuelAndalon** [comment]
just faced the same problem, currently trying the js support in a native image with Spring Boot 3

**Comment by sdeleuze** [comment]
Any chance to fix that in next major release?

**Comment by otcyury** [comment]
Will --language:js use with native build work with latest Quarkus based apps?

**Comment by oliveryasuna** [comment]
Facing this problem with `--language:python` in GraalVM 22.3.r17-grl.

**Comment by nsoubelet** [comment]
Hello @christianwimmer, based on the lack of activity for almost a year, I understand that this was not fixed yet nor you're planning to include a fix soon.
Is that correct?

**Comment by teshull** [comment]
Hi, with the release of 23.1, InlineBeforeAnalysis is compatible with Truffle languages.
