### ISSUE TITLE
[windows] NullPointerException: Cannot invoke "AllInstantiatedTypeFlow.addState(PointsToAnalysis, TypeState)" because "t.instantiatedTypes" is null

### ISSUE THREAD

**Issue by st4s1k** [oracle/graal#4476]
I'm not sure if this is a GraalVM issue or Gluon issue, sorry.
I get a NPE when trying to build the project. It appeared after I tried to integrate spring-boot into the project. I had other issues which I fixed by creating this file `resources/META-INF/substrate/config/initbuildtime` but then the current issue appeared.

### Expected Behavior
The build should not throw a NPE

### Current Behavior
The build throws a NPE
```
[Mon Apr 04 00:56:12 EEST 2022][INFO] [SUB] [3/7] Building universe...                                                                               (4.9s @ 5.67GB)
[Mon Apr 04 00:56:19 EEST 2022][INFO] [SUB] [4/7] Parsing methods...      [***]                                                                      (6.5s @ 2.94GB)
[Mon Apr 04 00:56:28 EEST 2022][INFO] [SUB] [5/7] Inlining methods...     [*****]                                                                    (8.1s @ 2.83GB)
[Mon Apr 04 00:56:59 EEST 2022][INFO] [SUB] [6/7] Compiling methods...    [*****]                                                                   (31.1s @ 4.27GB)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB] [7/7] Creating image...
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB] Fatal error: com.oracle.svm.core.util.VMError$HostedError: java.lang.NullPointerException: Cannot invoke "com.oracle.graal.pointsto.flow.AllInstantiatedTypeFlow.addState(com.oracle.graal.pointsto.PointsToAnalysis, com.oracle.graal.pointsto.typestate.TypeState)" because "t.instantiatedTypes" is null
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:72)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:656)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:494)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:426)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:587)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:126)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:617)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB] Caused by: java.lang.NullPointerException: Cannot invoke "com.oracle.graal.pointsto.flow.AllInstantiatedTypeFlow.addState(com.oracle.graal.pointsto.PointsToAnalysis, com.oracle.graal.pointsto.typestate.TypeState)" because "t.instantiatedTypes" is null
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.graal.pointsto.meta.AnalysisType.lambda$registerAsInstantiated$4(AnalysisType.java:443)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.graal.pointsto.meta.AnalysisType.forAllSuperTypes(AnalysisType.java:526)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.graal.pointsto.meta.AnalysisType.forAllSuperTypes(AnalysisType.java:512)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.graal.pointsto.meta.AnalysisType.forAllSuperTypes(AnalysisType.java:508)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.graal.pointsto.meta.AnalysisType.registerAsInstantiated(AnalysisType.java:442)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.graal.pointsto.meta.AnalysisType.registerAsAllocated(AnalysisType.java:425)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.graal.pointsto.meta.AnalysisType.markReachable(AnalysisType.java:482)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.graal.pointsto.meta.AnalysisType.forAllSuperTypes(AnalysisType.java:526)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.graal.pointsto.meta.AnalysisType.forAllSuperTypes(AnalysisType.java:512)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.graal.pointsto.meta.AnalysisType.forAllSuperTypes(AnalysisType.java:508)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.graal.pointsto.meta.AnalysisType.registerAsReachable(AnalysisType.java:466)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.registerAsReachable(AnalysisConstantReflectionProvider.java:290)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.ameta.HostedDynamicHubFeature.replace(HostedDynamicHubFeature.java:53)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:575)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.image.NativeImageHeap.addArrayElements(NativeImageHeap.java:576)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.image.NativeImageHeap.addObjectToImageHeap(NativeImageHeap.java:473)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.image.NativeImageHeap.addObject(NativeImageHeap.java:295)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.image.NativeImageHeap.processAddObjectWorklist(NativeImageHeap.java:598)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.image.NativeImageHeap.addTrailingObjects(NativeImageHeap.java:198)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:638)
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]     ... 5 more
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB] ------------------------------------------------------------------------------------------------------------------------
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]                        22.0s (13.9% of total time) in 101 GCs | Peak RSS: 9.66GB | CPU load: 6.92
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB] ------------------------------------------------------------------------------------------------------------------------
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB] Produced artifacts:
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB]  D:\MEGA\Plutus\DEV\LeagueTeamComp\target\gluonfx\x86_64-windows\gvm\LeagueTeamComp\com.st4s1k.leagueteamcomp.leagueteamcompapplication.build_artifacts.txt
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB] ========================================================================================================================
[Mon Apr 04 00:57:05 EEST 2022][INFO] [SUB] Failed generating 'com.st4s1k.leagueteamcomp.leagueteamcompapplication' after 2m 37s.
[Mon Apr 04 00:57:07 EEST 2022][INFO] [SUB] Error: Image build request failed with exit status 1
[Mon Apr 04 00:57:07 EEST 2022][INFO] [SUB] com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
[Mon Apr 04 00:57:07 EEST 2022][INFO] [SUB]     at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1770)
[Mon Apr 04 00:57:07 EEST 2022][INFO] [SUB]     at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1477)
[Mon Apr 04 00:57:07 EEST 2022][INFO] [SUB]     at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1438)
[Mon Apr 04 00:57:07 EEST 2022][INFO] [SUB]     at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1425)
[Mon Apr 04 00:57:07 EEST 2022][FINE] Result for compile: 1
[Mon Apr 04 00:57:07 EEST 2022][SEVERE] Process compile failed with result: 1
```

### Steps to Reproduce
1. checkout this branch https://github.com/st4s1k/League-of-Legends-Team-Composition-Tool/tree/spring-framework-integration
2. `mvn clean gluonfx:runagent gluonfx:build`

### My Environment
**Platform:** Windows 11
**JDK:** 17
**GraalVM:** graalvm-svm-java17-windows-gluon-22.0.0.3-Final

**Comment by st4s1k** [comment]
The only thing that pops up in google is this: https://build-native-java-apps.cc/developer-guide/debug-native-image-generation/

**Comment by st4s1k** [comment]
I cannot debug GraalVM classes because they are not accessible to me. Maybe there is a way to debug this but I don't know how. When you google `Fatal error: com.oracle.svm.core.util.VMError$HostedError: java.lang.NullPointerException: Cannot invoke "com.oracle.graal.pointsto.flow.AllInstantiatedTypeFlow.addState(com.oracle.graal.pointsto.PointsToAnalysis, com.oracle.graal.pointsto.typestate.TypeState)" because "t.instantiatedTypes" is null` you literally get 1 (one) search result.

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reporting this we will take a look into it and get back to you

**Comment by oubidar-Abderrahim** [comment]
If this issue is still relevant in the latest GraalVM versions with the latest springboot, please create a new issue for it and follow the template provided. Thank you
