### ISSUE TITLE
native-image error ,why?

### ISSUE THREAD

**Issue by zhangyajie4396** [oracle/graal#4499]
Found #15 types in static reflection list to register
[com.luter.graalvmdemo.graalvmdemoapplication:6808]        setup:   1,905.12 ms,  2.25 GB
Fatal error:java.lang.NoSuchMethodError: com.oracle.svm.hosted.config.ReflectionRegistryAdapter.resolveType(Ljava/lang/String;)Ljava/lang/Class;
	at org.springframework.graalvm.support.ReflectionHandler.register(ReflectionHandler.java:215)
	at org.springframework.graalvm.support.SpringFeature.duringSetup(SpringFeature.java:87)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$17(NativeImageGenerator.java:872)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:73)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:872)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:527)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
[com.luter.graalvmdemo.graalvmdemoapplication:6808]      [total]:  12,691.05 ms,  2.25 GB
# Printing build artifacts to: /usr/local/graalvm/native-image/graalvm-demo-master/target/com.luter.graalvmdemo.graalvmdemoapplication.build_artifacts.txt
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  24.537 s
[INFO] Finished at: 2022-04-21T19:31:18+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.graalvm.nativeimage:native-image-maven-plugin:20.3.1:native-image (default) on project graalvm-demo: Execution of /u

**Comment by oubidar-Abderrahim** [comment]
Hi, could you please create a new issue following our template and provide a clear description, stacktrace, details about the environment used to run this, and a reproducer for the issue?

**Comment by oubidar-Abderrahim** [comment]
Closed for unclarity
