### ISSUE TITLE
Executing image built using `language:js` flag throws an exception

### ISSUE THREAD

**Issue by david-pe** [oracle/graal#4507]
Executing image built without using the `language:js` flag executes fine. When the flag is used to build the image I get `int is not a value type` when executing.

**Steps to reproduce the issue**
1. **git clone --depth 1 https://github.com/david-pe/graalvm-failing-native-image**
2. **follow the step in the readme**

**GraalVM and environment:**
 -  ***openjdk 11.0.14 2022-01-18
    OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 11.0.14+9-jvmci-22.0-b05)
    OpenJDK 64-Bit Server VM GraalVM CE 22.0.0.2 (build 11.0.14+9-jvmci-22.0-b05, mixed mode, sharing)***
 - OS: **macOS Monterey 12.3**
 - Architecture: **Intel**

**run phase stacktrace**
```
    Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.openjdk.jmh.runner.options.CommandLineOptions.<init>(CommandLineOptions.java:99)
        at org.openjdk.jmh.Main.main(Main.java:41)
Caused by: java.lang.IllegalArgumentException: int is not a value type
        at joptsimple.internal.Reflection.findConverter(Reflection.java:66)
        at org.openjdk.jmh.runner.options.IntegerValueConverter.<clinit>(IntegerValueConverter.java:35)
        ... 2 more

```

**Comment by chumer** [comment]
I did some digging and this is actually not a problem related to the `--language:js` flag as I originally suspected.
When building your native image I think you overlooked the following output:

> Warning: Image 'benchmark_deploy' is a fallback image that requires a JDK for execution (use --no-fallback to suppress fallback image generation and to print more detailed information why a fallback image was necessary).

So when running the image it did not actually run in a native image but in a fallback image. Read more about it here:
https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/Limitations.md

This is what makes the difference. With `--language:js` we implicitly apply `--no-fallback`.
Building with:
```
native-image -jar bazel-bin/org/graaljs_formatter/benchmarks/benchmark_deploy.jar --no-fallback
```
And running the image leads to the same error. Namely:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.openjdk.jmh.runner.options.CommandLineOptions.<init>(CommandLineOptions.java:99)
	at org.openjdk.jmh.Main.main(Main.java:41)
Caused by: java.lang.IllegalArgumentException: int is not a value type
	at joptsimple.internal.Reflection.findConverter(Reflection.java:66)
	at org.openjdk.jmh.runner.options.IntegerValueConverter.<clinit>(IntegerValueConverter.java:35)
	... 2 more
```

Looking deeper there is `at joptsimple.internal.Reflection.findConverter(Reflection.java:66)` on the stack which uses reflection. So my guess is that there is a missing reflection configuration.

I suggest following this guide to get to a reflection configuration:
https://www.graalvm.org/22.0/reference-manual/native-image/Agent/

And then retry. Please close if that resolves your issue.

**Comment by fernando-valdez** [comment]
Thank you Christian for your response. I am closing this ticket as there hasn't been any feedback in any months
