### ISSUE TITLE
Non-public classes inherit HostAccess annotations from interfaces

### ISSUE THREAD

**Issue by mikethayes** [oracle/graal#4519]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **22.0.0.2**
 - CE or EE: **EE**
 - JDK version: **JDK17**
 - OS and OS Version: **[e.g.: macOS Catalina]**
 - Architecture: **[e.g.: amd64]**
 - The output of `java -Xinternalversion`: 
```
 **Java HotSpot(TM) 64-Bit Server VM (17.0.2+8-LTS-jvmci-22.0-b05) for bsd-amd64 JRE (17.0.2+8-LTS-jvmci-22.0-b05), built on Jan 20 2022 01:28:35 by "graal2" with clang Apple LLVM 12.0.0 (clang-1200.0.32.29)**
```

**Have you verified this issue still happens when using the latest snapshot?** YES

**Describe the issue**
(This issue originally arose when trying to figure out how to @Export members of a Java14 record so records are used in the example/description, but I have verified that this applies to classes as well)

In some circumstances non-public classes inherit HostAccess annotations from interfaces. 

Annotate a method of an interface with @Export
Create an inner class/record that implements that interface. *Do not* annotate the implemented method with @Export.
Bind an instance of the class/record to a context and try to access the annotated method - the method will not be visible on the bound object
However, if you make the class non public (package or private scope) you will be able to access the @Export annotated method

The expected behaviour is that @Export should *not* be inherited under any circumstances - items should only be explicitly exported.

**Code snippet or code repository that reproduces the issue**
```
import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.HostAccess;
import org.graalvm.polyglot.HostAccess.Export;

public class RecordTest {

    public interface PointInterface {
        @Export
        public int x();

        @Export
        public int y();
    }

    public record PublicPoint(int x, int y) implements PointInterface {
    }

    private record NonPublicPoint(int x, int y) implements PointInterface {
    }

    public static void main(String[] args) throws NoSuchMethodException {
        PublicPoint publicPoint = new PublicPoint(6, 7);
        NonPublicPoint nonPublicPoint = new NonPublicPoint(7, 6);

        System.out.println("Using public record with EXPLICIT hostaccess will fail...");
        runWithAccess(publicPoint, HostAccess.EXPLICIT);

        System.out.println("Using non-public record with EXPLICIT hostaccess will succeed...");
        runWithAccess(nonPublicPoint, HostAccess.EXPLICIT);
    }

    private static void runWithAccess(final PointInterface point, final HostAccess customAccess) {
        try (Context context = Context.newBuilder()
                .allowHostAccess(customAccess)
                .build()) {
            final var code = "p => console.log(p.x(), p.y())";
            context.eval("js", code).execute(point);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
    }
}
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Compile the class above and run it from the main() method 

**Expected behavior**
@Export gets inherited when the inner class is non-public. This should not happen.

**Additional context**
As already mentioned this came up in the context of trying to provide explicit access to java 14 record members. While the example works using records, I did check for the same behaviour using regular classes and interfaces. Jan suggested this bug may arise in [HostClassDesc.java](https://github.com/oracle/graal/blob/master/truffle/src/com.oracle.truffle.host/src/com/oracle/truffle/host/HostClassDesc.java)
<details><summary>Details</summary>

```
TypeError: invokeMember (x) on com.oracle.dx4c.inter.RecordTest$PublicPoint@4b20ca2b failed due to: Unknown identifier: x
	at <js> :=>(Unnamed:1:17-21)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.execute(Value.java:841)
	at com.oracle.dx4c.inter.RecordTest.runWithAccess(RecordTest.java:39)
	at com.oracle.dx4c.inter.RecordTest.main(RecordTest.java:28)
```
</details>

**Comment by chumer** [comment]
Given that example I think we should support:
```
public record PublicPoint(@Export int x, @Export int y) implements PointInterface {
    }
```

**Comment by woess** [comment]
Should be fixed as of https://github.com/oracle/graal/commit/5bbbd17acc4f3d44a8aa708b4d8348f9dad281ad.
