### ISSUE TITLE
Java Native image crashes at runtime with UnsatisfiedLinkError: no attach in java.library.path

### ISSUE THREAD

**Issue by Reason94** [oracle/graal#4562]
**Describe the issue**
The java native image crashes when calling VirtualMachine.attach.
```
java.lang.UnsatisfiedLinkError: no attach in java.library.path
	at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryRelative(NativeLibrarySupport.java:132)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:135)
	at java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.lang.System.loadLibrary(System.java:1871)
	at sun.tools.attach.VirtualMachineImpl.<clinit>(VirtualMachineImpl.java:374)
	at sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:58)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
	at mainApp.AgentBootstrap.testAttach(AgentBootstrap.java:21)
	at mainApp.AgentBootstrap.run(AgentBootstrap.java:14)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:777)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
	at mainApp.Test.main(Test.java:10)
```

**Steps to reproduce the issue**
1. Create new Spring Boot Application, code is below
```
@SpringBootApplication
public class Test {
    public static void main(String[] args){
        SpringApplication.run(Test.class, args);
    }

}

@Component
public class AgentBootstrap implements CommandLineRunner {

    @Override
    public void run(String... args) throws Exception {
        System.out.println("AgentBootstrap --- ");
        testAttach(args);
    }
    public void testAttach(String[] args) {

        try {
            System.out.println(System.getProperty("java.library.path"));
            System.out.println("Pid " + args[0]);
            VirtualMachine virtualMachine = VirtualMachine.attach(args[0]);
            virtualMachine.loadAgent(args[1], "cxs");
            System.out.println("ok");
            virtualMachine.detach();
        } catch (Throwable e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
    }
}

```
2. maven pom.xml
```
<dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.experimental</groupId>
            <artifactId>spring-native</artifactId>
            <version>0.11.4</version>
        </dependency>
 </dependencies>

<build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                    <encoding>utf-8</encoding>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.graalvm.buildtools</groupId>
                <artifactId>native-maven-plugin</artifactId>
                <version>0.9.11</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <id>build-native</id>
                        <goals>
                            <goal>build</goal>
                        </goals>
                        <phase>package</phase>
                    </execution>
                    <execution>
                        <id>test-native</id>
                        <goals>
                            <goal>test</goal>
                        </goals>
                        <phase>test</phase>
                    </execution>
                </executions>
                <configuration>
                    <!-- ... -->
                </configuration>
            </plugin>
            <!-- Avoid a clash between Spring Boot repackaging and native-maven-plugin -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <classifier>exec</classifier>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.springframework.experimental</groupId>
                <artifactId>spring-aot-maven-plugin</artifactId>
                <version>0.11.4</version>
                <executions>
                    <execution>
                        <id>test-generate</id>
                        <goals>
                            <goal>test-generate</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>generate</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>

```
3.  mvn clean package

**Describe GraalVM and your environment**
 - GraalVM version : graalvm-ce-java11-22.0.0.2
 - JDK major version: 11
 - OS:  Linux
 - Architecture: Linux version 3.10.0-862.el7.x86_64

**More details**
To fix this problem we try to 
```
export LD_LIBRARY_PATH=path/to/your/library/dir/ (on Linux or OSX)
```
```
-Djava.library.path=<your-path>
```
both not work. How could we fix it.

**Comment by Reason94** [comment]
I found that spring aot plugin doesn't generate jni-config.json by default. I try to generate jni-config.json with -agentlib and add to META-INF/native-image/ but still not work

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, we will take a look into it and get back to you

**Comment by saugion** [comment]
any news on this? I have the same issue with awt, thus i see the built image contains the needed files:
Produced artifacts: /layers/paketo-buildpacks_native-image/native-image/libawt_headless.so

**Comment by oubidar-Abderrahim** [comment]
Hi, please verify if the issue is still reproducible using the latest Oracle GraalVM (23.0.x or 23.1.x), if it does, please reopen or create a new issue and share a complete reproducer. Thank you
