### ISSUE TITLE
[GR-38663] Possible NullPointerException in ReflectionDataBuilder on buildRecordComponents

### ISSUE THREAD

**Issue by JohnAEX** [oracle/graal#4566]
**Describe the issue**
Under certain conditions, the RecordSupport Singleton within the ReflectionDataBuilder returns an array of non 0 size with a set of null entries when getRecordComponentAccessorMethods(clazz) is called. Null entries in the array lead to a NullPointer within the !reflectionMethods.containsKey(method) call. 

**Steps to reproduce the issue**
@fniephaus has access to reproducing the issue

**Describe GraalVM and your environment:**
 - GraalVM version 22.1
 - JDK major version: 17
 - OS: Ubuntu 20.04.1
 - Architecture: x86_64

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
    Fatal error: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at java.base/java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964)
	at com.oracle.svm.reflect.hosted.ReflectionDataBuilder.buildRecordComponents(ReflectionDataBuilder.java:733)
	at com.oracle.svm.reflect.hosted.ReflectionDataBuilder.registerTypesForClass(ReflectionDataBuilder.java:426)
	at com.oracle.svm.reflect.hosted.ReflectionDataBuilder.processMethodMetadata(ReflectionDataBuilder.java:265)
	at com.oracle.svm.reflect.hosted.ReflectionDataBuilder.duringAnalysis(ReflectionDataBuilder.java:185)
	at com.oracle.svm.reflect.hosted.ReflectionFeature.duringAnalysis(ReflectionFeature.java:189)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$10(NativeImageGenerator.java:726)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:74)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$11(NativeImageGenerator.java:726)
	at com.oracle.graal.pointsto.PointsToAnalysis.runAnalysis(PointsToAnalysis.java:751)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:723)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:558)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:515)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:615)
```

**Comment by fniephaus** [comment]
Thank you, @JohnAEX. We'll look into it.

**Comment by fniephaus** [comment]
https://github.com/oracle/graal/commit/8535148552c90a9020b8797c7a86ebcfae909f92 just landed on `master` and should fix the issue. Please re-open if the issue persists. Thanks!

**Comment by andrejusc** [comment]
@fniephaus - is there some timeline when such will be available via some 22.1 patch? I'm facing same today as well.

**Comment by fniephaus** [comment]
Hi @andrejusc, the patch will ship with 22.2, the next release of GraalVM. In the meantime, you can try a recent dev build, which should contain the patch.

**Comment by andrejusc** [comment]
Hi @fniephaus - should I take some dev build from this area: https://github.com/graalvm/graalvm-ce-dev-builds/releases ? Quick search over first page doesn't provide back link to mentioned above commit 8535148. And commit itself https://github.com/oracle/graal/commit/8535148552c90a9020b8797c7a86ebcfae909f92 is not tagged with any Dev build tag. Unless I'm missing that in some field in UI.

**Comment by fniephaus** [comment]
Yes, the latest dev build is based on https://github.com/oracle/graal/commit/61965329ce80df9659c3d592cfff0d79e0bdf76d (see GitHub release text) and should therefore include the patch. We don't provide builds of GraalVM for every commit. That would waste a lot of resources.
