### ISSUE TITLE
[native-image]Can't load '.so' files after GraalVM native image

### ISSUE THREAD

**Issue by cyw3** [oracle/graal#4579]
**Describe the issue**
1. When I use [sqlite-jdbc-crypt](https://github.com/Willena/sqlite-jdbc-crypt) in java or Jar, it works.

2. After I build Jar file to Native executor file with graalvm, I got the error below:
```bash
java.lang.UnsatisfiedLinkError: Can't load library: /tmp/sqlite-3.36.0-47497685-3d26-429d-9f26-9ac89d7a3e1d-libsqlitejdbc.so
Exception in thread "main" java.sql.SQLException: Error opening connection
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:257)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:60)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:23)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
        at org.sqlite.JDBC.createConnection(JDBC.java:104)
        at org.sqlite.SQLiteDataSource.getConnection(SQLiteDataSource.java:450)
        at org.sqlite.SQLiteDataSource.getConnection(SQLiteDataSource.java:442)
        at com.mageddo.sqlite.App.main(App.java:19)
Caused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=x86_64, paths=[/org/sqlite/native/Linux/x86_64]
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:391)
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:65)
        at org.sqlite.core.NativeDB.load(NativeDB.java:56)
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:254)
        ... 7 more
```

3. When I use System.load after graal, I get the same error.

```java
try {
	System.load("/data/xxx/libsqlitejdbc.so");
} catch (UnsatisfiedLinkError e) {
	System.err.println(e);
}
```

**Steps to reproduce the issue**

You can change this line of the demo project to reproduce the error.
https://github.com/mageddo/graalvm-examples/blob/master/sqlite/build.gradle#L14

```
implementation("io.github.willena:sqlite-jdbc:3.36.0")
```
while `implementation("org.xerial:sqlite-jdbc:3.36.0")`.

**Describe GraalVM and your environment:**
 - GraalVM version: GraalVM CE 20.3.0
 - JDK major version: 11.0.9
 - OS: centOS7
 - Architecture: x86_64

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
> compiling binary
Apply jar:file:///data/graalvm-examples/sqlite/build/libs/sqlite-all.jar!/META-INF/native-image/org.graalvm.polyglot/native-image.properties
Apply jar:file:///data/graalvm-examples/sqlite/build/libs/sqlite-all.jar!/META-INF/native-image/org.graalvm.home/native-image.properties
Apply jar:file:///data/graalvm-examples/sqlite/build/libs/sqlite-all.jar!/META-INF/native-image/io.github.willena/sqlite-jdbc/native-image.properties
Apply jar:file:///data/graalvm-examples/sqlite/build/libs/sqlite-all.jar!/META-INF/native-image/sqlite/native-image.properties
Apply jar:file:///data/graalvm-examples/sqlite/build/libs/sqlite-all.jar!/META-INF/native-image/io.github.willena/sqlite-jdbc/jni-config.json
Apply jar:file:///data/graalvm-examples/sqlite/build/libs/sqlite-all.jar!/META-INF/native-image/io.github.willena/sqlite-jdbc/reflect-config.json
Apply jar:file:///data/graalvm-examples/sqlite/build/libs/sqlite-all.jar!/META-INF/native-image/io.github.willena/sqlite-jdbc/resource-config.json
Executing [
/data/App/graal-jdk11-20.3.0/bin/java \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.site=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.stack=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.common=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.sparc=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.runtime=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.services=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.sparc=ALL-UNNAMED \
--add-exports=org.graalvm.truffle/com.oracle.truffle.api=ALL-UNNAMED \
--add-opens=jdk.internal.vm.compiler/org.graalvm.compiler.debug=ALL-UNNAMED \
--add-opens=jdk.internal.vm.compiler/org.graalvm.compiler.nodes=ALL-UNNAMED \
--add-opens=jdk.unsupported/sun.reflect=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.module=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.ref=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.reflect=ALL-UNNAMED \
--add-opens=java.base/java.io=ALL-UNNAMED \
--add-opens=java.base/java.lang=ALL-UNNAMED \
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED \
--add-opens=java.base/java.lang.invoke=ALL-UNNAMED \
--add-opens=java.base/java.lang.ref=ALL-UNNAMED \
--add-opens=java.base/java.net=ALL-UNNAMED \
--add-opens=java.base/java.nio=ALL-UNNAMED \
--add-opens=java.base/java.nio.file=ALL-UNNAMED \
--add-opens=java.base/java.security=ALL-UNNAMED \
--add-opens=java.base/javax.crypto=ALL-UNNAMED \
--add-opens=java.base/java.util=ALL-UNNAMED \
--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED \
--add-opens=java.base/sun.security.x509=ALL-UNNAMED \
--add-opens=java.base/jdk.internal.logger=ALL-UNNAMED \
--add-opens=java.desktop/sun.java2d.cmm.profiles=ALL-UNNAMED \
--add-opens=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED \
--add-opens=org.graalvm.sdk/org.graalvm.polyglot=ALL-UNNAMED \
--add-opens=org.graalvm.truffle/com.oracle.truffle.polyglot=ALL-UNNAMED \
--add-opens=org.graalvm.truffle/com.oracle.truffle.api.impl=ALL-UNNAMED \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx14g \
-Duser.country=US \
-Duser.language=en \
-Djava.awt.headless=true \
-Dorg.graalvm.version=20.3.0 \
-Dorg.graalvm.config= \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
--module-path \
/data/App/graal-jdk11-20.3.0/lib/truffle/truffle-api.jar \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-Dfile.encoding=UTF-8 \
-javaagent:/data/App/graal-jdk11-20.3.0/lib/svm/builder/svm.jar \
-cp \
/data/App/graal-jdk11-20.3.0/lib/svm/builder/llvm-wrapper-shadowed.jar:/data/App/graal-jdk11-20.3.0/lib/svm/builder/svm.jar:/data/App/graal-jdk11-20.3.0/lib/svm/builder/javacpp-shadowed.jar:/data/App/graal-jdk11-20.3.0/lib/svm/builder/llvm-platform-specific-shadowed.jar:/data/App/graal-jdk11-20.3.0/lib/svm/builder/svm-llvm.jar:/data/App/graal-jdk11-20.3.0/lib/svm/builder/objectfile.jar:/data/App/graal-jdk11-20.3.0/lib/svm/builder/pointsto.jar \
'com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus' \
-watchpid \
24597 \
-imagecp \
/data/App/graal-jdk11-20.3.0/lib/svm/library-support.jar:/data/graalvm-examples/sqlite/build/libs/sqlite-all.jar \
-H:Name=sqlite \
-H:Optimize=0 \
-H:-DeoptimizeAll \
-H:+CompileGraalWithC1Only \
-H:+JNI \
-H:+NativeArchitecture \
-H:-RemoveNeverExecutedCode \
-R:-RemoveNeverExecutedCode \
-H:-RemoveUnusedSymbols \
-H:-RemoveSaturatedTypeFlows \
-R:-RemoveSaturatedTypeFlows \
-H:+AllowVMInspection \
-H:+AllowFoldMethods \
-H:+AddAllCharsets \
-H:+AllowIncompleteClasspath \
-H:+DumpTargetInfo \
-H:ClassInitialization=org.graalvm.polyglot:build_time \
-H:Features=org.graalvm.home.HomeFinderFeature \
-H:FallbackThreshold=0 \
-H:Class=com.mageddo.sqlite.App \
'-H:IncludeResources=db/.*|static/.*|templates/.*|.*.yml|.*.xml|.*/org/sqlite/.*|org/sqlite/.*' \
-H:JNIConfigurationResources=META-INF/native-image/io.github.willena/sqlite-jdbc/jni-config.json \
-H:ReflectionConfigurationResources=META-INF/native-image/io.github.willena/sqlite-jdbc/reflect-config.json \
-H:ResourceConfigurationResources=META-INF/native-image/io.github.willena/sqlite-jdbc/resource-config.json \
-H:CLibraryPath=/data/App/graal-jdk11-20.3.0/lib/svm/clibraries/linux-amd64 \
-H:Path=/data/graalvm-examples/sqlite/build/graal \

]
[sqlite:24619]    classlist:   1,066.33 ms,  0.96 GB
[sqlite:24619]        (cap):     484.04 ms,  0.96 GB
[sqlite:24619]        setup:   1,655.95 ms,  0.96 GB
> Loading classes for future reflection support
> Declaring class: org.sqlite.core.NativeDB
        > method: busy_handler([class org.sqlite.BusyHandler])
        > method: errmsg([])
        > method: changes([])
        > method: total_changes([])
        > method: shared_cache([boolean])
        > method: enable_load_extension([boolean])
        > method: _open([class java.lang.String, int])
        > method: _close([])
        > method: _exec([class java.lang.String])
        > method: clear_bindings([long])
        > method: bind_parameter_count([long])
        > method: column_count([long])
        > method: column_type([long, int])
        > method: column_decltype([long, int])
        > method: column_table_name([long, int])
        > method: column_name([long, int])
        > method: column_text([long, int])
        > method: column_blob([long, int])
        > method: column_double([long, int])
        > method: column_long([long, int])
        > method: column_int([long, int])
        > method: bind_null([long, int])
        > method: bind_int([long, int, int])
        > method: bind_long([long, int, long])
        > method: bind_double([long, int, double])
        > method: bind_text([long, int, class java.lang.String])
        > method: bind_blob([long, int, class [B])
        > method: result_null([long])
        > method: result_text([long, class java.lang.String])
        > method: result_blob([long, class [B])
        > method: result_double([long, double])
        > method: result_long([long, long])
        > method: result_int([long, int])
        > method: result_error([long, class java.lang.String])
        > method: value_text([class org.sqlite.Function, int])
        > method: value_blob([class org.sqlite.Function, int])
        > method: libversion([])
        > method: busy_timeout([int])
        > method: stringToUtf8ByteArray([class java.lang.String])
        > method: utf8ByteBufferToString([class java.nio.ByteBuffer])
        > method: value_double([class org.sqlite.Function, int])
        > method: value_long([class org.sqlite.Function, int])
        > method: value_int([class org.sqlite.Function, int])
        > method: value_type([class org.sqlite.Function, int])
        > method: create_function([class java.lang.String, class org.sqlite.Function, int, int])
        > method: destroy_function([class java.lang.String, int])
        > method: create_collation([class java.lang.String, class org.sqlite.Collation])
        > method: destroy_collation([class java.lang.String])
        > method: free_functions([])
        > method: register_progress_handler([int, class org.sqlite.ProgressHandler])
        > method: clear_progress_handler([])
        > method: column_metadata([long])
        > method: set_commit_listener([boolean])
        > method: set_update_listener([boolean])
        > method: throwex([class java.lang.String])
        > method: _open_utf8([class [B, int])
        > method: _exec_utf8([class [B])
        > method: prepare_utf8([class [B])
        > method: errmsg_utf8([])
        > method: libversion_utf8([])
        > method: column_decltype_utf8([long, int])
        > method: column_table_name_utf8([long, int])
        > method: column_name_utf8([long, int])
        > method: column_text_utf8([long, int])
        > method: bind_text_utf8([long, int, class [B])
        > method: result_text_utf8([long, class [B])
        > method: result_error_utf8([long, class [B])
        > method: value_text_utf8([class org.sqlite.Function, int])
        > method: create_function_utf8([class [B, class org.sqlite.Function, int, int])
        > method: destroy_function_utf8([class [B, int])
        > method: create_collation_utf8([class [B, class org.sqlite.Collation])
        > method: destroy_collation_utf8([class [B])
        > method: restore([class java.lang.String, class java.lang.String, interface org.sqlite.core.DB$ProgressObserver])
        > method: restore([class [B, class [B, interface org.sqlite.core.DB$ProgressObserver])
        > method: backup([class [B, class [B, interface org.sqlite.core.DB$ProgressObserver])
        > method: backup([class java.lang.String, class java.lang.String, interface org.sqlite.core.DB$ProgressObserver])
        > method: step([long])
        > method: finalize([long])
        > method: limit([int, int])
        > method: load([])
        > method: interrupt([])
        > method: prepare([class java.lang.String])
        > method: reset([long])
        > field: pointer
        > field: isLoaded
        > field: loadSucceeded
        > field: udfdatalist
        > field: colldatalist
        > constructor: org.sqlite.core.NativeDB(3)
> Declaring class: org.sqlite.Function
        > method: value_text([int])
        > method: value_blob([int])
        > method: value_double([int])
        > method: value_long([int])
        > method: value_int([int])
        > method: value_type([int])
        > method: xFunc([])
        > method: checkContext([])
        > method: checkValue([int])
        > method: result([long])
        > method: result([class [B])
        > method: result([class java.lang.String])
        > method: result([int])
        > method: result([double])
        > method: result([])
        > method: args([])
        > method: destroy([interface java.sql.Connection, class java.lang.String, int])
        > method: destroy([interface java.sql.Connection, class java.lang.String])
        > method: create([interface java.sql.Connection, class java.lang.String, class org.sqlite.Function])
        > method: create([interface java.sql.Connection, class java.lang.String, class org.sqlite.Function, int])
        > method: create([interface java.sql.Connection, class java.lang.String, class org.sqlite.Function, int, int])
        > method: error([class java.lang.String])
        > field: FLAG_DETERMINISTIC
        > field: conn
        > field: db
        > field: context
        > field: value
        > field: args
        > constructor: org.sqlite.Function(0)
> Declaring class: org.sqlite.Function.Aggregate
        > method: xStep([])
        > method: xFinal([])
        > method: xFunc([])
        > method: clone([])
        > constructor: org.sqlite.Function$Aggregate(0)
> Declaring class: org.sqlite.ProgressHandler
        > method: progress([])
        > method: setHandler([interface java.sql.Connection, int, class org.sqlite.ProgressHandler])
        > method: clearHandler([interface java.sql.Connection])
        > constructor: org.sqlite.ProgressHandler(0)
> Declaring class: org.sqlite.Function.Window
        > method: xInverse([])
        > method: xValue([])
        > constructor: org.sqlite.Function$Window(0)
> Declaring class: org.sqlite.core.DB.ProgressObserver
        > method: progress([int, int])
# Building image for target platform: org.graalvm.nativeimage.Platform$LINUX_AMD64
# Using native toolchain:
#   Name: GNU project C and C++ compiler (gcc)
#   Vendor: redhat
#   Version: 4.8.5
#   Target architecture: x86_64
#   Path: /usr/lib64/ccache/gcc
# Using CLibrary: com.oracle.svm.core.posix.linux.libc.GLibC
[sqlite:24619]     (clinit):     425.67 ms,  2.21 GB
# Static libraries:
#   ../../App/graal-jdk11-20.3.0/lib/svm/clibraries/linux-amd64/liblibchelper.a
#   ../../App/graal-jdk11-20.3.0/lib/static/linux-amd64/glibc/libnet.a
#   ../../App/graal-jdk11-20.3.0/lib/svm/clibraries/linux-amd64/libffi.a
#   ../../App/graal-jdk11-20.3.0/lib/static/linux-amd64/glibc/libnio.a
#   ../../App/graal-jdk11-20.3.0/lib/static/linux-amd64/glibc/libjava.a
#   ../../App/graal-jdk11-20.3.0/lib/static/linux-amd64/glibc/libfdlibm.a
#   ../../App/graal-jdk11-20.3.0/lib/static/linux-amd64/glibc/libzip.a
#   ../../App/graal-jdk11-20.3.0/lib/svm/clibraries/linux-amd64/libjvm.a
# Other libraries: pthread,dl,z,rt
[sqlite:24619]   (typeflow):  10,235.74 ms,  2.21 GB
[sqlite:24619]    (objects):  11,605.93 ms,  2.21 GB
[sqlite:24619]   (features):     841.04 ms,  2.21 GB
[sqlite:24619]     analysis:  23,689.29 ms,  2.21 GB
[sqlite:24619]     universe:     822.99 ms,  2.32 GB
[sqlite:24619]      (parse):   1,650.89 ms,  2.32 GB
[sqlite:24619]    (compile):  11,191.98 ms,  4.18 GB
[sqlite:24619]      compile:  14,108.41 ms,  4.18 GB
[sqlite:24619]        image:   5,087.63 ms,  4.52 GB
[sqlite:24619]        write:     452.13 ms,  4.52 GB
[sqlite:24619]      [total]:  48,268.14 ms,  4.52 GB
```

**Comment by cyw3** [comment]
https://github.com/Willena/sqlite-jdbc-crypt/issues/61

**Comment by cyw3** [comment]
I fixed it, but I don't know why.

https://github.com/Willena/sqlite-jdbc-crypt/pull/62

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reporting this, could you please clarify if you still facing this issue? and if yes, please use a more recent build of GraalVM (22.1.0 or 21.3.2)

**Comment by cyw3** [comment]
> 

I use GraalVM 22.1.0 and get the same error.

Now I fixed it, but I don't know why.
https://github.com/Willena/sqlite-jdbc-crypt/pull/62

**Comment by wirthi** [comment]
Closing this ticket, unclear if there is any problem on our side. Feel free to reopen if you can provide more insight.
