### ISSUE TITLE
Fails to run on macOS

### ISSUE THREAD

**Issue by vprelovac** [oracle/graal#4586]
**Describe the issue**
Fails to run on macOS using the latest dev release.

**Describe GraalVM and your environment:**
macOS 15.4, Intel

**More details**
graalpython-22.2.0-dev-macos-amd64 % ./bin/graalpython
ERROR: com.oracle.truffle.api.CompilerDirectives$ShouldNotReachHere: Unable to load native posix support library
org.graalvm.polyglot.PolyglotException: com.oracle.truffle.api.CompilerDirectives$ShouldNotReachHere: Unable to load native posix support library
	at com.oracle.truffle.api.CompilerDirectives.shouldNotReachHere(CompilerDirectives.java:570)
	at com.oracle.graal.python.runtime.NFIPosixSupport$InvokeNativeFunction.loadLibrary(NFIPosixSupport.java:370)
	at com.oracle.graal.python.runtime.NFIPosixSupport$InvokeNativeFunction.call(NFIPosixSupport.java:294)
	at com.oracle.graal.python.runtime.NFIPosixSupport$InvokeNativeFunction.callLong(NFIPosixSupport.java:309)
	at com.oracle.graal.python.runtime.NFIPosixSupport.lseek(NFIPosixSupport.java:615)
	at com.oracle.graal.python.runtime.NFIPosixSupportGen$PosixSupportLibraryExports$Uncached.lseek(NFIPosixSupportGen.java:3398)
	at com.oracle.graal.python.runtime.ImageBuildtimePosixSupport.lseek(ImageBuildtimePosixSupport.java:256)
	at com.oracle.graal.python.runtime.ImageBuildtimePosixSupportGen$PosixSupportLibraryExports$Uncached.lseek(ImageBuildtimePosixSupportGen.java:1335)
	at com.oracle.graal.python.runtime.PosixSupportLibraryGen$UncachedDispatch.lseek(PosixSupportLibraryGen.java:6048)
	at com.oracle.graal.python.builtins.modules.io.FileIOBuiltins$SeekNode.internalSeek(FileIOBuiltins.java:789)
	at com.oracle.graal.python.builtins.modules.io.FileIOBuiltins$TellNode.internalTell(FileIOBuiltins.java:814)
	at com.oracle.graal.python.builtins.modules.io.AbstractBufferedIOBuiltins$BufferedInitNode.internalInit(AbstractBufferedIOBuiltins.java:118)
	at com.oracle.graal.python.builtins.modules.io.BufferedReaderBuiltins$BufferedReaderInit.internalInit(BufferedReaderBuiltins.java:95)
	at com.oracle.graal.python.builtins.modules.SysModuleBuiltins.initStd(SysModuleBuiltins.java:598)
	at com.oracle.graal.python.builtins.modules.SysModuleBuiltins.postInitialize(SysModuleBuiltins.java:581)
	at com.oracle.graal.python.builtins.Python3Core.postInitialize(Python3Core.java:909)
	at com.oracle.graal.python.runtime.PythonContext.patch(PythonContext.java:1173)
	at com.oracle.graal.python.PythonLanguage.patchContext(PythonLanguage.java:315)
	at com.oracle.graal.python.PythonLanguage.patchContext(PythonLanguage.java:103)
	at com.oracle.truffle.api.LanguageAccessor$LanguageImpl.patchEnvContext(LanguageAccessor.java:419)
	at com.oracle.truffle.polyglot.PolyglotLanguageContext.patch(PolyglotLanguageContext.java:779)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.patch(PolyglotContextImpl.java:3178)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.loadPreinitializedContext(PolyglotEngineImpl.java:1827)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.createContext(PolyglotEngineImpl.java:1701)
	at com.oracle.truffle.polyglot.PolyglotEngineDispatch.createContext(PolyglotEngineDispatch.java:159)
	at org.graalvm.polyglot.Context$Builder.build(Context.java:1837)
	at com.oracle.graal.python.shell.GraalPythonMain.launch(GraalPythonMain.java:611)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:296)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:121)
	at com.oracle.graal.python.shell.GraalPythonMain.main(GraalPythonMain.java:71)
Caused by: java.lang.UnsatisfiedLinkError: dlopen(/Users/prelovac/Downloads/graalpython-22.2.0-dev-macos-amd64/lib-graalpython/libposix.graalpython-38-native-x86_64-darwin.dylib, 0x0006): tried: '/Users/prelovac/Downloads/graalpython-22.2.0-dev-macos-amd64/lib-graalpython/libposix.graalpython-38-native-x86_64-darwin.dylib' (code signature in <2A217037-95A1-33E4-B3AE-1C82C1A35981> '/Users/prelovac/Downloads/graalpython-22.2.0-dev-macos-amd64/lib-graalpython/libposix.graalpython-38-native-x86_64-darwin.dylib' not valid for use in process: library load disallowed by system policy)
Internal GraalVM error, please report at https://github.com/oracle/graal/issues/.

**Comment by vprelovac** [comment]
Quarantine issue, this should be somewhere in docs.

sudo xattr -r -d com.apple.quarantine graalpython-22.2.0-dev-macos-amd64
