### ISSUE TITLE
Value.asHostObject throwns ClassCastException instead of IllegalStateException

### ISSUE THREAD

**Issue by mikethayes** [oracle/graal#4589]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **17.0.2**
 - CE or EE: **EE**
 - JDK version: **JDK17**
 - OS and OS Version: **macOS Monterey**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`: 
```
 Java HotSpot(TM) 64-Bit Server VM (17.0.2+8-LTS-jvmci-22.0-b05) for bsd-amd64 JRE (17.0.2+8-LTS-jvmci-22.0-b05), built on Jan 20 2022 01:28:35 by "graal2" with clang Apple LLVM 12.0.0 (clang-1200.0.32.29)
```

**Have you verified this issue still happens when using the latest snapshot?**
Yes, the result is the same

**Describe the issue**
If you call Value.asHostObject on a non-host object a ClassCastException is thrown. The docs suggest it should be an IllegalStateException

**Code snippet or code repository that reproduces the issue**
```
public class TestIsHostObject {
    public static void main(String[] args) {
        try (Context context = Context.newBuilder().build()) {
            final var code = "x => x * x";
            Value value = context.eval("js", code);
            final var result = value.execute(5);
            System.out.println(result.isHostObject());
            final var y = result.asHostObject();
            System.out.println(y);
        } catch (ClassCastException e) {
            System.out.println("ClassCastException");
        } catch (UnsupportedOperationException e) {
            System.out.println("UnsupportedOperationException");
        } catch (IllegalStateException e) {
            System.out.println("IllegalStateException");
        } catch (PolyglotException e) {
            System.out.println("PolyglotException");
        }
    }
}
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Save code above to TestIsHostObject.java
2. Run `java TestIsHostObject.java` using graal 

**Expected behaviour**
The Value.isHostObject docs say that this should return an IllegalStateException, not a ClassCastException. So I expected a IllegalStateException. 

I know you should guard the call with an isHostObject() call anyway, but in my use case I was always expecting host objects so I avoided this step (until a guest object inadvertently got passed).

**Additional context**
Add any other context about the problem here. Specially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary
<details><summary>Details</summary>

```
java.lang.ClassCastException: Cannot convert '25'(language: Java, type: java.lang.Integer)  using Value.asHostObject(): Value is not a host object. You can ensure that the value can be converted using Value.isHostObject().
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineException.classCast(PolyglotEngineException.java:145)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch.cannotConvert(PolyglotValueDispatch.java:1350)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch.asHostObjectUnsupported(PolyglotValueDispatch.java:856)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch.asHostObject(PolyglotValueDispatch.java:847)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.asHostObject(Value.java:1221)
	at com.oracle.dx4c.pr.TestIsHostObject.main(TestIsHostObject.java:14)
```
</details>

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reporting this, we're going to take a look into this and get back to you

**Comment by oubidar-Abderrahim** [comment]
Tracked internally on GR 51244
