### ISSUE TITLE
[native-image] `Missing CAP cache value` when trying to cross-compile

### ISSUE THREAD

**Issue by andreaTP** [oracle/graal#4596]
**Describe the issue**
Trying to cross-compile for a different target OS than the current fails with `Missing CAP cache value`.
It would be nice if we can statically provide those values "pre-calculated" or something along those lines.

The current approach/experiment is using `zig cc` as the C compiler and trying to leverage its cross-compiling features.

Any help debugging this issue is appreciated!

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. `git clone --depth 1 https://github.com/andreaTP/test_graal_zig_cc`
2. try to cross-compile for Win (static linking) or Mac (dynamic linking) from Linux
2.1 `docker build -f Dockerfile.mac . -t graal_zigcc_mac --progress=plain`
2.2 `docker build -f Dockerfile.win . -t graal_zigcc_win --progress=plain`

**Describe GraalVM and your environment:**
 - GraalVM version: `graalvm-ce-java11-22.1.0`
 - JDK major version: `11`

**More details**

Full stack trace of a failure:
```
#18 7.680 Error: Missing CAP cache value for: NativeCodeInfo:AMD64LibCHelperDirectives:StructInfo:CPUFeatures
#18 7.680 com.oracle.svm.core.util.UserError$UserException: Missing CAP cache value for: NativeCodeInfo:AMD64LibCHelperDirectives:StructInfo:CPUFeatures
#18 7.681       at com.oracle.svm.core.util.UserError.abort(UserError.java:72)
#18 7.681       at com.oracle.svm.hosted.c.info.InfoTreeVisitor.processChildren(InfoTreeVisitor.java:66)
#18 7.681       at com.oracle.svm.hosted.c.info.InfoTreeVisitor.visitNativeCodeInfo(InfoTreeVisitor.java:72)
#18 7.681       at com.oracle.svm.hosted.c.info.NativeCodeInfo.accept(NativeCodeInfo.java:57)
#18 7.681       at com.oracle.svm.hosted.c.query.QueryResultParser.parse(QueryResultParser.java:79)
#18 7.681       at com.oracle.svm.hosted.c.CAnnotationProcessor.makeQuery(CAnnotationProcessor.java:134)
#18 7.681       at com.oracle.svm.hosted.c.CAnnotationProcessor.process(CAnnotationProcessor.java:117)
#18 7.681       at com.oracle.svm.hosted.c.NativeLibraries.finish(NativeLibraries.java:554)
#18 7.681       at com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1622)
#18 7.681       at com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1065)
#18 7.681       at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:888)
#18 7.681       at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:555)
#18 7.682       at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:515)
#18 7.682       at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
#18 7.682       at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
#18 7.682       at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
#18 7.682       at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:615)
#18 7.682 ------------------------------------------------------------------------------------------------------------------------
#18 7.690                          0.3s (4.1% of total time) in 6 GCs | Peak RSS: 0.51GB | CPU load: 3.11
#18 7.691 ========================================================================================================================
#18 7.691 Failed generating 'code-with-quarkus-1.0.0-SNAPSHOT-runner' after 5.2s.
#18 7.769 Error: Image build request failed with exit status 1
#18 7.769 com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
#18 7.769       at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1678)
#18 7.769       at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1389)
#18 7.769       at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1350)
#18 7.769       at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1337)
```

**Comment by andreaTP** [comment]
Turns out we can use pre-recorded CAP files: `-H:+UseCAPCache -H:-NewCAPCache -H:CAPCacheDir="your caps"`
