### ISSUE TITLE
[native-image] java.lang.NoSuchMethodException: java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.<init>()

### ISSUE THREAD

**Issue by aldettinger** [oracle/graal#4600]
**Describe the issue**
I run an application with the native-image agent. It generates a big serialization-config file.
When I build the native image application with the serialization-config file, then an exception is thrown.

**Steps to reproduce the issue**

I was finally able to setup a reproducer.
The scenario is that we have an application failing in native mode with message below:
```
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: SerializationConstructorAccessor class not found for declaringClass: org.apache.camel.support.DefaultExchangeHolder (targetConstructorClass: java.lang.Object). Usually adding org.apache.camel.support.DefaultExchangeHolder to serialization-config.json fixes the problem.
```
So, we need to create a serialization-config file.
For this, we use the native-agent.
But still, the native mode is not working and reports:
```
Fatal error: com.oracle.svm.util.ReflectionUtil$ReflectionUtilError: java.lang.NoSuchMethodException: java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.<init>()
```

Please find below some instructions to reproduce this scenario, in a shell, run:
```
docker run -p 6379:6379 redis:6.2.6
```

In another shell, do:
```
git clone git@github.com:aldettinger/graal-4600-reproducer.git
mvn clean package
${GRAALVM_HOME}/bin/java -agentlib:native-image-agent=config-output-dir=target/graal-config -Dcamel.redis.test.server.authority="localhost:6379" -jar target/quarkus-app/quarkus-run.jar
cp target/graal-config/serialization-config.json src/main/resources
Edit the file src/main/resources/application.properties (set quarkus.native.additional-build-args= -H:SerializationConfigurationResources=serialization-config.json)
mvn clean integration-test -D native
```

**Describe GraalVM and your environment:**
GraalVM 22.0.0.2 Java 11 CE (Java Version 11.0.14+9-jvmci-22.0-b05)
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
RHEL 7
AMD64

**More details**
There is a bit of context in #3521, as I'm still investigating this.

```
Warning: Could not register java.lang.Object for serialization as it does not implement Serializable.
Warning: Could not register java.util.AbstractCollection for serialization as it does not implement Serializable.
Warning: Could not register java.util.AbstractCollection for serialization as it does not implement Serializable.
Warning: Could not register java.util.AbstractList for serialization as it does not implement Serializable.
Warning: Could not register java.util.AbstractList for serialization as it does not implement Serializable.
Warning: Could not register java.util.AbstractList for serialization as it does not implement Serializable.
Warning: Could not register java.util.AbstractMap for serialization as it does not implement Serializable.
Warning: Could not register java.util.AbstractMap for serialization as it does not implement Serializable.
Warning: Could not register java.util.AbstractSequentialList for serialization as it does not implement Serializable.
Warning: Could not register java.util.AbstractSequentialList for serialization as it does not implement Serializable.
Warning: Could not register java.util.AbstractSequentialList for serialization as it does not implement Serializable.
Warning: Could not register java.util.AbstractSequentialList for serialization as it does not implement Serializable.
Warning: Could not register java.util.AbstractSet for serialization as it does not implement Serializable.
Warning: Could not register java.util.AbstractSet for serialization as it does not implement Serializable.
Warning: Could not register java.util.AbstractSet for serialization as it does not implement Serializable.
                                                                    (11.6s @ 0.34GB)
Fatal error: com.oracle.svm.util.ReflectionUtil$ReflectionUtilError: java.lang.NoSuchMethodException: java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.<init>()
	at com.oracle.svm.util.ReflectionUtil.lookupConstructor(ReflectionUtil.java:91)
	at com.oracle.svm.util.ReflectionUtil.lookupConstructor(ReflectionUtil.java:78)
	at com.oracle.svm.reflect.serialize.hosted.SerializationBuilder.addReflections(SerializationFeature.java:264)
	at com.oracle.svm.reflect.serialize.hosted.SerializationBuilder.lambda$registerWithTargetConstructorClass$0(SerializationFeature.java:253)
	at com.oracle.svm.hosted.ConditionalConfigurationRegistry.registerConditionalConfiguration(ConditionalConfigurationRegistry.java:43)
	at com.oracle.svm.reflect.serialize.hosted.SerializationBuilder.registerWithTargetConstructorClass(SerializationFeature.java:251)
	at com.oracle.svm.reflect.serialize.hosted.SerializationBuilder.registerWithTargetConstructorClass(SerializationFeature.java:234)
	at com.oracle.svm.core.configure.SerializationConfigurationParser.parseSerializationDescriptorObject(SerializationConfigurationParser.java:67)
	at com.oracle.svm.core.configure.SerializationConfigurationParser.parseAndRegister(SerializationConfigurationParser.java:56)
	at com.oracle.svm.hosted.config.ConfigurationParserUtils.doParseAndRegister(ConfigurationParserUtils.java:127)
	at com.oracle.svm.hosted.config.ConfigurationParserUtils.lambda$parseAndRegisterConfigurations$3(ConfigurationParserUtils.java:113)
	at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:212)
	at com.oracle.svm.hosted.config.ConfigurationParserUtils$1.tryAdvance(ConfigurationParserUtils.java:106)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:491)
	at java.base/java.util.stream.IntPipeline.sum(IntPipeline.java:449)
	at com.oracle.svm.hosted.config.ConfigurationParserUtils.parseAndRegisterConfigurations(ConfigurationParserUtils.java:115)
	at com.oracle.svm.reflect.serialize.hosted.SerializationFeature.duringSetup(SerializationFeature.java:94)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$16(NativeImageGenerator.java:847)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:74)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:847)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:534)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:494)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:426)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:587)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:126)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:617)
Caused by: java.lang.NoSuchMethodException: java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
	at com.oracle.svm.util.ReflectionUtil.lookupConstructor(ReflectionUtil.java:83)
	... 37 more
```

**Comment by aldettinger** [comment]
I will try to check later.

**Comment by aldettinger** [comment]
@oubidar-Abderrahim Hello, I was not able to test with the latest snapshot locally. However, I've been able to build a small reproducer so that one can play with it.

**Comment by oubidar-Abderrahim** [comment]
If you can share a reproducer outside of docker, something I can run locally, that would be very helpful

**Comment by aldettinger** [comment]
@oubidar-Abderrahim Is docker only needed to start a redis server ? If that's the case, maybe one could try to [install a redis server locally](https://flaviocopes.com/redis-installation/) as a replacement.

**Comment by oubidar-Abderrahim** [comment]
> Is docker only needed to start a redis server ? 
I believe you're the one who can answer this question.

> However, I've been able to build a small reproducer so that one can play with it.
Could you please share this small reproducer so that we can debug it? Thank you

**Comment by aldettinger** [comment]
The steps to reproduce are described in the `Steps to reproduce the issue` summary at the beginning of the ticket:
 + In case `docker run -p 6379:6379 redis:6.2.6` can't be run, then it's worth trying to install a [redis server locally](https://flaviocopes.com/redis-installation/) as a replacement.
 + In case, there is another docker related issue, please share

**Comment by aldettinger** [comment]
Up on this one. Is it possible to debug the issue with the `Steps to reproduce the issue` ?

**Comment by oubidar-Abderrahim** [comment]
Please use our latest version and if there's still an issue, create a new issue. Thank you

**Comment by aldettinger** [comment]
Indeed, I was not able to move further on this subject, and there was a lot of changes in between.
