### ISSUE TITLE
Not able to import certificates in Native Image

### ISSUE THREAD

**Issue by bajpaiutkarsh** [oracle/graal#4603]
I have requirement for importing the certificates in native-image , i am getting the below errors

First Issue with building the native image
```
[INFO] '-H:ResourceConfigurationResources@jar:file:///builds/cx-verticals-dev/fabric-virus-scan-ms/fabric-virus-scan-app/target/fabric-virus-scan-app-22.10.0.0-SNAPSHOT.jar!/META-INF/native-image/resource-config.json=META-INF/native-image/resource-config.json' \
[INFO] '-H:DynamicProxyConfigurationResources@jar:file:///builds/cx-verticals-dev/fabric-virus-scan-ms/fabric-virus-scan-app/target/fabric-virus-scan-app-22.10.0.0-SNAPSHOT.jar!/META-INF/native-image/proxy-config.json=META-INF/native-image/proxy-config.json' \
[INFO] '-H:SerializationConfigurationResources@jar:file:///builds/cx-verticals-dev/fabric-virus-scan-ms/fabric-virus-scan-app/target/fabric-virus-scan-app-22.10.0.0-SNAPSHOT.jar!/META-INF/native-image/serialization-config.json=META-INF/native-image/serialization-config.json' \
[INFO] '-H:PredefinedClassesConfigurationResources@jar:file:///builds/cx-verticals-dev/fabric-virus-scan-ms/fabric-virus-scan-app/target/fabric-virus-scan-app-22.10.0.0-SNAPSHOT.jar!/META-INF/native-image/predefined-classes-config.json=META-INF/native-image/predefined-classes-config.json' \
[INFO] -H:Name=fabric-virus-scan-app-22.10.0.0-SNAPSHOT \
[INFO] -H:CLibraryPath=/usr/lib64/graalvm/graalvm22-ee-java11/lib/svm/clibraries/linux-amd64
[INFO] ]
[WARNING] Warning: Option 'EnableAllSecurityServices' is deprecated and might be removed from future versions
[WARNING] Warning: Option 'EnableAllSecurityServices' is deprecated and might be removed from future versions
[WARNING] Warning: Option 'EnableAllSecurityServices' is deprecated and might be removed from future versions
[WARNING] Warning: Option 'EnableAllSecurityServices' is deprecated and might be removed from future versions
[INFO] ========================================================================================================================
[INFO] GraalVM Native Image: Generating 'fabric-virus-scan-app-22.10.0.0-SNAPSHOT' (static executable)...
[INFO] ========================================================================================================================
[INFO] 
[INFO] [1/7] Initializing...                                                                                    (0.0s @ 0.60GB)
[WARNING] Fatal error: java.lang.NoClassDefFoundError: javax/enterprise/inject/spi/Bean
[WARNING] 	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
[WARNING] 	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
[WARNING] 	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
[WARNING] 	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
[WARNING] 	at com.oracle.svm.util.ReflectionUtil.lookupConstructor(ReflectionUtil.java:81)
[WARNING] 	at com.oracle.svm.util.ReflectionUtil.lookupConstructor(ReflectionUtil.java:76)
[WARNING] 	at com.oracle.svm.util.ReflectionUtil.newInstance(ReflectionUtil.java:95)
[WARNING] 	at com.oracle.svm.hosted.FeatureHandler.registerFeature(FeatureHandler.java:174)
[WARNING] 	at com.oracle.svm.hosted.FeatureHandler.registerFeatures(FeatureHandler.java:124)
[WARNING] 	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:830)
[INFO] ------------------------------------------------------------------------------------------------------------------------
[WARNING] 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:555)
[WARNING] 	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:515)
[WARNING] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
[WARNING] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
[WARNING] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
[WARNING] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:615)
[WARNING] Caused by: java.lang.ClassNotFoundException: javax.enterprise.inject.spi.Bean
[WARNING] 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
[WARNING] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[WARNING] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[WARNING] 	... 16 more
[INFO]                         0.6s (14.1% of total time) in 12 GCs | Peak RSS: 1.11GB | CPU load: 9.19
[INFO] ========================================================================================================================
[INFO] Failed generating 'fabric-virus-scan-app-22.10.0.0-SNAPSHOT' after 3.3s.
[WARNING] Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for fabric-virus-scan-ms 22.10.0.0-SNAPSHOT:
[INFO] 
[INFO] fabric-virus-scan-ms ............................... SUCCESS [  0.419 s]
[INFO] fabric-virus-scan-app .............................. FAILURE [01:02 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:04 min
[INFO] Finished at: 2022-05-23T10:49:19Z

```
Earlier once this build got succeeded but below errors were coming while importing the certificates

```
com.oracle.svm.core.jdk.UnsupportedFeatureError: Inaccessible trust store: /etc/icap_certs/*,-Djavax.net.ssl.trustStorePassword=changeit See https://www.graalvm.org/reference-manual/native-image/CertificateManagement#runtime-options for more details about runtime certificate management.
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89)
        at com.oracle.svm.core.jdk.TrustStoreManagerSupport.getRuntimeTrustStoreDescriptor(Target_sun_security_ssl_TrustStoreManager.java:156)
        at sun.security.ssl.TrustStoreManager.getTrustedCerts(TrustStoreManager.java:211)
        at sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:49)
        at javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:278)
        at sun.security.ssl.SSLContextImpl.en
```
command used in docker file
`./app/<native-image> -Djavax.net.ssl.trustStore=/etc/icap_certs/*,-Djavax.net.ssl.trustStorePassword=changeit`
please provide some suggestions for the above issue

**Comment by bajpaiutkarsh** [comment]
Hi,
1. GraalVM is **GraalVM Updater 22.1.0** and java is **openjdk 11.0.15 2022-04-19**
2. We are trying to import certificate which can authenticate the call from our backend to a service hosted. It is somekind of SHA certificate. attaching a sample certificate here. rest i can ping you internal details over slack
[icap_cert6.cer.txt](https://github.com/oracle/graal/files/8830271/icap_cert6.cer.txt) please remove .txt extension as it is now allowed to upload here.
3. Outside docker it works using keytool, but it is not working inside docker when trying to build graalVM native image
.

**Comment by oubidar-Abderrahim** [comment]
Closing this issue for inactivity
