### ISSUE TITLE
[GR-39172] -H:+PrintImageObjectTree option fails with java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by ChristophTF** [oracle/graal#4646]
**Describe the issue**
Calling native-image with the option `-H:+PrintImageObjectTree` fails on a trivial java project (i.e. a Hello World sample).

**Steps to reproduce the issue**
- `native-image HelloWorld -H:+PrintImageObjectTree`

**Describe GraalVM and your environment:**
 - GraalVM version: **CE 22.1**
 - JDK major version: **17**
 - OS: **Ubuntu 20.04.4 LTS**
 - Architecture: **AMD64**

**More details**
```
========================================================================================================================
GraalVM Native Image: Generating 'helloworld' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                    (4.1s @ 0.18GB)
 Version info: 'GraalVM 22.1.0 Java 17 CE'
 C compiler: gcc (linux, x86_64, 9.4.0)
 Garbage collector: Serial GC
[2/7] Performing analysis...  [******]                                                                  (11.8s @ 0.59GB)
   2,852 (74.19%) of  3,844 classes reachable
   3,399 (50.83%) of  6,687 fields reachable
  12,932 (44.56%) of 29,020 methods reachable
      27 classes,     0 fields, and   345 methods registered for reflection
      57 classes,    58 fields, and    51 methods registered for JNI access
# Printing object tree to: /home/christoph/git/Uni/SoSe22/RE/CE-Empty-Default/reports/object_tree_helloworld_20220614_221419.txt
Exhaustive heap scanning is disabled. The object tree will not contain all instances of types: java.lang.String
Exhaustive heap scanning can be turned on using -H:+ExhaustiveHeapScan.

Fatal error: java.lang.UnsatisfiedLinkError: 'java.lang.String com.oracle.svm.core.hub.DynamicHub.toString()'
        at com.oracle.svm.core.hub.DynamicHub.toString(Native Method)
        at java.base/java.lang.String.valueOf(String.java:4218)
        at jdk.internal.vm.ci/jdk.vm.ci.meta.JavaKind.format(JavaKind.java:344)
        at jdk.internal.vm.ci/jdk.vm.ci.meta.JavaKind.formatArray(JavaKind.java:372)
        at jdk.internal.vm.ci/jdk.vm.ci.meta.JavaKind.format(JavaKind.java:350)
        at com.oracle.graal.pointsto.reports.ObjectTreePrinter.constantAsString(ObjectTreePrinter.java:412)
        at com.oracle.graal.pointsto.reports.ObjectTreePrinter$ObjectNodeBase.constantFormat(ObjectTreePrinter.java:125)
        at com.oracle.graal.pointsto.reports.ObjectTreePrinter.printTypeHierarchyNode(ObjectTreePrinter.java:537)
        at com.oracle.graal.pointsto.reports.ObjectTreePrinter.printTypeHierarchy(ObjectTreePrinter.java:478)
        at com.oracle.graal.pointsto.reports.ObjectTreePrinter.doPrint(ObjectTreePrinter.java:78)
        at com.oracle.graal.pointsto.reports.ObjectTreePrinter.lambda$print$0(ObjectTreePrinter.java:65)
        at com.oracle.graal.pointsto.reports.ReportUtils.reportImpl(ReportUtils.java:154)
        at com.oracle.graal.pointsto.reports.ReportUtils.report(ReportUtils.java:90)
        at com.oracle.graal.pointsto.reports.ReportUtils.report(ReportUtils.java:72)
        at com.oracle.graal.pointsto.reports.ReportUtils.report(ReportUtils.java:68)
        at com.oracle.graal.pointsto.reports.ObjectTreePrinter.print(ObjectTreePrinter.java:64)
        at com.oracle.graal.pointsto.reports.AnalysisReporter.printAnalysisReports(AnalysisReporter.java:53)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:766)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:558)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:515)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:615)
------------------------------------------------------------------------------------------------------------------------
                        1.2s (7.1% of total time) in 14 GCs | Peak RSS: 2.11GB | CPU load: 5.95
========================================================================================================================
Failed generating 'helloworld' after 16.6s.
Error: Image build request failed with exit status 1
```

**Comment by fniephaus** [comment]
Fixed via https://github.com/oracle/graal/commit/d0acf5cf5a748c99672e753bbc49ecddb220c3af.
