### ISSUE TITLE
java.lang.NoSuchMethodException: com.ibm.db2.jcc.DB2SimpleDataSource.getConnection()

### ISSUE THREAD

**Issue by student20211017** [oracle/graal#4663]
I have created a simple Java program that queries a DB2 table, it works fine with Java 17 / Graal JIT.

When running it as Graal native-image, I get error message:

java.lang.NoSuchMethodException: com.ibm.db2.jcc.DB2SimpleDataSource.getConnection()

I build the executable with:

native-image --verbose --native-image-info -H:IncludeResourceBundles=com.ibm.db2.jcc.t2zos.af --no-fallback -cp ".;jcc-11.5.7.0.jar" myClass

The stacktrace starts with:

java.lang.NoSuchMethodException: 
com.ibm.db2.jcc.DB2SimpleDataSource.getConnection(java.lang.Object)
at java.lang.Class.getMethod(DynamicHub.java:2227)
at com.ibm.db2.jcc.am.ce.run(ce.java:49)
at java.security.AccessController.executePrivileged(AccessController.java:169)
at java.security.AccessController.doPrivileged(AccessController.java:318)
at com.ibm.db2.jcc.DB2SimpleDataSource.<clinit>(DB2SimpleDataSource.java:82)
at com.ibm.db2.jcc.DB2Driver.getDataSource(DB2Driver.java:1049)
at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:435)
at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:117)
at java.sql.DriverManager.getConnection(DriverManager.java:681)
at java.sql.DriverManager.getConnection(DriverManager.java:229) 

I have not found any confirmation that JDBC driver for DB2 is working or is not working.

I have posted at SO but not answer there. 
https://stackoverflow.com/questions/72697856/graalvm-java-lang-nosuchmethodexception-com-ibm-db2-jcc-db2simpledatasource-g

Is this a supported use case?

**Comment by fniephaus** [comment]
It seems like you're missing proper configuration files for creating native executables with GraalVM Native Image. Please take a look at the trace agent, which can help you find uses of reflection and other things in your application and create appropriate config files: https://www.graalvm.org/22.1/reference-manual/native-image/Agent/

Please feel free to re-open this if this doesn't solve your issue.
