### ISSUE TITLE
Compatibility issue in Java 19-ea

### ISSUE THREAD

**Issue by hejcz** [oracle/graal#4674]
**Describe the issue**
In my company we use openjdk 18 with graal compiler enabled with:
```bash
java -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI \
--module-path=$APP_HOME/graal-compiler \
--upgrade-module-path=$APP_HOME/graal-compiler/compiler.jar:$APP_HOME/graal-compiler/compiler-management.jar 
```
We try to upgrade from 21.3.2.1 to 22.1.0.1 but we experience memory leak problem that we believe may be related to https://bugs.openjdk.org/browse/JDK-8279949 It will be fixed in java 19 but when I tried to run 22.1.0.1 with java 19-ea I got:
```
Caused by: java.lang.NoClassDefFoundError: jdk.internal.access.foreign.MemorySegmentProxy
2022-06-21 15:54:32,461 [main] ERROR java.lang.Throwable -      at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.initLookupTypes(GraalTruffleRuntime.java:421)
2022-06-21 15:54:32,463 [main] ERROR java.lang.Throwable -      at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.<init>(GraalTruffleRuntime.java:177)
2022-06-21 15:54:32,463 [main] ERROR java.lang.Throwable -      at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.AbstractHotSpotTruffleRuntime.<init>(AbstractHotSpotTruffleRuntime.java:157)
2022-06-21 15:54:32,463 [main] ERROR java.lang.Throwable -      at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.java.HotSpotTruffleRuntime.<init>(HotSpotTruffleRuntime.java:40)
2022-06-21 15:54:32,463 [main] ERROR java.lang.Throwable -      at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.java.HotSpotTruffleRuntimeAccess.createRuntime(HotSpotTruffleRuntimeAccess.java:38)
2022-06-21 15:54:32,463 [main] ERROR java.lang.Throwable -      at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.AbstractHotSpotTruffleRuntimeAccess.getRuntime(AbstractHotSpotTruffleRuntimeAccess.java:49)
```

**Steps to reproduce the issue**
Running Graal on java 19-ea results in an error above.

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **22.1.0.1 **
 - JDK major version: **19-ea**
 - OS: **debian buster**
 - Architecture: **AMD64**

**More details**
Obviously I don't expect you to support java releases before they are released but I have some questions:
1. Could you add another if branch in GraalTruffleRuntime, so for java >= 19 MemorySegmentProxy isn't required.
2. As GraalVM is published only for LTS releases what is your policy regarding support for non-lts java releases? 
3. Can you confirm that 22.1.0.1 uses some mechanisms that could make memory-leak bug linked above more visible? Right now with the same openjdk 18 and graal 21.3.2.1 we don't experience leaks while with 22.1.0.1 after few hours a machine has whole memory allocated. Native Memory Tracker shows it is consumed by "Internal" category.

**Comment by hejcz** [comment]
@chumer FYI

**Comment by chumer** [comment]
Thanks for filing this! We are currently working on some infrastructure to be able to test against JKD 19 builds. We need to wait with fixing this until we have the infrastructure up. 

> Could you add another if branch in GraalTruffleRuntime, so for java >= 19 MemorySegmentProxy isn't required.

That is probably the fix we are going to deploy. 

> As GraalVM is published only for LTS releases what is your policy regarding support for non-lts java releases?

We try to stay on top of the non-lts releases. But sometimes we skip one. For example, we skipped support for 18.

> Can you confirm that 22.1.0.1 uses some mechanisms that could make memory-leak bug linked above more visible?

I am not aware of any changes that trigger this problem more. But it is generally hard to diagnose without seeing a heap dump of some sort. @tzezula @dougxc  do you have an idea what could cause this? Some changes in JNI usage in jargraal maybe?

**Comment by hejcz** [comment]
@chumer is there any chance the summer release of graal contains ths fix? Maybe we will be able to find another problem with jdk 19 before autumn release.

**Comment by oubidar-Abderrahim** [comment]
I believe this is no longer relevant since JDK19 is no longer supported. if you face a similar issue on the latest GraalVM versions, please create a new ticket and we can take another look at it

**Comment by chumer** [comment]
We also did fix this problem in latest releases. We are fully compatible with 21 and already 22 on master.
