### ISSUE TITLE
Build libnative-image-agent.so.image, prompt exception，The classpath of com.oracle.svm.hosted.NativeImageGeneratorRunner must not contain ".". This can happen implicitly if the builder runs exclusively on the --module-path but specifies the com.oracle.svm.hosted.NativeImageGeneratorRunner main class without --module.

### ISSUE THREAD

**Issue by 2854862159** [oracle/graal#4693]
**Describe the issue**
I try to build graalvm from source, and it shows that the build failed，I've been tortured for a day, please help me

**Steps to reproduce the issue**
1. **/home/tooru/mx/mx -v --primary-suite=vm --java-home=/home/tooru/labsjdk-ce-17.0.3-jvmci-22.1-b06 --dynamicimports /substratevm --disable-libpolyglot --disable-polyglot --force-bash-launchers=true --exclude-components=nju,nil,lg build** 

**Describe GraalVM and your environment:**
 - GraalVM source version : **[CE 22.1.0]**
 - JDK major version: **[labsjdk-ce-17.0.3-jvmci-22.1-b06]**
 - OS: **[20.04.1-Ubuntu]**
 - Architecture: **[AMD64]**

**More details**
```
   /home/tooru/graal-vm-22.1.0/sdk/mxbuild/linux-amd64/GRAALVM_7518798B10_JAVA17_STAGE1/graalvm-7518798b10-java17-22.1.0/lib/svm/bin/native-image --macro:native-image-agent-library -H:NumberOfThreads=2 -H:+BuildOutputPrefix -H:Path=/home/tooru/graal-vm-22.1.0/sdk/mxbuild/linux-amd64/libnative-image-agent.so.image
Fatal error: com.oracle.svm.core.util.VMError$HostedError: The classpath of com.oracle.svm.hosted.NativeImageGeneratorRunner must not contain ".". This can happen implicitly if the builder runs exclusively on the --module-path but specifies the com.oracle.svm.hosted.NativeImageGeneratorRunner main class without --module.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageClassLoaderSupport.<init>(NativeImageClassLoaderSupport.java:120)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.installNativeImageClassLoader(NativeImageGeneratorRunner.java:180)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:123)
Error: Image build request failed with exit status 1
[exit code: 1]
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/tooru/mx/mx.py", line 92, in run
    super(_DummyProcess, self).run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tooru/mx/mx.py", line 14490, in executeTask
    task.execute()
  File "/home/tooru/mx/mx.py", line 5129, in execute
    _built = self.build()
  File "/home/tooru/graal-vm-22.1.0/sdk/mx.sdk/mx_sdk_vm_impl.py", line 2151, in build
    self.svm_support.native_image(build_args, output_file)
  File "/home/tooru/graal-vm-22.1.0/sdk/mx.sdk/mx_sdk_vm_impl.py", line 1138, in native_image
    return mx.run(native_image_command, nonZeroIsFatal=nonZeroIsFatal, out=out, err=err)
  File "/home/tooru/mx/mx.py", line 13276, in run
    abort(retcode)
  File "/home/tooru/mx/mx.py", line 4106, in abort
    traceback.print_stack()

Building libnative-image-agent.so.image: Failed due to error: 1
Building libnative-image-agent.so.image failed
Shutting down
[Stopped javac-daemon on port 46481 for Java 17.0.3 (17) from /home/tooru/labsjdk-ce-17.0.3-jvmci-22.1-b06]
[Stopped javac-daemon on port 43191 for Java 17.0.3 (17) from /home/tooru/labsjdk-ce-17.0.3-jvmci-22.1-b06]
Shutting down
  File "/home/tooru/mx/mx_enter.py", line 41, in <module>
    mx._main_wrapper()
  File "/home/tooru/mx/mx.py", line 17884, in _main_wrapper
    main()
  File "/home/tooru/mx/mx.py", line 17864, in main
    retcode = c(command_args)
  File "/home/tooru/mx/mx_commands.py", line 144, in __call__
    return self.command_function(*args, **kwargs)
  File "/home/tooru/mx/mx.py", line 14552, in build
    abort('{0} build tasks failed'.format(len(failed)))
  File "/home/tooru/mx/mx.py", line 4106, in abort
    traceback.print_stack()
1 build tasks failed
```

**Comment by fniephaus** [comment]
Could you please update your checkout to the latest master or the latest commit on the 22.1 release branch, upgrade to the corresponding labsjdk, and try again? If that doesn't work, please re-open the issue. Thanks!
