### ISSUE TITLE
"PolyglotException: TypeError: protoParent is neither Object nor Null" while extends js-class from return from other graal-context

### ISSUE THREAD

**Issue by DmytroSerbin** [oracle/graal#4696]
- GraalVM version: 21.3.2 CE + 22.1.0.1 CE
 - JDK version: JDK8 + JDK17
 - OS: linux centos7

There is a need to migrate from the Nashorn. The script uses function-based inheritance.
For example:
```
function ClassBase() {
	
	this.method1 = function() {
	}
	
	this.method2 = function() {
		this.method1();
	}
	
}

function ClassMain() {

	ClassBase.call(this);

	this.method3 = function() {
		this.method2()
	}

}
```
From one graal-context, the code works without errors.

But if the ClassBase is returned from the first execution context and passed to the bindings of the second context, then I get an error "TypeError: \<this>.method1 is not a function" when I try to call ClassBase.method1() from ClassBase.method2() from ClassMain.method3().

If I use ES6-classes with a similar requirement of declaring a ClassBase in one context and passing it to another context, then I get the error "TypeError: protoParent is neither Object nor Null" when trying to inherit ClassMain from ClassBase.
Example of ES6 inheritance:

```
class ClassBase {
	
	constructor() {
	}
  
	method1() {
	}
	
	method2() {
		this.method1();
	}
	
};

class ClassMain extends ClassBase {

	constructor() {
		super()
	}
	
	method3() {
		this.method2()
	}
	
}
```

<details><summary>Working example console java-code to reproduce the issue</summary>

```

package test;

import javax.script.Bindings;
import javax.script.ScriptContext;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;
import javax.script.SimpleBindings;
import javax.script.SimpleScriptContext;

import org.graalvm.polyglot.Context;

public class GraalExtends {

	public static void main(String[] args) {
		new GraalExtends().process();
	}

	public GraalExtends() {
	}

	private void process() {

		System.out.println("Start");
		
		try {
			processLogicExtendsClassGraal();
		} catch (Throwable e) {
			System.out.println("Error in processLogicClassGraal: "+e);
			e.printStackTrace();
		}

		try {
			processLogicExtendsFuncGraal_Context();
		} catch (Throwable e) {
			System.out.println("Error in processLogicFuncGraal1: "+e);
			e.printStackTrace();
		}

		try {
			processLogicExtendsFuncGraal_Engine();
		} catch (Throwable e) {
			System.out.println("Error in processLogicFuncGraal2: "+e);
			e.printStackTrace();
		}

		try {
			processLogicExtendsFuncNashorn();
		} catch (Throwable e) {
			System.out.println("Error in processLogicFuncNashorn: "+e);
			e.printStackTrace();
		}
		
		System.out.println("All end");
		
	}

	private void processLogicExtendsClassGraal() {
		
		System.out.println("====== Start EXTENDS_CLASS_GRAAL");
		
		Context context;
		
		context = Context.newBuilder().allowExperimentalOptions(true).option("js.nashorn-compat", "true").build();
		Object classBase = context.eval("js", 
			  "class ClassBase {\n"
			+ "  constructor() {\n"
			+ "  }\n"
			+ "  method1() {\n"
			+ "    print(\"--- method1\");\n"
			+ "  }\n"
			+ "  method2() {\n"
			+ "    print(\"--- method2\");\n"
			+ "    this.method1();\n"
			+ "  }\n"
			+ "}\n"
			+ "print(\"--- declare ClassBase\");\n"
			+ "ClassBase;\n"
		);
		
		context = Context.newBuilder().allowExperimentalOptions(true).option("js.nashorn-compat", "true").build();
		context.getBindings("js").putMember("ClassBase", classBase);
		context.getPolyglotBindings().putMember("ClassBase", classBase);
		context.eval("js", 
			  "class ClassMain extends ClassBase {\n"
			+ "  constructor() {\n"
			+ "    super();\n"
			+ "  }\n"
			+ "  method3() {\n"
			+ "    print(\"--- method3\");\n"
			+ "    this.method2();\n"
			+ "  }\n"
			+ "}\n"
			+ "print(\"--- declare ClassMain\");\n"
			+ "var instance = new ClassMain();\n"
			+ "instance.method3();"
		);
		
		System.out.println("====== Success EXTENDS_CLASS_GRAAL");

	}

	private void processLogicExtendsFuncGraal_Context() {
		
		System.out.println("====== Start EXTENDS_FUNC_GRAAL_CONTEXT");
		
		Context context;
		
		context = Context.newBuilder().allowExperimentalOptions(true).option("js.nashorn-compat", "true").build();
		Object classBase = context.eval("js", 
			  "function ClassBase() {\n"
			+ "  this.method1 = function() {\n"
			+ "    print(\"--- method1\");\n"
			+ "  }\n"
			+ "  this.method2 = function() {\n"
			+ "    print(\"--- method2\");\n"
			+ "    this.method1();\n"
			+ "  }\n"
			+ "}\n"
			+ "print(\"--- declare ClassBase\");\n"
			+ "ClassBase;\n"
		);
		
		context = Context.newBuilder().allowExperimentalOptions(true).option("js.nashorn-compat", "true").build();
		context.getBindings("js").putMember("ClassBase", classBase);
		context.getPolyglotBindings().putMember("ClassBase", classBase);
		context.eval("js", 
			  "function ClassMain() {\n"
			+ "  ClassBase.call(this);\n"
			+ "  this.method3 = function() {\n"
			+ "    print(\"--- method3\");\n"
			+ "    this.method2();\n"
			+ "  }\n"
			+ "}\n"
			+ "print(\"--- declare ClassMain\");\n"
			+ "var instance = new ClassMain();\n"
			+ "instance.method3();"
		);
		
		System.out.println("====== Success EXTENDS_FUNC_GRAAL_CONTEXT");

	}
	
	private void processLogicExtendsFuncGraal_Engine() throws ScriptException {
		
		System.out.println("====== Start EXTENDS_FUNC_GRAAL_ENGINE");
		
		ScriptEngine engine = new ScriptEngineManager().getEngineByName("graal.js");
		ScriptContext context;
		
		context = new SimpleScriptContext();
		Object classBase = engine.eval( 
			  "function ClassBase() {\n"
			+ "  this.method1 = function() {\n"
			+ "    print(\"--- method1\");\n"
			+ "  }\n"
			+ "  this.method2 = function() {\n"
			+ "    print(\"--- method2\");\n"
			+ "    this.method1();\n"
			+ "  }\n"
			+ "}\n"
			+ "print(\"--- declare ClassBase\");\n"
			+ "ClassBase;\n"
		, context);
		
		Bindings bindings = new SimpleBindings();
		bindings.put("ClassBase", classBase);
		context = new SimpleScriptContext();
		context.setBindings(bindings, ScriptContext.ENGINE_SCOPE);
		engine.eval( 
			  "function ClassMain() {\n"
			+ "  ClassBase.call(this);\n"
			+ "  this.method3 = function() {\n"
			+ "    print(\"--- method3\");\n"
			+ "    this.method2();\n"
			+ "  }\n"
			+ "}\n"
			+ "print(\"--- declare ClassMain\");\n"
			+ "var instance = new ClassMain();\n"
			+ "instance.method3();"
		, context);
		
		System.out.println("====== Success EXTENDS_FUNC_GRAAL_ENGINE");

	}
	
	private void processLogicExtendsFuncNashorn() throws ScriptException {

		System.out.println("====== Start EXTENDS_FUNC_NASHORN");
		
		ScriptEngine engine = new ScriptEngineManager().getEngineByName("nashorn");
		ScriptContext context;
		
		context = new SimpleScriptContext();
		Object classBase = engine.eval( 
			  "function ClassBase() {\n"
			+ "  this.method1 = function() {\n"
			+ "    print(\"--- method1\");\n"
			+ "  }\n"
			+ "  this.method2 = function() {\n"
			+ "    print(\"--- method2\");\n"
			+ "    this.method1();\n"
			+ "  }\n"
			+ "}\n"
			+ "print(\"--- declare ClassBase\");\n"
			+ "ClassBase;\n"
		, context);
		
		Bindings bindings = new SimpleBindings();
		bindings.put("ClassBase", classBase);
		context = new SimpleScriptContext();
		context.setBindings(bindings, ScriptContext.ENGINE_SCOPE);
		engine.eval( 
			  "function ClassMain() {\n"
			+ "  ClassBase.call(this);\n"
			+ "  this.method3 = function() {\n"
			+ "    print(\"--- method3\");\n"
			+ "    this.method2();\n"
			+ "  }\n"
			+ "}\n"
			+ "print(\"--- declare ClassMain\");\n"
			+ "var instance = new ClassMain();\n"
			+ "instance.method3();"
		, context);
			
		System.out.println("====== Success EXTENDS_FUNC_NASHORN");
		
	}
	
}
```
</details>

<details><summary>Out here</summary>

```
Start
====== Start EXTENDS_CLASS_GRAAL
--- declare ClassBase
Error in processLogicClassGraal: org.graalvm.polyglot.PolyglotException: TypeError: protoParent is neither Object nor Null
TypeError: protoParent is neither Object nor Null
	at <js> :program(Unnamed:1-9:0-135)
	at org.graalvm.polyglot.Context.eval(Context.java:405)
	at test.GraalExtends.processLogicExtendsClassGraal(GraalExtends.java:84)
	at test.GraalExtends.process(GraalExtends.java:27)
	at test.GraalExtends.main(GraalExtends.java:16)
====== Start EXTENDS_FUNC_GRAAL_CONTEXT
--- declare ClassBase
--- declare ClassMain
--- method3
--- method2
Error in processLogicFuncGraal1: org.graalvm.polyglot.PolyglotException: TypeError: <this>.method1 is not a function
TypeError: <this>.method1 is not a function
	at <js> this.method2(Unnamed:7:143-156)
	at <js> this.method3(Unknown)
	at <js> :program(Unnamed:10:193-210)
	at org.graalvm.polyglot.Context.eval(Context.java:405)
	at test.GraalExtends.processLogicExtendsFuncGraal_Context(GraalExtends.java:127)
	at test.GraalExtends.process(GraalExtends.java:34)
	at test.GraalExtends.main(GraalExtends.java:16)
====== Start EXTENDS_FUNC_GRAAL_ENGINE
--- declare ClassBase
--- declare ClassMain
--- method3
--- method2
Error in processLogicFuncGraal2: javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: TypeError: <this>.method1 is not a function
javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: TypeError: <this>.method1 is not a function
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.toScriptException(GraalJSScriptEngine.java:483)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:460)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:426)
	at test.GraalExtends.processLogicExtendsFuncGraal_Engine(GraalExtends.java:170)
	at test.GraalExtends.process(GraalExtends.java:41)
	at test.GraalExtends.main(GraalExtends.java:16)
Caused by: org.graalvm.polyglot.PolyglotException: TypeError: <this>.method1 is not a function
	at <js>.this.method2(<eval>:7)
	at <js>.this.method3(<eval>:5)
	at <js>.:program(<eval>:10)
	at org.graalvm.polyglot.Context.eval(Context.java:379)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:458)
	... 4 more
====== Start EXTENDS_FUNC_NASHORN
--- declare ClassBase
--- declare ClassMain
--- method3
--- method2
--- method1
====== Success EXTENDS_FUNC_NASHORN
All end

```
</details>
Methods processLogicExtendsFuncGraal_Engine and processLogicExtendsFuncNashorn are equivalent. The first uses the Graal, the second uses the Nashorn. With the Graal - a error, with the Nashorn - success.

I assume that the causes of errors when trying to inherit the ES6-class and when inheriting JS-functions are related to an incomprehensible one architectural Graal-feature that is not in Nashorn.

I tested the specified java-code on the Graal version 21.3.2 (jdk8, with Nashorn) and on version 22.1.0.1 (jdk17 without nashorn).

Maybe I somehow incorrectly transfer the ClassBase-object/function from the first to the second context?
But in Nashorn, the same way of passing an ClassBase-object/function works as expected.

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, we will take a look into it and get back to you

**Comment by oubidar-Abderrahim** [comment]
If this issue is still relevant in the latest GraalVM versions, please create a new issue for it and follow the template provided. Thank you
