### ISSUE TITLE
how to access dynamoDB (Spring-native)

### ISSUE THREAD

**Issue by zhoujiuzhou9** [oracle/graal#4701]
I  try to access DynamoDB with Lambda ,but it failed

**Caused by: com.amazonaws.SdkClientException: Unable to load partition metadata from com/amazonaws/partitions/endpoints.json**

Error msg   
```
2022-07-05 09:09:00.674 ERROR 9 --- [           main] o.s.boot.SpringApplication               : Application run failed
--
java.lang.IllegalStateException: Failed to execute CommandLineRunner
at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:794) ~[spring-native-aws-lambda:2.5.6]
at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775) ~[spring-native-aws-lambda:2.5.6]

START RequestId: 58238b51-f2e4-4983-9955-895255220bed Version: $LATEST
--
2022-07-05 10:57:12.784  INFO 9 --- [           main] o.s.nativex.NativeListener               : This application is bootstrapped with code generated with Spring AOT
2022-07-05 10:57:12.804  INFO 9 --- [           main] o.s.c.f.a.aws.CustomRuntimeInitializer   : AWS Handler: exampleFunction
2022-07-05 10:57:12.810  INFO 9 --- [           main] c.c.s.SpringNativeAwsLambdaApplication   : Starting SpringNativeAwsLambdaApplication v0.0.1-SNAPSHOT using Java 11.0.11 on 169.254.206.69 with PID 9 (/var/task/spring-native-aws-lambda started by sbx_user1051 in /var/task)
2022-07-05 10:57:12.810  INFO 9 --- [           main] c.c.s.SpringNativeAwsLambdaApplication   : No active profile set, falling back to default profiles: default
2022-07-05 10:57:12.842  INFO 9 --- [           main] c.c.s.SpringNativeAwsLambdaApplication   : Started SpringNativeAwsLambdaApplication in 0.18 seconds (JVM running for 0.368)
2022-07-05 10:57:12.843  INFO 9 --- [           main] o.s.c.f.a.aws.CustomRuntimeEventLoop     : Starting spring-cloud-function CustomRuntimeEventLoop
2022-07-05 10:57:12.853  INFO 9 --- [           main] o.s.c.f.a.aws.CustomRuntimeEventLoop     : Entering event loop
2022-07-05 10:57:12.857  INFO 9 --- [           main] o.s.c.f.c.c.SimpleFunctionRegistry       : Located function: exampleFunction<class com.coffeebeans.springnativeawslambda.model.Request, class com.coffeebeans.springnativeawslambda.model.Response>
2022-07-05 10:57:12.858  INFO 9 --- [           main] o.s.c.f.a.aws.CustomRuntimeEventLoop     : Located function exampleFunction
2022-07-05 10:57:13.003  INFO 9 --- [           main] o.s.c.f.adapter.aws.AWSLambdaUtils       : Incoming JSON Event: {}
2022-07-05 10:57:13.142  INFO 9 --- [           main] o.s.c.f.adapter.aws.AWSLambdaUtils       : Incoming MAP: {}
2022-07-05 10:57:13.142  INFO 9 --- [           main] o.s.c.f.adapter.aws.AWSLambdaUtils       : Incoming request headers: {date=Tue, 05 Jul 2022 10:57:12 GMT, content-length=2, lambda-runtime-trace-id=Root=1-62c41907-49107e283c55fe060a1a7d1b;Parent=1185ecc24f956e19;Sampled=0, lambda-runtime-aws-request-id=58238b51-f2e4-4983-9955-895255220bed, id=9bbe0f33-253b-f795-dbd5-b6eb2b36753e, contentType=application/json, lambda-runtime-invoked-function-arn=arn:aws:lambda:ap-northeast-1:536824749084:function:PacFirstVersion, lambda-runtime-deadline-ms=1657018692857, timestamp=1657018633003}
2022-07-05 10:57:13.222  INFO 9 --- [           main] c.c.s.functions.ExampleFunction          : Converting request into a response...1
2022-07-05 10:57:13.284 ERROR 9 --- [           main] o.s.boot.SpringApplication               : Application run failed
java.lang.IllegalStateException: Failed to execute CommandLineRunner
at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:794) ~[spring-native-aws-lambda:2.5.6]
at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775) ~[spring-native-aws-lambda:2.5.6]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) ~[spring-native-aws-lambda:2.5.6]
at org.springframework.cloud.function.context.FunctionalSpringApplication.run(FunctionalSpringApplication.java:88) ~[na:na]
at org.springframework.cloud.function.context.FunctionalSpringApplication.run(FunctionalSpringApplication.java:83) ~[na:na]
at com.coffeebeans.springnativeawslambda.SpringNativeAwsLambdaApplication.main(SpringNativeAwsLambdaApplication.java:18) ~[spring-native-aws-lambda:0.0.1-SNAPSHOT]
Caused by: com.amazonaws.AmazonClientException: Unable to load parition metadata from com/amazonaws/partitions/endpoints.json
at com.amazonaws.partitions.PartitionsLoader.build(PartitionsLoader.java:82) ~[na:na]
at com.amazonaws.regions.RegionMetadataFactory.create(RegionMetadataFactory.java:30) ~[na:na]
at com.amazonaws.regions.RegionUtils.initialize(RegionUtils.java:66) ~[na:na]
at com.amazonaws.regions.RegionUtils.getRegionMetadata(RegionUtils.java:54) ~[na:na]
at com.amazonaws.regions.RegionUtils.getRegion(RegionUtils.java:107) ~[na:na]
at com.amazonaws.client.builder.AwsClientBuilder.withRegion(AwsClientBuilder.java:233) ~[na:na]
at com.amazonaws.client.builder.AwsClientBuilder.withRegion(AwsClientBuilder.java:222) ~[na:na]
at com.coffeebeans.springnativeawslambda.functions.ExampleFunction.apply(ExampleFunction.java:30) ~[na:na]
at com.coffeebeans.springnativeawslambda.functions.ExampleFunction.apply(ExampleFunction.java:21) ~[na:na]
at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeFunctionAndEnrichResultIfNecessary(SimpleFunctionRegistry.java:842) ~[na:na]
at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeFunction(SimpleFunctionRegistry.java:798) ~[na:na]
at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:663) ~[na:na]
at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:506) ~[na:na]
at org.springframework.cloud.function.adapter.aws.CustomRuntimeEventLoop.eventLoop(CustomRuntimeEventLoop.java:99) ~[spring-native-aws-lambda:3.1.4]
at org.springframework.cloud.function.adapter.aws.CustomRuntimeInitializer.lambda$null$0(CustomRuntimeInitializer.java:47) ~[na:na]
at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791) ~[spring-native-aws-lambda:2.5.6]
... 5 common frames omitted
END RequestId: 58238b51-f2e4-4983-9955-895255220bed
REPORT RequestId: 58238b51-f2e4-4983-9955-895255220bed	Duration: 505.18 ms	Billed Duration: 1003 ms	Memory Size: 128 MB	Max Memory Used: 113 MB	Init Duration: 497.74 ms
RequestId: 58238b51-f2e4-4983-9955-895255220bed Error: Runtime exited with error: exit status 1Runtime.ExitError
2022-07-05 10:57:14.040  INFO 9 --- [           main] o.s.nativex.NativeListener               : This application is bootstrapped with code generated with Spring AOT
2022-07-05 10:57:14.155  INFO 9 --- [           main] o.s.c.f.a.aws.CustomRuntimeInitializer   : AWS Handler: exampleFunction
2022-07-05 10:57:14.161  INFO 9 --- [           main] c.c.s.SpringNativeAwsLambdaApplication   : Starting SpringNativeAwsLambdaApplication v0.0.1-SNAPSHOT using Java 11.0.11 on 169.254.206.69 with PID 9 (/var/task/spring-native-aws-lambda started by sbx_user1051 in /var/task)
2022-07-05 10:57:14.161  INFO 9 --- [           main] c.c.s.SpringNativeAwsLambdaApplication   : No active profile set, falling back to default profiles: default
2022-07-05 10:57:14.289  INFO 9 --- [           main] c.c.s.SpringNativeAwsLambdaApplication   : Started SpringNativeAwsLambdaApplication in 0.561 seconds (JVM running for 0.731)
2022-07-05 10:57:14.390  INFO 9 --- [           main] o.s.c.f.a.aws.CustomRuntimeEventLoop     : Starting spring-cloud-function CustomRuntimeEventLoop
2022-07-05 10:57:14.400  INFO 9 --- [           main] o.s.c.f.a.aws.CustomRuntimeEventLoop     : Entering event loop

```
my source
```java
public class ExampleFunction implements Function<Request, Response> {
  private static AmazonDynamoDB amazonDynamoDBClient = null;
  private static Table table = null;
  @Override
  public Response apply(final Request request) {
    log.info("Converting request into a response...");
    //mysource
    amazonDynamoDBClient = AmazonDynamoDBClientBuilder.standard().withCredentials(new DefaultAWSCredentialsProviderChain()).withRegion(Regions.AP_NORTHEAST_1).build();
    table = new DynamoDB(amazonDynamoDBClient).getTable(DynamoConstants.TABLE_NAME);
......
```

mvn dependency
```
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-dynamodb</artifactId>
      <version>1.11.46</version>
    </dependency>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>amazon-kinesis-client</artifactId>
      <version>1.2.1</version>
      <scope>compile</scope>
    </dependency>
```

**Comment by oubidar-Abderrahim** [comment]
Hi, I took a look into the stacktrace of the issue and I can't find any relation to GraalVM, this might be an issue for SpringBoot, therefore I suggest to open an issue on their repository instead.

**Comment by zhoujiuzhou9** [comment]
> Hi, I took a look into the stacktrace of the issue and I can't find any relation to GraalVM, this might be an issue for SpringBoot, therefore I suggest to open an issue on their repository instead.

Thank you for reply to me
