### ISSUE TITLE
Quarkus generated Feature not being detected after d727a0f9fdb6bc04a7445ed77a217ce4ced2d199

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#4736]
**Describe the issue**

d727a0f9fdb6bc04a7445ed77a217ce4ced2d199 introduced [a regression in Quarkus Nightly builds](https://github.com/oracle/graal/runs/7422088389?check_suite_focus=true#step:8:311).

**Steps to reproduce the issue**
```
git clone git@github.com:quarkusio/quarkus.git --depth 1
cd quarkus
./mvnw -Dquickly # This will take some time...
export GRAALVM_HOME=~/path/to/graal/build
./mvnw -Dnative -pl integration-tests/main -Dnative.surefire.skip -Dformat.skip -Dno-descriptor-tests clean package -Dquarkus.native.container-build=false
```

**Describe GraalVM and your environment:**
 - GraalVM version: **d727a0f9fdb6bc04a7445ed77a217ce4ced2d199**
 - JDK major version: **11**
 - OS: **Ubuntu Github Runner**
 - Architecture: **AMD64**

**More details**

The resulting output looks like the following:

```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] /home/zakkak/code/mandrel-packaging/mandrel-bisect/bin/native-image -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dcom.sun.xml.bind.v2.bytecode.ClassTailor.noOptimize=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Duser.language=en -J-Duser.country=IE -J-Dfile.encoding=UTF-8 --features=io.quarkus.hibernate.orm.runtime.graal.DisableLoggingFeature,io.quarkus.caffeine.runtime.graal.CacheConstructorsFeature,io.quarkus.jdbc.postgresql.runtime.graal.SQLXMLFeature,io.quarkus.websockets.client.runtime.DisableLoggingFeature,io.quarkus.runner.Feature,io.quarkus.runtime.graal.ResourcesFeature,io.quarkus.runtime.graal.DisableLoggingFeature,io.quarkus.hibernate.validator.runtime.DisableLoggingFeature -H:-ParseOnce -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -H:ReflectionConfigurationFiles=reflection-config.json -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -J-Djava.awt.headless=true -H:FallbackThreshold=0 --link-at-build-time -H:+ReportExceptionStackTraces -H:+AddAllCharsets -H:EnableURLProtocols=http -H:NativeLinkerOption=-no-pie -H:-UseServiceLoaderFeature -H:+StackTrace -J--add-exports=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.proxy=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.localization=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.base/com.oracle.svm.util=ALL-UNNAMED quarkus-integration-test-main-999-SNAPSHOT-runner -jar quarkus-integration-test-main-999-SNAPSHOT-runner.jar
========================================================================================================================
GraalVM Native Image: Generating 'quarkus-integration-test-main-999-SNAPSHOT-runner' (executable)...
========================================================================================================================
[1/7] Initializing...
                                                                                    (0.0s @ 0.54GB)
Error: Feature io.quarkus.runner.Feature class not found on the classpath. Ensure that the name is correct and that the class is on the classpath.
com.oracle.svm.core.util.UserError$UserException: Feature io.quarkus.runner.Feature class not found on the classpath. Ensure that the name is correct and that the class is on the classpath.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.registerFeatures(FeatureHandler.java:135)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:847)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:570)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:530)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
------------------------------------------------------------------------------------------------------------------------
                        0.5s (4.8% of total time) in 12 GCs | Peak RSS: 1.01GB | CPU load: 3.00
========================================================================================================================
Failed generating 'quarkus-integration-test-main-999-SNAPSHOT-runner' after 10.4s.
Error: Image build request failed with exit status 1
```

Openning `quarkus-integration-test-main-999-SNAPSHOT-runner.jar` we see that `io.quarkus.runner.Feature` is present.

It is also interesting that this class is used by other tests without any issues, e.g.,
```
./mvnw -Dnative -pl integration-tests/jaxb -Dnative.surefire.skip -Dformat.skip -Dno-descriptor-tests clean package -Dquarkus.native.container-build=false
```

Works as expected.

cc @peter-hofer @fniephaus

**Comment by zakkak** [comment]
This is a Quarkus issue (not sure why it only shows up on the `main` test though.

Quarkus tries to access `com.oracle.svm.reflect.serialize.hosted.SerializationFeature` which has now been moved to `com.oracle.svm.hosted.reflect.serialize.SerializationFeature`.
https://github.com/quarkusio/quarkus/blob/dee454976827387e088523585968717cc15c82dc/core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageFeatureStep.java#L591-L592

**Comment by zakkak** [comment]
@christianwimmer  I was wondering if the refactoring in 22.3 could be used to make `SerializationFeature` public API as discussed in https://github.com/oracle/graal/discussions/4616?

**Comment by christianwimmer** [comment]
@olpaw will work in the next weeks to add proper API for all internals that we find in Quarkus. Existing classes like  `SerializationFeature` themselves cannot be declared public API because they are in the wrong package - all supported API is in the `org.graalvm.nativeimage` package, so new API that Quarkus can use will be added there.

**Comment by fniephaus** [comment]
If you like to help us with this, @zakkak, a complete list of all SVM internals used by Quarkus would be great.

**Comment by zakkak** [comment]
Nice. I will be out of office most of August but I believe @galderz will be able to help you with that :)

**Comment by galderz** [comment]
@fniephaus We're a bit thin at the moment with people off. Didn't @christianwimmer already collect a list of SVM usages in Quarkus? He mentioned having done during the monthly call where we discussed API changes.

As a FYI, following up that call I noted some of the things that seemed relevant to us in https://github.com/quarkusio/quarkus/issues/25943. Issues with serialization were pointed out there too.

**Comment by zakkak** [comment]
Fixed in https://github.com/quarkusio/quarkus/pull/26856
