### ISSUE TITLE
OutOfMemoryError with the tracing agent

### ISSUE THREAD

**Issue by sdeleuze** [oracle/graal#4737]
Regardless of the size of memory allocated to run the tracing agent on Hibernate test suite, we get `OutOfMemoryError` I think toward the end of the execution of the tests.
```
Exception in thread "main" java.lang.OutOfMemoryError
        at java.base/java.lang.AbstractStringBuilder.hugeCapacity(AbstractStringBuilder.java:214)
        at java.base/java.lang.AbstractStringBuilder.newCapacity(AbstractStringBuilder.java:206)
        at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:173)
        at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:686)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:232)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.json.JSONParser.readFully(JSONParser.java:471)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.json.JSONParser.<init>(JSONParser.java:56)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.configure.ConfigurationParser.parseAndRegister(ConfigurationParser.java:71)
        at org.graalvm.nativeimage.configure/com.oracle.svm.configure.ConfigurationTool.createConditionalConfig(ConfigurationTool.java:422)
        at org.graalvm.nativeimage.configure/com.oracle.svm.configure.ConfigurationTool.main(ConfigurationTool.java:106)
```

To reproduce run `./gradlew clean hibernate-core:test --tests "org.hibernate.orm.test.*" -Pdb=h2 -Pagent` on https://github.com/christophstrobl/hibernate-orm/tree/labs/native-agent.

Please tag this issue with the `spring` label.

**Comment by sdeleuze** [comment]
Slightly different error with Java 17 when I set `-Xmx=8g`
```
Exception in thread "main" java.lang.OutOfMemoryError: Required array length 2147483639 + 9 is too large
        at java.base/jdk.internal.util.ArraysSupport.hugeLength(ArraysSupport.java:649)
        at java.base/jdk.internal.util.ArraysSupport.newLength(ArraysSupport.java:642)
        at java.base/java.lang.AbstractStringBuilder.newCapacity(AbstractStringBuilder.java:257)
        at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:229)
        at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:740)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:233)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.json.JSONParser.readFully(JSONParser.java:471)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.json.JSONParser.<init>(JSONParser.java:56)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.configure.ConfigurationParser.parseAndRegister(ConfigurationParser.java:71)
        at org.graalvm.nativeimage.configure/com.oracle.svm.configure.ConfigurationTool.createConditionalConfig(ConfigurationTool.java:422)
        at org.graalvm.nativeimage.configure/com.oracle.svm.configure.ConfigurationTool.main(ConfigurationTool.java:106)
```
