### ISSUE TITLE
native image trace agent NullPointerException

### ISSUE THREAD

**Issue by ningpengtao-coder** [oracle/graal#4748]
java.lang.NullPointerException: null
    at java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:473)
    at java.util.Comparators$NullComparator.compare(Comparators.java:85)
    at java.util.Comparator.lambda$thenComparing$36697e65$1(Comparator.java:221)
    at java.util.TimSort.binarySort(TimSort.java:296)
    at java.util.TimSort.sort(TimSort.java:221)
    at java.util.Arrays.sort(Arrays.java:1307)
    at java.util.ArrayList.sort(ArrayList.java:1721)
    at com.oracle.svm.configure.json.JsonPrinter.printCollection(JsonPrinter.java:43)
    at com.oracle.svm.configure.config.ConfigurationType.printJson(ConfigurationType.java:381)
    at com.oracle.svm.configure.config.TypeConfiguration.printJson(TypeConfiguration.java:80)
    at com.oracle.svm.agent.tracing.ConfigurationResultWriter.writeToDirectory(ConfigurationResultWriter.java:89)
    at com.oracle.svm.agent.NativeImageAgent.writeConfigurationFiles(NativeImageAgent.java:514)
    at com.oracle.svm.agent.NativeImageAgent.onUnloadCallback(NativeImageAgent.java:587)
    at com.oracle.svm.jvmtiagentbase.JvmtiAgentBase.onUnload(JvmtiAgentBase.java:267)

**Comment by oubidar-Abderrahim** [comment]
Hi, I have to close this issue as there isn't much to work on. Please follow the template for reporting an issue in the GraalVM repository and include a description of the issue, the full stacktrace, a reproducer with detailed steps, and information about the environment used (GraalVM version, OS...)
