### ISSUE TITLE
Implement StackWalker.getMethodType

### ISSUE THREAD

**Issue by mhalbritter** [oracle/graal#4755]
Hello!

I have this small piece of code:

```java
StackWalker.getInstance(Option.RETAIN_CLASS_REFERENCE).forEach(i -> {
  System.out.println(i.getDeclaringClass());
  System.out.println(i.getMethodType());
});
```

The call to `getDeclaringClass` works, the `getMethodType` doesn't. It throws this exception:

```
Exception in thread "main" java.lang.UnsupportedOperationException
        at java.lang.StackWalker$StackFrame.getMethodType(StackWalker.java:148)
        at graal.filter.test.App.lambda$main$0(App.java:9)
        at com.oracle.svm.core.jdk.Target_java_lang_StackWalker$1.visitFrame(Target_java_lang_StackWalker.java:98)
        at com.oracle.svm.core.stack.JavaStackFrameVisitor.visitFrame(JavaStackFrameVisitor.java:49)
        at com.oracle.svm.core.stack.StackFrameVisitor.visitFrame(StackFrameVisitor.java:56)
        at com.oracle.svm.core.stack.StackFrameVisitor.visitFrame(StackFrameVisitor.java:36)
        at com.oracle.svm.core.stack.JavaStackWalker.callVisitor(JavaStackWalker.java:302)
        at com.oracle.svm.core.stack.JavaStackWalker.doWalk(JavaStackWalker.java:282)
        at com.oracle.svm.core.stack.JavaStackWalker.walkCurrentThread(JavaStackWalker.java:253)
        at com.oracle.svm.core.stack.JavaStackWalker.walkCurrentThread(JavaStackWalker.java:245)
        at java.lang.StackWalker.forEach(StackWalker.java:94)
        at graal.filter.test.App.main(App.java:7)
```

The JavaDoc for `StackWalker.Option.RETAIN_CLASS_REFERENCE` says:

![image](https://user-images.githubusercontent.com/98899556/180783656-7e6c9af0-3199-4630-96e7-8ed100560493.png)

I consider this a bug because the contract of `StackWalker` is violated.

```
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06, mixed mode, sharing)
```

**Comment by mhalbritter** [comment]
Please label this bug as `spring`, thanks!

**Comment by christianwimmer** [comment]
Originally we did not implement that method because the necessary metadata was not available at native image run time. But I think by now we have all the data available, since we can also create `java.lang.reflect.Method` objects with full signature for all reachable methods.
