### ISSUE TITLE
MIDI IN events not handled by native image 

### ISSUE THREAD

**Issue by java71** [oracle/graal#4780]
I wrote a simple program that capture MIDI In events and print received message. Configuration is Windows10 + Graalvm 17 + Eclipse + standard MIDI keyboard.

The program is a simple self-content file. All works properly using JVM. MIDI out events are produced and MIDI in events are captures.

The problem appears when this program is turned into EXE. Generation is performed without any problem. MIDI out events are produced and OK But as I hit a keyboard key, the MIDI in event causes an exception.

Exception in thread "Java Sound MidiInDevice Thread" java.lang.NoSuchMethodError: com.sun.media.sound.MidiInDevice.callbackShortMessage(IJ)V
        at com.oracle.svm.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1247)
        at com.oracle.svm.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1232)
        at com.oracle.svm.jni.functions.JNIFunctions.GetMethodID(JNIFunctions.java:412)
        at com.sun.media.sound.MidiInDevice.nGetMessages(MidiInDevice.java)
        at com.sun.media.sound.MidiInDevice.run(MidiInDevice.java:127)
        at java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
        at com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:143)

I tried to ask for initialization at 'build-time' or at 'run-time' but the problem persists.
The environment is simple : only WINDOWS with command-line tools ! Nothing else !
I think the function is not handled by native image. Is it a bug or is there a problem in my source code ?

Sorry but I do not understand how to insert colored code in this section, so I attach the simple code I wrote.
I insert also generated 'exe' file generated on WINDOWS 10 environment.
Many thanks for your help

[HelloMidiIn.zip](https://github.com/oracle/graal/files/9235932/HelloMidiIn.zip)
.

**Comment by oubidar-Abderrahim** [comment]
Hi, from the stacktrace I see JNI, did you try generating the config files before building your image? if no please check here on how to do so: https://www.graalvm.org/22.0/reference-manual/native-image/Agent/
Also check here for using JNI in native image: https://www.graalvm.org/22.0/reference-manual/native-image/JNI/

**Comment by java71** [comment]
Many thanks for the information.
I was not aware of these problems...
I used your links and now... it waoks properly.
Great advice !
