### ISSUE TITLE
Native-image doesn't build if I include jmisb dependency

### ISSUE THREAD

**Issue by calebdkofahl** [oracle/graal#4782]
I am trying to create a native-image using GraalVM's native-image and getting the following error:

```shell
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
========================================================================================================================
GraalVM Native Image: Generating 'app-1.0.0-jar-with-dependencies' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                    (5.8s @ 0.22GB)
 Version info: 'GraalVM 22.2.0 Java 11 CE'
 Java version info: '11.0.16+8-jvmci-22.2-b06'
 C compiler: cc (apple, x86_64, 13.1.6)
 Garbage collector: Serial GC
[2/7] Performing analysis...  [*]                                                                       (17.1s @ 2.59GB)
   3,373 (78.04%) of  4,322 classes reachable
   3,892 (50.78%) of  7,664 fields reachable
  19,176 (50.13%) of 38,250 methods reachable
     351 classes,    75 fields, and 1,013 methods registered for reflection

48 fatal errors detected:
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS_Unsafe_compareAndSwapLong_d44cf3dbd79fe11bdbf37794e85c4e49eea12682(com.oracle.svm.jni.nativeapi.JNIEnvironment, com.oracle.svm.jni.nativeapi.JNIObjectHandle, com.oracle.svm.jni.nativeapi.JNIMethodId, com.oracle.svm.jni.nativeapi.JNIObjectHandle, long, long, long) 
Parsing context: <no parsing context available> 

	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:152)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:104)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:83)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraph(MethodTypeFlow.java:65)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultAnalysisPolicy.staticRootMethodGraph(DefaultAnalysisPolicy.java:182)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis.lambda$addRootMethod$0(PointsToAnalysis.java:458)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$2.run(PointsToAnalysis.java:658)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.graalvm.compiler.debug.GraalError: unimplemented
	at jdk.internal.vm.compiler/org.graalvm.compiler.debug.GraalError.unimplemented(GraalError.java:39)
	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.graphbuilderconf.GraphBuilderContext.pop(GraphBuilderContext.java:104)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.StandardGraphBuilderPlugins$UnsafeAccessPlugin.createUnsafeAccess(StandardGraphBuilderPlugins.java:1312)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.StandardGraphBuilderPlugins$UnsafeCompareAndSwapPlugin.apply(StandardGraphBuilderPlugins.java:1428)
	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.graphbuilderconf.InvocationPlugin.execute(InvocationPlugin.java:300)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.tryInvocationPlugin(PEGraphDecoder.java:1082)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.trySimplifyInvoke(PEGraphDecoder.java:996)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.handleInvoke(PEGraphDecoder.java:957)
	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.processNextNode(GraphDecoder.java:817)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.processNextNode(InlineBeforeAnalysis.java:240)
	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:548)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.decode(PEGraphDecoder.java:833)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysis.decodeGraph(InlineBeforeAnalysis.java:98)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:176)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:343)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:93)
	... 13 more
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST_Unsafe_compareAndSwapLong_d44cf3dbd79fe11bdbf37794e85c4e49eea12682(com.oracle.svm.jni.nativeapi.JNIEnvironment, com.oracle.svm.jni.nativeapi.JNIObjectHandle, com.oracle.svm.jni.nativeapi.JNIMethodId, org.graalvm.word.WordBase) 
Parsing context: <no parsing context available> 

	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:152)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:104)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:83)
...
------------------------------------------------------------------------------------------------------------------------
                        1.5s (6.2% of total time) in 17 GCs | Peak RSS: 3.23GB | CPU load: 4.46
========================================================================================================================
Failed generating 'app-1.0.0-jar-with-dependencies' after 23.1s.
Error: Image build request failed with exit status 1
```
The command that produced these errors was `native-image -J-Xmx16g -jar target/app-1.0.0-jar-with-dependencies.jar`. I have also tried `native-image -jar target/app-1.0.0-jar-with-dependencies.jar` and other variations with the same errors being produced.

Here is my pom file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <version>1.0.0</version>
    <groupId>com.example</groupId>
    <artifactId>app</artifactId>
    <packaging>jar</packaging>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <maven.core.version>3.8.6</maven.core.version>
        <maven.version>3.3.9</maven.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.jmisb</groupId>
            <artifactId>jmisb-api</artifactId>
            <version>1.11.0</version>
        </dependency>
        <dependency>
            <groupId>org.locationtech.jts</groupId>
            <artifactId>jts-core</artifactId>
            <version>1.18.2</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.32</version>
        </dependency>
    </dependencies>

    <build>
    <pluginManagement><!-- lock down plugins versions to avoid using Maven defaults (may be moved to parent pom) -->
      <plugins>
        <!-- clean lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#clean_Lifecycle -->
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.1.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
        </plugin>
        <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-assembly-plugin</artifactId>
              <version>3.3.0</version>
              <configuration>
                  <descriptorRefs>
                      <descriptorRef>jar-with-dependencies</descriptorRef>
                  </descriptorRefs>
                  <archive>
                      <manifest>
                          <!-- <addClasspath>true</addClasspath> -->
                          <mainClass>com.example.App</mainClass>
                      </manifest>
                  </archive>
              </configuration>
              <executions>
                  <execution>
                      <id>make-assembly</id>
                      <goals>
                          <goal>single</goal>
                      </goals>
                      <phase>package</phase>
                  </execution>
              </executions>
          </plugin>
      </plugins>
    </pluginManagement>
  </build>
  </project>
```

I am using maven to build the app which just prints the first command line arg to stdout. The jar file works fine, but native-image fails to build.

GraalVM version: 22.2.0 (java11)
native-image version: 22.2.0 (java11)

Just creating a basic printing app adding jmisb as a dependency will break native-image and reproduce the errors I am seeing. Please advise as to a solution for this issue.

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reporting this, Could you please provide the following information?

1. Did you try generating the config files before building your image? if not, please check here on how to do so: https://www.graalvm.org/22.0/reference-manual/native-image/Agent/
2. If this is still an issue, could you please share a reproducer we can use to debug? that would be much appreciated

**Comment by oubidar-Abderrahim** [comment]
Closed for inactivity
