### ISSUE TITLE
java.lang.NullPointerException in ReflectionDataBuilder

### ISSUE THREAD

**Issue by yschimke** [oracle/graal#4787]
**Describe the issue**

```
Fatal error: java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at java.base/java.util.Collections$SetFromMap.add(Collections.java:5566)
	at com.oracle.svm.reflect.hosted.ReflectionDataBuilder.lambda$register$0(ReflectionDataBuilder.java:133)
	at com.oracle.svm.hosted.ConditionalConfigurationRegistry.registerConditionalConfiguration(ConditionalConfigurationRegistry.java:43)
	at com.oracle.svm.reflect.hosted.ReflectionDataBuilder.register(ReflectionDataBuilder.java:129)
	at org.graalvm.sdk/org.graalvm.nativeimage.impl.ReflectionRegistry.lambda$register$0(ReflectionRegistry.java:49)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.graalvm.sdk/org.graalvm.nativeimage.impl.ReflectionRegistry.register(ReflectionRegistry.java:49)
	at org.graalvm.sdk/org.graalvm.nativeimage.hosted.RuntimeReflection.register(RuntimeReflection.java:72)
	at okhttp3.TestRegistration.registerStandardClass(TestRegistration.kt:60)
	at okhttp3.TestRegistration.registerJupiterClasses(TestRegistration.kt:54)
	at okhttp3.TestRegistration.beforeAnalysis(TestRegistration.kt:32)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:722)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:78)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:722)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:564)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:615)
```

A clear and concise description of the issue. We recommend using the [latest snapshot builds](https://github.com/graalvm/graalvm-ce-dev-builds/releases) to replicate the issue as  bugs are constantly being fixed in the master branch

**Steps to reproduce the issue**

Build https://github.com/square/okhttp/runs/7661312925?check_suite_focus=true
PR https://github.com/square/okhttp/pull/7409

Reproducible in CI

Command is 

`./gradlew -PgraalBuild native-image-tests:nativeImage`

**Describe GraalVM and your environment:**

[1/7] Initializing...                                                                                   (12.2s @ 0.33GB)
 Version info: 'GraalVM 22.2.0 Java 11 CE'
 Java version info: '11.0.16+8-jvmci-22.2-b06'
 C compiler: gcc (linux, x86_64, 9.4.0)
 Garbage collector: Serial GC
 3 user-specific feature(s)
 - okhttp3.TestRegistration
 - okhttp3.internal.graal.OkHttpFeature
 - org.graalvm.home.HomeFinderFeature: Finds GraalVM paths and its version number

**Comment by yschimke** [comment]
This is a bug in our Feature.

Changed to make it more obvious.  Feel free to close, or just make the error more obvious.

```
    val clazz: Class<*> = access.findClassByName(name) ?: throw IllegalStateException("Missing class $name")
    RuntimeReflection.register(clazz)
```
