### ISSUE TITLE
[native-image] simple http server fails on Cloud Foundry with NioSocketError

### ISSUE THREAD

**Issue by making** [oracle/graal#480]
I made a simple http server as following and built as a native image.

```java
package hello;

import com.sun.net.httpserver.HttpServer;

import java.io.OutputStream;
import java.net.InetSocketAddress;

public class HelloHttp {
    public static void main(String[] args) throws Exception {
        long start = System.nanoTime();
        HttpServer server = HttpServer.create(new InetSocketAddress(8080), 0);
        server.createContext("/", exchange -> {
            String response = "Hello World!";
            exchange.sendResponseHeaders(200, response.length());
            OutputStream os = exchange.getResponseBody();
            os.write(response.getBytes());
            os.close();
        });
        server.start();
        long elapsed = System.nanoTime() - start;
        System.out.println("Started in " + elapsed / 1_000_000.0 + " [ms]");
    }
}
```

This works on my laptop and docker container but fails on Cloud Foundry deployed with [binary-buildpack](https://github.com/cloudfoundry/binary-buildpack).

The error log follows

```
2018-06-19T17:21:55.274+09:00 [APP/PROC/WEB/0] [ERR] Exception in thread "main" java.lang.reflect.InvocationTargetException
2018-06-19T17:21:55.274+09:00 [APP/PROC/WEB/0] [ERR] at java.lang.Throwable.<init>(Throwable.java:310)
2018-06-19T17:21:55.274+09:00 [APP/PROC/WEB/0] [ERR] at java.lang.Exception.<init>(Exception.java:102)
2018-06-19T17:21:55.274+09:00 [APP/PROC/WEB/0] [ERR] at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:89)
2018-06-19T17:21:55.274+09:00 [APP/PROC/WEB/0] [ERR] at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)
2018-06-19T17:21:55.274+09:00 [APP/PROC/WEB/0] [ERR] at com.oracle.svm.reflect.proxies.Proxy_1_HelloHttp_main.invoke(Unknown Source)
2018-06-19T17:21:55.274+09:00 [APP/PROC/WEB/0] [ERR] at java.lang.reflect.Method.invoke(Method.java:498)
2018-06-19T17:21:55.274+09:00 [APP/PROC/WEB/0] [ERR] at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:173)
2018-06-19T17:21:55.274+09:00 [APP/PROC/WEB/0] [ERR] Caused by: java.net.SocketException: NioSocketError
2018-06-19T17:21:55.274+09:00 [APP/PROC/WEB/0] [ERR] at java.lang.Throwable.<init>(Throwable.java:265)
2018-06-19T17:21:55.274+09:00 [APP/PROC/WEB/0] [ERR] at java.lang.Exception.<init>(Exception.java:66)
2018-06-19T17:21:55.274+09:00 [APP/PROC/WEB/0] [ERR] at java.io.IOException.<init>(IOException.java:58)
2018-06-19T17:21:55.274+09:00 [APP/PROC/WEB/0] [ERR] at java.net.SocketException.<init>(SocketException.java:47)
2018-06-19T17:21:55.274+09:00 [APP/PROC/WEB/0] [ERR] at com.oracle.svm.core.posix.PosixJavaNIOSubstitutions$Util_sun_nio_ch_Net.handleSocketError(PosixJavaNIOSubstitutions.java:1284)
2018-06-19T17:21:55.274+09:00 [APP/PROC/WEB/0] [ERR] at com.oracle.svm.core.posix.PosixJavaNIOSubstitutions$Target_sun_nio_ch_Net.socket0(PosixJavaNIOSubstitutions.java:766)
2018-06-19T17:21:55.274+09:00 [APP/PROC/WEB/0] [ERR] at sun.nio.ch.Net.serverSocket(Net.java:415)
2018-06-19T17:21:55.274+09:00 [APP/PROC/WEB/0] [ERR] at sun.nio.ch.ServerSocketChannelImpl.<init>(ServerSocketChannelImpl.java:88)
2018-06-19T17:21:55.274+09:00 [APP/PROC/WEB/0] [ERR] at sun.nio.ch.SelectorProviderImpl.openServerSocketChannel(SelectorProviderImpl.java:56)
2018-06-19T17:21:55.274+09:00 [APP/PROC/WEB/0] [ERR] at java.nio.channels.ServerSocketChannel.open(ServerSocketChannel.java:108)
2018-06-19T17:21:55.274+09:00 [APP/PROC/WEB/0] [ERR] at sun.net.httpserver.ServerImpl.<init>(ServerImpl.java:97)
2018-06-19T17:21:55.274+09:00 [APP/PROC/WEB/0] [ERR] at sun.net.httpserver.HttpServerImpl.<init>(HttpServerImpl.java:50)
2018-06-19T17:21:55.274+09:00 [APP/PROC/WEB/0] [ERR] at sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(DefaultHttpServerProvider.java:35)
2018-06-19T17:21:55.274+09:00 [APP/PROC/WEB/0] [ERR] at com.sun.net.httpserver.HttpServer.create(HttpServer.java:130)
2018-06-19T17:21:55.274+09:00 [APP/PROC/WEB/0] [ERR] at hello.HelloHttp.main(HelloHttp.java:11)
2018-06-19T17:21:55.274+09:00 [APP/PROC/WEB/0] [ERR] ... 3 more
2018-06-19T17:21:55.278+09:00 [APP/PROC/WEB/0] [OUT] Exit status 0
```

This exception seems a general error and occurred in `else` clause, so It's difficult to dig into more.
https://github.com/oracle/graal/blob/vm-1.0.0-rc2/substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixJavaNIOSubstitutions.java#L1284

I understand this project might not be right place to ask this question but I would appreciate if you could answer if  there is any other reason to get this error?

The source code was also correct because I could successfully deploy this app as a normal jar file with java-buildpack. 

Here is the reproducible project.
https://github.com/making/hello-graal
I'll also ask cloud foundry team if there is any restriction.

Thanks

**Comment by Peter-B-Kessler** [comment]
With some work we could add the cause of the exception to the exception detail string.  I have filed an issue to fix that.  I am not sure it would help in this case: We know all the errors that are not the cause, because we are in the final `else` clause.

I also see that between JDK-8 and JDK-10, the HotSpot implementation of `handleSocketException` added a case for `ENOTCONN`.  I have filed an issue to add that.

I am hoping that the Cloud Foundry team has a suggestion.
