### ISSUE TITLE
NPE in runtime image generation

### ISSUE THREAD

**Issue by timboudreau** [oracle/graal#481]
I'm attempting to get a [Netty+Guice-based framework](https://github.com/timboudreau/acteur) generating all of the necessary metadata about dependency injection to be able to create native images using annotation processors, starting from [this article](https://medium.com/graalvm/instant-netty-startup-using-graalvm-native-image-generation-ed6f14ff7692) about running Netty (I expect the Guice part to be challenging).

However, the first attempt to actually build a native image of a demo app fails with a rather inscrutable `NullPointerException` in a dynamic proxy (see below).  The class being proxied is most likely [this one](https://google.github.io/guava/releases/23.0/api/docs/com/google/common/collect/FluentIterable.html) - an iterable that wraps a `Function` (most likely implemented as a lambda).  Since the failure is in `toString()`, I'd tend to expect the problem is an attempted call to `toString()` on the lambda, since what that should do is fairly ill-defined in dynamic proxies but it is necessary to do something, and the lambda it's wrapping likely looks very different than in a traditional Java runtime.

I've done some grepping of the Graal codebase for `InvocationHandler` implementations, but haven't found anything that looks like an obvious culprit (nor is it obvious how to build it from source anymore - I see the mx tool is gone, replaced by ... what?)

```
native-image -jar acteur-graal-demo-all.jar -H:ReflectionConfigurationFiles=reflective.json --report-unsupported-elements-at-runtime -da -H:CPUFeatures="SSE4_1,POPCNT,AVX,AES,CLMUL,MMX,SSE3,SSE4_2,TSC,CMOV"
Build on Server(pid: 17578, port: 39941)
   classlist:   1,265.42 ms
       (cap):   1,269.99 ms
       setup:   2,245.84 ms
  (typeflow):  21,665.97 ms
   (objects):   9,740.42 ms
  (features):     185.96 ms
    analysis:  32,465.18 ms
    universe:   1,123.77 ms
     (parse):   4,808.60 ms
    (inline):   6,086.68 ms
   (compile):  24,190.96 ms
     compile:  36,174.10 ms
       image:     493.52 ms
fatal error: java.lang.NullPointerException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:381)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:281)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:378)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.executeCompilation(NativeImageBuildServer.java:390)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$processCommand$8(NativeImageBuildServer.java:327)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.withJVMContext(NativeImageBuildServer.java:408)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.processCommand(NativeImageBuildServer.java:324)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.processRequest(NativeImageBuildServer.java:268)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$serve$7(NativeImageBuildServer.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.oracle.svm.reflect.proxies.Proxy_135_FluentIterable$2_iterator.toString(Unknown Source)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at com.oracle.svm.hosted.image.NativeImageHeap.addObjectToBootImageHeap(NativeImageHeap.java:383)
	at com.oracle.svm.hosted.image.NativeImageHeap.addObject(NativeImageHeap.java:255)
	at com.oracle.svm.hosted.image.NativeImageHeap.processAddObjectWorklist(NativeImageHeap.java:566)
	at com.oracle.svm.hosted.image.NativeImageHeap.addTrailingObjects(NativeImageHeap.java:116)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:839)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:364)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Processing image build request failed
```

**Comment by cstancu** [comment]
Are you using the rc2 release? This issue should be fixed. That proxy is generated by us for reflective accesses. The problem was that the proxy didn't have an invocation handler that could handle `toString` calls which are necessary for debugging and error reporting. Can you please try building from source using the [quick start guide](https://github.com/oracle/graal/tree/master/substratevm#quick-start)?

**Comment by timboudreau** [comment]
```
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-11)
GraalVM 1.0.0-rc2 (build 25.71-b01-internal-jvmci-0.43, mixed mode)
```
Specifically here we seem to be proxying the iterator produced by a proxy of an iterable, and something is calling `toString()` on the iterator.

**Comment by timboudreau** [comment]
Building based on quickstart with a fresh checkout of `mx` gets:
```
Archiving SVM_DRIVER... [dependency com.oracle.svm.driver updated]
bootstrap.native-image... [dependency SVM_DRIVER updated]
Skip building native-image executable: No SVM gate-run
Process Process-265:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tim/work/foreign/mx/mx.py", line 11687, in executeTask
    task.execute()
  File "/home/tim/work/foreign/mx/mx.py", line 809, in execute
    self.build()
  File "/home/tim/work/foreign/graal/substratevm/mx.substratevm/mx_substratevm.py", line 419, in build
    librarySupportDistribution=self.subject.librarySupportDistribution
  File "/home/tim/work/foreign/graal/substratevm/mx.substratevm/mx_substratevm.py", line 359, in bootstrap_native_image
    relsymlink(join(jvmci_path, symlink_name), join(native_image_root, 'lib', 'jvmci', symlink_name))
  File "/home/tim/work/foreign/graal/substratevm/mx.substratevm/mx_substratevm.py", line 158, in relsymlink
    os.symlink(os.path.relpath(target_path, dirname(dest_path)), dest_path)
OSError: [Errno 17] File exists
bootstrap.native-image failed
1 build tasks failed
```

**Comment by timboudreau** [comment]
Is that because the bootstrap JDK is the copy of graal I already have?

**Comment by cstancu** [comment]
> Is that because the bootstrap JDK is the copy of graal I already have?

That's probably the cause. You should try building with a **JVMCI JDK** from http://www.oracle.com/technetwork/oracle-labs/program-languages/downloads/index.html.

**Comment by timboudreau** [comment]
Okay, got it built, and now getting a different error much earlier :-)

```
tim@tim ~/work/foreign/graal/substratevm $ ../../mx/mx native-image -R:+PrintCompilation -R:+PrintImageObjectTree --verbose -jar /home/tim/work/trivial/acteur-graal-demo/target/acteur-graal-demo-all.jar -H:ReflectionConfigurationFiles=/home/tim/work/trivial/acteur-graal-demo/target/classes/META-INF/injection/reflective.json --report-unsupported-elements-at-runtime -da -H:CPUFeatures="SSE4_1,POPCNT,AVX,AES,CLMUL,MMX,SSE3,SSE4_2,TSC,CMOV"
Executing [
/opt/labsjdk1.8.0_172-jvmci-0.44/bin/java \
-Xbootclasspath/a:/home/tim/work/foreign/graal/substratevm/svmbuild/native-image-root/lib/boot/graal-sdk.jar \
-cp \
/home/tim/work/foreign/graal/substratevm/svmbuild/native-image-root/lib/svm/builder/svm.jar:/home/tim/work/foreign/graal/substratevm/svmbuild/native-image-root/lib/svm/builder/pointsto.jar:/home/tim/work/foreign/graal/substratevm/svmbuild/native-image-root/lib/svm/builder/objectfile.jar:/home/tim/work/foreign/graal/substratevm/svmbuild/native-image-root/lib/jvmci/graal.jar:/home/tim/work/foreign/graal/substratevm/svmbuild/native-image-root/lib/jvmci/jvmci-api.jar:/home/tim/work/foreign/graal/substratevm/svmbuild/native-image-root/lib/jvmci/jvmci-hotspot.jar \
-server \
-d64 \
-noverify \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-XX:-UseJVMCIClassLoader \
-XX:+UseJVMCICompiler \
-Dgraal.CompileGraalWithC1Only=false \
-XX:CICompilerCount=2 \
-Dgraal.VerifyGraalGraphs=false \
-Dgraal.VerifyGraalGraphEdges=false \
-Dgraal.VerifyGraalPhasesSize=false \
-Dgraal.VerifyPhases=false \
-Dgraal.EagerSnippets=true \
-Xss10m \
-Xms1g \
-Xmx6648961432 \
-Duser.country=US \
-Duser.language=en \
-Dsubstratevm.version=dev \
-Dgraalvm.version=dev \
-Dorg.graalvm.version=dev \
-Dcom.oracle.graalvm.isaot=true \
-Djvmci.class.path.append=/home/tim/work/foreign/graal/substratevm/svmbuild/native-image-root/lib/jvmci/graal.jar \
com.oracle.svm.hosted.NativeImageGeneratorRunner \
-imagecp \
/home/tim/work/foreign/graal/substratevm/svmbuild/native-image-root/lib/boot/graal-sdk.jar:/home/tim/work/foreign/graal/substratevm/svmbuild/native-image-root/lib/svm/builder/svm.jar:/home/tim/work/foreign/graal/substratevm/svmbuild/native-image-root/lib/svm/builder/pointsto.jar:/home/tim/work/foreign/graal/substratevm/svmbuild/native-image-root/lib/svm/builder/objectfile.jar:/home/tim/work/foreign/graal/substratevm/svmbuild/native-image-root/lib/jvmci/graal.jar:/home/tim/work/foreign/graal/substratevm/svmbuild/native-image-root/lib/jvmci/jvmci-api.jar:/home/tim/work/foreign/graal/substratevm/svmbuild/native-image-root/lib/jvmci/jvmci-hotspot.jar:/home/tim/work/foreign/graal/substratevm/svmbuild/native-image-root/lib/svm/library-support.jar:/home/tim/work/foreign/graal/substratevm:/home/tim/work/trivial/acteur-graal-demo/target/acteur-graal-demo-all.jar \
-H:Path=/home/tim/work/foreign/graal/substratevm \
-R:+PrintCompilation \
-R:+PrintImageObjectTree \
-H:Class=com.mastfrog.acteur.graal.demo.Main \
-H:Name=acteur-graal-demo-all \
-H:+ReportUnsupportedElementsAtRuntime \
-H:-RuntimeAssertions \
-H:CPUFeatures=SSE4_1,POPCNT,AVX,AES,CLMUL,MMX,SSE3,SSE4_2,TSC,CMOV \
-H:CLibraryPath=/home/tim/work/foreign/graal/substratevm/svmbuild/native-image-root/lib/svm/clibraries/linux-amd64 \
-H:ReflectionConfigurationFiles=/home/tim/work/trivial/acteur-graal-demo/target/classes/META-INF/injection/reflective.json
]
   classlist:   3,709.59 ms
       setup:     258.84 ms
error: Already registered: java.lang.reflect.Proxy.proxyClassCache
Error: Image building with exit status 1
```

**Comment by cstancu** [comment]
Do you have any substitutions for `java.lang.reflect.Proxy.proxyClassCache`. We `@Delete` that field in `com.oracle.svm.core.jdk.proxy.Target_java_lang_reflect_Proxy` so it wouldn't be possible to add another substitution.

**Comment by cstancu** [comment]
Another cause could be if you have `svm.jar` on the classpath when you build `acteur-graal-demo-all.jar` and it gets transitively packed into the `acteur-graal-demo-all.jar`,e.g., if you need the substitution API, especially if you have the `svm.jar` from `rc2`. Then when you run `mx native-image` it adds the current `svm.jar` on the class path and you end up with duplicated core substitutions, therefore the error. If you started from the [netty-native-demo](https://github.com/cstancu/netty-native-demo) project that is probably the case. I had a mistake in the `pom.xml` [discovered](https://github.com/cstancu/netty-native-demo/issues/1) and [fixed](https://github.com/cstancu/netty-native-demo/commit/128931e2f57491f1477be642fa3d41a310b0febb#diff-600376dffeb79835ede4a0b285078036R20) by @olpaw.

**Comment by timboudreau** [comment]
`svm.jar` being bundled into the JAR file was the problem.  I filtered out everything but `com.oracle.svm.core.annotate` and the image gets built.

Running it gets an immediate segfault:

```
[ [ SubstrateSegfaultHandler caught signal 11 ] ]

General Purpose Register Set Values: 

  RAX 0000000000000000
  RBX 00007fe79a90a8d0
  RCX 00007fe79a949fa0
  RDX 000055b2ae681378
  RBP 000055b2adefd9a0
  RSI 000055b2ae39d070
  RDI 00007fe79a949fa0
  RSP 00007ffdc4ef0628
  R8  000055b2adcacdb0
  R9  0000000000000080
  R10 000055b2adce2bf0
  R11 00007fe79a949690
  R12 0000000000000080
  R13 00007fe79a9495a0
  R14 00007fe79a9495a0
  R15 000055b2aea53260
  EFL 0000000000010202
  RIP 0000000000000000
  

JavaFrameAnchor dump:

  No anchors
  
DeoptStubPointer address: 0000000000000000

TopFrame info:

  
VMThreads info:

  VMThread 00007fe794000b20  STATUS_IN_NATIVE
  VMThread 000055b2aea53260  STATUS_IN_JAVA (safepoints disabled)
  
VM Thread State for current thread 000055b2aea53260:

  0 (8 bytes): com.oracle.svm.core.genscavenge.PinnedAllocatorImpl.openPinnedAllocator = null
  8 (8 bytes): com.oracle.svm.core.heap.NoAllocationVerifier.openVerifiers = null
  16 (8 bytes): com.oracle.svm.core.jdk.IdentityHashCodeSupport.hashCodeGeneratorTL = java.util.SplittableRandom  00007fe79a901ef8
  24 (8 bytes): com.oracle.svm.core.snippets.SnippetRuntime.currentException = null
  32 (8 bytes): com.oracle.svm.core.thread.JavaThreads.currentThread = java.lang.Thread  000055b2ae985de8
  40 (8 bytes): com.oracle.svm.core.thread.ThreadingSupportImpl.activeTimer = null
  48 (32 bytes): com.oracle.svm.core.genscavenge.ThreadLocalAllocation.pinnedTLAB = 
    000055b2aea53290: 0000000000000000 0000000000000000
    000055b2aea532a0: 0000000000000000 0000000000000000
    
  
  80 (32 bytes): com.oracle.svm.core.genscavenge.ThreadLocalAllocation.regularTLAB = 
    000055b2aea532b0: 00007fe79a900000 00007fe79aa00000
    000055b2aea532c0: 00007fe79a94a000 0000000000000000
    
  
  112 (8 bytes): com.oracle.svm.core.genscavenge.ThreadLocalAllocation.freeList = 0  0000000000000000
  120 (8 bytes): com.oracle.svm.core.posix.thread.PosixVMThreads.IsolateTL = 94598687557484880  0150150150150150
  128 (8 bytes): com.oracle.svm.core.stack.JavaFrameAnchors.lastAnchor = 0  0000000000000000
  136 (8 bytes): com.oracle.svm.core.thread.VMThreads.nextTL = 0  0000000000000000
  144 (4 bytes): com.oracle.svm.core.thread.Safepoint.safepointRequested = -57790  ffff1e42
  148 (4 bytes): com.oracle.svm.core.thread.Safepoint.safepointRequestedValueBeforeSafepoint = 0  00000000
  152 (4 bytes): com.oracle.svm.core.thread.VMOperationControl.isLockOwner = 0  00000000
  156 (4 bytes): com.oracle.svm.core.thread.VMThreads$StatusSupport.safepointsDisabledTL = 1  00000001
  160 (4 bytes): com.oracle.svm.core.thread.VMThreads$StatusSupport.statusTL = 1  00000001
  
VMOperation dump:

  No VMOperation in progress
  

RuntimeCodeCache dump:

  == [Recent RuntimeCodeCache operations: ]
  
  == [RuntimeCodeCache: 0 methods]
  
Deoptimizer dump:

  == [Recent Deoptimizer Events: 
  ]
  
Dump Counters:

  
Raw Stacktrace:

  00007ffdc4ef0628: 000055b2ad6f236d 000001009a949f70
  00007ffdc4ef0638: 00007fe79a9496b8 0000000000000000
  00007ffdc4ef0648: 00007fe79a948060 00007fe79a949fa0
  00007ffdc4ef0658: 000055b2ad6f2226 00007fe79a949fb8
  00007ffdc4ef0668: 000055b2adce2ee1 00007fe79a9369f0
  00007ffdc4ef0678: 00007fe79a949fa0 000055b2ae4e2538
  00007ffdc4ef0688: 000055b2ad86420b 00007fe79a938020
  00007ffdc4ef0698: 000055b2adcd0f30 00007fe79a938020
  00007ffdc4ef06a8: 00007fe79a938918 0000000000000000
  00007ffdc4ef06b8: 00007fe79a9388f8 00007fe79a9384f8
  00007ffdc4ef06c8: 00000001adf0ecb8 00007fe79a949fe0
  00007ffdc4ef06d8: 000055b2ae681578 0000001800000001
  00007ffdc4ef06e8: 00007fe79a949fb8 00007fe79a949fa0
  00007ffdc4ef06f8: 00007fe79a949f70 00007fe79a90a8d0
  00007ffdc4ef0708: 00007fe79a949f40 000055b2ae3f7590
  00007ffdc4ef0718: 00007fe79a940ed0 00007fe79a940ea0
  00007ffdc4ef0728: 000055b2ae3f2bf8 000055b2ae3f6d78
  00007ffdc4ef0738: 000055b2ad8c0504 000055b2ae3e2c30
  00007ffdc4ef0748: 000055b2ae4a5c38 00007fe79a93e678
  00007ffdc4ef0758: 00007fe79a937fc0 00007fe79a936a18
  00007ffdc4ef0768: 000055b2ad6efc86 00007fe79a9388e8
  00007ffdc4ef0778: 00007fe79a9388c0 00007fe79a9388f8
  00007ffdc4ef0788: 00007fe79a937fc0 00007fe79a936a18
  00007ffdc4ef0798: 000055b2ad7f2b29 00007fe79a9383f0
  00007ffdc4ef07a8: 000055b2adc47771 00007fe79a9386b8
  00007ffdc4ef07b8: 00000001ad8e4331 0000000000000000
  00007ffdc4ef07c8: 00007fe79a936a18 00007fe79a937fc0
  00007ffdc4ef07d8: 000055b2ad7f3b57 000055b2ae40c418
  00007ffdc4ef07e8: 0000000100000004 00007fe79a9375e0
  00007ffdc4ef07f8: 00007fe79a936a18 00007fe79a9383f0
  00007ffdc4ef0808: 000055b2adc4b7f9 000055b2ae41f0d8
  00007ffdc4ef0818: 00007fe79a937fc0 000055b2ae3abfd8
  00007ffdc4ef0828: 00007fe79a937498 000055b2ae3f6d78
  00007ffdc4ef0838: 000055b2ad721256 0000006000000001
  00007ffdc4ef0848: 000055b2ad711219 00007fe79a9367b0
  00007ffdc4ef0858: 00007fe79a937850 00007fe79a9376b0
  00007ffdc4ef0868: 000055b2adf0eb48 00007fe79a937f70
  00007ffdc4ef0878: 000055b2ae3abbe8 000000019a937498
  00007ffdc4ef0888: 00007fe79a937640 00007fe79a937f88
  00007ffdc4ef0898: 00007fe79a937470 00007fe79a937150
  00007ffdc4ef08a8: 00007fe79a937138 00007fe79a937510
  00007ffdc4ef08b8: 00007fe79a937390 00007fe79a937428
  00007ffdc4ef08c8: 000055b2ad7274dc 00007fe79a936578
  00007ffdc4ef08d8: 00007fe79a935970 000055b2adcd4690
  00007ffdc4ef08e8: 000055b2adcd45e0 00007fe79a9375b0
  00007ffdc4ef08f8: 00007fe79a937640 00007fe79a9370f0
  00007ffdc4ef0908: 000055b2ad6f07c6 00007fe79a9367b0
  00007ffdc4ef0918: 000055b2adf0eb78 00007fe79a9370f0
  00007ffdc4ef0928: 00007fe79a9367b0 000055b2ae3f6d78
  00007ffdc4ef0938: 000055b2ad86a54b 00007fe79a935a28
  00007ffdc4ef0948: 00007fe79a9366f8 000055b2ae3b0c10
  00007ffdc4ef0958: 00007fe79a935198 00007fe79a9367d8
  00007ffdc4ef0968: 000055b2ad86cd5b 00007fe79a936720
  00007ffdc4ef0978: 000055b2ad86a816 000055b2ae3f71a0
  00007ffdc4ef0988: 00007fe79a936720 00007fe79a935a28
  00007ffdc4ef0998: 000055b2ae3e6ea0 00007fe79a936720
  00007ffdc4ef09a8: 000055b2ad843a64 000055b2adcd4c80
  00007ffdc4ef09b8: 000055b2ae4a55b0 00007fe79a9023e8
  00007ffdc4ef09c8: 000055b2ae3e6ea0 00007fe79a902288
  00007ffdc4ef09d8: 000055b2ad838333 0000000000000000
  00007ffdc4ef09e8: 0000000000000000 0000000000000000
  00007ffdc4ef09f8: 0000000000000000 0000000000000000
  00007ffdc4ef0a08: 00007fe79a902330 00007fe79a902288
  00007ffdc4ef0a18: 00007fe79a9021c0 00007fe79a9010c8
  
Stacktrace Stage0:

  
Stacktrace Stage1:

  
Full Stacktrace:

  
Use runtime option -R:-InstallSegfaultHandler if you don't want to use SubstrateSegfaultHandler.

Bye bye ...
```

**Comment by cstancu** [comment]
@timboudreau can you provide the code and steps to replicate this?

**Comment by timboudreau** [comment]
I'm attempting to create an isolate a test case with few-to-no dependencies.  It seems likely that the segfault is caused by Guice calling `equals()` or `hashCode()` on an annotation instance found via reflection - a common pattern with Guice is to do something like:

```
@Inject
public class Foo(@Named("host") String host) { ... }
```

and when initializing the application you set up a binding, using a programmatically created annotation instance, e.g. `bind(String.class).annotatedWith(Names.named("host")).toInstance("timboudreau.com")`, which relies on the implementation of `Named` returned by `Names.named(String)` to equal and have the same hash code as the `Named` instance found via reflection.

I can tell you already that the hash codes do not match, and while calling `Names.named("host").equals(foundByReflectionAnno)` returns true, calling `foundByReflectionAnno.equals(Names.named("host"))` results in a segfault.

However, when I strip down the example to leave Guice out of it, containing copies of the annotations and the `Named` implementation from Guice, I get other bizarre behavior - the following code
```
public class AnnotationTester {

    @Named(value = "doit")
    @Inject
    ExecutorService exe;

    @Inject
    public AnnotationTester() {
        try {
            Field f = AnnotationTester.class.getDeclaredField("exe");
            if (f != null) {
                System.out.println("FOUND FIELD");
            }
//            System.out.println("GOT FIELD " + f);
//            new Exception("Got field " + f).printStackTrace();
            Named named = f.getAnnotation(Named.class);
//            System.out.println("GOT NAMED " + named);
            if (named != null) {
                Named programmatic = new NamedImpl("doit");
                int genHashCode = programmatic.hashCode();

                System.out.println("GENERATED ANNO HASH CODE " + genHashCode);
                int compiledHashCode = named.hashCode();
                System.out.println("COMPILED ANNO HASH CODE " + compiledHashCode);
                boolean equal2 = programmatic.equals(named);
//                System.out.println("PROGRAMMATIC EQUALS COMPILED? " + equal2);
//                System.out.flush();
                //                    boolean equal = named.equals(programmatic);
                //                    System.out.println("COMPILED EQUALS PROGRAMMATIC? " + equal);
            } else {
                System.out.println("Annotation missing");
            }
        } catch (Throwable ex) {
            ex.printStackTrace(System.err);
            System.err.flush();
            System.exit(1);
        }
    }
}
```

goes into an endless loop printing "FOUND FIELD" and eventually segfaults (unclear why the behavior would change when _removing_ Guice and several other things from the image).  Moving this code out of the constructor does not change the behavior.  Printing a stack trace shows that the call to `programmatic.hashCode()` loops back (!!!).

**Comment by timboudreau** [comment]
Okay, [here is an isolated test case](https://timboudreau.com/files/graal-reflection-bug-481.tar.xz) which demonstrates

 * The looping problem (which makes it impossible to further diagnose the annotation problem)
 * The annotation problem (before I removed the dependency on Guice the looping issue was not there, and it did show the hash codes were wrong and segfaulted on `equals()`)

Set the environment variables `$SUBSTRATE_HOME` and `$MX_HOME` to run it, and have `JAVA_HOME` set to the labs JDK and `mvn` on the classpath.

**Comment by timboudreau** [comment]
FWIW, if we get past that, the next problem in getting Guice to work is that cglib tries to call a constructor on `ProtectionDomain`.

**Comment by olpaw** [comment]
@timboudreau thanks for the isolated test case. I will have a look and report back.

**Comment by timboudreau** [comment]
Verified that both the looping behavior and annotation equality are fixed as of 2c597bf501948b6f46856b754a98928b34da9037
