### ISSUE TITLE
KMongo / Fasterxml - Cannot construct instance of `myClass`

### ISSUE THREAD

**Issue by ThraaxSession** [oracle/graal#4830]
**Describe the issue**
```
19:15:08.209 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `technology.iatlas.spaceup.dto.db.Server` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: de.undercouch.bson4jackson.io.LittleEndianInputStream@c58ede5; pos: 0]
java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `technology.iatlas.spaceup.dto.db.Server` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: de.undercouch.bson4jackson.io.LittleEndianInputStream@c58ede5; pos: 0]
        at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:70)
        at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:722)
        at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:86)
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:191)
        at com.mongodb.client.internal.FindIterableImpl.first(FindIterableImpl.java:213)
        at kotlin.collections.KMongoIterableKt.firstOrNull(KMongoIterable.kt:67)
```

My Server class:
```
package technology.iatlas.spaceup.dto.db

data class Server(
    var installed: Boolean = false,
    var apiKey: String
)
```

My KMongo call:
![image](https://user-images.githubusercontent.com/3085830/185759022-0118c6d8-12b5-45d5-8f57-035ac860bb5a.png)

**Steps to reproduce the issue**
Add these dependencies to Micronaut and build native image:
```
implementation('org.litote.kmongo:kmongo:4.6.1')
implementation('org.litote.kmongo:kmongo-async:4.6.1')

implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
implementation("com.fasterxml.jackson.datatype:jackson-datatype-jdk8")
implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310")
```

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **[e.g. EE 19.3, CE 20.0, CE 20.1.0-dev-20200304_0848]**
 - JDK major version: **Graalvm 22.2.0**
 - OS: **Windows 11**

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reaching out. Are you sure this is an issue with GraalVM and not some missing config in your Micronaut application? does this issue occur only when using GraalVM or even on OpenJDK?

**Comment by ThraaxSession** [comment]
Hi @oubidar-Abderrahim, it works fine when I execute the Micronaut directly with GraalVM as JRE. :/ So I am pretty it's a problem when I compile to native image with GraalVM.

**Comment by oubidar-Abderrahim** [comment]
Sorry, there was no mention of native image usage anywhere in your description so I assumed this was run on the JVM. 
Do you use [the agent](https://www.graalvm.org/22.0/reference-manual/native-image/Agent/) to generate the config files? if yes, do you see an entry for `technology.iatlas.spaceup.dto.db.Server` in the generated files?

**Comment by ThraaxSession** [comment]
Yes there is. 😅
![Screenshot_20220827-070546.png](https://user-images.githubusercontent.com/3085830/187015606-089108cb-86c4-46ea-bd4b-a47a53f45349.png)

As I'm not at home, I need to try it with my Linux laptop and hope it will behave the same. I use the micronaut mechanism.
But I will check it.
