### ISSUE TITLE
Cannot invoke "jdk.internal.platform.CgroupInfo.getMountPoint()" because "anyController" is null

### ISSUE THREAD

**Issue by exoad** [oracle/graal#4831]
I got the following message when trying to use the `native-image` command on my class, which results
in the following error being generated:
```
$ javac Example.java
$ native-image Example

WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
=====================================================================================================================
GraalVM Native Image: Generating 'example' (executable)...
=====================================================================================================================
[1/7] Initializing...
                                                                                 (0.0s @ 0.23GB)
Fatal error: java.lang.NullPointerException: Cannot invoke "jdk.internal.platform.CgroupInfo.getMountPoint()" because "anyController" is null
        at java.base/jdk.internal.platform.cgroupv2.CgroupV2Subsystem.getInstance(CgroupV2Subsystem.java:80)
        at java.base/jdk.internal.platform.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:114)
        at java.base/jdk.internal.platform.CgroupMetrics.getInstance(CgroupMetrics.java:177)
        at java.base/jdk.internal.platform.SystemMetrics.instance(SystemMetrics.java:29)
        at java.base/jdk.internal.platform.Metrics.systemMetrics(Metrics.java:58)
        at java.base/jdk.internal.platform.Container.metrics(Container.java:43)
        at jdk.management/com.sun.management.internal.OperatingSystemImpl.<init>(OperatingSystemImpl.java:182)
        at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl.getOperatingSystemMXBean(PlatformMBeanProviderImpl.java:280)
        at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl$3.nameToMBeanMap(PlatformMBeanProviderImpl.java:199)
        at java.management/sun.management.spi.PlatformMBeanProvider$PlatformComponent.getMBeans(PlatformMBeanProvider.java:195)
        at java.management/java.lang.management.ManagementFactory.getPlatformMXBean(ManagementFactory.java:687)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.management.ManagementFeature.duringSetup(ManagementFeature.java:79)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$16(NativeImageGenerator.java:899)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:78)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:899)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:561)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
---------------------------------------------------------------------------------------------------------------------
Fatal error: java.lang.NullPointerException: Cannot invoke "jdk.internal.platform.CgroupInfo.getMountPoint()" because "anyController" is null
        at java.base/jdk.internal.platform.cgroupv2.CgroupV2Subsystem.getInstance(CgroupV2Subsystem.java:80)
        at java.base/jdk.internal.platform.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:114)
        at java.base/jdk.internal.platform.CgroupMetrics.getInstance(CgroupMetrics.java:177)
        at java.base/jdk.internal.platform.SystemMetrics.instance(SystemMetrics.java:29)
        at java.base/jdk.internal.platform.Metrics.systemMetrics(Metrics.java:58)
        at java.base/jdk.internal.platform.Container.metrics(Container.java:43)
        at jdk.management/com.sun.management.internal.OperatingSystemImpl.<init>(OperatingSystemImpl.java:182)
        at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl.getOperatingSystemMXBean(PlatformMBeanProviderImpl.java:280)
        at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl$3.nameToMBeanMap(PlatformMBeanProviderImpl.java:199)
        at java.management/sun.management.spi.PlatformMBeanProvider$PlatformComponent.getMBeans(PlatformMBeanProvider.java:195)
        at java.management/java.lang.management.ManagementFactory.getPlatformMXBean(ManagementFactory.java:687)
        at java.management/java.lang.management.ManagementFactory.getOperatingSystemMXBean(ManagementFactory.java:389)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ProgressReporter.printResourceStatistics(ProgressReporter.java:636)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ProgressReporter.printEpilog(ProgressReporter.java:555)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:467)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
Error: Image build request failed with exit status 1
```

The code I originally tried to compile:
```java
import static java.lang.System.*;
public class Example {
    public static void main(String ... args) {
        out.print(System.getProperty("os.name"));
    }
}
```

**My Environment**
Version: GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06)
OS: Manjaro Linux x64 (amd64)

**Comment by fniephaus** [comment]
Interesting, it seems `java.lang.management.ManagementFactory.getOperatingSystemMXBean()` does not work on your Linux distro. Can you try and run that in a `jshell` on your machine? It may be a bug in the JDK, but the Native Image builder also shouldn't fail if the bean does not work.

**Comment by fniephaus** [comment]
Also, can you try [this](https://stackoverflow.com/a/71585718/2976234) out?

**Comment by exoad** [comment]
> Interesting, it seems `java.lang.management.ManagementFactory.getOperatingSystemMXBean()` does not work on your Linux distro. Can you try and run that in a `jshell` on your machine? It may be a bug in the JDK, but the Native Image builder also shouldn't fail if the bean does not work.

OK thanks for the reply, running that call in the JShell fails with :
```
|  Welcome to JShell -- Version 17.0.4
|  For an introduction type: /help intro

jshell> java.lang.management.ManagementFactory.getOperatingSystemMXBean()
|  Exception java.lang.NullPointerException: Cannot invoke "jdk.internal.platform.CgroupInfo.getMountPoint()" because "anyController" is null
|        at CgroupV2Subsystem.getInstance (CgroupV2Subsystem.java:80)
|        at CgroupSubsystemFactory.create (CgroupSubsystemFactory.java:114)
|        at CgroupMetrics.getInstance (CgroupMetrics.java:177)
|        at SystemMetrics.instance (SystemMetrics.java:29)
|        at Metrics.systemMetrics (Metrics.java:58)
|        at Container.metrics (Container.java:43)
|        at OperatingSystemImpl.<init> (OperatingSystemImpl.java:182)
|        at PlatformMBeanProviderImpl.getOperatingSystemMXBean (PlatformMBeanProviderImpl.java:280)
|        at PlatformMBeanProviderImpl$3.nameToMBeanMap (PlatformMBeanProviderImpl.java:199)
|        at PlatformMBeanProvider$PlatformComponent.getMBeans (PlatformMBeanProvider.java:195)
|        at ManagementFactory.getPlatformMXBean (ManagementFactory.java:687)
|        at ManagementFactory.getOperatingSystemMXBean (ManagementFactory.java:389)
|        at (#1:1)
```

**Comment by fniephaus** [comment]
Can you please try updating your kernel? Closing this for now as it seems to be a kernel or JDK bug.

> The jdk.internal.platform.CgroupSubsystemFactory#create method expects a memory entry. You can check it with
>
> $ cat /proc/cgroups
>
> it should contain a row starting with "memory"
>
> After a kernel update the problem was gone

https://stackoverflow.com/a/71585718/2976234

**Comment by exoad** [comment]
> Can you please try updating your kernel? Closing this for now as it seems to be a kernel or JDK bug.
> 
> > The jdk.internal.platform.CgroupSubsystemFactory#create method expects a memory entry. You can check it with
> > $ cat /proc/cgroups
> > it should contain a row starting with "memory"
> > After a kernel update the problem was gone
> 
> https://stackoverflow.com/a/71585718/2976234

Ah, yes, this worked to solve the problem, thank you very much!

**Comment by fniephaus** [comment]
Great! Thanks for confirming.

**Comment by loiclefevre** [comment]
This java command line option also makes it work: `-XX:-UseContainerSupport`

**Comment by tiago-macedo** [comment]
@loiclefevre your solution worked for me, many thanks, life saver!
