### ISSUE TITLE
Native-image agent doesn't detect all JNI types

### ISSUE THREAD

**Issue by mhalbritter** [oracle/graal#4846]
```
openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06, mixed mode, sharing)
```

I played around with JNA and native-image and it looks like that the GraalVM agent doesn't detect all JNI types.

Reproducer project: https://github.com/mhalbritter/graalvm-agent-jni-problems

When running it with the agent, then copy the generated metadata into `META-INF/native-image` and then executing a `nativeRun`, I get:

```
JNA: Problems loading core IDs: java.lang.Object
java.lang.UnsatisfiedLinkError: Unsupported JNI version 0x0, required by /home/moe/.cache/JNA/temp/jna10621555043339308097.tmp
Exception in thread "main" java.lang.NoClassDefFoundError: java/lang/Object
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:345)
        at com.oracle.svm.jni.JNIOnLoadFunctionPointer.invoke(JNILibraryInitializer.java)
        at com.oracle.svm.jni.JNILibraryInitializer.callOnLoadFunction(JNILibraryInitializer.java:69)
        at com.oracle.svm.jni.JNILibraryInitializer.initialize(JNILibraryInitializer.java:126)
        at com.oracle.svm.core.jdk.NativeLibrarySupport.addLibrary(NativeLibrarySupport.java:186)
        at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibrary0(NativeLibrarySupport.java:142)
        at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryAbsolute(NativeLibrarySupport.java:101)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:54)
        at java.lang.Runtime.load0(Runtime.java:755)
        at java.lang.System.load(System.java:1953)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1019)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:989)
        at com.sun.jna.Native.<clinit>(Native.java:195)
```

If I add `java.lang.Object` in the `jni-config.json`, it complains about a different missing type. I would have expected that the agent detects the usage of those classes.

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reporting this. The agent is supposed to help you generate such config, but it doesn't guarantee to get all needed config. We use users feedback to improve our agent constantly. We'll take a look into this and find out if this is a bug.

**Comment by oubidar-Abderrahim** [comment]
Hi, when I try to reproduce I get the following error from gradle:
```
Could not determine the dependencies of task ':nativeCompile'.
> Could not resolve all dependencies for configuration ':nativeImageClasspath'.
   > Failed to calculate the value of task ':compileJava' property 'javaCompiler'.
      > No compatible toolchains found for request filter: {languageVersion=17, vendor=GRAAL_VM, implementation=vendor-specific} (auto-detect true, auto-download true)
```
My JAVA_HOME is set to the correct GraalVM, is there something I missed?

**Comment by mhalbritter** [comment]
This is using this feature: https://docs.gradle.org/current/userguide/toolchains.html

You can run `gradle -q javaToolchains` to list all available toolchains.

**Comment by oubidar-Abderrahim** [comment]
Hi, if this issue is still relevant with our latest GraalVM version. please reopen the issue or create a new ticket for it.
Thank you
