### ISSUE TITLE
[native-image] Using both AWT and OperatingSystemMXBean doesn't work with lld

### ISSUE THREAD

**Issue by kb-1000** [oracle/graal#4900]
**Describe the issue**
Using lld as the linker makes using headless AWT together with OperatingSystemMXBean fail.
(I'm using lld because if I use gold, debug info gets corrupted in my project, making gdb crash, while lld doesn't do that)

**Steps to reproduce the issue**
Please include both build steps as well as run steps

1. Download [AWTJMXTest.java](https://github.com/oracle/graal/files/9525640/AWTJMXTest.java.txt)
2. `javac AWTJMXTest.java`
3. `native-image -Djava.awt.headless=true --native-compiler-options=-fuse-ld=lld AWTJMXTest`

build fails, thus no run steps

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **[e.g. EE 19.3, CE 20.0, CE 20.1.0-dev-20200304_0848]** CE 22.2.0, EE 22.2.0
 - JDK major version: **[e.g.:8]** 17
 - OS: **[e.g. macOS Catalina]** Linux, Fedora 36
 - Architecture: **[e.g.: AMD64]** AMD64

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
========================================================================================================================
GraalVM Native Image: Generating 'awtjmxtest' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                    (5.0s @ 0.11GB)
 Version info: 'GraalVM 22.2.0 Java 17 CE'
 Java version info: '17.0.4+8-jvmci-22.2-b06'
 C compiler: gcc (redhat, x86_64, 12.2.1)
 Garbage collector: Serial GC
[2/7] Performing analysis...  [*****]                                                                   (13.9s @ 0.76GB)
   2,897 (71.30%) of  4,063 classes reachable
   3,476 (51.44%) of  6,757 fields reachable
  12,870 (42.63%) of 30,189 methods reachable
      28 classes,     0 fields, and   323 methods registered for reflection
      59 classes,    58 fields, and    55 methods registered for JNI access
       6 native libraries: dl, m, pthread, rt, stdc++, z
[3/7] Building universe...                                                                               (1.7s @ 1.28GB)
[4/7] Parsing methods...      [*]                                                                        (1.8s @ 0.58GB)
[5/7] Inlining methods...     [***]                                                                      (1.1s @ 1.09GB)
[6/7] Compiling methods...    [***]                                                                     (10.6s @ 1.39GB)
[7/7] Creating image...
                                                                                  (0.0s @ 1.82GB)
Fatal error: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1

Linker command executed:
/usr/lib64/ccache/gcc -fuse-ld=lld -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-3299150018469051287/exported_symbols.list -Wl,--exclude-libs,ALL -Wl,-x -o /home/user/awt-jmx-test/awtjmxtest awtjmxtest.o /home/user/graalvm-ce-java17-22.2.0/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/user/graalvm-ce-java17-22.2.0/lib/static/linux-amd64/glibc/libnet.a /home/user/graalvm-ce-java17-22.2.0/lib/static/linux-amd64/glibc/libnio.a /home/user/graalvm-ce-java17-22.2.0/lib/static/linux-amd64/glibc/libmanagement_ext.a /home/user/graalvm-ce-java17-22.2.0/lib/static/linux-amd64/glibc/libjava.a /home/user/graalvm-ce-java17-22.2.0/lib/static/linux-amd64/glibc/libfdlibm.a /home/user/graalvm-ce-java17-22.2.0/lib/static/linux-amd64/glibc/libawt_headless.a /home/user/graalvm-ce-java17-22.2.0/lib/static/linux-amd64/glibc/libawt.a /home/user/graalvm-ce-java17-22.2.0/lib/static/linux-amd64/glibc/libzip.a /home/user/graalvm-ce-java17-22.2.0/lib/svm/clibraries/linux-amd64/libjvm.a -v -L/tmp/SVM-3299150018469051287 -L/home/user/graalvm-ce-java17-22.2.0/lib/static/linux-amd64/glibc -L/home/user/graalvm-ce-java17-22.2.0/lib/svm/clibraries/linux-amd64 -lstdc++ -lm -lz -ldl -lpthread -lrt

Linker command output:
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/12/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --enable-libstdcxx-backtrace --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-12.2.1-20220819/obj-x86_64-redhat-linux/isl-install --enable-offload-targets=nvptx-none --without-cuda-driver --enable-offload-defaulted --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux --with-build-config=bootstrap-lto --enable-link-serialization=1
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.1 20220819 (Red Hat 12.2.1-1) (GCC) 
COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/12/:/usr/libexec/gcc/x86_64-redhat-linux/12/:/usr/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/12/:/usr/lib/gcc/x86_64-redhat-linux/
LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/12/:/usr/lib/gcc/x86_64-redhat-linux/12/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/12/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-fuse-ld=lld' '-z' 'noexecstack' '-o' '/home/user/awt-jmx-test/awtjmxtest' '-v' '-L/tmp/SVM-3299150018469051287' '-L/home/user/graalvm-ce-java17-22.2.0/lib/static/linux-amd64/glibc' '-L/home/user/graalvm-ce-java17-22.2.0/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64' '-dumpdir' '/home/user/awt-jmx-test/awtjmxtest.'
 /usr/libexec/gcc/x86_64-redhat-linux/12/collect2 -plugin /usr/libexec/gcc/x86_64-redhat-linux/12/liblto_plugin.so -plugin-opt=/usr/libexec/gcc/x86_64-redhat-linux/12/lto-wrapper -plugin-opt=-fresolution=/tmp/ccBmlrO9.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --no-add-needed --eh-frame-hdr --hash-style=gnu -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -fuse-ld=lld -o /home/user/awt-jmx-test/awtjmxtest -z noexecstack /usr/lib/gcc/x86_64-redhat-linux/12/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/12/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/12/crtbegin.o -L/tmp/SVM-3299150018469051287 -L/home/user/graalvm-ce-java17-22.2.0/lib/static/linux-amd64/glibc -L/home/user/graalvm-ce-java17-22.2.0/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-redhat-linux/12 -L/usr/lib/gcc/x86_64-redhat-linux/12/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/12/../../.. --gc-sections --dynamic-list /tmp/SVM-3299150018469051287/exported_symbols.list --exclude-libs ALL -x awtjmxtest.o /home/user/graalvm-ce-java17-22.2.0/lib/svm/clibraries/linux-amd64/liblibchelper.a /home/user/graalvm-ce-java17-22.2.0/lib/static/linux-amd64/glibc/libnet.a /home/user/graalvm-ce-java17-22.2.0/lib/static/linux-amd64/glibc/libnio.a /home/user/graalvm-ce-java17-22.2.0/lib/static/linux-amd64/glibc/libmanagement_ext.a /home/user/graalvm-ce-java17-22.2.0/lib/static/linux-amd64/glibc/libjava.a /home/user/graalvm-ce-java17-22.2.0/lib/static/linux-amd64/glibc/libfdlibm.a /home/user/graalvm-ce-java17-22.2.0/lib/static/linux-amd64/glibc/libawt_headless.a /home/user/graalvm-ce-java17-22.2.0/lib/static/linux-amd64/glibc/libawt.a /home/user/graalvm-ce-java17-22.2.0/lib/static/linux-amd64/glibc/libzip.a /home/user/graalvm-ce-java17-22.2.0/lib/svm/clibraries/linux-amd64/libjvm.a -lstdc++ -lm -lz -ldl -lpthread -lrt -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-redhat-linux/12/crtend.o /usr/lib/gcc/x86_64-redhat-linux/12/../../../../lib64/crtn.o
ld.lld: error: duplicate symbol: throw_internal_error
>>> defined at awtjmxtest.o:(IsolateEnterStub_LibManagementExtSupport_throwInternalError_8dcbf61ef7519f805415daa5101b4f16c1d6aada_ef63b5f4efb298f9ead1a6fd18512f88eec73184)
>>> defined at management_ext.c
>>>            management_ext.o:(.text.throw_internal_error+0x0) in archive /home/user/graalvm-ce-java17-22.2.0/lib/static/linux-amd64/glibc/libmanagement_ext.a

ld.lld: error: duplicate symbol: jvm
>>> defined at management_ext.c
>>>            management_ext.o:(jvm) in archive /home/user/graalvm-ce-java17-22.2.0/lib/static/linux-amd64/glibc/libmanagement_ext.a
>>> defined at awt_LoadLibrary.c
>>>            awt_LoadLibrary.o:(.bss.jvm+0x0) in archive /home/user/graalvm-ce-java17-22.2.0/lib/static/linux-amd64/glibc/libawt.a
collect2: error: ld returned 1 exit status
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:191)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:135)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:704)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
------------------------------------------------------------------------------------------------------------------------
                        0.8s (1.9% of total time) in 18 GCs | Peak RSS: 2.23GB | CPU load: 5.12
========================================================================================================================
Failed generating 'awtjmxtest' after 38.6s.
Error: Image build request failed with exit status 1

```

**Comment by fniephaus** [comment]
AWT, especially on JDK17+, is not designed to be statically linked. That's why you get the `duplicate symbol: jvm` error. We are working on switching to dynamically linking AWT on Linux and macOS, similar to how it's already done for Windows. While this won't make it into the 22.3, we hope to have this ready for the 23.0 release.

**Comment by stdStudent** [comment]
GraalVM 25 (current latest LTS distribution) dynamically link AWT, pulling the shared library next to the executable. The issue might not be relevant anymore.

**Comment by kb-1000** [comment]
Well, being able to use native-image to just put everything into a single executable is quite nice, it would be nice if it was possible to use static linking

**Comment by stdStudent** [comment]
@kb-1000, I totally agree, but that doesn't seem to be on the roadmap at the moment. As far as I understand, this needs to be addressed not just by GraalVM alone. 

By the way, I recently tracked down what was pulling in shared libraries. I managed to eliminate those calls/symbols from my rather small project, though it was quite a struggle.

**Comment by fniephaus** [comment]
> but that doesn't seem to be on the roadmap at the moment. As far as I understand, this needs to be addressed not just by GraalVM alone

That's correct. The AWT libraries are not designed to be statically linked, so we have no choice and must link them dynamically to be compatible. 

> I recently tracked down what was pulling in shared libraries.

This can be quite annoying. JAXB, for example, unconditionally pulls in AWT to support conversion of base64-encoded PNGs to `BufferedImage`. One way to avoid this would be to support configuration of what conversions are available at build time, but no one has cared to implement this in JAXB so far.

Another workaround is to use `--limit-modules <module>(,<module>)*` and include all modules you need, but exclude `java.desktop` (which contains AWT). This obviously only works if you know that AWT is not called at run time in your application.

Or, instead of AWT/Swing, you use something like SDL3 via LWJGL that can be linked statically.

**Comment by kb-1000** [comment]
Something I've been thinking about... would it be possible to pre-link the libraries into a single object file, such that only API/JNI entrypoint symbols are exported? That should act fairly similar to having them dynamically linked. There's `ld -r`, for example.
Or maybe the libraries could be linked with a single compiler invocation (like, a unity build) while marking everything not exported as static, or something entirely different I'm not thinking of, just throwing ideas here

**Comment by fniephaus** [comment]
Feel free to experiment with this. Maybe you want to give `-H:NativeLinkerOption` a try.

I can't quite recall why AWT cannot be linked statically. It may have something to do with it failing to build statically with musl, but I'm not quite sure.

**Comment by stdStudent** [comment]
> This can be quite annoying.

AWT was actually rather easy to get rid of. I struggled a lot with `management_ext.(so|dylib|dll)`, because some deep transitive dependency was using `sun`/`java` management classes that seem to be reachable only in obscure cases I couldn't replicate, but the GraalVM agent still puts them into the reachability metadata. 

> Another workaround is to use `--limit-modules <module>(,<module>)*` and include all modules you need, but exclude `java.desktop` (which contains AWT).

Good to know, thank you! For AWT exclusion, I was able to exclude a module that was never used this way:
```kotlin
implementation(libs.someLib) {
    exclude(group = "some.group", module = "module-name")
}
```

For Management Extensions, I used an `access-filter.json`:
```json
{
  "rules": [
    { "excludeClasses": "java.lang.management.ManagementFactory" },
    { "excludeClasses": "java.lang.management.RuntimeMXBean" },
    { "excludeClasses": "sun.management.VMManagementImpl" }
  ]
}
```
and passed it to the agent:
```kotlin
jvmArgs(
    "-agentlib:native-image-agent=access-filter-file=$accessFilterAbsolutePath",
)
```

These examples might be a bit off-topic, but I'd still like to leave them for anyone who stumbles upon this issue like I did.
