### ISSUE TITLE
AArch64Assembler patch methods error

### ISSUE THREAD

**Issue by ningpengtao-coder** [oracle/graal#4910]
I don't know what's causing it, I don't have a clue.

environment:
jdk:17.0.4
graalvm: 22.1.0
os: wsl

```
   Fatal error: com.oracle.svm.core.util.VMError$HostedError: org.graalvm.compiler.debug.GraalError: failed guarantee: value too large to fit into space
        at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:72)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:678)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:515)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:615)
Caused by: org.graalvm.compiler.debug.GraalError: failed guarantee: value too large to fit into space
        at jdk.internal.vm.compiler/org.graalvm.compiler.debug.GraalError.guarantee(GraalError.java:73)
        at jdk.internal.vm.compiler/org.graalvm.compiler.asm.aarch64.AArch64Assembler$SingleInstructionAnnotation.patch(AArch64Assembler.java:3320)
        at com.oracle.svm.hosted.code.aarch64.SingleInstructionHostedPatcher.patch(AArch64HostedPatcher.java:101)
        at com.oracle.svm.hosted.image.LIRNativeImageCodeCache.patchMethods(LIRNativeImageCodeCache.java:194)
        at com.oracle.svm.hosted.image.NativeImage$NativeTextSectionImpl.writeTextSection(NativeImage.java:965)
        at com.oracle.svm.hosted.image.NativeImage.build(NativeImage.java:457)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:666)
        ... 5 more
```

**Comment by ningpengtao-coder** [comment]
After upgrading to graalvm-17-22.2.0, this problem does not occur
