### ISSUE TITLE
Jaxb usage not detected by native image

### ISSUE THREAD

**Issue by sdeleuze** [oracle/graal#4911]
Usage of Jaxb in Spring Boot 3 via https://github.com/spring-projects/spring-framework/blob/main/spring-web/src/main/java/org/springframework/http/codec/xml/Jaxb2XmlEncoder.java is not detected by GraalVM native image (tested with 22.2.0 and 22.3.0-dev), without native config it produces the following error:
```
org.springframework.core.codec.CodecException: Could not create JAXBContext for class [class com.example.webflux.dto.Response]: null
	at org.springframework.http.codec.xml.JaxbContextContainer.lambda$getJaxbContext$0(JaxbContextContainer.java:58) ~[na:na]
Caused by: java.lang.NoSuchMethodException: org.glassfish.jaxb.runtime.v2.ContextFactory.createContext([Ljava.lang.Class;, java.util.Map)
	at java.lang.Class.getMethod(DynamicHub.java:2227) ~[webflux-netty:na]
	at jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:272) ~[na:na]
```
The class where Jaxb is reachable is https://github.com/spring-projects/spring-framework/blob/main/spring-web/src/main/java/org/springframework/http/codec/xml/JaxbContextContainer.java#L54.

If I add manually the following native configuration, it works:
```
[ 
  {
    "name": "org.glassfish.jaxb.runtime.v2.model.impl.Utils",
    "allDeclaredFields": true
  },
  {
    "name": "org.glassfish.jaxb.core.v2.model.nav.ReflectionNavigator",
    "allDeclaredMethods": true
  },
  {
    "name": "org.glassfish.jaxb.runtime.v2.ContextFactory",
    "allDeclaredMethods": true
  },
  {
    "name": "org.glassfish.jaxb.runtime.v2.runtime.property.ArrayElementLeafProperty",
    "allDeclaredConstructors": true
  },
  {
    "name": "org.glassfish.jaxb.runtime.v2.runtime.property.SingleMapNodeProperty",
    "allDeclaredConstructors": true
  },
  {
    "name": "org.glassfish.jaxb.runtime.v2.runtime.property.SingleReferenceNodeProperty",
    "allDeclaredConstructors": true
  },
  {
    "name": "org.glassfish.jaxb.runtime.v2.runtime.property.ArrayElementNodeProperty",
    "allDeclaredConstructors": true
  },
  {
    "name": "org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder",
    "allDeclaredConstructors": true
  },
  {
    "name": "org.glassfish.jaxb.runtime.v2.runtime.property.SingleElementLeafProperty",
    "allDeclaredConstructors": true
  },
  {
    "name": "org.glassfish.jaxb.runtime.v2.runtime.property.SingleElementNodeProperty",
    "allDeclaredConstructors": true
  },
  {
    "name": "org.glassfish.jaxb.runtime.v2.runtime.property.ArrayReferenceNodeProperty",
    "allDeclaredConstructors": true
  }
]
```

Please tag this issue with the `spring` label.

**Comment by sdeleuze** [comment]
I just saw we have a `org.glassfish.jaxb:jaxb-runtime` dependency in this project, maybe related hints should be added to https://github.com/oracle/graalvm-reachability-metadata.

**Comment by sdeleuze** [comment]
Superseded by https://github.com/oracle/graalvm-reachability-metadata/issues/49.
