### ISSUE TITLE
[GR-40939] `Class#newInstance` should not make `JarFile`, `JarVerifier` and `ManifestEntryVerifier` reachable

### ISSUE THREAD

**Issue by sdeleuze** [oracle/graal#4927]
While analyzing Spring Boot 3 applications footprint, I found that using `Class#newInstance` (super common) makes `JarFile`, `JarVerifier` and `ManifestEntryVerifier` reachable.

I was able to see that by using `-H:+TraceSecurityServices` which outputs:
```
 at java.security.MessageDigest.getInstance(MessageDigest.java:297)
        at sun.security.util.ManifestEntryVerifier.setEntry(ManifestEntryVerifier.java:140)
        at java.util.jar.JarVerifier.beginEntry(JarVerifier.java:176)
        at java.util.jar.JarFile.initializeVerifier(JarFile.java:760)
        at java.util.jar.JarFile.getInputStream(JarFile.java:845)
        at jdk.internal.module.ModulePath.readJar(ModulePath.java:652)
        at jdk.internal.module.ModulePath.readModule(ModulePath.java:337)
        at jdk.internal.module.ModulePath.scan(ModulePath.java:237)
        at jdk.internal.module.ModulePath.scanNextEntry(ModulePath.java:190)
        at jdk.internal.module.ModulePath.findAll(ModulePath.java:166)
        at jdk.internal.module.SystemModuleFinders$1$$Lambda$1078/0x00000007c1284340.run(Unknown Source)
        at com.oracle.svm.core.jdk.Target_java_security_AccessController.executePrivileged(SecuritySubstitutions.java:169)
        at java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.lang.Class.newInstance(Class.java:629)
```
When running a native image, I think creating a new class via `Class#newInstance` should not require those classes that transitively import a lot of crypto classes (removing the `JarFile` codepath removed 280 classes and reduced the RSS footprint by 1.15M). Maybe the regular JVM codepath should be adapted to use a more optimal one dedicated to native images.

Tested with GraalVM 22.2 Java 17.

Please tag this issue with the `spring` label.

**Comment by sdeleuze** [comment]
After a deeper look, we found this dependency has been introduced by https://github.com/spring-projects/spring-framework/commit/19b436c6aa14e79e6f3a98c15a8edff2a8c351fc so I think we can close this issue. Please remove it from `22.3` bucket since nothing had to be fixed.

**Comment by olpaw** [comment]
> After a deeper look, we found this dependency has been introduced by [spring-projects/spring-framework@19b436c](https://github.com/spring-projects/spring-framework/commit/19b436c6aa14e79e6f3a98c15a8edff2a8c351fc) so I think we can close this issue. Please remove it from `22.3` bucket since nothing had to be fixed.

cc @pejovica
