### ISSUE TITLE
IndexOutOfBoundsException in DAP server

### ISSUE THREAD

**Issue by nirvdrum** [oracle/graal#4944]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **22.3.0-dev f9726d7f20f5fce7b26578886a01e3750807d5d6**
 - CE or EE: **CE**
 - JDK version: **JDK11**
 - OS and OS Version: **Ubuntu 21.10**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
OpenJDK 64-Bit Server VM (11.0.16+7-jvmci-22.3-b02) for linux-amd64 JRE (11.0.16+7-jvmci-22.3-b02), built on Jul 13 2022 17:12:49 by "buildslave" with gcc 7.3.0
```

**Have you verified this issue still happens when using the latest snapshot?**
Yes.

**Describe the issue**
I've seen an IndexOutOfBoundsException when using the GraalVM Tools for Java extension in VS Code while debugging a TruffleRuby application. I don't know how to reproduce, unfortunately, so I'm hoping the stack trace is a enough to work out the problem. The last time I saw it was after I clicked the "Stop" button in the VS Code debugger controls.

**Exception info**
```
[dap] SEVERE: Index 23 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 23 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:372)
        at java.base/java.util.ArrayList.get(ArrayList.java:459)
        at com.oracle.truffle.tools.dap.server.LoadedSourcesHandler.getSource(LoadedSourcesHandler.java:80)
        at com.oracle.truffle.tools.dap.server.BreakpointsHandler.setBreakpoints(BreakpointsHandler.java:88)
        at com.oracle.truffle.tools.dap.server.DebugProtocolServerImpl.setBreakpoints(DebugProtocolServerImpl.java:281)
        at com.oracle.truffle.tools.dap.types.DebugProtocolServer$Session.processRequest(DebugProtocolServer.java:478)
        at com.oracle.truffle.tools.dap.types.DebugProtocolServer$Session.processMessage(DebugProtocolServer.java:405)
        at com.oracle.truffle.tools.dap.types.DebugProtocolServer$Session.run(DebugProtocolServer.java:342)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Steps to reproduce the issue**
I don't know how to reproduce it. I've just seen it happen several times while debugging a TruffleRuby application.

**Comment by entlicher** [comment]
Fixed by https://github.com/oracle/graal/commit/e61ab7616d8b8604b2a3d6be5f3f474c2556b88d.

**Comment by poojithaunnam** [comment]
Error : java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 3
I am getting the above mentioned error , i m using graalvm 22.3.1 version . graalvm 23.0.0 is not available to download
