### ISSUE TITLE
Error on the obfuscated code compilation in SubstrateVM

### ISSUE THREAD

**Issue by vektory79** [oracle/graal#496]
Recently I tryed to compile the [Minecraft server](https://minecraft.net/ru-ru/download/server) jar. It's contain an obfuscated code. This obfuscation is touching everything around. Even the enum declarations. As a result I have the compilation crash with this error:
```
$ $JAVA_HOME/bin/native-image --debug-attach -jar server/server.jar
Listening for transport dt_socket at address: 8000
   classlist:   8,514.58 ms
       (cap):   1,170.88 ms
       setup:   2,922.16 ms                                                                                                                                  
    analysis: 1,673,583.90 ms                                                                                                                                
fatal error: jdk.vm.ci.common.JVMCIError: jdk.vm.ci.common.JVMCIError: should not reach here: Enumeration does not have static field with enumeration values: AnalysisType<vl, allocated: false, inHeap: false, inTypeCheck: false>                                                                                       
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)                                                                             
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)                                                      
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)                                              
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)                                                                                   
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)                                                                    
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)                                                                                     
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:381)                                                                     
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:281)                                                  
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:378)                                                       
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:104)                                                        
Caused by: jdk.vm.ci.common.JVMCIError: should not reach here: Enumeration does not have static field with enumeration values: AnalysisType<vl, allocated: false, inHeap: false, inTypeCheck: false>                                                                                                                      
        at jdk.vm.ci.common.JVMCIError.shouldNotReachHere(JVMCIError.java:48)                                                                                
        at com.oracle.svm.hosted.analysis.Inflation.checkType(Inflation.java:177)                                                                            
        at java.lang.Iterable.forEach(Iterable.java:75)                                                                                                      
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)                                                                       
        at com.oracle.svm.hosted.analysis.Inflation.checkObjectGraph(Inflation.java:125)                                                                     
        at com.oracle.graal.pointsto.BigBang.checkObjectGraph(BigBang.java:582)
        at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:554)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:642)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:364)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Listening for transport dt_socket at address: 8000
Error: Image building with exit status 1
```

As I understand, it's because compilation is searching the static field's name with enum values array. But in obfuscated code this field's name is changed and algorithm can't find the field.

Do you are have any plans to suport obfuscated programs?

**Comment by cstancu** [comment]
We support obfuscated code. This issue was reported before and fixed. See https://github.com/oracle/graal/issues/436. You can [build from source](https://github.com/oracle/graal/tree/master/substratevm#quick-start) to get the latest fixes or wait for the next release which is scheduled for June 29th.
