### ISSUE TITLE
google protobuf  . UnsupportedFeatureError: Runtime reflection is not supported 

### ISSUE THREAD

**Issue by iceman567** [oracle/graal#4966]
reflect-config.json
{
  "name":"com.teamdev.jxbrowser.password.internal.rpc.SavePassword",
  "queriedMethods":[
    {"name":"getRequest","parameterTypes":[] }, 
    {"name":"getResponse","parameterTypes":[] }, 
    {"name":"getStageCase","parameterTypes":[] }, 
    {"name":"getSubscribe","parameterTypes":[] }, 
    {"name":"getTarget","parameterTypes":[] }, 
    {"name":"hasTarget","parameterTypes":[] }
  ]
},
{
  "name":"com.teamdev.jxbrowser.password.internal.rpc.SavePassword$Builder",
  "methods":[
    {"name":"setSubscribe","parameterTypes":["boolean"] }, 
    {"name":"setTarget","parameterTypes":["com.teamdev.jxbrowser.internal.rpc.BrowserId"] }
  ],
  "queriedMethods":[
    {"name":"clearRequest","parameterTypes":[] }, 
    {"name":"clearResponse","parameterTypes":[] }, 
    {"name":"clearStage","parameterTypes":[] }, 
    {"name":"clearSubscribe","parameterTypes":[] }, 
    {"name":"clearTarget","parameterTypes":[] }, 
    {"name":"getRequest","parameterTypes":[] }, 
    {"name":"getRequestBuilder","parameterTypes":[] }, 
    {"name":"getResponse","parameterTypes":[] }, 
    {"name":"getResponseBuilder","parameterTypes":[] }, 
    {"name":"getStageCase","parameterTypes":[] }, 
    {"name":"getSubscribe","parameterTypes":[] }, 
    {"name":"getTarget","parameterTypes":[] }, 
    {"name":"getTargetBuilder","parameterTypes":[] }, 
    {"name":"hasTarget","parameterTypes":[] }, 
    {"name":"setRequest","parameterTypes":["com.teamdev.jxbrowser.password.internal.rpc.SavePassword$Request"] }, 
    {"name":"setResponse","parameterTypes":["com.teamdev.jxbrowser.password.internal.rpc.SavePassword$Response"] }
  ]
},
{
  "name":"com.teamdev.jxbrowser.password.internal.rpc.SavePassword$Request",
  "queriedMethods":[{"name":"newBuilder","parameterTypes":[] }]
},
{
  "name":"com.teamdev.jxbrowser.password.internal.rpc.SavePassword$Response",
  "queriedMethods":[{"name":"newBuilder","parameterTypes":[] }]
}

===================================

Exception in thread "Browser Thread: b32abaf9-bedc-4e4d-a7a2-6f7ff658d8ba" com.oracle.svm.core.jdk.UnsupportedFeatureError: Runtime reflection is not supported for public com.teamdev.jxbrowser.password.internal.rpc.SavePassword$Request com.teamdev.jxbrowser.password.internal.rpc.SavePassword.getRequest()
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89)
        at java.lang.reflect.Method.acquireMethodAccessor(Method.java:77)
        at java.lang.reflect.Method.invoke(Method.java:564)
        at com.teamdev.jxbrowser.deps.com.google.protobuf.GeneratedMessageV3.invokeOrDie(GeneratedMessageV3.java:1856)
        at com.teamdev.jxbrowser.deps.com.google.protobuf.GeneratedMessageV3.access$1100(GeneratedMessageV3.java:79)
        at com.teamdev.jxbrowser.deps.com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor$ReflectionInvoker.get(GeneratedMessageV3.java:2196)
        at com.teamdev.jxbrowser.deps.com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor.get(GeneratedMessageV3.java:2277)
        at com.teamdev.jxbrowser.deps.com.google.protobuf.GeneratedMessageV3.getField(GeneratedMessageV3.java:273)
        at com.teamdev.jxbrowser.internal.rpc.stream.CallbackStream.process(CallbackStream.java:141)
        at com.teamdev.jxbrowser.internal.rpc.stream.Stream$StreamObserver.lambda$onNext$0(Stream.java:167)
        at com.teamdev.jxbrowser.internal.RpcThreadImpl$TaskRunner.processTasks(RpcThreadImpl.java:172)
        at java.lang.Thread.run(Thread.java:829)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
        at com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:143)

**Comment by oubidar-Abderrahim** [comment]
Hi @iceman567, could you please follow the template of reporting issues on the graal project? specify your environment, description of the problem, and share a reproduce

**Comment by oubidar-Abderrahim** [comment]
Closing this issue for inactivity
