### ISSUE TITLE
ObjectStamp cannot be cast IntegerStamp

### ISSUE THREAD

**Issue by dsyer** [oracle/graal#497]
I have no idea what this means, or if there is a way for me to configure around it. Here's the error (when generating a native-image):

```
Caused by: java.lang.ClassCastException: org.graalvm.compiler.core.common.type.ObjectStamp cannot be cast to org.graalvm.compiler.core.common.type.IntegerStamp
	at org.graalvm.compiler.java.BytecodeParser.processReturnValue(BytecodeParser.java:2529)
	at org.graalvm.compiler.java.BytecodeParser.genReturn(BytecodeParser.java:2508)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.genReturn(SharedGraphBuilderPhase.java:349)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:4784)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3115)
	... 21 more
```

**Comment by dsyer** [comment]
I was using rc2. You can reproduce using the "func" branch here: https://github.com/dsyer/spring-boot-micro-apps/tree/func. Follow the instructions in the README, but use `com.example.func.FuncApplication` instead of `MicroApplication` (which works).

**Comment by mukel** [comment]
Thanks for reporting, a fix is already being reviewed. It won't be out for RC3; you'll have to wait for RC4 or build SVM from source; there's no quick workaround. I'll close this issue when it's merged.
`MicroApplication` compiles and runs fine.
`FuncApplication` compiles but fails at runtime, here's the log:
```
mx native-image -Dio.netty.noUnsafe=true -H:Name=func -H:ReflectionConfigurationFiles=./playground/dsyer/spring-boot-micro-apps/graal.json --report-unsupported-elements-at-runtime -cp $CP com.example.func.FuncApplication

   classlist:   2,888.01 ms
       (cap):   1,468.78 ms
       setup:   2,607.46 ms
Jun 29, 2018 2:14:10 PM io.netty.util.internal.logging.Slf4JLogger info
INFO: Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
RecomputeFieldValue.ArrayIndexScale automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.arrayIndexScale(Class) was detected in the static initializer of io.netty.util.internal.shaded.org.jctools.util.UnsafeRefArrayAccess. Add a RecomputeFieldValue.ArrayIndexScale manual substitution for io.netty.util.internal.shaded.org.jctools.util.UnsafeRefArrayAccess. 
  (typeflow):  17,253.19 ms
   (objects):  12,827.78 ms
  (features):     383.32 ms
    analysis:  31,351.20 ms
    universe:     916.64 ms
     (parse):   2,671.71 ms
    (inline):   2,552.73 ms
   (compile):  11,442.58 ms
     compile:  17,764.03 ms
       image:   2,328.21 ms
       write:     620.77 ms
     [total]:  58,618.58 ms

$ ./func 
Jun 29, 2018 2:15:04 PM org.springframework.context.support.AbstractApplicationContext prepareRefresh
INFO: Refreshing org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext@68f50e3a: startup date [Fri Jun 29 14:15:04 CEST 2018]; root of context hierarchy
Jun 29, 2018 2:15:04 PM org.springframework.context.support.AbstractApplicationContext refresh
WARNING: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start reactive web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.web.embedded.netty.NettyReactiveWebServerFactory': Initialization of bean failed; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.ServerProperties': Could not bind properties to 'ServerProperties' : prefix=server, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.context.properties.ConversionServiceDeducer$Factory': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.context.properties.ConversionServiceDeducer$Factory]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.boot.context.properties.ConversionServiceDeducer$Factory.<init>()
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.lang.Throwable.<init>(Throwable.java:310)
        at java.lang.Exception.<init>(Exception.java:102)
        at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:89)
        at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)
        at com.oracle.svm.reflect.proxies.Proxy_1_FuncApplication_main.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:173)
Caused by: org.springframework.context.ApplicationContextException: Unable to start reactive web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.web.embedded.netty.NettyReactiveWebServerFactory': Initialization of bean failed; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.ServerProperties': Could not bind properties to 'ServerProperties' : prefix=server, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.context.properties.ConversionServiceDeducer$Factory': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.context.properties.ConversionServiceDeducer$Factory]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.boot.context.properties.ConversionServiceDeducer$Factory.<init>()
        at java.lang.Throwable.<init>(Throwable.java:287)
        at java.lang.Exception.<init>(Exception.java:84)
        at java.lang.RuntimeException.<init>(RuntimeException.java:80)
        at org.springframework.core.NestedRuntimeException.<init>(NestedRuntimeException.java:66)
        at org.springframework.beans.BeansException.<init>(BeansException.java:50)
        at org.springframework.beans.FatalBeanException.<init>(FatalBeanException.java:45)
        at org.springframework.context.ApplicationContextException.<init>(ApplicationContextException.java:45)
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:76)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544)
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:61)
        at com.example.func.FuncApplication.run(FuncApplication.java:111)
        at com.example.func.FuncApplication.main(FuncApplication.java:92)
        ... 3 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.web.embedded.netty.NettyReactiveWebServerFactory': Initialization of bean failed; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.ServerProperties': Could not bind properties to 'ServerProperties' : prefix=server, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.context.properties.ConversionServiceDeducer$Factory': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.context.properties.ConversionServiceDeducer$Factory]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.boot.context.properties.ConversionServiceDeducer$Factory.<init>()
        at java.lang.Throwable.<init>(Throwable.java:265)
        at java.lang.Exception.<init>(Exception.java:66)
        at java.lang.RuntimeException.<init>(RuntimeException.java:62)
        at org.springframework.core.NestedRuntimeException.<init>(NestedRuntimeException.java:56)
        at org.springframework.beans.BeansException.<init>(BeansException.java:40)
        at org.springframework.beans.FatalBeanException.<init>(FatalBeanException.java:35)
        at org.springframework.beans.factory.BeanCreationException.<init>(BeanCreationException.java:93)
        at org.springframework.beans.factory.BeanCreationException.<init>(BeanCreationException.java:108)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:589)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
        at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$463/1747119870.getObject(Unknown Source)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.getWebServerFactory(ReactiveWebServerApplicationContext.java:135)
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.createWebServer(ReactiveWebServerApplicationContext.java:99)
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:73)
        ... 7 more
Caused by: org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.ServerProperties': Could not bind properties to 'ServerProperties' : prefix=server, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.context.properties.ConversionServiceDeducer$Factory': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.context.properties.ConversionServiceDeducer$Factory]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.boot.context.properties.ConversionServiceDeducer$Factory.<init>()
        at java.lang.Throwable.<init>(Throwable.java:265)
        at java.lang.Exception.<init>(Exception.java:66)
        at java.lang.RuntimeException.<init>(RuntimeException.java:62)
        at org.springframework.core.NestedRuntimeException.<init>(NestedRuntimeException.java:56)
        at org.springframework.beans.BeansException.<init>(BeansException.java:40)
        at org.springframework.beans.FatalBeanException.<init>(FatalBeanException.java:35)
        at org.springframework.beans.factory.BeanCreationException.<init>(BeanCreationException.java:70)
        at org.springframework.beans.factory.BeanCreationException.<init>(BeanCreationException.java:81)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBindException.<init>(ConfigurationPropertiesBindException.java:38)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.bind(ConfigurationPropertiesBindingPostProcessor.java:110)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:93)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:424)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1700)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:581)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
        at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$463/1747119870.getObject(Unknown Source)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:224)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1015)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:339)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:334)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1107)
        at com.example.func.FuncApplication.lambda$registerReactiveWebServerFactoryAutoConfiguration$11(FuncApplication.java:193)
        at com.example.func.FuncApplication$$Lambda$410/41351020.get(Unknown Source)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1153)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1101)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
        at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$463/1747119870.getObject(Unknown Source)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:515)
        at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.getWebServerFactoryCustomizerBeans(WebServerFactoryCustomizerBeanPostProcessor.java:94)
        at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.getCustomizers(WebServerFactoryCustomizerBeanPostProcessor.java:84)
        at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.postProcessBeforeInitialization(WebServerFactoryCustomizerBeanPostProcessor.java:75)
        at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.postProcessBeforeInitialization(WebServerFactoryCustomizerBeanPostProcessor.java:61)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:424)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1700)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:581)
        ... 16 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.context.properties.ConversionServiceDeducer$Factory': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.context.properties.ConversionServiceDeducer$Factory]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.boot.context.properties.ConversionServiceDeducer$Factory.<init>()
        at java.lang.Throwable.<init>(Throwable.java:265)
        at java.lang.Exception.<init>(Exception.java:66)
        at java.lang.RuntimeException.<init>(RuntimeException.java:62)
        at org.springframework.core.NestedRuntimeException.<init>(NestedRuntimeException.java:56)
        at org.springframework.beans.BeansException.<init>(BeansException.java:40)
        at org.springframework.beans.FatalBeanException.<init>(FatalBeanException.java:35)
        at org.springframework.beans.factory.BeanCreationException.<init>(BeanCreationException.java:93)
        at org.springframework.beans.factory.BeanCreationException.<init>(BeanCreationException.java:108)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1238)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1137)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:305)
        at org.springframework.boot.context.properties.ConversionServiceDeducer.getConversionService(ConversionServiceDeducer.java:53)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBinder.getConversionService(ConfigurationPropertiesBinder.java:151)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBinder.getBinder(ConfigurationPropertiesBinder.java:135)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBinder.bind(ConfigurationPropertiesBinder.java:82)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.bind(ConfigurationPropertiesBindingPostProcessor.java:107)
        ... 49 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.context.properties.ConversionServiceDeducer$Factory]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.boot.context.properties.ConversionServiceDeducer$Factory.<init>()
        at java.lang.Throwable.<init>(Throwable.java:287)
        at java.lang.Exception.<init>(Exception.java:84)
        at java.lang.RuntimeException.<init>(RuntimeException.java:80)
        at org.springframework.core.NestedRuntimeException.<init>(NestedRuntimeException.java:66)
        at org.springframework.beans.BeansException.<init>(BeansException.java:50)
        at org.springframework.beans.FatalBeanException.<init>(FatalBeanException.java:45)
        at org.springframework.beans.BeanInstantiationException.<init>(BeanInstantiationException.java:59)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:83)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1230)
        ... 58 more
Caused by: java.lang.NoSuchMethodException: org.springframework.boot.context.properties.ConversionServiceDeducer$Factory.<init>()
        at java.lang.Throwable.<init>(Throwable.java:265)
        at java.lang.Exception.<init>(Exception.java:66)
        at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:56)
        at java.lang.NoSuchMethodException.<init>(NoSuchMethodException.java:51)
        at java.lang.Class.getConstructor0(Class.java:3082)
        at java.lang.Class.getDeclaredConstructor(Class.java:2178)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:78)
        ... 59 more
```

**Comment by dsyer** [comment]
This was marked as fixed before rc3 was released. I just tried rc4 and it's still broken. Do we need a new issue, or just some more clarity on when this fix is going to be released?

**Comment by dsyer** [comment]
More data: deleting stuff systematically from `func.json` until it works, it appears that the `ClassCastException` first appears when you add this to the JSON:

```
	{
		"name": "org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor",
		"methods": [
			{
				"name": "<init>",
				"parameterTypes": []
			}
		]
	}
```

So in fact, using a JSON file with just that entry is enough to break the compilation in a native-image build. I don't think the code in `WebServerFactoryCustomizerBeanPostProcessor` has changed lately, so something in graal did change I guess. Hopefully this will make it easier to pinpoint.

**Comment by sdeleuze** [comment]
@dougxc @mukel Is https://github.com/oracle/graal/commit/fda115b5e3a9b2ed95aa085c6760307ee7ead568 expected to be part of RC4?

**Comment by mukel** [comment]
Landed just after the freeze, should be out for RC5.

**Comment by dsyer** [comment]
How about using the "milestone" feature in Github to track that?
