### ISSUE TITLE
Native Image exception  Clojure with SnakeYaml

### ISSUE THREAD

**Issue by gaberger** [oracle/graal#500]
```
** ERROR: **
JVM Exception: #error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [org.yaml.snakeyaml.util.PlatformFeatureDetector isRunningOnAndroid PlatformFeatureDetector.java 25]}]
 :trace
 [[org.yaml.snakeyaml.util.PlatformFeatureDetector isRunningOnAndroid PlatformFeatureDetector.java 25]
  [org.yaml.snakeyaml.introspector.PropertyUtils <init> PropertyUtils.java 60]
  [org.yaml.snakeyaml.introspector.PropertyUtils <init> PropertyUtils.java 50]
  [org.yaml.snakeyaml.constructor.BaseConstructor getPropertyUtils BaseConstructor.java 531]
  [org.yaml.snakeyaml.constructor.BaseConstructor addTypeDescription BaseConstructor.java 552]
  [org.yaml.snakeyaml.constructor.Constructor <init> Constructor.java 84]
  [org.yaml.snakeyaml.constructor.Constructor <init> Constructor.java 70]
  [org.yaml.snakeyaml.constructor.Constructor <init> Constructor.java 56]
  [org.yaml.snakeyaml.constructor.Constructor <init> Constructor.java 46]
  [org.yaml.snakeyaml.Yaml <init> Yaml.java 75]
  [yaml.writer$make_yaml invokeStatic writer.clj 30]
  [yaml.writer$make_yaml doInvoke writer.clj 27]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.core$apply invokeStatic core.clj 657]
  [clojure.core$apply invoke core.clj 652]
  [yaml.writer$generate_string invokeStatic writer.clj 74]
  [yaml.writer$generate_string doInvoke writer.clj 73]
  [clojure.lang.RestFn invoke RestFn.java 439]
  [nparser.frr.core$gen_yaml invokeStatic core.clj 34]
  [nparser.frr.core$gen_yaml invoke core.clj 29]
  [cli_matic.core$invoke_subcmd invokeStatic core.clj 557]
  [cli_matic.core$invoke_subcmd invoke core.clj 545]
  [cli_matic.core$run_cmd_STAR_ invokeStatic core.clj 591]
  [cli_matic.core$run_cmd_STAR_ invoke core.clj 577]
  [cli_matic.core$run_cmd invokeStatic core.clj 601]
  [cli_matic.core$run_cmd invoke core.clj 593]
  [nparser.frr.core$_main invokeStatic core.clj 76]
  [nparser.frr.core$_main doInvoke core.clj 75]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [nparser.frr.core main nil -1]
  [com.oracle.svm.reflect.proxies.Proxy_1_core_main invoke nil -1]
  [java.lang.reflect.Method invoke Method.java 498]
  [com.oracle.svm.core.JavaMainWrapper run JavaMainWrapper.java 173]]}
```

**Comment by dougxc** [comment]
Thanks for the report @gaberger . Can you please provide steps to reproduce this error.

**Comment by gaberger** [comment]
Ok the issue is not with SnakeYaml. The problem is with String method `startsWith`

```
public class GraalTest {

public static void main(String[] args) {
  String r = System.getProperty("java.runtime.name");
  r.startsWith("graalvm");
	}
}
```

Compiled with 
`native-image --report-unsupported-elements-at-runtime -Djava.runtime.name=graalvm --verbose GraalTest --static GraalTest`

Execution Exception

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.lang.Throwable.<init>(Throwable.java:310)
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:89)
	at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)
	at com.oracle.svm.reflect.proxies.Proxy_5_GraalTest_main.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:173)
Caused by: java.lang.NullPointerException
	at GraalTest.main(GraalTest.java:5)
	... 3 more```

Also, passing properties in with `-D` does not seem to work.

```
native-image --version
SubstrateVM Version Info
b76cd1450aa1085c6b82d3d7f1563fa0c26d6b03:substratevm
GraalVM Version 1.0.0-rc2
```

**Comment by Peter-B-Kessler** [comment]
The cause of the `NullPointerException` is because native images do not have a `java.runtime.name` System property.  So `r` is `null` and you are trying to invoke `String.startsWith` on it.

**Comment by gaberger** [comment]
Thanks Peter, my oversite. This was obviously a bad assumption by the SnakeYAML guys.. Before I close this, is there anyway to set SystemProperties with -D flag as noted in the doc so this can be overridden?

**Comment by Peter-B-Kessler** [comment]
In general, we can not carry over System properties from the native image builder to the generated native image.

You could parse the command line available to the native image to extract whatever you want the "java.runtime.name" property to be, and then call `System.getProperty("java.runtime.name", whatever)`.  If that System property is where your application expects to find that information.

**Comment by gaberger** [comment]
Ok thanks, I will file an issue with SnakeYAML to remove that assertion..
