### ISSUE TITLE
`ImageName` half-ignored on Windows, creating the image fails

### ISSUE THREAD

**Issue by helins** [oracle/graal#5008]
**Describe the issue**
The last step of image creation fails on windows when the image name is a path with directories. Whether provide as CLI arg or via `ImageName` in `native-image.properties`.

I actually don't have a Windows machine to experiment further but I struggled with building my image on Github Actions and eventually figured this out after talking [about it on Slack](https://graalvm.slack.com/archives/CN9KSFB40/p1663584122308889). I've tried several configurations and only solve that issue by providing an image name that does not contain directories.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Build any image by providing an image name like `./some/dir/foo`
2. Image creation will fail like below (step 7) but only on Windows ; MacOs and Linux have always been fine

**Describe GraalVM and your environment:**
- GraalVM 22.2.0, Java 17, `windows-latest` runner on Github Actions

**More details**

Those are the relevant bits at step 7 with `-H:+TraceNativeToolUsage`. Image name was `private/target/shell`. While we recognize `.../private/target/shell.lib` throughout, the very end fails with some sort of linker error mentioning `...shell.lib`.

```
># /out:D:\a\convex.cljc\convex.cljc\private\target\shell.exe 
># /INCREMENTAL:NO 
># /NODEFAULTLIB:LIBCMT 
># /FILEALIGN:4096 
># /IMPLIB:C:\Users\RUNNER~1\AppData\Local\Temp\SVM-9441898229368795664\private\target\shell.lib 
># /LIBPATH:C:\hostedtoolcache\windows\graalvm-ce-java17-windows\22.2.0\x64\graalvm-ce-java17-22.2.0\lib\static\windows-amd64 
Fatal error: com.oracle.svm.core.util.VMError$HostedError: should not reach here
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:64)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.jdk.JNIRegistrationSupport.makeShimDLL(JNIRegistrationSupport.java:273)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.jdk.JNIRegistrationSupport.makeShimDLLs(JNIRegistrationSupport.java:247)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.jdk.JNIRegistrationSupport.afterImageWrite(JNIRegistrationSupport.java:192)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$doRun$8(NativeImageGenerator.java:710)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:78)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:710)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
># /LIBPATH:C:\hostedtoolcache\windows\graalvm-ce-java17-windows\22.2.0\x64\graalvm-ce-java17-22.2.0\lib\svm\clibraries\windows-amd64 
># psapi.lib 
># winhttp.lib 
># ncrypt.lib 
># crypt32.lib 
># version.lib 
># advapi32.lib 
># ws2_32.lib 
># secur32.lib 
># iphlpapi.lib 
># userenv.lib 
># setargv.obj 
># shell32.lib 
># /export:JDK_LoadSystemLibrary 
># /export:JNU_CallMethodByName 
># /export:JNU_CallMethodByNameV 
># /export:JNU_CallStaticMethodByName 
># /export:JNU_ClassString 
># /export:JNU_GetEnv 
># /export:JNU_GetFieldByName 
># /export:JNU_GetStaticFieldByName 
># /export:JNU_IsInstanceOfByName 
># /export:JNU_NewObjectByName 
># /export:JNU_NewStringPlatform 
># /export:JNU_SetFieldByName 
># /export:JNU_ThrowArrayIndexOutOfBoundsException 
># /export:JNU_ThrowByName 
># /export:JNU_ThrowIOException 
># /export:JNU_ThrowIllegalArgumentException 
># /export:JNU_ThrowInternalError 
># /export:JNU_ThrowNullPointerException 
># /export:JNU_ThrowOutOfMemoryError 
># /export:getEncodingFromLangID 
># /export:getJavaIDFromLangID 
># /export:JVM_CurrentTimeMillis 
># /export:JVM_RaiseSignal 
># /export:jio_snprintf 
># private\target\shell.obj 
># C:\hostedtoolcache\windows\graalvm-ce-java17-windows\22.2.0\x64\graalvm-ce-java17-22.2.0\lib\svm\clibraries\windows-amd64\libchelper.lib 
># C:\hostedtoolcache\windows\graalvm-ce-java17-windows\22.2.0\x64\graalvm-ce-java17-22.2.0\lib\static\windows-amd64\net.lib 
># C:\hostedtoolcache\windows\graalvm-ce-java17-windows\22.2.0\x64\graalvm-ce-java17-22.2.0\lib\static\windows-amd64\nio.lib 
># C:\hostedtoolcache\windows\graalvm-ce-java17-windows\22.2.0\x64\graalvm-ce-java17-22.2.0\lib\static\windows-amd64\management_ext.lib 
># C:\hostedtoolcache\windows\graalvm-ce-java17-windows\22.2.0\x64\graalvm-ce-java17-22.2.0\lib\static\windows-amd64\java.lib 
># C:\hostedtoolcache\windows\graalvm-ce-java17-windows\22.2.0\x64\graalvm-ce-java17-22.2.0\lib\static\windows-amd64\fdlibm.lib 
># C:\hostedtoolcache\windows\graalvm-ce-java17-windows\22.2.0\x64\graalvm-ce-java17-22.2.0\lib\static\windows-amd64\sunmscapi.lib 
># C:\hostedtoolcache\windows\graalvm-ce-java17-windows\22.2.0\x64\graalvm-ce-java17-22.2.0\lib\static\windows-amd64\zip.lib 
># C:\hostedtoolcache\windows\graalvm-ce-java17-windows\22.2.0\x64\graalvm-ce-java17-22.2.0\lib\svm\clibraries\windows-amd64\jvm.lib 
># C:\hostedtoolcache\windows\graalvm-ce-java17-windows\22.2.0\x64\graalvm-ce-java17-22.2.0\lib\svm\clibraries\windows-amd64\libchelper.lib 
># C:\hostedtoolcache\windows\graalvm-ce-java17-windows\22.2.0\x64\graalvm-ce-java17-22.2.0\lib\static\windows-amd64\net.lib 
># C:\hostedtoolcache\windows\graalvm-ce-java17-windows\22.2.0\x64\graalvm-ce-java17-22.2.0\lib\static\windows-amd64\nio.lib 
># C:\hostedtoolcache\windows\graalvm-ce-java17-windows\22.2.0\x64\graalvm-ce-java17-22.2.0\lib\static\windows-amd64\management_ext.lib 
># C:\hostedtoolcache\windows\graalvm-ce-java17-windows\22.2.0\x64\graalvm-ce-java17-22.2.0\lib\static\windows-amd64\java.lib 
># C:\hostedtoolcache\windows\graalvm-ce-java17-windows\22.2.0\x64\graalvm-ce-java17-22.2.0\lib\static\windows-amd64\fdlibm.lib 
># C:\hostedtoolcache\windows\graalvm-ce-java17-windows\22.2.0\x64\graalvm-ce-java17-22.2.0\lib\static\windows-amd64\sunmscapi.lib 
># C:\hostedtoolcache\windows\graalvm-ce-java17-windows\22.2.0\x64\graalvm-ce-java17-22.2.0\lib\static\windows-amd64\zip.lib 
># C:\hostedtoolcache\windows\graalvm-ce-java17-windows\22.2.0\x64\graalvm-ce-java17-22.2.0\lib\svm\clibraries\windows-amd64\jvm.lib 
>#    Creating library C:\Users\RUNNER~1\AppData\Local\Temp\SVM-9441898229368795664\private\target\shell.lib and object C:\Users\RUNNER~1\AppData\Local\Temp\SVM-9441898229368795664\private\target\shell.exp
>> 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.33.3[162](https://github.com/Convex-Dev/convex.cljc/actions/runs/3087983266/jobs/4993947889#step:6:163)9\bin\HostX64\x64\cl.exe' '/FeD:\a\convex.cljc\convex.cljc\private\target\java.dll' 'C:\Users\RUNNER~1\AppData\Local\Temp\SVM-9441898229368795664\shell.lib' msvcrt.lib /link /dll /implib:java.lib /export:JDK_LoadSystemLibrary /export:JNU_CallMethodByName /export:JNU_CallMethodByNameV /export:JNU_CallStaticMethodByName /export:JNU_ClassString /export:JNU_GetEnv /export:JNU_GetFieldByName /export:JNU_GetStaticFieldByName /export:JNU_IsInstanceOfByName /export:JNU_NewObjectByName /export:JNU_NewStringPlatform /export:JNU_SetFieldByName /export:JNU_ThrowArrayIndexOutOfBoundsException /export:JNU_ThrowByName /export:JNU_ThrowIOException /export:JNU_ThrowIllegalArgumentException /export:JNU_ThrowInternalError /export:JNU_ThrowNullPointerException /export:JNU_ThrowOutOfMemoryError /export:getEncodingFromLangID /export:getJavaIDFromLangID
># Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31629 for x64
># Copyright (C) Microsoft Corporation.  All rights reserved.
># 
># Microsoft (R) Incremental Linker Version 14.33.31629.0
># Copyright (C) Microsoft Corporation.  All rights reserved.
># 
># /out:D:\a\convex.cljc\convex.cljc\private\target\java.dll 
># /dll 
># /implib:java.lib 
># /export:JDK_LoadSystemLibrary 
># /export:JNU_CallMethodByName 
># /export:JNU_CallMethodByNameV 
># /export:JNU_CallStaticMethodByName 
># /export:JNU_ClassString 
># /export:JNU_GetEnv 
># /export:JNU_GetFieldByName 
># /export:JNU_GetStaticFieldByName 
># /export:JNU_IsInstanceOfByName 
># /export:JNU_NewObjectByName 
># /export:JNU_NewStringPlatform 
># /export:JNU_SetFieldByName 
># /export:JNU_ThrowArrayIndexOutOfBoundsException 
># /export:JNU_ThrowByName 
># /export:JNU_ThrowIOException 
># /export:JNU_ThrowIllegalArgumentException 
># /export:JNU_ThrowInternalError 
># /export:JNU_ThrowNullPointerException 
># /export:JNU_ThrowOutOfMemoryError 
># /export:getEncodingFromLangID 
># /export:getJavaIDFromLangID 
># C:\Users\RUNNER~1\AppData\Local\Temp\SVM-9441898229368795664\shell.lib 
># msvcrt.lib 
># LINK : fatal error LNK1181: cannot open input file 'C:\Users\RUNNER~1\AppData\Local\Temp\SVM-9441898229368795664\shell.lib'
```

**Comment by mageddo** [comment]
Still get  issue, see my report https://github.com/oracle/graal/issues/4563#issuecomment-1467314733
