### ISSUE TITLE
ModuleNotFoundError when use GraalPython with multiple python files

### ISSUE THREAD

**Issue by cyw3** [oracle/graal#5043]
**Describe the issue**
 I use GraalPython to run multiple python files.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Here is the demo
```python
# test1.py
def test1():
    print("test1")
```
```python
# test.py
import test1
import polyglot as poly

def test():
    print("test")
    test1.test1()

poly.export_value("test", test)

test()
```

```java
// Test.java
import java.io.File;

import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.Source;
import org.graalvm.polyglot.Value;

public class Test {
    public void callPythonMethods() {
        Context ctx = Context.newBuilder().allowAllAccess(true).build();
        try {
            File fibCal = new File("./test.py");
            ctx.eval(Source.newBuilder("python", fibCal).build());

            Value hearAnalysisFn = ctx.getBindings("python").getMember("test");

            Value heartAnalysisReport = hearAnalysisFn.execute();
            System.out.println("Average age of people who are getting level 3 and greater chest pain :" + heartAnalysisReport.toString());

        }   catch (Exception e) {
            System.out.println("Exception : " );
            e.printStackTrace();
        }
    }
    public static void main(String[] args) {
        Test obj = new Test();
        obj.callPythonMethods();
    }
}
```

2. Test with graalpython
```bash
$ graalpython test.py
test
test1
```

3. Test with java
```bash
$ javac Test.java
$ java Test
Exception : 
ModuleNotFoundError: No module named 'test1'
        at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:399)
        at Test.callPythonMethods(Test.java:12)
        at Test.main(Test.java:26)
```

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **[e.g. EE 19.3, CE 20.0, CE 20.1.0-dev-20200304_0848]**
 graalvm-ce-java17-22.1.0
 - JDK major version: **[e.g.:8]**
 JDK17
 - OS: **[e.g. macOS Catalina]**
 Centos7
 - Architecture: **[e.g.: AMD64]**
AMD64

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this, we'll take a look into it shortly

**Comment by cyw3** [comment]
> version 22.2.0

The version 22.2.0 has the same issue.

**Comment by oubidar-Abderrahim** [comment]
Tracked internally on GR 41886

**Comment by timfel** [comment]
The problem is that the directory is not on the python path. When you run the commandline, the directory of the argument script is automatically put on the path. When you embed in Java, you need to do this manually. Two options:

```java
// set PythonPath to the current working directory so we can import stuff from here
Context.newBuilder().allowAllAccess(true).option("python.PythonPath", ".") build();
```

```python
# in test.py

## add the directory that this file is in to the search path
import sys
import os.path
sys.path.insert(0, os.path.dirname(__file__))

...
```

**Comment by cyw3** [comment]
It work. Thanks.

Is there more doc proviced?
