### ISSUE TITLE
Can not access the JS function

### ISSUE THREAD

**Issue by feixiangdejiahao** [oracle/graal#5071]
**Describe GraalVM and your environment :**
 - CE or EE: **CE**
 - JDK version: **JDK11**
 - OS and OS Version: **Ubuntu 18.04**
 - The output of `java -Xinternalversion`:
```
 **OpenJDK 64-Bit Server VM (11.0.16+8-jvmci-22.2-b06) for linux-amd64 JRE (11.0.16+8-jvmci-22.2-b06), built on Jul 20 2022 19:06:49 by "buildslave" with gcc 7.3.0**
```

**Have you verified this issue still happens when using the latest snapshot?**
Yes

**Describe the issue**
When I try to use a JS function in the Java file, GraalVM throws a java.lang.UnsupportedOperationException.

**Code snippet or code repository that reproduces the issue**
```
import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.Value;

public class Main {
    public static void main(String[] args) {
        try (Context context = Context.create()) {
            Value function = context.eval("js", "function compute(n){" +
                    "n|=0;" +
                    "if (n < 0){" +
                    "let v= (-n) | 0;" +
                    "return Math.abs(n);}}");
            assert function.canExecute();
            int x = function.execute(-1).asInt();
            System.out.println(x);
        }
    }
}
```

**Steps to reproduce the issue**
```
$ cat main.js
function compute(n) {
    n |= 0;
    if (n < 0) {
        let v = (-n) | 0;
        return Math.abs(n);
    }
}
a = compute(-1);
console.log(a);
$ js main.js
1

$ javac Main.java
$ java Main
Exception in thread "main" java.lang.UnsupportedOperationException: Unsupported operation Value.execute(Object...) for 'undefined'(language: JavaScript, type: undefined). You can ensure that the operation is supported using Value.canExecute().
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineException.unsupported(PolyglotEngineException.java:147)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch.unsupported(PolyglotValueDispatch.java:1257)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch.executeUnsupported(PolyglotValueDispatch.java:595)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$AbstractExecuteNode.executeShared(PolyglotValueDispatch.java:4277)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$ExecuteNode.executeImpl(PolyglotValueDispatch.java:4349)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:124)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:656)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:628)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:561)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:545)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalRuntimeSupport.callProfiled(GraalRuntimeSupport.java:255)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue.execute(PolyglotValueDispatch.java:2396)
        at org.graalvm.sdk/org.graalvm.polyglot.Value.execute(Value.java:880)
        at Main.main(Main.java:13)
Caused by: Attached Guest Language Frames (1)
```

**Expected behavior**
```
$ java Main
1
```
</details>

**Comment by jirkamarsik** [comment]
Hi @feixiangdejiahao . You are seeing this error because you are trying to evaluate a function declaration statement. JavaScript makes a distinction between function declaration statements and function expressions, the former always evaluating to `undefined` and the latter evaluating to a function object. If you write a function this way in a JavaScript source, it is always parsed as a function declaration statement instead of a function expression. You can test this out in pure JavaScript using `eval`:

```
const f = eval("function compute(n) {" +
    "n |= 0;" +
    "if (n < 0) {" +
        "let v = (-n) | 0;" +
        "return Math.abs(n);" +
    "}" +
"}");
const x = f(-1);
console.log(x);
```

This code will throw a `TypeError`, because `x` will be `undefined`. It is essentially the same code as your example above.

In order to fix your example, you can do one of two things:
1) You can wrap your function in parentheses, which will force JavaScript to treat is a function expression. That way, you get the behavior that you were originally expecting:
```
import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.Value;

public class Main {
    public static void main(String[] args) {
        try (Context context = Context.create()) {
            Value function = context.eval("js", "(function compute(n){" +
                    "n|=0;" +
                    "if (n < 0){" +
                    "let v= (-n) | 0;" +
                    "return Math.abs(n);}})");
            assert function.canExecute();
            int x = function.execute(-1).asInt();
            System.out.println(x);
        }
    }
}
```
2) If you want to access the function while using the same JavaScript source as in your example, you can also access the global JavaScript bindings where the function declaration statement stored your function.
```
import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.Value;

public class Main {
    public static void main(String[] args) {
        try (Context context = Context.create()) {
            context.eval("js", "function compute(n){" +
                    "n|=0;" +
                    "if (n < 0){" +
                    "let v= (-n) | 0;" +
                    "return Math.abs(n);}}");
            Value function = context.getBindings("js").getMember("compute");
            assert function.canExecute();
            int x = function.execute(-1).asInt();
            System.out.println(x);
        }
    }
}
```

**Comment by feixiangdejiahao** [comment]
Thanks for your detailed explanation!
