### ISSUE TITLE
CodeCache is fully occupied frequently with graalvm 22.2 JDK11

### ISSUE THREAD

**Issue by diddowill** [oracle/graal#5103]
**Describe the issue**
After switching to graalvm 22.2，our applicatons frequently run into a crash due to out of code cache space after liveness of one or two weeks.
```
Uncaught error from thread lapplication-akka.actor.default-dispatcher-56]: Out of space in CodeCache for adapters, shutting down VM since 'akka.jvm-exit-on-fatal-error
1S enabled Tor Actorsystemlapplication.
java. Lang.Virtua (MachineError: Out of space in CodeCache for adapters
at com.qoogle.qson.internal.bind.ReflectiveTvpeAdapterFactorv.createBoundField(ReflectiveTypeAdapterFactorv.iava:120,
com.google.gson.internal.bind.ReflectivelypeAdapterFactory.getBoundFields(ReflectivelypeAdapterFactory.java:166)
at com.google.ason.internal-bind.keTlectivelypeAdapterractory.create(kerlectivelypeAdapterractory:lava:102
com.google.gson.Gson.getDelegateAdapter(Gson.java:541)
at io.gsonfire.gson.WrapTypeAdapterFactorv.create(WrapTvpeAdapterFactorv.iava:26)
at com.google-gson.uson.getAdapter(Gson.java:458)
at com.google-gson.Gson.TromJson(uson.lava:931)
Gson-fromJson(Gson-iava:897)
at com. google-ason.Gson.TromJson(uson-lava:846)
io-kubernetes-client-obenaoi.JSON-deserialize(JSON-java:142)
io.kubernetes.client.openapi.ApiClient.deserialize(ApiClient.java:779)
io-kubernetes.client.ooenaoi-ApiClient.handleResoonse(ApiClient-iava:980)
i0-kubernetes.client.openapi.ApiClient.execute(ApiClient.java:905)
10.kubernetes.client-openapi.apis.CoreV1Api.listNamespacedPodwithHttpInfo(CoreVlApi.java:30930)
10.kubernetes.client.openapl.ap1s.LoreviApl.L1StNamespacedrod(loreviApl.lava:30818)
K8sManagerServicelmol.detPodStatusWithPrefix(K8sManagerServicelmol-scala:109)
at controllers.KosManagerlontroller.sanontunsgetrodListsKosManagerLontroller.scala:/9)
at utils.auth-SecureController-aroundH
er-scalaros
at utils.auth.securelontroller
troller.scala://3)
(ZiokinTraceImolicits-scala:71)
quandata z10k1n.1mpLicits.<10k1n
is.wrapspanrorkequests\zipkinIraceImplicits.scala:23
Controller-scala:19)
at utils.auth.securelontro
§anonfunsLoaTracedActionAsvnc$1(SecureController-scala:517)
at utils.auth.securelontroller
. SanonTunsAuthorizedActionASVnc$4(Securelontroller.scala:486)
utils.auth.SecureContro
iredActionAsvnc$4sadanted(SecureController-scala:482
at scala.concurrent.ruture
(ruture.scala:30/)
mwiths1(Promise-scala:41
at scala.concurrent. impl
run(Promise.scala:64)
†Batch.orocessBatch(BatchinaExecutor-scala:63)
at akka.d1spatch.batchir
‹ablebatn.snonunsrunsI(batchinatxecutor.scala:100)
at scald. runtim.javd.J.
cVsso.aoolv(]Functiondsmcvsso.iava:23)
at scala.concurrent.blocklontexts.withblocklontext\blocklontext.scala:8)
akka.dispatch-BatchinaExecuto
r$BlockableBatch. run BatchinaExecutor-scala:100)
at akka.d1spatch.laskInvocation.run(AbstractDispatcher.scala:49)
akka.dispatch.ForkloinExecutorConfiguratorsAkkaForkloinTask.exec(ForkloinExecutorConfigurator-scala:48,
at
java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
lava.base/lava.utll.concurrent.rorkJoinpool.scan(rorkJo1npool.lava:1656)
java.base/java.util.concurrent.ForkJoinPool.runworker(ForkJoinPool.java:1594)
java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
Sometimes crash does not happen, but the application would run very slowly with high cpu load.

**Steps to reproduce the issue**

No code can be provided for now.

**Describe GraalVM and your environment:**
 - GraalVM version : **graalvm-ce-java11-22.2.0**
 - JDK major version: **11**
 - OS: **CentOS 7.6**
 - Architecture: **AMD64**

**More details**
code cache log from jcmd  Compiler.CodeHeap_Analytics is provided below.
http://122.9.181.207:8888/codecache.log.zip

Which is suspicious:  Stub<AMD64MathStub.pow> appears repeatedly in the non-profiled nmethods statistics.

`+---------------------------------------------------+
|  no free blocks found in CodeHeap 'non-nmethods'  |
+---------------------------------------------------+
======================================================================================
=  U S E D   S P A C E   S T A T I S T I C S   for CodeHeap 'non-profiled nmethods'  =
======================================================================================
Note: The Top100 list of the largest used blocks associates method names
      and other identifying information with the block size data.
+-----------------------------------------------------------+
|  Largest Used Blocks in CodeHeap 'non-profiled nmethods'  |
+-----------------------------------------------------------+

  -----------------------------------------------------

                                                   blob  compiler method
Addr(module)              offset              size type  type lvl   temp Name
0x00007f525b414110 (+0x029f5110) 0x000053f0(  20K)   N  jvmci   4    640 io.netty.channel.nio.NioEventLoop.run()V
0x00007f5262753310 (+0x09d34310) 0x00004560(  17K)   N     c1   1    640 java.util.GregorianCalendar.computeFields(II)I
0x00007f525b735390 (+0x02d16390) 0x000041d8(  16K)   X  jvmci   4      0 io.netty.channel.epoll.EpollEventLoop.run()V
0x00007f525b0b7a90 (+0x02698a90) 0x00004700(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525fe1d990 (+0x073fe990) 0x00004700(  17K)                       Stub<AMD64MathStub.pow>
0x00007f526046c690 (+0x07a4d690) 0x00004700(  17K)                       Stub<AMD64MathStub.pow>
0x00007f5261986610 (+0x08f67610) 0x00004700(  17K)                       Stub<AMD64MathStub.pow>
0x00007f52624ce010 (+0x09aaf010) 0x00004700(  17K)                       Stub<AMD64MathStub.pow>
0x00007f52625bcf10 (+0x09b9df10) 0x00004700(  17K)                       Stub<AMD64MathStub.pow>
0x00007f52625edd10 (+0x09bced10) 0x00004700(  17K)                       Stub<AMD64MathStub.pow>
0x00007f5258faa890 (+0x0058b890) 0x00004680(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525dc96210 (+0x05277210) 0x00004090(  16K)   N  jvmci   4    640 io.netty.channel.epoll.EpollEventLoop.run()V
0x00007f526143c610 (+0x08a1d610) 0x00004680(  17K)                       Stub<AMD64MathStub.pow>
0x00007f52615e3010 (+0x08bc4010) 0x00004680(  17K)                       Stub<AMD64MathStub.pow>
0x00007f5261ecd310 (+0x094ae310) 0x00004680(  17K)                       Stub<AMD64MathStub.pow>
0x00007f52622b1590 (+0x09892590) 0x00004680(  17K)                       Stub<AMD64MathStub.pow>
0x00007f52625f6f10 (+0x09bd7f10) 0x00004680(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525b611790 (+0x02bf2790) 0x00004600(  17K)                       Stub<AMD64MathStub.pow>
0x00007f5260c3df10 (+0x0821ef10) 0x00004600(  17K)                       Stub<AMD64MathStub.pow>
0x00007f5261c93090 (+0x09274090) 0x00004600(  17K)                       Stub<AMD64MathStub.pow>
0x00007f52623d3090 (+0x099b4090) 0x00004600(  17K)                       Stub<AMD64MathStub.pow>
0x00007f52625fb590 (+0x09bdc590) 0x00004600(  17K)                       Stub<AMD64MathStub.pow>
0x00007f52626ec210 (+0x09ccd210) 0x00004600(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525ebe6190 (+0x061c7190) 0x00004580(  17K)                       Stub<AMD64MathStub.pow>
0x00007f5260b20510 (+0x08101510) 0x00004580(  17K)                       Stub<AMD64MathStub.pow>
0x00007f5260ec3890 (+0x084a4890) 0x00004580(  17K)                       Stub<AMD64MathStub.pow>
0x00007f5260f24410 (+0x08505410) 0x00004580(  17K)                       Stub<AMD64MathStub.pow>
0x00007f5261055910 (+0x08636910) 0x00004580(  17K)                       Stub<AMD64MathStub.pow>
0x00007f5262454e90 (+0x09a35e90) 0x00004580(  17K)                       Stub<AMD64MathStub.pow>
0x00007f52625b6e10 (+0x09b97e10) 0x00004580(  17K)                       Stub<AMD64MathStub.pow>
0x00007f5259322890 (+0x00903890) 0x00004500(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525a7c8f90 (+0x01da9f90) 0x00004500(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525a7f9590 (+0x01dda590) 0x00004500(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525c534210 (+0x03b15210) 0x00004500(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525c71ad90 (+0x03cfbd90) 0x00004500(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525cc2d490 (+0x0420e490) 0x00004500(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525fbf9510 (+0x071da510) 0x00004500(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525ffa9290 (+0x0758a290) 0x00004500(  17K)                       Stub<AMD64MathStub.pow>
0x00007f52624be410 (+0x09a9f410) 0x00004500(  17K)                       Stub<AMD64MathStub.pow>
0x00007f52592de690 (+0x008bf690) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f52599fd710 (+0x00fde710) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f5259a01b90 (+0x00fe2b90) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f5259c10710 (+0x011f1710) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f5259c38210 (+0x01219210) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f5259f40610 (+0x01521610) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525a010010 (+0x015f1010) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525a01c510 (+0x015fd510) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525a1d7390 (+0x017b8390) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525a519890 (+0x01afa890) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525a76a010 (+0x01d4b010) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525a779b10 (+0x01d5ab10) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525a7bf910 (+0x01da0910) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525a874190 (+0x01e55190) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525aa97910 (+0x02078910) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525ae0af90 (+0x023ebf90) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525ae36590 (+0x02417590) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525af3b810 (+0x0251c810) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525b0a2c10 (+0x02683c10) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525b576290 (+0x02b57290) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525b581110 (+0x02b62110) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525b64fc10 (+0x02c30c10) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525b90f010 (+0x02ef0010) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525bb23a90 (+0x03104a90) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525bd42710 (+0x03323710) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525bd60d90 (+0x03341d90) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525bf4e110 (+0x0352f110) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525c337d90 (+0x03918d90) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525c37ad90 (+0x0395bd90) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525c6f4f90 (+0x03cd5f90) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525c788710 (+0x03d69710) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525c798090 (+0x03d79090) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525c79c510 (+0x03d7d510) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525c7a0990 (+0x03d81990) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525c7db390 (+0x03dbc390) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525c85df90 (+0x03e3ef90) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525c97b390 (+0x03f5c390) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525c9bb110 (+0x03f9c110) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525ce53410 (+0x04434410) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525d03d510 (+0x0461e510) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525d09d710 (+0x0467e710) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525d0ec390 (+0x046cd390) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525d0fb110 (+0x046dc110) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525d11fc90 (+0x04700c90) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525d197390 (+0x04778390) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525d53e810 (+0x04b1f810) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525d590c10 (+0x04b71c10) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525ddbf310 (+0x053a0310) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525dff3210 (+0x055d4210) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525e0ba010 (+0x0569b010) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525e207110 (+0x057e8110) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525e402710 (+0x059e3710) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525e455290 (+0x05a36290) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525e743990 (+0x05d24990) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525e815690 (+0x05df6690) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525e8bea10 (+0x05e9fa10) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525e8ca590 (+0x05eab590) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525e9a7310 (+0x05f88310) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525ee1ee90 (+0x063ffe90) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525eebd710 (+0x0649e710) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>
0x00007f525f0f7b90 (+0x066d8b90) 0x00004480(  17K)                       Stub<AMD64MathStub.pow>`

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, we'll take a look into this and then get back to you if needed.

**Comment by oubidar-Abderrahim** [comment]
@diddowill please remove all PI in your logs and share them as attached files or in a gist/repo in Github.

**Comment by diddowill** [comment]
@oubidar-Abderrahim Thanks for the note. But the log file is too big for a gist file. I will remove the download link if you have download it.

**Comment by qomosoloto** [comment]
The most straight difference can be seen below (ps: we switched back to 20.2.0 at 10-10)
![image](https://user-images.githubusercontent.com/8132885/195485025-bfbc9e24-1b8b-484d-b70c-be119a79bea0.png)

**Comment by oubidar-Abderrahim** [comment]
Hi, Any updates?

**Comment by oubidar-Abderrahim** [comment]
I'll be closing this issue for inactivity. If you still need assistance, please reopen the issue and provide the requested logs using a secure method. Thank you
