### ISSUE TITLE
Native image build hangs for a working jar

### ISSUE THREAD

**Issue by HindujaB** [oracle/graal#5109]
**Describe the issue**
I am getting an `Image generator watchdog detected no activity` error when I build the native image for a jar. 
The execution of `java -jar foo.jar` works without an issue. 
The version information :
```
 Version info: 'GraalVM 22.2.0 Java 11 CE'
 Java version info: '11.0.16+8-jvmci-22.2-b06'
 C compiler: gcc (linux, x86_64, 9.4.0)
 Garbage collector: Serial GC
 1 user-specific feature(s)
 - com.oracle.svm.thirdparty.gson.GsonFeature
```
**Steps to reproduce the issue**
Download the jar file [here](https://drive.google.com/file/d/1nu9BT0Ftr6-b_ms-3z7Ye-ozPnmBK2Nn/view?usp=sharing). 

```
native-image -H:MaxDuplicationFactor=40.0 -jar foo.jar
```
I added the required resource configurations. 

Error log : 
```
=== Image generator watchdog detected no activity. This can be a sign of a deadlock during image building. Dumping all stack traces. Current time: Thu Sep 29 16:42:12 IST 2022
"main" Id=1 in RUNNABLE
    at java.base@11.0.16/java.lang.Thread.yield(Native Method)
    at java.base@11.0.16/java.util.concurrent.ForkJoinPool.awaitQuiescence(ForkJoinPool.java:2990)
    at app/org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.complete(CompletionExecutor.java:243)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.compileAll(CompileQueue.java:802)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.finish(CompileQueue.java:451)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:637)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)

"Reference Handler" Id=2 in RUNNABLE
    at java.base@11.0.16/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
    at java.base@11.0.16/java.lang.ref.Reference.processPendingReferences(Reference.java:241)
    at java.base@11.0.16/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:213)

"Finalizer" Id=3 in WAITING on lock=java.lang.ref.ReferenceQueue$Lock@86ce9e1
    at java.base@11.0.16/java.lang.Object.wait(Native Method)
    at java.base@11.0.16/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
    at java.base@11.0.16/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
    at java.base@11.0.16/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:170)

"Signal Dispatcher" Id=4 in RUNNABLE

"JVMCI-native CompilerThread0" Id=6 in RUNNABLE

"Common-Cleaner" Id=9 in TIMED_WAITING on lock=java.lang.ref.ReferenceQueue$Lock@c537c34
    at java.base@11.0.16/java.lang.Object.wait(Native Method)
    at java.base@11.0.16/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
    at java.base@11.0.16/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148)
    at java.base@11.0.16/java.lang.Thread.run(Thread.java:829)
    at java.base@11.0.16/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:161)

"native-image pid watcher" Id=10 in TIMED_WAITING on lock=java.util.TaskQueue@4951e3da
    at java.base@11.0.16/java.lang.Object.wait(Native Method)
    at java.base@11.0.16/java.util.TimerThread.mainLoop(Timer.java:553)
    at java.base@11.0.16/java.util.TimerThread.run(Timer.java:506)

"Thread-2" Id=24 in RUNNABLE
    at java.management@11.0.16/sun.management.ThreadImpl.dumpThreads0(Native Method)
    at java.management@11.0.16/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:521)
    at java.management@11.0.16/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:509)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.DeadlockWatchdog.threadDump(DeadlockWatchdog.java:113)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.DeadlockWatchdog.watchdogThread(DeadlockWatchdog.java:80)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.DeadlockWatchdog$$Lambda$164/0x00000007c0282040.run(Unknown Source)
    at java.base@11.0.16/java.lang.Thread.run(Thread.java:829)

"Timer-0" Id=45 in TIMED_WAITING on lock=java.util.TaskQueue@171edc83
    at java.base@11.0.16/java.lang.Object.wait(Native Method)
    at java.base@11.0.16/java.util.TimerThread.mainLoop(Timer.java:553)
    at java.base@11.0.16/java.util.TimerThread.run(Timer.java:506)

"ForkJoinPool-2-worker-5" Id=48 in WAITING on lock=java.util.concurrent.ForkJoinPool@78d20c60
    at java.base@11.0.16/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.16/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.16/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
    at java.base@11.0.16/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"ForkJoinPool-2-worker-7" Id=49 in TIMED_WAITING on lock=java.util.concurrent.ForkJoinPool@78d20c60
    at java.base@11.0.16/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.16/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:275)
    at java.base@11.0.16/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1619)
    at java.base@11.0.16/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"ForkJoinPool-2-worker-15" Id=53 in WAITING on lock=java.util.concurrent.ForkJoinPool@78d20c60
    at java.base@11.0.16/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.16/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.16/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
    at java.base@11.0.16/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"ForkJoinPool.commonPool-worker-7" Id=59 in WAITING on lock=java.util.concurrent.ForkJoinPool@79fdbe5d
    at java.base@11.0.16/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.16/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.16/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
    at java.base@11.0.16/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"ForkJoinPool.commonPool-worker-9" Id=60 in WAITING on lock=java.util.concurrent.ForkJoinPool@79fdbe5d
    at java.base@11.0.16/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.16/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.16/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
    at java.base@11.0.16/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"ForkJoinPool.commonPool-worker-13" Id=62 in TIMED_WAITING on lock=java.util.concurrent.ForkJoinPool@79fdbe5d
    at java.base@11.0.16/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.16/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:275)
    at java.base@11.0.16/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1619)
    at java.base@11.0.16/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"pool-1-thread-1" Id=64 in TIMED_WAITING on lock=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@6f776d92
    at java.base@11.0.16/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.16/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
    at java.base@11.0.16/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
    at java.base@11.0.16/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
    at java.base@11.0.16/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
    at java.base@11.0.16/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
    at java.base@11.0.16/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
    at java.base@11.0.16/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base@11.0.16/java.lang.Thread.run(Thread.java:829)

"ForkJoinPool-3-worker-3" Id=65 in WAITING on lock=java.util.concurrent.ForkJoinPool@297e1c95
    at java.base@11.0.16/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.16/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.16/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
    at java.base@11.0.16/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"ForkJoinPool-3-worker-5" Id=66 in WAITING on lock=java.util.concurrent.ForkJoinPool@297e1c95
    at java.base@11.0.16/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.16/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.16/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
    at java.base@11.0.16/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"ForkJoinPool-3-worker-9" Id=68 in WAITING on lock=java.util.concurrent.ForkJoinPool@297e1c95
    at java.base@11.0.16/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.16/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.16/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
    at java.base@11.0.16/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"ForkJoinPool-3-worker-7" Id=67 in WAITING on lock=java.util.concurrent.ForkJoinPool@297e1c95
    at java.base@11.0.16/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.16/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.16/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
    at java.base@11.0.16/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"ForkJoinPool-3-worker-13" Id=70 in WAITING on lock=java.util.concurrent.ForkJoinPool@297e1c95
    at java.base@11.0.16/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.16/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.16/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
    at java.base@11.0.16/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"ForkJoinPool-3-worker-11" Id=69 in WAITING on lock=java.util.concurrent.ForkJoinPool@297e1c95
    at java.base@11.0.16/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.16/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.16/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
    at java.base@11.0.16/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"ForkJoinPool-3-worker-1" Id=72 in RUNNABLE
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.lir.alloc.lsra.Range.intersectsAt(Range.java:77)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.lir.alloc.lsra.Interval.currentIntersectsAt(Interval.java:720)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.lir.alloc.lsra.LinearScanWalker.freeCollectInactiveFixed(LinearScanWalker.java:211)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.lir.alloc.lsra.LinearScanWalker.allocFreeRegister(LinearScanWalker.java:774)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.lir.alloc.lsra.LinearScanWalker.activateCurrent(LinearScanWalker.java:1137)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.lir.alloc.lsra.IntervalWalker.walkTo(IntervalWalker.java:241)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.lir.alloc.lsra.IntervalWalker.walk(IntervalWalker.java:79)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.lir.alloc.lsra.LinearScanRegisterAllocationPhase.allocateRegisters(LinearScanRegisterAllocationPhase.java:66)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.lir.alloc.lsra.LinearScanRegisterAllocationPhase.run(LinearScanRegisterAllocationPhase.java:45)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.lir.alloc.lsra.LinearScanAllocationPhase.apply(LinearScanAllocationPhase.java:55)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.lir.alloc.lsra.LinearScanAllocationPhase.apply(LinearScanAllocationPhase.java:47)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.lir.alloc.lsra.LinearScan.allocate(LinearScan.java:755)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.lir.alloc.lsra.LinearScanPhase.run(LinearScanPhase.java:42)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.lir.alloc.lsra.LinearScanPhase.run(LinearScanPhase.java:35)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.lir.phases.LIRPhase.apply(LIRPhase.java:121)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.lir.phases.LIRPhase.apply(LIRPhase.java:110)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.lir.phases.LIRPhaseSuite.run(LIRPhaseSuite.java:100)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.lir.phases.LIRPhase.apply(LIRPhase.java:121)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.lir.phases.LIRPhase.apply(LIRPhase.java:110)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.core.gen.LIRCompilerBackend.emitLowLevel(LIRCompilerBackend.java:186)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.core.gen.LIRCompilerBackend.emitLIR0(LIRCompilerBackend.java:166)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.core.gen.LIRCompilerBackend.emitLIR(LIRCompilerBackend.java:116)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.core.gen.LIRCompilerBackend.emitBackEnd(LIRCompilerBackend.java:87)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.core.target.Backend.emitBackEnd(Backend.java:289)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:146)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:130)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:1417)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue$$Lambda$1885/0x00000007c2568040.compile(Unknown Source)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:1370)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:337)
    at app/org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
    at app/org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
    at app/org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor$$Lambda$545/0x00000007c1e96c40.run(Unknown Source)
    at java.base@11.0.16/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
    at java.base@11.0.16/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base@11.0.16/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base@11.0.16/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base@11.0.16/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base@11.0.16/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

"ForkJoinPool-3-worker-15" Id=71 in WAITING on lock=java.util.concurrent.ForkJoinPool@297e1c95
    at java.base@11.0.16/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.16/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.16/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
    at java.base@11.0.16/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)


=== Memory statistics (in MB):
=== Used heap size: 10335
=== Free heap size: 2325
=== Maximum heap size: 11236
=== Image generator watchdog is aborting image generation. To configure the watchdog, use the options -H:DeadlockWatchdogInterval=5 and -H:+DeadlockWatchdogExitOnTimeout
Error: Image build request failed with exit status 1
```

**Describe GraalVM and your environment:**
 - OS: Linux Ubuntu 20.04
 - Architecture: AMD64

What could be the cause of this error?

**Comment by warunalakshitha** [comment]
@cstancu Any update on this issue or any reason why we get this behaviour for given jar?
