### ISSUE TITLE
unexpected IllegalArgumentException "SubTree needs at least one child"

### ISSUE THREAD

**Issue by smallshen** [oracle/graal#5127]
graal version: 17(current latest, 22.2)

reproduce: 

minecraft as a dependency: https://github.com/SpongePowered/VanillaGradle or https://fabricmc.net/develop/ or forge or quiltmc

```java
net.minecraft.data.Main.main(
    arrayOf(
        "--all",
        "--output=debugFolder"
    )
);
```

tested with JetBrainsRuntime 17, it works fine. But graal throws `SubTree needs at least one child` error

stack trace
```
[04:35:49] [main/INFO]: [STDERR]: java.lang.IllegalArgumentException: SubTree needs at least one child
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.world.level.biome.Climate$RTree.buildParameterSpace(Climate.java:250)
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.world.level.biome.Climate$RTree$SubTree.<init>(Climate.java:112)
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.world.level.biome.Climate$RTree.build(Climate.java:200)
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.world.level.biome.Climate$RTree.lambda$build$2(Climate.java:200)
[04:35:49] [main/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[04:35:49] [main/INFO]: [STDERR]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[04:35:49] [main/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[04:35:49] [main/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[04:35:49] [main/INFO]: [STDERR]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[04:35:49] [main/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[04:35:49] [main/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.world.level.biome.Climate$RTree.build(Climate.java:200)
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.world.level.biome.Climate$RTree.lambda$build$2(Climate.java:200)
[04:35:49] [main/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[04:35:49] [main/INFO]: [STDERR]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[04:35:49] [main/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[04:35:49] [main/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[04:35:49] [main/INFO]: [STDERR]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[04:35:49] [main/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[04:35:49] [main/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.world.level.biome.Climate$RTree.build(Climate.java:200)
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.world.level.biome.Climate$RTree.create(Climate.java:152)
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.world.level.biome.Climate$ParameterList.<init>(Climate.java:279)
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.world.level.biome.MultiNoiseBiomeSource$Preset.lambda$static$2(MultiNoiseBiomeSource.java:112)
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.world.level.biome.MultiNoiseBiomeSource$Preset.biomeSource(MultiNoiseBiomeSource.java:130)
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.world.level.biome.MultiNoiseBiomeSource$PresetInstance.biomeSource(MultiNoiseBiomeSource.java:92)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.world.level.biome.MultiNoiseBiomeSource.lambda$static$3(MultiNoiseBiomeSource.java:42)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.datafixers.util.Either$Left.mapBoth(Either.java:33)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.DataResult.map(DataResult.java:110)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.MapDecoder$4.decode(MapDecoder.java:94)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.MapCodec$1.decode(MapCodec.java:34)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$decode$1(KeyDispatchCodec.java:67)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$decode$2(KeyDispatchCodec.java:58)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.codecs.KeyDispatchCodec.decode(KeyDispatchCodec.java:56)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.Decoder.parse(Decoder.java:18)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.codecs.FieldDecoder.decode(FieldDecoder.java:29)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.MapCodec$1.decode(MapCodec.java:34)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$7.decode(RecordCodecBuilder.java:408)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$decode$1(KeyDispatchCodec.java:67)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$decode$2(KeyDispatchCodec.java:58)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.codecs.KeyDispatchCodec.decode(KeyDispatchCodec.java:56)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.Decoder.parse(Decoder.java:18)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.codecs.FieldDecoder.decode(FieldDecoder.java:29)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.MapCodec$1.decode(MapCodec.java:34)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$3.decode(RecordCodecBuilder.java:249)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.Decoder.parse(Decoder.java:18)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.codecs.BaseMapCodec.lambda$decode$2(BaseMapCodec.java:31)
[04:35:49] [main/INFO]: [STDERR]: 	at java.base/java.util.stream.ReduceOps$1ReducingSink.accept(ReduceOps.java:80)
[04:35:49] [main/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[04:35:49] [main/INFO]: [STDERR]: 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
[04:35:49] [main/INFO]: [STDERR]: 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
[04:35:49] [main/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[04:35:49] [main/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[04:35:49] [main/INFO]: [STDERR]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[04:35:49] [main/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[04:35:49] [main/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:667)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.codecs.BaseMapCodec.decode(BaseMapCodec.java:27)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.codecs.UnboundedMapCodec.lambda$decode$0(UnboundedMapCodec.java:38)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.codecs.UnboundedMapCodec.decode(UnboundedMapCodec.java:38)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.Decoder.parse(Decoder.java:18)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.codecs.FieldDecoder.decode(FieldDecoder.java:29)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.MapCodec$1.decode(MapCodec.java:34)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$1.decode(RecordCodecBuilder.java:183)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.Decoder$1.decode(Decoder.java:49)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.Codec$2.decode(Codec.java:71)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.Decoder.parse(Decoder.java:18)
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.resources.RegistryResourceAccess$InMemoryStorage$Entry.parse(RegistryResourceAccess.java:113)
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.resources.RegistryLoader.overrideElementFromResources(RegistryLoader.java:69)
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.resources.RegistryLoader.lambda$overrideRegistryFromResources$1(RegistryLoader.java:36)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[04:35:49] [main/INFO]: [STDERR]: 	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.resources.RegistryLoader.overrideRegistryFromResources(RegistryLoader.java:36)
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.resources.RegistryLoader$Bound.overrideRegistryFromResources(RegistryLoader.java:94)
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.core.RegistryAccess.readRegistry(RegistryAccess.java:297)
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.core.RegistryAccess.load(RegistryAccess.java:292)
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.resources.RegistryOps.createAndLoad(RegistryOps.java:32)
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.core.RegistryAccess.builtinCopy(RegistryAccess.java:269)
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.core.RegistryAccess.lambda$static$12(RegistryAccess.java:287)
[04:35:49] [main/INFO]: [STDERR]: 	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.data.info.BiomeParametersDumpReport.run(BiomeParametersDumpReport.java:34)
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.data.DataGenerator.run(DataGenerator.java:62)
[04:35:49] [main/INFO]: [STDERR]: 	at net.minecraft.data.Main.main(Main.java:72)
```

**Comment by davleopo** [comment]
@smallshen  thanks for the report, this issue duplicates https://github.com/oracle/graal/issues/4776 . We already fixed it on master and the fix will be in the next 22.3 release.
