### ISSUE TITLE
 java.lang.ClassNotFoundException: com.oracle.truffle.js.builtins.MapPrototype@uiltins$MapPrototype

### ISSUE THREAD

**Issue by AnilKumarBilla** [oracle/graal#5137]
While running the feature file, the following error is occured.

java.lang.NoClassDefFoundError: com/oracle/truffle/js/builtins/MapPrototype@uiltins$MapPrototype
src/test/java/Cirium_Features/getUserbyParam.feature:3
<<<
Exception in thread "main" org.graalvm.polyglot.PolyglotException: java.lang.NoClassDefFoundError: com/oracle/truffle/js/builtins/MapPrototype@uiltins$MapPrototype
	at com.oracle.truffle.js.runtime.builtins.JSMap.createPrototype(JSMap.java:129)
	at com.oracle.truffle.js.runtime.builtins.JSConstructorFactory$Default.createConstructorAndPrototype(JSConstructorFactory.java:68)
	at com.oracle.truffle.js.runtime.builtins.JSMap.createConstructor(JSMap.java:145)
	at com.oracle.truffle.js.runtime.JSRealm.<init>(JSRealm.java:523)
	at com.oracle.truffle.js.runtime.JSContext.createRealm(JSContext.java:664)
	at com.oracle.truffle.js.lang.JavaScriptLanguage.createContext(JavaScriptLanguage.java:307)
	at com.oracle.truffle.js.lang.JavaScriptLanguage.createContext(JavaScriptLanguage.java:115)
	at com.oracle.truffle.api.LanguageAccessor$LanguageImpl.createEnvContext(LanguageAccessor.java:282)
	at com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureCreated(PolyglotLanguageContext.java:541)
	at com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureCreated(PolyglotLanguageContext.java:485)
	at com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureInitialized(PolyglotLanguageContext.java:627)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.getBindings(PolyglotContextImpl.java:1104)
	at com.oracle.truffle.polyglot.PolyglotContextDispatch.getBindings(PolyglotContextDispatch.java:97)
	at org.graalvm.polyglot.Context.getBindings(Context.java:536)
	at com.intuit.karate.graal.JsEngine.<init>(JsEngine.java:109)
	at com.intuit.karate.graal.JsEngine.<init>(JsEngine.java:46)
	at com.intuit.karate.graal.JsEngine$1.initialValue(JsEngine.java:62)
	at com.intuit.karate.graal.JsEngine$1.initialValue(JsEngine.java:59)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at com.intuit.karate.graal.JsEngine.local(JsEngine.java:98)
	at com.intuit.karate.report.Report$Builder.build(Report.java:122)
	at com.intuit.karate.report.SuiteReports.timelineReport(SuiteReports.java:62)
	at com.intuit.karate.Results.<init>(Results.java:97)
	at com.intuit.karate.Results.of(Results.java:57)
	at com.intuit.karate.Suite.buildResults(Suite.java:373)
	at com.intuit.karate.Runner$Builder.parallel(Runner.java:576)
	at com.intuit.karate.cli.IdeMain.main(IdeMain.java:60)
	at cucumber.api.cli.Main.main(Main.java:34)
Caused by: java.lang.ClassNotFoundException: com.oracle.truffle.js.builtins.MapPrototype@uiltins$MapPrototype
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 29 more

**pom.xml file:**

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.anil.karate</groupId>
	<artifactId>KaratePractice</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>KaratePractice</name>
	<url>http://maven.apache.org</url>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<mavan.compiler.source>1.8</mavan.compiler.source>
		<mavan.compiler.target>1.8</mavan.compiler.target>
	</properties>

	<dependencies>
		<dependency>
    		<groupId>com.intuit.karate</groupId>
    		<artifactId>karate-core</artifactId>
    		<version>1.2.0</version>
		</dependency>
		<dependency>
    		<groupId>com.intuit.karate</groupId>
    		<artifactId>karate-apache</artifactId>
   			<version>0.9.6</version>
    		<scope>test</scope>
		</dependency>
		<dependency>
    		<groupId>com.intuit.karate</groupId>
   			 <artifactId>karate-junit4</artifactId>
   			 <version>1.2.0</version>
    		<scope>test</scope>
		</dependency>
		<dependency>
    		<groupId>com.intuit.karate</groupId>
   			 <artifactId>karate-junit5</artifactId>
   			 <version>1.2.0</version>
    		<scope>test</scope>
		</dependency>
		<dependency>
    	<groupId>org.junit.jupiter</groupId>
    	<artifactId>junit-jupiter-api</artifactId>
    	<version>5.9.0</version>
   		<scope>test</scope>
		</dependency>
		<dependency>
    	<groupId>org.junit.jupiter</groupId>
   		 <artifactId>junit-jupiter-engine</artifactId>
    	<version>5.9.0</version>
    	<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-jdbc</artifactId>
			<version>5.1.9.RELEASE</version>
		</dependency>
		<dependency>
    		<groupId>mysql</groupId>
    		<artifactId>mysql-connector-java</artifactId>
   			 <version>8.0.29</version>
		</dependency>
		<dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
            <version>9.4.1.jre8</version>
        </dependency>
        <dependency>
    		<groupId>net.masterthought</groupId>
    		<artifactId>cucumber-reporting</artifactId>
   			<version>5.7.2</version>
			</dependency>
	</dependencies>
</project>

**Comment by woess** [comment]
Could you please provide complete files and steps to reproduce the error?
