### ISSUE TITLE
Unimplemented exception on javax.crypto.Mac.getInstance("HmacSHA256")

### ISSUE THREAD

**Issue by vhiairrassary** [oracle/graal#516]
After having generated a native image (using `native-image` from 1.0.0-rc3) of the following code, an exception is thrown at runtime:
```scala
import javax.crypto.Mac

object Main {
  def main(args: Array[String]): Unit = {
    Mac.getInstance("HmacSHA256")
  }
}
```

Stack trace:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.lang.Throwable.<init>(Throwable.java:310)
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:89)
	at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)
	at com.oracle.svm.reflect.proxies.Proxy_407_Main_main.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:173)
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: unimplemented
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Error.<init>(Error.java:70)
	at com.oracle.svm.core.jdk.UnsupportedFeatureError.<init>(UnsupportedFeatureError.java:31)
	at com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.unsupportedFeature(VMErrorSubstitutions.java:100)
	at com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.unimplemented(VMErrorSubstitutions.java:94)
	at com.oracle.svm.core.jdk.Target_javax_crypto_JceSecurity.getVerificationResult(SecuritySubstitutions.java:380)
	at javax.crypto.JceSecurity.canUseProvider(JceSecurity.java:204)
	at javax.crypto.Mac.getInstance(Mac.java:176)
	at Main$.main(Main.scala:5)
	at Main.main(Main.scala)
	... 3 more
```

Do you plan to support it in the future? Currently it is a blocker for some well known projects like AWS SDK v2.

**Comment by cstancu** [comment]
@vhiairrassary thank you for reporting. We currently don't support the JDK security packages but will implement them in the near future.

**Comment by cstancu** [comment]
This should be fixed in https://github.com/oracle/graal/commit/76d043560571c3f6c4c0d76f89cb876451062251 which adds support for HTTPS and JCA security services. These features will be available in the rc7 realease. See [JCA-SECURITY-SERVICES.md](https://github.com/oracle/graal/blob/master/substratevm/JCA-SECURITY-SERVICES.md) for details. You need to run `native-image` with `--enable-all-security-services` for `Mac` services to be available.
