### ISSUE TITLE
[native-image]: immediately fails

### ISSUE THREAD

**Issue by sickert** [oracle/graal#524]
I successfully compiled SubstrateVM from master (f731a8c), but `native-image --version` as well as all other commands immediately fail with the following stack-trace:

```
Exception in thread "main" com.oracle.svm.core.util.VMError$HostedError: Option name "GraphCompressionThreshold" has multiple definitions: org.graalvm.compiler.graph.Graph$Options.GraphCompressionThreshold and org.graalvm.compiler.graph.Graph$Options.GraphCompressionThreshold
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:66)
	at com.oracle.svm.hosted.option.HostedOptionParser.collectOptions(HostedOptionParser.java:88)
	at com.oracle.svm.driver.APIOptionHandler.extractOptions(APIOptionHandler.java:90)
	at com.oracle.svm.driver.APIOptionHandler.<init>(APIOptionHandler.java:83)
	at com.oracle.svm.driver.NativeImage.<init>(NativeImage.java:451)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:809)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:792)
```

The issue should be reproducible with the following steps:

```
# Get JDK 8 (patched)

wget https://github.com/graalvm/openjdk8-jvmci-builder/releases/download/jvmci-0.46/openjdk-8u172-jvmci-0.46-linux-amd64.tar.gz
shasum -a 256 openjdk-8u172-jvmci-0.46-linux-amd64.tar.gz
tar -xvzf openjdk-8u172-jvmci-0.46-linux-amd64.tar.gz
export EXTRA_JAVA_HOMES="/openjdk1.8.0_172-jvmci-0.46/"
${EXTRA_JAVA_HOMES}/bin/java -version

# Get JDK 11 (early access)

wget https://download.java.net/java/early_access/jdk11/21/GPL/openjdk-11-ea+21_linux-x64_bin.tar.gz
shasum -a 256 openjdk-11-ea+21_linux-x64_bin.tar.gz
tar -xvzf openjdk-11-ea+21_linux-x64_bin.tar.gz 
export JAVA_HOME="/jdk-11/"
${JAVA_HOME}/bin/java -version

# Fix lookup

export PATH=$JAVA_HOME/bin:$PATH

# Get MX

git clone https://github.com/graalvm/mx.git
export PATH=$PWD/mx:$PATH
mx --version

# Get Graal 

git clone https://github.com/oracle/graal.git

# Build and test SubstrateVM

cd graal/substratevm
mx build
mx native-image --version
```

**Comment by olpaw** [comment]
BTW,, if you just want to use SubstrateVM you don't need to define EXTRA_JAVA_HOMES.

**Comment by sickert** [comment]
Yes, this immediately resolves the problem.
Thank you for the fast answer.
