### ISSUE TITLE
Hosted Inlining and later Graal inlining do not inline Math.multiplyExact

### ISSUE THREAD

**Issue by smarr** [oracle/graal#5242]
On the latest Graal, `Math.multiplyExact()` is not inlined during native image compilation.

To me, it looks like `multiplyExact` was just missed when listing safe methods.
Or there might be some other strange interaction.

Either way, the hosted inlining logging gives:

```
CUTOFF   java.lang.Math.multiplyExact(long, long) [inlined    -, explored    -, monomorphic false, deopt false, inInterpreter false, propDeopt false, invoke  true, cost    -, subTreeCost    -, treeInvokes    -,   │  incomplete false, reason SVM detected not runtime compiled]
```

And the compilation graphs retain a full `Invoke#Direct#Math.multiplyExact`, as can be seen in the attached graph. [LocalVariableReadSquareWriteNode.bgv.zip](https://github.com/oracle/graal/files/9812479/LocalVariableReadSquareWriteNode.bgv.zip)

Issue found by @OctaveLarose. Probably for @chumer.

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this issue. is it possible to provide a reproducer to use for debugging?

**Comment by gergo-** [comment]
We should never even see a call to `Math.multiplyExact`, it should be replaced by an appropriate flavor of `IntegerMultiplyExact*Node`. I suspect that eliminating the check at https://github.com/oracle/graal/blob/0728038bd1febb9e26466637cad730b1f374b8f7/compiler/src/org.graalvm.compiler.replacements/src/org/graalvm/compiler/replacements/StandardGraphBuilderPlugins.java#L913 is all that it would take to fix this. The actual `createIntegerExact*Operation` methods know how to create the correct nodes with explicit exceptions. (This was not the case at the time the check was added.)

@smarr you could try to remove the `allowDeoptimization` check and see if everything just works.

**Comment by smarr** [comment]
@gergo- hm, doesn't look promising. I removed the check, and let TruffleSOM's CI run:


```
Fatal error: org.graalvm.compiler.debug.GraalError: com.oracle.svm.core.util.VMError$HostedError: No ForeignCallDescriptor for ByteCodeExceptionKind LONG_EXACT_OVERFLOW
	at method: LocalDate java.time.LocalDate.plusDays(long)  [Direct call from LocalDateTime LocalDateTime.plusWithOverflow(LocalDate, long, long, long, long, int)]
	at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:1169)
	at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:1098)
	at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:283)
	at com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: com.oracle.svm.core.util.VMError$HostedError: No ForeignCallDescriptor for ByteCodeExceptionKind LONG_EXACT_OVERFLOW
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
	at com.oracle.svm.core.util.VMError.guarantee(VMError.java:89)
	at com.oracle.svm.core.graal.snippets.NonSnippetLowerings.lookupBytecodeException(NonSnippetLowerings.java:206)
	at com.oracle.svm.core.graal.snippets.NonSnippetLowerings$ThrowBytecodeExceptionLowering.lower(NonSnippetLowerings.java:241)
	at com.oracle.svm.core.graal.snippets.NonSnippetLowerings$ThrowBytecodeExceptionLowering.lower(NonSnippetLowerings.java:232)
	at com.oracle.svm.core.graal.amd64.SubstrateAMD64LoweringProvider.lower(SubstrateAMD64LoweringProvider.java:60)
	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.spi.Lowerable.lower(Lowerable.java:40)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.process(LoweringPhase.java:603)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase$ProcessFrame.preprocess(LoweringPhase.java:534)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.processBlock(LoweringPhase.java:702)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.lower(LoweringPhase.java:278)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:256)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:108)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:445)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:334)
```

Full stack traces: https://github.com/SOM-st/TruffleSOM/actions/runs/3324274144/jobs/5495638397#step:3:1023

So, we end up here:
https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/graal/snippets/NonSnippetLowerings.java#L206

**Comment by gergo-** [comment]
Thanks for giving this a try. A few more bits and pieces of support will be needed, but it shouldn't be hard to do. Tracking internally as GR-42080.

**Comment by gergo-** [comment]
The proposed fix https://github.com/oracle/graal/pull/5361 is in the merge queue.

**Comment by gergo-** [comment]
The fix is merged. Please let me know if anything behaves in an unexpected way.

**Comment by smarr** [comment]
I can confirm it works for `multiplyExact`. Thank you!
