### ISSUE TITLE
VMError$HostedErro- NativeImageGeneratorRunner must not contain ".". 

### ISSUE THREAD

**Issue by cforce** [oracle/graal#5255]
- Windows Version	10.0.19044 Build 19044
- graalvm-ce-java17-22.2.0
- Microsoft Visual Studio\2022
- x64
- Java 17

Setup:
$choco install visualstudio2022buildtools
$choco install windows-sdk-10
$choco install visualstudio2022-workload-vctools
$choco install graalvm
$gu install native-image
  

```
C:\WINDOWS\system32>"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.3.6
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Windows\System32>cd \temp
C:\temp>notepad HelloWorld.java
C:\temp>javac HelloWorld.java
C:\temp>java HelloWorld
Hello, GraalVM Native Image!
C:\temp>native-image HelloWorld
Fatal error: com.oracle.svm.core.util.VMError$HostedError: The classpath of com.oracle.svm.hosted.NativeImageGeneratorRunner must not contain ".". This can happen implicitly if the builder runs exclusively on the --module-path but specifies the com.oracle.svm.hosted.NativeImageGeneratorRunner main class without --module.
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageClassLoaderSupport.<init>(NativeImageClassLoaderSupport.java:130)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.installNativeImageClassLoader(NativeImageGeneratorRunner.java:180)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:123)
Error: Image build request failed with exit status 1
```

Or more complex via Intellij/spring boot/maven
mvn package -Pnative
```
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.3.6
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
....

[INFO] --- native-maven-plugin:0.9.15:compile-no-fork (build-native) @ cloud-function-aws ---
[INFO] Executing: C:\Program Files\GraalVM\graalvm-ce-java17-22.2.0\bin\native-image.cmd -cp C:\Users\user\git\spring-native\samples\cloud-function-aws\target\cloud-function-aws-0_0_1-SNAPSHOT-shaded.jar --no-fallback -H:Path=C:\Users\user\git\spring-native\samples\cloud-function-aws\target -H:Name=cloud-function-aws
Fatal error: com.oracle.svm.core.util.VMError$HostedError: The classpath of com.oracle.svm.hosted.NativeImageGeneratorRunner must not contain ".". This can happen implicitly if the builder runs exclusively on the --module-path but specifies the com.oracle.svm.hosted.NativeImageGeneratorRunner main class without --module.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageClassLoaderSupport.<init>(NativeImageClassLoaderSupport.java:130)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.installNativeImageClassLoader(NativeImageGeneratorRunner.java:180)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:123)
Error: Image build request failed with exit status 1
```

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, could you please share a reproducer example to use?

**Comment by ynhj123** [comment]
Same question
![image](https://user-images.githubusercontent.com/26181404/199490973-69b3ab69-0830-4538-bdfe-fa9896f1bb83.png)

**Comment by ynhj123** [comment]
> Hi, Thank you for reporting this, We will take a look into it and get back to you
Check your JAVAHOME and CLASSPATH

**Comment by ynhj123** [comment]
Check the JAVAHOME and CLASSPATH. I fixed the problem by modifying the CLASSPATH

**Comment by cforce** [comment]
@ynhj123  What exactly did you do?

**Comment by ynhj123** [comment]
@cforce 
old: CLASSPATH = .;%JAVA_HOME%\lib\dt.jar;%JAVA_HOME%\lib\tools.jar;
new:  CLASSPATH = %JAVA_HOME%\lib\dt.jar;%JAVA_HOME%\lib\tools.jar;

**Comment by cforce** [comment]
Well, i checked my classpath and i don't have the extra ";" on mine. Even if i would that is ackward and does not fit to the error message as well-

**Comment by ynhj123** [comment]
@cforce You may not have noticed the "." in front of the ";"

**Comment by cforce** [comment]
Well, none of them seems to be there, but anyway its hard to take control of the classpath, a in my IntelliJ (any any other IDE as well) those cp is created automatically based on project settings like maven dependency and other project settings out of the box

**Comment by oubidar-Abderrahim** [comment]
If this issue is still occurring with our latest versions of GraalVM, please report it on a new ticket. Thank you
