### ISSUE TITLE
Cannot access class from unnamed module - java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by m0ver** [oracle/graal#5265]
**Describe the issue**
Fatal error: java.lang.IllegalAccessError: class com.oracle.svm.core.genscavenge.graal.HeapFeature (in unnamed module @0x47b5ef58) cannot access class com.oracle.svm.core.SubstrateOptions (in module org.graalvm.nativeimage.builder) because module org.graalvm.nativeimage.builder does not export com.oracle.svm.core to unnamed module @0x47b5ef58

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. ** mvn -Pnative package**

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06, mixed mode, sharing)**
 - JDK major version: **17**
 - OS: **macOS High Sierra**
 - Architecture: **AMD64**

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

```
[1/7] Initializing...
                                                                                    (0.0s @ 0.16GB)
Fatal error: java.lang.IllegalAccessError: class com.oracle.svm.core.genscavenge.graal.HeapFeature (in unnamed module @0x7dfa1bd9) cannot access class com.oracle.svm.core.SubstrateOptions (in module org.graalvm.nativeimage.builder) because module org.graalvm.nativeimage.builder does not export com.oracle.svm.core to unnamed module @0x7dfa1bd9
        at com.oracle.svm.core.genscavenge.graal.HeapFeature.isInConfiguration(HeapFeature.java:65)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.registerFeature(FeatureHandler.java:183)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.registerFeatures(FeatureHandler.java:128)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:838)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:561)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
------------------------------------------------------------------------------------------------------------------------
                        1.6s (10.1% of total time) in 11 GCs | Peak RSS: 0.87GB | CPU load: 2.40
========================================================================================================================
Failed generating 'dispatcher-native' after 13.3s.
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1716)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1413)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1374)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1361)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:03 min
[INFO] Finished at: 2022-10-21T02:02:04+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.16:build (build-native) on project 
```

**Comment by oubidar-Abderrahim** [comment]
Hi, please add this flag to the native-image build command: `--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core=ALL-UNNAMED`

**Comment by oubidar-Abderrahim** [comment]
Hi, Any updates?

**Comment by m0ver** [comment]
Thanks for your support! It's still not working for me: 

+ /Library/Java/JavaVirtualMachines/graalvm-ce-java11-22.3.0/Contents/Home/bin/native-image --no-fallback --initialize-at-run-time=io.netty.handler.ssl.BouncyCastleAlpnSslUtils --initialize-at-run-time=io.netty.util.AbstractReferenceCounted --initialize-at-run-time=io.netty.channel.epoll.Epoll,io.netty.channel.epoll.EpollEventLoop,io.netty.channel.epoll.Native,io.netty.channel.epoll.EpollEventArray,io.netty.channel.DefaultFileRegion,io.netty.channel.unix.Errors --initialize-at-build-time=org.slf4j.MDC --initialize-at-build-time=ch.qos.logback.classic.Level --initialize-at-build-time=ch.qos.logback.classic.Logger --initialize-at-build-time=ch.qos.logback.core.util.StatusPrinter --initialize-at-build-time=ch.qos.logback.core.status.StatusBase --initialize-at-build-time=ch.qos.logback.core.status.InfoStatus --initialize-at-build-time=ch.qos.logback.core.spi.AppenderAttachableImpl --initialize-at-build-time=org.slf4j.LoggerFactory --initialize-at-build-time=ch.qos.logback.core.util.Loader --initialize-at-build-time=org.slf4j.impl.StaticLoggerBinder --initialize-at-build-time=ch.qos.logback.classic.spi.ThrowableProxy --initialize-at-build-time=ch.qos.logback.core.CoreConstants --report-unsupported-elements-at-runtime --add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core=ALL-UNNAMED -cp ./target/tinystruct-0.7.4-jar-with-dependencies.jar -H:Name=dispatcher-native -H:Class=org.tinystruct.system.Dispatcher -H:+ReportExceptionStackTraces --add-opens java.base/jdk.internal.misc=ALL-UNNAMED -Dio.netty.tryReflectionSetAccessible=true -H:+ReportUnsupportedElementsAtRuntime
========================================================================================================================
GraalVM Native Image: Generating 'dispatcher-native' (executable)...
========================================================================================================================
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
Warning: Could not register io.netty.handler.codec.marshalling.MarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.netty.handler.codec.marshalling.MarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
Warning: Could not register io.netty.handler.codec.marshalling.MarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.netty.handler.codec.marshalling.MarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
[1/7] Initializing...                                                                                   (21.9s @ 0.45GB)
 Version info: 'GraalVM 22.3.0 Java 11 CE'
 Java version info: '11.0.17+8-jvmci-22.3-b08'
 C compiler: cc (apple, x86_64, 10.0.0)
 Garbage collector: Serial GC
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/Volumes/Untitled/development/tinystruct/target/tinystruct-0.7.4-jar-with-dependencies.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[2/7] Performing analysis...  [**]                                                                     (123.8s @ 1.74GB)
   9,190 (86.51%) of 10,623 classes reachable
  19,235 (65.11%) of 29,543 fields reachable
  48,272 (57.22%) of 84,357 methods reachable
     346 classes,   659 fields, and 3,853 methods registered for reflection
       1 native library: -framework CoreServices

Fatal error: org.graalvm.compiler.debug.GraalError: com.oracle.svm.util.ReflectionUtil$ReflectionUtilError: java.lang.NoSuchMethodException: jdk.internal.misc.Unsafe.putReference(java.lang.Object, long, java.lang.Object)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.setException(AnalysisFuture.java:49)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:269)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:63)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisElement.lambda$execute$2(AnalysisElement.java:170)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool.awaitQuiescence(ForkJoinPool.java:2984)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.complete(CompletionExecutor.java:243)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis.doTypeflow(PointsToAnalysis.java:541)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis.finish(PointsToAnalysis.java:529)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.AbstractAnalysisEngine.runAnalysis(AbstractAnalysisEngine.java:143)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:745)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
Caused by: com.oracle.svm.util.ReflectionUtil$ReflectionUtilError: java.lang.NoSuchMethodException: jdk.internal.misc.Unsafe.putReference(java.lang.Object, long, java.lang.Object)
        at org.graalvm.nativeimage.base/com.oracle.svm.util.ReflectionUtil.lookupMethod(ReflectionUtil.java:82)
        at org.graalvm.nativeimage.base/com.oracle.svm.util.ReflectionUtil.lookupMethod(ReflectionUtil.java:69)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.methodhandles.MethodHandleFeature.registerUnsafePutReference(MethodHandleFeature.java:271)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisElement$ElementNotification.lambda$notifyCallback$0(AnalysisElement.java:102)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        ... 17 more
Caused by: java.lang.NoSuchMethodException: jdk.internal.misc.Unsafe.putReference(java.lang.Object, long, java.lang.Object)
        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2475)
        at org.graalvm.nativeimage.base/com.oracle.svm.util.ReflectionUtil.lookupMethod(ReflectionUtil.java:74)
        ... 21 more
------------------------------------------------------------------------------------------------------------------------
                        9.8s (6.6% of total time) in 23 GCs | Peak RSS: 3.16GB | CPU load: 2.99
========================================================================================================================
Failed generating 'dispatcher-native' after 2m 26s.
Error: Image build request failed with exit status 1

**Comment by oubidar-Abderrahim** [comment]
The stack trace is different, which means the original issue was resolved.

For the command you're using, it should be `--add-opens=java.base/jdk.internal.misc=ALL-UNNAMED` not `--add-opens java.base/jdk.internal.misc=ALL-UNNAMED` please try it and let us know if the issue persists.

**Comment by m0ver** [comment]
Thanks a lot! 

The issue still persists here.
>....                                                                                                                      
                        --initialize-at-build-time=ch.qos.logback.core.CoreConstants \             
                        --report-unsupported-elements-at-runtime \                                 
                        --add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core=ALL-UNNAMED \
                        --add-opens=java.base/jdk.internal.misc=ALL-UNNAMED \                          
-cp ./target/tinystruct-0.7.5-jar-with-dependencies.jar \                                              
-H:Name=dispatcher-native \
-H:Class=org.tinystruct.system.Dispatcher \
-H:+ReportExceptionStackTraces \
-Dio.netty.tryReflectionSetAccessible=true \
-H:+ReportUnsupportedElementsAtRuntime
========================================================================================================================
GraalVM Native Image: Generating 'dispatcher-native' (executable)...
========================================================================================================================
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
Warning: Could not register io.netty.handler.codec.marshalling.MarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.netty.handler.codec.marshalling.MarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.netty.handler.codec.marshalling.CompatibleMarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
Warning: Could not register io.netty.handler.codec.marshalling.MarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.netty.handler.codec.marshalling.MarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
[1/7] Initializing...                                                                                   (30.0s @ 0.44GB)
 Version info: 'GraalVM 22.3.0 Java 11 CE'
 Java version info: '11.0.17+8-jvmci-22.3-b08'
 C compiler: cc (apple, x86_64, 10.0.0)
 Garbage collector: Serial GC
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/Volumes/Untitled/development/tinystruct/target/tinystruct-0.7.5-jar-with-dependencies.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[2/7] Performing analysis...  [**]                                                                     (122.1s @ 0.81GB)
   8,454 (85.48%) of  9,890 classes reachable
  17,614 (64.29%) of 27,396 fields reachable
  44,723 (55.07%) of 81,205 methods reachable
     346 classes,   659 fields, and 3,853 methods registered for reflection
       1 native library: -framework CoreServices

Fatal error: org.graalvm.compiler.debug.GraalError: com.oracle.svm.util.ReflectionUtil$ReflectionUtilError: java.lang.NoSuchMethodException: jdk.internal.misc.Unsafe.putReference(java.lang.Object, long, java.lang.Object)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.setException(AnalysisFuture.java:49)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:269)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:63)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisElement.lambda$execute$2(AnalysisElement.java:170)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.oracle.svm.util.ReflectionUtil$ReflectionUtilError: java.lang.NoSuchMethodException: jdk.internal.misc.Unsafe.putReference(java.lang.Object, long, java.lang.Object)
        at org.graalvm.nativeimage.base/com.oracle.svm.util.ReflectionUtil.lookupMethod(ReflectionUtil.java:82)
        at org.graalvm.nativeimage.base/com.oracle.svm.util.ReflectionUtil.lookupMethod(ReflectionUtil.java:69)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.methodhandles.MethodHandleFeature.registerUnsafePutReference(MethodHandleFeature.java:271)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisElement$ElementNotification.lambda$notifyCallback$0(AnalysisElement.java:102)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        ... 10 more
Caused by: java.lang.NoSuchMethodException: jdk.internal.misc.Unsafe.putReference(java.lang.Object, long, java.lang.Object)
        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2475)
        at org.graalvm.nativeimage.base/com.oracle.svm.util.ReflectionUtil.lookupMethod(ReflectionUtil.java:74)
        ... 14 more
------------------------------------------------------------------------------------------------------------------------
                        11.0s (6.8% of total time) in 25 GCs | Peak RSS: 3.14GB | CPU load: 2.66

**Comment by oubidar-Abderrahim** [comment]
Can you share the code in a GitHub repository?

**Comment by m0ver** [comment]
Yes. Here is the repository: https://github.com/tinystruct/tinystruct
You can execute the build.sh.

**Comment by oubidar-Abderrahim** [comment]
Unfortunately, I couldn't build the project. I got the following error 
```
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar (243 kB at 260 kB/s)
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
```

**Comment by m0ver** [comment]
Ok, I believe you can build it successfully after comment the code snippet in `pom.xml` under the project. Thanks a lot!

```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>1.6</version>
                <executions>
                    <execution>
                        <id>sign-artifacts</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>sign</goal>
                        </goals>
                        <configuration>
                            <gpgArguments>
                                <arg>--pinentry-mode</arg>
                                <arg>loopback</arg>
                            </gpgArguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by oubidar-Abderrahim** [comment]
Please always use the tracing agent to generate Metatdata before trying to create a native-image. you can find more here: https://www.graalvm.org/22.3/reference-manual/native-image/metadata/AutomaticMetadataCollection/

**Comment by BoykoAlex** [comment]
I similar error for `jdk.compiler/com.sun.tools.javac.file` to unnamed module.
```
Fatal error: org.graalvm.compiler.debug.GraalError: java.lang.IllegalAccessError: superclass access check failed: class org.openrewrite.java.isolated.ReloadableJava17Parser$ByteArrayCapableJavacFileManager (in unnamed module @0x56380231) cannot access class com.sun.tools.javac.file.JavacFileManager (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.file to unnamed module @0x56380231
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.setException(AnalysisFuture.java:49)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:63)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisElement.lambda$execute$2(AnalysisElement.java:170)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.IllegalAccessError: superclass access check failed: class org.openrewrite.java.isolated.ReloadableJava17Parser$ByteArrayCapableJavacFileManager (in unnamed module @0x56380231) cannot access class com.sun.tools.javac.file.JavacFileManager (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.file to unnamed module @0x56380231
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3297)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2371)
	at org.springframework.aot.nativex.feature.PreComputeFieldFeature.iterateFields(PreComputeFieldFeature.java:55)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisElement$SubtypeReachableNotification.lambda$notifyCallback$0(AnalysisElement.java:129)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 10 more
```

I did add --add-exports to the config in the maven:

```
			<plugin>
				<groupId>org.graalvm.buildtools</groupId>
				<artifactId>native-maven-plugin</artifactId>
				<configuration>
					<buildArg>--add-opens=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED</buildArg>
				</configuration>
			</plugin>
```

Any idea what is wrong? Or is this a bug?

**Comment by Jonathan-Zollinger** [comment]
@BoykoAlex are you using the tracing agent to produce the metadata like said in the prior comment? https://github.com/oracle/graal/issues/5265#issuecomment-1354952336

fwiw, you can add a call to the trace agent to run with your tests in your maven file
```xml
<plugin>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>3.0.0-M7</version>
    <configuration>
        <argLine>
            -agentlib:native-image-agent=config-output-dir=target/${trace-agent.output-directory}
        </argLine>
    </configuration>
</plugin>
```

**Comment by BoykoAlex** [comment]
@Jonathan-Zollinger yes, i ran the app with an agent to get a bunch of json files and i do include those files under `META-INF/native-image`... I'm curious what you'd expect to be added to the json files in this case... what are the possibilities you have on your mind?

**Comment by Jonathan-Zollinger** [comment]
I'm working to figure a similar problem on my own build, so take this all with a grain of salt, ya? but previously when I've run into this issue libraries like PicoCli and the JNI were throwing a wrench in things. configuring the trace agent told the Graal VM whatever it needed to build my image. I've since broken my build though! so I could be totally wrong, lol

**Comment by oubidar-Abderrahim** [comment]
Closing this issue as resolved
