### ISSUE TITLE
javascript: SyntaxError: expected arrow function parameter list

### ISSUE THREAD

**Issue by kommen** [oracle/graal#527]
With `graalvm-ee-1.0.0-rc2`, and `yarn` 1.7.0 installing https://github.com/GoogleChrome/puppeteer fails.

```
$ yarn add puppeteer
yarn add v1.7.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
error /Users/kommen/Desktop/pup/node_modules/puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/kommen/Desktop/pup/node_modules/puppeteer
Output:
/Users/kommen/Desktop/pup/node_modules/puppeteer/lib/Page.js:393
      window[bindingName] = async(...args) => {
                                  ^

SyntaxError: expected arrow function parameter list
    at createScript (vm.js:79:1)
    at Object.runInThisContext (vm.js:138:1)
    at Module._compile (module.js:616:28)
    at Object.<anonymous> (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:8:3)
    at Object.<anonymous> (/Users/kommen/Desktop/pup/node_modules/puppeteer/lib/Target.js:1:76)
```

The `yarn add` works with stock nodejs.

**Comment by iamstolis** [comment]
Thank you for the report. We will fix that. It seems that we do not parse rest parameters of async arrow functions correctly.

> I just found the https://github.com/graalvm/graaljs/issues repo, should this be rather reported there?

There is no need to move this issue there, but in general it is better to report JavaScript-specific issues there as you will most likely get faster response from JavaScript team there.

**Comment by iamstolis** [comment]
This problem should be fixed by https://github.com/graalvm/graaljs/commit/b1537a18d959b942ff8e0fd1bfdc91d7f33287cc The fix should appear in the next public `graalvm` build (1.0.0-rc4).
