### ISSUE TITLE
Cannot run wasm builded by Emscripten toolchain 

### ISSUE THREAD

**Issue by pu0238** [oracle/graal#5277]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **graalvm-ce-java17-22.2.0**
 - CE or EE: **ce**
 - JDK version: **OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06)**
 - OS and OS Version: **Windows wsl ubuntu**
 - Architecture: **amd64**
 - The output of `node --experimental-options --js.webassembly --jvm --polyglot src/swipl.js`:
```
com.oracle.truffle.api.CompilerDirectives$ShouldNotReachHere
        at org.graalvm.truffle/com.oracle.truffle.api.CompilerDirectives.shouldNotReachHere(CompilerDirectives.java:574)        at org.graalvm.truffle/com.oracle.truffle.api.CompilerDirectives.shouldNotReachHere(CompilerDirectives.java:494)        at org.graalvm.wasm.nodes.WasmFunctionNode.executeBodyFromOffset(WasmFunctionNode.java:1492)
        at org.graalvm.wasm.nodes.WasmFunctionNode.execute(WasmFunctionNode.java:418)
        at org.graalvm.wasm.nodes.WasmRootNode.executeWithContext(WasmRootNode.java:123)
        at org.graalvm.wasm.nodes.WasmRootNode.execute(WasmRootNode.java:99)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:656)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:628)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:561)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:545)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:491)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:68)
        at org.graalvm.wasm.nodes.WasmFunctionNode.executeDirectCall(WasmFunctionNode.java:1528)
        at org.graalvm.wasm.nodes.WasmFunctionNode.executeBodyFromOffset(WasmFunctionNode.java:629)
        at org.graalvm.wasm.nodes.WasmFunctionNode.execute(WasmFunctionNode.java:418)
        at org.graalvm.wasm.nodes.WasmRootNode.executeWithContext(WasmRootNode.java:123)
        at org.graalvm.wasm.nodes.WasmRootNode.execute(WasmRootNode.java:99)
```
(the result was displayed multiple times )

**Describe the issue**
I builded following repo to wasm https://github.com/SWI-Prolog/swipl-devel using this instruction: https://swi-prolog.discourse.group/t/swi-prolog-in-the-browser-using-wasm/5650. After building I got wasm files and while trying to run js file I got the above error. While trying to run the wasm file itself, I got the following error:

Command: 
```
wasm src/swipl.wasm
```
Result:
```
ERROR: The module 'a', referenced by the import 'fa' in the module 'main', does not exist.
```

I am able to run this code using vanilla dist node js (not graalvm one) and everything works fine.

I want to combine this with graalvm to use the capabilities of the Polyglot in this project.

EDIT

Simplified scenario to be recreated:

1. Init node project
2. Run "npm i swipl-wasm"
3. Create file:

index.js
```
const SWIPL = require("swipl-wasm/dist/swipl/swipl-web.js");
const path = require("path");

(async () => {
  console.log(1);
  const swipl = await SWIPL({
    arguments: ["-q"],
    locateFile: (file) => {
      //console.log(path)
      //const path = require("path");
      return path.join(
        __dirname,
        "node_modules",
        "swipl-wasm",
        "dist",
        "swipl",
        file
      );
    },
  });
  console.log(2);
  const version = swipl.prolog
  .query("current_prolog_flag(version, Version)")
  .once().Version;
  console.log(version)
})();

```
4. Run it (on vanilla node everything work on graalvm same error)

**Comment by oubidar-Abderrahim** [comment]
Hi, Can you please try with GraalVM 22.3.0?

**Comment by pu0238** [comment]
On command 
node --experimental-options --polyglot --js.webassembly --jvm swipl.js

I got:

```
[0.000s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /mnt/wsl/docker-desktop-bind-mounts/Ubuntu-20.04/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1/sys/fs/cgroup/cpuset.
[FATAL ERROR: at Fri Oct 28 21:41:55 2022
        Could not find system resources]
Aborted()
exiting due to exception: RuntimeError: Aborted(). Build with -sASSERTIONS for more info.
```

**Comment by oubidar-Abderrahim** [comment]
I cannot reproduce this using 22.3.0, This is the output I got:
```
> node --experimental-options --js.webassembly --jvm --polyglot index.js
1
2
80518
```
Could you make sure you have a clean installation of GraalVM and npm modules?

**Comment by pu0238** [comment]
My bad it work as is should for that example thanks
