### ISSUE TITLE
Native image tests fail with build time init when an enum uses a lambda

### ISSUE THREAD

**Issue by mhalbritter** [oracle/graal#5300]
I have this enum:

```java
enum EnumWithLambda {

    VALUE((s) -> false);

    EnumWithLambda(Predicate<String> predicate) {
    }

}
```

and this annotation which references the enum:

```java
@Target({ElementType.TYPE, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Inherited
public @interface EnumWithLambdaAnnotation {

    EnumWithLambda myEnum() default EnumWithLambda.VALUE;

}
```

and this this test, which is annotated with the annotation:

```java
@EnumWithLambdaAnnotation
class EnumWithLambdaTest {
    @Test
    void foo() {
        System.out.println("foo");
    }
}
```

when i run `gradle nativeTest`, this fails with:

```
Error: Classes that should be initialized at run time got initialized during image building:
 test.lambda.EnumWithLambda was unintentionally initialized at build time. To see why test.lambda.EnumWithLambda got initialized use --trace-class-initialization=test.lambda.EnumWithLambda
To see how the classes got initialized, use --trace-class-initialization=test.lambda.EnumWithLambda
```

The full trace is:

```
Error: Classes that should be initialized at run time got initialized during image building:
 test.lambda.EnumWithLambda was unintentionally initialized at build time. test.lambda.EnumWithLambda caused initialization of this class with the following trace: 
        at test.lambda.EnumWithLambda.<clinit>(EnumWithLambda.java:7)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Unknown Source)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:568)
        at java.lang.Class.getEnumConstantsShared(Class.java:3837)
        at java.lang.Class.enumConstantDirectory(Class.java:3859)
        at java.lang.Enum.valueOf(Enum.java:267)
        at sun.reflect.annotation.AnnotationParser.parseEnumValue(AnnotationParser.java:479)
        at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:344)
        at java.lang.reflect.Method.getDefaultValue(Method.java:717)
        at sun.reflect.annotation.AnnotationType.<init>(AnnotationType.java:133)
        at sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:85)
        at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:262)
        at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:121)
        at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:73)
        at java.lang.Class.createAnnotationData(Class.java:4068)
        at java.lang.Class.annotationData(Class.java:4057)
        at java.lang.Class.getDeclaredAnnotation(Class.java:3996)
        at org.junit.platform.commons.util.AnnotationUtils.findAnnotation(AnnotationUtils.java:150)
        at org.junit.platform.commons.util.AnnotationUtils.findAnnotation(AnnotationUtils.java:137)
        at org.junit.jupiter.engine.descriptor.DisplayNameUtils.determineDisplayName(DisplayNameUtils.java:73)
        at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.<init>(JupiterTestDescriptor.java:69)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.<init>(ClassBasedTestDescriptor.java:100)
        at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.<init>(ClassTestDescriptor.java:51)
        at org.junit.jupiter.engine.discovery.ClassSelectorResolver.newClassTestDescriptor(ClassSelectorResolver.java:119)
        at org.junit.jupiter.engine.discovery.ClassSelectorResolver.lambda$resolve$5(ClassSelectorResolver.java:98)
        at org.junit.jupiter.engine.discovery.ClassSelectorResolver$$Lambda$691/0x0000000100ef5908.apply(Unknown Source)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution$DefaultContext.createAndAdd(EngineDiscoveryRequestResolution.java:250)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution$DefaultContext.addToParent(EngineDiscoveryRequestResolution.java:213)
        at org.junit.jupiter.engine.discovery.ClassSelectorResolver.lambda$resolve$6(ClassSelectorResolver.java:98)
        at org.junit.jupiter.engine.discovery.ClassSelectorResolver$$Lambda$690/0x0000000100ef56c0.apply(Unknown Source)
        at java.util.Optional.map(Optional.java:260)
        at org.junit.jupiter.engine.discovery.ClassSelectorResolver.resolve(ClassSelectorResolver.java:96)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolveUniqueId$3(EngineDiscoveryRequestResolution.java:176)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution$$Lambda$676/0x0000000100ef6248.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:189)
at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveUniqueId(EngineDiscoveryRequestResolution.java:176)

        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:124)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.access$100(EngineDiscoveryRequestResolution.java:58)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution$DefaultContext.resolve(EngineDiscoveryRequestResolution.java:228)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution$DefaultContext.addToParent(EngineDiscoveryRequestResolution.java:222)
Failed generating 'junit-build-time-init-tests' after 16,9s.
        at org.junit.jupiter.engine.discovery.MethodSelectorResolver$MethodType.resolveUniqueIdIntoTestDescriptor(MethodSelectorResolver.java:224)
        at org.junit.jupiter.engine.discovery.MethodSelectorResolver$MethodType.access$200(MethodSelectorResolver.java:164)
        at org.junit.jupiter.engine.discovery.MethodSelectorResolver.lambda$resolve$4(MethodSelectorResolver.java:117)
        at org.junit.jupiter.engine.discovery.MethodSelectorResolver$$Lambda$678/0x0000000100ef66e0.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
        at org.junit.jupiter.engine.discovery.MethodSelectorResolver.resolve(MethodSelectorResolver.java:133)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolveUniqueId$3(EngineDiscoveryRequestResolution.java:176)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution$$Lambda$676/0x0000000100ef6248.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:189)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveUniqueId(EngineDiscoveryRequestResolution.java:176)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:124)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:92)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:83)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)
        at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:46)
        at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:69)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:132)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:107)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:78)
        at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:110)
        at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:78)
        at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.discover(DefaultLauncherSession.java:81)
        at org.junit.platform.launcher.core.SessionPerRequestLauncher.discover(SessionPerRequestLauncher.java:46)
        at org.graalvm.junit.platform.JUnitPlatformFeature.discoverTestsAndRegisterTestClassesForReflection(JUnitPlatformFeature.java:135)
        at org.graalvm.junit.platform.JUnitPlatformFeature.beforeAnalysis(JUnitPlatformFeature.java:94)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:736)
        at com.oracle.svm.hosted.NativeImageGenerator$$Lambda$490/0x0000000100ecfda0.accept(Unknown Source)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:85)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:736)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
```

It however works when I use this enum instead:

```java
enum EnumWithLambda {

    VALUE(new AlwaysFalse());

    EnumWithLambda(Predicate<String> predicate) {
    }

}
```

where I refactored the lambda into a class:

```java
class AlwaysFalse implements Predicate<String> {

    @Override
    public boolean test(String value) {
        return false;
    }
}
```

You can reproduce the whole thing [here](https://github.com/mhalbritter/graalvm-junit-build-time-init), just make sure comment in the

```
// @EnumWithLambdaAnnotation
```

on the `EnumWithLambdaTest` and run `gradle nativeImage`.

**Comment by sdeleuze** [comment]
@vjovanov Blocking issue for Spring Boot 3 test support. Not sure if that should be solved on GraalVM side or by stop doing build-time init on NBT.

**Comment by vjovanov** [comment]
Both: 
1) GraalVM should ignore the fact that this class is initialized ([proposal](https://github.com/graalvm/taming-build-time-initialization/blob/main/PROPOSAL_CLASS_INITIALIZATION.md)). CC @christianwimmer 

2) We should see if something is possible on the build-tools side, however, I doubt there is anything we can do. Reflectively accessing a class initializes the annotations and hence other stuff gets also initialized.

3) We can do a lightweight version of `1` which would treat all classes as `--rerun-class-initialization` by default.

**Comment by fernando-valdez** [comment]
@mhalbritter can you please confirm if this issue is present in the latest build?

**Comment by mhalbritter** [comment]
This one? https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/24.0.0-dev-20231209_0120
