### ISSUE TITLE
Native image tests fail with build time init when an enum uses another enum

### ISSUE THREAD

**Issue by mhalbritter** [oracle/graal#5301]
I have this enum:

```java
enum EnumWithEnum {

    VALUE(SomeOtherEnum.VALUE2);

    EnumWithEnum(SomeOtherEnum value2) {

    }
}
```

and this annotation which references the enum:

```java
@Target({ElementType.TYPE, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Inherited
public @interface EnumWithEnumAnnotation {

    EnumWithEnum myEnum() default EnumWithEnum.VALUE;

}
```

and this this test, which is annotated with the annotation:

```java
@EnumWithEnumAnnotation
class EnumWithEnumTest {
    @Test
    void foo() {
        System.out.println("foo");
    }
}
```

when i run `gradle nativeTest`, this fails with:

```
Error: Classes that should be initialized at run time got initialized during image building:
------------------------------------------------------------------------------------------------------------------------
 test.enumwithenum.EnumWithEnum was unintentionally initialized at build time. To see why test.enumwithenum.EnumWithEnum got initialized use --trace-class-initialization=test.enumwithenum.EnumWithEnum
To see how the classes got initialized, use --trace-class-initialization=test.enumwithenum.EnumWithEnum
```

The full trace is:

```
Error: Classes that should be initialized at run time got initialized during image building:
 test.enumwithenum.EnumWithEnum was unintentionally initialized at build time. test.enumwithenum.EnumWithEnum caused initialization of this class with the following trace: 
        at test.enumwithenum.EnumWithEnum.<clinit>(EnumWithEnum.java:5)

        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Unknown Source)
------------------------------------------------------------------------------------------------------------------------
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:568)
        at java.lang.Class.getEnumConstantsShared(Class.java:3837)
        at java.lang.Class.enumConstantDirectory(Class.java:3859)
        at java.lang.Enum.valueOf(Enum.java:267)
        at sun.reflect.annotation.AnnotationParser.parseEnumValue(AnnotationParser.java:479)
        at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:344)
        at java.lang.reflect.Method.getDefaultValue(Method.java:717)
        at sun.reflect.annotation.AnnotationType.<init>(AnnotationType.java:133)
        at sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:85)
        at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:262)
        at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:121)
        at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:73)
        at java.lang.Class.createAnnotationData(Class.java:4068)
        at java.lang.Class.annotationData(Class.java:4057)
        at java.lang.Class.getDeclaredAnnotation(Class.java:3996)
        at org.junit.platform.commons.util.AnnotationUtils.findAnnotation(AnnotationUtils.java:150)
        at org.junit.platform.commons.util.AnnotationUtils.findAnnotation(AnnotationUtils.java:137)
        at org.junit.jupiter.engine.descriptor.DisplayNameUtils.determineDisplayName(DisplayNameUtils.java:73)
        at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.<init>(JupiterTestDescriptor.java:69)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.<init>(ClassBasedTestDescriptor.java:100)
        at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.<init>(ClassTestDescriptor.java:51)
        at org.junit.jupiter.engine.discovery.ClassSelectorResolver.newClassTestDescriptor(ClassSelectorResolver.java:119)
        at org.junit.jupiter.engine.discovery.ClassSelectorResolver.lambda$resolve$5(ClassSelectorResolver.java:98)
        at org.junit.jupiter.engine.discovery.ClassSelectorResolver$$Lambda$688/0x0000000100eed000.apply(Unknown Source)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution$DefaultContext.createAndAdd(EngineDiscoveryRequestResolution.java:250)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution$DefaultContext.addToParent(EngineDiscoveryRequestResolution.java:213)
        at org.junit.jupiter.engine.discovery.ClassSelectorResolver.lambda$resolve$6(ClassSelectorResolver.java:98)
        at org.junit.jupiter.engine.discovery.ClassSelectorResolver$$Lambda$687/0x0000000100eefd60.apply(Unknown Source)
        at java.util.Optional.map(Optional.java:260)
        at org.junit.jupiter.engine.discovery.ClassSelectorResolver.resolve(ClassSelectorResolver.java:96)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolveUniqueId$3(EngineDiscoveryRequestResolution.java:176)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution$$Lambda$673/0x0000000100eeb7f8.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:189)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveUniqueId(EngineDiscoveryRequestResolution.java:176)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:124)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.access$100(EngineDiscoveryRequestResolution.java:58)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution$DefaultContext.resolve(EngineDiscoveryRequestResolution.java:228)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution$DefaultContext.addToParent(EngineDiscoveryRequestResolution.java:222)
        at org.junit.jupiter.engine.discovery.MethodSelectorResolver$MethodType.resolveUniqueIdIntoTestDescriptor(MethodSelectorResolver.java:224)
        at org.junit.jupiter.engine.discovery.MethodSelectorResolver$MethodType.access$200(MethodSelectorResolver.java:164)
        at org.junit.jupiter.engine.discovery.MethodSelectorResolver.lambda$resolve$4(MethodSelectorResolver.java:117)
        at org.junit.jupiter.engine.discovery.MethodSelectorResolver$$Lambda$675/0x0000000100eebc90.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
        at org.junit.jupiter.engine.discovery.MethodSelectorResolver.resolve(MethodSelectorResolver.java:133)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolveUniqueId$3(EngineDiscoveryRequestResolution.java:176)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution$$Lambda$673/0x0000000100eeb7f8.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:189)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveUniqueId(EngineDiscoveryRequestResolution.java:176)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:124)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:92)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:83)
        at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)
Failed generating 'junit-build-time-init-tests' after 13,9s.
        at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:46)
        at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:69)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:132)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:107)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:78)
        at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:110)
        at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:78)
        at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.discover(DefaultLauncherSession.java:81)
        at org.junit.platform.launcher.core.SessionPerRequestLauncher.discover(SessionPerRequestLauncher.java:46)
        at org.graalvm.junit.platform.JUnitPlatformFeature.discoverTestsAndRegisterTestClassesForReflection(JUnitPlatformFeature.java:135)
        at org.graalvm.junit.platform.JUnitPlatformFeature.beforeAnalysis(JUnitPlatformFeature.java:94)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:736)
        at com.oracle.svm.hosted.NativeImageGenerator$$Lambda$487/0x0000000100ecc960.accept(Unknown Source)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:85)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:736)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)

```

You can reproduce the whole thing [here](https://github.com/mhalbritter/graalvm-junit-build-time-init), just make sure comment in the

```
// @EnumWithEnumAnnotation
```

on the `EnumWithEnumTest` and run `gradle nativeTest`.

**Comment by vjovanov** [comment]
This will be fixed by the conversion to the new [initialization policy](https://github.com/graalvm/taming-build-time-initialization/blob/main/PROPOSAL_CLASS_INITIALIZATION.md).

The only way I see we can fix this until then is to treat `enum`s by default as `rerun-class-initialization`. This is a significant change though and I don't think it is worth doing it until we change the initialization strategy.

Why is this a blocker? To me it seems only in rare cases tests will fail with this exception, and this can be fixed by initailizing these enums at build time.

CC @christianwimmer

**Comment by mhalbritter** [comment]
I've worked around this issue in Spring Boot by refactoring the enum. Not pretty, but doable.
