### ISSUE TITLE
native-image throws ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by vhiairrassary** [oracle/graal#531]
I am trying to communicate between Scala & C using `org.graalvm.nativeimage.c.*`. The equivalent Java code works very well but the Scala version throws an exception while compiling the JAR to a native image (complete & **minimal** project https://github.com/vhiairrassary/graalvm_scala_bug):
```scala
import org.graalvm.nativeimage.c.function._
import org.graalvm.nativeimage.c.function.CFunction._

@CLibrary("test")
object Main {
  @CFunction(transition = Transition.NO_TRANSITION)
  @native def myFunction(): Unit

  def main(args: Array[String]): Unit = {
    myFunction()
  }
}
```

Steps to reproduce:
```
> sbt assembly
[...]

> $GRAALVM_PATH/bin/native-image -jar target/scala-2.12/test-assembly-0.1.jar
Build on Server(pid: 62697, port: 54882)*
   classlist:   4,670.28 ms
       (cap):   2,036.99 ms
       setup:   2,985.94 ms
  (typeflow):   4,187.66 ms
   (objects):   2,546.02 ms
  (features):      57.26 ms
    analysis:   6,892.17 ms
    universe:     248.71 ms
     (parse):   1,125.10 ms
    (inline):   1,447.59 ms
   (compile):     210.82 ms
     compile:   2,850.49 ms
fatal error: org.graalvm.compiler.graph.GraalGraphError: java.lang.ArrayIndexOutOfBoundsException: 0
	at node: 121|Invoke#Indirect#Main$.myFunction
	at method: int com.oracle.svm.core.JavaMainWrapper.run(int, CCharPointerPointer)  [Direct call from int CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(int, CCharPointerPointer)]
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.doBlock(NodeLIRBuilder.java:375)
	at org.graalvm.compiler.core.LIRGenerationPhase.emitBlock(LIRGenerationPhase.java:81)
	at org.graalvm.compiler.core.LIRGenerationPhase.run(LIRGenerationPhase.java:71)
	at org.graalvm.compiler.core.LIRGenerationPhase.run(LIRGenerationPhase.java:46)
	at org.graalvm.compiler.lir.phases.LIRPhase.apply(LIRPhase.java:117)
	at org.graalvm.compiler.lir.phases.LIRPhase.apply(LIRPhase.java:109)
	at org.graalvm.compiler.core.GraalCompiler.emitLIR0(GraalCompiler.java:340)
	at org.graalvm.compiler.core.GraalCompiler.emitLIR(GraalCompiler.java:304)
	at org.graalvm.compiler.core.GraalCompiler.emitBackEnd(GraalCompiler.java:284)
	at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:181)
	at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:165)
	at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:924)
	at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:881)
	at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:257)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at jdk.vm.ci.code.CallingConvention.getArgument(CallingConvention.java:85)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.visitInvokeArguments(NodeLIRBuilder.java:633)
	at com.oracle.svm.core.graal.code.amd64.SubstrateAMD64Backend$SubstrateAMD64NodeLIRBuilder.visitInvokeArguments(SubstrateAMD64Backend.java:464)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.emitInvoke(NodeLIRBuilder.java:596)
	at org.graalvm.compiler.nodes.InvokeNode.generate(InvokeNode.java:171)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.emitNode(NodeLIRBuilder.java:464)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.doRoot(NodeLIRBuilder.java:454)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.doBlock(NodeLIRBuilder.java:371)
	... 19 more
Error: Processing image build request failed
```

Note:
MacOS version of GraalVM:
```
> java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
GraalVM 1.0.0-rc3 (build 25.71-b01-internal-jvmci-0.45, mixed mode)
```

Simple Hello World code works very well:
```scala
object Main {
  def main(args: Array[String]): Unit = {
    printf("Hello")
  }
}
```

**Comment by vjovanov** [comment]
To catch the failure earlier one can run the following command: 
```

**Comment by vjovanov** [comment]
This problem is reproducible with Java as well. It happens when we put the `@CFunction` annotation on the native method instead of putting it on the static native function. In Java this can be reproduced with the following example: 
```
import org.graalvm.nativeimage.c.function.*;
import org.graalvm.nativeimage.c.function.CFunction.Transition;

public class Main {
  @CFunction(transition = Transition.NO_TRANSITION)
  native void myFunction();
  void functionCallingNative() {
    myFunction();
  }
  public static void main(String[] args) {
    new Main().functionCallingNative();
  }
}
```

**Comment by vjovanov** [comment]
The documentation of the `CFunction` says the following: 
```
Denotes a {@code static native} method that calls directly from Java to C, without following the JNI protocol.
```
But the `native-image` does not catch this problem early with a proper error message. 

The issue here is that Scala does not really have static methods; in order to support Scala we would have to change how we deal with this annotation, or we need to introduce a new mechanism for Scala.

One thing is for sure, we need a proper error message when we have `@CFunction` on a method that should not be annotated.

**Comment by vjovanov** [comment]
We now support this pattern.
