### ISSUE TITLE
Can't find header file sharedGCStructs.hpp

### ISSUE THREAD

**Issue by Anivie** [oracle/graal#5370]
**Describe the issue**
Then i try to use G1 gc to build a native image on windows,it give an error,i can't find this file in any environment on my computer.

**Steps to reproduce the issue**
Using `native-image --gc=G1 -H:-CheckToolchain main` to build

**Describe GraalVM and your environment:**
 - JDK major version: GraalVM EE 22.3.0 (build 19.0.1+10-jvmci-22.3-b07)
 - OS: Microsoft Windows 11 [version 10.0.22621.755]
 - Architecture: AMD64
 - Visual Studio Version: Microsoft Visual Studio Community 2022 (64 位) - Version 17.3.6

**More details**
It can work normally using the default GC.
```
========================================================================================================================GraalVM Native Image: Generating 'main' (executable)...
========================================================================================================================[1/7] Initializing...                                                                                    (4.8s @ 0.22GB) Version info: 'GraalVM 22.3.0 Java 19 EE'
 Java version info: '19.0.1+10-jvmci-22.3-b07'
 C compiler: cl.exe (null, null, 0.0.0)
 Garbage collector: Serial GC
[2/7] Performing analysis...  [*****]                                                                    (6.9s @ 1.42GB)   2,966 (73.47%) of  4,037 classes reachable
   3,497 (50.89%) of  6,872 fields reachable
  14,264 (45.10%) of 31,626 methods reachable
      24 classes,     0 fields, and   329 methods registered for reflection
      61 classes,    51 fields, and    52 methods registered for JNI access
       1 native library: version
[3/7] Building universe...                                                                               (0.9s @ 0.43GB)[4/7] Parsing methods...      [*]                                                                        (0.5s @ 1.18GB)[5/7] Inlining methods...     [***]                                                                      (0.3s @ 1.55GB)[6/7] Compiling methods...    [***]                                                                     (11.2s @ 2.71GB)[7/7] Creating image...                                                                                  (1.4s @ 3.20GB)   5.94MB (44.95%) for code area:     7,055 compilation units
   7.09MB (53.61%) for image heap:  117,712 objects and 5 resources
 195.56KB ( 1.44%) for other data
  13.22MB in total
------------------------------------------------------------------------------------------------------------------------Top 10 packages in code area:                               Top 10 object types in image heap:
 749.81KB java.util                                            1.08MB byte[] for code metadata
 521.54KB java.lang                                          817.80KB byte[] for general heap data
 429.15KB java.text                                          789.45KB java.lang.String
 344.09KB com.oracle.svm.core.code                           702.25KB byte[] for java.lang.String
 249.07KB java.util.concurrent                               489.43KB java.lang.Class
 212.32KB java.util.regex                                    296.81KB java.util.concurrent.ConcurrentHashMap$Node
 173.69KB java.math                                          207.19KB java.lang.Object[]
 158.21KB java.io                                            176.41KB java.util.HashMap$Node
 155.48KB com.oracle.svm.core.genscavenge                    152.82KB byte[] for embedded resources
 151.79KB com.oracle.svm.core.jni.functions                  142.94KB char[]
   2.82MB for 120 more packages                                1.30MB for 783 more object types
------------------------------------------------------------------------------------------------------------------------                        0.4s (1.4% of total time) in 21 GCs | Peak RSS: 4.93GB | CPU load: 7.20
```

If i am enable G1:
```
========================================================================================================================GraalVM Native Image: Generating 'main' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                    (0.0s @ 0.16GB)Fatal error: com.oracle.svm.core.util.VMError$HostedError: Header file include/sharedGCStructs.hpp not found at main search location(s):
C:\Java\Graal_19\lib\svm\clibraries\windows-amd64\include\sharedGCStructs.hpp
 Use option -H:CLibraryPath to specify header file search locations.
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.c.ProjectHeaderFile$HeaderResolversRegistry.resolve(ProjectHeaderFile.java:132)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.c.ProjectHeaderFile.resolve(ProjectHeaderFile.java:84)
        at com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.gc.g1.nativelib.a.getHeaderFiles(stripped:26)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.codegen.QueryCodeWriter.visitNativeCodeInfo(QueryCodeWriter.java:146)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.info.NativeCodeInfo.accept(NativeCodeInfo.java:57)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.codegen.QueryCodeWriter.write(QueryCodeWriter.java:91)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.CAnnotationProcessor.process(CAnnotationProcessor.java:101)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.NativeLibraries.finish(NativeLibraries.java:554)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1714)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1121)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:915)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:575)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
------------------------------------------------------------------------------------------------------------------------                         0.1s (3.2% of total time) in 8 GCs | Peak RSS: 0.64GB | CPU load: 0.52
========================================================================================================================Failed generating 'main' after 3.8s.
```

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, we will take a look into shortly

**Comment by wirthi** [comment]
Hi,

thanks for your report. We don't support G1 in native-image on Windows at the moment. This will be fixed eventually, it is not on any immediate roadmap yet.

What could definitely be better here is the error message.

Best,
Christian
