### ISSUE TITLE
Java AWT missing Native Library

### ISSUE THREAD

**Issue by KhanhVNMC** [oracle/graal#5372]
**Describe the issue**
A clear and concise description of the issue. We recommend using the [latest snapshot builds](https://github.com/graalvm/graalvm-ce-dev-builds/releases) to replicate the issue as  bugs are constantly being fixed in the master branch
Windows Native Image error: `no awt in java.library.path`
This issue have been reported before but after running the latest version of GraalVM, the issue still seems to be there, 
This doesn't stop the program from compiling, only when you compiled it into a native executable and execute it the error is thrown

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1.  Create a standard java application that uses Java AWT, In my example, awt ROBOT
2. Native image the output JAR 
3. Execute it

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **LATEST**
 - JDK major version: **17**
 - OS: **Windows 10**
 - Architecture: **AMD64**

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no awt in java.library.path
        at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryRelative(NativeLibrarySupport.java:132)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:47)
        at java.lang.Runtime.loadLibrary0(Runtime.java:818)
        at java.lang.System.loadLibrary(System.java:1989)
        at java.awt.Toolkit$2.run(Toolkit.java:1388)
        at java.awt.Toolkit$2.run(Toolkit.java:1386)
        at java.security.AccessController.executePrivileged(AccessController.java:169)
        at java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.awt.Toolkit.loadLibraries(Toolkit.java:1385)
        at java.awt.Toolkit.initStatic(Toolkit.java:1423)
        at java.awt.Toolkit.<clinit>(Toolkit.java:1397)
        at java.awt.Rectangle.<clinit>(Rectangle.java:175)
        at vn.giakhanhvn.ScreenshotTest.main(ScreenshotTest.java:13)```

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reporting this, I'm assuming you run this with v22.3.0, could you also check with v23.0.0-dev? did you generate the config files for the app using the native agent?

**Comment by rahmanusta** [comment]
I have the same issue with the java.awt.Taskbar class. The issue exist in v23.0.0-dev as well.

I'm using the following class from java.awt.**

```
import java.awt.Color;
import java.awt.Desktop;
import java.awt.font.FontRenderContext;
import java.awt.geom.Rectangle2D;
import java.awt.GraphicsEnvironment;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.awt.Image;
import java.awt.MenuItem;
import java.awt.PopupMenu;
import java.awt.RenderingHints;
import java.awt.Taskbar;
import java.awt.Toolkit;
```

**Comment by oubidar-Abderrahim** [comment]
Could you please share a reproducer with detailed steps on how to reproduce?

**Comment by KhanhVNMC** [comment]
The issue could be represented easily by any references to the Java AWT library, for example, I could easily reproduce this bug by making a Java project with the latest and "greatest" Java version (JdK18_1) create a class

'''java

import java.awt.AWTException;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.Robot;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.File;
import javax.imageio.ImageIO;
  
public class Screenshot {
    public static void main(String[] args) {
        try {
            Robot r = new Robot();
            String path = "test.jpg";
            Rectangle capture = 
            new Rectangle(Toolkit.getDefaultToolkit().getScreenSize());
            BufferedImage Image = r.createScreenCapture(capture);
        ImageIO.write(Image, "jpg", new File(path));
           System.out.println("done");
        }
        catch (Exception ex) {}
    }
}
'''
Compile it to a standard .JAR file and we done with java side for now

While executing with the standard 'java -jar Test.jar' the program function as it should and produce a file named "test.jpg" in the execution folder

But now, to the GraalVM Native image problem
Compile it by using 'native-image -jar Test.jar'
During the compilation, the native image compiler throws 'HostedError: should not reach here' but it does not fail, the program produced an .exe as it should, but as soon as I execute it, the No AWT exception is thrown, keep in mind that the native image compiler still produce all of its needed native library to work with, so the problem is probably somewhere else.

**Comment by oubidar-Abderrahim** [comment]
It seems like this is a missing config issue. I used the tracing agent to generate config files, added them during build time, and built a working executable.
You can learn more about the agent here: https://www.graalvm.org/22.3/reference-manual/native-image/metadata/AutomaticMetadataCollection/
Finally, these are the commands I used to build the image:

```
1. javac Screenshot.java
2. java -agentlib:native-image-agent=config-output-dir=configs Screenshot
3. native-image -H:ConfigurationFileDirectories=configs Screenshot
4. screenshot.exe
```

**Comment by KhanhVNMC** [comment]
My result said otherwise, i have built the "configuration" as you said and still got the error whatsoever
![image](https://user-images.githubusercontent.com/71543494/204126372-eba20011-22a7-47db-9b74-8b3ed70c3011.png)

**Comment by oubidar-Abderrahim** [comment]
I verified this issue on another machine and still was able to build and run the image successfully. Please verify that you have all the prerequisites for using native image and test your installation with a simple hello world example first.

**Comment by imgoby** [comment]
This is how to solve:
1. Install 23.0.5.r17-nik
sdk install java 23.0.5.r17-nik

2. Build the application and add the parameter: - Djava. awt. headless=true
```

<plugin>
                    <groupId>org.graalvm.nativeimage</groupId>
                    <artifactId>native-image-maven-plugin</artifactId>
                    <version>21.1.0</version>
                    <configuration>
                        <buildArgs>-J-Xmx4G -H:+ReportExceptionStackTraces -Djava.awt.headless=true -Dspring.native.remove-unused-autoconfig=true -Dspring.native.remove-yaml-support=true</buildArgs>
                        <imageName>${project.artifactId}</imageName>
                    </configuration>
                    <executions>
                        <execution>
                            <goals>
                                <goal>native-image</goal>
                            </goals>
                            <phase>package</phase>
                        </execution>
                    </executions>
                </plugin>
```


4. Copy executable file and ".so files" to the target environment
5 Run the executable file

**Comment by imgoby** [comment]
reference resources https://bell-sw.com/blog/how-to-turn-awt-applications-into-native-images/

**Comment by LeonisX** [comment]
I want to say that I also couldn't run the Screenshot example, the source code and build recipe of which were presented above. GraalVM CE 23-dev+25.1.

Even this method didn't help:

native-image -H:ConfigurationFileDirectories=configs -Djava.awt.headless=true Screenshot

Also tried with Java version: 23.0.2+9, vendor version: Liberica-NIK-24.1.2-1

========================================================================================================================
GraalVM Native Image: Generating 'screenshot' (executable)...
========================================================================================================================
For detailed information and explanations on the build output, visit:
https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/BuildOutput.md
------------------------------------------------------------------------------------------------------------------------
[1/8] Initializing...                                                                                    (5.7s @ 0.06GB)
 Java version: 23.0.2+9, vendor version: Liberica-NIK-24.1.2-1
 Graal compiler: optimization level: 2, target machine: x86-64-v3
 C compiler: cl.exe (microsoft, x64, 19.43.34808)
 Garbage collector: Serial GC (max heap size: 80% of RAM)
 1 user-specific feature(s):
 - com.oracle.svm.thirdparty.gson.GsonFeature
------------------------------------------------------------------------------------------------------------------------
Build resources:
 - 8.67GB of memory (54.7% of 15.85GB system memory, determined at start)
 - 8 thread(s) (100.0% of 8 available processor(s), determined at start)
[2/8] Performing analysis...  [******]                                                                  (20.3s @ 0.55GB)
    5,357 reachable types   (74.6% of    7,183 total)
    7,938 reachable fields  (48.2% of   16,475 total)
   24,350 reachable methods (47.3% of   51,459 total)
    1,700 types,    19 fields, and   367 methods registered for reflection
      187 types,   242 fields, and   144 methods registered for JNI access
        3 native libraries: crypt32, ncrypt, version
[3/8] Building universe...                                                                               (2.5s @ 0.62GB)
[4/8] Parsing methods...      [*]                                                                        (1.9s @ 0.68GB)
[5/8] Inlining methods...     [***]                                                                      (1.6s @ 0.76GB)
[6/8] Compiling methods...    [****]                                                                    (19.8s @ 0.66GB)
[7/8] Laying out methods...   [**]                                                                       (2.8s @ 0.83GB)

[8/8] Creating image...       [**]                                                                       (0.0s @ 0.91GB)
```

## Stack Trace

```java
com.oracle.svm.core.util.VMError$HostedError: should not reach here: unexpected input could not be handled: 2
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHereUnexpectedInput(VMError.java:97)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.jdk.JNIRegistrationSupport.makeShimLibrary(JNIRegistrationSupport.java:320)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.jdk.JNIRegistrationSupport.makeShimLibraries(JNIRegistrationSupport.java:278)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.jdk.JNIRegistrationSupport.afterImageWrite(JNIRegistrationSupport.java:224)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$doRun$9(NativeImageGenerator.java:767)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:93)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:767)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:554)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:533)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:716)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:139)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)

**Comment by LeonisX** [comment]
Same problem solved for Linux: https://github.com/oracle/graal/issues/8273

I tried to add the awt.lib library to the linker arguments, but I got serious conflicts with prism_d3d.lib and the application did not compile.

```
link C:\project\target\gluonfx\x86_64-windows\gvm\App\launcher.obj C:\project\target\gluonfx\x86_64-windows\gvm\tmp\SVM-1741246147075\app.mainapp.obj C:\project\target\gluonfx\x86_64-windows\gvm\App\IconGroup.obj j2pkcs11.lib java.lib net.lib nio.lib prefs.lib zip.lib sunmscapi.lib extnet.lib jvm.lib libchelper.lib advapi32.lib iphlpapi.lib secur32.lib userenv.lib version.lib ws2_32.lib winhttp.lib ncrypt.lib crypt32.lib mswsock.lib /NODEFAULTLIB:libcmt.lib /SUBSYSTEM:WINDOWS /ENTRY:mainCRTStartup comdlg32.lib dwmapi.lib gdi32.lib imm32.lib shell32.lib uiautomationcore.lib urlmon.lib winmm.lib glass.lib javafx_font.lib javafx_iio.lib prism_common.lib prism_d3d.lib /WHOLEARCHIVE:glass.lib /WHOLEARCHIVE:javafx_font.lib /WHOLEARCHIVE:javafx_iio.lib /WHOLEARCHIVE:prism_common.lib /WHOLEARCHIVE:prism_d3d.lib awt.lib /OUT:C:\project\target\gluonfx\x86_64-windows\App.exe /LIBPATH:C:\Users\user\.gluon\substrate\javafxStaticSdk\21-ea+11.2\windows-x86_64\sdk\lib /LIBPATH:C:\Program Files\Java\graal23\lib\svm\clibraries\windows-amd64 /LIBPATH:C:\Program Files\Java\graal23\lib\static\windows-amd64
```
