### ISSUE TITLE
java.lang.reflect.Parameter usage prevents native image generation

### ISSUE THREAD

**Issue by stuartwdouglas** [oracle/graal#539]
I got the following error when attempting to compile a jar that included eclipse Yasson (the JSON-B RI):

`
Error: Unsupported method java.lang.reflect.Executable.getParameters0() is reachable: Native method. If you intend to use the Java Native Interface (JNI), specify -H:+JNI and see also -H:JNIConfigurationFiles=<path> (use -H:+PrintFlags for details)
To diagnose the issue, you can add the option -H:+ReportUnsupportedElementsAtRuntime. The unsupported element is then reported at run time when it is accessed the first time.
Call path from entry point to java.lang.reflect.Executable.getParameters0():
at java.lang.reflect.Executable.getParameters0(Executable.java)
at java.lang.reflect.Executable.privateGetParameters(Executable.java:404)
at java.lang.reflect.Executable.getParameters(Executable.java:357)
at java.lang.reflect.Executable.getAllGenericParameterTypes(Executable.java:305)
at java.lang.reflect.Parameter.getParameterizedType(Parameter.java:201)
at java.lang.reflect.Parameter.toString(Parameter.java:125)
at com.oracle.svm.reflect.proxies.Proxy_1042_Object_toString.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:173)
at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
`

It appears to be caused by the usage of java.lang.reflect.Parameter

**Comment by cstancu** [comment]
The issue has been fixed.
