### ISSUE TITLE
`native-image` crashes when passing --gc=epsilon with some `serialGCOnly` option

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#5432]
**Describe the issue**
`native-image` crashes with 

```
Error: ImageSingletons do not contain key com.oracle.svm.core.heap.Heap
```

when passing --gc=epsilon with some serialGCOnly option.

**Steps to reproduce the issue**
```
native-image --gc=epsilon -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime HelloWorld
```

**Describe GraalVM and your environment:**
 - GraalVM version: **22.3.0**
 - JDK major version: **17**
 - OS: **Fedora 37**
 - Architecture: **AMD64**

**More details**
The stack trace is:
```
Error: ImageSingletons do not contain key com.oracle.svm.core.heap.Heap
com.oracle.svm.core.util.UserError$UserException: ImageSingletons do not contain key com.oracle.svm.core.heap.Heap
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ImageSingletonsSupportImpl$HostedManagement.doLookup(ImageSingletonsSupportImpl.java:117)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ImageSingletonsSupportImpl.lookup(ImageSingletonsSupportImpl.java:44)
	at org.graalvm.sdk/org.graalvm.nativeimage.ImageSingletons.lookup(ImageSingletons.java:86)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.heap.Heap.getHeap(Heap.java:51)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.genscavenge.SerialGCOptions.serialGCOnly(SerialGCOptions.java:113)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.option.HostedOptionKey.validate(HostedOptionKey.java:103)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.option.ValidateImageBuildOptionsFeature.validate(ValidateImageBuildOptionsFeature.java:52)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.option.ValidateImageBuildOptionsFeature.afterRegistration(ValidateImageBuildOptionsFeature.java:44)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$14(NativeImageGenerator.java:854)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:85)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:854)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:575)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)

```

It looks like `native-image` is trying to report that the option is not supported with the epsilon GC but crashes because it tries to get the GC name from the `Heap` in the `ImageSingletons` before actually setting it in
https://github.com/oracle/graal/blob/0164f3ece5830b8e8df953b92afe8bc3bc29d15f/substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/SerialGCOptions.java#L113

I suspect that the same holds for the check in https://github.com/oracle/graal/blob/0164f3ece5830b8e8df953b92afe8bc3bc29d15f/substratevm/src/com.oracle.svm.core.genscavenge/src/com/oracle/svm/core/genscavenge/SerialAndEpsilonGCOptions.java#L85

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, we'll take a look into it shortly
