### ISSUE TITLE
no object DCH for MIME type multipart/mixed, when trying to send smtp email, in spring boot 3 RC2 app native only

### ISSUE THREAD

**Issue by RobMaskell** [oracle/graal#5440]
**Describe the issue**
I have a Spring Boot app upgraded to 3.0.0-RC2, when I'm running in vscode it sends email fine, after I `nativeCompile` and run the resulting binary I get the following when the app tries to send an email via smtp (see partial stack trace below)

I have tried to debug the issue to add some hints for what looks like a missing resources or class issue but I can't get to the bottom of it or find it reported anywhere.

This version of Spring Boot has swapped over to the Jakarta mail code but this was happening on RC1 which presumably used the old code

**Steps to reproduce the issue**
I can create an example app if this isn't an obvious issue
I use `./gradlew clean nativeCompile` to create the native binary and then run it locally from the command line

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: 22.3.r17-grl for JDK and whatever comes with Spring Boot 3.0.0_RC2 and 0.9.17 of the gradle build tools. 
 - JDK major version: 17.0.5
```
openjdk 17.0.5 2022-10-18
OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)
```
 - OS: Pop_OS (Linux) in VM on MacOS
 - Architecture: Linux pop-os 6.0.6-76060006-generic #202210290932~1667401208~22.04~d2df702 SMP PREEMPT_DYNAMIC Wed N x86_64 x86_64 x86_64 GNU/Linux

**More details**
```
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.mail.MailSendException: Failed messages: jakarta.mail.MessagingException: IOException while sending message;
  nested exception is:
	jakarta.activation.UnsupportedDataTypeException: no object DCH for MIME type multipart/mixed; 
	boundary="----=_Part_0_978564634.1668545195831"; message exceptions (1) are:
Failed message 1: jakarta.mail.MessagingException: IOException while sending message;
  nested exception is:
	jakarta.activation.UnsupportedDataTypeException: no object DCH for MIME type multipart/mixed; 
	boundary="----=_Part_0_978564634.1668545195831"] with root cause

org.springframework.mail.MailSendException: Failed messages: jakarta.mail.MessagingException: IOException while sending message;
  nested exception is:
	jakarta.activation.UnsupportedDataTypeException: no object DCH for MIME type multipart/mixed; 
	boundary="----=_Part_0_978564634.1668545195831"
	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:491) ~[na:na]
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:361) ~[na:na]
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:356) ~[na:na]
```

**Comment by RobMaskell** [comment]
For anyone else who finds this I can't give you an exact fix but what I did was to run the jar with `-agentlib:native-image-agent=config-output-dir=checkAot/` then add anything related to `smtp` or `mail` to my reflect-config.json and resource-config.json and it started working, I imagine there is a missing hint somewhere
