### ISSUE TITLE
AWT  ERR

### ISSUE THREAD

**Issue by TheBlindM** [oracle/graal#5445]
code
```
  URI uri = URI.create(githubUrl);
   Desktop.getDesktop().browse(uri);
```

err
```
to handle request: java.lang.UnsupportedOperationException: Add AWT Quarkus extension to enable Java2D/ImageIO. Additional system libraries such as `freetype' and `fontconfig' might be needed.
        at java.desktop@19.0.1/java.awt.GraphicsEnvironment.isHeadless(GraphicsEnvironment.java:50)
        at java.desktop@19.0.1/java.awt.Desktop.getDesktop(Desktop.java:302)
        at com.tshell.service.DesktopService.toGithub(DesktopService.java:26)
        at com.tshell.service.DesktopService_ClientProxy.toGithub(Unknown Source)
        at com.tshell.controller.DesktopController.toGithub(DesktopController.java:28)
        at java.base@19.0.1/java.lang.reflect.Method.invoke(Method.java:578)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:91)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@19.0.1/java.lang.Thread.run(Thread.java:1589)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:178)
```

version 
java version "19.0.1" 2022-10-18
Java(TM) SE Runtime Environment GraalVM EE 22.3.0 (build 19.0.1+10-jvmci-22.3-b07)
Java HotSpot(TM) 64-Bit Server VM GraalVM EE 22.3.0 (build 19.0.1+10-jvmci-22.3-b07, mixed mode, sharing)

<quarkus.native.additional-build-args>-J--enable-preview,-R:MaxHeapSize=1073741824,-J-XX:+UseStringDeduplication,-R:MaxNewSize=20971520,--initialize-at-run-time=cn.hutool.core.lang.id.NanoId,--initialize-at-run-time=com.tshell.core.JschPtyConnector,--trace-object-instantiation=java.lang.Thread</quarkus.native.additional-build-args>

**Comment by Karm** [comment]
Hello @TheBlindM, 

Thanks for using Quarkus :)
The exceptions states hopefully clearly enough what is wrong:
```
to handle request: java.lang.UnsupportedOperationException:
Add AWT Quarkus extension to enable Java2D/ImageIO.
Additional system libraries such as `freetype' and `fontconfig' might be needed.
```
Beware that the AWT extension is meant for *headless* server side image processing, e.g. watermarking, writing text over images, resizing images, generating QR codes etc. Attempts to do anything beyond that are out of the scope of our server side setup.

This issue here should be closed.

**Comment by TheBlindM** [comment]
> 

so what should i do?😭
I wrote a desktop program with Quarkus and Tarui, and I need to use dasktop related, such as browser jump, or open file, Desktop.getDesktop().open(new File(savePath));

**Comment by wirthi** [comment]
HI @TheBlindM 

I am closing this issue here, as this is not a problem of GraalVM Native Image. Please use a Quarkus-related support channel like https://github.com/quarkusio/quarkus/discussions

Christian
