### ISSUE TITLE
native image build swt application can't run

### ISSUE THREAD

**Issue by duanli1985** [oracle/graal#5476]
i write a swt application 
`package cccc;
import org.eclipse.swt.SWT;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Shell;
import org.eclipse.swt.widgets.Text;

public class xx {

public static void main (String [] args) {
	Display display = new Display ();
	Shell shell = new Shell(display);
	
	Text helloWorldTest = new Text(shell, SWT.NONE);
	helloWorldTest.setText("Hello World SWT");
	helloWorldTest.pack();
	
	shell.pack();
	shell.open ();
	while (!shell.isDisposed ()) {
		if (!display.readAndDispatch ()) display.sleep ();
	}
	display.dispose ();
}
}`
i can run it using java -jar a.jar
i can  native build it using native-image -jar a.jar   success, but when i run it using ./a it will throw a exception
SWT-JNI: ERROR(1523): Failed to resolve 'java/lang/Throwable'
Exception in thread "main" java.lang.NoSuchMethodError: org.eclipse.swt.widgets.Display.rendererClassInitProc(JJ)J
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1259)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1244)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.GetStaticMethodID(JNIFunctions.java:413)
	at org.eclipse.swt.internal.Callback.bind(Callback.java)
	at org.eclipse.swt.internal.Callback.<init>(Callback.java:137)
	at org.eclipse.swt.internal.Callback.<init>(Callback.java:88)
	at org.eclipse.swt.internal.Callback.<init>(Callback.java:66)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:1188)
	at org.eclipse.swt.widgets.Display.create(Display.java:1091)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:168)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:643)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:634)
	at cccc.xx.main(xx.java:10)

my graalvm version is 22.3.0  jdk version is 17.0.5
os is 20.04  hardware is amd64

**Comment by wirthi** [comment]
Do you provide a JNI configuration? See https://www.graalvm.org/22.0/reference-manual/native-image/BuildConfiguration/ for the general information on the topic or https://www.graalvm.org/22.0/reference-manual/native-image/Agent/#building-native-image-with-java-reflection-example for how to use the tracing agent to generate the necessary files for you.

**Comment by duanli1985** [comment]
> Do you provide a JNI configuration? See https://www.graalvm.org/22.0/reference-manual/native-image/BuildConfiguration/ for the general information on the topic or https://www.graalvm.org/22.0/reference-manual/native-image/Agent/#building-native-image-with-java-reflection-example for how to use the tracing agent to generate the necessary files for you.

what should i do it?

**Comment by chirontt** [comment]
@duanli1985 
> what should i configure jni ? my jar file include a swt.jar file

How exactly is the `swt.jar` file included in your `a.jar` file?

Please show the steps how you compile and produce the `a.jar` file.

**Comment by fernando-valdez** [comment]
Closing this ticket due to the lack of response from the reporter.
