### ISSUE TITLE
native-image cannot set G1 as default gc on windows

### ISSUE THREAD

**Issue by kyangcmXF** [oracle/graal#5508]
**Describe the issue**
I use GraalVM17 CE on windows platform. When I try to set G1 as my default gc , I got some errors.

**Steps to reproduce the issue**
1. generate class file
javac HelloGraalVM.java
2. generate native image file
native-image.cmd HelloGraalVM --gc=G1

**Describe GraalVM and your environment:**
GraalVM version GraalVM CE 22.3.0 
JDK major version: 17
OS: Windows

**More details**
My java content is below here:
```
public class HelloGraalVM {
    public static void main(String[] args){
        System.out.println("hello GraalVM");
    }
}
```

**Error Log**

```
PS D:\00MyProject\Java\JDK17Demo> native-image.cmd HelloGraalVM --gc=G1
========================================================================================================================
GraalVM Native Image: Generating 'hellograalvm' (executable)...
========================================================================================================================

[1/7] Initializing...                                                                                    (0.0s @ 0.14GB)
Fatal error: com.oracle.svm.core.util.VMError$HostedError: Header file include/sharedGCStructs.hpp not found at main search location(s):
D:\JavaProgram\graalvm-ce-java17-22.3.0\lib\svm\clibraries\windows-amd64\include\sharedGCStructs.hpp
 Use option -H:CLibraryPath to specify header file search locations.
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.c.ProjectHeaderFile$HeaderResolversRegistry.resolve(ProjectHeaderFile.java:132)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.c.ProjectHeaderFile.resolve(ProjectHeaderFile.java:84)
        at com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.gc.g1.nativelib.a.getHeaderFiles(stripped:26)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.codegen.QueryCodeWriter.visitNativeCodeInfo(QueryCodeWriter.java:146)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.info.NativeCodeInfo.accept(NativeCodeInfo.java:57)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.codegen.QueryCodeWriter.write(QueryCodeWriter.java:91)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.CAnnotationProcessor.process(CAnnotationProcessor.java:101)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.NativeLibraries.finish(NativeLibraries.java:554)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1714)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1121)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:915)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:575)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
------------------------------------------------------------------------------------------------------------------------
                         0.2s (5.5% of total time) in 8 GCs | Peak RSS: 0.53GB | CPU load: 2.97
========================================================================================================================
Failed generating 'hellograalvm' after 2.8s.
Error: Image build request failed with exit status 1
```

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this,  We don't support G1 in native image on Windows at the moment. This will be fixed eventually, it is not on any immediate roadmap yet.
You can track this issue on #5370
