### ISSUE TITLE
Native image compilation fails with ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by vbekiaris** [oracle/graal#551]
Stack trace:
```
analysis:  91,812.37 ms
2 fatal errors detected:
fatal error: java.lang.IndexOutOfBoundsException: index -1
	at java.util.concurrent.atomic.AtomicReferenceArray.checkedByteOffset(AtomicReferenceArray.java:78)
	at java.util.concurrent.atomic.AtomicReferenceArray.get(AtomicReferenceArray.java:125)
	at com.oracle.graal.pointsto.flow.context.object.AnalysisObject.getInstanceFieldTypeStore(AnalysisObject.java:213)
	at com.oracle.graal.pointsto.flow.context.object.AnalysisObject.getInstanceFieldFlow(AnalysisObject.java:199)
	at com.oracle.graal.pointsto.flow.LoadFieldTypeFlow$LoadInstanceFieldTypeFlow.onObservedUpdate(LoadFieldTypeFlow.java:159)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:347)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:389)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:500)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

This occurs while trying to substitute 3 public static methods like this:

```
@TargetClass(ServiceLoader.class)
@Substitute
final class Target_com_hazelcast_util_ServiceLoader {

    @Substitute
    public static <T> Iterator<T> iterator(Class<T> expectedType, String factoryId, ClassLoader classLoader) throws Exception {
      ...
    }

    @Substitute
    public static <T> Iterator<Class<T>> classIterator(Class<T> expectedType, String factoryId, ClassLoader classLoader)
            throws Exception {
...
    }

    @Substitute
    public static <T> T load(Class<T> clazz, String factoryId, ClassLoader classLoader) throws Exception {
...
    }
}
```

Original class is [`com.hazelcast.util.ServiceLoader`](https://github.com/hazelcast/hazelcast/blob/81a872c2588e1f47cf613b09943b0f7f96f107bb/hazelcast/src/main/java/com/hazelcast/util/ServiceLoader.java#L50).

`java -version`:
```
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
GraalVM 1.0.0-rc4 (build 25.71-b01-internal-jvmci-0.45, mixed mode)
```

I did try to debug this but running with a debugger attached takes ages on my machine.

**Comment by cstancu** [comment]
Thank you for your report. The `IndexOutOfBoundsException` has been fixed in the meantime. If the underlying problem still persists now you should at least get a more intuitive error message. Please open a fresh issue if that's the case.
