### ISSUE TITLE
ForkJoinTask doesn't handle exceptions correctly in Native Image

### ISSUE THREAD

**Issue by panga** [oracle/graal#552]
Description: 

ForkJoinTask.getThrowableException() is unimplemented, so any exception thrown during a fork join task execution is hidden as "UnsupportedFeatureError" and fails my application.

GraalVM version: 1.0.0 RC4

Stacktrace:
```
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: unimplemented
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Error.<init>(Error.java:70)
	at com.oracle.svm.core.jdk.UnsupportedFeatureError.<init>(UnsupportedFeatureError.java:31)
	at com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.unsupportedFeature(VMErrorSubstitutions.java:109)
	at com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.unimplemented(VMErrorSubstitutions.java:103)
	at com.oracle.svm.core.jdk.Target_java_util_concurrent_ForkJoinTask.getThrowableException(RecomputedFields.java:497)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
````

**Comment by panga** [comment]
Hi! Do you have any update or feedback about this request?
