### ISSUE TITLE
Native Image fails when using Kotlin Coroutines

### ISSUE THREAD

**Issue by DarkAtra** [oracle/graal#5606]
**Describe the issue**
I'm trying to create a native image for [a spring boot 3 based kotlin application](https://github.com/DarkAtra/v-rising-discord-bot) that uses coroutines in some places.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. `git clone git@github.com:DarkAtra/v-rising-discord-bot.git`
2. `cd v-rising-discord-bot/`
3. `mvn -Pnative clean spring-boot:build-image` (requires docker)

**Describe GraalVM and your environment:**
 - GraalVM version: **GraalVM 22.3.0 Java 17 CE**
 - JDK major version: **17**
 - OS: **Linux - Ubuntu (WSL 2 on Windows 10)**
 - Architecture: **x86_64**

**More details**
```
Error: Non-reducible loop requires too much duplication. Setting MaxDuplicationFactor to a value higher than 2.0 may resolve this.
Detailed message:
Call path from entry point to de.darkatra.vrising.discord.ServerStatusMonitorService$launchServerStatusMonitor$1.invokeSuspend(Object):
	at de.darkatra.vrising.discord.ServerStatusMonitorService$launchServerStatusMonitor$1.invokeSuspend(ServerStatusMonitorService.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:233)
	at java.lang.Shutdown.runHooks(Shutdown.java:130)
	at java.lang.Shutdown.shutdown(Shutdown.java:185)
	at com.oracle.svm.core.jdk.RuntimeSupport.shutdown(RuntimeSupport.java:154)
	at com.oracle.svm.core.JavaMainWrapper.runShutdown(JavaMainWrapper.java:195)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:242)
```
I already tried increasing `MaxDuplicationFactor` to 4.0 and also 10.0 but it didn't solve the issue so i suspect something else is wrong.

**Comment by DarkAtra** [comment]
Hey @oubidar-Abderrahim,
i used the following property for the `spring-boot-maven-plugin` to customize the native image args:
```
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <configuration>
        <image>
            <name>${image.name}</name>
            <builder>paketobuildpacks/builder:tiny</builder>
            <env>
                <BP_OCI_SOURCE>${project.scm.url}</BP_OCI_SOURCE>
                <BP_NATIVE_IMAGE_BUILD_ARGUMENTS>-H:MaxDuplicationFactor=4.0</BP_NATIVE_IMAGE_BUILD_ARGUMENTS>
            </env>
        </image>
    </configuration>
</plugin>
```

**Comment by DarkAtra** [comment]
Any tips on how to proceed?

**Comment by DarkAtra** [comment]
it seems like moving the update logic into its own method fixes the issue and does not require setting a higher `MaxDuplicationFactor` than the default. See: https://github.com/DarkAtra/v-rising-discord-bot/commit/0e744c20520296120cf16357dbb3a26506a62f15
