### ISSUE TITLE
Native Image with Spring Boot 3.0.1 throwing Missing character set id 560 is not loaded at image build time Error

### ISSUE THREAD

**Issue by syedyusufh** [oracle/graal#5682]
Have built a native image using the Spring Boot latest version 3.0.1 (after solving many errors) and seeing the below error when application tries to connect to a Oracle database during startup.

Have tried `-H:+AddAllCharsets` and wasn't solving the issue either

```
java.lang.IllegalStateException: Missing character set id 560 is not loaded at image build time
        at oracle.sql.CharacterSet.make(CharacterSet.java:121) ~[xxxxxx:21.6.0.0.0]
        at oracle.jdbc.driver.DBConversion.init(DBConversion.java:184) ~[na:na]
        at oracle.jdbc.driver.DBConversion.<init>(DBConversion.java:137) ~[na:na]
        at oracle.jdbc.driver.T4CConnection.doCharSetNegotiation(T4CConnection.java:3122) ~[xxxxxxx:21.6.0.0.0]
        at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:2658) ~[xxxxxx:21.6.0.0.0]
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:666) ~[xxxxxx:21.6.0.0.0]
        at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:1088) ~[xxxxxx:21.6.0.0.0]
        at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:89) ~[xxxxxx:21.6.0.0.0]
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:732) ~[xxxxxx:21.6.0.0.0]
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:648) ~[xxxxxxx:21.6.0.0.0]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[na:na]
```

**Comment by aabbou** [comment]
Hi, thank you for reporting this issue. We will take a look at it and get back to you.

**Comment by oubidar-Abderrahim** [comment]
Have you tried generating the [Metadata files](https://www.graalvm.org/22.3/reference-manual/native-image/metadata/) while connected to the Oracle Database? remember that the config should be generated while testing most functionalities of your app as possible to have a complete configs.

**Comment by syedyusufh** [comment]
Yes, tried that option as well. However, it resulted in https://github.com/oracle/graal/issues/5684

**Comment by syedyusufh** [comment]
Hi @oubidar-Abderrahim , any update on this please? Thx in advance

**Comment by oubidar-Abderrahim** [comment]
From my understanding, this is a configuration issue and should be fixed by using the agent. If you're still facing this issue after using the agent (with the latest version of GraalVM and SpringBoot) please create a new issue and we will take a look at it. Thank you
