### ISSUE TITLE
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors

### ISSUE THREAD

**Issue by syedyusufh** [oracle/graal#5684]
Used the tracing agent to generate the necessary build-image artefacts for building native image with Spring Boot 3.0.1 and GraalVM 22.3.0. However seeing the below error,

```
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported features in 4 methods
Detailed message:
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image runtime.  Object has been initialized by the com.oracle.svm.hosted.annotation.SubstrateAnnotationExtracter class initializer with a trace:
        at java.util.jar.JarFile.<init>(JarFile.java:347)
        at jdk.internal.module.ModuleReferences$JarModuleReader.newJarFile(ModuleReferences.java:230)
        at jdk.internal.module.ModuleReferences$JarModuleReader.<init>(ModuleReferences.java:237)
        at jdk.internal.module.ModuleReferences.lambda$newJarModule$0(ModuleReferences.java:94)
        at jdk.internal.module.ModuleReferences$$Lambda$28/0x00000007c0004628.get(Unknown Source)
        at jdk.internal.module.ModuleReferenceImpl.open(ModuleReferenceImpl.java:93)
        at jdk.internal.loader.BuiltinClassLoader$5.apply(BuiltinClassLoader.java:1023)
        at jdk.internal.loader.BuiltinClassLoader$5.apply(BuiltinClassLoader.java:1020)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at jdk.internal.loader.BuiltinClassLoader.moduleReaderFor(BuiltinClassLoader.java:1031)
        at jdk.internal.loader.BuiltinClassLoader$2.run(BuiltinClassLoader.java:464)
        at jdk.internal.loader.BuiltinClassLoader$2.run(BuiltinClassLoader.java:459)
        at java.security.AccessController.executePrivileged(AccessController.java:807)
        at java.security.AccessController.doPrivileged(AccessController.java:569)
        at jdk.internal.loader.BuiltinClassLoader.findMiscResource(BuiltinClassLoader.java:458)
        at jdk.internal.loader.BuiltinClassLoader.findResources(BuiltinClassLoader.java:385)
        at java.lang.ClassLoader.getResources(ClassLoader.java:1468)
        at java.lang.ClassLoader.getResources(ClassLoader.java:1464)
        at java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1203)
        at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
        at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
        at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
        at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
        at jdk.vm.ci.services.JVMCIServiceLocator.getProviders(JVMCIServiceLocator.java:109)
        at jdk.vm.ci.hotspot.HotSpotJVMCICompilerConfig.getJVMCICompilerFactories(HotSpotJVMCICompilerConfig.java:159)
        at jdk.vm.ci.hotspot.HotSpotJVMCICompilerConfig.getCompilerFactory(HotSpotJVMCICompilerConfig.java:119)
        at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.<init>(HotSpotJVMCIRuntime.java:590)
        at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.runtime(HotSpotJVMCIRuntime.java:179)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Unknown Source)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:568)
        at com.oracle.svm.hosted.annotation.SubstrateAnnotationExtracter.<clinit>(SubstrateAnnotationExtracter.java:129)
```

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reaching out with this issue. Could you please provide the following?

- What OS you're using?
- What architecture?
- Could you please provide a reproducer for this issue?

**Comment by syedyusufh** [comment]
Hi @oubidar-Abderrahim , please find below

OS - Amazon Linux 2
Arch - AMD64
Reproducer - Please see if the below information helps, else I shall try to get one

The error does NOT occur if the below is configured for buildtime via native image configuration in pom.xml,

```
static {
	for (var id : reflectivelyReadAllCharacterSetIdentifiers()) {
		oracle.sql.CharacterSet.make(id);
	}
}

private static List<Short> reflectivelyReadAllCharacterSetIdentifiers() {

	var fields = CharacterSet.class.getFields();
	List<Short> collectedIds = new ArrayList<>(fields.length);

	for (var field : fields) {
		if (field.getType() == short.class && field.getName().endsWith("_CHARSET")) {
			try {
				collectedIds.add(field.getShort(null));
			} catch (IllegalAccessException e) {
				e.printStackTrace();
			}
		}
	}

	return collectedIds;
}
```

**Comment by pshirshov** [comment]
I experience the same problem.

The repo is here: https://github.com/7mind/distage-example
Checkout commit d3eacbe2c42872d79db6ae5f34fd087c1519ebb3, uncomment the following line in build.sbt:

```
//    graalVMNativeImageGraalVersion := Some("ol9-java17-22.3.1"), 
```

and comment out this one:

```
graalVMNativeImageGraalVersion := Some("ol8-java17-22.1.0"),
```


Then run ` sbt GraalVMNativeImage/packageBin`

**Comment by pshirshov** [comment]
Same issue: https://github.com/oracle/graal/issues/4797

**Comment by oubidar-Abderrahim** [comment]
duplicates #4797
