### ISSUE TITLE
Error encountered while parsing org.primefaces.component.treetable.export.TreeTablePDFExporter.addEmptyLine(com.lowagie.text.Paragraph, int)

### ISSUE THREAD

**Issue by ma-sharifi** [oracle/graal#5711]
I'm getting the following error while building a native image for a web application with Quarkus and Primefraces.

Describe GraalVM and environment:
- Java: 11
- GraalVM: OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)
- PrimeFaces: 11.0.0
- Quarkus: 2.12.1.Final
- OS: macOS , Apple M2

More details:
```
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.primefaces.component.treetable.export.TreeTablePDFExporter.addEmptyLine(com.lowagie.text.Paragraph, int) 
Parsing context:
   at org.primefaces.component.treetable.export.TreeTablePDFExporter.addEmptyLine(TreeTablePDFExporter.java:342)
   at org.primefaces.component.treetable.export.TreeTablePDFExporter.addEmptyLine(TreeTablePDFExporter.java:342)
   at org.primefaces.component.treetable.export.TreeTablePDFExporter.addEmptyLine(TreeTablePDFExporter.java:342)
   at org.primefaces.component.treetable.export.TreeTablePDFExporter.addEmptyLine(TreeTablePDFExporter.java:342)
   at org.primefaces.component.treetable.export.TreeTablePDFExporter.addEmptyLine(TreeTablePDFExporter.java:342)
   at org.primefaces.component.treetable.export.TreeTablePDFExporter.addEmptyLine(TreeTablePDFExporter.java:342)
   at org.primefaces.component.treetable.export.TreeTablePDFExporter.addEmptyLine(TreeTablePDFExporter.java:342)
   at org.primefaces.component.treetable.export.TreeTablePDFExporter.addEmptyLine(TreeTablePDFExporter.java:342)

        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:153)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:104)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:83)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraph(MethodTypeFlow.java:65)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultSpecialInvokeTypeFlow.onObservedUpdate(DefaultSpecialInvokeTypeFlow.java:61)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:562)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:488)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: com.lowagie.text.Paragraph.add(com.lowagie.text.Element). This error is reported at image build time because class org.primefaces.component.treetable.export.TreeTablePDFExporter is registered for linking at image build time by command line
        at parsing org.primefaces.component.treetable.export.TreeTablePDFExporter.addEmptyLine(TreeTablePDFExporter.java:343)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2518)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:110)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3393)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3345)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3190)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1138)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1030)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:97)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:84)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:446)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:135)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:685)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:171)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:349)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:93)
        ... 13 more
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: com.lowagie.text.Paragraph.add(com.lowagie.text.Element). This error is reported at image build time because class org.primefaces.component.treetable.export.TreeTablePDFExporter is registered for linking at image build time by command line
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:333)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedMethod(SharedGraphBuilderPhase.java:323)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedInvoke(SharedGraphBuilderPhase.java:279)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1721)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5286)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3385)
        ... 28 more

```

Added following commands to maven:
```
<quarkus.package.type>native</quarkus.package.type>
<quarkus.native.additional-build-args>
   --trace-class-initialization=rg.primefaces.component.treetable.export.TreeTablePDFExporter,
   --initialize-at-run-time=org.primefaces.component.treetable.export.TreeTablePDFExporter
</quarkus.native.additional-build-args>
```

Added following to reflect-config.json

```json
{
    "name":"org.primefaces.component.treetable.export.TreeTablePDFExporter",
    "methods":[{"name":"addEmptyLine","parameterTypes":["com.lowagie.text.Paragraph","int"] }]
  },
  {
    "name":"org.apache.myfaces.cdi.view.ViewScopeBeanHolder",
    "methods":[{"name":"generateUniqueViewScopeId","parameterTypes":[] }]
  },
  {
    "name":"com.lowagie.text.Paragraph",
    "methods":[{"name":"add","parameterTypes":["com.lowagie.text.Element"] }]
  },
  {
    "name":"org.primefaces.component.treetable.export.TreeTablePDFExporter",
    "methods":[{"name":"<init>","parameterTypes":[] }]
  }
```
Would it be possible to help me with how to solve it?

**Comment by fniephaus** [comment]
@zakkak could you take a look at this please?

**Comment by viniciusxyz** [comment]
@ma-sharifi 

Do you have a sample project?

If you can add a project I can take a look and try to help you fix the problem

**Comment by ma-sharifi** [comment]
I haven't had a sample project yet, but I try to develop a sample.

**Comment by viniciusxyz** [comment]
@ma-sharifi 

ok, within the items requested when opening an MR, the project and the steps to reproduce the problem are important mainly because that way we don't have to go to the lib that is having problems and understand all the flow of operation.

As soon as the project is available I can take a look, I'm waiting.

**Comment by zakkak** [comment]
@ma-sharifi the issue here is that primefaces doesn't appear to be supported by a quarkus extension. As a result, you need to manually handle configure your project to make `native-image` work.

The exception indicates that `com.lowagie.text.Paragraph` is not on the classpath. Can you check if `org.eclipse.birt.runtime.3_7_1:com.lowagie.text` is on the classpath? If not the simplest thing to do would be to explicitly add it. If things still don't work please open an [issue under the quarkus project](https://github.com/quarkusio/quarkus/issues).

Note that quarkus initializes and links all classes at build time so if a class is not on the classpath native compilation will fail.

**Comment by ma-sharifi** [comment]
I'm sorry for not getting back to you sooner; I had struggled with another issue. 
`org.eclipse.birt.runtime.3_7_1:com.lowagie.text` was not on the classpath. I added the following dependency explicitly, but it did not work! I will open an issue under Quarkus project.
```
    <dependency>
      <groupId>org.eclipse.birt.runtime.3_7_1</groupId>
      <artifactId>com.lowagie.text</artifactId>
      <version>2.1.7</version>
    </dependency>
```

**Comment by ma-sharifi** [comment]
The problem was solved by changing the dependencies as described below:

```
<dependency>
    <groupId>org.apache.myfaces.core.extensions.quarkus</groupId>
    <artifactId>myfaces-quarkus</artifactId>
    <version>2.3-next-M7</version>
    <exclusions>
        <exclusion>
            <groupId>com.github.librepdf</groupId>
            <artifactId>openpdf</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>org.apache.poi</groupId>
    <artifactId>poi-ooxml</artifactId>
    <version>5.2.2</version>
    <exclusions>
        <exclusion>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml-schemas</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml-lite</artifactId>
        </exclusion>
    </exclusions>
</dependency>

<dependency>
    <groupId>org.apache.poi</groupId>
    <artifactId>poi-ooxml-full</artifactId>
    <version>5.2.3</version>
</dependency>
<dependency>
    <groupId>org.primefaces</groupId>
    <artifactId>primefaces</artifactId>
    <version>11.0.0</version>
    <exclusions>
        <exclusion>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
        </exclusion>
        <exclusion>
            <groupId>commons-fileupload</groupId>
            <artifactId>commons-fileupload</artifactId>
        </exclusion>
        <exclusion>
            <groupId>com.github.librepdf</groupId>
            <artifactId>openpdf</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>com.github.librepdf</groupId>
    <artifactId>openpdf</artifactId>
    <version>1.3.30</version>
</dependency>
<dependency>
    <groupId>org.apache.xmlgraphics</groupId>
    <artifactId>fop</artifactId>
    <version>2.8</version>
    <exclusions>
        <exclusion>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>fop-util</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>fop-events</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>fop-core</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>org.apache.xmlgraphics</groupId>
    <artifactId>fop-core</artifactId>
    <version>2.8</version>
    <exclusions>
        <exclusion>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-anim</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-bridge</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-extension</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.apache.xmlgraphics</groupId>
            <artifactId>batik-transcoder</artifactId>
        </exclusion>
    </exclusions>
</dependency>

```

**Comment by melloware** [comment]
Sorry I know this is closed but wanted to share what I discovered and how I fixed it to help the GraalVM team.

So the issue above is because PrimeFaces was doing this with iText `paragraph.add(new Paragraph(" "));` which is fine and would work for me in a SMALL native image.   

However trying to use a larger Native image it would fail with `Discovered unresolved method during parsing: com.lowagie.text.Paragraph.add(com.lowagie.text.Element)` exactly like above.  Looking at the iText code for Paragraph it looks like this signature.

```java
 public boolean add(Object o) {
```

Notice it takes `Object o` but the error above is `com.lowagie.text.Paragraph.add(com.lowagie.text.Element)`?  That got me thinking somehow on larger projects GraalVM for some reason can't tell that that Element is an Object and that is the correct signature. So to test it out in my Quarkiverse iText extension I added a new method.

https://github.com/quarkiverse/quarkus-itext/blob/85ee9007b25d67d1d3be8a8eb46e6cff8ce31ae9/runtime/src/main/java/com/lowagie/text/Paragraph.java#L225-L235

And then in my PrimeFaces Quarkus extension I substitute calling that method instead:

https://github.com/quarkiverse/quarkus-primefaces/blob/d08c6863d09f41fa714086d5cc0bfc7ee99e1c58/quarkus-primefaces/runtime/src/main/java/io/quarkus/primefaces/runtime/graal/SubstituteTreeTablePdfExporter.java#L14-L23

And sure enough now GraalVM compiles EVERY time fine.  

I hope this makes sense but it seems the (Object o) notation is what is throwing it off.

**Comment by zakkak** [comment]
My intuition is that the issue is not actually in GraalVM not being able to discover the `Paragraph.add` method, but you see this error because of https://github.com/oracle/graal/issues/6253.

I believe that the substitution you made helps you work around the issue because it makes `com.lowagie.text.List` and/or `com.lowagie.text.Image` (or some other class) unreachable, which I believe is/are triggering a `NoClassDefFoundError` when loaded at native-image build time.
