### ISSUE TITLE
Error:  org.apache.cayenne.di.DIRuntimeException: DI container has no binding for key <BindingKey: org.apache.cayenne.resource.ResourceLocator>

### ISSUE THREAD

**Issue by ma-sharifi** [oracle/graal#5716]
I'm getting the following error after my native image is built and run. 

Describe GraalVM and environment:

Java: 11
GraalVM: OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)
Apache Cayenne: 4.2.M3
Quarkus: 2.12.1.Final
OS: macOS , Apple M2

More details:

```
 org.apache.cayenne.di.DIRuntimeException: DI container has no binding for key <BindingKey: org.apache.cayenne.resource.ResourceLocator>
        at org.apache.cayenne.di.spi.DefaultInjector.getProvider(DefaultInjector.java:158)
        at org.apache.cayenne.di.spi.DefaultInjector.getInstance(DefaultInjector.java:139)
        at org.apache.cayenne.di.spi.FieldInjectingProvider.value(FieldInjectingProvider.java:103)
        at org.apache.cayenne.di.spi.FieldInjectingProvider.injectMember(FieldInjectingProvider.java:68)
        at org.apache.cayenne.di.spi.FieldInjectingProvider.injectMembers(FieldInjectingProvider.java:59)
        at org.apache.cayenne.di.spi.FieldInjectingProvider.injectMembers(FieldInjectingProvider.java:63)
        at org.apache.cayenne.di.spi.FieldInjectingProvider.get(FieldInjectingProvider.java:44)
        at org.apache.cayenne.di.spi.CustomProvidersProvider.get(CustomProvidersProvider.java:39)
        at org.apache.cayenne.di.spi.FieldInjectingProvider.get(FieldInjectingProvider.java:43)
        at org.apache.cayenne.di.spi.DefaultScopeProvider.get(DefaultScopeProvider.java:50)
        at org.apache.cayenne.di.spi.DefaultInjector.getInstance(DefaultInjector.java:134)
        at org.apache.cayenne.configuration.server.ServerRuntime.getDataDomain(ServerRuntime.java:154)
        at com.bluerock.cayenne.CayenneRuntime.init(CayenneRuntime.java:58)
        at com.bluerock.cayenne.CayenneRuntime_Bean.create(Unknown Source)
        at com.bluerock.cayenne.CayenneRuntime_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:111)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:32)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:32)
        at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:19)
        at com.bluerock.cayenne.CayenneRuntime_ClientProxy.arc$delegate(Unknown Source)
        at com.bluerock.cayenne.CayenneRuntime_ClientProxy.arc_contextualInstance(Unknown Source)
        at com.bluerock.cayenne.CayenneRuntime_ProducerMethod_objectContext_523945eae5f84ea1eae216d8b340eb33a010ad80_Bean.create(Unknown Source)
        at com.bluerock.cayenne.CayenneRuntime_ProducerMethod_objectContext_523945eae5f84ea1eae216d8b340eb33a010ad80_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.RequestContext.getIfActive(RequestContext.java:73)
        at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:28)
        at org.apache.cayenne.CayenneRuntime_ProducerMethod_objectContext_523945eae5f84ea1eae216d8b340eb33a010ad80_ClientProxy.arc$delegate(Unknown Source)
        at org.apache.cayenne.CayenneRuntime_ProducerMethod_objectContext_523945eae5f84ea1eae216d8b340eb33a010ad80_ClientProxy.select(Unknown Source)
        at com.bluerock.repositories.impl.ResourceBundleRepositoryImpl.findByLocale(ResourceBundleRepositoryImpl.java:30)
        at com.bluerock.repositories.impl.ResourceBundleRepositoryImpl_ClientProxy.findByLocale(Unknown Source)
        at com.bluerock.report.ReportBuilder.workbook(ReportBuilder.java:72)
        at com.bluerock.report.ReportBuilder_Subclass.workbook$$superforward1(Unknown Source)
        at com.bluerock.report.ReportBuilder_Subclass$$function$$9.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
        at com.bluerock.core.BluerockFilter.logInvocation(BluerockFilter.java:23)
        at com.bluerock.core.BluerockFilter_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at com.bluerock.report.ReportBuilder_Subclass.workbook(Unknown Source)
        at com.bluerock.report.ReportBuilder_ClientProxy.workbook(Unknown Source)
        at com.bluerock.api.impl.BluerockVersionApi.test(BluerockVersionApi.java:35)
        at com.bluerock.api.impl.BluerockVersionApi$quarkusrestinvoker$test_e377f432b9ec312ac61927bcb3c4c52be4853fa2.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:108)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:140)
        at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:49)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:17)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:7)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:429)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:407)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.doPermissionCheck(HttpAuthorizer.java:117)
        at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$2.accept(HttpAuthorizer.java:134)
        at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$2.accept(HttpAuthorizer.java:123)
        at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
        at io.smallrye.mutiny.helpers.UniCallbackSubscriber.onItem(UniCallbackSubscriber.java:77)
        at io.smallrye.mutiny.operators.uni.builders.DefaultUniEmitter.complete(DefaultUniEmitter.java:37)
        at io.quarkus.vertx.http.runtime.security.HttpAuthorizer$1$1$1.run(HttpAuthorizer.java:76)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:557)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)

```

**Comment by viniciusxyz** [comment]
@ma-sharifi 

Do you have a sample project?

Have you tried using javaagent to validate that there is no missing metadata in the build?

**Comment by ma-sharifi** [comment]
Thanks for your response.
Indeed. I use javaagent for every library I've added.
I don't have a sample project, but I can develop one.

**Comment by andrus** [comment]
From the Cayenne perspective, this error means that DI module auto-loading does not work within the Graal environment. So in your code you may need to manually add modules:

```java
ServerRuntime.builder().addModule(new ServerModule())
   // ...
  .build();
```

**Comment by viniciusxyz** [comment]
@ma-sharifi 

As soon as the project is available I can take a look, I'm waiting.

**Comment by ma-sharifi** [comment]
@viniciusxyz 
I pushed my code into my repository.
But now, I got a different error from cayenne :-(

https://github.com/ma-sharifi/quarkus-cayenne-native

**Comment by andrus** [comment]
@ma-sharifi 

> I got a different error from cayenne :-(

What is the new error?

**Comment by ma-sharifi** [comment]
@andrus 
The current error:

```
Caused by: java.util.ServiceConfigurationError: org.apache.cayenne.configuration.server.CayenneServerModuleProvider: Provider org.apache.cayenne.configuration.server.MainCayenneServerModuleProvider not found
        at java.base@17.0.5/java.util.ServiceLoader.fail(ServiceLoader.java:593)
        at java.base@17.0.5/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219)
        at java.base@17.0.5/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:117)
        at java.base@17.0.5/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
        at java.base@17.0.5/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
        at java.base@17.0.5/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
        at org.apache.cayenne.di.spi.ModuleLoader.loadModules(ModuleLoader.java:70)
        at org.apache.cayenne.di.spi.ModuleLoader.load(ModuleLoader.java:50)
        at org.apache.cayenne.configuration.server.ServerRuntimeBuilder.autoLoadedModules(ServerRuntimeBuilder.java:211)
        at org.apache.cayenne.configuration.server.ServerRuntimeBuilder.build(ServerRuntimeBuilder.java:199)
        at com.djem.cayenne.DatasourceProducer.init(DatasourceProducer.java:50)
        at com.djem.cayenne.DatasourceProducer_Bean.create(Unknown Source)
        at com.djem.cayenne.DatasourceProducer_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
        at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
        at com.djem.cayenne.DatasourceProducer_ClientProxy.arc$delegate(Unknown Source)
        at com.djem.cayenne.DatasourceProducer_ClientProxy.arc_contextualInstance(Unknown Source)
        at com.djem.cayenne.DatasourceProducer_ProducerMethod_objectContext_523945eae5f84ea1eae216d8b340eb33a010ad80_Bean.create(Unknown Source)
        at com.djem.cayenne.DatasourceProducer_ProducerMethod_objectContext_523945eae5f84ea1eae216d8b340eb33a010ad80_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.RequestContext.getIfActive(RequestContext.java:74)
        at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:30)
        at org.apache.cayenne.DatasourceProducer_ProducerMethod_objectContext_523945eae5f84ea1eae216d8b340eb33a010ad80_ClientProxy.arc$delegate(Unknown Source)
        at org.apache.cayenne.DatasourceProducer_ProducerMethod_objectContext_523945eae5f84ea1eae216d8b340eb33a010ad80_ClientProxy.selectOne(Unknown Source)
        at org.apache.cayenne.query.FluentSelect.selectOne(FluentSelect.java:165)
        at org.apache.cayenne.query.ObjectSelect.selectCount(ObjectSelect.java:681)
        at com.djem.ShipmentResource.count(ShipmentResource.java:38)
        at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        ... 17 more
```

**Comment by andrus** [comment]
Ok, it is choking on the Java ServiceLoader code that I mentioned. This will require looking your Graal assembly by someone who understands Graal.

**Comment by ma-sharifi** [comment]
@andrus 
May I ask why my application can't find this class "MainCayenneServerModuleProvider"? I could not find this class in its package: org.apache.cayenne.configuration.server.
I'm looking for a way to use injection manually.

**Comment by andrus** [comment]
@ma-sharifi Something to do with the assembly under Graal? It is most certainly a part of the cayenne-server.jar: 

https://github.com/apache/cayenne/blob/STABLE-4.2/cayenne-server/src/main/java/org/apache/cayenne/configuration/server/MainCayenneServerModuleProvider.java

**Comment by ma-sharifi** [comment]
No, I mean in the code. Provide dependency for the class in a different way.

**Comment by andrus** [comment]
@ma-sharifi not quite sure what you are after here. But in general dependency injection can not be replaced inside Cayenne (and from our preliminary tests, DI by itself is compatible with Graal). Module autoloading can be disabled and replaced though. Here is an extended example of what I've shown above:

```java
ServerRuntime.builder()

  // no autoloading, each module will need to be explicitly added below
  .disableModulesAutoLoading() 

  // add the main Cayenne module
  .addModule(new ServerModule())

   // ...
  .build();
```

**Comment by ma-sharifi** [comment]
@andrus 
I changed my code this way:

```
  @Inject ValueObjectTypeRegistry valueObjectTypeRegistry;
  @PostConstruct
  public void  init(){
    cayenneRuntime = ServerRuntime.builder()
        .disableModulesAutoLoading()
        .addConfig("cayenne-project.xml")
        .dataSource(DataSourceBuilder.url("jdbc:mysql://localhost:3308/cayenne")
                        .driver(com.mysql.cj.jdbc.Driver.class.getName())
                        .userName("root")
                        .password("root")
                        .pool(1,3).build()
        )
            .addModule(new ServerModule())
            .addModule(binder ->{
          binder.bind(ValueComparisonStrategyFactory.class).toInstance(new DefaultValueComparisonStrategyFactory(valueObjectTypeRegistry));
        })
        .build();
    objectContext  = cayenneRuntime.newContext();
  }
}
```
But I got stuck with this error.  Would it be possible to help me?
```
Caused by: org.apache.cayenne.di.DIRuntimeException: No applicable constructor is found for constructor injection in class 'org.apache.cayenne.reflect.generic.DefaultValueComparisonStrategyFactory'
        at org.apache.cayenne.di.spi.ConstructorInjectingProvider.initConstructor(ConstructorInjectingProvider.java:103)
        at org.apache.cayenne.di.spi.ConstructorInjectingProvider.<init>(ConstructorInjectingProvider.java:42)
        at org.apache.cayenne.di.spi.DefaultBindingBuilder.to(DefaultBindingBuilder.java:44)
        at org.apache.cayenne.configuration.server.ServerModule.configure(ServerModule.java:452)
        at org.apache.cayenne.di.spi.DefaultInjector.<init>(DefaultInjector.java:68)
        at org.apache.cayenne.di.DIBootstrap.createInjector(DIBootstrap.java:38)
        at org.apache.cayenne.di.DIBootstrap.createInjector(DIBootstrap.java:46)
        at org.apache.cayenne.configuration.CayenneRuntime.<init>(CayenneRuntime.java:79)
        at org.apache.cayenne.configuration.server.ServerRuntime.<init>(ServerRuntime.java:72)
        at org.apache.cayenne.configuration.server.ServerRuntimeBuilder.build(ServerRuntimeBuilder.java:207)
        at com.djem.cayenne.DatasourceProducer.init(DatasourceProducer.java:59)
        at com.djem.cayenne.DatasourceProducer_Bean.create(Unknown Source)
        at com.djem.cayenne.DatasourceProducer_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
        at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
        at com.djem.cayenne.DatasourceProducer_ClientProxy.arc$delegate(Unknown Source)
        at com.djem.cayenne.DatasourceProducer_ClientProxy.arc_contextualInstance(Unknown Source)
        at com.djem.cayenne.DatasourceProducer_ProducerMethod_objectContext_523945eae5f84ea1eae216d8b340eb33a010ad80_Bean.create(Unknown Source)
        at com.djem.cayenne.DatasourceProducer_ProducerMethod_objectContext_523945eae5f84ea1eae216d8b340eb33a010ad80_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.RequestContext.getIfActive(RequestContext.java:74)
        at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:30)
        at org.apache.cayenne.DatasourceProducer_ProducerMethod_objectContext_523945eae5f84ea1eae216d8b340eb33a010ad80_ClientProxy.arc$delegate(Unknown Source)
        at org.apache.cayenne.DatasourceProducer_ProducerMethod_objectContext_523945eae5f84ea1eae216d8b340eb33a010ad80_ClientProxy.selectOne(Unknown Source)
        at org.apache.cayenne.query.FluentSelect.selectOne(FluentSelect.java:165)
        at org.apache.cayenne.query.ObjectSelect.selectCount(ObjectSelect.java:681)
        at com.djem.ShipmentResource.count(ShipmentResource.java:38)
        at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        ... 17 more

```

**Comment by ma-sharifi** [comment]
Thanks, @andrus .
My problem was solved by adding the following line to build ServerRuntime.builder()

```
// no autoloading, each module will need to be explicitly added below
  .disableModulesAutoLoading() 
OR
  // add the main Cayenne module
  .addModule(new ServerModule())
```

And repeatedly using the following command to find new reflections:

```shell script
java -agentlib:native-image-agent=config-output-dir=./native/ -jar target/quarkus-app/quarkus-run.jar
```
The result is in [this](https://github.com/ma-sharifi/quarkus-cayenne-native) repository.
