### ISSUE TITLE
NativeImageResourceFileSystem: Path.toURI produces wrong URI; Files.isSameFile throws exception

### ISSUE THREAD

**Issue by kohlschuetter** [oracle/graal#5720]
When using classpath resources in a native-image binary, the native image resource filesystem behaves erratically, preventing its use (without workarounds) where Path URIs are being used, such as Jetty 12.

The URI produced from a native-image resource path by calling Path#toURI is not equivalent to the URI returned by Class#getResource(String).toURI:

The original URI is of the form `resource:/package/subpackage/file`.
Creating a `Path` from it (`Path.of(URI)`) yields a toString/toRealPath string of `/package/subpackage/file` and a file system of class `com.oracle.svm.core.jdk.resources.NativeImageResourceFileSystem`.
Calling `toURI` on the path results in a URI of the form `resource:file:///resources!/package/subpackage/file`.
Creating a Path from that URI results in a in a path string of `file:/resources!/package/subpackage/file`, which doesn't exist as per `Files.exists`.

Moreover, trying to compare these paths using Files.isSameFile results in a `java.nio.file.NoSuchFileException` being thrown:

```
java.nio.file.NoSuchFileException: /resources
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.resources.NativeImageResourceFileSystem.checkAccess(NativeImageResourceFileSystem.java:394)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.resources.NativeImageResourcePath.checkAccess(NativeImageResourcePath.java:728)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.resources.NativeImageResourcePath.isSameFile(NativeImageResourcePath.java:709)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.resources.NativeImageResourceFileSystemProvider.isSameFile(NativeImageResourceFileSystemProvider.java:194)
	at java.base@19.0.1/java.nio.file.Files.isSameFile(Files.java:1539)
	at ...
```

Steps to reproduce:

1. Have a main class (e.g., `TestClass`) in some package (e.g., `package.subpackage`) and a corresponding resource in the class path under `/package/subpackage/file`. The code below is to be run from the main method.
2. Get the resource URI via `URI uri = TestClass.class.getResource("file").toURI()`
3. Obtain the resource Path via
```
Path path;
try {
  path = Path.of(uri);
} catch (FileSystemNotFoundException e) {
  FileSystems.newFileSystem(uri, Collections.emptyMap()); // required for ZipFileSystem, for example.
  path = Path.of(uri);
}
```
4. Convert the path to URI again
```
URI uri2 = path.toURI();
Path path2 = Path.of(uri2);
```
5. Print uris and paths:
```
System.out.println(uri);
System.out.println(path);
System.out.println(uri2);
System.out.println(path2);
```
6. Compare paths:
```
System.out.println(path.equals(path2)); // only not `true` with native-image
System.out.println(Files.isSameFile(path, path2)); // only throws java.nio.file.NoSuchFileException with native-image
```

Compare the output between a Hotspot build (e.g., from a `jar` file (which uses `ZipFileSystem`), from a default file system via Eclipse, and a native-image build).

 Version info: 'GraalVM 22.3.0 Java 19 CE'
 Java version info: '19.0.1+10-jvmci-22.3-b08'
 C compiler: cc (apple, arm64, 14.0.0)
 Garbage collector: Serial GC

**Comment by jovanstevanovic** [comment]
Internally tracked as GR-43605.

**Comment by jovanstevanovic** [comment]
The fix is on the master.
