### ISSUE TITLE
NullPointerException in CompileQueue.defaultCompileFunction

### ISSUE THREAD

**Issue by dsilvasc** [oracle/graal#582]
Minimal repro with Scala source code:

```scala
object Foo {
  def main(args: Array[String]): Unit = {
    val bar = new Bar
    bar.load()
    bar.start { event =>
      event.length.toString
    }
  }
}

class Bar {
  @native def start(handler: String => String): Unit

  def load(): Unit = {
    System.loadLibrary("bar_jni")
  }
}
```

Compile it with Scala 2.12.6:

```bash
scalac Foo.scala
```

Create a reflection config file to make the `handler` function object argument to Bar.start callable from JNI:

```json
[
  {
    "name": "scala.Function1",
    "methods": [
      {
        "name": "apply",
        "parameterTypes": ["java.lang.Object"]
      }
    ]
  }
]
```

Compile with native-image:

```bash
native-image -H:+JNI -H:JNIConfigurationFiles=$PWD/reflectconfig -J-Xmx4G -J-Xms2G -Dio.netty.noUnsafe=true --no-server -cp .:$HOME/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-library/2.12.6/6bd975dd5ca2a50b94413b708389b892ae423181/scala-library-2.12.6.jar Foo
```

This crashes with:

```
   classlist:  18,447.98 ms
       (cap):     695.00 ms
       setup:   1,601.63 ms
  (typeflow):   4,967.12 ms
   (objects):   2,248.89 ms
  (features):      68.71 ms
    analysis:   7,400.74 ms
    universe:     325.99 ms
     (parse):   1,439.28 ms
    (inline):   1,377.65 ms
   (compile):     922.07 ms
     compile:   3,835.09 ms
fatal error: java.lang.NullPointerException
	at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:895)
	at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:881)
	at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:257)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image building with exit status 1
```

This was with GraalVM native-image version 1.0.0-rc4 on a Linux x86_64 docker container.

Dockerfile:

```
FROM amazonlinux:1
RUN yum install file which strace -y
RUN yum install  java-1.8.0-openjdk-devel gcc gdb git -y
RUN yum install zlib-devel -y
RUN yum install zlib-static gmp-static glibc-static -y

ADD graalvm-ce-1.0.0-rc4-linux-amd64.tar.gz /
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/graalvm-ce-1.0.0-rc4/bin

RUN mkdir /work
WORKDIR /work
```

**Comment by peter-hofer** [comment]
Thank you for reporting this issue, I have been able to reproduce it and have a fix that should be merged soon.

**Comment by Jiri-Kremser** [comment]
I am hitting the same issue with `graalvm-ce-1.0.0-rc8`.

reproducer:

```
git clone https://github.com/radanalyticsio/spark-operator
cd spark-operator && mvn clean install
native-image -H:Name=micro -J-Xmx4G -J-Xms4G -H:+JNI -H:EnableURLProtocols=https -H:+ReportUnsupportedElementsAtRuntime -jar ./target/spark-operator-*.jar

...
[spark-operator-0.2.1-SNAPSHOT:16909]    (compile):   7,453.18 ms
[spark-operator-0.2.1-SNAPSHOT:16909]      compile:  11,454.29 ms
fatal error: java.lang.NullPointerException
	at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:896)
	at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:882)
	at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:257)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Do you want me to open a new issue for this?
