### ISSUE TITLE
Error encountered while parsing com.oracle.svm.reflect.proxies.Proxy_18_UnwindExceptionToCallerStub_unwindExceptionToCaller.invoke(java.lang.Object, java.lang.Object[])

### ISSUE THREAD

**Issue by lburgazzoli** [oracle/graal#584]
I'm experimenting again with graal, scripting and native image and so I have created a very simple class like

```java
import org.graalvm.polyglot.Context;

public class Main {
    public static void main(String[] args) {
        Context context = Context.create();
    }
}
```

and building with a simple maven configuration like:

```xml
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <phase>process-classes</phase>
                        <configuration>
                            <executable>native-image</executable>
                            <workingDirectory>${build.directory}</workingDirectory>
                            <arguments>
                                <argument>-cp</argument>
                                <classpath/>
                                <argument>-H:+JNI</argument>
                                <argument>org.apache.camel.graalvm.example.Main</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

there is a failure like:

```
uild on Server(pid: 27267, port: 41879)
   classlist:     216.48 ms
       (cap):     596.92 ms
       setup:     854.22 ms
    analysis:   5,128.72 ms
error: Error encountered while parsing org.graalvm.compiler.hotspot.nodes.AllocaNode.alloca(int) 
Parsing context:
    parsing org.graalvm.compiler.hotspot.stubs.OutOfBoundsExceptionStub.createOutOfBoundsException(OutOfBoundsExceptionStub.java:81)
    parsing com.oracle.svm.reflect.proxies.Proxy_15_OutOfBoundsExceptionStub_createOutOfBoundsException.invoke(Unknown Source)
    parsing java.lang.reflect.Method.invoke(Method.java:498)
    parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:173)
    parsing com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Original error: java.lang.NullPointerException
    at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:296)
    at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
    at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
    at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
    at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:346)
    at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:500)
    at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
    at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

error: Error encountered while parsing com.oracle.svm.reflect.proxies.Proxy_18_UnwindExceptionToCallerStub_unwindExceptionToCaller.invoke(java.lang.Object, java.lang.Object[])
```

Adding --language:js fixes the issue but it should not fail even without the native-image flag

**Comment by olpaw** [comment]
Hi @lburgazzoli 

If you build an image that makes use of truffle you need to build with `--tool:truffle`.

**Comment by lburgazzoli** [comment]
Adding ```--tool:truffle``` fixes the issue but a better message would be really useful
