### ISSUE TITLE
 Issue with using js-scriptEngine in OPENjdk17

### ISSUE THREAD

**Issue by iikonne777** [oracle/graal#5840]
I am trying to use the following jars to enable me to perform java scripting in my application running on OpenJDK17. I would
appreciate it if someone in this group could point me to right direction. Also, is what am trying to do actually possible?
 
Here is the scenario.
 
1.	Jar files:
js-scriptengine-22.3.1.jar
truffle-api-22.3.1.jar
compiler-22.3.1.jar
graal-sdk-22.3.1.jar
 
2.	JDK – OpenJDK17
openjdk version "17.0.5" 2022-10-18
IBM Semeru Runtime Open Edition 17.0.5.0 (build 17.0.5+8)
Eclipse OpenJ9 VM 17.0.5.0 (build openj9-0.35.0, JRE 17 Windows Server 2019 amd64-64-Bit Compressed References 20221018_298 (JIT enabled, AOT enabled)
OpenJ9   - e04a7f6c1
OMR      - 85a21674f
JCL      - 32d2c409a33 based on jdk-17.0.5+8)
 
3.	Code snippet

Here is my code snippet

import javax.script.ScriptEngineManager;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineFactory;
import javax.script.SimpleScriptContext;

import com.oracle.truffle.js.scriptengine.GraalJSScriptEngine;
import com.oracle.truffle.js.scriptengine.GraalJSEngineFactory;

static void main(string args[]){
ScriptEngine engine = null;
engine =  GraalJSScriptEngine.create();   
ScriptEngineFactory factory = engine.getFactory();
}

 Also ..

import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.HostAccess;
import org.graalvm.polyglot.PolyglotException;
import org.graalvm.polyglot.Source;
import org.graalvm.polyglot.Value;

public static void main(args[]){
	Context context = Context.create(); Value result = context.eval("js",
	 "40+2"); System.out.print("Answer->[" + result.asInt() == 42 + "]");
	  log.info("Answer->[" + result.asInt() == 42 + "]");
}
			
 
4.	Then I got the following exception
java.lang.NoClassDefFoundError: jdk.vm.ci.services.Services
        at org.graalvm.libgraal.LibGraal.<clinit>(LibGraal.java:71)
        at org.graalvm.compiler.truffle.runtime.hotspot.libgraal.LibGraalTruffleRuntimeAccess.getPriority(LibGraalTruffleRuntimeAccess.java:44)
        at com.oracle.truffle.api.Truffle.selectTruffleRuntimeAccess(Truffle.java:90)
        at com.oracle.truffle.api.Truffle$1.run(Truffle.java:131)
        at com.oracle.truffle.api.Truffle$1.run(Truffle.java:108)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
        at com.oracle.truffle.api.Truffle.initRuntime(Truffle.java:108)
        at com.oracle.truffle.api.Truffle.<clinit>(Truffle.java:63)
        at com.oracle.truffle.api.impl.Accessor.getTVMCI(Accessor.java:1365)
        at com.oracle.truffle.api.impl.Accessor$Constants.<clinit>(Accessor.java:1245)
        at com.oracle.truffle.api.impl.Accessor.engineSupport(Accessor.java:1306)

**Comment by oubidar-Abderrahim** [comment]
Hi, would you mind sharing this code as a repo on GitHub with steps to reproduce? that would be helpful

**Comment by oubidar-Abderrahim** [comment]
Any updates?

**Comment by oubidar-Abderrahim** [comment]
I would advise using GraalVM CE instead as your default JVM; this will help you avoid a lot of similar issues. I'll close this ticket for now, if you still need assistance you can reopen it and submit a complete reproducer. Thank you.

**Comment by walecharohit** [comment]
is this concluded ??
