### ISSUE TITLE
VS Code issue when debugging JS code with GraalVM

### ISSUE THREAD

**Issue by iannakin** [oracle/graal#5844]
Hi,
(This issue is a follow-up of this conversation : https://graalvm.slack.com/archives/CN9L59P61/p1674771213399709)

My environment : 
```
Windows 10 Pro
GraalVM / Java17 / CE 22.3.1 (same with CE 23.0.0-dev)
Kotlin with IntelliJ
VS Code (1.74.3 and 1.75-insider)

```
I encounter an issue when debugging with VS Code. I don't know if this issue is on the GraalVM side or on VS Code side.
Basically I can't make the debugger to show properly the content of a simple array, or even the global "this" variable. I initially thought it was an issue only with host objects provided by ProxyObject, but after a lot of painful testing, I narrowed it down to a very basic example where even native JS arrays / objects can't be debugged correctly. I get a weird error in VS Code : 

![image](https://user-images.githubusercontent.com/6087032/215102546-7b070fa2-ad05-4385-b39f-339e45845f61.png)

Here a kotlin code to reproduce:
```
val builder = Context.newBuilder("js").allowAllAccess(true).allowHostAccess(HostAccess.ALL)
    builder.option("inspect", "4242").option("inspect.Path", "debug").option("inspect.Suspend", "false").option("inspect.Internal", "true")
    builder.build().use { context ->
        val testCode = """
                const arrayFromGuest = ["foo"];
                debugger;  // I want to inspect any variable at that point
        """.trimIndent()
        val arrayFromHost = context.eval("js", "['bar']");
        context.getBindings("js").putMember("arrayFromHost", arrayFromHost)
        context.eval("js", testCode)
    }
```
My VS Code launch.json configuration is like this :
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "EfficyJS",
      "type": "node",
      "request": "attach",
      "address": "127.0.0.1",
      "timeout": 60000,
      "port": 4242,
      "trace": true,
      "websocketAddress": "ws://127.0.0.1:4242/debug",
    }
  ]
}
```

Thanks for your feedback !

**Comment by entlicher** [comment]
The error is strange an it comes from the `vscode-js-debug` extension:
```
Error processing variables: TypeError: Cannot read properties of undefined (reading 'length')
        at t.trimEnd (/snap/code/122/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1072270)
        at /snap/code/122/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:861162
        at h (/snap/code/122/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:862120)
        at d (/snap/code/122/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:860195)
        at t.previewRemoteObject (/snap/code/122/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:865356)
        at H.toDap (/snap/code/122/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:970003)
        at H.toDap (/snap/code/122/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:972309)
        at /snap/code/122/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:978571
        at Array.map (<anonymous>)
        at n.getVariables (/snap/code/122/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:978561)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async F._onVariables (/snap/code/122/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:840979)
        at async t.default._onMessage (/snap/code/122/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1090234)
```
Everything is displayed as expected when Chrome Inspector is attached (when you paste `devtools://devtools/bundled/js_app.html?ws=127.0.0.1:4242/debug` to Chrome or Chromium browser).

In VS Code it's best to use DAP protocol:
```
builder.option("dap", "4242").option("dap.Suspend", "true").option("dap.Internal", "true");
```
and configuration in `launch.json`:
```
        {
            "type": "node",
            "name": "DAP Attach",
            "request": "attach",
            "debugServer": 4242
        }
```
Then again, everything is displayed fine for me.

It looks like the `vscode-js-debug` extension does something strange and asks for length of an undefined object.

**Comment by iannakin** [comment]
when I change the debug options with the line you provide, I get the following error : 

```
java.lang.Exception: Output operation write(B[II) failed for com.oracle.truffle.tools.dap.server.OutputHandler$ListeneableOutputStream@4c9f8c13.
	at org.graalvm.truffle/com.oracle.truffle.api.impl.DispatchOutputStream$OutputStreamList.handleException(DispatchOutputStream.java:274)
	at org.graalvm.truffle/com.oracle.truffle.api.impl.DispatchOutputStream$OutputStreamList.writeMulti(DispatchOutputStream.java:216)
	at org.graalvm.truffle/com.oracle.truffle.api.impl.DispatchOutputStream.write(DispatchOutputStream.java:130)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)
	at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:313)
	at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:318)
	at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:160)
	at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:248)
	at java.base/java.io.BufferedWriter.flush(BufferedWriter.java:257)
	at java.base/java.io.PrintWriter.newLine(PrintWriter.java:567)
	at java.base/java.io.PrintWriter.println(PrintWriter.java:710)
	at java.base/java.io.PrintWriter.println(PrintWriter.java:821)
	at com.oracle.truffle.tools.dap.server.DebugProtocolServerImpl.start(DebugProtocolServerImpl.java:588)
	at com.oracle.truffle.tools.dap.instrument.DAPInstrument.launchServer(DAPInstrument.java:117)
	at com.oracle.truffle.tools.dap.instrument.DAPInstrument.onCreate(DAPInstrument.java:90)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.TruffleInstrument$Env.onCreate(TruffleInstrument.java:661)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler$InstrumentClientInstrumenter.create(InstrumentationHandler.java:2048)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler.createInstrument(InstrumentationHandler.java:253)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentAccessor$InstrumentImpl.createInstrument(InstrumentAccessor.java:123)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotInstrument.ensureCreated(PolyglotInstrument.java:181)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineImpl.ensureInstrumentsCreated(PolyglotEngineImpl.java:670)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineImpl.createInstruments(PolyglotEngineImpl.java:664)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineImpl.<init>(PolyglotEngineImpl.java:328)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotImpl.buildEngine(PolyglotImpl.java:288)
	at org.graalvm.sdk/org.graalvm.polyglot.Engine$Builder.build(Engine.java:625)
	at org.graalvm.sdk/org.graalvm.polyglot.Context$Builder.build(Context.java:1851)
	at com.efficy.test.applications.scripting.TestGraalJSKotlinKt.main(TestGraalJSKotlin.kt:21)
	at com.efficy.test.applications.scripting.TestGraalJSKotlinKt.main(TestGraalJSKotlin.kt)
Caused by: java.lang.NullPointerException: Cannot invoke "com.oracle.truffle.tools.dap.types.DebugProtocolClient.output(com.oracle.truffle.tools.dap.types.OutputEvent$EventBody)" because the return value of "com.oracle.truffle.tools.dap.server.ExecutionContext.getClient()" is null
	at com.oracle.truffle.tools.dap.server.DebugProtocolServerImpl$ConsoleOutputListener.outputText(DebugProtocolServerImpl.java:696)
	at com.oracle.truffle.tools.dap.server.OutputHandler$ListeneableOutputStream.wl(OutputHandler.java:92)
	at com.oracle.truffle.tools.dap.server.OutputHandler$ListeneableOutputStream.write(OutputHandler.java:78)
	at org.graalvm.truffle/com.oracle.truffle.api.impl.DispatchOutputStream$OutputStreamList.writeMulti(DispatchOutputStream.java:210)
	... 26 more
[Graal DAP] Starting server and listening on localhost/127.0.0.1:4242
```
My new code is : 
```
val builder = Context.newBuilder("js").allowAllAccess(true).allowHostAccess(HostAccess.ALL)
    builder.option("dap", "4242").option("dap.Suspend", "true").option("dap.Internal", "true");
    builder.build().use { context ->
        val testCode = """
               console.log("foo");
        """.trimIndent()
        context.getBindings("js").putMember("errorLauncher", ErrorLauncher(context))
        context.eval("js", testCode)
    }
```

Do I miss something ?
Thanks !

**Comment by entlicher** [comment]
This NullPointerException was fixed already, see https://github.com/oracle/graal/issues/5143
Please upgrade the GraalVM.

**Comment by iannakin** [comment]
Everything works now, thanks !

**Comment by smokeelow** [comment]
@entlicher  Getting this error again using GraaVM 25.0.0 

```
Caused by: java.lang.NullPointerException: Cannot invoke "com.oracle.truffle.tools.dap.types.DebugProtocolClient.output(com.oracle.truffle.tools.dap.types.OutputEvent$EventBody)" because "debugClient" is null

```

<img width="2141" height="271" alt="Image" src="https://github.com/user-attachments/assets/fe6fa148-eb50-4f89-8404-307ee6c1bc85" />
