### ISSUE TITLE
Resource bundle class without a nullary constructor

### ISSUE THREAD

**Issue by koutheir** [oracle/graal#5846]
When a resource bundle is included in a native image, why does `native-image` assume that all resource bundle classes have nullary constructors (constructors without arguments)?

I couldn't find this restriction documented anywhere.

This assumption is at `RuntimeReflection.registerForReflectiveInstantiation()` when called from `LocalizationSupport.prepareClassResourceBundle()`.

For example, using the following `resource-config.json`:
```json
{
  "resources":{},
  "bundles":[{
      "name":"...MyBundle",
      "classNames":["...SomeClass"]
    }]
}
```

If `SomeClass` does not define a nullary constructor, then the following `native-image` build fails:
```plain
Fatal error: java.lang.IllegalArgumentException: Class ...SomeClass cannot be instantiated reflectively . It does not have a nullary constructor.
	at org.graalvm.sdk/org.graalvm.nativeimage.hosted.RuntimeReflection.registerForReflectiveInstantiation(RuntimeReflection.java:148)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.localization.LocalizationSupport.prepareClassResourceBundle(LocalizationSupport.java:166)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.jdk.localization.LocalizationFeature.prepareClassResourceBundle(LocalizationFeature.java:534)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ResourcesFeature$ResourcesRegistryImpl.lambda$addClassBasedResourceBundle$3(ResourcesFeature.java:167)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ConditionalConfigurationRegistry.registerConditionalConfiguration(ConditionalConfigurationRegistry.java:43)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ResourcesFeature$ResourcesRegistryImpl.addClassBasedResourceBundle(ResourcesFeature.java:167)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.configure.ResourceConfigurationParser.parseBundle(ResourceConfigurationParser.java:119)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.configure.ResourceConfigurationParser.parseTopLevelObject(ResourceConfigurationParser.java:93)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.configure.ResourceConfigurationParser.parseAndRegister(ResourceConfigurationParser.java:51)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.configure.ConfigurationParser.parseAndRegister(ConfigurationParser.java:71)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.config.ConfigurationParserUtils.doParseAndRegister(ConfigurationParserUtils.java:125)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.config.ConfigurationParserUtils.lambda$parseAndRegisterConfigurations$1(ConfigurationParserUtils.java:84)
	at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:491)
	at java.base/java.util.stream.IntPipeline.sum(IntPipeline.java:449)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.config.ConfigurationParserUtils.parseAndRegisterConfigurations(ConfigurationParserUtils.java:86)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ResourcesFeature.beforeAnalysis(ResourcesFeature.java:195)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:762)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:85)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:762)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:602)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:559)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:405)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:582)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:129)
```

**GraalVM and environment:**
 - GraalVM version: **EE 22.3.0**
 - JDK major version: **11**
 - OS: **Linux**
 - Architecture: **AMD64**

**Comment by koutheir** [comment]
The issue #2652 might be related.

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, we'll take a look into it shortly

**Comment by oubidar-Abderrahim** [comment]
Hi @koutheir , could you please share a small reproducer to illustrate this issue? Thank you

**Comment by oubidar-Abderrahim** [comment]
Tracked internally on GR 44078

**Comment by AvocadoMoon** [comment]
I'm experiencing a similar issue where a resource bundle within a third party library. It uses a resource bundle controller as a factory for the resource bundles, with custom logic to provide input streams to the resource bundle | [[Problem Class in Question](https://github.com/sbmlteam/jsbml/blob/master/core/src/org/sbml/jsbml/util/XMLResourceBundleControl.java)]. The solution proposed in the [issue](https://github.com/oracle/graal/issues/2652) referenced earlier doesn't seem to work. Is there any new progress on this problem that points to a solution?
