### ISSUE TITLE
Stacktrace creation for PolyglotException fails on windows

### ISSUE THREAD

**Issue by hanzr** [oracle/graal#587]
I'm running graaljs on a stock jdk on windows, as described in issue #469.
When a script is loaded from the classpath, and an exception occurs, the stacktrace creation for the PolyglotException fails, due to an unexpected char in the source's path..

```
package example;

import java.net.URL;

import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.PolyglotException;
import org.graalvm.polyglot.Source;

public class Bug {

  public static void main(String[] args) throws Exception {

    //temporary workaround for windows
    System.getProperties().put("js.home", ".");
    System.getProperties().put("regex.home", ".");

    Context context = Context.create("js");

    // load sourcefile from the classpath
    // This is a file in our package, contains just 'exit();'
    URL resource = Bug.class.getResource("test.js");
    Source source = Source.newBuilder("js", resource).build();

    try {
      context.eval(source);
    } catch (PolyglotException exc) {
      exc.printStackTrace();
    }
  }

}
```

The result:

org.graalvm.polyglot.PolyglotException
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:/C:/dev/workspaces/eclipse-photon/Graal/bin/example/test.js
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.oracle.truffle.api.vm.PolyglotExceptionFrame.formatSource(PolyglotExceptionFrame.java:182)
	at com.oracle.truffle.api.vm.PolyglotExceptionFrame.toStringImpl(PolyglotExceptionFrame.java:107)
	at com.oracle.truffle.api.vm.PolyglotExceptionImpl.printStackTrace(PolyglotExceptionImpl.java:215)
	at com.oracle.truffle.api.vm.PolyglotExceptionImpl.printStackTrace(PolyglotExceptionImpl.java:192)
	at org.graalvm.polyglot.PolyglotException.printStackTrace(PolyglotException.java:87)
	at example.Bug.main(Bug.java:27)

**Comment by chumer** [comment]
Thanks for the detailed report! We will have a look.

**Comment by olegchir** [comment]
It should be fixed by latest commits in #469. Will have a look on this week

**Comment by hanzr** [comment]
I'm using the jars from rc5, this fix apparantly didn't make it inthere yet.. I'll try again with rc6 soon ;)

**Comment by boris-spas** [comment]
It sure looks a lot like it :)
@hanzr would you like to confirm this is not an issue with rc6 before we mark as duplicate?

**Comment by hanzr** [comment]
Yes I'll check and let you know

**Comment by hanzr** [comment]
Re-tested on rc6. The workaround with System.getProperties() is no longer needed, but the stacktrace creation still fails.

**Comment by hanzr** [comment]
Retested with 19.0.0, problem is gone. Closing the issue.
