### ISSUE TITLE
ExceptionInInitializerError in Java using Graalvm 

### ISSUE THREAD

**Issue by AkashItorix** [oracle/graal#5948]
- GraalVM version or : OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 11.0.17+8-jvmci-22.3-b08)
 - JDK version: JDK11
 - OS and OS Version: Mac Ventura 13.0.1
 - The output of `java -Xinternalversion`:OpenJDK 64-Bit Server VM (11.0.17+8-jvmci-22.3-b08) for bsd-aarch64 JRE (11.0.17+8-jvmci-22.3-b08), built on Oct 19 2022 01:47:06 by "graal1" with clang Apple LLVM 12.0.0 (clang-1200.0.32.29)

I was using Nashorn to convert javascript output to java objects but since it was deprecated I was trying to use the support provided by graalvm to access the javascript objects.But getting initializer exception when trying to access the Context object.I'm setting the system property "polyglot.js.nashorn-compat" as true aswell.This is the code snippet that I was trying.
<img width="916" alt="image" src="https://user-images.githubusercontent.com/105375362/217918740-9abe7b37-9fe5-4984-acb8-40f9ef3c8eac.png">

**Expected behavior**
The Context object build itself is not happening.
I'm attaching the logs as well.

java.lang.ExceptionInInitializerError
	at org.graalvm.truffle/com.oracle.truffle.api.impl.Accessor.engineSupport(Accessor.java:1306)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryAccessor.engineAccessor(LibraryAccessor.java:57)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.loadExternalDefaultProviders(LibraryFactory.java:439)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.getExternalDefaultProviders(LibraryFactory.java:430)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.initDefaultExports(LibraryFactory.java:221)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.<init>(LibraryFactory.java:216)
	at org.graalvm.truffle/com.oracle.truffle.api.library.DynamicDispatchLibraryGen.<init>(DynamicDispatchLibraryGen.java:32)
	at org.graalvm.truffle/com.oracle.truffle.api.library.DynamicDispatchLibraryGen.<clinit>(DynamicDispatchLibraryGen.java:24)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.loadGeneratedClass(LibraryFactory.java:791)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.resolveImpl(LibraryFactory.java:740)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.resolve(LibraryFactory.java:733)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.<init>(LibraryFactory.java:210)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen.<init>(InteropLibraryGen.java:175)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen.<clinit>(InteropLibraryGen.java:166)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.loadGeneratedClass(LibraryFactory.java:791)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.resolveImpl(LibraryFactory.java:740)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.resolve(LibraryFactory.java:733)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibrary.<clinit>(InteropLibrary.java:2873)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch.<clinit>(PolyglotValueDispatch.java:156)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotImpl.initialize(PolyglotImpl.java:166)
	at org.graalvm.sdk/org.graalvm.polyglot.impl.AbstractPolyglotImpl.setConstructors(AbstractPolyglotImpl.java:271)
	at org.graalvm.sdk/org.graalvm.polyglot.Engine$1.loadAndValidateProviders(Engine.java:940)
	at org.graalvm.sdk/org.graalvm.polyglot.Engine$1.run(Engine.java:900)
	at org.graalvm.sdk/org.graalvm.polyglot.Engine$1.run(Engine.java:894)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.graalvm.sdk/org.graalvm.polyglot.Engine.initEngineImpl(Engine.java:894)
	at org.graalvm.sdk/org.graalvm.polyglot.Engine$ImplHolder.<clinit>(Engine.java:139)
	at org.graalvm.sdk/org.graalvm.polyglot.Engine.getImpl(Engine.java:363)
	at org.graalvm.sdk/org.graalvm.polyglot.Engine$Builder.build(Engine.java:621)
	at org.graalvm.sdk/org.graalvm.polyglot.Context$Builder.build(Context.java:1851)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
	at org.graalvm.truffle/com.oracle.truffle.api.impl.Accessor$Constants.<clinit>(Accessor.java:1245)
	... 42 more

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reaching out about this, could you please share a complete reproducer to illustrate this issue? Thank you

**Comment by oubidar-Abderrahim** [comment]
Hi, Any updates on the reproducer?
