### ISSUE TITLE
[GR-44186] `native-image --expert-options-all`  throws error on `23.0.0-dev ` builds

### ISSUE THREAD

**Issue by sureshg** [oracle/graal#5949]
Using the latest version of GraalVM dev builds

```
$ native-image --version
GraalVM 23.0.0-dev Java 19.0.1+10-jvmci-23.0-b04 CE (Java Version 19.0.1+10-jvmci-23.0-b04)
```

Error is, 
```
$  native-image --expert-options-all
Exception in thread "main" java.util.NoSuchElementException: No value present
        at java.base@19.0.1/java.util.Optional.orElseThrow(Optional.java:377)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.completeImageBuild(NativeImage.java:1126)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.build(NativeImage.java:1553)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1521)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.main(NativeImage.java:1495)
```

**Comment by fniephaus** [comment]
Thanks for raising this, @sureshg!
