### ISSUE TITLE
Unable to make Kerberos Authenticated http calls due to GSSManager Oid issue

### ISSUE THREAD

**Issue by louis2845** [oracle/graal#5950]
Issue is caused by https://github.com/oracle/graal/issues/4700

GraalVM and environment:

OS: Linux RHEL 8
GraalVM version 22.3.1 EE
JDK: 17

GSSException: Unsupported mechanism requested: 1.2.840.113554.1.2.2
at java.security.jgss@17.0.6/sun.security.jgss.ProviderList.getMechFactory(ProviderList.java:199)
at java.security.jgss@17.0.6/sun.security.jgss.ProviderList.getMechFactory(ProviderList.java:166)
at java.security.jgss@17.0.6/sun.security.jgss.GSSManagerImpl.getNameElement(GSSManagerImpl.java:183)
at java.security.jgss@17.0.6/sun.security.jgss.GSSNameImpl.getElement(GSSNameImpl.java:469)
at java.security.jgss@17.0.6/sun.security.jgss.GSSNameImpl.init(GSSNameImpl.java:202)
at java.security.jgss@17.0.6/sun.security.jgss.GSSNameImpl.<init>(GSSNameImpl.java:171)
at java.security.jgss@17.0.6/sun.security.jgss.GSSNameImpl.<init>(GSSNameImpl.java:152)
at java.security.jgss@17.0.6/sun.security.jgss.GSSManagerImpl.createName(GSSManagerImpl.java:109)
at java.security.jgss@17.0.6/sun.net.www.protocol.http.spnego.NegotiatorImpl.init(NegotiatorImpl.java:95)
at java.security.jgss@17.0.6/sun.net.www.protocol.http.spnego.NegotiatorImpl.<init>(NegotiatorImpl.java:123)
at java.base@17.0.6/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base@17.0.6/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at java.base@17.0.6/sun.net.www.protocol.http.Negotiator.getNegotiator(Negotiator.java:65)
at java.base@17.0.6/sun.net.www.protocol.http.NegotiateAuthentication.isSupported(NegotiateAuthentication.java:120)
at java.base@17.0.6/sun.net.www.protocol.http.AuthenticationHeader.parse(AuthenticationHeader.java:201)
at java.base@17.0.6/sun.net.www.protocol.http.AuthenticationHeader.<init>(AuthenticationHeader.java:144)
at java.base@17.0.6/sun.net.www.protocol.http.AuthenticationHeader.<init>(AuthenticationHeader.java:124)
at java.base@17.0.6/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1818)
at java.base@17.0.6/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
at java.base@17.0.6/java.net.URLConnection.getContent(URLConnection.java:753)
at java.base@17.0.6/sun.net.www.protocol.https.HttpsURLConnectionImpl.getContent(HttpsURLConnectionImpl.java:404)

Like the attached issue it is difficult to recreate the environment due to needing to set up an entire Active Directory / Kerberos environment - but the attached code should recreate the problem

Seems like the code below should populate providers but it doesn't

```
    public GSSManagerImpl(GSSCaller caller) {
        list = new ProviderList(caller, USE_NATIVE);
    }
```

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this issue, please share a complete reproducer of this issue. with steps to reproduce. Thank you

**Comment by louis2845** [comment]
I think I commented on #4700 that there should be all you need there to recreate the problem. There is a java class and steps to compile it into native. Is there anything else you'd like me to provide?

**Comment by oubidar-Abderrahim** [comment]
Running the Sample class shared on #4700 throws the following
```
Exception in thread "main" GSSException: Invalid name provided (Mechanism level: KrbException: Cannot locate default realm)
	at java.security.jgss/sun.security.jgss.krb5.Krb5NameElement.getInstance(Krb5NameElement.java:127)
	at java.security.jgss/sun.security.jgss.krb5.Krb5MechFactory.getNameElement(Krb5MechFactory.java:99)
	at java.security.jgss/sun.security.jgss.GSSManagerImpl.getNameElement(GSSManagerImpl.java:184)
	at java.security.jgss/sun.security.jgss.GSSNameImpl.getElement(GSSNameImpl.java:469)
	at java.security.jgss/sun.security.jgss.GSSNameImpl.init(GSSNameImpl.java:202)
	at java.security.jgss/sun.security.jgss.GSSNameImpl.<init>(GSSNameImpl.java:171)
	at java.security.jgss/sun.security.jgss.GSSNameImpl.<init>(GSSNameImpl.java:152)
	at java.security.jgss/sun.security.jgss.GSSManagerImpl.createName(GSSManagerImpl.java:109)
	at Sample.main(Sample.java:7)
```
which doesn't seem to be a bug on GraalVM.

**Comment by louis2845** [comment]
I see, I think you may need to specify the krb5 config. Sorry for this, I will get back to you later today

**Comment by louis2845** [comment]
It seems as though you've actually gotten past the point which is causing an issue for me:

me - > at java.security.jgss/sun.security.jgss.GSSManagerImpl.getNameElement(GSSManagerImpl.java:183)
you -> at java.security.jgss/sun.security.jgss.GSSManagerImpl.getNameElement(GSSManagerImpl.java:184)

Looking at the code provided in the previous ticket:

javac Sample.java
java -agentlib:native-image-agent=config-output-dir=META-INF/native-image Sample
native-image --no-fallback Sample

The middle java call should fail where you are seeing an exception without proper Kerberos configuration.

Were you definitely running the native image?

javac Sample.java
native-image --no-fallback Sample
./sample

I've just tried the above and am still seeing:

Exception in thread "main" GSSException: Unsupported mechanism requested: 1.2.840.113554.1.2.2
	at java.security.jgss@17.0.6/sun.security.jgss.ProviderList.getMechFactory(ProviderList.java:199)
	at java.security.jgss@17.0.6/sun.security.jgss.ProviderList.getMechFactory(ProviderList.java:166)
	at java.security.jgss@17.0.6/sun.security.jgss.GSSManagerImpl.getNameElement(GSSManagerImpl.java:183)
	at java.security.jgss@17.0.6/sun.security.jgss.GSSNameImpl.getElement(GSSNameImpl.java:469)
	at java.security.jgss@17.0.6/sun.security.jgss.GSSNameImpl.init(GSSNameImpl.java:202)
	at java.security.jgss@17.0.6/sun.security.jgss.GSSNameImpl.<init>(GSSNameImpl.java:171)
	at java.security.jgss@17.0.6/sun.security.jgss.GSSNameImpl.<init>(GSSNameImpl.java:152)
	at java.security.jgss@17.0.6/sun.security.jgss.GSSManagerImpl.createName(GSSManagerImpl.java:109)
	at Sample.main(Sample.java:9)

**Comment by oubidar-Abderrahim** [comment]
Tracked internally on GR 44320

**Comment by vjovanov** [comment]
Thank you for a great reproducer! To make this work you need to add the flag `-H:AdditionalSecurityProviders=sun.security.jgss.SunProvider` the image build. 

We will work to provide a better UX around this feature.

**Comment by autodidacticon** [comment]
Where can we find definitive reference to this flag?

**Comment by vjovanov** [comment]
What is a definitive reference? We will document this better in the upcoming releases, but first, we need to revisit the defaults. I feel this one should be included by default.

**Comment by autodidacticon** [comment]
@vjovanov Where is the documentation to the flag `-H:AdditionalSecurityProviders`?

**Comment by vjovanov** [comment]
I wish I had a good answer. We will be improving this feature for JDK 23. Until then the best I can say is that this is the list of possible values in the JDK is:
```
['sun.security.provider.Sun', 'sun.security.rsa.SunRsaSign', 'sun.security.ec.SunEC', 'sun.security.ssl.SunJSSE', 'com.sun.crypto.provider.SunJCE', 'sun.security.jgss.SunProvider', 'com.sun.security.sasl.Provider', 'org.jcp.xml.dsig.internal.dom.XMLDSigRI', 'sun.security.smartcardio.SunPCSC', 'sun.security.provider.certpath.ldap.JdkLDAP', 'com.sun.security.sasl.gsskerb.JdkSASL']
```

I got this by running `sun.security.jca.Providers.getProviderList()` and inspecting class names.

**Comment by aanavaneeth** [comment]
In my case, graalvm is not respecting `sun.security.jgss.native=true`.  (ref: [native gss](https://docs.oracle.com/en/java/javase/11/security/accessing-native-gss-api.html#GUID-88A42A9C-AC8B-426E-A8A7-B30518C2162A))

**Comment by vjovanov** [comment]
Thank you very much for reporting the issue! We will look into it and see why it happens.

**Comment by yogeshkumargeek** [comment]
Hey @vjovanov , Facing same issue while implementing kerberos auth with native image in micronaut. 
Can you please here ? 
It's been quite some time for this issue .Please expedite this

**Comment by aanavaneeth** [comment]
If we have a way to create the instance of gssmanager by passing the "native" as parameter rather than using jvm arguments can help I guess. That would be a jdk change rather than graalvm. However, graalvm handling this also works. I wish they prioritise this. This is blocking a lot of enterprise software from using graalvm native compilation feature.

**Comment by vjovanov** [comment]
@jovanstevanovic is working in this area now so we should be able to provide a fix in the next release.

**Comment by aanavaneeth** [comment]
Wow that's a great news!! Thank you so much!!

**Comment by jovanstevanovic** [comment]
No worries. I can have a look.

**Comment by yogeshkumar-1234** [comment]
Hey @vjovanov , is there any alternative present at the moment for this kerberos auth issue in native image ?

**Comment by jovanstevanovic** [comment]
@yogeshkumar-1234 I've managed to make it work locally. Try the app but with the following command:
`native-image -H:+UnlockExperimentalVMOptions -H:AdditionalSecurityProviders=sun.security.jgss.SunProvider Sample`

**Comment by jovanstevanovic** [comment]
@yogeshkumar-1234 the solution in the [comment](https://github.com/oracle/graal/issues/5950#issuecomment-1746835465) does not help you?

**Comment by aanavaneeth** [comment]
I tried it sometimes back. It didn't work for me. I can check once again.

**Comment by yogeshkumar-1234** [comment]
@vjovanov It didn't work for me

**Comment by yogeshkumar-1234** [comment]
It didn't work for me > @yogeshkumar-1234 the solution in the [comment](https://github.com/oracle/graal/issues/5950#issuecomment-1746835465) does not help you?

**Comment by jovanstevanovic** [comment]
Okay, just to double-check.

**Comment by jovanstevanovic** [comment]
I tried running it on the latest master, and with the added flag (AdditionalSecurityProviders=...), everything works fine. So I don’t see any bug on our side.

The only thing we could improve in cases like this is the logging, so users can clearly see that the issue is due to missing providers, rather than something else. But again, that’s not strictly related to this specific problem.

@aanavaneeth @yogeshkumar-1234 For the issue you’re referring to, I left a comment with all the missing details. It also wasn’t a bug on the Native Image side.
