### ISSUE TITLE
AssertionError at lookupEncodedGraph (SubstrateReplacements.java:237)

### ISSUE THREAD

**Issue by koutheir** [oracle/graal#5998]
# GraalVM Native Image Error Report

## Build Output

```
========================================================================================================================
GraalVM Native Image: Generating 'hello' (executable)...
========================================================================================================================
[1/8] Initializing...
                                                                                    (0.0s @ 0.26GB)
```

## Stack Trace

```java
java.lang.AssertionError
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.graal.meta.SubstrateReplacements$1.lookupEncodedGraph(SubstrateReplacements.java:237)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.decode(PEGraphDecoder.java:839)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.graal.meta.SubstrateReplacements.getSnippet(SubstrateReplacements.java:250)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.graal.meta.SubstrateReplacements.getSnippetGraphs(SubstrateReplacements.java:183)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.initializeBigBang(NativeImageGenerator.java:1113)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:959)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:604)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:564)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:408)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:616)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:134)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)
```

## GraalVM Setup

| Name | Value |
| ---- | ----- |
| GraalVM version | `GraalVM dev Java 20+30-jvmci-23.0-b06 CE` |
| Java version | `20+30-jvmci-23.0-b06` |
| C compiler | `gcc (linux, x86_64, 12.2.0)` |
<details>
<summary>GraalVM <code>release</code> file</summary>

```
IMPLEMENTOR="GraalVM Community"
JAVA_VERSION="20"
JAVA_VERSION_DATE="2023-03-21"
LIBC="gnu"
MODULES="java.base java.compiler java.instrument java.logging java.management jdk.internal.vm.ci jdk.jfr jdk.unsupported org.graalvm.sdk java.datatransfer java.xml java.prefs java.desktop java.transaction.xa java.sql jdk.management org.graalvm.truffle jdk.internal.vm.compiler com.oracle.graal.graal_enterprise com.oracle.svm.extraimage_enterprise com.oracle.svm.svm_enterprise com.oracle.svm_enterprise.ml_dataset java.security.sasl java.naming java.rmi java.management.rmi java.net.http java.scripting java.security.jgss java.sql.rowset java.xml.crypto java.se java.smartcardio jdk.accessibility jdk.internal.jvmstat jdk.attach jdk.charsets jdk.zipfs jdk.compiler jdk.crypto.ec jdk.crypto.cryptoki jdk.dynalink jdk.internal.ed jdk.editpad jdk.hotspot.agent jdk.httpserver jdk.incubator.concurrent jdk.incubator.vector jdk.internal.le jdk.internal.opt jdk.internal.vm.compiler.management jdk.internal.vm.compiler.truffle.jfr jdk.jartool jdk.javadoc jdk.jcmd jdk.management.agent jdk.jconsole jdk.jdeps jdk.jdwp.agent jdk.jdi jdk.jlink jdk.jpackage jdk.jshell jdk.jsobject jdk.jstatd jdk.localedata jdk.management.jfr jdk.naming.dns jdk.naming.rmi jdk.net jdk.nio.mapmode jdk.random jdk.sctp jdk.security.auth jdk.security.jgss jdk.unsupported.desktop jdk.xml.dom org.graalvm.extraimage.builder org.graalvm.locator"
OS_ARCH="x86_64"
OS_NAME="Linux"
SOURCE=".:git:f39104f75ab8+ labsjdk-builder:0a7bc3910f8bc5f5804cc18d2550d719dbdce205 compiler:525b6972396e73479e45f806eba5566d2538e1be java-benchmarks:525b6972396e73479e45f806eba5566d2538e1be regex:525b6972396e73479e45f806eba5566d2538e1be sdk:525b6972396e73479e45f806eba5566d2538e1be substratevm:525b6972396e73479e45f806eba5566d2538e1be truffle:525b6972396e73479e45f806eba5566d2538e1be vm:525b6972396e73479e45f806eba5566d2538e1be"
GRAALVM_VERSION="23.0.0-dev"
COMMIT_INFO={"compiler": {"commit.committer": "Aleksandar Pejovic <aleksandar.pejovic@oracle.com>", "commit.committer-ts": 1676294530, "commit.rev": "525b6972396e73479e45f806eba5566d2538e1be"}, "java-benchmarks": {"commit.committer": "Aleksandar Pejovic <aleksandar.pejovic@oracle.com>", "commit.committer-ts": 1676294530, "commit.rev": "525b6972396e73479e45f806eba5566d2538e1be"}, "regex": {"commit.committer": "Aleksandar Pejovic <aleksandar.pejovic@oracle.com>", "commit.committer-ts": 1676294530, "commit.rev": "525b6972396e73479e45f806eba5566d2538e1be"}, "sdk": {"commit.committer": "Aleksandar Pejovic <aleksandar.pejovic@oracle.com>", "commit.committer-ts": 1676294530, "commit.rev": "525b6972396e73479e45f806eba5566d2538e1be"}, "substratevm": {"commit.committer": "Aleksandar Pejovic <aleksandar.pejovic@oracle.com>", "commit.committer-ts": 1676294530, "commit.rev": "525b6972396e73479e45f806eba5566d2538e1be"}, "truffle": {"commit.committer": "Aleksandar Pejovic <aleksandar.pejovic@oracle.com>", "commit.committer-ts": 1676294530, "commit.rev": "525b6972396e73479e45f806eba5566d2538e1be"}, "vm": {"commit.committer": "Aleksandar Pejovic <aleksandar.pejovic@oracle.com>", "commit.committer-ts": 1676294530, "commit.rev": "525b6972396e73479e45f806eba5566d2538e1be"}}
```

</details>

## Builder Setup

<details>
<summary>Class path</summary>

```
<...>/graalvm-ce-upstream/mdcssw
```

</details>

<details>
<summary>Module path</summary>

```
<...>/graalvm-ce-upstream/mdcssw/master/sdk/mxbuild/linux-amd64/GRAALVM_949D841C00_JAVA20/graalvm-949d841c00-java20-23.0.0-dev/lib/svm/library-support.jar
<...>/graalvm-ce-upstream/mdcssw/master/sdk/mxbuild/linux-amd64/GRAALVM_949D841C00_JAVA20/graalvm-949d841c00-java20-23.0.0-dev/lib/truffle/truffle-api.jar
<...>/graalvm-ce-upstream/mdcssw/master/sdk/mxbuild/linux-amd64/GRAALVM_949D841C00_JAVA20/graalvm-949d841c00-java20-23.0.0-dev/lib/svm/builder/javacpp-shadowed.jar
<...>/graalvm-ce-upstream/mdcssw/master/sdk/mxbuild/linux-amd64/GRAALVM_949D841C00_JAVA20/graalvm-949d841c00-java20-23.0.0-dev/lib/svm/builder/llvm-wrapper-shadowed.jar
<...>/graalvm-ce-upstream/mdcssw/master/sdk/mxbuild/linux-amd64/GRAALVM_949D841C00_JAVA20/graalvm-949d841c00-java20-23.0.0-dev/lib/svm/builder/objectfile.jar
<...>/graalvm-ce-upstream/mdcssw/master/sdk/mxbuild/linux-amd64/GRAALVM_949D841C00_JAVA20/graalvm-949d841c00-java20-23.0.0-dev/lib/svm/builder/javacpp-platform-specific-shadowed.jar
<...>/graalvm-ce-upstream/mdcssw/master/sdk/mxbuild/linux-amd64/GRAALVM_949D841C00_JAVA20/graalvm-949d841c00-java20-23.0.0-dev/lib/svm/builder/native-image-base.jar
<...>/graalvm-ce-upstream/mdcssw/master/sdk/mxbuild/linux-amd64/GRAALVM_949D841C00_JAVA20/graalvm-949d841c00-java20-23.0.0-dev/lib/svm/builder/svm-llvm.jar
<...>/graalvm-ce-upstream/mdcssw/master/sdk/mxbuild/linux-amd64/GRAALVM_949D841C00_JAVA20/graalvm-949d841c00-java20-23.0.0-dev/lib/svm/builder/pointsto.jar
<...>/graalvm-ce-upstream/mdcssw/master/sdk/mxbuild/linux-amd64/GRAALVM_949D841C00_JAVA20/graalvm-949d841c00-java20-23.0.0-dev/lib/svm/builder/llvm-platform-specific-shadowed.jar
<...>/graalvm-ce-upstream/mdcssw/master/sdk/mxbuild/linux-amd64/GRAALVM_949D841C00_JAVA20/graalvm-949d841c00-java20-23.0.0-dev/lib/svm/builder/svm.jar
```

</details>

<details>
<summary>Builder arguments</summary>

```
-H:CLibraryPath=<...>/graalvm-ce-upstream/mdcssw/master/sdk/mxbuild/linux-amd64/GRAALVM_949D841C00_JAVA20/graalvm-949d841c00-java20-23.0.0-dev/lib/svm/clibraries/linux-amd64
-H:Path=<...>/graalvm-ce-upstream/mdcssw
-H:Dump=*:1
-H:Class@explicit main-class=Hello
-H:Name@main-class lower case as image name=hello
-H:Features@jar:file://<...>/graalvm-ce-upstream/mdcssw/master/sdk/mxbuild/linux-amd64/GRAALVM_949D841C00_JAVA20/graalvm-949d841c00-java20-23.0.0-dev/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/thirdparty/native-image.properties=com.oracle.svm.thirdparty.gson.GsonFeature
-H:Features@jar:file://<...>/graalvm-ce-upstream/mdcssw/master/sdk/mxbuild/linux-amd64/GRAALVM_949D841C00_JAVA20/graalvm-949d841c00-java20-23.0.0-dev/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/polyglot/native-image.properties=com.oracle.svm.polyglot.groovy.GroovyIndyInterfaceFeature,com.oracle.svm.polyglot.scala.ScalaFeature
-H:+BuildOutputColorful
-H:+BuildOutputProgress
-H:+BuildOutputLinks
```

</details>

<details>
<summary>Builder properties</summary>

```
-Dcom.oracle.graalvm.isaot=true
-Dgraalvm.ForcePolyglotInvalid=true
-Dgraalvm.locatorDisabled=true
-Djava.awt.headless=true
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader
-Djdk.internal.lambda.disableEagerInitialization=true
-Djdk.internal.lambda.eagerlyInitialize=false
-Djdk.module.main=org.graalvm.nativeimage.builder
-Dorg.graalvm.config=CE
-Dorg.graalvm.vendor=Oracle Corporation
-Dorg.graalvm.vendorurl=https://www.graalvm.org/
-Dorg.graalvm.version=dev
-Dsubstratevm.HostLibC=glibc
-Dsubstratevm.IgnoreGraalVersionCheck=true
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime
-Dtruffle.TrustAllTruffleRuntimeProviders=true
```

</details>

<details>
<summary>Features enabled</summary>

```
com.oracle.svm.core.ContainersFeature, []
com.oracle.svm.core.IsolateArgumentParserFeature, []
com.oracle.svm.core.IsolateListenerFeature, [com.oracle.svm.core.IsolateListenerSupportFeature]
com.oracle.svm.core.IsolateListenerSupportFeature, []
com.oracle.svm.core.RuntimeAssertionsSupportFeature, []
com.oracle.svm.core.StaticFieldsFeature, []
com.oracle.svm.core.StaticFieldsSupportFeature, []
com.oracle.svm.core.SubstrateExitHandlerFeature, []
com.oracle.svm.core.SubstrateSegfaultHandlerFeature, [com.oracle.svm.core.IsolateListenerSupportFeature]
com.oracle.svm.core.UniqueShortNameProviderDefaultImplFeature, []
com.oracle.svm.core.UnsafeMemoryUtilFeature, []
com.oracle.svm.core.allocationprofile.AllocationProfilingFeature, [com.oracle.svm.core.jdk.RuntimeSupportFeature]
com.oracle.svm.core.amd64.AMD64FrameAccessFeature, []
com.oracle.svm.core.c.CTypeConversionSupportImplFeature, []
com.oracle.svm.core.c.ProjectHeaderFileHeaderResolversRegistryFeature, []
com.oracle.svm.core.c.function.IsolateSupportImplFeature, []
com.oracle.svm.core.code.CodeInfoFeature, [com.oracle.svm.core.util.CounterFeature]
com.oracle.svm.core.code.CodeInfoMemoryWalkerFeature, []
com.oracle.svm.core.code.InstalledCodeObserverSupportFeature, []
com.oracle.svm.core.cpufeature.RuntimeCPUFeatureCheckFeature, []
com.oracle.svm.core.cpufeature.RuntimeCPUFeatureCheckImplFeature, []
com.oracle.svm.core.genscavenge.AlignedHeapChunkMemoryWalkerAccessImplFeature, []
com.oracle.svm.core.genscavenge.JfrGCEventFeature, []
com.oracle.svm.core.genscavenge.PinnedObjectImplPinnedObjectSupportImplFeature, []
com.oracle.svm.core.genscavenge.UnalignedHeapChunkMemoryWalkerAccessImplFeature, []
com.oracle.svm.core.genscavenge.graal.BarrierSnippetCountersFeature, [com.oracle.svm.core.util.CounterFeature]
com.oracle.svm.core.genscavenge.graal.GenScavengeGCFeature, [com.oracle.svm.core.jdk.RuntimeSupportFeature com.oracle.svm.core.jdk.management.ManagementFeature com.oracle.svm.core.jvmstat.PerfDataFeature com.oracle.svm.core.heap.AllocationFeature]
com.oracle.svm.core.graal.amd64.AMD64NativePatchConsumerFactoryFeature, []
com.oracle.svm.core.graal.amd64.SubstrateAMD64Feature, []
com.oracle.svm.core.graal.amd64.SubstrateAMD64GraphBuilderPlugins, []
com.oracle.svm.core.graal.jdk.JDKIntrinsicsFeature, []
com.oracle.svm.core.graal.snippets.CFunctionSnippetsFeature, []
com.oracle.svm.core.graal.snippets.DeoptSnippetsFeature, []
com.oracle.svm.core.graal.snippets.ExceptionFeature, []
com.oracle.svm.core.graal.snippets.SafepointFeature, []
com.oracle.svm.core.graal.snippets.StackOverflowCheckFeature, []
com.oracle.svm.core.graal.snippets.amd64.AMD64SnippetsFeature, []
com.oracle.svm.core.graal.stackvalue.StackValueFeature, []
com.oracle.svm.core.handles.ObjectHandlesSupportImplFeature, []
com.oracle.svm.core.heap.AllocationFeature, []
com.oracle.svm.core.heap.GCCauseFeature, []
com.oracle.svm.core.heap.HostedHeapSizeVerifierFeature, []
com.oracle.svm.core.heap.ReferenceAccessImplFeature, []
com.oracle.svm.core.heap.ReferenceHandlerThreadFeature, []
com.oracle.svm.core.heap.VMOperationInfosFeature, []
com.oracle.svm.core.heap.VMOperationNamesFeatures, []
com.oracle.svm.core.heapdump.HeapDumpFeature, []
com.oracle.svm.core.hub.ClassForNameSupportFeature, []
com.oracle.svm.core.hub.DynamicHubSupportFeature, []
com.oracle.svm.core.identityhashcode.SubstrateIdentityHashCodeFeature, []
com.oracle.svm.core.jdk.AtomicFieldUpdaterFeature, []
com.oracle.svm.core.jdk.ClassLoaderSupportFeature, []
com.oracle.svm.core.jdk.CompletableFutureFeature, []
com.oracle.svm.core.jdk.FileSystemProviderFeature, []
com.oracle.svm.core.jdk.ForkJoinPoolFeature, []
com.oracle.svm.core.jdk.InnocuousForkJoinWorkerThreadFeature, []
com.oracle.svm.core.jdk.JDKVersionSpecificResourceBuilderJDK11OrLaterFeature, []
com.oracle.svm.core.jdk.JRTDisableFeature, []
com.oracle.svm.core.jdk.JavaNetFeature, []
com.oracle.svm.core.jdk.JavaNetHttpFeature, []
com.oracle.svm.core.jdk.NativeLibrarySupportFeature, []
com.oracle.svm.core.jdk.PlatformNativeLibrarySupportFeature, []
com.oracle.svm.core.jdk.RecordSupportJDK11OrEarlierFeature, []
com.oracle.svm.core.jdk.ResourcesFeature, []
com.oracle.svm.core.jdk.RuntimeFeature, [com.oracle.svm.core.jdk.RuntimeSupportFeature]
com.oracle.svm.core.jdk.RuntimeSupportFeature, []
com.oracle.svm.core.jdk.SealedClassSupportJDK11OrEarlierFeature, []
com.oracle.svm.core.jdk.ServiceCatalogSupportFeature, []
com.oracle.svm.core.jdk.SimpleWebServerFeature, []
com.oracle.svm.core.jdk.TimeZoneFeature, []
com.oracle.svm.core.jdk.TrustStoreManagerFeature, []
com.oracle.svm.core.jdk.URLProtocolsSupportFeature, []
com.oracle.svm.core.jdk.VarHandleFeature, []
com.oracle.svm.core.jdk.localization.LocalizationFeature, []
com.oracle.svm.core.jdk.management.ManagementFeature, [com.oracle.svm.core.jdk.RuntimeSupportFeature com.oracle.svm.core.thread.ThreadListenerSupportFeature]
com.oracle.svm.core.jdk17.RecordSupportJDK17OrLaterFeature, []
com.oracle.svm.core.jdk17.SealedClassSupportJDK17OrLaterFeature, []
com.oracle.svm.core.jfr.sampler.JfrNoExecutionSamplerFeature, [com.oracle.svm.core.jfr.JfrFeature]
com.oracle.svm.core.jfr.sampler.JfrRecurringCallbackExecutionSamplerFeature, [com.oracle.svm.core.jfr.JfrFeature]
com.oracle.svm.core.jvmstat.PerfDataFeature, [com.oracle.svm.core.thread.VMOperationListenerSupportFeature com.oracle.svm.core.jdk.RuntimeSupportFeature]
com.oracle.svm.core.meta.SubstrateObjectConstantEqualityFeature, []
com.oracle.svm.core.monitor.MonitorFeature, []
com.oracle.svm.core.option.RuntimeOptionsSupportImplFeature, []
com.oracle.svm.core.option.ValidateImageBuildOptionsFeature, []
com.oracle.svm.core.os.ImageHeapProviderFeature, []
com.oracle.svm.core.os.OSCommittedMemoryProviderFeature, []
com.oracle.svm.core.posix.IgnoreSIGPIPEFeature, []
com.oracle.svm.core.posix.PosixLoadAverageSupportFeature, []
com.oracle.svm.core.posix.PosixLogHandlerFeature, []
com.oracle.svm.core.posix.PosixNativeLibraryFeature, []
com.oracle.svm.core.posix.PosixRawFileOperationFeature, []
com.oracle.svm.core.posix.PosixSubstrateSegfaultHandlerFeature, []
com.oracle.svm.core.posix.PosixSubstrateSigProfHandlerFeature, [com.oracle.svm.core.IsolateListenerSupportFeature com.oracle.svm.core.jfr.JfrFeature]
com.oracle.svm.core.posix.PosixVirtualMemoryProviderFeature, []
com.oracle.svm.core.posix.UnmanagedMemorySupportImplFeature, []
com.oracle.svm.core.posix.amd64.AMD64LinuxUContextRegisterDumperFeature, []
com.oracle.svm.core.posix.heapdump.AllocationFreeFileOutputStreamPosixFeature, []
com.oracle.svm.core.posix.linux.LinuxImageSingletonsFeature, []
com.oracle.svm.core.posix.linux.LinuxPhysicalMemorySupportImplFeature, []
com.oracle.svm.core.posix.linux.LinuxProcessPropertiesSupportFeature, []
com.oracle.svm.core.posix.linux.LinuxStackOverflowSupportFeature, []
com.oracle.svm.core.posix.linux.LinuxSystemPropertiesFeature, []
com.oracle.svm.core.posix.linux.LinuxThreadCpuTimeSupportFeature, []
com.oracle.svm.core.posix.linux.LinuxVMSemaphoreFeature, []
com.oracle.svm.core.posix.pthread.PthreadVMLockFeature, []
com.oracle.svm.core.posix.thread.PosixParkEventFactoryFeature, []
com.oracle.svm.core.posix.thread.PosixPlatformThreadsFeature, []
com.oracle.svm.core.posix.thread.PosixVMThreadsFeature, []
com.oracle.svm.core.reflect.target.ReflectionMetadataDecoderImplFeature, []
com.oracle.svm.core.reflect.target.ReflectionMetadataDecoderImplMetadataAccessorImplFeature, []
com.oracle.svm.core.reflect.target.ReflectionMetadataEncodingFeature, []
com.oracle.svm.core.thread.ContinuationsFeature, []
com.oracle.svm.core.thread.JavaThreadsFeature, []
com.oracle.svm.core.thread.SafepointMasterFeature, []
com.oracle.svm.core.thread.ThreadListenerSupportFeature, []
com.oracle.svm.core.thread.ThreadingSupportImplFeature, []
com.oracle.svm.core.thread.VMOperationControlFeature, []
com.oracle.svm.core.thread.VMOperationListenerSupportFeature, []
com.oracle.svm.core.threadlocal.VMThreadLocalInfosFeature, []
com.oracle.svm.core.util.CounterFeature, []
com.oracle.svm.core.util.HostedStringDeduplicationFeature, []
com.oracle.svm.graal.RuntimeCPUFeatureRegionFeature, []
com.oracle.svm.graal.isolated.DisableSnippetCountersFeature, []
com.oracle.svm.graal.isolated.IsolateAwareObjectConstantEqualityFeature, []
com.oracle.svm.graal.meta.amd64.AMD64RuntimeCodeInstallerPlatformHelperFeature, []
com.oracle.svm.graal.stubs.AMD64StubForeignCallsFeature, []
com.oracle.svm.hosted.AMD64CPUFeatureAccessFeature, []
com.oracle.svm.hosted.ClassLoaderFeature, []
com.oracle.svm.hosted.ClassNewInstanceFeature, []
com.oracle.svm.hosted.ClassPredefinitionFeature, []
com.oracle.svm.hosted.ClassValueFeature, []
com.oracle.svm.hosted.ConcurrentReachabilityHandler, []
com.oracle.svm.hosted.FallbackFeature, []
com.oracle.svm.hosted.Log4ShellFeature, []
com.oracle.svm.hosted.LoggingFeature, []
com.oracle.svm.hosted.ModuleLayerFeature, []
com.oracle.svm.hosted.NativeSecureRandomFilesCloser, []
com.oracle.svm.hosted.ProgressReporterFeature, []
com.oracle.svm.hosted.ProtectionDomainFeature, []
com.oracle.svm.hosted.ResourcesFeature, []
com.oracle.svm.hosted.SecurityServicesFeature, []
com.oracle.svm.hosted.ServiceLoaderFeature, []
com.oracle.svm.hosted.SubstrateDiagnosticFeature, []
com.oracle.svm.hosted.SystemInOutErrFeature, []
com.oracle.svm.hosted.VMFeature, []
com.oracle.svm.hosted.ameta.HostedDynamicHubFeature, []
com.oracle.svm.hosted.annotation.AnnotationSupportFeature, []
com.oracle.svm.hosted.annotation.AnnotationTypeFeature, []
com.oracle.svm.hosted.c.CGlobalDataFeature, []
com.oracle.svm.hosted.c.function.CEntryPointSupport, []
com.oracle.svm.hosted.c.libc.HostedLibCFeature, []
com.oracle.svm.hosted.classinitialization.ClassInitializationFeature, []
com.oracle.svm.hosted.code.CEntryPointCallStubFeature, []
com.oracle.svm.hosted.code.CEntryPointLiteralFeature, []
com.oracle.svm.hosted.code.CFunctionLinkagesFeature, []
com.oracle.svm.hosted.code.CFunctionPointerCallStubSupportFeature, []
com.oracle.svm.hosted.code.FactoryMethodSupportFeature, []
com.oracle.svm.hosted.code.FrameInfoHostedMethodDataFeature, []
com.oracle.svm.hosted.code.RestrictHeapAccessCalleesFeature, []
com.oracle.svm.hosted.code.SubstrateCompilationDirectivesFeature, []
com.oracle.svm.hosted.code.SubstrateLIRBackendFeature, []
com.oracle.svm.hosted.code.UninterruptibleAnnotationCheckerFeature, []
com.oracle.svm.hosted.code.amd64.AMD64HostedPatcherFeature, []
com.oracle.svm.hosted.code.amd64.AMD64HostedTrampolineSupportFeature, []
com.oracle.svm.hosted.fieldfolding.StaticFinalFieldFoldingFeature, []
com.oracle.svm.hosted.heap.HeapDumpFieldsMapFeature, []
com.oracle.svm.hosted.heap.ImageHeapMapFeature, []
com.oracle.svm.hosted.heap.PodFeature, []
com.oracle.svm.hosted.image.DisallowedImageHeapObjectFeature, [com.oracle.svm.core.jdk.management.ManagementFeature]
com.oracle.svm.hosted.image.ImageHeapFillerObjectsFeature, []
com.oracle.svm.hosted.image.MethodPointerInvalidHandlerFeature, []
com.oracle.svm.hosted.image.StringInternFeature, []
com.oracle.svm.hosted.image.sources.SourceCacheFeature, []
com.oracle.svm.hosted.jdk.AccessControlContextReplacerFeature, []
com.oracle.svm.hosted.jdk.JDKInitializationFeature, []
com.oracle.svm.hosted.jdk.JDKRegistrations, []
com.oracle.svm.hosted.jdk.JNIRegistrationAwt, []
com.oracle.svm.hosted.jdk.JNIRegistrationJava, []
com.oracle.svm.hosted.jdk.JNIRegistrationJavaNet, []
com.oracle.svm.hosted.jdk.JNIRegistrationJavaNio, []
com.oracle.svm.hosted.jdk.JNIRegistrationManagementExt, []
com.oracle.svm.hosted.jdk.JNIRegistrationPrefs, []
com.oracle.svm.hosted.jdk.JNIRegistrationSupport, []
com.oracle.svm.hosted.jdk.JNIRegistrationsJavaZip, []
com.oracle.svm.hosted.jdk.JRTFeature, []
com.oracle.svm.hosted.jdk.localization.CharsetSubstitutionsFeature, []
com.oracle.svm.hosted.jdk.localization.LocalizationFeature, []
com.oracle.svm.hosted.jdk17.JNIRegistrationSupport_JDK17OrLater, []
com.oracle.svm.hosted.jni.JNIAccessFeature, [com.oracle.svm.hosted.meta.KnownOffsetsFeature]
com.oracle.svm.hosted.jni.JNIAutomaticFeature, [com.oracle.svm.hosted.jni.JNIFeature]
com.oracle.svm.hosted.jni.JNICallWrapperFeature, [com.oracle.svm.hosted.jni.JNIAccessFeature]
com.oracle.svm.hosted.jni.JNIFeature, [com.oracle.svm.hosted.jni.JNIFunctionTablesFeature com.oracle.svm.hosted.jni.JNICallWrapperFeature com.oracle.svm.hosted.jni.JNILibraryLoadFeature]
com.oracle.svm.hosted.jni.JNIFunctionTablesFeature, [com.oracle.svm.hosted.jni.JNIAccessFeature]
com.oracle.svm.hosted.jni.JNILibraryLoadFeature, []
com.oracle.svm.hosted.lambda.StableLambdaProxyNameFeature, []
com.oracle.svm.hosted.meta.HostedMethodNameFactory, []
com.oracle.svm.hosted.meta.InvalidVTableEntryFeature, []
com.oracle.svm.hosted.meta.KnownOffsetsFeature, [com.oracle.svm.hosted.thread.VMThreadMTFeature]
com.oracle.svm.hosted.meta.MaterializedConstantFieldsFeature, []
com.oracle.svm.hosted.methodhandles.MethodHandleFeature, []
com.oracle.svm.hosted.option.RuntimeOptionFeature, []
com.oracle.svm.hosted.phases.EnumSwitchFeature, []
com.oracle.svm.hosted.reflect.ReflectionFeature, []
com.oracle.svm.hosted.reflect.ReflectionMetadataEncoderImplFactoryFeature, []
com.oracle.svm.hosted.reflect.proxy.DynamicProxyFeature, [com.oracle.svm.hosted.reflect.ReflectionFeature]
com.oracle.svm.hosted.reflect.serialize.SerializationFeature, [com.oracle.svm.hosted.reflect.ReflectionFeature com.oracle.svm.hosted.reflect.proxy.DynamicProxyFeature]
com.oracle.svm.hosted.snippets.ExceptionUnwindFeature, []
com.oracle.svm.hosted.snippets.ImplicitExceptionsFeature, []
com.oracle.svm.hosted.substitute.AutomaticSubstitutionFeature, []
com.oracle.svm.hosted.thread.CEntryPointFeature, [com.oracle.svm.hosted.thread.VMThreadMTFeature]
com.oracle.svm.hosted.thread.VMThreadMTFeature, []
com.oracle.svm.hosted.xml.JavaxXmlClassAndResourcesLoaderFeature, []
com.oracle.svm.truffle.TruffleJFRFeature, []
```

</details>

**Comment by koutheir** [comment]
For reference, the command line I used was:
```shell
$ master/sdk/latest_graalvm_home/bin/native-image -J-ea '-H:Dump=*:1' -cp $(pwd) Hello
```

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this issue, we'll take a look into it shortly.

**Comment by koutheir** [comment]
@oubidar-Abderrahim, any news regarding this issue?

**Comment by oubidar-Abderrahim** [comment]
Sorry for the delay, I believe this was already fixed in Oracle GraalVM for JDK21
