### ISSUE TITLE
Esapi issue as native image

### ISSUE THREAD

**Issue by kartik-kaushik** [oracle/graal#6016]
Describe the bug
Spring Boot 3 native image not working with ESAPI dependency

Sample
Via the Spring Initializer, create any project with:
spring-boot-starter-parent:3.0.2
spring-boot-starter-actuator

add below dependency
org.owasp.esapi : esapi : 2.4.0.0

add ESAPI.properties in resources folder
https://raw.githubusercontent.com/OWASP/EJSF/master/esapi_master_FULL/WebContent/ESAPI.properties

Create a controller class

@RestController
public class HelloworldController {

private Logger logger = LoggerFactory.getLogger(HelloworldController.class);

@GetMapping(value = "/check", produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
public String check() {
String value="Success";
if (value != null) {
Encoder encoder = ESAPI.encoder();
return encoder.canonicalize(value, false);
}
return value;

}

}
Check with /check endpoint. The application works normally, but with native image giving error:

Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.owasp.esapi.errors.ConfigurationException: java.lang.ClassNotFoundException: org.owasp.esapi.reference.DefaultSecurityConfiguration SecurityConfiguration class (org.owasp.esapi.reference.DefaultSecurityConfiguration) must be in class path.] with root cause

java.lang.ClassNotFoundException: org.owasp.esapi.reference.DefaultSecurityConfiguration
at java.base@17.0.5/java.lang.Class.forName(DynamicHub.java:1132) ~[spring-ldaps:na]
at java.base@17.0.5/java.lang.Class.forName(DynamicHub.java:1105) ~[spring-ldaps:na]
at org.owasp.esapi.util.ObjFactory.loadClassByStringName(ObjFactory.java:158) ~[na:na]
at org.owasp.esapi.util.ObjFactory.make(ObjFactory.java:81) ~[na:na]
at org.owasp.esapi.ESAPI.securityConfiguration(ESAPI.java:185) ~[na:na]
at org.owasp.esapi.ESAPI.encoder(ESAPI.java:101) ~[na:na]
at com.example.springldaps.HelloworldController.health(HelloworldController.java:47) ~[spring-ldaps:na]
at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568) ~[spring-ldaps:na]
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[spring-ldaps:6.0.4]
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152) ~[spring-ldaps:6.0.4]
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-ldaps:6.0.4]
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-ldaps:6.0.4]
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-ldaps:6.0.4]
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-ldaps:6.0.4]
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1080) ~[spring-ldaps:6.0.4]
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:973) ~[spring-ldaps:6.0.4]
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[spring-ldaps:6.0.4]
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[spring-ldaps:6.0.4]
at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:705) ~[spring-ldaps:6.0]
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-ldaps:6.0.4]
at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:814) ~[spring-ldaps:6.0]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223) ~[na:na]at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[na:na]
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[spring-ldaps:10.1.5]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[na:na]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[na:na]
at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-ldaps:6.0.4]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-ldaps:6.0.4]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[na:na]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[na:na]
at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-ldaps:6.0.4]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-ldaps:6.0.4]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[na:na]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[na:na]
at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109) ~[spring-ldaps:6.0.4]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-ldaps:6.0.4]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[na:na]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[na:na]
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-ldaps:6.0.4]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-ldaps:6.0.4]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[na:na]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[na:na]
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177) ~[na:na]
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[na:na]
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[spring-ldaps:10.1.5]
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119) ~[na:na]
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[spring-ldaps:10.1.5]
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[na:na]
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[na:na]
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400) ~[na:na]
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[spring-ldaps:10.1.5]
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:859) ~[na:na]
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1734) ~[na:na]
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[spring-ldaps:10.1.5]
at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[na:na]
at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[na:na]
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[na:na]
at java.base@17.0.5/java.lang.Thread.run(Thread.java:833) ~[spring-ldaps:na]at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775) ~[spring-ldaps:na]
at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadS

Esapi is working in springboot3 as non-native and also able to build as native, but on hitting the api call the response is not coming and giving error with native.
Is there any hint available for the same? As the Esapi team is saying that jakarta is being used in springboot3 and esapi uses javax and they don't support it in boot3, then how come it is working in springboot3 as well without any change compared to boot 2.x.x

**Comment by SergejIsbrecht** [comment]
The callstack clearly display the issue:

`java.lang.ClassNotFoundException: org.owasp.esapi.reference.DefaultSecurityConfiguration`

A class called `DefaultSecurityConfiguration` is not registered for _reflection_. You need to do it via the config file, or try using the agent to create the config for your use-case.

**Comment by kartik-kaushik** [comment]
https://github.com/ESAPI/esapi-java-legacy/issues/773
Could you please answer this if that's the case. 
I will try your suggestion. But what is the best way for future usage if above is the case as per esapi

**Comment by SergejIsbrecht** [comment]
Please have a look at how native-image works. It does a static analysis of all reachable classes and code paths and removes all, which are not reachable. Dynamic features like _reflection_ must be configured properly. If you don't, you will see "ClassNotFoundException", because the class was not include in the native-image and therefore could not be loaded during runtime, because the static analysis didn't see it. 

I do not know spring or esapi. Therefore, I am probably of not much help. In any case, when seeing `ClassNotFoundException`s during runtime, this means something is missing and you should include this class.

If you have very _dynamic_ code, you should probably not use native-image at all, if it changes a lot and therefore requires a lot of configuration changes.

**Comment by oubidar-Abderrahim** [comment]
As mentioned above, please use the tracing agent to generate the config files for your application: https://www.graalvm.org/22.3/reference-manual/native-image/metadata/AutomaticMetadataCollection/

**Comment by oubidar-Abderrahim** [comment]
Hi, Any updates?

**Comment by oubidar-Abderrahim** [comment]
Hi, if you still face this issue, please reopen this thread.
