### ISSUE TITLE
How to tell the GraalVM to pick the file in the time of image build

### ISSUE THREAD

**Issue by VidyasagarDamotharan** [oracle/graal#6025]
We are currently migrating an old spring-boot project to the native image using build packs, we migrated the project to JDK-17 and Spring boot v3.0.2, The docker image has been build successfully but while trying to run the container, getting the below error

```
Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'graphQLProvider': resource schema.graphqls not found.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1751)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:961)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:915)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291)
	at com.abc.cefg.example.Application.main(Application.java:20)
Caused by: java.lang.IllegalArgumentException: resource schema.graphqls not found.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:120)
	at com.google.common.io.Resources.getResource(Resources.java:222)
	at com.abc.cefg.example.common.graphql.GraphQLProvider.init(GraphQLProvider.java:80)
	at java.base@17.0.6/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1850)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1807)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1747)
	... 16 common frames omitted

```

Steps:

1.  Build the native docker image using the command `mvn -Pnative spring-boot:build-image`
2.  `docker run` command was used to run the container but the above-mentioned error has been thrown while trying to run the container

GraalVM environment:
 - GraalVM version: CE 22.3.0 
 - JDK major version: JDK 17
 - OS: Ubuntu 20.04.4

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reaching out about this, this look like a missing resource configuration.
could you please verify the issue with the latest release of 22.3.1 and most importantly, make sure to generate Metadata configuration files using our Tracing agent before building the native image, you can check the following link for more info: https://www.graalvm.org/22.3/reference-manual/native-image/metadata/AutomaticMetadataCollection/

**Comment by VidyasagarDamotharan** [comment]
Hi @oubidar-Abderrahim. Thanks for the response :)
The above issue has been fixed by adding a class for telling the compiler to take the schema file at the time of compilation, attaching the code below

```
public class RuntimeHint implements RuntimeHintsRegistrar {
	@Override
	public void registerHints(RuntimeHints hints, ClassLoader classLoader) {
		try {
			ResourceHints resourceHints = hints.resources();
			resourceHints.registerPattern("schema.graphqls");
		} catch (Exception e) {
			throw new RuntimeException("Could not register RuntimeHint: " + e.getMessage());
		}
	}
}
```
Is this the correct way of fixing the issue
