### ISSUE TITLE
Reflection support for `Executable.getAnnotatedParameterTypes`

### ISSUE THREAD

**Issue by FroMage** [oracle/graal#603]
I think some reflection support is missing for this method, because I get the following exception:

```
com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported method java.lang.reflect.Executable.getTypeAnnotationBytes0() is reachable: Native method. If you intend to use the Java Native Interface (JNI), specify -H:+JNI and see also -H:JNIConfigurationFiles=<path> (use -H:+PrintFlags for details)
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Error.<init>(Error.java:70)
	at com.oracle.svm.core.jdk.UnsupportedFeatureError.<init>(UnsupportedFeatureError.java:31)
	at com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.unsupportedFeature(VMErrorSubstitutions.java:109)
	at java.lang.reflect.Executable.getTypeAnnotationBytes0(Executable.java)
	at java.lang.reflect.Executable.getAnnotatedParameterTypes(Executable.java:688)
	at java.lang.reflect.Parameter.getAnnotatedType(Parameter.java:237)
	at org.hibernate.validator.internal.metadata.provider.TypeAnnotationAwareMetaDataProvider.findTypeAnnotationConstraintsForExecutableParameter(TypeAnnotationAwareMetaDataProvider.java:85)
...
```

**Comment by cstancu** [comment]
Yes, support for `Executable.getAnnotated*Type(s)` methods is not currently implemented. A possible solution for this would be similar to [`Executable.sharedGetParameterAnnotations()`](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/target/Target_java_lang_reflect_Executable.java#L97), i.e., use a `CustomFieldValueComputer` to precompute the value at image build time and cache it in an `@Inject` field.

**Comment by FroMage** [comment]
Thanks. I tried adding that:

```java
    public static final class AnnotatedParameterTypesComputer implements CustomFieldValueComputer {

        @Override
        public Object compute(MetaAccessProvider metaAccess, ResolvedJavaField original, ResolvedJavaField annotated, Object receiver) {
            Executable executable = (Executable) receiver;
            return executable.getAnnotatedParameterTypes();
        }
    }
    @Inject @RecomputeFieldValue(kind = Kind.Custom, declClass = AnnotatedParameterTypesComputer.class) //
    AnnotatedType[] annotatedParameterTypes;

    @Substitute
    public AnnotatedType[] getAnnotatedParameterTypes() {
        Target_java_lang_reflect_Executable holder = getRoot();
        if (holder == null) {
            holder = this;
        }

        if (holder.annotatedParameterTypes == null) {
            throw VMError.shouldNotReachHere("Annotated parameter types must be computed during native image generation");
        }
        return holder.annotatedParameterTypes;
    }

```

But upon building my image I get these errors now:

```
error: Static field or an object referenced from a static field changed during native image generation?
  object:[Ljava.lang.reflect.Parameter;@60bc5e75  of class: java.lang.reflect.Parameter[]
  reachable through:
    object: public abstract java.sql.PreparedStatement java.sql.Connection.prepareStatement(java.lang.String) throws java.sql.SQLException  of class: java.lang.reflect.Method
    root: com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(String)

Error: Image building with exit status 1

```

**Comment by cstancu** [comment]
Your substitution code looks correct. I used it and I tried some small test but I cannot reproduce the issue. Can you share the code that produces this?

**Comment by FroMage** [comment]
I pushed my jar to https://github.com/FroMage/svm-test

I get the same problem if I try to support `Executable.getAnnotatedReturnType()` too.

Is that enough for you or do you need the source code too?

**Comment by FroMage** [comment]
Every error points to a `Parameter[]` held in `Executable`. I don't really understand why it would change, beside the complicated logic in `Executable.privateGetParameters()` which seems to be able to result in concurrent computation/memoization if called from multiple threads. I also don't really understand why there's any logic for that particular field in `Target_java_lang_reflect_Executable`, because it's memoized already (and forced at image build time), unlike the other fields.

**Comment by FroMage** [comment]
Could it have something to do with the `Executable.parameters` field being transient?

**Comment by cstancu** [comment]
The problem is that the object replacers don't get called consistently on all the objects that are added to the heap and sometimes they get called too late for some objects. The `ReflectionMetadataFeature` object replacer ensures that all the reflection metadata is initialized and cached but sometimes it computes the `Executable.parameters` too late, after the corresponding `Executable` was already added to the heap, thus the error. I have a quick fix but I will investigate this further. 

For now please use the [attached diff](https://github.com/oracle/graal/files/2289469/gh-603.diff.zip) that includes the substitutions and the fix. With this I can successfully build the image and, when I run it and go to `localhost:9000`, get the `Hello World`.

**Comment by FroMage** [comment]
Thanks, I tried your patch, but now I got this more annoying error during building the image:

```
Warning: class initialization of class com.oracle.svm.core.jdk.zipfile.ZipFile failed with exception java.lang.InternalError: missing overlay. This class will be initialized at runtime because option --report-unsupported-elements-at-runtime is used for image building. Use the option --delay-class-initialization-to-runtime=com.oracle.svm.core.jdk.zipfile.ZipFile to explicitly request delayed initialization of this class.
       setup:     300.18 ms
error: Cannot delay running the class initializer because class must be initialized for internal purposes: com.oracle.svm.core.jdk.zipfile.ZipFile
Error: Image building with exit status 1
```

**Comment by christianwimmer** [comment]
I cannot reproduce the `ZipFile` problem. Can you try a `mx clean` and `mx build` to get a completely new clean build of Graal and Substrate VM? There were some changes recently regarding jdk8/jdk9 source code separation that might have led to an inconsistent incremental build.

**Comment by FroMage** [comment]
Nope, no luck. I had a new error:

```
Error: Detected a direct/mapped ByteBuffer in the image heap. A direct ByteBuffer has a pointer to unmanaged C memory, and C memory from the image generator is not available at image run time. A mapped ByteBuffer references a file descriptor, which is no longer open and mapped at run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option --delay-class-initialization-to-runtime=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: 	object io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledDirectByteBuf
	object io.netty.buffer.ReadOnlyByteBuf
	object io.netty.buffer.UnreleasableByteBuf
	method io.netty.handler.codec.http2.Http2CodecUtil.connectionPrefaceBuf()
Call path from entry point to io.netty.handler.codec.http2.Http2CodecUtil.connectionPrefaceBuf(): 
	at io.netty.handler.codec.http2.Http2CodecUtil.connectionPrefaceBuf(Http2CodecUtil.java:169)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.sendPreface(Http2ConnectionHandler.java:370)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.channelActive(Http2ConnectionHandler.java:264)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.channelActive(Http2ConnectionHandler.java:420)
	at io.vertx.core.http.impl.VertxHttp2ConnectionHandler.channelActive(VertxHttp2ConnectionHandler.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.access$200(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$3.run(AbstractChannelHandlerContext.java:204)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:238)
	at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_002epthreadStartRoutine_0028com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_0024ThreadStartData_0029(generated:0)
Error: Detected a direct/mapped ByteBuffer in the image heap. A direct ByteBuffer has a pointer to unmanaged C memory, and C memory from the image generator is not available at image run time. A mapped ByteBuffer references a file descriptor, which is no longer open and mapped at run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option --delay-class-initialization-to-runtime=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: 	object io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledDirectByteBuf
	object io.netty.buffer.ReadOnlyByteBuf
	object io.netty.buffer.UnreleasableByteBuf
	method io.netty.handler.codec.http2.Http2CodecUtil.connectionPrefaceBuf()
Call path from entry point to io.netty.handler.codec.http2.Http2CodecUtil.connectionPrefaceBuf(): 
	at io.netty.handler.codec.http2.Http2CodecUtil.connectionPrefaceBuf(Http2CodecUtil.java:169)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.sendPreface(Http2ConnectionHandler.java:370)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.channelActive(Http2ConnectionHandler.java:264)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.channelActive(Http2ConnectionHandler.java:420)
	at io.vertx.core.http.impl.VertxHttp2ConnectionHandler.channelActive(VertxHttp2ConnectionHandler.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.access$200(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$3.run(AbstractChannelHandlerContext.java:204)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:238)
	at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_002epthreadStartRoutine_0028com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_0024ThreadStartData_0029(generated:0)

Error: Image building with exit status 1
```

Fixed it by adding `--delay-class-initialization-to-runtime=io.netty.buffer.UnreleasableByteBuf` so now my command is:

```
mx native-image --delay-class-initialization-to-runtime=io.netty.buffer.UnreleasableByteBuf --report-unsupported-elements-at-runtime -H:ReflectionConfigurationFiles=/home/stephane/src/java-eclipse/redpipe/reflect.json -H:DynamicProxyConfigurationFiles=/home/stephane/src/java-eclipse/redpipe/proxies.json -Dio.netty.noUnsafe=true  -H:EnableURLProtocols=http -Djava.net.preferIPv4Stack=true '-H:IncludeResources=META-INF/.*'  -jar /home/stephane/src/java-eclipse/redpipe/redpipe-example-helloworld/target/redpipe-example-helloworld-0.0.4-SNAPSHOT.jar
```

And I still get:

```
[redpipe-example-helloworld-0.0.4-SNAPSHOT:17085]    classlist:  16,237.76 ms
Warning: class initialization of class com.oracle.svm.core.jdk.zipfile.ZipFile failed with exception java.lang.InternalError: missing overlay. This class will be initialized at runtime because option --report-unsupported-elements-at-runtime is used for image building. Use the option --delay-class-initialization-to-runtime=com.oracle.svm.core.jdk.zipfile.ZipFile to explicitly request delayed initialization of this class.
[redpipe-example-helloworld-0.0.4-SNAPSHOT:17085]        setup:     298.45 ms
error: Cannot delay running the class initializer because class must be initialized for internal purposes: com.oracle.svm.core.jdk.zipfile.ZipFile
Error: Image building with exit status 1
```

**Comment by christianwimmer** [comment]
The `ByteBuffer` check was merged yesterday. The command line args I needed to add to Netty to get it working again is `--delay-class-initialization-to-runtime=io.netty.handler.codec.http.HttpObjectEncoder,io.netty.handler.codec.http2.Http2CodecUtil,io.netty.handler.codec.http2.DefaultHttp2FrameWriter,io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder`

**Comment by FroMage** [comment]
Thanks. I tried with that too and still get the same error about `ZipFile`.

**Comment by FroMage** [comment]
OK, with the latest master, I get further building the image, but still blocked by:

```
error: Class that is marked for delaying initialzation to runtime got initialized during image building: io.netty.handler.codec.http2.Http2CodecUtil
Error: Image building with exit status 1
```

We're getting further from the original reported issue, but it's still pretty limiting that I can't build native images anymore :(

**Comment by christianwimmer** [comment]
Disallowing direct byte buffers is absolutely necessary: we discovered the issue based on other bug reports that had Netty crash at runtime with a segfault because a direct byte buffer allocated during image generation was used at run time, i.e., memory that was no longer allocated was accessed.

So now a few classes that allocated direct byte buffers must be initialized at run time. The initial list of classes that I have - `--delay-class-initialization-to-runtime=io.netty.handler.codec.http.HttpObjectEncoder,io.netty.handler.codec.http2.Http2CodecUtil,io.netty.handler.codec.http2.DefaultHttp2FrameWriter,io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder` - is based on our internal Netty tests that we run. But there are more Netty classes that depend on these classes and therefore must be added to the list.

How do you find these? My approach is the following: run the image generator in the debugger. You can do that by adding `--debug-attach` to the `native-image` command line and then attaching any debugger (your favorite IDE) to debug port `8000`. Then set a breakpoint in the class initializer of the class that must not be initialized - in your case the class initializer of `io.netty.handler.codec.http2.Http2CodecUtil`. The image generator must stop on that breakpoint (because the class gets initialized). When you then look at the stack trace, you see other class initializers (`<clinit>`) methods on the stack. All these classes must be added to the `--delay-class-initialization-to-runtime` option.

**Comment by cstancu** [comment]
The originally reported issue is fixed in https://github.com/oracle/graal/commit/a77b66342d7fd04e66241f5ee36b0e2426f6a215. @FroMage the patch that I sent above shouldn't be needed anymore.

**Comment by FroMage** [comment]
OK, Indeed that works, except I still need this patch:

```
diff --git a/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageCodeCache.java b/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageCodeCache.java
index ef5e012779..45befb0107 100644
--- a/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageCodeCache.java
+++ b/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageCodeCache.java
@@ -366,7 +366,8 @@ public class NativeImageCodeCache {
             throw VMError.shouldNotReachHere("Non-instantiated type referenced by a compiled method: " + obj.getClass().getName());
         }
 
-        imageHeap.addObject(debug, obj, false, false, constantReasons.get(constant));
+        Object replaced = imageHeap.getAnalysisUniverse().replaceObject(obj);
+        imageHeap.addObject(debug, replaced, false, false, constantReasons.get(constant));
     }
 
     /**
diff --git a/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageHeap.java b/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageHeap.java
index 3088f93747..b8b9abdd96 100644
--- a/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageHeap.java
+++ b/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/NativeImageHeap.java
@@ -936,6 +936,10 @@ public final class NativeImageHeap {
         }
     }
 
+    protected AnalysisUniverse getAnalysisUniverse() {
+        return aUniverse;
+    }
+
     protected HostedUniverse getUniverse() {
         return universe;
     }
```

Otherwise I get:

```
error: Static field or an object referenced from a static field changed during native image generation?
  object:[Ljava.lang.reflect.Parameter;@6b5c5d60  of class: java.lang.reflect.Parameter[]
  reachable through:
    object: public sun.net.www.protocol.http.spnego.NegotiatorImpl(sun.net.www.protocol.http.HttpCallerInfo) throws java.io.IOException  of class: java.lang.reflect.Constructor
    root: sun.net.www.protocol.http.Negotiator.getNegotiator(HttpCallerInfo)

Error: Image building with exit status 1
```

**Comment by FroMage** [comment]
@christianwimmer thanks, I found that `io.vertx.core.http.impl.VertxHttp2ClientUpgradeCodec` was the culprit with your method, and now with that above patch I was finally able to compile and run my sample!

**Comment by FroMage** [comment]
@cstancu do you want me to open a new report for the remaining patch described above?

**Comment by cstancu** [comment]
@FroMage yes, please open a new report so we can close this one. We've already moved far enough from the original target.

**Comment by FroMage** [comment]
OK, opened #659. Thanks!
