### ISSUE TITLE
native-image crashes with NullPointerException

### ISSUE THREAD

**Issue by LanderlYoung** [oracle/graal#610]
compile a fat jar into native image by
`$GRAALVM_HOME/bin/native-image -jar fat.jar`
execute the resulted binary file

```bash
 ~/Desktop$ echo $GRAALVM_HOME
/Users/young/Applications/graalvm-ce-1.0.0-rc5/Contents/Home/
 ~/Desktop  $GRAALVM_HOME/bin/native-image -jar fat.jar
Shutdown Server(pid: 90189, port: 59711)
Build on Server(pid: 91828, port: 62908)*
   classlist:   5,115.97 ms
       (cap):   3,610.14 ms
       setup:   6,058.52 ms
  (typeflow):   9,794.53 ms
   (objects):   5,147.47 ms
  (features):     108.43 ms
    analysis:  15,233.72 ms
    universe:     568.00 ms
     (parse):   3,977.23 ms
    (inline):   3,042.67 ms
   (compile):  18,183.63 ms
     compile:  26,025.35 ms
       image:   2,643.82 ms
       write:   1,438.01 ms
     [total]:  57,205.04 ms
 ~/Desktop$ ./fat
Exception in thread "main" java.lang.NullPointerException
	at Main_Ktd$Companion.main(Main_Ktd.kt:5)
	at Main_Ktd.main(Main_Ktd.kt)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:177)

 ~/Desktop$ java -jar fat.jar
ktd: missing URL operand
```
System Info
macOS: 10.13.6
graalvm version: ce-1.0.0-rc5

testing file is here
[fat.jar.zip](https://github.com/oracle/graal/files/2279913/fat.jar.zip)

**Comment by cstancu** [comment]
Can you provide the source code for the fat.jar and instructions to build it?
