### ISSUE TITLE
java.io.IOException: Stream closed while hitting the API

### ISSUE THREAD

**Issue by VidyasagarDamotharan** [oracle/graal#6111]
Hi, We are trying to update the standard spring-boot project to GraalVM native docker image, the image has been created and the container running successfully but while trying to hit the API, we are facing java IOException, from the ua-parser library. Attaching the stack trace below
o.a.j.l.DirectJDKLog: Servlet.service() for servlet [dispatcherServlet] in context with path [/project-name] threw exception [Request processing failed: org.yaml.snakeyaml.error.YAMLException: java.io.IOException: Stream closed] with root cause
java.io.IOException: Stream closed
	at java.base@17.0.6/java.io.PushbackInputStream.ensureOpen(PushbackInputStream.java:74)
	at java.base@17.0.6/java.io.PushbackInputStream.read(PushbackInputStream.java:162)
	at org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:85)
	at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:117)
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:176)
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:169)
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:164)
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:119)
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1229)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:345)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:263)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:235)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:175)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:159)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:184)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:477)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:418)
	at ua_parser.Parser.initialize(Parser.java:83)
	at ua_parser.Parser.<init>(Parser.java:45)

I'm suspecting whether we need to tell the AOT compiler about the Parser we are using at the time of image build, if that's true what is the correct way to tell the compiler? Or there is any other way to resolve the issue?

Could someone please help me on this

**Comment by oubidar-Abderrahim** [comment]
I'm closing this issue, if you still need assistance, please re-open and provide the missing information from the comment above. Thank you
