### ISSUE TITLE
ModelMapper causes the executable to crash at runtime

### ISSUE THREAD

**Issue by joaoclaudior** [oracle/graal#6119]
Error in Image Native, Ubuntu 22.0.4. Execute in JVM is OK.
**graalvm-ce-java19-22.3.1**

**POM**
`<dependency>
	<groupId>org.modelmapper</groupId>
	          <artifactId>modelmapper</artifactId>
	<version>3.1.0</version>
</dependency>
`
**In Config Class**
`
@Bean
    public ModelMapper modelMapper() {
        return new ModelMapper();
    }
`
**In Controller**
`

    @Autowired
    private ModelMapper modelMapper;
    private ContactDTO convertToDto(ContactEntity contactEntity) {
        TypeMap<ContactEntity, ContactDTO> typeMap = modelMapper
                .typeMap(ContactEntity.class, ContactDTO.class)
                .implicitMappings()
                .addMappings(mapper -> {
                    mapper.map(source -> source.getPhone(), ContactDTO::setPhoneNumber);
                });

        return typeMap.map(contactEntity);
    }
`

Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed: com.oracle.svm.core.jdk.UnsupportedFeatureError: No classes have been predefined during the image build to load from bytecodes at runtime.] with root cause

com.oracle.svm.core.jdk.UnsupportedFeatureError: No classes have been predefined during the image build to load from bytecodes at runtime.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89) ~[na:na]
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.PredefinedClassesSupport.throwNoBytecodeClasses(PredefinedClassesSupport.java:76) ~[na:na]
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.PredefinedClassesSupport.loadClass(PredefinedClassesSupport.java:130) ~[na:na]
	at java.base@19.0.2/java.lang.ClassLoader.defineClass(ClassLoader.java:294) ~[contact:na]
	at org.modelmapper.internal.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader.invoker(JavaDispatcher.java:1317) ~[na:na]
	at org.modelmapper.internal.bytebuddy.utility.dispatcher.JavaDispatcher$InvokerCreationAction.run(JavaDispatcher.java:444) ~[na:na]
	at org.modelmapper.internal.bytebuddy.utility.dispatcher.JavaDispatcher$InvokerCreationAction.run(JavaDispatcher.java:437) ~[na:na]
	at java.base@19.0.2/java.security.AccessController.executePrivileged(AccessController.java:168) ~[na:na]
	at java.base@19.0.2/java.security.AccessController.doPrivileged(AccessController.java:318) ~[na:na]
	at org.modelmapper.internal.bytebuddy.utility.dispatcher.JavaDispatcher.doPrivileged(JavaDispatcher.java) ~[na:na]
	at org.modelmapper.internal.bytebuddy.utility.dispatcher.JavaDispatcher.<clinit>(JavaDispatcher.java:79) ~[na:na]
	at org.modelmapper.internal.bytebuddy.description.type.TypeDescription$ForLoadedType.<clinit>(TypeDescription.java:8411) ~[na:na]
	at org.modelmapper.internal.bytebuddy.description.type.TypeDescription.<clinit>(TypeDescription.java:65) ~[contact:na]
	at org.modelmapper.internal.bytebuddy.matcher.ElementMatchers.isFinalizer(ElementMatchers.java:1626) ~[na:na]
	at org.modelmapper.internal.bytebuddy.matcher.ElementMatchers.isDefaultFinalizer(ElementMatchers.java:1616) ~[na:na]
	at org.modelmapper.internal.bytebuddy.ByteBuddy.<init>(ByteBuddy.java:287) ~[na:na]
	at org.modelmapper.internal.bytebuddy.ByteBuddy.<init>(ByteBuddy.java:263) ~[na:na]
	at org.modelmapper.internal.ProxyFactory.<clinit>(ProxyFactory.java:46) ~[na:na]
	at org.modelmapper.internal.ReferenceMapExpressionImpl.<init>(ReferenceMapExpressionImpl.java:51) ~[na:na]
	at org.modelmapper.internal.ConfigurableConditionExpressionImpl.<init>(ConfigurableConditionExpressionImpl.java:40) ~[na:na]
	at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:266) ~[na:na]
	at br.com.jcr.contact.resources.ContactResource.convertToDto(ContactResource.java:34) ~[contact:na]
	at java.base@19.0.2/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
	at java.base@19.0.2/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
	at java.base@19.0.2/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[contact:na]
	at java.base@19.0.2/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[contact:na]
	at java.base@19.0.2/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[contact:na]
	at java.base@19.0.2/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[contact:na]
	at java.base@19.0.2/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[contact:na]
	at br.com.jcr.contact.resources.ContactResource.getContactByPhone(ContactResource.java:26) ~[contact:na]
	at java.base@19.0.2/java.lang.reflect.Method.invoke(Method.java:578) ~[contact:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[contact:6.0.5]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152) ~[contact:6.0.5]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[contact:6.0.5]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[contact:6.0.5]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[contact:6.0.5]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[contact:6.0.5]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[contact:6.0.5]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[contact:6.0.5]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[contact:6.0.5]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[contact:6.0.5]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:705) ~[contact:6.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[contact:6.0.5]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:814) ~[contact:6.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223) ~[na:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[na:na]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[contact:10.1.5]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[na:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[na:na]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[contact:6.0.5]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[contact:6.0.5]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[na:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[na:na]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[contact:6.0.5]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[contact:6.0.5]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[na:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[na:na]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[contact:6.0.5]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[contact:6.0.5]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[na:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[na:na]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177) ~[na:na]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[na:na]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[contact:10.1.5]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119) ~[na:na]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[contact:10.1.5]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[na:na]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[na:na]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400) ~[na:na]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[contact:10.1.5]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:859) ~[na:na]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1734) ~[na:na]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[contact:10.1.5]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[na:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[na:na]
	at java.base@19.0.2/java.lang.Thread.run(Thread.java:1589) ~[contact:na]
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775) ~[contact:na]
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203) ~[na:na]

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, could you please try generating the configuration files using the tracing agent as described [here](https://www.graalvm.org/22.3/reference-manual/native-image/metadata/AutomaticMetadataCollection/)? and add the experimental class define support as explained [here](https://www.graalvm.org/22.1/reference-manual/native-image/ExperimentalAgentOptions/). Thank you

**Comment by oubidar-Abderrahim** [comment]
Any updates?
