### ISSUE TITLE
Cannot initialize main class while compiling base Clojure 1.9; 1.8 ok.

### ISSUE THREAD

**Issue by ghadishayban** [oracle/graal#612]
### Reproducible Steps
1. clone https://github.com/ghadishayban/clojure/tree/graal-test
2. `mvn -Plocal clean package -Dmaven.test.skip=true`
3. `graalvm-ce-1.0.0-rc5/bin/native-image -cp clojure.jar clojure.main`

The branch above has a necessary fix for re-balancing monitorenter/exit, unrelated to the encountered error.

### Error output
```
➜  clojure git:(monitor-unbalanced) ✗ graalvm-ce-1.0.0-rc5/bin/native-image -cp clojure.jar clojure.main             
Build on Server(pid: 13403, port: 41481)
   classlist:     952.32 ms
       (cap):     609.66 ms
       setup:     793.01 ms
    analysis:   2,750.15 ms
error: Bytecode parsing error: java.lang.NoClassDefFoundError: Could not initialize class clojure.main
Detailed message:
Error: Bytecode parsing error: java.lang.NoClassDefFoundError: Could not initialize class clojure.main
Trace: 
	at parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:177)
Call path from entry point to com.oracle.svm.core.JavaMainWrapper.run(int, CCharPointerPointer): 
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:148)
	at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Original exception that caused the problem: java.lang.NoClassDefFoundError: Could not initialize class clojure.main
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.initialize(HotSpotResolvedObjectTypeImpl.java:389)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:213)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:193)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:170)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.getDeclaringClass(AnalysisMethod.java:296)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.getSignature(AnalysisMethod.java:273)
	at com.oracle.graal.pointsto.flow.MethodFlowsGraph.<init>(MethodFlowsGraph.java:98)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.<init>(MethodTypeFlow.java:75)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.<init>(AnalysisMethod.java:127)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createMethod(AnalysisUniverse.java:399)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:387)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:364)
	at com.oracle.svm.hosted.phases.IntrinsifyMethodHandlesInvocationPlugin.lookup(IntrinsifyMethodHandlesInvocationPlugin.java:428)
	at com.oracle.svm.hosted.phases.IntrinsifyMethodHandlesInvocationPlugin.processInvokeWithMethodHandle(IntrinsifyMethodHandlesInvocationPlugin.java:394)
	at com.oracle.svm.hosted.phases.IntrinsifyMethodHandlesInvocationPlugin.handleInvoke(IntrinsifyMethodHandlesInvocationPlugin.java:153)
	at org.graalvm.compiler.java.BytecodeParser.tryNodePluginForInvocation(BytecodeParser.java:2163)
	at org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1674)
	at org.graalvm.compiler.java.BytecodeParser.genDynamicInvokeHelper(BytecodeParser.java:1527)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeVirtualHelper(BytecodeParser.java:1553)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1534)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1480)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.genInvokeVirtual(SharedGraphBuilderPhase.java:177)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:4848)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3135)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:2944)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:888)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:782)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:95)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:196)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:315)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:346)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:502)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

Error: Processing image build request failed
```

**Comment by ghadishayban** [comment]
FYI clojure.main loads clojure.lang.RT, which loads clojure.core__init, which has a quite large `<clinit>`

**Comment by cstancu** [comment]
The reported error has been fixed. Now you can successfully build an image with `native-image --report-unsupported-elements-at-runtime  -cp clojure.jar clojure.main`:
```
$ native-image --report-unsupported-elements-at-runtime  -cp clojure.jar clojure.main
Build on Server(pid: 1448, port: 43927)
[clojure.main:1448]    classlist:   1,309.32 ms
[clojure.main:1448]        (cap):     562.67 ms
[clojure.main:1448]        setup:     826.73 ms
Warning: class initialization of class clojure.main failed with exception java.lang.ExceptionInInitializerError. This class will be initialized at run time because either option --report-unsupported-elements-at-runtime or option --allow-incomplete-classpath is used for image building. Use the option --delay-class-initialization-to-runtime=clojure.main to explicitly request delayed initialization of this class.
Warning: class initialization of class clojure.lang.RT failed with exception java.lang.NoClassDefFoundError: Could not initialize class clojure.lang.RT. This class will be initialized at run time because either option --report-unsupported-elements-at-runtime or option --allow-incomplete-classpath is used for image building. Use the option --delay-class-initialization-to-runtime=clojure.lang.RT to explicitly request delayed initialization of this class.
Warning: class initialization of class clojure.lang.Numbers failed with exception java.lang.NoClassDefFoundError: Could not initialize class clojure.lang.RT. This class will be initialized at run time because either option --report-unsupported-elements-at-runtime or option --allow-incomplete-classpath is used for image building. Use the option --delay-class-initialization-to-runtime=clojure.lang.Numbers to explicitly request delayed initialization of this class.
Warning: class initialization of class clojure.lang.Numbers$BigDecimalOps failed with exception java.lang.NoClassDefFoundError: Could not initialize class clojure.lang.Numbers$BigDecimalOps. This class will be initialized at run time because either option --report-unsupported-elements-at-runtime or option --allow-incomplete-classpath is used for image building. Use the option --delay-class-initialization-to-runtime=clojure.lang.Numbers$BigDecimalOps to explicitly request delayed initialization of this class.
Warning: class initialization of class clojure.lang.PersistentTreeMap failed with exception java.lang.NoClassDefFoundError: Could not initialize class clojure.lang.RT. This class will be initialized at run time because either option --report-unsupported-elements-at-runtime or option --allow-incomplete-classpath is used for image building. Use the option --delay-class-initialization-to-runtime=clojure.lang.PersistentTreeMap to explicitly request delayed initialization of this class.
Warning: class initialization of class clojure.lang.Intrinsics failed with exception java.lang.NoClassDefFoundError: Could not initialize class clojure.lang.RT. This class will be initialized at run time because either option --report-unsupported-elements-at-runtime or option --allow-incomplete-classpath is used for image building. Use the option --delay-class-initialization-to-runtime=clojure.lang.Intrinsics to explicitly request delayed initialization of this class.
[clojure.main:1448]   (typeflow):   3,510.91 ms
[clojure.main:1448]    (objects):   2,536.23 ms
[clojure.main:1448]   (features):     131.02 ms
[clojure.main:1448]     analysis:   6,311.87 ms
[clojure.main:1448]     universe:     258.28 ms
[clojure.main:1448]      (parse):     774.44 ms
[clojure.main:1448]     (inline):     776.89 ms
[clojure.main:1448]    (compile):   7,304.44 ms
[clojure.main:1448]      compile:   9,331.61 ms
[clojure.main:1448]        image:     850.60 ms
[clojure.main:1448]        write:     147.98 ms
[clojure.main:1448]      [total]:  19,104.10 ms
```

 However, running it will yield:
```
$ ./clojure.main 
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:281)
	at java.lang.Class.ensureInitialized(DynamicHub.java:402)
	at clojure.main.<clinit>(main.java:20)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:341)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:261)
	at java.lang.Class.ensureInitialized(DynamicHub.java:402)
Caused by: java.io.FileNotFoundException: Could not locate clojure/core__init.class or clojure/core.clj on classpath.
	at clojure.lang.RT.load(RT.java:463)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.lang.RT.doInit(RT.java:468)
	at clojure.lang.RT.<clinit>(RT.java:336)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:341)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:261)
	... 5 more
```

**Comment by jeroenvandijk** [comment]
I've tested the above with clojure 1.8 [1] and compiling works [2]:
```
~/bin/graalvm-ce-1.0.0-rc15/Contents/Home/bin/native-image --report-unsupported-elements-at-runtime  -cp  ~/.m2/repository/org/clojure/clojure/1.8.0/clojure-1.8.0.jar clojure.main
Build on Server(pid: 77535, port: 52731)
[clojure.main:77535]    classlist:   1,440.60 ms
[clojure.main:77535]        (cap):   1,132.83 ms
[clojure.main:77535]        setup:   1,599.17 ms
[clojure.main:77535]   (typeflow):  13,750.47 ms
[clojure.main:77535]    (objects):   6,861.93 ms
[clojure.main:77535]   (features):     451.15 ms
[clojure.main:77535]     analysis:  21,736.99 ms
[clojure.main:77535]     universe:     521.46 ms
[clojure.main:77535]      (parse):   2,570.68 ms
[clojure.main:77535]     (inline):   4,393.10 ms
[clojure.main:77535]    (compile):  24,681.03 ms
[clojure.main:77535]      compile:  33,054.32 ms
[clojure.main:77535]        image:   1,904.39 ms
[clojure.main:77535]        write:     510.15 ms
[clojure.main:77535]      [total]:  61,071.05 ms
```
However running a simple file `foo.clj`
```clj
(println "hi")
```
Gives the defineClass unsupported method error. 
```
➜  ~ ./clojure.main-1.8.0 foo.clj
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported method java.lang.ClassLoader.defineClass(String, byte[], int, int) is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class, compiling:(/Users/jeroen/foo.clj:1:1)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6875)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.eval(Compiler.java:6924)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$script_opt.invokeStatic(main.clj:335)
	at clojure.main$script_opt.invoke(main.clj:330)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported method java.lang.ClassLoader.defineClass(String, byte[], int, int) is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:102)
	at java.lang.ClassLoader.defineClass(Target_java_lang_ClassLoader.java:642)
	at clojure.lang.DynamicClassLoader.defineClass(DynamicClassLoader.java:46)
	at clojure.lang.Compiler$ObjExpr.getCompiledClass(Compiler.java:4903)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4059)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6866)
	... 14 more
```

Is this fixable by adding this (and other methods) to https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md ?

[1] clojure 1.9 and above have more complicated dependencies e.g. clojure.spec
[2] The jar can be fetched from http://central.maven.org/maven2/org/clojure/clojure/1.8.0/clojure-1.8.0.jar

**Comment by PaulSchulz** [comment]
I am seeing this same issue.

**Comment by PaulSchulz** [comment]
I can get GraalVM workimng for me if I follow the inmstructions from here..
https://github.com/BrunoBonacci/graalvm-clojure/blob/master/doc/clojure-graalvm-native-binary.md

(Not sure where the problem is.)

**Comment by borkdude** [comment]
@ghadishayban There is an issue with `locking` in Clojure 1.10. You can try compiling your project with Clojure 1.9 to see if that is the underlying issue. The patch that should fix this is https://clojure.atlassian.net/browse/CLJ-1472. I really hope this makes it in Clojure 1.11, since this comes up a lot. Meanwhile, this is a workaround: https://github.com/taylorwood/clojurl/commit/12b96b5e9a722b372f153436b1f6827709d0f2ab.
