### ISSUE TITLE
Fatal error: com.oracle.svm.core.util.VMError$HostedError: Must be either proven or specified

### ISSUE THREAD

**Issue by SkyeBeFreeman** [oracle/graal#6221]
**Describe the issue**

Build Spring Boot native image and encounter `HostedError`.

**Describe GraalVM and your environment:**
 - GraalVM version: OpenJDK Runtime Environment GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13)
 - JDK major version: 17
 - OS: macOs Monsterey
 - Architecture: AMD64

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
[2/7] Performing analysis...  [*************]                                                          (104.4s @ 4.57GB)
  23,819 (92.35%) of 25,793 classes reachable
  41,890 (67.96%) of 61,638 fields reachable
 122,125 (60.40%) of 202,203 methods reachable
   1,307 classes,   759 fields, and 6,211 methods registered for reflection
       5 native libraries: -framework CoreServices, -framework Foundation, dl, pthread, z

Fatal error: com.oracle.svm.core.util.VMError$HostedError: Must be either proven or specified
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ProvenSafeClassInitializationSupport.reasonForClass(ProvenSafeClassInitializationSupport.java:151)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.lambda$reportKind$4(ClassInitializationFeature.java:220)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.reportKind(ClassInitializationFeature.java:217)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.lambda$reportClassInitializationInfo$3(ClassInitializationFeature.java:209)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.reports.ReportUtils.reportImpl(ReportUtils.java:154)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.reports.ReportUtils.report(ReportUtils.java:90)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.reports.ReportUtils.report(ReportUtils.java:72)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.reports.ReportUtils.report(ReportUtils.java:68)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.reportClassInitializationInfo(ClassInitializationFeature.java:206)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.afterAnalysis(ClassInitializationFeature.java:181)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$12(NativeImageGenerator.java:766)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:85)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:766)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
------------------------------------------------------------------------------------------------------------------------
                        8.7s (7.1% of total time) in 32 GCs | Peak RSS: 5.83GB | CPU load: 4.99
========================================================================================================================

```

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for reaching out about this, could you please specify the following:

Did you generate the config files using the tracing agent before building the native image? if not please do so, you can find more about the tracing agent [here](https://www.graalvm.org/22.3/reference-manual/native-image/metadata/AutomaticMetadataCollection/)

If the issue still occurs, please share a reproducer example we can use to further investigate the issue. Thank you.

**Comment by oubidar-Abderrahim** [comment]
I'm closing this issue for inactivity, please make sure to use the latest GraalVM release with Spring 3.0.0+ and generate the Metadata config files for your application. If you still face the issue, please reopen the ticket and share a reproducer.
