### ISSUE TITLE
Cryptic parsing error messages with `--link-at-build-time` and incomplete classpath

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#6253]
**Describe the issue**
Parsing errors may be cryptic when using `--link-at-build-time` and incomplete classpath.
For instance if a `Class A` cannot be initialized due to a `NoClassDefFoundError` caused by a missing dependency, the user will be presented with an `UnresolvedElementException` stating that some method of `Class A` is unresolved, but it won't provide any additional info on the cause.

**Steps to reproduce the issue**
```
cd /tmp
git clone --branch 2023-03-21-graal-4661-parsing-error https://github.com/zakkak/issue-reproducers reproducer
cd reproducer
mvn package
export JAVA_HOME=/path/to/graalvm
# Attempt to generate native-image
$JAVA_HOME/bin/native-image \
  --no-fallback \
  -H:+ReportExceptionStackTraces \
  --link-at-build-time \
  --initialize-at-build-time=. \
  -jar target/reproducer-1.0-SNAPSHOT.jar
```

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **e9893c06ff637ec859c18dcba53598ca51933af1**
 - JDK major version: **20**
 - OS: **Fedora 37**
 - Architecture: **AMD64**

**More details**

The reproducer will result in build errors like the following:

```
Error: Unsupported features in 2 methods
Detailed message:
Error: Discovered unresolved method during parsing: net.sf.oval.expression.ExpressionLanguageJavaScriptImpl.<init>(). This error is reported at image build time because class net.sf.oval.expression.ExpressionLanguageRegistry is registered for linking at image build time by command line.
Error encountered while parsing net.sf.oval.expression.ExpressionLanguageRegistry.getExpressionLanguage(ExpressionLanguageRegistry.java:78) 
Parsing context:
   at net.sf.oval.AbstractCheck.isActive(AbstractCheck.java:151)
   at net.sf.oval.Validator.checkConstraint(Validator.java:763)
   at net.sf.oval.Validator._validateStaticInvariants(Validator.java:670)
   at net.sf.oval.Validator.validateInvariants(Validator.java:1382)
   at net.sf.oval.Validator.validate(Validator.java:1308)
   at gdv.xport.feld.Feld.validateInvariants(Feld.java:623)
   at gdv.xport.feld.Feld.validate(Feld.java:605)
   at gdv.xport.feld.AlphaNumFeld.validate(AlphaNumFeld.java:161)
   at gdv.xport.feld.Feld.validate(Feld.java:601)
   at gdv.xport.feld.Satznummer.validate(Satznummer.java:232)
   at gdv.xport.feld.Feld.isValid(Feld.java:583)
   at gdv.xport.feld.Feld.isInvalid(Feld.java:592)
   at gdv.xport.satz.Teildatensatz.getSatznummer(Teildatensatz.java:146)
   at gdv.xport.satz.Teildatensatz.toShortString(Teildatensatz.java:589)
   at gdv.xport.satz.Teildatensatz.findFeld(Teildatensatz.java:352)
   at gdv.xport.satz.Teildatensatz.getFeld(Teildatensatz.java:343)
   at gdv.xport.satz.Satz.findFeld(Satz.java:620)
   at gdv.xport.satz.Satz.getFeld(Satz.java:614)
   at gdv.xport.satz.Vorsatz.getErstellungsZeitraumBis(Vorsatz.java:229)
   at gdv.xport.satz.Vorsatz.setErstellungsZeitraumVon(Vorsatz.java:214)
   at gdv.xport.Datenpaket.setErstellungsDatumVon(Datenpaket.java:592)
   at gdv.xport.Datenpaket.<init>(Datenpaket.java:75)
   at gdv.xport.Datenpaket.<init>(Datenpaket.java:62)
   at Main.main(Main.java:5)
   at static root method.(Unknown Source)
...
```

not providing any indication about the reason the said method is unresolved (in this case the absence of `org/mozilla/javascript/Scriptable` from the classpath.

https://github.com/oracle/graal/pull/6245 was meant to address this but it looks like there are cases that still escape.

The issue seems to be caused when Graal ignores `NoClassDefFoundError`s in https://github.com/oracle/graal/blob/e9893c06ff637ec859c18dcba53598ca51933af1/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/phases/SharedGraphBuilderPhase.java#L223-L228

this results in the eager resolution failure to not get logged as the cause of the `UnresolvedElement`.

cc @cstancu

**Comment by knuspertante** [comment]
Hey @zakkak 

I'm back in this game... Unfortunately since I updated some dependencies and restructure my project I'm no longer able to build it with native-image. 

I use the same dependency (gdv.xport at version 6.5.0 now). In a small example like your reproducer (https://github.com/zakkak/mandrel/tree/2023-04-27-fix-6253) all works fine but in a larger project like described  in #5711 it fails. 

To build your reproducer I changed the following things: 

- add org.apache.commons as dependency

```xml
 <dependency>
                    <groupId>org.apache.commons</groupId>
                    <artifactId>commons-jexl3</artifactId>
                    <version>3.2.1</version>
                    <exclusions>
                        <exclusion>
                            <groupId>commons-logging</groupId>
                            <artifactId>commons-logging</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
```

- build native image with --initialize-at-build-time=net.sf.oval.ogn.ObjectGraphNavigatorJXPathImpl\\,\
net.sf.oval.expression\\,org.apache.logging.log4j.util.OsgiServiceLocator

```sh
native-image \
  --no-fallback \
  -H:+ReportExceptionStackTraces \
  --link-at-build-time \
  --initialize-at-build-time=net.sf.oval.ogn.ObjectGraphNavigatorJXPathImpl\\,\
net.sf.oval.expression\\,org.apache.logging.log4j.util.OsgiServiceLocator \
  -jar target/reproducer-1.0-SNAPSHOT.jar
```


Errror message:

```sh
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: gdv.xport.feld.Feld.getInhalt(). This error is reported at image build time because class de.j21p.pandora.core.adapter.input.InputGdvXport is registered for linking at image build time by command line
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:298)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedMethod(SharedGraphBuilderPhase.java:288)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedInvoke(SharedGraphBuilderPhase.java:244)
```

Now I have some trouble... Is it possible to get your pr compiled on my machine? FYI: I didn't compile graalvm by myself for now. Or to get any other support by you?

**Comment by zakkak** [comment]
Hi @knuspertante for building GraalVM from source you may refer to https://github.com/oracle/graal/tree/master/vm#readme

In short:

```
git clone https://github.com/graalvm/mx
git clone https://github.com/zakkak/mandrel --branch 2023-04-27-fix-6253 graal
cd graal/vm
../../mx/mx fetch-jdk --java-distribution labsjdk-ce-17
export JAVA_HOME=...
../../mx/mx --env ni-ce build
```

**Comment by knuspertante** [comment]
> Hi @knuspertante for building GraalVM from source you may refer to https://github.com/oracle/graal/tree/master/vm#readme
> 
> In short:
> 
> ```
> git clone https://github.com/graalvm/mx
> git clone https://github.com/zakkak/mandrel --branch 2023-04-27-fix-6253 graal
> cd graal/vm
> ../../mx/mx fetch-jdk --java-distribution labsjdk-ce-17
> export JAVA_HOME=...
> ../../mx/mx --env ni-ce build
> ```

@zakkak thanks a lot! You are my hero ;-)

**Comment by zakkak** [comment]
As discussed in https://github.com/oracle/graal/pull/6507#issuecomment-1568702628 

> The only real solution for this problem requires extensive JVMCI changes: we would need to preserve resolution and linking errors via JVMCI, where they are currently just ignored.

**Comment by zakkak** [comment]
Unfortunately we are seeing this again with GraalVM for JDK 21 and `master`, see https://github.com/quarkusio/quarkus/pull/41256#issuecomment-2177191739

**Comment by zakkak** [comment]
The new reproducer is:

```
cd /tmp
git clone --branch 2024-10-09-oracle-graal-6253-reproducer https://github.com/zakkak/issue-reproducers reproducers
cd reproducers
mvn package
# run in JVM
java \
  -jar target/reproducer-1.0-SNAPSHOT.jar
# generate native-image with --link-at-build-time
native-image \
  --no-fallback \
  --link-at-build-time  \
  -H:+ReportExceptionStackTraces \
  -jar target/reproducer-1.0-SNAPSHOT.jar
# Build fails
```

**Comment by zakkak** [comment]
Fixed by https://github.com/oracle/graal/pull/10320
