### ISSUE TITLE
java.lang.ClassNotFoundException: javax.validation.ValidationException building native image

### ISSUE THREAD

**Issue by dsyer** [oracle/graal#629]
A simple app with spring-boot on the classpath, but not hibernate-validator, cannot be made into a native image. This code (similar to what Spring Boot does to instantiate `FailureAnalyzers`) fails:

```java
    private Object load() throws Exception {
        String analyzerName = "org.springframework.boot.diagnostics.analyzer.ValidationExceptionFailureAnalyzer";
        try {
            Constructor<?> constructor = Class.forName(analyzerName)
                    .getDeclaredConstructor();
            ReflectionUtils.makeAccessible(constructor);
            return constructor.newInstance();
        }
        catch (Throwable ex) {
            System.out.println("Failed to load " + analyzerName + ", " + ex);
            return null;
        }
    }
```

It fails at build time without really revealing the source of the issue (much trial and error was involved in producing the sample above):

```
$ native-image -H:ReflectionConfigurationFiles=app.json --report-unsupported-elements-at-runtime -cp $CP com.acme.TestApplication
Build on Server(pid: 15654, port: 41853)
   classlist:   4,571.41 ms
       (cap):   1,080.29 ms
       setup:   1,470.39 ms
    analysis:   4,632.80 ms
fatal error: java.lang.NoClassDefFoundError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:414)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:275)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:372)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.executeCompilation(NativeImageBuildServer.java:390)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$processCommand$8(NativeImageBuildServer.java:327)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.withJVMContext(NativeImageBuildServer.java:408)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.processCommand(NativeImageBuildServer.java:324)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.processRequest(NativeImageBuildServer.java:268)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$serve$7(NativeImageBuildServer.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: javax/validation/ValidationException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at com.oracle.svm.reflect.hosted.ReflectionDataBuilder.duringAnalysis(ReflectionDataBuilder.java:162)
	at com.oracle.svm.reflect.hosted.ReflectionFeature.duringAnalysis(ReflectionFeature.java:99)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$doRun$7(NativeImageGenerator.java:696)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:59)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:696)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:397)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: javax.validation.ValidationException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
```

The JSON contains 

```
	{
		"name": "org.springframework.boot.diagnostics.analyzer.ValidationExceptionFailureAnalyzer",
		"allDeclaredConstructors": true
	},
```

**Comment by cstancu** [comment]
This has been fixed. If the reflection configuration registers a type that references a missing type it should print a warning of the form: [`WARNING: Could not register reflection metadata for ... Reason ...`](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/hosted/ReflectionDataBuilder.java#L213) and continue.
