### ISSUE TITLE
Using MBeans related GraalVM Reachability Metadata results in unfixed Exception in specific cases

### ISSUE THREAD

**Issue by linghengqian** [oracle/graal#6322]
**Describe the issue**
A clear and concise description of the issue. We recommend using the [latest snapshot builds](https://github.com/graalvm/graalvm-ce-dev-builds/releases) to replicate the issue as  bugs are constantly being fixed in the master branch

- Using MBeans-related GraalVM reachability metadata can lead to unfixed Exceptions under specific circumstances. This manifests itself as mentioned in https://github.com/spring-projects/spring-boot/issues/33210 .
- These metadata can cause calls to `ManagementFactory.getPlatformMBeanServer()` to fail with `javax.management.openmbean.OpenDataException`. In most cases, it would appear that the metadata is sufficient for the bootstrapping of the MBean server to take a different code path to normal and this path fails. There are reference operations in some PRs, such as https://github.com/oracle/graalvm-reachability-metadata/pull/113 , https://github.com/oracle/graalvm-reachability-metadata/pull/161 , https://github.com/oracle/graalvm-reachability-metadata/pull/162 . This includes the following five packages.
```
java.lang.management.**
jdk.management.**
com.sun.management.**
sun.management.**
javax.management.**
```
- More early investigations are at https://github.com/oracle/graalvm-reachability-metadata/pull/135, https://github.com/oracle/graalvm-reachability-metadata/issues/133 and https://github .com/apache/shardingsphere/issues/21347.
- Unfortunately personally, I've never managed to create a relevant minimal reproducible example, and so far most of the issues related to this have been reported on the Spring side.

**Steps to reproduce the issue**
Please include both build steps as well as run steps

- Due to the large changes in https://github.com/oracle/graalvm-reachability-metadata, it is difficult for me to create a related and reproducible example.

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **[e.g. EE 19.3, CE 20.0, CE 20.1.0-dev-20200304_0848]** `CE 22.3.1`
 - JDK major version: **[e.g.:8]** `17`
 - OS: **[e.g. macOS Catalina]** `Ubuntu 22.04.2`
 - Architecture: **[e.g.: AMD64]** `AMD64`

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```shell
2022-11-15T15:38:18.962+01:00 ERROR 95910 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalArgumentException: javax.management.NotCompliantMBeanException: com.sun.management.GarbageCollectorMXBean: Method com.sun.management.GarbageCollectorMXBean.getLastGcInfo has parameter or return type that cannot be translated into an open type
        at java.management@17.0.5/javax.management.StandardMBean.<init>(StandardMBean.java:271) ~[spring-boot-native-test:na]
        at java.management@17.0.5/javax.management.StandardEmitterMBean.<init>(StandardEmitterMBean.java:148) ~[spring-boot-native-test:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.management.ManagementSupport.addMXBean(ManagementSupport.java:299) ~[na:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.management.ManagementSupport.getPlatformMBeanServer(ManagementSupport.java:285) ~[na:na]
        at java.management@17.0.5/java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:45) ~[na:na]
        at io.micrometer.core.instrument.binder.tomcat.TomcatMetrics.getMBeanServer(TomcatMetrics.java:98) ~[na:na]
        at io.micrometer.core.instrument.binder.tomcat.TomcatMetrics.<init>(TomcatMetrics.java:72) ~[na:na]
        at org.springframework.boot.actuate.metrics.web.tomcat.TomcatMetricsBinder.onApplicationEvent(TomcatMetricsBinder.java:63) ~[spring-boot-native-test:3.0.0-RC2]
        at org.springframework.boot.actuate.metrics.web.tomcat.TomcatMetricsBinder.onApplicationEvent(TomcatMetricsBinder.java:42) ~[spring-boot-native-test:3.0.0-RC2]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[na:na]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[na:na]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:413) ~[spring-boot-native-test:6.0.0-RC4]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370) ~[spring-boot-native-test:6.0.0-RC4]
        at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:103) ~[spring-boot-native-test:3.0.0-RC2]
        at org.springframework.boot.SpringApplicationRunListeners.lambda$started$5(SpringApplicationRunListeners.java:76) ~[na:na]
        at java.base@17.0.5/java.lang.Iterable.forEach(Iterable.java:75) ~[spring-boot-native-test:na]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118) ~[na:na]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112) ~[na:na]
        at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:76) ~[na:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-native-test:3.0.0-RC2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[spring-boot-native-test:3.0.0-RC2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[spring-boot-native-test:3.0.0-RC2]
        at bootnative.SpringBootNativeTestApplication.main(SpringBootNativeTestApplication.java:12) ~[spring-boot-native-test:na]
Caused by: javax.management.NotCompliantMBeanException: com.sun.management.GarbageCollectorMXBean: Method com.sun.management.GarbageCollectorMXBean.getLastGcInfo has parameter or return type that cannot be translated into an open type
        at java.management@17.0.5/com.sun.jmx.mbeanserver.Introspector.throwException(Introspector.java:468) ~[na:na]
        at java.management@17.0.5/com.sun.jmx.mbeanserver.MBeanAnalyzer.<init>(MBeanAnalyzer.java:120) ~[spring-boot-native-test:na]
        at java.management@17.0.5/com.sun.jmx.mbeanserver.MBeanAnalyzer.analyzer(MBeanAnalyzer.java:102) ~[spring-boot-native-test:na]
        at java.management@17.0.5/com.sun.jmx.mbeanserver.MXBeanIntrospector.getAnalyzer(MXBeanIntrospector.java:74) ~[na:na]
        at java.management@17.0.5/com.sun.jmx.mbeanserver.MBeanIntrospector.getPerInterface(MBeanIntrospector.java:192) ~[spring-boot-native-test:na]
        at java.management@17.0.5/com.sun.jmx.mbeanserver.MBeanSupport.<init>(MBeanSupport.java:138) ~[spring-boot-native-test:na]
        at java.management@17.0.5/com.sun.jmx.mbeanserver.MXBeanSupport.<init>(MXBeanSupport.java:66) ~[na:na]
        at java.management@17.0.5/javax.management.StandardMBean.construct(StandardMBean.java:175) ~[spring-boot-native-test:na]
        at java.management@17.0.5/javax.management.StandardMBean.<init>(StandardMBean.java:269) ~[spring-boot-native-test:na]
        ... 23 common frames omitted
Caused by: java.lang.IllegalArgumentException: Method com.sun.management.GarbageCollectorMXBean.getLastGcInfo has parameter or return type that cannot be translated into an open type
        at java.management@17.0.5/com.sun.jmx.mbeanserver.ConvertingMethod.from(ConvertingMethod.java:46) ~[spring-boot-native-test:na]
        at java.management@17.0.5/com.sun.jmx.mbeanserver.MXBeanIntrospector.mFrom(MXBeanIntrospector.java:84) ~[na:na]
        at java.management@17.0.5/com.sun.jmx.mbeanserver.MXBeanIntrospector.mFrom(MXBeanIntrospector.java:54) ~[na:na]
        at java.management@17.0.5/com.sun.jmx.mbeanserver.MBeanAnalyzer.initMaps(MBeanAnalyzer.java:137) ~[spring-boot-native-test:na]
        at java.management@17.0.5/com.sun.jmx.mbeanserver.MBeanAnalyzer.<init>(MBeanAnalyzer.java:118) ~[spring-boot-native-test:na]
        ... 30 common frames omitted
Caused by: javax.management.openmbean.OpenDataException: Cannot convert type: com.sun.management.GcInfo
        at java.management@17.0.5/com.sun.jmx.mbeanserver.DefaultMXBeanMappingFactory.openDataException(DefaultMXBeanMappingFactory.java:1539) ~[na:na]
        at java.management@17.0.5/com.sun.jmx.mbeanserver.DefaultMXBeanMappingFactory.mappingForType(DefaultMXBeanMappingFactory.java:261) ~[na:na]
        at java.management@17.0.5/com.sun.jmx.mbeanserver.ConvertingMethod.<init>(ConvertingMethod.java:212) ~[spring-boot-native-test:na]
        at java.management@17.0.5/com.sun.jmx.mbeanserver.ConvertingMethod.from(ConvertingMethod.java:41) ~[spring-boot-native-test:na]
        ... 34 common frames omitted
Caused by: javax.management.openmbean.OpenDataException: Cannot convert type: java.util.Map<java.lang.String, java.lang.management.MemoryUsage>
        at java.management@17.0.5/com.sun.jmx.mbeanserver.DefaultMXBeanMappingFactory.openDataException(DefaultMXBeanMappingFactory.java:1539) ~[na:na]
        at java.management@17.0.5/com.sun.jmx.mbeanserver.DefaultMXBeanMappingFactory.mappingForType(DefaultMXBeanMappingFactory.java:261) ~[na:na]
        at java.management@17.0.5/com.sun.jmx.mbeanserver.DefaultMXBeanMappingFactory.makeCompositeMapping(DefaultMXBeanMappingFactory.java:475) ~[na:na]
        at java.management@17.0.5/com.sun.jmx.mbeanserver.DefaultMXBeanMappingFactory.makeMapping(DefaultMXBeanMappingFactory.java:294) ~[na:na]
        at java.management@17.0.5/com.sun.jmx.mbeanserver.DefaultMXBeanMappingFactory.mappingForType(DefaultMXBeanMappingFactory.java:259) ~[na:na]
        ... 36 common frames omitted
Caused by: javax.management.openmbean.OpenDataException: Cannot convert type: java.lang.management.MemoryUsage
        at java.management@17.0.5/com.sun.jmx.mbeanserver.DefaultMXBeanMappingFactory.openDataException(DefaultMXBeanMappingFactory.java:1539) ~[na:na]
        at java.management@17.0.5/com.sun.jmx.mbeanserver.DefaultMXBeanMappingFactory.mappingForType(DefaultMXBeanMappingFactory.java:261) ~[na:na]
        at java.management@17.0.5/com.sun.jmx.mbeanserver.DefaultMXBeanMappingFactory.makeTabularMapping(DefaultMXBeanMappingFactory.java:364) ~[na:na]
        at java.management@17.0.5/com.sun.jmx.mbeanserver.DefaultMXBeanMappingFactory.makeParameterizedTypeMapping(DefaultMXBeanMappingFactory.java:406) ~[na:na]
        at java.management@17.0.5/com.sun.jmx.mbeanserver.DefaultMXBeanMappingFactory.makeMapping(DefaultMXBeanMappingFactory.java:297) ~[na:na]
        at java.management@17.0.5/com.sun.jmx.mbeanserver.DefaultMXBeanMappingFactory.mappingForType(DefaultMXBeanMappingFactory.java:259) ~[na:na]
        ... 39 common frames omitted
Caused by: javax.management.openmbean.OpenDataException: Can't map java.lang.management.MemoryUsage to an open data type
        at java.management@17.0.5/com.sun.jmx.mbeanserver.DefaultMXBeanMappingFactory.makeCompositeMapping(DefaultMXBeanMappingFactory.java:462) ~[na:na]
        at java.management@17.0.5/com.sun.jmx.mbeanserver.DefaultMXBeanMappingFactory.makeMapping(DefaultMXBeanMappingFactory.java:294) ~[na:na]
        at java.management@17.0.5/com.sun.jmx.mbeanserver.DefaultMXBeanMappingFactory.mappingForType(DefaultMXBeanMappingFactory.java:259) ~[na:na]
        ... 43 common frames omitted
```

**Comment by fniephaus** [comment]
Thanks for raising this. Do you run into these problems without using the `--enable-monitoring` flag?
cc @roberttoyonaga

**Comment by linghengqian** [comment]
> Thanks for raising this. Do you run into these problems without using the `--enable-monitoring` flag?
> cc @roberttoyonaga 

- Unfortunately, I've never been able to directly reproduce this issue locally, and all issues seem to require specific versions of GraalVM Reachability Metadata and Spring Boot.  

- Existing reports point to a specific issue on the Spring Boot side, and over time this issue has become increasingly difficult to reproduce due to the evolution of the GraalVM Reachability Metadata central repository.  I suspect this has something to do with GraalVM Native Image not yet supporting JMX server directly.  

- CC @derkoe @wilkinsona I want to confirm if there is a minimal reproducible example available?

**Comment by solaanan** [comment]
Hello @linghengqian, did you manage to create a reproducer for this issue? Thank you.

**Comment by linghengqian** [comment]
> Hello @linghengqian, did you manage to create a reproducer for this issue? Thank you.

- I am totally unable to reproduce the situation described by @wilkinsona . 

- @wilkinsona Any further findings on the Spring side? I will close this issue without more information.

**Comment by solaanan** [comment]
Closing this issue due to absence of a reproducer, please feel free to reopen or to create a new issue if you still need assistance.
