### ISSUE TITLE
'error: unsupported features' when building substratevm

### ISSUE THREAD

**Issue by cushon** [oracle/graal#633]
I can't build the substrateVM at head. This is probably user error, but do you have any pointers?

```
TMPDIR=$(mktemp -d)
cd $TMPDIR
git clone -q git@github.com:oracle/graal.git
git clone -q git@github.com:graalvm/mx.git
wget -q https://github.com/graalvm/openjdk8-jvmci-builder/releases/download/jvmci-0.48/openjdk-8u172-jvmci-0.48-linux-amd64.tar.gz
tar xzf openjdk-8u172-jvmci-0.48-linux-amd64.tar.gz
cd graal/vm
JAVA_HOME=$TMPDIR/openjdk1.8.0_172-jvmci-0.48/ $TMPDIR/mx/mx --dynamicimports /substratevm build
```

```
error: unsupported features in 7 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a started Thread in the image heap. This is not supported. The object was reached from a static initializer. All static class initialization is done during native image construction, thus a static initializer cannot contain code that captures state dependent on the build machine. Write your own initialization methods and call them explicitly from your main entry point.
Trace: 
	at parsing org.graalvm.compiler.hotspot.management.HotSpotGraalManagement.initialize(HotSpotGraalManagement.java:68)
Call path from entry point to org.graalvm.compiler.hotspot.management.HotSpotGraalManagement.initialize(HotSpotGraalRuntime): 
	at org.graalvm.compiler.hotspot.management.HotSpotGraalManagement.initialize(HotSpotGraalManagement.java:60)
	at org.graalvm.compiler.hotspot.HotSpotGraalRuntime.<init>(HotSpotGraalRuntime.java:163)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:145)
	at org.graalvm.compiler.truffle.runtime.hotspot.HotSpotTruffleRuntimeAccess$LazyGraalRuntime.getCompiler(HotSpotTruffleRuntimeAccess.java:104)
	at org.graalvm.compiler.truffle.runtime.hotspot.HotSpotTruffleRuntimeAccess$LazyGraalRuntime.get(HotSpotTruffleRuntimeAccess.java:88)
	at org.graalvm.compiler.truffle.runtime.hotspot.HotSpotTruffleRuntimeAccess$LazyGraalRuntime.get(HotSpotTruffleRuntimeAccess.java:79)
	at org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.getGraalRuntime(GraalTruffleRuntime.java:250)
	at org.graalvm.compiler.truffle.runtime.hotspot.HotSpotTruffleRuntime.getVMConfig(HotSpotTruffleRuntime.java:232)
	at org.graalvm.compiler.truffle.runtime.hotspot.HotSpotTruffleRuntime.notifyTransferToInterpreter(HotSpotTruffleRuntime.java:307)
	at com.oracle.truffle.api.CompilerDirectives.transferToInterpreter(CompilerDirectives.java:68)
	at com.oracle.truffle.api.impl.ReadOnlyArrayList$LI.next(ReadOnlyArrayList.java:264)
	at java.util.concurrent.CopyOnWriteArrayList.equals(CopyOnWriteArrayList.java:1042)
	at java.util.Arrays.equals(Arrays.java:2829)
	at org.graalvm.compiler.hotspot.BootstrapWatchDog.run(BootstrapWatchDog.java:180)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:238)
	at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_002epthreadStartRoutine_0028com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_0024ThreadStartData_0029(generated:0)
```

Here's the full output from the build: https://gist.githubusercontent.com/cushon/45efc5682ac0440dc6e879c04e9cfd09/raw/099274672cdd0e259183181716ab4311872a55d4/gistfile1.txt

**Comment by dougxc** [comment]
I don't know what the underlying issue is, but it seems like using the `--disable-polyglot` and `--force-bash-launchers=true` options is a workaround:
```
mx --disable-libpolyglot --force-bash-launchers=true --dynamicimports /substratevm build
```

**Comment by ansalond** [comment]
This was fixed as part of https://github.com/oracle/graal/commit/51dd81d259ab9fec85cb8f34fb4dcbdaf57d5e5f:
```
mx --dynamicimports /substratevm build
```
now builds a GraalVM image with Graal, SubstrateVM, Truffle, the `polyglot` native launcher and `libpolyglot` (the polyglot shared library).
Since no language is included, you most likely do not need the polyglot launcher and library. To exclude them from the build:
```
mx --dynamicimports /substratevm --disable-polyglot --disable-libpolyglot build
```
