### ISSUE TITLE
Segfault detected when run the Native Executable with Jep(Java Embedded Python)

### ISSUE THREAD

**Issue by tangjing2022** [oracle/graal#6345]
**Describe the issue**
I'm using [Jep](https://github.com/ninia/jep/) to call python in Java. It works well in JVM, but when I build to the Native Executable and run it, it crashed. Source code:
```
import jep.SharedInterpreter;

public class JepTest {
    public static void main(String[] args) {
        try(SharedInterpreter interpreter = new SharedInterpreter()){
            interpreter.exec("import sys");                                  //ok
            interpreter.exec("sys.path.append(\".\")");
	    System.out.println("import jep_test");
            interpreter.exec("import jep_test");                           //crash occurred
            interpreter.exec("s = jep_test.func()");
            String s = interpreter.getValue("s", String.class);
            System.out.println(s);
        }
    }
}
```

**Steps to reproduce the issue**
build steps:
1. `git clone https://github.com/tangjing2022/jep-demo.git`
2. `cd jep-demo`
3. `python -m venv venv`
4. `source venv/bin/activate`
5. `python -m pip install jep`
6. `javac -cp .:./venv/lib/python3.7/site-packages/jep/jep-4.1.1.jar JepTest.java`
7. `java -agentlib:native-image-agent=config-output-dir=native-image -cp .:./venv/lib/python3.7/site-packages/jep/jep-4.1.1.jar JepTest`
8. `native-image -cp .:./venv/lib/python3.7/site-packages/jep/jep-4.1.1.jar -H:ConfigurationFileDirectories=native-image JepTest`

run steps:
`./jeptest`

**Describe GraalVM and your environment:**
 - GraalVM version 
 ```
openjdk 11.0.18 2023-01-17
OpenJDK Runtime Environment GraalVM CE 22.3.1 (build 11.0.18+10-jvmci-22.3-b13)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.1 (build 11.0.18+10-jvmci-22.3-b13, mixed mode, sharing)
```
 - JDK major version: **11**
 - Python version: **Python 3.7.9**
 - OS: **Ubuntu 16.04.7 LTS**
 - Architecture: **AMD64**

**More details**

when I run the executable,
```
(venv) tj@ubuntu:/opt/jep$ ./jeptest 
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /opt/jep/venv/lib/python3.7/site-packages/jep/libjep.so
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryAbsolute(NativeLibrarySupport.java:92)
	at java.base@11.0.18/java.lang.ClassLoader.loadLibrary(ClassLoader.java:124)
	at java.base@11.0.18/java.lang.Runtime.load0(Runtime.java:768)
	at java.base@11.0.18/java.lang.System.load(System.java:1835)
	at jep.LibraryLocator.searchPackageDir(LibraryLocator.java:243)
	at jep.LibraryLocator.searchSitePackages(LibraryLocator.java:146)
	at jep.LibraryLocator.findJepLibrary(LibraryLocator.java:325)
	at jep.MainInterpreter.initialize(MainInterpreter.java:131)
	at jep.MainInterpreter.getMainInterpreter(MainInterpreter.java:101)
	at jep.Jep.<init>(Jep.java:133)
	at jep.SharedInterpreter.<init>(SharedInterpreter.java:60)
	at JepTest.main(JepTest.java:10)
```
```
(venv) tj@ubuntu:/opt/jep$ ld /opt/jep/venv/lib/python3.7/site-packages/jep/libjep.so
ld: warning: libjvm.so, needed by /opt/jep/venv/lib/python3.7/site-packages/jep/libjep.so, not found (try using -rpath or -rpath-link)
ld: warning: cannot find entry symbol _start; not setting start address
/opt/jep/venv/lib/python3.7/site-packages/jep/libjep.so: undefined reference to `JNI_GetCreatedJavaVMs@SUNWprivate_1.1'
```
It seems libjep.so can't find libjvm.so, so I copy libjvm.so to /usr/lib/, then I get this error:
```
(venv) tj@ubuntu:/opt/jep$ ./jeptest 
import jep_test

[ [ SubstrateSegfaultHandler caught a segfault in thread 0x0000000002f500c0 ] ]
siginfo: si_signo: 11, si_code: 128, si_addr: 0x0000000000000000

Current timestamp: 1680509082644

General purpose register values:
  RAX 0x048b483878c08548 is an unknown value
  RBX 0x0000000000000000 
  RCX 0x0000000000000000 
  RDX 0x0000000000000000 
  RBP 0x00007fb8b11c0670 is an unknown value
  RSI 0x00007fff6ce92ff0 points into the stack for thread 0x0000000002f500c0
  RDI 0x00007fb8b091de9b is an unknown value
  RSP 0x00007fff6ce92fe0 points into the stack for thread 0x0000000002f500c0
  R8  0x00007fff6ce92fe8 points into the stack for thread 0x0000000002f500c0
  R9  0x0000000000000001 is an unknown value
  R10 0x00007fff6ce92fe4 points into the stack for thread 0x0000000002f500c0
  R11 0x000000000042f440 points into AOT compiled code 
  R12 0x00007fb8b1b3dcd0 is an unknown value
  R13 0x00007fb8b0dcaac0 is an unknown value
  R14 0x00007fb8b0df38a0 is an unknown value
  R15 0x00007fb8b11c0670 is an unknown value
  EFL 0x0000000000010246 is an unknown value
  RIP 0x00007fb8b0de2797 is an unknown value
  
Printing Instructions (ip=0x00007fb8b0de2797):
  0x00007fb8b0de2777: 0x25 0x28 0x00 0x00 0x00 0x48 0x89 0x44 0x24 0x18 0x31 0xc0 0xe8 0x98 0x6e 0xff
  0x00007fb8b0de2787: 0xff 0x48 0x8b 0x7c 0x24 0x08 0x31 0xd2 0x48 0x8d 0x74 0x24 0x10 0x48 0x8b 0x07
  0x00007fb8b0de2797: 0xff 0x50 0x38 0x48 0x8b 0x4c 0x24 0x18 0x64 0x48 0x33 0x0c 0x25 0x28 0x00 0x00
  0x00007fb8b0de27a7: 0x00 0x48 0x8b 0x44 0x24 0x10 0x75 0x05 0x48 0x83 0xc4 0x28 0xc3 0xe8 0x27 0x71

Top of stack (sp=0x00007fff6ce92fe0):
  0x00007fff6ce92fe0: 0x00000000000000a0 0x00007fb8b091de9b
  0x00007fff6ce92ff0: 0x0000000000000000 0x0a3504764658d300
  0x00007fff6ce93000: 0x0000000000000017 0x00007fb8b0df38e7
  0x00007fff6ce93010: 0x00007fff6ce93058 0x00007fff6ce93064
  0x00007fff6ce93020: 0x00007fb8b1b3dcd0 0x00007fb8b1b02470
  0x00007fff6ce93030: 0x0000000002f78910 0x00007fb8b0d60d00
  0x00007fff6ce93040: 0x0000000000000002 0x00007fb8b30c1450
  0x00007fff6ce93050: 0x00000000000000a0 0x00007fb8b093ef1e
  0x00007fff6ce93060: 0x0000000002f679a0 0x0000000000000000
  0x00007fff6ce93070: 0x00007fb8b11c0670 0x00007fb8b1b3dcd0
  0x00007fff6ce93080: 0x00007fb8b0dcaac0 0x00007fb8b0df38a0
  0x00007fff6ce93090: 0x00007fb8b0d66c70 0x00007fb8b08e8014
  0x00007fff6ce930a0: 0x00007fb8b0df3580 0x0000000000000000
  0x00007fff6ce930b0: 0x00007fb8b31d3390 0x00007fb8b1b37410
  0x00007fff6ce930c0: 0x00007fb8b1b0245a 0x00007fb8b1b375b0
  0x00007fff6ce930d0: 0x0000000002f679a0 0x00007fb8b1b375a0
  0x00007fff6ce930e0: 0x00007fb8b11c0670 0x00007fb8b08be51a
  0x00007fff6ce930f0: 0x00007fb8b1b375a0 0x00007fb8b1b02450
  0x00007fff6ce93100: 0x0000000000000000 0x00007fb8b1b01640
  0x00007fff6ce93110: 0x00007fb8b1b7da50 0xffffffff00000000
  0x00007fff6ce93120: 0x00007fb8b1b37598 0x00007fb8b1b37578
  0x00007fff6ce93130: 0x00007fb8b1b015f0 0x00007fff6ce931a0
  0x00007fff6ce93140: 0x00007fff6ce93188 0x00007fff6ce931b0
  0x00007fff6ce93150: 0x00007fff6ce93198 0x00007fb8b11c0670
  0x00007fff6ce93160: 0x00007fff6ce931e8 0x00007fb8b1b01230
  0x00007fff6ce93170: 0x00007fb8b31d67f0 0x59f9ea51ffffffff
  0x00007fff6ce93180: 0x00007fb8a4015360 0x00007fb8b31decd0
  0x00007fff6ce93190: 0x00007fb8b1b01230 0x00007fb8b091de2d
  0x00007fff6ce931a0: 0x00007fb8b31fb120 0x0000000000000009
  0x00007fff6ce931b0: 0x00007fb8b1b7da50 0x00007fb8b322c910
  0x00007fff6ce931c0: 0x00007fb8a4015360 0x0000000000000000
  0x00007fff6ce931d0: 0x00007fb8b1b01230 0x00007fb8b0a25388

Top frame info:
  Does not look like a Java Frame. Use JavaFrameAnchors to find LastJavaSP:
  Found matching Anchor:0x00007fff6ce93ee0
  LastJavaSP 0x00007fff6ce93ec0
  LastJavaIP 0x0000000000765ffe
  
Threads:
  0x00007fb8a40008c0 STATUS_IN_NATIVE (ALLOW_SAFEPOINT) "JepMainInterpreter" - 0x00007fb8b1a02ef8, daemon, stack(0x00007fb8a9ea4000,0x00007fb8aa6a4000)
  0x00007fb8ac0008c0 STATUS_IN_NATIVE (ALLOW_SAFEPOINT) "Reference Handler" - 0x00007fb8b20b08d0, daemon, stack(0x00007fb8b1200000,0x00007fb8b1a00000)
  0x0000000002f500c0 STATUS_IN_JAVA (PREVENT_VM_FROM_REACHING_SAFEPOINT) "main" - 0x00007fb8b20b0818, stack(0x00007fff6c696000,0x00007fff6ce95000)
  
VM thread locals for the failing thread 0x0000000002f500c0:
  0 (8 bytes): JNIThreadLocalEnvironment.jniFunctions = (bytes) 
    0x0000000002f500c0: 0x00007fb8b1f5c010
  8 (8 bytes): StackOverflowCheckImpl.stackBoundaryTL = (Word) 1 (0x0000000000000001)
  16 (4 bytes): Safepoint.safepointRequested = (int) 2146168532 (0x7febeed4)
  20 (4 bytes): StatusSupport.statusTL = (int) 1 (0x00000001)
  24 (32 bytes): ThreadLocalAllocation.regularTLAB = (bytes) 
    0x0000000002f500d8: 0x00007fb8a8d00000 0x00007fb8a8e00000
    0x0000000002f500e8: 0x00007fb8a8d9cec8 0x0000000000000000
  56 (8 bytes): PlatformThreads.currentThread = (Object) java.lang.Thread (0x00007fb8b20b0818)
  64 (8 bytes): JavaFrameAnchors.lastAnchor = (Word) 140735020613344 (0x00007fff6ce93ee0)
  72 (8 bytes): AccessControlContextStack = (Object) java.util.ArrayDeque (0x00007fb8b1a03170)
  80 (8 bytes): ExceptionUnwind.currentException = (Object) null
  88 (8 bytes): IdentityHashCodeSupport.hashCodeGeneratorTL = (Object) java.util.SplittableRandom (0x00007fb8a8d9c9a0)
  96 (8 bytes): IsolatedCompileClient.currentClient = (Object) null
  104 (8 bytes): IsolatedCompileContext.currentContext = (Object) null
  112 (8 bytes): JNIObjectHandles.handles = (Object) com.oracle.svm.core.handles.ThreadLocalHandles (0x00007fb8b1a011a0)
  120 (8 bytes): JNIThreadLocalPendingException.pendingException = (Object) null
  128 (8 bytes): JNIThreadLocalPinnedObjects.pinnedObjectsListHead = (Object) com.oracle.svm.core.jni.JNIThreadLocalPinnedObjects$PinnedObjectListNode (0x00007fb8a8d9cea0)
  136 (8 bytes): JNIThreadOwnedMonitors.ownedMonitors = (Object) null
  144 (8 bytes): NoAllocationVerifier.openVerifiers = (Object) null
  152 (8 bytes): ThreadingSupportImpl.activeTimer = (Object) null
  160 (8 bytes): SubstrateDiagnostics.threadOnlyAttachedForCrashHandler = (bytes) 
    0x0000000002f50160: 0x0000000000000000
  168 (8 bytes): ThreadLocalAllocation.allocatedBytes = (Word) 6266576 (0x00000000005f9ed0)
  176 (8 bytes): VMThreads.IsolateTL = (Word) 140431232860160 (0x00007fb8b1c00000)
  184 (8 bytes): VMThreads.OSThreadHandleTL = (Word) 140431256319744 (0x00007fb8b325f700)
  192 (8 bytes): VMThreads.OSThreadIdTL = (Word) 140431256319744 (0x00007fb8b325f700)
  200 (8 bytes): VMThreads.StackBase = (Word) 140735020617728 (0x00007fff6ce95000)
  208 (8 bytes): VMThreads.StackEnd = (Word) 140735012233216 (0x00007fff6c696000)
  216 (8 bytes): VMThreads.StartedByCurrentIsolate = (bytes) 
    0x0000000002f50198: 0x0000000000000000
  224 (8 bytes): VMThreads.nextTL = (Word) 0 (0x0000000000000000)
  232 (8 bytes): VMThreads.unalignedIsolateThreadMemoryTL = (Word) 49610912 (0x0000000002f500a0)
  240 (4 bytes): ActionOnExitSafepointSupport.actionTL = (int) 0 (0x00000000)
  244 (4 bytes): ActionOnTransitionToJavaSupport.actionTL = (int) 0 (0x00000000)
  248 (4 bytes): ImplicitExceptions.implicitExceptionsAreFatal = (int) 0 (0x00000000)
  252 (4 bytes): StackOverflowCheckImpl.yellowZoneStateTL = (int) 2130640638 (0x7efefefe)
  256 (4 bytes): StatusSupport.safepointBehaviorTL = (int) 1 (0x00000001)
  260 (4 bytes): ThreadingSupportImpl.currentPauseDepth = (int) 0 (0x00000000)
  
No VMOperation in progress

The 15 most recent VM operation status changes (oldest first):
  
Counters:
  
Java frame anchors for the failing thread 0x0000000002f500c0:
  Anchor 0x00007fff6ce93ee0 LastJavaSP 0x00007fff6ce93ec0 LastJavaIP 0x0000000000765ffe
  
Stacktrace for the failing thread 0x0000000002f500c0:
  SP 0x00007fff6ce92fe0 IP 0x00007fb8b0de2797  IP is not within Java code. Trying frame anchor of last Java frame instead.
  SP 0x00007fff6ce93ec0 IP 0x0000000000765ffe  [image code] jep.Jep.exec(Jep.java)
  SP 0x00007fff6ce93f20 IP 0x0000000000765f24  [image code] jep.Jep.exec(Jep.java:341)
  SP 0x00007fff6ce93f40 IP 0x0000000000405123  [image code] JepTest.main(JepTest.java:14)
  SP 0x00007fff6ce93f70 IP 0x00000000004100a4  [image code] com.oracle.svm.core.JavaMainWrapper.runCore0(JavaMainWrapper.java:175)
  SP 0x00007fff6ce93fa0 IP 0x000000000040fd75  [image code] com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:135)
  SP 0x00007fff6ce93fa0 IP 0x000000000040fd75  [image code] com.oracle.svm.core.JavaMainWrapper.doRun(JavaMainWrapper.java:232)
  SP 0x00007fff6ce93fd0 IP 0x000000000042fc8b  [image code] com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:218)
  SP 0x00007fff6ce93fd0 IP 0x000000000042fc8b  [image code] com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_3148eece06270530b6e0d4d60311411342c82698(IsolateEnterStub.java:0)
  
VM mutexes:
  mutex "thread" is unlocked.
  mutex "referencePendingList" is unlocked.
  mutex "mainVMOperationControlWorkQueue" is unlocked.
  
AOT compiled code is mapped at 0x0000000000405000 - 0x00000000007f7f9f

Heap settings and statistics:
  Supports isolates: true
  Heap base: 0x00007fb8b1c00000
  Object reference size: 8
  Aligned chunk size: 1048576
  Incremental collections: 0
  Complete collections: 0
  
Native image heap boundaries:
  ReadOnly Primitives: 0x00007fb8b1d01028 - 0x00007fb8b1e24218
  ReadOnly References: 0x00007fb8b1e24218 - 0x00007fb8b1f5bb08
  ReadOnly Relocatables: 0x00007fb8b1f5c000 - 0x00007fb8b1fc9ba0
  Writable Primitives: 0x00007fb8b1fca000 - 0x00007fb8b2066c58
  Writable References: 0x00007fb8b2066c58 - 0x00007fb8b224cf58
  Writable Huge: 0x0000000000000000 - 0x0000000000000000
  ReadOnly Huge: 0x00007fb8b2300030 - 0x00007fb8b240a618

Heap:
  Young generation: 
    Eden: 
      edenSpace:
        aligned: 0/0 unaligned: 0/0
    Survivors: 
      Survivor-1 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-1 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-2 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-2 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-3 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-3 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-4 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-4 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-5 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-5 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-6 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-6 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-7 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-7 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-8 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-8 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-9 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-9 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-10 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-10 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-11 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-11 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-12 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-12 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-13 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-13 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-14 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-14 To:
        aligned: 0/0 unaligned: 0/0
      Survivor-15 From:
        aligned: 0/0 unaligned: 0/0
      Survivor-15 To:
        aligned: 0/0 unaligned: 0/0
  Old generation: 
    oldFromSpace:
      aligned: 0/0 unaligned: 0/0
    oldToSpace:
      aligned: 0/0 unaligned: 0/0
    
  Unused:
    aligned: 0/0

Segfault detected, aborting process. Use runtime option -R:-InstallSegfaultHandler if you don't want to use SubstrateSegfaultHandler.

```
I aslo tried debug it with gdb, crash occurred at  `    private native void exec(long var1, String var3) throws JepException;`
I don't know how to debug this native function.
Please help me to repair this bug,thanks.

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, we'll take a look into this shortly

**Comment by oubidar-Abderrahim** [comment]
Hi, sorry for this late response. I had issues running the reproducer. after building I get the following error even after adding jep.jar to the classpath.

```
> ./jeptest
Exception in thread "main" java.lang.NoClassDefFoundError: jep.SharedInterpreter
	at JepTest.main(JepTest.java:5)
```

We've solved a similar issue in GraalVM 22.3.2, can you please verify with that version?

**Comment by fjtirado** [comment]
I run into similar issue with this python code 
```
try (Interpreter interp = new SharedInterpreter()) {
			interp.exec("s=\"manoolo\"");
			interp.set("x",1);  
			System.out.println(interp.getValue("s"));  // that works and prints manoolo
			System.out.println(interp.getValue("x")); // that fails with a segmentation fault
		}
```
If I change set("x",1) to set("x",false) it woked and prints false. So there is something happening with getValue() and int types

This is the native-image line Im using

```
[ftirados@localhost classes]$ native-image PythonCaller -cp .:$HOME/.m2/repository/black/ninia/jep/4.1.1/jep-4.1.1.jar -H:+ReportExceptionStackTraces -H:JNIConfigurationFiles=/home/ftirados/git/kogito-runtimes/quarkus/addons/python/runtime/src/main/resources/META-INF/native-image/jni-config.json -H:NativeLinkerOption=/home/ftirados/.local/lib/python3.11/site-packages/jep/libjep.so -g -H:ResourceConfigurationFiles=/home/ftirados/git/kogito-runtimes/quarkus/addons/python/runtime/src/main/resources/META-INF/native-image/resource-config.json -H:ReflectionConfigurationFiles=/home/ftirados/git/kogito-runtimes/quarkus/addons/python/runtime/src/main/resources/META-INF/native-image/reflect-config.json -H:DynamicProxyConfigurationFiles=/home/ftirados/git/kogito-runtimes/quarkus/addons/python/runtime/src/main/resources/META-INF/native-image/proxy-config.json
========================================================================================================================
GraalVM Native Image: Generating 'pythoncaller' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                    (2.8s @ 0.20GB)
 Version info: 'GraalVM 22.3.2 Java 11 CE'
 Java version info: '11.0.19+7-jvmci-22.3-b18'
 C compiler: gcc (redhat, x86_64, 13.1.1)
 Garbage collector: Serial GC
```

**Comment by fjtirado** [comment]
After looking at JEP code, I think the issue is here 
https://github.com/ninia/jep/blob/master/src/main/c/Jep/convert_p2j.c#L1074-L1089
So basically, string and boolean are working, but long is not, which is just after the numpy check. 
It is just a matter of making the numpy check work ;) (easy to say, continue looking)

**Comment by fjtirado** [comment]
If I install JEP without numpy installed, the program works as expected and 1 is printed. So probably an issue to be discussed in numpy/jep channel, not graalvm

**Comment by fjtirado** [comment]
If we compare [io](https://github.com/python/cpython/blob/3.11/Lib/io.py)  and [traceback](https://github.com/python/cpython/blob/3.11/Lib/traceback.py), we see that traceback is importing a submodule (collections.abc contains a dot), if we try to import collections.abc  it failed, if we try to import collections it works. Maybe it has something to do with the fact that it contains a dot?
[CAPI ](https://scicomp.ethz.ch/public/manual/Python/3.6.0/c-api.pdf) states
The Python/C API, Release 3.6.0
first. Each cleanup function will be called at most once. Since Python’s internal finalization will have completed
before the cleanup function, no Python APIs should be called by func.
6.4 Importing Modules
_PyObject* PyImport_ImportModule(const char *name)
Return value: New reference. This is a simplified interface to PyImport_ImportModuleEx() below,
leaving the globals and locals arguments set to NULL and level set to 0. When the name argument contains
a dot (when it specifies a submodule of a package), the fromlist argument is set to the list [’*’] so that the
return value is the named module rather than the top-level package containing it as would otherwise be the
case. (Unfortunately, this has an additional side effect when name in fact specifies a subpackage instead of a
submodule: the submodules specified in the package’s __all__ variable are loaded.) Return a new reference
to the imported module, or NULL with an exception set on failure. A failing import of a module doesn’t leave
the module in sys.modules.
This function always uses absolute imports._

**Comment by fjtirado** [comment]
So far, this imports works
```
interp.exec("import itertools");
interp.exec("import sys");
interp.exec("import collections");
interp.exec("import functools");
interp.exec("import os");
interp.exec("import re");
```

but not
`interp.exec("import collections.abc");`

**Comment by fjtirado** [comment]
The culprit that prevents non built-in modules to be loaded is here
https://github.com/ninia/jep/blob/master/src/main/python/jep/java_import_hook.py#L109-L113
Commenting that disable Java package loading, but makes import of not builtin python packages work.

**Comment by fjtirado** [comment]
Just for reference, there are the [jni-config.json](https://github.com/kiegroup/kogito-runtimes/blob/main/quarkus/addons/python/runtime/src/main/resources/META-INF/native-image/jni-config.json) and [reflect-config.json](https://github.com/kiegroup/kogito-runtimes/blob/main/quarkus/addons/python/runtime/src/main/resources/META-INF/native-image/reflect-config.json) being used to make python import work.

**Comment by oubidar-Abderrahim** [comment]
Good to hear, I'm closing this issue for now. If the issue is still present please reopen or create a new ticket for it.
