### ISSUE TITLE
Spring Boot Project using redis, failed with exception: Caused by: java.lang.UnsatisfiedLinkError: jdk.jfr.internal.JVM.getHandler(Ljava/lang/Class;)Ljava/lang/Object; [symbol: Java_jdk_jfr_internal_JVM_getHandler or Java_jdk_jfr_internal_JVM_getHandler__Ljava_lang_Class_2]

### ISSUE THREAD

**Issue by peterhonneparker** [oracle/graal#6357]
## Runtime error trace
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'enableRedisKeyspaceNotificationsInitializer': jdk.jfr.internal.JVM.getHandler(Ljava/lang/Class;)Ljava/lang/Object; [symbol: Java_jdk_jfr_internal_JVM_getHandler or Java_jdk_jfr_internal_JVM_getHandler__Ljava_lang_Class_2]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1751) ~[auth-client.exe:6.0.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[auth-client.exe:6.0.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[auth-client.exe:6.0.4]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[auth-client.exe:6.0.4]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[auth-client.exe:6.0.4]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[auth-client.exe:6.0.4]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[auth-client.exe:6.0.4]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:961) ~[auth-client.exe:6.0.4]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:915) ~[auth-client.exe:6.0.4]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[auth-client.exe:6.0.4]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[auth-client.exe:3.0.2]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[auth-client.exe:3.0.2]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[auth-client.exe:3.0.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[auth-client.exe:3.0.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[auth-client.exe:3.0.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[auth-client.exe:3.0.2]
        at com.hotpot.AuthApplication.main(AuthApplication.java:15) ~[auth-client.exe:na]
Caused by: java.lang.UnsatisfiedLinkError: jdk.jfr.internal.JVM.getHandler(Ljava/lang/Class;)Ljava/lang/Object; [symbol: Java_jdk_jfr_internal_JVM_getHandler or Java_jdk_jfr_internal_JVM_getHandler__Ljava_lang_Class_2]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:152) ~[na:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:53) ~[na:na]
        at jdk.jfr@17.0.5/jdk.jfr.internal.JVM.getHandler(JVM.java) ~[na:na]
        at jdk.jfr@17.0.5/jdk.jfr.internal.Utils.getHandler(Utils.java:448) ~[na:na]
        at jdk.jfr@17.0.5/jdk.jfr.internal.MetadataRepository.getHandler(MetadataRepository.java:174) ~[na:na]
        at jdk.jfr@17.0.5/jdk.jfr.internal.MetadataRepository.register(MetadataRepository.java:135) ~[na:na]
        at jdk.jfr@17.0.5/jdk.jfr.internal.MetadataRepository.register(MetadataRepository.java:130) ~[na:na]
        at jdk.jfr@17.0.5/jdk.jfr.FlightRecorder.register(FlightRecorder.java:136) ~[na:na]
        at io.lettuce.core.event.connection.JfrConnectionCreatedEvent.<clinit>(JfrConnectionCreatedEvent.java) ~[auth-client.exe:6.2.3.RELEASE]
        at java.base@17.0.5/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[auth-client.exe:na]
        at java.base@17.0.5/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[auth-client.exe:na]
        at io.lettuce.core.event.jfr.JfrEventRecorder.createEvent(JfrEventRecorder.java:108) ~[na:na]
        at io.lettuce.core.event.jfr.JfrEventRecorder.record(JfrEventRecorder.java:48) ~[na:na]
        at io.lettuce.core.AbstractRedisClient.initializeChannelAsync(AbstractRedisClient.java:398) ~[auth-client.exe:6.2.3.RELEASE]
        at io.lettuce.core.RedisClient.connectStatefulAsync(RedisClient.java:325) ~[auth-client.exe:6.2.3.RELEASE]
        at io.lettuce.core.RedisClient.connectStandaloneAsync(RedisClient.java:287) ~[auth-client.exe:6.2.3.RELEASE]
        at io.lettuce.core.RedisClient.connect(RedisClient.java:216) ~[auth-client.exe:6.2.3.RELEASE]
        at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.lambda$getConnection$1(StandaloneConnectionProvider.java:111) ~[na:na]
        at java.base@17.0.5/java.util.Optional.orElseGet(Optional.java:364) ~[auth-client.exe:na]
        at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.getConnection(StandaloneConnectionProvider.java:111) ~[na:na]
        at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.getConnection(LettuceConnectionFactory.java:1531) ~[na:na]
        at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection(LettuceConnectionFactory.java:1358) ~[auth-client.exe:3.0.1]
        at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getConnection(LettuceConnectionFactory.java:1341) ~[auth-client.exe:3.0.1]
        at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getSharedConnection(LettuceConnectionFactory.java:1059) ~[auth-client.exe:3.0.1]
        at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getConnection(LettuceConnectionFactory.java:398) ~[auth-client.exe:3.0.1]
        at org.springframework.session.data.redis.config.annotation.web.http.RedisIndexedHttpSessionConfiguration$EnableRedisKeyspaceNotificationsInitializer.afterPropertiesSet(RedisIndexedHttpSessionConfiguration.java:231) ~[auth-client.exe:3.0.0]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1797) ~[auth-client.exe:6.0.4]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1747) ~[auth-client.exe:6.0.4]
```
## Enviroment
 - GraalVM version : 22.3.0 (jdk-17)
 - OS: Win 10
 - Spring boot version: 3.0.2
 - lettuce version: 6.2.3.RELEASE
 - native maven plugin version: 0.9.19

## Build Args:
-H:+JNI
--enable-monitoring=jfr
--initialize-at-run-time=io.lettuce.core.event.connection.*

If more infomation needed, I'll provide.

thanks for the ideas

**Comment by peterhonneparker** [comment]
Thanks for your feedback. I'll close the issue now.
