### ISSUE TITLE
[native-image] ClassCastException re ObjectStamp vs IntegerStamp in canonicalizer phase after registering constructors for reflection use

### ISSUE THREAD

**Issue by AFaust** [oracle/graal#638]
I am currently trying to turn a small Java application based on Jetty and Graal.js into something that can be run successfully after compilation via native-image. In one step I added a Feature class to register Reflection usages for the analysis phase. While the native-image build ran fine after adding just classes, fields and methods of relevant classes, the build fails after adding the constructors of the same classes.

#### Steps to reproduce
1. Ensure [svm.jar is installed in the local Maven repository](https://github.com/AFaust/webhook-hub/tree/native-image#non-standard-dependency-svmjar)
2. Ensure Docker engine is running locally
3. Checkout the branch [native-image](https://github.com/AFaust/webhook-hub/tree/native-image) of my project
4. Build the project using ```mvn package```

#### Expectation
The build succeeds just as it has in the [commit before](https://github.com/AFaust/webhook-hub/tree/93c7de7215f62bb946e848dd95271bc0fd7d8620), where only classes, fields and methods had been registered.

#### Observation
Running native-image as part of the Docker image build fails. The following output is reported:
```
[INFO] DOCKER> Step 3/9 : RUN mkdir -p /var/lib/webhook-hub    && mv /tmp/webhook-hub-1.0.0-SNAPSHOT-shaded.jar /var/lib/webhook-hub/webhook-hub.jar    && cd /var/lib/webhook-hub    && /usr/lib/jvm/graalvm-ce-1.0.0-rc5/bin/native-image -jar ./webhook-hub.jar -H:Name=webhook-hub -H:+JNI -H:EnableURLProtocols=http
[INFO] DOCKER>
[INFO] DOCKER> ---> Running in 730d7b567b20
[INFO] DOCKER> Build on Server(pid: 13, port: 39811)*
[INFO] DOCKER> classlist
[INFO] DOCKER> :
[INFO] DOCKER> 3,528.48
[INFO] DOCKER> ms
[INFO] DOCKER> (cap)
[INFO] DOCKER> :
[INFO] DOCKER> 1,194.45
[INFO] DOCKER> ms
[INFO] DOCKER> setup
[INFO] DOCKER> :
[INFO] DOCKER> 2,608.94
[INFO] DOCKER> ms
[INFO] DOCKER> analysis
[INFO] DOCKER> :
[INFO] DOCKER> 46,422.11 ms
[INFO] DOCKER> [91merror: Error encountered while parsing com.oracle.svm.reflect.proxies.Proxy_88_UnwindExceptionToCallerStub_unwindExceptionToCaller.invoke(java.lang.Object, java.lang.Object[])
Parsing context:
        parsing java.lang.reflect.Method.invoke(Method.java:498)
        parsing ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:66)
        parsing ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:119)
        parsing ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:419)
        parsing ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
        parsing ch.qos.logback.classic.Logger.error(Logger.java:538)
        parsing org.orderofthebee.tools.webhook.hub.Runner.storeShutdownToken(Runner.java:206)
        parsing org.orderofthebee.tools.webhook.hub.Runner.runServer(Runner.java:144)
        parsing org.orderofthebee.tools.webhook.hub.Runner.main(Runner.java:124)
        parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:177)
        parsing com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Original error: org.graalvm.compiler.graph.GraalGraphError: java.lang.ClassCastException: org.graalvm.compiler.core.common.type.ObjectStamp cannot be cast to org.graalvm.compiler.core.common.type.IntegerStamp
        at node: 27|Pi
        at org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.tryCanonicalize(CanonicalizerPhase.java:340)
        at org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.processNode(CanonicalizerPhase.java:262)
        at org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.processWorkSet(CanonicalizerPhase.java:241)
        at org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.run(CanonicalizerPhase.java:211)
        at org.graalvm.compiler.phases.common.CanonicalizerPhase.run(CanonicalizerPhase.java:125)
        at org.graalvm.compiler.phases.common.CanonicalizerPhase.run(CanonicalizerPhase.java:66)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:206)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:315)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
        at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:186)
        at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:347)
        at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:389)
        at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:502)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassCastException: org.graalvm.compiler.core.common.type.ObjectStamp cannot be cast to org.graalvm.compiler.core.common.type.IntegerStamp
        at org.graalvm.compiler.core.common.type.IntegerStamp.join(IntegerStamp.java:350)
        at org.graalvm.compiler.core.common.type.IntegerStamp.join(IntegerStamp.java:60)
        at org.graalvm.compiler.nodes.PiNode.canonical(PiNode.java:211)
        at org.graalvm.compiler.nodes.PiNode.canonical(PiNode.java:224)
        at org.graalvm.compiler.phases.common.CanonicalizerPhase$Instance.tryCanonicalize(CanonicalizerPhase.java:335)
        ... 22 more
```

#### Remarks
It is unclear to me why the particular parsing context (a logging call in a shutdown operation) is reported when the addition of the constructors to the reflection registration should "only" affect [parts of the app reading configuration during startup](https://github.com/AFaust/webhook-hub/blob/native-image/src/main/java/org/orderofthebee/tools/webhook/hub/Runner.java#L175).

I had encountered the exact same kind of error relatively early in the development of that application, when none of the Graal.js use and Jackson-based configuration handling existed - but the problem disappeared for a while after adding additional features. I have reconstructed the simplified state of the app in the branch [simple-native-image-classcastexception](https://github.com/AFaust/webhook-hub/tree/simple-native-image-classcastexception) where it can be reproduced using the same steps listed above. Sometimes the error is also accompanied by the following NullPointerException, though I can not reliably reproduce that in a specific commit / branch:
```
[INFO] DOCKER> error: Error encountered while parsing org.graalvm.compiler.hotspot.nodes.AllocaNode.alloca(int)
Parsing context:
        parsing org.graalvm.compiler.hotspot.stubs.OutOfBoundsExceptionStub.createOutOfBoundsException(OutOfBoundsExceptionStub.java:81)
        parsing com.oracle.svm.reflect.proxies.Proxy_20_OutOfBoundsExceptionStub_createOutOfBoundsException.invoke(Unknown Source)
        parsing java.lang.reflect.Method.invoke(Method.java:498)
        parsing ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:66)
        parsing ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:119)
        parsing ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:419)
        parsing ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
        parsing ch.qos.logback.classic.Logger.error(Logger.java:538)
        parsing org.orderofthebee.tools.webhook.hub.Runner.loadShutdownToken(Runner.java:256)
        parsing org.orderofthebee.tools.webhook.hub.Runner.stopServer(Runner.java:212)
        parsing org.orderofthebee.tools.webhook.hub.Runner.main(Runner.java:125)
        parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:177)
        parsing com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Original error: java.lang.NullPointerException
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:296)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
        at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:346)
        at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:502)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by bishabosha** [comment]
I have received the same issue exactly on a different code base, triggered by the node 27|Pi
