### ISSUE TITLE
[native-image] The -report-unsupported-elements-at-runtime flag should support missing classes declared in annotations

### ISSUE THREAD

**Issue by graemerocher** [oracle/graal#641]
A class not on the classpath but present in an annotation results in

```
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
```

Apart from the fact that it is currently almost impossible to understand what class caused the issue this behaviour is not consistent with the `-report-unsupported-elements-at-runtime` flag.

The `-report-unsupported-elements-at-runtime` flag should cause this error to be ported at runtime.

Relates to #470

**Comment by cstancu** [comment]
This duplicates https://github.com/oracle/graal/issues/597.
