### ISSUE TITLE
jdk.net.ExtendedSocketOptions.TCP_KEEPIDLE not available in native-image application

### ISSUE THREAD

**Issue by beckermarc** [oracle/graal#6457]
I am facing issues using `jdk.net.ExtendedSocketOptions.TCP_KEEPIDLE` in native images. The following code runs fine on a JVM, but fails in a native image:

```java
AsynchronousSocketChannel socket = AsynchronousSocketChannel.open();
socket.setOption(jdk.net.ExtendedSocketOptions.TCP_KEEPIDLE, 100);
```

Error in native-image:

```
Exception in thread "main" java.lang.UnsupportedOperationException: 'TCP_KEEPIDLE' not supported
        at java.base@17.0.6/sun.nio.ch.AsynchronousSocketChannelImpl.setOption(AsynchronousSocketChannelImpl.java:461)
        at com.example.repro.Application.main(Application.java:15)
```

The class `jdk.net.ExtendedSocketOptions` registers some platform-dependent optionally available socket options. All of this is orchestrated by `sun.net.ext.ExtendedSocketOptions`, which [dynamically loads](https://github.com/openjdk/jdk17u-dev/blob/9d6f1d716ef13987cf4b36b6072b33d1c1aa5522/src/java.base/share/classes/sun/net/ext/ExtendedSocketOptions.java#L170-L191) `jdk.net.ExtendedSocketOptions` if available. `jdk.net.ExtendedSocketOptions` then performs initialization of these additional options [in a static code block](https://github.com/openjdk/jdk17u-dev/blob/9d6f1d716ef13987cf4b36b6072b33d1c1aa5522/src/jdk.net/share/classes/jdk/net/ExtendedSocketOptions.java#L213-L235).

For some reason, this static code block is not properly executed in the native-image. I know about build-time initialization of classes in native-images, but do not fully understand if this has an impact here.

To enable dynamic lookup of `jdk.net.ExtendedSocketOptions` I also put the following information into a `reflect-config.json`:

```json
[
    {
        "name": "jdk.net.ExtendedSocketOptions"
    }
]
```

Below I have provided a simple application to reproduce the issue. There I have provided additional debug output, which checks the conditions that check some boundary conditions for the exception to occur:

```java
AsynchronousSocketChannel socket = AsynchronousSocketChannel.open();
Set<SocketOption<?>> options = socket.supportedOptions();
System.out.println("Has TCP_KEEPIDLE? " + options.contains(jdk.net.ExtendedSocketOptions.TCP_KEEPIDLE));
System.out.println("Options: " + options);
```

Interestingly this produces the following output in a native-image:

```
Has TCP_KEEPIDLE? false
Options: [TCP_NODELAY, TCP_KEEPCOUNT, TCP_KEEPINTERVAL, SO_REUSEADDR, SO_SNDBUF, SO_RCVBUF, TCP_KEEPIDLE, SO_INCOMING_NAPI_ID, TCP_QUICKACK, SO_KEEPALIVE, SO_REUSEPORT]
```

Notice that the `contains` check evaluates to false, however the stringified options **DO INCLUDE** `TCP_KEEPIDLE`. Maybe this helps in finding the issue. My guess is this has something to do with build-time class initialization and code optimization, but I don't fully understand this behaviour.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Unpack the application: [tcp-keepidle-repro.zip](https://github.com/oracle/graal/files/11285982/tcp-keepidle-repro.zip)
2. `mvn native:compile`
3. `java -jar target/tcp-keepaliveidle-0.0.1-SNAPSHOT.jar` -> works
4. `target/tcp-keepaliveidle` -> fails

**Describe GraalVM and your environment:**
 - GraalVM version: `OpenJDK 64-Bit Server VM GraalVM CE 17.0.7-dev+4.1 (build 17.0.7+4-jvmci-23.0-b10, mixed mode, sharing)`
 - JDK major version:  `17`
 - OS: Ubuntu 22.04
 - Architecture: AMD64

**Comment by beckermarc** [comment]
I added some more output to my repro application, which better explains the current behaviour and points more to a bug:

```java
AsynchronousSocketChannel socket = AsynchronousSocketChannel.open();
Set<SocketOption<?>> options = socket.supportedOptions();

System.out.println("Has TCP_KEEPIDLE (obj)? " + options.contains(jdk.net.ExtendedSocketOptions.TCP_KEEPIDLE));
System.out.println("Has TCP_KEEPIDLE (string)? " + options.stream().anyMatch(s -> s.name().equals(jdk.net.ExtendedSocketOptions.TCP_KEEPIDLE.name())));
System.out.println("Options: " + options);

SocketOption<?> so = options.stream().filter(s -> s.name().equals(jdk.net.ExtendedSocketOptions.TCP_KEEPIDLE.name())).findFirst().get();
System.out.println("Constant identity: " + System.identityHashCode(jdk.net.ExtendedSocketOptions.TCP_KEEPIDLE));
System.out.println("Set identity: " + System.identityHashCode(so));
socket.setOption(jdk.net.ExtendedSocketOptions.TCP_KEEPIDLE, 100);
```

The code above produces the following output when run on the JVM:

```
Has TCP_KEEPIDLE (obj)? true
Has TCP_KEEPIDLE (string)? true
Options: [TCP_KEEPCOUNT, TCP_QUICKACK, SO_KEEPALIVE, SO_REUSEADDR, SO_INCOMING_NAPI_ID, TCP_KEEPIDLE, SO_SNDBUF, SO_RCVBUF, SO_REUSEPORT, TCP_NODELAY, TCP_KEEPINTERVAL]
Constant identity: 186276003
Set identity: 186276003
```

In a native-image it produces the following output:

```
Has TCP_KEEPIDLE (obj)? false
Has TCP_KEEPIDLE (string)? true
Options: [SO_KEEPALIVE, TCP_NODELAY, TCP_KEEPINTERVAL, SO_REUSEADDR, SO_REUSEPORT, TCP_QUICKACK, SO_RCVBUF, TCP_KEEPCOUNT, SO_SNDBUF, SO_INCOMING_NAPI_ID, TCP_KEEPIDLE]
Constant identity: 1710198919
Set identity: 95685867
Exception in thread "main" java.lang.UnsupportedOperationException: 'TCP_KEEPIDLE' not supported
        at java.base@17.0.6/sun.nio.ch.AsynchronousSocketChannelImpl.setOption(AsynchronousSocketChannelImpl.java:461)
        at com.example.repro.Application.main(Application.java:29)
```

As you can see there exist two object instances for `TCP_KEEPIDLE` in the native-image. However the JDK source code relies on object identity comparison and uses the `public static final SocketOption<Integer> TCP_KEEPINTERVAL` [declared object](https://github.com/openjdk/jdk17u-dev/blob/9d6f1d716ef13987cf4b36b6072b33d1c1aa5522/src/jdk.net/share/classes/jdk/net/ExtendedSocketOptions.java#L105) everywhere. Can you explain why there exist two different instances in the native-image?

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this, This is tracked internally on GR 45893

**Comment by fniephaus** [comment]
> Can you explain why there exist two different instances in the native-image?

Because one instance was created at build-time, and the other at run-time. More specifically, it is `sun.nio.ch.AsynchronousSocketChannelImpl$DefaultOptionsHolder` that is initialized at build-time and then incorrectly persisted as part of the executable. https://github.com/oracle/graal/commit/b6654d05ed84981936da7f736c04f0d683a1a4f3 makes sure its class initializer runs again at run-time, so that the set is reinitialized with the correct values. With my patch, I now get:

```
tcp-keepidle-repro$ ./target/tcp-keepaliveidle 
Is Linux? true
Has TCP_KEEPIDLE? true
Options: [TCP_QUICKACK, SO_RCVBUF, SO_KEEPALIVE, TCP_NODELAY, TCP_KEEPCOUNT, SO_SNDBUF, TCP_KEEPIDLE, SO_REUSEPORT, SO_INCOMING_NAPI_ID, TCP_KEEPINTERVAL, SO_REUSEADDR]
Constant identity: 164063280
Set identity: 164063280
```

If you want to try this out now, you need to build Native Image from source with my patch. Soon after #7440 is merged, the [latest dev build](https://github.com/graalvm/graalvm-ce-dev-builds/releases/latest) will ship the fix.

Hope this helps!

-- Fabio

**Comment by beckermarc** [comment]
Awesome! Thanks for looking into this :)
Can this reinitialization also be configured somehow in native-image.properties, as a workaround for now?

**Comment by fniephaus** [comment]
Yes, I believe you can use `--initialize-at-run-time=sun.nio.ch.AsynchronousSocketChannelImpl$DefaultOptionsHolder`. You can add the flag via your `pom.xml` file like so:
```xml
<buildArgs>
	<buildArg>--initialize-at-run-time=sun.nio.ch.AsynchronousSocketChannelImpl$DefaultOptionsHolder</buildArg>
</buildArgs>
```

**Comment by beckermarc** [comment]
Thanks, yes this works!
