### ISSUE TITLE
[LLVM] Problem with internal typecasting on 1st invocation

### ISSUE THREAD

**Issue by bademux** [oracle/graal#6515]
Hello
I discovered weird behavior:
when executing `void* allocX()`  its OK.
but if I put type: `X* allocX()`  - 1st invocation is failed on AssertionError and 2nd sequential invocation pass OK.
Is it something well known or it is better to report an issue with full test case

How to reproduce:

Cpp code below compiled with `clang++ -fPIC -xc++ -shared src/main/c/lib.c -o build/resources/main/lib.so`
```bash
clang++ --version
clang version 14.0.6 (GraalVM.org llvmorg-14.0.6-3-gc7a4a53c32-bgc5e298fd27 c7a4a53c32ccf93dd118fb6c13f2ecf02baeadf4)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/user/.sdkman/candidates/java/22.3.r19-grl/lib/llvm/bin
``` 
```c++
#include <graalvm/llvm/polyglot.h>
#include <vector>
#include <stdlib.h>

typedef struct X {
    std::vector<int> *items;
} X;

X *allocX() {
    X * x = (X *) malloc(sizeof(*x));
    x->items = new std::vector<int>();
    return x;
}
```
Java code prints exception stack trace (please find it below under spoiler) and "2nd" text

```java
import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.PolyglotException;
import org.graalvm.polyglot.Source;

import java.io.IOException;

import static java.lang.Boolean.TRUE;

public class Test {
    public static void main(String[] args) throws IOException {
        try(var context = Context.newBuilder().option("llvm.C++Interop", TRUE.toString()).allowAllAccess(true).build()) {
            var bc = context.eval(Source.newBuilder("llvm", Test.class.getResource("/lib.so")).build());
            try {
                bc.invokeMember("allocX"); //exception here
                System.out.println("1st");
            } catch (PolyglotException e) {
                e.printStackTrace();
            }
            bc.invokeMember("allocX"); //2nd invocation OK
            System.out.println("2nd");
        }
    }
}
```

<details>
  <summary>1st invocation Stacktrace</summary>
  
org.graalvm.polyglot.PolyglotException: java.lang.ClassCastException: class com.oracle.truffle.llvm.runtime.debug.type.LLVMSourceStructLikeType cannot be cast to class com.oracle.truffle.llvm.runtime.debug.type.LLVMSourceClassLikeType (com.oracle.truffle.llvm.runtime.debug.type.LLVMSourceStructLikeType and com.oracle.truffle.llvm.runtime.debug.type.LLVMSourceClassLikeType are in unnamed module of loader com.oracle.graalvm.locator.GraalVMLocator$GuestLangToolsLoader @47d384ee)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convertClass(LLVMInteropType.java:1000)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convertStructured(LLVMInteropType.java:943)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convert(LLVMInteropType.java:917)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.get(LLVMInteropType.java:905)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convertClass(LLVMInteropType.java:1009)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convertStructured(LLVMInteropType.java:943)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.getStructured(LLVMInteropType.java:935)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convertPointer(LLVMInteropType.java:1078)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convert(LLVMInteropType.java:913)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.get(LLVMInteropType.java:905)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convertStruct(LLVMInteropType.java:986)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convertStructuredStruct(LLVMInteropType.java:959)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convertStructured(LLVMInteropType.java:945)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.getStructured(LLVMInteropType.java:935)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convertPointer(LLVMInteropType.java:1078)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convert(LLVMInteropType.java:913)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.get(LLVMInteropType.java:905)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry$Register.get(LLVMInteropType.java:892)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$Function.<init>(LLVMInteropType.java:796)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convertFunction(LLVMInteropType.java:1021)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convertStructured(LLVMInteropType.java:947)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convert(LLVMInteropType.java:917)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.get(LLVMInteropType.java:905)
	at com.oracle.truffle.llvm.runtime.LLVMLanguage.getInteropType(LLVMLanguage.java:674)
	at com.oracle.truffle.llvm.runtime.LLVMFunctionCode.initForeignCallTarget(LLVMFunctionCode.java:460)
	at com.oracle.truffle.llvm.runtime.LLVMFunctionCode.getForeignCallTarget(LLVMFunctionCode.java:476)
	at com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptor$Execute.createCall(LLVMFunctionDescriptor.java:201)
	at com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptorGen$InteropLibraryExports$Cached.executeAndSpecialize(LLVMFunctionDescriptorGen.java:151)
	at com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptorGen$InteropLibraryExports$Cached.execute(LLVMFunctionDescriptorGen.java:121)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.execute(InteropLibraryGen.java:7765)
	at com.oracle.truffle.llvm.runtime.SulongLibrary.invokeMember(SulongLibrary.java:197)
	at com.oracle.truffle.llvm.runtime.SulongLibraryGen$InteropLibraryExports$Cached.invokeMemberNode_AndSpecialize(SulongLibraryGen.java:255)
	at com.oracle.truffle.llvm.runtime.SulongLibraryGen$InteropLibraryExports$Cached.invokeMember(SulongLibraryGen.java:240)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.invokeMember(InteropLibraryGen.java:8328)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$AbstractInvokeNode.executeShared(PolyglotValueDispatch.java:4446)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$InvokeNoArgsNode.executeImpl(PolyglotValueDispatch.java:4510)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:124)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:971)
	at Test.main(Test.java:14)
Original Internal Error: 
java.lang.ClassCastException: class com.oracle.truffle.llvm.runtime.debug.type.LLVMSourceStructLikeType cannot be cast to class com.oracle.truffle.llvm.runtime.debug.type.LLVMSourceClassLikeType (com.oracle.truffle.llvm.runtime.debug.type.LLVMSourceStructLikeType and com.oracle.truffle.llvm.runtime.debug.type.LLVMSourceClassLikeType are in unnamed module of loader com.oracle.graalvm.locator.GraalVMLocator$GuestLangToolsLoader @47d384ee)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convertClass(LLVMInteropType.java:1000)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convertStructured(LLVMInteropType.java:943)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convert(LLVMInteropType.java:917)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.get(LLVMInteropType.java:905)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convertClass(LLVMInteropType.java:1009)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convertStructured(LLVMInteropType.java:943)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.getStructured(LLVMInteropType.java:935)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convertPointer(LLVMInteropType.java:1078)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convert(LLVMInteropType.java:913)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.get(LLVMInteropType.java:905)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convertStruct(LLVMInteropType.java:986)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convertStructuredStruct(LLVMInteropType.java:959)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convertStructured(LLVMInteropType.java:945)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.getStructured(LLVMInteropType.java:935)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convertPointer(LLVMInteropType.java:1078)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convert(LLVMInteropType.java:913)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.get(LLVMInteropType.java:905)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry$Register.get(LLVMInteropType.java:892)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$Function.<init>(LLVMInteropType.java:796)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convertFunction(LLVMInteropType.java:1021)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convertStructured(LLVMInteropType.java:947)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.convert(LLVMInteropType.java:917)
	at com.oracle.truffle.llvm.runtime.interop.access.LLVMInteropType$InteropTypeRegistry.get(LLVMInteropType.java:905)
	at com.oracle.truffle.llvm.runtime.LLVMLanguage.getInteropType(LLVMLanguage.java:674)
	at com.oracle.truffle.llvm.runtime.LLVMFunctionCode.initForeignCallTarget(LLVMFunctionCode.java:460)
	at com.oracle.truffle.llvm.runtime.LLVMFunctionCode.getForeignCallTarget(LLVMFunctionCode.java:476)
	at com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptor$Execute.createCall(LLVMFunctionDescriptor.java:201)
	at com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptorGen$InteropLibraryExports$Cached.executeAndSpecialize(LLVMFunctionDescriptorGen.java:151)
	at com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptorGen$InteropLibraryExports$Cached.execute(LLVMFunctionDescriptorGen.java:121)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.execute(InteropLibraryGen.java:7765)
	at com.oracle.truffle.llvm.runtime.SulongLibrary.invokeMember(SulongLibrary.java:197)
	at com.oracle.truffle.llvm.runtime.SulongLibraryGen$InteropLibraryExports$Cached.invokeMemberNode_AndSpecialize(SulongLibraryGen.java:255)
	at com.oracle.truffle.llvm.runtime.SulongLibraryGen$InteropLibraryExports$Cached.invokeMember(SulongLibraryGen.java:240)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.invokeMember(InteropLibraryGen.java:8328)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$AbstractInvokeNode.executeShared(PolyglotValueDispatch.java:4446)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$InvokeNoArgsNode.executeImpl(PolyglotValueDispatch.java:4510)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:124)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:709)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:632)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:565)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:549)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalRuntimeSupport.callProfiled(GraalRuntimeSupport.java:256)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue.invoke(PolyglotValueDispatch.java:2426)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:971)
	at Test.main(Test.java:14)
Caused by: Attached Guest Language Frames (1)

</details>

**Comment by bademux** [comment]
I also don't understand why first invocation of `bc.invokeMember("allocX");` failing. 
It looks like `new std::vector<int>();` is failing when `allocX` has typed return instead of `void*`

**Comment by bademux** [comment]
Graal LLVM can't handle C++ std:vector.
We need to wrap the x with handler method `add`

```
void *allocX() {
    X * x = (X *) malloc(sizeof(*x));
    x->items = new std::vector<int>();
    return x;
}

void add(void* x, int v) {
    ((X *) x)->items->push_back(v);
    return x;
}

```
