### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Invalid logger interface org.hibernate.validator.internal.util.logging.Log (implementation not found in jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c)

### ISSUE THREAD

**Issue by bishalghosh-zs** [oracle/graal#6526]
Hi, 
I am having an issue mentioned below while running the application (building worked properly)
```
Caused by: java.lang.IllegalArgumentException: Invalid logger interface org.hibernate.validator.internal.util.logging.Log (implementation not found in jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c)
        at org.jboss.logging.Logger.doGetMessageLogger(Logger.java:2564)
        at org.jboss.logging.Logger.getMessageLogger(Logger.java:2530)
        at org.jboss.logging.Logger.getMessageLogger(Logger.java:2516)
        at org.hibernate.validator.internal.util.logging.LoggerFactory.make(LoggerFactory.java:22)
        at org.hibernate.validator.internal.util.Version.<clinit>(Version.java:20)
```
I am using an in-house framework (not a spring project). 

Did anyone find this issue or seen this issue before?

 GraalVM version
 - openjdk version "11.0.19" 2023-04-18
 - OpenJDK Runtime Environment GraalVM CE 22.3.2 (build 11.0.19+7-jvmci-22.3-b18)
 - OpenJDK 64-Bit Server VM GraalVM CE 22.3.2 (build 11.0.19+7-jvmci-22.3-b18, mixed mode, sharing)

**Comment by fernando-valdez** [comment]
Hi. Can you please share a reproducer that we can use to get that error?
