### ISSUE TITLE
Unable to create native-image of a jar, getting an error Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image runtime.

### ISSUE THREAD

**Issue by bishalghosh-zs** [oracle/graal#6527]
**Describe the issue**
Hi, 
While running the command `native-image -jar build/libs/Dummy-1.0-SNAPSHOT.jar --initialize-at-build-time=org.slf4j,ch.qos.logback --initialize-at-run-time=io.grpc.netty,io.netty` it generates a fallback image successfully and I can able to run the application flawlessly.

But, on running the command `native-image -jar build/libs/Dummy-1.0-SNAPSHOT.jar --initialize-at-build-time=org.slf4j,ch.qos.logback --initialize-at-run-time=io.grpc.netty,io.netty --no-fallback` it fails at step 2 and generates an error
```
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image runtime.
``` 

Below is the whole error stack trace attached. Please have a look.

```
Error: Unsupported features in 4 methods
Detailed message:
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.util.jar.JarFile. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field jdk.internal.module.ModuleReferences$JarModuleReader.jf of constant 
    jdk.internal.module.ModuleReferences$JarModuleReader@c4bec63: jdk.internal.module.ModuleReferences$JarModuleReader@c4bec63
  reading field java.util.concurrent.ConcurrentHashMap$Node.val of constant 
    java.util.concurrent.ConcurrentHashMap$Node@19972abe: [module org.graalvm.nativeimage.pointsto, location=file:///Library/Java/JavaVirt...
  indexing into array java.util.concurrent.ConcurrentHashMap$Node[]@7fbc5352: [Ljava.util.concurrent.ConcurrentHashMap$Node;@7fbc5352
  reading field java.util.concurrent.ConcurrentHashMap.table of constant 
    java.util.concurrent.ConcurrentHashMap@5f654b6b: {[module jdk.jstatd, location=jrt:/jdk.jstatd]=jdk.internal.module.SystemModuleF...
  reading field jdk.internal.loader.BuiltinClassLoader.moduleToReader of constant 
    jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c: jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c
  reading static field java.lang.ClassLoader.scl
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.util.jar.JarFile. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field jdk.internal.module.ModuleReferences$JarModuleReader.jf of constant 
    jdk.internal.module.ModuleReferences$JarModuleReader@11e88776: jdk.internal.module.ModuleReferences$JarModuleReader@11e88776
  reading field java.util.concurrent.ConcurrentHashMap$Node.val of constant 
    java.util.concurrent.ConcurrentHashMap$Node@7eb918ec: [module org.graalvm.nativeimage.base, location=file:///Library/Java/JavaVirtualM...
  indexing into array java.util.concurrent.ConcurrentHashMap$Node[]@7fbc5352: [Ljava.util.concurrent.ConcurrentHashMap$Node;@7fbc5352
  reading field java.util.concurrent.ConcurrentHashMap.table of constant 
    java.util.concurrent.ConcurrentHashMap@5f654b6b: {[module jdk.jstatd, location=jrt:/jdk.jstatd]=jdk.internal.module.SystemModuleF...
  reading field jdk.internal.loader.BuiltinClassLoader.moduleToReader of constant 
    jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c: jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c
  reading static field java.lang.ClassLoader.scl
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.util.jar.JarFile. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field jdk.internal.module.ModuleReferences$JarModuleReader.jf of constant 
    jdk.internal.module.ModuleReferences$JarModuleReader@18cf9f74: jdk.internal.module.ModuleReferences$JarModuleReader@18cf9f74
  reading field java.util.concurrent.ConcurrentHashMap$Node.val of constant 
    java.util.concurrent.ConcurrentHashMap$Node@530b294: [module org.graalvm.nativeimage.builder, location=file:///Library/Java/JavaVirtu...
  indexing into array java.util.concurrent.ConcurrentHashMap$Node[]@7fbc5352: [Ljava.util.concurrent.ConcurrentHashMap$Node;@7fbc5352
  reading field java.util.concurrent.ConcurrentHashMap.table of constant 
    java.util.concurrent.ConcurrentHashMap@5f654b6b: {[module jdk.jstatd, location=jrt:/jdk.jstatd]=jdk.internal.module.SystemModuleF...
  reading field jdk.internal.loader.BuiltinClassLoader.moduleToReader of constant 
    jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c: jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c
  reading static field java.lang.ClassLoader.scl
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.util.jar.JarFile. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field jdk.internal.module.ModuleReferences$JarModuleReader.jf of constant 
    jdk.internal.module.ModuleReferences$JarModuleReader@37cfd74b: jdk.internal.module.ModuleReferences$JarModuleReader@37cfd74b
  reading field java.util.concurrent.ConcurrentHashMap$Node.val of constant 
    java.util.concurrent.ConcurrentHashMap$Node@571bad33: [module org.graalvm.nativeimage.objectfile, location=file:///Library/Java/JavaVi...
  indexing into array java.util.concurrent.ConcurrentHashMap$Node[]@7fbc5352: [Ljava.util.concurrent.ConcurrentHashMap$Node;@7fbc5352
  reading field java.util.concurrent.ConcurrentHashMap.table of constant 
    java.util.concurrent.ConcurrentHashMap@5f654b6b: {[module jdk.jstatd, location=jrt:/jdk.jstatd]=jdk.internal.module.SystemModuleF...
  reading field jdk.internal.loader.BuiltinClassLoader.moduleToReader of constant 
    jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c: jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c
  reading static field java.lang.ClassLoader.scl

com.oracle.svm.core.util.UserError$UserException: Unsupported features in 4 methods
Detailed message:
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.util.jar.JarFile. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field jdk.internal.module.ModuleReferences$JarModuleReader.jf of constant 
    jdk.internal.module.ModuleReferences$JarModuleReader@c4bec63: jdk.internal.module.ModuleReferences$JarModuleReader@c4bec63
  reading field java.util.concurrent.ConcurrentHashMap$Node.val of constant 
    java.util.concurrent.ConcurrentHashMap$Node@19972abe: [module org.graalvm.nativeimage.pointsto, location=file:///Library/Java/JavaVirt...
  indexing into array java.util.concurrent.ConcurrentHashMap$Node[]@7fbc5352: [Ljava.util.concurrent.ConcurrentHashMap$Node;@7fbc5352
  reading field java.util.concurrent.ConcurrentHashMap.table of constant 
    java.util.concurrent.ConcurrentHashMap@5f654b6b: {[module jdk.jstatd, location=jrt:/jdk.jstatd]=jdk.internal.module.SystemModuleF...
  reading field jdk.internal.loader.BuiltinClassLoader.moduleToReader of constant 
    jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c: jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c
  reading static field java.lang.ClassLoader.scl
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.util.jar.JarFile. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field jdk.internal.module.ModuleReferences$JarModuleReader.jf of constant 
    jdk.internal.module.ModuleReferences$JarModuleReader@11e88776: jdk.internal.module.ModuleReferences$JarModuleReader@11e88776
  reading field java.util.concurrent.ConcurrentHashMap$Node.val of constant 
    java.util.concurrent.ConcurrentHashMap$Node@7eb918ec: [module org.graalvm.nativeimage.base, location=file:///Library/Java/JavaVirtualM...
  indexing into array java.util.concurrent.ConcurrentHashMap$Node[]@7fbc5352: [Ljava.util.concurrent.ConcurrentHashMap$Node;@7fbc5352
  reading field java.util.concurrent.ConcurrentHashMap.table of constant 
    java.util.concurrent.ConcurrentHashMap@5f654b6b: {[module jdk.jstatd, location=jrt:/jdk.jstatd]=jdk.internal.module.SystemModuleF...
  reading field jdk.internal.loader.BuiltinClassLoader.moduleToReader of constant 
    jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c: jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c
  reading static field java.lang.ClassLoader.scl
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.util.jar.JarFile. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field jdk.internal.module.ModuleReferences$JarModuleReader.jf of constant 
    jdk.internal.module.ModuleReferences$JarModuleReader@18cf9f74: jdk.internal.module.ModuleReferences$JarModuleReader@18cf9f74
  reading field java.util.concurrent.ConcurrentHashMap$Node.val of constant 
    java.util.concurrent.ConcurrentHashMap$Node@530b294: [module org.graalvm.nativeimage.builder, location=file:///Library/Java/JavaVirtu...
  indexing into array java.util.concurrent.ConcurrentHashMap$Node[]@7fbc5352: [Ljava.util.concurrent.ConcurrentHashMap$Node;@7fbc5352
  reading field java.util.concurrent.ConcurrentHashMap.table of constant 
    java.util.concurrent.ConcurrentHashMap@5f654b6b: {[module jdk.jstatd, location=jrt:/jdk.jstatd]=jdk.internal.module.SystemModuleF...
  reading field jdk.internal.loader.BuiltinClassLoader.moduleToReader of constant 
    jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c: jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c
  reading static field java.lang.ClassLoader.scl
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.util.jar.JarFile. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field jdk.internal.module.ModuleReferences$JarModuleReader.jf of constant 
    jdk.internal.module.ModuleReferences$JarModuleReader@37cfd74b: jdk.internal.module.ModuleReferences$JarModuleReader@37cfd74b
  reading field java.util.concurrent.ConcurrentHashMap$Node.val of constant 
    java.util.concurrent.ConcurrentHashMap$Node@571bad33: [module org.graalvm.nativeimage.objectfile, location=file:///Library/Java/JavaVi...
  indexing into array java.util.concurrent.ConcurrentHashMap$Node[]@7fbc5352: [Ljava.util.concurrent.ConcurrentHashMap$Node;@7fbc5352
  reading field java.util.concurrent.ConcurrentHashMap.table of constant 
    java.util.concurrent.ConcurrentHashMap@5f654b6b: {[module jdk.jstatd, location=jrt:/jdk.jstatd]=jdk.internal.module.SystemModuleF...
  reading field jdk.internal.loader.BuiltinClassLoader.moduleToReader of constant 
    jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c: jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c
  reading static field java.lang.ClassLoader.scl

        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:85)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:248)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:776)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported features in 4 methods
Detailed message:
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.util.jar.JarFile. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field jdk.internal.module.ModuleReferences$JarModuleReader.jf of constant 
    jdk.internal.module.ModuleReferences$JarModuleReader@c4bec63: jdk.internal.module.ModuleReferences$JarModuleReader@c4bec63
  reading field java.util.concurrent.ConcurrentHashMap$Node.val of constant 
    java.util.concurrent.ConcurrentHashMap$Node@19972abe: [module org.graalvm.nativeimage.pointsto, location=file:///Library/Java/JavaVirt...
  indexing into array java.util.concurrent.ConcurrentHashMap$Node[]@7fbc5352: [Ljava.util.concurrent.ConcurrentHashMap$Node;@7fbc5352
  reading field java.util.concurrent.ConcurrentHashMap.table of constant 
    java.util.concurrent.ConcurrentHashMap@5f654b6b: {[module jdk.jstatd, location=jrt:/jdk.jstatd]=jdk.internal.module.SystemModuleF...
  reading field jdk.internal.loader.BuiltinClassLoader.moduleToReader of constant 
    jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c: jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c
  reading static field java.lang.ClassLoader.scl
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.util.jar.JarFile. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field jdk.internal.module.ModuleReferences$JarModuleReader.jf of constant 
    jdk.internal.module.ModuleReferences$JarModuleReader@11e88776: jdk.internal.module.ModuleReferences$JarModuleReader@11e88776
  reading field java.util.concurrent.ConcurrentHashMap$Node.val of constant 
    java.util.concurrent.ConcurrentHashMap$Node@7eb918ec: [module org.graalvm.nativeimage.base, location=file:///Library/Java/JavaVirtualM...
  indexing into array java.util.concurrent.ConcurrentHashMap$Node[]@7fbc5352: [Ljava.util.concurrent.ConcurrentHashMap$Node;@7fbc5352
  reading field java.util.concurrent.ConcurrentHashMap.table of constant 
    java.util.concurrent.ConcurrentHashMap@5f654b6b: {[module jdk.jstatd, location=jrt:/jdk.jstatd]=jdk.internal.module.SystemModuleF...
  reading field jdk.internal.loader.BuiltinClassLoader.moduleToReader of constant 
    jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c: jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c
  reading static field java.lang.ClassLoader.scl
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.util.jar.JarFile. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field jdk.internal.module.ModuleReferences$JarModuleReader.jf of constant 
    jdk.internal.module.ModuleReferences$JarModuleReader@18cf9f74: jdk.internal.module.ModuleReferences$JarModuleReader@18cf9f74
  reading field java.util.concurrent.ConcurrentHashMap$Node.val of constant 
    java.util.concurrent.ConcurrentHashMap$Node@530b294: [module org.graalvm.nativeimage.builder, location=file:///Library/Java/JavaVirtu...
  indexing into array java.util.concurrent.ConcurrentHashMap$Node[]@7fbc5352: [Ljava.util.concurrent.ConcurrentHashMap$Node;@7fbc5352
  reading field java.util.concurrent.ConcurrentHashMap.table of constant 
    java.util.concurrent.ConcurrentHashMap@5f654b6b: {[module jdk.jstatd, location=jrt:/jdk.jstatd]=jdk.internal.module.SystemModuleF...
  reading field jdk.internal.loader.BuiltinClassLoader.moduleToReader of constant 
    jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c: jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c
  reading static field java.lang.ClassLoader.scl
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.util.jar.JarFile. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field jdk.internal.module.ModuleReferences$JarModuleReader.jf of constant 
    jdk.internal.module.ModuleReferences$JarModuleReader@37cfd74b: jdk.internal.module.ModuleReferences$JarModuleReader@37cfd74b
  reading field java.util.concurrent.ConcurrentHashMap$Node.val of constant 
    java.util.concurrent.ConcurrentHashMap$Node@571bad33: [module org.graalvm.nativeimage.objectfile, location=file:///Library/Java/JavaVi...
  indexing into array java.util.concurrent.ConcurrentHashMap$Node[]@7fbc5352: [Ljava.util.concurrent.ConcurrentHashMap$Node;@7fbc5352
  reading field java.util.concurrent.ConcurrentHashMap.table of constant 
    java.util.concurrent.ConcurrentHashMap@5f654b6b: {[module jdk.jstatd, location=jrt:/jdk.jstatd]=jdk.internal.module.SystemModuleF...
  reading field jdk.internal.loader.BuiltinClassLoader.moduleToReader of constant 
    jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c: jdk.internal.loader.ClassLoaders$AppClassLoader@5474c6c
  reading static field java.lang.ClassLoader.scl

        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:129)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:771)
        ... 5 more
------------------------------------------------------------------------------------------------------------------------
                        6.1s (11.0% of total time) in 26 GCs | Peak RSS: 5.99GB | CPU load: 6.90
========================================================================================================================
Failed generating 'Dummy-1.0-SNAPSHOT' after 55.0s.
Error: Image build request failed with exit status 1
```

**GraalVM version**

openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment GraalVM CE 22.3.2 (build 11.0.19+7-jvmci-22.3-b18)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.2 (build 11.0.19+7-jvmci-22.3-b18, mixed mode, sharing)

**Comment by fernando-valdez** [comment]
Hi. I will check this issue, but first, can you please provide a reproducer?

**Comment by fernando-valdez** [comment]
Closing due to the lack of response.
