### ISSUE TITLE
NPE in image generation

### ISSUE THREAD

**Issue by stuartwdouglas** [oracle/graal#654]
```
fatal error: org.graalvm.compiler.debug.GraalError: java.lang.NullPointerException
	at method: Object io.agroal.pool.ConnectionPool$ConnectionHandlerThreadLocal.initialValue()  [Virtual call from Object ThreadLocal.setInitialValue(), callTarget Object ThreadLocal.initialValue()]
	at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:956)
	at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:882)
	at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:257)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at org.graalvm.compiler.replacements.DefaultJavaLoweringProvider.insertAllocationBarrier(DefaultJavaLoweringProvider.java:933)
	at org.graalvm.compiler.replacements.DefaultJavaLoweringProvider.finishAllocatedObjects(DefaultJavaLoweringProvider.java:922)
	at org.graalvm.compiler.replacements.DefaultJavaLoweringProvider.lowerCommitAllocationNode(DefaultJavaLoweringProvider.java:850)
	at org.graalvm.compiler.replacements.DefaultJavaLoweringProvider.lower(DefaultJavaLoweringProvider.java:229)
	at com.oracle.svm.core.graal.meta.SubstrateBasicLoweringProvider.lower(SubstrateBasicLoweringProvider.java:143)
	at com.oracle.graal.enterprise.a.i.lower(stripped:139)
	at org.graalvm.compiler.nodes.virtual.CommitAllocationNode.lower(CommitAllocationNode.java:120)
	at org.graalvm.compiler.phases.common.LoweringPhase$Round.process(LoweringPhase.java:465)
	at org.graalvm.compiler.phases.common.LoweringPhase$Round.access$200(LoweringPhase.java:341)
	at org.graalvm.compiler.phases.common.LoweringPhase$Round$ProcessFrame.preprocess(LoweringPhase.java:405)
	at org.graalvm.compiler.phases.common.LoweringPhase.processBlock(LoweringPhase.java:564)
	at org.graalvm.compiler.phases.common.LoweringPhase$Round.run(LoweringPhase.java:390)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:212)
	at org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:56)
	at org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:38)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.phases.common.LoweringPhase.lower(LoweringPhase.java:261)
	at org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:254)
	at org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:93)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:212)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:256)
	at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:180)
	at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:165)
	at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:925)
```
I think the class that is causing problems is https://github.com/agroal/agroal/blob/master/agroal-pool/src/main/java/io/agroal/pool/ConnectionPool.java#L295

This is a problem on both RC5 and RC6

**Comment by cstancu** [comment]
@stuartwdouglas is this still a problem? Can you provide a reproducible example?

**Comment by stuartwdouglas** [comment]
Pretty sure this is no longer a problem.
