### ISSUE TITLE
NoClassDefFoundError: kotlin/reflect/KParameter

### ISSUE THREAD

**Issue by dsyer** [oracle/graal#656]
This is new with image generation for a minimal Spring Boot app in rc6:

```
fatal error: java.lang.NoClassDefFoundError: kotlin/reflect/KParameter
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at jdk.vm.ci.hotspot.HotSpotResolvedJavaMethodImpl.toJava(HotSpotResolvedJavaMethodImpl.java:611)
	at jdk.vm.ci.hotspot.HotSpotResolvedJavaMethodImpl.getAnnotation(HotSpotResolvedJavaMethodImpl.java:537)
	at com.oracle.svm.hosted.cenum.CEnumCallWrapperSubstitutionProcessor.lookup(CEnumCallWrapperSubstitutionProcessor.java:51)
...
```

Source code and README: https://github.com/dsyer/spring-boot-aot.

**Comment by dsyer** [comment]
I can't say I like that solution. It's a workaround right? I shouldn't have to put things on the classpath just to build a native image? It bloats the image and possibly even changes the behaviour of the app at runtime.

**Comment by dougxc** [comment]
@christianwimmer @cstancu this is a reasonable objection raised by @dsyer . I think all calls to `getAnnotation()` (and friends) in the native image building process should now take into account that `NoClassDefFoundError` can occur.

**Comment by cstancu** [comment]
This issue is fixed as of RC12. `NoClassDefFoundError`s that occur as result of `getAnnotation()` and other reflective calls are now swallowed by the native image builder and, where appropriate, the proper error is reported at run time when the `--allow-incomplete-classpath` option is used.
