### ISSUE TITLE
Cannot compile polyglot native image

### ISSUE THREAD

**Issue by agilob** [oracle/graal#667]
Previously I run the following commands to install ruby:
```
/home/agilob/Downloads/graalvm-ce-1.0.0-rc6/bin/gu -v install -c org.graalvm.ruby
/home/agilob/Downloads/graalvm-ce-1.0.0-rc6/jre/languages/ruby/lib/truffle/post_install_hook.sh
/home/agilob/Downloads/graalvm-ce-1.0.0-rc6/jre/lib/svm/bin/rebuild-images ruby
```
When I try to compile and run this code:

```
import org.graalvm.polyglot.*;

public class Main {

public static void main(String[] args) {
    System.out.println("Hello polyglot world Java!");
    Context context = Context.newBuilder().allowAllAccess(true).build();
    context.eval("js", "print('Hello polyglot world JavaScript!');");
    context.eval("ruby", "puts 'Hello polyglot world Ruby!'");
    }
}
```

I get this error and no file is produced:
```
graal /home/agilob/Downloads/graalvm-ce-1.0.0-rc6/bin/javac Main.java && /home/agilob/Downloads/graalvm-ce-1.0.0-rc6/bin/native-image --delay-class-initialization-to-runtime=Main Main
Build on Server(pid: 14232, port: 34803)
[main:14232]    classlist:     295.40 ms
[main:14232]        (cap):   1,026.10 ms
[main:14232]        setup:   1,493.49 ms
Warning: Detected unnecessary RecomputeFieldValue.ArrayBaseOffset com.oracle.svm.core.jdk.Target_java_nio_DirectByteBuffer.arrayBaseOffset substitution field for java.nio.DirectByteBuffer.arrayBaseOffset. The annotated field can be removed. This ArrayBaseOffset computation can be detected automatically. Use option -H:+UnsafeAutomaticSubstitutionsLogLevel=2 to print all automatically detected substitutions. 
[main:14232]     analysis:  44,170.71 ms
error: unsupported features in 7 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option --delay-class-initialization-to-runtime=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: 
        at parsing org.graalvm.compiler.hotspot.management.HotSpotGraalManagement.initialize(HotSpotGraalManagement.java:68)
Call path from entry point to org.graalvm.compiler.hotspot.management.HotSpotGraalManagement.initialize(HotSpotGraalRuntime): 
        at org.graalvm.compiler.hotspot.management.HotSpotGraalManagement.initialize(HotSpotGraalManagement.java:60)
        at org.graalvm.compiler.hotspot.HotSpotGraalRuntime.<init>(HotSpotGraalRuntime.java:163)
        at org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.createCompiler(HotSpotGraalCompilerFactory.java:145)
        at org.graalvm.compiler.truffle.runtime.hotspot.HotSpotTruffleRuntimeAccess$LazyGraalRuntime.getCompiler(HotSpotTruffleRuntimeAccess.java:104)
        at org.graalvm.compiler.truffle.runtime.hotspot.HotSpotTruffleRuntimeAccess$LazyGraalRuntime.get(HotSpotTruffleRuntimeAccess.java:88)
        at org.graalvm.compiler.truffle.runtime.hotspot.HotSpotTruffleRuntimeAccess$LazyGraalRuntime.get(HotSpotTruffleRuntimeAccess.java:79)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:130)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.setProperty(SystemPropertiesSupport.java:115)
        at com.oracle.svm.core.jdk.Target_java_lang_System.setProperty(JavaLangSubstitutions.java:359)
        at com.oracle.svm.core.properties.RuntimePropertyParser.parseProperty(RuntimePropertyParser.java:68)
        at com.oracle.svm.core.properties.RuntimePropertyParser.parse(RuntimePropertyParser.java:43)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:144)
        at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Invoke with MethodHandle argument could not be reduced to at most a single call: java.lang.invoke.MethodHandle.bindTo(Object)
Trace: 
        at parsing java.lang.invoke.MethodHandleImpl.makePairwiseConvertByEditor(MethodHandleImpl.java:221)
Call path from entry point to java.lang.invoke.MethodHandleImpl.makePairwiseConvertByEditor(MethodHandle, MethodType, boolean, boolean): 
        at java.lang.invoke.MethodHandleImpl.makePairwiseConvertByEditor(MethodHandleImpl.java:207)
        at java.lang.invoke.MethodHandleImpl.makePairwiseConvert(MethodHandleImpl.java:194)
        at java.lang.invoke.MethodHandleImpl.makePairwiseConvert(MethodHandleImpl.java:380)
        at java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:776)
        at java.lang.invoke.MethodHandle.asType(MethodHandle.java:761)
        at java.lang.invoke.MethodHandleImpl.makeVarargsCollector(MethodHandleImpl.java:443)
        at java.lang.invoke.MethodHandle.setVarargs(MethodHandle.java:1325)
        at java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:1670)
        at java.lang.invoke.MethodHandles$Lookup.getDirectMethod(MethodHandles.java:1605)
        at java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:781)
        at java.lang.invoke.BoundMethodHandle$Factory.makeCbmhCtor(BoundMethodHandle.java:818)
        at java.lang.invoke.BoundMethodHandle$Factory.makeCtors(BoundMethodHandle.java:763)
        at java.lang.invoke.BoundMethodHandle$SpeciesData.<init>(BoundMethodHandle.java:349)
        at java.lang.invoke.BoundMethodHandle$SpeciesData$1.apply(BoundMethodHandle.java:389)
        at java.lang.invoke.BoundMethodHandle$SpeciesData$1.apply(BoundMethodHandle.java:383)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at com.oracle.truffle.polyglot.PolyglotLanguageContext.lookupValueCache(PolyglotLanguageContext.java:572)
        at com.oracle.truffle.polyglot.PolyglotLanguageContext.asValue(PolyglotLanguageContext.java:565)
        at com.oracle.truffle.polyglot.PolyglotList.toString(PolyglotList.java:114)
        at java.lang.String.valueOf(String.java:2994)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at com.oracle.svm.core.amd64.AMD64CPUFeatureAccess.verifyHostSupportsArchitecture(AMD64CPUFeatureAccess.java:165)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:138)
        at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Invoke with MethodHandle argument could not be reduced to at most a single call: java.lang.invoke.MethodHandleImpl$BindCaller.prepareForInvoker(MethodHandle)
Trace: 
        at parsing java.lang.invoke.MethodHandleImpl$BindCaller.makeInjectedInvoker(MethodHandleImpl.java:1166)
Call path from entry point to java.lang.invoke.MethodHandleImpl$BindCaller.makeInjectedInvoker(Class): 
        at java.lang.invoke.MethodHandleImpl$BindCaller.makeInjectedInvoker(MethodHandleImpl.java:1141)
        at java.lang.invoke.MethodHandleImpl$BindCaller.access$300(MethodHandleImpl.java:1122)
        at java.lang.invoke.MethodHandleImpl$BindCaller$1.computeValue(MethodHandleImpl.java:1175)
        at java.lang.invoke.MethodHandleImpl$BindCaller$1.computeValue(MethodHandleImpl.java:1173)
        at com.oracle.svm.core.jdk.Target_java_lang_ClassValue.get(JavaLangSubstitutions.java:515)
        at org.graalvm.compiler.debug.DebugContext.convertFormatArg(DebugContext.java:1851)
        at org.graalvm.compiler.debug.DebugContext.formatDebugName(DebugContext.java:1857)
        at org.graalvm.compiler.debug.AbstractKey.createName(AbstractKey.java:102)
        at org.graalvm.compiler.debug.AbstractKey.getName(AbstractKey.java:96)
        at org.graalvm.compiler.debug.AbstractKey.toString(AbstractKey.java:107)
        at java.lang.String.valueOf(String.java:2994)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at com.oracle.svm.core.amd64.AMD64CPUFeatureAccess.verifyHostSupportsArchitecture(AMD64CPUFeatureAccess.java:165)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:138)
        at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Invoke with MethodHandle argument could not be reduced to at most a single call: java.lang.invoke.MethodHandleImpl.buildVarargsArray(MethodHandle, MethodHandle, int)
Trace: 
        at parsing java.lang.invoke.MethodHandleImpl.varargsArray(MethodHandleImpl.java:1634)
Call path from entry point to java.lang.invoke.MethodHandleImpl.varargsArray(Class, int): 
        at java.lang.invoke.MethodHandleImpl.varargsArray(MethodHandleImpl.java:1611)
        at java.lang.invoke.MethodHandleImpl$IntrinsicMethodHandle.asCollector(MethodHandleImpl.java:1363)
        at java.lang.invoke.MethodHandleImpl$AsVarargsCollector.<init>(MethodHandleImpl.java:460)
        at java.lang.invoke.MethodHandleImpl$AsVarargsCollector.<init>(MethodHandleImpl.java:454)
        at java.lang.invoke.MethodHandleImpl.makeVarargsCollector(MethodHandleImpl.java:445)
        at java.lang.invoke.MethodHandle.setVarargs(MethodHandle.java:1325)
        at java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:1670)
        at java.lang.invoke.MethodHandles$Lookup.getDirectMethod(MethodHandles.java:1605)
        at java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:781)
        at java.lang.invoke.BoundMethodHandle$Factory.makeCbmhCtor(BoundMethodHandle.java:818)
        at java.lang.invoke.BoundMethodHandle$Factory.makeCtors(BoundMethodHandle.java:763)
        at java.lang.invoke.BoundMethodHandle$SpeciesData.<init>(BoundMethodHandle.java:349)
        at java.lang.invoke.BoundMethodHandle$SpeciesData$1.apply(BoundMethodHandle.java:389)
        at java.lang.invoke.BoundMethodHandle$SpeciesData$1.apply(BoundMethodHandle.java:383)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at com.oracle.truffle.polyglot.PolyglotLanguageContext.lookupValueCache(PolyglotLanguageContext.java:572)
        at com.oracle.truffle.polyglot.PolyglotLanguageContext.asValue(PolyglotLanguageContext.java:565)
        at com.oracle.truffle.polyglot.PolyglotList.toString(PolyglotList.java:114)
        at java.lang.String.valueOf(String.java:2994)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at com.oracle.svm.core.amd64.AMD64CPUFeatureAccess.verifyHostSupportsArchitecture(AMD64CPUFeatureAccess.java:165)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:138)
        at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported method java.lang.Class.getDeclaredClasses0() is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Trace: 
        at parsing java.lang.Class.getDeclaredClasses(Class.java:1867)
Call path from entry point to java.lang.Class.getDeclaredClasses(): 
        at java.lang.Class.getDeclaredClasses(Class.java:1866)
        at java.lang.Class$2.run(Class.java:1504)
        at java.lang.Class$2.run(Class.java:1499)
        at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:70)
        at java.util.SplittableRandom.initialSeed(SplittableRandom.java:228)
        at com.oracle.svm.core.jdk.Target_java_util_SplittableRandom.<init>(JavaUtilSubstitutions.java:251)
        at com.oracle.svm.core.jdk.IdentityHashCodeSupport.generateHashCode(IdentityHashCodeSupport.java:43)
        at com.oracle.svm.core.jdk.Target_java_lang_System.identityHashCode(JavaLangSubstitutions.java:337)
        at jdk.internal.org.objectweb.asm.Label.toString(Label.java:587)
        at java.lang.String.valueOf(String.java:2994)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at com.oracle.svm.core.amd64.AMD64CPUFeatureAccess.verifyHostSupportsArchitecture(AMD64CPUFeatureAccess.java:165)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:138)
        at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Error: type is not available in this platform: org.graalvm.nativeimage.Feature
Trace:  object java.lang.Class[]
        object java.lang.invoke.MethodType
        object java.lang.invoke.MethodType$ConcurrentWeakInternSet$WeakEntry
        object java.util.concurrent.ConcurrentHashMap$Node
        object java.util.concurrent.ConcurrentHashMap$Node[]
        object java.util.concurrent.ConcurrentHashMap
        object java.lang.invoke.MethodType$ConcurrentWeakInternSet
        method java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean)
Call path from entry point to java.lang.invoke.MethodType.makeImpl(Class, Class[], boolean): 
        at java.lang.invoke.MethodType.makeImpl(MethodType.java:301)
        at java.lang.invoke.MethodType.methodType(MethodType.java:206)
        at java.lang.invoke.MemberName.getMethodType(MemberName.java:150)
        at java.lang.invoke.MemberName.getType(MemberName.java:221)
        at java.lang.invoke.MemberName.toString(MemberName.java:826)
        at java.lang.String.valueOf(String.java:2994)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at com.oracle.svm.core.amd64.AMD64CPUFeatureAccess.verifyHostSupportsArchitecture(AMD64CPUFeatureAccess.java:165)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:138)
        at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Error: type is not available in this platform: org.graalvm.nativeimage.impl.ImageSingletonsSupport

Error: Processing image build request failed
```

**Comment by ScalaWilliam** [comment]
I'm having the same problem, what does this mean?

**Comment by nhoughto** [comment]
adding `--language:..` fixed this issue for me.

**Comment by cstancu** [comment]
@nhoughto thanks for confirming!
