### ISSUE TITLE
Class missing when using graal packaging 

### ISSUE THREAD

**Issue by hergua** [oracle/graal#6679]
**Describe the issue**
I wrote a Java program whose function is to query the status of local services and upload the query results to Kafka. At the same time, applcation can also receive messages from Kafka to execute local script files and report the execution results. 
In order to make the program more flexible, I will pass the parameters through the command when starting the program. This means that the program does not stop, and parameters need to be read explicitly from startup.

I'm following the documentation to use graal to package it into a program that the OS can run directly. But when I enter the command `mvn -Pnative -Dagent exec:exec@java-agent`, an error occurs, the parameter is missing, and the program returns not 0.

Then I skip `mvn -Pnative -Dagent exec:exec@java-agent` and use `mvn -Pnative -Dagent package` directly
Package, package and use the command to run the program `./target/remote -agent 1581941120776581121 -ip 192.168.17.151 -operation operation -result operation_result -status agent_status -kafka 192.168.17.90:9092 -username admin -passwd admin-ZMSTqIx1S2zMWdLe`. another error occurs.  Class missing

What should I do to package the program correctly？

document url: https://www.graalvm.org/22.2/reference-manual/native-image/guides/use-native-image-maven-plugin/
here's my code: https://github.com/hergua/remote.git

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1.  git clone https://github.com/hergua/remote.git
2.  mvn clean package
3.  mvn -Pnative -Dagent exec:exec@java-agent

**Describe GraalVM and your environment:**
 - GraalVM version latest VM GraalVM CE 22.3.1
 - JDK major version:  OpenJDK 64-Bit Server VM GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13, mixed mode, sharing)
 - OS: macOS Ventura
 - Architecture:  AMD64

**More details**
$  mvn -Pnative -Dagent exec:exec@java-agent -Dexec.args="-agent 1581941120776581121 -ip 192.168.17.151 -operation operation -result operation_result -status agent_status -kafka 192.168.17.90:9092 -username admin -passwd admin-ZMSTqIx1S2zMWdLe"

[INFO] Scanning for projects...
[INFO] Found GraalVM installation from JAVA_HOME variable.
[INFO] 
[INFO] -------------------------< xin.opstime:remote >-------------------------
[INFO] Building remote 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:3.0.0:exec (java-agent) @ remote ---
Unrecognized option: -agent
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:982)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:929)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:457)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:301)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:211)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:165)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:157)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:121)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:127)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.711 s
[INFO] Finished at: 2023-05-25T18:33:00+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (java-agent) on project remote: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Another
$  ./target/remote -agent 1581941120776581121 -ip 192.168.17.151 -operation operation -result operation_result -status agent_status -kafka 192.168.17.90:9092 -username admin -passwd admin-ZMSTqIx1S2zMWdLe

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" org.apache.kafka.common.config.ConfigException: Invalid value org.apache.kafka.common.serialization.StringSerializer for configuration key.serializer: Class org.apache.kafka.common.serialization.StringSerializer could not be found.
        at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:744)
        at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:490)
        at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:483)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:129)
        at org.apache.kafka.clients.producer.ProducerConfig.<init>(ProducerConfig.java:536)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:291)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:318)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:303)
        at xin.opstime.remote.Remote.initKafkaProducer(Remote.java:169)
        at xin.opstime.remote.Remote.main(Remote.java:57)

**Comment by oubidar-Abderrahim** [comment]
Thank you for sharing this, I'll take a look into this.

**Comment by oubidar-Abderrahim** [comment]
Hi, If I understood correctly you're trying to run the application with two agents, the native image tracing agent and another agent used for Kafka, right?

Can you try running the jar without maven and providing both agents?

**Comment by oubidar-Abderrahim** [comment]
Any updates?

**Comment by oubidar-Abderrahim** [comment]
Closing for inactivity.
