### ISSUE TITLE
native-image - netty with TLS - any hope?

### ISSUE THREAD

**Issue by sundbp** [oracle/graal#668]
Hi,

After getting my basic gRPC example working I tried adding TLS into the mix by adding the dependency to: [io.netty/netty-tcnative-boringssl-static "2.0.7.Final"]

If I add that to the project native-image is no longer a happy camper.

Before looking further into this - given this involves native code etc, **is there any reason to expect native-image being able to tackle this situation?**

It fails with:
```
error: unsupported features in 2 methods
Detailed message:
Error: Detected a direct/mapped ByteBuffer in the image heap. A direct ByteBuffer has a pointer to unmanaged C memory, and C memory from the image generator is not available at image run time. A mapped ByteBuffer references a file descriptor, which is no longer open and mapped at run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option --delay-class-initialization-to-runtime=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace:  object io.netty.buffer.PoolChunk
        object io.netty.buffer.PoolThreadCache$MemoryRegionCache$Entry
        object java.lang.Object[]
        object java.util.concurrent.atomic.AtomicReferenceArray
        object io.netty.util.internal.shaded.org.jctools.queues.atomic.MpscAtomicArrayQueue
        object io.netty.buffer.PoolThreadCache$SubPageMemoryRegionCache
        object io.netty.buffer.PoolThreadCache$MemoryRegionCache[]
        object io.netty.buffer.PoolThreadCache
        object java.lang.Object[]
        object io.netty.util.internal.InternalThreadLocalMap
        object io.netty.util.concurrent.FastThreadLocal$1
        object io.netty.util.internal.ObjectCleaner$AutomaticCleanerReference
        object java.util.concurrent.ConcurrentHashMap$Node
        object java.util.concurrent.ConcurrentHashMap$Node[]
        object java.util.concurrent.ConcurrentHashMap
        object io.netty.util.internal.ConcurrentSet
        method io.netty.util.internal.ObjectCleaner.access$000()
Call path from entry point to io.netty.util.internal.ObjectCleaner.access$000(): 
        at io.netty.util.internal.ObjectCleaner.access$000(ObjectCleaner.java:34)
        at io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:51)
        at java.lang.Thread.run(Thread.java:748)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:238)
        at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_002epthreadStartRoutine_0028com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_0024ThreadStartData_0029(generated:0)
Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option --delay-class-initialization-to-runtime=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace:  object io.netty.util.internal.ObjectCleaner$AutomaticCleanerReference
        object java.util.concurrent.ConcurrentHashMap$Node
        object java.util.concurrent.ConcurrentHashMap$Node[]
        object java.util.concurrent.ConcurrentHashMap
        object io.netty.util.internal.ConcurrentSet
        method io.netty.util.internal.ObjectCleaner.access$000()
Call path from entry point to io.netty.util.internal.ObjectCleaner.access$000(): 
        at io.netty.util.internal.ObjectCleaner.access$000(ObjectCleaner.java:34)
        at io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:51)
        at java.lang.Thread.run(Thread.java:748)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:238)
        at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_002epthreadStartRoutine_0028com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_0024ThreadStartData_0029(generated:0)

Error: Image building with exit status 1
```

If I add a couple of delayed initializations via the new flag I get to this:
```
error: Detected a direct/mapped ByteBuffer in the image heap. A direct ByteBuffer has a pointer to unmanaged C memory, and C memory from the image generator is not available at image run time. A mapped ByteBuffer references a file descriptor, which is no longer open and mapped at run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option --delay-class-initialization-to-runtime=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Error: Detected a direct/mapped ByteBuffer in the image heap. A direct ByteBuffer has a pointer to unmanaged C memory, and C memory from the image generator is not available at image run time. A mapped ByteBuffer references a file descriptor, which is no longer open and mapped at run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option --delay-class-initialization-to-runtime=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace:  object io.netty.buffer.PoolChunk
        object io.netty.buffer.PoolChunkList
        object io.netty.buffer.PoolArena$DirectArena
        object io.netty.buffer.PoolArena[]
        object io.netty.buffer.PooledByteBufAllocator
        method io.netty.channel.DefaultChannelConfig.<init>(Channel, RecvByteBufAllocator)
Call path from entry point to io.netty.channel.DefaultChannelConfig.<init>(Channel, RecvByteBufAllocator): 
        at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:72)
        at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:69)
        at io.netty.bootstrap.FailedChannel.<init>(FailedChannel.java:30)
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:330)
        at io.netty.bootstrap.AbstractBootstrap.register(AbstractBootstrap.java:234)
        at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:222)
        at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:32)
        at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:230)
        at io.grpc.internal.InternalSubchannel.access$600(InternalSubchannel.java:57)
        at io.grpc.internal.InternalSubchannel$1EndOfCurrentBackoff.run(InternalSubchannel.java:255)
        at java.lang.Thread.run(Thread.java:748)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:238)
        at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_002epthreadStartRoutine_0028com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_0024ThreadStartData_0029(generated:0)

Error: Image building with exit status 1
```

If I try to delay that class it seems to have no impact, and I can't see any obvious substitution to make for that class.

(the repo is here https://gitlab.com/sundbp/native-image-grpc-test without the tls dependency added)

**Comment by cstancu** [comment]
@sundbp what is the complete list of delayed classes that you tried so far?

**Comment by sundbp** [comment]
`--delay-class-initialization-to-runtime=io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator,io.netty.handler.ssl.ReferenceCountedOpenSslEngine,io.netty.util.internal.ObjectCleaner,io.netty.handler.ssl.ReferenceCountedOpenSslContext,io.netty.channel.DefaultChannelConfig`

I checked it in as a branch here if you want to run it: https://gitlab.com/sundbp/native-image-grpc-test/tree/tls

**Comment by marcelomrwin** [comment]
Have you solve your problem?

**Comment by sundbp** [comment]
Afraid not. I gave up my last effort around the time of my last reply in this thread.

**Comment by hpehl** [comment]
I'm facing similar issues when building the native profile of my [gRPC quickstart](https://github.com/hpehl/quarkus-grpc-quickstart):

```
Error: Detected a direct/mapped ByteBuffer in the image heap. A direct ByteBuffer has a pointer to unmanaged C memory, and C memory from the image generator is not available at image run time. A mapped ByteBuffer references a file descriptor, which is no longer open and mapped at run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option --delay-class-initialization-to-runtime=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
```

I filed https://github.com/quarkusio/quarkus/issues/820 to track the overall progress for the gRPC extensions in Quarkus. Please let me know if you make any progress here.

**Comment by vongosling** [comment]
If not open OpenSSL in netty, The build parameter in  https://github.com/oracle/graal/issues/2028 will help you.
