### ISSUE TITLE
Confusing error when setting C-standard

### ISSUE THREAD

**Issue by sgammon** [oracle/graal#6699]
(My native-image build did not produce a `svm_err_b_*.md`, at least that I can find. If I am in the wrong place, please let me know and I can re-file.)

Building a native image with `C11` on `arm64` yields the following exception for me:

```
Error: C standard "C11" is not supported. Supported standards are: [C89, C99, C11]
```

The same build works fine on amd64 with the same flags. I can provide further context about the host machine, GVM version, etc., if needed.

<details>
<summary>Full stacktrace</summary>
<pre>
[1/7] Initializing...                                                                                    (0.0s @ 0.75GB)
Error: C standard "C11" is not supported. Supported standards are: [C89, C99, C11]
com.oracle.svm.core.util.UserError$UserException: C standard "C11" is not supported. Supported standards are: [C89, C99, C11]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageOptions.getCStandard(NativeImageOptions.java:148)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.codegen.CSourceCodeWriter.writeCStandardHeaders(CSourceCodeWriter.java:85)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.codegen.QueryCodeWriter.visitNativeCodeInfo(QueryCodeWriter.java:123)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.info.NativeCodeInfo.accept(NativeCodeInfo.java:57)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.codegen.QueryCodeWriter.write(QueryCodeWriter.java:91)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.CAnnotationProcessor.process(CAnnotationProcessor.java:101)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.NativeLibraries.finish(NativeLibraries.java:554)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1714)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1121)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:915)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:575)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
</pre>
</details>

**Comment by sgammon** [comment]
okay, after a bit more investigation, I should update the title and content of this bug. I tried `C99` and it also failed, but then I noticed that I was wrapping the C standard flag in quotes:

from a gradle build in kotlin DSL syntax:
```kotlin
val nativeImageCStandard = "C11"

// ...

val commonNativeArgs: List<String> = listOf(
  "-H:CStandard=\"$nativeImageCStandard\"",
  // ... other args
)
```

after removing the quotes:
```kotlin
"-H:CStandard=$nativeImageCStandard",
```

the build works fine. not entirely sure why this surfaced on our `arm64` box versus our `amd64` box, where the build works fine with the quotes. but perhaps it has to do with our arm box using pure bash instead of zsh.

in any case, it may help with this to [strip single/double quotes before looking up the C-standard version](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageOptions.java#L177-L183). i will submit a PR shortly to remedy this.

**Comment by fniephaus** [comment]
Hi @sgammon,
Thanks for raising this.

> (My native-image build did not produce a svm_err_b_*.md, at least that I can find. If I am in the wrong place, please let me know and I can re-file.)

This is a new feature of the upcoming releases on June 13. If you want to test it today, you can use a [dev build](https://github.com/graalvm/graalvm-ce-dev-builds/releases), but it's quite obvious what's going on here.

> Building a native image with C11 on arm64 yields the following exception for me:
> `Error: C standard "C11" is not supported. Supported standards are: [C89, C99, C11]`
> The same build works fine on amd64 with the same flags

That's indeed unexpected. I think it'd be good if we investigate why this happens. The fix you're proposing works, but only for one option. The weird behavior may still happen with other options.
For a start, I think we may want to improve the error message and quote the value. This would result in the quoting error becoming more obvious (`Error: C standard '"C11"' is not supported...`).
In addition, let me look into our option parser and see whether we can and should trip quotes from all option values. They are needed when the argument contains a space (I don't have an example for that at hand). But it seems this is something Native Image should be able to handle for the user.

**Comment by sgammon** [comment]
@fniephaus sounds good 😁

**Comment by fniephaus** [comment]
>but perhaps it has to do with our arm box using pure bash instead of zsh.

I think you may be right. The shell is supposed to handle quotes, so within Native Image, there's not much should do apart from making it more obvious what values have reached the build process. I'm going to improve the error message as previously suggested.
