### ISSUE TITLE
Graal Updater incorrectly resolves graal home

### ISSUE THREAD

**Issue by Berstanio** [oracle/graal#6708]
**Describe the issue**
In some cases (some fresh graal installations work, some not. Haven't found a pattern yet) gu doesn't run, because it evaluates `/path/to/graal/Contents` as the graal home, instead of  `/path/to/graal/Contents/Home`. This leads to a failure of gu.
This cannot be fixed by setting `GRAALVM_HOME_DEV`, the result is the same.
Only workaround I found so far is creating `/path/to/graal/Contents/Home/bin/tmp/`, copying gu into the folder, and run it from there. Then it picks up the home folder correctly.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Download https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.1/graalvm-ce-java17-darwin-aarch64-22.3.1.tar.gz
2. Extract + potential remove quarantine
3. Run /path/to/graal/Contents/Home/bin/gu

**Describe GraalVM and your environment:**
 - GraalVM version GraalVM CE 22.3.1
 - JDK major version: 17
 - OS: Ventura
 - Architecture: aarch64

**More details**
```
% gu install native-image -e                                                                                     
Error: The GraalVM directory [...]/graalvm-ce-java17-22.3.1/Contents is invalid.
org.graalvm.component.installer.FailedOperationException: The GraalVM directory [...]/graalvm-ce-java17-22.3.1/Contents is invalid.
	at org.graalvm.component.installer.Environment.failure(Environment.java:213)
	at org.graalvm.component.installer.ComponentInstaller.findGraalHome(ComponentInstaller.java:551)
	at org.graalvm.component.installer.ComponentInstaller.completeEnvironment(ComponentInstaller.java:273)
	at org.graalvm.component.installer.ComponentInstaller.interpretOptions(ComponentInstaller.java:315)
	at org.graalvm.component.installer.ComponentInstaller.processOptions(ComponentInstaller.java:347)
	at org.graalvm.component.installer.ComponentInstaller.processCommand(ComponentInstaller.java:453)
	at org.graalvm.component.installer.ComponentInstaller.run(ComponentInstaller.java:580)
	at org.graalvm.component.installer.ComponentInstaller.main(ComponentInstaller.java:633)

```

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, I have a question, do you set JAVA_HOME to `/path/to/graal/Contents/Home/` and add `$JAVA_HOME/bin` to the `PATH`?

**Comment by Berstanio** [comment]
Yes, I do both!

**Comment by oubidar-Abderrahim** [comment]
Unfortunately, we couldn't reproduce this issue, if you can have a more reliable way to reproduce this, please reopen this issue and we'll take another look into it.
