### ISSUE TITLE
[Sulong] UnsupportedSpecializationException when running SPEC CPU2006's 445.gobmk

### ISSUE THREAD

**Issue by pekd** [oracle/graal#676]
445.gobmk was compiled with clang v6.0.1 with the compiler flag `-O1`. Execution fails with the following stack trace:
```
ERROR: com.oracle.truffle.api.dsl.UnsupportedSpecializationException: Unexpected values provided for LLVMSubNodeGen@6b888692: [0x7f84f0319210, 140208942190336], [LLVMPointerImpl,Long]
org.graalvm.polyglot.PolyglotException: com.oracle.truffle.api.dsl.UnsupportedSpecializationException: Unexpected values provided for LLVMSubNodeGen@6b888692: [0x7f84f0319210, 140208942190336], [LLVMPointerImpl,Long]
        at com.oracle.truffle.llvm.nodes.op.LLVMArithmeticNodeFactory$LLVMSubNodeGen.executeAndSpecialize(LLVMArithmeticNodeFactory.java:1763)
        at com.oracle.truffle.llvm.nodes.op.LLVMArithmeticNodeFactory$LLVMSubNodeGen.executeGeneric_generic7(LLVMArithmeticNodeFactory.java:1501)
        at com.oracle.truffle.llvm.nodes.op.LLVMArithmeticNodeFactory$LLVMSubNodeGen.executeGeneric(LLVMArithmeticNodeFactory.java:1304)
        at com.oracle.truffle.llvm.nodes.vars.LLVMWriteNodeFactory$LLVMWriteI64NodeGen.execute_generic1(LLVMWriteNodeFactory.java:485)
        at com.oracle.truffle.llvm.nodes.vars.LLVMWriteNodeFactory$LLVMWriteI64NodeGen.execute(LLVMWriteNodeFactory.java:466)
        at com.oracle.truffle.llvm.nodes.base.LLVMBasicBlockNode.execute(LLVMBasicBlockNode.java:92)
        at com.oracle.truffle.llvm.nodes.control.LLVMDispatchBasicBlockNode.executeGeneric(LLVMDispatchBasicBlockNode.java:102)
        at com.oracle.truffle.llvm.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:77)
        at <llvm> @undo_trymove(Unknown)
        at <llvm> @popgo(gobmk.bc:@popgo:1:0-14)
        at <llvm> @attack2(gobmk.bc:@attack2:1:0-16)
        at <llvm> @do_attack(gobmk.bc:@do_attack:1:0-18)
        at <llvm> @defend2(gobmk.bc:@defend2:1:0-16)
        at <llvm> @do_find_defense(gobmk.bc:@do_find_defense:1:0-24)
        at <llvm> @find_defense(gobmk.bc:@find_defense:1:0-21)
        at <llvm> @gtp_defend(gobmk.bc:@gtp_defend:1:0-19)
        at <llvm> @gtp_main_loop(gobmk.bc:@gtp_main_loop:1:0-22)
        at <llvm> @play_gtp(gobmk.bc:@play_gtp:1:0-17)
        at <llvm> @specmain(gobmk.bc:@specmain:1:0-17)
        at <llvm> @main(gobmk.bc:@main:1:0-13)
        at <llvm> @_start(libsulong.bc:@_start:1:0-19)
        at org.graalvm.polyglot.Value.execute(Value.java:310)
        at com.oracle.truffle.llvm.launcher.LLVMLauncher.execute(LLVMLauncher.java:214)
        at com.oracle.truffle.llvm.launcher.LLVMLauncher.launch(LLVMLauncher.java:63)
        at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:106)
        at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:54)
        at com.oracle.truffle.llvm.launcher.LLVMLauncher.main(LLVMLauncher.java:53)
Original Internal Error:
com.oracle.truffle.api.dsl.UnsupportedSpecializationException: Unexpected values provided for LLVMSubNodeGen@6b888692: [0x7f84f0319210, 140208942190336], [LLVMPointerImpl,Long]
        at com.oracle.truffle.llvm.nodes.op.LLVMArithmeticNodeFactory$LLVMSubNodeGen.executeAndSpecialize(LLVMArithmeticNodeFactory.java:1763)
        at com.oracle.truffle.llvm.nodes.op.LLVMArithmeticNodeFactory$LLVMSubNodeGen.executeGeneric_generic7(LLVMArithmeticNodeFactory.java:1501)
        at com.oracle.truffle.llvm.nodes.op.LLVMArithmeticNodeFactory$LLVMSubNodeGen.executeGeneric(LLVMArithmeticNodeFactory.java:1304)
        at com.oracle.truffle.llvm.nodes.vars.LLVMWriteNodeFactory$LLVMWriteI64NodeGen.execute_generic1(LLVMWriteNodeFactory.java:485)
        at com.oracle.truffle.llvm.nodes.vars.LLVMWriteNodeFactory$LLVMWriteI64NodeGen.execute(LLVMWriteNodeFactory.java:466)
        at com.oracle.truffle.llvm.nodes.base.LLVMBasicBlockNode.execute(LLVMBasicBlockNode.java:92)
        at com.oracle.truffle.llvm.nodes.control.LLVMDispatchBasicBlockNode.executeGeneric(LLVMDispatchBasicBlockNode.java:102)
        at com.oracle.truffle.llvm.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:77)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:269)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:258)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:248)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:230)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:213)
        at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:88)
        at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:72)
        at com.oracle.truffle.llvm.nodes.func.LLVMDispatchNode.doDirect(LLVMDispatchNode.java:91)
        at com.oracle.truffle.llvm.nodes.func.LLVMDispatchNodeGen.executeAndSpecialize(LLVMDispatchNodeGen.java:132)
        at com.oracle.truffle.llvm.nodes.func.LLVMDispatchNodeGen.executeDispatch(LLVMDispatchNodeGen.java:93)
        at com.oracle.truffle.llvm.nodes.func.LLVMLookupDispatchNode.doDirectCached(LLVMLookupDispatchNode.java:78)
        at com.oracle.truffle.llvm.nodes.func.LLVMLookupDispatchNodeGen.executeAndSpecialize(LLVMLookupDispatchNodeGen.java:152)
        at com.oracle.truffle.llvm.nodes.func.LLVMLookupDispatchNodeGen.executeDispatch(LLVMLookupDispatchNodeGen.java:110)
        at com.oracle.truffle.llvm.nodes.func.LLVMCallNode.executeGeneric(LLVMCallNode.java:75)
        at com.oracle.truffle.llvm.runtime.nodes.api.LLVMVoidStatementNodeGen.execute(LLVMVoidStatementNodeGen.java:24)
        at com.oracle.truffle.llvm.nodes.base.LLVMBasicBlockNode.execute(LLVMBasicBlockNode.java:92)
        at com.oracle.truffle.llvm.nodes.control.LLVMDispatchBasicBlockNode.executeGeneric(LLVMDispatchBasicBlockNode.java:102)
        at com.oracle.truffle.llvm.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:77)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:269)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:258)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:248)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:230)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:213)
        at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:88)
        at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:72)
        at com.oracle.truffle.llvm.nodes.func.LLVMDispatchNode.doDirect(LLVMDispatchNode.java:91)
        at com.oracle.truffle.llvm.nodes.func.LLVMDispatchNodeGen.executeAndSpecialize(LLVMDispatchNodeGen.java:132)
        at com.oracle.truffle.llvm.nodes.func.LLVMDispatchNodeGen.executeDispatch(LLVMDispatchNodeGen.java:93)
        at com.oracle.truffle.llvm.nodes.func.LLVMLookupDispatchNode.doDirectCached(LLVMLookupDispatchNode.java:78)
        at com.oracle.truffle.llvm.nodes.func.LLVMLookupDispatchNodeGen.executeAndSpecialize(LLVMLookupDispatchNodeGen.java:152)
        at com.oracle.truffle.llvm.nodes.func.LLVMLookupDispatchNodeGen.executeDispatch(LLVMLookupDispatchNodeGen.java:110)
        at com.oracle.truffle.llvm.nodes.func.LLVMCallNode.executeGeneric(LLVMCallNode.java:75)
        at com.oracle.truffle.llvm.runtime.nodes.api.LLVMVoidStatementNodeGen.execute(LLVMVoidStatementNodeGen.java:24)
        at com.oracle.truffle.llvm.nodes.base.LLVMBasicBlockNode.execute(LLVMBasicBlockNode.java:92)
        at com.oracle.truffle.llvm.nodes.control.LLVMDispatchBasicBlockNode.executeGeneric(LLVMDispatchBasicBlockNode.java:102)
        at com.oracle.truffle.llvm.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:77)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:269)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:258)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:248)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:230)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:213)
[…]
```

Sulong and graal are built from git/master (76d043560571c3f6c4c0d76f89cb876451062251).

This already worked in the past.

**Comment by spavlusieva** [comment]
hi @pekd , this issue has been inactive for more than 180 days. We’ll close it to focus on current issues. In case it’s still relevant, please reopen it and we’ll take another look. Thank you!
