### ISSUE TITLE
Self static method cannot reflection?

### ISSUE THREAD

**Issue by GrapeBaBa** [oracle/graal#6768]
We depend a third party lib https://github.com/gestalt-config/gestalt/issues/96, it use a reflection call static method actual is itself, doesn't it allow?

Code:
https://github.com/gestalt-config/gestalt/blob/main/gestalt-core/src/main/java/org/github/gestalt/config/utils/RecordUtils.java#L50-L53

Error:
`
 Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Runtime reflection is not supported for public boolean java.lang.Class.isRecord()
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89)
        at java.base@19.0.2/java.lang.reflect.Method.acquireMethodAccessor(Method.java:76)
        at java.base@19.0.2/java.lang.reflect.Method.invoke(Method.java:575)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.Util_java_lang_invoke_MethodHandle.invokeInternal(Target_java_lang_invoke_MethodHandle.java:221)
        at java.base@19.0.2/java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:76)
        at java.base@19.0.2/java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:0)
        at java.base@19.0.2/java.lang.invoke.LambdaForm$MH/0x00000007c1c9ac00.invokeExact_MT(LambdaForm$MH)
        at org.github.gestalt.config.utils.RecordUtils.isRecord(RecordUtils.java:97)
        ... 29 more
`

**Comment by GrapeBaBa** [comment]
fixed, when adding reflect-config.json
