### ISSUE TITLE
[native-image] Unable to invoke no-args constructor exceptions

### ISSUE THREAD

**Issue by ChadKillingsworth** [oracle/graal#680]
When building closure-compiler with the RC6 release, the following exception is thrown. This error is not encountered when built with the native-image tool from 9b7872c.

```
java.lang.RuntimeException: Unable to invoke no-args constructor for class com.google.javascript.jscomp.AbstractCommandLineRunner$JsonFileSpec. Register an InstanceCreator with Gson for this type may fix this problem.
	at java.lang.Throwable.<init>(Throwable.java:287)
	at java.lang.Exception.<init>(Exception.java:84)
	at java.lang.RuntimeException.<init>(RuntimeException.java:80)
	at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:226)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.javascript.jscomp.AbstractCommandLineRunner.parseJsonFilesFromInputStream(AbstractCommandLineRunner.java:575)
	at com.google.javascript.jscomp.AbstractCommandLineRunner.doRun(AbstractCommandLineRunner.java:1127)
	at com.google.javascript.jscomp.AbstractCommandLineRunner.run(AbstractCommandLineRunner.java:540)
	at com.google.javascript.jscomp.CommandLineRunner.main(CommandLineRunner.java:2166)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:163)
Caused by: java.lang.UnsupportedOperationException: Cannot allocate class com.google.javascript.jscomp.AbstractCommandLineRunner$JsonFileSpec
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Exception.<init>(Exception.java:66)
	at java.lang.RuntimeException.<init>(RuntimeException.java:62)
	at java.lang.UnsupportedOperationException.<init>(UnsupportedOperationException.java:52)
	at com.google.gson.internal.UnsafeAllocator$4.newInstance(UnsafeAllocator.java:104)
	at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:223)
	... 7 more
```

Command to repo the error:

```
echo "[{\"src\": \"console.log('hello world');\", \"path\": \"foo.js\"}]" | compiler --json_streams=IN
```

**Comment by cstancu** [comment]
@ChadKillingsworth I think that you are missing some reflection configuration. GSON uses reflection to allocated bean instances. Did you try registering the "no-args constructor for class `com.google.javascript.jscomp.AbstractCommandLineRunner$JsonFileSpec`" for reflection?

**Comment by ChadKillingsworth** [comment]
I can definitely try that. Any idea why it works with an old commit?

**Comment by ChadKillingsworth** [comment]
I looked at the reflection config. Currently we have: 

```json
{
    "name" : "com.google.javascript.jscomp.AbstractCommandLineRunner$JsonFileSpec",
    "allDeclaredConstructors" : true,
    "allDeclaredMethods": true,
    "allDeclaredFields": true
}
```

However, there is not a no-args constructor in the source code for this class. Does one need added?

**Comment by ChadKillingsworth** [comment]
Here's a link to the class definition: https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/AbstractCommandLineRunner.java#L2762

**Comment by ChadKillingsworth** [comment]
It looks like adding:

```java
private JsonFileSpec() {
  this(null, null, null, null);
}
```

Is all it takes to work around this.
