### ISSUE TITLE
Unable to handle classpath element on Windows

### ISSUE THREAD

**Issue by sormuras** [oracle/graal#6812]
**Describe the issue**
Native image is unable to handle classpath element on Windows, when run in users home directory. Running the same command in a different directory (and/or drive) does work.

**More details**
```
C:\Users\Sor>"J:\jdks\graalvm-jdk-20.0.1+9.1\bin\native-image.cmd" A
========================================================================================================================
GraalVM Native Image: Generating 'a' (executable)...
========================================================================================================================
[1/8] Initializing...                                                                                    (8.8s @ 0.18GB)
 Java version: 20.0.1+9, vendor version: Oracle GraalVM 20.0.1+9.1
 Graal compiler: optimization level: 2, target machine: x86-64-v3, PGO: ML-inferred
 C compiler: cl.exe (microsoft, x64, 19.35.32217)
 Garbage collector: Serial GC (max heap size: 80% of RAM)
[2/8] Performing analysis...  [*]                                                                        (6.0s @ 0.76GB)
   3,139 (72.29%) of  4,342 types reachable
   3,796 (50.24%) of  7,556 fields reachable
  16,296 (47.49%) of 34,312 methods reachable
     936 types,   106 fields, and   446 methods registered for reflection

Error: Unable to handle classpath element 'C:\Users\Sor'. Make sure that all classpath entries are either directories or valid jar files.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
------------------------------------------------------------------------------------------------------------------------
                        0.8s (5.2% of total time) in 18 GCs | Peak RSS: 1.67GB | CPU load: 3.92
========================================================================================================================
Finished generating 'a' in 15.0s.
```

Used `-H:+ReportExceptionStackTraces` to print stacktrace of underlying exception:
```
com.oracle.svm.core.util.UserError$UserException: Unable to handle classpath element 'C:\Users\Sor'. Make sure that all classpath entries are either directories or valid jar files.
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ClassLoaderSupportImpl.collectResources(ClassLoaderSupportImpl.java:132)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ResourcesFeature.duringAnalysis(ResourcesFeature.java:343)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$10(NativeImageGenerator.java:770)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:86)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$11(NativeImageGenerator.java:770)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.AbstractAnalysisEngine.runAnalysis(AbstractAnalysisEngine.java:179)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:767)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:582)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:539)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:408)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:612)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:134)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)
```

Work-around:

- `C:\Users\Sor>copy A.class J:\local`
- `J:\local>"J:\jdks\graalvm-jdk-20.0.1+9.1\bin\native-image.cmd" A`

```
========================================================================================================================
GraalVM Native Image: Generating 'a' (executable)...
========================================================================================================================
[1/8] Initializing...                                                                                    (5.8s @ 0.18GB)
 Java version: 20.0.1+9, vendor version: Oracle GraalVM 20.0.1+9.1
 Graal compiler: optimization level: 2, target machine: x86-64-v3, PGO: ML-inferred
 C compiler: cl.exe (microsoft, x64, 19.35.32217)
 Garbage collector: Serial GC (max heap size: 80% of RAM)
[2/8] Performing analysis...  [****]                                                                     (7.3s @ 0.40GB)
   3,199 (72.89%) of  4,389 types reachable
   3,869 (50.58%) of  7,650 fields reachable
  16,638 (47.50%) of 35,028 methods reachable
     959 types,   106 fields, and   487 methods registered for reflection
      61 types,    51 fields, and    52 methods registered for JNI access
       1 native library: version
[3/8] Building universe...                                                                               (0.9s @ 0.89GB)
[4/8] Parsing methods...      [**]                                                                       (2.7s @ 0.41GB)
[5/8] Inlining methods...     [***]                                                                      (0.3s @ 0.76GB)
[6/8] Compiling methods...    [****]                                                                    (13.7s @ 0.78GB)
[7/8] Layouting methods...    [*]                                                                        (1.2s @ 0.47GB)
[8/8] Creating image...       [*]                                                                        (1.9s @ 0.66GB)
   7.63MB (49.67%) for code area:     8,385 compilation units
   7.55MB (49.11%) for image heap:  137,411 objects and 5 resources
 191.97kB ( 1.22%) for other data
  15.37MB in total
------------------------------------------------------------------------------------------------------------------------
Top 10 origins of code area:                                Top 10 object types in image heap:
   5.45MB java.base                                            1.43MB byte[] for code metadata
   1.60MB svm.jar (Native Image)                             906.17kB byte[] for java.lang.String
 161.58kB java.logging                                       906.14kB java.lang.String
 143.09kB com.oracle.svm.svm_enterprise                      866.73kB byte[] for general heap data
  59.74kB jdk.proxy1                                         566.88kB java.lang.Class
  48.62kB jdk.proxy3                                         312.22kB java.util.concurrent.ConcurrentHashMap$Node
  34.48kB org.graalvm.nativeimage.base                       241.49kB java.lang.Object[]
  33.15kB org.graalvm.sdk                                    237.00kB java.util.HashMap$Node
  22.01kB jdk.internal.vm.compiler                           156.31kB byte[] for reflection metadata
  16.69kB jdk.proxy2                                         154.27kB byte[] for embedded resources
  16.94kB for 3 more packages                                  1.53MB for 893 more object types
------------------------------------------------------------------------------------------------------------------------
Recommendations:
 PGO:  Use Profile-Guided Optimizations ('--pgo') for improved throughput.
 HEAP: Set max heap for improved and more predictable memory usage.
 CPU:  Enable more CPU features with '-march=native' for improved performance.
 QBM:  Use the quick build mode ('-Ob') to speed up builds during development.
 BRPT: Try out the new build reports with '-H:+BuildReport'.
------------------------------------------------------------------------------------------------------------------------
                        2.0s (5.6% of total time) in 52 GCs | Peak RSS: 2.37GB | CPU load: 8.70
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 J:\local\a.exe (executable)
========================================================================================================================
Finished generating 'a' in 34.6s.
```

**Comment by fniephaus** [comment]
Thanks for the bug report, @sormuras. We'll look into it. :)

**Comment by wirthi** [comment]
Our general guidance is not to work from the user-directory. This would put the whole user directory on the classpath. Not only might this take quite a while to scan, I assume the problem experienced here was triggered by some follow-up problem of this.

At the very least, copy your file to a subdirectory, avoiding any problem.

I was not able to reproduce your exact problem, but while doing so, native-image indexed e.g. all files I was using via WSL, which took quite long. We certainly suggest do avoid this.
