### ISSUE TITLE
NullPointerException in DefaultJavaLoweringProvider.java

### ISSUE THREAD

**Issue by katox** [oracle/graal#682]
I'm trying to compile a web application skeleton based on Clojure **Luminus** template using **http-kit** (which should be already suported) plus a **postgresql** database support.

I created a substitution class to avoid running into ClassNotFound in postgresql driver but `native-image` fails to create an image while processing *Hikari Connection Pool*:

```[lumgraal:32168]    classlist:   5,686.55 ms
[lumgraal:32168]        (cap):     871.90 ms
[lumgraal:32168]        setup:   1,432.93 ms
[lumgraal:32168]   (typeflow): 132,606.40 ms
[lumgraal:32168]    (objects):  74,390.44 ms
[lumgraal:32168]   (features):     327.90 ms
[lumgraal:32168]     analysis: 209,028.51 ms
[lumgraal:32168]     universe:   1,525.21 ms
[lumgraal:32168]      (parse):   4,443.80 ms
[lumgraal:32168]     (inline):   5,041.62 ms
[lumgraal:32168]    (compile):   7,328.37 ms
[lumgraal:32168]      compile:  17,060.93 ms
fatal error: org.graalvm.compiler.debug.GraalError: java.lang.NullPointerException
	at method: Object com.zaxxer.hikari.util.ConcurrentBag$$Lambda$438.2146953421.get()  [Virtual call from void SystemPropertiesSupport.initializeLazyValue(String), callTarget Object Supplier.get()]
	at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:956)
	at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:882)
	at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:257)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at org.graalvm.compiler.replacements.DefaultJavaLoweringProvider.insertAllocationBarrier(DefaultJavaLoweringProvider.java:933)
	at org.graalvm.compiler.replacements.DefaultJavaLoweringProvider.finishAllocatedObjects(DefaultJavaLoweringProvider.java:922)
	at org.graalvm.compiler.replacements.DefaultJavaLoweringProvider.lowerCommitAllocationNode(DefaultJavaLoweringProvider.java:850)
	at org.graalvm.compiler.replacements.DefaultJavaLoweringProvider.lower(DefaultJavaLoweringProvider.java:229)
	at com.oracle.svm.core.graal.meta.SubstrateBasicLoweringProvider.lower(SubstrateBasicLoweringProvider.java:143)
	at org.graalvm.compiler.nodes.virtual.CommitAllocationNode.lower(CommitAllocationNode.java:120)
	at org.graalvm.compiler.phases.common.LoweringPhase$Round.process(LoweringPhase.java:465)
	at org.graalvm.compiler.phases.common.LoweringPhase$Round.access$200(LoweringPhase.java:341)
	at org.graalvm.compiler.phases.common.LoweringPhase$Round$ProcessFrame.preprocess(LoweringPhase.java:405)
	at org.graalvm.compiler.phases.common.LoweringPhase.processBlock(LoweringPhase.java:564)
	at org.graalvm.compiler.phases.common.LoweringPhase$Round.run(LoweringPhase.java:390)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:212)
	at org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:56)
	at org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:38)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.phases.common.LoweringPhase.lower(LoweringPhase.java:261)
	at org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:254)
	at org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:93)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:212)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:256)
	at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:180)
	at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:165)
	at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:925)
	... 8 more
Error: Image building with exit status 1
```

Here is the repo that contains the sample project sources: [https://github.com/katox/lumgraal](https://github.com/katox/lumgraal).

 To reproduce the bug you need to install `lein`, create a maven artifact for `svm.jar`, create an uberjar and run `native-image` on it. The parameters used are in the `run.sh` script. 

Necessary steps to reproduce the issue are described in the [README.md](https://github.com/katox/lumgraal/blob/master/README.md) in the sample repository.

**Comment by cstancu** [comment]
@katox this issue should be fixed in https://github.com/oracle/graal/commit/f5da6acd973cad37bc1c7b3dc7658acbca89ab4f. The fix will be shipped with rc7. In the meantime you can try [building from source](https://github.com/oracle/graal/tree/master/substratevm#quick-start).
