### ISSUE TITLE
Unsupported method java.security.ProtectionDomain.getCodeSource()

### ISSUE THREAD

**Issue by vhiairrassary** [oracle/graal#685]
Do you plan to support `java.security.ProtectionDomain.getCodeSource()` in the future? [It is used in the aws-sdk-java-v2 ](https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/util/UserAgentUtils.java#L152). Otherwise I can create a ticket in this project to ask them to be more friendly with GraalVM/SubstrateVM.

```
mx native-image \
  -jar ./test-aws-graal-assembly-0.1.jar \
  --enable-url-protocols=https \
  -H:+JNI \
  -H:ReflectionConfigurationFiles=./aws_reflection_config.json \
  -H:DynamicProxyConfigurationFiles=./aws_proxy_config.json \
  -H:IncludeResources='^software/amazon/awssdk/regions/internal/region/endpoints\.json$'
[test-aws-graal-assembly-0.1:14314]    classlist:   5,749.96 ms
[test-aws-graal-assembly-0.1:14314]        (cap):   1,148.26 ms
[test-aws-graal-assembly-0.1:14314]        setup:   2,767.20 ms
[test-aws-graal-assembly-0.1:14314]     analysis:  18,524.57 ms
error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported method java.security.ProtectionDomain.getCodeSource() is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported method java.security.ProtectionDomain.getCodeSource() is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Trace:
	at parsing software.amazon.awssdk.core.internal.util.UserAgentUtils.kotlinVersion(UserAgentUtils.java:152)
Call path from entry point to software.amazon.awssdk.core.internal.util.UserAgentUtils.kotlinVersion():
	at software.amazon.awssdk.core.internal.util.UserAgentUtils.kotlinVersion(UserAgentUtils.java:147)
	at software.amazon.awssdk.core.internal.util.UserAgentUtils.getAdditionalJvmLanguages(UserAgentUtils.java:112)
	at software.amazon.awssdk.core.internal.util.UserAgentUtils.userAgent(UserAgentUtils.java:87)
	at software.amazon.awssdk.core.internal.util.UserAgentUtils.initializeUserAgent(UserAgentUtils.java:72)
	at software.amazon.awssdk.core.internal.util.UserAgentUtils.getUserAgent(UserAgentUtils.java:59)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.lambda$mergeGlobalDefaults$0(SdkDefaultClientBuilder.java:193)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder$$Lambda$358/1376518821.accept(Unknown Source)
	at software.amazon.awssdk.utils.builder.SdkBuilder.applyMutation(SdkBuilder.java:60)
	at software.amazon.awssdk.core.internal.client.config.SdkClientConfiguration.merge(SdkClientConfiguration.java:67)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.mergeGlobalDefaults(SdkDefaultClientBuilder.java:190)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:145)
	at software.amazon.awssdk.services.s3.DefaultS3ClientBuilder.buildClient(DefaultS3ClientBuilder.java:27)
	at software.amazon.awssdk.services.s3.DefaultS3ClientBuilder.buildClient(DefaultS3ClientBuilder.java:22)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:120)
	at Main$.main(Main.scala:25)
	at Main.main(Main.scala)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:163)
	at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)

Error: Image building with exit status 1
```

**Comment by cstancu** [comment]
@vhiairrassary we haven't looked into `java.security.ProtectionDomain.getCodeSource()` yet, however even if we will have some partial support for it in the future I don't think we can support this use case as it relies on the JAR to be available at run time: it loads "the Manifest from that class' JAR to determine the Kotlin version." You can probably work around this with substitutions though.

**Comment by cstancu** [comment]
In https://github.com/oracle/graal/commit/e3ef4f3f741d171a83c2dd2a0390dbede6b2c62d the behaviour of `ProtectionDomain` changes in the sense that `Class.getProtectionDomain().getCodeSource()` always [returns `null`](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/hub/DynamicHub.java#L1065) instead of failing at build time with
`Unsupported method java.security.ProtectionDomain.getCodeSource() is reachable`. 

In your case this means that [`software.amazon.awssdk.core.internal.util.UserAgentUtils.kotlinVersion()`](https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/util/UserAgentUtils.java#L146) will always return the empty string, `""`. You can modify this behavior by substituting `UserAgentUtils.kotlinVersion()` and returning an image build time computed value.

It didn't make the cut for rc7 so it will be available in rc8 or you can build from source.

**Comment by blazingkin** [comment]
This is still an issue, here is a short code sample that will reproduce the issue

```
import java.net.URL;
public class GetSourceDir {

    public static void main(String[] args) {
        try {
            System.out.println(GetSourceDir.class);
            System.out.println(GetSourceDir.class.getProtectionDomain());
            System.out.println(GetSourceDir.class.getProtectionDomain().getCodeSource());
            System.out.println(GetSourceDir.class.getProtectionDomain().getCodeSource().getLocation());
            URL cwd = GetSourceDir.class.getProtectionDomain().getCodeSource().getLocation();
            System.out.println(cwd.toURI());
        }catch(Exception e){
            e.printStackTrace();
        }
    }

}
```

The expected behavior should return the directory that the binary is in.

**Comment by blazingkin** [comment]
Is a warning possible?

This led to an unexpected Null Pointer Exception when using `native-image`.
