### ISSUE TITLE
native-image crashes, when CCompilerInvoker is not present

### ISSUE THREAD

**Issue by Berstanio** [oracle/graal#6875]
Hi,

native-image crashes, if the CCompilerInvoker is not present:
https://github.com/oracle/graal/blob/f9ef31f0c872872f7008ae771540f3020223414c/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ProgressReporter.java#L249-L254
I don't know though, whether a missing `CCompilerInvoker` in itself is a bug. 

Below the error report:

# GraalVM Native Image Error Report

## Build Output

```
========================================================================================================================
GraalVM Native Image: Generating 'org.moe.ioslauncher' (shared library)...
========================================================================================================================
[1/8] Initializing...                                                                                    (2,3s @ 0,09GB)
 Java version: 17.0.7+7, vendor version: GraalVM CE 17.0.7+7.1
 Graal compiler: optimization level: 2, target machine: armv8-a

```

## Stack Trace

```java
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "value" is null
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ProgressReporterJsonHelper$GeneralInfo.record(ProgressReporterJsonHelper.java:243)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ProgressReporter.recordJsonMetric(ProgressReporter.java:781)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ProgressReporter.printInitializeEnd(ProgressReporter.java:254)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:946)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:579)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:539)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:408)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:612)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:134)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)
```

## GraalVM Setup

| Name | Value |
| ---- | ----- |
| Java version | `17.0.7+7` |
| Vendor version | `GraalVM CE 17.0.7+7.1` |
| Runtime version | `17.0.7+7-jvmci-23.0-b12` |
<details>
<summary>GraalVM <code>release</code> file</summary>

```
IMPLEMENTOR="GraalVM Community"
JAVA_VERSION="17.0.7"
JAVA_VERSION_DATE="2023-04-18"
LIBC="default"
MODULES="java.base java.compiler java.instrument java.logging java.management jdk.internal.vm.ci jdk.jfr jdk.unsupported org.graalvm.sdk java.datatransfer java.xml java.prefs java.desktop java.transaction.xa java.sql jdk.management org.graalvm.truffle jdk.internal.vm.compiler com.oracle.graal.graal_enterprise com.oracle.svm.extraimage_enterprise com.oracle.svm.svm_enterprise com.oracle.svm_enterprise.ml_dataset java.security.sasl java.naming java.rmi java.management.rmi java.net.http java.scripting java.security.jgss java.sql.rowset java.xml.crypto java.se java.smartcardio jdk.accessibility jdk.internal.jvmstat jdk.attach jdk.charsets jdk.compiler jdk.crypto.ec jdk.crypto.cryptoki jdk.dynalink jdk.internal.ed jdk.editpad jdk.hotspot.agent jdk.httpserver jdk.incubator.foreign jdk.incubator.vector jdk.internal.le jdk.internal.opt jdk.internal.vm.compiler.management jdk.internal.vm.compiler.truffle.jfr jdk.jartool jdk.javadoc jdk.jcmd jdk.management.agent jdk.jconsole jdk.jdeps jdk.jdwp.agent jdk.jdi jdk.jlink jdk.jpackage jdk.jshell jdk.jsobject jdk.jstatd jdk.localedata jdk.management.jfr jdk.naming.dns jdk.naming.rmi jdk.net jdk.nio.mapmode jdk.random jdk.sctp jdk.security.auth jdk.security.jgss jdk.unsupported.desktop jdk.xml.dom jdk.zipfs org.graalvm.extraimage.builder org.graalvm.js.scriptengine org.graalvm.locator org.graalvm.nativeimage.llvm"
OS_ARCH="aarch64"
OS_NAME="Darwin"
SOURCE=".:git:f0c27edacc83+ labsjdk-builder:6fdba7be9f6310a40fce95618f0a2195d0cbf183 compiler:f9ef31f0c872872f7008ae771540f3020223414c graal-js:940f9a35184ed498c66f156bd9f7adc99a3cec97 java-benchmarks:f9ef31f0c872872f7008ae771540f3020223414c regex:f9ef31f0c872872f7008ae771540f3020223414c sdk:f9ef31f0c872872f7008ae771540f3020223414c substratevm:f9ef31f0c872872f7008ae771540f3020223414c tools:f9ef31f0c872872f7008ae771540f3020223414c truffle:f9ef31f0c872872f7008ae771540f3020223414c vm:f9ef31f0c872872f7008ae771540f3020223414c"
GRAALVM_VERSION="23.0.0"
COMMIT_INFO={"compiler": {"commit.committer": "Gilles Duboscq <gilles.m.duboscq@oracle.com>", "commit.committer-ts": 1686090907, "commit.rev": "f9ef31f0c872872f7008ae771540f3020223414c"}, "graal-js": {"commit.committer": "Gilles Duboscq <gilles.m.duboscq@oracle.com>", "commit.committer-ts": 1686090643, "commit.rev": "940f9a35184ed498c66f156bd9f7adc99a3cec97"}, "java-benchmarks": {"commit.committer": "Gilles Duboscq <gilles.m.duboscq@oracle.com>", "commit.committer-ts": 1686090907, "commit.rev": "f9ef31f0c872872f7008ae771540f3020223414c"}, "regex": {"commit.committer": "Gilles Duboscq <gilles.m.duboscq@oracle.com>", "commit.committer-ts": 1686090907, "commit.rev": "f9ef31f0c872872f7008ae771540f3020223414c"}, "sdk": {"commit.committer": "Gilles Duboscq <gilles.m.duboscq@oracle.com>", "commit.committer-ts": 1686090907, "commit.rev": "f9ef31f0c872872f7008ae771540f3020223414c"}, "substratevm": {"commit.committer": "Gilles Duboscq <gilles.m.duboscq@oracle.com>", "commit.committer-ts": 1686090907, "commit.rev": "f9ef31f0c872872f7008ae771540f3020223414c"}, "tools": {"commit.committer": "Gilles Duboscq <gilles.m.duboscq@oracle.com>", "commit.committer-ts": 1686090907, "commit.rev": "f9ef31f0c872872f7008ae771540f3020223414c"}, "truffle": {"commit.committer": "Gilles Duboscq <gilles.m.duboscq@oracle.com>", "commit.committer-ts": 1686090907, "commit.rev": "f9ef31f0c872872f7008ae771540f3020223414c"}, "vm": {"commit.committer": "Gilles Duboscq <gilles.m.duboscq@oracle.com>", "commit.committer-ts": 1686090907, "commit.rev": "f9ef31f0c872872f7008ae771540f3020223414c"}}
component_catalog="https://www.graalvm.org/component-catalog/v2/graal-updater-component-catalog-java17.properties|{ee=GraalVM Enterprise Edition}rest://gds.oracle.com/api/20220101/"
GDS_PRODUCT_ID="D53FAE8052773FFAE0530F15000AA6C6"
```

</details>

## Builder Setup

<details>
<summary>Class path</summary>

```
/Users/USERNAME/IdeaProjects/tmpSamples/moe-samples-java/Calculator/ios/build/moe/main/proguard/release/output.jar
/Users/USERNAME/IdeaProjects/tmpSamples/moe-samples-java/Calculator/ios/build/moe/main/resources/release/application.jar
```

</details>

<details>
<summary>Module path</summary>

```
/Library/Java/JavaVirtualMachines/graalvm-community-openjdk-17.0.7+7.1/Contents/Home/lib/svm/library-support.jar
/Library/Java/JavaVirtualMachines/graalvm-community-openjdk-17.0.7+7.1/Contents/Home/lib/truffle/truffle-api.jar
/Library/Java/JavaVirtualMachines/graalvm-community-openjdk-17.0.7+7.1/Contents/Home/lib/svm/builder/svm.jar
/Library/Java/JavaVirtualMachines/graalvm-community-openjdk-17.0.7+7.1/Contents/Home/lib/svm/builder/native-image-base.jar
/Library/Java/JavaVirtualMachines/graalvm-community-openjdk-17.0.7+7.1/Contents/Home/lib/svm/builder/objectfile.jar
/Library/Java/JavaVirtualMachines/graalvm-community-openjdk-17.0.7+7.1/Contents/Home/lib/svm/builder/pointsto.jar
```

</details>

<details>
<summary>Builder arguments</summary>

```
-H:CLibraryPath=/Library/Java/JavaVirtualMachines/graalvm-community-openjdk-17.0.7+7.1/Contents/Home/lib/svm/clibraries/darwin-aarch64
-H:Path=/Users/USERNAME/IdeaProjects/tmpSamples/moe-samples-java/Calculator/ios/build/moe/main/native_image/Release-iphoneos-arm64/svmTmp
-H:+SharedLibrary
-H:-SpawnIsolates
-H:PageSize=16384
-H:-DeadlockWatchdogExitOnTimeout
-H:DeadlockWatchdogInterval=0
-H:+ExitAfterRelocatableImageWrite
-H:Features=org.graalvm.home.HomeFinderFeature
-H:+IncludeAllLocales
-H:ClassInitialization=org.moe.MOE$Build:build_time
-H:TempDirectory=/Users/USERNAME/IdeaProjects/tmpSamples/moe-samples-java/Calculator/ios/build/moe/main/native_image/Release-iphoneos-arm64/svmTmp
-H:+UseCAPCache
-H:CAPCacheDir=/Users/USERNAME/IdeaProjects/tmpSamples/moe-samples-java/Calculator/ios/build/moe/main/native_image/Release-iphoneos-arm64/svmTmp/capcache
-H:ResourceConfigurationFiles=/Users/USERNAME/IdeaProjects/tmpSamples/moe-samples-java/Calculator/ios/build/moe/main/resources/release/resource-config.json
-H:JNIConfigurationFiles=/Users/USERNAME/.moe/moe-sdk-2.0.0-SNAPSHOT/tools/jni-config-base.json
-H:JNIConfigurationFiles=/Users/USERNAME/IdeaProjects/tmpSamples/moe-samples-java/Calculator/ios/build/moe/main/reflection/release/reflection-config.json
-H:ReflectionConfigurationFiles=/Users/USERNAME/.moe/moe-sdk-2.0.0-SNAPSHOT/tools/reflection-config-base.json
-H:ReflectionConfigurationFiles=/Users/USERNAME/IdeaProjects/tmpSamples/moe-samples-java/Calculator/ios/build/moe/main/reflection/release/reflection-config.json
-H:DynamicProxyConfigurationFiles=/Users/USERNAME/IdeaProjects/tmpSamples/moe-samples-java/Calculator/ios/build/moe/main/reflection/release/proxy-config.json
-H:+AllowIncompleteClasspath
-H:Class@explicit main-class=org.moe.IOSLauncher
-H:Name@main-class lower case as image name=org.moe.ioslauncher
-H:Features@jar:file:///Library/Java/JavaVirtualMachines/graalvm-community-openjdk-17.0.7+7.1/Contents/Home/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/thirdparty/native-image.properties=com.oracle.svm.thirdparty.gson.GsonFeature
-H:Features@jar:file:///Library/Java/JavaVirtualMachines/graalvm-community-openjdk-17.0.7+7.1/Contents/Home/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/polyglot/native-image.properties=com.oracle.svm.polyglot.groovy.GroovyIndyInterfaceFeature,com.oracle.svm.polyglot.scala.ScalaFeature
```

</details>

<details>
<summary>Builder properties</summary>

```
-Dcom.oracle.graalvm.isaot=true
-Dgraalvm.ForcePolyglotInvalid=true
-Dgraalvm.locatorDisabled=true
-Djava.awt.headless=true
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader
-Djdk.internal.lambda.disableEagerInitialization=true
-Djdk.internal.lambda.eagerlyInitialize=false
-Djdk.internal.lambda.eagerlyInitialize=false
-Djdk.module.main=org.graalvm.nativeimage.builder
-Dmoe.debug=false
-Dmoe.platform.name=iphoneos
-Dorg.graalvm.vendor=GraalVM Community
-Dorg.graalvm.vendorurl=https://www.graalvm.org/
-Dorg.graalvm.vendorversion=GraalVM CE 17.0.7+7.1
-Dorg.graalvm.version=23.0.0
-Dsubstratevm.IgnoreGraalVersionCheck=true
-Dsvm.platform=org.graalvm.nativeimage.Platform$IOS_AARCH64
-Dsvm.targetArch=arm64
-Dsvm.targetName=iOS
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime
-Dtruffle.TrustAllTruffleRuntimeProviders=true
```

</details>

<details>
<summary>Features enabled</summary>

```
com.oracle.svm.core.IsolateArgumentParserFeature, []
com.oracle.svm.core.IsolateListenerFeature, [com.oracle.svm.core.IsolateListenerSupportFeature]
com.oracle.svm.core.IsolateListenerSupportFeature, []
com.oracle.svm.core.RuntimeAssertionsSupportFeature, []
com.oracle.svm.core.StaticFieldsFeature, []
com.oracle.svm.core.StaticFieldsSupportFeature, []
com.oracle.svm.core.SubstrateExitHandlerFeature, []
com.oracle.svm.core.SubstrateSegfaultHandlerFeature, [com.oracle.svm.core.IsolateListenerSupportFeature]
com.oracle.svm.core.UniqueShortNameProviderDefaultImplFeature, []
com.oracle.svm.core.UnsafeMemoryUtilFeature, []
com.oracle.svm.core.aarch64.AArch64FrameAccessFeature, []
com.oracle.svm.core.allocationprofile.AllocationProfilingFeature, [com.oracle.svm.core.jdk.RuntimeSupportFeature]
com.oracle.svm.core.c.CTypeConversionSupportImplFeature, []
com.oracle.svm.core.c.ProjectHeaderFileHeaderResolversRegistryFeature, []
com.oracle.svm.core.c.function.IsolateSupportImplFeature, []
com.oracle.svm.core.code.CodeInfoFeature, [com.oracle.svm.core.util.CounterFeature]
com.oracle.svm.core.code.CodeInfoMemoryWalkerFeature, []
com.oracle.svm.core.code.InstalledCodeObserverSupportFeature, []
com.oracle.svm.core.cpufeature.RuntimeCPUFeatureCheckFeature, []
com.oracle.svm.core.cpufeature.RuntimeCPUFeatureCheckImplFeature, []
com.oracle.svm.core.genscavenge.AlignedHeapChunkMemoryWalkerAccessImplFeature, []
com.oracle.svm.core.genscavenge.JfrGCEventFeature, []
com.oracle.svm.core.genscavenge.PinnedObjectImplPinnedObjectSupportImplFeature, []
com.oracle.svm.core.genscavenge.UnalignedHeapChunkMemoryWalkerAccessImplFeature, []
com.oracle.svm.core.genscavenge.graal.BarrierSnippetCountersFeature, [com.oracle.svm.core.util.CounterFeature]
com.oracle.svm.core.genscavenge.graal.GenScavengeGCFeature, [com.oracle.svm.core.jdk.RuntimeSupportFeature com.oracle.svm.core.jdk.management.ManagementFeature com.oracle.svm.core.jvmstat.PerfDataFeature com.oracle.svm.core.heap.AllocationFeature]
com.oracle.svm.core.graal.aarch64.AArch64NativePatchConsumerFactoryFeature, []
com.oracle.svm.core.graal.aarch64.SubstrateAArch64Feature, []
com.oracle.svm.core.graal.aarch64.SubstrateAArch64GraphBuilderPlugins, []
com.oracle.svm.core.graal.jdk.JDKIntrinsicsFeature, []
com.oracle.svm.core.graal.snippets.CFunctionSnippetsFeature, []
com.oracle.svm.core.graal.snippets.DeoptSnippetsFeature, []
com.oracle.svm.core.graal.snippets.ExceptionFeature, []
com.oracle.svm.core.graal.snippets.SafepointFeature, []
com.oracle.svm.core.graal.snippets.StackOverflowCheckFeature, []
com.oracle.svm.core.graal.snippets.aarch64.AArch64ArithmeticForeignCallsFeature, []
com.oracle.svm.core.graal.snippets.aarch64.AArch64SnippetsFeature, []
com.oracle.svm.core.graal.stackvalue.StackValueFeature, []
com.oracle.svm.core.handles.ObjectHandlesSupportImplFeature, []
com.oracle.svm.core.heap.AllocationFeature, []
com.oracle.svm.core.heap.GCCauseFeature, []
com.oracle.svm.core.heap.HostedHeapSizeVerifierFeature, []
com.oracle.svm.core.heap.ReferenceAccessImplFeature, []
com.oracle.svm.core.heap.ReferenceHandlerThreadFeature, []
com.oracle.svm.core.heap.VMOperationInfosFeature, []
com.oracle.svm.core.heap.VMOperationNamesFeatures, []
com.oracle.svm.core.hub.ClassForNameSupportFeature, []
com.oracle.svm.core.hub.DynamicHubSupportFeature, []
com.oracle.svm.core.identityhashcode.SubstrateIdentityHashCodeFeature, []
com.oracle.svm.core.jdk.AtomicFieldUpdaterFeature, []
com.oracle.svm.core.jdk.ClassLoaderSupportFeature, []
com.oracle.svm.core.jdk.CompletableFutureFeature, []
com.oracle.svm.core.jdk.FileSystemProviderFeature, []
com.oracle.svm.core.jdk.ForkJoinPoolFeature, []
com.oracle.svm.core.jdk.InnocuousForkJoinWorkerThreadFeature, []
com.oracle.svm.core.jdk.JDKVersionSpecificResourceBuilderJDK11OrLaterFeature, []
com.oracle.svm.core.jdk.JRTDisableFeature, []
com.oracle.svm.core.jdk.JavaNetFeature, []
com.oracle.svm.core.jdk.JavaNetHttpFeature, []
com.oracle.svm.core.jdk.NativeLibrarySupportFeature, []
com.oracle.svm.core.jdk.PlatformNativeLibrarySupportFeature, []
com.oracle.svm.core.jdk.RecordSupportJDK11OrEarlierFeature, []
com.oracle.svm.core.jdk.ResourcesFeature, []
com.oracle.svm.core.jdk.RuntimeFeature, [com.oracle.svm.core.jdk.RuntimeSupportFeature]
com.oracle.svm.core.jdk.RuntimeSupportFeature, []
com.oracle.svm.core.jdk.SealedClassSupportJDK11OrEarlierFeature, []
com.oracle.svm.core.jdk.ServiceCatalogSupportFeature, []
com.oracle.svm.core.jdk.TimeZoneFeature, []
com.oracle.svm.core.jdk.TrustStoreManagerFeature, []
com.oracle.svm.core.jdk.URLProtocolsSupportFeature, []
com.oracle.svm.core.jdk.VarHandleFeature, []
com.oracle.svm.core.jdk.localization.LocalizationFeature, []
com.oracle.svm.core.jdk.management.ManagementFeature, [com.oracle.svm.core.jdk.RuntimeSupportFeature com.oracle.svm.core.thread.ThreadListenerSupportFeature]
com.oracle.svm.core.jdk17.RecordSupportJDK17OrLaterFeature, []
com.oracle.svm.core.jdk17.SealedClassSupportJDK17OrLaterFeature, []
com.oracle.svm.core.jfr.sampler.JfrNoExecutionSamplerFeature, [com.oracle.svm.core.jfr.JfrFeature]
com.oracle.svm.core.jfr.sampler.JfrRecurringCallbackExecutionSamplerFeature, [com.oracle.svm.core.jfr.JfrFeature]
com.oracle.svm.core.jvmstat.PerfDataFeature, [com.oracle.svm.core.thread.VMOperationListenerSupportFeature com.oracle.svm.core.jdk.RuntimeSupportFeature]
com.oracle.svm.core.meta.SubstrateObjectConstantEqualityFeature, []
com.oracle.svm.core.monitor.MonitorFeature, []
com.oracle.svm.core.option.RuntimeOptionsSupportImplFeature, []
com.oracle.svm.core.option.ValidateImageBuildOptionsFeature, []
com.oracle.svm.core.os.BufferedFileOperationFeature, []
com.oracle.svm.core.os.ImageHeapProviderFeature, []
com.oracle.svm.core.os.OSCommittedMemoryProviderFeature, []
com.oracle.svm.core.posix.IgnoreSIGPIPEFeature, []
com.oracle.svm.core.posix.PosixLoadAverageSupportFeature, []
com.oracle.svm.core.posix.PosixLogHandlerFeature, []
com.oracle.svm.core.posix.PosixNativeLibraryFeature, []
com.oracle.svm.core.posix.PosixRawFileOperationFeature, []
com.oracle.svm.core.posix.PosixSubstrateSegfaultHandlerFeature, []
com.oracle.svm.core.posix.PosixSubstrateSigProfHandlerFeature, [com.oracle.svm.core.IsolateListenerSupportFeature com.oracle.svm.core.jfr.JfrFeature]
com.oracle.svm.core.posix.PosixVirtualMemoryProviderFeature, []
com.oracle.svm.core.posix.UnmanagedMemorySupportImplFeature, []
com.oracle.svm.core.posix.aarch64.AArch64DarwinUContextRegisterDumperFeature, []
com.oracle.svm.core.posix.darwin.DarwinImageSingletonsFeature, []
com.oracle.svm.core.posix.darwin.DarwinLibCSupportFeature, []
com.oracle.svm.core.posix.darwin.DarwinProcessPropertiesSupportFeature, []
com.oracle.svm.core.posix.darwin.DarwinStackOverflowSupportFeature, []
com.oracle.svm.core.posix.darwin.DarwinSystemPropertiesFeature, []
com.oracle.svm.core.posix.darwin.DarwinThreadCpuTimeSupportFeature, []
com.oracle.svm.core.posix.darwin.DarwinTimeUtilFeature, []
com.oracle.svm.core.posix.darwin.DarwinVMSemaphoreFeature, []
com.oracle.svm.core.posix.darwin.PhysicalMemorySupportImplFeature, []
com.oracle.svm.core.posix.heapdump.AllocationFreeFileOutputStreamPosixFeature, []
com.oracle.svm.core.posix.pthread.PthreadVMLockFeature, []
com.oracle.svm.core.posix.thread.PosixParkerFactoryFeature, []
com.oracle.svm.core.posix.thread.PosixPlatformThreadsFeature, []
com.oracle.svm.core.posix.thread.PosixVMThreadsFeature, []
com.oracle.svm.core.reflect.target.ReflectionMetadataDecoderImplFeature, []
com.oracle.svm.core.reflect.target.ReflectionMetadataDecoderImplMetadataAccessorImplFeature, []
com.oracle.svm.core.reflect.target.ReflectionMetadataEncodingFeature, []
com.oracle.svm.core.thread.ContinuationsFeature, []
com.oracle.svm.core.thread.JavaThreadsFeature, []
com.oracle.svm.core.thread.SafepointMasterFeature, []
com.oracle.svm.core.thread.ThreadListenerSupportFeature, []
com.oracle.svm.core.thread.ThreadingSupportImplFeature, []
com.oracle.svm.core.thread.VMOperationControlFeature, []
com.oracle.svm.core.thread.VMOperationListenerSupportFeature, []
com.oracle.svm.core.threadlocal.VMThreadLocalInfosFeature, []
com.oracle.svm.core.util.CounterFeature, []
com.oracle.svm.core.util.HostedStringDeduplicationFeature, []
com.oracle.svm.graal.RuntimeCPUFeatureRegionFeature, []
com.oracle.svm.graal.meta.aarch64.AArch64RuntimeCodeInstallerPlatformHelperFeature, []
com.oracle.svm.graal.stubs.AArch64StubForeignCallsFeature, []
com.oracle.svm.hosted.AArch64CPUFeatureAccessFeature, []
com.oracle.svm.hosted.ClassLoaderFeature, []
com.oracle.svm.hosted.ClassNewInstanceFeature, []
com.oracle.svm.hosted.ClassPredefinitionFeature, []
com.oracle.svm.hosted.ClassValueFeature, []
com.oracle.svm.hosted.ConcurrentReachabilityHandler, []
com.oracle.svm.hosted.FallbackFeature, []
com.oracle.svm.hosted.Log4ShellFeature, []
com.oracle.svm.hosted.LoggingFeature, []
com.oracle.svm.hosted.ModuleLayerFeature, []
com.oracle.svm.hosted.NativeSecureRandomFilesCloser, []
com.oracle.svm.hosted.ProgressReporterFeature, []
com.oracle.svm.hosted.ProtectionDomainFeature, []
com.oracle.svm.hosted.ResourcesFeature, []
com.oracle.svm.hosted.SecurityServicesFeature, []
com.oracle.svm.hosted.ServiceLoaderFeature, []
com.oracle.svm.hosted.SubstrateDiagnosticFeature, []
com.oracle.svm.hosted.SystemInOutErrFeature, []
com.oracle.svm.hosted.VMFeature, []
com.oracle.svm.hosted.ameta.HostedDynamicHubFeature, []
com.oracle.svm.hosted.annotation.AnnotationSupportFeature, []
com.oracle.svm.hosted.annotation.AnnotationTypeFeature, []
com.oracle.svm.hosted.c.CGlobalDataFeature, []
com.oracle.svm.hosted.c.function.CEntryPointSupport, []
com.oracle.svm.hosted.classinitialization.ClassInitializationFeature, []
com.oracle.svm.hosted.code.CEntryPointCallStubFeature, []
com.oracle.svm.hosted.code.CEntryPointLiteralFeature, []
com.oracle.svm.hosted.code.CFunctionLinkagesFeature, []
com.oracle.svm.hosted.code.CFunctionPointerCallStubSupportFeature, []
com.oracle.svm.hosted.code.FactoryMethodSupportFeature, []
com.oracle.svm.hosted.code.FrameInfoHostedMethodDataFeature, []
com.oracle.svm.hosted.code.RestrictHeapAccessCalleesFeature, []
com.oracle.svm.hosted.code.SubstrateCompilationDirectivesFeature, []
com.oracle.svm.hosted.code.SubstrateLIRBackendFeature, []
com.oracle.svm.hosted.code.UninterruptibleAnnotationCheckerFeature, []
com.oracle.svm.hosted.code.aarch64.AArch64HostedPatcherFeature, []
com.oracle.svm.hosted.code.aarch64.AArch64HostedTrampolineSupportFeature, []
com.oracle.svm.hosted.fieldfolding.StaticFinalFieldFoldingFeature, []
com.oracle.svm.hosted.heap.HeapDumpFeature, []
com.oracle.svm.hosted.heap.ImageHeapMapFeature, []
com.oracle.svm.hosted.heap.PodFeature, []
com.oracle.svm.hosted.image.DisallowedImageHeapObjectFeature, [com.oracle.svm.core.jdk.management.ManagementFeature]
com.oracle.svm.hosted.image.ImageHeapFillerObjectsFeature, []
com.oracle.svm.hosted.image.MethodPointerInvalidHandlerFeature, []
com.oracle.svm.hosted.image.StringInternFeature, []
com.oracle.svm.hosted.image.sources.SourceCacheFeature, []
com.oracle.svm.hosted.jdk.AccessControlContextReplacerFeature, []
com.oracle.svm.hosted.jdk.JDKInitializationFeature, []
com.oracle.svm.hosted.jdk.JDKRegistrations, []
com.oracle.svm.hosted.jdk.JNIRegistrationJava, []
com.oracle.svm.hosted.jdk.JNIRegistrationJavaNet, []
com.oracle.svm.hosted.jdk.JNIRegistrationJavaNio, []
com.oracle.svm.hosted.jdk.JNIRegistrationManagementExt, []
com.oracle.svm.hosted.jdk.JNIRegistrationPrefs, []
com.oracle.svm.hosted.jdk.JNIRegistrationSupport, []
com.oracle.svm.hosted.jdk.JNIRegistrationsJavaZip, []
com.oracle.svm.hosted.jdk.JRTFeature, []
com.oracle.svm.hosted.jdk.localization.CharsetSubstitutionsFeature, []
com.oracle.svm.hosted.jdk.localization.LocalizationFeature, []
com.oracle.svm.hosted.jdk17.JNIRegistrationSupport_JDK17OrLater, []
com.oracle.svm.hosted.jni.JNIAccessFeature, [com.oracle.svm.hosted.meta.KnownOffsetsFeature]
com.oracle.svm.hosted.jni.JNIAutomaticFeature, [com.oracle.svm.hosted.jni.JNIFeature]
com.oracle.svm.hosted.jni.JNICallWrapperFeature, [com.oracle.svm.hosted.jni.JNIAccessFeature]
com.oracle.svm.hosted.jni.JNIFeature, [com.oracle.svm.hosted.jni.JNIFunctionTablesFeature com.oracle.svm.hosted.jni.JNICallWrapperFeature com.oracle.svm.hosted.jni.JNILibraryLoadFeature]
com.oracle.svm.hosted.jni.JNIFunctionTablesFeature, [com.oracle.svm.hosted.jni.JNIAccessFeature]
com.oracle.svm.hosted.jni.JNILibraryLoadFeature, []
com.oracle.svm.hosted.lambda.StableLambdaProxyNameFeature, []
com.oracle.svm.hosted.meta.HostedMethodNameFactory, []
com.oracle.svm.hosted.meta.InvalidVTableEntryFeature, []
com.oracle.svm.hosted.meta.KnownOffsetsFeature, [com.oracle.svm.hosted.thread.VMThreadMTFeature]
com.oracle.svm.hosted.meta.MaterializedConstantFieldsFeature, []
com.oracle.svm.hosted.methodhandles.MethodHandleFeature, []
com.oracle.svm.hosted.option.RuntimeOptionFeature, []
com.oracle.svm.hosted.phases.EnumSwitchFeature, []
com.oracle.svm.hosted.reflect.ReflectionFeature, []
com.oracle.svm.hosted.reflect.ReflectionMetadataEncoderImplFactoryFeature, []
com.oracle.svm.hosted.reflect.proxy.DynamicProxyFeature, [com.oracle.svm.hosted.reflect.ReflectionFeature]
com.oracle.svm.hosted.reflect.serialize.SerializationFeature, [com.oracle.svm.hosted.reflect.ReflectionFeature com.oracle.svm.hosted.reflect.proxy.DynamicProxyFeature]
com.oracle.svm.hosted.snippets.ExceptionUnwindFeature, []
com.oracle.svm.hosted.snippets.ImplicitExceptionsFeature, []
com.oracle.svm.hosted.substitute.AutomaticSubstitutionFeature, []
com.oracle.svm.hosted.thread.CEntryPointFeature, [com.oracle.svm.hosted.thread.VMThreadMTFeature]
com.oracle.svm.hosted.thread.VMThreadMTFeature, []
com.oracle.svm.hosted.xml.JavaxXmlClassAndResourcesLoaderFeature, []
com.oracle.svm.truffle.TruffleJFRFeature, []
org.graalvm.home.HomeFinderFeature, []
```

</details>

**Comment by fniephaus** [comment]
Thanks for the error report, @Berstanio. We'll get this fixed. :)

**Comment by fniephaus** [comment]
I have fixed the NPE but then I realized:

> I don't know though, whether a missing `CCompilerInvoker` in itself is a bug.

It's often a bug. Are you sure you've [installed the dependencies](https://www.graalvm.org/latest/reference-manual/native-image/#prerequisites) for your system?

Please let me know if that fixes the problem on your end!

**Comment by Berstanio** [comment]
Hi,

thank you for fixing, I will test out the nightly build.

> It's often a bug. Are you sure you've [installed the dependencies](https://www.graalvm.org/latest/reference-manual/native-image/#prerequisites) for your system?

I looked in the source code and found, that this code is responsible for the missing CCompilerInvoker:
https://github.com/oracle/graal/blob/52d791068b5c34f37b48174500f437aca642f027/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/NativeImageGenerator.java#L941-L942
I use the parameter `ExitAfterRelocatableImage` and `UseCAPCache`.

**Comment by Berstanio** [comment]
> thank you for fixing, I will test out the nightly build.

I thought there was one, but now I don't find it. Do I need to build from source to test it?

**Comment by fniephaus** [comment]
> I use the parameter `ExitAfterRelocatableImageWrite` and `UseCAPCache`.

It seems these are non-API options, so what you're trying to do is not supported. I'm guessing you're trying to cross-compile? There are lots of issues around this topic, including https://github.com/oracle/graal/issues/407.

> I thought there was one, but now I don't find it. Do I need to build from source to test it?

You're looking for the [dev builds](https://github.com/graalvm/graalvm-ce-dev-builds/releases). Please note that they aren't necessarily updated every night. The last build is unfortunately from two weeks and we are still investigating what is blocking the updates.
If you want to test the fix out now, you can of course build from source. It should be relatively simple:

```bash
git clone https://github.com/oracle/graal.git
git clone https://github.com/graalvm/mx.git
cd graal/substratevm
../../mx/mx build # builds a slim GraalVM with native-image
../../mx/mx graalvm-home # prints the path to the GraalVM build you can use as JAVA_HOME
```

**Comment by Berstanio** [comment]
> It seems these are non-API options, so what you're trying to do is not supported. I'm guessing you're trying to cross-compile? There are lots of issues around this topic, including #407.

I'm using native-image for targetting iOS. This works fine (except the NPE in this issue). Since related PR's got merged, I would expect it to be at least indirectly supported (https://github.com/oracle/graal/pull/3340)? Or do I misunderstand what you mean by "so what you're trying to do is not supported."


> > I thought there was one, but now I don't find it. Do I need to build from source to test it?
> 
> You're looking for the [dev builds](https://github.com/graalvm/graalvm-ce-dev-builds/releases). Please note that they aren't necessarily updated every night. The last build is unfortunately from two weeks and we are still investigating what is blocking the updates. If you want to test the fix out now, you can of course build from source. It should be relatively simple:
> 
> ```shell
> git clone https://github.com/oracle/graal.git
> git clone https://github.com/graalvm/mx.git
> cd graal/substratevm
> ../../mx/mx build # builds a slim GraalVM with native-image
> ../../mx/mx graalvm-home # prints the path to the GraalVM build you can use as JAVA_HOME
> ```

The last time I tried to compile svm from source on a M1 mac, it gave me quite some headache. I think I'll wait for now, since I'm able to workaround this issue.

**Comment by fniephaus** [comment]
> This works fine (except the NPE in this issue). Since related PR's got merged, I would expect it to be at least indirectly supported (https://github.com/oracle/graal/pull/3340)? Or do I misunderstand what you mean by "so what you're trying to do is not supported."

If it works with the new patch, then you should be fine. I was referring to the fact that the flags you're using are non-API flags, and none of what they do is officially supported.

> The last time I tried to compile svm from source on a M1 mac, it gave me quite some headache. I think I'll wait for now, since I'm able to workaround this issue.

Ok, up to you. Dev builds tell you from what commit they're built, so you can check if the patch is included.
