### ISSUE TITLE
Reflective access to elements in reflect-config.json gives runtime exception

### ISSUE THREAD

**Issue by pompiuses** [oracle/graal#6877]
**Describe the issue**
First complete the steps below to build the native image. The following exception is thrown on native image startup (full stacktrace below):
```Exception in thread "main" java.lang.NoSuchMethodError: java.lang.Thread$Builder$OfVirtual.unstarted(java.lang.Runnable)```

The tracing agent has, seemingly correctly, added the following to ```reflect-config.json```, but to no effect:
```
{
  "name":"java.lang.Thread$Builder$OfVirtual",
  "methods":[{"name":"name","parameterTypes":["java.lang.String"] }, {"name":"unstarted","parameterTypes":["java.lang.Runnable"] }]
}
```

Why does the application fail on startup even though reflection metadata seemingly looks correct? Note that this is with preview enabled. The reflective call which fail is done by Javalin's [ConcurrencyUtil.kt](https://github.com/javalin/javalin/blob/master/javalin/src/main/java/io/javalin/util/ConcurrencyUtil.kt#L100).

**Steps to reproduce the issue**
1. Clone demo repo
  ```git clone https://github.com/pompiuses/graalvm-javalin-demo.git```
2. Build fat jar
  ```mvn clean package```
3. Start application with tracing agent
  ```java -agentlib:native-image-agent=config-output-dir=target/META-INF/native-image --enable-preview -jar target/graalvm-demo-1.0-SNAPSHOT-jar-with-dependencies.jar```
4. Then hit ```http://localhost:7070``` in your browser to trigger all execution paths for the tracing agent to pick up.
5. Stop the application.
6. Build native image
  ```native-image -jar target/graalvm-demo-1.0-SNAPSHOT-jar-with-dependencies.jar -H:ConfigurationFileDirectories=target/META-INF/native-image -o target/app --no-fallback --enable-preview```
7. Start native image
  ```./target/app```

**Describe GraalVM and your environment:**
 - GraalVM version: **Oracle GraalVM 20.0.1+9.1 (build 20.0.1+9-jvmci-23.0-b12)**
  - JDK major version: **20.0.1**
 - OS: **MacOS 13.4.1 Ventura**
 - Architecture: **Apple M1 Max**

**More details**
Full stacktrace:
```
Exception in thread "main" java.lang.NoSuchMethodError: java.lang.Thread$Builder$OfVirtual.unstarted(java.lang.Runnable)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.Util_java_lang_invoke_MethodHandleNatives.resolve(Target_java_lang_invoke_MethodHandleNatives.java:345)
	at java.base@20.0.1/java.lang.invoke.MethodHandleNatives.resolve(MethodHandleNatives.java:199)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.Util_java_lang_invoke_MethodHandle.invokeInternal(Target_java_lang_invoke_MethodHandle.java:137)
	at java.base@20.0.1/java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:76)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.MethodHandleIntrinsicImpl.execute(MethodHandleIntrinsicImpl.java:181)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.Util_java_lang_invoke_MethodHandle.invokeInternal(Target_java_lang_invoke_MethodHandle.java:142)
	at java.base@20.0.1/java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:76)
	at java.base@20.0.1/java.lang.invoke.LambdaForm$NamedFunction.invokeWithArguments(LambdaForm.java:96)
	at java.base@20.0.1/java.lang.invoke.LambdaForm.interpretName(LambdaForm.java:949)
	at java.base@20.0.1/java.lang.invoke.LambdaForm.interpretWithArguments(LambdaForm.java:926)
	at java.base@20.0.1/java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:82)
	at java.base@20.0.1/java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:0)
	at java.base@20.0.1/java.lang.invoke.Invokers$Holder.invoke_MT(Invokers$Holder)
	at io.javalin.util.ReflectiveVirtualThreadBuilder.unstarted(ConcurrencyUtil.kt:117)
	at io.javalin.util.NamedVirtualThreadFactory.newThread(ConcurrencyUtil.kt:91)
	at java.base@20.0.1/java.util.concurrent.ThreadPerTaskExecutor.newThread(ThreadPerTaskExecutor.java:219)
	at java.base@20.0.1/java.util.concurrent.ThreadPerTaskExecutor$ThreadBoundFuture.<init>(ThreadPerTaskExecutor.java:337)
	at java.base@20.0.1/java.util.concurrent.ThreadPerTaskExecutor.submit(ThreadPerTaskExecutor.java:285)
	at java.base@20.0.1/java.util.concurrent.ThreadPerTaskExecutor.submit(ThreadPerTaskExecutor.java:293)
	at io.javalin.util.LoomUtil$LoomThreadPool.execute(ConcurrencyUtil.kt:63)
	at org.eclipse.jetty.io.SelectorManager.execute(SelectorManager.java:139)
	at org.eclipse.jetty.io.ManagedSelector.doStart(ManagedSelector.java:119)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.io.SelectorManager.doStart(SelectorManager.java:239)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:367)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:75)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:228)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.server.Server.doStart(Server.java:428)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at io.javalin.jetty.JettyServer.start(JettyServer.kt:82)
	at io.javalin.Javalin.start(Javalin.java:171)
	at io.javalin.Javalin.start(Javalin.java:148)
	at demo.App.main(App.java:9)
```

**Comment by ossama-ismaili** [comment]
The issue appears to be non-reproducible. To troubleshoot, I recommend updating to the latest version of GraalVM, version 23. This update will ensure that you have the most recent security patches and fixes implemented.

**Comment by ossama-ismaili** [comment]
Issue not reproducible on GraalVM JDK17.
We are trying to reproduce it on GraalVM JDK20.

**Comment by ossama-ismaili** [comment]
Issue is reproducible on JDK20.
Thanks @pompiuses for reporting the issue.

**Comment by pompiuses** [comment]
Any ETA on this?

**Comment by saasvantage** [comment]
Issue is reproducible in JDK 21.

```
java -version

openjdk version "21" 2023-09-19
OpenJDK Runtime Environment GraalVM CE 21+35.1 (build 21+35-jvmci-23.1-b15)
OpenJDK 64-Bit Server VM GraalVM CE 21+35.1 (build 21+35-jvmci-23.1-b15, mixed mode, sharing)
```

```
Exception in thread "main" java.lang.NoSuchMethodError: java.lang.Thread$Builder$OfVirtual.unstarted(java.lang.Runnable)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.Util_java_lang_invoke_MethodHandleNatives.resolve(Target_java_lang_invoke_MethodHandleNatives.java:335)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.Util_java_lang_invoke_MethodHandle.invokeInternal(Target_java_lang_invoke_MethodHandle.java:181)
	at java.base@21/java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:98)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.MethodHandleIntrinsicImpl.execute(MethodHandleIntrinsicImpl.java:179)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.Util_java_lang_invoke_MethodHandle.invokeInternal(Target_java_lang_invoke_MethodHandle.java:186)
	at java.base@21/java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:98)
	at java.base@21/java.lang.invoke.LambdaForm$NamedFunction.invokeWithArguments(LambdaForm.java:96)
	at java.base@21/java.lang.invoke.LambdaForm.interpretName(LambdaForm.java:959)
	at java.base@21/java.lang.invoke.LambdaForm.interpretWithArguments(LambdaForm.java:936)
	at java.base@21/java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:105)
	at java.base@21/java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:0)
	at java.base@21/java.lang.invoke.Invokers$Holder.invoke_MT(Invokers$Holder)
	at io.javalin.util.ReflectiveVirtualThreadBuilder.unstarted(ConcurrencyUtil.kt:169)
	at io.javalin.util.NamedVirtualThreadFactory.newThread(ConcurrencyUtil.kt:143)
	at java.base@21/java.util.concurrent.ThreadPerTaskExecutor.newThread(ThreadPerTaskExecutor.java:219)
	at java.base@21/java.util.concurrent.ThreadPerTaskExecutor$ThreadBoundFuture.<init>(ThreadPerTaskExecutor.java:336)
	at java.base@21/java.util.concurrent.ThreadPerTaskExecutor.submit(ThreadPerTaskExecutor.java:285)
	at java.base@21/java.util.concurrent.ThreadPerTaskExecutor.submit(ThreadPerTaskExecutor.java:293)

```

**Comment by ratacolita** [comment]
I still get this error on JDK 23, using the new reachability-metadata.json configuration format.

```
17:45:52.948 [main] ERROR br.com.comolatti.Program - Uncaught exception in thread: main
java.lang.NoSuchMethodError: java.lang.Thread$Builder$OfVirtual.unstarted(java.lang.Runnable)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.Util_java_lang_invoke_MethodHandleNatives.resolve(Target_java_lang_invoke_MethodHandleNatives.java:352)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.Util_java_lang_invoke_MethodHandle.invokeInternal(Target_java_lang_invoke_MethodHandle.java:181)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.Util_java_lang_invoke_MethodHandle.linkTo(Target_java_lang_invoke_MethodHandle.java:171)
        at java.base@23.0.1/java.lang.invoke.MethodHandle.linkToInterface(MethodHandle.java:137)
        at java.base@23.0.1/java.lang.invoke.MethodHandle.linkToInterface(MethodHandle.java:0)
        at java.base@23.0.1/java.lang.invoke.LambdaForm$DMH/s885f8cca.invokeInterface(LambdaForm$DMH)
        at io.javalin.util.ReflectiveVirtualThreadBuilder.unstarted(ConcurrencyUtil.kt:159)
        at io.javalin.util.NamedVirtualThreadFactory.newThread(ConcurrencyUtil.kt:133)
        at java.base@23.0.1/java.util.concurrent.ThreadPerTaskExecutor.newThread(ThreadPerTaskExecutor.java:219)
        at java.base@23.0.1/java.util.concurrent.ThreadPerTaskExecutor$ThreadBoundFuture.<init>(ThreadPerTaskExecutor.java:336)
        at java.base@23.0.1/java.util.concurrent.ThreadPerTaskExecutor.submit(ThreadPerTaskExecutor.java:285)
        at java.base@23.0.1/java.util.concurrent.ThreadPerTaskExecutor.submit(ThreadPerTaskExecutor.java:293)
        at io.javalin.util.LoomUtil$LoomThreadPool.execute(ConcurrencyUtil.kt:62)
        at org.eclipse.jetty.io.SelectorManager.execute(SelectorManager.java:139)
        at org.eclipse.jetty.io.ManagedSelector.doStart(ManagedSelector.java:119)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
        at org.eclipse.jetty.io.SelectorManager.doStart(SelectorManager.java:256)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:367)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:75)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:228)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
        at org.eclipse.jetty.server.Server.doStart(Server.java:428)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
        at io.javalin.jetty.JettyServer.start(JettyServer.kt:93)
        at io.javalin.Javalin.start(Javalin.java:123)
        at br.com.comolatti.Program.main(Program.java:42)
        at java.base@23.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```

**Comment by loicottet** [comment]
This issue is a combination of two issues. The first one is a bug in the Native Image agent when tracing method handles. Reflection registration in the Native Image builder relies on the visibility rules of the reflection API. As such, `Thread$Builder$OfVirtual` doesn't see `unstarted` as it is a package-private method defined in the superclass `Thread$Builder`. On the other hand, `MethodHandles.Lookup.findVirtual(OfVirtual.class, "unstarted", ...)` will locate the method just fine.

The second issue is that our implementation of the method handles lookup doesn't consider interfaces when it can't find a method in the lookup type or its superclasses.

I will update the Native Image agent to register the actual declaring class instead of the queried class on method handle lookups, and fix the method handle resolution implementation to take interfaces into account.

**Comment by loicottet** [comment]
Fixed by https://github.com/oracle/graal/pull/12622
