### ISSUE TITLE
Unable to use AWT for 2D drawing

### ISSUE THREAD

**Issue by wssy001** [oracle/graal#6918]
Describe the issue

When I use GraalVM 22.3.1, I can use AWT for 2D drawing, but after I upgrade to GraalVM 23.0.01, I can't do it

Steps to reproduce the issue
Please include both build steps as well as run steps

the test project is [here](https://github.com/wssy001/awt-test)

- run `mvn clean native:compile -Pnative -Dmaven.test.skip=true` to build a native image

- run `./target/awt-test `

GraalVM version: GraalVM CE 20.0.1+9.1 (build 20.0.1+9-jvmci-23.0-b12)
JDK major version: 20
OS: Ubuntu 20.04
Architecture: arm64

log:
```shell
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.1.1)

2023-07-02T14:36:27.512+08:00  INFO 39483 --- [           main] com.example.awttest.AwtTestApplication   : Starting AOT-processed AwtTestApplication using Java 20.0.1 with PID 39483 (/root/awt-test/target/awt-test started by root in /root/awt-test)
2023-07-02T14:36:27.513+08:00  INFO 39483 --- [           main] com.example.awttest.AwtTestApplication   : No active profile set, falling back to 1 default profile: "default"
2023-07-02T14:36:27.522+08:00  INFO 39483 --- [           main] com.example.awttest.AwtTestApplication   : Started AwtTestApplication in 0.143 seconds (process running for 0.183)
Exception in thread "main" java.lang.Error: java.home property not set
        at java.desktop@20.0.1/sun.awt.FontConfiguration.findFontConfigFile(FontConfiguration.java:180)
        at java.desktop@20.0.1/sun.awt.FontConfiguration.<init>(FontConfiguration.java:97)
        at java.desktop@20.0.1/sun.font.MFontConfiguration.<init>(MFontConfiguration.java:48)
        at java.desktop@20.0.1/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:688)
        at java.desktop@20.0.1/sun.font.SunFontManager$2.run(SunFontManager.java:352)
        at java.desktop@20.0.1/sun.font.SunFontManager$2.run(SunFontManager.java:309)
        at java.base@20.0.1/java.security.AccessController.executePrivileged(AccessController.java:171)
        at java.base@20.0.1/java.security.AccessController.doPrivileged(AccessController.java:319)
        at java.desktop@20.0.1/sun.font.SunFontManager.<init>(SunFontManager.java:309)
        at java.desktop@20.0.1/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
        at java.desktop@20.0.1/sun.awt.X11FontManager.<init>(X11FontManager.java:55)
        at java.desktop@20.0.1/sun.font.PlatformFontInfo.createFontManager(PlatformFontInfo.java:37)
        at java.desktop@20.0.1/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:51)
        at java.desktop@20.0.1/java.awt.Font.getFont2D(Font.java:526)
        at java.desktop@20.0.1/java.awt.Font.defaultLineMetrics(Font.java:2394)
        at java.desktop@20.0.1/java.awt.Font.getLineMetrics(Font.java:2501)
        at java.desktop@20.0.1/java.awt.font.TextLayout.fastInit(TextLayout.java:597)
        at java.desktop@20.0.1/java.awt.font.TextLayout.<init>(TextLayout.java:392)
        at java.desktop@20.0.1/sun.java2d.SunGraphics2D.drawString(SunGraphics2D.java:2926)
        at com.example.awttest.AwtTestApplication.main(AwtTestApplication.java:47)
```

**Comment by SergejIsbrecht** [comment]
You probably need to start the native-image with `-DjavaHome=...` to a Java-directory (e.g. GraalVM CE). It might be set to something wrong, if you set `-Dsun.awt.fontconfig=..` properly.

```
    private void findFontConfigFile() {

        foundOsSpecificFile = true; // default assumption.
        String javaHome = System.getProperty("java.home");
        if (javaHome == null) {
            throw new Error("java.home property not set");
        }
        javaLib = javaHome + File.separator + "lib";
        String userConfigFile = System.getProperty("sun.awt.fontconfig");
        if (userConfigFile != null) {
            fontConfigFile = new File(userConfigFile);
        } else {
            fontConfigFile = findFontConfigFile(javaLib);
        }
    }
```

```
    private File findFontConfigFile(String javaLib) {
        String baseName = javaLib + File.separator + "fontconfig";
        File configFile;
        String osMajorVersion = null;
        if (osVersion != null && osName != null) {
            configFile = findImpl(baseName + "." + osName + "." + osVersion);
            if (configFile != null) {
                return configFile;
            }
            int decimalPointIndex = osVersion.indexOf(".");
            if (decimalPointIndex != -1) {
                osMajorVersion = osVersion.substring(0, osVersion.indexOf("."));
                configFile = findImpl(baseName + "." + osName + "." + osMajorVersion);
                if (configFile != null) {
                    return configFile;
                }
            }
        }
        if (osName != null) {
            configFile = findImpl(baseName + "." + osName);
            if (configFile != null) {
                return configFile;
            }
        }
        if (osVersion != null) {
            configFile = findImpl(baseName + "." + osVersion);
            if (configFile != null) {
                return configFile;
            }
            if (osMajorVersion != null) {
                configFile = findImpl(baseName + "." + osMajorVersion);
                if (configFile != null) {
                    return configFile;
                }
            }
        }
        foundOsSpecificFile = false;

        configFile = findImpl(baseName);
        if (configFile != null) {
            return configFile;
        }
        return null;
    }
```

**Comment by fniephaus** [comment]
22.3.1 did not support JDK 20, and AWT internals might have changed from JDK 17/19 to JDK 20. Have you tried regenerating reachability metadata using the [tracing agent](https://www.graalvm.org/latest/reference-manual/native-image/guides/configure-with-tracing-agent/)?

**Comment by wssy001** [comment]
> 22.3.1 did not support JDK 20, and AWT internals might have changed from JDK 17/19 to JDK 20. Have you tried regenerating reachability metadata using the [tracing agent](https://www.graalvm.org/latest/reference-manual/native-image/guides/configure-with-tracing-agent/)?
@fniephaus 
1: I know 22.3.1 not support JDK 20. What I want to say is that the same Java code can run in GraalVM version 22.3.1 well
2: I do use the `tracing agent` and collect a file named `[jni-config.json](https://github.com/wssy001/awt-test/blob/master/src/main/resources/jni-config.json)`. that`s why I can  use AWT for 2D drawing in old GraalVM version

**Comment by wssy001** [comment]
finally, I give up. Guys you would rather use <code>[javacv](https://github.com/bytedeco/javacv)</code>than use AWT
