### ISSUE TITLE
Native-image failed to handle java2d classes

### ISSUE THREAD

**Issue by plankp** [oracle/graal#697]
Take a very simple GUI app:

```java
import javax.swing.JFrame;

public class DummyClass {
    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.setSize(100, 100);
        frame.setResizable(false);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
    }
}
```

After compiling it with `javac` and making sure it runs, running `native-image` on it results in the following error:

![image](https://user-images.githubusercontent.com/7527421/46205951-7ffc9780-c2f0-11e8-8b7b-07b5541a2f8b.png)

Adding the flags `--delay-class-initialization-to-runtime` on `DummyClass` still results in the same error and apply it on `sun.java2d.opengl.OGLRenderQueue` results in the following:

![image](https://user-images.githubusercontent.com/7527421/46206159-221c7f80-c2f1-11e8-9f49-6a72a29b171e.png)

--------

Is using `native-image` on swing not supported?
Or what is the workaround for this?
(Or am I misunderstanding how `native-image` works? I am using debian 9.5.0)

**Comment by chumer** [comment]
Swing requires AWT and that is not yet supported by `native-image`. It does not mean it is not possible but it is not trivial to support.

**Comment by alexzorin** [comment]
@chumer thanks for answering all these native-image questions, it's really helpful when exploring. Would you be able to comment on how deep the issue runs with AWT? I'm having a go at building a simple [Apache FOP](https://xmlgraphics.apache.org/fop/) PDF transformation and see:

```
error: unsupported features in 2 methods
Detailed message:
Error: Detected a FileDescriptor in the image heap. File descriptors opened during image generation are no longer open at image run time, and the files might not even be present anymore at image run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option --delay-class-initialization-to-runtime=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace:  object java.io.RandomAccessFile
        object sun.nio.ch.FileChannelImpl
        object sun.font.TrueTypeFont$TTDisposerRecord
        object java.util.Hashtable$Entry
        object java.util.Hashtable$Entry[]
        object java.util.Hashtable
        method sun.java2d.Disposer.run()
Call path from entry point to sun.java2d.Disposer.run():
        at sun.java2d.Disposer.run(Disposer.java:148)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:142)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:87)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:155)
        at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Error: Detected a FileDescriptor in the image heap. File descriptors opened during image generation are no longer open at image run time, and the files might not even be present anymore at image run time. The object was probably created by a class initializer and is reachable from a static field. By default, all class initialization is done during native image building.You can manually delay class initialization to image run time by using the option --delay-class-initialization-to-runtime=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace:  object sun.nio.ch.FileChannelImpl
        object sun.font.TrueTypeFont$TTDisposerRecord
        object java.util.Hashtable$Entry
        object java.util.Hashtable$Entry[]
        object java.util.Hashtable
        method sun.java2d.Disposer.run()
Call path from entry point to sun.java2d.Disposer.run():
        at sun.java2d.Disposer.run(Disposer.java:148)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:142)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:87)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:155)
        at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
```

From playing in jdb, this seems to be related to loading of fonts and ICC color profiles (though not in `<clinit>`).

Is this likely to be the same issue with AWT/java2d support? IOW, something that would need to be addressed in Graal runtime rather than something that could reasonably be worked-around by modifying FOP?

**Comment by jdevp** [comment]
It would be very nice to see that native-image support will support Swing/Java2D, which will bring Java on client to the next level.

**Comment by spavlusieva** [comment]
hi @plankp , this issue has been inactive for more than 180 days. We’ll close it to focus on current issues. In case it’s still relevant, please reopen it and we’ll take another look. Thank you!

**Comment by vjovanov** [comment]
This issue is likely fixed in the latest release.
