### ISSUE TITLE
Native Image creation throws Fatal Error

### ISSUE THREAD

**Issue by MaxiLambda** [oracle/graal#6970]
**Describe the issue**
Compiling a project containing the com.sap.conn.jco.sapjco3-3.1.6.0.jar fails with fatal error.  This error ocurs in the newsest verison 23.0.0 CE (and 22.3.2 EE) but not on version 22.3.2 CE.  
At the moment i can't give a minimal example.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
2. **[e.g.: mvn -Pnative -DskipTests package]**

**Describe GraalVM and your environment:**
 - GraalVM version: **23.0.0 CE**
 - JDK major version: **17**
 - OS: **Windows (some Problem on WSL2 Ubuntu)**
 - Architecture: **[x64]**

**More details**

the path to the project has been replaced with <PATH>
the path to the userhome has been replaced with <USERHOME>
**native-image** Arguments:
```
-cp
<PATH>\\target\\rewind-jco-test-1.0-SNAPSHOT.jar;<USERHOME>\\.m2\\repository\\org\\latencyutils\\LatencyUtils\\2.0.3\\LatencyUtils-2.0.3.jar;<USERHOME>\\.m2\\repository\\com\\example\\cloud\\sapjco3\\sapjco3-dll\\3.1.6.0\\sapjco3-dll-3.1.6.0.jar;<USERHOME>\\.m2\\repository\\com\\google\\code\\findbugs\\jsr305\\3.0.2\\jsr305-3.0.2.jar;<USERHOME>\\.m2\\repository\\com\\example\\cloud\\rewind\\rewind-core\\8.0.0\\rewind-core-8.0.0.jar;<USERHOME>\\.m2\\repository\\org\\hdrhistogram\\HdrHistogram\\2.1.12\\HdrHistogram-2.1.12.jar;<USERHOME>\\.m2\\repository\\com\\example\\cloud\\sapjco3\\com.sap.conn.jco.sapjco3\\3.1.6.0\\com.sap.conn.jco.sapjco3-3.1.6.0.jar;<USERHOME>\\.m2\\repository\\com\\example\\cloud\\sapjco3\\sapjco3-all\\3.1.6.0\\sapjco3-all-3.1.6.0.jar;<USERHOME>\\.m2\\repository\\com\\github\\spotbugs\\spotbugs-annotations\\4.0.0-beta2\\spotbugs-annotations-4.0.0-beta2.jar;<USERHOME>\\.m2\\repository\\org\\apache\\commons\\commons-lang3\\3.9\\commons-lang3-3.9.jar;<USERHOME>\\.m2\\repository\\com\\example\\cloud\\rewind\\rewind-jco\\8.0.0\\rewind-jco-8.0.0.jar;<USERHOME>\\.m2\\repository\\org\\slf4j\\slf4j-api\\1.7.29\\slf4j-api-1.7.29.jar;<USERHOME>\\.m2\\repository\\io\\micrometer\\micrometer-core\\1.7.3\\micrometer-core-1.7.3.jar
--no-fallback
--verbose
-Ob
-H:Path=<PATH>\\target
-H:Name=rewind-jco-test
-H:Class=com.example.Main
--native-image-info
-H:ConfigurationFileDirectories=<PATH>\\target\\native\\agent-output\\main
-H:+AllowIncompleteClasspath
-H:ConfigurationFileDirectories=<PATH>\\target\\native\\agent-output\\main
-H:+AllowIncompleteClasspath

```

```
Apply jar:file:///<USERHOME>/.m2/repository/io/micrometer/micrometer-core/1.7.3/micrometer-core-1.7.3.jar!/META-INF/native-image/io.micrometer/micrometer-core/native-image.properties
Apply jar:file:///<USERHOME>/.m2/repository/io/micrometer/micrometer-core/1.7.3/micrometer-core-1.7.3.jar!/META-INF/native-image/io.micrometer/micrometer-core/reflect-config.json
Apply jar:file:///<USERHOME>/.jdks/graalvm-jdk-17.0.7+8.1/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/thirdparty/native-image.properties
Apply jar:file:///<USERHOME>/.jdks/graalvm-jdk-17.0.7+8.1/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/polyglot/native-image.properties
Executing [
'INCLUDE=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\ATLMFC\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt' \
'LIB=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\ATLMFC\lib\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\lib\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22000.0\\um\x64' \
'Path=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\VCPackages;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\bin\Roslyn;C:\Program Files\Microsoft Visual Studio\2022\Community\Team Tools\Performance Tools\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\\x64;C:\Program Files (x86)\Windows Kits\10\bin\\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\\MSBuild\Current\Bin\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\;C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.16.10261.0_x64__8wekyb3d8bbwe;<USERHOME>\.jdks\jdk8u372-b07-jre\bin;<USERHOME>\.jdks\jdk8u372-b07-jre\bin;C:\Program Files\BellSoft\LibericaJRE-17\bin\;C:\Program Files\Zulu\zulu\bin\;C:\Program Files\Zulu\zulu-8\bin\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.9.2\bin;C:\ProgramData\nvm;C:\Program Files\nodejs;<USERHOME>\.jdks\graalvm-jdk-17.0.7+8.1\bin;<USERHOME>\.jdks\jdk8u372-b07-jre\bin;<USERHOME>\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\IntelliJ IDEA 2023.1.2\bin;;C:\Program Files\Git\usr\bin;C:\ProgramData\nvm;C:\Program Files\nodejs;;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\Linux\bin\ConnectionManagerExe;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg' \
'TEMP=<USERHOME>\AppData\Local\Temp' \
USE_NATIVE_IMAGE_JAVA_PLATFORM_MODULE_SYSTEM=true \
'<USERHOME>\.jdks\graalvm-jdk-17.0.7+8.1\bin\java.exe' \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
--add-exports=java.base/com.sun.crypto.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.access.foreign=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.event=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.loader=org.graalvm.nativeimage.builder,org.graalvm.truffle \
--add-exports=java.base/jdk.internal.logger=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.misc=com.oracle.svm.svm_enterprise,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile,org.graalvm.nativeimage.pointsto \
--add-exports=java.base/jdk.internal.misc=com.oracle.svm.svm_enterprise,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile,org.graalvm.nativeimage.pointsto \
--add-exports=java.base/jdk.internal.module=jdk.internal.vm.compiler,org.graalvm.nativeimage.base,org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.org.objectweb.asm=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.perf=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.platform=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.ref=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=java.base/jdk.internal.reflect=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.util=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.vm.annotation=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.vm=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.invoke.util=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.net=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.nio.ch=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=java.base/sun.reflect.annotation=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.factory=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.reflectiveObjects=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.repository=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.scope=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.tree=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.jca=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.ssl=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.util=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.x509=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.text.spi=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.calendar=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.cldr=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.locale.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.locale=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.resources=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util=org.graalvm.nativeimage.builder \
--add-exports=java.management.rmi/com.sun.jmx.remote.internal.rmi=org.graalvm.nativeimage.builder \
--add-exports=java.management.rmi/com.sun.jmx.remote.protocol.rmi=org.graalvm.nativeimage.builder \
--add-exports=java.management/com.sun.jmx.mbeanserver=org.graalvm.nativeimage.builder \
--add-exports=java.management/sun.management=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=java.rmi/sun.rmi.server=org.graalvm.nativeimage.builder \
--add-exports=java.xml.crypto/org.jcp.xml.dsig.internal.dom=org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.aarch64=com.oracle.graal.graal_enterprise,com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.amd64=com.oracle.graal.graal_enterprise,com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.site=com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.stack=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=com.oracle.graal.graal_enterprise,com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.common=com.oracle.graal.graal_enterprise,com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.aarch64=jdk.internal.vm.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.amd64=jdk.internal.vm.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot=com.oracle.graal.graal_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.meta=com.oracle.graal.graal_enterprise,com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.base,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.runtime=com.oracle.graal.graal_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.services=com.oracle.graal.graal_enterprise,com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.events=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal.handlers=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal.jfc=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal=org.graalvm.nativeimage.builder \
--add-exports=jdk.management.agent/jdk.internal.agent=org.graalvm.nativeimage.builder \
--add-exports=jdk.management/com.sun.management.internal=org.graalvm.nativeimage.builder \
--add-exports=org.graalvm.truffle/com.oracle.truffle.api.object=com.oracle.graal.graal_enterprise \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-XX:MaxRAMPercentage=36.046990097326194 \
-XX:GCTimeRatio=19 \
-XX:+ExitOnOutOfMemoryError \
-Djava.awt.headless=true \
'-Dorg.graalvm.vendor=Oracle Corporation' \
-Dorg.graalvm.vendorurl=https://www.graalvm.org/ \
'-Dorg.graalvm.vendorversion=Oracle GraalVM 17.0.7+8.1' \
-Dorg.graalvm.version=23.0.0 \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
--add-modules=ALL-DEFAULT \
--module-path \
'<USERHOME>\.jdks\graalvm-jdk-17.0.7+8.1\lib\truffle\truffle-api.jar;<USERHOME>\.jdks\graalvm-jdk-17.0.7+8.1\lib\svm\builder\native-image-base.jar;<USERHOME>\.jdks\graalvm-jdk-17.0.7+8.1\lib\svm\builder\objectfile.jar;<USERHOME>\.jdks\graalvm-jdk-17.0.7+8.1\lib\svm\builder\pointsto.jar;<USERHOME>\.jdks\graalvm-jdk-17.0.7+8.1\lib\svm\builder\svm-enterprise.jar;<USERHOME>\.jdks\graalvm-jdk-17.0.7+8.1\lib\svm\builder\svm.jar' \
--module \
org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner \
-imagecp \
'<PATH>\target\rewind-jco-test-1.0-SNAPSHOT.jar;<USERHOME>\.m2\repository\org\latencyutils\LatencyUtils\2.0.3\LatencyUtils-2.0.3.jar;<USERHOME>\.m2\repository\com\example\cloud\sapjco3\sapjco3-dll\3.1.6.0\sapjco3-dll-3.1.6.0.jar;<USERHOME>\.m2\repository\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar;<USERHOME>\.m2\repository\com\example\cloud\rewind\rewind-core\8.0.0\rewind-core-8.0.0.jar;<USERHOME>\.m2\repository\org\hdrhistogram\HdrHistogram\2.1.12\HdrHistogram-2.1.12.jar;<USERHOME>\.m2\repository\com\example\cloud\sapjco3\com.sap.conn.jco.sapjco3\3.1.6.0\com.sap.conn.jco.sapjco3-3.1.6.0.jar;<USERHOME>\.m2\repository\com\example\cloud\sapjco3\sapjco3-all\3.1.6.0\sapjco3-all-3.1.6.0.jar;<USERHOME>\.m2\repository\com\github\spotbugs\spotbugs-annotations\4.0.0-beta2\spotbugs-annotations-4.0.0-beta2.jar;<USERHOME>\.m2\repository\org\apache\commons\commons-lang3\3.9\commons-lang3-3.9.jar;<USERHOME>\.m2\repository\com\example\cloud\rewind\rewind-jco\8.0.0\rewind-jco-8.0.0.jar;<USERHOME>\.m2\repository\org\slf4j\slf4j-api\1.7.29\slf4j-api-1.7.29.jar;<USERHOME>\.m2\repository\io\micrometer\micrometer-core\1.7.3\micrometer-core-1.7.3.jar' \
-imagemp \
'<USERHOME>\.jdks\graalvm-jdk-17.0.7+8.1\lib\svm\graal-microservices.jar;<USERHOME>\.jdks\graalvm-jdk-17.0.7+8.1\lib\svm\library-support.jar' \
'-H:CLibraryPath=<USERHOME>\.jdks\graalvm-jdk-17.0.7+8.1\lib\svm\clibraries\windows-amd64' \
'-H:Path=<PATH>' \
'-H:ReflectionConfigurationResources@jar:file:///<USERHOME>/.m2/repository/io/micrometer/micrometer-core/1.7.3/micrometer-core-1.7.3.jar!/META-INF/native-image/io.micrometer/micrometer-core/native-image.properties=META-INF/native-image/io.micrometer/micrometer-core/reflect-config.json' \
'-H:ReflectionConfigurationResources@jar:file:///<USERHOME>/.m2/repository/io/micrometer/micrometer-core/1.7.3/micrometer-core-1.7.3.jar!/META-INF/native-image/io.micrometer/micrometer-core/reflect-config.json=META-INF/native-image/io.micrometer/micrometer-core/reflect-config.json' \
'-H:FallbackThreshold@argfile:target\tmp\native-image-6698708801237369300.args=0' \
'-H:Optimize@argfile:target\tmp\native-image-6698708801237369300.args=b' \
'-H:Path@argfile:target\tmp\native-image-6698708801237369300.args=<PATH>\\target' \
'-H:Name@argfile:target\tmp\native-image-6698708801237369300.args=rewind-jco-test' \
'-H:Class@argfile:target\tmp\native-image-6698708801237369300.args=com.example.Main' \
'-H:+DumpTargetInfo@argfile:target\tmp\native-image-6698708801237369300.args' \
'-H:ConfigurationFileDirectories@argfile:target\tmp\native-image-6698708801237369300.args=<PATH>\target\native\agent-output\main' \
'-H:+AllowIncompleteClasspath@argfile:target\tmp\native-image-6698708801237369300.args' \
'-H:ConfigurationFileDirectories@argfile:target\tmp\native-image-6698708801237369300.args=<PATH>\target\native\agent-output\main' \
'-H:+AllowIncompleteClasspath@argfile:target\tmp\native-image-6698708801237369300.args' \
'-H:Features@jar:file:///<USERHOME>/.jdks/graalvm-jdk-17.0.7+8.1/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/thirdparty/native-image.properties=com.oracle.svm.thirdparty.gson.GsonFeature' \
'-H:Features@jar:file:///<USERHOME>/.jdks/graalvm-jdk-17.0.7+8.1/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/polyglot/native-image.properties=com.oracle.svm.polyglot.groovy.GroovyIndyInterfaceFeature,com.oracle.svm.polyglot.scala.ScalaFeature'
]
========================================================================================================================
GraalVM Native Image: Generating 'rewind-jco-test' (executable)...
========================================================================================================================
[1/8] Initializing...                                                                                   (11,4s @ 0,18GB)
 Java version: 17.0.7+8-LTS, vendor version: Oracle GraalVM 17.0.7+8.1
 Graal compiler: optimization level: b, target machine: x86-64-v3, PGO: off
 C compiler: cl.exe (microsoft, x64, 19.36.32534)
 Garbage collector: Serial GC (max heap size: 80% of RAM)
# Printing compilation-target information to: <PATH>\target\reports\target_info_20230703_120037.txt
# Printing native-library information to: <PATH>\target\reports\native_library_info_20230703_120058.txt
[2/8] Performing analysis...  [*****]                                                                   (21,8s @ 0,68GB)
   6.628 (84,72%) of  7.823 types reachable
   9.792 (57,28%) of 17.094 fields reachable
  36.249 (58,10%) of 62.395 methods reachable
   2.101 types,    95 fields, and 1.589 methods registered for reflection
      79 types,    70 fields, and    67 methods registered for JNI access
       4 native libraries: crypt32, ncrypt, version, winhttp
[3/8] Building universe...                                                                               (4,1s @ 0,76GB)
[4/8] Parsing methods...      [**]                                                                       (3,5s @ 1,05GB)
[5/8] Inlining methods...     [***]                                                                      (1,5s @ 1,05GB)
[6/8] Compiling methods...    [***]                                                                      (8,0s @ 1,23GB)

Fatal error: org.graalvm.compiler.debug.GraalError: failed guarantee: 358|SubstrateMethodCallTarget earliest block B12 (174|Begin) does not dominate latest block B28 (314|Merge)
        at method: void com.sap.i18n.cp.ConverterJNI.<clinit>()  [entry point]
        at jdk.internal.vm.compiler/org.graalvm.compiler.debug.GraalError.guarantee(GraalError.java:168)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.schedule.SchedulePhase$Instance.checkLatestEarliestRelation(SchedulePhase.java:336)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.schedule.SchedulePhase$Instance.selectLatestBlock(SchedulePhase.java:320)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.schedule.SchedulePhase$Instance.calcLatestBlock(SchedulePhase.java:626)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.schedule.SchedulePhase$Instance.calcLatestBlocks(SchedulePhase.java:306)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.schedule.SchedulePhase$Instance.run(SchedulePhase.java:237)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.schedule.SchedulePhase.run(SchedulePhase.java:170)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.schedule.SchedulePhase.run(SchedulePhase.java:96)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:434)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:322)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.lower(LoweringPhase.java:270)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:256)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:108)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:434)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:322)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.phases.BaseTier.run(BaseTier.java:47)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:434)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:322)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:290)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:169)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:137)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:1278)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:1226)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:300)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:187)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:171)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this issue, it would be very helpful to provide a small reproducer for this

**Comment by MaxiLambda** [comment]
I am trying to create a reproducer but so far i was not able to do so

**Comment by oubidar-Abderrahim** [comment]
Unfortunately, the stacktrace alone won't be enough to debug and identify the issue here. 
For now, I will close this issue, if you manage to create a small reproducer to it, please feel free to reopen this ticket or create a new one with the reproducer attached, then we can take a look into it. Thank you.
