### ISSUE TITLE
Exception "java.lang.IllegalArgumentException: A language with id 'js' is not installed" in OSGI karaf environment

### ISSUE THREAD

**Issue by mashrafi29** [oracle/graal#6977]
Using GraalVM version 22.0.0 in OSGI environment as part of a Java program gets the following exception:
**java.lang.IllegalArgumentException: A language with id 'js' is not installed. Installed languages are: []**

Here is my code:

`try {
       tl = ThreadLocal.withInitial(() -> {

        /**
         * Get the Context reference.
         * 
         * @return - Context reference
         */
        return Context.newBuilder()
            .allowExperimentalOptions(true)
            .engine(mEngine)
            .allowNativeAccess(true)
            .allowIO(true)
            .allowHostClassLoading(true)
            .allowCreateThread(true)
            .allowHostAccess(HostAccess.ALL)
            .allowHostClassLookup(s -> true)
            .build();
      });

      //
      // Get the context.
      //
      Context cx = tl.get();
      Value value = cx.getBindings("js");`

Where mEngine is set as follows:

`mEngine = Engine.newBuilder("js").allowExperimentalOptions(true).build();`

Line '**Value value = cx.getBindings("js");**" is throwing the exception.

 - GraalVM version (Maven Version 22.0.0), 
 - JDK major version: **[8]**
 - OS: **[ubuntu]**
 - Architecture: **[AMD64]**

**More details**
Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
    2023-07-11T17:18:32,333 | ERROR | Thread-39        | TransformAPI                     | 70 - com.instana.cdc-transformapi-provider - 1.0.0 | transformRow | An error occurred while tranforming row - java.lang.IllegalArgumentException: A language with id 'js' is not installed. Installed languages are: []. - SAP_T_System - SAP_T_System_HeaderToItem_results_ItemToMatrics_results -\n{Category=PERFORM, Event_Names=Number of Tables not Fully Replicated, SRC=noreply@mydomain.com, Rating=0, Event_name=Performance, Unit=, Timestamp=0, Name=S4H~ABAP, ObjectType=, Period_unit=S, YellowtoRed=0, Contextid=000C2942890F1EE8A1A011DF70C84B25, indexKey=
java.lang.IllegalArgumentException: A language with id 'js' is not installed. Installed languages are: [].
	at com.oracle.truffle.polyglot.PolyglotEngineException.illegalArgument(PolyglotEngineException.java:125) ~[!/:?]
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.throwNotInstalled(PolyglotEngineImpl.java:1103) ~[!/:?]
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.requirePublicLanguage(PolyglotEngineImpl.java:1110) ~[!/:?]
	at com.oracle.truffle.polyglot.PolyglotContextImpl.requirePublicLanguage(PolyglotContextImpl.java:1317) ~[!/:?]
	at com.oracle.truffle.polyglot.PolyglotContextImpl.lookupLanguageContext(PolyglotContextImpl.java:1279) ~[!/:?]
	at com.oracle.truffle.polyglot.PolyglotContextImpl.getBindings(PolyglotContextImpl.java:1038) ~[!/:?]
	at com.oracle.truffle.polyglot.PolyglotContextDispatch.getBindings(PolyglotContextDispatch.java:98) ~[!/:?]
	at org.graalvm.polyglot.Context.getBindings(Context.java:560) ~[!/:?]
	at com.instana.cdc.transformapi.provider.MethodManager.execute(MethodManager.java:138) ~[?:?]
	at com.instana.cdc.transformapi.provider.TransformAPI.runVirtualColumnFunction(TransformAPI.java:1886) ~[?:?]

```

**Comment by oubidar-Abderrahim** [comment]
GraalVM 22.0.0 is an outdated version of GraalVM, please always use the latest version
The error's stacktrace is clear, you do not have 'js' installed. please use `gu install js` to resolve the issue
