### ISSUE TITLE
try / catch leads to PermanentBailoutException: Loop formed by an exception handler

### ISSUE THREAD

**Issue by graemerocher** [oracle/graal#698]
Steps to reproduce:

* `git clone https://github.com/graemerocher/micronaut-graal-experiments.git`
* cd `app-with-discovery`
* `./build-native-image.sh`

Exception:

```
Error: Loop formed by an exception handler
Call path from entry point to io.micronaut.discovery.eureka.$EurekaConfiguration$EurekaRegistrationConfigurationDefinition.injectBean(BeanResolutionContext, BeanContext, Object): 
	at io.micronaut.discovery.eureka.$EurekaConfiguration$EurekaRegistrationConfigurationDefinition.injectBean(Unknown Source)
	at io.micronaut.context.AbstractBeanDefinition.inject(AbstractBeanDefinition.java:354)
	at io.micronaut.context.DefaultBeanContext.refreshBean(DefaultBeanContext.java:262)
	at io.micronaut.runtime.context.scope.refresh.RefreshScope.refreshAllConfigurationProperties(RefreshScope.java:176)
	at io.micronaut.runtime.context.scope.refresh.RefreshScope.lambda$onApplicationEvent$1(RefreshScope.java:123)
	at io.micronaut.runtime.context.scope.refresh.RefreshScope$$Lambda$8626/716697751.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:238)
	at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_002epthreadStartRoutine_0028com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_0024ThreadStartData_0029(generated:0)
Original exception that caused the problem: org.graalvm.compiler.core.common.PermanentBailoutException: Loop formed by an exception handler
	at org.graalvm.compiler.java.BciBlockMapping.makeLoopHeader(BciBlockMapping.java:1001)
	at org.graalvm.compiler.java.BciBlockMapping.computeBlockOrder(BciBlockMapping.java:1035)
	at org.graalvm.compiler.java.BciBlockMapping.computeBlockOrder(BciBlockMapping.java:1051)
	at org.graalvm.compiler.java.BciBlockMapping.computeBlockOrder(BciBlockMapping.java:1051)
	at org.graalvm.compiler.java.BciBlockMapping.computeBlockOrder(BciBlockMapping.java:1051)
```

The actual code is generated byte code which does this:

```
try {
    var10000.setSecurePort(var10001);
} catch (NoSuchMethodError var28) {
    super.warnMissingProperty(InstanceInfo.class, "setSecurePort", "securePort");
}
```

Could be an issue with the byte code, but works fine when run with the regular JVM.

**Comment by dougxc** [comment]
This should also work fine on GraalVM without `native-image`. Is it possible to work around by changing the shape of the generated code? As the comment suggests, this may require quite some effort to support.

**Comment by graemerocher** [comment]
I will look into it and see what we can do

**Comment by graemerocher** [comment]
I couldn't find a shape that worked, since the catch block only logged a debug level exception I have removed this logging temporarily since it isn't critical and better that folks can actually build applications. I have however hit another issue which I will report in a minute

**Comment by wirthi** [comment]
I am closing this stale ticket. I suppose the problem has been resolved in the meantime. Grame has also remove the reproducer in the meantime.
Let us know if there is something still open in this area.
