### ISSUE TITLE
ZipException: zip END header not found

### ISSUE THREAD

**Issue by vanonnahenrik** [oracle/graal#7034]
Hi all,
I'm getting the error even after marking the org.graalvm.nativeimage dependency as provided as mentioned here #3093.
As you can see in the pom.xml I marked the org.graalvm.nativeimage dependency as provided. I'm using Visual Studio 2022 Developer Command Prompt v17.6.5 on windows.
Thanks in advance.
The steps to reproduce:
git clone https://github.com/vanonnahenrik/demo1
mvn package -DskipTests
native-image -jar target/demo1-0.0.1-SNAPSHOT.jar --no-fallback --verbose
execute demo1-0.0.1-SNAPSHOT.exe

results in error:
```
Exception in thread "main" java.lang.IllegalStateException: java.util.zip.ZipException: zip END header not found
        at org.springframework.boot.loader.ExecutableArchiveLauncher.<init>(ExecutableArchiveLauncher.java:57)
        at org.springframework.boot.loader.JarLauncher.<init>(JarLauncher.java:42)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.util.zip.ZipException: zip END header not found
        at java.base@17.0.7/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
        at java.base@17.0.7/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
        at java.base@17.0.7/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
        at java.base@17.0.7/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
        at java.base@17.0.7/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
        at java.base@17.0.7/java.util.zip.ZipFile.<init>(ZipFile.java:243)
        at java.base@17.0.7/java.util.zip.ZipFile.<init>(ZipFile.java:172)
        at java.base@17.0.7/java.util.jar.JarFile.<init>(JarFile.java:347)
        at java.base@17.0.7/java.util.jar.JarFile.<init>(JarFile.java:318)
        at java.base@17.0.7/java.util.jar.JarFile.<init>(JarFile.java:284)
        at org.springframework.boot.loader.jar.AbstractJarFile.<init>(AbstractJarFile.java:39)
        at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:130)
        at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:125)
        at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:111)
        at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:102)
        at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:73)
        at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:69)
        at org.springframework.boot.loader.Launcher.createArchive(Launcher.java:136)
        at org.springframework.boot.loader.ExecutableArchiveLauncher.<init>(ExecutableArchiveLauncher.java:53)
        ... 2 more
```

full output of native-image -jar target/demo1-0.0.1-SNAPSHOT.jar --no-fallback --verbose:
```
Apply jar:file:///C:/Users/hvo.DSA/graalvm/graalvm-jdk-17_windows-x64_bin/graalvm-jdk-17.0.7+8.1/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/thirdparty/native-image.properties
Apply jar:file:///C:/Users/hvo.DSA/graalvm/graalvm-jdk-17_windows-x64_bin/graalvm-jdk-17.0.7+8.1/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/polyglot/native-image.properties
Executing [
'INCLUDE=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\ATLMFC\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt' \
'LIB=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\ATLMFC\lib\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\lib\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22000.0\\um\x64' \
'Path=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\VCPackages;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\bin\Roslyn;C:\Program Files\Microsoft Visual Studio\2022\Community\Team Tools\Performance Tools\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\\x64;C:\Program Files (x86)\Windows Kits\10\bin\\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\\MSBuild\Current\Bin\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\;C:\Users\hvo.DSA\graalvm\graalvm-jdk-17_windows-x64_bin\graalvm-jdk-17.0.7+8.1\bin;C:\Program Files\Java\jdk-17\bin;t_C:\Program Files\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\PuTTY\;C:\Users\hvo.DSA\apache-maven-3.8.3-bin\apache-maven-3.8.3\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\nodejs\;C:\Program Files\CMake\bin;C:\Program Files\JetBrains\CLion 2022.2.4\bin\mingw\bin;C:\Program Files\TortoiseGit\bin;C:\Users\hvo.DSA\Strawberry\c\bin;C:\Users\hvo.DSA\Strawberry\perl\site\bin;C:\Users\hvo.DSA\Strawberry\perl\bin;C:\Android;C:\Windows\System32;C:\Users\hvo.DSA\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\hvo.DSA\AppData\Local\Programs\Python\Python311\;C:\Users\hvo.DSA\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\hvo.DSA\AppData\Local\Programs\Python\Python37\;C:\Users\hvo.DSA\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\hvo.DSA\AppData\Local\Programs\Python\Python37-32\;C:\Ruby31-x64\bin;C:\Program Files\Ruby31-x64\bin;C:\Users\hvo.DSA\AppData\Local\Microsoft\WindowsApps;C:\Users\hvo.DSA\.dotnet\tools;C:\Program Files (x86)\Sophos\Sophos SSL VPN Client\bin;C:\Users\hvo.DSA\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\JetBrains\PyCharm Community Edition 2021.3.2\bin;C:\Users\hvo.DSA\AppData\Local\Programs\MiKTeX\miktex\bin\x64\;C:\Program Files\JetBrains\DataGrip 2022.2.5\bin;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.3\bin;C:\Program Files\JetBrains\CLion 2022.2.4\bin;C:\Users\hvo.DSA\AppData\Roaming\npm;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64;C:\Users\hvo.DSA\Strawberry\perl\bin\;C:\Users\hvo.DSA\AppData\Local\JetBrains\Toolbox\scripts;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\Linux\bin\ConnectionManagerExe' \
'TEMP=C:\Users\hvo.DSA\AppData\Local\Temp' \
USE_NATIVE_IMAGE_JAVA_PLATFORM_MODULE_SYSTEM=true \
'C:\Users\hvo.DSA\graalvm\graalvm-jdk-17_windows-x64_bin\graalvm-jdk-17.0.7+8.1\bin\java.exe' \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
--add-exports=java.base/com.sun.crypto.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.access.foreign=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.event=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.loader=org.graalvm.nativeimage.builder,org.graalvm.truffle \
--add-exports=java.base/jdk.internal.logger=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.misc=com.oracle.svm.svm_enterprise,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile,org.graalvm.nativeimage.pointsto \
--add-exports=java.base/jdk.internal.module=jdk.internal.vm.compiler,org.graalvm.nativeimage.base,org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.org.objectweb.asm=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.perf=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.platform=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.ref=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=java.base/jdk.internal.reflect=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.util=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.vm.annotation=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.vm=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.invoke.util=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.net=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.nio.ch=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=java.base/sun.reflect.annotation=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.factory=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.reflectiveObjects=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.repository=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.scope=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.tree=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.jca=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.ssl=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.util=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.x509=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.text.spi=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.calendar=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.cldr=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.locale.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.locale=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.resources=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util=org.graalvm.nativeimage.builder \
--add-exports=java.management.rmi/com.sun.jmx.remote.internal.rmi=org.graalvm.nativeimage.builder \
--add-exports=java.management.rmi/com.sun.jmx.remote.protocol.rmi=org.graalvm.nativeimage.builder \
--add-exports=java.management/com.sun.jmx.mbeanserver=org.graalvm.nativeimage.builder \
--add-exports=java.management/sun.management=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=java.rmi/sun.rmi.server=org.graalvm.nativeimage.builder \
--add-exports=java.xml.crypto/org.jcp.xml.dsig.internal.dom=org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.aarch64=com.oracle.graal.graal_enterprise,com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.amd64=com.oracle.graal.graal_enterprise,com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.site=com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.stack=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=com.oracle.graal.graal_enterprise,com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.common=com.oracle.graal.graal_enterprise,com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.aarch64=jdk.internal.vm.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.amd64=jdk.internal.vm.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot=com.oracle.graal.graal_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.meta=com.oracle.graal.graal_enterprise,com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.base,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.runtime=com.oracle.graal.graal_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.services=com.oracle.graal.graal_enterprise,com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.events=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal.handlers=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal.jfc=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal=org.graalvm.nativeimage.builder \
--add-exports=jdk.management.agent/jdk.internal.agent=org.graalvm.nativeimage.builder \
--add-exports=jdk.management/com.sun.management.internal=org.graalvm.nativeimage.builder \
--add-exports=org.graalvm.truffle/com.oracle.truffle.api.object=com.oracle.graal.graal_enterprise \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-XX:MaxRAMPercentage=39.12686094341933 \
-XX:GCTimeRatio=19 \
-XX:+ExitOnOutOfMemoryError \
-Djava.awt.headless=true \
'-Dorg.graalvm.vendor=Oracle Corporation' \
-Dorg.graalvm.vendorurl=https://www.graalvm.org/ \
'-Dorg.graalvm.vendorversion=Oracle GraalVM 17.0.7+8.1' \
-Dorg.graalvm.version=23.0.0 \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
--add-modules=ALL-DEFAULT \
--module-path \
'C:\Users\hvo.DSA\graalvm\graalvm-jdk-17_windows-x64_bin\graalvm-jdk-17.0.7+8.1\lib\truffle\truffle-api.jar;C:\Users\hvo.DSA\graalvm\graalvm-jdk-17_windows-x64_bin\graalvm-jdk-17.0.7+8.1\lib\svm\builder\native-image-base.jar;C:\Users\hvo.DSA\graalvm\graalvm-jdk-17_windows-x64_bin\graalvm-jdk-17.0.7+8.1\lib\svm\builder\objectfile.jar;C:\Users\hvo.DSA\graalvm\graalvm-jdk-17_windows-x64_bin\graalvm-jdk-17.0.7+8.1\lib\svm\builder\pointsto.jar;C:\Users\hvo.DSA\graalvm\graalvm-jdk-17_windows-x64_bin\graalvm-jdk-17.0.7+8.1\lib\svm\builder\svm-enterprise.jar;C:\Users\hvo.DSA\graalvm\graalvm-jdk-17_windows-x64_bin\graalvm-jdk-17.0.7+8.1\lib\svm\builder\svm.jar' \
--module \
org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner \
-imagecp \
'C:\Users\hvo.DSA\DSA_Repos\zip-demo\demo1\target\demo1-0.0.1-SNAPSHOT.jar' \
-imagemp \
'C:\Users\hvo.DSA\graalvm\graalvm-jdk-17_windows-x64_bin\graalvm-jdk-17.0.7+8.1\lib\svm\graal-microservices.jar;C:\Users\hvo.DSA\graalvm\graalvm-jdk-17_windows-x64_bin\graalvm-jdk-17.0.7+8.1\lib\svm\library-support.jar' \
'-H:CLibraryPath=C:\Users\hvo.DSA\graalvm\graalvm-jdk-17_windows-x64_bin\graalvm-jdk-17.0.7+8.1\lib\svm\clibraries\windows-amd64' \
'-H:Path=C:\Users\hvo.DSA\DSA_Repos\zip-demo\demo1' \
'-H:Name@manifest from file:///C:/Users/hvo.DSA/DSA_Repos/zip-demo/demo1/target/demo1-0.0.1-SNAPSHOT.jar=demo1-0.0.1-SNAPSHOT' \
'-H:Class@manifest from file:///C:/Users/hvo.DSA/DSA_Repos/zip-demo/demo1/target/demo1-0.0.1-SNAPSHOT.jar=org.springframework.boot.loader.JarLauncher' \
-H:FallbackThreshold=0 \
'-H:Features@jar:file:///C:/Users/hvo.DSA/graalvm/graalvm-jdk-17_windows-x64_bin/graalvm-jdk-17.0.7+8.1/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/thirdparty/native-image.properties=com.oracle.svm.thirdparty.gson.GsonFeature' \
'-H:Features@jar:file:///C:/Users/hvo.DSA/graalvm/graalvm-jdk-17_windows-x64_bin/graalvm-jdk-17.0.7+8.1/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/polyglot/native-image.properties=com.oracle.svm.polyglot.groovy.GroovyIndyInterfaceFeature,com.oracle.svm.polyglot.scala.ScalaFeature'
]
========================================================================================================================
GraalVM Native Image: Generating 'demo1-0.0.1-SNAPSHOT' (executable)...
========================================================================================================================
[1/8] Initializing...                                                                                   (17,7s @ 0,17GB)
 Java version: 17.0.7+8-LTS, vendor version: Oracle GraalVM 17.0.7+8.1
 Graal compiler: optimization level: 2, target machine: x86-64-v3, PGO: ML-inferred
 C compiler: cl.exe (microsoft, x64, 19.36.32537)
 Garbage collector: Serial GC (max heap size: 80% of RAM)
[2/8] Performing analysis...  [****]                                                                    (12,5s @ 0,37GB)
   3.778 (75,24%) of  5.021 types reachable
   4.743 (52,86%) of  8.972 fields reachable
  18.899 (49,01%) of 38.564 methods reachable
   1.252 types,     0 fields, and   568 methods registered for reflection
      70 types,    54 fields, and    59 methods registered for JNI access
       3 native libraries: crypt32, ncrypt, version
[3/8] Building universe...                                                                               (2,1s @ 0,45GB)
[4/8] Parsing methods...      [***]                                                                      (6,0s @ 0,39GB)
[5/8] Inlining methods...     [***]                                                                      (1,0s @ 0,42GB)
[6/8] Compiling methods...    [******]                                                                  (38,5s @ 0,90GB)
[7/8] Layouting methods...    [**]                                                                       (2,6s @ 1,26GB)
[8/8] Creating image...       [**]                                                                       (3,4s @ 0,63GB)
   8,95MB (49,33%) for code area:     9.772 compilation units
   8,99MB (49,52%) for image heap:  161.979 objects and 5 resources
 215,13kB ( 1,16%) for other data
  18,15MB in total
------------------------------------------------------------------------------------------------------------------------
Top 10 origins of code area:                                Top 10 object types in image heap:
   6,53MB java.base                                            1,75MB byte[] for code metadata
   1,70MB svm.jar (Native Image)                               1,03MB byte[] for java.lang.String
 194,64kB demo1-0.0.1-SNAPSHOT.jar                      1,00MB java.lang.String
 169,69kB java.logging                                       968,03kB byte[] for general heap data
 122,71kB com.oracle.svm.svm_enterprise                      645,34kB java.lang.Class
  51,03kB jdk.crypto.mscapi                                  410,09kB java.util.HashMap$Node
  32,76kB jdk.crypto.ec                                      381,75kB java.util.concurrent.ConcurrentHashMap$Node
  32,62kB org.graalvm.sdk                                    177,09kB com.oracle.svm.core.hub.DynamicHubCompanion
  31,31kB org.graalvm.nativeimage.base                       173,33kB byte[] for reflection metadata
  15,61kB jdk.internal.vm.compiler                           149,09kB char[]
  19,70kB for 5 more packages                                  1,78MB for 960 more object types
------------------------------------------------------------------------------------------------------------------------
Recommendations:
 PGO:  Use Profile-Guided Optimizations ('--pgo') for improved throughput.
 HEAP: Set max heap for improved and more predictable memory usage.
 CPU:  Enable more CPU features with '-march=native' for improved performance.
 QBM:  Use the quick build mode ('-Ob') to speed up builds during development.
 BRPT: Try out the new build reports with '-H:+BuildReport'.
------------------------------------------------------------------------------------------------------------------------
                        2,5s (2,9% of total time) in 228 GCs | Peak RSS: 1,91GB | CPU load: 5,06
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 C:\Users\hvo.DSA\DSA_Repos\zip-demo\demo1\demo1-0.0.1-SNAPSHOT.exe (executable)
========================================================================================================================
Finished generating 'demo1-0.0.1-SNAPSHOT' in 1m 24s.

```

**Comment by oubidar-Abderrahim** [comment]
Thank you for reaching out about this, we'll take a look into it shortly
Tracked internally on GR 47591

**Comment by oubidar-Abderrahim** [comment]
It seems that this problem only happens if you try to build a native image directly from the `.jar` file. 
Normally, this would result in a fallback image but it is of course possible to configure everything in a way that the Native Image can actually be built. However, this just results in a broken Native Image because the Native Image executable tries to open itself as a `.jar` file, which eventually results in the exception above because the Native Image is not a `.jar` file.

Spring comes with its own way of building a Native Image and everything seems to work fine if that approach is used (e.g., mvn -Pnative native:compile, refer to the Spring documentation for more details: https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html)

Please use `mvn -Pnative native:compile` to build the image.

**Comment by vanonnahenrik** [comment]
Okay thank you for the response.
