### ISSUE TITLE
[native-image] GroovyRuntimeException: Failed to create DGM method proxy : java.lang.ClassNotFoundException: org.codehaus.groovy.runtime.dgm$463

### ISSUE THREAD

**Issue by wololock** [oracle/graal#706]
I'm playing around with GraalVM (1.0.0-RC7) and some Groovy code, and I faced following issue. I have created a simple Groovy class:

*HelloWorld.groovy*
```groovy
import groovy.transform.CompileStatic
import groovy.transform.TypeChecked

@CompileStatic
@TypeChecked
class HelloWorld {
    static void main(String[] args) {
        println ((0..10).sum())
    }
}
```
I compile it (Groovy 2.4.12):

```bash
groovyc HelloWorld.groovy
```

And I am able to run it with using `java`:

```bash
% java -version
openjdk version "1.8.0_172"
OpenJDK Runtime Environment (build 1.8.0_172-20180625212755.graaluser.jdk8u-src-tar-g-b11)
GraalVM 1.0.0-rc7 (build 25.71-b01-internal-jvmci-0.48, mixed mode)

% java -cp ".:$HOME/.m2/repository/org/codehaus/groovy/groovy-all/2.4.12/groovy-all-2.4.12.jar" HelloWorld
55
```
Creating GraalVM native image works:

```bash
% native-image -H:+ReportUnsupportedElementsAtRuntime --no-server -cp ".:$HOME/.m2/repository/org/codehaus/groovy/groovy-all/2.4.12/groovy-all-2.4.12.jar" HelloWorld
[helloworld:25010]    classlist:   2,515.16 ms
[helloworld:25010]        (cap):     644.38 ms
[helloworld:25010]        setup:   1,199.07 ms
Warning: Detected unnecessary RecomputeFieldValue.ArrayBaseOffset com.oracle.svm.core.jdk.Target_java_nio_DirectByteBuffer.arrayBaseOffset substitution field for java.nio.DirectByteBuffer.arrayBaseOffset. The annotated field can be removed. This ArrayBaseOffset computation can be detected automatically. Use option -H:+UnsafeAutomaticSubstitutionsLogLevel=2 to print all automatically detected substitutions. 
[helloworld:25010]   (typeflow):   6,735.51 ms
[helloworld:25010]    (objects):   6,214.31 ms
[helloworld:25010]   (features):      92.78 ms
[helloworld:25010]     analysis:  14,747.73 ms
[helloworld:25010]     universe:     531.84 ms
[helloworld:25010]      (parse):   1,978.91 ms
[helloworld:25010]     (inline):   2,369.40 ms
[helloworld:25010]    (compile):  10,841.72 ms
[helloworld:25010]      compile:  18,930.68 ms
[helloworld:25010]        image:   1,862.20 ms
[helloworld:25010]        write:     339.16 ms
[helloworld:25010]      [total]:  41,736.50 ms
```

Now, when I run `./helloworld` it produces following stacktrace:

```bash
% ./helloworld 
java.lang.ClassNotFoundException: org.codehaus.groovy.runtime.dgm$463
	at java.lang.Throwable.<init>(Throwable.java:287)
	at java.lang.Exception.<init>(Exception.java:84)
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:75)
	at java.lang.ClassNotFoundException.<init>(ClassNotFoundException.java:82)
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:51)
	at com.oracle.svm.core.jdk.Target_java_lang_ClassLoader.loadClass(Target_java_lang_ClassLoader.java:126)
	at org.codehaus.groovy.reflection.GeneratedMetaMethod$Proxy.createProxy(GeneratedMetaMethod.java:91)
	at org.codehaus.groovy.reflection.GeneratedMetaMethod$Proxy.proxy(GeneratedMetaMethod.java:83)
	at org.codehaus.groovy.reflection.GeneratedMetaMethod$Proxy.isValidMethod(GeneratedMetaMethod.java:68)
	at groovy.lang.MetaClassImpl.chooseMethodInternal(MetaClassImpl.java:3197)
	at groovy.lang.MetaClassImpl.chooseMethod(MetaClassImpl.java:3159)
	at groovy.lang.MetaClassImpl.getNormalMethodWithCaching(MetaClassImpl.java:1375)
	at groovy.lang.MetaClassImpl.getMethodWithCaching(MetaClassImpl.java:1290)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1060)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.sum(DefaultGroovyMethods.java:5716)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.sum(DefaultGroovyMethods.java:5541)
	at HelloWorld.main(HelloWorld.groovy:8)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:163)
Exception in thread "main" groovy.lang.GroovyRuntimeException: Failed to create DGM method proxy : java.lang.ClassNotFoundException: org.codehaus.groovy.runtime.dgm$463
	at java.lang.Throwable.<init>(Throwable.java:287)
	at java.lang.Exception.<init>(Exception.java:84)
	at java.lang.RuntimeException.<init>(RuntimeException.java:80)
	at groovy.lang.GroovyRuntimeException.<init>(GroovyRuntimeException.java:47)
	at org.codehaus.groovy.reflection.GeneratedMetaMethod$Proxy.createProxy(GeneratedMetaMethod.java:96)
	at org.codehaus.groovy.reflection.GeneratedMetaMethod$Proxy.proxy(GeneratedMetaMethod.java:83)
	at org.codehaus.groovy.reflection.GeneratedMetaMethod$Proxy.isValidMethod(GeneratedMetaMethod.java:68)
	at groovy.lang.MetaClassImpl.chooseMethodInternal(MetaClassImpl.java:3197)
	at groovy.lang.MetaClassImpl.chooseMethod(MetaClassImpl.java:3159)
	at groovy.lang.MetaClassImpl.getNormalMethodWithCaching(MetaClassImpl.java:1375)
	at groovy.lang.MetaClassImpl.getMethodWithCaching(MetaClassImpl.java:1290)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1060)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.sum(DefaultGroovyMethods.java:5716)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.sum(DefaultGroovyMethods.java:5541)
	at HelloWorld.main(HelloWorld.groovy:8)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:163)
Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.runtime.dgm$463
	at java.lang.Throwable.<init>(Throwable.java:287)
	at java.lang.Exception.<init>(Exception.java:84)
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:75)
	at java.lang.ClassNotFoundException.<init>(ClassNotFoundException.java:82)
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:51)
	at com.oracle.svm.core.jdk.Target_java_lang_ClassLoader.loadClass(Target_java_lang_ClassLoader.java:126)
	at org.codehaus.groovy.reflection.GeneratedMetaMethod$Proxy.createProxy(GeneratedMetaMethod.java:91)
	... 12 more
```

According to the following line from the stacktrace:
```
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.sum(DefaultGroovyMethods.java:5716)
```
it looks like invoking `plus` method via metaclass causes this problem: https://github.com/apache/groovy/blob/GROOVY_2_4_12/src/main/org/codehaus/groovy/runtime/DefaultGroovyMethods.java#L5716

Another thing: GraalVM throws `ClassNotFoundException`, but it looks like the class it cannot find exists in the `groovy-all-2.4.12.jar` file:

```bash
% unzip -l $HOME/.m2/repository/org/codehaus/groovy/groovy-all/2.4.12/groovy-all-2.4.12.jar | grep 'dgm$463'
      718  06-21-2017 17:10   org/codehaus/groovy/runtime/dgm$463.class
```

I'm guessing that Groovy hits [GraalVM limitation](https://github.com/oracle/graal/blob/master/substratevm/LIMITATIONS.md) in this case. I hope you find this report useful.

Btw, if I do a simple "Hello, World!" instead of calling `(0..10).sum()`, then native image runs without any issues.

```groovy
import groovy.transform.CompileStatic
import groovy.transform.TypeChecked

@CompileStatic
@TypeChecked
class HelloWorld {
    static void main(String[] args) {
        println "Hello, World!"
    }
}
```

Output:

```bash
% native-image -H:+ReportUnsupportedElementsAtRuntime --no-server -cp ".:$HOME/.m2/repository/org/codehaus/groovy/groovy-all/2.4.12/groovy-all-2.4.12.jar" HelloWorld
[helloworld:11603]    classlist:   2,492.32 ms
[helloworld:11603]        (cap):     643.83 ms
[helloworld:11603]        setup:   1,189.73 ms
Warning: Detected unnecessary RecomputeFieldValue.ArrayBaseOffset com.oracle.svm.core.jdk.Target_java_nio_DirectByteBuffer.arrayBaseOffset substitution field for java.nio.DirectByteBuffer.arrayBaseOffset. The annotated field can be removed. This ArrayBaseOffset computation can be detected automatically. Use option -H:+UnsafeAutomaticSubstitutionsLogLevel=2 to print all automatically detected substitutions. 
[helloworld:11603]   (typeflow):   6,981.35 ms
[helloworld:11603]    (objects):   6,528.48 ms
[helloworld:11603]   (features):      99.03 ms
[helloworld:11603]     analysis:  15,174.59 ms
[helloworld:11603]     universe:     591.48 ms
[helloworld:11603]      (parse):   1,898.78 ms
[helloworld:11603]     (inline):   2,413.22 ms
[helloworld:11603]    (compile):  11,608.69 ms
[helloworld:11603]      compile:  19,588.14 ms
[helloworld:11603]        image:   1,803.54 ms
[helloworld:11603]        write:     358.38 ms
[helloworld:11603]      [total]:  42,714.23 ms

% ./helloworld 
Hello, World!
```

**Comment by wololock** [comment]
Btw, I've run the same example with `2.5.2` and `3.0.0-alpha-3` Groovy version - same result.

**Comment by wololock** [comment]
I have a workaround that allowed me running this broken example. I have created a configuration JSON file for AOT:

*graal.json*
```json
[
  {
    "name": "org.codehaus.groovy.runtime.dgm$463",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true
  },
  {
    "name": "org.codehaus.groovy.runtime.dgm$1121",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true
  }
]
```

Creating native image with this configuration file allowed me to execute `./helloworld` program.

```bash
native-image -H:+ReportUnsupportedElementsAtRuntime -H:ReflectionConfigurationFiles=graal.json --no-server -cp ".:$HOME/.m2/repository/org/codehaus/groovy/groovy-all/2.4.12/groovy-all-2.4.12.jar" HelloWorld
```
I am aware that in this case these two `dgm$...` classes where missing for AOT. In most cases there will be much more `dgm$...` classes missing (there are 1280 `dgm$...` classes in Groovy 2.4.12).

**Comment by wololock** [comment]
Implementing `Feature` seems to be a good alternative. Thanks @cstancu 

Btw, `RuntimeReflection.register(SomeClass.class)` an equivalent of 

```json
[
  {
    "name": "SomeClass",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true
  }
]
```

or something else has to be called to get `allPublicMethods` triggered with the custom feature?

**Comment by cstancu** [comment]
`RuntimeReflection.register(SomeClass.class)` only registers the class. You need `RuntimeReflection.register(SomeClass.class.getMethods())` to get all public methods. That's what we do when [parsing ` "allPublicMethods" : true`](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/config/ReflectionConfigurationParser.java#L119).
