### ISSUE TITLE
LLVM backend broken: no jniLLVM (is it because of ARM?)

### ISSUE THREAD

**Issue by CGDogan** [oracle/graal#7071]
ARM64 Linux:

```
public class Ab {
public static void main(String[] s) {
System.out.println("hhh");
}
}
```

`native-image -H:CompilerBackend=llvm    Ab`:

```
Fatal error: org.graalvm.compiler.debug.GraalError: java.lang.NoClassDefFoundError: Could not initialize class com.oracle.svm.shadowed.org.bytedeco.llvm.global.LLVM
	at method: void Ab.main(String[])  [entry point]
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:1295)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:1224)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:300)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:187)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:171)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.oracle.svm.shadowed.org.bytedeco.llvm.global.LLVM
	at org.graalvm.nativeimage.llvm/com.oracle.svm.core.graal.llvm.util.LLVMIRBuilder.<init>(LLVMIRBuilder.java:74)
	at org.graalvm.nativeimage.llvm/com.oracle.svm.core.graal.llvm.LLVMGenerator.<init>(LLVMGenerator.java:185)
	at org.graalvm.nativeimage.llvm/com.oracle.svm.core.graal.llvm.SubstrateLLVMBackend.emitLLVM(SubstrateLLVMBackend.java:121)
	at org.graalvm.nativeimage.llvm/com.oracle.svm.core.graal.llvm.SubstrateLLVMBackend.emitBackEnd(SubstrateLLVMBackend.java:105)
	at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:170)
	at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:137)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:1276)
	... 10 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: no jniLLVM in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib [in thread "main"]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2444)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:880)
	at java.base/java.lang.System.loadLibrary(System.java:2051)
	at com.oracle.svm.shadowed.org.bytedeco.javacpp/com.oracle.svm.shadowed.org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1800)
	at com.oracle.svm.shadowed.org.bytedeco.javacpp/com.oracle.svm.shadowed.org.bytedeco.javacpp.Loader.load(Loader.java:1402)
	at com.oracle.svm.shadowed.org.bytedeco.javacpp/com.oracle.svm.shadowed.org.bytedeco.javacpp.Loader.load(Loader.java:1214)
	at com.oracle.svm.shadowed.org.bytedeco.javacpp/com.oracle.svm.shadowed.org.bytedeco.javacpp.Loader.load(Loader.java:1190)
	at com.oracle.svm.shadowed.org.bytedeco.llvm/com.oracle.svm.shadowed.org.bytedeco.llvm.global.LLVM.<clinit>(LLVM.java:14)
	at org.graalvm.nativeimage.llvm/com.oracle.svm.core.graal.llvm.util.LLVMIRBuilder.<init>(LLVMIRBuilder.java:74)
	at org.graalvm.nativeimage.llvm/com.oracle.svm.core.graal.llvm.LLVMGenerator.<init>(LLVMGenerator.java:185)
	at org.graalvm.nativeimage.llvm/com.oracle.svm.core.graal.llvm.SubstrateLLVMBackend.emitLLVM(SubstrateLLVMBackend.java:121)
	at org.graalvm.nativeimage.llvm/com.oracle.svm.core.graal.llvm.SubstrateLLVMBackend.emitBackEnd(SubstrateLLVMBackend.java:105)
	at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:170)
	at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:137)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:1276)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:1224)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:300)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:187)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:171)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool.externalHelpQuiesce(ForkJoinPool.java:2260)
	at java.base/java.util.concurrent.ForkJoinPool.helpQuiescePool(ForkJoinPool.java:2297)
	at java.base/java.util.concurrent.ForkJoinPool.awaitQuiescence(ForkJoinPool.java:3565)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.complete(CompletionExecutor.java:237)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.runOnExecutor(CompileQueue.java:597)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.compileAll(CompileQueue.java:885)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.finish(CompileQueue.java:427)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:670)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:547)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:522)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:707)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:142)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:97)
...
```

full [out.txt.tar.gz](https://github.com/oracle/graal/files/12179441/out.txt.tar.gz)

It's correct, find /graalvm-community-openjdk-20.0.1+9.1/ -name "*jniLLVM*" returns nothing

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this, we'll take a look into it shortly

**Comment by xuxiaocheng0201** [comment]
Sorry, but the same problem. The command `gu install native-image-llvm-backend` is not worked.

Because that I'm running a linux arm64 docker container on darwin arm64?

<details><summary>java --version</summary><code>
openjdk 17.0.8 2023-07-18
OpenJDK Runtime Environment GraalVM CE 17.0.8+7.1 (build 17.0.8+7-jvmci-23.0-b15)
OpenJDK 64-Bit Server VM GraalVM CE 17.0.8+7.1 (build 17.0.8+7-jvmci-23.0-b15, mixed mode, sharing)
</code>
</details>
