### ISSUE TITLE
[native-image] Groovy script and missing InvokerHelper.runScript() method when building native image

### ISSUE THREAD

**Issue by wololock** [oracle/graal#708]
Specs: GraalVM-1.0.0-RC7, Groovy 2.4.12

I'm trying to build native image of a simple "Hello, World!" Groovy script. 

*HelloWorld.groovy*
```groovy
#!groovy

println "Hello, World!"
```

It compiles:

```bash
groovyc HelloWorld.groovy
```

And runs as a Java program:

```bash
java -version
openjdk version "1.8.0_172"
OpenJDK Runtime Environment (build 1.8.0_172-20180625212755.graaluser.jdk8u-src-tar-g-b11)
GraalVM 1.0.0-rc7 (build 25.71-b01-internal-jvmci-0.48, mixed mode)

java -cp ".:$HOME/.m2/repository/org/codehaus/groovy/groovy-all/2.4.12/groovy-all-2.4.12.jar" HelloWorld
Hello, World!
```
Now, in the next step I tried building native image for GraalVM with the following command:

```bash
native-image -H:+ReportUnsupportedElementsAtRuntime -H:ReflectionConfigurationFiles=graal.json,groovy.json --no-server -cp ".:$HOME/.m2/repository/org/codehaus/groovy/groovy-all/2.4.12/groovy-all-2.4.12.jar" HelloWorld
```

where `graal.json` file (https://gist.github.com/wololock/923afb730a918d0d86ef14a4b5648220) lists all dynamically generated methods accessed via reflecion, and `groovy.json` simply adds `HelloWorld` class so GraalVM can locate its constructor:

```json
[
  {
    "name": "HelloWorld",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
  }
]
```

Image builds:

```bash
[helloworld:23841]    classlist:   2,750.39 ms
[helloworld:23841]        (cap):     802.15 ms
[helloworld:23841]        setup:   2,801.21 ms
Warning: Detected unnecessary RecomputeFieldValue.ArrayBaseOffset com.oracle.svm.core.jdk.Target_java_nio_DirectByteBuffer.arrayBaseOffset substitution field for java.nio.DirectByteBuffer.arrayBaseOffset. The annotated field can be removed. This ArrayBaseOffset computation can be detected automatically. Use option -H:+UnsafeAutomaticSubstitutionsLogLevel=2 to print all automatically detected substitutions. 
[helloworld:23841]   (typeflow):  14,050.77 ms
[helloworld:23841]    (objects):  11,259.90 ms
[helloworld:23841]   (features):     197.58 ms
[helloworld:23841]     analysis:  27,320.90 ms
[helloworld:23841]     universe:   1,034.53 ms
[helloworld:23841]      (parse):   3,799.24 ms
[helloworld:23841]     (inline):   3,542.06 ms
[helloworld:23841]    (compile):  16,638.90 ms
[helloworld:23841]      compile:  30,028.42 ms
[helloworld:23841]        image:   3,356.42 ms
[helloworld:23841]        write:     675.05 ms
[helloworld:23841]      [total]:  76,222.73 ms
```

But when I try to run it, it throws following exception:

```bash
./helloworld
Exception in thread "main" groovy.lang.MissingMethodException: No signature of method: static org.codehaus.groovy.runtime.InvokerHelper.runScript() is applicable for argument types: (java.lang.Class, [Ljava.lang.String;) values: [class HelloWorld, [0, 10]]
	at java.lang.Throwable.<init>(Throwable.java:250)
	at java.lang.Exception.<init>(Exception.java:54)
	at java.lang.RuntimeException.<init>(RuntimeException.java:51)
	at groovy.lang.GroovyRuntimeException.<init>(GroovyRuntimeException.java:34)
	at groovy.lang.MissingMethodException.<init>(MissingMethodException.java:49)
	at groovy.lang.MetaClassImpl.invokeStaticMissingMethod(MetaClassImpl.java:1501)
	at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1487)
	at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.call(StaticMetaClassSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at HelloWorld.main(HelloWorld.groovy)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:163)

```

`InvokeHelper` class has a method for expected argument types - https://github.com/apache/groovy/blob/GROOVY_2_4_X/src/main/org/codehaus/groovy/runtime/InvokerHelper.java#L425

Two interesting facts:

1. If I add a compiler configuration for `groovyc` and I force static compilation, native image runs without any issue.

*compiler.groovy*
```groovy
withConfig(configuration) {
    ast(groovy.transform.CompileStatic)
    ast(groovy.transform.TypeChecked)
}
```

```bash
groovyc -configscript compiler.groovy HelloWorld.groovy
```

2. If I switch from a Groovy script to a Groovy class (without static compilation), native image builds correctly and it runs without any issue.

The second case proved, that GraalVM can run a class created without static compilation. Groovy script gets compiled to a class, so technically it should be possible to run a script without static compilation. And here is what the script class looks like in Java (bytecode decompiled to a Java):

```java
//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by Fernflower decompiler)
//

import groovy.lang.Binding;
import groovy.lang.Script;
import org.codehaus.groovy.runtime.InvokerHelper;
import org.codehaus.groovy.runtime.callsite.CallSite;

public class HelloWorld extends Script {
    public HelloWorld() {
        CallSite[] var1 = $getCallSiteArray();
    }

    public HelloWorld(Binding context) {
        CallSite[] var2 = $getCallSiteArray();
        super(context);
    }

    public static void main(String... args) {
        CallSite[] var1 = $getCallSiteArray();
        var1[0].call(InvokerHelper.class, HelloWorld.class, args);
    }

    public Object run() {
        CallSite[] var1 = $getCallSiteArray();
        return var1[1].callCurrent(this, "Hello, World!");
    }
}
```

**Comment by wololock** [comment]
I just did a test with GraalVM 1.0.0-RC11, problem still exists. Native image of a simple Groovy script (without static compilation) executes with `java -jar ...`, native image compiles, but running `./helloworld` from the above example fails with the following stack trace:

```
./helloworld 
Exception in thread "main" groovy.lang.MissingMethodException: No signature of method: static org.codehaus.groovy.runtime.InvokerHelper.runScript() is applicable for argument types: (Class, [Ljava.lang.String;) values: [class HelloWorld, []]
	at groovy.lang.MetaClassImpl.invokeStaticMissingMethod(MetaClassImpl.java:1528)
	at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1514)
	at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.call(StaticMetaClassSite.java:52)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
	at HelloWorld.main(HelloWorld.groovy)
```

**Comment by cstancu** [comment]
@wololock did you try registering `InvokeHelper.runScript(Class scriptClass, String[] args) ` for reflection? I am not familiar with groovy internals, but does `CallSite.call(InvokerHelper.class, HelloWorld.class, args)` use reflection?

**Comment by wololock** [comment]
@cstancu I added `InvokerHelper.runScript(Class scriptClass, String[] args)` to reflection after your suggestion. I think it revealed a root cause:

_reflection.json_
```
[
  {
    "name": "HelloWorld",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true
  },
  {
    "name": "org.codehaus.groovy.runtime.InvokerHelper",
    "methods": [
      { "name": "runScript", "parameterTypes": ["java.lang.Class", "java.lang.String[]"] }
    ]
  }
]
```

_./helloworld_

```
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported method java.lang.ClassLoader.defineClass(String, byte[], int, int, ProtectionDomain) is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:109)
	at java.lang.ClassLoader.defineClass(Target_java_lang_ClassLoader.java:761)
	at org.codehaus.groovy.reflection.ClassLoaderForClassArtifacts.define(ClassLoaderForClassArtifacts.java:43)
	at org.codehaus.groovy.reflection.ClassLoaderForClassArtifacts$1.run(ClassLoaderForClassArtifacts.java:76)
	at org.codehaus.groovy.reflection.ClassLoaderForClassArtifacts$1.run(ClassLoaderForClassArtifacts.java:74)
	at java.security.AccessController.doPrivileged(AccessController.java:62)
	at org.codehaus.groovy.reflection.ClassLoaderForClassArtifacts.defineClassAndGetConstructor(ClassLoaderForClassArtifacts.java:74)
	at org.codehaus.groovy.runtime.callsite.CallSiteGenerator.compileStaticMethod(CallSiteGenerator.java:262)
	at org.codehaus.groovy.reflection.CachedMethod.createStaticMetaMethodSite(CachedMethod.java:302)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.createStaticMetaMethodSite(StaticMetaMethodSite.java:114)
	at groovy.lang.MetaClassImpl.createStaticSite(MetaClassImpl.java:3455)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:76)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:161)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
	at HelloWorld.main(HelloWorld.groovy)
```

**Comment by cstancu** [comment]
Defining new classes at run time is not supported since you would need the machinery to interpret/compile the new bytecodes at run time. `native-image` doesn't include such machinery by design, to achieve the fast start-up/low footprint goals. As you mentioned above, you should either force static compilation for `groovyc` or  switch from Groovy script to a Groovy class.
