### ISSUE TITLE
AssertionError exception in PolyglotList.java when calling Java code from JS.

### ISSUE THREAD

**Issue by itwaseasy** [oracle/graal#7082]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **17.0.8+9.1 (build 17.0.8+9-LTS-jvmci-23.0-b14)**
 - CE or EE: **CE**
 - JDK version: **17**
 - OS and OS Version: **macOS Ventura 13.5**
 - Architecture: **amd64**
 - The output of `java -Xinternalversion`:
```
Java HotSpot(TM) 64-Bit Server VM (17.0.8+9-LTS-jvmci-23.0-b14) for bsd-amd64 JRE (17.0.8+9-LTS-jvmci-23.0-b14), built on Jun 27 2023 12:00:39 by "graal1" with clang Apple LLVM 12.0.0 (clang-1200.0.32.29)
```

**Have you verified this issue still happens when using the latest snapshot?**
Yes.

**Describe the issue**
AssertionError exception in PolyglotList.java when calling Java code with different parameters from JS: 
```
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotList$Cache.lookup(PolyglotList.java:194)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotList.<init>(PolyglotList.java:75)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotList.create(PolyglotList.java:98)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotHostAccess.toList(PolyglotHostAccess.java:92)
        at org.graalvm.truffle/com.oracle.truffle.host.HostToTypeNode.asJavaObject(HostToTypeNode.java:437)
        at org.graalvm.truffle/com.oracle.truffle.host.HostToTypeNode.convertImpl(HostToTypeNode.java:208)
        at org.graalvm.truffle/com.oracle.truffle.host.HostToTypeNode.doCached(HostToTypeNode.java:130)
        at org.graalvm.truffle/com.oracle.truffle.host.HostToTypeNodeGen.executeAndSpecialize(HostToTypeNodeGen.java:126)
        at org.graalvm.truffle/com.oracle.truffle.host.HostToTypeNodeGen.execute(HostToTypeNodeGen.java:90)
        at org.graalvm.truffle/com.oracle.truffle.host.HostExecuteNode.doFixed(HostExecuteNode.java:130)
        at org.graalvm.truffle/com.oracle.truffle.host.HostExecuteNodeGen$Inlined.executeAndSpecialize(HostExecuteNodeGen.java:402)
        at org.graalvm.truffle/com.oracle.truffle.host.HostExecuteNodeGen$Inlined.execute(HostExecuteNodeGen.java:362)
        at org.graalvm.truffle/com.oracle.truffle.host.HostObject.invokeMember(HostObject.java:465)
        at org.graalvm.truffle/com.oracle.truffle.host.HostObjectGen$InteropLibraryExports$Cached.invokeMemberNode_AndSpecialize(HostObjectGen.java:7369)
        at org.graalvm.truffle/com.oracle.truffle.host.HostObjectGen$InteropLibraryExports$Cached.invokeMember(HostObjectGen.java:7355)
        at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibrary$Asserts.invokeMember(InteropLibrary.java:3565)
        at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.invokeMember(InteropLibraryGen.java:8477)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$ForeignInvokeNode.executeCall(JSFunctionCallNode.java:1609)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:318)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:263)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$InvokeNode.execute(JSFunctionCallNode.java:764)
        at com.oracle.truffle.js.nodes.control.DiscardResultNode.execute(DiscardResultNode.java:88)
        at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73)
        at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:156)
        at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:96)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:718)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:641)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:574)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:558)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:504)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:69)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$DirectJSFunctionCacheNode.executeCall(JSFunctionCallNode.java:1391)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:318)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:263)
        at com.oracle.truffle.js.nodes.interop.JSInteropExecuteNode.doDefault(JSInteropExecuteNode.java:68)
        at com.oracle.truffle.js.nodes.interop.JSInteropExecuteNodeGen.execute(JSInteropExecuteNodeGen.java:75)
        at com.oracle.truffle.js.runtime.interop.InteropBoundFunction.execute(InteropBoundFunction.java:111)
        at com.oracle.truffle.js.runtime.interop.InteropBoundFunctionGen$InteropLibraryExports$Cached.execute(InteropBoundFunctionGen.java:218)
        at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$Delegate.execute(InteropLibraryGen.java:3943)
        at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibrary$Asserts.execute(InteropLibrary.java:3102)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$SharedExecuteNode.doDefault(PolyglotValueDispatch.java:4379)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$SharedExecuteNodeGen$Inlined.executeShared(PolyglotValueDispatchFactory.java:9203)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$ExecuteVoidNoArgsNode.doDefault(PolyglotValueDispatch.java:4435)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$ExecuteVoidNoArgsNodeGen.executeImpl(PolyglotValueDispatchFactory.java:9518)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:124)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:718)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:641)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:574)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:558)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalRuntimeSupport.callProfiled(GraalRuntimeSupport.java:255)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue.executeVoid(PolyglotValueDispatch.java:2447)
        at org.graalvm.sdk/org.graalvm.polyglot.Value.executeVoid(Value.java:901)
        at org.example.Main.lambda$main$0(Main.java:43)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.example.Main.main(Main.java:37)
```

**Code snippet or code repository that reproduces the issue**
```
https://github.com/itwaseasy/graal-assert-issue
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. git clone --depth 1 https://github.com/itwaseasy/graal-assert-issue
2. ./mvnw clean package
3. target/app/bin/main 

**Expected behavior**
The JS code example works correctly and prints the following:
```
(3)[["hello"], ["world"], []]
[["hello"]]
```

**Comment by woess** [comment]
Thanks for the report! Fixed in https://github.com/oracle/graal/commit/10bcd49477a13975f58eeb83c6188a3a6158f4b8.
