### ISSUE TITLE
Building SubstrateVM fails after https://github.com/oracle/graal/pull/7102

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#7146]
**Describe the issue**
Since the merge of https://github.com/oracle/graal/pull/7102 building substrate VM with:

```
mx --native=native-image,lib:jvmcicompiler --components="Native Image,LibGraal" build
```

fails with:

```
...
Archiving NATIVE_IMAGE_BASE... [dependency com.oracle.svm.common updated]
Building Java module org.graalvm.nativeimage.base (native-image-base.jar) from NATIVE_IMAGE_BASE
Compiling com.oracle.truffle.host with javac-daemon(JDK 21)... [dependency TRUFFLE_DSL_PROCESSOR updated]
Error: Module org.graalvm.sdk not found, required by jdk.internal.vm.compiler.management
java.lang.module.FindException: Module org.graalvm.sdk not found, required by jdk.internal.vm.compiler.management
	at java.base/java.lang.module.Resolver.findFail(Resolver.java:892)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:192)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:141)
	at java.base/java.lang.module.Configuration.resolve(Configuration.java:420)
	at java.base/java.lang.module.Configuration.resolve(Configuration.java:254)
	at jdk.jlink/jdk.tools.jlink.internal.Jlink$JlinkConfiguration.resolve(Jlink.java:217)
	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.createImageProvider(JlinkTask.java:523)
	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.createImage(JlinkTask.java:411)
	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.run(JlinkTask.java:286)
	at jdk.jlink/jdk.tools.jlink.internal.Main.run(Main.java:56)
	at jdk.jlink/jdk.tools.jlink.internal.Main.main(Main.java:34)

Building graalvm-jimage: Failed due to error: 1
Note: Some input files use or override a deprecated API that is marked for removal.
Note: Recompile with -Xlint:removal for details.
```

This causes the Quarkus CI nightly runs to fail, see https://github.com/oracle/graal/actions/runs/5746129140/job/15575150905

**Steps to reproduce the issue**
1. git clone https://github.com/oracle/graal.git
2. cd graal/substratevm
3. `mx --native=native-image,lib:jvmcicompiler --components="Native Image,LibGraal" build`

**Describe GraalVM and your environment:**
 - GraalVM version: **https://github.com/oracle/graal/commit/0775f084cca8b111d9cdb8c3511931440e310d70**
 - JDK major version: **21**
 - OS: **Fedora 38**
 - Architecture: **AMD64**

cc @chumer @fniephaus

**Comment by zakkak** [comment]
@chumer this is caused by the change in https://github.com/oracle/graal/pull/7102/files#diff-5b7b034c643f0954a36331bffe67fd7cec40f5046af55d21d08065df107f7f08L1344-R1340

`Truffle API` used to bring in `Graal SDK` as well, while `Truffle Compiler` does not

**Comment by chumer** [comment]
FYI: @zakkak my change is now in the merge-queue: https://github.com/oracle/graal/pull/7171

**Comment by jerboaa** [comment]
Thanks, I've verified this is fixed with #7171. We also see it building again in [nighly mandrel CI](https://github.com/graalvm/mandrel/actions/runs/5827845086/job/15804572271#step:7:3).

**Comment by chumer** [comment]
@jerboaa thanks for verifying!

**Comment by zakkak** [comment]
Thank you for the follow up @chumer !
