### ISSUE TITLE
Inconsistent behaviour of ClassLoader and Class.forName()

### ISSUE THREAD

**Issue by dsyer** [oracle/graal#715]
Some code (for a class that is on the class path):

```java
		System.err.println(Thread.currentThread().getContextClassLoader());
		System.err.println(getClass().getClassLoader());
		System.err.println(Class.forName("com.fasterxml.jackson.databind.ObjectMapper"));
		System.err.println(getClass().getClassLoader()
				.loadClass("com.fasterxml.jackson.databind.ObjectMapper"));
```

In a normal JVM:

```
sun.misc.Launcher$AppClassLoader@73d16e93
sun.misc.Launcher$AppClassLoader@73d16e93
class com.fasterxml.jackson.databind.ObjectMapper
class com.fasterxml.jackson.databind.ObjectMapper
```

In a Substrate VM:

```
java.lang.ClassLoader@55bb3ed30828
java.lang.ClassLoader@55bb3ebba478
class com.fasterxml.jackson.databind.ObjectMapper
Exception in thread "main" java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper
	at java.lang.Throwable.<init>(Throwable.java:287)
	at java.lang.Exception.<init>(Exception.java:84)
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:75)
	at java.lang.ClassNotFoundException.<init>(ClassNotFoundException.java:82)
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:51)
	at com.oracle.svm.core.jdk.Target_java_lang_ClassLoader.loadClass(Target_java_lang_ClassLoader.java:126)
	at Classes.run(Classes.java:14)
	at Classes.main(Classes.java:6)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:163)
```

So, while it is nice that there is a non-null `ClassLoader` available at runtime, its behaviour is so different to the regular one it is not really all that useful.

The javadocs for `Class.forName()` say:

> Invoking this method is equivalent to:
>        
>         Class.forName(className, true, currentLoader)
>         
> where currentLoader denotes the defining class loader of the current class.

so that seems to be a good guide to the desired behaviour in Substrate (where the equivalence is not broken, but probably `ClassLoader.loadClass()` should also work)?

**Comment by sbrannen** [comment]
The following test passes within a native image using GraalVM 20.0.

```java
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class ClassLoaderTests {

	@Test
	void test() throws Exception {
		String className = "org.junit.jupiter.api.RepeatedTest";

		assertThat(Thread.currentThread().getContextClassLoader()).isEqualTo(getClass().getClassLoader());
		assertThat(Class.forName(className)).isEqualTo(getClass().getClassLoader().loadClass(className));
	}

}
```

Thus, I think you can probably close this issue.
