### ISSUE TITLE
SubstrateVM: Hibernate Validator UnsupportedFeatureError in RC6

### ISSUE THREAD

**Issue by graemerocher** [oracle/graal#718]
Hibernate Validator seems to be hitting a `UnsupportedFeatureError`. I have looked at the code and it doesn't appear to be doing anything too unusual.

Note that I have been unable to test RC7 due to #717

Steps to reproduce:

* Use Graal-RC6
* Clone the repo: https://github.com/ilopmar/micronaut-security-jwt-graal
* Execute ./build-native-image.sh

```
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Unresolved element found 
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Error.<init>(Error.java:70)
	at com.oracle.svm.core.jdk.UnsupportedFeatureError.<init>(UnsupportedFeatureError.java:31)
	at com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.unsupportedFeature(VMErrorSubstitutions.java:109)
	at com.oracle.svm.core.snippets.SnippetRuntime.unresolved(SnippetRuntime.java:205)
	at org.hibernate.validator.internal.metadata.core.ConstraintHelper.<init>(ConstraintHelper.java:674)
	at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.<init>(ValidatorFactoryImpl.java:142)
	at org.hibernate.validator.HibernateValidator.buildValidatorFactory(HibernateValidator.java:38)
	at org.hibernate.validator.internal.engine.ConfigurationImpl.buildValidatorFactory(ConfigurationImpl.java:364)
	at io.micronaut.configuration.hibernate.validator.ValidatorFactoryProvider.validatorFactory(ValidatorFactoryProvider.java:94)
	at io.micronaut.configuration.hibernate.validator.$ValidatorFactoryProvider$ValidatorFactoryDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1282)
	... 78 common frames omitted
```

**Comment by emmanuelbernard** [comment]
I tried and failed at

```
git clone ...
export JAVA_HOME=...rc6/...
export PATH=...
/build-native-image.sh
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not find com.oracle.substratevm:svm:GraalVM-1.0.0-rc6.
  Required by:
      project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
1 actionable task: 1 executed
Error: Could not find or load main class io.micronaut.graal.reflect.GraalClassLoadingAnalyzer
Warning: Invalid classpath entry: build/libs/micronaut-security-jwt-graal-0.1-all.jar
Error: Invalid Path entry build/reflect.json
Caused by: java.nio.file.NoSuchFileException: /Users/emmanuel/Downloads/nobackup/micronaut-security-jwt-graal/build/reflect.json
```

**Comment by emmanuelbernard** [comment]
OK so I guess HV passes, cool :) I would not be concerned about `version null`, we read it from the META-INF or some weird thing like that.

**Comment by Sanne** [comment]
thanks @petenorth , I'll take care of the "null version" - but as Emmanuel mentioned don't worry about it.

**Comment by Sanne** [comment]
Regarding the "null version" issue; Validator prints the version it gets from this code:

    Version.class.getPackage().getImplementationVersion()

its is being null during the build of the `native-image`, in which classloaders are still valid. I think the problem is with how you're building the application: you don't have the original jars from Hibernate Validator as apparently there is some kind of uber-jar produced in `/builds/lib`, so the MANIFEST entries are missing.
