### ISSUE TITLE
No X509TrustManager implementation available in substrate

### ISSUE THREAD

**Issue by pmlopes** [oracle/graal#720]
I'm trying to connect to a remote HTTPS server and get this when my images are built with:

```
--enable-https
--enable-all-security-services
-Djava.library.path=${java.home}/jre/lib/amd64
```

```
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at java.lang.Throwable.<init>(Throwable.java:265)
        at java.lang.Exception.<init>(Exception.java:66)
        at java.io.IOException.<init>(IOException.java:58)
        at javax.net.ssl.SSLException.<init>(SSLException.java:52)
        at javax.net.ssl.SSLHandshakeException.<init>(SSLHandshakeException.java:50)
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:330)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:992)
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:989)
        at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:97)
        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1467)
        at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1435)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1343)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1177)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1221)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
        ... 18 more
Caused by: java.security.cert.CertificateException: No X509TrustManager implementation available
        at java.lang.Throwable.<init>(Throwable.java:265)
        at java.lang.Exception.<init>(Exception.java:66)
        at java.security.GeneralSecurityException.<init>(GeneralSecurityException.java:56)
        at java.security.cert.CertificateException.<init>(CertificateException.java:56)
        at sun.security.ssl.DummyX509TrustManager.checkServerTrusted(SSLContextImpl.java:1198)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1601)
        ... 30 more
```

works fine on graal sdk.

**Comment by cstancu** [comment]
@pmlopes can you share the code to reproduce this? Thanks!

**Comment by pmlopes** [comment]
@cstancu i'll work on reducing it to a small bit, as off the moment it is quite some big app i was experimenting with

**Comment by pmlopes** [comment]
@cstancu actually it was easy to reproduce: https://gist.github.com/pmlopes/5997fb4b4d77075730ddca25e00b2394

**Comment by cstancu** [comment]
Trying to build I get:
```
$ mvn package
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building native-secure-app 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for io.vertx:vertx-core:jar:3.6.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.201 s
[INFO] Finished at: 2018-10-05T14:34:58-07:00
[INFO] Final Memory: 16M/479M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project myapp: Could not resolve dependencies for project com.example:myapp:jar:0.0.1-SNAPSHOT: Could not find artifact io.vertx:vertx-core:jar:3.6.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by pmlopes** [comment]
Sorry, you need to allow snapshots from maven, use this settings.xml https://github.com/pmlopes/openfaas-svm-vertx/blob/develop/template/vertx-svm/settings.xml and just run as:

`mvn --settings settings.xml -Pnative-image`

**Comment by cstancu** [comment]
After a few more struggles I was able to reproduce the issue. Next time please pack the reproducing code as a repo and provide all steps to build and run to make sure we run the same thing. :)

**Comment by cstancu** [comment]
This issue has since been fixed.
