### ISSUE TITLE
[native-image] application packed to image works in different way

### ISSUE THREAD

**Issue by aplut** [oracle/graal#721]
Hi,

I've created a simple app to test native-image as a CLI app. Unfornatelly the same jar file gives different output when started as native-image and when started as simple jar file using `java -jar` command.

Could you please take a look and advice?

I'm using **graalvm-ce-1.0.0-rc7** on **Ubuntu 16.04**.

java:
```
[--help]
Usage: Graal CLI 1.0.0 [options]
  Options:
    -h, --help
      print this help
    status
      check url status
      Default: false
```

native-image:
```
[--help]
Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter '--help' but no main parameter was defined in your arg class
        at java.lang.Throwable.<init>(Throwable.java:265)
        at java.lang.Exception.<init>(Exception.java:66)
        at java.lang.RuntimeException.<init>(RuntimeException.java:62)
        at com.beust.jcommander.ParameterException.<init>(ParameterException.java:34)
        at com.beust.jcommander.JCommander.initMainParameterValue(JCommander.java:936)
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:752)
        at com.beust.jcommander.JCommander.parse(JCommander.java:340)
        at com.beust.jcommander.JCommander.parse(JCommander.java:319)
        at io.pluta.graal.cli.Main.main(Main.java:22)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:163)
```

How to reproduce it:
```
git clone git@github.com:aplut/graalvm-cli.git
cd graalvm-cli
./mvnw clean install
${graalvm_path}/bin/native-image -jar target/graal-cli-1.0.0-SNAPSHOT-jar-with-dependencies.jar
```

```
java -jar target/graal-cli-1.0.0-SNAPSHOT-jar-with-dependencies.jar --help
```

```
./graal-cli-1.0.0-SNAPSHOT-jar-with-dependencies --help
```

Thanks in advance.

Best regards,
Adrian

**Comment by dsyer** [comment]
I don't know how JCommander works, but it probably needs reflective access to your `Args` class. You need to configure that for the native image, e.g. see https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md.

**Comment by jramirez-isc** [comment]
@aplut as @dsyer commented, you need to add the reflection config. You can use the [native-image-agent](https://github.com/oracle/graal/blob/master/substratevm/CONFIGURE.md) to automatically detect the reflectively accessed elements and generate the config files.

After setting up the reflection config, I added a few more options to run `native-image` command with your code:
```
native-image -H:ReflectionConfigurationFiles=config-dir/reflect-config.json -H:ResourceConfigurationFiles=config-dir/resource-config.json --allow-incomplete-classpath --no-fallback -H:+AddAllCharsets --enable-all-security-services -jar target/graal-cli-1.0.0-SNAPSHOT-jar-with-dependencies.jar graalvm-cli
```
Find the full code here: https://github.com/jramirez-isc/graalvm-cli
