### ISSUE TITLE
Native image builds fail using GraalVM built with labsjdk 17 

### ISSUE THREAD

**Issue by roberttoyonaga** [oracle/graal#7212]
**Describe the issue**
As the title says, NI builds fail when using GraalVM built with labsjdk17. Has been happening on master branch for the past few days. LabsJDK 17 version: labsjdk-ce-17.0.8+7-jvmci-23.0-b15-linux-amd64 

See error here: https://gist.github.com/roberttoyonaga/7ea551021096c9a1a00ab3435e9507fa

It seems like the commit that's causing the issue is  https://github.com/oracle/graal/commit/8bd168ee6f2603f3a9a45e183f28b29e1491a614

**Comment by roberttoyonaga** [comment]
Hi @peter-hofer, do you know why this could be happening?

**Comment by zapster** [comment]
As I said [here](https://github.com/oracle/graal/pull/7211#issuecomment-1680086860):

> The next release 23.1 will be JDK 21 only (https://github.com/oracle/graal/issues/6854), so we are gradually dropping support for other version

**Comment by jerboaa** [comment]
Pasting the build failure trace for ref:

```
GraalVM Native Image: Generating 'com.redhat.ni.tester.tester' (executable)...
========================================================================================================================
[1/8] Initializing...                                                                                    (2.4s @ 0.15GB)
 Java version: 17.0.8+7, vendor version: GraalVM CE 17.0.8-dev+7.1
 Graal compiler: optimization level: 2, target machine: x86-64-v3
 C compiler: gcc (redhat, x86_64, 8.5.0)
 Garbage collector: Serial GC (max heap size: 80% of RAM)
 1 user-specific feature(s):
 - com.oracle.svm.thirdparty.gson.GsonFeature
--------------------
Build resources:
 - 26.49GB of memory (42.4% of 62.42GB system memory, determined at start)
 - 16 thread(s) (100.0% of 16 available processor(s), determined at start)
[2/8] Performing analysis...  []                                                                         (0.7s @ 0.24GB)
	  839 reachable types   (45.2% of    1,855 total)
	  472 reachable fields  (26.0% of    1,812 total)
	2,276 reachable methods (33.3% of    6,827 total)
	  255 types,    27 fields, and   103 methods registered for reflection

Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.oracle.svm.core.JavaMainWrapper.runCore0(JavaMainWrapper.java:213) 
Parsing context:
   at com.oracle.svm.core.JavaMainWrapper.doRun(JavaMainWrapper.java:292)
   at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
   at static root method.(Unknown Source)

		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:149)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:184)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:153)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraphInfo(MethodTypeFlow.java:111)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultStaticInvokeTypeFlow.lambda$update$0(DefaultStaticInvokeTypeFlow.java:75)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.LightImmutableCollection.forEach(LightImmutableCollection.java:90)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultStaticInvokeTypeFlow.update(DefaultStaticInvokeTypeFlow.java:74)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:491)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:187)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:171)
		at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
		at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
		at java.base/java.util.concurrent.ForkJoinPool.externalHelpQuiescePool(ForkJoinPool.java:2104)
		at java.base/java.util.concurrent.ForkJoinPool.awaitQuiescence(ForkJoinPool.java:3323)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.complete(CompletionExecutor.java:237)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis.doTypeflow(PointsToAnalysis.java:529)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis.finish(PointsToAnalysis.java:517)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.AbstractAnalysisEngine.runAnalysis(AbstractAnalysisEngine.java:162)
		at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:784)
		at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:593)
		at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:551)
		at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:528)
		at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:710)
		at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:142)
		at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:97)
Caused by: com.oracle.svm.core.util.VMError$HostedError: guarantee failed
		at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:78)
		at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.guarantee(VMError.java:115)
		at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.methodhandles.MethodHandleInvokerRenamingSubstitutionProcessor.lambda$getSubstitution$0(MethodHandleInvokerRenamingSubstitutionProcessor.java:94)
		at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
		at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.methodhandles.MethodHandleInvokerRenamingSubstitutionProcessor.getSubstitution(MethodHandleInvokerRenamingSubstitutionProcessor.java:90)
		at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.methodhandles.MethodHandleInvokerRenamingSubstitutionProcessor.lookup(MethodHandleInvokerRenamingSubstitutionProcessor.java:74)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:217)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:197)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.<init>(AnalysisMethod.java:182)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.PointsToAnalysisMethod.<init>(PointsToAnalysisMethod.java:70)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.PointsToAnalysisFactory.createMethod(PointsToAnalysisFactory.java:35)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.createMethod(AnalysisUniverse.java:453)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:441)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:417)
		at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisMethodHandleAccessProvider.resolveInvokeBasicTarget(AnalysisMethodHandleAccessProvider.java:70)
		at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.nodes.MethodHandleNode.getInvokeBasicTarget(MethodHandleNode.java:214)
		at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.nodes.MethodHandleNode.tryResolveTargetInvoke(MethodHandleNode.java:106)
		at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.nodes.MethodHandleWithExceptionNode.trySimplify(MethodHandleWithExceptionNode.java:74)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.handleMethodHandle(InlineBeforeAnalysisGraphDecoder.java:350)
		at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.processNextNode(GraphDecoder.java:924)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.processNextNode(InlineBeforeAnalysisGraphDecoder.java:344)
		at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:650)
		at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.decode(PEGraphDecoder.java:892)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysis.decodeGraph(InlineBeforeAnalysis.java:76)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:194)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:606)
		at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:167)
		... 23 more
--------------------
						 0.2s (5.0% of total time) in 9 GCs | Peak RSS: 0.77GB | CPU load: 7.49
========================================================================================================================
Finished generating 'com.redhat.ni.tester.tester' in 3.3s.
```

**Comment by christianwimmer** [comment]
Support for JDK 17 was removed in the current master version, so this is a feature and not a bug.

**Comment by jerboaa** [comment]
OK, makes sense. Thanks.
