### ISSUE TITLE
Build failure on Archlinux: Guarantee failed (AnalysisObject.getInstanceFieldTypeStore(AnalysisObject.java:238))

### ISSUE THREAD

**Issue by pekd** [oracle/graal#7242]
**Describe the issue**
Building GraalVM CE from git master fails on Archlinux when generating native images. Running the same build command multiple times occasionally results in a different stack trace, but it still has to do with pointsto analysis and a failed guarantee. Unfortunately I cannot debug this further myself, since I don't have sufficient knowledge of Graal/SVM internals.

The error does not occur when using a significantly older commit like e.g. 324c733f0c215555d7747c43e34c2e8f37f6d03e

**Steps to reproduce the issue**
essentially "build GraalVM CE on JDK 17":
1. git clone https://github.com/graalvm/mx
2. git clone https://github.com/oracle/graal
3. wget https://github.com/graalvm/labs-openjdk-17/releases/download/jvmci-23.0-b15/labsjdk-ce-17.0.8+7-jvmci-23.0-b15-linux-amd64.tar.gz
4. tar xf labsjdk-ce-17.0.8+7-jvmci-23.0-b15-linux-amd64.tar.gz
5. cd graal/vm && ../../mx/mx --java-home ../../labsjdk-ce-17.0.8-jvmci-23.0-b15 --env ce build

**Describe GraalVM and your environment:**
 - GraalVM version: **commit f011d4d056a7ed78fe9669cc38062e6d09c14bed** (this was the latest commit on master at the time)
 - JDK major version: **OpenJDK 64-Bit Server VM (build 17.0.8+7-jvmci-23.0-b15, mixed mode, sharing)**
 - OS: **Archlinux**
 - Architecture: **AMD64**

**More details**
Final lines of the output:
```
[native-image:196879] Build resources:
[native-image:196879]  - 26.49GB of memory (42.3% of 62.64GB system memory, determined at start)
[native-image:196879]  - 8 thread(s) (66.7% of 12 available processor(s), set via '--parallelism=8')
[native-image:196879] [2/8] Performing analysis...  []                                                   (0.9s @ 0.23GB)
[native-image:196879]       869 reachable types   (46.7% of    1,861 total)
[native-image:196879]       410 reachable fields  (22.2% of    1,849 total)
[native-image:196879]     2,121 reachable methods (32.8% of    6,461 total)
[native-image:196879]       233 types,    16 fields, and   103 methods registered for reflection

Error: Guarantee failed
com.oracle.graal.pointsto.util.AnalysisError: Guarantee failed
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.guarantee(AnalysisError.java:178)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.context.object.AnalysisObject.getInstanceFieldTypeStore(AnalysisObject.java:238)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.context.object.AnalysisObject.getInstanceFieldFlow(AnalysisObject.java:223)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.LoadFieldTypeFlow$LoadInstanceFieldTypeFlow.onObservedUpdate(LoadFieldTypeFlow.java:140)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:620)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:491)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:187)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:171)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[native-image:196879] ------------------------------------------------------------------------------------------------------------------------
[native-image:196879]                          0.3s (3.9% of total time) in 9 GCs | Peak RSS: 0.72GB | CPU load: 4.89
[native-image:196879] ========================================================================================================================
[native-image:196879] Finished generating 'native-image' in 6.2s.
```
Another build with exactly the same steps:
```
[libjvmcicompiler:199476] [2/8] Performing analysis...  []                                               (0.9s @ 0.17GB)
[libjvmcicompiler:199476]     1,341 reachable types   (54.1% of    2,480 total)
[libjvmcicompiler:199476]       534 reachable fields  (19.2% of    2,785 total)
[libjvmcicompiler:199476]     2,416 reachable methods (28.7% of    8,417 total)
[libjvmcicompiler:199476]       387 types,    31 fields, and   179 methods registered for reflection

Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.oracle.svm.core.reflect.target.ReflectionMetadataDecoderImpl.parseConstructors(ReflectionMetadataDecoderImpl.java:146)
Parsing context:
   at com.oracle.svm.core.hub.DynamicHub.getDeclaredConstructors0(DynamicHub.java:1619)
   at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
   at com.oracle.svm.core.hub.DynamicHub.getConstructor0(DynamicHub.java:1220)
   at java.lang.Class.newInstance(Class.java:626)
   at java.net.InetAddress.loadImpl(InetAddress.java:1732)
   at java.net.InetAddressImplFactory.create(InetAddress.java:1828)
   at java.net.InetAddress.<clinit>(InetAddress.java:1140)
   at static root method.(Unknown Source)

        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:149)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:184)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:153)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraphInfo(MethodTypeFlow.java:111)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultSpecialInvokeTypeFlow.lambda$onObservedUpdate$0(DefaultSpecialInvokeTypeFlow.java:88)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.LightImmutableCollection.forEach(LightImmutableCollection.java:90)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultSpecialInvokeTypeFlow.onObservedUpdate(DefaultSpecialInvokeTypeFlow.java:87)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:620)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:491)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:187)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:171)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: com.oracle.svm.core.util.VMError$HostedError: guarantee failed
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:78)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.guarantee(VMError.java:115)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.methodhandles.MethodHandleInvokerRenamingSubstitutionProcessor.lambda$getSubstitution$0(MethodHandleInvokerRenamingSubstitutionProcessor.java:94)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.methodhandles.MethodHandleInvokerRenamingSubstitutionProcessor.getSubstitution(MethodHandleInvokerRenamingSubstitutionProcessor.java:90)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.methodhandles.MethodHandleInvokerRenamingSubstitutionProcessor.lookup(MethodHandleInvokerRenamingSubstitutionProcessor.java:74)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:217)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:197)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.<init>(AnalysisMethod.java:182)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.PointsToAnalysisMethod.<init>(PointsToAnalysisMethod.java:70)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.PointsToAnalysisFactory.createMethod(PointsToAnalysisFactory.java:35)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.createMethod(AnalysisUniverse.java:453)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:441)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:417)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisMethodHandleAccessProvider.resolveInvokeBasicTarget(AnalysisMethodHandleAccessProvider.java:70)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.nodes.MethodHandleNode.getInvokeBasicTarget(MethodHandleNode.java:214)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.nodes.MethodHandleNode.tryResolveTargetInvoke(MethodHandleNode.java:106)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.nodes.MethodHandleWithExceptionNode.trySimplify(MethodHandleWithExceptionNode.java:74)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.handleMethodHandle(InlineBeforeAnalysisGraphDecoder.java:350)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.processNextNode(GraphDecoder.java:924)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.processNextNode(InlineBeforeAnalysisGraphDecoder.java:344)
        at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:650)
        at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.decode(PEGraphDecoder.java:892)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysis.decodeGraph(InlineBeforeAnalysis.java:76)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:195)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:621)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:167)
        ... 15 more
[libjvmcicompiler:199476] ------------------------------------------------------------------------------------------------------------------------
[libjvmcicompiler:199476]                         0.2s (3.7% of total time) in 10 GCs | Peak RSS: 0.72GB | CPU load: 5.38
[libjvmcicompiler:199476] ========================================================================================================================
[libjvmcicompiler:199476] Finished generating 'libjvmcicompiler' in 5.1s.
```
It looks like there is some nondeterminism involved.

**Comment by oubidar-Abderrahim** [comment]
Thank you for reaching out about this, we'll take a look into it shortly.

Just to confirm, do you experience this issue with other Linux distributions or only ArchLinux? Could you please share the exact version of ArchLinux used, the output of `uname -a`

Tracked internally on GR 48241

**Comment by pekd** [comment]
Unfortunately I cannot test this on other distros for now since I only have Archlinux systems available at the moment; uname says:
```
Linux norfair 6.1.46-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 16 Aug 2023 19:25:35 +0000 x86_64 GNU/Linux
```

**Comment by petermz** [comment]
I don't think the master branch will build and work properly on JDK17.
Try JDK21

**Comment by christianwimmer** [comment]
As mentioned in the previous comment, JDK 17 is no longer supported with the latest master version (for anything related to the upcoming GraalVM 23.1).
Please try with labsjdk based on JDK 21, and if you still see problems open a new issue.

**Comment by pekd** [comment]
In that case it would be *very* useful if the build process told me that I'm attempting to build GraalVM with an unsupported JDK instead of throwing a "random" runtime exception at native image generation.

**Comment by sempervictus** [comment]
`jdk-openjdk` package does not work either:
```make
`find_java_home': $JAVA_HOME does not seem to point to a JVMCI-enabled JDK (`/usr/lib/jvm/java-21-openjdk/bin/java -version` does not contain 'jvmci') (RuntimeError)
```
nor can i use the graalvm itself...
```make
WARNING: JVM standalone 'RUBY_JAVA_STANDALONE_SVM_JAVA21' misses LibGraal. Make sure that it is part of the main GraalVM distribution
GraalVM cannot be built using a GraalVM as base-JDK ('/usr/lib/jvm/java-21-graalvm').
Please check the value of the 'JAVA_HOME' environment variable, your mx 'env' files, and the documentation of this suite.
```
