### ISSUE TITLE
npm install issue with sqlite3

### ISSUE THREAD

**Issue by cesarhernandezgt** [oracle/graal#731]
Environment:

- OSX: 10.13.6
- graalvm-ee-1.0.0-rc7

Issue Description:
I have a NodeJS app that works fine with NodeJS v10.5.0 and uses sqlite3 ("sqlite3": "^4.0.2") but when I try to install and run the app with GraalVM I get the following error:
```
node app.js
module.js:681
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Native module '/Users/cesar/borrar/comments-api/node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node' is compiled against the original Node.js!
Use '--nodedir=<GraalVMHome>/jre/languages/js' option of 'npm install' (resp. 'node-gyp') for the compilation against Graal-Node.js.
If the native module is downloaded by 'node-pre-gyp' then use also '--build-from-source' option (to force the compilation).
    at Object.<anonymous> (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:8:3)
    at Object.<anonymous> (/Users/cesar/borrar/comments-api/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:652:30)
    at Object.<anonymous> (module.js:663:10)
    at Module.load (module.js:565:32)
```
I tried to both:
`npm  install --nodedir=$GraalVMHome/jre/languages/js`
```
> sqlite3@4.0.2 install /Users/cesar/borrar/comments-api/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
[sqlite3] Success: "/Users/cesar/borrar/comments-api/node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node" is installed via remote
added 162 packages in 37.066s
```

and
`npm  install --nodedir=$GraalVMHome/jre/languages/js --build-from-source`
```
> sqlite3@4.0.2 install /Users/cesar/borrar/comments-api/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
gyp: /Users/cesar/juniverse/software/graalvm-ee-1.0.0-rc7/Contents/Home/bin/jre/languages/js/common.gypi not found (cwd: /Users/cesar/borrar/comments-api/node_modules/sqlite3) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/cesar/juniverse/software/graalvm-ee-1.0.0-rc7/Contents/Home/jre/languages/js/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:124:1)
gyp ERR! stack     at ChildProcess.emit (events.js:156:31)
gyp ERR! stack     at Process.<anonymous> (internal/child_process.js:183:25)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/cesar/juniverse/software/graalvm-ee-1.0.0-rc7/Contents/Home/jre/languages/js/bin/node" "/Users/cesar/juniverse/software/graalvm-ee-1.0.0-rc7/Contents/Home/jre/languages/js/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/cesar/borrar/comments-api/node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/cesar/borrar/comments-api/node_modules/sqlite3/lib/binding/node-v57-darwin-x64" "--napi_version=1" "--node_abi_napi=napi" "--nodedir=/Users/cesar/juniverse/software/graalvm-ee-1.0.0-rc7/Contents/Home/bin/jre/languages/js"
gyp ERR! cwd /Users/cesar/borrar/comments-api/node_modules/sqlite3
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/cesar/juniverse/software/graalvm-ee-1.0.0-rc7/Contents/Home/jre/languages/js/bin/node /Users/cesar/juniverse/software/graalvm-ee-1.0.0-rc7/Contents/Home/jre/languages/js/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/cesar/borrar/comments-api/node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/cesar/borrar/comments-api/node_modules/sqlite3/lib/binding/node-v57-darwin-x64 --napi_version=1 --node_abi_napi=napi --nodedir=/Users/cesar/juniverse/software/graalvm-ee-1.0.0-rc7/Contents/Home/bin/jre/languages/js' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/cesar/borrar/comments-api/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:124:1)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:156:31)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:940:1)
node-pre-gyp ERR! stack     at Process.<anonymous> (internal/child_process.js:183:25)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/Users/cesar/juniverse/software/graalvm-ee-1.0.0-rc7/Contents/Home/jre/languages/js/bin/node" "/Users/cesar/borrar/comments-api/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/cesar/borrar/comments-api/node_modules/sqlite3
node-pre-gyp ERR! node -v v8.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute '/Users/cesar/juniverse/software/graalvm-ee-1.0.0-rc7/Contents/Home/jre/languages/js/bin/node /Users/cesar/juniverse/software/graalvm-ee-1.0.0-rc7/Contents/Home/jre/languages/js/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/cesar/borrar/comments-api/node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/cesar/borrar/comments-api/node_modules/sqlite3/lib/binding/node-v57-darwin-x64 --napi_version=1 --node_abi_napi=napi --nodedir=/Users/cesar/juniverse/software/graalvm-ee-1.0.0-rc7/Contents/Home/bin/jre/languages/js' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cesar/.npm/_logs/2018-10-10T23_40_57_745Z-debug.log
```

But I got the same error when trying `node app.js`

**Comment by cesarhernandezgt** [comment]
I fixed the issue.

**Short answer:** 
I was providing a wrong `--nodedir` path.

**Detailed answer**
The official website instructions and the error code provided by GraalVM CLI are misleading:

The official installation docs state:
```
Linux
export GraalVMHome=/path/to/graalvm

OSX
export GraalVMHome=/path/to/graalvm/Contents/Home
```

but the GraalVM CLI for `node` state:
```
.... Use '--nodedir=<GraalVMHome>/jre/languages/js' ....
```

Clearly, if you subsitute `GraalVMHome` on `<GraalVMHome>` this could result in a wrong path on OSX:
```
/Users/cesar/juniverse/software/graalvm-ee-1.0.0-rc7/Contents/Home/bin/jre/languages/js
```


**Fix**
The correct `--nodedir` path that worked was:
```
/Users/cesar/juniverse/software/graalvm-ee-1.0.0-rc7/Contents/Home/jre/languages/js
```

**Comment by cesarhernandezgt** [comment]
Closed and provided proposal to prevent this kind of issues on  https://github.com/oracle/graal/issues/732

**Comment by Rishi0405** [comment]
I am facing the same issue with "node-sass": "^4.11.0", and the above-mentioned steps are not working
Environment
Ubuntu 18.04, GraalVm CE 19.0.0, Angular6.1.1

I tried npm install --nodedir=<GraalVMHome>/jre/languages/js

I tried with Node V8.10.0, npm 3.5.2, It is working

**Comment by cesarhernandezgt** [comment]
In case this question is still open:
> > The official installation docs state:
> 
> ```
> Linux
> export GraalVMHome=/path/to/graalvm
> 
> OSX
> export GraalVMHome=/path/to/graalvm/Contents/Home
> ```
> 
> Could you, please, tell me where exactly I can find this section? I am not sure what do you mean by "official installation docs". Thank you in advance.

https://www.graalvm.org/docs/graalvm-as-a-platform/implement-language/

![image](https://user-images.githubusercontent.com/1454523/59230392-91de4c00-8b9a-11e9-96f1-947b7d7cbd6c.png)

**Comment by cesarhernandezgt** [comment]
> I am facing the same issue with "node-sass": "^4.11.0", and the above-mentioned steps are not working
> Environment
> Ubuntu 18.04, GraalVm CE 19.0.0, Angular6.1.1
> 
> I tried npm install --nodedir=<GraalVMHome>/jre/languages/js
> 
> I tried with Node V8.10.0, npm 3.5.2, It is working

@Rishi0405 
What is the value for your 
`<GraalVMHome>` ?

**Comment by Rishi0405** [comment]
> > I am facing the same issue with "node-sass": "^4.11.0", and the above-mentioned steps are not working
> > Environment
> > Ubuntu 18.04, GraalVm CE 19.0.0, Angular6.1.1
> > I tried npm install --nodedir=/jre/languages/js
> > I tried with Node V8.10.0, npm 3.5.2, It is working
> 
> @Rishi0405
> What is the value for your
> `<GraalVMHome>` ?
It is
/usr/lib/jvm/graalvm-ce-19.0.0/bin

**Comment by iamstolis** [comment]
> It is /usr/lib/jvm/graalvm-ce-19.0.0/bin

This is a misunderstanding. `GraalVMHome` is the directory where `GraalVM` is installed, i.e., `/usr/lib/jvm/graalvm-ce-19.0.0` in your case. So, the installation should work when you use `--nodedir=/usr/lib/jvm/graalvm-ce-19.0.0/jre/languages/js` option.
