### ISSUE TITLE
Getting `GraalError: failed guarantee` on macOS with AArch64

### ISSUE THREAD

**Issue by TharmiganK** [oracle/graal#7367]
**Describe the issue**

Building a native-image on macOS with AArch64 fails with this error:
```
Fatal error: org.graalvm.compiler.debug.GraalError: failed guarantee: Immediate has to be 21bit signed number.
```

**Steps to reproduce the issue**
1. Download the zip file in this link: https://drive.google.com/file/d/11C_k1obBRrtnylnU7bAtgd9gMznDd8Jl/view?usp=sharing
2. Run `sh build.sh` inside the unzipped directory

**Describe GraalVM and your environment:**
 - GraalVM version: **CE-17.0.8**
 - JDK major version: **17**
 - OS: **macOS Ventura**
 - Architecture: **AArch64**

**More details**
Stacktrace:
```
Fatal error: org.graalvm.compiler.debug.GraalError: failed guarantee: Immediate has to be 21bit signed number. Got value 0x10f54c
        at lir instruction: B15423@768462 org.graalvm.compiler.lir.StandardOp$LabelOp [] = LABEL alignment: 0 numbPhis: 0 label: 1242440
        at method: Object ballerina.http2_tests$test.2.$value$$anonType$_40.$gen$$get$$0046(Strand, BObject, BObject)  [Direct call from Object $value$$anonType$_40.call(Strand, String, Object[])]
        at jdk.internal.vm.compiler/org.graalvm.compiler.debug.GraalError.guarantee(GraalError.java:108)
        at jdk.internal.vm.compiler/org.graalvm.compiler.asm.aarch64.AArch64Assembler$ImmediateOpChecks.validateSigned(AArch64Assembler.java:731)
        at jdk.internal.vm.compiler/org.graalvm.compiler.asm.aarch64.AArch64Assembler.b(AArch64Assembler.java:1305)
        at jdk.internal.vm.compiler/org.graalvm.compiler.asm.aarch64.AArch64MacroAssembler.patchJumpTarget(AArch64MacroAssembler.java:2005)
        at jdk.internal.vm.compiler/org.graalvm.compiler.asm.Label.bind(Label.java:83)
        at jdk.internal.vm.compiler/org.graalvm.compiler.asm.Assembler.bind(Assembler.java:224)
        at jdk.internal.vm.compiler/org.graalvm.compiler.asm.aarch64.AArch64MacroAssembler.bind(AArch64MacroAssembler.java:99)
        at jdk.internal.vm.compiler/org.graalvm.compiler.lir.StandardOp$LabelOp.emitCode(StandardOp.java:171)
        at jdk.internal.vm.compiler/org.graalvm.compiler.lir.asm.CompilationResultBuilder.emitOp(CompilationResultBuilder.java:615)
        at jdk.internal.vm.compiler/org.graalvm.compiler.lir.asm.CompilationResultBuilder.emitBlock(CompilationResultBuilder.java:591)
        at jdk.internal.vm.compiler/org.graalvm.compiler.lir.asm.CompilationResultBuilder.emitLIR(CompilationResultBuilder.java:544)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.graal.aarch64.SubstrateAArch64Backend.emitCode(SubstrateAArch64Backend.java:1260)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.gen.LIRCompilerBackend.emitCode(LIRCompilerBackend.java:223)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.gen.LIRCompilerBackend.emitBackEnd(LIRCompilerBackend.java:90)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.target.Backend.emitBackEnd(Backend.java:292)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:170)
        at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:137)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:1278)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:1226)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:300)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:187)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:171)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by TharmiganK** [comment]
@teshull Any update on this issue?

**Comment by teshull** [comment]
Your issue indeed is due to extremely huge methods which we never encountered before on AArch64. https://github.com/oracle/graal/pull/7441should resolve your issue

**Comment by dsilvasc** [comment]
Any chance this will make it to a GraalVM JDK21 patch release, or is it more likely in the JDK22 release?

**Comment by cmdjulian** [comment]
also happens on linux aarch64

**Comment by metacosm** [comment]
I'm seeing similar errors with 21.0.1 on Apple Silicon:
```java
The build process encountered an unexpected error:

org.graalvm.compiler.debug.GraalError: failed guarantee: Addend has to be 24bit signed number. Got value 0x800000
        at jdk.internal.vm.compiler/org.graalvm.compiler.debug.GraalError.guarantee(GraalError.java:100)
        at org.graalvm.nativeimage.objectfile/com.oracle.objectfile.macho.MachORelocationInfo.write(MachORelocationElement.java:300)
        at org.graalvm.nativeimage.objectfile/com.oracle.objectfile.macho.MachORelocationElement.getOrDecideContent(MachORelocationElement.java:93)
        at org.graalvm.nativeimage.objectfile/com.oracle.objectfile.ObjectFile.bake(ObjectFile.java:1625)
        at org.graalvm.nativeimage.objectfile/com.oracle.objectfile.macho.MachOObjectFile.bake(MachOObjectFile.java:1822)
        at org.graalvm.nativeimage.objectfile/com.oracle.objectfile.ObjectFile.write(ObjectFile.java:1282)
        at org.graalvm.nativeimage.objectfile/com.oracle.objectfile.ObjectFile.lambda$write$5(ObjectFile.java:1274)
        at org.graalvm.nativeimage.objectfile/com.oracle.objectfile.ObjectFile.withDebugContext(ObjectFile.java:1814)
        at org.graalvm.nativeimage.objectfile/com.oracle.objectfile.ObjectFile.write(ObjectFile.java:1273)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImage.write(NativeImage.java:166)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:98)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:741)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:550)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:538)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:720)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:142)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:97)

```

**Comment by chris-hatton** [comment]
Also happens on `17.0.9-graalce`
