### ISSUE TITLE
TruffleCompilerThread cpu usage is high

### ISSUE THREAD

**Issue by CALLEVE** [oracle/graal#7378]
**Describe GraalVM and your environment :**

 - openjdk version "11.0.15" 2022-04-19
   OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 11.0.15+10-jvmci-22.1-b06)
   OpenJDK 64-Bit Server VM GraalVM CE 22.1.0 (build 11.0.15+10-jvmci-22.1-b06, mixed mode, sharing)
 - OS and OS Version: **[Linux version 3.10.0-862.el7.x86_64  ]**
 - Architecture: **[amd64]**
 - The output of `java -Xinternalversion`:

```
-- jvm
-XX:CICompilerCount=12 -XX:ConcGCThreads=3 -XX:+EnableJVMCIProduct -XX:+ExplicitGCInvokesConcurrent -XX:G1ConcRefinementThreads=13 -XX:G1HeapRegionSize=2097152 -XX:GCDrainStackTargetSize=64 -XX:InitialHeapSize=4294967296 -XX:MarkStackSize=4194304 -XX:MaxGCPauseMillis=250 -XX:MaxHeapSize=4294967296 -XX:MaxNewSize=2575302656 -XX:MinHeapDeltaBytes=2097152 -XX:NonNMethodCodeHeapSize=7594288 -XX:NonProfiledCodeHeapSize=163975016 -XX:ProfiledCodeHeapSize=163975016 -XX:ReservedCodeCacheSize=335544320 -XX:+SegmentedCodeCache -XX:ThreadPriorityPolicy=1 -XX:-UnlockExperimentalVMOptions -XX:-UseAOT -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseGCOverheadLimit 

```

**Describe the issue**
TruffleCompilerThread cpu usage is high

**Code snippet or code repository that reproduces the issue**

```
"TruffleCompilerThread-411" Id=411 cpuUsage=99.86% deltaTime=201ms time=13377ms RUNNABLE (in native)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.libgraal.TruffleToLibGraalCalls.doCompile(Native Method)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.libgraal.LibGraalHotSpotTruffleCompiler.doCompile(LibGraalHotSpotTruffleCompiler.java:133)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.compileImpl(GraalTruffleRuntime.java:761)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.doCompile(GraalTruffleRuntime.java:737)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.doCompile(GraalTruffleRuntime.java:716)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.CompilationTask$1.accept(CompilationTask.java:50)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.CompilationTask$1.accept(CompilationTask.java:44)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.CompilationTask.call(CompilationTask.java:225)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.CompilationTask.call(CompilationTask.java:42)
    at java.base@11.0.15/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base@11.0.15/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base@11.0.15/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base@11.0.15/java.lang.Thread.run(Thread.java:829)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.BackgroundCompileQueue$TruffleCompilerThreadFactory$1.run(BackgroundCompileQueue.java:287)
```

TruffleCompilerThread will suddenly occupy a high amount of CPU and last for several minutes. How should I optimize and solve this situation?

![1694170245233](https://github.com/oracle/graal/assets/63762949/56db8611-6fe4-41f4-94f0-e595018b8ea2)

**Comment by oubidar-Abderrahim** [comment]
Hi Thank you for reaching out, could you please use a more recent version of GraalVM and verify if that improved performance?

**Comment by oubidar-Abderrahim** [comment]
Closing this issue for inactivity, if you can verify the issue using Oracle GraalVM for JDK 17, please reopen and share your findings. Thank you
