### ISSUE TITLE
UnsupportedFeatureError with Zipkin

### ISSUE THREAD

**Issue by ilopmar** [oracle/graal#740]
- Clone this repo: https://github.com/ilopmar/micronaut-zipkin-graal. 
- `cd micronaut-zipkin-graal`
- Even if I plan to use Zipkin I've added Jaeger dependency `compile 'io.jaegertracing:jaeger-thrift:0.31.0'` as a workaround for https://github.com/oracle/graal/issues/705
- Use Graalvm rc7
- Build the native image with `./build-native-image.sh`
- Run it:
```
$ ./micronaut-zipkin-graal 
09:58:46.089 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Failed to inject value for parameter [braveTracerConfiguration] of class: io.micronaut.tracing.brave.BraveTracerFactory

Path Taken: new ExecutorServiceInstrumenter([Tracer tracer]) --> new BraveTracerFactory([BraveTracerConfiguration braveTracerConfiguration])
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [braveTracerConfiguration] of class: io.micronaut.tracing.brave.BraveTracerFactory

Path Taken: new ExecutorServiceInstrumenter([Tracer tracer]) --> new BraveTracerFactory([BraveTracerConfiguration braveTracerConfiguration])
	at java.lang.Throwable.<init>(Throwable.java:287)
	at java.lang.Exception.<init>(Exception.java:84)
	at java.lang.RuntimeException.<init>(RuntimeException.java:80)
	at io.micronaut.context.exceptions.BeanContextException.<init>(BeanContextException.java:32)
	at io.micronaut.context.exceptions.DependencyInjectionException.<init>(DependencyInjectionException.java:42)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:981)
	at io.micronaut.tracing.brave.$BraveTracerFactoryDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1282)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1838)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1574)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1554)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:870)
	at io.micronaut.tracing.brave.$BraveTracerFactory$BraveTracerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1282)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1838)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1574)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1554)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:883)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:973)
	at io.micronaut.tracing.instrument.scheduling.$ExecutorServiceInstrumenterDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1282)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2171)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2102)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:751)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:521)
	at io.micronaut.context.DefaultBeanContext.initializeEventListeners(DefaultBeanContext.java:1000)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:1968)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:155)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:138)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:67)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:271)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:257)
	at micronaut.zipkin.graal.Application.main(Application.java:8)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:163)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.tracing.brave.BraveTracerFactory]

Message: Unresolved element found 
Path Taken: new ExecutorServiceInstrumenter([Tracer tracer]) --> new BraveTracerFactory([BraveTracerConfiguration braveTracerConfiguration])
	at java.lang.Throwable.<init>(Throwable.java:287)
	at java.lang.Exception.<init>(Exception.java:84)
	at java.lang.RuntimeException.<init>(RuntimeException.java:80)
	at io.micronaut.context.exceptions.BeanContextException.<init>(BeanContextException.java:32)
	at io.micronaut.context.exceptions.BeanInstantiationException.<init>(BeanInstantiationException.java:50)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1296)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1838)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1574)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1554)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:883)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:973)
	... 28 common frames omitted
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Unresolved element found 
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Error.<init>(Error.java:70)
	at com.oracle.svm.core.jdk.UnsupportedFeatureError.<init>(UnsupportedFeatureError.java:31)
	at com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.unsupportedFeature(VMErrorSubstitutions.java:109)
	at com.oracle.svm.core.snippets.SnippetRuntime.unresolved(SnippetRuntime.java:206)
	at io.micronaut.tracing.brave.BraveTracerConfiguration.<init>(BraveTracerConfiguration.java:70)
	at io.micronaut.tracing.brave.$BraveTracerConfigurationDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1282)
	... 33 common frames omitted
```

**Comment by cstancu** [comment]
@ilopmar the reported issue cannot be reproduced anymore. The `native-image` command requires the `--allow-incomplete-classpath` and ` -Dio.netty.noUnsafe=true` options and the resulting image will behave as expected:
```
$ ./micronaut-zipkin-graal 
18:59:29.661 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 17ms. Server Running: http://localhost:8080
```
```
$ curl  http://localhost:8080
{"_links":{"self":{"href":"/","templated":false}},"message":"Page Not Found"}
```

**Comment by ilopmar** [comment]
Thanks!
