### ISSUE TITLE
[native-image] NullPointerException at sun.security.provider.KeyStoreDelegator.engineLoad

### ISSUE THREAD

**Issue by cypressious** [oracle/graal#741]
I'm trying to build a native image where I use OkHTTP. I'm using graalvm 1.0.0-rc-7 and I'm building the project using a [Dockerfile](https://github.com/cypressious/graal-native-image-test/blob/master/Dockerfile). The native-image step looks like this:

```Dockerfile
RUN native-image -jar native-image-test-all-1.0-SNAPSHOT.jar\
 -H:+JNI \
 -H:+ReportUnsupportedElementsAtRuntime \
 -H:Name=native-image-test\
 --static\
 --enable-all-security-services\
 --enable-https\
 --no-server
```

The compilation finished successfully but at runtime, the app crashes with the following stacktrace:

```
WARNING: The sunec native library could not be loaded.
Exception in thread "main" java.lang.NullPointerException
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:215)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at sun.security.ssl.TrustManagerFactoryImpl.getCacertsKeyStore(TrustManagerFactoryImpl.java:226)
	at sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:50)
	at javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:250)
	at okhttp3.OkHttpClient.systemDefaultTrustManager(OkHttpClient.java:286)
	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:254)
	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:228)
	at de.rakhman.nativeimagetest.MainKt.main(Main.kt:6)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:163)

```

You can reproduce it using the repo from https://github.com/cypressious/graal-native-image-test

**Comment by cstancu** [comment]
This issue is not reproducible anymore.
