### ISSUE TITLE
[native-image] IOTA iri native

### ISSUE THREAD

**Issue by Fabryprog** [oracle/graal#748]
Hello. I am trying to compile iri jar with native image using ubuntu system

I followed this steps:

1. Download iota iri jar from https://github.com/iotaledger/iri/releases/tag/v1.5.5

2. Compile native image with this command

```
native-image -H:+JNI --report-unsupported-elements-at-runtime --rerun-class-initialization-at-runtime=zmq.util.Utils,com.iota.iri.network.Node -jar iri-1.5.5.jar
```
3. Executing error

```
fabry@server:~/iri-native$ ./iri-1.5.5                                             Logging - property 'logging-level' set to: [INFO]
10/19 14:48:15.570 [main] INFO  com.iota.iri.IRI$IRILauncher - Configuration is created using command line args only
10/19 14:48:15.570 [main] INFO  com.iota.iri.IRI$IRILauncher - parsed the following cmd args: []
10/19 14:48:15.570 [main] INFO  com.iota.iri.IRI$IRILauncher - Welcome to IRI 1.5.510/19 14:48:34.954 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Initializing Database Backend...
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.rocksdb.Env.setBackgroundThreads(JII)V [symbol: Java_org_rocksdb_Env_setBackgroundThreads or Java_org_rocksdb_Env_setBackgroundThreads__JII]
        at java.lang.Throwable.<init>(Throwable.java:265)
        at java.lang.Error.<init>(Error.java:70)
        at java.lang.LinkageError.<init>(LinkageError.java:55)
        at java.lang.UnsatisfiedLinkError.<init>(UnsatisfiedLinkError.java:54)
        at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:125)
        at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:54)
        at org.rocksdb.Env.setBackgroundThreads(Env.java)
        at org.rocksdb.Env.setBackgroundThreads(Env.java:55)
        at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.initDB(RocksDBPersistenceProvider.java:438)
        at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.init(RocksDBPersistenceProvider.java:77)
        at com.iota.iri.storage.Tangle.init(Tangle.java:26)
        at com.iota.iri.Iota.init(Iota.java:68)
        at com.iota.iri.IRI$IRILauncher.main(IRI.java:98)
        at com.iota.iri.IRI.main(IRI.java:33)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:163)
10/19 14:48:34.964 [Shutdown Hook] INFO  com.iota.iri.IRI$IRILauncher - Shutting down IOTA node, please hold tight...
Exception in thread "Shutdown Hook" java.lang.UnsatisfiedLinkError: sun.reflect.Reflection.getCallerClass(I)Ljava/lang/Class; [symbol: Java_sun_reflect_Reflection_getCallerClass or Java_sun_reflect_Reflection_getCallerClass__I]
        at java.lang.Throwable.<init>(Throwable.java:265)
        at java.lang.Error.<init>(Error.java:70)
        at java.lang.LinkageError.<init>(LinkageError.java:55)
        at java.lang.UnsatisfiedLinkError.<init>(UnsatisfiedLinkError.java:54)
        at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:125)
        at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:54)
        at sun.reflect.Reflection.getCallerClass(Reflection.java)
        at ch.qos.logback.classic.spi.PackagingDataCalculator.populateFrames(PackagingDataCalculator.java:85)
        at ch.qos.logback.classic.spi.PackagingDataCalculator.calculate(PackagingDataCalculator.java:58)
        at ch.qos.logback.classic.spi.ThrowableProxy.calculatePackagingData(ThrowableProxy.java:142)
        at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:122)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:419)
        at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
        at ch.qos.logback.classic.Logger.error(Logger.java:538)
        at com.iota.iri.IRI$IRILauncher.lambda$shutdownHook$0(IRI.java:117)
        at com.iota.iri.IRI$IRILauncher$$Lambda$687/934815686.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:748)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:475)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:199)
```
Can you help me?

**Comment by cstancu** [comment]
@Fabryprog there seems to be two separate issues. 

First, it looks like you are missing a native library dependency. The ` -H:+JNI` flag that you are using enables you to load the native libraries at run-time with `System.loadLibrary()`. I am not familiar with `rocksDB` but your code seems to be needing the library that contains the implementation for [this native method](https://github.com/facebook/rocksdb/blob/master/java/src/main/java/org/rocksdb/Env.java#L89) which seems to be declared [here](https://github.com/facebook/rocksdb/blob/master/include/rocksdb/env.h#L406). Please read the [JNI documentation](https://github.com/oracle/graal/blob/master/substratevm/JNI.md) for more info on linking native libraries.

Second, it looks like the `logback` library is using a deprecated Java API that we don't support: `sun.reflect.Reflection.getCallerClass(I)Ljava/lang/Class;`. The replacement of that API, i.e., `sun.reflect.Reflection.getCallerClass()Ljava/lang/Class;` always returns `null` on SVM due to [this substitution](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.reflect/src/com/oracle/svm/reflect/target/Target_jdk_internal_reflect_Reflection.java#L37). Sometimes libraries are able to cope with `null` returned by `Reflect.getCallerClass()` but I am not sure about logback. If you [build from source](https://github.com/oracle/graal/tree/master/substratevm#quick-start) you can try adding this substitution to the same file:
```
    @Substitute
    public static Class<?> getCallerClass(int depth) {
        return null;
    }
```
 This might allow you to move forward.

**Comment by Fabryprog** [comment]
Hello @cstancu 

According documentation there are few informations. Can you help me?

I changed my build command but i have an error to link librockdbjni-amd64.so file.

```
native-image  -H:+JNI -H:IncludeResources=/home/fabry/iri-native/clibraries/*.so --report-unsupported-elements-at-runtime --rerun-class-initialization-at-runtime=zmq.util.Utils,com.iota.iri.network.Node --delay-class-initialization-to-runtime=org.rocksdb.RocksDB,org.rocksdb.RocksObject -jar iri-1.5.5.jar
```

**Comment by cstancu** [comment]
@Fabryprog you cannot use `-H:IncludeResources=` for loading native libraries. You need to load the native library  `librockdbjni-linux64.so` at run time using `System.loadLibrary()`: add this to your code on a path reached at run time before the library is used: `System.loadLibrary(rockdbjni-linux64)`. You can add it at the begining of your `main()` function; do not add it in a static initializer as that can be run at image build time.

If you copy `librockdbjni-linux64.so` in the same directory as the resulting native image then `System.loadLibrary()` should find it. If you want to specify a different path where the library can be found, i.e., `/home/fabry/iri-native/clibraries/` in your case, you also need to set `java.library.path` accordingly: add this `System.setProperty("java.library.path", libPath);` before the call to `System.loadLibrary()`.

**Comment by Fabryprog** [comment]
I  put rockdbjni-linux64 into some directory and i resolve it

But now i have another resource error, xio library load using getResourcesAsStream()

https://github.com/xnio/xnio/blob/8a1b9b8a296579d7c2e49a6339fbc74da43f77d5/api/src/main/java/org/xnio/Version.java#L53

I am tring to resove with -H:IncludeResources=".*Version.properties$" without success!

**Comment by cstancu** [comment]
`-H:IncludeResources=".*Version.properties$"` looks good. I will register these resources: `org/xnio/Version.properties` and `org/xnio/nio/Version.properties`. 

You should also use `-H:-UseServiceLoaderFeature` to disable the automatic services processing since that will load types that are referencing missing libraries and lead to a known issue related to incomplete classpaths. 

Using this command ` mx native-image -H:+JNI -H:IncludeResources=".*Version.properties$" -Djava.library.path=/home/fabry/iri-native/clibraries/ --report-unsupported-elements-at-runtime --rerun-class-initialization-at-runtime=zmq.util.Utils,com.iota.iri.network.Node --delay-class-initialization-to-runtime=org.rocksdb.RocksDB,org.rocksdb.RocksObject,io.undertow.protocols.alpn.ALPNManager,org.xnio.Xnio,org.xnio.Version -H:-UseServiceLoaderFeature -jar iri-1.5.5.jar` I was able to build an image of your app. Running it it looks like I am missing some file:
```
$ ./iri-1.5.5 
Logging - property 'logging-level' set to: [INFO]
10/23 12:08:12.469 [main] INFO  com.iota.iri.IRI$IRILauncher - Configuration is created using command line args only
10/23 12:08:12.469 [main] INFO  com.iota.iri.IRI$IRILauncher - parsed the following cmd args: []
10/23 12:08:12.469 [main] INFO  com.iota.iri.IRI$IRILauncher - Welcome to IRI 1.5.5
Exception in thread "main" java.io.FileNotFoundException: /snapshotMainnet.txt
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Exception.<init>(Exception.java:66)
	at java.io.IOException.<init>(IOException.java:58)
	at java.io.FileNotFoundException.<init>(FileNotFoundException.java:64)
	at com.oracle.svm.core.posix.PosixUtils.fileOpen(PosixUtils.java:239)
	at com.oracle.svm.core.posix.Target_java_io_FileInputStream.open(PosixJavaIOSubstitutions.java:461)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at com.iota.iri.SignedFiles.digestFile(SignedFiles.java:57)
	at com.iota.iri.SignedFiles.isFileSignatureValid(SignedFiles.java:16)
	at com.iota.iri.Snapshot.init(Snapshot.java:34)
	at com.iota.iri.Iota.<init>(Iota.java:49)
	at com.iota.iri.IRI$IRILauncher.main(IRI.java:71)
	at com.iota.iri.IRI.main(IRI.java:33)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:164)
```

**Comment by cstancu** [comment]
Regarding ` --report-unsupported-elements-at-runtime`: this option is needed to ignore the image building errors caused by missing libraries that your code references and only report them at runtime iff an execution path that actually uses those libraries is ever taken. If you want to build without the ` --report-unsupported-elements-at-runtime` you can try adding the missing dependencies (e.g., `org/slf4j/impl/StaticLoggerBinder`) but that can lead to other errors due to transitive dependencies.

**Comment by Fabryprog** [comment]
@cstancu to run must extract 3 files from jar:

snapshotMainnet.txt
snapshotMainnet.sig
librockdbjni.....

**Comment by Fabryprog** [comment]
@cstancu i updated graalvm to rc8

Using new parameter now i have another error

```
fabry@server:~/iri-native$ native-image -H:+JNI -H:IncludeResources=".*Version.properties$" -Djava.library.path=/home/fabry/iri-native/clibraries/ --report-unsupported-elements-at-runtime --rerun-class-initialization-at-runtime=zmq.util.Utils,com.iota.iri.network.Node --delay-class-initialization-to-runtime=org.rocksdb.RocksDB,org.rocksdb.RocksObject,io.undertow.protocols.alpn.ALPNManager,org.xnio.Xnio,org.xnio.Version -H:-UseServiceLoaderFeature -jar iri-1.5.5.jar
Build on Server(pid: 30663, port: 45937)*
[iri-1.5.5:30663]    classlist:  14,262.29 ms
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[iri-1.5.5:30663]        (cap):   1,940.65 ms
[iri-1.5.5:30663]        setup:   5,151.00 ms
p[iri-1.5.5:30663]   (typeflow):  22,371.56 ms
[iri-1.5.5:30663]    (objects):  13,996.16 ms
[iri-1.5.5:30663]   (features):     270.84 ms
[iri-1.5.5:30663]     analysis:  37,487.10 ms
[iri-1.5.5:30663]     universe:   1,290.40 ms
[iri-1.5.5:30663]      (parse):   7,322.94 ms
[iri-1.5.5:30663]     (inline):   7,129.34 ms
[iri-1.5.5:30663]    (compile):  31,412.55 ms
[iri-1.5.5:30663]      compile:  48,219.88 ms
[iri-1.5.5:30663]        image:   4,395.43 ms
[iri-1.5.5:30663]        write:     886.40 ms
[iri-1.5.5:30663]      [total]: 111,924.41 ms
fabry@server:~/iri-native$ ./iri-1.5.5                                             Logging - property 'logging-level' set to: [INFO]                                  Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: Unresolved element found                                                                          at java.lang.Throwable.<init>(Throwable.java:265)                                  at java.lang.Error.<init>(Error.java:70)
        at com.oracle.svm.core.jdk.UnsupportedFeatureError.<init>(UnsupportedFeatureError.java:31)
        at com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.unsupportedFeature(VMErrorSubstitutions.java:109)
        at com.oracle.svm.core.snippets.SnippetRuntime.unresolved(SnippetRuntime.java:206)
        at org.xnio.Xnio.doGetInstance(Xnio.java:247)
        at org.xnio.Xnio.getInstance(Xnio.java:187)
        at io.undertow.Undertow.start(Undertow.java:116)
        at com.iota.iri.service.API.init(API.java:144)
        at com.iota.iri.IRI$IRILauncher.main(IRI.java:99)
        at com.iota.iri.IRI.main(IRI.java:33)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:164)
```

**Comment by Peter-B-Kessler** [comment]
@cstancu The file you are not finding is `/snapshotMainnet.txt`, not `./snapshotMainnet.txt`.  I don't know where that difference comes from, but it probably makes a difference.

**Comment by Fabryprog** [comment]
Sorry boys but my pc has brokenup.

To replicate this issue, I'll post a fork project soon as possible

**Comment by nhoughto** [comment]
More as an FYI to those trying to use xnio with `native-image`, you actually need a bit more to make undertow/xnio run, in the above example I don't think execution went far enough to hit these 
problems, working config to start undertow/xnio server for `xnio 3.3.8.Final`:

reflection config
```
[
  {
    "name" : "org.xnio.nio.NioXnioProvider",
    "methods": [
      { "name": "<init>", "parameterTypes": [] }
    ]
  },
  {
    "name" : "io.undertow.server.protocol.http.HttpRequestParser$$generated",
    "methods": [
      { "name": "<init>", "parameterTypes": ["org.xnio.OptionMap"] }
    ]
  }
]
```

cmd
`native-image -cp "..." -H:IncludeResources=".*Version.properties$" -H:IncludeResources="META-INF/services/*.*" -H:-UseServiceLoaderFeature --allow-incomplete-classpath --delay-class-initialization-to-runtime=io.undertow.protocols.alpn.ALPNManager,org.xnio.Xnio,org.xnio.Version,org.xnio.nio.NioXnioProvider,org.xnio.channels.Channels,io.undertow.server.protocol.ajp.AjpServerResponseConduit,io.undertow.server.protocol.ajp.AjpServerRequestConduit -H:ReflectionConfigurationFiles=./reflection-config.json <class>`

**Comment by cstancu** [comment]
@Fabryprog I made some progress on this. Using the `reflection-config.json` from @nhoughto and this command line:
```
native-image -H:IncludeResources="(.*Version.properties$)|(.*snapshotMainnet.*$)" --report-unsupported-elements-at-runtime --allow-incomplete-classpath --rerun-class-initialization-at-runtime=zmq.util.Utils,com.iota.iri.network.Node,org.rocksdb.RocksDB,org.rocksdb.NativeLibraryLoader --delay-class-initialization-to-runtime=io.undertow.protocols.alpn.ALPNManager,org.xnio.Xnio,org.xnio.Version,org.xnio.nio.NioXnioProvider,org.xnio.channels.Channels,io.undertow.server.protocol.ajp.AjpServerResponseConduit,io.undertow.server.protocol.ajp.AjpServerRequestConduit -H:-UseServiceLoaderFeature -H:ReflectionConfigurationFiles=./reflection-config.json -jar target/iri-1.5.5.jar
```
I can build an image from your example code at https://github.com/Fabryprog/iri/blob/iri-native/GraalVM.md.

Then you can run it with
```
./iri-1.5.5 -Djava.library.path=$(pwd)/clibraries/
```
In my case I needed the `librocksdbjni-linux64.so` in `$(pwd)/clibraries/`. You may need a different library depending on your platform.

However, when I run the image now I get a `SEGSEV`:

```
SEGSEV at 0x00007fffbb80a080 in Java_org_rocksdb_Env_setBackgroundThreads () from /home/cdrtz/projects/github/gh-748/iri/clibraries/librocksdbjni-linux64.so
```
Something goes wrong inside the `librocksdbjni`. It probably misses a [JNI config](https://github.com/oracle/graal/blob/master/substratevm/JNI.md#java-native-interface-jni-on-substrate-vm) that exposes some Java classes to native code.
