### ISSUE TITLE
[GR-48883] Broken `-H:+BuildReport` at latest Oracle GraalVM

### ISSUE THREAD

**Issue by sgammon** [oracle/graal#7485]
**Describe the issue**
After upgrading to the latest GVM Java 21 release (Oracle GraalVM), the `-H:+BuildReport` flag throws the following error

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. `git clone https://github.com/elide-dev/elide.git && cd elide`
2. open the `packages/cli/build.gradle.kts` file and flip `enableBuildReport` to `true`
3. run build with `./gradlew :packages:cli:nativeCompile`

**Describe GraalVM and your environment:**
 - GraalVM version: `Oracle GraalVM 21+35.1 (build 21+35-jvmci-23.1-b15)`
 - JDK major version: `21`
 - OS: `macOS Ventura 13.5.1`
 - Architecture: `aarch64` (M2)

```
Fatal error: com.oracle.svm.core.util.VMError$HostedError: Failed to generate build report
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:86)
        at com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.buildreport.a.a(stripped:238)
        at com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.hosted.h.createAdditionalArtifacts(stripped:117)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ProgressReporter.createAdditionalArtifacts(ProgressReporter.java:722)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ProgressReporter.printEpilog(ProgressReporter.java:672)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.reportEpilog(NativeImageGeneratorRunner.java:604)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:596)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:720)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:142)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:97)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "com.oracle.svm.enterprise.buildreport.data.a$a.g()" is null
        at com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.buildreport.data.a.f(stripped:183)
        at com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.buildreport.data.a.e(stripped:176)
        at com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.buildreport.data.a.a(stripped:135)
        at com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.buildreport.data.a.e(stripped:121)
        at com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.buildreport.a$b.a(stripped:187)
        at com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.buildreport.a$b.a(stripped:156)
        at com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.buildreport.a$b.a(stripped:143)
        at com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.buildreport.a$b.a(stripped:152)
        at com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.buildreport.a$b.a(stripped:165)
        at com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.buildreport.a.a(stripped:233)
```

**Comment by fniephaus** [comment]
Hi @sgammon,
is it possible you see this error when there is actually another error stopping the build (e.g., when running with `--strict-image-heap`)? We've [fixed an issue with that recently](https://github.com/oracle/graal/commit/730b19df17d9f863b3d34758aaa629372d2fcc8a) but that fix didn't make it into the 21.0.0 release. I'm backporting it to the release branch so it should land in the next 21 update release soon.

**Comment by sgammon** [comment]
@fniephaus hm, it could certainly be related to other flags, but we _only_ see this one when enabling the `BuildReport` flag in our environment, and the exception seems to be specific to that part of the toolchain:

```
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "com.oracle.svm.enterprise.buildreport.data.a$a.g()" is null
```

But, candidly, I don't know exactly where or why this is failing. We are planning to adjust flags aggressively over the next few days and if I observe any similar error (or observe the flag working) I'll report back

**Comment by sgammon** [comment]
(Also, please forgive that the repro is on a branch -- `feat/gvm-trunk-pt3`. It should be merged soon but if you can't find the `enableBuildReport` flag, that's why)

**Comment by sgammon** [comment]
@fniephaus Will do, thank you! 😄
