### ISSUE TITLE
[native-image] should not reach here with jooby+undertow+others

### ISSUE THREAD

**Issue by asm0dey** [oracle/graal#749]
I'm trying to build native image from this project: https://github.com/asm0dey/school-crm

Build log is following:

```
/usr/lib/jvm/java-8-graal/bin/native-image -jar target/crm-1.5.0.jar
Build on Server(pid: 16916, port: 37973)*
[crm-1.5.0:16916]    classlist:   8,884.80 ms
[crm-1.5.0:16916]        (cap):     776.87 ms
[crm-1.5.0:16916]        setup:   2,364.10 ms
[crm-1.5.0:16916]     analysis:   6,765.95 ms
fatal error: com.oracle.svm.core.util.VMError$HostedError: should not reach here
        at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:62)
        at com.oracle.svm.hosted.SVMHost.dynamicHub(SVMHost.java:205)
        at com.oracle.svm.hosted.analysis.Inflation.checkType(Inflation.java:139)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
        at com.oracle.svm.hosted.analysis.Inflation.checkObjectGraph(Inflation.java:130)
        at com.oracle.graal.pointsto.BigBang.checkObjectGraph(BigBang.java:590)
        at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:562)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:691)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:402)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Processing image build request failed
```

To reproduce you need to perform following steps;

1. `git clone git@github.com:asm0dey/school-crm.git`
1. `cd school-crm`
1. `mvn clean package` (optionally you can add `-Dmaven.test.skip=true` or, vice versa add `verify` to be sure that everything works in your environment (it should), but I'd stuck with default option)
1. call `native-image -jar target/crm-1.5.0.jar`

My env:

```
Apache Maven 3.5.4 (NON-CANONICAL_2018-09-08T01:02:16+02:00_root; 2018-09-08T02:02:16+03:00)
Maven home: /opt/maven
Java version: 1.8.0_172, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-graal/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.18.12-1-manjaro", arch: "amd64", family: "unix"
```
JVM version is graal rc8 ee

**Comment by cstancu** [comment]
This seems to generate the same trace as https://github.com/oracle/graal/issues/754. This problem is caused by trying to build the native image with an incomplete class path, i.e., the app that you are trying to build the image from has some optional library dependencies which you probably don't use. We are currently working on a general solution for these issues and plan to release it in rc9.

**Comment by asm0dey** [comment]
@cstancu thank you for reply! Is there any way do find this dependency?

**Comment by cstancu** [comment]
For your app the missing class seems to be: `org.apache.log4j.Logger` reached from:
```
	at parsing org.jooq.tools.JooqLogger.isInfoEnabled(JooqLogger.java:311)
	at parsing org.jooq.tools.JooqLogger.getLogger(JooqLogger.java:123)
	at parsing org.jooq.tools.jdbc.JDBCUtils.<clinit>(JDBCUtils.java:104)
```

There is no option unfortunately to give you this information, you need to run in debug mode and know where to look or modify the source and catch the exception close to where it happens. What I did was to add:
```
        } catch (Throwable t) {
            t.printStackTrace();
            throw t;
``` 
[just before the `} finally {` in `AnalysisUniverse.createType()`](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.graal.pointsto/src/com/oracle/graal/pointsto/meta/AnalysisUniverse.java#L291). The issue happens when we create a new type and eagerly resolve its dependencies, some of which are missing resulting in a `java.lang.NoClassDefFoundError`.

**Comment by asm0dey** [comment]
@cstancu looks like it makes sense to add this at least until release. Looks like nothing bad can happen because at this place native image is going to crash anyways.

**Comment by asm0dey** [comment]
@cstancu I've added following dependencies to classpath: /tmp/log4j-over-slf4j-1.5.11.jar:/tmp/OSGi_R4_v4.2_core_spec-4.2.0.200908310645.jar:/tmp/janino-3.0.10.jar:/tmp/spring-jdbc-1.2.9.jar:/tmp/spring-beans-4.3.20.RELEASE.jar and got error again:

```
Build on Server(pid: 16249, port: 40151)
[crm-1.5.0:16249]    classlist:   7,084.08 ms
[crm-1.5.0:16249]        (cap):     707.69 ms
[crm-1.5.0:16249]        setup:   1,209.33 ms
[crm-1.5.0:16249]     analysis:   7,582.15 ms
fatal error: com.oracle.svm.core.util.VMError$HostedError: should not reach here
        at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:62)
        at com.oracle.svm.hosted.SVMHost.dynamicHub(SVMHost.java:205)
        at com.oracle.svm.hosted.analysis.Inflation.checkType(Inflation.java:139)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
        at com.oracle.svm.hosted.analysis.Inflation.checkObjectGraph(Inflation.java:130)
        at com.oracle.graal.pointsto.BigBang.checkObjectGraph(BigBang.java:590)
        at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:562)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:691)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:402)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Processing image build request failed
```

**Comment by asm0dey** [comment]
Also I've tried just to create empty `org.apache.log4j.Logger` class and gained the same error

**Comment by asm0dey** [comment]
Closing in favor of #778
