### ISSUE TITLE
Adware? 

### ISSUE THREAD

**Issue by acunniffe** [oracle/graal#758]
I just started trying to use Graal native-image binary on my mac. About 3 min into the build process I was asked by OSX to give Terminal Access to my Photos, Contacts & Calendar. I cancelled the process immediately. 

I run CLI tools all day and I've never seen that before. I don't suspect Graal is doing anything nefarious -- it's likely an unintended side-effect of something else, but it is off-putting.

**Comment by Peter-B-Kessler** [comment]
Where did you get your `native-image` binary from?  Our [Community Edition](https://github.com/oracle/graal/releases) or the [Enterprise Edition](https://www.oracle.com/technetwork/oracle-labs/program-languages/downloads/index.html)? Or did you build your own `native-image` from [the source](https://github.com/oracle/graal)?

What are you building a native image of?  (If you can share.) 

Are you running the built-in `Terminal` app (/Applications/Utilities/Terminal.app), or some variant?

I will try to reproduce your issue if you give me more details.  If you can reproduce the issue, instead of cancelling the native image build, can you poke around and see which process it asking for access?  And if possible get a stack trace for that process.  (E.g., with the Activity Monitor, select the process, and use the gear icon in the tool bar to choose "Sample Process".  Or your favorite CLI process sampler.)

I build native images all day on my Mac, and have never seen anything like that.  I have never seen any code in Graal that would ask for permissions like that.

**Comment by acunniffe** [comment]
Downloaded the community edition
> graalvm-ce-1.0.0-rc8-macos-amd64.tar.gz    md5 2b9b1267b1cdb6668113c820bad57a7d

I was building a native image that contained some JavaFX code. There's a lot of platform specific code that runs when those libraries instantiate, might it be that? Does Graal run anything in my Jar? It hadn't occurred to me that it might be that.  

Built in terminal. 

I've been trying it again, but since I clicked disallow the first time, the build just crashes. So much is happening it's hard for me to track specifically what is breaking, but here's the stacktrace from Graal. 

```
MacBook-Pro-9:~ aidancunniffe$ /Users/aidancunniffe/Downloads/graalvm-ce-1.0.0-rc8/Contents/Home/bin/native-image -jar  /Users/aidancunniffe/Developer/knack/optic-core/cli/jars/server-assembly.jar 
Build on Server(pid: 1171, port: 62213)
[server-assembly:1171]    classlist: 182,411.19 ms
[server-assembly:1171]        (cap):   7,054.38 ms
[server-assembly:1171]        setup:   8,435.83 ms
[server-assembly:1171]     analysis:   1,626.19 ms
fatal error: java.lang.IncompatibleClassChangeError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:419)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:278)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:375)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.executeCompilation(NativeImageBuildServer.java:391)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$processCommand$8(NativeImageBuildServer.java:328)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.withJVMContext(NativeImageBuildServer.java:409)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.processCommand(NativeImageBuildServer.java:325)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.processRequest(NativeImageBuildServer.java:269)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$serve$7(NativeImageBuildServer.java:229)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IncompatibleClassChangeError: com.opticdev.server.http.Lifecycle and com.opticdev.server.http.Lifecycle$delayedInit$body disagree on InnerClasses attribute
	at java.lang.Class.getDeclaringClass0(Native Method)
	at java.lang.Class.getDeclaringClass(Class.java:1235)
	at java.lang.Class.getEnclosingClass(Class.java:1277)
	at jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.getEnclosingType(HotSpotResolvedObjectTypeImpl.java:911)
	at jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.getEnclosingType(HotSpotResolvedObjectTypeImpl.java:60)
	at com.oracle.graal.pointsto.meta.AnalysisType.<init>(AnalysisType.java:175)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:251)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:193)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:170)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:69)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaType0(UniverseMetaAccess.java:91)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaType(UniverseMetaAccess.java:82)
	at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaType(AnalysisMetaAccess.java:48)
	at com.oracle.graal.pointsto.AnalysisObjectScanner.forScannedConstant(AnalysisObjectScanner.java:135)
	at com.oracle.graal.pointsto.ObjectScanner.scanConstant(ObjectScanner.java:225)
	at com.oracle.graal.pointsto.ObjectScanner.scanField(ObjectScanner.java:133)
	at com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:271)
	at com.oracle.graal.pointsto.ObjectScanner.finish(ObjectScanner.java:312)
	at com.oracle.graal.pointsto.ObjectScanner.scanBootImageHeapRoots(ObjectScanner.java:81)
	at com.oracle.graal.pointsto.ObjectScanner.scanBootImageHeapRoots(ObjectScanner.java:63)
	at com.oracle.graal.pointsto.BigBang.checkObjectGraph(BigBang.java:591)
	at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:562)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:691)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:402)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Processing image build request failed

```

**Comment by Peter-B-Kessler** [comment]
Thanks for the details.

Yes, building an image runs all the [static initializers](https://github.com/oracle/graal/blob/master/substratevm/LIMITATIONS.md#static-initializers) for the classes in the built image.  If there are static initializers that request access permissions, that will happen during image building.  If you know what classes are causing the issue, you can delay the static initialization until runtime with the `--delay-class-initialization-to-runtime=` flag, or re-run the static initialization at runtime with the `--rerun-class-initialization-at-runtime=` flag.  See `native-image --help` for somewhat more detail.  If the list of classes is extensive, there is also a programmatic way to delay or re-run static initializers.

I do not know why 
```
com.opticdev.server.http.Lifecycle and com.opticdev.server.http.Lifecycle$delayedInit$body disagree on InnerClasses attribute
```
If you built those classes yourself, you might try cleaning and rebuilding.  If they come from a jar file you use, you might look in the jar file to see why they disagree.

**Comment by acunniffe** [comment]
Got it -- thanks for the help. I'm pretty sure something in JavaFX or another library that binds to mac stuff is triggering those. It's probably just calling static initializers in those dependencies that I never do. Thanks for your help.
