### ISSUE TITLE
[native-image] fatal error: java.lang.reflect.MalformedParameterizedTypeException

### ISSUE THREAD

**Issue by CNAmira** [oracle/graal#759]
I'm trying to build a 'native' Minecraft 1.13.2 server using official jar provided by Mojang, but `native-image` fails.
Here is verbose log, although I don't think it is useful.
```
Build on Server(pid: 9715, port: 52181)
SendBuildRequest [
-task=com.oracle.svm.hosted.NativeImageGeneratorRunner
-imagecp
/Users/alpine/graalvm-ce-1.0.0-rc8/Contents/Home/jre/lib/svm/builder/svm.jar:/Users/alpine/graalvm-ce-1.0.0-rc8/Contents/Home/jre/lib/svm/builder/objectfile.jar:/Users/alpine/graalvm-ce-1.0.0-rc8/Contents/Home/jre/lib/svm/builder/pointsto.jar:/Users/alpine/graalvm-ce-1.0.0-rc8/Contents/Home/jre/lib/jvmci/graal.jar:/Users/alpine/graalvm-ce-1.0.0-rc8/Contents/Home/jre/lib/jvmci/graal-management.jar:/Users/alpine/graalvm-ce-1.0.0-rc8/Contents/Home/jre/lib/jvmci/jvmci-api.jar:/Users/alpine/graalvm-ce-1.0.0-rc8/Contents/Home/jre/lib/jvmci/jvmci-hotspot.jar:/Users/alpine/graalvm-ce-1.0.0-rc8/Contents/Home/jre/lib/boot/graaljs-scriptengine.jar:/Users/alpine/graalvm-ce-1.0.0-rc8/Contents/Home/jre/lib/boot/graal-sdk.jar:/Users/alpine/graalvm-ce-1.0.0-rc8/Contents/Home/jre/lib/svm/library-support.jar:/Users/alpine/Downloads/server/cache:/Users/alpine/Downloads/server/cache/mojang_1.13.2.jar
-H:Path=/Users/alpine/Downloads/server/cache
-H:Class=net.minecraft.server.MinecraftServer
-H:Name=mojang_1.13.2
-H:CLibraryPath=/Users/alpine/graalvm-ce-1.0.0-rc8/Contents/Home/jre/lib/svm/clibraries/darwin-amd64
]
[mojang_1.13.2:9715]    classlist:  11,879.11 ms
[mojang_1.13.2:9715]        (cap):   1,882.19 ms
[mojang_1.13.2:9715]        setup:   7,742.22 ms
[mojang_1.13.2:9715]     analysis:   9,027.38 ms
fatal error: java.lang.reflect.MalformedParameterizedTypeException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:419)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:278)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:375)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.executeCompilation(NativeImageBuildServer.java:391)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$processCommand$8(NativeImageBuildServer.java:328)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.withJVMContext(NativeImageBuildServer.java:409)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.processCommand(NativeImageBuildServer.java:325)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.processRequest(NativeImageBuildServer.java:269)
	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$serve$7(NativeImageBuildServer.java:229)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.MalformedParameterizedTypeException
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.validateConstructorArguments(ParameterizedTypeImpl.java:58)
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.<init>(ParameterizedTypeImpl.java:51)
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.make(ParameterizedTypeImpl.java:92)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeParameterizedType(CoreReflectionFactory.java:105)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:140)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.repository.ClassRepository.getSuperInterfaces(ClassRepository.java:108)
	at java.lang.Class.getGenericInterfaces(Class.java:913)
	at com.oracle.svm.hosted.analysis.Inflation.fillGenericInfo(Inflation.java:284)
	at com.oracle.svm.hosted.analysis.Inflation.checkType(Inflation.java:141)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at com.oracle.svm.hosted.analysis.Inflation.checkObjectGraph(Inflation.java:130)
	at com.oracle.graal.pointsto.BigBang.checkObjectGraph(BigBang.java:590)
	at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:562)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:691)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:402)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Processing image build request failed
```

**Comment by cstancu** [comment]
This error is generated when we call `Class.getGenericInterfaces()` on one of the minecraft classes. I downloaded the `minecraft_server.1.13.2.jar` from https://minecraft.net/en-us/download/server/, run it with `native-image --jar server.jar` and reproduced the same error. Using the `--debug-attach` option and a breakpoint at `com.oracle.svm.hosted.analysis.Inflation.java:284` I can see that the class in question is an interface named `fc` which I guess is a mingled name. This is not a GraalVM problem, but without the source code is hard to diagnose further. You can report this to the minecraft developers. To reproduce you need the `server.jar` and a  simple test class:
```
public class Test {
	public static void main(String[] args) {
		fc.class.getGenericInterfaces();
	}
}
```
Then you can compile and run it with:
```
$ javac -cp .:server.jar Test.java 
$ java -cp .:server.jar Test 
Exception in thread "main" java.lang.reflect.MalformedParameterizedTypeException
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.validateConstructorArguments(ParameterizedTypeImpl.java:58)
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.<init>(ParameterizedTypeImpl.java:51)
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.make(ParameterizedTypeImpl.java:92)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeParameterizedType(CoreReflectionFactory.java:105)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:140)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.repository.ClassRepository.getSuperInterfaces(ClassRepository.java:108)
	at java.lang.Class.getGenericInterfaces(Class.java:913)
	at Test.main(Test.java:3)
```

**Comment by cstancu** [comment]
I closed this issue, feel free to open another one if you run into further problems after this is addressed by the minecraft developers.

**Comment by CNAmira** [comment]
According to [Spigot](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/builddata/browse/mappings/bukkit-1.13.2-cl.csrg) it is `IRegistry` interface.
Decompiled code is 
```java
package net.minecraft.server;

import java.util.Iterator;
import java.util.Random;
import java.util.Set;
import java.util.function.Consumer;
import java.util.stream.Stream;
import java.util.stream.StreamSupport;
import javax.annotation.Nullable;
import org.apache.commons.lang3.Validate;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public interface IRegistry<T> extends Registry<T> {

    Logger e = LogManager.getLogger();
    IRegistry<IRegistry<?>> f = new RegistryMaterials();
    IRegistry<Block> BLOCK = a("block", (IRegistry) (new RegistryBlocks(new MinecraftKey("air"))));
    IRegistry<FluidType> FLUID = a("fluid", (IRegistry) (new RegistryBlocks(new MinecraftKey("empty"))));
    IRegistry<Paintings> MOTIVE = a("motive", (IRegistry) (new RegistryBlocks(new MinecraftKey("kebab"))));
    IRegistry<PotionRegistry> POTION = a("potion", (IRegistry) (new RegistryBlocks(new MinecraftKey("empty"))));
    IRegistry<DimensionManager> DIMENSION_TYPE = a("dimension_type", (IRegistry) (new RegistryMaterials()));
    IRegistry<MinecraftKey> CUSTOM_STAT = a("custom_stat", (IRegistry) (new RegistryMaterials()));
    IRegistry<BiomeBase> BIOME = a("biome", (IRegistry) (new RegistryMaterials()));
    IRegistry<BiomeLayout<?, ?>> BIOME_SOURCE_TYPE = a("biome_source_type", (IRegistry) (new RegistryMaterials()));
    IRegistry<TileEntityTypes<?>> BLOCK_ENTITY_TYPE = a("block_entity_type", (IRegistry) (new RegistryMaterials()));
    IRegistry<ChunkGeneratorType<?, ?>> CHUNK_GENERATOR_TYPE = a("chunk_generator_type", (IRegistry) (new RegistryMaterials()));
    IRegistry<Enchantment> ENCHANTMENT = a("enchantment", (IRegistry) (new RegistryMaterials()));
    IRegistry<EntityTypes<?>> ENTITY_TYPE = a("entity_type", (IRegistry) (new RegistryMaterials()));
    IRegistry<Item> ITEM = a("item", (IRegistry) (new RegistryMaterials()));
    IRegistry<MobEffectList> MOB_EFFECT = a("mob_effect", (IRegistry) (new RegistryMaterials()));
    IRegistry<Particle<? extends ParticleParam>> PARTICLE_TYPE = a("particle_type", (IRegistry) (new RegistryMaterials()));
    IRegistry<SoundEffect> SOUND_EVENT = a("sound_event", (IRegistry) (new RegistryMaterials()));
    IRegistry<StatisticWrapper<?>> STATS = a("stats", (IRegistry) (new RegistryMaterials()));

    static default <T> IRegistry<T> a(String s, IRegistry<T> iregistry) {
        IRegistry.f.a(new MinecraftKey(s), (Object) iregistry);
        return iregistry;
    }

    static default void e() {
        IRegistry.f.forEach((iregistry) -> {
            if (iregistry.d()) {
                IRegistry.e.error("Registry \'{}\' was empty after loading", IRegistry.f.getKey(iregistry));
                if (SharedConstants.b) {
                    throw new IllegalStateException("Registry: \'" + IRegistry.f.getKey(iregistry) + "\' is empty, not allowed, fix me!");
                }
            }

            if (iregistry instanceof RegistryBlocks) {
                MinecraftKey minecraftkey = iregistry.b();

                Validate.notNull(iregistry.get(minecraftkey), "Missing default of DefaultedMappedRegistry: " + minecraftkey, new Object[0]);
            }

        });
    }

    @Nullable
    MinecraftKey getKey(T t0);

    T getOrDefault(@Nullable MinecraftKey minecraftkey);

    MinecraftKey b();

    int a(@Nullable T t0);

    @Nullable
    T fromId(int i);

    Iterator<T> iterator();

    @Nullable
    T get(@Nullable MinecraftKey minecraftkey);

    void a(int i, MinecraftKey minecraftkey, T t0);

    void a(MinecraftKey minecraftkey, T t0);

    Set<MinecraftKey> keySet();

    boolean d();

    @Nullable
    T a(Random random);

    default Stream<T> f() {
        return StreamSupport.stream(this.spliterator(), false);
    }

    boolean c(MinecraftKey minecraftkey);
}
```
where `Registry` is 
```java
package net.minecraft.server;

public interface Registry extends Iterable {}
```
