### ISSUE TITLE
ThreadLocalHandles.popFramesIncluding sporadic ArrayIndexOutOfBoundsException error

### ISSUE THREAD

**Issue by imperatorx** [oracle/graal#7599]
**Describe the issue**
When calling a JNI method (not sure that it matters, but from a virtual thread), sometimes the exception below is thrown. Upon repeated calls, the exception is mostly no longer thrown during the application's runtime, and the method works as expected. On one occasion, every subsequent call to this method yielded an exception.

**Steps to reproduce the issue**
It is hard to reproduce, as it occurs very sporadically, needs FoundationDB native libraries, FoundationDB JNI libraries etc.
1. Install FoundationDB 7.1 server and client packages
2. Install FoundationDB 7.1 jar driver including the JNI lib
3. Make sure native image reflection is configured for FoundationDB classes, including JNI reflection
4. Call transaction.getEstimatedRangeSizeBytes for multiple ranges in a single transaction in multiple forked virtual threads in parallel.
5. Sometimes, the error is thrown once.

These are async methods, and their call is guarded with a lock, so only one thread can call this native method. Exception only occurs in native image

**Describe GraalVM and your environment:**
 - GraalVM version **CE for JDK21** (happened in 19 and Mandrel for JDK 19 too)
 - JDK major version: **21**
 - OS: **Linux and Windows**
 - Architecture: **AMD64**

__Exception__
```
 java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
     at org.graalvm.nativeimage.builder/com.oracle.svm.core.handles.ThreadLocalHandles.popFramesIncluding(ThreadLocalHandles.java:136)
     at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIObjectHandles.popLocalFramesIncluding(JNIObjectHandles.java:229)
     at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIGeneratedMethodSupport.nativeCallEpilogue(JNIGeneratedMethodSupport.java:62)
     at com.apple.foundationdb.FDBTransaction.Transaction_getEstimatedRangeSizeBytes(Native Method)
     at com.apple.foundationdb.FDBTransaction.getEstimatedRangeSizeBytes(FDBTransaction.java:322)
     at com.apple.foundationdb.FDBTransaction.getEstimatedRangeSizeBytes(FDBTransaction.java:330)
```

__Signature of the native method:__
```
private native long Transaction_getEstimatedRangeSizeBytes(long cPtr, byte[] keyBegin, byte[] keyEnd);
```

__native method__:
```
JNIEXPORT jlong JNICALL
Java_com_apple_foundationdb_FDBTransaction_Transaction_1getEstimatedRangeSizeBytes(JNIEnv* jenv,
                                                                                   jobject,
                                                                                   jlong tPtr,
                                                                                   jbyteArray beginKeyBytes,
                                                                                   jbyteArray endKeyBytes) {
	if (!tPtr || !beginKeyBytes || !endKeyBytes) {
		throwParamNotNull(jenv);
		return 0;
	}
	FDBTransaction* tr = (FDBTransaction*)tPtr;

	uint8_t* startKey = (uint8_t*)jenv->GetByteArrayElements(beginKeyBytes, JNI_NULL);
	if (!startKey) {
		if (!jenv->ExceptionOccurred())
			throwRuntimeEx(jenv, "Error getting handle to native resources");
		return 0;
	}

	uint8_t* endKey = (uint8_t*)jenv->GetByteArrayElements(endKeyBytes, JNI_NULL);
	if (!endKey) {
		jenv->ReleaseByteArrayElements(beginKeyBytes, (jbyte*)startKey, JNI_ABORT);
		if (!jenv->ExceptionOccurred())
			throwRuntimeEx(jenv, "Error getting handle to native resources");
		return 0;
	}

	FDBFuture* f = fdb_transaction_get_estimated_range_size_bytes(
	    tr, startKey, jenv->GetArrayLength(beginKeyBytes), endKey, jenv->GetArrayLength(endKeyBytes));
	jenv->ReleaseByteArrayElements(beginKeyBytes, (jbyte*)startKey, JNI_ABORT);
	jenv->ReleaseByteArrayElements(endKeyBytes, (jbyte*)endKey, JNI_ABORT);
	return (jlong)f;
}
```

**Comment by imperatorx** [comment]
I got the exception once from calling a different, very simple JNI method. The only thing I can think of is that the same `ThreadLocalHandles` object is accessed from multiple virtual threads in parallel. Is there a bug/race condition in `FastThreadLocalObject` that results in the virtual thread getting a threadlocal instance belonging to another virtual thread? Or is the `ThreadLocalHandles` instance accessed some other way from multiple threads? The rare occasion of the bug suggests there is a race condition somewhere.

**Comment by elkorchi** [comment]
I am investigating on this one, can you provide a small reproducer ?

**Comment by imperatorx** [comment]
> I am investigating on this one, can you provide a small reproducer ?

Sure:
Reproducer: https://github.com/imperatorx/graalvm-threadlocal-reproducer

The reproducer
 - starts 10 virtual threads
 - and on each virtual thread, it forks 100 virtual threads using the StructuredTaskScope.
 - In each fork (10k forks total) it reads a ThreadLocal variable, writes a ThreadLocal variable, then calls into a FoundationDB native call, when the error might occur.

Steps:
 - Use an RPM based linux instance/container with GraalVM and native tools installed
 - Install https://github.com/apple/foundationdb/releases/download/7.3.27/foundationdb-clients-7.3.27-1.el7.x86_64.rpm
 - Install https://github.com/apple/foundationdb/releases/download/7.3.27/foundationdb-server-7.3.27-1.el7.x86_64.rpm
 - Run build.sh
 - Run run.sh
 - Observe errors printed in the console in less than 10 minutes

I ran it on a 8 core, lightly loaded machine, It might make a difference since this is a suspected concurrency bug. Could also reproduce in Windows with a 16 core mashine with no load. Could not reproduce in OpenJDK.

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
        at demo.Fortune.joinScope(Fortune.java:256)
        at demo.Fortune.loop(Fortune.java:120)
        at demo.Fortune.lambda$background$0(Fortune.java:98)
        at java.base@21.0.2/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
        at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
        at java.base@21.0.2/java.lang.VirtualThread.run(VirtualThread.java:309)
        at java.base@21.0.2/java.lang.VirtualThread$VThreadContinuation$1.run(VirtualThread.java:190)
Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
        at java.base@21.0.2/java.util.concurrent.StructuredTaskScope$ShutdownOnFailure.throwIfFailed(StructuredTaskScope.java:1318)
        at java.base@21.0.2/java.util.concurrent.StructuredTaskScope$ShutdownOnFailure.throwIfFailed(StructuredTaskScope.java:1295)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.Util_java_lang_invoke_MethodHandle.invokeInternal(Target_java_lang_invoke_MethodHandle.java:263)
        at java.base@21.0.2/java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:98)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.MethodHandleIntrinsicImpl.execute(MethodHandleIntrinsicImpl.java:179)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.Util_java_lang_invoke_MethodHandle.invokeInternal(Target_java_lang_invoke_MethodHandle.java:186)
        at java.base@21.0.2/java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:98)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$NamedFunction.invokeWithArguments(LambdaForm.java:96)
        at java.base@21.0.2/java.lang.invoke.LambdaForm.interpretName(LambdaForm.java:959)
        at java.base@21.0.2/java.lang.invoke.LambdaForm.interpretWithArguments(LambdaForm.java:936)
        at java.base@21.0.2/java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:105)
        at java.base@21.0.2/java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:0)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$MH/0x00000007c0f8f400.invoke_MT(LambdaForm$MH)
        at demo.Fortune.joinScope(Fortune.java:254)
        ... 6 more
```

**Comment by imperatorx** [comment]
Sometimes it is even throwing Fatal errors like this:

```
Fatal error: java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 4
    at com.oracle.svm.core.handles.ThreadLocalHandles.pushFrame(ThreadLocalHandles.java:80)
    at com.oracle.svm.core.jni.JNIObjectHandles.pushLocalFrame(JNIObjectHandles.java:221)
    at com.oracle.svm.core.jni.JNIGeneratedMethodSupport.nativeCallPrologue(JNIGeneratedMethodSupport.java:58)
    at java.io.FileOutputStream.writeBytes(FileOutputStream.java:-2)
    at java.io.FileOutputStream.write(FileOutputStream.java:367)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:125)
    at java.io.BufferedOutputStream.implFlush(BufferedOutputStream.java:252)
    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:240)
    at java.io.PrintStream.implWrite(PrintStream.java:645)
    at java.io.PrintStream.write(PrintStream.java:623)
    at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:309)
    at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:405)
    at sun.nio.cs.StreamEncoder.lockedFlushBuffer(StreamEncoder.java:123)
    at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:110)
    at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:192)
    at java.io.PrintStream.implWrite(PrintStream.java:812)
    at java.io.PrintStream.write(PrintStream.java:790)
    at java.io.PrintStream.print(PrintStream.java:1002)
    at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:697)
    at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
    at java.lang.Thread.dispatchUncaughtException(Thread.java:2901)
    at java.lang.VirtualThread.run(VirtualThread.java:311)
    at java.lang.VirtualThread$VThreadContinuation$1.run(VirtualThread.java:190)

Printing instructions (ip=0x0000557d54be854e):
  0x0000557d54be844e: 0x00 0x00 0xc6 0x43 0x2a 0x00 0xc5 0xfa 0x7f 0x43 0x2c 0x48 0x8b 0xc7 0x48 0x8b
  0x0000557d54be845e: 0xfb 0x48 0x8b 0xf0 0x48 0xc7 0xc2 0xff 0xff 0xff 0x7f 0x48 0x89 0x44 0x24 0x10 ....
```

**Comment by kohlschuetter** [comment]
I'm also hitting this for very simple JNI methods, using the latest junixsocket snapshot, which introduces support for VirtualThreads. It has a selftest suite that can be run as a native-image, and now it has a "[MassiveParallelTest](https://github.com/kohlschutter/junixsocket/blob/4923337cf26a3d7f2442871ec5d3f0befd31f5ae/junixsocket-common/src/test/java/org/newsclub/net/unix/domain/MassiveParallelTest.java)", which exercises connections via VirtualThreads.

Notably, these jobs are all executed via `Executors.newVirtualThreadPerTaskExecutor()`, and no project-specific `ThreadLocal`s are used in these cases.

**Comment by kohlschuetter** [comment]
@elkorchi Could this bug be due to a missing `@Uninterruptible` annotation for `getOrCreateLocals` (line 100) (and perhaps createLocals, line 109) in [JNIObjectHandles](https://github.com/oracle/graal/blob/a65ec785e7fecfa58450c0ccc062e3a64f16aca0/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jni/JNIObjectHandles.java#L100)?

Compare for example `getExistingLocals` on [line 116](https://github.com/oracle/graal/blob/a65ec785e7fecfa58450c0ccc062e3a64f16aca0/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jni/JNIObjectHandles.java#L116).

**Comment by peter-hofer** [comment]
@kohlschuetter apologies for the delay. I doubt that `@Uninterruptible` usage is the problem here, but you can test that by deleting the annotation on `JNIGeneratedMethodSupport.boxObjectInLocalHandle`. It's worrying that this happens with virtual threads though because they should not make any difference with JNI handles, suggesting a larger issue. I'll investigate.

**Comment by imperatorx** [comment]
I think the key vector to this is native node calling back to java code through JNI (java -> native -> java), I could not reproduce with simple java -> native calls (such as using the lz4-java library).

**Comment by peter-hofer** [comment]
@imperatorx I was able to reproduce the issue on GraalVM `master`, thank you for the reproducer. I tested with #9053 which fixes several problems in the JNI implementation and have not been able to reproduce this issue (so far). I'll have a closer look.
@kohlschuetter I couldn't reproduce the bug locally with your project's `MassiveParallelTest` with GraalVM CE for JDK 21 and several other GraalVM builds. I tried to modify the test to make it the issue more likely to trigger, but it seems like a rebuild didn't incorporate my local changes. Could it be that the class files are sourced via maven rather than via a local build?

**Comment by peter-hofer** [comment]
I'm fairly confident that the change moving the call of `nativeCallPrologue` to after `nativeCallAddress` in [`JNINativeCallWrapperMethod.buildGraph`](https://github.com/oracle/graal/pull/9053/commits/d9c0aee1a62c8202ae24afa5d3479e14df3b7548#diff-cc6aa56e7fd88c5450ae375773404811d978111bb3feb11b2e96d6feb4e9d494) fixes the issue since with only that difference, I cannot reproduce the failure any longer. I strongly suspect that blocking on the lock in `NativeLibrarySupport.findSymbol` can cause a virtual thread to migrate to a carrier thread which does not have a matching JNI handle frame count or sufficient handle stack size. This is also supported by the observation that this issue triggers early on (when symbols are resolved) or not at all.
