### ISSUE TITLE
Spring Boot Build Failure: InternalFeature defined by [...] unexpectedly failed

### ISSUE THREAD

**Issue by BullyWiiPlaza** [oracle/graal#7604]
**Describe the issue**
When I compile my Spring Boot REST API, I get a build failure close to the end of the native compilation:
```
>The build process encountered an unexpected error:

com.oracle.svm.core.util.VMError$HostedError: InternalFeature defined by com.oracle.svm.hosted.image.NativeImageDebugInfoFeature unexpectedly failed with a(n) java.nio.file.InvalidPathException
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:86)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.handleFeatureError(FeatureHandler.java:287)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:92)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:748)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:554)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:538)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:720)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:142)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:97)
Caused by: java.nio.file.InvalidPathException: Illegal char <<> at index 0: <generated>
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:204)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
        at java.base/java.nio.file.Path.resolve(Path.java:516)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.sources.SourceManager.computePrototypeName(SourceManager.java:155)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.sources.SourceManager.locateSource(SourceManager.java:172)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.sources.SourceManager.findAndCacheSource(SourceManager.java:72)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageDebugInfoProvider$NativeImageDebugFileInfo.<init>(NativeImageDebugInfoProvider.java:162)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageDebugInfoProvider$NativeImageDebugTypeInfo.<init>(NativeImageDebugInfoProvider.java:238)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageDebugInfoProvider$NativeImageDebugInstanceTypeInfo.<init>(NativeImageDebugInfoProvider.java:468)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageDebugInfoProvider.createDebugTypeInfo(NativeImageDebugInfoProvider.java:912)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at org.graalvm.nativeimage.objectfile/com.oracle.objectfile.debugentry.DebugInfoBase.installDebugInfo(DebugInfoBase.java:290)
        at org.graalvm.nativeimage.objectfile/com.oracle.objectfile.pecoff.PECoffObjectFile.installDebugInfo(PECoffObjectFile.java:728)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageDebugInfoFeature.beforeImageWrite(NativeImageDebugInfoFeature.java:113)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$doRun$8(NativeImageGenerator.java:748)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:90)
        ... 6 more
```
Running `vcvars64.bat` also did not help.
**Steps to reproduce the issue**
1. Create a [demo Spring Boot app](https://start.spring.io) exactly like in the image below:
![image](https://github.com/oracle/graal/assets/7620135/daacb07e-1dce-4b02-93e1-e617fdb2243c)
2. Edit the `pom.xml` and add the following `native-maven-plugin` configuration:
```
<configuration>
    <!-- This triggers the exception -->
    <!-- https://graalvm.github.io/native-build-tools/latest/maven-plugin.html -->
    <debug>true</debug>
</configuration>
```
3. On Windows, open the `x64 Native Tools Command Prompt for VS 2022`, navigate to the Spring Boot project folder in CMD and run the native image build command with `mvn native:compile -Pnative`

**Describe GraalVM and your environment:**
 - GraalVM version: graalvm-community-openjdk-21+35.1
 - JDK major version: openjdk 21 2023-09-19
 - OS: Windows 11 Pro
 - Architecture: AMD64

**Comment by fernando-valdez** [comment]
Thanks for sharing a reproducer, I will take a look at it and will let you know if I have any question

**Comment by The-RootCause** [comment]
I'm facing The same issue,

Java 21
MacOS, Macbook M2
Tried GraalVM 21 and GralVM 22 both giving: VMError$HostedError: InternalFeature defined by com.oracle.svm.hosted.image.NativeImageDebugInfoFeature
However with new project it's working fine.

Any updates ?

**Comment by fernando-valdez** [comment]
This should be fixed using the latest version of Spring/GraalVM.
