### ISSUE TITLE
Kotlin on MacOS with ARM64 native images fail with UnsatisfiedLinkError

### ISSUE THREAD

**Issue by nkiesel** [oracle/graal#7607]
Trying to use native-image 17.0.8 2023-07-18 on my ARM64 MacBook for my Kotlin project at https://github.com/nkiesel/CertificateHelper fails.

This is after building a JAR using `./gradlew uber` and then running `native-image -jar ./build/libs/*.jar`. This produces a binary, but executing it results in:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/darwin-aarch64/libjnidispatch.jnilib) not found in resource path ()
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1059)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:1015)
        at com.sun.jna.Native.<clinit>(Native.java:221)
        at com.github.ajalt.mordant.internal.MacosMppImpls.<init>(JnaMppImplsMacos.kt:46)
        at com.github.ajalt.mordant.internal.MppImplKt.<clinit>(MppImpl.kt:98)
        at com.github.ajalt.mordant.terminal.TerminalDetection.isJediTerm(TerminalDetection.kt:143)
        at com.github.ajalt.mordant.terminal.TerminalDetection.isIntellijRunActionConsole(TerminalDetection.kt:169)
        at com.github.ajalt.mordant.terminal.TerminalDetection.detectTerminal(TerminalDetection.kt:16)
        at com.github.ajalt.mordant.terminal.StdoutTerminalInterface.<init>(StdoutTerminalInterface.kt:17)
        at com.github.ajalt.mordant.terminal.Terminal.<init>(Terminal.kt:56)
        at com.github.ajalt.mordant.terminal.Terminal.<init>(Terminal.kt:45)
        at CertificateHelper.<init>(CertificateHelper.kt:147)
        at CertificateHelperKt.main(CertificateHelper.kt:92)
```

Any suggestion what is wrong with my setup?

**Comment by nkiesel** [comment]
Found the solution:
`native-image -H:IncludeResources='com/sun/jna/darwin-aarch64/libjnidispatch.jnilib' -jar ./build/libs/*.jar`
