### ISSUE TITLE
DAP's LoadedSourcesHandler::getPath throws InvalidPathException after debugger attached

### ISSUE THREAD

**Issue by yuxuanchiadm** [oracle/graal#7609]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: 23.1.0
 - CE or EE: EE
 - JDK version: JDK 21
 - OS and OS Version: Windows 10
 - Architecture: amd64
 - The output of `java -Xinternalversion`:
```
Java HotSpot(TM) 64-Bit Server VM (21+35-jvmci-23.1-b15) for windows-amd64 JRE (21+35-jvmci-23.1-b15), built on 2023-09-05T20:06:14Z by "OCIWIN03Buildbot" with MS VC++ 17.1 (VS2022)
```

**Have you verified this issue still happens when using the latest snapshot?**
Yes

**Describe the issue**
When debugging guest code using VSCode through DAP. DAP will try to convert `Source` object from Truffle format into DAP format. It calls `com.oracle.truffle.tools.dap.server.LoadedSourcesHandler::getPath` to get path of guest code and check whether it is readable by polyglot context. But `Soruce::getPath` will looks like `/F:/devdir/graalvm_dap_issue/target/classes/guestcode.js` if gust code is created using URL like `file:/F:/devdir/graalvm_dap_issue/target/classes/guestcode.js` on Windows, which is the path component of URL. And is invalid nio Path.
Also it seems like `sourceReference` will be set if `getPath` determine path is not readable by polyglot context. When polyglot context has no permission to access sourcecode. Will cause vscode to retrive sourcecode using `source` DAP command and open temporary tab to display it instead open actual sourcecode file. Which seems incorrect.

Edit: After some investigation it seems to me that `sourceReference` should only be sent if sourcecode doesn't have host file path. Such as dynamically generated code. Otherwise IDE will not locate sourcecode through `path` in DAP's `Source` object according to https://microsoft.github.io/debug-adapter-protocol/specification#Types_Source

**Code snippet or code repository that reproduces the issue**
https://github.com/yuxuanchiadm/graalvm_dap_issue

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Run `git clone https://github.com/yuxuanchiadm/graalvm_dap_issue`
2. Open project using idea or vscode
3. `mvn compile`
4. Run Main.java
5. Attach debugger from vscode
6. Issue is reproduced

**Expected behavior**
DAP should correctly retrive path and readability of Source

**Additional context**
Stack traces in Details
<details><summary>Details</summary>

```
Exception in thread "main" org.graalvm.polyglot.PolyglotException: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /F:/devdir/graalvm_dap_issue/target/classes/guestcode.js
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:204)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at java.base/java.nio.file.Path.of(Path.java:148)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.FileSystems$DeniedIOFileSystem.parsePath(FileSystems.java:1098)
	at org.graalvm.truffle/com.oracle.truffle.api.LanguageAccessor$LanguageImpl.getTruffleFile(LanguageAccessor.java:487)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.EngineAccessor$EngineImpl.getTruffleFile(EngineAccessor.java:273)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.TruffleInstrument$Env.getTruffleFile(TruffleInstrument.java:862)
	at com.oracle.truffle.tools.dap/com.oracle.truffle.tools.dap.server.LoadedSourcesHandler.getPath(LoadedSourcesHandler.java:219)
	at com.oracle.truffle.tools.dap/com.oracle.truffle.tools.dap.server.LoadedSourcesHandler.from(LoadedSourcesHandler.java:180)
	at com.oracle.truffle.tools.dap/com.oracle.truffle.tools.dap.server.LoadedSourcesHandler.assureLoaded(LoadedSourcesHandler.java:157)
	at com.oracle.truffle.tools.dap/com.oracle.truffle.tools.dap.server.LoadedSourcesHandler.assureLoaded(LoadedSourcesHandler.java:140)
	at com.oracle.truffle.tools.dap/com.oracle.truffle.tools.dap.server.LoadedSourcesHandler.onLoad(LoadedSourcesHandler.java:66)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler.notifySourceLoadedBinding(InstrumentationHandler.java:750)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler.notifySourceLoadedBindings(InstrumentationHandler.java:743)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler$1.accept(InstrumentationHandler.java:126)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler$1.accept(InstrumentationHandler.java:123)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.SourceInstrumentationHandler$AllSourcesNotification.runNotifications(SourceInstrumentationHandler.java:407)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.SourceInstrumentationHandler$SourcesNotificationQueue.process(SourceInstrumentationHandler.java:312)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler$FindSourcesOperation.postVisitNotifications(InstrumentationHandler.java:1622)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler$Visitor.postVisit(InstrumentationHandler.java:2108)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoot(InstrumentationHandler.java:1176)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoot(InstrumentationHandler.java:1119)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler.onLoad(InstrumentationHandler.java:199)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentAccessor$InstrumentImpl.onLoad(InstrumentAccessor.java:206)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedRuntimeSupport.notifyOnLoad(OptimizedRuntimeSupport.java:93)
	at org.graalvm.truffle/com.oracle.truffle.api.nodes.RootNode.setupCallTarget(RootNode.java:422)
	at org.graalvm.truffle/com.oracle.truffle.api.nodes.RootNode.initializeTarget(RootNode.java:402)
	at org.graalvm.truffle/com.oracle.truffle.api.nodes.RootNode.getCallTarget(RootNode.java:389)
	at org.graalvm.js/com.oracle.truffle.js.runtime.builtins.JSFunctionData.ensureInitialized(JSFunctionData.java:390)
	at org.graalvm.js/com.oracle.truffle.js.runtime.builtins.JSFunctionData.getCallTarget(JSFunctionData.java:166)
	at org.graalvm.js/com.oracle.truffle.js.nodes.ScriptNode.fromFunctionData(ScriptNode.java:70)
	at org.graalvm.js/com.oracle.truffle.js.parser.JavaScriptTranslator.translateScript(JavaScriptTranslator.java:143)
	at org.graalvm.js/com.oracle.truffle.js.parser.JavaScriptTranslator.translateScript(JavaScriptTranslator.java:105)
	at org.graalvm.js/com.oracle.truffle.js.parser.JavaScriptTranslator.translateScript(JavaScriptTranslator.java:78)
	at org.graalvm.js/com.oracle.truffle.js.parser.GraalJSEvaluator.parseScript(GraalJSEvaluator.java:252)
	at org.graalvm.js/com.oracle.truffle.js.lang.JavaScriptLanguage.parseScript(JavaScriptLanguage.java:312)
	at org.graalvm.js/com.oracle.truffle.js.lang.JavaScriptLanguage.parse(JavaScriptLanguage.java:214)
	at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$ParsingRequest.parse(TruffleLanguage.java:1190)
	at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage.parse(TruffleLanguage.java:1579)
	at org.graalvm.truffle/com.oracle.truffle.api.LanguageAccessor$LanguageImpl.parse(LanguageAccessor.java:299)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotSourceCache.parseImpl(PolyglotSourceCache.java:94)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotSourceCache$WeakCache.lookup(PolyglotSourceCache.java:222)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotSourceCache.parseCached(PolyglotSourceCache.java:80)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext.parseCached(PolyglotLanguageContext.java:366)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:1683)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextDispatch.eval(PolyglotContextDispatch.java:60)
	at org.graalvm.polyglot.impl.UnnamedToModuleContextDispatchGen.eval(UnnamedToModuleContextDispatchGen.java:61)
	at org.graalvm.polyglot.Context.eval(Context.java:402)
	at Main.main(Main.java:19)
	Suppressed: Attached Guest Language Frames (0)
Internal GraalVM error, please report at https://github.com/oracle/graal/issues/.
```
</details>

**Comment by elkorchi** [comment]
Does this issue still get reproduced with the latest GraalVM for JDK 21 ?

**Comment by elkorchi** [comment]
Closing this ticket for non activity, please reopen if it still reproduce with Latest GraalVM for JDK 21
