### ISSUE TITLE
native-image failure with --enable-all-security-services enabled

### ISSUE THREAD

**Issue by katox** [oracle/graal#763]
Without security security services native-image produces a working program.

With security services enabled it fails with "incompatible with types in state":
```
error: unsupported features in 69 methods
Detailed message:
Error: Parameter 0 of org.postgresql.core.SetupQueryRunner.run(QueryExecutor, String, boolean) has declared type org.postgresql.core.QueryExecutor which is incompatible with types in state: 1TypeMObject<[0x00000D2B0002FAC1:!S:QueryExecutorImpl]>
Call path from entry point to org.postgresql.core.SetupQueryRunner.run(QueryExecutor, String, boolean): 
	at org.postgresql.core.SetupQueryRunner.run(SetupQueryRunner.java:43)
	at org.postgresql.core.v3.ConnectionFactoryImpl.isMaster(ConnectionFactoryImpl.java:745)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:256)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:454)
	at org.postgresql.Driver.access$100(Driver.java:57)
	at org.postgresql.Driver$ConnectThread.run(Driver.java:364)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:142)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:87)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:156)
	at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
```

It might a be a missing (unused) dependency but the compiler doesn't report which one it is.

The repo to reproduce the issue: https://github.com/katox/graal-pg-client

**Comment by katox** [comment]
No longer reproducible with RC12. Fixed!

**Comment by cstancu** [comment]
Thanks for checking back. We made a lot of progress in supporting code with missing dependencies since then, just haven't had a chance to recheck old issues.
