### ISSUE TITLE
epsilon gc, Node implementing Lowerable not handled: 30|SerialWriteBarrier

### ISSUE THREAD

**Issue by Karm** [oracle/graal#7652]
Hello,
There seems to be a regression in native-image compilation of a non-trivial app, e.g. Quarkus app, when `--gc=epsilon` is selected.
I did not manage to reproduce it with a plain public static void main hello world app, but perhaps it's not Quarkus specific. TBD...

# Failure with epsilon gc

The compilation fails with:

```
[2/8] Performing analysis...  [******]                                                                  (10.1s @ 1.02GB)
   10,642 reachable types   (85.7% of   12,412 total)
   15,012 reachable fields  (56.6% of   26,509 total)
   53,215 reachable methods (55.3% of   96,148 total)
    3,434 types,   107 fields, and 3,148 methods registered for reflection
       61 types,    59 fields, and    55 methods registered for JNI access
        4 native libraries: dl, pthread, rt, z
[3/8] Building universe...                                                                               (2.4s @ 1.55GB)
[4/8] Parsing methods...      [*]                                                                        (0.8s @ 1.44GB)
[5/8] Inlining methods...     [***]                                                                      (0.5s @ 1.51GB)
[6/8] Compiling methods...    [**]                                                                       (2.1s @ 0.91GB)

Fatal error: org.graalvm.compiler.debug.GraalError: should not reach here: Node implementing Lowerable not handled: 30|SerialWriteBarrier
	at method: void com.oracle.svm.core.heap.StoredContinuationAccess.fillUninterruptibly(StoredContinuation, CodePointer, Pointer, int)  [Direct call from int StoredContinuationAccess.allocateFromStack(Continuation, Pointer, Pointer, CodePointer, IsolateThread)]
	at jdk.internal.vm.compiler/org.graalvm.compiler.debug.GraalError.shouldNotReachHere(GraalError.java:57)
	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.DefaultJavaLoweringProvider.lower(DefaultJavaLoweringProvider.java:328)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.graal.meta.SubstrateBasicLoweringProvider.lower(SubstrateBasicLoweringProvider.java:149)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.graal.aarch64.SubstrateAArch64LoweringProvider.lower(SubstrateAArch64LoweringProvider.java:66)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.genscavenge.graal.ForcedSerialPostWriteBarrier.lower(ForcedSerialPostWriteBarrier.java:66)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.process(LoweringPhase.java:663)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase$ProcessFrame.preprocess(LoweringPhase.java:551)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.processBlock(LoweringPhase.java:762)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.lower(LoweringPhase.java:295)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:269)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:113)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:434)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:322)
	at jdk.internal.vm.compiler/org.graalvm.compiler.core.phases.BaseTier.run(BaseTier.java:47)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:434)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:322)
	at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:304)
	at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:169)
	at jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:137)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:1307)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:1255)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:305)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:187)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:171)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

# Reproducer quick (amd64)
Using [graalvm-community-jdk-21.0.0_linux-x64_bin.tar.gz](https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-21.0.0/graalvm-community-jdk-21.0.0_linux-x64_bin.tar.gz) and this pre-built Quarkus app [code-with-quarkus-1.0.0-SNAPSHOT-native-image-source-jar.zip](https://github.com/oracle/graal/files/13069854/code-with-quarkus-1.0.0-SNAPSHOT-native-image-source-jar.zip):

On my amd64 CentOS 8 Stream workstation:

```
$ unzip code-with-quarkus-1.0.0-SNAPSHOT-native-image-source-jar.zip
$ /home/karm/X/JDKs/graalvm-community-openjdk-21+35.1/bin/native-image -J-Dlogging.initial-configurator.min-level=500 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Duser.language=en -J-Duser.country=US -J-Dfile.encoding=UTF-8 --features=io.quarkus.runner.Feature,io.quarkus.runtime.graal.DisableLoggingFeature -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -J--add-opens=java.base/java.io=ALL-UNNAMED -J--add-opens=java.base/java.lang.invoke=ALL-UNNAMED -J--add-opens=java.base/java.util=ALL-UNNAMED -H:+UnlockExperimentalVMOptions -H:BuildOutputJSONFile=code-with-quarkus-1.0.0-SNAPSHOT-runner-build-output-stats.json -H:-UnlockExperimentalVMOptions -R:-InstallSegfaultHandler -march=native -R:MaxHeapSize=128m --gc=epsilon -H:+UnlockExperimentalVMOptions -H:+AllowFoldMethods -H:-UnlockExperimentalVMOptions -J-Djava.awt.headless=true --no-fallback --link-at-build-time -H:+UnlockExperimentalVMOptions -H:+ReportExceptionStackTraces -H:-UnlockExperimentalVMOptions -H:-AddAllCharsets --enable-url-protocols=http -H:NativeLinkerOption=-no-pie --enable-monitoring=heapdump -H:+UnlockExperimentalVMOptions -H:-UseServiceLoaderFeature -H:-UnlockExperimentalVMOptions -J--add-exports=org.graalvm.nativeimage/org.graalvm.nativeimage.impl=ALL-UNNAMED --exclude-config io\.netty\.netty-codec /META-INF/native-image/io\.netty/netty-codec/generated/handlers/reflect-config\.json --exclude-config io\.netty\.netty-handler /META-INF/native-image/io\.netty/netty-handler/generated/handlers/reflect-config\.json --bundle-create code-with-quarkus-1.0.0-SNAPSHOT-runner -jar ./code-with-quarkus-1.0.0-SNAPSHOT-native-image-source-jar/code-with-quarkus-1.0.0-SNAPSHOT-runner.jar
```

**Note that if you replace the word `epsilon` with the word `serial` in the aforementioned command, the build completes successfully.**

I originally pursued this issue on my CentOS 9 Stream aarch64 workstation, with GraalVM 9dcc01b90ff built with [labsjdk-ce-21.0.1+12-jvmci-23.1-b22-linux-aarch64](https://github.com/graalvm/labs-openjdk-21/releases/download/jvmci-23.1-b22/labsjdk-ce-21.0.1+12-jvmci-23.1-b22-linux-aarch64.tar.gz). I created two replayable bundles there, in case it helps anyone with the reproducer:

:x: [epsilon-replayable-bundle.nib.zip](https://github.com/oracle/graal/files/13069855/epsilon-replayable-bundle.nib.zip)
:heavy_check_mark: [serial-replayable-bundle.nib.zip](https://karms.biz/tmp/serial-replayable-bundle.nib.zip)

# Reproducer full (aarch64)
The full step reproducer, building the Quarkus app (on my aarch64, CentOS 9 workstation):
```
$ wget https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-21.0.0/graalvm-community-jdk-21.0.0_linux-aarch64_bin.tar.gz
$ tar -xvf graalvm-community-jdk-21.0.0_linux-aarch64_bin.tar.gz
$ cd /tmp
$ export JAVA_HOME=/tmp/graalvm-community-openjdk-21+35.1;export GRAALVM_HOME=${JAVA_HOME};export PATH=${JAVA_HOME}/bin:${PATH}
$ git clone https://github.com/Karm/dev-null.git
$ cd dev-null/qepsilon/
$ ./mvnw package -Dnative
```

Now note that all it takes to make the build pass is switching to `serial` in `src/main/resources/application.properties`

# First occurrence
I attempted to use git bisect to get to the commit that caused this regression and this is the result: 9dcc01b90ff.

e.g. 
```
$ git checkout 9dcc01b90ff
$ export JAVA_HOME=/home/tester/karm/labsjdk-ce-21.0.1-jvmci-23.1-b22
$ cd vm
$ mx --dynamicimports /substratevm,/tools,/sulong --exclude-components=nju,nic,ni,nil,llp --force-bash-launchers=polyglot build
$ export JAVA_HOME=/home/tester/karm/graal666/graal2/sdk/mxbuild/linux-aarch64/GRAALVM_3970A0E3B9_JAVA21_STAGE1/graalvm-3970a0e3b9-java21-24.0.0-dev/;export GRAALVM_HOME=${JAVA_HOME};export PATH=${JAVA_HOME}/bin:${PATH}
```
Note that for the aforementioned Quarkus app reproducer, one needs to remove `--strict-image-heap` for GraalVM versions that don't have it yet, e.g. 9dcc01b90ff. 

```
tester@mandrel2:~/karm/graal (master =|BISECTING)$ git bisect good 7ea250747d1
status: waiting for bad commit, 1 good commit known
tester@mandrel2:~/karm/graal (master =|BISECTING)$ git bisect bad 72fa0d2131a
Bisecting: 258 revisions left to test after this (roughly 8 steps)

...Karm having a coffee break...

tester@mandrel2:~/karm/graal ((9dcc01b90ff...)|BISECTING)$ git bisect bad
9dcc01b90ff7b6ffb95cfedae39a95db675f8fff is the first bad commit
commit 9dcc01b90ff7b6ffb95cfedae39a95db675f8fff
Author: Christian Wimmer <christian.wimmer@oracle.com>
Date:   Wed Sep 6 17:49:57 2023 -0700

    Virtual Threads should not be considered preview in JDK 21

 .../src/com/oracle/svm/core/thread/ContinuationsFeature.java        | 6 ++++--
 1 file changed, 4 insertions(+), 2 deletions(-)
```
i.e. ping @christianwimmer  :smile: 
Might interest: @zakkak  @jerboaa  too.

**Comment by peter-hofer** [comment]
Thanks a lot for your very helpful bug report @Karm! Can you please try changing `HeapImpl.dirtyAllReferencesOf()` so that the condition reads as follows and see if that solves the problem? `if (SubstrateOptions.useRememberedSet() && obj != null) {`

**Comment by Karm** [comment]
@peter-hofer Hello Peter, thx, I can confirm it fixes the build for me. While I have it here, do I open PR & backports or you have it already going on?
