### ISSUE TITLE
Simple Python "import csv" failed to executed

### ISSUE THREAD

**Issue by qidian99** [oracle/graal#7655]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **[e.g. 19.3]**
 - CE or EE: **[e.g.: CE]**
 - JDK version: **[e.g.: JDK8]**
 - OS and OS Version: **[e.g.: macOS Catalina]**
 - Architecture: **[e.g.: amd64]**
 - The output of `java -Xinternalversion`:
```
 **PASTE OUTPUT HERE**
```

mac aarch64 jdk21 23.1.0

**Have you verified this issue still happens when using the latest snapshot?**
Yes

**Describe the issue**
ModuleNotFoundError: No module named 'csv'
        at <python> <module>(Unknown)
        at org.graalvm.polyglot/org.graalvm.polyglot.Context.eval(Context.java:428)

**Code snippet or code repository that reproduces the issue**
```
            String venvExePath = Paths.get("testenv", "bin", "graalpy").toString();

            Context context = Context.newBuilder().allowAllAccess(true).option("python.Executable", venvExePath).build();
            context.eval("python", "import site");
            context.eval("python", "import csv"); // <--- error here
``` 

**Steps to reproduce the issue**

**Expected behavior**

**Additional context**
Add any other context about the problem here. Specially important are stack traces or log output. Feel free to link to gists or to screenshots if necesary
<details><summary>Details</summary>

```
ModuleNotFoundError: No module named 'csv'
        at <python> <module>(Unknown)
        at org.graalvm.polyglot/org.graalvm.polyglot.Context.eval(Context.java:428)
```
</details>

**Comment by qidian99** [comment]
Also tried to execute `import csv` in the python shell, and it works fine. 

csv gives the path to graalpy installation:
```bash
>>> import csv
>>> csv
<module 'csv' from '/***redacted***/graalpy-23.1.0/lib/python3.10/csv.py'>
```

**Comment by elkorchi** [comment]
Can you please confirm which JDK and Graal version you are using : from java `-Xinternalversion` it seems you are using Oracle GraalVM 23.0.2 but just under you mentioned that you are using JDK 21 GraalVM 23.1.0, so which one is correct ?

**Comment by elkorchi** [comment]
I am closing this issue, since the reporter is not responding, and there is no context to the issue
