### ISSUE TITLE
Native image of Apache Httpclient fails with `InvalidAlgorithmParameterException`

### ISSUE THREAD

**Issue by DmPanov** [oracle/graal#768]
### Prerequisites:
* `org.apache.httpcomponents:httpclient:4.5.2`
* `graalvm-ce-1.0.0-rc8`
### How to reproduce:
Build native image of plain call to `https://www.google.com`(see https://github.com/DmPanov/graal-vs-apache-httpclient/blob/master/src/main/java/Main.java) and run it
### How to run example:
```
git clone https://github.com/DmPanov/graal-vs-apache-httpclient.git
cd graal-vs-apache-httpclient
./gradlew run
```
result is exception:
```
Exception in thread "main" javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at java.lang.Throwable.<init>(Throwable.java:265)
        at java.lang.Exception.<init>(Exception.java:66)
        at java.io.IOException.<init>(IOException.java:58)
        at javax.net.ssl.SSLException.<init>(SSLException.java:52)
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1921)
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1904)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1420)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:220)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:139)
        at Main.main(Main.java:37)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:164)

```
What am I doing wrong?

**Comment by maizy** [comment]
@DmPanov  looks like you forget to add some params to native-image. Try to build with `--enable-http --enable-https`, it may help. [more info](https://github.com/oracle/graal/blob/master/substratevm/URL-PROTOCOLS.md).

@cstancu  I've got problems with apache http client too. But with commons-logging initializing.

I've built executable with:
```
native-image -H:Path=... --enable-http --enable-https --enable-url-protocols=http,https --enable-all-security-services -jar ahc-test.jar
```

```
native-image --version
GraalVM Version 1.0.0-rc9
```

Sample reproduce app may be found in AHC docs (use `https://example.com/` for url):
http://hc.apache.org/httpcomponents-client-4.5.x/quickstart.html

or in my code (it's in scala):
https://github.com/maizy/skalka/blob/71580129af29492c840af345c44fdeb59028bc25/ahc-test/src/main/scala/space/maizy/skalka/AhcTestApp.scala#L18-L31

Application crushes at runtime with:
```
Exception in thread "main" org.apache.commons.logging.LogConfigurationException: java.lang.ClassNotFoundException: org.apache.commons.logging.impl.LogFactoryImpl (Caused by java.lang.ClassNotFoundException: org.apache.commons.logging.impl.LogFactoryImpl)
    at java.lang.Throwable.<init>(Throwable.java:265)
    at java.lang.Exception.<init>(Exception.java:66)
    at java.lang.RuntimeException.<init>(RuntimeException.java:62)
    at org.apache.commons.logging.LogConfigurationException.<init>(LogConfigurationException.java:65)
    at org.apache.commons.logging.LogConfigurationException.<init>(LogConfigurationException.java:55)
    at org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1158)
    at org.apache.commons.logging.LogFactory$2.run(LogFactory.java:960)
    at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:62)
    at org.apache.commons.logging.LogFactory.newFactory(LogFactory.java:957)
    at org.apache.commons.logging.LogFactory.getFactory(LogFactory.java:624)
    at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:655)
    at org.apache.http.conn.ssl.DefaultHostnameVerifier.<init>(DefaultHostnameVerifier.java:82)
    at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:955)
    at org.apache.http.impl.client.HttpClients.createDefault(HttpClients.java:56)
    at space.maizy.skalka.AhcTestApp$.main(AhcTestApp.scala:19)
    at space.maizy.skalka.AhcTestApp.main(AhcTestApp.scala)
    at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:164)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.impl.LogFactoryImpl
    at java.lang.Throwable.<init>(Throwable.java:287)
    at java.lang.Exception.<init>(Exception.java:84)
    at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:75)
    at java.lang.ClassNotFoundException.<init>(ClassNotFoundException.java:82)
    at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:51)
    at com.oracle.svm.core.jdk.Target_java_lang_ClassLoader.loadClass(Target_java_lang_ClassLoader.java:127)
    at org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1020)
    ... 11 more
```

How I understand it happens because of dynamic loading of logging adapter in AHC. May you suggest how to fix it.

**Comment by cstancu** [comment]
@maizy Can you please try building with latest master? In https://github.com/oracle/graal/commit/d598be2ab629c68b9e939a11d9d5fda4954fc8cc we introduced a new option: `--allow-incomplete-classpath`. The type resolution errors should be reported at run time when the types are accessed for the first time, instead of during image building. This will be available in rc10.

**Comment by DmPanov** [comment]
@maizy I run native-image with `--enable-https`, see https://github.com/DmPanov/graal-vs-apache-httpclient/blob/master/run.sh.
By the way `ClassNotFoundException: org.apache.commons.logging.impl.LogFactoryImpl` can be fixed in rc8 by using Graal `@Substitute`, see https://github.com/DmPanov/graal-vs-apache-httpclient/blob/master/src/main/java/Main.java

**Comment by maizy** [comment]
Thanks, @DmPanov. You were right.

With substitutions I have the same runtime exception (with `GraalVM Version 1.0.0-rc9`):
```
Exception in thread "main" javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Exception.<init>(Exception.java:66)
	at java.io.IOException.<init>(IOException.java:58)
	at javax.net.ssl.SSLException.<init>(SSLException.java:52)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1903)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1886)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1402)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at space.maizy.skalka.ahctest.AhcTestApp$.main(AhcTestApp.scala:22)
	at space.maizy.skalka.ahctest.AhcTestApp.main(AhcTestApp.scala)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:164)
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.lang.Throwable.<init>(Throwable.java:287)
	at java.lang.Exception.<init>(Exception.java:84)
	at java.lang.RuntimeException.<init>(RuntimeException.java:80)
	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:91)
	at sun.security.validator.Validator.getInstance(Validator.java:181)
	at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)
	at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	... 16 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Exception.<init>(Exception.java:66)
	at java.security.GeneralSecurityException.<init>(GeneralSecurityException.java:56)
	at java.security.InvalidAlgorithmParameterException.<init>(InvalidAlgorithmParameterException.java:64)
	at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
	at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
	at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:89)
	... 28 more
```

I'll try to compile code against graalvm master branch and return with updates.

**Comment by maizy** [comment]
Trying to build agains current master (rc10-dev, dcf3f7c4) on macOS High Sierra 10.13.5, Darwin Kernel Version 17.6.0.

Without `@Substitution` for `org.apache.commons.logging.LogFactory#newFactory` & `org.apache.commons.logging.impl.LogFactoryImpl#discoverLogImplementation` native binary failed at runtime with the same error as in rc9:
```
org.apache.commons.logging.LogConfigurationException: java.lang.ClassNotFoundException: org.apache.commons.logging.impl.LogFactoryImpl
...
```.

With substitutions still failed in initing SSL socket:
```
javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```

**Comment by DmPanov** [comment]
@plutext thank you! Applied in https://github.com/DmPanov/graal-vs-apache-httpclient/commit/553be402370a363131e44c8f8e0a7cff1ca953ce

**Comment by PGoski** [comment]
here is my reflection-config.json file which allows to initialize commons-logging at run time:

[
  {
    "name" : "java.lang.String"
  }
,
  {
    "name" : "java.lang.Thread"
  }
,
  {

    "name" : "org.apache.commons.logging.LogFactory"
  }
,
  {

    "name" : "org.apache.commons.logging.impl.SimpleLog"
  }
]

**Comment by acron0** [comment]
@PGoski this json file, with `-H:ReflectionConfigurationFiles=reflectconfig` didn't work for me
