### ISSUE TITLE
[native-image] fails to generate image in rc9-SNAPSHOT

### ISSUE THREAD

**Issue by katox** [oracle/graal#774]
The latest master build fails to create an image with a stacktrace
```
fatal error: com.oracle.svm.core.util.VMError$HostedError: Objects with relocatable pointers must be immutable
	at com.oracle.svm.core.util.VMError.guarantee(VMError.java:85)
	at com.oracle.svm.hosted.image.NativeImageHeap.choosePartition(NativeImageHeap.java:484)
	at com.oracle.svm.hosted.image.NativeImageHeap.addObjectToBootImageHeap(NativeImageHeap.java:443)
	at com.oracle.svm.hosted.image.NativeImageHeap.addObject(NativeImageHeap.java:263)
	at com.oracle.svm.hosted.image.NativeImageCodeCache.addConstantToHeap(NativeImageCodeCache.java:369)
	at com.oracle.svm.hosted.image.NativeImageCodeCache.addConstantsToHeap(NativeImageCodeCache.java:356)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:887)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:402)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image building with exit status 1
```
I ran into it on a fairly large program and so far I haven't been able to slim it down. But it seems to have something to do with JNI
![screenshot from 2018-11-02 18-23-01](https://user-images.githubusercontent.com/287639/47955798-7b856780-df9d-11e8-9f59-2a4416e81ac9.png).

**Comment by katox** [comment]
I tried **RC8** native-image and it produced a binary which segfaulted on run attempt:
```
Logging level set to INFO
2018-11-16T21:24:46 INFO com.zaxxer.hikari.HikariDataSource <init> HikariPool-1 - Starting...
[ [ SubstrateSegfaultHandler caught signal 11 ] ]

General Purpose Register Set Values: 

  RAX 00007ff50d5ff620
  RBX 00007ff50d5fe200
  RCX 0000000000000001
  RDX 0000000000000031
  RBP 00007ff50e1a66f0
  RSI 00007ff50e1a7ba1
  RDI 00007ff50d5fe200
  RSP 00007ff50d5fdcb0
  R8  00007ff50e1a7bb4
  R9  0000000000000000
  R10 0000000000000005
  R11 00007ff50e500890
  R12 00007ff50d5fe200
  R13 00007ff50d5ff620
  R14 0000000000000000
  R15 00007ff50d5fe5df
  EFL 0000000000010203
  RIP 00007ff50db71448
  

JavaFrameAnchor dump:

  Anchor 000001056ce3a000 LastJavaSP fish: “./program” terminated by signal SIGSEGV (Address boundary error)

```
So it seems to prevent an error in produced db-related code.

**Comment by bradnewman** [comment]
I may be a little late to the party (it's not immediately obvious @christianwimmer's commit resolves this issue or not - it's still open) , but I have a relatively small reproducer for this that I can share:

https://github.com/bradnewman/graal-774-repro

It fails with the `Objects with relocatable pointers must be immutable` error when using GraalVM RC9 and RC10, but produces a working binary with RC8.

**Comment by katox** [comment]
No, the original issue is still present on RC11.

**Comment by katox** [comment]
@bradnewman graal-774-repro fails with the latest master build as well.

**Comment by peter-hofer** [comment]
We have introduced more fixes for this in 3313858 and 4839d47, can you please try again with master?

**Comment by bradnewman** [comment]
@peter-hofer Sorry for the delay - I've tested with 528ece0 using graal-774-repro and no longer receive the `Objects with relocatable pointers must be immutable` error - instead, it produced a working binary as with RC8.  Awesome, thanks!

Though, I feel I should note that I can't speak for @katox's or his application.

**Comment by peter-hofer** [comment]
Thank you @bradnewman! I'll close this then. @katox, feel free to reopen if you still encounter this bug.

**Comment by katox** [comment]
@peter-hofer Whitelisting immutable classes fixed the problem. I just verified the original repo as well. It works. Thank you!
