### ISSUE TITLE
[WASM] Defining imports throws error

### ISSUE THREAD

**Issue by Oliver-makes-code** [oracle/graal#7756]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: 23.1.0
 - CE or EE: CE
 - JDK version: 18
 - OS and OS Version: Kubuntu 22.04
 - Architecture: amd64
 - The output of `java -Xinternalversion`:
```
OpenJDK 64-Bit Server VM (18.0.2+9-FR) for linux-amd64 JRE (18.0.2+9-FR), built on Jul 15 2022 19:39:41 by "jenkins" with gcc 7.3.1 20180303 (Red Hat 7.3.1-5)
```

**Have you verified this issue still happens when using the latest snapshot?**
You can find snapshot builds here: https://github.com/graalvm/graalvm-ce-dev-builds/releases
n/a

**Describe the issue**
A clear and concise description of the issue.

**Code snippet or code repository that reproduces the issue**
```kt
fun main() {
    val bytes = File("./test.wasm").readBytes()

    val contextBuilder = Context.newBuilder("wasm").allowAllAccess(true)
    val sourceBuilder = Source.newBuilder("wasm", ByteSequence.create(bytes), "test")
    val source = sourceBuilder.build()
    val context = contextBuilder.build()

    val module = context.eval(source)
    
    module.putMember("env", Env)
}

object Env {
    @Export
    fun get_value(): Int = 8
}
```

(rust module)
```rs
extern "C" {
  fn get_value() -> i32;
}

#[no_mangle]
pub extern "C" fn test() -> i32 {
  unsafe {return get_value() + 42}
}
```

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. build the rust module described for a wasm32-unknown-unknown
2. create a kotlin project with the following code
3. run the kotlin program

**Expected behavior**
It creates doesn't crash

**Additional context**
It worked fine without the module imports

```kt
Exception in thread "main" The module 'env', referenced by the import 'get_value' in the module 'main', does not exist.
	at org.graalvm.polyglot.Value.putMember(Value.java:829)
	at de.olivermakesco.graal_wasm_test.MainKt.main(main.kt:22)
	at de.olivermakesco.graal_wasm_test.MainKt.main(main.kt)
```

**Comment by elkorchi** [comment]
@Oliver-makes-code Can you please check if it still reproduce with GraalVM for JDK 21 ?

**Comment by Burkino** [comment]
I'm having the same issue.
Java host:
```java
import java.io.IOException;

import org.graalvm.polyglot.*;
import org.graalvm.polyglot.proxy.ProxyExecutable;

public class Main {
    public static void main(String[] args) throws IOException {
        Context context = Context.newBuilder("wasm")
                .allowAllAccess(true)
                .option("wasm.Builtins", "wasi_snapshot_preview1").build();
        Source source = Source.newBuilder("wasm", Main.class.getResource("rust_guest.wasm")).build();
        // context.getPolyglotBindings().putMember("get_number", (ProxyExecutable) (_args) -> {
        //     return 99;
        // });

        Value result = context.eval(source);
        
        result.putMember("get_number", (ProxyExecutable) (_args) -> {
            return 99;
        });

        Value mainFunc = result.getMember("main");

        mainFunc.executeVoid();
    }
}
```
Rust guest:
```wit
package computer:host;

world host {
  import get-number: func() -> s32;
  export main: func();
}
```
```rust
wit_bindgen::generate!({
    world: "host"
});

struct MyStruct;
impl Guest for MyStruct {
    fn main() {
        println!("Running Rust with Wasm");
        println!("Number: {}", get_number());
    }
}
export!(MyStruct);
```
Error:
```java
Exception in thread "main" The module '$root', referenced by the import 'get-number' in the module 'rust_guest.wasm', does not exist.
        at org.graalvm.polyglot.Value.putMember(Value.java:878)
        at Main.main(Main.java:18)
```
