### ISSUE TITLE
com.oracle.svm.core.jdk.UnsupportedFeatureError

### ISSUE THREAD

**Issue by tjeske** [oracle/graal#785]
How can I resolve the following problem?
```
        at java.lang.Throwable.<init>(Throwable.java:265)
        at java.lang.Error.<init>(Error.java:70)
        at com.oracle.svm.core.jdk.UnsupportedFeatureError.<init>(UnsupportedFeatureError.java:31)
        at com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.unsupportedFeature(VMErrorSubstitutions.java:109)
        at com.oracle.svm.core.snippets.SnippetRuntime.unresolved(SnippetRuntime.java:206)
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:357)
```
TerminalBuilder.java:357 is  `Pty pty = load(JnaSupport.class).current();`

and load() is defined as
```
    private <S> S load(Class<S> clazz) {
        return ServiceLoader.load(clazz, clazz.getClassLoader()).iterator().next();
    }
```

**Comment by cstancu** [comment]
Can you provide steps to reproduce? The call to `SnippetRuntime.unresolved()` is usually intrinsified into the image when we discover references to missing classes/methods/fields. However, this behavior has recently changed and it should give better error messages. You can [build a VM distribution from source](https://github.com/oracle/graal/tree/master/vm) (make sure to include `substratevm` to get the `native-image` tool).

**Comment by tjeske** [comment]
I have tried to build graal from source but it failed (`Imported suite 'sulong' not found (binary or source).`). Anyway, here is a minimal working example to reproduce the problem.

```
package main;

import org.jline.terminal.Terminal;
import org.jline.terminal.TerminalBuilder;
import java.io.IOException;

public class HelloWorld {

    public static void main(String[] args) {
        try {
            Terminal terminal = TerminalBuilder.builder().dumb(true).build();
        } catch(IOException ignored) {
        }
    }
}
```
and here the corresponding build.gradle file

```
plugins {
  id "com.palantir.graal" version "0.2.0-3-g7f884ba"
}

repositories {
    jcenter()
}

apply plugin: "com.palantir.graal"
apply plugin: 'java'

graal {
    mainClass 'main.HelloWorld'
    outputName 'hello'
    graalVersion '1.0.0-rc9'
    option '--verbose'
    option '--report-unsupported-elements-at-runtime'
}

dependencies {
    compile group: 'org.jline', name: 'jline', version: '3.9.0'
}
```

output
```
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: Unresolved element found
        at java.lang.Throwable.<init>(Throwable.java:265)
        at java.lang.Error.<init>(Error.java:70)
        at com.oracle.svm.core.jdk.UnsupportedFeatureError.<init>(UnsupportedFeatureError.java:31)
        at com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.unsupportedFeature(VMErrorSubstitutions.java:109)
        at com.oracle.svm.core.snippets.SnippetRuntime.unresolved(SnippetRuntime.java:206)
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:357)
        at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:262)
        at main.HelloWorld.main(HelloWorld.java:11)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:164)
```

**Comment by cstancu** [comment]
This issue is now fixed. As of https://github.com/oracle/graal/commit/345567b0db51c0266334f6c7a4cc3bfd695359fb (which will be included in RC13) you should be able to build an image for the simple example above. You also need  the `-H:IncludeResources="org/jline/utils/*.*" ` option to include the resources in the native image.

**Comment by galderz** [comment]
@tjeske Had the same build issue. I didn't have sulong pre-built, but now that sulong is part of the graal repo, I just made the changes [here](https://github.com/oracle/graal/pull/1638) and it seemed to have worked.
