### ISSUE TITLE
Cannot invoke "com.oracle.truffle.api.debug.Debugger.getInstrumenter()" because "this.debugger" is null

### ISSUE THREAD

**Issue by chenjie100** [oracle/graal#7886]
OS Name:Windows 10
Java VM Version: 17.0.8+9-LTS-jvmci-23.0-b14
 org.graalvm.polyglot.PolyglotException: java.lang.NullPointerException: Cannot invoke "com.oracle.truffle.api.debug.Debugger.getInstrumenter()" because "this.debugger" is null
	at org.graalvm.truffle/com.oracle.truffle.api.debug.Breakpoint.install(Breakpoint.java:556)
	at org.graalvm.truffle/com.oracle.truffle.api.debug.Breakpoint.install(Breakpoint.java:545)
	at org.graalvm.truffle/com.oracle.truffle.api.debug.DebuggerSession.install(DebuggerSession.java:904)
	at org.graalvm.truffle/com.oracle.truffle.api.debug.DebuggerSession.install(DebuggerSession.java:892)
	at com.oracle.truffle.tools.chromeinspector.BreakpointsHandler.lambda$createURLBreakpoint$0(BreakpointsHandler.java:98)
	at com.oracle.truffle.tools.chromeinspector.ScriptsHandler.assureLoaded(ScriptsHandler.java:167)
	at com.oracle.truffle.tools.chromeinspector.ScriptsHandler.assureLoaded(ScriptsHandler.java:138)
	at com.oracle.truffle.tools.chromeinspector.ScriptsHandler.onLoad(ScriptsHandler.java:221)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler.notifySourceLoadedBinding(InstrumentationHandler.java:750)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler.notifySourceLoadedBindings(InstrumentationHandler.java:743)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler$1.accept(InstrumentationHandler.java:126)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler$1.accept(InstrumentationHandler.java:123)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.SourceInstrumentationHandler$AllSourcesNotification.runNotifications(SourceInstrumentationHandler.java:407)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.SourceInstrumentationHandler$SourcesNotificationQueue.process(SourceInstrumentationHandler.java:312)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler$FindSourcesOperation.postVisitNotifications(InstrumentationHandler.java:1622)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler$Visitor.postVisit(InstrumentationHandler.java:2108)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoot(InstrumentationHandler.java:1176)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoot(InstrumentationHandler.java:1119)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler.onLoad(InstrumentationHandler.java:199)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentAccessor$InstrumentImpl.onLoad(InstrumentAccessor.java:205)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalRuntimeSupport.notifyOnLoad(GraalRuntimeSupport.java:77)
	at org.graalvm.truffle/com.oracle.truffle.api.nodes.RootNode.setupCallTarget(RootNode.java:422)
	at org.graalvm.truffle/com.oracle.truffle.api.nodes.RootNode.initializeTarget(RootNode.java:402)
	at org.graalvm.truffle/com.oracle.truffle.api.nodes.RootNode.getCallTarget(RootNode.java:389)
	at com.oracle.truffle.js.runtime.builtins.JSFunctionData.ensureInitialized(JSFunctionData.java:387)
	at com.oracle.truffle.js.runtime.builtins.JSFunctionData.getCallTarget(JSFunctionData.java:167)
	at com.oracle.truffle.js.nodes.ScriptNode.fromFunctionData(ScriptNode.java:70)
	at com.oracle.truffle.js.parser.JavaScriptTranslator.translateScript(JavaScriptTranslator.java:143)
	at com.oracle.truffle.js.parser.JavaScriptTranslator.translateScript(JavaScriptTranslator.java:105)
	at com.oracle.truffle.js.parser.JavaScriptTranslator.translateScript(JavaScriptTranslator.java:78)
	at com.oracle.truffle.js.parser.GraalJSEvaluator.parseScript(GraalJSEvaluator.java:246)
	at com.oracle.truffle.js.lang.JavaScriptLanguage.parseScript(JavaScriptLanguage.java:311)
	at com.oracle.truffle.js.lang.JavaScriptLanguage.parse(JavaScriptLanguage.java:213)
	at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$ParsingRequest.parse(TruffleLanguage.java:1000)
	at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage.parse(TruffleLanguage.java:1357)
	at org.graalvm.truffle/com.oracle.truffle.api.LanguageAccessor$LanguageImpl.parse(LanguageAccessor.java:298)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotSourceCache.parseImpl(PolyglotSourceCache.java:94)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotSourceCache.parseCached(PolyglotSourceCache.java:82)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext.parseCached(PolyglotLanguageContext.java:372)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:1480)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextDispatch.eval(PolyglotContextDispatch.java:63)
	at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:403)
	Suppressed: Attached Guest Language Frames (0)
Internal GraalVM error, please report at https://github.com/oracle/graal/issues/.

**Comment by marwan-hallaoui** [comment]
Hi, @chenjie100 , Thank you for reporting this issue, could you please share the steps to reproduce this issue so we can start working on it, you can use the following template issue [here](https://github.com/oracle/graal/issues/new/choose) to add the missing information.

**Comment by chenjie100** [comment]
@marwan-hallaoui 
I'm sorry, this is an occasional exception and I can't reproduce it now.

**Comment by marwan-hallaoui** [comment]
Thanks @chenjie100 for the update, hence I will close the issue
