### ISSUE TITLE
java.nio.file.InvalidPathException when initializing JS Scriptengine under Windows

### ISSUE THREAD

**Issue by LStampf** [oracle/graal#7918]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: 23.1.1
 - CE or EE: CE
 - JDK version: JDK17
 - OS and OS Version: Windows 11
 - Architecture: x64
 - The output of `java -Xinternalversion`:
```
OpenJDK 64-Bit Server VM (17.0.8.1+1) for windows-amd64 JRE (17.0.8.1+1), built on Aug 23 2023 15:29:17 by "admin" with MS VC++ 16.7 (VS2019)
```

**Have you verified this issue still happens when using the latest snapshot?**
No, but I checked the source and the code leading to this is unchanged

**Describe the issue**
Trying to create a js ScriptEngine in an web environment that utilizes the URLClassloader (e.g. Tomcat)  under Windows leads to the below StackTrace. The problem is that the Engine.ClassPathIsolation.collectClassPathJars Method uses the URL -> URI -> getPath method to feed Path.of. Which doesn't work with the : contained in /C:/ . This should be handled like e.g in LanguageCache getLanguageHomeFromURLConnection which had the same problem in the past. 

**Steps to reproduce the issue**
```
        URL url = new URL("file:/C:/test");
        URI uri = url.toURI();
        
        Path working= Path.of(uri);
        Path notWorking = Path.of(uri.getPath());
```

**Expected behavior**
Able to create a ScriptEngine under Windows

**Additional context**

```
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/.......
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at org.graalvm.polyglot.Engine$ClassPathIsolation.collectClassPathJars(Engine.java:1988)
	at org.graalvm.polyglot.Engine$ClassPathIsolation.createIsolatedTruffleModule(Engine.java:1783)
	at org.graalvm.polyglot.Engine$ClassPathIsolation.createIsolatedTruffle(Engine.java:1723)
	at org.graalvm.polyglot.Engine$1.searchServiceLoader(Engine.java:1682)
	at org.graalvm.polyglot.Engine$1.run(Engine.java:1668)
	at org.graalvm.polyglot.Engine$1.run(Engine.java:1663)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at org.graalvm.polyglot.Engine.initEngineImpl(Engine.java:1663)
	at org.graalvm.polyglot.Engine$ImplHolder.<clinit>(Engine.java:186)
```
</details>

**Comment by medoussboug** [comment]
Hello, to my knowledge the class Paths doesn't have a method of(String), there is a Path.of(String), also the Paths.get() internally uses Path.of(). Additionally I am confused on the versions you provided as "OpenJDK 64-Bit Server VM (17.0.8.1+1) for windows-amd64 JRE (17.0.8.1+1), built on Aug 23 2023 15:29:17 by "admin" with MS VC++ 16.7 (VS2019)" indicates that it's an openJDK build not a GraalVM build, Also I think there might be a typo in the GraalVM version since there isn't a JDK 17 in GraalVM 23.1.1.

Kindly update the informations and the reproducer so that we are able to investigate your issue. (please include the steps to reproduce, the commands to use...)

**Comment by LStampf** [comment]
@medoussboug Hi, you are correct, typos on my end. I dug a little deeper, this only occurs in web environments e.g. Tomcat where the UrlClassLoader is used. The problem is this row:
https://github.com/oracle/graal/blob/4fed6a36941e9e4d6cd08ab98d2c458cd3a33933/sdk/src/org.graalvm.polyglot/src/org/graalvm/polyglot/Engine.java#L2008C31-L2008C34

If the URL is a Windows URL with C:/ in it. Path.of(URI) works, but Path.of(String) won't. The same error appeared happened a few times in the past like here: https://github.com/oracle/graal/issues/469 just in a different place.

**Comment by LStampf** [comment]
Sorry, I just noticed this is a duplicate of https://github.com/oracle/graal/issues/7833 But maybe my additional Info can help. You can use the reproducer in that ticket. It is the same issue with windows URL classloading.

**Comment by LStampf** [comment]
Closed because of duplicate.
