### ISSUE TITLE
error on compile with pgo

### ISSUE THREAD

**Issue by Ricard-Kollcaku** [oracle/graal#7964]
We have a spring boot 3.2 project running as native image. everything is ok when we dont use pgo, it compiles and runs ok.
than we created a pgo file using `buildArgs.add("--pgo-instrument")`
compile the app as native runn it do some load test close the app and the .iprof file gets generated successfully, 
when we try to compile the app using this generated profile we get an error. Below you will find the error log from graalvm
# GraalVM Native Image Error Report

## Build Output

```
========================================================================================================================
GraalVM Native Image: Generating 'project' (executable)...
========================================================================================================================
For detailed information and explanations on the build output, visit:
https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/BuildOutput.md
------------------------------------------------------------------------------------------------------------------------
[1/8] Initializing...                                                                                   (10.8s @ 0.36GB)
 Java version: 21.0.1+12, vendor version: Oracle GraalVM 21.0.1+12.1
 Graal compiler: optimization level: 3, target machine: x86-64-v3, PGO: user-provided
 C compiler: gcc (linux, x86_64, 11.4.0)
 Garbage collector: Serial GC (max heap size: 80% of RAM)
 2 user-specific feature(s):
 - com.oracle.svm.thirdparty.gson.GsonFeature
 - org.springframework.aot.nativex.feature.PreComputeFieldFeature
------------------------------------------------------------------------------------------------------------------------
 4 experimental option(s) unlocked:
 - '-H:ClassInitialization' (alternative API option(s): --initialize-at-run-time=datadog.trace.api.Config:rerun,datadog.trace.api.Platform:rerun,datadog.trace.api.env.CapturedEnvironment:build_time,datadog.trace.api.ConfigDefaults:build_time,datadog.trace.api.InstrumenterConfig:build_time,datadog.trace.api.Functions:build_time,datadog.trace.api.GlobalTracer:build_time,datadog.trace.api.MethodFilterConfigParser:build_time,datadog.trace.api.WithGlobalTracer:build_time,datadog.trace.api.PropagationStyle:build_time,datadog.trace.bootstrap.config.provider.ConfigConverter:build_time,datadog.trace.bootstrap.config.provider.ConfigProvider:build_time,datadog.trace.bootstrap.config.provider.ConfigProvider$Singleton:build_time,datadog.trace.bootstrap.Agent:build_time,datadog.trace.bootstrap.BootstrapProxy:build_time,datadog.trace.bootstrap.CallDepthThreadLocalMap:build_time,datadog.trace.bootstrap.DatadogClassLoader:build_time,datadog.trace.bootstrap.InstrumentationClassLoader:build_time,datadog.trace.bootstrap.FieldBackedContextStores:build_time,datadog.trace.bootstrap.benchmark.StaticEventLogger:build_time,datadog.trace.bootstrap.instrumentation.java.concurrent.ConcurrentState:build_time,datadog.trace.bootstrap.instrumentation.java.concurrent.ExcludeFilter:build_time,datadog.trace.bootstrap.instrumentation.java.concurrent.QueueTimeHelper:build_time,datadog.trace.bootstrap.instrumentation.java.concurrent.TPEHelper:build_time,datadog.trace.logging.LoggingSettingsDescription:build_time,datadog.trace.logging.simplelogger.SLCompatFactory:build_time,datadog.trace.util.CollectionUtils:build_time,datadog.slf4j.impl.StaticLoggerBinder:build_time,datadog.slf4j.LoggerFactory:build_time,com.blogspot.mydailyjava.weaklockfree.WeakConcurrentMap:build_time,net.bytebuddy:build_time,com.sun.proxy:build_time,jnr.enxio.channels:run_time,jnr.unixsocket:run_time, --initialize-at-run-time=io.netty.internal.tcnative.SSL:run_time,io.netty.internal.tcnative.CertificateVerifier:run_time,io.netty.internal.tcnative.AsyncSSLPrivateKeyMethod:run_time,io.netty.internal.tcnative.SSLPrivateKeyMethod:run_time,io.netty.handler.ssl.OpenSslPrivateKeyMethod:run_time,io.netty.handler.ssl.ReferenceCountedOpenSslEngine:run_time,io.netty.handler.ssl.OpenSslAsyncPrivateKeyMethod:run_time, --initialize-at-run-time=org.springframework.aot.nativex.feature.ThrowawayClassLoader:build_time, --initialize-at-run-time=io.netty.handler.codec.compression.BrotliDecoder:run_time, --initialize-at-run-time=io.netty.channel.epoll:run_time,io.netty.channel.unix.Limits:run_time,io.netty.channel.unix.IovArray:run_time,io.netty.channel.unix.Errors:run_time, --initialize-at-run-time=com.mongodb.UnixServerAddress:run_time,com.mongodb.internal.connection.SnappyCompressor:run_time,org.bson.types.ObjectId:run_time,com.mongodb.internal.connection.ClientMetadataHelper:run_time, --initialize-at-run-time=org.bson.types.ObjectId:run_time; origin(s): command line)
 - '-H:EnableURLProtocols' (alternative API option(s): --enable-http, --enable-http, --enable-https, --enable-https; origin(s): command line)
 - '-H:IncludeResources' (origin(s): command line)
 - '-H:ReflectionConfigurationResources' (origin(s): command line)
------------------------------------------------------------------------------------------------------------------------
Build resources:
 - 13.15GB of memory (42.4% of 31.00GB system memory, determined at start)
 - 8 thread(s) (100.0% of 8 available processor(s), determined at start)
[2/8] Performing analysis...  [******]                                                                 (139.4s @ 4.98GB)
   42,167 reachable types   (92.3% of   45,704 total)
   64,775 reachable fields  (62.1% of  104,324 total)
  205,149 reachable methods (66.4% of  308,893 total)
   11,824 types, 2,007 fields, and 18,001 methods registered for reflection
       95 types,    99 fields, and    67 methods registered for JNI access
        4 native libraries: dl, pthread, rt, z

```

## Stack Trace

```java
com.oracle.svm.core.util.VMError$HostedError: Conditionals must have the same number of branches in every context.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:78)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.guarantee(VMError.java:122)
	at com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.profiling.kinds.a.a(stripped:108)
	at com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.profiling.metadata.cctree.c.a(stripped:41)
	at com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.profiling.loaders.ProfilingLoader.loadNodes(stripped:133)
	at com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.profiling.profiles.ProfilingBaseProfile.buildMetadata(stripped:126)
	at com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.hosted.pgo.profiles.b.<init>(stripped:57)
	at com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.hosted.pgo.loaders.a.newProfile(stripped:66)
	at com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.profiling.loaders.ProfilingLoader.lambda$loadProfile$0(stripped:69)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662)
	at com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.profiling.loaders.ProfilingLoader.loadProfile(stripped:71)
	at com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.hosted.pgo.features.PGOFeature.loadProfiles(stripped:240)
	at com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.hosted.pgo.features.PGOFeature.afterAnalysis(stripped:229)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$12(NativeImageGenerator.java:804)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:90)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:804)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:592)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:550)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:538)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:720)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:142)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:97)
```

## GraalVM Setup

| Name | Value |
| ---- | ----- |
| Java version | `21.0.1+12` |
| Vendor version | `Oracle GraalVM 21.0.1+12.1` |
| Runtime version | `21.0.1+12-jvmci-23.1-b19` |
| C compiler | `gcc (linux, x86_64, 11.4.0)` |
<details>
<summary>GraalVM <code>release</code> file</summary>

```
IMPLEMENTOR="Oracle Corporation"
JAVA_RUNTIME_VERSION="21.0.1+12-jvmci-23.1-b19"
JAVA_VERSION="21.0.1"
JAVA_VERSION_DATE="2023-10-17"
LIBC="gnu"
MODULES="java.base java.logging java.management jdk.internal.vm.ci jdk.unsupported org.graalvm.collections jdk.management org.graalvm.truffle.compiler org.graalvm.word jdk.internal.vm.compiler com.oracle.graal.graal_enterprise org.graalvm.nativeimage com.oracle.svm.enterprise.truffle com.oracle.svm.extraimage_enterprise java.compiler java.datatransfer java.xml java.prefs java.desktop java.instrument java.security.sasl java.naming java.rmi java.management.rmi java.net.http java.scripting java.security.jgss java.transaction.xa java.sql java.sql.rowset java.xml.crypto java.se java.smartcardio jdk.accessibility jdk.internal.jvmstat jdk.attach jdk.charsets jdk.internal.opt jdk.zipfs jdk.compiler jdk.crypto.ec jdk.crypto.cryptoki jdk.dynalink jdk.internal.ed jdk.editpad jdk.hotspot.agent jdk.httpserver jdk.incubator.vector jdk.internal.le jdk.internal.vm.compiler.management jdk.jartool jdk.javadoc jdk.jcmd jdk.management.agent jdk.jconsole jdk.jdeps jdk.jdwp.agent jdk.jdi jdk.jfr jdk.jlink jdk.jpackage jdk.jshell jdk.jsobject jdk.jstatd jdk.localedata jdk.management.jfr jdk.naming.dns jdk.naming.rmi jdk.net jdk.nio.mapmode jdk.random jdk.sctp jdk.security.auth jdk.security.jgss jdk.unsupported.desktop jdk.xml.dom org.graalvm.extraimage.builder"
OS_ARCH="x86_64"
OS_NAME="Linux"
SOURCE=".:git:38e747d58ef4 open:git:db26df3b0823 labsjdk-builder:ce01baf820a68601ac8bfdda7c246ea84aef91dc compiler:b102df7bc5acaa64069b6a606f77bc463874f997 graal-enterprise:8068a2458a38f9cf446a76ffcd065bbe1fb25c0e graal-microservices:8068a2458a38f9cf446a76ffcd065bbe1fb25c0e java-benchmarks:b102df7bc5acaa64069b6a606f77bc463874f997 regex:b102df7bc5acaa64069b6a606f77bc463874f997 sdk:b102df7bc5acaa64069b6a606f77bc463874f997 substratevm:b102df7bc5acaa64069b6a606f77bc463874f997 substratevm-enterprise:8068a2458a38f9cf446a76ffcd065bbe1fb25c0e substratevm-enterprise-gcs:b5b3ad2db4b8df213021450612ebeeb9268915a2 tools:b102df7bc5acaa64069b6a606f77bc463874f997 truffle:b102df7bc5acaa64069b6a606f77bc463874f997 vm:b102df7bc5acaa64069b6a606f77bc463874f997 vm-enterprise:8068a2458a38f9cf446a76ffcd065bbe1fb25c0e"
GRAALVM_VERSION="23.1.1"
COMMIT_INFO={"compiler": {"commit.committer": "Marouane El Hallaoui <marouane.el.hallaoui@oracle.com>", "commit.committer-ts": 1696857619, "commit.rev": "b102df7bc5acaa64069b6a606f77bc463874f997"}, "graal-enterprise": {"commit.committer": "Marouane El Hallaoui <marouane.el.hallaoui@oracle.com>", "commit.committer-ts": 1696858095, "commit.rev": "8068a2458a38f9cf446a76ffcd065bbe1fb25c0e"}, "graal-microservices": {"commit.committer": "Marouane El Hallaoui <marouane.el.hallaoui@oracle.com>", "commit.committer-ts": 1696858095, "commit.rev": "8068a2458a38f9cf446a76ffcd065bbe1fb25c0e"}, "java-benchmarks": {"commit.committer": "Marouane El Hallaoui <marouane.el.hallaoui@oracle.com>", "commit.committer-ts": 1696857619, "commit.rev": "b102df7bc5acaa64069b6a606f77bc463874f997"}, "regex": {"commit.committer": "Marouane El Hallaoui <marouane.el.hallaoui@oracle.com>", "commit.committer-ts": 1696857619, "commit.rev": "b102df7bc5acaa64069b6a606f77bc463874f997"}, "sdk": {"commit.committer": "Marouane El Hallaoui <marouane.el.hallaoui@oracle.com>", "commit.committer-ts": 1696857619, "commit.rev": "b102df7bc5acaa64069b6a606f77bc463874f997"}, "substratevm": {"commit.committer": "Marouane El Hallaoui <marouane.el.hallaoui@oracle.com>", "commit.committer-ts": 1696857619, "commit.rev": "b102df7bc5acaa64069b6a606f77bc463874f997"}, "substratevm-enterprise": {"commit.committer": "Marouane El Hallaoui <marouane.el.hallaoui@oracle.com>", "commit.committer-ts": 1696858095, "commit.rev": "8068a2458a38f9cf446a76ffcd065bbe1fb25c0e"}, "substratevm-enterprise-gcs": {"commit.committer": "Gilles Duboscq <gilles.m.duboscq@oracle.com>", "commit.committer-ts": 1693648031, "commit.rev": "b5b3ad2db4b8df213021450612ebeeb9268915a2"}, "tools": {"commit.committer": "Marouane El Hallaoui <marouane.el.hallaoui@oracle.com>", "commit.committer-ts": 1696857619, "commit.rev": "b102df7bc5acaa64069b6a606f77bc463874f997"}, "truffle": {"commit.committer": "Marouane El Hallaoui <marouane.el.hallaoui@oracle.com>", "commit.committer-ts": 1696857619, "commit.rev": "b102df7bc5acaa64069b6a606f77bc463874f997"}, "vm": {"commit.committer": "Marouane El Hallaoui <marouane.el.hallaoui@oracle.com>", "commit.committer-ts": 1696857619, "commit.rev": "b102df7bc5acaa64069b6a606f77bc463874f997"}, "vm-enterprise": {"commit.committer": "Marouane El Hallaoui <marouane.el.hallaoui@oracle.com>", "commit.committer-ts": 1696858095, "commit.rev": "8068a2458a38f9cf446a76ffcd065bbe1fb25c0e"}}
```

</details>

**Comment by fniephaus** [comment]
Hey @Ricard-Kollcaku, thanks for filing this. Is there any way you could provide us with a reproducer?

**Comment by Ricard-Kollcaku** [comment]
Unfortunately this is a production project so i cant share the code

**Comment by fniephaus** [comment]
Ok, no problem. Does the error happen with different profiles?

**Comment by Ricard-Kollcaku** [comment]
yes i tried to generate 3 different profiles but all of them throw the same error when it tries compiles.

**Comment by jovanstevanovic** [comment]
One note: this occurs when using `--pgo` (applying profiles) and not `--pgo-instrument` (collecting profiles) as you stated. The reason for the failure is that the same switch statement has a different number of branches during collecting and applying profiles due to a different way of optimizing. It will be tricky to find it without actual workload, but I'll see what we can do.

**Comment by jovanstevanovic** [comment]
The fix is now on the master.

**Comment by DigitalMediageek** [comment]
Latest available download for linux/x64 is "21.0.2" 2024-01-16. Your last comment is dated January 23rd. Hence, I guess the fix is not included in latest version. When will it be available?

**Comment by sgammon** [comment]
@DigitalMediageek I believe the "latest available" download would be [JDK 22](https://www.graalvm.org/downloads/) which came out last week.

**Comment by fniephaus** [comment]
Yes, the fix is included in the JDK 22 release and we have backported the fix for JDK 21.0.3, which will be released in April.

**Comment by DigitalMediageek** [comment]
Thanks. Currently, my build doesn't work with 22. But I can wait for 21.0.3.
