### ISSUE TITLE
mx_vm.py uses hardcoded ':' as path separators, which fail to be parsed on Windows

### ISSUE THREAD

**Issue by JornVernee** [oracle/graal#797]
I was running into an exception when running the following code:

```
import org.graalvm.polyglot.*;

public class Main {
    public static void main(String[] args) {
        System.out.println("Hello Java!");
        Context context = Context.create();
        context.eval("js", "print('Hello JavaScript!');");
    }
}
```

The following exception:

```
Uncaught exception at ..\..\src\share\vm\jvmci\jvmciRuntime.cpp:1392
java.lang.ExceptionInInitializerError
	at jdk.vm.ci.services.Services.getJVMCIClassLoader0(Native Method)
	at jdk.vm.ci.services.Services.getJVMCIClassLoader(Services.java:261)
	at jdk.vm.ci.services.Services.load0(Services.java:147)
	at jdk.vm.ci.services.Services.loadSingle(Services.java:226)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.graalvm.polyglot.Engine$1.run(Engine.java:593)
	at org.graalvm.polyglot.Engine$1.run(Engine.java:580)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.graalvm.polyglot.Engine.initEngineImpl(Engine.java:580)
	at org.graalvm.polyglot.Engine.access$000(Engine.java:99)
	at org.graalvm.polyglot.Engine$ImplHolder.<clinit>(Engine.java:108)
	at org.graalvm.polyglot.Engine.getImpl(Engine.java:261)
	at org.graalvm.polyglot.Engine$Builder.build(Engine.java:484)
	at org.graalvm.polyglot.Context$Builder.build(Context.java:1085)
	at org.graalvm.polyglot.Context.create(Context.java:663)
	at main.Main.main(Main.java:9)
Caused by: java.nio.file.InvalidPathException: Illegal char <:>
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
	at jdk.vm.ci.services.JVMCIClassLoaderFactory.getJVMCIParentClassLoader(JVMCIClassLoaderFactory.java:103)
	at jdk.vm.ci.services.JVMCIClassLoaderFactory.newClassLoader(JVMCIClassLoaderFactory.java:74)
	at jdk.vm.ci.services.JVMCIClassLoaderFactory.<clinit>(JVMCIClassLoaderFactory.java:62)
	at jdk.vm.ci.services.Services.getJVMCIClassLoader0(Native Method)
	at jdk.vm.ci.services.Services.getJVMCIClassLoader(Services.java:261)
	at jdk.vm.ci.services.Services.load0(Services.java:147)
	at jdk.vm.ci.services.Services.loadSingle(Services.java:226)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.graalvm.polyglot.Engine$1.run(Engine.java:593)
	at org.graalvm.polyglot.Engine$1.run(Engine.java:580)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.graalvm.polyglot.Engine.initEngineImpl(Engine.java:580)
	at org.graalvm.polyglot.Engine.access$000(Engine.java:99)
	at org.graalvm.polyglot.Engine$ImplHolder.<clinit>(Engine.java:108)
	at org.graalvm.polyglot.Engine.getImpl(Engine.java:261)
	at org.graalvm.polyglot.Engine$Builder.build(Engine.java:484)
	at org.graalvm.polyglot.Context$Builder.build(Context.java:1085)
	at org.graalvm.polyglot.Context.create(Context.java:663)
	at main.Main.main(Main.java:9)
```

This code is trying to load a classpath file located in `latest_graal_home/jre/lib/jvmci/parentClassLoader.classpath`, but the class path contains harcoded `:` as path separators so this is failing to parse on Windows.

I can work around this problem by replacing the path separators with Windows ones (`;`) by hand.

The file is being created by `mx_vm.py` [1]

```
"<jdk_base>/jre/lib/jvmci/parentClassLoader.classpath": [
    "string:../truffle/truffle-api.jar:../truffle/locator.jar:../truffle/truffle-nfi.jar",
],
```

Exchanging the path separators with `os.pathsep` works for me, but I'm not sure this solution works when cross-compiling, so I'm leaving this as an issue instead of making a PR.

(Also, please note that I had to [jump through some hoops](https://github.com/oracle/graal/issues/795#issuecomment-437381718) to get the vm suite to build)

[1] : https://github.com/oracle/graal/blob/cb3237438193144b7dbc26d53702e12d3e81a053/vm/mx.vm/mx_vm.py#L1275

**Comment by wirthi** [comment]
I am closing this ticket. The concrete case has at least been significantly reworked. I also believe that we are way more supportive of Windows nowadays, so I would assume the feature is working.
Let me know if there is anything still broken.
