### ISSUE TITLE
orai18n dependency causes native image build to fail with GraalVM for JDK 21

### ISSUE THREAD

**Issue by syedyusufh** [oracle/graal#8067]
Native image build fails if **orai18n.jar** is included as a dependency

Below is a minimal sample to reproduce the problem,

https://github.com/syedyusufh/hello-sample.git

```
Error: An object of type 'oracle.sql.converter.I18CharacterConvertersWrapper' was found in the image heap. This type, however, is marked for initialization at image run time for the following reason: classes are initialized at run time by default.
This is not allowed for correctness reasons: All objects that are stored in the image heap must be initialized at build time.

You now have two options to resolve this:

1) If it is intended that objects of type 'oracle.sql.converter.I18CharacterConvertersWrapper' are persisted in the image heap, add

    '--initialize-at-build-time=oracle.sql.converter.I18CharacterConvertersWrapper'

to the native-image arguments. Note that initializing new types can store additional objects to the heap. It is advised to check the static fields of 'oracle.sql.converter.I18CharacterConvertersWrapper' to see if they are safe for build-time initialization,  and that they do not contain any sensitive data that should not become part of the image.

2) If these objects should not be stored in the image heap, you can use

    '--trace-object-instantiation=oracle.sql.converter.I18CharacterConvertersWrapper'

to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with

    '--initialize-at-run-time=<culprit>'

to prevent the instantiation of the object.

The culprit object has been instantiated with the following trace:
	at oracle.sql.converter.I18CharacterConvertersWrapper.<init>(I18CharacterConvertersWrapper.java:61)
	at oracle.sql.converter.CharacterConverterFactoryOGS.make(CharacterConverterFactoryOGS.java:46)
	at oracle.sql.CharacterSetWithConverter.getInstance(CharacterSetWithConverter.java:99)
	at oracle.sql.CharacterSetFactoryThin.make(CharacterSetFactoryThin.java:130)
	at oracle.sql.CharacterSet$$Lambda/0x0000007003242ac0.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
	at oracle.sql.CharacterSet.make(CharacterSet.java:519)
	at java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(DirectMethodHandle$Holder)
	at java.lang.invoke.LambdaForm$MH/0x0000007002c0d000.invoke(LambdaForm$MH)
	at java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:154)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.lang.reflect.Method.invoke(Method.java:580)
	at oracle.nativeimage.CharacterSetFeature.duringAnalysis(CharacterSetFeature.java:86)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$10(NativeImageGenerator.java:786)
	at com.oracle.svm.hosted.NativeImageGenerator$$Lambda/0x0000007003247848.accept(Unknown Source)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:90)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$11(NativeImageGenerator.java:786)
	at com.oracle.svm.hosted.NativeImageGenerator$$Lambda/0x0000007002ab0460.apply(Unknown Source)
	at com.oracle.graal.pointsto.AbstractAnalysisEngine.runAnalysis(AbstractAnalysisEngine.java:181)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:783)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:592)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:550)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:543)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:725)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:142)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:97)
```

**Comment by hamzaGhaissi** [comment]
Thanks for reporting, issue was reproduced and we are tracking it internally.

**Comment by syedyusufh** [comment]
@hamzaGhaissi can you please suggest any workaround to continue with build as **orai18n** is part of any Oracle DB driver application dependency and this is a show-stopper for us. Thx in advance

**Comment by syedyusufh** [comment]
@hamzaGhaissi tried the same application with the newer version **GraalVM 21.0.2**, still the same error. Kindly help. Thanks

**Comment by syedyusufh** [comment]
Hi @hamzaGhaissi build is successful, however the application startup fails with the below error, kindly check

`Missing character set id 170 not loaded at image build time at oracle.sql.CharacterSet.make(CharacterSet.java:114)`

**Comment by hamzaGhaissi** [comment]
What's the command you are using to generate native-image and your graalvm version ?

**Comment by syedyusufh** [comment]
Once the Spring AOT classes are generated via `mvn -Pnative package` native image is built using `mvn -Pnative native:compile` on`GraalVM for JDK 21 Community 21.0.2`

**Comment by hamzaGhaissi** [comment]
unfortunately, I couldn't reproduce using Macos aarch64 and
`openjdk 21.0.2 2024-01-16
OpenJDK Runtime Environment GraalVM CE 21.0.2+13.1 (build 21.0.2+13-jvmci-23.1-b30)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.2+13.1 (build 21.0.2+13-jvmci-23.1-b30, mixed mode, sharing)
`
what's you OS & architecture ?

**Comment by syedyusufh** [comment]
@hamzaGhaissi can you please pull the latest sample project and configure a working Oracle Database in `application.properties` file to recreate the issue? Thx in advance.

https://github.com/syedyusufh/hello-sample.git

P.S: Earlier shared sample version had database autostart disabled on application startup.

**Comment by hamzaGhaissi** [comment]
can you confirm that this issue doesn't exist using the JVM ?

**Comment by syedyusufh** [comment]
Non-Native image works fine with JVM and GraalVM also. Issue is with native image only.

**Comment by hamzaGhaissi** [comment]
@syedyusufh can you please open a new github issue, since the original issue has been solved and closed

**Comment by syedyusufh** [comment]
https://github.com/oracle/graal/issues/8265 created

Thanks @hamzaGhaissi
