### ISSUE TITLE
Fatal error: java.lang.reflect.MalformedParameterizedTypeException

### ISSUE THREAD

**Issue by ignatov** [oracle/graal#809]
Hi, I'm trying to build a native image for Kotlin compiler and got an error. The issue looks like a bug in Graal itself.

```
kotlinc > ./build.sh                                                                                                                                                         master
+ set -e
++ pwd
+ KT_HOME=/Users/ignatov/Downloads/kotlinc
+ /Users/ignatov/bin/graalvm-ce-1.0.0-rc9/Contents/Home/bin/native-image -cp /Users/ignatov/Downloads/kotlinc/lib/kotlin-compiler.jar org.jetbrains.kotlin.cli.jvm.K2JVMCompiler -H:Name=kotlincc
Build on Server(pid: 99778, port: 55186)
[kotlincc:99778]    classlist:   5,120.56 ms
[kotlincc:99778]        (cap):   1,300.41 ms
[kotlincc:99778]        setup:   1,863.29 ms
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of com.intellij.openapi.util.UserDataHolderBase. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., The field com.intellij.util.concurrency.AtomicFieldUpdater.offset, where the value produced by the field offset computation is stored, is not static.
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of com.intellij.psi.impl.source.PsiFileImpl. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., The field com.intellij.util.concurrency.AtomicFieldUpdater.offset, where the value produced by the field offset computation is stored, is not static.
[kotlincc:99778]     analysis:   1,348.69 ms
fatal error: java.lang.reflect.MalformedParameterizedTypeException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:419)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:278)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:375)
        at com.oracle.svm.hosted.server.NativeImageBuildServer.executeCompilation(NativeImageBuildServer.java:391)
        at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$processCommand$8(NativeImageBuildServer.java:328)
        at com.oracle.svm.hosted.server.NativeImageBuildServer.withJVMContext(NativeImageBuildServer.java:409)
        at com.oracle.svm.hosted.server.NativeImageBuildServer.processCommand(NativeImageBuildServer.java:325)
        at com.oracle.svm.hosted.server.NativeImageBuildServer.processRequest(NativeImageBuildServer.java:269)
        at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$serve$7(NativeImageBuildServer.java:229)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.MalformedParameterizedTypeException
        at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.validateConstructorArguments(ParameterizedTypeImpl.java:58)
        at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.<init>(ParameterizedTypeImpl.java:51)
        at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.make(ParameterizedTypeImpl.java:92)
        at sun.reflect.generics.factory.CoreReflectionFactory.makeParameterizedType(CoreReflectionFactory.java:105)
        at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:140)
        at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
        at sun.reflect.generics.repository.ClassRepository.getSuperInterfaces(ClassRepository.java:108)
        at java.lang.Class.getGenericInterfaces(Class.java:913)
        at com.oracle.svm.hosted.analysis.Inflation.fillGenericInfo(Inflation.java:284)
        at com.oracle.svm.hosted.analysis.Inflation.checkType(Inflation.java:141)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
        at com.oracle.svm.hosted.analysis.Inflation.checkObjectGraph(Inflation.java:130)
        at com.oracle.graal.pointsto.BigBang.checkObjectGraph(BigBang.java:590)
        at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:562)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:691)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:402)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

For reproducing please run `./build.sh` in the root of the https://github.com/ignatov/kotlin-graal

I'm on macOS with graalvm-ce-1.0.0-rc9.

**Comment by cstancu** [comment]
This issue is fixed in RC12. Thank you for your report!
