### ISSUE TITLE
ImageSingletons do not contain key org.graalvm.nativeimage.impl.RuntimeForeignAccessSupport

### ISSUE THREAD

**Issue by lohhonglee** [oracle/graal#8115]
**Describe the issue**
I am using GraalVM for JDK 21.0.1 (release version) to build a very simple native application that uses Foreign Function & Memory (FFM) API (third preview). I followed what is documented in the [reference manual](https://www.graalvm.org/latest/reference-manual/native-image/dynamic-features/foreign-interface/), including registering foreign calls using a custom `Feature` but encountered this error during compilation:
```
Error: ImageSingletons do not contain key org.graalvm.nativeimage.impl.RuntimeForeignAccessSupport
------------------------------------------------------------------------------------------------------------------------
                        0.2s (5.7% of total time) in 12 GCs | Peak RSS: 0.51GB | CPU load: 3.47
========================================================================================================================
Finished generating 'app' in 2.9s.
com.oracle.svm.driver.NativeImage$NativeImageError
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.showError(NativeImage.java:2336)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.build(NativeImage.java:1919)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1878)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.main(NativeImage.java:1852)
        at java.base@21.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```
The Java application itself can be compiled and run. It only fails during native-image compilation.
The argument `--features=com.example.ForeignRegistrationFeature` is passed to the native-image at build time and the class is properly implemented per the documentation but it triggers the error. Without this argument, compilation passed but failed at runtime.

Source code can be found here: https://github.com/lohhonglee/ffm-graalvm

**Steps to reproduce the issue**
1. `git clone https://github.com/lohhonglee/ffm-graalvm`
2. `cd ffm-graalvm`
3. `gcc -o libhello.so -shared hello.c` (the library for downcall)
4. `./gradlew nativeRun`

**Describe GraalVM and your environment:**
 - GraalVM version: **21.0.1+12-jvmci-23.1-b19**
 - JDK major version: **21**
 - OS: **Ubuntu 22.04.3 LTS**
 - Architecture: **AMD64**
 - Build: **Gradle 8.5**

**More details**
```
$ ./gradlew nativeRun

> Task :app:generateResourcesConfigFile
[native-image-plugin] Resources configuration written into /home/hlloh/ffm-graalvm/app/build/native/generated/generateResourcesConfigFile/resource-config.json

> Task :app:nativeCompile
[native-image-plugin] Args are: [-cp, /home/hlloh/ffm-graalvm/app/build/libs/app.jar, --no-fallback, --verbose, -Ob, -o, /home/hlloh/ffm-graalvm/app/build/native/nativeCompile/app, -J--enable-preview, -J--enable-native-access=ALL-UNNAMED, -H:ConfigurationFileDirectories=/home/hlloh/ffm-graalvm/app/build/native/generated/generateResourcesConfigFile, --features=com.example.ForeignRegistrationFeature, com.example.App]
[native-image-plugin] GraalVM Toolchain detection is enabled
[native-image-plugin] GraalVM uses toolchain detection. Selected:
[native-image-plugin]    - language version: 21
[native-image-plugin]    - vendor: Oracle
[native-image-plugin]    - runtime version: 21.0.1+12-jvmci-23.1-b19
[native-image-plugin] Native Image executable path: /home/hlloh/.sdkman/candidates/java/21.0.1-graal/lib/svm/bin/native-image
Apply jar:file:///home/hlloh/.sdkman/candidates/java/21.0.1-graal/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/thirdparty/native-image.properties
Apply jar:file:///home/hlloh/.sdkman/candidates/java/21.0.1-graal/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/polyglot/native-image.properties
Executing [
HOME=/home/hlloh \
LANG=C.UTF-8 \
'PATH=/home/hlloh/.sdkman/candidates/java/current/bin:/home/hlloh/.sdkman/candidates/gradle/current/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/Eclipse Adoptium/jdk-17.0.7.7-hotspot/bin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Users/hlloh/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/hlloh/AppData/Local/Programs/Microsoft VS Code/bin:/snap/bin' \
PWD=/home/hlloh/ffm-graalvm \
USE_NATIVE_IMAGE_JAVA_PLATFORM_MODULE_SYSTEM=true \
/home/hlloh/.sdkman/candidates/java/21.0.1-graal/bin/java \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.HostLibC=glibc \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
--add-exports=java.base/com.sun.crypto.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.access=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.event=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.loader=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.logger=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.misc=com.oracle.svm.svm_enterprise,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile,org.graalvm.nativeimage.pointsto \
--add-exports=java.base/jdk.internal.module=org.graalvm.nativeimage.base,org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.org.objectweb.asm=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.perf=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.platform=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.ref=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=java.base/jdk.internal.reflect=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.util=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.vm.annotation=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.vm=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.invoke.util=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.net.www=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.net=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.nio.ch=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=java.base/sun.reflect.annotation=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.factory=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.reflectiveObjects=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.repository=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.scope=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.tree=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.jca=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.ssl=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.util=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.x509=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.text.spi=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.calendar=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.cldr=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.locale.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.locale=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.resources=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util=org.graalvm.nativeimage.builder \
--add-exports=java.management/com.sun.jmx.mbeanserver=org.graalvm.nativeimage.builder \
--add-exports=java.management/sun.management=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.aarch64=com.oracle.graal.graal_enterprise,com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.amd64=com.oracle.graal.graal_enterprise,com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.site=com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.stack=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=com.oracle.graal.graal_enterprise,com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile,org.graalvm.nativeimage.pointsto,org.graalvm.truffle.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.common=com.oracle.graal.graal_enterprise,com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.aarch64=jdk.internal.vm.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.amd64=jdk.internal.vm.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot=com.oracle.graal.graal_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.meta=com.oracle.graal.graal_enterprise,com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.base,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile,org.graalvm.nativeimage.pointsto,org.graalvm.truffle.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.runtime=com.oracle.graal.graal_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.services=com.oracle.graal.graal_enterprise,com.oracle.svm.svm_enterprise,jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.events=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal.jfc=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal=org.graalvm.nativeimage.builder \
--add-exports=jdk.management/com.sun.management.internal=org.graalvm.nativeimage.builder \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-XX:MaxRAMPercentage=53.54595613636812 \
-XX:GCTimeRatio=9 \
-XX:+ExitOnOutOfMemoryError \
-Djava.awt.headless=true \
'-Dorg.graalvm.vendor=Oracle Corporation' \
-Dorg.graalvm.vendorurl=https://www.graalvm.org/ \
'-Dorg.graalvm.vendorversion=Oracle GraalVM 21.0.1+12.1' \
-Dorg.graalvm.version=23.1.1 \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
--enable-preview \
--enable-native-access=ALL-UNNAMED \
--add-modules=ALL-DEFAULT \
--module-path \
/home/hlloh/.sdkman/candidates/java/21.0.1-graal/lib/svm/builder/svm.jar:/home/hlloh/.sdkman/candidates/java/21.0.1-graal/lib/svm/builder/svm-enterprise.jar:/home/hlloh/.sdkman/candidates/java/21.0.1-graal/lib/svm/builder/native-image-base.jar:/home/hlloh/.sdkman/candidates/java/21.0.1-graal/lib/svm/builder/pointsto.jar:/home/hlloh/.sdkman/candidates/java/21.0.1-graal/lib/svm/builder/objectfile.jar \
--module \
org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner \
-watchpid \
1239104 \
-imagecp \
/home/hlloh/ffm-graalvm/app/build/libs/app.jar \
-imagemp \
/home/hlloh/.sdkman/candidates/java/21.0.1-graal/lib/svm/graal-microservices.jar:/home/hlloh/.sdkman/candidates/java/21.0.1-graal/lib/svm/library-support.jar \
-H:CLibraryPath=/home/hlloh/.sdkman/candidates/java/21.0.1-graal/lib/svm/clibraries/linux-amd64 \
-H:Path@driver=/home/hlloh/ffm-graalvm/app/build/native/nativeCompile \
-H:FallbackThreshold@user+api=0 \
-H:Optimize@user+api=b \
-H:Name@user+api=app \
-H:ConfigurationFileDirectories@user=/home/hlloh/ffm-graalvm/app/build/native/generated/generateResourcesConfigFile \
-H:Features@user+api=com.example.ForeignRegistrationFeature \
'-H:Class@explicit main-class=com.example.App' \
-H:ImageBuildID@driver=54b8b09b-a599-e9a7-8706-2e7949dd2be7 \
'-H:Features@jar:file:///home/hlloh/.sdkman/candidates/java/21.0.1-graal/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/thirdparty/native-image.properties+api=com.oracle.svm.thirdparty.gson.GsonFeature' \
'-H:Features@jar:file:///home/hlloh/.sdkman/candidates/java/21.0.1-graal/lib/svm/library-support.jar!/META-INF/native-image/com.oracle.svm/polyglot/native-image.properties+api=com.oracle.svm.polyglot.groovy.GroovyIndyInterfaceFeature,com.oracle.svm.polyglot.scala.ScalaFeature'
]
========================================================================================================================
GraalVM Native Image: Generating 'app' (executable)...
========================================================================================================================
For detailed information and explanations on the build output, visit:
https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/BuildOutput.md
------------------------------------------------------------------------------------------------------------------------

[1/8] Initializing...                                                                                    (0.0s @ 0.06GB
Error: ImageSingletons do not contain key org.graalvm.nativeimage.impl.RuntimeForeignAccessSupport
------------------------------------------------------------------------------------------------------------------------
                        0.2s (5.7% of total time) in 12 GCs | Peak RSS: 0.51GB | CPU load: 3.47
========================================================================================================================
Finished generating 'app' in 2.9s.
com.oracle.svm.driver.NativeImage$NativeImageError
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.showError(NativeImage.java:2336)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.build(NativeImage.java:1919)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1878)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.main(NativeImage.java:1852)
        at java.base@21.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)

> Task :app:nativeCompile FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:nativeCompile'.
> Process 'command '/home/hlloh/.sdkman/candidates/java/21.0.1-graal/bin/native-image'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 4s
4 actionable tasks: 2 executed, 2 up-to-date
```

Am I missing  something or the FFM API support is still not ready?
Thanks.

**Comment by fniephaus** [comment]
Thanks for raising this, @lohhonglee.

> Am I missing something or the FFM API support is still not ready?

I'm afraid Native Image is missing full support for the FFM API. For details, please take a look at the corresponding roadmapt item https://github.com/oracle/graal/issues/8113. I hope you don't mind if I'm closing this one. Please feel free to leave any comments, feedback, or suggestions on the roadmap item. Thanks!

**Comment by lohhonglee** [comment]
@fniephaus, thanks for the reply. Kindly let me know if there is a GraalVM CE Dev build with the preliminary FFM API support available. I am eager to try it out!

**Comment by fniephaus** [comment]
@lohhonglee great! I recommend you subscribe to the roadmap item. We'll close it when the FFM API has landed and shortly after, it should ship as part of a dev build.

**Comment by lohhonglee** [comment]
Ok, thanks.
