### ISSUE TITLE
Destroy method not found in Native image for ExecutorService bean type

### ISSUE THREAD

**Issue by RomanCht** [oracle/graal#8136]
**Describe the issue**
I have a Spring Boot 3 _(version 3.2.1)_ app with nothing on the classpath except `spring-boot-starter`.

if I use following code:
```java
package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadPoolExecutor;

@SpringBootApplication
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

    @Bean
    ExecutorService executorService() {
        return Executors.newFixedThreadPool(10);
    }
}
```

...and then compile as Native image:
```bash
mvn clean native:compile -Pnative
```

...and run: 
```bash
./target/demo
```

...then I get the following error:
```bash
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'executorService': Invalid destruction signature
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:643) ~[demo:6.1.2]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[demo:6.1.2]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[demo:6.1.2]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[demo:6.1.2]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[demo:6.1.2]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[demo:6.1.2]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[demo:6.1.2]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:960) ~[demo:6.1.2]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:625) ~[demo:6.1.2]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762) ~[demo:3.2.1]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:464) ~[demo:3.2.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[demo:3.2.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1358) ~[demo:3.2.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1347) ~[demo:3.2.1]
        at com.example.demo.DemoApplication.main(DemoApplication.java:15) ~[demo:na]
Caused by: org.springframework.beans.factory.support.BeanDefinitionValidationException: Could not find a destroy method named 'shutdown' on bean with name 'executorService'
        at org.springframework.beans.factory.support.DisposableBeanAdapter.<init>(DisposableBeanAdapter.java:134) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.registerDisposableBeanIfNecessary(AbstractBeanFactory.java:1868) ~[demo:6.1.2]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:639) ~[demo:6.1.2]
```

And if I'll switch bean type to a precise one: _(`ThreadPoolExecutor`)_ instead of _(`ExecutorService`)_, then it works:
```java
    // This works
    @Bean
    ThreadPoolExecutor executorService() {
        return (ThreadPoolExecutor) Executors.newFixedThreadPool(10);
    }

    // This doesn't work
    @Bean
    ExecutorService executorService() {
        return Executors.newFixedThreadPool(10);
    }
```

This issue is almost exactly the same like this one: [#29545](https://github.com/spring-projects/spring-framework/issues/29545) except that now it only reproducing for `ExecutorService`.

**Steps to reproduce the issue**
Please see reproducible Demo app: [spring-native-executor-demo.zip](https://github.com/oracle/graal/files/13890111/spring-native-executor-demo.zip)

**Describe GraalVM and your environment:**
 - GraalVM version: **17.0.9-graal**
 - JDK major version: **17**
 - OS: **macOS Sonoma 14.1.1 (23B81)**
 - Architecture: **ARM64**

**Comment by RomanCht** [comment]
Sorry, wrong Github Project. Closing this issue. Here's the correct one: https://github.com/spring-projects/spring-framework/issues/32006
