### ISSUE TITLE
Micronaut Graal example native-image freezes / throws assertion with RC9

### ISSUE THREAD

**Issue by heziegl** [oracle/graal#814]
I tried the Micronaut Graal example:
https://github.com/micronaut-guides/micronaut-creating-first-graal-app/tree/master/complete/src/main/java/example/micronaut

If I use native-image and run the result, the application starts but if I do a http request the CPU goes up to 100% and the application freezes.

If I use native-image with `-J-ea` parameter a assertion is thrown:
```
Sending build context to Docker daemon  11.99MB
Step 1/7 : FROM oracle/graalvm-ce:1.0.0-rc9
 ---> caf701c9e18f
Step 2/7 : EXPOSE 8080
 ---> Using cache
 ---> d014ddbab3fb
Step 3/7 : COPY *.jar graaltest.jar
 ---> d0e12833db47
Removing intermediate container 0621b08b6a8d
Step 4/7 : ADD . build
 ---> cd854b84d98e
Removing intermediate container f1957332a4a9
Step 5/7 : RUN java -cp graaltest.jar io.micronaut.graal.reflect.GraalClassLoadingAnalyzer
 ---> Running in 283d78e6f276
21:55:43.667 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [cloud]
Graal Class Loading Analysis Enabled.
Graal Class Loading Analysis Enabled.
Writing reflect.json file to destination: build/reflect.json
 ---> 759052d99879
Removing intermediate container 283d78e6f276
Step 6/7 : RUN native-image --no-server -J-ea              --class-path graaltest.jar              -H:ReflectionConfigurationFiles=build/reflect.json              -H:EnableURLProtocols=http              -H:IncludeResources="logback.xml|application.yml|application.properties|META-INF/services/*.*"              -H:Name=graaltest              -H:Class=hello.world.Application              -H:+ReportUnsupportedElementsAtRuntime              -H:+AllowVMInspection              -H:-UseServiceLoaderFeature              --rerun-class-initialization-at-runtime='sun.security.jca.JCAUtil$CachedSecureRandomHolder,javax.net.ssl.SSLContext'              --delay-class-initialization-to-runtime=io.netty.handler.codec.http.HttpObjectEncoder,io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder,io.netty.handler.ssl.util.ThreadLocalInsecureRandom,com.sun.jndi.dns.DnsClient,io.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator,io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator,io.netty.handler.ssl.ReferenceCountedOpenSslEngine
 ---> Running in 22590e249d2c
[graaltest:8]    classlist:   5,040.85 ms
[graaltest:8]        (cap):   1,027.28 ms
[graaltest:8]        setup:   2,615.74 ms
[graaltest:8]     analysis:  24,194.72 ms
error: Error encountered while parsing com.oracle.svm.reflect.proxies.Proxy_io_reactivex_Single_constructor_.newInstance(java.lang.Object[])
Parsing context:
        parsing java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        parsing sun.net.www.protocol.http.Negotiator.getNegotiator(Negotiator.java:63)
        parsing sun.net.www.protocol.http.NegotiateAuthentication.firstToken(NegotiateAuthentication.java:234)
        parsing sun.net.www.protocol.http.NegotiateAuthentication.setHeaders(NegotiateAuthentication.java:209)
        parsing sun.net.www.protocol.http.HttpURLConnection.getServerAuthentication(HttpURLConnection.java:2525)
        parsing sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1737)
        parsing sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        parsing java.net.URL.openStream(URL.java:1045)
        parsing io.micronaut.core.io.service.SoftServiceLoader$ServiceLoaderIterator.hasNext(SoftServiceLoader.java:203)
        parsing io.micronaut.core.io.service.SoftServiceLoader$1.next(SoftServiceLoader.java:158)
        parsing io.micronaut.core.io.service.SoftServiceLoader$1.next(SoftServiceLoader.java:137)
        parsing io.micronaut.context.DefaultBeanContext.resolveBeanConfigurations(DefaultBeanContext.java:1018)
        parsing io.micronaut.context.DefaultApplicationContext.resolveBeanConfigurations(DefaultApplicationContext.java:95)
        parsing io.micronaut.context.DefaultBeanContext.readAllBeanConfigurations(DefaultBeanContext.java:1909)
        parsing io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:155)
        parsing io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:138)
        parsing io.micronaut.runtime.Micronaut.start(Micronaut.java:67)
        parsing io.micronaut.runtime.Micronaut.run(Micronaut.java:271)
        parsing io.micronaut.runtime.Micronaut.run(Micronaut.java:257)
        parsing hello.world.Application.main(Application.java:9)
        parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:164)
        parsing com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Original error: java.lang.AssertionError: AnalysisType<io.reactivex.Single, allocated: false, inHeap: false, inTypeCheck: true>
        at com.oracle.graal.pointsto.meta.AnalysisType.registerAsAllocated(AnalysisType.java:526)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.registerUsedElements(MethodTypeFlowBuilder.java:235)
        at com.oracle.svm.hosted.analysis.flow.SVMMethodTypeFlowBuilder.registerUsedElements(SVMMethodTypeFlowBuilder.java:66)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:212)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:323)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
        at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:186)
        at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:347)
        at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:389)
        at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:508)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

Error: Image building with exit status 1
```

**Comment by Hades32** [comment]
Created an project including CI job to show issue with quite minimal deps:
https://gitlab.com/Hades32/graaltest/-/jobs/124325637

**Comment by Hades32** [comment]
@cstancu  maybe same as #713 ?

**Comment by cstancu** [comment]
I'll close this since it is an old issue that should be fixed in the latest GraalVM RC. Please reopen if you still have problems.
