### ISSUE TITLE
Getting Error while creating exe using graalvm and Sping boot

### ISSUE THREAD

**Issue by abhijeeta94** [oracle/graal#8150]
I am trying to create exe file using graalvm for sping boot application which contains rest apis. For that I have added plugin <groupId>org.graalvm.buildtools</groupId> <artifactId>native-maven-plugin</artifactId> and using spring boot version 3.2.0  but I am getting below error.

org.springframework.boot.SpringApplication$AbandonedRunException
        at org.springframework.boot.SpringApplicationAotProcessor$AotProcessorHook$1.contextLoaded(SpringApplicationAotProcessor.java:101)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$contextLoaded$4(SpringApplicationRunListeners.java:72)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
        at org.springframework.boot.SpringApplicationRunListeners.contextLoaded(SpringApplicationRunListeners.java:72)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:431)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1342)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1331)
        at com.kpit.tf2.configuration.Application.main(Application.java:33)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:281)
        at org.springframework.boot.SpringApplicationAotProcessor.lambda$prepareApplicationContext$0(SpringApplicationAotProcessor.java:62)
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:58)
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:46)
        at org.springframework.boot.SpringApplication.withHook(SpringApplication.java:1442)
        at org.springframework.boot.SpringApplicationAotProcessor$AotProcessorHook.run(SpringApplicationAotProcessor.java:109)
        at org.springframework.boot.SpringApplicationAotProcessor.prepareApplicationContext(SpringApplicationAotProcessor.java:60)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:83)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
        at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
        at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:80)
Exception in thread "main" java.lang.IllegalStateException: No application context available after calling main method of 'com.kpit.tf2.configuration.Application'. Does it run a SpringApplication?
        at org.springframework.boot.SpringApplicationAotProcessor$AotProcessorHook.run(SpringApplicationAotProcessor.java:120)
        at org.springframework.boot.SpringApplicationAotProcessor.prepareApplicationContext(SpringApplicationAotProcessor.java:60)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:83)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
        at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
        at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:80)

pom.xml code
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.2.0</version>
	</parent>
	<groupId>com.kpit.diagnostics.tf2</groupId>
	<artifactId>tf2-product-launcher-application</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<name>tf2-product-launcher-application</name>
	<packaging>jar</packaging>

	<properties>
		<java.version>17</java.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.vintage</groupId>
			<artifactId>junit-vintage-engine</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents.client5</groupId>
			<artifactId>httpclient5</artifactId>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
                
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-resources</id>
                        
                        <phase>package</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${basedir}/target/win32/java</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${java.home}</directory>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
		</plugins>
	</build>
<profiles>
		<profile>
			<id>native</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.graalvm.buildtools</groupId>
						<artifactId>native-maven-plugin</artifactId>
						<executions>
							<execution>
								<id>build-native</id>
								<goals>
									<goal>compile-no-fork</goal>
								</goals>
								<phase>package</phase>
							</execution>
						</executions>
						<configuration>
							<mainClass>com.kpit.tf2.configuration.Application</mainClass>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
`
Main Claas
`package com.kpit.tf2.configuration;

import org.springframework.boot.ExitCodeExceptionMapper;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.scheduling.annotation.EnableScheduling;

/**
 * Main class to configure and launch Application.
 *
 * @author gauravt5
 *
 */
@SpringBootApplication
@ComponentScan(value = "com.kpit.tf2")
@EnableScheduling
//@ConfigurationProperties(prefix = "application.properties")
public class Application {

    /**
     * Main method to launch application.
     *
     * @param args commandline String array argument
     */
    public static void main(String[] args) {
        try {
            
            System.out.println("In the Main claas");
            SpringApplication.run(Application.class, args);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Bean
    ExitCodeExceptionMapper exitCodeToexceptionMapper() {
        return exception -> {
            return StartupErrorCodes.getExitCodeFromException(exception);
        };
    }
}`

Using graalvm version 
Java version: 17.0.9, vendor: Oracle Corporation, runtime: D:\graalvm-jdk-17_windows-x64_bin\graalvm-jdk-17.0.9+11.1

I am using application.properties located at src/main/resource/application.properties which contains server.port=8444
For logging I am logback.xml file.
`<?xml version="1.0" encoding="UTF-8"?>
<configuration debug="true">

	<appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
		<layout class="ch.qos.logback.classic.PatternLayout">
			<Pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
			</Pattern>
		</layout>
	</appender>

	<property name="LOG_HOME" value="logs" />
	<property name="MIN_INDEX" value="1" />
	<property name="MAX_ZIP_FILES" value="10" />

	<appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
		<file>${LOG_HOME}/launcher_application.log</file>
		<rollingPolicy class="ch.qos.logback.core.rolling.FixedWindowRollingPolicy">
			
			<fileNamePattern>${LOG_HOME}/launcher_application.%i.log.zip
			</fileNamePattern>
			<minIndex>${MIN_INDEX}</minIndex>
			<maxIndex>${MAX_ZIP_FILES}</maxIndex>
		</rollingPolicy>
		
		<triggeringPolicy class="ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy">
			<maxFileSize>5MB</maxFileSize>
		</triggeringPolicy>
		<encoder>
			<pattern>%date %level [%thread] [%file:%line] %msg%n
			</pattern>
		</encoder>
	</appender>
	<root level="WARN">
		<appender-ref ref="FILE" level="ERROR" />
		<appender-ref ref="STDOUT" level="ERROR" />
	</root>
	<logger name="com.kpit" level="DEBUG" additivity="true">
		<appender-ref ref="STDOUT" level="WARNING" />
	</logger>
	<logger name="com.kpit" level="TRACE" additivity="false">
		<appender-ref ref="STDOUT" level="WARNING" />
	</logger>

</configuration>`

I am using maven command  **mvn clean package -Pnative**  to create native image.

Complete stackstrace added below
```
    D:\CLAAS\ST-ForTesting\tf2-product-launcher-application>mvn clean package -Pnative
[INFO] Scanning for projects...
[INFO]
[INFO] -----< com.kpit.diagnostics.tf2:tf2-product-launcher-application >------
[INFO] Building tf2-product-launcher-application 1.0.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- clean:3.3.2:clean (default-clean) @ tf2-product-launcher-application ---
[INFO] Deleting D:\CLAAS\ST-ForTesting\tf2-product-launcher-application\target
[INFO]
[INFO] --- native:0.9.28:add-reachability-metadata (add-reachability-metadata) @ tf2-product-launcher-application ---
[INFO] Downloaded GraalVM reachability metadata repository from file:/C:/Users/abhijeeta3/.m2/repository/org/graalvm/buildtools/graalvm-reachability-metadata/0.9.28/graalvm-reachability-metadata-0.9.28-repository.zip
[INFO] [graalvm reachability metadata repository for ch.qos.logback:logback-classic:1.4.11]: Configuration directory not found. Trying latest version.
[INFO] [graalvm reachability metadata repository for ch.qos.logback:logback-classic:1.4.11]: Configuration directory is ch.qos.logback\logback-classic\1.4.1
[INFO] [graalvm reachability metadata repository for com.fasterxml.jackson.core:jackson-databind:2.15.3]: Configuration directory not found. Trying latest version.
[INFO] [graalvm reachability metadata repository for com.fasterxml.jackson.core:jackson-databind:2.15.3]: Configuration directory is com.fasterxml.jackson.core\jackson-databind\2.15.2
[INFO] [graalvm reachability metadata repository for org.apache.tomcat.embed:tomcat-embed-core:10.1.16]: Configuration directory not found. Trying latest version.
[INFO] [graalvm reachability metadata repository for org.apache.tomcat.embed:tomcat-embed-core:10.1.16]: Configuration directory is org.apache.tomcat.embed\tomcat-embed-core\10.0.20
[INFO]
[INFO] --- resources:3.3.1:resources (default-resources) @ tf2-product-launcher-application ---
[INFO] Copying 1 resource from src\main\resources to target\classes
[INFO] Copying 1 resource from src\main\resources to target\classes
[INFO]
[INFO] --- compiler:3.11.0:compile (default-compile) @ tf2-product-launcher-application ---
[INFO] Changes detected - recompiling the module! :source
[INFO] Compiling 16 source files with javac [debug release 17] to target\classes
[INFO] /D:/CLAAS/ST-ForTesting/tf2-product-launcher-application/src/main/java/com/kpit/tf2/application/lifecycle/implementation/backend/ServiceTesterLifeCycleManager.java: D:\CLAAS\ST-ForTesting\tf2-product-launcher-application\src\main\java\com\kpit\tf2\application\lifecycle\implementation\backend\ServiceTesterLifeCycleManager.java uses unchecked or unsafe operations.
[INFO] /D:/CLAAS/ST-ForTesting/tf2-product-launcher-application/src/main/java/com/kpit/tf2/application/lifecycle/implementation/backend/ServiceTesterLifeCycleManager.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- resources:3.3.1:testResources (default-testResources) @ tf2-product-launcher-application ---
[INFO] skip non existing resourceDirectory D:\CLAAS\ST-ForTesting\tf2-product-launcher-application\src\test\resources
[INFO]
[INFO] --- compiler:3.11.0:testCompile (default-testCompile) @ tf2-product-launcher-application ---
[INFO] Changes detected - recompiling the module! :dependency
[INFO]
[INFO] --- surefire:3.1.2:test (default-test) @ tf2-product-launcher-application ---
[WARNING]  Parameter 'systemProperties' is deprecated: Use systemPropertyVariables instead.
[INFO]
[INFO] --- spring-boot:3.2.0:process-aot (process-aot) @ tf2-product-launcher-application ---
11:29:59,442 |-INFO in ch.qos.logback.classic.LoggerContext[default] - This is logback-classic version 1.4.11
11:29:59,446 |-INFO in ch.qos.logback.classic.util.ContextInitializer@6d3af739 - Here is a list of configurators discovered as a service, by rank:
11:29:59,446 |-INFO in ch.qos.logback.classic.util.ContextInitializer@6d3af739 -   org.springframework.boot.logging.logback.RootLogLevelConfigurator
11:29:59,446 |-INFO in ch.qos.logback.classic.util.ContextInitializer@6d3af739 - They will be invoked in order until ExecutionStatus.DO_NOT_INVOKE_NEXT_IF_ANY is returned.
11:29:59,446 |-INFO in ch.qos.logback.classic.util.ContextInitializer@6d3af739 - Constructed configurator of type class org.springframework.boot.logging.logback.RootLogLevelConfigurator
11:29:59,457 |-INFO in ch.qos.logback.classic.util.ContextInitializer@6d3af739 - org.springframework.boot.logging.logback.RootLogLevelConfigurator.configure() call lasted 0 milliseconds. ExecutionStatus=INVOKE_NEXT_IF_ANY
11:29:59,457 |-INFO in ch.qos.logback.classic.util.ContextInitializer@6d3af739 - Trying to configure with ch.qos.logback.classic.joran.SerializedModelConfigurator
11:29:59,458 |-INFO in ch.qos.logback.classic.util.ContextInitializer@6d3af739 - Constructed configurator of type class ch.qos.logback.classic.joran.SerializedModelConfigurator
11:29:59,478 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.scmo]
11:29:59,478 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.scmo]
11:29:59,478 |-INFO in ch.qos.logback.classic.util.ContextInitializer@6d3af739 - ch.qos.logback.classic.joran.SerializedModelConfigurator.configure() call lasted 20 milliseconds. ExecutionStatus=INVOKE_NEXT_IF_ANY
11:29:59,478 |-INFO in ch.qos.logback.classic.util.ContextInitializer@6d3af739 - Trying to configure with ch.qos.logback.classic.util.DefaultJoranConfigurator
11:29:59,479 |-INFO in ch.qos.logback.classic.util.ContextInitializer@6d3af739 - Constructed configurator of type class ch.qos.logback.classic.util.DefaultJoranConfigurator
11:29:59,480 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
11:29:59,483 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/D:/CLAAS/ST-ForTesting/tf2-product-launcher-application/target/classes/logback.xml]
11:29:59,616 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [STDOUT]
11:29:59,617 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
11:29:59,650 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
11:29:59,651 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
11:29:59,653 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
11:29:59,656 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [FILE]
11:29:59,656 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
11:29:59,665 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@6a01e23 - Will use zip compression
11:29:59,670 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:29:59,671 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: logs/launcher_application.log
11:29:59,672 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [logs/launcher_application.log]
11:29:59,675 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to WARN
11:29:59,675 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [FILE] to Logger[ROOT]
11:29:59,677 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [STDOUT] to Logger[ROOT]
11:29:59,683 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [com.kpit] to DEBUG
11:29:59,687 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [com.kpit] to true
11:29:59,687 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [STDOUT] to Logger[com.kpit]
11:29:59,688 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [com.kpit] to TRACE
11:29:59,689 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [com.kpit] to false
11:29:59,689 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [STDOUT] to Logger[com.kpit]
11:29:59,690 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@4278a03f - End of configuration.
11:29:59,692 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@77167fb7 - Registering current configuration as safe fallback point
11:29:59,693 |-INFO in ch.qos.logback.classic.util.ContextInitializer@6d3af739 - ch.qos.logback.classic.util.DefaultJoranConfigurator.configure() call lasted 214 milliseconds. ExecutionStatus=DO_NOT_INVOKE_NEXT_IF_ANY
In the Main claas
11:30:00,083 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [STDOUT]
11:30:00,083 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
11:30:00,087 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
11:30:00,087 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
11:30:00,088 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
11:30:00,089 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [FILE]
11:30:00,090 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
11:30:00,091 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@31add175 - Will use zip compression
11:30:00,093 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:30:00,094 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: logs/launcher_application.log
11:30:00,094 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [logs/launcher_application.log]
11:30:00,096 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to WARN
11:30:00,097 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@ae3540e - Propagating WARN level on Logger[ROOT] onto the JUL framework
11:30:00,098 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [FILE] to Logger[ROOT]
11:30:00,098 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [STDOUT] to Logger[ROOT]
11:30:00,099 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [com.kpit] to DEBUG
11:30:00,099 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@ae3540e - Propagating DEBUG level on Logger[com.kpit] onto the JUL framework
11:30:00,100 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [com.kpit] to true
11:30:00,100 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [STDOUT] to Logger[com.kpit]
11:30:00,101 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [com.kpit] to TRACE
11:30:00,104 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@ae3540e - Propagating TRACE level on Logger[com.kpit] onto the JUL framework
11:30:00,107 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [com.kpit] to false
11:30:00,107 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [STDOUT] to Logger[com.kpit]
11:30:00,108 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@345f69f3 - End of configuration.
11:30:00,111 |-INFO in org.springframework.boot.logging.logback.SpringBootJoranConfigurator@35645047 - Registering current configuration as safe fallback point

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.2.0)

11:30:00.258 [main] INFO  c.kpit.tf2.configuration.Application - Starting Application using Java 17.0.9 with PID 18308 (D:\CLAAS\ST-ForTesting\tf2-product-launcher-application\target\classes started by abhijeeta3 in D:\CLAAS\ST-ForTesting\tf2-product-launcher-application)
11:30:00.260 [main] DEBUG c.kpit.tf2.configuration.Application - Running with Spring Boot v3.2.0, Spring v6.1.1
11:30:00.264 [main] INFO  c.kpit.tf2.configuration.Application - No active profile set, falling back to 1 default profile: "default"
org.springframework.boot.SpringApplication$AbandonedRunException
        at org.springframework.boot.SpringApplicationAotProcessor$AotProcessorHook$1.contextLoaded(SpringApplicationAotProcessor.java:101)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$contextLoaded$4(SpringApplicationRunListeners.java:72)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
        at org.springframework.boot.SpringApplicationRunListeners.contextLoaded(SpringApplicationRunListeners.java:72)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:431)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1342)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1331)
        at com.kpit.tf2.configuration.Application.main(Application.java:33)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:281)
        at org.springframework.boot.SpringApplicationAotProcessor.lambda$prepareApplicationContext$0(SpringApplicationAotProcessor.java:62)
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:58)
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:46)
        at org.springframework.boot.SpringApplication.withHook(SpringApplication.java:1442)
        at org.springframework.boot.SpringApplicationAotProcessor$AotProcessorHook.run(SpringApplicationAotProcessor.java:109)
        at org.springframework.boot.SpringApplicationAotProcessor.prepareApplicationContext(SpringApplicationAotProcessor.java:60)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:83)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
        at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
        at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:80)
Exception in thread "main" java.lang.IllegalStateException: No application context available after calling main method of 'com.kpit.tf2.configuration.Application'. Does it run a SpringApplication?
        at org.springframework.boot.SpringApplicationAotProcessor$AotProcessorHook.run(SpringApplicationAotProcessor.java:120)
        at org.springframework.boot.SpringApplicationAotProcessor.prepareApplicationContext(SpringApplicationAotProcessor.java:60)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:83)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
        at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
        at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:80)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.389 s
[INFO] Finished at: 2024-01-12T11:30:00+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:3.2.0:process-aot (process-aot) on project tf2-product-launcher-application: Process terminated with exit code: 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by mamaorha** [comment]
Exception in thread "main" java.lang.IllegalStateException: No application context available after calling main method of 'com.kpit.tf2.configuration.Application'. Does it run a SpringApplication?

do you have tomcat or anything else that will actually run your app? (make sure its compile level rather than runtime)

**Comment by fernando-valdez** [comment]
Hello @abhijeeta94, can you please provide a reproducer so we can see the error locally? also, please share the exact steps you took to build and execute that project

**Comment by abhijeeta94** [comment]
Please clone project provided by graalvm demo - https://github.com/graalvm/graalvm-demos/tree/master/spring-native-image

Then I have installed graalvm version which has jdk version 17.0.9.
Added one plugin in pom.xml
`	<build>
		<plugins>
			<plugin>
				<groupId>org.graalvm.buildtools</groupId>
				<artifactId>native-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>build-native</id>
						<phase>package</phase>
						<goals>
							<goal>build</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<verbose>true</verbose>
					<quickBuild>true</quickBuild>
					<buildArgs combine.children="append">
						<buildArg>-H:+ReportExceptionStackTraces</buildArg>
						<buildArg>-H:-CheckToolchain</buildArg>
					</buildArgs>
				</configuration>
			</plugin>
                 </plugins>
          </build>` 
 
 I have tried tried to hit command **mvnw native:compile -Pnative** 
 Expectation is it should create exe file which I can run and hit provided api - http://localhost:8080/jibber

**Comment by abhijeeta94** [comment]
@mamaorha Yes we are using tomcat which is inbuild in spring boot application

**Comment by oubidar-Abderrahim** [comment]
If the issue persists using the latest GraalVM version with the latest Spring boot, please create a new issue and we can follow up on it
