### ISSUE TITLE
Graphics & Fonts Usage fails

### ISSUE THREAD

**Issue by fellmann** [oracle/graal#817]
Version: GraalVM 1.0.0-RC9

Minimal example:

Example1.java
```java
import java.awt.*;
import java.awt.image.BufferedImage;

public class Example1 {
    public static void main(String[] args) {
        BufferedImage bufferedImage = new BufferedImage(200, 200, BufferedImage.TYPE_INT_ARGB);
        Graphics graphics = bufferedImage.getGraphics();
        graphics.drawString("test", 100, 100);
        graphics.dispose();
    }
}
```

Then run:
```bash
docker run -v $(pwd):/work -w /work --rm -it oracle/graalvm-ce:1.0.0-rc9 sh -c "javac Example1.java && java Example1"
```

Expected: no error
Result:
```
Exception in thread "main" java.lang.NullPointerException
	at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
	at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
	at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
	at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
	at sun.font.SunFontManager$2.run(SunFontManager.java:431)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.SunFontManager.<init>(SunFontManager.java:376)
	at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at java.awt.Font.getFont2D(Font.java:491)
	at java.awt.Font.access$000(Font.java:224)
	at java.awt.Font$FontAccessImpl.getFont2D(Font.java:228)
	at sun.font.FontUtilities.getFont2D(FontUtilities.java:180)
	at sun.java2d.SunGraphics2D.checkFontInfo(SunGraphics2D.java:669)
	at sun.java2d.SunGraphics2D.getFontInfo(SunGraphics2D.java:830)
	at sun.java2d.pipe.GlyphListPipe.drawString(GlyphListPipe.java:50)
	at sun.java2d.pipe.ValidatePipe.drawString(ValidatePipe.java:165)
	at sun.java2d.SunGraphics2D.drawString(SunGraphics2D.java:2928)
	at Example1.main(Example1.java:8)
```

**Comment by dougxc** [comment]
This seems to work fine in the non-docker scenario. Can you please confirm @fellmann .
Also, can you please run `java -Dsun.java2d.debugfonts=true Example1` and post the output here.

**Comment by ansalond** [comment]
@mzachh, could you please `yum install fontconfig` in the Dockerfile?

**Comment by fellmann** [comment]
After some investigation, you were right - fontconfig is missing in the oracle/graalvm-ce package.

Yet, this does not fix the problem, as there seems to be a version clash with the freetype package available in the oracle/graalvm-ce docker image (too old for JRE 8?).

New Error:
```
java: symbol lookup error: /lib64/libfontconfig.so.1: undefined symbol: FT_Get_Advance
```

What works is creating a docker container based on debian:stretch, installing fontconfig package, and then graalvm.

**Comment by ansalond** [comment]
@fellmann, how did you get this error?
```
java: symbol lookup error: /lib64/libfontconfig.so.1: undefined symbol: FT_Get_Advance
```
I can run the previous example after installing `fontconfig`:
```
yum install fontconfig
```

**Comment by fellmann** [comment]
Sorry, I was using a different code. Please consider the following example given some ttf file in the current folder: https://github.com/google/fonts/blob/master/apache/opensans/OpenSans-Regular.ttf . I assume the same error will occur with locally installed fonts.

Example1.java
```java
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class Example1 {
    public static void main(String[] args) throws FontFormatException, IOException {
        BufferedImage bufferedImage = new BufferedImage(200, 200, BufferedImage.TYPE_INT_ARGB);
        Graphics graphics = bufferedImage.getGraphics();
        graphics.setFont(Font.createFont(Font.TRUETYPE_FONT, new File("OpenSans-Regular.ttf")));
        graphics.drawString("test", 100, 100);
        graphics.dispose();
    }
}
```

docker run -v $(pwd):/work -w /work --rm -it oracle/graalvm-ce:1.0.0-rc9 sh -c "yum install fontconfig -y && javac Example1.java && java Example1"

**Comment by ansalond** [comment]
Thanks for the instructions!
I still cannot reproduce the problem. Could you please try the following?

```
$ mkdir graalvm_test
$ cd graalvm_test
$ echo 'import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class Example2 {
    public static void main(String[] args) throws FontFormatException, IOException {
        BufferedImage bufferedImage = new BufferedImage(200, 200, BufferedImage.TYPE_INT_ARGB);
        Graphics graphics = bufferedImage.getGraphics();
        graphics.setFont(Font.createFont(Font.TRUETYPE_FONT, new File("/usr/share/fonts/dejavu/DejaVuSans.ttf")));
        graphics.drawString("test", 100, 100);
        graphics.dispose();
        System.out.println("Done!");
    }
}' >Example2.java
$ docker run -v $(pwd):/work -w /work --rm -it oracle/graalvm-ce:1.0.0-rc9 sh -c "yum install fontconfig -y && javac Example2.java && java Example2"
```

You should see:
```
[...]
Complete!
Done!
```

Also cloning `git@github.com:google/fonts.git` and using `fonts/apache/opensans/OpenSans-Regular.ttf` seems to work.

**Comment by fellmann** [comment]
@ansalond You are right again - it works when you run `yum install fontconfig -y && javac Example2.java && java Example2`. But as soon as the fontconfig is installed in a previous step, it fails. Given as a Dockerfile:
```Dockerfile
FROM oracle/graalvm-ce:1.0.0-rc9
COPY Example2.java /work/
WORKDIR /work
RUN yum install fontconfig -y
RUN javac Example2.java && java Example2
```

**Comment by fellmann** [comment]
Same happens when I add the fontconfig package here: https://github.com/oracle/docker-images/blob/master/GraalVM/CE/1.0.0-rc9/Dockerfile#L29

**Comment by ansalond** [comment]
Thanks, I can now reproduce the issue!

It's really strange, I don't see how this can work:
```
RUN javac Example2.java 
RUN yum install fontconfig -y && java Example2
RUN java Example2
```
while this doesn't:
```
RUN javac Example2.java
RUN yum install fontconfig -y
RUN java Example2
```

**Comment by fellmann** [comment]
Me neither, that's why I shared the wrong example code... Only thing I know that in the second version the commands don't share the same shell session. But that should not affect installed packages?

**Comment by behrica** [comment]
Just bumping in this now as well.
Same exception, but on a completely different setup.

I use
oracle/graalvm-ce:1.0.0-rc9 

on  Arch Linux, no Docker,
using it from Clojure...
Exceptin stacktrace seems to be the same,
fontconfig is installed

```
   FontConfiguration.java: 1264  sun.awt.FontConfiguration/getVersion
    FontConfiguration.java:  219  sun.awt.FontConfiguration/readFontConfigFile
    FontConfiguration.java:  107  sun.awt.FontConfiguration/init
       X11FontManager.java:  774  sun.awt.X11FontManager/createFontConfiguration
       SunFontManager.java:  431  sun.font.SunFontManager$2/run
     AccessController.java:   -2  java.security.AccessController/doPrivileged
       SunFontManager.java:  376  sun.font.SunFontManager/<init>
        FcFontManager.java:   35  sun.awt.FcFontManager/<init>
       X11FontManager.java:   57  sun.awt.X11FontManager/<init>
NativeConstructorAccessorImpl.java:   -2  sun.reflect.NativeConstructorAccessorImpl/newInstance0
NativeConstructorAccessorImpl.java:   62  sun.reflect.NativeConstructorAccessorImpl/newInstance
DelegatingConstructorAccessorImpl.java:   45  sun.reflect.DelegatingConstructorAccessorImpl/newInstance
          Constructor.java:  423  java.lang.reflect.Constructor/newInstance
                Class.java:  442  java.lang.Class/newInstance
   FontManagerFactory.java:   83  sun.font.FontManagerFactory$1/run
     AccessController.java:   -2  java.security.AccessController/doPrivileged
   FontManagerFactory.java:   74  sun.font.FontManagerFactory/getInstance
```

**Comment by behrica** [comment]
The same code on an ubuntu headless server is working fine.

**Comment by behrica** [comment]
Running with debug gives:
```
java -Dsun.java2d.debugfonts=true Example1 
Nov 27, 2018 10:42:11 PM sun.awt.X11FontManager registerFontDir
INFO: ParseFontDir /usr/lib/jvm/java-8-graal/jre/lib/fonts
Nov 27, 2018 10:42:11 PM sun.awt.FontConfiguration <init>
INFO: Creating standard Font Configuration
Nov 27, 2018 10:42:11 PM sun.awt.FontConfiguration <init>
INFO: Creating standard Font Configuration
Nov 27, 2018 10:42:11 PM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no font for sans:regular:roman
Nov 27, 2018 10:42:11 PM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no font for sans:bold:roman
Nov 27, 2018 10:42:11 PM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no font for sans:regular:italic
Nov 27, 2018 10:42:11 PM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no font for sans:bold:italic
Nov 27, 2018 10:42:11 PM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no font for serif:regular:roman
Nov 27, 2018 10:42:11 PM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no font for serif:bold:roman
Nov 27, 2018 10:42:11 PM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no font for serif:regular:italic
Nov 27, 2018 10:42:11 PM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no font for serif:bold:italic
Nov 27, 2018 10:42:11 PM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no font for monospace:regular:roman
Nov 27, 2018 10:42:11 PM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no font for monospace:bold:roman
Nov 27, 2018 10:42:11 PM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no font for monospace:regular:italic
Nov 27, 2018 10:42:11 PM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no font for monospace:bold:italic
Nov 27, 2018 10:42:11 PM sun.font.FontConfigManager initFontConfigFonts
INFO: Fontconfig returned no fonts at all.
Nov 27, 2018 10:42:11 PM sun.font.FcFontConfiguration warning
WARNING: Failed to get info from libfontconfig
Nov 27, 2018 10:42:11 PM sun.font.FcFontConfiguration warning
WARNING: Failed to get info from libfontconfig
Exception in thread "main" java.lang.NullPointerException
	at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
```


I seems to try to read fonts from "/usr/lib/jvm/java-8-graal/jre/lib/fonts" which is not present on my machine. And then it does not search furter.

On my other machine(where it works), the output is different.
Here the JDK font directory is not present neither, but it seems to search somewhere else, and find fonts accordingly. (in /usr/share/fonts)

```
Nov 27, 2018 10:52:57 PM sun.awt.X11FontManager registerFontDir
INFO: ParseFontDir /home/behrica/graalvm-ce-1.0.0-rc9/jre/lib/fonts
Nov 27, 2018 10:52:57 PM sun.awt.FontConfiguration <init>
INFO: Creating standard Font Configuration
Nov 27, 2018 10:52:57 PM sun.awt.FontConfiguration <init>
INFO: Creating standard Font Configuration
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager$2 run
INFO: JRE font directory: /home/behrica/graalvm-ce-1.0.0-rc9/jre/lib/fonts
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager$2 run
INFO: Extra font path: null
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager$2 run
INFO: Debug font path: null
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager initCompositeFonts
INFO: Initialising composite fonts
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager addCompositeToFontList
INFO: Add to Family Serif, Font Serif.plain rank=2
Nov 27, 2018 10:52:57 PM sun.font.FontFamily setFont
INFO: Request to add Serif with style 0 to family Serif
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager initCompositeFonts
INFO: registered Serif.plain
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager addCompositeToFontList
INFO: Add to Family Serif, Font Serif.bold rank=2
Nov 27, 2018 10:52:57 PM sun.font.FontFamily setFont
INFO: Request to add Serif with style 1 to family Serif
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager initCompositeFonts
INFO: registered Serif.bold
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager addCompositeToFontList
INFO: Add to Family Serif, Font Serif.italic rank=2
Nov 27, 2018 10:52:57 PM sun.font.FontFamily setFont
INFO: Request to add Serif with style 2 to family Serif
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager initCompositeFonts
INFO: registered Serif.italic
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager addCompositeToFontList
INFO: Add to Family Serif, Font Serif.bolditalic rank=2
Nov 27, 2018 10:52:57 PM sun.font.FontFamily setFont
INFO: Request to add Serif with style 3 to family Serif
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager initCompositeFonts
INFO: registered Serif.bolditalic
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager addCompositeToFontList
INFO: Add to Family SansSerif, Font SansSerif.plain rank=2
Nov 27, 2018 10:52:57 PM sun.font.FontFamily setFont
INFO: Request to add SansSerif with style 0 to family SansSerif
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager initCompositeFonts
INFO: registered SansSerif.plain
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager addCompositeToFontList
INFO: Add to Family SansSerif, Font SansSerif.bold rank=2
Nov 27, 2018 10:52:57 PM sun.font.FontFamily setFont
INFO: Request to add SansSerif with style 1 to family SansSerif
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager initCompositeFonts
INFO: registered SansSerif.bold
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager addCompositeToFontList
INFO: Add to Family SansSerif, Font SansSerif.italic rank=2
Nov 27, 2018 10:52:57 PM sun.font.FontFamily setFont
INFO: Request to add SansSerif with style 2 to family SansSerif
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager initCompositeFonts
INFO: registered SansSerif.italic
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager addCompositeToFontList
INFO: Add to Family SansSerif, Font SansSerif.bolditalic rank=2
Nov 27, 2018 10:52:57 PM sun.font.FontFamily setFont
INFO: Request to add SansSerif with style 3 to family SansSerif
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager initCompositeFonts
INFO: registered SansSerif.bolditalic
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager addCompositeToFontList
INFO: Add to Family Monospaced, Font Monospaced.plain rank=2
Nov 27, 2018 10:52:57 PM sun.font.FontFamily setFont
INFO: Request to add Monospaced with style 0 to family Monospaced
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager initCompositeFonts
INFO: registered Monospaced.plain
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager addCompositeToFontList
INFO: Add to Family Monospaced, Font Monospaced.bold rank=2
Nov 27, 2018 10:52:57 PM sun.font.FontFamily setFont
INFO: Request to add Monospaced with style 1 to family Monospaced
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager initCompositeFonts
INFO: registered Monospaced.bold
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager addCompositeToFontList
INFO: Add to Family Monospaced, Font Monospaced.italic rank=2
Nov 27, 2018 10:52:57 PM sun.font.FontFamily setFont
INFO: Request to add Monospaced with style 2 to family Monospaced
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager initCompositeFonts
INFO: registered Monospaced.italic
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager addCompositeToFontList
INFO: Add to Family Monospaced, Font Monospaced.bolditalic rank=2
Nov 27, 2018 10:52:57 PM sun.font.FontFamily setFont
INFO: Request to add Monospaced with style 3 to family Monospaced
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager initCompositeFonts
INFO: registered Monospaced.bolditalic
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager addCompositeToFontList
INFO: Add to Family Dialog, Font Dialog.plain rank=2
Nov 27, 2018 10:52:57 PM sun.font.FontFamily setFont
INFO: Request to add Dialog with style 0 to family Dialog
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager initCompositeFonts
INFO: registered Dialog.plain
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager addCompositeToFontList
INFO: Add to Family Dialog, Font Dialog.bold rank=2
Nov 27, 2018 10:52:57 PM sun.font.FontFamily setFont
INFO: Request to add Dialog with style 1 to family Dialog
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager initCompositeFonts
INFO: registered Dialog.bold
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager addCompositeToFontList
INFO: Add to Family Dialog, Font Dialog.italic rank=2
Nov 27, 2018 10:52:57 PM sun.font.FontFamily setFont
INFO: Request to add Dialog with style 2 to family Dialog
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager initCompositeFonts
INFO: registered Dialog.italic
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager addCompositeToFontList
INFO: Add to Family Dialog, Font Dialog.bolditalic rank=2
Nov 27, 2018 10:52:57 PM sun.font.FontFamily setFont
INFO: Request to add Dialog with style 3 to family Dialog
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager initCompositeFonts
INFO: registered Dialog.bolditalic
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager addCompositeToFontList
INFO: Add to Family DialogInput, Font DialogInput.plain rank=2
Nov 27, 2018 10:52:57 PM sun.font.FontFamily setFont
INFO: Request to add DialogInput with style 0 to family DialogInput
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager initCompositeFonts
INFO: registered DialogInput.plain
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager addCompositeToFontList
INFO: Add to Family DialogInput, Font DialogInput.bold rank=2
Nov 27, 2018 10:52:57 PM sun.font.FontFamily setFont
INFO: Request to add DialogInput with style 1 to family DialogInput
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager initCompositeFonts
INFO: registered DialogInput.bold
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager addCompositeToFontList
INFO: Add to Family DialogInput, Font DialogInput.italic rank=2
Nov 27, 2018 10:52:57 PM sun.font.FontFamily setFont
INFO: Request to add DialogInput with style 2 to family DialogInput
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager initCompositeFonts
INFO: registered DialogInput.italic
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager addCompositeToFontList
INFO: Add to Family DialogInput, Font DialogInput.bolditalic rank=2
Nov 27, 2018 10:52:57 PM sun.font.FontFamily setFont
INFO: Request to add DialogInput with style 3 to family DialogInput
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager initCompositeFonts
INFO: registered DialogInput.bolditalic
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager findFont2D
INFO: Search for font: Dialog
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager initialiseDeferredFont
INFO: Opening deferred font file /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
Nov 27, 2018 10:52:57 PM sun.font.TrueTypeFont open
INFO: open TTF: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager addToFontList
INFO: Add to Family DejaVu Sans, Font DejaVu Sans rank=2
Nov 27, 2018 10:52:57 PM sun.font.FontFamily setFont
INFO: Request to add ** TrueType Font: Family=DejaVu Sans Name=DejaVu Sans style=0 fileName=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf with style 0 to family Font family: DejaVu Sans plain=null bold=null italic=null bolditalic=null
Nov 27, 2018 10:52:57 PM sun.font.SunFontManager registerFontFile
INFO: Registered file /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf as font ** TrueType Font: Family=DejaVu Sans Name=DejaVu Sans style=0 fileName=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf rank=2
```

**Comment by behrica** [comment]
I tried all type of workarround from the internet, but nothing worked for me.

**Comment by mzachh** [comment]
@ansalond , @fellmann does it help if you regenerate the fonts cache with `fc-cache -f -v` like: 

```
FROM oracle/graalvm-ce:1.0.0-rc9
COPY Example2.java /work/
WORKDIR /work
RUN yum install fontconfig -y
RUN fc-info -f -v
RUN javac Example2.java && java Example2
```

Need to do some further testing, but if this works we can add this to oracle/graalvm-ce:1.0.0-rc10

**Comment by mzachh** [comment]
Using `RUN fc-info -f -v` fixes the issue for me.

I think it shouldn't be necessary. There might be an issue with the fonts rpm packages. Maybe related to the Docker storage driver. I could confirm the issue with overlayfs2 on XFS.

Anyway, I will add the `RUN fc-info -f -v` to the next `oracle/graalvm-ce` image. I think it is good practice to regenerate the fontconfig-cache after installing new fonts.

**Comment by fellmann** [comment]
@mzachh I can confirm this partly solves the issue.
- The command is `fc-cache --force` for me
- It only works if run after fontconfig install

Working:
```Dockerfile
FROM oracle/graalvm-ce:1.0.0-rc9
COPY Example2.java /work/
WORKDIR /work
RUN yum install fontconfig -y
RUN fc-cache --force
RUN javac Example2.java && java Example2
```

Failing: 
```Dockerfile
FROM oracle/graalvm-ce:1.0.0-rc9
COPY Example2.java /work/
WORKDIR /work
RUN yum install fontconfig -y && fc-cache --force
RUN javac Example2.java && java Example2
```

I also assume a problem with the RPM package or the storage driver - and it would be bad practice to create a new docker layer just for running a single command.

**Comment by mzachh** [comment]
@fellmann thanks for confirming!

The new oracle/graalvm-ce:1.0.0-rc10 image is online with the new fontconfig support, so your examples should work now out-of-the-box.

Indeed, I also recognized that fc-cache and the font RPMs behave strangely. We will discuss this with the  Linux team.
