### ISSUE TITLE
Cannot pass a host custom objects to an Espresso method

### ISSUE THREAD

**Issue by etreliu** [oracle/graal#8175]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: 23.1.1
 - CE or EE: CE
 - JDK version: JDK21
 - OS and OS Version: Windows 10
 - Architecture: amd64

**Have you verified this issue still happens when using the latest snapshot?**
Yes

**Describe the issue**
I cannot pass a Java object from host to the Espresso guest.

I minimized the example to the following:

Create the three following files

Employee.java
package test;

public class Employee {
		
	private String name;
	
	public void setName(String name) {
		this.name = name;
	}
	
	public String getName() {
		return name;
	}
	
}

Guest.java
package test;

public class Guest {
	
	public void setEmployee(Employee employee) {
		System.out.println("Guest Employee = " + employee.getName());
	}
	
}

Host.java
package test;

import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.Value;

public class Host {

	public void test() {
		Employee employee = new Employee();	
		employee.setName("Host to guest name");
		Context context = Context.newBuilder("java").allowAllAccess(true).build();
		Value guest = javavm.getBindings("java").getMember("Guest").newInstance();
		guest.invokeMember("setEmployee", employee);
	}
	
	public static void main(String[] args) throws Exception {
		Host host = new Host();
		host.test();
	}
	
}

**Expected behavior**
Guest Employee = Host to guest name

Instead, the Espresso invocations fail with IllegalArgumentException, see the traces below.

Exception in thread "main" java.lang.IllegalArgumentException: Invalid argument when invoking 'setEmployee' on 'Guest@531cbf7c'(language: Java, type: Guest). Ltest/Employee;Provided arguments: ['Host to guest name'(language: Java, type: test.Employee)].
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch.invalidInvokeArgumentType(PolyglotValueDispatch.java:1460)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$SharedInvokeNode.doDefault(PolyglotValueDispatch.java:4722)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$SharedInvokeNodeGen$Inlined.executeShared(PolyglotValueDispatchFactory.java:10235)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$InvokeNode.doDefault(PolyglotValueDispatch.java:4753)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatchFactory$InteropValueFactory$InvokeNodeGen.executeImpl(PolyglotValueDispatchFactory.java:10463)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:128)
        at org.graalvm.truffle/com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
        at org.graalvm.truffle/com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:102)
        at org.graalvm.truffle/com.oracle.truffle.api.impl.DefaultRuntimeAccessor$DefaultRuntimeSupport.callProfiled(DefaultRuntimeAccessor.java:184)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue.invoke(PolyglotValueDispatch.java:2634)
        at org.graalvm.polyglot/org.graalvm.polyglot.Value.invokeMember(Value.java:974)

**Comment by mukel** [comment]
Note that host and guest Java, even if it's the same language, are isolated from each other e.g. guest Java has its own class hierarchy, different from the host JVM.
You can use type converters to map custom host object to guest objects e.g. see
 https://github.com/oracle/graal/blob/master/docs/reference-manual/java-on-truffle/Interoperability.md#converting-host-objects-to-guest-types-using-type-converters

**Comment by etreliu** [comment]
Thank you!
