### ISSUE TITLE
mx --strict-compliance gate --strict-mode fails on Windows with the compiler suite

### ISSUE THREAD

**Issue by JornVernee** [oracle/graal#833]
When running `mx --strict-compliance gate --strict-mode` on the `compiler` suite it fails during `mx --strict-compliance java_base_unittest` with the following error:

```
Traceback (most recent call last):
  File "J:\Projects\mx2\mx_gate.py", line 419, in gate
    _run_gate(cleanArgs, args, tasks)
  File "J:\Projects\mx2\mx_gate.py", line 561, in _run_gate
    runner(args, tasks)
  File "J:\Projects\graal\compiler\mx.compiler\mx_compiler.py", line 664, in _graal_gate_runner
    compiler_gate_runner(['compiler', 'truffle'], graal_unit_test_runs, graal_bootstrap_tests, tasks, args.extra_vm_argument)
  File "J:\Projects\graal\compiler\mx.compiler\mx_compiler.py", line 496, in compiler_gate_runner
    if t: java_base_unittest(_remove_empty_entries(extraVMarguments) + [])
  File "J:\Projects\graal\compiler\mx.compiler\mx_compiler.py", line 987, in java_base_unittest
    basejdk = mx.JDKConfig(basejdk_dir)
  File "J:\Projects\mx2\mx.py", line 11521, in __init__
    raise JDKConfigException('Javac launcher does not exist: ' + self.java)
JDKConfigException: Javac launcher does not exist: J:\Projects\graal\compiler\mxbuild\jdkbase\bin\java.exe
```

First off, it's printing the wrong path there due to a typo in mx.py [1], it's actually looking for `javac.exe` in that same directory.

There is a `javac` file there, but not `javac.exe`. Also, the `javac` file is 0 bytes.

This looks to me like a symlink is being copied into that folder, which can cause a result like this (file of 0 bytes created), on Windows. I'm not sure how to fix though, sorry.

[1] : https://github.com/graalvm/mx/blob/d283559eae6d87243c02be4c344ac7c41666cd6b/mx.py#L11532

**Comment by wirthi** [comment]
I am closing this stale old ticket. We have come a long way with our Windows support and overall our `mx` implementation since this ticket had been filed.
