### ISSUE TITLE
TestThrottler#testDistributionHighRate fails transiently

### ISSUE THREAD

**Issue by fniephaus** [oracle/graal#8401]
Hi @roberttoyonaga, could you take a look at this? The new test seems to fail sometimes, even here on GitHub:

```
1) com.oracle.svm.test.jfr.TestThrottler#testDistributionHighRate
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.oracle.svm.test.jfr.TestThrottler.expectNear(TestThrottler.java:311)
	at com.oracle.svm.test.jfr.TestThrottler.testDistribution(TestThrottler.java:306)
	at com.oracle.svm.test.jfr.TestThrottler.testDistributionHighRate(TestThrottler.java:236)
```

Example build: https://github.com/oracle/graal/actions/runs/7958635035/job/21723904758?pr=8400#step:14:1966

**Comment by roberttoyonaga** [comment]
Hi @fniephaus! I looked into the problem and made a PR here https://github.com/oracle/graal/pull/8412

**Comment by fniephaus** [comment]
Fixed by https://github.com/oracle/graal/pull/8412
