### ISSUE TITLE
native-image hangs after inlining methods (Windows x64)

### ISSUE THREAD

**Issue by aburnett397** [oracle/graal#8426]
I'm trying building to build a native image from a jar file withe the command:
`native-image --enable-preview -classpath path-to-jar main-class --no-fallback`

After this output:
`[5/8] Inlining methods...     [***]                                                                      (0.4s @ 2.11GB)`
The output freezes until the watchdog stops the process after 10 minutes. During this time, the process is active on a single core. In the thread dump that follows, every thread is waiting except:
`"ForkJoinPool-3-worker-9" Id=118 in RUNNABLE
    at app/org.graalvm.collections/org.graalvm.collections.EconomicMapImpl.findWithCollision(EconomicMapImpl.java:305)
    at app/org.graalvm.collections/org.graalvm.collections.EconomicMapImpl.findHash(EconomicMapImpl.java:292)
    at app/org.graalvm.collections/org.graalvm.collections.EconomicMapImpl.find(EconomicMapImpl.java:253)
    at app/org.graalvm.collections/org.graalvm.collections.EconomicMapImpl.get(EconomicMapImpl.java:244)
    at app/com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.hosted.phases.priorityinline.InterproceduralPartialEscapeAnalysisPhase$a.a(stripped:241)
    at app/com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.hosted.phases.priorityinline.d.a(stripped:140)
    at app/com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.hosted.phases.priorityinline.d.a(stripped:147)
    at app/com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.hosted.phases.priorityinline.d.a(stripped:147)
    at app/com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.hosted.phases.priorityinline.d.a(stripped:85)
    at app/com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.hosted.phases.priorityinline.d$$Lambda/0x0000000801919520.accept(Unknown Source)
    at app/com.oracle.graal.graal_enterprise/com.oracle.graal.phases.preciseinline.priorityinline.nodes.a.c(stripped:452)
    at app/com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.hosted.phases.priorityinline.d.a(stripped:76)
    at app/com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.hosted.phases.priorityinline.SubstratePolicyFactory$a.a(stripped:150)
    at app/com.oracle.graal.graal_enterprise/com.oracle.graal.phases.preciseinline.priorityinline.d.a(stripped:71)
    at app/com.oracle.graal.graal_enterprise/com.oracle.graal.phases.preciseinline.priorityinline.PriorityInliningPhase$a.d(stripped:582)
    at app/com.oracle.graal.graal_enterprise/com.oracle.graal.phases.preciseinline.priorityinline.PriorityInliningPhase$a.c(stripped:537)
    at app/com.oracle.graal.graal_enterprise/com.oracle.graal.phases.preciseinline.priorityinline.PriorityInliningPhase.d(stripped:474)
    at app/com.oracle.graal.graal_enterprise/com.oracle.graal.phases.preciseinline.priorityinline.PriorityInliningPhase.a(stripped:469)
    at app/com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.hosted.phases.priorityinline.SubstratePriorityInliningPhase.a(stripped:191)
    at app/com.oracle.svm.svm_enterprise/com.oracle.svm.enterprise.hosted.phases.priorityinline.SubstratePriorityInliningPhase.run(stripped:76)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:434)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:322)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:390)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:434)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:322)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:294)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:169)
    at platform/jdk.internal.vm.compiler/org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:137)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:1310)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue$$Lambda/0x000000080190e628.compile(Unknown Source)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:1258)
    at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:306)
    at app/org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:187)
    at app/org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:171)
    at app/org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor$$Lambda/0x000000080143ef48.run(Unknown Source)
    at java.base@21.0.2/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
    at java.base@21.0.2/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
    at java.base@21.0.2/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
    at java.base@21.0.2/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
    at java.base@21.0.2/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
    at java.base@21.0.2/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)`

A quick look at [EconomicMapImpl.java](https://github.com/oracle/graal/blob/c5c5934e912166b712a8802374ff3479452e3ac5/sdk/src/org.graalvm.collections/src/org/graalvm/collections/EconomicMapImpl.java) indicates that the process is indeed stuck in a loop.

Is there anything I can do narrow down the responsible code? This is coming from a rather large project. --verbose provides no extra hints.

I'm using GraalVM 21.0.2+13.1 on windows 11.

**Comment by fniephaus** [comment]
Hi @aburnett397, thanks for raising this! It seems there are a lot of hash collisions in one or more EconomicMaps when Native Image builds your application. Could you try reproduce this on the [latest EA build](https://github.com/graalvm/oracle-graalvm-ea-builds/releases)? Is there any way you could share a reproducer with us? We'd like to take a look at why there an increased amount of collisions.

**Comment by aburnett397** [comment]
@fniephaus Yes, the latest EA build does solve the issue. 
I am now however running into an exception at image creation
`com.oracle.svm.core.util.VMError$HostedError: should not reach here: unexpected input could not be handled: 2`
I will post a new issue if I can't figure this out.

**Comment by aburnett397** [comment]
@fniephaus As for a reproducer, I really can't. After making some modifications to try graalvm for java 22, the bug no longer appears even when using the current java 21 version. All I can say is that the code consists in part of many auto-generated source files with identical templating, perhaps a weak spot for the hashing mecanism?

**Comment by fniephaus** [comment]
> As for a reproducer, I really can't. After making some modifications to try graalvm for java 22, the bug no longer appears even when using the current java 21 version. All I can say is that the code consists in part of many auto-generated source files with identical templating, perhaps a weak spot for the hashing mecanism?

Ok, let me close this ticket for now. Auto-generated sources shouldn't be the problem, but do let us know if you can reproduce this again.

**Comment by DraconicOv** [comment]
@aburnett39 I also ended up getting the error
 ` com.oracle.svm.core.util.VMError$HostedError: should not reach here: unexpected input could not be handled: 2`, how did you resolve it?

**Comment by aburnett397** [comment]
@DraconicOv By switching back to Java 21, I only had the error with the early access Java 22.
