### ISSUE TITLE
Bytecode parsing occasionally self-destructs

### ISSUE THREAD

**Issue by dmlloyd** [oracle/graal#844]
It's usually ultimately due to some unrelated code problem, but the error doesn't give much information to go on:

```
fatal error: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.svm.core.util.VMError$HostedError: missing implementation for runtime call: deoptimize(long,SpeculationReason)void
	at parsing com.oracle.svm.hosted.snippets.DeoptHostedSnippets.deoptSnippet(DeoptHostedSnippets.java:106)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:418)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:278)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:375)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:104)
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.svm.core.util.VMError$HostedError: missing implementation for runtime call: deoptimize(long,SpeculationReason)void
	at parsing com.oracle.svm.hosted.snippets.DeoptHostedSnippets.deoptSnippet(DeoptHostedSnippets.java:106)
	at org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2415)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:93)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3155)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:2959)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:889)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:783)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:95)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at org.graalvm.compiler.replacements.ReplacementsImpl$GraphMaker.buildInitialGraph(ReplacementsImpl.java:501)
	at com.oracle.svm.hosted.code.SubstrateGraphMaker.buildInitialGraph(SubstrateGraphMaker.java:66)
	at org.graalvm.compiler.replacements.ReplacementsImpl$GraphMaker.makeGraph(ReplacementsImpl.java:399)
	at org.graalvm.compiler.replacements.ReplacementsImpl.makeGraph(ReplacementsImpl.java:359)
	at com.oracle.svm.core.graal.meta.SubstrateReplacements.registerSnippet(SubstrateReplacements.java:220)
	at org.graalvm.compiler.replacements.SnippetTemplate$AbstractTemplates.snippet(SnippetTemplate.java:629)
	at com.oracle.svm.core.graal.snippets.SubstrateTemplates.snippet(SubstrateTemplates.java:66)
	at com.oracle.svm.core.graal.snippets.SubstrateTemplates.snippet(SubstrateTemplates.java:61)
	at com.oracle.svm.hosted.snippets.DeoptHostedSnippets.access$000(DeoptHostedSnippets.java:63)
	at com.oracle.svm.hosted.snippets.DeoptHostedSnippets$DeoptimizeLowering.<init>(DeoptHostedSnippets.java:139)
	at com.oracle.svm.hosted.snippets.DeoptHostedSnippets.<init>(DeoptHostedSnippets.java:130)
	at com.oracle.svm.hosted.snippets.DeoptHostedSnippets.registerLowerings(DeoptHostedSnippets.java:123)
	at com.oracle.svm.hosted.NativeImageGenerator.registerReplacements(NativeImageGenerator.java:1090)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:587)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:401)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.svm.core.util.VMError$HostedError: missing implementation for runtime call: deoptimize(long,SpeculationReason)void
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:66)
	at com.oracle.svm.core.graal.meta.SubstrateForeignCallsProvider.lookupForeignCall(SubstrateForeignCallsProvider.java:62)
	at com.oracle.svm.core.graal.meta.SubstrateForeignCallsProvider.isReexecutable(SubstrateForeignCallsProvider.java:69)
	at org.graalvm.compiler.nodes.extended.ForeignCallNode.hasSideEffect(ForeignCallNode.java:147)
	at org.graalvm.compiler.nodes.graphbuilderconf.GraphBuilderContextUtil.setStateAfterIfNecessary(GraphBuilderContext.java:372)
	at org.graalvm.compiler.nodes.graphbuilderconf.GraphBuilderContext.add(GraphBuilderContext.java:108)
	at org.graalvm.compiler.nodes.extended.ForeignCallNode.intrinsify(ForeignCallNode.java:99)
	at com.oracle.svm.core.graal.snippets.Plugin_SubstrateIntrinsics_runtimeCall__1.execute(PluginFactory_SubstrateIntrinsics.java:107)
	at org.graalvm.compiler.java.BytecodeParser.tryInvocationPlugin(BytecodeParser.java:2165)
	at org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1696)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1461)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1443)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:4945)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3150)
	... 28 more
Error: Image building with exit status 1
```

**Comment by dmlloyd** [comment]
Really this comes from a bad, bad try/finally block in NativeImageGenerator.  It does all kinds of things with the "bigbang" field, which is not initialized until partway through the try block, so if anything fails before that point, it blows up in the finally block leaving no hint as to what happened.

**Comment by dmlloyd** [comment]
I modified `com.oracle.svm.core.graal.meta.SubstrateForeignCallsProvider` to bluff past the problem to see if any more interesting information was forthcoming, but still ended up failing in a similar way:

```

**Comment by dmlloyd** [comment]
I made it dump the whole map of foreign calls and it looks like this:

```
	arithmeticCos(double)double -> RuntimeCall<Math.arithmeticCos>
	arithmeticExp(double)double -> RuntimeCall<StrictMath.arithmeticExp>
	arithmeticLog(double)double -> RuntimeCall<Math.arithmeticLog>
	arithmeticLog10(double)double -> RuntimeCall<Math.arithmeticLog10>
	arithmeticPow(double,double)double -> RuntimeCall<StrictMath.arithmeticPow>
	arithmeticSin(double)double -> RuntimeCall<Math.arithmeticSin>
	arithmeticTan(double)double -> RuntimeCall<Math.arithmeticTan>
	attachThread(Isolate,int)int -> RuntimeCall<CEntryPointSnippets.attachThread>
	checkArrayHub(DynamicHub)void -> RuntimeCall<AllocationSnippets.checkArrayHub>
	checkDynamicHub(DynamicHub)void -> RuntimeCall<AllocationSnippets.checkDynamicHub>
	clone()Object -> RuntimeCall<Object.clone>
	createArrayStoreException(Object)ArrayStoreException -> RuntimeCall<ImplicitExceptions.createArrayStoreException>
	createClassCastException(Object,Class)ClassCastException -> RuntimeCall<ImplicitExceptions.createClassCastException>
	createDivisionByZeroException()ArithmeticException -> RuntimeCall<ImplicitExceptions.createDivisionByZeroException>
	createIsolate(CEntryPointCreateIsolateParameters,int)int -> RuntimeCall<CEntryPointSnippets.createIsolate>
	createNullPointerException()NullPointerException -> RuntimeCall<ImplicitExceptions.createNullPointerException>
	createOutOfBoundsException(int,int)ArrayIndexOutOfBoundsException -> RuntimeCall<ImplicitExceptions.createOutOfBoundsException>
	detachThreadMT(IsolateThread)int -> RuntimeCall<CEntryPointSnippets.detachThreadMT>
	doArraycopy(Object,int,Object,int,int)void -> RuntimeCall<ArraycopySnippets.doArraycopy>
	enterIsolateMT(Isolate)int -> RuntimeCall<CEntryPointSnippets.enterIsolateMT>
	enterSlowPathNativeToJava()void -> RuntimeCall<Safepoint.enterSlowPathNativeToJava>
	enterSlowPathSafepointCheck()void -> RuntimeCall<Safepoint.enterSlowPathSafepointCheck>
	failFatally(int,CCharPointer)void -> RuntimeCall<CEntryPointSnippets.failFatally>
	indexOf1Byte(Pointer,int,byte)int -> RuntimeCall<AMD64ArrayIndexOfForeignCalls.indexOf1Byte>
	indexOf1Char(Pointer,int,char)int -> RuntimeCall<AMD64ArrayIndexOfForeignCalls.indexOf1Char>
	indexOf2Bytes(Pointer,int,byte,byte)int -> RuntimeCall<AMD64ArrayIndexOfForeignCalls.indexOf2Bytes>
	indexOf2Chars(Pointer,int,char,char)int -> RuntimeCall<AMD64ArrayIndexOfForeignCalls.indexOf2Chars>
	indexOf3Bytes(Pointer,int,byte,byte,byte)int -> RuntimeCall<AMD64ArrayIndexOfForeignCalls.indexOf3Bytes>
	indexOf3Chars(Pointer,int,char,char,char)int -> RuntimeCall<AMD64ArrayIndexOfForeignCalls.indexOf3Chars>
	indexOf4Bytes(Pointer,int,byte,byte,byte,byte)int -> RuntimeCall<AMD64ArrayIndexOfForeignCalls.indexOf4Bytes>
	indexOf4Chars(Pointer,int,char,char,char,char)int -> RuntimeCall<AMD64ArrayIndexOfForeignCalls.indexOf4Chars>
	indexOfTwoConsecutiveBytes(Pointer,int,int)int -> RuntimeCall<AMD64ArrayIndexOfForeignCalls.indexOfTwoConsecutiveBytes>
	indexOfTwoConsecutiveChars(Pointer,int,int)int -> RuntimeCall<AMD64ArrayIndexOfForeignCalls.indexOfTwoConsecutiveChars>
	isAttachedMT(Isolate)boolean -> RuntimeCall<CEntryPointSnippets.isAttachedMT>
	monitorEnter(Object)void -> RuntimeCall<MonitorSupport.monitorEnter>
	monitorExit(Object)void -> RuntimeCall<MonitorSupport.monitorExit>
	newMultiArray(DynamicHub,int,Pointer,AllocationCounter)Object -> RuntimeCall<AllocationSnippets.newMultiArray>
	registerFinalizer(Object)void -> RuntimeCall<SnippetRuntime.registerFinalizer>
	reportException(Throwable)int -> RuntimeCall<CEntryPointSnippets.reportException>
	reportRuntimeAssertionFatal(Object)void -> RuntimeCall<SnippetRuntime.reportRuntimeAssertionFatal>
	reportRuntimeAssertionFatalDouble(Object,double)void -> RuntimeCall<SnippetRuntime.reportRuntimeAssertionFatalDouble>
	reportRuntimeAssertionFatalFloat(Object,float)void -> RuntimeCall<SnippetRuntime.reportRuntimeAssertionFatalFloat>
	reportRuntimeAssertionFatalInt(Object,int)void -> RuntimeCall<SnippetRuntime.reportRuntimeAssertionFatalInt>
	reportRuntimeAssertionFatalLong(Object,long)void -> RuntimeCall<SnippetRuntime.reportRuntimeAssertionFatalLong>
	reportRuntimeAssertionFatalObj(Object,Object)void -> RuntimeCall<SnippetRuntime.reportRuntimeAssertionFatalObj>
	reportRuntimeAssertionFatalObjObj(Object,String,Throwable)void -> RuntimeCall<SnippetRuntime.reportRuntimeAssertionFatalObjObj>
	reportTypeAssertionError(byte[],Object)void -> RuntimeCall<SnippetRuntime.reportTypeAssertionError>
	slowPathNewArray(DynamicHub,int)Object -> RuntimeCall<ThreadLocalAllocation.slowPathNewArray>
	slowPathNewArray(PinnedAllocatorImpl,DynamicHub,int)Object -> RuntimeCall<PinnedAllocatorImpl.slowPathNewArray>
	slowPathNewInstance(DynamicHub)Object -> RuntimeCall<ThreadLocalAllocation.slowPathNewInstance>
	slowPathNewInstance(PinnedAllocatorImpl,DynamicHub)Object -> RuntimeCall<PinnedAllocatorImpl.slowPathNewInstance>
	tearDownIsolate()int -> RuntimeCall<CEntryPointSnippets.tearDownIsolate>
	throwCachedArithmeticException()void -> RuntimeCall<ImplicitExceptions.throwCachedArithmeticException>
	throwCachedArrayStoreException()void -> RuntimeCall<ImplicitExceptions.throwCachedArrayStoreException>
	throwCachedClassCastException()void -> RuntimeCall<ImplicitExceptions.throwCachedClassCastException>
	throwCachedNullPointerException()void -> RuntimeCall<ImplicitExceptions.throwCachedNullPointerException>
	throwCachedOutOfBoundsException()void -> RuntimeCall<ImplicitExceptions.throwCachedOutOfBoundsException>
	throwNewArithmeticException()void -> RuntimeCall<ImplicitExceptions.throwNewArithmeticException>
	throwNewArrayStoreException()void -> RuntimeCall<ImplicitExceptions.throwNewArrayStoreException>
	throwNewClassCastException()void -> RuntimeCall<ImplicitExceptions.throwNewClassCastException>
	throwNewNullPointerException()void -> RuntimeCall<ImplicitExceptions.throwNewNullPointerException>
	throwNewOutOfBoundsException()void -> RuntimeCall<ImplicitExceptions.throwNewOutOfBoundsException>
	unreachedCode()void -> RuntimeCall<SnippetRuntime.unreachedCode>
	unresolved(String)void -> RuntimeCall<SnippetRuntime.unresolved>
	unwindException(Throwable,Pointer,CodePointer)void -> RuntimeCall<SnippetRuntime.unwindException>
```

It sure looks like the DeoptimizationFeature didn't get installed... but why?

**Comment by christianwimmer** [comment]
What GraalVM version are you using? There were some recent changes that make `DeoptimizationFeature` optional (because you only need it when you build an image that contains Truffle languages and the Graal compiler for runtime compilation).

**Comment by christianwimmer** [comment]
The relevant code (latest master version) in `DeoptHostedSnippet.deoptSnippet` looks like the following: 
```
        } else if (reason == DeoptimizationReason.TransferToInterpreter) {
            if (DeoptimizationSupport.enabled()) {
                /* We use this reason in TestDeoptimizeNode for deoptimization testing. */
                runtimeCall(DeoptimizationRuntime.DEOPTIMIZE, Deoptimizer.encodeDeoptActionAndReasonToLong(DeoptimizationAction.None, DeoptimizationReason.TransferToInterpreter, 0), null);
```
This means that the code path to the reference of `DeoptimizationRuntime.DEOPTIMIZE` is conditional on `DeoptimizationSupport.enabled()`. This method is annotated with `@Fold` and therefore constant-folded during bytecode parsing.

The handling of `@Fold` methods is done using a graph builder plugin that is generated by an annotation processor by the Java compiler. So in case you are working on a source code build (and not a GraalVM release), you must have a class `Plugin_DeoptimizationSupport_enabled`. If the annotation processor did not run correctly and this file is missing, then the method `DeoptimizationSupport.enabled()` is not constant folded during bytecode parsing, which would lead to the symptom that you are experiencing.

**Comment by dmlloyd** [comment]
This error occurs with the GraalVM RC10 release.  My attempts to debug it are based on the vm-1.0.0-rc10 tag but the symptom reproduces with the official release for us.

**Comment by dmlloyd** [comment]
We do not have any truffle languages in the image AFAICT.  I'm not sure I can come up with a minimum shareable reproducer though.  Our command line looks like this:
```
native-image \
    -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime \
    -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 \
    -H:-PrintAnalysisCallTree -H:EnableURLProtocols=http \
    -H:-JNI \
    --no-server \
    -H:-UseServiceLoaderFeature \
    -H:+StackTrace \
    -jar <jarname>.jar
```
Plus a few `-J-Dxxx=yyy` system properties being set.

**Comment by dmlloyd** [comment]
Here's the error if I add `-H:Features=com.oracle.svm.graal.hosted.DeoptimizationFeature` manually:

```
error: ImageSingletons.add must not overwrite existing key com.oracle.svm.core.deopt.DeoptimizationSupport
Existing value: com.oracle.svm.core.deopt.DeoptimizationSupport@5dbc2c90
New value: com.oracle.svm.core.deopt.DeoptimizationSupport@789d6bb1
```

**Comment by christianwimmer** [comment]
`com.oracle.svm.graal.hosted.DeoptimizationFeature` should be the only place that registers the `DeoptimizationSupport` singleton (using `ImageSingletons.add(DeoptimizationSupport.class ...`)

Can you debug `ImageSingletons.add` to find out who else registers the `DeoptimiationSupport`?

**Comment by dmlloyd** [comment]
The stack traces seem identical:

```
java.lang.Throwable: Registered here
	at org.graalvm.nativeimage.ImageSingletons.add(ImageSingletons.java:73)
	at com.oracle.svm.core.deopt.DeoptimizationFeature.afterRegistration(DeoptimizationSupport.java:82)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$doRun$2(NativeImageGenerator.java:513)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:513)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:401)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
java.lang.Throwable: Registered here
	at org.graalvm.nativeimage.ImageSingletons.add(ImageSingletons.java:73)
	at com.oracle.svm.graal.hosted.DeoptimizationFeature.afterRegistration(DeoptimizationFeature.java:82)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$doRun$2(NativeImageGenerator.java:513)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:513)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:401)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by christianwimmer** [comment]
No, you have `com.oracle.svm.graal.hosted.DeoptimizationFeature` and `com.oracle.svm.core.deopt.DeoptimizationFeature` (note the different package).

`com.oracle.svm.core.deopt.DeoptimizationFeature` was deleted recently - it should no longer exist.

**Comment by dmlloyd** [comment]
Ah your right, my IDE just completed it for me and I didn't read it.

**Comment by dmlloyd** [comment]
I guess I'm confused.  I added -H:Features=com.oracle.svm.graal.hosted.DeoptimizationFeature and got the error about `com.oracle.svm.core.deopt.DeoptimizationSupport` (not `*Feature`).  The two identical stack traces above are where `com.oracle.svm.core.deopt.DeoptimizationSupport` was registered from.

**Comment by dmlloyd** [comment]
...which leads me to think that it must be enabled?  but then, how does its entry not end up registered in the foreign calls map?

**Comment by dmlloyd** [comment]
yeah it's definitely registered because if I leave my (original) stack trace thing in and don't give `-H:Feature:...` I still get one stack trace printed.  So it's just the mystery as to why the registration didn't work right.  I'll keep debugging this...

**Comment by dmlloyd** [comment]
OK I think I can say fairly definitively that `com.oracle.svm.graal.hosted.DeoptimizationFeature#afterRegistration` is being called but `com.oracle.svm.graal.hosted.DeoptimizationFeature#registerForeignCalls` is not.

**Comment by dmlloyd** [comment]
it's a bit weird because it's like the value disappeared from the list between `NativeImageGenerator.java:513` and `NativeImageGenerator.java:587`... yet nothing removes from the `com.oracle.svm.hosted.FeatureHandler#featureInstances` list, it only ever adds.  Unless they're somehow distinct invocations, checking that next.

**Comment by dmlloyd** [comment]
What is stumping me is that I don't see how my local code changes could be taking effect if I had some out of date build, yet I can't find any cached files or sources for "com.oracle.svm.core.deopt.DeoptimizationFeature".  And, why would the problem also affect the official release?  This is pretty odd.

**Comment by dmlloyd** [comment]
I guess there must be something really weird about one of our generated classes?

**Comment by dmlloyd** [comment]
Oh man - yeah - it has a Class-Path which pulls in RC9 classes.  Arrrrgh

**Comment by dmlloyd** [comment]
I guess this was environmental.  Sorry for all the noise.
