### ISSUE TITLE
GraalVM error with sbt nativeImage plugin : Registering type as reachable after analysis when using google-cloud-compute library

### ISSUE THREAD

**Issue by CallisteH** [oracle/graal#8461]
**Describe the issue**
I try to build a simple [hello-world](https://github.com/CallisteH/scala-hello-world) application with the [sbt-native-image](https://github.com/scalameta/sbt-native-image/tree/main) plugin. 
When I'm running `sbt nativeImage`, everything works well if I don't use extra libraries.
However, if I decide to add the [google-cloud-compute](https://github.com/googleapis/google-cloud-java/tree/main/java-compute) library and run `sbt nativeImage`, I get "shouldNotReach" error (see the logs below). 

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. clone the repo
   git clone https://github.com/CallisteH/scala-hello-world.git
2. compile with graalVM
   ```
      sbt nativeImage
   ``` 

**Environment**
 - GraalVM version : 22.3.3
 - JDK  version: openjdk version "19.0.2" 
 - OS: ubuntu 22.04
 - Architecture: amd64

**More details**
Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
[info] welcome to sbt 1.9.8 (Private Build Java 19.0.2)
[info] loading settings for project hello-world-build from plugins.sbt ...
[info] loading project definition from /home/chanriat/seed/seed-steer-update/steer-powercontrol/tmp/scala-example/hello-world/project
[info] loading settings for project helloWorld from build.sbt ...
[info] set current project to helloWorld (in build file:/home/chanriat/seed/seed-steer-update/steer-powercontrol/tmp/scala-example/hello-world/)
[warn] there are 2 keys that are not used by any other settings/tasks:
[warn]  
[warn] * helloWorld / nativeImageJvm
[warn]   +- /home/chanriat/seed/seed-steer-update/steer-powercontrol/tmp/scala-example/hello-world/build.sbt:13
[warn] * helloWorld / nativeImageVersion
[warn]   +- /home/chanriat/seed/seed-steer-update/steer-powercontrol/tmp/scala-example/hello-world/build.sbt:12
[warn]  
[warn] note: a setting might still be used by a command; to exclude a key from this `lintUnused` check
[warn] either append it to `Global / excludeLintKeys` or call .withRank(KeyRanks.Invisible) on the key
[info] /home/chanriat/.cache/coursier/jvm/graalvm-java17@22.3.3/bin/native-image -cp /home/chanriat/seed/seed-steer-update/steer-powercontrol/tmp/scala-example/hello-world/target/native-image-internal/manifest.jar -H:+TraceNativeToolUsage helloWorld /home/chanriat/seed/seed-steer-update/steer-powercontrol/tmp/scala-example/hello-world/target/native-image/helloWorld
========================================================================================================================
GraalVM Native Image: Generating '/home/chanriat/seed/seed-steer-update/steer-powercontrol/tmp/scala-example/hello-world/target/native-image/helloWorld' (executable)...
========================================================================================================================
>> /usr/bin/gcc -v
># Using built-in specs.
># COLLECT_GCC=/usr/bin/gcc
># COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
># OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
># OFFLOAD_TARGET_DEFAULT=1
># Target: x86_64-linux-gnu
># Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.4.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
># Thread model: posix
># Supported LTO compression algorithms: zlib zstd
># gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04) 
>> /usr/bin/gcc -Wall -Werror -o /tmp/SVM-14139785684025835649/AMD64LibCHelperDirectives /tmp/SVM-14139785684025835649/AMD64LibCHelperDirectives.c
>> /usr/bin/gcc -Wall -Werror -o /tmp/SVM-14139785684025835649/PosixDirectives /tmp/SVM-14139785684025835649/PosixDirectives.c
>> /usr/bin/gcc -Wall -Werror -o /tmp/SVM-14139785684025835649/AArch64LibCHelperDirectives /tmp/SVM-14139785684025835649/AArch64LibCHelperDirectives.c
>> /usr/bin/gcc -Wall -Werror -I/home/chanriat/.cache/coursier/jvm/graalvm-java17@22.3.3/include/linux -o /tmp/SVM-14139785684025835649/JNIHeaderDirectives /tmp/SVM-14139785684025835649/JNIHeaderDirectives.c
>> /usr/bin/gcc -Wall -Werror -o /tmp/SVM-14139785684025835649/BuiltinDirectives /tmp/SVM-14139785684025835649/BuiltinDirectives.c
Warning: Could not resolve com.google.auth.appengine.AppEngineCredentials for reflection configuration. Reason: java.lang.ClassNotFoundException: com.google.auth.appengine.AppEngineCredentials.
Warning: Could not resolve org.apache.commons.pool2.impl.DefaultEvictionPolicy for reflection configuration. Reason: java.lang.ClassNotFoundException: org.apache.commons.pool2.impl.DefaultEvictionPolicy.
Warning: Could not register io.grpc.netty.shaded.io.netty.handler.codec.compression.Lz4FrameDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Exception.
Warning: Could not register io.grpc.netty.shaded.io.netty.handler.codec.compression.Lz4FrameEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Exception.
Warning: Could not register io.grpc.netty.shaded.io.netty.handler.codec.marshalling.CompatibleMarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.grpc.netty.shaded.io.netty.handler.codec.marshalling.CompatibleMarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
Warning: Could not register io.grpc.netty.shaded.io.netty.handler.codec.marshalling.MarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.grpc.netty.shaded.io.netty.handler.codec.marshalling.MarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
Warning: Could not register io.grpc.netty.shaded.io.netty.handler.codec.compression.Lz4FrameDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Exception.
Warning: Could not register io.grpc.netty.shaded.io.netty.handler.codec.compression.Lz4FrameEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Exception.
Warning: Could not register io.grpc.netty.shaded.io.netty.handler.codec.marshalling.CompatibleMarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.grpc.netty.shaded.io.netty.handler.codec.marshalling.CompatibleMarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
Warning: Could not register io.grpc.netty.shaded.io.netty.handler.codec.marshalling.MarshallingDecoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteInput.
Warning: Could not register io.grpc.netty.shaded.io.netty.handler.codec.marshalling.MarshallingEncoder: queryAllPublicMethods for reflection. Reason: java.lang.NoClassDefFoundError: org/jboss/marshalling/ByteOutput.
[1/7] Initializing...                                                                                   (23.7s @ 0.43GB)
 Version info: 'GraalVM 22.3.3 Java 17 CE'
 Java version info: '17.0.8+7-jvmci-22.3-b22'
 C compiler: gcc (linux, x86_64, 11.4.0)
 Garbage collector: Serial GC
 5 user-specific feature(s)
 - com.google.api.gax.grpc.nativeimage.GrpcNettyFeature
 - com.google.api.gax.nativeimage.GoogleJsonClientFeature
 - com.google.api.gax.nativeimage.OpenCensusFeature
 - com.oracle.svm.polyglot.scala.ScalaFeature
 - com.oracle.svm.thirdparty.gson.GsonFeature
Feb 27, 2024 5:27:20 PM com.google.api.gax.nativeimage.NativeImageUtils registerClassForReflection
WARNING: Failed to find io.grpc.netty.shaded.io.netty.channel.ProtocolNegotiators on the classpath for reflection.
[2/7] Performing analysis...  [**************]                                                         (251.7s @ 3.32GB)
  15,142 (90.68%) of 16,698 classes reachable
  40,068 (67.34%) of 59,498 fields reachable
 281,977 (82.14%) of 343,276 methods reachable
   3,742 classes, 1,406 fields, and 233,238 methods registered for reflection
      63 classes,    68 fields, and    55 methods registered for JNI access
       4 native libraries: dl, pthread, rt, z
[3/7] Building universe...                                                                              (21.4s @ 3.51GB)
[4/7] Parsing methods...      [****]                                                                    (20.9s @ 2.62GB)
[5/7] Inlining methods...     [***]                                                                      (9.2s @ 2.93GB)
[6/7] Compiling methods...    [************]                                                           (162.6s @ 3.36GB)
Fatal error: com.oracle.svm.core.util.VMError$HostedError: com.oracle.svm.core.util.VMError$HostedError: Registering type as reachable after analysis: AnalysisType<java.util.concurrent.ConcurrentSkipListMap$Values, allocated: 0, inHeap: 0, reachable: 0>
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:72)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:696)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
Caused by: com.oracle.svm.core.util.VMError$HostedError: Registering type as reachable after analysis: AnalysisType<java.util.concurrent.ConcurrentSkipListMap$Values, allocated: 0, inHeap: 0, reachable: 0>
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.registerAsReachable(AnalysisConstantReflectionProvider.java:252)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.HostedDynamicHubFeature.replace(HostedDynamicHubFeature.java:52)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:595)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageHeap.addArrayElements(NativeImageHeap.java:576)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageHeap.addObjectToImageHeap(NativeImageHeap.java:473)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageHeap.addObject(NativeImageHeap.java:295)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageHeap.processAddObjectWorklist(NativeImageHeap.java:598)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageHeap.addTrailingObjects(NativeImageHeap.java:198)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:678)
        ... 4 more

[7/7] Creating image...                                                                                  (0.0s @ 3.12GB)
------------------------------------------------------------------------------------------------------------------------
                       56.8s (10.8% of total time) in 189 GCs | Peak RSS: 5.78GB | CPU load: 5.58
========================================================================================================================
Failed generating '/home/chanriat/seed/seed-steer-update/steer-powercontrol/tmp/scala-example/hello-world/target/native-image/helloWorld' after 8m 42s.
Error: Image build request failed with exit status 1
[error] native-image command failed with exit code '1'
[error] (nativeImage) native-image command failed with exit code '1'
[error] Total time: 528 s (08:48), completed Feb 27, 2024, 5:35:39 PM```

**Comment by fniephaus** [comment]
Thanks for raising this, @CallisteH. JDK 19 is no longer supported and actually quite old. Could you please try with a JDK 21 build of GraalVM? Hopefully, this will give you a much better error message, or even just work. :)

**Comment by CallisteH** [comment]
Thanks for the reply @fniephaus 
Your suggestion worked ! 

Here is the git diff : 
```
-        nativeImageVersion := "22.3.3",
-        nativeImageJvm := "graalvm-java17",
+        nativeImageVersion := "21.0.2",
+        nativeImageJvm := "graalvm-java21",
```

Thanks again !

**Comment by fniephaus** [comment]
Nice! Glad it's working just fine now! :)
