### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Invalid logger interface org.hibernate.validator.internal.util.logging.Log (implementation not found in jdk.internal.loader.ClassLoaders$AppClassLoader@2f7c7260)

### ISSUE THREAD

**Issue by anshu-zs** [oracle/graal#8474]
Hi,
I am having an issue mentioned below while running the artifact using nativeRun. (nativeCompile worked properly)

```
Caused by: java.lang.IllegalArgumentException: Invalid logger interface org.hibernate.validator.internal.util.logging.Log (implementation not found in jdk.internal.loader.ClassLoaders$AppClassLoader@2f7c7260)
	at org.jboss.logging.Logger.doGetMessageLogger(Logger.java:2564)
	at org.jboss.logging.Logger.getMessageLogger(Logger.java:2530)
	at org.jboss.logging.Logger.getMessageLogger(Logger.java:2516)
	at org.hibernate.validator.internal.util.logging.LoggerFactory.make(LoggerFactory.java:22)
	at org.hibernate.validator.internal.util.Version.<clinit>(Version.java:20)
```

I am using an in-house framework (not a spring project).

Did anyone find this issue or seen this issue before?

**GraalVM version:**

- java 21.0.2 2024-01-16 LTS
- Java(TM) SE Runtime Environment Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30)
- Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30, mixed mode, sharing)
- OS: macOS Sonoma -v 14.3.1
- Architecture: arm64

### **Graal vm gradle configuration**
```
graalvmNative {
    binaries {
        main {
            javaLauncher = javaToolchains.launcherFor {
                languageVersion = JavaLanguageVersion.of(21)
            }
            configurationFileDirectories.from(file('native-config/run'))

            imageName.set('app')
            buildArgs.add('--verbose')
            buildArgs.add('--add-opens=java.base/java.nio=ALL-UNNAMED')
            buildArgs.add('--add-opens=java.base/jdk.internal.misc=ALL-UNNAMED')
            buildArgs.add('--add-opens=java.base/jdk.internal.ref=ALL-UNNAMED')
            buildArgs.add('--trace-class-initialization=ch.qos.logback.classic.Logger')
            buildArgs.add('--trace-object-instantiation=ch.qos.logback.core.AsyncAppenderBase$Worker')
            buildArgs.add('--initialize-at-build-time=org.slf4j.LoggerFactory,ch.qos.logback')
            buildArgs.add('--initialize-at-run-time=io.netty')
            buildArgs.add('--initialize-at-run-time=!org.hibernate.validator.internal.util.logging.Log')
        }
    }
}
nativeBuild {
    buildArgs('-H:ReflectionConfigurationFiles=/example/student/src/main/resources/reflection-config.json')
}
```

### **Stack traces:**
<img width="1322" alt="Screenshot 2024-02-29 at 4 05 42 PM" src="https://github.com/oracle/graal/assets/125887735/be80dfea-99c5-4907-95c7-be25f36815dd">

**Comment by solaanan** [comment]
Hello @anshu-zs, thank you for reporting this issue, can this issue be easily reproduced? Can you share the steps on how to do so. Thank you.

**Comment by anshu-zs** [comment]
Hi @solaanan, thank you for replying. I am using an in house framework and it's not feasible for us to share the code, but I'm trying to reproduce the same issue using simple java application. I'll get back to you as soon as possible.

For the time being here's the complete stacktrace

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.hibernate.validator.internal.engine.AbstractConfigurationImpl.<clinit>(AbstractConfigurationImpl.java:84)
	at java.base@21.0.2/java.lang.Class.ensureInitialized(DynamicHub.java:601)
	at org.hibernate.validator.HibernateValidator.createGenericConfiguration(HibernateValidator.java:33)
	at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:296)
	at com.zopsmart.rocket.util.ValidationWrapper.<clinit>(ValidationWrapper.java:10)
	at com.zopsmart.rocket.util.JsonParser.<init>(JsonParser.java:36)
	at com.zopsmart.rocket.logger.JsonFormatter.<clinit>(JsonFormatter.java:10)
	at com.zopsmart.rocket.logger.LoggerProvider.getLogger(LoggerProvider.java:29)
	at com.zopsmart.rocket.Rocket.<clinit>(Rocket.java:24)
	at com.zopsmart.Main.main(Main.java:9)
	at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.lang.IllegalArgumentException: Invalid logger interface org.hibernate.validator.internal.util.logging.Log (implementation not found in jdk.internal.loader.ClassLoaders$AppClassLoader@2f7c7260)
	at org.jboss.logging.Logger.doGetMessageLogger(Logger.java:2564)
	at org.jboss.logging.Logger.getMessageLogger(Logger.java:2530)
	at org.jboss.logging.Logger.getMessageLogger(Logger.java:2516)
	at org.hibernate.validator.internal.util.logging.LoggerFactory.make(LoggerFactory.java:22)
	at org.hibernate.validator.internal.util.Version.<clinit>(Version.java:20)
	... 11 more
	
```

and this is the dependency that is causing the issue:  **org.hibernate.validator.internal.util.logging.Log**

**Comment by anshu-zs** [comment]
Hi @solaanan the above issue has been fixed by putting the implementation of this class **(org.hibernate.validator.internal.util.logging.Log)**  in reflection-config.json file.

I am facing other issue now I am trying to create native image using this command
```
native-image --no-fallback indeed -H:ReflectionConfigurationFiles=reflection-config.json -H:IncludeResources=logback.xml -H:IncludeResources=version.properties -H:IncludeResources=.env -H:+ReportUnsupportedElementsAtRuntime   -H:Class=examples.http.Main  -jar rocket-examples-0.31.0.jar
```

but I am not able to see some classes as part of native-image when I run the below command
```
strings indeed | sudo grep UndertowHTTPServer
```

I tried to initialize those classes using --initialize-at-build-time and --initialize-at-run-time but still they are not getting initialized. Also the project is too large and has around 100 classes so how can I figure out this:

- which classes are initialized 
- which classes I need to initialize
- when to initiailize (at build time or run time)

Thanks!

**Comment by solaanan** [comment]
Hi @anshu-zs, I'm glad that the original issue is resolved. As for your current issue, GraalVM provides a Tracing Agent that gathers reachability metadata files, you can find out how to use it in here: [https://www.graalvm.org/latest/reference-manual/native-image/metadata/AutomaticMetadataCollection/](https://www.graalvm.org/latest/reference-manual/native-image/metadata/AutomaticMetadataCollection/)

**Comment by anshu-zs** [comment]
Hi @solaanan I tried adding all the classes via META-INF/native-image/ and I am able to run the native image
but I'm getting this error. Has this been resolved yet?

```
Exception in thread "main" io.github.classgraph.ClassGraphException: Uncaught exception during scan
        at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1637)
        at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1654)
        at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1667)
        at com.zopsmart.rocket.engine.scanner.ClassScanner.scanClasses(ClassScanner.java:42)
        at com.zopsmart.rocket.engine.DependencyEngine.build(DependencyEngine.java:714)
        at com.zopsmart.rocket.engine.EngineManager.buildDependencyStore(EngineManager.java:68)
        at com.zopsmart.rocket.context.ContextManager.initStores(ContextManager.java:67)
        at com.zopsmart.rocket.context.ContextManager.initPrimaryContexts(ContextManager.java:48)
        at com.zopsmart.rocket.context.ContextManager.<init>(ContextManager.java:37)
        at com.zopsmart.rocket.Rocket.initialize(Rocket.java:44)
        at com.zopsmart.rocket.Rocket.run(Rocket.java:99)
        at examples.http.Main.main(Main.java:10)
Caused by: java.lang.IllegalArgumentException: Method "list" could not be invoked
        at nonapi.io.github.classgraph.reflection.ReflectionUtils.invokeMethod(ReflectionUtils.java:230)
        at io.github.classgraph.ModuleReaderProxy.list(ModuleReaderProxy.java:111)
        at io.github.classgraph.ClasspathElementModule.scanPaths(ClasspathElementModule.java:318)
        at io.github.classgraph.Scanner$4.processWorkUnit(Scanner.java:1100)
        at io.github.classgraph.Scanner$4.processWorkUnit(Scanner.java:1094)
        at nonapi.io.github.classgraph.concurrency.WorkQueue.runWorkLoop(WorkQueue.java:246)
        at nonapi.io.github.classgraph.concurrency.WorkQueue.access$000(WorkQueue.java:50)
        at nonapi.io.github.classgraph.concurrency.WorkQueue$1.call(WorkQueue.java:201)
        at nonapi.io.github.classgraph.concurrency.WorkQueue$1.call(WorkQueue.java:198)
        at java.base@11.0.18/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base@11.0.18/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base@11.0.18/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base@11.0.18/java.lang.Thread.run(Thread.java:829)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base@11.0.18/java.lang.reflect.Method.invoke(Method.java:566)
        at nonapi.io.github.classgraph.reflection.StandardReflectionDriver.invokeMethod(StandardReflectionDriver.java:193)
        at nonapi.io.github.classgraph.reflection.ReflectionUtils.invokeMethod(ReflectionUtils.java:227)
        ... 14 more
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: JRT file system is disabled
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89)
        at java.base@11.0.18/jdk.internal.module.SystemModuleFinders$SystemImage.reader(SystemModuleFinders.java:139)
        at java.base@11.0.18/jdk.internal.module.SystemModuleFinders$ModuleContentSpliterator.<init>(SystemModuleFinders.java:508)
        at java.base@11.0.18/jdk.internal.module.SystemModuleFinders$SystemModuleReader.list(SystemModuleFinders.java:483)
        ... 17 more
```

Thanks

**Comment by solaanan** [comment]
Hi @anshu-zs, I see that this issue is being monitored here: https://github.com/oracle/graal/issues/8541
so I am going to be closing this one.
