### ISSUE TITLE
[GR-52473] Serialization of  arrays is not supported in Native Image

### ISSUE THREAD

**Issue by imgoby** [oracle/graal#8509]
**Describe the issue**
 in Native Image ReflectionFactory.getReflectionFactory().newConstructorForSerialization() does not support arrays type. for example float[] ,int[], Integer[]

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. install jdk:

sdk install java 17.0.10-graal
sdk use java 17.0.10-graal
sdk default java 17.0.10-graal

2. code : HelloWorld.java

```
import sun.reflect.ReflectionFactory;
import java.io.ObjectStreamClass;
import java.io.Serializable;
import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Method;

public class HelloWorld {
     public static void main(String[] args) throws Exception{

        Class clazz= float[].class;
        Constructor c = java.lang.Object.class.getDeclaredConstructor((Class[]) null);
        c = ReflectionFactory.getReflectionFactory().newConstructorForSerialization(clazz, c);
         System.out.println("Hello, Native World!");
     }
 }
```

3. serialization-config.json is follow:
```
{
  "types": [
      {
        "name": "[F"
      },

    {
      "name": "java.lang.Number"
    },
    {
      "name": "java.text.Format"
    },
    {
      "name": "java.text.DateFormat"
    },
    {
      "name": "java.util.Calendar"
    },
    {
      "name": "java.util.TimeZone"
    },


    {
      "name": "java.lang.String"
    },
    {
      "name": "java.lang.Byte"
    },
    {
      "name": "java.lang.Short"
    },
    {
      "name": "java.lang.Integer"
    },
    {
      "name": "java.lang.Long"
    },
    {
      "name": "java.lang.Float"
    },
    {
      "name": "java.lang.Double"
    },
    {
      "name": "java.math.BigDecimal"
    },
    {
      "name": "java.math.BigInteger"
    },
    {
      "name": "java.lang.Character"
    },
    {
      "name": "java.lang.Boolean"
    },
    {
      "name": "java.util.TreeMap"
    },
    {
      "name": "java.util.HashMap"
    },
    {
      "name": "java.util.ArrayList"
    },
    {
      "name": "java.util.concurrent.ConcurrentHashMap"
    },
    {
      "name": "java.net.URL"
    },
    {
      "name": "java.util.Date"
    },
    {
      "name": "java.sql.Date"
    },
    {
      "name": "java.text.SimpleDateFormat"
    },
    {
      "name": "java.util.TreeSet"
    },
    {
      "name": "java.util.LinkedList"
    },
    {
      "name": "java.util.SimpleTimeZone"
    },
    {
      "name": "java.util.GregorianCalendar"
    },
    {
      "name": "java.util.Vector"
    },
    {
      "name": "java.util.Hashtable"
    },
    {
      "name": "java.util.BitSet"
    },
    {
      "name": "java.sql.Timestamp"
    },
    {
      "name": "java.util.Locale"
    },
    {
      "name": "java.lang.StringBuffer"
    },
    {
      "name": "java.lang.StringBuilder"
    },
    {
      "name": "java.lang.Object[]"
    },
    {
      "name": "java.lang.Object[][]"
    },
    {
      "name": "java.lang.Object[][][]"
    },
    {
      "name": "byte[]"
    },
    {
      "name": "byte[][]"
    },
    {
      "name": "char[]"
    },
    {
      "name": "char[][]"
    },
    {
      "name": "java.lang.String[]"
    },
    {
      "name": "java.lang.String[][]"
    },
    {
      "name": "int[]"
    },
    {
      "name": "int[][]"
    },
    {
      "name": "float[]"
    },
    {
      "name": "float[][]"
    },
    {
      "name": "double[]"
    },
    {
      "name": "double[][]"
    },
    {
      "name": "long[]"
    },
    {
      "name": "long[][]"
    }
  ],
  "lambdaCapturingTypes": [],
  "proxies": []
}
```

4.  
```
javac HelloWorld.java
native-image HelloWorld --no-fallback  -H:SerializationConfigurationFiles=serialization-config.json
```

5.Exception is as as follow:
```
[root@localhost example]# ./helloworld 
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: SerializationConstructorAccessor class not found for declaringClass: [F (targetConstructorClass: java.lang.Object). Usually adding [F to serialization-config.json fixes the problem.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:92)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.reflect.serialize.SerializationSupport.getSerializationConstructorAccessor(SerializationSupport.java:143)
	at java.base@17.0.10/jdk.internal.reflect.MethodAccessorGenerator.generateSerializationConstructor(MethodAccessorGenerator.java:61)
	at java.base@17.0.10/jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:463)
	at java.base@17.0.10/jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:376)
	at jdk.unsupported@17.0.10/sun.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:100)
	at HelloWorld.main(HelloWorld.java:13)
```

**Describe GraalVM and your environment:**
 - GraalVM 17.0.10+11.1
 - JDK major version: 17.0.10 2024-01-16 LTS
 - OS: Centos 7.9
 - Architecture: x64

**Comment by aelmassa** [comment]
Hi

Thank you for reporting this issue. We will be looking into it.

By the way, this warning may be worth addressing   
```java
HelloWorld.java:1: warning: ReflectionFactory is internal proprietary API and may be removed in a future release
import sun.reflect.ReflectionFactory;
                  ^
HelloWorld.java:9: warning: ReflectionFactory is internal proprietary API and may be removed in a future release
        c = ReflectionFactory.getReflectionFactory().newConstructorForSerialization(clazz, c);
            ^
2 warnings
```

**Comment by imgoby** [comment]
Thank you.
I hope this issue can be resolved as quickly as possible. 
the warning doesn't affect currently.there is the same warning in JDK 21 .

**Comment by imgoby** [comment]
Is this graal's problem. What caused it? When can it be resolved?

**Comment by imgoby** [comment]
@vjovanov Hello, Is there any plan to fix it?I am waiting for it.

**Comment by vjovanov** [comment]
The fix is ready and will be out with GraalVM for JDK 23 in September. Thanks for reporting @imgoby!

**Comment by imgoby** [comment]
> The fix is ready and will be out with GraalVM for JDK 23 in September. Thanks for reporting @imgoby!

Has it been published?
Can JDK17 be supported?

**Comment by imgoby** [comment]
I use Java 23.ea.24-gray version and the issue has been resolved. But version 22 and below are not supported.
Will Java 17 solve it in the future? Maybe I should upgrade to Java 23 or 24

**Comment by vjovanov** [comment]
This is not officially released in GraalVM for JDK 23. It will likely not be backported to earlier JDKs.

**Comment by imgoby** [comment]
I wrote it wrong, it should be 23.ea.24-graal, this is official.
Okay, I'll start switching to JDK 23.
Thank you.
