### ISSUE TITLE
Class.forName can return a ghost type

### ISSUE THREAD

**Issue by stuartwdouglas** [oracle/graal#851]
With the changes in RC10 it is now possible that Class.forName will return a ghost class. It looks like there is code in NativeImageClassLoader that is supposed to stop this, however it appears that if the ghost class has already been created via bytecode parsing then it will be returned (as the order of class loading is not guaranteed this means the problem will not always appear). 

This will cause problems with any library that allows optional features. I saw this problem with Hibernate validator, which is attempting to check for the existence of a Java FX class to see if it should enable Java FX validation. This then causes problems as these classes are linked against ghost classes with the wrong signature resulting in a MalformedParameterizedTypeException.

**Comment by Sanne** [comment]
To add some more detail:

### stacktrace

```
Caused by: java.lang.reflect.MalformedParameterizedTypeException
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.validateConstructorArguments(ParameterizedTypeImpl.java:58)
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.<init>(ParameterizedTypeImpl.java:51)
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.make(ParameterizedTypeImpl.java:92)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeParameterizedType(CoreReflectionFactory.java:105)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:140)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.repository.ClassRepository.getSuperInterfaces(ClassRepository.java:108)
	at java.lang.Class.getGenericInterfaces(Class.java:913)
	at sun.reflect.annotation.TypeAnnotationParser.buildAnnotatedInterfaces(TypeAnnotationParser.java:190)
	at java.lang.Class.getAnnotatedInterfaces(Class.java:3636)
	at org.hibernate.validator.internal.engine.valueextraction.ValueExtractorDescriptor.determineValueExtractorDefinitions(ValueExtractorDescriptor.java:150)
	at org.hibernate.validator.internal.engine.valueextraction.ValueExtractorDescriptor.getValueExtractorDefinition(ValueExtractorDescriptor.java:123)
	at org.hibernate.validator.internal.engine.valueextraction.ValueExtractorDescriptor.<init>(ValueExtractorDescriptor.java:45)
	at org.hibernate.validator.internal.engine.valueextraction.ObservableValueValueExtractor.<clinit>(ObservableValueValueExtractor.java:27)
```

This exception happens only during the `native-image` run. It's not otherwise reproducible.

**Comment by cstancu** [comment]
Thank you for the report, we are aware of this problem and working on a solution.

**Comment by Sanne** [comment]
Happy to report that indeed it resolved the problems we had

Thanks @cstancu !
