### ISSUE TITLE
javax.xml.transform.TransformerFactory.newTemplates(Source) NullPointerException in Native Image

### ISSUE THREAD

**Issue by PeteSL** [oracle/graal#8546]
I have an application that uses an XSLT file to present XML data to a browser. I added Objects.requireNonNull() to validate that the resource was actually there and being parsed (used -H:IncludeResources and log shows it was added as well):
`xslt = transformerFactory.newTemplates(new StreamSource(Objects.requireNonNull(StatusListenerPort.class.getResourceAsStream("detail.xsl"), "Package detail.xml not found")));
`
This produces the following (same exception if using java.nio.file.Files.newInputStream and an external file):
`Caused by: javax.xml.transform.TransformerConfigurationException: java.lang.NullPointerException
	... 10 more
Caused by: java.lang.NullPointerException
	at java.xml@21.0.2/com.sun.org.apache.xalan.internal.xsltc.compiler.util.ErrorMsg.getFileName(ErrorMsg.java:264)
	at java.xml@21.0.2/com.sun.org.apache.xalan.internal.xsltc.compiler.util.ErrorMsg.<init>(ErrorMsg.java:237)
	at java.xml@21.0.2/com.sun.org.apache.xalan.internal.xsltc.compiler.Parser.makeInstance(Parser.java:1000)
	at java.xml@21.0.2/com.sun.org.apache.xalan.internal.xsltc.compiler.Parser.startElement(Parser.java:1312)
	at java.xml@21.0.2/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:518)
	at java.xml@21.0.2/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:376)
	at java.xml@21.0.2/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:615)
	at java.xml@21.0.2/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3079)
	at java.xml@21.0.2/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:836)
	at java.xml@21.0.2/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml@21.0.2/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:114)
	at java.xml@21.0.2/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
	at java.xml@21.0.2/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
	at java.xml@21.0.2/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
	at java.xml@21.0.2/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml@21.0.2/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml@21.0.2/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
	at java.xml@21.0.2/com.sun.org.apache.xalan.internal.xsltc.compiler.Parser.parse(Parser.java:439)
	at java.xml@21.0.2/com.sun.org.apache.xalan.internal.xsltc.compiler.Parser.parse(Parser.java:524)
	at java.xml@21.0.2/com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:478)
	at java.xml@21.0.2/com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:575)
	at java.xml@21.0.2/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:1036)
	... 9 more
`  The XSLTs work fine with JVMs. The XSLT does reference java.util.Date per the XSLT 1.0 spec:
`<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xalan="http://xml.apache.org/xslt" xmlns:Date="xalan://java.util.Date" exclude-result-prefixes="xalan Date">
	<xsl:output method="html"/>
	<xsl:template name="javaUTCDateTime">
		<xsl:param name="longdate"/>
		<xsl:variable name="jDate" select="Date:new()"/>
		<xsl:value-of select="Date:setTime($jDate, number($longdate))"/>
		<xsl:value-of select="Date:toGMTString($jDate)"/>
	</xsl:template>
	<xsl:template name="javaYear">
		<xsl:param name="longdate"/>
		<xsl:variable name="jDate" select="Date:new()"/>
		<xsl:value-of select="Date:setTime($jDate, number($longdate))"/>
		<xsl:value-of select="Date:getYear($jDate) + 1900"/>
	</xsl:template>
	<xsl:template name="DurationDisplay">
		<xsl:param name="longdate"/>
		<xsl:variable name="seconds" select="(number($longdate) mod 60000) div 1000.0"/>
		<xsl:variable name="minutes" select="floor((number($longdate) div 60000) mod 60)"/>
		<xsl:variable name="hours" select="floor((number($longdate) div 3600000) mod 24)"/>
		<xsl:variable name="days" select="floor(number($longdate) div 86400000)"/>
		<xsl:value-of select="concat(format-number($days, '#0'), 'd', format-number($hours, '#0'), 'h', format-number($minutes, '#0'), 'm', $seconds, 's')"/>
	</xsl:template>
`
Possible issue with xalan trying to reference the Date class which works in Java but maybe not in a native image?  Everything else in the XSLT is standard HTML/XSLT stuff.

**Comment by hamzaGhaissi** [comment]
Hi can you please share a small reproducer of this issue with your OS and graalvm version ?

**Comment by PeteSL** [comment]
Linux x86_64 (Debian) graalvm JDK 21.0.2+13.1
The error, according to the JDK 8 source from OpenJDK, is occurring at line 1000 of the Parser:
`                // Check if this is an XSLTC extension element
                else if (uri.equals(TRANSLET_URI)) {
                    node = new UnsupportedElement(uri, prefix, local, true);
                    UnsupportedElement element = (UnsupportedElement)node;
                    ErrorMsg msg = new ErrorMsg(ErrorMsg.UNSUPPORTED_EXT_ERR,
                                                getLineNumber(),local);
                    element.setErrorMessage(msg);
                }`
which is the line creating ErrorMsg which should call ErrorMsg(String, int, String).  However, that does not match up with the OpenJDK source on GitHub which Parser.java line 1000 doesn't match with any ErrorMsg creation at all and the init area in ErrorMsg is for ErrorMsg(String code, SyntaxTreeNode node) which is not ErrorMsg(String, int, String) nor would the (String, int, String) version cause a NullPointerException. I will test a simplified XSLT with only the above templates and a template creating the <html></html> basic tags needed to see if it still causes the exception.  If it does, I will post it here in a comment.

**Comment by PeteSL** [comment]
Here is a full XSLT that causes the error:
`<?xml version="1.0"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xalan="http://xml.apache.org/xslt" xmlns:Date="xalan://java.util.Date" exclude-result-prefixes="xalan Date">
	<xsl:output method="html"/>
	<xsl:template name="javaUTCDateTime">
		<xsl:param name="longdate"/>
		<xsl:variable name="jDate" select="Date:new()"/>
		<xsl:value-of select="Date:setTime($jDate, number($longdate))"/>
		<xsl:value-of select="Date:toGMTString($jDate)"/>
	</xsl:template>
	<xsl:template name="javaYear">
		<xsl:param name="longdate"/>
		<xsl:variable name="jDate" select="Date:new()"/>
		<xsl:value-of select="Date:setTime($jDate, number($longdate))"/>
		<xsl:value-of select="Date:getYear($jDate) + 1900"/>
	</xsl:template>
	<xsl:template name="DurationDisplay">
		<xsl:param name="longdate"/>
		<xsl:variable name="seconds" select="(number($longdate) mod 60000) div 1000.0"/>
		<xsl:variable name="minutes" select="floor((number($longdate) div 60000) mod 60)"/>
		<xsl:variable name="hours" select="floor((number($longdate) div 3600000) mod 24)"/>
		<xsl:variable name="days" select="floor(number($longdate) div 86400000)"/>
		<xsl:value-of select="concat(format-number($days, '#0'), 'd', format-number($hours, '#0'), 'h', format-number($minutes, '#0'), 'm', $seconds, 's')"/>
	</xsl:template>
	<xsl:template match="/">
		<html>
			<head>
				<title>Status Page</title>
				<meta content="noindex,nofollow" name="robots"/>
			</head>
			<body bgColor="#606060">
				<center>
				</center>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>`
I am bothered that the Parser line number does not match the OpenJDK line number but does match the ErrorMsg(String, SyntaxTreeNode) line number.  The Parser line number does match the Java 8 code but then the ErrorMsg(String, int, String) is called, not the ErrorMsg(String, SyntaxTreeNode) constructor.

**Comment by hamzaGhaissi** [comment]
Can also share the source code of the app you are running or reproducer ?

**Comment by PeteSL** [comment]
The reproducer line is:
xslt = transformerFactory.newTemplates(new StreamSource(Objects.requireNonNull(StatusListenerPort.class.getResourceAsStream("detail.xsl"), "Package detail.xml not found"))); 

but you can use any stream (Files.newInputStream, for instance) to feed the StreamSource with the xslt that I showed previously.  Understand, this is not doing a transform, only creating the Template for transforming and it works with any JVM including the GraalVM JVM.  It does not work within a native image.

**Comment by PeteSL** [comment]
More information:
The reason the failure is in newTemplates() is because I am calling that procedure twice (doesn't make sense it would throw an exception but...).  If the newTemplates() is called once with an extension (tried with the xalan java extension and the EXSLT extension), the extensions are not included in the native-image binary. If you try loading another stylesheet with the extension, then you get the exception where it should not be anyway (should be giving an exception stating "unknown exception at line number").  It seems there may be a mismatch of what is included in the native-image vs. what is in a regular JVM (no extensions vs. xalan and EXSLT extensions) and the xalan compiled packages may have mismatched error reporting (never should be getting to getFileName() in ErrMsg.

**Comment by hamzaGhaissi** [comment]
Is this the same stack trace your having 
```
Exception in thread "main" javax.xml.transform.TransformerConfigurationException: java.net.MalformedURLException
        at java.xml@21.0.2/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:1077)
        at com.sample.HelloSampleApplication.main(HelloSampleApplication.java:23)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.net.MalformedURLException
        at java.base@21.0.2/java.net.URL.<init>(URL.java:806)
        at java.base@21.0.2/java.net.URL.<init>(URL.java:654)
        at java.base@21.0.2/java.net.URL.<init>(URL.java:590)
        at java.xml@21.0.2/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:651)
        at java.xml@21.0.2/com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:150)
        at java.xml@21.0.2/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:861)
        at java.xml@21.0.2/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
        at java.xml@21.0.2/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml@21.0.2/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
        at java.xml@21.0.2/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
        at java.xml@21.0.2/com.sun.org.apache.xalan.internal.xsltc.compiler.Parser.parse(Parser.java:439)
        at java.xml@21.0.2/com.sun.org.apache.xalan.internal.xsltc.compiler.Parser.parse(Parser.java:524)
        at java.xml@21.0.2/com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:478)
        at java.xml@21.0.2/com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:575)
        at java.xml@21.0.2/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:1036)
        ... 2 more
Caused by: java.lang.NullPointerException
        at java.base@21.0.2/java.net.URL.<init>(URL.java:712)
        ... 16 more
---------
java.net.MalformedURLException
        at java.base@21.0.2/java.net.URL.<init>(URL.java:806)
        at java.base@21.0.2/java.net.URL.<init>(URL.java:654)
        at java.base@21.0.2/java.net.URL.<init>(URL.java:590)
        at java.xml@21.0.2/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:651)
        at java.xml@21.0.2/com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:150)
        at java.xml@21.0.2/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:861)
        at java.xml@21.0.2/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
        at java.xml@21.0.2/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml@21.0.2/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
        at java.xml@21.0.2/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
        at java.xml@21.0.2/com.sun.org.apache.xalan.internal.xsltc.compiler.Parser.parse(Parser.java:439)
        at java.xml@21.0.2/com.sun.org.apache.xalan.internal.xsltc.compiler.Parser.parse(Parser.java:524)
        at java.xml@21.0.2/com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:478)
        at java.xml@21.0.2/com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:575)
        at java.xml@21.0.2/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:1036)
        at com.sample.HelloSampleApplication.main(HelloSampleApplication.java:23)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.lang.NullPointerException
        at java.base@21.0.2/java.net.URL.<init>(URL.java:712)
        ... 16 more
```

using the following
```
TransformerFactory transformerFactory = TransformerFactory.newInstance();
InputStream xsltStream = HelloSampleApplication.class.getClassLoader().getResourceAsStream("transform.xslt");
Source xslt = new StreamSource(xsltStream);

// Create a Transformer object from the XSLT source
Templates transformer = transformerFactory.newTemplates(xslt);
```

**Comment by PeteSL** [comment]
No, I posted the exception when I opened the issue.  In -theory-, a single call to newTemplates() should not cause an exception as it is (reading the comments in the Xalan code) assumed that an unknown extension might be resolved at parsing time.  However, what I was seeing is those unknown extensions (which are known in Java) causing an exception with the wrong call to ErrMsg (never should see getFileName() in the stack as an unknown extension causes a transformation exception that shows the parsed name of the extension and the line number in the XSLT.  So it is a bug for newTempates() to cause an exception when it doesn't in Java.

**Comment by hamzaGhaissi** [comment]
I was not able get the same exception as you, please create a reproducer, upload it to github, then share it with me

**Comment by PeteSL** [comment]
`import org.w3c.dom.*;
import javax.xml.parsers.*;
import javax.xml.transform.*;
import javax.xml.transform.dom.*;
import javax.xml.transform.stream.*;
import java.nio.file.*;
import java.util.*;

public class sampl
{
	private static final TransformerFactory transformerFactory = TransformerFactory.newInstance();

	public static void main(String[] args)
	{
		try
		{
			Templates xslt = transformerFactory.newTemplates(new StreamSource(Objects.requireNonNull(Files.newInputStream(Paths.get("gensimpl.xsl")), "gensimpl.xsl not found")));
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
}`
Use this with XSLT code I put previously in a file called gensimpl.xsl and it will run in Java and cause an exception with native-image.

**Comment by hamzaGhaissi** [comment]
Thank you we are tracking this

**Comment by vjovanov** [comment]
This looks like missing metadata. To make sure that the reflection for your image is configured correctly please add `-H:ThrowMissingRegistrationErrors=` to the native-image build arguments. If the resulting image fails in libraries that are not under your control, you can always use a package prefix to prevent that: `-H:ThrowMissingRegistrationErrors=<package-prefix>`.

If the application accidentally swallows the failure, one can add the following flag to the image build: `-H:MissingRegistrationReportingMode=<Warn|Exit>`. When set to `-H:MissingRegistrationReportingMode=Warn` the application will only print missing reflection, and with `-H:MissingRegistrationReportingMode=Exit` the application will exit immediately without throwing an exception.

**Comment by PeteSL** [comment]
> STDERR: com.oracle.svm.core.jdk.resources.MissingResourceRegistrationError: The program tried to access the resource at path META-INF/services/javax.xml.parsers.DocumentBuilderFactory without it being registered as reachable. Add it to the resource metadata to solve this problem.

As you suspected, this is an issue with what native-build is including with the javax.xml packages.  It is -not- an issue with my code as I have already made sure to include all the resources my code directly uses.

**Comment by vjovanov** [comment]
Note that XML from the JDK will not work in most cases even with resources configured as it will try to generate bytecodes at build time. We are working on fixing that. 

Until XML in the JDK is fixed the only way to make XML work is to use the interpreter for XML from `xalan`.

**Comment by PeteSL** [comment]
I don't know if it is a concern or not because it appears logging and java.nio.file.Files.probeContentType() are working but they also flagged on accessing their services files which tells me there is an issue with native-image including JDK services files.  I know this is a reported issue with applications and module loading but it is working with classpath loading in the application.  I am using classpath, not module-path to build this image because of the ServiceLoader issue with module-path reported in [https://github.com/oracle/graal/issues/7634]#7634.
