### ISSUE TITLE
MacOS native-image: No awt in java.library.path

### ISSUE THREAD

**Issue by ruwi-next** [oracle/graal#8602]
**Describe the issue**
When building a native-image that uses `System.loadLibrary("awt")` on macos. native-image does not output any dylibs, only the executable binary.

```
Produced artifacts:
/graal_shared_libs/Foo (executable)
```

When running the binary it throws an exception UnsatisifiedLinkError 
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: No awt in java.library.path
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryRelative(NativeLibrarySupport.java:136)
        at java.base@21.0.2/java.lang.ClassLoader.loadLibrary(ClassLoader.java:106)
        at java.base@21.0.2/java.lang.Runtime.loadLibrary0(Runtime.java:916)
        at java.base@21.0.2/java.lang.System.loadLibrary(System.java:2063)
        at Foo.main(Foo.java:8)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```

I have tried changing `java.library.path` to point at the dylib directory but to no avail.

I have also tested the same code on windows and it works there (correctly produces the dlls and no link exception).

**Steps to reproduce the issue**
I have created a reproducible repo that demonstrates the issue
1. Clone https://github.com/ruwi-next/graal-shared-libs
2. Run `make run_native`

**Describe GraalVM and your environment:**
 - native-image 21.0.2 2024-01-16
 - GraalVM Runtime Environment Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30)
 - Substrate VM Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS, serial gc, compressed references)
 - OS: macos Sonoma 14.2.1
 - Architecture: ARM64

Any help is much appreciated.

**Comment by fernando-valdez** [comment]
Hi @ruwi-next thanks for reporting this issue. But unfortunately, this is a known issue. 
You can track the efforts on solving the problem here: https://github.com/oracle/graal/issues/4921 
Additionally, you can read a little about this issue in the comments of the open ticket: https://github.com/oracle/graal/issues/4124

I will close this issue as it is duplicated
