### ISSUE TITLE
Clojure locking issue

### ISSUE THREAD

**Issue by eraserhd** [oracle/graal#861]
This program fails to build in a native image:

```clojure
(ns rep.core
  (:gen-class))

(defn- foo [s]
  (locking s
    42))

(defn -main
  [& args]
  (foo))
```

This is the latest Clojure, patched with clj-1472-3.patch found here:  
https://dev.clojure.org/jira/browse/CLJ-1472
^^ that patch resolves structured locking issues, and I can then use `locking` (cf Java's `synchronized`), but I can't use it on a function argument.

Since the patch literally just passes a closure to a Java method with synchronized() in it, it seems likely this is related to Graal.

Error:
```
fatal error: com.oracle.svm.core.util.VMError$HostedError: Objects with relocatable pointers must be immutable              
        at com.oracle.svm.core.util.VMError.guarantee(VMError.java:85)                                                      
        at com.oracle.svm.hosted.image.NativeImageHeap.choosePartition(NativeImageHeap.java:492)                            
        at com.oracle.svm.hosted.image.NativeImageHeap.addObjectToBootImageHeap(NativeImageHeap.java:451)                   
        at com.oracle.svm.hosted.image.NativeImageHeap.addObject(NativeImageHeap.java:271)                                  
        at com.oracle.svm.hosted.image.NativeImageCodeCache.addConstantToHeap(NativeImageCodeCache.java:369)                
        at com.oracle.svm.hosted.image.NativeImageCodeCache.addConstantsToHeap(NativeImageCodeCache.java:356)               
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:882)                                  
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:401)                           
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)                             
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)                                                  
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)                                      
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)                                              
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by eraserhd** [comment]
I've encountered another instance of this error which I haven't fully isolated yet in some calls to `clojure.pprint/cl-format`.   I'm not sure locking is involved here.  I'll add a small repro in the next couple days.

**Comment by nikbucher** [comment]
Exactly same stacktrace in Kotlin, when I'm using coroutines.

**Comment by eraserhd** [comment]
Also, `(ns foo (:gen-class)) (defn main [& _] (read-string))` is sufficient in Clojure.  This is just a wrapper for the Java static method clojure.lang.RT/readString, and calling that directly also causes it.

**Comment by peter-hofer** [comment]
This should be fixed in RC11.

**Comment by eraserhd** [comment]
Confirmed that this works with RC11. (Though it seems to have increased memory usage quite a bit when it hits these cases - CircleCI is unhapppy.)
