### ISSUE TITLE
[GR-52997] Native image run failure with modelmapper propertymap

### ISSUE THREAD

**Issue by blackhawkee** [oracle/graal#8652]
**Describe the issue**
Native image run fails with the below error even though reachability metadata is generated.

**Steps to reproduce the issue**
A sample here https://github.com/blackhawkee/native-mapper

**Describe GraalVM and your environment:**
 - GraalVM version -  GraalVM 22+36.1
 - JDK major version: 22
 - OS:Ubuntu
 - Architecture: AMD64

**More details**
Build args are available in src/main/resources/META-INF/native-image/native-image.properties

Reachability metadata is generated but still one of the classfile(TestRequestToTestResponseMap) is not available at image run, causing the below failure - 
```
Caused by: org.modelmapper.ConfigurationException: ModelMapper configuration errors:

1) Failed to configure mappings

1 error
        at org.modelmapper.internal.Errors.throwConfigurationExceptionIfErrorsExist(Errors.java:240) ~[native-mapper:na]
        at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:252) ~[native-mapper:na]
        at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:104) ~[native-mapper:na]
        at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:92) ~[na:na]
        at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:127) ~[na:na]
        at org.modelmapper.ModelMapper.addMappings(ModelMapper.java:113) ~[native-mapper:na]
        at com.mapper.nativemapper.config.ModelMapperConfig.modelMapper(ModelMapperConfig.java:24) ~[native-mapper:na]
        at com.mapper.nativemapper.config.ModelMapperConfig$$SpringCGLIB$$0.CGLIB$modelMapper$0(<generated>) ~[native-mapper:na]
        at com.mapper.nativemapper.config.ModelMapperConfig$$SpringCGLIB$$FastClass$$1.invoke(<generated>) ~[native-mapper:na]
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258) ~[native-mapper:6.1.5]
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[na:na]
        at com.mapper.nativemapper.config.ModelMapperConfig$$SpringCGLIB$$0.modelMapper(<generated>) ~[native-mapper:na]
        at com.mapper.nativemapper.config.ModelMapperConfig__BeanDefinitions.lambda$getModelMapperInstanceSupplier$0(ModelMapperConfig__BeanDefinitions.java:34) ~[na:na]
        at org.springframework.util.function.ThrowingFunction.apply(ThrowingFunction.java:63) ~[native-mapper:6.1.5]
        at org.springframework.util.function.ThrowingFunction.apply(ThrowingFunction.java:51) ~[native-mapper:6.1.5]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.lambda$withGenerator$0(BeanInstanceSupplier.java:171) ~[na:na]
        at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:68) ~[native-mapper:6.1.5]
        at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:54) ~[native-mapper:6.1.5]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.lambda$get$2(BeanInstanceSupplier.java:206) ~[na:na]
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:58) ~[native-mapper:6.1.5]
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:46) ~[native-mapper:6.1.5]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.invokeBeanSupplier(BeanInstanceSupplier.java:218) ~[na:na]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:206) ~[na:na]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.obtainInstanceFromSupplier(DefaultListableBeanFactory.java:949) ~[native-mapper:6.1.5]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1217) ~[native-mapper:6.1.5]
        ... 52 common frames omitted
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: No classes have been predefined during the image build to load from bytecodes at runtime.
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:121) ~[na:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.PredefinedClassesSupport.throwNoBytecodeClasses(PredefinedClassesSupport.java:76) ~[na:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.PredefinedClassesSupport.loadClass(PredefinedClassesSupport.java:130) ~[na:na]
        at java.base@22/java.lang.ClassLoader.defineClass(ClassLoader.java:280) ~[native-mapper:na]
        at org.modelmapper.internal.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader.invoker(JavaDispatcher.java:1383) ~[na:na]
        at org.modelmapper.internal.bytebuddy.utility.dispatcher.JavaDispatcher$InvokerCreationAction.run(JavaDispatcher.java:459) ~[na:na]
        at org.modelmapper.internal.bytebuddy.utility.dispatcher.JavaDispatcher$InvokerCreationAction.run(JavaDispatcher.java:452) ~[na:na]
        at java.base@22/java.security.AccessController.executePrivileged(AccessController.java:128) ~[native-mapper:na]
        at java.base@22/java.security.AccessController.doPrivileged(AccessController.java:319) ~[native-mapper:na]
        at org.modelmapper.internal.bytebuddy.utility.dispatcher.JavaDispatcher.doPrivileged(JavaDispatcher.java) ~[na:na]
        at org.modelmapper.internal.bytebuddy.utility.dispatcher.JavaDispatcher.<clinit>(JavaDispatcher.java:87) ~[na:na]
        at org.modelmapper.internal.bytebuddy.description.type.TypeDescription$ForLoadedType.<clinit>(TypeDescription.java:8659) ~[na:na]
        at org.modelmapper.internal.bytebuddy.matcher.ElementMatchers.isFinalizer(ElementMatchers.java:1624) ~[na:na]
        at org.modelmapper.internal.bytebuddy.matcher.ElementMatchers.isDefaultFinalizer(ElementMatchers.java:1614) ~[na:na]
        at org.modelmapper.internal.bytebuddy.ByteBuddy.<init>(ByteBuddy.java:311) ~[na:na]
        at org.modelmapper.internal.bytebuddy.ByteBuddy.<init>(ByteBuddy.java:285) ~[na:na]
        at org.modelmapper.internal.ProxyFactory.<clinit>(ProxyFactory.java:46) ~[na:na]
        at org.modelmapper.internal.ExplicitMappingBuilder.createProxy(ExplicitMappingBuilder.java:330) ~[native-mapper:na]
        at org.modelmapper.internal.ExplicitMappingBuilder.createProxies(ExplicitMappingBuilder.java:281) ~[native-mapper:na]
        at org.modelmapper.internal.ExplicitMappingBuilder.visitPropertyMap(ExplicitMappingBuilder.java:274) ~[native-mapper:na]
        at org.modelmapper.PropertyMap.configure(PropertyMap.java:386) ~[native-mapper:na]
        at java.base@22/java.lang.reflect.Method.invoke(Method.java:580) ~[native-mapper:na]
        at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:235) ~[native-mapper:na]
        ... 75 common frames omitted
```

**Comment by blackhawkee** [comment]
@oubidar-Abderrahim  - any leads on this please. on further check, the issue exists in previous versions as well.
Alternatively have tried with --experimental-class-define-support and the issue still recurs. Thanks in advance.

**Comment by syedyusufh** [comment]
@blackhawkee did you solve this issue? Running into the same problem with the latest version of ModelMapper.

**Comment by vjovanov** [comment]
This is the new error message in GraalVM:
```
To make this work, you have the following options:
                      1) Modify or reconfigure your application (or a third-party library) so that it does not generate classes at runtime or load them via non-built-in class loaders.
                      2) If the classes must be generated, try to generate them at build time in a static initializer of a dedicated class.
                     The generated java.lang.Class objects should be stored in static fields and the dedicated class initialized by passing '--initialize-at-build-time=<class_name>' as the build argument.
                      3) If none of the above is applicable, use the tracing agent to run this application and collect predefined classes with
                     'java -agentlib:native-image-agent=config-output-dir=<config-dir>,experimental-class-define-support <application-arguments>'.
                     Note that this is an experimental feature and that it does not guarantee success. Furthermore, the resulting classes can contain entries
                     from the classpath that should be manually filtered out to reduce image size. The agent should be used only in cases where modifying the source of the project is not possible.
```
Have you tried the steps above?

**Comment by syedyusufh** [comment]
Hi @vjovanov , sorry the late response

1 & 2 are not possible

3, Tried by generating the metadata, captured it, built and tried starting the application. However,  still it failed with some reference to ModelMapper's dynamic class loading via bytebuddy

don't have GH access from the environment where this error is thrown :(

**Comment by vjovanov** [comment]
I would suspect that the issue arises due to unstable bytecodes for the generated class. This is one of the downsides of the agent approach.  

To see if the bytecodes are stable I would advise to run the agent several times and see if the hash code in `predefined-classes-config.json`. I can improve the error message to include the hash that was detected during run-time.

**Comment by vjovanov** [comment]
Why can't we initialize `org.modelmapper.internal.ProxyFactory` at build time?

**Comment by syedyusufh** [comment]
@vjovanov option 2 did not help as well, please check the minimal reproducer available at https://github.com/syedyusufh/modelmapper-issue.git

**Comment by vjovanov** [comment]
Works for me but fails with another error. Then I add the following to fix all the missing registration errors:
```
<buildArg>--initialize-at-build-time=org.modelmapper.internal.ExplicitMappingBuilder</buildArg>
<buildArg>-H:ThrowMissingRegistrationErrors=</buildArg>
```
and invoke with 

`modelmapper-issue -XX:MissingRegistrationReportingMode=Warn`

Now it fails as it tries to access classes from JARs at run time. I would check with SpringBoot on how to fix this issue. I suspect that all class access must be done at build time.

**Comment by syedyusufh** [comment]
@vjovanov any luck with the reported issue, please?

**Comment by vjovanov** [comment]
This can not be fixed on Native Image side as the library does things currently unsupported by native image. The only way is to fix or up-vote the issue you posted.
