### ISSUE TITLE
Cannot run program "/usr/local/musl/bin/x86_64-linux-musl-gcc"

### ISSUE THREAD

**Issue by SimoneGiusso** [oracle/graal#8667]
**Describe the issue**
I'm trying to create a fully static native image but I'm getting the following error:

```
Error: Unable to compile C-ABI query code /tmp/SVM-875408230020192212/JNIHeaderDirectives.c. Make sure native software development toolchain is installed on your system.
com.oracle.svm.core.util.UserError$UserException: Unable to compile C-ABI query code /tmp/SVM-875408230020192212/JNIHeaderDirectives.c. Make sure native software development toolchain is installed on your system.
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:85)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.codegen.CCompilerInvoker.compileAndParseError(CCompilerInvoker.java:495)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.CAnnotationProcessor.compileQueryCode(CAnnotationProcessor.java:168)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.CAnnotationProcessor.process(CAnnotationProcessor.java:112)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.NativeLibraries.finish(NativeLibraries.java:559)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1712)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1171)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:934)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:579)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:539)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:408)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:612)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:134)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)
Caused by: java.io.IOException: Cannot run program "/usr/local/musl/bin/x86_64-linux-musl-gcc" (in directory "/tmp/SVM-875408230020192212"): error=0, Failed to exec spawn helper: pid: 65, exit value: 1
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.codegen.CCompilerInvoker.compileAndParseError(CCompilerInvoker.java:469)
        ... 12 more
Caused by: java.io.IOException: error=0, Failed to exec spawn helper: pid: 65, exit value: 1
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 14 more
```

**Steps to reproduce the issue**
This build is done in docker using the following command:

```
RUN native-image --static --libc=glibc --target=linux-amd64 --gc=serial \
    -J-Xlog:gc \
    -H:+ReportUnsupportedElementsAtRuntime \
    -H:+ReportExceptionStackTraces \
    -H:-CheckToolchain \
    -cp ...
```

from this image: `ghcr.io/graalvm/native-image-community:17-muslib`

**Describe GraalVM and your environment:**
 - OS: macOS Ventura
 - Architecture: Apple M1 Pro

**Comment by oubidar-Abderrahim** [comment]
Hi, M1 Pro uses Silicon to my knowledge, Static native images are supported only on amd64. are you building an amd64 docker image?

**Comment by SimoneGiusso** [comment]
> Static native images are supported only on amd64

Well, this is not true according to the [documentation](https://www.graalvm.org/22.0/reference-manual/native-image/ARM64/). However I'm targeting `--target=linux-amd64`
