### ISSUE TITLE
mx configuration assumes XML plist on macOS, while a binary plist is also valid

### ISSUE THREAD

**Issue by Berstanio** [oracle/graal#8719]
**Describe the issue**
I am trying to build graal from source with the command `mx --env ce [...]`. I have my JAVA_HOME pointed to a Corretto 21.0.2 installation. When trying to run any command I get an exception (see stacktrace below). 
The issue is the following line:
https://github.com/oracle/graal/blob/e96f9a550406fd96b20ad7d6dc18683e99bb5386/sdk/mx.sdk/mx_sdk_vm_impl.py#L464
This assumes, that the plist inside a JDK distribution is in the xml format, while it can also be in binary. The corretto version earlier e.g. seems to distribute in binary. Converting the plist with `plutil -convert xml1 Info.plist` fixes the issue.

**Steps to reproduce the issue**
1. (Run on macOS)
2. Checkout graal, point JAVA_HOME to any corretto version, e.g. https://corretto.aws/downloads/latest/amazon-corretto-21-aarch64-macos-jdk.tar.gz for M1. Alternativly, convert an xml plist to binary with `plutil -convert binary1 Info.plist`
3. Run `mx --env ce graalvm-show`
 
**Describe GraalVM and your environment:**
 - GraalVM commit: e96f9a550406fd96b20ad7d6dc18683e99bb5386
 - JDK major version: 21
 - OS: macOS 14.4
 - Architecture: aarch64

**More details**
```
Traceback (most recent call last):
  File ".../mx/mx.py", line 31, in <module>
    runpy.run_module("mx")
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File ".../mx/src/mx/__main__.py", line 49, in <module>
    _main_wrapper()
  File ".../mx/src/mx/_impl/mx.py", line 18154, in _main_wrapper
    main()
  File ".../mx/src/mx/_impl/mx.py", line 18059, in main
    primary_suite().recursive_post_init()
  File ".../mx/src/mx/_impl/mx.py", line 2448, in recursive_post_init
    self.visit_imports(Suite._init_metadata_visitor)
  File ".../mx/src/mx/_impl/mx.py", line 2495, in visit_imports
    visitor(self, suite_import, **extra_args)
  File ".../mx/src/mx/_impl/mx.py", line 2462, in _init_metadata_visitor
    imported_suite._init_metadata()
  File ".../mx/src/mx/_impl/mx.py", line 2479, in _init_metadata
    self._load_metadata()
  File ".../mx/src/mx/_impl/mx.py", line 2713, in _load_metadata
    self.mx_register_dynamic_suite_constituents(_register_project, _register_distribution)
  File ".../graal/sdk/mx.sdk/mx_sdk.py", line 195, in mx_register_dynamic_suite_constituents
    mx_sdk_vm_impl.mx_register_dynamic_suite_constituents(register_project, register_distribution)
  File ".../graal/sdk/mx.sdk/mx_sdk_vm_impl.py", line 3449, in mx_register_dynamic_suite_constituents
    _final_graalvm_distribution = get_final_graalvm_distribution()
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../graal/sdk/mx.sdk/mx_sdk_vm_impl.py", line 3101, in get_final_graalvm_distribution
    _final_graalvm_distribution = GraalVmLayoutDistribution(_graalvm_base_name, stage1=False)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../graal/sdk/mx.sdk/mx_sdk_vm_impl.py", line 940, in __init__
    super(GraalVmLayoutDistribution, self).__init__(base_name, **kw_args)
  File ".../graal/sdk/mx.sdk/mx_sdk_vm_impl.py", line 893, in __init__
    super(AbstractGraalVmLayoutDistribution, self).__init__(
  File ".../graal/sdk/mx.sdk/mx_sdk_vm_impl.py", line 530, in __init__
    incl_list = _patch_darwin_jdk()
                ^^^^^^^^^^^^^^^^^^^
  File ".../graal/sdk/mx.sdk/mx_sdk_vm_impl.py", line 464, in _patch_darwin_jdk
    root = etreeParse(orig_info_plist)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/xml/etree/ElementTree.py", line 1218, in parse
    tree.parse(source, parser)
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/xml/etree/ElementTree.py", line 580, in parse
    self._root = parser._parse_whole(source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 8
```

**Comment by oubidar-Abderrahim** [comment]
Thank you for reaching out. Using Corretto as JAVA_HOME is not supported. However, if you’d like to submit a pull request that makes it work with Corretto, we can review it and consider it for merging. Thank you

**Comment by Berstanio** [comment]
Thank you for the reply!

> Using Corretto as JAVA_HOME is not supported

What is a supported JAVA_HOME? Only labsopenjdk? The docs, from what I found, only mention:
> A common requirement is that the JAVA_HOME environment variable must point to the latest JVMCI-enabled JDK8 ([pre-built archives](https://github.com/graalvm/openjdk8-jvmci-builder/releases); [build instructions](https://github.com/graalvm/openjdk8-jvmci-builder)).

(Source: https://github.com/oracle/graal/tree/master/vm)

which points to an archived repository which doesn't even have mac builds.
