### ISSUE TITLE
Premature initialization of SVM encodings

### ISSUE THREAD

**Issue by sgammon** [oracle/graal#8795]
## Describe the issue

When building a Truffle-enabled `native-image` with a certain combination of `Feature` implementations on the classpath, initialization of registered encodings for `TruffleString` may occur before the full suite of Truffle languages has loaded; this causes an invalid state which causes TruffleRuby to crash later, at runtime.

Truffle decides [whether to enable `JCodings`](https://github.com/oracle/graal/blob/407ca89d90b9a37f0aded86e334c2711d16b411e/truffle/src/com.oracle.truffle.api.strings/src/com/oracle/truffle/api/strings/JCodings.java#L60) based on a simple condition:

https://github.com/oracle/graal/blob/407ca89d90b9a37f0aded86e334c2711d16b411e/truffle/src/com.oracle.truffle.api.strings/src/com/oracle/truffle/api/strings/JCodings.java#L60

[`TStringAccessor` delegates](https://github.com/oracle/graal/blob/master/truffle/src/com.oracle.truffle.api.strings/src/com/oracle/truffle/api/strings/TStringAccessor.java#L67) to the engine:

https://github.com/oracle/graal/blob/407ca89d90b9a37f0aded86e334c2711d16b411e/truffle/src/com.oracle.truffle.api.strings/src/com/oracle/truffle/api/strings/TStringAccessor.java#L66-L68

Which delegates to [`EngineAccessor`](https://github.com/oracle/graal/blob/407ca89d90b9a37f0aded86e334c2711d16b411e/truffle/src/com.oracle.truffle.polyglot/src/com/oracle/truffle/polyglot/EngineAccessor.java#L1982-L1985):

https://github.com/oracle/graal/blob/407ca89d90b9a37f0aded86e334c2711d16b411e/truffle/src/com.oracle.truffle.polyglot/src/com/oracle/truffle/polyglot/EngineAccessor.java#L1982-L1985

Which ultimately [calls into the `LanguageCache`](https://github.com/oracle/graal/blob/master/truffle/src/com.oracle.truffle.polyglot/src/com/oracle/truffle/polyglot/LanguageCache.java#L214-L220):

https://github.com/oracle/graal/blob/407ca89d90b9a37f0aded86e334c2711d16b411e/truffle/src/com.oracle.truffle.polyglot/src/com/oracle/truffle/polyglot/LanguageCache.java#L214-L220

... which then queries the registered Truffle languages to determine if all codings are needed.

However, at this stage of execution, it is not guaranteed that Truffle languages [have loaded yet via `TruffleBaseFeature`](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.truffle/src/com/oracle/svm/truffle/TruffleBaseFeature.java#L247-L255):

https://github.com/oracle/graal/blob/407ca89d90b9a37f0aded86e334c2711d16b411e/substratevm/src/com.oracle.svm.truffle/src/com/oracle/svm/truffle/TruffleBaseFeature.java#L247-L255

TruffleRuby at latest release happens to [depend on all encodings](https://github.com/oracle/truffleruby/blob/vm-24.0.1/src/main/java/org/truffleruby/RubyLanguage.java#L163). As a result, the `native-image` created under these conditions either breaks immediately at runtime, with:

```
Caused by: java.lang.IllegalArgumentException: unknown encoding: "ASCII-8BIT"
        at org.graalvm.truffle/com.oracle.truffle.api.strings.InternalErrors.illegalArgument(InternalErrors.java:76)
        at org.graalvm.truffle/com.oracle.truffle.api.strings.InternalErrors.unknownEncoding(InternalErrors.java:96)
        at org.graalvm.truffle/com.oracle.truffle.api.strings.TruffleString$Encoding.fromJCodingName(TruffleString.java:1094)
        at org.truffleruby.core.encoding.TStringUtils.jcodingToTEncoding(TStringUtils.java:43)
        at org.truffleruby.core.encoding.RubyEncoding.<init>(RubyEncoding.java:57)
        at org.truffleruby.core.encoding.Encodings.initializeRubyEncodings(Encodings.java:95)
        at org.truffleruby.core.encoding.Encodings.<clinit>(Encodings.java:43)
```

... or at build time with the same exception, if `--initialize-at-build-time=org.truffleruby.core.encoding.Encodings` is passed.

## Steps to reproduce the issue

In our case ([Elide](https://github.com/elide-dev/elide)), we are building against latest (`24.0.1`) `native-image`, with GraalPython, TruffleRuby, and GraalJs.

GraalPython triggers the early initialization of `TruffleString` encodings via a handful of calls in the [`BouncyCastleFeature`](https://github.com/oracle/graalpython/blob/master/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/BouncyCastleFeature.java) and [`JNIFeature`](https://github.com/oracle/graalpython/blob/master/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/JNIFeature.java) classes. In both cases, there are checks against `PythonOptions` static fields; for example [here](https://github.com/oracle/graalpython/blob/0b2a38ff709eb9e40ca7e18ba259ff925aae1cd2/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/JNIFeature.java#L53). It is the [class initialization](https://github.com/oracle/graalpython/blob/0b2a38ff709eb9e40ca7e18ba259ff925aae1cd2/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/runtime/PythonOptions.java#L75-L77) of `PythonOptions` which initializes encodings with `TruffleString` literals used at class-init time.

1. `git clone git@github.com:elide-dev/elide.git -b main`
2. `cd elide && ./gradlew build -x test -x check`
3. `vim ./packages/cli/build.gradle.kts`
4. Change `enableRuby` to `true`
5. `./gradlew :packages:cli:nativeCompile`
6. `./packages/cli/build/native/nativeCompile/elide.debug shell --language=RUBY`

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **`24.0.1`**
 - JDK major version: **`22.0.1`**
 - OS: **macOS Sonoma `14.3.1`**
 - Architecture: **M-series (aarch64)**

**Comment by fernando-valdez** [comment]
Thanks for reporting this. I will take a look at it

**Comment by eregon** [comment]
This specific code changed on master, compare
24.0: https://github.com/oracle/graal/blob/release/graal-vm/24.0/truffle/src/com.oracle.truffle.api.strings/src/com/oracle/truffle/api/strings/TruffleString.java#L1049-L1051
master: https://github.com/oracle/graal/blob/c0959eeb526e2d7b4c8d12b0dd51c05c7ba0e9e1/truffle/src/com.oracle.truffle.api.strings/src/com/oracle/truffle/api/strings/JCodings.java#L143

Could you try with master too?
There are dev builds at https://github.com/graalvm/graalvm-ce-dev-builds and https://github.com/graalvm/oracle-graalvm-ea-builds/releases.
I suspect no error or a different error on master.

**Comment by eregon** [comment]
FWIW I tried to reproduce on GraalVM for JDK 23.0.2 (so 24.1.2), but failed with:
```
> Task :packages:test:transformCommonMainDependenciesMetadata
Dependency verification failed for configuration ':packages:test:commonMainResolvableDependenciesMetadata'
16 artifacts failed verification:
  - infinispan-bom-15.0.0.Final.pom (org.infinispan:infinispan-bom:15.0.0.Final) from repository MavenRepo
...
```
`./gradlew --write-verification-metadata pgp,sha256,sha512 help` worked.
Then:
```
$ ./gradlew build -x test -x check                              
Configuration on demand is an incubating feature.
Type-safe project accessors is an incubating feature.
> Task :packages:sqlite:checkNative FAILED
> Task :packages:graalvm:checkNative FAILED

[Incubating] Problems report is available at: file:///home/eregon/code/elide/build/reports/problems/problems-report.html

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':packages:sqlite:checkNative'.
> SQLite JDBC native library not found at '/home/eregon/code/elide/target/debug/libsqlitejdbc.so'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':packages:graalvm:checkNative'.
> Required path does not exist: '/home/eregon/code/elide/target/debug'. Please build Elide's native layer with 'make natives' or 'cargo build'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.
==============================================================================

BUILD FAILED in 5s
61 actionable tasks: 6 executed, 55 up-to-date
```

**Comment by eregon** [comment]
Also I see https://github.com/elide-dev/elide/blob/864d39e7d7b43c2073367666bb2bf829a785d31a/packages/cli/build.gradle.kts#L82 is true, does that mean this is no longer an issue?

**Comment by woess** [comment]
@eregon I, too, suspect this is no longer an issue since 24.1 due to the above changes (but didn't verify).

**Comment by sgammon** [comment]
Hi, reporter here. I believe this was solved :) I will close for now. Thank you GraalVM team for your hard work.
