### ISSUE TITLE
No such file or directory: graal/sdk/mxbuild/linux-amd64/polybench.image/polybench

### ISSUE THREAD

**Issue by oroppas** [oracle/graal#8809]
**Describe the issue**
Building process fails with `graal/sdk/mxbuild/linux-amd64/polybench.image/polybench` not being built.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. **git clone https://github.com/oracle/graal**
2. **git clone https://github.com/oracle/graalpython**
3. **git clone https://github.com/oracle/graaljs**
4. **git clone https://github.com/graalvm/mx**
5. **wget -qO- https://github.com/graalvm/labs-openjdk-21/releases/download/jvmci-23.1-b33/labsjdk-ce-21.0.2+13-jvmci-23.1-b33-linux-amd64.tar.gz | tar xvz**
6. **cd graal/vm**
7. `JAVA_HOME=$PWD/../../labsjdk-ce-21.0.2-jvmci-23.1-b33 ../../mx/mx --max-cpus 2 --dynamicimports /substratevm,/tools,/sulong,/graal-nodejs,/graalpython,/wasm,/espresso build
`

**Describe GraalVM and your environment:**
 - GraalVM version **master branch**
 - JDK major version: **21.0.1**
 - OS: **Fedora 39**
 - Architecture: **AMD64**

**More details**
Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
Archiving GRAALVM_1952F01966_JAVA21... [dependencies updated: espresso.image, ESPRESSO, ESPRESSO_SUPPORT, TRUFFLENODE_GRAALVM_SUPPORT, GRAALPYTHON, GRAALPYTHON_GRAALVM_SUPPORT, graalvm-jimage, graalvm-native-binutil.image, graalvm-native-clang++.image, graalvm-native-clang-cl.image, graalvm-native-clang.image, graalvm-native-flang.image, graalvm-native-ld.image, java.base.jmod_modifier, jvmcicompiler-library_native-image.properties, libgraal-nodejs.so.image, libjavavm.so.image, libjsvm.so.image, libjvmcicompiler.so.image, libllvmvm.so.image, libnative-image-agent.so.image, libnative-image-diagnostics-agent.so.image, libpolyglot.so.image, libpythonvm.so.image, libwasmvm.so.image, native-image-agent-library_native-image.properties, native-image-configure-launcher_native-image.properties, native-image-configure.image, native-image-diagnostics-agent-library_native-image.properties, native-image-launcher_native-image.properties, native-image.image, org.graalvm.language.java.ni_resources_filelist, org.graalvm.language.nodejs.ni_resources_filelist, org.graalvm.language.python.ni_resources_filelist, org.graalvm.launcher.native.js, org.graalvm.launcher.native.llvm, org.graalvm.launcher.native.python, org.graalvm.launcher.native.wasm, polybench.image, polyglot.image, GRAAL_HOTSPOT_LIBRARY, JUNIT_SUPPORT, JVMTI_AGENT_BASE, LIBRARY_SUPPORT, NATIVE_IMAGE_BASE, OBJECTFILE, POINTSTO, POLYGLOT_NATIVE_API, POLYGLOT_NATIVE_API_HEADERS, SVM, SVM_AGENT, SVM_CONFIGURE, SVM_DIAGNOSTICS_AGENT, SVM_DRIVER, SVM_LLVM, TRUFFLE_RUNTIME_SVM]
Archiving GRAALVM_1952F01966_JAVA21: Failed due to error: [Errno 2] No such file or directory: '/home/ryuta/packages/graalvm/graalvm/graal/sdk/mxbuild/linux-amd64/polybench.image/polybench'
Exception in thread Thread-880 (executeTask):
Traceback (most recent call last):
  File "/usr/lib64/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/home/ryuta/packages/graalvm/graalvm/mx/src/mx/_impl/mx.py", line 390, in run
    super(_DummyProcess, self).run()
  File "/usr/lib64/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ryuta/packages/graalvm/graalvm/mx/src/mx/_impl/mx.py", line 14641, in executeTask
    task.execute()
  File "/home/ryuta/packages/graalvm/graalvm/mx/src/mx/_impl/build/tasks/build.py", line 165, in execute
    _built = self.build()
             ^^^^^^^^^^^^
  File "/home/ryuta/packages/graalvm/graalvm/graal/sdk/mx.sdk/mx_sdk_vm_impl.py", line 1096, in build
    super(GraalVmLayoutDistributionTask, self).build()
  File "/home/ryuta/packages/graalvm/graalvm/graal/sdk/mx.sdk/mx_sdk_vm_impl.py", line 857, in build
    super(BaseGraalVmLayoutDistributionTask, self).build()
  File "/home/ryuta/packages/graalvm/graalvm/mx/src/mx/_impl/mx.py", line 5023, in build
    self.subject.make_archive()
  File "/home/ryuta/packages/graalvm/graalvm/mx/src/mx/_impl/mx.py", line 5878, in make_archive
    self._install_source(source, output, destination, arc)
  File "/home/ryuta/packages/graalvm/graalvm/mx/src/mx/_impl/mx.py", line 5641, in _install_source
    _install_source_files([next(d.getArchivableResults(single=True))], archive=archive)
  File "/home/ryuta/packages/graalvm/graalvm/mx/src/mx/_impl/mx.py", line 5625, in _install_source_files
    merge_recursive(_source_file, _dst, _arcname, excludes, archive=archive)
  File "/home/ryuta/packages/graalvm/graalvm/mx/src/mx/_impl/mx.py", line 5593, in merge_recursive
    archiver.add(src, dst, provenance)
  File "/home/ryuta/packages/graalvm/graalvm/mx/src/mx/_impl/mx.py", line 15219, in add
    self._add_f(filename, archive_name, provenance)
  File "/home/ryuta/packages/graalvm/graalvm/mx/src/mx/_impl/mx.py", line 15148, in _add_tar
    self.zf.add(filename, archive_name, filter=self._tarinfo_filter, recursive=False)
  File "/usr/lib64/python3.12/tarfile.py", line 2164, in add
    tarinfo = self.gettarinfo(name, arcname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/tarfile.py", line 2037, in gettarinfo
    statres = os.lstat(name)
              ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/ryuta/packages/graalvm/graalvm/graal/sdk/mxbuild/linux-amd64/polybench.image/polybench'
Archiving GRAALVM_1952F01966_JAVA21 failed
```

**Comment by oubidar-Abderrahim** [comment]
Hi, if this issue is still present in the latest GraalVM version, please create a new issue to be triaged properly, thank you
