### ISSUE TITLE
BouncyCastle SP800SecureRandom initialization at build-time

### ISSUE THREAD

**Issue by r1cky33** [oracle/graal#8842]
Hi!

I'm currently experiencing a problem where  `org.bouncycastle.crypto.prng.SP800SecureRandom`  always gets initialized at build-time by `org.bouncycastle.jcajce.provider.drbg.DRBG`.

### Environment
I'm trying to compile a Spring-Boot Application (version=3.2.4) natively using:
```
                <groupId>org.graalvm.buildtools</groupId>
                <artifactId>native-maven-plugin</artifactId>
                <version>0.10.1</version> <!-- Latest stable version -->
```
JDK: `VM Oracle GraalVM 17.0.10+11.1 (build 17.0.10+11-LTS-jvmci-23.0-b27, mixed mode, sharing)`
Build: Maven
BouncyCastle: bctls-jdk15to18 (version=1.78.1)

Native-Maven-Plugin configuration:
```
<build>
        <plugins>
            <plugin>
                <groupId>org.graalvm.buildtools</groupId>
                <artifactId>native-maven-plugin</artifactId>
                <version>0.10.1</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>com.test.dev.SimulatorApplication</mainClass>
                    <outputDirectory>target/native-image</outputDirectory>
                    <buildArgs>
                        <arg>-H:ConfigurationFileDirectories=/home/richarch/test/repos/testkon/application-simulator/config/</arg>
                        <arg>--enable-all-security-services</arg>
                        <arg>-H:+ReportExceptionStackTraces</arg>

                        <arg>--initialize-at-build-time=org.bouncycastle</arg>

                        <arg>--trace-class-initialization=org.bouncycastle.crypto.prng.SP800SecureRandom,org.bouncycastle.jcajce.provider.drbg.DRBG,org.bouncycastle.jce.provider.BouncyCastleProvider</arg>
                        <arg>--initialize-at-run-time=org.bouncycastle.crypto.prng.SP800SecureRandom</arg>
                    </buildArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

### Compilation Issue
```
Error: Classes that should be initialized at run time got initialized during image building:
 org.bouncycastle.crypto.prng.SP800SecureRandom the class was requested to be initialized at run time (from command line with 'org.bouncycastle.crypto.prng.SP800SecureRandom'). org.bouncycastle.jcajce.provider.drbg.DRBG$Default caused initialization of this class with the following trace: 
        at org.bouncycastle.crypto.prng.SP800SecureRandom.<clinit>(Unknown Source)
        at org.bouncycastle.crypto.prng.SP800SecureRandomBuilder.buildHMAC(Unknown Source)
        at org.bouncycastle.jcajce.provider.drbg.DRBG$OneShotHybridEntropySource.<init>(Unknown Source)
        at org.bouncycastle.jcajce.provider.drbg.DRBG.createBaseRandom(Unknown Source)
        at org.bouncycastle.jcajce.provider.drbg.DRBG.access$100(Unknown Source)
        at org.bouncycastle.jcajce.provider.drbg.DRBG$Default.<clinit>(Unknown Source)


com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 org.bouncycastle.crypto.prng.SP800SecureRandom the class was requested to be initialized at run time (from command line with 'org.bouncycastle.crypto.prng.SP800SecureRandom'). org.bouncycastle.jcajce.provider.drbg.DRBG$Default caused initialization of this class with the following trace: 
        at org.bouncycastle.crypto.prng.SP800SecureRandom.<clinit>(Unknown Source)
        at org.bouncycastle.crypto.prng.SP800SecureRandomBuilder.buildHMAC(Unknown Source)
        at org.bouncycastle.jcajce.provider.drbg.DRBG$OneShotHybridEntropySource.<init>(Unknown Source)
        at org.bouncycastle.jcajce.provider.drbg.DRBG.createBaseRandom(Unknown Source)
        at org.bouncycastle.jcajce.provider.drbg.DRBG.access$100(Unknown Source)
        at org.bouncycastle.jcajce.provider.drbg.DRBG$Default.<clinit>(Unknown Source)


        at com.oracle.svm.core.util.UserError.abort(UserError.java:73)
        at com.oracle.svm.hosted.classinitialization.ProvenSafeClassInitializationSupport.checkDelayedInitialization(ProvenSafeClassInitializationSupport.java:277)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:164)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$10(NativeImageGenerator.java:770)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:89)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$11(NativeImageGenerator.java:770)
        at com.oracle.graal.pointsto.AbstractAnalysisEngine.runAnalysis(AbstractAnalysisEngine.java:179)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:767)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:582)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:539)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:408)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:612)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:134)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:626)
```

I tried specifying `<arg>--initialize-at-run-time=org.bouncycastle.crypto.prng.SP800SecureRandom</arg>` or `org.bouncycastle.crypto.prng.SP800SecureRandom,org.bouncycastle.jcajce.provider.drbg.DRBG` but this doesn't help since the origin of the build-time initialization seems to be within the `BouncyCastleProvider` itself.

**Comment by r1cky33** [comment]
Fixed by:
```
                        <arg>--trace-class-initialization=org.bouncycastle.crypto.prng.SP800SecureRandom,org.bouncycastle.jcajce.provider.drbg.DRBG,org.bouncycastle.jce.provider.BouncyCastleProvider</arg>
                        <arg>--rerun-class-initialization-at-runtime=org.bouncycastle.jcajce.provider.drbg.DRBG$Default,org.bouncycastle.jcajce.provider.drbg.DRBG$NonceAndIV</arg>
                        <arg>--rerun-class-initialization-at-runtime=org.bouncycastle.crypto.prng.SP800SecureRandom</arg>
```
