### ISSUE TITLE
Native build failed after upgrade graalVM jdk 22 on linux but success on macOS

### ISSUE THREAD

**Issue by GrapeBaBa** [oracle/graal#8862]
**Describe the issue**
After upgrade graalVM jdk 22, native build failed.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
```sh
git clone --single-branch --branch jdk22 git@github.com:optimism-java/hildr.git
//if local is linux
./gradlew buildBinary

//if local is non linux
cd docker
COMPOSE_PROFILES=hildr-node-native,op-geth,metrics docker compose up -d
```

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **[e.g. EE 19.3, CE 20.0, CE 20.1.0-dev-20200304_0848]**
 - JDK major version: **22**
 - OS: **ubuntu latest**
 - Architecture: **AMD64**

**More details**
Consider adding the `--native-image-info` and  `--verbose` flags when building your native image and paste output below.

Add any other information about the problem here. Especially important are stack traces or log output. Feel free to link to gists or to screenshots if necessary.
```
398.0 Error: Detected a FileDescriptor in the image heap. File descriptors opened during image generation are no longer open at image runtime, and the files might not even be present anymore at image runtime. Try avoiding to initialize the class that caused initialization of the FileDescriptor.
398.0 The culprit object has been instantiated by the 'sun.security.provider.SunEntries' class initializer with the following trace:
398.0   at java.io.FileDescriptor.<init>(FileDescriptor.java:127)
398.0   at java.io.FileInputStream.<init>(FileInputStream.java:149)
398.0   at sun.security.provider.FileInputStreamPool.getInputStream(FileInputStreamPool.java:110)
398.0   at sun.security.provider.NativePRNG$RandomIO.<init>(NativePRNG.java:390)
398.0   at sun.security.provider.NativePRNG$1.run(NativePRNG.java:192)
398.0   at sun.security.provider.NativePRNG$1.run(NativePRNG.java:132)
398.0   at java.security.AccessController.executePrivileged(AccessController.java:778)
398.0   at java.security.AccessController.doPrivileged(AccessController.java:319)
398.0   at sun.security.provider.NativePRNG.initIO(NativePRNG.java:131)
398.0   at sun.security.provider.NativePRNG.<clinit>(NativePRNG.java:93)
398.0   at sun.security.provider.SunEntries.<clinit>(SunEntries.java:362)
398.0 The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
398.0 Trace: Object was reached by
398.0   reading field java.io.FileInputStream.fd of constant 
398.0     java.io.FileInputStream@4f24c58e: java.io.FileInputStream@4f24c58e
398.0   reading field java.io.FilterInputStream.in of constant 
398.0     sun.security.provider.FileInputStreamPool$UnclosableInputStream@7a7afc35: sun.security.provider.FileInputStreamPool$UnclosableInputStream@7a7afc35
398.0   reading field sun.security.provider.NativePRNG$RandomIO.seedIn of constant 
398.0     sun.security.provider.NativePRNG$RandomIO@fefb164: sun.security.provider.NativePRNG$RandomIO@fefb164
398.0   reading static field sun.security.provider.NativePRNG$Blocking.INSTANCE
398.0     at <unknown-location>
398.0   registered as read because: null
398.0 Error: Detected a FileDescriptor in the image heap. File descriptors opened during image generation are no longer open at image runtime, and the files might not even be present anymore at image runtime. Try avoiding to initialize the class that caused initialization of the FileDescriptor.
398.0 The culprit object has been instantiated by the 'sun.security.provider.SunEntries' class initializer with the following trace:
398.0   at java.io.FileDescriptor.<init>(FileDescriptor.java:127)
398.0   at java.io.FileInputStream.<init>(FileInputStream.java:149)
398.0   at sun.security.provider.FileInputStreamPool.getInputStream(FileInputStreamPool.java:110)
398.0   at sun.security.provider.NativePRNG$RandomIO.<init>(NativePRNG.java:391)
398.0   at sun.security.provider.NativePRNG$1.run(NativePRNG.java:192)
398.0   at sun.security.provider.NativePRNG$1.run(NativePRNG.java:132)
398.0   at java.security.AccessController.executePrivileged(AccessController.java:778)
398.0   at java.security.AccessController.doPrivileged(AccessController.java:319)
398.0   at sun.security.provider.NativePRNG.initIO(NativePRNG.java:131)
398.0   at sun.security.provider.NativePRNG.<clinit>(NativePRNG.java:93)
398.0   at sun.security.provider.SunEntries.<clinit>(SunEntries.java:362)
398.0 The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
398.0 Trace: Object was reached by
398.0   reading field java.io.FileInputStream.fd of constant 
398.0     java.io.FileInputStream@22ab7cdd: java.io.FileInputStream@22ab7cdd
398.0   reading field java.io.FilterInputStream.in of constant 
398.0     sun.security.provider.FileInputStreamPool$UnclosableInputStream@20043089: sun.security.provider.FileInputStreamPool$UnclosableInputStream@20043089
398.0   reading field sun.security.provider.NativePRNG$RandomIO.seedIn of constant 
398.0     sun.security.provider.NativePRNG$RandomIO@58db6c3d: sun.security.provider.NativePRNG$RandomIO@58db6c3d
398.0   reading static field sun.security.provider.NativePRNG$NonBlocking.INSTANCE
398.0     at <unknown-location>
398.0   registered as read because: null
398.0 
398.0 com.oracle.svm.driver.NativeImage$NativeImageError
398.0   at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.showError(NativeImage.java:2258)
398.0   at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.build(NativeImage.java:1871)
398.0   at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1830)
398.0   at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.main(NativeImage.java:1812)
398.0   at java.base@22.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
398.1 
398.1 FAILURE: Build failed with an exception.
398.1 
398.1 * Where:
398.1 Build file '/root/hildr/hildr-node/build.gradle' line: 348
398.1 
```

**Comment by fernando-valdez** [comment]
Hi, can you please share which version was working before? was that version working on iOS and Linux too?

Finally, the error is showing this message:
`The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.`

did you try that?

**Comment by GrapeBaBa** [comment]
> Hi, can you please share which version was working before? was that version working on iOS and Linux too?
> 
> Finally, the error is showing this message: `The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.`
> 
> did you try that?

My laptop is macOS, it can build successfully. The build error happened on Linux, the version is latest graalvm here https://github.com/optimism-java/hildr/blob/jdk22/docker/Dockerfile#L3 .

I have added all the classes in the trace, however still not works.

**Comment by fernando-valdez** [comment]
Can you try to add this flag `-H:ThrowMissingRegistrationErrors` and share your results?

**Comment by GrapeBaBa** [comment]
> Can you try to add this flag `-H:ThrowMissingRegistrationErrors` and share your results? Also, just to be sure, you are getting this error when building the native image, right?

Got error when added this flag `Error: Invalid native-image hosted-option -H:ThrowMissingRegistrationErrors at user`.

Yes, only build native image on ubuntu, macOS is OK.

**Comment by gingk1212** [comment]
I also tried to reproduce the issue on my local Linux x64 environment (WSL 2 + Ubuntu 24.0.1), but the build succeeded without any problems.

Command:

```
$ git clone --single-branch --branch jdk22 git@github.com:optimism-java/hildr.git
$ ./gradlew buildBinary
...
BUILD SUCCESSFUL in 1m 39s
7 actionable tasks: 7 executed
$ ./hildr-node/build/binary/hildr-node
SLF4J(I): Connected with provider of type [ch.qos.logback.classic.spi.LogbackServiceProvider]
Missing required options: '--l1-rpc-url=<l1RpcUrl>', '--l1-ws-rpc-url=<l1WsRpcUrl>', '--l1-beacon-url=<l1BeaconUrl>', '--l2-rpc-url=<l2RpcUrl>', '--l2-engine-url=<l2EngineUrl>', '--rpc-port=<rpcPort>'
Usage: hildr [-hvV] [--devnet] [--metrics-enable]
             [--checkpoint-hash=<checkpointHash>]
             ...
```

Version:

```
$ java -version
java version "22.0.2" 2024-07-16
Java(TM) SE Runtime Environment Oracle GraalVM 22.0.2+9.1 (build 22.0.2+9-jvmci-b01)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 22.0.2+9.1 (build 22.0.2+9-jvmci-b01, mixed mode, sharing)
```

I hope this information is helpful in some way.
