### ISSUE TITLE
java.nio.file.FileSystemNotFoundException: nul

### ISSUE THREAD

**Issue by shenfengok** [oracle/graal#888]
my java code 
`    try (Context context = Context.create("js")) {
            if (null == jsStr) {
                jsStr = readFromInputStream(js.getInputStream());
            }
            Source source = Source.newBuilder("js", jsStr,"src.js").build();
            context.eval(source);
            org.graalvm.polyglot.Value bindings = context.getBindings("js").getMember("ytfmt_search_run");
            org.graalvm.polyglot.Value json = bindings.execute(s);
            var str = json.asString();
            jsonView = JSON.parseObject(str, MyJSONVIew.class);
        } catch (Exception e) {
            log.error("error:", e);
        }`

and in linux system ,error comes below 

l
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:169) ~[jdk.zipfs:na]
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:155) ~[jdk.zipfs:na]
	at java.base/java.nio.file.Path.of(Path.java:208) ~[na:na]
	at java.base/java.nio.file.Paths.get(Paths.java:97) ~[na:na]
	at com.oracle.truffle.polyglot.LanguageCache.collectLanguages(LanguageCache.java:284) ~[truffle-api-1.0.0-rc9.jar!/:na]
	at com.oracle.truffle.polyglot.LanguageCache.createLanguages(LanguageCache.java:211) ~[truffle-api-1.0.0-rc9.jar!/:na]
	at com.oracle.truffle.polyglot.LanguageCache.languages(LanguageCache.java:201) ~[truffle-api-1.0.0-rc9.jar!/:na]
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.initializeLanguages(PolyglotEngineImpl.java:480) ~[truffle-api-1.0.0-rc9.jar!/:na]
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.<init>(PolyglotEngineImpl.java:168) ~[truffle-api-1.0.0-rc9.jar!/:na]
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.<init>(PolyglotEngineImpl.java:152) ~[truffle-api-1.0.0-rc9.jar!/:na]
	at com.oracle.truffle.polyglot.PolyglotImpl.buildEngine(PolyglotImpl.java:197) ~[truffle-api-1.0.0-rc9.jar!/:na]
	at org.graalvm.polyglot.Engine$Builder.build(Engine.java:488) ~[graal-sdk-1.0.0-rc9.jar!/:na]
	at org.graalvm.polyglot.Context$Builder.build(Context.java:1083) ~[graal-sdk-1.0.0-rc9.jar!/:na]
	at org.graalvm.polyglot.Context.create(Context.java:660) ~[graal-sdk-1.0.0-rc9.jar!/:na]
	at tv.rr.thor.content.service.impl.YoutubeServiceImpl.getScriptData(YoutubeServiceImpl.java:117) ~[classes!/:0.0.1-SNAPSHOT]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:107) ~[reactor-core-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1476) ~[reactor-core-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241) ~[reactor-core-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121) ~[reactor-core-3.2.3.RELEASE.jar!/:3.2.3.RELEASE]

**Comment by wirthi** [comment]
Hi @shenfengok 

I am closing this older ticket. If this problem persists, please post the full error message and other relevant data like GraalVM release version, Java version, the exact command you run, etc. Best if you can prepare a working (or rather, failing) example so we can directly investigate your full setup.

Thanks,
CHristian
