### ISSUE TITLE
jdk.graal.compiler.debug.GraalError: should not reach here: kind=V256_QWORD input=xmm6|V256_QWORD result=xmm0|V256_QWORD

### ISSUE THREAD

**Issue by Thihup** [oracle/graal#8979]
**Describe the issue**
Since JDK 22, the class [HBShaper](https://github.com/openjdk/jdk/blob/master/src/java.desktop/share/classes/sun/font/HBShaper.java#L54) was modified to use the FFI API. It seems to have broken the native image generation when using the `java.deskop` module.

I was trying to register manually both the downcalls and upcalls, and I hit this issue. 

Source code of the Feature:
```java
import org.graalvm.nativeimage.hosted.Feature;
import org.graalvm.nativeimage.hosted.RuntimeForeignAccess;

import java.lang.foreign.FunctionDescriptor;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.ValueLayout.JAVA_INT;

public class NativeImageFeature implements Feature {

    @Override
    public void duringSetup(DuringSetupAccess access) {
        RuntimeForeignAccess.registerForDowncall(FunctionDescriptor.of(ADDRESS, JAVA_LONG));
        RuntimeForeignAccess.registerForDowncall(FunctionDescriptor.of(ADDRESS, ADDRESS));
        RuntimeForeignAccess.registerForDowncall(FunctionDescriptor.ofVoid(ADDRESS));
        RuntimeForeignAccess.registerForDowncall(FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, JAVA_INT, JAVA_INT, ADDRESS, ADDRESS));
        RuntimeForeignAccess.registerForDowncall(FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, JAVA_INT, ADDRESS, ADDRESS));
        RuntimeForeignAccess.registerForDowncall(FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, JAVA_INT, ADDRESS));
        RuntimeForeignAccess.registerForDowncall(FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, JAVA_INT, ADDRESS));
        RuntimeForeignAccess.registerForDowncall(FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, JAVA_INT, JAVA_INT, ADDRESS, ADDRESS, ADDRESS));
        RuntimeForeignAccess.registerForDowncall(FunctionDescriptor.of(ADDRESS, ADDRESS, ADDRESS, ADDRESS, ADDRESS, ADDRESS));
        RuntimeForeignAccess.registerForDowncall(FunctionDescriptor.ofVoid(JAVA_INT, JAVA_INT, JAVA_INT, JAVA_FLOAT, JAVA_FLOAT, JAVA_FLOAT, JAVA_INT, JAVA_INT, ADDRESS, ADDRESS));
        RuntimeForeignAccess.registerForDowncall(FunctionDescriptor.ofVoid(JAVA_FLOAT, ADDRESS, ADDRESS, ADDRESS, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_FLOAT, JAVA_FLOAT, JAVA_INT, JAVA_INT, ADDRESS, ADDRESS));

        try {
            Method registerForUpcall = RuntimeForeignAccess.class.getDeclaredMethod("registerForUpcall", Object.class, Object[].class);

            Object[] objects = new Object[0];
            registerForUpcall.invoke(null, FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, JAVA_INT, JAVA_INT, ADDRESS, ADDRESS), objects);
            registerForUpcall.invoke(null, FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, JAVA_INT, ADDRESS, ADDRESS), objects);
            registerForUpcall.invoke(null, FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, JAVA_INT, ADDRESS), objects);
            registerForUpcall.invoke(null, FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, JAVA_INT, ADDRESS), objects);
            registerForUpcall.invoke(null, FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, JAVA_INT, JAVA_INT, ADDRESS, ADDRESS, ADDRESS), objects);
            registerForUpcall.invoke(null, FunctionDescriptor.of(JAVA_INT, JAVA_INT, ADDRESS), objects);
            registerForUpcall.invoke(null, FunctionDescriptor.ofVoid(JAVA_INT, JAVA_INT, JAVA_INT, JAVA_FLOAT, JAVA_FLOAT, JAVA_FLOAT, JAVA_INT, JAVA_INT, ADDRESS, ADDRESS), objects);

        } catch (NoSuchMethodException | InvocationTargetException | IllegalAccessException e) {
            throw new RuntimeException(e);
        }

    }
}

```

**Describe GraalVM and your environment:**
 - GraalVM version 23-dev+23.1
 - JDK major version: 23-dev
 - OS: Windows 11
 - Architecture: AMD64

**More details**
```
Fatal error: jdk.graal.compiler.debug.GraalError: should not reach here: kind=V256_QWORD input=xmm6|V256_QWORD result=xmm0|V256_QWORD
	at lir instruction: B0@34 jdk.graal.compiler.lir.amd64.AMD64Move$MoveFromRegOp xmm0|V256_QWORD = MOVE xmm6|V256_QWORD moveKind: V256_QWORD
	at method: void com.oracle.svm.core.foreign.UpcallStubsHolder.upcallLow_IIIFFFIIJJ_V_4LSSnZatMKLNLDtNCLR9dB(int, int, int, float, float, float, int, int, long, long)  [entry point]
	at jdk.graal.compiler/jdk.graal.compiler.debug.GraalError.shouldNotReachHere(GraalError.java:57)
	at jdk.graal.compiler/jdk.graal.compiler.lir.amd64.AMD64Move.reg2reg(AMD64Move.java:565)
	at jdk.graal.compiler/jdk.graal.compiler.lir.amd64.AMD64Move.move(AMD64Move.java:502)
	at jdk.graal.compiler/jdk.graal.compiler.lir.amd64.AMD64Move$AbstractMoveOp.emitCode(AMD64Move.java:78)
	at jdk.graal.compiler/jdk.graal.compiler.lir.amd64.AMD64Move$MoveFromRegOp.emitCode(AMD64Move.java:106)
	at jdk.graal.compiler/jdk.graal.compiler.lir.amd64.AMD64LIRInstruction.emitCode(AMD64LIRInstruction.java:44)
	at jdk.graal.compiler/jdk.graal.compiler.lir.asm.CompilationResultBuilder.emitOp(CompilationResultBuilder.java:598)
	at jdk.graal.compiler/jdk.graal.compiler.lir.asm.CompilationResultBuilder.emitBlock(CompilationResultBuilder.java:574)
	at jdk.graal.compiler/jdk.graal.compiler.lir.asm.CompilationResultBuilder.emitLIR(CompilationResultBuilder.java:527)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.graal.amd64.SubstrateAMD64Backend.emitCode(SubstrateAMD64Backend.java:1603)
	at jdk.graal.compiler/jdk.graal.compiler.core.gen.LIRCompilerBackend.emitCode(LIRCompilerBackend.java:222)
	at jdk.graal.compiler/jdk.graal.compiler.core.gen.LIRCompilerBackend.emitBackEnd(LIRCompilerBackend.java:89)
	at jdk.graal.compiler/jdk.graal.compiler.core.target.Backend.emitBackEnd(Backend.java:294)
	at jdk.graal.compiler/jdk.graal.compiler.core.GraalCompiler.compile(GraalCompiler.java:169)
	at jdk.graal.compiler/jdk.graal.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:136)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:1[288](https://github.com/Thihup/JVisualg/actions/runs/9257622568/job/25466150422#step:8:289))
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:1236)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:306)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:166)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:152)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1726)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1717)
	at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1641)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool.externalHelpQuiesce(ForkJoinPool.java:2530)
	at java.base/java.util.concurrent.ForkJoinPool.helpQuiescePool(ForkJoinPool.java:2564)
	at java.base/java.util.concurrent.ForkJoinPool.awaitQuiescence(ForkJoinPool.java:3800)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.complete(CompletionExecutor.java:208)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.runOnExecutor(CompileQueue.java:604)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.compileAll(CompileQueue.java:920)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.finish(CompileQueue.java:438)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:674)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:551)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:529)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:704)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:140)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:95)
```

**Comment by Thihup** [comment]
It is possible to bypass the use of FFM using the following property: `sun.font.layout.ffm=false`

**Comment by lcbrunetti001** [comment]
@Thihup , how did you solve this? I’m working on a project using GraalVM 23 and facing the same issue. When I use registerForUpcall, the native compilation doesn’t work.
