### ISSUE TITLE
SubstrateVM breaks spring-jcl classpath detection

### ISSUE THREAD

**Issue by sdeleuze** [oracle/graal#904]
Even when using `--allow-incomplete-classpath`, SubstrateVM is unable to make `LogFactory#getLog(java.lang.Class<?>)` from `spring-jcl` logging abstraction running correctly when Log4j is not in the classpath.

A simple repro project is available at https://github.com/sdeleuze/graal-issues/tree/master/spring-log-factory.

During GraalVM native image executio, we see the following error:
```
Fatal error: java.lang.NoClassDefFoundError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:462)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:357)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:501)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:115)
Caused by: java.lang.NoClassDefFoundError: Lorg/apache/logging/log4j/spi/LoggerContext;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredField(Class.java:2068)
	at com.oracle.graal.pointsto.infrastructure.OriginalFieldProvider.getJavaField(OriginalFieldProvider.java:43)
	at com.oracle.graal.pointsto.meta.AnalysisField.getJavaField(AnalysisField.java:420)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readUninitializedStaticValue(AnalysisConstantReflectionProvider.java:136)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:87)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:77)
	at com.oracle.svm.hosted.meta.HostedField.readValue(HostedField.java:156)
	at com.oracle.svm.hosted.thread.VMThreadLocalCollector.sortThreadLocals(VMThreadLocalCollector.java:110)
	at com.oracle.svm.hosted.thread.VMThreadMTFeature.beforeCompilation(VMThreadMTFeature.java:267)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$doRun$2(NativeImageGenerator.java:571)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:571)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.spi.LoggerContext
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 20 more
```

**Comment by cstancu** [comment]
@sdeleuze thanks for your report. Proper support for Java logging is next on my list.

**Comment by sdeleuze** [comment]
@cstancu Any chance you could have a look at this one which is blocking proper logging support on Spring applications?

**Comment by eginez** [comment]
@sdeleuze This is now fixed
```
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< com.sample:spring-log-factory >--------------------
[INFO] Building spring-log-factory 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ spring-log-factory ---
[INFO] Deleting /Users/eginez/src/temp/graal-issues/spring-log-factory/target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ spring-log-factory ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/eginez/src/temp/graal-issues/spring-log-factory/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ spring-log-factory ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/eginez/src/temp/graal-issues/spring-log-factory/target/classes
[INFO]
[INFO] --- maven-assembly-plugin:2.2-beta-5:single (default-cli) @ spring-log-factory ---
[INFO] Building jar: /Users/eginez/src/temp/graal-issues/spring-log-factory/target/spring-log-factory-1.0-SNAPSHOT-jar-with-dependencies.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.710 s
[INFO] Finished at: 2020-04-29T10:24:09-07:00
[INFO] ------------------------------------------------------------------------
[com.sample.app:24056]    classlist:   1,268.02 ms,  1.17 GB
[com.sample.app:24056]        (cap):     969.01 ms,  1.17 GB
[com.sample.app:24056]        setup:   2,032.51 ms,  1.17 GB
[com.sample.app:24056]     (clinit):     117.37 ms,  1.75 GB
[com.sample.app:24056]   (typeflow):   3,684.04 ms,  1.75 GB
[com.sample.app:24056]    (objects):   3,582.86 ms,  1.75 GB
[com.sample.app:24056]   (features):     143.58 ms,  1.75 GB
[com.sample.app:24056]     analysis:   7,661.76 ms,  1.75 GB
[com.sample.app:24056]     universe:     262.06 ms,  1.78 GB
[com.sample.app:24056]      (parse):     424.87 ms,  1.78 GB
[com.sample.app:24056]     (inline):   1,243.54 ms,  1.80 GB
[com.sample.app:24056]    (compile):   3,534.89 ms,  2.07 GB
[com.sample.app:24056]      compile:   5,524.90 ms,  2.07 GB
[com.sample.app:24056]        image:     698.81 ms,  2.07 GB
[com.sample.app:24056]        write:     213.81 ms,  2.07 GB
[com.sample.app:24056]      [total]:  17,908.40 ms,  2.07 GB
In regular JVM
Apr 29, 2020 10:24:28 AM com.sample.App main
SEVERE: Foo

As GraalVM native image
Apr 29, 2020 10:24:28 AM com.sample.App main
SEVERE: Foo```
