### ISSUE TITLE
native-image and poi: Defining hidden classes at runtime is not supported

### ISSUE THREAD

**Issue by nb333999** [oracle/graal#9072]
I encountered a problem when using apache poi to export to excel. In the Windows environment (java -jar), I can export to excel normally. After packaging the project into native-image in the Linux environment, I executed the export again and this error was reported: Defining hidden classes at runtime is not supported. Please help me how to use poi correctly in native-image.

Project operating environment:
GraalVM 21.0.1+12.1
OS: CentOS 7
SpringBoot: 3.1.5
poi-ooxml: 5.2.5
Packaging native image script:
mvn clean package -U
mvn -P native native:compile

Execute script:
./target/demo -Xmx4g --server.port=8070

At runtime, an error is reported after executing the endpoint "/excel":

ERROR StatusLogger Unable to load services for service class org.apache.logging.log4j.spi.Provider
 java.lang.InternalError: com.oracle.svm.core.jdk.UnsupportedFeatureError: Defining hidden classes at runtime is not supported.
	at java.base@21.0.1/java.lang.invoke.InnerClassLambdaMetafactory.generateInnerClass(InnerClassLambdaMetafactory.java:451)
	at java.base@21.0.1/java.lang.invoke.InnerClassLambdaMetafactory.spinInnerClass(InnerClassLambdaMetafactory.java:373)
	at java.base@21.0.1/java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:308)
	at java.base@21.0.1/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:341)
	at org.apache.logging.log4j.util.ServiceLoaderUtil.callServiceLoader(ServiceLoaderUtil.java:110)
	at org.apache.logging.log4j.util.ServiceLoaderUtil$ServiceLoaderSpliterator.<init>(ServiceLoaderUtil.java:146)
	at org.apache.logging.log4j.util.ServiceLoaderUtil.loadClassloaderServices(ServiceLoaderUtil.java:101)
	at org.apache.logging.log4j.util.ServiceLoaderUtil.loadServices(ServiceLoaderUtil.java:83)
	at org.apache.logging.log4j.util.ServiceLoaderUtil.loadServices(ServiceLoaderUtil.java:77)
	at org.apache.logging.log4j.util.ProviderUtil.<init>(ProviderUtil.java:67)
	at org.apache.logging.log4j.util.ProviderUtil.lazyInit(ProviderUtil.java:145)
	at org.apache.logging.log4j.util.ProviderUtil.hasProviders(ProviderUtil.java:129)
	at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:90)
	at org.apache.poi.ooxml.POIXMLDocumentPart.<clinit>(POIXMLDocumentPart.java:56)
	at java.base@21.0.1/java.lang.Class.ensureInitialized(DynamicHub.java:595)
	at java.base@21.0.1/java.lang.Class.ensureInitialized(DynamicHub.java:595)
	at com.example.demo.excel.PoiExcel.write2(PoiExcel.java:38)
	at com.example.demo.excel.PoiExcel.write(PoiExcel.java:34)
	at com.example.demo.excel.PoiExcel.write(PoiExcel.java:29)
	at com.nasa.common.excel.ExcelUtils.write(ExcelUtils.java:28)
	at com.nasa.common.excel.ExcelUtils.write(ExcelUtils.java:24)
	at com.example.demo.CommonRest.excel(CommonRest.java:80)
	at java.base@21.0.1/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base@21.0.1/java.lang.Thread.runWith(Thread.java:1596)
	at java.base@21.0.1/java.lang.Thread.run(Thread.java:1583)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)

[demo.zip](https://github.com/user-attachments/files/15746513/demo.zip)

**Comment by dreamlike-ocean** [comment]
you should try ` mvn clean package && java -agentlib:native-image-agent=config-output-dir=src/main/resources/META-INF/native-image/,experimental-class-define-support --enable-preview -jar target/demo-1.0.jar` to generate config file，
then use `mvn -P native native:compile` to rebuild
![result](https://github.com/oracle/graal/assets/56702218/3fce4e39-5427-40e8-8b48-7e9bc341b62e)

**Comment by nb333999** [comment]
Thank you very much for your help, it's very useful.

**Comment by nb333999** [comment]
> you should try ` mvn clean package && java -agentlib:native-image-agent=config-output-dir=src/main/resources/META-INF/native-image/,experimental-class-define-support --enable-preview -jar target/demo-1.0.jar` to generate config file， then use `mvn -P native native:compile` to rebuild ![result](https://private-user-images.githubusercontent.com/56702218/338178286-3fce4e39-5427-40e8-8b48-7e9bc341b62e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNzQ3MTIsIm5iZiI6MTcxODA3NDQxMiwicGF0aCI6Ii81NjcwMjIxOC8zMzgxNzgyODYtM2ZjZTRlMzktNTQyNy00MGU4LThiNDgtN2U5YmMzNDFiNjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDAyNTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZWM1OTRjNjVlZGRmZDhmMjUxYTcwODZlNmE0MzQ5MWRlOWEwMWUxMTQxNjBjMDgyZWU5ODI0ZWY1ZWM1ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1AmWhw_IKZgOYO-AMXg7lWh6AXaWnwNy3ZYVrbrBQGs)

Thank you very much for your help, it's very useful.

**Comment by imgoby** [comment]
mvn -P native native:compile  was failed:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.3.0:resources (default-resources) on project sail-web: filtering /xxx/src/main/resources/META-INF/native-image/agent-extracted-predefined-classes/8bef38e75959c0755f578f6b182338b79bf922f88b1321a1e38a083ec85d5f5a.classdata to xxx/target/classes/META-INF/native-image/agent-extracted-predefined-classes/8bef38e75959c0755f578f6b182338b79bf922f88b1321a1e38a083ec85d5f5a.classdata failed with MalformedInputException: Input length = 1 -> [Help 1]`
