### ISSUE TITLE
--allow-incomplete-classpath fails with Micronaut and rc12-dev

### ISSUE THREAD

**Issue by ilopmar** [oracle/graal#912]
We have detected a new case of `--allow-incomplete-classpath` not working properly with Micronaut (https://github.com/micronaut-projects/micronaut-core/issues/1110)

- Clone https://github.com/micronaut-graal-tests/micronaut-graal-experiments
- `cd micronaut-graal-experiments/fresh-graal`
- `./build-native-image.sh`

We're using GraalVM master branch to test it.

It fails with:

```
[fresh-graal:79]    classlist:  10,224.38 ms
[fresh-graal:79]        (cap):   2,714.73 ms
[fresh-graal:79]        setup:   7,230.11 ms
Warning: class initialization of class io.micronaut.reactive.reactor.ReactorInstrumentation failed with exception java.lang.NoClassDefFoundError: reactor/core/scheduler/Schedulers$Factory. This class will be initialized at run time because either option --report-unsupported-elements-at-runtime or option --allow-incomplete-classpath is used for image building. Use the option --delay-class-initialization-to-runtime=io.micronaut.reactive.reactor.ReactorInstrumentation to explicitly request delayed initialization of this class.
[fresh-graal:79]     analysis:  57,107.90 ms
error: Error encountered while parsing io.micronaut.scheduling.io.watch.$MacOsWatchServiceFactory$MacWatchServiceDefinition.build(io.micronaut.context.BeanResolutionContext, io.micronaut.context.BeanContext, io.micronaut.inject.BeanDefinition) 
Parsing context:
	parsing io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1331)
	parsing io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2248)
	parsing io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2153)
	parsing io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:527)
	parsing io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:929)
	parsing io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:171)
	parsing io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:141)
	parsing io.micronaut.runtime.Micronaut.start(Micronaut.java:67)
	parsing io.micronaut.runtime.Micronaut.run(Micronaut.java:274)
	parsing io.micronaut.runtime.Micronaut.run(Micronaut.java:260)
	parsing fresh.graal.Application.main(Application.java:8)
	parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:164)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Original error: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at parsing io.micronaut.scheduling.io.watch.$MacOsWatchServiceFactory$MacWatchServiceDefinition.build(Unknown Source)
	at org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2424)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:88)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3178)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:2982)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:890)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:784)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:95)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:204)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:323)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:186)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:347)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:389)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:508)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:226)
	at sun.reflect.annotation.AnnotationParser.parseAnnotationArray(AnnotationParser.java:765)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:537)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.reflect.Executable.declaredAnnotations(Executable.java:599)
	at java.lang.reflect.Executable.getAnnotation(Executable.java:570)
	at java.lang.reflect.Method.getAnnotation(Method.java:622)
	at jdk.vm.ci.hotspot.HotSpotJDKReflection.getMethodAnnotation(HotSpotJDKReflection.java:203)
	at jdk.vm.ci.hotspot.HotSpotResolvedJavaMethodImpl.getAnnotation(HotSpotResolvedJavaMethodImpl.java:540)
	at com.oracle.svm.hosted.cenum.CEnumCallWrapperSubstitutionProcessor.lookup(CEnumCallWrapperSubstitutionProcessor.java:51)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:380)
	at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupMethod(WrappedConstantPool.java:112)
	at org.graalvm.compiler.java.BytecodeParser.lookupMethod(BytecodeParser.java:4018)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1506)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5004)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3173)
	... 23 more

Error: Image building with exit status 1
```

**Comment by ilopmar** [comment]
Thanks. I can confirm it works, our build already passed: https://gitlab.com/micronaut-projects/micronaut-graal-tests/pipelines/43802345
