### ISSUE TITLE
Incomplete classpath regression with rc11 on Spring Fu

### ISSUE THREAD

**Issue by sdeleuze** [oracle/graal#913]
I see in RC11 release notes that the incomplete classpath mechanism has been reworked, sadly it does not allow to compile Spring Fu basic sample where RC10 was fine.

To reproduce:

```
git clone https://github.com/spring-projects/spring-fu.git
./gradlew build publishToMavenLocal
cd samples/jafu-reactive-minimal
./build.sh

Build on Server(pid: 7215, port: 40671)*
[com.sample.application:7215]    classlist:   4,961.19 ms
[com.sample.application:7215]        (cap):     804.07 ms
[com.sample.application:7215]        setup:   1,847.28 ms
[com.sample.application:7215]     analysis:   1,235.47 ms
error: Error encountered while parsing org.springframework.boot.SpringApplication.createApplicationContext() 
Parsing context:
	parsing org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
	parsing org.springframework.fu.jafu.JafuApplication.run(JafuApplication.java:83)
	parsing org.springframework.fu.jafu.JafuApplication.run(JafuApplication.java:58)
	parsing com.sample.Application.main(Application.java:30)
	parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:164)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Original error: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.NoClassDefFoundError: javax/servlet/ServletContext
	at parsing org.springframework.boot.SpringApplication.createApplicationContext(SpringApplication.java:591)
	at org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2424)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:88)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3178)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:2982)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:890)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:784)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:95)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:204)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:323)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:186)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:347)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:389)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:508)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NoClassDefFoundError: javax/servlet/ServletContext
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at com.oracle.svm.hosted.ClassInitializationFeature.declaresDefaultMethods(ClassInitializationFeature.java:281)
	at com.oracle.svm.hosted.ClassInitializationFeature.processInterfaces(ClassInitializationFeature.java:327)
	at com.oracle.svm.hosted.ClassInitializationFeature.computeInitKindAndMaybeInitializeClass(ClassInitializationFeature.java:311)
	at com.oracle.svm.hosted.ClassInitializationFeature.computeInitKindAndMaybeInitializeClass(ClassInitializationFeature.java:291)
	at com.oracle.svm.hosted.ClassInitializationFeature.maybeInitializeHosted(ClassInitializationFeature.java:128)
	at com.oracle.svm.hosted.SVMHost.registerType(SVMHost.java:214)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:252)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:193)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:170)
	at com.oracle.graal.pointsto.meta.AnalysisType.convertTypes(AnalysisType.java:208)
	at com.oracle.graal.pointsto.meta.AnalysisType.<init>(AnalysisType.java:168)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:251)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:193)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:170)
	at com.oracle.graal.pointsto.meta.AnalysisType.getSuperclass(AnalysisType.java:758)
	at com.oracle.graal.pointsto.meta.AnalysisType.<init>(AnalysisType.java:167)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:251)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:193)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:170)
	at com.oracle.graal.pointsto.meta.AnalysisType.getSuperclass(AnalysisType.java:758)
	at com.oracle.graal.pointsto.meta.AnalysisType.<init>(AnalysisType.java:167)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:251)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:193)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:170)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:69)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaType0(UniverseMetaAccess.java:91)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaType(UniverseMetaAccess.java:82)
	at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaType(AnalysisMetaAccess.java:48)
	at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaType(AnalysisMetaAccess.java:40)
	at com.oracle.svm.hosted.snippets.ReflectionPlugins.processForName(ReflectionPlugins.java:187)
	at com.oracle.svm.hosted.snippets.ReflectionPlugins.access$000(ReflectionPlugins.java:61)
	at com.oracle.svm.hosted.snippets.ReflectionPlugins$1.apply(ReflectionPlugins.java:119)
	at org.graalvm.compiler.nodes.graphbuilderconf.InvocationPlugin.execute(InvocationPlugin.java:208)
	at org.graalvm.compiler.java.BytecodeParser.tryInvocationPlugin(BytecodeParser.java:2174)
	at com.oracle.svm.hosted.phases.AnalysisGraphBuilderPhase$AnalysisBytecodeParser.tryInvocationPlugin(AnalysisGraphBuilderPhase.java:68)
	at org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1705)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1464)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1444)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5002)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3173)
	... 23 more
Caused by: java.lang.ClassNotFoundException: javax.servlet.ServletContext
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 66 more

error: Error encountered while parsing org.springframework.boot.SpringApplication.getOrCreateEnvironment() 
Parsing context:
	parsing org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
	parsing org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	parsing org.springframework.fu.jafu.JafuApplication.run(JafuApplication.java:83)
	parsing org.springframework.fu.jafu.JafuApplication.run(JafuApplication.java:58)
	parsing com.sample.Application.main(Application.java:30)
	parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:164)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Original error: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.NoClassDefFoundError: javax/servlet/ServletContext
	at parsing org.springframework.boot.SpringApplication.getOrCreateEnvironment(SpringApplication.java:463)
	at org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2424)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:88)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3178)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:2982)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:890)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:784)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:95)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:204)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:323)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.flow.SpecialInvokeTypeFlow.onObservedUpdate(InvokeTypeFlow.java:421)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:347)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:389)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:508)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NoClassDefFoundError: javax/servlet/ServletContext
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at com.oracle.svm.hosted.ClassInitializationFeature.declaresDefaultMethods(ClassInitializationFeature.java:281)
	at com.oracle.svm.hosted.ClassInitializationFeature.processInterfaces(ClassInitializationFeature.java:327)
	at com.oracle.svm.hosted.ClassInitializationFeature.computeInitKindAndMaybeInitializeClass(ClassInitializationFeature.java:311)
	at com.oracle.svm.hosted.ClassInitializationFeature.computeInitKindAndMaybeInitializeClass(ClassInitializationFeature.java:291)
	at com.oracle.svm.hosted.ClassInitializationFeature.maybeInitializeHosted(ClassInitializationFeature.java:128)
	at com.oracle.svm.hosted.SVMHost.registerType(SVMHost.java:214)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:252)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:193)
	at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupType(WrappedConstantPool.java:151)
	at org.graalvm.compiler.java.BytecodeParser.lookupType(BytecodeParser.java:3975)
	at org.graalvm.compiler.java.BytecodeParser.genNewInstance(BytecodeParser.java:4218)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5005)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3173)
	... 23 more
Caused by: java.lang.ClassNotFoundException: javax.servlet.ServletContext
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
```

**Comment by pmlopes** [comment]
The same happens for `netty` applications which do not use the `netty-all` artifact but explicitly pick the needed artifacts.

**Comment by cstancu** [comment]
Thank you for your report. This should be fixed by https://github.com/oracle/graal/commit/dd0bae325265b9910281566a93f09ad42b4453a2. I will add SpringFu to our integration tests to avoid regressions in the future.

**Comment by sdeleuze** [comment]
Thanks!
