### ISSUE TITLE
Linkage error for Postgres driver using SSL

### ISSUE THREAD

**Issue by FroMage** [oracle/graal#919]
Even with SSL support enabled, I get the following exception using the postgres driver on a server which favours SSL connection upgrades:

```
Caused by: java.lang.UnsatisfiedLinkError: sun.security.ec.ECKeyPairGenerator.generateECKeyPair(I[B[B)[Ljava/lang/Object; [symbol: Java_sun_security_ec_ECKeyPairGenerator_generateECKeyPair or Java_sun_security_ec_ECKeyPairGenerator_generateECKeyPair__I_3B_3B]
    at java.lang.Throwable.<init>(Throwable.java:265)
    at java.lang.Error.<init>(Error.java:70)
    at java.lang.LinkageError.<init>(LinkageError.java:55)
    at java.lang.UnsatisfiedLinkError.<init>(UnsatisfiedLinkError.java:54)
    at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:125)
    at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:54)
    at sun.security.ec.ECKeyPairGenerator.generateECKeyPair(ECKeyPairGenerator.java)
    at sun.security.ec.ECKeyPairGenerator.generateKeyPair(ECKeyPairGenerator.java:128)
    at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:703)
    at sun.security.ssl.ECDHCrypt.<init>(ECDHCrypt.java:78)
    at sun.security.ssl.ClientHandshaker.serverKeyExchange(ClientHandshaker.java:783)
    at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:302)
    at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
    at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
    at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:40)
    at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:435)
    at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:94)
    at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
    at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
    at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
    at org.postgresql.Driver.makeConnection(Driver.java:454)
    at org.postgresql.Driver.connect(Driver.java:256)
```

**Comment by cstancu** [comment]
@FroMage do you provide `libsunec.so` at runtime as the [doc](https://github.com/oracle/graal/blob/master/substratevm/JCA-SECURITY-SERVICES.md#native-implementations) suggests?

**Comment by FroMage** [comment]
I'm pretty sure I do, because I got https clients to work, but perhaps something went wrong here. Do you think this is related? I thought it was due to an incomplete implementation.

**Comment by FroMage** [comment]
Sorry for the confusion, you were right, it was missing and it works if it's there.
