### ISSUE TITLE
Executable for JavaFX Modular CLI sample application built on Windows 11 with GraalVM 22.0.1+8.1 failed to run

### ISSUE THREAD

**Issue by alina-yur** [oracle/graal#9213]
### Discussed in https://github.com/oracle/graal/discussions/9166

<div type='discussions-op-text'>

<sup>Originally posted by **OlexYarm** June 23, 2024</sup>
I built executable (native image) on Windows 11 for JavaFX Modular CLI sample application with Oracle GraalVM 22.0.1+8.1 (build 22.0.1+8-jvmci-b01).
I failed to run with error below:
Exception in thread "main" java.lang.RuntimeException: java.lang.ClassNotFoundException: hellofx.HelloFX
        at javafx.graphics@22/javafx.application.Application.launch(Application.java:311)
        at hellofx/hellofx.HelloFX.main(HelloFX.java:23)
Caused by: java.lang.ClassNotFoundException: hellofx.HelloFX
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:143)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:106)
        at java.base@22.0.1/java.lang.Class.forName(DynamicHub.java:1387)
        at java.base@22.0.1/java.lang.Class.forName(DynamicHub.java:1377)
        at javafx.graphics@22/javafx.application.Application.launch(Application.java:299)
        ... 1 more

Step to reproduce
1. Install required software (Oracle GraalVM 22.0.1+8.1, OpenJFX 22 for Windows x64, Git 2.45.x, Git Desktop 2.50.x).
2. Open Windows Command Prompt
3. Clone JavaFX samples from GitHub (with Git or Git Desktop)
cd /
gh repo clone openjfx/samples
4. Build JavaFX Modular CLI sample application according to README.md
cd CommandLine\Modular\CLI\hellofx
set PATH_TO_FX="C:\openjfx-22_windows-x64_bin-sdk\javafx-sdk-22\lib"
dir /s /b src\*.java > sources.txt & javac --module-path %PATH_TO_FX% -d mods/hellofx @sources.txt & del sources.txt
5. Run sample application for testing
java --module-path "%PATH_TO_FX%;mods" -m hellofx/hellofx.HelloFX
5. Run sample with GraalVM agent for creating reflection, etc. config files
java -agentlib:native-image-agent=config-output-dir=native-image --module-path "%PATH_TO_FX%;mods" -m hellofx/hellofx.HelloFX
6. Build native image with native-image tool
native-image --verbose --native-image-info -H:+UnlockExperimentalVMOptions -H:+BuildReport -g --no-fallback --module-path "%PATH_TO_FX%;mods" -m hellofx/hellofx.HelloFX --class-path "mods" -o jfxHello
7. Run native image
jfxHello.exe
</div>

**Comment by selhagani** [comment]
Thank you for sharing this with us!

This issue is the same as [this one](https://github.com/oracle/graal/issues/7471) and it is tracked internally as GR-49845. Therefore I will be closing it since it is a duplicate.  You may follow up on updates in the original issue. 

Thank you
