### ISSUE TITLE
GraalError: failed guarantee: value too large to fit into space

### ISSUE THREAD

**Issue by LordTylus** [oracle/graal#9268]
**Describe the issue**
I am using Gluon Mobile which uses GraalVM to compile our mobile app to native. 

This worked fine so far until I tried compiling to arm64-ios today, which fails with the log below.

Compiling for x86_64-ios-simulator works just fine.

I notice my mac is very low on memory and a lot of time is spent swapping memory around, as it only has 16 GB in total.

Could this error be related to that?

**Steps to reproduce the issue**
Unfortunately I have no idea how to reproduce it without our original project, configuration and source code, which I am unfortunately not allowed to share. 

At this point in time I just don't know what the error means exactly and was hoping I could get a lead on where to look and how to further investigate.

**Describe GraalVM and your environment:**
 - GraalVM version: https://github.com/gluonhq/graal/releases/tag/gluon-22.1.0.1-Final
 - JDK major version: **17 (I am using GraalVM above as JDK)**
 - OS: **[e.g. macOS Ventura 13.6.7]**
 - Architecture: **x86 (runs on an intel-core-i5)**

**More details**
I do realize that Gluon forked GraalVM and that they are using an slightly outdated version of it. I, however, was told that they only made a change for compiling for android which likely shouldn't have an affect on iOS.

I have other Apps compiled for iOS using this very same version that work just fine.

Stacktrace:
```
[1/7] Initializing...                                                                                    (7,6s @ 0,22GB)
 Version info: 'GraalVM 22.1.0.1 Java 17 CE'
 Garbage collector: Serial GC
 2 user-provided feature(s)
  - com.oracle.svm.polyglot.kotlin.KotlinFeature
  - com.oracle.svm.thirdparty.gson.GsonFeature
[2/7] Performing analysis...  [**************]                                                         (365,7s @ 9,62GB)
  42.985 (96,49%) of 44.550 classes reachable
 102.877 (80,95%) of 127.085 fields reachable
 387.080 (85,19%) of 454.385 methods reachable
  16.695 classes, 55.189 fields, and 130.069 methods registered for reflection
     120 classes,   109 fields, and   199 methods registered for JNI access
[3/7] Building universe...                                                                              (77,1s @ 9,83GB)
GC warning: 60,5s spent in 9 GCs during the last stage, taking up 78,38% of the time.
            Please ensure more than 11,13GB of memory is available for Native Image
            to reduce GC overhead and improve image build time.
[4/7] Parsing methods...      [*****]                                                                   (30,5s @ 9,31GB)
GC warning: 20,1s spent in 6 GCs during the last stage, taking up 63,92% of the time.
            Please ensure more than 11,13GB of memory is available for Native Image
            to reduce GC overhead and improve image build time.
[5/7] Inlining methods...     [*****]                                                                   (37,1s @ 8,52GB)
GC warning: 23,7s spent in 19 GCs during the last stage, taking up 60,53% of the time.
            Please ensure more than 11,13GB of memory is available for Native Image
            to reduce GC overhead and improve image build time.
[6/7] Compiling methods...    [***********]                                                           (120,6s @ 10,52GB)

[7/7] Creating image...                                                                                  (0,0s @ 5,85GB)
Fatal error: com.oracle.svm.core.util.VMError$HostedError: org.graalvm.compiler.debug.GraalError: failed guarantee: value too large to fit into space
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:72)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:678)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:515)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:615)
Caused by: org.graalvm.compiler.debug.GraalError: failed guarantee: value too large to fit into space
	at jdk.internal.vm.compiler/org.graalvm.compiler.debug.GraalError.guarantee(GraalError.java:73)
	at jdk.internal.vm.compiler/org.graalvm.compiler.asm.aarch64.AArch64Assembler$SingleInstructionAnnotation.patch(AArch64Assembler.java:3320)
	at com.oracle.svm.hosted.code.aarch64.SingleInstructionHostedPatcher.patch(AArch64HostedPatcher.java:101)
	at com.oracle.svm.hosted.image.LIRNativeImageCodeCache.patchMethods(LIRNativeImageCodeCache.java:194)
	at com.oracle.svm.hosted.image.NativeImage$NativeTextSectionImpl.writeTextSection(NativeImage.java:965)
	at com.oracle.svm.hosted.image.NativeImage.build(NativeImage.java:457)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:666)
	... 5 more
------------------------------------------------------------------------------------------------------------------------
                      272,7s (39,1% of total time) in 283 GCs | Peak RSS: 11,13GB | CPU load: 3,90
========================================================================================================================
```

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reaching out. I believe this issue should be reported to https://github.com/gluonhq/substrate/issues
