### ISSUE TITLE
Unable to use javascript with Ruby

### ISSUE THREAD

**Issue by zaknuces** [oracle/graal#939]
I am trying to create an example of Ruby and Javascript interoperability. However, I am getting the following error when running a JSON parse example (https://www.graalvm.org/docs/reference-manual/languages/ruby/#interoperability) 

This is the error
```
test-polyglot.rb:5:in `eval': No language for id js found. Supported languages are: [native, nfi, llvm, ruby] (IllegalStateException) (RuntimeError)
	from com.oracle.truffle.polyglot.PolyglotEngineImpl.findLanguage(PolyglotEngineImpl.java:449)
	from com.oracle.truffle.polyglot.PolyglotImpl$EngineImpl.parseForLanguage(PolyglotImpl.java:473)
	from com.oracle.truffle.api.TruffleLanguage$Env.parse(TruffleLanguage.java:1786)
	from org.truffleruby.interop.PolyglotNodes$EvalNode.parse(PolyglotNodes.java:72)
	from org.truffleruby.interop.PolyglotNodesFactory$EvalNodeFactory$EvalNodeGen.executeAndSpecialize(PolyglotNodesFactory.java:164)
	from org.truffleruby.interop.PolyglotNodesFactory$EvalNodeFactory$EvalNodeGen.execute(PolyglotNodesFactory.java:124)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:34)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:51)
	from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:54)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:275)
Translated to internal error
	from test-polyglot.rb:5:in `<main>'
```

Command `ruby --polyglot --jvm test-polyglot.rb`

I am running this in a docker container based on oracle/graalvm-ce:1.0.0-rc11

**Comment by eregon** [comment]
Hello,
Thank you for the report.
I tried to reproduce, but it works fine for me when using this Dockerfile:
```dockerfile
FROM oracle/graalvm-ce:1.0.0-rc11
RUN gu install ruby
# Works
RUN ruby --polyglot --jvm -e 'Polyglot.eval("js", "print(1 << 86)")'
# Fails, as expected as there is no --polyglot or --jvm argument
RUN ruby -e 'Polyglot.eval("js", "print(1 << 86)")'
```

and the output is:
```
$ docker build --no-cache .
Step 1/4 : FROM oracle/graalvm-ce:1.0.0-rc11
 ---> edfc03b14bf6

Step 2/4 : RUN gu install ruby
 ---> Running in 14cebe66ce8b
Downloading: Component catalog
Processing component archive: Component ruby
Downloading: Component ruby
Installing new component: TruffleRuby (org.graalvm.ruby, version 1.0.0-rc11)

IMPORTANT NOTE:
---------------
The Ruby openssl C extension needs to be recompiled on your system to work with the installed libssl.
First, make sure TruffleRuby's dependencies are installed, which are described at:
  https://github.com/oracle/truffleruby/blob/master/README.md#dependencies
Then run the following command:
        /opt/graalvm-ce-1.0.0-rc11/jre/languages/ruby/lib/truffle/post_install_hook.sh


IMPORTANT NOTE:
---------------
Set of Graal VM components that provide language implementations have changed. The Polyglot native image and polyglot native C library may be out of sync: 
- new languages may not be accessible
- removed languages may cause the native binary to fail on missing resources or libraries.
To rebuild and refresh the native binaries, use the following command:
        /opt/graalvm-ce-1.0.0-rc11/jre/bin/gu rebuild-images


Refreshed alternative links in /usr/bin/
 ---> 0ffbd71b5e96
Removing intermediate container 14cebe66ce8b

Step 3/4 : RUN ruby --polyglot --jvm -e 'Polyglot.eval("js", "print(1 << 86)")'
 ---> Running in 1821841a57a1
4194304
 ---> 81dc8096d1da
Removing intermediate container 1821841a57a1

Step 4/4 : RUN ruby -e 'Polyglot.eval("js", "print(1 << 86)")'
 ---> Running in f6ac2e258c28
-e:1:in `eval': No language for id js found. Supported languages are: [native, nfi, llvm, ruby] (IllegalStateException) (RuntimeError)
	from com.oracle.truffle.polyglot.PolyglotEngineImpl.findLanguage(PolyglotEngineImpl.java:449)
	from com.oracle.truffle.polyglot.PolyglotImpl$EngineImpl.parseForLanguage(PolyglotImpl.java:473)
	from com.oracle.truffle.api.TruffleLanguage$Env.parse(TruffleLanguage.java:1786)
	from org.truffleruby.interop.PolyglotNodes$EvalNode.parse(PolyglotNodes.java:72)
	from org.truffleruby.interop.PolyglotNodesFactory$EvalNodeFactory$EvalNodeGen.executeAndSpecialize(PolyglotNodesFactory.java:164)
	from org.truffleruby.interop.PolyglotNodesFactory$EvalNodeFactory$EvalNodeGen.execute(PolyglotNodesFactory.java:124)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:34)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:51)
	from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:54)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:275)
Translated to internal error
	from -e:1:in `<main>'
The command '/bin/sh -c ruby -e 'Polyglot.eval("js", "print(1 << 86)")'' returned a non-zero code: 1
```


Can you make sure you actually pass `--jvm` to the Ruby process?

Maybe the ruby process spawns a subprocess?
In such a case, it's possible to always pass `--jvm` for all ruby processes by setting `TRUFFLERUBYOPT=--jvm` in the environment.

If you want to use `--polyglot` in `--native` mode (not `--jvm`), then the polyglot native image needs to be recompiled with `gu rebuild-images polyglot` first.

**Comment by zaknuces** [comment]
Thanks @eregon . Using TRUFFLERUBYOPT worked for me. I am spawning the child process and that explains why it was not working.
Thanks alot

**Comment by eregon** [comment]
@zaknuces Thank you for confirming. I'll close this issue then.
