### ISSUE TITLE
native-image-configure tool is throwing a ClassCastException on latest Oracle EA Build

### ISSUE THREAD

**Issue by thejudge156** [oracle/graal#9452]
**Describe the issue**
While trying to run the configure tool with the latest EA build, a ClassCastException is thrown if any reachability metadata input is in the command.

**Steps to reproduce the issue**
1. Try running the configure tool with the attached metadata

**Describe GraalVM and your environment:**
 - GraalVM version: [jdk-24.0.0-ea.06](https://github.com/graalvm/oracle-graalvm-ea-builds/tree/jdk-24.0.0-ea.06)
 - JDK major version: Java 24
 - OS: Windows 11
 - Architecture: AMD64

**More details**
File attached here:
[reachability-metadata.json](https://github.com/user-attachments/files/16488416/reachability-metadata.json)

```
    java.lang.ClassCastException: class org.graalvm.collections.EconomicMapImpl cannot be cast to class java.util.List (org.graalvm.collections.EconomicMapImpl is in module org.graalvm.collections of loader 'app'; java.util.List is in module java.base of loader 'bootstrap')
        at org.graalvm.nativeimage.configure/com.oracle.svm.configure.trace.TraceProcessor.process(TraceProcessor.java:59)
        at org.graalvm.nativeimage.configure/com.oracle.svm.configure.command.ConfigurationGenerateCommand.generate(ConfigurationGenerateCommand.java:297)
        at org.graalvm.nativeimage.configure/com.oracle.svm.configure.command.ConfigurationGenerateCommand.apply(ConfigurationGenerateCommand.java:60)
        at org.graalvm.nativeimage.configure/com.oracle.svm.configure.ConfigurationTool.main(ConfigurationTool.java:84)
        at org.graalvm.nativeimage.enterprise.configure/com.oracle.svm.enterprise.configure.ConfigurationEnterpriseTool.main(ConfigurationEnterpriseTool.java:24)
```

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reaching out about this issue. could you please share a reproducer with the exact steps you take to recreate the issue? Thank you

**Comment by thejudge156** [comment]
Will do soon

**Comment by vjovanov** [comment]
I have a problem reproducing this on the latest release branch. I used this command:
```bash
$ native-image-configure generate --input-dir=/home/vjovanov/Downloads --output-dir=/tmp/
```

**Comment by vjovanov** [comment]
Was this happening with the gradle or maven plugin?

**Comment by vjovanov** [comment]
@thejudge156 we would like to fix this issue this week. However, to do this we would need to have the reproducer ready.

**Comment by thejudge156** [comment]
Howdy, apologies for the Radio silence. 

This issue appears to be fixed in new EA builds.
