### ISSUE TITLE
java.lang.NoClassDefFoundError with allow-incomplete-classpath and without -H:-UseServiceLoaderFeature

### ISSUE THREAD

**Issue by ilopmar** [oracle/graal#947]
I've found a `java.lang.NoClassDefFoundError: com/netflix/hystrix/strategy/concurrency/HystrixConcurrencyStrategy` when building a Micronaut native image.

To reproduce the issue:
- `git clone https://github.com/micronaut-graal-tests/micronaut-zipkin-graal`
- `cd micronaut-zipkin-graal`
- `git checkout graal-rc13-dev`
- Use GraalVM rc13-dev
- `./build-native-image.sh`

Please keep in mind that I'm not using `-H:-UseServiceLoaderFeature` and I'm using `--allow-incomplete-classpath`.

The error is because of this class https://github.com/micronaut-projects/micronaut-core/blob/master/tracing/src/main/java/io/micronaut/tracing/instrument/hystrix/TracingHystrixConcurrentStrategy.java references `HystrixConcurrencyStrategy`, but it should not attempt to load that because of 
https://github.com/micronaut-projects/micronaut-core/blob/master/tracing/src/main/java/io/micronaut/tracing/instrument/hystrix/TracingHystrixConcurrentStrategy.java#L45.

I think this is a bug because the class should not be loaded (because the `@Requires` is not satisfied) and `--allow-incomplete-classpath` should allow that to work.

The error is:
```
[zipkin-graal:15913]    classlist:  10,454.53 ms
[zipkin-graal:15913]        (cap):   1,682.29 ms
[zipkin-graal:15913]        setup:   5,013.96 ms
Warning: class initialization of class io.micronaut.reactive.reactor.ReactorInstrumentation failed with exception java.lang.NoClassDefFoundError: reactor/core/scheduler/Schedulers$Factory. This class will be initialized at run time because either option --report-unsupported-elements-at-runtime or option --allow-incomplete-classpath is used for image building. Use the option --delay-class-initialization-to-runtime=io.micronaut.reactive.reactor.ReactorInstrumentation to explicitly request delayed initialization of this class.
Warning: class initialization of class io.micronaut.tracing.instrument.rxjava.RxJava1TracingInstrumentation failed with exception java.lang.NoClassDefFoundError: rx/functions/Func1. This class will be initialized at run time because either option --report-unsupported-elements-at-runtime or option --allow-incomplete-classpath is used for image building. Use the option --delay-class-initialization-to-runtime=io.micronaut.tracing.instrument.rxjava.RxJava1TracingInstrumentation to explicitly request delayed initialization of this class.
[zipkin-graal:15913]     analysis:  37,020.59 ms
Fatal error: java.lang.NoClassDefFoundError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:427)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:285)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:407)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:106)
Caused by: java.lang.NoClassDefFoundError: com/netflix/hystrix/strategy/concurrency/HystrixConcurrencyStrategy
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.repository.ClassRepository.getSuperInterfaces(ClassRepository.java:108)
	at java.lang.Class.getGenericInterfaces(Class.java:913)
	at com.oracle.svm.hosted.analysis.Inflation.fillGenericInfo(Inflation.java:302)
	at com.oracle.svm.hosted.analysis.Inflation.checkType(Inflation.java:146)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at com.oracle.svm.hosted.analysis.Inflation.checkObjectGraph(Inflation.java:132)
	at com.oracle.graal.pointsto.BigBang.checkObjectGraph(BigBang.java:597)
	at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:555)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:648)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:492)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:410)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: com.netflix.hystrix.strategy.concurrency.HystrixConcurrencyStrategy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 36 more
Error: Image building with exit status 1
```

**Comment by cstancu** [comment]
Thanks for the detailed report! I'll look into it.

**Comment by cstancu** [comment]
Fixed in https://github.com/oracle/graal/commit/f64799e805e69f8974e4a466ddec80ba3e3ca6c4. With these changes I can successfully build and run the image for your example app.

The problem is that we rely on the JDK mechanism to parse and build generics and annotations metadata and that mechanism will throw when classes are missing. We were already catching `MalformedParameterizedTypeException` and `TypeNotPresentException` that have observed before in such situations however it seems that a `ClassNotFoundError` can also slip through. `sun.reflect.generics.factory.CoreReflectionFactory` catches all the `ClassNotFoundException` and wrapps them in `TypeNotPresentException`:

```
public Type makeNamedType(String name){
    try {return Class.forName(name, false, // don't initialize
                              getDeclsLoader());}
    catch (ClassNotFoundException c) {
            throw new TypeNotPresentException(name, c);
    }
}
```
, however it looks like `Class.forName` doesn't always pack `ClassNotFoundError`s in `ClassNotFoundException`s.

**Comment by ilopmar** [comment]
That was fast, thank you very much for the quick fix, I can confirm it works! :clap:
