### ISSUE TITLE
[native-image] instantiating javax.script.ScriptEngineManager crashes the compiler

### ISSUE THREAD

**Issue by evacchi** [oracle/graal#958]
reproducer:

```sh
native-image ex.Example
```

```java
package ex;
import javax.script.*;
import java.util.*;
public class Example {
    public static void main(String... args) {
        ScriptEngineManager manager = new ScriptEngineManager();
    }
}
```
this WILL complete successfully if we pass (e.g.) `--language:js` to `native-image`:

```sh
native-image --language:js ex.Example
```
but compilation will take a lot more time.

bonus: using `--language:js` and by changing the main above as follows:

```java
        ScriptEngineManager manager = new ScriptEngineManager();
        List<ScriptEngineFactory> factories = manager.getEngineFactories();
        for (ScriptEngineFactory factory : factories) {
            System.out.println(factory);
        }
```

all the factory ids get printed as expected 

```sh
% ./ex.example                                                         
jdk.nashorn.api.scripting.NashornScriptEngineFactory@7fcb5e318a00
com.oracle.truffle.js.scriptengine.GraalJSEngineFactory@7fcb5e318868
```

**Comment by cstancu** [comment]
In what way does the compiler crash? I cannot replicate any problem with your example code and latest GraalVM master:
```
$ cat Example.java 
import javax.script.*;
import java.util.*; 
public class Example { 
	public static void main(String... args) { 
 		ScriptEngineManager manager = new ScriptEngineManager(); 
 		List<ScriptEngineFactory> factories = manager.getEngineFactories(); 
 		for (ScriptEngineFactory factory : factories) { 
 			System.out.println(factory); 
 		}	
 	} 
}
$ javac Example.java 
$ java Example 
jdk.nashorn.api.scripting.NashornScriptEngineFactory@3d4eac69
$ native-image Example
Build on Server(pid: 4791, port: 42753)
[example:4791]    classlist:     237.26 ms
[example:4791]        (cap):     548.47 ms
[example:4791]        setup:     878.17 ms
[example:4791]   (typeflow):   4,209.68 ms
[example:4791]    (objects):   2,622.33 ms
[example:4791]   (features):      94.63 ms
[example:4791]     analysis:   6,997.53 ms
[example:4791]     universe:     120.64 ms
[example:4791]      (parse):     412.91 ms
[example:4791]     (inline):     522.66 ms
[example:4791]    (compile):   3,582.46 ms
[example:4791]      compile:   4,761.02 ms
[example:4791]        image:     596.30 ms
[example:4791]        write:     158.50 ms
[example:4791]      [total]:  13,804.43 ms
$ ./example 
jdk.nashorn.api.scripting.NashornScriptEngineFactory@7fecd2b076d0
$ native-image --version
GraalVM Version 1.0.0-rc13-dev

```

**Comment by evacchi** [comment]
that is great news!

this is happening on rc11, here's the trace https://gist.github.com/evacchi/a575945e5de30c3e8b53dcd2885287b5

is a nightly build available somewhere public?

**Comment by cstancu** [comment]
I can see the error in rc12 too. There is no nightly build, but you can [build a GraalVM distribution from source](https://github.com/oracle/graal/tree/master/vm#vm-suite).

**Comment by evacchi** [comment]
Unfortunately I can still reproduce this with master build

```java
package ex;
import javax.script.*;
import java.util.*;
public class Example {
    // static volatile Long l = System.nanoTime();
    public static void main(String... args) {
        System.out.println(System.getProperty("org.graalvm.nativeimage.imagecode"));
        System.out.println(System.getProperty("java.vm.name"));
        System.out.println(System.getProperty("java.home"));
        System.out.println(System.getProperty("java.vendor"));
        System.out.println(System.getProperty("java.version"));
        System.out.println(System.getProperty("java.specification.vendor"));

        ScriptEngineManager manager = new ScriptEngineManager();
        List<ScriptEngineFactory> factories = manager.getEngineFactories();
        for (ScriptEngineFactory factory : factories) {
            System.out.println(factory);
        }
    }
}
```

with `java` prints:

```
null
GraalVM 1.0.0-rc13-dev
/home/evacchi/Devel/graal/graal/vm/mxbuild/linux-amd64/GRAALVM_CE/graalvm-ce-1.0.0-rc13-dev/jre
Oracle Corporation
1.8.0_192
Oracle Corporation
com.oracle.truffle.js.scriptengine.GraalJSEngineFactory@3d646c37
jdk.nashorn.api.scripting.NashornScriptEngineFactory@2ef1e4fa
```

with `native-image`:

```
$GRAALVM_HOME/bin/native-image ex.Example
Build on Server(pid: 8312, port: 37681)
[ex.example:8312]    classlist:   2,704.52 ms
[ex.example:8312]        (cap):   1,146.17 ms
[ex.example:8312]        setup:   1,806.19 ms
[ex.example:8312]     analysis:  10,275.05 ms
Error: Error encountered while parsing com.oracle.svm.core.deopt.DeoptimizationSupport.get() 
Parsing context:
	parsing com.oracle.svm.core.deopt.DeoptimizationSupport.getDeoptStubPointer(DeoptimizationSupport.java:71)
	parsing com.oracle.svm.core.deopt.Deoptimizer.<init>(Deoptimizer.java:424)
	parsing com.oracle.svm.core.stack.SubstrateInspectedFrame.getDeoptimizer(SubstrateStackIntrospection.java:205)
	parsing com.oracle.svm.core.stack.SubstrateInspectedFrame.getLocalConstant(SubstrateStackIntrospection.java:235)
	parsing com.oracle.svm.core.stack.SubstrateInspectedFrame.toString(SubstrateStackIntrospection.java:362)
	parsing java.util.Formatter$FormatSpecifier.printString(Formatter.java:2886)
	parsing java.util.Formatter$FormatSpecifier.print(Formatter.java:2763)
	parsing java.util.Formatter.format(Formatter.java:2508)
	parsing java.util.Formatter.format(Formatter.java:2455)
	parsing com.oracle.truffle.polyglot.OptionValuesImpl.failNotFound(OptionValuesImpl.java:214)
	parsing com.oracle.truffle.polyglot.PolyglotEngineImpl.parseOptions(PolyglotEngineImpl.java:378)
	parsing com.oracle.truffle.polyglot.PolyglotEngineImpl.patch(PolyglotEngineImpl.java:265)
	parsing com.oracle.truffle.polyglot.PolyglotImpl.buildEngine(PolyglotImpl.java:191)
	parsing org.graalvm.polyglot.Engine$Builder.build(Engine.java:488)
	parsing org.graalvm.polyglot.Engine.create(Engine.java:237)
	parsing com.oracle.truffle.js.scriptengine.GraalJSEngineFactory.<init>(GraalJSEngineFactory.java:95)
	parsing com.oracle.svm.reflect.GraalJSEngineFactory_constructor_192419c5841f18e8d6ae4a824acf7e9c596c4b3f_13.newInstance(Unknown Source)
	parsing java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	parsing com.oracle.svm.core.hub.DynamicHub.newInstance(DynamicHub.java:658)
	parsing java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	parsing java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	parsing java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	parsing javax.script.ScriptEngineManager.initEngines(ScriptEngineManager.java:122)
	parsing javax.script.ScriptEngineManager.init(ScriptEngineManager.java:84)
	parsing javax.script.ScriptEngineManager.<init>(ScriptEngineManager.java:61)
	parsing ex.Example.main(Example.java:24)
	parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:152)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Original error: com.oracle.svm.core.util.UserError$UserException: ImageSingletons do not contain key com.oracle.svm.core.deopt.DeoptimizationSupport
	at com.oracle.svm.core.util.UserError.abort(UserError.java:67)
	at com.oracle.svm.hosted.ImageSingletonsSupportImpl$HostedManagement.doLookup(ImageSingletonsSupportImpl.java:110)
	at com.oracle.svm.hosted.ImageSingletonsSupportImpl.lookup(ImageSingletonsSupportImpl.java:44)
	at org.graalvm.nativeimage.ImageSingletons.lookup(ImageSingletons.java:85)
	at com.oracle.svm.hosted.snippets.SubstrateGraphBuilderPlugins$44.apply(SubstrateGraphBuilderPlugins.java:826)
	at org.graalvm.compiler.nodes.graphbuilderconf.InvocationPlugin.execute(InvocationPlugin.java:208)
	at org.graalvm.compiler.java.BytecodeParser.tryInvocationPlugin(BytecodeParser.java:2185)
	at com.oracle.svm.hosted.phases.AnalysisGraphBuilderPhase$AnalysisBytecodeParser.tryInvocationPlugin(AnalysisGraphBuilderPhase.java:71)
	at org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1717)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1476)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1456)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5020)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3184)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:2993)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:891)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:785)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:95)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:214)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:333)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:346)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:508)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Processing image build request failed
```

**Comment by evacchi** [comment]
oh but interestingly enough, my build comes with graaljs, while yours does not.

mine: 
```java
com.oracle.truffle.js.scriptengine.GraalJSEngineFactory@3d646c37
jdk.nashorn.api.scripting.NashornScriptEngineFactory@2ef1e4fa
```
yours:
```
jdk.nashorn.api.scripting.NashornScriptEngineFactory@7fecd2b076d0
```

which is consistent with the trace:

```
	parsing com.oracle.truffle.js.scriptengine.GraalJSEngineFactory.<init>(GraalJSEngineFactory.java:95)
```

shall I report this to `graal/graaljs` ?

**Comment by cstancu** [comment]
I don't think disabling `grral/graaljs` would fix the problem. It seems that we have a problem when Truffle is reachable and neither `--tool:truffle` nor a `--language:xxx` is added because then the HotSpot runtime might get pulled in. (Truffle code becomes reachable due to `ScriptEngineManager`.) Instead you should try adding `--language:js` to make sure you have a default Truffle runtime. One solution that we could implement to avoid this problem in the future would be to have `native-image` select a default Truffle runtime, which can then be overwritten when Truffle is explicitly activated.

What do you use `ScriptEngineManager` for? You should know that Nashorn doesn't work with `native-image` since `native-image` must see all bytecodes AOT.

Also, I built GraalVM from source above using: `mx --dynamicimports /substratevm-enterprise --disable-polyglot --disable-libpolyglot build`. This only builds the `native-image` tool and it might make a difference in how it is packed. @olpaw should know more.

**Comment by evacchi** [comment]
> What do you use `ScriptEngineManager` for? You should know that Nashorn doesn't work with `native-image` since `native-image` must see all bytecodes AOT.

actually, right now for *nothing*. The code I have at hand invokes

```
        ScriptEngineManager manager = new ScriptEngineManager();
        List<ScriptEngineFactory> factories = manager.getEngineFactories();
``` 

then it iterates over the factories but never really use them (it's an existing code base), so I was wondering why it broke. `--language:js` does work although it increases compile team considerably. Not a blocker to me, I have already added a conditional to skip creating `ScriptEngineManager` since it is not (currently) used anyway. Just thought I should report it. 

If the feature is not supported when no `--language` is provided I'd expect either  `manager.getEngineFactories()` to return an empty list or to raise an `UnsupportedOperationException()` (or something like that).

**Comment by olpaw** [comment]
We have merged https://github.com/oracle/graal/commit/c1eee6009af5796abecbdbeb6ba6576025a0f540 to master

With this change your example can be built into a native-image with the same arguments you would run it with java. I.e. building:
```
package ex;
import javax.script.*;
import java.util.*;
public class Example {
    // static volatile Long l = System.nanoTime();
    public static void main(String... args) {
        System.out.println(System.getProperty("org.graalvm.nativeimage.imagecode"));
        System.out.println(System.getProperty("java.vm.name"));
        System.out.println(System.getProperty("java.home"));
        System.out.println(System.getProperty("java.vendor"));
        System.out.println(System.getProperty("java.version"));
        System.out.println(System.getProperty("java.specification.vendor"));

        ScriptEngineManager manager = new ScriptEngineManager();
        List<ScriptEngineFactory> factories = manager.getEngineFactories();
        for (ScriptEngineFactory factory : factories) {
            System.out.println(factory);
        }
    }
}
```
with graalvm now works as expected. Running on java with:
```
> bin/java -cp $HOME/OLabs/test ex.Example
null
GraalVM 1.0.0-rc13-dev
/home/pwoegere/OLabs/git/GR-13748/graal/vm/mxbuild/linux-amd64/GRAALVM_BJS_BLLI_CMP_GU_GVM_INS_JS_NJS_POLYNATIVE_PRO_RGX_SLG_SVM_TFL_VVM/graalvm-bjs-blli-cmp-gu-gvm-ins-js-njs-polynative-pro-rgx-slg-svm-tfl-vvm-1.0.0-rc13-dev/jre
Oracle Corporation
1.8.0_192
Oracle Corporation
jdk.nashorn.api.scripting.NashornScriptEngineFactory@27fa135a
com.oracle.truffle.js.scriptengine.GraalJSEngineFactory@306a30c7
```
vs. building an image with:
```
> bin/native-image -cp $HOME/OLabs/test ex.Example
Build on Server(pid: 3799, port: 37143)
[ex.example:3799]    classlist:     167.91 ms
...
[ex.example:3799]      [total]:  24,094.73 ms

> ./ex.example 
runtime
Substrate VM
null
Oracle Corporation
1.8.0_192
Oracle Corporation
com.oracle.truffle.js.scriptengine.GraalJSEngineFactory@7fe734b0ac88
jdk.nashorn.api.scripting.NashornScriptEngineFactory@7fe734b0ae20
```

**Comment by olpaw** [comment]
Note that if you want an image that is able to perform partial evaluation you still need the `--tool:truffle` option (or a `Requires = tool:truffle`) in your `native-image.properties` file.

**Comment by evacchi** [comment]
Thanks, that's great!
