### ISSUE TITLE
[GR-57845] Java/Espresso Support: EspressoFinalReference NoSuchMethodError

### ISSUE THREAD

**Issue by Weaxs** [oracle/graal#9599]
**Describe GraalVM and your environment :**
 - GraalVM version or commit id if built from source: **[e.g. 19.3]**
 - CE or EE:  CE
 - JDK version: OpenJDK 17.0.10
 - OS and OS Version: macOS
 - Architecture: arm
 - The output of `java -Xinternalversion`:

**Have you verified this issue still happens when using the latest snapshot?**
You can find snapshot builds here: https://github.com/graalvm/graalvm-ce-dev-builds/releases

**Describe the issue**

A error has occurred `Caused by: java.lang.NoSuchMethodError: 'void com.oracle.truffle.espresso.ref.EspressoFinalReference.<init>(com.oracle.truffle.espresso.runtime.staticobject.StaticObject, com.oracle.truffle.espresso.runtime.staticobject.StaticObject, java.lang.ref.ReferenceQueue)'
` where I execute script by `java` language.

**Code snippet or code repository that reproduces the issue**
maven dependicy

```
        <dependency>
            <groupId>org.graalvm.sdk</groupId>
            <artifactId>graal-sdk</artifactId>
            <version>${graalvm.version}</version>
        </dependency>
        <dependency>
            <groupId>org.graalvm.truffle</groupId>
            <artifactId>truffle-api</artifactId>
            <version>${graalvm.version}</version>
        </dependency>
        <dependency>
            <groupId>org.graalvm.polyglot</groupId>
            <artifactId>polyglot</artifactId>
            <version>${graalvm.version}</version>
        </dependency>
        <dependency>
            <groupId>org.graalvm.polyglot</groupId>
            <artifactId>js-community</artifactId>
            <version>${graalvm.version}</version>
            <type>pom</type>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.graalvm.polyglot</groupId>
            <artifactId>python-community</artifactId>
            <version>${graalvm.version}</version>
            <type>pom</type>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.graalvm.polyglot</groupId>
            <artifactId>java-community</artifactId>
            <version>${graalvm.version}</version>
            <type>pom</type>
        </dependency>
```

code: 

```
private static final String java_script = """
  public class Main {
    public ObjectNode main(ObjectNode state) {
        state.put("aaa", 3);
        state.put("bbb", "hi");
        return state;
      }
  }
""";

private static void script(String script, String language) {
        ObjectNode params = JsonNodeFactory.instance.objectNode();
        Source source = Source.create(language, script);
        HostAccess hostAccess = HostAccess.newBuilder(HostAccess.ALL)
                .build();
        Context.Builder ctxBuilder = Context.newBuilder("js", "python", "java")
                .allowHostAccess(hostAccess).allowNativeAccess(true)
                .allowExperimentalOptions(true)
                .option("js.ecmascript-version", "11")
                .option("js.foreign-object-prototype", "true")
                .option("js.foreign-object-prototype", "true")
                .option("js.console", "true")
                .option("js.print", "true")
                .option("js.unhandled-rejections", "throw")
                .option("js.async-context", "true")
                .option("python.ForceImportSite", "true")
                .option("java.UseHostFinalReference", "true")
                .allowAllAccess(true)
                .allowIO(IOAccess.ALL)
                .engine(Engine.create());

        try (Context context = ctxBuilder.build()) {
            Object obj = JsScriptUtil.covertObject(params);
            context.eval(source);
            Value jsFunc = context.getBindings(language).getMember("main");
            Object result = jsFunc.execute(obj).as(Object.class);
            System.out.println(result);
        }
    }

```

the error occurred:

```
Exception in thread "main" org.graalvm.polyglot.PolyglotException: com.oracle.truffle.espresso.meta.EspressoError: should not reach here: Error injecting while injecting classes to support finalization in the host (version 17)
	at com.oracle.truffle.espresso.meta.EspressoError.shouldNotReachHere(EspressoError.java:73)
	at com.oracle.truffle.espresso.ref.FinalizationSupport.<clinit>(FinalizationSupport.java:72)
	at com.oracle.truffle.espresso.runtime.EspressoEnv.<init>(EspressoEnv.java:139)
	at com.oracle.truffle.espresso.runtime.EspressoContext.<init>(EspressoContext.java:213)
	at com.oracle.truffle.espresso.EspressoLanguage.createContext(EspressoLanguage.java:192)
	at com.oracle.truffle.espresso.EspressoLanguage.createContext(EspressoLanguage.java:85)
	at com.oracle.truffle.api.LanguageAccessor$LanguageImpl.createEnvContext(LanguageAccessor.java:270)
	at com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureCreated(PolyglotLanguageContext.java:652)
	at com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureInitialized(PolyglotLanguageContext.java:731)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:1681)
	at com.oracle.truffle.polyglot.PolyglotContextDispatch.eval(PolyglotContextDispatch.java:60)
	at org.graalvm.polyglot.Context.eval(Context.java:402)
	at aaaaaa.ScriptTest.script(ScriptTest.java:138)
	at aaaaaa.ScriptTest.main(ScriptTest.java:51)
	Suppressed: Attached Guest Language Frames (0)
Caused by: java.lang.NoSuchMethodException: no such constructor: com.oracle.truffle.espresso.ref.EspressoFinalReference.<init>(StaticObject,StaticObject,ReferenceQueue)void/newInvokeSpecial
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:974)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1117)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3649)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:2750)
	at com.oracle.truffle.espresso.ref.FinalizationSupport.<clinit>(FinalizationSupport.java:69)
	... 12 more
Caused by: java.lang.NoSuchMethodError: 'void com.oracle.truffle.espresso.ref.EspressoFinalReference.<init>(com.oracle.truffle.espresso.runtime.staticobject.StaticObject, com.oracle.truffle.espresso.runtime.staticobject.StaticObject, java.lang.ref.ReferenceQueue)'
	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1085)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1114)
	... 15 more
Internal GraalVM error, please report at https://github.com/oracle/graal/issues/.
```

**Expected behavior**
execute success.

**Additional context**
https://github.com/oracle/graal/blob/master/espresso/src/com.oracle.truffle.espresso/src/com/oracle/truffle/espresso/ref/ClassAssembler.java
![8404a75e511c08b23a60d311219a0e38](https://github.com/user-attachments/assets/17bc8640-7c74-499f-8154-df4441b5915a)

**Comment by gilles-duboscq** [comment]
The fix was merged in #9662
