### ISSUE TITLE
[native-image] Runtime error when using java.lang.reflect.Array in library

### ISSUE THREAD

**Issue by tomgelu** [oracle/graal#9603]
# Describe the issue
Native application throws com.oracle.svm.core.jdk.UnsupportedFeatureError in runtime, while using java.lang.reflect.Array to generate a new instance of an object encapsulated in a generic. Adding a type hint did not solve the issue.

The error is observed only when such operation is inside a dependency. Extracting the code from the library and putting it into the application being compiled, seem to trigger a proper reflection autoconfiguration.

It would be interesting to understand how that specific reflection hit can be provided in the native-image configuration.

Also it's crashing when using Jakarta RESTful WS API but not when using `QuarkusApplication`. Working example commented in the repo.

# Steps to reproduce the issue

1. `git clone git@github.com:tomgelu/native-image-issue.git`
2. `cd native-image-issue`
3. `docker build -f src/main/docker/Dockerfile.native-micro -t native-image-issue:test .`
4. `docker run -p 8080:8080 native-image-issue:test`
5. `curl --request POST --url http://localhost:8080/test`

# More details

```
at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:121)
at java.base@21.0.2/java.lang.reflect.Array.multiNewArray(Array.java:409)
at java.base@21.0.2/java.lang.reflect.Array.newInstance(Array.java:114)
at org.hipparchus.util.MathArrays.buildArray(MathArrays.java:1628)
at org.hipparchus.geometry.euclidean.threed.FieldRotation.<init>(FieldRotation.java:247)
at org.orekit.frames.LOFType$3.rotationFromInertial(LOFType.java:151) 
```

**Comment by fernando-valdez** [comment]
Thanks for reporting this issue. I will take a look at the repreducer and will let you know if I have any questions

**Comment by gingk1212** [comment]
This issue is very similar to #4590.

That aside, I was able to reproduce it using the reproducer. When using GraalVM 23.0.1+11.1, a more detailed message was output.

```
Exception in thread "main" org.graalvm.nativeimage.MissingReflectionRegistrationError: The program tried to reflectively instantiate the array class

   org.hipparchus.analysis.differentiation.Gradient[][]

without it being registered for runtime reflection. Add org.hipparchus.analysis.differentiation.Gradient[][] to the reflection metadata to solve this problem. Note: Add "unsafeAllocated" to the array class registration to enable runtime instantiation. See https://www.graalvm.org/latest/reference-manual/native-image/metadata/#reflection for help.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.reflect.MissingReflectionRegistrationUtils.errorForArray(MissingReflectionRegistrationUtils.java:121)
	at java.base@23.0.1/java.lang.reflect.Array.multiNewArray(Array.java:410)
	at java.base@23.0.1/java.lang.reflect.Array.newInstance(Array.java:112)
	at org.hipparchus.util.MathArrays.buildArray(MathArrays.java:1660)
	at org.hipparchus.geometry.euclidean.threed.FieldRotation.<init>(FieldRotation.java:247)
	at org.example.Main.main(Main.java:18)
	at java.base@23.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```

I’m not sure why a 2D array requires metadata registration, but following the explanation, adding the following metadata to src/main/resources/META-INF/native-image/reachability-metadata.json resolved the error.

```
{
  "reflection": [
    {
      "type": "[[Lorg.hipparchus.analysis.differentiation.Gradient;"
    }
  ]
}
```

I hope this can be of some help.
