### ISSUE TITLE
java.lang.UnsatisfiedLinkError: com.fazecast.jSerialComm.SerialPort.getCommPortsNative()

### ISSUE THREAD

**Issue by 18028798638** [oracle/graal#9605]
**Describe the issue**
jSerialComm doesn't work in native-image, but the Java program succeeded.

**Steps to reproduce the issue**
Please include both build steps as well as run steps
1. Add the jSerialComm dependency.
2. Coding with jSerialComm...
3. mvn -Pnative native:compile -DskipTests 
4. run native-image.exe

**Describe GraalVM and your environment:**
 - GraalVM version: GraalVM CE 21.0.2+13.1
 - JDK major version: 21
 - OS: windows 10
 - Architecture: arm64

**More details**
[jni-config.json](https://github.com/user-attachments/files/16846223/jni-config.json)

```
   
Caused by: java.lang.UnsatisfiedLinkError: com.fazecast.jSerialComm.SerialPort.getCommPortsNative()[Lcom/fazecast/jSerialComm/SerialPort; [symbol: Java_com_fazecast_jSerialComm_SerialPort_getCommPortsNative or Java_com_fazecast_jSerialComm_SerialPort_getCommPortsNative__]
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:152)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:54)
	at com.fazecast.jSerialComm.SerialPort.getCommPortsNative(Native Method)
	at com.fazecast.jSerialComm.SerialPort.getCommPorts(SerialPort.java:491)
	at com.appo.iotservice.tcp.custom.CustomSerialCom.findPorts(CustomSerialCom.java:39)
	at com.appo.iotservice.controller.ZkNettyController.getSerialPorts(ZkNettyController.java:199)
	at java.base@21.0.2/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
	... 46 common frames omitted
```

**Comment by fernando-valdez** [comment]
Thanks for reporting this issue and sharing the steps. However, can you please create a simple project that can be used to reproduce the issue?

**Comment by 18028798638** [comment]
> Thanks for reporting this issue and sharing the steps. However, can you please create a simple project that can be used to reproduce the issue?

Thank you for your attention, this is my simple project.
https://github.com/18028798638/jSerialComm

**Comment by kulik** [comment]
same issue with GraalVM gradle and jSerialComm independant of version 2.7 or 2.11
`Caused by: java.lang.UnsatisfiedLinkError: com.fazecast.jSerialComm.SerialPort.retrievePortDetails()V [symbol: Java_com_fazecast_jSerialComm_SerialPort_retrievePortDetails or Java_com_fazecast_jSerialComm_SerialPort_retrievePortDetails__]
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:152) ~[na:na]
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:41) ~[na:na]
	at com.fazecast.jSerialComm.SerialPort.retrievePortDetails(Native Method) ~[na:na]
	at com.fazecast.jSerialComm.SerialPort.getCommPort(SerialPort.java:546) ~[na:na]
	a`

**Comment by kulik** [comment]
Graalvm natiму як прописати so файли в градле

**Comment by selhagani** [comment]
Could you please try testing using the latest available version of GraalVM and tell me if that fixes your issue? You can find it here https://github.com/graalvm/graalvm-ce-builds/releases/

**Comment by selhagani** [comment]
As I haven't heard back from you in over three weeks, I will be closing this issue for now.
Thank you for your understanding.

**Comment by andlinger** [comment]
Hi @selhagani!

I just came across this issue. I have the same problem and it still persists. I am using GraalVM 25.0.1.
What are the options here?

**Comment by Jeroenr1** [comment]
> Hi [@selhagani](https://github.com/selhagani)!
> 
> I just came across this issue. I have the same problem and it still persists. I am using GraalVM 25.0.1. What are the options here?

When using Quarkus with JSerialComm and native-image, it is working. Maybe you can look at that solution to get your software working? https://github.com/Fazecast/jSerialComm/issues/438#issuecomment-3926310221
