### ISSUE TITLE
Deadlock when executing shutdown hook in parallel with context close calls

### ISSUE THREAD

**Issue by astral303** [oracle/graal#961]
My application experiences a deadlock on shutdown, due to conflicting synchronization order during "shutdown hook engine close" and "close context" calls happening in two separate threads.

```Found one Java-level deadlock:
=============================
"Thread-18":
  waiting to lock monitor 0x00007ffb4c00d438 (object 0x00000007595c94c0, a com.oracle.truffle.polyglot.PolyglotContextImpl),
  which is held by "object-pool-3-thread-1"
"object-pool-3-thread-1":
  waiting to lock monitor 0x00007ffb4884e218 (object 0x0000000743edef30, a com.oracle.truffle.polyglot.PolyglotEngineImpl),
  which is held by "Thread-18"
Java stack information for the threads listed above:
===================================================
"Thread-18":
	at com.oracle.truffle.polyglot.PolyglotContextImpl.closeImpl(PolyglotContextImpl.java:911)
	- waiting to lock <0x00000007595c94c0> (a com.oracle.truffle.polyglot.PolyglotContextImpl)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.ensureClosed(PolyglotEngineImpl.java:734)
	- locked <0x0000000743edef30> (a com.oracle.truffle.polyglot.PolyglotEngineImpl)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl$PolyglotShutDownHook.run(PolyglotEngineImpl.java:897)
	at java.lang.Thread.run(Thread.java:748)
"object-pool-3-thread-1":
	at com.oracle.truffle.polyglot.PolyglotLanguage.freeInstance(PolyglotLanguage.java:223)
	- waiting to lock <0x0000000743edef30> (a com.oracle.truffle.polyglot.PolyglotEngineImpl)
	at com.oracle.truffle.polyglot.PolyglotLanguageContext.dispose(PolyglotLanguageContext.java:226)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.closeImpl(PolyglotContextImpl.java:977)
	- locked <0x00000007595c94c0> (a com.oracle.truffle.polyglot.PolyglotContextImpl)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.close(PolyglotContextImpl.java:803)
	at org.graalvm.polyglot.Context.close(Context.java:598)
	at handler.deallocate
	at object.pool.dealloc
	at object.pool.shutPoolDown
Found 1 deadlock.
```

Looks like the locking order during shutdown hook is "lock engine, then lock context." During context close, the locking order is "lock context, then lock engine."

Workaround:

Enforce "lock engine first" lock ordering by wrapping calls to `context.close()` like so: `synchronize (context.getEngine()) { context.close(); }`.

Using GraalVM 1.0-rc12.

**Comment by chumer** [comment]
This was already fixed some time ago. Whenever the engine lock is held to free the instance the context lock is not longer held. This should unblock this deadlock.
