### ISSUE TITLE
Classes not available at runtime still causing issues in build

### ISSUE THREAD

**Issue by dsyer** [oracle/graal#965]
There are a lot of improvements to this area in rc12, so thank you. I still have this issue:

```
$ native-image ...
Build on Server(pid: 8907, port: 32969)
[target/demo:8907]    classlist:     584.66 ms
[target/demo:8907]        (cap):     553.10 ms
[target/demo:8907]        setup:     728.71 ms
Warning: class initialization of class org.springframework.http.converter.feed.AbstractWireFeedHttpMessageConverter failed with exception java.lang.NoClassDefFoundError: com/rometools/rome/io/FeedException. This class will be initialized at run time because either option --report-unsupported-elements-at-runtime or option --allow-incomplete-classpath is used for image building. Use the option --delay-class-initialization-to-runtime=org.springframework.http.converter.feed.AbstractWireFeedHttpMessageConverter to explicitly request delayed initialization of this class.
Warning: class initialization of class org.apache.commons.logging.LogAdapter$Log4jLog failed with exception java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager. This class will be initialized at run time because either option --report-unsupported-elements-at-runtime or option --allow-incomplete-classpath is used for image building. Use the option --delay-class-initialization-to-runtime=org.apache.commons.logging.LogAdapter$Log4jLog to explicitly request delayed initialization of this class.
[target/demo:8907]     analysis:     988.08 ms
Fatal error: java.lang.TypeNotPresentException: Type com.rometools.rome.feed.WireFeed not present
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.reflectiveObjects.TypeVariableImpl.getBounds(TypeVariableImpl.java:144)
	at com.oracle.svm.core.hub.TypeVariableBoundsComputer.compute(SunReflectTypeSubstitutions.java:139)
	at com.oracle.svm.hosted.substitute.ComputedValueField.readValue(ComputedValueField.java:253)
	at com.oracle.svm.core.meta.ReadableJavaField.readFieldValue(ReadableJavaField.java:35)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:99)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:74)
	at com.oracle.graal.pointsto.ObjectScanner.scanField(ObjectScanner.java:114)
	at com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:278)
	at com.oracle.graal.pointsto.ObjectScanner.finish(ObjectScanner.java:319)
	at com.oracle.graal.pointsto.ObjectScanner.scanBootImageHeapRoots(ObjectScanner.java:81)
	at com.oracle.graal.pointsto.ObjectScanner.scanBootImageHeapRoots(ObjectScanner.java:63)
	at com.oracle.graal.pointsto.BigBang.checkObjectGraph(BigBang.java:598)
	at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:555)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:648)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:492)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:410)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: com.rometools.rome.feed.WireFeed
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	... 23 more
Error: Processing image build request failed
```

Sample project in @sdeleuze issues project: https://github.com/sdeleuze/graal-issues/tree/master/rome. It's a bit hard to reproduce without using `RestTemplate` - see the `README` in the sample.

**Comment by cstancu** [comment]
Thanks for the report! I'll look into it.

**Comment by cstancu** [comment]
Fixed in https://github.com/oracle/graal/commit/a4dd822048d68bef0b4308f41ff8bd89a0b65297.
