### ISSUE TITLE
The build crashed with $ mx build on IBM Semeru 21 LTS JDK

### ISSUE THREAD

**Issue by Tibor17** [oracle/graal#9651]
**Describe GraalVM and your environment :**

- JDK version: IBM Semeru 21.0.4 (OpenJ9)
- OS and OS Version: Ubuntu
- Architecture: x64
- The output of `java -Xinternalversion`:

> Eclipse OpenJ9 IBM Semeru Runtime Open Edition 64-bit Server VM (21.0.4+7-LTS) from linux-amd64 JRE with Extensions for OpenJDK for Eclipse OpenJ9 21.0.4.0, built on Jul 16 2024 00:00:00 by admin with g++-11.2 (Adoptium/sxa) 11.2.0

**Have you verified this issue still happens when using the latest snapshot?**
Yes, these are the repro steps.
```
export JAVA_HOME=/path/to/jdk-21-semeru
$ cd compiler
$ mx build
```
**Describe the issue**
>mx build
JVMJ9VM007W Command-line option unrecognised: -Xlog:disable
Exception in thread "main" java.lang.IllegalArgumentException: Invalid version string: '**openj9-0.46.0**'
        at java.base/java.lang.Runtime$Version.parse(Runtime.java:1122)
        at jdk.graal.compiler.hotspot.JVMCIVersionCheck.run(JVMCIVersionCheck.java:358)
        at jdk.graal.compiler.hotspot.JVMCIVersionCheck.check(JVMCIVersionCheck.java:273)
        at jdk.graal.compiler.hotspot.JVMCIVersionCheck.check(JVMCIVersionCheck.java:259)
        at jdk.graal.compiler.hotspot.JVMCIVersionCheck.main(JVMCIVersionCheck.java:413)

**Comment by selhagani** [comment]
Hi @Tibor17, 
Thanks for reaching out to us.

Could you please try downloading and setting up GraalVM before you test? You can download it from [this link](https://github.com/graalvm/graalvm-ce-builds/releases)

**Comment by Tibor17** [comment]
> Hi @Tibor17, Thanks for reaching out to us.
> 
> Could you please try downloading and setting up GraalVM before you test? You can download it from [this link](https://github.com/graalvm/graalvm-ce-builds/releases)

My point is to build my own GraalVM based on IBM Semeru JDK because it have a special GC and VM and abilities to shrink native committed memory.

**Comment by Tibor17** [comment]
> I see, I get you now. IBU Semeru seems to be based on OpenJ9 and cannot be used as a base to build GraalVM distributions.

But here https://github.com/oracle/graal/issues/7679 is another issue which is related to JDK 17 and it is obvious that in January the build was working with IBM Semeru.
