### ISSUE TITLE
[native-image] Failed to create native image when sqlite3 jar file is used in the application

### ISSUE THREAD

**Issue by moorsu** [oracle/graal#966]
error: unsupported features in 2 methods
Detailed message:
Error: Parameter 1 of org.sqlite.date.FastDatePrinter$TwelveHourField.<init>(FastDatePrinter$NumberRule) has declared type org.sqlite.date.FastDatePrinter$NumberRule which is incompatible with types in state: MTypeMObject<3:[0x00000F1800005E32:!S:FastDatePrinter$PaddedNumberField, 0x00000F1900005E33:!S:FastDatePrinter$TwoDigitNumberField, 0x00000F1A00005E34:!S:FastDatePrinter$UnpaddedNumberField]>
Call path from entry point to org.sqlite.date.FastDatePrinter$TwelveHourField.<init>(FastDatePrinter$NumberRule): 
	at org.sqlite.date.FastDatePrinter$TwelveHourField.<init>(FastDatePrinter.java:988)
	at org.sqlite.date.FastDatePrinter.parsePattern(FastDatePrinter.java:234)
	at org.sqlite.date.FastDatePrinter.init(FastDatePrinter.java:162)
	at org.sqlite.date.FastDatePrinter.<init>(FastDatePrinter.java:155)
	at org.sqlite.date.FastDateFormat.<init>(FastDateFormat.java:394)
	at org.sqlite.date.FastDateFormat.<init>(FastDateFormat.java:379)
	at org.sqlite.date.FastDateFormat$1.createInstance(FastDateFormat.java:101)
	at org.sqlite.date.FastDateFormat$1.createInstance(FastDateFormat.java:98)
	at org.sqlite.date.FormatCache.getInstance(FormatCache.java:82)
	at org.sqlite.date.FastDateFormat.getInstance(FastDateFormat.java:129)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:70)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:26)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)

**Comment by cstancu** [comment]
@moorsu can you please provide steps to reproduce this error?

**Comment by cstancu** [comment]
I'll close this due to inactivity. @moorsu please reopen if you can provide a reproducible example.

**Comment by moorsu** [comment]
Hi @cstancu, Apology for the delay. Here are the steps to reproduce the problem

Write a test program to open a java.sql.Connection using the SQLite JDBC driver org.xerial.sqlite-jdbc.jar (version 3.18.0)

try {
Class.forName("org.sqlite.JDBC");
Connection  connection = DriverManager.getConnection("jdbc:sqlite:mydb");
}
catch (Exception e){
}

Or use the example program from 

https://bitbucket.org/xerial/sqlite-jdbc

Try to get native-image from that class.

Please let me know if you need more info. Sorry about the delay again.

**Comment by borkdude** [comment]
I'm interested in using sqlite with GraalVM native too.
I'm getting this Exception:

```
Caused by: java.lang.Exception: No native library is found for os.name=Mac and os.arch=x86_64. path=/org/sqlite/native/Mac/x86_64
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:333)
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:64)
	at org.sqlite.core.NativeDB.load(NativeDB.java:63)
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:235)
```

**Comment by borkdude** [comment]
There's also an issue for this in the sqlite-jdbc project:
https://github.com/xerial/sqlite-jdbc/issues/413

**Comment by mageddo** [comment]
here a repo where you can reproduce the issue

https://github.com/mageddo/graalvm-examples/tree/1137b7bf48/sqlite

```
$ ./gradlew clean build nativeImage && ./build/graal/sqlite
Failed to load native library:sqlite-unknown-b8850178-1f5f-41ea-a1dd-1d3349f3a388-libsqlitejdbc.so. osinfo: Linux/x86_64
java.lang.UnsatisfiedLinkError: Unsupported JNI version 0xffffffff, required by /var/tmp/sqlite-unknown-b8850178-1f5f-41ea-a1dd-1d3349f3a388-libsqlitejdbc.so
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V [symbol: Java_org_sqlite_core_NativeDB__1open_1utf8 or Java_org_sqlite_core_NativeDB__1open_1utf8___3BI]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:54)
	at org.sqlite.core.NativeDB._open_utf8(NativeDB.java)
	at org.sqlite.core.NativeDB._open(NativeDB.java:78)
	at org.sqlite.core.DB.open(DB.java:195)
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:243)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21)
	at org.sqlite.JDBC.createConnection(JDBC.java:115)
	at org.sqlite.SQLiteDataSource.getConnection(SQLiteDataSource.java:410)
	at org.sqlite.SQLiteDataSource.getConnection(SQLiteDataSource.java:398)
	at com.mageddo.sqlite.App.main(App.java:15)

```

**Comment by araspitzu** [comment]
Any news on this? I'm hitting exactly the same problem

**Comment by mageddo** [comment]
The graalvm is now working, [here the working version](https://github.com/mageddo/graalvm-examples/tree/59f1f1bf09894681edfddaa100b4504770ad0685), special thanks to @mukel

**Comment by cboddy** [comment]
Hello, this appears to still be an issue for us too with:
[sqlite-jdbc 3.28.0](https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc/3.28.0) and [graalvm-ce-linux-amd64-19.2.0](https://github.com/oracle/graal/releases/tag/vm-19.2.0).

Specifically I see this 
```
native-image -cp "lib/*" -jar my_jar.jar \
     --no-fallback\
     --initialize-at-build-time=org.sqlite.JDBC\
     --initialize-at-build-time=org.sqlite.core.DB\$ProgressObserver\
     --initialize-at-build-time=org.sqlite.core.DB\
     --initialize-at-build-time=org.sqlite.core.NativeDB\
     --initialize-at-build-time=org.sqlite.ProgressHandler\
     --initialize-at-build-time=org.sqlite.Function\
     --initialize-at-build-time=org.sqlite.Function\$Aggregate\
     --initialize-at-build-time=org.sqlite.Function\$Window\
     -H:+AllowVMInspection\
     -H:+ReportUnsupportedElementsAtRuntime\
     -H:EnableURLProtocols=http\
     --allow-incomplete-classpath
```

```
native-image Build on Server(pid: 11818, port: 33963)
[PeergosServer:11818]    classlist:   1,947.74 ms
[PeergosServer:11818]        (cap):   1,038.01 ms
[PeergosServer:11818]        setup:   1,468.45 ms
[PeergosServer:11818]     analysis:  17,006.04 ms
Error: Classes that should be initialized at run time got initialized during image building:
 org.sqlite.RS was unintentionally initialized at build time.  To see why org.sqlite.RS got initialized use -H:+TraceClassInitializationorg.sqlite.ExtendedCommand$SQLExtension was unintentionally initialized at build time.  To see why org.sqlite.ExtendedCommand$SQLExtension got initialized use -H:+TraceClassInitializationorg.sqlite.ExtendedCommand was unintentionally initialized at build time.  To see why org.sqlite.ExtendedCommand got initialized use -H:+TraceClassInitializationorg.sqlite.Stmt was unintentionally initialized at build time.  To see why org.sqlite.Stmt got initialized use -H:+TraceClassInitializationorg.sqlite.Unused was unintentionally initialized at build time.  To see why org.sqlite.Unused got initialized use -H:+TraceClassInitializationorg.sqlite.Codes was unintentionally initialized at build time.  To see why org.sqlite.Codes got initialized use -H:+TraceClassInitializationorg.sqlite.Conn was unintentionally initialized at build time.  To see why org.sqlite.Conn got initialized use -H:+TraceClassInitializationorg.sqlite.PrepStmt was unintentionally initialized at build time.  To see why org.sqlite.PrepStmt got initialized use -H:+TraceClassInitializationorg.sqlite.SQLiteConfig was unintentionally initialized at build time.  To see why org.sqlite.SQLiteConfig got initialized use -H:+TraceClassInitializationorg.sqlite.DB was unintentionally initialized at build time.  To see why org.sqlite.DB got initialized use -H:+TraceClassInitialization
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

Is there any plan for it to be fixed (or is there a version we can move to already)? 

Many thanks!

**Comment by mageddo** [comment]
@cboddy it will be easier to help you if you create a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by araspitzu** [comment]
If it can help i've been able to use SQLite jdbc driver (on JNI) following this repo https://github.com/mageddo/graalvm-examples/tree/master/sqlite

**Comment by cstancu** [comment]
@mageddo thanks for sharing your working solution!

**Comment by budduedgar** [comment]
I have tried to follow some steps in the provided (@mageddo) solution using build.gradle ..
```
    implementation 'org.xerial:sqlite-jdbc:3.36.0.1'
    compileOnly("com.oracle.substratevm:svm:19.2.1")
    implementation("org.graalvm.sdk:graal-sdk:21.1.0")

```
with the following native-image parameters as below...
        "--no-fallback",
        "--enable-all-security-services",
        "--report-unsupported-elements-at-runtime",
        "--initialize-at-build-time=java.sql.DriverManager",
        "--initialize-at-build-time=org.sqlite.JDBC",
	"--initialize-at-build-time=org.sqlite.core.DB\$ProgressObserver",
	"--initialize-at-build-time=org.sqlite.core.DB",
	"--initialize-at-build-time=org.sqlite.core.NativeDB",
	"--initialize-at-build-time=org.sqlite.ProgressHandler",
	"--initialize-at-build-time=org.sqlite.Function",
	"--initialize-at-build-time=org.sqlite.Function\$Aggregate",
	"--initialize-at-build-time=org.sqlite.Function\$Window"

The generated native image runs with the following error whenever I try to make a connection to the database 
jdbc:sqlite:/data/demo.db
---------------------------------------------------------------------------------

java.sql.SQLException: Error opening connection
at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:244)
Caused by: java.lang.Exception: No native library is found for os.name=Linux, os.arch=aarch64, path=[]

**Comment by cyw3** [comment]
> Fix the native image JNI configuration for the SQLite example. mageddo/graalvm-examples#2

I have the same error here.
