### ISSUE TITLE
[native-image] Failed to create native image with the error Too many loops in method - The class has around 30000+ lines of code.

### ISSUE THREAD

**Issue by moorsu** [oracle/graal#967]
Error: Too many loops in method
Call path from entry point to 
....
.....
....
com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Original exception that caused the problem: org.graalvm.compiler.core.common.PermanentBailoutException: Too many loops in method
	at org.graalvm.compiler.java.BciBlockMapping.makeLoopHeader(BciBlockMapping.java:1014)
	at org.graalvm.compiler.java.BciBlockMapping.computeBlockOrder(BciBlockMapping.java:1041)
	at org.graalvm.compiler.java.BciBlockMapping.computeBlockOrder(BciBlockMapping.java:1057)
	at org.graalvm.compiler.java.BciBlockMapping.computeBlockOrder(BciBlockMapping.java:1057)
	at org.graalvm.compiler.java.BciBlockMapping.computeBlockOrder(BciBlockMapping.java:1057)
	at org.graalvm.compiler.java.BciBlockMapping.computeBlockOrder(BciBlockMapping.java:1057)

**Comment by cstancu** [comment]
@moorsu can you please provide steps to reproduce this error?

**Comment by cstancu** [comment]
This is a limitation in the Graal compiler: [only 64 loops per method are allowed](https://github.com/oracle/graal/blob/master/compiler/src/org.graalvm.compiler.java/src/org/graalvm/compiler/java/BciBlockMapping.java#L1014). @dougxc can we lift this limitation?

**Comment by dougxc** [comment]
In theory we could but it's not trivial to do it without increasing the memory overhead for compilations that don't blow this limit. I assume this is generated code - maybe the code generator can split methods up to avoid this limit?

**Comment by dougxc** [comment]
@moorsu please re-open if you have a reproducer so that we can test any fix we come up with.
