### ISSUE TITLE
[GR-66205] Native images don't print "Helpful NullPointerExceptions" (JEP 358)

### ISSUE THREAD

**Issue by zakkak** [oracle/graal#9680]
**Describe the issue**
JVM prints:

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.length()" because "HelloWorld.name" is null
	at HelloWorld.main(HelloWorld.java:6)
```

while the corresponding native image prints:

```
Exception in thread "main" java.lang.NullPointerException
	at HelloWorld.main(HelloWorld.java:6)
```

**Steps to reproduce the issue**
```
cat > HelloWorld.java <<EOF                                                                                                                                                                     
public class HelloWorld {

    static final String name = null;

    public static void main(String[] args) {
        System.out.println("Hello world! " + name.length());
    }

}
EOF
javac HelloWorld.java
java HelloWorld
native-image -cp ./ HelloWorld
./helloworld
```

**Describe GraalVM and your environment:**
 - GraalVM version (latest snapshot builds can be found [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)), or commit id if built from source: **a5ce3a7367da1d145e364f78551c16618495a3af**
 - JDK major version: **24+3**
 - OS: **Fedora 40**
 - Architecture: **AMD64**

**More details**
Originally reported in https://github.com/quarkusio/quarkus/issues/43274

**Comment by zakkak** [comment]
FWIW in order to "fix" this, substratevm should implement

https://github.com/oracle/graal/blob/bd969aab3186e660842157e605020ff1b12b564b/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JavaLangSubstitutions.java#L607-L611

**Comment by zapster** [comment]
Hey @zakkak! Back when this feature was added to the JDK, we consciously decided against supporting it. Implementing it would require a lot of metadata (comparable to full deoptimization infos required for run-time compilation in native image), which would grow the image size significantly. Since it is only a quality-of-life feature, we don't plan on adding support. That said, we are open for external contributions of someone really wants this feature, as long as it is optional and has no impact on the default image size and maintainability of the code base.

**Comment by zakkak** [comment]
Thanks for the clarification @zapster
