### ISSUE TITLE
Order of entries in jar changes result of native-image

### ISSUE THREAD

**Issue by bradnewman** [oracle/graal#969]
I have a project where:

 * I can build it on one machine and `native-image` RC12 produces a working binary.
 * I can build it on another machine and `native-image` RC12 produces an error.

This is apparently not due to a difference in behavior of `native-image` between the systems or between attempts, because it is consistently reproducible and I can copy the .jar from the "working" system to the "failing" system and `native-image` then works, and vice versa with the .jar from the "failing" system - the behavior follows the .jar file around.

I've compared the .jars produced by the two systems, and the only difference I can see (other than a couple timestamps) is the order of the entries within the two .jar files.  The vast majority of the entries in the jars are from Gradle dependencies, and thus are 100% identical.

To be clear, I'm not concerned about the error from `native-image` - I can work around it, and I'm not totally sure, but I think the error from `native-image` might actually be the "correct" behavior for this application.  I am concerned that the behavior of `native-image` seems to depend on the order of the entries within the .jar, which as far as I know should not matter.

I'm not sure what determines the order of the entries within the jar file, or what specifically about the two orders results in different behavior from `native-image`.

I'm attaching the failing and working jars for reference, renamed to zips so that GitHub will allow me to attach them to this issue:

[working.zip](https://github.com/oracle/graal/files/2846623/working.zip)
[failing.zip](https://github.com/oracle/graal/files/2846624/failing.zip)

    native-image --verbose --static --report-unsupported-elements-at-runtime -jar working.zip
    # [example.zip:8]      [total]: 264,766.68 ms
    native-image --verbose --static --report-unsupported-elements-at-runtime -jar failing.zip
    # Fatal error: java.lang.UnsupportedClassVersionError

Other information that might be useful:

The "failing" jar was produced on:

    JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
    OS:           Linux 3.10.0-862.3.2.el7.x86_64 amd64

The "working" jar was produced on:

    JVM:          1.8.0_45 (Oracle Corporation 25.45-b02)
    OS:           Windows 7 6.1 amd64

On both systems, `native-image` is being run within a Docker container based on the same GraalVM image.

The jars are built from the example in [HewlettPackard/kraal](https://github.com/HewlettPackard/kraal):

    git clone https://github.com/HewlettPackard/kraal.git
    cd kraal/example
    git checkout v0.0.14
    ./gradlew build

    docker build -f Dockerfile -t kraal-example build/fatjar
    # OR: 
    native-image --static --report-unsupported-elements-at-runtime -jar build/fatjar/example.jar

The error that `native-image` reports for the "failing" jar:

    Fatal error: java.lang.UnsupportedClassVersionError
            at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
            at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
            at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
            at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:427)
            at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:285)
            at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:407)
            at com.oracle.svm.hosted.server.NativeImageBuildServer.executeCompilation(NativeImageBuildServer.java:390)
            at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$processCommand$8(NativeImageBuildServer.java:327)
            at com.oracle.svm.hosted.server.NativeImageBuildServer.withJVMContext(NativeImageBuildServer.java:408)
            at com.oracle.svm.hosted.server.NativeImageBuildServer.processCommand(NativeImageBuildServer.java:324)
            at com.oracle.svm.hosted.server.NativeImageBuildServer.processRequest(NativeImageBuildServer.java:268)
            at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$serve$7(NativeImageBuildServer.java:228)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            at java.lang.Thread.run(Thread.java:748)
    Caused by: java.lang.UnsupportedClassVersionError: org/eclipse/jetty/alpn/java/server/JDK9ServerALPNProcessor has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
            at java.lang.ClassLoader.defineClass1(Native Method)
            at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
            at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
            at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
            at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
            at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
            at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
            at java.security.AccessController.doPrivileged(Native Method)
            at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
            at java.lang.Class.forName0(Native Method)
            at java.lang.Class.forName(Class.java:348)
            at com.oracle.svm.hosted.ImageClassLoader.forName(ImageClassLoader.java:373)
            at com.oracle.svm.hosted.ImageClassLoader.findClassByName(ImageClassLoader.java:363)
            at com.oracle.svm.hosted.FeatureImpl$FeatureAccessImpl.findClassByName(FeatureImpl.java:100)
            at com.oracle.svm.hosted.ServiceLoaderFeature.handleType(ServiceLoaderFeature.java:203)
            at com.oracle.svm.hosted.ServiceLoaderFeature.duringAnalysis(ServiceLoaderFeature.java:114)
            at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:671)
            at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
            at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:671)
            at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:492)
            at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:410)
            at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
            at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
            at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
            at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
            at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
    Error: Processing image build request failed

**Comment by cstancu** [comment]
I could not replicate this issue.
