### ISSUE TITLE
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/Buffer; when calling from JNI code

### ISSUE THREAD

**Issue by kostya-sh** [oracle/graal#9691]
**Describe the issue**
When using solclientj native library (unfortunately closed source) I get the following error when attempting to load the library from the native-image compiled executable:

```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/Buffer;
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1347) ~[?:?]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1332) ~[?:?]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.GetMethodID(JNIFunctions.java:434) ~[?:?]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIOnLoadFunctionPointer.invoke(JNILibraryInitializer.java) ~[?:?]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNILibraryInitializer.callOnLoadFunction(JNILibraryInitializer.java:70) ~[?:?]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNILibraryInitializer.initialize(JNILibraryInitializer.java:131) ~[?:?]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibrarySupport.addLibrary(NativeLibrarySupport.java:128) ~[?:?]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibrarySupport.addLibrary(NativeLibrarySupport.java:84) ~[?:?]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibraries.loadLibrary0(NativeLibraries.java:147) ~[launcher:?]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibraries.loadLibraryAbsolute(NativeLibraries.java:102) ~[launcher:?]
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:114) ~[launcher:?]
        at java.base/java.lang.Runtime.load0(Runtime.java:852) ~[launcher:?]
        at java.base/java.lang.System.load(System.java:2030) ~[?:?]
        at com.solacesystems.solclientj.core.NarSystem.loadLibrary(NarSystem.java:50) ~[?:?]
        at com.solacesystems.solclientj.core.Solclient.<clinit>(Solclient.java:66) ~[?:?]
```

The same application works under GraalVM and HotSpot VM.  

I believe the issue is that the solclient JNI library attempts to access **java.nio.ByteBuffer.position(I)Ljava/nio/Buffer** method from JDK 8 while the native image VM expects it to use JDK 9+ **java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer** method. I found the following blog post describing a similar issue: https://www.morling.dev/blog/bytebuffer-and-the-dreaded-nosuchmethoderror/

It looks like native image VM cannot resolve the method correctly in this case.

**Describe GraalVM and your environment:**
 - GraalVM version: **22.0.2+9.1**
 - JDK major version: **22**
 - OS: **Redhat 8**
 - Architecture: **AMD64**

**Comment by oubidar-Abderrahim** [comment]
Thank you for sharing this, we'll take a look into it shortly

**Comment by oubidar-Abderrahim** [comment]
Is it possible to provide a small reproducer to this issue? Thanks

**Comment by kostya-sh** [comment]
thank you for looking into this. Will prepare a standalone reproducer in the next few days.

**Comment by kostya-sh** [comment]
I've experimented a bit more and it appears that the issue is that the mentioned method is not included in the image even though it is specified in the JNI reachability metadata (I am using reachability metadata created by native-image-agent).

The reproducer can be found here: [kostya-sh/graal-9691](https://github.com/kostya-sh/graal-9691)

I have also found a workaround, if I include all methods and fields for java.nio.ByteBuffer everything works (see https://github.com/kostya-sh/graal-9691/blob/main/src/main/resources/META-INF/native-image/test/test/reachability-metadata.json.working)

**Comment by oubidar-Abderrahim** [comment]
Glad to hear your found a solution. It is advisable to manually review the generated configuration files. Because the agent observes only executed code, thus, sometimes it fails to capture all required methods.

**Comment by kostya-sh** [comment]
I think this is still a bug though a workaround exists. The method that was not found in runtime present in the reachability metadata: https://github.com/kostya-sh/graal-9691/blob/main/src/main/resources/META-INF/native-image/test/test/reachability-metadata.json#L50
