### ISSUE TITLE
Cannot create a Context for java guest on windows

### ISSUE THREAD

**Issue by balazs-zsoldos** [oracle/graal#9722]
**Describe the issue**
I tried the start a Java guest context on windows, but fails with exception. I have to run my code always on docker images with hacks to test executing java guest code with graalvm.

**Steps to reproduce the issue**
The following command fails on windows:

    Context context = Context.newBuilder("java")

**Describe GraalVM and your environment:**
 Tried on openjdk 21 and on Graalvm Java 23, Windows x64 with the following dependencies (graalvm.version is 24.1.0):

    <dependency>
      <groupId>org.graalvm.polyglot</groupId>
      <artifactId>js-community</artifactId>
      <version>${graalvm.version}</version>
      <type>pom</type>
    </dependency>
    <dependency>
      <groupId>org.graalvm.polyglot</groupId>
      
      <artifactId>tools</artifactId>
      <version>${graalvm.version}</version>
      <type>pom</type>
    </dependency>
    <dependency>
      <groupId>org.graalvm.polyglot</groupId>
      <artifactId>java</artifactId>
      <version>${graalvm.version}</version>
      <type>pom</type>
    </dependency>
    <dependency>
      <groupId>org.graalvm.truffle</groupId>
      <artifactId>truffle-api</artifactId>
      <version>${graalvm.version}</version>
    </dependency>
    <dependency>
      <groupId>org.graalvm.espresso</groupId>
      <artifactId>espresso-runtime-resources-jdk21</artifactId>
      <version>${graalvm.version}</version>
    </dependency>

As the espresso-runtime-resources-jdk21 has windows executable inside, I was guessing that finally guest java code can be tested on windows programmatically.

**More details**

Stack trace:

Exception in thread "main" org.graalvm.polyglot.PolyglotException: com.oracle.truffle.espresso.meta.EspressoError: should not reach here: This can be caused by mixing native/ffi symbols with llvm signatures and vice-versa
	at com.oracle.truffle.espresso.meta.EspressoError.shouldNotReachHere(EspressoError.java:73)
	at com.oracle.truffle.espresso.ffi.nfi.NFINativeAccess$NativeToJavaWrapper.doExecute(NFINativeAccess.java:289)
	at com.oracle.truffle.espresso.ffi.nfi.NFINativeAccess$NativeToJavaWrapper.doExecuteBoundary(NFINativeAccess.java:246)
	at com.oracle.truffle.espresso.ffi.nfi.NFINativeAccess$NativeToJavaWrapper$Execute.doGeneric(NFINativeAccess.java:318)
	at com.oracle.truffle.espresso.ffi.nfi.NativeToJavaWrapperGen$InteropLibraryExports$Uncached.execute(NativeToJavaWrapperGen.java:270)
	at com.oracle.truffle.api.interop.InteropLibraryGen$UncachedDispatch.execute(InteropLibraryGen.java:7008)
	at com.oracle.truffle.espresso.jni.NativeEnv.initializeAndGetEnv(NativeEnv.java:135)
	at com.oracle.truffle.espresso.jni.NativeEnv.initializeAndGetEnv(NativeEnv.java:124)
	at com.oracle.truffle.espresso.jni.JniEnv.<init>(JniEnv.java:386)
	at com.oracle.truffle.espresso.jni.JniEnv.create(JniEnv.java:418)
	at com.oracle.truffle.espresso.runtime.EspressoContext.spawnVM(EspressoContext.java:404)
	at com.oracle.truffle.espresso.runtime.EspressoContext.initializeContext(EspressoContext.java:320)
	at com.oracle.truffle.espresso.EspressoLanguage.initializeContext(EspressoLanguage.java:294)
	at com.oracle.truffle.espresso.EspressoLanguage.initializeContext(EspressoLanguage.java:94)
	at com.oracle.truffle.api.TruffleLanguage$Env.postInit(TruffleLanguage.java:3927)
	at com.oracle.truffle.api.LanguageAccessor$LanguageImpl.postInitEnv(LanguageAccessor.java:288)
	at com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureInitialized(PolyglotLanguageContext.java:771)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.getBindings(PolyglotContextImpl.java:1417)
	at com.oracle.truffle.polyglot.PolyglotContextDispatch.getBindings(PolyglotContextDispatch.java:95)
	at org.graalvm.polyglot.Context.getBindings(Context.java:563)
	at org.goodmonolith.sandbox.TempApp.extracted(TempApp.java:23)
	at org.goodmonolith.sandbox.TempApp.main(TempApp.java:11)
	Suppressed: Attached Guest Language Frames (0)
Caused by: com.oracle.truffle.api.interop.UnsupportedMessageException: Message not supported.
	Suppressed: Attached Guest Language Frames (1)
Internal GraalVM error, please report at https://github.com/oracle/graal/issues/.

**Comment by gilles-duboscq** [comment]
Hi @balazs-zsoldos,
Thanks for the report. The root issue there is the lack isolation between the host and guest Java native libraries.

On windows at the moment the only option is to run your host application as a native-image as long as you only have 1 guest context.

A proper solution that works on HotSpot could be using sulong versions of the native libraries. That would require building the JDK libraries with the sulong LLVM toolchain.

In the meanwhile, i thought we already had better error messages for this case but it's still rather cryptic.
