### ISSUE TITLE
Static method of the base class not available through JNI reflection in a native image and delayed initialization

### ISSUE THREAD

**Issue by cubuspl42** [oracle/graal#993]
In the native image, when the JNI code tries to get a static method `Bar.foo` via `GetStaticMethodID`, if the initialization of `Bar` is delayed till runtime and the method is actually declared in a super class `Foo`, the resolution fails. It works with OpenJDK `java` (HotSpot), in Graal `java` and with native image without delayed initialization. Am I doing everything correctly?

Code: https://github.com/cubuspl42/JavaExperiments/tree/master/jni1

`Foo.java`:
```java
package com.example;

public class Foo {
    public static void foo() {
        System.out.println("foo");
    }
}

```
`Bar.java`:
```java
package com.example;

public class Bar extends Foo {
    private native static void nativeMethod();

    static {
        System.loadLibrary("native");
        nativeMethod();
    }

    public static void bar() {
        System.out.println("bar");
    }
}
```

`com_example_Bar.c`:
```c
#include "com_example_Bar.h"

#include <stdio.h>

JNIEXPORT void JNICALL Java_com_example_Bar_nativeMethod(JNIEnv *env, jclass cls) {
    printf("nativeMethod\n");

    jmethodID bar = (*env)->GetStaticMethodID(env, cls, "bar", "()V");
    if ((*env)->ExceptionCheck(env)) return;

    (*env)->CallStaticVoidMethod(env, cls, bar);

    jmethodID foo = (*env)->GetStaticMethodID(env, cls, "foo", "()V");
    if ((*env)->ExceptionCheck(env)) return;

    (*env)->CallStaticVoidMethod(env, cls, foo);
}
```

`Main.java`:
```java
package com.example;

public class Main {
    public static void main(String[] args) {
        System.out.println("main");
        Bar bar = new Bar(); // Initialize Bar
    }
}
```

`jniconfig.json`:
```json
[
    {
        "name": "com.example.Foo",
        "allDeclaredConstructors": true,
        "allPublicConstructors": true,
        "allDeclaredMethods": true,
        "allPublicMethods": true
    },
    {
        "name": "com.example.Bar",
        "allDeclaredConstructors": true,
        "allPublicConstructors": true,
        "allDeclaredMethods": true,
        "allPublicMethods": true
    }
]

```

```zsh
➜  jni git:(master) uname -a
Darwin MacBook-Pro-Jakub.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
➜  jni git:(master) /usr/bin/java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
➜  jni git:(master) /usr/bin/java -Djava.library.path=`pwd`/../out/ -cp ../out/production/jni1 com.example.Main
main
nativeMethod
bar
foo
➜  jni git:(master) java -version
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (build 1.8.0_192-20181024123616.buildslave.jdk8u-src-tar--b12)
GraalVM 1.0.0-rc12 (build 25.192-b12-jvmci-0.54, mixed mode)
➜  jni git:(master) java -Djava.library.path=`pwd`/../out/ -cp ../out/production/jni1 com.example.Main
main
nativeMethod
bar
foo
➜  jni git:(master) native-image --version
GraalVM Version 1.0.0-rc12
➜  jni git:(master) native-image --server-shutdown-all && native-image -Djava.library.path=`pwd`/../out/ -cp ../out/production/jni1 com.example.Main ../out/main
Cleanup Server(pid: 60603, port: 53974) running for: 430703:55:03
Build on Server(pid: 60869, port: 54157)*
[../out/main:60869]    classlist:   1,235.01 ms
[../out/main:60869]        (cap):     914.94 ms
[../out/main:60869]        setup:   2,064.10 ms
bar
foo
[../out/main:60869]   (typeflow):   2,466.13 ms
[../out/main:60869]    (objects):     711.57 ms
[../out/main:60869]   (features):     134.16 ms
[../out/main:60869]     analysis:   3,366.38 ms
[../out/main:60869]     universe:     158.48 ms
[../out/main:60869]      (parse):     433.49 ms
[../out/main:60869]     (inline):     849.59 ms
[../out/main:60869]    (compile):   3,340.93 ms
[../out/main:60869]      compile:   4,838.47 ms
[../out/main:60869]        image:     351.07 ms
[../out/main:60869]        write:     163.09 ms
[../out/main:60869]      [total]:  12,345.04 ms
➜  jni git:(master) ../out/main
main
➜  jni git:(master) native-image --server-shutdown-all && native-image -H:JNIConfigurationFiles=jniconfig.json --delay-class-initialization-to-runtime=com.example.Bar -cp ../out/production/jni1 com.example.Main ../out/main-delayed
Cleanup Server(pid: 60869, port: 54157) running for: 430703:56:45
Build on Server(pid: 60924, port: 54179)*
[../out/main-delayed:60924]    classlist:   1,275.61 ms
[../out/main-delayed:60924]        (cap):   1,058.70 ms
[../out/main-delayed:60924]        setup:   2,219.16 ms
[../out/main-delayed:60924]   (typeflow):   6,999.41 ms
[../out/main-delayed:60924]    (objects):   3,771.12 ms
[../out/main-delayed:60924]   (features):     191.93 ms
[../out/main-delayed:60924]     analysis:  11,132.30 ms
[../out/main-delayed:60924]     universe:     275.62 ms
[../out/main-delayed:60924]      (parse):     898.46 ms
[../out/main-delayed:60924]     (inline):   1,926.72 ms
[../out/main-delayed:60924]    (compile):   7,941.53 ms
[../out/main-delayed:60924]      compile:  11,258.66 ms
[../out/main-delayed:60924]        image:   1,057.85 ms
[../out/main-delayed:60924]        write:     285.46 ms
[../out/main-delayed:60924]      [total]:  28,482.54 ms
➜  jni git:(master) ../out/main-delayed -Djava.library.path=`pwd`/../out/
main
nativeMethod
bar
Exception in thread "main" java.lang.NoSuchMethodError: com.example.Bar.foo()V
	at com.oracle.svm.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1016)
	at com.oracle.svm.jni.functions.JNIFunctions.GetStaticMethodID(JNIFunctions.java:385)
	at com.example.Bar.nativeMethod(Bar.java)
	at com.example.Bar.<clinit>(Bar.java:8)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:341)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:261)
	at java.lang.Class.ensureInitialized(DynamicHub.java:376)
	at com.example.Main.main(Main.java:6)
```

**Comment by cubuspl42** [comment]
By the way, this isn't a made up thing ;) It's a blocker for making JavaFX work with Graal .

**Comment by johanvos** [comment]
I filed this before but it seems to be solved: https://github.com/oracle/graal/issues/858
(I manually changed all calls from Native to Java in the native JavaFX layer)

**Comment by peter-hofer** [comment]
Confirmed to work with your unmodified sources:
```
> ./com.example.main 
main
nativeMethod
bar
foo
```
