### ISSUE TITLE
Crash while building native-image of spring-petclinic

### ISSUE THREAD

**Issue by rkennke** [oracle/graal#996]
I am trying to build spring-petclinic with substratevm and getting the following crash:

mx native-image -jar spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar

Error: Error encountered while parsing com.oracle.svm.reflect.$Proxy103_constructor_daf58cf9081b19dd3dce8d77b02a3aa856a99e1a.newInstance(java.lang.Object[]) 
Parsing context:
	parsing java.base@11.0.1/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	parsing java.base@11.0.1/java.security.UnresolvedPermission.resolve(UnresolvedPermission.java:278)
	parsing java.base@11.0.1/java.security.Permissions.getUnresolvedPermissions(Permissions.java:318)
	parsing java.base@11.0.1/java.security.Permissions$1.apply(Permissions.java:249)
	parsing java.base@11.0.1/java.security.Permissions$1.apply(Permissions.java:244)
	parsing java.base@11.0.1/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
	parsing java.base@11.0.1/java.nio.charset.CoderResult.malformedForLength(CoderResult.java:222)
	parsing java.base@11.0.1/java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:588)
	parsing java.base@11.0.1/java.lang.StringCoding$StringEncoder.encode(StringCoding.java:388)
	parsing java.base@11.0.1/java.lang.StringCoding.encode(StringCoding.java:502)
	parsing java.base@11.0.1/java.lang.String.getBytes(String.java:981)
	parsing app//com.oracle.svm.core.c.CCharPointerHolderImpl.<init>(CTypeConversionSupportImpl.java:160)
	parsing app//com.oracle.svm.core.c.CTypeConversionSupportImpl.toCString(CTypeConversionSupportImpl.java:137)
	parsing app/org.graalvm.sdk/org.graalvm.nativeimage.c.type.CTypeConversion.toCString(CTypeConversion.java:94)
	parsing app//com.oracle.svm.core.posix.PosixUtils.fileOpen(PosixUtils.java:224)
	parsing app//com.oracle.svm.core.posix.Target_java_io_FileInputStream.open(PosixJavaIOSubstitutions.java:461)
	parsing java.base@11.0.1/java.io.FileInputStream.<init>(FileInputStream.java:157)
	parsing org.springframework.boot.loader.archive.ExplodedArchive.getManifest(ExplodedArchive.java:94)
	parsing org.springframework.boot.loader.ExecutableArchiveLauncher.getMainClass(ExecutableArchiveLauncher.java:55)
	parsing org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	parsing org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
	parsing app//com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:152)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Original error: com.oracle.svm.core.util.VMError$HostedError: should not reach here
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:62)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.deleteErrorMessage(AnnotationSubstitutionProcessor.java:902)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.deleteErrorMessage(AnnotationSubstitutionProcessor.java:887)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.lookup(AnnotationSubstitutionProcessor.java:184)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:128)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:391)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:371)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:75)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaMethod(UniverseMetaAccess.java:99)
	at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaMethod(AnalysisMetaAccess.java:66)
	at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaMethod(AnalysisMetaAccess.java:39)
	at com.oracle.svm.reflect.hosted.ReflectionSubstitutionType$ReflectiveNewInstanceMethod.buildGraph(ReflectionSubstitutionType.java:589)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.buildGraph(AnalysisMethod.java:306)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:186)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:332)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:186)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:352)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:394)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:508)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:169)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

**Comment by johanvos** [comment]
This seems to be the same issue as https://github.com/oracle/graal/issues/968
(Proxy with a constructor)

**Comment by vjovanov** [comment]
It is similar, this is what happens. The issue happens because in the following snippet 
```
try {
   Constructor<?> c = pc.getConstructor(PARAMS1);
   return (Permission) c.newInstance(
         new Object[] { name});
} catch (NoSuchMethodException ne) {
   Constructor<?> c = pc.getConstructor(PARAMS2);
   return (Permission) c.newInstance( // the problem is here
        new Object[] { name, actions });
}
```
from `java.security.UnresolvedPermission.resolve(UnresolvedPermission.java:278)` analysis believes that `c` can be one of our substitution types and tries to generate a constructor for it (which is currently impossible).

This happens now as this code is reachable from the lambda at `java.security.Permissions.getPermissionCollection` and this lambda did not exist in JDK 8. In #968 the issue comes through a different path, but the code pattern that causes it is the same.

The patch that @johanvos proposed for #968 works to fix this issue, but causes another problem with JDK 11. We will have to address that before this can work.

Note `spring-petclinic` does not even build on JDK 8. I would start with that first. Also, with those fixes I have reached the same point as in JDK 8.

**Comment by rkennke** [comment]
Thanks for the comments. Yeah, I tried with jdk8 too, but as you say, that won't even work either. My current goal is to get anything working that lets me play with substrate's GC. https://github.com/adinn/churn seems to do the job and actually fits the bill very nicely.

**Comment by cstancu** [comment]
Using the changes in the #1001 PR and the ones that I discussed in https://github.com/oracle/graal/issues/1002#issuecomment-466867932 I was able to build an image for `spring-petclinic`. You also need to specifcy `--report-unsupported-elements-at-runtime`: 
`native-image --report-unsupported-elements-at-runtime -jar target/spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar`.

However when I run the image I get:
```
$ ./spring-petclinic-2.1.0.BUILD-SNAPSHOT 
Exception in thread "main" java.lang.IllegalStateException: java.lang.IllegalStateException: Unable to determine code source archive
	at org.springframework.boot.loader.ExecutableArchiveLauncher.<init>(ExecutableArchiveLauncher.java:41)
	at org.springframework.boot.loader.JarLauncher.<init>(JarLauncher.java:35)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.IllegalStateException: Unable to determine code source archive
	at org.springframework.boot.loader.Launcher.createArchive(Launcher.java:122)
	at org.springframework.boot.loader.ExecutableArchiveLauncher.<init>(ExecutableArchiveLauncher.java:38)
	... 2 more
```

**Comment by cstancu** [comment]
This issue is fixed on master. Although you can now build an image of `spring-petclinic` it will crash at run time as described above. Judging by the error message it looks like it tries to execute a jar which is currently not supported with `native-image`.
